### ISSUE TITLE
[Enhancement]: Improve Order Search Performance When HPOS is Enabled

### ISSUE THREAD

**Issue by robertstaddon** [woothemes/woocommerce#45721]
### Describe the solution you'd like

On sites with a large number of orders (e.g. 150k), the WooCommerce order search becomes considerably slower when HPOS is enabled and the search filter is in its default state of "All". This was a disappointment, as the expectation after enabling HPOS was that it would improve the speed of managing lots of orders in the WooCommerce admin. The cause of this problem is that the default "All" state of the search filter is an extremely expensive database query on sites with lots of orders.

This is noted in the following two tickets:
https://github.com/woocommerce/woocommerce/pull/43865#issuecomment-1988763021
https://github.com/woocommerce/woocommerce/issues/41317#issuecomment-1975186791

I would propose that we make the default state of the WooCommerce order search filter an option that is faster than "All". Perhaps one that searches similar order data as it did without HPOS enabled (when WooCommerce uses the default post meta tables)?

### Describe alternatives you've considered

A solution that might be easier to implement in the meantime would be a WordPress hook to allow a store owner to specify the default state of their store's order search filter. This would permit small stores to keep using "All" as their default but could allow larger stores to specify a different faster default order search filter (e.g. Customer).

Perhaps the best long-term solution would be a search that used a highly effective index to speed up the search query.

**Comment by shameemreza** [comment]
Another report here: 7904276-zen
Thread: https://wordpress.org/support/topic/order-seach-extremely-slow

**Comment by vedanshujain** [comment]
I am planning to investigate few approaches for this:
 - [x] Set default to the same search that post had, (which is similar to `All`, but it would preload valid orders based on filter before hand instead of filtering in the query). Seems like that worked better in actuality based on the reports we are getting, even though the query explainer would suggest that it's slower.
 - [x] Explore FTS for product and customer address search.
