### ISSUE TITLE
Introduce a new ExPlat experiment in 8.8: pre-publish modal

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#45736]
**Description:** As we prepare to release a batch of improvements, including the pre-publish modal, we'll keep the incremental approach and include a new experiment in 8.7.

**Acceptance criteria:**

- [x] Replicate the experiment running in 8.7. In sum, we should expose users who choose one of the following options in the "Add products" task: Physical product, Variable product, Digital product, Grouped product, and External product. 
- [x] Create the experiment P2. (feel free to ping me to review the draft)
- [x] Create the experiment in Abacus.
- [x] Add the segment to the WPCOM core.

**Comment by mattsherman** [comment]
Staged experiment created yesterday

**Comment by louwie17** [comment]
Closing all items above are done, just waiting to start it now.
