### ISSUE TITLE
[Enhancement]: Provide better feedback for Hiding shipping costs option when it is not available

### ISSUE THREAD

**Issue by wavvves** [woothemes/woocommerce#45754]
### Describe the solution you'd like

Currently, when Local pickup options powered by the Checkout block is being used the option to `Hide shipping costs until an address is entered` on `WooCommerce` > `Settings` > `Shipping` > `Shipping settings` displays the following:

![image](https://github.com/woocommerce/woocommerce/assets/17236129/9ff72dde-3846-4eb5-af83-43034aff2989)

This leaves the user unclear on what exactly is not available if he doesn't know that screen from memory. We should keep the option, disable it, and state why it is disabled.
This is just a (bad) example that would improve this:

![image](https://github.com/woocommerce/woocommerce/assets/17236129/814f5d48-579d-4a42-b1e0-d055d19f75ed)

### Describe alternatives you've considered

Remove the option altogether.

**Comment by pmcpinto** [comment]
I'll close this, as it will be fixed in #46022
