### ISSUE TITLE
Variable Products: Attibute is required error

### ISSUE THREAD

**Issue by olc01** [woothemes/woocommerce#45769]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When we create a set of variable products and use the "any Xxxxxx" on the dropdowns we are experiencing issues when users try to add the product to the cart.
The issue is also reported by another user here: https://wordpress.org/support/topic/error-attribute-is-required/ and doesn't seem to have been resolved,

### Expected behavior

If we add a product that has a range of colour variations, for example, but they all have the same price. Rather than adding a variation in WooCommerce product data for each colour, we just add one variation and select "any colour" on the dropdown. Then, whichever colour the user selects on the front end, the applicable price etc should apply.

### Actual behavior

Unless we put each and every variation into WooCommerce product data and don't use the "any xxxx" dropdown, we get reports of errors whereby customers cannot add the product to the cart.

### Steps to reproduce

Add a new product with two variable attributes (colour (2) and type (2)).
Create a variation for each type (2 product variations) and set the colour to "any colour" on both.
Then try to add the product to the cart and you will find that on occasions, the user will be unable to add the product to the cart as it will say the colour attribute is required.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by imanish003** [comment]
Hey @olc01, I tried to reproduce the issue but I was unable to reproduce it. I can see following text in the description:
> you will find that on occasions, the user will be unable to add the product to the cart as it will say the colour attribute is required.

It seems like this bug pops up only occasionally. I'm going to give it another try, but if you could share any specific steps or conditions that make this issue appear, that would be super helpful. Any extra details you provide can really make a difference in tracking down what's happening.

Questions: 
- Which theme you are using (classic or block)?
- Which template is used in case a block theme is used? (classic template, blockified template)
- Which plugins are enabled?
