### ISSUE TITLE
Using 'wp wc hpos cleanup all' leaves Orders pending sync

### ISSUE THREAD

**Issue by chvillanuevap** [woothemes/woocommerce#45777]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I recently migrated from the legacy order table architecture to the new HPOS system. After the change, I wanted to delete the old data remaining in wp_postmeta. I initially tried using the tool introduced in WC 8.7 (https://github.com/woocommerce/woocommerce/pull/43293), but then I saw there was a CLI tool (https://github.com/woocommerce/woocommerce/issues/40714). So I used this tool instead. It seems it worked well with the `wp_postmeta` table, as my number of rows went down from ~15M to ~6M. However, now the Features page says there are 358,703 orders pending sync. From what I can see, these orders have a `shop_order_placehold` post type.

<img width="1512" alt="Screen Shot 2024-03-20 at 10 15 26 AM" src="https://github.com/woocommerce/woocommerce/assets/3827771/661a6951-94d7-4d12-8ad5-24608eaba783">

Using `--force` didn't change things.

<img width="1512" alt="Screen Shot 2024-03-20 at 5 16 41 PM" src="https://github.com/woocommerce/woocommerce/assets/3827771/cd23e3e8-18f6-4f2f-b77c-611523cd9306">

<img width="1344" alt="Screen Shot 2024-03-20 at 10 15 08 AM" src="https://github.com/woocommerce/woocommerce/assets/3827771/78d154ff-6d3f-47a3-9d80-68523e2c8f99">

It also seems I can't use the Clean Up tool anymore either.

<img width="1342" alt="Screen Shot 2024-03-20 at 10 15 03 AM" src="https://github.com/woocommerce/woocommerce/assets/3827771/75b20b2a-ee77-4a0f-99ff-c1c5394733ff">

This issue was reported here as well: https://wordpress.org/support/topic/shop_order_placehold-post_type-and-deleting-these-rows/

Should I do what they did and simply remove all rows from `wp_posts` where `post_type=shop_order_placehold` directly in the database?

### Expected behavior

I expected all legacy data to be deleted and not to have 358,703 orders pending sync.

### Actual behavior

The data in 'wp_postmeta' was deleted correctly, but new data (or old data with a new post type) was placed in 'wp_posts'.

### Steps to reproduce

1. Migrate to the new HPOS system.
2. Use `wp wc hpos cleanup all` or `wp wc hpos cleanup all --force`.
3. See that new orders need syncing in WooCommerce >> Settings >> Advanced >> Features.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://thepostmansknock.com
Site address (URL): https://thepostmansknock.com
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: ❌ 6.3.3 - There is a newer version of WordPress available (6.4.3)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.14
PHP Post Max Size: 256 MB
PHP Time Limit: 43300
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.35-27
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Total Database Size: 10587.25MB
Database Data Size: 7205.63MB
Database Index Size: 3381.62MB
wp_woocommerce_sessions: Data: 23.06MB + Index: 1.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 187.72MB + Index: 253.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 87.61MB + Index: 20.55MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 725.98MB + Index: 461.77MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 35.06MB + Index: 30.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 15.05MB + Index: 13.03MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_sales: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 46.58MB + Index: 40.63MB + Engine InnoDB
wp_comments: Data: 183.70MB + Index: 163.48MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 1.52MB + Index: 0.11MB + Engine InnoDB
wp_gf_entry_meta: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hubwoo_log: Data: 82.09MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 130.47MB + Index: 2.13MB + Engine InnoDB
wp_oses_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_emails: Data: 48.02MB + Index: 1.02MB + Engine InnoDB
wp_oses_failures: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_popularpostsdata: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_popularpostssummary: Data: 9.52MB + Index: 11.55MB + Engine InnoDB
wp_popularpoststransients: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 4010.98MB + Index: 920.97MB + Engine InnoDB
wp_posts: Data: 200.67MB + Index: 67.23MB + Engine InnoDB
wp_pum_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sensei_pro_groups_courses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sensei_pro_groups_students: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 10.52MB + Index: 5.52MB + Engine InnoDB
wp_term_taxonomy: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_termmeta: Data: 22.55MB + Index: 21.09MB + Engine InnoDB
wp_terms: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_usermeta: Data: 442.98MB + Index: 220.42MB + Engine InnoDB
wp_users: Data: 21.55MB + Index: 14.55MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 15.52MB + Index: 18.08MB + Engine InnoDB
wp_wc_download_log: Data: 167.70MB + Index: 100.17MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_addresses: Data: 47.59MB + Index: 86.25MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_wc_order_operational_data: Data: 58.61MB + Index: 27.09MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 50.58MB + Index: 38.03MB + Engine InnoDB
wp_wc_order_stats: Data: 24.55MB + Index: 16.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_wc_orders: Data: 101.66MB + Index: 100.88MB + Engine InnoDB
wp_wc_orders_meta: Data: 327.91MB + Index: 725.98MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.16MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 91.61MB + Index: 3.50MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 2.52MB + Index: 0.63MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.14MB + Index: 0.25MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_links: Data: 7.52MB + Index: 3.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.23MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

_pods_field: 3
_pods_pod: 5
amp_validated_url: 456
attachment: 19439
bm_autoresponder: 1
bm_block_template: 362
bm_list: 6
bm_newsletter: 874
bm_newsletter_ares: 4
bm_newsletter_rss: 1
bm_template: 11
course: 18
ep-synonym: 1
faq: 17
feedback: 2
gallery: 8
global_product_addon: 1
jetpack_migration: 2
lesson: 92
nav_menu_item: 16
oembed_cache: 7
page: 61
popup: 2
popup_theme: 8
portfolio: 20
post: 963
product: 614
product_variation: 54
question: 233
quiz: 92
revision: 36
safecss: 1
scw_newsletter: 12
scw_newsletter_rss: 1
scw_template: 6
sendy_newsletter: 34
sensei_email: 19
shop_coupon: 1061
shop_order_placehold: 358707
sidebar: 7
slideshow: 3
supply: 21
ticket-meta-fieldset: 3
tribe_events: 21
tribe_organizer: 1
tribe_venue: 9
tribe_wooticket: 262
user_request: 19
wishlist: 11
wp_block: 1
wp_global_styles: 1
wp_navigation: 4
wpephpcompat_jobs: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (61) ###

Gravity Forms: by Gravity Forms – 2.8.5
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.2.1
AffiliateWP: by Sandhills Development
LLC – 2.6.6

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Attributes for Blocks: by websevendev – 1.0.5
Boldermail Connect for Gravity Forms: by Hernan Villanueva – 0.3.0
Boldermail Connect for WooCommerce: by Hernan Villanueva – 1.1.0
Boldermail: by Hernan Villanueva – 2.3.8
Cloudflare: by Cloudflare
Inc. – 4.12.6

CMB2: by CMB2 team – 2.10.1
Facebook for WooCommerce: by Facebook – 3.1.12
Google Listings and Ads: by WooCommerce – 2.6.3
Site Kit by Google: by Google – 1.122.0
Gravity Forms HubSpot Add-On: by Gravity Forms – 2.1.0
HTML Editor Syntax Highlighter: by James Bradford – 2.4.4
HubSpot WooCommerce HPOS Compatibility: by MakeWebBetter – 1.0.0
Smash Balloon Instagram Feed: by Smash Balloon – 6.2.9
Interact Quiz Embed: by The Quiz Collective Inc. – 3.1
Jetpack: by Automattic – 13.2.1
Live Cart by WP Engine: by WP Engine – 1.0.1
MWB HubSpot for WooCommerce: by MakeWebBetter – 1.5.3
Members: by MemberPress – 3.2.9
Pinterest for WooCommerce: by WooCommerce – 1.3.23
Popup Maker - Exit Intent Popups: by WP Popup Maker – 1.4.0
Popup Maker: by Popup Maker – 1.18.5
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.49
Redirection: by John Godley – 5.4.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
ReplyPress: by Hernán Villanueva – 2.1.0
Sensei LMS Course Progress: by Automattic – 2.0.4
Sensei LMS Media Attachments: by Automattic – 2.0.3
Shortcode Empty Paragraph Fix: by  – 0.2
Show Hidden Post Meta: by Philip Newcomer – 1.0.1
User Switching: by John Blackbourn & contributors – 1.7.3
Username Changer: by Widgit Team – 3.2.2
Woo Composite Products: by Woo – 9.0.1
WooCommerce Cost of Goods: by SkyVerge – 2.13.1
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.5.0
WooCommerce Dynamic Pricing: by Element Stark – 3.2.3
WooCommerce Featured Media: by Hernán Villanueva – 1.0.0
WooCommerce Affirm Gateway: by WooCommerce – 2.3.0
WooCommerce Stripe Gateway: by WooCommerce – 8.0.1
WooCommerce Order Status Control: by SkyVerge – 1.16.0
WooCommerce PayPal Payments: by WooCommerce – 2.6.0
Woo Product Add-ons: by Woo – 6.6.0 (update to version 6.8.0 is available)
Woo Product Bundles: by Woo – 7.0.1
WooCommerce Shipping & Tax: by WooCommerce – 2.5.3
WooCommerce Shipment Tracking: by WooCommerce – 2.4.2 (update to version 2.4.6 is available)
WooCommerce Smart Coupons: by StoreApps – 8.16.0 (update to version 8.18.0 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.6 (update to version 3.1.7 is available)
WooCommerce: by Automattic – 8.7.0
Sensei Pro (WC Paid Courses): by Automattic – 4.21.0.1.21.0
WordPress Popular Posts: by Hector Cabrera – 6.4.2
Yoast SEO Premium: by Team Yoast – 22.2
Yoast SEO: by Team Yoast – 22.2
WP Admin No Show: by Doug Sparling – 1.7.0
WP Crontrol: by John Blackbourn & crontributors – 1.16.1
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.6
WP Offload SES Lite: by Delicious Brains – 1.6.8
Yoast SEO: WooCommerce: by Team Yoast – 15.7
YITH Maintenance Mode: by YITH  – 1.9.0

### Inactive Plugins (1) ###

ElasticPress: by 10up – 5.0.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (6) ###

Courier: by Hernán Villanueva – 6.4.4
Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.3.0
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 10 MB

### WC Pages ###

Shop base: #4026 - /catalog/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #4028 - /checkout/
My account: #4029 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: The Postman's Knock
Version: 6.3.0
Author URL: https://thepostmansknock.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: thepostmansknock/templates/woocommerce/archive-product.php
thepostmansknock/templates/woocommerce/emails/email-downloads.php
/nas/content/live/thepostmanskck/wp-content/plugins/woocommerce/templates/block-notices/error.php
/nas/content/live/thepostmanskck/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/nas/content/live/thepostmanskck/wp-content/plugins/woocommerce/templates/block-notices/success.php
thepostmansknock/templates/woocommerce/order/order-downloads.php
thepostmansknock/templates/woocommerce/single-product.php
thepostmansknock/templates/order-confirmation.html
thepostmansknock/templates/page-checkout.html

### Composite Products ###

Database Version: 9.0.1
Loopback Test: ✔
Template Overrides: –

### Product Bundles ###

Database Version: 7.0.1
Loopback Test: ✔
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-21 17:48:43 -06:00
Options: ✔
Notes: 36
Onboarding: completed

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 2
Custom formats: 0
Next export: Not scheduled

### Action Scheduler ###

Canceled: 7
Oldest: 2024-03-07 11:34:46 -0700
Newest: 2024-03-19 11:44:06 -0600

Complete: 77,447
Oldest: 2024-02-18 17:01:31 -0700
Newest: 2024-03-20 17:24:42 -0600

Failed: 58
Oldest: 2024-02-22 14:36:12 -0700
Newest: 2024-03-20 13:54:23 -0600

Pending: 20
Oldest: 2024-03-20 17:27:31 -0600
Newest: 2024-03-21 13:54:31 -0600

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: no
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: no
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: no
Combine emails: no
Auto generated coupon email: yes
Combined auto generated coupons email: no
Acknowledgement email: yes
Enable taxes: yes
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: single
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: yes
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2024-03-20 17:26:57 -06:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @chvillanuevap!

Thanks for reaching out. Technically the message is correct: if you have used the cleanup tool, you have removed all the data associated to those orders from the posts table, so those orders are "pending sync" but that's only relevant if you actually _intend_ to change datastores back to the legacy one for any reason.

We are aware that the messaging can be confusing. This was also reported in #43268 and we will be looking for a way to remove the confusion.

> Should I do what they did and simply remove all rows from wp_posts where post_type=shop_order_placehold directly in the database?

Please don't. We're currently working on ways to allow this, but leaving the placeholders alone would be best for now. Given most order data is actually stored in postmeta, and this data is already handled by the cleanup tool, the post that remains is a very lightweight object.

* * * *

I'm closing this in favor of #43268, but please let me know if I have misrepresented something. Thanks again for the report!
