### ISSUE TITLE
Default Block Checkout - SHipping default text is a barrier to conversions, especially on mobile

### ISSUE THREAD

**Issue by martinmcshane** [woothemes/woocommerce#45796]
### Discussed in https://github.com/woocommerce/woocommerce/discussions/45338

<div type='discussions-op-text'>

<sup>Originally posted by **martinmcshane** March  6, 2024</sup>
Hi, on the block checkout or Woo. The default Shipping text is "No Shipping Options Available" shows, until the shopper enters their address/postcode.. where upon this changes.

This has been a proven barrier to a sale, as the customer is lead to believe that shop does not ship orders. Especially on mobile devises. I have tested this on a live store and 16 customers asked why I no longer shipped orders. 

The text should read "To be calculated" or "Enter address for shipping costs"...
Maybe even allow the shop owner to enter their own custom text via the Woo Shipping admin section

![Screenshot from 2024-03-06 11-30-46](https://github.com/woocommerce/woocommerce/assets/108077288/7a3df7ec-a58b-4aa4-b1d0-82eb31e01ee5)
</div>

**Comment by senadir** [comment]
Yeah! thank you for the valuable feedback, we will prioritize this issue, it's already reported here as well

https://github.com/woocommerce/woocommerce/issues/42124

Closing this as duplicate for now, do subscribe to the other one to see when it's fixed.
