### ISSUE TITLE
[Enhancement]: Checkout block to include option for setting account password, upon checking out

### ISSUE THREAD

**Issue by anastas10s-afk** [woothemes/woocommerce#45794]
### Describe the solution you'd like

The checkout block has a checkbox to opt for account creation upon checkout currently.
It could be useful to enhance this, by allowing password creation while checking out.
Moreover, the inclusion of an option with a clarification that guest checkout will occur otherwise, appears to assist in setting customer expectations while interacting with the Checkout block.

#hc

### Describe alternatives you've considered

As there are currently no such options available within the block's settings, it sounds worthwhile adding them, for the stores that need activating them.

### Additional context

With the Checkout block options, account password is possible only after opening the related email.

Related forum threads:
- https://wordpress.org/support/topic/create-an-account-doesnt-display-a-password-field/
- https://wordpress.org/support/topic/checkout-missing-username-password-custom-fields/

![Screenshot-from-2024-03-04-11-04-37](https://github.com/woocommerce/woocommerce/assets/73900974/1f1c2a4c-cea4-46f3-a3d5-d7ea85f708d9)
<img width="861" alt="Screenshot 2024-03-21 at 13 47 42" src="https://github.com/woocommerce/woocommerce/assets/73900974/7dcbc9e8-d32d-4379-9a64-c31ef5c5c572">
<img width="950" alt="Screenshot 2024-03-21 at 13 47 25" src="https://github.com/woocommerce/woocommerce/assets/73900974/27ab5aff-4880-44f8-b844-7df37d49aefa">
<img width="890" alt="Screenshot 2024-03-21 at 13 46 18" src="https://github.com/woocommerce/woocommerce/assets/73900974/0cfbe744-f760-4bf9-8240-9da22089d057">

**Comment by maxlaf** [comment]
Thanks for opening this @anastas10s-afk!

This is the same as #42430 which is part of this Epic #45144

I'm going to close this issue, but if it differs from the above, please feel free to reopen it.
