### ISSUE TITLE
"Product categories" block does not show all product categories when used in a product context

### ISSUE THREAD

**Issue by Prin-S** [woothemes/woocommerce#45819]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the **Product categories** block is used in a product context (e.g. the **Product Catalog** template), only some of the shop's product categories are shown. Tested with [Twenty Twenty-Four](https://wordpress.org/themes/twentytwentyfour/).

Note that the block has been set to show product categories.
![Screenshot 2567-03-22 at 12 06 47](https://github.com/woocommerce/woocommerce/assets/98200861/787b960b-c36e-4027-ad18-616d8a2d7425)

### Expected behavior

All product categories are shown.

### Actual behavior

Some product categories are shown.

For example, for a site with the following product categories, only **Music** is shown:
![Screenshot 2567-03-22 at 12 10 32](https://github.com/woocommerce/woocommerce/assets/98200861/d6353080-641a-42fd-a28d-e97b5d468f41)

![Screenshot 2567-03-22 at 12 11 46](https://github.com/woocommerce/woocommerce/assets/98200861/9f6aaa0f-6327-4194-88db-182887e2aef7)

### Steps to reproduce

1. Select a theme with full-site editing.
2. Go to **Appearance > Editor**.
3. Go to **Templates > Product Catalog**.
4. Edit the template. Add the **Product categories** block.
5. Save and view the site's shop page.

### WordPress Environment ###

WordPress address (URL): https://prinwp-test.mystagingwebsite.com
Site address (URL): https://prinwp-test.mystagingwebsite.com
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.16
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.6.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 42.15MB
Database Data Size: 26.77MB
Database Index Size: 15.38MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 5.02MB + Index: 1.97MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.02MB + Index: 1.45MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_cfw_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cfw_log_reserved: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.16MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.20MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 1.92MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.09MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_mnm_child_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 3.45MB + Index: 1.81MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 1.48MB + Index: 1.88MB + Engine InnoDB
__wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_cfw_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_cfw_log_reserved: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
__wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_options: Data: 2.06MB + Index: 0.14MB + Engine InnoDB
__wp_postmeta: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
__wp_posts: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
__wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
__wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_mnm_child_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
__wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
__wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wpml_mails: Data: 1.52MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

af_crt_order_rstrct: 1
af_wc_donat: 3
attachment: 29
aw_workflow: 12
bookable_person: 6
bookable_resource: 6
customize_changeset: 2
custom_css: 1
event_ticket: 4
page: 17
post: 1
product: 74
product_variation: 42
revision: 41
shop_coupon: 4
shop_order: 104
shop_order_refund: 8
shop_subscription: 42
wc_booking: 1
wc_user_membership: 1
wp_global_styles: 2
wp_navigation: 1
wp_template: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.6.1 (update to version 8.7.0 is available)

### Inactive Plugins (40) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
AutomateWoo: by WooCommerce – 6.0.17
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.3.30 (update to version 1.3.33 is available)
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.7.13 (update to version 2.7.16 is available)
Bookings Helper: by WooCommerce – 1.0.7
Cart and Order Restrictions: by Addify – 1.2.1
Check Conflicts: by ioannup – 1.1.6
Code Snippets: by Code Snippets Pro – 3.6.4
Customize My Account Page For Woocommerce: by WPEverest – 0.4.8
Custom Start Date For WooCommerce Subscriptions: by Launch & Sell – 1.3.14
Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
Jetpack: by Automattic – 13.3-a.5
Jetpack Protect: by Automattic - Jetpack Security team – 2.0.0
Loco Translate: by Tim Whitlock – 2.6.6
Pressable Cache Management: by Pressable CS Team – 4.2.4
Pressable OnePress Login: by Pressable – 1.3.2
Query Monitor: by John Blackbourn – 3.15.0
Say What?: by Ademti Software – 2.2.2
Self-service Dashboard for WooCommerce Subscriptions: by eCommerce Tools – 3.0.2
Woo All Products For Subscriptions: by Woo – 5.0.1
WooCommerce Bookings: by WooCommerce – 2.0.9 (update to version 2.1.0 is available)
WooCommerce Box Office: by WooCommerce – 1.2.5
WooCommerce Deposits: by WooCommerce – 2.2.4 (update to version 2.2.6 is available)
WooCommerce Memberships: by SkyVerge – 1.26.4
WooCommerce Photography: by Themesquad – 1.2.1
WooCommerce Product Vendors: by WooCommerce – 2.2.4 (update to version 2.2.6 is available)
WooCommerce Shipping Per Product v2: by WooCommerce – 2.5.5
WooCommerce Stripe Gateway: by WooCommerce – 8.0.0
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.5
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.7.0
WooCommerce USPS Shipping: by WooCommerce – 4.7.6 (update to version 4.8.2 is available)
Woo Gift Cards: by Woo – 1.16.10
WooPayments: by Automattic – 7.0.0 (update to version 7.3.0 is available)
Woo Product Add-ons: by Woo – 6.8.0
Woo Product Bundles: by Woo – 7.0.1
Woo Subscriptions: by WooCommerce – 6.0.0
WordPress Importer: by wordpressdotorg – 0.8.1
WP Crontrol: by John Blackbourn & crontributors – 1.16.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
competition (competition)
external (external)
grouped (grouped)
lottery (lottery)
mix and match (mix-and-match)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-22 13:27:00 +00:00
Options: ✔
Notes: 87
Onboarding: completed

### Action Scheduler ###

Complete: 6,904
Oldest: 2024-02-20 08:23:53 +0000
Newest: 2024-03-22 05:17:02 +0000

Pending: 15
Oldest: 2024-03-22 05:19:55 +0000
Newest: 2025-01-20 03:41:03 +0000

Failed: 605
Oldest: 2023-10-05 08:35:54 +0000
Newest: 2024-03-18 04:51:24 +0000

Canceled: 12
Oldest: 2024-02-22 09:03:01 +0000
Newest: 2024-03-22 03:22:08 +0000

### Status report information ###

Generated at: 2024-03-22 05:17:03 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Prin-S** [comment]
7926417-zd-a8c

**Comment by imanish003** [comment]
Hey @Prin-S,

I've conducted an initial investigation and discovered that the block in question isn't a WooCommerce block. Instead, it's included with Gutenberg as a variation of [Post Terms](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-terms/block.json), with these variations registered on the server side through a PHP file([here](https://github.com/WordPress/gutenberg/blob/f85d5c9de9507a78958d732c3d3d28a664bbe038/packages/block-library/src/post-terms/index.php#L115C1-L129C56)). I'll delve deeper into the issue within Gutenberg to understand why it’s not functioning as anticipated. However, it seems likely that we'll need to open an issue in the Gutenberg repository rather than in the WooCommerce repo. I'll keep you updated on my findings.

**Comment by imanish003** [comment]
On further debugging, I found out that [Post Terms](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-terms/block.json) is used for showing terms specific to a post. In case of, Product Categories, it’s supposed to show categories specific to a Product as can be seen in [this code](https://github.com/WordPress/gutenberg/blob/f85d5c9de9507a78958d732c3d3d28a664bbe038/packages/block-library/src/post-terms/index.php#L54-L60). Therefore, It’s showing Product Categories of only one Product based on the value of [$block->context['postId']](https://github.com/WordPress/gutenberg/blob/f85d5c9de9507a78958d732c3d3d28a664bbe038/packages/block-library/src/post-terms/index.php#L55).

**Comment by imanish003** [comment]
I'm closing this issue because it's related to the Gutenberg block. But if you have a good reason, I'm more than happy to reopen it.

**Comment by imanish003** [comment]
Related issue: #42391
