### ISSUE TITLE
Deleting a shop coupon via the API returns a 500 error even though it works

### ISSUE THREAD

**Issue by jcredland** [woothemes/woocommerce#45829]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The bug is fully described by another user in this stackexchange report:

https://stackoverflow.com/questions/77747153/faulty-error-response-from-woocommerce-rest-api-coupon-delete

He writes: ```Steps to Reproduce:

Create a new coupon (or use the id of an existing one).
Delete it with an http request to DELETE /wp-json/wc/v3/coupons/<id> as per the [WooCommerce Rest Api Documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#delete-a-coupon). The resulting response always seems to be
{
  "code": "woocommerce_rest_cannot_delete",
  "message": "The shop_coupon cannot be deleted.",
  "data": {
    "status": 500
  }
}
Even though the checking the coupons status, which is now trash, shows that the deletion was successful.

Did not find any record of this problem posted online. I tracked the problem to the Woo source code.

class-wc-rest-crud-controller.php

$object->delete();
$result = 'trash' === $object->get_status();
...
if ( ! $result ) {
    /* translators: %s: post type */
    return new WP_Error( 'woocommerce_rest_cannot_delete', sprintf( __( 'The %s cannot be deleted.', 'woocommerce' ), $this->post_type ), array( 'status' => 500 ) );
}
The above code looks ok, it’s reasonable that the status of the object should change to trash upon a successful call to $object->delete(); . However, looking closer at the code in WC_Coupon delete()

wp_trash_post( $id );
do_action( 'woocommerce_trash_coupon', $id );
The trashing of the coupon is accomplished with a global function which is independent of the WC_Coupon object that is saved in $object. Therefore the line from above $result = 'trash' === $object->get_status(); will always come back false.
```

### Expected behavior

A nice happy result code

### Actual behavior

Error 500.

### Steps to reproduce

Steps to Reproduce:

Create a new coupon (or use the id of an existing one).
Delete it with an http request to DELETE /wp-json/wc/v3/coupons/<id> as per the [WooCommerce Rest Api Documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#delete-a-coupon). The resulting response always seems to be
{
  "code": "woocommerce_rest_cannot_delete",
...

This can also be replicated by trying to delete a coupon with `wp wc shop_coupon delete <id>` which returns `Error: The shop_coupon cannot be deleted. {"status":500}` even though the coupon is moved to trash.

### WordPress Environment

`
### WordPress Environment ###

WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.44-48-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔


### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
Thanks for the report @jcredland. If you'd be inclined to submit a PR to fix this, we'd be happy to work with you on that.

**Comment by jcredland** [comment]
Thank for this (better you fixed this rather than me, my php is dangerous!)
