### ISSUE TITLE
Graduate Additional Fields API to stable.

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#45841]
Around 8.9, we should graduate the additional fields API to stable, this means:

- Updating docs.
- Updating function names.

We can consider doing this in a backward compatible way for now.

**Comment by webdados** [comment]
> We can consider doing this in a backward compatible way for now.

Yes, please throw a deprecation notice on the current `__experimental_woocommerce_blocks_register_checkout_field` function and keep it working for some time after renaming it.
