### ISSUE TITLE
Product Collection block - hand-picked items - limited to first 100 in catalog?

### ISSUE THREAD

**Issue by n9yty** [woothemes/woocommerce#45842]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When attempting to use a product collection block for hand-picked products, only the first 100 products are availble for selection, whether using the drop down list or searching. Searching only pulls from the items in the initial list.

### Expected behavior

I would expect to be able to use any products in the catalog, not only the first 100.

### Actual behavior

Only the first 100 products are available.

### Steps to reproduce

From our team member working on this:

I’m trying to get this set up to replace a Hand-Picked Products block—one where I’ve selected a few specific products I want to always show as great starting points for customers. The Product Collection block has a Hand-Picked Products filter but it’s only loading the first 100 products alphabetically. Even if I type in the box, it won’t load up any products past that first 100.

To reproduce:

1. Add the Product Collection (Beta) block to a page.
2. In the Filters section of the block controls, click the three dots and choose Hand-Picked Products
3. A box appears for selecting a product to feature. Search for something that’s not in the first 100 alphabetically.

### WordPress Environment

`
### Status report information ###

Generated at: 2024-03-22 10:17:46 -05:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by thealexandrelara** [comment]
Hey @n9yty, thank you for reporting this issue! I can confirm that I was able to reproduce the problem so I'm adding this to our backlog.

@kmanijak @imanish003 Do you know if there is a limit set on the Product Collection (Beta) block itself or if this is a WooCommerce limitation? I have a testing environment set up in here in case you need it ( see: 33f24-pb )

**Comment by imanish003** [comment]
@thealexandrelara AFAIK, There is no such limit. I will look into it today.

**Comment by imanish003** [comment]
Update: Fixed the issue in https://github.com/woocommerce/woocommerce/pull/45931
