### ISSUE TITLE
Variations with letter "ñ" causes issues

### ISSUE THREAD

**Issue by careboll-1982** [woothemes/woocommerce#45867]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

 When you create variations in spanish with the letter "ñ" and want to edit the variations list, the popup edit window removes all selected variations

### Expected behavior

Keep all variations selected without removing any when click on "edit" button

### Actual behavior

Deletes all selected variations and need to add them all again

### Steps to reproduce

1. Create a variation Ex: Age
2. Add a variations with ñ. Ex: 2 años, 3 años, 4 años
3. Create a product and add this variation with all the values list
4. Save
5. Click on "edit" the product variation list
6. The lists is empty

### WordPress Environment

6.4.2

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
Hi, @careboll-1982!
Thanks for opening this issue. I have not been able to reproduce it.
I have created an attribute with terms with the letter `ñ`. Then, I created variations for each of those terms in the product and everything seemed normal.
<img width="898" alt="Screenshot 2024-08-19 at 11 04 53" src="https://github.com/user-attachments/assets/8e21fa63-85d4-45bb-9c4d-1b5a04ee1f21">
Could you try again to see if you can still reproduce it? Could you maybe clarify what you mean by step `5. Click on "edit" the product variation list`?

Thanks a lot!
