### ISSUE TITLE
[Launch Your Store] Congrats page

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#45872]
## Description

Add a congrats page after store is launched by Launch Your Store task.

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/8d6811ac-5611-4c1c-98af-3af7c843e5c1)

Figma link: https://www.figma.com/file/0BWMerqRR1f468EwC7g5tg/LYS?type=design&node-id=1045-18473&mode=design&t=lEd2IUyQUCxvUKbj-4

## Acceptance Criteria
- Display animated confetti
- Provide button to copy URL
- Emoji feedback
- Dynamically display things to do next

**Comment by rjchow** [comment]
@ilyasfoo the congrats page sequence looks like a pretty large scope, if you haven't already started on the feedback bits what do you think of splitting that out?

**Comment by ilyasfoo** [comment]
@rjchow The feedback bits are already done, thanks for asking! It's manageable so far 👍
