### ISSUE TITLE
terugkerende klant? Klik hier om in te loggen   werkt niet

### ISSUE THREAD

**Issue by JeugdCentraleGKU** [woothemes/woocommerce#45870]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"terugkerende klant? [Klik hier om in te loggen](https://activiteiten.gku-pkn.nl/afrekenen/#)" werkt niet    de klanten worden niet teruggeleid naar de inlog pagina

### Expected behavior

teruggeleid naar de inlog pagina

### Actual behavior

"terugkerende klant? [Klik hier om in te loggen](https://activiteiten.gku-pkn.nl/afrekenen/#)" werkt niet    de klanten worden niet teruggeleid naar de inlog pagina

### Steps to reproduce

"terugkerende klant? [Klik hier om in te loggen](https://activiteiten.gku-pkn.nl/afrekenen/#)" werkt niet    de klanten worden niet teruggeleid naar de inlog pagina

### WordPress Environment

"terugkerende klant? [Klik hier om in te loggen](https://activiteiten.gku-pkn.nl/afrekenen/#)" werkt niet    de klanten worden niet teruggeleid naar de inlog pagina

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Kunt u een systeemrapport bijvoegen waarin u kunt zien welke versies u gebruikt en welke geïnstalleerde plug-ins er zijn?
