### ISSUE TITLE
[Launch Your Store] Site Visibility Settings Tracks Events

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#45873]
## Issue Description

There are concerns the save button is not obvious when using the Site Visibility settings. Add tracks events when:
* Users change the site visibility settings
* Save settings (does this already exist?)

**Comment by moon0326** [comment]
@adrianduffell 

> Users change the site visibility settings

Do we want to track it when the user clicks on the save button or whenever the user changes a value, regardless of whether they click the save button?

**Comment by adrianduffell** [comment]
> Do we want to track it when the user clicks on the save button or whenever the user changes a value, regardless of whether they click the save button?

@moon0326 I think it will need to be both of those events so a funnel can be created to learn the percentage of times the save button isn't used.

* whenever the user clicks on the save button
* whenever the user changes a site visibility value, regardless of whether they click the save button
