### ISSUE TITLE
[DOC-BUG] Customizing woocommerce_checkout_fields

### ISSUE THREAD

**Issue by TechnicallyWeb3** [woothemes/woocommerce#45882]
## Link to the Page/Section

> Provide a link to the specific page or section that you're referring to.
https://developer.woo.com/docs/customizing-checkout-fields-using-actions-and-filters/

## Description of the Suggestion

> Describe the changes you suggest to improve or correct the documentation. Be specific about any errors or areas of confusion you've identified.
While working in the new WooCommerce Checkout page in the new block mode I cannot use functions.php to modify fields using the documentation above, nor do any checkout page plugins work such as Flexible Checkout Fields.

I attempted using various modifications to my theme (twentytwentyfour) functions.php file with no luck. I could not remove or adjust requirement for fields. I had to revert to the classic WooCommerce Checkout page.

I suggest to update the documentation to reflect the new method or possibly write new docs about this topic and link them in the existing docs so anyone who finds themselves there doesn't also spend 5 hours trying to modify their checkout form only to realize it won't work on the new version (or maybe it should and this should be a bug report instead).

## Reason for the Suggestion

> Why do you believe this change will make the documentation clearer or more accurate?

I would like to see this work because the new checkout page is much more visually appealing in my opinion. I am also sure other people will want to modify their details.

## Additional Context

> Add any other context, references, or screenshots that support your suggestion.

I did notice some settings in the block editor, however, it did not allow me to remove all billing details. My store only accepts crypto as payment and billing addresses are not necessary and I feel will lead to cart abandonment issues.

**Comment by opr** [comment]
Hi @TechnicallyWeb3 thanks for reporting this, actually we have a discussion open for editing/removing fields.

https://github.com/woocommerce/woocommerce/discussions/42996

When we conclude this and start work on it, adding documentation for it will be part of the effort.

It'd be great if you could add your voice to that discussion so we have more uses cases to base our decisions on when it comes to working on it.

I'll close this as there's nothing actionable for us _right now_. Thanks again for the feedback.

**Comment by iwebxa** [comment]
Hi @lanej0
 
How to revert to the classic WooCommerce Checkout page? You mean switch to old version?
