### ISSUE TITLE
[Launch Your Store] Coming Soon WordPress Page

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#45900]
## Issue Description

Add a coming soon page to WooCommerce's official pages that get created upon installation. This page should work in the same manner as other official pages (see screenshot) to allow the coming soon page to be looked up by an ID, however full settings page integration is not required, but a "nice to have" at this stage.

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/677389b3-e87f-4041-a2b0-13db1bf4e69a)

This content of this page will be used to render a coming soon splash screen on the front-end. It should be populated with the pattern created in https://github.com/woocommerce/woocommerce/issues/45113

## Acceptance criteria

* Publish an coming soon WordPress page when WooCommerce is installed.
* For the benefit of existing sites, detect whether a coming soon page exists whenever the visibility setting changes to "coming soon". If the page doesn't exist, publish it.
* Allow the coming soon page's ID to be looked up (in a similar way to other official WooCommerce pages).
* Populate the coming soon page with a default coming soon pattern created in https://github.com/woocommerce/woocommerce/issues/45113

**Comment by moon0326** [comment]
This is partially done in https://github.com/woocommerce/woocommerce/pull/45773

**Comment by moon0326** [comment]
@adrianduffell Could you provide copy for the tooltip?



![Image](https://github.com/woocommerce/woocommerce/assets/4723145/fe4aea79-414f-4f3a-8d41-fddffcd801a7)

**Comment by adrianduffell** [comment]
> Could you provide copy for the tooltip?

@moon0326 We can use this:

`The page visitors are shown when the site visibility is set to "coming soon".`
