### ISSUE TITLE
Product Editor: Block switcher toolbar icon is present for blocks using toolbar, with Gutenberg 18.1

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#45908]
**Issue Description:**

With Gutenberg 18.1 (or trunk), a change was made in https://github.com/WordPress/gutenberg/pull/60010 that causes the block switcher toolbar icon to be present for blocks using the toolbar (such as summary and description), as well as a hover outline. 

**Gutenberg 18.1**

Summary:
<img width="1111" alt="Screenshot 2024-03-25 at 14 37 05" src="https://github.com/woocommerce/woocommerce/assets/2098816/a343cc07-1986-427e-8ea2-bb83a8d54000">

Descirption:
<img width="1111" alt="Screenshot 2024-03-25 at 14 37 38" src="https://github.com/woocommerce/woocommerce/assets/2098816/43d1fb07-2922-442b-a74f-b5dab6f0a9d2">

**Gutenberg 18 or older**

Summary:
<img width="1111" alt="Screenshot 2024-03-25 at 14 34 29" src="https://github.com/woocommerce/woocommerce/assets/2098816/770f9688-a440-4147-b366-9758618932cc">

Description:
<img width="1111" alt="Screenshot 2024-03-25 at 14 34 52" src="https://github.com/woocommerce/woocommerce/assets/2098816/bfcdc487-b040-48fb-8fa9-02d3dc921e62">

**Technical Considerations**

We could consider introducing a change upstream in Gutenberg to force the block switcher to never appear. Whether that would be welcomed is unknown. This certainly is yet another example of how assumptions on what a "block editor" is can make their way into packages such as `@wordpress/block-editor`. Or, perhaps we are making assumptions on what a "block editor" is, and we really shouldn't be using `@wordpress/block-editor` at all.

Another approach, which would be rather fragile and prone to future breakage, could be to use CSS to target and hide the block switcher toolbar icon.

**Comment by gigitux** [comment]
Could we close this issue?

**Comment by retrofox** [comment]
Yes, let's close the issue for now
