### ISSUE TITLE
Bug: Product form content is not aligned to the centre

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#45925]
We noticed during our recent user research interviews that the content of the form is not centred under the tabs. 
You can see the centre annotated with the big dashed line in the image below:

**Note:** This is specific to Atomic sites

Screenshot:

<img width="674" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/12d6e933-af35-432b-9ad9-41913e6cadd2">

<img width="1094" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/ab86d1c0-4e32-4675-986d-ba7dbe645b4c">

The green box shows where the content should be, the red box shows where the content is now. 
This bug is can be observed throughout all templates.

**Comment by louwie17** [comment]
@j111q is this still an issue? I can't reproduce this on a JN site.
Also in what version of WooCommerce is this?

**Comment by retrofox** [comment]
I see it properly centered too

<img width="1081" alt="image" src="https://github.com/woocommerce/woocommerce/assets/77539/dcf381b6-cf1b-4dce-8933-c159dc72ffd8">

**Comment by louwie17** [comment]
Update on the above two comments, this does seem to be something specific to Atomic sites

**Comment by octaedro** [comment]
I'm closing this issue because this error has been fixed on WC 8.9.
I thought it was still around because I had WC 8.8 installed on my test site, but after updating it wasn't reproducible anymore.
