### ISSUE TITLE
Add help text under `Include downloads` toggle

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#45921]
Through our recent user research, we noticed that a lot of users were unsure what `Downloads` referred to. 

We'd like to add some help text under the toggle to guide users on this feature. 

Copy:
`Add any files you'd like to make available for the customer to download after purchasing, such as instructions or warranty info.`

Mock-up when toggled/checked off:
<img width="689" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/4c0ef92e-b7d4-44f5-aef1-acb3c8996520">

Mock-up when toggled / checked on:
<img width="682" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/a35571cb-5d98-4108-8399-07ef21db9a93">

This change should be applied across all templates (Standard, Grouped, Affiliate).

**Comment by pmcpinto** [comment]
@octaedro is this going to be included in 9.0?

**Comment by octaedro** [comment]
Hi @pmcpinto,

> is this going to be included in 9.0?

Yes, it will be included. Code freeze for 9.0 will happen on May 22nd.

**Comment by pmcpinto** [comment]
👍 thanks for the clarification
