### ISSUE TITLE
Product Editor: Unable to save product if unedited properties are invalid

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#45957]
**Describe the bug**

Due to a regression introduced in #45436, non-dirty properties (those not edited in the product editor) are sent in the REST API request when the product is saved, causing the save to fail if those properties contain values that are not valid. 

This has been observed with extensions such as WooCommerce Product Bundles, which is not yet integrated with the new product editor in WooCommerce.

This results in errors such as the following:

```json
{
    "code": "rest_invalid_param",
    "message": "Invalid parameter(s): bundle_layout, bundle_add_to_cart_form_location, bundle_sold_individually_context, bundle_item_grouping",
    "data": {
        "status": 400,
        "params": {
            "bundle_layout": "bundle_layout is not one of default, tabular, and grid.",
            "bundle_add_to_cart_form_location": "bundle_add_to_cart_form_location is not one of default and after_summary.",
            "bundle_sold_individually_context": "bundle_sold_individually_context is not one of product and configuration.",
            "bundle_item_grouping": "bundle_item_grouping is not one of parent, noindent, and none."
        },
        "details": {
            "bundle_layout": {
                "code": "rest_not_in_enum",
                "message": "bundle_layout is not one of default, tabular, and grid.",
                "data": null
            },
            "bundle_add_to_cart_form_location": {
                "code": "rest_not_in_enum",
                "message": "bundle_add_to_cart_form_location is not one of default and after_summary.",
                "data": null
            },
            "bundle_sold_individually_context": {
                "code": "rest_not_in_enum",
                "message": "bundle_sold_individually_context is not one of product and configuration.",
                "data": null
            },
            "bundle_item_grouping": {
                "code": "rest_not_in_enum",
                "message": "bundle_item_grouping is not one of parent, noindent, and none.",
                "data": null
            }
        }
    }
}
```

**To Replicate**

With a WooCommerce dev env with the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**) and WooCommerce Product Bundles activated...

1. Go to **Products** > **Add New**
2. Enter a name
3. Click **Publish** > **Publish**
4. See **Failed to save product** toast message and error mentioned above in dev console. 

**Screenshots**

**Expected behavior**

Products can be saved in the new product editor even when extensions such as WooCommerce Product Bundles are installed.

**Comment by helgatheviking** [comment]
Following :)

**Comment by PanosSynetos** [comment]
@helgatheviking here's the draft PR too
- https://github.com/woocommerce/woocommerce/pull/45958
