### ISSUE TITLE
applying coupons in wc 8.8beta cart generates php deprecated error in wp core files (using PHP 8.1,any theme, no plugins, wp 6.4.3 & wp 6.5rc3))

### ISSUE THREAD

**Issue by Danielspain22** [woothemes/woocommerce#45956]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you apply a coupon in cart page using wc 8.8beta and php 8.1, every time you a apply one you'll get:
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /xxx.test/wp-includes/formatting.php on line 3557
This doesn't happen with php 8.0, i can't test with php 8.2. and 8.3, but 8.1 is still supported.

### Expected behavior

No errors in logs should be expected after applying a coupon

### Actual behavior

Using any theme(tried Neve and defaults like twenty twenty three, etc) with php 8.1 and wc 8.8beta applying coupons generates deprecated errors in logs.
If you apply a coupon using wc 8.8beta and php 8.1in cart page, every time you a apply one you'll get:
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /xxx.test/wp-includes/formatting.php on line 3557
This doesn't happen with php 8.0, i can't test with php 8.2. and 8.3, but 8.1 is still supported(8.1 is still as strong as 8.2 as wordpress stats suggests)  and some sites will be stuck in that version up to december 2024 when it gets out of official support . Also doesn't seem plugin conflict related...checked with all disabled but woocommerce too.
Happens with current wp 6.4.3 and wp 6.5rc3 (wp 6.5 final not released yet at time of this bug report)
Further note: it happens only when you apply coupon in the CART PAGE, not in the final checkout page clicking in the note: "Have a coupon? [Click here to enter your code]

### Steps to reproduce

Use php 8.1, latest wordpress, a default theme like twenty twenty three and wc 8.8 beta, apply a coupon and view your logs

### WordPress Environment ###

WordPress address (URL): https://xxx.test
Site address (URL): https://xxx.text
WC Version: 8.8.0
REST API Version: ✔ 8.8.0
Action Scheduler Version: ✔ 3.7.3
Log Directory Writable: ✔
WP Version: 6.5-RC3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.6.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

WC Database Version: 8.8.0
WC Database Prefix: wp_
Tamaño total de la base de datos: 311.91MB
Tamaño de los datos de la base de datos: 151.41MB
Tamaño del índice de la base de datos: 160.50MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 2.52MB + Índice: 0.50MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 22.56MB + Índice: 10.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.14MB + Índice: 0.07MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.09MB + Índice: 0.07MB + Motor InnoDB
wp_commentmeta: Datos: 0.34MB + Índice: 0.34MB + Motor InnoDB
wp_comments: Datos: 9.52MB + Índice: 10.09MB + Motor InnoDB
wp_duplicator_packages: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_litespeed_url: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_litespeed_url_file: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_options: Datos: 4.52MB + Índice: 0.30MB + Motor InnoDB
wp_postmeta: Datos: 53.59MB + Índice: 63.17MB + Motor InnoDB
wp_posts: Datos: 6.52MB + Índice: 3.83MB + Motor InnoDB
wp_sm_advanced_search_temp: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_stream: Datos: 0.00MB + Índice: 0.01MB + Motor InnoDB
wp_stream_meta: Datos: 0.00MB + Índice: 0.01MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.14MB + Índice: 0.09MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 8.52MB + Índice: 13.03MB + Motor InnoDB
wp_users: Datos: 1.52MB + Índice: 0.58MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.01MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.43MB + Índice: 0.34MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_orders: Datos: 4.52MB + Índice: 6.11MB + Motor InnoDB
wp_wc_orders_meta: Datos: 15.55MB + Índice: 37.22MB + Motor InnoDB
wp_wc_order_addresses: Datos: 3.52MB + Índice: 6.06MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.19MB + Índice: 0.32MB + Motor InnoDB
wp_wc_order_operational_data: Datos: 2.52MB + Índice: 3.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 1.31MB + Índice: 0.95MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.99MB + Índice: 0.58MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.00MB + Índice: 0.01MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.17MB + Índice: 0.42MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wpmailsmtp_debug_events: Datos: 0.08MB + Índice: 0.00MB + Motor InnoDB
wp_wpmailsmtp_tasks_meta: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wsal_metadata: Datos: 3.44MB + Índice: 1.96MB + Motor InnoDB
wp_wsal_occurrences: Datos: 2.48MB + Índice: 0.73MB + Motor InnoDB

### Post Type Counts ###

attachment: 341
customize_changeset: 2
nav_menu_item: 48
neve_custom_layouts: 3
page: 20
post: 2
product: 378
product_variation: 1026
revision: 305
shop_coupon: 75
shop_order: 13619
shop_order_placehold: 2
shop_order_refund: 21
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (11) ###

Contact Form 7: por Takayuki Miyoshi – 5.9.3
Duplicator: por Duplicator – 1.5.8.1
Neve Pro Addon: por ThemeIsle – 2.8.4
Advanced Order Export For WooCommerce: por AlgolPlus – 3.4.6
WooCommerce Beta Tester: por WooCommerce – 2.3.0
WooCommerce: por Automattic – 8.8.0-beta.1
WordPress Beta Tester: por Equipo de actualización/instalación de WordPress – 3.5.5
WP Crontrol: por John Blackbourn – 1.16.2
WP Mail SMTP: por WP Mail SMTP – 4.0.1
WP Activity Log: por Melapress – 4.6.4
WPFront Notification Bar: por Syam Mohan – 3.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: ARS (AR$)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog-2 (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
exclude-from-search-2 (exclude-from-search-2)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 días
Level threshold: –
Log directory size: 3 KB

### WC Pages ###

Base de la tienda: #4 - /productos-disponibles/
Carrito: #5 - /carrito/
Finalizar compra: #6 - /pago-de-compra/
Mi cuenta: #7 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://es.wordpress.org
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ❌ No declarada

### Templates ###

Overrides: /xxx.test/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/xxx.test/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/xxx.test/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2024-03-26 17:23:47 -03:00
Options: ✔
Notes: 3
Onboarding: completed

### Action Scheduler ###

Completo: 536
Oldest: 2024-02-24 18:32:50 -0300
Newest: 2024-03-26 11:16:15 -0300

Fallida: 7
Oldest: 2023-02-28 13:23:36 -0300
Newest: 2023-10-17 18:37:44 -0300

Pendiente: 3
Oldest: 2024-03-26 22:37:45 -0300
Newest: 2024-03-27 08:57:05 -0300

### Status report information ###

Generated at: 2024-03-26 11:19:24 -03:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
The origin seems to be this recent change:

https://github.com/woocommerce/woocommerce/pull/43872

Setting to `team: rubik` on that basis.
