### ISSUE TITLE
[Enhancement]: Block-based checkout input fields style updates

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46008]
This is a subticket of https://github.com/woocommerce/woocommerce/issues/44835, which has more context on the changes

- [x] Change fields outline to Universal / Border - Light. This affects fields that are currently outlined with black. No changes for dark mode.

![CleanShot 2024-02-21 at 10 46 13@2x](https://github.com/woocommerce/woocommerce/assets/99638528/da3ed806-2e9f-4044-9c53-1719fe550444)

- [x] Fields are a bit tall currently at 60px (see pic). Please check the 2JyXNimI4oGeJZhgQNZE9V-fi-2072%3A31996 for prescribed dimensions which is 50px tall. Minimized filled state label text size from 18px to 12px

![CleanShot 2024-03-04 at 14 28 06@2x](https://github.com/woocommerce/woocommerce/assets/99638528/1339793f-fad8-4f1b-bbf3-e761277bc9a0)

- [x] Add chevron icon to dropdown fields

![CleanShot 2024-03-04 at 14 32 02@2x](https://github.com/woocommerce/woocommerce/assets/99638528/61fa5236-b7c0-432c-bfbe-c635e95a4042)

- [ ] ~When checked, the checkbox must be filled with a color depending on global setting.~ This change needs to be discussed internally, as we're using checkboxes in various blocks and should ensure consistency. See also https://github.com/woocommerce/woocommerce/issues/46008#issuecomment-2102035395.

![CleanShot 2024-02-21 at 10 49 16@2x](https://github.com/woocommerce/woocommerce/assets/99638528/b4083ef6-3a75-4e32-b5f6-31de2318fb87)

**Comment by nielslange** [comment]
> Change fields outline to Universal / Border - Light. This affects fields that are currently outlined with black. No changes for dark mode.

@nikkivias Should the outline colours of the `:focus` state also be adjusted, or should they remain as they are? Here's a screenshot that shows the updated outline colours and the first field in the `:focus` state:

<img width="739" alt="Screenshot 2024-04-02 at 22 04 06" src="https://github.com/woocommerce/woocommerce/assets/3323310/9f828788-5381-4f85-b530-9d58fe1c260f">

**Comment by dominique-vias** [comment]
@nielslange Looks great! I would increase the weight of the focus borderline to 2px though.

**Comment by nielslange** [comment]
> @nielslange Looks great! I would increase the weight of the focus borderline to 2px though.

Thanks for your reply. @nikkivias. Just to double-check, shall the change of the outline color be applied to all input fields, thus, text input, checkboxes, radio boxes, etc. Or shall this change only affect the text inputs and the dropdown boxes? I'm asking as applying the same outline logic for focused input elements could create a consistent look. On the other hand, changing the outline color of checkboxes and radio buttons to Universal / Border - Light, might impact their visability. Below, I've created screenshots for both the regular and the focus states for checkboxes and radio buttons.

## Regular state of checkboxes

<table>
<tr>
<td valign="top">Outline "$universal-border-medium":
<br><br>
<img width="275" alt="Screenshot 2024-04-05 at 12 48 00" src="https://github.com/woocommerce/woocommerce/assets/3323310/22805fba-54a9-421c-a277-a99df14d17da">
</td>
<td valign="top">Outline "$universal-border-light":
<br><br>
<img width="267" alt="Screenshot 2024-04-05 at 12 45 13" src="https://github.com/woocommerce/woocommerce/assets/3323310/8d693daa-e237-4e63-85d2-9fae3f174d30">
</tr>
</table>

## Regular state of radio buttons

<table>
<tr>
<td valign="top">Outline "$universal-border-medium":
<br><br>
<img width="197" alt="Screenshot 2024-04-05 at 12 47 40" src="https://github.com/woocommerce/woocommerce/assets/3323310/53928978-0c45-4f67-b4c9-8453746df8fe">

</td>
<td valign="top">Outline "$universal-border-light":
<br><br>
<img width="199" alt="Screenshot 2024-04-05 at 12 46 46" src="https://github.com/woocommerce/woocommerce/assets/3323310/01cbbe09-3b69-4a1e-b451-1fb1ffd7b90f">
</td>
</tr>
</table>

## Focus state of checkboxes

<table>
<tr>
<td valign="top">1px outline on focus:
<br><br>
<img width="268" alt="Screenshot 2024-04-05 at 12 27 32" src="https://github.com/woocommerce/woocommerce/assets/3323310/3e0db7a5-6c96-48d6-9a00-66a23f328981">
</td>
<td valign="top">2px outline on focus:
<br><br>
<img width="277" alt="Screenshot 2024-04-05 at 12 27 48" src="https://github.com/woocommerce/woocommerce/assets/3323310/0385f581-714b-493c-a676-04d6baf9d536">
</td>
</tr>
</table>

## Focus state of radio buttons

<table>
<tr>
<td valign="top">1px outline on focus:
<br><br>
<img width="194" alt="Screenshot 2024-04-05 at 12 29 43" src="https://github.com/woocommerce/woocommerce/assets/3323310/e3406b0d-fc9a-4336-bf31-b76a796dc9f3">

</td>
<td valign="top">2px outline on focus:
<br><br>
<img width="203" alt="Screenshot 2024-04-05 at 12 30 00" src="https://github.com/woocommerce/woocommerce/assets/3323310/8c18c8ba-9aee-4916-a732-ded45df15e92">

</td>
</tr>
</table>

I've checked https://baymard.com/ for recommendations, but couldn't find any guidelines around that.

**Comment by nielslange** [comment]
I'm now working on the checkbox colors and the issue description says the following:
>  When checked, the checkbox must be filled with a color depending on global setting.

I'm not sure which global settings you are you referring to, @nikkivias. Are you referring to the text color? Here's a screenshot of what the checkbox would look like if the merchant selects the text color green:

### Selected state when not focused

<img width="272" alt="Screenshot 2024-04-09 at 13 31 39" src="https://github.com/woocommerce/woocommerce/assets/3323310/7f3746aa-121e-420a-bb3a-9bf96bc89285">

### Selected state when focused

<img width="264" alt="Screenshot 2024-04-09 at 13 31 54" src="https://github.com/woocommerce/woocommerce/assets/3323310/e4e09b45-7cf1-465a-9808-ba719131b3c1">

Apart from that, the first task in the issue description says:
>  Change fields outline to Universal / Border - Light. This affects fields that are currently outlined with black. No changes for dark mode.

As for the checkbox color, there's no note regarding dark mode. Does that mean that dark mode should be adjusted or shall the dark mode colors not be touched?

**Comment by dominique-vias** [comment]
hi @nielslange thanks for the mockups.. all of these look good to me but seeing the focused states now, maybe let's take it down a notch and use 1.5px instead.

> I'm not sure which global settings you are you referring to

I just meant to maintain wherever we are currently pulling the colors for selected states right now (which I assumed is part of the global colors?)

> As for the checkbox color, there's no note regarding dark mode. Does that mean that dark mode should be adjusted or shall the dark mode colors not be touched?

Actually, would you mind showing me what dark mode looks like for the entire checkout? The main thing we were doing for light mode was to decrease the contrast between fields and the background. Right now the black outlines in light mode create a harsh contrast against the background and as a result creates a busy looking interface. We want to make sure the experience isn't the same for dark mode.

![CleanShot 2024-04-09 at 15 17 53@2x](https://github.com/woocommerce/woocommerce/assets/99638528/eecb3322-0dac-4f00-bea7-17685b090d70)

**Comment by nielslange** [comment]
> hi @nielslange thanks for the mockups.. all of these look good to me but seeing the focused states now, maybe let's take it down a notch and use 1.5px instead.

Sure. I'll adjust the focus state to 1.5px. Should this change also affect the radio buttons and checkboxes or only the textual inputs?

> I just meant to maintain wherever we are currently pulling the colors for selected states right now (which I assumed is part of the global colors?)

Thanks for clarifying this. By selected state, you mean the focus state, correct? This screenshot shows the focused state of the country selector, which has a border color of #50575e. I've used this color for the background of the checked checkbox.

<img width="652" alt="Screenshot 2024-04-09 at 15 38 55" src="https://github.com/woocommerce/woocommerce/assets/3323310/0eece821-e285-4e36-ac39-1ba3ffa1775a">

> Actually, would you mind showing me what dark mode looks like for the entire checkout? The main thing we were doing for light mode was to decrease the contrast between fields and the background. Right now the black outlines in light mode create a harsh contrast against the background and as a result creates a busy looking interface. We want to make sure the experience isn't the same for dark mode.

Here are two screenshots of dark styles of the [Twenty Twenty-Four](https://wordpress.org/themes/twentytwentyfour/) theme.

<table>
<tr>
<td valign="top" width="50%">Maelstrom:
<br><br>

![store test_checkout_ (2)](https://github.com/woocommerce/woocommerce/assets/3323310/9bdb153f-e116-4d0b-8c45-c6b63b83d97a)

</td>
<td valign="top" width="50%">Onyx:
<br><br>

![store test_checkout_ (3)](https://github.com/woocommerce/woocommerce/assets/3323310/5a01627c-d000-489d-90c5-cfc5eb841927)

</td>
</tr>
</table>

**Comment by dominique-vias** [comment]
> Should this change also affect the radio buttons and checkboxes or only the textual inputs?

Yes, apply to radio and checkboxes.

Re: colors, I think I might have created confusion. We don't need to make any changes regarding colors.

Re: dark mode... Hmmm they don't appear visible at all. Is this a result of the change we made, or has it always been like this? It would be worth exploring how dark mode should appear.

**Comment by nielslange** [comment]
> Yes, apply to radio and checkboxes.

Thanks for clarifying this, @nikkivias.

> Re: colors, I think I might have created confusion. We don't need to make any changes regarding colors.

OK. So we do not change the border color of the input elements, but we do set the outline width for all input elements (text input, textarea, checkbox, and radio button) to 1.5px, correct?

> Re: dark mode... Hmmm they don't appear visible at all. Is this a result of the change we made, or has it always been like this? It would be worth exploring how dark mode should appear.

By _"they don't appear visible at all"_, are you referring to the checkboxes, which I mentioned in https://github.com/woocommerce/woocommerce/issues/46008#issuecomment-2044247918, or are you referring to all input elements? 

It also seems that you've overseen this question in https://github.com/woocommerce/woocommerce/issues/46008#issuecomment-2044468990:
> [...] _By selected state, you mean the focus state, correct? This screenshot shows the focused state of the country selector, which has a border color of #50575e. I've used this color for the background of the checked checkbox._

This question was regarding the color of the selected checkboxes. Currently, it's not clear to me if the focus color (dark grey for light mode / white for dark mode) should be applied or another color.

**Comment by nielslange** [comment]
@nikkivias In https://github.com/woocommerce/woocommerce/issues/46008#issuecomment-2044292337, you mentioned:

> hi @nielslange thanks for the mockups.. all of these look good to me but seeing the focused states now, maybe let's take it down a notch and use 1.5px instead.

I just saw @opr PR https://github.com/woocommerce/woocommerce/pull/46525, in which he changed the borders width of the  selected shipping and payment method from 1.5px to 2px, to prevent pixel issues on high-res displays. Based on this issue, I believe we should go with 2px, to prevent this issue from happening again. Would you agree to that?

**Comment by dominique-vias** [comment]
Hi @nielslange

### Re: focus states

let's do 2PX as well if the same pixelation issue occurs

![CleanShot 2024-05-06 at 16 42 11@2x](https://github.com/woocommerce/woocommerce/assets/99638528/483f6e98-9a11-4127-9890-05e2a771cb8a)

### Re: dark mode

I would like to clarify this statement:

> Hmmm they don't appear visible at all. Is this a result of the change we made, or has it always been like this? It would be worth exploring how dark mode should appear.

I requested a view of what dark mode looks like so I can see if we need to recommend changes. You provided me with the below photos, and I noticed that the outline of most components (highlighted in red) are barely visible. I wanted to clarify if this is a result of the color changes we made for the light mode.

Although I should note that the checkbox and radio button outlines are more visible, but creates too much contrast against the background.

![CleanShot 2024-05-06 at 16 45 53@2x](https://github.com/woocommerce/woocommerce/assets/99638528/da24aae5-037d-4fdf-bdcd-5292d682169c)

I would love your guidance on how to approach this, as I want a uniformed look for all borders/outlines that has the right amount of contrast against the background (visible but not too much)

**Comment by nielslange** [comment]
> let's do 2PX as well if the same pixelation issue occurs

Thanks for confirming this, @nikkivias.

> I requested a view of what dark mode looks like so I can see if we need to recommend changes. You provided me with the below photos, and I noticed that the outline of most components (highlighted in red) are barely visible. I wanted to clarify if this is a result of the color changes we made for the light mode.

Based on the issue description _"Change fields outline to Universal / Border - Light. This affects fields that are currently outlined with black. No changes for dark mode."_, I have not applied any changes to the dark mode. The outline colors in dark mode, that you mentioned, might be the result of https://github.com/woocommerce/woocommerce-blocks/pull/11474.

**Comment by dominique-vias** [comment]
In that case, we will have to resolve Dark mode separately.

**Comment by nielslange** [comment]
> In that case, we will have to resolve Dark mode separately.

Let's do this, @nikkivias. This also ensures that the issues are easier to implement and to test.

**Comment by nielslange** [comment]
@nikkivias and I discussed the designs of the checkboxes and the radio buttons, as proposed in https://github.com/woocommerce/woocommerce/issues/46008#issuecomment-2095387512. As these elements are used in various places, we agreed that @nikkivias would bring this change up in an internal discussion to involve all teams that are affected by such a change.

cc: @ralucaStan & @pmcpinto

**Comment by pmcpinto** [comment]
Thanks for the update. Should this issue be moved to blocked again?

**Comment by nielslange** [comment]
I'd rather finalise the issue without changing the design of the checkboxes and radio buttons. If we want to change their designs, we can create a separate issue for that later. Does that sound good to you, @pmcpinto?

**Comment by pmcpinto** [comment]
Ok 👍

**Comment by senadir** [comment]
I recently updated the colors of the labels to make them accessible. Part of this PR https://github.com/woocommerce/woocommerce/pull/47470 to handle this issue https://github.com/woocommerce/woocommerce/issues/43619

If we're going to modify text color here let's make sure it's contrasting above 4.5 (and ideally 7)

**Comment by nielslange** [comment]
> I recently updated the colors of the labels to make them accessible. Part of this PR #47470 to handle this issue #43619
> 
> If we're going to modify text color here let's make sure it's contrasting above 4.5 (and ideally 7)

Thanks for mentioning this, @senadir. This PR only changes outline colors, though. It does not touch text colors. But I'll double-check the text colors to ensure that their contrast ration is above 4.5.
