### ISSUE TITLE
[Enhancement]: Block-based checkout shipping options updates

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46009]
This is a subticket of https://github.com/woocommerce/woocommerce/issues/44835, which has more context on the changes

Currently, Shipping options, pickup options and payments options are styled differently. We want to use a consistent style for options.

- [x] Use consistent style for "options"

- [x] Add a border around selection option
2JyXNimI4oGeJZhgQNZE9V-fi-2053%3A2911
<p align="center">
<img src="https://github.com/woocommerce/woocommerce/assets/99638528/7b667df9-ede1-48e4-87a2-bb857f9edb14" alt="First Image Description" width="400" />
<img src="https://github.com/woocommerce/woocommerce/assets/99638528/d5991bff-e1a2-46e7-8975-fe22256b20ec" alt="First Image Description" width="400" />
</p>

- [x] If single option only, apply the same styling, instead of simple text

![CleanShot 2024-02-21 at 10 55 54@2x](https://github.com/woocommerce/woocommerce/assets/99638528/cc4e6cd3-2757-49a5-94bb-9d44639162e7)

**Comment by opr** [comment]
@nikkivias should this border also apply to selected payment methods? It's the same component used for both

**Comment by opr** [comment]
@nikkivias hi! In the cart it is possible to select shipping methods too (see bottom right). Should we update the shipping selectors there, or leave them as is? My concern is the additional spacing required to accommodate the border. The space is a little narrow already.

<img width="900" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/2965d8d7-0e96-4ed0-b1e0-04d56c4aeebe">

**Comment by opr** [comment]
Reopening, this was closed by the "main" PR but there are still outstanding issues:

https://github.com/woocommerce/woocommerce/pull/46284
https://github.com/woocommerce/woocommerce/pull/46345 <-- Needs design feedback cc @nikkivias

**Comment by dominique-vias** [comment]
@opr the tagged issue that needs my feedback has been reviewed. Should we unblock this issue?

**Comment by opr** [comment]
@nikkivias thanks for checking - yes I think we can.

Actually, could we even close it? There is one task on this ticket that says:

>  Use consistent style for "options"

Do you consider this complete based on the results of https://github.com/woocommerce/woocommerce/pull/46284 and https://github.com/woocommerce/woocommerce/pull/46345?

**Comment by dominique-vias** [comment]
It looks like they now employ the same styling— just wanted to check though why in payment options, the selected item's text is bolded?

![CleanShot 2024-05-06 at 22 52 59@2x](https://github.com/woocommerce/woocommerce/assets/99638528/5de9c115-450e-4292-9db4-5dcebca96f66)

**Comment by opr** [comment]
Hi @nikkivias it's always been that way actually it wasn't modified as part of this effort. Should I un-bold the selected payment method so it's consistent with the shipping methods? I think it's pretty easy do to that.

**Comment by dominique-vias** [comment]
Yes let's remove the bold on select :) Thank you!
