### ISSUE TITLE
[Enhancement]: Checkout Shipping options empty states

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46014]
This is a subticket of #44835

- [ ] Visually enhance styling to communicate "empty" and call attention to the action required 2JyXNimI4oGeJZhgQNZE9V-fi-2072%3A31996

![CleanShot 2024-02-21 at 10 54 38@2x](https://github.com/woocommerce/woocommerce/assets/99638528/3a254a04-5864-41d5-8a7e-bce773413659)

**Comment by nielslange** [comment]
> - [ ] Visually enhance styling to communicate "empty" and call attention to the action required 2JyXNimI4oGeJZhgQNZE9V-fi-2072%3A31996

![CleanShot 2024-02-21 at 10 54 38@2x](https://github.com/woocommerce/woocommerce/assets/99638528/3a254a04-5864-41d5-8a7e-bce773413659)

@nikkivias I was wondering if we should re-use the existing `<NoticeBanner>` component, for consistency-reasons, before introducing a new design element. 

### Default notice banner

<img width="696" alt="Screenshot 2024-03-29 at 14 45 03" src="https://github.com/woocommerce/woocommerce/assets/3323310/ac37c08c-ff99-4baf-bf77-a3e8653c6bca">

### Info notice banner

<img width="697" alt="Screenshot 2024-03-29 at 14 46 25" src="https://github.com/woocommerce/woocommerce/assets/3323310/1a99959d-e112-4383-9d14-41856625a40e">

### Warning notice banner

<img width="703" alt="Screenshot 2024-03-29 at 14 46 56" src="https://github.com/woocommerce/woocommerce/assets/3323310/99b69012-ac93-4bb8-8333-d475108777fa">

**Comment by dominique-vias** [comment]
Hey @nielslange good question and I appreciate the suggestion. However, using a notice component might not send the right message, even if we used the default option. Because this component is used to _inform_ them of something, It would appear as if something went wrong when they've _just_ entered the flow.

We are trying to communicate 'empty' or 'none', so the new design is visually subdued and acts more like a skeleton / placeholder.

**Comment by nielslange** [comment]
> We are trying to communicate 'empty' or 'none', so the new design is visually subdued and acts more like a skeleton / placeholder.

Thanks for clarifying this, @nikkivias.

**Comment by ralucaStan** [comment]
closing, this will be handled in https://github.com/woocommerce/woocommerce/issues/46949
