### ISSUE TITLE
[Enhancement]: Block-based checkout - Pickup section updates

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46012]
This is a subticket of https://github.com/woocommerce/woocommerce/issues/44835, which has more context on the changes. c8VYjXqluE9vlVSE1RgJix-fi-34%3A527

- [x] Rename “Local pickup options” to "Pickup locations".
- [x] Show all pickup location addresses by default.
- [x] Only show the pickup details of the selected pickup location.
- [x] Truncate the pickup details after two lines.

<img width="1456" alt="Default   Empty" src="https://github.com/woocommerce/woocommerce/assets/99638528/595a5531-b4c4-4065-820b-0c6ff678cc51">

**Comment by ralucaStan** [comment]
>  Rename “Local pickup options” to “Pickup points”

I am worried about using the word `points`. Merchants use the term `location` when adding them
<img width="1009" alt="Screenshot 2024-04-17 at 16 34 55" src="https://github.com/woocommerce/woocommerce/assets/1628454/be9ada10-a516-4fb2-8f07-a2d3c1eeda04">
to avoid confusion, should we use `Pickup locations` instead of `Pickup points`?

I also want to highlight that this label can be changed in the Editor. So whatever we choose is a default, but merchants can change that.
<img width="610" alt="Screenshot 2024-04-17 at 16 38 48" src="https://github.com/woocommerce/woocommerce/assets/1628454/d47119b3-f97e-4f8a-981c-6df8ed8c21fb">

@nikkivias there are no details about the surface area for this change.

Order confirmation

<img width="778" alt="Screenshot 2024-04-17 at 16 41 16" src="https://github.com/woocommerce/woocommerce/assets/1628454/2e715ad7-3d6c-4125-8dc3-ab20422871fe">

>  Show addresses by default, not just on selection

<img width="623" alt="Screenshot 2024-04-17 at 16 36 09" src="https://github.com/woocommerce/woocommerce/assets/1628454/3b5ced76-a6da-4ac1-ada4-8daaacea8ecb">

We show those addresses by default in the editor, but using dummy data. We should update the look and feel in the editor as well and followup with using the merchant defined addresses. What do you think @pmcpinto 

-------

once we define the expected outcome I recommend splitting this ticket

**Comment by dominique-vias** [comment]
Ah nice, thanks for showing me that. It would be good to reflect what is in the admin— `Pickup locations` it is then!

> I also want to highlight that this label can be changed in the Editor. So whatever we choose is a default, but merchants can change that.

No problem.

> there are no details about the surface area for this change.

I mentioned this in another issue #42422 but it looks like we will need to update the Summary labels to Delivery as well, including in the Order confirmation.

**Comment by pmcpinto** [comment]
> to avoid confusion, should we use Pickup locations instead of Pickup points?

Good catch. +1 on using locations. Out of curiosity, Shopify uses points and locations. [Example](https://shopify.dev/docs/api/functions/reference/pickup-point-delivery-option-generator).

> We show those addresses by default in the editor, but using dummy data. We should update the look and feel in the editor as well and followup with using the merchant defined addresses. What do you think @pmcpinto

It makes sense to show the real address. But I'd treat it as a separate issue.

**Comment by ralucaStan** [comment]
Thank you both:
to wrap up:
- use `Pickup locations` instead of `Pickup points`; @nikkivias the design needs to be updated, could you update the image in the ticket?
- we'll handle showing the merchant defines pickup locations in the editor in a separate ticket

> I mentioned this in another issue https://github.com/woocommerce/woocommerce/issues/42422 but it looks like we will need to update the Summary labels to Delivery as well, including in the Order confirmation.

@nikkivias Could you explain the expected result in more detail? Will the Shipping label on the Order confirmation page be updated to `Delivery` for everyone, or just for people using Local pickup?

@nikkivias seems I missed this part:

> Opens a pop up modal to show full text (Explore if modal is feasible)

Why did you favor a modal over showing the full text? I don't expect to have huge amounts of text there to require a modal. Just showing the full text should be enough. 

We also don't have  modal usage in our checkout blocks and I feel we should be wary when considering introducing one.

**Comment by dominique-vias** [comment]
> Could you explain the expected result in more detail? Will the Shipping label on the Order confirmation page be updated to Delivery for everyone, or just for people using Local pickup?

I was hoping we would officially change it to Delivery so the wording doesn't need to change whether they pick `Ship` or `Pickup`. Apart from the visualizations [in this file](https://www.figma.com/file/c8VYjXqluE9vlVSE1RgJix/WooCommerce-Cart-%26-Checkout?type=design&node-id=0%3A1&mode=design&t=841XUQV0civ24Oj6-1), I could mockup all the places where the changes need to happen.

> here are no details about the surface area for this change.

Can you clarify what you meant here @ralucaStan ? Do you mean where else are we going to make the name change?

> seems I missed this part about the modal

We were previously discussing displaying the policies page in a modal so that they don't have to exit checkout to view them. I wanted to reuse that behavior in other places where a large amount of text will need to be displayed. But I agree it may not be needed here and expanding the card will suffice.

I updated the main image in the issue and removed the modal requirement from the task lists.

**Comment by ralucaStan** [comment]
> Can you clarify what you meant here @ralucaStan ? Do you mean where else are we going to make the name change?

Yes, exactly; So if we are to stay with `Pickup locations` then we aren't changing anything in the Admin, only in the merchant and the shopper views. The label does not surface on the Order confirmation.

**Comment by nielslange** [comment]
@ralucaStan The issue description says
>  Show a Pickup location's addresses by default, not just on selection
and
> Truncate a Pickup location's addresses text after two lines with more link

The design, shows that the pickup details and not the pickup location address is truncated. This raises two questions:

1. As per design, we do want to truncate the pickup details and not the pickup address, correct?
2. Apart from displaying the pickup location constantly, shall we also constantly display the pickup details, or shall they appear only when the corresponding pickup option is selected?

cc: @pmcpinto and @nikkivias

**Comment by pmcpinto** [comment]
> As per design, we do want to truncate the pickup details and not the pickup address, correct?

Yes.

> Apart from displaying the pickup location constantly, shall we also constantly display the pickup details, or shall they appear only when the corresponding pickup option is selected?

They should only appear when the corresponding option is selected to declutter the experience and decrease the cognitive load. 

cc @nikkivias

**Comment by nielslange** [comment]
> They should only appear when the corresponding option is selected to declutter the experience and decrease the cognitive load.

Thanks for clarifying this, @pmcpinto. As that change is pretty straight-forward, I'll apply it right away. If @nikkivias or @ralucaStan should have any objections, it's pretty easy to revert.
