### ISSUE TITLE
[DOC-BUG] WooCommerce Checkout Blocks API add field only for billing address

### ISSUE THREAD

**Issue by davide75** [woothemes/woocommerce#46029]
## Link to the Page/Section

Referring to this: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/additional-checkout-fields.md#available-field-locations

## Description of the Suggestion

> I need to add some fields to address location, but I need that only in billing section of address, and not in shipping. Currently if I add fields to address the same field will appear in shipping and billing section, but for fields like 'VAT Number' that's not good

## Reason for the Suggestion

 I know I could add my custom fields to additional information location, but I think it should be better, also for the user experience, to give the possibility to add a field only in billing or shipping section of address.

**Comment by opr** [comment]
Hi there @davide75 thanks a lot for the feedback.

Having the address fields appear in both shipping _and_ billing was a deliberate choice.

We discussed this quite a bit in the discussion for this feature - https://github.com/woocommerce/woocommerce/discussions/42995

We know that this is something merchants and developers would like to do so we will keep it in mind for future iterations on the feature, but for the time being it's not something we will enable.

The `contact` section is probably your best choice.

I'll close this issue as there's nothing actionable for now, but please feel free to add your voice to the discussion.
