### ISSUE TITLE
[Enhancement]: Product Collection Block - the Hand-Picked filter shows only the first 100 products for selection and search

### ISSUE THREAD

**Issue by shameemreza** [woothemes/woocommerce#46058]
### Describe the solution you'd like

When you activate the Hand-Picked Filter in the Product Collection Block, it shows only the first 100 products for selection. Even when you search, the results stem only from these initial 100 products.

Ideally, you should have the option to expand this selection list. Alternatively, the search results should encompass all the products, not just the first 100.

Tested and replicated the issue using the below:

- WC 8.7.0
- PHP  8.1.27
- Twenty Twenty-Four theme

![CleanShot 2024-03-29 at 16 45 53](https://github.com/woocommerce/woocommerce/assets/14240438/08e6d4d6-add8-48df-9c1c-0ee987d21fd0)

### Additional context

Reported here: 7928899-zen
Thread link: https://wordpress.org/support/topic/product-collection-block-hand-picked-only-first-100-items

**Comment by kmanijak** [comment]
This has been fixed in https://github.com/woocommerce/woocommerce/pull/48379

**Comment by GterB** [comment]
I'm running into the same behavior in Wordpress 6.6.2, WooCommerce version 9.3.2
I have used the Product Collection Block to show the ‘[On Sale](https://muraadshop.nl/sale/)‘ products, but only the first 100 are shown.

**Comment by kmanijak** [comment]
Hey @GterB!

I checked your page and I can see `... data-query="{"perPage"100, ...` on Product Collection block which most likely means that's the setup from the Editor.

To change that, please enter the Editor, focus on the Product Collection block and check the "Display Settings" in Toolbar options. Most likely "Items per page" will say 100.

<img width="653" alt="image" src="https://github.com/user-attachments/assets/fd0c57d0-de0d-426d-9c00-b82358a1ef80">

I can think of two options to fix it:
- you can put `0` which simply means "Show all available products". The downside is that if you have too many products, rendering them all may impact the performance of your page.
- so to make browsing more convenient for shoppers, you can include Pagination block. To do that:
    - insert "Pagination" block in scope of Product Collection/On Sale block (see screenshot below)
    - change "Max page to show" for Product Collection to `0` to show all of the pages
    - change "Items per page" to number of products per page you want to display. You can keep 100 if you want or decrease it to make browsing products easier

<img width="1267" alt="image" src="https://github.com/user-attachments/assets/dbf190f8-b822-4ac8-989a-3f83be1616d0">

Let me know if that helps and if my instructions make sense! 🙌

**Comment by GterB** [comment]
Hi @kmanijak ,

Thank you for explaining so thoroughly! It was indeed set to 100.
Sadly the options you described don't work:
- Setting it to 0 is not accepted, minimum is 1. Also, it won't accept >100
- Pagination is not a standard block but a paid extension. Once I have the lot up and running we will probably have the whole shop revamped by a professional, but for now it's just 'hobby', so I won't be investing too much money to get the quirks ironed out. 

Glad I learned something today, many thanks!

Regard,

Gerard

**Comment by kmanijak** [comment]
> Setting it to 0 is not accepted, minimum is 1. Also, it won't accept >100

@GterB, ugh, my bad! 😬 But I guess that's a bug and we should allow for it. I created a draft PR to fix it but need to consult it with my colleagues first. CC: @ObliviousHarmony, @imanish003, what do you think, should we allow putting `0` in Items per page which would simply show ALL of the products from collection?

> Pagination is not a standard block but a paid extension. Once I have the lot up and running we will probably have the whole shop revamped by a professional, but for now it's just 'hobby', so I won't be investing too much money to get the quirks ironed out.

Hmm.. [Pagination is a core block](https://wordpress.org/documentation/article/pagination-block/), coming from Gutenberg, and is available for free in every WordPress instance. It's restricted in terms of ancestors, meaning that it won't appear in the inserter anywhere, only in specific places. It should appear when trying to insert when INSIDE Product Collection block:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/267dc0ad-829d-47f4-ace9-44c18ac94e14">

**Comment by GterB** [comment]
That was quite the search! Clicking the + sign in the upper left (indicated with the arrow) does not work, I specifically needed to click the + sign in the lower right of the Product Collection Block (circled), and that plus sign only appears when _clicking_ the block.
![image](https://github.com/user-attachments/assets/dd86693a-c367-432c-ae2f-1233cb730c3d)

Anyway, I got it working, Thank you for the info,

Regards, Gerard
