### ISSUE TITLE
Woocommerce removes the current-menu-item class

### ISSUE THREAD

**Issue by Marc-pi** [woothemes/woocommerce#46060]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In case of WooCommerce usage, the current-menu-item class is removed

see this PR https://github.com/woocommerce/woocommerce/pull/45095

### Expected behavior

Woo must not remove the classes, especially the current-menu-item that permits to style any selected entry

### Actual behavior

We cannot style the current entry within the menu
the WP current-menu-item class is removed

### Steps to reproduce

1. Use TT4 theme
2. Add a navigation
3. Observe that the current-menu-item-class is not present in case you click on a menu entry
4. Works in case no woocommerce entry is there in the navigation bar

### WordPress Environment

WP 6.4.3 
Woo 8.7
TT4

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> Observe that the current-menu-item-class is not present in case you click on a menu entry

@Marc-pi Thanks for reporting this issue. Could you clarify where this occurs so that we can try to reproduce the issue?

**Comment by Marc-pi** [comment]
By default, the WP Navigation block generates the current-menu-item class (it permit us to highlight the current page within the navigation menu, through css style)
If you add any woocommerce link within the navigation block (as entry, like a category page), the class is deleted
see the above PR that fixes this, you'll understand
Woo must not alter any WP Feature, only extend it

**Comment by roykho** [comment]
From my testing, I am seeing the `current-menu-item` class for most of the navigation (Cart, Checkout, My Account) except for `Shop`. Is that what you're referring to @Marc-pi ?

**Comment by Marc-pi** [comment]
yep.
it's very frequent to add `category pages` within the menu entries, most of the case as top parent entry
once you add any woocommerce page, the wp current-menu-item class is removed, so we cannot style (hightlight) the current area where the user is / navigated to
btw i did not test to add a product page within the nav, but who knows...
have a look at the PR, he founds the culprit

**Comment by Marc-pi** [comment]
seems there is a workaround on gutenberg 18.2 on this but for Post Archive
https://github.com/WordPress/gutenberg/pull/57808
Here we are more on Page Archive for the CPT product-category

**Comment by Marc-pi** [comment]
@coreymckrill any news about the fix ? seems not validated yet

**Comment by coreymckrill** [comment]
@Marc-pi unfortunately I don't have an estimate for when the linked PR will be reviewed and merged. cc @vedanshujain

**Comment by vedanshujain** [comment]
Seems like I missed this in my queue, will take a look this week.

**Comment by Marc-pi** [comment]
@vedanshujain don't forget to validate this, thx

**Comment by Marc-pi** [comment]
ok, works well / 9.2, thx
