### ISSUE TITLE
HPOS: Misaligned fields for order search filters on the Orders list table screen

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#46074]
On the HPOS version of the Orders list table screen, there's an extra dropdown field on the search form. It doesn't align quite right with the text input and the button, at least in Firefox:

![search-form](https://github.com/woocommerce/woocommerce/assets/916023/07448aa9-db92-44cb-8731-7c43ca336d18)

## Steps to replicate

1. Make sure HPOS is authoritative.
2. Go to WooCommerce > Orders and check the search form in the upper right corner.

**Comment by jorgeatorres** [comment]
Hey @coreymckrill!

Thanks for the report. We've already logged this in the past. I'm closing this issue in favor of #44129, but will transfer the `good first issue` label, which makes perfect sense in this case. Thanks again!
