### ISSUE TITLE
[Launch Your Store] Tour

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#46070]
## Issue Description

Add a tour for existing users to learn about the homescreen status badge.

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/63220070-1809-42f5-866b-0c992e44f2b6)

[Figma](https://www.figma.com/file/0BWMerqRR1f468EwC7g5tg/LYS?type=design&node-id=858-51429&mode=design&t=4PLoT5Yi0FirrY1j-4)

## Acceptance Criteria

* The tour should be activated when the WooCommerce plugin is updated and the previous version was `< 8.9`. Perhaps an option needs to be set in the [db update functions](https://github.com/woocommerce/woocommerce/blob/56ca4e3f3ccb0d2c0fbaf815ba1ec1d333855fc7/plugins/woocommerce/includes/wc-update-functions.php).
* The tour should appear on the homescreen until it has been dismissed with the close button
* The tour should not appear when a site switches from coming soon to live.

**Comment by moon0326** [comment]
@adrianduffell Do we link `Discover more` to the settings page?

**Comment by adrianduffell** [comment]
> Do we link Discover more to the settings page?

@moon0326 good question -- it will link to documentation on woo.com that isn't ready yet. We can link this to something like `#` for now.

**Comment by adrianduffell** [comment]
This was reverted in https://github.com/woocommerce/woocommerce/pull/47005. It will need to be re-instated for the 9.0.0 release.

**Comment by adrianduffell** [comment]
Re-instated with #47603
