### ISSUE TITLE
wc_get_orders() unexpected behavior with legacy orders, field_query and meta_query ignored

### ISSUE THREAD

**Issue by Sartoric** [woothemes/woocommerce#46076]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using the wc_get_orders() function to retrieve orders when the "legacy" option is selected lead to potential unexpected behavior, since the *_query arguments are simply ignored/missing in the final SQL.

At least update the [documentation](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query) as it's misleading 

`wc_get_orders and WC_Order_Query provide a standard way of retrieving orders that is safe to use and will not break due to database changes in future WooCommerce versions. `

### Expected behavior

Working the same way it works when using HPOS

### Actual behavior

the *_query (at least meta and field) are not used and all the orders are returned.

### Steps to reproduce

- create an $args set that includes a meta_query or a field_query array to filter the orders
- run the wc_get_orders() and check the number of orders returned 

### WordPress Environment

Wordpress 6.4.3
WooCommerce 8.7.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @Sartoric!

Even though both `field_query` and `meta_query` are specifically documented as HPOS-only (and so not subject to backwards compatibility), we understand this can be confusing.
We've discussed on the team, and regardless of the work in #37564, we think it'd be good to indicate the use of unsupported properties via a `_doing_it_wrong()` and possibly returning no orders (as you've suggested).

As such, I'm bumping priority on this issue and we'll take a look soon.
