### ISSUE TITLE
Payment method renders delayed on Checkout block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46086]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using a non-default payment method, e.g. [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/), if the payment method is slow to load (e.g. if it runs a synchronous request on a slow network) rendering is delayed for all other payment methods on the Checkout block.

### Expected behavior

I expect the payment methods to be rendered almost instantly.

### Actual behavior

The payment methods render after approx. 7s.

### Screen recording of the Checkout block:

![Screen Capture on 2024-04-01 at 19-25-55](https://github.com/woocommerce/woocommerce/assets/3323310/5a75b6d0-43f1-4eea-8131-d7dc38a41c81)

### Screen recording of the shortcode checkout:

![Screen Capture on 2024-04-01 at 19-27-50](https://github.com/woocommerce/woocommerce/assets/3323310/a08300d4-13b5-4f6a-8f97-a04388def3ed)

### Steps to reproduce

1. Install and activate the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) plugin.
2. Go to the frontend.
3. Add a product to the cart.
4. Go to the checkout page using the Checkout block.
5. See that the payment methods render delayed.
6. Force refresh the page, to see the issue better.
7. Go to the checkout page using the shortcode checkout.
8. See that the payment methods render almost instantly.

### WordPress Environment

<details>
<summary>System Status Report </summary>

```
### WordPress Environment ###

WordPress address (URL): https://store.test
Site address (URL): https://store.test
WC Version: 8.9.0
REST API Version: ✔ 8.9.0
Action Scheduler Version: ✔ 3.7.3
Log Directory Writable: ✔
WP Version: 6.5-RC3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.4
PHP Version: 8.1.27
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.6.0
(SecureTransport) OpenSSL/3.2.1

SUHOSIN Installed: –
MySQL Version: 8.3.0
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.0
WC Database Prefix: wp_
Total Database Size: 6.19MB
Database Data Size: 4.43MB
Database Index Size: 1.76MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 22
page: 11
post: 16
product: 18
product_variation: 7
revision: 9
shop_order_placehold: 4
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 8.1.0
WooCommerce: by Automattic – 8.9.0-dev

### Inactive Plugins (2) ###

Query Monitor: by John Blackbourn – 3.15.0
Simple Custom CSS and JS: by SilkyPress.com – 3.46

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 108 KB

### WC Pages ###

Shop base: #54 - /products-beta/classic-shop/
Cart: #56 - /cart/
Checkout: #57 - /checkout/
My account: #60 - /my-account/
Terms and conditions: #61 - /terms/

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/nielslange/Plugins/woocommerce/plugins/woocommerce/templates/block-notices/error.php
/Users/nielslange/Plugins/woocommerce/plugins/woocommerce/templates/block-notices/notice.php
/Users/nielslange/Plugins/woocommerce/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-04-02 06:00:36 +00:00
Options: ✔
Notes: 75
Onboarding: -

### Action Scheduler ###

Complete: 154
Oldest: 2024-03-19 05:58:20 +0000
Newest: 2024-04-01 12:25:50 +0000

Failed: 2
Oldest: 2024-03-27 17:33:01 +0000
Newest: 2024-03-28 13:48:08 +0000

Pending: 2
Oldest: 2024-04-01 23:38:31 +0000
Newest: 2024-04-02 11:38:31 +0000


### Status report information ###

Generated at: 2024-04-01 12:29:09 +00:00
```

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
@nikkivias we discussed in slack that you ideally want this solved a different way (either keep the current behavior or show a loader) instead of waiting for payment methods one by one.

**Comment by dominique-vias** [comment]
Hi @senadir @nielslange Yes a loader would be good, because the current behavior where it just suddenly appears isn't very elegant. But if I'm understanding it right, because it is at the bottom at the page, the shopper wouldn't really see the awkward transition? Or does it lazy load?

![Image](https://github.com/woocommerce/woocommerce/assets/99638528/4d64cbf1-afe6-40bd-9233-ba062301b8d1)

I also propose a cleaner and much nicer looking solution that we can consider as part of optimizing the default experience. Not only does it emphasize the existing options and declutter the UI, but it also solves the delayed rendering issue as it doesn't need to be shown at all at page load. Only when relevant. Let me know what you think cc: @ralucaStan @pmcpinto 

![Image](https://github.com/woocommerce/woocommerce/assets/99638528/e912e22f-dd8e-49a6-ad67-e25208020139)

**Comment by nielslange** [comment]
> Hi @senadir @nielslange Yes a loader would be good, because the current behavior where it just suddenly appears isn't very elegant. But if I'm understanding it right, because it is at the bottom at the page, the shopper wouldn't really see the awkward transition? Or does it lazy load?

@nikkivias If a seller purchases a virtual product, all shipping-related sections will not appear. On a big screen, the payment options will be visible immediately:

<img width="1279" alt="Screenshot 2024-06-10 at 16 54 01" src="https://github.com/woocommerce/woocommerce/assets/3323310/83319438-4c60-4afc-bf14-4d72edd9656a">

> I also propose a cleaner and much nicer looking solution that we can consider as part of optimizing the default experience. Not only does it emphasize the existing options and declutter the UI, but it also solves the delayed rendering issue as it doesn't need to be shown at all at page load. Only when relevant. Let me know what you think cc: @ralucaStan @pmcpinto

Baymard states that some sellers abandon a checkout if their desired payment method is not available. If payment options are hidden behind a link, sellers might not know that their preferred way to pay is actually available.

**Comment by senadir** [comment]
@nielslange they would only be hidden if the customer has a saved payment method so technically their preferred payment method is always there.

**Comment by nielslange** [comment]
> @nielslange they would only be hidden if the customer has a saved payment method so technically their preferred payment method is always there.

I'm aware of that, @senadir, but what if a seller used the credit card before and now wants to use PayPal, which would be hidden behind a link? A seller could easily oversee PayPal in such a case.

**Comment by senadir** [comment]
If they're no longer accepting credit cards, then the saved credit cards won't show and a customer will directly see the actual payment step.

**Comment by senadir** [comment]
There's a small possibility that a customer used 1 payment method now and wants to change it (previously used CC and now wants to use PayPal) but I'd not optimize the minority and create extra friction/steps for the majority. Most people will benefit from having less steps to look at.

**Comment by senadir** [comment]
![image](https://github.com/woocommerce/woocommerce/assets/6165348/2397570c-8874-4d14-abc7-96afbf6de330)

@nikkivias it's unlikely that we can go with this (I will look into it) because currently it's not possible to separate saved payment methods from new ones, since they're controlled by the same source.

FWIW the delay right now is a payment method making a request to see if it can present itself (along with its saved methods).

**Comment by dominique-vias** [comment]
I understand @senadir  Thanks for the discussion here folks. @nielslange would you mind sharing the Baymard link? I'd like to investigate this further.

**Comment by nielslange** [comment]
@nikkivias I sent you the link to Baymard via Slack.

**Comment by pmcpinto** [comment]
> I also propose a cleaner and much nicer looking solution that we can consider as part of optimizing the default experience. Not only does it emphasize the existing options and declutter the UI, but it also solves the delayed rendering issue as it doesn't need to be shown at all at page load. Only when relevant. Let me know what you think cc: @ralucaStan @pmcpinto

@nikkivias this is an interesting idea, but I think it should be a separate issue, as it requires more deliberation. Thanks

**Comment by opr** [comment]
I don't believe this issue should be blocked anymore, so I am moving it back into the backlog. This issue seems to have been blocked waiting for design feedback, however it has arrived, and I think the solution Nikki proposed is great, but does not address the case when a user has no saved payment methods. This issue is still valid and should still be looked at.

@senadir I have unassigned you.

**Comment by senadir** [comment]
Just to be clear, this is the outcome you're looking for @nikkivias ?

![Image](https://github.com/woocommerce/woocommerce/assets/99638528/e912e22f-dd8e-49a6-ad67-e25208020139)
