### ISSUE TITLE
WC_Order_Factory::get_order() returns invalid orders from cache

### ISSUE THREAD

**Issue by prettyboymp** [woothemes/woocommerce#46128]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Related to #45550 

When using order cache, if SQL replication lag is present, `WC_Order_Factory::get_order()` will return an invalid order object ($id===0) instead of `false`.

Because WC_Data objects are serialized to only include the $id, Orders have their constructor re-run when being unserialized after being retrieved from cache.  When this happens, if the DB data for the given order does not exist, the Order will set it's ID to `0` and finish it's construction.

However the order cache loading in `WC_Order_Factory` doesn't account for this:

https://github.com/woocommerce/woocommerce/blob/561a3d18c562834eb058283f08d8b3563b58ed70/plugins/woocommerce/includes/class-wc-order-factory.php#L37-L40

If the object were not cached at all, `false` would be returned if replication lag were still present because of the $classname check below:

https://github.com/woocommerce/woocommerce/blob/561a3d18c562834eb058283f08d8b3563b58ed70/plugins/woocommerce/includes/class-wc-order-factory.php#L43-L46

### Expected behavior

The following line should also check that `$order->get_id() !== 0` before returning the `$order`, otherwise, return `false` since we already know the order wasn't able to be read. https://github.com/woocommerce/woocommerce/blob/561a3d18c562834eb058283f08d8b3563b58ed70/plugins/woocommerce/includes/class-wc-order-factory.php#L38-L40

### Actual behavior

Orders with an ID of `0` are returned.

### Steps to reproduce

Write a custom script that will do the following:
1. Load a valid order through `WC_Order_Factory::get_order()` to have it cached.
2. Run a query directly against the orders table to remove the row from the DB to mimic replication lag.
3. Attempt to reload the same order from step 1 through `WC_Order_Factory::get_order()`.

### WordPress Environment

WPCOM

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thanks for the report, @prettyboymp. If you have time and interest, we'd definitely be receptive to a PR. 

Also, to help us gauge priority, can you indicate what sort of functional problems you are seeing (what the severity/impact is, in the environments where you see this)? We understand the problem you are describing, but are just looking for insights about the real world impact to help us assess priority relative to other issues.

**Comment by prettyboymp** [comment]
> Also, to help us gauge priority, can you indicate what sort of functional problems you are seeing (what the severity/impact is, in the environments where you see this)? We understand the problem you are describing, but are just looking for insights about the real world impact to help us assess priority relative to other issues.

Overall this is probably a pretty rare scenario. The impact for us is as follows:

1. A user purchases are subscription which triggers a webhook to an outside service.
2. That service then triggers a webhook back to Woocommerce to connect that subscription to a specific resource.
3. Occasionally, when the subscription is retrieved from the Order Factory, the ID of the subscription is set to 0 instead of the ID we were searching for.

Replication lag being high enough for two remote requests to occur is somewhat rare, but with enough volume, does affect a couple subscriptions a week.

**Comment by barryhughes** [comment]
Perfect, thank you for sharing :+1:
