### ISSUE TITLE
[Enhancement]: Customize Receipt Rendering output

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#46122]
### Describe the solution you'd like

I just tested how a Mix and Match product appears in the Receipt Rendering engine.... and it's very difficult to tell which products are part of the mix and match pack/bundle:

![image](https://github.com/woocommerce/woocommerce/assets/507025/a8c6c958-5734-440a-a565-c57a0bca0c4b)

In the cart, order, email contexts I am able to add some customization to import the bundled products. Here's an example of the cart. 
![image](https://github.com/woocommerce/woocommerce/assets/507025/f5c5079e-5880-4916-9e88-abe07e6daf6a)

Looking at the [`order-receipt.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/ReceiptRendering/Templates/order-receipt.php) template.... there are currently no extensibility points to alter the output at all. 

So I think I would like to see similar filters to the `order-details-item.php` template which uses the [`woocommerce_order_item_class`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/order/order-details-item.php#L26) ) (which is also used in the admin AND in emails if I remember correctly.

HTML emails also offer a [`woocommerce_email_styles`](https://github.com/woocommerce/woocommerce/blob/ed3febb948f78ef98fe75cf9dbca80399e52e00e/plugins/woocommerce/includes/emails/class-wc-email.php#L607) hook where we can insert some custom CSS.

I suspect both would be required to get the bundled items to indent. 

### Describe alternatives you've considered

There aren't extensibility points, so the only alternative is do nothing.

**Comment by PanosSynetos** [comment]
Following, as this affects (at least) Product Bundles too

**Comment by Konamiman** [comment]
Hi, please confirm if a filter with the following design would work:

- It accepts two arguments: the formatted line item in HTML (minus the `<tr>` tags, so starting with `<td>...`) and an array with information about the line item.
- The array contains the line item type (being `product` one of the possible types), the title, the amount, and when it's a product line item, the quantity and the product id.
- The filter returns the new HTML for the line item (expected to start with `<td>...` too).

**Comment by helgatheviking** [comment]
I think that's more than what I need as I don't particularly need to insert any content... at most I might insert an arrow icon or something. I'd like to see `woocommerce_order_item_class` on the `<tr>` element. And then the ability to add some CSS.

**Comment by Konamiman** [comment]
Ok, if it's <i>more</i> than you need and not <i>less</i>, we're good. If I'm going to implement customization I want to add enough flexibility for any future needs.

**Comment by dave-green-uk** [comment]
We're in the process of doing discovery on a printing feature for a product of ours that I would love to build on top of this feature.

The key things would be the ability to use a filter to [modify the order data params](https://github.com/woocommerce/woocommerce/pull/43502/files#r1481037822) and support for [overriding receipt templates](https://github.com/woocommerce/woocommerce/blob/ed3febb948f78ef98fe75cf9dbca80399e52e00e/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php#L122).

More granular filters as suggested above, as well as the ability to contribute basic styles to the template would be super useful!

**Comment by helgatheviking** [comment]
>Ok, if it's more than you need and not less, we're good.

Well it is less in that it's not what _I_ need. I think it could be handy for some users, but fairly certain I don't need that part in particular. 

To dig in just a tiny bit...

```
<tr class="<?php apply_filters( 'woocommerce_order_item_class', '', $line_item, $order ); ?>"><td><?php echo $line_item['title']; ?> × <?php echo $line_item['quantity']; ?></td><td><?php echo $line_item['amount']; ?></td></tr>
```

Unfortunately doesn't work right out of the box as the `$line_items` array you are looping through is an array of arrays (with no way to detect product types or order item meta) and not an array of `WC_Order_Item` objects. But still, this is the gist of what I'm hoping for.

**Comment by PanosSynetos** [comment]
We'll come back with some requirements from @woocommerce/somewherewarm 's end, but I just thought that we'd definitely need RTL support here.

For example `Title x 2` would be `2 x Title` in RTL
