### ISSUE TITLE
Unable to activate WC dependent plugins on live branches

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#46169]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I install WC using the Live Branches, I am unable to activate the dependent plugins, such as WooPayments. The error message shows, `This plugin cannot be activated because required plugins are missing or inactive.`

![Screenshot 2024-04-03 at 16 47 31](https://github.com/woocommerce/woocommerce/assets/4344253/3d7d3fb5-fd47-41a3-9b07-2e1a795f2533)

This is caused by this [this](https://github.com/Automattic/woocommerce-payments/commit/ee235db25ba088a9f97158abab68152e0f417f2a#diff-ad243b7f0e0ae2cc54963fec106a5c54ece9c5bb8b272acaeece1836d71418a2R15) change in the woocommerce-payments plugin. WP 6.5 introduced a new [plugin dependency feature](https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/), and WooPayments just used it.

It is not possible to activate the plugin because the `woocommerce` folder is named `wc_beta_tester_live_branch_8.9.0-dev-*`.

We can rename the folder name to `woocommerce` to activate it.

We could also use the new filter mentioned in the [post](https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/) . If we can get the current slug, maybe something like:
add_filter( 'wp_plugin_dependencies_slug', 'convert_woocommerce_slug' );

```php
function convert_woocommerce_slug( $slug ) {
	if ( 'woocommerce' === $slug ) {
		$slug = 'wc_beta_tester_live_branch_8.9.0-dev-8533900737-g40be78c';
	}
	return $slug;
}
```

### Expected behavior

Can activate WooPayments.

### Actual behavior

Can't activate WooPayments.

### Steps to reproduce

1. Install WC using wc beta tester live branch
2. Go to wp-admin/plugins.php
3. Install `WooPayments`
4. See the error

### WordPress Environment

WP 6.5

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
cc  @woocommerce/vortex since this is related to tooling in monerepo.

**Comment by adrianduffell** [comment]
@tammullen I escalated this to critical because it blocks @woocommerce/ghidorah's testing workflows. I can take the issue if your prefer.

**Comment by tammullen** [comment]
Thanks @adrianduffell, reach out to the team on Slack if you need assistance

**Comment by csmcneill** [comment]
I'm finding that this can also affect WooAF, as the folder is named `woocommerce-accelerated-frequency`.
