### ISSUE TITLE
[Enhancement]: REST API disable wp-admin sign-in

### ISSUE THREAD

**Issue by thewho2018** [woothemes/woocommerce#46165]
### Describe the solution you'd like

On the new REST API settings you assign a account to the REST API. I would like to disable that user just so it cannot login to wp-admin. When writing this i think maybe this is something wordpress need to fix?

Does this user need to be Administrator?

**Comment by barryhughes** [comment]
Hi @thewho2018,

I'm closing this, as described above. I did also want to leave a few preliminary ideas:

- You could perhaps use your own account, or another suitable existing user account, to generate the key, then share the key but not any of the account details?
- Or, you might create a new user account with the appropriate role, but use an artificial email address and, again, share the key with whichever person or service needs it but not the details of the user account.
- Beyond that, if you need fine grained control over things, you could consider exploring a custom solution: there are lots of hooks through which you can exert control.

Thanks!

**Comment by thewho2018** [comment]
> Hi @thewho2018,
> 
> I'm closing this, as described above. I did also want to leave a few preliminary ideas:
> 
>     * You could perhaps use your own account, or another suitable existing user account, to generate the key, then share the key but not any of the account details?
> 
>     * Or, you might create a new user account with the appropriate role, but use an artificial email address and, again, share the key with whichever person or service needs it but not the details of the user account.
> 
>     * Beyond that, if you need fine grained control over things, you could consider exploring a custom solution: there are lots of hooks through which you can exert control.
> 
> 
> Thanks!

Hi Barryhughes.

In Microsoft Business Central they call this "Device user" if i understood it correctly. And this is to integrate to a Microsoft Nav2018 so a bit to old for a modern connector. so REST API was the only way to go.

But i made a user called "REST API" and that user has a password for wp-admin where that very user should have no way to access so that password will never be shared and no one will over sign into it unless it has been hacked/leeked.

I thought this function would be used for example when REST API updates quantity or trackingnumber on a order, stuff like that it would be logged and who changed the product or order last time so then it would be better to have a specified username instead of my username.

**Comment by thewho2018** [comment]
So just be clear. not a support request. For me i just wanted to contribute somehow. Just give some input and from what i have seen while researching Microsoft Business Central they do that very thing but call it "Device User". But then again i could be wrong.

**Comment by barryhughes** [comment]
Associating API keys with users is part of the current permissions model. Changing this, or adding to it, would require careful consideration.

I'm a little unsure if the 'Device User' you are describing is a sort of artificial user (no user record actually exists), or just a user that is explicitly prevented from accessing certain areas  (in this case, the wp-admin area)?

**Comment by jobthomas** [comment]
@thewho2018 can correct me if I'm wrong, but it seems that the specific use case here is where 3rd party solutions rely on getting API keys to connect to Woo, but without an easy way to restrict access: it's either the keys to the whole store (incl. changing passwords) or no access at all. 

E.g. when using a migration tool and you only want to move the store details over, the solutions doesn't need admin access, just read/write to products, orders and customers.

**Comment by barryhughes** [comment]
> Without an easy way to restrict access

So it's definitely true that, at present, it is not easy to generate API keys with specific grants. 

For instance, generating an API key that allows a service to interact with the catalog (ie, create products, update inventory levels) but prohibits access to the orders endpoints, may technically be possible but isn't particularly easy. That's something we're very aware of and has come up in discussions about the future of the API [(related discussion here)](https://github.com/woocommerce/woocommerce/discussions/44199).

> It's either the keys to the whole store (incl. changing passwords) or no access at all.

However, I'm not sure this piece is accurate (or perhaps I am misunderstanding). An API key can be generated, and shared, without any need to share the login itself. 

That to say, you can pass an API key to a trusted third party service—which lets them interact with our REST API—but this does not mean they can log in to wp-admin.
