### ISSUE TITLE
Orphan refund

### ISSUE THREAD

**Issue by therealgilles** [woothemes/woocommerce#46206]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I just issue a couple of order refunds through the admin panel as Stripe refunds. They seem to have been processed fine but appear as orphan orders, instead of appearing inside the original order. See screenshots below.

This has never happened before (that I recall at least).

<img width="1045" alt="Screenshot 2024-04-03 at 7 28 42 PM" src="https://github.com/woocommerce/woocommerce/assets/18076992/4dc77612-6021-4eb6-bc6b-60adcc384bcf">

<img width="886" alt="Screenshot 2024-04-03 at 7 29 15 PM" src="https://github.com/woocommerce/woocommerce/assets/18076992/d3c5300a-2278-4a9f-bc84-361f2505a6ee">

### Expected behavior

I expect a refund to appear as part of the original order.

### Actual behavior

The refund appear a separate orphan order.

### Steps to reproduce

Issue a refund through Stripe using the admin panel and `Refund` order button.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://...
Site address (URL): https://...
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.27
PHP Post Max Size: 16 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider.

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Total Database Size: 631.83MB
Database Data Size: 417.25MB
Database Index Size: 214.58MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 7.52MB + Index: 8.55MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.47MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 1.09MB + Engine InnoDB
wp_ac_segments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_addactionsandfilters_plugin_usercode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_admin_columns: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_st: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_submits: Data: 0.48MB + Index: 0.28MB + Engine InnoDB
wp_cleanup_optimizer_block_range_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_block_single_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_db_scheduler: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_licensing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_login_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_plugin_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_wp_scheduler: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_comments: Data: 9.52MB + Index: 9.09MB + Engine InnoDB
wp_cptch_blacklist_ip: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cptch_track_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cptch_track_visitor: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_email_log: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hctpc_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hctpc_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hctpc_whitelist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_bans: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_dashboard_lockouts: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_itsec_firewall_rules: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 2.52MB + Index: 0.55MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_itsec_vulnerabilities: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_avatar: Data: 5.52MB + Index: 3.53MB + Engine InnoDB
wp_litespeed_crawler: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url: Data: 10.52MB + Index: 17.11MB + Engine InnoDB
wp_litespeed_url_file: Data: 1.52MB + Index: 6.08MB + Engine InnoDB
wp_oauth_access_tokens: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_oauth_authorization_codes: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_oauth_jwt: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_public_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_refresh_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oauth_scopes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 18.42MB + Index: 1.25MB + Engine InnoDB
wp_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_postexpirator_debug: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 94.61MB + Index: 63.94MB + Engine InnoDB
wp_posts: Data: 175.48MB + Index: 7.34MB + Engine InnoDB
wp_ppfuture_actions_args: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_pum_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_redirection_404: Data: 2.02MB + Index: 2.14MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_relevanssi: Data: 7.33MB + Index: 11.48MB + Engine InnoDB
wp_relevanssi_log: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sm_sessions: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
wp_tec_events: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_tec_occurrences: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wp_tec_series_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
wp_term_relationships: Data: 2.27MB + Index: 1.17MB + Engine InnoDB
wp_term_taxonomy: Data: 0.48MB + Index: 0.59MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_sitemeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_updraftcentral_sites: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_site_temporary_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_user_cron: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_upme_post_features: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 10.52MB + Index: 8.03MB + Engine InnoDB
wp_users: Data: 0.33MB + Index: 0.27MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.47MB + Index: 0.48MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_orders: Data: 4.52MB + Index: 7.33MB + Engine InnoDB
wp_wc_orders_meta: Data: 11.52MB + Index: 26.17MB + Engine InnoDB
wp_wc_order_addresses: Data: 2.52MB + Index: 4.92MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.47MB + Index: 0.77MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 2.52MB + Index: 1.83MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 3.52MB + Index: 1.66MB + Engine InnoDB
wp_wc_order_stats: Data: 3.52MB + Index: 0.98MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_osmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.11MB + Index: 0.19MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_status_action: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpfront_ure_post_type: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfront_ure_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wp_topbar_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 8.52MB + Index: 14.08MB + Engine InnoDB
wp_wsal_occurrences: Data: 9.52MB + Index: 3.03MB + Engine InnoDB
wp_zerospam_blocked_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zerospam_log: Data: 0.16MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

_pods_field: 22
_pods_group: 11
_pods_pod: 9
action_monitor: 13
attachment: 934
curriculum-topic: 203
customize_changeset: 3
document: 39
flamingo_inbound: 102
internal-document: 86
itsec-dash-card: 4
itsec-dashboard: 1
jetpack_migration: 2
nav_menu_item: 74
oembed_cache: 1
page: 46
popup: 1
popup_theme: 7
pos_custom_product: 1
pos_temp_register_or: 5
post: 199
product: 373
product_config: 4
product_variation: 445
revision: 1957
shop_coupon: 148
shop_order: 12617
shop_order_refund: 256
staff: 89
tablepress_table: 5
team_member: 1
tribe_event_series: 122
tribe_events: 276
tribe_filters: 2
tribe_organizer: 39
tribe_venue: 7
tribe-ea-record: 2
um_directory: 1
um_form: 3
um_role: 2
user_request: 1
vc_grid_item: 3
vc_settings_preset: 3
wccpf: 1
wll_records: 2857
wo_client: 3
wp-rest-api-log: 1687
wpcf7_contact_form: 4
wpex_font: 1
wpex_templates: 25
wpex_widget_area: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (105) ###

Add Shortcodes Actions And Filters: by Michael Simpson – 2.10
Admin Columns Pro: by AdminColumns.com – 6.4.6
Admin Menu Editor: by Janis Elsts – 1.12.1
Advanced Post Manager: by The Events Calendar – 4.5.4
Solid Security Basic: by SolidWP – 9.3.2
Bootstrap Modals: by Neil Gee – 1.3.2
Five Star Business Profile and Schema: by Five Star Plugins – 2.3.7
Classic Editor: by WordPress Contributors – 1.6.3
Cloudflare: by Cloudflare
Inc. – 4.12.6

Honeypot for Contact Form 7: by Nocean – 2.1.1
Contact Form DB: by Michael Simpson – 2.10.29
Contact Form 7: by Takayuki Miyoshi – 5.9.3
Convert Post Types: by Stephanie Leary – 1.4
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.16
Custom Content Shortcode: by Eliot Akira – 4.0.2
Debug Bar: by wordpressdotorg – 1.1.6
Delete Me: by Clinton Caldwell – 3.1
Disable Cart Fragments: by Optimocha – 2.3
Disable Comments: by WPDeveloper – 2.4.6
Disable Elements for WPBakery Page Builder: by WPExplorer – 1.1
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.6
Disable Flamingo Addressbook: by Christian Sabo – 1.0
Duplicate Menu: by Jonathan Christopher – 0.2.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Email Address Encoder: by Till Krüss – 1.0.23
Email Log: by Sudar – 2.4.9
Email Obfuscate Shortcode: by khromov – 2.0
Enable Media Replace: by ShortPixel – 4.1.5
Envato Market: by Envato – 2.0.11
The Events Calendar Pro: by The Events Calendar – 6.3.2
EWWW Image Optimizer: by Exactly WWW – 7.5.0
Flamingo: by Takayuki Miyoshi – 2.5
XML Sitemap Generator for Google: by Auctollo – 4.1.19
Hello Dolly: by Matt Mullenweg – 1.7.2
Hikari Category Permalink: by Hikari – 1.00.08
Image Widget: by The Events Calendar – 4.4.9
WPBakery Page Builder: by Michael M - WPBakery.com – 7.4
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.12
Links in Captions: by Katz Web Services
Inc. – 1.2

LiteSpeed Cache: by LiteSpeed Technologies – 6.1
Log cleaner for Solid Security: by Rocket Apps – 1.4.1
Login With Ajax: by Pixelite – 4.3
Logout Redirect: by Arefly – 1.0.2
Mailgun: by Mailgun – 1.9.9
Obfuscate Email: by Scott Reilly – 3.8.1
Passwordless Login: by Cozmoslabs
sareiodata – 1.1.3

Pods - Custom Content Types and Fields: by Pods Framework Team – 3.2.1
PublishPress Future: by PublishPress – 3.3.1
Post Tags and Categories for Pages: by curtismchale – 1.4.1
Post Type Switcher: by Triple J Software
Inc. – 3.3.1

Post Types Order: by Nsp Code – 2.2
QL Events: by kidunot89 – 0.0.1
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.50
Redirection: by John Godley – 5.4.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Relevanssi: by Mikko Saari – 4.22.1
Reveal IDs: by Oliver Schlöbe – 1.6.1
Rollbar: by Rollbar – 2.7.1
Shortcode in Menus: by Gagan Deep Singh – 3.5.1
Simple Tooltips: by Justin Saad – 2.1.4
TablePress: by Tobias Bäthge – 2.3
Tabsy for Visual Composer: by phpbits – 1.0
WP Tabsy: by phpbits – 1.4
Link/Obfuscate Telephone Numbers: by Grandadevans – 1.4.1
Templatera: by WPBakery – 2.1.0
Text Expander: by Alexander Zigelski – 0.3
The Events Calendar: by The Events Calendar – 6.3.5
Total Theme Core: by WPExplorer – 1.8.2
The Events Calendar Extension: Events Control: by Modern Tribe
Inc. – 1.3.0

The Events Calendar Extension: Events Happening Now: by Modern Tribe
Inc. – 1.0.0

The Events Calendar Extension: Open external links in a new tab.: by The Events Calendar – 1.0.1
The Events Calendar Extension: Don't Hide Recurring Instances on Month and Week View: by Modern Tribe
Inc. – 1.0.0

UpdraftCentral Dashboard: by David Anderson + Team Updraft – 0.8.30
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.2

UPME NoCaptcha reCaptcha: by Themefluent – 1.1
User Profiles Made Easy: by ThemeFluent – 2.3.09
User Switching: by John Blackbourn & contributors – 1.7.3
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.4.6
When Last Login: by Yoohoo Plugins – 1.2.2
Widget Importer & Exporter: by ChurchThemes.com – 1.6.1
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.6
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.12
WooCommerce Colors: by WooThemes – 1.0.7
WooCommerce Stripe Gateway: by WooCommerce – 8.1.0
WooCommerce One Page Checkout: by Automattic – 2.8.1
Woo Product Bundles: by Woo – 7.0.2
WooCommerce Product Details Customiser: by jameskoster – 0.2.0
WooCommerce Smart Coupons: by StoreApps – 8.19.0
WooCommerce: by Automattic – 8.7.0
WooCommerce Donations Plugin: by Albdesign – 2.0.1
WP Block Admin: by Callum Macdonald – 0.2.3.0
Combined Query: by birgire – 1.2.2
Contact Form 7 Email Spam Blocker: by Hardik Kalathiya – 1.0.0
WP Crontrol: by John Blackbourn – 1.16.2
WP First Letter Avatar: by Dev49.net – 2.2.8
WP Gatsby: by GatsbyJS
Jason Bahl
Tyler Barnes – 2.3.3

WPGraphQL CORS: by  – 2.0
WPGraphQL WooCommerce (WooGraphQL): by kidunot89 – 0.18.3
WPGraphQL: by WPGraphQL – 1.22.1
WP Menu Cart Pro: by WP Overnight – 4.0.2
WP OAuth Server - Pro: by WP OAuth Server – 4.3.2
REST API Log: by Pete Nelson – 1.7.0
WP Activity Log: by Melapress – 4.6.4
WP Session Manager: by Eric Mann – 4.2.0
WPFront User Role Editor: by Syam Mohan – 4.1.0

### Inactive Plugins (15) ###

Better Search Replace: by WP Engine – 1.4.5
Bulk Delete: by Sudar – 6.0.2
Duplicator: by Duplicator – 1.5.8.1
Faust.js™: by WP Engine – 1.2.3
Git Updater: by Andy Fragen – 11.1.9
Media Deduper: by Cornershop Creative – 1.5.6
No Clear Password in Email: by Paul Newman (modified by ...) – 1.00
Query Monitor: by John Blackbourn – 3.15.0
Revision Control: by Dion Hulse – 2.3.2
The Events Calendar: Virtual Events: by The Events Calendar – 1.9.0
WooCommerce Dynamic Pricing: by Element Stark – 3.2.6
WooCommerce Name Your Price: by Kathy Darling – 3.5.13
WP Activity Log for WooCommerce: by WP White Security – 1.5.2
WP Bulk Delete: by Xylus Themes – 1.2.7
WPGraphQL JWT Authentication: by WPGraphQL
Jason Bahl – 0.4.1

### Dropin Plugins () ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 14 MB

### WC Pages ###

Shop base: #218 - /shop/
Cart: #219 - /cart/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: #11138 - /store-terms-conditions/

### Theme ###

Name: ...
Version: 1.6.25
Author URL: https://...
Child Theme: ✔
Parent Theme Name: Total
Parent Theme Version: 5.12
Parent Theme Author URL: https://www.wpexplorer.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: Total/woocommerce/archive-product.php
...l/woocommerce/checkout/form-checkout.php
Total/woocommerce/loop/loop-start.php
Total/woocommerce/loop/orderby.php
Total/woocommerce/loop/pagination.php
.../woocommerce/myaccount/form-edit-account.php
.../woocommerce/myaccount/my-orders.php
.../woocommerce/single-product/add-to-cart/variable.php
.../woocommerce/single-product/meta.php
Total/woocommerce/single-product/rating.php
Total/woocommerce/single-product/tabs/tabs.php
.../woocommerce/single-product/title.php

### Product Bundles ###

Database Version: 7.0.2
Loopback Test: ❌ Loopback test failed.
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-04 03:49:58 -07:00
Options: ✔
Notes: 23
Onboarding: completed

### Action Scheduler ###

Complete: 968
Oldest: 2024-03-03 21:39:06 -0800
Newest: 2024-04-03 19:33:06 -0700

Failed: 19
Oldest: 2021-06-20 12:27:00 -0700
Newest: 2024-04-02 21:53:05 -0700

Pending: 5
Oldest: 2024-04-04 00:00:00 -0700
Newest: 2024-04-06 03:02:06 -0700

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: no
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: no
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: yes
Combine emails: yes
Auto generated coupon email: yes
Combined auto generated coupons email: yes
Acknowledgement email: yes
Enable taxes: no
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: itemized
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: yes
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2024-04-03 19:33:14 -07:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @therealgilles,

Thanks for opening this issue. Could you provide reproduction steps for a fresh WooCommerce install?
