### ISSUE TITLE
Product Collection: "Sync with current query" doesn't display the correct products in the specific category templates

### ISSUE THREAD

**Issue by maxlaf** [woothemes/woocommerce#46201]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When "Sync with current query" is used on a user-created category template, it doesn't display the correct products from the given category.

Switching from a Products (Beta) block to a Product Collection block does not resolve this. For context, the Query Loop block does not have this issue, and it correctly displays post from a given category when creating a new category-specific template.

Product Category
![J6GgoI.png](https://github.com/woocommerce/woocommerce/assets/56649567/c36f7d56-8cb0-4fc2-9653-fe7610aba211)

Post Category
![kcOwaZ.png](https://github.com/woocommerce/woocommerce/assets/56649567/0b272d6f-87ce-4659-af1e-68d0c58f3a25)

### Expected behavior

Products from a given category to be displayed.

### Actual behavior

Seems to display all products.

### Steps to reproduce

1. Add some products and categories.
2. Navigate to the Site Editor and create a new template.
3. Select the Category (product_cat) template and pick a category.
4. See products not within the specified category on the template that's created.

### WordPress Environment

<details>

`
### WordPress Environment ###

WordPress address (URL): https://mortally-mystic.jurassic.ninja
Site address (URL): https://mortally-mystic.jurassic.ninja
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Total Database Size: 3.37MB
Database Data Size: 1.58MB
Database Index Size: 1.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 8
post: 3
product: 19
product_variation: 7
revision: 10
shop_order_placehold: 4
wp_global_styles: 2
wp_navigation: 1
wp_template: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Companion Plugin: by Osk – 1.30
Jetpack: by Automattic – 13.3-beta
WooCommerce Stripe Gateway: by WooCommerce – 8.1.0
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by Automattic – 7.4.0
WooCommerce: by Automattic – 8.7.0
WP Rollback: by WP Rollback – 2.0.6

### Inactive Plugins (1) ###

Gutenberg: by Gutenberg Team – 18.0.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 462 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php

### WooPayments ###

Version: 7.4.0
Connected to WPCOM: Yes
WPCOM Blog ID: 231531225
Account ID: acct_1P1GnFFj90jxspIy
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-03 23:17:59 +00:00
Options: ✔
Notes: 67
Onboarding: skipped

### Action Scheduler ###

Complete: 37
Oldest: 2024-04-02 23:19:24 +0000
Newest: 2024-04-03 20:49:00 +0000

Failed: 4
Oldest: 2024-04-02 23:21:24 +0000
Newest: 2024-04-03 20:50:11 +0000

Pending: 1
Oldest: 2024-04-03 23:19:24 +0000
Newest: 2024-04-03 23:19:24 +0000

### Status report information ###

Generated at: 2024-04-03 21:41:05 +00:00
`

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
I was able to reproduce this issue. More over the `Sync with current query` (Product Collection) and `Inherit query from template` (Products beta) should probably be enabled without letting user change this because the template itself is already in a specific query context.

**Comment by maxlaf** [comment]
> should probably be enabled without letting user change this

My argument against this is it's unnecessarily limiting. If a user wanted to add a 2nd product collection block, say, to showcase a few featured products at the top of category archive pages, they wouldn't be able to.

**Comment by roykho** [comment]
> My argument against this is it's unnecessarily limiting. If a user wanted to add a 2nd product collection block, say, to showcase a few featured products at the top of category archive pages, they wouldn't be able to.

I see what you mean however for those cases, wouldn't they just create a "regular" template instead of a specific product category template? I just find it confusing that you if specifically choose to create a product category template and want to have the products be generic.

**Comment by maxlaf** [comment]
Just to recap the user's support request, the primary thing was they were confused as to why the editor showed a different selection of products than the frontend. I just saw #44874 today, which could address that confusion too.

>I see what you mean however for those cases, wouldn't they just create a "regular" template instead of a specific product category template? I just find it confusing that you if specifically choose to create a product category template and want to have the products be generic.

I see your point too. I've never seen a user utilizing category-specific templates and I didn't know they were a thing, until now. But, to play devil's advocate, maybe they want to add a 2nd collection block with certain products which aren't in the category but need to be different across each category

An example use case: I sell coffee and tea. In my categories for coffee beans and tea leaves, I want to add a 2nd collection block to highlight some bestselling coffee or tea equipment. I don't want coffee equipment in the tea category, and vice versa. That can already be done, but if we added the proposed limitation, it wouldn't be possible, I think.

**Comment by kmanijak** [comment]
Hey @maxlaf , thanks for raising this and @roykho for responding!

Let me clarify some points you touched upon:

> Roy: More over the Sync with current query (Product Collection) and Inherit query from template (Products beta) should probably be enabled without letting user change this because the template itself is already in a specific query context.
> Max: My argument against this is it's unnecessarily limiting. If a user wanted to add a 2nd product collection block, say, to showcase a few featured products at the top of category archive pages, they wouldn't be able to.

We don't want to limit users exactly as Max described. The "Sync with current query" option is enabled by default for the first Product Collection block you insert at the page but disabled for the 2nd+. This is exactly to make the default user's path described by Max easy to achieve but at the same time let them change the settings if the default doesn't work for them.

> Just to recap the user's support request, the primary thing was they were confused as to why the editor showed a different selection of products than the frontend. I just saw https://github.com/woocommerce/woocommerce/issues/44874 today, which could address that confusion too.

Misalignment of Editor and Frontend is incorrect behavior. https://github.com/woocommerce/woocommerce/issues/44874 could _hide_ the issue but not solve it. Let's use this issue to actually _fix_ the problem and display the same products that are expected in frontend.

> An example use case: I sell coffee and tea. In my categories for coffee beans and tea leaves, I want to add a 2nd collection block to highlight some bestselling coffee or tea equipment. I don't want coffee equipment in the tea category, and vice versa. That can already be done, but if we added the proposed limitation, it wouldn't be possible, I think.

Exactly! That use case validates our assumptions.
