### ISSUE TITLE
[Enhancement]: Text adjustments on shipping zones settings page

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46209]
### Describe the solution you'd like

On `/wp-admin/admin.php?page=wc-settings&tab=shipping`, we display general information about shipping. In https://github.com/woocommerce/woocommerce/issues/41534#issuecomment-2023083159, @pmcpinto suggested the following changes when the Checkout block is enabled:

- Update the text _"A shipping zone consists of the region(s) you'd like to ship to and the shipping method(s) offered. A shopper can only be matched to one zone, and we'll use their shipping address to show them the methods available in their area. To offer local pickup, configure your pickup locations in the [local pickup settings]."_ to reference to the local pickup settings.
- Remove the text _"Local zone = California ZIP 90210 = Local pickup"_ from the main screen that is visible when no shipping zones and no shipping methods have been created/enabled yet.

The following screenshots show the corresponding texts:

<img width="1279" alt="Screenshot 2024-04-04 at 12 38 31" src="https://github.com/woocommerce/woocommerce/assets/3323310/d4ec14fb-b1d5-4c6d-91b0-852b99268e69">

**Comment by pmcpinto** [comment]
Niels, thanks for creating the issue. Just a heads up that the copy changes should be applied only when the checkout block is enabled. When it's disabled, the users need to work with the "classic" local pickup option. Sounds good?

**Comment by nielslange** [comment]
Thanks for clarifying this, @pmcpinto. I've added a note to the issue description.
