### ISSUE TITLE
[DOC-REQ] Document monorepo commands

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46225]
## Description of the Document Requested

> Provide a detailed description of the topic you'd like to see documented.

The integration of WooCommerce Blocks into the monorepo has led to changes in several regularly used commands. To assist both internal and external engineers, we should document common monorepo commands. See also pdV5qK-jz-p2, pdV5qK-jz-p2#comment-771 and pdV5qK-jz-p2#comment-850.

## Why is this Document Important?

> Explain why this topic is crucial and how it can benefit the WooCommerce community.

To further clarify the importance of the requested documentation on common monorepo commands post-WooCommerce Blocks integration, you could enhance your description by focusing on the specific benefits and problems it aims to address. Here’s a refined version of that section incorporating these elements:

Why is this Document Important?

The integration of WooCommerce Blocks into our monorepo represents a significant shift in how we approach development processes, affecting both our internal team and the broader WooCommerce developer community. The necessity for this document arises from several key challenges and opportunities:

1. **Reducing Confusion:** Developers, especially those new to our project or monorepo structure, often encounter confusion regarding which command should be used for a specific task. This confusion can lead to inefficiencies, as developers spend valuable time searching through various documents or relying on trial and error.
2. **Preventing Errors:** Utilizing outdated commands or incorrect command contexts can lead to errors that may disrupt development workflows, affect project timelines, and potentially compromise the integrity of our codebase. By providing updated and centralized command documentation, we significantly reduce the risk of such errors.
3. **Standardizing Practices:** As our project evolves, so do our development practices. A central document that outlines common commands helps ensure that all developers, regardless of their role or level of experience, follow the same best practices, enhancing the consistency and reliability of our development efforts.
4. **Facilitating Onboarding:** For new engineers joining our project, whether they are internal team members or external contributors, having a single, comprehensive document that covers essential commands can greatly accelerate their onboarding process, enabling them to contribute more effectively and efficiently.

By addressing these issues, the document will serve as a valuable resource, not just as a reference tool, but as a foundation for more efficient, error-free, and unified development workflows within the WooCommerce community.

## Potential Content

> If you have an idea about what the new document should cover, list the points or sub-topics here.

In pdV5qK-jz-p2, I collected the following commands:

```sh
// Build the Woo core folder
pnpm --filter=@woocommerce/plugin-woocommerce build
 
// Create the woocommerce.zip file
pnpm --filter=@woocommerce/plugin-woocommerce build:zip
 
// Build and watch the Woo core folder
pnpm --filter=@woocommerce/plugin-woocommerce watch:build
 
// Add a changelog entry to the Woo core folder
pnpm --filter=@woocommerce/plugin-woocommerce changelog add
 
// Build the Woo Blocks folder
pnpm --filter='@woocommerce/block-library' build
 
// Build and watch the Woo Blocks folder
pnpm --filter='@woocommerce/block-library' watch:build
 
// PHPUnit: Run a specific PHP test file
pnpm --filter="@woocommerce/plugin-woocommerce" test:php:env -- tests/php/src/Blocks/StoreApi/Routes/Cart.php
 
// Playwright: Run normal tests
pnpm test:e2e
 
// Playwright: Run normal tests in UI mode
pnpm test:e2e --ui
 
// Playwright: Run classic tests
pnpm test:e2e:classic-theme
 
// Playwright: Run classic tests in UI mode
pnpm test:e2e:classic-theme --ui
 
// Playwright: Run side effects tests
pnpm test:e2e:side-effects
 
// Playwright: Run side effects tests in UI mode
pnpm test:e2e:side-effects --ui
```

These commands do not have to be copied one by one. When creating the new doc, we should list the most common commands and reference to other files where needed.

## Additional Context

> Add any other context, references, or information that can help in the creation of this new document.

n/a

**Comment by jjroley** [comment]
The documentation still assumes the WooCommerce repo is structured as a plugin rather than a monorepo. Are there plans to update that anytime soon?

https://github.com/woocommerce/woocommerce/blob/trunk/docs/getting-started/development-environment.md

**Comment by ralucaStan** [comment]
> The documentation still assumes the WooCommerce repo is structured as a plugin rather than a monorepo. Are there plans to update that anytime soon?

@jjroley could you point out the parts that hint to it being a plugin rather than a monorepo. What updates would you like to see?

**Comment by ralucaStan** [comment]
I am going to close this issue, as it has become stale. A separate issue might come out of this, depending on @jjroley's answer.

**Comment by nielslange** [comment]
@ralucaStan It seems you closed this issue based on https://github.com/woocommerce/woocommerce/issues/46225#issuecomment-2517622793, but the initial reason I created this issue was slightly different. At the moment, we still don’t have a document that lists the main commands for working with the monorepo.

Would it be possible to revisit this, as I believe such documentation would be valuable for the team and contributors?

**Comment by jjroley** [comment]
@ralucaStan

> [@jjroley](https://github.com/jjroley) could you point out the parts that hint to it being a plugin rather than a monorepo. What updates would you like to see?

https://github.com/woocommerce/woocommerce/blob/cd2a6f4cf72442126f123c4d613bc28147f8ad57/docs/getting-started/development-environment.md?plain=1#L85

Cloning the repo directly into the plugins directory is not enough anymore, what I ended up doing was cloning to a directory elsewhere in my project then making symlinks from the repo's plugins directory to my WordPress plugin directory. Also, you need to navigate into `./plugins/woocommerce` before running build:zip.
