### ISSUE TITLE
Exclude coming soon page from navigation

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#46230]
The coming soon page unexpectedly appears in default navigation in TT24 theme. [ChatGPT says](https://chat.openai.com/share/4cf58354-22d4-47ee-a387-41ba0bace3dd) this could be automatically removed with a filter:

```
function exclude_page_from_nav($items, $menu, $args) {
    // Change '123' to your page ID
    $exclude = array(123);
    
    foreach ($items as $key => $item) {
        if (in_array($item->object_id, $exclude)) {
            unset($items[$key]);
        }
    }
    return $items;
}
add_filter('wp_get_nav_menu_items', 'exclude_page_from_nav', 10, 3);
```

## Screenshot

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/c50c1a93-1418-4358-b972-7f5d2506cd7b)

**Comment by moon0326** [comment]
Good catch!

Just leaving a note before my EOD

`wp_get_nav_menu_items` hook no longer works for block themes. It seems like we should use `block_core_navigation_render_inner_blocks` now, but I haven't figured out how to use it yet.

**Comment by adrianduffell** [comment]
Just re-opening this until we have the automatic coming soon page creation removed.

**Comment by psealock** [comment]
>Just re-opening this until we have the automatic coming soon page creation removed.

I have a PR in progress for this task

**Comment by adrianduffell** [comment]
Closes with https://github.com/woocommerce/woocommerce/pull/46561
