### ISSUE TITLE
Coupons > Usage restrictions > Allowed Emails section won't display email values under OS Sonoma 14.4.1 Safari Version 17.4.1

### ISSUE THREAD

**Issue by namiokuzono** [woothemes/woocommerce#46257]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When trying to set or view the email value of Coupons > Usage restrictions > Allowed Emails section, the setting won't display email values under OS Sonoma 14.4.1 Safari Version 17.4.1

### Expected behavior

I would expect the setting to work as expected:

- You can view the save Allowed emails setting
- You can save the Allowed emails setting

### Actual behavior

Instead, Coupons > Usage restrictions > Allowed Emails section won't display email values nor does it save the setting. This is a major inconvenience. 

### Steps to reproduce

1. Have a Mac device that can be upgraded to Sonoma OS 14.4.1
2. Observe the behavior under Instead, Coupons > Usage restrictions > Allowed Emails

https://media.publit.io/file/Device-Issue.html

### WordPress Environment

Staging site with only WooCommerce plugin and Striple plugin installed. 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by namiokuzono** [comment]
Originally reported in 7964652-zd-a8c

**Comment by barryhughes** [comment]
Interesting. It seems like this is specifically an issue with the [`multiple` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple). When removed, the email address renders as normal.

Could this be a bug in Sonoma 14.4.1/Safari 17.4.1?

**Comment by barryhughes** [comment]
Seems others have come across it, and it is definitely not specific to WooCommerce:

https://stackoverflow.com/questions/78403943/safari-issues-with-input-type-email-and-multiple-attribute

**Comment by barryhughes** [comment]
It seems [this is already known](https://bugs.webkit.org/show_bug.cgi?id=271043), and a fix is [in the pipeline](https://github.com/WebKit/WebKit/pull/26657). As it is an upstream issue (effectively), I'm going to close this report.
