### ISSUE TITLE
Core profiler does not get triggered when WC is activated from Plugins page

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#46254]
Slack thread: p1712267732746079-slack-C01DT6U03HC

### Issue

In WordPress 6.5, when WC is activated from /wp-admin/plugin-install.php, users are not redirected to the core profiler immediately.

### Steps to reproduce

1. Create a fresh site without.
2. Go to `Plugins` and click on `Add New Plugin` button.
3. Search for `woocommerce`
4. Click on `Install now` button.
5. Click on `Activate` button
6. Notice nothing happens.

### Expected behavior

Users should be redirected to the core profiler after activating WooCommerce

**Comment by adrianduffell** [comment]
Thanks for opening this @moon0326.

I wasn't able to reproduce this in WP 6.4 and not sure what the expected behavior is. I'll block it while I confirm some more details.

https://github.com/woocommerce/woocommerce/assets/9312929/8003f984-6aee-4e22-bf0f-780b12f01ac4

**Comment by ilyasfoo** [comment]
It seems like redirect change was caused by [WordPress 6.5](https://core.trac.wordpress.org/ticket/60709) and it's intended. Closing this issue since this is going to be the expected behaviour moving forward.

Internal reference: p1712308917630599/1712267732.746079-slack-C01DT6U03HC
