### ISSUE TITLE
Stock on variations dissapears

### ISSUE THREAD

**Issue by Studio-Sjoege** [woothemes/woocommerce#46260]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have variable products where we manage the stock on variation levels. so they are all filled, we've checked the boxes on is active and manage stock. this all works fine, but somehow, when one of the variations is sold, the whole product goes out of stock on the frontend of the website.

### Expected behavior

When selling a variation of the product, it should decrease the amount of stock. 

### Actual behavior

We have an extensive logger on the backend as this problem is happening for the last 4 months. only with variable products. we've alleady deleted all the products, re imported them with wp-all import. but also hade a number of products set up by hand to be sure the import isn't ruining anything. in the logger we see the variation being added to the customers order, nothing more nothing less. but on the frontend the product becomes completely out of stock. in the backend, there is stock. when we save the product from the backend, the problem on the frontend is solved. if we look at the database, while in the frontend the product is out of stock, it's also in stock with a qty. we can easily spot the problem products because when we look at the backend and filter on variable products, the troubled ones will have '-' as price field. when we save the product, the price or price range is back there.. so something really strange is happening. we've already disabled a lot of the plugins, themes etc.. but we run multiple woo sites with the same plugins so I don't think that's it. To make it even harder.. not every time when an order is placed with a variable product, the problem occurs.

when we save to product from the backend to cure the pain, we see in the long that the field download expiry date is set from 'never' to 'nooit' which means the same in our native language. 

### Steps to reproduce

At the moment all of the products behave normal. today we had the following product having trouble:

https://kwispelenrelax.nl/product/ydolo-bone-broth-v2/
Re-saving the product in the backend solved the issue.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://kwispelenrelax.nl
Site address (URL): https://kwispelenrelax.nl
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.17
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.5.24-MariaDB-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: Kszhptbv2_
Totale database grootte: 233.50MB
Database gegevens grootte: 193.78MB
Database index grootte: 39.72MB
Kszhptbv2_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
Kszhptbv2_woocommerce_order_items: Data: 0.25MB + Index: 0.09MB + Engine InnoDB
Kszhptbv2_woocommerce_order_itemmeta: Data: 2.44MB + Index: 3.02MB + Engine InnoDB
Kszhptbv2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
Kszhptbv2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_actionscheduler_actions: Data: 6.41MB + Index: 8.67MB + Engine InnoDB
Kszhptbv2_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_actionscheduler_logs: Data: 7.52MB + Index: 4.52MB + Engine InnoDB
Kszhptbv2_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_cmplz_cookies: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_cmplz_statistics: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_comments: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
Kszhptbv2_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
Kszhptbv2_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
Kszhptbv2_e_submissions: Data: 0.06MB + Index: 0.27MB + Engine InnoDB
Kszhptbv2_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
Kszhptbv2_e_submissions_values: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
Kszhptbv2_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
Kszhptbv2_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_jet_search_suggestions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_jet_search_suggestions_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_jet_smart_filters_indexer: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_litespeed_img_optming: Data: 0.13MB + Index: 0.22MB + Engine InnoDB
Kszhptbv2_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_options: Data: 13.05MB + Index: 3.13MB + Engine InnoDB
Kszhptbv2_pmxe_exports: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxe_posts: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxi_hash: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxi_images: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxi_imports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxi_posts: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_pmxi_templates: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_postmeta: Data: 111.30MB + Index: 11.80MB + Engine InnoDB
Kszhptbv2_posts: Data: 39.08MB + Index: 3.69MB + Engine InnoDB
Kszhptbv2_qss: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
Kszhptbv2_rsssl_csp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_rsssl_xmlrpc: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_term_relationships: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
Kszhptbv2_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_usermeta: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
Kszhptbv2_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
Kszhptbv2_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_wcpdf_invoice_number_2023: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_wc_customer_lookup: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
Kszhptbv2_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
Kszhptbv2_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_wc_order_product_lookup: Data: 0.23MB + Index: 0.27MB + Engine InnoDB
Kszhptbv2_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
Kszhptbv2_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
Kszhptbv2_wc_product_attributes_lookup: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
Kszhptbv2_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_wc_product_meta_lookup: Data: 0.22MB + Index: 0.45MB + Engine InnoDB
Kszhptbv2_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Kszhptbv2_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_wpr_rocket_cache: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
Kszhptbv2_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
Kszhptbv2_wsal_metadata: Data: 0.20MB + Index: 0.34MB + Engine InnoDB
Kszhptbv2_wsal_occurrences: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
Kszhptbv2_yith_wcwtl_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_yith_wcwtl_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
Kszhptbv2_yith_wcwtl_waitlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 11021
b2bking_conversation: 1
b2bking_custom_field: 11
b2bking_custom_role: 2
b2bking_group: 1
b2bking_rule: 6
custom_css: 2
customize_changeset: 10
elementor_font: 2
elementor_library: 21
elementor_snippet: 1
jet-smart-filters: 1
jet-woo-builder: 4
nav_menu_item: 50
page: 27
post: 17
product: 457
product_variation: 683
revision: 1391
shop_coupon: 50
shop_order: 448
shop_order_refund: 15
wp_global_styles: 2
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

ManageWP - Worker: door GoDaddy – 4.9.19
Complianz Privacy Suite (GDPR/CCPA) premium: door Really Simple Plugins – 7.0.8
Elementor Pro: door Elementor.com – 3.20.2
Elementor: door Elementor.com – 3.20.3
Google Listings and Ads: door WooCommerce – 2.6.4
Hide My WP Ghost: door WPPlugins – 7.2.05
Imagify: door Imagify – Optimize Images & Convert WebP & Avif – 2.2.1
JetBlocks For Elementor: door Crocoblock – 1.3.11
JetBlog For Elementor: door Crocoblock – 2.3.6
JetCompareWishlist For Elementor: door Crocoblock – 1.5.6
JetElements For Elementor: door Crocoblock – 2.6.17.1
JetEngine: door Crocoblock – 3.4.2
JetMenu: door Crocoblock – 2.4.4
JetSearch: door Crocoblock – 3.3.1
JetSmartFilters: door Crocoblock – 3.4.3
JetWooBuilder For Elementor: door Crocoblock – 2.1.11
JetWooBuilder - Products Grid Load More: door Crocoblock – 1.2.0
Kadence WooCommerce Email Designer: door Kadence WP – 1.5.12
Mollie Payments for WooCommerce: door Mollie – 7.5.1
Really Simple SSL: door Really Simple Plugins – 8.0.0
Squirrly SEO (Newton): door Squirrly – 12.3.18
User Switching: door John Blackbourn & contributors – 1.7.3
Variation Swatches for WooCommerce: door CartFlows – 1.0.8
White Label CMS: door www.videousermanuals.com – 2.7.3
MyParcel: door MyParcel – 4.22.1
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.8.0
WooCommerce: door Automattic – 8.7.0
WP Mail SMTP Pro: door WPForms – 3.5.2
WP Rocket: door WP Media – 3.15.10
WP Activity Log: door Melapress – 4.6.4
YITH WooCommerce Waitlist Premium: door YITH – 3.8.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: door GoDaddy – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dagen
Level threshold: –
Log directory size: 895 KB

### WC Pages ###

Winkelbasis: #461 - /shop/
Winkelwagen: #462 - /cart/
Afrekenen: #463 - /checkout/
Mijn account: #464 - /my-account/
Algemene voorwaarden: #20738 - /algemene-voorwaarden/

### Theme ###

Name: Astra
Version: 4.6.10 (update naar versie 4.6.11 is beschikbaar)
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een sub thema aan. Zie: Hoe maak je eensub thema

WooCommerce Support: ✔

### Templates ###

Overrides: /var/www/vhosts/kwispelenrelax.nl/httpdocs/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/form-login.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-05 18:11:19 +02:00
Options: ✔
Notes: 129
Onboarding: completed

### Action Scheduler ###

Afgerond: 5.042
Oldest: 2024-03-05 09:29:25 +0000
Newest: 2024-04-05 09:08:35 +0000

Mislukt: 6.730
Oldest: 2023-05-08 14:19:32 +0000
Newest: 2024-04-04 12:27:14 +0000

In afwachting: 31
Oldest: 2024-04-05 09:06:21 +0000
Newest: 2024-04-09 09:35:18 +0000

### Status report information ###

Generated at: 2024-04-05 11:09:09 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Studio-Sjoege** [comment]
Update, it seems that somehow transients in the database are causing the issue. at least, when we delete old transients, the problem is resolved. maybe this helps with the investigation?

**Comment by Studio-Sjoege** [comment]
how come no one has been assigned to this issue in 2 weeks?

**Comment by Studio-Sjoege** [comment]
Still waiting over here. we've developed a custom plugin that checks for bad transients.  it deletes/regenerates them at that moment. but it doesn't fix the original cause.. so why is no one coming up in this issue

**Comment by 79mplus-admin** [comment]
I couldn't reproduce the issue. If a variation is out of stock, the product doesn't disappear from the front end; instead, the variant is shown as out of stock.

![image](https://github.com/woocommerce/woocommerce/assets/36501099/6956813f-63e8-4bf5-8a30-45e6d94c0ce3)

**Comment by Studio-Sjoege** [comment]
Hi there,

This problem is well known online, there are other forums where people describe this exact problem and no one has solved it. The problem is related to bad transients.. we’ve had a couple of staging sites where we monitored the issue but we can’t reproduce the problem in steps so it’s very hard to determine where it’s coming from.. seems completely random. We paid a Codeable dev to build a plugin that checks for bad transients in the variable products and fixes them.. this cost us over 1400 dollars to build after extensive testing and not finding out what’s causing it… so finally just fixing it everyday automatically is a acceptable solution.

I really have the feeling WooCommerce is sticking their heads in the sand with this one.. it’s an issue that’s been going on for years now. We could give you access to the staging site to see if you can find anything.

regards. 

Met vriendelijke groet,

Jelle 
Developer 🤓

06 5734 6967

Noordeinde 162, 2371CX Roelofarendsveen
www.studiosjoege.nl
https://www.instagram.com/studiosjoege/

logo | branding | websites
￼

**Comment by tjcafferkey** [comment]
@Studio-Sjoege thanks for submitting this issue, I apologise that someone has not got round to responding sooner. I have just tried to reproduce this issue without success. When I manage the stock levels of variation products and I purchase one, the stock level decreases as expected rather than going completely out of stock.

I see that you had some insights into why this was happening regarding transients and had a third-party engineer find a solution for you. Were you or the engineer able to find out how to reliably reproduce this issue so I can investigate it further for you?

Thanks.

**Comment by Studio-Sjoege** [comment]
Please reopen this issue, I didn't receive a notice you replied after months!... the issue is still active and last week we got another webshop build by us getting the same issue. this webshop has been online for over a year without issues, and now it has the same problem with the prices disappearing on variable products randomly. regenerating transients fixes it but where is this coming from. this webshop is also hosted on another server than the first 2 shops where we got this issue. as I told earlier in this page, we never had the possibility to reproduce the issue, we could hire the code able engineer for another 50 hours or whatever to keep searching but that's a pretty expensive thing to do. we solved it with a plugin that checks for bad transients in the db and then fixes them. this issue can be found online on other forums and has been going on for years, without a fix to the cause. even Woocommerce support is looking the other way and directs us to codeable... this is exactly what happens on other forums, months no reply and then a reply that doesn't help a bit... if you'd read the earlier communication you'd know we never got to reproducing etc.. I'm sorry if I come across hard but this is not a way to run a business.. we have a lot of webshops build by us and under maintenance where we can only hope the issue doesn't spread to them. the plugin does its work but isn't 100% watertight.. Woocommerce has to investigate more!

**Comment by lanej0** [comment]
Re-opened, but please provide further information as we've been unable to reproduce this on our end.

**Comment by Studio-Sjoege** [comment]
Hi Jonathan, thanks for re-opening. it's hard to reproduce this as was already mentioned in different messages. The problem however is clearly there, we already have had 3 sites where the problem occurred and we fixed it with the custom plugin that checks the database for corrupt fields regarding the woo reg price and then fixes them. this happened on different hosts also, so at first we thought maybe it had something to do with the LiteSpeed server but that has been busted by now. if you look around on the internet, you'll see there are more people with this issue, going back years and never has there been a answer. if we look at the similarities between the shops, we see the plugin 'variation swatches from Carflows' has been installed on all the 3 sites. and if we look in the change log of that plugin, we see this: 

1.0.5 – TUESDAY, 18th OCTOBER 2022

Fixed – Compatibility issues with WP Sheet Editor – Taxonomy Terms Pro.
Fixed – Fatal error with Astra theme.
Fixed – Variation price disappears on shop page.

**Comment by Studio-Sjoege** [comment]
but, that was fixed I guess.  so I don't think it's the problem. I can share the plugin code if that would help?

**Comment by Studio-Sjoege** [comment]
unfortunately, again it takes a very long time to get a response over here. in the meantime I've adjusted the plugin that regenerates the corrupted transients so that I can set the interval, and made it every 30 minutes. this makes it more tunneled where to search for us. yesterday, a customer ordered a variable product in the shop and right after that the price became corrupt, and was regenerated by the plugin in the next half hour. so although it's not every time a variable product is purchased, this still means there is a relation to a product that has been sold, and then  get corrupted.. can you give me directions where to search next?

**Comment by Studio-Sjoege** [comment]
3 weeks gone by, no one here, what a disappointing community

**Comment by Studio-Sjoege** [comment]
another 2 weeks.. months go by without any communication.

**Comment by Studio-Sjoege** [comment]
and another 5 weeks, this is getting hilarious

**Comment by tjcafferkey** [comment]
Hi @Studio-Sjoege 

I'm sorry you feel some frustration due to the response time, I completely understand. I see that this issue is a duplicate of https://github.com/woocommerce/woocommerce/issues/50855 so I'm going to close this one and follow up on the one linked.

I also just want to say I appreciate your investigative efforts and detailed summaries. It's definitely going to help as I pick up this issue now to look into it.

If you have any further information or comments please feel free to follow up on the other issue.

Thanks, and hopefully I'll be in touch soon!

**Comment by tjcafferkey** [comment]
Hi @Studio-Sjoege 

Just following up with a potential workaround that a community member has come up with which might help you in the meantime. It can be found here https://github.com/woocommerce/woocommerce/issues/50855#issuecomment-2469740799 on the related issue I linked.

It might be also beneficial if you could review the discussion on there to see if there's any valuable insights you can add to the discussion from your own investigations.

Im still in the process of catching up on this issue myself.
