### ISSUE TITLE
Changing between countries with states results in an error in the Checkout block

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#46270]
### Issue description

When editing a saved address and switching between two countries with states, e.g. Japan and Hungary an error is shown in the address form.

```
The provided state (JP02) is not valid. Must be one of: BK, BE, BA, BZ, BU, CS, FE, GS, HB, HE, JN, KE, NO, PE, SO, SZ, TO, VA, VE, ZA
The provided postcode / ZIP is not valid
```

This shows that server-side validation is still happening against the old country.

### Reproduction

0. Disable local pickup (I had trouble reproducing with Local Pickup enabled)
1. ~Be logged in.~ *
2. Add an item to your cart and go to the Checkout block.
3. Select Japan as your country. You may use this example address: 2 Chome-19-23 Aobadai, Meguro City, Tokyo 153-0042, Japan
4. Place the order.
5. Add another item to your cart and go to the Checkout block.
6. On the saved address card, edit your address and go immediately to the Country field. Change it to Hungary.
7. Observe the error.

1* This also works if you're logged out, you just have to fill a complete address then change country

#### Video

https://www.loom.com/share/5b8faeac82d241feab166862046501e4

#### Screenshot

<img width="826" alt="Screenshot 2024-04-06 at 15 17 12" src="https://github.com/woocommerce/woocommerce/assets/3323310/fa74ce19-84bd-4cae-ae40-5ef13846255f">

**Comment by nielslange** [comment]
Thanks for reporting this issue, @opr. I was able to reproduce it and will move this issue to our backlog.

**Comment by wavvves** [comment]
Shouldn't changing Country reset all the dependent fields? Is that what we're aiming at? What is the expected behaviour that a PR should contain? 🤔

**Comment by opr** [comment]
I don't think it should reset anything, except the state, but only when state can be chosen from a discrete list of values.

**Comment by ralucaStan** [comment]
a related internal chat p1715078726958079-slack-C8X6Q7XQU surfacing that for some countries we show the optional state fields in the shortcode, but not in the checkout. 

this is not the reason for the bug, but having those states listed would enable shoppers to fix the notice;

If we do reset the state than we might not see the notice, so that could work.
