### ISSUE TITLE
Input too big on Order summary page

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46283]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

<img width="1181" alt="Screenshot 2024-04-05 at 18 04 48" src="https://github.com/woocommerce/woocommerce/assets/1628454/6bba0af6-ce21-4f98-b076-ef7495969b14">

### Expected behavior

the input should be smaller in width

### Actual behavior

The input spans the full-width on desktop.

### Expected behaviour
The input should span half of the container width on desktop, and full width on tablets and smaller.

### Steps to reproduce

1. place an order as a guest
2. copy the link for the Order confirmation page
3. open the link in incognito

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@nikkivias what input width do you recommend for this use case?

**Comment by dominique-vias** [comment]
@ralucaStan @pmcpinto We can do half the container width on desktop, and full width on tablets and smaller.

Curious what this does— does it link the order to the email if they do guest checkout, whether or not they have an existing account?

**Comment by ralucaStan** [comment]
This screen is for `Guest user viewing confirmation page in incognito window:`.

You can see https://github.com/woocommerce/woocommerce-blocks/pull/10567 for more screens and https://github.com/woocommerce/woocommerce-blocks/pull/10414 to learn how access is determined
