### ISSUE TITLE
CYS: Customize your theme page just reloads with WP 6.5.1-alpha

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#46288]
Using WP 6.5.1-alpha (nightly), I am seeing an issue when clicking on `Customize your theme`. The page just reloads without going anywhere nor any information/message.

https://github.com/woocommerce/woocommerce/assets/2132595/328f420d-7df7-4895-a082-efc04c591100

Steps to reproduce:

WP 6.5.1-alpha

1. Go to WooCommerce->Home->Customize your store
2. Click on Customize your theme
3. Witness the page just reloads and does nothing

**Comment by gigitux** [comment]
I'm going to close this issue because we are not able to replicate it anymore
