### ISSUE TITLE
[TT4] The coupon input is too big

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46282]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A small visual bug, the coupon input is too big
<img width="412" alt="Screenshot 2024-04-05 at 15 54 40" src="https://github.com/woocommerce/woocommerce/assets/1628454/a3a106ef-f1f5-4f16-a36d-14b8f3c3049c">

### Expected behavior

The input and the bug should have the same height;

### Actual behavior

The difference is quite big between the heights of the 2 elements, specific to TT4

### Steps to reproduce

1. go to Cart block
2. click on add a coupon

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ralucaStan** [comment]
@nikkivias could I get a thumbs up for you on this one? Not a high priority
The input size is similar in the checkout block, but here the difference is bigger with the button.

**Comment by dominique-vias** [comment]
@ralucaStan Yes correct they should be the same size. The input must be sized down to match button

**Comment by nielslange** [comment]
Closing this issue as @alexflorisca solved this issue while working on [Update Order Summary Design](https://github.com/woocommerce/woocommerce/pull/45767).

cc: @ralucaStan & @nikkivias
