### ISSUE TITLE
Product Filters Redesign: Create a parent block for the Product Filters block

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#46293]
## Description
This issue outlines the creation of a parent block for the existing Product Filters block.

## Current Behavior:
Individual Filter Blocks (e.g., Filter by Price, Filter by Attribute, Filter by Rating, etc) are added separately within the Blocks Editor.

## Expected Behavior:
- Introduce a new parent block called "Product Filters."
- All existing individual filter blocks become child blocks of the "Product Filters" parent block. Users can only add these child blocks within the parent block.
- Filters can only be added once, except for Status and Attribute filters.
- In pages, posts, and/or templates, The Parent and inner blocks should be hidden from the Block Inserter.
- The Parent block can only be inserted inside the Product Filters template part.

| Current | Expected |
|--------|--------|
| ![CleanShot 2024-04-05 at 17 17 20@2x](https://github.com/woocommerce/woocommerce/assets/20469356/27f90183-0305-44c3-9cc9-ecd025676f54) |  ![CleanShot 2024-04-05 at 17 14 01@2x](https://github.com/woocommerce/woocommerce/assets/20469356/782f0418-6e23-49f5-845a-69b94b152dd1) |

**Comment by roykho** [comment]
Some thoughts here:

- What if people want to add blocks in-between filters? For example like a paragraph block or a separator block.
- What if people want to have some filters on the left column and some on a right column?

cc @jarekmorawski for direction.

**Comment by jarekmorawski** [comment]
Good questions! Happy to answer them.

> What if people want to add blocks in-between filters?

They should be. The parent block should accept all block types, just like the Product Collection block.

> What if people want to have some filters on the left column and some on a right column?

We have little evidence to support this use case at the moment; it's an uncommon pattern. If the builders really wanted it, they'd add a second block and remove the filters they don't need.

**Comment by thealexandrelara** [comment]
Closed by #47294
