### ISSUE TITLE
Product Filters Redesign: Create a "Clear" button

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#46296]
## Description
This issue outlines the creation of a shared "Clear" button functionality within the redesigned Product Filters block. The goal is to provide users with a convenient way to reset selections applied across all child filter blocks (e.g., Filter by Price, Filter by Attribute, Filter by Ratings, etc).

## Current Behavior:

Currently, there is no dedicated way to clear selections within a single filter. 

## Expected Behavior:

- Create a "Clear" button within the Product Filters block that the child filter blocks can share.
- The Clear button block can only be added to a Filter Block (for example: Attribute Filter, Status Filter, etc)
- Clicking the "Clear" button removes all currently selected options within the specific filter.
- The "Clear" button must be locked and cannot be removed manually.

## Reference images

| Clear Button in the Blocks List View |
|--------|
| ![CleanShot 2024-04-05 at 17 36 01@2x](https://github.com/woocommerce/woocommerce/assets/20469356/af12b175-ecff-4a6c-8d37-1cf5e7586224) | 

| Clear Button in Editor |
|--------|
| ![CleanShot 2024-04-05 at 17 35 30@2x](https://github.com/woocommerce/woocommerce/assets/20469356/ec1cd2be-ffdc-449e-8435-d9c2ac602ffc) |

**Comment by roykho** [comment]
Currently, the `Active Filters` block have a `clear all` button. It functions to clear all filters on the page. Do we want to remove that in favor of the above proposed design? cc @jarekmorawski
