### ISSUE TITLE
Disable mobile app banner for full-screen flows such as Core Profiler, LYS, and CYS

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#46300]
### Issue description

When going through core profiler with mobile app, the iOS app banner is shown and pushes the screen downwards.

There was a discussion around this: p1710901299555949/1710896482.621579-slack-C01SFMVEYAK

<img src="https://github.com/woocommerce/woocommerce/assets/3747241/836b68a3-8db9-40d2-995b-2755f4a6d4a7" width="400">

#### To reproduce

1. Go to Setup Wizard with Safari/iPhone
2. Observe the mobile app banner is shown and pushes the screen downwards
3. This may apply to other screens such as CYS and LYS

### Acceptance criteria

1. Disable the mobile banner meta for the relevant screens

**Comment by moon0326** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/47429
