### ISSUE TITLE
[Launch Your Store] Woo-themed Confetti 🎊

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#46304]
### Issue description

We discussed about having Woo-themed confetti to better represent our brand. We'd like to explore: 

- Having a better animation
- Using Woo color palette

p1712367634736229/1712054131.047329-slack-C06DJHTE04U

### Acceptance criteria

1. Create a video with the confetti updates and share with the team
2. If approved, implement

**Comment by chihsuan** [comment]
I'm waiting for the feedback. p1712821722792219-slack-C06DJHTE04U.

But I think we could probably get this done during meetup. 🙂
