### ISSUE TITLE
A fatal error occurred after installation 🥶

### ISSUE THREAD

**Issue by lynn1286** [woothemes/woocommerce#46307]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm using `@woocommerce/create-woo-extension` scaffolding to create a development template, and everything went well, but when I built the zip package for installation, woocommerce prompted me to encounter a fatal error.

I'm new to PHP. I don't know what problem I encountered. This is the error log:
![image](https://github.com/woocommerce/woocommerce/assets/40122311/399a167b-0e30-460d-ac6f-37f250edb883)

### Expected behavior

I hope my plug-in can be used normally.

### Actual behavior

Uncaught Error: Failed opening required '/var/www/html/wp-content/plugins/woo-product-field//vendor/autoload_packages.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/woo-product-field/woo-product-field.php:22  

### Steps to reproduce

1. npx @wordpress/create-block -t @woocommerce/create-woo-extension woo-product-field
2. Enter the code
3. pnpm plugin-zip

### WordPress Environment

![image](https://github.com/woocommerce/woocommerce/assets/40122311/1457b107-4676-42ea-a003-ba49afe5a2c9)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @lynn1286,

Thanks for the report. Are you following [this guide](https://github.com/woocommerce/woocommerce/blob/trunk/docs/extension-development/building-your-first-extension.md) for creating an extension? If so can you confirm that you've run `npm install` ahead of trying to run `npm plugin-zip`?

Can you verify that you have composer installed and which version is installed? You can do this with `composer -V`.

**Comment by lynn1286** [comment]
> Hi @lynn1286,
> 
> Thanks for the report. Are you following [this guide](https://github.com/woocommerce/woocommerce/blob/trunk/docs/extension-development/building-your-first-extension.md) for creating an extension? If so can you confirm that you've run `npm install` ahead of trying to run `npm plugin-zip`?
> 
> Can you verify that you have composer installed and which version is installed? You can do this with `composer -V`.

Yes, I strictly followed the documentation for expansion development. After investigation, I found that the file package of `pnpm run plugin - zip` did not have a `vendor` dependency file. After I made the following configuration in `package.json`, the plugin package was installed. all the best.`
{
...
"files": [
  "/block.json",
  "/build",
  "/includes",
  "/languages",
  "/composer.json",
  "/composer.lock",
  "/mademine-woocommerce-plugin.php",
  "/README.md",
  "/vendor"
],
...
}
`
I don’t know if there are any hidden dangers in doing this.
