### ISSUE TITLE
Mini-Cart Throws Separator Errors With WooPayments Multi-currency set to EURO

### ISSUE THREAD

**Issue by AbhinavSakalle** [woothemes/woocommerce#46319]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using a block theme like Tsubaki or TwentyTwentyFour and having Multi-currency enabled with Euro added through WooPayments, adding an item to your cart with the currency set to Euro leads to an error when opening the Mini-cart, as shown in the linked screenshot.

However, if you deactivate Multi-currency in WooPayments or switch the currency back to USD, the Mini-cart functions correctly without any issues.

### Expected behavior

Ideally, the Mini-cart should show the products in Euro when applicable and not throw errors.

### Actual behavior

When you turn on the Multi-currency feature in WooPayments and set the Euro as the currency for orders, you might encounter an unexpected error on the Mini-cart if you're using a block theme. This error specifically points out issues in two files: **woocommerce/mini-cart-products-table-block** and **woocommerce/mini-cart-footer-block**:

```Error: Decimal separator can't be same as thousand separator. thousandSeparator: , (thousandSeparator = {true} is same as thousandSeparator = ",") decimalSeparator: , (default value for decimalSeparator is .)```

Deactivating the Multi-currency feature in WooPayments resolves the problem.

### Steps to reproduce

1. Use a block theme like Tsubaki or TwentyTwentyFour
2. With WooPayments, enable Multi-currency and add Euro
3. Add an item to cart making sure the selected currency is Euro
4. Open the Mini-cart and it will show this error: https://d.pr/i/OwUFXe
5. Deactivate Multi-currency in WooPayments or change the currency to USD and the mini-cart works finethe 

### WordPress Environment

Tested on clean install in the following environment and also happening on a user's site:

WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5
WP Memory Limit: 512 MB

WooPayments: by Automattic – 7.4.0
WooCommerce: by Automattic – 8.7.0
Theme: Twenty Twenty-Four

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ralucaStan** [comment]
Thank you for taking the time to report this @AbhinavSakalle. This will be fixed as part of https://github.com/woocommerce/woocommerce/pull/46241 so I am going to close this issue.  

The fix will land in WooCommerce 8.9

**Comment by ralucaStan** [comment]
To fix this issue you will need until the WooCommerce 8.9 release you will need to set the thousand separator to something other than `,`, mostly. Either a space ` ` or `'` are generally accepted.
