### ISSUE TITLE
New Product Editor > attribute association > add atttibute : first list term is selected by default

### ISSUE THREAD

**Issue by Marc-pi** [woothemes/woocommerce#46311]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you associate your product to an attribute term, the first term is by defaut selected

### Expected behavior

Don't auto-select the first entry in the attribute term list

### Actual behavior

the first list entry is auto-selected, which can lead to a wrong association / wrong data
the user has to unselect first, adding an unusefull extra step in the product management process

### Steps to reproduce

1. Create a attribute with several terms
2. Edit your product to link it from the Organization tab to one attribute
3. You'll notice that in any case, the first list entry is auto-selected,

### WordPress Environment

WP6.5 / Woo8.7 / Gutenberg 18

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
Hello @Marc-pi!
Thanks for opening this issue. I have not been able to reproduce it.
Could you clarify what you mean by `link it from the Organization tab to one attribute`?
What I tried to do to link it to an attribute is edit a product and go to the `Attributes` tab in the `Product Data` section:
<img width="829" alt="Screenshot 2024-08-19 at 10 48 35" src="https://github.com/user-attachments/assets/c6b21362-4f43-48d8-ac56-5130da6436b4">
But I don't see any auto-selected attribute.

Thank you!

**Comment by Marc-pi** [comment]
Hello,
i've just activated back the new product Editor, seems it works right actually on 9.1x
but so far it has been fixed in between (my tests were on Woo 8.7 / 2024, April)
thanks, i close the issue, will reopen if needed
