### ISSUE TITLE
Shop archive title isn't updating in the block-based theme

### ISSUE THREAD

**Issue by shameemreza** [woothemes/woocommerce#46318]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you use a block-based theme like the Twenty Twenty-Four theme and try to edit the page title under Pages > All Pages, you will notice that the changes don't reflect on the front end. But this works fine with a classic theme.

![CleanShot 2024-04-07 at 10 54 05](https://github.com/woocommerce/woocommerce/assets/14240438/d7e3d5b7-be50-4148-a1a4-e300f17f69fd)

### Expected behavior

The shop app title should change according to the page title (Pages > All Pages).

### Actual behavior

No matter the theme we choose, the page title should be updated as updated in the page edit.

As a temporary workaround, I followed these steps to make it work:

* Navigate to Appearance > Site Editor > Templates and select Product Catalog
* Remove the Archive title block and insert a heading block to manually add the shop title.
* Save the template, and done.

![CleanShot 2024-04-07 at 11 03 21](https://github.com/woocommerce/woocommerce/assets/14240438/6ed91b69-f4e4-44ae-86ff-b865ac20766d)

### Steps to reproduce

* Install and activate Twenty Twenty-Four
* Change the Shop page title in Pages > All Page.
* Visit the Store page.
* The title should change as set on the page edit, but it always shows shop as the title.

### WordPress Environment

* WC 8.7.0
* Twenty Twenty-Four 1.1
* WordPress 6.5
* PHP 8.1.27
* No additional plugins or customization

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Hebhansen** [comment]
Also this does not work in the above configuration:

// Change Shop title to something other
add_filter( 'woocommerce_page_title', 'new_woocommerce_page_title');

function new_woocommerce_page_title( $page_title ) {

if( $page_title == 'Shop' ) {
return "Art Fair";
}

**Comment by Marc-pi** [comment]
related to https://github.com/woocommerce/woocommerce/issues/42234 :-)

**Comment by samueljseay** [comment]
Thank you very much for raising this! 🙌 

I'll also note that editing the page directly and changing the contents of the heading block doesn't work.

All these behaviours combined are certainly confusing and I agree it's a bug. I've asked our team to take a look at this, but can't commit to a timeline on a fix for this at the moment.

**Comment by Aljullu** [comment]
I agree that the boundaries between the Shop page and the Product Catalog template are confusing, we have an issue to improve that: https://github.com/woocommerce/woocommerce/issues/42152.

In the meanwhile, there are two ways you can change the title of the Shop page in block themes:

1. Go to Appearance > Editor > Templates > Product Catalog and change the _Archive Title_ block to a custom h1 title with the text you want. Note: this will also change the title of the Products by Category, Products by Tag and Products by Attribute templates, so you will need to modify those ones later if you want them to have a different title.
2. You can also add this PHP snippet to override [this filter](https://github.com/woocommerce/woocommerce/blob/de54195c3ab3a091c3c406984622b61a6f8fa413/plugins/woocommerce/src/Blocks/BlockTemplatesController.php#L556-L578):

```PHP
add_action('init', function() {
	add_filter( 'post_type_archive_title', function( $post_type_name, $post_type ) {
		if (
			function_exists( 'is_shop' ) &&
			is_shop() &&
			'product' === $post_type
		) {
			return __( 'Our products', 'woocommerce' );
		}

		return $post_type_name;
	}, 20, 2 );
} );
```

**Comment by Aljullu** [comment]
Once again, thanks folks for opening this issue!

I tried to reproduce again with `trunk` and it seems to have been fixed. If I'm not mistaken, it was fixed in https://github.com/woocommerce/woocommerce/pull/48255, which will land in WooCommerce 9.1. cc @WunderBart 

Based on that, I will close this issue. But feel free to reopen if you think that's a mistake.

**Comment by paaljoachim** [comment]
Ahh so this issue has been fixed. Good!
I happen to make a duplicate issue here: https://github.com/woocommerce/woocommerce/issues/48510 (I will go ahead and close it.)
