### ISSUE TITLE
[Enhancement]: Default the stock quantity to 0

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#46342]
Revert the changes added in https://github.com/woocommerce/woocommerce/issues/37117 and default the stock quantity to 0.

When a product with enabled stock management is added without specifying a stock value, the product form defaults the stock quantity to 1, whereas in other areas of the system it's null. This inconsistency leads to unexpected increases in stock quantity to 1 when the product is subsequently edited and saved by a user, without any action taken to change the stock value.

The expected behavior is to automatically assign a zero value to the stock instead of `null` or `1`.

For additional details https://github.com/woocommerce/woocommerce/issues/39475

**Comment by pmcpinto** [comment]
@octaedro should we close https://github.com/woocommerce/woocommerce/issues/39475 to avoid having 2 issues about the same topic?

**Comment by octaedro** [comment]
> should we close https://github.com/woocommerce/woocommerce/issues/39475 to avoid having 2 issues about the same topic?

Good call @pmcpinto, I just closed the issue.
