### ISSUE TITLE
[Launch Your Store] Launch Your Store task item should not be clickable once completed

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#46352]
#  Issue Description

On the WC Home onboarding task list, after the store is launched the LYS task will show as completed.

This is confusing to users as it leads back to the LYS task as if the store hasn't been launched.

Figma Discussion: 0BWMerqRR1f468EwC7g5tg-fi-2761_12024

![Image](https://github.com/woocommerce/woocommerce/assets/27843274/5c440728-bf5c-47af-abbc-41a88662f161)

# Acceptance Criteria
- The task list item should not be clickable once the task has been completed
- Instructions on how to undo this for development and testing purposes

**Comment by chihsuan** [comment]
> Instructions on how to undo this for development and testing purposes

Hey @rjchow  👋  With https://github.com/woocommerce/woocommerce/pull/46358,  the LYS task will sync with `woocommerce_coming_soon` option. Do you think we still need to have a way to undo this for development and testing purposes? We can change site visibility back to `coming soon` to make the LYS task show as incomplete and clciakble again. Let me know what you think. 🙏

**Comment by rjchow** [comment]
I think just documenting the option in that PR will do ☺️
