### ISSUE TITLE
Replace ComboboxControl with Ariakit equivalent

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#46357]
The current Combobox provided by `@wordpress/components` should be removed and replaced with the [Ariakit combobox](https://ariakit.org/components/combobox).

This work should not be undertaken until the Country and State inputs have been changed to use select fields. https://github.com/woocommerce/woocommerce/issues/47757

The main reason we feel the combobox is not suitable for these fields is its unpredictability when it comes to handling user input and autocomplete. Address autocompletion is a very important thing to get right in the checkout flow and having a degraded experience is likely to harm conversion rates. The main issues with autocomplete are:

- Chrome autocomplete works differently to 1Password autocomplete
- There is no good way to check if a browser autocomplete is being used or if the user was typing
- When using autocomplete, this bug (https://github.com/woocommerce/woocommerce/issues/44653) occurs where United States addresses keep the dropdown list open, this is because there are two matches for United States (United States (US) and United States (US) Minor Outlying Islands)

With this said, we can remove this complex autocomplete functionality and allow the combobox to be used in other applications, such as in the Additional Checkout Fields API.

**Comment by opr** [comment]
This issue is blocked by https://github.com/woocommerce/woocommerce/issues/47757

**Comment by samueljseay** [comment]
I've added PR #50975 which will remove the last mention of the old component, and after that this can be closed.
