### ISSUE TITLE
Woo.com Reference in the Inbox During Onboarding

### ISSUE THREAD

**Issue by alvarothomas** [woothemes/woocommerce#46427]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

During the onboarding process, there's a Woo.com reference in the 'inbox' section: "Connect to Woo.com"

### Expected behavior

The caption should be "Connect to WooCommerce".

### Actual behavior

One of the messages landing on the Inbox, suggests the user to connect with Woo.com instead of WooCommerce.

<img width="1189" alt="Screenshot 2024-04-10 at 14 34 26" src="https://github.com/woocommerce/woocommerce/assets/29686881/1e6b22b2-8945-4de6-8958-9aa0ef347b27">

When clicking “Connect” the expected WooCommerce reference is correct in here.

<img width="1511" alt="Screenshot 2024-04-10 at 14 35 28" src="https://github.com/woocommerce/woocommerce/assets/29686881/7426ca79-f1d4-42cb-8a5c-365e85d30613">
<img width="558" alt="Screenshot 2024-04-10 at 14 39 06" src="https://github.com/woocommerce/woocommerce/assets/29686881/621f0e6c-a5b0-4a1f-b561-065905c7cba6">

### Steps to reproduce

1. Start a new site with WooCommerce installed
2. Before customizing your store, scroll down on WooCommerce/Home
3. Scroll down until "Inbox" section is displayed
4. Notice the "Connect to Woo.com" message

### WordPress Environment

WordPress 6.5.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Note that the issue is not present on new installs of 8.8. However, upgrading from 8.7 to 8.8 does not overwrite the inbox message.
