### ISSUE TITLE
[New k6 Perf Test]: Verify the page title and footer of a page

### ISSUE THREAD

**Issue by juliaamosova** [woothemes/woocommerce#46439]
### Describe the solution you'd like

In p1712762933174399/1712740857.054269-slack-C7YPW6K40, Atomic shared a list of assertions from their smoke tests that need to be added to our k6 perf tests. 

For example, Atomic tests for the page title and the footer of a `/blog` page below to ensure that the page had completely loaded:
```php
$this->deploy_checks['pool1']['https://xxx.yyy.zzz/blog/'] = array(
    sprintf( '/%s/', preg_quote( '<title>Blog &#8211; Site Title</title>', '/' ) ),
    sprintf( '/%s/', preg_quote( '<a href="https://wordpress.com/?ref=footer_website" target="_blank" title="WordPress.com - The Best eCommerce Platform for WordPress" rel="author">Built with Storefront &amp; WordPress.com</a>', '/' ) ),
);
```

In the k6 perf tests, we can add similar assertions to the tests inside the `plugins/woocommerce/tests/performance/requests/shopper` directory, which will partially address https://github.com/woocommerce/woocommerce/issues/46431 as well.

**Comment by rodelgc** [comment]
This task is very much related to https://github.com/woocommerce/woocommerce/issues/46440 so I went ahead and created a single PR for both of these two issues: https://github.com/woocommerce/woocommerce/pull/46485
