### ISSUE TITLE
[New E2E Test]: Verify API endpoint response in browser

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#46436]
### Describe the solution you'd like

In p1712762933174399/1712740857.054269-slack-C7YPW6K40, Atomic shared a list of assertions from their smoke tests that need to be added to our E2E tests. 

For example, the Atomic smoke tests include a scenario where the response from the `/hello` endpoint would be displayed on the browser:
```php
$this->deploy_checks['pool1']['https://xxcx.yyy.zzz/wp-json/wpcom/v2/hello'] = array(
    sprintf( '/^%s$/', preg_quote( '{"hello":"world"}', '/' ) ),
);
```
We can have a similar assertion added to the `basic.setup.js` e2e test.

**Comment by juliaamosova** [comment]
After reviewing this issue we decided not to proceed with implementing it because we already have it covered. What this test does is verify if the site has been loaded and didn't get killed which we check with other tests in our test suite.
