### ISSUE TITLE
[New k6 Perf Test]: Verify the page title of a product page

### ISSUE THREAD

**Issue by juliaamosova** [woothemes/woocommerce#46440]
### Describe the solution you'd like

In p1712762933174399/1712740857.054269-slack-C7YPW6K40, Atomic shared a list of assertions from their smoke tests that need to be added to our k6 perf tests. 

For example, Atomic tests for the page title of the product page for "Beanie" in the snippet below:
```php
$this->deploy_checks['pool1']['https://xxx.yyy.zzz/product/beanie/'] = array(
    sprintf( '/%s/', preg_quote( '<title>Beanie &#8211; Site Title</title>', '/' ) ),
    '/<h1\s+[^>]*class="[^"]*\bentry-title\b[^"]*"[^>]*>\s*Beanie/i'
);
```

We have a number of k6 tests that navigate to product pages, so adding an assertion for their page titles will allow the tests to be in sync with the Atomic smoke tests.

**Comment by rodelgc** [comment]
This task is very much related to https://github.com/woocommerce/woocommerce/issues/46439 so I went ahead and created a single PR for both of these two issues: https://github.com/woocommerce/woocommerce/pull/46485

**Comment by juliaamosova** [comment]
This issue is closed via https://github.com/woocommerce/woocommerce/pull/46485.
