### ISSUE TITLE
Two `wc/store/v1/cart/select-shipping-rate` requests included in the batch request when changing shipping method

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#46470]
### Issue

When changing shipping method in the Cart and Checkout blocks, it sends the request in a batch request. This batch request actually contains two requests to `wc/store/v1/cart/select-shipping-rate`. It should really only contain one request to this endpoint.

<img width="440" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/d91e03a2-3e9c-4080-a32a-9161c5bcd358">

### To reproduce

1. Create multiple shipping methods for a zone
2. Add an item to your cart and go to the Checkout block.
3. Fill in your address so it shows up the shipping methods
4. Change shipping method and observe the network monitor of your dev tools.
5. Notice that only one batch request is made, but it contains two `wc/store/v1/cart/select-shipping-rate` requests.

### Expected result

Only one request should be included in the batch request.

**Comment by wavvves** [comment]
One quick thing to add, I think we should re-evaluate our abuse of batch requests. We're using it everywhere, even for coupon adding, most contain only one single request, and won't be needing to add more. Doing batch involves more server overhead parsing it.

I'm adding this task to our backlog for planning.

**Comment by esschul** [comment]
We have this as well

**Comment by esschul** [comment]
@opr This was fixed in 9.2.0 Looks like it skips the whole batch thing now. Think this can be closed.
* Fix - Accessibility: Prevent shipping losing focus when making selections during checkout. [#48370](https://github.com/woocommerce/woocommerce/pull/48370)

**Comment by opr** [comment]
@esschul thanks for clarifying. I'll close this then, but if anything similar pops up we can reopen.
