### ISSUE TITLE
[Enhancement]: Block-based checkout - "Country" field should be first in the address form.

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46513]
### Describe the solution you'd like

This issue contains the following task: 
- [ ]  "Country" field should be first in the address form (moved over from #46013). 

Regarding the country selector, [Baymard states the following](https://baymard.com/premium/guideline-collections/ahnvda/565):
> If not using geotargeting, the "country" field should be first in the address form, as the other address fields depend on this

In https://github.com/woocommerce/woocommerce/issues/46013#issuecomment-2031715160, @opr clarified that adjusting the order of the checkout fields is possible and in https://github.com/woocommerce/woocommerce/issues/46013#issuecomment-2032253092, he shared the following code:

```php
add_filter('woocommerce_get_country_locale', function($locale) {
	$locale['CA']['postcode']['priority'] = 1;
	return $locale;
} );
```

> [!WARNING]
> When implementing this change, we need to be careful not to break backwords compatibility, see also [Reorder Checkout Fields](https://rudrastyh.com/woocommerce/reorder-checkout-fields.html).

**Comment by nielslange** [comment]
@pmcpinto Based on your comment in https://github.com/woocommerce/woocommerce/issues/46013#issuecomment-2036686777, I assume that you want this change to be implemented, correct?
> based on @opr comments, it looks like it's possible to move the country to the top. This will also be useful in the future, if we introduce an address autocomplete feature.

**Comment by pmcpinto** [comment]
> @pmcpinto Based on your comment in https://github.com/woocommerce/woocommerce/issues/46013#issuecomment-2036686777, I assume that you want this change to be implemented, correct?

Yes, as this is part of @nikkivias proposals to improve the experience, as long as there is a low risk of breaking backwards compatibility. Thanks.

**Comment by nielslange** [comment]
> > @pmcpinto Based on your comment in [#46013 (comment)](https://github.com/woocommerce/woocommerce/issues/46013#issuecomment-2036686777), I assume that you want this change to be implemented, correct?
> 
> Yes, as this is part of @nikkivias proposals to improve the experience, as long as there is a low risk of breaking backwards compatibility. Thanks.

Thanks for confirming this, @pmcpinto.

**Comment by ralucaStan** [comment]
@woocommerce/rubik had some concerns about the impact of this change so I'd like to hear more from the team about what they see as problematic if we were to work on  `Country" field should be first in the address form`.

The team also expressed some concerns about making this an opt-in or not, about limiting it per country etc.

**Comment by pmcpinto** [comment]
Thanks. It would be helpful to hear the concerns as it will shape how we implement this.

**Comment by senadir** [comment]
The main concern is that, do we want to move this field by default but still let it be changed by developers (as it stands right now) or do we want to force it to the top (like we do with email field)?

That's the main concern I have, the other one being that we need to communicate this in case some people have strong opinions.

**Comment by pmcpinto** [comment]
@senadir thanks for your feedback.

> The main concern is that, do we want to move this field by default but still let it be changed by developers (as it stands right now) or do we want to force it to the top (like we do with email field)?

I think we should move it to the top, but allow 3PDs to change the order. Do you see any cons from a shopper experience POV?

**Comment by senadir** [comment]
If we can also support hiding/disabling the field if it's a single country shop, that would be great. I don't see much issues. either that, or we move country a bit higher (after first and last name).

**Comment by nielslange** [comment]
@senadir What do you mean by _"[...] or we move country a bit higher (after first and last name)."_? I'm asking as this issue aims to place the country field above all other fields.

**Comment by senadir** [comment]
I was the under the assumption that's how Shopify does it (First Name, Last Name, Country, rest of address fields). I was wrong

<img width="653" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6165348/107468a6-053d-4e9b-aa18-d8e356932240">

**Comment by nielslange** [comment]
Thanks for clarifying this, @senadir.

**Comment by pmcpinto** [comment]
Thanks for the feedback. We can move forward with the proposed scope as long as we allow developers to change the order and don't have any backward compatibility issues.
