### ISSUE TITLE
Add WC REST API documentation for the endpoint to "Duplicate product"

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#46537]
The PR https://github.com/woocommerce/woocommerce/pull/46141 added a new REST API endpoint to `duplicate a product`.

As part of the efforts to enhance [WooCommerce REST API documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction), we should document that endpoint to keep the documentation up to date.

[This is](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php#L66-L113) the endpoint's code.

```[tasklist]
### Tasks
- [ ] Create the missing WooCommerce REST API documentation for the endpoint to duplicate a products
```

**Comment by octaedro** [comment]
This repo [WooCommerce REST API docs](https://github.com/woocommerce/woocommerce-rest-api-docs) handles the API REST documentation. It seems like we should add a `.md` to [this folder](https://github.com/woocommerce/woocommerce-rest-api-docs/tree/trunk/source/includes/wp-api-v3).

**Comment by louwie17** [comment]
This has been addressed as part of: https://github.com/woocommerce/woocommerce-rest-api-docs/pull/244
I will close this issue.
