### ISSUE TITLE
[Enhancement]: Add Coupons Column in the order list 

### ISSUE THREAD

**Issue by TheRadicalDreamer** [woothemes/woocommerce#46554]
### Describe the solution you'd like

I would like to be able to see the coupons used on each order in the order list view.
Like this:
![image](https://github.com/woocommerce/woocommerce/assets/11801254/6561c843-8310-4ad7-9619-8e8c20836a8e)

### Describe alternatives you've considered

I have coded myself a solution:

```
add_filter( 'manage_edit-shop_order_columns', 'create_coupon_column' );
       function create_coupon_column( $columns ) {
       $new_columns = array();
    
        foreach ( $columns as $column_key => $column_label ) {
            if ( 'order_total' === $column_key ) {
                $new_columns['order_coupons'] = __('Coupons', 'woocommerce');
            }
    
     $new_columns[$column_key] = $column_label;
        }
        return $new_columns;
    }
    
    add_action( 'manage_shop_order_posts_custom_column' , 'show_order_coupons' );
    function show_order_coupons( $column ) {
        global $the_order, $post;
        if( $column  == 'order_coupons' ) {
            if( $coupons = $the_order->get_coupon_codes() ) {
                echo implode(', ', $coupons);
            } else {
                echo '-';
            }
        }
    }
```

### Additional context

This is very useful to give you an idea about who is using X coupon on the fly.

**Comment by lsinger** [comment]
Hello @TheRadicalDreamer,

Thank you for this idea. However, for new feature requests, we'd like you to [submit a feature request here](https://woocommerce.com/feature-requests/woocommerce/) -- GitHub issues should be used for more developer-oriented enhancement requests. I'll close this here, but please do submit it as a feature request.

**Comment by TheRadicalDreamer** [comment]
Thanks, but i cannot submit an issue/feature request on Woo if i don't have a site hosted in Wordpress.com  :/


There is a way you can help me with this?

**Comment by lsinger** [comment]
> Thanks, but i cannot submit an issue/feature request on Woo if i don't have a site hosted in Wordpress.com :/
> 
> There is a way you can help me with this?

Hey @TheRadicalDreamer,

You don't need a site -- you just need a WordPress.com account. This is how we ensure we can contact you again in case we have questions or update you in case there's been progress. Hope that helps!

**Comment by TheRadicalDreamer** [comment]
Sorry, if this is out of the scope. But the woocommerce feature request site cannot be logged in. I am trapped in a eternal loop.
[Screen recording 2024-04-17 14.59.09.webm](https://github.com/woocommerce/woocommerce/assets/11801254/5d9d81d4-9ccf-4d29-85f2-d06c149e7b93)

So i thought i had to notify this, so if you send more people there, it might be a dead end.
