### ISSUE TITLE
Admin banner appears on non-store pages when setting is "store pages only"

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#46574]
When a site is in coming soon mode and "store pages" only, the admin banner does not need to appear.

Steps to reproduce:

1. Enable coming soon mode and toggle "Restrict to store pages only" on.
2. View the front-end homepage as an admin.
3. The footer banner incorrectly appears. It should only appear on store pages.

## Current Behavior

The banner unexpectedly appears on the homepage:
![Image](https://github.com/woocommerce/woocommerce/assets/9312929/46121f86-d06b-4c1c-ad29-7699e1d04beb)

**Comment by chihsuan** [comment]
Closing the issue.

I was able to reproduce the issue on the trunk. I believe the issue has been fixed.
