### ISSUE TITLE
[Launch Your Store] Private link is page specific when used when "Restrict to store pages only" is enabled

### ISSUE THREAD

**Issue by findingsimple** [woothemes/woocommerce#46575]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the coming soon page settings - when private link sharing is used in conjunction with the  "Restrict to store pages only" setting, the private key needs to be added to all restricted pages.

However when "Restrict to store pages only" is disabled the share link just needs to be user once on any page to make all the pages accessible for the user.

Possibly to do with the scope of the cookie perhaps? 

When "Restrict to store pages only" is on

/shop/?woo-share=xxxxx
/my-account/?woo-share=xxxxx
/cart/?woo-share=xxxxx

vs

When "Restrict to store pages only" is off 

/?woo-share=xxxxx - gets you access to all pages /shop, /my-account, /cart 

https://github.com/woocommerce/woocommerce/assets/355014/ca94a6ce-0946-402d-bb2b-b523fd94e196

### Expected behavior

Loosely held opinion - once private link is used all pages should becoming visible.

### Actual behavior

When the private link (?woo-share=xxxxx query parameter) is used on a page e.g. `/shop/?woo-share=xxxxx` all other private pages are still restricted.

### Steps to reproduce

1. Enable Coming Soon site visibility with "Restrict to store pages only" and "Share your site with a private link"
2. Copy the private link it should be the store shop url e.g. `/shop/?woo-share=UgCWitjWAIumAdXU522VvwmJQOiQqvVA`
3. Clear your browser cache and go to the link - it should be visible
4. Try and go to `/my-account/` it will still be private
5. Try and go to `/cart/` it will still be private
6. Add the share link to cart or my-account links and they will be accessible too

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rjchow** [comment]
It's indeed the scope of the cookie, this PR from yesterday addresses it: https://github.com/woocommerce/woocommerce/pull/46571

**Comment by findingsimple** [comment]
Thank @rjchow !
