### ISSUE TITLE
[Enhancement]: Block-based checkout - Update address fields display logic (sub issue)

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46581]
### Describe the solution you'd like

> [!IMPORTANT]
> This is a sub issue of #46512 and serves as the foundation for #46582.

This issue contains the following tasks:
- [ ] Allow merchants to make the `Address line 2` field required. → new functionality
- [ ] Allow merchants to control the display logic of all address fields via radio buttons. → updated functionality
- [ ] Hide the `Address line 2` field behind a link (moved over from #46013) when it's marked as optional. → new functionality

## Screenshot

> [!CAUTION]
> While the screenshot shows the labels `Optional (Recommended)`, the wording should be `Optional`. See https://github.com/woocommerce/woocommerce/issues/46581#issuecomment-2089942170 and https://github.com/woocommerce/woocommerce/issues/46581#issuecomment-2092348383

![CleanShot 2024-04-09 at 11 00 24@2x](https://github.com/woocommerce/woocommerce/assets/3323310/6c8cde08-3fe6-4ddc-92c7-285f6ae1ced6)

### Display logic

> [!NOTE]
> The display logic below affects the `Conmany name`, `Address line 2`  and `Phone number` fields.

- When the corresponding field is enabled, it's visible in the checkout form, independent if it's optional or required.
- When the corresponding field is set as required, the checkout form cannot be submitted when the field is empty.
- When the corresponding field is set as optional, the checkout form can be submitted even when the field is empty.
- When the `Address line 2` field is set to required, it's visible by default.
- When the `Address line 2` field is set to optional, it's hidden behind a link called `+ Add apartment, suitenumber, etc.`
- When the `Address line 2` field is set to optional, but it contains text, it's visible by default. It remains visible, when the seller empties the field during the checkout.

**Comment by pmcpinto** [comment]
@nikkivias I'm not 100% confident that we should have (recommended) as it can be heavily influenced by the merchant's business/goals. I'd drop it for now.

**Comment by dominique-vias** [comment]
Alright, agreed

**Comment by nielslange** [comment]
@pmcpinto and @nikkivias As discussed by you, I've removed the wording `(recommended)`.
