### ISSUE TITLE
[Enhancement]: Block-based checkout - Apply address fields display logic to My Account section (sub issue)

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46582]
### Describe the solution you'd like

> [!IMPORTANT]
> This is a sub issue of #46512 and builds on top of the sub issue #46581. 

This issue contains the following task:
- [ ] The display logic of the address fields (as implemented in #46581) should be reflected within the address forms of the My Account area (`/my-account/edit-address/`).

### Display logic

> [!NOTE]
> The display logic below affects the `Conmany name`, `Address line 2`  and `Phone number` fields.

- When the corresponding field is enabled, it's visible in the address forms, independent if it's optional or required.
- When the corresponding field is set as required, the address form cannot be submitted when the field is empty.
- When the corresponding field is set as optional, the address form can be submitted even when the field is empty.

### Similar issue

- https://github.com/woocommerce/woocommerce/issues/45717

**Comment by nielslange** [comment]
I haven't had time to work on this issue yet, so I'll unassign myself and move it back to the backlog to ensure others can take it on.

**Comment by ralucaStan** [comment]
moving this to cycle 4

**Comment by ralucaStan** [comment]
Marking as blocked. The team is uncertain if we need to proceed with this, considering the scenario where a store can use multiple checkout blocks. We need to find valid use cases that would explain work on this issue.

**Comment by senadir** [comment]
This is done via https://github.com/woocommerce/woocommerce/pull/52784
