### ISSUE TITLE
[CFT Custom fields]: Fix tooltip copy

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#46606]
Under the Products > Add New > Organization. Modify the tooltip wording from "_or internal inventory organization_" to  “_or **for** internal inventory organization_”.

<img width="1096" alt="screenshot-2024-04-14-at-07 21 22" src="https://github.com/woocommerce/woocommerce/assets/1314156/07e33652-6249-4237-90a8-43811afa52e3">

**Comment by mdperez86** [comment]
Done in https://github.com/woocommerce/woocommerce/issues/46540
