### ISSUE TITLE
[CFT Custom fields]: Allow adding multiple custom fields with the same name

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#46612]
It's not possible to add multiple custom fields with the same name, but that's actually possible in the legacy editor.
The multiple fields with the same name show up in the list until the product is saved.

![Screen Recording on 2024-04-15 at 05-53-10](https://github.com/woocommerce/woocommerce/assets/1314156/57301ed4-45d5-4e5a-b8d8-fabc1a8d99b2)

**Comment by mdperez86** [comment]
For now the api does not allow to add multiple custom fields with the same name so this issue is going to be tacked when the API gets correctly implemented in https://github.com/woocommerce/woocommerce/issues/46541

**Comment by octaedro** [comment]
This issue is duplicated. Closing this in favor of https://github.com/woocommerce/woocommerce/issues/46920
