### ISSUE TITLE
Updating WC by uploading a zip file does not trigger the site visibility tour

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#46620]
### Problem

Updating WC version to the latest by uploading a zip file does not trigger the site visibility tour.

### Steps to reproduce

1. Create a new JN site with WooCommerce Beta only.
2. Upload a previous version of WooCommerce (e.g, 8.7.0)
3. Complete the core profiler.
4. Go to `Plugins` and upload the latest WooCommerce with the launch your store included.
5. Enable `launch-your-store` feature flag.
6. Go to `WooCommerce -> Home`

I've noticed that manually uploading a zip file to update the WC version does not trigger the [update function](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-update-functions.php#L2673).

**Comment by adrianduffell** [comment]
@moon, I think we can close this out? 🤔

**Comment by moon0326** [comment]
@adrianduffell Yup! The tour appears after the DB update. Closing it.
