### ISSUE TITLE
Cursor does not change state when hovering the Mini-Cart icon

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46625]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

All menu items display a pointer cursor on hover, signaling interactivity. However, the Mini-Cart icon is an exception; hovering over it does not change the cursor. There is a minor color change, but this might not be noticeable to visually impaired users, potentially leading them to think the icon is not clickable.

### Expected behavior

The cursor should change to a pointer on hover over the Mini-Cart icon, consistent with other interactive menu elements.

### Actual behavior

The cursor does not change to a pointer on hover over the Mini-Cart icon.

### Steps to reproduce

1. Install and activate the [Twenty Twenty-Four](https://wordpress.org/themes/twentytwentyfour/) theme.
2. Go to `Appearance » Editor » Patterns » Header » Header`.
3. Add the `Customer account` icon to the header.
4. Ensure that the `Mini-Cart` icon is also in the header

<img width="950" alt="Screenshot 2024-04-16 at 12 41 20" src="https://github.com/woocommerce/woocommerce/assets/3323310/a2d2f7c0-ec6b-4379-9bdc-bba4f70cefa1">

5. Go to the frontend.
6. Hover over the menu items. 
7. See that the cursor changes to a pointer.
8. Hover over the `Customer account` icon.
9. See that the cursor changes to a pointer.
10. Hover over the `Mini-Cart` icon.
11. See that the cursor does not change to a pointer.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mdperez86** [comment]
I tried to reproduce this issue in the following environment.

- WordPress v6.6.1
- WooCommerce v9.3.0-dev
- Gutenberg v18.9.0
- Twenty Twenty-Four theme v1.2

I could not see the bug described here.
- I followed the testing instructions.
- I also moved the Mini-Cart to the beginning of the Header, before, inside and after the navigation.

https://github.com/user-attachments/assets/627fd6a7-5b03-4ebe-88cd-0a117c09a25a
