### ISSUE TITLE
the way to update metabox field on order add/edit after recent update.

### ISSUE THREAD

**Issue by Arifursdev** [woothemes/woocommerce#46635]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

the recent update i think woo. moved from post type to new table. so after adding some metaboxes using
```php
add_action('add_meta_boxes', [$this, 'display_meta_boxes']);
```

on order add/save from dashboard > woocommerce > orders > order
it doesn't seem to run the "save_post" action

```php
add_action( 'save_post', [$this, 'save_order_metabox'], 10 );

public function save_order_metabox( $post_id ) {
     file_put_contents( __DIR__ . '/logs.json', json_encode( $_POST, JSON_PRETTY_PRINT ), FILE_APPEND ); // doesn't run
}
```

### Expected behavior

when order is saved or manually add, it should run save_post or somekind of action in order to modify the values or do something when before/after values are saved.

### Actual behavior

?

### Steps to reproduce

add metabox on woocommerce order add/edit page, and try to save it when order is added/updated.

### WordPress Environment

WooCommerce version:  8.7.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by helgatheviking** [comment]
With HPOS enabled... orders are not _posts_ in the database... so `save_post` would never be called. I'm not a Woo employee but that doesn't seem like a bug to me. 

I think you'd be better suited to update your code to work with the Woo CRUD and save on:
[`woocommerce_before_order_object_save`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L209)
[`woocommerce_after_order_object_save`](https://github.com/woocommerce/woocommerce/blob/eb75902c4cb5001e94db69eac6d8bf7c7b790b5f/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L230)

few more options... which exist in both the legacy orders as post system _and_ HPOS so compatible with both automatically:
`woocommerce_new_order` [cpt](https://github.com/woocommerce/woocommerce/blob/eb75902c4cb5001e94db69eac6d8bf7c7b790b5f/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L103) | [hpos](https://github.com/woocommerce/woocommerce/blob/eb75902c4cb5001e94db69eac6d8bf7c7b790b5f/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2511)
`woocommerce_update_order` [cpt](https://github.com/woocommerce/woocommerce/blob/eb75902c4cb5001e94db69eac6d8bf7c7b790b5f/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L196) | [hpos](https://github.com/woocommerce/woocommerce/blob/eb75902c4cb5001e94db69eac6d8bf7c7b790b5f/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2609)

**Comment by Arifursdev** [comment]
> I think you'd be better suited to update your code to work with the Woo CRUD and save on: [`woocommerce_before_order_object_save`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L209) [`woocommerce_after_order_object_save`](https://github.com/woocommerce/woocommerce/blob/eb75902c4cb5001e94db69eac6d8bf7c7b790b5f/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L230)
> 

I see, I was not aware of that. Thank you for your kind reply.
