### ISSUE TITLE
Product Block Editor: Variations option sections hidden in mobile

### ISSUE THREAD

**Issue by retrofox** [woothemes/woocommerce#46641]
<img width="747" alt="image" src="https://github.com/woocommerce/woocommerce/assets/77539/5cd305a3-0cc6-433c-876e-42bbf4f160e4">

**Comment by pmcpinto** [comment]
I'll closing this, as we already have one issue about this topic: #45641

**Comment by retrofox** [comment]
💯 thanks, Pedro
