### ISSUE TITLE
Fields using incorrect IDs in the Product Block Editor 

### ISSUE THREAD

**Issue by Rahmon** [woothemes/woocommerce#46659]
The IDs of the fields `Hide in product catalog` and `Hide from search results` are inverted:

![image](https://github.com/woocommerce/woocommerce/assets/6010232/a0c747c9-43fb-4be2-ba71-4412d9d44573)

- Hide in product **catalog**
   - id: product-catalog-**search**-visibility
- Hide from **search** results
   - id: product-catalog-**catalog**-visibility

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Features/ProductBlockEditor/ProductTemplates/SimpleProductTemplate.php#L456

**Comment by mattsherman** [comment]
@Rahmon This actually appears correct to me, if a bit confusing. The UX in the new product editor is using the "hide" case, so these are flipped a bit from what you'd expect. But, you see that the `visibility` attribute is set correct on each block.

Please let me know and provide detailed reproduction steps if you still believe this to be incorrect.

**Comment by kmanijak** [comment]
It's been couple of months with no response hence I'm closing the issue. But please be aware the closed issues can still be commented on.
