### ISSUE TITLE
 Individual variations screens are not scrollable in the new product editor

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#46677]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

It's not possible to scroll under variation pages.

![Screen Recording on 2024-04-17 at 09-00-39](https://github.com/woocommerce/woocommerce/assets/1314156/7d61cf4f-bbee-4509-bc4b-213aa54d252c)

[This code](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/products/product-page.scss#L78-L82) adds the `overflow: hidden`.

### Steps to reproduce

1. Having the new product editor enabled.
2. Go to Products > Add New.
3. Create a product with a few variations.
4. Select one variation you created in the `Variations` tab.
5. On the variation page, try to scroll down.
6. It won't work. 

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@louwie17 this bug should be investigated and fixed in time to be included in 8.9. AFAIK they'll release 8.8.2 in the upcoming days, but I don't think it will be possible to include this fix. Pls keep me posted. Thanks
