### ISSUE TITLE
Product types, traits, and templates audit

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#46676]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

This issue is to do an audit on the technical limitations around templates for a bundle of plugins.
The plugins to test together:
- Subscriptions
- All Products for Woo Subscriptions
- Memberships
- Name your price
- Bonus: a page builder like Elementor Pro

Have a look at how these plugins interact or not interact with each other and answer some of the below questions.
Keep in mind the initial standards around the new templating system and try to figure out if there are any limitations to this approach when working with a bundle of plugins.

**Bonus**
- Create a couple sample templates for each plugin in the new product editor.

### Standards

Here are the standards that we should keep in mind as we conduct this audit for each plugin:
- Require developers who want to **add extra fields** to the Standard Product template to support all core features of it (Shipping, Inventory, Attributes, Variations, Downloads, etc) Meaning to **disallow the developer to control the visibility/availability of Core Standard Product template features.**
- Guide developers who want to replace entire areas or fields to first examine if a new type/template would make more sense.
- Carefully consider under which conditions (and how) to allow 3PDs to replace Core fields in the Standard Product template.

### Each Audit should contain answers to these questions:

Assuming the plugin extends the product editor screen:
- Does the plugin create a new product type or trait?
    - What fields get added to this product type?
    - Does it hide any core fields? ( like price/shipping/etc… )
    - Does it replace any core fields? ( like price/shipping/etc… ) and if so, does the data format of the field stay the same?
- Does the plugin extend the simple product?
    - What fields get added?
    - Does it hide any core fields? ( like price/shipping/etc… )
    - Does it replace any core fields? ( like price/shipping/etc… ) and if so, does the data format of the field stay the same?
- Does the plugin extend any of the other core types/traits ( digital / affiliate / grouped )
- Does the plugin add fields that are type / trait independent? ( Meaning it’s available on everything ), also for variations? 
    - Does it also remove or replace fields across all types / traits?

- If yes to removing or replacing any of the core fields:
    - Is it possible for the plugin to continue working without touching core fields? 
    - Would a new template make sense for this plugin? Why? Why not?
    - If replacing core fields, those it drastically change the data? 
- Did the plugin contain any edge cases that may impact our product template management? 
- Anything else worth mentioning?

**Comment by mattsherman** [comment]
Initial audit results shared internally. Public discussion will follow after internal discussion.

pcQJnU-2yY-p2

**Comment by louwie17** [comment]
Closing this as this has been published and a discussion has been created and finished: https://github.com/woocommerce/woocommerce/discussions/48026

Follow up work will be in new issues.
