### ISSUE TITLE
REST API order price item is wrong

### ISSUE THREAD

**Issue by VSBam** [woothemes/woocommerce#46695]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,
there is a problem with the price field in the order line_items derived from API.
If the price in the product page is for example 12.99 while deriving the product prices via API in the order (https://www.example.com/wp-json/wc/v3/orders/13?consumer_key=ck_XXX&consumer_secret=cs_XXX) the price is like this:

![image](https://github.com/woocommerce/woocommerce/assets/937723/554d3d50-a21a-4a53-a642-2800d86e8483)
 
line_items price has many more numbers after the comma than those defined in woocommerce settings.

I've tested this in a fresh wordpress installation with only woocommerce as plugin and 1 product.
If in /woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php after this line:
`$data['price'] = $item->get_quantity() ? $item->get_total() / $item->get_quantity() : 0;`
you use wc_format_decimal the price return right like the price in the page product.

### Expected behavior

The expected behaviour is having the price of the order in line_items retrived by REST API with the number after the comma as defined in woocommerce settings.

### Actual behavior

Due to division by quantity the result of line_items price in order retrived by REST API has more number after the comma than the numbers defined in woocommerce settings.

### Steps to reproduce

1. make a product with a float price
2. make an order
3. retrieve the order by REST API
4. check the price in line_items

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://tst3.visib italy.com
Site address (URL): https://tst3.visib italy.com
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 150 MB
PHP Time Limit: 5400
PHP Max Input Vars: 12000
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.44-log
Max Upload Size: 150 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wpts_
Total Database Size: 4.83MB
Database Data Size: 3.13MB
Database Index Size: 1.70MB
wpts_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpts_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpts_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpts_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpts_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpts_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpts_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wpts_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wpts_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpts_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpts_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpts_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpts_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpts_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpts_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpts_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpts_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpts_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpts_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpts_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpts_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order_placehold: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.7.0

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 92 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/visibitaly/tst3.visibitaly.com/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/visibitaly/tst3.visibitaly.com/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/visibitaly/tst3.visibitaly.com/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-18 11:19:34 +00:00
Options: ✔
Notes: 68
Onboarding: skipped

### Action Scheduler ###

Complete: 15
Oldest: 2024-04-04 11:20:45 +0000
Newest: 2024-04-17 15:11:16 +0000

Failed: 1
Oldest: 2024-04-04 11:21:48 +0000
Newest: 2024-04-04 11:21:48 +0000

Pending: 1
Oldest: 2024-04-18 15:09:52 +0000
Newest: 2024-04-18 15:09:52 +0000

### Status report information ###

Generated at: 2024-04-17 16:51:39 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi @VSBam, thanks for your report. Do you know if that order was created via checkout in the shop page or manually in the admin area of the site?

**Comment by VSBam** [comment]
Hi @Konamiman, the order was create on frontend through checkout.
Thanks.

**Comment by naman03malhotra** [comment]
Hey @VSBam, I tried to reproduce this issue with the following steps, but I am not able to

1. I created a product from wp-admin dashboard and set the price in float.
2. I placed an order via the checkout flow.
3. I fetched that order using the API and observed the following,

Can you please check if I am missing something.



![Image](https://github.com/woocommerce/woocommerce/assets/15019298/0dc97996-d034-4748-a3ee-483b8422784a)

**Comment by naman03malhotra** [comment]
Closing this for now, please feel to reopen it with more specific instructions
<img width="298" alt="image" src="https://github.com/woocommerce/woocommerce/assets/15019298/71ded3c3-b029-4838-85a5-8517f4aa0ee4">
