### ISSUE TITLE
Relocate helper (child) themes

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46746]
### Describe the solution you'd like

While working on #45780, I noticed that one of the helper themes `theme-with-woo-templates`, which is used for our Playwright e2e2 tests, is still located at `plugins/woocommerce-blocks/tests/mocks` while our other helper child themes are located at `plugins/woocommerce-blocks/tests/e2e/bin/themes`. Apart from the different locations, where we store the helper (child) themes, I also noticed that we're using two different ways of installing them when setting up our e2e environment:

### 1. Installing via `.wp-env`

The helper theme `theme-with-woo-templates`, which is located at `plugins/woocommerce-blocks/tests/mocks`, gets installed via `.wp-env`. This is the part, that installs this and other themes: https://github.com/woocommerce/woocommerce/blob/05a728ff03e7cbee0d170655ee08794336532963/plugins/woocommerce-blocks/.wp-env.json#L20-L26

### 2. Installing via `wp theme`

The helper child themes `storefront-child__block-notices-filter`, `storefront-child__block-notices-template`, `storefront-child__classic-notices-template`, `twentytwentyfour-child__block-notices-filter`, `twentytwentyfour-child__block-notices-template` and `twentytwentyfour-child__classic-notices-template`, which are located at `plugins/woocommerce-blocks/tests/e2e/bin/themes`, are first zipped so that they can be installed via `wp theme install`. In case there's already a corresponding zip file available, it gets deleted before generating the new zip. This step ensures that the zip file contains the latest modifications of the corresponding helper child theme. This is the part, that generates the zip files and deletes existing zip files, if available: https://github.com/woocommerce/woocommerce/blob/05a728ff03e7cbee0d170655ee08794336532963/plugins/woocommerce-blocks/tests/e2e/bin/test-env-setup.sh#L9-L35

In `plugins/woocommerce-blocks/tests/e2e/bin/scripts/parallel/themes.sh`, we're then deleting already installed themes via `wp theme delete` and install the desired helper child themes via `wp theme install`. This is the part that deletes existing and installs the desired helper child themes: https://github.com/woocommerce/woocommerce/blob/05a728ff03e7cbee0d170655ee08794336532963/plugins/woocommerce-blocks/tests/e2e/bin/scripts/parallel/themes.sh#L9-L23

## Benchmark

I was keen in seeing which of these approaches is faster. While I had the gut feeling that the `.wp-env` approach is faster than the `wp theme delete`/`wp theme install` approach, I decided to measure the time it requires to set up the e2e environment. I ran both`pnpm env:start` and `pnpm env:restart` 5 times each against both approaches. These are the results:

<table>
    <tr>
        <td></td>
        <td>Installing via <strong>.wp-env</strong>:</td>
        <td>Generating a zip file and installing via <strong>wp theme install</strong>:</td>
    </tr>
    <tr>
        <td><strong>pnpm env:start</strong></td>
        <td>~ 50s</td>
        <td>~ 1m 10s</td>
    </tr>
    <tr>
        <td><strong>pnpm env:restart</strong></td>
        <td>~ 55s</td>
        <td>~ 1m 15s</td>
    </tr>
</table>

As expected, the `.wp-env` approach is faster than deleting and generating zip files and deleting and installing the themes via the `wp theme` command.

## Proposed changes

- Move the helper child themes `storefront-child__block-notices-filter`, `storefront-child__block-notices-template`, `storefront-child__classic-notices-template`, `twentytwentyfour-child__block-notices-filter`, `twentytwentyfour-child__block-notices-template` and `twentytwentyfour-child__classic-notices-template` from `plugins/woocommerce-blocks/tests/e2e/bin/themes` to `plugins/woocommerce-blocks/tests/e2e/themes`. Earlier, there were located at `plugins/woocommerce-blocks/tests/e2e/bin/themes` to be inside the folder that contains the setup scripts.
- Move the helper theme `theme-with-woo-templates` from `plugins/woocommerce-blocks/tests/mocks` to `plugins/woocommerce-blocks/tests/e2e/themes`.
- Install all helper (child) themes via `.wp-env` instead of via `wp theme`.

> [!NOTE]
> Our helper plugins are currently located at `plugins/woocommerce-blocks/tests/e2e/plugins`. To further streamline our file organization and complement existing structures, I suggest relocating the helper (child) themes to `plugins/woocommerce-blocks/tests/e2e/themes`. This adjustment would help us maintain consistency and simplify navigation across our project resources.

cc: @WunderBart and @gigitux I'm keen in hearing your thoughts on my proposed changes.

**Comment by WunderBart** [comment]
Nice catch! I'm all for moving them to be installed via the `.wp-env.json` config. Faster, cleaner, and less maintenance! 🚀
