### ISSUE TITLE
[BUG] Wrong Dimension lead in PickupDelivery to convert error

### ISSUE THREAD

**Issue by pustekuchen91** [woothemes/woocommerce#46776]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I report this error for a friend. i dont own any instance of wocommerce.

wc_get_dimension will lead to an type error (string * float)  if dimension is a string. This seems to happen if the dimensions are not filled propertly  / complete

https://github.com/woocommerce/woocommerce/blob/007a4238c3956e3de3c33a95b3138093c11c01c7/plugins/woocommerce/includes/wc-formatting-functions.php#L130

wc_get_dimension  is called in woocommerce-germanized-shiopments/src/PickupDelivery.php (378)

### Expected behavior

dimension should be checked

### Actual behavior

dimension is not checked and can lead to type conversion error

### Steps to reproduce

1. Do not fill dimension propertly
2. add an item to the cart 

### WordPress Environment

*

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pustekuchen91** [comment]
PickupDelivery seems to come from an plugin
https://plugins.trac.wordpress.org/browser/woocommerce-germanized/trunk/packages/woocommerce-germanized-shipments/src/PickupDelivery.php#L378

`wc_get_dimension` is called with invalid parameter

**Comment by jonathansadowski** [comment]
Hi @pustekuchen91,

Thanks for the report. As you've pointed out, the underlying issue appears to be in a 3rd party plugin, and should probably be reported to its authors. The function `wc_get_dimension` is documented as accepting int or float for its first parameter.

I'm going to mark this issue as an enhancement request and assign it to our developers to get their opinion on whether we should be more lenient with the dimension parameter, but the bug seems to be coming from [Germanized](https://wordpress.org/plugins/woocommerce-germanized/).

**Comment by vedanshujain** [comment]
I think we can probably cast the `$dimension` param to float if it's not float already [https://github.com/woocommerce/woocommerce/blob/007a4238c3956e3de3c33a95b3138093c1[…]1c01c7/plugins/woocommerce/includes/wc-formatting-functions.php](https://github.com/woocommerce/woocommerce/blob/007a4238c3956e3de3c33a95b3138093c11c01c7/plugins/woocommerce/includes/wc-formatting-functions.php#L119)

**Comment by albarin** [comment]
The bug was fixed in the `Germanized` plugin some months ago: https://github.com/vendidero/woocommerce-germanized-shipments/commit/f71602617678c771ee814d9263d4fd0394bf8c7b
