### ISSUE TITLE
error in loading pictures while updating a product

### ISSUE THREAD

**Issue by Aymenjnayah** [woothemes/woocommerce#46784]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I can't upload any image or pdf file whenever i want to update the details of a product .

### Expected behavior

i want to upload files  

### Actual behavior

the page freezes at the console shows upload script error ,

### Steps to reproduce

<img width="704" alt="image" src="https://github.com/woocommerce/woocommerce/assets/91474315/82a8b24b-1a4c-4dec-996b-9c2ad05262d0">
<img width="704" alt="Screenshot 2024-04-22 124916" src="https://github.com/woocommerce/woocommerce/assets/91474315/a9b011b3-d81a-4a25-a8df-0b403161ceba">

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://v1.objetsdesign.com
Site address (URL): https://v1.objetsdesign.com
WC Version: 8.8.2
REST API Version: ✔ 8.8.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 640 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.3.3
PHP Post Max Size: 300 Mo
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB-1:10.6.17+maria~deb11-log
Max Upload Size: 300 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.2
WC Database Prefix: wp_1064740_
Taille totale de la base de données: 25.17MB
Taille de la base de données: 18.99MB
Taille de l’index: 6.18MB
wp_1064740_woocommerce_sessions: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_1064740_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_actionscheduler_actions: Données : 1.52MB + Index : 0.97MB + Moteur InnoDB
wp_1064740_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_actionscheduler_logs: Données : 1.52MB + Index : 0.47MB + Moteur InnoDB
wp_1064740_aioseo_cache: Données : 0.11MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_aioseo_crawl_cleanup_blocked_args: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_aioseo_crawl_cleanup_logs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_aioseo_notifications: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_aioseo_posts: Données : 0.39MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_comments: Données : 0.05MB + Index : 0.09MB + Moteur InnoDB
wp_1064740_frmt_form_entry: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_1064740_frmt_form_entry_meta: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_1064740_frmt_form_reports: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_frmt_form_views: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_gla_attribute_mapping_rules: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_gla_budget_recommendations: Données : 0.19MB + Index : 0.14MB + Moteur InnoDB
wp_1064740_gla_merchant_issues: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_gla_shipping_rates: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_gla_shipping_times: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_jetpack_sync_queue: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_mailchimp_carts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_mailchimp_jobs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_options: Données : 6.03MB + Index : 0.19MB + Moteur InnoDB
wp_1064740_postmeta: Données : 5.31MB + Index : 1.89MB + Moteur InnoDB
wp_1064740_posts: Données : 2.11MB + Index : 0.22MB + Moteur InnoDB
wp_1064740_snippets: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_term_relationships: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_usermeta: Données : 0.17MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_1064740_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_wc_admin_note_actions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_1064740_wc_orders_meta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_1064740_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_wc_product_attributes_lookup: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_wc_product_meta_lookup: Données : 0.05MB + Index : 0.09MB + Moteur InnoDB
wp_1064740_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_wdp_orders: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_1064740_wdp_order_items: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_1064740_wdp_persistent_rules_cache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_wdp_rules: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_1064740_wpforms_logs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_wpforms_payments: Données : 0.02MB + Index : 0.14MB + Moteur InnoDB
wp_1064740_wpforms_payment_meta: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_1064740_wpforms_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_1064740_yith_wcwl: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_1064740_yith_wcwl_lists: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB

### Post Type Counts ###

attachment: 229
b2bking_custom_role: 3
b2bking_group: 1
custom_css: 4
customize_changeset: 50
forminator_forms: 1
jetpack_migration: 2
nav_menu_item: 48
page: 47
post: 26
product: 93
product_variation: 158
project: 8
revision: 206
shop_order_placehold: 13
team: 3
testimonial: 2
tpt-global-rule: 6
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 3
wpmnotifications: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

WooCommerce Tiered Price Table (Premium): par u2Code – 4.2.3
All in One SEO Pack: par L’équipe All in One SEO – 4.6.0
Code Snippets: par Code Snippets Pro – 3.6.4
Contact Form 7: par Takayuki Miyoshi – 5.9.3
Yoast Duplicate Post: par Enrico Battocchi & l’équipe Yoast – 4.5
MonsterInsights - Google Analytics pour WordPress: par MonsterInsights – 8.26.0
Google Listings and Ads: par WooCommerce – 2.6.6
WP Armour - Honeypot Anti Spam: par Dnesscarkey – 2.1.19
Easy HTTPS (SSL) Redirection: par Tips and Tricks HQ – 1.9.2
Instant Images: par Darren Cooney – 6.1.2
Jetpack: par Automattic – 13.3.1
Éditeur de page: par Michael M - WPBakery.com – 7.4
MC4WP : Mailchimp pour WordPress: par ibericode – 4.9.11
New User Approve: par WPExpertsio – 2.5.3
One Click Demo Import: par OCDI – 3.2.1
Pinterest pour WooCommerce: par WooCommerce – 1.3.24
Seese Core: par VictorThemes – 2.3
UpdraftPlus - Sauvegarde/Restauration: par UpdraftPlus.Com
DavidAnderson – 1.24.2

Variation Swatches for WooCommerce: par CartFlows – 1.0.8
Visual Email Builder: par Sushil Kumar – 1.2
WooCommerce.com Update Manager: par Automattic – 1.0.2
WooCommerce Quantity Increment: par Automattic
WooThemes – 1.1.0

WooCommerce: par Automattic – 8.8.2
ShopLentor – WooCommerce Builder for Elementor & Gutenberg: par HasThemes – 2.8.5
WordPress Importer: par wordpressdotorg – 0.8.2
WP-PageNavi: par Lester 'GaMerZ' Chan – 2.94.1
WP Super Cache: par Automattic – 1.12.0
WPForms Lite: par WPForms – 1.8.7.2
Custom Product Tabs for WooCommerce: par Code Parrots – 1.8.5
YITH WooCommerce Wishlist: par YITH – 3.31.0

### Inactive Plugins (6) ###

Forminator: par WPMU DEV – 1.29.3
Mailchimp for WooCommerce: par Mailchimp – 3.7
TikTok: par TikTok – 1.2.5
VOD Infomaniak: par Infomaniak Staff – 1.5.6
WooCommerce Tiered Price Table: par u2Code – 4.2.3
WooCommerce Wholesale Prices: par Rymera Web Co – 2.1.12

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 481 Ko

### WC Pages ###

Base de la boutique: #28837 - /boutique/
Panier: #28838 - /cart/
Commander: #28839 - /checkout/
Mon compte: #28840 - /my-account/
Conditions générales de vente et d’utilisation: #29298 - /nos-conditions-generales-de-ventes/

### Theme ###

Name: Seese
Version: 3.0.1
Author URL: https://victorthemes.com
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Archive Template: Votre thème a un fichier woocommerce.php
vous ne serez pas en mesure de substituer le modèle personnalisé woocommerce/archive-product.php étant donné que woocommerce.php a la priorité sur archive-product.php. Ceci vise à prévenir les problèmes d’affichage.

Overrides: seese/woocommerce/cart/cart-shipping.php version 3.6.0 est obsolète. La version du noyau est 8.8.0
seese/woocommerce/cart/cart-totals.php
seese/woocommerce/cart/cart.php version 4.4.0 est obsolète. La version du noyau est 7.9.0
seese/woocommerce/content-product.php
seese/woocommerce/content-single-product.php
seese/woocommerce/emails/customer-invoice.php
seese/woocommerce/emails/customer-new-account.php
seese/woocommerce/emails/customer-processing-order.php
seese/woocommerce/loop/loop-start.php
seese/woocommerce/myaccount/form-login.php version 6.0.0 est obsolète. La version du noyau est 7.0.1
seese/woocommerce/single-product/product-image.php version 3.5.1 est obsolète. La version du noyau est 7.8.0
seese/woocommerce/single-product/product-thumbnails.php
seese/woocommerce/single-product/related.php
seese/woocommerce/single-product/up-sells.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-04-23 10:25:36 +02:00
Options: ✔
Notes: 57
Onboarding: completed

### Action Scheduler ###

Terminé: 2 440
Oldest: 2024-04-05 12:26:39 +0200
Newest: 2024-04-22 13:49:46 +0200

Échoué: 16
Oldest: 2024-04-05 12:28:43 +0200
Newest: 2024-04-22 13:08:29 +0200

En attente: 15
Oldest: 2024-04-22 14:04:46 +0200
Newest: 2024-04-27 13:55:59 +0200

### Tiered Pricing Table ###

Tiered Pricing: Activation date: 
Tiered Pricing: Seen notifications: 

### Status report information ###

Generated at: 2024-04-22 13:50:52 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @Aymenjnayah,

Thanks for your report. It looks like you may have a non-default WordPress theme with several customizations. Are you able to reproduce this issue with either one of the default WordPress themes or [Storefront](https://woocommerce.com/products/storefront/)? If so, are there a series of steps that you're able to provide us that would allow us to recreate this issue?

**Comment by Aymenjnayah** [comment]
Hello @jonathansadowski ,
i didn't understand that , can you give me solution , I'm using a template that I purchased called seese , i tried to contact their it support but they are not working

**Comment by adimoldovan** [comment]
Hi @Aymenjnayah,
Can you try changing the theme from Seese to a default one, or to Storefront and try uploading an image again? We could then figure out if this is caused by the theme you're using or not.

**Comment by Aymenjnayah** [comment]
i did that , and it seems that the problem is caused by eaither seese or woocommerce

**Comment by adimoldovan** [comment]
> i did that , and it seems that the problem is caused by eaither seese or woocommerce

Thanks for testing that @Aymenjnayah. 
Can you be more specific? Is it still happening without `Seese`?

**Comment by Aymenjnayah** [comment]
when i  disabled seese , it works fine , so as a conclusion the problem is caused by  seese theme

**Comment by tammullen** [comment]
Thanks for checking, closing this issue, if you discover a WooCommerce bug free feel to open a new issue.

**Comment by Aymenjnayah** [comment]
No , it' not resolved yet , the seese theme that i payed for isn't working !
