### ISSUE TITLE
Summary field - line break isn't working

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#46803]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The line breaks added to the summary text aren't reflected on the product page. It connects all the text as if it was a single sentence. were

### Expected behavior

The line breaks should be reflected in the front-end, as the summary field can't be used by users who want to add more than one sentence.

### Actual behavior

See the screenshots:

<img width="747" alt="Captura de ecrã 2024-04-22, às 18 12 21" src="https://github.com/woocommerce/woocommerce/assets/3380168/3bfeef1b-e238-4a70-a0eb-b47762b7599b">
<img width="527" alt="Captura de ecrã 2024-04-22, às 18 12 43" src="https://github.com/woocommerce/woocommerce/assets/3380168/45691d4b-3d55-4520-b5b6-f43dd01e2025">

### Steps to reproduce

1. Open the new product form
2. At text to the summary field with at least one line break
3. Publish the product
4. View the product page and confirm that the line break isn't reflected in the front-end

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Marc-pi** [comment]
same as https://github.com/woocommerce/woocommerce/issues/39934
so same same as https://github.com/woocommerce/woocommerce-blocks/issues/10653, that will bring you to https://github.com/WordPress/gutenberg/issues/15117

if we can push the gutenberg team to fix this summer 2023 regression, would be fine :-)
ping https://github.com/woocommerce/woocommerce/issues/42071 poke @paaljoachim

**Comment by mattsherman** [comment]
Closing this as this is a core Gutenberg issue, as Marc-pi mentioned above: https://github.com/WordPress/gutenberg/issues/15117
