### ISSUE TITLE
Test all scripts with JSHint

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#4680]
The scripts should all be ran through JSHint and improved. This will reduce the likelihood of errors in browsers like IE.

**Comment by claudiosmweb** [comment]
@mikejolley @roykho I fix all our JavaScript files, all using jshint and now Grunt will check every time before using uglify on all files.
In other words, if you write JavaScript ugly, will not minify any file :P

**Comment by roykho** [comment]
@claudiosmweb :+1:

**Comment by shivapoudel** [comment]
+1
