### ISSUE TITLE
Single Order Screen > Custom Field metabox extreme slow query issue 

### ISSUE THREAD

**Issue by amans2k** [woothemes/woocommerce#46806]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the single-order screen. Custom Field meta box
![image](https://github.com/woocommerce/woocommerce/assets/6773011/36037502-1d8b-466f-95d9-1ee0f10a6479)

I upgraded my site from 8.7.0 to 8.8.2 and found that the query takes 45+ seconds every time.
![image](https://github.com/woocommerce/woocommerce/assets/6773011/c2eca5ba-d90b-47b6-a9b9-62bc5edddd65)

This is the end method which is executing inside the callback
woocommerce/src/Internal/DataStores/CustomMetaDataStore.php
![image](https://github.com/woocommerce/woocommerce/assets/6773011/650ced62-f62c-4b90-8f5b-c0e504b392a7)

Query used inside the function is 

`SELECT DISTINCT `meta_key` FROM `wp_wc_orders_meta` WHERE `meta_key` NOT LIKE '_%';` followed by order by and limit.

My 'Order meta' table has 1.6 million rows.

As per standards, if the query pattern involves a wildcard at the beginning of the string, as in LIKE '%value' or NOT LIKE '_%'. These patterns typically can't utilize indexes efficiently.
The LIKE '_%' condition is likely the main performance bottleneck. This condition forces a full scan because it needs to check the first character of every meta_key.

For high-volume store owners, this is performance-impacting.

### Expected behavior

The single order page should load fast and shouldn't take 40+ seconds.

### Actual behavior

The single order page always takes 45+ seconds to load the page because of the 'Custom Field' meta box.

### Steps to reproduce

1. Go to the Single Order screen
2. It will take time to load if the order meta table has many rows.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://xxxxxx.com
Site address (URL): https://xxxxxx.com
WC Version: 8.8.2
REST API Version: ✔ 8.8.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 60
PHP Max Input Vars: 3000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.17-MariaDB-1:10.6.17+maria~ubu2004
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.2
WC Database Prefix: wp_
Total Database Size: 3463.98MB
Database Data Size: 2096.20MB
Database Index Size: 1367.78MB
wp_woocommerce_sessions: Data: 9.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 5.52MB + Index: 9.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 11.52MB + Index: 4.50MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 134.67MB + Index: 65.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 13.02MB + Index: 14.83MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 8.22MB + Index: 6.22MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_campaigns: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_affiliate_wp_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_affiliate_wp_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creativemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_affiliate_wp_customers: Data: 0.25MB + Index: 0.19MB + Engine InnoDB
wp_affiliate_wp_custom_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_affiliate_wp_notifications: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_sales: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 15.52MB + Index: 2.52MB + Engine InnoDB
wp_bv_activities_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_abandonedcarts: Data: 3.52MB + Index: 0.17MB + Engine InnoDB
wp_bwfan_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automationmeta: Data: 0.33MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_automations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automation_complete_contact: Data: 74.61MB + Index: 15.06MB + Engine InnoDB
wp_bwfan_automation_contact: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_contact_claim: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_automation_contact_trail: Data: 302.84MB + Index: 319.20MB + Engine InnoDB
wp_bwfan_automation_events: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automation_step: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_broadcast: Data: 0.52MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_bulk_action: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_contact_automations: Data: 7.52MB + Index: 7.03MB + Engine InnoDB
wp_bwfan_contact_note: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_conversions: Data: 0.20MB + Index: 0.36MB + Engine InnoDB
wp_bwfan_engagement_tracking: Data: 65.63MB + Index: 79.27MB + Engine InnoDB
wp_bwfan_engagement_trackingmeta: Data: 102.64MB + Index: 6.52MB + Engine InnoDB
wp_bwfan_fields: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_field_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_form_feeds: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_import_export: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_link_triggers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_logmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_message: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_message_unsubscribe: Data: 0.19MB + Index: 0.52MB + Engine InnoDB
wp_bwfan_syncrecords: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_taskmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_tasks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bwfan_task_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_templates: Data: 9.52MB + Index: 0.19MB + Engine InnoDB
wp_bwfan_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_ab_experiments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_actions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwf_action_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_contact: Data: 8.52MB + Index: 7.92MB + Engine InnoDB
wp_bwf_contact_fields: Data: 6.52MB + Index: 27.55MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_conversion_tracking: Data: 1.09MB + Index: 2.27MB + Engine InnoDB
wp_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_wc_customers: Data: 3.52MB + Index: 0.36MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 86.61MB + Index: 46.09MB + Engine InnoDB
wp_email_log: Data: 344.58MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fk_cart_stats: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_fk_order_stats: Data: 5.52MB + Index: 22.52MB + Engine InnoDB
wp_fsmpt_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 16.17MB + Index: 2.16MB + Engine InnoDB
wp_oses_attachments: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_emails: Data: 3.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_failures: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_patchstack_event_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_patchstack_firewall_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_patchstack_logic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 388.88MB + Index: 266.58MB + Engine InnoDB
wp_posts: Data: 122.52MB + Index: 9.97MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 40.56MB + Index: 30.64MB + Engine InnoDB
wp_users: Data: 3.52MB + Index: 4.52MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 3.52MB + Index: 0.30MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 2.52MB + Index: 1.80MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 17.55MB + Index: 22.66MB + Engine InnoDB
wp_wc_orders_meta: Data: 193.73MB + Index: 346.38MB + Engine InnoDB
wp_wc_order_addresses: Data: 9.52MB + Index: 12.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.44MB + Index: 0.58MB + Engine InnoDB
wp_wc_order_operational_data: Data: 8.52MB + Index: 5.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 10.52MB + Index: 9.06MB + Engine InnoDB
wp_wc_order_stats: Data: 3.52MB + Index: 4.53MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfab_message_tracking: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wfacp_stats: Data: 1.52MB + Index: 1.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.30MB + Index: 0.00MB + Engine InnoDB
wp_wfco_connectormeta: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wfco_connectors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_report_views: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 12.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 2.02MB + Index: 0.20MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 1.02MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfob_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfocu_api_manager_secure_hash: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfocu_event: Data: 0.17MB + Index: 0.22MB + Engine InnoDB
wp_wfocu_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfocu_events_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfocu_event_meta: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_wfocu_session: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_api_manager_secure_hash: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xlutm: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_xlutmmeta: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 1
acf-field: 29
acf-field-group: 7
attachment: 328
custom_css: 1
elementor_library: 12
elementor-popup: 1
nav_menu_item: 8
oembed_cache: 16
omapi: 2
page: 49
post: 6
product: 91
product_variation: 218
revision: 2528
shop_coupon: xxxx
shop_order: xxxx
shop_order_refund: xxxx
shop_subscription: xxxx
wac_checkout: 1
wfacp_checkout: xxxx
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Query Monitor: by John Blackbourn – 3.15.0
Advanced Custom Fields PRO: by WP Engine – 6.2.9
AffiliateWP: by AffiliateWP – 2.24.2
AffiliateWP - Custom Affiliate Slugs: by Sandhills Development
LLC – 1.2

Code Snippets: by Code Snippets Pro – 3.6.4
Elementor Pro: by Elementor.com – 3.21.0
Elementor: by Elementor.com – 3.21.1
Email Log: by Sudar – 2.4.9
FunnelKit Funnel Builder Pro: by FunnelKit – 3.3.1
FunnelKit Funnel Builder: by FunnelKit – 3.3.1
Stripe Payment Gateway for WooCommerce: by FunnelKit – 1.8.0
JSM Show Post Metadata: by JS Morisset – 4.3.0
OptinMonster: by OptinMonster Popup Builder Team – 2.16.0
SlingBlocks – Gutenberg Blocks by FunnelKit (Formerly WooFunnels): by FunnelKit (formerly WooFunnels) – 1.4.0
User Switching: by John Blackbourn & contributors – 1.7.3
UTM Leads Tracker - XLPlugins: by XLPlugins – 1.2.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.5.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.8.0
Woo Subscriptions: by WooCommerce – 6.1.0
WooCommerce: by Automattic – 8.8.2
WP Crontrol: by John Blackbourn – 1.16.3
FunnelKit Automations Connectors: by FunnelKit – 2.8.0
FunnelKit Automations Pro: by FunnelKit – 3.0.beta.22042024
FunnelKit Automations: by FunnelKit – 3.0.beta-1713783972
WP Offload SES Lite: by Delicious Brains – 1.6.8

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 52 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /
Terms and conditions: #227 - /terms-conditions/

### Theme ###

Name: Astra Child
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.6.10 – 4.6.12 is available
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Outdated Templates: ❌

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://xxxxxx.com
Subscriptions-core Library Version: 6.9.0
Subscriptions Template Theme Overrides: astra-child/woocommerce/myaccount/subscription-details.php
astra-child/woocommerce/myaccount/subscription-totals.php
astra-child/woocommerce/myaccount/view-subscription.php

Subscription Statuses: wc-active: xxxx
wc-cancelled: xxxx
wc-expired: xxxx
wc-on-hold: xxxx
wc-pending: xxxx
wc-pending-cancel: xxxx

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ❌ No
Cache Update Failures: ❌ 3 failure

### Store Setup ###

Country / State: United States (US) — Delaware

### Subscriptions by Payment Gateway ###

Stripe Gateway: wc-active: xxxx
wc-cancelled: xxxx
wc-expired: xxxx
wc-on-hold: xxxx
wc-pending: xxxx
wc-pending-cancel: xxxx

PayPal Standard: wc-active: xxxx
wc-cancelled: xxxx
wc-expired: xxxx
wc-on-hold: xxxx
wc-pending: xxxx
wc-pending-cancel: xxxx

other: wc-active: xxxx
wc-cancelled: xxxx
wc-expired: xxxx
wc-on-hold: xxxx
wc-pending: xxxx
wc-pending-cancel: xxxx

### Payment Gateway Support ###

Stripe Gateway: products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
products
refunds
tokenization
add_payment_method
pre-orders

PayPal Standard: subscriptions
gateway_scheduled_payments
subscription_payment_method_change_customer
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ❌ No
Test Gateway: products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
refunds

Test Gateway: products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
refunds

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-04-23 11:06:21 +05:30
Options: ✔
Notes: 182
Onboarding: completed

### Action Scheduler ###

Complete: 29,850
Oldest: 2024-03-22 18:07:16 +0000
Newest: 2024-04-03 08:55:34 +0000

Failed: 25
Oldest: 2023-11-13 14:49:05 +0000
Newest: 2024-04-22 15:28:13 +0000

Pending: 5,053
Oldest: 2024-04-22 17:32:31 +0000
Newest: 2027-01-04 18:15:18 +0000

### Status report information ###

Generated at: 2024-04-22 22:58:58 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by naman03malhotra** [comment]
Hey @amans2k, thank you for raising this issue. The query in the latest version of [trunk](https://github.com/woocommerce/woocommerce/blob/dc2cf822f25f38581d575bf56c0a3e25f7be1675/plugins/woocommerce/src/Internal/DataStores/CustomMetaDataStore.php#L253) already has a fix for it, further I've raised https://github.com/woocommerce/woocommerce/pull/46985 to make it more performant. If you are comfortable editing the code yourself, please have a look at the PR or [trunk](https://github.com/woocommerce/woocommerce/blob/dc2cf822f25f38581d575bf56c0a3e25f7be1675/plugins/woocommerce/src/Internal/DataStores/CustomMetaDataStore.php#L253) and go head!

Here are some dates for the upcoming releases:

WooCommerce 8.9 Beta
- April 30, 2024

WooCommerce 8.9 RC
- May 7, 2024

WooCommerce 8.9 Release
- May 14, 2024
