### ISSUE TITLE
Product Collection: Product Categories Filter Only Supports First 10 Categories

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#46850]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you add a "Product categories" filter to a Product Collection block the UI will not necessarily let you select all of categories on your store.

### Expected behavior

You should be able to search for any category in your store and select it.

### Actual behavior

When taxonomy inspector controls are loaded they prefetch "all" of the terms for the taxonomy. This is done because the `FormTokenField` only accepts a list of string suggestions. We use this to map suggestions back to term IDs so that they can be assigned to the collection's query. Unfortunately, we're actually only selecting the first 10 terms. This means that even though terms will show up in the search they can't be selected since there is no ID to resolve to.

### Steps to reproduce

1. Ensure that you have more than 10 categories.
2. Create a Product Collection block.
3. Add a "Product categories" filter and attempt to add every category (just 11 or more unique ones)
4. You can double-check in the inspector and you'll see that only the categories in the initial `product_cat` query are usable. Any that aren't in this first request don't work.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
@adimoldovan is there a reason you labeled this for Mothra? pretty sure this is a block issue belonging to kirigami/origami

**Comment by adimoldovan** [comment]
> @adimoldovan is there a reason you labeled this for Mothra? pretty sure this is a block issue belonging to kirigami/origami

@samueljseay No specific reason, only a triage mistake. Feel free to re-label as you see fit.
