### ISSUE TITLE
[Enhancement]: Open Mini-Cart drawer in single product

### ISSUE THREAD

**Issue by wpchannel** [woothemes/woocommerce#46866]
### Describe the solution you'd like

The mini cart drawer block alllows us to open it automatically after adding a product to the cart. This only works in archive pages, not in single product page. The behavior is not consistent between pages and the description in block panel is not accurate. 

![image](https://github.com/woocommerce/woocommerce/assets/7568562/83fc94c0-3ff1-414f-bc38-a58ab15de374)

### Describe alternatives you've considered

At least, we should change the description by saying that single product pages are not concerned by this behavior.

The best enhancement would be to add this behavior for all pages using add to cart block button.

**Comment by nielslange** [comment]
Thanks for reaching out, @wpchannel, and for suggesting the changes. I'll add this issue to our backlog for now.

**Comment by Aljullu** [comment]
I think a blocker of this issue is that the Add to Cart button causes a page reload in the Single Product page (https://github.com/woocommerce/woocommerce/issues/36006), and that's why the Mini-Cart doesn't have the chance to open.

**Comment by nielslange** [comment]
> I think a blocker of this issue is that the Add to Cart button causes a page reload in the Single Product page (https://github.com/woocommerce/woocommerce/issues/36006), and that's why the Mini-Cart doesn't have the chance to open.

Thanks for adding that additional info, @Aljullu.

**Comment by ResponsiveFlow** [comment]
@nielslange the #36006 issue has been open for a while, it is a standard implementation in every modern ecommerce stores and it's still not possible with WooCommerce.
There are some themes that introduced that feature (through Ajax), but none of them are block themes.

**Comment by Aljullu** [comment]
@nielslange do you think we should mark this issue as a duplicate of https://github.com/woocommerce/woocommerce/issues/42638?

**Comment by nielslange** [comment]
> @nielslange do you think we should mark this issue as a duplicate of #42638?

Yes, that makes sense, @Aljullu. I missed the other issue when I added this one to the backlog.

**Comment by nielslange** [comment]
Closing this issue as a duplicate of #42638.
