### ISSUE TITLE
Creating a membership at checkout does not work with subscriptions.

### ISSUE THREAD

**Issue by 0xBeycan** [woothemes/woocommerce#46911]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For normal products, the user is created and set to order. 

However, in subscriptions, as you can see in the picture below, the user is created but not set to order. For this reason, Woo Subscription gives an error.

Maybe only subscriptions are created early.

![image](https://github.com/woocommerce/woocommerce/assets/50718965/dff0af7f-0d43-4128-a022-efa647ec6a15)

Json track logs: https://codeshare.io/ApDXOe

### Expected behavior

Normally, you should first set the user to the order and then create the subscription. Thus, there is no problem in creating a user at checkout.

### Actual behavior

However, during user creation on the checkout page, if the product is subscription, it gives this error “Invalid subscription customer_id.”

### Steps to reproduce

1. Make active in settings "Allow customers to create an account during checkout"
2. Create a normal product and a subscription
3. Try with a test payment gateway for payment and create user in checkout

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:3020
Site address (URL): http://localhost:3020
WC Version: 8.8.2
REST API Version: ✔ 8.8.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 500 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Debian)
PHP Version: 8.1.28
PHP Post Max Size: 500 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 11.2.2-MariaDB-1:11.2.2+maria~ubu2204
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.2
WC Database Prefix: wp_
Total Database Size: 58.51MB
Database Data Size: 40.70MB
Database Index Size: 17.81MB
wp_woocommerce_sessions: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.33MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_49df9_license: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 8.52MB + Index: 5.36MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 5.52MB + Index: 4.03MB + Engine InnoDB
wp_b2s_network_insights: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_b2s_posts: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_b2s_posts_drafts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_b2s_posts_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_b2s_posts_insights: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_b2s_posts_network_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_b2s_posts_sched_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_b2s_user: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_b2s_user_contact: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_b2s_user_network_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_active_plugins: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_bp_apf_payouts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bp_apf_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bp_deactive_plugins: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_bp_plugin_feedbacks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.30MB + Index: 0.23MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_cp_order_transaction: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_d261a_license: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_easywpsmtp_debug_events: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_activities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_conversations: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_fs_data_metrix: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_mail_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_persons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_products: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_taggables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_tag_pivot: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fs_tickets: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_index_now_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_dashboard_lockouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_firewall_rules: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_itsec_vulnerabilities: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.31MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.25MB + Index: 0.25MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 6.52MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.06MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.38MB + Index: 0.13MB + Engine InnoDB
wp_peachpay_analytics_interval: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_peachpay_analytics_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_peachpay_customer_cart: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_peachpay_customer_cart_contents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_peachpay_customer_cart_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 1.94MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.14MB + Engine InnoDB
wp_post_views: Data: 0.42MB + Index: 0.38MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_simple_history: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_simple_history_contexts: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wp_skrill_transaction_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.52MB + Index: 0.31MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.31MB + Index: 0.30MB + Engine InnoDB
wp_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_bp_apf_payouts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_bp_apf_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

amp_validated_url: 7
attachment: 155
cryptocurrency: 42
custom_css: 1
itsec-dash-card: 8
itsec-dashboard: 1
mailpoet_page: 1
nav_menu_item: 19
page: 16
plugin_repo: 1
post: 30
product: 17
product_variation: 22
revision: 150
shop_coupon: 70
shop_order: 102
shop_subscription: 61
wp_easy_pay: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (25) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
AMP: by AMP Project Contributors – 2.5.3
Solid Security Basic: by SolidWP – 9.3.2
Classic Widgets: by WordPress Contributors – 0.3
Code Syntax Block: by Marcus Kazmierczak – 3.1.1
CryptoPay Solana: by BeycanPress LLC – 1.3.1
CryptoPay Tron: by BeycanPress LLC – 1.2.0
CryptoPay: by BeycanPress LLC – 2.1.4
Custom Payment Gateway: by  – 1.0
Easy Table of Contents: by Magazine3 – 2.0.65
Easy WP SMTP: by Easy WP SMTP – 2.3.0
Fluent Support: by WPManageNinja LLC – 1.7.80
Licensor: by BeycanPress LLC – 2.4.3
MailPoet: by MailPoet – 4.48.2
IndexNow: by Collins Agbonghama – 2.6.5
Post Views Counter: by dFactory – 1.4.6
Payment Plugins for PayPal WooCommerce: by Payment Plugins
support@paymentplugins.com – 1.0.46

Redirection: by John Godley – 5.4.2
Simple History: by Pär Thernström – 4.14.0
Simple Login Notification: by Jeff Starr – 1.7
WooCommerce FreshBooks Integration: by BeycanPress LLC – 1.1.3
WooCommerce Stripe Gateway: by WooCommerce – 8.2.0
Woo Subscriptions: by WooCommerce – 6.2.0
WooCommerce: by Automattic – 8.8.2
Yoast SEO: by Team Yoast – 22.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 B

### WC Pages ###

Shop base: ❌ Page not set
Cart: #10 - /cart/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: #49 - /membership-and-sales-agreement/

### Theme ###

Name: BeycanPress
Version: 2.8.5
Author URL: https://beycanpress.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: beycanpress/views/woocommerce/form-checkout.php
beycanpress/views/woocommerce/payment.php version 7.8.0 is out of date. The core version is 8.1.0
beycanpress/views/woocommerce/terms.php
beycanpress/views/woocommerce/content-widget-product.php
beycanpress/views/woocommerce/breadcrumb.php
beycanpress/views/woocommerce/add-to-cart.php
beycanpress/views/woocommerce/tabs.php

Outdated Templates: ❌
					
					
						Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: http://beycanpress.com
Subscriptions-core Library Version: 7.0.0
Subscription Statuses: wc-active: 48
wc-pending-cancel: 5
wc-pending: 3
wc-on-hold: 3
wc-cancelled: 2

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Wyoming

### Subscriptions by Payment Gateway ###

Custom Payment Gateway: wc-active: 7
PayPal Gateway By Payment Plugins: wc-active: 12
wc-on-hold: 1
wc-pending-cancel: 1

other: wc-pending-cancel: 1
Stripe: wc-active: 29
wc-cancelled: 2
wc-on-hold: 2
wc-pending: 3
wc-pending-cancel: 3

### Payment Gateway Support ###

Custom Payment Gateway: products
subscriptions

CryptoPay: products
refunds
subscriptions

PayPal Gateway By Payment Plugins: tokenization
products
subscriptions
add_payment_method
subscription_cancellation
multiple_subscriptions
subscription_amount_changes
subscription_date_changes
default_credit_card_form
refunds
pre-orders
subscription_payment_method_change_admin
subscription_reactivation
subscription_suspension
subscription_payment_method_change_customer

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-01-06 02:05:15 +03:00
Options: ✔
Notes: 115
Onboarding: completed

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: http://localhost?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Canceled: 44
Oldest: -0001-11-30 01:55:52 +0155
Newest: -0001-11-30 01:55:52 +0155

Complete: 19,814
Oldest: 2023-12-05 07:15:05 +0300
Newest: 2024-02-16 11:01:10 +0300

Failed: 45
Oldest: 2023-05-10 10:24:22 +0300
Newest: 2023-11-19 06:50:10 +0300

Pending: 171
Oldest: 2024-04-25 05:59:30 +0300
Newest: 2025-03-25 06:11:42 +0300

### Status report information ###

Generated at: 2024-04-25 15:11:06 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by 0xBeycan** [comment]
The error is not exactly related to subscriptions. The error is exactly that the user is created on the checkout page but not set to order. It is never done.

**Comment by 0xBeycan** [comment]
The problem was caused by another plugin

**Comment by ArmourShawn** [comment]
I am experiencing the same error on checkout, what was the other plugin that was causing this error?

**Comment by 0xBeycan** [comment]
Hello, this was due to a plugin bug, the plugin was accidentally synchronizing the user id to 0. So you can try disabling your plugins.

**Comment by ArmourShawn** [comment]
Just start disabling all other plugins other than the WooSubscriptions?

**Comment by 0xBeycan** [comment]
Just try with WooCommerce and Subscriptions plugin

**Comment by ArmourShawn** [comment]
Much appreciated, I got it to go through, it was a WooCommerce CAPTCHA plugin interfering.
