### ISSUE TITLE
Upgrading WooCommerce to 8.8.x results in cron errors regarding to woocommerce_marketplace_fetch_promotions

### ISSUE THREAD

**Issue by remkus** [woothemes/woocommerce#46923]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

All of my clients have WP Cron running on server versus WordPress' internal cron. Since updating to WooCommerce 8.8.x I'm seeing this error report for all WooCommerce sites:

`Error: Error processing action 1448751: Scheduled action for woocommerce_marketplace_fetch_promotions will not be executed as no callbacks are registered.
`

### Expected behavior

Cron not to give any errors like it did for the 8.7.x branch.

### Actual behavior

Running WordPress 6.4.4, WooCommerce 8.8.2, WP Cron deferred to the server yields error message

### Steps to reproduce

1. Moved cron to server
2. See errors flood in

Not sure what else to say here besides the attached WordPress environment data and the explanation above. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): redacted
Site address (URL): redacted
WC Version: 8.8.2
REST API Version: ✔ 8.8.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 8.0.30
PHP Post Max Size: 50 MB
PHP Time Limit: 600
PHP Max Input Vars: 2000
cURL Version: 7.82.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 10.5.21-MariaDB-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.2
WC Database Prefix: 
Totale database grootte: 711.70MB
Database gegevens grootte: 515.51MB
Database index grootte: 196.19MB
woocommerce_sessions: Data: 5.02MB + Index: 0.08MB + Engine InnoDB
woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
woocommerce_order_itemmeta: Data: 37.56MB + Index: 18.02MB + Engine InnoDB
woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
actionscheduler_actions: Data: 38.58MB + Index: 27.03MB + Engine InnoDB
actionscheduler_claims: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
actionscheduler_logs: Data: 30.56MB + Index: 15.03MB + Engine InnoDB
adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
atum_product_data: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
commentmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
comments: Data: 10.52MB + Index: 10.08MB + Engine InnoDB
lecm_rewrite: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mailchimp_jobs: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
mclean_refs: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
member_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
options: Data: 41.44MB + Index: 1.27MB + Engine InnoDB
pmxe_exports: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
pmxe_posts: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
portfolio_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
postmeta: Data: 273.25MB + Index: 93.59MB + Engine InnoDB
posts: Data: 23.09MB + Index: 7.16MB + Engine InnoDB
product_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sb_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sitemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
termmeta: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
term_relationships: Data: 2.52MB + Index: 1.48MB + Engine InnoDB
term_taxonomy: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
usermeta: Data: 5.50MB + Index: 7.03MB + Engine InnoDB
users: Data: 0.36MB + Index: 0.28MB + Engine InnoDB
wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wcpdf_invoice_number_2021: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wcpdf_invoice_number_2022: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wcpdf_invoice_number_2023: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wc_admin_notes: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wc_customer_lookup: Data: 0.45MB + Index: 0.34MB + Engine InnoDB
wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_order_product_lookup: Data: 2.52MB + Index: 2.56MB + Engine InnoDB
wc_order_stats: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
wc_order_tax_lookup: Data: 0.41MB + Index: 0.34MB + Engine InnoDB
wc_product_attributes_lookup: Data: 0.14MB + Index: 0.08MB + Engine InnoDB
wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_product_meta_lookup: Data: 1.52MB + Index: 1.34MB + Engine InnoDB
wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfblockediplog: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wfconfig: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wffilemods: Data: 11.55MB + Index: 0.00MB + Engine InnoDB
wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfissues: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wfknownfilelist: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wflogins: Data: 0.41MB + Index: 0.17MB + Engine InnoDB
wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfnotifications: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wfstatus: Data: 0.28MB + Index: 0.16MB + Engine InnoDB
wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpr_rocket_cache: Data: 0.38MB + Index: 0.48MB + Engine InnoDB
wpr_rucss_used_css: Data: 1.52MB + Index: 1.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yoast_indexable: Data: 3.52MB + Index: 1.00MB + Engine InnoDB
yoast_indexable_hierarchy: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yoast_primary_term: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
yoast_prominent_words: Data: 0.33MB + Index: 0.59MB + Engine InnoDB
yoast_seo_links: Data: 0.52MB + Index: 0.30MB + Engine InnoDB

### Post Type Counts ###

attachment: 5362
atum_supplier: 21
br_labels: 14
cookielawinfo: 6
customize_changeset: 7
custom_css: 1
elementor_library: 2
nav_menu_item: 102
NIET_op_transaction: 2
op_transaction: 5791
op_z_report: 1318
page: 48
popup: 1
popup_theme: 8
porto_builder: 16
post: 43
postman_sent_mail: 186
product: 3153
product_variation: 1205
revision: 328
shop_coupon: 7
shop_order: 5906
shop_order_refund: 101
wcpcsu-custom-post: 1
wcps: 6
wcps_layout: 1
whatsapp-accounts: 1
wpcf7_contact_form: 2
wp_block: 1
wp_global_styles: 2
wp_navigation: 1
_op_receipt: 2
_op_register: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

ManageWP - Worker: door GoDaddy – 4.9.19
ATUM Voorraadbeheer voor WooCommerce: door Stock Management Labs ™ – 1.9.38
Classic Widgets: door WordPress Contributors – 0.3
Code Snippets: door Code Snippets Pro – 3.6.4
CookieYes | GDPR Cookie Consent: door CookieYes – 3.2.2
Yoast Duplicate Post: door Enrico Battocchi & Team Yoast – 4.5
Facebook for WooCommerce: door Facebook – 3.1.15
Site Kit by Google: door Google – 1.125.0
LitExtension Customer Password Plugin: door LitExtension – 1.0.0
LitExtension SEO Plugin: door LitExtension – 1.0.1
Mailchimp for WooCommerce: door Mailchimp – 4.0.1
Mailgun: door Mailgun – 1.9.9
Pinterest for WooCommerce: door WooCommerce – 1.3.24
PixelYourSite: door PixelYourSite – 9.5.5
Porto Theme - Functionality: door P-Themes – 3.0.3
Product GTIN (EAN, UPC, ISBN) for WooCommerce: door Emanuela Castorina – 1.1.1
Say What?: door Ademti Software – 2.2.2
Scanfully: door Scanfully – 1.1.2
Servebolt Optimizer: door Servebolt – 3.5.32
WooCommerce Sisow betaalmethoden: door Sisow – 5.5.8
Spectra: door Brainstorm Force – 2.12.9
Product Feed PRO for WooCommerce: door AdTribes.io – 13.3.2
WooCommerce.com Update Manager: door Automattic – 1.0.2
WooCommerce Advanced Product Labels: door BeRocket – 3.2.6.5
Booster for WooCommerce: door Pluggabl LLC – 7.1.9
Woocommerce - Openpos - WooCommerce Germanized: door anhvnit@gmail.com – 1.0
Woocommerce OpenPos Pending Payment: door anhvnit@gmail.com – 1.1
Woocommerce OpenPos: door anhvnit@gmail.com – 6.0.7.1
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.8.1
Product Slider for WooCommerce by PickPlugins: door PickPlugins – 1.13.49
WooCommerce: door Automattic – 8.8.2
WordPress Importer: door wordpressdotorg – 0.8.2
Yoast SEO Premium: door Team Yoast – 22.5
Yoast SEO: door Team Yoast – 22.5
WP Chat App: door NinjaTeam – 3.6.4
WP All Export - User Export Add-On Pro: door Soflyy – 1.0.7
Yoast SEO: WooCommerce: door Team Yoast – 16.2

### Inactive Plugins (6) ###

Contact Form 7: door Takayuki Miyoshi – 5.9.3
Google Analytics for WooCommerce: door WooCommerce – 2.0.6
WP All Export - ACF Export Add-On Pro: door Soflyy – 1.0.5
WP All Export - WooCommerce Export Add-On Pro: door Soflyy – 1.0.9
WP All Export Pro: door Soflyy – 1.8.3
WP Rocket: door WP Media – 3.15.0.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: door GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dagen
Level threshold: –
Log directory size: 105 MB

### WC Pages ###

Winkelbasis: #207 - /shop/
Winkelwagen: #208 - /winkelwagen/
Afrekenen: #209 - /afrekenen/
Mijn account: #210 - /my-account/
Algemene voorwaarden: #3312 - /algemene-voorwaarden-webshop/

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: https://www.portotheme.com/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 7.0.10
Parent Theme Author URL: https://www.portotheme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-empty.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/form-shipping.php
porto/woocommerce/checkout/payment-method.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/checkout/thankyou.php
porto/woocommerce/content-product-cat.php
porto/woocommerce/content-product.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/dashboard.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/navigation.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details-customer.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/order-downloads.php
porto/woocommerce/order/tracking.php
porto-child/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto-child/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-04-26 10:19:34 +02:00
Options: ✔
Notes: 208
Onboarding: completed

### Action Scheduler ###

Geannuleerd: 4
Oldest: 2024-04-17 16:25:03 +0200
Newest: -0001-11-30 00:19:32 +0019

Afgerond: 41.678
Oldest: 2024-03-25 15:10:03 +0100
Newest: 2024-04-25 16:00:40 +0200

Mislukt: 48.542
Oldest: 2021-01-27 14:09:19 +0100
Newest: 2024-04-25 16:05:03 +0200

In afwachting: 15
Oldest: 2024-04-25 16:05:09 +0200
Newest: 2025-01-01 00:00:01 +0100

### Status report information ###

Generated at: 2024-04-25 16:09:05 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by remkus** [comment]
I will add to this that upgrading one site from 6.4.4. to 6.5.2 doubled to quintupled the amount of erorrs per cron error email.

**Comment by andfinally** [comment]
Thanks @remkus. There is a workaround that might be useful while we work on a fix. You add this filter:

```php
add_filter( 'woocommerce_marketplace_suppress_promotions', '__return_true' );
```

Then find the scheduled action in `wp-admin/tools.php?page=action-scheduler&status=pending&s=woocommerce_marketplace_fetch_promotions&action=-1&paged=1&action2=-1`, and cancel it.

**Comment by andfinally** [comment]
Hi @remkus, to help us reproduce this error, would you mind sharing what you mean by "Moved cron to server"? Have you set `DISABLE_WP_CRON` to true and set up a crontab that makes a request to `/wp-cron.php?doing_wp_cron`, like is discussed [here](https://easyengine.io/tutorials/wordpress/wp-cron-crontab/)?

**Comment by remkus** [comment]
I'm using the built-in option of the Servebolt Optimizer plugin, but it's essentially this: https://servebolt.com/help/cron-jobs/set-up-cron-for-wordpress-multisite/

**Comment by andfinally** [comment]
Thank you!

**Comment by cubehrends** [comment]
Same issue here, thanks for the workaround.
