### ISSUE TITLE
[Custom fields] - Modify validations to allow duplicated names

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#46920]
The names are saved in each product as a meta so retrieve all distinct ones will be a performance issue. So this needs to be considered when creating the API. 
Modify validations to allow duplicated names.

**Comment by mdperez86** [comment]
Currently allowing multiple custom filed with the same name is allowed in the classic editor. But in the new editor the way we update the custom field names is by using the [update_meta_data](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-data.php#L462) function that prevents the meta duplication on creation as a solution for this bug https://github.com/woocommerce/woocommerce/issues/20431. That means that the product API does not allow the creation of multiple metas with the same key.

We have to ways to go for this:
1. Keep the validation so that the user can create unique custom fields per product. (Maybe we want to add that restriction also to the classic editor).
2. Use the new product custom field API to manage the custom fields independently. (This can also conflict with the [importer meta](https://github.com/woocommerce/woocommerce/issues/20431) since the custom fields are metas after all and I think it is a present problem in the classic editor like saving a product with same custom fields and then import it)

cc: @j111q @louwie17

**Comment by mdperez86** [comment]
Closing this until new decision has made about the previous comment.

**Comment by j111q** [comment]
Hi @mdperez86, thanks for the ping

> Keep the validation so that the user can create unique custom fields per product. (Maybe we want to add that restriction also to the classic editor).

I think this makes sense, to not allow multiple custom fields with the same name. My assumption here is that all custom fields would have different names anyway, and we shouldn't even allow users to add multiple fields with the same name (it should show an error message or something like, `This custom field already exists`).
