### ISSUE TITLE
CYS > Update the AI endpoints to rely on either JetPack or OpenAI.

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#46940]
**Issue Description:**

We need to update the endpoint used to power the AI feature within the Customize Your Store so that we can rely on JetPack or OpenAI instead. For more details and context about this task, please refer to the internal discussion on p1714038146184779-slack-C056QSJJQ91

**Comment by gigitux** [comment]
I'm going to close this issue, given that the AI flow isn't a focus anymore.
