### ISSUE TITLE
[Enhancement]: Optimise flow when using the Cart block and shipping calculations are disabled

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46949]
> [!IMPORTANT]
> This is a sub issue of #46945 and should be implemented as a featured branch against the parent issue.

```[tasklist]
### Acceptance criteria
- [ ] Change the wording `Shipping` to `Delivery`.
- [ ] Display the wording `Calculated during checkout` normal instead of strong and italic.
- [ ] When an address has been provided, but not shipping methods are available, display the warning notice (yellow) with the wording `No delivery options available for {ADDRESS}. Please verify the address is correct or try a different address.`.
``` 

## Conditions

- Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=options`.
- Disable the option `Enable the shipping calculator on the cart page`.
- Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section`.
- Remove all shipping methods.
- Add one shipping method to the Netherlands.
- Open an incognito window.
- Add a product to the cart.
- Go to the cart page that is using the Cart block.
- See the wording `Shipping`. → This affects the acceptance criteria 1.
- See the text `Calculated during checkout` formatted in strong and italic. → This affects the acceptance criteria 2.
- Go to the checkout page that is using the Checkout block.
- Provide a German address, e.g. `69120 Heidelberg, Germany`.
- Go back to the cart page.
- See the wordings `Shipping` and `Calculated during checkout` → This affects the acceptance criteria 3.

## Screenshots

> [!NOTE]
> The screenshots below, show the expected result only. 

- [ ] Change the wording `Shipping` to `Delivery`.
- [ ] Display the wording `Calculated during checkout` normal instead of strong and italic.

<img width="1456" alt="Default (1)" src="https://github.com/woocommerce/woocommerce/assets/3323310/c9faa970-ddcf-4b23-9a92-cc3437711c83">

- [ ] When an address has been provided, but not shipping methods are available, display the warning notice (yellow) with the wording `No delivery options available for {ADDRESS}. Please verify the address is correct or try a different address.`.

<img width="1456" alt="Default (2)" src="https://github.com/woocommerce/woocommerce/assets/3323310/d452f6a8-9922-49bf-907b-eee1e212a72c">

**Comment by opr** [comment]
Closed in favour of https://github.com/woocommerce/woocommerce/issues/50556
