### ISSUE TITLE
[Enhancement]: Optimise shipping calculations flows

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46945]
> [!IMPORTANT]
> This issue is a fresh start of #42422. The sub issues below should be implemented as a featured branch against this issue to ensure that we're releasing them as a bundle and not independent of each other.

```[tasklist]
### Block-related tasks
- [ ] https://github.com/woocommerce/woocommerce/issues/50546
- [ ] https://github.com/woocommerce/woocommerce/issues/50554
- [ ] https://github.com/woocommerce/woocommerce/issues/50555
- [ ] https://github.com/woocommerce/woocommerce/issues/50556
- [ ] https://github.com/woocommerce/woocommerce/issues/50557
- [ ] https://github.com/woocommerce/woocommerce/issues/50558
```

```[tasklist]
### Shortcode-related tasks
- [ ] #46946
- [ ] #46947 
- [ ] #46950 
```

**Comment by ralucaStan** [comment]
Hey @nielslange could you ping me when all the sub issues are defined?

I am not sure we should be changing things in the shortcode; as far as I know the changes were made for the checkout blocks.

A reminder for when reviewing this final ticket, we were also aiming at closing these issues:
https://github.com/woocommerce/woocommerce/issues/45525 
https://github.com/woocommerce/woocommerce/issues/46014
https://github.com/woocommerce/woocommerce/issues/42124

**Comment by nielslange** [comment]
> Hey @nielslange could you ping me when all the sub issues are defined?

Sure, I'll do that, @ralucaStan.

> I am not sure we should be changing things in the shortcode; as far as I know the changes were made for the checkout blocks.

This wasn't clear to me based on thread in #42422 and the corresponding Figma designs. Shouldn't we align both the classic checkout and the block checkout for consistency-reasons? 

> A reminder for when reviewing this final ticket, we were also aiming at closing these issues:
https://github.com/woocommerce/woocommerce/issues/45525
https://github.com/woocommerce/woocommerce/issues/46014
https://github.com/woocommerce/woocommerce/issues/42124

Absolutely. Once I'm done with creating the sub issues, I'll close the above-mentioned issues and refer to the corresponding sub issue.

**Comment by tarunvijwani** [comment]
I have created a branch for this issue: update/46945-optimise-shipping-calculations-flows so that sub-issues can be implemented as a featured branch against this issue, ensuring that they are released as a bundle.

**Comment by nielslange** [comment]
Thanks for creating the feature branch, @tarunvijwani.

**Comment by pmcpinto** [comment]
What's missing to complete this work?

**Comment by nielslange** [comment]
> What's missing to complete this work?

Looking at the tasks above, I'd say this issue can be closed, @pmcpinto, as all sub-tasks have been resolved. I'll close it for now.
