### ISSUE TITLE
[Enhancement]: Optimise flow when using the Cart block and shipping calculations are enabled

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46948]
> [!IMPORTANT]
> This is a sub issue of #46945 and should be implemented as a featured branch against the parent issue.

```[tasklist]
### Acceptance criteria
- [ ] Change the wording `Shipping` to `Delivery`.
- [ ] Change the wording `Add an address for shipping options` to `Enter address to check delivery options`.
- [ ] Display the address form, when clicking the `Enter address to check delivery options` link, in a `<panel>` component, similar to the `Add a coupon` section.
- [ ] When the address for is open, change the wording of the button from `Update` to `Check delivery options`.
- [ ] When the address for is open, change the button styles from primary (full button) to secondary (outlined button).
- [ ] When an address has been provided and a shipping method is available, display the wording `Delivers to {ADDRESS}` instead of `Shipping to {ADDRESS}`.
- [ ] When an address has been provided and a shipping method is available, link the wording `Delivers to {ADDRESS}` to the address form `<panel>`.
- [ ] When an address has been provided and a shipping method is available, remove the link `Change address`.
- [ ] When an address has been provided, but not shipping methods are available, display the wording `No delivery options available for {ADDRESS}.`.
``` 

## Conditions

- Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=options`.
- Enable the option `Enable the shipping calculator on the cart page`.
- Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section`.
- Remove all shipping methods.
- Add one shipping method to the Netherlands.
- Open an incognito window.
- Add a product to the cart.
- Go to the cart page that is using the Cart block.
- See the wordings `Shipping` and `Add an address for shipping options` within the cart totals section. → This affects the acceptance criteria 1 and 2.
- See that the wording `Add an address for shipping options` is a link instead of a `<panel>`. → This affects the acceptance criteria 3.
- Click on the link `Add an address for shipping options` and see the address form. → This affects the acceptance criteria 4 and 5.
- Provide a Dutch address, e.g. `1010 AA Amsterdam, Netherlands` and click the `Update` button.
- See the wording `Shipping to {ADDRESS}`. → This affects the acceptance criteria 6.
- See the link `Change address`. → This affects the acceptance criteria 7 and 8.
- Provide a German address, e.g. `69120 Heidelberg, Germany` and click the `Update` button.
- See that the shipping options disappeared and only the wordings `Shipping` and `Add an address for shipping options` are displayed within the cart totals section. → This affects the acceptance criteria 9.

## Screenshots

> [!NOTE]
> The screenshots below, show the expected result only. 

- Change the wording `Shipping` to `Delivery`.
- Change the wording `Add an address for shipping options` to `Enter address to check delivery options`.

<img width="1456" alt="Default   Empty" src="https://github.com/woocommerce/woocommerce/assets/3323310/ef26f782-a982-4376-8b83-c0e4ba497d01">

- Display the address form, when clicking the `Enter address to check delivery options` link, in a `<panel>` component, similar to the `Add a coupon` section.
- When the address for is open, change the wording of the button from `Update` to `Check delivery options`.
- When the address for is open, change the button styles from primary (full button) to secondary (outlined button).

<table>
<tr>
<td valign="top">
<img alt="Expanded   Empty" src="https://github.com/woocommerce/woocommerce/assets/3323310/ece93abb-9a09-407e-9aaa-adb4e12181fa">
</td>
<td valign="top">
<img alt="Expanded   Filled" src="https://github.com/woocommerce/woocommerce/assets/3323310/0b80461a-120e-4497-8faa-357b2a1780b0">
</td>
</tr>
</table>

- When an address has been provided and a shipping method is available, display the wording `Delivers to {ADDRESS}` instead of `Shipping to {ADDRESS}`.
- When an address has been provided and a shipping method is available, link the wording `Delivers to {ADDRESS}` to the address form `<panel>`.
- When an address has been provided and a shipping method is available, remove the link `Change address`.

<table>
<tr>
<td valign="top">
<img alt="Address provided" src="https://github.com/woocommerce/woocommerce/assets/3323310/47a75db2-6c62-4b85-944b-10979353afcd">
</td>
<td valign="top">
<img alt="Change address" src="https://github.com/woocommerce/woocommerce/assets/3323310/8e408c39-9f69-4509-817e-f5d3d7382c5e">
</td>
</tr>
</table>

- When an address has been provided, but not shipping methods are available, display the wording `No delivery options available for {ADDRESS}.`.

![No shipping options](https://github.com/woocommerce/woocommerce/assets/3323310/9dcaf5fd-7919-4370-9f35-324e24c7e7ae)

**Comment by opr** [comment]
Closed in favour of:

- https://github.com/woocommerce/woocommerce/issues/50546
- https://github.com/woocommerce/woocommerce/issues/50554
- https://github.com/woocommerce/woocommerce/issues/50555
