### ISSUE TITLE
[Checkout block] Single Shipping option should show boarder and spacing

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46956]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We should improve the display of the single shipping option in the Checkout block. 

### Expected behavior

A Single Shipping option should show a border and spacing to make it more visible; it would also be consistent with the way a single Payment options is displayed

### Actual behavior

The shopping option is shown, but it doesn't stand out
<img width="698" alt="Screenshot 2024-04-26 at 14 56 17" src="https://github.com/woocommerce/woocommerce/assets/1628454/361840b0-1522-4bf6-996e-6cc194e323c4">

### Steps to reproduce

1. add one shipping method, one payment method
2. go to the checkout block
3. add one address that matches the shipping method 
4. notice the missing border

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Hello @ralucaStan, it's strange that you're seeing this, as both the shipping and payment options are showing borders on my end when building against `trunk`:

<img width="750" alt="Screenshot 2024-04-28 at 09 46 30" src="https://github.com/woocommerce/woocommerce/assets/3323310/a5d619f1-55ff-4997-9b04-fa2f264f976a">

In #46525, @opr actually increased the border width of the shipping and payment options. On your screenshot, the border does not reflect the change @opr applied two weeks ago. Would you mind double-checking this?

**Comment by ralucaStan** [comment]
Thank you Niels for double checking. I was indeed testing with WooCommerce 8.8.2; I'll close this ticket

**Comment by nielslange** [comment]
I'm glad to hear that you found the reason for this issue, @ralucaStan. 🙌
