### ISSUE TITLE
[Enhancement]: Optimise shipping calculations flow when using the Checkout block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#46951]
> [!IMPORTANT]
> This is a sub issue of #46945 and should be implemented as a featured branch against the parent issue.

```[tasklist]
### Acceptance criteria
- [ ] When no address has been provided, change the wording `No shipping options available` in the order summary section to `Enter address to calculate`, and display it in 80% of the font size of the `Shipping` label and normal, neither `<strong>` nor `<em>`.
- [ ] When no address has been provided, change the wording `Shipping options will be displayed here after entering your full shipping address.` to `Enter a shipping address to view shipping options`, center the text vertically and horizontally and add a grey background.
- [ ] When a partial address has been provided, change the wording `Add a shipping address to view shipping options.` to `Enter a shipping address to view shipping options`, center the text vertically and horizontally and add a grey background.
- [ ] When no address has been provided, change the wording `No shipping options available` in the order summary section to `No available delivery option`, and display it in 80% of the font size of the `Shipping` label and normal, neither `<strong>` nor `<em>`.
- [ ] When a full address has been provided, but no shipping options are available for that address, change the wording `There are no shipping options available. Please check your shipping address.` to `No shipping options are available for this address. Please verify the address is correct or try a different address.`.
``` 

## Conditions

- Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section`.
- Remove all shipping methods.
- Add one shipping method to the Netherlands.
- Open an incognito window.
- Add a product to the cart.
- Go to the checkout page that is using the Checkout block.
- See the wording `No shipping options available` in the order summary section. → This affects the acceptance critaria 1.
- See the wording `Shipping options will be displayed here after entering your full shipping address.` in the shipping options section. → This affects acceptance criteria 2.
- Provide a partial Dutch address, e.g. `Brandarisstraat 2, 8881 AW West-Terschelling, Netherlands`, but do not provide a first and last name. Then, click the `Update` button.
- See the wording `Add a shipping address to view shipping options.` in the shipping options section. → This affects acceptance criteria 3.
- Provide a first and last name, e.g. `Jaap Schippers`.
- See the wording `No shipping options available` in the order summary section. → This affects the acceptance criteria 4.
- See the wording `There are no shipping options available. Please check your shipping address.` in a warning notice in the shipping options section. → This affects acceptance criteria 5.

## Screenshots

> [!NOTE]
> The screenshots below, show the expected result only. 

- When no address has been provided, change the wording `No shipping options available` in the order summary section to `Enter address to calculate`, and display it in 80% of the font size of the `Shipping` label and normal, neither `<strong>` nor `<em>`.
- When no address has been provided, change the wording `Shipping options will be displayed here after entering your full shipping address.` to `Enter a shipping address to view shipping options`, centre the text vertically and horizontally and add a grey background.
- When a partial address has been provided, change the wording `Add a shipping address to view shipping options.` to `Enter a shipping address to view shipping options`, centre the text vertically and horizontally and add a grey background.

![Checkout](https://github.com/woocommerce/woocommerce/assets/3323310/4fa39bb7-523c-455e-a027-67099c014193)

- When no address has been provided, change the wording `No shipping options available` in the order summary section to `No available delivery option`, and display it in 80% of the font size of the `Shipping` label and normal, neither `<strong>` nor `<em>`.
- When a full address has been provided, but no shipping options are available for that address, change the wording `There are no shipping options available. Please check your shipping address.` to `No shipping options are available for this address. Please verify the address is correct or try a different address.`.

![Checkout (1)](https://github.com/woocommerce/woocommerce/assets/3323310/fb73cec6-0d9c-402a-a2ed-761de17aec27)

**Comment by opr** [comment]
Closed in favour of:

- https://github.com/woocommerce/woocommerce/issues/50557
- https://github.com/woocommerce/woocommerce/issues/50558
