### ISSUE TITLE
Improve specific single product template names

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#46952]
Currently, there are two ways a store might have specific single product templates: either they are provided by the theme or they are created manually. However, they are displayed with a different naming structure:

* Templates created by the theme: `Single Product [product_name]`, ie: _Single Product Belt_.
* Templates created by the user: `Product: [product_name]`, ie: _Product: Belt_.

![imatge](https://github.com/woocommerce/woocommerce/assets/3616980/30befc28-27ab-4579-8d75-a983654b41db)

This issue is about unifying them, ideally to `Single Product: [product_name]`.

Note: the title of theme templates can be modified via the `theme.json` file, so I don't think it's an urgent one to fix.

Note 2: ideally, we should also unify templates titles for specific taxonomies, like categories and tags.

**Comment by Aljullu** [comment]
If https://github.com/WordPress/gutenberg/pull/60367 is merged upstream, it would be great if this issue can be fixed usptream as well. If I'm not wrong, the fix will consist on changing the label which is used to prefix the CPT individual templates, from `singular_name` to `template_name`.

**Comment by Aljullu** [comment]
Given that in https://github.com/woocommerce/woocommerce/pull/48106 we decided to leave the Single Product template name to `Single item: Product` to keep it consistent with posts, I think we should also keep the templates for individual products as they are. That means keeping them as `Product: [product_name]` instead of `Single Product: [product_name]` as I initially suggested in the issue description. This will keep it consistent with posts, which are represented as `Post: [post_title]`

<img src="https://github.com/woocommerce/woocommerce/assets/3616980/e63000a3-9643-43fc-88f5-f7b164d2349e" width="544" alt="" />

:point_up_2: that makes reference to templates created by the user.

And as mentioned in the issue description, the templates created by the theme can be named in `theme.json`, so I don't think WooCommerce should modify them in any way.

_tl;dr_ I think we should close this issue as won't fix. What do you think @WunderBart?

**Comment by Aljullu** [comment]
cc @WunderBart about the previous comment, I originally pinged the wrong GitHub user and I think that's why you weren't notified. :sweat_smile:

**Comment by WunderBart** [comment]
> cc @WunderBart about the previous comment, I originally pinged the wrong GitHub user and I think that's why you weren't notified. 😅

Ha, no worries! Not the first mis-ping – the other Bart has already got quite a few pings from Woo! 😅 

> Given that in https://github.com/woocommerce/woocommerce/pull/48106 we decided to leave the Single Product template name to Single item: Product to keep it consistent with posts, I think we should also keep the templates for individual products as they are. That means keeping them as Product: [product_name] instead of Single Product: [product_name] as I initially suggested in the issue description. This will keep it consistent with posts, which are represented as Post: [post_title]

Agreed, this seems the most consistent way to go for now. Let's close as wontfix, as you suggested. 👍

**Comment by Aljullu** [comment]
> Agreed, this seems the most consistent way to go for now. Let's close as wontfix, as you suggested. 👍

Let's do that! Thanks for the feedback!
