### ISSUE TITLE
[DOC-BUG] Backslashes removed from HPOS compatibility declaration code snippets

### ISSUE THREAD

**Issue by patrickmcelwee** [woothemes/woocommerce#46987]
## Link to the Page/Section

> Provide a link to the specific page or section that you're referring to.

https://developer.woocommerce.com/docs/hpos-extension-recipe-book/#2-supporting-high-performance-order-storage-in-your-extension
- See the two code snippets under "Declaring extension (in)compatibility". The blackslashes in the following class name have been removed 4 times:

"\Automattic\WooCommerce\Utilities\FeaturesUtil" instead reads "AutomatticWooCommerceUtilitiesFeaturesUtil"

## Description of the Suggestion

Make the backslashes appear.

> Describe the changes you suggest to improve or correct the documentation. Be specific about any errors or areas of confusion you've identified.

The markdown here looks correct, but there is some kind of translation to html, and the error is introduced in that process: https://github.com/woocommerce/woocommerce/blob/94e438f524c9fd78da691d5722b005e09b06dc51/docs/high-performance-order-storage/recipe-book.md?plain=1#L159

## Reason for the Suggestion

> Why do you believe this change will make the documentation clearer or more accurate?

This should be fixed. This caused me, as a plugin developer, to burn time debugging why my copy-pasted compatibility declaration was failing.

## Additional Context

> Add any other context, references, or screenshots that support your suggestion.

**Comment by barryhughes** [comment]
I believe this has been resolved via a change in the docs site:

![docs-backslashes](https://github.com/woocommerce/woocommerce/assets/3594411/3ab67c2f-ae56-415f-b3f9-81a1f1ad9f2b)

Please don't hesitate to let me know if I'm mistaken, or the problem persists in some pages and I'll re-open.
