### ISSUE TITLE
Product Filters Redesign > Block: Investigating Feasibility of Block Insertion Limits in the Editor

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#46981]
## Description
The Product Filters block is a container where users can add and manage filter blocks. The inserter must display filters that have yet to be added. Each filter block can only be added once, except for status and attributes, which can be inserted any number of times.

## Expected Results:

Currently, we have blocks that can only be added inside specific templates, pages, or posts. However, it appears that we do not limit the number of times a block can exist within another. The purpose of this GitHub issue is to investigate whether this can be implemented in the Editor.

## Additional Info:
There is an open issue in Gutenberg which seems to be requesting exactly what we need here: https://github.com/WordPress/gutenberg/issues/38958

**Comment by roykho** [comment]
Currently the way WP/GB handles it is by declaring `multiple: false` in `block.json`. We also already use this on our Product Filter: Stock Status. However this method doesn't actually hide the block from being discovered in the block inserter. It will instead display a message after you have added a second block noting `This block can only be used once.`. You will also get an option to jump to the original/first added block or to remove it. I have pitched the idea of hiding the block if there is already one on the page [here](https://github.com/WordPress/gutenberg/issues/61415) on GB. Without hacking up our own custom solution. I believe this will suffice for the time being WDYT?  cc @jarekmorawski

**Comment by jarekmorawski** [comment]
Thanks for making that contribution, Roy! Much appreciated. I confirm that's the desired behavior. An error message is confusing and can be easily missed, so it's best to _prevent_ the error in the first place by not letting the user add duplicated blocks.

By the way, we should also remove the `Duplicate` action from the filter block's contextual menu in the canvas and the List View. We should also prevent users from duplicating a Group or another container block with the filter block inside. In all such cases (like when someone copies and tries to paste a filter block), we could show a snackbar message that reads:

`[Filter block name] can only be used once.`

**Comment by roykho** [comment]
So unfortunately I was not able to find a way to implement this even with a hacky solution. There is a way to detect if the block already exists on the page but the hard part is hooking into the inserter search result and trying to filter the block out.

There isn't any existing hooks that I can see searching the Gutenberg source. The closest is hooking into `registerBlockType` but that won't work because if you disable/remove the block at that level, the existing block that is on the page will seize to work.

With that said, if we implement the filter block as a parent as proposed in the design and then shown each individual filter options, perhaps at that level we can limit it as we may have more control over that. That is just my assumptions without seeing how the parent block actually works. Perhaps we can revisit this once that is implemented.

**Comment by jarekmorawski** [comment]
Thanks for looking into it, @roykho. What about Rich's suggestion in the issue you created in the Gutenberg repo? If we can disable the block in the inserter, change the cursor to `not-allowed`, and display a tooltip on hover, we could prevent users from adding duplicates without hacking our way around the editor.

> perhaps at that level we can limit it as we may have more control over that

That'd be the desired outcome. It makes sense to restrict the use of inner blocks in a parent, it's a pattern we'll use in filters and a few other blocks.

Worst case scenario, we can allow duplicates, but I'd appreciate it if you could explore other options. Maybe there's something in existing block hooks or props that could serve a similar purpose?

**Comment by thealexandrelara** [comment]
After several discussions and considering feedback from the team (ref: p1724771607439439-slack-C05UMTA7W0P), we’ve decided not to limit the number of filter blocks of the same type that can be added. As highlighted in our conversations, merchants might have different needs, and restricting the number of filter blocks could pose a limitation. Additionally, it would increase the complexity of the implementation for minimal gain.

Given this, I'm closing this issue.
