### ISSUE TITLE
Checkout Block + Custom Shipping Method - Multiple add_rate() with dynamic IDs don't set as Shipping Option

### ISSUE THREAD

**Issue by GreyforestDigital** [woothemes/woocommerce#46982]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When building a custom Shipping Method plugin that extends WC_Shipping_Method class, displaying multiple rates from a third party service (or even manually entering rates) requires an array including ID, label, cost, and calculation_type in the **add_rate()** $args. WooCommerce documentation states that the "id" must be unique, and examples show a setup like this:

``` 
$args => array( 
'id' => $this->id . '_rate1', 
'label' => __('$5 Shipping Rate'), 
'cost' => '5.00', 
'calculation_type' => 'flat' 
)
$this->add_rate($args);

$args2 => array( 
'id' => $this->id . '_rate2', 
'label' => __('$10 Shipping Rate'), 
'cost' => '10.00', 
'calculation_type' => 'flat' 
)
$this->add_rate($args2);
````

However, if the "id" in the $args does not match $this->id of the whole shipping method (set in the __construct() class), it fails to submit the order and returns "Sorry, this order requires a shipping option." Which is the error returned by **OrderController::validate_selected_shipping_methods()**. This only happens when using the Checkout Block. Classic Checkout works fine with dynamic shipping method rate IDs.

I did a test using add_rates() with dynamic IDs as listed above, then before submission looped through the **WC()->session->get( 'chosen_shipping_methods' )** session variables, updated the ID to match the $this->id variable, and the order submitted properly, but no shipping method or price is attached to the order.

**Super Simple Custom Shipping Method:**
![WC-shippingmethod-class](https://github.com/woocommerce/woocommerce/assets/4615829/ff7791c9-1786-4f7c-84f3-8f58ddd3f853)

**Shipping Method is Activated:**
![WC-shippingmethod-admin](https://github.com/woocommerce/woocommerce/assets/4615829/a4adee58-c5ae-429d-a02c-096cf108a162)

**Shipping Method Appears on Checkout:**
![WC-shippingmethod-checkout](https://github.com/woocommerce/woocommerce/assets/4615829/ad1a0703-1793-44e9-8e16-d32a323d9616)

### Expected behavior

I expected the add_rate() function to work in the same way it does in documentation provided by WooCommerce. As it works using the Classic Checkout, I would expect it to work the same with Blocks, as presumably many shipping plugins are based on this function to provide multiple rates from the same method.

### Actual behavior

If a custom shipping method adds multiple rates via **add_rate($args)** and they have a dynamic "id" that doesn't match the shipping method id, the order will fail to submit and present a "rest_invalid_shipping_error" notice of "Sorry, this order requires a shipping option."

**Error Notice in Checkout:**
![WC-shippingmethod-checkouterror](https://github.com/woocommerce/woocommerce/assets/4615829/9ed16272-8513-409b-bf0a-d6e9debd7070)

**Request:**
![WC-shippingmethod-request](https://github.com/woocommerce/woocommerce/assets/4615829/156f81ca-f466-4955-806f-949890d7aefc)

**Response:**
![WC-shippingmethod-badrequest](https://github.com/woocommerce/woocommerce/assets/4615829/0d585ead-70d8-45f3-bab8-b089d9e23553)
![WC-shippingmethod-badrequest2](https://github.com/woocommerce/woocommerce/assets/4615829/0e60be23-fb9d-41cc-aabc-d3269549f430)

### Steps to reproduce

1. Spool up a brand new WordPress and WooCommerce environment.
2. Use pre-installed Twenty TwentyFour theme.
3. Setup Checkout page using the Checkout Block (not Classic Checkout).
4. Add a custom shipping method with 2 rates, each using a custom/dynamic string for the "id" value of $args that is used in add_rate().
5. Select that shipping rate in Checkout, and attempt to place an order.

**Basic Shipping Method Class:**
```

add_action('woocommerce_shipping_init', 'add_shipping_method');
function add_shipping_method() { 
	$newShippingMethod = new WC_Custom_Shipping_Method();
}

add_filter('woocommerce_shipping_methods', 'add_custom_shipping_method'); 
function add_custom_shipping_method( $methods ) { 
	$methods['custom_shipping_method'] = 'WC_Custom_Shipping_Method'; 
	return $methods; 
}
		

class WC_Custom_Shipping_Method extends WC_Shipping_Method { 
	
	public function __construct() { 
		$this->id = 'custom_shipping_method'; 
		$this->method_title = __('Custom Shipping Method'); 
		$this->title = __('Custom Shipping Method'); 
		$this->method_description = __('Custom shipping method with two available rates - $5 and $10'); 
		$this->enabled = 'yes'; 
	} 
	
	public function calculate_shipping($package = array()) { 
		$this->add_rate(array( 'id' => $this->id . '_rate1', 'label' => __('$5 Shipping Rate'), 'cost' => '5.00', 'calculation_type' => 'flat' )); 
		$this->add_rate(array( 'id' => $this->id . '_rate2', 'label' => __('$10 Shipping Rate'), 'cost' => '10.00', 'calculation_type' => 'flat' ));
	} 
} 	

```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.example.com
Site address (URL): https://www.example.com
WC Version: 8.8.2
REST API Version: ✔ 8.8.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.2.18
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.31
Max Upload Size: 931 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.2
WC Database Prefix: wp_
Total Database Size: 9.76MB
Database Data Size: 7.26MB
Database Index Size: 2.50MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.23MB + Index: 0.27MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_aiowps_audit_log: Data: 0.47MB + Index: 0.06MB + Engine InnoDB
wp_aiowps_debug_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_events: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_logged_in_users: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_aiowps_message_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.30MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 38
custom_css: 1
customize_changeset: 3
page: 8
post: 1
product: 6
product_variation: 14
revision: 109
shop_order_placehold: 59
wp_font_face: 9
wp_font_family: 1
wp_global_styles: 3
wp_navigation: 1
wp_template: 10
wp_template_part: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Code Snippets: by Code Snippets Pro – 3.6.4
WooCommerce: by Automattic – 8.8.2

### Inactive Plugins (8) ###

All In One WP Security: by All In One WP Security & Firewall Team – 5.2.9
Meta Field Block: by Phi Phan – 1.2.8
SMTP Mailer: by naa986 – 1.1.13
The SEO Framework: by The SEO Framework Team – 5.0.6
WP-Optimize - Clean, Compress, Cache: by David Anderson
WP fail2ban: by Charles Lecklider – 5.2.2.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 MB

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-04-26 17:52:13 -04:00
Options: ✔
Notes: 53
Onboarding: completed

### Action Scheduler ###

Complete: 798
Oldest: 2024-04-13 17:53:25 +0000
Newest: 2024-04-26 17:48:30 +0000

Pending: 2
Oldest: 2024-04-26 18:22:50 +0000
Newest: 2024-04-26 21:28:11 +0000

### Status report information ###

Generated at: 2024-04-26 13:52:13 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
This has been fixed here https://github.com/woocommerce/woocommerce/pull/46719 (initially reported here https://github.com/woocommerce/woocommerce/pull/46719), coming out with 8.9.0

This bugs is happening because there's an implicit requirement that shipping rates IDs are on the shape of `"{$this->id}:{$instance_id}"` so for example `flat_rate:1`

In your case, the separator is `_`. This would cause problems down the road like persisting the selected shipping method and such.

It's recommended you update your shipping method separator to be `:`. Or not pass an `id` and just pass `instance_id`

I will close this given it's already solved, but you can still continue replying here.
