### ISSUE TITLE
Invalid link generated in dashboard setup widget

### ISSUE THREAD

**Issue by beaulebens** [woothemes/woocommerce#46993]
Under some circumstances, the invalid link is generated and used on the "Start selling" button displayed in the dashboard widget. I'm not sure exactly what combination of settings or anything triggers it:

<img width="637" alt="Screenshot 2024-04-26 at 9 39 59 PM" src="https://github.com/woocommerce/woocommerce/assets/108942/15e5b054-31d8-40fe-91b9-239512fc18fd">

(also note weird layout/formatting of the text in this widget).

The link appears to come from here:
https://github.com/woocommerce/woocommerce/blob/f9a7ff04f08e759142667c23689791e697b33a12/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php#L93-L103

I have a test site set up on `https`, installed in a subdirectory, and the link on that "Start selling" button is: `https://DOMAIN/SUBDIR/wp-admin/wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store`. Note the double `wp-admin`. Clicking it gives a 404.

**Comment by beaulebens** [comment]
I'm using WP 6.5.2 and WC 8.8.2.

**Comment by adrianduffell** [comment]
A PR is in progress to fix this here https://github.com/woocommerce/woocommerce/pull/47010
