### ISSUE TITLE
Stores using FSE themes cannot access the customizer resulting in the inability to edit WooCommerce settings like Store Notices.

### ISSUE THREAD

**Issue by imodouglas** [woothemes/woocommerce#46995]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Stores using FSE-enabled themes cannot access the customizer under Appearance > Customize as the option is not available for FSE-enabled themes. This results in their inability to edit WooCommerce settings like Store Notices.

### Expected behavior

Stores with WooCommerce enabled should be able to access the customizer from the dashboard.

### Actual behavior

Customizer can only be accessed using a link [yoursiteurl]/wp-admin/customize.php

### Steps to reproduce

1. Install WooComerce on WordPress.
2. Enabled an FSE enabled theme link Twenty Twenty-Four
3. Try to access the customizer to enabled Store Notice without using the URL.

### WordPress Environment

[not provided]

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by imodouglas** [comment]
**Workaround:** You can the attached mini plugin to add the customize link for FSE enabled themes.
[customize-link-for-FSE.zip](https://github.com/woocommerce/woocommerce/files/15146042/customize-link-for-FSE.zip)

**Comment by nefeline** [comment]
Hi @imodouglas, thanks for reaching out to us!

Regarding:

> Stores using FSE-enabled themes cannot access the customizer under Appearance > Customize as the option is not available for FSE-enabled themes. This results in their inability to edit WooCommerce settings like Store Notices.

The equivalent of **Appearance > Customize** for any block theme is **Appearance > Editor**

To edit the Store Notices for example, you can head over to Appearance > Editor > Templates > Product Catalog and edit it. While we still don't have a lot of customization options for the Store Notices block just yet, you can add custom classes to it for applying your CSS via your theme's stylesheet, for example:

<img width="1239" alt="Screenshot 2024-05-05 at 09 58 12" src="https://github.com/woocommerce/woocommerce/assets/15730971/91b5f365-fece-420d-8450-cca691f13007">

I hope this helps! I'm going ahead and closing this issue out, but feel free to follow up here if you have questions.

**Comment by kelasante** [comment]
Thanks @nefeline,  resurfacing this again. For the store notice, I do not see an option to edit this in the Site Editor. The CSS class allows you to add CSS to style it, but the block itself is not editable. 

In the Customizer, the notice can be edited, however, the Editor looks to be missing an option to edit:
<img width="1500" alt="Markup 2024-06-28 at 17 43 46 (1)" src="https://github.com/woocommerce/woocommerce/assets/74204272/01a33d10-1c3b-4603-aa99-1b94b93f307c">

So as a feature request for the Store Notice block, instead of showing the uneditable `Notices added by WooCommerce or extensions will show up here.`, can that be a block of text that can be edited?
