### ISSUE TITLE
CYS > AI content generation failing for patterns

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#47015]
**Issue Description:**

Within WooExpress, AI content generation is failing for patterns. Opening this issue so we can find out the cause and solve the problem.

## Steps to reproduce:

- Create a new WooExpress install: https://woocommerce.com/start/#/ 
- Access My home > Customize your store
- Provide a business description
- After finishing loading, notice how patterns don't have AI content generated, but products do.

**Comment by albarin** [comment]
This was fixed, for more context p1714218704634239-slack-C053716F2H2
