### ISSUE TITLE
CYS > The frame is not accessible on Safari

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#47014]
**Issue Description:**

Whenever attempting to access the CYS on Safari, the frame is blank:

<img width="1240" alt="Screenshot 2024-04-29 at 09 33 47" src="https://github.com/woocommerce/woocommerce/assets/15730971/bf9ebd09-352c-4cb8-8640-cd331b3fb485">

After initial investigation, the following error might be directly related to this problem:

`ResizeObserver loop completed with undelivered notifications.`

By reading the docs it looks like this can happen in case of resize infinite loops https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors

We are using ResizeObserver in the frame: [https://github.com/woocommerce/woocommerce/blob/79ff29138c9d1fc35454fc84ed3ba473c8[…]ocommerce-admin/client/customize-store/assembler-hub/iframe.jsx](https://github.com/woocommerce/woocommerce/blob/79ff29138c9d1fc35454fc84ed3ba473c8d80f06/plugins/woocommerce-admin/client/customize-store/assembler-hub/iframe.jsx#L17)

Opening this issue for further investigation.

**Comment by albarin** [comment]
No longer reproducible
