### ISSUE TITLE
Local Pickup goes into a loop in the editor

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#47023]
Possibly most likely related to https://github.com/woocommerce/woocommerce/issues/46470, In the editor, Local Pickup and Regular shipping go into a loop of selection with hundreds of requests in console.

### Steps to reproduce:

- Enable Local Pickup and regular shipping, have at least 2 pickup locations.
- In frontend, logged in, select local pickup and let it persist.
- Edit the Checkout page, notice the loop happening.

https://github.com/woocommerce/woocommerce/assets/6165348/daa870c4-c082-4703-9c71-c6d27e4acd04

**Comment by senadir** [comment]
Inspecting the request, I see 2 `select-shipping-rate` going with batch, each for a shipping method. The local pickup one has package_id set as null, while the other has the correct package.

**Comment by wavvves** [comment]
I can replicate it consistently using the following steps:

1. Enable Local Pickup and regular shipping, have at least 2 pickup locations.
2. Keep a tab open with the editor and one with checkout.
3. In the editor tab, click local pick
4. In the Checkout tab click Local pickup
5. Refresh the Editor tab


https://github.com/woocommerce/woocommerce/assets/17236129/b94bc819-3ec7-4b49-be8b-cf681b752d87

**Comment by ralucaStan** [comment]
I was able to replicate this one until before 8.0.3; si it’s been a long time active.

I’ve boiled it down to [this effect](https://github.com/woocommerce/woocommerce/blob/35c50ebdb417d2a15ae22eb65451773919b5607a/plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx#L61-L65) that is being called multiple times with the same value for `selectedOption` ; coming from this PR https://github.com/woocommerce/woocommerce-blocks/pull/10472/files

I didn't have more time to invest in this for now to understand what is causing this loop but I wanted to share my findings

**Comment by samueljseay** [comment]
I cannot reproduce this at the moment, wondering if someone else on @woocommerce/rubik could have a look to confirm.

What I see if I use the steps in https://github.com/woocommerce/woocommerce/issues/47023#issuecomment-2084893702 is that the editor switches once but it doesn't go into a loop for me.

**Comment by alexflorisca** [comment]
I just tried this as well and I couldn't reproduce it. I tried logged in as well as out, toggling between local pickup and shipping in various different ways in editor and frontend and nada. 

I noticed however that if I try to select `Ship` in the editor while `Local Pickup` is selected on the front-end, then I refresh the page, it's not persisted and local pickup loads as the default option. Maybe that's related to this bug?

**Comment by samueljseay** [comment]
> I noticed however that if I try to select Ship in the editor while Local Pickup is selected on the front-end, then I refresh the page, it's not persisted and local pickup loads as the default option. Maybe that's related to this bug?

I'm not certain but that behaviour doesn't matter much right?

I'm going to say this closed for now. If someone else can reproduce it we can reopen.
