### ISSUE TITLE
[Enhancement]: Improve banner styling 

### ISSUE THREAD

**Issue by danielvann777** [woothemes/woocommerce#47034]
### Describe the solution you'd like

Receiving notifications on the home of WooCommerce, beyond the discussion of timeliness or usefulness, can also be overwhelming due to styling. Long lines (way above the ~70 chars per line that make text well readable), type sizing, and balance in general, make the experience feel heavy.

I suggest we explore, as a starting point, a couple of ways to simplify the styling and get it to the same max-width as the main body. Attaching some examples, and happy to dive deeper to document this once this enhancement is considered.

![image (1)](https://github.com/woocommerce/woocommerce/assets/158479847/f64c66ab-2b43-4b76-b8ce-3c59236fde1a)
<img width="822" alt="main-component-notice" src="https://github.com/woocommerce/woocommerce/assets/158479847/7d8410f6-14b1-4701-a9f5-183e180703b0">

**Comment by adrianduffell** [comment]
I think we could adjust the width of this on homepage to match the main body as below. @danielvann777 what do you think?


![Image](https://github.com/woocommerce/woocommerce/assets/9312929/8344a4cf-b18e-4e30-b5d6-94a704720337)


Note that it would also need to change size when the two-column layout is configured:

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/ff07b424-3647-482a-9ce2-92836821f039)

cc @verofasulo

**Comment by danielvann777** [comment]
This looks good to me. Would we be able to reduce the headline to the same size as the body text, just in bold?
The size feels overwhelming right now, and I think both placement and color help the user learn it's a critical/important message.

cc @elizaan36

**Comment by elizaan36** [comment]
Thanks for the ping, @danielvann777! @adrianduffell We have a set of variations that show an optional notice title as well. The title matches the body text size but in bold. Let me know what you think. 

<img width="822" alt="Main component" src="https://github.com/woocommerce/woocommerce/assets/5121465/cc0b9881-7469-471f-add8-ef53d8f72c52">

I think adjusting the width of notices to match the main body makes sense. Are there possibilities to apply the wp-notice color system to these wc-admin notices? I'm wondering how to alert the merchant on the urgency of the RIN if critical. If it's not critical it would be better suited to the inbox note variation.

**Comment by adrianduffell** [comment]
Thanks @elizaan36, we would be able to change it to match the critical alert title size and colors.

The database update note in the description has a note type named "update", but essentially should be considered a critical alert. I suspect the custom name is why it currently falls outside of the design system.

**Comment by elizaan36** [comment]
Thanks @adrianduffell ! Sounds good.

Separately, do you know of documentation that lists notices/triggers, for everything that appears as a banner in the admin? We're doing an audit to try making a more coherent system.

- "Update" type RIN 
- JITMs 
- Are there any WooCommerce core notices that use the wp-admin style or are those all coming from woo.com and plugins?

**Comment by psealock** [comment]
Here is what I have currently. @elizaan36 do you have Figma files for images in [this comment](https://github.com/woocommerce/woocommerce/issues/47034#issuecomment-2148319320)?

<img width="1318" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/b8ab642c-39eb-4d82-a371-6e5700a9be47">

**Comment by elizaan36** [comment]
Nice. I just shared the Figma with you in Slack. For this particular update with pagination it would look like this variant. Let me know what you think. 
<img width="547" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5121465/16e281b7-ee12-4921-8f6d-59ae1629a0db">
