### ISSUE TITLE
Product Filters Redesign: Create the template part

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#47038]
## Description
The Product Filters block is a container where users can add and manage filter blocks. The block can only be inserted inside a template part of the same name.

## Current Behavior:

Currently, there is no template part for the Product Filters block.

## Expected Behavior:

- The title of the template part is "Product Filters"
- The Product Filters block should be hidden from the block inserter. Only the template part can be added to the canvas.
- The Product Filters block and its inner blocks can only be inserted within the Product Filters part.
- The regular inserter doesn't display the parent block and individual filters.

## Reference images

| Product Filters template part |
|--------|
| ![CleanShot 2024-04-29 at 16 16 05@2x](https://github.com/woocommerce/woocommerce/assets/20469356/a536228b-7419-46bc-b616-6fb3c649d309) | 

| Block Inserter showing only the Product Filters template part |
|--------|
| ![CleanShot 2024-04-29 at 16 16 45@2x](https://github.com/woocommerce/woocommerce/assets/20469356/0ae38a32-be32-45f0-b0d1-18634f6eaad0) |

**Comment by roykho** [comment]
Hi @thealexandrelara - just a reminder here that we've decided to use synced patterns instead of template part per Darren's suggestion.

**Comment by thealexandrelara** [comment]
Hey Roy, thank you for the heads-up! Yeah, this issue was created before the decision was made, so I'll have to revisit it and also shift my focus away from the work I was doing related to it. 😞

**Comment by thealexandrelara** [comment]
Closing this issue in favor of [#49711](https://github.com/woocommerce/woocommerce/issues/47911)

**Comment by thealexandrelara** [comment]
I am reopening this issue because, after [some investigation](https://github.com/woocommerce/woocommerce/issues/47911), the team identified that in its current state, Synced Patterns do not provide an API that allows easy management. Therefore, it would be better to implement the Product Filters as a template part instead.
