### ISSUE TITLE
Product Block Editor: the attribute values component loses the `box` style

### ISSUE THREAD

**Issue by retrofox** [woothemes/woocommerce#47059]
When creating new options for the current attribute, the component shows each one with the `box` style:

<img width="726" alt="image" src="https://github.com/woocommerce/woocommerce/assets/77539/5345cabe-fc58-485b-a843-0488c23be276">

... but if you click outside, for instance, in the modal, the component loses the style:

<img width="713" alt="Screenshot 2024-04-30 at 16 04 26" src="https://github.com/woocommerce/woocommerce/assets/77539/4e9adfac-d5f5-47e4-a4fe-5f36698838fd">

**Comment by mattsherman** [comment]
Closing -- works as designed
