### ISSUE TITLE
Introduce a new ExPlat experiment in 9.0

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#47054]
**Description:** we want to release a new experiment to monitor the impact of the price tab changes: #47053
The 9.0 code freeze is May 22nd.

**Acceptance criteria:**

- [x] Replicate the experiment running in 8.8. In sum, we should expose users who choose one of the following options in the "Add products" task: Physical product, Variable product, Digital product, Grouped product, and External product. 
- [x] Create the experiment P2. (feel free to ping me to review the draft)
- [x] Create the experiment in Abacus.
- [x] Add the segment to the WPCOM core.

**Comment by louwie17** [comment]
Closing this, all items are done in the above list. Only the experiment needs to be enabled upon release.
