### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#47079]
Removed - Please see our security policy https://github.com/woocommerce/woocommerce/security/policy

**Comment by helgatheviking** [comment]
I always try to remember to strip mine out, but an automatic tool would be great!

**Comment by jonathansadowski** [comment]
Hi @kkmuffme,

Thank you for taking the time to file this report. [As per our security policy](https://github.com/woocommerce/woocommerce/security/policy), please report any potential security issues via HackerOne. This allows us to handle them appropriately, as well as avoid accidental disclosure.

**Comment by helgatheviking** [comment]
I don't understand why it needs to go to hackerone? It's not a vulnerability in the plugin itself... It's specifically about your new issue template here at GitHub.
