### ISSUE TITLE
[HPOS] CustomMetaDataStore::get_meta_keys causing EXTREMELY slow query

### ISSUE THREAD

**Issue by skunkbad** [woothemes/woocommerce#47074]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The current release of WooCommerce 8.8.3 includes code in CustomMetaDataStore.php, in the get_meta_keys method, that causes an EXTREMELY slow query in my database of 100,000+ orders. This is the query that is generated:

SELECT DISTINCT meta_key 
FROM wp_wc_orders_meta 
WHERE meta_key NOT LIKE '\\_%' 
ORDER BY meta_key ASC LIMIT 30

### Expected behavior

A reasonably fast query that doesn't make loading an order take 120+ seconds.

### Actual behavior

Sit and wait while the extremely slow query does it's thing.

### Steps to reproduce

Try to view one of my 100,000+ orders.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://localhost.wildfish
Site address (URL): https://localhost.wildfish
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Ubuntu)
PHP Version: 8.1.2-1ubuntu2.15
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.16-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: wp_
Total Database Size: 3549.64MB
Database Data Size: 1898.03MB
Database Index Size: 1651.61MB
wp_woocommerce_sessions: Data: 8.52MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 31.56MB + Index: 16.55MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 742.00MB + Index: 228.56MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
eventDateTimes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
eventLocations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
geoIpFilterLog: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
geoIpTempAccess: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pain: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
shipment_trackings: Data: 14.52MB + Index: 4.52MB + Engine InnoDB
wassEmailMarketingRecipients: Data: 3.52MB + Index: 2.52MB + Engine InnoDB
wassEmailMarketingSubscriptionOptions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wassEmailMarketingSubscriptionOptionsCategories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wassEmailMarketingSubscriptions: Data: 0.31MB + Index: 0.36MB + Engine InnoDB
wassOrderBonusesApplied: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wassToolsAcquisitionLog: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wassToolsAddonsAdded: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wassToolsAdminLoginLogout: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsDbBackups: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wassToolsDeliveryBlackoutDates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsFreeShippingStateExclusions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsGoogleReviewsCache: Data: 0.38MB + Index: 0.16MB + Engine InnoDB
wassToolsPluginConfig: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsProductsRemovedAtSubRenewal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsQrUsageLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsSecurityBannedIps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsSecurityBlacklistedIps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsSecurityWhitelistedIps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsShippingBlackoutDates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsShippingExcludedStatesForcedUpgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsStatesShippingOnlyOnMondays: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsStatesWithG3ShippingUpgradedToFree3DaySelect: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wassToolsUpsClaimsQueue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wassToolsZipCodes: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wass_queue: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wmlp_mail_refs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 7.52MB + Index: 12.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 3.52MB + Index: 4.52MB + Engine InnoDB
wp_actionscheduler_logs: Data: 5.52MB + Index: 5.03MB + Engine InnoDB
wp_commentmeta: Data: 5.52MB + Index: 6.03MB + Engine InnoDB
wp_comments: Data: 176.72MB + Index: 121.39MB + Engine InnoDB
wp_easywpsmtp_debug_events: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_loyal_customers: Data: 5.52MB + Index: 2.52MB + Engine InnoDB
wp_options: Data: 13.44MB + Index: 1.61MB + Engine InnoDB
wp_osapi_last_modified: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pimwick_gift_card: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_pimwick_gift_card_activity: Data: 0.31MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 265.28MB + Index: 212.27MB + Engine InnoDB
wp_posts: Data: 42.56MB + Index: 25.77MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 83.63MB + Index: 91.27MB + Engine InnoDB
wp_users: Data: 5.52MB + Index: 5.55MB + Engine InnoDB
wp_wass_referrals_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.45MB + Index: 0.06MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 5.52MB + Index: 6.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 35.58MB + Index: 40.16MB + Engine InnoDB
wp_wc_orders_meta: Data: 316.89MB + Index: 764.00MB + Engine InnoDB
wp_wc_order_addresses: Data: 30.56MB + Index: 38.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 19.56MB + Index: 10.06MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 25.56MB + Index: 29.06MB + Engine InnoDB
wp_wc_order_stats: Data: 12.52MB + Index: 10.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wotv_woo_track_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.34MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.11MB + Index: 0.28MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.25MB + Index: 0.19MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 2
acf-field: 29
acf-field-group: 7
attachment: 493
custom_css: 3
custom_order_status: 10
customize_changeset: 1
edge: 2
elementor_library: 33
enr_subsc_plan: 3
nav_menu_item: 69
oembed_cache: 5
omapi: 4
page: 35
post: 129
product: 54
product_variation: 190
revision: 1570
rp_shop_giftcard: 143
shop_coupon: 388
shop_order_placehold: 108963
tab_slider: 3
testimonial: 2
vc_settings_preset: 6
wass_event: 31

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Search order by product SKU for WooCommerce: by laboratorio d'Avanguardia – 0.2
Toolbox for WooCommerce Subscriptions: by Shop Plugins – 1.5.4
UPS OAuth2 Access Token Manager: by Robert Brian Gottier – 0.0.3
WASS Email Marketing: by Robert Brian Gottier – 0.0.1
WASS Loyal Customers: by Robert B Gottier – 0.0.1
WASS Multi-Step Checkout: by Robert Brian Gottier – 1.00
WASS Outgoing Email Rotation (SMTP): by Robert Brian Gottier – 1.0.0
WASS Upcoming Subscription Renewals Widget: by Robert Brian Gottier – 1.0.0
WASS Tools: by Robert Brian Gottier – 1.0.3
WASS Show All Reviews: by Brian was AppJetty – 7.7.7
Checkout Field Editor for WooCommerce: by ThemeHigh – 2.0.1
Payment Plugins Braintree For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.2.55

WooCommerce Search by Product SKU: by Clayton Kriesel [Three Remain Production] – 1.0
WooCommerce.com Update Manager: by Automattic – 1.0.2
WooCommerce Extended Coupon Features PRO: by Soft79 – 3.3.3
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.10.2
WooCommerce New Customer Report: by SkyVerge – 1.1.0
OneSaas Connect: by OneSaas – 2.0.6.45
Sequential Order Numbers for WooCommerce: by SkyVerge – 1.10.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.4.2
Woo Subscriptions: by WooCommerce – 6.2.0
WooCommerce: by Automattic – 8.8.3
Yoast SEO Premium: by Team Yoast – 22.5
Yoast SEO: by Team Yoast – 22.5
WP Mail Logger Plugin (WMLP): by Robert Brian Gottier – 0.2.0
Yoast SEO: WooCommerce: by Team Yoast – 16.2

### Inactive Plugins (11) ###

LiveChat: by LiveChat – 4.5.20
MailChimp Tagged Signups: by Robert Brian Gottier – 1.0.0
Order Export for WooCommerce: by JEM Plugins – 3.22
Pixel Manager for WooCommerce: by SweetCode – 1.42.4
Route App: by Route – 2.2.10
WASS MailChimp MyAccount Page: by Robert Brian Gottier – 0.0.1
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.3.3
WooCommerce Legacy REST API: by WooCommerce – 1.0.1
WooCommerce PayPal Checkout Gateway: by WooCommerce (HACKED BY BRIAN) – 7772.1.3
WP 2FA - Two-factor authentication for WordPress: by Melapress – 2.6.4
WP Super Cache: by Automattic – 1.12.0

### Dropin Plugins () ###

install.php: WP Install Defaults
maintenance.php: maintenance.php

### Must Use Plugins (2) ###

Plugin History: by R.B. Gottier – 0.777
WASS Must Use Plugins: by Robert Brian Gottier – 1.0.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 11 MB

### WC Pages ###

Shop base: #1197 - /buy-wild-alaskan-salmon-online/
Cart: #312 - /cart/
Checkout: #313 - /checkout/
My account: #314 - /my-account/
Terms and conditions: #586 - /terms/

### Theme ###

Name: WASS Theme v3
Version: 3.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: wass-theme-v3/woocommerce/archive-product.php
wass-theme-v3/woocommerce/cart/cart-empty.php
wass-theme-v3/woocommerce/cart/cart-shipping.php
wass-theme-v3/woocommerce/cart/cart-totals.php
wass-theme-v3/woocommerce/cart/cart.php
wass-theme-v3/woocommerce/checkout/form-billing.php
wass-theme-v3/woocommerce/checkout/form-checkout.php
wass-theme-v3/woocommerce/checkout/form-coupon.php
wass-theme-v3/woocommerce/checkout/form-pay.php
wass-theme-v3/woocommerce/checkout/form-shipping.php
wass-theme-v3/woocommerce/checkout/payment.php
wass-theme-v3/woocommerce/checkout/review-order.php
wass-theme-v3/woocommerce/checkout/thankyou.php
wass-theme-v3/woocommerce/content-product.php
wass-theme-v3/woocommerce/content-single-product.php
wass-theme-v3/woocommerce/emails/admin-cancelled-order.php
wass-theme-v3/woocommerce/emails/admin-failed-order.php
wass-theme-v3/woocommerce/emails/admin-new-order.php
wass-theme-v3/woocommerce/emails/customer-completed-order.php
wass-theme-v3/woocommerce/emails/customer-invoice.php
wass-theme-v3/woocommerce/emails/customer-new-account.php
wass-theme-v3/woocommerce/emails/customer-note.php
wass-theme-v3/woocommerce/emails/customer-on-hold-order.php
wass-theme-v3/woocommerce/emails/customer-processing-order.php
wass-theme-v3/woocommerce/emails/customer-refunded-order.php
wass-theme-v3/woocommerce/emails/customer-reset-password.php
wass-theme-v3/woocommerce/emails/email-addresses.php
wass-theme-v3/woocommerce/emails/email-footer.php
wass-theme-v3/woocommerce/emails/email-header.php
wass-theme-v3/woocommerce/emails/email-styles.php
wass-theme-v3/woocommerce/emails/plain/customer-processing-order.php
wass-theme-v3/woocommerce/global/breadcrumb.php
wass-theme-v3/woocommerce/global/form-login.php
wass-theme-v3/woocommerce/loop/header.php
wass-theme-v3/woocommerce/loop/sale-flash.php
wass-theme-v3/woocommerce/myaccount/dashboard.php
wass-theme-v3/woocommerce/myaccount/form-edit-account.php
wass-theme-v3/woocommerce/myaccount/form-edit-address.php
wass-theme-v3/woocommerce/myaccount/form-login.php
wass-theme-v3/woocommerce/myaccount/form-lost-password.php
wass-theme-v3/woocommerce/myaccount/my-account.php
wass-theme-v3/woocommerce/myaccount/my-address.php
wass-theme-v3/woocommerce/myaccount/navigation.php
wass-theme-v3/woocommerce/myaccount/orders.php
wass-theme-v3/woocommerce/myaccount/view-order.php
wass-theme-v3/woocommerce/notices/error.php
wass-theme-v3/woocommerce/notices/notice.php
wass-theme-v3/woocommerce/notices/success.php
wass-theme-v3/woocommerce/order/order-again.php
wass-theme-v3/woocommerce/order/order-details-customer.php
wass-theme-v3/woocommerce/order/order-details-item.php
wass-theme-v3/woocommerce/order/order-details.php
wass-theme-v3/woocommerce/single-product/add-to-cart/external.php
wass-theme-v3/woocommerce/single-product/add-to-cart/grouped.php
wass-theme-v3/woocommerce/single-product/add-to-cart/simple.php
wass-theme-v3/woocommerce/single-product/add-to-cart/variable.php
wass-theme-v3/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
wass-theme-v3/woocommerce/single-product/add-to-cart/variation.php
wass-theme-v3/woocommerce/single-product/meta.php
wass-theme-v3/woocommerce/single-product/price.php
wass-theme-v3/woocommerce/single-product/product-image.php
wass-theme-v3/woocommerce/single-product/rating.php
wass-theme-v3/woocommerce/single-product/sale-flash.php
wass-theme-v3/woocommerce/single-product/tabs/tabs.php
wass-theme-v3/woocommerce/single-product-reviews.php
wass-theme-v3/woocommerce/single-product.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: https://wildalaskasalmonandseafood.com
Subscriptions-core Library Version: 7.0.0
Subscriptions Template Theme Overrides: wass-theme-v3/woocommerce/checkout/recurring-totals.php
wass-theme-v3/woocommerce/emails/admin-new-renewal-order.php
wass-theme-v3/woocommerce/emails/admin-new-switch-order.php
wass-theme-v3/woocommerce/emails/admin-payment-retry.php
wass-theme-v3/woocommerce/emails/cancelled-subscription.php
wass-theme-v3/woocommerce/emails/customer-completed-renewal-order.php
wass-theme-v3/woocommerce/emails/customer-completed-switch-order.php
wass-theme-v3/woocommerce/emails/customer-payment-retry.php
wass-theme-v3/woocommerce/emails/customer-processing-renewal-order.php
wass-theme-v3/woocommerce/emails/customer-renewal-invoice.php
wass-theme-v3/woocommerce/emails/expired-subscription.php
wass-theme-v3/woocommerce/emails/on-hold-subscription.php
wass-theme-v3/woocommerce/emails/plain/admin-payment-retry.php
wass-theme-v3/woocommerce/emails/plain/customer-completed-renewal-order.php
wass-theme-v3/woocommerce/myaccount/my-subscriptions.php
wass-theme-v3/woocommerce/myaccount/related-orders.php
wass-theme-v3/woocommerce/myaccount/related-subscriptions.php
wass-theme-v3/woocommerce/myaccount/subscription-details.php
wass-theme-v3/woocommerce/myaccount/subscription-totals-table.php

Subscription Statuses: wc-active: 748
wc-cancelled: 1774
wc-on-hold: 182
wc-paused: 283
wc-pending: 5
wc-pending-cancel: 53
wc-product-issues: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Illinois

### Subscriptions by Payment Gateway ###

Authorize.Net Credit Card: wc-active: 638
wc-cancelled: 1461
wc-on-hold: 171
wc-paused: 227
wc-pending: 5
wc-pending-cancel: 40

other: wc-cancelled: 168
wc-on-hold: 1

Braintree PayPal Gateway: wc-active: 107
wc-cancelled: 95
wc-on-hold: 9
wc-paused: 56
wc-pending-cancel: 13
wc-product-issues: 1

### Payment Gateway Support ###

Authorize.Net Credit Card: products
card_types
payment_form
inline
lightbox
tokenization
token_editor
charge
charge-virtual
authorization
capture_charge
customer_decline_messages
refunds
voids
customer_id
add_payment_method
apple_pay
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin

Braintree PayPal Gateway: tokenization
subscriptions
products
add_payment_method
subscription_cancellation
multiple_subscriptions
subscription_amount_changes
subscription_date_changes
default_credit_card_form
refunds
pre-orders
subscription_payment_method_change_admin
subscription_reactivation
subscription_suspension
subscription_payment_method_change_customer
wc_braintree_fees
wc_braintree_subscriptions
wc_braintree_subscriptions_change_payment_method
wc_braintree_cart_checkout
wc_braintree_banner_checkout
wc_braintree_product_checkout
wc_braintree_mini_cart

### Authorize.Net Credit Card ###

Environment: Test
Tokenization Enabled: 
Debug Mode: Off
Webhooks Enabled: ❌
						Not generated

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-02 01:18:45 -05:00
Options: ✔
Notes: 24
Onboarding: completed

### Action Scheduler ###

Complete: 22,181
Oldest: 2024-03-31 00:18:43 -0500
Newest: 2024-04-30 23:41:20 -0500

Failed: 49
Oldest: 2021-02-03 21:43:42 -0600
Newest: 2024-04-15 01:13:02 -0500

Pending: 1,481
Oldest: 2024-05-01 02:22:39 -0500
Newest: 2024-10-31 00:00:00 -0500

### Status report information ###

Generated at: 2024-05-01 00:18:12 -05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @skunkbad!

Thanks for reaching out. I'm sorry you're having trouble with the order edit screen.
We are aware of this bug and have implemented a couple of fixes for this. One will go out with 8.9.0 (https://github.com/woocommerce/woocommerce/pull/46476) and then we iterated on that fix for 9.0.0 too (https://github.com/woocommerce/woocommerce/pull/46985).

So far, we've found that those changes address the underlying performance issue. We have a beta for 8.9 already available in case you want to give that a try: https://developer.woocommerce.com/2024/04/29/woocommerce-8-9-pre-release-updates/.

I'm going to close this issue, but please do re-open if you're still having trouble.

**Comment by skunkbad** [comment]
I'm having this problem again. We now have about 120,000 orders, and this query is taking 72 seconds according to Query Monitor.
