### ISSUE TITLE
[Enhancement]: Add Navigation Landmarks

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce#47071]
### Describe the solution you'd like

An accessibility best practice (and sometimes requirement) is to [add navigation landmarks to a page](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11).

Users who use screen reading software will often use tools to help them skip repetitive parts of a website like the header, navigation, sidebar, etc. To give these tools as much information as possible we should add ARIA landmarks to these sections.

🔧 Example tool: [Landmark Navigation via Keyboard or Pop-up](https://chromewebstore.google.com/detail/landmark-navigation-via-k/ddpokpbjopmeeiiolheejjpkonlkklgp) Chrome browser extension

Here's what this tool outputs in an empty WooCommerce store:
<img width="1125" alt="Screenshot 2024-04-30 at 3 26 02 PM" src="https://github.com/woocommerce/woocommerce/assets/1065372/fe103583-5209-453a-ac8b-ac7e58b82c96">

Here's what it looks like on a live Woo store with other plugins & themes active: 
<img width="1294" alt="navigation-landmarks" src="https://github.com/woocommerce/woocommerce/assets/1065372/14865db5-36c0-494d-8d57-13c1cff08cde">

You can see in the live Woo store that we have 3 nav elements in the Main section. Two of those are from WooCommerce core. One is from a plugin (Gridlist toggle).

It would be helpful if WooCommerce core and extensions would label their landmarks to help screen reading software scan the page and give users the ability to skip right to the section they want.

My preferred solution: edit the Pagination template (`woocommerce/plugins/woocommerce/templates/loop/pagination.php`) to include an aria label.

``` html
<nav class="woocommerce-pagination" aria-label="Product Pagination">
```

---

Here's what this looks like if both WooCommerce & extensions had better labels on nav elements:

<img width="1289" alt="Screenshot 2024-04-30 at 3 32 58 PM" src="https://github.com/woocommerce/woocommerce/assets/1065372/585dc81c-6451-4e43-bbb1-8aa07d4a927f">

The labeled navigation elements are much more useful to people who use screen reading software.

### Describe alternatives you've considered

You can also use `aria-labelledby` but it seems less intuitive than `aria-label`. 🤷 

### Additional context

Additional WCAG reading: https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html

**Comment by amesplant** [comment]
I am looking into this issue this week
