### ISSUE TITLE
[Enhancement]: logger don't write to file if message empty

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#47090]
### Describe the solution you'd like

The file logger shouldn't write empty text to log file, since it will append a new line automatically and create huge empty log files if the text was filtered to '' (e.g. on `woocommerce_format_log_entry`) which can be used e.g. to prevent leaking of PII data to the log file or as a way to filter out irrelevant error messages to avoid write race conditions that possibly clash with higher priority errors
(since there is no other filter/hook where the whole message with all details can be retrieved and possible the logging aborted)

**Comment by jorgeatorres** [comment]
Thanks for reaching out @kkmuffme!

Please note that WC provides a filter that you can use to prevent a message from being logged at all: https://github.com/woocommerce/woocommerce/blob/de91a0881d7df32573b107507f9f836897832612/plugins/woocommerce/includes/class-wc-logger.php#L186-L186

Does that suit your use case?

**Comment by kkmuffme** [comment]
Thanks, I'm aware, however there are 2 reasons why I didn't use that:
- when using multiple handlers the message is changed for all subsequent handlers when using that filter (since it's reassigning $message in a loop), but we only need to filter it for the file handler.

- it's too early to prevent race conditions/overwrites, since, depending on the filters added,... it will take up to 5ms up to the point where it writes to the file, while the one I used is the last possible hook immediately before writing basically and doesn't have that delay when checking with a profiler.

**Comment by coreymckrill** [comment]
@kkmuffme re: the first reason, just noting that the filter hook provides a parameter for the current handler, so you could do something like this to isolate just the file handler:

```php
use Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2;
add_filter(
	'woocommerce_logger_log_message',
	function ( $message, $level, $context, $handler ) {
		if ( LogHandlerFileV2::class === $handler ) {
			return null;
		}
	},
	10,
	4
);
```

**Comment by kkmuffme** [comment]
This doesn't work bc this will change $message for all subsequent handlers too which is wrong.

**Comment by coreymckrill** [comment]
Oh, I see what you mean! I've opened an issue for that here: https://github.com/woocommerce/woocommerce/issues/47126
