### ISSUE TITLE
Update Cart and Checkout Slot Fill to the latest version of @wordpress/components

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#47106]
In my opinion it is not worth trying to replace the @wordpress/components Slot Fill implementation as part of this, for several reasons:

The rationale that wp components is not suited to front-ends doesn't apply to the slot fill, its not styled or user facing behaviour. It's more like a utility for React.

Once wp components is tree-shaken to just the slot fill library it will be very small

There is not a really good drop-in replacement that would give backwards compat, not a good use of our time to reimplement slot fill functionality, even if a library comes close

Finally, we're looking in future to provide more of these extension points via the block hooks API. With that in mind it doesn't make much sense to invest further in a Slot Fill implementation.

**Comment by ralucaStan** [comment]
this was closed via https://github.com/woocommerce/woocommerce/pull/47105
