### ISSUE TITLE
Prevent `product_edit` and `product_add_publish` tracks from being triggered when importing products

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#47107]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Currently we are triggering the `product_edit` and `product_add_publish` when a product published for the first time or saved. This appears to also happen when products are imported and these events are triggered. This causes a weird spike of edit/publish events that makes the data more difficult to analyze.

**To reproduce**

1. Create a new WooCommerce store and install the WooCommerce Beta Tester from the mono repo
2. Make sure you have tracking enabled under **WooCommerce > Settings > Advanced > WooCommerce.com > Enable tracking**
3. Go to **Products > All products** and click **Import**
4. Import the CSV available within the mono repo: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/sample-data/sample_products.csv
5. Finish the importing
6. Go to **WooCommerce > Status > Logs** and open the tracks log ( only created if the beta tester is enabled )
7. Notice the events for `product_edit` and `product_add_publish` for each imported product.

**Acceptance criteria**

- [ ] `product_edit` and `product_add_publish` events should not be triggered when a user is importing products

**Comment by nathanss** [comment]
[Other alternative would be to use the `source` property](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L344), set it to something like `bulk-import`, and then we could keep the tracks events and filter them in the analysis.
