### ISSUE TITLE
"View affected templates" to view outdated templates brings user to a loop

### ISSUE THREAD

**Issue by jeff-at-livecanvas** [woothemes/woocommerce#47142]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the wp-admin Dashboard, if using **a theme with outdated WooCommerce templates**, an alert message and a button is shown to help the user: "View affected templates".
Clicking this button brings to the WooCommerce Status view, but without going to the right section.
Plus, the same button shows again, bringing the user to a loop.

### Expected behavior

I'd expect the button to move to the right tab & anchor, to actually see the list of affected templates.

### Actual behavior

Clicking this button just brings to the WooCommerce Status view, in a new tab.

### Steps to reproduce

1. Go to wp-admin, when running a Theme with outdated WooCommerce Templates.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888/livecanvas-wp
Site address (URL): http://localhost:8888/livecanvas-wp
WC Version: 8.8.2
REST API Version: ✔ 8.8.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2u PHP/8.2.0 mod_wsgi/3.5 Python/2.7.18 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 8.2.0
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.2
WC Database Prefix: wp_
Total Database Size: 21.82MB
Database Data Size: 19.29MB
Database Index Size: 2.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_api_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_api_key_uses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_ewwwio_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mwai_filemeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mwai_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 14.34MB + Index: 0.13MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_simply_static_pages: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_staatic_builds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_staatic_crawl_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_staatic_deployments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_staatic_known_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_staatic_log_entries: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_staatic_publications: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_staatic_results: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_staatic_results_deployment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
acf-post-type: 1
attachment: 28
custom_css: 4
customize_changeset: 6
imajinn_prompt: 5
lc_block: 2
lc_dynamic_template: 5
lc_gt_block: 1
lc_partial: 5
lc_section: 4
meta_box: 1
movie: 5
nav_menu_item: 9
oembed_cache: 11
page: 48
post: 9
product: 17
product_variation: 7
revision: 410
wp_block: 1
wp_font_face: 4
wp_font_family: 1
wp_global_styles: 4
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Imajinn AI: by Imajinn AI – 1.5.4
LC After Dark Screensaver: by LiveCanvas – 1.0
LiveCanvas: by The LiveCanvas Team – 3.11.0
Reset Theme Options: by  – 0.3
WooCommerce: by Automattic – 8.8.2 (update to version 8.8.3 is available)

### Inactive Plugins (72) ###

Advanced Custom Fields: by WP Engine – 6.2.9
AI Engine: by Jordy Meow – 2.2.63
AI Image Generator: by Cognitive Dynamics – 1.0.5
AI Mojo: by WPAIMojo – 0.9.2
API UI Plugin: by Avdax – 1.0
Autoptimize: by Frank Goossens (futtta) – 3.1.10
Breadcrumb NavXT: by John Havlik – 7.2.0
bunny.net: by bunny.net – 1.0.8
Classic Editor: by WordPress Contributors – 1.6.3
Classic Widgets: by WordPress Contributors – 0.3
CMB2: by CMB2 team – 2.10.1
CMB2 Admin Extension: by twoelevenjay – 0.2.3
Contact Form 7: by Takayuki Miyoshi – 5.8.3
CookieYes | GDPR Cookie Consent: by CookieYes – 3.1.7
CSS Hero: by The CSS Hero Team – 4.08
Custom Fonts: by Brainstorm Force – 2.1.0
EWWW Image Optimizer: by Exactly WWW – 7.2.1
Font Hero: by DPlugins – 2.0.1
FrozenCanvas: by Dopewp.com – alpha1
Fullwidth Page Templates: by Brainstorm Force – 1.1.1
HappyFiles: by Codeer – 1.5.1
Image Background Focus Position: by florianmatthias – 1.0
Insert PHP Code Snippet: by xyzscripts.com – 1.3.4
iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: by iubenda – 3.7.8
Jetpack: by Automattic – 12.8.1
LC Autocomplete: by Artisan – 1.0
LC Cookies: by Giovanni Panasiti – 1.0
LiveCanvas Custom Form Pompi: by  – 0.1
LiveCanvas Custom Posts Display: by livecanvas.com – 0.1
LiveCanvas Debugger: by livecanvas.com –
LiveCanvas Demo Enabler: by Dopewp.com – 1.0
LiveCanvas Experiments Guby: by livecanvas.com –
LiveCanvas Experiments Official: by livecanvas.com –
LiveCanvas Experiments Tree: by livecanvas.com –
LiveCanvas Recipes: by LiveCanvas – 1.0
Loco Translate: by Tim Whitlock – 2.6.6
Matt Debugger: by  –
Meta Box: by MetaBox.io – 5.8.2
OpenAI Chat: by Your Name – 2.0
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.4
Polylang: by WP SYNTEX – 3.5.2
Post Type Switcher: by Triple J Software
Inc. – 3.2.1

Rank Math SEO: by Rank Math – 1.0.206
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Reset Meta Box Positions: by David Gwyer – 0.1.2
Saladil: by Saladil Team – 0.9.7
Shortcodes Ultimate: by Vova Anokhin – 5.13.3
Simply Static: by Patrick Posner – 3.1.2
Simply Static Deploy: by GRRR – 2.3.0
Smush: by WPMU DEV – 3.15.1
SSGpress: by Merlin Scholz – 0.0.1
Staatic - Static Site Generator: by Team Staatic – 1.6.3
StaticPress2019: by yshinoda
wokamoto
amimotoami
pas5027
hideokamoto – 0.8.0

TailPress: by freshbrewedweb – 0.4.4
Tangible: Loops & Logic: by Team Tangible – 3.3.1
Text Spinner: by WPGurus – 1.3.0
Theme Check: by Theme Review Team – 20230417
UsageDD: by Dion Designs – 2.1
Use Any Font: by Dnesscarkey – 6.3.04
User Switching: by John Blackbourn & contributors – 1.7.2
W3 Total Cache: by BoldGrid – 2.6.0
WooPayments: by Automattic – 7.2.0 (update to version 7.5.3 is available)
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.5
WordPress Importer: by wordpressdotorg – 0.8.1
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.21

WP2Static: by WP2Static – 7.1.4-dev
WP Coder: by WPCoder – 3.2
WP Compress | MainWP: by WP Compress – 6.10.07
WP Fastest Cache: by Emre Vona – 1.2.2
Yabe Siul: by Rosua – 1.0.21
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Yoast SEO: by Team Yoast – 21.5

### Must Use Plugins (8) ###

0-32bit-integer-warnings.php: by  –
0-allowed-redirect-hosts.php: by  –
0-check-theme-availability.php: by  –
0-dns-functions.php: by  –
0-sqlite.php: by  –
0-thumbnails.php: by  –
LiveCanvas Compatibility Filters Plugin: by The LiveCanvas Team – 1.1.2
Meta Box Test: by The LiveCanvas Team – 1.0.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 125 B

### WC Pages ###

Shop base: #46 - /shop/
Cart: #47 - /cart/
Checkout: #48 - /checkout/
My account: #49 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: picostrap5
Version: 3.1.0
Author URL: https://picostrap.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: picostrap5/woocommerce/archive-product.php version 3.4.0 is out of date. The core version is 8.6.0
picostrap5/woocommerce/global/sidebar.php
picostrap5/woocommerce/myaccount/my-address.php version 2.6.0 is out of date. The core version is 8.7.0
picostrap5/woocommerce/myaccount/my-orders.php
picostrap5/woocommerce/myaccount/navigation.php
picostrap5/woocommerce/myaccount/orders.php
picostrap5/woocommerce/product-searchform.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-03 20:14:04 +00:00
Options: ✔
Notes: 136
Onboarding: completed

### Action Scheduler ###

Complete: 29
Oldest: 2024-04-23 14:14:53 +0000
Newest: 2024-05-03 13:47:32 +0000

Failed: 5
Oldest: 2023-03-03 15:38:55 +0000
Newest: 2023-05-01 00:32:46 +0000

Pending: 2
Oldest: 2024-05-03 15:56:02 +0000
Newest: 2024-05-04 01:47:32 +0000

### Status report information ###

Generated at: 2024-05-03 13:56:00 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
- We can add an `id` attribute to the relevant section of `includes/admin/views/html-admin-page-status-report.php`. We can then link directly to it from the admin notice.
- Owing to the 'layout status wrapper' at the top of these pages, we may also need some JS (perhaps a suitable function already exists?) to offset the scroll position. Otherwise, part of the relevant section will be obscured by the page header:

![settings-header-offset](https://github.com/woocommerce/woocommerce/assets/3594411/9a51d07b-0da9-48b0-bdeb-04d9883d9628)
