### ISSUE TITLE
[Enhancement] Move all Pricing fields to General and remove Pricing tab

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#47145]
Context and design is here in P2: pfrEX1-8Y-p2

We hypothesized that putting all the **Pricing** fields under **General** could help users successfully create more products, and it might be worthwhile as a quick experiment to see what happens. It would also simplify the tab menu, since the **Pricing** tab would no longer appear.

**Comment by pmcpinto** [comment]
I'll close this issue as we already have #47053
