### ISSUE TITLE
Problem/Error/Bug with entering the menu (Categories) under the header

### ISSUE THREAD

**Issue by kaprizo1** [woothemes/woocommerce#47163]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,
I have a problem (error or bug) with entering the menu (Categories) under the header of the main page, which does not load and does not lead anywhere. The reason for this is perhaps or from the Theme or because I changed the PHP version to 8.0. , I do not know! How can this error be fixed?
Thanks in advance!
All the best!
![under hedar menu](https://github.com/woocommerce/woocommerce/assets/168896768/864fc42b-713b-4fce-89e9-138aaf5a6d53)

### Expected behavior

I have a problem (error or bug) with entering the menu (Categories) under the header of the main page, which does not load and does not lead anywhere. The reason for this is perhaps or from the Theme or because I changed the PHP version to 8.0. , I do not know! How can this error be fixed?

### Actual behavior

I have a problem (error or bug) with entering the menu (Categories) under the header of the main page, which does not load and does not lead anywhere. The reason for this is perhaps or from the Theme or because I changed the PHP version to 8.0. , I do not know! How can this error be fixed?
![under hedar menu](https://github.com/woocommerce/woocommerce/assets/168896768/c1890ce6-b904-4ca2-ab87-0e32b70c804f)

### Steps to reproduce

![under hedar menu](https://github.com/woocommerce/woocommerce/assets/168896768/12435ad5-15be-4e3c-b3f1-c3329f94aaec)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://kaprizo.com
Site address (URL): https://kaprizo.com
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 64 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB-cll-lve-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: wp8r_
Total Database Size: 63.40MB
Database Data Size: 56.96MB
Database Index Size: 6.44MB
wp8r_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_actionscheduler_actions: Data: 3.61MB + Index: 1.17MB + Engine MyISAM
wp8r_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_actionscheduler_logs: Data: 2.00MB + Index: 1.82MB + Engine MyISAM
wp8r_aioseo_cache: Data: 0.10MB + Index: 0.01MB + Engine MyISAM
wp8r_aioseo_crawl_cleanup_blocked_args: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_aioseo_crawl_cleanup_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_aioseo_notifications: Data: 0.10MB + Index: 0.01MB + Engine MyISAM
wp8r_aioseo_posts: Data: 0.40MB + Index: 0.02MB + Engine MyISAM
wp8r_cky_banners: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp8r_cky_cookies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_cky_cookie_categories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_commentmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp8r_comments: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp8r_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_frmt_form_entry: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_frmt_form_entry_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_frmt_form_reports: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_frmt_form_views: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_fsmpt_email_logs: Data: 0.68MB + Index: 0.00MB + Engine MyISAM
wp8r_gla_attribute_mapping_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_gla_budget_recommendations: Data: 0.10MB + Index: 0.12MB + Engine MyISAM
wp8r_gla_merchant_issues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_gla_shipping_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_gla_shipping_times: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_jetpack_sync_queue: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp8r_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_litespeed_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_litespeed_url_file: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_loginizer_logs: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_mailpoet_automations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_automation_runs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_automation_run_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_automation_run_subjects: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_automation_triggers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_automation_versions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_dynamic_segment_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_feature_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_mailpoet_newsletters: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp8r_mailpoet_newsletter_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_newsletter_templates: Data: 1.04MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_scheduled_tasks: Data: 0.13MB + Index: 0.05MB + Engine MyISAM
wp8r_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_segments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_mailpoet_sending_queues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_statistics_bounces: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_statistics_woocommerce_purchases: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_subscribers: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp8r_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_subscriber_tag: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_user_agents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_options: Data: 3.87MB + Index: 0.14MB + Engine MyISAM
wp8r_postmeta: Data: 3.57MB + Index: 0.40MB + Engine MyISAM
wp8r_posts: Data: 9.91MB + Index: 0.14MB + Engine MyISAM
wp8r_prli_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_prli_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_prli_link_metas: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_css: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
wp8r_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_sliders: Data: 0.19MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_slides: Data: 1.96MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_ta_link_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_ta_link_clicks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_termmeta: Data: 0.05MB + Index: 0.06MB + Engine MyISAM
wp8r_terms: Data: 0.01MB + Index: 0.04MB + Engine MyISAM
wp8r_term_relationships: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp8r_term_taxonomy: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp8r_userfeedback_surveys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_userfeedback_survey_responses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_usermeta: Data: 0.09MB + Index: 0.03MB + Engine MyISAM
wp8r_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_wc_admin_notes: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_admin_note_actions: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp8r_wc_category_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wfblockediplog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wfblocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wfconfig: Data: 5.30MB + Index: 0.01MB + Engine MyISAM
wp8r_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wffilemods: Data: 13.31MB + Index: 1.51MB + Engine MyISAM
wp8r_wfhits: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp8r_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wfissues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_wfknownfilelist: Data: 9.82MB + Index: 0.46MB + Engine MyISAM
wp8r_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wflocs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp8r_wflogins: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
wp8r_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8r_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp8r_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp8r_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp8r_wfpendingissues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8r_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wfsecurityevents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wfstatus: Data: 0.19MB + Index: 0.09MB + Engine MyISAM
wp8r_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wfwaffailures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wpforms_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wpforms_payments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wpforms_payment_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_wpmailsmtp_debug_events: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp8r_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_yith_wcwl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8r_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 360
customize_changeset: 1
custom_css: 4
elementor_library: 10
mailpoet_page: 1
mas_static_content: 25
nav_menu_item: 265
page: 65
post: 2
product: 81
revision: 448
shop_coupon: 1
wpforms: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Redux Framework: by Team Redux – 4.4.16
Advanced Custom Fields: by WP Engine – 6.2.9
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
All in One SEO: by All in One SEO Team – 4.6.2
Backuply: by Softaculous – 1.3.0
Classic Editor: by WordPress Contributors – 1.6.3
CookieYes | GDPR Cookie Consent: by CookieYes – 3.2.2
Electro Extensions: by MadrasThemes – 3.3.7
Elementor: by Elementor.com – 3.21.4
Envato Market: by Envato – 2.0.11
Filter Everything — WooCoomerce Product & WordPress Filter: by Andrii Stepasiuk – 1.8.4
Google Listings and Ads: by WooCommerce – 2.6.8
Site Kit by Google: by Google – 1.125.0
GoSMTP: by Softaculous Team – 1.0.6
GTranslate: by Translate AI Multilingual Solutions – 3.0.6
Hello Dolly: by Matt Mullenweg – 1.7.2
WPBakery Page Builder: by Michael M - WPBakery.com – 7.6
LiteSpeed Cache: by LiteSpeed Technologies – 6.2.0.1
Loginizer: by Softaculous – 1.8.4
MailPoet: by MailPoet – 4.49.1
MAS Static Content: by MadrasThemes – 1.0.8
MAS Brands for WooCommerce: by MadrasThemes – 1.0.9
OptinMonster: by OptinMonster Popup Builder Team – 2.16.1
Plugin Detective - Troubleshooting: by NSquared – 1.2.20
Slider Revolution: by ThemePunch – 6.6.14
Simple Custom CSS: by John Regan – 4.0.6
WooCommerce.com Update Manager: by Automattic – 1.0.2
WooCommerce: by Automattic – 8.8.3
Wordfence Security: by Wordfence – 7.11.5
WP File Manager: by mndpsingh287 – 7.2.6
WP Mail SMTP: by WP Mail SMTP – 4.0.1
WPForms Lite: by WPForms – 1.8.8.3
YITH WooCommerce Compare: by YITH – 2.38.0
YITH WooCommerce Wishlist: by YITH – 3.32.0

### Inactive Plugins (4) ###

FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.73
Loco Translate: by Tim Whitlock – 2.6.7
One Click Demo Import: by OCDI – 3.2.1
WooPayments: by Automattic – 7.5.3

### Dropin Plugins () ###

maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 30 KB

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #3854 - /my-account-2/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Child-Theme Kaprizo
Version: 21.0.1708246547
Author URL: https://kaprizo.com/
Child Theme: ✔
Parent Theme Name: Electro
Parent Theme Version: 3.3.7
Parent Theme Author URL: https://madrasthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: Child-ThemeKaprizo/woocommerce/archive-product.php
Child-ThemeKaprizo/woocommerce/global/quantity-input.php
Child-ThemeKaprizo/woocommerce/myaccount/dashboard.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-05 08:35:31 +00:00
Options: ✔
Notes: 109
Onboarding: completed

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://kaprizo.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Complete: 10,878
Oldest: 2024-04-03 18:01:28 +0000
Newest: 2024-05-04 17:58:16 +0000

Failed: 802
Oldest: 2023-07-21 18:45:51 +0000
Newest: 2024-05-04 17:08:46 +0000

Pending: 18
Oldest: 2024-05-04 17:59:43 +0000
Newest: 2024-05-07 08:55:23 +0000

### Status report information ###

Generated at: 2024-05-04 17:59:27 +00:00
`
[SystemStatusReport_kaprizo.com_2024-05-04T18-03-23.txt](https://github.com/woocommerce/woocommerce/files/15210538/SystemStatusReport_kaprizo.com_2024-05-04T18-03-23.txt)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @kaprizo1 -- your best bet is to try activating a default theme and see if that fixes the issue for you.  If it does, best to get in touch with your theme's author for support.

**Comment by kaprizo1** [comment]
> Hi @kaprizo1 -- your best bet is to try activating a default theme and see if that fixes the issue for you. If it does, best to get in touch with your theme's author for support.

Thank you for your assistance!
