### ISSUE TITLE
scheduled items. (After few days of reactivating compatibility mode, they are still pending). And they have stopped at this stage.

### ISSUE THREAD

**Issue by paulvek** [woothemes/woocommerce#47166]
scheduled items. (After few days of reactivating compatibility mode, they are still pending). And they have stopped at this stage.

![9hJakkk](https://github.com/woocommerce/woocommerce/assets/153482922/898229a8-224d-4273-8d6e-0a2f2019238d)

_Originally posted by @paulvek in https://github.com/woocommerce/woocommerce/issues/46909#issuecomment-2095337304_

**Comment by vedanshujain** [comment]
Note that we are discussing this here https://github.com/woocommerce/woocommerce/issues/46909#issuecomment-2098312006

**Comment by vedanshujain** [comment]
Closing in favor of #46909, but will reopen if there's an specific error that needs fixing.
