### ISSUE TITLE
[Enhancement]: Allow filtering the cart and checkout blocks data when hydrated on the server side

### ISSUE THREAD

**Issue by smachi** [woothemes/woocommerce#47174]
### Describe the solution you'd like

We have some filters as explained in these docs:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/available-filters.md

That we can use to alter the cart and checkout blocks when they are rendered on the browser side.
But if the blocks come prerendered because they were hydrated on the server side, these filters do not work.

I couldn't find a way to filter the hydrated content before they are submitted to the browser to apply the same changes there too.

**Comment by opr** [comment]
@smachi thanks for reporting this.

> if the blocks come prerendered because they were hydrated on the server side, these filters do not work.

Could you please provide more info on what you mean by this? We don't render them on the server side, they are client-side only.

How are you adding the filters, and when is the script that contains them loaded? I tested this loading a script using the [`IntegrationInterface`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/integration-interface.md#integrationinterface-methods) and it worked OK for me.

It'd be great to know more about your setup to see if this is a bug with our code or if you need to tweak something on your end.

Thanks!

**Comment by smachi** [comment]
Hi @opr 

You're right.
I've just created a new extension by using this template:
https://www.npmjs.com/package/@woocommerce/extend-cart-checkout-block

And it seems working as expected in all cases.

I'm going to review my code.

Thank you!
