### ISSUE TITLE
Concurrency for community-label.yml causing failed workflow runs

### ISSUE THREAD

**Issue by tammullen** [woothemes/woocommerce#47179]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Some of the workflow runs for community-label.yml are failing.
https://github.com/woocommerce/woocommerce/actions/workflows/community-label.yml?query=is%3Acancelled

They fail with error `Canceling since a higher priority waiting request for 'Add Community Label, Assign Reviewers-refs/heads/trunk' exists`

The workflow currently has this concurrency step

```
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
```

The `github.ref` is always returning `trunk` instead of the branch name so it appears like the workflow is already running when multiple are triggered at the same time. Perhaps use `github.head_ref` instead https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request_target-workflow-based-on-the-head-or-base-branch-of-a-pull-request

### Expected behavior

All runs pass

### Actual behavior

Some runs fail if there is another run in progress at the same time. 
https://github.com/woocommerce/woocommerce/actions/workflows/community-label.yml?query=is%3Acancelled

### Steps to reproduce

Go to https://github.com/woocommerce/woocommerce/actions/workflows/community-label.yml
See some runs are cancelled due to error

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adimoldovan** [comment]
Noting that this was affecting the pr-project-label.yml workflow too and was fixed with https://github.com/woocommerce/woocommerce/pull/45793. We should check if other workflows are affected.
