### ISSUE TITLE
CYS: In WP 6.4.4, the suggested font pairings do not appear

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#47170]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Discovered while doing WC 8.9 Beta testing.

In WP 6.4.4, the two suggested font pairings do not appear in the "Choose fonts" screen of CYS:

<img width="352" alt="font pairings WP 6 4 4" src="https://github.com/woocommerce/woocommerce/assets/4509348/70162164-72fa-4e30-87b3-617a3490060a">

However, they do appear in WP 6.5
<img width="359" alt="font pairings 6 5" src="https://github.com/woocommerce/woocommerce/assets/4509348/231bea02-e6eb-4d0b-940a-fe733508375a">

### Expected behavior

The generated font pairings should appear in WP 6.4.4

### Actual behavior

The generated font pairings do not appear in WP 6.4.4

### Steps to reproduce

1. Create a WP 6.4.4 site.
2. Install and activate WooCommerce 8.9 beta (already available in WP.org)
3. Go through the CYS flow until you get to the "Choose fonts" screen.
4. Notice that the font pairings were not shown. 

### WordPress Environment

WP 6.4.4.
WC 8.9.0-beta.1
Theme: TT4

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Already notified the CYS folks here: p1714986589976229-slack-C053716F2H2

**Comment by gigitux** [comment]
Thanks for opening this issue, @rodelgc!

Checking the code, it doesn't look like a regression, and it always worked in this way. This use-case has been implemented in this PR: https://github.com/woocommerce/woocommerce/pull/44532. You can check the first video, and you can see that it works as expected.

**Comment by nefeline** [comment]
Thanks for reaching out to us @rodelgc! What you are describing on this issue is the expected behavior: prior to WP 6.5, we display that message as [the new Font Library was released only on this version](https://make.wordpress.org/core/2024/03/14/new-feature-font-library/).

I'm going ahead and closing this one out, but feel free to re-open it in case of additional/related questions & concerns! I know you mentioned the issue with the e2e tests in our internal conversation: we are going to tackle it separately 🙌 .
