### ISSUE TITLE
Coupon code not showing on Basket

### ISSUE THREAD

**Issue by DeafAware** [woothemes/woocommerce#47185]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After adding a product on the Product page I was taken to the Basket page and applied a coupon code, which reduced the cost of the balance.

However, when I moved to the Checkout page the coupon had not been applied on the Order Summary. The original full cost of the product was shown and when I tried to add the coupon code it said 'coupon code has already been applied'. 

When I paid and was taken to the Payment Success page, the coupon code had been applied and I had only paid the reduced price (even though on the Checkout page it said I was going to pay the full price). 

### Expected behavior

When a coupon code is applied it is visible at all times and reduces the price on the Basket page, Checkout page and Payment Success page

### Actual behavior

As above

### Steps to reproduce

1) Add a product to the basket and apply launch30 coupon code on the Basket page: https://deafaware.msdp.org.uk/basket/
2) On the Checkout page the coupon is not showing on the Order Summary: https://deafaware.msdp.org.uk/checkout/.
3) Use test card details on the page to complete purchase
4) The Order Confirmed page shows that the coupon has actually been applied.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://deafaware.msdp.org.uk
Site address (URL): https://deafaware.msdp.org.uk
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 800 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.44-log
Max Upload Size: 800 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: 4xbzk_
Total Database Size: 39.49MB
Database Data Size: 32.32MB
Database Index Size: 7.17MB
4xbzk_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
4xbzk_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
4xbzk_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
4xbzk_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
4xbzk_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_actionscheduler_actions: Data: 2.52MB + Index: 1.73MB + Engine InnoDB
4xbzk_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_actionscheduler_logs: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
4xbzk_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
4xbzk_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
4xbzk_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
4xbzk_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_grassblade_completions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_grassblade_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_grassblade_scorm_data: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_irrp_redirectionmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_irrp_redirections: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
4xbzk_irrp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
4xbzk_irrp_referer_urls: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
4xbzk_learndash_pro_quiz_category: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_learndash_pro_quiz_form: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_learndash_pro_quiz_lock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_learndash_pro_quiz_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_learndash_pro_quiz_prerequisite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_learndash_pro_quiz_question: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_learndash_pro_quiz_statistic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_learndash_pro_quiz_statistic_ref: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_learndash_pro_quiz_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_learndash_pro_quiz_toplist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_learndash_user_activity: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
4xbzk_learndash_user_activity_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_learnpress_files: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_learnpress_order_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_learnpress_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_learnpress_question_answermeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_learnpress_question_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_learnpress_quiz_questions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_learnpress_sections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_learnpress_section_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_learnpress_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_learnpress_user_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_learnpress_user_items: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
4xbzk_learnpress_user_item_results: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
4xbzk_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
4xbzk_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
4xbzk_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
4xbzk_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
4xbzk_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
4xbzk_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
4xbzk_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_options: Data: 8.02MB + Index: 0.14MB + Engine InnoDB
4xbzk_postmeta: Data: 0.28MB + Index: 0.13MB + Engine InnoDB
4xbzk_posts: Data: 14.25MB + Index: 0.22MB + Engine InnoDB
4xbzk_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_thim_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
4xbzk_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
4xbzk_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
4xbzk_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
4xbzk_wc_orders_meta: Data: 0.11MB + Index: 0.23MB + Engine InnoDB
4xbzk_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
4xbzk_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
4xbzk_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
4xbzk_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
4xbzk_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
4xbzk_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
4xbzk_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
4xbzk_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
4xbzk_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 66
customize_changeset: 1
elementor_library: 1
gb_xapi_content: 2
groups: 35
ldgr_group_code: 9
lp_course: 2
lp_lesson: 2
mailpoet_page: 1
page: 30
post: 2
product: 2
revision: 694
sfwd-certificates: 3
sfwd-courses: 2
sfwd-lessons: 3
shop_coupon: 1
shop_order_placehold: 47
um_directory: 1
um_form: 3
wp_block: 3
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 7
wp_template: 19
wp_template_part: 5
wpcode: 3
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Antispam Bee: by pluginkollektiv – 2.11.6
Blockskit: by blockskitdev – 1.0.1
CookieYes | GDPR Cookie Consent: by CookieYes – 3.2.2
GrassBlade xAPI Companion: by Next Software Solutions – 6.1.5
Jetpack: by Automattic – 13.3.1
Multiple Themes: by David Gewirtz – 7.1.1
LearnDash Group Registration: by WisdmLabs – 4.3.12
LearnDash LMS - Certificate Builder: by LearnDash – 1.0.4
LearnDash LMS - Course Grid: by LearnDash – 2.0.9
LearnDash Licensing & Management: by LearnDash – 1.3
LearnDash LMS - WooCommerce Integration: by LearnDash – 1.9.8.1
MailPoet: by MailPoet – 4.49.1
Members: by MemberPress – 3.2.9
Redirect Redirection: by Inisev – 1.2.2
LearnDash LMS: by LearnDash – 4.14.0
Ultimate Member: by Ultimate Member – 2.8.5
WooCommerce.com Update Manager: by Automattic – 1.0.2
WooPayments: by Automattic – 7.5.3
WooCommerce Shipping & Tax: by WooCommerce – 2.5.5
WooCommerce: by Automattic – 8.8.3
WPForms Lite: by WPForms – 1.8.8.3

### Inactive Plugins (5) ###

Advanced Import: by AddonsPress – 1.4.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
WC Custom Thank You: by Nicola Mustone – 1.2.1
WPCode Lite: by WPCode – 2.1.12
WP Mail SMTP: by WP Mail SMTP – 4.0.1

### Dropin Plugins () ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 909 KB

### WC Pages ###

Shop base: #472 - /shop/
Basket: #473 - /basket/
Checkout: #474 - /checkout/
My account: #475 - /my-account/
Terms and conditions: #124 - /lp-term-conditions/

### Theme ###

Name: Blockskit Medical
Version: 1.0.2
Author URL: https://blockskit.com
Child Theme: ✔
Parent Theme Name: Blockskit Base
Parent Theme Version: 1.0.8 – 1.0.9 is available
Parent Theme Author URL: https://blockskit.com
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/msdporg/public_html/deafaware.msdp.org.uk/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/msdporg/public_html/deafaware.msdp.org.uk/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/msdporg/public_html/deafaware.msdp.org.uk/wp-content/plugins/woocommerce/templates/block-notices/success.php
blockskit-medical/templates/archive-product.html
blockskit-medical/templates/page-cart.html
blockskit-medical/templates/page-checkout.html
blockskit-medical/templates/product-search-results.html
blockskit-medical/templates/single-product.html

### WooPayments ###

Version: 7.5.3
Connected to WPCOM: Yes
WPCOM Blog ID: 232068590
Account ID: acct_1P8JHHFxpvBjBGW5
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Enabled
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-06 14:29:27 +00:00
Options: ✔
Notes: 76
Onboarding: completed

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://deafaware.msdp.org.uk?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Canceled: 33
Oldest: 2024-04-23 18:47:50 +0000
Newest: 2024-05-06 11:01:07 +0000

Complete: 4,826
Oldest: 2024-04-06 11:47:47 +0000
Newest: 2024-05-06 13:37:14 +0000

Failed: 183
Oldest: 2024-03-31 18:06:01 +0000
Newest: 2024-05-06 12:52:17 +0000

Pending: 11
Oldest: 2024-05-06 13:39:14 +0000
Newest: 2024-05-12 20:36:46 +0000

### Status report information ###

Generated at: 2024-05-06 13:37:54 +00:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @DeafAware,

Can you confirm that you've tried these two troubleshooting steps? 

> I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).

I'm not able to reproduce this issue using a default theme.
