### ISSUE TITLE
[Launch Your Store] After completing an essential task, redirect users back to LYS hub

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#47190]
When users complete an essential task, ideally they should be redirected back to the LYS hub instead of the homescreen.

A quick fix is acceptable for the MVP, while we figure out better architecture in the task list to support it properly. A potential quick fix is to add a short lived cookie when tasks are initiated from the "essential tasks" sidebar. Then, when tasks are completed, check for the presence of this cookie, and if it exists, redirect back to the LYS hub.

**Comment by chihsuan** [comment]
P2 here pdibGW-38R-p2 before moving forward
