### ISSUE TITLE
[Launch Your Store] Non-native emojis displayed on LYS congrats screen

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#47191]
"Twemoji" appears to be rendered on the congrats screen instead of native system emoji. This can be jarring at first for users more accustomed to seeing their system's emoji style.

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/7fe08ae5-ef80-4d18-b8e1-6442539347a2)

**Comment by rjchow** [comment]
I believe it's showing the system's native emojis - is the report asking for the opposite? To show the "standard" Apple emojis?

This is what's rendered on my MacOS / Firefox:

![Image](https://github.com/woocommerce/woocommerce/assets/27843274/8582a0ce-23b3-4714-b500-cf20128991b8)


And this is the source code:

https://github.com/woocommerce/woocommerce/blob/fbcdb78d1807846f2012e3a02c70825d6cbc6259/packages/js/customer-effort-score/src/components/customer-feedback-simple/customer-feedback-simple.tsx#L33-L64

**Comment by rjchow** [comment]
To be 100% sure that it's not because of a font customisation issue (i.e user has customised the default font), we can also apply this css to the survey buttons:

`{
    font-family: Apple Color Emoji, "Segoe UI Emoji", "Noto Color Emoji";
}
`

From: https://fullystacked.net/using-emoji-on-the-web/

**Comment by chihsuan** [comment]
> I believe it's showing the system's native emojis - is the report asking for the opposite? To show the "standard" Apple emojis?
> 
> This is what's rendered on my MacOS / Firefox:
> 
> ![Image](https://private-user-images.githubusercontent.com/27843274/328739510-8582a0ce-23b3-4714-b500-cf20128991b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDg3NjQsIm5iZiI6MTcxNTE0ODQ2NCwicGF0aCI6Ii8yNzg0MzI3NC8zMjg3Mzk1MTAtODU4MmEwY2UtMjNiMy00NzE0LWI1MDAtY2YyMDEyODk5MWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2MDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjgxZDRhZTYyMmUxYmIwOTY4MjA2NDg4ZTZiMzlkN2MxMzdhZWQ1M2JlODhkYjYwZTYwNWEyOWZiYjFjODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PDucCqz_GMDzmtvOZW194fQcd3AIMVHOEiS4hRipcWs)
> 

I can confirm that. I'm seeing the same on my Mac. I tried with Chrome, Firefox, and Safari and they all show the same emojis.

**Comment by adrianduffell** [comment]
Thanks for testing this @chihsuan and @rjchow!

Sorry for the bother, It looks to be related to my OS (Monterey). I'm not able to reproduce it in Sonoma, Ventura, or WIndows 11. Since Monterey is a few years old now, I'll close this out.

## macOS Sonoma

<img width="1792" alt="emoji  sonoma" src="https://github.com/woocommerce/woocommerce/assets/9312929/d01c2944-0d84-446c-ad70-9a3237d61ff3">


## macOS Ventura

<img width="1792" alt="emoji ventura" src="https://github.com/woocommerce/woocommerce/assets/9312929/9452789c-1ec3-4070-a01a-7b84c484f302">

## Windows 11

<img width="1792" alt="emoji windows 11" src="https://github.com/woocommerce/woocommerce/assets/9312929/265c79c8-6ea5-4187-95ff-8b1e944451b0">

## macOS Monterey

<img width="1792" alt="emoji monterey" src="https://github.com/woocommerce/woocommerce/assets/9312929/24745f06-c78a-4c7a-8870-99b1562be101">
