### ISSUE TITLE
Remove generic incompatibility notices

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#47192]
**Description:** This generic notice was added as a preventive measure, considering that we cannot auto-identify if extensions are incompatible, except for payment extensions. However, this might prevent users from adopting the block-based experience, even if they aren't using incompatible extensions, and extension developers had plenty of time to enable the incompatibility flag. The block-based experience has been the default since November. Therefore, we think it's time to remove the generic notice. 

![Screenshot on 2024-05-06 at 18-32-38](https://github.com/woocommerce/woocommerce/assets/3380168/695f36c9-3f04-4b23-a207-f09936a6a91b)

**Acceptance criteria:**
- [ ] Remove generic notice from the Cart page/template when the store doesn't have incompatible extensions
- [ ] Remove generic notice from the Checkout page/template when the store doesn't have incompatible extensions

**Comment by pmcpinto** [comment]
@ralucaStan can we include this in the current cycle? Assuming it's a quick change.

**Comment by ralucaStan** [comment]
sure thing! I added an estimate of 1

**Comment by pmcpinto** [comment]
Thanks. I included it in the backlog column.
