### ISSUE TITLE
Wordpress you're not allowed in order page

### ISSUE THREAD

**Issue by Vishalini2112** [woothemes/woocommerce#47204]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

while i am editing the woocommerce order page its shows you're not allowed error.

### Expected behavior

need to edit the order ssection

### Actual behavior

need to edit

### Steps to reproduce

order page
edit
change order status 
update

### WordPress Environment

woocommerce >> status 

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @Vishalini2112,

Thanks for your report. Are you able to reproduce this issue when other plugins are deactivated? Are you using a default theme or Storefront?

Also, can you please reply and include your system status report? You can obtain this by visiting WooCommerce > Status and then selecting "Get system report" and then selecting "Copy for support".
