### ISSUE TITLE
Performance issue with SQL query in large wp_wc_orders_meta table

### ISSUE THREAD

**Issue by rafaljosko** [woothemes/woocommerce#47212]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When executing the SQL query SELECT DISTINCT meta_key FROM wp_wc_orders_meta WHERE meta_key NOT LIKE '\\_%' ORDER BY meta_key ASC LIMIT 30, there is a significant slowdown in loading orders, especially noticeable when the wp_wc_orders_meta table is of substantial size. This impacts the performance of the WooCommerce admin order page, causing delays and increasing load times. The issue becomes particularly severe in our environment, where we have approximately 60,000 orders in the store, highlighting how the query's performance degrades with larger data volumes.  

### Expected behavior

The expected behavior is that the query executes efficiently without causing a substantial delay, regardless of the size of the wp_wc_orders_meta table.

### Actual behavior

The actual behavior is a dramatic slowdown in the admin order page when this query is run, especially as the size of the wp_wc_orders_meta table increases. This affects the usability and responsiveness of the WooCommerce admin panel.

### Steps to reproduce

Go to WooCommerce admin panel.
Navigate to the Orders page, and edit orders
Observe the slowdown when the page loads, which executes the mentioned query.
The issue is exacerbated as the size of the wp_wc_orders_meta table increases.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.18
PHP Post Max Size: 512 MB
PHP Time Limit: 180
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1w

wp_wc_orders_meta: Dane: 1653.98MB + Indeks: 1074.97MB + Silnik InnoDB

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @rafaljosko!

Thanks for reaching out. I'm sorry you're having trouble with the order edit screen.
We are aware of this bug and have implemented a couple of fixes for this. One will go out with 8.9.0 (https://github.com/woocommerce/woocommerce/pull/46476) and then we iterated on that fix for 9.0.0 too (https://github.com/woocommerce/woocommerce/pull/46985).

So far, we've found that those changes address the underlying performance issue. We have a beta for 8.9 already available in case you want to give that a try: https://developer.woocommerce.com/2024/04/29/woocommerce-8-9-pre-release-updates/.

I'm going to close this issue, but please do re-open if you're still having trouble.

**Comment by OllieJones** [comment]
I've got an interim fix here. Same query as will roll in 9.0.0. I believe. https://www.plumislandmedia.net/wordpress-plugins/fast-woo-order-lookup/
