### ISSUE TITLE
Update 'Template structure & Overriding templates via a theme' docs to account for block themes

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#47218]
WooCommerce docs have a page named [_Template structure & Overriding templates via a theme_](https://woocommerce.com/document/template-structure/), which currently is only relevant for classic themes. However, nowhere on the page we mention that. It would be nice to update this documentation page to account for both, classic and block themes.

**Comment by Brianmitchtay** [comment]
This page also exists in the developer documentation site which is created from the markdown files at https://github.com/woocommerce/woocommerce/blob/trunk/docs/theme-development/template-structure.md

It would be great for the developer doc to get any improvements that the merchant docs get. Happy to collaborate on this. 👍

**Comment by Aljullu** [comment]
If https://github.com/woocommerce/woocommerce/pull/48247 gets accepted, I think we could add a link to those new docs from that page and that should be enough, no? In block themes the Site Editor is available so merchants are less likely to need to manage templates directly in the filesystem, so probably no need to get too much in detail in that specific page, simply saying "things are different in block themes, please check out this other document" and with a link to the block theming docs from #48247. How does it sound?

**Comment by Brianmitchtay** [comment]
> probably no need to get too much in detail in that specific page, simply saying "things are different in block themes, please check out this other document" and with a link to the block theming docs from #48247. How does it sound?

I think that sounds good, although am I understanding correctly that for the moment the new info being added in #48247 won't be added to the dev docs site at [developer.woocommerce.com/docs](http://developer.woocommerce.com/docs)?

Long term IMO it'd be better to send people to the developer docs than directly to Github, just so they land in a place where it's easy to navigate to other information. But I imagine that's on your radar and you'll check in with the Dev Advocacy team to get any information added to the dev docs. cc: @JacklynBiggin just to put this on your radar.

**Comment by Aljullu** [comment]
Thanks for the feedback, @Brianmitchtay! I just updated the [_Template structure & Overriding templates via a theme_ document](https://woocommerce.com/document/template-structure/) with a link to the _Theming_ docs for block themes. We can keep iterating on these docs to improve them, but at least now there is a _Note_ mentioning block themes in that page. :slightly_smiling_face: 

> I think that sounds good, although am I understanding correctly that for the moment the new info being added in https://github.com/woocommerce/woocommerce/pull/48247 won't be added to the dev docs site at [developer.woocommerce.com/docs](http://developer.woocommerce.com/docs)?

That's correct, currently WooCommerce Blocks docs in the repo don't show up in developer.woocommerce.com/docs, but that's something that will be fixed in the future.

> Long term IMO it'd be better to send people to the developer docs than directly to Github, just so they land in a place where it's easy to navigate to other information.

100% agree.
