### ISSUE TITLE
Clean up unused CSS imports from 'wordpress-components' dependency

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#47210]
During the migration of cart and checkout base components to Ariakit we left behind some imports of css from the 'wordpress-components' alias.

This applies to the new Button and Combobox components.

This task is to go back for each component and remove those imports and test it to make sure there are no style regressions or issues.

You can determine which imports are from the old aliased version because they'll be called `wordpress-components` in the import path not `@wordpress/components`. 

```[tasklist]
### Tasks
- [x] Remove old scss imports from Button
- [x] ~Remove old scss imports from Combobox~
```

**Comment by opr** [comment]
Since we didn't remove the combobox and this will be addressed in a followup, I propose we remove `Remove old scss imports from Combobox` from the task list

**Comment by samueljseay** [comment]
Update:

1. We can remove our wc Combobox component now and I have a PR up for that: https://github.com/woocommerce/woocommerce/issues/46357

2. With that we can also remove any scss styles imported under the `wordpress-components` (except for FormTokenField styles which we still need at the moment). but I just checked this now, there is only one reference remaining, that would be to the combobox control styles. We will just need to test that the handful of styles from that component do not target any classes we have remaining in our new native select implementation.
