### ISSUE TITLE
Add the "optional" config option to the CI config for jobs

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#47223]
Add an `optional` property to `config.ci` for lint and test job types in package.json.

**Comment by jonathansadowski** [comment]
Hi @adimoldovan. This looks like it might be similar to https://github.com/woocommerce/woocommerce/issues/45097. If it's the same, can we close this in favor of that one? If not, can we add some more details to this issue?

**Comment by adimoldovan** [comment]
Hi @jonathansadowski, it's not the same, I want to split the work in 2 parts, one for `ci-jobs` util and one for `ci.yml`. I was planning on adding this info later on.
