### ISSUE TITLE
Daily Smoke Tests: Performance tests failing consistently

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#47232]
The k6 performance tests have been failing consistently on our daily smoke test runs for some time.  My suspicion is that the environment we're testing against with that run needs a thorough cleanup/fixup.

Here's an example failure: https://github.com/woocommerce/woocommerce/actions/runs/8979233510/job/24661054199

**Comment by adimoldovan** [comment]
This was already fixed.
