### ISSUE TITLE
Allow running entire suite of `ci.yml` via label addition.

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#47234]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The tests in `ci.yml` will attempt to detect which portion of the suite should be run based on the projects that are touched. The entire suite is also run if there's a change to `package.json`, but sometimes it's desirable to run the entire set of tests without changing `package.json.

One approach might be to allow the entire suite to be triggered via the addition of a label (which can then optionally be removed by the workflow, so that future changes to the PR don't automatically trigger the entire suite unintentionally).

**Comment by adimoldovan** [comment]
This can be done now via the `On demand` workflow. Closing.
