### ISSUE TITLE
Daily Smoke Tests: Plugin tests should only run a subset of tests

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#47233]
Our daily smoke tests run the e2e suite against WC with a few different plugins installed:
- Gutenberg
- Gutenberg nightly
- WooPayments
- WooCommerce Shipping & Tax
- WooCommerce Paypal Payments

The trouble is that some of our e2e tests assume that they're running against a clean WC install and so having one of these plugins installed may break things.  For example, we have some e2e tests in core that check a payment flow assuming that the only payment method enabled will be COD -- that's not the case when WooPayments or WooCommerce Paypal Payments are installed.

We've floated the idea of creating a subset of e2e tests for running against these plugins.  So we'd need to identify a list for that.  Addiontally, these runs aren't currently sharded, which may help improbe the reliability.

**Comment by adimoldovan** [comment]
This was done with https://github.com/woocommerce/woocommerce/pull/48715
