### ISSUE TITLE
The postmeta is growing rapidly by auto deleted after cancel_sale_schedule.

### ISSUE THREAD

**Issue by martinym28** [woothemes/woocommerce#47255]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The postmeta is growing rapidly by auto deleted after cancel_sale_schedule.
Any sale_schedule or cancel_sale_schedule be operated repeatedly, and the postmeta auto deleted repeatedly.
How to keep and set first time of _sale_price_dates_from or _sale_price_dates_to = empty for update without delete?

### Expected behavior

stop delete _sale_price_dates_from or _sale_price_dates_to

### Actual behavior

keep and update _sale_price_dates_from or _sale_price_dates_to

### Steps to reproduce

edit and update product page

### WordPress Environment

All are the latest versions

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @martinym28,

Thanks for your report. Can you please confirm that you still experience this issue when only the WooCommerce plugin is active and that you're using either a default WordPress theme or Storefront?

Also, can you please include your system status report? You can obtain this by visiting WooCommerce > Status and then selecting "Get system report" and then "Copy for support".

Is there a specific list of steps that we could follow to reproduce this issue?
