### ISSUE TITLE
Refactor: Checkout Pickup Options block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#47258]
### Describe the solution you'd like

In #47173, we renamed `Pickup options` to `Pickup locations`. However, we did not rename the corresponding component from `checkout-pickup-options-block` to `checkout-pickup-locations-block`, as such a change might break various things. I briefly looked into this and noticed that after adjusting the component's name, all e2e tests started failing. Therefore, I separated this issue from #47173.

**Comment by opr** [comment]
I don't think we should do this. Extensions adding inner blocks to the Cart/Checkout would use the block name to set the parent (An example is in https://github.com/woocommerce/wceu23-shipping-workshop-final/blob/main/src/js/shipping-workshop-block/block.json#L14) - if this block name changes the plugin would stop working. This change would break back compatibility.

Based on this, I'll close the issue, but please reopen it if you disagree, or have some proposals on how we can do this change while maintaining backward compatibility.

Thanks Niels!

**Comment by nielslange** [comment]
That's a good point, @opr. Let's keep this issue closed. And thanks for adding more context regarding backwards compatibility.
