### ISSUE TITLE
Activate skipped translation in Checkout block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#47260]
### Describe the solution you'd like

In #47083, we've updated the place order button label in a way that it allows displaying the total cart price. Due to that change, one of the translations within an e2e tests started failing. This was expected, as the corresponding string is not available on https://translate.wordpress.org/projects/wp-plugins/woocommerce/ yet. Once WooCommerce 9.0.0 had been released and the string `'Place Order · %s'` had been translated, the following part can be activated again:

https://github.com/woocommerce/woocommerce/blob/2296e45d3386f2e85ff0e0ceaa93e1661b617677/plugins/woocommerce-blocks/tests/e2e/tests/cart/cart-checkout-block-translations.shopper.block_theme.side_effects.spec.ts#L105-L107

**Comment by ralucaStan** [comment]
closing as we reverted that PR
