### ISSUE TITLE
Woo Commerce is no longer sending Customer Notes

### ISSUE THREAD

**Issue by MIItineraries** [woothemes/woocommerce#47286]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Customer Notes are no longer sending from the Edit Order page.  

### Expected behavior

I usually edit the note in Settings: emails: Customer Note and save it.  
I then usually go to Orders: Edit Order: Add Note: Customer Note: Add.  The note usually sends and the notification shows up in the Order Notes catalogue.

### Actual behavior

I follow all of the usual steps and when I hit the Add (Customer Note) button, nothing happens.  The Customer Note does not send.

### Steps to reproduce

[Screen Recording 2024-05-08 at 8.51.57 AM.mov.zip](https://github.com/woocommerce/woocommerce/files/15251585/Screen.Recording.2024-05-08.at.8.51.57.AM.mov.zip)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://miitineraries.com
Site address (URL): https://miitineraries.com
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.18
PHP Post Max Size: 516 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: _MAK_
Total Database Size: 12.68MB
Database Data Size: 9.77MB
Database Index Size: 2.91MB
_MAK_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
_MAK_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_MAK_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_MAK_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_actionscheduler_actions: Data: 0.09MB + Index: 0.04MB + Engine MyISAM
_MAK_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_MAK_actionscheduler_logs: Data: 0.10MB + Index: 0.08MB + Engine MyISAM
_MAK_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_MAK_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_MAK_ff_scheduled_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_fluentform_entry_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_fluentform_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_fluentform_form_analytics: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_fluentform_form_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_fluentform_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_fluentform_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_fluentform_submission_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
_MAK_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_MAK_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_MAK_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
_MAK_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_MAK_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
_MAK_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_MAK_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_MAK_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
_MAK_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_options: Data: 3.70MB + Index: 0.11MB + Engine MyISAM
_MAK_postmeta: Data: 0.40MB + Index: 0.08MB + Engine MyISAM
_MAK_posts: Data: 0.92MB + Index: 0.04MB + Engine MyISAM
_MAK_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_MAK_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_MAK_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_usermeta: Data: 0.09MB + Index: 0.03MB + Engine MyISAM
_MAK_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_MAK_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
_MAK_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
_MAK_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
_MAK_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_MAK_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_MAK_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_MAK_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
_MAK_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_MAK_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_MAK_yoast_indexable: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
_MAK_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_MAK_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_MAK_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_MAK_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 52
custom_css: 1
mailpoet_page: 1
nav_menu_item: 8
oembed_cache: 1
page: 11
post: 9
product: 12
revision: 224
shop_order: 13
shop_order_refund: 5
wapf_product: 2
wp_global_styles: 1
wp_navigation: 1
wpforms: 1
yaymail_template: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Google Listings and Ads: by WooCommerce – 2.6.9
Jetpack: by Automattic – 13.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.3

WooCommerce Stripe Gateway: by WooCommerce – 8.2.0
WooPayments: by Automattic – 7.5.3
WooCommerce Shipping & Tax: by WooCommerce – 2.5.6
WooCommerce: by Automattic – 8.8.3
Yoast SEO: by Team Yoast – 22.6
Smush: by WPMU DEV – 3.16.2
YayMail - WooCommerce Email Customizer: by YayCommerce – 3.5.0

### Inactive Plugins (1) ###

Advanced Product Fields Pro for WooCommerce: by StudioWombat – 2.0.1

### Must Use Plugins (2) ###

Endurance Page Cache: by Mike Hansen – 2.2.1
SSO: by Garth Mortensen
Mike Hansen – 0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 KB

### WC Pages ###

Shop base: #160 - /shop/
Cart: #161 - /cart/
Checkout: #162 - /checkout/
My account: #163 - /my-account/
Terms and conditions: #164 - /terms-and-conditions/

### Theme ###

Name: Twenty Seventeen
Version: 3.4 (update to version 3.6 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.5.3
Connected to WPCOM: Yes
WPCOM Blog ID: 193299069
Account ID: acct_1KJQsg2HO3AUNCBQ
Payment Gateway: Disabled
Test Mode: Disabled
Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-08 22:09:18 -07:00
Options: ✔
Notes: 154
Onboarding: completed

### Action Scheduler ###

Complete: 211
Oldest: 2024-04-07 16:08:32 -0700
Newest: 2024-05-08 05:54:06 -0700

Failed: 9
Oldest: 2023-02-14 15:07:13 -0800
Newest: 2023-06-01 04:03:45 -0700

Pending: 4
Oldest: 2024-05-08 17:54:06 -0700
Newest: 2024-05-08 23:39:05 -0700

### Status report information ###

Generated at: 2024-05-08 08:27:10 -07:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by CacheMeOwside** [comment]
Hey @MIItineraries, thanks for your report! I wasn't able to recreate this issue on my test site with the same version of WordPress and WooCommerce installed as yours, and with the "Twenty Seventeen" theme activated.
Additionally, in the uploaded video, I noticed that you had not entered any text in the `Add Note` text area before selecting `Note to Customer`, and clicking on `Add`. So, there was nothing to be sent or saved in the Order notes section.

Here is a video of my test:
https://github.com/woocommerce/woocommerce/assets/64858136/31424c96-f0b7-431f-b862-ef6e806b41cc

Could you please test by deactivating all other plugins other than WooCommerce as mentioned in the `Isolating the problem` checklist in the issue request? You should be able to add a note after you enter some text in the text field.
