### ISSUE TITLE
Helcim plugin Payments are not recognizedare not 

### ISSUE THREAD

**Issue by Zinfandel22** [woothemes/woocommerce#47299]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When plugin is configured, the payments module is not recognized

### Expected behavior

Helcim payments should be recognized.

### Actual behavior

Payements component of the checkout process is not recognized.
Wordpress 6.5.3
Woocommerce 8.8.3
Helcim 4.0.3

### Steps to reproduce

Install wordpress, WooCommerce and Helcim plugin
Configure a product and test the checkout process.
On payment see error message
"There are no payment methods available. This may be an error on our side. Please contact us if you need any help placing your order.'

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://satoricellars.com
Site address (URL): https://satoricellars.com
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.18
PHP Post Max Size: 516 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: wp_0p4az8_
Total Database Size: 38.84MB
Database Data Size: 32.59MB
Database Index Size: 6.25MB
wp_0p4az8_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_0p4az8_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_0p4az8_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0p4az8_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0p4az8_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
staging_wp_0p4az8_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
staging_wp_0p4az8_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_nextend2_image_storage: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_nextend2_section_storage: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_nextend2_smartslider3_slides: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_nfd_data_event_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
staging_wp_0p4az8_options: Data: 3.73MB + Index: 0.04MB + Engine MyISAM
staging_wp_0p4az8_postmeta: Data: 1.96MB + Index: 0.19MB + Engine MyISAM
staging_wp_0p4az8_posts: Data: 1.71MB + Index: 0.11MB + Engine MyISAM
staging_wp_0p4az8_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
staging_wp_0p4az8_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
staging_wp_0p4az8_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
staging_wp_0p4az8_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
staging_wp_0p4az8_revslider_css: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_revslider_css_bkp: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_sliders_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
staging_wp_0p4az8_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_usermeta: Data: 0.17MB + Index: 0.02MB + Engine MyISAM
staging_wp_0p4az8_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
staging_wp_0p4az8_yoast_indexable: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
staging_wp_0p4az8_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
staging_wp_0p4az8_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
staging_wp_0p4az8_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
staging_wp_0p4az8_yoast_seo_links: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_0p4az8_actionscheduler_actions: Data: 1.52MB + Index: 0.92MB + Engine InnoDB
wp_0p4az8_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_actionscheduler_logs: Data: 0.50MB + Index: 0.41MB + Engine InnoDB
wp_0p4az8_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_jetpack_sync_queue: Data: 10.45MB + Index: 1.16MB + Engine InnoDB
wp_0p4az8_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_nextend2_image_storage: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_nextend2_section_storage: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_nextend2_smartslider3_slides: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_nfd_data_event_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0p4az8_options: Data: 5.31MB + Index: 0.17MB + Engine MyISAM
wp_0p4az8_postmeta: Data: 2.83MB + Index: 0.62MB + Engine MyISAM
wp_0p4az8_posts: Data: 1.92MB + Index: 0.22MB + Engine MyISAM
wp_0p4az8_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_0p4az8_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_0p4az8_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_0p4az8_revslider_css: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_revslider_css_bkp: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_sliders_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_0p4az8_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_0p4az8_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_usermeta: Data: 0.17MB + Index: 0.02MB + Engine MyISAM
wp_0p4az8_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_0p4az8_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_0p4az8_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0p4az8_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_0p4az8_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_0p4az8_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_0p4az8_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_0p4az8_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_0p4az8_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0p4az8_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_yoast_indexable: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_0p4az8_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_0p4az8_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0p4az8_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0p4az8_yoast_seo_links: Data: 0.16MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

attachment: 835
carousels: 32
custom_css: 1
customize_changeset: 9
masonry-gallery: 9
nav_menu_item: 30
oembed_cache: 1
page: 65
portfolio-item: 72
post: 9
product: 10
product_variation: 85
revision: 301
shop_order: 3
slides: 36
tablepress_table: 2
testimonials: 7
upcp_catalog: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

The Bluehost Plugin: by Bluehost – 3.10.0
Classic Editor: by WordPress Contributors – 1.6.3
Edge CPT: by Edge Themes – 2.1
Edge Instagram Feed: by Edge Themes – 2.1.1
Helcim Commerce for WooCommerce: by Helcim Inc. – 4.0.3
Jetpack Boost: by Automattic - Jetpack Site Speed team – 3.2.2
Jetpack: by Automattic – 13.4
WPBakery Page Builder: by Michael M - WPBakery.com – 7.6
Meta Tag Manager: by Pixelite – 3.1
Printful Integration for WooCommerce: by Printful – 2.2.7
Redirection: by John Godley – 5.4.2
Slider Revolution: by ThemePunch – 6.5.19
Smart Slider 3: by Nextend – 3.5.1.23
TablePress Extension: Cell Highlighting: by Tobias Bäthge – 1.0
TablePress Extension: Row Highlighting: by Tobias Bäthge – 1.0
TablePress: by Tobias Bäthge – 2.3.1
W3 Total Cache: by BoldGrid – 2.7.2
WooCommerce.com Update Manager: by Automattic – 1.0.2
WooCommerce: by Automattic – 8.8.3
Yoast SEO: by Team Yoast – 22.6

### Inactive Plugins (3) ###

WooCommerce Amazon Pay: by Amazon Pay – 2.5.1
WooCommerce Legacy REST API: by WooCommerce – 1.0.1
WooPayments: by Automattic – 7.6.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Endurance Page Cache: by Mike Hansen – 2.2.1
SSO: by Garth Mortensen
Mike Hansen – 0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 MB

### WC Pages ###

Shop base: #8005 - /shop/
Cart: #8006 - /cart/
Checkout: #8007 - /checkout/
My account: #8008 - /my-account/
Terms and conditions: #8009 - /refund_returns/

### Theme ###

Name: Dorian
Version: 2.2
Author URL: https://themeforest.net/user/edge-themes
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: dorianwp/woocommerce/cart/cart-shipping.php version 3.6.0 is out of date. The core version is 8.8.0
dorianwp/woocommerce/cart/cart-totals.php
dorianwp/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.9.0
dorianwp/woocommerce/cart/shipping-calculator.php version 4.0.0 is out of date. The core version is 7.0.1
dorianwp/woocommerce/content-product.php
dorianwp/woocommerce/content-single-product.php
dorianwp/woocommerce/content-widget-product.php
dorianwp/woocommerce/global/quantity-input.php version 4.0.0 is out of date. The core version is 7.8.0
dorianwp/woocommerce/loop/pagination.php
dorianwp/woocommerce/product-searchform.php version 3.3.0 is out of date. The core version is 7.0.1
dorianwp/woocommerce/single-product/add-to-cart/external.php version 3.4.0 is out of date. The core version is 7.0.1
dorianwp/woocommerce/single-product/add-to-cart/grouped.php version 4.8.0 is out of date. The core version is 7.0.1
dorianwp/woocommerce/single-product/add-to-cart/simple.php version 3.4.0 is out of date. The core version is 7.0.1
dorianwp/woocommerce/single-product/meta.php
dorianwp/woocommerce/single-product/product-image.php version 3.5.1 is out of date. The core version is 7.8.0
dorianwp/woocommerce/single-product/related.php
dorianwp/woocommerce/single-product/tabs/tabs.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-09 16:00:09 -07:00
Options: ✔
Notes: 58
Onboarding: skipped

### Action Scheduler ###

Complete: 2,274
Oldest: 2024-05-01 16:00:26 +0000
Newest: 2024-05-09 04:35:26 +0000

Failed: 4
Oldest: 2024-05-01 16:02:38 +0000
Newest: 2024-05-09 00:39:18 +0000

Pending: 3
Oldest: 2024-05-09 05:01:43 +0000
Newest: 2024-05-09 16:35:26 +0000

### Status report information ###

Generated at: 2024-05-08 21:38:25 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
if you're using Checkout block (which you most likely are) then you need to have that payment method compatible with it. You need to contact the plugin author to make it compatible.

As a different solution, you can switch back to the old Checkout shortcode

https://woocommerce.com/document/cart-checkout-blocks-status/#section-6
