### ISSUE TITLE
Store API  - AbstractCartRoute uses previous data when calculates the totals

### ISSUE THREAD

**Issue by mynewvk** [woothemes/woocommerce#47296]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have a plugin that adjusts prices based on quantity (tiered pricing table for woocommerce)

We have successfully utilized the "woocommerce_before_calculate_totals" for years to set new prices for cart items.
We pull "quantity" from the cart item, calculate a new price, and set it directly to the WC_Product instance via $cart_item['data'], so WC_Cart_Totals can calculate totals based on the new price.

### Expected behavior

It works perfectly with the old cart and checkout.
However, the new Store API endpoints do not use the latest cart item data, causing a big problem during calculations.

It triggers cart_controller->calculate_totals(), which is fine, but it loads the cart from the session -> calculates prices, and then updates the cart in the session with the new quantity. This means the "woocommerce_before_calculate_totals" hook (and all others during the calculations) uses $cart_item with the previous data.
We get the outdated $cart_item['quantity'] and cannot correctly calculate the new price. I believe this could also affect other plugins.

I hope this makes sense and can be fixed in the subsequent WooCommerce release.

Thank you 

### Actual behavior

So, your logic is the following: 
1. You get a request to update the cart item
2. You load the cart instance from the session (but it does not include updated quantity)
3. You trigger cart_controller->calculate_totals() with the wrong quantity (it works fine for default WooCommerce because  the new cart block actually calculates totals using JS on the frontend; it uses only cart item price, which is not changed)
4. You update the cart with the new quantity and store it in the session.

### Steps to reproduce

Try to use "woocommerce_before_calculate_totals" hook to get cart item quantity

### WordPress Environment

Default WooCommerce setup

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mynewvk** [comment]
<img width="961" alt="image" src="https://github.com/woocommerce/woocommerce/assets/3198553/f8fd0b7e-6ae7-429d-a2b3-cc2aad26ebe9">

**Comment by mynewvk** [comment]
<img width="871" alt="image" src="https://github.com/woocommerce/woocommerce/assets/3198553/329b123c-8506-46d1-a863-0a81e751e012">
<img width="1327" alt="image" src="https://github.com/woocommerce/woocommerce/assets/3198553/3f0c137d-fdb6-46f4-86ed-2902f954ad87">

**Comment by opr** [comment]
Hi @mynewvk thanks for posting this, I can reproduce what you're seeing however I haven't had time to dive deep into the Store API to check the reasons _why_.

@senadir could you share some thoughts on why we calculate totals at the _start_ of the request, then again before the end? Could we perhaps omit the first one if we know the totals are going to be recalculated at the end of the request?

**Comment by senadir** [comment]
Thanks for highlighting this, while it's true it's running twice. This only happens for routes that update the cart, the first calculation ensures whatever cart is loaded from session has the correct totals, runs the update, then calculates totals again.

I can also see that cart block and checkout block do the same thing, run twice, although they seem to apply changes before running twice.

Anything specific you have concerns about here that's causing an issue for you @mynewvk ?

**Comment by mynewvk** [comment]
Thanks for getting back on this.

If this behavior is normal, why is it not the case for the regular cart?
Why can't you just update the cart totals once with the new arguments?

"the first calculation ensures whatever cart is loaded from the session has the correct totals." - Why is it important?
 
This is the issue for us because our plugin works in the following algorithm:
1. Get the price based on the quantity.
2.  If there is a tiered price for a quantity -> update the cart item price. Otherwise, do not modify anything.

Let's say we have the following tiered pricing:

1 - 9 pieces = Regular price
10+ pieces = 10% discount

If a user changes the quantity from 10 to 9, it will not work correctly:

1. The first iteration will pass the previous cart item quantity (10), and the plugin will modify the cart item price to a 10% discount.
2. The second iteration will get the correct quantity (9), but there is no tiered pricing for this quantity, so it will not change the price. **However, the price was already changed to a 10% discount in the initial "before_calculate_totals" iteration, so the final price will be wrong.**

We technically can redesign our plugin to make it work (saving the original product price to resetting it when there is no tiered pricing), but from our perspective, triggering the "before_calculate_totals" hook twice with different values in one request is an issue that could produce unexpected behavior for other third-party plugins.
This should be also performance inefficient to do the same calculations twice.

**Comment by senadir** [comment]
> If this behavior is normal, why is it not the case for the regular cart?

I cannot speak for the old codebase yet because it predates me, but I find it very normal to have 2 carts depending on when you hook into a request. Calculations will run several times and you code should assume any possible state and work with it.

The old cart does run twice, but with the new cart items in both cases.

> "the first calculation ensures whatever cart is loaded from the session has the correct totals." - Why is it important?

It is important because whatever cart is loaded from session can be dirty or outdated, cart is loaded right now, or after days, and you can't be sure if it's up to date or not. Whoever is hooking before the end of request should be able to conclude that it's safe and up to date.

Instead of saving the original price, I'd opt to fetch the product again instead of relying on `$item['data']`.


For sake of testing, I've thrown this change to our test suite to see what might break.

https://github.com/woocommerce/woocommerce/pull/47544

**Comment by mynewvk** [comment]
Hello @senadir,

Thanks for getting back to me.

Why do you need to ensure that the cart is not "dirty" if you don't interact with the cart at that point? Can it be rechecked with the updated data?

I can imagine a case where a third-party plugin makes heavy calculations on those hooks, for example, requesting an API, so calling it twice might significantly increase the response time.

Yes, I agree that our plugin should work at any state of the cart, but the price in $cart_item['data'] can be different depending on how it is called (via Store API or regular cart) because of double calling :)

I don't think resetting the price if there is no tiered pricing for this quantity is not a good idea because we can break other third-party plugins that may already have changed this price at this point, and we just override it when we don't have to make any price adjustments.

Please let me know if you are willing to fix this. The discussion does not make sense if you do not consider it a bug.

Thank you

**Comment by mikejolley** [comment]
> Why do you need to ensure that the cart is not "dirty" if you don't interact with the cart at that point? Can it be rechecked with the updated data?

The session does not contain everything; it contains a cache of totals and the items in the cart, but when the session is loaded it needs to recalculate.

I guess a real world scenario where that would be needed would be a case where a customer has a cart, and the admin updates the price of some item. When the customer loads a page, they need to have the latest price of said product used for calculations, because the stored cart will be outdated.

In the case of the Store API, to ensure all endpoints return current and updated information, we do an early recalculation. This will happen on all routes that return cart (GET routes included).

It just so happens that some routes (those that POST or update cart data) need to do another calculation after the cart is updated. e.g. updating the product quantity needs to refresh totals.

**So we have two options here;**

1. We leave the logic as-is. It ensures all routes will always return up to date cart data
2. We re-calculate later or conditionally depending on the route. The risk here is that before the update completes and the cart data is recalculated, stale cart data may be visible via other hooks.

@senadir @opr What are your thoughts on the above?

**Comment by opr** [comment]
> The risk here is that before the update completes and the cart data is recalculated, stale cart data may be visible via other hooks.

I think this is an experience we definitely want to avoid, wouldn't we then be deferring the duty to calculate totals on the consumers of those hooks? If so, this would be worse because each hook would have to do it rather than it just happening once.

I prefer leaving it as-is.

**Comment by mynewvk** [comment]
I agree that recalculating the cart from the session makes sense. I just cannot understand why it cannot be made after it gets the updated data, in this case, the new product quantity. Why it should be done twice? 
If there is a risk that the "dirty" cart can be used by other hooks (what hooks?), maybe the first recalculation should already be made with the new quantity data.

In your example, the price will be updated just fine if recalculate totals are done only before sending the response, including new data. 

I can imagine the case when a user has an item in the session with a quantity of 5, and the stock changes to 4.
The update cart request gets a request to update the cart to the quantity of 4 -> It loads the cart from the session -> does the recalculation -> checks that 5 does not satisfy the stock level -> Remove the item from the ca, andrt pushes the notice before it even update the cart item quantity to a valid quantity value.

**Comment by mikejolley** [comment]
"AbstractCartRoute uses previous data" should be "AbstractCartRoute uses current data". The update hasn't happened when the Store API is initialised.

The lifecycle of API call is this:

- Request comes in
- Request is routed to the Store API
- Store API sees that this is a cart route - the cart is loaded (with current session data) so its ready for endpoints to handle.

At this point it may be a simple GET request, in which case the loaded cart data is converted into a response and returned.
For POST requests at this point we validate the request, update the data, and recalculate totals.

Some endpoints need data before we can validate the request. Take coupon routes for example; to apply a coupon you need to already know the current totals so validation works.

The alternative would be to defer the initial calculation and make every route responsible for calculating totals. Some routes might need to calculate twice. This seems more error prone. The current system ensures all routes get the same data and have a valid session in place.

@senadir what do you think about this? Do you anticipate other errors from deferring the initial calculation, or should we just ensure developers code more defensively?

**Comment by mikejolley** [comment]
I did some testing within `AbstractCartRoute` and between the initial calculate and the generation of the response there are no hooks being called, so we could potentially move the calculation into each endpoint class so long as it happens before the cart response is generated. I will do further testing to see if this is viable or causes other issues.

**Comment by senadir** [comment]
I also did some testing to keep cart hydration but skip the totals calculation part and nothing seems to be broken.

> @senadir what do you think about this? Do you anticipate other errors from deferring the initial calculation, or should we just ensure developers code more defensively?

Given this is the current behavior in legacy cart, how does that work? it seems to e safe anyway?
