### ISSUE TITLE
Add loading state to save button

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#47305]
The Site Visibility save button takes a few seconds to process but doesn't give an indication it's been pressed. Is it possible to add a loading state animation on it to let users know it's processing?

https://github.com/woocommerce/woocommerce/assets/9312929/fff5bfa9-de7a-4d9d-bc81-ee0f7286921b

**Comment by moon0326** [comment]
It's tricky to add a loading state to the button as it's not a React component. How about we disable it once it's clicked? I think it's reasonable as it is a classic form submission with a page refresh.

![Image](https://github.com/woocommerce/woocommerce/assets/4723145/4b8b6e80-65e8-411e-ad96-8476b78a65f8)

**Comment by psealock** [comment]
The behaviour of the Save button is a UX inherent to the all Settings screens. I ran into this type or issue when revamping Shipping Settings and creating a departure just for Site Visibility will create a disconnect between the rest of the settings pages. My opinion is to leave this as is.

**Comment by adrianduffell** [comment]
> It's tricky to add a loading state to the button as it's not a React component. How about we disable it once it's clicked? I think it's reasonable as it is a classic form submission with a page refresh.

@moon0326 Good points, yeah it looks like the disabled pattern is consistent with classic WP UI. How about we also add the spinner next to it like as done in the products editor? I was able to hack it in the mockup below with `<span class="spinner is-active"></span>` and a few overriding styles: `float: none; margin: -4px 8px 0` . 



### Mockup of spinner
https://github.com/woocommerce/woocommerce/assets/9312929/24a85308-940e-4d42-a25a-74ccae702a2a


### Spinner next to the update button
https://github.com/woocommerce/woocommerce/assets/9312929/5399df75-7245-4095-b2ac-c3ee345a69cf

**Comment by adrianduffell** [comment]
> The behaviour of the Save button is a UX inherent to the all Settings screens. I ran into this type or issue when revamping Shipping Settings and creating a departure just for Site Visibility will create a disconnect between the rest of the settings pages. My opinion is to leave this as is.

@psealock That's a good insight, thanks! Rather than leave as-is, how about we bring this to all of the settings to try to improve the experience across the board? If we use the disabled + spinner pattern above, it would look like:

<img width="1792" alt="settings spinner" src="https://github.com/woocommerce/woocommerce/assets/9312929/0f70e424-faaa-4e46-9c2b-9079939ac89a">

**Comment by moon0326** [comment]
@adrianduffell I like it! The change should be pretty straightforward. I'm wondering if we should check with Veronica and proton team as well?

**Comment by adrianduffell** [comment]
> I'm wondering if we should check with Veronica and proton team as well?

Good idea, @verofasulo and @woocommerce/proton what are your thoughts on this spinner concept for the settings screen?

I've aimed to find a classic WordPress component for this as it's tricky to place a modern loading state here. WordPress' own classic settings screens don't have a loading state so I used the spinner found on the classic product / post editor.

**Comment by naman03malhotra** [comment]
>what are your thoughts on this spinner concept for the settings screen?
I've aimed to find a classic WordPress component for this as it's tricky to place a modern loading state here.

I really like it. I think it would improve the user's perceived experience while saving the settings.

Question:

Do you only plan to apply it for the site visibility tab or the whole settings section?

**Comment by adrianduffell** [comment]
> Do you only plan to apply it for the site visibility tab or the whole settings section?

@naman03malhotra The plan would be for the whole settings section -- whenever a tab has a "Save changes" button.

**Comment by naman03malhotra** [comment]
Sounds good @adrianduffell, go for it! Though, maybe we can a quick input from the design as well if they have something to add here cc @j111q

**Comment by adrianduffell** [comment]
I think it would be worth revisiting whether we can apply a modern loading state like found in the gutenberg components. I believe this is done there by [applying an .is-busy class and using a CSS animation](https://github.com/WordPress/gutenberg/blob/28847b04ce121fd333ee364a6525d2ca7f969e10/packages/components/src/button/style.scss#L256). 

https://github.com/woocommerce/woocommerce/assets/9312929/81f43c22-ad59-4c57-90b6-cfb6e7741d6b

**Comment by ilyasfoo** [comment]
@adrianduffell I've attempted to use the `is-busy` animation: https://github.com/woocommerce/woocommerce/pull/47626. It's hack-ish since I hitchhike on Gutenberg's CSS without using its components. It has a little bit of risk of breaking in case of Gutenberg component changes, but I think it's not a too big of a risk.
