### ISSUE TITLE
Different handling of optional states between Shortcode and Block Checkouts

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#47317]
Countries who declare their state hidden and optional, but still have states, will show up in Checkout shortcode but are not visible in Checkout block. A prime example is Germany.

https://github.com/woocommerce/woocommerce//blob/a66075ee115c3d699c37240d7a597fa64ed175c5/plugins/woocommerce/includes/class-wc-countries.php#L1048-L1056

### Steps to reproduce

1. Sell to all countries.
2. Navigate to Checkout block, select Germany, see that state field is not visible.
3. Navigate to Checkout shortcode, select Germany, see that state field is visible and optional.

**Comment by ralucaStan** [comment]
@senadir it's not clear to me what experience this ticket is targeting. How is it impacted by  https://github.com/woocommerce/woocommerce/pull/47319?

Could you rewrite the ticket using the issue template for bugs?

**Comment by senadir** [comment]
I don't know which outcome is best, so I'm not sure what should be expected behavior, just that we have 2 behaviors here.

When talking to Mike, him and I agreed that hiding the states regardless should be the preferred outcome, but we won't touch shortcode Checkout to fix this.

**Comment by senadir** [comment]
Added a won't fix label.

**Comment by pmcpinto** [comment]
To recap, we currently don't show the state field for countries where the state is optional and don't offer an easy way for users to display this field, correct?

**Comment by senadir** [comment]
To be exact, if states is marked as "hidden", we don't show it.
In shortcode Checkout, if state is marked as "hidden" but still had a predefined list of states, it will be shown regardless.

There isn't any cases of this so far, only Germany, and I already fixed it.

A way for a merchant to show it is to mark the state as visible,

```php
add_filter('woocommerce_get_country_locale', function( $locale ) {
$locale['DE']['state']['hidden'] = false;
}, 10, 1 );
```

It seems this might only happen by mistake that you end up adding states to a country but not enable the state button.

**Comment by pmcpinto** [comment]
Thanks for the clarification. Can we close this one, or is there anything missing?

**Comment by senadir** [comment]
I think we can close it for now, I documented it as a difference between Block and Shortcode
