### ISSUE TITLE
Applying coupon on subscription renewal throws PHP Fatal error:  Uncaught Error: Call to a member function is_coupon_emails_allowed() on null in /wp-content/plugins/woocommerce/includes/class-wc-discounts.php:979

### ISSUE THREAD

**Issue by mslepko** [woothemes/woocommerce#47330]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We are applying custom coupon codes on subscription renewals and due to the is_coupon_emails_allowed function introduced a couple of weeks ago we’ve started to get errors with subscription renewals.

```
2024-05-01T11:01:13+00:00 Notice scheduled action XYZ (subscription payment) failed to finish processing due to the following exception: Call to a member function is_coupon_emails_allowed() on null  
Additional context
{
    "_legacy": true
}

2024-05-01T11:01:13+00:00 Notice action args: subscription_id: XYZ
```

It looks like `WC()->cart` is null in this scenario in https://github.com/woocommerce/woocommerce/blob/release/8.8.0.20/plugins/woocommerce/includes/class-wc-discounts.php#L979 

```
[29-Apr-2024 09:51:25 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_coupon_emails_allowed() on null in /wp-content/plugins/woocommerce/includes/class-wc-discounts.php:979
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/class-wc-discounts.php(1046): WC_Discounts->validate_coupon_allowed_emails(Object(WC_Coupon))
#1 /wp-content/plugins/woocommerce/includes/class-wc-discounts.php(252): WC_Discounts->is_coupon_valid(Object(WC_Coupon))
#2 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1252): WC_Discounts->apply_coupon(Object(WC_Coupon))
#3 /wp-content/themes/my_theme/custom/discount-on-renewal.php(132): WC_Abstract_Order->apply_coupon('renewal_couponXYZ')
```

My custom function is called using this filter
```
add_filter( 'wcs_renewal_order_created', 'apply_discount_on_renewal_order_created', 10, 2 );

function apply_discount_on_renewal_order_created( $renewal_order, $subscription ) {
    $coupon_codes = array( 'renewal_code1', 'renewal_code2', 'renewal_code3');

    $order = new WC_Order( $renewal_order->get_id() );
 
   foreach ( $coupon_codes as $coupon_code ) {
	  $coupon        = new WC_Coupon( $coupon_code ); 
	  $expiry_date = $coupon->get_date_expires();

	  if( $coupon->get_usage_count() < $coupon->get_usage_limit() && (date('Y-m-d') < date('Y-m-d', strtotime($expiry_date)) ) ){
		$order->apply_coupon($coupon_code);
	   }
     }
}
```

I’ve already fixed the issue in my theme and wrapped the code in try/catch block but I’m wondering if this shouldn’t be fixed in WooCommerce code as well as cart is not available it this specific scenarion.

Thanks
Michal

### Expected behavior

Email restricted coupons should be applied on subscription renewals

### Actual behavior

Fatal error is thrown

### Steps to reproduce

Apply an email restricted coupon code on subscription renewals

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://prodog.local
Site address (URL): http://prodog.local
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.4.1 - There is a newer version of WordPress available (6.5.3)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 8.2.10
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider.
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider.

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 10896.83MB
Database Data Size: 5296.99MB
Database Index Size: 5599.84MB

### Status report information ###

Generated at: 2024-05-09 16:01:47 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Changing team, as this seems to have its origin in this recent change (for which Proton doesn't have the same amount of context):

https://github.com/woocommerce/woocommerce/pull/43872

**Comment by wavvves** [comment]
Added `type:refactor `as this is a current code limitation.

@mslepko Thank you for reporting this, we've identified some improvements in our code to ensure this specific use case is viable.

**Comment by wavvves** [comment]
Hi again @mslepko, a fix is underway to be on the next WooCommerce release. In the meantime, and since there's no current ETA for that release, you can try instantiating the Cart object so that the method doesn't fail, so right before applying the coupon on the order add:

```php
WC()->cart = new WC_Cart();
$order->apply_coupon($coupon_code);
```

This will be compatible with the planned fix, but you can remove that line after updating.

**Comment by mslepko** [comment]
thank you @wavvves
