### ISSUE TITLE
Fix and re-enable product editor tests

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#47346]
Some broken e2e tests on product editor were disabled with https://github.com/woocommerce/woocommerce/pull/47268. We should fix and re-enable them.

**Comment by tammullen** [comment]
Specifically this is for `'can create a variation option and publish the product'`

**Comment by adimoldovan** [comment]
This was fixed by https://github.com/woocommerce/woocommerce/pull/48725
