### ISSUE TITLE
Country input captures scroll events on android chrome-based browsers.

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#47358]
This is a follow up to https://github.com/woocommerce/woocommerce/pull/46943 - this bug is not reproducible until that is merged. 

In the PR we found a bug where the touchable area of the country input combobox goes beyond its visual boundary. This video illustrates it a little better.

https://github.com/woocommerce/woocommerce/assets/5656702/4954e28c-3aa9-4475-8a21-841683c0f789

To reproduce:

- On an android device (I used a Samsung S23 ultra) open the store in chrome/brave/MS Edge
- Add an item to the cart and go to checkout.
- Open the country input and scroll down so that the country input moves up the page.
- Try scrolling down the page using the area immediately below the country input.
- The input will scroll, not the page, despite touching outside of the input.

**Comment by ralucaStan** [comment]
This will be closed by https://github.com/woocommerce/woocommerce/issues/47757

**Comment by ralucaStan** [comment]
We need to check if this is still applicable with the native select now in use

**Comment by opr** [comment]
Yes, closed by #47757
