### ISSUE TITLE
[Rest API request] creating new order generating 500 error

### ISSUE THREAD

**Issue by Gradin98** [woothemes/woocommerce#47384]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When access the create order endpoint, I receive an 500 internal server error

### Expected behavior

Order to be created

### Actual behavior

{
    "code": "internal_server_error",
    "message": "<p>There has been a critical error on this website.</p><p><a href=\"https://wordpress.org/documentation/article/faq-troubleshooting/\">Learn more about troubleshooting WordPress.</a></p>",
    "data": {
        "status": 500
    },
    "additional_errors": []
}

Log error
[12-May-2024 07:06:26 UTC] PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /home/gurnyfu/sere/wp-content/plugins/booked/includes/add-ons/woocommerce-payments/lib/woocommerce/class-wc-cart.php:114
Stack trace:
#0 /home/gurnyfu/sere/wp-content/plugins/booked/includes/add-ons/woocommerce-payments/lib/woocommerce/class-wc-cart.php(114): method_exists(NULL, 'get_cart')
#1 /home/gurnyfu/sere/wp-content/plugins/booked/includes/add-ons/woocommerce-payments/lib/woocommerce/class-wc-order.php(174): Booked_WC_Cart::get_cart_appointments()
#2 /home/gurnyfu/sere/wp-includes/class-wp-hook.php(326): Booked_WC_Order_Hooks::woocommerce_validate_order_items(19549)
#3 /home/gurnyfu/sere/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4 /home/gurnyfu/sere/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home/gurnyfu/sere/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(2506): do_action('woocommerce_new...', 19549, Object(WC_Order))
#6 /home/gurnyfu/sere/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(186): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->create(Object(WC_Order))
#7 /home/gurnyfu/sere/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(214): WC_Data_Store->create(Object(WC_Order))
#8 /home/gurnyfu/sere/wp-content/plugins/woocommerce/includes/class-wc-order.php(252): WC_Abstract_Order->save()
#9 /home/gurnyfu/sere/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php(208): WC_Order->save()
#10 /home/gurnyfu/sere/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(191): WC_REST_Orders_Controller->save_object(Object(WP_REST_Request), true)
#11 /home/gurnyfu/sere/wp-includes/rest-api/class-wp-rest-server.php(1230): WC_REST_CRUD_Controller->create_item(Object(WP_REST_Request))
#12 /home/gurnyfu/sere/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/v3/orders', Array, NULL)
#13 /home/gurnyfu/sere/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#14 /home/gurnyfu/sere/wp-includes/rest-api.php(428): WP_REST_Server->serve_request('/wc/v3/orders')
#15 /home/gurnyfu/sere/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#16 /home/gurnyfu/sere/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#17 /home/gurnyfu/sere/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#18 /home/gurnyfu/sere/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#19 /home/gurnyfu/sere/wp-includes/class-wp.php(813): WP->parse_request('')
#20 /home/gurnyfu/sere/wp-includes/functions.php(1336): WP->main('')
#21 /home/gurnyfu/sere/wp-blog-header.php(16): wp()
#22 /home/gurnyfu/sere/index.php(17): require('/home/gurnyfu/s...')
#23 {main}
  thrown in /home/gurnyfu/sere/wp-content/plugins/booked/includes/add-ons/woocommerce-payments/lib/woocommerce/class-wc-cart.php on line 114

### Steps to reproduce

1. Make request with url /wp-json/wc/v3/orders
Body is
{
  "payment_method": "euplatesc",
  "payment_method_title": "Online",
  "set_paid": false,
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  },
  "line_items": [
    {
      "product_id": 19546,
      "quantity": 1
    }
  ],
  "shipping_lines": [
  ]
}

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://serenityheadspa.ro
Site address (URL): https://serenityheadspa.ro
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.3.0
PHP Post Max Size: 130 MB
PHP Time Limit: 165
PHP Max Input Vars: 16000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.42-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: mod168_
Total Database Size: 84.05MB
Database Data Size: 78.46MB
Database Index Size: 5.59MB
mod168_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod168_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod168_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod168_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
mod168_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
mod168_cff_facebook_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_cff_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_cff_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_cff_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
mod168_ctf_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_ctf_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_ctf_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_ctf_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_ctf_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_event_hours: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
mod168_event_hours_booking: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
mod168_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_litespeed_img_optming: Data: 0.45MB + Index: 0.72MB + Engine InnoDB
mod168_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_litespeed_url_file: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
mod168_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
mod168_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod168_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_newsletters: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
mod168_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod168_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
mod168_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod168_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
mod168_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod168_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
mod168_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
mod168_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_options: Data: 10.41MB + Index: 0.14MB + Engine InnoDB
mod168_postmeta: Data: 13.52MB + Index: 0.59MB + Engine InnoDB
mod168_posts: Data: 4.48MB + Index: 0.22MB + Engine InnoDB
mod168_revslider_css: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
mod168_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_revslider_navigations: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
mod168_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_revslider_sliders: Data: 3.45MB + Index: 0.02MB + Engine InnoDB
mod168_revslider_sliders_bkp: Data: 0.30MB + Index: 0.02MB + Engine InnoDB
mod168_revslider_slides: Data: 32.52MB + Index: 0.02MB + Engine InnoDB
mod168_revslider_slides_bkp: Data: 2.52MB + Index: 0.02MB + Engine InnoDB
mod168_revslider_static_slides: Data: 5.27MB + Index: 0.02MB + Engine InnoDB
mod168_revslider_static_slides_bkp: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
mod168_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_sbi_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_sbr_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_sbr_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_sbr_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_sbr_reviews_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod168_sbr_sources: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_sby_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_sby_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_sby_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_timetable_guests: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
mod168_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod168_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
mod168_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
mod168_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
mod168_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod168_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mod168_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod168_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mod168_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
mod168_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mod168_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mod168_wpr_rocket_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mod168_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

attachment: 683
booked_appointments: 3
clients: 8
custom_css: 2
customize_changeset: 2
e-landing-page: 1
elementor_library: 58
events: 10
mailpoet_page: 1
masonry-gallery: 25
nav_menu_item: 9
page: 48
post: 28
product: 5
revision: 179
seedprod: 2
shop_order_placehold: 3
testimonials: 16
timetable_weekdays: 7
wp_global_styles: 1
wp_navigation: 1
wp_template: 3
wpcf7_contact_form: 6
wpcode: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (54) ###

All-in-One WP Migration: by ServMask – 7.81
Booked: by QuickCal
BoxyStudio – 2.4.4

Classic Widgets: by WordPress Contributors – 0.3
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.15.23
Contact Form 7: by Takayuki Miyoshi – 5.9.3
Smash Balloon Custom Facebook Feed: by Smash Balloon – 4.2.3
Custom Twitter Feeds: by Smash Balloon – 2.2.2
Elementor: by Elementor.com – 3.20.2
Envato Market: by Envato – 2.0.11
Estetique Endpoints: by Kocsis Lorand – 1.0
Feeds for YouTube: by Smash Balloon YouTube Team – 2.2
Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
WPCode Lite: by WPCode – 2.1.10
LiteSpeed Cache: by LiteSpeed Technologies – 6.1
Loco Translate: by Tim Whitlock – 2.6.7
Mailjet for WordPress: by Mailjet SAS – 5.5.4
Qi Addons For Elementor: by Qode Interactive – 1.6.9
Qi Blocks: by Qode Interactive – 1.2.6
Qode Framework: by Qode Interactive – 1.2.2
Reina Core: by Qode Interactive – 1.3
Reviews Feed: by Smash Balloon – 1.1.1
Slider Revolution Before/After Add-On: by ThemePunch – 3.1.1
Slider Revolution Bubblemorph AddOn: by ThemePunch – 3.0.8
Slider Revolution Charts AddOn: by ThemePunch – 3.0.5
Slider Revolution Duotone-Filters Add-On: by ThemePunch – 3.0.5
Slider Revolution Exploding Layers Add-On: by ThemePunch – 3.0.5
Slider Revolution The FluidDynamics AddOn: by ThemePunch – 1.0.0
Slider Revolution WP Gallery Add-On: by ThemePunch – 2.0.5
Slider Revolution Distortion Effect AddOn: by ThemePunch – 3.0.5
Slider Revolution Lottie AddOn: by ThemePunch – 3.1.2
Slider Revolution Coming Soon & Maintenance Add-on: by ThemePunch – 3.0.0
Slider Revolution Mousetrap Add-On: by ThemePunch – 3.0.9
Slider Revolution Paint-Brush Add-On: by ThemePunch – 3.0.4
Slider Revolution Panorama AddOn: by ThemePunch – 3.0.9
Slider Revolution Particles Effect: by ThemePunch – 3.3.3
Slider Revolution Particle Wave Add-On: by ThemePunch – 1.1.5
Slider Revolution Reveal Preloaders: by ThemePunch – 3.0.3
Slider Revolution Scroll Video Add-On: by ThemePunch – 3.0.4
Slider Revolution Slicey Add-On: by ThemePunch – 3.0.4
Slider Revolution Holiday Snow: by ThemePunch – 3.0.5
Slider Revolution The Cluster AddOn: by ThemePunch – 1.0.10
Slider Revolution Transitionpack Add-On: by ThemePunch – 1.0.6
Slider Revolution Typewriter Effect: by ThemePunch – 3.0.6
Slider Revolution Weather Add-on: by ThemePunch – 3.0.1
Slider Revolution: by ThemePunch – 6.6.20
SiteOrigin CSS: by SiteOrigin – 1.5.9
Sticky Menu (or Anything!) on Scroll: by WebFactory Ltd – 2.32
Stylish Price List: by Designful – 7.0.22
Timetable Responsive Schedule for WordPress: by QuanticaLabs – 7.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.1

Converter for Media: by matt plugins – 5.12.3
WooCommerce Euplatesc Gateway: by Zamfir Vladimir – 2.5.0
WooCommerce: by Automattic – 8.8.3
WP File Manager: by mndpsingh287 – 7.2.5

### Inactive Plugins (5) ###

Code Snippets: by Code Snippets Pro – 3.6.4
Fonts Plugin | Google Fonts Typography: by Fonts Plugin – 3.6.0
Smash Balloon Instagram Feed: by Smash Balloon – 6.2.9
WP Extra File Types: by Davide Airaghi – 0.5.2
WP Rocket: by WP Media – 3.15.10

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 37 KB

### WC Pages ###

Shop base: #8 - /shop/
Basket: #9 - /basket/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Reina
Version: 1.8.1
Author URL: https://qodeinteractive.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: reina/inc/woocommerce/templates/content-widget-product.php
reina/inc/woocommerce/templates/global/quantity-input.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-12 20:59:26 +01:00
Options: ✔
Notes: 77
Onboarding: completed

### Action Scheduler ###

Complete: 65
Oldest: 2024-04-11 19:10:41 +0100
Newest: 2024-05-12 08:06:34 +0100

Failed: 8
Oldest: 2024-02-01 21:04:16 +0000
Newest: 2024-03-25 08:19:51 +0000

Pending: 2
Oldest: 2024-05-12 20:06:34 +0100
Newest: 2024-05-12 21:17:39 +0100

### Status report information ###

Generated at: 2024-05-12 08:06:44 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vbelolapotkov** [comment]
@mjdeacon @deepakpathania  sending this one to you for further tracking and prioritization.

**Comment by zmaglica** [comment]
Hi @Gradin98, thank you for reaching out to us.

After reviewing the issue, it seems to be unrelated to WooCommerce Payments. Our repository does not contain a `woocommerce` [folder](https://github.com/Automattic/woocommerce-payments/tree/develop/lib) within the `lib` `directory`. The stack trace instead points to the Booked plugin, likely developed by this author: [https://quickcal.co/](https://quickcal.co/). It appears the mentioned plugin adds a `woocommerce-payments` folder and other WooCommerce-related files to its add-ons directory. I recommend contacting the Booked plugin's author for assistance, as the error originates from their code.

I will close this issue now. Please feel free to contact us again or comment here if you have any further questions.
