### ISSUE TITLE
Checkout Block Field not remove

### ISSUE THREAD

**Issue by shakilr** [woothemes/woocommerce#47381]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

i have tired no option and hook are work to remove entire billing fields

### Expected behavior

i want to remove field from checkout block. from billing

### Actual behavior

when i remove field should be remove or add

### Steps to reproduce

1. add to cart any product
2. go checkout 
3. try to remove billing field with hook or template but its not working
4. try checkout block page

### WordPress Environment

not reported

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shakilr** [comment]
please check this error

**Comment by senadir** [comment]
Hey @shakilr! Billing form is hidden and it's behind the shipping form.

Do you want to remove both forms?

**Comment by shakilr** [comment]
yes i want both forms

**Comment by Sepehrworklife** [comment]
I have this problem too, seeking for a solution.

**Comment by tarunvijwani** [comment]
@shakilr @Sepehrworklife Address fields are determined from the country locale. 

You can see how they are defined here:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-countries.php#L851

You may use the `woocommerce_get_country_locale` filter to remove any field. However, I would like to highlight that removing the address fields has consequences. For example, if you have not implemented the code correctly, taxes could break.

**Comment by mikejolley** [comment]
I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

Thank you.
