### ISSUE TITLE
CYS > Patterns Migration: Ensure a handful of pre-selected patterns are still kept within the WooCommerce plugin

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#47402]
**Issue Description:**

Related to: https://github.com/woocommerce/woocommerce/issues/47396

We should ensure a handful of pre-selected patterns are still kept within the WooCommerce plugin: those patterns should still be registered the same way they used to prior to the patterns migration only on the occasion the user is offline or didn't allow fetching patterns from the PTK.

Tagging @verofasulo here as I believe the decision on which patterns should be preserved in the codebase is still pending. All other patterns and corresponding images should be removed.

**Comment by gigitux** [comment]
This is the list of patterns that we have to include in core:

![Default patterns (Woo plugin)](https://github.com/woocommerce/woocommerce/assets/4463174/5edbb38a-beb4-4d76-958e-d4bb03aa0885)


Slack discussion: p1718805314102279-slack-C053716F2H2
