### ISSUE TITLE
Create Unit Test for #40254

### ISSUE THREAD

**Issue by masteradhoc** [woothemes/woocommerce#47413]
### Describe the solution you'd like

Based on the reply of @lsinger we should create unit tests for change #40254.
Let's decouple it so we can go ahead and merge the change already :)

**Comment by barryhughes** [comment]
@masteradhoc thanks for creating this, but it doesn't really seem appropriate to us to create the unit test outside of the PR (especially as the PR is pretty simple, and has not yet been merged).

Adding tests (or updating existing tests) when appropriate, adding changelogs are all part of creating a merge-ready PR (and, of course, other review feedback should be addressed).
