### ISSUE TITLE
thumbnail display error

### ISSUE THREAD

**Issue by rushran** [woothemes/woocommerce#47421]

**Comment by lanej0** [comment]
Hi @rushran -- this is most likely an issue with the theme you're using on your site.  Have you tried enabling one of the default themes and seeing if your issue is still present?

**Comment by rushran** [comment]
> Hi @rushran -- this is most likely an issue with the theme you're using on your site. Have you tried enabling one of the default themes and seeing if your issue is still present?

to be honest, everything worked fine until this day, the site was made by another programmer. if disable the theme used....then everything will break
