### ISSUE TITLE
CYS > Full Composability - Update the frame to ensure that one header, one Intro pattern, and one footer are displayed

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#47462]
**Issue Description:**

⚠️ Blocked by: https://github.com/woocommerce/woocommerce/issues/47402

Currently, the hardcoded template 1 is displayed whenever accessing the assembler for the very first time. According to the new designs, we should update the frame to ensure that only one header, one Intro pattern, and one footer are displayed instead. Example:

<img width="460" alt="Screenshot 2024-05-14 at 13 22 15" src="https://github.com/woocommerce/woocommerce/assets/15730971/5fe6c6d1-105f-4688-b17c-073267f2c39c">

Ideally, these 3 patterns should match whatever we decide to keep as the default fallback within the Woocommerce plugin (see https://github.com/woocommerce/woocommerce/issues/47402 for more details)

Tagging @verofasulo here because I believe the decision on which patterns should be preserved in the codebase is still pending.

**Comment by gigitux** [comment]
Fixed with https://github.com/woocommerce/woocommerce/pull/48467
