### ISSUE TITLE
CYS > Full Composability - When the user hovers over a pattern in the panel, ensure a tooltip with the pattern name appears

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#47463]
**Issue Description:**

When the user hovers over a pattern in the panel, a tooltip with the pattern name appears:

![image-10](https://github.com/woocommerce/woocommerce/assets/15730971/7775c229-deb5-4bd9-86e4-9de471c5b5f1)

**Comment by gigitux** [comment]
Fixed with https://github.com/woocommerce/woocommerce/pull/48207
