### ISSUE TITLE
CYS > Full composability - Ensure the panel with patterns can be closed whenever clicking on the close button

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#47465]
**Issue Description:**

Ensure the panel with patterns can be closed whenever clicking on the close button:

<img width="477" alt="Screenshot 2024-05-14 at 13 33 51" src="https://github.com/woocommerce/woocommerce/assets/15730971/f007dbc5-ecdd-42c5-9ed4-fd7facc84d7f">

[Figma designs](https://www.figma.com/design/FlPl7fHaGv9mpu8Nfl0joH/CYS-with-Assembler---Core?node-id=1334-27728&t=1jGrWrpOrOymVf4F-4)

**Comment by gigitux** [comment]
Fixed with https://github.com/woocommerce/woocommerce/pull/48207
