### ISSUE TITLE
Daily e2e tests: some tests are consistently failing 

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#47473]
Since fixing the workflow there are tests failing for each of the plugin suites in the daily runs.
We should ix those.

**Comment by adimoldovan** [comment]
The workflow was deprecated with https://github.com/woocommerce/woocommerce/pull/48101 and the configuration of those running tests changed. Proper configuration will be addressed with https://github.com/woocommerce/woocommerce/issues/48140.

The Gutenberg tests are still failing and need attention.

**Comment by veljkho** [comment]
Due to merging of #48896 and a few more PRs related to flakiness fixing has resulted in the [daily tests](https://github.com/woocommerce/woocommerce/actions/workflows/tests-daily-run.yml) passing for the first time ever.
