### ISSUE TITLE
Woocommerce setup wizard got stuck after page Business info

### ISSUE THREAD

**Issue by ourbeagleguus** [woothemes/woocommerce#47483]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After repeatedly trying to install the Woocommerce plugin in Wordpress using the automatic setup Wizard, it failed.
The Wizard gets stuck on the page https://allesvoorjebeagle.nl/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=plugins. From here you can then see a completely white screen.

I have tried many times to deactivate the plugin, delete it, clear cache, use other themes (including Storefront and Twenty Twenty-four), deactivate other Plugins to avoid conflicts, but the problem remains.

I also manually installed (and uninstalled again, multiple times) Wordpress in FileZilla and applied the following code in the wp-config.php file:

define( 'WC_REMOVE_ALL_DATA', true );

with the result that my entire arc page was deleted.... Basicly: I've no clue what I'm doing anymore.:)

Now I partially tried to install Woocommerce manually, only now (as a beginner) I don't know how to get pages like “Store”, “Shopping Basket”, “Checkout” and “My Account” installed, as well as the payment page. This bug is not shown in my basic course on how to start a blog with a small shop, and now I'm stuck in to continuing building my website.

### Expected behavior

I expected as a newbie to easily complete the learning module and use the Setup Wizard to easily open a small Woocommerce shop. So that I could and continue with my course and with my sidehustle. Meanwhile, I am now three days along and I am stuck. With a white screen and half a store with no pages.

### Actual behavior

As described earlier, the automatic setup wizard does not function as it should. A bug occurs on the fourth page (the one that redirects to the plugins).

### Steps to reproduce

![Schermafbeelding 2024-05-14 om 19 19 59](https://github.com/woocommerce/woocommerce/assets/169835369/12bfba4e-2c08-43b9-936d-0ba5953aebbf)
![Schermafbeelding 2024-05-14 om 19 20 04](https://github.com/woocommerce/woocommerce/assets/169835369/118631e1-6d7e-41ac-b6f5-94f864fd29f4)
![Schermafbeelding 2024-05-14 om 19 20 11](https://github.com/woocommerce/woocommerce/assets/169835369/9a4f4278-b49a-43c8-9a69-d870d7e26b32)
![Schermafbeelding 2024-05-14 om 19 20 21](https://github.com/woocommerce/woocommerce/assets/169835369/0ce10cf4-fb4a-421e-83c5-54e93293039e)

### WordPress Environment

[SystemStatusReport_allesvoorjebeagle.nl_2024-05-14T17-24-08.txt](https://github.com/woocommerce/woocommerce/files/15312101/SystemStatusReport_allesvoorjebeagle.nl_2024-05-14T17-24-08.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
Hey @ourbeagleguus, thanks for your report! I'm sorry to hear you're having trouble with the setup wizard. I'm going to try to help you out here.

> Now I partially tried to install Woocommerce manually, only now (as a beginner) I don't know how to get pages like “Store”, “Shopping Basket”, “Checkout” and “My Account” installed, as well as the payment page. This bug is not shown in my basic course on how to start a blog with a small shop, and now I'm stuck in to continuing building my website.

First, let's try to get your pages back. You can create the pages you're missing by going to `WooCommerce > Status > Tools` and use the page installer tool. See https://woocommerce.com/document/woocommerce-pages/#install-pages-again for more information.


> As described earlier, the automatic setup wizard does not function as it should. A bug occurs on the fourth page (the one that redirects to the plugins).

Unfortunately, we can't reproduce the issue on our end. I suspect there might be a conflict with another plugin or theme. However, we can try to troubleshoot the issue.

To help us understand what's going wrong, could you please provide us with browser console errors by following these steps:

1. Click on Chrome settings button ( the three dots in the upper-right hand corner of the browser)
2. Go to `More tools > Developer tools`. This should open up the Chrome developer tools panel.
3. Click on the "Console" tab in the Chrome developer tools panel:
4. Take a screenshot of the console and share it with us.

https://developer.chrome.com/docs/devtools/open

You mentioned you tried deactivating other plugins and switching themes, but the issue persists. It would be helpful if you could deactivate all plugins except WooCommerce and switch to a default theme like Twenty Twenty Four when running the setup wizard.

This will help us understand what's going wrong and provide you with a solution. Looking forward to your response! 🙂
