### ISSUE TITLE
Checkout block shows warning `Warning: foreach() argument must be of type array|object, string given` when a guest session is loaded after upgrading to 8.9

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#47485]
#### Issue

Warning shown when loading the Checkout block in WC 8.9 with a guest session created in 8.8.

`Warning: foreach() argument must be of type array|object, string given in wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php on line 152`

It is potentially linked to https://github.com/woocommerce/woocommerce/pull/46762/files#diff-578ec004cc2b40bb0b5b7d4901dc51c209cc8a76456b588cbcbc12b693757466

#### Reproduction steps

1. Be on WC 8.8.3 with no other plugins installed
2. Open an incognito window and add an item to your cart. Go to the Checkout block and check out as a guest.
3. Add an item to the cart and go to the Checkout block.
4. In your main window, upgrade to WC 8.9
5. In the incognito window, refresh the Checkout page.
6. The warning will be shown

**Comment by johanmolen** [comment]
Same issue here.

**Comment by ZaDeveloper** [comment]
Same Issues Here How to fix it?

**Comment by senadir** [comment]
Hey! A fix is here and should land with 8.9.1

https://github.com/woocommerce/woocommerce/pull/47514

This warning will only trigger for guest customers who already had a session in 8.8.x and 8.7.x. It only happens on the first load and then it's gone.

If you really want to get rid of it, you can go to WooCommerce -> Status -> Tools -> Clear Customer sessions, but that will clear existing carts as well.
