### ISSUE TITLE
Cart & Checkout Blocks not working on stores with WC 8.9 + Jetpack Boost's "Concatenate JS" feature

### ISSUE THREAD

**Issue by mattallan** [woothemes/woocommerce#47492]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Internal Slack thread: p1715723094509679-slack-C7U3Y3VMY

Since WooCommerce 8.9, stores using Jetpack + Boost's concatenate JS feature are experiencing an issue where the Cart + Checkout Blocks get stuck loading when any product is added to the cart:

![image](https://github.com/woocommerce/woocommerce/assets/2275145/ae3fac46-209f-45f9-ad9b-2714294c9868)

I think this might be caused by this recent change https://github.com/woocommerce/woocommerce/pull/45859 but I haven't confirmed that yet.

### Expected behavior

Cart and Checkout blocks pages load: 
![image](https://github.com/woocommerce/woocommerce/assets/2275145/dff1e216-cad8-435f-ba3e-4327e889a2d6)

### Actual behavior

Cart & Checkout block pages are getting stuck loading (see screenshot above)

### Steps to reproduce

1. Install & activate the latest WC 8.9
2. Install & activate Jetpack and Jetpack Boost plugins
3. Make sure your store is using the Cart and Checkout blocks
4. Enable Jetpacks "Concatenate JS" by going to **WP Admin > Jetpack > Boost** and turn on the feature ![image](https://github.com/woocommerce/woocommerce/assets/2275145/98347b09-5183-4193-b09b-87dee7892e8d)
5. Visit the shop page and add any product to your cart.
6. Navigate to the Cart block page and notice it's stuck loading:
![image](https://github.com/woocommerce/woocommerce/assets/2275145/d42eedba-8eb1-4838-a357-19a287db8747)
7. Revert back to WC 8.8.3 and refresh the Cart block page, and confirm the Cart is loading.

### WordPress Environment

<details>
### WordPress Environment ###

WordPress address (URL): https://unabashedly-faithful.jurassic.ninja
Site address (URL): https://unabashedly-faithful.jurassic.ninja
WC Version: 8.9.0
REST API Version: ✔ 8.9.0
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.0
WC Database Prefix: wp_
Total Database Size: 3.23MB
Database Data Size: 1.47MB
Database Index Size: 1.76MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
jb_store_css: 1
page: 7
post: 2
product: 1
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Jetpack Boost: by Automattic - Jetpack Site Speed team – 3.3.0
Jetpack: by Automattic – 13.5-a.1
WooCommerce: by Automattic – 8.9.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 B

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-16 03:34:31 +00:00
Options: ✔
Notes: 61
Onboarding: -

### Action Scheduler ###

Complete: 8
Oldest: 2024-05-15 03:35:12 +0000
Newest: 2024-05-15 03:56:53 +0000

Failed: 1
Oldest: 2024-05-15 03:37:35 +0000
Newest: 2024-05-15 03:37:35 +0000

Pending: 2
Oldest: 2024-05-15 15:35:12 +0000
Newest: 2024-05-16 03:35:12 +0000

### Status report information ###

Generated at: 2024-05-15 04:07:49 +00:00
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Update: this comment is now logged as a separate issue in https://github.com/woocommerce/woocommerce/issues/47495

As discussed here, p1715748474161819/1715723094.509679-slack-C7U3Y3VMY, we observed a bug with the mini-cart that could be related to this issue. In order to reproduce this mini-cart issue, you will need to have WooCommerce Subscriptions or WooCommerce Deposits (possibly affects other extensions too) **_AND_** JP Concatenate JS feature enabled too. Here are the steps to replicate:

1. Install WC 8.9
2. Install Jetpack Boost
3. In the Jetpack Boost settings, enable the "Concatenate JS" feature
4. Install WooCommerce Subscriptions.
5. As a shopper, open your browser console and go to the /shop page. 
6. Symptom 1: you will see a bunch of JS errors just by loading the shop page:

![Screenshot from 2024-05-15 13-42-06](https://github.com/woocommerce/woocommerce/assets/4509348/368760ae-418b-43d1-845c-3db0b881e13d)

7. Click on the mini-cart icon.
8. Symptom 2: the contents of the mini-cart is blank, it doesn't load

![Screenshot from 2024-05-15 13-42-23](https://github.com/woocommerce/woocommerce/assets/4509348/64798181-1d2d-490e-815d-e34b2863c9bd)

9. Disable the "Concatenate JS" feature.
10. Notice that the 2 problems above go away.

**Comment by i11za** [comment]
User report 8191409-zd-a8c

**Comment by ralucaStan** [comment]
This issue was fixed with a release of Jetpack boost 3.3.1 https://github.com/Automattic/jetpack-boost-production/releases/tag/3.3.1. To the people affected please update to that version.

**Comment by ralucaStan** [comment]
Reopening this for better visibility as it might come in handy to some people. We'll close it once WooCommerce 8.9.1 will be released on Monday [Dot Release: WooCommerce 8.9.1 is coming soon with fixes.](https://developer.woocommerce.com/2024/05/15/dot-release-woocommerce-8-9-1-is-coming-soon-with-fixes/)

**Comment by ralucaStan** [comment]
closing as [WooCommerce 8.9.1: Dot release ](https://developer.woocommerce.com/2024/05/21/woocommerce-8-9-1-dot-release/) happened
