### ISSUE TITLE
A state is missing "chapainawabganj"  on wocommerce state From Bangladesh. Please add "chapainawabganj" state in bangladesh

### ISSUE THREAD

**Issue by aknirob** [woothemes/woocommerce#47493]
### Describe the solution you'd like

A state is missing "chapainawabganj"  on wocommerce state From Bangladesh. Please add "chapainawabganj" state in bangladesh

### Describe alternatives you've considered

A state is missing "chapainawabganj"  on wocommerce state From Bangladesh. Please add "chapainawabganj" state in bangladesh

### Additional context

A state is missing "chapainawabganj"  on wocommerce state From Bangladesh. Please add "chapainawabganj" state in bangladesh

**Comment by tammullen** [comment]
Hi, in WooCommerce, we use the UNICODE CLDR standard for countries and regions naming and divisions. The recent UNICODE CLDR release 45 showing current country/state names can be seen below:

https://github.com/unicode-org/cldr/blob/dd5776f650183c9172abe2a57313ed41619d41fb/common/subdivisions/en.xml#L385

Closing this won't fix as now, but can reopen if things change with a future CLDR release
