### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by jaydaknight** [woothemes/woocommerce#47517]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I access my site flyingknight.com through a third party link like google search, my site gets redirected to a spam page.
If you google say "Flying knight artist"and then hit the link to my site via the search results it does this. If I access my site by directly typing it into the browser then there is no problem.
I am not sure how to fix this issue.
Thank you

### Expected behavior

Have the spam redirect eliminated

### Actual behavior

When I access my site flyingknight.com through a third party link like google search, my site gets redirected to a spam page.
If you google say "Flying knight artist"and then hit the link to my site via the search results it does this. If I access my site by directly typing it into the browser then there is no problem.
I am not sure how to fix this issue.

### Steps to reproduce

![2](https://github.com/woocommerce/woocommerce/assets/169923558/5a343521-4011-4532-91a2-db8e28fa243d)
![1](https://github.com/woocommerce/woocommerce/assets/169923558/f32f1d73-c89b-4c1b-a8d4-3230911b786d)

### WordPress Environment

Not quite sure

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
FWIW @jaydaknight I can access your site fine from google I do not get a redirect, this might be a problem with your own browser setup.

**Comment by jaydaknight** [comment]
Hi,

Ok. I really appreciate you helping me.
Thank you
