### ISSUE TITLE
[DOC-BUG] Fix 404 in "Understanding WooCommerce Endpoints"

### ISSUE THREAD

**Issue by Brianmitchtay** [woothemes/woocommerce#47567]
## Link to the Page/Section

> Provide a link to the specific page or section that you're referring to.

https://developer.woocommerce.com/docs/woocommerce-endpoints/
https://github.com/woocommerce/woocommerce/blob/trunk/docs/getting-started/woocommerce-endpoints.md

In the "Learn More" section at the bottom [Customizing endpoint URLs](https://developer.woocommerce.com/docs/woocommerce-endpoints/docs/customizing-endpoint-urls) links to a 404 - https://developer.woocommerce.com/docs/woocommerce-endpoints/docs/customizing-endpoint-urls

The article is at - https://developer.woocommerce.com/docs/customizing-woocommerce-endpoint-urls/

## Description of the Suggestion

> Describe the changes you suggest to improve or correct the documentation. Be specific about any errors or areas of confusion you've identified.

It looks like these relative links in the markdown files should be correctly targeting the docs we want, but it's not rendering that way.

I'm not sure what system is being used to render the dev docs, but if it supports root relative URLs we could potentially reformat the markdown on the page to:

```
- [Customizing endpoint URLs](/docs/woocommerce-endpoints/customizing-endpoint-urls.md)
- [Troubleshooting endpoints](/docs/woocommerce-endpoints/troubleshooting-endpoints.md)
```

## Reason for the Suggestion

> Why do you believe this change will make the documentation clearer or more accurate?

We should avoid 404's where possible, this may be a broader issue.

**Comment by rrennick** [comment]
```
- [Customizing endpoint URLs](/docs/woocommerce-endpoints/customizing-endpoint-urls.md)
- [Troubleshooting endpoints](/docs/woocommerce-endpoints/troubleshooting-endpoints.md)
```

Changing to these links will not work. I ran `Refresh from source` on this doc in my dev install and the links in the learn more section are correct.

**Comment by piinthecloud** [comment]
We have fixed the issues by running `Refresh from source`
