### ISSUE TITLE
Wrong redirect to cart page

### ISSUE THREAD

**Issue by cycu85** [woothemes/woocommerce#47573]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After updating, there was an issue with the Show Cart button. opens the checkout page
when redirection to cart is enabled, it also redirects to the checkout page

currently use 8.9.0 version of woocommerce

### Expected behavior

How can i fix it

### Actual behavior

After updating, there was an issue with the Show Cart button. opens the checkout page
when redirection to cart is enabled, it also redirects to the checkout page

prodably problem is with  _wc_add_to_cart_params.cart_url_ 

currently use 8.9.0 version of woocommerce

### Steps to reproduce

1

### WordPress Environment

![obraz](https://github.com/woocommerce/woocommerce/assets/68426297/13008e97-1893-4c41-b7ff-312519b40746)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @cycu85 

Without the information we asked for it is difficult to try recreate this issue.

Can you confirm if you have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active?

Can you also give more details on the theme and plugins you have and where you are seeing the "Show Cart" button?

**Comment by cycu85** [comment]
OK, I know where the problem was
This was with the plugin "Event Manager and Tickets Selling Plugin for WooCommerce - WpEvently - WordPress Plugin" 

Sorry for taking up your time and thank you for your help
You can close the ticket
