### ISSUE TITLE
Checkout fields namespace contains / but is not supported in JS querySelector 

### ISSUE THREAD

**Issue by leonardola** [woothemes/woocommerce#47635]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The new [checkout additional fields](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/additional-checkout-fields.md) uses a `/` as the namespace separator for input ids but javascript query selector throws an error when trying to query ids using `/` 

```
Failed to execute 'querySelector' on 'Document': '#additional-information-woocommerce-payments/woopay-phone-number' is not a valid selector.
```

[Here's](https://github.com/woocommerce/woocommerce/blob/a9aa14e2547b60b8970606e9418d1e763f93952c/plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php#L408C3-L414C1) where Woo checks for the namespace separator.

### Expected behavior

Not use namespace separators that make it impossible to query a field via javascript

### Actual behavior

Currently a `/` is required in the additional checkout field id but javascript throws an error when trying to query fields with `/`.

### Steps to reproduce

- Add the following snippet to a the functions.php file of your theme to add a new checkout field

```
add_action(
	'woocommerce_blocks_loaded',
	function() {
		woocommerce_blocks_register_checkout_field(
			array(
				'id'       => 'plugin-name/test-field',
				'label'    => 'Test field',
				'location' => 'additional',
				'type'     => 'checkbox',
			)
		);
	}
);
```

- Add a product to your cart
- Visit the blocks checkout page
- Open the dev tools
- Execute the following code in the console:

```
document.querySelector('#plugin-name/test-field');
```
- An error will be thrown

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
Thank you for the report @leonardola, not sure how we missed that but yeah,[ IDs can only contain ascii letters, numbers, and `-` and `_`.](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id)

**Comment by jkudish** [comment]
I ran into this too -- IDs can have `/` but to select them you need to escape them with double backslashes, like so:

`my_namespace\\/field_id`

This works and is in the spec:

```Technically, the value for an id attribute may contain any character, except [whitespace](https://developer.mozilla.org/en-US/docs/Glossary/Whitespace) characters. [...]```

Looks like this was already changed, but if I understand the change correctly, it means that we'll need to support both the old ID (with `/` for WC 8.9) and the new ID (with `-` for 8.10+) right? Not ideal... cc @senadir

**Comment by senadir** [comment]
True, it seems it is technically valid if escaped, it's recommended to only stick to ascii letters, numbers, and dash and underscore, I think that's a good balance.

> Looks like this was already changed, but if I understand the change correctly, it means that we'll need to support both the old ID (with / for WC 8.9) and the new ID (with - for 8.10+) right? Not ideal... cc @senadir

Sadly yes :/ I didn't consider the previous behavior valid so this is mainly treated as a bug fix, not an enhancement. I don't think we will backport this to 8.9.
