### ISSUE TITLE
Add global coming soon mode property to wcadmin tracks events

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#47642]
## Issue Description

It would be useful to segment Tracks events by coming soon vs live mode.

## Acceptance Criteria

* Add a global `coming_soon` Tracks property to all wcadmin events.
* Use the values of:
  * `no` when the site / store is live.
  * `site` when the whole site is in coming soon mode.
  * `store` when only the store is in coming soon mode.

**Comment by ilyasfoo** [comment]
@adrianduffell property looks good to me! Caveat is this will not work for onboarding tracks since they are fired before coming soon is determined.

**Comment by ilyasfoo** [comment]
I'll start working on this while we decide for any changes

**Comment by ilyasfoo** [comment]
@adrianduffell Should we also check if `launch-your-store` feature is disabled? If so, we could add `disabled` in the list of possible values

**Comment by adrianduffell** [comment]
> Should we also check if launch-your-store feature is disabled? If so, we could add disabled in the list of possible values

@ilyasfoo Hmm, I think just set the value to `no` in this case because technically the site would be live 🤔 

I'd like to remove the feature flag in 2-3 releases time, so it will only be an edge case for a few months.

**Comment by adrianduffell** [comment]
> Caveat is this will not work for onboarding tracks since they are fired before coming soon is determined

@ilyasfoo Ha good point, I think these will return as `no`. The `woocommerce_coming_soon` option will be set that way when WooCommerce is installed. 

However could it default to `no` when the option value can't be retrieved?

**Comment by ilyasfoo** [comment]
>I'd like to remove the feature flag in 2-3 releases time, so it will only be an edge case for a few months.

@adrianduffell Got it, makes sense.

>However could it default to no when the option value can't be retrieved?

Yes, can be done 👍
