### ISSUE TITLE
[Launch Your Store] Add `is_site_fresh` check before setting coming soon mode after onboarding

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#47641]
### Issue description

We should add `is_site_fresh` criteria prior setting a site to coming soon mode after onboarding wizard is completed to ensure no accidental coming soon set.

### Acceptance criteria

1. Prior setting coming soon mode, ensure [`is_site_fresh`](https://github.com/woocommerce/woocommerce/blob/466e8dac3eca2cb7b7d549e3f1f7b4bcaf29ca9f/plugins/woocommerce/src/Admin/WCAdminHelper.php#L108) returns true

**Comment by adrianduffell** [comment]
@ilyasfoo is it already in place here? https://github.com/woocommerce/woocommerce/blob/8541afa4187326aa35188cbf9fd1a5bf9c523bc4/plugins/woocommerce/src/Admin/API/LaunchYourStore.php#L96

**Comment by ilyasfoo** [comment]
@adrianduffell Oops, I missed that logic! 😆 

Closing this issue
