### ISSUE TITLE
How do we migrate custom product options and tab to the new product editor?

### ISSUE THREAD

**Issue by rogercoathup** [woothemes/woocommerce#47657]
### Discussed in https://github.com/woocommerce/woocommerce/discussions/47329

<div type='discussions-op-text'>

<sup>Originally posted by **rogercoathup** May  9, 2024</sup>
With the current product editor, it's a simple process to add custom product options to the editor.  We'd hook e.g. on 
`woocommerce_product_options_general_product_data` to add options to the general tab, and hook on `woocommerce_process_product_meta` to save the options.

It was similarly simple to add new tabs (and indeed is the approach of a number of plugins e.g. dynamic pricing, facebook for wp, gravity forms, affiliateWP).

How do we add & save custom product options with the new product editor?  </div>

**Comment by tammullen** [comment]
Thanks for asking, closing this issue as there is already a discussion. I will highlight your discussion so hopefully you can get an answer there.
