### ISSUE TITLE
Consider stacking the input and button in the Add Coupon section of Cart/Checkout blocks on smaller screens

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#47655]
When on a smaller screen, the coupon code input and apply button are still shown inline. This causes the placeholder to be cut off. It may be worth considering stacking these when the screen size is smaller to allow the full input to be shown.

<img width="288" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/ac2e45ab-dce3-4f6c-b3e4-350f64dbdf76">

In languages where the word for "Apply" is longer, such as German, this issue becomes even more obvious.

<img src="https://github.com/woocommerce/woocommerce/assets/5656702/ab8613fc-37d6-4446-a9d8-554b541dda75" width="288" />

cc @nikkivias

**Comment by pmcpinto** [comment]
@nikkivias can you take a look at this issue in the upcoming days? Thanks

**Comment by dominique-vias** [comment]
Yes, let's 100% stack the elements when it gets too small. [Here is a mockup of it](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic-File%5D-Cart-%26-Checkout-Blocks?node-id=637-9489&t=SqLQNkiTDqqZbuir-1)

What do you propose is a good breakpoint size to when it stacks?

![Summary-Small](https://github.com/woocommerce/woocommerce/assets/99638528/536ff434-62e7-4754-a15e-35135adbec86)

**Comment by pmcpinto** [comment]
@opr @ralucaStan can we unblock this one, considering that we already have the mockup?

**Comment by ralucaStan** [comment]
Done
