### ISSUE TITLE
Create Shipping Method modal - update local pickup copy

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#47734]
**Description:** we received feedback indicating that the local pickup copy displayed in the "Create Shipping Method" modal may be confusing for some users when they already have pickup options enabled. Feedback [here](https://wordpress.org/support/topic/local-pickup-not-showing-up-in-method-selections/). We should improve the copy to avoid any potential ambiguity. 

<img width="1005" alt="Captura de ecrã 2024-05-22, às 19 33 48" src="https://github.com/woocommerce/woocommerce/assets/3380168/fba231ba-c3e1-4297-8591-d513237d016b">

**Acceptance criteria:**
- [ ] When the store has the block-based local pickup enabled, update the local pickup copy displayed in the modal to Local pickup: Manage existing pickup locations in the [Local pickup settings page].

**Comment by pmcpinto** [comment]
cc @elizaan36 can you review the copy? Thanks

**Comment by elizaan36** [comment]
Looks perfect!

**Comment by ralucaStan** [comment]
I've added this to the `Polish the out-of-the-box checkout experience` epic, under Admin
