### ISSUE TITLE
Improve Performance and Registration Method for Dynamic WooCommerce Blocks

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#47736]
## Description:

Currently, WooCommerce uses various blocks to construct posts, pages, and templates in the editor. Some of these blocks are registered dynamically, depending on whether the user is editing posts, pages, or templates. One method, registerBlockSingleProductTemplate, is used to register specific blocks only within the Single Product template. This method works by subscribing to the `core/edit-site` and `core/edit-post` stores of WordPress.

## Problem:

The current approach has the following issues:

- Performance Impact: Each block registered using `registerBlockSingleProductTemplate` is notified for every update in the `core/edit-site` and `core/edit-post` stores. This results in significant performance degradation.
- Race Conditions: Multiple blocks using this method can lead to race conditions, as they receive updates simultaneously.

## Proposed Solution:

To address these issues, a more performant method has been developed for the Product Gallery block. This method only sends notifications when there is navigation to another post, page, or template. When this occurs, we decide whether to register the block for that specific post, page, or template.

## Steps to Implement:

- Identify Dynamic Blocks: List all blocks currently using `registerBlockSingleProductTemplate`.
- Adopt New Method: Implement the new registration method used for the Product Gallery block across these dynamic blocks.
- Optimize Notifications: Ensure that notifications are sent only during navigation to different posts, pages, or templates.
- Testing and Validation: Thoroughly test the new method to ensure no race conditions and improved performance.

## Expected Outcomes:

- Enhanced performance due to reduced notifications.
- Avoidance of race conditions.
- Consistent and efficient dynamic block registration across posts, pages, and templates.

**Comment by Aljullu** [comment]
I'm not sure if it's exactly the same, but we have some code to register/unregister the Classic Template block as well:

https://github.com/woocommerce/woocommerce/blob/f85a7ba3d4c5b6a7da5ca361a828b6b5aa7a66ff/plugins/woocommerce-blocks/assets/js/blocks/classic-template/index.tsx#L364-L444

In case it's possible, it would be nice to unify the logic of all those blocks that need to be dynamically registered or unregistered.
