### ISSUE TITLE
[LYS] The "coming soon" message doesn't display properly on tablet and mobile

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47759]
I noticed the "Coming soon" banner on the front-end looks a bit off on tablet and mobile. Ideally, it'd have the same spacing and padding as the desktop version. Additionally, the `Change visibility settings` button should be capitalized.

![image](https://github.com/woocommerce/woocommerce/assets/79307566/da007c21-ca8b-4b8e-997f-951cee43080c)

cc @verofasulo

**Comment by ilyasfoo** [comment]
@jarekmorawski This is what it's looking right now with @chihsuan's [fix here](https://github.com/woocommerce/woocommerce/pull/47980). I'm not sure how did you get the `change visibility settings` button to appear disjointed from the sentence, but in this example I think capitalization of `Change` may not look as intended. What do you think?


<img width="657" alt="image" src="https://github.com/woocommerce/woocommerce/assets/3747241/03351602-d7d9-4ca3-85e7-0ea31de522bd">


cc @chihsuan

**Comment by jarekmorawski** [comment]
Agreed. I actually thought the link was detached from the rest of the message. If that isn't the case, I'd lowercase.
