### ISSUE TITLE
Delete test orders in LYS hub

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#47769]
## Issue Description

Provide an option to delete test orders in LYS. For the first implementation, delete test orders made with the WooPayments payment gateway only. For details about it's test mode, see: https://woocommerce.com/document/woopayments/testing-and-troubleshooting/testing/

We'll look to support a full range of payment gateways at a later date.

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/73b96776-1906-4064-843a-89de5d0c0dfb)

[Figma](https://www.figma.com/design/0BWMerqRR1f468EwC7g5tg/LYS?node-id=835-28896&t=P21Ov9OujfOBd0bq-4)

## Acceptance Criteria

Using WooPayments test orders only,

* Implement the design above, using a toggle to delete test orders and in the label provide an accurate count of test orders in the system.
* The toggle should be enabled by default.
* Perform a bulk delete test orders when the user clicks "Launch your store button" and the option is toggled
* Detect errors and send a Tracks event, but continue launching the store regardless.

**Comment by moon0326** [comment]
**Dev note**

The [doc](https://woocommerce.com/document/managing-orders/testing-orders/) says:

> There is currently no visual difference or special status for test orders. As a result, other extensions, plugins, or services that integrate with WooCommerce, may be unable to differentiate between these test orders and your real orders.

However, test orders have `_wcpay_mode` meta data with `test` value stored in `wp_wc_orders_meta` table.

**Comment by moon0326** [comment]
Do we also want to make it backward compatible for those stores without [HPOS](https://woocommerce.com/document/high-performance-order-storage/) enabled?

It is enabled by default for new installations from WooCommerce 8.2 and onward.
