### ISSUE TITLE
WP core/list-item block has a specific behavior when querying attributes with WooCommerce 8.9.1 active

### ISSUE THREAD

**Issue by webaxones** [woothemes/woocommerce#47768]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In a typography correction plugin, I check keyboard input via `subscribe` and retrieve the attributes of the current block using `getBlockAttributes(currentBlockId)` to determine if it can be processed.

For a Paragraph block (as with other blocks of this type), we initially get a result with the content attribute, which returns the `RichTextData` class. However, this is immediately followed by a second result where the content attribute indeed holds the entered character. Furthermore, as typing continues, the content attribute updates with the correct string.
![image](https://github.com/WordPress/gutenberg/assets/17084006/fbff47d0-4f1d-4700-88ea-cc9953afb698)

However, with a `core/list-item` block, **and WooCommerce active**, the behavior differs for the first item compared to the subsequent items: for the first element of the list, with each character input, we consistently receive the RichTextData wrapper. Yet, starting from the second list item, the content attribute displays the entered content correctly.
![image](https://github.com/WordPress/gutenberg/assets/17084006/6b4115fd-d388-418e-a6e9-5b8c82879e8f)

The following image corresponds exactly to the previous one. Three characters entered on the first list item return RichTextData, while the same three characters entered on the second list item return the content.
![image](https://github.com/WordPress/gutenberg/assets/17084006/c4eede09-a7e5-4584-8201-07d95b1c8506)

My question is as follows: is it normal to have different results for each item in the list when WooCommerce is active?

Thanks!

### Expected behavior

The same result as without woocommerce

### Actual behavior

A WP Core block strange behavior

### Steps to reproduce

1. Install WooCommerce and activate it
2. Create a plugin to have a JS file in the post editor and paste following code
3. Add a core/list-item block on a post and type first and second item
4. Save console.log results for comparison
5. Deactivate WooCommerce
6. Add a core/list-item on a post and type first and second item
7. Compare console.log results with previous ones.

```js
import { subscribe, select } from '@wordpress/data'
const { getBlockAttributes } = select( 'core/block-editor' )
domReady( () => {
	subscribe( () => {
		const blockAttributes = getBlockAttributes( currentBlockId )
		console.log( blockAttributes )
	} )
} )
```

### WordPress Environment

WordPress 6.5.3
Gutenberg plugin is not installed
WooCommerce 8.9.1 (same with previous version)

===

`
### WordPress Environment ###

WordPress address (URL): http://woocommerce.lndo.site
Site address (URL): http://woocommerce.lndo.site
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 1 Go
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Debian)
PHP Version: 8.2.18
PHP Post Max Size: 100 Mo
PHP Time Limit: 90
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.29
Max Upload Size: 100 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: woo_
Taille totale de la base de données: 5.93MB
Taille de la base de données: 4.16MB
Taille de l’index: 1.77MB
woo_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
woo_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
woo_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
woo_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
woo_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
woo_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_actionscheduler_actions: Données : 0.06MB + Index : 0.16MB + Moteur InnoDB
woo_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
woo_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_options: Données : 3.03MB + Index : 0.06MB + Moteur InnoDB
woo_postmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_posts: Données : 0.06MB + Index : 0.06MB + Moteur InnoDB
woo_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
woo_wc_admin_notes: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
woo_wc_admin_note_actions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
woo_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
woo_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
woo_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
woo_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
woo_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
woo_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
woo_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
woo_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
woo_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
woo_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 6
revision: 16
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Consistency: par Loïc Antignac – 1.5.3
WooCommerce: par Automattic – 8.9.1

### Inactive Plugins (4) ###

Block Example: par The WordPress Contributors – 0.1.0
Block Visibility: par Nick Diego – 3.4.0
Nico: par  – 1.0.0
Query Monitor: par John Blackbourn – 3.16.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 38 Ko

### WC Pages ###

Base de la boutique: #6 - /boutique/
Panier: #7 - /panier/
Commander: #8 - /commander/
Mon compte: #9 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Storefront
Version: 4.5.5 (une mise à jour de la version 4.6.0 est disponible)
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-24 14:49:09 +02:00
Options: ✔
Notes: 76
Onboarding: skipped

### Action Scheduler ###

Terminé: 74
Oldest: 2024-05-01 17:10:25 +0200
Newest: 2024-05-23 16:47:04 +0200

En attente: 2
Oldest: 2024-05-24 04:46:53 +0200
Newest: 2024-05-24 16:44:32 +0200

### Status report information ###

Generated at: 2024-05-23 17:09:59 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
Hi @webaxones, thanks for reporting this issue.
What I see from my tests is that the previously created list items return the RichTextData object and the newly created ones return the string.

Steps:
1. Insert a `List` block.
2. Type the first item (then I see the log with just the string I typed).
3. Save/update the post and refresh the page.
4. Add some more characters to the first item (then I see the RichTextData object logged).
5. Press enter and start typing the second list item (then I see the log with just the string).
6. At this point if you save/update the post, refresh the page, and try again, I get the RichTextData on items 1 and 2 and the string on newly added list items.

I've been able to reproduce consistently that mentioned behavior with and without WooCommerce installed.
Would you be able to try those steps and see if you can reproduce the same?

Thanks a lot!

**Comment by webaxones** [comment]
Hi @albarin 
[Here is the behavior](https://www.dropbox.com/s/rvwvm8emnptrbfo/Enregistrement%20de%20l%E2%80%99%C3%A9cran%202024-05-28%20%C3%A0%2018.10.23.mov?dl=0) I observe when reproducing what you say. Indeed I don't have WooCommerce (shame on me because I first made an issue on gutenberg and I closed it to move it here), however it seems that it's a bit different from what you have because I don't have a string when typing the first item.
For ease, I use wp-env and [my own plugin](https://github.com/webaxones/consistency) and I just commented out all the lines inside [the subscribe](https://github.com/webaxones/consistency/blob/master/src/index.js#L63) and added the ones to log:
```js		
		const blockAttributes = getBlockAttributes( currentBlockId )
		console.log( blockAttributes )
```
Thanks :)

**Comment by webaxones** [comment]
Hi @albarin 
Do you want me to move this issue back to the Gutenberg repository?
Because I'm going to be away for 1 month, so in 2 days I won't be able to do it anymore :)

**Comment by albarin** [comment]
Yes, that would be great, thank you so much @webaxones

**Comment by webaxones** [comment]
Done :)
