### ISSUE TITLE
New image empty state for variations

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#47788]
**Description:** this issue is a follow-up of #45920, as we only support one image per product variation and the new empty state can mislead users. We need to adjust the experience when the empty state is applied to a product variation

**Acceptance criteria:**
- [x] These changes should only be applied to product variations
- [x] The image should only show the frame of one product
- [x] The copy should also be updated to something like: For best results, offer an image for each product variation, showing its unique characteristics.

**Comment by pmcpinto** [comment]
@louwie17 I added this to the cycle 48. I assume it's a simple change, so it should be handled with #45920. cc @mdperez86 

@j111q can you add the image for this empty state and review the copy? Thanks

**Comment by j111q** [comment]
Here's my proposal to make this clearer for the user.

Change the **Section Title** to `Variation image`.
**Copy**: `Add an image which displays the unique characteristics of this variation.`

Mock-up:
![image](https://github.com/woocommerce/woocommerce/assets/65582817/ae832892-45c4-4cd5-beb5-9f9e3c63748e)

[Figma link here](https://www.figma.com/design/vhp1LFki2xHqjck6UegZJT/Product-Form-2.0-Working-FIle?node-id=1169%3A26751&t=H4ar2KKMRh1LxaRB-1).

Do y'all think that works?

**Comment by pmcpinto** [comment]
Looks good to me. Thanks!
