### ISSUE TITLE
Get Store currency from WooCommerce Settings instead of `wcpay_multi_currency_store_currency`

### ISSUE THREAD

**Issue by AashikP** [woothemes/woocommerce#47793]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you use a custom currency, and then remove the code declaration for that custom currency, WooPayments will throw a Fatal Error.

### Expected behavior

WooCommerce itself reverts back to the first currency in the list if the code declaration for the custom currency is not available. WooPayments should either use that logic or look at store currency.

### Actual behavior

WooPayments relies on the `wcpay_multi_currency_store_currency` database entry to guess the custom currency .

### Steps to reproduce

1. Create a custom currency

```
add_filter( 'woocommerce_currencies', 'add_my_currency' );

function add_my_currency( $currencies ) {
     $currencies['SING'] = __( 'Singa Custom', 'woocommerce' );
     return $currencies;
}
```

2. Set that as the currency under WooCommerce → Settings → General → Currency options
3. Remove the custom code 
4. WooPayments will then throw this error:

```
24-May-2024 06:52:37 UTC] PHP Fatal error:  Uncaught TypeError: WCPay\MultiCurrency\Currency::get_name(): Return value must be of type string, null returned in /wordpress/plugins/woocommerce-payments/7.6.0/includes/multi-currency/Currency.php:156
Stack trace:
#0 /wordpress/plugins/woocommerce-payments/7.6.0/includes/multi-currency/Analytics.php(140): WCPay\MultiCurrency\Currency->get_name()
#1 /wordpress/plugins/woocommerce-payments/7.6.0/includes/multi-currency/Analytics.php(63): WCPay\MultiCurrency\Analytics->register_customer_currencies()
#2 /wordpress/plugins/woocommerce-payments/7.6.0/includes/multi-currency/Analytics.php(52): WCPay\MultiCurrency\Analytics->init()
#3 /wordpress/plugins/woocommerce-payments/7.6.0/includes/multi-currency/MultiCurrency.php(286): WCPay\MultiCurrency\Analytics->__construct(Object(WCPay\MultiCurrency\MultiCurrency))
#4 /wordpress/core/6.5.3/wp-includes/class-wp-hook.php(324): WCPay\MultiCurrency\MultiCurrency->init('')
#5 /wordpress/core/6.5.3/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/core/6.5.3/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/core/6.5.3/wp-settings.php(695): do_action('init')
#8 /srv/htdocs/wp-config.php(83): require_once('/wordpress/core...')
#9 /wordpress/core/6.5.3/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#10 /wordpress/core/6.5.3/wp-blog-header.php(13): require_once('/wordpress/core...')
#11 /wordpress/core/6.5.3/index.php(17): require('/wordpress/core...')
#12 {main}
  thrown in /wordpress/plugins/woocommerce-payments/7.6.0/includes/multi-currency/Currency.php on line 156
```

5. To fix this, you either need to add the currency declaration back, or save a different currency under WooCommerce → Settings → General → Currency options

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by AashikP** [comment]
Hat tip to @kaushikasomaiya  for narrowing this down.

**Comment by kaushikasomaiya** [comment]
Another report spotted on forum https://wordpress.org/support/topic/fatal-error-using-currency/

**Comment by tammullen** [comment]
Hi @AashikP @kaushikasomaiya do you think this is a WooCommerce core issue? Or should it be in the WooPayments repo?

**Comment by csmcneill** [comment]
@tammullen I've moved this over to https://github.com/Automattic/woocommerce-payments/issues/8879 as the error seems primarily related to some of the code in `includes/multi-currency/Currency.php`.

I'm not a developer, but it seems as though WooPayments tries to get currency information from Core — like [the currency name](https://github.com/Automattic/woocommerce-payments/blob/7e803543334fe72317b178ac94f58790be6c45aa/includes/multi-currency/Currency.php#L157-L165) using `get_woocommerce_currencies()`. However, in this particular instance, it seems like WooPayments may not be handling that super well if a merchant is using a custom currency.

I'll close this issue. If we determine this is an issue in WooCommerce Core, we can re-open it.

**Comment by AashikP** [comment]
Sorry about that! I meant to post it in WooPayments repo and not here 😅
