### ISSUE TITLE
Variation selector display issues on the front end

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47794]
First reported here: https://github.com/woocommerce/woocommerce/issues/42299

There are a few issues with how the variation selector block is shown on the front-end. Tested in Chrome and Safari on MacOS.

**The dropdown should use the same appearance settings (height, padding, border size and color) as the stepper and the quantity input field.**

<img width="309" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/f88b5907-b42e-43aa-9108-e0bf5876e511">

**On a variable product page, the right padding of the dropdown button is missing.**

![image](https://github.com/woocommerce/woocommerce/assets/79307566/9270f37d-35e9-428f-b825-1f56ef61e67d)

**The dropdown is unstyled in Safari.**

![image](https://github.com/woocommerce/woocommerce/assets/79307566/7e6df56d-dc0d-4f6f-ba87-40df0894c195)

**Comment by gigitux** [comment]
Regarding the Safari issue, I did an investigation, and unfortnaly I discovered that if the default WebKit style is disabled with `webkit-appearance:none`, the arrow will not be visible anymore:

![image](https://github.com/woocommerce/woocommerce/assets/4463174/adc75012-2c95-44a8-9246-8e5be898e471)


This is a common issue:
- https://github.com/alphagov/govuk-frontend/issues/3520
- https://www.sitepoint.com/community/t/select-arrow-no-showing-webkit-appearance-none/114625/1



Adding an arrow requires some DOM/CSS changes. I'm going to put this issue on hold and revisit it when we have the capacity to work on this block.

**Comment by ResponsiveFlow** [comment]
Does it mean that for now the variation picker will stay as is in Safari?

**Comment by gigitux** [comment]
> Does it mean that for now the variation picker will stay as is in Safari?

Yes!

**Comment by octaedro** [comment]
Hi @j111q,

I'm working on this issue. I fixed the [selector styles in Chrome](https://github.com/woocommerce/woocommerce/pull/51023) but I was wondering what is expected for the chevron styles.

Initially, it looks correct to me, but I wanted to confirm with you if we should modify anything regarding its alignment.
![Screenshot 2024-08-28 at 5 04 53 PM](https://github.com/user-attachments/assets/81f20f15-ab40-46fc-a011-33560a8f05ab)

**Comment by j111q** [comment]
Oh got it. I think, following the quantity picker design as Jarek mentioned above, we'd also need padding on the right on the chevron. I believe it's 12px? So something like this:

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/27992fb5-a55a-4d52-932e-9760f7319063">

Let me know if that works 😁
