### ISSUE TITLE
Add a way of opening 'add product' with a different starting template

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#47817]
## Description

Extensions need a way of redirecting to the new editor while also choosing a specific product template. We could do that through a URL parameter, here's an example:

`admin.php?page=wc-admin&path=%2Fadd-product&template=<template_id>`

When that parameter is provided, we could automatically choose that template instead of starting with the standard one.

### Acceptance Criteria

- [ ] When opening the new product editor with `admin.php?page=wc-admin&path=%2Fadd-product&template=<template_id>`, passing a valid template id, that template is automatically selected instead of the standard template.

**Comment by ResponsiveFlow** [comment]
I think this issue is related #38061
