### ISSUE TITLE
Fluent SMTP Server Error

### ISSUE THREAD

**Issue by TassyJade24** [woothemes/woocommerce#47818]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have been struggling to get my emails to work through my website. I managed to add my email accounts to Outlook after having problems adding accounts. I had to ask my IT guy, who had originally set up my emails, to change the DNS setting to match the server provider that I am with. After doing so, I added my email accounts without a problem, but now I can't send emails via Fluent SMTP or any mail service. I tried SMTP Mailer and had the same issue. An error message popped up, stating it couldn't connect to the host server. I have tried with all 3 emails. My server double-checked my credentials repeatedly and said everything is fine. I have opened a ticket with Fluent SMTP and haven't heard anything yet. I have tried everything I could think of. I have googled and searched and keep coming up with the same problem. 

I can send and receive emails on my outlook account on their own but nothing from my website. 

![Screenshot 2024-05-24 133240](https://github.com/woocommerce/woocommerce/assets/170761822/300afc98-7a06-40af-bcf4-38488a768a8e)
![Screenshot 2024-05-24 101743](https://github.com/woocommerce/woocommerce/assets/170761822/3d486827-be9f-4b19-a6e8-bf4a6e37cf63)
![Screenshot 2024-05-24 101728](https://github.com/woocommerce/woocommerce/assets/170761822/118d7206-00ab-4609-9ba4-33ef8a2ddd41)
![Screenshot 2024-05-24 101713](https://github.com/woocommerce/woocommerce/assets/170761822/80d2aee3-1e3b-4ccf-8c9f-fde9d30aa199)

### Expected behavior

I need a solution. I have gone around in circles for about 2 weeks to get my emails to work. I need to be able to send and receive emails via WordPress. 

### Actual behavior

It keeps popping up with an Error message stating it can't connect to a server. Something I also noticed while recording the email logs didn't update after 2pm I am submitting this bug at 10:03pm

### Steps to reproduce

Uploading 24.05.2024_21.59.53_REC.mp4…

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://tasminscrochetcreations.co.za
Site address (URL): https://tasminscrochetcreations.co.za
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.28
PHP Post Max Size: 1 GB
PHP Time Limit: 720
PHP Max Input Vars: 10000
cURL Version: 7.76.1
OpenSSL/3.0.7

SUHOSIN Installed: –
MySQL Version: 8.0.36-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wpca_
Total Database Size: 86.16MB
Database Data Size: 73.88MB
Database Index Size: 12.28MB
wpca_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpca_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpca_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpca_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_actionscheduler_actions: Data: 2.50MB + Index: 3.05MB + Engine InnoDB
wpca_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_actionscheduler_logs: Data: 2.52MB + Index: 1.92MB + Engine InnoDB
wpca_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpca_cp_calculated_fields_form_discount_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_cp_calculated_fields_form_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_cp_calculated_fields_form_revision: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wpca_cp_calculated_fields_form_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_firebox_logs: Data: 1.52MB + Index: 0.86MB + Engine InnoDB
wpca_firebox_logs_details: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_firebox_submission_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_firebox_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_fsmpt_email_logs: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wpca_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wpca_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_hfcm_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_options: Data: 13.20MB + Index: 0.14MB + Engine InnoDB
wpca_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_post_smtp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_postmeta: Data: 39.52MB + Index: 3.88MB + Engine InnoDB
wpca_posts: Data: 9.52MB + Index: 0.39MB + Engine InnoDB
wpca_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpca_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpca_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wpca_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wpca_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpca_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpca_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpca_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpca_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpca_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wpca_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpca_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpca_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpca_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wpca_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpca_wpml_mails: Data: 1.52MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 403
bsf_custom_fonts: 1
customize_changeset: 41
custom_css: 1
elementor_library: 2
firebox: 5
nav_menu_item: 23
page: 18
post: 1
product: 41
product_variation: 425
revision: 780
shop_order: 14
wpcf7_contact_form: 1
wpforms: 11
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.73
PUDO Shipping for WooCommerce: by The Courier Guy – 1.0.0
Starter Templates: by Brainstorm Force – 4.2.5
Calculated Fields Form: by CodePeople – 5.2.5
Classic Widgets: by WordPress Contributors – 0.3
Contact Form 7: by Takayuki Miyoshi – 5.9.4
Custom Fonts: by Brainstorm Force – 2.1.5
Decorator - WooCommerce Email Customizer: by WebToffee – 1.2.9
Elementor: by Elementor.com – 3.21.7
FireBox: by FireBox Popup Plugin Team – 2.1.12
Google Listings and Ads: by WooCommerce – 2.7.0
Site Kit by Google: by Google – 1.126.0
Header Footer Code Manager: by 99robots – 1.1.37
Image Optimizer by Elementor – Compress, Resize and Optimize Images: by Elementor.com – 1.3.0
Maintenance: by WebFactory Ltd – 4.08
SMTP Mailer: by naa986 – 1.1.13
TikTok: by TikTok – 1.2.5
Discount Rules Core: by Flycart – 2.6.3
WooCommerce Legacy REST API: by WooCommerce – 1.0.3
WooCommerce Payfast Gateway: by WooCommerce – 1.6.5
WooCommerce: by Automattic – 8.9.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WPForms Lite: by WPForms – 1.8.8.3
YouTube WordPress Plugin by Embed Plus: by Embed Plus YouTube Plugin Team – 14.2.1.2

### Inactive Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.12
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.62

Variation Swatches for WooCommerce: by CartFlows – 1.0.8
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.27

### Must Use Plugins (1) ###

Elementor Safe Mode: by Elementor.com – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 781 KB

### WC Pages ###

Shop base: #1613 - /shop/
Cart: #1079 - /cart/
Checkout: #1080 - /checkout/
My account: #1081 - /my-account/
Terms and conditions: #1995 - /terms-conditions/

### Theme ###

Name: Astra
Version: 4.6.15
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-25 09:15:50 +00:00
Options: ✔
Notes: 134
Onboarding: completed

### Action Scheduler ###

Complete: 6,745
Oldest: 2024-04-23 20:45:41 +0000
Newest: 2024-05-24 19:21:49 +0000

Failed: 42
Oldest: 2023-06-23 12:14:24 +0000
Newest: 2024-05-24 09:40:54 +0000

Pending: 12
Oldest: 2024-05-25 04:46:13 +0000
Newest: 2024-05-27 14:00:30 +0000

### Status report information ###

Generated at: 2024-05-24 20:04:30 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@TassyJade24 Sorry to hear you are having the issue with your email. WooCommerce relies on the WP core email implementation (which your SMTP plugin extends) and does not have any custom email handling code. I'll close this as a support issue where you need to follow up with your server and DNS support.
