### ISSUE TITLE
Error 404 spamming in log for coming-soon.css not found

### ISSUE THREAD

**Issue by Dennis1993** [woothemes/woocommerce#47829]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After the update to 8.9.1 the log get spammed by the following error if someone edits a page in wp-admin

ERROR404: /wp-content/plugins/woocommerce/assets/client/blocks/coming-soon.css?ver=wc-8.9.1

### Expected behavior

no error 404

### Actual behavior

error 404 appears if you edit a page in wp-admin

### Steps to reproduce

1. Go to /wp-admin
2. click on pages on the left sidebar
3. edit a page and the log entry appears

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://intranet
Site address (URL): https://intranet
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Ubuntu)
PHP Version: 8.2.19
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.11.8-MariaDB-ubu2004
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 145.51MB
Datenbank-Datengröße: 70.94MB
Datenbank-Indexgröße: 74.57MB
wp_woocommerce_sessions: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.27MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 2.52MB + Index: 2.97MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.41MB + Index: 0.56MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.31MB + Index: 0.27MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 1.52MB + Index: 0.45MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 5.05MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Daten: 18.22MB + Index: 13.14MB + Engine InnoDB
wp_posts: Daten: 23.42MB + Index: 2.89MB + Engine InnoDB
wp_statistics_events: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_exclusions: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_historical: Daten: 6.52MB + Index: 9.06MB + Engine InnoDB
wp_statistics_pages: Daten: 2.02MB + Index: 20.08MB + Engine InnoDB
wp_statistics_search: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_useronline: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visit: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor: Daten: 6.02MB + Index: 21.13MB + Engine InnoDB
wp_statistics_visitor_relationships: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termine: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.27MB + Index: 0.14MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 2.20MB + Index: 1.97MB + Engine InnoDB
wp_users: Daten: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.31MB + Index: 0.30MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1809
ibf: 33
nav_menu_item: 102
oembed_cache: 6
page: 154
post: 919
product: 184
product_variation: 309
revision: 3478
shop_order: 376
wp_block: 2
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 23

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Co-Authors Plus: von Mohammad Jangda
Daniel Bachhuber
Automattic – 3.6.1

Contact Form 7: von Takayuki Miyoshi – 5.9.5
Members: von MemberPress – 3.2.9
Simple LDAP Login: von Clif Griffin Development Inc. – 1.6.0
WooCommerce: von Automattic – 8.9.1
WP Statistics: von VeronaLabs – 14.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 1.019 B

### WC Pages ###

Shop-Basis: #1427 - /shop/
Warenkorb: #1428 - /warenkorb/
Kasse: #1429 - /kasse/
Mein Konto: #1430 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Intranet
Version: 1.4.0
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: intranet/woocommerce/myaccount/dashboard.php
intranet/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-25 14:53:55 +02:00
Options: ✔
Notes: 167
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 1.206
Oldest: 2024-04-24 15:25:01 +0200
Newest: 2024-05-25 12:15:02 +0200

Fehlgeschlagen: 11
Oldest: 2023-02-15 19:49:04 +0100
Newest: 2023-09-20 08:10:01 +0200

Ausstehend: 2
Oldest: 2024-05-25 22:30:01 +0200
Newest: 2024-05-26 07:00:01 +0200

### Status report information ###

Generated at: 2024-05-25 14:51:53 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
@Dennis1993 Thanks for the report. 

I'm having trouble reproducing this one. Are you seeing the 404 error in your browser console or in the PHP logs? I've checked both and see no error logs. I confirmed the file `wp-content/plugins/woocommerce/assets/client/blocks/coming-soon.css` should not exist, but something is trying to request it, I just don't know where from.

Which page are you editing? Do you see the error on all pages? Or are you editing a template?

Thanks

**Comment by psealock** [comment]
I can confirm it now when adding a new post. Thanks for the issue @Dennis1993, we'll get this sorted as soon as we can.

<img width="515" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/f7e653d4-e415-40d0-ae8a-068e345afcfc">

**Comment by psealock** [comment]
Although I can reproduce this with WooCommerce 8.9.1, I am not able to with 9.0.0-beta.1. I wonder if its already been fixed? Here is the beta zip for reference, [woocommerce.9.0.0-beta.1.zip](https://github.com/user-attachments/files/15507534/woocommerce.9.0.0-beta.1.zip)

**Comment by psealock** [comment]
I will close this for now, and if the 404 pops up again will reopen this issue. Thanks @Dennis1993

**Comment by masteradhoc** [comment]
@psealock why was this not added as part of the last release 8.9.3?
We still get these messages a lot.

**Comment by psealock** [comment]
@masteradhoc It will be in 9.0.0 released last week
