### ISSUE TITLE
Allow tracking is enabled by default in show wizard - conflict with #7 of plugin guidelines

### ISSUE THREAD

**Issue by dziudek** [woothemes/woocommerce#47835]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,

I have been quite surprised when I have discovered that many of customer shops send some requests to stats.wp.com. I am pretty sure that nobody allowed this tracking with explicit consent.

Now I have discovered a reason - the tracking checkbox is checked by default in the shop wizard:
<img width="1615" alt="Screenshot 2024-05-26 at 15 21 40" src="https://github.com/woocommerce/woocommerce/assets/22004/66e1e2a1-09c7-46eb-84a3-9766c2f88562">

What is in opposite to #7 of plugin guidelines: https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#7-plugins-may-not-track-users-without-their-consent which requires EXPLICIT consent. 

For me it is a dark UX pattern, because the checkbox seems to be intentionally at the bottom, so it is also very easy to miss it on large display (to be honest I have found it in second try to diagnose the magically enable of the woocommerce_allow_tracking option).

### Expected behavior

Checkbox for tracking should be unchecked by default to be in line with plugin guidelines.
Also checkbox should be higher on the shop wizard to make the choice easier for users

### Actual behavior

Checkbox for tracking is checked by defalt what is in opposite to the plugin guidelines

### Steps to reproduce

1. Install WooCommerce
2. Go to the WooCommerce main page in dashboard
3. Check the status of checkbox in the shop wizard displayed after first WooCommerce installation

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): [REDACTED]
Site address (URL): [REDACTED]
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.18
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.37
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wpbd_
Całkowity rozmiar bazy danych: 4.19MB
Rozmiar bazy danych: 2.53MB
Rozmiar indeksu bazy danych: 1.66MB
wpbd_woocommerce_sessions: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wpbd_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_woocommerce_order_itemmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wpbd_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wpbd_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wpbd_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_actionscheduler_actions: Dane: 0.02MB + Indeks: 0.11MB + Silnik InnoDB
wpbd_actionscheduler_claims: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_actionscheduler_groups: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_actionscheduler_logs: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_commentmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_comments: Dane: 0.02MB + Indeks: 0.08MB + Silnik InnoDB
wpbd_links: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_options: Dane: 1.44MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_postmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_posts: Dane: 0.06MB + Indeks: 0.06MB + Silnik InnoDB
wpbd_term_relationships: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_termmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_terms: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_usermeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_users: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wpbd_wc_admin_note_actions: Dane: 0.05MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_wc_admin_notes: Dane: 0.06MB + Indeks: 0.00MB + Silnik InnoDB
wpbd_wc_category_lookup: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wpbd_wc_customer_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_wc_order_addresses: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wpbd_wc_order_coupon_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_wc_order_operational_data: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_wc_order_product_lookup: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wpbd_wc_order_stats: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wpbd_wc_order_tax_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_wc_orders: Dane: 0.02MB + Indeks: 0.11MB + Silnik InnoDB
wpbd_wc_orders_meta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wpbd_wc_product_attributes_lookup: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_wc_product_download_directories: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_wc_product_meta_lookup: Dane: 0.02MB + Indeks: 0.09MB + Silnik InnoDB
wpbd_wc_rate_limits: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_wc_reserved_stock: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wpbd_wc_tax_rate_classes: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wpbd_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: przez Automattic – 8.9.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dni
Level threshold: –
Log directory size: 233 B

### WC Pages ###

Strona sklepu: #7 - /sklep/
Koszyk: #8 - /koszyk/
Zamówienie: #9 - /zamowienie/
Moje konto: #10 - /moje-konto/
Regulamin: ❌ Strona nie ustawiona

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://pl.wordpress.org
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ❌ Nie zadeklarowane

### Templates ###

Overrides: /wp-content/plugins/woocommerce/templates/block-notices/error.php
/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-26 13:12:55 +00:00
Options: ✔
Notes: 58
Onboarding: completed

### Action Scheduler ###

Oczekujące: 4
Oldest: 2024-05-26 12:49:12 +0000
Newest: 2024-05-26 13:12:57 +0000

Anulowano: 1
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000

### Status report information ###

Generated at: 2024-05-26 13:28:36 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dziudek** [comment]
Hi,

Any news regarding this issue - it is marked as "high" priority, but in the meantime we had 2 major releases of WooCommerce and the issue is not touched

**Comment by adrianduffell** [comment]
Hey @dziudek, thanks for reaching out about this and apologies for the delay in the reply.

The behavior on this screen has been checked by the plugin review team and meets the plugin guidelines. As a result we don't have current plans to change it. I'll close this issue now.

You may wish to use a code-based solution to automatically opt-out of tracking on your customer's shops. I have an example plugin here: https://gist.github.com/adrianduffell/779f67b53b12d75e8608b1bb1a758203
