### ISSUE TITLE
[Enhancement]: Issue with limiting property path length to maximum 28 characters. Let's raise the bar even further.

### ISSUE THREAD

**Issue by phanduynam** [woothemes/woocommerce#47840]
### Describe the solution you'd like

Currently I am using Woocommerce 8.9.1. This makes importing from my old site to my new site problematic. I created a new site and I exported the products from the old site and imported it into the new site. So how can we increase the current limit on maximum property path length from 28 characters to more?

![image](https://github.com/woocommerce/woocommerce/assets/97380556/916a4e07-ea1e-4d1e-bec3-d4c2caa22f54)

**Comment by rrennick** [comment]
> how can we increase the current limit on maximum property path length from 28 characters to more?

@phanduynam Are you referring to categories, tags, or global attributes? 

If so, that is a limitation in taxonomy slugs in WordPress that cannot be changed without altering WP core tables.

**Comment by phanduynam** [comment]
> > how can we increase the current limit on maximum property path length from 28 characters to more?
> 
> @phanduynam Are you referring to categories, tags, or global attributes?
> 
> If so, that is a limitation in taxonomy slugs in WordPress that cannot be changed without altering WP core tables.

I'm talking about product attributes. All website components such as wordpress, plugins, themes are the latest version.

**Comment by rrennick** [comment]
@phanduynam Thanks for the follow up. The limitation is explained in https://github.com/woocommerce/woocommerce/issues/12294#issuecomment-259652262 with a reference to the limitation in WP. I'll close this as a duplicate.
