### ISSUE TITLE
[CYS - Full Composability] Scroll freeze whenever attempting to move patterns

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#47855]
**Issue Description:**

As discovered on #47322, in certain conditions that we were not able to identify the cause just yet, whenever moving patterns, it is possible for the screen to freeze, with the user being completely unable to scroll up and down in the frame:

https://github.com/woocommerce/woocommerce/assets/15730971/7bb4af27-0b8d-4c47-aad0-91a43b42afcd

While this issue can be consistently reproduced in my install, I wasn't able to reproduce it on two other brand-new separate  WordPress installs: for this reason, #47322 was approved, but we still need to keep an eye on this as there might be certain conditions to triggered it that were just not uncovered yet, given the consistency.

**Comment by gigitux** [comment]
We didn't get any report about this issue! I'm going to close this!
