### ISSUE TITLE
Add "Width" and "Height" settings to Woo blocks nested inside Group/Row/Stack/Grid

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47884]
We don't support the Width, Height, Min. Width, and Min. Height controls like most core blocks when nested inside a container block (Group, Row, Stack, Grid). Let's start by adding them to the Product Collection block. The new controls should be displayed in the Dimensions section in the Inspector panel.

<img width="366" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/753a27b3-4d48-4cd0-b386-a2efa68b6059">

**Comment by octaedro** [comment]
Hi @j111q,
I'm working on this issue, and I have a couple of questions.

By default, the `Product Collection` block wrapper has `display: block`, which prevents the `flex-grow: 1` from having any effect. Given this, I'm wondering if we should only keep the `Fill` and `Fixed`  options, as it's not possible to apply the `Fit` option.

Additionally, the issue requests adding controls for:
- Height 
- Min. Width
- Min. Height
 
However, I’m unclear on exactly what these controls should do and how they should interact. I would expect this block to only require width and a Min. Height. If the idea is to add all four controls, it would be helpful to see an example to better understand how they should function together.
