### ISSUE TITLE
Product Search block doesn't respect background and text color options

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47889]
There are color options in the Styles tab of the Product Search block, but they only work on the search button, not the input field. If the button is hidden, users can change those settings and see no effect on the canvas.

<img width="638" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/ba5df921-22ca-49ec-a448-26ad505b3402">

Let's rename these options to `Button background` and `Button text` to make it clear what they're for.

[Nice to have]

If possible, let's make the input field customizable and add the following color styles:

- Input background
- Input border
- Input text
- Input placeholder

**Comment by ccwalburn** [comment]
Adding a case where this would have helped: 8559723-zd-a8c

**Comment by octaedro** [comment]
This issue has been moved to the Gutenberg repo [#65343](https://github.com/WordPress/gutenberg/issues/65343)
