### ISSUE TITLE
Add 'Grid Spacing' to the Product Collection block

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47883]
There's currently no way to set the gutter between products in the Product Collection block. Let's solve that by adding a Grid Spacing slider in the `Layout` section. It'd only show when the `Grid` layout style is selected and work exactly the same as the Block Spacing control.

<img width="263" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/3611ccb0-696e-4c00-b221-f29bf999ffc0">

**Comment by kmanijak** [comment]
This issue will be covered in scope of https://github.com/woocommerce/woocommerce/issues/43307 that's being worked on by @ObliviousHarmony.

I'm closing this one to keep the backlog clean.
