### ISSUE TITLE
Remove the tab description from the Product Details' front-end representation

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47895]
The Product Details block displays a non-customizable large title of the currently selected tab on the front-end.

<img width="961" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/2ad6235c-f0fe-43b8-8b3d-c8f00aaf74ce">

It isn't shown in the canvas.

<img width="757" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/08c97f01-abac-40f4-8a98-86ca0e02ea36">

Let's remove the header completely. If someone needs it, they can add it directly in the block editor or in each individual product's description.

**Comment by sunyatasattva** [comment]
Let's investigate whether this happens in classic themes, because that would make the issue more delicate to work with.

**Comment by Aljullu** [comment]
> Let's investigate whether this happens in classic themes, because that would make the issue more delicate to work with.

Good point. In classic themes titles are displayed as well:

Storefront | Twenty Nineteen
--- | ---
![image](https://github.com/woocommerce/woocommerce/assets/3616980/7939c32a-48e9-4702-9363-4dd1429536f3) | ![image](https://github.com/woocommerce/woocommerce/assets/3616980/451aafcf-61f7-4fc6-b0cd-9b5892df8424)

I'm also a bit concerned about backwards-compatibility, as hiding the header in existing stores might cause some unexpected effects. So I would rather avoid changing it in existing stores, what do you think?

If we agree on that, I guess we have two paths forward:

1. Make it an option in the _Product Details_ block. In new stores, we would make titles hidden by default, but merchants would still be able to toggle the behavior. In existing stores we wouldn't change anything, but merchants would have the option to switch to the new behavior.
2. Same as above but the option is "hidden" in new stores, so new stores are forced to have titles hidden.

I lean more towards option 1 as it causes less divergence between existing and new stores.

If we agree on making it an option, we will need some texts for the editor toggle, something along these lines (@jarekmorawski is that something you can provide?):

![imatge](https://github.com/woocommerce/woocommerce/assets/3616980/0b325ffa-d907-455a-b7d8-b1074411b632)

**Comment by jarekmorawski** [comment]
I'm not sure a toggle is the right approach. A title is a design element and those should be blocks, not block _settings_. What if the title was an inner block inside Product Details? We'd add it by default, but users could delete it if they wanted (and add it back again using the inline inserter; that and any other block).

<img width="603" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/f40d74a3-5b25-46ad-abb4-8237e25ab409">

**Comment by jarekmorawski** [comment]
I had a different idea at first, but after thinking it through, I agree it should be a toggle (unless we want to add a heading block inside and connect it using the new Block Bindings API).

I'd place the toggle in a Settings section (it'd be off by default for new stores), display the heading (only the title of the description tab), make the heading editable, and display additional controls in the block toolbar when the user clicks and/or highlights the heading (heading style, justification, text formatting).

It's not much, but it'd be a good start towards a more customizable experience that's coming in the future.

![productdetails](https://github.com/woocommerce/woocommerce/assets/79307566/9ec553c6-8e80-4abd-8fbd-6f13e1937eea)

**Comment by Aljullu** [comment]
Thanks for the extra context, @jarekmorawski! Sorry for not being clear in my previous comment, I definitely agree we should move into "blockifying" the inner blocks inside the _Product Details_ block. My previous proposal was more like an "interim solution" and not the end goal for the _Product Details_ block.

> make the heading editable, and display additional controls in the block toolbar when the user clicks and/or highlights the heading (heading style, justification, text formatting)

My assumption when reading this is that if the title is customizable, it should be its own inner block, right?

Something that I think it's important to get right is to make sure this is aligned with the "end goal" we have for the _Product Details_ block. In other words, when the _Product Details_ block is fully blockified, will this generic title block (let's call it "Product Details Tab Title" block) still exist or will it be replaced by individual _Title_ blocks for each tab? If the "Product Details Tab Title" block is expected to exist once _Product Details_ have been fully blockified, I think we are good to go, but if we are planning to replace it with individual _Title_ blocks for each tab, I think we should avoid creating it. The main reason is that any block we create now will need to be maintained forever.

Blockifying the _Product Details_ block is tricky because if we allow moving inner blocks from inside to outside the tabs, we can't create generic blocks like "Product Details Tab Title", instead they should be individual _Title_ blocks that can work either inside or outside the tabs. That's why I think the "end result" of the blockified _Product Details_ block should determine which interim solution we use now.

**Comment by Aljullu** [comment]
By the way, for reference this seems to be the related issue about "blockifying the _Product Details_ block": https://github.com/woocommerce/woocommerce/issues/42277.

**Comment by jarekmorawski** [comment]
> My assumption when reading this is that if the title is customizable, it should be its own inner block, right?

That'd be ideal, but we can't do it properly unless we fully blockify Product Details. More specifically, even if the title was a block, we'd need three for each tab because users will expect to edit their content much like any block in the site editor. That won't be possible unless we implement block states or surface the tabs as block variations... this could get out of hand too quickly.

I'm thinking of an interim solution similar to the Button block in core. You can edit the label by clicking the block; it isn't an inner block, just its "content". This is the simplest solution that should provide decent customizability before we fully blockify the element.

> In other words, when the Product Details block is fully blockified, will this generic title block (let's call it "Product Details Tab Title" block) still exist or will it be replaced by individual Title blocks for each tab?

No. It will be replaced by a generic Heading block placed inside a Tabs block, which doesn't exist yet. Users will be able to customize the content (title) and appearance of each heading block individually. We wouldn't have to worry about the connection because that'll be up to the user. Tabs will be generic, meaning that they will contain any combination of blocks. For instance, if the user adds Heading and Product Description blocks, they can name the tab `Description` and edit the Heading block to say `Description`... or anything they like.

In that way, building a custom block isn't scalable and would go in vain once we officially kick off the work on blockifying the product page.

**Comment by Aljullu** [comment]
> I'm thinking of an interim solution similar to the Button block in core. You can edit the label by clicking the block; it isn't an inner block, just its "content". This is the simplest solution that should provide decent customizability before we fully blockify the element.

Gotcha, I have two follow-up questions:

1. From your message, am I understanding it right that the title should be customizable but nothing else? Ie: if the user selects the option to align the text to the right, should everything be right aligned (tabs, text content, etc.) or only the title?
2. I'm also a bit confused by "edit the label". Do you mean editing the text of the title? How would that work if in the editor we only display the first tab title (_Description_)?

Sidenote: I'm wondering whether we should decouple both tasks: one about making it possible to show/hide the title, and the other about adding support for customizability (alignment, italics, bold, etc). I don't think one depends on the other and breaking it into smaller tasks would ease getting it done this cooldown or the next one. What do you think?

> No. It will be replaced by a generic Heading block placed inside a Tabs block, which doesn't exist yet. Users will be able to customize the content (title) and appearance of each heading block individually. We wouldn't have to worry about the connection because that'll be up to the user. Tabs will be generic, meaning that they will contain any combination of blocks. For instance, if the user adds Heading and Product Description blocks, they can name the tab `Description` and edit the Heading block to say `Description`... or anything they like.

Makes a lot of sense, thanks!

**Comment by jarekmorawski** [comment]
> should everything be right aligned (tabs, text content, etc.) or only the title?

Great question. Can that be separate? For instance, if click the title, can I edit it separately from the rest of the block? If not, I'll be fine with the settings affecting the whole block. Text justification should only affect the tab title because the description cannot be edited in the canvas (text alignment can be managed in the product editor).

> I'm also a bit confused by "edit the label". Do you mean editing the text of the title? How would that work if in the editor we only display the first tab title (Description)?

Yeah, that's the difficulty I meant. I don't think we should make the title editable unless we fully blockify Product Details.

> I don't think one depends on the other and breaking it into smaller tasks would ease getting it done this cooldown or the next one. What do you think?

Agreed! In terms of priorities, the one with the showing/hiding the toggle takes priority over adding the extra formatting options.

**Comment by Aljullu** [comment]
> Great question. Can that be separate? For instance, if click the title, can I edit it separately from the rest of the block? If not, I'll be fine with the settings affecting the whole block. Text justification should only affect the tab title because the description cannot be edited in the canvas (text alignment can be managed in the product editor).

I don't think it's possible without breaking each individual part we want to be customizable into individual blocks.

> Yeah, that's the difficulty I meant. I don't think we should make the title editable unless we fully blockify Product Details.

:+1: 

> Agreed! In terms of priorities, the one with the showing/hiding the toggle takes priority over adding the extra formatting options.

Make sense, thanks @jarekmorawski!

**Comment by sunyatasattva** [comment]
> I'm also a bit confused by "edit the label". Do you mean editing the text of the title? How would that work if in the editor we only display the first tab title (Description)?

Is there anything stopping us from providing an interactive experience to the users in the editor? The tabs are just React components, what stops us from allowing the users to tab through them in the editor and edit the labels as suggested by @jarekmorawski? Is it a technical issue or a discoverability/UX issue?

---

Re: blockifying the entire experience, how would we want to proceed? We already refactored out the “Reviews” section in its own block, for example. Should we just provide each tab content as its own blockified experience as a first step and eventually wait/help a “Tabs block” to be provided upstream in Gutenberg, or do we want to offer our own solution specific to this block?

**Comment by jarekmorawski** [comment]
> The tabs are just React components, what stops us from allowing the users to tab through them in the editor and edit the labels as suggested by @jarekmorawski? Is it a technical issue or a discoverability/UX issue?

We'd do it, but not without a proper Tabs block that supports renaming tab titles, reordering, adding and deleting tabs, etc. Imho, it should be a core (or core-adjacent) block that we could use in patterns and page templates across all Woo pages.

For example, if we let users change the tab title, they should be able to rename the tab, too. Or, when they add the reviews block, they may want to get rid of the "Reviews" tab in the Product Details block. The scope keeps growing, so I'd like us to start small and fix the issue at hand before blowing up the Product Details block into smaller pieces and move them inside the new Tabs block.
