### ISSUE TITLE
Products get listed in incompatible_with_feature plugin screen due to cart_checkout_blocks

### ISSUE THREAD

**Issue by gedex** [woothemes/woocommerce#47920]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There are some features that are _marked_ as legacy here:

https://github.com/woocommerce/woocommerce/blob/09670be305f64460d32bd23b91e3aba6ef8cb163/plugins/woocommerce/src/Internal/Features/FeaturesController.php#L163-L164

however, `cart_checkout_blocks` doesn't have `is_legacy => true` like others.

https://github.com/woocommerce/woocommerce/blob/09670be305f64460d32bd23b91e3aba6ef8cb163/plugins/woocommerce/src/Internal/Features/FeaturesController.php#L206-L211

This cause Woo products (including Woo Update Manager) get listed in `/wp-admin/plugins.php?plugin_status=incompatible_with_feature&feature_id=all`

<img width="550" alt="image" src="https://github.com/woocommerce/woocommerce/assets/78313/758e3736-8614-417a-ae50-d9041da9a277">

The compatibility check for WUM doesn't show any incompatible features, only uncertain.

```
$feature_controller = wc_get_container()->get( \Automattic\WooCommerce\Internal\Features\FeaturesController::class )

$feature_controller->get_compatible_features_for_plugin( 'woo-update-manager/woo-update-manager.php' )

=> array(3) {
  ["compatible"]=>
  array(1) {
    [0]=>
    string(19) "custom_order_tables"
  }
  ["incompatible"]=>
  array(0) {
  }
  ["uncertain"]=>
  array(7) {
    [0]=>
    string(9) "analytics"
    [1]=>
    string(14) "new_navigation"
    [2]=>
    string(20) "product_block_editor"
    [3]=>
    string(20) "cart_checkout_blocks"
    [4]=>
    string(11) "marketplace"
    [5]=>
    string(17) "order_attribution"
    [6]=>
    string(16) "hpos_fts_indexes"
  }
}
```

If I set `is_legacy => true` on `cart_checkout_blocks`, then the list doesn't show WUM and any other Woo products.

### Expected behavior

Not sure if this is expected. Ideally, it shouldn't show in the `incompatible_with_feature` screen.

### Actual behavior

WUM shown in `incompatible_with_feature` screen.

### Steps to reproduce

* Install and activate [WUM](https://woocommerce.test/product-download/woo-update-manager)
* Go to `/wp-admin/plugins.php?plugin_status=incompatible_with_feature&feature_id=all`

### WordPress Environment

wp-env from this repo

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Thanks for reporting this issue, @gedex. I went ahead and created #47988 to address this issue.

**Comment by nielslange** [comment]
Hello @gedex, while reviewing #47988, @opr and I realised that my fix was the wrong approach. Extensions can explicitly declare whether they are compatible or incompatible. Adding `'is_legacy' => true` to `cart_checkout_blocks` would instantly ignore existing declarations of all extensions. The reason for that is, that `'is_legacy' => true` bypasses the compatibility check. 

Instead, compatibility with `cart_checkout_blocks` should be declared by making the following call within the WooCommerce.com Update Manager:
```php
FeaturesUtil::declare_compatibility( 'cart_checkout_blocks', __FILE__, true );
```

On https://developer.woocommerce.com/2023/11/06/faq-extending-cart-and-checkout-blocks/#:~:text=Declaring%20Compatibility&text=If%20your%20plugin%20extends%20the,gateway%20compatibility%20are%20determined%20separately., you can find further information regarding `declare_compatibility`.

I created https://github.com/Automattic/woo-update-manager/issues/11 for tracking this issue. As this issue needs to be addressed within the corresponding extension, I'm going to close this issue.

**Comment by gedex** [comment]
I think core needs to make the messaging obvious on which feature is incompatible. Currently, there's no notice and clue without diving into the `Automattic\WooCommerce\Internal\Features\FeaturesController`. In my case, I had to check each feature ID one by one.

**Comment by nielslange** [comment]
> I think core needs to make the messaging obvious on which feature is incompatible.

I understand the need for clarity in messaging about feature compatibility. However, it's a bit complex due to the varied compatibility across different extensions. For instance, [WooCommerce One Page Checkout](https://woocommerce.com/products/woocommerce-one-page-checkout/) does not work with the Cart and Checkout blocks, but is compatible with HPOS. The incompatibility is explicitly declared in its codebase [here](https://github.com/woocommerce/woocommerce-one-page-checkout/blob/e2b6bf8c2f5818bcc4e5fbf79ea39654e16df0f1/woocommerce-one-page-checkout.php#L35-L44).

As previously mentioned, using `is_legacy` set to `true` can bypass these compatibility checks. This means extensions that have declared incompatibility with the Cart and Checkout blocks would no longer trigger incompatibility flags.

> Currently, there's no notice and clue without diving into the `Automattic\WooCommerce\Internal\Features\FeaturesController`. In my case, I had to check each feature ID one by one.

This sounds frustrating. Can you share more about the challenges you faced when checking each feature ID? What were you hoping to see, instead of manually checking each feature ID?

**Comment by senadir** [comment]
I'm opening this back, because as far as I understand it correctly, plugins will now show as incompatible by default, which is not what we're looking for.
