### ISSUE TITLE
Unify styling between taxonomy blocks

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47922]
On the product page, only tags and categories are styled similarly. The SKU and Brand blocks have a different structure and functionality. For instance, it isn't possible to change the `SKU:` prefix or change the appearance of the actual SKU value (the default appearance is different from tags and categories). The Brands block doesn't have a prefix like the other blocks.

<img width="647" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/99d0d841-3f70-488e-80e8-b64a79a3c364">

Let's fix that by:

- Making each block work exactly the same as Tags and Categories, meaning that the user should be able to add and remove a prefix and a suffix.
- The default prefix for the SKU block is `SKU:`. For Brands, it's `Brand:`. There's no default suffix.
- Let's rename `Brands` to `Product Brand` to align with the other blocks.
- The SKU value uses the same appearance as the other blocks. Users can highlight it in the canvas and change typography settings using the toolbar and the Inspector.

**Comment by albarin** [comment]
@jarekmorawski Do we have a `Brands` block? I'm seeing only Categories, Tags, and SKU in the `Product Meta` 🤔 
<img width="286" alt="Screenshot 2024-08-28 at 15 14 59" src="https://github.com/user-attachments/assets/f03e716e-4eb9-42e5-9ffc-5b1089be8c42">

**Comment by j111q** [comment]
Hi @albarin 👋  Taking over for Jarek, thanks for flagging this. 
We do have a Brands block but it doesn't appear by default, you have to have the Brands extension and then you can add the block.  

To me, the improvements highlighted above might actually be part of the More in Core work of rolling Brands into Woo Core -- so let me tag @jimjasson who is leading that project, so he can chime in on whose team should tackle this work.
