### ISSUE TITLE
Add support for other units for height and width controls

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47927]
All height and width controls in the Product Image block currently use pixels, which can be restraining at times. It's also misaligned with the direction core blocks have taken where the user can switch between pixels, ems, rems, vw, percentages, etc.

Let's add support for the additional units for each height, width, and other dimension-related control in the block. This should affect the Product Gallery (Beta) block, too.

**Comment by roykho** [comment]
After some investigation, we found that core blocks also don't have this feature. Without having to create our own custom solution, we feel this isn't worth the effort for now.

**Comment by jarekmorawski** [comment]
I found a [WidthHeightTool component](https://wordpress.github.io/gutenberg/?path=/docs/blockeditor-private-apis-dimensionstool-widthheighttool--docs) that we could use. I'll reopen the issue to keep it in our backlog.

**Comment by roykho** [comment]
[WidthHeightTool component](https://wordpress.github.io/gutenberg/?path=/docs/blockeditor-private-apis-dimensionstool-widthheighttool--docs) is a private API though.

**Comment by jarekmorawski** [comment]
I reached out to the Gutenberg team and learned that there's another component we can use: [UnitControl](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-unitcontrol--docs).
