### ISSUE TITLE
Hide the quantity input field when the product is set to allow only 1 piece per order 

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47930]
Merchants can set up a product in a way that restricts the shopper from buying more than one item in an order, but we still display the quantity field on the front-end.

<img width="590" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/46ced1f7-9c5f-4c49-b7ba-5840a04a5084">

Let's hide it to reduce friction and confusion and draw the shopper's attention to the add-to-cart button. We should also remove the quantity selectors from the cart and checkout blocks.

**Comment by roykho** [comment]
I had a look at this and it seems the quantity field is already hidden in both mentioned cases when the `Limit purchases to 1 item per order` is enabled.

Image refs:

![Google Chrome - Cart – woo-blocks-dev 2024-08-16 at 10 03 05 AM](https://github.com/user-attachments/assets/a3877f93-7913-45b8-8403-0c07bfbaa6cd)
![Google Chrome - Adidas – woo-blocks-dev 2024-08-16 at 10 03 44 AM](https://github.com/user-attachments/assets/37977b2d-6eb0-4933-b2ca-f727e32e80e1)

**Comment by octaedro** [comment]
I couldn't reproduce the described behavior. After enabling the `Limit purchases to 1 item per order` check, the quantity field was hidden in both cases:

![Screenshot 2024-08-27 at 1 15 59 PM](https://github.com/user-attachments/assets/a43aa752-8833-4fa3-af8d-3e87cf5f4876)

and

![Screenshot 2024-08-27 at 1 16 28 PM](https://github.com/user-attachments/assets/9ba9e5b6-9896-4893-a481-d65cdcd5b2be)

I'm going to close this issue. //cc @jarekmorawski
