### ISSUE TITLE
Product Collection: analyse the All Products extensibility in comparison to PC block

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#47959]
**Issue Description:**
Before we soft-deprecate All products block, let's verify the existing extensibility points in that block and assess usage across extensions.

**Goal:**
Analyze of:
    - existing extensibility points
    - usage of extensibility points across extensions
    - answer the question: Can All Products be safely hidden from the inserter and "replaced" by Product Collection
        - if yes: follow with that (separate issue: https://github.com/woocommerce/woocommerce/issues/43410)
        - if not: provide a plan on how PC can support such extensibility points OR what are the alternatives.

**Comment by imanish003** [comment]
> if yes: follow with that

@kmanijak Just to confirm, It also includes updating documentation & an announcement post. Right?

**Comment by kmanijak** [comment]
> @kmanijak Just to confirm, It also includes updating documentation & an announcement post. Right?

No, there's a separate issue covering that (soft-deprecation + docs update + announcement post). I added that to issue description so it's clear, apologies for confusion :)

**Comment by kmanijak** [comment]
The outcome of the analysis with next steps recommendations is gathered in GitHub discussion: https://github.com/woocommerce/woocommerce/discussions/48814.

There are three issues that would cover the remaining extensibility of PC block:
- https://github.com/woocommerce/woocommerce/issues/48861
- https://github.com/woocommerce/woocommerce/issues/48862
- https://github.com/woocommerce/woocommerce/issues/42924
