### ISSUE TITLE
[Flaky] merchant/users-create.spec.js

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#47957]
can create a new Shop manager 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9286687075

**Comment by lanej0** [comment]
can create a new Shop manager 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9286687075

**Comment by veljkho** [comment]
This test was flaky recently and for a reason. I am reopening it to fix flakiness so it doesn't occur in the future.
