### ISSUE TITLE
Product Collection: Add validation for `registerProductCollection` arguments

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#47963]
**Issue description:**  
3PD should be able to register new collections. Based on [woocommerce/woocommerce#47345](https://github.com/woocommerce/woocommerce/discussions/47345) we should expose an experimental API to do that. In order to make the function robust we should introduce the validation for `registerProductCollection` arguments.

Here is how the function could look like:

```ts
__experimentalRegisterProductCollection(
	title,
	description,
	icon,
	...,
	preview: {
		handlePreviewState,
		initialState: {
			isPreview: true,
			previewMessage: 'This is in preview mode',
		},
	},
)
```

**Goal:**
- Implement validation in registerProductCollection function for its arguments, especially preview

**Comment by imanish003** [comment]
Update: I made some changes to the description of the issue.
