### ISSUE TITLE
Product Collection: expose experimental `registerProductCollection` for 3PDs

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#47962]
**Issue description:**
3PD should be able to register new collections. Based on https://github.com/woocommerce/woocommerce/discussions/47345 we should expose an experimental API to do that.

⚠️ This is just the first iteration of such API so has to be marked as experimental and is subject to changes!

**Goal:**
- Expose `registerProductCollection` to 3PD
- Make sure API is marked as experimental!

**Comment by imanish003** [comment]
A decision was made in [this GitHub discussion comment](https://github.com/woocommerce/woocommerce/discussions/47345#discussioncomment-9567828) that we will expose `registerProductCollection` using `@woocommerce/blocks-registry` package.
