### ISSUE TITLE
Product Filters Redesign > Overlay Template Part: Create the Product Filters Overlay Block

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#47977]
## Description
The Product Filters Overlay block is the only block, by default, within the Filters Overlay Template Part. It’s basically a container block with some layout-related settings and a link to the main Product Filters block in the block details card at the top.

## Expected Behavior:

- The title of the block is "Product Filters Overlay".
- The block description is "Display product filters in an overlay on top of a page."
- The block will only exist within the Filters Overlay template part.
- In the Style tab, users can decide how the overlay should be displayed on the front-end.
  - Full-screen will show it as a new layer on top of the page. The template part will fill up the whole screen.
  - Drawer will show it as a modal that only partially covers the rest of the page. The overlay will show on the left or right side of the screen (it’ll always be full-screen on mobile).
- There are two blocks inside the Product Filters Overlay block: Product Filters and Navigation.
  - Product Filters is a copy of the main Product Filters block (it’s useful if the main one is set to always display the overlay) and the two are in full sync. We display a badge in the Filters tab to communicate that to the user.
  - Users can’t add or remove filters in the overlay when the blocks are synced. They only do that in the main block.
  - Users can click the ellipsis button to reveal the Unsync option. Clicking it will sever the connection with the main block, meaning that users can manage filters in the overlay independently.
  - Users can restore the connection by selecting Sync again from the ellipsis menu.
  - When the block is disconnected, we also show a Clear all option. Clicking it removes all other filters (but not other blocks like Heading or Paragraph).

## Reference images

| Product Filters Overlay block |
|--------|
| ![image](https://github.com/woocommerce/woocommerce/assets/20469356/a2f97ca6-db33-4151-8c1b-71345d281985) | 

| Product Filters Overlay block - Style settings - Full Screen option selected|
|--------|
| ![image](https://github.com/woocommerce/woocommerce/assets/20469356/57da3e71-7afa-40c0-8c85-35029ddb4a52) | 

| Product Filters Overlay block - Style settings - Drawer option selected|
|--------|
| ![image](https://github.com/woocommerce/woocommerce/assets/20469356/53dc095d-79b0-4961-9c17-eda1e653c7cd) | 

| Product Filters Overlay block - Synced statuses|
|--------|
| ![image](https://github.com/woocommerce/woocommerce/assets/20469356/837c1cb0-00be-420d-ac95-39d21be49999) |

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce/pull/48472
