### ISSUE TITLE
checkout form not working

### ISSUE THREAD

**Issue by HuzaifaAzhar09** [woothemes/woocommerce#47978]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

checkout form not working
![image](https://github.com/woocommerce/woocommerce/assets/161307201/b76a45e6-9ec0-4971-a936-7dd7d038842e)

### Expected behavior

![image](https://github.com/woocommerce/woocommerce/assets/161307201/31293fe6-8991-41a5-b759-e30cf954de80)

### Actual behavior

![image](https://github.com/woocommerce/woocommerce/assets/161307201/872dd248-afe5-4057-a613-5bf845bcdaf1)

### Steps to reproduce

![image](https://github.com/woocommerce/woocommerce/assets/161307201/15c7e4da-38e3-406a-9639-86236244a454)

### WordPress Environment

![image](https://github.com/woocommerce/woocommerce/assets/161307201/dc5436fd-f7ba-43c8-acd4-a2986431388b)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by HuzaifaAzhar09** [comment]
please solve this issue

**Comment by adimoldovan** [comment]
Thank you @HuzaifaAzhar09 for reporting this issue. In order for use to make better sense of it, can you please fill out the required field of the report form? More specifically, clear steps to reproduce, and the [WooCommerce System Status Report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/)
