### ISSUE TITLE
Fatal error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:371

### ISSUE THREAD

**Issue by jmillermilehighideas** [woothemes/woocommerce#47974]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This critical error was triggered when heading into wp-admin/edit.php?post_type=product, it suddenly appeared out of the blue. I haven't made any changes, i deactivated all the plugins except Woocommerce, and switched to 2024 theme. and it still being triggered.

knowing that i had this being triggered on the front-end with some Widgets related to ShopEngine plugin. for example the advanced search widget. However after i removed this widget from the front-end, the website is working fine. but right now i can't access the all products page to manage my store.

### Expected behavior

i expect to be able to see the all products page.

### Actual behavior

This critical error was triggered when heading into wp-admin/edit.php?post_type=product, it suddenly appeared out of the blue. I haven't made any changes, i deactivated all the plugins except Woocommerce, and switched to 2024 theme. and it still being triggered.

### Steps to reproduce

1- go to Admin Dashboard.
2 - Click on All products.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://3otoory.com
Site address (URL): https://3otoory.com
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.28
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.44-cll-lve
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wpoa_
Total Database Size: 95.89MB
Database Data Size: 89.32MB
Database Index Size: 6.57MB
wpoa_woocommerce_sessions: Data: 5.52MB + Index: 0.14MB + Engine InnoDB
wpoa_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpoa_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpoa_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpoa_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpoa_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_actionscheduler_actions: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wpoa_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_actionscheduler_logs: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wpoa_aioseo_blc_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_aioseo_blc_links: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wpoa_aioseo_blc_link_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_aioseo_blc_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpoa_aioseo_blc_posts: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpoa_aioseo_cache: Data: 0.20MB + Index: 0.03MB + Engine InnoDB
wpoa_aioseo_crawl_cleanup_blocked_args: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_aioseo_crawl_cleanup_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_aioseo_notifications: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
wpoa_aioseo_posts: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wpoa_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_chaty_contact_form_leads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wpoa_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_fluentform_entry_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_fluentform_form_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_fluentform_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_fluentform_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_fluentform_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_hfcm_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpoa_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_nextend2_section_storage: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
wpoa_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_nextend2_smartslider3_sliders: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wpoa_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_nextend2_smartslider3_slides: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wpoa_options: Data: 7.02MB + Index: 0.23MB + Engine InnoDB
wpoa_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_postmeta: Data: 43.28MB + Index: 3.02MB + Engine InnoDB
wpoa_posts: Data: 28.47MB + Index: 0.50MB + Engine InnoDB
wpoa_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_term_relationships: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wpoa_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpoa_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wpoa_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpoa_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpoa_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wpoa_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpoa_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpoa_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpoa_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpoa_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpoa_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wpoa_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_woof_front_builder: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoa_woof_sd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_woof_sd_presets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wpoa_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpoa_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpoa_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field-group: 1
acf-taxonomy: 1
attachment: 1024
br_filters_group: 1
br_product_filter: 4
custom_css: 1
customize_changeset: 66
e-landing-page: 1
elementor_library: 1
elementor-hf: 6
filter-field: 5
filter-set: 1
nav_menu_item: 26
page: 21
post: 3
product: 350
revision: 1266
shop_coupon: 1
shop_order: 62
shop_order_refund: 1
shopengine-template: 11
um_directory: 1
um_form: 3
wp_global_styles: 1
wp_navigation: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (27) ###

Advanced Custom Fields: by WP Engine – 6.3.0
All in One SEO: by All in One SEO Team – 4.6.3
Chaty: by Premio – 3.2.4
Decorator - WooCommerce Email Customizer: by WebToffee – 1.2.9
Elementor: by Elementor.com – 3.21.7
ElementsKit Lite: by Wpmet – 3.1.4
Essential Addons for Elementor: by WPDeveloper – 5.9.22
Exclusive Addons Elementor: by Exclusive Addons – 2.6.9.7
Filter Everything — WooCoomerce Product & WordPress Filter: by Andrii Stepasiuk – 1.8.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.26.0
Header Footer Code Manager: by 99robots – 1.1.37
Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.34

Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
Jetpack Boost: by Automattic - Jetpack Site Speed team – 3.3.1
Jetpack: by Automattic – 13.4.3
Qi Addons For Elementor: by Qode Interactive – 1.7.1
ShopEngine: by Wpmet – 4.6.4
Smart Slider 3: by Nextend – 3.5.1.23
Sticky Header Effects for Elementor: by Rwattner – 1.6.11
Templately: by Templately – 3.0.6
Ultimate Member: by Ultimate Member – 2.8.6
Under Construction: by WebFactory Ltd – 4.00
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.3

W3 Total Cache: by BoldGrid – 2.7.2
WooCommerce: by Automattic – 8.9.1
WP Mail SMTP: by WP Mail SMTP – 4.0.1
WPForms Lite: by WPForms – 1.8.8.3

### Inactive Plugins (7) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.1
Broken Link Checker by AIOSEO: by All in One SEO Team – 1.2.0
Hello Dolly: by Matt Mullenweg – 1.7.2
OptinMonster: by OptinMonster Popup Builder Team – 2.16.0
Prisna GWT - Google Website Translator: by Prisna – 1.4.6
Weglot Translate: by Weglot Translate team – 4.2.1
WP Debugging: by Andy Fragen – 2.11.24

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.9.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EGP (EGP)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-29 16:49:39 +00:00
Options: ✔
Notes: 91
Onboarding: completed

### Action Scheduler ###

Complete: 398
Oldest: 2024-04-28 17:53:45 +0000
Newest: 2024-05-29 16:53:55 +0000

Failed: 25
Oldest: 2023-07-23 13:08:31 +0000
Newest: 2024-05-29 16:49:53 +0000

Pending: 8
Oldest: 2024-05-29 17:08:55 +0000
Newest: 2024-06-04 12:09:58 +0000

### Status report information ###

Generated at: 2024-05-29 17:08:50 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pdesaulniers-vertisoft** [comment]
FWIW, we had the same issue. In our case, we think it was caused by the "Post Duplicator" feature in `Exclusive Addons Elementor`.

When duplicating a product, this plugin stores product metas as 1-element arrays instead of simple strings. For example: `_manage_stock` => `a:1:{i:0;s:3:"yes";}` instead of `_manage_stock` => `yes`

This causes the `read_product_data` function to crash for duplicated products.
