### ISSUE TITLE
Product Filters Redesign: Investigate Synced Pattern Technical Details

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#48019]
## Description
This is a spike to understand some technical details regarding the Synced Patterns.

ref: p1715080013574219/1714665846.469939-slack-C05UMTA7W0P

## Expected result:

- A P2 post answering the following questions:
  - Is there a native API for plugins to register a synced pattern?
  - Can welcome tours be offered for a synced pattern/template part focused view?

**Comment by roykho** [comment]
The conclusion of this spike:

- A P2 was posted about the synced pattern. The summary is that there currently isn't a way to programmatically create a synced pattern.
- Welcome tours can be created to guide first time users.
