### ISSUE TITLE
Product Filters Redesign > Wrapper Block Settings: Add the "Block Spacing" setting 

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#48022]
## Description
The "Product Filters" wrapper block contains a setting that allows merchants to set the spacing between the inner blocks. That can be a little bit tricky since each inner block will have to respect that setting on the Editor and on the front end.

## Expected Behavior:

- When a merchant edits the block spacing, that should be reflected on the frontend.
- When a merchant edits the block spacing, that should be reflected on the editor.

## Reference images

| Product FIlters Wrapper Block Settings |
|--------|
| ![image](https://github.com/woocommerce/woocommerce/assets/20469356/2d8cc19c-f712-4803-8b3c-96725261f727) |

**Comment by dinhtungdu** [comment]
> That can be a little bit tricky since each inner block will have to respect that setting on the Editor and on the front end.

@thealexandrelara do you mean the inner blocks will inherit the spacing setting and apply to their inner blocks as well? For example if the block spacing of `Product Filters` is `3`, then the block spacing of `Attributes` is also `3`, and we have to add spacing (and layout) support to the `Attributes` block as well?

**Comment by thealexandrelara** [comment]
> @thealexandrelara do you mean the inner blocks will inherit the spacing setting and apply to their inner blocks as well? For example if the block spacing of `Product Filters` is `3`, then the block spacing of `Attributes` is also `3`, and we have to add spacing (and layout) support to the `Attributes` block as well?

Good question! I believe when I wrote this issue, that is what I was thinking about; however, for now, I believe that just adding the block spacing to each of the direct children would be enough. Otherwise, it would be too much complex and difficult to reason about the end result.

**Comment by dinhtungdu** [comment]
@thealexandrelara thank you for your confirmation! I also don't think we should apply the same spacing to children of inner block, as they should have a smaller spacing, which can be controlled by heading/filter option block styling setting. The #48429 is ready to review then.
