### ISSUE TITLE
class-wc-product-variation.php -> get_permalink()  ; array_filter() expects parameter 1 to be array

### ISSUE THREAD

**Issue by sultank1** [woothemes/woocommerce#48033]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

array_filter() expects parameter 1 to be array;

function get_permalink..  following is returning string when it should be array ;;; 
reason is the first condition that uses $item_object  and item object has string not array ;;;
it works fine when if i manually disable the first condtion "if ( ! empty( $item_object['variation'] ) ) {"

SUGGESTED FIX 
change `if ( ! empty( $item_object['variation'] ) ) {` to `if ( ! empty( $item_object['variation'] )  and is_array( $item_object['variation'] ) ) {`

line# 164 ;  
		```
if ( ! empty( $item_object['variation'] ) ) {
			$data = $item_object['variation'];
		} elseif ( ! empty( $item_object['item_meta_array'] ) ) {
			$data_keys   = array_map( 'wc_variation_attribute_name', wp_list_pluck( $item_object['item_meta_array'], 'key' ) );
			$data_values = wp_list_pluck( $item_object['item_meta_array'], 'value' );
			$data        = array_intersect_key( array_combine( $data_keys, $data_values ), $this->get_variation_attributes() );
		} else {
			$data = $this->get_variation_attributes();
		}
```

### Expected behavior

verify if ( $item_object['variation'] ) is array 

### Actual behavior

does not verify if ( $item_object['variation'] ) is array 

### Steps to reproduce

no idea 

### WordPress Environment

<html>
<body>

PHP version: |   | 8.2.18
-- | -- | --

</body>
</html>

<html>
<body>

WooCommerce version: |   | 8.9.1
-- | -- | --

</body>
</html>

<html>
<body>

WordPress version: |   | 6.5.3
-- | -- | --

</body>
</html>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kmanijak** [comment]
Hi @sultank1, thanks for raising this. Unfortunately, I'm not sure I understand the issue.

Can you provide the steps to get the error you mentioned in the title (`array_filter() expects parameter 1 to be array`)? What problem would that additional validation solve?

**Comment by sultank1** [comment]
Yeah 

i had created variables  products and i did not select from existing attributes values and created new one..

I think the issues is dues to the fact i had not used global attributes and created new attribute values right on variable product... 
By global attribute i mean the ones created on /wp-admin/edit.php? post_type=product&page=product_attributes

I somehow causes issue on thankyou order page and it crashes.

**Comment by sultank1** [comment]
> Hi @sultank1, thanks for raising this. Unfortunately, I'm not sure I understand the issue.
> 
> Can you provide the steps to get the error you mentioned in the title (`array_filter() expects parameter 1 to be array`)? What problem would that additional validation solve?

This was the solution i had to used for that time to fix the issue... As it was empty array and it did not made proper checks...

Anyways in end for more permanent solution i removed the get_permalink for variable products on thankyou order page template file

**Comment by albarin** [comment]
Hi @sultank1, thanks again, unfortunately, we have not been able to reproduce this issue, we can see the order page without any error.
It would be really useful if you could provide step-by-step instructions on how to trigger this error so we can try to reproduce it and fix it. You could include screenshots/video recordings so we can see them as well.
Thanks a lot!

**Comment by tjcafferkey** [comment]
I am also unable to reproduce this issue. If you find that you're still experiencing this issue feel free to reopen it with additional information to help us reliably reproduce this.
