### ISSUE TITLE
Clear frontend caches when changing coming soon mode in hosts

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#48032]
### Issue Description:

In https://github.com/woocommerce/woocommerce/discussions/47418#discussioncomment-9539054, @cre8tivediva observed that frontend was cached and did not reflect a coming soon mode change in WP Engine site.

> I just created a brand new staging on WPE. And I noticed after going back and forth toggling on and off settings, that there's caching going on. I am Live testing in Firefox but checking the site in FireFox Incognito. And when I toggle the settings - I have to clear the WPE caching for the pages to go offline or to come back online. More testing might be needed on various hosting platforms. Will there be a way to cache exclude any functionality in this? I'm going to turn off "object cache" to see if that helps.

We'll need to investigate and implement hosts-specific cache busting mechanisms to ensure coming soon mode is reflected on settings change.

### Acceptance criteria:

1. Investigate WPE and Siteground host behaviour on coming soon mode changes
2. If possible, integrate with cache invalidation for coming soon mode changes

**Comment by chihsuan** [comment]
Closing this issue as:

We've added direct cache expiration for hosts in https://github.com/woocommerce/woocommerce/issues/48515 and we have also been working with hosts to ensure that coming soon mode changes are reflected in the frontend.
