### ISSUE TITLE
[WC Beta Tester] Bug report for version "8.9.1"

### ISSUE THREAD

**Issue by Neibye** [woothemes/woocommerce#48049]
**Describe the bug**
I am not able to upgrade woocommerce to the new 9.0.0 beta version. I need to do this to be able to test if the new update will work with my shop and my integrations.

**To Reproduce**
1. Go to 'Switch versions'
2. Click on '9.0.0-beta.2'
3. Scroll down to 'Bottom of page'
4. Click on Switch version
5. Nothing happens.

**Screenshots**

**Expected behavior**
That my WooCommerce version gets updated to 9.0.0-beta.2 so that I can test the new version.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

</details>

**Comment by rrennick** [comment]
@Neibye Thanks for reporting the issue. I was able to update to `9.0.0-beta.2` in a test install using the beta tester plugin. Could you retry this with all other plugins deactivated and switched to a default theme?

**Comment by Neibye** [comment]
> @Neibye Thanks for reporting the issue. I was able to update to `9.0.0-beta.2` in a test install using the beta tester plugin. Could you retry this with all other plugins deactivated and switched to a default theme?

I found the problem with the support. I had to change theme from Tsubaki to Storefront and then it worked.
