### ISSUE TITLE
issue with 

### ISSUE THREAD

**Issue by rccess** [woothemes/woocommerce#48086]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

i have issue with API in php 8.2 version, working fine with php 7.4

-----------------------------------------
https://www.domain.com/wc-api/v3/orders/?consumer_key=ck_63e93bXXXXXXXXXdc93b9c71eeab19cdfe51310f02&consumer_secret=cs_a490064XXXXXXXXX9b7ff22eea5b46de3b4af5da
-----------------------------------------
<br />
<b>Fatal error</b>: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class
WacR_Rest_Api does not have a method &quot;wacr_load_apifile&quot; in
/home/u930288886/domains/domain.com/public_html/wp-includes/class-wp-hook.php:324
Stack trace:
#0 /home/u930288886/domains/domain.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#1 /home/u930288886/domains/domain.com/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#2
/home/u930288886/domains/domain.com/public_html/wp-content/plugins/woocommerce/includes/legacy/class-wc-legacy-api.php(252):
do_action()
#3
/home/u930288886/domains/domain.com/public_html/wp-content/plugins/woocommerce/includes/legacy/class-wc-legacy-api.php(174):
WC_Legacy_API-&gt;includes()
#4 /home/u930288886/domains/domain.com/public_html/wp-includes/class-wp-hook.php(324):
WC_Legacy_API-&gt;handle_rest_api_requests()
#5 /home/u930288886/domains/domain.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#6 /home/u930288886/domains/domain.com/public_html/wp-includes/plugin.php(565): WP_Hook-&gt;do_action()
#7 /home/u930288886/domains/domain.com/public_html/wp-includes/class-wp.php(418): do_action_ref_array()
#8 /home/u930288886/domains/domain.com/public_html/wp-includes/class-wp.php(813): WP-&gt;parse_request()
#9 /home/u930288886/domains/domain.com/public_html/wp-includes/functions.php(1336): WP-&gt;main()
#10 /home/u930288886/domains/domain.com/public_html/wp-blog-header.php(16): wp()
#11 /home/u930288886/domains/domain.com/public_html/index.php(17): require('/home/u93028888...')
#12 {main}
thrown in <b>/home/u930288886/domains/domain.com/public_html/wp-includes/class-wp-hook.php</b> on line <b>324</b><br />

### Expected behavior

i have issue with API in php 8.2 version, working fine with php 7.4

### Actual behavior

htting error on php 8.2 version

### Steps to reproduce

test the API with php 8.2 version

### WordPress Environment

Server architecture | Linux 5.14.0-427.16.1.el9_4.x86_64 x86_64
Web server | LiteSpeed
PHP version | 8.2.18 (Supports 64bit values)
PHP SAPI | litespeed
PHP max input variables | 5000
PHP time limit | 300
PHP memory limit | 512M
Max input time | 240
Upload max filesize | 256M
PHP post max size | 256M
cURL version | 7.76.1 OpenSSL/3.0.7
Is SUHOSIN installed? | No
Is the Imagick library available? | Yes
Are pretty permalinks supported? | Yes
.htaccess rules | Custom rules have been added to your .htaccess file.
Current time | 2024-06-01T04:37:33+00:00
Current UTC time | Saturday, 01-Jun-24 04:37:33 UTC
Current Server time
-----------------------------------------

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @rccess,

It's not clear what's happening but it seems like it might relate to a third party plugin:

```
Uncaught TypeError: call_user_func_array(): Argument https://github.com/woocommerce/woocommerce/issues/1 ($callback) must be a valid callback, class WacR_Rest_Api does not have a method "wacr_load_apifile"
```

Do you know which plugin ('wacr_rest_api') this might be? Or could you share your list of active plugins and we'll see if we spot any likely candidates?

Regardless, I'm not sure we are going to be able to provide too much help if the problem cannot be replicated using WooCommerce alone.
