### ISSUE TITLE
Impossible to validate coupons restricted to an email when placing orders without account

### ISSUE THREAD

**Issue by danieleperilli** [woothemes/woocommerce#48089]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This recent change [Validate and present custom error for not in allowed emails coupons #43872](https://github.com/woocommerce/woocommerce/pull/43872) makes it impossible to apply a coupon restricted to an email, when the customer has not an account and purchasing as a guest is allowed.

The only workaround that I found is to comment the line below in the your source code:
![screen2024-06-02-000472](https://github.com/woocommerce/woocommerce/assets/9072177/a586ae10-6982-40e1-8f1f-9dc981e7696b)

### Expected behavior

Prior to mentioned change, we were able to use a coupon restricted to an email address even when the user was not authenticated, as validation was done after the order was submitted and the billing email address was used to validate it.

### Actual behavior

Currently, after entering a valid coupon that is limited to an email address, we receive a validation error when the user is not authenticated, also if the allowed email address has been inserted in the billing email address field.

### Steps to reproduce

1. Allow Guest checkout
2. Create a coupon restricted to an email
![screen2024-06-02-000474](https://github.com/woocommerce/woocommerce/assets/9072177/ee648fdd-877c-4458-b534-106e295d3e54)

3. Add a product to the checkout
4. Enter a coupon code that is restricted to an email address -> Here you receive a validation error, regardless of the email in the billing email address field
![screen2024-06-02-000473](https://github.com/woocommerce/woocommerce/assets/9072177/0fbaace5-e167-46bd-aed9-186a9ef4628f)

### WordPress Environment

WordPress 6.5.3
WooCommerce 8.9.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
When applying an email bound coupon, the email is still sent with the request to validate against it. But I see your point of view, @wavvves What was the reason we moved to validating at applying the coupon vs validating at the time of placing the order?

**Comment by wavvves** [comment]
@senadir we still validate the coupon on placing the order to ensure the correct email is provided at the most critical point. The reasoning for this change is to only allow customers to apply a discount they are entitled to, and not see it being removed when placing the order. Before that, the coupon could always be added.

@danieleperilli I will investigate this, as this is not supposed to happen. The email is submitted along the coupon to check ownership, both on cart and checkout. Before I dig into this, are you using a dev build of woocommerce? Some javascript files might not be properly reloading without running "pnpm clean" before building again.

**Comment by senadir** [comment]
if on a guest account and without adding an email, you add a coupon, it will fail.

**Comment by wavvves** [comment]
> if on a guest account and without adding an email, you add a coupon, it will fail.

That is the expected behavior. Before, the coupon would be added and the discount shown, ultimately being removed when placing the order if the billing email didn't own the coupon

**Comment by senadir** [comment]
Would it possible to keep the old logic but return an error if you try to place an order with mismatching coupon/email instead of removing the email and passing?

**Comment by wavvves** [comment]
> Would it possible to keep the old logic but return an error if you try to place an order with mismatching coupon/email instead of removing the email and passing?

@senadir The old behaviour was returning an error and removing the coupon from the order, but still making the user to place the order again. That was the purpose of the PR, never allow a user to add a coupon only to be disappointed in the end.

@danieleperilli I having trouble replicating this, with the correct email filled in the coupon is added to the order.  Can you please test on a fresh install? Is there anything that could be interfering? (plugins, etc)

**Comment by danieleperilli** [comment]
@wavvves Yes, unfortunately with a fresh installation the coupon is added. This is sad, since it means that a theme or pluign that we used for years is interfering...

**Comment by wavvves** [comment]
@danieleperilli can you please share the system report of WooCommerce, so we can replicate and investigate if anything can be done from our side?

**Comment by danieleperilli** [comment]
@wavvves Thank you Paulo. I am not comfortable sharing the system report, but I appreciate your offer to help. I will check in the next few weeks and if I can't solve the problem, I will send more information.

**Comment by tarunvijwani** [comment]
@danieleperilli Sure, I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Comment by molomoot** [comment]
> [@danieleperilli](https://github.com/danieleperilli) Sure, I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

Can we re-open this because I am having this exact issue and have found no solution :(

**Comment by danieleperilli** [comment]
<img width="1818" height="690" alt="Image" src="https://github.com/user-attachments/assets/5160f797-8039-4707-9e3c-18d0c30b257c" />
To be honest, I continued to patch your source code to have the feature available in **classic template** websites.

**Comment by molomoot** [comment]
> <img alt="Image" width="1818" height="690" src="https://private-user-images.githubusercontent.com/9072177/523249626-5160f797-8039-4707-9e3c-18d0c30b257c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUwMjMyMDUsIm5iZiI6MTc2NTAyMjkwNSwicGF0aCI6Ii85MDcyMTc3LzUyMzI0OTYyNi01MTYwZjc5Ny04MDM5LTQ3MDctOWUzYy0xOGQwYzMwYjI1N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDZUMTIwODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzgwNzM5M2NkYmQyYzkxYWVhNzNlNTI2Yjc5ODhmNDk4YjE5ZWMzNTdiNDJkZTBlNWZkMWM5MzUwZWQzYjA4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.an3l2lZR1nZLsNNQJombTf7mlYRHM0wa7Gi9FAuldwE"> To be honest, I continued to patch your source code to have the feature available in **classic template** websites.

Does this remove the validate coupon from allowed email entirely or fix the issue of allowing guest checkout with valid email?

**Comment by molomoot** [comment]
> > Would it possible to keep the old logic but return an error if you try to place an order with mismatching coupon/email instead of removing the email and passing?
> 
> [@senadir](https://github.com/senadir) The old behaviour was returning an error and removing the coupon from the order, but still making the user to place the order again. That was the purpose of the PR, never allow a user to add a coupon only to be disappointed in the end.
> 
> [@danieleperilli](https://github.com/danieleperilli) I having trouble replicating this, with the correct email filled in the coupon is added to the order. Can you please test on a fresh install? Is there anything that could be interfering? (plugins, etc)

I really want to avoid doing a complete fresh install if I can. 
I want customers to be able to check out as a guest as long as the email address in billing is in the allowed emails list.

**Comment by danieleperilli** [comment]
> > <img alt="Image" width="1818" height="690" src="https://private-user-images.githubusercontent.com/9072177/523249626-5160f797-8039-4707-9e3c-18d0c30b257c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUwMjMyMDUsIm5iZiI6MTc2NTAyMjkwNSwicGF0aCI6Ii85MDcyMTc3LzUyMzI0OTYyNi01MTYwZjc5Ny04MDM5LTQ3MDctOWUzYy0xOGQwYzMwYjI1N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDZUMTIwODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzgwNzM5M2NkYmQyYzkxYWVhNzNlNTI2Yjc5ODhmNDk4YjE5ZWMzNTdiNDJkZTBlNWZkMWM5MzUwZWQzYjA4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.an3l2lZR1nZLsNNQJombTf7mlYRHM0wa7Gi9FAuldwE"> To be honest, I continued to patch your source code to have the feature available in **classic template** websites.
> 
> Does this remove the validate coupon from allowed email entirely or fix the issue of allowing guest checkout with valid email?

This feature allows guests to checkout using a valid email, which was something we wanted (and worked before the PR).

Regarding potential interferences, of course we use various plugins, including proprietary ones. Therefore, attempting a fresh installation takes significantly more time than commenting a single line of code. I understand that you can’t assist me if I don’t perform the tests, but finding time to do that is a problem. Also, since I identified the line of code and the exact moment when you added it, maybe it can give you some clues. If you are not able to find the problem and cannot simply comment the line, I will continue with the workaround, at least until I have time to try with a fresh installation.
