### ISSUE TITLE
[Checkout block] The default Payment Method Not Automatically Selected at Checkout

### ISSUE THREAD

**Issue by qasumitbagthariya** [woothemes/woocommerce#48088]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the payment method settings, we have the option to set a My account > default payment method, which is intended to be displayed as the default payment option during the checkout process. However, this default payment method is not being automatically selected in the block checkout.

This issue may lead to a poor user experience, as users expect the default payment method to be pre-selected to streamline the checkout process.

https://github.com/woocommerce/woocommerce/assets/67687255/420520d6-0013-468b-93ea-40f4f52602f5

### Expected behavior

 The expected behavior is for the default payment method to be pre-selected when a user reaches the checkout page.

### Actual behavior

The default payment method is displayed but not automatically selected, requiring manual selection by the user.

### Steps to reproduce

1. Goto my-account>payment-methods
2. Set any one payment method as the "default".
3. Goto to the shop page, add to the cart any product, and process for checkout(checkout block must be added)
4. Observe that the default payment method is displayed but not automatically selected.

### WordPress Environment

WordPress: 6.5.3
Theme: Storefront 4.6.0
WooCommerce - 8.9.1
Browser: Chrome 
OS: macOS Ventura 13.3 

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
Thank you, I managed to reproduce.
