### ISSUE TITLE
Ship to a different address option is missing on the Block-based checkout

### ISSUE THREAD

**Issue by shameemreza** [woothemes/woocommerce#48087]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I use the checkout block on the checkout page, the option to ship to a different address doesn't appear. I remember seeing this option before. But the option shows up correctly when I switch to the classic checkout or shortcode. 

![CleanShot 2024-06-01 at 17 07 34](https://github.com/woocommerce/woocommerce/assets/14240438/29655791-73ca-4147-8270-8af8889f9447)

![CleanShot 2024-06-01 at 17 14 36](https://github.com/woocommerce/woocommerce/assets/14240438/797264c7-a760-4242-9d9c-71a238c6118b)

### Expected behavior

When you set the "Shipping destination" setting to either "Default to customer shipping address" or "Default to customer billing address", you should see the "Ship to a different address" option. It doesn't matter if you use the checkout block, classic checkout, or shortcode.

### Actual behavior

Go to your checkout page and add the checkout block. Once that's done, you'll need to adjust the "Shipping destination" setting. You can select either "Default to customer shipping address" or "Default to customer billing address".

After you've made your selection, try adding a product to your cart and proceed to checkout. You'll see that the "Ship to a different address?" option doesn't appear. I've also checked, but there's no option in the block settings to enable or disable this feature.

### Steps to reproduce

Go to your checkout page and add the checkout block. Once that's done, you'll need to adjust the "Shipping destination" setting. You can select either "Default to customer shipping address" or "Default to customer billing address".

After you've made your selection, try adding a product to your cart and proceed to checkout. You'll see that the "Ship to a different address?" option doesn't appear.

### WordPress Environment

* WooCommerce version: 8.9.1
* WordPress version: 6.5.3
* PHP version: 8.1.27
* Theme: Storefront and Twenty Twenty-Four

Reported here: 8246767-zen
Thread link: https://wordpress.org/support/topic/about-shipping-options-to-other-addresses/

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
I'm not sure I understand the request? In Checkout block, the shipping address is the one collected first, this is in contrast to Shortcode Checkout which collected billing first.  The `"Ship to a different address?"` will never show, you will only see `Use same address for billing`.

**Comment by shameemreza** [comment]
Thanks for the clarification @senadir. Closing as completed.
