### ISSUE TITLE
Checkout block doesn't support shipping rate description.

### ISSUE THREAD

**Issue by fixcoderu** [woothemes/woocommerce#48090]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

During the checkout process, it is not possible to display a description of the delivery method.

In the old version, a hook existed and worked:

do_action( 'woocommerce_after_shipping_rate', $method, $index );

But, in the version with the block structure of the order, this hook does not work.

I have studied the help and have not found anything that could help me to get a description of the delivery method.

![2024-06-02_16-56-14](https://github.com/woocommerce/woocommerce/assets/54111009/d84ed6e1-5006-46e2-b134-3f69fe1c6298)

### Expected behavior

I expect to receive the description text under the name of the delivery method after adding this hook:

add_action( 'woocommerce_after_shipping_rate', 'bbloomer_shipping_rate_description' );

function bbloomer_shipping_rate_description( $method ) {
    if ( $method->id === 'free_shipping:12' ) {
        echo '<p>Some HTML in here where you can explain the benefits of choosing this shipping rate</p>';
    }
}

### Actual behavior

Nothing is output

### Steps to reproduce

1. Add cart product
2. Go to the page "Checkout"

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost
Site address (URL): http://localhost
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 2 ГБ
WP Debug Mode: ✔
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.9
PHP Post Max Size: 50 МБ
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.77.0
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 50 МБ
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: wp_
Общий размер базы данных: 5.05MB
Размер данных в базе данных: 3.33MB
Размер индекса базы данных: 1.72MB
wp_woocommerce_sessions: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_api_keys: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_attribute_taxonomies: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_downloadable_product_permissions: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_order_items: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_order_itemmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_tax_rates: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_tax_rate_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zones: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_shipping_zone_locations: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_woocommerce_shipping_zone_methods: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_payment_tokens: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_payment_tokenmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_log: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_actions: Данные: 0.11MB + Индекс: 0.11MB + Движок InnoDB
wp_actionscheduler_claims: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_groups: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_logs: Данные: 0.11MB + Индекс: 0.03MB + Движок InnoDB
wp_commentmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_comments: Данные: 0.02MB + Индекс: 0.09MB + Движок InnoDB
wp_links: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_options: Данные: 2.03MB + Индекс: 0.06MB + Движок InnoDB
wp_postmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_posts: Данные: 0.08MB + Индекс: 0.06MB + Движок InnoDB
wp_termmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_terms: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_term_relationships: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_term_taxonomy: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_usermeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_users: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_wc_admin_notes: Данные: 0.06MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_admin_note_actions: Данные: 0.06MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_category_lookup: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_customer_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_download_log: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_orders: Данные: 0.02MB + Индекс: 0.11MB + Движок InnoDB
wp_wc_orders_meta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_addresses: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_wc_order_coupon_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_operational_data: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_product_lookup: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_wc_order_stats: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_wc_order_tax_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_product_attributes_lookup: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_product_download_directories: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_product_meta_lookup: Данные: 0.02MB + Индекс: 0.09MB + Движок InnoDB
wp_wc_rate_limits: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_reserved_stock: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_tax_rate_classes: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_webhooks: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB

### Post Type Counts ###

attachment: 1
page: 8
polygon_post: 6
post: 2
product: 2
revision: 4
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					В вашем магазине не используется HTTPS. Подробнее об HTTPS и SSL-сертификатах.
Hide errors from visitors: ❌Не стоит отображать для посетителей сообщения об ошибках.

### Active Plugins (3) ###

Polygon WCPolygonDeliveryMethod: от Roman Suvorov – 1.0.0
Post Meta Viewer: от Yongki Agustinus – 2.0
WooCommerce: от Automattic – 8.9.1

### Inactive Plugins (4) ###

Akismet Anti-spam: Spam Protection: от Automattic - Anti-spam Team – 5.3.2
Hello Dolly: от Matt Mullenweg – 1.7.2
Metabase - Post Meta and User Meta Editor: от David Towoju – 0.8
WC Easy Checkout: от  – 1.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: RUB (₽)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 дней
Level threshold: –
Log directory size: 454 КБ

### WC Pages ###

Ссылка магазина: #7 - /?page_id=7
Корзина: #8 - /?page_id=8
Оформление заказа: #9 - /?page_id=9
Мой аккаунт: #10 - /?page_id=10
Правила и условия: ❌ Страница не задана

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://ru.wordpress.org
Child Theme: ❌ – Если вы хотите оформить WooCommerce родительской темой
которую создал кто-то другой
мы рекомендуем воспользоваться дочерней темой. См. "Как создать дочернюю тему"

WooCommerce Support: ❌ Не определено

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-06-03 07:57:21 +03:00
Options: ✔
Notes: 70
Onboarding: skipped

### Action Scheduler ###

Выполнено: 264
Oldest: 2024-05-07 09:09:18 +0000
Newest: 2024-06-02 13:56:43 +0000

Неудачно: 1
Oldest: 2024-04-05 08:00:48 +0000
Newest: 2024-04-05 08:00:48 +0000

В ожидании: 2
Oldest: 2024-06-03 01:12:45 +0000
Newest: 2024-06-03 13:12:45 +0000

### Status report information ###

Generated at: 2024-06-02 17:03:19 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
We do not support shipping rate descriptions yet, I will loop in @nikkivias who might be able to provide better feedback if we should.

@nikkivias by default, WooCommerce shipping methods don't support a description and don't have that field, but shipping extensions can provide a description if they want.

**Comment by opr** [comment]
Similar to https://github.com/woocommerce/woocommerce/issues/42667 - think we should fix this upstream by supporting `description` in `WC_Shipping_Rate`

**Comment by opr** [comment]
Closing this issue in favour of https://github.com/woocommerce/woocommerce/issues/42667
