### ISSUE TITLE
Blocks Checkout fails with legacy payment gateways integrated in form mode for offsite payment

### ISSUE THREAD

**Issue by alexminza** [woothemes/woocommerce#48126]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Classic payment gateways that need to [submit a browser form](https://developer.woocommerce.com/docs/woocommerce-payment-gateway-api/#0-types-of-payment-gateway) to the payment processor for the transaction to take place offsite use the `woocommerce_receipt_*` action https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/checkout/order-receipt.php#L44

The migration to blocks checkout relies on the `process_legacy_payment` function https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Legacy.php#L27

The `process_legacy_payment` function calls `WC_Payment_Gateway process_payment` that in this type of integration outputs a self-submitting HTML form to initiate the payment process. Since in Blocks Checkout mode this is an AJAX call the generated HTML form is not inserted into the DOM and the form is not submitted further for payment on the bank side.

Alternatively, trying to return a `pending` result with a redirect to the auto-submitting form page renders an error since `process_legacy_payment` code looks specifically for `success` result marking everything else as `failure` even if `pending` is a valid status as defined by `PaymentResult $valid_statuses` https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Payments/PaymentResult.php#L13

```
    "payment_result": {
        "payment_status": "failure",
        "payment_details": [
            {
                "key": "result",
                "value": "pending"
            },
            {
                "key": "redirect",
                "value": "http:\/\/localhost:8080\/checkout\/order-pay\/70286\/?key=wc_order_xZHs3ers16S1w"
            }
        ],
        "redirect_url": "http:\/\/localhost:8080\/checkout\/order-pay\/70286\/?key=wc_order_xZHs3ers16S1w"
    },
```

Additionally, with Blocks Checkout calling `wp_doing_ajax` in `process_payment` does not return the correct result as `process_legacy_payment` AJAX call is not declared as such. This makes impossible to differentiate the type of checkout in `process_payment` to have correct behavior and responses for each case - classic or blocks.

### Expected behavior

-  Support legacy payment gateways with form mode integration for offsite payment https://github.com/alexminza/wc-victoriabank/blob/v1.4.0/wc-victoriabank.php#L744
- Properly define AJAX calls performed by `process_legacy_payment` to allow differentiation on the server side in `process_payment` https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Legacy.php#L36
- Allow payment result statuses in `process_legacy_payment` as defined by `PaymentResult $valid_statuses` so that payments can be performed in several steps https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Payments/PaymentResult.php#L13

### Actual behavior

Legacy payment gateways integrated in form mode (auto-submitted browser forms to initiate payment offsite) cannot be integrated with Blocks Checkout mode today.

### Steps to reproduce

This is the migration WIP code that fails in the current setup as described above https://github.com/alexminza/wc-victoriabank/tree/v1.4.0

### WordPress Environment

<details>

### WordPress Environment ###

WordPress address (URL): http://localhost:8080
Site address (URL): http://localhost:8080
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Debian)
PHP Version: 8.2.15
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 8.0.36
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wp_
Total Database Size: 240.67MB
Database Data Size: 128.19MB
Database Index Size: 112.48MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.14MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 50.56MB + Index: 59.06MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 33.56MB + Index: 28.08MB + Engine InnoDB
wp_atum_inventories: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_atum_inventory_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_atum_inventory_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_inventory_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_atum_inventory_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_inventory_regions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_inventory_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 0.47MB + Index: 0.56MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 31.02MB + Index: 15.02MB + Engine InnoDB
wp_term_taxonomy: Data: 1.03MB + Index: 3.03MB + Engine InnoDB
wp_termmeta: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_terms: Data: 1.03MB + Index: 3.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
atum_supplier: 2
page: 7
post: 2
product: 2
product_variation: 2
revision: 22
shop_order: 17
shop_order_placehold: 5
wp_global_styles: 1
wp_navigation: 1
wp_template: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

ECOM: by Alexander Minza – 0.1.26-beta
Featured Image from URL (FIFU): by fifu.app – 4.7.8
WooCommerce maib Moldova Agroindbank Payment Gateway: by Alexander Minza – 1.4.1-beta
WooCommerce Victoriabank Payment Gateway: by Alexander Minza – 1.4.0
WooCommerce: by Automattic – 8.9.1
WP Crontrol: by John Blackbourn – 1.16.3
WP File Manager: by mndpsingh287 – 7.2.8

### Inactive Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.39.2
ATUM Multi-Inventory: by Stock Management Labs™ – 1.9.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce PayPal Payments: by WooCommerce – 2.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: MDL (MDL)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 B

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-06-04 18:35:02 +00:00
Options: ✔
Notes: 56
Onboarding: skipped

### Action Scheduler ###

Complete: 137,325
Oldest: 2024-03-31 05:31:37 +0000
Newest: 2024-06-04 06:36:30 +0000

Failed: 5
Oldest: 2024-03-31 14:14:21 +0000
Newest: 2024-03-31 14:14:30 +0000

Pending: 6
Oldest: 2024-06-04 17:34:58 +0000
Newest: 2024-06-06 08:50:08 +0000

### Status report information ###

Generated at: 2024-06-04 06:58:15 +00:00
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by alexminza** [comment]
@mikejolley it seems that you developed this functionality so you must have the deepest expertise and knowledge on this subject :) https://github.com/woocommerce/woocommerce/commit/676e10b80512afb2ad056d69cfc894200de7cb60

In short - is there any support, possibility to integrate "old school" bank card payment gateway with Checkout Blocks that relies on the browser submitting a POST form to initiate offsite payment?

**Comment by alexminza** [comment]
Current test code:

https://github.com/alexminza/wc-victoriabank/blob/v1.4.0/wc-victoriabank.php#L744

```php
public function process_payment($order_id) {
	$this->log('process_payment');

	if(!$this->check_settings()) {
		$this->log('process_payment check_settings');
		$message = sprintf(__('%1$s is not properly configured.', self::MOD_TEXT_DOMAIN), $this->method_title);

		wc_add_notice($message, 'error');
		$this->settings_admin_notice();

		return array(
			'result'   => 'failure',
			'messages' => $message
		);
	}

	//if(wp_doing_ajax()) {
		$this->log('process_payment wp_doing_ajax');
		$order = wc_get_order($order_id);

		return array(
			'result'   => 'pending',
			'redirect' => $order->get_checkout_payment_url(true)
		);
	//}

	$this->receipt_page($order_id);
}
```

* `wp_doing_ajax` is not able to detect if this is an AJAX call from blocks checkout `process_legacy_payment`
* returning `pending` results in `process_legacy_payment` marking the order payment as failed https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Legacy.php#L64
* returning `success` marks the order as paid before redirecting to the payment gateway to perform the actual payment on the bank page

**Comment by mikejolley** [comment]
cc @senadir 

The legacy checkout flow was to place order>redirect to thanks page>render form>auto submit form.

The big difference between legacy and block checkout is that you have an order populated in the database as soon as you hit the block based checkout as a customer, so we don't need to place the order first.

So I would expect the checkout block solution would be to render the form in the payment area and submit it when the place order button is pressed. @senadir do you agree?

**Comment by alexminza** [comment]
> So I would expect the checkout block solution would be to render the form in the payment area and submit it when the place order button is pressed.

An easier alternative might be:
* allowing redirects when the place order button is pressed
* accepting `pending` as a valid intermediate status of the `process_legacy_payment` function.

Step by step the process would be:
* customer clicks place order button in blocks checkout
* `StoreApi process_legacy_payment` calls `WC_Payment_Gateway process_payment` which returns `array('result' => 'pending', 'redirect' => $order->get_checkout_payment_url(true));`
* `StoreApi process_legacy_payment` sets order status to `pending`
* customer is redirected to the `checkout/order-pay` page where the offsite payment form is rendered and auto-submitted to the bank payment page
* customer makes the payment and the bank payment gateway calls back `woocommerce_api_wc_*`
 action that validates the payment and marks the order as paid
* customer is redirected to order `get_return_url`

**Comment by senadir** [comment]
I'm struggling a bit to understand this flow of redirecting to receipt page that auto submits a form, is this a common design pattern in the old payment methods?

> Additionally, with Blocks Checkout calling wp_doing_ajax in process_payment does not return the correct result as process_legacy_payment AJAX call is not declared as such. This makes impossible to differentiate the type of checkout in process_payment to have correct behavior and responses for each case - classic or blocks.

You can simply declare a `woocommerce_rest_checkout_process_payment_with_context` function that will only for Store API requests.

I'm also not understand how your forms actually works? why can't you call `generate_form` before returning an order status?

**Comment by senadir** [comment]
To my understanding, the `process_payment` function should return a redirect URL that Checkout will redirect to. The order status will always be `pending` until you get a callback from the payment provider to approve it or not.

**Comment by alexminza** [comment]
> I'm struggling a bit to understand this flow of redirecting to receipt page that auto submits a form, is this a common design pattern in the old payment methods?

Yes, the form has to be submitted from the browser, so these payment gateways inject the form in the DOM and peform a simulated click/submit to the bank payment page.

At this stage there has to be an order, so that the order number and details are submitted along to the bank payment page.

On the bank payment page the client enters their payment details, and after bank confirmation the user is redirected back to the shop.

**Comment by alexminza** [comment]
> You can simply declare a `woocommerce_rest_checkout_process_payment_with_context` function that will only for Store API requests.

This would override the default legacy processing logic of `process_legacy_payment` and force the implementer to copy/paste duplicate the logic from https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Legacy.php#L27

The goal here is to maximize compatibility with existing gateways that need to work in both classic and blocks checkout.

**Comment by alexminza** [comment]
> To my understanding, the `process_payment` function should return a redirect URL that Checkout will redirect to. The order status will always be `pending` until you get a callback from the payment provider to approve it or not.

Exactly, and the logic that would enable this adaption is:
* allow returing a `pending` order status and a redirect url from `StoreApi process_legacy_payment`
* allow properly identifying in `WC_Payment_Gateway process_payment` that the call is from blocks checkout


This is what currently the community has found as a potential solution to detect that current checkout is in blocks mode https://stackoverflow.com/questions/77948982/check-programatically-if-cart-or-checkout-blocks-are-used-in-woocommerce

**Comment by senadir** [comment]
The order will be set to `pending` before we call `process_payment`, what you're returning from `process_payment` isn't the new order status, it's the processing logic (was it successful or not).

As for sharing code, a couple of options:
- Move shared code to a single function that's called with different params from both functions.
- Detect if the current request is a Store API request, as Store API requests aren't AJAX requests, this can be done using the following code `wc()->is_store_api_request()`.

**Comment by alexminza** [comment]
> what you're returning from `process_payment` isn't the new order status, it's the processing logic (was it successful or not).

A `success` or `failure` status will be set immediately after calling `WC_Payment_Gateway process_payment`

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Legacy.php#L64

```php
// Process Payment.
$gateway_result = $payment_method_object->process_payment( $context->order->get_id() );

...

// Handle result.
$result->set_status( isset( $gateway_result['result'] ) && 'success' === $gateway_result['result'] ? 'success' : 'failure' );
```

**Comment by alexminza** [comment]
So the `WC_Payment_Gateway` code would look like this:

```php
public function process_payment($order_id) {
	if(WC()->is_store_api_request()) {
		$order = wc_get_order($order_id);

		return array(
			'result'   => 'success',
			'redirect' => $order->get_checkout_payment_url(true)
		);
	}

	$this->receipt_page($order_id);
}
```

Is it correct to return `success` result here and not `pending`?

I see that `CheckoutTrait process_payment` sets order status to `pending` before doing action `woocommerce_rest_checkout_process_payment_with_context` which in turn executes `StoreApi process_legacy_payment`.

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Utilities/CheckoutTrait.php#L65

```php
// Transition the order to pending before making payment.
$this->order->update_status( 'pending' );
```

**Comment by mikejolley** [comment]
@senadir I don't see us using these internally:

`payment_status: 'success' | 'failure' | 'pending' | 'error';`

Are they just for the gateway implementation to act on? If so either would be valid—only `error` and `failure` would halt checkout.

**Comment by mikejolley** [comment]
Just catching up here. So to summarise:

- You want to integrate a form-post based payment method with block based checkout
- Shortcode based checkout worked by redirecting the customer to the receipt page where the form was rendered and POSTed to the payment provider
- Because you wish to maintain support with shortcode checkout, you wish to avoid `woocommerce_rest_checkout_process_payment_with_context`

**Issue 1 - Pending status**

`payment_status` of `pending` does not redirect like `success` does, it instead gives `Something went wrong. Please contact us to get assistance.`. 

_Pending_ is not documented properly and I wonder if it was included as a mistake. Its not actually needed; you can return a `success` response for the redirect to work:

`return array(
	'result'   => 'success',
	'redirect' => $this->get_return_url( $order ),
);`

This does not change the order status.

**Issue 2 - `woocommerce_receipt_` does not run.**

@alexminza Given you want to render and POST this form from both checkouts, could you instead do this with a more general WordPress hook such as `init`?

- From your side you'd want to include something in the return URL you can check for later e.g. ?action=my_gateway_redirect
- On init, if this parameter is set, check customer has permission and render the form. Exit after rendering the form.
- Include JavaScript to submit the form automatically

This intermediary page could be the same on both checkouts. There is nothing to present to the customer because it should redirect automatically.

cc @senadir

**Comment by alexminza** [comment]
> Just catching up here. So to summarise:

@mikejolley I cannot confirm the conclusion from `Issue 2 - woocommerce_receipt_ does not run.` - as you can see from the example code below it will run after a simple redirect to the receipt page.

This is the current code that incorporates the discussion and seems to work well in both classic and blocks checkout modes:

https://github.com/alexminza/wc-victoriabank/blob/v1.4.0/wc-victoriabank.php#L725

```php
public function process_payment($order_id) {
	if(!$this->check_settings()) {
		$message = sprintf(__('%1$s is not properly configured.', self::MOD_TEXT_DOMAIN), $this->method_title);

		//https://github.com/woocommerce/woocommerce/issues/48687#issuecomment-2186475264
		if(WC()->is_store_api_request()) {
			throw new Exception($message);
		}

		wc_add_notice($message, 'error');

		return array(
			'result'   => 'failure',
			'messages' => $message
		);
	}

	//https://github.com/woocommerce/woocommerce/issues/48126#issuecomment-2180991020
	if(WC()->is_store_api_request()) {
		$order = wc_get_order($order_id);

		return array(
			'result'   => 'success',
			'redirect' => $order->get_checkout_payment_url(true)
		);
	}

	$this->receipt_page($order_id);
}
```

**Comment by mikejolley** [comment]
@alexminza Ok I see you're using the pay page, not the order confirmation page. That one hasn't received the block treatment yet.

So only issue 1 is actionable; I think the pending status may not be needed and can be deprecated, or treated like success.

**Comment by alexminza** [comment]
> Ok I see you're using the pay page, not the order confirmation page. That one hasn't received the block treatment yet.

Does this mean that this method will stop working after upgrade of the pay page to blocks checkout?

This is how currently the payment integration middleware generates and auto-submits the form:

https://github.com/alexminza/wc-victoriabank/blob/v1.4.0/vendor/fruitware/victoria-bank-gateway/src/VictoriaBank/Authorization/AuthorizationRequest.php#L148

**Comment by mikejolley** [comment]
> Does this mean that this method will stop working after upgrade of the pay page to blocks checkout?

I imagine the hooks will be made backwards compatible but may be rendered at a different point.

> This is how currently the payment integration middleware generates and auto-submits the form

I see. It shouldn't include HTML tags if this is within the body of the page?

**Comment by alexminza** [comment]
> I see. It shouldn't include HTML tags if this is within the body of the page?

True, but this is a 3rd party legacy middleware that implements the bank communication protocol.
It should be adjusted to output just the form code - I think a PR must be submitted to the project author - thanks for the suggestion!
Currently browsers understand and properly ignore this so the form is injected and auto-submitted without any issues.
