### ISSUE TITLE
Building classic assets probably needs some love

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#48121]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'll start by saying this could all boil down to a misunderstanding over how things are currently intended to work (if so, please point me in the right direction). However, we sometimes wish to work on 'classic' or 'legacy' assets, and don't really want the overhead of running the entire build process.

This used to be achievable, but as of recently (not sure when exactly things changed), we find that running:

```sh
pnpm --filter='@woocommerce/classic-assets' build
```

Isn't sufficient to let us see our changes. It does seem like the assets are built, but they are not moved to the `assets/` directory.

```
plugins/
    woocommerce/
        assets/
            css/   ← Assets are enqueued from these directories, but
            js/    ← it seems we need to copy them here manually.
        client/
            legacy/
                build/  ← Once built, the assets are placed in here.
                js/     ← Source dir for JS.
                css/    ← Source dir for CSS.
```

### Expected behavior

I expect to be able to build the classic assets and test the output, and for expediency would like to be able to do this using a simple command and with minimum overhead.

### Actual behavior

Assets are built, but don't go to the right place. At least, that's my interpretation of things as they stand 🙃 

### Steps to reproduce

1. Make some changes to any of the classic assets, ie within `plugins/woocommerce/client/legacy/js` (or `css`).
2. Run `pnpm --filter='@woocommerce/classic-assets' build`.
3. Try to test your changes.

### WordPress Environment

Not applicable.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment]
Just a reminder that https://github.com/woocommerce/woocommerce/pull/43433 proposed adding build aliases that solve this problem.

**Comment by barryhughes** [comment]
OK, I'm happy if we close this one if you're sure that covers it. 

The alias would need to not just take care of watching for changes and building the classic assets, but also copying them to the correct location (which is my chief complaint here—that is, `pnpm --filter='@woocommerce/classic-assets' build` isn't sufficient by itself for us to see our changes).

**Comment by ObliviousHarmony** [comment]
Yep @barryhughes!

That's exactly why I proposed the aliases in the first place :smile: It basically just runs what amounts to `pnpm --filter='@woocommerce/classic-assets' --filter='@woocommerce/plugin-woocommerce' build:project` which covers building and copying.

**Comment by barryhughes** [comment]
Alright, thanks @ObliviousHarmony ... in that case, closing this issue :-)
