### ISSUE TITLE
'active_plugins' doesn't mean plugin file exists

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#48132]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PHP notice 

>file_get_contents(...): failed to open stream: No such file or directory

from `$data                  = get_plugin_data( WP_PLUGIN_DIR . '/' . $plugin );` in 
class-wc-rest-system-status-v2-controller.php

because the plugin might still be in the option but the file doesn't exist anymore in that point in time e.g. bc the directory was removed in the meantime.

### Expected behavior

No notice

### Actual behavior

Notice

### Steps to reproduce

Irrelevant to fix it

### WordPress Environment

Irrelevant

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @kkmuffme!

Thanks for reaching out! Could you please include a more comprehensive description of the problem and maybe some details on how to reproduce? I understand that this might be a bit of an edge case, so maybe not easily reproducible, but still, you could point out to the correct endpoint that is generating the notice/etc.
This being a public repository, we feel it's important for historical records, even if the problem or the solution are trivial. Thanks again!

**Comment by kkmuffme** [comment]
Hi Jorge,

sorry for being brief, but I can't provide support for WP core. See e.g. https://developer.wordpress.org/reference/functions/wp_get_active_and_valid_plugins/ for details on why/how to reproduce.

This isn't an edge case at all, but part of how active plugins works in WP.

**Comment by jorgeatorres** [comment]
Re-opening due to this revert: https://github.com/woocommerce/woocommerce/pull/50881.
