### ISSUE TITLE
Bug on the screen for all wordpress products

### ISSUE THREAD

**Issue by YangoodStore** [woothemes/woocommerce#48147]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The bug is on the WordPress "All Products" page. I installed the Rank SEO plugin, and now the page is not functioning correctly.

### Expected behavior

The area where Rank SEO is displayed is problematic because it is too narrow, causing the text to stretch downwards and increasing the space between products. This layout is suboptimal. The Rank SEO section should be centered on the page or placed in a more suitable location.

https://github.com/woocommerce/woocommerce/assets/171697036/494d6633-4c9f-4112-a563-71cc95c4fb01

### Actual behavior

I'm sending you a screen recording so you can see what it looks like on the products page

https://github.com/woocommerce/woocommerce/assets/171697036/b005267d-4eee-44fb-95de-d84fe6dac694

### Steps to reproduce

https://github.com/woocommerce/woocommerce/assets/171697036/26ab4c20-ad76-4048-ad17-c881ad094451

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://yangood.com
Site address (URL): https://yangood.com
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.8.0
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 360
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.11.7-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wp_
Total Database Size: 242.73MB
Database Data Size: 220.06MB
Database Index Size: 22.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 5.50MB + Index: 5.89MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwfan_abandonedcarts: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automation_complete_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwfan_automation_contact: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_contact_claim: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_automation_contact_trail: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bwfan_automation_step: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_message_unsubscribe: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bwf_actions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwf_action_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_wc_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_visits: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_visits_meta: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_options: Data: 6.48MB + Index: 0.23MB + Engine InnoDB
wp_parcelpanel_courier: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_parcelpanel_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_parcelpanel_tracking: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_parcelpanel_tracking_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_postmeta: Data: 118.47MB + Index: 6.95MB + Engine InnoDB
wp_posts: Data: 78.47MB + Index: 1.03MB + Engine InnoDB
wp_presto_player_audio_presets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_presto_player_email_collection: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_presto_player_presets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_presto_player_videos: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_presto_player_visits: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_presto_player_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vi_wad_ali_orders_info: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vi_wad_error_product_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfacp_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfco_connectormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_connectors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 2102
cartflows_flow: 1
cartflows_step: 3
custom_css: 2
customize_changeset: 7
e-landing-page: 1
elementor_library: 22
elementor_snippet: 20
flamingo_contact: 201
flamingo_inbound: 302
nav_menu_item: 13
page: 15
post: 2
pp_video_block: 1
product: 36
product_variation: 184
product-feed: 1
revision: 2628
shop_order: 599
vi_wad_draft_product: 1
wp_global_styles: 2
wp_navigation: 1
wp_template: 2
wpcf7_contact_form: 5
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

DSers Dropshipping Solution: Find products on AliExpress for WooCommerce: by DSers – 1.5.5
CartFlows Pro: by CartFlows Inc – 2.0.4
CartFlows: by CartFlows Inc – 2.0.5
Contact Form 7: by Takayuki Miyoshi – 5.9.5
EAN for WooCommerce: by WPFactory – 4.9.5
Elementor: by Elementor.com – 3.21.8
Facebook for WooCommerce: by Facebook – 3.2.3
Flamingo: by Takayuki Miyoshi – 2.5
FULL - Cliente: by FULL. – 3.1.7
Google Listings and Ads: by WooCommerce – 2.7.1
Judge.me Product Reviews for WooCommerce: by Judge.me – 1.3.22
PRO Elements: by PROElements.org – 3.21.3
Rank Math SEO with AI Best SEO Tools: by Rank Math – 1.0.220
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.27
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.71

Variation Swatches for WooCommerce - Pro: by Emran Ahmed – 2.0.31
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.31
WooCommerce PayPal Payments: by WooCommerce – 2.7.1
WooCommerce: by Automattic – 8.9.1
Woostify Pro: by Woostify – 1.8.2
Woostify Sites Library: by Woostify – 1.4.8
Custom Product Tabs for WooCommerce: by Code Parrots – 1.8.5

### Inactive Plugins (3) ###

LiteSpeed Cache: by LiteSpeed Technologies – 6.2.0.1
Payment Plugins for PayPal WooCommerce: by Payment Plugins
support@paymentplugins.com – 1.0.47

Temporary Login Without Password: by StoreApps – 1.8.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 39 MB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #4265 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page ID is set
but the page does not exist

### Theme ###

Name: Woostify
Version: 2.3.2
Author URL: https://woostify.com/about
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: woostify/woocommerce/emails/customer-invoice.php
woostify/woocommerce/single-product/stock.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: BR
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-06-04 17:09:45 +00:00
Options: ✔
Notes: 119
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2024-06-04 12:43:00 +0000
Newest: 2024-06-04 12:43:00 +0000

Complete: 14,739
Oldest: 2024-05-04 13:49:50 +0000
Newest: 2024-06-04 13:05:52 +0000

Failed: 154
Oldest: 2023-07-17 17:13:10 +0000
Newest: 2024-05-30 14:08:59 +0000

Pending: 12
Oldest: 2024-06-04 13:55:52 +0000
Newest: 2024-07-04 00:22:42 +0000

### Status report information ###

Generated at: 2024-06-04 13:50:08 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
@YangoodStore While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. The issue you are having seems to be caused by the Rank SEO plugin, please contact them.
