### ISSUE TITLE
[9.0.0 RC1]: All links containing "return_url" query var are broken

### ISSUE THREAD

**Issue by strategio** [woothemes/woocommerce#48154]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

As soon as you have the `return_url` query var in an admin URL, you are automatically redirected to this "return URL".

This bug has been caused by this commit => https://github.com/woocommerce/woocommerce/commit/da57287c560ab8b4d9fc3f0f80b3fc54f2944e21

The scope of the logic in `WC_Install::install_actions` should be reduced.

### Expected behavior

WooCommerce should not redirect all requests based on the `return_url` query var:

Example:
https://wpml.loc/wp-admin/post.php?post=1&action=edit&return_url=https://wpml.loc/ should just open the post editor.

### Actual behavior

Example:
https://wpml.loc/wp-admin/post.php?post=1&action=edit&return_url=https://wpml.loc/ is redirecting us to https://wpml.loc/ (the home page)

### Steps to reproduce

1. On a WooCommerce site, navigate to Example:
https://wpml.loc/wp-admin/post.php?post=1&action=edit&return_url=https://wpml.loc/

### WordPress Environment

No need for more details, the bug is clear and located in the code.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### Extra notes
- This bug was found in the context of a full automatic E2E test campaign between WC 9.0.0-rc.1 and WPML and WooCommerce Multilingual.
- This bug is causing critical issues and we expect it to be fixed before the release of WC 9.0.0.

**Comment by strategio** [comment]
Hi @rrennick, do you have any update on this issue? Will we have a RC2 so we can re-test it?

For more context, this bug prevents the [WPML](https://wpml.org/) user from opening a translation job (it just makes WPML unusable).

**Comment by moon0326** [comment]
> Hi @rrennick, do you have any update on this issue? Will we have a RC2 so we can re-test it?
> 
> For more context, this bug prevents the [WPML](https://wpml.org/) user from opening a translation job (it just makes WPML unusable).

Hi @strategio 

Sorry for the delay in response. It looks like I made a mistake when I opened my [PR](https://github.com/woocommerce/woocommerce/pull/48163). It did not connect the issue with it.

The [fix](https://github.com/woocommerce/woocommerce/pull/48163) has been merged and it'll be included in the next RC.

Please let us know if you have any questions or concerns.

Thanks!

**Comment by strategio** [comment]
Thank you @moon0326! We'll check the next RC version when it's out :)

**Comment by rrennick** [comment]
@moon0326 Should this be closed as addressed?

**Comment by moon0326** [comment]
@rrennick Sorry for the delay in response. Yup! I can close it.
