### ISSUE TITLE
PHP Deprecated Error in Filter 'woocommerce_get_price_html'

### ISSUE THREAD

**Issue by ajaymaravind** [woothemes/woocommerce#48173]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

https://woocommerce.github.io/code-reference/files/woocommerce-includes-abstracts-abstract-wc-product.html#source-view.1875

apply_filters( ‘woocommerce_get_price_html’, $price, $this );

The above filter is giving error while using in extension and theme. We need to switch position of price and product variable in core. Below is the newrelic finding:

The stack trace indicates that there is a deprecation warning in a PHP application. The warning message states that an optional parameter $price is declared before a required parameter $product, which is not allowed in PHP. This can cause issues because PHP requires that all optional parameters come after any required parameters in a function’s signature.
The stack trace indicates that there is a deprecation warning in a PHP application. The warning message states that an optional parameter $price is declared before a required parameter $product, which is not allowed in PHP. This can cause issues because PHP requires that all optional parameters come after any required parameters in a function’s signature.

Root Cause: The root cause of this issue is a PHP function definition that incorrectly places an optional parameter before a required parameter. This is against PHP’s function declaration rules and has been deprecated.

Potential Solutions: To resolve this issue, you should modify the function definition so that all required parameters come before any optional parameters. Specifically, you should check the function that includes the $price and $product parameters and rearrange them accordingly.

### Expected behavior

No PHP error while using the mentioned filter

### Actual behavior

Error thrown while using this filter

### Steps to reproduce

Use the filter in a theme function to enhance the functionality. 
Load the website page where pricing is shown/ filter is applicable. 
Error recorded in APM(new relic)

PHP version: 8.1

### WordPress Environment

WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.4.4 - There is a newer version of WordPress available (6.5.3)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.28
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-0ubuntu0.20.04.2
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: wp_
Total Database Size: 609.30MB
Database Data Size: 412.96MB
Database Index Size: 196.34MB

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment]
Hi @ajaymaravind, thanks for the report!

I tested the filter and didn't get any warning. Can you please share an example snippet that triggers the warning?

**Comment by tjcafferkey** [comment]
I have also tested this filter and did not get any warning. Is it possible that this error is triggered by another filter or callback somehow?

I'm going to close this issue for now, but please feel free to reopen if you're still experiencing this issue and can provide more information.
