### ISSUE TITLE
Unable to upload larger files as downloads

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#48170]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm getting an error when I try to upload files larger than 20MB to be sold as downloads. I don't see any browser console errors or failed network requests.

### Expected behavior

Allow me to upload files with larger than 20 MB

### Actual behavior

It shows a snackbar with an error message, and it doesn't allow me to upload files.

<img width="1754" alt="Captura de ecrã 2024-06-05, às 10 47 25" src="https://github.com/woocommerce/woocommerce/assets/3380168/a98aa8a4-7b8f-46a2-861b-cd94bbeebfab">

### Steps to reproduce

1. Create a test store and enable the new product creation experience
2. Go to the new experience and toggle the downloads option
3. Try to upload a zip file larger than 20MB
4. See snackbar with error

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment]
Closed. This was addressed in the following PRs:

- https://github.com/woocommerce/woocommerce/pull/48396
- https://github.com/woocommerce/woocommerce/pull/48399
