### ISSUE TITLE
New Product Editor: Missing Tooltip to Add Variations

### ISSUE THREAD

**Issue by alvarothomas** [woothemes/woocommerce#48261]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There's no tooltip letting the user know how to fill a new product variations. For example, trying with '|' instead of a comma, seems to be possible and that the variation is indeed added, but the Variations section remains empty as a result.

### Expected behavior

There's a tooltip as in the old product editor, indicating the user that a comma symbol ',' needs to be used to add possible product variations.

### Actual behavior

There are no captions or tooltip letting the user know how to add variations. Using the old product editor way (adding variations with the '|' symbol) results into an empty Variations section.

https://github.com/woocommerce/woocommerce/assets/29686881/40841358-3654-4b31-bda5-eeca37352d3d

### Steps to reproduce

PRE: New Product Editor is enabled under wp-admin/admin.php?page=wc-settings&tab=advanced&section=features

1. Go to Products -> Add New (/wp-admin/admin.php?page=wc-admin&path=%2Fadd-product)
2. Click on "Add options" button.
3. Notice the variations menu. Look for a tooltip letting the user know how to proceed.
4. Add a variation like, for example: `Color`.
5. Then add its possible values as in the old editor: red | green | yellow.
6. Click "Add".
7. Notice the "Variations" section.

### WordPress Environment

- PHP 8.1
- WC 9.0.0.40
- WP 6.5.4
- JP 13.5-beta

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
Good feedback, as I assume merchants used to the classic experience will try to add options that way.


cc @j111q this is something that we need to assess.

**Comment by louwie17** [comment]
Closing this, we now have help text displayed below mentioning the separation by comma or enter key.

![Image](https://github.com/user-attachments/assets/25e9bb1a-2af8-4626-819e-233f3b4c3f8d)
