### ISSUE TITLE
New Product Editor: Glitches On Variations Value Input

### ISSUE THREAD

**Issue by alvarothomas** [woothemes/woocommerce#48269]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Entering variation values by typing and hitting 'Enter' makes them disappear, and then popping up again when entering the next value.

https://github.com/woocommerce/woocommerce/assets/29686881/456bde23-fa2c-4c21-a4bf-45fe31295529

### Expected behavior

Variations values are added as they are typed in after pressing 'Enter' key.

### Actual behavior

Variations values disappear, and then popping up again when entering the next value.

### Steps to reproduce

PRE: New Product Editor is enabled under wp-admin/admin.php?page=wc-settings&tab=advanced&section=features

1. Go to Products -> Add New (/wp-admin/admin.php?page=wc-admin&path=%2Fadd-product)
2. Click on "Add options" button.
3. Add a variation like, for example: Color.
4. Then add its possible values. For instance: red, yellow, green. Write them one by one, pressing 'Enter' after each value.
5. Notice the value that was just entered.

### WordPress Environment

PHP 8.1
WC 9.0.0.40
WP 6.5.4
JP 13.5-beta

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@mattsherman is this blocked for any particular reason?

**Comment by mattsherman** [comment]
@pmcpinto Because when we were grooming it I mentioned that there was a work-in-progress PR that addressed this. So, we blocked it until it was followed up on. 

We shouldn't block without a corresponding comment though, to give context.

That PR is:

- https://github.com/woocommerce/woocommerce/pull/47618

Unblocking this one now, and assigning to @retrofox as he has the PR in-progress.

**Comment by pmcpinto** [comment]
👍 thanks for the clarification.
