### ISSUE TITLE
Types for wooCommerce Checkout Blocks are not available for plugin developers

### ISSUE THREAD

**Issue by dkrebs** [woothemes/woocommerce#48287]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

As a developer building a payment method for wooCommerce Blocks using the [Payment Method Integration for the Checkout Block
](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md) I want to use the types defined in [payments.ts](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/types/type-defs/payments.ts). Unfortunately they seem to be exported nowhere.

### Expected behavior

I install a lib from npmjs and vscode has the types available.

### Actual behavior

I could not find any lib in npmjs which contains the types.

### Steps to reproduce

1. Follow the [docs](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md) to build a payment method
2. Use Typescript and type the payment method config object `ExpressPaymentMethodConfiguration`, tried with the following import: 
`import ExpressPaymentMethodConfiguration from '@woocommerce/block-library'`

### WordPress Environment

wooCommerce from trunk

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tarunvijwani** [comment]
@dkrebs Thank you for reaching out! 
The types available in `@woocommerce/types` package. You'll need to use the `@woocommerce/types` instead of `@woocommerce/block-library` to import the types. 

For example, to import the `ExpressPaymentMethodConfiguration` type, please try using the following import statement:

```js
import type { ExpressPaymentMethodConfiguration } from '@woocommerce/types';
```

I hope this clears your doubts. If you have any questions or need assistance with anything, please let us know.

**Comment by dkrebs** [comment]
Thanks for your answer! I cannot install the types:
```
% npm install $ % npm install @woocommerce/types
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@woocommerce%2ftypes - Not found
```

**Comment by tarunvijwani** [comment]
@dkrebs It should be installed automatically when you set up the WooCommerce plugin by following this guide: https://github.com/woocommerce/woocommerce?tab=readme-ov-file#getting-started

Note: WooCommerce repository utilizes `PNPM` to manage project dependencies.

**Comment by dkrebs** [comment]
@tarunvijwani This may be true for developers contributing to wooCommerce. But how is it intended to use the types in plugins extending wooCommerce, i.e. a payment plugin?

**Comment by ralucaStan** [comment]
@dkrebs thank you for reaching out. We have another issue with a similar request. https://github.com/woocommerce/woocommerce/issues/47154 

I am going to keep the first issue and close this one. 

@woocommerce/rubik I think we'll need to start a discussion about this soon about our options for fixing this (see https://github.com/woocommerce/woocommerce/issues/47154#issuecomment-2098844543 by @opr )
