### ISSUE TITLE
WC 9.1 (nightly) checkout block has horizontal movement 

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#48297]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since the last improvements to the checkout block with WC 9.1 nightly, there is a horizontal movement in the checkout block on mobile.

The issue seems related to the following component:
`.is-mobile .wc-block-components-form .wc-block-components-checkout-step:after, .is-small .wc-block-components-form .wc-block-components-checkout-step:after`

And in particular to its width attribute set to 200vw. By reducing it to 192vw the issue is fixed. 

### Expected behavior

the checkout block on mobile should only have vertical scroll

### Actual behavior

the checkout block has horizontal scroll as well.

https://github.com/woocommerce/woocommerce/assets/47855768/3fdcc292-c4e8-4719-9777-de661dcdf5b1

### Steps to reproduce

1 update to WooCommerce 9 beta
2. add the checkout block
3. add a product to the cart
4. proceed to checkout

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://tommasop47.sg-host.com
Site address (URL): http://tommasop47.sg-host.com
WC Version: 9.1.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6-beta1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.20
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 8.0.34-26
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.0
WC Database Prefix: xrx_
Dimensione totale database: 10.17MB
Dimensione dati database: 8.30MB
Dimensione indice database: 1.87MB
xrx_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
xrx_woocommerce_order_items: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
xrx_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
xrx_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
xrx_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_actionscheduler_actions: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
xrx_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_actionscheduler_logs: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_comments: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
xrx_jetpack_sync_queue: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
xrx_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_options: Dati: 7.08MB + indice: 0.08MB + motore InnoDB
xrx_postmeta: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
xrx_posts: Dati: 0.09MB + indice: 0.06MB + motore InnoDB
xrx_sgs_log_events: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_sgs_log_visitors: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
xrx_wc_admin_note_actions: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
xrx_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
xrx_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
xrx_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_wc_order_addresses: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
xrx_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
xrx_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
xrx_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
xrx_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
xrx_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
xrx_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
xrx_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
xrx_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 20
page: 7
post: 2
product: 10
revision: 54
shop_order_placehold: 3
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1
wp_template: 3
wp_template_part: 3

### Security ###

Secure connection (HTTPS): ❌
					Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (5) ###

Speed Optimizer: di SiteGround – 7.6.0
Security Optimizer: di SiteGround – 1.5.0
Ajax add to cart per WooCommerce: di QuadLayers – 2.3.6
WooCommerce: di Automattic – 9.1.0-dev
WordPress Beta Tester: di WordPress Upgrade/Install Team – 3.5.5

### Inactive Plugins (4) ###

Jetpack: di Automattic – 13.5
SiteGround Central: di SiteGround – 3.0.2
TikTok: di TikTok – 1.2.6
WooPayments: di Automattic – 7.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 giorni
Level threshold: –
Log directory size: 16 KB

### WC Pages ###

Shop base: #6 - /shop/
Carrello: #7 - /cart/
Pagamento: #8 - /checkout/
Il mio account: #9 - /my-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ❌ Non dichiarato

### Templates ###

Overrides: /home/customer/www/tommasop47.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/customer/www/tommasop47.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/customer/www/tommasop47.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-06-09 17:09:59 +00:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Completato: 40
Oldest: 2024-06-08 17:10:10 +0000
Newest: 2024-06-09 08:45:15 +0000

Operazione non riuscita: 1
Oldest: 2024-06-08 17:39:58 +0000
Newest: 2024-06-08 17:39:58 +0000

In attesa: 1
Oldest: 2024-06-09 17:10:10 +0000
Newest: 2024-06-09 17:10:10 +0000

### Status report information ###

Generated at: 2024-06-09 08:46:37 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Hi @tomxygen, thank you for reporting this.
I have verified the regression, and steps will be taken to fix it before the release.
