### ISSUE TITLE
Wrong CSS class in AbstractProductGrid line 461, which breaks theme.json styling

### ISSUE THREAD

**Issue by enduity** [woothemes/woocommerce#48298]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In [Line 461](https://github.com/woocommerce/woocommerce/blob/b8a6966ca6eb3514fc683ee7ddabdab485c26f9e/plugins/woocommerce/src/Blocks/BlockTypes/AbstractProductGrid.php#L461) of the `AbstractProductGrid` class, inside the `get_container_classes()` method, there's an error:

Currently, the CSS class is:
```php
"wp-block-{$this->block_name}"
```

It should be:
```php
"wp-block-woocommerce-{$this->block_name}"
```

**Reason**: The `theme.json` styling for blocks creates CSS rules based on the block's nominal class name, which follows the pattern `wp-block-[namespace]-[block name]`. For instance, for the `product-new` block, a rule is generated for `wp-block-woocommerce-product-new`. Since the current code renders the `product-new` block with the class `wp-block-product-new`, the theme-based custom styles are not applied correctly.

Additionally, this issue might also be present in the `ClassicShortcode` and `ProductCategories` classes, as they use the same `get_container_classes()` method without the correct class names included in the array. However, I have not verified this.

### Expected behavior

I add custom styles for the `woocommerce/product-new` block type in my theme's `theme.json` and the changes appear on the published website.

### Actual behavior

The changes do appear in the editor, but not on the published website.

### Steps to reproduce

1. Setup WordPress and WooCommerce
2. Add the "Newest products" block somewhere on the website
3. Edit the `theme.json` of the current theme, adding this under `"styles" -> "blocks"`:
```json
"woocommerce/product-new": {
    "elements": {
        "button": {
            "color": {
                "background": "red !important"
            }
        }
    }
}
```
4. Notice how the buttons are red in the block editor, but not on the published website

To see the expected behavior, modify `woocommerce/src/Blocks/BlockTypes/AbstractProductGrid.php` manually and notice how the buttons are now also red on the published website.

### WordPress Environment

I have isolated the specific line of code, I do not believe a system status report is necessary at this point.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment]
Hi @enduity,

Thanks for your report, I can confirm the issue and submit a PR fixing it. Please see #50697 for more details.
