### ISSUE TITLE
CYS loading screen images flicker

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#48301]
### Issue Description:

Customize your store's loading screen images flicker, reproducible as of `9.1.0-dev-9412095893-g64615eb`:

https://github.com/woocommerce/woocommerce/assets/3747241/e57c836b-d0a7-40bf-8deb-46c8a6265754

### To reproduce:

1. Go to WooCommerce > Home
1. Skip profiler or don't opt-in to tracks
3. Click on `Customize your store` task
4. Click on "Start designing"
5. Observe the loading images flicker

**Comment by Aljullu** [comment]
Thanks for opening this issue, @ilyasfoo! Unfortunately, I don't seem to be able to reproduce, the _Setting up the foundations_ image is always visible.

Pinging @nefeline @gigitux and @albarin in case they have an idea of what might be going on.

**Comment by gigitux** [comment]
@ilyasfoo Did you have the dev Tools opened with the disable cache enabled? If so, can you try enabling the cache? 

![e5KiNJ.png](https://github.com/woocommerce/woocommerce/assets/4463174/0812c161-e196-46ff-bc48-c412706f1172)

**Comment by ilyasfoo** [comment]
> @ilyasfoo Did you have the dev Tools opened with the disable cache enabled? If so, can you try enabling the cache?

@gigitux Ah, yes it does not flicker when caching is enabled. Still, I think that may be a sign of the image component being re-rendered unnecessarily?

**Comment by gigitux** [comment]
> Ah, yes it does not flicker when caching is enabled. Still, I think that may be a sign of the image component being re-rendered unnecessarily?


I created a PR https://github.com/woocommerce/woocommerce/pull/48460. Can you take a look when you have some time?

**Comment by gigitux** [comment]
I added the label `focus: customize-your-store`

**Comment by ilyasfoo** [comment]
@gigitux Thanks for fixing it so quickly, took a quick look at your PR and looks good 👍
