### ISSUE TITLE
Placing an order on Checkout Blocks won't trigger the woocommerce_new_order hook when using CPT

### ISSUE THREAD

**Issue by wavvves** [woothemes/woocommerce#48343]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Placing an order on Checkout Blocks won't trigger the woocommerce_new_order hook when using CPT

### Expected behavior

The hook `woocommerce_new_order` should be triggered, and the error log should print information about the order.

### Actual behavior

The woocommerce_new_order hook is not triggered

### Steps to reproduce

1. Install the Debug Log Manager extension
2. Using the Code Snippets extension add the following snippet
```php
add_action( 'woocommerce_new_order', 'any', 20, 1 );
function any( $order_id ) {
	error_log( 'Order ID: ' . $order_id . ' with status: ' . get_post_status( $order_id ) );
}
```
3. Go to WooCommerce > Settings > Advanced > Features
4. Enable `WordPress posts storage (legacy)`
5. Place an order using the Checkout Blocks
6. Go to /wp-admin/tools.php?page=debug-log-manager and verify that no error is present confirming the new order hook wasn't triggered.,

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
Related to #48342. This looks like it's the same issue occurring in a different location.

**Comment by wavvves** [comment]
> Related to #48342. This looks like it's the same issue occurring in a different location.

These are all new finds coming from #47422 affecting that hook not being triggered. To ship more granular and testable work they have been broken apart into different issues.
pca54o-7Pu-p2
