### ISSUE TITLE
In the admin, changing an order from draft to completed doesn't trigger anything when using CPT

### ISSUE THREAD

**Issue by wavvves** [woothemes/woocommerce#48342]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When CPT is enabled for orders, changing a draft order into the complete status won't trigger the `woocommerce_new_order`hook.

### Expected behavior

The hook `woocommerce_new_order` should be triggered, and the error log should print information about the order.

### Actual behavior

The `woocommerce_new_order` hook is not triggered

### Steps to reproduce

1. Install the Debug Log Manager extension
2. Using the Code Snippets extension add the following snippet
```php
add_action( 'woocommerce_new_order', 'any', 20, 1 );
function any( $order_id ) {
	error_log( 'Order ID: ' . $order_id . ' with status: ' . get_post_status( $order_id ) );
}
```
3. Go to WooCommerce > Settings > Advanced > Features
4. Enable WordPress posts storage (legacy)
5. Go to WooCommerce > Orders and click `Add Order`
6. Change the order status to draft and click `Create`
7. Go to `/wp-admin/tools.php?page=debug-log-manager` and clear the log
8. Go back to WooCommerce > Orders open the just created draft order and change the status to completed. Save the changes
9. Go to `/wp-admin/tools.php?page=debug-log-manager` and verify that no error is present confirming the new order hook wasn't triggered.,

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
> 6. Change the order status to draft and click Create
> 7. Go to /wp-admin/tools.php?page=debug-log-manager and clear the log

To clarify, is this step needed because `woocommerce_new_order` *is* fired in relation to the draft being created?
