### ISSUE TITLE
Products get converted from `product` to `product_form` post type after switching themes

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#48375]
This is a weird issue I have been trying to debug for a few hours with no luck yet. For some reason, the post type of existing products changes from `product` to `product_form` when switching themes (I tried with TT4 to TT3, but I think it's reproducible in other combinations of themes).

## Steps to reproduce

https://github.com/woocommerce/woocommerce/assets/3616980/e1044ef3-cc6d-4847-ba00-80ea66ce9553

1. Create a new WordPress site from scratch.
2. Install WooCommerce `trunk` and enable it.
3. Create an example product.
4. Visit the product in the frontend. Everything will look alright.
5. Now, switch the store theme from TT4 to TT3.
6. Visit the product you created in step 3 again.
7. You will see a 404 error.
8. If you `print_r( $wp_query )`, it looks like this:

```
WP_Query Object
(
    [query] => Array
        (
            [page] => 
            [product_form] => example-product
            [post_type] => product_form
            [name] => example-product
        )

    [query_vars] => Array
        (
        ...
```

Notice for some reason the `post_type` changed from `product` to `product_form`.

---

Some other findings:

1. Newly created products are affected as well, they are created with `product_form` as the post type.
2. While debugging, I could get the error fixed so new products were created with `product` post type. I'm not sure what solved it, though. I think it was a mix between switching themes and navigating through the repo history.

I still couldn't figure out what's going on and when this issue was introduced, but cc'ing @retrofox as it looks like you worked in this area recently.

**Comment by retrofox** [comment]
Thanks @Aljullu for the report.
QQ:  Is the `product-editor-template-system` feature flag enabled?
It should be `false` as default. Asking because this feature is hidden behind that feature.

**Comment by Aljullu** [comment]
It's set to true, I guess because I'm using a dev build of `trunk`?

**Comment by retrofox** [comment]
Probably. The feature flag is enabled only in the development environment. So I guess if the system considers that _dev build of `trunk`_, then the feature would be enabled?
First thing that we'll do is disabled the feature as default, even for dev-env.

**Comment by retrofox** [comment]
#48378 is RfR, if you have the chance :-)

**Comment by retrofox** [comment]
#48378 is merged. You shouldn't see that anymore in dev trunk since the feature flag is now disabled even for this environment.

Now we'll continue to address the issue.

**Comment by retrofox** [comment]
second one should close this issue 🤞
