### ISSUE TITLE
Function wp_get_attachment_image_url issue with FSE themes

### ISSUE THREAD

**Issue by n0th** [woothemes/woocommerce#48417]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you use the function wp_get_attachment_image_url on a FSE theme it turns out that when it returns the address and the image has the typical size information, the ‘x’ that separates the sizes is not the letter ‘x’, it is a multiplication symbol. They look the same but are not, which makes the address completely useless. 

### Expected behavior

Receive same information from a function does not matter the type of theme used.

### Actual behavior

If you have a classic theme the output its ok, if you use a FSE theme the output its different.

### Steps to reproduce

1.- Activate a FSE theme (Twenty Twnety-Four for example.
2.- Use the function to recevi thumbnails url for a resize image.
3.- Put the url receive into the browser to check that it does not exists due the x symbol.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://wordpress-560181-4620892.cloudwaysapps.com
Site address (URL): https://wordpress-560181-4620892.cloudwaysapps.com
WC Version: 8.9.3
REST API Version: ✔ 8.9.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Debian)
PHP Version: 8.1.29
PHP Post Max Size: 100 MB
PHP Time Limit: 400
PHP Max Input Vars: 2500
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.34-MariaDB-1:10.4.34+maria~deb10-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@n0th Thanks for reporting the issue. Is this issue related to WooCommerce? Based on your description, this looks like a core WP issue.

**Comment by n0th** [comment]
Hi!, oh yes sorry I confused as I also was using the wc get products, Il cancel it.

**Comment by n0th** [comment]
Wrong forum,

**Comment by n0th** [comment]
Wrong forum.
