### ISSUE TITLE
[CYS]: Shuffle feature should be available when the user hovers header and footer

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#48439]

**Comment by gigitux** [comment]
Given that https://github.com/WordPress/gutenberg/issues/61105#issuecomment-2454146992 has been closed, what do you think if we close this issue too? cc @Aljullu @mdperez86

**Comment by Aljullu** [comment]
It makes sense to me. Thanks for keeping up with these issues, @gigitux! 🙌
