### ISSUE TITLE
[BUG]: Coupon email restrictions not correctly validating customer emails

### ISSUE THREAD

**Issue by EstianH** [woothemes/woocommerce#48459]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a customer is logged-in and attempts to apply a coupon that is restricted by email in their cart the coupon does not correctly validate the logged-in customer's profile or billing email addresses.

### Expected behavior

A coupon with an email restriction should correctly validate and be redeemable if a customer is logged in with the restricted email or has the restricted email saved as their billing email.

### Actual behavior

Coupons that are saved with email restrictions do not correctly validate with logged-in customer profile or saved billing email addresses.

### Steps to reproduce

1. Create a new coupon and save "_test@test.test_" to the "_Allowed emails_" field under "_Usage restriction_".
![image](https://github.com/woocommerce/woocommerce/assets/17120180/77593a43-f680-47be-9eee-30f914e16bac)
2. Create a new customer account with the "_test@test.test_" email address.
![image](https://github.com/woocommerce/woocommerce/assets/17120180/ae5b3812-a420-44c7-8153-26093775de25)
3. [Optional] Update the newly created customer account's billing email address to "_test@test.test_".
![image](https://github.com/woocommerce/woocommerce/assets/17120180/5ed00fbb-54e9-421c-8fe5-8e6224544c84)
4. Log in with the newly created customer account.
5. Add any priced product to your cart.
6. Navigate to the cart page.
7. Apply the above newly created coupon to the cart.
![image](https://github.com/woocommerce/woocommerce/assets/17120180/07362d23-0d1f-427a-a9a4-491a2716db39)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://wordpress.local
Site address (URL): http://wordpress.local
WC Version: 8.9.3
REST API Version: ✔ 8.9.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.3
PHP Version: 8.2.3
PHP Post Max Size: 500 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 8.0.32
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.0
WC Database Prefix: wp_
Total Database Size: 7.20MB
Database Data Size: 5.35MB
Database Index Size: 1.85MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpsmtp_logs: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
guest_author: 1
page: 7
post: 3
product: 10
product_variation: 3
revision: 2
shop_coupon: 1
shop_order: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.9.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 32 KB

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /cart/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/wp/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/wp/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/wp/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2023-09-26 12:37:18 +00:00
Options: ✔
Notes: 75
Onboarding: skipped

### Action Scheduler ###

Pending: 25
Oldest: 2023-09-26 12:37:20 +0000
Newest: 2024-06-13 07:53:24 +0000

### Status report information ###

Generated at: 2024-06-13 07:59:26 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tarunvijwani** [comment]
@EstianH, Thank you for reporting the issue. Unfortunately, I'm unable to reproduce it. Could you please provide your testing site URL and WooComerce system report?

**Comment by EstianH** [comment]
> @EstianH, Thank you for reporting the issue. Unfortunately, I'm unable to reproduce it. Could you please provide your testing site URL and WooComerce system report?

Hi @tarunvijwani , thank you for the feedback.
The WooCommerce system report has already been attached to this ticket.
I am able to reproduce this issue on my local machine with a clean WordPress & WooCommerce install, with no other active plugins.

**Comment by tarunvijwani** [comment]
@EstianH Oh sorry, I missed checking the system report with the issue. Here are the steps I'm following to reproduce this bug on WooCommerce 8.9.3: 


https://github.com/woocommerce/woocommerce/assets/11503784/32780b1c-a620-44f3-9e6a-2721639f2629

Am I missing any step? While creating the new user, did you select the `customer` as their role? If not, please try changing their role to customer.

**Comment by EstianH** [comment]
@tarunvijwani Thank you again for the feedback as well as the attached video.
I've followed your video and done this testing on my end as well and can confirm that when creating a new user (_customer_) the email address field and billing email address fields are filled in with the _test@test.test_ email.
On checkout the coupon is then validated correctly with the new user thanks to the below line:
`$check_emails[] = $this->object->get_customer()->get_billing_email();`
(class-wc-discounts.php:975)
The bug remains below in that the _$user object_ does not correctly return the billing email or profile email addresses:
`$check_emails = array( $user->get_billing_email(), $user->get_email() );`
(class-wc-discounts.php:972)
A user that is logged into an account with the _test@test.test_ email address will not be able to redeem the restricted coupon if the billing email address field is not filled in, for instance.

Please test by removing the billing email address from the account and re-try redeeming the coupon by validating the profile email address field.

**Comment by wavvves** [comment]
Hi @EstianH thank you for reporting this. Unfortunately I am not able to reproduce this. Following the step by step instructions, and skipping the optional step #3 of adding the billing email, I was able to apply the coupon on cart successfully

<img width="300" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17236129/e1bfbcc9-9bbe-4a2a-a3b0-bc7ee8ec7322">

Is there any possibility of retrying this on a fresh install with no plugins?
Also, a long shot but, are you using a dev version for woocommerce (eg cloned from the github repo)?
If so, try running the following and clearing browser cache before retrying:

`pnpm clean && pnpm install && pnpm build`

**Comment by EstianH** [comment]
Hi @wavvves, thank you for your feedback.
Skipping step 3 as per the initial steps unfortunately will not allow us to replicate the bug.
As we now know my initial steps were faulty, specifically step 3.

Please see the below revised steps on a clean WP & WC install:
1. Create a new coupon and save "_test@test.test_" to the "Allowed emails" field under "Usage restriction".
![image](https://github.com/woocommerce/woocommerce/assets/17120180/6d4e21e4-a93a-4f88-a56c-6830a20d3cc5)
2. Create a new customer account with the "_test@test.test_" email address.
![image](https://github.com/woocommerce/woocommerce/assets/17120180/1dda5d95-a9fc-4dd2-9113-83f4b21e06ad)
3. Edit the above created account by removing/editing the **_billing_** email address to "_willnotvalidate@test.test_". Confirm the change.
![image](https://github.com/woocommerce/woocommerce/assets/17120180/16619aa0-80fc-4bee-b043-4b57b0b912de)
4. Log in with the newly created customer account.
5. Add any priced product to your cart.
6. Navigate to the cart page.
7. Apply the above created coupon to the cart.
![image](https://github.com/woocommerce/woocommerce/assets/17120180/c01289f4-d1a9-4825-ac19-8664cc40039f)

I have reinstalled a new local environment with WooCommerce, see below:
- WordPress v.6.5.4
- WooCommerce v.9.0.0
- No other plugins
- Default 2024 theme

Find the newly generated system report attached.
[SystemStatusReport_wordpress.local_2024-06-20T06-58-17.txt](https://github.com/user-attachments/files/15910051/SystemStatusReport_wordpress.local_2024-06-20T06-58-17.txt)

--

As per my initial ticket description, the below line is responsible for the bug:
`$check_emails = array( $user->get_billing_email(), $user->get_email() );`
class-wc-discounts.php:973

**Comment by tarunvijwani** [comment]
Thank you for sharing the steps again! I'm able to reproduce the issue. I think this is the expected behavior. We're checking against the allowed billing address email, not the customer account email address. 

Here is the screenshot: 
<img width="859" alt="image" src="https://github.com/woocommerce/woocommerce/assets/11503784/1d89df9a-bd97-4244-817e-dbd357a692e5">


If we keep the billing address the same as the allowed email, it works as expected: 

https://github.com/woocommerce/woocommerce/assets/11503784/fd46be30-5fc2-4c7a-ab86-e0cc1d66e571


Let's wait for @nikkivias to confirm this.

**Comment by tarunvijwani** [comment]
@nikkivias Here is the summary: 

For coupon restriction validations, the coupons are currently checked against the billing email address of the customer, not the customer's profile email address.

In this scenario, the customer profile email address is the allowed email address, but a different billing email address is used. We believe that declining the coupon in this situation is the expected behavior, as indicated by the details in the allowed email section. We would really appreciate your opinion on this. 

![image](https://github.com/woocommerce/woocommerce/assets/11503784/e6123638-96cf-4f7b-8e77-0d557c60a36e)

**Comment by EstianH** [comment]
Thank you @tarunvijwani for the follow up.
I just wanted to add that when you look at the implemented code the validation is surely meant to validate both the account email address and the billing email address, as per the below line:
`$check_emails = array( $user->get_billing_email(), $user->get_email() );`
class-wc-discounts.php:973

If indeed the expected behaviour is as per your feedback, this line should be removed/modified regardless as it is returning _(bool) false_ and _(bool) false_ as the "_WP_User_" class is incorrectly used here; The correct class to use for the "get_billing_email()" and "get_email()" methods would be the "_WC_Customer_" class.
Please refer to my PR #48488.

**Comment by wavvves** [comment]
Indeed @EstianH it will return false. So to sum it up, if the user wants to supply a different billing email, but the coupon actually belongs to his account email (so still the owner) it will fail to validate. Nice find 👏💪

I'm reviewing your PR right now, there might be a way without resorting to instantiate WC_Customer and we just might have to add some tests to catch this in the future ;)
