### ISSUE TITLE
Error after setting a regular price >= 20 characters

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#48481]
There is an error when adding a price with a length of 20 digits or more.

https://github.com/woocommerce/woocommerce/assets/1314156/525897cb-63bb-4974-b292-a5dc804789ed

This issue happens consistently when handling prices (both regular and sale prices):
- Under the `General` tab in simple products.
- When editing a single variation.
- Under the `Variations` tab, when editing prices inline.

### Steps to reproduce

1. Be sure you enabled tracks under `WooCommerce` > `Settings` > `Advanced` > `WooCommerce.com` > `Enable tracking`.
2. Go to `Products` > `Add New`.
3. Add a product name and a price with a length of 20 digits or more.
4. See the error

### WordPress Environment

This is happening on `trunk`.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by retrofox** [comment]
We want a simple validation so far, like a maximum of 19 characters in length.
