### ISSUE TITLE
[DOC-BUG] broken link to `class-wc-install.php` file.

### ISSUE THREAD

**Issue by ericmutta** [woothemes/woocommerce#48484]
## Link to the Page/Section

https://github.com/woocommerce/woocommerce/wiki/Database-Description#source-file

## Description of the Suggestion

The link to the `includes/class-wc-install.php` file is currently as follows:

```
https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-install.php
```

...but that is giving me a 404 error as follows:

![image](https://github.com/woocommerce/woocommerce/assets/20465797/b740cb60-1d2d-4fca-b471-b5655c239e37)

It looks like the files may have been moved to a `plugins` subfolder at some point (I am not sure, this is my first time looking at this project), so the correct link should be changed to this I think:

```
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-install.php
```

## Reason for the Suggestion

It will help new users (like myself) look into the code where the database schema is defined.

## Additional Context

See above.

**Comment by barryhughes** [comment]
Thank you, updated!

**Comment by ericmutta** [comment]
Thank you @barryhughes ✅
