### ISSUE TITLE
payment_method_selected JavaScript event no longer triggered when using blocks-based checkout

### ISSUE THREAD

**Issue by alex-georgiou** [woothemes/woocommerce#48497]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If I need to recalculate the shipping costs whenever a payment method is selected, with classic checkout I could do this:

    $('.woocommerce-checkout').on('payment_method_selected', function() {
        setTimeout(function() {
            $('body').trigger('update_checkout');
        }, 100);
    });

With blocks, this doesn't seem to work. This is because in `assets/js/frontend.js` the event is triggered only if there is a (radio) input with `name="payment_method"` and there is no such input when using blocks in the checkout.

Is this a bug or intended behavior? What's the recommended way to capture such frontend events now?

### Expected behavior

I expected to be able to capture using JavaScript code the `payment_method_selected` event when switching between available payment methods.

### Actual behavior

The event is not triggered when using blocks, only with classic checkout it is triggered.

### Steps to reproduce

1. On a site with the twentytwentyfour theme installed, attach a script with the above JS code, capturing the `payment_method_selected` bubbling event.
2. Go to checkout page
3. Change payment method
4. The event is not triggered.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://demo.shippingcalculators.gr
Site address (URL): https://demo.shippingcalculators.gr
WC Version: 8.9.3
REST API Version: ✔ 8.9.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 8.2.13
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 8.2.0
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.3
WC Database Prefix: wp_
Total Database Size: 9.13MB
Database Data Size: 7.35MB
Database Index Size: 1.78MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.03MB + Index: 0.08MB + Engine InnoDB
wp_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_post_smtp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 3
product: 7
revision: 6
shop_order_placehold: 2
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 3
wp_template: 2
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

Post SMTP: by Post SMTP – 2.9.4
ELTA Courier Shipping Costs: by Alexandros Georgiou  – 0.1.1-beta
Jetpack: by Automattic – 13.5
WooPayments: by Automattic – 7.7.0
WooCommerce Shipping & Tax: by WooCommerce – 2.6.0
WooCommerce: by Automattic – 8.9.3
WP Console: by Edi Amin – 2.4.1

### Inactive Plugins (7) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Google Listings and Ads: by WooCommerce – 2.7.2
Hello Dolly: by Matt Mullenweg – 1.7.2
MailPoet: by MailPoet – 4.51.2
Pinterest for WooCommerce: by WooCommerce – 1.3.24
TikTok: by TikTok – 1.2.6
WP Mail SMTP: by WP Mail SMTP – 4.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 105 KB

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four Child
Version: 1.0.0
Author URL: https://alexgeorgiou.gr
Child Theme: ✔
Parent Theme Name: Twenty Twenty-Four
Parent Theme Version: 1.1
Parent Theme Author URL: https://wordpress.org
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php

### WooPayments ###

Version: 7.7.0
Connected to WPCOM: ❌ No
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-06-15 09:43:19 +00:00
Options: ✔
Notes: 67
Onboarding: completed

### Action Scheduler ###

Complete: 56
Oldest: 2024-06-05 09:43:25 +0000
Newest: 2024-06-14 10:47:15 +0000

Failed: 47
Oldest: 2024-06-05 09:45:18 +0000
Newest: 2024-06-14 10:36:39 +0000

Pending: 6
Oldest: 2024-06-14 11:36:39 +0000
Newest: 2024-06-17 14:00:00 +0000

### Status report information ###

Generated at: 2024-06-14 10:56:20 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tarunvijwani** [comment]
@alex-georgiou Thank you for reaching out. For the block-based checkout, you may use the `getActivePaymentMethod` selector of the Payment Store to retrieve the selected payment method. Here is the example code that you may use:


```js

const store = select( PAYMENT_STORE_KEY );
const activePaymentMethod = store.getActivePaymentMethod();

useEffect(() => {
    console.log('Recalculate the shipping costs for active payment method:', activePaymentMethod);
}, [activePaymentMethod]);
```

You can read more about the available selectors for the Payment Store here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/data-store/payment.md#table-of-contents- 


I hope this helps! If you have any questions or need any assistance, please let us know.

**Comment by alex-georgiou** [comment]
Thank you for the reply @tarunvijwani. It seems like I have some reading to do.

~~One question: Does the above mean that I need to create a new block? My plugin does not require any custom UI in the frontend. I am simply trying to interact with the existing cart and checkout blocks.~~

Please disregard my previous question. I would appreciate some more help with this.

I am trying to implement the above code. Assuming I manage to get to the `console.log` part, how would I trigger a recalculation of the checkout? Is there something equivalent to `trigger('update_checkout');`? I don't want to pass any new parameters, just to force the recalculation to occur with the new payment method.

I have also tried passing a dummy value (current timestamp) to `woocommerce_store_api_register_update_callback()` but to no effect. This only controls what data is passed to the backend when the update occurs, but does not trigger an update.

For context, my shipping costs calculation needs to add an additional charge in case the payment method "Cash on Delivery" is selected, because the courier company charges extra for this. I am still not sure how to achieve this.

Any help greatly appreciated.

**Comment by tarunvijwani** [comment]
@alex-georgiou If you just want to trigger the update, then I would recommend using `extensionCartUpdate`. Since you mentioned you already tried using `woocommerce_store_api_register_update_callback()`, could you please share the JS and PHP code you're using? 

Here is the sample code that might help: 
PHP:

```php

function recalculate_shipping_for_cod() {
  
    // Your custom code before recalculate totals

    // Recalculate the cart totals
    WC()->cart->calculate_totals();
}


add_action('woocommerce_blocks_loaded', function() {
    woocommerce_store_api_register_update_callback(
        [
            'namespace' => 'custom-namespace',
            'callback'  => 'recalculate_shipping_for_cod',
        ]
    );
});

```


JS:

```js

const { extensionCartUpdate } = window.wc.blocksCheckout;

const updateCartForCod = () => {
    extensionCartUpdate({
        namespace: 'custom-namespace',
        data: {}, // No new data needed
    });
};

```

You can learn more about it here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md

**Comment by alex-georgiou** [comment]
Thank you @tarunvijwani .

I hadn't realized that I needed to learn React for this, so I took some time to skim through some tutorials, but I'm still not sure what I'm doing.

I did go through the tutorial for building a WordPress block, but I'm still not sure that I need to create a block for this.

I have come up with the following code that doesn't work, but maybe it's salvageable?

The PHP code:
```php
<?php
/**
 * Plugin Name: WC Block Checkout Update on Payment Change Plugin
 * Description: A plugin to update the block checkout totals whenever the payment method is changed.
 * Version: 1.0
 */

if ( ! defined('ABSPATH') ) {
    exit;
}

function wc_block_checkout_plugin_enqueue_scripts() {

    if ( ! class_exists('WooCommerce') || ! class_exists('Automattic\WooCommerce\Blocks\Package' ) ) {
        return;
    }

    wp_enqueue_script(
        'wc-block-checkout-update-plugin-script',
        plugin_dir_url( __FILE__ ) . 'assets/js/wc-block-checkout-update-plugin.js',
        array( 'wp-blocks', 'wp-element', 'wp-components', 'wp-data', 'wp-plugins', 'wc-blocks-checkout' ),
        filemtime( plugin_dir_path( __FILE__ ) . 'assets/js/wc-block-checkout-update-plugin.js' ),
        true
    );
}
add_action(
    'enqueue_block_assets',
    'wc_block_checkout_plugin_enqueue_scripts'
);

function recalculate_shipping_for_cod() {
    WC()->cart->calculate_totals();
}


add_action(
    'woocommerce_blocks_loaded',
    function() {
        woocommerce_store_api_register_update_callback(
            [
                'namespace' => 'wc-block-checkout-update-plugin',
                'callback'  => 'recalculate_shipping_for_cod',
            ]
        );
    }
);
```

And the JavaScript code:

```js
(function(wp) {

    const { select } = wp.data;
    const { useEffect } = wp.element;

    const { extensionCartUpdate } = wc.blocksCheckout;
    const { PAYMENT_STORE_KEY } = wc.wcBlocksData;

    const store = select( PAYMENT_STORE_KEY );
    const activePaymentMethod = store.getActivePaymentMethod();

    var PaymentMethodChangeHandler = function () {
        console.log('Payment Method Change Handler running');

        useEffect(() => {
            console.log('Recalculating the shipping costs for active payment method:', activePaymentMethod);

            extensionCartUpdate({
                namespace: 'wc-block-checkout-update-plugin',
                data: {}, // No new data needed
            });

        }, [activePaymentMethod]);

        return null;
    };

    var initializeExtension = function () {
        console.log('Initializing extension...');

        var checkoutWrapper = document.querySelector('.wc-block-checkout');
        var div = document.createElement('div');
        checkoutWrapper.insertBefore(div, checkoutWrapper.firstChild );


        if ( checkoutWrapper ) {

            const root = wp.element.createRoot(div);
            root.render( PaymentMethodChangeHandler );

            console.log('Initialized extension');
        }
    };

    document.addEventListener('DOMContentLoaded', initializeExtension);

})(window.wp);
```

In the browser console, I see the message "Initialized extension" but not "Payment Method Change Handler running".

To reiterate my requirement: every time the user changes a payment method, I would like the shipping calculators to run again. One of the inputs of the shipping calculator that determines the shipping cost, is whether the payment method is Cash on Delivery or not.

I realize now that the issue is me not having thoroughly studied React yet. If the fix to my code is something simple, please advise, otherwise we can close this ticket and I will ask for help elsewhere.

Thank you for your help in any case.

**Comment by mikejolley** [comment]
You don't need to look at the DOM elements or render anything your side. You only need to:

1. Hook into the checkout events with a callback on the javascript side. This fires off the request to server.
2. Have a callback server side do any calculations e.g. adding fees

Here is a more full example of adding fees:

https://gist.github.com/mikejolley/f185f73f0046353f05773843bd153a9a

I guess in your case the API request is enough?

Related issues and tutorials:

- https://www.tychesoftwares.com/how-to-add-woocommerce-checkout-fees-based-on-shipping-method-payment-method/
- https://github.com/woocommerce/woocommerce/issues/42185#issuecomment-1862769537
- https://github.com/woocommerce/woocommerce/issues/42809
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/rest-api/extend-rest-api-add-data.md

**Comment by alex-georgiou** [comment]
Thank you @mikejolley , the solution you provided is exactly what I was looking for.

I appreciate the help very much!
