### ISSUE TITLE
[Bug]: My Account / Order view throws 500 error when using a block theme and a plugin that hooks into that same template

### ISSUE THREAD

**Issue by mlaetitia** [woothemes/woocommerce#48505]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The myaccount/view-order.php (frontend ) of one of our sites is going into loop mode / exhausting memory - freezing OR throwing a 500 (depending on the scenario).

There's a filter function in woocommerce `plugins/woocommerce/src/Blocks/Domain/Services/Notices.php` hooked to `wc_get_template` . [This function](https://github.com/woocommerce/woocommerce/blob/cac7e0dfe9909cdcee941a7803cbb7048ef5037a/plugins/woocommerce/src/Blocks/Domain/Services/Notices.php#L106) `get_notices_template` receives a template and based on some logic returns another (or the same) file template. This function uses `get_stylesheet_directory` to get the style folder and checks whether that template exists in the custom theme. If it does, it returns that theme's template file - if not it returns the same template that was given as input.

The issue here is that this function is also called in other instances, including if the `wc_get_template` is used to include a plugin template. If the plugin template has the same name as a theme custom template (like the `view_order.php`) this function returns the theme template instead - which can cause a loop or a 500 error (most common) as the theme will be called without context.

_**Please note that this is only reproducible if the theme is a block theme.**_ 

### Expected behavior

 - Should see the order details / view

### Actual behavior

- 500 error after warning `Undefined variable $order in /srv/htdocs/wp-content/themes/my_custom_theme/woocommerce/myaccount/view-order.php` because the theme's custom `view-order.php` gets called without context when it should be loading the plugin template instead.

### Steps to reproduce

This is reproducible with the following setup - without any other plugins installed:

1. Standard WP installation
2. Install Woo + Create a product + Complete a purchase
3. Make sure the theme you're using is a **BLOCK THEME** and has a view-order.php in `your-theme/woocommerce/myaccount` folder. For the simplicity of testing you can actually copy the woocommerce plugin `view-order.php` template as is into that folder. This will make sure your theme's template will override the Woo one. The important thing is that the `do_action( 'woocommerce_view_order', $order_id )` is called in that template file
4. Install a plugin that overrides the `view-order.php` template as well. In our case we tested with the [Woo Shipment Tracking](https://woocommerce.com/products/shipment-tracking/) - as it was the one we were using on the site. See below for an alternative to testing without this plugin.
5. Head to the store front end - click [My Account](https://helloyumidev2.vipdev.lndo.site/my-account/) and click an order ID - this will trigger a 500 error:

```
[14-Jun-2024 17:20:35 UTC] PHP Warning:  Undefined variable $order in /srv/htdocs/wp-content/themes/my_custom_theme/woocommerce/myaccount/view-order.php on line 22
[14-Jun-2024 17:20:35 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_customer_order_notes() on null in /srv/htdocs/wp-content/themes/my_custom_theme/woocommerce/myaccount/view-order.php:22
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include()
#1 /srv/htdocs/wp-content/plugins/test-template-override-plugin/test-template-override-plugin.php(16): wc_get_template('myaccount/view-...', Array, '', '/srv/htdocs/wp-...')
#2 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): custom_function(15)
#3 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /srv/htdocs/wp-content/plugins/woocommerce/templates/myaccount/view-order.php(56): do_action('woocommerce_vie...', 15)
#6 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
#7 /srv/htdocs/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php(153): wc_get_template('myaccount/view-...', Array)
#8 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3334): WC_Shortcode_My_Account::view_order(15)
#9 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): woocommerce_account_view_order('15')
#10 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#11 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3268): do_action('woocommerce_acc...', '15')
#13 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): woocommerce_account_content('')
#14 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#15 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 /srv/htdocs/wp-content/plugins/woocommerce/templates/myaccount/my-account.php(34): do_action('woocommerce_acc...')
#17 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
#18 /srv/htdocs/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php(123): wc_get_template('myaccount/my-ac...', Array)
#19 /srv/htdocs/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php(72): WC_Shortcode_My_Account::my_account(Array)
#20 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_My_Account::output(Array)
#21 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(115): WC_Shortcodes::shortcode_wrapper(Array, Array)
#22 /srv/htdocs/__wp__/wp-includes/shortcodes.php(433): WC_Shortcodes::my_account(Array, '', 'woocommerce_my_...')
#23 [internal function]: do_shortcode_tag(Array)
#24 /srv/htdocs/__wp__/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_my...')
#25 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): do_shortcode('[woocommerce_my...')
#26 /srv/htdocs/__wp__/wp-includes/plugin.php(205): WP_Hook->apply_filters('[woocommerce_my...', Array)
#27 /srv/htdocs/__wp__/wp-includes/blocks/post-content.php(48): apply_filters('the_content', '<!-- wp:shortco...')
#28 /srv/htdocs/__wp__/wp-includes/class-wp-block.php(463): render_block_core_post_content(Array, '<!-- wp:shortco...', Object(WP_Block))
#29 /srv/htdocs/__wp__/wp-includes/blocks.php(1705): WP_Block->render()
#30 /srv/htdocs/__wp__/wp-includes/blocks.php(1743): render_block(Array)
#31 /srv/htdocs/__wp__/wp-includes/blocks/template-part.php(150): do_blocks('  <!-- wp:group...')
#32 /srv/htdocs/wp-content/plugins/woocommerce/src/Blocks/BlockTemplatesController.php(118): render_block_core_template_part(Array)
#33 /srv/htdocs/__wp__/wp-includes/class-wp-block.php(463): Automattic\WooCommerce\Blocks\BlockTemplatesController->render_woocommerce_template_part(Array, '', Object(WP_Block))
#34 /srv/htdocs/__wp__/wp-includes/class-wp-block.php(443): WP_Block->render()
#35 /srv/htdocs/__wp__/wp-includes/blocks.php(1705): WP_Block->render()
#36 /srv/htdocs/__wp__/wp-includes/blocks.php(1743): render_block(Array)
#37 /srv/htdocs/__wp__/wp-includes/block-template.php(260): do_blocks('<!-- wp:templat...')
#38 /srv/htdocs/__wp__/wp-includes/template-canvas.php(12): get_the_block_template_html()
#39 /srv/htdocs/__wp__/wp-includes/template-loader.php(106): include('/srv/htdocs/__w...')
#40 /srv/htdocs/__wp__/wp-blog-header.php(19): require_once('/srv/htdocs/__w...')
#41 /srv/htdocs/__wp__/index.php(17): require('/srv/htdocs/__w...')
#42 {main}
  thrown in /srv/htdocs/wp-content/themes/my_custom_theme/woocommerce/myaccount/view-order.php on line 22
```

If you don't have access to that plugin , you can use another - as long as :

- Create a view-order.php template on the plugin path `/templates/myaccount/view-order.php` . Can just have something like `<div>plugin template</div>`
- on the main plugin file add : `add_action( 'woocommerce_view_order', 'my_custom_function' );`
- create the `my_custom_function`. Inside add the following code:
```php
wc_get_template( 'myaccount/view-order.php', array(),'', plugin_dir_path( __FILE__ )  . '/templates/'  );
```

### WordPress Environment

Latest WP version, latest Woo version.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tarunvijwani** [comment]
Hi @mlaetitia, Thank you for reporting the issue. I was able to reproduce it. I used the same [view-order.php](https://github.com/Automattic/woocommerce.com/blob/trunk/themes/woo/woocommerce/myaccount/view-order.php) file you might be using. 

After testing, I noticed the template was called multiple times, with $order and without $order. I'm not sure at the moment why it was called without $order being set. Maybe @mikejolley could help us understand this better. 

I added the below code in the template file and it resolved the issue for me:
```php
// Make sure $order is defined
if ( ! isset( $order ) ) {
    return;
}
```

| Code | Output |
|---|---|
|![image](https://github.com/woocommerce/woocommerce/assets/11503784/6868e50c-5cae-4a32-9c50-254e972ae9f6)|![image](https://github.com/woocommerce/woocommerce/assets/11503784/cdf27d52-a279-43be-8f9a-a1ca007a8124)|


As a workaround, I would highly recommend adding the  `isset( $order )` check for now in [view-order.php](https://github.com/Automattic/woocommerce.com/blob/trunk/themes/woo/woocommerce/myaccount/view-order.php) file. I will move this bug to the backlog for the future development.

**Comment by tarunvijwani** [comment]
Internal discussion: p1718828870969939-slack-C8X6Q7XQU
