### ISSUE TITLE
Detect cache when launching store

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#48516]
## Issue Description

Provide an alternative message on the congratulations page when the site is cached.

## Acceptance criteria

* After the site is launched via the LYS hub, perform a check on the shop page to confirm expected content (e.g. make a server-site HTTP request).
* If the coming soon template content is detected, display an alternative message on the congratulations page. Message TBD.

**Comment by moon0326** [comment]
Added a new API in https://github.com/woocommerce/woocommerce/compare/update/48516-detect-cache-when-launching-store?expand=1#diff-f73e4780f54b17eaf799454a972d6f659f8d624638930cdaed31fbfc9b521621R242

I'll continue working on it once we get the final copy.

**Comment by adrianduffell** [comment]
Hey @moon0326, here's the final copy:

Title: Congratulations! Your store will launch soon
Body: It’ll be ready to view as soon as your [server caches](https://woocommerce.com/document/server-caches/) have updated. Please wait, or contact your web host to find out how to do this manually.

Please make sure to remove the underline for the link.

**Comment by adrianduffell** [comment]
What do you think about using a custom meta tag like `<meta name="woo-coming-soon-page" content="yes" />` to flag the template? I think technically input tags aren't allow to be placed inside the head.

**Comment by moon0326** [comment]
> What do you think about using a custom meta tag like <meta name="woo-coming-soon-page" content="yes" /> to flag the template? I think technically input tags aren't allow to be placed inside the head.

Good catch 👍
