### ISSUE TITLE
Product Collection filtering broke after 9.0 on a Front Page Shop Page

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#48585]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Product Collection filtering stopped working after updating to 9.0 on a Front Page Shop Page

I assume it relates to this merge:
https://github.com/woocommerce/woocommerce/pull/45820

I have a Product Collection on a page that is set as a Front Page and also as a Shop Page.

The Product Collection inherits the page query.

The page has filtering which worked fine before WooCommerce 9.0, and now doesn't work.

You can see it here:
https://hobbies4.life/

### Expected behavior

Product Collection filtering should work

### Actual behavior

Product Collection filtering isn't working.

### Steps to reproduce

1. Add a Product Collection block to a page set both as Front Page and Shop Page.
2. Add a Filter by Attribute block.
3. Try to filter.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hobbies4.life
Site address (URL): https://hobbies4.life
WC Version: 9.0.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.20
PHP Post Max Size: 64 MB
PHP Time Limit: 1800
PHP Max Input Vars: 1800
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.0.0
WC Database Prefix: whHhGW_
Total Database Size: 78.82MB
Database Data Size: 57.53MB
Database Index Size: 21.29MB
whHhGW_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
whHhGW_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
whHhGW_aryo_activity_log: Data: 0.22MB + Index: 0.59MB + Engine InnoDB
whHhGW_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_blc_instances: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
whHhGW_blc_links: Data: 8.52MB + Index: 3.56MB + Engine InnoDB
whHhGW_blc_synch: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
whHhGW_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
whHhGW_hcaptcha_events: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
whHhGW_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
whHhGW_options: Data: 2.47MB + Index: 0.22MB + Engine InnoDB
whHhGW_postmeta: Data: 5.52MB + Index: 4.03MB + Engine InnoDB
whHhGW_posts: Data: 16.52MB + Index: 0.44MB + Engine InnoDB
whHhGW_relevanssi: Data: 4.52MB + Index: 8.55MB + Engine InnoDB
whHhGW_relevanssi_log: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
whHhGW_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_termmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
whHhGW_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
whHhGW_term_relationships: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
whHhGW_term_taxonomy: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
whHhGW_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
whHhGW_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_vrts_alerts: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
whHhGW_vrts_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
whHhGW_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_product_attributes_lookup: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
whHhGW_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
whHhGW_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfblockediplog: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wfconfig: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wffilemods: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfhits: Data: 1.52MB + Index: 0.23MB + Engine InnoDB
whHhGW_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wfknownfilelist: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
whHhGW_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wflogins: Data: 0.41MB + Index: 0.14MB + Engine InnoDB
whHhGW_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
whHhGW_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfnotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
whHhGW_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_yoast_indexable: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
whHhGW_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_yoast_seo_links: Data: 0.14MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

acf-field: 90
acf-field-group: 4
attachment: 349
feedback: 108
oembed_cache: 97
page: 14
post: 29
product: 100
revision: 752
wp_block: 3
wp_font_face: 1
wp_font_family: 1
wp_global_styles: 7
wp_navigation: 2
wp_template: 12
wp_template_part: 3
wpcode: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

ManageWP - Worker: by GoDaddy – 4.9.20
Query Monitor: by John Blackbourn – 3.16.3
Advanced Custom Fields PRO: by WP Engine – 6.3.1.2
Activity Log: by Activity Log Team – 2.10.1
Broken Link Checker: by WPMU DEV – 2.2.4
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 7.1.0
Image Placeholders: by WordPress Performance Team – 1.1.1
Site Kit by Google: by Google – 1.129.0
hCaptcha for WordPress: by hCaptcha – 4.2.1
Instant Images: by Darren Cooney – 6.1.2
Jetpack: by Automattic – 13.5
LiteSpeed Cache: by LiteSpeed Technologies – 6.2.0.1
Loco Translate: by Tim Whitlock – 2.6.10
Mailgun: by Mailgun – 1.9.9
Performance Lab: by WordPress Performance Team – 3.2.0
PWA: by PWA Plugin Contributors – 0.8.1
Relevanssi: by Mikko Saari – 4.22.2
Tidio Chat: by Tidio LLC – 6.0.19
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.3

VRTs – Visual Regression Tests: by Bleech – 1.9.1
WooCommerce: by Automattic – 9.0.0
Wordfence Security: by Wordfence – 7.11.6
Yoast SEO: by Team Yoast – 22.9
WP Consent API: by RogierLankhorst – 1.0.7
WP Crontrol: by John Blackbourn – 1.16.3
YITH WooCommerce Wishlist: by YITH – 3.35.0

### Inactive Plugins (2) ###

ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.1

Rollbar: by Rollbar – 2.7.1

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php
object-cache.php: Performance Lab Server Timing Object Cache Drop-In

### Must Use Plugins (2) ###

H4L MU Plugin: by  –
ManageWP - Worker Loader: by GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 83 KB

### WC Pages ###

Shop base: #653 - /
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: #656 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Loudness Child Theme
Version: 0.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Loudness
Parent Theme Version: 1.0.5
Parent Theme Author URL: https://automattic.com
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/asafdevc/hobbies4.life/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/asafdevc/hobbies4.life/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/asafdevc/hobbies4.life/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-06-19 14:56:39 +01:00
Options: ✔
Notes: 95
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: -0001-11-29 23:58:45 -0001
Newest: -0001-11-29 23:58:45 -0001

Complete: 134
Oldest: 2024-05-18 23:20:03 +0100
Newest: 2024-06-18 20:22:06 +0100

Failed: 23
Oldest: 2023-04-12 15:59:56 +0100
Newest: 2024-06-18 16:50:03 +0100

Pending: 2
Oldest: 2024-06-19 00:20:03 +0100
Newest: 2024-06-19 16:50:03 +0100

### Status report information ###

Generated at: 2024-06-18 20:26:49 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Thanks for reporting the issue @asafm7! Investigating.

**Comment by juliaamosova** [comment]
I can confirm that the "Filter by Attributes" block is indeed not working after the 9.0 update. 

**WooCommerce 8.9 experience:**

https://github.com/woocommerce/woocommerce/assets/19143190/a2a95438-18d4-4ff7-86df-a08718572cff

**WooCommerce 9.0 experience:**

https://github.com/woocommerce/woocommerce/assets/19143190/e8f1535f-bed2-4fff-b380-0202e55eefbf

Still testing to see if the issue isolated to "Filter by Attriutes" block itself or if it happens in combination with "Product Collection" block only.

**Comment by juliaamosova** [comment]
It seems that the issue is present only in combination with the "Product Collection" block. I've tried with the "Products (Beta)" block and the "Filter by Attributes" block is working in 9.0:


https://github.com/woocommerce/woocommerce/assets/19143190/fa58b4b7-81e9-45ef-81ab-de74b54a796f

@asafm7 someone will be in touch here as far as when we will fix this. Thanks again for reporting!

**Comment by asafm7** [comment]
I'm glad you were able to reproduce it, @juliaamosova.

Looking forward to a fix.

Thanks!

**Comment by kmanijak** [comment]
Hi @asafm7, thanks for raising this issue and I'm sorry about the inconvenience.

> I assume it relates to this merge: [45820](https://github.com/woocommerce/woocommerce/pull/45820)

Yes, this is related and the change was intentional. Collections that _don’t sync the query with template_ (previously called: inherit query from template) are not filterable. That includes collections like On Sale or Featured but also Product Catalog that doesn’t sync the query.

> The Product Collection inherits the page query.
> You can see it here: https://hobbies4.life/

I checked on the page you provided and seems like Product Collection in your setup doesn’t sync the query and hence doesn’t react to filters.

![image](https://github.com/woocommerce/woocommerce/assets/20098064/092b6d64-1ef2-4bb0-a996-459524ab7aee)

Next steps:
1. We’re working on new filter blocks which allow filtering without page refresh. Users will be able to place them directly in the Product Collection block, and the filter will be applied to that Product Collection no matter if it’s syncing query with a template or not and if it’s a collection like On Sale or not.
2. In the meantime we’re discussing your use case when Product Collection is used on pages with current filters like Filter by Attribute. We’ll get back to you soon 🙌

**Comment by asafm7** [comment]
Thanks, @kmanijak.

I assumed it inherits the query because it is a Shop Page and I didn't manually set the query (also, I didn't find an "Inherit Query" option, so I assumed it is the default option. I do remember seeing such a setting in the past). Anyway, sorry for getting it wrong.

I look forward to hearing from you about a solution for the meantime.

It used to work, so hopefully it won't be too complicated to restore the functionality.

Thanks again.

**Comment by kmanijak** [comment]
Hey @asafm7, I'm getting back with some updates!

We keep the change we introduced as it's an improvement in other aspects of the Product Collection block (prevent filtering of collections like On Sale or New Arrivals). However, your use case is valid and requires a solution!

We decided to go forward with a new control to make the Product Collection filterable on-demand in a non-archive context (e.g. in posts/pages) like in your case. You can check the details in the issue: https://github.com/woocommerce/woocommerce/issues/48749.

This is the enhancement we plan to tackle in the upcoming weeks so please follow the other issue for updates. 🙌 
Thanks again for bringing that use case to us, we really appreciate that input!

**Comment by asafm7** [comment]
Thanks, @kmanijak, for the detailed response.

I'm looking forward to the update.

BTW, I tried to understand why, although placed in a page set as a Shop Page (and a Front Page), the Product Collection isn't synced with the query.

I assumed it is because the Product Collection is placed on the page and not in the template (which uses the Content block to display the content of the page, including the Product Collection).

I tried to place the Product Collection directly in the Front Page template, as I don't see a way to create a Shop Page template.

When doing so, I did see on the editor the "Sync with current query" toggle, which looked promising. But with this setup, the Product Collection block doesn't show up in the front end at all (I tried a couple of times, also with all other plugins deactivated and with a Twenty-Twenty-Four theme).

Unless I'm missing something, there seems not to be a straightforward way of setting the Front Page as a Shop Page.

While having the ability to place the Product Collection block anywhere and still be able to use filters - as you described for the upcoming update - might render this setup redundant and the definition of a Shop Page less essential, I thought it might be useful to mention anyway.

Let me know if I missed anything or got something wrong.

Thanks again for your help, and looking forward to an update.

**Comment by kmanijak** [comment]
You're touching on an important topic, @asafm7. And I must agree that "pages vs templates" is a confusing area requiring more of our attention.

> BTW, I tried to understand why, although placed in a page set as a Shop Page (and a Front Page), the Product Collection isn't synced with the query.
> I assumed it is because the Product Collection is placed on the page and not in the template (which uses the Content block to display the content of the page, including the Product Collection).
> I tried to place the Product Collection directly in the Front Page template, as I don't see a way to create a Shop Page template.

Your assumption is correct. Technically speaking we can sync the query only in templates. On pages there's no global query to sync with even though the page is used as a shop page. That is a limitation based on how WordPress operates. But like I said, I agree we should give this more attention and explore possibilities to overcome it.

> When doing so, I did see on the editor the "Sync with current query" toggle, which looked promising. But with this setup, the Product Collection block doesn't show up in the front end at all (I tried a couple of times, also with all other plugins deactivated and with a Twenty-Twenty-Four theme).

Thanks for bringing this up. Until you brought that up, I wasn't aware of it and that means the current logic determining if we should display "Sync with current query" doesn't cover all cases. And that's a bug, control should not be displayed in the case you mentioned! I'll raise a bug for it.

> Unless I'm missing something, there seems not to be a straightforward way of setting the Front Page as a Shop Page.
> While having the ability to place the Product Collection block anywhere and still be able to use filters - as you described for the upcoming update - might render this setup redundant and the definition of a Shop Page less essential, I thought it might be useful to mention anyway.

Yes, I hope the upcoming enhancement to enable filtering on-demand will solve that problem! 🙌

_BTW, thanks for the patience, all the bugs you raised, and for bringing all that feedback! It's important for us!_

**Comment by asafm7** [comment]
Thanks, @kmanijak for the detailed response. I'm happy to help where I can.

Looking forward to future updates :)

**Comment by kmanijak** [comment]
I created the issue about the "Sync with current query" control showing up in incorrect places: https://github.com/woocommerce/woocommerce/issues/48867.

---

Considering we have a dedicated issue for the main problem you raised (filtering on in non-archive context: https://github.com/woocommerce/woocommerce/issues/48749) I'll go ahead and close this issue. Please follow https://github.com/woocommerce/woocommerce/issues/48749 for further updates (like I said we plan to tackle it in upcoming weeks).
And as always, please note the closed issue can still be commented on! :)

**Comment by kmanijak** [comment]
Hi @asafm7, little update that "Sync with current query" control showing up in incorrect places: https://github.com/woocommerce/woocommerce/issues/48867 has been merged and change will be available in WooCommerce 9.2. It was smaller change so we tackled it sooner to avoid confusion.

Filtering in non-archive context: https://github.com/woocommerce/woocommerce/issues/48749 is on our radar and there's a chance it will land in 9.2 as well but I'll keep you updated 🙌

**Comment by asafm7** [comment]
Thanks, @kmanijak, for the update!

I'm looking forward to the https://github.com/woocommerce/woocommerce/issues/48749 fix :)

**Comment by kmanijak** [comment]
@asafm7, I forgot to mention that https://github.com/woocommerce/woocommerce/issues/48749 is done (here's the PR: https://github.com/woocommerce/woocommerce/pull/49627). It'll be included in WooCommerce 9.2 release :)

Again, thanks for raising this and for collaboration!

**Comment by asafm7** [comment]
This is great, @kmanijak!

Thanks for the update :)
