### ISSUE TITLE
Memory exhausted when using wp-env from plugins/woocommerce

### ISSUE THREAD

**Issue by gedex** [woothemes/woocommerce#48591]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Pretty often I got OOM when I ran `pnpm -- wp-env start` (during `afterStart`). If the start command ran without OOM, I still got it when opening `localhost:8888`

```
Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 36864 bytes) in /var/www/html/wp-includes/formatting.php on line 6177 Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/wp-includes/pomo/mo.php on line 1
```

### Expected behavior

No OOM on default config

### Actual behavior

Got OOM.

To prevent memory getting exhausted, I use [.htaccess](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#advanced-php-settings) with following values:

```
# probably doesn't need to be this big
php_value post_max_size 2G
php_value upload_max_filesize 2G
php_value memory_limit 2G
```

Make sure to destroy the env first, `pnpm -- wp-env destroy`.

### Steps to reproduce

1. Checkout latest `trunk`
2. Go to `plugins/woocommerce`
3. Run `pnpm -- wp-env start`

### WordPress Environment

wp-env on OSX

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @gedex,

Could we get a little more information from you about this?  We're having trouble reproducing this:

- What hardware specs are you using?  How much RAM, what processor?
- Are you using Docker Desktop? Or a different Docker client?  What hardware are you allocating to Docker in the settings (Memory limit, CPU limit)?
- Are you running other containers simultaneously?

**Comment by gedex** [comment]
Hi Lane,

> What hardware specs are you using? How much RAM, what processor?

Apple M1 Max with 32 GB of memory

> Are you using Docker Desktop? Or a different Docker client? What hardware are you allocating to Docker in the settings (Memory limit, CPU limit)?

Yes, I use Docker Desktop 4.28.0. Here's my resource allocation:

<img width="526" alt="image" src="https://github.com/woocommerce/woocommerce/assets/78313/0b13b495-a55e-4ebf-8c00-75b7109e85f7">

> Are you running other containers simultaneously?

Yes, I've other containers running. I'll try with other containers stopped and report later.

**Comment by gedex** [comment]
> I'll try with other containers stopped and report later

It's now working. It could be other containers took almost all allocated resources.

I'll close this. Thanks for taking a look, @lanej0
