### ISSUE TITLE
Woocommerce Disbale Guest Checkout Doesn't Work

### ISSUE THREAD

**Issue by qijiew** [woothemes/woocommerce#48592]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Disbale Guest Checkout doesn't work

### Expected behavior

Disbale Guest Checkout shoule be able work after uncheck the enable choice.

### Actual behavior

Guest still can checkout

### Steps to reproduce

1. woocommerce
2. settings
3. uncheck 
Allow customers to place orders without an accountLogin Allow customers to log into an existing account during checkout
--
Account creation Allow customers to create an account during checkout Allow customers to create an account on the "My account" page

### WordPress Environment

wordpress-elementor

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adimoldovan** [comment]
Thanks for reporting this @qijiew. Can you please also add a System Status Report?

We use the [WooCommerce System Status Report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue.
Without this report we won't be able to fully evaluate this issue.
