### ISSUE TITLE
CYS > Import Dotcom patterns to Woo Pattern source site and replace text and images from the Dotcom patterns

### ISSUE THREAD

**Issue by albarin** [woothemes/woocommerce#48603]
We have to import Dotcom patterns to the Woo Pattern source site, and after that, we need to update **text and images** of the Dotcom patterns from the PTK API following these [designs](https://www.figma.com/design/FlPl7fHaGv9mpu8Nfl0joH/CYS-with-Assembler---Core?node-id=2814-125908&t=FFVrzEhzmKjfDFWi-4).

The Dotcom pattern should be imported in dedicated categories structured in this way: `dotcom_imported_{category}.` This allows consumers to filter imported dotcom patterns.

Also, we need to update the `fetch_patterns` https://github.com/woocommerce/woocommerce/blob/9a157eb94d926837385de7693d3b20fb35d1f6aa/plugins/woocommerce/src/Blocks/Patterns/PTKPatternsStore.php/#L181-L226 to fetch patterns only from the Woo Pattern source and update the logic to map the categories.

**Comment by gigitux** [comment]
I have updated the issue title and description to align with the current roadmap.
