### ISSUE TITLE
[Enhancement]: Create password field component for block checkout

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#48628]
### Describe the solution you'd like

Checkout lacks the ability to set a custom password during account creation (https://github.com/woocommerce/woocommerce/issues/42430). To solve this we need to implement a password component.

- [x] Implement password field type component
- [x] Implement password strength meter. This should be enabled based on a component attribute
- [ ] Support ability to pass in extra validation rules

Once the component is implemented, it should be shown when the create account checkbox is used to satisfy #42430 In addition, the checkout API route needs to be updated to handle a user set password.

### Additional context

WordPress uses the `zxcvbn` library but its heavy. @senadir suggested looking into a lightweight alternative such as https://bundlephobia.com/package/check-password-strength@2.0.10

**Comment by senadir** [comment]
Not all stores needs the same password strength rules, so if we can reuse the same extensible rules that already exists, it would be great.

**Comment by mikejolley** [comment]
@senadir There don't seem to be any rules exposed by zxcvbn or WordPress, which lets zxcvbn do its thing. I'm happy to just use the rules https://www.npmjs.com/package/check-password-strength implements by default. They cover length and diversity. We'll only be guiding customers here, I wasn't going to lock things down if the customer entered something insecure unless you think we must?
