### ISSUE TITLE
Add "happy path" e2e test for core profiler

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#48632]
## Issue Description

Add a basic e2e test for the new core profiler going through the "happy path". Note, existing tests may exist for the previous profiler.

## Acceptance Criteria

* Provide answers to all questions and continue to the next screen until reaching the home screen.
* De-select all plugins / extensions (and therefore it shouldn't try to connect Jetpack)
* Proceeding tests may rely on default values. If so, create a function to reset values back to defaults when the test completes.

**Comment by psealock** [comment]
This issue has been addressed by https://github.com/woocommerce/woocommerce/pull/44022
