### ISSUE TITLE
Related Products Controls block invites user to "Upgrade to Product Collection" which is not possible

### ISSUE THREAD

**Issue by Brianmitchtay** [woothemes/woocommerce#48647]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When editing the single product template in the site editor, and reviewing the "Related Products" block, I'm prompted to "upgrade to Product Collection" when I select the locked "related product controls" block.

I'm making some assumptions here, but I'm guessing that the Related Products Controls block that gets used in the single product template, must be an extension of the Products(beta) block and so it's showing the same upgrade option to try and get users on the product collection block.

> Upgrade all Products (Beta) blocks on this page to Product Collection for more features!
![Screenshot 2024-06-19 at 1 50 32 PM](https://github.com/woocommerce/woocommerce/assets/45057772/4bff3e5c-16d6-435b-8abd-15e6679af82a)

However, this block is locked, so clicking the prompt to upgrade does nothing. Also AFAIK there is not yet a product collection option that fills this "related Products" need.  

I don't believe we should be offering users to upgrade to the product collection when:
1. It's not possible, clicking the button doesn't work and just feels broken.
2. The product collection block can't (yet) be configured to show product recommendations based on the current product being viewed.	

### Expected behavior

No upgrade notice should show on the "Related Product Controls" block

### Actual behavior

In the sidebar settings of the Related Product Controls block, a message shows inviting users to upgrade to the product collection. Clicking the link to upgrade does nothing.

### Steps to reproduce

On a fresh install of WC 9.0:
- Ensure you're running a block theme.
- Head to the editor.
- Open the Single Product template.
- Expand the list view and select the Related Product Controls block
- See notice in block settings sidebar

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.0.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.6.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 140
aw_workflow: 1
customize_changeset: 3
page: 11
post: 3
product: 194
product_variation: 451
revision: 35
shop_order_placehold: 60
wp_global_styles: 2
wp_navigation: 1
wp_template: 9
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Commit Message Plugin: by Brian Taylor – 0.2
PublishPress Revisions: by PublishPress – 3.5.9
WooCommerce: by Automattic – 9.0.0

### Inactive Plugins (2) ###

WooCommerce Smooth Generator: by Automattic – 1.1.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 76 KB

### WC Pages ###

Shop base: #987 - /shop/
Cart: #32 - /cart/
Checkout: #33 - /checkout/
My account: #34 - /my-account/
Terms and conditions: #35 - /refund_returns/

### Theme ###

Name: Assembler
Version: 0.0.16
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/briantaylor/Local Sites/woo-documentation/app/public/wp-content/plugins/woocommerce/templates/block-notices/error.php
/Users/briantaylor/Local Sites/woo-documentation/app/public/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/Users/briantaylor/Local Sites/woo-documentation/app/public/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-06-20 18:59:37 +00:00
Options: ✔
Notes: 78
Onboarding: skipped

### Action Scheduler ###

Complete: 160
Oldest: 2024-05-21 18:50:51 +0000
Newest: 2024-06-19 21:20:08 +0000

Failed: 6
Oldest: 2024-04-04 19:13:03 +0000
Newest: 2024-06-03 20:46:17 +0000

Pending: 1
Oldest: 2024-06-19 23:55:25 +0000
Newest: 2024-06-19 23:55:25 +0000


### Status report information ###

Generated at: 2024-06-19 21:52:32 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Brianmitchtay** [comment]
Looking closer at this I think the "Advanced Filters" section probably shouldn't be showing either.
![Screenshot 2024-06-19 at 1 57 01 PM](https://github.com/woocommerce/woocommerce/assets/45057772/db4fc375-dd6f-4a46-b0ef-d2c377da6a18)

**Comment by roykho** [comment]
Hi @Brianmitchtay - Thanks for reporting. I believe [this PR](https://github.com/woocommerce/woocommerce/pull/47845) should have addressed that issue?

**Comment by Brianmitchtay** [comment]
Ah thanks @roykho - I hadn't seen that PR for the upcoming 9.1. release. I'll go ahead and close this since #47845 will resolve it in the 9.1. release.
