### ISSUE TITLE
Product Filters Redesign > Filters Overlay add edit link to product filters synced pattern

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#48641]
## Description

We need to add a link to the Filters Overlay block that points to the Product Filters Synced Pattern. Ideally just under the block description. But if this is not possible, we can add it to the inspector controls settings tab.

## Reference Image

![Google Chrome -  Block  Product Filters – Figma 2024-06-19 at 1 57 06 PM](https://github.com/woocommerce/woocommerce/assets/2132595/ab60414f-de68-48f9-a1ea-afb946bc5c88)

**Comment by dinhtungdu** [comment]
> Filters Overlay add edit link to product filters synced pattern

It should be `product filters template part`, right?

**Comment by roykho** [comment]
Closing this. Please see [PR comment](https://github.com/woocommerce/woocommerce/pull/50107)
