### ISSUE TITLE
Add beta tester tool to show coming soon landing page

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#48655]
## Issue Description

To make it easier to test the coming soon landing pages and flow, add a tool to WooCommerce Beta Tester to force the coming soon landing pages to show no matter what the site visibility settings are.

## Acceptance Criteria

* Tester can force the coming soon landing pages to display on the front-end, independently of the site visibility settings.
* Tester can select whether to show the "whole site" or "store only" template.

**Comment by chihsuan** [comment]
> To make it easier to test the coming soon landing pages and flow, add a tool to WooCommerce Beta Tester to force the coming soon landing pages to show no matter what the site visibility settings are.


Hey @adrianduffell I wonder what issue did you encounter that led to this improvement?  I'm not sure if I understand the issue correctly. 😅  

From what I imagine, the tool in beta tester would be very similar to the site visibility settings. If we want to test the coming soon landing pages and flow, we can set the site visibility to "Coming Soon" and then test it. What's the benefit of having a tool in beta tester to force the coming soon landing pages to show no matter what the site visibility settings are? 🤔

**Comment by adrianduffell** [comment]
> What's the benefit of having a tool in beta tester to force the coming soon landing pages to show no matter what the site visibility settings are?

Hey @chihsuan , it's a good question. The use-case I have in mind is to simulate the coming soon landing page being aggressively cached no matter what the site visibility settings are. This would help us easily test the alternative congrats page from PR https://github.com/woocommerce/woocommerce/pull/48586. At present, we only know how to test it using certain hosting providers.

**Comment by chihsuan** [comment]
> it's a good question. The use-case I have in mind is to simulate the coming soon landing page being aggressively cached no matter what the site visibility settings are. This would help us easily test the alternative congrats page from PR https://github.com/woocommerce/woocommerce/pull/48586. At present, we only know how to test it using certain hosting providers.

Gotcha! 🙂
