### ISSUE TITLE
9.0.0 breaks web hook signatures -- they are blank!

### ISSUE THREAD

**Issue by jjxtra** [woothemes/woocommerce#48675]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In 9.0.0 release from June 18th, the webhook signature is empty. Rolling back to 8.9.3 from June 10 fixes this.

### Expected behavior

Webhook signature should be sent

### Actual behavior

Webhook signature is not sent

### Steps to reproduce

Download woocommerce 9.0.0 and place an order (make sure webhook is enabled)

### WordPress Environment

Ubuntu 22.04

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @jjxtra,

When I test with any of 8.9.3, 9.0.0 or 9.0.1, and where I've defined a secret, I find the `x-wc-webhook-signature` header is set and populated.

Could something else be at play here, besides the 9.0.0 update? I realize you checked the relevant boxes in the *isolating the problem* section of the bug report, but is it possible something was missed along the way?

**Comment by barryhughes** [comment]
I'll just quickly note, I did test with a range of different webhooks. `order.created` as you noted, also `product.updated` and a few others. I couldn't find a case where the delivery was unsigned, using 9.0.0.

**Comment by jjxtra** [comment]
I'm using woo subscriptions 6.2.0, perhaps there's a bad interaction there -- its `subscription.updated`

![image](https://github.com/woocommerce/woocommerce/assets/1271832/19b0d1ef-1830-46e4-83db-558cdc62f24f)

**Comment by barryhughes** [comment]
OK, can you verify if that is the case (are you in a position to test without subscriptions)?

**Comment by jjxtra** [comment]
It's a "subscription.updated" so testing without subscriptions plugin seems, well, pointless. Unless I'm missing something.

**Comment by barryhughes** [comment]
Gotcha. I wasn't completely sure if that is the only webhook where you are seeing this, or the only one you are aware of *so far.* 

If you are confident the problem only occurs with Subscriptions, or only happens with one or more Subscriptions-related webhooks, then it probably makes to [get support from the subscriptions team](https://woocommerce.com/contact-us/) (development is not public in the same way as for WooCommerce core, so that's the best way to be kept informed of progress, etc).

As it doesn't currently appear to be a problem in the core WooCommerce plugin, I'll go ahead and close this issue.

**Comment by jjxtra** [comment]
Leaving a final note: do not upgrade to woocomerce >= 9.0.0 if you are using woo subscriptions <= 6.2.0 and using webhooks, the signature will be blank, breaking any listeners.
