### ISSUE TITLE
action failed via WP Cron: Call to a member function get_endpoint_data() on null

### ISSUE THREAD

**Issue by kresch23** [woothemes/woocommerce#48741]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

 have problems with my webhook since the update to 9.0.1 it no longer fires.
Error message: woocommerce_deliver_webhook_async -> action failed via WP Cron: Call to a member function get_endpoint_data() on null

My webhook looks like this:

`function add_custom_filters_and_actions() {
add_filter( 'woocommerce_webhook_topic_hooks', 'add_custom_wcs_topics', 30, 2 );
add_filter( 'woocommerce_valid_webhook_events', 'add_custom_wcs_events', 20, 1 );
add_filter( 'woocommerce_webhook_topics' , 'add_custom_wcs_topics_admin_menu', 20, 1 );
add_action( 'woocommerce_subscription_status_pending-cancel_to_cancelled', 'add_subscription_cancelled_callback', 10, 1 );
add_action( 'woocommerce_subscription_status_pending_to_active', 'add_subscription_active_callback', 10, 1 );
}

/* add Custom Subscription webhook topics*/
function add_custom_wcs_topics( $topic_hooks, $webhook ) {
switch ( $webhook->get_resource() ) {
case 'subscription':
$topic_hooks = apply_filters( 'woocommerce_subscriptions_webhook_topics', array(
'subscription.cancelled' => array(
'wcs_webhook_status_cancelled'
),
'subscription.activated' => array(
'wcs_webhook_status_active'
)
), $webhook );
break;
}
return $topic_hooks;
}

/* add Subscription topics to the Webhooks dropdown menu in when creating a new webhook.*/
function add_custom_wcs_topics_admin_menu( $topics ) {
$front_end_topics = array(
'subscription.cancelled' => ( 'Subscription Cancelled', 'woocommerce-subscriptions' ), 'subscription.activated' => ( 'Subscription Activated', 'woocommerce-subscriptions' )
);
return array_merge( $topics, $front_end_topics );
}

/* add webhook event for subscription switched.*/
function add_custom_wcs_events( $events ) {
$events[] = 'cancelled';
$events[] = 'activated';
return $events;
}

function add_subscription_cancelled_callback( $subscription ) {
do_action( 'wcs_webhook_status_cancelled', $subscription->get_id());
}

function add_subscription_active_callback( $subscription ) {
do_action( 'wcs_webhook_status_active', $subscription->get_id());
}

add_custom_filters_and_actions();`

### Expected behavior

Triggering the webhook and sending the information to the desired URL

### Actual behavior

Webhook no longer works since the update. Other webhooks for "normal" orders (not subscription) work.

### Steps to reproduce

Use the code from above and trigger the webhook.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://tiedje-trading.com
Site address (URL): https://tiedje-trading.com
WC Version: 9.0.1
Legacy REST API Package Version: Auf dieser Website ist das alte REST-API-Plugin nicht installiert.
Action Scheduler Version: ✔ 3.8.0
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.20
PHP Post Max Size: 256 MB
PHP Time Limit: 240
PHP Max Input Vars: 200000
cURL Version: 8.2.1
NSS/3.90

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.0.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 91.23MB
Datenbank-Datengröße: 61.34MB
Datenbank-Indexgröße: 29.89MB
wp_woocommerce_sessions: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 1.52MB + Index: 0.67MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
setups_active: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
setups_in: Daten: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 16.02MB + Index: 12.11MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 6.02MB + Index: 5.03MB + Engine InnoDB
wp_btcbi_flow: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_btcbi_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 1.50MB + Index: 0.72MB + Engine InnoDB
wp_hidemysiteSecure: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Daten: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Daten: 0.16MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Daten: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_mailpoet_automation_triggers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Daten: 0.31MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Daten: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Daten: 4.28MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Daten: 0.31MB + Index: 0.25MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Daten: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Daten: 0.08MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsletter: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_emails: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_sent: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_stats: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_user_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_user_meta: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 5.14MB + Index: 0.19MB + Engine InnoDB
wp_postmeta: Daten: 15.08MB + Index: 0.45MB + Engine InnoDB
wp_posts: Daten: 1.36MB + Index: 0.27MB + Engine InnoDB
wp_snippets: Daten: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 1.50MB + Index: 0.67MB + Engine InnoDB
wp_users: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_comments_subscription: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_feedback_forms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_follow_users: Daten: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_wc_orders: Daten: 0.25MB + Index: 0.25MB + Engine InnoDB
wp_wc_orders_meta: Daten: 2.52MB + Index: 4.56MB + Engine InnoDB
wp_wc_order_addresses: Daten: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Daten: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_phrases: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_users_rated: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_users_voted: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforo_accesses: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpforo_activity: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wpforo_boards: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforo_bookmarks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforo_follows: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpforo_forums: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wpforo_languages: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpforo_logs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforo_phrases: Daten: 0.06MB + Index: 0.09MB + Engine MyISAM
wp_wpforo_postmeta: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wpforo_posts: Daten: 0.02MB + Index: 0.28MB + Engine InnoDB
wp_wpforo_post_revisions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforo_profiles: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wpforo_reactions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforo_subscribes: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpforo_tags: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforo_topics: Daten: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_wpforo_usergroups: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpforo_visits: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_wppm_attachments: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_checklist: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_checklist_items: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_project: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_project_categories: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_project_comment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_project_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_project_statuses: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_project_users: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_task: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_task_comment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_task_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_task_priorities: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppm_task_statuses: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 77
condition_group: 1
flamingo_contact: 254
flamingo_inbound: 193
mailpoet_page: 1
nav_menu_item: 18
page: 23
post: 17
product: 6
product_variation: 4
restriction: 1
revision: 101
shop_coupon: 1
shop_order_placehold: 587
template: 2
wpcf7_contact_form: 3
wpdiscuz_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Admin Menu Editor Pro: von Janis Elsts – 2.24.3
Bit Integrations: von Automation & Integration Plugin - Bit Apps – 2.0.9
Classic Editor: von WordPress-Mitwirkende – 1.6.3
Code Snippets: von Code Snippets Pro – 3.6.5.1
Contact Form 7: von Takayuki Miyoshi – 5.9.6
Yoast Duplicate Post: von Enrico Battocchi & Team Yoast – 4.5
Easy FancyBox - WordPress Lightbox Plugin: von FirelightWP – 2.2.1
Flamingo: von Takayuki Miyoshi – 2.5
MailPoet Premium: von MailPoet – 4.52.0
MailPoet: von MailPoet – 4.52.0
Taskbuilder: von Taskbuilder Team – 3.0.1
WP User Avatar - Reloaded: von saadiqbal – 1.2.2
WooCommerce.com Update Manager: von Automattic – 1.0.3
Checkout Field Editor for WooCommerce (Pro): von ThemeHigh – 3.6.3
WooCommerce Conversion Tracking: von weDevs – 2.0.12
WooPayments: von Automattic – 7.8.0
PDF Invoices & Packing Slips for WooCommerce: von WP Overnight – 3.8.4
WooCommerce Subscriptions: von WooCommerce – 6.4.0
WooCommerce: von Automattic – 9.0.1
WP Menu Cart: von WP Overnight – 2.14.3
wpDiscuz - Embeds: von gVectors Team – 1.1.2
wpDiscuz - Emoticons: von gVectors Team – 7.0.15
wpDiscuz - Front-end Moderation: von gVectors Team – 7.1.0
wpDiscuz: von gVectors Team – 7.6.20

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 17 MB

### WC Pages ###

Shop-Basis: #147 - /shop/
Warenkorb: #148 - /warenkorb/
Kasse: ❌ Die Seite enthält nicht den [woocommerce_checkout]-Shortcode oder woocommerce/checkout-Block.
Mein Konto: #150 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Betheme
Version: 27.4.5
Author URL: https://muffingroup.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Archive Template: Dein Theme hat eine woocommerce.php-Datei
was dazu führt
dass du das Template woocommerce/archive-product.php nicht überschreiben kannst
da woocommerce.php höher gewichtet wird als archive-product.php. Das ist beabsichtigt
um Darstellungsprobleme zu verhindern.

Overrides: betheme/woocommerce/archive-product.php
betheme/woocommerce/cart/cart-totals.php
betheme/woocommerce/cart/cart.php
betheme/woocommerce/cart/cross-sells.php
betheme/woocommerce/cart/mini-cart.php
betheme/woocommerce/checkout/form-checkout.php
betheme/woocommerce/content-product.php
betheme/woocommerce/content-single-product.php
betheme/woocommerce/global/form-login.php
betheme/woocommerce/loop/loop-end.php
betheme/woocommerce/loop/loop-start.php
betheme/woocommerce/loop/no-products-found.php
betheme/woocommerce/loop/pagination.php
betheme/woocommerce/myaccount/downloads.php
betheme/woocommerce/notices/error.php
betheme/woocommerce/notices/success.php
betheme/woocommerce/single-product/add-to-cart/external.php
betheme/woocommerce/single-product/meta.php
betheme/woocommerce/single-product/product-image.php
betheme/woocommerce/single-product/product-thumbnails.php
betheme/woocommerce/single-product/related.php
betheme/woocommerce/single-product/sale-flash.php
betheme/woocommerce/single-product/tabs/description.php
betheme/woocommerce/single-product/tabs/tabs.php
betheme/woocommerce/single-product/title.php
betheme/woocommerce/single-product/up-sells.php
betheme/woocommerce/single-product-reviews.php

### WooPayments ###

Version: 7.8.0
Connected to WPCOM: Ja
WPCOM Blog ID: 227260540
Account ID: acct_1Ool3yFsBmYDF2uZ
Payment Gateway: Aktiviert
Test Mode: Deaktiviert
Enabled APMs: card
WooPay: Nicht berechtigt
Apple Pay / Google Pay: Aktiviert (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Aktiviert
Auth and Capture: Aktiviert
Documents: Aktiviert
Logging: Aktiviert

### Abonnements ###

WCS_DEBUG: ✔ Nein
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://tiedje-trading.com
Subscriptions-core Library Version: 7.2.0
Subscription Statuses: trash: 1
wc-active: 126
wc-cancelled: 52
wc-on-hold: 4
wc-pending: 1
wc-pending-cancel: 10

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Ja
Cache Update Failures: ✔ 0 Fehler

### Shop-Einrichtung ###

Country / State: Schweiz — Luzern

### Abonnements nach Zahlungs-Gateway ###

WooPayments: wc-active: 124
wc-cancelled: 52
wc-on-hold: 4
wc-pending: 1
wc-pending-cancel: 10

### Zahlungs-Gateway-Unterstützung ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### MailPoet ###

Sending Method: SMTP
Send all site's emails with: Standard-WordPress-Versandmethode
Task Scheduler method: Action Scheduler
Cron ping URL: https://tiedje-trading.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-06-23 18:46:58 +02:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Canceled: 32
Oldest: 2024-05-25 15:46:00 +0200
Newest: 2024-06-21 18:10:13 +0200

Complete: 23.624
Oldest: 2024-05-23 10:01:27 +0200
Newest: 2024-06-23 09:59:01 +0200

Failed: 39
Oldest: 2024-01-30 16:44:42 +0100
Newest: 2024-06-22 21:56:10 +0200

Pending: 143
Oldest: 2024-06-23 10:00:42 +0200
Newest: 2028-08-31 19:12:26 +0200

### Status report information ###

Generated at: 2024-06-23 09:59:11 +02:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by chartspots** [comment]
I have the same issue for webhooks created using the Wordpress GUI for 'Subscription Updated' and 'Subscription Created'. 

Tried with all plugins / themes disabled : same result.

I also see this error in Cron overview: action failed via WP Cron: Call to a member function get_endpoint_data() on null

**Comment by kresch23** [comment]
Thanks for the support, so I can upgrade the other task, I hope someone can help us soon.
I am active on several channels with the problem: Slack, codeable
As soon as there is something outside I will report here.

**Comment by chartspots** [comment]
I just got a reply to my support ticket, they asked to provide system details. 

_"Thank you for sharing your detailed investigation and identifying the issue with WooCommerce v9.0.1. It's great to hear that downgrading to 8.8.5 helped resolve the problem with the webhooks for "Subscription Active" and "Subscription Updated". I will escalate this information to our development team to investigate further and address this as a potential bug in version 9.0.1."_

So as you can see, in my case I "solved" it by downgrading to my previous version 8.8.5. 

I will link this issue when I reply to the support ticket.

**Comment by kresch23** [comment]
@chartspots Thank you for the information, but we have already updated the database, which was necessary after the update to 9.0.0. Have you also restored your old database? This would be a challenge for us as we have carried out many transactions in the meantime.

**Comment by barryhughes** [comment]
Looks like it may be essentially the same problem as was described here:

https://github.com/woocommerce/woocommerce/issues/48675

**Comment by tammullen** [comment]
As per the other issue linked above, it doesn't currently appear to be a problem in the core WooCommerce plugin, I'll go ahead and close this issue.

**Comment by kresch23** [comment]
@tammullen What else could it be? It's strange that several users have had this problem since the update to 9.0.0, how am I supposed to solve this, I don't feel taken seriously here. Previously this worked for years.

**Comment by kresch23** [comment]
@tammullen On the staging side, we have now rolled back to version 8.9.3 and the webhooks work without any problems. But we don't know how this is compatible with the database update which was done during the upgrade to 9.0.0, can you tell us more about this? How can it be that this issue is closed and ignored although this can be proven with the version?

**Comment by barryhughes** [comment]
@kresch23: you are correct, this **does** stem from a change made in WooCommerce 9.0. However, a fix is being made by our friends and colleagues on the WooCommerce Subscriptions team and that should hopefully be available soon. 

The core problem is that `wc()->api` will now always be `null`, unless the [WooCommerce Legacy REST API](https://wordpress.org/plugins/woocommerce-legacy-rest-api/) plugin is installed and activated (which is another way to solve this). 

In general, though, we encourage extension developers to avoid referencing `wc()->api`. As of 9.0, they should use the equivalent functionality provided by methods within the `Automattic\WooCommerce\Utilities\RestApiUtil` utility class.

**Comment by kresch23** [comment]
@barryhughes Thanks for the feedback, if this is looked at and fixed by Woocommerce Subscription it's good. I hope for a fix soon.

**Comment by james-allan** [comment]
@kresch23 We've just deployed WooCommerce Subscriptions 6.4.1 which includes a fix for this. It should appear in your updates soon. Thanks for your patience and sorry for the inconvenience.
