### ISSUE TITLE
Product and Variant reponse empty "on_sale"

### ISSUE THREAD

**Issue by oldtune** [woothemes/woocommerce#48744]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have a store that use Woocommerce 9.0.0 and the `on_sale` field in Variant is empty upon response.
```
[
   {
      "id":2976,
      "type":"variation",
      "date_created":"2024-06-21T04:20:18",
      "date_created_gmt":"2024-06-21T04:20:18",
      "date_modified":"2024-06-21T04:20:18",
      "date_modified_gmt":"2024-06-21T04:20:18",
      "description":"",
      "permalink":"https:\/\/stitchinstuff.co.nz\/?post_type=product&p=2855&attribute_sa-size=10+-+22",
      "sku":"13619",
      "price":"10",
      "regular_price":"10",
      "sale_price":"",
      "date_on_sale_from":null,
      "date_on_sale_from_gmt":null,
      "date_on_sale_to":null,
      "date_on_sale_to_gmt":null,
      "on_sale":"",
      "status":"publish",
      "purchasable":true,
      "virtual":false,
      "downloadable":false,
      "downloads":[
         
      ],
      "download_limit":-1,
      "download_expiry":-1,
      "tax_status":"taxable",
      "tax_class":"",
      "manage_stock":true,
      "stock_quantity":3,
      "stock_status":"instock",
      "backorders":"no",
      "backorders_allowed":false,
      "backordered":false,
      "low_stock_amount":null,
      "weight":"0.0000",
      "dimensions":{
         "length":"",
         "width":"",
         "height":""
      },
      "shipping_class":"",
      "shipping_class_id":0,
      "image":null,
      "attributes":[
         {
            "id":0,
            "name":"SA SIZE",
            "slug":"sa-size",
            "option":"10 - 22"
         }
      ],
      "menu_order":0,
      "meta_data":[
         
      ],
      "name":"10 - 22",
      "parent_id":2855,
      "_links":{
         "self":[
            {
               "href":"https:\/\/stitchinstuff.co.nz\/wp-json\/wc\/v3\/products\/2855\/variations\/2976"
            }
         ],
         "collection":[
            {
               "href":"https:\/\/stitchinstuff.co.nz\/wp-json\/wc\/v3\/products\/2855\/variations"
            }
         ],
         "up":[
            {
               "href":"https:\/\/stitchinstuff.co.nz\/wp-json\/wc\/v3\/products\/2855"
            }
         ]
      }
   }
]
```
However, according to the official documentation. There on_sale field is boolean and not mentioned anywhere as "nullable" which breaks my json data contract upon deserialization.
https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties
Is there a workaround for this? My current workaround is to change from `bool` to `string`
Actually my underlying data type for `on_sale` is `bool?` (nullable boolean) however the underlying conventions of the language i'm using (C#) rejects deserializing to `nullable boolean` from the empty string in this case

### Expected behavior

`on_sale` always have `true` or `false` value and not empty or null

### Actual behavior

`on_sale` returns empty

### Steps to reproduce

1. Fetch the variant from this endpoint /wp-json/wc/v3/products/2855/variations?sku=13619
2. The response returns empty `on_sale`

### WordPress Environment

I use WooCommerce 9.0.0

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by naman03malhotra** [comment]
Hey @oldtune, thanks for opening this issue. As per the code below, seems like `woocommerce_product_is_on_sale` must be interfering with your results, could please verify if that's the case?

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1633

**Comment by oldtune** [comment]
Hi @naman03malhotra That's correct. It's supposed to be "true" or "false" but returned empty string which breaks my deserialization

**Comment by naman03malhotra** [comment]
Then there must be some custom code or plugin that must be inserting that hook.

**Comment by oldtune** [comment]
@naman03malhotra sorry but i can't really confirm that because i don't have the access to the site but only the API. I changed the data type from bool to string as a workaround since i didn't use that field
