### ISSUE TITLE
Product Collection: add control to toggle whether block is filterable in non-archive context

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#48749]
### Issue Description

**Context:**
In https://github.com/woocommerce/woocommerce/pull/45820 we only made Product Collection blocks that sync the query with template filterable. It was a conscious decision since collections such as On Sale or New Arrivals are not meant to react to filtering.

However, there's also a "Product Catalog" collection which in:
- archive context (e.g. Product Catalog or Products by Category templates) is filterable when syncing query. This, we assumed, represents the main use case of Product Collection block as a "main" product catalog.
- non-archive context (e.g. post or page) is not filterable at all as there's no way to sync query (there's no template to sync the query with).

**Problem:**
The second case creates the problem. We assumed this case is used to create some custom, hand-made collections (e.g. Handpicked Products) but nothing prevents merchants to use a Page as their main Shop Page (instead of Product Catalog). In that case, Product Collection used on that page becomes the "main" product catalog and there should be a way to make it filterable.

That case was raised by @asafm7 in https://github.com/woocommerce/woocommerce/issues/48585. Kudos @asafm7 for bringing this topic to us!

### Goal

Add control to Product Collection inspector controls:

![image](https://github.com/user-attachments/assets/c75b997b-7dbd-4599-a204-c7c13fd71724)

**Requirements:**
This includes renaming "Sync with current query" to the above (the control will be unified)

- Availability:
    - The control is available ONLY in a non-archive context. In other words: whenever "Sync query with template" is not available.
    - The control is available ONLY for Product Catalog collection (aka "Default"/"Custom"). So it's NOT available for all the collections like "On Sale", "Top Rated" etc.
    - The control is there no matter if Filter blocks are included somewhere or not

- Default state:
    - First Product Catalog on a page has the option ENABLED by default
    - 2nd+ has the option DISABLED by default

- Filtering:
    - If enabled, block reacts to filters ([code responsible for that](https://github.com/woocommerce/woocommerce/blob/3b00882aed0056df5c18d3eefbf0d85f98d55d2b/plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php#L457))
    - If disabled, block doesn't react to filters (as-is now)

References:
- p1718741382773849-slack-C01DT6U03HC
- p1718780723617949-slack-C05UMTA7W0P

**Comment by dinhtungdu** [comment]
Why does a control is needed? Isn't allowing filter blocks to be added to PC a self explanation that the PC is filterable?

**Comment by kmanijak** [comment]
> Isn't allowing filter blocks to be added to PC a self explanation that the PC is filterable?

@dinhtungdu, this feature is not yet implemented in new filters (and even if it was, they're not public yet) and won't be in old filters. So at this moment, PC in a non-archive context is non-filterable at all, hence this solution.
