### ISSUE TITLE
Return to Cart: Disable toggle by default in Checkout blocks

### ISSUE THREAD

**Issue by nikivias** [woothemes/woocommerce#48757]
### Background

This relates to #44837, where we introduced the Cart link in the header for the block-based checkout header. The blocks checkout is designed especially to minimize navigational elements during the checkout process.

### Proposal 

Disable the "Return to Cart" toggle by default in the block-based checkout to avoid having multiple link outs to the cart. This prioritizes the cart link in the header which is a more optimized position for this action.

### Secondary enhancement request

- [ ] Change `Account options` to `Navigation options`
- [ ] Add a subtext to explain when to turn it on or off

> Recommended to enable only if there is no Cart link in the header.

[See design in Figma](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic-File%5D-Cart-%26-Checkout-Blocks?node-id=800-3977&t=XkgkrMvcI2FoB2mb-1)

![CleanShot 2024-06-24 at 21 00 19@2x](https://github.com/woocommerce/woocommerce/assets/99638528/7d2b35b9-e5d3-4851-b13d-5b288fffe3c2)

cc: @pmcpinto

**Comment by SpaceSurfer1** [comment]
@nikkivias , PR #48762 created for the requested enhancements. Thanks.
