### ISSUE TITLE
Split PR/Daily/Release e2e run Buildkite reporting?

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#48755]
Currently, all flaky/failing test reporting for e2e tests are going into the same "bucket" in Buildkite (the same Test Suite in Buildkite terms).

We could split the reporting so that each of the different types goes into their own Test Suite bucket -- might help us to improve the reliability of daily runs vs. release runs vs. PR (the test suite in general).  It's easy enough to just set up a different suite and swap in the token based on the triggering event.

Thoughts on this approach @adimoldovan @veljkho ?

**Comment by veljkho** [comment]
In one hand it makes sense, in the other hand, multiple views to check for flaky tests even if sometimes are the same flaky tests. I'm thinking if we soon start seeing %95+ passing tests, it will be easy to monitor further any failures and just keep at a very high level. That way, we won't need separate runs to monitor as it will always be a high score and will require tiny maintenance.

I'm going to fix those this week.

**Comment by adimoldovan** [comment]
We mostly care about flakiness rates against trunk, and we get that in the current report by filtering by branch. The daily checks are also trunk, so we're covered there. The release checks could be interesting to see, but they are rare enough that we can just see the reports in the dashboards for it, I don't think setting up a BK report would add much value.

**Comment by lanej0** [comment]
Sounds like keeping it together is the best bet for now!
