### ISSUE TITLE
Template version bump suggests the wrong version

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#48770]
For a [recent PR](https://github.com/woocommerce/woocommerce/pull/48743) (created 2024-06-23), I noticed that the template version bump check ran as expected and flagged that some templates were in need of a bump. However, the suggested version was incorrect:

<div align="center"><img src="https://github.com/woocommerce/woocommerce/assets/3594411/48dcdaff-da1d-4f2c-b72b-e9eced0435bd" alt="Template version check, signalling here that the version should be set to 9.1.0" width="600"></div>

In this example, it notes that 9.1.0 is expected but code freeze for 9.1.0 was 2024-06-19, so it should be suggesting 9.2.0 instead. Not sure if this is an ongoing problem or not, but it could *potentially* lead to a bit of confusion, wasted cycles for community contributors in particular, and simply the wrong version number being added to our templates.

**Comment by tammullen** [comment]
Thanks for raising, we think this is a one off as the usual small window between code freeze and version bump (automated but needs manually merged) in trunk was bigger than normal https://github.com/woocommerce/woocommerce/pull/48653
