### ISSUE TITLE
Add a new icon style to the Customer account block

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#48793]
@verofasulo requested a new icon style for the Custom account block. Moving on, we should come up with a more robust solution that will enable users to pick any icon they like, but that problem needs to be solved in WordPress core first.

For now, let's add a new icon style. It should behave exactly like the other two and follow the text size and color.

Here's the icon:

![customer_account_icon_new](https://github.com/woocommerce/woocommerce/assets/79307566/180afbdf-83c2-4dfd-8079-d8fbbb937c89)

**Comment by gigitux** [comment]
Thanks for opening this issue, @jarekmorawski!

Just to clarify, should we add a third option with this icon?

![image](https://github.com/woocommerce/woocommerce/assets/4463174/6eca8774-d2e5-4f17-8aa7-4cf0b536e91b)

**Comment by jarekmorawski** [comment]
Yup! That's what I pictured.
