### ISSUE TITLE
[Enhancement]: Overriding receipt template

### ISSUE THREAD

**Issue by Rahmon** [woothemes/woocommerce#48812]
### Describe the solution you'd like

Currently, there are some filters that allow to customize the order receipt generation (added by #46224):
- woocommerce_printable_order_receipt_data
- woocommerce_printable_order_receipt_line_item_display_data
- woocommerce_printable_order_receipt_css

However, I'd like to suggest adding a filter to override the template itself. It could be a filter to change the path to the template or a filter to change the rendered template.

Examples:

1. woocommerce_printable_order_receipt_template_path

```php
ob_start();
$template_path = apply_filters( 'woocommerce_printable_order_receipt_template_path', __DIR__ . '/Templates/order-receipt.php', $data, $order );
include $template_path;
$rendered_template = ob_get_contents();
ob_end_clean();
```

2. woocommerce_printable_order_receipt_rendered_template

```php
ob_start();
include __DIR__ . '/Templates/order-receipt.php';
$rendered_template = apply_filters( 'woocommerce_printable_order_receipt_rendered_template', ob_get_contents(), $data, $order );
ob_end_clean();
```

### Describe alternatives you've considered

It's possible to use the filter [rest_dispatch_request](https://developer.wordpress.org/reference/hooks/rest_dispatch_request/) to override the template. However, it's necessary to mimic some steps of the `generate_receipt` function to guarantee the output follows the expected shape.

```php
add_filter(
	'rest_dispatch_request',
	function( $dispatch_result, $request, $route, $handler ) {
		if ( '/wc/v3/orders/(?P<id>[\d]+)/receipt' !== $route) {
			return $dispatch_result;
		}

		/**
		 * Implement the custom logic
		 * 
		 * 1. Check for `force_new` parameter
		 * 2. Calculate the expiration date
		 * 3. Create the transient file
		 * 4. Save the transient file name to the order metadata
		 * 5. Get the public URL
		 * 6. Return the public URL and the expiration date
		 */

		return $dispatch_result;
	}
);
```

### Additional context

- https://github.com/woocommerce/woocommerce/issues/46122
- https://github.com/woocommerce/woocommerce/pull/46224

**Comment by dave-green-uk** [comment]
This would be incredibly valuable!

**Comment by naman03malhotra** [comment]
Hey @Rahmon, thanks for opening this issue. We definitely see the value in this, and we would be open to receiving a PR for it as well.
