### ISSUE TITLE
[Enhancement]: improving WC_Product_Variables' get_available_variations function's performance by using wc_get_products 

### ISSUE THREAD

**Issue by eddr** [woothemes/woocommerce#48892]
Edit: closed it in order to provide more detailed analysis 

### Describe the solution you'd like

Hello!

So, we encountered a performance hit in a certain situation with a site that has many variations. The solution is complex but part of it might be improving _get_available_variations_ inside WC_Product_Variable class. 

The current code is:

`public function get_available_variations( $return = 'array' ) {
	$variation_ids        = $this->get_children();
	$available_variations = array();

	if ( is_callable( '_prime_post_caches' ) ) {
		_prime_post_caches( $variation_ids );
	}

	foreach ( $variation_ids as $variation_id ) {

		$variation = wc_get_product( $variation_id );
		[...]
`
Which results in many DB queries and a lot of PHP time ( unclear to me why ).

We propose ( and tried ) the following simple change:
`$variation_args = [
			'include' => $variation_ids,
			'type' => ['variation'],
			'limit' => 0
		];
		$variations = wc_get_products( $variation_args );
		
		foreach ( $variations as $variation ) {
[...]
`

it's a small improvement for a specific use case, but could be significant

### Describe alternatives you've considered

Alternatives might be related to improving other nodes in the process. It seems that for some reason, although fetching the data from the DB is not that of a performance hit, creating multiple WC_Product objects is.

1. Caching variations / products in some way ( maybe related to #24659 ) - in our case, where the same variation is queried again and again, it would be very helpful
2. Reducing calculations needed for creating the final WC_Product object or at least allowing some easy parameters to be used in order to reduce them
3. Reusing 'WC_Data_Store' object ( by type ) instead of creating it all over again for hundreds of times? not sure about the performance impact, but still it looks like something that could be improved
4. In our specific case we using a 3rd party WC plugin which needs to be improved, but that's a different issue.

### Additional context

The scenario:
Latest WooCommerce and WordPress version
Using 'WPC Product Bundles for WooCommerce (Premium)' plugin ( and almost no other, for testing purposes )
Having a bundle product that includes individual products with perhaps 30-40 variations each. In our case, the bundled products are actually identical, so repetitiveness is even more significant

A separated performance test resulted in big difference:

Test code:
`
require_once( 'wp-load.php' );

$_ids = wc_get_products( [ 'limit' => 100, 'return' => 'ids'] );

$_t1 = microtime( true );
$_ps = [];
$_ids = wc_get_products( [ 'limit' => 100, 'return' => 'ids'] );

$_do_wc_get_product = true;

$_t1 = microtime( true );

// Run wc_get_product individually for each ID
//
if ( $_do_wc_get_product  ) {

    foreach( $_ids as $id ) {

        $_ps[] = wc_get_product( $id );
    }
}
else {
    $_ps2 = wc_get_products( [ 'include' => $_ids, 'limit' => 100 ] );
}
$_t2 = microtime( true );

echo $_t2 - $_t1;
`

Results in our system had a rather consistent ratio of about 1:4

**Comment by pduclo** [comment]
Hi eddr, Did you make a follow-up to this? I am seeing the same thing with get_available_variations. When I have 1000s of variations (most of which are out of stock) the php used to filter out the outofstock variations is so much slower than if it were done in the db query. I might have 5000 variations for a product but only 200 in stock.

**Comment by eddr** [comment]
Hi @pduclo 

Sorry, no. I partially solved the problem locally by caching some stuff, it helped immensely in my case but I think this is not a general solution
I can send the changes if you wish

**Comment by pduclo** [comment]
Sure. I'll give it a try. Thanks.

I'll try modifying the get_available_variations() function in a few weeks to see if I can overcome that php overhead.
