### ISSUE TITLE
Product Collection: hand-picked products filter isn't working as expected for "On Sale" collection

### ISSUE THREAD

**Issue by imanish003** [woothemes/woocommerce#48918]
I found out that hand-picked products filter isn't working as expected for "On Sale" collection. 

## Steps to reproduce

1. Create a new post and add Product Collection block.
2. Select "On Sale" collection and then add hand-picked products filter.
3. In hand-picked products, add some products that aren't on sale.
    - For example, in sample products, "Album" isn't on sale. So you can add that.
4. You will notice that all products are showing instead of only handpicked products.

Here is a demo video:

https://github.com/woocommerce/woocommerce/assets/16707866/567f7f1c-61ed-4c41-a261-53d69f5392bf

## Expected behavior

IMO
- either we should show only on sale products in Handpicked filter when On Sale collection is selected.
- OR If there are handpicked products that aren't on sale, then we shouldn't show any products. Because it doesn't make sense to ignore handpicked filter and show all the products.

CC: @kmanijak

**Comment by ObliviousHarmony** [comment]
Hello @imanish003,

I've just checked `trunk` and I can't seem to replicate this.

**Comment by ObliviousHarmony** [comment]
This is fixed by the `post__in` merging in https://github.com/woocommerce/woocommerce/pull/51076.

**Comment by imanish003** [comment]
Let's test it after merging #51076. If the issue is no longer reproducible post-merge, we can close this issue 🚀

**Comment by imanish003** [comment]
I tested it after merging #51076. The issue is no longer reproducible. So, I am closing this issue 🙌🏻
