### ISSUE TITLE
Product Editor: Adding variations erroring after React 18 createRoot() change

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#48933]
**Issue Description:**

After the change from React 17's `render()` to React 18's `createRoot()`, it seems like creating a variation in the new product editor causes a block error.

To reproduce, you need to make this change in `./plugins/woocommerce-admin/client/index.js` or use the build from [this branch](https://github.com/woocommerce/woocommerce/pull/48785).

```diff
-import { render } from '@wordpress/element';
+import { render, createRoot } from '@wordpress/element';
...
-       render(
+	createRoot( appRoot ).render(
		<ErrorBoundary>
			<HydratedPageLayout />
-		</ErrorBoundary>,
-              appRoot
+		</ErrorBoundary>
	);
``` 

Screen Capture:

https://github.com/woocommerce/woocommerce/assets/27843274/3d15f749-7ea5-4f8d-9bab-920b70fb294f

Stack Trace:
```
TypeError: w is undefined
    zw https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/block-editor.min.js?ver=868d782fcb169133c92b:26
    wt https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    vr https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    js https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    wl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    bl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    yl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    il https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    fl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Nn https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    xl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    xl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    ol https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    v https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
    ce https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
```

As far as I can determine, this error originates from [the block editor package from Gutenberg](https://github.com/WordPress/gutenberg/blob/ea72cf12669b42e477ce3b388c5a00ecc2954e29/packages/block-editor/src/components/inner-blocks/index.js#L135)

Reasons for believing so:

The error occurs in this minified file: `./wp-includes/js/dist/block-editor.min.js?ver=868d782fcb169133c92b` on line 41107.
```
 return 0 === Object.keys(w.providesContext).length ? P : (0, s.createElement) (Ow, {
```

Findings on this:
- `w` seems to be a block from context
- changing from `render()` to `createRoot()` activates React's concurrent mode and batching
- It's likely an issue with either of those causing a race condition 
- It's not reproducible in my local environment
- Installing Gutenberg doesn't fix it
- Happens on Jurassic Ninja with WP 6.5.5

**Comment by louwie17** [comment]
There appears to be some weird behaviour going on, on the variation tab anyhow when generating variations. As it appears its doing a redirect.
When this, locally it was redirecting to the `General` tab for me, so potentially addressing the redirect will fix this?

**Comment by mattsherman** [comment]
> There appears to be some weird behaviour going on, on the variation tab anyhow when generating variations. As it appears its doing a redirect. When this, locally it was redirecting to the `General` tab for me, so potentially addressing the redirect will fix this?

That is what I was seeing as well. There is some convoluted state management of the selected tab that is causing this -- I'm addressing this in #49058.

**Comment by mattsherman** [comment]
Reopening this, as it does not appear fixed.
