### ISSUE TITLE
Dropshipping Import Products for WooCommerce - Won't detect UTF-8 - Č and Ž letter.

### ISSUE THREAD

**Issue by nscrm** [woothemes/woocommerce#48956]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I try to import, I won't detect UTF-8 - Č and Ž letters and import just without those letters.

### Expected behavior

I believe that UTF-8 is not supported.

### Actual behavior

I must import a .csv file with 170 items to my Slovenian language store. The file includes special characters like Č, Š, and Ž and is saved in UTF-8 format. Unfortunately, when I try to import it using the Dropshipping Import Products for WooCommerce plugin, the preview fails to detect the characters Č and Ž. Consequently, when I proceed with the import, these letters are not imported correctly.

### Steps to reproduce

1. import .csv woocommerce products file
2. There is an instant error with those letters on the preview.

### WordPress Environment

WordPress - Dropshipping Import Products for WooCommerce - Import Manager - Create New

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
Hi @nscrm , this is open source repo WooCommerce core plugin. We do support special characters, I think you would want to reach out to support folks from the "Dropshipping Import Products for WooCommerce" plugin to get relevant help.

I am closing this issue for repo maintenance, but reach out if that's incorrect and issue is indeed with woocommerce core plugin.
