### ISSUE TITLE
WooCommerce changing the WP lost Password page

### ISSUE THREAD

**Issue by paaljoachim** [woothemes/woocommerce#48958]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am testing a site that use the Enfold theme. (I do not want to switch to a default WP theme and back again to Enfold as I can risk not having the Enfold theme show things with errors.)

All plugins are off except WooCommerce.
I am logged out in another private tab. As I login and click the Lost Password link.

**The regular Lost Password page.**
This is what is seen when WooCommerce is deactivated. (Tested with no plugins active and all other plugins active.)

![Screenshot 2024-06-29 at 13 35 28](https://github.com/woocommerce/woocommerce/assets/5323259/c05aa5fe-28b7-41ee-91cb-d447e73eb05d)

**Not expected page.**
When activating WooCommerce 9.0.2 the following lost password screen is seen.
(The page is also slow to load.)

![Screenshot 2024-06-29 at 13 40 20](https://github.com/woocommerce/woocommerce/assets/5323259/f96238f1-38dd-43bf-955e-a383d9663948)

This issue seems to be associated: https://github.com/woocommerce/woocommerce/issues/48479

### Expected behavior

I expect to be able to go to the regular Lost Password screen. Even with the Enfold theme.

### Actual behavior

Using the Enfold theme and WooCommerce. Clicking the Lost Password link in the login screen leads to wrong page.
I will have to also share this issue with Enfold as it might be something they have to fix. I do want to mention it here if there is something WooCommerce should do in relation to this issue.

### Steps to reproduce

I have Enfold theme active.
Logging in and clicking Lost Password leads to a wrong page.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.0.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nb_NO
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.6 (CloudLinux) OpenSSL/1.0.2k-fips
PHP Version: 8.2.13
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.36
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 207
avia_framework_post: 59
flamingo_contact: 13
flamingo_inbound: 12
itsec-dash-card: 10
itsec-dashboard: 1
nav_menu_item: 127
oembed_cache: 2
page: 21
post: 2
product: 95
revision: 15
wp_global_styles: 2
wp_navigation: 1
wp_template: 2
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

ManageWP - Worker: by GoDaddy – 4.9.20
Koko Analytics: by ibericode – 1.3.10
Polylang: by WP SYNTEX – 3.6.3
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.28.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Code Snippets Pro (Premium): by Code Snippets Pro – 3.6.5
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 7.1.0
Contact Form 7: by Takayuki Miyoshi – 5.9.6
Discourage Search Engines Notifier: by <a href="http://ragu.cz">Ragu.cz</a> – 2.0
Duplicator Pro: by Duplicator – 4.5.17.4
Email Encoder - Protect Email Addresses: by Jannis Thuemmig – 2.2.2
Flamingo: by Takayuki Miyoshi – 2.5
Imsanity: by Exactly WWW – 2.8.4
Solid Security Pro: by SolidWP – 8.5.0
WooCommerce: by Automattic – 9.0.2
WP Rocket: by WP Media – 3.16.1.1

### Inactive Plugins (12) ###

Asset CleanUp: Page Speed Booster: by Gabe Livan – 1.3.9.3
Duplicate Page: by mndpsingh287 – 4.5.3
Glow: by Glow – 3.2.0
Site Kit by Google: by Google – 1.129.1
Smush: by WPMU DEV – 3.16.5
Sold Out Badge for WooCommerce: by Charlie Etienne – 4.4.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.3

WP Rocket | Change Parameters: by WP Rocket Support Team –
WPS Menu Exporter: by WPServeur
NicolasKulka
wpformation
benoti – 1.3.7.1

Yoast SEO: by Team Yoast – 22.9
Yoast SEO: WooCommerce: by Team Yoast – 16.2
Yoast SEO Premium: by Team Yoast – 22.9

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

ManageWP - Worker Loader: by GoDaddy – 1.0.0
WordPress automation by Installatron: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 510 KB

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Enfold
Version: 5.7.1
Author URL: https://kriesi.at
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-06-29 19:48:21 +00:00
Options: ✔
Notes: 88
Onboarding: skipped

### Action Scheduler ###

Complete: 623
Oldest: 2024-05-29 12:40:46 +0000
Newest: 2024-06-29 11:46:18 +0000

Failed: 180
Oldest: 2023-09-07 20:53:31 +0000
Newest: 2024-06-29 11:41:52 +0000

In-progress: 1
Oldest: –
Newest: –

Pending: 10
Oldest: 2024-06-29 11:47:32 +0000
Newest: 2024-06-30 11:00:52 +0000


### Status report information ###

Generated at: 2024-06-29 11:47:33 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adimoldovan** [comment]
Hi @paaljoachim!
I tried this flow with a WP theme and it worked as expected, so it looks like an issue with the Enfold theme. Please come back to us if it turns out to be something on Woocommerce side.

**Comment by paaljoachim** [comment]
Hi

I switched over to Twenty Twenty Four and did a refresh through WP Rocket. I received a this page is not found error.
![Screenshot 2024-07-02 at 14 22 41](https://github.com/woocommerce/woocommerce/assets/5323259/b7f7a8ae-b494-4501-bdf8-e9c6ca10ec79)

I deactivated WooCommerce and did a refresh through WP Rocket and another hard refresh using shift+cmd+R and the Lost password page came up.

![Screenshot 2024-07-02 at 14 25 31](https://github.com/woocommerce/woocommerce/assets/5323259/115b6035-d597-4b9a-814a-06970f641ce1)

I got to say right now that the original site labhuset.no which was now cloned over to industrihuset.no has had multiple problems from the very start. Enfold and WooCommerce has been at the heart of these problems. Here is an issue I made a few months ago. https://wordpress.org/support/topic/recovery-mode-mentions-these-errors/

I will suggest having someone contact me at paaljoachim@hotmail.com or paaljoachim@easywebdesigntutorials.com so that I can give direct access to see where WooCommerce fits into all of this. As it might uncover something that would be beneficial to look at closer.

---

I retested. Deactivating and reactivating WooCommerce. Twenty Twenty Four theme is active.
https://industrihuset.no/

Used another browser. The Lost Password page is still not showing up.

**Comment by senadir** [comment]
Hey @paaljoachim, Nice to see you again :D 

 
This might be related to your permalink settings.

For me, clicking "lost password" link redirects to `my-account/lost-password/`

<img width="1132" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6165348/19f8a2c8-7def-4985-be59-e593205712d7">

This is because WooCommerce overrides the lost password url here

https://github.com/woocommerce/woocommerce//blob/fed46ed1e7c11d737ecabc6379dd3a1abfbf948e/plugins/woocommerce/includes/wc-account-functions.php#L13-L41

Accessing wp-login.php?action=lostpassword directly does give me the lost password page.



In your `wp-admin/admin.php?page=wc-settings&tab=advanced` page, ensure there's a My Account page set and ensure the permalinks are set for that page:


<img width="1042" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6165348/e486a33c-db17-4e8b-8f61-a5557c7c3471">


The function logic seems does protect against that, so there might be something else at play.

You can choose to disable that behavior via removing the filter if you want:

```php
remove_filter( 'lostpassword_url', 'wc_lostpassword_url', 10, 1 );
```

**Comment by paaljoachim** [comment]
Heya @senadir Seghir. I had to check Slack to see the last time we connected...:) Good to hear from you again.

Ahhh so WooCommerce does take over the Lost password page atleast in regards when the Enfold theme is activated.
WooCommerce -> Settings ->  Advanced. I changed the lost-password name to something else. Saved. Also resaved the Permalinks. Then this site went to the correct Lost password page: https://industrihuset.no/wp-login.php?action=lostpassword

The other site where I have not done anything still goes to this password page: https://labhuset.no/lost-password/

Going to the Advanced page and just resaving and doing a hard refresh it now goes to https://labhuset.no/wp-login.php?action=lostpassword

So to me it seems like an error in Enfold. Not sure if there is anything WooCommerce should do about it or not.
I will share this issue with Enfold support.

Btw
Thank you for setting me on the right track Seghir!

**Comment by thealexandrelara** [comment]
Thank you for reporting this issue and for explaining the permalink settings, Seghir. As this does not seem to be a WooCommerce-related issue, I will close this issue for now. 

If you have any further questions or if the issue persists and you believe it is related to WooCommerce, please feel free to reopen the issue 🙌 .
