### ISSUE TITLE
[Enhancement]: woocommerce_after_subscription_object_save is too late and needs a pre-save counterpart

### ISSUE THREAD

**Issue by skunkbad** [woothemes/woocommerce#48960]
### Describe the solution you'd like

When a subscription is saved for any reason, whether it be by admin or customer, and even when there is no status change, I have a need to take action on the subscription, and this includes making an API request that is not free and has rate limits. When I use the woocommerce_after_subscription_object_save action it is called multiple times. As many as 9 times in my testing. I'd really like to be able to just have this action called once, **but even if were only called once, the subscription has already been saved, leading to buggy behavior if I call the save method again.**

### Describe alternatives you've considered

As a work-around, I've set a transient and do the API requests and extra processing triggered by a cron looking for the transients, but this isn't ideal as transients are not guaranteed to exist. I could instead create a custom queue in the database and process the subscriptions through that, but feel like this amount of work shouldn't be necessary, and hope that you will consider adding a filter on the subscription just before it's saved.

### Additional context

It's also important to give admins and customers instant feedback on the processing that's happening on their subscriptions, but this is impossible to do with the transients or DB queue solutions that I've described as alternatives.

**Comment by rrennick** [comment]
@skunkbad I'm going to mark this as a support request. That will add a comment with instructions for contacting support. This issue looks to be related to the WooCommerce Subscriptions extension.

**Comment by skunkbad** [comment]
When an issue is created here, one of YOUR options is "Enhancement Request".  If this doesn't meet your requirements for an enhancement request, then what does?

**Comment by rrennick** [comment]
> When an issue is created here, one of YOUR options is "Enhancement Request".

> woocommerce_after_subscription_object_save

@skunkbad WooCommerce core does not have a `subscription` order type. This hook will not be called at all when only WooCommerce is active. That's why I suggested you to contact support for the extension you are using that adds subscription support.
