### ISSUE TITLE
Fix broken metrics tests run

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#48972]
Metrics tests are broken again:

`Error: Command failed: npm install -g pnpm@^9.1.0 && cd plugins/woocommerce && pnpm test:metrics editor`

See [this run](https://github.com/woocommerce/woocommerce/actions/runs/9735008637/job/26863729163#step:9:81)

**Comment by tammullen** [comment]
Internal discussion pdV5qK-zn-p2

**Comment by adimoldovan** [comment]
Fixed with https://github.com/woocommerce/woocommerce/pull/50214
