### ISSUE TITLE
[Navigation Feature] Remove code strategically

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#48997]
Instead of going through a deprecation process, we could remove the code functionality all at once and keep the classes like \Automattic\WooCommerce\Admin\Features\Navigation\Menu intact with dummy functions that return nothing, or maybe a notice. The default would be the current experience. Add a Tracks event in there and we’ll know for sure if anyone is actually using this feature.

**Comment by psealock** [comment]
## Internal plugins with registration 

These plugins have Navigation integration we need to remove. https://github.com/woocommerce/woocommerce-admin/issues/5335
- [ ] https://github.com/Automattic/woocommerce-payments/pull/1067 - https://github.com/Automattic/woocommerce-payments/pull/9228
- [x] https://github.com/woocommerce/automatewoo/pull/836 - https://github.com/woocommerce/automatewoo/pull/1843
- [x] https://github.com/woocommerce/automatewoo-referrals/pull/100 - https://github.com/woocommerce/automatewoo-referrals/pull/314
- [x] https://github.com/woocommerce/google-listings-and-ads/pull/605 - https://github.com/woocommerce/google-listings-and-ads/pull/2574
- [x] https://github.com/woocommerce/woocommerce-subscriptions/pull/3868 - No sign of Navigation in current code base
- [ ] https://github.com/woocommerce/woocommerce-product-addons/pull/637 - https://github.com/woocommerce/woocommerce-product-addons/pull/1070
- [ ] [Klarna](https://github.com/krokedil/klarna-payments-for-woocommerce/pull/208) - https://github.com/krokedil/klarna-payments-for-woocommerce/pull/396
- [ ] https://github.com/woocommerce/woocommerce-bookings/pull/3001 - https://github.com/woocommerce/woocommerce-bookings/pull/3846
- [ ] https://github.com/woocommerce/woocommerce-product-csv-import-suite/pull/186
- [ ] https://github.com/woocommerce/woocommerce-product-vendors/pull/618
- [ ] https://github.com/woocommerce/woocommerce-xero/pull/242
- [ ] https://github.com/woocommerce/woocommerce-box-office/pull/301
- [x] https://github.com/woocommerce/facebook-for-woocommerce/pull/1837 - https://github.com/woocommerce/facebook-for-woocommerce/pull/2800

**Comment by tomalec** [comment]
Does the reference to "WooCommerce Navigation" in https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/docs/extension-development/working-with-woocommerce-admin-pages.md?plain=1#L62-L64 means the removed navigation, or the regular one?

Also, should we keep the code like this https://github.com/woocommerce/woocommerce/blob/8b35b0785c761bda0b90188ade462c83af5b3643/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php#L122:L138 in place for some longer support?

**Comment by psealock** [comment]
>means the removed navigation, or the regular one?

Thanks @tomalec, yes that is the one that was removed. Thanks for surfacing.

>Also, should we keep the code like this

Good find as well, this can be safely removed. I can't think of a reason why "Payments" would need to be added once again if the option is set to `yes` as the entire UI has been removed.
