### ISSUE TITLE
Accessibility: Incorrect use of links on the Checkout block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#49046]
### Describe the solution you'd like

https://a11y-101.com/design/button-vs-link states:

> A link is focusable and can be triggered by the enter key. A link will redirect you to a new page or a section within the same page. [...]
> 
> A button is focusable, too, and can be triggered by the space key. A button will trigger an action like opening or closing something. Or sending a form. In most cases JavaScript is used to do this. [...]

On the Checkout block, we condense both the billing and the shipping address for returning and logged-in shoppers. To edit the addresses, the shopper can click a link called `Edit`:

<img width="1499" alt="Screenshot 2024-07-02 at 20 45 34" src="https://github.com/woocommerce/woocommerce/assets/3323310/372b40b3-1848-4b5c-b04a-b345763b611f">

When using the keyboard, buttons can be triggered by pressing the SPACE BAR. Examples of that are the `Add a coupon` button and the `+ Add apartment, suite, etc.` button:

<img width="1487" alt="Screenshot 2024-07-02 at 20 49 14" src="https://github.com/woocommerce/woocommerce/assets/3323310/497249d3-3316-452a-a760-69cdf0517bae">

Using both `<a>` and `<button>` to open sections is confusing to shoppers, as `<a>` elements are triggered via the ENTER key instead of via the SPACE BAR, as for `<button>` elements. Based on the reference I shared above, we should use `<button>` elements for all actions that open or close something.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by opr** [comment]
> Based on the reference I shared above, we should use <button> elements for all actions that open or close something.

Sounds good, I looked at some other sources and agree with this.

We would likely need to update the handlers to react to the `space` press wouldn't we? When changing that `Edit` link to a button, it didn't work when I pressed space.

**Comment by nielslange** [comment]
> We would likely need to update the handlers to react to the space press wouldn't we? When changing that Edit link to a button, it didn't work when I pressed space.

Which handlers are you referring to? Isn't that something React does under the hood when changing an `<a>` to a `<button>` element?

**Comment by opr** [comment]
> Which handlers are you referring to?

When you click "edit" the address card changing into the form

> Isn't that something React does under the hood when changing an <a> to a <button> element?

I don't think so, but not 100% sure. Try it out and see :)

**Comment by nielslange** [comment]
Thanks for your swift reply, @opr. When I created this issue, I temporarily changed `<a>` to `<button>` and could not see any immediate issues. That said, it's good to keep your points in mind when working on this issue.

**Comment by Manussakis** [comment]
I have started working on this issue.
