### ISSUE TITLE
WooCommerce Blocks: Finish migration of block asset files

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#49108]
Since migrating the (now deprecated) WooCommerce Blocks plugin into the monorepo there is confusion around why the PHP source files are not colocated with the JS and assets for Woo Blocks.

For example:
* PHP source files for WooCommerce Blocks are located here: [plugins/woocommerce/src/Blocks](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/Blocks)
* JS files and assets for the same blocks are located here: [plugins/woocommerce-blocks/assets](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/assets)

**Proposed Solution**:

Since these files are closely related I believe they should be located near each other within the repository structure. We should move the JS files and assets so they reside closer to the PHP files somewhere so navigating the codebase is easier and more intuitive.

**Comment by adimoldovan** [comment]
@tjcafferkey Is this duplicating https://github.com/woocommerce/woocommerce/issues/43337?

**Comment by tjcafferkey** [comment]
@adimoldovan yes looks to be. Thank you! Ill close this.
