### ISSUE TITLE
Memberships export is broken

### ISSUE THREAD

**Issue by AntoineLePotagiste** [woothemes/woocommerce#49179]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In WooCommerce / Memberships / Import Export, the Export button doesn't work anymore.

backbone-modal.min.js?ver=9.0.2:1 Uncaught 
TypeError: Cannot read properties of null (reading 'target')
    at n.initialize (backbone-modal.min.js?ver=9.0.2:1:876)
    at n.initialize (wc-memberships-impor…s?ver=1.26.6:1:6994)
    at h.View (backbone.min.js?ver=1.5.0:2:14872)
    at n [as constructor] (backbone.min.js?ver=1.5.0:2:23777)
    at n.constructor (wc-memberships-modal…js?ver=1.26.6:1:307)
    at new n (backbone.min.js?ver=1.5.0:2:23777)
    at Object.success (wc-memberships-impor…s?ver=1.26.6:1:6501)
    at c (jquery.min.js?ver=3.7.1:2:25304)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=3.7.1:2:26053)
    at l (jquery.min.js?ver=3.7.1:2:77782)

### Expected behavior

I expect the Export button to work

### Actual behavior

In WooCommerce / Memberships / Import Export, the Export button doesn't work anymore.

### Steps to reproduce

In WooCommerce / Memberships / Import Export, the Export button doesn't work anymore.

### WordPress Environment

everything uptodate

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by AntoineLePotagiste** [comment]
![image](https://github.com/woocommerce/woocommerce/assets/82303666/552f75de-961f-472c-bf5a-95884ee899c8)

**Comment by lanej0** [comment]
Hi @AntoineLePotagiste -- memberships isn't a part of WooCommerce Core.  You must be using another plugin that provides that functionality.  If you provide a Site Status Report (WooCommerce > Status > Get System Report), we can help you out in tracking down which plugin is giving you trouble and get you in touch with the developers of that plugin.

**Comment by AntoineLePotagiste** [comment]
It's woo commerce subscriptions plugin I think. I have all latest versions of everything.

`
### WordPress Environment ###

WordPress address (URL): https://xxxxxx.com
Site address (URL): https://xxxxxx.com
WC Version: 9.0.2
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 130 Mo
PHP Time Limit: 165
PHP Max Input Vars: 16000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.0.2
WC Database Prefix: zpm434
Taille totale de la base de données: 317.01MB
Taille de la base de données: 240.86MB
Taille de l’index: 76.15MB
zpm434woocommerce_sessions: Données : 1.02MB + Index : 0.02MB + Moteur InnoDB
zpm434woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
zpm434woocommerce_order_items: Données : 1.52MB + Index : 0.36MB + Moteur InnoDB
zpm434woocommerce_order_itemmeta: Données : 6.52MB + Index : 6.00MB + Moteur InnoDB
zpm434woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
zpm434woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
zpm434woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434woocommerce_payment_tokens: Données : 0.08MB + Index : 0.02MB + Moteur InnoDB
zpm434woocommerce_payment_tokenmeta: Données : 0.19MB + Index : 0.22MB + Moteur InnoDB
zpm434woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434actionscheduler_actions: Données : 4.02MB + Index : 1.13MB + Moteur InnoDB
zpm434actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434actionscheduler_logs: Données : 2.02MB + Index : 1.14MB + Moteur InnoDB
zpm434commentmeta: Données : 0.33MB + Index : 0.34MB + Moteur InnoDB
zpm434comments: Données : 7.52MB + Index : 9.08MB + Moteur InnoDB
zpm434links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434login_redirects: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434options: Données : 5.03MB + Index : 0.25MB + Moteur InnoDB
zpm434postmeta: Données : 42.55MB + Index : 38.84MB + Moteur InnoDB
zpm434posts: Données : 26.28MB + Index : 3.64MB + Moteur InnoDB
zpm434slicewp_affiliate_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434slicewp_affiliates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434slicewp_collection_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434slicewp_collection_object_relationships: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434slicewp_collections: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434slicewp_commission_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434slicewp_commissions: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434slicewp_creatives: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434slicewp_customer_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434slicewp_customers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434slicewp_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434slicewp_payment_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434slicewp_payments: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434slicewp_payout_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434slicewp_payouts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434slicewp_visits: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
zpm434term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434usermeta: Données : 15.30MB + Index : 10.67MB + Moteur InnoDB
zpm434users: Données : 2.52MB + Index : 1.52MB + Moteur InnoDB
zpm434wc_admin_note_actions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
zpm434wc_admin_notes: Données : 0.09MB + Index : 0.00MB + Moteur InnoDB
zpm434wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434wc_customer_lookup: Données : 0.42MB + Index : 0.28MB + Moteur InnoDB
zpm434wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
zpm434wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434wc_order_product_lookup: Données : 1.52MB + Index : 0.55MB + Moteur InnoDB
zpm434wc_order_stats: Données : 1.50MB + Index : 0.50MB + Moteur InnoDB
zpm434wc_order_tax_lookup: Données : 0.19MB + Index : 0.22MB + Moteur InnoDB
zpm434wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
zpm434wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
zpm434wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434wc_product_meta_lookup: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
zpm434wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
zpm434wcpdf_invoice_number: Données : 0.17MB + Index : 0.00MB + Moteur InnoDB
zpm434wcpdf_packing_slip_number: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
zpm434wpml_mails: Données : 118.55MB + Index : 0.20MB + Moteur InnoDB

### Post Type Counts ###

attachment: 9
custom_css: 2
et_pb_layout: 2
nav_menu_item: 9
page: 17
product: 5
revision: 797
shop_order: 4559
shop_order_refund: 49
shop_subscription: 3425
wc_membership_plan: 1
wc_user_membership: 3285
wp_global_styles: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

If Menu - Visibility control for menus: par Par couches – 0.18.0
More Visibility Rules: par Layered – 0.4
LoginWP (Formerly Peter's Login Redirect): par LoginWP Team – 3.0.8.5
SliceWP: par SliceWP – 1.1.15
Thank You Page for WooCommerce: par Nitin Prakash – 4.1.3
WooCommerce.com Update Manager: par Automattic – 1.0.3
WooCommerce Stripe Gateway: par WooCommerce – 8.4.0
WooCommerce Memberships: par SkyVerge – 1.26.6
WooPayments: par Automattic – 7.8.1
WooCommerce PayPal Payments: par WooCommerce – 2.8.1
PDF Invoices & Packing Slips for WooCommerce: par WP Overnight – 3.8.4
Abonnements WooCommerce: par WooCommerce – 6.4.1
WooCommerce: par Automattic – 9.0.2
WP Mail Logging: par WP Mail Logging Team – 1.12.0

### Inactive Plugins (1) ###

Akismet Anti-spam: Spam Protection: par Automattic - Anti-spam Team – 5.3.2

### Dropin Plugins () ###

db-error.php: db-error.php

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 117 Ko

### WC Pages ###

Base de la boutique: #30 - /boutique/
Panier: #31 - /panier/
Commander: #32 - /commander/
Mon compte: #33 - /mon-compte/
Conditions générales de vente et d’utilisation: #90 - /cgv/

### Theme ###

Name: Divi Child
Version: (une mise à jour de la version 0 est disponible)
Author URL: https://astucesdivi.com/
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.20.2
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.8.1
Connected to WPCOM: ❌ Non
Logging: Désactivé

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 1
Abonné Potager Coach:: Members: 3285Access method: Product(s) purchaseAccess length: Specific length (1 years)Subscription: YesInstallment plan: No

### Abonnements ###

WCS_DEBUG: ✔ Non
Subscriptions Mode: ✔ En direct
Subscriptions Live URL: https://potagercoach.com
Subscriptions-core Library Version: 7.2.0
Subscription Statuses: wc-active: 2411
wc-pending-cancel: 186
wc-pending: 1
wc-on-hold: 314
wc-cancelled: 513

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Oui
Cache Update Failures: ✔ 0 échecs

### Configuration de la boutique ###

Country / State: France

### Abonnements par passerelle de paiement ###

Stripe: wc-cancelled: 498
wc-active: 2023
wc-on-hold: 314
wc-pending-cancel: 161
wc-pending: 1

PayPal: wc-cancelled: 15
wc-active: 388
wc-pending-cancel: 25


### Prise en charge de la passerelle de paiement ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

PayPal: refunds
products
tokenization
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: FR
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: PayPal Subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-06 10:36:12 +02:00
Options: ✔
Notes: 154
Onboarding: completed

### Action Scheduler ###

Terminé: 519
Oldest: 2024-06-04 21:42:18 +0200
Newest: 2024-07-05 12:25:49 +0200

Échoué: 9
Oldest: 2023-02-15 08:40:44 +0100
Newest: 2023-06-01 09:40:42 +0200

En attente: 2 795
Oldest: 2024-07-06 04:15:00 +0200
Newest: 2030-09-27 00:00:00 +0200


### Status report information ###

Generated at: 2024-07-05 20:21:57 +02:00
