### ISSUE TITLE
Template selector is visible in the Cart and Checkout pages

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#49190]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I might be misunderstanding [this code](https://github.com/woocommerce/woocommerce/blob/d3df046f975f1bc5f39c0c96deaa8b0277762406/plugins/woocommerce/src/Blocks/BlockTemplatesController.php#L78-L95), but I assume the Template selector should not be visible in the Cart and Checkout pages, however it is (tested with WP 6.5 and 6.6).

### Steps to reproduce

1. Go to Pages > Cart or Pages > Checkout.
2. In the _Page_ sidebar, notice there is the option to choose the template.

![image](https://github.com/woocommerce/woocommerce/assets/3616980/35777318-22ae-47ef-9fef-79f36112714b)

Expected behavior: there shouldn't be the Template option for Cart and Checkout pages.

### WordPress Environment

Tested with WP 6.5 and 6.6.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by opr** [comment]
@Aljullu thanks for the report, this seems related to https://github.com/woocommerce/woocommerce/issues/49095 would you prefer to carry on the discussion over there? I'll close this in case you do, but if you feel differently please reopen. Thanks!

**Comment by Aljullu** [comment]
> @Aljullu thanks for the report, this seems related to https://github.com/woocommerce/woocommerce/issues/49095 would you prefer to carry on the discussion over there? I'll close this in case you do, but if you feel differently please reopen. Thanks!

Ouch, yes, I missed that one. :man_facepalming:  Thanks for pointing out the relation, @opr!
