### ISSUE TITLE
[Enhancement]: Only add wccomHelper on admin pages

### ISSUE THREAD

**Issue by leonardola** [woothemes/woocommerce#49210]
The `wccomHelper` data is being added by [this hook ](https://github.com/woocommerce/woocommerce/blob/e62f28b3ca987d04d8a95625aea45c3321a9aa31/plugins/woocommerce/includes/admin/helper/class-wc-helper-admin.php#L30) and seems to only be used in [admin areas](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce+wccomHelper&type=code) (/wp-admin). The problem is it's being added to the blocks cart and blocks checkout pages too which ends up adding just a little bit of overhead in page loads. It would be good to add a check to prevent loading unnecessary data.

While profiling a WPCom site I noticed that this function was using about 7% of the total request time. For a fresh site with only Woo on it it only uses about 0.5% of the total request time so it definitely will have more impact on bigger sites with more code running.

**Comment by nielslange** [comment]
Thanks for creating this issue, @leonardola. In p1720434329064639-slack-C01LE21AWCD, I reached out to the team that implemented this part. Could you please add steps on how to reproduce this issue?

**Comment by raicem** [comment]
Thanks for the ping @nielslange! 

I don't think we have any reservations about using that hook, we likely used it without understanding the consequences fully (i.e. that this data is loaded frequently).

I can think of two solutions. I'm inclined to start with the first option, but please correct me if this needs more urgency or care.  

1) Quick `is_admin` check and returning early can prevent loading this code in the front end. However, admin pages where we actually don't need this data will continue to suffer.
2) Finding a new way to share PHP data to the JS script will minimize the performance hit as we can make sure we run this only when we need it.

**Comment by nielslange** [comment]
Thanks for your prompt reply, @raicem. I think going with option 1. is a good approach. After all, merchants are less affected by performance in the admin area, than shoppers are affected in the frontend area.

**Comment by leonardola** [comment]
For now I just disabled the hook on non admin areas in the affected site so no need to rush on my end. But this might be affecting other merchants which will benefit from a fix. 

>  I think going with option 1. is a good approach. After all, merchants are less affected by performance in the admin area

It depends. Some plugins already make the admin area pretty slow so adding unnecessary overhead is not ideal. So if possible I would prefer to add checks to only load it when really needed. I do agree that adding a `is_admin` check would be a quick win for customers though and we should get it in place until we get a better solution.
