### ISSUE TITLE
When editing a product's variations, variation SKUs are not updated when saved. 

### ISSUE THREAD

**Issue by zirplsoftware** [woothemes/woocommerce#49211]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When editing a product's variations, changes to the variation SKUs are not updated when saved. 

### Expected behavior

Each variation should be updated with its own specified SKU

### Actual behavior

The main product SKU remains in place. It is possible that the bug is not quite this behavior but rather that the first value added as the variation's SKU remains in place.

### Steps to reproduce

Add a product
Set the SKU
Add a variation
Set the variation's SKU to the same as the product
Save the product
Change the variation's SKU
Save the product
Note that the variation's SKU has not been updated

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://deepyarnings.com
Site address (URL): https://deepyarnings.com
WC Version: 9.0.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.5
PHP Version: 8.1.29
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.11.8-MariaDB-ubu2004
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.0.2
WC Database Prefix: wp_
Total Database Size: 42.59MB
Database Data Size: 33.22MB
Database Index Size: 9.37MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.03MB + Index: 1.47MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.03MB + Index: 1.30MB + Engine InnoDB
wp_aioseo_cache: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_visits: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_visits_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.19MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_omnisend_contact_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_omnisend_logs: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 5.28MB + Index: 0.23MB + Engine InnoDB
wp_peachpay_analytics_interval: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_peachpay_analytics_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_peachpay_customer_cart: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_peachpay_customer_cart_contents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_peachpay_customer_cart_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 5.19MB + Index: 2.66MB + Engine InnoDB
wp_posts: Data: 2.34MB + Index: 0.14MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_star_testimonial_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.25MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_attachment_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 9.39MB + Index: 0.08MB + Engine InnoDB
wp_wpmailsmtp_emails_queue: Data: 2.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_email_attachments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_email_tracking_events: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_email_tracking_links: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 1.02MB + Index: 0.78MB + Engine InnoDB
wp_wsal_occurrences: Data: 0.42MB + Index: 0.14MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 2
acf-post-type: 1
acf-taxonomy: 1
attachment: 110
cartflows_flow: 9
cartflows_step: 58
custom_css: 1
customize_changeset: 1
e-landing-page: 1
elementor_library: 4
et_body_layout: 1
et_footer_layout: 2
et_header_layout: 2
et_pb_layout: 20
et_tb_item: 3
et_template: 6
et_theme_builder: 1
genesis_custom_block: 1
nav_menu_item: 9
nf_sub: 4
page: 9
post: 2
product: 22
product_variation: 27
revision: 17
shop_coupon: 1
shop_order: 186
shop_order_refund: 2
stars_testimonial: 2
testimonial: 3
tss-sc: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wpcode: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Advanced Custom Fields: by WP Engine – 6.3.3
CartFlows Pro: by CartFlows Inc – 2.0.6
CartFlows: by CartFlows Inc – 2.0.8
Cost of Goods for WooCommerce: by WPFactory – 3.4.7
Facebook for WooCommerce: by Facebook – 3.2.4
FileBird Lite: by Ninja Team – 6.3.2
Flexible Shipping: by Octolize – 4.25.2
Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
WPCode Lite: by WPCode – 2.1.14
Metorik Helper: by Metorik – 1.7.1
Ninja Forms: by Saturday Drive – 3.8.5
Omnisend for WooCommerce: by Omnisend – 1.15.11
Pinterest for WooCommerce: by WooCommerce – 1.3.24
Testimonial Slider and Showcase: by RadiusTheme – 2.3.11
WooCommerce.com Update Manager: by Automattic – 1.0.3
Variation Swatches for WooCommerce: by Emran Ahmed – 2.1.1
Google Analytics for WooCommerce: by WooCommerce – 2.1.4
WooPayments: by Automattic – 7.8.1
WooCommerce PayPal Payments: by WooCommerce – 2.8.1
WooCommerce Subscriptions: by WooCommerce – 6.4.1
WooCommerce: by Automattic – 9.0.2
WP Mail SMTP Pro: by WP Mail SMTP – 4.0.2
WP Activity Log: by Melapress – 5.1.0

### Inactive Plugins (5) ###

Payments Plugin and Checkout Plugin for WooCommerce: Stripe, PayPal, Square, Authorize.net: by PeachPay
Inc. – 1.107.0

WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.3.0
WooCommerce Shipping & Tax: by WooCommerce – 2.6.1
WP File Manager: by mndpsingh287 – 7.2.9
WP Mail SMTP: by WP Mail SMTP – 4.0.1

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: by  – 1.9.1
Kinsta Must-use Plugins: by Kinsta Team – 3.1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 4 MB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #957 - /terms-and-conditions/

### Theme ###

Name: Divi
Version: 4.26.0
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.8.1
Connected to WPCOM: Yes
WPCOM Blog ID: 222091641
Account ID: acct_1NdSQFFkWWNtjMeg
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card,link
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://deepyarnings.com
Subscriptions-core Library Version: 7.2.0
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Connecticut

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

PayPal: refunds
products
tokenization
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: PayPal Subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-06 04:24:12 -04:00
Options: ✔
Notes: 107
Onboarding: completed

### Action Scheduler ###

Canceled: 2
Oldest: 2024-07-05 16:28:11 -0400
Newest: 2024-07-05 17:01:10 -0400

Complete: 4,697
Oldest: 2024-06-26 17:41:02 -0400
Newest: 2024-07-05 21:57:06 -0400

Failed: 43
Oldest: 2023-12-05 05:51:23 -0500
Newest: 2024-07-03 17:51:01 -0400

Pending: 16
Oldest: 2024-07-05 21:58:06 -0400
Newest: 2024-07-26 17:41:03 -0400

### Status report information ###

Generated at: 2024-07-05 21:57:26 -04:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment]
@zirplsoftware thank you for the report!

> Set the variation's SKU to the same as the product
Save the product

Didn't you get the following error when you try to set the same SKU? In my test, I can't set the variation SKU if it's the same as the product. Can you please check and update the steps to reproduce if possible? Thanks!

![Image](https://github.com/user-attachments/assets/7c0379de-8f41-4b50-842f-4304d326c483)

**Comment by tjcafferkey** [comment]
@zirplsoftware thanks for opening this issue. I got the same results as @dinhtungdu where I am unable to create a variation with the same SKU as the product. Tested on WP 6.6 and WC 9.2

If you are still experiencing this issue or have further information to help us reliably reproduce this please reopen but for the time being I will close this.

![Image](https://github.com/user-attachments/assets/6b7db565-5dcd-4ce7-b43f-355006e090b9)
