### ISSUE TITLE
ExtendStore task is not marked upon navigation back

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#49221]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a user clicks on the `Enhance your store with extensions` task and then navigates back to the Home page by clicking on the Home link, the ExtendStore task is not marked as completed. This status update only occurs after a full page reload, which is not an ideal user experience.

I think we should consider implementing a mechanism to always re-fetch the task list status whenever navigating back to the Home page from other pages. This ensures that the task list reflects the most current status of each task.

https://github.com/woocommerce/woocommerce/assets/4344253/48087b76-5671-4b05-a334-e53beaa3f6be

### Expected behavior

The ExtendStore task should be marked as completed immediately upon navigating back to the Home page, without requiring a full page reload.

### Actual behavior

The ExtendStore task remains marked as incomplete until a full page reload is performed.

### Steps to reproduce

1. Go to the `WooCommerce > Home`.
2. Click on the `Enhance your store with extensions task`
3. Click on the task.
4. Navigate back to the Home page by clicking on the Home link.
5. Observe that the ExtendStore task is not marked as completed.

### WordPress Environment

WP 6.5.5

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adrianduffell** [comment]
I think there are similarities here with the navigation badge in https://github.com/woocommerce/woocommerce/pull/50584

It would be good to ensure that hydrating this data won't cause multiple API fetches between both!
