### ISSUE TITLE
[Flaky] mini-cart/mini-cart-block.merchant.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49308]
can only be inserted once 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9859712773

**Comment by lanej0** [comment]
can only be inserted once 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9859986917

**Comment by Aljullu** [comment]
FYI: I assigned this issue to Rubik, as they own the Mini-Cart block.

**Comment by lanej0** [comment]
can only be inserted once 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9872418006

**Comment by lanej0** [comment]
can only be inserted once 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9872473905

**Comment by lanej0** [comment]
can only be inserted once 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9873811041

**Comment by lanej0** [comment]
can only be inserted once 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9873825707
