### ISSUE TITLE
[Enhancement]: Extend support for Tazapay Plugin in cart and checkout block

### ISSUE THREAD

**Issue by tazapay-suraj** [woothemes/woocommerce#49327]
### Describe the solution you'd like

We have a plugin called "tazapay" which is a payment gateway. When i am using checkout blocks i am not able to see Tazapay payment option on checkout page and on admin side i am getting a working that its not supported for block-based-checkout

![Screenshot 2024-07-10 at 9 29 38 AM](https://github.com/woocommerce/woocommerce/assets/163376974/0e9adac7-c606-4da5-bad2-9eb3303670f5)

Please add tazapay to support in block-based-checkout.

Thanks.

**Comment by lanej0** [comment]
It's best to get in touch with the developers of the tazapay plugin.  They'll be the ones who are best able to add support for blocks checkout to their payment plugin.
