### ISSUE TITLE
Prevent Printful open tab from sending browser referrer 

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#49349]
### Issue Description

Originally reported in pb22l9-304-p2 regarding a potential user privacy exposure in https://github.com/woocommerce/woocommerce/pull/48520

> Ensure that the URL is trusted and sanitized. Additionally, use rel="noopener noreferrer" to prevent the new page from accessing the original page’s window object.

### Acceptance criteria

1. Add the appropriate parameters to `window.open`. ChatGPT suggests: `window.open('...', '_blank', 'noopener,noreferrer');`

**Comment by rjchow** [comment]
After looking at the discussion in the linked P2 (and [confirming](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noopener) with mdn), it would seem that _blank implies noopener so only noreferrer is necessary.

(Although I do want to note that I wasn't aware of `window.opener` which seems to be a preeeeeeetty big security issue if we have things like settings on window.wcSettings!)
