### ISSUE TITLE
Woo Commerce css files loaded in the footer rather than in the header

### ISSUE THREAD

**Issue by romain-granai** [woothemes/woocommerce#49352]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Some css files such as wc-blocks-style-all-products-css, wc-blocks-style-cart-css or wc-blocks-packages-style-css to name a few, for whatever reason are loaded in the footer. I'd like to have those loaded in the header so I could easily overide them with my own css, without having to use dirty css tricks like !important.

### Expected behavior

CSS file should be loaded in the header.

### Actual behavior

CSS files are loaded in the footer.

### Steps to reproduce

right click => open developer tool => check in the footer => the woocommerce css files are loded in the footer

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://blone:8888
Site address (URL): http://blone:8888
WC Version: 8.9.2
REST API Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.18
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.2
WC Database Prefix: wp_
Total Database Size: 5.63MB
Database Data Size: 3.68MB
Database Index Size: 1.95MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.39MB + Index: 0.28MB + Engine InnoDB
wp_posts: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 76
acf-field-group: 9
attachment: 21
family: 9
nav_menu_item: 30
page: 10
post: 1
product: 5
revision: 78
shop_order_placehold: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Advanced Custom Fields PRO: by Delicious Brains – 5.9.9
Classic Editor: by WordPress Contributors – 1.6.3
Show Current Template: by JOTAKI Taisuke – 0.5.2
Simply Show Hooks: by Stuart O'Brien
cxThemes – 1.2.1

Big File Uploads: by Infinite Uploads – 2.1.2
WooCommerce: by Automattic – 8.9.2 (update to version 9.0.2 is available)

### Inactive Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
All-in-One WP Migration: by ServMask – 7.82
WP Hooks Finder: by Muhammad Rehman – 1.2.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 9 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Blone V1
Version: 1
Author URL: https://www.romaingranai.be
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: blone/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-07-11 12:46:17 +00:00
Options: ✔
Notes: 69
Onboarding: skipped

### Action Scheduler ###

Complete: 90
Oldest: 2024-06-09 16:17:19 +0000
Newest: 2024-07-10 14:31:11 +0000

Failed: 1
Oldest: 2024-06-04 13:03:10 +0000
Newest: 2024-06-04 13:03:10 +0000

Pending: 3
Oldest: 2024-07-10 14:59:15 +0000
Newest: 2024-07-10 21:40:06 +0000

### Status report information ###

Generated at: 2024-07-10 14:47:02 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment]
Hi @romain-granai ,

Thanks for reporting this issue. I tried a fresh installation with latest WooCommerce and WooCommerce 8.9.2 as yours but couldn't reproduce this issue. All WooCommerce CSS files are loaded inside `<head>` for me. Can you try to reproduce the issue with WooCommerce only and a default theme like Twenty Twenty-Four to ensure this isn't a plugin/theme config?

**Comment by patrickwc** [comment]
@dinhtungdu 
I am seeing this behaviour too, but only if I have used a WooCommerce Gutenberg block on that page, e.g. Best Selling Products. If I do, then these two files load outside of the `<head>`, way down the page at the top of all of the .js files near the end of `<body>`

```
<link rel='stylesheet' id='wc-blocks-style-css' href='...wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks.css?ver=1701185756' media='all' />
<link rel='stylesheet' id='wc-blocks-style-all-products-css' href='...wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/all-products.css?ver=1701185756' media='all' />
```

It makes trying to overwriting Woo styles in a project very difficult. I suppose this is because the block CSS is only loaded on the page if a WC block is used on the page, but by the time that check happens it's too late to load the CSS file in the `<head>`? If it can't be fixed it should be documented somewhere so theme authors are less confused.

I tested this with WP v 6.6.2 and Woo 9.3.3

**Comment by patrickwc** [comment]
I think this issue only happens with hybrid themes. I have tested with https://github.com/billerickson/BE-Starter and again, if a WooCommerce Gutenberg block is used on the page, the two stylesheets I mentioned above are loaded far down the page.

**Comment by dinhtungdu** [comment]
I can reproduce the issue now with non-block themes like Storefront or Twenty-Twenty.

Unfortunately, this is a general issue with non-block themes, and it applies to all blocks, not only ones from WooCommerce. You can try adding the Cover block, and you will see similar behavior: the cover block is added inline in the footer.

Previously, for classic themes, we load a big CSS file containing all blocks style in header (even what ones that aren't used on the current page), which is worse than loading only used blocks style in footer. That's the tradeoff we are taking.

You can read more about this behavior at https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/.

**Comment by patrickwc** [comment]
Hi @dinhtungdu ,

Thanks for the information. I have tested out my hybrid theme with and without `add_filter( 'should_load_separate_core_block_assets', '__return_true' );` and if I have that filter enabled, then I get the wp-block-cover styles in the footer of the page as you describe. However, if the filter is not enabled, they appear in the main block-library style.css file in the header. So I suppose the issue here is WooCommerce does not respect the `should_load_separate_core_block_assets` filter.

I suppose I'll just have to make our styles more opinionated for WooCommerce blocks.

**Comment by dinhtungdu** [comment]
> So I suppose the issue here is WooCommerce does not respect the should_load_separate_core_block_assets filter.

As the filter name suggests, that filter is only for Core block assets. So we don't use that filter for WooCommerce. As I mentioned above, loading style in the footer is the tradeoff we're taking over loading a big and growing CSS file that contains the style of all WooCommerce blocks.
