### ISSUE TITLE
[Enhancement]: Evaluate if we need to implement rate-limiting for checkout in core.

### ISSUE THREAD

**Issue by naman03malhotra** [woothemes/woocommerce#49388]
### Describe the solution you'd like

More context: p1720176681477009-slack-C0E1AV8T0

I also found that good folks from the blocks team are running a rate-limiting experiment ([Experiment: Add Rate Limits to Store API ](https://github.com/woocommerce/woocommerce-blocks/pull/5962/files)) for blocks checkout, which is behind a flag right now, [documentation](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/hooks/filters.md#woocommerce_store_api_rate_limit_options).

Their solution is based on tracking user ID and IP address and only allowing Y requests in X seconds.

However, we'd need to evaluate:
- Should such a solution exist in the core or be implemented at the payment plugin/gateway level?
- Do we want to extend the same solution to classic checkout and put it behind a feature flag (or make it default)?

Also, it would need some critical thinking and collecting feedback from the payment plugins, we can start with WC Payments and see if that will benefit them because most plugins apply rate-limits independently.

### Describe alternatives you've considered

Do nothing and no rate limits are applied; we rely on payment plugins to do that.

**Comment by maxrice** [comment]
We support & maintain the Clover payment gateway integration and we'd love to see this in core. It's a frequent issue in support and while Clover (and lots of other payment providers) have implemented their own solutions (like captchas, etc), it would be great for Woo to have a core option that can be part of a defense-in-depth strategy.

**Comment by barryhughes** [comment]
It would be great to widen this up to others, so I'm going to convert to a discussion. We'd also love input from @woocommerce/rubik given Naman's earlier note about [your rate limiting experiment](https://github.com/woocommerce/woocommerce-blocks/pull/5962/files) (ie, where should this live/is that sufficient)?
