### ISSUE TITLE
[Flaky] checkout/additional-fields.shopper.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49409]
Shopper can see server-side validation errors 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Shopper can fill in the checkout form with additional fields and can have different value for same field in shipping and billing address 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Shopper can see and edit submitted fields in my account area. Values are also sanitized and validated in my account area. 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Shopper can see and edit submitted fields in my account area. Values are also sanitized and validated in my account area. 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can input unsanitized values that become sanitized after checkout 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can fill in the checkout form with additional fields and can have different value for same field in shipping and billing address 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can see server-side validation errors 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can see server-side validation errors 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can see and edit submitted fields in my account area. Values are also sanitized and validated in my account area. 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can fill in the checkout form with additional fields and can have different value for same field in shipping and billing address 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can input unsanitized values that become sanitized after checkout 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
Shopper can input unsanitized values that become sanitized after checkout 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922203554

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922203554

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922297667

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10081438422

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10086387796

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10092748607

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10094157452

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10094157452

**Comment by lanej0** [comment]
Shopper can see server-side validation errors 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10096895071

**Comment by lanej0** [comment]
Shopper can input unsanitized values that become sanitized after checkout 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10096895071

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10096895071

**Comment by lanej0** [comment]
Shopper can see and edit submitted fields in my account area. Values are also sanitized and validated in my account area. 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10096895071

**Comment by lanej0** [comment]
Shopper can change the values of fields multiple times and place the order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10113584963

**Comment by lanej0** [comment]
Shopper can fill in the checkout form with additional fields and can have different value for same field in shipping and billing address 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10113584963

**Comment by lanej0** [comment]
Shopper can see server-side validation errors 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10113584963

**Comment by lanej0** [comment]
Shopper can input unsanitized values that become sanitized after checkout 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10113584963

**Comment by lanej0** [comment]
Shopper can see and edit submitted fields in my account area. Values are also sanitized and validated in my account area. 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10113584963

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
