### ISSUE TITLE
[Flaky] checkout/additional-fields.merchant.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49413]
Merchant can see additional fields in the order admin page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Merchant can edit custom fields from the order admin page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Merchant can see additional fields in the order admin page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Merchant can edit custom fields from the order admin page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Merchant can see additional fields in the order admin page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Merchant can edit custom fields from the order admin page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
