### ISSUE TITLE
[Flaky] checkout/checkout-block.merchant.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49412]
Return to cart link is visible and can be toggled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Merchant can see T&S and Privacy Policy links without checkbox 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Merchant can see T&S and Privacy Policy links with checkbox 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Return to cart link is visible and can be toggled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Merchant can see T&S and Privacy Policy links with checkbox 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Return to cart link is visible and can be toggled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Merchant can see T&S and Privacy Policy links without checkbox 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Merchant can see T&S and Privacy Policy links with checkbox 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
Company input visibility and optional and required can be toggled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
Merchant can see T&S and Privacy Policy links with checkbox 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
inner blocks can be added/removed by filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
renders without crashing and can only be inserted once 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
Merchant can see T&S and Privacy Policy links with checkbox 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968138417

**Comment by lanej0** [comment]
Apartment input visibility and optional and required can be toggled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10012013695

**Comment by lanej0** [comment]
Apartment input visibility and optional and required can be toggled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10012013695

**Comment by lanej0** [comment]
Merchant can see T&S and Privacy Policy links with checkbox 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10047144203

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
