### ISSUE TITLE
[Flaky] checkout/order-confirmation.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49415]
Confirm shipping address section is hidden, but billing is visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Place order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Confirm shipping address section is hidden, but billing is visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Confirm shipping address section is hidden, but billing is visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Place order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Place order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Confirm order downloads are visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Confirm shipping address section is hidden, but billing is visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10207677845

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
