### ISSUE TITLE
[Flaky] checkout/checkout-block.shopper.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49410]
Shopper can choose free shipping, flat rate shipping, and can have different billing and shipping addresses 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Shopper can log in to an existing account and can create an account 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
can place a digital order when shipping is disabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
can place a digital order when shipping is disabled, but Local Pickup is still enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Guest user can place order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Guest user can place order 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can log in to an existing account and can create an account 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
can place a digital order when shipping is disabled, but Local Pickup is still enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can choose free shipping, flat rate shipping, and can have different billing and shipping addresses 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can choose free shipping, flat rate shipping, and can have different billing and shipping addresses 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can log in to an existing account and can create an account 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9839367135

**Comment by lanej0** [comment]
User can add postcodes for different countries 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9985836103

**Comment by lanej0** [comment]
User can add postcodes for different countries 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9987121899

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9990997506

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9993269598

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9993269598

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9995045554

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9995045554

**Comment by lanej0** [comment]
User can add postcodes for different countries 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10002027463

**Comment by lanej0** [comment]
User can add postcodes for different countries 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003939751

**Comment by lanej0** [comment]
User can add postcodes for different countries 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
The shopper can choose a local pickup option 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10074124610

**Comment by lanej0** [comment]
Shopper can log in to an existing account and can create an account 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10122184604

**Comment by lanej0** [comment]
Shopper can log in to an existing account and can create an account 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10145855966

**Comment by lanej0** [comment]
Enable company field 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10174443836

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
