### ISSUE TITLE
[Flaky] checkout/additional-fields.guest-shopper.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49411]
Shopper can see an error message when a required field is not filled in the checkout form 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894637490

**Comment by lanej0** [comment]
Shopper can see an error message when a required field is not filled in the checkout form 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can fill in the checkout form with additional fields and can have different value for same field in shipping and billing address 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
Shopper can see an error message when a required field is not filled in the checkout form 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can fill in the checkout form with additional fields and can have different value for same field in shipping and billing address 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
Shopper can fill in the checkout form with additional fields and can have different value for same field in shipping and billing address 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10096895071

**Comment by lanej0** [comment]
Shopper can fill in the checkout form with additional fields and can have different value for same field in shipping and billing address 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10113584963

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
