### ISSUE TITLE
[Flaky] cart/cart-checkout-block-translations.shopper.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49418]
User can view translated Checkout block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9894792752

**Comment by lanej0** [comment]
User can view translated Checkout block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906158742

**Comment by lanej0** [comment]
User can view translated Checkout block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9906860033

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
