### ISSUE TITLE
System State Check don't work as expected (no realt-time-check)

### ISSUE THREAD

**Issue by xstable** [woothemes/woocommerce#49439]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have checked several times and made sure that the two files `Child-Theme-Webshop/woocommerce/myaccount/orders.php` and `Child-Theme-Webshop/woocommerce/order/order-details.php` are my updated version.

I think that Woo-Commerce checks the version based on the comment at the top of the files, and as you can see in the screenshots, it is "new" for both files.

But the state checker still complains that the files are out of date.
Even running `wp cache flush` on SSH or run "Clear Template Cache" in WooCommerce Tab "Tools" don't have any effect. 

BUT on the `next day` the state-check shows that the templates are all up-to-date.
I reproduced this with a duplicated Server... same behavior. Right after updating the template the state-checker still show wrong template version for hours... only on the next day, the state checker shows that anything is ok now.

**So i think it's a bug, that the System-State-checker not really test in real-time, but show some old (previous) test results.**

![image](https://github.com/user-attachments/assets/09d13c75-593a-48f5-9821-30924b8aecd1)

![image](https://github.com/user-attachments/assets/75d8bc8f-82c5-4826-a706-0221b7a3bc7c)

![image](https://github.com/user-attachments/assets/de434a27-1da8-4284-a00e-801afed4293f)

---- 

Forum Request (in German Language) here: https://de.wordpress.org/support/topic/theme-dateien-werden-trotz-update-als-veraltet-angezeigt/

### Expected behavior

State-checker should trigger a NEW "realt-time" test of the system.
Maybe a "re-check-now" button might be a good Idea!

### Actual behavior

System-State-checker don't really check the state, but show info of previous checks

### Steps to reproduce

1. Update your WooCommerce Template
2. Go to WoCommerce > Status and have a look down at section Templates
3. Try to run `wp cache flush` or `Clear Template Cache` in WooCommerce > Status > Tools, nothing will cause the State-Checker to re-check the state

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://test.mySecretDomain.com
Site address (URL): https://test.mySecretDomain.com
WC Version: 8.9.3
REST API Version: ✔ 8.9.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.5.4 - There is a newer version of WordPress available (6.5.5)
WP Multisite: –
WP Memory Limit: 356 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.2
PHP Version: 8.0.17
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.3.28-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.3
WC Database Prefix: wp_
Total Database Size: 312.39MB
Database Data Size: 150.31MB
Database Index Size: 162.08MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.32MB + Index: 0.24MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.61MB + Index: 0.25MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 2.62MB + Index: 0.49MB + Engine MyISAM
wp_aiowps_audit_log: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_aiowps_debug_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_logged_in_users: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_aiowps_message_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.17MB + Index: 0.07MB + Engine MyISAM
wp_e_submissions: Data: 0.00MB + Index: 0.03MB + Engine MyISAM
wp_e_submissions_actions_log: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_e_submissions_values: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_icl_background_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_core_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_languages: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_icl_languages_translations: Data: 0.11MB + Index: 0.11MB + Engine MyISAM
wp_icl_locale_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_message_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_mo_files_domains: Data: 0.25MB + Index: 0.10MB + Engine MyISAM
wp_icl_node: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_reminders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_strings: Data: 2.32MB + Index: 1.71MB + Engine MyISAM
wp_icl_string_batches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_packages: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_pages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_positions: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
wp_icl_string_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_translations: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
wp_icl_string_urls: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translate: Data: 7.05MB + Index: 0.17MB + Engine MyISAM
wp_icl_translate_job: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_icl_translations: Data: 0.10MB + Index: 0.17MB + Engine MyISAM
wp_icl_translation_batches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 6.14MB + Index: 0.03MB + Engine MyISAM
wp_imprint_fetcher: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_moove_activity_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 13.36MB + Index: 0.15MB + Engine MyISAM
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 7.30MB + Index: 1.20MB + Engine MyISAM
wp_posts: Data: 10.69MB + Index: 0.23MB + Engine MyISAM
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_documentmeta: Data: 0.47MB + Index: 0.42MB + Engine InnoDB
wp_storeabill_documents: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_storeabill_document_itemmeta: Data: 0.27MB + Index: 0.28MB + Engine InnoDB
wp_storeabill_document_items: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_storeabill_document_noticemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_document_notices: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_storeabill_journals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.14MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 0.28MB + Index: 0.17MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_user_registration_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp_wc_order_stats: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdcp_credits_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wf_sn_tests: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gzd_dhl_im_products: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wsal_generated_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 88.63MB + Index: 147.55MB + Engine InnoDB
wp_wsal_occurrences: Data: 4.52MB + Index: 7.03MB + Engine InnoDB
wp_wsal_periodic_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_sessions: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_xst_plugin: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xst_vat_id_check: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xst_vat_id_check_request_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

aam_policy: 4
attachment: 231
cc_restriction: 7
custom-css-js: 3
document_template: 6
elementor_font: 7
elementor_library: 14
faq: 23
itsec-dash-card: 8
itsec-dashboard: 1
nav_menu_item: 733
oembed_cache: 3
page: 505
post: 1
product: 7
revision: 1060
shop_order: 497
shop_order_refund: 1
ticket: 6
um_directory: 1
um_form: 3
user_registration: 6
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Security Ninja: by WP Security Ninja – 5.195
weLaunch Framework: by weLaunch.io – 1.1.1
WPML Multilingual CMS: by OnTheGoSystems – 4.6.11
All In One WP Security: by All In One WP Security & Firewall Team – 5.3.0
AntiVirus: by pluginkollektiv – 1.5.1
Content Control: by Code Atlantic – 2.3.0
Advanced Scripts: by Clean Plugins – 2.5.2
One Stop Shop for WooCommerce: by vendidero – 1.6.2
WPassword: by WP White Security – 2.6.0
User Registration: by WPEverest – 3.2.1.1
User Role Editor: by Vladimir Garagulya – 4.64.2
vendidero Helper: by vendidero – 2.2.3
Digital Goods for WooCommerce Checkout: by theDotstore – 3.7.4
Woo Credits Platinum: by http://woocredits.com/ – 4.1.5
Germanized for WooCommerce Pro: by vendidero – 3.10.3
Germanized for WooCommerce: by vendidero – 3.16.9
WooCommerce: by Automattic – 8.9.3 (update to version 9.1.1 is available)
WordPress TotalDesk: by weLaunch – 1.7.27
WP Mail SMTP: by WP Mail SMTP – 4.0.1
WP Activity Log (Premium): by Melapress – 5.0.0
WPML String Translation: by OnTheGoSystems – 3.2.12
xst_pluginChecker: by Samuel Suther  – 0.2.2

### Inactive Plugins (6) ###

Freemius Fixer: by Freemius – 1.0.0
My Wordpress Login Logo: by Afsal Rahim – 2.4.1
SVG Support: by Benbodhi – 2.5.5
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.6
WPML Media Translation: by OnTheGoSystems – 2.7.4

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Auto Activate Freemius Licenses: by Clean Plugins – 1.0
prime-mover-cli-plugin-manager.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: credits (credits)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 14 KB

### WC Pages ###

Shop base: #1560 - /wc-shop/
Cart: #2212 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /account/
Terms and conditions: #80 - /terms-of-service/

### Theme ###

Name: Child Theme Webshop
Version: 1.0
Author URL: http://omu.agency/
Child Theme: ✔
Parent Theme Name: Twenty Twenty
Parent Theme Version: 2.6
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: Child-Theme-Webshop/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 8.5.0
Child-Theme-Webshop/woocommerce/order/order-again.php version 3.5.0 is out of date. The core version is 7.8.0
Child-Theme-Webshop/woocommerce/order/order-details-item.php
Child-Theme-Webshop/woocommerce/order/order-details.php version 7.8.0 is out of date. The core version is 8.5.0

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-07-12 13:38:23 +02:00
Options: ✔
Notes: 153
Onboarding: completed

### Action Scheduler ###

Complete: 123
Oldest: 2024-06-12 08:38:15 +0200
Newest: 2024-07-12 10:00:52 +0200

Failed: 1,315
Oldest: 2021-08-20 11:20:11 +0200
Newest: 2024-06-25 20:15:43 +0200

Pending: 9
Oldest: 2024-07-12 22:00:36 +0200
Newest: 2024-07-13 10:00:36 +0200

### Status report information ###

Generated at: 2024-07-12 10:09:24 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment]
Hi @xstable,

Thanks for the report!

> So i think it's a bug, that the System-State-checker not really test in real-time, but show some old (previous) test results.

I can confirm the check is not real time, but it's intended, not a bug. WooCommerce scans template files in your theme and compares them with their corresponding WooCommerce templates, using the version from `@version` tag in the file header. The scan results is cached for an hour under a transient named `wc_system_status_theme_info`. The cache is necessary to ensure good performance when loading the Tools page.

If you want to force WooCommerce to scan your updated templates, you can use WP CLI to delete that transient like following

```
wp transient delete wc_system_status_theme_info
```

I'm closing this issue but feel free to continue the conversation if you still have more questions.

**Comment by xstable** [comment]
@dinhtungdu thanks for clarification. 
It would be awesome if you could add a simple button to the state-checker page which do exactly this... delete the wc_system... flag and retrigger the check.
This way it has no impact to the performance (as it only start if manually triggered) on the other hand you give developers full control when to "re-check" if anything ok now (e.g. after upgrading some templates).

**Comment by dinhtungdu** [comment]
@xstable Your suggestion makes sense. I created another issue in https://github.com/woocommerce/woocommerce/issues/49891 to track the work of adding the new tool. Thank you again for the report and recommendation.
