### ISSUE TITLE
[Flaky] product-filters-overlay/product-filters-overlay-template-part.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49434]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9902151559

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9935345448

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9937601384

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9941441444

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9942413165

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9942934758

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9952586194

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9954405210

**Comment by lanej0** [comment]
should render the Product Filters block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10094563101

**Comment by lanej0** [comment]
should be visible in the templates part list 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10094563101

**Comment by lanej0** [comment]
should render the Product Filters block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10095652449

**Comment by lanej0** [comment]
should render the Product Filters block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10107843114

**Comment by lanej0** [comment]
should render the Product Filters block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10119344375

**Comment by lanej0** [comment]
should render the correct inner blocks 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10152204690

**Comment by lanej0** [comment]
should navigate to product filters template part 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10152204690

**Comment by lanej0** [comment]
should navigate to product filters template part 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10152431333

**Comment by lanej0** [comment]
should navigate to product filters template part 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10152431333

**Comment by lanej0** [comment]
should render the correct inner blocks 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10161789333

**Comment by lanej0** [comment]
should render the correct inner blocks 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10162842666

**Comment by lanej0** [comment]
should render the correct inner blocks 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10163706125

**Comment by lanej0** [comment]
should render the correct inner blocks 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10173339039

**Comment by lanej0** [comment]
should render the Product Filters block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10180761108

**Comment by lanej0** [comment]
should render the Product Filters block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10196228537

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
