### ISSUE TITLE
Shipping costs are not correct

### ISSUE THREAD

**Issue by keeslamper** [woothemes/woocommerce#49449]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a customer go to the checkout shipping costs are much to expensive. When we go to shipping zones and look in the shipping rates for 'Flatrate shipping' we see there's a , instead of expected decimal . 

When we change , for . it fixes the problem. There was earlier in June 2024 the same bug. https://developer.woocommerce.com/2024/06/24/woocommerce-9-0-2-dot-release/ 

### Expected behavior

Normal shipping costs.

### Actual behavior

Wrong shipping costs.

### Steps to reproduce

Add product to cart en go to cart / checkout.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://bikeshoprenevdlaar.nl
Site address (URL): https://bikeshoprenevdlaar.nl
WC Version: 9.1.1
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.7.44-49-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.1
WC Database Prefix: wp_
Totale database grootte: 285.16MB
Database gegevens grootte: 188.50MB
Database index grootte: 96.66MB
wp_woocommerce_sessions: Data: 34.56MB + Index: 0.52MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 30.56MB + Index: 23.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.47MB + Index: 0.53MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.31MB + Index: 0.20MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 11.52MB + Index: 9.09MB + Engine InnoDB
wp_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hfcm_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_iwp_backup_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_iwp_processed_iterator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mainwp_stream: Data: 1.52MB + Index: 0.73MB + Engine InnoDB
wp_mainwp_stream_meta: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 9.48MB + Index: 0.47MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 54.58MB + Index: 34.11MB + Engine InnoDB
wp_posts: Data: 6.52MB + Index: 3.69MB + Engine InnoDB
wp_redirection_404: Data: 1.02MB + Index: 0.28MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_simple_history: Data: 1.42MB + Index: 0.25MB + Engine InnoDB
wp_simple_history_contexts: Data: 3.02MB + Index: 2.77MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
wp_terms: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp_term_taxonomy: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_usermeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.36MB + Index: 0.23MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 6.52MB + Index: 6.06MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.28MB + Index: 0.66MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_admin_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_image_overlays: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_point_labels: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 6.52MB + Index: 1.50MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.33MB + Index: 0.48MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.30MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 3088
custom_css: 1
iwp_log: 284
jetpack_migration: 2
nav_menu_item: 6
oembed_cache: 1
page: 11
post: 2
postman_sent_mail: 1
product: 2286
revision: 307
shop_order: 8539
shop_order_refund: 40
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Advanced Access Manager: door AAM  – 6.9.34
Classic Editor: door WordPress Contributors – 1.6.3
Code Snippets: door Code Snippets Pro – 3.6.5.1
Contact Form 7 Datepicker: door Aurel Canciu – 2.6.0
Contact Form 7: door Takayuki Miyoshi – 5.9.6
Disable Gutenberg: door Jeff Starr – 3.1.2
Yoast Duplicate Post: door Enrico Battocchi & Team Yoast – 4.5
Easy WP SMTP: door Easy WP SMTP – 2.3.1
Email Address Encoder: door Till Krüss – 1.0.23
Envato Market: door Envato – 2.0.11
GTranslate: door Translate AI Multilingual Solutions – 3.0.6
Header Footer Code Manager: door DraftPress – 1.1.38
iOS Images Fixer: door Bishoy A. – 1.3.0
WPBakery Page Builder: door Michael M - WPBakery.com – 7.6
Kadence WooCommerce Email Designer: door Kadence WP – 1.5.13
Kirki Customizer Framework: door Themeum – 5.1.0
Loco Translate: door Tim Whitlock – 2.6.10
MainWP Child Reports: door MainWP – 2.2
MainWP Child: door MainWP – 5.1.1
Max Mega Menu: door megamenu.com – 3.3.1
Mollie Payments for WooCommerce: door Mollie – 7.6.0
Really Simple CAPTCHA: door Takayuki Miyoshi – 2.3
Really Simple SSL: door Really Simple Plugins – 8.1.5
Redirection: door John Godley – 5.4.2
Slider Revolution: door ThemePunch – 6.2.1
Simple History: door Pär Thernström – 4.16.0
Themes Zone Feature Pack: door Themes Zone – 1.0.8
Widget Logic: door WPChef – 5.10.4
WooCommerce Advanced Notifications: door WooCommerce – 1.4.5 (update naar versie 1.4.7 is beschikbaar)
WooCommerce Legacy REST API: door WooCommerce – 1.0.4
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.8.4
WooCommerce: door Automattic – 9.1.1
Yoast SEO: door Team Yoast – 23.0
WP Go Maps (formerly WP Google Maps): door WP Go Maps (formerly WP Google Maps) – 9.0.40
WP Mail Logging: door WP Mail Logging Team – 1.12.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dagen
Level threshold: –
Log directory size: 2 MB

### WC Pages ###

Winkelbasis: #5 - /winkel/
Winkelwagen: #6 - /winkelmand/ -  Bevat de [woocommerce_cart] shortcode
Afrekenen: #7 - /afrekenen/ -  Bevat de [woocommerce_checkout] shortcode
Mijn account: #8 - /mijn-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Bikeway
Version: 1.0.11
Author URL: http://themes.zone
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een sub thema aan. Zie: Hoe maak je eensub thema

WooCommerce Support: ✔

### Templates ###

Overrides: bikeway/woocommerce/checkout/thankyou.php versie 3.2.0 is verouderd. De hoofdversie is 8.1.0
bikeway/woocommerce/content-product.php versie 3.0.0 is verouderd. De hoofdversie is 3.6.0
bikeway/woocommerce/content-widget-product.php versie 3.3.0 is verouderd. De hoofdversie is 3.5.5
bikeway/woocommerce/loop/loop-start.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-12 15:41:53 +02:00
Options: ✔
Notes: 209
Onboarding: completed

### Action Scheduler ###

Afgerond: 1.121
Oldest: 2024-06-11 13:58:04 +0200
Newest: 2024-07-12 11:18:00 +0200

Mislukt: 12
Oldest: 2023-02-15 20:03:58 +0100
Newest: 2024-05-27 09:29:35 +0200

In afwachting: 2
Oldest: 2024-07-12 15:41:39 +0200
Newest: 2024-07-12 20:12:07 +0200

### Status report information ###

Generated at: 2024-07-12 13:24:53 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Hello @keeslamper 👋

Thanks for reaching out. 

> When a customer go to the checkout shipping costs are much to expensive. When we go to shipping zones and look in the shipping rates for 'Flatrate shipping' we see there's a , instead of expected decimal .

> When we change , for . it fixes the problem. There was earlier in June 2024 the same bug. https://developer.woocommerce.com/2024/06/24/woocommerce-9-0-2-dot-release/

Can you share detailed steps of how to reproduce this issue, and potentially share screenshots as well? I'm asking, as I'm unable to reproduce this issue on my end:

## 12345,67

![Image](https://github.com/user-attachments/assets/deaf6278-3c64-45b3-b9ef-033238d19858)

## 12345.67

![Image](https://github.com/user-attachments/assets/417b8410-a0a8-466f-accf-71ca6ff18dfb)

**Comment by mikejolley** [comment]
I'm seeing the same results as @nielslange for this. If I enter `4,00` I get a `4.00` price on the frontend. This is expected:

> Thousand separators are not supported in flat rate shipping costs and may result in unintended outputs. For example, if your flat rate shipping costs $12,345.67, you should enter 12345.67 or 12345,67 as the price. 

While it doesn't matter which symbol is used, `.` is recommended since `,` can cause visual bugs elsewhere.

For that reason, I’m going to close this issue, but please do leave a comment if you have additional information that you think will help us reproduce the issue. We will re-open if we’re able to replicate.

Thanks again for your report!
