### ISSUE TITLE
[Flaky] templates/legacy-templates.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49459]
woocommerce//* slug is supported 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
woocommerce//* slug is supported 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
woocommerce//* slug is supported 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
woocommerce//* slug is supported 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
woocommerce//* slug is supported 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
woocommerce//* slug is supported 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
woocommerce//* slug is supported 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934487009

**Comment by lanej0** [comment]
woocommerce//* slug is supported 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
