### ISSUE TITLE
[Flaky] on-sale-badge/on-sale-badge-single-product-template.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49468]
should be rendered on the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
should be aligned to the left 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
should be aligned to the center 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
should be rendered on the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
should be not rendered when the product isn't on sale the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
should be aligned to the right by default 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
should be not rendered when the product isn't on sale the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should be rendered on the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should be aligned to the right by default 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should be not rendered when the product isn't on sale the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should be aligned to the center 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should be aligned to the left 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should be rendered on the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should be aligned to the center 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
should be rendered on the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
should be aligned to the left 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
should be aligned to the left 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should be aligned to the right by default 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should be rendered on the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should be not rendered when the product isn't on sale the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should be not rendered when the product isn't on sale the frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
should be aligned to the right by default 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10200119971

**Comment by lanej0** [comment]
should be aligned to the center 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10200119971

**Comment by lanej0** [comment]
should be rendered on the editor side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10200119971

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
