### ISSUE TITLE
[Flaky] product-gallery/product-gallery.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49469]
should have as first thumbnail, the same image that it is visible in the Large Image block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
should change the image when the user click on the previous or next button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
should change the image when the user click on a thumbnail image 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should change the image when the user click on a thumbnail image 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should persistently display the block when navigating back to the template without a page reload 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9940345457

**Comment by lanej0** [comment]
should persistently display the block when navigating back to the template without a page reload 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10004244400

**Comment by lanej0** [comment]
should persistently display the block when navigating back to the template without a page reload 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10056572286

**Comment by lanej0** [comment]
should reset to the first thumbnail when the pop-up is closed 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10144644947

**Comment by lanej0** [comment]
should change the image when the user click on a pager item 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10144644947

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
