### ISSUE TITLE
[Flaky] product-gallery/inner-blocks/product-gallery-pager/product-gallery-pager.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49460]
display pages as numbers when display mode is set to "Digits" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
correctly hides the block when display mode is set to "Off" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
correctly hides the block when display mode is set to "Off" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
Renders Product Gallery Pager block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
display pages as numbers when display mode is set to "Digits" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
correctly hides the block when display mode is set to "Off" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
Renders Product Gallery Pager block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
display pages as dot icons when display mode is set to "Dots" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
correctly hides the block when display mode is set to "Off" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
display pages as dot icons when display mode is set to "Dots" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
Renders Product Gallery Pager block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
display pages as numbers when display mode is set to "Digits" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
Renders Product Gallery Pager block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
correctly hides the block when display mode is set to "Off" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
display pages as dot icons when display mode is set to "Dots" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
correctly hides the block when display mode is set to "Off" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
display pages as dot icons when display mode is set to "Dots" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
correctly hides the block when display mode is set to "Off" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
display pages as dot icons when display mode is set to "Dots" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
correctly hides the block when display mode is set to "Off" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
Renders Product Gallery Pager block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
display pages as dot icons when display mode is set to "Dots" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
display pages as dot icons when display mode is set to "Dots" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968138417

**Comment by lanej0** [comment]
display pages as numbers when display mode is set to "Digits" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10144644947

**Comment by lanej0** [comment]
display pages as dot icons when display mode is set to "Dots" 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10144644947

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
