### ISSUE TITLE
[Flaky] product-gallery/inner-blocks/product-gallery-large-image/product-gallery-large-image.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49463]
should work on frontend when is enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10144644947

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
