### ISSUE TITLE
[Flaky] product-gallery/inner-blocks/product-gallery-large-image/product-gallery-large-image.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49465]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
Renders Product Gallery Large Image block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
should work on frontend when is enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
should not work on frontend when is disabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
Renders Product Gallery Large Image block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
should work on frontend when is enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
should not work on frontend when is disabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
Renders Product Gallery Large Image block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should work on frontend when is enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should not work on frontend when is disabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should not work on frontend when is disabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
Renders Product Gallery Large Image block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
should work on frontend when is enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
should not work on frontend when is disabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
Renders Product Gallery Large Image block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934487009

**Comment by lanej0** [comment]
should work on frontend when is enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934487009

**Comment by lanej0** [comment]
should work on frontend when is enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
Renders Product Gallery Large Image block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should not work on frontend when is disabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should work on frontend when is enabled 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
Renders Product Gallery Large Image block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
Renders Product Gallery Large Image block on the editor and frontend side 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by lanej0** [comment]
should be enabled by default 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by lanej0** [comment]
Renders correct image when selecting a product variation in the Add to Cart With Options block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10200119971

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
