### ISSUE TITLE
[Flaky] filter-blocks/attribute-filter.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49461]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922297667

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922297667

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by lanej0** [comment]
renders a dropdown list with the available attribute filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
renders a checkbox list with the available attribute filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
clear button is not shown on initial page load 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
clear button is not shown on initial page load 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
Renders checkboxes with associated product counts 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
Clicking a dropdown option should filter the displayed products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9988508130

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
renders a checkbox list with the available attribute filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
clear button is not shown on initial page load 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
Clicking a dropdown option should filter the displayed products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
Renders checkboxes with associated product counts 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
clear button is not shown on initial page load 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
renders a dropdown list with the available attribute filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10003364342

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10037196653

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10037196653

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10037196653

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10037196653

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10039137520

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10039137520

**Comment by lanej0** [comment]
renders a checkbox list with the available attribute filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10039137520

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10039137520

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10039137520

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10041131703

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10041131703

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10041131703

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10041131703

**Comment by lanej0** [comment]
renders a checkbox list with the available attribute filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10041131703

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10042785430

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10042785430

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10042785430

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10042785430

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10061958452

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10061958452

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10061958452

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10061958452

**Comment by lanej0** [comment]
clear button is not shown on initial page load 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
clear button is not shown on initial page load 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
renders a checkbox list with the available attribute filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
Renders checkboxes with associated product counts 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
Clicking a dropdown option should filter the displayed products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
renders a dropdown list with the available attribute filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10062712255

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10071068137

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10071068137

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10071068137

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10071068137

**Comment by lanej0** [comment]
clear button hides after deselecting all filters 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10071068137

**Comment by lanej0** [comment]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10071068137

**Comment by lanej0** [comment]
filters the list of products by selecting an attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10071068137

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10071068137

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
