### ISSUE TITLE
[Flaky] templates/single-product-template.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49467]
loads the Single Product template for a specific product 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
loads the Single Product template for a specific product 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
loads the Single Product template for a specific product 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
loads the Single Product template for a specific product 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
loads the Single Product template for a specific product 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
loads the Single Product template for a specific product 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
loads the Single Product template for a specific product 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
