### ISSUE TITLE
[Flaky] templates/product-search-results.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49466]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
loads the correct template in the Site Editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
