### ISSUE TITLE
[Flaky] page-content-wrapper/page-content-wrapper.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49464]
the content of the Cart page is correctly rendered in the Cart template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
the content of the Checkout page is correctly rendered in the Checkout template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908379565

**Comment by lanej0** [comment]
the content of the Cart page is correctly rendered in the Cart template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909337319

**Comment by lanej0** [comment]
the content of the Cart page is correctly rendered in the Cart template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
the content of the Checkout page is correctly rendered in the Checkout template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
the content of the Cart page is correctly rendered in the Cart template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
the content of the Checkout page is correctly rendered in the Checkout template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
the content of the Cart page is correctly rendered in the Cart template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
