### ISSUE TITLE
[Flaky] attributes-filter/attribute-filter.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49462]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908191234

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9908379565

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909689318

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909337319

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
should allow toggling the visibility of the filter button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9913523420

**Comment by lanej0** [comment]
should allow changing the display style 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
should allow changing the display style 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10095972622

**Comment by lanej0** [comment]
should allow changing the block's title 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10095972622

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10112641292

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10180761108

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
