### ISSUE TITLE
[Flaky] product-gallery/inner-blocks/product-gallery-thumbnails/product-gallery-thumbnails.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49475]
positions thumbnails to the bottom 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
hides thumbnails 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909081914

**Comment by lanej0** [comment]
hides thumbnails 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
positions thumbnails to the right 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
positions thumbnails to the left 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
hides thumbnails 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
renders as expected 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
renders as expected 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
hides thumbnails 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
positions thumbnails to the right 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
positions thumbnails to the bottom 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
hides thumbnails 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
renders as expected 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
positions thumbnails to the left 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
hides thumbnails 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
renders as expected 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
positions thumbnails to the right 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
hides thumbnails 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
positions thumbnails to the left 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
positions thumbnails to the left 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by lanej0** [comment]
renders as expected 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by lanej0** [comment]
positions thumbnails to the bottom 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
