### ISSUE TITLE
[Flaky] price-filter/price-filter.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49484]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9909337319

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10095972622

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10200119971

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
