### ISSUE TITLE
[Flaky] rating-filter/rating-filter.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49488]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9910882211

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911360475

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911479497

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
should allow changing the display style 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
should allow changing the block's title 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922203554

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922297667

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934487009

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934487009

**Comment by lanej0** [comment]
should show all products 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
should refresh the page only if the user clicks on button 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9966622549

**Comment by lanej0** [comment]
should show only products that match the filter 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968138417

**Comment by lanej0** [comment]
should allow changing the display style 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10095972622

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
