### ISSUE TITLE
[Flaky] templates/checkout-template.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49496]
Admin bar edit site link opens site editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
Template can be accessed from the page editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
Admin bar edit site link opens site editor 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
