### ISSUE TITLE
[Flaky] classic-template/classic-template.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49495]
is registered/unregistered when navigating from a WC template to a non-WC template and back 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
is registered/unregistered when navigating from a non-WC template to a WC template and back 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
is registered/unregistered when navigating from a non-WC template to a WC template and back 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
updates block title when navigating between WC templates 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by lanej0** [comment]
updates block title when navigating between WC templates 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by lanej0** [comment]
is registered/unregistered when navigating from a WC template to a non-WC template and back 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934845900

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
