### ISSUE TITLE
[Flaky] templates/single-product-template.block_theme_with_templates.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49490]
loads the theme template for a specific product using the product slug and it can be customized 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911020250

**Comment by lanej0** [comment]
loads the theme template for a specific product using the product slug and it can be customized 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9911171586

**Comment by lanej0** [comment]
loads the theme template for a specific product using the product slug and it can be customized 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9934552697

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
