### ISSUE TITLE
[Flaky] all-reviews/all-reviews.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49506]
block can be inserted and it sorts reviews by most recent by default 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
can sort by lowest rating in the frontend 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
block can be inserted and it sorts reviews by most recent by default 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10095972622

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
