### ISSUE TITLE
[Flaky] product-button/product-button.classic_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49508]
should add product to the cart 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9914914132

**Comment by lanej0** [comment]
should add product to the cart 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
should be visible 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
