### ISSUE TITLE
[Flaky] filter-blocks/price-filter.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49515]
clear button appears after a filter is applied 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
filters are cleared after clear button is clicked 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9922365994

**Comment by lanej0** [comment]
Changes in the price input field triggers price slider updates 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
