### ISSUE TITLE
Product Collection: manual sorting option 

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#49529]
Background:

Increase the sorting options for products

Goal:

Provide the option to sort products manually (follow the Products menu order).

Current | Expected
-- | --
<img width="236" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/1fa682c7-4cfc-4813-83fc-45658b87a14c"> | <img width="246" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/6de68c78-9667-40b6-a961-87d98fc2c88e">

**Comment by asafm7** [comment]
That's great, @kmanijak!

The random option would be great.

To clarify, will these options be available in the back- or front-end, or both?

**Comment by kmanijak** [comment]
I'm glad you're glad @asafm7! :D 

> The random option would be great.

There's an issue for random option as well (https://github.com/woocommerce/woocommerce/issues/49530) but it's not our priority atm.

> To clarify, will these options be available in the back- or front-end, or both?

This option will be available for a merchant to set in the Editor. There's "Catalog Sorting" block for the shoppers (frontend) but we won't touch it in scope of this issue.

**Comment by kmanijak** [comment]
> The random option would be great.
> > There's an issue for random option as well (https://github.com/woocommerce/woocommerce/issues/49530) but it's not our priority atm.

@asafm7, good news, @imanish003 implemented a random order option! It'll be available in WooCommerce 9.5 🙌

**Comment by asafm7** [comment]
That's great, @kmanijak. Thanks for the update!
