### ISSUE TITLE
Update Database button is broken

### ISSUE THREAD

**Issue by therealgilles** [woothemes/woocommerce#49523]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Clicking the `Update Database` button results in an error:
```
404 <site-rest-api-endpoint>/wc-analytics/admin/notes/126/action/25038?_locale=user
```

### Expected behavior

Clicking `Update Database` starts updating the database and succeeds.

### Actual behavior

Clicking the `Update Database` button results in an error.

```
{"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}
```

### Steps to reproduce

1. Click the `Update Database` button.
2. Wait for the error toast to appear.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://...
Site address (URL): https://...
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.20
PHP Post Max Size: 16 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-0ubuntu0.22.04.1-log
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.2
WC Database Prefix: wp_

### Post Type Counts ###

_pods_field: 22
_pods_group: 11
_pods_pod: 9
action_monitor: 64
attachment: 966
curriculum-topic: 211
customize_changeset: 2
document: 40
flamingo_inbound: 344
internal-document: 87
itsec-dash-card: 4
itsec-dashboard: 1
jetpack_migration: 2
nav_menu_item: 74
oembed_cache: 1
page: 46
popup: 1
popup_theme: 7
pos_custom_product: 1
pos_temp_register_or: 5
post: 205
product: 373
product_config: 4
product_variation: 446
revision: 2178
shop_coupon: 152
shop_order: 13075
shop_order_placehold: 558
shop_order_refund: 256
staff: 98
tablepress_table: 5
team_member: 1
tribe_event_series: 138
tribe_events: 292
tribe_filters: 2
tribe_organizer: 39
tribe_venue: 7
tribe-ea-record: 2
um_directory: 1
um_form: 3
um_role: 2
user_request: 1
vc_grid_item: 3
vc_settings_preset: 3
wccpf: 1
wll_records: 2967
wo_client: 3
wp-rest-api-log: 807
wpcf7_contact_form: 4
wpex_card: 1
wpex_font: 1
wpex_templates: 25
wpex_widget_area: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (92) ###

Add Shortcodes Actions And Filters: by Michael Simpson – 2.10
Admin Columns Pro: by AdminColumns.com – 6.4.10
Admin Menu Editor: by Janis Elsts – 1.12.3
Solid Security Basic: by SolidWP – 9.3.3
Bootstrap Modals: by Neil Gee – 1.3.2
Five Star Business Profile and Schema: by Five Star Plugins – 2.3.8
Classic Editor: by WordPress Contributors – 1.6.3
Cloudflare: by Cloudflare
Inc. – 4.12.7

Honeypot for Contact Form 7: by WPExperts – 2.1.3
Contact Form DB: by Michael Simpson – 2.10.29
Contact Form 7: by Takayuki Miyoshi – 5.9.6
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.17.1
Custom Content Shortcode: by Eliot Akira – 4.0.2
Debug Bar: by wordpressdotorg – 1.1.6
Delete Me: by Clinton Caldwell – 3.2
Disable Cart Fragments: by Optimocha – 2.3
Disable Comments: by WPDeveloper – 2.4.6
Disable Elements for WPBakery Page Builder: by WPExplorer – 1.1
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.6
Disable Flamingo Addressbook: by Christian Sabo – 1.0
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Email Address Encoder: by Till Krüss – 1.0.23
Email Log: by Sudar – 2.4.9
Email Obfuscate Shortcode: by khromov – 2.0
Enable Media Replace: by ShortPixel – 4.1.5
Envato Market: by Envato – 2.0.11
The Events Calendar Pro: by The Events Calendar – 6.5.0
EWWW Image Optimizer: by Exactly WWW – 7.7.0
Flamingo: by Takayuki Miyoshi – 2.5
XML Sitemap Generator for Google: by Auctollo – 4.1.21
Hello Dolly: by Matt Mullenweg – 1.7.2
Hikari Category Permalink: by Hikari – 1.00.08
WPBakery Page Builder: by Michael M - WPBakery.com – 7.7.2
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.13
Links in Captions: by Katz Web Services
Inc. – 1.2

LiteSpeed Cache: by LiteSpeed Technologies – 6.2.0.1
Log cleaner for Solid Security: by Rocket Apps – 1.4.1
Login With Ajax: by Pixelite – 4.3
Logout Redirect: by Arefly – 1.0.2
Mailgun: by Mailgun – 1.9.9
Obfuscate Email: by Scott Reilly – 3.8.1
Passwordless Login: by Cozmoslabs
sareiodata – 1.1.3

Pods - Custom Content Types and Fields: by Pods Framework Team – 3.2.2
PublishPress Future: by PublishPress – 3.4.1
Post Types Order: by Nsp Code – 2.2.3
QL Events: by kidunot89 – 0.0.1
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.51
Redirection: by John Godley – 5.4.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Relevanssi: by Mikko Saari – 4.22.2
Reveal IDs: by Oliver Schlöbe – 1.6.1
Rollbar: by Rollbar – 2.7.1
Shortcode in Menus: by Gagan Deep Singh – 3.5.1
Simple Tooltips: by Justin Saad – 2.1.4
TablePress: by Tobias Bäthge – 2.3.2
Tabsy for Visual Composer: by phpbits – 1.0
WP Tabsy: by phpbits – 1.4
Link/Obfuscate Telephone Numbers: by Grandadevans – 1.4.1
Templatera: by WPBakery – 2.1.0
Text Expander: by Alexander Zigelski – 0.3
The Events Calendar: by The Events Calendar – 6.5.1.5
Total Theme Core: by WPExplorer – 1.8.7
The Events Calendar Extension: Events Control: by Modern Tribe
Inc. – 1.3.0

The Events Calendar Extension: Events Happening Now: by Modern Tribe
Inc. – 1.0.0

The Events Calendar Extension: Open external links in a new tab.: by The Events Calendar – 1.0.1
The Events Calendar Extension: Don't Hide Recurring Instances on Month and Week View: by Modern Tribe
Inc. – 1.0.0

UPME NoCaptcha reCaptcha: by Themefluent – 1.1
User Profiles Made Easy: by ThemeFluent – 2.3.09
User Switching: by John Blackbourn & contributors – 1.7.3
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.4.6
When Last Login: by Yoohoo Plugins – 1.2.2
Advanced Order Export For WooCommerce: by AlgolPlus – 3.5.3
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.15
WooCommerce Colors: by WooThemes – 1.0.7
WooCommerce Stripe Gateway: by WooCommerce – 8.5.1
WooCommerce One Page Checkout: by Automattic – 2.8.5
WooCommerce Product Details Customiser: by jameskoster – 0.2.0
WooCommerce Smart Coupons: by StoreApps – 9.5.0
WooCommerce: by Automattic – 9.1.2
WooCommerce Donations Plugin: by Albdesign – 2.0.1
WP Block Admin: by Callum Macdonald – 0.2.3.0
Contact Form 7 Email Spam Blocker: by Hardik Kalathiya – 1.0.0
WP Crontrol: by John Blackbourn – 1.16.3
WP First Letter Avatar: by Dev49.net – 2.2.8
WPGraphQL CORS: by  – 2.0
WPGraphQL WooCommerce (WooGraphQL): by kidunot89 – 0.20.0
WPGraphQL: by WPGraphQL – 1.27.2
WP OAuth Server - Pro: by WP OAuth Server – 4.3.2
REST API Log: by Pete Nelson – 1.7.0
WP Session Manager: by Eric Mann – 4.2.0
WPFront User Role Editor: by Syam Mohan – 4.1.1

### Inactive Plugins (20) ###

Advanced Post Manager: by The Events Calendar – 4.5.4
Better Search Replace: by WP Engine – 1.4.7
Bulk Delete: by Sudar – 6.0.2
Combined Query: by birgire – 1.2.2
Convert Post Types: by Stephanie Leary – 1.4
Duplicate Menu: by Jonathan Christopher – 0.2.2
Duplicator: by Duplicator – 1.5.10
Git Updater: by Andy Fragen – 11.1.9
Image Widget: by The Events Calendar – 4.4.9
Media Deduper: by Cornershop Creative – 1.5.7
No Clear Password in Email: by Paul Newman (modified by ...) – 1.00
Post Tags and Categories for Pages: by curtismchale – 1.4.1
Post Type Switcher: by Triple J Software
Inc. – 3.3.1

Query Monitor: by John Blackbourn – 3.16.3
UpdraftCentral Dashboard: by David Anderson + Team Updraft – 0.8.30
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.4

WP Activity Log: by Melapress – 5.1.0
WP Bulk Delete: by Xylus Themes – 1.2.9
WP Gatsby: by GatsbyJS
Jason Bahl
Tyler Barnes – 2.3.3

WPGraphQL JWT Authentication: by WPGraphQL
Jason Bahl – 0.4.1

### Dropin Plugins () ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 22 MB

### WC Pages ###

Shop base: #218 - /shop/
Cart: #219 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #221 - /my-account/
Terms and conditions: #11138 - /store-terms-conditions/

### Theme ###

Name: ...
Version: 2.2.2
Author URL: https://...
Child Theme: ✔
Parent Theme Name: ...
Parent Theme Version: 5.17
Parent Theme Author URL: https://www.wpexplorer.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: Total/woocommerce/archive-product.php
theme/woocommerce/checkout/form-checkout.php
Total/woocommerce/loop/loop-start.php
Total/woocommerce/loop/orderby.php
Total/woocommerce/loop/pagination.php
theme/woocommerce/myaccount/form-edit-account.php
theme/woocommerce/myaccount/my-orders.php
theme/woocommerce/single-product/add-to-cart/variable.php
theme/woocommerce/single-product/meta.php
Total/woocommerce/single-product/rating.php
Total/woocommerce/single-product/tabs/tabs.php
theme/woocommerce/single-product/title.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-15 03:49:58 -07:00
Options: ✔
Notes: 23
Onboarding: completed

### Action Scheduler ###

Complete: 1,139
Oldest: 2024-06-13 18:04:08 -0700
Newest: 2024-07-14 15:54:09 -0700

Failed: 20
Oldest: 2021-06-20 12:27:00 -0700
Newest: 2024-04-21 12:19:09 -0700

Pending: 2
Oldest: 2024-07-15 00:36:08 -0700
Newest: 2024-07-20 03:08:08 -0700

### Smart Coupons related settings ###

⠀* Number of coupons to show: 5
⠀* Number of characters in auto-generated coupon code: 
⠀* Valid order status for auto-generating coupon: Processing | Completed
⠀* Include tax in the amount of the generated gift card: ❌ No
⠀* Deduct credit/gift before doing tax calculations: ❌ No
⠀* Gift Card discount is inclusive of tax: ❌ No
⠀* Automatic deletion: ❌ No
⠀* Coupon emails: ✔ Yes
⠀* Printing coupons: ❌ No
⠀* Sell gift cards at less price?: ❌ No
⠀* Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: ✔ Yes
⠀* Renewal orders should not generate coupons even when they include a product that issues coupons: ❌ No
⠀* Allow sending of coupons to others: ✔ Yes
⠀* Allow schedule sending of coupons?: ✔ Yes
⠀* Combine emails: ✔ Yes
⠀* Auto generated coupon email: ✔ Yes
⠀* Combined auto generated coupons email: ✔ Yes
⠀* Acknowledgement email: ✔ Yes
⠀* Enable taxes: ❌ No
⠀* Prices entered with tax: ❌ No
⠀* Display prices in the shop: ❌ Excl
⠀* Display prices during cart and checkout: ❌ Excl
⠀* Rounding: ❌ No
⠀* Display tax totals: Itemized
⠀* Enable the use of coupon codes: ✔ Yes
⠀* Calculate coupon discounts sequentially: ✔ Yes
⠀* Account endpoints > Coupons: wc-smart-coupons
⠀* Block-enabled Cart: ❌ No
⠀* Block-enabled Checkout: ❌ No
⠀* WooCommerce Account Connected: ✔ Yes

### Status report information ###

Generated at: 2024-07-14 15:57:03 -07:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).

@therealgilles Thanks for creating the issue. We need to be able to reproduce issues in our development installs on a default theme with only WooCommerce active. Can you confirm that this issue occurs with your plugins disabled and a default theme?

Also, what version of WooCommerce did you update from?
