### ISSUE TITLE
Orders data is truncated on the orders list page when viewed on mobile

### ISSUE THREAD

**Issue by rajwpdev117** [woothemes/woocommerce#49522]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you access the order lists page on your mobile device, regardless of the browser, you will notice that most of the order data, like the order number and name, aren’t visible. Deselecting other available columns also didn’t make any difference.
 
https://github.com/user-attachments/assets/fd1744cd-4841-495a-a920-e58f17af27e1

Reported on the thread here: https://wordpress.org/support/topic/admin-list-orders-at-cell-phone/
Ticket: 8478804 - zen

### Expected behavior

When you access through the mobile browser, you should be able to see the order details, such as order number, and name on mobile view.

### Actual behavior

As explained in the bug description.

### Steps to reproduce

Navigate to WooCommerce → Orders page from a Mobile Browser.

### WordPress Environment

WooCommerce version: 9.1.2
WordPress version: 6.5.5
Theme: Storefront
PHP version:: 8.2.21

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by cardehngeh** [comment]
8475887-zen

**Comment by cardehngeh** [comment]
8477422-zen

**Comment by carolframen** [comment]
8494130-zen
