### ISSUE TITLE
Checkout page Uncaught TypeError: e.computedStyleMap is not a function

### ISSUE THREAD

**Issue by valentabc** [woothemes/woocommerce#49525]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The checkout page outputs a console error:
Uncaught TypeError: e.computedStyleMap is not a function

I have tried with a clean WordPress install, no other plugins, default theme, default settings.

### Expected behavior

The checkout works without any JavaScript errors.

### Actual behavior

Console errors on the checkout page:
`Uncaught TypeError: e.computedStyleMap is not a function
    n https://wptesting.tripstore.eu/wp-content/plugins/woocommerce/assets/client/blocks/checkout-blocks/totals-frontend.js?ver=343f491eec258cc39e07:1
    n https://wptesting.tripstore.eu/wp-content/plugins/woocommerce/assets/client/blocks/checkout-blocks/totals-frontend.js?ver=343f491eec258cc39e07:1
    ResizeObserverCallback* https://wptesting.tripstore.eu/wp-content/plugins/woocommerce/assets/client/blocks/checkout-blocks/totals-frontend.js?ver=343f491eec258cc39e07:1
    Ur https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    El https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    fl https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Nn https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    ul https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    ul https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Pl https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Ll https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    promise callback*n/qr/< https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    qr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Kr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Yr https://wptesting.tripstore.eu/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10`

### Steps to reproduce

1. Install fresh WooCommerce WordPress install
2. Add one test product
3. Go to checkout

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sk_SK
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.19
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 7000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.5.9-MariaDB-1:10.5.9+maria~focal-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 2
avia_framework_post: 7
page: 8
post: 2
product: 1
revision: 2
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Media Library Assistant: David Lingren – 3.18
ShortPixel Image Optimizer: ShortPixel - Convert WebP/AVIF & Optimize Images – 5.6.2
WooCommerce: Automattic – 9.1.2
Perfect Images (Optimize, Rebuild, Replace, Thumbnails, Retina): Jordy Meow – 6.6.2
WPS Hide Login: WPServeur
NicolasKulka
wpformation – 1.9.16.7


### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dní
Level threshold: –
Log directory size: 269 B

### WC Pages ###

Slug pre obchod: #21 - /index.php/obchod/
Košík: #22 - /index.php/kosik/ -  Contains the woocommerce/cart block
Pokladňa: #23 - /index.php/kontrola-objednavky/ -  Contains the woocommerce/checkout block
Môj účet: #24 - /index.php/moj-ucet/
Všeobecné obchodné podmienky: ❌ Stránka nenastavená

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – Ak upravujete WooCommerce na rodičovskej téme
ktorú ste nevytvorili
odporúčame použiť odvodenú tému. Prečítajte si návod Ako vytvoriť odvodenú tému.

WooCommerce Support: ❌ Nie je zaručená

### Templates ###

Overrides: /data/2/0/200fee51-e2ae-4a68-a673-b4895ad1afaf/tripstore.eu/sub/wptesting/wp-content/plugins/woocommerce/templates/block-notices/error.php
/data/2/0/200fee51-e2ae-4a68-a673-b4895ad1afaf/tripstore.eu/sub/wptesting/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/data/2/0/200fee51-e2ae-4a68-a673-b4895ad1afaf/tripstore.eu/sub/wptesting/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-16 08:34:53 +02:00
Options: ✔
Notes: 57
Onboarding: completed

### Action Scheduler ###

Označiť ako vybavenú: 5
Oldest: 2024-07-15 10:35:06 +0200
Newest: 2024-07-15 10:40:08 +0200

Zlyhal: 1
Oldest: 2024-07-15 10:37:23 +0200
Newest: 2024-07-15 10:37:23 +0200

Vybavuje sa: 1
Oldest: 2024-07-16 10:35:06 +0200
Newest: 2024-07-16 10:35:06 +0200


### Status report information ###

Generated at: 2024-07-15 10:44:45 +02:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
This seems to be a browser issue, which browser are you running?

**Comment by valentabc** [comment]
Hello, this is Firefox 128 on macOS 14.5

**Comment by wavvves** [comment]
Thank you for reporting this @valentabc 
According to Can I Use, [computedStyleMap is not supported on Firefox](https://caniuse.com/mdn-api_element_computedstylemap).
This issue will be added to the backlog for addressing 👍
