### ISSUE TITLE
Product Collection: random sorting option

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#49530]
Background:

Increase the sorting options for products

Goal:

Provide the option to display products in random order

Current | Expected
-- | --
<img width="236" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/1fa682c7-4cfc-4813-83fc-45658b87a14c"> | <img width="246" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/6de68c78-9667-40b6-a961-87d98fc2c88e">

**Comment by scrobbleme** [comment]
Lol, somehow cynic, that Woocommerce will add "random", but there seems no way in it for [Gutenberg "core query loops"](https://github.com/WordPress/gutenberg/issues/40481 )... 

The shops I maintain have more products than any other content.
