### ISSUE TITLE
Explore building in a distinct job and re-using build artifact in the test jobs

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#49546]
Explore the idea of running the build step only once in a distinct prerequisite job, upload the artifact and the following test jobs would download and use this artifact.
Check if this makes sense and it's worth it, given that the build step is optimised for each type of test (unit vs api vs e2e).

**Comment by juliaamosova** [comment]
See this Slack thread for the discussion and next steps: p1726674533813879-slack-C07JJG089M0.

**Comment by kalessil** [comment]
I think we can close this issue after revisiting the issue details and the latest state of CI jobs.

In [.github/actions/setup-woocommerce-monorepo/action.yml](https://github.com/woocommerce/woocommerce/blob/trunk/.github/actions/setup-woocommerce-monorepo/action.yml#L103) we have `Cache Build Output` step which caches build steps output. 

It is very close to our original intention of exploring this issue, but it also does not block other CI jobs—therefore, it is a better fit for keeping CI times lower.
