### ISSUE TITLE
Checkout: Regression with default country behaviour on guest checkout

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#49553]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you have this setting:

![Screenshot 2024-07-15 at 13 39 51](https://github.com/user-attachments/assets/9aecfa37-665f-4e25-84be-d910a34cc300)

And then do a guest checkout, the country field used to default to a blank value. This meant the customer had to select their country.

After https://github.com/woocommerce/woocommerce/pull/48180 we have a select box. This does not have an empty option, so it defaults to Afganistan on entry instead.

### Expected behavior

It should default to an empty value, or a more sensible default such as store country.

### Actual behavior

Afganistan is selected as your country.

### Steps to reproduce

1. Set default customer address to "no default location"
2. Go to guest checkout (logged out)
3. Check the value of the country field

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ralucaStan** [comment]
@samueljseay for awarness

**Comment by mikejolley** [comment]
This was fixed in https://github.com/woocommerce/woocommerce/pull/49616

**Comment by samueljseay** [comment]
Whoops looks like I didn't link the issue thanks for spotting this. 🙇
