### ISSUE TITLE
Missing global $product within injected block loop hooks

### ISSUE THREAD

**Issue by dennisnissle** [woothemes/woocommerce#49598]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using an FSE theme Woo tries to inject hooks used within legacy templates via [ArchiveProductTemplatesCompatibility](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/Templates/ArchiveProductTemplatesCompatibility.php#L197). Hooks attached to the block `core/post-title`, e.g. `woocommerce_before_shop_loop_item_title` will be called/hooked before the global `$product` object has been set up. This leads to fatal errors with custom logic that works just fine in non-FSE themes. Other hooks, like `woocommerce_before_shop_loop_item` work just fine as those are attached to `product-loop-item`.

### Expected behavior

Set up `$product` object before injecting hooks.

### Actual behavior

`$product` is null.

### Steps to reproduce

Add the following snippet to your FSE theme's functions.php

```php
add_action( 'woocommerce_after_shop_loop_item_title', function() {
   global $product;

   var_dump( $product->get_id() );
}, 10 );
```

### WordPress Environment

Latest WP, WooCommerce.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment]
Hi @dennisnissle,

Thanks for your report, I can reproduce the issue. We found the root cause of the issue and will work on a fix soon.
