### ISSUE TITLE
[Enhancement]: WooCommerce Product blocks do not display native product stock status

### ISSUE THREAD

**Issue by joshlapin** [woothemes/woocommerce#49612]
### Describe the solution you'd like

When you have a native Category Page in WooCommerce the products that are out of stock will receive that indication across the product image. For reference, this is how that looks on this page of our website:

[Copper Creek 22 ARC](https://coppercreekcartridgeco.com/product-category/ammunition/22arc/)

[Screenshot of Native Behavior](https://i.sstatic.net/CUAxEYkr.png)

I have created a custom page to use as a Category Landing Page. I used Woo’s native block editor to build this page, Using a mix of specific product or tags to create the groups I’d Like. Here is how that looks.

[Custom 22 ARC Category Page](https://coppercreekcartridgeco.com/22-arc/)

Screenshot of those same products, which do not show the out of stock behavior. [Products from WooCommerce blocks](https://i.sstatic.net/JE0ytW2C.png).

Is there a way to show the stock status of these products across the product image? I am aware that I can hide out of stock products, that is not what I am trying to achieve.

I have searched and googled high and low and have found others facing this dilemma but have not seen any solutions or workarounds.

### Describe alternatives you've considered

I have looked at every plugin for enhanced blocks. Not a single one seems to offer any solution

**Comment by OmarFPG** [comment]
Thank you so much for submitting the report here. I wanted to add that this also depends on how your theme displays things (the out of stock image on top of your products is part of your theme).

For instance, I just tried this with Storefront and used the products by tag just the same as you did, and I intentionally set a product out of stock, I noticed then in my case the button changed from “Add to cart” to “Read more” for single products (looking at your [video](https://share.vidyard.com/watch/QutN5JAX9fUs5J8tjYZH8W) in detail I can see this is also the case).

For variable products I still see the “Select options” text on the button, which is misleading as they’re all out of stock. This should indeed be fixed. I just wanted to share some more context about this enhancement request for our devs.

8474357-zen

**Comment by dinhtungdu** [comment]
Hi there,

Thanks for the report! I'd recommend using the Product Collection block to replace the Product with the Tag and Handpicked Products block for your case. Product Collection provides a lot of filters enabling you to control the products being displayed, it has Tag and Handpicked filters, which should serve your needs. The Product Collection blocks also allows you to customize the component of the loop item, for example, you can add the stock status indicator to your loop. Please try and let us know if it works for you.



![Image](https://github.com/user-attachments/assets/32a82461-0335-4c4c-91ab-0e57d5f1a7dc)

**Comment by gigitux** [comment]
@joshlapin I’m going to close this. If/when you have additional details, you can still add them to this issue! Thanks!
