### ISSUE TITLE
Twenty Twenty-Four child Theme with Google Font Alegreya causes PHP Warning

### ISSUE THREAD

**Issue by FifthPress** [woothemes/woocommerce#49618]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PHP Warning:  Undefined array key “name” in /home/hh/domains/fifthpress.org/public_html/style/wp-content/plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php on line 188

(note I wrote hh instead of some private hosting name)

The error is printed on my log file located in /public_html/wp-content/debug.log

If I go to /home/hh/domains/fifthpress.org/public_html/style/wp-content/plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php line 188 is
if ( $font['name'] === $font_to_add['name'] ) {
When I change it to 
if ( isset($font['name']) && $font['name']  === $font_to_add['name'] ) {
The error goes away.

From debuging I can see that the $font array for the Alegreya font has no "name" key in it, the code assumes that there will be such key but it does not exist. Note the font was added with WP official Create Block Theme plugin's Add Google Font option and not manually, see more info in steps to reproduce.

Please also note the bug reported by us here https://wordpress.org/support/topic/twenty-twenty-four-child-theme-with-google-font-alegreya-causes-php-warning/#post-17888527 another user reported the same error.

### Expected behavior

no PHP warning showing up in my log file from WooCommerce

### Actual behavior

no visible errors on the site, but this warning shows that the WooCommerce code breaks.

### Steps to reproduce

with active Plugins: Create Block Theme (by WordPress.org), WooCommerce and WooCommerce.com Update Manager.
And a fresh install of Theme Twenty Twenty-Four, please follow these steps:
1. Appearance-> Create Block Theme -> Create child of Twenty Twenty-Four-> Theme Name “Twenty-Four Child”-> Generate-> zip of Twenty-Four Child will be downloaded
2. Appearance-> Theme-> Add New Theme-> Upload Theme-> choose the zip of Twenty-Four Child and upload-> Activate
3. Appearance-> Manage Theme Fonts-> Add Google Font-> Alegreya-> Select the font variants you want to include:-> Select all-> Add Google Fonts to your theme
4. Load the website as a user, click on any link on the website to go to another page
5. reload the log file and see the error in the log file

With my current data base and staging site this will result in the above mentioned error. Alegreya SC font will produce the same bug.
This bug will not reproduce with the Twenty Twenty-Four parent Theme, only with a child of it, produced with WordPress’s official Create Block Theme plugin.

### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 360
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.11.8-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1292
content_block: 5
custom_css: 2
customize_changeset: 49
flamingo_contact: 49
flamingo_inbound: 2
nav_menu_item: 207
page: 42
polylang_mo: 3
post: 134
product: 8
revision: 2786
rl_gallery: 1
shop_coupon: 57903
shop_order: 4
tb_layout: 7
tb_sidebar: 13
wcs_ruleset: 1
wp_block: 46
wp_global_styles: 4
wp_navigation: 25
wp_template: 65
wp_template_part: 34
wpcf7_contact_form: 4
wpdiscuz_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Create Block Theme: by WordPress.org – 1.13.8
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce: by Automattic – 9.1.2

### Inactive Plugins (29) ###

Advanced Database Cleaner PRO: by Younes JFR. – 3.2.9
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Blocks CSS: CSS Editor for Gutenberg Blocks: by ThemeIsle – 2.6.12
Classic Editor: by WordPress Contributors – 1.6.3
Code Snippets: by Code Snippets Pro – 3.6.5.1
Conditional Shipping for WooCommerce: by Lauri Karisola / WP Trio – 3.2.0
Contact Form 7: by Takayuki Miyoshi – 5.9.6
Discount Rules Core: by Flycart – 2.6.4
eForm - WordPress Form Builder: by WPQuark – 4.17.0
Flamingo: by Takayuki Miyoshi – 2.5
Hide Related Video Youtube: by Trần Hoàng Quốc. – 1.0
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.26.11
LiteSpeed Cache: by LiteSpeed Technologies – 6.2.0.1
Mailchimp for WooCommerce: by Mailchimp – 4.1
Portfolios: by Theme Blvd – 1.1.6
Responsive Lightbox & Gallery: by dFactory – 2.4.7
Sequential Order Numbers for WooCommerce: by WebToffee – 1.6.3
Theme Blvd Importer: by Theme Blvd – 1.0.4
Theme Blvd Layout Builder: by Theme Blvd – 2.3.6
Theme Blvd Shortcodes: by Theme Blvd – 1.6.8
Theme Blvd Widget Areas: by Theme Blvd – 1.3.0
Theme Blvd Widget Pack: by Theme Blvd – 1.0.6
The Simplest Favicon: by EPIPE Communications – 1.1
WooCommerce PayPal Payments: by WooCommerce – 2.8.1
WP All Export Pro: by Soflyy – 1.8.6
WP Cloud Plugins - Google Drive (Use-your-Drive): by WP Cloud Plugins – 2.13.2
WPML Multilingual CMS: by OnTheGoSystems – 4.6.11
WPML String Translation: by OnTheGoSystems – 3.2.12
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.16.7

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.18.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 29 KB

### WC Pages ###

Shop base: #4548 - /shop/
Cart: #4549 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #4550 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #4551 - /my-account/
Terms and conditions: #4889 - /terms-and-conditions/

### Theme ###

Name: Twenty-Four Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Twenty Twenty-Four
Parent Theme Version: 1.1
Parent Theme Author URL: https://wordpress.org
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/u236960822/domains/fifthpress.org/public_html/style/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/u236960822/domains/fifthpress.org/public_html/style/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/u236960822/domains/fifthpress.org/public_html/style/wp-content/plugins/woocommerce/templates/block-notices/success.php
twentyfourchild/parts/checkout-header.html
twentyfourchild/parts/mini-cart.html
twentyfourchild/parts/product-filters-overlay.html
twentyfourchild/templates/archive-product.html
twentyfourchild/templates/coming-soon.html
twentyfourchild/templates/order-confirmation.html
twentyfourchild/templates/page-cart.html
twentyfourchild/templates/page-checkout.html
twentyfourchild/templates/product-search-results.html
twentyfourchild/templates/single-product.html
twentyfourchild/templates/taxonomy-product_attribute.html
twentyfourchild/templates/taxonomy-product_cat.html
twentyfourchild/templates/taxonomy-product_tag.html

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-14 22:44:38 -07:00
Options: ✔
Notes: 14
Onboarding: completed

### Action Scheduler ###

Complete: 14,807
Oldest: 2024-05-16 10:54:04 -0700
Newest: 2024-07-14 01:41:33 -0700

Failed: 18
Oldest: 2023-11-04 21:49:16 -0700
Newest: 2024-03-23 04:45:06 -0700

Pending: 1
Oldest: 2024-07-14 21:20:27 -0700
Newest: 2024-07-14 21:20:27 -0700

### Status report information ###

Generated at: 2024-07-14 01:47:42 -07:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rosa2** [comment]
Hello and thanks for this great theme!!!!
I had this morning the same warning after installing [Custom Fonts](https://wordpress.org/plugins/custom-fonts/) and enabling one. The plugin adds in theme.json the font. It has not the name key, so Woocommerce is not happy. I go to report there.
I put the code here:

```

					"fontFamily": "Font Awesome 5 Free",
					"slug": "font-awesome-5-free",
					"fontFace": [
						{
							"fontFamily": "Font Awesome 5 Free",
							"fontStretch": "",
							"fontStyle": "normal",
							"fontWeight": "400",
							"src": [
								"http://test.devel/wp-content/uploads/2024/07/fa-regular-400.woff2"
							]
						},
						{
							"fontFamily": "Font Awesome 5 Free",
							"fontStretch": "",
							"fontStyle": "normal",
							"fontWeight": "900",
							"src": [
								"http://test.devel/wp-content/uploads/2024/07/fa-solid-900.woff2"
							]
						}
					],
					"isBcf": true
				}
```
And adding the name
```

{
					"fontFamily": "Font Awesome 5 Free",
					"slug": "font-awesome-5-free",
					"name": "font awesome",
					"fontFace": [
						{
							"fontFamily": "Font Awesome 5 Free",
							"fontStretch": "",
							"fontStyle": "normal",
							"fontWeight": "400",
							"src": [
								"http://test.devel/wp-content/uploads/2024/07/fa-regular-400.woff2"
							]
						},
						{
							"fontFamily": "Font Awesome 5 Free",
							"fontStretch": "",
							"fontStyle": "normal",
							"fontWeight": "900",
							"src": [
								"http://test.devel/wp-content/uploads/2024/07/fa-solid-900.woff2"
							]
						}
					],
					"isBcf": true
				}
```

I go to report to the plugin, thanks a lot again :) I really enjoy a lot your theme with a child theme.

**Comment by philbraun** [comment]
Can confirm: adding the name key to typography > fontFamilies makes the WooCommerce error go away, and the 2 WooCommerce fonts are added to /uploads/fonts and to the site editor.

**Comment by FifthPress** [comment]
Confirming that rosa2's suggestion to manually add the name to the theme.json file is a good workaround for now. Better than editing the WooCommerce core code of ComingSoonRequestHandler.php.

**Comment by chihsuan** [comment]
Thanks for reporting this issue! We'll fix it and try to include it in the next update.
