### ISSUE TITLE
[Flaky] reviews-by-category/reviews-by-category.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49622]
can sort by lowest rating 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9968815398

**Comment by lanej0** [comment]
block can be inserted and it successfully renders a review in the editor and the frontend 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10095972622

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
