### ISSUE TITLE
Flaky PHP unit test: WC_Admin_Tests_API_Reports_Orders::test_get_reports_with_orphaned_refund

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#49630]
```
1) WC_Admin_Tests_API_Reports_Orders::test_get_reports_with_orphaned_refund
Failed asserting that 125 matches expected 124.

/var/www/html/wp-content/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/api/reports-orders.php:138
phpvfscomposer:///var/www/html/wp-content/plugins/woocommerce/vendor/phpunit/phpunit/phpunit:106

```

Example of a failing run: https://github.com/woocommerce/woocommerce/actions/runs/9969500873/job/27546599057#step:7:120

**Comment by kalessil** [comment]
Hey @jorgemd24 :wave: Routing this issue to you, as it's a fresh test introduced in https://github.com/woocommerce/woocommerce/pull/49006, and we do not exactly have the necessary insights here. Can you look into the issue please?

**Comment by jorgemd24** [comment]
Thanks @kalessil for the ping. I am AFK until July 28th. I can take a look when I am back if no one from my team has addressed it by then. Feel free to skip the test for now if it's causing inconvenience.

**Comment by kalessil** [comment]
Sounds good, thanks! I'll skip it then for now.

**Comment by tomalec** [comment]
Thanks for reporting. It turned out that sometimes the order and the refund are created with the exact same timestamp, which makes the order in asserted results non-deterministic. The fix is waiting for the review at https://github.com/woocommerce/woocommerce/pull/49741
