### ISSUE TITLE
[Enhancement]: Ensure backward compatibility in `WC_Product_Data_Store_CPT::obtain_lock_on_sku_for_concurrent_requests()`, new filter needed.

### ISSUE THREAD

**Issue by Hug0-Drelon** [woothemes/woocommerce#49660]
### Describe the solution you'd like

https://github.com/woocommerce/woocommerce/pull/47476 introduced a new method `WC_Product_Data_Store_CPT::obtain_lock_on_sku_for_concurrent_requests()` to lock SKU during REST request.
But unfortunately it doesn't provide any way to filter the query as `wc_product_has_unique_sku()` does.
So there is now way to have consistent behavior for third parties between the two methods.

Here is something that could do the job:
```php
private function obtain_lock_on_sku_for_concurrent_requests( $product ) {
	global $wpdb;
	$product_id = $product->get_id();
	$sku        = $product->get_sku();

	$query = $wpdb->prepare(
		"INSERT INTO $wpdb->wc_product_meta_lookup (product_id, sku)
		SELECT %d, %s FROM $wpdb->options
		WHERE NOT EXISTS (
			SELECT * FROM $wpdb->wc_product_meta_lookup WHERE sku = %s LIMIT 1
		) LIMIT 1;",
		$product_id,
		$sku,
		$sku
	);

	/**
	 * Filters the query to lock SKU on product creation.
	 *
	 * @since 9.2.1
	 *
	 * @param $query   The query to lock SKU.
	 * @param $product The product being created.
	 */
	$query = apply_filters( 'wc_lock_sku_query', $query, $product );

	// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
	$result = $wpdb->query( $query );
	return (bool) $result;
}
```

### Additional context

This is some key feature in a multilingual environment, where SKU can be shared across languages. That's what we do at Polylang for instance.

**Comment by Hug0-Drelon** [comment]
I'd be glad to make a pull request with some unit tests if needed, once the idea validated of course.

**Comment by naman03malhotra** [comment]
Thanks @Hug0-Drelon for creating this issue, I see your concern is valid, ~~I am curious about use-case you have here, as in, do you have your own check for SKU?~~. I see its multilingual environment. Also, please feel free to send a PR across.

**Comment by Hug0-Drelon** [comment]
@naman03malhotra,

Here it is #49755.
