### ISSUE TITLE
The logo width picker in the CYS sometimes occasionally changes footer's logo in the preview screen

### ISSUE THREAD

**Issue by veljkho** [woothemes/woocommerce#49676]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have the e2e test that checks logo picker in the CYS and the site preview's logo, and the test seems to fail occasionally sometimes (reliability score of the test is poor ~70%).

### Expected behavior

Header's logo changes in the preview screen when changing logo width from the picker

### Actual behavior

Footer's logo changes in size instead header's

### Steps to reproduce

1. Go to CYS: `/wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store%2Fdesign`
2. Choose your logo and attach any from the media library
3. Change the logo width from the picker
4. Obsereve issue, the logo didn't resize in the preview screen for the header, but for the footer instead

[issue is happening occasionally sometimes]
GIF: https://d.pr/i/mLHdJz

### WordPress Environment

clean install

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by veljkho** [comment]
The test seems to pass, and there are no more reported failures in this case. It might be a temporary issue or fixed by another PR.

**Comment by gigitux** [comment]
Thanks for the heads-up! I noticed the same thing! Checking the timeline, it looks like that https://github.com/woocommerce/woocommerce/pull/49681 fixes both issues! I'm going to close this issue! Feel free to re-open if you get additional failure report!
