### ISSUE TITLE
Add support for API test to run against external test sites in ci-jobs

### ISSUE THREAD

**Issue by Stojdza** [woothemes/woocommerce#49694]
We need to run API tests against external sites, but the CI jobs currently only support wp-env. 

Related to https://github.com/woocommerce/woocommerce/issues/48920

**Comment by kalessil** [comment]
@Stojdza: it sounds like it's for Vortex. Can you confirm?

**Comment by Stojdza** [comment]
Hello @kalessil 👋 Yes, it is. Looping @tammullen just in case. Thanks!
