### ISSUE TITLE
Product Filters Redesign > Parent block: Add overlay navigation block

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#49690]
This is a follow-up to https://github.com/woocommerce/woocommerce/issues/47039

## Expected Behavior:

- We want to create the navigation block that is an inner block of the parent Product Filters block. This is needed when user sets the Overlay mode to `mobile` and `always`.
- The navigation block should have the same settings as the overlay navigation block.

## Reference Image:
![Google Chrome -  Block  Product Filters – Figma 2024-07-18 at 11 49 00 AM](https://github.com/user-attachments/assets/3841f095-ef9a-436f-aadb-580b27e19eb4)

**Comment by dinhtungdu** [comment]
I think we can create a variation of the overlay navigation block added in https://github.com/woocommerce/woocommerce/pull/48677. The difference between open and close button is icon and the icon selector, which can be rendered conditionally based on attribute used to distinguish between variations.
