### ISSUE TITLE
Don't attempt creation of a logging directory if file logging isn't in use

### ISSUE THREAD

**Issue by prettyboymp** [woothemes/woocommerce#49761]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

#44735 introduced changes that now attempts to create a logging directory if one does not yet exist every load even when file logging is not being used.

We use custom logging for WooCommerce on WPCOM that does not require write access to the file system.  Further, not all web servers have access to a writeable filesystem.  

The line below in class-woocommerce.php ends up calling `Automattic\WooCommerce\Internal\Admin\Logging\Settings::get_log_directory()` every time WooCommerce is loaded.  This method attempts to create the directory if it does not yet exist.

https://github.com/woocommerce/woocommerce/pull/44735/files#diff-97fb927371ee663e98afaf8b8134905a96d4b59c68f6a83c569ec42a6b468a08R380

### Expected behavior

If file logging is not in use, there should be no attempt to create a logs directory. 

### Actual behavior

There is an attempt to create the logs directory even when file logging isn't active.

### Steps to reproduce

1. Setup a WooCommerce site.
2. For the sake of mimicking some hosting environments that don't have direct file system access to the uploads directory, either delete or make the uploads directory read-only.
3. Attempt to run the site
4. Check the php error logs for warnings similar to: `Warning: mkdir(): No such file or directory in ...`

### WordPress Environment

WPCOM

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@prettyboymp do you think https://github.com/woocommerce/woocommerce/pull/49766 resolves this issue completely, or is there still more to do here?

**Comment by prettyboymp** [comment]
closed with #49766
