### ISSUE TITLE
Investigate K6 tests failures

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#49794]
The K6 perf tests are randomly failing on push to trunk. We should investigate those runs.

Examples:
https://github.com/woocommerce/woocommerce/actions/runs/10057103361/job/27797417326
https://github.com/woocommerce/woocommerce/actions/runs/10055465515/job/27792237188
https://github.com/woocommerce/woocommerce/actions/runs/10053697937/job/27786974862
https://github.com/woocommerce/woocommerce/actions/runs/10042072751/job/27751758665

**Comment by adimoldovan** [comment]
Potentially https://github.com/woocommerce/woocommerce/pull/48937 fixed the issues.
Let's keep this open for a few more days and if no new failures occur we'll close it.

**Comment by tammullen** [comment]
Still some occasion fails that look flakiness related p1722590852064409-slack-C073SCV2RB9

**Comment by adimoldovan** [comment]
The tests have been stable lately, I will close this one.
