### ISSUE TITLE
Product Filters Redesign: Refactor Product Filter Block Variations into Individual Blocks

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#49811]
## Description
Currently, the Product Filter block contains several block variations, each representing a different type of filter. This issue aims to convert the block variations into separate blocks.

## Expected Behavior:

- Each filter type will be implemented as a separate block (Active Filters, Attribute, Rating, Stock Status, etc).
- Each block will have its own settings and functionalities.
- The block structure must remains the same, containing the header and the Filter Options.

**Comment by dinhtungdu** [comment]
#51096 covers this one so I'm closing.
