### ISSUE TITLE
Unable to create a product using API woocommerce_product_invalid_image_id

### ISSUE THREAD

**Issue by danny-reynolds** [woothemes/woocommerce#49884]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi all.

I'm trying to create a product using the API (python implementation)

I'm passing the product data shown here:
`{
	'name': 'Blacksmith S-Hook',
	'description': 'Hand-forged S-Hook with scroll and twist detail',
	'status': 'publish',
	'catalog_visibility': 'visible',
	'purchasable': True,
	'tax_status': None,
	'tax_class': 'zero-rate',
	'manage_stock': False,
	'stock_status': 'instock',
	'reviews_allowed': True,
	'categories': [
		{'id': 18}
		],
	'shipping_required': True,
	'shipping_class_id': 19,
	'slug': 'hook_S_square_twist',
	'sku': 'hook_S_square_twist',
	'tags': [
		{'id': 59},
		{'id': 60},
		{'id': 61},
		{'id': 62},
		{'id': 63},
		{'id': 64},
		{'id': 65},
		{'id': 66},
		{'id': 67},
		{'id': 68},
		{'id': 64},
		{'id': 69},
		{'id': 70}
		],
	'images': [
		{'url': 'https://i.etsystatic.com/25383872/r/il/a06ab8/4063307182/il_fullxfull.4063307182_t7lb.jpg'},
		{'url': 'https://i.etsystatic.com/25383872/r/il/c047d1/4110948077/il_fullxfull.4110948077_phcc.jpg'},
		{'url': 'https://i.etsystatic.com/25383872/r/il/0c3877/4063307746/il_fullxfull.4063307746_elow.jpg'},
		{'url': 'https://i.etsystatic.com/25383872/r/il/cc9656/4063308024/il_fullxfull.4063308024_cprf.jpg'},
		{'url': 'https://i.etsystatic.com/25383872/r/il/bb16a5/4110949159/il_fullxfull.4110949159_e8kx.jpg'},
		{'url': 'https://i.etsystatic.com/25383872/r/il/edfca1/4110949133/il_fullxfull.4110949133_1y7l.jpg'},
		{'url': 'https://i.etsystatic.com/25383872/r/il/074dbd/4063308472/il_fullxfull.4063308472_4sxp.jpg'}
		],
	'featured': False,
	'type': 'variable'
}`

I'm getting the error response:

`{'code': 'woocommerce_product_invalid_image_id', 'message': '#0 is an invalid image ID.', 'data': {'status': 400}}`

I've searched a LOT and obviously found many people talking about this error, but have not found a clear way to fix it. The usual issues like there not being an extension in the URL aren't there.

These image URLs are from Etsy, it's worth noting that when I put these into a csv and upload through the woocommerce web interface, it works perfectly.

### Expected behavior

Adding a new product

### Actual behavior

`{'code': 'woocommerce_product_invalid_image_id', 'message': '#0 is an invalid image ID.', 'data': {'status': 400}}`

### Steps to reproduce

Upload a product using the above data object (ommiting the tag and category ids, cause you wont have them).
Used python implementation with:

`wcapi.post("products", listing_obj).json()`

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.6 - There is a newer version of WordPress available (6.6.1)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-cll-lve
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 4
page: 7
post: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.1.2

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/techno/public_html/development/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/techno/public_html/development/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/techno/public_html/development/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-24 15:43:49 +00:00
Options: ✔
Notes: 58
Onboarding: completed

### Action Scheduler ###

Complete: 5
Oldest: 2024-07-23 15:45:08 +0000
Newest: 2024-07-23 19:27:51 +0000

Pending: 1
Oldest: 2024-07-24 15:45:08 +0000
Newest: 2024-07-24 15:45:08 +0000


### Status report information ###

Generated at: 2024-07-23 23:20:32 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
hey @danny-reynolds , I think instead of `url` the param is called `src`. so your request should look like this: 
```
...
 'images': [ {'src': 'https://i.etsystatic.com/25383872/r/il/a06ab8/4063307182/il_fullxfull.4063307182_t7lb.jpg'}, ...
```

**Comment by danny-reynolds** [comment]
I can't believe I did something that simple wrong. It's because I'm using the woocommerce and etsy api in this project, pulling the image from etsy where it's listed as url, not src.

My bad, tested and working fine
