### ISSUE TITLE
[Enhancement]: Обновление фрагмента счётчика корзины

### ISSUE THREAD

**Issue by xeqtr-zhg** [woothemes/woocommerce#49925]
### Describe the solution you'd like

Good afternoon, I use "woocommerce_add_to_cart_fragments" to display the counter of products (which are in the cart) in the header of the site, it works fine with one exception. When a user is on the main page of the shopping cart and tries to change the number of products or delete products, the fragment in the header of the site is not updated automatically, although it would be logical that the value would be updated. I do not know if this behavior is intended or if it is a bug, I would be grateful if you could tell me how to update the value after the changes. Thank you and forgive me for my English.

**Comment by opr** [comment]
I'll reply with the assumption you're using the Cart block.

It's expected that fragments aren't returned when updating products in the Cart block.

If you want to respond to changes in the cart, I'd recommend subscribing to the `wc/store/cart` data store.

- [More info on `@wordpress/data`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/)
- [More info on the `wc/store/cart` data store](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/data-store/cart.md).

**Comment by xeqtr-zhg** [comment]
> Я отвечу, предполагая, что вы используете блок «Корзина».
> 
> Ожидается, что фрагменты не возвращаются при обновлении товаров в блоке «Корзина».
> 
> Если вы хотите реагировать на изменения в корзине, я бы рекомендовал подписаться на `wc/store/cart`хранилище данных.
> 
> * [Дополнительная информация о`@wordpress/data`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/)
> * [Дополнительная информация о `wc/store/cart`хранилище данных](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/data-store/cart.md) .

Да это именно то что мне нужно, спасибо большое.
