### ISSUE TITLE
Add a tool in Beta Tester to create WooPayments test orders

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#49920]
## Issue Description

It would be helpful to have a beta tester tool that can convert an existing order to a [WooPayments Test Order](https://woocommerce.com/document/woopayments/testing-and-troubleshooting/testing/#test-orders). This would make it simpler to test features in the "Launch your store" task.

## Acceptance Criteria

* Provide a tool that applies the following "post meta" to existing orders: 

| Name | Value |
|---|---|
| _wcpay_mode | test |

**Comment by psealock** [comment]
@adrianduffell As an initial first pass I'm going with something like this:

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/7a47c4bf-88c7-473c-b901-b874ea17d5a7">

Is the use case for more than a few orders? I could add pagination and a bulk edit feature.

**Comment by adrianduffell** [comment]
@psealock Wow, it's looking great! 

I picture about 5-10 orders would be changed when testing, so this would be perfect for it. Perhaps, let's see if the use case expands and we need pagination / bulk edit too?
