### ISSUE TITLE
Product Filters Redesign > Overlay: Implement Trigger Button to Open Overlay

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#49933]
## Description
There’s an overlay setting in the settings tab. Users can decide whether filters should be shown on top of the page on mobile, always (no matter the screen size), or never.

## Expected Behavior:

- All filters should be rendered on the frontend when the Overlay Style is set to Never.
- When the Overlay Style is set to Mobile, and the user is on a mobile device, the trigger button should be rendered on the frontend instead of the filters.
- When the Overlay Style is set to Always, the trigger button should be rendered on the frontend instead of the filters, regardless of the device they use.
- The trigger button should respect the customizations made by the merchants in the editor.

## Reference images

| Product Filters Overlay Style settings |
|--------|
| ![image](https://github.com/user-attachments/assets/205f1cf2-2386-4bb5-bbfd-1fa17b56f2c1) |

| Example of how the trigger button would appear in the frontend when the Icon and Label option is selected |
|--------|
| ![CleanShot 2024-07-24 at 18 09 41@2x](https://github.com/user-attachments/assets/7fdf2246-2dc4-4482-8556-21e9d2dd2aff) |

**Comment by dinhtungdu** [comment]
It looks like the trigger button belongs to the Product Filters template part. What should we do with the overlay as it now [contains](https://github.com/woocommerce/woocommerce/pull/49999) the Product Filters template part, so does the trigger button?

**Comment by thealexandrelara** [comment]
> It looks like the trigger button belongs to the Product Filters template part. What should we do with the overlay as it now https://github.com/woocommerce/woocommerce/pull/49999 the Product Filters template part, so does the trigger button?

Initially, I tried to remove it from the Filters Overlay, but that is not an option since it is synced with the Product Filters template part. The best option I can think of is to hide it from those template parts. It will still appear in the list view, just not in the editor and the front end. Another option, instead of hiding it, is to think about showing some kind of message, like the ones that appear for the Rating Filter when there are no reviews for that shop.

**Comment by dinhtungdu** [comment]
> It will still appear in the list view, just not in the editor and the front end.

This will make users confused. I think it's best to ask @jarekmorawski for help on this.

**Comment by jarekmorawski** [comment]
I'm not sure. Given the editor's constraints, I'd say @thealexandrelara's initial approach is correct.

However, I wonder if the trigger button should be included in the template part. In the design, the template part is removed when the overlay is set to `Always`. Perhaps we'd do the same? Then the Product Filters template part would only contain the trigger button and the Filters Overlay would become the main way to edit the filters.

If that isn't possible or doesn't make sense, I'd do what Alexandre suggests. We already have a similarly quirky behavior in the Product Collection block where the 'No Results' block is always displayed in the canvas even though it will only be displayed when there are no products to show.

**Comment by dinhtungdu** [comment]
> In the design, the template part is removed when the overlay is set to Always.

@jarekmorawski  Correct me if I'm wrong, but from my observation, the Overlay Navigation belongs to the Product Filters block, right? When the overlay is set to Always, the `Product Filters` block is still there, we only remove the inner blocks like heading and filter options. Is that what you want?

Here is a visual representation of the current structure.

![image](https://github.com/user-attachments/assets/deff4875-8332-43d8-ae08-bd1cd51769db)


We are embed the whole Product Filters template part, which is the main one that is inserted to the Product Catalog and other archive templates. So we can't do this with the current structure:

> However, I wonder if the trigger button should be included in the template part. In the design, the template part is removed when the overlay is set to Always. Perhaps we'd do the same? Then the Product Filters template part would only contain the trigger button and the Filters Overlay would become the main way to edit the filters.

So, the navigation shouldn't be synced, right. Then I think we can alter the current approach as I suggested in pdnLyh-66e-p2#comment-4754

> If the Products Filter Navigation block shouldn’t be a part of Overlay, then we will need a Filter Options synced pattern to be shared between Product Filters and Product Filter Overlay, right?

![image](https://github.com/user-attachments/assets/e6f87a50-89dc-498a-beb0-0b1782e9c585)
 
What do you think? cc @thealexandrelara @roykho

**Comment by thealexandrelara** [comment]
> However, I wonder if the trigger button should be included in the template part. In the design, the template part is removed when the overlay is set to Always. Perhaps we'd do the same? Then the Product Filters template part would only contain the trigger button and the Filters Overlay would become the main way to edit the filters.

Unfortunately, we cannot remove the Product Filters block and replace it with the trigger button (the Navigation block). One reason for this is that when we remove blocks from the editor, we lose their state. For example, if merchants modify the Product Filters block and set the overlay to ‘Always’, we would remove the Product Filters block. If they later set the overlay back to ‘Never’, we wouldn’t be able to restore the initial state of the modified Product Filters block.

Another limitation is that we need to keep the Product Filters block in sync with the template part within the Product Filters Overlay. We are using the Product Filters template part inside it, which means that if we remove the Product Filters block when the user sets the Overlay setting to ‘Always’, it will also affect the Product Filters Overlay.

If we want to have different views depending on the selected Overlay option, we would need something like what Tung suggested - a view switcher similar to what we have for the Cart block.

**Comment by dinhtungdu** [comment]
> Another limitation is that we need to keep the Product Filters block in sync with the template part within the Product Filters Overlay. We are using the Product Filters template part inside it, which means that if we remove the Product Filters block when the user sets the Overlay setting to ‘Always’, it will also affect the Product Filters Overlay.

@thealexandrelara what do you think about my suggestion above on using another template part to share filter options.

Here is another quirky behavior of embedding the `Product Filters` template part inside `Filter Overlay` template part:

<img width="1687" alt="image" src="https://github.com/user-attachments/assets/1a13f1d5-34e6-4729-832a-d283bd7432d1">

**Comment by thealexandrelara** [comment]
> what do you think about my suggestion above on using another template part to share filter options.

It’s a little bit hard to predict the possible outcomes of this change (so many template parts 😅), but this is definitely something we can explore. I believe this way we get the benefit of separating the Overlay Navigation blocks. The issue is that, based on your diagrams, the Product Filters wrapper block would exist only in the Product Filters template part, so if users change the settings there, it would not be reflected in the Product Filters Overlay template part, right?

**Comment by dinhtungdu** [comment]
> so if users change the settings there, it would not be reflected in the Product Filters Overlay template part, right?

Yes, that's the point. The only thing shared between them is the actual filter blocks. I don't see how it can be an issue.

I can work on a PR (next cooldown/cycle) for consideration. What do you think?

cc @jarekmorawski is this something worth exploring?

**Comment by jarekmorawski** [comment]
I think it's worth exploring. However, I wonder if we can somehow simplify the block structure because it's getting out of hand. What if:

- we only had one template part with all Product Filters (without the Product Filters wrapper block)
- it'd be locked and not removable
- it'd be automatically inserted into the Product Filters block
- we'd remove the overlay wrapper block and only put the new filters template part and the navigation block in the overlay template part

**Comment by dinhtungdu** [comment]
> we only had one template part with all Product Filters (without the Product Filters wrapper block)

@jarekmorawski So we're adding the wrapper block directly to template, not wrapped by a template part like we're doing? If yes, then how do we sync the setting of the wrapper block, for example between shop and category page?

**Comment by jarekmorawski** [comment]
> If yes, then how do we sync the setting of the wrapper block, for example between shop and category page?

I don't know. Perhaps the template part alone could hold that data somehow? In the UI, template parts and synced patterns act like regular blocks, but I assume it isn't the same under the hood. Would it make sense to run this by the Gutenberg team? Maybe a template part allows for storing metafields or attributes we'd transfer between instances?

**Comment by dinhtungdu** [comment]
> Perhaps the template part alone could hold that data somehow?

AFAIK, no. But even if it's possible, I don't think it's the right place to store the data. The template part is children of the Product Filters block, if we store Product Filters block data to it, then, when the Overlay Navigation block needs to retrieve the overlay setting, the Product Filters block need to get the setting from the template part and pass it down to the Overlay Navigation. I don't say it's impossible, but it's a confusing data flow. As the general flow of data in blocks is top-down/unidirectional flow from parent to children through context.
