### ISSUE TITLE
Add React root for WooPayments payment methods screen

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#49930]
## Issue Description

To allow the WooPayments payments settings screen to be populated with React views, create a new settings page with a react root and component.

![Image](https://github.com/user-attachments/assets/176670d2-bf9e-4800-b89b-ea0fec555e2a)

## Acceptance Criteria

* When the [feature flag](https://github.com/woocommerce/woocommerce/issues/49926) is enabled, add a new settings "sub-page" within payments for WooPayments payment methods.
* When the feature flag is disabled, no operations are required because an equivalent page does not currently exist
* The title of the page should be "Enable payments with Woo"
* Create a basic react component, e.g. a large black box, to demonstrate usage

**Comment by adrianduffell** [comment]
The slot will eventually be populated with a view such as

<img width="1271" alt="payment setings woo payment methods" src="https://github.com/user-attachments/assets/4a02ebd3-fa20-48dd-a69a-95be917a3f8c">

**Comment by ilyasfoo** [comment]
Completed in https://github.com/woocommerce/woocommerce/pull/50008
