### ISSUE TITLE
[Flaky] product-filters/attribute-filter.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#49987]
should dynamically set block title and heading based on the selected attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10094563101

**Comment by lanej0** [comment]
should display the correct inspector setting controls 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10202478988

**Comment by lanej0** [comment]
should dynamically set block title and heading based on the selected attribute 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10202478988

**Comment by lanej0** [comment]
should display the correct inspector style controls 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10202478988

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
