### ISSUE TITLE
Product Filters Redesign: Rename Navigation blocks

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#49980]
## Description

The navigation block has the same name and icon as the Core Navigation block, but it only opens/closes the overlay. It may be confusing to merchants. Can we change it to other name and use a different icons to distinguish from the Core one?

**Comment by dinhtungdu** [comment]
@jarekmorawski can you share your insights here? In our call, we shared the same confusion about this block.

**Comment by jarekmorawski** [comment]
Good call. We can call it `Overlay Navigation` and use the icon below (right-click to save as SVG).

![Icon](https://github.com/user-attachments/assets/5d0727a0-915c-4429-8f6c-28ad78bab2a3)

<img width="574" alt="image" src="https://github.com/user-attachments/assets/59c05efb-3afe-42fa-b492-c8687008b087">
