### ISSUE TITLE
[Flaky] add-to-cart-form/add-to-cart-form.block_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#50001]
can be added in the Post Editor - Single Product Template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10101705862

**Comment by lanej0** [comment]
can be added in the Site Editor only as inner block of the Single Product Block - Product Catalog Template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10101705862

**Comment by lanej0** [comment]
can be added in the Post Editor - Single Product Template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10164602861

**Comment by lanej0** [comment]
can be added in the Post Editor - Single Product Template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10200119971

**Comment by lanej0** [comment]
can be added in the Post Editor only as inner block of the Single Product Block 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10200119971

**Comment by lanej0** [comment]
can be added in the Site Editor only as inner block of the Single Product Block - Product Catalog Template 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10200119971

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
