### ISSUE TITLE
Product Collection: Editor vs frontend price range filter disparity

### ISSUE THREAD

**Issue by WunderBart** [woothemes/woocommerce#50019]
### Describe the bug

Related convo: p1721905572300349/1721828740.238419-slack-C05UMTA7W0P

When a merchant price range filter is set, products with variations are not displayed in both the editor and the front end. If the merchant filter is disabled and only a client price range filter is used, products with variations are displayed.

### Expected behavior

Products with variations should always be included when a matching price range is set, regardless of whether it's a merchant or client filter. 

### Actual behavior

Products with variations that match the current price range query are rendered when the client price range filter is used but not when the merchant price range filter is used.

### Steps to reproduce

1. Create a new post.
2. Add the Product Collection block.
3. Apply the merchant price range filter that should include at least one product with variations.
4. Notice that the matching product is not in the results.
5. Publish the post and go to the frontend.
6. See that the matching product is not in the results.
7. Go back to the editor.
8. Remove the merchant price range filter.
9. Add the `Filter by Price` block.
10. Publish the post and go to frontend.
11. Apply the same price range and see that the matching product with variations is included with the results.

### WordPress Environment

WP 6.6

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment]
There is an issue with the post clause filter for the price range filter.

https://github.com/woocommerce/woocommerce/blob/49fa0a7b1a116477dd7935f4613fab118cb0e21d/plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php#L1670-L1686

The correct clauses should be similar to what we use for the new price filter block in QueryFilters.php. When query the product for the min price filter, we need to compare the max price of that product, not the min one. The same applies to the max price filter.

https://github.com/woocommerce/woocommerce/blob/49fa0a7b1a116477dd7935f4613fab118cb0e21d/plugins/woocommerce/src/Blocks/QueryFilters.php#L234-L252
