### ISSUE TITLE
Unexpected hooked block rendered before product summary block (`wp-post-excerpt`) when any action in added on `woocommerce_before_single_product_summary` hook.

### ISSUE THREAD

**Issue by daviedR** [woothemes/woocommerce#50056]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When there are actions registered on the `woocommerce_before_single_product_summary` hook, they will be rendered on the product excerpt block (`wp-post-excerpt`).

This should be considered a bug because the hook is used to insert elements before or between the product images and the product summary column in the classic template. For example, wrapping the product images column or adding new elements before the product images column.

These actions might not be relevant when used on a blocks template.

I think this logic is defined by the `set_hook_data` on the `SingleProductTemplateCompatibility` file. I am not sure what's the actual purpose of this implementation. But in my use case, it breaks the rendered product summary block.

### Expected behavior

All actions registered on the `woocommerce_before_single_product_summary` hook should NOT be rendered before the product excerpt.

### Actual behavior

All actions registered on the `woocommerce_before_single_product_summary` hook are rendered before the product excerpt.

### Steps to reproduce

Add this snippet to the functions.php:

```
add_action( 'woocommerce_before_single_product_summary', function() {
	echo 'test';
} );
```

Check on the single product page (with the blockified template), the `test` text is rendered just before the product excerpt.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.3.8
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 19
post: 6
product: 18
product_variation: 7
revision: 1
shop_coupon: 1
shop_order_placehold: 1
wp_font_face: 2
wp_font_family: 1
wp_global_styles: 7
wp_navigation: 1
wp_template: 5
wp_template_part: 2
wpcode: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.1.2

### Inactive Plugins (23) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Gutenberg: by Gutenberg Team – 18.8.0
WooPayments: by WooCommerce – 7.9.2
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 81 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /account/
Terms and conditions: #458 - /terms-and-conditions/

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /.../public/wp-content/plugins/woocommerce/templates/block-notices/error.php
/.../public/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/.../public/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-21 07:59:40 +07:00
Options: ✔
Notes: 79
Onboarding: completed

### Action Scheduler ###

Complete: 559
Oldest: 2024-06-20 01:52:42 +0000
Newest: 2024-07-20 16:22:49 +0000

Failed: 2
Oldest: 2023-12-28 08:04:25 +0000
Newest: 2024-07-09 05:08:31 +0000

Pending: 1
Oldest: 2024-07-21 16:12:19 +0000
Newest: 2024-07-21 16:12:19 +0000


### Status report information ###

Generated at: 2024-07-20 23:22:54 +07:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
Hi @daviedR! Thanks for opening this issue!

Can you explain why the `All actions registered on the woocommerce_before_single_product_summary hook should NOT be rendered before the product excerpt`? 

The Product excerpt is the Product Summary, so I think that the hook is injected in the right place. I noticed that the documentation wasn't updated. I updated it with https://github.com/woocommerce/woocommerce/pull/50348

**Comment by daviedR** [comment]
Hi @gigitux 

In the classic template, the `woocommerce_before_single_product_summary` hook is used by WooCommerce itself to inject sale badge and product images gallery. The images gallery will create a column on the left side beside the summary column. ref: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/content-single-product.php

If developers want to add a section just before the images & summary column, they will use the `woocommerce_before_single_product_summary` hook.

In the blockified template, the hooked section will be rendered before the product excerpt (inside the summary column).

I think in the classic template, the `product_summary` term in the hook name refers to the whole summary column, which contains a lot of elements: title, rating, price, excerpt, add to cart form, and product meta.

While in the blockified template, `product_summary` is treated as the product excerpt block, which is NOT the same.

I have created a sample snippet to demonstrate this. I am using the default Twenty Twenty Four theme.

```
add_action(
	'woocommerce_before_single_product_summary',
	function() {
		echo '<p>This is added via `woocommerce_before_single_product_summary` hook.</p>';
	}
);
```

In the classic template (using the `Product (Classic)` block):

![image](https://github.com/user-attachments/assets/33641f01-7d3a-40d6-bcfe-f2f7b43ece46)

In the blockified template:

![image](https://github.com/user-attachments/assets/1098d9c3-08c9-4674-9cbf-37c6d2e6a084)

In the screenshots above, it's clear that the `woocommerce_before_single_product_summary` hook is not properly used in the blockified template.

**Comment by gigitux** [comment]
Thanks, @daviedR, for catching this! 

We are planning to fix it https://github.com/woocommerce/woocommerce/pull/50392
