### ISSUE TITLE
[Flaky] checkout/checkout-block.merchant.classic_theme.spec.ts

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#50052]
can't be inserted in a widget area 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10122184604

**Comment by lanej0** [comment]
can't be inserted in a widget area 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/10145855966

**Comment by WunderBart** [comment]
p1722589443272369/1722588389.163629-slack-C03CPM3UXDJ
