### ISSUE TITLE
Migrate All Products block to functional component

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#50063]
**Issue Description:**

There is currently some effort going on to migrate all blocks to v3 [in this PR](https://github.com/woocommerce/woocommerce/pull/48720). But migrating the all products block is hindered because we need to make it a functional component. (See [this comment](https://github.com/woocommerce/woocommerce/pull/48720#issuecomment-2252604725) ).

**Comment by dinhtungdu** [comment]
@samueljseay this is a blocker for the migration so I decided to tackle it now. For cooldown, we can convert it the TypeScript. I opened #50203 and tagged you as the reviewer. Can you please take a look?
