### ISSUE TITLE
woocommerce product data is blank

### ISSUE THREAD

**Issue by sqahremani419** [woothemes/woocommerce#50069]
I use woocommerce last update. the product data is blank and don.t show anything. i change them and disable all other plugins but the problem still persist. 
i downgrade to woocommerce v2 and it was ok. but its version is very old and better to use new version. all newer version has the same problem.
anyone can help me?

![Screenshot-2024-07-26-111008](https://github.com/user-attachments/assets/095d9b45-5dab-48cb-8450-06856525723c)

**Comment by lanej0** [comment]
Hi @sqahremani419,

Can you open up the JavaScript console (View > Developer > JavaScript Console in Chrome) and try reloading the page?  Also try using another browser, and let me know if you see the same thing (this looks like you might have a browser extension blocking the page load).

**Comment by sqahremani419** [comment]
> Hi @sqahremani419,
> 
> Can you open up the JavaScript console (View > Developer > JavaScript Console in Chrome) and try reloading the page?  Also try using another browser, and let me know if you see the same thing (this looks like you might have a browser extension blocking the page load).

thanks a lot. i find problem.
a chrome extension named "v lock up" couse this problem. i disabled it and i haven't got any problem now.
