### ISSUE TITLE
The Atributes is not showing iven i selected it in product settings page.

### ISSUE THREAD

**Issue by Riscul** [woothemes/woocommerce#50071]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Atributes is not showing iven i selected it in product settings page.

### Expected behavior

The Atributes is not showing iven i selected it in product settings page.

### Actual behavior

The Atributes is not showing iven i selected it in product settings page.

### Steps to reproduce

The Atributes is not showing iven i selected it in product settings page.

### WordPress Environment

The Atributes is not showing iven i selected it in product settings page.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @Riscul,

Could you attach a screenshot of what you're seeing?  Preferably with the JavaScript Console open (View > Developer > JavaScript Console in Chrome).  Also, if you could include a System Status Report, that might help us identify a plugin conflict that might be causing this.
