### ISSUE TITLE
Include purge cache when coming soon template is updated in documentation

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#50077]
### Issue Description

In pgbkb-9YC-p2#comment-26629, Yordan suggests:

> Perhaps you can expose the “coming soon” template edit to one of the hooks in your documentation and not send no-cache headers? 

It'll be a good addition to put into our documentation for hosting providers to integrate to ensure coming soon template changes will trigger a cache purge.

### Acceptance criteria

1. Add documentation to using `save_post_wp_template` and `save_post_wp_template_part` to detect coming soon template changes and purge cache in https://github.com/woocommerce/woocommerce/blob/63c77caf95d8a1b2731bf2a823a3c305c03dd35d/docs/extension-development/integrating-coming-soon-mode.md

**Comment by rjchow** [comment]
For accuracy, we've changed it to [60s cache instead of no-cache](https://github.com/woocommerce/woocommerce/pull/52200)
