### ISSUE TITLE
Missing css .tips class in admin list with order statuses

### ISSUE THREAD

**Issue by pzmijewski** [woothemes/woocommerce#50089]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The problem is related to the CSS class .tips on the admin orders list view.
The class was previously used within data-colname=“Status” in the mark selector.
Currently, there is only the class “order-status” and the status itself in the selector.

![Woo_v914](https://github.com/user-attachments/assets/e30e28f6-d042-4259-8ebd-71fa7dd86e89)
![Woo_v902](https://github.com/user-attachments/assets/eb254ee7-bb49-45b1-aa87-97f4364fb02f)

### Expected behavior

It seems to me that the class should be maintained

### Actual behavior

No class ".tips", can cause problems related to the colors of customized order statuses.

### Steps to reproduce

1. go to the order list and compare the classes in the new current version 9.1.4 and version 9.0.2
2. check with devTools that the status of a given order is missing the tips class in the mark selector.

### WordPress Environment

n/a
woo 9.1.4 vs woo 9.0.2

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi! It looks like you may be taking advantage of custom statuses. If these do not have an attached description (one way to ensure they do, is by taking advantage of the `woocommerce_get_order_status_labels` filter hook) then the tip class may not be applied. This is intentional, and I'm not sure we want to change it.

> No class ".tips", can cause problems related to the colors of customized order statuses.

Is there a reason you reference `.tips` if your primary goal is to colorize these status labels?

**Comment by pzmijewski** [comment]
> Is there a reason you reference `.tips` if your primary goal is to colorize these status labels?

Maybe it's strange, but I used this class to support the selector to have the highest priority - in case of any problems.

@barryhughes Could you please check in your latest version of woocommerce if you see tooltips when you hover over the status?
In the previous version [9.0.2] (it works for me, but the current version does not. It is possible that the problem is more serious than just a `.tips `class issue?)

thank you.

**Comment by barryhughes** [comment]
> In the previous version [9.0.2] (it works for me, but the current version does not. It is possible that the problem is more serious than just a .tips class issue?)

That's possible, yep. [This other report](https://github.com/woocommerce/woocommerce/issues/50284), which seems related, also came in (though we hadn't seen it before evaluating this one). We'll look into it—thank you for flagging!

**Comment by barryhughes** [comment]
It seems the change was intentional, but it is possible to restore the earlier behaviour:

https://github.com/woocommerce/woocommerce/issues/50284#issuecomment-2309827186

With that in mind, I'll close this issue.
