### ISSUE TITLE
[DOC-REQ] HPOS current tested / approved compatibility list or incompatibility list

### ISSUE THREAD

**Issue by TomasHurtz** [woothemes/woocommerce#50109]
Hello team

Thank you for your continued work on such a great product.

Just wondering if there is a global list somewhere that is contributable, with plugins that are / are not compatible with HPOS?

Would be great to be able to refer to to such a chart, and where feasible, to contribute to it.

I apologise if this has already been asked, but I searched and was not able to find anything definitive.

I did find this, but it seems not up to date: 
https://github.com/woocommerce/woocommerce/tree/trunk/docs/high-performance-order-storage
https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/

**Comment by barryhughes** [comment]
Hi!

That's an interesting idea, but we are not aware of an existing list and are just a little unsure about our ability to compose such a thing and maintain it—especially if it should cover third party plugins/extensions not sold in the official marketplace—or the ongoing value of such a list now that HPOS is the default data-store.

For those extensions that *are* in the marketplace, compatibility with HPOS is generally indicated on the product pages. [Example:](https://woocommerce.com/products/minmax-quantities/)

<div align="center"><img src="https://github.com/user-attachments/assets/39670398-15a4-4495-a026-b063076b5799" width="300px" alt="Example of HPOS compatibility flag on a marketplace product page" /></div>

> I did find this, but it seems not up to date:
> https://github.com/woocommerce/woocommerce/tree/trunk/docs/high-performance-order-storage
> https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/

Indeed, the blog post is from 2022 so has to be read with that in mind. Are there specific problems with the [main HPOS doc](https://github.com/woocommerce/woocommerce/tree/trunk/docs/high-performance-order-storage) you referenced? We'd certainly be interested in bug reports and/or PRs for this if so 👍🏼
