### ISSUE TITLE
Product Filters Redesign: Attribute Filter: Loading State

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#50150]
It should pulse, slowly changing opacity from 5% to 8% and back.

![image](https://github.com/user-attachments/assets/163fe03f-626c-4390-908f-b211796d4ab5)

Figma: 3td38XZM4P9WhWg618nXjt-fi-64_167456

**Comment by roykho** [comment]
@dinhtungdu can you please give move context to this issue? This is for frontend? When should it show this loading state? When an attribute is clicked? Currently the action clicking on the attribute is almost instant so loading state would only flash.

**Comment by dinhtungdu** [comment]
> This is for frontend?

@roykho This is for the editor. I updated the full screenshot and Figma link for your reference.

> When should it show this loading state?

When the data is loading: In the editor, when the block is rendered, it starts fetching attribute terms and filter counts for those attribute terms. The loading state should be visible until all data has been loaded and the filter options are processed.

> Currently the action clicking on the attribute is almost instant so loading state would only flash.

It loads instantly in localhost on a fast machine with small sample data. But there will be a delay if:
- The store has many product attribute terms.
- The network is slow.
- The hosting is slow.
