### ISSUE TITLE
Automate updates to latest WordPress version for E2E tests

### ISSUE THREAD

**Issue by WunderBart** [woothemes/woocommerce#50163]
Let's continue [the discussion](https://github.com/woocommerce/woocommerce/pull/49704#pullrequestreview-2187861968) from #49704 here.

**Current action items**

1. Implement a system to promptly update the `wp-env` configuration file with each new WP release.
2. Ensure E2E tests for WC Core and WC Blocks run against the same WP version.
3. Incorporate RC and latest-1 version checks into the daily testing routine.

cc: @gigitux @opr @adimoldovan

**Comment by adimoldovan** [comment]
> 1. Implement a system to promptly update the wp-env configuration file with each new WP release.

This is already implemented. The config file doesn't need to be updated, the version is controlled in CI via the `WP_ENV_CORE` variable. This is set by the [`ci-jobs`](https://github.com/woocommerce/woocommerce/blob/4b90743ada8f13d56efc1576f9fd111ceb643567/tools/monorepo-utils/src/ci-jobs/lib/test-environment.ts#L23) utility based on the job configuration [`testEnv.config.wpVersion`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/package.json#L435).


> 2. Ensure E2E tests for WC Core and WC Blocks run against the same WP version.

This is already happening as long as the core version in `.wp-env.json` config file is left `null` or missing. This is to cover the (default) job config where `testEnv.config.wpVersion` is not configured, and the version will fallback to whatever is set in `.wp-env.json` (and null -> latest).

> 3. Incorporate RC and latest-1 version checks into the daily testing routine.

[`latest-1`](https://github.com/woocommerce/woocommerce/blob/4b90743ada8f13d56efc1576f9fd111ceb643567/plugins/woocommerce/package.json#L421) is already running for Core e2e. 


What's left to implemented:
- include blocks e2e with latest-1 in the daily run?
- automate the RC version. The tricky part is that an RC is not always available.

**Comment by tammullen** [comment]
>  automate the RC version. The tricky part is that an RC is not always available.

@lanej0 started looking into a possible solution here

https://github.com/woocommerce/woocommerce/blob/430a099b9d2273b9694325f5db2aac3bf95c0110/plugins/woocommerce/tests/e2e-pw/utils/wordpress.js#L24

**Comment by tammullen** [comment]
We have a target deadline for this of WP 6.7 Beta currently due Oct 1 
https://make.wordpress.org/core/2024/07/05/wordpress-6-7-planning-proposal-call-for-volunteers/

**Comment by adimoldovan** [comment]
Update: work in progress, started gathering feedback in pcr5Cj-6YP-p2
