### ISSUE TITLE
'Restrict to Store Only' breaks Privacy Policy page

### ISSUE THREAD

**Issue by thegulshankumar** [woothemes/woocommerce#50161]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

(https://wordpress.org/support/topic/activating-plugin-deleted-content-of-my-privacy-policy-page/#post-17922694)

### Expected behavior

Coming soon or restricted mode shouldn't affect normal pages like Privacy Policy. 

### Actual behavior

If coming soon or restricted mode is set, it should impact the Shop part only not Privacy Policy page.

### Steps to reproduce

1. Install & Activate WooCommerce plugin only with default WordPress site. Nothing else.
2. Do this https://imgur.com/zGVJaUg
3. Set or Create privacy policy page in WordPress settings. Grab its link from pages.
4. Try to open in logged out mode, it won't. In fact, the privacy policy page content will be replaced with poorly formatted HTML.

### WordPress Environment

PHP 8.3, OpenLiteSpeed, Ubuntu 22.04x64

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Changing team assignment, apologies if we got it wrong ...

**Comment by adrianduffell** [comment]
Hi @thegulshankumar, thanks for reporting the issue. We think you're right -- the privacy policy page should be excluded from the coming soon protection. We'll work on a fix. 

Please let me know if you need a workaround in the meantime.
