### ISSUE TITLE
Fix failing test relying on external resource

### ISSUE THREAD

**Issue by dmallory42** [woothemes/woocommerce#50167]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While wrangling the `9.1` release, it was pointed out that we have a flaky test: 
https://github.com/woocommerce/woocommerce/actions/runs/9896003577

Which looks to have been introduced in this PR: https://github.com/woocommerce/woocommerce/pull/49234

It seems the following test relies on an external resource (a JSON spec file of payment gateways), which should be mocked for the purposes of the test:

```
1) WC_Admin_Tests_PaymentGatewaySuggestions_Init::test_empty_suggestions
112
Failed asserting that 23 matches expected 24.
```

### Expected behavior

All tests should pass, and shouldn't rely on the external resource, rather we should mock the external request.

### Actual behavior

Test is failing because a new payment method has been added to the suggestions list defined here: https://github.com/woocommerce/woocommerce/blob/3d15fa689880c594a2aeb31de2b7ef70f766c881/plugins/woocommerce/src/Admin/Features/PaymentGatewaySuggestions/PaymentGatewaySuggestionsDataSourcePoller.php/#L17-L22

### Steps to reproduce

1. Run `npm run test`
2. Test `WC_Admin_Tests_PaymentGatewaySuggestions_Init::test_empty_suggestions` should fail.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dmallory42** [comment]
@anu-rock tagging you as this issue should be on @woocommerce/moltres's radar. 🙂

**Comment by anu-rock** [comment]
@dmallory42 Thanks for the report! I'll add it to our backlog.
