### ISSUE TITLE
Latest Woocommerce-paypal-payments Plugin breaks entire Wordpress Instance

### ISSUE THREAD

**Issue by clusterzx** [woothemes/woocommerce#50177]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After Update to the newest Woocommerce-payments v8.0.0 the wocommerce-paypayl-payments Plugin breaks the entire Wordpress instance.

### Expected behavior

Work with newest version

### Actual behavior

Breaks site

`Ein Fehler vom Typ E_ERROR wurde in der Zeile 47 der Datei /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-blocks/extensions.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined function WooCommerce\PayPalCommerce\Blocks\wc_terms_and_conditions_page_id() in /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-blocks/extensions.php:47 Stack trace: #0 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(132): WooCommerce\PayPalCommerce\Blocks\BlocksModule->WooCommerce\PayPalCommerce\Blocks\{closure}() #1 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}() #2 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}() #3 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}() #4 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(144): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}() #5 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(74): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeExtension() #6 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php(318): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get() #7 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}() #8 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory() #9 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php(77): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get() #10 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}() #11 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory() #12 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeContainer.php(53): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get() #13 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(61): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeContainer->get() #14 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(161): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}() #15 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(128): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->invokeGenerator() #16 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(62): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->getCached() #17 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php(511): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->get() #18 /var/www/html/wp-includes/class-wp-hook.php(324): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}() #19 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters() #20 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(94): apply_filters() #21 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(76): WC_Payment_Gateways->init() #22 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(49): WC_Payment_Gateways->__construct() #23 /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-features.php(271): WC_Payment_Gateways::instance() #24 /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php(1583): WC_Payments_Features::is_woopay_direct_checkout_enabled() #25 /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php(599): WC_Payments::maybe_init_woopay_direct_checkout() #26 /var/www/html/wp-includes/class-wp-hook.php(324): WC_Payments::{closure}() #27 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #28 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action() #29 /var/www/html/wp-settings.php(630): do_action() #30 /var/www/html/wp-config.php(98): require_once('...') #31 /var/www/html/wp-load.php(50): require_once('...') #32 /var/www/html/wp-blog-header.php(13): require_once('...') #33 /var/www/html/index.php(17): require('...') #34 {main} thrown`

### Steps to reproduce

https://github.com/woocommerce/woocommerce-paypal-payments/issues/2481
https://github.com/woocommerce/woocommerce-paypal-payments/issues/2482

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL):
WC Version: 9.1.4
Legacy REST API Package Version: Auf dieser Website ist das alte REST-API-Plugin nicht installiert.
Action Scheduler Version: ✔ 3.8.0
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 8.1.2-1ubuntu2.18
PHP Post Max Size: 25 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.4
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 32.85MB
Datenbank-Datengröße: 23.57MB
Datenbank-Indexgröße: 9.28MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 4.05MB + Index: 3.64MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 2.06MB + Index: 1.38MB + Engine InnoDB
wp_cky_banners: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cky_cookies: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_easywpsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Daten: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_runs: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_triggers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Daten: 3.27MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Daten: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Daten: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Daten: 0.23MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Daten: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_tags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 6.08MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Daten: 1.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Daten: 2.25MB + Index: 0.06MB + Engine InnoDB
wp_storeabill_document_attachmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_document_attachments: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_storeabill_document_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_document_items: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_document_notices: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_storeabill_documentmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_storeabill_documents: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforms_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payment_meta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Daten: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Daten: 1.33MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 29
document_template: 5
mailpoet_page: 1
nav_menu_item: 8
page: 14
post: 1
product: 4
product_variation: 7
revision: 57
shop_coupon: 5
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 1
wp_template_part: 2
wppopups: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Starter Templates: von Brainstorm Force – 4.3.9
CookieYes | GDPR Cookie Consent: von CookieYes – 3.2.5
Easy WP SMTP: von Easy WP SMTP – 2.3.2
Google for WooCommerce: von WooCommerce – 2.8.0
Klarna Payments for WooCommerce: von klarna – 3.5.4
MailPoet Premium: von MailPoet – 4.58.0
MailPoet: von MailPoet – 4.58.0
Pinterest für WooCommerce: von WooCommerce – 1.3.25
TikTok: von TikTok – 1.2.8
Spectra: von Brainstorm Force – 2.14.1
WooCommerce.com Update Manager: von Automattic – 1.0.3
Germanized für WooCommerce Pro: von vendidero – 4.0.0
Germanized für WooCommerce: von vendidero – 3.17.1
WooPayments: von WooCommerce – 8.0.0
WooCommerce: von Automattic – 9.1.4
WP Encryption - One Click SSL & Force HTTPS: von WP Encryption SSL HTTPS – 7.4.0
WP Mail Logging: von WP Mail Logging Team – 1.12.0
WP Rollback: von WP Rollback – 2.0.7

### Inactive Plugins (8) ###

Akismet Anti-spam: Spam Protection: von Automattic - Anti-spam Team – 5.3.3
DHL Shipping Germany for WooCommerce: von DHL – 3.7.1
eCommerce Companion: von sellerthemes – 8.1.5
Hello Dolly: von Matt Mullenweg – 1.7.2
Jetpack: von Automattic – 13.6
WooCommerce PayPal Payments: von WooCommerce – 2.8.2
WooCommerce Shipping & Tax: von WooCommerce – 2.7.0
WP Mail SMTP: von WP Mail SMTP – 4.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 147 kB

### WC Pages ###

Shop-Basis: #57 - /shop/
Warenkorb: #163 - /warenkorb/ -  Enthält den woocommerce/cart-Block
Kasse: #14 - /kasse/ -  Enthält den woocommerce/checkout-Block
Mein Konto: #15 - /mein-konto/
Allgemeine Geschäftsbedingungen: #225 - /agb/

### Theme ###

Name: Astra
Version: 4.7.3
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.0.0
Connected to WPCOM: Ja
WPCOM Blog ID: 233268232
Account ID: acct_1PMQKBCMbiHEANmA
Payment Gateway: ❌ Einrichtung erforderlich
Test Mode: Deaktiviert
Enabled APMs: card
WooPay: Nicht berechtigt
Apple Pay / Google Pay: Aktiviert (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Aktiviert
Auth and Capture: Aktiviert
Documents: Aktiviert
Logging: Deaktiviert

### MailPoet ###

Sending Method: SMTP
Send all site's emails with: Standard-WordPress-Versandmethode
Task Scheduler method: Action Scheduler
Cron ping URL: https://smarden.io?mailpoet_router&endpoint=cron_daemon&action=ping

### Klarna Payments Request Log ###

No Klarna Payment errors: 

### Klarna Countries ###

Production Countries: AU
Test Countries: No countries selected

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-01 15:40:53 +02:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Complete: 7.841
Oldest: 2024-06-30 17:51:56 +0200
Newest: 2024-07-31 17:43:07 +0200

Failed: 129
Oldest: 2024-05-19 18:01:56 +0200
Newest: 2024-07-31 17:28:10 +0200

Pending: 9
Oldest: 2024-07-31 17:45:07 +0200
Newest: 2024-08-01 12:42:45 +0200

### Status report information ###

Generated at: 2024-07-31 17:43:52 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Thanks for reporting. This repository is for WooCommerce Core. There is [an issue](https://github.com/Automattic/woocommerce-payments/issues/9195) (now resolved) for this in the WooPayments repository.
