### ISSUE TITLE
Review count not updating on the frontend of the product page when adding review through the product edit page manually

### ISSUE THREAD

**Issue by sreeragp7** [woothemes/woocommerce#50191]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am writing to report a bug I encountered while using the product edit page in our application. When I manually add a review to a product that does not have any existing reviews through the backend, the review count below the product title on the frontend does not update. However, if I add a review from the frontend first and then add a review through the backend, the count updates correctly.

### Expected behavior

The review count should update immediately below the product title on the frontend whenever a review is added, regardless of whether it is added through the backend or frontend.

### Actual behavior

The review count does not update when a review is manually added through the backend if the product initially has no reviews. The count only updates correctly when a review is first added through the frontend.

### Steps to reproduce

Select a product that has no existing reviews.
Manually add a review to the product through the product edit page in the backend.
Observe that the review count below the product title on the frontend remains unchanged.
Add a review to the same product from the frontend.
Add another review through the backend.
Observe that the review count now updates correctly.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://demo8.wtdev.xyz
Site address (URL): https://demo8.wtdev.xyz
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.62 (Debian)
PHP Version: 8.0.30
PHP Post Max Size: 499 MB
PHP Time Limit: 10
PHP Max Input Vars: 2500
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.5.25-MariaDB-deb11-log
Max Upload Size: 499 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.1
WC Database Prefix: wp_
Total Database Size: 198.02MB
Database Data Size: 125.16MB
Database Index Size: 72.86MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.22MB + Index: 0.23MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 1.64MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.02MB + Index: 0.56MB + Engine InnoDB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 0.52MB + Index: 0.45MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_csv_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 5.50MB + Index: 4.61MB + Engine InnoDB
wp_duplicator_packages: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_icl_background_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 2.52MB + Index: 8.02MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
wp_import_detail_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_import_log_detail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_import_postID: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_iwp_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 1.33MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mail_catcher_logs: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.06MB + Index: 0.14MB + Engine InnoDB
wp_parcelpanel_courier: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
wp_parcelpanel_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_parcelpanel_tracking: Data: 0.03MB + Index: 0.05MB + Engine InnoDB
wp_parcelpanel_tracking_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_postmeta: Data: 69.50MB + Index: 25.08MB + Engine InnoDB
wp_posts: Data: 17.03MB + Index: 13.97MB + Engine InnoDB
wp_smackcsv_file_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smackuci_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.22MB + Index: 0.36MB + Engine InnoDB
wp_terms: Data: 0.28MB + Index: 0.36MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_term_taxonomy: Data: 0.36MB + Index: 0.25MB + Engine InnoDB
wp_ultimate_csv_importer_acf_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ultimate_csv_importer_mappingtemplate: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ultimate_csv_importer_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ultimate_csv_importer_shortcode_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ultimate_post_entries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.22MB + Index: 0.45MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 3.31MB + Index: 2.39MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 4.42MB + Index: 9.38MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfpklist_template_data: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpie_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wtmgdp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_email_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wt_mgdp_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_mgdp_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_pf_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_pf_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_pf_facebook_sync: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_pf_fbsync_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 3.45MB + Index: 1.39MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.28MB + Index: 0.39MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

attachment: 22883
iwp-importer: 1
page: 8
polylang_mo: 2
post: 2
product: 4540
product_variation: 2059
revision: 28
shop_coupon: 4
shop_order: 73
shop_subscription: 9
wc_booking: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

Advanced Custom Fields: by WP Engine – 6.2.1
ARI Adminer: by ARI Soft – 1.2.3
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.38
Code Snippets: by Code Snippets Pro – 3.6.4
WordPress Comments Import & Export: by WebToffee – 2.3.6
CookieYes | GDPR Cookie Consent: by CookieYes – 3.2.5
Duplicator: by Duplicator – 1.5.9
Products & Order Export for WooCommerce: by WPFactory – 2.0.8
Import and export users and customers: by codection – 1.24.6
Import WP: by James Collings  – 2.11.4
Jetpack: by Automattic – 13.5
LitCommerce: by LitCommerce – 1.1.6
LitExtension: Shopping Carts to WooCommerce: by Litextension – 1.2.0
Object Cache Pro: by Rhubarb Group – 1.20.2
Parcel Panel Order Tracking for WooCommerce: by Parcel Panel – 4.2.1
Plugin Check (PCP): by WordPress Performance Team and Plugin Review Team – 1.0.1
WooCommerce PDF Invoices, Packing Slips, Delivery Notes and Shipping Labels: by WebToffee – 4.5.3
Product Import Export for WooCommerce: by WebToffee – 2.4.5
Stars Rating: by Fahid Javid – 4.0.2
Import Export WordPress Users and WooCommerce Customers: by WebToffee – 2.5.5
WooCommerce Additional Variation Images: by WooCommerce – 2.1.0
WooCommerce Brands: by WooCommerce – 1.6.30
WooCommerce Composite Products: by WooCommerce – 8.7.5
WooCommerce - Store Exporter: by Visser Labs – 2.7.2.1
WooCommerce Payments: by Automattic – 6.6.2 (update to version 8.0.1 is available)
WooCommerce Product Bundles: by SomewhereWarm – 6.6.0
WooCommerce Shipping & Tax: by WooCommerce – 2.6.1 (update to version 2.7.0 is available)
WooCommerce Subscriptions: by WooCommerce – 4.7.0
WooCommerce: by Automattic – 8.6.1 (update to version 9.1.4 is available)
WordPress Importer: by wordpressdotorg – 0.8.2
Yoast SEO: by Team Yoast – 22.8
WP File Manager: by mndpsingh287 – 7.1.6
WP Import Export Lite: by VJInfotech – 3.9.26
Mail logging - WP Mail Catcher: by James Ward – 2.0.5
WP Mail Logging: by SendLayer – 1.10.5
WebToffee WP Backup and Migration: by WebToffee – 1.5.0
WP phpMyAdmin: by Puvox.software – 5.2.1.02
WP Ultimate CSV Importer: by Smackcoders – 7.10.5
WP Ultimate Exporter: by Smackcoders – 2.5.0
Yoast SEO: WooCommerce: by Team Yoast – 15.8
WriteText.ai: by 1902 Software – 1.30.6
Order Import Export for WooCommerce Add-on: by WebToffee – 1.2.5
Product Import Export for WooCommerce Add-on: by WebToffee – 1.2.4
User Import Export for WooCommerce Add-on: by WebToffee – 1.1.9
Import Export for WooCommerce Wrapper: by WebToffee – 1.2.9

### Inactive Plugins (35) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Booster for WooCommerce: by Pluggabl LLC – 6.0.5
CTX Feed: by WebAppick – 4.5.1
GDPR Cookie Consent: by WebToffee – 3.0.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Import Export Suite for WooCommerce: by WebToffee – 1.2.7
Order Export & Order Import for WooCommerce: by WebToffee – 2.5.5
Order XML File Export Import for WooCommerce(BASIC): by WebToffee – 1.3.8
PayPal Express Checkout Payment Gateway for WooCommerce: by WebToffee – 1.3.7
PayPal Express Checkout Payment Gateway for WooCommerce ( Basic ): by WebToffee – 1.6.9
Polylang: by WP SYNTEX – 3.1.4
Product/Review CSV Import Export: by WebToffee – 3.8.5
Product Categories Import Export for WooCommerce Add-on: by WebToffee – 1.0.0
Product review Import Export for WooCommerce Add-on: by Webtoffee – 1.0.4
Rank Math SEO: by Rank Math – 1.0.67
Smart Coupons for WooCommerce  Pro: by WebToffee – 1.3.3
Stripe Payment Gateway for WooCommerce: by WebToffee – 3.3.8
Stripe Payment Plugin for WooCommerce: by WebToffee – 3.7.2
Subscription Import Export for WooCommerce Add-on: by WebToffee – 1.1.2
Subscriptions for WooCommerce: by WebToffee – 3.2.5
ThemeREX Addons: by ThemeREX – 2.7.3
User Role Editor: by Vladimir Garagulya – 4.61.2
WebToffee WooCommerce Product Feed & Sync Manager: by WebToffee – 2.1.7
WebToffee WooCommerce Product Feed & Sync Manager(Pro): by WebToffee – 1.1.2
WooCommerce Bookings: by WooCommerce – 1.15.40
WooCommerce Disability VAT Exemption: by WooCommerce – 1.4.5
WooCommerce Mailchimp Pro: by Saint Systems – 2.4.4
WooCommerce Multilingual: by OnTheGoSystems – 4.11.5
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.10
WPML Media: by OnTheGoSystems – 2.6.4
WPML Multilingual CMS: by OnTheGoSystems – 4.6.7
WPML String Translation: by OnTheGoSystems – 3.2.2
WPML Translation Management: by OnTheGoSystems – 2.10.6
WP Reset: by WebFactory Ltd – 1.95
WP WooCommerce Mailchimp: by Saint Systems – 2.4.8

### Dropin Plugins (1) ###

object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (1) ###

importwp-compatibility.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3 (update to version 2.3 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 6.6.2
Connected to WPCOM: Yes
WPCOM Blog ID: 224912963
Account ID: acct_1O3B76C4PjS4guJU
Payment Gateway: ❌ Needs setup
Test Mode: Enabled
UPE: Disabled
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Enabled
Logging: Disabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://demo8.wtdev.xyz
Subscription Statuses: wc-active: 6
wc-expired: 1
wc-pending: 2

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

other: wc-active: 2

### Payment Gateway Support ###

Cash on delivery: products

### Composite Products ###

Database Version: 8.7.5
Loopback Test: ✔
Template Overrides: –

### Product Bundles ###

Database Version: ❌ 6.15.3 - Database version mismatch.
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-08-01 09:15:49 +00:00
Options: ✔
Notes: 170
Onboarding: skipped

### Action Scheduler ###

Complete: 3,217
Oldest: 2024-07-01 09:40:51 +0000
Newest: 2024-08-01 06:43:18 +0000

Failed: 24
Oldest: 2023-02-22 07:09:05 +0000
Newest: 2024-07-31 11:17:08 +0000

Pending: 6
Oldest: 2024-08-01 12:44:00 +0000
Newest: 2024-08-03 13:07:05 +0000

### Status report information ###

Generated at: 2024-08-01 06:45:44 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
Thanks for opening this issue!

I’ve tried reproducing this bug using your steps:



https://github.com/user-attachments/assets/ef635628-5e37-430c-8f79-0c002b2b21f1


I’m unable to successfully reproduce the bug. This doesn’t mean there isn’t something happening, but it appears to be specific to your environment. Until we can reproduce this, there isn’t anything we can do to fix. For that reason, I’m going to close this issue, but please do leave a comment if you have additional information that you think will help us reproduce the issue. We will re-open if we’re able to replicate.

Thanks again for your report!
