### ISSUE TITLE
Analytics report: first default page is not stored with correct key in wp-data store

### ISSUE THREAD

**Issue by ecgan** [woothemes/woocommerce#50262]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When we visit an analytics report page such as Orders analytics at `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Forders&period=year&compare=previous_year`, the data will be fetched and stored in wp-data store `wc/admin/reports` like this:

<img width="669" alt="image" src="https://github.com/user-attachments/assets/d8afb507-e66d-4d4b-bcb2-a69b4bf75032">

Notice the key part with `"page": 1`.

Then, when we go to page 2, we will see the following in the wp-data store:

<img width="671" alt="image" src="https://github.com/user-attachments/assets/e490bf69-06f1-4dfb-9968-1fb0deb0f410">

Notice the key part with `"page": "2"`.

When we go back to page 1, we expect that there would be no API request and we would see the data in the table immediately, but in actual result, we see that there is another request being made and the result is stored like this:

<img width="676" alt="image" src="https://github.com/user-attachments/assets/cbc1603a-0a3c-481c-819e-1e7e41751f3a">

Notice the key part with `"page": "1"`.

The cause of the problem is because we are storing the first page data with `"page": 1` incorrectly; it should be  `"page": "1"` instead.

### Expected behavior

The data should be stored with  `"page": "1"`. There should be no API request when we go from page 2 back to page 1, and we should see the page 1 data immediately in the report table.

### Actual behavior

The data is stored with  `"page": 1`. There is an unnecessary API request when we go from page 2 back to page 1.

### Steps to reproduce

1. Go to `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Forders&period=year&compare=previous_year`
2. In the report table, go to page 2.
3. Go back to page 1.

### WordPress Environment

WordPress 6.5.5
WooCommerce 9.3.0-dev

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tomalec** [comment]
Thanks for catching that, fixed in https://github.com/woocommerce/woocommerce/pull/51396
