### ISSUE TITLE
Broken UI in shipping zone settings

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#50349]
### Issue Description

Multiple issues in shipping zone settings dropdown:

1. Checkboxes are not rendered properly: <p><img width="500" alt="image" src="https://github.com/user-attachments/assets/ac18f35e-4ac4-40dd-8dad-e5c93ec21e93"></p>

1. Special characters are not rendered properly. For example, `Saint Barthélemy`: <p><img width="500" alt="image" src="https://github.com/user-attachments/assets/22441b87-2a05-41a6-8825-ff96b3553e89">
</p>

### Acceptance criteria

1. Checkboxes should be rendered properly
2. Special characters should be rendered properly

**Comment by rjchow** [comment]
closed by #50593 and #50694
