### ISSUE TITLE
Clicking on the "Add payment methods" link in LYS congrat screen redirects to a blank page.

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#50346]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the user **hasn't completed the payment task and the store is eligible for WooPayments**, after the user launches the store and clicks on the "Add payment methods" link in the coming soon congrats screen, it goes to a blank page.

https://github.com/user-attachments/assets/db539666-64d0-4822-935b-e2fdd565e967

### Expected behavior

The user should be redirected to the WooPayments page to complete the payment task.

### Actual behavior

The user is redirected to the payments task page but it is blank because the page is not available when WooPayments task is shown.

### Steps to reproduce

1. Go to Core Profiler
2. Select a store country that is eligible for WooPayments
3. Install WooPayments in installation step
4. Complete Core Profiler
5. Go to WooCommerce > Home
6. Click on `Launch your store` task and launch the store
7. Click on the "Add payment methods" link in the coming soon congrat screen

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
> The user should be redirected to the WooPayments page to complete the payment task.

![Image](https://github.com/user-attachments/assets/d0371e7e-e411-456a-a060-60d776a58858)

Hey @adrianduffell On second thought, I think we need add a new step for the WooPayments task in the coming soon congrats screen since the existing one's copy is not suitable for the WooPayments task. Or we can update the `Add payment methods` link to the payment settings page instead of payments task page. What do you think?

**Comment by adrianduffell** [comment]
> Or we can update the Add payment methods link to the payment settings page instead of payments task page. What do you think?

Hey @chihsuan , I think this one sounds best. It's aligned with the new direction to have settings be the main hub for payments as seen in https://github.com/woocommerce/woocommerce/issues/49923
