### ISSUE TITLE
Add woocommerce_coming_soon option for all sites

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#50367]
## Issue Description

Extra queries are made on the front-end for live sites that don't have `woocommerce_coming_soon` option value present. This includes sites installed before v9.1 or those that skipped the core profiler.

Ideally for performance, all sites should have the `woocommerce_coming_soon` option value set with autoloading enabled. This would ensure the value can be retrieved with `get_option()` without an extra query. [As of WordPress 6.6, the option is implicitly autoloaded](https://make.wordpress.org/core/2024/06/18/options-api-disabling-autoload-for-large-options/) so the main change to make here is to ensure all sites have the option present.

Steps to reproduce

1. Install [AAA Option Optimizer](https://wordpress.org/plugins/aaa-option-optimizer/)
2. Install WooCommerce but stop at the core profiler intro screen
3. View the site front-end as a non-admin user (it should be in live mode)
4. Go to Tools > Option Optimizer > Requested options that do not exist
5. See `woocommerce_coming_soon` in list.

<img width="1792" alt="options that dont exist" src="https://github.com/user-attachments/assets/f6243778-6e0d-4161-9f3d-6f946358127f">

## Acceptance Criteria

* Add a db update routine to add the  `woocommerce_coming_soon` option  when it is not currently present. Potentially, this can be done with `add_option`, since it has logic to check whether the option already exists.
* The value should be `no`.

**Comment by dcx15** [comment]
It would be nice if there was a filter to completely disable this feature to minimize its calling on the front end of a site. Is such a filter planned? Or would you recommend disabling via remove_action on the front end hook instead?

**Comment by adrianduffell** [comment]
> It would be nice if there was a filter to completely disable this feature to minimize its calling on the front end of a site. Is such a filter planned? Or would you recommend disabling via remove_action on the front end hook instead?

@dcx15 Thanks for the suggestion! There is a feature flag that we discuss at the end of [this blog post](https://developer.woocommerce.com/2024/06/18/introducing-coming-soon-mode/), but we plan to remove it in 2025.

Our plans are instead to have the `woocommerce_coming_soon` option be equivalent to turning the feature on or off. When the option is set to `no`, the aim is for no impact on performance. To filter it, you could use the [in-built WordPress "pre option" filter](https://developer.wordpress.org/reference/hooks/pre_option_option/) and force the value to always be `no`. This would ensure a query is never made since the value is returned by code.

```
add_filter('pre_option_woocommerce_coming_soon', 'opt_out_woocommerce_coming_soon');

function opt_out_woocommerce_coming_soon() {
	return 'no';
}
```

I also have this available as plugin in the [gist here](https://gist.github.com/adrianduffell/8792c104401aaf2aa4fd7c43986d5e54).

Would this solve your needs?

> Or would you recommend disabling via remove_action on the front end hook instead?

This is also another possibility at the moment, but it might break if we change the front-end hook in the future (e.g. changing the name). I would recommend the pre option filter above to give you a full guarantee of backwards compatibility.

**Comment by dcx15** [comment]
@adrianduffell That's really helpful, thanks!
