### ISSUE TITLE
Autoload options for frequently used settings

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#50370]
## Issue Description

The following options are frequently used but are not autoloaded.

 * `woocommerce_allow_tracking`

### Steps to reproduce

1. Install [AAA Option Optimizer](https://wordpress.org/plugins/aaa-option-optimizer/)
1. Install WooCommerce but stop at the core profiler intro screen
1. View the site front-end as a non-admin user (it should be in live mode)
1. Go to Tools > Option Optimizer > Used, but not autoloaded
1. See the options

<img width="1792" alt="not autoloaded" src="https://github.com/user-attachments/assets/2986857a-6e8b-49d5-a2c8-8898be4b7d20">

## Acceptance Criteria

* In the install routine, ensure the above options are autoloaded. Logic [for this is here](https://github.com/woocommerce/woocommerce/blob/f8854e0a4f24995bc418c79bfee60fcc5223a789/plugins/woocommerce/includes/class-wc-install.php#L951-L960).
* Add a db update routine to enable autoload for these options on existing sites. Potentially this can be done with the [new  wp_set_option_autoload_values() function](https://make.wordpress.org/core/2023/10/17/new-option-functions-in-6-4/).

**Comment by kalessil** [comment]
@adrianduffell: do you have any specific team in mind for this issue?

**Comment by adrianduffell** [comment]
@kalessil Apologies, I missed adding the labels for my team 🤦

**Comment by adrianduffell** [comment]
After discussions internally, let's continue with `woocommerce_show_marketplace_suggestions` off and investigate why it is requested so often.
