### ISSUE TITLE
CYS: Remove description links from Assembler sidebar

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#50386]
In the main menu and submenus there is a link that redirects away from the experience.
![glWPVz.png](https://github.com/user-attachments/assets/7cd58fb3-84e6-4d27-bdcd-ed435b381c35)

We should remove them.

**Comment by tjcafferkey** [comment]
What about other links in the sidebar? Eg Styles

![Screenshot 2024-08-06 at 15 42 33](https://github.com/user-attachments/assets/f2edc240-0adc-410d-8c6b-b96d38e8c161)

**Comment by gigitux** [comment]
Yeah, in the submenus too!

**Comment by tjcafferkey** [comment]
Thanks! I updated this title and desc hope thats ok

**Comment by gigitux** [comment]
> Thanks! I updated this title and desc hope thats ok

Thanks! <3
