### ISSUE TITLE
Move `Grow your business` task to extended tasklist

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#50408]
### Issue Description

P2: pfwcF5-PP-p2#comment-519

Marketing task is a critical task prior launching a store. We can move it to "Things to do next" list.

### Acceptance criteria

1. Move marketing task to extended tasklist, but keep it at the top of the list.

**Comment by adrianduffell** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/50487
