### ISSUE TITLE
In the editor, the Checkout block's step titles have vertical scroll bars

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#50415]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the editor, the Checkout block's step titles have vertical scroll bars even though the text is on one line.
![image](https://github.com/user-attachments/assets/07557777-79e2-4c92-9df0-27a9786e88b5)

### Expected behavior

For the vertical scrollbars not to appear

### Actual behavior

In the editor, the Checkout block's step titles have vertical scroll bars

### Steps to reproduce

1. Go to the Checkout block in the editor (site editor or page editor is fine)
2. Notice the step titles have vertical scroll bars.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
This should be fixed with https://github.com/woocommerce/woocommerce/pull/48720
