### ISSUE TITLE
Able to create two products with the same GTIN, UPC, EAN or ISBN value through trashing and restoring.

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#50442]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The introduction of the GTIN, UPC, EAN or ISBN field in Woo 9.2 allowed us to enter a globally unique id to products. This means that no two products should have the same value, much like how SKU works. 

However, I was able to find a way to end up with two products having the exact same GTIN, UPC, EAN or ISBN by temporarily trashing a product, creating a new one with the same GTIN, UPC, EAN or ISBN, and then restoring the first product from the trash.

### Expected behavior

We're not sure yet on how to handle this scenario, but at the very least we should not end up with two products that have the same GTIN, UPC, EAN or ISBN when one of them was restored from trash. My suggestion would be to empty the GTIN, UPC, EAN or ISBN field of the product at the moment it's restored. Or maybe have an error notice saying that restoring it will cause duplicate unique id's, while at the same time preventing the restoration from proceeding.

### Actual behavior

You end up with two products that have the same GTIN, UPC, EAN or ISBN values.

### Steps to reproduce

1. Create a simple product with a GTIN, UPC, EAN or ISBN value of `012345678905`. The GTIN, UPC, EAN or ISBN field can be found in the Inventory tab of the product editor.
2. Trash that product.
3. Create another simple product that also has the same GTIN, UPC, EAN or ISBN (`012345678905`).
4. Restore the first product from trash.
5. Inspect both of their GTIN, UPC, EAN or ISBN values. You will notice that you now have two products with exactly the same GTIN, UPC, EAN or ISBN, which shouldn't be the case. We should only have 1 product that has that value.

### WordPress Environment

Reproducible in JN with Woo 9.2 beta.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by louwie17** [comment]
Good catch @rodelgc, I just tried to reproduce this with SKU as well, but it appears to add a `-1` if you restore a product with an existing SKU.
We should do the same thing for GTIN's.

**Comment by louwie17** [comment]
It appears that for SKU we call the `wc_product_force_unique_sku` when a product is untrashed: https://github.com/woocommerce/woocommerce/blob/ef74ccd496a21ae3b90ebecfaaa675d40ceae22f/plugins/woocommerce/includes/class-wc-post-data.php#L407

We should do something similar for the unique ID.
