### ISSUE TITLE
Bug Report: Product Attributes Not Displaying Terms in Submenu

### ISSUE THREAD

**Issue by beaushowcase** [woothemes/woocommerce#50441]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When adding attributes to products, the terms do not appear in the submenu under "Configure terms".

### Expected behavior

The terms for the product attributes should be visible in the submenu after clicking "Configure terms".

### Actual behavior

The terms are not displayed in the submenu after clicking "Configure terms".

### Steps to reproduce

1. Navigate to the WooCommerce Products section.
2. Add attributes to a product.
3. Open the attributes submenu.
4. Click on "Configure terms".

**Screenshots**
1. Attributes added: https://prnt.sc/0e-Tdxirgyjs
2. Configure terms click: https://prnt.sc/ThgazmSB3lkd
3. Terms not displayed: https://prnt.sc/jrexNW0GZmAG

### WordPress Environment

We use the WooCommerce System Status Report to help us evaluate the issue. Without this report, we won't be able to fully evaluate this issue.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
Thank you for opening this issue!

Just to clarify, are you reporting a regression or suggesting an improvement?

**Comment by shameemreza** [comment]
Reported here: 8581928-zen
Thread: https://wordpress.org/support/topic/bug-report-product-attributes-not-displaying-terms-in-submenu/#post-17946828

Note: It seems they overlooked the functionality of attributes. They might expect a configure option for the attribute terms as the attributes themselves.

**Comment by kmanijak** [comment]
Our suggestion would be to keep the "Attributes" highlighted. Is that what you had in mind @beaushowcase?
