### ISSUE TITLE
Super slow backend, failed requests towards "obw-free-extensions" endpoint

### ISSUE THREAD

**Issue by hogash** [woothemes/woocommerce#50453]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

These failed requests are slowing the backend:

![Markup on 2024-08-07 at 21-34-59](https://github.com/user-attachments/assets/e4d52c0d-706f-474f-9d30-48fe658d5cfa)

----

While accessing this URL https://woocommerce.com/wp-json/wccom/obw-free-extensions/4.0/extensions.json , these errors show up:

<img width="2778" alt="Markup 2024-08-07 at 21 35 48" src="https://github.com/user-attachments/assets/35e24017-77c8-4834-b1af-7e668b623d38">

and

<img width="2786" alt="Markup 2024-08-07 at 21 36 38" src="https://github.com/user-attachments/assets/fd1baac9-5248-4b9b-8c15-c91ebce71c2e">

### Expected behavior

Please cache them for at least 1 hour.

### Actual behavior

Not applicable.

### Steps to reproduce

Not applicable.

### WordPress Environment

Not applicable.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by freebeans** [comment]
I've been suffering from these same slow requests and it seems it started happening recently.

**Comment by denho** [comment]
There was an outage on the server at woocommerce.com that caused the malfunction of certain endpoints, used by WooCommerce. This has been resolved at the moment, and we are looking into measures to ensure it doesn't happen again. Including the changes in WooCommerce to minimize the negative effect of the remote server downtime on store admin performance. We are looking into reducing the number of requests and their timeout settings, caching and potentially offloading to a background job.

**Comment by freebeans** [comment]
Everything seems to be back no normal. Thank you, guys!

> potentially offloading to a background job

I'm not sure what these requests are all about, but this does make sense. Maybe a scheduled update event?

Since the issue has been resolved, I believe it could be closed, unless you want to keep track for a todo.
