### ISSUE TITLE
[Enhancement]: Allow declaring 3rd party blocks as supporting enhanced pagination to prevent page reload

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#50468]
### Describe the solution you'd like

If I understand [this function](https://github.com/woocommerce/woocommerce/blob/8aba7eebde3f4cc412972e4e518cc5f9b340b28c/plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-advanced-controls/utils.tsx#L14
) correctly, there is currently no way for a 3rd party block (not core or WooCommerce) to declare enhanced pagination support.

Is this the case? If so, wouldn't it be good to allow it?

### Additional context

I'm trying to place a YITH Add to Cart button in a Product Collection.

**Comment by kmanijak** [comment]
> If I understand [this function](https://github.com/woocommerce/woocommerce/blob/8aba7eebde3f4cc412972e4e518cc5f9b340b28c/plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-advanced-controls/utils.tsx#L14) correctly, there is currently no way for a 3rd party block (not core or WooCommerce) to declare enhanced pagination support.
> Is this the case? If so, wouldn't it be good to allow it?

Hi @asafm7, definitely! We plan to do so and there's an issue covering that: https://github.com/woocommerce/woocommerce/issues/48550. Also, thanks for raising the issue as it helps us prioritize some items like this one. We should pick it up soon.

To keep the backlog clean I'll go ahead and close this issue, please follow https://github.com/woocommerce/woocommerce/issues/48550 for further updates 🙌
