### ISSUE TITLE
Classic/shortcode checkout isn't translating the section title and email label.

### ISSUE THREAD

**Issue by shameemreza** [woothemes/woocommerce#50470]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you use the classic checkout block or shortcode, you will notice that the section titles for the "Contact information" and "Email address" field labels aren't getting translated. I've tried translating them using Loco Translate and the Say What plugin, but the translation still isn't happening.

![CleanShot 2024-08-08 at 15 07 22](https://github.com/user-attachments/assets/43f9a002-db85-43c4-9083-2e1562feba71)

Everything is in order with the Checkout Block. However, some text is still in English.

![CleanShot 2024-08-08 at 15 08 47](https://github.com/user-attachments/assets/d656cd86-714b-4667-9be0-6d1612be3063)

![process in gif](https://s12.gifyu.com/images/SDHam.gif)

### Expected behavior

Since the selected language is already 100% translated, some basic strings should be translated automatically into it.

### Actual behavior

If you use the classic checkout block or shortcode, you will notice that the section titles for the "Contact information" and "Email address" field labels aren't getting translated. I've tried translating them using Loco Translate and the Say What plugin, but the translation still isn't happening.

### Steps to reproduce

1. Open the checkout page and convert to classic checkout or insert the shortcode.
2. Change the language to non-English.
3. Check the checkout page.

### WordPress Environment

WordPress version: 6.6.1
WooCommerce version: 9.1.4
PHP version: 8.1.27
Theme: Tested on Storefront and Twnety Twenty-Four

## Reported Here:
* 8582294-zen
* https://wordpress.org/support/topic/contact-information-block-on-checkout-not-translated/

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
The first issue is likely coming from WooPayments as that section is added by them.

**Comment by wavvves** [comment]
Hi @shameemreza , thank you for reporting this. Besides the feedback given by @senadir, can you please change to another common language (eg French), make sure translations are updated (via Dashboard > Updates) and recheck those missing translations?

I tried to replicate your issue, but didn't find any issue ( I was using Portuguese though ), which may hint at missing translated strings for the desired language.

**Comment by shameemreza** [comment]
Hi @wavvves 

I ran another test using France and everything seems to be in order. Interestingly, I didn't have to deactivate any plugins.

![CleanShot 2024-08-15 at 09 09 30](https://github.com/user-attachments/assets/141466de-21cb-4a49-bdb7-b67414570371)

However, the situation remained the same when I used Ukrainian or another language. Interestingly, everything works perfectly once I disable WooPayments. The position of the checkout fields also changed. 

![CleanShot 2024-08-15 at 09 19 10](https://github.com/user-attachments/assets/e5055185-a5ec-439a-946b-b8d7940f3446)

So, as @senadir pointed out, WooPayments is causing an interference here.

**Comment by lynnjat7** [comment]
Another report of this here:
8647967-zen

and I have been able to duplicate it on my simple test site.

![yNQJeK.png](https://github.com/user-attachments/assets/d054495a-9f81-428f-ace2-6ed4948cebad)
this is with French set as my language.

Find my test site here:
https://numberseven.mystagingwebsite.com/

SSR of that site:
`
### WordPress Environment ###

WordPress address (URL): https://numberseven.mystagingwebsite.com
Site address (URL): https://numberseven.mystagingwebsite.com
WC Version: 9.2.2
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.22
PHP Post Max Size: 2 Go
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.13

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 Go
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() a échoué. Contactez votre fournisseur d’hébergement.

### Database ###

WC Database Version: 9.2.2
WC Database Prefix: wp_
Taille totale de la base de données: 53.86MB
Taille de la base de données: 32.47MB
Taille de l’index: 21.39MB
wp_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 18.05MB + Index : 12.19MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 7.02MB + Index : 6.03MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_gla_attribute_mapping_rules: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_gla_budget_recommendations: Données : 0.19MB + Index : 0.14MB + Moteur InnoDB
wp_gla_merchant_issues: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_gla_shipping_rates: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_gla_shipping_times: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_jetpack_sync_queue: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_automations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_automation_runs: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_mailpoet_automation_run_logs: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_mailpoet_automation_run_subjects: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_automation_triggers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_automation_versions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_custom_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_dynamic_segment_filters: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_feature_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletters: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_newsletter_links: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_newsletter_option: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_option_fields: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_posts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_segment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_newsletter_templates: Données : 4.52MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_scheduled_tasks: Données : 0.08MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_scheduled_task_subscribers: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_segments: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_sending_queues: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_settings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_statistics_bounces: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_mailpoet_statistics_clicks: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_statistics_forms: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_statistics_newsletters: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_statistics_opens: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_mailpoet_statistics_unsubscribes: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wp_mailpoet_stats_notifications: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_subscribers: Données : 0.02MB + Index : 0.23MB + Moteur InnoDB
wp_mailpoet_subscriber_custom_field: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_subscriber_ips: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_subscriber_segment: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_subscriber_tag: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_mailpoet_tags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_user_agents: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailpoet_user_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 0.47MB + Index : 0.06MB + Moteur InnoDB
wp_postmeta: Données : 0.14MB + Index : 0.06MB + Moteur InnoDB
wp_posts: Données : 0.09MB + Index : 0.06MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.09MB + Index : 0.03MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 42
mailpoet_page: 1
page: 8
post: 1
product: 18
product_variation: 7
revision: 4
shop_order_placehold: 4
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-spam: Spam Protection: par Automattic - Anti-spam Team – 5.3.3
Google for WooCommerce: par WooCommerce – 2.8.3
Jetpack: par Automattic – 13.8-a.5
MailPoet: par MailPoet – 5.0.1
WooCommerce Shipping & Tax: par WooCommerce – 2.7.0
WooCommerce: par Automattic – 9.2.2

### Inactive Plugins (2) ###

Jetpack Protect: par Automattic - Jetpack Security team – 3.0.0
WooPayments: par WooCommerce – 8.0.2

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 1 Mo

### WC Pages ###

Base de la boutique: #8 - /shop/
Panier: #9 - /cart/ -  Contient le bloc woocommerce/cart
Commander: #10 - /checkout/ -  Contient le bloc woocommerce/checkout
Mon compte: #11 - /my-account/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Cakely
Version: 1.0.3
Author URL: https://automattic.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ❌ Non déclaré

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Méthode d’envoi par défaut de WordPress
Task Scheduler method: Action Scheduler
Cron ping URL: https://numberseven.mystagingwebsite.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-25 16:03:19 -04:00
Options: ✔
Notes: 75
Onboarding: completed

### Action Scheduler ###

Terminé: 25 752
Oldest: 2024-07-24 13:53:38 -0400
Newest: 2024-08-24 13:50:41 -0400

Échoué: 1
Oldest: 2024-05-29 12:07:20 -0400
Newest: 2024-05-29 12:07:20 -0400

En attente: 3
Oldest: 2024-08-24 13:51:20 -0400
Newest: 2024-08-24 18:41:18 -0400


### Status report information ###

Generated at: 2024-08-24 13:51:04 -04:00
`

**Comment by mikejolley** [comment]
Generally, these types of issue are caused by missing translations on .org, thats why it only impacts certain languages. When translations get updated, going to Dashboard > Updates and clicking the link to update translations will fix things. Note also that some content (like the form steps) can be manually changed by editing the block.

As for the sidebar/totals area localisation, that is a separate issue and was fixed in https://github.com/woocommerce/woocommerce/pull/50892 This will be fixed in the next point release.

Ill leave this open while the conflict with WooPayments is looked into.

**Comment by mikejolley** [comment]
It seems the untranslated sections are inserted by WooCommerce Payments. They are not being translated automatically because that plugin translation is not 100%:

https://translate.wordpress.org/projects/wp-plugins/woocommerce-payments/

Contact information translation:

https://translate.wordpress.org/projects/wp-plugins/woocommerce-payments/stable/es/default/?filters%5Bterm%5D=Contact+information&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

The textdomain in these cases is `woocommerce-payments`.

Since there is nothing to fix in cart/checkout blocks I will close this issue. Thanks.
