### ISSUE TITLE
Email is not sent to guest who has selected "create an account" box at checkout

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#50489]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Email to set user password is not sent when guest customer creates an order and "create an account" box has been selected at checkout

This was tested on `9.2 Beta, 9.1.4 and 9.0.2

### Expected behavior

Email should be sent to allow guest user to set password after an order is created and "create an account" box has been selected at checkout

### Actual behavior

Email to set user password is not sent when guest customer creates an order and "create an account" box has been selected at checkout

### Steps to reproduce

1. Create a site with a product
2. Ensure a payment type is available - COD is fine for testing purposes
3. Ensure WooCommerce > Settings > Account & Privacy has `Allow customers to create an account during checkout` checked
4. As a guest, add something to your cart and checkout.
5. Ensure you toggle the “create an account” box on. 
6. Place order and receive confirmation
7. Email is not received

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.0.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order_placehold: 4
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Jetpack: by Automattic – 13.7-beta
WooCommerce: by Automattic – 9.0.2 (update to version 9.1.4 is available)

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 88 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 59
Onboarding: -

### Action Scheduler ###

Complete: 12
Oldest: 2024-08-08 13:28:45 +0000
Newest: 2024-08-08 14:37:28 +0000

Failed: 1
Oldest: 2024-08-08 13:29:49 +0000
Newest: 2024-08-08 13:29:49 +0000

Pending: 1
Oldest: 2024-08-09 13:28:45 +0000
Newest: 2024-08-09 13:28:45 +0000


### Status report information ###

Generated at: 2024-08-08 14:43:45 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
I wasn't able to reproduce this locally, I will try with a non-jurassic website.

**Comment by nigeljamesstevenson** [comment]
Note - this was recreated with `JN`, `Pressable` and a `local 9.0.4` site

**Comment by opr** [comment]
@mikejolley can you reproduce this?

**Comment by opr** [comment]
I reproduced on pressable.

**Comment by opr** [comment]
I installed [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) and I do see the emails are being sent, but they are not being delivered to my inbox. I'm not receiving _any_ Woo emails from my pressable site, so probably not specific to the account creation flow.

**Comment by mikejolley** [comment]
@opr Locally I found that:

- If password auto generation is on, new account email arrives before order confirmation email. Tested via Mailpit
- If password auto generation is off, you only get an order confirmation email

So the logic seems sound. Perhaps there is some kind of spam filtering or email sending restriction in place on the affect hosts.

**Comment by opr** [comment]
I tested on an external production site and it works OK. Closing this as it seems to be an issue with pressable/JN's email deliverability rather than Woo.
