### ISSUE TITLE
[Flaky Test] Update variations `can edit a variation` e2e test  

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#50532]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We witnessed a test failure on the WooCommerce 9.2 Beta QIT run when executing with the WooCommerce Points and Rewards

Variations tab > Create variable products – can edit a variation

If you take a peek at pb22l9-36s-p2, we can see test failure for WooCommerce Points and Rewards and a related comment with a suggested solution

**Comment by adimoldovan** [comment]
This was already fixed by https://github.com/woocommerce/woocommerce/pull/49729
