### ISSUE TITLE
Check and potentially fix timeout issues with remote specs requests

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#50538]
### Issue Description

P2: pdibGW-3xH-p2

During the breakdown of WCCOM API, it was found that some users have various loading times, reaching up to 60 seconds or more: p1723056887864719-slack-C07418EA0

However, @moon0326 and @psealock have identified that the default timeout for [`wp_remote_get`](https://github.com/WordPress/wordpress-develop/blob/6.6/src/wp-includes/class-wp-http.php#L163) call was 5 seconds.

I'm unsure if there are other factors at play, we'll need to identify them and ensure that remote calls timeouts are 5 seconds.

@bor0 also suggested (p6JqRr-cZQ-p2#comment-18599) to go through these references and ensure the timeouts are 5 seconds:

> I [still see a few references](https://href.li/?https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce+%22woocommerce.com%2Fwp-json%22&type=code) to wp_remote_get and wp_safe_remote_get without timeout (this might not be an issue since the [default is 5 seconds](https://href.li/?https://github.com/WordPress/wordpress-develop/blob/9f09c574c0ac64041c81760f10646994d21ce49d/src/wp-includes/class-wp-http.php#L163)) arg or caching. Just to be on the safe side for the future, should we go through those as well? We also may want to go through [DataSourcePoller](https://href.li/?https://github.com/woocommerce/woocommerce/blob/ff347bdcd489bcf1c152c49628e228fa6d567ce7/plugins/woocommerce/src/Admin/RemoteSpecs/DataSourcePoller.php#L199-L208).

### Acceptance criteria

1. Investigate and confirm if the timeouts for all remote spec calls are 5 seconds
2. If not, fix to ensure it is 5 seconds

**Comment by ilyasfoo** [comment]
Quick debug: After deleting all transients with `wp transient delete --all` and `var_dump($data_sources);` [here](https://github.com/woocommerce/woocommerce/blob/8eaa9807941eb61054ad4bc8b7b604950bee782b/plugins/woocommerce/src/Admin/RemoteSpecs/DataSourcePoller.php#L145), it seems WoocommercePayments task calls a read multiple times in a single request:

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/38e21580-6965-4bc5-8356-f61dfe0da344">

It's possible that this is the cause of the extended loading time, but I haven't looked at everything thoroughly.

**Comment by adrianduffell** [comment]
I think the default value of `5` is appropriate. Perhaps it is better to check we haven't set any timeouts larger than that 🤔 

> It's possible that this is the cause of the extended loading time, but I haven't looked at everything thoroughly.

Nice find! This seem quite plausible between marketing task and payments task.

**Comment by psealock** [comment]
> Quick debug: After deleting all transients with wp transient delete --all and var_dump($data_sources); [here](https://github.com/woocommerce/woocommerce/blob/8eaa9807941eb61054ad4bc8b7b604950bee782b/plugins/woocommerce/src/Admin/RemoteSpecs/DataSourcePoller.php#L145), it seems WoocommercePayments task calls a read multiple times in a single request

As of https://github.com/woocommerce/woocommerce/pull/50521 when a request times out, the cached result is now an empty `array()` which means it won't retry a new request and will gather the cached result instead. A var dump of the `$data_sources` when viewing the payments task now shows a single call:

<img width="811" alt="image" src="https://github.com/user-attachments/assets/6ca19416-bbf4-4b5e-af3b-dc8cdaf380db">

The data poller uses [wp_remote_get](https://github.com/WordPress/wordpress-develop/blob/6.6/src/wp-includes/class-wp-http.php#L163) and it will default to 5 seconds.

https://github.com/woocommerce/woocommerce/blob/6fcc0f84904a3daf4b69941b21abd8fd2a5731ec/plugins/woocommerce/src/Admin/RemoteSpecs/DataSourcePoller.php#L199

I confirmed default timeout for `wp_safe_remote_get` is also [5 seconds](https://developer.wordpress.org/reference/classes/wp_http/).

I checked the code base for [references](https://href.li/?https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce+%22woocommerce.com%2Fwp-json%22&type=code) to woocommerce.com endpoints to see if errors cause unnecessary retries either explicitly or by reading a non-existent cached value.

Marketing suggestions does retry, but uses Queue to schedule another attempt in one day's time:

https://github.com/woocommerce/woocommerce/blob/0468bdbe82b2ebb0d3c8ec04bdb7c840b3e7de3b/plugins/woocommerce/includes/admin/marketplace-suggestions/class-wc-marketplace-updater.php#L79-L82

Another potential is `OnboardingProducts` that does not set the transient on error. Code calling this function will make a new request every time its run. The solution here will be to set the default value into a short lived transient when an error occurs. However, this code is called by the `purchase` task which appears (to me) to be unreachable code. @adrianduffell do you know if we've done away with the [Purchase task](https://github.com/woocommerce/woocommerce/pull/33178)?

https://github.com/woocommerce/woocommerce/blob/0468bdbe82b2ebb0d3c8ec04bdb7c840b3e7de3b/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingProducts.php#L99-L101

I think we can safely close this issue after making the change to `OnboardingProducts.php` or create another issue to remove the unreachable code if its no longer in use. 

cc @ilyasfoo

**Comment by adrianduffell** [comment]
> @adrianduffell do you know if we've done away with the https://github.com/woocommerce/woocommerce/pull/33178?

Yes, we have indeed stopped showing the Purchase task. We can remove it entirely.

**Comment by ilyasfoo** [comment]
Great sleuthing, @psealock! 👨‍🍳 

> I think we can safely close this issue after making the change to OnboardingProducts.php or create another issue to remove the unreachable code if its no longer in use.

I agree, we can close this issue.

> Yes, we have indeed stopped showing the Purchase task. We can remove it entirely.

I created an [issue](https://github.com/woocommerce/woocommerce/issues/50624) to remove these:

- [OnboardingThemes](https://github.com/woocommerce/woocommerce/blob/82af27814a5149f2a87624556273fa0d4863ef74/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingThemes.php#L18)
- [OnboardingProducts](https://github.com/woocommerce/woocommerce/blob/82af27814a5149f2a87624556273fa0d4863ef74/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingProducts.php#L16)
- [Purchase](https://github.com/woocommerce/woocommerce/blob/82af27814a5149f2a87624556273fa0d4863ef74/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Purchase.php#L13) task

Would you agree @psealock @adrianduffell?

**Comment by adrianduffell** [comment]
> Would you agree @psealock @adrianduffell?

Agree!

**Comment by psealock** [comment]
Thanks team! 

>I created an https://github.com/woocommerce/woocommerce/issues/50624 to remove these:

Perfect! With that I will close this issue as solved 🙇🏽
