### ISSUE TITLE
[DOC-BUG] Leave feedback about document link directs to 404 (old WooCommerce Blocks repo)

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#50534]
## Link to the Page/Section

> Provide a link to the specific page or section that you're referring to.
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/docs/products.md

## Description of the Suggestion

> Describe the changes you suggest to improve or correct the documentation. Be specific about any errors or areas of confusion you've identified.

the bottom section has a 
>🐞 Found a mistake, or have a suggestion? [Leave feedback about this document here.](https://github.com/woocommerce/woocommerce-blocks/issues/new?assignees=&labels=type%3A+documentation&template=--doc-feedback.md&title=Feedback%20on%20./src/StoreApi/docs/products.md)

This link is now a 404 and it should link to _this_ repo.

## Reason for the Suggestion

> Why do you believe this change will make the documentation clearer or more accurate?

nobody likes 404s :)

**Comment by wavvves** [comment]
Hi @helgatheviking , thank you for reporting this. I added it to the backlog with a note to search other cases.

**Comment by helgatheviking** [comment]
I did a search for that everywhere in the Store API folder. Fixed them all and the docu build file in #50539
