### ISSUE TITLE
Make `menu_task_count` safer

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#50533]
### Issue description

P2: pdibGW-3xy-p2

The [`menu_task_count`](https://github.com/woocommerce/woocommerce/blob/49109ea28708767b7b0b1c5e2f1665c08e52fcd0/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php#L431) runs a count of unfinished tasks. 

Some of tasks' status, including [WooPayments](https://github.com/woocommerce/woocommerce/blob/db5eb6baa63ef2cb2a1220c0718019121543b9d9/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/WooCommercePayments.php#L182) code path includes a remote endpoint query. This is expensive and potentially dangerous since an issue with the remote endpoint could break the entire wp-admin.

We should de-couple badge menu by having it cached.

The way we could do this is by having a code run in every task completion change to re-calculate the count in an async process, then store it in a transient, and then subsequently queried by the menu badge.

It is not critical for the badge to be accurate immediately.

### Acceptance criteria

1. De-couple `menu_task_count` from having to recalculate task completion

**Comment by chihsuan** [comment]
Hey @ilyasfoo It seems that we call `is_complete` method in several places. 

https://github.com/woocommerce/woocommerce/blob/03049e0d17f564688930eece358f0359e75afe8c/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php#L337-L340

https://github.com/woocommerce/woocommerce/blob/03049e0d17f564688930eece358f0359e75afe8c/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Task.php#L402-L404

Do you think decoupling the badge from the task completion status would be sufficient to solve the issue? 

Also, because the count of remaining tasks also depends on whether the task can be viewed or not, recalculating the count on every task completion change might not be the best solution. 🤔  I think we can probably calculate the count of completed tasks from `COMPLETED_OPTION` and subtract it from the total number of viewable tasks. What do you think?


```diff
	/**
	 * Return number of setup tasks remaining
	 *
	 * @return number
	 */
	public static function setup_tasks_remaining() {
		$setup_list = self::get_list( 'setup' );

-		if ( ! $setup_list || $setup_list->is_hidden() || $setup_list->has_previously_completed() || $setup_list->is_complete() ) {
+              if ( ! $setup_list || $setup_list->is_hidden() || $setup_list->has_previously_completed() ) {
			return;
		}

-		$remaining_tasks = array_values(
-			array_filter(
-				$setup_list->get_viewable_tasks(),
-				function( $task ) {
-					return ! $task->is_complete();
-				}
-			)
-		);

+             // Use woocommerce_task_list_tracked_completed_tasks option to calculate the remaining tasks count

		return count( $remaining_tasks );
	}
```

**Comment by ilyasfoo** [comment]
Good question, @chihsuan!

> It seems that we call is_complete method in several places.

Yes, but I think this is only runs when rendering homescreen with tasklist displayed, and they're run async. The surface area is smaller compared to the admin menu.

> Also, because the count of remaining tasks also depends on whether the task can be viewed or not, recalculating the count on every task completion change might not be the best solution. 🤔 I think we can probably calculate the count of completed tasks from COMPLETED_OPTION and subtract it from the total number of viewable tasks. What do you think?

Good thinking, but how would you calculate the number of viewable tasks? It seems at least [`AdditionalPayments.php`](https://github.com/woocommerce/woocommerce/blob/82af27814a5149f2a87624556273fa0d4863ef74/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php#L104) has exposure to a sync call for PaymentGatewaySuggestion spec.

> Do you think decoupling the badge from the task completion status would be sufficient to solve the issue?

If there's no code path that is without calling a sync remote spec, I believe it would be sufficient for the purpose of rendering menu badge. Since it's called on every wp-admin page, I think it's worth to decouple. Let me know if you have other suggestions!

**Comment by chihsuan** [comment]
> Good thinking, but how would you calculate the number of viewable tasks? It seems at least [AdditionalPayments.php](https://github.com/woocommerce/woocommerce/blob/82af27814a5149f2a87624556273fa0d4863ef74/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php#L104) has exposure to a sync call for PaymentGatewaySuggestion spec.

Since we will address that issue in https://github.com/woocommerce/woocommerce/issues/50543, I think we can just get viewable tasks by calling `get_viewable_tasks` method. 😀 


> If there's no code path that is without calling a sync remote spec, I believe it would be sufficient for the purpose of rendering menu badge. Since it's called on every wp-admin page, I think it's worth to decouple. Let me know if you have other suggestions!

Got it, that makes sense. 👍
