### ISSUE TITLE
 New Product Editor: Sticky Notifications on Variations Edit

### ISSUE THREAD

**Issue by alvarothomas** [woothemes/woocommerce#50545]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The variations tab on the new product editor gets sticky notifications while creating new variations and editing them.

### Expected behavior

The variations tab on the new product editor gets notifications that fade away after creating new variations and editing them.

### Actual behavior

<img width="933" alt="Screenshot 2024-08-05 at 17 09 29" src="https://github.com/user-attachments/assets/cac1d50b-a8aa-405e-adc6-0eb6181072d6">
<img width="922" alt="Screenshot 2024-08-05 at 17 09 15" src="https://github.com/user-attachments/assets/6b7d0f68-2d9e-4b32-8c60-8275ddc428f8">

### Steps to reproduce

PRE: New Product Editor is enabled under wp-admin/admin.php?page=wc-settings&tab=advanced&section=features and no product variations have been added until now.

1. Go to Products -> Add New (/wp-admin/admin.php?page=wc-admin&path=%2Fadd-product).
2. Click on "Variations" tab.
3. Add product variations and click on "Add".
4. Notice the notifications confirming the action.
5. Keep editing and adding variations.

### WordPress Environment

WP 6.6.1, PHP 8.1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kmanijak** [comment]
Hi @alvarothomas, thanks for raising this issue. Can you tell us what WooCommerce version you use? I couldn't reproduce it in WooCommerce 9.1.4 (the latest one). The notifications are merged into a single one there:

![Image](https://github.com/user-attachments/assets/84110790-e55b-48d5-8da7-2607637e4cae)

**Comment by nigeljamesstevenson** [comment]
Hi @kmanijak there is more context pb22l9-35a-p2#comment-3374 - this was tested on a specific T51 site using `9.2 Beta`.

@alvarothomas - can you test and see if the same occurs under `9.1.4`?
thanks!

**Comment by tjcafferkey** [comment]
@alvarothomas @nigeljamesstevenson I was also unable to reproduce this issue on `WC 9.2.3`. I'm going to close this issue for now, but please reopen it if you're able to reproduce, ideally with a screen recording too if possible.

![Image](https://github.com/user-attachments/assets/6deffa9a-7a6a-4275-b2d3-f0b15c8c7aae)

Thanks!
