### ISSUE TITLE
New Product Editor: Overlapping Extension Banner on Variations Tab (Copy & Delete Posts Extension)

### ISSUE THREAD

**Issue by alvarothomas** [woothemes/woocommerce#50548]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the New Product Editor, a 'Copy & Delete Posts' extension banner overlaps Variations tab content.

### Expected behavior

'Copy & Delete Posts' extension banner is visible but it does not overlap Variations tab content.

### Actual behavior

'Copy & Delete Posts' extension banner overlaps Variations tab content.

<img width="1120" alt="Screenshot 2024-08-05 at 17 06 16" src="https://github.com/user-attachments/assets/da6f8c47-af30-4b3f-bef6-f35f118d04a8">

### Steps to reproduce

PRE: New Product Editor is enabled under wp-admin/admin.php?page=wc-settings&tab=advanced&section=features and the Copy & Delete Posts Extension is installed and activated.

1. Go to Products -> Add New (/wp-admin/admin.php?page=wc-admin&path=%2Fadd-product).
2. Click on "Variations" tab.
3. Notice the Copy & Delete Posts Extension banner

### WordPress Environment

WP 6.6.1, PHP 8.1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kmanijak** [comment]
Thanks @alvarothomas for taking the time to submit this issue.

Could you confirm if it's Product Editor specific? Does this conflict/issue also appear on other WooCommerce Admin pages like `WooCommerce > Home` or `Analytics > Overview`?

**Comment by nigeljamesstevenson** [comment]
Hi @kmanijak there is more context pb22l9-35a-p2#comment-3374 - this was tested on a specific T51 site using 9.2 Beta.

@alvarothomas - can you also test to see if the same occurs under 9.1.4?
thanks!

**Comment by tjcafferkey** [comment]
Just following up on this, @nigeljamesstevenson were you able to check against other admin views? I'm just trying to understand whether this is a Product Editor specific issue or not.

**Comment by nigeljamesstevenson** [comment]
Apologies @tjcafferkey and @kmanijak for the delay in the response...

I just checked and the Copy and Delete Posts banner appears ok on `WooCommerce > Home` and `Analytics > Overview` i.e. there is not overlapping:
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/51c3ca35-202d-4e3e-9cc5-bd58f13be868">

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/31a5c7d4-a4d9-4491-a790-73afd65edcc7">

the overlap only seems to appear on the new product editor page:
<img width="972" alt="image" src="https://github.com/user-attachments/assets/274057aa-e5df-4c5b-9669-4c1785c78f9d">

It does not appear on the original product editor
