### ISSUE TITLE
Investigate other synchronous calls to remote endpoints

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#50543]
### Issue Description

P2: pdibGW-3xH-p2

It was discovered that the Marketing task and [WooCommercePayments task](https://github.com/woocommerce/woocommerce/blob/db5eb6baa63ef2cb2a1220c0718019121543b9d9/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/WooCommercePayments.php#L182) had synchronous calls to Remote Specs API fetch. Marketing task was [fixed](https://github.com/woocommerce/woocommerce/pull/50479), but there could be more remote endpoint calls that could potentially break wp-admin.

### Acceptance criteria

1. Investigate and ensure no other calls to external endpoints are synchronous
2. Fix if found

**Comment by chihsuan** [comment]
We also call the remote endpoint in AdditionalPayments task.

https://github.com/woocommerce/woocommerce/blob/9297409c5a705d1cd0ae65ec9b058271bd90851e/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php#L189-L202

**Comment by ilyasfoo** [comment]
Thanks for looking, @chihsuan!

I can't think of an easy fix since it makes sense for AdditionalPayments' logic to use the data.

I wonder if we could alternate method for remote specs which only uses the cached value and not start a sync remote call? 🤔

**Comment by ilyasfoo** [comment]
@adrianduffell, would you know if the `Set up additional payments` task in the extended tasklist is also removed for payments settings refresh? If so, perhaps we could use the default values too 🤔

**Comment by adrianduffell** [comment]
> would you know if the Set up additional payments task in the extended tasklist is also removed for payments settings refresh? 

@ilyasfoo  Yes! Indeed, there will only be one payments task after the payments setting refresh, and it will link to the new payments settings.

> If so, perhaps we could use the default values too

Sounds good to me!

**Comment by ilyasfoo** [comment]
@adrianduffell Awesome, thanks! I can pick this up if you haven't started working on it @chihsuan

**Comment by chihsuan** [comment]
@ilyasfoo I haven't started yet, so feel free to take it! 🙂

**Comment by ilyasfoo** [comment]
It seems there are 2 more WCCOM endpoints called synchronously, however they're not a remote spec:

1. [Wc-helper](https://github.com/woocommerce/woocommerce/blob/65ed125271a64172b815b89e1ba926eec48b501e/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php#L567-L582)
2. [Marketplace_Promotions](https://github.com/woocommerce/woocommerce/blob/65ed125271a64172b815b89e1ba926eec48b501e/plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php#L124)

From what I can tell, these are cached but is called in any wp-admin screen.

**Comment by ilyasfoo** [comment]
> Marketplace_Promotions

I [left a comment](https://github.com/woocommerce/woocommerce/pull/47262#discussion_r1719316345) in the PR that added marketplace query to get an opinion on whether it should be addressed or not.

> Wc-helper

It seems this is run when WordPress [does update check](https://github.com/woocommerce/woocommerce/blob/4af4389ef3bb5c8cbf3c3e32fe21b4cc9d632dff/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php#L64), which sometimes can be during a wp-admin request. The code is 7 years old and I think this is fine to leave as-is.
