### ISSUE TITLE
Product Details: weird effect when tabs are clicked

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#50550]
**Issue Description:**

During the review of #50495, @imanish003 noticed a weird effect when tabs are clicked on the Product Details block.

https://github.com/user-attachments/assets/f8494746-e0a2-41f1-9e5a-73aaae1e892d

I went further and double-checked all the possible scenarios:

### Product Details - minimal

https://github.com/user-attachments/assets/e2a6c6e6-e652-4a45-bd86-093d287274af

### Product Details - classic

https://github.com/user-attachments/assets/4e2aeaaf-0184-4df3-9085-2e5de658a405

## Classic Template

https://github.com/user-attachments/assets/1e21d280-7310-4c57-934c-66c9bc184454

@jarekmorawski, can you give us feedback on this? Do you think that it should work in this way? Thanks in advance!

**Comment by jarekmorawski** [comment]
I suppose the focus ring is displayed to assist with accessibility. I admit it doesn't look good and we should if we can hide it. Perhaps we could use the `:focus-visible` pseudo-class?
