### ISSUE TITLE
CI/Metrics: Drop the monorepo setup step

### ISSUE THREAD

**Issue by WunderBart** [woothemes/woocommerce#50623]
The Metrics job includes the `Install Monorepo` step, which takes >4 minutes to complete. The runner script itself does not require the entire monorepo to be set up, as it fetches and builds the compared plugin versions independently via the [`performance.js`](https://github.com/woocommerce/woocommerce/blob/c69e72d90e14aee1467fa4303d443bf0e8a80cf9/tools/compare-perf/performance.js) script. All we need to run the Metrics job is:

- `nvm`
- `node`
- `pnpm`
- Dependencies of the `compare-perf` package (`pnpm i --filter="compare-perf"`)

The main setup script ([`run-metrics.sh`](https://github.com/woocommerce/woocommerce/blob/31e78d8da8cf89b9d780d4cf12b58749d41ccf69/.github/workflows/scripts/run-metrics.sh)) already installs `nvm` and the deps of `compare-perf` package but it still relies on `pnpm` provided by the `Install Monorepo` step. To streamline the process, we can add the `npm install -g pnpm` step to `run-metrics.sh`, which will allow us to eliminate the `Install Monorepo` step, saving a significant amount of time.

**Comment by tammullen** [comment]
Can help with https://github.com/woocommerce/woocommerce/issues/49550 as well

**Comment by kalessil** [comment]
#49550 will cover this, hence closing this issue.
