### ISSUE TITLE
Remove OnboardingProducts, OnboardingThemes, and Purchase task

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#50624]
### Issue description

From this [discussion](https://github.com/woocommerce/woocommerce/issues/50538#issuecomment-2285116850), the following classes and all its references can be removed:

- [OnboardingThemes](https://github.com/woocommerce/woocommerce/blob/82af27814a5149f2a87624556273fa0d4863ef74/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingThemes.php#L18)
- [OnboardingProducts](https://github.com/woocommerce/woocommerce/blob/82af27814a5149f2a87624556273fa0d4863ef74/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingProducts.php#L16)
- [Purchase](https://github.com/woocommerce/woocommerce/blob/82af27814a5149f2a87624556273fa0d4863ef74/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Purchase.php#L13) task
### Acceptance criteria

1. Remove unused classes and its references and perform smoke test to ensure no regression 
2. Optionally, look for unused JS files corresponding to the purchase task and remove them as well

**Comment by adrianduffell** [comment]
Will there also be associated JS files to remove?

**Comment by ilyasfoo** [comment]
@adrianduffell  Good question, there should be JS files somewhere in tasklist and old onboarding wizard. By extension, perhaps we could remove the entire old onboarding wizard too 🤔

**Comment by adrianduffell** [comment]
> By extension, perhaps we could remove the entire old onboarding wizard too

@ilyasfoo Yeah, I think we need an issue to graduate the core profiler out of the feature flag and clean-up the old wizard 😅

**Comment by ilyasfoo** [comment]
Closing in favor of https://github.com/woocommerce/team-ghidorah/issues/352
