### ISSUE TITLE
WooCommerce Shipping promotional banner not showing on order page with HPOS

### ISSUE THREAD

**Issue by kallehauge** [woothemes/woocommerce#50653]
## Summary

Our WC Shipping promotional banner is not showing on order edit pages when HPOS is enabled, so we need to update `Automattic\WooCommerce\Internal\Admin\ShippingLabelBanner` to support HPOS.

## Context

https://github.com/woocommerce/woocommerce/pull/48704 mentions the banner and HPOS in context, but that's the only reference I've been able to find about it.

## Screenshot(s)

![Image](https://github.com/user-attachments/assets/5035a98d-00d4-4516-911d-2964de01345a)

**Comment by samnajian** [comment]
Core does the following check to decide to add the banner:

```
if ( 'shop_order' !== $post_type ) {
     return;
}
```
