### ISSUE TITLE
New Customer Account icon looks smaller than the previous icon

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#50667]
### Steps to reproduce

1. Install WC 9.1.4 and look at how the Customer Account icon looks next to the Mini-Cart icon.
2. Now update to WC 9.2.0-rc.1 and notice the new Customer Account icon looks smaller than the previous one.

WC 9.1 | WC 9.2
--- | ---
![Screenshot 9.1](https://github.com/user-attachments/assets/5feb9d37-90e2-4342-848f-8ef13511e0e9) | ![Screenshot 9.2](https://github.com/user-attachments/assets/c5e62934-b407-47ee-8070-58a04316987c)

In detail:

WC 9.1 | WC 9.2
--- | ---
![Screenshot 9.1](https://github.com/user-attachments/assets/ce29ace5-3177-4f80-b808-bcc9df0b6fb1) | ![Screenshot 9.2](https://github.com/user-attachments/assets/8ce709cf-27b6-4917-9113-400d94d28c06)

Even though it's probably only one pixel smaller at the top and another pixel smaller at the bottom of the image, the new icon looks a bit out of balance next to the Mini-Cart icon, IMO.

### Next steps

1. IMO, we should avoid changing the default icon on existing stores.
2. For new stores or stores that manually select the new icon, I think it should be slightly bigger. I guess that's quite subjective, but I feel the new icon feels a bit small next to the Mini-Cart icon. :smile: 

cc @albarin as I think you worked on this recently?

**Comment by albarin** [comment]
Hey @Aljullu, are you using any particular pattern to insert those two icons? which theme do you have enabled? TY!

**Comment by Aljullu** [comment]
> Hey @Aljullu, are you using any particular pattern to insert those two icons? which theme do you have enabled? TY!

The screenshots are with Twenty-Twenty Four, and the blocks are the ones which are added automatically with block hooks once you install WooCommerce. I didn't use any patterns.
