### ISSUE TITLE
Place continue button directly under extension cards when scrolling not required

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#50719]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
With the new sticky button in https://github.com/woocommerce/woocommerce/pull/50582, when a small amount of recommendations are shown on a small-size screen, the continue button sticks to the bottom of the screen instead of directly under the recommendations. It should only stick to the bottom of the screen when scrolling is required. This is evident using Fiji as store country.

### Current Behavior

<img width="1411" alt="fiji current" src="https://github.com/user-attachments/assets/8cd459ea-3be7-4c85-898d-55cf8b3949d2">

### Expected Behavior

<img width="1411" alt="fiji expected" src="https://github.com/user-attachments/assets/073c8f33-449c-4f32-b446-ced57a6b7468">

**Comment by chihsuan** [comment]
Fixed by https://github.com/woocommerce/woocommerce/pull/50727
