### ISSUE TITLE
Not able to view last row of  extensions in core profiler on small screens

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#50718]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

With the new sticky button on small screens in https://github.com/woocommerce/woocommerce/pull/50582, overflown content is hidden behind the continue button when scrolling to the bottom. It should be possible to scroll so that you can view the entirety of the extension cards in the last row.

https://github.com/user-attachments/assets/de33f1e5-0855-46a0-bb67-a39319f3b350

**Comment by chihsuan** [comment]
Fixed by https://github.com/woocommerce/woocommerce/pull/50727
