### ISSUE TITLE
site visibility option not showing in woocommerce setting

### ISSUE THREAD

**Issue by Shiponali2002** [woothemes/woocommerce#50728]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

woccommerce settings site visibility option is not working

### Expected behavior

want to more option( live/ comming son)

### Actual behavior

but show me blank page

### Steps to reproduce

1. wordpress log in
2. go to woocommerce setting
3. select site visibility
4. there are no option for select

### WordPress Environment

solve please

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adrianduffell** [comment]
Hi @Shipon360, I'm sorry it seems something has gone astray for you here. 

We would need more information from you to reproduce this. Do you have any error logs that point to the problem?

You may also be best to receive help from the [support forum](https://wordpress.org/support/plugin/woocommerce/) to help diagnose the problem.

**Comment by jas8522** [comment]
I had this happen as well - it was caused by the "MIsc WooCommerce Tweaks" in Docket Cache - can be disabled in the Docket settings. I have reported it to them :)
