### ISSUE TITLE
Populate react-powered main payments settings screen

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#50721]
Replicate the existing main payments settings screen using React, as much as possible (timeboxed to 2 days)

## Acceptance criteria

* Populate the react component created in https://github.com/woocommerce/woocommerce/issues/49927
* Pre-fill WooPayments
* Fetch payment gateways from data store
* Don't include re-order functionality
* Don't include 3-dots menu on WooPayments row

![Image](https://github.com/user-attachments/assets/a7874fc6-c201-444a-a5a1-bc990f84c1c1)

**Comment by vbelolapotkov** [comment]
@adrianduffell I see this issue is routed to Transact during triage. I suppose you'll handle it during the ongoing project? 

cc @anu-rock, because otherwise I'd routed to you :)

**Comment by adrianduffell** [comment]
Thanks @vbelolapotkov, it should have been with me. Looks like I missed adding the team label when creating the issue 😅 

It is close to completion in https://github.com/woocommerce/woocommerce/pull/50825!
