### ISSUE TITLE
[Remote Specs] Ensure endpoints and evaluation of results only happens in admin

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#50773]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

[In this discussion](https://github.com/woocommerce/woocommerce/issues/50714) its been discovered that some remote specs are gathered and evaluated on front end requests, slowing down time to first byte (TTFB). For example, see [PaymentGatewaySuggestions](https://github.com/woocommerce/woocommerce/blob/50900d9d4e58e38baea0ee5f6f4a9f12f34f4941/plugins/woocommerce/src/Admin/Features/PaymentGatewaySuggestions/Init.php#L47).

## Acceptance Criteria

Ensure no Remote Specs logic is executed on non-admin screens.

**Comment by chihsuan** [comment]
Confirmed the issue has been fixed in https://github.com/woocommerce/woocommerce/pull/51161
