### ISSUE TITLE
Add site visibility settings confirmation modal 

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#50778]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We received feedback to add safety around changing a site from live to coming soon. We'll try adding a confirmation prompt when the setting is changed like this.

![image](https://github.com/user-attachments/assets/f5a3ae1f-ff7a-4407-aaab-97dd29533c28)

[Figma](https://www.figma.com/design/0BWMerqRR1f468EwC7g5tg/LYS?node-id=3674-22105&t=gQZVBG8flvIj9Qsx-4)

## Acceptance Criteria

* Display confirmation on site visibility settings screen when changing value from live to coming soon.

**Comment by ilyasfoo** [comment]
Done in https://github.com/woocommerce/woocommerce/pull/50759
