### ISSUE TITLE
Checkout block: Improvement of the positioning of the summary block

### ISSUE THREAD

**Issue by orschiro** [woothemes/woocommerce#50797]
Hi team, 

Currently, the summary block is shown at the top when viewed on mobile.

<img src="https://github.com/user-attachments/assets/fe975741-00b5-489d-b206-777de6379c40" height="400">

This is very confusing because it tells the customer there are no sipping options available. Obviously because entering the shipping address comes after the summary block. This can be very confusing to the customer.

There are two ways to move the summary block to the bottom.

**CSS:**

```
.is-mobile .wc-block-checkout__main {

order: 0!important;
}
```

**PHP:**

```
function tl67t_custom_woocommerce_checkout_css() {
if(is_checkout()){
?>
    <style type="text/css">
        @media only screen and (max-width: 768px) {
.wc-block-checkout__sidebar {
                order: 2 !important;
            }
.wc-block-checkout__main {
                order: 1 !important;
            }
        }
    </style>
<?php
}
}
add_action('wp_head', 'tl67t_custom_woocommerce_checkout_css', 99);
```

However, both have the same disadvantage. The summary block is shown even after the final purchase button, which looks very ugly and unusual. 

![image](https://github.com/user-attachments/assets/4f76e203-4b72-4364-9edd-6db1007f7083)

What are your thoughts? 

How can we improve this?

Thank you!

**Comment by senadir** [comment]
This issue describes a solution that we're aiming to ship to fix that

https://github.com/woocommerce/woocommerce/issues/45285

This issue describes several fixes to the copy of that section so it indicates the state better

https://github.com/woocommerce/woocommerce/issues/50558

**Comment by orschiro** [comment]
Thank you!

What do you suggest next?

Subscribe to twose two mentioned issues or is there anything else I can contribute?

20.08.2024 15:51:00 Seghir Nadir ***@***.***>:

**Comment by wavvves** [comment]
Hi @orschiro, thanks for suggesting this. I would say it would be best to wait for those changes @senadir mentioned ship and then reevaluate this one.

Of course contributions are always welcome, please do provide some feedback on the other issues, or even open/contribute to a PR ☺️

**Comment by orschiro** [comment]
I'm going to wait for those changes then.
Thank you! :)

24.08.2024 03:06:04 Paulo Arromba ***@***.***>:

**Comment by mikejolley** [comment]
Since this issue is covered by https://github.com/woocommerce/woocommerce/issues/45285 I will mark this one closed. Thank you!
