### ISSUE TITLE
WooCommerce 9.2 conflict with ACF select2 fields

### ISSUE THREAD

**Issue by mattgrshaw** [woothemes/woocommerce#50847]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi folks!

I'm one of the developers on the ACF team and wanted to report a potential conflict with WooCommerce 9.2.

Woo 9.2 appears to have dropped support for select2 in favor of selectWoo. In doing so, it appears that `select2` is still registered via `wp_register_script()`, but it now points to the selectWoo library:
https://github.com/woocommerce/woocommerce/pull/48731/files#diff-93e330e41dcee0a7211c92b86b52ba9c4c1f2c0424457958abdfc8b2fb45e659R152

We have some logic in ACF that checks the registered version of select2 to enqueue different scripts based on the registered version - this is mainly done to avoid conflicts between plugins registering select2 v3 and v4. But since `select2` is registered with the `selectWoo` library (currently v1), this fails and we end up enqueueing the wrong scripts on our end.

This is likely relatively easy to workaround on our end, but I thought it might be helpful to mention this here as well in case you run into similar issues with other plugins or if you want to reconsider registering `selectWoo` as `select2`.

### Expected behavior

No conflicts with select2

### Actual behavior

Conflicts with select2

### Steps to reproduce

1. Install WooCommerce 9.2
2. Create a field group with some ACF fields that use select2 (i.e. Post Object, Page Link, etc.) and assign that field group to a post/page
3. Try to edit a post/page with those fields and notice that the select2 fields are not displaying properly.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.0-rc.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.2
PHP Version: 8.2.9
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 8.2.1
(SecureTransport) OpenSSL/3.1.2

SUHOSIN Installed: –
MySQL Version: 8.1.0
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 129
acf-field-group: 13
attachment: 1
page: 7
post: 28
product: 1
revision: 27
shop_order_placehold: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

ACF Tweaks: by Matt Shaw – 1.0.0
Advanced Custom Fields PRO: by WP Engine – 6.3.5
WooCommerce: by Automattic – 9.2.0-rc.1

### Inactive Plugins (12) ###

[REDACTED]

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 27 KB

### WC Pages ###

Shop base: #220 - /shop/
Cart: #221 - /cart/ -  Contains the woocommerce/cart block
Checkout: #222 - /checkout/ -  Contains the woocommerce/checkout block
My account: #223 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: ACF Child Theme
Version: 1.0.0
Child Theme: ✔
Parent Theme Name: Twenty Twenty-One
Parent Theme Version: 2.3
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-22 15:26:09 +00:00
Options: ✔
Notes: 59
Onboarding: skipped

### Action Scheduler ###

Complete: 11
Oldest: 2024-08-20 21:53:35 +0000
Newest: 2024-08-21 15:27:11 +0000

Failed: 1
Oldest: 2024-08-20 21:53:40 +0000
Newest: 2024-08-20 21:53:40 +0000

Pending: 1
Oldest: 2024-08-21 21:53:35 +0000
Newest: 2024-08-21 21:53:35 +0000


### Status report information ###

Generated at: 2024-08-21 16:30:46 +00:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by naman03malhotra** [comment]
>We have some logic in ACF that checks the registered version of select2 to enqueue different scripts based on the registered version - this is mainly done to avoid conflicts between plugins registering select2 v3 and v4

Hey @mattgrshaw, thanks for bringing this to our attention.

I want to double check with you that, [this](https://github.com/woocommerce/woocommerce/pull/48731/files#diff-ae075b9e432e37b804d3d289c89337670bfb8dc547f773cf8c10c32bb0c46736R239) is the version your are checking with your custom logic?

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/4a92fd95-11ad-40b0-b1c5-dc601ba6bd5e">

**Comment by mattgrshaw** [comment]
@naman03malhotra We check the version directly in the `$wp_scripts` global, which ends up getting set to `1.0.6` here:
https://github.com/woocommerce/woocommerce/pull/48731/files#diff-93e330e41dcee0a7211c92b86b52ba9c4c1f2c0424457958abdfc8b2fb45e659R152

<img width="796" alt="Screenshot 2024-08-21 at 3 04 59 PM" src="https://github.com/user-attachments/assets/35247604-81ec-48d5-856c-18c9112e07f4">

**Comment by naman03malhotra** [comment]
>This is likely relatively easy to workaround on our end

I see, sorry our change is causing trouble. How is the fix looking at your end?

**Comment by lgladdy** [comment]
I was just about to say this feels like a repeat of https://github.com/woocommerce/woocommerce/pull/30473 but it looks like maybe this is going to reverted?

ACF has 2 issues with this change. The first we can fix easily (it’s in our detection of select2 versions, because as Matt mentioned above, we’re detecting select2 v1 now) - but the second is a much bigger problem, and I suspect will affect many other plugins than just ACF.

The main problem is, selectWoo is not fully compatible with select2. Things like `templateSelection` is modified in selectWoo and not supported fully, meaning this change will break many third party plugins.

ACF has specific code which tried to work around this, but it could only do by fully removing any custom `templateResult` or `templateSelection` arguments used in ACF’s select2s which breaks several select2’s in our UI, and all kinds of third party custom code where users are trying to do things like inject icons into results.

We’re limited in ways we could fix this ourselves. We could either try and force unload selectWoo and load select2-full again (which presumably will either now, or eventually, cause problems in WooCommerce), or we just say “If you use woocommerce, you can’t use any custom select2 templates” which is a bad experience for our users.

Is it possible to namespace selectWoo fully away from select2, so both things can exist?

Here’s the current code we’re shipping back from the first time selectWoo was shipped as select2 in WooCommerce:
```
// Only use the template if SelectWoo is not loaded to work around https://github.com/woocommerce/woocommerce/pull/30473
if ( ! acf.isset( window, 'jQuery', 'fn', 'selectWoo' ) ) {
	if ( ! options.templateSelection ) {
		options.templateSelection = function ( selection ) {
			var $selection = $(
				'<span class="acf-selection"></span>'
			);
			$selection.html(
				options.escapeMarkup( selection.text )
			);
			$selection.data( 'element', selection.element );
			return $selection;
		};
	}
} else {
	delete options.templateSelection;
	delete options.templateResult;
}
```

Without that code, all selected values appear as `[Object object]` because selectWoo behaves differently to select2.

**Comment by naman03malhotra** [comment]
We have reverted our change with WC 9.2.2, which should solve the conflict with ACF. So far we have only received reports from ACF users which were affected.

That said, we'd like to collaborate with ACF to avoid such conflicts in the future.

**Comment by alexsoluweb** [comment]
Some styles are still conflicting with ACF select2 in the editor:

<img width="252" height="60" alt="Image" src="https://github.com/user-attachments/assets/94f2d8cc-1aff-4f0c-93e8-7a79c0f675c5" />

<img width="344" height="370" alt="Image" src="https://github.com/user-attachments/assets/d2b059a1-dbd7-4b2c-960e-c75c0754e64d" />
