### ISSUE TITLE
[Enhancement]: How to remove the code “?is-descendent-of-single-product-block=false”

### ISSUE THREAD

**Issue by phanduynam** [woothemes/woocommerce#50861]
### Describe the solution you'd like

I created a product with an external link, when I clicked on the product cap, my external link changed to something like this “example.com?is-descendent-of-single-product-block=false”. How can I remove the “?is-descendent-of-single-product-block=false” part on the product url?
![image](https://github.com/user-attachments/assets/3bbbfbf3-253a-447f-a736-78bfee5279a5)

**Comment by imanish003** [comment]
Hey @phanduynam,

Thanks a bunch for bringing this to our attention! We really appreciate you taking the time to report this issue. It's definitely something we want to look into and improve.

We hear you on wanting to clean up those external URLs. I have added this to our backlog and we'll look into it as soon as we can 🙏🏻

**Comment by imanish003** [comment]
Hey @phanduynam,

I found out that there is another issue #50695 for this issue. Therefore, I am going to close this issue as a duplicate. Please follow the issue #50695 for further updates.
