### ISSUE TITLE
Flushing rewrite rules via WP CLI does not seem to flush WC's rewrite rules

### ISSUE THREAD

**Issue by alessandrotesoro** [woothemes/woocommerce#50863]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm using the `@wordpress/env` package to run e2e tests via playwright. On test sites, I import an `.sql` file which I use as a base for the tests. After importing the sql file I flush the rewrite rules via WP CLI on the Docker site powered by `@wordpress/env` package however upon visiting the "shop" page I'm presented with a 404 server error (not the "not found" WP page). 

The only way to solve it is pressing the save button on the permalinks page on the wp-admin side.

Is there a way to flush WC's rewrite rules via WP CLI?

### Expected behavior

Flushing rewrite rules via WP CLI should work for the shop page too.

### Actual behavior

The page shows a 404 error and the only way to solve it is manually saving permalinks again.

### Steps to reproduce

1. Setup a wp-env site
2. Import an `.sql` file exported from a WooCommerce website
3. Flush rewrite rules via WP CLI on the wp-env site
4. Navigate to the shop page to see the error

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
Hey @alessandrotesoro when you flush the rewrite rules, are you adding `--hard` to the command?

`wp rewrite structure '/%postname%/' --hard`

**Comment by alessandrotesoro** [comment]
@coreymckrill yes, unfortunately that doesn't help

![CleanShot 2024-08-26 at 13 16 51](https://github.com/user-attachments/assets/8cdad0e1-f277-45ac-84f0-f84b0cb6bc37)

**Comment by coreymckrill** [comment]
Is the shop page the only one that's not working after you flush the rewrites via wp-cli? Are other post and page URLs working?
