### ISSUE TITLE
CYS: Cart and checkout are in the wrong position

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#50879]
For some reason the cart and checkout icons are located to the left of the navigation when typically they are seen on the right hand side.

**Comment by dilipbheda-kwt** [comment]
@tjcafferkey I think the `WP Navigation Block` displayed the navigation according to pages menu order.

Pages list

![image](https://github.com/user-attachments/assets/d805600a-26b7-438d-809e-2dacbbde6254)

Frontend menu items

![image](https://github.com/user-attachments/assets/01447114-bc79-4e70-8f98-9337d4ac671b)

**Comment by tjcafferkey** [comment]
Thank you for the comment @dilipbheda-kwt, this issue was specifically referring to the Customize Your Store (CYS) flow where the icons are displayed on the left hand side (rather than the typical right hand side) in the assembler view during this part of the experience.

![Screenshot 2024-08-22 at 14 26 32](https://github.com/user-attachments/assets/f6415456-a3e9-4519-8b5a-d81dc2f3bcfd)
