### ISSUE TITLE
CYS: Replace Nokul theme with a free alternative

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#50872]
Nokul is being retired. We need to replace this theme with Gizmo https://woocommerce.com/products/gizmo/

**Comment by tjcafferkey** [comment]
Pinging @ellenbauer for the alternative theme we are going to use instead.

**Comment by Aljullu** [comment]
The code to change it seems to be here:

https://github.com/woocommerce/woocommerce/blob/30ae60b27336ce050bd69ecf6e2707e7f593a76a/plugins/woocommerce/src/Admin/API/OnboardingThemes.php#L351-L382
