### ISSUE TITLE
Product filters not loading/disappearing on paginated pages 

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#50875]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

1. Place Product Collection with filters on the homepage
2. Load the second page of the collection
3. Filters disappear

This is true also when filtering before loading a paginated page. 

### Expected behavior

Filters will remain on paginated pages

### Actual behavior

Filters not loading/disappearing

### Steps to reproduce

1. Place Product Collection with filters on the homepage
2. Load the second page of the collection
3. Filters disappear

This is true also when filtering before loading a paginated page. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://staging.hobbies4.life
Site address (URL): https://staging.hobbies4.life
WC Version: 9.2.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.22
PHP Post Max Size: 64 MB
PHP Time Limit: 1800
PHP Max Input Vars: 1800
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.1
WC Database Prefix: whHhGW_
Total Database Size: 112.51MB
Database Data Size: 92.75MB
Database Index Size: 19.76MB
whHhGW_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
whHhGW_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
whHhGW_ahrefs_seo_content: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
whHhGW_ahrefs_seo_snapshots: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_aryo_activity_log: Data: 0.38MB + Index: 0.98MB + Engine InnoDB
whHhGW_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_blc_instances: Data: 0.28MB + Index: 0.17MB + Engine InnoDB
whHhGW_blc_links: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
whHhGW_blc_synch: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
whHhGW_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
whHhGW_hcaptcha_events: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
whHhGW_jetpack_sync_queue: Data: 0.25MB + Index: 0.06MB + Engine InnoDB
whHhGW_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
whHhGW_options: Data: 4.44MB + Index: 0.19MB + Engine InnoDB
whHhGW_postmeta: Data: 7.52MB + Index: 4.03MB + Engine InnoDB
whHhGW_posts: Data: 54.34MB + Index: 0.61MB + Engine InnoDB
whHhGW_relevanssi: Data: 5.52MB + Index: 9.55MB + Engine InnoDB
whHhGW_relevanssi_log: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
whHhGW_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_termmeta: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
whHhGW_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
whHhGW_term_relationships: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
whHhGW_term_taxonomy: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
whHhGW_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
whHhGW_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_vrts_alerts: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
whHhGW_vrts_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
whHhGW_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_product_attributes_lookup: Data: 0.22MB + Index: 0.17MB + Engine InnoDB
whHhGW_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
whHhGW_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfblockediplog: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wfconfig: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wffilemods: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfhits: Data: 1.52MB + Index: 0.25MB + Engine InnoDB
whHhGW_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wfknownfilelist: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
whHhGW_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wflogins: Data: 0.42MB + Index: 0.17MB + Engine InnoDB
whHhGW_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
whHhGW_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfnotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
whHhGW_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_yoast_indexable: Data: 0.19MB + Index: 0.09MB + Engine InnoDB
whHhGW_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_yoast_seo_links: Data: 0.17MB + Index: 0.17MB + Engine InnoDB

### Post Type Counts ###

acf-field: 92
acf-field-group: 4
attachment: 384
customize_changeset: 2
feedback: 56
oembed_cache: 110
page: 15
post: 36
product: 104
revision: 2162
wp_block: 7
wp_font_face: 3
wp_font_family: 3
wp_global_styles: 7
wp_navigation: 2
wp_template: 12
wp_template_part: 5
wpcode: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Query Monitor: by John Blackbourn – 3.16.4
Advanced Custom Fields PRO: by WP Engine – 6.3.5
Activity Log: by Activity Log Team – 2.11.0
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 7.1.0
Image Placeholders: by WordPress Performance Team – 1.1.1
hCaptcha for WP: by hCaptcha – 4.4.0
Instant Images: by Darren Cooney – 6.1.2
Jetpack: by Automattic – 13.7
Loco Translate: by Tim Whitlock – 2.6.11
Mailgun: by Mailgun – 2.1.0
Performance Lab: by WordPress Performance Team – 3.4.0
Relevanssi: by Mikko Saari – 4.23.0
Rollbar: by Rollbar – 2.7.1
Temporary Login Without Password: by StoreApps – 1.8.3
Tidio Chat: by Tidio LLC – 6.0.21
WooCommerce: by Automattic – 9.2.1
Yoast SEO: by Team Yoast – 23.3
WP Consent API: by RogierLankhorst – 1.0.7
WP Crontrol: by John Blackbourn – 1.17.0
YITH WooCommerce Wishlist: by YITH – 3.37.0

### Inactive Plugins (9) ###

ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.1

Broken Link Checker: by WPMU DEV – 2.3.0
LiteSpeed Cache: by LiteSpeed Technologies – 6.4.1
ManageWP - Worker: by GoDaddy – 4.9.20
PWA: by PWA Plugin Contributors – 0.8.1
Site Kit by Google: by Google – 1.133.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.4

VRTs – Visual Regression Tests: by Bleech – 1.9.1
Wordfence Security: by Wordfence – 7.11.7

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php
object-cache.php: Performance Lab Server Timing Object Cache Drop-In

### Must Use Plugins (2) ###

H4L MU Plugin: by  –
WP Toolkit Worker Plugin: by  – 6.5.2-8719

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 117 KB

### WC Pages ###

Shop base: #653 - /
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: #656 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Loudness Child Theme
Version: 0.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Loudness
Parent Theme Version: 1.0.10
Parent Theme Author URL: https://automattic.com
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/asafdevc/staging.hobbies4.life/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/asafdevc/staging.hobbies4.life/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/asafdevc/staging.hobbies4.life/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-22 14:56:39 +01:00
Options: ✔
Notes: 94
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2024-08-20 14:27:28 +0100
Newest: 2024-08-20 14:27:28 +0100

Complete: 135
Oldest: 2024-07-22 20:20:21 +0100
Newest: 2024-08-22 11:11:09 +0100

Failed: 46
Oldest: 2023-04-12 15:59:56 +0100
Newest: 2024-08-20 14:29:29 +0100

Pending: 1
Oldest: 2024-08-23 04:10:02 +0100
Newest: 2024-08-23 04:10:02 +0100

### Status report information ###

Generated at: 2024-08-22 11:20:34 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by imanish003** [comment]
Hey @asafm7,

Thanks a lot for reporting this issue.

After some initial testing, I've observed that the issue seems to occur specifically when the filter blocks are placed inside the Product Collection block. However, we'd like to confirm if this aligns with your experience:

1. Does the issue occur when the filter blocks are inside the Product Collection block?
2. Have you tried placing the filter blocks outside of the Product Collection block? If so, does the issue still persist in that configuration?

Thank you again for your patience and cooperation as we work to resolve this 🙏🏻

**Comment by asafm7** [comment]
Thanks, @imanish003.
 
You are right. The filter is placed inside the Product Collection block. I didn't think about it.

I tried moving it outside the block and it seems to solve the issue.

I guess the filter shouldn't be placed inside?

**Comment by kmanijak** [comment]
Hey @asafm7,

> I guess the filter shouldn't be placed inside?

In short, yes. Placing them inside is not the intended way. At the same time, we should disallow that or make sure they work even with degraded experience. As you know we're disabling client-side navigation in PC block if we detect Interactivity API incompatible blocks inside. Filter blocks are indeed incompatible and may result in such a state as you described. For this purpose, I'm adding them to the unsupported blocks list: https://github.com/woocommerce/woocommerce/pull/51358.

But yeah, to keep the best shopper experience (keeping client-side navigation) and have filters working I recommend placing them outside of the PC block.

As I mentioned some time ago, we're working on a new set of filter blocks Interactivity API compatible which you'll be able to place inside PC block if needed 🙌

**Comment by asafm7** [comment]
Thanks, @kmanijak.

I'm looking forward to the improved filters.
