### ISSUE TITLE
Explore building our own translation po/mo/json instead of off the shelf translation in E2E

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#50910]
This is a follow up from https://github.com/woocommerce/woocommerce/pull/50892. In our E2E tests, we load up NL_nl translations to test against, this has some drawbacks:

- We're always testing against the previous release translation, for code currently in trunk, this means we run into a lot of false negatives (which causes us to disable E2E tests until further release). https://github.com/woocommerce/woocommerce/pull/45371
- We avoid false positives that caused the bug linked above (#50892), because migration might still work in a current release but stop working in a future release (false positives).

@dinhtungdu did explore this once and I suggest we go this route again.

**Comment by dinhtungdu** [comment]
FYI, here is the PR I tried to test the translation by generating dummy translation locally: https://github.com/woocommerce/woocommerce-blocks/pull/6424
