### ISSUE TITLE
Change in WooCommerce settings not possible

### ISSUE THREAD

**Issue by Broedadmin** [woothemes/woocommerce#50940]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I can not save any changes in the settings-page. 
For example: if I disable an e-mail being sent out automatically, the button to save the setting is not enabled.

### Expected behavior

When making a change, the option to save the setting should become available.

### Actual behavior

No possibility to save a new setting.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/e4996a3f-9293-49dc-bb6d-345629cf3e7c)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://broed.be
Site address (URL): https://broed.be
WC Version: 9.2.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: nl_BE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.44-49-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.2
WC Database Prefix: wp_
Totale databasegrootte: 78.09MB
Database datagrootte: 73.42MB
Database index grootte: 4.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_em_bookings: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_em_events: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_em_locations: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_em_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_em_tickets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_em_tickets_bookings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.48MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 40.52MB + Index: 1.91MB + Engine InnoDB
wp_posts: Data: 24.52MB + Index: 0.36MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wprm_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wprm_ratings: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 277
custom_css: 1
customize_changeset: 1
e-landing-page: 2
elementor_library: 2
elementor-hf: 2
ml-slide: 2
ml-slider: 1
nav_menu_item: 7
nf_sub: 58
oembed_cache: 1
page: 15
post: 2
product: 8
product_variation: 48
revision: 1836
shop_coupon: 6
shop_order: 74
wp_block: 1
wp_global_styles: 16
wp_navigation: 22
wp_template: 5
wp_template_part: 12
wpcm_menu: 4
wprm_recipe: 1
wpzoom_rcb: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Complianz | GDPR/CCPA Cookie Consent: door Really Simple Plugins – 7.1.0
Elementor: door Elementor.com – 3.23.4
GA Google Analytics: door Jeff Starr – 20240820
Gallery Custom Links: door Jordy Meow – 2.2.0
Elementor Header & Footer Builder: door Brainstorm Force
Nikhil Chavan – 1.6.39

Kirki Customizer Framework: door Themeum – 5.1.0
Ninja Forms: door Saturday Drive – 3.8.12
WooCommerce - Show only lowest prices in variable products: door Fernando Tellado – 1.0.5
Product Slider for WooCommerce by PickPlugins: door PickPlugins – 1.13.51
WooCommerce: door Automattic – 9.2.2
Yoast SEO: door Team Yoast – 23.3

### Inactive Plugins (1) ###

Image Optimizer by Elementor – Compress, Resize and Optimize Images: door Elementor.com – 1.5.2

### Must Use Plugins (2) ###

Ensure admin user isn't deleted: door  – 1.0
WP CLI Login Command Server: door Evan Mattson – 1.3

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dagen
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Winkelbasis: #780 - /ons-assortiment
Winkelwagen: #781 - /winkelwagen -  Contains the [woocommerce_cart] shortcode
Afrekenen: #782 - /afrekenen -  Contains the [woocommerce_checkout] shortcode
Mijn account: #783 - /mijn-account
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Hello Elementor
Version: 3.1.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-25 15:27:45 +00:00
Options: ✔
Notes: 138
Onboarding: completed

### Action Scheduler ###

Afgerond: 214
Oldest: 2024-07-25 04:30:14 +0000
Newest: 2024-08-24 19:44:23 +0000

Mislukt: 10
Oldest: 2023-02-15 01:31:40 +0000
Newest: 2023-06-02 02:31:31 +0000

In afwachting: 1
Oldest: 2024-08-25 19:33:00 +0000
Newest: 2024-08-25 19:33:00 +0000

### Status report information ###

Generated at: 2024-08-24 20:17:03 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by boyketenbroeke** [comment]
I have exactly the same issue, I already verified the above aswell. And, switched template but it still happened. Also my checkout page is not working (it shows the page now but no text!

**Comment by boyketenbroeke** [comment]
@Broedadmin 
I did a rollback on woocommerce plugin to version 9.0.0 and that fixed the entire problem. 
The new woocommerce versions are very buggy so i'll stick to 9.0.0 for now. 
Hope this solves it for you aswell.

**Comment by Broedadmin** [comment]
it worked, thank you :)

**Comment by coreymckrill** [comment]
@Broedadmin I just tried this on the same version shown in your system status report (9.2.2) and I was not able to replicate the issue. It sounds like it might be a javascript conflict, potentially with some other extension. If you run into this again, you can check in your browser developer console for JS error messages, which would give us more information to try and troubleshoot.
