### ISSUE TITLE
"Product out of stock" email sent when stock quantity is not tracked

### ISSUE THREAD

**Issue by Screenfeed** [woothemes/woocommerce#50958]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I think #49583 introduced a bug related to the "Product out of stock" email being sent when the stock quantity is not tracked.

Possible fix:
Maybe `wc_trigger_stock_change_actions()` should use the value of `manage_stock` and bail out if `false`.
Also, a test checking that no emails are sent in such case should be added.

### Expected behavior

If the stock quantity is not tracked for a given product, WooCommerce should not send a "Product out of stock" email.

### Actual behavior

WooCommerce sends a "Product out of stock" email for products not tracking the stock quantity.

### Steps to reproduce

1. Optional: install a plugin that logs emails.
2. Create a simple product and in `Inventory` => `Stock management`, do not tick `Track stock quantity for this product`.
3. Upon saving the product, the email is sent and can be listed in the email logs.

Can also be reproduced by doing `WC_Helper_Product::create_simple_product()` without arguments.

### WordPress Environment

This can be reproduced in #49583's WordPress Playground.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Thank you for flagging this, and for proactively testing before the release. I can replicate the same problem.
