### ISSUE TITLE
REST API: Stock not reduced when adding an item to an order

### ISSUE THREAD

**Issue by Ecarrion** [woothemes/woocommerce#51024]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When adding an item to an order via the rest API, the stock of the product is not instantly reduced. However, updating the order item(with the same values) seems to correctly reduce the product stock.

### Expected behavior

The stock of the managed product should be reduced as soon as the item is added to the order.

### Actual behavior

The stock of the managed product is not reduced until the order item is updated for a second time.

### Steps to reproduce

1. Create an empty order via the rest API 
```
POST /wc/v3/orders
{
  "status": "on-hold",
}
```

2. Add an item to the order via the rest API
```
POST /wc/v3/orders/{new_order_id}

{
  "line_items": [
    {
      "quantity": 1,
      "id": 0,
      "product_id": {real-product-id-with-stock-management-enabled}
    }
  ],
  "status": "on-hold",
}
```

3. See that the returned line item does not have the `_reduced_stock` metadata and that the product did not reduce its stock.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
Additional context: peaMlT-P3-p2#comment-2098

**Comment by coreymckrill** [comment]
On a quick step-through of the flow for creating a new line item, it looks like if we remove [this conditional](https://github.com/woocommerce/woocommerce/blob/b40c4a95e5f8e92413abb335d1687d8b8efc230b/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L933-L933) the stock would get correctly updated. At this moment, I'm not sure why I added that conditional in the first place 😕
