### ISSUE TITLE
Imported orders lose Shipping Country on order update

### ISSUE THREAD

**Issue by ETN-A** [woothemes/woocommerce#51030]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We are using WP All Import to import Woocommerce orders. The one and only issue we ran into is that although orders import fine, any order updates via the admin backend (e.g. changing the order Status), results in the Shipping Country losing its value. Perhaps this is a select2 issue (as I believe that is what is used for the country dropdown list)?

E.g. an order gets imported with 'United Kingdom (UK)' as the value for shipping country. When you open up the order on via admin 'United Kingdom (UK)' is shown as part of the shipping address. However if you click on Edit to edit the address there is nothing selected for country, and if you proceed to update the order without reselecting 'United Kingdom' from the dropdown list, upon save the country name gets nulled.

### Expected behavior

The imported shipping country value should not be nulled on order save or update.

### Actual behavior

The imported shipping country value gets lost (gets nulled).

### Steps to reproduce

1. Import an order
2. Open the order (you will still see the shipping country).
Either
3.a Update the order > Shipping country gets lost
3.b Edit the shipping address > Shipping country dropdown ("Country/Region") will be blank, requiring the country that was showing just before proceeding to edit to be reselected.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.14
PHP Post Max Size: 1 GB
PHP Time Limit: 30000
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.11.8-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 47
acf-field-group: 4
apifw_inv_templates: 1
attachment: 514
custom_css: 2
display_type: 7
e-landing-page: 1
elementor_library: 51
ept_post_type: 107
jet-smart-filters: 2
nav_menu_item: 57
ngg_gallery: 1
ngg_pictures: 831
oembed_cache: 8
order_status: 3
page: 94
post: 121
product: 26305
revision: 552
shop_coupon: 3
shop_order: 344
shop_order_refund: 1
user_request: 1
wp_global_styles: 5
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (49) ###

ACF QuickEdit Fields: by Jörn Lund – 3.3.7
Action Scheduler: by Automattic – 3.8.1
Admin Columns Pro: by AdminColumns.com – 6.3.5
Admin Menu Editor: by Janis Elsts – 1.12.4
Advanced Custom Fields PRO: by WP Engine – 6.3.5
Advanced Database Cleaner: by Younes JFR. – 3.1.4
All In One WP Security: by All In One WP Security & Firewall Team – 5.3.2
Custom Order Status Manager for WooCommerce: by Bright Plugins – 1.1.3.2
Classic Widgets: by WordPress Contributors – 0.3
Custom Twitter Feeds: by Smash Balloon – 2.2.2
Debug Bar: by wordpressdotorg – 1.1.6
Easy Notification Bar: by WPExplorer – 1.6
Elementor: by Elementor.com – 3.23.4
Site Kit by Google: by Google – 1.130.0
WPCode Lite: by WPCode – 2.1.14
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.13
Nextend Social Login: by Nextendweb – 3.1.13
PDF Invoices and Packing Slips For WooCommerce PRO: by Acowebs – 3.2.8
PRO Elements: by PROElements.org – 3.23.3
SearchWP Diagnostics: by SearchWP – 1.5.2
SearchWP Modal Search Form: by SearchWP
LLC – 0.5.3

SearchWP Shortcodes: by SearchWP – 1.8.4
SearchWP WooCommerce Integration: by SearchWP – 1.3.12
SearchWP: by SearchWP – 4.3.16
The Plus Addons for Elementor: by POSIMYTH – 5.6.2
The Plus Addons for Elementor - Pro: by POSIMYTH – 5.6.1
Transients Manager: by WPBeginner – 2.0.5
WooCommerce Address Book: by CrossPeak – 2.6.3
Order Weight for WooCommerce: by Andreas Karman – 1.2.2
Woo Store Vacation: by MyPreview – 1.9.4
WooCommerce Stripe Gateway: by WooCommerce – 8.6.1
WooCommerce: by Automattic – 9.2.3
WP All Export Pro: by Soflyy – 1.8.9
WP All Import Pro: by Soflyy – 4.8.8
WP Crontrol: by John Blackbourn – 1.17.0
WP Mail SMTP: by WP Mail SMTP – 4.0.1
WP Activity Log: by Melapress – 5.1.0

WP All Export - ACF Export Add-On Pro: by Soflyy – 1.0.5
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.10-beta-2.0
WP All Import - ACF Add-On: by Soflyy – 3.3.8
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 4.0.0

### Must Use Plugins (3) ###

BA-mu-plugin-patch.php: by  –
installatron_hide_status_test.php: by  –
WP STAGING Optimizer: by René Hermenau – 1.5.1

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 220 KB

### Theme ###

Name: Hello Elementor Child 
Version: 1.0.1
Author URL: https://elementor.com/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 3.1.0 – 3.1.1 is available
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: BookAddicition/woocommerce/emails/admin-new-order.php
BookAddicition/woocommerce/emails/customer-completed-order.php
BookAddicition/woocommerce/single-product/product-thumbnails.php version - is out of date. The core version is 3.5.1

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-30 02:44:08 +01:00
Options: ✔
Notes: 155
Onboarding: skipped

### Action Scheduler ###

Complete: 218,554
Oldest: 2024-07-29 09:13:22 +0100
Newest: 2024-08-29 09:02:45 +0100

Failed: 12,191
Oldest: 2023-03-02 13:45:44 +0000
Newest: 2024-08-21 18:34:23 +0100

Pending: 69
Oldest: 2024-08-29 09:04:00 +0100
Newest: 2024-09-02 14:01:08 +0100


### Status report information ###

Generated at: 2024-08-29 09:03:49 +01:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

![Woocommerce Shopping Country Issue](https://github.com/user-attachments/assets/aa0ffa07-c2d9-420d-ae1f-41348a71f33b)

**Comment by coreymckrill** [comment]
@ETN-A can you provide a sample of your import file (with sensitive customer data redacted)? I'm curious what value it's using for the country field.

**Comment by ETN-A** [comment]
> @ETN-A can you provide a sample of your import file (with sensitive customer data redacted)? I'm curious what value it's using for the country field.

Hi, was about to post an update so thanks for the nudge. You were thinking along the right lines — it turns out that the issue is that the county field needs to be a Country Code and NOT the name of the country. I swear I haven't found this mentioned anywhere... but I have now come up with the following function which "translates" names of counties to the correct code:

`function modify_country_name($country) {
    $country_map = array(
        'Afghanistan' => 'AF',
        'Albania' => 'AL',
        'Algeria' => 'DZ',
        'Andorra' => 'AD',
        'Angola' => 'AO',
        'Anguilla' => 'AI',
        'Antarctica' => 'AQ',
        'Antigua and Barbuda' => 'AG',
        'Argentina' => 'AR',
        'Armenia' => 'AM',
        'Aruba' => 'AW',
        'Australia' => 'AU',
        'Austria' => 'AT',
        'Azerbaijan' => 'AZ',
        'Bahamas' => 'BS',
        'Bahrain' => 'BH',
        'Bangladesh' => 'BD',
        'Barbados' => 'BB',
        'Belgium' => 'BE',
        'Belize' => 'BZ',
        'Benin' => 'BJ',
        'Bermuda' => 'BM',
        'Bhutan' => 'BT',
        'Bolivia' => 'BO',
        'Bosnia' => 'BA',
        'Bosnia and Herzegowina' => 'BA',
        'Bonaire' => 'BQ',
        'Botswana' => 'BW',
        'Bouvet Island' => 'BV',
        'Brazil' => 'BR',
        'British Indian Ocean Territory' => 'IO',
        'British Virgin Islands' => 'VG',
        'Brunei' => 'BN',
        'Bulgaria' => 'BG',
        'Burkina Faso' => 'BF',
        'Burundi' => 'BI',
        'Cambodia' => 'KH',
        'Cameroon' => 'CM',
        'Canada' => 'CA',
        'Cape Verde' => 'CV',
        'Cayman Islands' => 'KY',
        'Central African Republic' => 'CF',
        'Chad' => 'TD',
        'Chile' => 'CL',
        'China' => 'CN',
        'Christmas Island' => 'CX',
        'Cocos (Keeling) Islands' => 'CC',
        'Colombia' => 'CO',
        'Comoros' => 'KM',
        'Congo' => 'CG',
        'Cook Islands' => 'CK',
        'Costa Rica' => 'CR',
        'Croatia' => 'HR',
        'Cyprus' => 'CY',
        'Czech Republic' => 'CZ',
        'Denmark' => 'DK',
        'Djibouti' => 'DJ',
        'Dominica' => 'DM',
        'Dominican Republic' => 'DO',
        'Ecuador' => 'EC',
        'Egypt' => 'EG',
        'El Salvador' => 'SV',
        'Equatorial Guinea' => 'GQ',
        'Eritrea' => 'ER',
        'Estonia' => 'EE',
        'Ethiopia' => 'ET',
        'Falkland Islands' => 'FK',
        'Faroe Islands' => 'FO',
        'Fiji' => 'FJ',
        'Finland' => 'FI',
        'France' => 'FR',
        'French Guiana' => 'GF',
        'French Polynesia' => 'PF',
        'French Southern Territories' => 'TF',
        'Gabon' => 'GA',
        'Gambia' => 'GM',
        'Georgia' => 'GE',
        'Germany' => 'DE',
        'Ghana' => 'GH',
        'Gibraltar' => 'GI',
        'Greece' => 'GR',
        'Greenland' => 'GL',
        'Grenada' => 'GD',
        'Guadeloupe' => 'GP',
        'Guam' => 'GT',
        'Guatemala' => 'GG',
        'Guinea' => 'GN',
        'Guinea-Bissau' => 'GW',
        'Guyana' => 'GY',
        'Haiti' => 'HT',
        'Heard and McDonald Islands' => 'HM',
        'Honduras' => 'HN',
        'Hong Kong' => 'HK',
        'Hungary' => 'HU',
        'Iceland' => 'IS',
        'India' => 'IN',
        'Indonesia' => 'ID',
        'Iraq' => 'IQ',
        'Ireland' => 'IE',
        'Israel' => 'IL',
        'Italy' => 'IT',
        'Jamaica' => 'JM',
        'Japan' => 'JP',
        'Jordan' => 'JO',
        'Kazakhstan' => 'KZ',
        'Kenya' => 'KE',
        'Kiribati' => 'KI',
        'Korea (South)' => 'KR',
        'Kuwait' => 'KW',
        'Kyrgyzstan' => 'KG',
        'Lao' => 'LA',
        'Latvia' => 'LV',
        'Lebanon' => 'LB',
        'Lesotho' => 'LS',
        'Liberia' => 'LR',
        'Libya' => 'LY',
        'Libyan Arab Jamahiriya' => 'LY',
        'Liechtenstein' => 'LI',
        'Lithuania' => 'LT',
        'Luxembourg' => 'LU',
        'Macau' => 'MO',
        'Macedonia' => 'MK',
        'Madagascar' => 'MG',
        'Malawi' => 'MW',
        'Malaysia' => 'MY',
        'Maldives' => 'MV',
        'Mali' => 'ML',
        'Malta' => 'MT',
        'Marshall Islands' => 'MH',
        'Martinique' => 'MQ',
        'Mauritania' => 'MR',
        'Mauritius' => 'MU',
        'Mayotte' => 'YT',
        'Mexico' => 'MX',
        'Micronesia' => 'FM',
        'Moldova' => 'MD',
        'Monaco' => 'MC',
        'Mongolia' => 'MN',
        'Montenegro' => 'ME',
        'Montserrat' => 'MS',
        'Morocco' => 'MA',
        'Mozambique' => 'MZ',
        'Myanmar' => 'MN',
        'Namibia' => 'NA',
        'Nauru' => 'NR',
        'Nepal' => 'NP',
        'Netherlands' => 'NL',
        'Netherlands Antilles' => 'AN',
        'New Caledonia' => 'NC',
        'New Zealand' => 'NZ',
        'Nicaragua' => 'NI',
        'Niger' => 'NE',
        'Nigeria' => 'NG',
        'Niue' => 'NU',
        'Norfolk Island' => 'NF',
        'Norway' => 'NO',
        'Oman' => 'OM',
        'Pakistan' => 'PK',
        'Panama' => 'PA',
        'Papua New Guinea' => 'PG',
        'Paraguay' => 'PY',
        'Peru' => 'PE',
        'Philippines' => 'PH',
        'Pitcairn' => 'PN',
        'Poland' => 'PL',
        'Portugal' => 'PT',
        'Qatar' => 'QA',
        'Reunion' => 'RE',
        'Romania' => 'RO',
        'Russia' => 'RU',
        'Russian Federation' => 'RU',
        'Rwanda' => 'RW',
        'Saint Barthelemy' => 'BL',
        'Saint Helena' => 'HL',
        'St. Kitts' => 'KN',
        'Saint Kitts and Nevis' => 'KN',
        'St. Lucia' => 'LC',
        'Saint Lucia' => 'LC',
        'St. Vincent and the Grenadines' => 'VC',
        'Saint Vincent and the Grenadines' => 'VC',
        'San Marino' => 'SM',
        'Saudi Arabia' => 'SA',
        'Senegal' => 'SN',
        'Serbia' => 'RS',
        'Seychelles' => 'SC',
        'Sierra Leone' => 'SL',
        'Singapore' => 'SG',
        'Slovak Republic' => 'SK',
        'Slovenia' => 'SI',
        'Solomon Islands' => 'SB',
        'Somalia' => 'SO',
        'South Africa' => 'ZA',
        'South Georgia/South Sandwich Islands' => 'GS',
        'South Sudan' => 'SS',
        'Spain' => 'ES',
        'Sri Lanka' => 'LK',
        'Suriname' => 'SR',
        'Svalbard and Jan Mayen Islands' => 'SJ',
        'Swaziland' => 'SZ',
        'Sweden' => 'SE',
        'Switzerland' => 'CH',
        'Taiwan' => 'TW',
        'Tajikistan' => 'TJ',
        'Tanzania' => 'TZ',
        'Thailand' => 'TH',
        'Timor-Leste' => 'TL',
        'Togo' => 'TG',
        'Tokelau' => 'TK',
        'Tonga' => 'TO',
        'Trinidad and Tobago' => 'TT',
        'Tunisia' => 'TN',
        'Turkey' => 'TR',
        'Turkmenistan' => 'TM',
        'Turks and Caicos' => 'TC',
        'Turks and Caicos Islands' => 'TC',
        'Tuvalu' => 'TV',
        'United States' => 'US',
        'U.S.A.' => 'US',
        'Uganda' => 'UG',
        'Ukraine' => 'UA',
        'United Arab Emirates' => 'AE',
        'United Kingdom' => 'GB',
        'Uruguay' => 'UY',
        'Uzbekistan' => 'UZ',
        'Vanuatu' => 'VU',
        'Vatican' => 'VA',
        'Vatican City State' => 'VA',
        'Venezuela' => 'VE',
        'Vietnam' => 'VN',
        'Viet Nam' => 'VN',
        'Wallis and Futuna Islands' => 'WF',
        'Western Sahara' => 'EH',
        'Yemen' => 'YE',
        'Zambia' => 'ZM',
        'Zimbabwe' => 'ZW'
    );
    
    // Check if the country exists in the map
    if (array_key_exists($country, $country_map)) {
        // Log the substitution to the error log
        error_log("Country name '{$country}' was substituted with '{$country_map[$country]}'.");

        // Return the substituted value
        return $country_map[$country];
    }
    
    // Return the original country if no substitution was made
    return $country;
}
`

The imported country name (derivered from 3rd parties, who use slightly different country names in their relevant drop-down) is passed to the above function during the import... and it works! the country names that show no longer get lost, and they properly appear as already selected in the Edit address country dropdown.

Outstanding issue seems to be that there appears to be some interplay between States and countries... so for example for the US I've also come up with a modify_state_name function. However, considering how [extensive](https://www.wptechnic.com/woocommerce-country-state-codes/) country codes and options are... I clearly can't code for all eventualities.

**Comment by coreymckrill** [comment]
@ETN-A oh, glad you figured it out. There are some built-in PHP functions in WooCommerce that can give you the country and state codes and labels that it uses internally. Example:

```
WC()->countries->get_countries(); // Like your array above, but with code and label flipped
WC()->countries->get_states( 'US' ); // Associative array of code => label pairs for each state
```
