### ISSUE TITLE
[Enhancement]: Decouple WooPayments incentive and Payments nav item

### ISSUE THREAD

**Issue by anu-rock** [woothemes/woocommerce#51111]
### Describe the solution you'd like

Currently, the Payments nav item notification badge in wp-admin is tied to WooPayments incentive. The badge is not visible if an incentive is unavailable in the merchant's country. We need to change this behavior.

#### Acceptance criteria:

* When the WooPayments plugin is NOT installed, regardless of an incentive being available - the left nav payments item will always show with the notification badge.
* If an incentive is available, clicking the nav item will take the merchant to the fake connect page.
* If an incentive is unavailable, clicking the nav item will take the merchant to the payments task page.
* Update the WooPayments tile on all surfaces to use the new payment methods shared component (#49300) so it is consistent with our other pages.
* Remove the recommended badge on Stripe when WooPayments is presented.

### Additional context

![image](https://github.com/user-attachments/assets/6e94f543-9b77-4fb9-a0c4-80f9ec47b571)

**Comment by timmy5685** [comment]
> When the WooPayments plugin is NOT installed, regardless of an incentive being available - the left nav payments item will always show with the notification badge.
@anu-rock my understanding from @csmcneill is that the badge is based on this:

> Currently, this badge still only occur if Display suggestions within WooCommerce is enabled at WooCommerce > Settings > Advanced > WooCommerce.com > Marketplace suggestions.

I don't think we should change this. So the left nav item should always show and the badge should continue to be dependent on that.

Sharing the screenshot for the payments task page for reference, as well:

<img width="484" alt="WooPayments Onboarding Flows" src="https://github.com/user-attachments/assets/aa63f7c3-9376-4502-915c-53f62883bad0">
