### ISSUE TITLE
/lost-password/ attack

### ISSUE THREAD

**Issue by calevans** [woothemes/woocommerce#51126]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

My site has been under attack for a week now. 

```
172.69.130.143 - - [03/Sep/2024:19:26:51 -0400] "GET /my-account//lost-password/ HTTP/1.1" 503 19332 "-" "Mozilla/5.0 (Windows NT 10.0; rv:123.0) Gecko/20100101 Firefox/123.0"
172.71.164.189 - - [03/Sep/2024:19:27:31 -0400] "GET /my-account//lost-password/ HTTP/1.1" 503 19332 "-" "Mozilla/5.0 (Windows NT 10.0; rv:123.0) Gecko/20100101 Firefox/123.0"
172.71.164.120 - - [03/Sep/2024:19:27:31 -0400] "GET /my-account/ HTTP/1.1" 503 19332 "-" "Mozilla/5.0 (Windows NT 10.0; rv:123.0) Gecko/20100101 Firefox/123.0"
172.70.242.241 - - [03/Sep/2024:19:27:32 -0400] "POST /my-account/ HTTP/1.1" 503 19332 "-" "Mozilla/5.0 (Windows NT 10.0; rv:123.0) Gecko/20100101 Firefox/123.0"
172.71.182.247 - - [03/Sep/2024:19:27:38 -0400] "GET /my-account//lost-password/ HTTP/1.1" 503 19332 "-" "Mozilla/5.0 (Windows NT 10.0; rv:123.0) Gecko/20100101 Firefox/123.0"
```
All of the records look like this.

The pattern is USUALLY (but not always)
GET /my-account/
GET /my-account/lost-password/
POST /my-account/
POST /my-account/lost-password/

now I'm using WordFence to 503 hits on /my-account/* because on this particular site it doesn't make a difference. However, before I did that, the hackers were able to create accounts using this sequence. I had to delete more than 9,000 accounts once I got WordFence configured to block.

Is it at all possible that the /lost-password/ code will create an account if it does not exist? In looking at the log sequences, there were no other calls that would have created the account. Account creation is turned off for this site. So it seems like it would be somewhere in woocommerce. 

Also, this particular site is pretty simple, just a few pages and a few products. It's not like there are a lot of other plugins installed. 

TIA! 😄 
=C=

### Expected behavior

The call to `/lost-password/` would not create an account. 

### Actual behavior

The call to `/lost-password/` creates an account. 

### Steps to reproduce

I cannot. But I can watch it being done on my site. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 9.2.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.58 (Ubuntu)
PHP Version: 8.3.11
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.3
WC Database Prefix: wp_
Total Database Size: 21.23MB
Database Data Size: 18.18MB
Database Index Size: 3.05MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fsmpt_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.17MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.14MB + Index: 0.19MB + Engine InnoDB
wp_wfconfig: Data: 1.30MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.30MB + Index: 0.27MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.44MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 20
nav_menu_item: 5
nf_sub: 43
page: 17
post: 2
product: 7
shop_coupon: 1
shop_order: 6
wpcode: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Cloudflare: by Cloudflare
Inc. – 4.12.8

Custom Adobe Fonts (Typekit): by Brainstorm Force – 1.0.18
Font Awesome: by Font Awesome – 4.5.0
Redis Object Cache: by Till Krüss – 2.5.3
WooCommerce Stripe Gateway: by WooCommerce – 8.6.1
WP Menu Cart: by WP Overnight – 2.14.5
WooCommerce Shipping & Tax: by WooCommerce – 2.8.0
WooCommerce: by Automattic – 9.2.3
Wordfence Security: by Wordfence – 7.11.7
Yoast SEO: by Team Yoast – 23.4
WP fail2ban: by Charles Lecklider – 5.3.2

### Inactive Plugins (4) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.80
What The File: by Never5 – 1.6.0
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.22 (update to version 2.7.1 is available)

### Dropin Plugins () ###

object-cache.php: Redis Object Cache Drop-In

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 28 KB

### WC Pages ###

Shop base: #31 - /shop/
Cart: #32 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #33 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #34 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Cal
Version: 0.6.5.0
Author URL: http://www.kathyevans.biz
Child Theme: ✔
Parent Theme Name: Understrap
Parent Theme Version: 1.1.0 – 1.2.4 is available
Parent Theme Author URL: https://howarddc.com
WooCommerce Support: ✔

### Templates ###

Overrides: understrap/woocommerce/cart/cart-empty.php version 3.5.0 is out of date. The core version is 7.0.1
understrap/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.9.0
understrap/woocommerce/cart/proceed-to-checkout-button.php version 2.4.0 is out of date. The core version is 7.0.1
/woocommerce/checkout/form-checkout.php
understrap/woocommerce/checkout/form-coupon.php version 3.4.4 is out of date. The core version is 7.0.1
understrap/woocommerce/checkout/form-pay.php version 5.2.0 is out of date. The core version is 8.2.0
/woocommerce/checkout/form-shipping.php version 3.0.9 is out of date. The core version is 3.6.0
understrap/woocommerce/checkout/payment.php version 3.5.3 is out of date. The core version is 8.1.0
/woocommerce/checkout/thankyou.php version 3.2.0 is out of date. The core version is 8.1.0
understrap/woocommerce/global/form-login.php version 3.6.0 is out of date. The core version is 9.2.0
understrap/woocommerce/loop/add-to-cart.php version 3.3.0 is out of date. The core version is 9.0.0
understrap/woocommerce/loop/orderby.php
understrap/woocommerce/myaccount/downloads.php version 3.2.0 is out of date. The core version is 7.8.0
understrap/woocommerce/myaccount/form-edit-account.php version 3.5.0 is out of date. The core version is 8.7.0
understrap/woocommerce/myaccount/form-edit-address.php version 3.6.0 is out of date. The core version is 7.0.1
/woocommerce/myaccount/form-login.php version 3.6.1 is out of date. The core version is 9.2.0
understrap/woocommerce/myaccount/form-lost-password.php
understrap/woocommerce/myaccount/form-reset-password.php
/woocommerce/myaccount/my-address.php version 2.6.0 is out of date. The core version is 9.2.0
understrap/woocommerce/myaccount/my-orders.php
understrap/woocommerce/myaccount/navigation.php version 2.6.0 is out of date. The core version is 9.0.0
understrap/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 9.2.0
understrap/woocommerce/product-searchform.php version 3.3.0 is out of date. The core version is 7.0.1
/woocommerce/single-product/add-to-cart/simple.php version 3.4.0 is out of date. The core version is 7.0.1
understrap/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.4.0 is out of date. The core version is 7.0.1

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-09-04 00:24:26 +00:00
Options: ✔
Notes: 191
Onboarding: completed

### Action Scheduler ###

Complete: 85
Oldest: 2024-08-04 10:16:40 +0000
Newest: 2024-09-03 22:17:43 +0000

Failed: 11
Oldest: 2021-10-13 14:25:04 +0000
Newest: 2023-11-08 12:44:55 +0000

Pending: 1
Oldest: 2024-09-04 15:53:59 +0000
Newest: 2024-09-04 15:53:59 +0000

### Status report information ###

Generated at: 2024-09-03 23:37:11 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @calevans, thanks for getting in touch!

I'm guessing that you've probably got account creation on the my account page enabled (if you go in to wp-admin > WooCommerce > Settings > Accounts & Privacy, there's a checkbox to enable/disable account creation).  If you toggle that off, it should prevent new accounts from being created.

**Comment by calevans** [comment]
That was it. Thank you. I had no idea that was an option. :)
