### ISSUE TITLE
WooPayments: error retrieving settings

### ISSUE THREAD

**Issue by sb218593** [woothemes/woocommerce#51157]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

TypeError: Cannot read properties of undefined (reading 'filter')

    at sO (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce-payments/dist/index.js?ver=8.1.1:9:324977)
    at Suspense
    at W (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:461572)
    at div
    at div
    at $r (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:554599)
    at div
    at sw (https://www.moto-booking-paris.fr/wp-includes/js/dist/components.min.js?ver=36b97398bf090476214e:34:226008)
    at lw (https://www.moto-booking-paris.fr/wp-includes/js/dist/components.min.js?ver=36b97398bf090476214e:34:226686)
    at dw (https://www.moto-booking-paris.fr/wp-includes/js/dist/components.min.js?ver=36b97398bf090476214e:34:227033)
    at w (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/admin-layout/index.js?ver=092d36684bd43b3c307d:1:1989)
    at ta (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:555193)
    at ea (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:554987)
    at https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:558458
    at https://www.moto-booking-paris.fr/wp-includes/js/dist/data.min.js?ver=7c62e39de0308c73d50c:9:3292
    at WithSelect(Component) (https://www.moto-booking-paris.fr/wp-includes/js/dist/compose.min.js?ver=b8d54449305350b51869:9:18934)
    at https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=820c86a0605e0b140a55:2:134859
    at O (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:439760)
    at I (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:439201)
    at a (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:433712)
    at https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:558711
    at https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=820c86a0605e0b140a55:2:135936
    at https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=820c86a0605e0b140a55:2:132811
    at https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=820c86a0605e0b140a55:2:132811
    at https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=820c86a0605e0b140a55:2:134033
    at Ta (https://www.moto-booking-paris.fr/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=9d2b748e1652cd6dd765:2:569172)

### Expected behavior

i expected to enable WooPayment

### Actual behavior

can't enable WooPayment

### Steps to reproduce

![Image 04-09-2024 à 21 40](https://github.com/user-attachments/assets/242d81c1-b8cf-41ea-a268-63040719c625)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.moto-booking-paris.fr
Site address (URL): https://www.moto-booking-paris.fr
WC Version: 9.2.3
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 4 Go
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.29
PHP Post Max Size: 512 Mo
PHP Time Limit: 360
PHP Max Input Vars: 2000000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.6.19-MariaDB
Max Upload Size: 512 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.3
WC Database Prefix: wpvepf_
Taille totale de la base de données: 20.24MB
Taille de la base de données: 17.49MB
Taille de l’index: 2.75MB
wpvepf_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpvepf_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpvepf_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_actionscheduler_actions: Données : 0.05MB + Index : 0.11MB + Moteur InnoDB
wpvepf_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_actionscheduler_logs: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
wpvepf_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wpvepf_eb_form_settings: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_e_events: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_itsec_bans: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_itsec_dashboard_events: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_itsec_dashboard_lockouts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_itsec_distributed_storage: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_itsec_fingerprints: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_itsec_firewall_rules: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpvepf_itsec_geolocation_cache: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_itsec_lockouts: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
wpvepf_itsec_logs: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wpvepf_itsec_mutexes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_itsec_opaque_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_itsec_temp: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpvepf_itsec_user_groups: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_itsec_vulnerabilities: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpvepf_jetpack_sync_queue: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpvepf_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_options: Données : 7.06MB + Index : 0.09MB + Moteur InnoDB
wpvepf_postmeta: Données : 6.47MB + Index : 0.20MB + Moteur InnoDB
wpvepf_posts: Données : 2.39MB + Index : 0.06MB + Moteur InnoDB
wpvepf_quickcab_customers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_quickcab_geofence_shapes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_quickcab_geofence_shape_coordinates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_quickcab_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_quickcab_tiered_pricing: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpvepf_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wpvepf_wc_admin_note_actions: Données : 0.03MB + Index : 0.02MB + Moteur InnoDB
wpvepf_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wpvepf_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpvepf_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpvepf_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpvepf_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpvepf_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_wc_product_meta_lookup: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wpvepf_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpvepf_wpforms_logs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpvepf_wpforms_payments: Données : 0.02MB + Index : 0.14MB + Moteur InnoDB
wpvepf_wpforms_payment_meta: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpvepf_wpforms_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB

### Post Type Counts ###

attachment: 60
custom_css: 2
customize_changeset: 6
elementor_library: 2
fixed_address: 30
geofence_rule: 102
page: 19
post: 2
product: 2
qc_booking_form: 4
qc_checkout_field: 3
quickcab_vehicle: 10
revision: 62
shop_order_placehold: 5
surge_price_rule: 4
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Modèles de démarrage: par Brainstorm Force – 4.4.2
Solid Security Basique: par SolidWP – 9.3.3
Elementor: par Elementor.com – 3.23.4
Essential Addons for Elementor: par WPDeveloper – 6.0.3
QuickCab: par QuickCab – 1.2.8
WooCommerce Stripe Gateway: par WooCommerce – 8.6.1
WooPayments: par Woocommerce – 8.1.1
WooCommerce: par Automattic – 9.2.3
WP Fastest Cache: par Emre Vona – 1.3.0
WPForms Lite: par WPForms – 1.9.0.4

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 181 Ko

### WC Pages ###

Base de la boutique: #7 - /boutique/
Panier: #8 - /panier/ -  Contient le bloc woocommerce/cart
Commander: #9 - /commander/ -  Contient le bloc woocommerce/checkout
Mon compte: #10 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Astra
Version: 4.8.0
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.1.1
Connected to WPCOM: Oui
WPCOM Blog ID: 236628550
Account ID: acct_1Puv9zFxctTTHaYm
Payment Gateway: Activé
Test Mode: Activé
Enabled APMs: card
WooPay: Non éligible
Apple Pay / Google Pay: Activé (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Activé
Auth and Capture: Activé
Documents: Activé
Logging: Désactivé

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-09-04 23:04:24 +00:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Annulé: 3
Oldest: 2024-09-04 14:10:29 +0000
Newest: 2024-09-04 19:13:01 +0000

Terminé: 72
Oldest: 2024-09-02 00:31:20 +0000
Newest: 2024-09-04 19:32:32 +0000

En attente: 6
Oldest: 2024-09-04 23:10:16 +0000
Newest: 2024-09-11 18:05:54 +0000

### Status report information ###

Generated at: 2024-09-04 19:41:22 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Stojdza** [comment]
Hi @sb218593,

Thank you for reporting this issue. To help us investigate the problem with enabling WooPayment, could you please provide more detailed steps to reproduce the bug? Currently, we see that an image is attached, but having a clearer step-by-step description would help us identify the cause faster.

**Comment by jinitpatel** [comment]
After upgrade we are having similar issue. On Woo Payment settings page getting "Error retrieving settings." 
Somehow CSS code is being injected in JSON response. Please check below screenshot.

![image](https://github.com/user-attachments/assets/b1d10886-1a0c-48c3-9979-15e97f596ada)

Due to this it doesn't shows up list of payment methods.  Please check below image. 

![image](https://github.com/user-attachments/assets/17407b3e-2de0-4443-850b-639eb9ad47ca)

**Comment by Cottonnion** [comment]
facing same issue, anyone got solution ?

**Comment by weweb-hu** [comment]
I have exactly the same issue. Anyone found a solution?
