### ISSUE TITLE
HTML of product blocks is sanitized differently when inside the cart block

### ISSUE THREAD

**Issue by ChrisPlaneta** [woothemes/woocommerce#51155]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**General description**

I use the "woocommerce_blocks_product_grid_item_html" filter to add  inline <script> tags to the product items of product blocks like "Newest products" block or "Best selling products" block. 

This works fine but causes errors when I use these blocks inside a cart block (empty state).  In such case, the whole cart block is not rendered and an error message gets thrown.

![image](https://github.com/user-attachments/assets/ecad429d-aa72-4459-becc-09e77a0ef77f)

---

**More information**

I am building an analytics plugin that tracks (among other things) interactions with products (clicks, views, adding to cart, etc.).

To track these interactions, I add product data to products loop items. I do it this way because the data provided by Rest API is not useful and gives inaccurate prices in the "all products" block.

I add the product data inside <script>...</script> tags, which are added to the end of HTML of product loop items via the "woocommerce_blocks_product_grid_item_html" filter.

Everything works fine when I use the product blocks (like "newest products") inside ordinary pages, however, when I add them inside the cart block (empty state) then the block is not rendered.

I found out that when I add ordinary HTML with the above filter, then the blocks are rendered correctly in all places. However this is not useful for my use case. I need to know exactly when a block finishes rendering to be able to send "product view" event to tracking tools, but I have not found a way to do it and the documentation doesnt help. That is why I add JS to product blocks.

### Expected behavior

The cart block should not throw an error and the whole block (along with the product block) should be rendered correctly

### Actual behavior

The block is not renderred

### Steps to reproduce

1. use this filter and function

add_filter( 'woocommerce_blocks_product_grid_item_html', 'fupi_woo_block_teasers');

function fupi_woo_block_teasers( $html, $data, $product ){
		
		if ( is_admin() ) return $html;

		if ( substr( $html, -5 ) == '</li>' ) {
			
			$script = "<script ></script>";

			return substr( $html, 0, -5 ) . $script . '</li>';
		}

		return $html;
	}

2. Go to the page with the cart block and make sure that it is empty. It will not render.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://wp2.tracking.ovh
Site address (URL): https://wp2.tracking.ovh
WC Version: 9.2.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: ✔
WP Memory Limit: 8 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.16
PHP Post Max Size: 8 GB
PHP Time Limit: 3000
PHP Max Input Vars: 6000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.3
WC Database Prefix: s982hs_9_
Total Database Size: 19.34MB
Database Data Size: 15.42MB
Database Index Size: 3.92MB
s982hs_9_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
s982hs_9_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
s982hs_9_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
s982hs_9_woocommerce_order_itemmeta: Data: 0.20MB + Index: 0.23MB + Engine InnoDB
s982hs_9_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
s982hs_9_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
s982hs_9_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_actionscheduler_actions: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
s982hs_9_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
s982hs_9_aepc_custom_audiences: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_aepc_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
s982hs_9_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_fluentform_entry_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_fluentform_form_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_fluentform_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_fluentform_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_fluentform_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_gdpr_cookie_post_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_gdpr_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
s982hs_9_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
s982hs_9_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_icl_strings: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
s982hs_9_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_string_translations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_icl_translate: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_icl_translations: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
s982hs_9_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_icl_translation_status: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
s982hs_9_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
s982hs_9_options: Data: 4.28MB + Index: 0.16MB + Engine InnoDB
s982hs_9_postmeta: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
s982hs_9_posts: Data: 3.36MB + Index: 0.13MB + Engine InnoDB
s982hs_9_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
s982hs_9_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
s982hs_9_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
s982hs_9_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
s982hs_9_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
s982hs_9_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
s982hs_9_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_9_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
s982hs_9_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
s982hs_9_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_9_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
s982hs_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
s982hs_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
s982hs_sitemeta: Data: 3.05MB + Index: 0.03MB + Engine InnoDB
s982hs_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
s982hs_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

acf-field: 10
acf-field-group: 2
attachment: 163
custom_css: 3
custom-css-js: 4
customize_changeset: 31
gp_elements: 6
happyform: 1
mc4wp-form: 1
nav_menu_item: 45
oembed_cache: 1
page: 38
popup: 2
post: 20
product: 21
product_variation: 7
revision: 87
shop_coupon: 3
shop_order: 97
wck_fieldset: 1
wp_global_styles: 2
wp_navigation: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Query Monitor: by John Blackbourn – 3.16.4
KP Media Library Lightbox: by Krzysztof Planeta – 1.0.0
Code Snippets: by Code Snippets Pro – 3.6.5.1
Simple Custom CSS and JS: by SilkyPress.com – 3.47
Debug Log Manager: by Bowo – 2.3.3
WP Full Picture: by Krzysztof Planeta – 7.6.46
GenerateBlocks: by Tom Usborne – 1.9.1
Google for WooCommerce: by WooCommerce – 2.8.4
Kadence Blocks – Gutenberg Blocks for Page Builder Features: by Kadence WP – 3.2.52
Kadence AI Starter Templates: by Kadence WP – 2.1.3
WooCommerce: by Automattic – 9.2.3
Custom Post Type UI: by WebDevStudios – 1.17.1
KP Tweaks: by Krzysiek Planeta – 1.0
GenerateBlocks: by Tom Usborne – 1.9.1
NinjaFirewall (WP Edition): by The Ninja Technologies Network – 4.6.1

### Inactive Plugins (81) ###

Advanced Cron Manager: by BracketSpace – 2.5.10
Advanced Custom Fields: by WP Engine – 6.3.6
Advanced Database Cleaner: by Younes JFR. – 3.1.4
Autoptimize: by Frank Goossens (futtta) – 3.1.12
Beautiful and responsive cookie consent: by Beautiful Cookie Banner – 4.3.0
Beehive Analytics: by WPMU DEV – 3.4.12
Brave Conversion Engine: by Brave – 0.7.2
Caldera Forms: by Caldera Forms – 1.9.7
Code Profiler: by Jerome Bruandet ~ NinTechNet Ltd. – 1.7
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 7.1.0
Contact Form 7: by Takayuki Miyoshi – 5.9.8
Conversios.io - All-in-one Google Analytics, Pixels and Product Feed Manager for WooCommerce: by Conversios – 7.1.6
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.18
CookieYes | GDPR Cookie Consent: by CookieYes – 3.2.6
Everest Forms: by WPEverest – 3.0.2
Facebook for WooCommerce: by Facebook – 3.2.8
FakerPress: by Gustavo Bordoni – 0.6.6
Fathom Analytics for WP: by Conva Ventures Inc – 3.2.3
Fluent Forms: by Contact Form - WPManageNinja LLC – 5.2.0
Formidable Forms: by Strategy11 Form Builder Team – 6.13
Forminator: by WPMU DEV – 1.35.0
Form Maker: by 10Web Form Builder Team – 1.15.27
FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 1.4.2.1
GA Google Analytics: by Jeff Starr – 20240820
GDPR Cookie Compliance: by Moove Agency – 4.15.2
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 8.0.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 9.0.1
GP Premium: by Tom Usborne – 2.3.1
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.20.2
Happyforms (free): by Happyforms – 1.26.1
HTTP Headers: by Dimitar Ivanov – 1.19.1
illow | GDPR, LGPD and CCPA/CPRA Cookie Consent: by illow – 0.2.0
iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: by iubenda – 3.11.0
Kali Forms - WordPress Forms Made Easy: by Kali Forms – 2.3.51
Lara's Google Analytics (GA4): by XtraOrbit Web Development SRL – 4.0.3
Lightweight Social Icons: by Thomas Usborne – 1.1
LiteSpeed Cache: by LiteSpeed Technologies – 6.4.1
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.15
Minimal Coming Soon & Maintenance Mode: by WebFactory Ltd – 2.39
Ninja Forms: by Saturday Drive – 3.8.14
OTGS Installer: by OnTheGoSystems – 3.0.4
Pixel Caffeine: by AdEspresso – 2.3.3
Pixel Cat Lite: by Fatcat Apps – 3.0.5
Pixel Manager for WooCommerce: by SweetCode – 1.43.5
PixelYourSite: by PixelYourSite – 9.7.2
Plausible Analytics: by Plausible.io – 2.1.3
Pods - Custom Content Types and Fields: by Pods Framework Team – 3.2.7
Polylang: by WP SYNTEX – 3.6.4
QQ Woocommerce Tracking: by Krzysiek Planeta – 3.4
Rank Math SEO: by Rank Math – 1.0.227
Ray Enterprise Translation: by Ray Enterprise and Frédéric Demarle – 1.6.3
Real Cookie Banner (Free): by devowl.io – 4.7.15
Remove jQuery Migrate: by Hendy Tan – 1.0.3
Seers Cookie Consent Banner Privacy Policy: by Seers – 8.1.5
ShareThis Dashboard for Google Analytics: by ShareThis – 3.2.0
Simple Analytics Official: by Simple Analytics – 1.25
Site Kit by Google: by Google – 1.134.0
Social Media and Share Icons (Ultimate Social Media): by Inisev – 2.9.2
Termly - GDPR/CCPA Cookie Consent Banner: by Termly - GDPR/CCPA Cookie Consent Banner – 3.3.0
Unbloater: by Christoph Rado – 1.6.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.4

W3 Total Cache: by BoldGrid – 2.7.5
WC Kalkulator: by Krzysztof Piątkowski – 1.6.1
Widget Options: by Widget Options Team – 4.0.6.1
WooCommerce Blocks: by Automattic – 11.7.0
WooCommerce Conversion Tracking: by weDevs – 2.0.12
WooCommerce Load More Products: by BeRocket – 1.2.0.1
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.3.7
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.5.0

WP AutoTerms: by WP AutoTerms – 2.5.1
WP Cookie Consent: by WPEkaClub – 3.4.3
WPC Smart Quick View for WooCommerce: by WPClever – 4.1.1
WPC Smart Wishlist for WooCommerce: by WPClever – 4.9.0
WPForms Lite: by WPForms – 1.9.0.4
WPML Media: by OnTheGoSystems – 2.7.1
WPML Multilingual CMS: by OnTheGoSystems – 4.5.14
WPML Sticky Links: by OnTheGoSystems – 1.5.4
WPML String Translation: by OnTheGoSystems – 3.2.3
XStore Core: by 8theme – 5.3.1
XT Floating Cart for WooCommerce: by XplodedThemes – 2.8.0
YITH WooCommerce Wishlist: by YITH – 3.37.0

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (2) ###

NinjaFirewall WP (mu-plugin): by The Ninja Technologies Network – 1.0
Plausible Analytics - Proxy Speed Module: by Plausible HQ – 1.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 94 KB

### WC Pages ###

Shop base: #3886 - /store/
Cart: #2867 - /cart-block/ -  Contains the woocommerce/cart block
Checkout: #2869 - /checkout-block/ -  Contains the woocommerce/checkout block
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Kadence
Version: 1.2.9
Author URL: https://www.kadencewp.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-09-05 11:43:56 +02:00
Options: ✔
Notes: 212
Onboarding: completed

### Action Scheduler ###

Complete: 175
Oldest: 2024-08-04 19:12:59 +0200
Newest: 2024-09-04 18:35:48 +0200

Failed: 46
Oldest: 2023-02-15 06:28:40 +0100
Newest: 2024-08-29 12:52:55 +0200

Pending: 3
Oldest: 2024-09-05 12:54:40 +0200
Newest: 2024-09-05 12:54:40 +0200

### Status report information ###

Generated at: 2024-09-04 18:58:47 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
Hi @ChrisPlaneta , thank you for reporting this.
By having a look at the React specific [error](https://react.dev/errors/60?invariant=60) I believe you are bumping into a limitation of how React works. Can you please provide more details on what you are trying to achieve so we can check if there is an alternate solution?

**Comment by ChrisPlaneta** [comment]
Sure.

I am using this hook to add Javascript <script> element with:

1. Data of a product that can be interacted with (viewed, clicked, added to cart)
2. Trigger a JS function that will make all of it possible

I found it to be the only reliable method to track interactions with products dynamically added to HTML.

The alternative to point #1 is to add product data as a json inside HTML element (hooked in the same place). This works, ok.

However, the problem is with point #2. 

If I use the solution above, then I don't know when the HTML with the product data is added to the page. There is no block hook that fires after each block is rendered and so I have to use MutationObserver (not ideal in my situation) or run a check for new products every half a second (which is also far from perfect).

I hope this sheds some more light and you can suggest something that I have not thought about.

**Comment by mikejolley** [comment]
If rendering inline is not compatible with React, you could continue to use `woocommerce_blocks_product_grid_item_html` but cache the values in memory without adjusting the HTML returned via `woocommerce_blocks_product_grid_item_html`.

Then you can render your script in the footer of the page using an action such as https://developer.wordpress.org/reference/functions/wp_footer/

Would that work?

**Comment by ChrisPlaneta** [comment]
I'm not sure if this is really the problem with React. When standard blocks are inside of other blocks, they work fine. This is how there were created. The problem is only when product blocks are inside the "cart" block with "empty" state.

I've found that there is even problem with HTML. 

When I add this HTML: `<!-- some text --><span class="sth" style="display: none">123</span>`, then the inside of the HTML comment is displayed along with the "123" text in span. See the screenshots.

![woo-cart-prod-issue](https://github.com/user-attachments/assets/93d18901-522f-4351-9b0c-f0226702928c)
![woo-cart-prod-issue-2](https://github.com/user-attachments/assets/29c76880-1c8f-4fb1-9a40-3338eb7a0f0a)

For me, it looks like a problem with sanitisation in the cart block.

**Comment by mikejolley** [comment]
@ChrisPlaneta Standard blocks are rendered as-is; exactly how they are saved to the post. 

In the context of the cart, due to its dynamic nature, saved block markup is parsed and converted back into React components. So yes, React is likely sanitising the script hence the error @wavvves pointed out here https://react.dev/errors/60?invariant=60

**Comment by ChrisPlaneta** [comment]
Hmm...I see. That is not good. I need to find a way to go around this problem. Otherwise product blocks rendered in empty cart block are impossible to track and will always give errors.

Do you know of a different hook or method I could use to add JS to product blocks to track them?

Or maybe, there is a way to find out if the product is to be rendered inside the cart block? I could use it to stop my scripts from adding any extra HTML or JS there until I find a different way to track these products.

**Comment by mikejolley** [comment]
> Do you know of a different hook or method I could use to add JS to product blocks to track them?

[My earlier suggestion.](https://github.com/woocommerce/woocommerce/issues/51155#issuecomment-2352821195) Track what products get rendered, then output the script in the footer using the product data you collected.

@senadir do you think there is a way to allow scripts to run in inner blocks? The error using the above snippet is:

```
Error: Can only set one of `children` or `props.dangerouslySetInnerHTML`.
```

The script element is including both.

**Comment by mikejolley** [comment]
I think we can skip script tags in parsing and fix this. Ill work on a PR.

**Comment by ChrisPlaneta** [comment]
@mikejolley Thank you for the fix. That was super quick!
