### ISSUE TITLE
[Enhancement]: Show actions on order screen

### ISSUE THREAD

**Issue by peterwilsoncc** [woothemes/woocommerce#51186]
### Describe the solution you'd like

In my account, the orders list shows a number of actions a purchaser can take. For example an order that is pending payment is presented with the actions Pay, View or Cancel.

![orders-listing](https://github.com/user-attachments/assets/b3d0e626-7159-4dd3-b8f0-d8fb4ec9b813)

These actions are missing from the individual order page, so once a purchaser reviews the details of an order, they need to return to the list of orders to take any action

![order-details](https://github.com/user-attachments/assets/1d683867-56dc-4c60-a1b4-c0226f82809f)

I think it would be beneficial to add the order actions to the bottom of the table below the row. Somewhere around this code in the order template. 

https://github.com/woocommerce/woocommerce/blob/a7b957dbce68fbcdf56c2a3713d71f90a1962851/plugins/woocommerce/templates/order/order-details.php#L96-L101

### Describe alternatives you've considered

I've looked for an appropriate hook to allow extensions to add an extension row to the table but haven't been able to find one. The closest I could find is `woocommerce_order_details_after_order_table_items` but adding the actions there places them between the itemized product listing and the sub-total. This is a little sub-optimal.

### Additional context

Related to Pre-Orders#507

The suggested location is based on the location of the actions in WooCommerce Subscriptions

![Screenshot 2024-09-06 at 11 55 32 AM](https://github.com/user-attachments/assets/b0bc1f25-6b34-432a-ae99-82f0387ac3b8)

**Comment by wavvves** [comment]
Tagging @nikkivias for feedback.

**Comment by jeffpaul** [comment]
@nikkivias any feedback on this item?  It's currently blocking work downstream in the Pre-Orders extension.

**Comment by alexflorisca** [comment]
@jeffpaul This will be fixed by https://github.com/woocommerce/woocommerce/pull/52756
