### ISSUE TITLE
Delayed Account Creation: "Send password setup link" flow

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#51193]
This will be the default experience/flow for the delayed account creation block:

![Screenshot 2024-09-06 at 10 43 59](https://github.com/user-attachments/assets/b844842a-56b0-4bd8-b62e-5816a067cad0)

No password field; just the button to create an account. This will be used when the "Send password setup link" setting is enabled in WooCommerce > Settings > Accounts and Privacy.

## Existing flow

To compare the flows, this is the existing _password flow_:

1. Customer enters strong password
2. Customer clicks "create account"
3. Customer is automatically logged in
4. Current order is linked to customer account
5. Confirmation shown:

![Screenshot 2024-09-06 at 10 50 57](https://github.com/user-attachments/assets/7d619e06-a466-488d-8d0a-7db3ba4c8e51)

Note that because the customer does not confirm they own the email address, we can only safely assign the current order to the account; not past orders they used this email address.

## Default "send password setup link" flow

With this flow I would suggest a few changes (will seek design approval before unblocking this task) for the following reasons:

**No auto log-in**

When a password is changed in WordPress, sessions are invalidated for security purposes. Users must log in again using the new password that was just set. Therefore I would suggest not logging them in after account creation.

Instead, I think the confirmation message should be something along the lines of "check your email address for the password setup link" instead of links to account pages.

The other benefit of this would be that by using the password setup link in the email, we know the user owns the email address.

**Assigning past orders**

In the password flow which automatically logs in the user, we only assign the new order to the account. We cannot be sure the user owns the email address because its not verified.

However, if we are using a link in the email to set the account password, we do know they own the email address. So we can assign all past orders associated with that email address to the account instead of just the most recent order.

**Account creation steps**

1. Customer clicks "Create Account" on the confirmation page
2. System creates the account and emails the customer the password setup link. _Customer is not logged in; confirmation tells them to check email_
3. Customer clicks link in email
4. Customer sets password. At this point, past orders are linked to account
5. Customer logs in and is taken to account pages

If we want to keep the automatic log-in, we could still link all past orders when using the link in email, but until that point only the current order is linked, and note, as soon as they set the new password they must log in again anyway.

**Comment by nikkivias** [comment]
Hi @mikejolley 

No auto login makes sense, but I can see now that it **_delays the promises of account creation_**. As soon as you create account, you don’t yet experience the benefits that we outline until you go through the steps of going to email, click link, set password, login, etc etc etc. 

We initially chose this flow to be the default experience because we assumed one-click meant it was the shortest flow to Create an account. _Which it is_— but no auto-login would break that deal.

I agree about changing the messaging to let them know we sent them an email password link.

Overall, I agree with your suggestions. Thank you so much for your thoroughness! Given what has come to light, I think the default experience should be where Users sets a password > Create account > and DONE

**Comment by mikejolley** [comment]
@nikkivias Should we experiment to see if we can login on creation and preserve login when setting initial password? Circumventing the logout that would normally occur.

**Comment by mikejolley** [comment]
Update @nikkivias 

I've found a simple method of keeping the user logged in after setting the password, so new flow would be:

1. Customer clicks "Create Account" on the confirmation page
2. System creates the account and emails the customer the password setup link. Customer is also logged in.
3. (optional) Customer clicks link in email
4. (optional) Customer sets password. 

During step 2 we link the current order to the new account.
During step 3/4 we can look into bringing older orders under the new account.
