### ISSUE TITLE
 Invalid Nonce from getCart / Nonce still required with Cart-Token

### ISSUE THREAD

**Issue by BintouNdy** [woothemes/woocommerce#51217]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the process of integrating the WooCommerce API for handling cart operations (e.g., adding items to the cart), I encountered an issue where the Nonce provided by the getCart API is consistently invalid. Despite receiving a valid Cart-Token, the API still requires a valid Nonce to proceed, and the one provided by getCart does not work as expected.

### Expected behavior

When Cart-Token is provided, the Nonce should not be required if the Cart-Token is sufficient for authorization.
The nonce from GetCart response should be valid when performing post

### Actual behavior

The Nonce provided by the getCart API is consistently invalid for subsequent requests.
Even with a valid Cart-Token, the API rejects the request, requiring a valid Nonce.

### Steps to reproduce

1)Perform a GET request to fetch the cart:

```
this.http.get(`${storeUrl}/cart/`, { observe: 'response' })
  .subscribe((response) => {
    this.nonce = response.headers.get('Nonce');
    this.cartToken = response.headers.get('Cart-Token');
    console.log('Nonce:', this.nonce);
    console.log('Cart-Token:', this.cartToken);
  });

private getWooHeaders(): HttpHeaders {
	return new HttpHeaders({
	'Cart-Token': this.cartToken,
	Nonce: this.nonce,
	});
}
```
2)Use the fetched Nonce and Cart-Token to add an item to the cart:
```
const url = `${this.storeUrl}/cart/add-item`;
const params = { id: productId.toString(), quantity: quantity.toString() };
return this.http
.post(url, null, {
        headers: this.getWooHeaders(),
	params,
	observe: 'response',})
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://bamgen.com
Site address (URL): https://bamgen.com
WC Version: 9.2.3
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.29
PHP Post Max Size: 128 Mo
PHP Time Limit: 360
PHP Max Input Vars: 200000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.5.25-MariaDB
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.3
WC Database Prefix: wp_
Taille totale de la base de données: 103.00MB
Taille de la base de données: 97.36MB
Taille de l’index: 5.64MB
wp_woocommerce_sessions: Données : 0.07MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_api_keys: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_woocommerce_attribute_taxonomies: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_downloadable_product_permissions: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_woocommerce_order_items: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_order_itemmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_tax_rates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_tax_rate_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zones: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zone_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_shipping_zone_methods: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_payment_tokens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_payment_tokenmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_woocommerce_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
noc_autologin: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_actionscheduler_actions: Données : 2.31MB + Index : 0.80MB + Moteur MyISAM
wp_actionscheduler_claims: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_actionscheduler_groups: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_actionscheduler_logs: Données : 1.21MB + Index : 0.97MB + Moteur MyISAM
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_e_events: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_e_submissions: Données : 0.02MB + Index : 0.27MB + Moteur InnoDB
wp_e_submissions_actions_log: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_e_submissions_values: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_gla_attribute_mapping_rules: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_gla_budget_recommendations: Données : 0.10MB + Index : 0.12MB + Moteur MyISAM
wp_gla_merchant_issues: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_gla_shipping_rates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_gla_shipping_times: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_jetpack_sync_queue: Données : 0.36MB + Index : 0.05MB + Moteur MyISAM
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_litespeed_url: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_litespeed_url_file: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_automations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_automation_runs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_automation_run_logs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_automation_run_subjects: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_automation_triggers: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_automation_versions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_custom_fields: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_dynamic_segment_filters: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_feature_flags: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_forms: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_migrations: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_mailpoet_newsletters: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_newsletter_links: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_newsletter_option: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_newsletter_option_fields: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_mailpoet_newsletter_posts: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_newsletter_segment: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_newsletter_templates: Données : 1.05MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_scheduled_tasks: Données : 0.06MB + Index : 0.02MB + Moteur MyISAM
wp_mailpoet_scheduled_task_subscribers: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_segments: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_mailpoet_sending_queues: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_settings: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_statistics_bounces: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_statistics_clicks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_statistics_forms: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_statistics_newsletters: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_statistics_opens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_statistics_unsubscribes: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_statistics_woocommerce_purchases: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_stats_notifications: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_subscribers: Données : 0.00MB + Index : 0.02MB + Moteur MyISAM
wp_mailpoet_subscriber_custom_field: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_subscriber_ips: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_subscriber_segment: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_subscriber_tag: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_tags: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_user_agents: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mailpoet_user_flags: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_mwai_chats: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mwai_files: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 12.02MB + Index : 0.14MB + Moteur InnoDB
wp_postmeta: Données : 61.48MB + Index : 1.94MB + Moteur InnoDB
wp_posts: Données : 17.48MB + Index : 0.28MB + Moteur InnoDB
wp_simple_history: Données : 0.05MB + Index : 0.02MB + Moteur MyISAM
wp_simple_history_contexts: Données : 0.58MB + Index : 0.18MB + Moteur MyISAM
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.02MB + Index : 0.02MB + Moteur MyISAM
wp_users: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_admin_notes: Données : 0.03MB + Index : 0.00MB + Moteur MyISAM
wp_wc_admin_note_actions: Données : 0.02MB + Index : 0.01MB + Moteur MyISAM
wp_wc_category_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_customer_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_download_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_orders: Données : 0.00MB + Index : 0.02MB + Moteur MyISAM
wp_wc_orders_meta: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_addresses: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_coupon_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_order_operational_data: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_product_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_stats: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_order_tax_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_product_attributes_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_product_download_directories: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_product_meta_lookup: Données : 0.01MB + Index : 0.03MB + Moteur MyISAM
wp_wc_rate_limits: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_reserved_stock: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wc_tax_rate_classes: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
wp_wc_webhooks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfblockediplog: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfblocks7: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfconfig: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
wp_wfcrawlers: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wffilechanges: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wffilemods: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfhits: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfhoover: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfissues: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfknownfilelist: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wflivetraffichuman: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wflocs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wflogins: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfls_role_counts: Données : 0.00MB + Index : 0.00MB + Moteur MEMORY
wp_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfnotifications: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfpendingissues: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfreversecache: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfsecurityevents: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfsnipcache: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfstatus: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wftrafficrates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wfwaffailures: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wrc_caches: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wrc_relations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
wp_wsal_metadata: Données : 0.09MB + Index : 0.09MB + Moteur MyISAM
wp_wsal_occurrences: Données : 0.08MB + Index : 0.03MB + Moteur MyISAM

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 211
elementor_library: 1
mailpoet_page: 1
nav_menu_item: 30
page: 18
post: 8
product: 154
revision: 993
shop_order: 3
wp_font_face: 33
wp_font_family: 12
wp_navigation: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Advanced Custom Fields PRO: par WP Engine – 6.3.3
AHS Demo Importer: par AlHikmahSoft – 1.0.0
AiNext Toolkit: par AlHikmahSoft – 1.2
Akismet Anti-spam: Spam Protection: par Automattic - Anti-spam Team – 5.3.3
Contact Form 7: par Takayuki Miyoshi – 5.9.8
Elementor: par Elementor.com – 3.23.4
Google for WooCommerce: par WooCommerce – 2.8.4
Jetpack: par Automattic – 13.8
LiteSpeed Cache: par Technologies LiteSpeed – 6.5
MailPoet: par MailPoet – 5.1.0
Pinterest pour WooCommerce: par WooCommerce – 1.4.8
Simple History: par Pär Thernström – 4.17.0
SQL Buddy: par Delicious Brains – 1.0.0
TikTok: par TikTok – 1.2.8
WooPayments: par Woocommerce – 8.1.1
WooCommerce Shipping & Tax: par WooCommerce – 2.8.0
WooCommerce: par Automattic – 9.2.3
Wordfence Security: par Wordfence – 7.11.7
WP REST Cache: par Acato – 2024.2.1
WP Activity Log: par Melapress – 5.1.0

### Inactive Plugins (1) ###

Hello Dolly: par Matt Mullenweg – 1.7.2

### Must Use Plugins (1) ###

WP REST Cache - Must-Use Plugin: par Richard Korthuis - Acato – 2021.3.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 191 Ko

### WC Pages ###

Base de la boutique: #1292 - /shop/
Panier: #1293 - /cart/ -  Contient le code court [woocommerce_cart]
Commander: #1294 - /checkout/ -  Contient le code court [woocommerce_checkout]
Mon compte: #1295 - /my-account/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: AiNext
Version: 1.2
Author URL: http://alhikmahsoft.com
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: ainext/woocommerce/archive-product.php
ainext/woocommerce/cart/cart-totals.php
ainext/woocommerce/cart/cart.php
ainext/woocommerce/cart/proceed-to-checkout-button.php
ainext/woocommerce/checkout/form-billing.php
ainext/woocommerce/checkout/form-checkout.php
ainext/woocommerce/checkout/form-shipping.php
ainext/woocommerce/checkout/payment.php
ainext/woocommerce/content-product.php
ainext/woocommerce/content-single-product.php
ainext/woocommerce/global/quantity-input.php
ainext/woocommerce/loop/add-to-cart.php
ainext/woocommerce/loop/loop-end.php
ainext/woocommerce/loop/loop-start.php
ainext/woocommerce/loop/orderby.php
ainext/woocommerce/loop/pagination.php
ainext/woocommerce/myaccount/form-edit-account.php
ainext/woocommerce/myaccount/form-login.php version 8.3.1 est obsolète. La version du noyau est 9.2.0
ainext/woocommerce/myaccount/form-lost-password.php version 9.0.0 est obsolète. La version du noyau est 9.2.0
ainext/woocommerce/myaccount/my-address.php version 8.7.0 est obsolète. La version du noyau est 9.2.0
ainext/woocommerce/single-product/add-to-cart/simple.php
ainext/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
ainext/woocommerce/single-product/meta.php
ainext/woocommerce/single-product/related.php
ainext/woocommerce/single-product/sale-flash.php
ainext/woocommerce/single-product/tabs/additional-information.php
ainext/woocommerce/single-product/tabs/description.php
ainext/woocommerce/single-product/tabs/tabs.php
ainext/woocommerce/single-product/title.php
ainext/woocommerce/single-product/up-sells.php
ainext/woocommerce/single-product-reviews.php
ainext/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### WooPayments ###

Version: 8.1.1
Connected to WPCOM: Oui
WPCOM Blog ID: 235704568
Account ID: ❌ Non Connecté
Logging: Désactivé

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Méthode d’envoi par défaut de WordPress
Task Scheduler method: Action Scheduler
Cron ping URL: https://bamgen.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-09-08 14:13:36 +02:00
Options: ✔
Notes: 74
Onboarding: completed

### Action Scheduler ###

Terminé: 7 164
Oldest: 2024-08-07 22:18:12 +0000
Newest: 2024-09-07 22:07:13 +0000

Échoué: 4
Oldest: 2023-12-07 18:36:19 +0000
Newest: 2024-09-04 21:00:56 +0000

En attente: 4
Oldest: 2024-09-07 22:09:13 +0000
Newest: 2024-09-08 21:41:55 +0000

### Status report information ###

Generated at: 2024-09-08 00:07:22 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
Nonce can be invalid for variety of reasons, like session switching between the nonce being generated and the respond being sent.

Nonce being optional for Cart-Token requests is only available as part of 9.3, which comes out tomorrow.

**Comment by bylmzio** [comment]
As @senadir said, i checked out  9.3 and it worked.
