### ISSUE TITLE
Coupons not saving allowed email 

### ISSUE THREAD

**Issue by cskindley** [woothemes/woocommerce#51220]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When an email is entered in the restriction for allowed email it does not save. Searching the database confirms the email isn’t present. The email used has never been used on the website before.

### Expected behavior

I’d expect the email to be saved and visible in the coupon restriction settings for allowed emails.

### Actual behavior

Create coupon, add restriction for allowed email, email doesn’t save when you update the coupon.

### Steps to reproduce

Create coupon, add restriction for allowed email, email doesn’t save when you update the coupon.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://completecpr.com
Site address (URL): https://completecpr.com
WC Version: 9.2.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.18
PHP Post Max Size: 750 MB
PHP Time Limit: -1
PHP Max Input Vars: 3000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.37-0ubuntu0.22.04.3
Max Upload Size: 750 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.3
WC Database Prefix: wp_wwajeh_
Total Database Size: 82.38MB
Database Data Size: 46.82MB
Database Index Size: 35.56MB
wp_wwajeh_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_actionscheduler_actions: Data: 14.02MB + Index: 18.67MB + Engine InnoDB
wp_wwajeh_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_actionscheduler_logs: Data: 11.02MB + Index: 8.30MB + Engine InnoDB
wp_wwajeh_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wwajeh_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wwajeh_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_commentmeta: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_wwajeh_comments: Data: 0.31MB + Index: 0.78MB + Engine InnoDB
wp_wwajeh_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_jetpack_waf_blocklog: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_options: Data: 1.20MB + Index: 0.08MB + Engine InnoDB
wp_wwajeh_postmeta: Data: 3.52MB + Index: 1.97MB + Engine InnoDB
wp_wwajeh_posts: Data: 5.52MB + Index: 0.30MB + Engine InnoDB
wp_wwajeh_sensei_pro_groups_courses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_sensei_pro_groups_students: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_snippets: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_term_relationships: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_usermeta: Data: 1.44MB + Index: 0.39MB + Engine InnoDB
wp_wwajeh_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_wc_customer_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wwajeh_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wwajeh_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_woocommerce_downloadable_product_permiss: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_wpforms_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_wpforms_entry_fields: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wwajeh_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_wpr_above_the_fold: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_wwajeh_wpr_rocket_cache: Data: 0.13MB + Index: 0.20MB + Engine InnoDB
wp_wwajeh_wpr_rucss_used_css: Data: 0.36MB + Index: 0.45MB + Engine InnoDB
wp_wwajeh_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_zbs_automation_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_canned_replies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_zbs_contacts: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_customfields: Data: 0.31MB + Index: 0.45MB + Engine InnoDB
wp_wwajeh_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wwajeh_zbs_externalsources: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wwajeh_zbs_lineitems: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_logs: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_mail: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_mail_campaign_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_zbs_mail_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_mail_links: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_mail_sequences: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_mail_sequences_steps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_mail_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_zbs_mail_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_meta: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wwajeh_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_object_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_product_index: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wwajeh_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_scheduled_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_settings: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_sys_cronmanagerlogs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wwajeh_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_tags_links: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wwajeh_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wwajeh_zbs_twilio_numbers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wwajeh_zbs_workflows: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

attachment: 241
aw_workflow: 22
certificate: 80
certificate_template: 3
course: 10
custom_css: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
lesson: 343
nav_menu_item: 22
page: 20
post: 7
product: 20
question: 205
quiz: 343
sensei_email: 19
shop_coupon: 2
shop_order: 2
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 4
wp_template: 30
wp_template_part: 7
wpcf7_contact_form: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

WP Frontend Delete Account: by Mini Plugins – 2.3.0
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
AutomateWoo: by WooCommerce – 6.1.0
Code Snippets Pro (Premium): by Code Snippets Pro – 3.6.5
Contact Form 7: by Takayuki Miyoshi – 5.9.8
Customize My Account Page For Woocommerce: by WPEverest – 0.4.8
DreamHost Panel Login: by DreamHost
danielbachhuber – 1.0.0

Head & Footer Code: by Aleksandar Urošević – 1.3.5
Headers Security Advanced & HSTS WP: by 🐙 Andrea Ferro – 5.0.40
Jetpack VaultPress Backup: by Automattic - Jetpack Backup team – 2.9
Jetpack VideoPress: by Automattic - Jetpack Video team – 2.1
Jetpack: by Automattic – 13.8
Jetpack CRM Extension: Advanced Segments: by Automattic – 2.0.5
Jetpack CRM Extension: Automations: by Automattic – 1.5.7
Jetpack CRM Extension: Client Portal Pro: by Automattic – 2.2.2
Jetpack CRM Extension: Contact Form 7 Connector: by Automattic – 2.9.3
Jetpack CRM Extension: CSV Importer PRO: by Automattic – 2.2.5
Jetpack CRM Extension: Invoicing Pro: by Automattic – 2.8.2
Jetpack CRM Extension: Sales Dashboard: by Automattic – 2.8.0
Jetpack CRM Extension: System Emails Pro: by Automattic – 1.4.0
Jetpack CRM Extension: Twilio Connect: by Automattic – 1.7.2
Jetpack CRM Extension: WordPress Utilities: by Jetpack – 1.3
Loco Translate: by Tim Whitlock – 2.6.11
Redis Object Cache: by Till Krüss – 2.5.3
Sensei LMS Certificates: by Automattic – 2.5.2
Sensei LMS: by Automattic – 4.24.3
Sensei Pro: by Automattic – 1.24.1
Transients Manager: by WPBeginner – 2.0.5
Big File Uploads: by Infinite Uploads – 2.1.3
User Switching: by John Blackbourn – 1.8.0
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.16
Force Sells for WooCommerce: by Kestrel – 1.5.1
WooPayments: by WooCommerce – 8.1.1
WooCommerce Shipping & Tax: by WooCommerce – 2.8.0
WooCommerce Shipping: by WooCommerce – 1.1.1
WooCommerce: by Automattic – 9.2.3
WordPress Importer: by wordpressdotorg – 0.8.2
WP Mail SMTP: by WP Mail SMTP – 4.1.1
WP Rocket: by WP Media – 3.16.4
WPForms: by WPForms – 1.9.0.4
Jetpack CRM Extension: Mail Campaigns: by Jetpack – 2.5.2
Jetpack CRM: by Automattic - Jetpack CRM team – 6.4.4

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Redis Object Cache Drop-In

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 90 days
Level threshold: –
Log directory size: 489 KB

### WC Pages ###

Shop base: #7449 - /catalog/
Cart: #7450 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7451 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #7452 - /my-account/
Terms and conditions: #1259 - /terms/

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/dh_nxbkat/completecpr.com/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/dh_nxbkat/completecpr.com/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/dh_nxbkat/completecpr.com/wp-content/plugins/woocommerce/templates/block-notices/success.php

### WooPayments ###

Version: 8.1.1
Connected to WPCOM: Yes
WPCOM Blog ID: 225537871
Account ID: acct_1OS6UkCGL0OrV71T
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card,afterpay_clearpay
WooPay: Disabled
WooPay Incompatible Extensions: Yes
Apple Pay / Google Pay: Disabled
Fraud Protection Level: basic
Multi-currency: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-09-09 11:22:28 -06:00
Options: ✔
Notes: 42
Onboarding: completed

### Action Scheduler ###

Complete: 43,854
Oldest: 2024-09-01 12:59:09 -0600
Newest: 2024-09-08 12:57:48 -0600

Failed: 47
Oldest: 2024-09-02 19:16:03 -0600
Newest: 2024-09-08 11:00:45 -0600

Pending: 30
Oldest: 2024-09-08 12:58:48 -0600
Newest: 2024-09-15 11:00:45 -0600

### Status report information ###

Generated at: 2024-09-08 12:58:22 -06:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adimoldovan** [comment]
Thanks @cskindley for reporting this. Can you please check https://github.com/woocommerce/woocommerce/issues/51220? Looks like the same issue?

**Comment by cskindley** [comment]
> Thanks @cskindley for reporting this. Can you please check #51220? Looks like the same issue?

#51220 is this report!

**Comment by adimoldovan** [comment]
> #51220 is this report!

Oh, I'm sorry @cskindley, my mistake. I meant to paste the link to another issue. I checked that issue again though and it's not the same.

**Comment by barryhughes** [comment]
@cskindley I don't see any problem, but we are aware of an issue that impacts users of the Safari web browser when interacting with email-type inputs (specifically, inputs that accept multiple email addresses, like this one).

That leads me to ask, are you using Safari? If so, does switching to another browser resolve this?

**Comment by cskindley** [comment]
> @cskindley I don't see any problem, but we are aware of an issue that impacts users of the Safari web browser when interacting with email-type inputs (specifically, inputs that accept multiple email addresses, like this one).
> 
> That leads me to ask, are you using Safari? If so, does switching to another browser resolve this?

Happens on both Safari and Chrome.

Here’s a screen capture vid: https://videopress.com/v/j8PWFFxt

I’ll keep the video up for a week.

**Comment by barryhughes** [comment]
Thanks for sharing that. Was that captured via an iPad, and can you see the same on a desktop (other than with Safari)? Asking just to tease out the possibility that we're still looking at a Safari bug (iirc, at least in the past, all browsers running on iOS were ultimately powered by the same web engine provided by that platform—so it seems that could be a possibility, here).

**Comment by barryhughes** [comment]
Additionally, the screencast shows that various other plugins are installed. Can I just take a moment to verify that you are indeed able to verify this when no other plugins are active?

**Comment by cskindley** [comment]
> Thanks for sharing that. Was that captured via an iPad, and can you see the same on a desktop (other than with Safari)? Asking just to tease out the possibility that we're still looking at a Safari bug (iirc, at least in the past, all browsers running on iOS were ultimately powered by the same web engine provided by that platform—so it seems that could be a possibility, here).

Yes, captured via iPad Pro. It’s 2024 and I haven’t used a desktop in over 14 years. Haven’t used a laptop in 3 years. The iOS is up to date as of this posting at iPadOS version 17.6.1 (21G93).

Automattic/JetPack/Woo and all their other brands need to be compatible with iOS and Android devices.

**Comment by cskindley** [comment]
> Additionally, the screencast shows that various other plugins are installed. Can I just take a moment to verify that you are indeed able to verify this when no other plugins are active?

As originally reported in the bug report the very last section titled:

“Isolating the problem

 I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
 This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
 I can reproduce this bug consistently using the steps above.”

were all checked.

In addition the vast majority of plugins are all Automattic/JetPack/Woo authored plugins.

**Comment by barryhughes** [comment]
Thanks! 

I was checking on that last point, both because that was not apparent from the screencast and because experience has shown lots of people check those boxes, thinking they have to (and so they are not always reflective of the steps the reporter has taken).

> In addition the vast majority of plugins are all Automattic/JetPack/Woo authored plugins.

Sure, but, that doesn't mean conflicts cannot occur. If there *was* a conflict, we'd still want to identify it.

In any case: given the iOS web browser dimension (may or may not be a factor, as Apple's policy on this has changed [in at least some geographies](https://www.theverge.com/2024/1/25/24050478/apple-ios-17-4-browser-engines-eu)), it seems this may be a possible duplicate of https://github.com/woocommerce/woocommerce/issues/49362.

**Comment by barryhughes** [comment]
Closing as a duplicate, per last note.
