### ISSUE TITLE
Product Collection: Standardize filers names' case

### ISSUE THREAD

**Issue by WunderBart** [woothemes/woocommerce#51233]
Let's make PC filters' casing consistent. Right now, they vary all over the place:

<img width="165" alt="Screenshot 2024-09-09 at 16 45 54" src="https://github.com/user-attachments/assets/a4531791-0e34-4970-916a-e006dcb2c5f9">

I suggest going with the **Title Case**:

| Current Filter Casing        | Suggested Casing           |
|----------------------------|----------------------------|
| On Sale                    | -                  |
| Stock status               | Stock Status               |
| Hand-picked Products       | Hand-Picked Products       |
| Keyword                    | -                  |
| Product Attributes         | -                  |
| Product categories         | Product Categories         |
| Product tags               | Product Tags               |
| Featured                   | -                  |
| Created                    | -                  |
| Price Range                | -                  |

**Comment by WunderBart** [comment]
Should we also make the filers' names more streamlined and consistent by removing the redundant "product" from them? For example:

- On Sale ➜ On Sale
- Stock Status ➜ Stock Status
- Hand-Picked Products ➜ Hand-Picked
- Keyword ➜ Keyword
- Product Attributes ➜ Attributes
- Product Categories ➜ Categories
- Product Tags ➜ Tags
- Featured ➜ Featured
- Created ➜ Created
- Price Range ➜ Price Range

cc: @imanish003 @kmanijak @ObliviousHarmony @xristos3490 @j111q

**Comment by kmanijak** [comment]
I like the idea, definitely!

> Product Attributes ➜ Attributes
> Product Categories ➜ Categories
> Product Tags ➜ Tags

It's nuanced but `Tags` and Product Tags` are different taxonomies (same for Categories vs Product Categories) so I'm wondering if we should do it. On the other hand, there's no "Product" in admin navigation so I'm ok with simplifying. Editing Product Collection should be obvious we're in "product" domain: 

<img width="163" alt="image" src="https://github.com/user-attachments/assets/efe47255-4548-4b31-9820-3c4881044221">

**Comment by imanish003** [comment]
> It's nuanced but Tags and Product Tags` are different taxonomies (same for Categories vs Product Categories) so I'm wondering if we should do it. On the other hand, there's no "Product" in admin navigation so I'm ok with simplifying. Editing Product Collection should be obvious we're in "product" domain:

After reading this, I am not sure if we should do it. I don't have strong feelings about it, but it might be a bit confusing for some users, so IMO it's better to keep it as it is. 

Regarding "Hand-picked Products" vs "Hand-Picked", I think it's okay to remove "Product" from "Hand-picked Products". This aligns with other concise filter names like "Featured" and "On Sale".
