### ISSUE TITLE
Dynamically set plugin_name when redirecting to Jetpack Auth

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#51248]
The new passwordless authentication on WCCOM displays a different title and subtitle depending on the value of plugin_name. Currently, the core profiler has a hardcoded plugin_name. Update the value dynamically so that we can display a different title based on the selected plugin.

## Acceptance criteria

**WooPayments**
```
Given a user on the core profiler's extensions page
When the user selects `WooPayments` and `Jetpack`
Then set [plugin_name](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/core-profiler/index.tsx#L311) to `woocommerce-payments`
```

**Order Attribution**
TBD

**Comment by chihsuan** [comment]
Hey @moon0326  If users select `WooPayments` without selecting `Jetpack`, but Jetpack is already installed, should we also set `plugin_name` to `woocommerce-payments`? 🤔

**Comment by moon0326** [comment]
@chihsuan I think so. `plugin_name` is used to [determine](https://github.com/Automattic/wp-calypso/pull/93163/commits/73adefb5767639be9e527d5580319ca6920022df#diff-af36267901f79bfab39d29ba249bbb3fb65fe581616b37a37bc5ea1e03e9ab10R239) the title.
