### ISSUE TITLE
Add option to simulate PHP error before WordPress has loaded

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#51317]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
In https://github.com/woocommerce/woocommerce/issues/51301, it was determined the remote error logging feature may fall into a failing state when it reports on errors thrown before WordPress has loaded.

To help test fixes for this, the beta tester tooling adding in https://github.com/woocommerce/woocommerce/pull/50425 could be refined to simulate an error early in the request lifecycle before WordPress is available.

**Comment by chihsuan** [comment]
> To help test fixes for this, the beta tester tooling adding in https://github.com/woocommerce/woocommerce/pull/50425 could be refined to simulate an error early in the request lifecycle before WordPress is available.

To simulate an error early in the request lifecycle but also need to be in the woocommerce context,  we'll need to add a hook that runs during the woocommerce loading process but before pluggable functions are loaded.

```
https://github.com/WordPress/wordpress-develop/blob/47122105f20624e5a6b8ed151d732157f2f2605c/src/wp-settings.php#L519-L538

- beta tester plugin loaded
- woocommerce plugin loaded <--- simulate an error here
- do_action( 'plugin_loaded', $plugin );  <--- or here

- WP Load pluggable functions
- do_action( 'plugins_loaded' );
```



I'm not sure if there's a hook that runs at that point in the WooCommerce loading process. If there isn't, I think we could hook into `plugin_loaded` and call a WC function that triggers an error.

**Comment by rjchow** [comment]
This is amazing, I thought about it and couldn't quite come up with a solution to simulate an early-stage error!
