### ISSUE TITLE
[Enhancement]: Allow Coming Soon mode to be configurable/deactivated entirely

### ISSUE THREAD

**Issue by martymi** [woothemes/woocommerce#51389]
### Describe the solution you'd like

The new coming soon mode is creating distracting UI elements in the WP toolbar, leading to confusion. Have an option in the settings page to disable Coming Soon mode entirely. If not possible, please consider the other suggestions here:
https://github.com/woocommerce/woocommerce/pull/50775#issuecomment-2349967819

See also:
https://wordpress.org/support/topic/new-live-label-on-wordpress-toolbar-why/
https://wordpress.org/support/topic/live-admin-bar/

**Comment by scottybo** [comment]
Agree with this sentiment. This is confusing our customers no-end, and doesn't add any value - it simply reduces available space in the admin bar.

For example, one of our customers is an events company, and they host live events online. To have this "Live" button suddenly appear in the admin area just doesn't make any sense. In addition, the site is live, and has been live for over 10 years. It never goes into maintenance mode.

This badge is a completely useful "feature".

**Comment by shameemreza** [comment]
Another report here: 8733846-zen
Thread: https://wordpress.org/support/topic/how-can-i-completely-disable-site-visibility-functionality/

**Comment by rajwpdev117** [comment]
8735643 - zen

Thread: https://wordpress.org/support/topic/option-to-edit-coming-soon-page-from-pages-area-or-disable-site-visibility/

**Comment by blogtutor** [comment]
+1

I understand why you might want a "Coming Soon" notice in the admin bar, but there should not be a "Live" notice.

**Comment by adrianduffell** [comment]
For the time being, I think your best bet is to remove the badge with code using the [filter here](https://wordpress.org/support/topic/new-live-label-on-wordpress-toolbar-why/#post-18013418) or via a plugin like [Admin Bar Editor](https://wordpress.org/plugins/admin-bar/), which provides full customization over the admin bar. Please let us know about the viability of these solutions. Unfortunately, we don’t normally provide settings to remove UI elements as it can create an overwhelming amount of choices for users. This is explained more in the [WordPress philosophy](https://wordpress.org/about/philosophy/).

We hope for the badge to unlock a new use-case where store owners can easily place their store back into coming soon mode and make updates in private. This is a tactic Apple takes with their online store during their new product presentations for example, and may be interesting to Woo store owners as well.

In a worse-case scenario, it also serves as a visual alert to help where the store is accidentally placed in the wrong mode. Admin users have the coming soon protections bypassed and may not be aware it’s happened without the visual cue.

The feedback has been valuable here and we'll continue to monitor it before making next decisions.

**Comment by scottybo** [comment]
@adrianduffell thanks for this, but it's not really a viable solution when you manage hundreds of sites...

It's a bit of an odd choice, to show a badge to 100% of people when it only impacts 0.1% of store owners. Perhaps one to keep just for wordpress.com sites?

The irony is that there was never a risk of putting the site into the "wrong mode" before this feature was rolled out.

**Comment by adrianduffell** [comment]
> It's a bit of an odd choice, to show a badge to 100% of people when it only impacts 0.1% of store owners. 

@scottybo We do expect a significant amount of live site owners to use the badge as time goes on. The placement is based on user testing sessions conducted WordCamp Europe and overwhelming feedback to include the status in the admin bar.

>  it's not really a viable solution when you manage hundreds of sites

I sympathize with this. Are you finding a large amount of your users have concerns with the badge? How would you normally customize the sites in bulk?

**Comment by blogtutor** [comment]
> This is a tactic Apple takes

Comparing WooCommerce stores to the Apple store is silly. The same "rules" don't apply to them.

Seems so strange that Woo would spend any time adding this feature, when it's something that's so rarely needed and so easily solved with [dozens of existing free plugins](https://wordpress.org/plugins/search/coming%20soon/). 

Regardless, if you're going to keep this feature, the "Coming Soon" badge makes a lot of sense -- it'll probably be noticed more reliably than a regular Admin notice (which most users seem to be completely blind to).  

**I really only take issue with the unnecessary `Live` notice. Is there a filter to remove just the `Live` ?**

**Comment by scottybo** [comment]
I'd be curious to know the sample size of the number of users involved in the testing sessions at WordCamp Europe, and how the survey was conducted.

Agree with @blogtutor about not showing the Live notice.

The default state of a WooCommerce store is to be "live". So this notice should only show when it's not (just like most of the plugins out there, you only know it's maintenance mode when maintenance mode is enabled).

As for how I'd normally customise sites in bulk - I don't, that's the issue.

**Comment by ShaneSchroll** [comment]
@blogtutor No filter, but you can use this action to solve it.
Same here, our clients have reported mis-clicks on this instead of the homepage button to view changes.

This is what I did personally.
In `functions.php` add this:

```
add_action( 'admin_head', 'admin_head_css' );
function admin_head_css() {
  ?>
  <style type="text/css">
    #wp-admin-bar-woocommerce-site-visibility-badge { display: none !important; }
  </style>
  <?php
}

**Comment by CharlieLivingston** [comment]
There is arguably value in showing a 'Coming soon' badge in the menu, though even then I would say it is highly visible. However, I am firmly of the opinion that there is no need for such a prominent 'Live' badge. It is the most prominent UI element in the dashboard and it is communicating unnecessary information. Once a site is set Live, that is usually it. It's not like store owners are going to be regularly switching between Live and Coming Soon. So there is just no value in been constantly reminded that the store is in Live mode, not to mention how distracting it is visually.

**Comment by martymi** [comment]
Had one client who wanted an explanation for this change ask about switching to shopify today. Small details like this add up.

> We hope for the badge to unlock a new use-case where store owners can easily place their store back into coming soon mode and make updates in private. This is a tactic Apple takes with their online store during their new product presentations for example, and may be interesting to Woo store owners as well.

There seems to be an assumption built in here that WooCommerce store/products are the main focus of the site. For many WP sites that also use Woo, this is not the case. If we have a news site selling some t-shirts, this kind of feature broadcast to the entire installation makes little sense. The footprint Woo is leaving on the entire dashboard has been growing exponentially. 

For many folks the complaint has to do with unnecessary/distracting UI element of the LIVE label on the toolbar not with the functionality itself, though IMO coming soon mode makes sense as a separate plugin not an integral part of the ecommerce plugin. I don't expect Woo to completely unwind the functionality but the UI change is clearly a point of frustration.

**Comment by raabmar** [comment]
I also got a phone call today from a client - he was shocked as it seemed that the coming soon site is Live now. It's connected to an ERP and there was immediate panic. Almost everyone is upset because of how this went down

**Comment by keeslamper** [comment]
Please remove his function or disable by default. Get unnecessary tickets from clients with questions about these feature.

**Comment by sybrew** [comment]
This feature shouldn't be part of the plugin at all. It's out of its scope.

**Comment by riegeo** [comment]
Please add an option to disable these labels. They confuse people. Especially when a shop is live for a long time. There's no need to tell that its live. Or show the label only if its in "coming soon" mode. But with the option to disable.it

**Comment by singhpaul** [comment]
This feature in its entirety should be a plugin, not a part of Woo core. Failing that, the behavior should be to display nothing in the admin bar unless the site is not live. This is useless clutter that is confusing clients.

**Comment by adrianduffell** [comment]
Thanks for the feedback, everyone. 

I believe we at Woo made a mistake by not including a setting to remove the badge. We would like to address this by adding a new setting under the Advanced > Features settings screen. This will treat the badge as a customizable feature in core that can be turned on/off at will.

![image](https://github.com/user-attachments/assets/78cfe8ce-f874-48db-9d7f-bbdc964b05c4)


Please let me know your thoughts.

We would like to enable the feature by default for now. At present, we see significant usage of the live -> coming soon flow supported by the badge (1000+ unique tracked sites per day). We are interested to see how this develops and whether the flow becomes a routine habit for many users. If it doesn't turn out, another solution is to show the badge in coming soon mode only.

In addition to the checkbox, the setting can be controlled by an option value. This could be used as part of a script to remove it from many sites at once:

```
update_option( 'woocommerce_feature_site_visibility_badge_enabled', 'no' );
```

We would also like to address the confusion when sites are in a staging environment. We are interested whether it could be solved by checking [wp_get_environment_type](https://developer.wordpress.org/reference/functions/wp_get_environment_type/) and changing the label when `staging` is returned. Is this environment type commonly used in your staging environments?

<img width="1792" alt="staging settings" src="https://github.com/user-attachments/assets/6e477599-3a0e-487e-9cbb-6fc11e0846eb">

**Comment by blogtutor** [comment]
This is great! Thank you for being so responsive to community feedback.

As proposed above, though, it won't do all that much to solve the primary problem:  A `Live` badge is appearing on sites and confusing/concerning users. To solve that:

1. Please make the badge display feature _off_ by default for existing Woo installations, and (maybe) _on_ for new ones.

That way users who have never used Coming Soon mode won't be surprised by the `Live` badge (which is the biggest concern raised here).  But if they _do_ enable Coming Soon mode, they'll understand why the badges might be displayed -- because they enabled the mode explicitly at some point.

2. I also suggest putting the option to display the badge on the Site Visibility Tab, rather than burying it in the `Advanced > Features` tab. Otherwise, if the badge is on by default, and there's this hard-to-find option, nobody will know how to turn it on or off anyway. Perhaps this checkbox could be in both places?

**Comment by singhpaul** [comment]
TBH, even with the feature deliberately turned on, the live badge seems superfluous. In most frameworks, CMS platforms and even WP itself, the default state is understood as the site being live. The flag deviates from convention not just on a general scale but with WP as well, so it's a confusing and obtrusive UX mechanic, even for those who are familiar with the WP ecosystem. IMHO, it's the sort of admin panel pollution that Class A plugins should avoid.  

All that said, at minimum, yes, please make it so the feature can be turned off. 

If the live flag was removed (or optional) we would find value with your proposed feature extension of displaying a flag in staging and dev environments. I have to confess that I wasn't aware of _wp_get_environment_type_ and so we've been setting our own environment global and display a UX notice when not in prod. There's no reason we couldn't switch to using _wp_get_environment_type_ on Woo sites. If this featureset is added, please include support for all base environment types supported by _wp_get_environment_type_, especially staging and dev.

**Comment by martymi** [comment]
Thanks you @adrianduffell and team for considering the issue thoughtfully and responding accordingly.

I really like the idea of the setting under Advanced! This is generally the spirit of my request so I am pleased with that. 

That said, my gut says _the setting's scope should enable/disable the entire coming soon mode_ in Woo. If there is a need for more fine detail control of the badge with coming soon mode ON, then the badge setting could be under the CS tab. 

From the reception of the new badge it sounds like CS is a feature a select portion of installs will ever make use of. One less tab in the options, one less area for confusion, and hopefully a little less bloat in the process. And if you want those features, it's only an updated setting away.

**Comment by JapeNZ** [comment]
Hi @adrianduffell,
Will you be adding the ability to customize the coming soon page if we're not using blocks?

I currently use a 3rd party plugin for a coming soon page and appreciate how useful a feature it can be, but if I can't customize the page appearance it's completely unusable.

If I can't customize the page, I need to be able to completely deactivate the Woo coming soon option.
I'm concerned if it can't be deactivated completely it will potentionally create a conflict with 3rd party plugins already being used for the same purpose, plus the Woo coming soon option is just bloat if it's not usable.

If you can add the option to customize the coming soon page when not using blocks, great!
I'd happily use a built in function instead of a 3rd party plugin.

Having the option to hide or only display the admin bar label when in coming soon or staging mode would be good.
The site is live 99% of the time, and I don't need a label to tell me it's live.

Alternatively you could add the option to switch between live and coming soon from a dropdown option in the label.
In this case perhaps the 'live' label could be displayed in the standard style, and only the 'coming soon' label be negative so it stands out.

**Comment by sybrew** [comment]
Instead of adding this feature to WooCommerce, please add it to WordPress Core and let plugins listen to a flag.

This way, all WordPress sites can benefit from it. 

5ftf.

**Comment by adrianduffell** [comment]
We have the setting merged now and  scheduled for the 9.4 release. If you would like to test it, the latest beta is available on the [dev blog.](https://developer.woocommerce.com/2024/09/20/woocommerce-9-4-pre-release-updates/).

Thanks again for the feedback. We will continue to monitor discussions about the badge and consider further changes.

At this stage, we have decided to keep it enabled by default because we're seeing considerable usage from existing Woo installations already. It maybe confusing for those users to suddenly lose the badge in the next release. We would also like to keep the badge as a separate feature to the coming soon mode / site visibility settings. It can essentially be disabled by having the site visibility settings in live mode already, so adding an extra setting on top of this adds complexity.

I would like to address staging sites and support classic / non-block themes in our pipelines. We will seek further feedback about it in the [GitHub discussions](https://github.com/woocommerce/woocommerce/discussions/categories/coming-soon-mode) later this month.

**Comment by raabmar** [comment]
@adrianduffell not sure if I understand correctly. You add a "Live" badge that confuses everyone, requires us to explain to the client, etc. ..then you keep it for a few weeks annoying many with it leading to hundreds of discussions, then you check some analytics and argument that you see considerable usage from existing Woo installations so you cannot take it away anymore

Did I miss something? For your information, I kept it enabled and didn't add custom code to get rid of this, because I believed that it'll be gone within a few days anyways

**Comment by riegeo** [comment]
> At this stage, we have decided to keep it enabled by default because we're seeing considerable usage from existing Woo installations already.

I have no idea how you get your statistics so I could be completely wrong. But isn't it that every installation that does the update has the "Live" Badge enabled? I mean there is no way to remove it right now. So an what do you base your statistics if anybody that does the update is probably force to see the badge?

People that have removed it with some kind of hack, are certainly in the minority, but I'm not sure I would make decisions based on that.

Anyway, thanks for giving us the option to remove it.

**Comment by sybrew** [comment]
Two things can be true at the same time. 

1. The Live mode badge is ridiculous and should be removed.
2. The Coming Soon mode badge should stay so people know they should switch to Live mode.

Also, having yet another option isn't helpful — decisions, not options.

Please reconsider.

**Comment by blogtutor** [comment]
> It can essentially be disabled by having the site visibility settings in live mode already,

@adrianduffell Could you please clarify what you mean by this?  Are you implying that sites that have never used the new "Coming Soon Mode" will no longer get the `Live` badge? (if so, that would be excellent!)

**Comment by singhpaul** [comment]
> At this stage, we have decided to keep it enabled by default because we're seeing considerable usage from existing Woo installations already. It maybe confusing for those users to suddenly lose the badge in the next release. 

I would think there are orders of magnitude more users who are confused by the badge suddenly appearing (and thus will welcome its disappearance) than the subset whose sites have been upgraded and will have grown an affinity/expectation of the badge being there and will thus now be confused when it's gone.  

> We would also like to keep the badge as a separate feature to the coming soon mode / site visibility settings. 

Could you please explain? Apologies if I'm not understanding but isn't the whole point of the badge to indicate the status of the coming soon/site visibility setting? How are they separate?

If there are future planned uses for the badge then IMO that would be the time (with pre-discussion hopefully) to decide whether to have it enabled by default.

**Comment by njwgh** [comment]
> _the setting's scope should enable/disable the entire coming soon mode in Woo

This is my feeling as well.  The 'apply to store pages only' option actually breaks my site, so I don't want the option available at all.

**Comment by superbmario** [comment]
I really wish this feature was created as an external plugin. It would have saved everyone involved a lot of pain.

I can't help but wonder why it wasn't, it feels like such a lack of common sense. There was even feedback suggesting that specific point at https://developer.woocommerce.com/2024/07/11/woocommerce-9-1-coming-soon-product-lookup-optimizations-and-checkout-styling-galore/

**Comment by raabmar** [comment]
It seems this battle is not to win - weeks later I am still annoyed by it. I believed the community will win here, but no say in it. I started implementing custom code now to get rid of this. It's small things overall, but they give a very bad taste and makes me more and more looking at other solutions

**Comment by ablears** [comment]
I'm a super admin looking after hundreds of Woo sites across a few networks, and we've had store owners wondering why their sales tanked, it turns out they were in "coming soon" mode rather than live. The coming soon status is far too prominent in the admin bar.
