### ISSUE TITLE
[Enhancement]: Update tests to consider 3rd-party UI elements.

### ISSUE THREAD

**Issue by mynewvk** [woothemes/woocommerce#51394]
Hello there,

I've faced an issue with QIT, and support suggested creating an issue on GitHub.

Because of the UI tests, I cannot release a new version of my plugin.

Currently, I face 2 issues, but I believe there can be more issues with tests like that:

1) The test that checks the "Advanced" tab in the edit product page fails because it also found my subsection called "Advanced Options":

I believe you can find your elements by an ID or find elements related to WooCommerce core based on some wrapper. Finding information by text is a bad idea, in my opinion. I had to rename our section to "Additional options."
![image](https://github.com/user-attachments/assets/b77fa81f-9a14-46e5-8a5b-9316ff171a1a)
![image](https://github.com/user-attachments/assets/0aebaa99-e2f7-4787-bcec-0830fd288f7a)

2) I have the same issue with the button on the order page. The one from our plugin is called "Recalculate with tiered pricing," it conflicts with the test that finds the "Recalculate" button.
![image](https://github.com/user-attachments/assets/5859ad5e-1dc7-44ac-b918-d79b7567269b)

It worked fine for the previous updates. It just ignored those tests and let us release the new version, but now those tests are mandatory to pass.

I hope you'll be able to solve this soon. 

Thank you!

**Comment by rodelgc** [comment]
Thank you for raising this @mynewvk. While we cannot give an ETA yet, you may submit a PR for it and we'll review it as soon as we can.

**Comment by mynewvk** [comment]
What should I do to release a new version of my plugin and skip those tests?

**Comment by lanej0** [comment]
Hey @mynewvk -- I [opened a PR](https://github.com/woocommerce/woocommerce/pull/51945) to update the locators on those two e2e tests.  It should make them more specific and unblock your specific submission.

Sorry about that!  It's a band-aid solution, and this definitely will crop up again in the future.  If you feel comfortable doing so, I'd encourage you  to submit a PR and propose updates to the tests yourself.  We'll test those PRs and ensure they don't break compatibility in other areas.

**Comment by lanej0** [comment]
I was talking to the QIT folks, and that failure in the e2e tests should have flagged a warning, but shouldn't have blocked your submission. 

Were you blocked entirely?  Let me know, I'd like to follow up with them if there is a bug here!

**Comment by mynewvk** [comment]
Hello @lanej0,

Thank you, sounds good!

Yes, the plugin update was blocked by not passing those two tests, so I had to rename the button and the "Advance options" section to release the new version.

**Comment by lanej0** [comment]
Going to ping @MrJnrman here for visibility on a potential qit bug
