### ISSUE TITLE
[Enhancement]: AJAX Notifications everywhere

### ISSUE THREAD

**Issue by fesarlis** [woothemes/woocommerce#51400]
### Describe the solution you'd like

There should be an option to deliver all notifications via AJAX. Not doing so causes many problems.

### Describe alternatives you've considered

This thread discusses the issue, your colleague claims he forwarded this to DEV team 2 years ago.

https://wordpress.org/support/topic/notices-after-ajax-add-to-cart/

**Comment by mikejolley** [comment]
This is a potential solution to https://github.com/woocommerce/woocommerce/issues/51399 but I think we only need to track https://github.com/woocommerce/woocommerce/issues/51399 so I'll close this one.
