### ISSUE TITLE
[DOC-BUG] Where can security issues for plugins sold on woocommerce.com be reported?

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#51403]
## Link to the Page/Section

https://developer.woocommerce.com/docs/reporting-security-issues/

## Description of the Suggestion

It is unclear where security issues for plugins sold on woocommerce.com can be reported to.
When selecting "Asset" on hackerone, I see "WooCommerce" with description:
>Any security issues on the WordPress WooCommerce plugin (https://wordpress.org/plugins/woocommerce/) and/or https://woocommerce.com/

Therefore I assume this is only for Woocommerce itself?

## Reason for the Suggestion

I found a severe security issue in automatewoo plugin that allows full take over of any WP site that runs automatewoo, but it's not clear where I can report it.

**Comment by tammullen** [comment]
Thanks for this suggestion @kkmuffme ! It does need to be clearer

In the meantime you can use that HackerOne WooCommerce asset to submit an issue. 

> ## Platform(s) Affected:
> [website/mobile app/service]

In this section you can state it is for AutomateWoo

**Comment by puntope** [comment]
https://hackerone.com/automattic

**Comment by mikkamp** [comment]
> I found a severe security issue in automatewoo plugin that allows full take over of any WP site that runs automatewoo, but it's not clear where I can report it.

@kkmuffme Is this issue still present, I wasn't able to find any report. If it's still possible to reproduce could you report the details in [hackerone](https://hackerone.com/automattic)?
