### ISSUE TITLE
"Default customer location" setting should only apply to country and not to state/region

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#51409]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the setting Default customer location is set to Shop country/region, at checkout both the country and region are automatically pre-selected.
However, this solution doesn't really make sense because stores may have most of the orders from their country but not necessarily from their region.

For example:
store based in Italy in the region of Lombardia
the store wants to sell in the whole european union, however most of the orders come from Italy, but not necessarily from the store's region (Lombardia).
So it would make sense to auto-select Italy as country to avoid most of the shoppers going through the entire country list of the EU, but then it doesn't really make sense to auto select the region in this case.

It would be nice to be able to decide whether only the country or both country and region should be auto-selected.

### Expected behavior

It should be possible to auto select the country but not the region

### Actual behavior

It is not possible to only auto-select the country without auto-selecting the province.

### Steps to reproduce

1. in WooCommerce > Settings, add the store location
2. in WooCommerce > Settings, select Default Customer Location -> Shop country/region
3. Go to checkout. User's shipping information should not be already added, otherwise they will be shown as default.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://tommasop57.sg-host.com
Site address (URL): http://tommasop57.sg-host.com
WC Version: 9.4.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.23
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.4

SUHOSIN Installed: –
MySQL Version: 8.0.36-28
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.4.0
WC Database Prefix: mda_
Total Database Size: 9.53MB
Database Data Size: 7.77MB
Database Index Size: 1.76MB
mda_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mda_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mda_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mda_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mda_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
mda_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
mda_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_options: Data: 6.11MB + Index: 0.06MB + Engine InnoDB
mda_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
mda_posts: Data: 0.52MB + Index: 0.06MB + Engine InnoDB
mda_sgs_log_events: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
mda_sgs_log_visitors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mda_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
mda_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
mda_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mda_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mda_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mda_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mda_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
mda_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mda_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
mda_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mda_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mda_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 8
page: 8
post: 2
product: 6
product_variation: 2
revision: 47
wp_font_face: 39
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 1
wp_template: 4
wp_template_part: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Gutenberg: by Gutenberg Team – 19.2.0
Speed Optimizer: by SiteGround – 7.6.5
Security Optimizer: by SiteGround – 1.5.4
WooCommerce: by Automattic – 9.4.0-dev

### Inactive Plugins (1) ###

SiteGround Central: by SiteGround – 3.1.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 10 KB

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the woocommerce/cart block
Checkout: #8 - /checkout/ -  Contains the woocommerce/checkout block
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.8
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /home/customer/www/tommasop57.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/customer/www/tommasop57.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/customer/www/tommasop57.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-17 07:46:57 +00:00
Options: ✔
Notes: 60
Onboarding: skipped

### Action Scheduler ###

Complete: 28
Oldest: 2024-09-13 07:47:27 +0000
Newest: 2024-09-16 09:08:07 +0000

Pending: 1
Oldest: 2024-09-17 09:08:07 +0000
Newest: 2024-09-17 09:08:07 +0000

### Status report information ###

Generated at: 2024-09-16 10:59:35 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Reassigning because it describes a desirable change in the checkout, but feel free to make a further correction if needed :-)

**Comment by mikejolley** [comment]
The question becomes how do we decide if state should be pre-selected or not, or if we just do this for all customers. I would expect it to have larger impact of countries with a defined list of states and/or state-level taxes. I would rather not introduce a new setting to control something niche like this.

Will open up for feedback from @woocommerce/rubik This change would impact all checkout flows, including legacy.

**Comment by senadir** [comment]
Seems like something that can be done/controlled via a filter, and I suspect such filter already exists?

**Comment by ResponsiveFlow** [comment]
@mikejolley @senadir why not having an additional option?

Currently the options are
- no default location
- shop country/region location
- geolocate
- geolocate with cache support

There could be another option like
- shop country location
So without region.

**Comment by senadir** [comment]
Adding extra options is no small feat at this scale and I very much would only want to do it if there's a strong case. I will bring this inward for further discussion.

Right now, this code will do just that for you:

```php
function custom_filter_default_customer_address( $default_location_array ) {
    $default_location_array['state'] = '';
    
    return $default_location_array;
}
add_filter( 'woocommerce_customer_default_location_array', 'custom_filter_default_customer_address', 10, 1 );
```

**Comment by ResponsiveFlow** [comment]
Thanks for sharing the code!

> Adding extra options is no small feat at this scale 

I'm quite curious about that, why adding an additional option is complicated at this scale?

**Comment by mikejolley** [comment]
> why adding an additional option is complicated at this scale

More options to document and maintain over time. Generally we'd like the default to be the most widely applicable solution. 

In this case since a filter exists to tweak the functionality for use-cases like this I don't think we need to introduce more options and can close this issue. The filter seems flexible enough.

Thanks!
