### ISSUE TITLE
CSV import failure on Windows

### ISSUE THREAD

**Issue by Screenfeed** [woothemes/woocommerce#51415]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello.

#51344 introduced a bug on Windows servers in `WC_Product_CSV_Importer_Controller::check_file_path()`.
Basically we have the following:
```php
protected static function check_file_path( string $path ): void {
	// ...
	$path = realpath( $path );
	// ...
	foreach ( $valid_locations as $valid_location ) {
		if ( 0 === stripos( $path, trailingslashit( realpath( $valid_location ) ) ) ) {
			// ...
		}
	}
	// ...
}
```

Then we can have this kind of thing:
- `$path` => `C:\path-to\wp-content\uploads\file.csv`
- `trailingslashit( realpath( $valid_location ) )` => `C:\path-to\wp-content\uploads/`

The trailing slash on `$valid_location` is the issue here.

Possible solutions:
- Use `wp_normalize_path()` on both `$path` and `$valid_location` (safest solution IMHO).
- Use `DIRECTORY_SEPARATOR` instead of `trailingslashit()` (simplest solution IMHO).
- Use `preg_match()` to match both slash types (seems difficult and would require `preg_quote()` to escape other characters).

### Expected behavior

`WC_Product_CSV_Importer_Controller::check_file_path()` to handle Windows' back slashes in paths.

### Actual behavior

Error `File path provided for import is invalid.`.

### Steps to reproduce

We produced this [in our integration](https://github.com/polylang/polylang-wc/pull/845#pullrequestreview-2306284028) tests on Windows.

### WordPress Environment

PhP 7.4 to 8.3 in our integration tests.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pauloventurab** [comment]
Same issue on 9.4.1
#51460
