### ISSUE TITLE
Problem creating products through API with batch operation

### ISSUE THREAD

**Issue by tobiasgardner** [woothemes/woocommerce#51410]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Changed behaviour after update to Woocommerce 9.3.1?

Trying to create a product via the REST API, both with CREATE operation as well as BATCH operation. This worked before the update to 9.3.x, but after the update I get an error. The error is the same, regardless of CREATE or BATCH operation.

```
{ 'create': [
{ 'error': {
'code': 'woocommerce_rest_product_not_created',
'data': {'status': 400},
'message': 'Den SKU (105446) du försöker infoga bearbetas redan'},
'id': 0}]}
```

The JSON that is sent to the API can be found below:
```
{ 'create': [ { 'attributes': [],
                'backorders': 'notify',
                'catalog_visibility': 'visible',
                'categories': [],
                'default_attributes': [],
                'description': '',
                'downloadable': 'false',
                'featured': 'false',
                'manage_stock': 'true',
                'name': 'Temperatur sensor till Sundance Spas/Jacuzzi, 6600-751',
                'parent_id': '0',
                'purchase_note': '',
                'regular_price': '1192',
                'sale_price': '',
                'shipping_class': '',
                'short_description': '',
                'sku': '105446111',
                'sold_individually': 'false',
                'status': 'publish',
                'stock_quantity': 0,
                'type': 'simple',
                'virtual': 'false'}],
  'delete': [],
  'update': []}
```

### Expected behavior

Product should be created

### Actual behavior

An error message as described below. I have validated and the SKU is not used earlier.

```
{ 'create': [
{ 'error': {
'code': 'woocommerce_rest_product_not_created',
'data': {'status': 400},
'message': 'Den SKU (105446) du försöker infoga bearbetas redan'},
'id': 0}]}
```

### Steps to reproduce

1. Send in the following POST request
2. Send the request from the description to the REST API /products/batch/

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.villaspa.se
Site address (URL): https://www.villaspa.se
WC Version: 9.3.1
Legacy REST API Package Version: Tillägget Legacy REST API är inte installerat på denna webbplats.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.23
PHP Post Max Size: 50 MB
PHP Time Limit: 90
PHP Max Input Vars: 3000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.19-MariaDB-cll-lve
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.1
WC Database Prefix: wp_
Total databasstorlek: 563.37MB
Datastorlek för databas: 467.62MB
Indexstorlek för databas: 95.75MB
wp_woocommerce_sessions: Data: 241.65MB + Index: 4.43MB + Motor MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_woocommerce_order_items: Data: 2.29MB + Index: 1.56MB + Motor MyISAM
wp_woocommerce_order_itemmeta: Data: 23.35MB + Index: 12.66MB + Motor MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_actionscheduler_actions: Data: 2.01MB + Index: 0.97MB + Motor MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_actionscheduler_logs: Data: 1.76MB + Index: 1.04MB + Motor MyISAM
wp_aws_cache: Data: 3.55MB + Index: 0.00MB + Motor MyISAM
wp_aws_index: Data: 12.31MB + Index: 12.30MB + Motor MyISAM
wp_berocket_termmeta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_commentmeta: Data: 0.03MB + Index: 0.03MB + Motor MyISAM
wp_comments: Data: 11.39MB + Index: 4.64MB + Motor MyISAM
wp_facetwp_index: Data: 1.61MB + Index: 0.68MB + Motor MyISAM
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Motor InnoDB
wp_gla_merchant_issues: Data: 1.52MB + Index: 0.00MB + Motor InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_litespeed_avatar: Data: 0.01MB + Index: 0.01MB + Motor MyISAM
wp_litespeed_img_optm: Data: 2.46MB + Index: 0.94MB + Motor MyISAM
wp_litespeed_img_optming: Data: 0.04MB + Index: 0.07MB + Motor MyISAM
wp_litespeed_url: Data: 0.39MB + Index: 0.51MB + Motor MyISAM
wp_litespeed_url_file: Data: 1.23MB + Index: 1.64MB + Motor MyISAM
wp_mclean_refs: Data: 0.09MB + Index: 0.04MB + Motor MyISAM
wp_mclean_scan: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_options: Data: 19.81MB + Index: 0.63MB + Motor MyISAM
wp_pmxe_exports: Data: 0.66MB + Index: 0.00MB + Motor MyISAM
wp_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB + Motor MyISAM
wp_pmxe_posts: Data: 0.62MB + Index: 0.28MB + Motor MyISAM
wp_pmxe_templates: Data: 0.19MB + Index: 0.00MB + Motor MyISAM
wp_pmxi_files: Data: 0.01MB + Index: 0.00MB + Motor MyISAM
wp_pmxi_geocoding: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_pmxi_hash: Data: 0.19MB + Index: 0.18MB + Motor MyISAM
wp_pmxi_history: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_pmxi_images: Data: 0.36MB + Index: 0.04MB + Motor MyISAM
wp_pmxi_imports: Data: 0.83MB + Index: 0.00MB + Motor MyISAM
wp_pmxi_posts: Data: 1.64MB + Index: 0.52MB + Motor MyISAM
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB + Motor MyISAM
wp_postmeta: Data: 78.60MB + Index: 40.89MB + Motor MyISAM
wp_posts: Data: 9.96MB + Index: 3.74MB + Motor MyISAM
wp_sco_sessions: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_seopress_content_analysis: Data: 1.52MB + Index: 0.02MB + Motor InnoDB
wp_seopress_significant_keywords: Data: 1.18MB + Index: 1.35MB + Motor MyISAM
wp_snippets: Data: 0.05MB + Index: 0.00MB + Motor MyISAM
wp_termmeta: Data: 0.23MB + Index: 0.23MB + Motor MyISAM
wp_terms: Data: 0.04MB + Index: 0.09MB + Motor MyISAM
wp_term_relationships: Data: 0.35MB + Index: 0.78MB + Motor MyISAM
wp_term_taxonomy: Data: 0.05MB + Index: 0.06MB + Motor MyISAM
wp_usermeta: Data: 0.33MB + Index: 0.14MB + Motor MyISAM
wp_users: Data: 0.01MB + Index: 0.02MB + Motor MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Motor MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_category_lookup: Data: 0.02MB + Index: 0.03MB + Motor MyISAM
wp_wc_customer_lookup: Data: 0.64MB + Index: 0.57MB + Motor MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Motor InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Motor InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp_wc_order_coupon_lookup: Data: 0.06MB + Index: 0.12MB + Motor MyISAM
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 1.58MB + Motor MyISAM
wp_wc_order_stats: Data: 0.93MB + Index: 0.50MB + Motor MyISAM
wp_wc_order_tax_lookup: Data: 0.47MB + Index: 0.60MB + Motor MyISAM
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_wc_product_meta_lookup: Data: 0.16MB + Index: 0.26MB + Motor MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_bundled_itemmeta: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_woocommerce_bundled_items: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_gpf_google_taxonomy: Data: 2.52MB + Index: 0.23MB + Motor InnoDB
wp_woof_query_cache: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Motor InnoDB
wp_wpforms_payments: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wpforms_payment_meta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wpmailsmtp_debug_events: Data: 0.09MB + Index: 0.00MB + Motor InnoDB
wp_wpmailsmtp_emails_log: Data: 36.02MB + Index: 0.30MB + Motor InnoDB
wp_wpmailsmtp_email_tracking_events: Data: 1.02MB + Index: 0.36MB + Motor InnoDB
wp_wpmailsmtp_email_tracking_links: Data: 1.08MB + Index: 0.08MB + Motor InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.04MB + Index: 0.01MB + Motor MyISAM

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 3006
b2bking_custom_field: 9
b2bking_custom_role: 2
b2bking_group: 3
b2bking_rule: 1
br_product_filter: 2
ct_template: 13
custom_css: 1
nav_menu_item: 44
oembed_cache: 3
oxy_user_library: 1
page: 39
post: 1
product: 2004
product_variation: 248
revision: 177
seopress_404: 13324
seopress_bot: 7
seopress_schemas: 1
shop_coupon: 420
shop_order: 10771
shop_order_refund: 46
wapf_product: 1
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Advanced Custom Fields PRO: av WP Engine – 6.3.6
Advanced Database Cleaner: av Younes JFR. – 3.1.4
Advanced Woo Search PRO: av ILLID – 3.15
All-in-One WP Migration: av ServMask – 7.86
Code Snippets: av Code Snippets Pro – 3.6.5.1
Cookies och Content Security Policy: av Jonk @ Follow me Darling – 2.26
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: av Thomas Geiger – 1.20.2
Hydrogen Pack: av Clean Plugins – 1.5.0
Facebook for WooCommerce: av Facebook – 3.2.9
Fortnox: av Redlight Media – 4.4.2
Fraktjakts fraktmetod för WooCommerce: av Fraktjakt AB (Sverige) – 2.6.0
Google for WooCommerce: av WooCommerce – 2.8.5
OMGF: av Daan from Daan.dev – 5.9.1
LiteSpeed Cache: av LiteSpeed Technologies – 6.5.0.2
Loco Translate: av Tim Whitlock – 2.6.11
OxyNinja: av OxyNinja – 3.5.3
Oxy Toolbox: av Gagan S Goraya
Sridhar Katakam – 1.6.0

Oxygen Gutenberg Integration: av Soflyy – 1.4.5
Oxygen Elements for WooCommerce: av Soflyy – 2.0.1
Oxygen: av Soflyy – 4.9
Remember Me Controls: av Scott Reilly – 2.1
Svea Checkout för WooCommerce: av The Generation AB – 2.8.10
UpdraftPlus - Backup/Restore: av UpdraftPlus.Com
DavidAnderson – 1.24.4

User Menus: av Code Atlantic – 1.3.2
WooCommerce.com Update Manager: av Automattic – 1.0.3
Sequential Order Numbers for WooCommerce: av SkyVerge – 1.10.1
WooCommerce: av Automattic – 9.3.1
WP All Export Pro: av Soflyy – 1.9.1
WP All Import Pro: av Soflyy – 4.9.0
Asset CleanUp: Page Speed Booster: av Gabe Livan – 1.3.9.7
WP Mail SMTP Pro: av WP Mail SMTP – 4.1.1
SEOPress PRO: av The SEO Guys at SEOPress – 8.1.1
SEOPress: av The SEO Guys at SEOPress – 8.1.1
WP All Export - ACF Export Add-On Pro: av Soflyy – 1.0.5
WP All Export - User Export Add-On Pro: av Soflyy – 1.0.7
WP All Export - WooCommerce Export Add-On Pro: av Soflyy – 1.0.9
WP All Import - ACF Add-On: av Soflyy – 3.3.8
WP All Import - WooCommerce Import Add-On Pro: av Soflyy – 4.0.0
WPForms Lite: av WPForms – 1.9.0.4

### Inactive Plugins (19) ###

Advanced Product Fields for WooCommerce: av StudioWombat – 1.6.10
annasta Woocommerce Product Filters: av annasta.net – 1.7.4
B2BKing: av WebWizards – 3.1.0
Better Search Replace: av WP Engine – 1.4.7
CoBlocks: av GoDaddy – 3.1.13
Flying Analytics by FlyingPress: av FlyingPress – 2.0.1
Flying Images: av WP Speed Matters – 2.4.14
Flying Scripts: av WP Speed Matters – 1.2.3
HUSKY - Products Filter Professional for WooCommerce: av realmag777 – 1.3.6.2
Media Cleaner (Pro): av Jordy Meow – 6.6.4
OxyPowerPack: av The OxyPowerPack team – 2.0.4
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 3.1.6
Site Kit by Google: av Google – 1.135.0
WooCommerce Blocks: av Automattic – 11.7.0
WooCommerce Stripe Gateway: av WooCommerce – 8.6.1
WooCommerce Swish Ecommerce Gateway: av Redlight Media – 5.2.0
WordPress REST API Authentication: av miniOrange – 3.4.0
WP-Optimize - Clean, Compress, Cache: av David Anderson
Ruhani Rabin
Team Updraft – 3.5.0

WP Mail SMTP: av WP Mail SMTP – 4.1.1

### Dropin Plugins () ###

object-cache.php: LiteSpeed Cache - Object Cache (Drop-in)

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dagar
Level threshold: –
Log directory size: 3 MB

### WC Pages ###

Butikbas: #131 - /shop/
Varukorg: #133 - /kundvagn/ -  Innehåller kortkoden [woocommerce_cart]
Kassan: ❌ Sidan innehåller inte kortkoden [woocommerce_checkout] eller blocket woocommerce/checkout.
Mitt konto: #132 - /konto/
Villkor: #174 - /allmanna-villkor/

### Theme ###

Name: twentytwenty
Version: (en uppdatering till version 2.7 finns tillgänglig)
Author URL: 
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-17 06:26:30 +02:00
Options: ✔
Notes: 16
Onboarding: completed

### Action Scheduler ###

Färdigbehandlad: 4 988
Oldest: 2024-08-16 13:15:59 +0200
Newest: 2024-09-16 13:07:42 +0200

Misslyckades: 155
Oldest: 2023-08-21 15:28:12 +0200
Newest: 2024-09-16 13:02:52 +0200

Väntar: 11
Oldest: 2024-09-16 16:02:36 +0200
Newest: 2024-09-22 20:54:21 +0200

### Status report information ###

Generated at: 2024-09-16 13:12:13 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tobiasgardner** [comment]
In previous version, I did not get an error when using this statement:
'manage_stock': 'yes',
but in this version, the CREATE operation does not allow that while there is no specific error thrown from the BATCH operation.

Changing the above statement to
'manage_stock': 'true',
removes the error in the CREATE operation.

**Comment by tobiasgardner** [comment]
Related issue [https://github.com/woocommerce/woocommerce/issues/51412](https://github.com/woocommerce/woocommerce/issues/51412)

**Comment by jeanfranrene** [comment]
Same issue here with Woocommerce 9.3.1. Had to go back to the old version we had before the update 9.1.4.

**Comment by albarin** [comment]
Hi @tobiasgardner, thanks for reporting this.
Could you double-check if you have some older products in the Trash with the same SKUs you are trying to insert? Or some orphaned SKU entries in the `wc_product_meta_lookup` table? 
We haven't been able to reproduce this error if that's not the case. A similar issue was reported and another user suggested a way to clean any orphan entries: https://github.com/woocommerce/woocommerce/issues/51412#issuecomment-2354769311
Thank you!

**Comment by naman03malhotra** [comment]
Closing this as duplicate of https://github.com/woocommerce/woocommerce/issues/51412 and a work around it present https://github.com/woocommerce/woocommerce/issues/51412#issuecomment-2354769311

**Comment by tobiasgardner** [comment]
> Hi @tobiasgardner, thanks for reporting this. Could you double-check if you have some older products in the Trash with the same SKUs you are trying to insert? Or some orphaned SKU entries in the `wc_product_meta_lookup` table? We haven't been able to reproduce this error if that's not the case. A similar issue was reported and another user suggested a way to clean any orphan entries: [#51412 (comment)](https://github.com/woocommerce/woocommerce/issues/51412#issuecomment-2354769311) Thank you!

The workaround suggested in that ticket does not really work when working through the API. You need access to the server/backend to be able to apply that workaround, something we do not have when we sync through the API.

I tried creating products with SKUs with SKUs that were unique, i.e. could not exist in the database.

**Comment by maxbrwn** [comment]
@tobiasgardner did you manage to find a solution here as I'm having exactly the same issue? Any additional source on how to solve this would be helpful 🙏

**Comment by albarin** [comment]
Hi @maxbrwn, we found a fix for this issue and it will be included in the next WooCommerce release, 9.4. For more context: https://github.com/woocommerce/woocommerce/pull/51735#issuecomment-2422660487
Thanks!

**Comment by tobiasgardner** [comment]
I have no solution, except for downgrading Woocommerce (which I have not done).
I am about to swap out Woocommerce for another platform, so not really worth spending any time on this for me.

From: Maximilian Braun ***@***.***>
Date: Monday, 21 October 2024 at 09:57
To: woocommerce/woocommerce ***@***.***>
Cc: tobiasgardner ***@***.***>, Mention ***@***.***>
Subject: Re: [woocommerce/woocommerce] Problem creating products through API with batch operation (Issue #51410)

@tobiasgardner<https://github.com/tobiasgardner> did you manage to find a solution here as I'm having exactly the same issue? Any additional source on how to solve this would be helpful 🙏

**Comment by maxbrwn** [comment]
@tobiasgardner @albarin thank you both for getting back to me.
This is a really crucial topic for us as it affects several customers that relay on the woo api. I really wonder how this can take so much time and not being addressed with a hot fix in this case.

**Comment by tobiasgardner** [comment]
From my perspective (not working with woo development/maintenance) I can only agree maximilian. It is not a new feature, but something that was broken in a maintenance release…

From: Maximilian Braun ***@***.***>
Date: Tuesday, 22 October 2024 at 08:16
To: woocommerce/woocommerce ***@***.***>
Cc: tobiasgardner ***@***.***>, Mention ***@***.***>
Subject: Re: [woocommerce/woocommerce] Problem creating products through API with batch operation (Issue #51410)

@tobiasgardner<https://github.com/tobiasgardner> @albarin<https://github.com/albarin> thank you both for getting back to me.
This is a really crucial topic for us as it affects several customers that relay on the woo api. I really wonder how this can take so much time and not being addressed with a hot fix in this case.

**Comment by albarin** [comment]
Can I suggest a different temporary workaround?
You could include this snippet to bypass the query that is causing the issue:
```php
add_filter( 'wc_product_pre_lock_on_sku', '__return_true' );
```
The snippet could be included using a snippets plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/), or in the `functions.php` of your theme through the `Theme File Editor` in the admin.

@tobiasgardner @maxbrwn sorry for the inconvenience.

**Comment by tobiasgardner** [comment]
Thank you! Added with Code snipplets, and validated 😊
Works like a charm!

From: Alba Rincón ***@***.***>
Date: Tuesday, 22 October 2024 at 10:25
To: woocommerce/woocommerce ***@***.***>
Cc: tobiasgardner ***@***.***>, Mention ***@***.***>
Subject: Re: [woocommerce/woocommerce] Problem creating products through API with batch operation (Issue #51410)

Can I suggest a different temporary workaround?
You could include this snippet to bypass the query that is causing the issue:

add_filter( 'wc_product_pre_lock_on_sku', '__return_true' );

The snippet could be included using a snippets plugin like Code Snippets<https://wordpress.org/plugins/code-snippets/>, or in the functions.php of your theme through the Theme File Editor in the admin.

@tobiasgardner<https://github.com/tobiasgardner> @maxbrwn<https://github.com/maxbrwn> sorry for the inconvenience.

**Comment by stzoran1** [comment]
> Can I suggest a different temporary workaround? You could include this snippet to bypass the query that is causing the issue:
> 
> add_filter( 'wc_product_pre_lock_on_sku', '__return_true' );
> The snippet could be included using a snippets plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/), or in the `functions.php` of your theme through the `Theme File Editor` in the admin.
> 
> [@tobiasgardner](https://github.com/tobiasgardner) [@maxbrwn](https://github.com/maxbrwn) sorry for the inconvenience.

Worked for me too. Thank you.

**Comment by nishad8898** [comment]
> Can I suggest a different temporary workaround? You could include this snippet to bypass the query that is causing the issue:
> 
> add_filter( 'wc_product_pre_lock_on_sku', '__return_true' );
> The snippet could be included using a snippets plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/), or in the `functions.php` of your theme through the `Theme File Editor` in the admin.
> 
> [@tobiasgardner](https://github.com/tobiasgardner) [@maxbrwn](https://github.com/maxbrwn) sorry for the inconvenience.

Thanks Worked for me, but will it cause any issue 🤔
