### ISSUE TITLE
[Enhancement]: Make descriptions in textarea fields consistent with text fields in WooCommerce settings

### ISSUE THREAD

**Issue by medavidallsop** [woothemes/woocommerce#51436]
### Describe the solution you'd like

Where textarea fields are registered in WooCommerce settings the description (if not a tooltip) it displayed above the field which is inconsistent with text fields, which display the description below.

In addition, the text color of the description is a different shade compared to the description of most other fields.

The color should be consistent, there might be reasoning of why the description of textareas is placed above the field, but it potentially just looks like an inconsistency/oversight.

<img width="669" alt="image" src="https://github.com/user-attachments/assets/f017a373-22ab-4e0b-8342-3a1b927326f5">

Note the differences between the description (Lorem ipsum...) position and color on the above text and textarea fields.

### Describe alternatives you've considered

None

**Comment by juliaamosova** [comment]
Hi @medavidallsop! Thanks for reporting the issue. Can you please specify some examples where you see inconsistencies? 

I've checked all the `WooCommerce/Settings` options and they are all unified with file descriptions below the text area. Some examples below:

![Screenshot 2024-09-18 at 4 15 38 PM](https://github.com/user-attachments/assets/8d206e5d-5f41-4fda-836e-36a2be6796dc)

![Screenshot 2024-09-18 at 4 16 28 PM](https://github.com/user-attachments/assets/bc7823c3-c750-4c5f-9b8b-a945d26bcae0)

I also randomly checked few other are such as `Product Categories` and it also looks as expected:

![Screenshot 2024-09-18 at 4 21 16 PM](https://github.com/user-attachments/assets/5b5a6c08-f0ce-4481-8561-7c32ba933cd1)

**Comment by medavidallsop** [comment]
Hi @juliaamosova 

I don't think there are any core settings using textarea fields at present,  but any plugin can use the WooCommerce setting functionality to register a new setting in the WooCommerce settings section, and can choose a type of textarea, which WooCommerce then controls the markup of.

In the initial post, the screenshot shows what these look like, if you want to see this, check out the PR I wrote for this, in the testing you'll see the code needed to render a textarea here, like plugins do.

**Comment by rodelgc** [comment]
Thanks for the response @medavidallsop and also thank you for submitting the PR! It will be reviewed once the development team gets to it.
