### ISSUE TITLE
[WC Payments NOX] Manage active payment gateway extensions

### ISSUE THREAD

**Issue by vladolaru** [woothemes/woocommerce#51446]
### Description

Integrate active payment gateway extensions into the main payment providers list and provide management tools.
These are WP plugins that are already installed and activated.

### Acceptance criteria

* Installed and activated WC payment gateway extensions automatically populate the payment providers list
* Deactivated WC payment gateway extensions (via plugins) are automatically removed from the list
* The drag&drop re-ordering of payment providers is automatically saved, store-wide (not per-user)
* Use real payment provider details: icon, title, description
* Provide working management tools:
  * Disable via the context menu
  * Enable and Manage buttons

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Dev notes
Reactifying the Payments settings page: pe4Hk0-1ly-p2
Populate react-powered main payments settings screen PR: https://github.com/woocommerce/woocommerce/pull/50825

### Additional context
PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

**Comment by dmallory42** [comment]
Closed by #52220. There are some acceptance criteria that are only partially met that will be satisfied by other PRs in progress or will spin up new issues for them later.
