### ISSUE TITLE
[WC Payments NOX] Integrate WooPayments incentives UI

### ISSUE THREAD

**Issue by vladolaru** [woothemes/woocommerce#51453]
### Description

If there is an active WooPayments incentive, surface it on the Payments settings page.

### Acceptance criteria

* The action incentive UI is present when there is an active incentive.
* The switch incentive UI is present when there is an active incentive. 

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Dev notes
Reactifying the Payments settings page: pe4Hk0-1ly-p2
Populate react-powered main payments settings screen PR: https://github.com/woocommerce/woocommerce/pull/50825

### Additional context
PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

cc @timmy5685

**Comment by timmy5685** [comment]
Adding link to requirements for incentive designs: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc
