### ISSUE TITLE
[WC Payments NOX] WooPayments test-drive onboarding flow

### ISSUE THREAD

**Issue by vladolaru** [woothemes/woocommerce#51452]
### Description

When WooPayments is _first_ enabled, we will provide an e2e test-drive onboarding flow.

### Acceptance criteria

* If WooPayments hasn't been set up before on the store, when the user clicks "Enable":
  * If there is no WPCOM/Jetpack connection for the store, redirect the user to the WPCOM/Jetpack connection screens
  * If there is a working WPCOM/Jetpack connection, show the progress screen and set up a test-drive account
  * After the test-drive account is properly connected, display modal with "Set up live payments" and "Continue store setup" CTAs
* Handle rejection of Jetpack connection
* Handle failure to create test-drive account
* When WooPayments is in test-drive, show "Set up live payments" CTA button in the primary payment providers list and implement the switch to live flow

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Dev notes
Reactifying the Payments settings page: pe4Hk0-1ly-p2
Populate react-powered main payments settings screen PR: https://github.com/woocommerce/woocommerce/pull/50825

### Additional context
PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

cc @timmy5685

**Comment by timmy5685** [comment]
> If WooPayments hasn't been set up before on the store, when the user clicks "Enable"

@vladolaru - just confirming that we are also accounting for logic where we skip the test account when the merchant is already established and processing through another gateway as defined here: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc
