### ISSUE TITLE
Out of stock email notificaitons when duplicating a variable product

### ISSUE THREAD

**Issue by ram33z** [woothemes/woocommerce#51512]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Out of stock notifications for each variation while creating duplicate of a variable product.  If a variable product has 100 variations then it triggers 100 out of stock email notifications.

We didn't face this issue in version  9.2.3.

I believe its something to do with this change introduced in 9.3.0

- * Fix - Ensure low and no stock email notification routine is triggered whenever product stock changes [#49583](https://github.com/woocommerce/woocommerce/pull/49583)

### Expected behavior

It shouldn't send out of stock notifications while product is still in draft when creating a duplicate. 

### Actual behavior

Right now Out of Stock notification is being send for each variation while creating a duplicate product (still in draft). 

### Steps to reproduce

1. Go to Woocommerce -> Products -> Hover on any Out of Stock Variable Product and select Duplicate
2. Check mailbox for out of stock notifications 

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###


### Server Environment ###

### Database ###

[REDACTED]

### Post Type Counts ###


### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###


### Inactive Plugins (5) ###


### Dropin Plugins () ###

### Must Use Plugins (1) ###


### Settings ###


### Logging ###

### Action Scheduler ###


### Status report information ###

Generated at: 2024-09-18 12:16:43 -04:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @ram33z! Thanks for reporting the issue. We are about to release WooCommerce 9.3.2 where we reverted the offending PR: https://github.com/woocommerce/woocommerce/pull/51441 - it should be available within an hour or less. 

Once released, please confirm if the issue is solved for you. Thank you!

**Comment by ram33z** [comment]
@juliaamosova  Thanks. Yes, I can confirm that the issue is now fixed with the new update.
