### ISSUE TITLE
Add Spinner / Loading State While Cart Updating in Checkout Page (Woocommerce Blocks)

### ISSUE THREAD

**Issue by febrianasdk** [woothemes/woocommerce#51531]
I'm trying woocommerce blocks for my plugin, when on the checkout page and the cart is being updated (such as changing payment methods and adding fees for certain payments) there is nothing like a spinner or loading state in order summary, is there no spinner? or is there something I need to do?

**Comment by rodelgc** [comment]
Hi @FebrianaPasonangSidauruk I saw that you already submitted an enhancement request in https://github.com/woocommerce/woocommerce/issues/51565 so I'll go ahead and close this issue.
