### ISSUE TITLE
filter woocommerce_upsells_total passes string '-1' instead of int -1

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#51548]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

wrong type used as default value

### Expected behavior

int

### Actual behavior

string

### Steps to reproduce

add_filter on woocommerce_upsells_total - value can be '-1'

### WordPress Environment

irrelevant

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @woocommerce/proton I see that you already started reviewing the PR for this issue, so just attaching the team label here as part of triage.
