### ISSUE TITLE
BUG in variable selection

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#51556]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi woocommerce team,

Customers are facing a problem when choosing a variable...
On our website, each product has 3 variables. **Color**, **code** and **size**. In fact, in each product, each color has a code. Like the following example :

- red  -  code 1  -   size a
- red   -  code 1  -   size b
- red  -   code 1  -  size c

- blue  -  code 2  -   size a
- blue  -  code 2   -  size b
- blue  -  code 2   -  size c

According to the above, we will have 6 variables. So if the user chooses red color, he will only see 1 codes. There is no problem here.
But if you increase the number of variables to 31 according to the above (16 variables in red color, 16 variables in blue color), then the user will have difficulty in selecting the variable. **The problem is that if, for example, they choose the red color, both code 1 and code 2 will be displayed in the code variable, while only code 1 should be available.**
If you reduce the number of variables from 31 to 30, the problem will be solved!

### Expected behavior

As I mentioned above, if the number of variables is less than 31, everything works as expected.

### Actual behavior

-

### Steps to reproduce

Please watch the video below : 

https://github.com/user-attachments/assets/396a2e41-8fa1-4819-ad33-6809782f6924

### WordPress Environment

**Note:** As you can see below, the theme of my website is bricks. But I have the same problem in Elementor websites. Even in 2024 theme and without elementor.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.19
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.7.1
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. 403
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 164
bricks_fonts: 1
bricks_template: 16
faq: 8
nav_menu_item: 73
page: 61
post: 101
product: 1
product_variation: 30
revision: 14
shop_order_placehold: 1
sliced_invoice: 1
testimonials: 6
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.3.1 (update to version 9.3.2 is available)

### Inactive Plugins (9) ###

Rank Math SEO: by Rank Math – 1.0.227.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 9 KB

### WC Pages ###

Shop base: #3674 - /shop/
Cart: #3675 - /cart/ -  Contains the woocommerce/cart block
Checkout: #3676 - /checkout/ -  Contains the woocommerce/checkout block
My account: #3677 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Bricks Child Theme
Version: 1.1
Author URL: https://bricksbuilder.io/
Child Theme: ✔
Parent Theme Name: Bricks
Parent Theme Version: 1.10.3
Parent Theme Author URL: https://bricksbuilder.io/
WooCommerce Support: ✔

### Templates ###

Overrides: bricks/archive-product.php
bricks/woocommerce/cart/cart-empty.php
bricks/woocommerce/cart/cart.php
bricks/woocommerce/cart/proceed-to-checkout-button.php
bricks/woocommerce/checkout/form-checkout.php
bricks/woocommerce/checkout/form-pay.php
bricks/woocommerce/checkout/order-receipt.php
bricks/woocommerce/checkout/thankyou.php
bricks/single-product.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-20 13:32:51 +03:30
Options: ✔
Notes: 60
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2024-09-19 21:37:24 +0330
Newest: 2024-09-19 21:37:24 +0330

Complete: 1,921
Oldest: 2024-08-20 00:07:48 +0330
Newest: 2024-09-19 21:42:31 +0330

Failed: 5
Oldest: 2024-07-20 17:12:04 +0330
Newest: 2024-09-17 18:27:18 +0330

Pending: 2
Oldest: 2024-09-20 00:33:06 +0330
Newest: 2024-09-20 17:06:25 +0330


### Status report information ###

Generated at: 2024-09-19 21:44:05 +03:30
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
I can reproduce the issue. If I only have 30 variations (all Reds only have the Code 1 variation, and all Blues have the Code 2 variation) the product page will only allow me to select Code 1 if the color I selected was Red, and only Code 2 if the color I selected was Blue. 

But if I add a 31st variation, selecting either Blue or Red in the product page would show both Code 1 and 2.

**Comment by 79ho3ein** [comment]
Exactly, I hope this bug is fixed soon. Our customers always have problems choosing products.

**Comment by RiaanKnoetze** [comment]
I think this is the intended behaviour as it's the middleground between performance and usability when it comes to dynamically updating the variation select field. More information here: https://woocommerce.com/document/change-limit-on-number-of-variations-for-dynamic-variable-product-dropdowns/

**Comment by rodelgc** [comment]
Thank you for pointing that out @RiaanKnoetze! 

@79ho3ein as @RiaanKnoetze pointed out, it is the intended behavior for performance reasons. The link provided above contains a sample snippet for the `woocommerce_ajax_variation_threshold` filter. Can you try that instead?

For the meantime I'm closing this issue. If you need more help with using the filter, feel free to reach out to our usual support channels at https://wordpress.org/support/plugin/woocommerce/ or [WooCommerce Community Slack](https://woocommerce.com/community-slack/).

**Comment by 79ho3ein** [comment]
Hi again woocommerce team,

I tried to increase the default value from 30 to 100 using this code, but after applying the code, the error "This product is currently out of stock and unavailable" is not displayed in the variation selector section. Please advise? And is there also no plan to improve this issue in WooCommerce core? Thank you

```
function custom_wc_ajax_variation_threshold( $qty, $product ) {
	return 100;
}
add_filter( 'woocommerce_ajax_variation_threshold', 'custom_wc_ajax_variation_threshold', 10, 2 );
```
