### ISSUE TITLE
Fatal Error: Uncaught TypeError in class-wc-order.php on WooCommerce - hash_equals() receives null value

### ISSUE THREAD

**Issue by MikeNovemberr** [woothemes/woocommerce#51555]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using Cart Flows plugin, this bug happens. even on final Thank you page, or in Elementor editor.

Stack trace: PHP Fatal error: Uncaught TypeError: hash_equals(): Argument #2 ($user_string) must be of type string, null given in /path/to/wp-content/plugins/woocommerce/includes/class-wc-order.php:1585

I fix this by coding myself, but as soon as update arrives, this happens again

### Expected behavior

The hash_equals() function should be called with valid string arguments, and the system should gracefully handle any missing or null values for $user_string.

### Actual behavior

A TypeError is thrown when $user_string is null, causing a fatal error on the site.

### Steps to reproduce

U must use Cart Flows to reproduce this error. The error is thrown because $user_string is null.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://pet-subs.com
Site address (URL): https://pet-subs.com
WC Version: 9.3.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.5.25-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.1
WC Database Prefix: wp_
Total Database Size: 163.21MB
Database Data Size: 142.89MB
Database Index Size: 20.32MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.22MB + Index: 1.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_asce_postback_data: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_asce_webhook_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_abandonedcarts: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_automation_complete_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwfan_automation_contact: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwfan_automation_contact_claim: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwfan_automation_contact_trail: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bwfan_automation_step: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwfan_message_unsubscribe: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bwf_ab_experiments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_actions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwf_action_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_conversion_tracking: Data: 0.02MB + Index: 0.33MB + Engine InnoDB
wp_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bwf_wc_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_visits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_visits_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.20MB + Index: 0.25MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fk_cart_stats: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_icl_background_task: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.09MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_icl_translate: Data: 4.52MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.48MB + Index: 0.94MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 5.52MB + Index: 0.11MB + Engine InnoDB
wp_jet_apartment_bookings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_apartment_units: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_appointments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_appointments_excluded: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_appointments_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_bookings_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_cct_feedback: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_fb_attachments_to_records: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jet_fb_csrf_tokens: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_jet_fb_dynamic_routes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_jet_fb_dynamic_routes_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_jet_fb_migrations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_fb_records: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jet_fb_records_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jet_fb_records_errors: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jet_fb_records_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jet_fb_reset_passwords: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jet_fb_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jet_fb_tokens_to_records: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jet_post_types: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_jet_rel_10: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_rel_default: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_review_comments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_review_guests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_review_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_review_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_search_suggestions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_search_suggestions_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_smart_filters_indexer: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_notification_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_omnisend_contact_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_omnisend_logs: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 8.23MB + Index: 0.16MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 85.36MB + Index: 5.95MB + Engine InnoDB
wp_posts: Data: 15.52MB + Index: 0.88MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_trp_dictionary_en_us_ru_ru: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
wp_trp_dictionary_en_us_sr_rs: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
wp_trp_gettext_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_original_strings: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_trp_gettext_ru_ru: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
wp_trp_gettext_sr_rs: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
wp_trp_original_meta: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wp_trp_original_strings: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_usermeta: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.11MB + Index: 0.17MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfacp_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wfco_connectormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_connectors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfob_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfocu_event: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfocu_event_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfocu_session: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wt_abandonment_coupon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_sc_coupon_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.09MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 6150
bnfw_notification: 1
cartflows_flow: 1
cartflows_step: 2
doctors: 5
elementor_font: 6
elementor_library: 53
emailkit: 1
google-reviews: 4
itsec-dash-card: 10
itsec-dashboard: 1
jet-engine: 31
jet-engine-booking: 4
jet-form-builder: 12
jet-page-template: 1
jet-popup: 4
jet-smart-filters: 28
jet-theme-core: 2
jet-woo-builder: 2
language_switcher: 4
nav_menu_item: 2
page: 31
pet: 10
post: 5
pricing-plans: 60
product: 543
product_variation: 2
revision: 628
services: 1
shop_coupon: 4
shop_order_placehold: 23
staff: 6
tickets: 1
wfacp_checkout: 1
wffn_ty: 1
wfob_bump: 1
woolentor-template: 1
wp_global_styles: 1
wp_navigation: 1
wpcode: 122
yaymail_template: 14

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

AllSecure Exchange: by <a href="https://www.allsecure.eu/">AllSecure</a> – 2.0.5
CartFlows: by CartFlows Inc – 2.0.10
Cloudflare: by Cloudflare
Inc. – 4.12.8

Crocoblock Wizard: by Crocoblock – 1.2.12
Custom Taxonomy Order: by Marcel Pol – 4.0.0
Elementor Pro: by Elementor.com – 3.23.3
Elementor: by Elementor.com – 3.23.4
ElementsKit Lite: by Wpmet – 3.2.7
Fiscomm PURS E-Fiscalisation: by Square One Consulting – 0.3.13
Flexible Shipping: by Octolize – 4.25.8
Site Kit by Google: by Google – 1.135.0
Coding Chicken - JetEngine Importer: by Coding Chicken – 1.2.3
WPCode Lite: by WPCode – 2.2.1
Jet Appointments Booking: by Crocoblock – 2.1.2
JetBlocks For Elementor: by Crocoblock – 1.3.14
JetBlog For Elementor: by Crocoblock – 2.4.0
JetElements For Elementor: by Crocoblock – 2.6.20.1
JetEngine - Custom visibility conditions: by Crocoblock – 1.1.2
JetEngine - dynamic tables builder: by Crocoblock – 1.0.10
JetEngine - Trim string callback: by Crocoblock – 1.0.3
JetEngine: by Crocoblock – 3.5.5
JetFormBuilder Formless Actions Endpoints: by Crocoblock – 1.0.2
JetFormBuilder Hierarchical Select: by Crocoblock – 1.0.3
JetFormBuilder User Login Action: by Crocoblock – 2.0.5
JetFormBuilder Save Form Progress: by Crocoblock – 1.0.10
JetFormBuilder WooCommerce Cart & Checkout Action: by Crocoblock – 1.0.7
JetPopup: by Crocoblock – 2.0.6
JetReviews For Elementor: by Crocoblock – 2.3.4
JetSearch: by Crocoblock – 3.5.3
JetSmartFilters: by Crocoblock – 3.5.5
JetTabs For Elementor: by Crocoblock – 2.2.4
JetThemeCore: by Crocoblock – 2.2.2.1
JetWooBuilder For Elementor: by Crocoblock – 2.1.14
JetFormBuilder: by Crocoblock – 3.4.2
Notification: by BracketSpace – 8.0.15
Omnisend for WooCommerce: by Omnisend – 1.15.19
PluginsForWP Plugin Manager: by PluginsForWP – 4.3.3
WooCommerce Subscriptions: by WooCommerce – 6.6.1 (update to version 6.7.0 is available)
WooCommerce: by Automattic – 9.3.1 (update to version 9.3.2 is available)
Wordfence Security: by Wordfence – 7.11.7
Yoast SEO: by Team Yoast – 23.2
WP All Import Pro: by Soflyy – 4.8.9-beta-1.1
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 4.0.1-beta-2.1

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: RSD (RSD)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 MB

### WC Pages ###

Shop base: #15 - /shop/
Cart: ❌ Page ID is set
but the page does not exist

Checkout: #15626 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #15466 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor
Version: 3.1.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://pet-subs.com
Subscriptions-core Library Version: 7.4.2
Subscription Statuses: wc-active: 2
wc-cancelled: 2

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Serbia — South Bačka

### Subscriptions by Payment Gateway ###

AllSecure Exchange: wc-active: 2
wc-cancelled: 2

### Payment Gateway Support ###

AllSecure Exchange: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change
subscription_payment_method_change_admin
subscription_payment_method_change_customer

Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-20 14:45:43 +02:00
Options: ✔
Notes: 78
Onboarding: skipped

### Action Scheduler ###

Complete: 3,057
Oldest: 2024-08-19 19:08:24 +0200
Newest: 2024-09-19 14:11:38 +0200

Failed: 70
Oldest: 2024-05-25 16:39:35 +0200
Newest: 2024-09-18 20:32:45 +0200

Pending: 6
Oldest: 2024-09-20 01:53:44 +0200
Newest: 2024-10-19 13:39:03 +0200

### Status report information ###

Generated at: 2024-09-19 19:05:23 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
> U must use Cart Flows to reproduce this error. The error is thrown because $user_string is null.

Hi @MikeNovemberr thanks for raising this. In order to get a better understanding of the issue, could you elaborate a bit more details on how to reproduce the issue?

I installed the [WooCommerce Checkout & Funnel Builder by CartFlows](https://wordpress.org/plugins/cartflows/) and activated it on my test site, but I didn't see any fatal errors in the logs right after activating it. So I assume there should be steps that need to be made in order to trigger this fatal error. If you would be able to elaborate on the steps to reproduce, that would be great. It might be hard to fix if we can't replicate it in the first place.

> I fix this by coding myself, but as soon as update arrives, this happens again

Would you be able to submit a pull request for it so we could review it? This approach would be faster. Thanks!

**Comment by MikeNovemberr** [comment]
Hi @rodelgc thanks for reverting back. 

I am not totally sure if this error is fired due to other plugins and snippets in combination, but here is how i am experiencing. I have custom checkout page created with Cart Flows, as well as Thank you page. Once you setup that, u can edit Thankyou page with elementor, this is more like built in option when you select your Thank you page inside Cart Flows. Edit will trigger editing Thank you page inside Elementor editor and this is where the error is fired. Also after a purchase, thank you page on front end fires the error and messes up layout of the page. I dont have screenshots, site in production, and i cant experiment at this moment. I patched the issue by adding this inside class-wc-order.php   ----- 

public function key_is_valid( $key ) {
    $order_key = $this->get_order_key();

    if (is_string($order_key) && !empty($order_key) && is_string($key) && !empty($key)) {
        return hash_equals( $order_key, $key );
    }

    return false;
}

**Comment by lanej0** [comment]
Hi @MikeNovemberr 

It sounds like the error you're experiencing might be coming from a conflict between Elementor and the Cart Flows plugin.  Because we don't develop either of those, there isn't much we can do to help out here.  Probably best to get in contact with them (I'd suggest starting with Cart Flows) to see if they can help out further.
