### ISSUE TITLE
forward to #46260

### ISSUE THREAD

**Issue by Studio-Sjoege** [woothemes/woocommerce#51578]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm reposting this with a forward to #46260 because there isn't a decent reply in time unfortunately.

### Expected behavior

I guess to get a reply within a few weeks would be nice

### Actual behavior

takes months, then comes up with a useless reply.

### Steps to reproduce

check #46260

### WordPress Environment

not needed

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by Studio-Sjoege** [comment]
oh and I'm posting this because you've closed the ticket #46260 unfortunately

**Comment by lanej0** [comment]
I'll close this and re-open the other issue as there's no context here.
