### ISSUE TITLE
Delayed account creation: Add usage tracking to measure performance

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#51584]
See pfwcF5-Rd-p2

cc @senadir

**Comment by mikejolley** [comment]
@senadir is there a checklist of what is remaining to close this?

**Comment by senadir** [comment]
Sure

What's left is pushing a single PR in Jetpack to track:

- post-checkout account creation event.
- Adding the event prop in existing events.

Will close this once that PR is merged.
