### ISSUE TITLE
Custom Payment fields and validation

### ISSUE THREAD

**Issue by maukoese** [woothemes/woocommerce#51599]
I finally managed to get my custom payment gateway to work with Checkout Blocks.

In the past, we used the `payment_fields` and `validate_fields` methods to set and validate some extra custom fields on the checkout flow.

How would I go about achieving the same using Blocks, since these are not showing up on the checkout page?

```php

            public function payment_fields()
            {
                if ($description = $this->get_description()) {
                    echo wpautop(wptexturize($description));
                }

                woocommerce_form_field(
                    'billing_mpesa_phone',
                    [
                        'type'        => 'tel',
                        'class'       => array('form-row-wide', 'wc-mpesa-phone-field'),
                        'label'       => 'Confirm M-PESA Phone Number',
                        'label_class' => 'wc-mpesa-label',
                        'placeholder' => 'Confirm M-PESA Phone Number',
                        'required'    => true,
                    ]
                );
            }

            /**
             *
             */
            public function validate_fields()
            {
                if (empty($_POST['billing_mpesa_phone'])) {
                    wc_add_notice('M-PESA phone number is required!', 'error');
                    return false;
                }

                return true;
            }
```

**Comment by mikejolley** [comment]
See here https://github.com/woocommerce/woocommerce/blob/trunk/docs/cart-and-checkout-blocks/checkout-payment-methods/payment-method-integration.md#payment-methods---registerpaymentmethod-options-

[This links to a real world example of Stripe although it might be complex and could use a better example.](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1467/files)

But the idea is when you register the payment method on the javascript side, you provide a `content` prop which contains the react components used in your form. In this case it would be a telephone field. This has a better example of passing values to the server https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-api.md#passing-a-value-from-the-client-through-to-server-side-payment-processing

**Comment by maukoese** [comment]
Thank you so much @mikejolley I had figured out the Content part, and had implemented the field. I was struggling to pass the value to the backend. I tried React.useState but that wasn't picking the updated value. 

![mpesa](https://github.com/user-attachments/assets/6a984124-a14b-4835-a8bf-a5c8270648b1)


Let me go through the shared links and see if I find a solution.

**Comment by mikejolley** [comment]
Remember your `useEffect` may need a dependency of `billingMpesePhone`.

This week I've updated the docs and examples which can be seen here https://github.com/woocommerce/woocommerce/blob/5ae12b27d846babcfbdebc76a2d1aca98a06e08b/docs/cart-and-checkout-blocks/checkout-payment-methods/payment-method-integration.md Ill close this issue since I think its been answered.

Thank you
