### ISSUE TITLE
GTIN, UPC, EAN, or ISBN field is not included in the default Export

### ISSUE THREAD

**Issue by shameemreza** [woothemes/woocommerce#51600]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I use the default exporter to export CSV files, I can't select the GTIN, UPC, EAN, or ISBN column. Even if I enable custom meta during export, these columns don't appear in the exported CSV.

![CleanShot 2024-09-22 at 09 48 17](https://github.com/user-attachments/assets/e5946212-dac5-42a4-8acc-4bf5dc13ab1e)

**Initially reported here:**

* 8760007-zen
* https://wordpress.org/support/topic/gtin-upc-ean-or-isbn-import-export/

### Expected behavior

We should be able to export and import the value added in the GTIN, UPC, EAN, or ISBN, just like we would with the SKU. 

### Actual behavior

When I use the default exporter to export CSV files, I can't select the GTIN, UPC, EAN, or ISBN column. Even if I enable custom meta during export, these columns don't appear in the exported CSV.

### Steps to reproduce

1. Open any product in the editor.
2. Scroll to the product data section and click on the Inventory Tab.
3. Add a value to the GTIN, UPC, EAN, or ISBN
4. Save the product.
5. Go back to the All products and click on the Export.
6. Check Column lists in "Which columns should be exported?"; it is missing here.
7. Enable the "Export custom meta?" option.
8. Export the product in CSV and open it in Google Sheets, and there is no column or option to update it.

### WordPress Environment

WooCommerce version: 9.3.2
WordPress version: 6.6.2
PHP version: 8.1.27
Theme: Storefront

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
@woocommerce/automata I think you introduced this new field, so bringing to your attention (but, we can also take care of it in due course).

**Comment by puntope** [comment]
> I think you introduced this new field, so bringing to your attention (but, we can also take care of it in due course).

hey there @barryhughes, we did not add it. We just added the field to the product structure data.

find field info here: pffQ75-pV-p2

p.s I believe also no problem for us to take care of it?

**Comment by jorgemd24** [comment]
@puntope I am working on a PR to fix this issue

**Comment by JoseManuelFV** [comment]
On PR to fix the issue not added import method, only export.
You need change into https://github.com/woocommerce/woocommerce/blob/cd2edff7523a18db4d3402c3c407cc1690475549/plugins/woocommerce/includes/admin/importers/class-wc-product-csv-importer-controller.php#L645 too

@jorgemd24

**Comment by jsballarini** [comment]
I used the codes so that the column appears in the product export and export in CSV.

add_filter('woocommerce_product_export_columns', 'add_ean_to_export_columns');
function add_ean_to_export_columns($columns) {
    // Add a new column to the CSV for the _global_unique_id field
    $columns['ean_gtin_mpn'] = 'EAN/GTIN/MPN';
    return $columns;
}

add_filter('woocommerce_product_export_product_default_columns', 'add_ean_to_default_export_columns');
function add_ean_to_default_export_columns($columns) {
    // Add the column to the default set of exported columns
    $columns['ean_gtin_mpn'] = 'EAN/GTIN/MPN';
    return $columns;
}

add_filter('woocommerce_product_export_product_column_ean_gtin_mpn', 'export_ean_meta_data', 10, 2);
function export_ean_meta_data($value, $product) {
    // Retrieve the value of the custom field _global_unique_id
    return $product->get_meta('_global_unique_id', true);
}

// Add EAN to Import
add_filter('woocommerce_csv_product_import_mapping_options', 'add_ean_to_import_mapping_options');
function add_ean_to_import_mapping_options($options) {
    // Add EAN/GTIN/MPN to the list of mapping options during import
    $options['ean_gtin_mpn'] = 'EAN/GTIN/MPN';
    return $options;
}

add_filter('woocommerce_csv_product_import_mapping_default_columns', 'map_ean_column_to_meta_key');
function map_ean_column_to_meta_key($columns) {
    // Map the EAN/GTIN/MPN column to the _global_unique_id meta key
    $columns['EAN/GTIN/MPN'] = '_global_unique_id';
    $columns['ean_gtin_mpn'] = '_global_unique_id';
    return $columns;
}

add_action('woocommerce_product_import_inserted_product_object', 'import_ean_meta_data', 10, 2);
function import_ean_meta_data($product, $data) {
    // Save the value from the EAN/GTIN/MPN column to the _global_unique_id meta key
    if (!empty($data['ean_gtin_mpn'])) {
        $product->update_meta_data('_global_unique_id', $data['ean_gtin_mpn']);
    }
}

**Comment by mikkamp** [comment]
Thanks for providing some code snippets @jsballarini 

Exporting was implemented in #51703
Importing was implemented in #52240

Both of these are set to be released in WooCommerce 9.5 which should be out soon. So those code snippets won't be needed after the release.

**Comment by joyryde456** [comment]
> Thanks for providing some code snippets [@jsballarini](https://github.com/jsballarini)
> 
> Exporting was implemented in [#51703](https://github.com/woocommerce/woocommerce/pull/51703) Importing was implemented in [#52240](https://github.com/woocommerce/woocommerce/pull/52240)
> 
> Both of these are set to be released in WooCommerce 9.5 which should be out soon. So those code snippets won't be needed after the release.

Any plans to add it to the Quick Edit menu on the product page? That would be IDEAL.

**Comment by mikkamp** [comment]
> Any plans to add it to the Quick Edit menu on the product page? That would be IDEAL.

I haven't seen any plans for that. But to make sure your request doesn't get lost in this closed issue, I'd suggest to request it here: https://woocommerce.com/feature-requests/woocommerce/

**Comment by joyryde456** [comment]
> > Any plans to add it to the Quick Edit menu on the product page? That would be IDEAL.
> 
> I haven't seen any plans for that. But to make sure your request doesn't get lost in this closed issue, I'd suggest to request it here: https://woocommerce.com/feature-requests/woocommerce/

Will do! Thanks!

**Comment by jcaip1** [comment]
Can this also work with the REST API?

**Comment by mikkamp** [comment]
> Can this also work with the REST API?

Based on the details in this PR: https://github.com/woocommerce/woocommerce/pull/51264

It's been added to the REST API for products in WooCommerce 9.4. Is that what you were looking for, or is there a particular type of support in the REST API that you were expecting?

**Comment by jcaip1** [comment]
> > Can this also work with the REST API?
> 
> Based on the details in this PR: [#51264](https://github.com/woocommerce/woocommerce/pull/51264)
> 
> It's been added to the REST API for products in WooCommerce 9.4. Is that what you were looking for, or is there a particular type of support in the REST API that you were expecting?

OK, my apologizes I'm on the latest and it didn't work, I'll re-try it or look at the PR more closely, thanks for replying,

**Comment by bryanblden** [comment]
We would need it in the REST API for orders too, could this be done ?

**Comment by mikkamp** [comment]
> We would need it in the REST API for orders too, could this be done ?

This issue is already resolved/closed, so it's best to look for open issues or create a new one. Adding it to the orders endpoints is already being covered here: https://github.com/woocommerce/woocommerce/issues/54020
I'd suggest you join the conversation there.
