### ISSUE TITLE
Update Rating Filter block to the new structure

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#51639]
Following #51096, we need to update the Rating Filter block to the new structure, in which:
- The `woocommerce/product-filter-rating` becomes the parent block, like the `core/query` block, it has rating status settings, but it doesn't render anything except its inner block. It processes filter data and passes it down to inner blocks through block context.
- The `woocommerce/product-filter-rating` now contains the following inner block by default:
	- Group (named as Header)
		- Heading
		- Clear Button
	- List (`woocommerce/product-filter-checkbox-list`): This block consumes the `filterData` block context and renders the filter data.

An example of migration can be found in #51660. The migration should be based on #51642 (or trunk when the PR is merged).

Here is the diagram of the filter block's data flow and filter structure.

![image](https://github.com/user-attachments/assets/22e4bccb-9d2c-4ae9-b586-483de7886e56)

**Comment by retrofox** [comment]
Re-opening to track the follow-ups

- [ ] Support block styles (list, dropdown)
- [ ] Improve preview
- [ ] Implement multiple selection
- [ ] ...

**Comment by dinhtungdu** [comment]
> Support block styles (list, dropdown)

FYI, according to the new design, we don't have the dropdown style anymore.

> Implement multiple selection

Isn't the block multi-select already?

**Comment by retrofox** [comment]
> > Support block styles (list, dropdown)
> 
> FYI, according to the new design, we don't have the dropdown style anymore.
> 
> > Implement multiple selection
> 
> Isn't the block multi-select already?

If we implement the dropdown, it doesn't.

Being said that, I think we can close the issue.
