### ISSUE TITLE
Problema con las columnas de los widgets para edición de producto

### ISSUE THREAD

**Issue by Mauro2004** [woothemes/woocommerce#51632]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

 El error  esta en que  cuando se seleccionan dos columnas    todos los widgets quedan en la segunda columna apliados, la unica manera es poder verlo en 1 ola columna

### Expected behavior

  .

### Actual behavior

.

### Steps to reproduce

1. productos
2. editar producto
3. columns
4. 2 
5. 

### WordPress Environment

c,d

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nigeljamesstevenson** [comment]
Translation:
Problem with columns in product editing widgets

The error is that when two columns are selected, all the widgets remain applied in the second column, the only way is to be able to see it in 1 column.

**Comment by dinhtungdu** [comment]
> [!NOTE]  
> I use English in this and future comments, you can use a translation to translate my reply into your language.

Hi @Mauro2004,

I can't reproduce the issue you mentioned. I tried changing the column count between 1 and 2, the meta boxes move accordingly in my test. Can you move the meta boxes manually from one column to another? It'll help a lot if you can update the reproduction steps with more detailed instructions and include some screenshot/screencast.

**Comment by dinhtungdu** [comment]
Looks like this is duplicate of https://github.com/woocommerce/woocommerce/issues/51684 which is fixed in https://github.com/woocommerce/woocommerce/pull/51734. @Mauro2004 can you check the linked issue and PR to confirm?
