### ISSUE TITLE
Broken Product Editor on Safari 18.0 on MacOS Sequoia

### ISSUE THREAD

**Issue by wyter** [woothemes/woocommerce#51684]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The WooCommerce product editor is broken on Safari 18.0 on MacOS Sequoia when showing a 2-column layout.

### Expected behavior

The product editor should work well on Safari 18.0 on MacOS Sequoia when using a 2-column layout. It should keep the columns well laid out instead of flushing everything to the left apart from the product data metabox. It should be possible to edit all product metaboxes as well as drag and drop them from the left column to the right column.

### Actual behavior

WooCommerce product editor is broken on Safari 18.0 on MacOS Sequoia when showing a 2-column layout. It will only show the product data metabox on the right while it flushes the rest to the left and makes some of them uneditable. Further, they can't be dragged and dropped back to the right.

The product editor appears to work well on other browsers (like Google Chrome Version 128.0.6613.139). It also works well on Safari 18.0 if one selects a 1-column layout in screen options.

### Steps to reproduce

1. Make sure you're using Safari 18.0 on MacOS Sequoia
2. Confirm on Screen Options that you're using the 2 columns layout
![Annotation on 2024-09-25 at 16-24-43](https://github.com/user-attachments/assets/6a1ce8e3-32f5-4d33-81c2-63be414e5127)

3. Go to your site's WP-Admin → Products → Add new
4. Notice that the product editor only displays the product data metabox on the right and pushes everything else to the right. It's impossible to type in the product short description as well. It is also impossible to drag and drop the other metaboxes to the left.
![Annotation on 2024-09-25 at 16-29-26](https://github.com/user-attachments/assets/87bfc36f-cfe7-42bb-808a-cd387e8b743f)

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ❌ To allow logging
make /srv/htdocs/wp-content/uploads/wc-logs/ writable.

WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.11.9-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Jetpack: by Automattic – 13.9-a.7
WooCommerce: by Automattic – 9.3.2

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 0 B

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-26 13:08:44 +00:00
Options: ✔
Notes: 56
Onboarding: -

### Action Scheduler ###

Complete: 3
Oldest: 2024-09-25 13:09:17 +0000
Newest: 2024-09-25 13:10:23 +0000

Pending: 1
Oldest: 2024-09-26 13:09:17 +0000
Newest: 2024-09-26 13:09:17 +0000


### Status report information ###

Generated at: 2024-09-25 13:29:56 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wyter** [comment]
First reported on 8773375-zen

**Comment by chihsuan** [comment]
Another user reported the same issue 8780066-zen

**Comment by namiokuzono** [comment]
Woo FB community https://www.facebook.com/share/p/ojbhQjtjNNsgc8ke/?

**Comment by namiokuzono** [comment]
Community members discussions with some resolutions noted: https://wordpress.org/support/topic/safari-18-0-breaking-classic-editor/#utm_medium=referral&utm_source=facebook.com&utm_content=social

**Comment by louwie17** [comment]
I will work on a fix on the WooCommerce side, as the fix is pretty easy.
Although this does feel more like an upstream WordPress issue, but is not noticeable unless the classic editor plugin is enabled. Unlike WooCommerce were we still use the classic form for the product form.

**Comment by namiokuzono** [comment]
8791877-zd-a8c

**Comment by namiokuzono** [comment]
8763795-zd-a8c

**Comment by csnlima1** [comment]
8807442-zd-a8c

**Comment by cardehngeh** [comment]
8820452-zen
