### ISSUE TITLE
[Fatal] Uncaught TypeError (string wanted, array given) | `OrderUtil.php`

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#51690]
During 9.3.x release monitoring, we observed the following fatal error:

```
PHP Fatal error: Uncaught TypeError:
    Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix(): 
    Argument #1 ($status) must be of type string, array given 

called in woocommerce/includes/abstracts/abstract-wc-order.php on line 629 
defined in woocommerce/src/Utilities/OrderUtil.php:239
```

<details>
<summary>Backtrace</summary>

```
Stack trace:

#0 /.../plugins/woocommerce/includes/abstracts/abstract-wc-order.php(629):
Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix(Array)

#1 /.../plugins/woocommerce/includes/class-wc-order.php(286):
WC_Abstract_Order->set_status(Array)

#2 /.../plugins/woocommerce/includes/class-wc-order.php(364):
WC_Order->set_status(Array, '', false)

#3 /.../plugins/tinkoff-woocommerce/tinkoff/success.php(63):
WC_Order->update_status(Array)
```

</details>

Per the backtrace, the origin of the problem in this particular instance is a third-party plugin which appears to be passing an array to [`WC_Order::update_status()`](https://github.com/woocommerce/woocommerce/blob/9.3.2/plugins/woocommerce/includes/class-wc-order.php#L349-L382), which [expects a `string`](https://github.com/woocommerce/woocommerce/blob/9.3.2/plugins/woocommerce/includes/class-wc-order.php#L353) but doesn't have strong typing. Things cascade from there.

Same problem is true of other public methods in the chain, such as [`WC_Order::set_status()`](https://github.com/woocommerce/woocommerce/blob/9.3.2/plugins/woocommerce/includes/class-wc-order.php#L285) (also accepts any type, but only expects a string). Not sure what the correct solution is here, but one possibility is adding defensive checks, throw a *doing-it-wrong* (and/or log an error), and return early without letting things escalate to a fatal error.

**Comment by tomoveout** [comment]
Hi @barryhughes,

I got the same fatal error message when customers buying package from my website, I see transactions from Stripe dashboard but a critical error is shown.

Uncaught TypeError: Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix(): Argument #1 ($status) must be of type string, null given, called in /home/u196177799/domains/tomoveout.com/public_html/fr/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 629 and defined in /home/u196177799/domains/tomoveout.com/public_html/fr/wp-content/plugins/woocommerce/src/Utilities/OrderUtil.php:239  

Do you have any idea to solve this issue ?

Regards.

**Comment by barryhughes** [comment]
We haven't looked at this in any depth just yet, we were just capturing the problem and will address it in due course 👍🏼

**Comment by tentapps** [comment]
We are having the same issue.  Woocommerce and Woocommerce stripe are both fully updated.

We just updated to 8.8.1 and now subscriptions are not renewing and new subscriptions are unable to be created. Here is the trace. Thoughts on this?

Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix() must be of the type string, null given, called in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 629 and defined in /wp-content/plugins/woocommerce/src/Utilities/OrderUtil.php:239

Stack trace:
#0 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(629): Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix() #1 /wp-content/plugins/woocommerce/includes/class-wc-order.php(286): WC_Abstract_Order->set_status() #2 /wp-content/plugins/woocommerce/includes/class-wc-order.php(150): WC_Order->set_status() #3 /wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-p

**Comment by barryhughes** [comment]
Hi @tentapps, it looks like the stack trace was cut-off. Are you able to share the full trace?

**Comment by Otkambasok** [comment]
I got a similar problem on 9.3.3 😞

> Uncaught TypeError: Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix(): Argument #1 ($status) must be of type string, null given, called in /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/woocommerce/includes/wc-order-functions.php on line 151 and defined in /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/woocommerce/src/Utilities/OrderUtil.php:239

**Additional Context** {
    "error": {
        "type": 1,
        "file": "/home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/woocommerce/src/Utilities/OrderUtil.php",
        "line": 239
    },
    "**backtrace**": [
        "",
        "#0 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/woocommerce/includes/wc-order-functions.php(151): Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix()",
        "#1 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/Parsers/DocumentsParser.php(491): wc_get_order_status_name()",
        "#2 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/Parsers/DocumentsParser.php(170): BytePerfect\EDI\Parsers\DocumentsParser->update_status()",
        "#3 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/Parsers/DocumentsParser.php(53): BytePerfect\EDI\Parsers\DocumentsParser->update_order()",
        "#4 /home/Lurker/web/hellomoto23.ru/public_html/wp-includes/class-wp-hook.php(324): BytePerfect\EDI\Parsers\DocumentsParser->process()",
        "#5 /home/Lurker/web/hellomoto23.ru/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()",
        "#6 /home/Lurker/web/hellomoto23.ru/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()",
        "#7 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/Parsers/XMLParser.php(414): do_action()",
        "#8 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/Parsers/XMLParser.php(297): BytePerfect\EDI\Parsers\XMLParser->end_element()",
        "#9 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/Parsers/XMLParser.php(133): BytePerfect\EDI\Parsers\XMLParser->find_next()",
        "#10 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/SaleInterchange.php(139): BytePerfect\EDI\Parsers\XMLParser->parse()",
        "#11 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/SaleInterchange.php(92): BytePerfect\EDI\SaleInterchange->action_import_parse()",
        "#12 [internal function]: BytePerfect\EDI\SaleInterchange->action_import()",
        "#13 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/AbstractInterchange.php(50): call_user_func()",
        "#14 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/SaleInterchange.php(33): BytePerfect\EDI\AbstractInterchange->run()",
        "#15 /home/Lurker/web/hellomoto23.ru/public_html/wp-content/plugins/e-commerce-data-interchange/src/Request.php(245): BytePerfect\EDI\SaleInterchange->run()",
        "#16 /home/Lurker/web/hellomoto23.ru/public_html/wp-includes/class-wp-hook.php(324): BytePerfect\EDI\Request->process_request()",
        "#17 /home/Lurker/web/hellomoto23.ru/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()",
        "#18 /home/Lurker/web/hellomoto23.ru/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()",
        "#19 /home/Lurker/web/hellomoto23.ru/public_html/wp-settings.php(722): do_action()",
        "#20 /home/Lurker/web/hellomoto23.ru/public_html/wp-config.php(103): require_once('/home/Lurker/w...')",
        "#21 /home/Lurker/web/hellomoto23.ru/public_html/wp-load.php(50): require_once('/home/Lurker/w...')",
        "#22 /home/Lurker/web/hellomoto23.ru/public_html/wp-blog-header.php(13): require_once('/home/Lurker/w...')",
        "#23 /home/Lurker/web/hellomoto23.ru/public_html/index.php(17): require('/home/Lurker/w...')",
        "#24 {main}",
        "thrown"
    ]
}

**Comment by barryhughes** [comment]
Thank you for sharing! So, on [this line](https://plugins.trac.wordpress.org/browser/e-commerce-data-interchange/tags/2.0.0/src/Parsers/DocumentsParser.php#L491):

```php
if ( wc_get_order_status_name( $details['Статус заказа'] ) === $details['Статус заказа'] ) {
```

The problem is that first parameter, `$details['Статус заказа']` (translated, that's `$details['order status']`, right?) is probably expected to contain a string like `completed` but, when this problem occurs, is actually `null`. So, where is this coming from? Well, it seems like it is [coming from an XML document](https://plugins.trac.wordpress.org/browser/e-commerce-data-interchange/tags/2.0.0/src/Parsers/DocumentsParser.php#L83) of some kind ... but presumably the XML source being parsed doesn't actually contain a node with this information.

So, I think the authors of your plugin could probably tighten this up and check to make sure they have the information they need, but on our side we can also add some defensive coding to `wc_get_order_status_name()`. I'm not absolutely sure this is the best course of action, but we could for instance just return non-strings unmodified, and also issue a *doing-it-wrong* warning. This would alert developers to the problem, without causing fatals at runtime (...although, it doesn't entirely remove the potential for a fatal error later on in the request) 🤔

**Comment by Otkambasok** [comment]
Got it
Yep, 'Статус заказа' is 'order status' :) 
Thank you very much for such a detailed answer 🤗
