### ISSUE TITLE
Attributes 

### ISSUE THREAD

**Issue by Maudelli** [woothemes/woocommerce#51726]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Nella sezione attributi i testi sono compressi o non allineati o visibili come da screenshot
![Screenshot_20240927-081524_Samsung Internet](https://github.com/user-attachments/assets/9ca532ba-89a7-4b32-8d7d-2b9691ab6128)

### Expected behavior

Leggibilità e editing della sezione attributi

### Actual behavior

Impossibile editare la sezione attributi

### Steps to reproduce

![Screenshot_20240927-081524_Samsung Internet](https://github.com/user-attachments/assets/aadeada7-f134-4087-8288-67bda5ad8fc0)

### WordPress Environment

![Uploading Screenshot_20240927-083958_Samsung Internet.jpg…]()

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Stojdza** [comment]
Hello @Maudelli!

Thank you for reporting this issue. We appreciate your feedback on the attributes section's readability and editability. To help us better understand and address the problem you're experiencing, could you please provide some additional information?
- A detailed list of steps to reproduce the issue;
- Specific details about your WordPress environment (System status report);
- Any error messages or logs related to this issue;
- A more detailed description of what you expect to see versus what is currently happening.

This additional context will help us investigate the problem.

Thank you for your cooperation in helping us improve WooCommerce.
