### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by aksthelion** [woothemes/woocommerce#51737]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Self hosted WooCommerce.
Payments -> Overview

```
   at sM (https://mystore.com/wp-content/plugins/woocommerce-payments/dist/index.js?ver=8.2.2:9:324909)
    at Suspense
    at U (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:461617)
    at div
    at div
    at Tr (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:540470)
    at div
    at sw (https://mystore.com/wp-includes/js/dist/components.min.js?ver=36b97398bf090476214e:34:226008)
    at lw (https://mystore.com/wp-includes/js/dist/components.min.js?ver=36b97398bf090476214e:34:226686)
    at dw (https://mystore.com/wp-includes/js/dist/components.min.js?ver=36b97398bf090476214e:34:227033)
    at w (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/admin-layout/index.js?ver=092d36684bd43b3c307d:1:1989)
    at Or (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:541064)
    at Ir (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:540858)
    at https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:544170
    at https://mystore.com/wp-includes/js/dist/data.min.js?ver=7c62e39de0308c73d50c:9:3292
    at WithSelect(Component) (https://mystore.com/wp-includes/js/dist/compose.min.js?ver=b8d54449305350b51869:9:18934)
    at https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=b12c464487b712c0dad5:2:134861
    at O (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:439453)
    at I (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:438894)
    at a (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:433405)
    at https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:544423
    at https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=b12c464487b712c0dad5:2:135938
    at https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=b12c464487b712c0dad5:2:132813
    at https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=b12c464487b712c0dad5:2:132813
    at https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=b12c464487b712c0dad5:2:134035
    at Ca (https://mystore.com/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=71d1eb5b2f91486cefbb:2:555556)
```

### Expected behavior

Should show the overview content.

### Actual behavior

TypeError: Cannot read properties of undefined (reading 'filter')

### Steps to reproduce

Click on Payments -> Overview menu

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://mystore.com
Site address (URL): https://mystore.com
WC Version: 9.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.29
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/3.0.7

SUHOSIN Installed: –
MySQL Version: 8.0.39
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.3
WC Database Prefix: wp_
Total Database Size: 21.83MB
Database Data Size: 19.93MB
Database Index Size: 1.90MB
wp_woocommerce_sessions: Data: 11.80MB + Index: 0.34MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.46MB + Index: 0.13MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.30MB + Index: 0.17MB + Engine MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_comments: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wp_gla_attribute_mapping_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gla_budget_recommendations: Data: 0.10MB + Index: 0.12MB + Engine MyISAM
wp_gla_merchant_issues: Data: 0.16MB + Index: 0.01MB + Engine MyISAM
wp_gla_shipping_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_gla_shipping_times: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automation_run_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automation_runs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automation_triggers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automation_versions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_automations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_dynamic_segment_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_feature_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_newsletter_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_templates: Data: 1.04MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_scheduled_tasks: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_segments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_sending_queues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_bounces: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_tag: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscribers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_user_agents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2.23MB + Index: 0.07MB + Engine MyISAM
wp_postmeta: Data: 1.46MB + Index: 0.30MB + Engine MyISAM
wp_posts: Data: 1.74MB + Index: 0.16MB + Engine MyISAM
wp_term_relationships: Data: 0.02MB + Index: 0.05MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.04MB + Engine MyISAM
wp_usermeta: Data: 0.33MB + Index: 0.16MB + Engine MyISAM
wp_users: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdr_order_discounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdr_order_item_discounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdr_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 559
mailpoet_page: 1
page: 15
post: 16
product: 138
product_variation: 20
revision: 355
shop_coupon: 1
shop_order: 2
wp_global_styles: 2
wp_navigation: 6
wp_template: 10
wp_template_part: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Stripe Gateway: by WooCommerce – 8.7.0
WooPayments: by WooCommerce – 8.2.2
WooCommerce Shipping & Tax: by WooCommerce – 2.8.2
WooCommerce: by Automattic – 9.3.3

### Inactive Plugins (4) ###

Google for WooCommerce: by WooCommerce – 2.8.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Tawk.to Live Chat: by Tawkto – 0.8.6
WP Menu Cart: by WP Overnight – 2.14.6

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 5 MB

### WC Pages ###

Shop base: #7 - /shop
Cart: #8 - /cart -  Contains the [woocommerce_cart] shortcode
Checkout: #9 - /checkout -  Contains the [woocommerce_checkout] shortcode
My account: #10 - /my-account
Terms and conditions: #66 - /terms-conditions

### Theme ###

Name: Shop
Version: 0.0.1
Author URL: https://mystore.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

....

### WooPayments ###

Version: 8.2.2
Connected to WPCOM: Yes
WPCOM Blog ID: 215015341
Account ID: acct_1MVLt8CKX2KCeQfK
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: advanced
Enabled Fraud Filters: AVS Verification
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Enabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-27 21:18:29 +00:00
Options: ✔
Notes: 153
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2024-09-27 13:21:42 +0000
Newest: 2024-09-27 13:21:42 +0000

Complete: 239
Oldest: 2024-08-27 20:15:06 +0000
Newest: 2024-09-27 15:18:58 +0000

Failed: 739
Oldest: 2023-01-28 21:40:48 +0000
Newest: 2023-10-14 15:42:29 +0000

Pending: 2
Oldest: 2024-09-28 01:01:43 +0000
Newest: 2024-09-28 03:00:00 +0000

### Status report information ###

Generated at: 2024-09-27 15:40:32 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by aksthelion** [comment]
Issue with functions.php

**Comment by vbelolapotkov** [comment]
@aksthelion, thanks for reporting the issue. Unfortunately, I can't reproduce it with the same version of WooCommerce or WooPayments, and the stack trace doesn't give that much hints about what went wrong on your site. So far I can only see that rendering React component (Overview page) fails.

You also mentioned that the issue is with functions.php. Could you please explain more? What made you think it's there?

**Comment by aksthelion** [comment]
Issue was with my theme file which was causing this error. I fixed the theme code and it fixed the issue.

**Comment by vbelolapotkov** [comment]
Got it, glad it works for you now! And thanks for the update. I'm closing the issue then :)

**Comment by BlazPerus** [comment]
**This is still happening**

**Comment by vbelolapotkov** [comment]
@BlazPerus could you please share the info about your environment and full error message so we could check it's the same or something else. Also could you please share which theme are you using and if you tried to reproduce the issue with some default themes, e.g. Storefront?

**Comment by BlazPerus** [comment]
@vbelolapotkov hey, tried to fix this myself and tried almost everything and then I read somewhere that "hard refresh" of broswer might **do the trick (shift + refresh) and it did**, so this fixed my problem.

Before I cleaned the session/cookie/storage/history on browser and it didnt help. Also tried with plugins/themes but no luck.

**Comment by vbelolapotkov** [comment]
Thanks for sharing your tip @BlazPerus, and glad it worked for you! 🙌
