### ISSUE TITLE
cash on deliver does not show up unless Shipping is enabled

### ISSUE THREAD

**Issue by robinne** [woothemes/woocommerce#51756]
Seems it should be possible to setup WooCommerce for only Local Pickup and Cash on Delivery. To use Cash on Delivery, I have learned that Shipping must be enabled. As a workaround I need to update text on the Checkout page to clearly state that there is no Shipping, do not fill out shipping address, do not fill out Billing address. Would be nice to only have Local Pickup and Cash on Delivery.

### Discussed in https://github.com/woocommerce/woocommerce/discussions/51753

<div type='discussions-op-text'>

<sup>Originally posted by **robinne** September 28, 2024</sup>
I only want to show Cash on Delivery. This has not worked on a test wordpress site. This has not worked on Docker on localhost, this has not worked on Hostinger which is wordpress friendly and very easy to configure and setup wordpress.

<img width="884" alt="WPPhoto" src="https://github.com/user-attachments/assets/5ef4d2b4-4a3c-4e71-a4d7-24226a7984ef">
<img width="841" alt="WPPhoto1" src="https://github.com/user-attachments/assets/71970836-ec33-44e8-974d-842308b1b972">
<img width="1067" alt="WPPhoto2" src="https://github.com/user-attachments/assets/fdd3436a-6d7c-4084-8151-f3a2dcbdd961">
<img width="1525" alt="WPPhoto3" src="https://github.com/user-attachments/assets/faf54751-67df-47e7-9111-de7980a7aacb">
</div>

**Comment by vbelolapotkov** [comment]
@robinne, thanks for your report. It's possible to use COD as a payment method for local pickup orders. A good example of how to configure it is described in this guide: https://woocommerce.com/document/local-pickup/ . 

However, as I understand, you want to use that option for all shipping addresses. In this case you'd need to add local pickup shipping method to the default zone called `Rest of the world`. This way, cash on delivery will be available as a payment option for any address.

You can read more about shipping zones [here](https://woocommerce.com/document/setting-up-shipping-zones/#shipping-zones) if necessary.

**Comment by vbelolapotkov** [comment]
I'm closing the issue due to no response in 2 weeks. @robinne if you feel it's still relevant, feel free to reopen.

**Comment by robinne** [comment]
Hi, sorry. I think I just have to work around this and add notes to the checkout to not select SHIP. I cannot choose Local Pickup from Rest of the World, see attached for the only 2 options I have. I do have a Local Pickup location already set.
![Image](https://github.com/user-attachments/assets/756e1d77-b2e2-476e-9a6a-e368bf0cab19)

**Comment by vbelolapotkov** [comment]
Have you tried to check `Local pickup settings page`? 
If not working I'd also suggest trying to create some shipping zone other than the rest of the world and configuring pickup there.

Last but not least, you can consider using `Enable for shipping methods` setting in cash on delivery payment method settings page (Settings > Payments > Cash on delivery) to make it appears for local pickup shipping option.

**Comment by robinne** [comment]
Yes, not a lot to change under Local pickup settings. I enabled Local Pickup for COD, still get both SHIP and Pickup options. I will just move on and add labels where I can. Thank you.
