### ISSUE TITLE
[Enhancement]: Improve core profiler plugin installation permission error message

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#51763]
### Describe the solution you'd like

Currently, when a user tries to install the core profiler plugin without the required permissions, it displays a generic error message `Oops! We encountered a problem while installing tiktok-for-business, pinterest-for-woocommerce, woocommerce-payments, google-listings-and-ads,...`. This is not helpful for the user to understand what went wrong. It would be great to improve this error message to something like `You do not have the required permissions to install plugins. Please contact your site administrator for assistance.`

<img width="1351" alt="Screenshot 2024-09-30 at 15 22 07" src="https://github.com/user-attachments/assets/de193f6f-dc15-47e2-8d73-cef4474f491d">

### Additional context

To reproduce the issue, use shop manager role to complete core profiler plugin installation.

**Comment by rjchow** [comment]
For later reference, the permissions required to render CoreProfiler is ['manage_woocommerce'](https://github.com/woocommerce/woocommerce/blob/65efc7398f5531dff9e2790063ab252b958ed687/plugins/woocommerce/client/admin/client/layout/controller.js#L263) and to install plugins is ['install_plugins'](https://github.com/woocommerce/woocommerce/blob/65efc7398f5531dff9e2790063ab252b958ed687/plugins/woocommerce/src/Admin/API/Plugins.php#L220)

The "Shop Manager" role included in WC is an instance of such a user role combination

**Comment by ilyasfoo** [comment]
@chihsuan @rjchow would it be even better if we preemptively check permission before installing extensions and display the error before they attempt?

**Comment by rjchow** [comment]
Big brain idea! I’ll do that
