### ISSUE TITLE
Product Filters Redesign > Active Filters: Update block styles to match the design

### ISSUE THREAD

**Issue by thealexandrelara** [woothemes/woocommerce#51787]
# Description

The Active block informs shoppers which product filters are active and lets them easily clear them. As part of the work to redesign the Product Filters blocks, we need to update the design of the Active filters block to the new design.

# Dependencies

> [!IMPORTANT]
> This issue is blocked by #51641 

# Acceptance Criteria

## Scenario 1: The filter chips match the design in the editor
_**Given**_  a merchant visits a template
_**and**_  adds the Product Filters (Experimental) block to the template
_**When**_  the block is rendered in the editor
**_Then_** the filter chips match the design.

| Current | Expected |
|--------|--------|
| ![CleanShot 2024-09-30 at 16 52 39@2x](https://github.com/user-attachments/assets/b94df9cc-a45b-49f0-b4fa-58f78e1f366c) | ![CleanShot 2024-09-30 at 16 51 36@2x](https://github.com/user-attachments/assets/6cf698f2-068b-45d6-a88f-31d4be2dd706) | 

---

## Scenario 2: The filter chips match the design on the frontend
_**Given**_  a shopper visits a page that has the Product Filters block added to it
_**When**_ the block is rendered on the frontend
_**Then**_ the filter chips match the design.

| Current | Expected |
|--------|--------|
| ![CleanShot 2024-09-30 at 16 52 39@2x](https://github.com/user-attachments/assets/b94df9cc-a45b-49f0-b4fa-58f78e1f366c) | ![CleanShot 2024-09-30 at 16 51 36@2x](https://github.com/user-attachments/assets/6cf698f2-068b-45d6-a88f-31d4be2dd706) | 

---

## Scenario 3: The clear button appears below the filter chips in the editor
_**Given**_  a merchant visits a template
_**and**_  adds the Product Filters (Experimental) block to the template
_**When**_ the Active Filters block is rendered in the editor
_**Then**_ the merchant can see the clear button in the canvas and the blocks list view.

| Current | Expected |
|--------|--------|
| ![CleanShot 2024-09-30 at 16 52 39@2x](https://github.com/user-attachments/assets/b94df9cc-a45b-49f0-b4fa-58f78e1f366c) | ![CleanShot 2024-09-30 at 16 51 36@2x](https://github.com/user-attachments/assets/6cf698f2-068b-45d6-a88f-31d4be2dd706) | 

---

## Scenario 4: The clear button appears below the filter chips on the frontend
_**Given**_ a shopper visits a page that has the Product Filters block added to it
_**When**_ the block is rendered on the frontend
_**and**_ the shopper select some filter options
_**Then**_ the Active Filters block correctly renders the selected filters
_**and**_ the clear button is displayed

| Reference  |
|---------|
| ![CleanShot 2024-09-30 at 16 51 36@2x](https://github.com/user-attachments/assets/6cf698f2-068b-45d6-a88f-31d4be2dd706) | 

---

## Scenario 5: Shoppers can clear all selected filters
_**Given**_ a shopper visits a page that has the Product Filters block added to it
_**and**_ the shopper select some filter options
_**When**_ the Active Filters block correctly renders the selected filters
_**and**_ the shopper clicks on the Clear button
_**Then**_ the Active Filters does not display any selected filters
_**and**_ the Clear button disappears
_**and**_ all filters are reset to an empty state

---

## Scenario 6: The Orientation setting is shown on the block toolbar and the Inspector Controls
_**Given**_ a merchant adds the Product Filters block to a page/template
_**When**_ they select the Product Filters block
_**Then**_  the Orientation setting is shown on the block toolbar [Image Reference 1]
_**and**_  the Orientation setting is shown on the Inspector Control [Image Reference 2]

| Image Reference 1: Orientation settings on the block toolbar |
|--------|
| ![CleanShot 2024-09-30 at 17 12 34@2x](https://github.com/user-attachments/assets/e3024f30-a568-45da-a2c8-569ac4f0519c) | 

| Image Reference 2: Orientation settings within the Inspector Controls |
|--------|
| ![CleanShot 2024-09-30 at 17 26 06@2x](https://github.com/user-attachments/assets/18342283-e453-458c-adc8-145b772b717c) | 

---

## Scenario 7: Merchants can edit the block orientation from the block toolbar
_**Given**_ a template/page has the Product Filters block
_**and**_ a merchant selected the block
_**When**_ they change the block orientation setting in the block toolbar to vertical
_**Then**_ the filter chips are shown vertically

| Reference |
|--------|
| ![CleanShot 2024-09-30 at 17 22 29@2x](https://github.com/user-attachments/assets/01f1c471-f41d-4b2a-82cf-c431ca20aad5) | 

---

## Scenario 8: Merchants can edit the block orientation from the inspector controls
_**Given**_ a template/page has the Product Filters block
_**and**_ a merchant selected the block
_**When**_ they change the block orientation setting in the inspector controls to vertical
_**Then**_ the filter chips are shown vertically

| Reference |
|--------|
| ![CleanShot 2024-09-30 at 17 22 29@2x](https://github.com/user-attachments/assets/01f1c471-f41d-4b2a-82cf-c431ca20aad5) | 

---

## Scenario 9: Merchants see the setting to display or hide the Clear all button from the Inspector Controls
_**Given**_ a template/page has the Product Filters block
_**When**_ a merchant select the block
_**and**_ visits the Styles settings for the block
_**Then**_ the setting to enable or hide the Clear all button is shown

| Reference |
|--------|
| ![CleanShot 2024-09-30 at 17 40 35@2x](https://github.com/user-attachments/assets/59656bab-5ba9-48f2-8a80-57d141ee55ba) | 

---

## Scenario 10: Merchants can display or hide the Clear all button from the Inspector Controls
_**Given**_ a template/page has the Product Filters block
_**and**_ a merchant selects the block
_**and**_ visit the Styles settings for the block
_**When**_ they disable the Clear all button setting
_**Then**_ the Clear all button is hidden

---

## Scenario 11: Shoppers don't see the Clear All Button when its setting is disabled
_**Given**_ a shopper visits a page that has the Product Filters block added to it
_**and**_ the shopper select some filter options
_**When**_ the Active Filters block correctly renders the selected filters
_**Then**_ the Clear all button is not displayed

---

## Scenario 12: Merchants can edit the Typography, Dimensions and Border settings 
_**Given**_ a template/page has the Product Filters block
_**and**_ a merchant selects the block
_**When**_ visit the Styles settings for the block
_**Then**_ they can edit the Typography, Dimensions, and Border settings
_**and**_ the changes can be seen in the canvas

---

**Comment by dinhtungdu** [comment]
Note that the first and second items should belong to #51641

**Comment by thealexandrelara** [comment]
> Note that the first and second items should belong to #51641

Yes, and this issue is blocked by https://github.com/woocommerce/woocommerce/issues/51641. The idea behind the acceptance criteria section is to establish specific conditions or requirements for the implemented feature to be considered complete. Even though the subtasks are done in other issues, we still need to ensure the changes on this issue do not negatively affect the functionality.
