### ISSUE TITLE
REST API: Add order endpoint to trigger re-sending of email receipts

### ISSUE THREAD

**Issue by coreymckrill** [woothemes/woocommerce#51797]
Currently, when an order is created through the REST API and is marked as "paid", which sets the status of the order to "completed", emails are sent to both merchant and customer, as long as the order data has an email address for the customer. However, there’s no way via the REST API to manually send the order details to the customer again, later, like there is via WP Admin.

The idea here is to create a new endpoint, something like `POST wc/v3/orders/{order ID}/details` (`receipt` is [already taken](https://github.com/woocommerce/woocommerce/blob/e48b0352fec13385077176a1a7216dcc1960fbf4/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingRestController.php#L32-L44)). With this endpoint, you can re-send details about an order to the customer associated with that order.

**Comment by malinajirka** [comment]
@coreymckrill Will it be possible to send the email to an email address provided in a query parameter or will it always automatically send the email to the customer-address set on the order? 

We might be able to work with either approach on the clients, however, it'll impact the designs. Also, if both approaches worked, it would give us more flexibility.

**Comment by coreymckrill** [comment]
@malinajirka the underlying functionality that we're tapping into for this assumes sending to the customer billing email address. So for now that is all that's available.

We can look into making the email address customizable in a separate issue/PR.

**Comment by staskus** [comment]
@malinajirka thanks for bringing it up.

@coreymckrill, with this approach, if the customer email wasn't set before completing the order, then we would need to:
1. Update the order with the customer's email
2. Trigger `"action": "send_order_details"`
3. Email will be sent to a newly set customer email

Correct? Thanks!

**Comment by coreymckrill** [comment]
@staskus that is correct! Update the billing email address in the order.
