### ISSUE TITLE
Accessibility: Headings hidden from screen readers

### ISSUE THREAD

**Issue by vikrampm1** [woothemes/woocommerce#51800]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

The checkout page is not showing any headings in the screen reader headings list because the existing H2s have been hidden from screen reader users with aria-hidden=""true"".  

This is not a significant issue give the presence of the fieldset legends, but it may make it difficult for screen reader users to navigate the page.

<img width="1739" alt="aria-hidden h2" src="https://github.com/user-attachments/assets/02db31b8-553e-44f7-b855-742c8cd00635">

### Component or Page: 

**Page: Checkout Process (Block-Based)**

### Name affected element:

Contact information, Billing address, Payment options H2s

### Relevant code snippets:

`<h2 class="wc-block-components-title wc-block-components-checkout-step__title" aria-hidden="true">Billing address</h2>`

### Recommended fix:

Consider removing the aria-hidden attributes from the H2s so they show in screen reader heading lists and can be used to navigate the page.

**Comment by Manussakis** [comment]
@vikrampm1 This issue can be closed since it was fixed along with the #50925 one.
