### ISSUE TITLE
[Enhancement]: Add "or" between the "proceed to checkout" button and express payment methods on shortcode cart

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#51811]
### Describe the solution you'd like

In the Cart shortcode, when a payment method renders express payment buttons, they come immediately under the "Proceed to checkout" button.

<img width="531" alt="image" src="https://github.com/user-attachments/assets/77a14a95-1d1c-427d-8186-7f6cce7a4569">

It would be a good improvement to separate these by an "OR" like we do in the Cart block (don't necessarily need to change the order, but a separator would be useful).

<img width="580" alt="image" src="https://github.com/user-attachments/assets/54b69d45-8ede-4deb-ad05-f19c13bdfd8e">

**Comment by mikejolley** [comment]
I've looked into this to see if its possible and after some investigation I think this needs to be marked as won't fix and closed. Unlike blocks there is no formal registration of payment buttons in this area. 

There are action hooks such as `woocommerce_proceed_to_checkout` and these can be used to render payment buttons e.g. here in [Woo Pay](https://github.com/Automattic/woocommerce-payments/blob/6639fe9fb7887e828ebc0386e6f4c536602d0e7d/includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php#L91).

Core renders some buttons for some gateways using `wc_get_pay_buttons` via this hook as well.

We would only want to inject `—OR—` if payment buttons were actually present, but we do not know:

1. If a button was rendered, or
2. If it was rendered before or after the “Proceed to Checkout” button

So its not looking feasible, and given this is shortcode I wouldn’t expect us to create a formal solution to solve this.
