### ISSUE TITLE
Parent Order linking to the same order make a DoS

### ISSUE THREAD

**Issue by rspadim** [woothemes/woocommerce#51822]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

if i do $order->set_parent($order->id); the woocommerce stop, the same occur if you set parent_order_id at orders table
should be interesting the set_parent avoid this, and any recursive of the same id be avoided, this cause a DoS very dificult to find, cpu goes 100% memory too, EC2 server stop responding, and no log is output only kernel out of memory

### Expected behavior

don't accept same order id at set parent order

### Actual behavior

allow any number

### Steps to reproduce

$order->set_parent($order->id); 
or at database orders table set the parent_order_id as order_id

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): xxxxx
Site address (URL): xxxxx
WC Version: 9.2.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.3.6
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 8.5.0
OpenSSL/3.0.13

SUHOSIN Installed: –
MySQL Version: 10.11.8-MariaDB-0ubuntu0.24.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.3
WC Database Prefix: wp_
Total Database Size: 29.52MB
Database Data Size: 22.00MB
Database Index Size: 7.52MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.48MB + Index: 1.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_check_email_error_logs: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_check_email_log: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
xxxxxxxxxxxxxxxxxx: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xxxxxxxxxxxxxxxxxx: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
xxxxxxxxxxxxxxxxxx: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.05MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 2.98MB + Engine InnoDB
wp_posts: Data: 6.44MB + Index: 0.33MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_am_api_activation: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_am_api_resource: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_am_associated_api_key: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_am_grace_period: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_am_legacy_product_id: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_am_secure_hash: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_od_time_framemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_od_time_frames: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_xyz_ips_short_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.05MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 183
cartflows_flow: 1
cartflows_step: 2
customize_changeset: 1
nav_menu_item: 36
page: 21
post: 4
product: 260
product_variation: 294
revision: 284
shop_order_placehold: 41
us_content_template: 1
us_grid_layout: 2
us_header: 1
us_page_block: 1
wc_membership_plan: 1
wc_order_status: 9
wc_user_membership: 1
wcpa_pt_forms: 1
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.19.22
xxxxxxxxxxxxx: by Roberto Spadim – 1.0
GTranslate: by Translate AI Multilingual Solutions – 3.0.7
Insert PHP Code Snippet: by xyzscripts.com – 1.3.7
WPBakery Page Builder: by Michael M - WPBakery.com – 7.9
xxxxxxxxxxxxx: by Roberto Spadim – 1.0.0
UpSolution Core: by UpSolution – 8.28.1
Multi-Carrier ShipStation Shipping for WooCommerce: by OneTeamSoftware – 1.4.14
WooCommerce B2B Sales Agents: by Code4Life – 1.4.7
Woo Composite Products: by Woo – 9.0.1 (update to version 10.1.1 is available)
WooCommerce Cost of Goods: by SkyVerge – 2.13.0 (update to version 2.13.1 is available)
WooCommerce Stripe Gateway: by WooCommerce – 8.7.0
WooCommerce Custom Payment Gateway: by WPRuby – 1.3.10
WooPayments: by WooCommerce – 8.1.1 (update to version 8.2.2 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.8.1 (update to version 2.8.2 is available)
WooCommerce - ShipStation Integration: by WooCommerce – 4.4.4
WooCommerce Subscriptions: by WooCommerce – 6.5.0 (update to version 6.7.0 is available)
WooCommerce Warranty Requests: by WooCommerce – 2.4.2 (update to version 2.5.5 is available)
WooCommerce: by Automattic – 9.2.3 (update to version 9.3.3 is available)
WP Crontrol: by John Blackbourn – 1.17.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Inactive Plugins (1) ###

YITH WooCommerce Wishlist: by YITH – 3.37.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 9 MB

### WC Pages ###

Shop base: #7 - /
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Impreza
Version: 8.28
Author URL: http://us-themes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.1.1
Connected to WPCOM: Yes
WPCOM Blog ID: 236575154
Account ID: acct_1Pzq1RCLBIODwy88
Payment Gateway: ❌ Needs setup
Test Mode: Enabled
Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Disabled
Fraud Protection Level: basic
Multi-currency: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: xxxxxxxxxxxxxxxxxxxxxx
Subscriptions-core Library Version: 7.3.0
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Florida

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Composite Products ###

Database Version: 9.0.1
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-10-02 19:43:46 -02:00
Options: ✔
Notes: 70
Onboarding: completed

### Action Scheduler ###

Complete: 2,299
Oldest: 2024-09-01 19:44:54 +0000
Newest: 2024-10-01 20:45:02 +0000

Failed: 1,108
Oldest: 2024-09-01 20:00:06 +0000
Newest: 2024-10-01 20:27:02 +0000

Pending: 7
Oldest: 2024-10-01 20:57:02 +0000
Newest: 2024-10-30 00:00:02 +0000

### Status report information ###

Generated at: 2024-10-01 18:53:18 -02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@rspadim The [`set_parent_id` method](https://github.com/woocommerce/woocommerce/blob/a35e55081fadc2d22922233ca4a150cade39e2a7/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L614) actually does check to make sure it isn't the same order ID. Is there somewhere else in the code you're thinking of where this check doesn't happen?
