### ISSUE TITLE
Product Collection: refactor "is_product_collection_block" check

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#51854]
A comment came out of this PR review https://github.com/woocommerce/woocommerce/pull/51790#pullrequestreview-2342859660

Manish mentioned that since we're repeatedly using the same "if" clause check -- we should refactor it to it's own helper function. Ref on the exact lines:
https://github.com/woocommerce/woocommerce/blob/ac6362b6cb814edeea63f439a0d9e3c4288c1f90/plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php#L1714-L1716 https://github.com/woocommerce/woocommerce/blob/ac6362b6cb814edeea63f439a0d9e3c4288c1f90/plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php#L1759-L1761
https://github.com/woocommerce/woocommerce/blob/ac6362b6cb814edeea63f439a0d9e3c4288c1f90/plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php#L1789-L1791

**Comment by ObliviousHarmony** [comment]
While this code _is_ used in many places, I'm not actually sure a helper function would be that useful? It would just be something like `ProductCollectionUtils::is_product_collection( $query_vars )` and encapsulate that check, right? I would agree if there were a number of repetitive checks but we need to unwrap `$query_vars` anyway so the scope this would cover is very small.

cc @imanish003

**Comment by kmanijak** [comment]
> While this code is used in many places, I'm not actually sure a helper function would be that useful? It would just be something like ProductCollectionUtils::is_product_collection( $query_vars ) and encapsulate that check, right? I would agree if there were a number of repetitive checks but we need to unwrap $query_vars anyway so the scope this would cover is very small.

I took a task and prepared a PR. I didn't read this comment before but I'm with @ObliviousHarmony on this one! I'm against merging it 😆 I don't see much value, and IMO it's less readable now. @imanish003, feel free to review. I left it in the draft, but if you feel like it's a good one, let me know, and we can merge: https://github.com/woocommerce/woocommerce/pull/52261.

**Comment by imanish003** [comment]
After looking at the PR code, I agree that it doesn't add much value. I thought this refactor would remove more than one line, but it looks like the new function is only replacing one line. My idea was that we could make it part of the "ProductCollection.php" file itself but as a helper function. I don't think it makes sense to add it to the "ProductCollectionUtils.php" file.

I agree, and let's close this issue. This will probably be taken care of as part of the #51534 issue while breaking up the "ProductCollection.php" file into smaller files 😀

**Comment by kmanijak** [comment]
Closing the PR and the issue! Thanks all for participating, it was fun 😆
