### ISSUE TITLE
[Fatal] Array and string offset access syntax with curly braces is no longer supported | wc-formatting-functions.php

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#51882]
Fatal error logged in WooCommerce 9.3.3:

`PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-formatting-functions.php on line 746`

<details><summary>Stack trace</summary>

```
--
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-formatting-functions.php on line 746
  |  

<br class="Apple-interchange-newline">
```

</details> 

### Steps to reproduce

No clear steps to reproduce, but observed over 700 instances of this problem on Fri Sep 27, 1200 UTC to 2359 UTC on 5+ sites.

**Comment by barryhughes** [comment]
Closing. We could be missing something, but we don't think this is actually a concern in 9.3.3:

[wc-formatting-functions.php:746](https://github.com/woocommerce/woocommerce/blob/9.3.3/plugins/woocommerce/includes/wc-formatting-functions.php#L746)

It seems more likely this is from an older version of WooCommerce, or that the plugin was modified directly on the sites in question.
