### ISSUE TITLE
Accessibility: Non-list content is incorrectly marked as a list

### ISSUE THREAD

**Issue by vikrampm1** [woothemes/woocommerce#51903]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

Non-list content is being incorrectly marked up as a list using `<ul>, <ol>, or <dl>` elements.

![Image](https://github.com/user-attachments/assets/562f486e-8a62-48f5-a2d0-7815d0043e89)

### Component or Page: 

Component: Mini Cart Slide-Out / Modal 

### Name affected element:

1. Size: Et

### Relevant code snippets:

`<ul class="wc-block-components-product-details"><li class="wc-block-components-product-details__size"><span class="wc-block-components-product-details__name">Size:</span> <span class="wc-block-components-product-details__value">Et</span></li></ul>`

### Recommended fix:

Action: Eliminate the list markup from the content.
How to fix:
1. Omit the `<ul>/<li> or <ol>/<li>` elements surrounding the content in the HTML code. Alternatively,
2. Implement role=""presentation"" to strip the list semantics from the markup.

Only include a 
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html

**Comment by mikejolley** [comment]
This is a list if there are multiple attributes present, FYI. If you test with a variable product with more than one attribute you'll see multiple items.
