### ISSUE TITLE
[Enhancement]: [StoreApi] Make 'order' endpoint can be extended with ExtendSchema

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#51911]
### Describe the solution you'd like

currently 'order' endpoint is not available to extend, see:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/available-endpoints-to-extend.md

Please add this feature because sometimes we need to get data which only available in meta data of the order

**Comment by mikejolley** [comment]
Can you explain more about your use case? Because the other REST API (v3) which is the authenticated version does surface more data than the customer/store facing API.

**Comment by alexflorisca** [comment]
Closing this as hasn't had an answer in 2 weeks. Feel free to open again if it's still an issue
