### ISSUE TITLE
Accessibility: Incorrect focus order

### ISSUE THREAD

**Issue by vikrampm1** [woothemes/woocommerce#51927]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

The elements on the product zoom modal don't follow a logical (Top to bottom, left to right) keyboard sequence. Close (Esc)>> Toggle fullscreen>> Zoom in/out, breaking the expected keyboard navigation for the web page.

![Image](https://github.com/user-attachments/assets/3f602ca1-91d6-481a-bcd8-7eb1f98846f3)

### Component or Page: 

Page: Product Single (Simple)  

### Name affected element:

1. Close (Esc)
2. Toggle fullscreen
3. Zoom in/out

### Relevant code snippets:

N/A

### Recommended fix:

Change the focus order to match the visual order of elements on the page. Check that the tabindex is not modified and that there is no CSS visually moving elements out of order from how they appear in the DOM.

**Comment by darrenjacoby** [comment]
@ankitguptaindia left a comment in the PR, let me know.

**Comment by darrenjacoby** [comment]
@ankitguptaindia left a comment in the PR again.
