### ISSUE TITLE
[Enhancement]: [StoreApi] Make Order endpoint doesnt require key

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#51934]
### Describe the solution you'd like

Before I'm using this woocommerce built in shortcode for order tracking page:
https://github.com/woocommerce/woocommerce/blob/e48b0352fec13385077176a1a7216dcc1960fbf4/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-order-tracking.php#L50

This page exist to make guest can track their previous order using any device. But I want to make it headless but current Store Api doesnt let me replicate this feature because it require key, which is not avialable if guest track order from another device

See:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/docs/order.md#get-order

Please reconsider making 'key' a requirement. or add a filter to change this behaviour

**Comment by senadir** [comment]
This screen is not meant for order tracking from a new device, returning orders with just emails is very risky as it exposes personal data like shipping and billing addresses as well as previous orders.
Consider having your own secure intermediate endpoint that fetch keys based on email, but I wouldn't suggest this.
