### ISSUE TITLE
WooCommerce cart page wrong product

### ISSUE THREAD

**Issue by Alex-sas6** [woothemes/woocommerce#51944]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When i add a product, or products in the cart and go to the cart page it shows one different product from what my choice was. 

### Expected behavior

I expect to see the product/s that i click on (add to cart), not some random product

### Actual behavior

When i add a product, or products in the cart and go to the cart page it shows one different product from what my choice was. 

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/6f1d6c40-0197-433c-b65a-4b6217de31c7)

![Image](https://github.com/user-attachments/assets/3fd316d4-ba60-4e6c-b0c4-95f08deceacd)

![Image](https://github.com/user-attachments/assets/73dfd124-4e43-4d9a-9f02-25afa22dbd60)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://acousticbuild.com
Site address (URL): https://acousticbuild.com
WC Version: 9.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: bg_BG
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.23
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 8.10.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.19-MariaDB-log
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.3
WC Database Prefix: knR_
Total Database Size: 33.11MB
Database Data Size: 26.89MB
Database Index Size: 6.22MB
knR_woocommerce_sessions: Data: 0.63MB + Index: 0.02MB + Engine MyISAM
knR_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
knR_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_actionscheduler_actions: Data: 0.85MB + Index: 0.29MB + Engine MyISAM
knR_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_actionscheduler_logs: Data: 0.49MB + Index: 0.35MB + Engine MyISAM
knR_berocket_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
knR_dgwt_wcas_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
knR_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_gla_attribute_mapping_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_gla_budget_recommendations: Data: 0.10MB + Index: 0.12MB + Engine MyISAM
knR_gla_merchant_issues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_gla_shipping_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_gla_shipping_times: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_jetpack_sync_queue: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_litespeed_img_optming: Data: 0.04MB + Index: 0.06MB + Engine MyISAM
knR_options: Data: 11.57MB + Index: 0.14MB + Engine MyISAM
knR_postmeta: Data: 9.83MB + Index: 3.87MB + Engine MyISAM
knR_posts: Data: 2.22MB + Index: 0.27MB + Engine MyISAM
knR_rank_math_analytics_gsc: Data: 0.39MB + Index: 0.25MB + Engine MyISAM
knR_rank_math_analytics_inspections: Data: 0.19MB + Index: 0.05MB + Engine MyISAM
knR_rank_math_analytics_objects: Data: 0.08MB + Index: 0.04MB + Engine MyISAM
knR_rank_math_internal_links: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
knR_rank_math_internal_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
knR_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_termmeta: Data: 0.07MB + Index: 0.05MB + Engine MyISAM
knR_terms: Data: 0.04MB + Index: 0.10MB + Engine MyISAM
knR_term_relationships: Data: 0.17MB + Index: 0.30MB + Engine MyISAM
knR_term_taxonomy: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
knR_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_usermeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
knR_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
knR_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
knR_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wc_orders: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
knR_wc_orders_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
knR_wc_order_addresses: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wc_order_operational_data: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wc_product_meta_lookup: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
knR_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woof_sd: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_woof_sd_presets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wpforms_payments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wpforms_payment_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
knR_wpf_filters: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
knR_wpf_meta_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wpf_meta_values: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
knR_wpf_meta_values_bk: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

acf-field: 51
acf-field-group: 16
attachment: 1749
br_product_tab: 1
custom_css: 1
customize_changeset: 6
elementor_library: 6
filter-field: 86
filter-seo-rule: 1
filter-set: 16
is_search_form: 4
nav_menu_item: 6
oembed_cache: 1
page: 11
post: 3
product: 477
revision: 614
rm_content_editor: 1
shop_order_placehold: 2
woo_product_tab: 1
wp_global_styles: 3
wp_navigation: 1
wp_template: 2
yith_wcan_preset: 1
ymc_filters: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Advanced Custom Fields: by WP Engine – 6.3.6
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.28.1
Starter Templates: by Brainstorm Force – 4.4.3
Beautiful and responsive cookie consent: by Beautiful Cookie Banner – 4.3.0
Bulgarisation for WooCommerce: by Autopolis.bg – 3.0.30
Easy Auto SKU Generator for WooCommerce: by Dan Zakirov – 1.2.0
Elementor: by Elementor.com – 3.24.5
Filter Everything PRO: by Andrii Stepasiuk – 1.8.1
Site Kit by Google: by Google – 1.136.0
Rank Math SEO: by Rank Math – 1.0.229
WP Version Remover: by SuperHosting.BG – 1.0
MultiStep Checkout for WooCommerce: by ThemeHigh – 2.2.8
WooCommerce Checkout Manager: by QuadLayers – 7.5.9
WooCommerce: by Automattic – 9.3.3
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.6.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: BGN (лв.)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 23 KB

### WC Pages ###

Shop base: #7 - /%d0%ba%d0%b0%d1%82%d0%b0%d0%bb%d0%be%d0%b3/
Cart: #8 - /kolichka/ -  Contains the woocommerce/cart block
Checkout: #4216 - /porachka/ -  Contains the [woocommerce_checkout] shortcode
My account: #10 - /moyat-profil/
Terms and conditions: #16 - /%d0%bf%d1%80%d0%b0%d0%b2%d0%b8%d0%bb%d0%b0-%d0%b8-%d1%83%d1%81%d0%bb%d0%be%d0%b2%d0%b8%d1%8f/

### Theme ###

Name: Astra
Version: 4.8.2
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-10-07 13:03:15 +02:00
Options: ✔
Notes: 79
Onboarding: completed

### Action Scheduler ###

Canceled: 24
Oldest: 2024-10-02 20:27:55 +0000
Newest: 2024-10-02 20:27:55 +0000

Complete: 2,457
Oldest: 2024-09-11 12:42:50 +0000
Newest: 2024-10-06 11:37:57 +0000

Failed: 4
Oldest: 2024-01-05 13:21:15 +0000
Newest: 2024-02-24 09:51:23 +0000

Pending: 2
Oldest: 2024-10-07 11:37:57 +0000
Newest: 2024-10-09 12:48:32 +0000

### Status report information ###

Generated at: 2024-10-06 15:08:28 +02:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
This looks like a caching issue. If I remove items from the cart and refresh, the cart item is still there.

I'd suggest starting by disabling caching plugins to confirm the issue.

**Comment by Alex-sas6** [comment]
I'm using WP-Optimize for caching. I already try to disable it and the problem was still present.

**Comment by mikejolley** [comment]
Some web hosts also implement caching. I would leave the caching plugin disabled for the time being to help narrow the issue.

**Comment by Alex-sas6** [comment]
Alright, i disabled WP-Optimize

**Comment by mikejolley** [comment]
Is `advanced-cache.php` still present? If it is, it should be removed. You should then see if there is anything caching hosting side. 

These were my replication steps:

1. Add product to cart
2. Go to cart page
3. Remove from cart
4. Refresh page
5. Item still displayed, but the remove button no longer works. 

That said, this only happened once and I can no longer replicate.

**Comment by Alex-sas6** [comment]
Think i found the problem. In the hosting provider web page i found SuperCache Manager option that was ON. I spoke with the provider and came to conclusion to turn the SuperCache Manager option OFF. Right now i don't have the cart page issue even with all plugins activated. I will post if everything is ok after few days.

**Comment by mikejolley** [comment]
Great. Ill close this out then. It can be reopened if needed.

Thanks

**Comment by najm-uddin** [comment]
Yes,I have the same issue. I'm using SiteGround hosting.

**Comment by najm-uddin** [comment]
wrong product is being added to the cart

**Comment by galleta5** [comment]
I have the same issue too. I'm using SiteGround and Elementor theme with WooCommerce.

**Comment by zsoltnemesnyikwebery** [comment]
> I have the same issue too. I'm using SiteGround and Elementor theme with WooCommerce.

I'm not sure if it's related, but we've experienced a similar issue with the latest WP and Elementor versions...

WP update --> Product added to cart --> Incorrect product is added to the cart

The solution was to disable the Element caching (Dashboard > Elementor > Settings > Performance tab > Element cache (deactivate). Earlier WP versions had this feature under the Features tab I guess.
