### ISSUE TITLE
Cross-sells does not work

### ISSUE THREAD

**Issue by yuvalassayag** [woothemes/woocommerce#51946]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

hey I would like to have the option to add products at the cart and im trying to use woo commerce to do it and I dont have the "Product" option in my woo commerce. 

### Expected behavior

help me

### Actual behavior

help me

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/68dc5740-9ae0-450b-9829-bc78567e3b3a)

### WordPress Environment

help me

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
![Image](https://github.com/user-attachments/assets/28fc4fa8-a2ec-4c98-89ac-4403075e1d88)

^ You need to edit a product to see the cross sells section. 

Documentation for this feature is here:

https://woocommerce.com/document/related-products-up-sells-and-cross-sells/
