### ISSUE TITLE
HPOS compatibility checkbox label unclear

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#51941]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

on /wp-admin/admin.php?page=wc-settings&tab=advanced&section=features the checkbox for HPOS compatibility mode has the text:

>Enable compatibility mode (synchronizes orders to the posts table).

However, when reading https://developer.woocommerce.com/docs/a-large-stores-guide-to-enable-hpos-on-woocommerce/ it seems that checking that checkbox will not only synchronize them to the posts table - but if legacy is enabled as authoritative, sync them to the HPOS tables (from posts table)

### Expected behavior

Clarify checkbox label

### Actual behavior

Unclear/contradicting description

### Steps to reproduce

none

### WordPress Environment

WooCommerce 9.3

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by asumaran** [comment]
@kkmuffme thanks for reporting the issue. I think you're right, we need to tweak the description a little bit. Do you have a suggestion? I'm going to change it to `Enable compatibility mode (Synchronize orders between both order data storage).` what do you think? cc @vedanshujain

**Comment by vedanshujain** [comment]
Maybe `Enable compatibility mode (Synchronize orders between High-performance order storage and WordPress posts storage).`, as these are the names of actual settings.

**Comment by asumaran** [comment]
Addressed via https://github.com/woocommerce/woocommerce/pull/51962
