### ISSUE TITLE
Move jetpack connection consent above button

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#52047]
## Issue Description

The Jetpack connection consent should be placed above the button and read:

By clicking [Button Text], you agree to our [Terms of Service](https://wordpress.com/tos/) and to [sync your site’s data](https://jetpack.com/redirect/?source=jetpack-support-what-data-does-jetpack-sync) with us.

**Comment by moon0326** [comment]
This is done, but only shown on horizon.wordpress.com at the moment.

We'll need to clean up the code to show the passwordless related changes on prod later.

Closing it for now.
