### ISSUE TITLE
[WC Payments NOX]: Implement drag and drop for main payment gateways on the settings page

### ISSUE THREAD

**Issue by oaratovskyi** [woothemes/woocommerce#52053]
### Description

Implement a drag-and-drop solution for the payment gateways on the settings page—research existing solutions suggested in pe4Hk0-1zc-p2#comment-1917 before creating one from scratch. We could start from something that does not fully work, and improve it.

### Additional context

In https://github.com/woocommerce/woocommerce/pull/52030, I suggested extracting the drag-and-drop part to a separate issue. 

Discussion about what not to sort: p6riRB-bfm-p2#comment-11466

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Dev notes
Reactifying the Payments settings page: pe4Hk0-1ly-p2
Populate react-powered main payments settings screen PR: https://github.com/woocommerce/woocommerce/pull/50825

### Additional context
PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

**Comment by anu-rock** [comment]
See also the proposed nuance of allowing to sort only the active payment gateways as opposed to PGs + suggestions: p6riRB-bfm-p2#comment-11466 (link added to issue description too).

**Comment by oaratovskyi** [comment]
we can close this one since we're covering the settings main page in #53247 
@vladolaru WDYT?

**Comment by vladolaru** [comment]
Sure thing. Closing...
