### ISSUE TITLE
[DOC] Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [woothemes/woocommerce#52099]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing WooCommerce application as shown [here](https://elest.io/open-source/woocommerce). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example Button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/woocommerce)

**Comment by piinthecloud** [comment]
Hi @kaiwalyakoparkar - It looks like you are interested in forming a partnership with Woo. We have some different avenues to connect with our partnerships teams, but the best way to connect for this proposal is through the [affiliates program](https://woocommerce.com/affiliates/). I've already given the person going through that form a heads-up that a request will be coming in via [kaiwalya@elest.io](mailto:kaiwalya@elest.io) should you be interested in filling it out.
