### ISSUE TITLE
patterns_ai_data CPT shouldn't be registered on sites that don't use the CYS AI flow

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#52153]
The CYS AI flow is only used on certain sites, so we would like to make sure AI-specific resources are only loaded on those sites. That includes `/src/Blocks/Patterns/AIPatterns.php`, for example, which registers the `patterns_ai_data` CPT.

This issue is about:

1. Making sure the `patterns_ai_data` CPT isn't registered unnecessarily on sites that don't use the CYS AI flow. Ideally, making it so we don't initialize the `AIPatterns` class at all.
2. Audit other AI-related PHP classes that we could avoid initializing when not needed.

**Comment by mdperez86** [comment]
I think this is going to be removed when we delete the AI flow.

**Comment by Aljullu** [comment]
> I think this is going to be removed when we delete the AI flow.

Yeah, thanks for pointing it out. I think we can close this one in favor of https://github.com/woocommerce/woocommerce/issues/52548 and https://github.com/woocommerce/woocommerce/issues/52549.
