### ISSUE TITLE
[GlobalStep]  [WP 6.7 Beta 3] Shop page fails to translate into the respective language when the "WooPayments" and "Jetpack" plugins are activated.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#52155]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For WP 6.7 Beta 3, Shop page fails to translate into the respective language when the "WooPayments" and "Jetpack" plugins are activated. 

### Expected behavior

Shop page should be translated into the respective language when the "WooPayments" and "Jetpack" plugins are activated. 

### Actual behavior

Shop page fails to translate into the respective language when the "WooPayments" and "Jetpack" plugins are activated. 

### Steps to reproduce

1.Create a test site.
2. Update the Wordpress version to WP 6.7 Beta 3.
3. Install and activate the Woocommerce version  9.5.0-dev plugins.
4. Install and activate "WooPayments" and "Jetpack" plugins.
5. Go to the Settings> General page.
6. Change site Language.
7. Go to Dashboard> Update page.
8. Click on the Update Translations button.
9. Go to the Shop page.
10. Observe that, Shop page fails to translate into the respective language when the "WooPayments" and "Jetpack" plugins are activated. 

### Note:
1. This issue was only observed in WordPress 6.7 Beta 3.
2. "Doing it Wrong" error is displayed.

### Video
https://github.com/user-attachments/assets/9bae9755-3725-48bf-9878-ad326aab2266

![Image](https://github.com/user-attachments/assets/ce584983-f742-48dd-b118-eead4eea9512)

### WordPress Environment

Woocommerce Version: 9.5.0-dev
WordPress version: WP 6.7 Beta 3

PC:
Windows 10
Chrome (Version 130.0.6723.59)
Firefox (Version 131.0.3)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7-beta3-59248
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.14

SUHOSIN Installed: –
MySQL Version: 10.11.9-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 18
product_variation: 7
revision: 3
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Jetpack: by Automattic – 14.0-a.5
Query Monitor: by John Blackbourn – 3.16.4
WooPayments: by WooCommerce – 8.3.1
WooCommerce: by Automattic – 9.5.0-dev

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### WooPayments ###

Version: 8.3.1
Connected to WPCOM: Sí
WPCOM Blog ID: 238144959
Account ID: acct_1QBBAkCQtjms58WX
Payment Gateway: Activa
Test Mode: Activa
Enabled APMs: card
WooPay: Desactivado
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Activa (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Activa
Auth and Capture: Activa
Documents: Desactivado
Logging: Desactivado

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-10-19 07:44:28 +00:00
Options: ✔
Notes: 59
Onboarding: skipped

### Action Scheduler ###

Complete: 37
Oldest: 2024-10-18 07:46:04 +0000
Newest: 2024-10-18 12:15:12 +0000

Failed: 2
Oldest: 2024-10-18 07:54:16 +0000
Newest: 2024-10-18 08:30:46 +0000

Pending: 1
Oldest: 2024-10-19 07:46:04 +0000
Newest: 2024-10-19 07:46:04 +0000


### Status report information ###

Generated at: 2024-10-18 12:47:51 +00:00
```
</details>

**Comment by Sisanu** [comment]
I can replicate the issue with other plugins as well, not sure if it is WooCommerce related, but rather core 6.7 related. The issue is not that we get the hook warning, but that the translations are not picked up at all.

**Comment by barryhughes** [comment]
✍ Supporting that earlier comment, a combination of Jetpack _plus_ WooCommerce Payments (WooPayments) doesn't seem to be necessary, just adding WooPayments is enough for me to see the problem: WooCommerce (latest trunk code) plus Jetpack by itself doesn't lead to this problem.

**Comment by veljkho** [comment]
I wasn't able to reproduce this issue using WP 6.7 Beta 4 and Woo 9.4 RC3 or even 9.5-dev.
Tested across multiple sites using the steps above.

**Comment by barryhughes** [comment]
- This may have been solved by https://github.com/woocommerce/woocommerce/pull/52199
- Which would make sense given your note, as it was cherry-picked to RC3 in https://github.com/woocommerce/woocommerce/pull/52340 (and so were some other related fixes)

So, I think we can close (will go ahead and do so, but feel free to re-open if I mis-stepped).
