### ISSUE TITLE
[ WP 6.7 Beta 3][TT5] New product block images have wrong aspect ratio

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#52165]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On WP 6.7 Beta 3 running TT5 Theme with sunrise color style, new product block in Cart empty state has the wrong aspect ration for images.
I couldn't reproduce this with other colors and after some testing around it just got fixed by itself. @opr and I reproduced this on 3 places (his setup, my local setup, and a Jurassic ninja setup).

### Expected behavior

Images should have the correct aspect ratio.

![Image](https://github.com/user-attachments/assets/904a99f6-8d37-469a-85ba-e2bf6a74a133)

### Actual behavior

Squshad images 

![Image](https://github.com/user-attachments/assets/5d2e3e9f-1f63-4593-95fc-40673ed72820)

### Steps to reproduce

1. Enable WP 6.7 Beta 3
2. Enable TT5 theme
3. Enable Sunrise color palette
4. Go to Checkout with no products, you should get the empty cart view.

### WordPress Environment

WP 6.7 Beta 3

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by kmanijak** [comment]
The issues is related to all product grids based on AbstractProductGrid: https://github.com/woocommerce/woocommerce/issues/52382. I'm investigating.
