### ISSUE TITLE
[WC Payments NOX] Offline payment methods - API

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#52179]
### Description

Tasks in https://github.com/woocommerce/woocommerce/issues/51444 and https://github.com/woocommerce/woocommerce/issues/52178 require APIs to retrieve and persist Offline payment method settings. This task is extracted out from the UI work so that all the APIs can be worked on in a single task. This is so that the APIs will be coherent as I expect them to be very similar in requirements.

### Acceptance Criteria
- APIs should have the correct permissions checks. Not sure if shop_manager is sufficient or do we need manage_woocommerce? Check existing requirements
- ~APIs for read~ (See comment below for existing API in `window.wp.data.resolveSelect("wc/payment-gateways").getPaymentGateways()`
  - ~There should exist an API which takes one or more payment methods slugs and returns an object with their statuses. These statuses could be 'installed', 'activated', 'enabled'. Not sure if there's prior work on this by Moltres~
  - ~There should exist an API which takes a payment method slug and returns its saved details.~ 
    - Bank Transfer:
      - Enabled: bool 
      - Title: string
      - Description: string
      - Instructions: string
      - Account details: Table - array of Account Name, Account number, Bank name, BSB, IBAN, BIC / Swift
    - Check payments:
      - Enabled: bool
      - Title: string
      - Description: string
      - Instructions: string
    - Cash on delivery:
      - Enabled: bool
      - Title: string
      - Description: string
      - Instructions: string
      - Enable for shipping methods: select shipping methods - combobox that presents shipping methods for selection
      - Accept for virtual orders: bool

- APIs for persistence: input shape same as the above, and it should respond with success/failure as well as the new values for the methods settings

**Comment by chihsuan** [comment]
> There should exist an API which takes one or more payment methods slugs and returns an object with their statuses. These statuses could be 'installed', 'activated', 'enabled'. Not sure if there's prior work on this by Moltres

I think we can reuse existing payment gateways API (e.g `getPaymentGateways` selector) to retrieve the payment methods and their statuses.

> APIs for persistence: input shape same as the above, and it should respond with success/failure as well as the new values for the methods settings

If we only need to toggle the status of a payment gateway, we post ajax with `woocommerce_toggle_gateway_enabled` action.

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/admin/client/settings-payments/components/payment-method.tsx#L41-L52

**Comment by rjchow** [comment]
Thanks @chihsuan ! I'll update the issue

Here's the response from `window.wp.data.resolveSelect("wc/payment-gateways").getPaymentGateways()`

```
{
  "id": "bacs",
  "title": "Direct bank transfer",
  "description": "Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.",
  "order": "",
  "enabled": true,
  "method_title": "Direct bank transfer",
  "method_description": "Take payments in person via BACS. More commonly known as direct bank/wire transfer.",
  "method_supports": [
    "products"
  ],
  "settings": {
    "title": {
      "id": "title",
      "label": "Title",
      "description": "This controls the title which the user sees during checkout.",
      "type": "safe_text",
      "value": "Direct bank transfer",
      "default": "Direct bank transfer",
      "tip": "This controls the title which the user sees during checkout.",
      "placeholder": ""
    },
    "instructions": {
      "id": "instructions",
      "label": "Instructions",
      "description": "Instructions that will be added to the thank you page and emails.",
      "type": "textarea",
      "value": "",
      "default": "",
      "tip": "Instructions that will be added to the thank you page and emails.",
      "placeholder": ""
    }
  },
  "needs_setup": false,
  "post_install_scripts": [],
  "settings_url": "https://wccore-dev.nerd.sg/wp-admin/admin.php?page=wc-settings&tab=checkout&section=bacs",
  "connection_url": null,
  "setup_help_text": null,
  "required_settings_keys": [],
  "_links": {
    "self": [
      {
        "href": "https://wccore-dev.nerd.sg/index.php?rest_route=/wc/v3/payment_gateways/bacs",
        "targetHints": {
          "allow": [
            "GET",
            "POST",
            "PUT",
            "PATCH"
          ]
        }
      }
    ],
    "collection": [
      {
        "href": "https://wccore-dev.nerd.sg/index.php?rest_route=/wc/v3/payment_gateways"
      }
    ]
  }
}

**Comment by rjchow** [comment]
Also it seems that shop_manager is sufficient permissions to execute that

**Comment by ilyasfoo** [comment]
> APIs for persistence: input shape same as the above, and it should respond with success/failure as well as the new values for the methods settings

@rjchow Looking at the [offline gateway screen](https://github.com/user-attachments/assets/13d6438b-80ef-4ece-b497-e67e83acb0c5) for MVP, it seems like we don't need to fetch the new values seems we're only interested in enable/disable state. With the existing API @chihsuan [mentioned](https://github.com/woocommerce/woocommerce/blob/a882acc7e3f419422c6a24657ef547251cf8d65c/plugins/woocommerce/client/admin/client/settings-payments/components/payment-method.tsx#L41-L52), we can already determine to switch the CTA button on individual methods to `Enable` or `Manage` depending on the API response.

I'm thinking we could reuse both fetch & persist APIs at least for MVP, would you agree?

![Image](https://github.com/user-attachments/assets/31514074-8577-4b96-aa2a-12570d6bf72f)

**Comment by rjchow** [comment]
I'm 100% with you 😬 We can close this issue and come back to it later if necessary
