### ISSUE TITLE
[WC Payments NOX] Offline payment methods - List component & Offline payment methods screen

### ISSUE THREAD

**Issue by rjchow** [woothemes/woocommerce#52178]
### Description
Implement the "Offline payment methods" list component which is presented under 'Payment Providers' in the new payments settings screen.

Additionally, also implement the settings page that lists the offline payment methods.

### Acceptance criteria
- Clicking on the list component should bring you to the offline payment methods screen
- Use your discretion to determine whether the offline payments method screen needs its own URL. This decision  should take into consideration how the other payment settings work.
- The offline payments method screen should present the 3 offline payment methods: "Direct bank transfer", "Check payments", "Cash on delivery"
- At this point in time there is no specification for extensibility in this implementation, but you may want to consider some exploration regarding whether there are existing third party plugins that extend this list of offline payments. Feel free to create a separate issue to track progress on this.
- The list should reflect the status of each payment method, and display "Enable" (button - primary variant) if it is not enabled, and "Manage" (button - secondary variant) otherwise
- Clicking on "Enable" should fire a placeholder API request to enable the gateway. If the other task to implement the API endpoints is complete by this time, you may simply use that instead
- Clicking on "Manage" should bring you to the individual payment methods settings screen. Depending on the reply in #51444, this screen may be the old (classic settings) or new (reactified) setting screen.

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

![Image](https://github.com/user-attachments/assets/c5b5cfd9-2dde-472c-99a0-41a775f82e73)
![Image](https://github.com/user-attachments/assets/00a6c65c-5d34-4cb8-8fc2-ac7ea3e4cea6)

### Dev notes
- Referencing pe4Hk0-1zc-p2, as of that article's writing it seems like there is no suitable list component. Do investigate if any progress has been made since then

**Comment by rjchow** [comment]
There’s some scaffolding at https://github.com/woocommerce/woocommerce/pull/52030

**Comment by ilyasfoo** [comment]
> There’s some scaffolding at https://github.com/woocommerce/woocommerce/pull/52030

Note if anyone is picking this up, use the base branch of where the above PR merged to: [add/settings-nox](https://github.com/woocommerce/woocommerce/tree/add/settings-nox). 

For awareness, Moltres is also working on [making changes on the base UI](https://github.com/woocommerce/woocommerce/issues/52113) to follow more closely with Figma

**Comment by ilyasfoo** [comment]
Picking this up

**Comment by ilyasfoo** [comment]
> At this point in time there is no specification for extensibility in this implementation, but you may want to consider some exploration regarding whether there are existing third party plugins that extend this list of offline payments. Feel free to create a separate issue to track progress on this.

@rjchow I don't think WooCommerce core currently has any extensibility regarding offline methods. I'm unsure if it's actually needed too.

**Comment by rjchow** [comment]
Me neither

**Comment by ilyasfoo** [comment]
Closing with a follow-up: https://github.com/woocommerce/woocommerce/issues/52392
