### ISSUE TITLE
Review how dark themes styles impact the checkout and cart experiences

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#52183]
**Description:** some checkout elements don't work well by default when combined with a dark theme. For example, the new Delivery section:

![Image](https://github.com/user-attachments/assets/1b676802-f891-4186-9c49-ca6f3395836a)

This creates usability and readability issues out-box-the-box, which should be avoided as it leads to more friction and can potentially discourage merchants from using the block-based checkout. More info here: p1729105556940669-slack-woosupport

**Acceptance criteria:**

- [ ] Review the cart and checkout blocks to identify additional elements negatively impacted by the dark theme combo.
- [ ] Prioritize and fix the main elements to avoid having these issues by default.

**Comment by pmcpinto** [comment]
This audit made by the WooPay team (Piero) identified elements where the cart and checkout block don't play well together with dark themes: WooPay-Themed-Checkouts-QA-fi

**Comment by senadir** [comment]
This should have been recently fixed (https://github.com/woocommerce/woocommerce/pull/51585) lands in 9.5

@pierorocca can someone test with 9.5 (not yet released, so ideally test from trunk).

**Comment by pierorocca** [comment]
Awesome thanks @senadir. I can retest once I'm able to get my local dev environment back up after replacing my laptop.

@malithsen @leonardola looks like some of the changes in 9.5 could help resolve some of the WooPay theming issues on Blocks.

**Comment by pmcpinto** [comment]
Nadir, thanks. I wasn't aware of that PR. I'll close this issue.
