### ISSUE TITLE
Overlapping settings in 'edit product' screen

### ISSUE THREAD

**Issue by mfwildenberg** [woothemes/woocommerce#52185]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,

I've noticed something strange in the 'edit product' screen. Since 2 days some of the setting sections (such as 'settings' and 'product information' are overlapping the sections in the 2nd column (such as product image). 

### Expected behavior

Normally the 'settings' 'Order of products' ' productinformation' and 'short product description' are shown under the 'product description' section. All in the first column. And the second column shows for example the product image.

### Actual behavior

Some of the setting sections (such as 'settings' and 'product information' are overlapping the sections in the 2nd column (such as product image). 

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/0ee0efce-d543-40f1-9aa6-57235568275e)

### WordPress Environment

[SystemStatusReport_geheugenhulp.nl_2024-10-21T09-23-29.txt](https://github.com/user-attachments/files/17458465/SystemStatusReport_geheugenhulp.nl_2024-10-21T09-23-29.txt)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by Ayax2** [comment]
Have the same problem for two weeks in more than 10 websites. i think it's  a Wordpress error and not the woocommerce.

**Comment by louwie17** [comment]
@mfwildenberg are you using Safari by chance as your browser? This appears to be a Safari specific issue, see related issues: https://github.com/woocommerce/woocommerce/issues/51684
We do have a fix in place for WooCommerce with the new release, but there is also some work arounds for the time being:
- Switching to a single layout under **Screen options > layout**
- Using another browser like Chrome of Firefox
