### ISSUE TITLE
Improve email logo settings

### ISSUE THREAD

**Issue by NeosinneR** [woothemes/woocommerce#52217]
**Behind** the experimental flag from #52212.

- Please also check [Figma file](https://href.li/?https://www.figma.com/design/FAA2sMXXfT8Qs40AC3V1gL/WC-Core-Emails?node-id=594-7764) for more details and different states. 
- Replace email template description: `Customize your WooCommerce email template and preview it below.`
- Replace the logo text field with a more interactive component:
  - Show chosen logo.
  - When the logo is set:
    - Add the `Change image` button, which opens the Media library.
    - Add the `Remove` button, which removes the logo.
  - Tooltip text: `Add your logo to each of your WooCommerce emails. If no logo is uploaded, your site title will be used instead.`
  - The functionality should stay the same - the full URL is saved in the database and used in email.
- Add `Header alignment` setting:
  - Options: `Left`, `Center`, `Right` (default to `Left`)
  - Tooltip text: none
  - Update the email template to align the logo, **main title, and header text** based on this setting.
    - When the option is not set, default to `left`. 

![Image](https://github.com/user-attachments/assets/7239464a-5041-4074-ba66-ab3ba87d8952)

**Comment by alex-mpoet** [comment]
@NeosinneR A few questions:
1. Couldn't find this in Figma. What would the state look like when the logo isn't chosen yet? Like it is now, a simple text iput? So you can only use the Media library when you have already saved an initial URL?
2. How to specify an externally hosted image in the new UI? Should we still have a text input maybe? 
3. If an externally hosted image is specified, can it be unsafe or against GDPR to display it (e.g. tracking of the admin user is possible via the image)? Or since if comes from authorized users we can assume good intent?

**Comment by NeosinneR** [comment]
1. I can't find it in Figma either now, but there is an RFC Proposal (FAA2sMXXfT8Qs40AC3V1gL-fi-75_1596), which includes the empty state, so I think we can use that one. Clicking on the whole box would open the Media library. 

![Image](https://github.com/user-attachments/assets/3b7aecf7-6290-4073-a2e1-00b518ab0ba7)

2. I think it's okay not to allow external URLs. This shouldn't break existing websites, as you'll see the external logo in settings, and it will continue to be used in emails, but all new logos will need to be uploaded to the website. If this turns out to be an issue, we can always allow text input in the future.
3. In this case, I think it's safe to assume the good intent.

**Comment by NeosinneR** [comment]
@alex-mpoet, we have a final, proofread copy for the Logo tooltip (`Add your logo to each of your WooCommerce emails. If no logo is uploaded, your site title will be used instead.`). The Header alignment won't have any tooltip. Is there still time to update the PR with the final copy, or should I create a new issue? I'll update this issue description based on what works for you.

**Comment by alex-mpoet** [comment]
@NeosinneR It's fine to update the current issue with the final copy.

**Comment by NeosinneR** [comment]
@alex-mpoet done

**Comment by alex-mpoet** [comment]
@NeosinneR The copy promises something we don't have yet:

> Add your logo to each of your WooCommerce emails. If no logo is uploaded, your site title will be used instead.

Currently it's either a logo or nothing, will this be changed in the future to actually use site title in place of a logo?

**Comment by NeosinneR** [comment]
> will this be changed in the future to actually use site title in place of a logo

@alex-mpoet yes, with modernized email styles, we'll also default to the site title when the logo is not set (pfrEX1-t4-p2 - see `Defaults for non-block themes` section)
