### ISSUE TITLE
Add email preview when managing specific email

### ISSUE THREAD

**Issue by NeosinneR** [woothemes/woocommerce#52293]
Figma file: FAA2sMXXfT8Qs40AC3V1gL-fi-598_12825

1. Add a new section when managing specific email
    1. Copy 
        - Title: `Email preview`
        - Description: `Preview your email template. You can also test on different devices and send yourself a test email.`
    2. Show email preview component
        - Don't allow changing email type - only show the one the user is editing
        - Show current email subject
        - For now, ignore previewing live changes in the settings above the email preview - will be added later

**Comment by alex-mpoet** [comment]
@NeosinneR I see some changes in Figma not mentioned in this issue, including added subheadings and reordered fields, e.g. "Email type" is placed after "Enable / Disable". Do we need to implement this now? Field ordering can be set differently for each specific email. Right now it is defined in each of these classes:
```
class-wc-email.php
class-wc-email-cancelled-order.php
class-wc-email-customer-invoice.php
class-wc-email-customer-refunded-order.php
class-wc-email-failed-order.php
class-wc-email-new-order.php
```
Therefore we need to change all the above emails so the order matches the design. Extensions can have their own order too. If we don't do it now, the preview component will be placed between "Email type" and "HTML/plain template" settings. Or it can be put after "HTML/plain template". Shall we reorder?
