### ISSUE TITLE
404 error on Woo readme.txt page

### ISSUE THREAD

**Issue by alanjacobmathew** [woothemes/woocommerce#52306]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There is an link in the wordpress.org home page that redirects to a 404 page.
Speed up development with a lightning-fast [CLI](https://woocommerce.github.io/code-reference/classes/wc-cli-rest-command.html?utm_medium=referral&utm_source=wordpress.org&utm_campaign=wp_org_repo_listing).

### Expected behavior

Page is supposed to lead the user to https://woocommerce.github.io/code-reference/classes/WC-CLI-REST-Command.html

### Actual behavior

404 error

### Steps to reproduce

Readme.txt error 
* Open wordpress.org page.
* Click on that link

### WordPress Environment

Readme.txt Error

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
- Resolved via https://github.com/woocommerce/woocommerce/pull/52351.
- We chose a different documentation link, but of course we could adjust a second time if necessary.
