### ISSUE TITLE
[WC Payments NOX] Recommended payment methods list UI

### ISSUE THREAD

**Issue by mordeth** [woothemes/woocommerce#52330]
### Description

This issue focuses on implementing the user interface for the recommended payment methods settings list within the WooCommerce Payments NOX onboarding process.

### Acceptance criteria
- The page displays all Local Payment Methods (LPMs) and Buy Now, Pay Later (BNPL) options that are enabled by default.
- A Show More button is located at the bottom of the enabled LPMs list.
- When the Show More button is clicked, all available LPMs are revealed.
- Each LPM can be toggled on or off, except for the mandatory Credit/Debit Card option, which remains enabled by default.

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Dev notes
Reactifying the Payments settings page: pe4Hk0-1ly-p2
Populate react-powered main payments settings screen PR: https://github.com/woocommerce/woocommerce/pull/50825

### Additional context
PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

**Comment by vladolaru** [comment]
I've merged [this PR](https://github.com/woocommerce/woocommerce/pull/53380) to provide real recommended PMs data through the GET providers API endpoint.
