### ISSUE TITLE
Mobile app task is not marked as complete after clicking the dismiss button.

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#52366]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

https://github.com/user-attachments/assets/51b3eaa1-9076-4fc4-ac2c-283830b9e50a

### Expected behavior

Mobile app task should be marked as complete after clicking the dismiss button.

### Actual behavior

Mobile app task is not marked as complete after clicking the dismiss button.

### Steps to reproduce

1. Create a fresh site
2. Go to `WooCommerce > Home`
3. Click on the `Mobile app` task
4. Click on the `Dismiss` button

### WordPress Environment

n/a

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rjchow** [comment]
I think it's marked complete after a refresh, so probably needs a @wp/data cache invalidation
