### ISSUE TITLE
[Fatal] PHP Fatal error:  Uncaught Error: Call to a member function get_image() on string | wc-template-functions.php:1470

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#52375]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.3.3

[Link to code](https://github.com/woocommerce/woocommerce/blob/e66ab452634da522af668779bf98cd1a8adbe354/plugins/woocommerce/includes/wc-template-functions.php#L1470)

```
PHP Fatal error:  Uncaught Error: Call to a member function get_image() on string in /../plugins/woocommerce/9.3.3/includes/wc-template-functions.php:1470
Stack trace:
#0 /srv/htdocs/wp-content/themes/astra/inc/compatibility/woocommerce/class-astra-woocommerce.php(3752): woocommerce_get_product_thumbnail()
#1 /../core/6.6.2/wp-includes/class-wp-hook.php(324): Astra_Woocommerce->single_product_sticky_add_to_cart('')
#2 /../core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /../core/6.6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /../core/6.6.2/wp-includes/general-template.php(3081): do_action('wp_footer')
#5 /../core/6.6.2/wp-includes/template-canvas.php(25): wp_footer()
#6 /../plugins/woocommerce/9.3.3/src/Internal/ComingSoon/ComingSoonRequestHandler.php(81): include('/../core...')
#7 /../core/6.6.2/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\ComingSoon\ComingSoonRequestHandler->handle_template_include('/srv/htdocs/wp-...')
#8 /../core/6.6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters('/srv/htdocs/wp-...', Array)
#9 /../core/6.6.2/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/srv/htdocs/wp-...')
#10 /../core/6.6.2/wp-blog-header.php(19): require_once('/../core...')
#11 /../core/6.6.2/index.php(17): require('/../core...')
#12 {main}
  thrown in /../plugins/woocommerce/9.3.3/includes/wc-template-functions.php on line 1470
``` 

### Expected behavior

No fatal errors when attempting to call $product->get_image( $image_size, $attr, $placeholder )

### Actual behavior

Fatal errors when attempting to call $product->get_image( $image_size, $attr, $placeholder )

### Steps to reproduce

We don't have steps to reproduce, but we observed 3819 instances of this problem on Mon Oct 28, 0800 UTC to 1100 UTC across 1 site.

Related discussion p1730106683736129-slack-C01DT6U03HC

Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi, to narrow down the issue, could you please confirm if the issue is specific to the Astra theme (which I see referenced in the stack trace)?

**Comment by nigeljamesstevenson** [comment]
Thanks for taking a look @Konamiman !

Looking at the same timeframe, we can see one other instance of a different site encountering the same issue and referencing the same astra theme

However, later in the day, the following trace appears at a much lower volume for another site but not referencing the astra theme:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_image() on string in /../plugins/woocommerce/9.3.3/includes/wc-template-functions.php:1470
Stack trace:
#0 /../wp-content/plugins/kadence-pro/dist/woocommerce-addons/hooks.php(136): woocommerce_get_product_thumbnail()
#1 /../core/6.6.2/wp-includes/class-wp-hook.php(324): Kadence_Pro\single_product_sticky_add_to_cart('')
#2 /../core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /../core/6.6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /../core/6.6.2/wp-includes/general-template.php(3081): do_action('wp_footer')
#5 /../core/6.6.2/wp-includes/template-canvas.php(25): wp_footer()
#6 /../plugins/woocommerce/9.3.3/src/Internal/ComingSoon/ComingSoonRequestHandler.php(81): include('/../core...')
#7 /../core/6.6.2/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\ComingSoon\ComingSoonRequestHandler->handle_template_include('/../wp-...')
#8 /../core/6.6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters('/../wp-...', Array)
#9 /../core/6.6.2/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/../wp-...')
#10 /../core/6.6.2/wp-blog-header.php(19): require_once('/../core...')
#11 /../core/6.6.2/index.php(17): require('/../core...')
#12 {main}
  thrown in /../plugins/woocommerce/9.3.3/includes/wc-template-functions.php on line 1470
```

**Comment by barryhughes** [comment]
Even if the origin of the problem is Astra, Kadence, or another theme, it does seem like we could be a bit stricter within `woocommerce_get_product_thumbnail()`.

```php
return $product ? $product->get_image( $image_size, $attr, $placeholder ) : '';
```

We're guarding against 'empty'/falsey values, but we could actually check to ensure we are working with a `WC_Product`.

**Comment by Konamiman** [comment]
I see 10 instances of `global $product;` only in `wc-template-functions.php`. In all cases either the global product object is passed to a filter, or some operation is performed on it assuming that it's a `WC_Product` (without even checking if it's null).

There's another usage in `WC_Structured_Data` and one more in `WC_Report_Stock`. The former does the right thing:

```php
if ( ! is_a( $product, 'WC_Product' ) ) {
	return;
}
```

So if we want to add some robustness to the code, maybe we should do the same in all the cases.
