### ISSUE TITLE
Emoji in Order Notes Causes Order Update Failure

### ISSUE THREAD

**Issue by jan-embite** [woothemes/woocommerce#52378]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a customer adds an emoji in the order notes field, the order fails to update correctly. This issue causes WooCommerce to throw an error, preventing the order from being saved or modified.

### Expected behavior

The order should update successfully even when the order notes field contains an emoji.

### Actual behavior

When an emoji is present in the order notes field, WooCommerce is unable to process the update, resulting in an error. The order remains unmodified and the update attempt fails.

### Steps to reproduce

1. Go to the WooCommerce Orders page in the WordPress admin.
2. Select an order to edit.
3. In the order notes field, add an emoji (e.g., 😊, ❤️).
4. Click "Update" to save the order.
5. Order could not be updated.

### WordPress Environment

-

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by 07lodgeT** [comment]
Cannot reproduce on Storefront on latest release or other themes
