### ISSUE TITLE
Product SKU looks different than Category and Tags in Single Product template

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#52396]
**Steps to reproduce:**

1. Go to Editor > Single Product template
2. Reset customizations if you've applied any changes

Expected: Product SKU, categories and tags should looks similar as they're used in the same context/way
Actual: Products SKU stands out: font size is bigger and "Suffix" placeholder is present no matter if block is focused or not

![Image](https://github.com/user-attachments/assets/f939f138-24cd-462e-9808-f058fdd84fa8)

For Product Categories and Tags "Suffix" appears only when block is focused:

![Image](https://github.com/user-attachments/assets/43c17557-479c-4d6f-87f9-14278e24d9c4)

**Comment by gersipanci** [comment]
@kmanijak I'm on WP 6.6.2 and WC 9.3.3 and it looks and acts a bit different now:

Nothing selected:
![Image](https://github.com/user-attachments/assets/89e070e4-6b73-43b1-83d0-245be5ac49fd)

Product selected:
![Image](https://github.com/user-attachments/assets/a31f0f30-c2aa-46ad-9c1d-dc2ab7903e9c)

Category selected:
![Image](https://github.com/user-attachments/assets/1adfac63-b845-48c9-9210-59ae95a64d67)

I think it's to make the difference clearer from SKU to Category and Tags
