### ISSUE TITLE
Coming soon shared social blocks

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#52397]
### Issue Description

P2: pfwcF5-13s-p2

Social blocks are reused in multiple templates. We need to move out the social block as a reusable block and apply them where necessary.

| ![Image](https://github.com/user-attachments/assets/6c08a5d0-0886-4f6d-84e3-dc918c94a6cc)  |    ![Image](https://github.com/user-attachments/assets/d2f57463-d2a7-49a4-beb4-2bd98d5356e0)       |
|----------|----------|
| ![Image](https://github.com/user-attachments/assets/9a24d533-0d63-4b1f-a8ed-3ec7253e56e3)   | ![Image](https://github.com/user-attachments/assets/ce8b824c-c6d4-48a1-b1ff-50451c3c4721)   |

### Acceptance Criteria

1. Extract social UI components with from entire site coming soon template into an independant block

**Comment by chihsuan** [comment]
Hey @ilyasfoo, I tried to extract the social block as a reusable block, but I think it may not be helpful to solve the issue.

Extracting it as a reusable block does help when we insert it using block inserter but does not help when we build the template. We still have duplicate code for each template. For example:

```html
<!-- woocommerce/social-links {"iconColorValue":"#ff0000","iconBackgroundColorValue":"#eeeeee"} -->
<div class="my-social-links-wrapper" style="--icon-color:#ff0000;--background-color:#eeeeee;">
    <ul class="wp-block-social-links has-icon-color is-style-logos-only">
        <!-- wp:social-link {"url":"https://www.linkedin.com","service":"linkedin"} /-->
        <!-- wp:social-link {"url":"https://www.instagram.com","service":"instagram"} /-->
        <!-- wp:social-link {"url":"https://www.facebook.com","service":"facebook"} /-->
    </ul>
</div>
<!-- /woocommerce/social-links -->
```



I wonder if what we need is to extract it as a pattern instead so we can just use the pattern in each template?

```html
<!-- wp:pattern {"slug":"woocommerce/social-links","attributes":{"iconColorValue":"#ff0000","iconBackgroundColorValue":"#eeeeee"}} /-->
```

**Comment by ilyasfoo** [comment]
Sounds like a better solution, thanks for looking into it deeper @chihsuan !
