### ISSUE TITLE
[Enhancement]: Support request mails removes previous discussions

### ISSUE THREAD

**Issue by betayazilim** [woothemes/woocommerce#52407]
### Describe the solution you'd like

Hi there,

I create support tickets through woocommerce.com or by support@woocommerce.com mail.

When I got reply, my original message is deleted, so I can't understand what issues I covered after few mails.
So, I keep explaining again and again.

I raised this issue few times by mail but no update.

It is not that difficult to keep whole conversations in the mail, right?

**Comment by rodelgc** [comment]
Hi @ned-bs apologies but I think I'm quite confused with this enhancement request. 

> When I got reply, my original message is deleted, so I can't understand what issues I covered after few mails.
So, I keep explaining again and again.

It sounds to me that your previous conversations are being deleted in your mail, so I guess that's a problem with your mail, whichever email service or client you're using, and not on the WooCommerce plugin itself?

**Comment by betayazilim** [comment]
Hi,

Let's go step by step.

1. Please send an email to support@woocommerce.com
2. AI will reply to you, but you will not see your original question under that reply.
3. You have to go your mail client's sent folder to check what you have asked.
4. Then a person will reply to you. again you will not see your original message under that reply.
5. You reply the person with additional information.
6. Then a person will reply to you. and You WILL NOT see any of your previous messages.

Now
 you have to go your sent folder find these 2 mails to check what you discussed before.

**Comment by lanej0** [comment]
Hi @ned-bs,

I think your enhancement is best sent on to the folks at woocommerce.com -- this repository is for the open source WooCommerce plugin, so the support channels you're describing aren't part of it.
