### ISSUE TITLE
Woocommerce variable product error

### ISSUE THREAD

**Issue by developershohel** [woothemes/woocommerce#52401]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

```
JQMIGRATE: Migrate is installed, version 3.4.1
wp-util.min.js?ver=6.6.2:2 Uncaught TypeError: _.memoize is not a function
    at wp-util.min.js?ver=6.6.2:2:112
    at wp-util.min.js?ver=6.6.2:2:1383Understand this errorAI
add-to-cart-variation.min.js?ver=9.3.3:1 Uncaught TypeError: wp.template is not a function
    at o (add-to-cart-variation.min.js?ver=9.3.3:1:13552)
    at HTMLFormElement.<anonymous> (add-to-cart-variation.min.js?ver=9.3.3:1:5986)
    at HTMLFormElement.dispatch (jquery.min.js?ver=3.7.1:2:40035)
    at HTMLFormElement.<anonymous> (jquery.min.js?ver=3.7.1:2:38006)
    at Object.trigger (jquery.min.js?ver=3.7.1:2:70124)
    at HTMLFormElement.<anonymous> (jquery.min.js?ver=3.7.1:2:70726)
    at Function.each (jquery.min.js?ver=3.7.1:2:3129)
    at ce.each (jquery.min.js?ver=3.7.1:2:1594)
    at ce.trigger (jquery.min.js?ver=3.7.1:2:70701)
    at HTMLFormElement.<anonymous> (add-to-cart-variation.min.js?ver=9.3.3:1:4989)
o @ add-to-cart-variation.min.js?ver=9.3.3:1
(anonymous) @ add-to-cart-variation.min.js?ver=9.3.3:1
dispatch @ jquery.min.js?ver=3.7.1:2
(anonymous) @ jquery.min.js?ver=3.7.1:2
trigger @ jquery.min.js?ver=3.7.1:2
(anonymous) @ jquery.min.js?ver=3.7.1:2
each @ jquery.min.js?ver=3.7.1:2
each @ jquery.min.js?ver=3.7.1:2
trigger @ jquery.min.js?ver=3.7.1:2
(anonymous) @ add-to-cart-variation.min.js?ver=9.3.3:1
dispatch @ jquery.min.js?ver=3.7.1:2
(anonymous) @ jquery.min.js?ver=3.7.1:2
trigger @ jquery.min.js?ver=3.7.1:2
(anonymous) @ jquery.min.js?ver=3.7.1:2
each @ jquery.min.js?ver=3.7.1:2
each @ jquery.min.js?ver=3.7.1:2
trigger @ jquery.min.js?ver=3.7.1:2
(anonymous) @ add-to-cart-variation.min.js?ver=9.3.3:1
dispatch @ jquery.min.js?ver=3.7.1:2
(anonymous) @ jquery.min.js?ver=3.7.1:2Understand this error
```

### Expected behavior

I am using latest wordpress and woocommerce plugin and get this error

### Actual behavior

When i change the variable product variation then i get the errro

### Steps to reproduce

on change

### WordPress Environment

<html>
<body>

WordPress address (URL): |   | https://vmsuniverse.com
-- | -- | --
Site address (URL): |   | https://vmsuniverse.com
WooCommerce version: |   | 9.3.3
WooCommerce Legacy REST API package: |   | The Legacy REST API plugin is not installed on this site.
Action Scheduler package: |   | 3.8.1 wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable: |   | wp-content/uploads/wc-logs/
WordPress version: |   | 6.6.2
WordPress multisite: |   | –
WordPress memory limit: |   | 3 GB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

</body>
</html>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
I’m unable to successfully reproduce the bug. This doesn’t mean there isn’t something happening, but it appears to be specific to your environment. Until we can reproduce this, there isn’t anything we can do to fix. For that reason, I’m going to close this issue, but please do leave a comment if you have additional information that you think will help us reproduce the issue. We will re-open if we’re able to replicate.

Thanks again for your report!
