### ISSUE TITLE
Allow resetting/resyncing color palette

### ISSUE THREAD

**Issue by NeosinneR** [woothemes/woocommerce#52421]
**Behind** the experimental flag from #52212.

![Image](https://github.com/user-attachments/assets/bcbcfb81-ea07-4f13-b0f3-dff0fb40a905)

Figma file: FAA2sMXXfT8Qs40AC3V1gL-fi-597_10797

1. Add a button next to the `Color palette`
    1. Text: for themes with theme.json it's `Sync with theme`, otherwise `Reset`
    2. Variant: `secondary`
    3. On click:
        - Change the color palette inputs to values from theme.json or default hardcoded ones.
2. When _all_ values are the same as default ones, the button should be replaced with the text:
    - theme.json - `Synced with theme`
    - without theme.json - `Using default values.`
3. Show `Undo button` next to it:
    - Variant: `secondary`
    - When clicked, undo all local (not saved) changes, but only in color palette values
    - This button should only be visible when there are some local changes done to color palette and should disappear when the values are the same as the ones saved in database.

**Comment by alex-mpoet** [comment]
@NeosinneR I have a few questions:
1. Should clicking the blue modal buttons reset colors in the DB or just in the input fields, requiring manual saving afterwards? The latter way seems safer and more flexible to me, but the copy doesn't quite match it.
2. Should the "Reset" and "Resync" buttons be displayed if the values are set to defaults already?
3. Related to the previous one. How are conditions for displaying the red notice different from other conditions requiring resyncing? Looks like the red notice will be always displayed if the values aren't set to defaults.

**Comment by NeosinneR** [comment]
@alex-mpoet great questions. As I don't think there is a simple answer, I surfaced this in Slack (p1732872134661969-slack-C07LQ9WS38S) to get opinions from product and design people.

**Comment by NeosinneR** [comment]
@alex-mpoet The issue description has been updated with the new approach. Thanks for surfacing it!
