### ISSUE TITLE
Add to Cart Form - Stepper Layout: Layout broken with extensions

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#52488]
![Image](https://github.com/user-attachments/assets/9f9cf4ff-7eb9-416e-b788-e9b7dbab6e99)

https://github.com/woocommerce/woocommerce/blob/90b87702570960083e28236d390ea01b28f7fd87/plugins/woocommerce-blocks/assets/js/blocks/product-elements/add-to-cart-form/style.scss#L31-L36

The recent addition of the flexbox rule to the form element has caused most extensions to stack in a column, disrupting the expected layout. This unintended behavior needs to be addressed to restore the original design.

**Comment by helgatheviking** [comment]
The easiest way to ensure the quantity stepper + add to cart ARE in a flex alignment would be to wrap them in their own div element

**Comment by gigitux** [comment]
Thanks for the feedback, but we are aiming to not change too much the HTML structure.

**Comment by helgatheviking** [comment]
That makes sense. I'm just thinking that a wrapper div is more reliable than css `.not` exclusions 

```
form.cart {
		&:not(.grouped_form):not(.variations_form) 
``

and would work across all product types
