### ISSUE TITLE
[Enhancement]: Inconsistent coupon behavior when coupon value changes after application but before checkout

### ISSUE THREAD

**Issue by Stojdza** [woothemes/woocommerce#52494]
### Describe the solution you'd like

When a shopper applies a coupon to their cart but does not immediately complete the order, and the merchant changes the coupon’s value, the updated coupon value is unexpectedly applied during checkout. This behavior could lead to shopper confusion or potential pricing discrepancies, as shoppers expect the value of the applied coupon to remain the same. Ideally, WooCommerce should either retain the initially applied coupon value or alert shoppers to reapply the coupon if its value has changed.

Steps:
- As a merchant, create a coupon (e.g. XYZ) with a specific discount value
- As a shopper, add items to the cart
- Go to the cart page, apply the XYZ coupon (but do not proceed to checkout)
- As a merchant, update the XYZ coupon’s discount value
- As a shopper, complete the checkout process with the coupon still applied
Result: The new (updated) coupon value is applied at checkout without notifying the shopper of the change.

### Describe alternatives you've considered

From a shopper perspective, it would be more clear if:
- Retain the initially applied coupon value for the shopper until checkout is complete, or
- Display a message alerting the shopper that the coupon has changed and needs to be reapplied to reflect the current value

**Comment by senadir** [comment]
Given the little chances of this happening, I don't think it's a high priority, but for a more generic solution, we're going to implement this https://github.com/woocommerce/woocommerce/issues/52663 which should alert the shopper if totals changed.

I'm going to close this in favor of that one.
