### ISSUE TITLE
[Enhancement]: Parameter type hints

### ISSUE THREAD

**Issue by Maikuolan** [woothemes/woocommerce#52502]
I was thinking, it *would* be *possible* to refactor and modernise some of the codebase and enforce stricter parameter typing by utilising parameter type hints, which would, in turn, allow simplification of some of the checks and code guards elsewhere in some cases. As an example, changing [this](https://github.com/woocommerce/woocommerce/blob/148e3b9295a54f65d1efbec9b5131a68b7aced3d/plugins/woocommerce/includes/wc-formatting-functions.php#L1062C13-L1064C2):

```PHP
/**
 * Sanitize phone number.
 * Allows only numbers and "+" (plus sign).
 *
 * @since 3.6.0
 * @param string $phone Phone number.
 * @return string
 */
function wc_sanitize_phone_number( $phone ) {
	return preg_replace( '/[^\d+]/', '', $phone ?? '' );
}
```

To this:

```PHP
/**
 * Sanitize phone number.
 * Allows only numbers and "+" (plus sign).
 *
 * @since 3.6.0
 * @param string $phone Phone number.
 * @return string
 */
function wc_sanitize_phone_number( string $phone ) {
	return preg_replace( '/[^\d+]/', '', $phone );
}
```

(In the example, hinting that `$phone` should be a `string` means PHP would enforce the parameter type strictly, and attempt to coerce any supplied non-string value to a string, thus allowing us to omit the formerly necessary null check).

I was considering attempting a pull request to implement this, but noticing that it doesn't seem to have been implemented anywhere in WooCommerce yet AFAICT, and not finding any similar issues, pull requests, or discussions on the subject when searching the issue tracker for WooCommerce here at GitHub, I figured it might be worth creating an issue here on the subject myself, to ask for maintainers' opinions. Has this idea already been floated before, rejected, and I simply didn't do a very good job when searching for related issues/PRs/discussions before? Is it perhaps a worthwhile idea, or are there reasons why it would be a bad idea which I haven't considered yet, or mightn't be aware of? (Maybe it wouldn't necessarily be considered *bad*, per se, but would perhaps simply be considered as unnecessary and not worth maintainers' time to bother about, considering limited time and the numerous other things already on the to-do list and various other works-in-progress)?

As parameter type hints were *[introduced with PHP 7.0](https://www.php.net/manual/en/migration70.new-features.php)*, using them wouldn't have been possible until more recent major versions of WooCommerce, where the minimum PHP version requirement was increased. As the minimum PHP version requirement for the current latest versions of WooCommerce is PHP 7.4, backwards compatibility shouldn't be a concern here.

The biggest downside I see to it is that, if it were to be implemented, it would likely need to take place in stages, slowly, over time, across multiple pull requests, in order to avoid/reduce the likelihood of merge conflicts appearing, because although the individual changes in any affected file are likely to be small, said changes would likely affect a large number of files overall, and trying to do the whole lot in a single pull request is pretty much guaranteed to either (1) cause merge conflicts in other pull requests, due to the number of open pull requests here at any given time and the regularity of new commits appearing at the monorepo here (a regularity which is a fantastic thing, of course), or (2) cause said singular pull request to pretty much never be mergable itself (i.e., holding it back in order to avoid causing the aforementioned merge conflicts, but in turn, causing merge conflicts to appear for said singular pull request due to other things being merged and such). The easiest way to avoid both outcomes, of course, would be to split it up into multiple, smaller pull requests, across stages.

Anyway, figure it would be worth asking before attempting any pull requests on this, as I see it as the kind of thing where opinions could swing either way: Either as it being a good/useful idea, or as being something unwanted/unnecessary, where reviewing such pull requests occupies time which could be better spent reviewing other, already existing pull requests and such. I'm happy to contribute, and would be happy to work on this if it's seen as a good/useful idea, but it's just an idea that I had on a whim, so no stress at all if related to the unwanted/unnecessary side of the fence. :-)

**Comment by coreymckrill** [comment]
Hi @Maikuolan, thanks for bringing this up. We do have type hinting in some parts of the codebase (newer parts, mostly), and we do have the expectation that all new code going forward should use parameter type hints as well as return type hints where possible. However, going through and adding hints to old parts of the codebase is generally not palatable because it would potentially break backcompatibility for extensions and other third party custom code that use those functions.
