### ISSUE TITLE
[Enhancement]: Revisit Allow the removal of the "WooCommerce knowledge base" blog feed Coupons screen

### ISSUE THREAD

**Issue by TimBHowe** [woothemes/woocommerce#52511]
### Describe the solution you'd like

Originally asked for this feature here: https://github.com/woocommerce/woocommerce/issues/31430

The issue was close as a duplicate
https://github.com/woocommerce/woocommerce/issues/31430#issuecomment-1824818533

In the duplicate issue here https://github.com/woocommerce/woocommerce/issues/31462

They closed it saying "Closing this as the marketing screen has been refactored."
https://github.com/woocommerce/woocommerce/issues/31462#issuecomment-1824817046

It doesn't seem like a clear answer was given so I'm "Create a new issue with details of the current implementation."

- Will this be a future option?
- If so, What is the timeline for this?

Any information is appreciated.
Thanks 

#### Information

The "WooCommerce knowledge base" displays on the Marketing and Coupon Section of sites regardless of if you want the information or not.

This is making asset request to the https://woocommerce.com/ site for the blog feed for post and on the Coupon Screen post with the 'coupons' tag.

This still appears even when the WooCommerce > Settings > Advanced > WooCommerce.com setting for the Usage Tracking and Marketplace suggestions.

There appears to not be a back-end setting to remove this external blog feed from the backend of the site.

### Describe alternatives you've considered

Looked at dequeue the following
`add_action( 'admin_enqueue_scripts', array( $this, 'maybe_add_marketing_coupon_script' ) );`

Add a check to this function

```php
/**
 * Return installed marketing extensions data.
 *
 * @param \WP_REST_Request $request Request data.
 *
 * @return \WP_Error|\WP_REST_Response
 */
public function get_knowledge_base_posts( $request ) {
	$category = $request->get_param( 'category' );
	return rest_ensure_response( MarketingFeature::get_instance()->get_knowledge_base_posts( $category ) );
}
```

**Comment by ecgan** [comment]
Hi @TimBHowe , thanks for raising this issue. 

> This still appears even when the WooCommerce > Settings > Advanced > WooCommerce.com setting for the Usage Tracking and Marketplace suggestions.

We have merged a PR https://github.com/woocommerce/woocommerce/pull/52715 that will not display the knowledge base card when the "Marketplace suggestions" settings is turned off. This should be in the next WooCommerce release. We hope that works for you.

**Comment by TimBHowe** [comment]
Hi @ecgan, This looks great.
Thanks you and @rawdreeg for the patch and reply. 
I look forward to seeing this in the next release.
