### ISSUE TITLE
[Enhancement]: Replace Cart Cross-Sells block with Cross-Sells collection block

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#52561]
### Describe the solution you'd like

In #52068, @octaedro introduced the Cross-Sells Collection block, which provides enhanced customisation options compared to our current Cart Cross-Sells block within the Cart block. To streamline our development and ensure consistency across our platform, I propose we replace the Cart Cross-Sells block with the Cross-Sells Collection block. This change will not only help us avoid duplicative efforts, but also improve our site's performance by reducing code redundancy and simplifying maintenance. Additionally, having one block in various sections, rather than multiple similar blocks, offering slightly different customisation options, will provide a more unified and intuitive user experience.

> [!NOTE]
> The Cross-Sells Collection block currently requires manual product selection to display cross-sell products. For seamless integration within the Cart block, it should be configured to automatically fetch cross-sell products based on the items present in the cart.

## [Cart Cross-Sells block](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/cart-cross-sells-block/edit.tsx)

![Image](https://github.com/user-attachments/assets/1f2a6547-c371-46c8-b03f-29f29cb12d9e)

## [Cross-Sells Collection block](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/blocks/product-collection/collections/cross-sells.tsx)

![Image](https://github.com/user-attachments/assets/fb4abf6f-5a16-4122-9221-d42fc769777d)

**Comment by ralucaStan** [comment]
> The Cross-Sells Collection block currently requires manual product selection to display cross-sell products. 

For this reason I think it makes sense to discuss how the replacement will happen. 
Current users of the block should still be able to use it; 
Merchants looking to add cross-sells to the Cart Block should no longer see the current block, but the new Product Collection variation. This would allow them to configure it.

This would mean a soft-deprecation of the current block, and a full deprecation should follow. 

> For seamless integration within the Cart block, it should be configured to automatically fetch cross-sell products based on the items present in the cart.

@nielslange is there a ticket created for this feature of the Product collection variation?

**Comment by nielslange** [comment]
> For this reason I think it makes sense to discuss how the replacement will happen.
> Current users of the block should still be able to use it;
> Merchants looking to add cross-sells to the Cart Block should no longer see the current block, but the new Product Collection variation. This would allow them to configure it.
> 
> This would mean a soft-deprecation of the current block, and a full deprecation should follow.

Absolutely. My primary intention of creating this issue, was to keep track of it.

> @nielslange is there a ticket created for this feature of the Product collection variation?

I haven't created a separate ticket for that, as such a feature cannot be tested in isolation, but only when used in combination with a parent block that contains products. I saw such a feature as part of this ticket.

**Comment by pmcpinto** [comment]
@ralucaStan this should be merged with #52589, right?

**Comment by ralucaStan** [comment]
Good catch. We can keep #52589, but there were some concerns about just replacing the blocks in this comment https://github.com/woocommerce/woocommerce/issues/52589#issuecomment-2478579389. 

I will close this one, let's keep the discussion going on that ticket and decide the next steps there.
