### ISSUE TITLE
Store core profiler progress state

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#52565]
## Issue Description

At present, it's generally possible to infer the core profiler progress from the `woocommerce_onboarding_profile` option, except in case when the user has completed the intro screen only. In this scenario, the option is still empty and therefore it is ambiguous whether the user has seen the intro screen or not.

This issue is to allow the core profiler progress to be determined explicitly. This will enable us to:

* Accurately default to opting-in to tracking when core profiler intro screen is shown for first time. See https://github.com/woocommerce/woocommerce/pull/52525#issuecomment-2456118449
* Lay foundations to provide an "auto-resume" feature in the core profiler -- that is re-displaying the core profiler in subsequent user sessions when it has only been partially completed.

## Acceptance Criteria

Todo: decide whether this data should be contained in a single option or spread across multiple options. A consideration is that an "auto-resume" feature likely needs to query the option value on every page load.

Track the following data as progress is made through core profiler:

* Core profiler progress status, e.g: none | complete | partially complete
* Core profiler last completed step
* Core profiler last timestamp

**Comment by rjchow** [comment]
Completed by https://github.com/woocommerce/woocommerce/pull/52525
