### ISSUE TITLE
[Infra] tests should run if tests are updated

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#52560]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

💡 At least in relation to unit tests, it seems that if tests are modified, removed or added to, the test suite and our usual test matrix will not run. So we've no way to validate the change is correct, other than locally, which usually isn't as comprehensive (most of us don't run the tests against a battery of PHP and WP versions).

👀 Please see [this PR](https://github.com/woocommerce/woocommerce/pull/52433) and its action history for an example.

### Expected behavior

🤔 If somebody submits a change that alters a unit test (or adds a test), and nothing else, our test matrix should kick in within GitHub.

### Actual behavior

😢 Above expectations are not met.

### Steps to reproduce

1. Alter a test.
2. Change nothing else.
3. Submit as a PR.
4. Observe which actions do and do not run.

### WordPress Environment

—

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by kalessil** [comment]
Tested with #52734, as per the latest state the UTs jobs [do start as expected](https://github.com/woocommerce/woocommerce/actions/runs/11796361648/job/32858059515?pr=52734).

**Comment by kalessil** [comment]
@barryhughes: I can see some pointers that tests were not stated in the PR (https://github.com/woocommerce/woocommerce/pull/52433/commits), but I suspect one of two things:
- it's relevant to my most recent patches of CI-workflow: pdV5qK-KA-p2
- or GitHub actions not launching the CI-workflow: it rarely, but happen and on my observation list

I did the fresh test - see comment above and will close the issue. If it surface again, we'll reopen it.

**Comment by barryhughes** [comment]
Great, thank you for checking on it!
