### ISSUE TITLE
Patterns: Product Hero 2 Column 2 Row lacks images

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#52592]
**Steps to reproduce:**
1. Add new post
2. Try adding "Product Hero 2 Column 2 Row" pattern
3. There are 2 images missing called:
- `man-person-winter-photography-guy-statue.jpg`
- `pattern-fashion-clothing-outerwear-wool-scarf.png`

![Image](https://github.com/user-attachments/assets/682fe6be-3317-470e-b81c-dee996769678)

![Image](https://github.com/user-attachments/assets/83c05609-f1ab-4d38-a578-1c506f126335)

**Note:**
The problem is there's no reference to such images in the repository so I'm not sure where it's coming from.

**Comment by Aljullu** [comment]
I just checked, and it seems like we don't use this pattern in the AI flow, so it should be fine to remove it from the PTK.

Fun fact, we already have a very similar pattern in WC core (which is also used in the AI flow): Hero Product Chessboard.

![Image](https://github.com/user-attachments/assets/7b2e46be-d277-4d52-a8c5-c672c2505c36)

**Comment by gigitux** [comment]
Thanks for checking it, @Aljullu! I removed it! 🙇
