### ISSUE TITLE
Add To Cart Form button: button and input height discrepancy

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#52628]
There’s a noticeable height difference between the button and the input, especially with larger buttons (like TT5 style). We are aware of this problem, but it is more pronounced with larger buttons:

| Classic Layout | Stepper Layout |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/12c18120-cec1-4d83-9a44-44dd39e8197b)| ![Image](https://github.com/user-attachments/assets/66a41261-f1e5-47bf-857f-90cc8c5e05f2)| 

Steps to Reproduce:
1. Install and enable TT5.
2. Visit a simple product page.
3. See the button and input height discrepancy

Could it make sense to explore a fix for this issue specifically for the TT5 theme?

**Comment by danielwrobert** [comment]
It seems like we have a button and input height discrepancy in the opposite direction with TT4, where the input is greater in height than the button.

![Image](https://github.com/user-attachments/assets/627da4fe-8b9a-4411-b33e-855119cbcffa)

I'll let @j111q (and anyone else) weigh in here but I'm not sure we should prioritize this, unless we can find a way to ensure consistency across themes. 🤔

**Comment by retrofox** [comment]
Crossing references
 
* https://github.com/woocommerce/woocommerce/pull/48876
* ...

**Comment by retrofox** [comment]
Just FYI, testing with `TT3`, similar issues:

![Image](https://github.com/user-attachments/assets/5bf36602-74b4-49f9-94ad-9a24174732cd)

**Comment by gigitux** [comment]
Thank you for your feedback on this issue! As mentioned in the description, we are aware that this problem affects all block themes. In my opinion, the issue is more noticeable with larger buttons (so on TT5). I believe we should aim to enhance the appearance and feel of this button in TT5, but maybe I'm overthinking! Let's see if @j111q has a specific opinion on this.

EDIT: I removed `[TT5]` from the title.

**Comment by danielwrobert** [comment]
> As mentioned in the description, we are aware that this problem affects all block themes.

@gigitux thanks for reiterating this point, I overlooked it in the description! 😄 

To be clear, I do agree that we should aim to enhance these buttons. My main point was not to necessarily prioritize it ahead of some of the other TT5-specific items, given that this appears to be a bit more broad.

**Comment by gigitux** [comment]
> > As mentioned in the description, we are aware that this problem affects all block themes.
> 
> [@gigitux](https://github.com/gigitux) thanks for reiterating this point, I overlooked it in the description! 😄
> 
> To be clear, I do agree that we should aim to enhance these buttons. My main point was not to necessarily prioritize it ahead of some of the other TT5-specific items, given that this appears to be a bit more broad.

@retrofox investigated on this (thanks!), and it looks super complex to find a good solution. At this point, I agree with you and I would suggest prioritizing other TT5 specific items!

**Comment by ResponsiveFlow** [comment]
What happened to the quantity stepper in the latest nightly? it disappeared

**Comment by gigitux** [comment]
We hide this feature under an experimental flag (https://github.com/woocommerce/woocommerce/pull/52573). This allows us to gather feedback from the community before releasing it!

You can enable it installing `WooCommerce Beta Tester`, visiting `wp-admin/tools.php?page=woocommerce-admin-test-helper` and enabling `add-to-cart-with-options-stepper-layout` feature.
