### ISSUE TITLE
[Product Editor] Fatal error loading on JN site

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#52635]
When loading the new All Products screen a fatal error occurs. cc @louwie17 

<img width="625" alt="image" src="https://github.com/user-attachments/assets/508bf891-f646-423c-af81-d90a322cd1e8">

### Steps to reproduce

1. JN site with WC Beta Tester, `trunk` branch, and Gutenberg plugin
2. Turn on the Product Editor WooCommerce > Settings > Advanced > Feature > Try the new Product Editor
3. Make sure Gutenberg experiments are turned on, Gutenberg > Experiments > Custom dataviews
4. Turn on the feature flag `product-data-views`, Tools > WCA Test Helper > Features
5. Visit the new Product Editor, Products > All Products ( new )
6. See blank screen and fatal errors

**Comment by gigitux** [comment]
Thank you for reporting this! I’m closing this issue because:
- We are aware of it.
- “All Products (new)” is simply a playground environment for testing the DataViews library.
