### ISSUE TITLE
When rewriting only title of product the button update doesnt works

### ISSUE THREAD

**Issue by elchin-dev** [woothemes/woocommerce#52645]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Console
An invalid form control with name='_deal_quantity' is not focusable. <input type=​"number" min=​"2" class=​"short" name=​"_deal_quantity" id=​"_deal_quantity" value=​"1">​

### Expected behavior

An invalid form control with name='_deal_quantity' is not focusable. <input type=​"number" min=​"2" class=​"short" name=​"_deal_quantity" id=​"_deal_quantity" value=​"1">​

### Actual behavior

An invalid form control with name='_deal_quantity' is not focusable. <input type=​"number" min=​"2" class=​"short" name=​"_deal_quantity" id=​"_deal_quantity" value=​"1">​

### Steps to reproduce

An invalid form control with name='_deal_quantity' is not focusable. <input type=​"number" min=​"2" class=​"short" name=​"_deal_quantity" id=​"_deal_quantity" value=​"1">​

### WordPress Environment

An invalid form control with name='_deal_quantity' is not focusable. <input type=​"number" min=​"2" class=​"short" name=​"_deal_quantity" id=​"_deal_quantity" value=​"1">​

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nigeljamesstevenson** [comment]
Hi @elchin-dev 

Can you please edit the issue and provide more details? All of the sections in the issue above are identical. We would need more information to move forward... Thanks
