### ISSUE TITLE
[DOC-BUG] Replace `wp wc cot` with `wp wc hpos` on HPOS CLI Tools

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#52659]
## Link to the Page/Section

> Provide a link to the specific page or section that you're referring to.

The doc in question is https://developer.woocommerce.com/docs/hpos-cli-tools/.

## Description of the Suggestion

> Describe the changes you suggest to improve or correct the documentation. Be specific about any errors or areas of confusion you've identified.

On that page, we still refer to `wp wc cot`, even though we replaced these commands with `wp wc hpos` in #46766. 

cc: @jorgeatorres 

## Reason for the Suggestion

> Why do you believe this change will make the documentation clearer or more accurate?

As `wp wc cot` is deprecated, we should either replace these commands with `wp wc hpos`, or mention that these commands are deprecated and mention the new commends.

## Additional Context

> Add any other context, references, or screenshots that support your suggestion.

n/a

**Comment by jorgeatorres** [comment]
I believe this was fully addressed in #52552, but please let me know if I'm missing something @nielslange. Happy to re open if that's the case. Thanks for the report!

**Comment by nielslange** [comment]
Thanks for following up, @jorgeatorres. I confirm that the issue has been addressed and can remain closed. 🙌
