### ISSUE TITLE
wc9.4.rc 4 and new wp 6.7 rc4 php notices on non-english default  languages

### ISSUE THREAD

**Issue by MariaLM2017** [woothemes/woocommerce#52705]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With the new wordpress 6.7 rc4 and woocoomerce 9.4 rc4 all  Spanish variations and main Spanish language get  php notices appear in an uncontrolled way adding them in the logs for each access to the site:

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /home/dev/misitio.local/wp-includes/functions.php on line 6114 

### Expected behavior

no php notices should be generated when using non-english default(in english default you don't get the notices)

### Actual behavior

if you're using "Spain" language (or as i'm testing now every non default english after updating translations from updates menu) the site get translated ok but a lot of the same php notice appears every access to a page:

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /home/dev/misitio.local/wp-includes/functions.php on line 6114 

### Steps to reproduce

a) Spanish(as an example) getting php notices
0. set language of your site to "Spanish" 
1.upgrade wc to latest rc(9.4 rc4)
2. upgrade to wp 6.7 rc4 using wordpress beta tester plugin
3. update your translations
4. navigate around your site
5. watch the logs or if you set wp-debug display to on you'll see the errors

 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://misitio.local
Site address (URL): https://misitio.local
WC Version: 9.4.0-rc.4
Legacy REST API Package Version: El plugin Legacy REST API no está instalado en este sitio.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7-RC4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.37
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.4.0
WC Database Prefix: wp_
Tamaño total de la base de datos: 318.23MB
Tamaño de los datos de la base de datos: 157.12MB
Tamaño del índice de la base de datos: 161.11MB
wp_woocommerce_sessions: Datos: 0.03MB + Índice: 0.01MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.01MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.01MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 2.52MB + Índice: 0.22MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 40.56MB + Índice: 11.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.04MB + Índice: 0.12MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.05MB + Índice: 0.09MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.04MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.04MB + Índice: 0.12MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.04MB + Índice: 0.01MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.04MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.04MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.04MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.20MB + Índice: 0.10MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.15MB + Índice: 0.12MB + Motor InnoDB
wp_commentmeta: Datos: 0.70MB + Índice: 0.70MB + Motor InnoDB
wp_comments: Datos: 20.11MB + Índice: 11.00MB + Motor InnoDB
wp_duplicator_packages: Datos: 0.03MB + Índice: 0.01MB + Motor InnoDB
wp_links: Datos: 0.04MB + Índice: 0.04MB + Motor InnoDB
wp_litespeed_url: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_litespeed_url_file: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_options: Datos: 8.70MB + Índice: 0.50MB + Motor InnoDB
wp_postmeta: Datos: 100.1MB + Índice: 100.20MB + Motor InnoDB
wp_posts: Datos: 11.53MB + Índice: 6.74MB + Motor InnoDB
wp_sm_advanced_search_temp: Datos: 0.02MB + Índice: 0.01MB + Motor InnoDB
wp_stream: Datos: 0.00MB + Índice: 0.01MB + Motor InnoDB
wp_stream_meta: Datos: 0.00MB + Índice: 0.02MB + Motor InnoDB
wp_term_relationships: Datos: 0.3MB + Índice: 0.11MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.01MB + Índice: 0.03MB + Motor InnoDB
wp_termmeta: Datos: 0.01MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.04MB + Índice: 0.06MB + Motor InnoDB
wp_usermeta: Datos: 8.52MB + Índice: 13.03MB + Motor InnoDB
wp_users: Datos: 2.53MB + Índice: 1.08MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.01MB + Índice: 0.01MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.73MB + Índice: 0.34MB + Motor InnoDB
wp_wc_download_log: Datos: 0.04MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_addresses: Datos: 2.51MB + Índice: 2.07MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.20MB + Índice: 0.11MB + Motor InnoDB
wp_wc_order_operational_data: Datos: 4.57MB + Índice: 2.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 2.71MB + Índice: 1.09MB + Motor InnoDB
wp_wc_order_stats: Datos: 1.23MB + Índice: 0.55MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_orders: Datos: 4.33MB + Índice: 4.22MB + Motor InnoDB
wp_wc_orders_meta: Datos: 25.56MB + Índice: 54.22MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.01MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.27MB + Índice: 0.68MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.05MB + Índice: 0.05MB + Motor InnoDB
wp_woocommerce_termmeta: Datos: 0.05MB + Índice: 0.05MB + Motor InnoDB
wp_wpmailsmtp_debug_events: Datos: 0.01MB + Índice: 0.00MB + Motor InnoDB
wp_wpmailsmtp_tasks_meta: Datos: 0.00MB + Índice: 0.00MB + Motor InnoDB
wp_wsal_metadata: Datos: 0.09MB + Índice: 0.07MB + Motor InnoDB
wp_wsal_occurrences: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 170
nav_menu_item: 28
page: 41
post: 11
product: 401
product_variation: 952
revision: 211
shop_coupon: 99
shop_order: 12280
shop_order_placehold: 4
shop_order_refund: 260
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (11) ###

Contact Form 7: por Takayuki Miyoshi – 6.0
WooCommerce: por Automattic – 9.4.0-rc.4
WordPress Beta Tester: por Equipo de actualización/instalación de WordPress – 3.6.1
WP Mail SMTP: por WP Mail SMTP – 4.2.0

### Inactive Plugins (14) ###

Adminimize: por WP Media – 1.11.11

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: ARS (AR$)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog-2 (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
exclude-from-search-2 (exclude-from-search-2)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 días
Level threshold: –
Log directory size: 72 KB

### WC Pages ###

Base de la tienda: #4 - /misprod/
Carrito: #5 - /carrito/ -  Contiene el shortcode [woocommerce_cart]
Finalizar compra: #6 - /tusdatos/ -  Contiene el shortcode [woocommerce_checkout]
Mi cuenta: #7 - /mi-cuenta/
Términos y condiciones: /tyc/

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-11 17:23:47 -03:00
Options: ✔
Notes: 4
Onboarding: completed

### Action Scheduler ###

Completo: 366
Oldest: 2024-10-11 11:03:28 -0300
Newest: 2024-11-11 09:11:13 -0300

Fallida: 0

Pendiente: 2
Oldest: 2024-11-11 13:57:34 -0300
Newest: 2024-11-11 13:57:34 -0300

### Status report information ###

Generated at: 2024-11-11 09:31:55 -03:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by MariaLM2017** [comment]
When you update your language translations, in some variations they start to work, but the php notice then appears everytime, like in the main spanish language!!

**Comment by MariaLM2017** [comment]
doing a back of the envelope calculation, my site logs will grow up to 1gb daily with just that php notice everytime!!

**Comment by tammullen** [comment]
Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/52646. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
