### ISSUE TITLE
Delayed account creation styling adjustments

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#52717]
Some styling adjustments can be made to the delayed account creation block to improve the experience on mobile and appearance of forms. This issue gathers those tasks.

- [x] Stacked columns on mobile (adjust flex layout)
- [x] Lessen the content jump when inputting an invalid password

**Comment by nerrad** [comment]
@mikejolley I'm closing this issue because it looks like it was fixed with the attached PR (and the checked off subtasks). Please do re-open if it I closed it in error (and it'd be helpful to know if this is a feature or bug).
