### ISSUE TITLE
[Product List API] Filter by product type

### ISSUE THREAD

**Issue by albarin** [woothemes/woocommerce#52771]
We want to add the `include_types` and `exclude_types` parameters to the `/products` endpoint to enable filtering products by specific product types: `simple`, `variable`, `external`, `grouped`, `virtual`, `downloadable`, and `purchasable`.

These types need to be filtered in combination. For example, we might need to retrieve `simple` and `variable` products but exclude `virtual` or `external` ones in a single request.

Note: `virtual`, `downloadable`, and `purchasable` are not actual product types, we need to investigate how we can include them in the same query.

**Comment by coreymckrill** [comment]
It seems like `virtual`, `downloadable`, and `purchasable`, aside from not being actual product types, are also different in that they can be combined with product types and with each other. So I'm not sure it makes sense to try and lump them all into `include_types` and `exclude_types`.

An alternative would be to have separate collection params for these properties. Similar to the existing [`featured` collection param](https://github.com/woocommerce/woocommerce/blob/4214c5c675883382583b29370f7bcc219994ad17/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php#L2342-L2347), we could just have `virtual` and `downloadable` as boolean params. I'm not sure about `purchasable`, as I don't see that as one of the available [backend query vars](https://github.com/woocommerce/woocommerce/blob/4214c5c675883382583b29370f7bcc219994ad17/plugins/woocommerce/includes/class-wc-product-query.php#L28-L64).

**Comment by albarin** [comment]
> An alternative would be to have separate collection params for these properties. Similar to the existing [featured collection param](https://github.com/woocommerce/woocommerce/blob/4214c5c675883382583b29370f7bcc219994ad17/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php#L2342-L2347), we could just have virtual and downloadable as boolean params. I'm not sure about purchasable, as I don't see that as one of the available [backend query vars](https://github.com/woocommerce/woocommerce/blob/4214c5c675883382583b29370f7bcc219994ad17/plugins/woocommerce/includes/class-wc-product-query.php#L28-L64).

@coreymckrill I agree, they are not product types, so it would be weird to include them in `include_types`.
Also, `purchasable` is a bit different, it depends on multiple conditions and it has a filter: https://github.com/woocommerce/woocommerce/blob/9ac48232a944baa2dbfaa7dd47edf9027cca9519/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1661

Adding, @malinajirka @iamgabrielma and @AnirudhBhat to the conversation to have their input as well. Thanks!

**Comment by malinajirka** [comment]
I like the proposal and I agree that including them in `include_types` would be misleading. Having them as separate flags will work just fine for the mobile clients.

> Also, purchasable is a bit different, it depends on multiple conditions and it has a filter:

I don't fully understand this one - would it be problematic to include it on the API given it has a filter + depends on multiple conditions?

**Comment by albarin** [comment]
> I don't fully understand this one - would it be problematic to include it on the API given it has a filter + depends on multiple conditions?

@malinajirka might be trickier since `purchasable` cannot be queried directly from the DB as @coreymckrill mentioned 👇 

> I'm not sure about purchasable, as I don't see that as one of the available [backend query vars](https://github.com/woocommerce/woocommerce/blob/4214c5c675883382583b29370f7bcc219994ad17/plugins/woocommerce/includes/class-wc-product-query.php#L28-L64).

We'll look into it.
