### ISSUE TITLE
How to Trigger an Action After WooCommerce Block Cart Update for Updated Total Value for js?

### ISSUE THREAD

**Issue by prswzz** [woothemes/woocommerce#52783]
### Describe the solution you'd like

Is there an event or action that triggers after the cart is updated, such as when an item’s quantity changes or an item is removed? We need this to fire only once the cart has been fully updated, as we need to retrieve the updated cart total value for use in WooCommerce cart blocks and JavaScript code.

### Describe alternatives you've considered

const delayedFetchCartData = () => setTimeout( fetchCartData, 4000 );
		addAction(
			'experimental__woocommerce_blocks-cart-set-item-quantity',
			'asnpWesb',
			delayedFetchCartData
		);
		addAction(
			'experimental__woocommerce_blocks-cart-remove-item',
			'asnpWesb',
			delayedFetchCartData
		);

**Comment by senadir** [comment]
Hey! There's no foolproof way to get an event after state has been applied, however, you can use `isItemPendingQuantity( key )` and `isItemPendingDelete( key )`



```js
wp.hooks.addAction(
	'experimental__woocommerce_blocks-cart-set-item-quantity',
	'test',
	( { product, quantity } ) => {
		const key = product.key;
		const unsubscribe = wp.data.subscribe(() => {
            const isPendingQuantity = wp.data.select('wc/store/cart').isItemPendingQuantity(key);
            if ( ! isPendingQuantity ) {
                console.log('done pending');
                unsubscribe();
            }
        }, 'wc/store/cart');
	}
);
```

Let me know if this works for you.

**Comment by kevinamorim** [comment]
> Hey! There's no foolproof way to get an event after state has been applied, however, you can use `isItemPendingQuantity( key )` and `isItemPendingDelete( key )`
> 
> wp.hooks.addAction(
> 	'experimental__woocommerce_blocks-cart-set-item-quantity',
> 	'test',
> 	( { product, quantity } ) => {
> 		const key = product.key;
> 		const unsubscribe = wp.data.subscribe(() => {
>             const isPendingQuantity = wp.data.select('wc/store/cart').isItemPendingQuantity(key);
>             if ( ! isPendingQuantity ) {
>                 console.log('done pending');
>                 unsubscribe();
>             }
>         }, 'wc/store/cart');
> 	}
> );
> Let me know if this works for you.

Tested on my side and works perfectly. Thanks!
