### ISSUE TITLE
Checkout block notices aren't dismissed after a successful request

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#52813]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In Checkout block, dismissible notices (and possibly non-dismissible ones but I didn't test)  stays rendered after a successful request, this causes confusion for users because if they actually did fix the issue, it's not clear if the error is gone or not and they need to know to remove it.

This is a regression in 9.3

https://github.com/user-attachments/assets/d455f8fc-f801-4fec-a8b0-c80989ec70a3

### Expected behavior

Notices should clear after a successful request.

### Actual behavior

Notices persist even if you fix the issue.

### Steps to reproduce

1. [Copy the example](https://developer.woocommerce.com/docs/cart-and-checkout-additional-checkout-fields/#7-a-full-example) here somewhere or in a snippet plugin.
2. Go to Checkout, fill out all fields, notice that filling the second Gov ID field doesn't clear the error.
3. Make sure both fields match, manually remove the error.
4. Modify one field.
5. You get a new error, now fix the field again.
6. Notice the error persists.

### WordPress Environment

WP 6.7
WC trunk.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by danielcharrua** [comment]
@ralucaStan what's the author feedback you need here?

**Comment by senadir** [comment]
Feedback I assume was about non-dismissed notice Raluca? I did answer in Slack but answer here for better visibility.

I wasn't able to get a non-dismissible notice to render in Checkout, the only one was related to Coupons but that's unrelated. A recent refactor made all of our notices dismissible.
