### ISSUE TITLE
[DOC-BUG] Mention identifier of available field locations

### ISSUE THREAD

**Issue by nielslange** [woothemes/woocommerce#52823]
## Link to the Page/Section

> Provide a link to the specific page or section that you're referring to.

https://developer.woocommerce.com/docs/cart-and-checkout-additional-checkout-fields/#0-available-field-locations

## Description of the Suggestion

> Describe the changes you suggest to improve or correct the documentation. Be specific about any errors or areas of confusion you've identified.

Currently, the section refers to the following locations:

- Contact information
- Addresses (Shipping and Billing)
- Order information

At this stage, it's unclear what identifier these locations have. I suggest replacing this list with the following table:

| Title                                | Identifier |
| ------------------------------------ | ---------- |
| Contact information                  | **`contact`**  |
| Addresses (Shipping **and** Billing) | **`address`**  |
| Order information                    | **`order`**    |

Additionally, including snippets and screenshots for each field location would further help developers visualize the changes and understand where their custom fields will appear. 

## Reason for the Suggestion

> Why do you believe this change will make the documentation clearer or more accurate?

Currently, the section [Available field locations](https://developer.woocommerce.com/docs/cart-and-checkout-additional-checkout-fields/#0-available-field-locations) only tells the name of the available locations, but it does not mention the corresponding identifier. While the section [Using the API](https://developer.woocommerce.com/docs/cart-and-checkout-additional-checkout-fields/#3-using-the-api) lists the available locations, it's easy to miss this part.

**Comment by senadir** [comment]
Make sense!
