### ISSUE TITLE
Wrong calculation of the width of thumbnails in the product gallery

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#52829]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi woocommerce team,

It seems that WooCommerce calculates the width of thumbnails wrongly in RTL. Please see the screenshot below.

![Image](https://github.com/user-attachments/assets/198b871c-c488-40eb-9b7e-1dabf8df8da8)

It also gets worse when we move to the next image.

![Image](https://github.com/user-attachments/assets/29b1d876-acc6-4675-8dc7-727946847a49)

### Expected behavior

But in LTR things are quite good.

![Image](https://github.com/user-attachments/assets/e72b0452-333f-47d3-b1af-3cfd977b9cf1)

### Actual behavior

-

### Steps to reproduce

Make sure it is RTL website. On the product page, check the width of thumbnail images.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://domain.com
Site address (URL): https://domain.com
WC Version: 9.4.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.7.1
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.19-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. 403
Remote Get: ✔

### Database ###

WC Database Version: 9.4.1
WC Database Prefix: avgrohkhza_
Total Database Size: 6.15MB
Database Data Size: 5.42MB
Database Index Size: 0.73MB
avgrohkhza_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_actionscheduler_actions: Data: 0.08MB + Index: 0.04MB + Engine MyISAM
avgrohkhza_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_actionscheduler_logs: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
avgrohkhza_bricks_filters_element: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_bricks_filters_index: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_bricks_filters_index_job: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_bricks_form_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_e_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_e_notes_users_relations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_e_submissions: Data: 0.00MB + Index: 0.03MB + Engine MyISAM
avgrohkhza_e_submissions_actions_log: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_e_submissions_values: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_jet_post_types: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_jet_search_suggestions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_jet_search_suggestions_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_jet_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_options: Data: 2.28MB + Index: 0.07MB + Engine MyISAM
avgrohkhza_postmeta: Data: 2.34MB + Index: 0.07MB + Engine MyISAM
avgrohkhza_posts: Data: 0.37MB + Index: 0.04MB + Engine MyISAM
avgrohkhza_rank_math_404_logs: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_rank_math_internal_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_rank_math_internal_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_rank_math_redirections: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_rank_math_redirections_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_terms: Data: 0.09MB + Index: 0.13MB + Engine MyISAM
avgrohkhza_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_term_taxonomy: Data: 0.11MB + Index: 0.06MB + Engine MyISAM
avgrohkhza_usermeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
avgrohkhza_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_orders: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
avgrohkhza_wc_orders_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_order_addresses: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_order_operational_data: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
avgrohkhza_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
avgrohkhza_woocommerce_ir: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 109
bricks_template: 8
custom_css: 1
elementor_font: 2
elementor_library: 9
elementor_snippet: 1
jet-menu: 3
jet-smart-filters: 7
jet-woo-builder: 10
page: 6
post: 5
product: 16
product_variation: 7
revision: 241
shop_order_placehold: 6
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.4.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 698 B

### WC Pages ###

Shop base: #13361 - /shop/
Cart: #13389 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #13391 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Bricks
Version: 1.11.1
Author URL: https://bricksbuilder.io/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: bricks/archive-product.php
bricks/woocommerce/cart/cart-empty.php
bricks/woocommerce/cart/cart.php
bricks/woocommerce/cart/proceed-to-checkout-button.php
bricks/woocommerce/checkout/form-checkout.php version 3.5.0 is out of date. The core version is 9.4.0
bricks/woocommerce/checkout/form-pay.php
bricks/woocommerce/checkout/order-receipt.php
bricks/woocommerce/checkout/thankyou.php
bricks/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-14 14:48:51 +03:30
Options: ✔
Notes: 32
Onboarding: completed

### Action Scheduler ###

Complete: 279
Oldest: 2024-11-01 23:44:48 +0330
Newest: 2024-11-14 10:26:35 +0330

Failed: 9
Oldest: 2023-02-22 00:22:00 +0330
Newest: 2024-11-11 18:18:53 +0330

Pending: 1
Oldest: 2024-11-14 21:34:01 +0330
Newest: 2024-11-14 21:34:01 +0330

### Status report information ###

Generated at: 2024-11-14 15:51:46 +03:30
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
Hi @79ho3ein,

Thanks for opening this issue!

I attempted to replicate the issue using [TT4](https://wordpress.org/themes/twentytwentyfour/) but was unsuccessful. Could you please try checking with TT4 on your end? It could be an issue of Bricks theme.

**Comment by 79ho3ein** [comment]
Hi @gigitux, Thank you for reviewing this report.

Please make sure that the **slider** for Thumbnail is enabled. Also, the language of the website should be **RTL**. Everything works well in LTR.

**Comment by gigitux** [comment]
WooCommerce Core does not include a feature for enabling the Thumbnail slider. It appears to be a functionality provided by the Brick Builder. If possible, please share reproduction steps that do not involve any additional plugins.

**Comment by 79ho3ein** [comment]
Thank you @gigitux, I passed it on to the team. Thank you for your reply

**Comment by gigitux** [comment]
I’m going to close this issue, but please do leave a comment if you have additional information that you think will help us reproduce the issue. We will re-open if we’re able to replicate.

Thanks again for your report!
