### ISSUE TITLE
Incorrect wording in WooPayments no thanks modal

### ISSUE THREAD

**Issue by anu-rock** [woothemes/woocommerce#52868]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The modal that appears on clicking the action incentive's "no thanks" button says, "Note that the extension hasn’t been installed, this will simply remove WooPayments from the navigation." We'll need to change the wording as this is [no longer the case](https://github.com/woocommerce/woocommerce/pull/51541).

### Expected behavior

Dismissing the WooPayments promo no longer removes the Payments menu item from WP Admin. So, the modal content should not mention that.

### Actual behavior

The no thanks modal mentions an outdated behavior that was changed in WC 9.4.

### Steps to reproduce

1. Spin up a new WooCommerce site (v9.4+).
2. Go to WP Admin → Payments.
3. In the WooPayments promo, click the "no thanks" button.
4. On the resulting no thanks modal, notice the first line below the title.

![Image](https://github.com/user-attachments/assets/b5189de3-0d5b-4fa6-a0af-50c5c6c1ff75)

### WordPress Environment

NA

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by vladolaru** [comment]
I've updated the wording to: "Note that the extension hasn’t been installed. This will simply dismiss our limited time offer. Please take a moment to tell us why you’d like to dismiss the WooPayments offer."
