### ISSUE TITLE
Analytics report tables do not scroll horizontally

### ISSUE THREAD

**Issue by mikkamp** [woothemes/woocommerce#52879]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When opening any of the Analytics Report pages, the tables which show an overview do not scroll horizontally when on a mobile device.

The following recording shows how the full screen scrolls instead of just the table columns:

https://github.com/user-attachments/assets/0b364149-54f9-46ef-bb9a-6e3467d8353b

We have done some troubleshooting and tracked this down to the changes in this PR: https://github.com/woocommerce/woocommerce/pull/48487

> Before the change, it wouldn't import [woocommerce-admin/client/homescreen/style.scss](https://github.com/woocommerce/woocommerce/blob/9.2.0/plugins/woocommerce-admin/client/homescreen/style.scss) until they share the [hasTwoColumnLayout](https://github.com/woocommerce/woocommerce/pull/48487/files#diff-09decac422e095f59e5dbee20fbd9c9255e09bd833ecc0c582d9dd07055ea887R42) function and then indirectly load that style.css file.

This causes [the following rule](https://github.com/woocommerce/woocommerce/blob/9.2.0/plugins/woocommerce-admin/client/homescreen/style.scss#L1-L5) to be included which makes the content overflow visible:
```css
.woocommerce-admin-page #wpcontent,
.woocommerce-admin-page.woocommerce_page_wc-admin #wpbody-content {
	overflow-x: inherit !important; // Overwriting wc-admin css from elsewhere. Necessary to make the right-hand column 'stick'
	position: relative;
}
```

Disabling this rule allows the table to be scrollable. Since these changes were initially intended only for the "two column" layout on the WooCommerce > Home screen, one of the suggestions was to use the class `.woocommerce-admin-page__home` to restrict it to only apply to the home screen and not every wc-admin page. This means any Analytic reports will not be affected.

Issue originally reported on x: https://x.com/tombrunberg/status/1857166309559066902

### Expected behavior

For the table columns to scroll correctly, as is shown in the following recording with the offending CSS rule disabled:

https://github.com/user-attachments/assets/1b26b652-b8ee-4e01-ac9c-972af1f7fe3b

### Actual behavior

All the screen content scrolls instead of just the columns.

### Steps to reproduce

1. Go to Analytics > Revenue in the admin dashboard on a mobile (or use Chrome dev tools with mobile view)
2. No need to have order data available for that period as the table will be populated per day with 0 values
3. Scroll the table horizontally
4. Notice that the full table scrolls instead of just the columns

### WordPress Environment

WordPress 6.7
WooCommerce 9.4.1 (this was tested and confirmed to be happening since WooCommerce 9.2.0)
Platform: Android mobile or Chrome dev tools with mobile view

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikkamp** [comment]
As a workaround the following code snippet can be used to override the behaviour until this issue gets resolved:

```php
add_action(
	'admin_head',
	function() {
	?>
	<style>
		html:has(body.woocommerce-admin-page__analytics_report) { overflow-x: hidden; }
	</style>
	<?php
	}
);
```

**Comment by ecgan** [comment]
This issue is fixed in PR https://github.com/woocommerce/woocommerce/pull/52971. Closing this issue.
