### ISSUE TITLE
Woocommerce bug

### ISSUE THREAD

**Issue by gittajozifek** [woothemes/woocommerce#52881]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Dear WooCommerce Support Team,

I am encountering an issue with registering my webshop on WooCommerce. The email associated with the account is aszlone1971@gmail.com, and the website domain is sopianaeimperialgloves.com.

Here are the problems I am experiencing:

I cannot complete the registration process for my webshop in WooCommerce.
The "Country/Region" selector does not work during the setup, preventing me from moving forward.
I am unable to connect the Google for WooCommerce plugin, as it consistently shows error messages.
I have tried troubleshooting by updating all plugins and WordPress to the latest versions, clearing my browser cache, and attempting the setup in incognito mode, but the issues persist.

Could you please assist me in resolving this?

Thank you in advance for your help.

Best regards,

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

-

### WordPress Environment

-

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by gittajozifek** [comment]
-

**Comment by lanej0** [comment]
Hi @gittajozifek,

Is this happening during sign up for a hosting account?  Which web host are you using? Could you include a screenshot of the problem you're experiencing (and if possible, could you open the JavaScript Console when signing up so we can see any errors that may be occurring)?
