### ISSUE TITLE
Function _load_textdomain_just_in_time was called incorrectly.

### ISSUE THREAD

**Issue by Martje65** [woothemes/woocommerce#52893]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Sins WordPress 6.7 we have the next notice, please correct it.

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /wp-includes/functions.php on line 6114

### Expected behavior

No error

### Actual behavior

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /wp-includes/functions.php on line 6114

### Steps to reproduce

define( 'WP_DEBUG', true);
install woocommerce 9.4.1
install wordpress 6.7 and see the notice.

### WordPress Environment

woocommerce 9.4.1
wordpress 6.7

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @Martje65,

Could you include some information about what theme you're using/what other plugins and extensions you have installed?  These errors can occasionally be caused by a conflict between extensions.

**Comment by Martje65** [comment]
Dear @lanej0 
I have tested with only Woocommerce 9.4.1 active and Twenty Twenty-Five theme.

Here you can read more about the notice: https://core.trac.wordpress.org/ticket/44937

**Comment by rodelgc** [comment]
Hi @Martje65.

This seems like a duplicate of an earlier issue - https://github.com/woocommerce/woocommerce/issues/52646. Discussions had already started there. Monitor that thread instead for developments.

I will close this issue now. Feel free to provide additional details if you think this issue is not the same as the other one I mentioned. Thanks!
