### ISSUE TITLE
[CFE]: Fix Payments menu item linking to a blank page

### ISSUE THREAD

**Issue by vladolaru** [woothemes/woocommerce#52901]
### Which release does this request apply to?

9.5

### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/52900

### Why do these PRs need to break the code freeze?

This fixes the Payments main menu item linking to a blank page when the setup tasklist has been hidden, leading to a poor UX. 

Plus, there are scenarios when this can lead to fatal PHP errors (see this Slack discussion p1731934069552079/1731709304.869299-slack-C3ECCGUVC). This happens, most likely, if someone removes the tasklists with the `woocommerce_admin_experimental_onboarding_tasklists` filter.

The changes that need this fix have been introduced in WC 9.4.

### What is the consequence if this exception does not get included?

Users who have hidden the setup tasklist will see a blank page when clicking the Payments main menu item. Under certain circumstances, some users may receive a fatal error.

### What is the plan should defects to be discovered in these PRs ahead of final release?

Reverting this PR.

### How should this change be communicated in the release post on the public developer blog:

There is no need to add additional communication besides the already planned one.

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

@woocommerce/moltres 

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.

**Comment by tammullen** [comment]
- [x] Escape analysis completed (reminder ping this is needed, although some analysis also happening in https://github.com/woocommerce/woocommerce/issues/52918#issuecomment-2487407013)
- [x] PR merged to target release branch
- [x] PR cherry-picked to trunk
- [ ] Followup issue if any

**Comment by vladolaru** [comment]
Escape Analysis:

We missed accounting for the scenario where the user hides the task lists because of our bias in onboarding _not_ to do that. Our mindset should have been more adversarial.

Going forward, we should aim to make our code more defensive and less assuming of happy paths. I don't think this scenario is worthy of inclusion in our critical paths or GS testing as it is sufficiently edgy, and there are workarounds available.

**Comment by lanej0** [comment]
To add to the escape analysis above:

We've [set up an alert](https://mc.a8c.com/grafana/alerting/grafana/ee9bfsxvie22od/view) which will notify Solaris if this type of error spikes in the future.
