### ISSUE TITLE
Create and publish new e2e-utils-playwright package

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#52939]
More context: peIGPw-zp-p2

This issue tracks the tasks required to create a new JS package named e2e-utils-playwright, move all the relevant utils from the e2e tests into the package and release/publish it to NPM.

**Comment by jeffpaul** [comment]
@Sidsector9 FYI on above in case any are items you can help cover as part of your Project Thread on this topic.  cc: @vikrampm1

**Comment by jeffpaul** [comment]
@adimoldovan with the existing sub-issues closed is there anything else you see as needed here?

**Comment by adimoldovan** [comment]
This is done.
