### ISSUE TITLE
Delayed Account Creation: update shopper facing copy when Send password setup link is on

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#52986]
**Description:** when the `After checkout` option is enabled alongside `Send password setup link`, we should make it clear where we're sending the password.

![Image](https://github.com/user-attachments/assets/69536dfe-26fb-42d1-b3a4-83229aeae5c2)

**Acceptance criteria:** 
- [ ] Include the email address in the CTA or copy below to ensure users understand where they'll receive the password.

**Comment by elizaan36** [comment]
![Image](https://github.com/user-attachments/assets/f88372c2-ddf8-442c-9410-b2131daef270)

How does this update sound? 

> Check your email at {{email}} for the link to set up an account password. By creating an account you agree to our Terms and Privacy policy.

**Comment by mikejolley** [comment]
@elizaan36 You want to combine the 2 sentences?

I raised https://github.com/woocommerce/woocommerce/pull/53558 with them separated like before.

**Comment by elizaan36** [comment]
Yes as long as they can stay on two (or three lines on mobile) comfortably. The two separate sentences and mixed bold and regular text create some imbalance.
