### ISSUE TITLE
[GlobalStep] PHP Fatal error displayed after clicking "Pay for Order" button with "4000002500003155" card on "Pay for order" page.

### ISSUE THREAD

**Issue by dmallory42** [woothemes/woocommerce#52990]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Bug Description:

**Note:** this issue was originally [discovered](https://github.com/Automattic/woocommerce-payments/issues/9760) during WooPayments beta testing, but after [investigation](https://github.com/Automattic/woocommerce-payments/issues/9760#issuecomment-2488089899) I believe it is a WC Core issue.

PHP Fatal error displayed after clicking "Pay for Order" button with "4000002500003155" card on "Pay for order" page.

### Environment:
Woocommerce Version: WooCommerce  9.5.0-beta.1
WooCommerce Payments: 8.6.0-test-1
WordPress version: v6.7

PC:
Windows 10,
Chrome(Version 131.0.6778.70)
Firefox (Version 132.0.2)

### Steps To Reproduce:
1. Create any test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.5.0-beta.1 plugin.
4. Install the version of WooCommerce Payments 8.6.0-test-1 plugin.
5. Complete WooCommerce Payments KYC flow.
6. Go to Shopper and add product to cart.
7. Purchase product with this card "4000000000000002" and error appear.
8. Navigate to My account -> Orders and click Pay button in Actions column for the latest order.
9. Select 'Use a new payment method'.
10. Add card "4000002500003155" with required details.
11. Click on "Pay for order".
12. Observe that, PHP Fatal error triggered after clicking 'Change payment method' button using new payment method on "My Account > Subscriptions" page.

### Instruction Link:
https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#pay-for-order

### Actual Result:
PHP Fatal error displayed after clicking "Pay for Order" button with "4000002500003155" card on "Pay for order" page.

### Expected Result:
Product should be purchased without any errors after clicking "Pay for Order" button with "4000002500003155" card on "Pay for order" page.

### Video:

![Image](https://github.com/user-attachments/assets/6f3ddf47-00ad-4f75-91b6-cd9a2a8cc392)

### Fatal Error Logs:
[#9760 Fatal error logs.txt](https://github.com/user-attachments/files/17817799/9760.Fatal.error.logs.txt)

Woocommerce bugs uploading format:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>Stack Trace</summary>

```
Fatal error: Uncaught Error: Call to a member function get_payment_method_details() on null
in /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Orders/PaymentInfo.php on line 124

Call stack:

Automattic\W\I\O\PaymentInfo::get_wcpay_card_info()
wp-content/plugins/woocommerce/src/Internal/Orders/PaymentInfo.php:39
Automattic\W\I\O\PaymentInfo::get_card_info()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:608
WC_Abstract_Order::get_payment_card_info()
wp-content/plugins/woocommerce/includes/class-wc-order.php:2353
WC_Order::add_order_item_totals_payment_method_row()
wp-content/plugins/woocommerce/includes/class-wc-order.php:2404
WC_Order::get_order_item_totals()
wp-content/plugins/woocommerce/templates/checkout/form-pay.php:20
include()
wp-content/plugins/woocommerce/includes/wc-core-functions.php:345
wc_get_template()
wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php:228
WC_Shortcode_Checkout::order_pay()
wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php:61
WC_Shortcode_Checkout::output()
wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php:72
WC_Shortcodes::shortcode_wrapper()
wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php:95
WC_Shortcodes::checkout()
wp-includes/shortcodes.php:434
do_shortcode_tag()
preg_replace_callback()
wp-includes/shortcodes.php:273
do_shortcode()
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters()
wp-includes/plugin.php:205
apply_filters()
wp-includes/post-template.php:256
the_content()
wp-content/themes/storefront/inc/storefront-template-functions.php:352
storefront_page_content()
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:348
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-content/themes/storefront/content-page.php:18
require()
wp-includes/template.php:812
load_template()
wp-includes/template.php:745
locate_template()
wp-includes/general-template.php:206
get_template_part()
wp-content/themes/storefront/page.php:24
include()
wp-includes/template-loader.php:106
require_once()
wp-blog-header.php:19
require()
index.php:17
```
</details>

### Expected behavior

A fatal error shouldn't occur 

### Actual behavior

A fatal error occurs when following the reproduction steps (tested on WooCommerce  9.5.0-beta.1) - I also tested on WooCommerce 9.4.2 and can confirm I don't see the same error.

### Steps to reproduce

1. Create any test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.5.0-beta.1 plugin.
4. Install the version of WooCommerce Payments 8.6.0-test-1 plugin.
5. Complete WooCommerce Payments KYC flow.
6. Go to Shopper and add product to cart.
7. Purchase product with this card "4000000000000002" and error appear.
8. Navigate to My account -> Orders and click Pay button in Actions column for the latest order.
9. Select 'Use a new payment method'.
10. Add card "4000002500003155" with required details.
11. Click on "Pay for order".
12. Observe that, PHP Fatal error triggered after clicking 'Change payment method' button using new payment method on "My Account > Subscriptions" page.

### WordPress Environment

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.30
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.14

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 21
product_variation: 7
revision: 1
shop_order_placehold: 11
wp_font_face: 36
wp_font_family: 12
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Query Monitor: by John Blackbourn – 3.16.4
WooPayments Dev Tools: by Automattic –
WooPayments: by WooCommerce – 8.6.0-test-1
WooCommerce: by Automattic – 9.5.0-beta.1

### Inactive Plugins (1) ###

WooCommerce Subscriptions: by WooCommerce – 6.9.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 MB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.6.0-test-1
Connected to WPCOM: Yes
WPCOM Blog ID: 239163809
Account ID: acct_1QMrS6CTCnHhCiIR
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Disabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2024-11-20 13:03:21 +00:00
Options: ✔
Notes: 63
Onboarding: skipped

### Action Scheduler ###

Canceled: 6
Oldest: 2024-11-19 13:43:33 +0000
Newest: 2024-11-19 14:19:58 +0000

Complete: 118
Oldest: 2024-11-19 13:03:26 +0000
Newest: 2024-11-19 14:22:14 +0000

Failed: 6
Oldest: 2024-11-19 13:39:12 +0000
Newest: 2024-11-19 14:18:49 +0000

Pending: 3
Oldest: 2024-11-19 15:53:30 +0000
Newest: 2024-12-19 13:47:22 +0000

### Status report information ###

Generated at: 2024-11-19 15:53:09 +00:00

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
Fixed by https://github.com/woocommerce/woocommerce/pull/53051
