### ISSUE TITLE
Woocommerce Rest API Search product by name

### ISSUE THREAD

**Issue by bevinGithub** [woothemes/woocommerce#52996]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I want to search a product by part of the name or full name i.e.based on title that contain a string, basically a simple search.
the search parameter does not work, I tested it on two sites and both not working.

here is a request url:
https://website.com/wp-json/wc/v3/products?search=product_name&consummer_key=****&consummer_secret=*****

Other api end points works except the search by product_name

### Expected behavior

Expect to get products that match partly or match full name being searched for using the end point
https://website.com/wp-json/wc/v3/products?search=product_name&consummer_key=****&consummer_secret=*****

### Actual behavior

Actual behaviour is returning empty result from the end point
https://website.com/wp-json/wc/v3/products?search=product_name&consummer_key=****&consummer_secret=*****

### Steps to reproduce

You will need to activate and generate the woocommerce rest api details. Replace the *** with the actual key and secret. then use the url of your website store and put your key and secret and search for a product name.

https://website.com/wp-json/wc/v3/products?search=product_name&consummer_key=****&consummer_secret=*****

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.fishingmania.co.za
Site address (URL): https://www.fishingmania.co.za
WC Version: 9.4.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: ❌ 6.6.2 - There is a newer version of WordPress available (6.7)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.30
PHP Post Max Size: 128 MB
PHP Time Limit: 90
PHP Max Input Vars: 2500
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.5.27-MariaDB-deb11
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.4.2
WC Database Prefix: wp_
Total Database Size: 98.88MB
Database Data Size: 70.79MB
Database Index Size: 28.09MB
wp_woocommerce_sessions: Data: 2.52MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
business_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
payments_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
support_queries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_active_auctions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atbdp_review: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cff_facebook_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cff_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cff_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cff_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_contact_owner: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_custom_favourites: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_custom_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_directorist_booking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mp_timetable_data: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.48MB + Index: 1.70MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 34.56MB + Index: 16.03MB + Engine InnoDB
wp_posts: Data: 12.50MB + Index: 3.73MB + Engine InnoDB
wp_pv_commission: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders7: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides7: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_simple_auction_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.25MB + Index: 0.31MB + Engine InnoDB
wp_terms: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcfm_daily_analysis: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_wcfm_detailed_analysis: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_enquiries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_enquiries_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_enquiries_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_enquiries_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_fbc_chat_rows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_fbc_chat_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_fbc_chat_visitors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_fbc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_following_followers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_marketplace_orders_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_product_multivendor: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_marketplace_refund_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_refund_request_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reverse_withdrawal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reverse_withdrawal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reviews_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reviews_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_review_rating_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_store_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_vendor_ledger: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_withdraw_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_withdraw_request_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_membership_subscription: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_messages: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_messages_modifier: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_messages_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_support: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_support_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_support_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_support_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcmp_cust_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcmp_cust_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcmp_products_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcmp_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcmp_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcmp_vendor_ledger: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcmp_vendor_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcmp_visitors_stats: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.41MB + Index: 0.42MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.38MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wishlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_guest_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcan_cache: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_indexable: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

at_biz_dir: 195
atbdp_fields: 5
atbdp_orders: 10
atbdp_pricing_plans: 2
attachment: 4723
cf_mega_menu: 8
custom_css: 2
customize_changeset: 8
efbl_skins: 3
elementor_library: 2
mc4wp-form: 2
member: 8
mif_skins: 1
nav_menu_item: 38
page: 59
post: 2
product: 1037
product_variation: 4792
revision: 739
shop_order: 31
swbdp-ad-manager: 1
testimonial: 5
wcfm_memberships: 2
wpcf7_contact_form: 8
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Livemesh Addons for WPBakery Page Builder: by Livemesh – 3.9.2
Beautiful and responsive cookie consent: by Beautiful Cookie Banner – 4.3.0
Better Search Replace: by WP Engine – 1.4.7
Brands for WooCommerce: by BeRocket – 3.8.4
Breadcrumb NavXT: by John Havlik – 7.3.1
PublishPress Capabilities: by PublishPress – 2.15.0
Classic Editor: by WordPress Contributors – 1.6.5
Classic Widgets: by WordPress Contributors – 0.3
Code Snippets: by Code Snippets Pro – 3.6.5.1
Contact Form 7: by Takayuki Miyoshi – 6.0
Content Aware Sidebars: by DEV Institute – 3.20
Directorist - Ads Manager: by wpWax – 2.1
Directorist - Business Hour: by wpWax – 3.3
Directorist - Claim Listing: by wpWax – 1.4.3
Directorist - Business Directory Plugin: by wpWax – 8.0.1
Duplicate Page: by mndpsingh287 – 4.5.4
Fishingmania Advanced Shortcodes: by Tigere Bevin Masevenza – 1.0
Fishingmania Shortcodes: by Tigere Bevin Masevenza – 1.0
Health Check & Troubleshooting: by The WordPress.org community – 1.7.1
WPBakery Page Builder: by Michael M - WPBakery.com – 7.7.2
JWT Authentication for WP-API: by Enrique Chavez – 1.3.4
ModelTheme Framework: by ModelTheme – 2.6
Paygate for WooCommerce: by Payfast (Pty) Ltd – 1.4.9
Pods - Custom Content Types and Fields: by Pods Framework Team – 3.2.8
Redux Framework: by Team Redux – 4.5.0
Slider Revolution: by ThemePunch – 6.7.13
Sassy Social Share: by Team Heateor – 3.3.69
User Menus: by Code Atlantic – 1.3.2
Converter for Media: by matt plugins - Optimize images by convert WebP & AVIF – 6.1.3
Checkout Field Editor for WooCommerce: by ThemeHigh – 2.0.6
WPC Smart Wishlist for WooCommerce: by WPClever – 4.9.5
WooCommerce Brands: by WooCommerce – 1.6.25 (update to version 1.7.7 is available)
WooCommerce: by Automattic – 9.4.2
WP Fastest Cache: by Emre Vona – 1.3.2
WP REST API Controller: by Evan Herman – 2.1.2
YITH WooCommerce Ajax Product Filter: by YITH – 5.5.0
YITH WooCommerce Wishlist: by YITH – 4.0.1

### Inactive Plugins (43) ###

Directorist - Compare Listing: by wpWax – 1.1.3
Directorist - Coupon: by wpWax – 1.1.0
Directorist - Listings FAQs: by wpWax – 1.3.0
Directorist - Live Chat: by wpWax – 1.3.1
Directorist - Mark as Sold: by wpWax – 1.1.2
Directorist - Paypal Payment Gateway: by wpWax – 1.4.0
Directorist - Post Your Need: by wpWax – 1.2.2
Directorist - Pricing Plans: by wpWax – 1.8.6
Directorist - Rank Featured Listings -beta: by Aazztech – 1.2.0
Directorist - Social Login: by wpWax – 1.2.0
Directorist - Stripe Payment Gateway: by wpWax – 2.3.1
Directorist - WooCommerce Pricing Plans: by AazzTech – 1.4.2
Directorist Booking: by wpWax – 1.4.3
Directorist Gallery: by wpWax – 1.3.1
Directorist Google reCAPTCHA: by wpWax – 1.3.1
Directorist Listings Slider & Carousel: by wpWax – 1.6.1
Directorist Listings with Map: by AazzTech – 1.4.0
Directorist Listings with Map: by wpWax – 1.6.0
Dokan: by weDevs – 3.13.1
Envato Market: by Envato – 2.0.11
Fishingmania Shortcodes: by Tigere Bevin Masevenza – 1.0
Flexy Breadcrumb: by PressTigers – 1.2.1
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.19
MultiVendorX: by MultiVendorX – 4.2.7
PayGate PayWeb for WooCommerce Migrator: by PayGate (Pty) Ltd – 1.4.4
Product Feed PRO for WooCommerce: by AdTribes.io – 13.3.9.1
Smash Balloon Custom Facebook Feed: by Smash Balloon – 4.2.6
Smash Balloon Instagram Feed: by Smash Balloon – 6.6.1
Store Exporter for WooCommerce: by Visser Labs – 2.7.3
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.10
WCFM - WooCommerce Frontend Manager: by WC Lovers – 6.7.14
WCFM - WooCommerce Multivendor Marketplace: by WC Lovers – 3.6.12
WCFM - WooCommerce Multivendor Membership: by WC Lovers – 2.11.5
WC Vendors Marketplace: by WC Vendors – 2.5.3
Widget Importer & Exporter: by ChurchThemes.com – 1.6.1
WooCommerce Remove Product Sorting: by SkyVerge – 1.2.0
WooCommerce Simple Auction: by wpgenie – 1.2.38
WordPress Importer: by wordpressdotorg – 0.8.3
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 4.0.0
WP All Import Pro: by Soflyy – 4.8.8
WP Instant Feeds: by mnmlthms – 1.3.4
YITH WooCommerce Social Login: by YITH – 1.4.8
Yoast SEO: by Team Yoast – 23.9

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.9.2

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: auction (auction)
external (external)
grouped (grouped)
listing_pricing_plans (listing_pricing_plans)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 166 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #9 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #10 - /my-account/
Terms and conditions: #6384 - /terms-conditions/

### Theme ###

Name: iBid
Version: 4.0.4
Author URL: https://modeltheme.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: ibid/woocommerce/archive-product.php
ibid/woocommerce/content-product.php version 3.6.0 is out of date. The core version is 9.4.0
ibid/woocommerce/content-single-product.php
ibid/woocommerce/global/quantity-input.php version 7.8.0 is out of date. The core version is 9.4.0
ibid/woocommerce/loop/add-to-cart.php version 3.3.0 is out of date. The core version is 9.2.0
ibid/woocommerce/loop/orderby.php
ibid/woocommerce/myaccount/form-login.php version 7.0.1 is out of date. The core version is 9.2.0
ibid/woocommerce/single-product/add-to-cart/grouped.php
ibid/woocommerce/single-product/add-to-cart/simple.php
ibid/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
ibid/woocommerce/single-product/product-image.php version 7.8.0 is out of date. The core version is 9.0.0
ibid/woocommerce/single-product/tabs/tabs.php
ibid/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-21 08:31:34 +02:00
Options: ✔
Notes: 117
Onboarding: completed

### Action Scheduler ###

Complete: 42
Oldest: 2024-10-21 05:29:47 +0200
Newest: 2024-11-20 13:44:35 +0200

Failed: 5
Oldest: 2024-06-25 16:18:22 +0200
Newest: 2024-07-18 10:43:22 +0200

Pending: 1
Oldest: 2024-11-21 13:44:35 +0200
Newest: 2024-11-21 13:44:35 +0200

### Status report information ###

Generated at: 2024-11-20 13:49:45 +02:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Unfortunately, we can't replicate so far.

- I see you checked the box confirming you performed basic troubleshooting (without other plugins), but just want to double-check this was done?
- Can you give an example of an actual search term and the corresponding product title you expect it to match?
- Can you navigate to **Tools ‣ Site Health ‣ Info** and check what database collation is in effect?

Thanks!
