### ISSUE TITLE
[CFE]: Fix "missing 'price' property in 'offers'" error in Google Search Console

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#53000]
### Which release does this request apply to?

9.5

### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/52871

### Why do these PRs need to break the code freeze?

In https://github.com/woocommerce/woocommerce/pull/52105 we updated the structured data of sale prices. That was done by moving the sale price and the regular price under `priceSpecification`, which allowed for both prices to be listed in the metadata. That was an SEO enhancement.

Even though the code from that PR passed the validator checks, after testing it in an online store, it caused Google Search Console to output an error and a warning. The error (`missing 'price' property in 'offers'`) is specially serious, as it might cause the products to be delisted from Google enriched results.

### What is the consequence if this exception does not get included?

Merchants might see their products removed from Google enriched results.

### What is the plan should defects to be discovered in these PRs ahead of final release?

I would say revert https://github.com/woocommerce/woocommerce/pull/52871 **AND** https://github.com/woocommerce/woocommerce/pull/52105. That would leave things as they were in 9.4.

### How should this change be communicated in the release post on the public developer blog:

Ensure all product enriched data required by Google is printed correctly in the product page.

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

Yes, please ping @dinhtungdu or anybody from Kirigami/Origami.

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.

**Comment by Aljullu** [comment]
> Think about how the bug escaped your team.

When reviewing #52105, I didn't think the [Google Search Console](https://search.google.com/test/rich-results) validator would be more strict than the [Schema Markup Validator](https://validator.schema.org/), which was the one mentioned in the PR testing steps.

> Write down ideas on how you could prevent this bug – for example, by writing automated tests, creating a new process, or updating documentation.

I opened a PR (https://github.com/woocommerce/woocommerce/pull/53001) adding a comment on top of the file mentioning that, when making changes, the generated markup needs to be tested in both tools.

> Make a plan with your team to implement the changes proposed above in order to catch the bug earlier next time and add the related tasks to your backlog.

PR already created.

**Comment by tammullen** [comment]
- [x] Escape analysis completed
- [x] PR merged to target release branch
- [x] PR cherry-picked to trunk
- [x] Followup issue if any
