### ISSUE TITLE
[Enhancement]: Create Add to Cart Form Wrapper Block

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#53008]
### Description
Develop the `Add to Cart Form` wrapper block that manages different block states based on the product type. This wrapper will ensure that the appropriate inner blocks are displayed according to the current state.

### Details
- **Functionality**
  - Serve as a container for all inner blocks of the Add to Cart Form.
  - Handle block states to render different content based on product types.

- **Implementation Considerations**
  - Maybe we can follow a similar approach as `useGetLocation()` from the Product Collection block and create a `useProductType()` hook for blocks to read the current product type in the editor. From [this comment](https://github.com/woocommerce/woocommerce/discussions/49799#discussioncomment-10221178).

```[tasklist]
### ACs
- [ ] Create the wrapper block structure and attributes.
- [ ] Implement the state management logic within the wrapper block.
- [ ] Ensure compatibility with multiple product types.
- [ ] Write tests to verify state handling and conditional rendering.
```

**Comment by retrofox** [comment]
`product-add-to-cart-with-options` for the folder name?

**Comment by helgatheviking** [comment]
Do you think this will be a new block entirely? Or a variation on the add to cart form block?
