### ISSUE TITLE
Store is "Live" by default on a fresh install of WooCommerce with core profiler skipped

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#53036]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In JN, when you create a new site, and install WC (current version is 9.4.2) and then navigate away from the onboarding page by typing a different URL in the address bar, notice that the Store defaults into Live mode. I was expecting it would default to "Coming soon" mode since it's a very fresh install of WC.

I read the [Default Behavior for Coming soon mode](https://woocommerce.com/document/configuring-woocommerce-settings/coming-soon-mode/#default-behavior) documentation and it appears that the scenario where the onboarding was "skipped" by navigating away via the address bar wasn't covered there. 

### Expected behavior

Store defaults to Coming Soon mode since it's just a very fresh WC install.

### Actual behavior

Store defaulted to Live mode.

### Steps to reproduce

1. Create a new JN site (although I observed this happening on other environments too like on a Google Cloud WP installation).
2. Go to the Plugins page and search for WooCommerce. Install and activate it.
3. As expected, you'll be taken to the beginning of the core profiler. Do not interact with any of the elements there. Navigate away from the core profiler by typing a different path onto the browser's address bar, like the WP Dashboard page (`/wp-admin/`) then hit Enter.
4. First indicator that the store is in Live mode: the "Live" badge in the top nav:

![Image](https://github.com/user-attachments/assets/44dfab92-0d31-4ef0-b2b3-0910318d32b7)

5. Open an incognito browser window and navigate to the shop page. Notice that you see the shop page loaded, instead of seeing the "Coming soon" page.

### WordPress Environment

JN site
WP 6.7
WC 9.4.2

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment]
> I read the [Default Behavior for Coming soon mode](https://woocommerce.com/document/configuring-woocommerce-settings/coming-soon-mode/#default-behavior) documentation and it appears that the scenario where the onboarding was "skipped" by navigating away via the address bar wasn't covered there.

Hey @adrianduffell Just to confirm, should we cover this scenario in the coming soon mode?  I feel like we should since it's a fresh site and user enter the onboarding page. 🤔

**Comment by adrianduffell** [comment]
> Just to confirm, should we cover this scenario in the coming soon mode?

@chihsuan, thanks for confirming. I think we could now default to coming soon mode at WooCommerce installation.

At launch, out of precaution we decided to use core profiler to set the coming soon mode. I agree it's unexpected to have the store live when Woo is installed now.

I think the installation defaults should be:

coming soon = yes
store pages only = yes

Then we would still have core profiler setting the values as it does now.

**Comment by chihsuan** [comment]
> I think the installation defaults should be:
> 
> coming soon = yes store pages only = yes
> 
> Then we would still have core profiler setting the values as it does now.

Sounds good!
