### ISSUE TITLE
[CFE]: Update DOMPurify to 2.5.7

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#53041]
### Which release does this request apply to?

9.5

### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/52961

### Why do these PRs need to break the code freeze?

It adds a security update to dompurify, which is used to sanitize HTML.

### What is the consequence if this exception does not get included?

The application will be slightly less secure.

### What is the plan should defects to be discovered in these PRs ahead of final release?

Revert this PR

### How should this change be communicated in the release post on the public developer blog:

There is no need for communication

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

@woocommerce/somewherewarm 

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.
- [x] I understand that I will need to merge the PR to the target `release` branch when my request is approved
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `trunk` when my request is approved

### Closing Checklist for Solaris

- [x] Escape analysis completed
- [x] PR merged to target `release` branch
- [x] PR cherry-picked to `trunk` (you can find the links in PR comments to verify)
- [x] Followup issue if any

**Comment by tammullen** [comment]
- [ ] Escape analysis completed
- [x] PR merged to target release branch
- [x] PR cherry-picked to trunk
- [ ] Followup issue if any

**Comment by tammullen** [comment]
Escape n/a in this instance as flagged in internal process
