### ISSUE TITLE
[Order confirmation/Delayed account creation] Notice for account creation is showing on order for shoppers registering via My account

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#53117]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a shopper registers via the My Account page and then places an order, they see a notice for successful account creation on the Order confirmation page. This happens for multiple orders in a row. 

### Expected behavior

The notice should not be visible, because the shopper already had the account created

### Actual behavior

When a shopper registers via the My Account page and then places an order, they see a notice for successful account creation on the Order confirmation page. This happens for multiple orders in a row. 

### Steps to reproduce

1. Go to `/wp-admin/admin.php?page=wc-settings&tab=account`
2. Select Account creation > On "My account" page setting; select Password by email
3. Go to `/my-account/` and create account
4. Place an order on the shop
5. See the notice below on the order confirmation page
6. Place another order, see the notice again![Image](https://github.com/user-attachments/assets/b324b847-ea32-4a40-896e-8e603bf42151)

### WordPress Environment

-

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
That notice seems to be controlled by the `default_password_nag` option, which is set when an account with generated password is created. I do think that:

- We should show the notice on the my account screen.
- We should flip that option to false once its been shown, not once a password is set.

@mikejolley for input.

**Comment by mikejolley** [comment]
@senadir I think the reminder is needed so perhaps it can be reworded to apply to both scenarios, or as you say, add a notice under my account as well. I don't think the notice should be hidden on display.

**Comment by senadir** [comment]
We might need to create yet another account creation source if we want to do so. But I agree

**Comment by senadir** [comment]
@mikejolley adding a notice in my account means we can skip the notice that shows up on order confirmation screen right?

**Comment by mikejolley** [comment]
@senadir Yeah that might make sense so they can check out the email first which has the same info.

**Comment by senadir** [comment]
Doing 2 distinct notices with 2 sign up flows (but not knowing from where the customer is created) makes this rather hard to fix without adding yet another user option, I'm unassigning for now as I don't want to bloat.

Essence is that I can't figure out (in Order placed screen) if an account was created via Checkout or my My account screen

**Comment by mikejolley** [comment]
We could reword the notice so it applies to both areas, and makes sense if its printed multiple times. e.g. "You need to confirm you account password xyz we sent you an email"

**Comment by senadir** [comment]
I have not tested that, but if you feel it make sense then let's go for it. But should that notice be dismissable?

**Comment by mikejolley** [comment]
@senadir I think it requires separate user action and that action is required, so I don't think it should be dismissed.

**Comment by ralucaStan** [comment]
The notice text works better but I'd like to challenge a bit the fact that we show that notice on the order screen.

When I create an account on the My account page, with email sent password, the next screen I see when after I click register is the My account area. I think this notice should be shown here and not on the order page. 

@mikejolley is it possible to remove that notice from the order page and show it in the my account section until the shopper picks a password?

**Comment by ralucaStan** [comment]
On the My Account page it shouldn't be dismissable.

**Comment by mikejolley** [comment]
@ralucaStan Thats probably sensible. I think this came from the designs, but we already have a big confirmation message after creating the account so this one is probably not required too.

We can build this into the shortcode and remove from the block.

**Comment by mikejolley** [comment]
With delayed account creation we show a confirmation message within the order confirmation page, and log the user in. They would only see this notice if they refreshed or came back at a later date. So I think this notice is not needed here and can be removed.

On the My Account page you are also logged in automatically. There are links to the edit password screen, but this requires the current password (which the user does not know). Therefore this is where the nag is needed. I'll raise the PR again with the notice on the account screen.
