### ISSUE TITLE
[CFE]: Fix woocommerce_reports_charts filter

### ISSUE THREAD

**Issue by tomalec** [woothemes/woocommerce#53137]
### Which release does this request apply to?

9.5

### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/53126

### Why do these PRs need to break the code freeze?

A PR included in 9.5 (https://github.com/woocommerce/woocommerce/pull/51592) broke an existing filter.

### What is the consequence if this exception does not get included?

`woocommerce_reports_charts` filter will not be working at all, potentially breaking existing extensions (5 known).

### What is the plan should defects to be discovered in these PRs ahead of final release?

Fix if possible, or rever this PR requiring 3PDS to replace `woocommerce_reports_charts` with `woocommerce_admin_reports`

### How should this change be communicated in the release post on the public developer blog:

No, as it fixes something broken in 9.5 only.

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

@mikkamp 

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.
- [x] I understand that I will need to merge the PR to the target `release` branch when my request is approved
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `trunk` when my request is approved

### Closing checklist for Solaris

- [ ] Escape analysis completed
- [x] PR merged to target `release` branch
- [x] PR cherry-picked to `trunk` (you can find the links in PR comments to verify)
- [ ] Followup issue if any

**Comment by tammullen** [comment]
@tomalec Reminder to do an escape analysis for this

**Comment by tomalec** [comment]
### Escape analysis

#### Investigation
While fixing a bug with Analytics & reports filters, colliding names (`woocommerce_admin_reports`) https://github.com/woocommerce/woocommerce/issues/36737,
I accidentally introduced a new one for the legacy version of it in reports - `woocommerce_reports_charts`.
It was just an oversight of when the backward compatibility code was executed. 

It was spotted during beta testing at https://github.com/woocommerce/woocommerce/issues/52910.

The issue could have been avoided if we had tested all the filters.
However, as we're working on new analytics solution, while having the current one, then the deprecated-for-years legacy reports, and having legacy filters even there... writing tests for them does not seem a priority.


#### Why did it have to break the CF?
As already stated, the future is so long deprecated, and the workaround is easy; we may consider it not enough of a priority to bother.
However, as I checked, at least 5 known extensions were using that filter, plus breaking the filter could also affect some customizations. Also, the old legacy-legacy (`woocommerce_reports_charts`) filter didn't have the collision problem, so it is useful for distinguishing between both cases. This could work well for older versions of WC and the 9.5+.
