### ISSUE TITLE
Block Checkout - Force Shipping Address Fields for Virtual Products

### ISSUE THREAD

**Issue by jmccall75** [woothemes/woocommerce#53148]
Using WooCommerce Blocks checkout, I need to always display shipping address fields, even when cart contains only virtual products. Current filters and methods attempted:

`woocommerce_cart_needs_shipping`
`woocommerce_cart_needs_shipping_address`
JavaScript dispatch methods

Environment:

WooCommerce version: 9.4.2
WordPress version: 6.7.1
Active theme: Authentic

Specific Behavior Needed:

Shipping address fields must be visible
Works for carts with virtual-only products
Compatible with WooCommerce Blocks checkout

Expected Outcome:
Both billing and shipping address forms always displayed, regardless of cart contents.
Tried Solutions:

PHP filters to force shipping
JavaScript dispatchers
Custom Store API modifications

Request: Can you provide a definitive method to always show shipping address fields in block-based checkout?

**Comment by senadir** [comment]
Using the `woocommerce_cart_needs_shipping` filter works fine for me, what problem are you facing?

Billing/Shipping addresses won't be both displayed at the same time, billing will be synced with shipping and customers can untoggle them.

**Comment by jmccall75** [comment]
OMG, you are totally right. I hadn't yet configured a shipping method. That turns out to be the problem. :(
