### ISSUE TITLE
[PRR]: Fix search in Installed Plugins page

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#53198]
### Which release does this request apply to?

9.4

### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/53196

### Why does this PR need a point release?

The search functionality of the Installed Plugins is broken

### What is the consequence if this fix not being included in the point release (if any)? e.g. number of users affected and how they are affected

All users will be affected while using the search functionality in the Installed Plugins page

### What is the plan should defects to be discovered in these PR after the point release?

We will need to make another fix, as reverting this would just leave us with the original issue

### How should this change be communicated in the release post on the public developer blog: cc @woocommerce/developer-advocacy

There is no need

### Is there a workaround to the issue? If yes, how should we communicate it on the (public developer blog)[https://developer.woo.com/blog/]?

No

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

@woocommerce/somewherewarm 

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.
- [x] I understand that I will need to merge the PR to the target `release` branch when my request is approved
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `trunk`
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `frozen release` branch

### Closing checklist for Solaris

- [ ] Escape analysis completed
- [ ] PR merged to target `release` branch
- [ ] PR cherry-picked to `trunk` (you can find the links in PR comments to verify)
- [ ] PR merged to frozen `release` branch
- [ ] Followup issue if any

**Comment by nathanss** [comment]
# Escape Analysis

It is very tricky to ensure the quality of a code that runs in multiple contexts. We try to be as defensive as possible, but sometimes we assume things and cause fatal errors. In this case, we assumed that the global `$wp_list_table` would always be defined in the context of the code, which was not true. This could theoretically be detected in code review. 

I also think the plugin page doesn't have any E2E tests from WooCommerce end, since it's part of WordPress core, but this could also be considered.

**Comment by tammullen** [comment]
> Please switch the base to trunk and merge your PR.

Ignore this and in this instance please switch the base to 9.5 and raise a CFE for 9.5 instead
