### ISSUE TITLE
[e2e tests] Multisite environments compatibility

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#53197]
Update the e2e and api tests so that we can easily run them a in multisite environment.

Definition of done:

With a multisite setup with a site URL like `https://my-site.com/store1`:

1. Running `pnpm test:e2e` against the above URL all tests will pass and not code updates are required
2. Running `pnpm test:api` against the above URL all tests will pass and not code updates are required

**Comment by nigeljamesstevenson** [comment]
Looking at this related PR:
[[e2e-tests] Update URLs across tests for multisite setup compatibility](https://github.com/woocommerce/woocommerce/pull/53228#top)
there has been activity in the last week. I am adding this comment so it is not being flagged in error during sweep

**Comment by adimoldovan** [comment]
Most of the issues were fixed. Any remaining fixes will be handled by https://github.com/woocommerce/woocommerce/issues/53712.
