### ISSUE TITLE
[Enhancement]: Implement the product type selector for the Wrapper block

### ISSUE THREAD

**Issue by retrofox** [woothemes/woocommerce#53207]
We need to figure out how to implement a product type select at Wrapper block level.
The idea, through the UI, is that the user should be able to switch between the different product types to see how the block representation could change according to it.

Depends on #53008

```[tasklist]
### Issues
- [ ] https://github.com/woocommerce/woocommerce/pull/53354
- [ ] https://github.com/woocommerce/woocommerce/issues/53365
- [ ] https://github.com/woocommerce/woocommerce/issues/53479
- [ ] https://github.com/woocommerce/woocommerce/issues/53389
```

**Comment by Aljullu** [comment]
Closing this as completed.
