### ISSUE TITLE
[Blocks] The 'useSelect' hook returns different values when called with the same state and parameters. This can lead to unnecessary rerenders

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#53218]
Visiting `wp-admin/site-editor.php` triggers multiple warnings:

https://github.com/user-attachments/assets/fc9d4093-7b48-41c3-b8f3-2aae0b4d8e3d

```
index.js:163 The 'useSelect' hook returns different values when called with the same state and parameters. This can lead to unnecessary rerenders. Error Component Stack
    at AddToCartButton (block.tsx:31:2)
    at div (<anonymous>)
    at Block (block.tsx:132:10)
    at with-product-data-context.js:61:51
    at div (<anonymous>)
    at Disabled (index.tsx:62:2)
    at div (<anonymous>)
    at Edit (edit.tsx:68:2)
```

Steps to Reproduce:
- Navigate to `wp-admin/site-editor.php`.
- Observe the warnings that appear.

**Comment by tjcafferkey** [comment]
@gigitux do we know what data is different? I suspect it could be related to this issue (https://github.com/woocommerce/woocommerce/issues/53181) since I suspect they use the same context `<ProductDataContextProvider>`

**Comment by gigitux** [comment]
Checking the stack trace, it mentions `with-product-data-context.js`, so maybe you're right! I didn't check in-depth.

**Comment by tjcafferkey** [comment]
When I was doing some brief digging into the code I noticed that `clientId` was different every return. Dont know if this is the reason but highlighting incase, I didnt dig any deeper at the time.

**Comment by gigitux** [comment]
I'm closing this issue in favor of https://github.com/woocommerce/woocommerce/issues/53849
