### ISSUE TITLE
Product page category list selection issue.

### ISSUE THREAD

**Issue by asp111** [woothemes/woocommerce#53254]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,

The categories selection on the product page is not working properly. I noticed for one of the categories when trying to select it, then many other categories get auto-selected. I have a video of the bug attached here. When I crosscheck the IDs of all these categories which are getting auto-selected has a common ID number of all of them in front. So the problem is when we select category with ID 28 then it selects all other categories whose ID starts with 28... Example: 281, 285, 287, 2882, etc.

Please also note this is happening to only this category with ID: 28, I have tested with other categories eg: ID: 32 and its counter part IDs like 321, 324, 328 etc and they all seem to be working normally. 

Also note, I'm also getting the same bug when testing on local environment, with only woocmmerce plugin active and storefront theme active. I have to use the database of my website so I get the categories as structured.

## Video bug
https://github.com/user-attachments/assets/33b053c5-d89b-4049-857e-6f1cb0e47b33

### Expected behavior

It should only select the required category

### Actual behavior

Various categories are getting auto-selected when selecting the one category.  It seem like some JS selection bug

### Steps to reproduce

1. Go to the product edit page
2. Select the category that you want to select
3. Once you select the category, other unnecessary categories will be selected. (This only happens if categories share the same ID at the front 
 with ID 28 in my case)

### WordPress Environment

`
### WordPress Environment ###

WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –e
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Debian)
PHP Version: 8.2.20
PHP Post Max Size: 1 GB
PHP Time Limit: 600
PHP Max Input Vars: 12000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.34-MariaDB-1:10.4.34+maria~deb10-log
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @asp111! Thanks for reporting the issue and I am sorry you are having trouble with product categories. I've assigned an engineering team responsible for this area so they will take a look and respond here soon. However, I noticed that you are using a very old WooCommerce version (in your System Status Report). You are using 8.3.1 but our current version is 9.4.2. You are using a version that is moe than 1 year old. Are there any reasons you are not updating to the newer version? It is expected that older versions have bugs but most importantly you are missing out on many security updates we had since.

**Comment by cubehrends** [comment]
We are experiencing the same issue. When selecting the product category "in-product_cat-44-1," all subcategories matching the pattern "in-product_cat-44XX-X" are also being selected automatically.

**Comment by kunzi** [comment]
Same issue here with most recent WP and Woo.

**Comment by asp111** [comment]
> Hi [@asp111](https://github.com/asp111)! Thanks for reporting the issue and I am sorry you are having trouble with product categories. I've assigned an engineering team responsible for this area so they will take a look and respond here soon. However, I noticed that you are using a very old WooCommerce version (in your System Status Report). You are using 8.3.1 but our current version is 9.4.2. You are using a version that is moe than 1 year old. Are there any reasons you are not updating to the newer version? It is expected that older versions have bugs but most importantly you are missing out on many security updates we had since.

Hi @juliaamosova, yes there is the reason we kept the old version still as we are waiting for a plugin update compatible with latest version of WC. As @kunzi found, there is the same issue with the most recent version, so this needs attention.

For now, I have a workaround to get this fixed, I created a new category, then assigned all the products from old(problematic category) to this new category and deleted the old category. So now the issue is sorted for main category with ID: 28. However, now we found the same issue in 4 other categories. A fix would be appreciated if anyone could help. Thanks

**Comment by flashjunkie** [comment]
It seems this may go beyond WC. I have Easy Digital Downloads and we are experiencing the exact same bug, it seems to be related to the javascript for the category selector which to my understanding is wordpress core code?

**Comment by chipweb** [comment]
Hello, the same thing is happening to us: https://www.loom.com/share/00c39468780548d49cccd7d6f82e17ae

**Comment by SpeedBlur** [comment]
I'm also experiencing this issue - my current work around is to use Quick Edit on each product, seems to work with no glitch.

**Comment by jaxr** [comment]
9169492-zen is affected by this

**Comment by LightBlackGit** [comment]
Same Issue here

**Comment by wpniall** [comment]
9171049-zen is affected as well.

**Comment by fetenlakhal** [comment]
9171830-zen

**Comment by daniyalahmadk** [comment]
9161753-zen

**Comment by LightBlackGit** [comment]
anyone here to provide support on this issue?

**Comment by louwie17** [comment]
@asp111 thanks for creating the issue, I was also able to reproduce this locally on a test site. I did some digging and it turns out that issue stems from WordPress ( around [this logic](https://github.com/WordPress/wordpress-develop/blob/6.7/src/js/_enqueues/admin/post.js#L657-L667) )
I believe it was caused by the fix implemented for this issue: https://core.trac.wordpress.org/ticket/62440
They have already addressed it in WordPress as part of this issue: https://core.trac.wordpress.org/ticket/62504 and should get released as part of WordPress `6.7.2`.

I am going to close this to avoid confusion. Feel free to re-open if the issue persists in WP 6.7.2.
