### ISSUE TITLE
WooCommerce does not display Shop page properly when it is set to Homepage in Wordpress

### ISSUE THREAD

**Issue by kurtgschumacher** [woothemes/woocommerce#53289]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the Shop page is set to the Homepage in the WordPress Reading setting, when the site is loaded it displays a page titled "Shop" with no content.

I don't know if this related or if I should open a new incident, but when I go to WooCommerce > Settings > Advanced there is no dropdown shown for the Shop page.

### Expected behavior

When the Homepage is set to the Shop page the site should display the actual Shop page.

The WooCommerce advanced settings should display a dropdown for the Shop page.

### Actual behavior

When the Homepage is set to the Shop page the site displays a page titled Ship with no content.

There is no dropdown for the Shop page in the WooCommerce Advanced settings.

### Steps to reproduce

1. Install WordPress
2. Install WooCommerce
3. Add a simple product
4. Go to WP Settings > Reading and set the Homepage to the Shop page
5. Open the site. It displays a page titled Shop with no content.
6. Go to thesite.com/shop. It should display the Shop page with the product that was added

Also:
Go to WooCommerce > Settings > Advanced. There is no dropdown to set the Shop page.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ❌ To allow logging
make /home/carryon/public_html/staging/wp-content/uploads/wc-logs/ writable.

WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.26
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.40
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 3
page: 7
post: 2
product: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.4.2

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 0 B

### WC Pages ###

Shop base: #7 - /
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/carryon/public_html/staging/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/carryon/public_html/staging/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/carryon/public_html/staging/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-29 20:41:18 +00:00
Options: ✔
Notes: 56
Onboarding: -

### Action Scheduler ###

Complete: 5
Oldest: 2024-11-28 20:42:44 +0000
Newest: 2024-11-28 21:05:59 +0000

Failed: 1
Oldest: 2024-11-28 20:43:16 +0000
Newest: 2024-11-28 20:43:16 +0000

Pending: 1
Oldest: 2024-11-29 20:42:44 +0000
Newest: 2024-11-29 20:42:44 +0000


### Status report information ###

Generated at: 2024-11-28 21:25:29 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kurtgschumacher** [comment]
![Image](https://github.com/user-attachments/assets/dd936b0b-1b86-41b4-9850-fb2061ce432e)
![Image](https://github.com/user-attachments/assets/963abe5d-4beb-463f-ab47-a00478b0f92c)
![Image](https://github.com/user-attachments/assets/7be6149d-4c4c-4d5a-bb9e-c70daf97062a)
![Image](https://github.com/user-attachments/assets/e6379955-ea2a-4e1e-abe8-b4899263d1a5)

**Comment by Aljullu** [comment]
Thanks for reporting this, @kurtgschumacher! Would you mind trying again with WooCommerce 9.5? If I'm not wrong, this was fixed in https://github.com/woocommerce/woocommerce/pull/51626.

**Comment by kurtgschumacher** [comment]
> Thanks for reporting this, [@kurtgschumacher](https://github.com/kurtgschumacher)! Would you mind trying again with WooCommerce 9.5? If I'm not wrong, this was fixed in [#51626](https://github.com/woocommerce/woocommerce/pull/51626).

You are not wrong, it is fixed in 9.5.1. I had circumvented the problem by setting the Home page that immediately redirected to the Shop page.

However, there is still no way to specify the Shop page in WooCommerce > Settings > Advanced. Should I open a separate incident on that so that this one can be closed out?

**Comment by Aljullu** [comment]
> You are not wrong, it is fixed in 9.5.1. I had circumvented the problem by setting the Home page that immediately redirected to the Shop page.

Good to hear that it's solved in 9.5.1 and that you found a work-around before it! 🙂 

> However, there is still no way to specify the Shop page in WooCommerce > Settings > Advanced. Should I open a separate incident on that so that this one can be closed out?

The option to select which page is the _Shop_ page is under WooCommerce > Settings > Products. Does it work for you?

**Comment by kurtgschumacher** [comment]
> The option to select which page is the _Shop_ page is under WooCommerce > Settings > Products. Does it work for you?

D'oh! When I looked up how to set the shop page, everything I found said to go to Settings > Advanced. That's one of the major problems with the Web. Things get posted and become obsolete. A product's user interface is changed and no one updates their docs pages.

Thanks again, closing this incident.

**Comment by Aljullu** [comment]
Good to hear that it worked! Yes, sometimes the information on the web might be misleading. 😄  I will go ahead and close this issue. 👍
