### ISSUE TITLE
Product Collection: `RegisterProductCollection` does not recognize align & layout attributes

### ISSUE THREAD

**Issue by Andrew-Starr** [woothemes/woocommerce#53287]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Product Collection block supports the align and layout attributes, but when registering a custom product collection with `__experimentalRegisterProductCollection` the align and layout attributes are not passed to the product collection block.

```
wc.wcBlocksRegistry.__experimentalRegisterProductCollection( {
	name: 'woocommerce/product-collection/themeslug-product-collection',
	title: __( 'Just a Test', 'themeslug'),
	scope: ['block'],
	attributes:
	{
		displayLayout: {
			type: 'flex',
			columns: 4,
			shrinkColumns: true
		},
		query: {
			perPage: 4,
			pages: 1
		},
		align: 'full',
		layout: {
			type: 'constrained'
		}
	},
	innerBlocks:[
		[
			'woocommerce/product-template',
			{},
			[
				[
					'woocommerce/product-image',
					{
						'imageSizing': 'thumbnail',
						'isDescendentOfQueryLoop': true
					},
					[]
				],
				[
					'core/post-title',
					{
						'textAlign': 'center',
						'level': 3,
						'isLink': true,
						'fontSize': 'medium',
						'__woocommerceNamespace': 'woocommerce/product-collection/product-title'
					},
					[]
				],
				
			]
		]
	]
} );
```

In the example above, one would expect the block to be displayed full-width after selecting the "Just a Test" product collection, but it is displayed in the default width.

### Expected behavior

The block should be initially displayed with the defined width, as the block does support the alignment attribute.

### Actual behavior

The alignment attribute is not recognized.

### Steps to reproduce

1. Add the above example code to a theme or plugin.
2. Add a Product Collection block to a new page or post.
3. In the Choose Collection select "Just a Test" custom product collection.
4. Notice that the block is displayed in the default width, when it should be full width.

### WordPress Environment

.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by imanish003** [comment]
Hi @Andrew-Starr, Thanks for reporting this issue. I verified that the align and layout attributes are not passed to the product collection block. After [looking at the code](https://github.com/woocommerce/woocommerce/blob/db81bf0925a4f5802128f7051faf1cab99666070/plugins/woocommerce-blocks/assets/js/blocks-registry/product-collection/register-product-collection.tsx#L377-L423), I can see that we are selectively passing the attributes to the product collection block, which doesn't include align and layout attributes. I will create a PR to fix this.

**Comment by imanish003** [comment]
**Update:** I have created PR #53785 to fix issue. Thanks again for reporting this issue.
