### ISSUE TITLE
[Enhancement]: Develop a mechanism for persisting payment selection

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#53306]
### Describe the solution you'd like

We recently reverted https://github.com/woocommerce/woocommerce/pull/52044 because it affected stores using Square and potentially other payment plugins that rely on DOM-based selection for payment methods.

A public API (__internalSetActivePaymentMethod) exists but is marked as internal and not documented for external use. Plugins should be encouraged to use this or similar data store mechanisms instead of DOM hacks.

We need to evaluate if making the `__internalSetActivePaymentMethod` public is the best way to persisting payment selection.

### Additional context

https://github.com/woocommerce/woocommerce/issues/53088
p1732214845206319-slack-C8X6Q7XQU

**Comment by senadir** [comment]
The title and beyond seems mismatching for me. `__internalSetActivePaymentMethod` is only client side, and basically is similar to a click event on a payment radio button. The title seems to indicate we want so save server side

**Comment by ralucaStan** [comment]
Closing this, as [#42079](https://github.com/woocommerce/woocommerce/issues/42079) will enable us to persist the payment selection.

A separate discussion about making `__internalSetActivePaymentMethod` should happen outside this ticket.
