### ISSUE TITLE
[Enhancement]: Author name for products admin columns

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#53324]
### Describe the solution you'd like

Hi crocoblock team,

It would be great if we could see the name of the user publishing the products on the products page.

### How does this help?

We have 3 employees who publish on the product website. An employee makes a lot of mistakes when uploading products. When the product author name is visible, we can easily identify the employee who is making mistakes when uploading products.

### Describe alternatives you've considered

Currently, I am using the JetEngine plugin for admin columns to address this need.

**Comment by lanej0** [comment]
Hi @79ho3ein 

You can already do this with an edit to your theme's functions.php file.  Something like this should do what you need:

```php
add_action( 'woocommerce_single_product_summary', 'display_product_author_name', 6 );

function display_product_author_name() {
    global $post;

    // Get the author's display name
    $author_name = get_the_author_meta( 'display_name', $post->post_author );

    // Output the author's name
    if ( $author_name ) {
        echo '<p class="product-author">Published by: ' . esc_html( $author_name ) . '</p>';
    }
}
```
