### ISSUE TITLE
Review /activate-and-setup folder

### ISSUE THREAD

**Issue by Stojdza** [woothemes/woocommerce#53329]
Review tests in the tests/e2e-pw/tests/activate-and-setup folder and add tags and/or todo comments to follow-up.

Use this guide: pdV5qK-Ie-p2#comment-1212

**Comment by rodelgc** [comment]
~~Initial list of candidates for tagging are marked as "Yes" in the `activate-and-setup` sheet in this [spreadsheet](https://docs.google.com/spreadsheets/d/1YcIP5FpFIunHC7xnNJsdFzlU_lBVkFe8wSySqZFEbnU/edit?usp=sharing).~~

We are now using a different approach to tagging the tests, so I'm crossing out the statement above to prevent confusion.
