### ISSUE TITLE
[Enhancement]: New login / account creation logic before checkout

### ISSUE THREAD

**Issue by bwafels** [woothemes/woocommerce#53320]
### Describe the solution you'd like

As a wholesale business I want people to login before they reach their checkout page. 
So Cart > log in (if not logged in) > Checkout.
This is important as account details need to be correct every time for accounting reasons.
I do not understand why this is not an option. Should be an easy add. Selecting account creation boxes or hoping for correct info is not ok for our business.

Now I need a plugin to do this: https://wordpress.org/plugins/woo-force-authentification-before-checkout/

Discussion about it: https://wordpress.org/support/topic/default-option-to-log-in-before-checkout/

### Additional context

I needed to ask again as for some reason the plugin stopped working comming from Woo 9.3.3 to 9.4.2
I have no idea why as it is a really simple coded plugin. The only thing I have is that I do not use the payment gateways from Woocommerce (wholesales is payed after delivery) and I use a snippet: add_filter('woocommerce_cart_needs_payment', '__return_false');

I there is any other way to get if working again I can upgrade Woocommerce

**Comment by lanej0** [comment]
Hi @bwafels,

You'll have to get in touch with the author of that plugin for support.  We don't work on that plugin, so we don't have access to make updates/bug fixes.  The best way to contact their support is here: https://wordpress.org/support/plugin/woo-force-authentification-before-checkout/
