### ISSUE TITLE
Review /admin-analytics folder

### ISSUE THREAD

**Issue by Stojdza** [woothemes/woocommerce#53330]
Review tests in the tests/e2e-pw/tests/admin-analytics folder and add tags and/or todo comments to follow-up.

Use this guide: pdV5qK-Ie-p2#comment-1212

**Comment by rodelgc** [comment]
Initial list of candidates for tagging are marked as "Yes" in the `admin-analytics` sheet in this [spreadsheet](https://docs.google.com/spreadsheets/d/1YcIP5FpFIunHC7xnNJsdFzlU_lBVkFe8wSySqZFEbnU/edit?usp=sharing).
