### ISSUE TITLE
Review /api-tests folder

### ISSUE THREAD

**Issue by Stojdza** [woothemes/woocommerce#53333]
Review tests in the tests/e2e-pw/tests/api-tests folder and add tags and/or todo comments to follow-up.

Use this guide: pdV5qK-Ie-p2#comment-1212

**Comment by adimoldovan** [comment]
Reviewed all tests in the `api-tests` folder. 
While there are many improvements that we can bring to these tests, none would apply to the scope of this project. We can leave them as they are, run all of them as they are fast and stable enough for that.
