### ISSUE TITLE
[PRR]: Fix CYS with latest Gutenberg Nightly

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#53356]
### Which release does this request apply to?

9.4

### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/53352

### Why does this PR need a point release?

[CYS is broken with the latest Gutenberg nightly](https://href.li/?https://github.com/woocommerce/woocommerce/issues/52617). If nothing changes, it will likely also be incompatible with Gutenberg 19.9 when it’s released in December 18th. The reason is that an experimental React component we are using now requires an additional prop. If that prop isn't passed, a JS error occurs causing all the app to crash.

### What is the consequence if this fix not being included in the point release (if any)? e.g. number of users affected and how they are affected

All users onboarding into WooCommerce and going through the CYS flow will encounter a broken experience and won’t be able to complete the CYS process.

### What is the plan should defects to be discovered in these PR after the point release?

While the PR could be reverted, without it the CYS flow is completely broken with the latest Gutenberg. So ideally we should find an alternative solution.

### How should this change be communicated in the release post on the public developer blog: cc @woocommerce/developer-advocacy

Adapting a changelog like this:

> Fix a CYS error with the upcoming Gutenberg release

### Is there a workaround to the issue? If yes, how should we communicate it on the (public developer blog)[https://developer.woo.com/blog/]?

Uninstalling or downgrading Gutenberg to a version prior to 19.9.

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

@mdperez86 @gigitux and Team Kirigami and Origami

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.
- [x] I understand that I will need to merge the PR to the target `release` branch when my request is approved
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `trunk`
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `frozen release` branch

### Closing checklist for Solaris

- [ ] Escape analysis completed
- [ ] PR merged to target `release` branch
- [ ] PR cherry-picked to `trunk` (you can find the links in PR comments to verify)
- [ ] PR merged to frozen `release` branch
- [ ] Followup issue if any

**Comment by Aljullu** [comment]
This is very similar to a CFE we had to do a few weeks ago: pf59Ax-2dt-p2.

## Think about how the bug escaped your team.

Technically the bug didn't escape our team. We are using experimental APIs so it's expected they will break with new Gutenberg releases. The bug was correctly caught by our automated testing, which gave us some time to fix it and (hopefully) include the fix in a WC release before Gutenberg 19.9 is shipped.

## Write down ideas on how you could prevent this bug – for example, by writing automated tests, creating a new process, or updating documentation.

Using experimental APIs in our code base is likely to cause this kind of issue, where we need to rush a release because of a change in Gutenberg.

## Make a plan with your team to implement the changes proposed above in order to catch the bug earlier next time and add the related tasks to your backlog.

There is an ongoing discussion in the Gutenberg repo with the goal of offering a safe system for 3rd-parties to use unstable APIs from Gutenberg: https://github.com/WordPress/gutenberg/issues/66197.

**Comment by tammullen** [comment]
> Please switch the base to trunk and merge your PR.

Ignore this and in this instance please switch the base to 9.5 and raise a CFE for 9.5 instead
