### ISSUE TITLE
Stepper input style is corrupted when form has additional fields

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#53359]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the quantity input stepper feature is enabled and the product is Name Your Price (or presumably any other form field is displayed) then the CSS layout responsible for the plus/minus buttons doesn't work as expected (because it's including other inputs)

### Expected behavior

The quantity, steppers, and add to cart button should align no matter what additional fields are displayed

### Actual behavior

Alignment is broken, see the screenshot

![Image](https://github.com/user-attachments/assets/b2e11dc0-632c-41a6-891a-2119395cc71e)

### Steps to reproduce

1. Create a name your price simple product (or possibly also a simple product with a product addon)
2. Display that product in a single product block somewhere
3. enable the stepper inputs feature and turn it on for this block

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

truncated-
```

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by imanish003** [comment]
Hi @helgatheviking, Thanks for reporting this issue. I've created a PR to fix it -- [Fix stepper input style is corrupted when form has additional fields #53782](https://github.com/woocommerce/woocommerce/pull/53782).
