### ISSUE TITLE
[WC Payments NOX] Redirect from get paid task and payments menu item to the settings page rather than wcpay welcome page

### ISSUE THREAD

**Issue by oaratovskyi** [woothemes/woocommerce#53379]
### Description
when WooPayments is not active:
- Redirect from payments menu item to the Payments settings page rather than payments task page
- Redirect from get paid task to the Payments settings page.
- Redirect from the Set up additional payment options task to the Payments settings page.

![Image](https://github.com/user-attachments/assets/54519004-d0e2-44d0-8305-0840cdfb8deb)

### Dev notes
Only if the feature flag is on!

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Dev notes
Reactifying the Payments settings page: pe4Hk0-1ly-p2
Populate react-powered main payments settings screen PR: https://github.com/woocommerce/woocommerce/pull/50825

### Additional context
PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

**Comment by vladolaru** [comment]
I updated the specs to exclude WooPayments incentive. The Payments NOX can show incentives, so we don't need to point to the current WCPay Welcome Page.
