### ISSUE TITLE
[Fatal] Uncaught Error: Call to undefined function wc_get_container() | `OrderUtil.php`

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#53434]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed this fatal error from WooCommerce 9.4.2.

[Link to code](https://github.com/woocommerce/woocommerce/blob/a1ea4258250b0b434508fbfb027be5ac65718eb1/plugins/woocommerce/src/Utilities/OrderUtil.php#L35-L36)

```
PHP Fatal error:  Uncaught Error: Call to undefined function Automattic\WooCommerce\Utilities\wc_get_container() in /wordpress/plugins/woocommerce/9.4.2/src/Utilities/OrderUtil.php:36
Stack trace:
#0 [...]/wp-content/plugins/gtm-ecommerce-woo/src/Util/WooCommerceFeaturesUtil.php(9): Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled()
#1 [...]/wp-content/plugins/gtm-ecommerce-woo/src/Service/OrderMonitorService.php(85): GtmEcommerceWoo\Lib\Util\WooCommerceFeaturesUtil::isHposEnabled()
#2 [...]/wp-content/plugins/gtm-ecommerce-woo/gtm-ecommerce-woo.php(41): GtmEcommerceWoo\Lib\Service\OrderMonitorService->initialize()
#3 /wordpress/core/6.7.1/wp-settings.php(526): include_once('[...]/wp-...')
#4 [...]/wp-config.php(83): require_once('/wordpress/core...')
#5 /wordpress/core/6.7.1/wp-load.php(55): require_once('[...]/wp-...')
#6 /wordpress/core/6.7.1/wp-blog-header.php(13): require_once('/wordpress/core...')
#7 /wordpress/core/6.7.1/index.php(17): require('/wordpress/core...')
#8 {main}
  thrown in /wordpress/plugins/woocommerce/9.4.2/src/Utilities/OrderUtil.php on line 36 
```

### Expected behavior

No fatal errors.

### Actual behavior

Fatal error encountered.

### Steps to reproduce

N/A. Fatals were observed on Nov 29, 2024 from 12:00:00.000 to 23:30:00

From the stats wrangled by @nigeljamesstevenson (thank you Nigel):
We don’t have steps to reproduce, but observed 3922 Fatals of this type were observed on Fri Nov 29, 2024 across 10 sites.
Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
This is coming from [Google Tag Manager Integration for WooCommerce](https://wordpress.org/plugins/gtm-ecommerce-woo/). I suspect it was an oopsie on their side relating to namespacing. Seems like a mutual customer [already flagged this](https://wordpress.org/support/topic/call-to-undfnd-fn-wc_get_container/), and they've fixed it as of their 1.12.2 release.

For that reason, I'm going to close this issue. Any users of that plugin who hit this error should be encouraged to update in the first instance :+1:
