### ISSUE TITLE
[Enhancement]: Expose perPage and Layout Options in Related Products Block Settings

### ISSUE THREAD

**Issue by a3rev** [woothemes/woocommerce#53470]
### Describe the solution you'd like

The current implementation of the WooCommerce Related Products block in the Site Editor lacks options to configure key attributes, such as the number of products displayed (perPage) and the layout (e.g., columns). These options are essential for controlling the appearance and usability of the Related Products section on product pages but are only accessible via the Code Editor.

**As it stands:**

- The perPage value defaults to 5, and there is no user-friendly way to adjust this via the block settings panel.

- Adjusting this setting requires switching to the Code Editor and manually modifying the block's JSON configuration, which is not intuitive or accessible for non-technical users.

**Steps to Reproduce**

- Open the Site Editor in a Block Theme.
- Edit the Single Product template.
- Locate the Related Products block.
- Attempt to modify the number of products displayed or the layout (columns) in the block settings panel.
- Notice that no settings for perPage or layout are available in the UI.![Image](https://github.com/user-attachments/assets/5e792a9d-0388-49e5-94f0-2bb3b2a61c92)

### Proposed Solution
Add the following options to the block settings panel for the Related Products block:

- Number of Products (perPage): Allow users to specify how many related products are displayed (e.g., a dropdown or input field).
- Layout/Columns: Add a setting to define the number of columns for displaying related products.

### Benefits

- Improves accessibility for non-technical users.
- Eliminates the need to modify JSON directly in the Code Editor.
- Aligns the Related Products block with the intuitive, user-friendly experience expected in the block editor.

**Comment by imanish003** [comment]
Hi @a3rev, Thank you for taking the time to submit this enhancement suggestion. I appreciate the detailed description and clear explanation of the current limitations.

As announced in [Product Collection block—The new default](https://developer.woocommerce.com/2024/11/19/product-collection-block-the-new-default/), this Related Products block is now replaced by the Product Collection block collection. In WooCommerce 9.5, we are shipping a new collection called "Related Products" which supports perPage and layout options. It is much more flexible and powerful than the old Related Products block. I would suggest to use this new collection. As can be seen in [releases](https://github.com/woocommerce/woocommerce/releases), we already have RC1 (Release Candidate 1) for WooCommerce 9.5. and final release is expected on on Monday, 16th December (3 days from now). 

Some related PRs:
- https://github.com/woocommerce/woocommerce/pull/51076
- https://github.com/woocommerce/woocommerce/pull/52580
- https://github.com/woocommerce/woocommerce/pull/52666

As this is covered by the new collection, I'll close this issue. But feel free to leave more comments if you have any questions.

**Comment by a3rev** [comment]
@imanish003 Thank you Manish - I look forward to using the new Product Collection blocks and in particular the 'Related Products' block .

Have a great day.

Steve
