### ISSUE TITLE
[Fatal] Uncaught Exception: Invalid data store. in class-wc-data-store.php:101

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#53517]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.4.3:

[link to code](https://github.com/woocommerce/woocommerce/blob/4d48d242225299672ae68b3443c61269efc081e8/plugins/woocommerce/includes/class-wc-data-store.php#L107)

```
PHP Fatal error:  Uncaught Exception: Invalid data store. in/../wp-content/plugins/woocommerce/includes/class-wc-data-store.php:101
Stack trace:
#0/../wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('customer-sessio...')
#1/../wp-content/plugins/woocommerce/includes/class-wc-customer.php(124): WC_Data_Store::load('customer-sessio...')
#2/../wp-content/plugins/woocommerce/includes/class-woocommerce.php(1025): WC_Customer->__construct(0, true)
#3/../wp-content/plugins/woocommerce/includes/wc-core-functions.php(2570): WooCommerce->initialize_cart()
#4/../wp-content/plugins/woocommerce/includes/class-woocommerce.php(843): wc_load_cart()
#5/../core/6.7.1/wp-includes/class-wp-hook.php(324): WooCommerce->init('')
#6/../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7/../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8/../core/6.7.1/wp-settings.php(704): do_action('init')
#9/../wp-config.php(84): require_once('/wordpress/core...')
#10/../core/6.7.1/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#11/../core/6.7.1/wp-blog-header.php(13): require_once('/wordpress/core...')
#12/../core/6.7.1/index.php(17): require('/wordpress/core...')
#13 {main}
  thrown in/../wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 101
``` 

### Expected behavior

No fatal error witnessed

### Actual behavior

Fatal error witnessed

### Steps to reproduce

We don't have steps to reproduce, but we observed an instance of this fatal on Dec 4 on a site when debugging a related issue.

There are some related comments from @wavvves p1733490063695079/1733277802.451389-slack-C01DT6U03HC

Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Assigning team labels for FSE teams and Solaris since there are multiple teams involved in the discussion. Discussion still ongoing on the thread mentioned by @nigeljamesstevenson 

> There are some related comments from @wavvves p1733490063695079/1733277802.451389-slack-C01DT6U03HC

**Comment by wavvves** [comment]
I'm trying to replicate this now. If unsuccessful, logging will be improved. Either way, a discussion will be created around improvements for the Data Store factory.
Further details on the slack thread p1733490063695079/1733277802.451389-slack-C01DT6U03HC

**Comment by ralucaStan** [comment]
As discussed on the above thread there is nothing actionable on this issue. @Luc45 will improve the error logging logic to add context to when a PHP error was logged
