### ISSUE TITLE
[Fatal] Uncaught TypeError: Cannot access offset of type string on string | add-to-cart.php:40

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#53520]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

[link to code](https://github.com/woocommerce/woocommerce/blob/5afd55098b0d1b2443be02c6cbcc24d1f9f04d96/plugins/woocommerce/templates/loop/add-to-cart.php#L40)

```
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /..//wp-content/plugins/woocommerce/templates/loop/add-to-cart.php:40
Stack trace:
#0 /..//wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include()
#1 /..//wp-content/plugins/hide-add-to-cart-button/hide-add-to-cart-button.php(125): wc_get_template('loop/add-to-car...', '')
#2/../core/6.7.1/wp-includes/class-wp-hook.php(324): wppc_woocommerce_template_loop_add_to_cart('')
#3/../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4/../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /..//wp-content/plugins/woocommerce/templates/content-product.php(65): do_action('woocommerce_aft...')
#6/../core/6.7.1/wp-includes/template.php(812): require('/..//wp-...')
#7 /..//wp-content/plugins/woocommerce/includes/wc-core-functions.php(284): load_template('/..//wp-...', false)
#8 /..//wp-content/plugins/woocommerce/templates/single-product/related.php(43): wc_get_template_part('content', 'product')
#9 /..//wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/..//wp-...')
#10 /..//wp-content/plugins/woocommerce/includes/wc-template-functions.php(2097): wc_get_template('single-product/...', Array)
#11 /..//wp-content/themes/Avada/includes/class-avada-woocommerce.php(1733): woocommerce_related_products(Array)
#12/../core/6.7.1/wp-includes/class-wp-hook.php(324): Avada_Woocommerce->output_related_products('')
#13/../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#14/../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#15 /..//wp-content/plugins/woocommerce/templates/content-single-product.php(72): do_action('woocommerce_aft...')
#16/../core/6.7.1/wp-includes/template.php(812): require('/..//wp-...')
#17 /..//wp-content/plugins/woocommerce/includes/wc-core-functions.php(284): load_template('/..//wp-...', false)
#18 /..//wp-content/plugins/woocommerce/templates/single-product.php(37): wc_get_template_part('content', 'single-product')
#19/../core/6.7.1/wp-includes/template-loader.php(106): include('/..//wp-...')
#20/../core/6.7.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#21/../core/6.7.1/index.php(17): require('/wordpress/core...')
#22 {main}
  thrown in /..//wp-content/plugins/woocommerce/templates/loop/add-to-cart.php on line 40
``` 

### Expected behavior

No fatal error

### Actual behavior

Fatal error witnessed

### Steps to reproduce

We don’t have steps to reproduce, but 1405 Fatals of this type were observed on Fri Nov 29, 2024 across 2 sites.
Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
As ever, apologies if I got the team label wrong! However, this feels like a 'classic frontend' problem (because the issue, or potential issue, is inside `templates/loop/add-to-cart.php`), hence the change.

**Comment by imanish003** [comment]
Hi @nigeljamesstevenson,

Looks like error happens on following line:
```
isset( $args['attributes'] ) ? wc_implode_html_attributes( $args['attributes'] ) : '',
```

This happens because `$args` is being passed as a string instead of an array when trying to access `$args['attributes']`. This file (`loop/add-to-cart.php`) is being added [here](https://github.com/woocommerce/woocommerce/blob/31960d611c15124b469011740e128e563ea3ad9b/plugins/woocommerce/includes/wc-template-functions.php#L1427) using `wc_get_template` function. I don't think this is a bug in WooCommerce core. Here are my findings:
- There is custom code or plugin which is using `woocommerce_loop_add_to_cart_args` filter and passing a string instead of an array.
- I can see there is plugin called `hide-add-to-cart-button` in error logs. Probably, This plugin is calling `wc_get_template` function in wrong way? 🤔

**Comment by imanish003** [comment]
I am going to close this issue for now since it doesn't seem to be a WooCommerce core issue.
