### ISSUE TITLE
Minor issues in woocommerce

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#53524]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi woocommerce team,

There are two bugs in the backend that are very minor and do not cause any problems in the workflow. However, they are bugs that can be fixed.

1- When we click on the star for add to the featured product, two dots appear around it and are clickable.

![Image](https://github.com/user-attachments/assets/2306d7f2-247d-44dc-a216-224ef6c4208f)

2- In Variable Products > Variable Options, the 3 Dimensions fields are completely stuck together. But in simple products, there is no problem.

### Variable Products

![Image](https://github.com/user-attachments/assets/57cc7703-6b57-4b48-9dc8-374735f4a164)

### simple products

![Image](https://github.com/user-attachments/assets/84ed4f3b-4964-4370-a374-4482a907922e)

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

-

### WordPress Environment

Wordpress: 6.7.1
Woocommerce: 9.4.3
Php: 8.1
Browser: chrome 131.0.6778.87
Active plugins: elementor, woocommerce
Theme: Hello elementor

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by imanish003** [comment]
Hi @79ho3ein,

Thank you for reporting these styling issues in Product Editor. I've created PR #53707, which addresses both the featured product star display and variation dimensions spacing problems you identified.

**Comment by 79ho3ein** [comment]
Hi @imanish003, Thanks for following up🙏
