### ISSUE TITLE
Shipping Methods Don't Show Up On Checkout Block But Works On Cart Page

### ISSUE THREAD

**Issue by roguewdesign** [woothemes/woocommerce#53532]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the new Checkout Blocks template, the Shipping Options block does not show any third party / custom shipping methods. However, they show up on the Cart page.

I've included screenshots, one being the admin editor where the Shipping Options block has been added, and another is the front end where the area where the Shipping Options should be is blank.

I'll also mention there on the right side of the Editor, I see "The following shipping integrations are active on your store." and the custom methods via plugins appear there, without any warnings or errors.![Image](https://github.com/user-attachments/assets/dbd8e13b-9dd3-44f5-8e70-5d0049bad498)
![Image](https://github.com/user-attachments/assets/df899b0e-0d8e-434d-986f-e7d36275b0ac)
![Image](https://github.com/user-attachments/assets/a9fe5783-3ede-408f-9895-70b1412977cd)
![Image](https://github.com/user-attachments/assets/25db5030-e3c5-4bc9-8320-1b17bdb88e3e)

Again, it seems to be for custom shipping methods only which show up on the Cart page, but not the Checkout page

### Expected behavior

Shipping options to appear on the Checkout Page (using the Blocks Checkout template)

### Actual behavior

No Shipping Options block or selection appears on the Checkout page.

### Steps to reproduce

1. Go to Checkout page (either page with Checkout Blocks or Theme Template with Checkout Block).
2. Confirm Shipping Options block is added to the Checkout FIelds.
3. Go to front-end of site and add something to your cart.
4. Go to the cart page, and view Shipping Options.
5. Go to the Checkout page, and see there are not shipping options to choose from.
6. Note* IF YOU ARE USING FLAT RATE or FREE SHIPPING, they may show up, but any plugin added (Canada Post, Clickship, etc) options do not appear.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.2.9
PHP Post Max Size: 50 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.40-0ubuntu0.22.04.1
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 102
page: 12
post: 1
product: 21054
product_variation: 7
revision: 290
shop_order: 1
shop_order_placehold: 12
wp_block: 4
wp_font_face: 34
wp_font_family: 13
wp_global_styles: 1
wp_navigation: 3
wp_template: 14
wp_template_part: 5
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Better Search Replace: by WP Engine – 1.4.7
ClickShip: by ClickShip – 1.0.2
Contact Form 7: by Takayuki Miyoshi – 6.0.1
Rogue Woo Wish List: by Rogue Web Design – 1.0.0
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Stripe Gateway: by Stripe – 8.9.0
WooCommerce PayPal Payments: by WooCommerce – 2.9.4
WooCommerce Canada Post Shipping: by WooCommerce – 3.0.4
WooCommerce: by Automattic – 9.4.3

### Inactive Plugins (0) ###


### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 16 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  This page's content is overridden by custom template content
Checkout: #9 - /checkout/ -  This page's content is overridden by custom template content
My account: #10 - /my-account/
Terms and conditions: #230 - /terms-conditions/

### Theme ###

Name: Rogue Web Design Block Theme
Version: 1.0.9
Author URL: https://roguewebdesign.ca
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /home/forge/store.c-tow.ca/public/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/forge/store.c-tow.ca/public/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/forge/store.c-tow.ca/public/wp-content/plugins/woocommerce/templates/block-notices/success.php
ctow-woo-theme/woocommerce/single-product/product-image.php
ctow-woo-theme/woocommerce/single-product/product-thumbnails.php


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CA
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-12-07 20:44:23 -08:00
Options: ✔
Notes: 105
Onboarding: completed

### Action Scheduler ###

Cancelled: 1
Oldest: 2024-12-06 13:46:17 -0800
Newest: 2024-12-06 13:46:17 -0800

Complete: 423
Oldest: 2024-11-06 14:17:45 -0800
Newest: 2024-12-06 14:52:21 -0800

Failed: 6
Oldest: 2023-08-28 11:47:25 -0700
Newest: 2024-11-28 09:25:54 -0800

Pending: 1
Oldest: 2024-12-07 14:40:31 -0800
Newest: 2024-12-07 14:40:31 -0800


### Status report information ###

Generated at: 2024-12-06 14:55:13 -08:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
Hey! I'm unable to actually reproduce this. Sadly Canada Post and Clickship both require a Canadian credit card to use them, both don't come with a test mode as well.

I tried other plugins like table rate shipping and it worked fine.

For your case, it seems the block is having JS problems because otherwise it should show a warning that no shipping is available.

Can you confirm if there's no console errors or provide a live website to test this on>

**Comment by roguewdesign** [comment]
Thanks @senadir although I already checked the console, it turns out there was a REST requests not logged in error. Not sure how I missed it the first time, but this resolve the issue!

Cheers :)

**Comment by senadir** [comment]
That's strange, you shouldn't be seeing such error if you're able to see Checkout block. I assume the error was against a Store API request?
