### ISSUE TITLE
How to set PickUp as default Shipping Method

### ISSUE THREAD

**Issue by zurmoehle** [woothemes/woocommerce#53540]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have a woocommerce shop where i don't have any delivery at the moment. 

So Pickup should be default. Delivery should be as option to request it so the client can communicate per mail.

but i dint see any option to set Pickup as default not in the block either in any filter. is there any way to set this as default selected option?

### Expected behavior

in the block for shipping has to be a option to set one of the shipping or pickup as default (first element)

### Actual behavior

When i go to the checkout there is shipping default selectet. not Pickup

### Steps to reproduce

pick a product
go to checkout

### WordPress Environment

i use woocommerce with the woocommerce germanized plugin

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @zurmoehle This looks more like a support request than an issue. We use GitHub for bug reports and enhancement requests. Please reach out to any of our official support channels instead:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
- Join our [WooCommerce Community Slack channel](https://woocommerce.com/community-slack/) and ask your question there.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look. If you want to suggest an enhancement, please use the Enhancement Request template by clicking on this [link](https://github.com/woocommerce/woocommerce/issues/new?template=2-enhancement.yml).
