### ISSUE TITLE
forward to 46260 after MONTHS OF NO COMMUNICATION

### ISSUE THREAD

**Issue by Studio-Sjoege** [woothemes/woocommerce#53559]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

forward to #46260. what a disappointing community.. not a response in months, this is a BIG issue and I'm not the only one getting this issue, I've seen a lot more people having this online and this is a BIG BIG BIG issue in woocommerce. why won't this be dealt with the right priorities?? is it to difficult? woocommerce sticks it head in the sand.. 

### Expected behavior

forward to #46260. what a disappointing community.. not a response in months, this is a BIG issue and I'm not the only one getting this issue, I've seen a lot more people having this online and this is a BIG BIG BIG issue in woocommerce. why won't this be dealt with the right priorities?? is it to difficult? woocommerce sticks it head in the sand.. 

### Actual behavior

forward to #46260. what a disappointing community.. not a response in months, this is a BIG issue and I'm not the only one getting this issue, I've seen a lot more people having this online and this is a BIG BIG BIG issue in woocommerce. why won't this be dealt with the right priorities?? is it to difficult? woocommerce sticks it head in the sand.. 

### Steps to reproduce

see the other post

### WordPress Environment

not needed

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tjcafferkey** [comment]
Hi @Studio-Sjoege, appreciate the frustration you're feeling here. I have followed up on your original issue with a comment https://github.com/woocommerce/woocommerce/issues/46260#issuecomment-2531353636
