### ISSUE TITLE
Wrong image and missing animation in Product Gallery Block (beta)

### ISSUE THREAD

**Issue by wpchannel** [woothemes/woocommerce#53599]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Scrolling images in product gallery block (beta) is not working fine. The first time you scroll it seems to works fine, but when going back the animation is not working and the second image is shown. Here is a video to illustrate:

https://github.com/user-attachments/assets/668470a8-091d-41a0-b546-b3822cf54bce

### Expected behavior

Having a smooth scroll when changing slide.

### Actual behavior

The second image is not showing with animation on click. Only works the first time after loading page.

### Steps to reproduce

1. Edit single product using FSE to add Product Gallery block (beta)
2. Create a product with a featured image and gallery of images
3. Open the single product in front and scroll several times

### WordPress Environment

WordPress 6.6
WooCommerce 9.3.4

Using MAMP PRO 7 with default WordPress settings, no plugins except WooCommerce and default theme.

Also happens on live website.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kmanijak** [comment]
Thanks for raising this issue! I spotted the same recently and it's been fixed in https://github.com/woocommerce/woocommerce/pull/53314. It will land in WooCommerce 9.6 🙌 

I'mTo keep the backlog clean, I'm closing this issue but keep in mind the closed issues can still be commented on if needed!
