### ISSUE TITLE
Widget Area crashes when the Product Collection is rendered

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#53639]
> We are going to reopen the issue because we noticed the same issue in the widget area. 
> 
> https://github.com/user-attachments/assets/c4f3b84c-6508-4d28-a81c-227749faca81
> 
> 
> To reproduce this issue:
> - Switch to a classic theme like Storefront
> - Visit `wp-admin/widgets.php`
> - Click on the + button and search "Product Collection"
> - See the crash
> 
> 
> The widget editor crashes when loading the Product Collection preview. If this block is frequently used and appears among the first visible blocks, the widget area crashes upon clicking the plus button. 

 _Originally posted by @gigitux in [#52699](https://github.com/woocommerce/woocommerce/issues/52699#issuecomment-2536332645)_

**Comment by imanish003** [comment]
@gigitux Should we close this issue, as I believe it was fixed in #53638? Or are there more edge cases that we need to address?

**Comment by gigitux** [comment]
Thanks for the ping! I'm going to close this issue!
