### ISSUE TITLE
Blueprint: Import - Run the importer

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#53680]
Figma: Y5pUYSJPsGEud1vknUZhi8-fi-3791_17942

When the user clicks on `Import` button, run the importer.

## Acceptance Criteria

Conflict detection state is set from https://github.com/woocommerce/woocommerce/issues/53679

Scenario: User clicks on the `Import` button and conflicts are detected.

Given a user who has successfully uploaded a schema file
When the user clicks on the import button
And conflicts are detected
Then show a modal with the list of conflicts (Y5pUYSJPsGEud1vknUZhi8-fi-3791_28867)

Scenario: User clicks on the `Import` button and no conflicts are detected.

Given a user who has successfully uploaded a schema file
When the user clicks on the import button
And no conflicts are detected
Then make a request to run the importer with the uploaded file
When the request returns any errors
Then show them (Y5pUYSJPsGEud1vknUZhi8-fi-3700_13745)

**Comment by chihsuan** [comment]
> Scenario: User clicks on the Import button and conflicts are detected.

@moon0326 👋  Do we have an existing method to detect conflicts? Or do we still need to implement it?

**Comment by moon0326** [comment]
@chihsuan We still need to implement. I haven't found a way to detect changes made by users yet.

**Comment by chihsuan** [comment]
Gotcha! @moon0326 I'll implement UI part first. I think we can always show the modal and display the changes based on the import file as the first step so that we can get more feedback in the design call next week.
