### ISSUE TITLE
[Fatal] PHP Fatal error:  Uncaught Error: Call to a member function get_title() on null in | wc-template-functions.php:1668

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#53761]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

During 9.5.0 release, we have witnessed a fatal when the `woocommerce-additional-variation-images` is installed

[link to code](https://github.com/woocommerce/woocommerce/blob/90faf2cacfaf4a5f9f0ba196a2afd8fe91696c40/plugins/woocommerce/includes/wc-template-functions.php#L1668)

we witnessed ~248 fatals across 18 sites after the deploy from 2pm UTC to 330pm UTC on Mon Dec 16th, 2024

```
PHP Fatal error:  Uncaught Error: Call to a member function get_title() on null in /../plugins/woocommerce/9.5.0/includes/wc-template-functions.php:1668
Stack trace:
#0 /../wp-content/plugins/woocommerce-additional-variation-images/includes/class-wc-additional-variation-images-frontend.php(101): wc_get_gallery_image_html(727, false)
#1 /../core/6.7.1/wp-includes/class-wp-hook.php(324): WC_Additional_Variation_Images_Frontend->ajax_get_images('')
#2 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /../plugins/woocommerce/9.5.0/includes/class-wc-ajax.php(96): do_action('wc_ajax_wc_addi...')
#5 /../core/6.7.1/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax('')
#6 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /../core/6.7.1/wp-includes/template-loader.php(13): do_action('template_redire...')
#9 /../core/6.7.1/wp-blog-header.php(19): require_once('/../core...')
#10 /../core/6.7.1/index.php(17): require('/../core...')
#11 {main}
  thrown in /../plugins/woocommerce/9.5.0/includes/wc-template-functions.php on line 1668
``` 

That line got altered here in 9.5
https://github.com/woocommerce/woocommerce/pull/51936

### Expected behavior

No fatal error

### Actual behavior

In 9.5.0 if a shopper visits a variable product page that has used that plugin to add extra product images it triggers the fatal.
The page displays the product images instead (as if the plugin was deactivated)
But otherwise functionality seems to still work (just no additional images).

9.4.3 WC only
Product images and variation details
![Image](https://github.com/user-attachments/assets/b5a97849-1b50-4bdb-a712-b8dfa96f0f3f)

![Image](https://github.com/user-attachments/assets/df6e9416-6e4b-4042-8ed4-396448aaa16b)

9.4.3 WC & WooCommerce Additional Variation Images plugin
I’ve added a green tick here as an extra image, and you can see it when you select that variation as a shopper
![Image](https://github.com/user-attachments/assets/de191e5c-b7ce-46f9-b7e2-e9fe83dda889)

![Image](https://github.com/user-attachments/assets/f73acb49-2ed6-46cb-a1f7-7993d2a9d8c4)

9.5.0 WC & WooCommerce Additional Variation Images plugin
Shopper doesn’t see extra image, functionality still works, Fatal appears in site logs.

![Image](https://github.com/user-attachments/assets/8b226299-6556-4e58-a19b-9f1c575c0cbe)

### Steps to reproduce

see actual behaviour above

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/53762
