### ISSUE TITLE
[CFE]: Hide LYS Launch Newsletter panel when feature is disabled

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#53783]
### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/53781

### Why do these PRs need to break the code freeze?

The `Launch Newsletter` panel is not meant to be shown when the feature flag is disabled

### What is the consequence if this exception does not get included?

New users will experience half-baked feature when they're editing coming soon page, as a result it may cause confusion and dropoff.

### What is the plan should defects to be discovered in these PRs ahead of final release?

Reverting should be sufficient

### How should this change be communicated in the release post on the public developer blog:

Not required

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

@woocommerce/ghidorah 

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.
- [x] I understand that I will need to merge the PR to the target `release` branch for which the fix was intended, when my request is approved
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `trunk` when my request is approved

### Closing checklist for Solaris

- [x] Escape analysis completed
- [x] The fix is raised from intended release branch. For a fix targeting WC X.Y, the base branch should be `release/X.Y`
- [x] PR merged to target `release` branch
- [x] PR cherry-picked to `trunk` (you can find the links in PR comments to verify)
- [x] Followup issue if any

**Comment by ilyasfoo** [comment]
### Escape analysis

In the original PR (https://github.com/woocommerce/woocommerce/pull/52650), we've missed testing with the feature flag being disabled. Since it was not apparent code wise (feature flag check was added in PHP, but not Javascript), the bug went through undetected.

I think we need to be more careful with testing according to instructions, perhaps even adding in regression check in instructions. Might be good topic to bring up in our cycle retro cc @adrianduffell.

**Comment by ilyasfoo** [comment]
> I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post.

In lieu of a GitHub issue, we're going to include a topic in our team discussion with an improvement suggestion: include specific instructions when it's expected for things to be hidden under a feature flag. Let me know if this is okay!

**Comment by nigeljamesstevenson** [comment]
> > I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post.
> 
> In lieu of a GitHub issue, we're going to include a topic in our team discussion with an improvement suggestion: include specific instructions when it's expected for things to be hidden under a feature flag. Let me know if this is okay!

Thanks @ilyasfoo !
