### ISSUE TITLE
[Enhancement]: Thank you page - shortcode and dedicated page

### ISSUE THREAD

**Issue by tunyk** [woothemes/woocommerce#53800]
### Describe the solution you'd like

1. Create a shortcode for Thank you page
2. In the admin on the page /wp-admin/admin.php?page=wc-settings&tab=advanced&section in the Page Settings block, add the Thank you page selection

**Comment by wavvves** [comment]
Hi @tunyk thank you for reaching out. 
Currently the Thank You content can be edited by overriding the templates `/woocommerce/templates/checkout/thankyou.php` and `/woocommerce/templates/checkout/order-received.php`, and further customizations can be added through the `woocommerce_before_thankyou` filter.
Parallel to that, what you mentioned is already possible when using a block based theme, by editing the Order Confirmation template found in Appearance > Editor

I understand the need for easily editing the content before and after through the page editor, like the legacy way of editing cart and checkout pages, but for the reasons above mentioned this is not planned for tackling right now. Closing the issue, but feel free to reopen this if there is more things you'd like to add 🙂
