### ISSUE TITLE
Blueprint: Import - Add new endpoints to support schema validation, conflict check, and queued upload.

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#53803]
Figma: https://www.figma.com/design/Y5pUYSJPsGEud1vknUZhi8/Core-onboarding---Profiler?node-id=3791-29758&m=dev

The new import flow validates the schema and checks for conflicts before processing. To support pre-checks, the upload endpoint must return a reference for queued uploads and allow processing the file later using that reference. We'll make two new endpoints to support the flow.

**Endpoints**

**POST** `/wp-json/wc-admin/blueprint/queue`

- Accepts a Blueprint schema file and validate it for the format and possible conflicts.
- The endpoint must return a reference that can be used to process the file later.

Response:
```json
{
    "reference": "string | null",
    "errors": [
        "upload": [],
        "schema_validation": [],
        "conflicts": []
   ]
}
```

**POST** `/wp-json/wc-admin/blueprint/process`

For the `result` field, please refer to the current [import](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/Blueprint/RestApi.php#L126) endpoint.

Response:
```json
{
    "processed": "bool",
    "message": "string",
    "data": {
        "redirect": "string",
        "result": []
    }
}
```

**Comment by rjchow** [comment]
Hi thanks for this @moon0326 !

Thoughts -

For POST /wp-json/wc-admin/blueprint/queue, would the error details be available immediately in the response? I had assumed that because its async it would take awhile to get those details. Also I think reference should never be null 

For POST /wp-json/wc-admin/blueprint/process

- I think it should be a GET? From what I'm understanding in this issue, the processing would be kicked off automatically once /queue is posted to and this endpoint would just return the status. Perhaps it should be `./status` or `./details` rather than `./process` ?
- would it take a {blueprint_upload_id} in the path param?

**Comment by moon0326** [comment]
> I think it should be a GET? From what I'm understanding in this issue, the processing would be kicked off automatically once /queue is posted to and this endpoint would just return the status. Perhaps it should be ./status or ./details rather than ./process ?

As I understand it, users must click the "Import" button to trigger the import process.

See: https://www.figma.com/design/Y5pUYSJPsGEud1vknUZhi8/Core-onboarding---Profiler?node-id=3791-17471&m=dev

The "Import" button only becomes available after the file is successfully uploaded. Therefore, I believe this is not an asynchronous process. The endpoint `/wp-json/wc-admin/blueprint/queue` uploads the file to a temporary location and returns the results of schema validation and conflict checks. The frontend makes an additional request to the process endpoint to run the importer when users click on the button.

I personally prefer a one-step upload process — we run the importer immediately and return the result.

> would it take a {blueprint_upload_id} in the path param?

If we support /wp-json/wc-admin/blueprint/{ref_id}/process, it implies supporting multiple files. I think we should only support one file at a time per user."
