### ISSUE TITLE
Remove "invoice" from the customer invoice email - round 2

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#53889]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is related to #26692 

The email still has a reference to "invoice" if the order needs payment. This should be removed.
`__( 'An order has been created for you on %1$s. Your invoice is below, with a link to make payment when you’re ready: %2$s', 'woocommerce' ),`

I suggest:
`__( 'An order has been created for you on %1$s. The order details are below, with a link to make payment when you’re ready: %2$s', 'woocommerce' ),`

### Expected behavior

Not having any mention to invoice on this email, as this is not a legal invoice em several jurisdictions, as discussed on https://github.com/woocommerce/woocommerce/issues/26692

### Actual behavior

There's still a mention to "invoice"

### Steps to reproduce

1. Create an unpaid order
2. Send the order details email

### WordPress Environment

Not relevant.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by webdados** [comment]
Hi @juliaamosova @barryhughes @jorgeatorres, sorry for the tag but you were all involved in #26692 and it would be cool if this wouldn't take almost 4 years again to close such a simple issue.

One of the objectives of the first issue was not achieved after all:
> Remove all mentions to "invoice" on this email (and WooCoommerce altogether)

**Comment by barryhughes** [comment]
Thanks for flagging. I've started [drafting a fix](https://github.com/woocommerce/woocommerce/pull/53897), feel free to follow along :+1:

**Comment by webdados** [comment]
🙌
