### ISSUE TITLE
Multiple block compatibility layer for search results are executed

### ISSUE THREAD

**Issue by dennisnissle** [woothemes/woocommerce#53990]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using a block-based theme, the `ArchiveProductTemplatesCompatibility` object is used to inject template hooks into the block layout. The issue is that specifically for search results, 2 compatibility layers are injected:

1. `src/Blocks/Templates/ProductSearchResultsTemplate::render_block_template()` and
2. `src/Blocks/Templates/ProductCatalogTemplate::render_block_template()`

This leads to hooks being injected twice (leading to duplicate output of the hook's content)

### Expected behavior

Hook content should only be injected once.

### Actual behavior

Hook content is injected twice.

### Steps to reproduce

1. Make sure to use a block-theme
2. Add a little snippet to register a hook that has compatibility

`add_action( 'woocommerce_after_shop_loop_item', function() {
	echo "test hook injection";
} );`

3. Open the product search results page (with some results), e.g.: my-site.com/?s=test&post_type=product
4. See that hook output is injected twice

### WordPress Environment

Latest WP, Woo.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by imanish003** [comment]
Hi @dennisnissle,

Thank you for reporting this issue. I was able to confirm the duplicate hook injection behavior you described when using block themes.

I've created PR #54060 that addresses this by adding a check to prevent the ProductCatalogTemplate compatibility layer from initializing during search requests. This should ensure hooks are only injected once as expected.
