### ISSUE TITLE
Backordered Stock Management

### ISSUE THREAD

**Issue by kloon** [woothemes/woocommerce#5669]
The backordered functionality is in serious need of some love, currently there is no way for a store manager to view orders that have products that is on backorder.

Lets use this issue to discuss possibilities on how we can improve it for store managers to know which orders has backordered products and how to handle orders like that.

**Comment by mikejolley** [comment]
This item has been moved to the roadmap https://trello.com/c/hTPB8fkD/56-backordered-stock-management
