### ISSUE TITLE
Allow product short code to pre-select attributes for variable products

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#5866]
As per the title

>I have a variable subscription with an SKU code of "variable-subscription", and it's two variations have SKU codes of "variable-subscription-variation" and "variable-subscription-variation-2".

>Whilst this shortcode will work...

>[product sku="variable-subscription"]

>...these shortcodes output nothing...

>[product sku="variable-subscription-variation"] 
[product sku="variable-subscription-variation-2"]

>...but they should show the product page with the variation pre-selected.

**Comment by splashingpixels** [comment]
@ChromeOrange do you perhaps mean the shortcode [product_page] ?  Because [product] suppose to display the product in archive view.

**Comment by ChromeOrange** [comment]
@splashingpixels probably, I think I just copied that out of a ticket

this 

[product sku="variable-subscription-variation"] 
[product sku="variable-subscription-variation-2"]

and this

[product_page sku="variable-subscription-variation"] 
[product_page sku="variable-subscription-variation-2"]

don't work, certainly the second should IMHO.

**Comment by splashingpixels** [comment]
@ChromeOrange do you want to give this PR a whirl to see if it does what you were looking for? :)

**Comment by ChromeOrange** [comment]
@splashingpixels yeah that works https://dl.dropboxusercontent.com/s/s2z78cuah1g6hu3/2015-01-18%20at%2022.32%202x.png?dl=0

**Comment by mikejolley** [comment]
Closed in fav of #7136
