### ISSUE TITLE
Document v2 REST API

### ISSUE THREAD

**Issue by maxrice** [woothemes/woocommerce#5942]
Lots of changes in the v2 REST API which need to be documented :smile: 

- [x] differences between v1/v2 APIs
- [x] XML response is gone in v2
- [x] Coupon PUT/POST/DELETE (see http://woothemes.github.io/woocommerce-rest-api-docs/#coupons)
- [x] Customer PUT/POST/DELETE (see http://woothemes.github.io/woocommerce-rest-api-docs/#customers)
- [x] Customer GET /customer/#{id}/downloads (see http://woothemes.github.io/woocommerce-rest-api-docs/#view-customer-downloads)
- [x] Order PUT/POST/DELETE (see http://woothemes.github.io/woocommerce-rest-api-docs/#orders)
- [x] New GET /order response (item meta, etc) (see http://woothemes.github.io/woocommerce-rest-api-docs/#view-an-order)
- [x] Order notes PUT/POST/DELETE (see http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-note-for-an-order)
- [x] Order refunds GET/PUT/POST/DELETE (see http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-refund-for-an-order)
- [x] Products PUT/POST/DELETE (see http://woothemes.github.io/woocommerce-rest-api-docs/#products)
- [x] Product categories endpoint (see http://woothemes.github.io/woocommerce-rest-api-docs/#view-a-product-category)
- [x] Orderby filter for all resources
- [x] Order filter for customers endpoint
- [x] Webhooks overview & endpoints (see http://woothemes.github.io/woocommerce-rest-api-docs/#webhooks4)

In-progress: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by j0rd** [comment]
Looking for documentation for POST /products

Looking to move off shopify on to woocommerce, but I need ability to create products via API to ease the transition (~9000+ products)

**Comment by oBigZee** [comment]
Looking for documentation for Order POST to be able to create orders.

**Comment by madianas** [comment]
I have been working with WooCommerce REST API doing some cool things, and have some feedback. Thought I should mention that to POST a file to a downloadable product, 'url' needs to be passed instead of 'file', even though you GET 'file'. It took me sometime to figure this one out. Mind you it was my first time looking into a php file.
GET
```            "downloads": [
                {
                    "id": "99883d1e6be5d804f4738643530b9535",
                    "name": "2012-592.pdf",
                    "file": "https://site/wp-content/uploads/woocommerce_uploads/2014/12/2012-592.pdf"
                }
            ]```


POST
```
 "downloads": [
                {
                    "name": "2012-592.pdf",
                    "url": "https://site/wp-content/uploads/woocommerce_uploads/2014/12/2012-592.pdf"
                }
            ],```

**Comment by growdev** [comment]
@claudiosmweb let us know where the docs land so we can contribute.

**Comment by claudiosmweb** [comment]
@growdev We're hitting some details on that soon I think I'll work hard at it and we will have space for contributions :D
Thank you for showing interest in contributing.

**Comment by claudiosmweb** [comment]
The new REST API Docs is in http://woothemes.github.io/woocommerce-rest-api-docs/

Anyone who wants to contribute can send Pull Requests: https://github.com/woothemes/woocommerce-rest-api-docs

We'll put all REST API versions on this new page and depreciate the old links.

**Comment by claudiosmweb** [comment]
@j0rd ready now: http://woothemes.github.io/woocommerce-rest-api-docs/#products ;)

**Comment by claudiosmweb** [comment]
@madianas I just fixed this. Will work better in WC 2.3 :)

**Comment by camilloaddis** [comment]
@maxrice Hi, I figured out how to create an order via POST method, and it worked. 
But my product is a variable one, and if I set in "line_items" a "meta" property with correct value (which I got from a order created via the "create order" button), It won't create that part, and it won't update it via PUT method.
I'm trying

**POST**
```
{
 "order": {
  "status" : "pending",
  "currency" : "EUR",
  "billing_address" : {…},
  "shipping_address" : {…},
  "line_items": [
   { 
    "id":null,
    "quantity":1,
    "product_id":31,
    "meta":[
     {
      "key":"pa_taglia",
      "label":"taglia",
      "value":"medium"
     }
    ]
   }
  ]
 }
}
```
and **PUT**
``` 
{
 "order": {
  "status": "pending",
  "line_items": [
   {
    "id": 8,
    "product_id": 31,
    "meta": [
     {
      "key": "pa_taglia",
      "label": "Taglia",
      "value": "large"
     }
    ]
   }
  ]
 }
}
```
How can I make this work?
Thank you – also for your great job! Can't wait the release of the complete api doc!

**Comment by BennSandoval** [comment]
I have an Android Client for woocommerce it could be useful to see the calls to the API

https://github.com/BennSandoval/Woodmin

**Comment by claudiosmweb** [comment]
Docs ready! http://woothemes.github.io/woocommerce-rest-api-docs/

If someone found an error or a typo in the documentation, send Pull Request or open an issue on: https://github.com/woothemes/woocommerce-rest-api-docs
