### ISSUE TITLE
Create/Update product variations with REST API

### ISSUE THREAD

**Issue by kallewallin** [woothemes/woocommerce#6082]
We are testing woocommerce Version 2.2.0-bleeding REST API

We are trying to create products with variantions and is posting the following(POST to [URL]/wc-api/v2/products):

```
{  
   "title":"Parent 10",
   "sku":"parent10",
   "type":"variable",
   "regular_price":"100.00",
   "attributes":[  
      {  
         "name":"Color",
         "visible":true,
         "variation":true,
         "options":[  
            "Red",
            "Blue",
            "Green"
         ]
      }
   ],
   "variations":[  
      {  
         "sku":"parent10child1",
         "attributes":[  
            {  
               "name":"Color",
               "option":"blue"
            }
         ]
      },
      {  
         "sku":"parent10child2",
         "attributes":[  
            {  
               "name":"Color",
               "option":"red"
            }
         ]
      }
   ]
}
```

and we get the following response:

```
<br />
<b>Warning</b>:  array_filter() expects parameter 1 to be array, null given in <b>/var/www/woocommerce-2-2-beta/wp-content/plugins/woocommerce-2.2-beta/includes/class-wc-product-variation.php</b> on line <b>169</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/woocommerce-2-2-beta/wp-content/plugins/woocommerce-2.2-beta/includes/api/class-wc-api-products.php</b> on line <b>1691</b><br />
<br />
<b>Warning</b>:  array_filter() expects parameter 1 to be array, null given in <b>/var/www/woocommerce-2-2-beta/wp-content/plugins/woocommerce-2.2-beta/includes/class-wc-product-variation.php</b> on line <b>169</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/woocommerce-2-2-beta/wp-content/plugins/woocommerce-2.2-beta/includes/api/class-wc-api-products.php</b> on line <b>1691</b><br />
{"product":{"title":"Parent 10","id":48,"created_at":"2014-08-22T14:28:03Z","updated_at":"2014-08-22T14:28:03Z","type":"variable","status":"publish","downloadable":false,"virtual":false,"permalink":"[URL]\/product\/parent-10-3","sku":"parent10","price":"0.00","regular_price":"0.00","sale_price":null,"price_html":"","taxable":false,"tax_status":"taxable","tax_class":"","managing_stock":false,"stock_quantity":0,"in_stock":true,"backorders_allowed":false,"backordered":false,"sold_individually":false,"purchaseable":false,"featured":false,"visible":false,"catalog_visibility":"hidden","on_sale":false,"weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":null,"description":"","short_description":"","reviews_allowed":true,"average_rating":"0.00","rating_count":0,"related_ids":[],"upsell_ids":[],"cross_sell_ids":[],"categories":[],"tags":[],"images":[{"id":0,"created_at":"2014-08-22T14:28:03Z","updated_at":"2014-08-22T14:28:03Z","src":"[URL]\/wp-content\/plugins\/woocommerce-2.2-beta\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"featured_src":false,"attributes":[{"name":"Color","position":0,"visible":false,"variation":true,"options":["Red","Blue","Green"]}],"downloads":[],"download_limit":0,"download_expiry":0,"download_type":"","purchase_note":"","total_sales":0,"variations":[{"id":49,"created_at":"2014-08-22T14:28:03Z","updated_at":"2014-08-22T14:28:03Z","downloadable":false,"virtual":false,"permalink":"\/wc-api\/v2\/products?=[URL]\/product\/parent-10-3","sku":"parent10child1","price":"0.00","regular_price":"0.00","sale_price":null,"taxable":false,"tax_status":"taxable","tax_class":"","stock_quantity":0,"in_stock":true,"backordered":false,"purchaseable":false,"visible":false,"on_sale":false,"weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_class":"","shipping_class_id":null,"image":[{"id":0,"created_at":"2014-08-22T14:28:03Z","updated_at":"2014-08-22T14:28:03Z","src":"[URL]\/wp-content\/plugins\/woocommerce-2.2-beta\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"attributes":[],"downloads":[],"download_limit":0,"download_expiry":0},{"id":50,"created_at":"2014-08-22T14:28:03Z","updated_at":"2014-08-22T14:28:03Z","downloadable":false,"virtual":false,"permalink":"\/wc-api\/v2\/products?=[URL]\/product\/parent-10-3","sku":"parent10child2","price":"0.00","regular_price":"0.00","sale_price":null,"taxable":false,"tax_status":"taxable","tax_class":"","stock_quantity":0,"in_stock":true,"backordered":false,"purchaseable":false,"visible":false,"on_sale":false,"weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_class":"","shipping_class_id":null,"image":[{"id":0,"created_at":"2014-08-22T14:28:03Z","updated_at":"2014-08-22T14:28:03Z","src":"[URL]\/wp-content\/plugins\/woocommerce-2.2-beta\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"attributes":[],"downloads":[],"download_limit":0,"download_expiry":0}],"parent":[]}}
```

The product is created with 2 variations but the color option is not selected. As the response suggests, the attributes is not saved. Posting "option":"blue" or "option":"Blue" for example gives the same result.

GET [URL]/wc-api/v2/products/48 will then give the same error until we goes to the product in admin and saves it. Then GET [URL]/wc-api/v2/products/48 will work but with cleared variation attributes:

```
"attributes": [{"name": "Color","option": ""}]
```

The same scenario is true when trying to update the product.

**Comment by alexrusenhack** [comment]
I have the same problem.

The variations do not change.

```json
{
     "title":"T-Shirt",
     "id":"64",
     "sku":"",
     "variations":[
          {
               "id":"81",
               "price":"10.00",
               "regular_price":"10.00",
               "attributes": [
                    {
                         "name":"pa_tamanho",
                         "option":"m"
                    },
                    {
                         "name":"pa_cor",
                         "option":"verde"
                    }
               ]
          }
     ]
}```

![attributes](https://cloud.githubusercontent.com/assets/5992210/6160168/12b9fdb6-b246-11e4-94a1-f9872c5da144.png)

**Comment by claudiosmweb** [comment]
@alexrusenhack just use the `slug`, that is new in 2.3.
http://woothemes.github.io/woocommerce-rest-api-docs/?shell#products-properties

**Comment by alexrusenhack** [comment]
Ok. I replace "name" for "slug", but it does not worked.
I used all the combinations for the "slug" as: "attribute_pa_tamanho", "pa_tamanho" and "tamanho". Nothing updated the product variation.

**Comment by alexrusenhack** [comment]
Sorry guys! I've found the problem. My code was hiding the "id" key of the variation product. Because of this the product could not be updated.

@claudiosmweb The code worked with the "name" attribute too.

Thanks!

**Comment by claudiosmweb** [comment]
Works with name or slug :)

**Comment by uresh** [comment]
hi need help 
i used 
/**
 * WooCommerce API Client Class
 *
 * @author Gerhard Potgieter
 * @since 2013.12.05
 * @copyright Gerhard Potgieter
 * @version 0.3.1
 * @license GPL 3 or later http://www.gnu.org/licenses/gpl.html
 */
when i try to update order status its insert new order ??? what might be the problem.??? couldnt find any articles abut rest api how to use

**Comment by ankitdwivedi** [comment]
Hello, I want to update product in woocommerce but don't know how to use update a product rest api. 
please help me in this.

**Comment by je-rodriguez** [comment]
hello there,

I have been working with the API in trying to update a product variation, but I'm having trouble.
Is there a way to update a single product variation? Here is what I'm using:

/wc-api/v2/products/<id>

{
	"product": {
		"variations": [{
			"id": 145,
			"stock_quantity": 13
		}]
	}
}


Is my json formatted incorrectly? is there a different way to specify a variations?

**Comment by samuelcar** [comment]
I'm having a similar issue as @je-rodriguez , is there a way to update just a specific variation?

**Comment by je-rodriguez** [comment]
@samuelcar I actually figured out how to update a specific variation.
Using the Update a Product call, use the variation id as opposed to the product id.
In my case, it would be /wc-api/v2/products/145

```
{
    "product": {
           "stock_quantity": 13
    }
}
```

**Comment by Freshclicks** [comment]
This wasn't working for me until I changed 'option' to 'options' and made it an array of values. Even where it was just a single value.

**Comment by ad-on-is** [comment]
I still can't get the variations mapped to the attributes

    $np = array(
			'products' => array(
				array(
					'title' => 'Adis Testet'.time(),
					'sku' => time(),
					'type' => 'variable',
					'attributes' => array(
						array(
							'name' => 'Hardness',
							'slug' => 'attr_var_mattress_hardness',
							'visible' => true,
							'variation' => true,
							'options' => array(
								'hard', 'medium', 'soft'
							)
						)
					),
					'variations' => array(
						array(
							'sku' => 'VA'.time(),
							'attributes' => array(
								array(
									'slug' => 'pa_attr_var_mattress_hardness',
									'option' => 'hard'
								)
							)
						),
						array(
							'sku' => 'VB'.time(),
							'attributes' => array(
								array(
									'slug' => 'pa_attr_var_mattress_hardness',
									'option' => 'soft'
								)
							)
						)
					)
				)
			)
		);


In the backend i get two variations. None of them has a hardness assigned. Both have the selectbox saying "Every hardness"

**Comment by mjpramos** [comment]
I have the same issue.

**Comment by isZZ** [comment]
Did anyone find an answer to the 'variations not being mapped to the attributes' issue mentioned above. I'm having to manually select the attribute on product pages.

**Comment by isZZ** [comment]
When adding the product below with the WP API Client's, I get a new blank variation added every time I run 'create/update' on top of the tests1 and tests2 variation. The blank variations add up when running a daily cron job. Any thoughts? 

`$np = array(
							'title' => 'test',
							'sku' => 'test',
							'type' => 'variable',
							'attributes' => array(
									array(
											'name' => 'Size',
											'visible' => true,
											'variation' => true,
											'options' => array(
												'small', 'medium'
											)
									)
							),
							'variations' => array(
									array(
											'regular_price' => 10,
											'sku' => 'tests1',
											'attributes' => array(
													array(
															'name' => 'Size',
															'option' => 'small'
													)
											)
									),
									array(
											'regular_price' => 20,
											'sku' => 'tests2',
											'attributes' => array(
													array(
															'name' => 'Size',
															'option' => 'medium'
													)
											)
									)
							)
    );`

**Comment by cs090006** [comment]
I found a solution

`'variations' => array(
			 	array(
					'sku' => date('His').'_1',
			 		'regular_price' => '29.98',
			 		'attributes' => array( 
			 			array( 
			 				'id' => date('YmdHis', strtotime('+2 seconds')),
			 				'slug'=>'color',
			 				'name'=>'color',
			 				'option'=>'red'	
			 					
			 			)
			 			
			 		) 
			 	),
			 	array(
					'sku' => date('His').'_2',
			 		'regular_price' => '29.98',
			 		'attributes' => array( 
			 			array( 
			 				'id' => date('YmdHis'),
			 				'slug'=>'color',
			 				'name'=>'color',
			 				'option'=>'black'
			 			)
			 		) 
			 	)
			)
`

works for me

**Comment by smtech12** [comment]
**NOTE : i am using wooCoommerece v3 version & i already wasted my 3 to 4 days on that** ,
 
i am facing an issue in product variation post.
i am doing it by two ways 
First:
created json of product with variations .... but the issue is it's posted successfully but not showing select attributes in variations. see attachment for better clearance. 
Second:
created product by _WCObject.PostProduct((Product Model)) without variation and get in success return product id ... then again i am hitting  _WCObject.UpdateProduct(result.Id, Product Model) for variation update with product id 

let me know i am going in right direction or wrong ...?
second thing is which parameters are necessary for product variations detail ???

here is my Variation product Json 

{"title":"Variation Product Testing","type":"variable","sku":"Variationproduct","price":"100","regular_price":"100","sale_price":"120","managing_stock":true,"stock_quantity":10,"in_stock":true,"shipping_required":true,"shipping_taxable":true,"description":"<p>Variation Product Testing&nbsp; &nbsp;Variation Product Testing&nbsp; &nbsp;Variation Product Testing<br></p>","short_description":"<p>Variation Product Testing&nbsp;Variation Product Testing&nbsp;Variation Product Testing&nbsp;Variation Product Testing<br></p>","categories":["24"],"attributes":[{"name":"Color","slug":"Color","position":0,"visible":true,"variation":true,"options":["Black","Blue","Purple"]}],"default_attributes":[{"name":"Color","slug":"Color","option":"Black"},{"name":"Color","slug":"Color","option":"Blue"},{"name":"Color","slug":"Color","option":"Purple"}],"purchase_note":"no condition note","variations":[{"sku":"Variationproduct1","image":[{"id":86172,"created_at":"2017-11-20T16:51:33.3991874+05:00","src":"http://demo.kcompute.com:8073/Images/2175/Products/b19c7f95-6fb0-4116-a933-673234d14351.png","title":"Woocommerce Image","alt":"","position":1}],"attributes":[{"name":"Color","slug":"Color","variation":true,"options":["Black"]}]},{"sku":"Variationproduct2","image":[{"id":86173,"created_at":"2017-11-20T16:51:33.4051774+05:00","src":"http://demo.kcompute.com:8073/Images/2175/Products/b19c7f95-6fb0-4116-a933-673234d14351.png","title":"Woocommerce Image","alt":"","position":1}],"attributes":[{"name":"Color","slug":"Color","variation":true,"options":["Blue"]}]}]}

**Comment by strarsis** [comment]
Related issue: https://github.com/woocommerce/wc-api-php/issues/157

**Comment by anveshSingh417** [comment]
@claudiosanches 
Hey, thanks for the info, I wanted to know, How can I add attributes for a specific product, using REST API. Or I can put it like this in the context of UI, How to add some variation attributes on the Attributes tab using REST API. When I create a product variation and hasn't set the attributes through UI, I am not able to see my variations. However, after manually setting attributes (through UI), I was able to see the product variation but my attribute was not set with the term which I put in my REST request.
