### ISSUE TITLE
WC_Settings_API required options

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#6083]
Maybe it would be cool to have required options for when we are creating integrations.

Thus if the user does not fill, show alerts saying that they are required fields.

I have done this in a lot of plugins, but if it had support in core would be much simpler.

**Comment by riteshpanchal1** [comment]
:+1:

**Comment by claudiosmweb** [comment]
This works really great with HTML5.

@ragulka I tested email and number, you can use the `custom_attributes` to set the number range.

I'm thinking of maybe just add a new attribute "required" and use with HTML5.
