### ISSUE TITLE
Refactor API error handling to use WC_API_Exception

### ISSUE THREAD

**Issue by maxrice** [woothemes/woocommerce#6138]
The `WC_API_Exception` class introduced in SHA: c9342d63448453d11f1c3f06e308dbffd1bc3a70 is a more readable way to handle errors during API requests. Currently only the [`WC_API_Orders`](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-orders.php) is making use of the exception class. We should refactor the other remaining methods & classes, along with the API server error handling to use exceptions.

**Comment by claudiosmweb** [comment]
@maxrice all done :)

**Comment by claudiosmweb** [comment]
@maxrice thanks :D
