### ISSUE TITLE
WooCommerce does not fully support pretty permalinks

### ISSUE THREAD

**Issue by rocketeer76** [woothemes/woocommerce#6158]
WooCommerce doesn't fully support SEO friendly url structures like below:
**domain.com/shop/category/subcategory/subsequentsubcategories/product**

without returning the 404 error.

WooCommerce does support the below structure:
**domain.com/shop/category/product**

But that's not SEO friendly, breadcrumb friendly or inventory management system friendly.

Please make WooCommerce support SEO friendly url structures where all subcategories are present in the url without returning a 404 error on the product level. It's a big problem when moving from other e-commerce systems to WooCommerce that you can't set your permalinks properly to reflect the old url structures.

**Comment by ComSeo** [comment]
Hi Bryce I tried your solution as well. But its not going as I hoped. It conflicts with my YOAST Seo plugin. Are there any other updates coming?
