### ISSUE TITLE
Custom "My Account" endpoints

### ISSUE THREAD

**Issue by oropesa** [woothemes/woocommerce#6210]
Hi!

I've seen the need to add more data to "My Account". Show this data is easy because I added the 'woocommerce templates' in my theme and now I can modify them. Problems come when I want to make the edit form to save them. But I solved!

It's really easy. I'm going to track a random example (social data):

**1. I need to register the endpoint where to redirect the edit form.**

So I added in the array of the function `WC_Query::init_query_vars()` the line:
```php
'edit-social' => get_option( 'woocommerce_myaccount_edit_social_endpoint', 'edit-social' ),
```
The class is located in `includes/class-wc-query.php` and the array is from the variable `$this->query_vars`.

1.1 Not necessary, but I wanted to have a custom endpoint name, so I added in the DB table `wp_options` the row.
```
[option_name] woocommerce_myaccount_edit_social_endpoint
[option_value] my-edit-social
````

**2. I need to link the endpoint with a form template**
So I added in the function `WC_Shortcode_My_Account::output()` the lines between the comments:
```php
...
} elseif ( isset( $wp->query_vars['add-payment-method'] ) ) {
    self::add_payment_method( $wp->query_vars['add-payment-method'] );
//ORO EDIT
} elseif ( isset( $wp->query_vars['edit-social'] ) ) {
    wc_get_template( 'myaccount/form-edit-social.php', array( 'user' => get_user_by( 'id', get_current_user_id() ) ) );
//END ORO EDIT
} else {
    self::my_account( $atts );
}
```
The class is located in `includes/shortcodes/class-wc-shortcode-my-account-php`.

**3. I need to call the function which saves the form's data**

So I added in the function `WC_Form_Handler::__construct()` the line:
```php
add_action( 'template_redirect', 'save_my_social_account_details' );
```

The class is located in `includes/class-wc-form-handler.php`.

**4. Now is my developer responsibility to code correctly the form template and the saved function**
This is simple because I have the `form-edit-account.php` and the `save_account_details()` as references.

The most important stuff is to join the template form with the saved function, so in the form it's necessary to have the input
```html
<input type="hidden" name="action" value="save_my_social_account_details" />
```
and in the saved function
```php
if ( empty($_POST[ 'action' ]) || ('save_my_social_account_details' !== $_POST[ 'action' ]) || empty($_POST['_wpnonce']) ) {
    return;
}
```

**My Limitations**

I had to edit the woocommerce plugin and right now I can't upgrade it. For that reason I ask you to improve this functionality to extend it.

**To improve the point 1:** Add an apply_filters() to $this->query_vars.
**To improve the point 1.1:** It's the responsibility of the developer.
**To improve the point 2:** Refactoring the function and add a do_action() for the code which are into 'elseif'.
**To improve the point 3:** Add a do_action() to encapsulate the rest of the add_action().
**To improve the point 4:** It's the responsibility of the developer.

Finally, to be completely awesome, all this could be encapsulated into a function:
```php
register_myaccount_endpoint( $endpoint_name, $endpoint_db_name, $template_function, $saved_function )
```
In my example it would be
```php
register_myaccount_endpoint( 'edit-social', 'edit_social', 'call_my_social_form_template', 'save_my_social_account_details')
```

**Extra**
I found the issue #3708 and what I ask is in the roadmap. I hope my issue helps you to have the functionality ahead of schedule.

Thanks!

**Comment by vanbo** [comment]
@mikejolley , I can help with this, so devs or anyone can add their own custom endpoints. 
But for I want some pointers as to how it would be best handled.

1.We add a filter to the `WC_Query` `init_query_vars()`, so endpoints can be modified, but the method is called earlier than the theme has access, so theme authors can't use it. If we are to filter it(and themes have access to it), it needs to be at least at `after_setup_theme`. What do you think, can you give some feedback?
2. Then we can add a filter to the My Account page (may be to the Checkout, too, if needed), to detect the query_var and call the appropriate template. Something like this (https://github.com/woothemes/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-my-account.php#L60): 
```
// Allow for plugins/themes to detect the custom endpoint to My Account page
// Should return the matched endpoint
$custom_endpoint = apply_filters( 'wc_my_account_display_custom_endpoint', false );

if ( $custom_endpoint ) {

	// Allow for special output on the matched
	do_action( 'wc_my_account_endpoint_'. $custom_endpoint, $atts );

} elseif ( ! empty( $wp->query_vars['view-order'] ) ) {

	self::view_order( absint( $wp->query_vars['view-order'] ) );

} elseif ( isset( $wp->query_vars['edit-account'] ) ) {

	self::edit_account();

} elseif ( isset( $wp->query_vars['edit-address'] ) ) {

	self::edit_address( wc_edit_address_i18n( sanitize_title( $wp->query_vars['edit-address'] ), true ) );

} elseif ( isset( $wp->query_vars['add-payment-method'] ) ) {

	self::add_payment_method( $wp->query_vars['add-payment-method'] );

} else {

	self::my_account( $atts );

}
```

3. This can also be combined with endpoint settings in the admin, so the user can edit the endpoint, but I think this is entirely up to the dev who adds the custom endpoint to add.

Any feedback is appreciated. I think I already have this working, just need to be sure that this is what's needed.

**Comment by moomal** [comment]
I'm sure this is my fault, but I can't get my custom endpoint working. I'd really appreciate any help I can get on this. 

As far as I understand it, at its simplest (say you just wanted to just display a static page), this would mean:

1. in `WC_Query::init_query_vars()` add to the array:
`'page-name' => 'page-name',`

2. in `WC_Shortcode_My_Account::output()` add:
```
} elseif ( isset( $wp->query_vars['page-name'] ) ) {
    wc_get_template( 'myaccount/page-name.php', array( 'user' => get_user_by( 'id', get_current_user_id() ) ) );
```
3. Create `page-name.php` and save it with the other myaccount templates.

I have done all this, but when I visit mysite.com/my-account/page-name/ I get a 404 error. What am I missing?

**Comment by vanbo** [comment]
@moomal just resave your permalinks or the Account endpoint from the settings.

**Comment by oropesa** [comment]
@moomal, @vanbo is right. Or you could try mysite.com/my-account/?page-name

**Comment by moomal** [comment]
Thank you!

**Comment by mikejolley** [comment]
I've moved this one to the Trello Roadmap until we plan on building it. I don't think this is likely to be 2.4, but we'll reopen this issue once decided. https://trello.com/c/D3Vo1ccI/55-custom-my-account-page-endpoints

**Comment by nvartolomei** [comment]
@mikejolley any news about this one?

**Comment by robinnatur** [comment]
Upvoted on Trello. I had to implement Oropesa solutions on WooThemes subscriptions to add a custom endpoint: edit-subscription. Just adding it here if it is to value too see how i used custom endpoint in WP->WC->WCS. Sorry if not (just delete), im pretty new to this.

1. Copied the "View" function and made it edit in \woocommerce-subscriptions\includes\class-wc-subscription.php:
```
	//RPE EDIT 04.11.15
	 /**
	 * Now uses the URL /my-account/edit-subscription/{post-id} when editing a subscription from the My Account Page.
	 * 
	 * @since 2.0
	 */
	public function get_edit_order_url() {
		$edit_subscription_url = wc_get_endpoint_url( 'edit-subscription', $this->id, wc_get_page_permalink( 'myaccount' ) );

		return apply_filters( 'wcs_get_edit_subscription_url', $edit_subscription_url, $this->id );
	}//END RPE EDIT 04.11.15
```

2. Change in \woocommerce-subscriptions\includes\class-wcs-query.php

public function init_query_vars
```
			//RPE EDIT 04.11.15
			'edit-subscription' => get_option( 'woomps_myaccount_edit_subscriptions_endpoint', 'edit-subscription' ),
			//END RPE EDIT 04.11.15
```
public function add_breadcrumb
```
		//RPE EDIT 04.11.15
		if ( $this->is_query( 'edit-subscription' ) ) {
			$crumbs[] = array( $this->get_endpoint_title( 'edit-subscription' ) );
		}
		//END RPE EDIT 04.11.15
```
public function change_endpoint_title
```
		//RPE EDIT 04.11.15
		if ( $this->is_query( 'edit-subscription' ) && in_the_loop() ) {
			$title = $this->get_endpoint_title( 'edit-subscription' );
		}
		//END RPE EDIT 04.11.15
```
public function get_endpoint_title
```
			//RPE EDIT 04.11.15
			case 'edit-subscription':
				$subscription = wcs_get_subscription( $wp->query_vars['edit-subscription'] );
				$title        = ( $subscription ) ? sprintf( _x( 'Subscription #%s', 'hash before order number', 'woocommerce-subscriptions' ), $subscription->get_order_number() ) : '';
				break;
			//END RPE EDIT 04.11.15
```
3. Change in \woocommerce-subscriptions\includes\class-wcs-template-loader.php
public static function add_view_subscription_template
```
		//RPE EDIT 04.11.15
		if ( 'myaccount/my-account.php' == $template_name && ! empty( $wp->query_vars['edit-subscription'] ) ) {
			$located = wc_locate_template( 'myaccount/edit-subscription.php', $template_path, plugin_dir_path( WC_Subscriptions::$plugin_file ) . 'templates/' );
		}
		//END RPE EDIT 04.11.15
```

**Comment by Mqrius** [comment]
```
// Because Woocommerce hasn't made appropriate filters on their endpoint handling, we have to hijack its internal operation like this
add_filter('woocommerce_checkout_shortcode_tag', 'nullify_checkout_shortcode');
function nullify_checkout_shortcode($shortcode) {
	return $shortcode . '_';
}
// Instead of Woocommerce handling [woocommerce_checkout] itself, we pass it through our code, so that we can intervene if necessary.
add_shortcode( 'woocommerce_checkout', 'hijack_checkout_shortcode' );
function hijack_checkout_shortcode($atts){
	global $wp;
	if ( ! empty( $wp->query_vars['bitcoin-step-2'] ) ) {
		return bitcoin_step_2($wp->query_vars['bitcoin-step-2']);
	} else {
		$return = WC_Shortcodes::checkout($atts);
		return $return;
	}
}
```

...I feel unclean.

**Comment by claudiosanches** [comment]
@Mqrius Good for you :)
But this issue talks about custom endpoints for "My Account" and in your case you not even need a second endpoints on checkout page.
