### ISSUE TITLE
Issue with the shop page pagination?

### ISSUE THREAD

**Issue by piotrkunicki** [woothemes/woocommerce#6220]
I have a problem with pagination on the main shop page after update WC to 2.2.2.

Before update, when I click the second page - the URL was in this format:
http://localhost:8888/test/?post_type=product&paged=2
but after the update:
http://localhost:8888/test/?post_type=product#038;paged=2
instead of & I can see ```#038;``` HTML char and link doesn't work.

I've tested on TwentyThirteen default theme:
![screen](https://cloud.githubusercontent.com/assets/2950258/4232270/ab20d388-399a-11e4-8d57-163205d980ee.jpg)

**Comment by JuKa87** [comment]
I am having the same issue using 2.2.10

**Comment by Rashid83** [comment]
hello i face one big problem please solved my problem.  plz  solve  this error
i can't go next page of product  in place of #038 i put & then it automatically send me 2nd page of product
http://localhost/jugal/?post_type=product#038;paged=2

**Comment by ChromeOrange** [comment]
@mikejolley seeing this issue on ticket 246131 WC 2.2.10

I've modified the template file temporarily with a str_replace

```
		echo str_replace( '#038;','&', paginate_links( apply_filters( 'woocommerce_pagination_args', array(
			'base'         => esc_url( str_replace( 999999999, '%#%', remove_query_arg( 'add-to-cart', htmlspecialchars_decode( get_pagenum_link( 999999999 ) ) ) ) ),
			'format'       => '',
			'current'      => max( 1, get_query_var( 'paged' ) ),
			'total'        => $wp_query->max_num_pages,
			'prev_text'    => '&larr;',
			'next_text'    => '&rarr;',
			'type'         => 'list',
			'end_size'     => 3,
			'mid_size'     => 3
		) ) ) );
```

**Comment by mikejolley** [comment]
@ChromeOrange See https://github.com/woothemes/woocommerce/issues/7011 It will be in 2.3

**Comment by Krishnag09** [comment]
@ChromeOrange - where did you place this code. Which file of the template. 

I have a lot of custmisation on the woocomerce, so i would like to just update the required file for making this work. @mikejolley - can you please let me know which file to update.  Can i copy from the latest version and place it on my website.

Any info/help will be really appreciated.

**Comment by Krishnag09** [comment]
Hey, I placed this code into the templates>>loops>>pagination.php  The #38 issue still persists..

Here is my complete code. The link is http://lambbooks.org/?product_cat=english

All options in permalinks are set to default.

<?php
/**
 * Pagination - Show numbered pagination for catalog pages.
 *
 * @author 		WooThemes
 * @package 	WooCommerce/Templates
 * @version     2.2.2
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

global $wp_query;

if ( $wp_query->max_num_pages <= 1 ) {
	return;
}
?>
<nav class="woocommerce-pagination">
	<?php
  echo str_replace( '#038;','&', paginate_links( apply_filters( 'woocommerce_pagination_args', array(

           'base' => esc_url_raw( str_replace( 999999999, '%#%', remove_query_arg( 'add-to-cart', get_pagenum_link( 999999999, false ) ) ) ),
           'format' => '',
           'current' => max( 1, get_query_var( 'paged' ) ),
           'total' => $wp_query->max_num_pages,
           'prev_text'    => '&larr;',
            'next_text'    => '&rarr;',
            'type'         => 'list',
            'end_size'     => 3,
            'mid_size'     => 3
        ) ) ) );
	?>
</nav>
