### ISSUE TITLE
Tax-related bug with variable product 'get_price_html' and 'get_variation_price' logic.

### ISSUE THREAD

**Issue by franticpsyx** [woothemes/woocommerce#6504]
Steps to reproduce:

Check the following WC Settings: 

1) shop prices displayed including tax and 
2) prices defined excluding tax.

Create a variable product with 2 variations. One has a price of 10 units and belongs to a tax class with 20% tax, and the other has a price of 11 units and belongs to a tax class with 0% tax.

Now, the saved ```_min_variation_price``` will be 10 and the ```_max_variation_price``` 11.

As a result, the range displayed by ```get_price_html``` will be: 12$ -- 11$, which is wrong.

One solution that will help keep ```get_price_html``` light would be to introduce new meta, saved during variable product sync:

- ```_{min/max}_variation_{incl/excl}_tax_{price/regular_price/sale_price}```

and 

- ```_{min/max}_variation_{incl/excl}_tax_{price/regular_price/sale_price}_variation_id```

Another solution would be to introduce some new  `get_variation_{regular_ / sale / }price` logic, specifically in the case that variations do not all have the same tax rate. This could be indicated by a single meta field used for that purpose. This new (slow) logic will just loop through variations, grab the necessary price meta, add tax and return the min / max value.

( On a side note, I am not entirely convinced about the usefulness of having tax classes at variation level, but that's mainly because I haven't come across any shops that use them. In most cases, tax class differences apply to products of different scope / use from a tax law perspective. Variations should be expected to share the same basic properties with their parent by nature. The tax class could easily be one such property. )

**Comment by mikejolley** [comment]
To make this problem more complex, there could potentially be issues when:

- There are more than 2 tax rates used
- The user location changes and thus different tax rates are used
- The store owner adds a suffix with the ex vat price as well as the inc vat price

Therefore I think the suggestion of _has_multiple_variation_tax_rates should be used,   but a range should be avoided.
