### ISSUE TITLE
Cart ajax

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#6734]
We'll change the actions in the cart page to work with ajax:

- [ ] Quantity button/update cart button
- [ ] Coupons
- [ ] Shipping
- [ ] Cart Totals

**Comment by BFTrick** [comment]
Pippin and Brad talk about removing the update button and using ajax instead on [Apply Filters Episode 37](http://applyfilters.fm/podcast/episode-37/) right around 11:30.

**Comment by mikejolley** [comment]
@BFTrick @claudiosmweb I think this is a feature we can do without in the onboarding release to speed release. Let's revise for future milestone.

**Comment by BFTrick** [comment]
This definitely isn't critical. I'm fine punting it.

**Comment by BFTrick** [comment]
We might be looking at this for 2.5. We need to be careful to not upset existing stores which don't expect the update button to disappear. It should be an option they can turn on.

For new stores we could either have an option to turn off Ajax or we can make the choice for them and automatically use Ajax.

@claudiosmweb can you add another todo for this?

**Comment by claudiosmweb** [comment]
@BFTrick absolutely do not intend to remove any buttons and no changes in the layout in any way.

**Comment by claudiosmweb** [comment]
@BFTrick here one example of I'm saying: http://ragob.com/wooajaxcart/ (add some product to the cart and try change the quantity).

**Comment by BFTrick** [comment]
Oh that's fantastic. I like the idea of keeping the button and still updating via ajax. The button also serves as a notice to the user about what's going on. I'm totally fine with this. :) :+1:

**Comment by claudiosmweb** [comment]
@BFTrick Yeah, I don't want to risk removing the button and let people angry with us :p

**Comment by mikejolley** [comment]
This is such a small, easy to code thing there should really be no issue at all with putting it in 2.5 regardless of other items. Lets just :shipit: with 2.5. @claudiosmweb

**Comment by BFTrick** [comment]
Just had a chat with @jameskoster and we should make sure that when someone adds a product to their cart via Ajax that the cart widget should update.

Relevant idea: http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/5116719-ajax-refresh-for-quantity-update-on-cart-page

**Comment by DavidAnderson684** [comment]
This will impact plugins that respond to cart quantities, so please make sure there are lots of ways to hook into it and respond. From my brief experience, changing the displayed info messages and errors on a cart page when something changes isn't easy. (I have a couple of plugins that respond to changes in shipping method).

**Comment by WPprodigy** [comment]
Another thing to consider with this is plugins that do discounts like Dynamic Pricing. Like when the cart quantity is > 10, then apply a 50% discount.

Would those hooks still be able to get triggered on quantity updates? I'm thinking yes, as something similar is needed for coupons I'd think.

**Comment by claudiosmweb** [comment]
Seems like that you guys are not understand what we intend to do here...

Things we will do:

- Add a JS file to make it work with Ajax
- New ajax methods

Things we will NOT do:

- Change template files
- Remove actions or filters
- Change the way the cart works
- Forcing everyone to use ajax
- Deprecate functions or methods

If any of these items from the list of "Things we will NOT do" is necessary, we'll abandon this idea.

**Comment by paulparauan** [comment]
So, you changed the cart page, now on my website averytime you ad something in the cart, it doubles the quantity. If you hit back (ar move to anoter page of the shop or product) it doubles the quantity from the one more time.

**Comment by MrJoshFisher** [comment]
Where is the code to update the price when the quantity changes ?

**Comment by claudiosmweb** [comment]
Closed in favor of #10342
