### ISSUE TITLE
Product Listing Quick Edit Not Setting Product Stock Status Correctly

### ISSUE THREAD

**Issue by Jplus2** [woothemes/woocommerce#6789]
* Go to woocommerce product listing on the back end
* on the list of products, click quick edit of any of the product
* Check the Manage Stock? checkbox
* Input 0 on Stock Qty or just leave the default value of 0
* Leave the rest as is and click update button

on the product listing, it looks as its as if woocommerce does things ok, but click on that product page
look at the inventory status, you will see the Stock Status as "In Stock" and the Stock Qty as 0

I further proved it by examining the post meta

```
[_stock_status] => Array
        (
            [0] => instock
        )
```
Woocommerce version: 2.2.8
Wordpress version: 4

**Comment by claudiosmweb** [comment]
Works correctly in the latest version of WooCommerce.
