### ISSUE TITLE
[WC-API-V2] Ability to login customer

### ISSUE THREAD

**Issue by BENMESSAOUD** [woothemes/woocommerce#6816]
Hi, 

I would like to revoke #6133 issue because I think is important to have an authenticate endpoint for mobile apps. With the current version of Woocommerce API, anyone is able to get access to other accounts (using email endpoint) and make orders there or get all private informations like address, phone number, avatar image, etc. and this makes the email's endpoint insecure! 
I think that the method created by @artemkolotilkin is pretty good. may be the password should be md5 crypt when comes to the server side for more security.
I think that most of mobiles application using woocommerce API will needs this authentification step.

@maxrice please let me know your thoughts and if this could be in future version.

**Comment by claudiosmweb** [comment]
This is not a good idea.

https://github.com/woothemes/woocommerce/pull/6133#issuecomment-54008484

**Comment by photoboothowners** [comment]
Some method to authenticate would be greatly useful. Could be locked down to https only?

**Comment by okezieokpara** [comment]
@claudiosmweb why do you think thats a bad idea

**Comment by LifetimeDev** [comment]
I got around this login issue by using WP OAuth Server plugin, which enable me to authenticate users and retrieve their customer ID, hence display orders data securely and authentically. I hope woocommerce REST API integrate such mechanism to enable online customers to track orders information securely.
