### ISSUE TITLE
[WC-API-V2] Ability to send link by email to customer to renew password

### ISSUE THREAD

**Issue by BENMESSAOUD** [woothemes/woocommerce#6827]
Hi, 
## The problem

in the API there is no endpoint that allows to send a link by email to renew password when user lost or forget their password.

## The Solution

So i made this endpoint in *woocommerce/includes/api/class-wc-api-customers.php*
and i would like to know your opinion.
here the endpoint route : 
```
# POST /customers/renewpassword
 $routes[ $this->base . '/renewpassword' ] = array(
 array( array( $this, 'lost_password' ),   WC_API_SERVER::CREATABLE | WC_API_Server::ACCEPT_DATA ),
 );
```
Here the method implementation : 
```
 /**
 * retreive password
 * @since 2.x
 * @param array $data
 * @return array
 */
public function lost_password( $data ) {
    // Checks the username.
    if ( ! isset( $data['username'] ) ) {
        return new WP_Error( 'woocommerce_api_missing_customer_username', sprintf( __( 'Missing parameter %s', 'woocommerce' ), 'username' ), array( 'status' => 400 ) );
    }
    $username = $data['username'];
    if ( is_email($username) )
    {
        $user = get_user_by( 'email', $username );
        if ( $user ) $username = $user->user_login;
    }
    else{
        $user = get_user_by( 'login', $username );
    }
    if ( ! $user ) {
        return new WP_Error( 'woocommerce_api_invalid_customer_email', __( 'Invalid customer Email', 'woocommerce' ), array( 'status' => 404 ) );
    }
    $_POST['user_login'] = $username;
    
    return array( 'result' => WC_Shortcode_My_Account::retrieve_password() );
}
```

This method was tested and work fine for me. 

@claudiosmweb  Please let me know what do you think.

**Comment by claudiosmweb** [comment]
@maxrice What do you think? Not sure if we should have endpoints of this type to send email only.

**Comment by maxrice** [comment]
@claudiosmweb Yeah this feels related to a login endpoint, which we decided not to include. I'd vote for not adding this right now.

@BENMESSAOUD what's your use case for this? Are you working within a mobile app and need some way to login customers/allow them to reset their password?

**Comment by claudiosmweb** [comment]
@BENMESSAOUD You can also create custom endpoints.

```php
add_action( 'woocommerce_api_loaded', 'my_api_loaded' );
add_filter( 'woocommerce_api_classes', 'my_api_classes' );

function my_api_loaded() {
     include_once( 'PATH/TO/API/CLASS.php' );
}

function my_api_classes( $apis ) {
	$apis[] = 'My_Custom_Customers_API';

	return $apis;
}
```

And the api class file:

```php
class My_Custom_Customers_API extends WC_API_Resource {

	/**
	 * The route base.
	 *
	 * @var string
	 */
	protected $base = '/custom-customers';

	public function register_routes( $routes ) {
		# POST /customers/renewpassword
		$routes[ $this->base . '/renewpassword' ] = array(
			array( array( $this, 'lost_password' ), WC_API_SERVER::CREATABLE | WC_API_Server::ACCEPT_DATA ),
		);
	}

	/**
	 * retreive password
	 * @since 2.x
	 * @param array $data
	 * @return array
	 */
	public function lost_password( $data ) {
		// Checks the username.
		if ( ! isset( $data['username'] ) ) {
			return new WP_Error( 'woocommerce_api_missing_customer_username', sprintf( __( 'Missing parameter %s', 'woocommerce' ), 'username' ), array( 'status' => 400 ) );
		}

		$username = $data['username'];
		if ( is_email( $username ) ) {
			$user = get_user_by( 'email', $username );

			if ( $user ) {
				$username = $user->user_login;
			}
		} else {
			$user = get_user_by( 'login', $username );
		}

		if ( ! $user ) {
			return new WP_Error( 'woocommerce_api_invalid_customer_email', __( 'Invalid customer Email', 'woocommerce' ), array( 'status' => 404 ) );
		}
		
		$_POST['user_login'] = $username;

		return array( 'result' => WC_Shortcode_My_Account::retrieve_password() );
	}
}

**Comment by BENMESSAOUD** [comment]
Hi  @claudiosmweb @maxrice 
thank you for your response. 
@maxrice I'am trying to build an iOS woocommerce framework. I was asking how can i share the project in this space spot everyone can contribute :)

@claudiosmweb making a costume endpoint don't make easier to have a public framework ;)

**Comment by okezieokpara** [comment]
pls I need a way for users to manage their accounts i.e login, logout and register from within my mobile app.

**Comment by BasicPro** [comment]
Yes I do think too that it would be nice to have login and password reset in the WooCommerce API, I'm implementing it myself as Benmessaoud did too, I don't understand why you decide it is not a good idea, can you explain? you only need to add 2 endpoints more (login and password lost) and there're users that already implemented working endpoints.

Regards

**Comment by mikejolley** [comment]
@BasicPro you don't login and logout from WooCommerce, you do so to WordPress. So why should it be in the WooCommerce API? I don't think it's a good fit.

**Comment by BasicPro** [comment]
@mikejolley if you register a user or use the lost password feature of Wordpress the email sent to the user won't be using the WooCommerce email system, it will send the default Wordpress email. WooCommerce replaces login, register and password functions on the web site, so why not do it in the API too? Also there's no secure API to login a user, the ones I've seen are petty insecure, so why not be one step forward for little effort?

**Comment by mikejolley** [comment]
@BasicPro Claudio and Max will know more about the history, but the API is more geared towards accessing and writing data that interacting as a customer. It wasn't built with that in mind. I don't think it's little effort either; there would be security concerns.

**Comment by maxrice** [comment]
@BasicPro see the discussion in #6133 -- I don't think a `/login` endpoint will be implemented, at least not in WC core, so you'd have to add a custom plugin to expose that. The reset password endpoint is a more interesting idea (since it's reasonable that an external app might need to trigger a password reset for a user) and I could see it in a future release, provided there's interest from other users in making it available.

**Comment by BasicPro** [comment]
Thanks @mikejolley  and @maxrice for your reply. I understand your point, it would be nice to have the password reset implemented but anyway I already implemented both myself, I was just letting you know my opinion. 

I guess there would be some security concerns over http, do you see any extra security concerns over https I might not be aware of?

Regards

**Comment by maxrice** [comment]
@BasicPro no specific security concerns provided it's HTTPS-only
