### ISSUE TITLE
Permalinks and Windows hosting and wc-api

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#6832]
>return esc_url_raw( trailingslashit( home_url( '/wc-api/' . $request, $scheme ) ) );

if permalinks look like

![](https://dl.dropboxusercontent.com/s/gbgh78e6bqlupjx/2014-11-24%20at%2023.37.png?dl=0)

then it doesn't work

Given how rare this is maybe a filter is the best way?

>return esc_url_raw( trailingslashit( home_url( apply_filters(woocommerce_permalinks_windows_fix, '/wc-api/') . $request, $scheme ) ) );

**Comment by mikejolley** [comment]
I don't think we should support this edge case - there are workarounds for IIS users.

- Filtering the home_url http://wordpress.stackexchange.com/questions/102523/home-url-on-iis-missing-permalink-index-php
- Removing the index.php https://wordpress.org/support/topic/removing-indexphp-in-permalinks-using-iis-8?replies=5

Could be documented @ChromeOrange?

cc @claudiosmweb

**Comment by claudiosmweb** [comment]
I agree with you @mikejolley.
