### ISSUE TITLE
WC_Sessions performance on large sites

### ISSUE THREAD

**Issue by deltafactory** [woothemes/woocommerce#6846]
Saving a change to a session to the `wp_options` table flushes the options cache. On large sites, this negates the presence of the object cache and can lead to massive performance issues.

I have observed this on 2.0.x but understand that this has since been mitigated in later versions by deferring creation of the session. This can still happen too frequently and bloat the `wp_options` table significantly - something that may impact smaller sites without caching as well. I haven't compared performance of deferred sessions with 2.0.x but would be interested in others' observations.

In my own case, I've separated session data into a separate table which also benefits from simpler queries and expiration logic. Is this something that might be considered for core?

Given its close relationship with the WP_Sessions implementation, it might be something worth exploring in that context as well.

**Comment by deltafactory** [comment]
I'm currently working on testing and profiling this code. I've added object cache support and can push updates to github this week.

In the `WC_Session` abstract class, `__unset()` checks to see if the property `isset()` before dirtying the session. Is there a reason the same check isn't done to `set()` using `===`?

In early testing, the main offender of unnecessary session-dirtying is `wc_clear_notices()` which spends a lot of time setting `wc_notices` to `null` when it already was.

For the moment, I'm testing this in the custom handler:
```PHP
	public function set( $key, $value ) {
		if ( $value !== $this->get( $key ) ) {
			parent::set( $key, $value );
		}
	}
```
I think that core's handler would benefit from either this, or a targeted optimization on `wc_clear_notices()` though there may be some complex comparisons that would cause issues.

**Comment by deltafactory** [comment]
https://github.com/deltafactory/woocommerce-session-table-handler
Updated to 1.1. Feedback welcome.

**Comment by kloon** [comment]
Running this on woothemes.com now for a couple of weeks without any issues https://github.com/kloon/woocommerce-large-sessions Will go live soon as a plugin for wp.org at https://wordpress.org/plugins/woocommerce-large-sessions/ just need to upload it

**Comment by toddlahman** [comment]
@kloon Have you looked into this issue? https://github.com/kloon/woocommerce-large-sessions/issues/1

**Comment by kloon** [comment]
@toddlahman are you also experiencing it?

**Comment by toddlahman** [comment]
@kloon Not yet. Just curious if this issue had been explored before deploying it in a persistent cache environment.

**Comment by kloon** [comment]
@toddlahman we run object caching and use it without any issues like that

**Comment by toddlahman** [comment]
@kloon Testing with Memcached now. Not seeing any issues at this time.
