### ISSUE TITLE
Removal of Store Notice

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#6861]
I'd like to discuss the removal of the store notice feature/option from WC as 2.3 approaches.

It really doesn't seem to be an essential part of most stores, but rather something that should be a free extension.

I suggest removing it and adding the functionality into a plugin. If a user has already set up a store notice before updating, we can check for this and display a notice after updating, prompting them to get the free plugin. The plugin can then use the same setting ID from WC core, so there's an easy transition.

We can then add a couple cool features to the plugin like custom colors, display a random product link, etc.

Putting my :hand: up to do this if you agree.

**Comment by bryceadams** [comment]
@BFTrick so we leaving this for 2.4 (based on tracking feedback)? Can probably close and then add to roadmap for now then.

**Comment by BFTrick** [comment]
Yeah. Let's close and we can always reopen down the line if no one uses this feature. :+1:

**Comment by ChromeOrange** [comment]
It's my favourite WooCommerce option, I vote it stays!
