### ISSUE TITLE
Webhook UI

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#6912]

**Comment by BFTrick** [comment]
Hey @claudiosmweb , love all the work you did for the webhooks. I played around with it and it looks nice. I have a few Qs.

Should webhooks be a top level menu item?
![webhooks_ _woocommerce_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/5620323/10753226-94e8-11e4-892d-2778c910e79b.png)

I'm not convinced. Very few of our users will actually know what a webhook is let alone how to use one. This seems like more of an advanced setting that a small percentage of store owners will setup. What do we think about putting this under Integrations? It basically is another way to integrate with a 3rd party service and makes a bit more sense there.

**Comment by mikejolley** [comment]
@BFTrick Webhooks only get shown when the API is enabled. Do you not think it's safe to assume if a user knows about the API, they will understand webhooks too?

**Comment by maxrice** [comment]
API is enabled by default so all users would see this, no? I think putting it under Integrations is a good idea :)

**Comment by mikejolley** [comment]
I didn't realise it was enabled by default. Why is that? :)

**Comment by claudiosmweb** [comment]
We can have a new option for enable and disable this too.

**Comment by maxrice** [comment]
It's enabled by default because it makes it easier to 3rd party integrations to work with the API, so the setup can simply be "go copy your API keys" rather than, "enable API, then go copy your keys". The index doesn't show any information which isn't already publicly accessible, so net/net it's a good thing™ to have it enabled by default :)

@claudiosmweb I'd rather see the Webhook menu item elsewhere than a enable/disable option for the UI.

**Comment by BFTrick** [comment]
A new option to enable / disable the webhooks hides webhooks for people who don't need them which is nice. It's still in a bit of an awkward place and it's an extra setting we wouldn't need if the webhooks page had more context. :(

**Comment by claudiosmweb** [comment]
I'm open to suggestions :)
I think we could put an option for it after the `Enable the REST API`.
We cann't super hide it, because hopefully soon third parties will build integrations using Webhooks and this will greatly facilitate for users.

**Comment by maxrice** [comment]
I like @BFTrick's suggestion to make it section under "Integrations" -- it'll be a bit of work to fit the list table in there, but it makes sense and keeps it slightly hidden from regular users who don't need to access it.

:-1: on an enable/disable for the UI itself, if it's not a sub-menu item, there's no need for a setting.

**Comment by mikejolley** [comment]
Just to throw it out there, will we ever require more screens related to api/web hooks? Reports/logs, more advanced screens for generating keys, Api specific settings?

If we do plan on this, when that time comes I think all of these need to come together under a WooCommerce-submenu with tabs (like the settings section).

**Comment by maxrice** [comment]
Yeah almost certainly, logging and key management probably deserve their own screens at some point.
