### ISSUE TITLE
Cart session not storing properly (REF issue #6743)

### ISSUE THREAD

**Issue by LiamBailey** [woothemes/woocommerce#6924]
Come across a similar issue to #6743 on http://www.huisenthuis.nl/ - this time the same debugging output shows that the cart is completely empty when you come across into https- the suhosin rules are in place in the correct php.ini but still the problem persists, and no caching plugins are in play. Any ideas.

**Comment by claudiosmweb** [comment]
Seems to be working properly.
I tried to reproduce the error, but to no luck.
Have some time that we do not have problems like this.
