### ISSUE TITLE
[API] - Add a visual endpoint for authenticating a store with a third-party service

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#6930]
I'd love to see an endpoint (note: not necessarily an API endpoint, but a WordPress rewrite rule) added for a visual screen for authenticating a WordPress user's access to an app.

*Problem*: Third-party services often require the store manager to input their WooCommerce API keys. This is a confusing process for the store manager and isn't abundantly clear.

To remedy this, I'd propose taking a leaf out of Facebook's tree and creating a similar authentication screen.

# How this could work

The third-party service or app passes through a signed request to our endpoint, as well as their app name and an optional logo image URL (both for presentation purposes only). We could perhaps also pass a parameter to determine what kind of access the service requires, at a minimum (Github does this well).

We could optionally pass through a callback URL here, which would be the URL the store manager would be directed to within the service.

Upon arrival, we check if there is a logged in user. If so, we display the authentication screen, with an option to logout if they are not the correct user.

If not logged in, we redirect to the WordPress (or a custom) login screen, appending a `redirect_to` querystring variable to redirect to the authentication screen.

Once logged in, the user clicks the "Authorize" button. There is potentially an option to select the type of access ("read", "write" or "read/write") on this screen as well.

Once "Authorize" is clicked, the callback URL is fired (default to the referring URL), and is passed the keys necessary for interaction with the WooCommerce API.

This is almost an 0Auth flow, of sorts.

![Example screens](http://f.cl.ly/items/3C1F3Q0327353T2g0y0N/Image%202014-12-10%20at%201.37.06%20PM.png)

Thoughts, @maxrice @justinstern @mikejolley @claudiosmweb @kloon ?

**Comment by claudiosmweb** [comment]
Closed by #8021
