### ISSUE TITLE
Pre-select country select box using geo-location

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#6969]
During the recent testing of our upcoming Taxamo extension, we noticed a nuance with the UX around the country select box at checkout.

It could be useful to include some basic geo-location within WooCommerce core, to attempt to pre-fill the country select box at checkout with the correct country.

Perhaps with a checkbox to turn this on and off, if a store owner doesn't wish to have this feature.

What do you reckon, @barrykooij @mikejolley @claudiosmweb ?

**Comment by mikejolley** [comment]
Checked; geoiprecord looks like it's from the city version and also includes geoIP itself. Will add a check.

**Comment by daigo75** [comment]
@mikejolley That was probably the reason why I added that check (I don't remember exactly, it was very long ago).
