### ISSUE TITLE
Dots in attributes value generates a JS error

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#6986]
We noticed that when we use values like "2.5x2.5", the javascript in add-to-cart-variation.min.js breaks. Chrome Dev Tools Reports the following:

Uncaught TypeError: Cannot read property 'length' of null add-to-cart-variation.min.js?ver=2.2.7:4

But when we remove the dots, it works fine.

**Comment by mikejolley** [comment]
Unable to replicate in 2.2 or 2.3 master. I did this: http://glui.me/?i=bcyzj25fboenhmt/2015-01-05_at_15.32_2x.png/
