### ISSUE TITLE
Product Categories Widget not showing empty categories

### ISSUE THREAD

**Issue by spidrr** [woothemes/woocommerce#6987]
Just posted this against an issue which I subsequently noticed was closed.  As I've spent the best part of a day debugging this I thought i'd raise another issue with the fix.  Apologies for the duplication.

Empty categories are not being displayed in the widget. I am in the process of upgrading my clients site whilst moving it to a better server. The old version of WooCommerce (1.6) that he has, displayed the empty categories in the widget. He wanted the upgraded site to work the same. My client is running v2.2.10 of WooCommerce on the new server.

I tried to override the hide_empty flag by using a 'woocommerce_product_categories_widget_args' filter but this had no effect.

Further investigation showed that the display_elements member function of the WC_Product_Cat_Dropdown_Walker specifically filters out empty categories. This is the problem code.

if ( ! $element || 0 === $element->count ) {
return;
}

The fix is simply to check for the presence and value of the hide_empty flag in the $args variable.

// Get the value of the hide_empty flag. Default to true to as per WP standard
$hide_empty = ( isset( $args[0]['hide_empty'] ) ? $args[0]['hide_empty'] : true );

if ( ! $element || ( 0 === $element->count && $hide_empty ) ) {
return;
}

The same logic is used in the product categories dropdown walker. The fix allows the walker to work as expected when the hide_empty flag is not included in $args, whilst honouring the flag if set in a filter.

Hope this helps some one.

**Comment by claudiosmweb** [comment]
Will works fine in 2.3.

![screenshot from 2015-01-02 11 07 14](https://cloud.githubusercontent.com/assets/1264099/5596202/8d5d3e3a-926f-11e4-8d62-c1419c398234.png)
