### ISSUE TITLE
Product tabs - CSS broken

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#6996]
![screenshot from 2014-12-22 12 52 50](https://cloud.githubusercontent.com/assets/1264099/5526341/7f1e9cf4-89d9-11e4-9a2a-a651a40778fa.png)

**Comment by jameskoster** [comment]
I'm unable to replicate either of those issues, I'm on osx though. 

The css looks fine... Inspect the arrow in the payment form, you should see that the border top/right/left are set as transparent: http://cl.ly/image/3Z1o3f2F1j27

**Comment by claudiosmweb** [comment]
Sorry xD
I need update the WooCommerce Colors.

**Comment by jameskoster** [comment]
it's cool
