### ISSUE TITLE
Plot completed orders on graph of Reports for different times of the day

### ISSUE THREAD

**Issue by joelchen** [woothemes/woocommerce#7003]
Hi WooCommerce Team,

Would like to be able to see the completed orders plotted on the graph of Reports for different times of the day. Thank you.

**Comment by mikejolley** [comment]
Our reports cover a minimum of a day - no current plans for hour by hour reports. Sounds like it could be an extension? Maybe log on http://ideas.woothemes.com/ if you feel it could be useful, with more info.
