### ISSUE TITLE
Might be formatting bug in $product->get_variation_attributes();

### ISSUE THREAD

**Issue by phppoet** [woothemes/woocommerce#7004]
Hi there ,

In case of global greek attributes (http://i.imgur.com/Ca5qiq0.png) . Somehow

$product->get_variation_attributes();  is returning

Array ( [pa_τεχνοδερμα] => Array ( [0] => black [1] => brown [2] => white ) [pa_γωνια] => Array ( [0] => %ce%b1%cf%81%ce%b9%cf%83%cf%84%ce%b5%cf%81%ce%ae [3] => %ce%b4%ce%b5%ce%be%ce%b9%ce%ac ) ) 

Shouldn't it return 

Array ( [pa_τεχνοδερμα] => Array ( [0] => black [1] => brown [2] => white ) [pa_γωνια] => Array ( [0] => Αριστερή [3] => Δεξιά ) ) 

also 

$terms = get_terms( 'pa_τεχνοδερμα', array('menu_order' => 'ASC') );

returning unformated array. Not sure is it a bug or it should work this way . 

thanks @mikejolley, @claudiosmweb, @barrykooij

**Comment by mikejolley** [comment]
get_variation_attributes will return them in this way because they are sanitized. If you display them, run the values through rawurldecode first like we do in core.
