### ISSUE TITLE
Order creation with supplied created_at/updated_at/completed_at fields via REST API

### ISSUE THREAD

**Issue by joelchen** [woothemes/woocommerce#7005]
Hi WooCommerce Team,

Would like to be able to create orders with supplied time fields via REST API, so as to enable offline order creation, updating of orders on WooCommerce when network is available, and plotting of graph in Reports discretely as mentioned in https://github.com/woothemes/woocommerce/issues/7003. Thank you.

**Comment by mikejolley** [comment]
I've added this request to the RoadMap here: https://trello.com/c/mG2MwL4C/51-rest-api-setting-of-date-fields-when-creating-orders-created-at-updated-at-completed-at

Thanks for the feedback.

**Comment by amjad** [comment]
@mikejolley Is there any way to find out which version of WooCommerce made this fix if it was done. I see the created_at date is read-only for the API.
