### ISSUE TITLE
Monaco is part of the European Union for VAT purposes

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#7013]
Monaco is not fully part of the EU; however, for purposes of EU VAT, Monaco (ISO code, MC) is part of the EU (as can be verified from many sources with a quick Google).

WC_Countries::get_european_union_countries() does *not* return 'MC' as part of its results. This is technically correct; however, this method is called by by WC_Countries::tax_or_vat(), WC_Countries::ex_tax_or_vat() and WC_Countries::inc_tax_or_vat(), with no correction made for MC. Thus, those three methods return wrong results for MC.

**Comment by mikejolley** [comment]
I've updated EU VAT and my APIs for this. Will update core.
