### ISSUE TITLE
Save and Close Backbone Modal events on Enter/Escape keypress

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#7016]
Backbone Modal used on WooCommerce should have the events to save and close modal-dialog on Enter/Escape Keypress. I am not quiet familiar with Backbone so have shared this snippet how this can be done :)

```JS
// Save and Close Backbone Modal events on Enter/Escape keypress.
$( document ).bind( 'keydown.WCBackboneModal', function( e ) {
	// Ensure event is not null
	e = e || window.event;

	// Save Event
	if ( e.which === 13 && ! ( e.target.tagName && e.target.tagName.toLowerCase() === 'textarea' ) ) {
		setTimeout( function() {
			obj.executeCallback(); // Callback to save
		}, 100 );

		e.stopImmediatePropagation();
	}

	// Close Event
	if ( e.which === 27 ) {
		setTimeout( function() {
			obj.close(); // Callback to close
		}, 100 );

		e.stopImmediatePropagation();
	}
});
```
Note: Callback used should be define. This is only the sample how I have used in my certain project !

**Comment by shivapoudel** [comment]
Can't wait for this awesome keydown event xD

One more thing you can do with this backbone modal is attach a close icon at the top-right of the header with `#btn-cancel` event (ofcourse ESC Keypress should work for it). It will be just clean and tidy ;)

**Comment by shivapoudel** [comment]
I think if we click on the backdrop it should get disappear too.

**Comment by claudiosmweb** [comment]
Done.

**Comment by shivapoudel** [comment]
o/

**Comment by shivapoudel** [comment]
#7034 since you were missing some changes for add-tax backbone modal ;)

**Comment by shivapoudel** [comment]
#7035 Let's bail the modal animation. Look pretty awesome what's about you @claudiosmweb  ?

**Comment by claudiosmweb** [comment]
No, thanks.
