### ISSUE TITLE
Attribute term page and out of stock product variations

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#7026]
When you view the page for a particular attribute term, it shows all the products that have variations with that term, even those products where that specific variation is out of stock.

If the product inventory setting is such that out of stock products are hidden from the catalog (http://cld.wthms.co/19qP1), would it not make sense to carry that setting to the attributes so that if a blue t-shirt variation is out of stock, the t-shirt product is hidden from the "blue" attribute page?

**Comment by claudiosmweb** [comment]
"wontfix" for now https://github.com/woothemes/woocommerce/issues/5840#issuecomment-50601474

**Comment by stimart** [comment]
Here my solution: http://www.stimart.net/web/woocommerce-hide-out-of-stock-items-that-appears-using-layered-nav-filter-widget-solution-3/
Hope it helps! :-)
