### ISSUE TITLE
Custom post type and shared taxonomy

### ISSUE THREAD

**Issue by sebastienpenet** [woothemes/woocommerce#7027]
Hello

I have a custom taxonomy which is shared between woocommerce and my custom post type. When I try to access my taxonomy it gets handled by woocommerce. So I forced it to use my own post type with a pre_get_posts hook where I properly set the query var. It works but the query gets modified and some catalog visibility check is added, so I must remove it manually with some filter.

Not sure if it's my fault or if I'm wrong, but I wouldn't expect that. (I must precise that I hook before product_query to change the post type, of course).

Thanks

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:
 
* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
