### ISSUE TITLE
Error message in account par

### ISSUE THREAD

**Issue by zobboy** [woothemes/woocommerce#7032]
Hello,

WooCommerce version: 2.2.10
WP version: 4.1

Error message are not displayed when user (on .../my-account/):
- doesn't enter email or/and password but press "LOGIN" button
- doesn't enter the correct password and press "LOGIN" button
We can see the red background, but no message.

For "registration" part, all error messages are displayed, but for "login" part, no error messages.
Tested on 2 different WP + Woocommerce, with 2 different themes.

Before, we had error messages like:
- Error: Username is required.
- Error: Password is required.
- ERROR: Incorrect username or password.

Thank you in advance.

**Comment by splashingpixels** [comment]
I believe this is a theme issue.  I cannot replicate it on my end with 2012 theme.  Please confirm.

**Comment by zobboy** [comment]
The theme is working on an other WooCommerce version...
Both themes will be concerned, why not.

I will test a second time on a virgin installation.

**Comment by splashingpixels** [comment]
Closing for now as I believe this is a theme issue.

**Comment by zobboy** [comment]
Really sorry.

I found the origin of the problem.... plugin iThemes Security.
I don't know yet, but something deactivate these kind of messages.

And all my sites have this plugin, that's why I've the problem on all of them.
