### ISSUE TITLE
WooCommerce isn't adding VAT as configured to

### ISSUE THREAD

**Issue by lmartins** [woothemes/woocommerce#7036]
Hi,

In the shops I manage it's quite common to have the prices inserted without VAT, but shown on the front end with VAT included. For that purpose, I've setup WooCommerce as follows.

Tax Options:
![screen shot 2015-01-02 at 15 43 33](https://cloud.githubusercontent.com/assets/151981/5597198/296473d6-9296-11e4-861d-d6c4e025b495.png)

Tax Rate Configuration:
![screen shot 2015-01-02 at 15 44 05](https://cloud.githubusercontent.com/assets/151981/5597201/38524e04-9296-11e4-8fe9-690e516b75db.png)

Product Configuration:
![screen shot 2015-01-02 at 15 44 56](https://cloud.githubusercontent.com/assets/151981/5597212/587ee246-9296-11e4-8000-18e4fdad3184.png)

And this is what is shown on the front-end:
![screen shot 2015-01-02 at 15 45 21](https://cloud.githubusercontent.com/assets/151981/5597219/6a7282b4-9296-11e4-9d9a-6e670597813c.png)
![screen shot 2015-01-02 at 15 45 54](https://cloud.githubusercontent.com/assets/151981/5597222/77cc300e-9296-11e4-8c22-dfa051e2f442.png)

I've looked everywhere and I can't find a reason for this. Disabled cache, everything and it still outputs the prices without adding VAT to them.

Any idea of what might be happening?

**Comment by mikejolley** [comment]
Customer's default address is 'no address'.

**Comment by lmartins** [comment]
Hi Mike, 

Thank you so much for the fast reply.
Got it, changing the default address to "shop address" does the trick.

Thanks again.
