### ISSUE TITLE
Order can't be created, when no "generic" sales tax is available for country without specific sales tax

### ISSUE THREAD

**Issue by scrobbleme** [woothemes/woocommerce#7040]
After updating to the latest version of WooCommerce customers from countries without sales tax weren't able to order and just got a generic error message like "Error: Unable to create order. Please try again." (#6952)

The problem was, that we didn't configured a "generic" sales tax with 0% for *, after doing this it worked, but it also worked before upgrading WooCommerce from 2.0.x.

At least there should be a better error message given. 

Also see this "workflow": https://www.dropbox.com/s/7ugiyp5h5n4g5i6/problem_woocommerce_table_rate_shipping.png?dl=0

**Comment by mikejolley** [comment]
This shouldn't happen because the array of combined taxes should be empty. I'm unable to reproduce the error itself when I configure no taxes for a country.

**Comment by mikejolley** [comment]
Did spot a related issue with the 'zero-rated' tax though. Committing a fix.
