### ISSUE TITLE
Last Item in stock of a product makes removal difficult on iPhone screens.

### ISSUE THREAD

**Issue by questulent** [woothemes/woocommerce#7041]
When the last item in stock of a product is added to the cart ("manage inventory" checked), the cart does not display the usual plus and minus buttons around the number "1" (see last item on attached image).

The only way in this case to remove the item from the cart us by using "the little red x" - however, some themes (including Woothemes Hustle) need to remove this red x on iPhone screens to fit the cart on the screen, leaving customers no way to remove such a product from their cart once added.

Is there a way woocommerce could hide only the plus sign and not the minus sign in this case?

![img_0379](https://cloud.githubusercontent.com/assets/2563553/5602961/d5120b58-9377-11e4-8628-514986f0850a.PNG)

**Comment by jameskoster** [comment]
Should just remain as an input.

**Comment by Kenshino** [comment]
IMO It should be an input, however, the + sign should be removed, leaving only the - sign to act as a product removal

**Comment by jameskoster** [comment]
@Kenshino the +/- buttons are gone in 2.3.

**Comment by Kenshino** [comment]
Ah sorry, forgot it got moved into plugin.

Input is great :).... then I assume putting a 0 in makes it remove itself?

**Comment by jameskoster** [comment]
Yep, changing the 1 to a 0 and updating the cart will remove it.
