### ISSUE TITLE
Shipping address not displayed in confirm-order and confirmation email

### ISSUE THREAD

**Issue by zobboy** [woothemes/woocommerce#7044]
I see that this issue was present in 2.2.1 and was solved in 2.2.3... but still present in my version... and I have exactly the same problem.

Maybe because I updated directly from old version (2.1), before 2.2.1, it was not corrected?

To be sure that it's a Woocommerce issue, I've disabled all plugins, put default theme, and deleted all caches, etc... no result.

I hope you will find the solution, because today, only billing address is displayed.

WP 4.1
WooCommerce 2.2.10

Thank you.
Regards,
Arnaud

**Comment by mikejolley** [comment]
This is the code we use:

`
<?php if ( ! wc_ship_to_billing_address_only() && $order->needs_shipping_address() && ( $shipping = $order->get_formatted_shipping_address() ) ) : ?>
`

1. wc_ship_to_billing_address_only = the setting that prevents shipping addresses
2. $order->needs_shipping_address()  = whether or not the order actually needs to be shipped https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L2416 If its local pickup, it won't be shippable.
3. $shipping = $order->get_formatted_shipping_address() - if the address is set

So it should only display when needed. I have no issues with 2.3 master around this - just tested to confirm.

**Comment by mikejolley** [comment]
Also tested 2.2 http://glui.me/?i=b7swuw0mpxw5x3q/2015-01-05_at_16.06_2x.png/
