### ISSUE TITLE
(Page #'s and Page Arrow) at bottom of Product page Does Nothing!

### ISSUE THREAD

**Issue by nolanconcepts** [woothemes/woocommerce#7045]
I have Ruled out Themes, Plugins, Tried different Browsers. 
The Problem is my sites main shop page has categories to shop from.
under the Gold category i have the most products. (14 products at the moment)
it shows 12 out of 14 and at the bottom of the page has page | 1 | 2 | --> |
However when i click on page 2 or the arrow the address bar link changes but nothing else does. The original 12 are still displayed and the remaining 2 products never show up.
My site is here: http://darth.net84.net/wordpress/?post_type=product

**Comment by splashingpixels** [comment]
Fixed in 2.3.0 release coming soon.
