### ISSUE TITLE
pagination don't work

### ISSUE THREAD

**Issue by stefanopeli** [woothemes/woocommerce#7046]
if i search products and try to go to 2nd page the link shows #038; in place of &
http://stefanop-001-site3.smarterasp.net/?post_type=product

can't face off this problem

**Comment by mikejolley** [comment]
Please search first https://github.com/woothemes/woocommerce/issues/7011 Fixed in the next release.

**Comment by stefanopeli** [comment]
Thank you so much!

 

Da: Mike Jolley [mailto:notifications@github.com] 
Inviato: lunedì 5 gennaio 2015 15.49
A: woothemes/woocommerce
Cc: stefanopeli
Oggetto: Re: [woocommerce] pagination don't work (#7046)

 

Please search first #7011 <https://github.com/woothemes/woocommerce/issues/7011>  Fixed in the next release.

—
Reply to this email directly or view it on GitHub <https://github.com/woothemes/woocommerce/issues/7046#issuecomment-68717033> .  <https://github.com/notifications/beacon/AJ66nRzwav_0GHKBv0peIP5aIdT390cAks5nepvlgaJpZM4DOZUD.gif> 



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
http://www.avast.com
