### ISSUE TITLE
Hide local pickup shipping option when "Ship to a different address" is checked

### ISSUE THREAD

**Issue by capecodder90** [woothemes/woocommerce#7047]
I have a client who has been having problems with people trying to cheat them out of their shipping charge. Customers have been checking off the "Ship to different address" checkbox and filling in a shipping address, then selecting the FREE local pickup option from the drop-down. Obviously, if someone enters a shipping address, the FREE local pickup option should not be an option.

Is that something that could be fixed?
![screen-shot-2015-01-05-at-10 48 13-am](https://cloud.githubusercontent.com/assets/8960625/5615391/d7155174-94c8-11e4-99bf-b0bc397cca85.jpg)

**Comment by mikejolley** [comment]
There are already settings for this - http://glui.me/?i=epi6oum1o3ymlv3/2015-01-05_at_15.55_2x_(1).png/ These settings are based on the package destination, in your case shipping address.

**Comment by capecodder90** [comment]
I don't understand how that solves it. If I enter the store's zip code, anyone living within that zip code will still be able to select the local pickup option even if they want the package shipped. It only solves the problem if my client never has a customer who lives in the same zip code who wants their package shipped...

**Comment by mikejolley** [comment]
Local pickup checks against the package address - this is billing primarily, or shipping if set. If you enter a different shipping address, thats what this method will check against.

Are you saying you have users inputting a shipping address local to your store?

**Comment by capecodder90** [comment]
I'm not following.

What should be happening, is that when someone enters a shipping address in the "Ship to a different address?" section, the local pickup shipping option shouldn't be disabled.

So that you can visually see what is happening:
The store's zip code is 02660. 
I have chosen a ship-to address that is across the street from the store; also a 02660 zip code. As you can see below, the checkout page is allowing the customer to choose the free local pickup (a.k.a. in-store pickup) option, AND enter a shipping address.
![screen shot 2015-01-05 at 11 43 00 am](https://cloud.githubusercontent.com/assets/8960625/5616239/851c5248-94d0-11e4-9d48-761104121b66.png)

In other words, customers who want their package shipped to a 02660 address will be able to choose the free local pickup option and circumvent the normal shipping charge of $10.

There should be an option to hide the "Ship to a different address?" section when the customer has chosen the Local Pickup option, so that they cannot enter a shipping address. Customers should either be able to enter the shipping address and get charged the $10 shipping charge, or choose local pickup and not be able to enter a shipping address.

This is how I have the Local Pickup settings:
![screen shot 2015-01-05 at 11 43 45 am](https://cloud.githubusercontent.com/assets/8960625/5616342/aafac5a2-94d1-11e4-917a-dc2c249035d7.png)

**Comment by mikejolley** [comment]
Shipping is chosen after address input, so disabling that based on the method isn't really feasible.

I don't understand how this is a major issue for you anyway - if they choose in store pickup, surely its down to the customer to get their item?

**Comment by capecodder90** [comment]
That's what I tried to tell my client, but her boss doesn't see it that way. Thank you for the assistance and patience. I will have to see what I can do.
