### ISSUE TITLE
Drop down menu not working

### ISSUE THREAD

**Issue by JohnFerrari** [woothemes/woocommerce#7048]
I am having trouble with drop down menus with WooCommerce. Instead of acting normally, they seem to be listing all available options below a text box. This is the same on my website, as well as on WooCommerce settings using WordPress. Is there a way to fix this as it makes the check out process a lot more complicated.
![image](https://cloud.githubusercontent.com/assets/10405528/5617246/836b669e-9504-11e4-80b7-b2a343ffdfb1.png)

**Comment by claudiosmweb** [comment]
That's some javascript error caused by another plugin.
Try disabling some plugins until you find the culprit.
