### ISSUE TITLE
Product-tag permalink is getting picked for translation and results in 404

### ISSUE THREAD

**Issue by lmartins** [woothemes/woocommerce#7049]
One of our clients has a site configured to use pt_PT lang and he assigns tags to his products.
The permalink that is being generated to access a tag archive is being translated and as a results it returns 404.

You can see an example here:
http://bazarvirtual.webipack.com/shop/fato-carnaval-adulto-capuchinho/

Any ideia on how to resolve this?

**Comment by mikejolley** [comment]
Settings > Permalinks and save.

**Comment by lmartins** [comment]
Just by saving didn't solved it. I had to manually assign a string to the tags part of the permalink.

Thank you for tip. Btw, this happens every time the site language is changed?

**Comment by mikejolley** [comment]
Yes - if the language file changes the slug/permalink.
