### ISSUE TITLE
wc_add_notice breaks -  Call to a member function get() on a non-object

### ISSUE THREAD

**Issue by mikemcguire** [woothemes/woocommerce#7050]
I have a clean install of wordpress (4.1) and woocommerce (2.2.10) on twentyfourteen. 
I'm putting the function in functions.php on the first line, seen as "wc_add_notice('fart', 'error');"
I get an error that breaks both the front-end and admin

Fatal error: Call to a member function get() on a non-object in /sandbox2/wp-content/plugins/woocommerce/includes/wc-notice-functions.php on line 67

I originally ran into this error working on a site with a custom theme using woocommerce 2.1.7 and decided to set-up a sandbox to see what was wrong.  Needless to say, same error. 

The issue comes from this line 
$notices = WC()->session->get( 'wc_notices', array() );

**Comment by splashingpixels** [comment]
Call that function within the "init" action hook.
