### ISSUE TITLE
Reports module is not showing accurate sales data

### ISSUE THREAD

**Issue by gregelizondo** [woothemes/woocommerce#7052]
I'm experiencing a strange issue with the WooCommerce Reports feature.

My store has done a decent amount of orders for the month of December, 2014 (100+). However, when I go to the report tab and bring up data from "Last Month," only 1 order is shown (screenshot). This also happens if I manually set the date range from 12/1/2014-12/31/2014.

It may be important to note that all of these orders were previously trashed after being marked "Completed." They were then restored prior to running the report.

![screen shot 2015-01-06 at 10 29 18 am](https://cloud.githubusercontent.com/assets/534738/5630791/f0f2d6ea-958e-11e4-9781-27bf899b61ae.png)

**Comment by mikejolley** [comment]
To test this I trashed all my orders then restored them - reports worked but I needed to clear transients. I'll make the transients clear automatically.
