### ISSUE TITLE
Woocommerce Problem

### ISSUE THREAD

**Issue by realestateofficial** [woothemes/woocommerce#7053]
Any ideas why the purchased items # not showing in Woocommers order area? Also the products are missing as well. I installed a fresh and a new WordPress platform and imported orders from an old website. Any help how to fix this would be greatly appreciated. #woocommerce 
![12](https://cloud.githubusercontent.com/assets/5168046/5631706/a59899ac-9596-11e4-8b04-ec282a8c493c.png)
![14](https://cloud.githubusercontent.com/assets/5168046/5631707/a59b2302-9596-11e4-95a5-08003e7feb83.png)

#woocommerce info:

WC Version: 	2.2.10
WC Database Version: 	2.2.10
WP Version: 	4.1
WP Multisite Enabled: 	No
Web Server Info: 	Apache
PHP Version: 	5.4.19
MySQL Version: 	5.5.37

**Comment by claudiosmweb** [comment]
It looks like you do not care the data correctly.
This is not a WooCommerce core issue and so I'm closing.
