### ISSUE TITLE
Plugins hiding products menu option

### ISSUE THREAD

**Issue by gareth-gillman** [woothemes/woocommerce#7057]
I have noticed on WP 4.1 that a lot of plugins when activated make the products menu of Woo disappear. Not a major thing for me but can make my clients go a bit mad.

The most popular is TablePress,lots of other small ones (some from Codecanyon)

Is there something we can use to fix this so when the client uploads plugins it won't affect the menu?

**Comment by bryceadams** [comment]
Hey! Which version of WC? And which other plugins?

Just tried WC 2.2.10 and latest TablePress without any issues:

![see screen shot](http://cld.wthms.co/19qto+)

**Comment by mikejolley** [comment]
When you add a menu item, you need to define a priority which defines where it gets places. To avoid conflicts, we used a decimal (55.5) which is our position.

No doubt an author on CC 'borrowed' this and thus now conflict. They would need to change their 55.5 to something else - we cannot work around this.
