### ISSUE TITLE
Don't Set Expiry Date for Download Permissions When Using WooCommerce Subscriptions & WooCommerce Subscription Downloads

### ISSUE THREAD

**Issue by 30suns** [woothemes/woocommerce#7058]
In a scenario where a simple virtual product's download has a expiry date set, but that same download is made available to a subscription via the premium WooCommerce Subscription Downloads plugin, the expiry date is set when a customer signs up, so even if their subscription is active, the link expires. I wasn't able to find a clean way to fix this without hard coding a check for `WC_Subscriptions_Order::order_contains_subscription( $data['order_id'] )`. We may need new hooks within the core `includes/wc-order-functions.php` to facilitate overriding the expiry date before `$data['access_expires']` is set to `$expires`.

**Comment by mikejolley** [comment]
Could you report this on support.woothemes.com so the dev of WooCommerce Subscription Downloads can look into this/into a core filter? That would be best since this isn't specifically a core issue. If a filter is needed to support it, happy to oblige.

Thanks!

**Comment by russoanthony** [comment]
I seem to be having this issue as well.  Has this not been fixed?

**Comment by vimarshacooray** [comment]
seems not.
