### ISSUE TITLE
woocommerce_before_checkout_billing_form hook location

### ISSUE THREAD

**Issue by kieranbarnes** [woothemes/woocommerce#7059]
The `woocommerce_before_checkout_billing_form` seems like the only location we can hook into on the checkout page before the all checkout fields. A logical location to add messages or other important fields, however the hook is called **after** the `<h3>Billing Details</h3>` code here https://github.com/woothemes/woocommerce/blob/master/templates/checkout/form-billing.php#L27

It is much more logical to call that hook **before** the header tags otherwise anything we hook in will always be within "Billing Details", not where the hook suggests which is before billing details.

**Comment by bryceadams** [comment]
It's the same for `woocommerce_before_checkout_shipping_form` - not sure if we could move the filter as a lot of people using it will expect it to hook into after the title but you do have a point about being able to hook into before the title.

@mikejolley @claudiosmweb @barrykooij Maybe a new filter before? Feels like overkill but still.

**Comment by claudiosmweb** [comment]
The best would create new filters. For not to change what everyone has made.

**Comment by mikejolley** [comment]
There are other actions.

woocommerce_checkout_billing with a lower priority will be before billing  but inside the col-1.

woocommerce_checkout_before_customer_details is before the columns,

Take your pick.
