### ISSUE TITLE
activating woocommerce "kills" changing wordpress general settings language translation and  woocommerce pages are not translated any more

### ISSUE THREAD

**Issue by francegourmande** [woothemes/woocommerce#7060]
Hi,
After last update of the plugin, I noticed that activating it "kills" the option of setting wordpress language to a different from the default english language and the translation of woocommerce pages like cart or check out. 
when woocommerce plugin is deactivated everything runs smoothly and once it gets activated it is no longer posible to get the dashboard translated into russian
please, see the status report and print screens
hope you can help me

thanks,
Arina

P.S. In addition to the above, I don't have the "force translation" option in the tools of woocommerce settings
![screen shot 2015-01-07 at 23 24 00](https://cloud.githubusercontent.com/assets/10441569/5654542/7cc2fce6-96c4-11e4-93e2-bd42a9691bb9.png)
![screen shot 2015-01-07 at 23 24 50](https://cloud.githubusercontent.com/assets/10441569/5654543/7cc63230-96c4-11e4-8d90-81941a78a790.png)
![screen shot 2015-01-07 at 23 25 15](https://cloud.githubusercontent.com/assets/10441569/5654544/7cc9b810-96c4-11e4-96b6-b58dc0f19369.png)

### Environment ###

Home URL:                http://francegourmande.eu
Site URL:                http://francegourmande.eu
WC Version:              2.2.10
WC Database Version:     2.2.10
WP Version:              4.1
WP Multisite Enabled:    No
Web Server Info:         Apache mod_fcgid/2.3.10-dev
PHP Version:             5.4.35
MySQL Version:           5.5.36
WP Active Plugins:       20
WP Memory Limit:         40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode:           No
WP Language:             en_US
WP Max Upload Size:      32 MB
PHP Post Max Size:       48 MB
PHP Time Limit:          0
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
WC Logging:              Log directory (/home/arkhangelskayaa/public_html/wc-logs/) is writable.
Default Timezone:        Default timezone is UTC
fsockopen/cURL:          Your server has fsockopen and cURL enabled.
SOAP Client:             Your server has the SOAP Client class enabled.
WP Remote Post:          wp_remote_post() was successful - PayPal IPN is working.

### Locale ###

decimal_point:           .
thousands_sep:           N/A
mon_decimal_point:       N/A
mon_thousands_sep:       N/A

### Plugins ###

Installed Plugins:       BackUpWordPress by Human Made Limited version 3.0.4
                         Contact Form 7 by Takayuki Miyoshi version 4.0.3
                         Envato WordPress Toolkit by Envato version 1.7.1
                         Google Analytics Dashboard for WP by Alin Marcu version 4.3.11
                         WPBakery Visual Composer by Michael M - WPBakery.com version 4.3.4
                         Leverage Browser Caching Ninja by CustomWPNinjas version 2.1
                         Limit Attempts by BestWebSoft version 1.0.6
                         mqTranslate by xhaleera version 2.9.1.2
                         PayPal for WooCommerce by Angell EYE version 1.1.5.3
                         Post Types Order by Nsp Code version 1.7.4
                         Really Simple CAPTCHA by Takayuki Miyoshi version 1.8.0.1
                         Revolution Slider by ThemePunch version 4.6.0
                         Sticky Header by ThematoSoup version 1.2
                         W3 Total Cache by Frederick Townes version 0.9.4.1
                         WooCommerce-qTML by SomewhereWarm version 2.0.12
                         Woocommerce Weight & Country Based Shipping by Jeriff Cheng version 1.1
                         WooCommerce by WooThemes version 2.2.10
                         WP-Optimize by Ruhani Rabin version 1.8.9.7
                         WP Retina 2x by Jordy Meow version 2.4.0
                         WP Smush.it by WPMU DEV version 1.6.5.4

### Settings ###

Force SSL:               No

### WC Pages ###

Shop Base:               #2183 - /shop/
Cart:                    #10 - /the-cart/
Checkout:                #11 - /checkout/
My Account:              #12 - /my-account/

### WC Taxonomies ###

Product Types:           external (external)
                         grouped (grouped)
                         simple (simple)
                         variable (variable)

### Theme ###

Theme Name:              The Retailer
Theme Version:           2.1.2
Theme Author URL:        http://www.getbowtied.com/
Is Child Theme:          No
WooCommerce Support:     Yes

### Templates ###

Template Overrides (WooCommerce):theretailer/theretailer/woocommerce/archive-product.php
                         theretailer/theretailer/woocommerce/cart/cart-empty.php
                         theretailer/theretailer/woocommerce/cart/cart-shipping.php
                         theretailer/theretailer/woocommerce/cart/cart-totals.php
                         theretailer/theretailer/woocommerce/cart/cart.php
                         theretailer/theretailer/woocommerce/cart/cross-sells.php
                         theretailer/theretailer/woocommerce/cart/mini-cart.php
                         theretailer/theretailer/woocommerce/content-product.php
                         theretailer/theretailer/woocommerce/content-product_cat.php
                         theretailer/theretailer/woocommerce/content-single-product.php
                         theretailer/theretailer/woocommerce/global/quantity-input.php
                         theretailer/theretailer/woocommerce/loop/orderby.php
                         theretailer/theretailer/woocommerce/loop/price.php
                         theretailer/theretailer/woocommerce/loop/result-count.php
                         theretailer/theretailer/woocommerce/myaccount/form-login.php version 2.1.0 is out of date. The core version is 2.2.6
                         theretailer/theretailer/woocommerce/order/form-tracking.php
                         theretailer/theretailer/woocommerce/order/order-details.php
                         theretailer/theretailer/woocommerce/single-product/add-to-cart/external.php
                         theretailer/theretailer/woocommerce/single-product/add-to-cart/simple.php
                         theretailer/theretailer/woocommerce/single-product/add-to-cart/variable.php
                         theretailer/theretailer/woocommerce/single-product/meta.php
                         theretailer/theretailer/woocommerce/single-product/price.php
                         theretailer/theretailer/woocommerce/single-product/product-image.php
                         theretailer/theretailer/woocommerce/single-product/product-thumbnails.php
                         theretailer/theretailer/woocommerce/single-product/related.php
                         theretailer/theretailer/woocommerce/single-product/review.php
                         theretailer/theretailer/woocommerce/single-product/short-description.php
                         theretailer/theretailer/woocommerce/single-product/tabs/additional-information.php
                         theretailer/theretailer/woocommerce/single-product/tabs/description.php
                         theretailer/theretailer/woocommerce/single-product/tabs/tabs.php
                         theretailer/theretailer/woocommerce/single-product/title.php
                         theretailer/theretailer/woocommerce/single-product/up-sells.php
                         theretailer/theretailer/woocommerce/single-product-reviews.php
                         theretailer/theretailer/woocommerce/single-product.php

**Comment by mikejolley** [comment]
The force button only appears when WordPress is not in en_US.

WooCommerce doesn't affect the language option, see my site: https://dl.dropboxusercontent.com/s/g1bw2mvqde4jizz/2015-01-08%20at%2014.04%202x.png?dl=0

The language setting in WordPress only appears if a language pack/file is available.

Download and install your language file for WordPress manually to see if that option can re-enable. And if you're certain its a plugin, try disabling plugins that rely on WC, such as the qTML plugin which will affect localisation.

Closing as this isn't a core issue.

**Comment by francegourmande** [comment]
thank you Mike

Deliciously yours,
France Gourmande
Email: france_gourmande@hotmail.com
Website: http://francegourmande.eu
Instagram:http://instagram.com/france_gourmande
