### ISSUE TITLE
"Featured Image" meta box for page is changed to "Product Image"

### ISSUE THREAD

**Issue by rilwis** [woothemes/woocommerce#7063]
Hi,

When I install WordPress in another **English** language, specifically **English - Australia**, and add a new **Page**, I see the text in **Featured Image** meta box is changed to **Product Image**:

![bug](http://i.imgur.com/uGEQYov.png)

Here is the settings:

![bug](http://i.imgur.com/isRJSuf.png)

I checked the code of WooCommerce, and found the function that changes text is located in `includes/admin/class-wc-admin-post-types.php`. There's no check for current post type. I think adding the check will fix the problem.

Thanks for the great plugin.

**Comment by SiR-DanieL** [comment]
Refer to https://github.com/woothemes/woocommerce/issues/6966
