### ISSUE TITLE
woocommerce plugin page shortcode is not working

### ISSUE THREAD

**Issue by smpdesignmedia** [woothemes/woocommerce#7064]
- any of the pages shortcode is not working after upgrading woocommerce to latest version

**Comment by mikejolley** [comment]
What shortcode are you using?

Is WooCommerce still active?

**Comment by smpdesignmedia** [comment]
I've loaded default woocommerce pages, I've Used twentyfifteen wordpress theme & added theme woocommerce theme support.

My cart page, checkout page is not working, shop page is working, i've added one product to cart, "cart page & checkout page"  shortcode is there

**Comment by smpdesignmedia** [comment]
I've loaded default woocommerce pages, I've Used twentyfifteen wordpress theme & added theme woocommerce theme support.

My cart page, checkout page is not working, shop page is working, i've added one product to cart, "cart page & checkout page"  shortcode is there

**Comment by smpdesignmedia** [comment]
I've loaded default woocommerce pages, I've Used twentyfifteen wordpress theme & added theme woocommerce theme support.

My cart page, checkout page is not working, shop page is working, i've added one product to cart, "cart page & checkout page"  shortcode is there
