### ISSUE TITLE
Downloadable products folder under nginx

### ISSUE THREAD

**Issue by chvillanuevap** [woothemes/woocommerce#7066]
Hi,

I own an ecommerce shop that sells a lot of digital products. Recently, a customer informed me that a Google search provided a direct link to each individual digital file that I am selling.

The issue was that the woocommerce_uploads folder has a .htaccess file, but my server uses nginx. Basically, the products were available to anyone who could come up with the right keywords on Google search. While getting the correct combination of keywords in the search is tricky, the issue is still concerning.

I already contacted my hosting company and they added the rewrite rules on the nginx configuration file.

Now, I'm trying to think of what approaches should be taken so this issue does not happen again in the future, for me or anyone else. Nginx is used by a lot of major hosting companies, such as WPEngine, Web Synthesis, etc., so they might be a lot of people with this issue that are not even aware of it. The first thing I am trying to figure out is whose responsibility it is to prevent this problem.

- Should the responsibility lie on the webmaster? If so, maybe a blog post on the WooThemes page might be useful to inform people.
- If you consider this was an error on behalf on my hosting company because they should have scanned my folders and detect .htaccess files, then I will submit a ticket with them and request this as a feature to their engineers.
- If the issue is with WooCommerce core, what approaches should be taken? Should I have been aware of some plugin that handles this kind of situation?

Thanks for any feedback,

Hernan

**Comment by mikejolley** [comment]
Hi Hernan

I'll ping the docs team to cover this, but its odd they were indexed.

I don't think we can solve this on Nginx directly as there is no htaccess equivalent so it's mainly down to the webmaster. However, core does add an index.html file to prevent directory listing at least. Were you missing this file?

**Comment by chvillanuevap** [comment]
Did you mean it's odd it was indexed, or odd it was not indexed?

A Google search did not return any results regarding my problem. However, this could be due to bad SEO or me using the wrong terms/keywords.

There is an index.html file which prevents directory listing. However, that does not prevent Google from indexing the files inside the directories. I did check my sitemap and as I far as I could tell, the files are not listed there, but Google must have indexed them anyway.

I feel this is an important issue. What is the point of selling digital products if anyone with the right keyword combination can find them for free? Like I said in my initial comment, a lot of people use managed WordPress hosting services, and a lot of those use nginx. There could be tons of people out there with this issue and they would have no idea. I personally did not know until a reader from Malaysia emailed me with a heads-up including the links to the digital files. At that time, I found out that another website was linking directly to my digital product files touting them as a ¨free resource¨, which of course I found very disconcerting.

The best solution is to contact your hosting provider and ask them to configure the rewrite rules, but of course, you need to be aware of the issue first. The documentation should definitely help on this. Is there a way WooCommerce could detect that the server runs under nginx and display a notification to the user? Another approach is to manually remove the URLs from the search engines indices, but this is not scalable.

**Comment by mikejolley** [comment]
@chvillanuevap odd that it indexed. Google can only index files it can find, so either you've got them linked somewhere (sitemap for example, or direct links in your content) or it can find the directory listing (should be prevented by index file). I don't think google can guess directory structures on it's own..

**Comment by chvillanuevap** [comment]
I do agree it's odd that Google indexed the digital products even thought the directory did not provide listing. Perhaps either my hosting provider or me listed the link at some point in time and Google indexed it. Also, I did check my sitemap prior to submitting this ticket, and did not see the digital products listed there. However, I could have made a mistake and skipped the listing. I use Yoast SEO by the way.

Like I mentioned before, my issue was resolved before I even posted this ticket. My main goal was to inform you that there might be some finicky stuff going on when the user uses WooCommerce on nginx. I wanted to inform other users so they can make sure their products are indeed private.

**Comment by mikejolley** [comment]
That would be my assumption- linked from somewhere directly. WC has options to 'force' download which should in effect hide the links too, preventing other people from posting direct links. Let us know if you find any more clues.

**Comment by jacksonwp** [comment]
FWIF - I just had this issue with a client site on WPEngine as well. The link got exposed because the site was producing 'Attachment Pages' and Yoast SEO was putting media in the sitemap. The htaccess file in the 'woocommerce_downloads' file does not get used, and any file within is directly downloadable. Seems like a pretty common combination that could catch a lot of folks unaware.
