### ISSUE TITLE
Checkout page won't show the payment options/ info under "YOUR ORDER"

### ISSUE THREAD

**Issue by raphaelmarinho** [woothemes/woocommerce#7067]
'm having an issue with the Black Sea theme shop.

After adding a product to the cart (http://farafena.fabrocreative.com/cart/), the Checkout page won't show the payment options/ info under "YOUR ORDER".

Do you have any insights?

**Comment by mikejolley** [comment]
You have an error on your page. It's hidden - enable WP_DEBUG to see what it is exactly. http://codex.wordpress.org/WP_DEBUG

If its memory, increase it http://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP

If its some other error, its likely from your theme or another plugin you have installed. You'll need to do some investigation yourself into that.

Please note this isn't a support forum - its for bug reports only, and this isn't one. Good luck with your issue anyway.

**Comment by raphaelmarinho** [comment]
Thanks for the reply. I made the change but still didn't fix the issue.

**Comment by raphaelmarinho** [comment]
I got it fixed. Here is the solution:

Downloaded a fresh version of the Woocommerce plugin (https://wordpress.org/plugins/woocommerce/), then replaced the REVIEW-ORDER.PHP file that I had in my existing installation in my FTP folder /wp-content/plugins/woocommerce/templates/checkout

It only took me the entire day to figure it out :|
