### ISSUE TITLE
How to update/add custom item information in orders

### ISSUE THREAD

**Issue by novasdream** [woothemes/woocommerce#7069]
I want change add/change a meta_data in order **item** after complete a payment
is somethink like add a custom field with *secret* ***random number.***

How I can make that ?

I dont found how
```php
public function process_payment( $order_id ) {

    global $woocommerce;
    $order = new WC_Order( $order_id );

    // Mark as on-hold (we're awaiting the cheque)
    if ( 'yes' == $this->debug ) {
        $this->log->add( 'Compra', "IPN Response Loggin test" );
    }
    $order->get_items();
    if ( sizeof( $order->get_items() ) > 0 ) {
        foreach ( $order->get_items() as $item ) {
            if ( ! $item['qty'] ) {
                continue;
            }
            // Any information about function to edit meta data in item ?
        }
    }
    $order->payment_complete();
    // Reduce stock levels
    $order->reduce_order_stock();
    // Remove cart
    $woocommerce->cart->empty_cart();

    // Return thankyou redirect
    return array(
        'result' => 'success',
        'redirect' => $this->get_return_url( $order )
    );
}
```

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:
 
* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
