### ISSUE TITLE
Missing WC-quicktag button to insert shortcode

### ISSUE THREAD

**Issue by hapkemedia** [woothemes/woocommerce#7071]
After the update to 2.2.10 the quicktag button of WooCommerce is missing in the visual editor window.
Now it is not possible for me to insert a shortcode like [product id="" sku=""].

**Comment by claudiosmweb** [comment]
Was removed from WooCommerce 2.1.
You can use this plugin now: https://wordpress.org/plugins/woocommerce/screenshots/
