### ISSUE TITLE
Variable Products need shipping when all variations are virtual

### ISSUE THREAD

**Issue by thenbrent** [woothemes/woocommerce#7072]
The `WC_Product` class provides a handy `needs_shipping()` method to check if a product needs to be shipped (i.e. is not virtual).

However, the `WC_Product_Variable` class does not override `WC_Product::needs_shipping()` to check variations, nor does it set its own `virtual` property based on whether all of its variations are virtual or not.

As a result, a variable product's `virtual` property will always be set to the default value, of `'no'` and the variable product will always require shipping, even when all of its variations are virtual.

The `WC_Product_Variable::sync()` could be updated to check the `virtual` status of all variations and set  its own value based on that. If all variations are virtual, the variable product is virtual, otherwise it is not. This would also fix `WC_Product_Variable::needs_shipping()`.

If that sounds like a reasonable solution, let me know and I'll submit a pull request for v2.3.

**Comment by mikejolley** [comment]
Are there ever cases where a variable is checked directly, rather than one of it's variations? When in the cart, it should be a variation.

**Comment by thenbrent** [comment]
@mikejolley not in core, but in extensions.

For example, One Page Checkout tries to determine whether to displaying shipping fields on the checkout based on the products displayed on the page (which may include variable products), not just those products already in the cart.

We can fix the issue in OPC by looping over variations easily enough, but I think it is a bug in WC.

**Comment by mikejolley** [comment]
Your idea for 'sync' method handling this should work. What about other sub-types - downloadable etc?

**Comment by thenbrent** [comment]
> What about other sub-types - downloadable etc?

Looks like `$this->downloable` will default to `'no'` even if all variations are downloadable also: https://github.com/woothemes/woocommerce/blob/9c52a7059712839c033db97be877970de633ca17/includes/abstracts/abstract-wc-product.php#L63

Other properties look OK because they can be or are set at the variable level (i.e. `'backorders'`, `'manage_stock'`, `'featured'`, `'sold_individually'`, `'crosssell_ids'`, `'upsell_ids'`, `'hidden'` and `'tax_status'`).

> Your idea for 'sync' method handling this should work.

I'll submit a PR to determine `downloadable` and `virtual` based on variations in the next day or two.

**Comment by mikejolley** [comment]
:+1:
