### ISSUE TITLE
json_search_products does not appear to grab products from WPML languages.

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#7073]
When using WPML and performing a product search, product names are not returned translated.

[Screenshot 1](https://woothemes.zendesk.com/attachments/token/PDwytwTdxAKamrSHWQpNv1P9b/?name=2014-12-23_02-02-38.png)

[Screenshot 2](https://woothemes.zendesk.com/attachments/token/AjTgslFAkE1Z7Wm9u0Vb3bnet/?name=2014-12-23_01-57-02.png)

Ticket:
https://woothemes.zendesk.com/agent/tickets/242115

**Comment by claudiosmweb** [comment]
Content Blocks is not part of WooCommerce Core.
Seems that needs to be fixed in another plugin.
