### ISSUE TITLE
WooCommerce Data Update Required – We just need to update your install to the latest version

### ISSUE THREAD

**Issue by sobytes** [woothemes/woocommerce#7075]
Hi 

I constantly get this issue in this post can you help please. 

https://wordpress.org/support/topic/woocommerce-data-update-required

Thanks

**Comment by mikejolley** [comment]
If it's not going away after running, it may be running out of resources during the update (and thus not updating the database version).

Try increasing the memory limit (http://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP) and if that doesn't help, check your error logs to see if you can find out why its not succeeding.

**Comment by pramodhanu** [comment]
First, Take to Backup your Website and then you can update your Store.
