### ISSUE TITLE
Changing from variable product to simple product doesn't delete variations

### ISSUE THREAD

**Issue by kieranbarnes** [woothemes/woocommerce#7077]
If you have a variable product that gets changed back to a simple product without deleting each variation individually first the variations never get deleted.

This is cool if you accidently change from variable to simple as the variations reappear, however if the variations had SKUs this leads to issues when you add new products with the same SKU as other products at a later date.

We had a situation like this with a client earlier who couldn't add products, they reported the error "Product SKU must be unique."

Maybe delete the variations if the product is longer variable? Or at least remove the SKU as this prevents new products being added.

**Comment by claudiosmweb** [comment]
Not a good idea, exactly for this reason we display a notice warning that changing the type of product when it has variations.
About this editing has to have a little common sense and delete the changes.
If the opposite will happens several incidents of people losing data.

**Comment by kieranbarnes** [comment]
Perhaps a more detailed "Product SKU must be unique." error? This is the second time I've noticed this issue (2 different sites)?

**Comment by aliomaster** [comment]
This is not a bug. These are former variations of variable products when it type have been changed to Simple or another type of product not variable. WooCommerce does not remove these variations to the case you decide to change the product type on variable again. For this case variables remain intact with all fields filled in, including the SKU field.
This plugin helps to remove old variations - https://wordpress.org/plugins/sku-error-fixer-for-woocommerce/
