### ISSUE TITLE
Bug? esc_html__( $order->status, 'woocommerce-bookings' ) not translated

### ISSUE THREAD

**Issue by nicmare** [woothemes/woocommerce#7079]
in my wordpress orders overview everything is translated properly except the column "order" where you see a link to the order and after that a label i.e. "completed". I found the code in class-wc-bookings-cpt.php, line 271: esc_html__( $order->status, 'woocommerce-bookings' )
for some reasons these text strings do not appear in WC Bookings language pot file?! i've also checked english translation in transiflex. there are no strings for the order status.

**Comment by coenjacobs** [comment]
You should contact WooThemes support. This is just the bug tracker for the core WooCommerce plugin and you need help with the WooCommerce Bookings premium extension.

**Comment by nicmare** [comment]
damn it. yes of course. you are right. just forget it for a moment…
