### ISSUE TITLE
Globa Price for Variable Product

### ISSUE THREAD

**Issue by SilverKenn** [woothemes/woocommerce#7085]
How do you set a global price for variable product?

I have a product that has two variations, "Color" and "Size". all variations have the same data, except the thumbnail for each color, 

I see that you can set a global dimensions, but isn't it possible with the price? do I have do a "LINK all variations" then set the same prices for each variations? 

Can someone please verify? Been working with woocommerce since version 1.0 but its my first time dealing with prices, 

Thank you,

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:
 
* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
