### ISSUE TITLE
abstract-wc-order.php - method "add_product" doesn't add line_tax_data

### ISSUE THREAD

**Issue by perfectsenseab** [woothemes/woocommerce#7088]
In the method add_product, there seems to be code missing that should write the line_tax_data which currently results in blank tax data in the admin interface if an order is created programmatically.

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce/blob/cab9e14fcd69d9634a445eb54d9031a2ac5f02a7/includes/abstracts/abstract-wc-order.php#L154-L164
