### ISSUE TITLE
Products have disappeared in WooCommerce

### ISSUE THREAD

**Issue by hitechenterprisesinc** [woothemes/woocommerce#7090]
Running WP 4.1 Virtue Child theme (from Virtue 2.3.3), Woo 2.2.10.  All products, except those in Trash have disappeared.  Changed to 2014 Theme, deactivated all plugins except Woo and no change.  System status only showing recommend upgrade WP memory limit from 40 to 64.

### Environment ###

Home URL:                http://www.videoequipment.com/arwp
Site URL:                http://www.videoequipment.com/arwp
WC Version:              2.2.10
WC Database Version:     2.2.10
WP Version:              4.1
WP Multisite Enabled:    No
Web Server Info:         Apache
PHP Version:             5.4.35
MySQL Version:           5.5.40
WP Active Plugins:       15
WP Memory Limit:         40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode:           No
WP Language:             en_US
WP Max Upload Size:      64 MB
PHP Post Max Size:       64 MB
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
WC Logging:              Log directory (/home1/eqvid939/public_html/arwp/wc-logs/) is writable.
Default Timezone:        Default timezone is UTC
fsockopen/cURL:          Your server has fsockopen and cURL enabled.
SOAP Client:             Your server has the SOAP Client class enabled.
WP Remote Post:          wp_remote_post() was successful - PayPal IPN is working.

### Locale ###

decimal_point:           .
thousands_sep:           N/A
mon_decimal_point:       N/A
mon_thousands_sep:       N/A

### Plugins ###

Installed Plugins:       Google Fonts For WordPress by Lukas Pawlik version 2.0.2
                         Limit Login Attempts by Johan Eenfeldt version 1.7.1
                         PayPal for WooCommerce by Angell EYE version 1.1.5.3
                         Redirection by John Godley version 2.3.12
                         Regenerate Thumbnails Reminder by Nicolas Jonas version 1.3.1
                         Regenerate Thumbnails by Viper007Bond version 2.2.4
                         Search By SKU - for Woocommerce by Matthew Lawson version 0.6.1
                         Sucuri Security - Auditing
                         Malware Scanner and Hardening by Sucuri
                         INC version 1.7.5
                         UpdraftPlus - Backup/Restore by UpdraftPlus.Com
                         DavidAnderson version 1.9.46
                         Virtue / Pinnacle ToolKit by Kadence Themes version 2.5
                         WooCommerce PDF Invoices & Packing Slips by Ewout Fernhout version 1.5.2
                         Woocommerce Product Tabs by Nilambar Sharma version 1.0.1
                         WooCommerce Sequential Order Numbers by SkyVerge version 1.3.4
                         WooCommerce by WooThemes version 2.2.10
                         WP-Lister Pro for eBay by Matthias Krok version 2.0.5

### Settings ###

Force SSL:               No

### WC Pages ###

Shop Base:               #17 - /
Cart:                    #18 - /cart/
Checkout:                #19 - /checkout/
My Account:              #20 - /my-account/

### WC Taxonomies ###

Product Types:           external (external)
                         grouped (grouped)
                         simple (simple)
                         variable (variable)

### Theme ###

Theme Name:              virtue child
Theme Version:           1.0
Theme Author URL:        http://videoequipment.com/arwp
Is Child Theme:          Yes
Parent Theme Name:       Virtue
Parent Theme Version:    2.3.3
Parent Theme Author URL: http://kadencethemes.com/
WooCommerce Support:     Yes

### Templates ###

Template Overrides (WooCommerce):virtue/woocommerce/archive-product.php
                         virtue/woocommerce/cart/shipping-calculator.php
                         virtue/woocommerce/content-product.php
                         virtue/woocommerce/content-product_cat.php
                         virtue/woocommerce/content-single-product.php
                         virtue/woocommerce/loop/add-to-cart.php
                         virtue/woocommerce/loop/loop-end.php
                         virtue/woocommerce/loop/loop-start.php
                         virtue/woocommerce/loop/price.php
                         virtue/woocommerce/loop/rating.php
                         virtue/woocommerce/loop/sale-flash.php
                         virtue/woocommerce/order/form-tracking.php
                         virtue/woocommerce/single-product/add-to-cart/external.php
                         virtue/woocommerce/single-product/add-to-cart/grouped.php
                         virtue/woocommerce/single-product/add-to-cart/simple.php
                         virtue/woocommerce/single-product/add-to-cart/variable.php
                         virtue/woocommerce/single-product/price.php
                         virtue/woocommerce/single-product/product-image.php
                         virtue/woocommerce/single-product/product-thumbnails.php
                         virtue/woocommerce/single-product/rating.php
                         virtue/woocommerce/single-product/review.php
                         virtue/woocommerce/single-product/sale-flash.php
                         virtue/woocommerce/single-product/share.php
                         virtue/woocommerce/single-product/short-description.php
                         virtue/woocommerce/single-product-reviews.php
                         virtue/woocommerce/single-product.php
                         virtue/woocommerce/taxonomy-product_cat.php
                         virtue/woocommerce/taxonomy-product_tag.php

**Comment by bryceadams** [comment]
Hi @hitechenterprisesinc - This is not an official WooThemes support channel. If you are a paying WooThemes customer, please open a new ticket here: http://support.woothemes.com/hc/en-us/requests/new - so a Support Ninja can assist you. If you have yet to purchase a product from WooThemes.com you can post your query to the public support forums here: http://wordpress.org/support/plugin/woocommerce 

Thanks!
