### ISSUE TITLE
Tax information for orders in wp-admin/post.php is partially based upon current (rather than order-time) tax tables

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#7092]
The "Order Items" meta box for an order (i.e.in the page wp-admin/post.php?action=edit&post_id=<order_id>) shows tax information that is partially based upon data in the tax rate tables at the time that the meta box is viewed - rather than at the time that the order was created.

There may be others, but specifically, in includes/admin/meta-boxes/views/html-order-items.php, tax labels are fetched via a call to:

```wc_get_tax_class_by_tax_id( $tax_item['rate_id'] );```

This function selects the current data from the woocommerce_tax_rates table.

There are multiple scenarios under which this may be problematic; e.g.

1) The shop owner deleted the tax rate, and re-created it, for some reason. Result: no label.

2) The shop owner includes the tax rate in the tax label. This is common with shop owners who charge VAT (any VAT - not just the new EU digital VAT), because in some jurisdictions, it is compulsory for invoices to display the VAT rates charged, and totals separated by VAT rate. Including the rate in the label means that this can be achieved. However, if the VAT rate later changes (and many VAT rates are happening or proposed at the present time - see vatlive.com), then the label changes. And thus, the rate shown in the label in the meta box may differ from the actual rate that was charged at the time. It may show "VAT (24%"), when in fact what was charged on the order was 22%.

It looks like the line_tax_data item meta added in WC 2.2 was an attempt to solve some of the problems resulting from information about how different taxes corresponded to different line items not being recorded. However, this attempt is incomplete; the tax label needs to also be recorded.

**Comment by mikejolley** [comment]
I think you're mistaken here.

wc_get_tax_class_by_tax_id() gets live data yes, but this is not the label. This is the tax class.

The label comes from here:

`
$column_label   = ! empty( $tax_item['label'] ) ? $tax_item['label'] : __( 'Tax', 'woocommerce' );
`

This is stored within the actual tax line, so the data will always reflect that which existed at the time it was saved.
