### ISSUE TITLE
Adding a html under the shipping info box

### ISSUE THREAD

**Issue by oaattia** [woothemes/woocommerce#7093]
Hello, i searched in woocommerce code for a hook to add a new html section after the a specifc shipping method but with no luck, i just created a new shipping method with woocommerce shipping api, but i struggled in adding  html for front shipping info box ( selectbox for the user to choose from ) . 

I see that that that whole info box rendered as a ajax ? is there is any solution to do that ?

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:
 
* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
