### ISSUE TITLE
admin-ajax used also when there's not the cart

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7102]
Using TwentyTwelve as example, without widget cart or anything else which should use admin-ajax.php, i have this in the console

![](http://cld.wthms.co/133DS+)

seems that it calls admin-ajax.php also when it's not needed.

**Ticket 248607**

**Comment by ChromeOrange** [comment]
Oop, sorry @barrykooij I was supposed to create an issue wasn't I 

@SiR-DanieL do you have add to cart buttons on that page?

@barrykooij 

https://dl.dropboxusercontent.com/s/tlskua4gzyauhwg/2014-12-15%20at%2008.12%202x.png?dl=0

>class-wc-frontend-scripts.php#141-146 and #178-183
those are the two blocks on the frontpage
I'll fix this for 2.3

**Comment by SiR-DanieL** [comment]
No @ChromeOrange , it's the index page with the blog.

**Comment by mikejolley** [comment]
@ChromeOrange @SiR-DanieL This request is understandable. Some themes don't have widget cart, but they do have areas that need updating via ajax. This runs in order to update those areas.

**Comment by mikejolley** [comment]
Those fragments (stored in local storage) also need updating after a cart has been emptied so you cannot just non-enqueue the entire script conditionally.

**Comment by mikejolley** [comment]
The second issue (two vars) @ChromeOrange is already fixed in 2.3

**Comment by mikejolley** [comment]
Script called wc-cart-fragments can be de-enqueued if needed.
