### ISSUE TITLE
[2.3.0] Warning when default stylesheets are dequeued

### ISSUE THREAD

**Issue by blainerobison** [woothemes/woocommerce#7104]
Version: 2.3.0 Beta 1

I receive the following warning when I [disable the default stylesheet](http://docs.woothemes.com/document/disable-the-default-stylesheet/) via the `woocommerce_enqueue_styles` hook.

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /Users/mactop/Sites/demostore.dev/wp-content/plugins/woocommerce-2.3.0-beta-1/includes/admin/class-wc-admin-notices.php on line 167

`add_filter( 'woocommerce_enqueue_styles', 	'__return_false' );`

**Comment by claudiosmweb** [comment]
`woocommerce_enqueue_styles` need to return an array.

The correct is use:

```php
add_filter( 'woocommerce_enqueue_styles', '__return_empty_array' );
```

**Comment by mikejolley** [comment]
@claudiosmweb we should probably work around that too and do a type check?

**Comment by claudiosmweb** [comment]
@mikejolley I'm doing it now ;)
