### ISSUE TITLE
Add Attribute Descriptions for Product Options

### ISSUE THREAD

**Issue by gthayer** [woothemes/woocommerce#7105]
Currently, there is no method for adding a description field for attributes within WooCommerce. This would be important for when the choice itself needs more explanation than each option, i.e. Why is having the correct t-shirt color important instead of why red is a great color.

An example seen in the wild exists on Apple.com:
http://store.apple.com/us/buy-mac/imac-retina?product=MF886LL/A&step=config

I've built a little plugin to add this field. Would you be interested in seeing a forked version of WooCommerce with these changes?

**Comment by splashingpixels** [comment]
I believe this would be a good feature.  But I am not sure if this should be in core or a plugin.  @mikejolley @claudiosmweb @barrykooij  thoughts?

**Comment by claudiosmweb** [comment]
Based on this "seen in the wild exists on Apple.com" example, this would look better in WooCommerce Product Add-ons.

**Comment by splashingpixels** [comment]
Yes I agree Product Add-Ons would benefit from this but I also think the core variations would be a good addition as well.

**Comment by gthayer** [comment]
Thanks for taking a look. With the current build, for the the additional input fields to exist as a plugin I've needed to extend WC_Admin_Attributes to override class-wc-admin-attributes.php which requires removing and re-creating the submenu pages. I'd consider this a sub-optimal approach.

However if lines 216 and 218 of class-wc-admin-attributes.php was changed from "self" to "static", I'd be able to extend the class WC_Admin_Attributes and override each function individually.

Below is a link to the plugin I've been working on. Perhaps this will give you a better sense of where I am coming from. I've sent invites to view the repo to each person tagged in @splashingpixels comment. Please let me know if you are unable to view.

https://github.com/hallme/WooCommerce-Attribute-Descriptions

**Comment by splashingpixels** [comment]
@gthayer wasn't able to see the repo.

**Comment by claudiosmweb** [comment]
@splashingpixels I agree with description for variations and not for attributes in the core.
But let's see what @gthayer has made.

**Comment by splashingpixels** [comment]
Yes I too agree that this shouldn't be tied to attributes as different products can use the same attributes.  So perhaps add a description field for the variation when generated.  Will have to think more on this.

**Comment by gthayer** [comment]
Sorry about that. You should have access to the repo now. It's still half baked, so please be kind :)

Description fields for the variations already exist, but are not commonly displayed. Additionally, tools like Advanced Custom Fields can hook into variations to add as many custom fields as the user would like.

Because Attributes are built outside of the usual taxonomy framework, ACF is unable to customize them. For me, the idea of adding a description field to the attribute specifically is important precisely because it is available across all products. In my personal opinion, if a single attribute is used differently for each product, then the admin should be creating different attributes for each product type.

Example:
Two attributes with the name "Size" can be given the slug "shoe-size" and "shirt-size". Each would have a different attribute description which helps the user find the respective size. An added benefit to this method of sorting would be better categorization of variations within each attribute, e.g. Shoes would never accidentally be labeled as "XL".

**Comment by splashingpixels** [comment]
@gthayer - right however the attribute "size" for example could be added to different types of products and the description could vary based on that.

**Comment by mikejolley** [comment]
Closed in fav of #7121 / #7118

**Comment by nimmolo** [comment]
@gthayer @roykho Hi just checking what became of this feature. I realize your work on this was long ago, but in my use case it would be good to add more fields than a description. I'd like to find a method to add fields to a variation, including a graphic.

**Comment by colorfill** [comment]
Hi Guys,
sorry for getting back to this old thread but I'm looking for a way to add 'description' field in the attribute generation form. 've tried both Toolset types and ACF without success.. Is it doable? Ideal outcome - lets say ive got an attribute Speed -> i would like to add an description: KM/H

**Comment by dakkafex** [comment]
its been 6 years... how is this still not implemented?....

**Comment by davidpottrell** [comment]
Still waiting
