### ISSUE TITLE
Currency symbol only in British Pound

### ISSUE THREAD

**Issue by WindowFrog** [woothemes/woocommerce#7106]
Regardless of what currency is set in the admin, the cart displays the British Pound.

**Comment by slash1andy** [comment]
Can you provide a bit more info? This hasn't happened to me or anyone that I've helped. 

Can you try changing your theme to the default 2012 and checking? Sounds like a theme issue.

**Comment by claudiosmweb** [comment]
Sounds like a problem with the theme or some plugin manipulating it.
Experiment with your plugins and theme.
Not a issue in WooCommerce.
