### ISSUE TITLE
Visual distinction when gateway doesn't support automatic refunds

### ISSUE THREAD

**Issue by dominic-p** [woothemes/woocommerce#7107]
This is more of a suggestion, but it would be nice if there was some kind of notice or visual distinction that let shop managers know if the payment gateway used to place an order supports automatic refunds.

The issue we ran into was that a refund was initiated in WC, and it was assumed that this would be sent to the payment gateway for processing even though that gateway didn't support auto refunds. It's a pretty minor issue, but it might improve the user experience a bit.

**Comment by splashingpixels** [comment]
So there is already a visual distinction.  If it supports it you will see both a "refund" button and a "manual refund" button.  If it does not, you will only see a "manual refund" button.

**Comment by dominic-p** [comment]
I suppose that makes sense (especially if you're working with a gateway that supports auto refunds), but I guess I'm just thinking it could be made clearer. If you only work with gateways that support manual refunds, you won't ever see the second button. You have to know that the word "manual" on the button means that you have to go to your gateway and initiate a refund. Maybe that shouldn't be a hard leap to make, but I've ran into real world issues with it. :)

Perhaps a simple notice that appears with the rest of the refund details (after you click the refund button) that reads something to the effect of:

`
"The payment gateway used to process this order does not support automatic refunds. You will still need to manually issue a refund through your payment gateway."
`

**Comment by splashingpixels** [comment]
Yes I see your point.  Since there is a modal box popup when refund is clicked, perhaps the message can be displayed there.

**Comment by dominic-p** [comment]
Yeah, that would be perfect I think. Would you like me to put together a pull request?

**Comment by mikejolley** [comment]
@dominic-p go for it

**Comment by mikejolley** [comment]
#7117
