### ISSUE TITLE
Problem with Shop Margins

### ISSUE THREAD

**Issue by olplotard** [woothemes/woocommerce#7108]
Hi, I am new with Woocommerce and I installed the plugin on my wordpress website. I have a problem with the margins of my "shop" page as well as the title of the page that I cannot change ("categorized as")

Can you help me with this issue please?
url: http://brunbanana.com/shop-2/

Thx!!

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:
 
* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
