### ISSUE TITLE
[2.3] WooCommerce cart widget not working when the add_to_cart_fragments filter hook is used

### ISSUE THREAD

**Issue by dennyf** [woothemes/woocommerce#7110]
Hi All,

I just found that when using the now deprecated "add_to_cart_fragments" filter, the WooCommerce Cart widget doesn't work anymore - it doesn't generate any content at all. You can test this by using the following code:

```
add_filter('add_to_cart_fragments', 'my_add_to_cart_fragments');
function my_add_to_cart_fragments($fragments){
	return $fragments;
}
```
Once the filter is registered in a theme or plugin, even when the hooked function doesn't do anything, the Cart Widget content would be empty - it wouldn't show the items added to the cart.

I have tested this code with multiple themes and no additional plugins active, with the latest version of WordPress running and WooCommerce 2.3 Beta 1.

**Comment by mikejolley** [comment]
Due to the notice being fired during the ajax event.
