### ISSUE TITLE
Download permissions not available

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7111]
On some sites i get an error with download permissions.

As soon as i come back from the payment gateway (usually PayPal) i still do not have the download permissions. If i refresh the page then it's ok, i can see the download links and files.

I debugged this code

```
if ( $_product && $_product->exists() && $_product->is_downloadable() && $order->is_download_permitted() ) {
```

and only ` $order->is_download_permitted()` return false.

**Comment by mikejolley** [comment]
Enable PDT or there may be a delay with the IPN update.
