### ISSUE TITLE
2.3 Beta 1 Variations Problem

### ISSUE THREAD

**Issue by onebob** [woothemes/woocommerce#7115]
The variations select boxes do not 'refill' with the selected data when saved/opened although the variations exist and display correctly if you revert to 2.2.10

WP Version:              4.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.4.7
PHP Version:             5.5.9-1ubuntu4.5
MySQL Version:           5.5.40
WP Active Plugins:       5
WP Memory Limit:         1 GB
WP Debug Mode:           Yes
WP Language:             en_GB
WP Max Upload Size:      8 MB
PHP Post Max Size:       64 MB
PHP Time Limit:          300
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
WC Logging:              Log directory (/home/wordpress/public_html/wc-logs/) is writable.
Default Timezone:        Default timezone is UTC
fsockopen/cURL:          Your server has fsockopen and cURL enabled.
SOAP Client:             Your server has the SOAP Client class enabled.
WP Remote Post:          wp_remote_post() was successful - PayPal IPN is working.

### Locale ###

decimal_point:           .
thousands_sep:           N/A
mon_decimal_point:       N/A
mon_thousands_sep:       N/A

### Plugins ###

Installed Plugins:       Duplicator by LifeInTheGrid version 0.5.12
                         White Label CMS by www.videousermanuals.com version 1.5.2
                         WooCommerce by WooThemes version 2.2.10
                         WordPress Importer by wordpressdotorg version 0.6.1
                         WordPress Reset by Matt Martz version 1.3.3

### Settings ###

Force SSL:               No

### WC Pages ###

Shop Base:               #1740 - /shop/
Basket:                  #1741 - /cart/
Checkout:                #1742 - /checkout/
My Account:              #1743 - /my-account/

### WC Taxonomies ###

Product Types:           external (external)
                         grouped (grouped)
                         simple (simple)
                         variable (variable)

### Theme ###

Theme Name:              xxxxxxxxxxxxxxxxx bespoke
Theme Version:           1.1
Theme Author URL:        http://redforgedesign.co.uk
Is Child Theme:          No
WooCommerce Support:     Yes

### Templates ###

Template Overrides:      No overrides present in theme.

**Comment by claudiosmweb** [comment]
For the sake of all that is most sacred in the world. Don't use a beta version in production!

**Comment by claudiosmweb** [comment]
Show me a screenshot of it.

**Comment by claudiosmweb** [comment]
This in the frontend or backend?

**Comment by onebob** [comment]
Hi Claudio

Sorry Yes I should have said backend.

Please see attached screenshots, one is 2.2.10 the other (with Any Frame
etc) is the 2.3  beta.

Thanks

David
AKA Onebob

**Comment by claudiosmweb** [comment]
@onebob attached screenshots don't work from emails, you need to come back here on Github and add the images.

**Comment by onebob** [comment]
Hi Claudio

Sorry about that, first time using github issues!

So firstly you don't need to worry about using beta in product, wow who would be that stupid!

This is a test system on my local server....

Secondly as you will see the same product, same variations, first screen shot shows data correctly:

![screenshot from 2015-01-15 17 01 31](https://cloud.githubusercontent.com/assets/4520729/5762706/f8026172-9cdb-11e4-88c2-ac8715dc4370.png)

second screen shot shows the variations by ID but all the select boxes effectively empty, although on the frontend the selects display OK:

![screenshot from 2015-01-15 17 02 50](https://cloud.githubusercontent.com/assets/4520729/5762725/20a66cea-9cdc-11e4-958b-51276edaa440.png)

Thanks for your time

Onebob

**Comment by claudiosmweb** [comment]
@onebob when you said you did downgrade, I thought it was in production xD

**Comment by onebob** [comment]
Hi Claudio

Yeah I probably should have made it clear at the beginning, sorry, I think it was the excitement of actually having a bug to post  8^)

Cheers

Onebob

**Comment by claudiosmweb** [comment]
@onebob thanks man, I'm fixing this right now :)

**Comment by claudiosmweb** [comment]
@onebob fixed :D
Thank you very much for reporting this bug.

**Comment by onebob** [comment]
Hi, quick work thanks

**Comment by helgatheviking** [comment]
@claudiosmweb I am having trouble with Name Your Price and the WC2.3beta and I think it is related to this. 

In 2.3, the `$variation_data` was set to include all the variation's meta 

```
$variation_data                      = get_post_meta( $variation_id );   
```

which was important since the `$variation_data` is passed to the `html-variation-admin.php` views template, and it then passed along to the action hook where I am adding the NYP checkbox. 

```
<?php do_action( 'woocommerce_variation_options', $loop, $variation_data, $variation ); ?>
```

and to the 

```
<?php do_action( 'woocommerce_product_after_variable_attributes', $loop, $variation_data, $variation ); ?>
```

Basically the nyp meta isn't in `$variation_data` any more so the checkbox and values are always blank.

**Comment by helgatheviking** [comment]
Never mind. I can get the `$variation->ID` out of the 3rd passed variable and get the post meta from there. Do you know if `$variation` has always been passed to those hooks? Just wondering if I will have backcompat issues this way.

**Comment by claudiosmweb** [comment]
@helgatheviking yes, I can confirm that it will works at least since 2.0: https://github.com/woothemes/woocommerce/blob/v2.0.20/admin/post-types/writepanels/variation-admin-html.php#L163

:)

**Comment by helgatheviking** [comment]
Perfect. Obrigada!
