### ISSUE TITLE
Duplicate javascript code on page

### ISSUE THREAD

**Issue by Track77** [woothemes/woocommerce#7119]
Hi!
This code is duplicated on front-pages.
woocommerce version:2.2.10 

    var wc_add_to_cart_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","ajax_loader_url":"\/\/3d-kstudio.com\/wp-content\/plugins\/woocommerce\/assets\/images\/ajax-loader@2x.gif","i18n_view_cart":"View Cart","cart_url":"http:\/\/3d-kstudio.com\/cart\/","is_cart":"","cart_redirect_after_add":"no"};
    var wc_add_to_cart_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","ajax_loader_url":"\/\/3d-kstudio.com\/wp-content\/plugins\/woocommerce\/assets\/images\/ajax-loader@2x.gif","i18n_view_cart":"View Cart","cart_url":"http:\/\/3d-kstudio.com\/cart\/","is_cart":"","cart_redirect_after_add":"no"};
----------------
    var woocommerce_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","ajax_loader_url":"\/\/3d-kstudio.com\/wp-content\/plugins\/woocommerce\/assets\/images\/ajax-loader@2x.gif"};
    var woocommerce_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","ajax_loader_url":"\/\/3d-kstudio.com\/wp-content\/plugins\/woocommerce\/assets\/images\/ajax-loader@2x.gif"};
----------------
    var wc_cart_fragments_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","fragment_name":"wc_fragments"};
    var wc_cart_fragments_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","fragment_name":"wc_fragments"};

**Comment by splashingpixels** [comment]
This is already fixed in the next 2.3...
