### ISSUE TITLE
API Order total/subtotal bug

### ISSUE THREAD

**Issue by Nils-Fredrik** [woothemes/woocommerce#7120]
Hi and thanks for creating WooCommerce,

I think I have found a bug in the API v2. 

In file: woocommerce/includes/class-wc-api-orders.php, in the method: `set_line_item($order, $item, $action)` from line 865 where you start asigning total values to the `$item_args` array. The naming for the array keys are `$item_args['totals']['line_total']`, `$item_args['totals']['line_tax']`, etc. All using 'line_'. 

The the $item_args is passed to the `add_product()` method in the WC_Order object (file: woocommerce/includes/abstracts/abstract-wc-order.php line 112). 

In the `add_product()` method the above `$item_args` is `$args`. But, on line 135 to 138 it tries to use the array keys: `$args['totals']['subtotal']`, `$args['totals']['total']`, `$args['totals']['subtotal_tax']` and `$args['totals']['tax']`. But, they don't exist. The real array keys are: line_subtotal, line_total, line_tax and line_subtotal_tax. The same goes for the `update_product()` method in the WC_Order object which also is called from `set_line_item()`.

So, in stead of using the passed values it fetches product prices from the database. But, I dont want that, I want to specify my own prices. 

I guess this should be fixed in class-wc-api-orders.php and not in the abstract-wc-order.php, perhaps as simple as this?

```php
// total
if ( isset( $item['total'] ) ) {
$item_args['totals']['total'] = floatval( $item['total'] );
}

// total tax
if ( isset( $item['total_tax'] ) ) {
$item_args['totals']['tax'] = floatval( $item['total_tax'] );
}

// subtotal
if ( isset( $item['subtotal'] ) ) {
$item_args['totals']['subtotal'] = floatval( $item['subtotal'] );
}

// subtotal tax
if ( isset( $item['subtotal_tax'] ) ) {
$item_args['totals']['subtotal_tax'] = floatval( $item['subtotal_tax'] );
}

``` 

Best regards,

Nils-Fredrik

http://twitter.com/nilsfredrik

**Comment by mikejolley** [comment]
It's already there in 2.3 https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-orders.php#L881

**Comment by Nils-Fredrik** [comment]
Great! :+1:
