### ISSUE TITLE
Show SKU on list for Variable Products

### ISSUE THREAD

**Issue by lmartins** [woothemes/woocommerce#7124]
Variable products should also show the SKU's entries on list.
I understand this poses a problem for the sorting algorithm, to which I don't really have a solution, perhaps consider the first SKU for the sorting, anyway customer heavily relying on SKUs need this information available for search and visible in the dashboard list.

**Comment by claudiosmweb** [comment]
What list are you talking about?

**Comment by lmartins** [comment]
Products list on the backend interface

**Comment by mikejolley** [comment]
Listing SKUs there, but not being able to sort by them, would appear confusing to end-users IMO.

What you can do is set the variation SKU instead. So say you have variations with PRODUCT-BLUE, PRODUCT-RED, you can give the parent a SKU of PRODUCT. That will be displayed, and sortable, in admin.

**Comment by lmartins** [comment]
Yup, that's a reasonable approach too. Thank you Mike.
