### ISSUE TITLE
Duplicate SKUs are silently deleted on product insertion

### ISSUE THREAD

**Issue by lmartins** [woothemes/woocommerce#7125]
When adding a new product, if we insert an SKU already inserted in another product, the system doesn't show any information, accepts the save but silently deletes the contents from that field.

**Comment by claudiosmweb** [comment]
You receive an alert about it, see:

![screenshot from 2015-01-16 09 09 03](https://cloud.githubusercontent.com/assets/1264099/5775298/60dab0cc-9d5f-11e4-83a3-3872d8b5b726.png)
