### ISSUE TITLE
Console error on checkout (select2)

### ISSUE THREAD

**Issue by JeroenSormani** [woothemes/woocommerce#7127]
Hi,

I'm getting a error in my console as follows; http://cl.ly/image/1V3n2C1K2i1m

On both a fresh install and a older install (tested on woocommerce-2.3.0-beta-1 and the latest code pulled form GH).

Error detail; http://cl.ly/image/1A0Y0E31183Z

(tested local on MAMP)

**Comment by mikejolley** [comment]
Seems to be select2 itself, but how do you replicate it?

**Comment by JeroenSormani** [comment]
It looks like its only happening when logged in, and already done a order to the Netherlands. 
This defaults the country field to the Netherlands and I see the error. When doing a order to the UK and re-check I don't get the error.

Does that make sense?

Done some very quick testing and when commenting this line I don't get the error. http://cl.ly/image/0D2q1r0e1F2V

Will do some more testing / debugging when I've got some more time..
