### ISSUE TITLE
Shipping cost inclusive of tax

### ISSUE THREAD

**Issue by RistoNiinemets** [woothemes/woocommerce#7128]
My scenario:
* Taxes enabled
* Standard Rate set to 20%, applied to shipping
* Prices entered tax inclusive
* Prices shown tax inclusive (in cart and shop)
* One shipping method: International Delivery, cost 10€, taxable

The problem is that shipping cost calculation does not respect the option to show prices inclusive of tax. At the moment, International Delivery will be applied tax of 20% (total of 12€), whereas it should be 10€ (including 1.67€ tax).

````php
public static function calc_shipping_tax( $price, $rates ) {
	return self::calc_exclusive_tax( $price, $rates );
}
````

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-tax.php#L63

I tried:
````php
public static function calc_shipping_tax( $price, $rates ) {
	return self::calc_tax( $price, $rates, wc_prices_include_tax() );
}
````
Which will calculate the taxes right, but cart still sums shipping taxes and shipping total altogether, not respecting "inclusive of tax" option.

Is this the way it is supposed to work?

**Comment by mikejolley** [comment]
Shipping costs are always defined tax-exclusive regardless of product settings. There is a roadmap item about it here https://trello.com/c/cjHijcxy/19-shipping-inc-tax-prices-4425
