### ISSUE TITLE
Errors in applying discount coupon to shipping costs and tax calculation

### ISSUE THREAD

**Issue by ebalink** [woothemes/woocommerce#7129]
When discount coupon (cart % discount) is applied with  "apply before tax" as checked, the discount is only calculated from the order's product and not applied to shipping costs. 
When "apply before tax" is set to unchecked, the discount is calculated from the shipping costs as well, but the stored tax amounts are not updated and refer to prices without discount. So for the buyer in Cart and Checkout pages and for the store admin in Edit Order -page the tax money amounts are too big.
In the pictures a coupon of 10 % discount is used.

![image](https://cloud.githubusercontent.com/assets/1458230/5776860/d6e99f5e-9d95-11e4-9223-56233277fd61.png)

![image](https://cloud.githubusercontent.com/assets/1458230/5776862/dc3ab56a-9d95-11e4-978b-688963e7515c.png)

**Comment by mikejolley** [comment]
If its applied after tax, tax isn't changed. These types of discounts are being removed in WC 2.3.

Regarding the other type, discounts apply to products in the cart only. It's a cart discount.

**Comment by ebalink** [comment]
Ok.

In that case I hope you'll provide another discount coupon option to give exact money amount discounts regarding the total price (including tax).
E.g.: with 20 € discount:
* (price net 100 € * VAT 24 % ) - discount 20 € = 104,00 €
* (price net 100 € - discount 20 € ) * VAT 24 % = 99,20 €.

Of course the stores CAN do the math when providing discounts, but I think for the customer the former discount option is more clear than the latter.
