### ISSUE TITLE
Coupon product search finding invalid products

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#7133]
To recreate this issue: 
1. Make note of a product's SKU in your store (tested with a non-numeric SKU value)
2. Change the SKU of that product to be something else, unrelated to the original SKU
3. Add a new coupon and on the Usage Restrictions tab, search for a product using the original SKU that you noted in step 1
4. You will see that the product that you changed the SKU for displays in the list, even though the product name, SKU, slug (nothing!) refers to the search term you're using

**Comment by mikejolley** [comment]
Tested this on 2.3.

1. used random-sku
2. Searched for random-sku, found it.
3. Changed to something-else.
4. Searched random-sku again - no results.

I'd guess this as being either caching (wpengine?) or a plugin (WPML?), unless of course the product data contains the same text as the SKU in another field. This uses WordPress 's' searching which searches post content/description/meta.

**Comment by MindyPostoff** [comment]
Weird. I can't re-create this issue any more. I had tested locally (not WPEngine and no caching) and noticed it was not displaying the parent product, only the variations. Will investigate further on client site. Thanks!
