### ISSUE TITLE
Auto Shipping Calculation Selects Text Fields in Checkout Form in Safari 6.1.6

### ISSUE THREAD

**Issue by ishmaelangelo** [woothemes/woocommerce#7135]
When typing and moving between the address fields, woocommerce does periodic shipping recalculation in checkout.js:

	$( 'form.checkout' )

	/* Update totals/taxes/shipping */
	// Inputs/selects which update totals instantly
	.on( 'input change', 'select.shipping_method, input[name^=shipping_method], #ship-to-different-address input, .update_totals_on_change select, .update_totals_on_change input[type=radio]', function() {
		clearTimeout( updateTimer );
		dirtyInput = false;
		$( 'body' ).trigger( 'update_checkout' );
	})

update_checkout() makes an ajax call. In Safari, after the callback completes, the current active textfield gets all of its text selected, so that if you are in the middle of typing, you overwrite everything.

No issue in other browsers, Just Safari 6.1.6
WordPress 4.1
WooCommerce 2.2.10
OSX 10.7.5

**Comment by ishmaelangelo** [comment]
The culprit is this code: $( '#order_review' ).html( $.trim( response.html ) ); on line 122 of checkout.js

If it is commented out, the current text field that you are typing in does not have its text selected.

In my case, shipping is free and tax is based on seller's location, not the buyer's, so nothing is going to change in the order_review table upon changes to the address information, so I just commented out line 122, and also line 56 where the overlay is placed over order_review.

**Comment by mikejolley** [comment]
This doesn't occur in latest builds of Safari so must have been a bug in 6.1.x. Current version is 8.x. 

Safari 6 doesn't even register on usage stats so I don't feel we should look into a workaround for this browser issue http://www.w3counter.com/globalstats.php

Thanks

**Comment by ishmaelangelo** [comment]
Ok, thanks, I won't worry about it then.
