### ISSUE TITLE
Product.default_attribute is not saved if attribute isn't global via API

### ISSUE THREAD

**Issue by jdluzen** [woothemes/woocommerce#7137]
When creating a variable product, it seems that the default_attribute[s] are not saved if it's not a global attribute. If the attributes are by product only, the default is not saved because get_attribute_taxonomy_by_label can return null.

**Comment by splashingpixels** [comment]
Can you please explain more on this?  I am testing 2.3 beta and I am not seeing this issue.  Here are custom added attributes and I have set a default and it saves fine.  See here http://cld.wthms.co/1hh4H

**Comment by jdluzen** [comment]
Ah, I should have added: this is via the API.

**Comment by claudiosmweb** [comment]
@jdluzen show me what you are doing.

**Comment by claudiosmweb** [comment]
Fixed in 2.3.
