### ISSUE TITLE
REST API Warning when creating an order with a fee line

### ISSUE THREAD

**Issue by madianas** [woothemes/woocommerce#7140]
When creating an order via with a fee line via REST API, I get the following warning:

```
<br />
<b>Warning</b>:  array_map(): Argument #2 should be an array in <b>html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php</b> on line <b>412</b><br />
```
The order is still created with fee lines, however I believe fee line taxes are not saved properly due to this warning.

To reproduce pass POST request to https://site/wc-api/v2/orders? with this in the body:

```{
  "order": {
    "order_number": "90519",
    "customer_id": "2",
    "shipping_lines": [
      {
        "method_id": "flat_rate",
        "method_title": "Delivery",
        "total": "123.2000"
      }
    ],
    "fee_lines": [
      {
        "title": "OPT KITCHEN",
        "total": "3186.0000",
        "taxable": true,
        "tax_class": "standard",
        "total_tax": "414.180000"
      },
      {
        "title": "Customer Discount Per Line",
        "total": "-2102.7600"
      }
    ]
  }
}```

I am trying to add fee lines with tax

**Comment by mikejolley** [comment]
There is a workaround in 2.3 where it sets the tax_data array. This should be passed in though (it's an array of tax lines). Example https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L1979
