### ISSUE TITLE
wc_customer_bought_product() causes non-object PHP error notices // improperly checks user_id value

### ISSUE THREAD

**Issue by janeczku** [woothemes/woocommerce#7145]
My PHP error log gets spammed with literally hundreds of the following PHP error notice:
> Trying to get property of non-object in /wp-content/plugins/woocommerce/includes/wc-user-functions.php on line 230

https://github.com/woothemes/woocommerce/blob/master/templates/single-product-reviews.php#L52
```PHP
	<?php if ( ... || wc_customer_bought_product( '', get_current_user_id(), $product->id ) ) : ?>
```
So when user is not logged in, then the wc_customer_bought_product() function is invoked with  the default return value of get_current_user_id() = 0.

This then triggers the PHP error notice, since the conditional logic in wc_customer_bought_product() does not exclude 0 values:
```PHP
if ( $user_id ) {
```
returns true for $user_id = (int) 0

It then tries to access the $user->user_email property without checking if $user object has been initialized. Of course when $user_id = 0 then $user = false.

https://github.com/woothemes/woocommerce/blob/master/includes/wc-user-functions.php#L219-L227
```PHP
function wc_customer_bought_product( $customer_email, $user_id, $product_id ) {
	global $wpdb;
	$emails = array();
	if ( $user_id ) {
		$user     = get_user_by( 'id', $user_id );
		$emails[] = $user->user_email;
	}
```

Fix:

https://github.com/woothemes/woocommerce/blob/master/includes/wc-user-functions.php#L224
```PHP
- if ( $user_id ) {
+ if ( ! empty($user_id) ) {
```

**Comment by claudiosmweb** [comment]
This does not prevent errors when you send a user ID that does not exist.
