### ISSUE TITLE
Some template changes can be undone by ajax fragments

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#7150]
EG https://www.dropbox.com/sc/vumatjh3c8ne3rq/AAC1zsixuaUBidDAoszeeHaxa

Basically a customer wanted to change the heading from PRODUCT to ITEM on the checkout so he modified the review-order.php template file and it shows ITEM until that section is refreshed, then it changes back to PRODUCT.

This customer is now using Say What to work around the issue

**Comment by mikejolley** [comment]
@ChromeOrange Checkout doesn't use the fragments/cache - it reloads the review-order.php template. If you make a change to the review-order.php file you can confirm this.

Probably his customisation!
