### ISSUE TITLE
[2.2] Package rate transients are not cleared on settings save / product save

### ISSUE THREAD

**Issue by franticpsyx** [woothemes/woocommerce#7151]
See https://github.com/woothemes/woocommerce/issues/6723

Confirmed this is still an issue in 2.2:

Saving the shipping settings does not clear the `_wc_ship` transients. For instance, changing the per-item cost in flat-rate shipping has no effect for cached package rates.

**Comment by franticpsyx** [comment]
2.3 needs to be checked, too -- https://github.com/woothemes/woocommerce/commit/9e53b3fb3316c6b9111b13917a2a028fb01096cb resolved the first issue there but not the second.

**Comment by mikejolley** [comment]
Won't be patching 2.2 - 2.3 will be the next release. Will see if we can expire _wc_ship instead of deleting them so we can avoid that query.
