### ISSUE TITLE
Variable products without sale price are listed as 'free'

### ISSUE THREAD

**Issue by colibriinteractive** [woothemes/woocommerce#7154]
When I create a variable product with attributes and set the regular price this price is not shown correctly. It shows 'free' as price. In the backend product list as well as in the frontend.
Only when I set a sale price too I get the "from" price and the sale price correctly.
![screen shot 2015-01-19 at 14 46 10](https://cloud.githubusercontent.com/assets/6388819/5801317/fa157db2-9fe9-11e4-8909-e62728e93041.png)

**Comment by mikejolley** [comment]
Fixed in master.
