### ISSUE TITLE
Cart page: Changing the amount is not working

### ISSUE THREAD

**Issue by colibriinteractive** [woothemes/woocommerce#7156]
When I enter a new amount for a product and click on the "update cart" button the amount is not changed and the price gets not recalculated.

**Comment by mikejolley** [comment]
For this and #7155, please rule out conflicts with your theme and ensure the cart page is not cached. We are not able to reproduce this issue our side.

**Comment by colibriinteractive** [comment]
I get this issue with my theme and the 2015 default WP theme. Do you have a "testtheme" I can use to determine which issues come from my theme and which are bugs of WC 2.3? 
Both issues do not appear with WC 2.2

**Comment by mikejolley** [comment]
use Twenty Twelve to test. Thats my testing theme anyway. Remember to check caching too, as well as other installed plugins.

**Comment by colibriinteractive** [comment]
Thanks and sorry for the false alarm.
Works with 2012 and with my theme now. 
WPML WooCommerce Multilingual v3.4.3 is causing the issue. Updating to v3.4.4b fixes the issue.
