### ISSUE TITLE
Untranslated Lines

### ISSUE THREAD

**Issue by n13s013** [woothemes/woocommerce#7157]
![trans](https://cloud.githubusercontent.com/assets/6414831/5803924/a0967112-a00a-11e4-9de8-260aa840ea8c.jpg)

**Comment by claudiosmweb** [comment]
Need to be translated on Transifex: https://www.transifex.com/projects/p/woocommerce/

**Comment by n13s013** [comment]
The first line translated but it still looks as English.
The second line not exist in the source file.

**Comment by claudiosmweb** [comment]
What WC version and language?

**Comment by n13s013** [comment]
### WordPress Environment ###

Home URL                  http://localhost/13
Site URL                  http://localhost/13
WC Version                2.3.0
WC Database Version       2.3.0
Log Directory Writable    ✔ C:\wamp\www\13/wp-content/uploads/wc-logs/
WP Version                4.1
WP Multisite              –
WP Memory Limit           40 MB - En az 64MB bellek ayarlamanızı öneririz. PHP'ye ayrılan bellek miktarını artırmak için buraya  göz atabilirsiniz.
WP Debug Mode             –
Language                  tr_TR

### Server Environment ###

Server Info               Apache/2.4.4 (Win32) PHP/5.4.16
PHP Version               5.4.16
PHP Post Max Size         999 MB
PHP Time Limit            300000
PHP Max Input Vars        1000
SUHOSIN Installed         –
MySQL Version             5.6.12
Max Upload Size           999 MB
Default Timezone is UTC   ✔
fsockopen/cURL:           ✔
SoapClient:               ✕							Sunucunuzda SOAP Client sınıfı etkin değil - SOAP kullanan bazı ağ geçidi eklentileri beklendiği gibi çalışmayabilir.
Uzak Mesaj:               ✔
Uzak Erişim:              ✔

### Server Locale ###

decimal_point:            .
thousands_sep:            yok
mon_decimal_point:        yok
mon_thousands_sep:        yok

### Active Plugins (7) ###

iThemes Security          (iThemes.com) – 4.5.10
CodeStyling Localization  (Heiko Rabe) – 1.99.30
Contact Form 7            (Takayuki Miyoshi) – 4.0.3
Twitter Widget Pro        (Aaron D. Campbell) – 2.6.0
WooCommerce               (WooThemes) – 2.3-beta-1
WooCommerce Product Archive Customiser (jameskoster) – 0.4.0
YITH WooCommerce Wishlist (Your Inspiration Themes) – 1.1.7

### Settings ###

API Enabled               ✔
Taxes Enabled             –
Shipping Enabled          ✔
Force SSL                 –
Currency                  TRY (₺)
Currency Position         left_space
Thousand Separator        ,
Decimal Separator         .
Number of Decimals        2

### WC Pages ###

Mağaza Anasayfası :       #4 - /?page_id=4
Sepet:                    #5 - /?page_id=5
Ödeme:                    #6 - /?page_id=6
Hesabım:                  #7 - /?page_id=7

### Taxonomies ###

Product Types             external (external)
                         grouped (grouped)
                         simple (simple)
                         variable (variable)


### Theme ###

Name                      Twenty Twelve
Version                   1.6
Author URL                http://wordpress.org/
Child Theme               ✕ Bir alt tema kullanmanızı öneriyoruz. Nasıl alt tema oluşturacağınızı öğrenmek için buraya göz atabilirsiniz.
WooCommerce Support       ✔

### Templates ###

Overrides                 –

**Comment by claudiosmweb** [comment]
Nothing to worry about, is 2.3 development version, not with this fully updated translation package yet.

But it seems that we need to improve support for select2 with translations.
