### ISSUE TITLE
Lot of translated strings not showing in admin area

### ISSUE THREAD

**Issue by napcok** [woothemes/woocommerce#7158]
I have almost completely translated woocommerce-admin-pl_PL.po and .mo files. But only part of translated strings are shown on admin area.
![woocommerce](https://cloud.githubusercontent.com/assets/3028270/5805555/3111829a-a010-11e4-975d-f6a6b3f8c313.png)

**Comment by claudiosmweb** [comment]
Need to be translated in http://transifex.com/projects/p/woocommerce/

Here instructions for custom translations https://github.com/woothemes/woocommerce/blob/master/i18n/languages/README.md
