### ISSUE TITLE
TypeError: a.sizes.thumbnail is undefined when adding images to product gallery

### ISSUE THREAD

**Issue by p4cm4n** [woothemes/woocommerce#7169]
When i try to add images to product gallery, the workflow seems to operate correctly (Windows closes, etc) but no images show (or be saved) in any case, the browser console shows the following error:

```
TypeError: a.sizes.thumbnail is undefined 
```
the file at which the debuggger points is meta-boxes-product.min.js

**Comment by claudiosmweb** [comment]
What WooCommerce version?

**Comment by p4cm4n** [comment]
template problem sorry :P
