### ISSUE TITLE
"Payment method" string not being translated

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#7171]
Files:
includes/shortcodes/class-wc-shortcode-checkout.php
templates/checkout/thankyou.php

The string "Payment method" is used, but on the PO files we only have "Payment Method", so of course the translation is not picked up correctly.

**Comment by claudiosmweb** [comment]
What WooCommerce Version?

**Comment by webdados** [comment]
Sorry.

Latest: 2.2.10

I've tweaked my .PO file and solved the problem, but the original strings update must be synced to transifex.

**Comment by claudiosmweb** [comment]
Is synced, but now with our master (WC 2.3).
Probably not previously had this translation available when it launched the 2.2.10.

**Comment by webdados** [comment]
So the transifex strings are synced with your dev version and not for the production one available for download?

**Comment by claudiosmweb** [comment]
This synced now with the master (2.3-beta-1), because we'll launch the new version within two weeks, we'll not have more versions of 2.2.x
