### ISSUE TITLE
Lost connection during AJAX request to woocommerce_update_order_review

### ISSUE THREAD

**Issue by dgwatkins** [woothemes/woocommerce#7176]
This happens only with the latest Safari (I'm testing with OSX Yosemite).

Steps to reproduce:
1) Install fresh WordPress + WooCommerce
2) Create automatic pages and add an example product
3) Enable SSL in Checkout (WooCommerce -> Settings)

Now you just have to add a product to the cart, head to checkout page and change the selected country (see screenshot)
![screen shot 2015-01-22 at 16 45 35](https://cloud.githubusercontent.com/assets/17052/5858880/bdb15eda-a256-11e4-912d-9e8e1a352f69.png)

**Comment by dgwatkins** [comment]
I asked several colleagues to test this before reporting and tried on 2 different servers.
Both are running Apache 2.4 (Ubuntu trusty). 
One of them has a real SSL certificate, the other one has a self-signed one. 

I can provide you with access details to our dev server, just let me know.

For what is worth: I was also unable to replicate it on my local environment.
We are also paying customers if it makes any difference.

**Comment by mikejolley** [comment]
TBH this looks more server related. On this install, have you tested it 'clean' i.e. twenty twelve theme, nothing except WC activated?

**Comment by dgwatkins** [comment]
Yes, fresh install. The steps outlined above are done from scratch.

I tried on 2 different servers, but both Ubuntu trusty with Apache 2.4 (I think its a very common configuration). Do you have a SSL demo available where I can test?

On a side note, this is preventing some of our customers from shopping.

**Comment by mikejolley** [comment]
Your screenshots are not from Twenty Twelve...

My tests are local. This also hasn't come up before from what I can see. Checked your server error logs?

**Comment by dgwatkins** [comment]
It's twentythirteen, yes.
I'm sorry, let me repeat the tests with twentytwelve and I will post back.

**Comment by mikejolley** [comment]
Find anything?

**Comment by dgwatkins** [comment]
same symptoms

**Comment by mikejolley** [comment]
http://stackoverflow.com/questions/4390134/failed-to-load-resource-under-chrome

**Comment by mikejolley** [comment]
^ some ideas there.

**Comment by mikejolley** [comment]
Also try that commit - it will output info about the error in your console. Still think its server related.

**Comment by dgwatkins** [comment]
I have tested without extensions on Safari and it still happens.
Let me try that commit. Thanks.

**Comment by dgwatkins** [comment]
There is nothing different in the error console after testing with master.
The error comes up very quickly, as if its not even reaching the server.

**Comment by mikejolley** [comment]
You need to enable WP_DEBUG for that console notice to be logged. http://codex.wordpress.org/WP_DEBUG

**Comment by dgwatkins** [comment]
Hang on, I need to enable SCRIPT_DEBUG ... 
nope, still the same
![screen shot 2015-01-26 at 16 16 01](https://cloud.githubusercontent.com/assets/17052/5901964/d9213c12-a576-11e4-9108-bad1c3f70d55.png)

**Comment by dgwatkins** [comment]
We posted almost at the same time.
I left you feedback there, I'm still looking into this issue myself.
I also suspect server problem but havent pinned it yet.
Any ideas are welcome.

Thanks so far
David

**Comment by dgwatkins** [comment]
Just a short update on my little progress here:

It looks as if the request doesn't even leave the browser.
It fails straight away after changing the country, with no network traffic and no log entries in the server.

This looks very similar to what I'm experiencing:
https://discussions.apple.com/thread/6761633

**Comment by dgwatkins** [comment]
I think I found the reason in virtualhost configuration.

Any different than "SSLProtocol all" is making Safari fail.

I will confirm during the day and close here.
Thanks for all the help, tips, etc

**Comment by mikejolley** [comment]
Good to hear you've making progress. Sorry I haven't had time to look yet, I've had my hands full with 2.3

**Comment by dgwatkins** [comment]
Just in case someone else runs into this strange problem, let me share an update.
We have been having this issue up until a couple of hours ago that I disabled KeepAlive on Apache.
It has been the only way to get the latest version of Safari to do a checkout on any of our SSL servers.

**Comment by kainjow** [comment]
I am seeing the exact same issue, and our server is also Ubuntu 14.04.2 (Apache 2.4). Seeing this on Safari 8.0.4. I can confirm through phpinfo() that HTTP_CONNECTION is set to keep-alive.

@dgwatkins has the disabling of KeepAlive continued to be a solution for you?

According to this thread, it's an underlying OS X/iOS networking implementation bug:
https://github.com/AFNetworking/AFNetworking/issues/2314

**Comment by kainjow** [comment]
Forgot to mention, we are also seeing an issue with the /login/ WordPress page where when you go to submit the form, Safari instantly dies with "Safari can't open the page /login/ because the server unexpectedly dropped the connection" - this sounds like yet another symptom of the same problem.

**Comment by kainjow** [comment]
Seems like turning off KeepAlive is the solution. However since I don't have access to our server's apache config file, I was able to put this in the .htaccess file:

    BrowserMatch "Safari" nokeepalive

With my initial testing this seems to resolve the issue. I confirmed in Safari that the HTTP Connection is Close while in Chrome it's Keep-Alive.

Since testing the /login/ page is the easiest, I cannot reproduce anymore, but if I disable that line, then Safari > Clear History and Website Data and relaunch Safari, I can reproduce again.

Thanks @dgwatkins for the tips!

**Comment by dgwatkins** [comment]
Hi Kainjow, yes, this is still a solution for us.

**Comment by kainjow** [comment]
FWIW, I still see this issue. On all of our production sites, we have KeepAlive disabled for Safari which resolves it. For some internal sites that use SSL I see this very often, even though we don't have KeepAlive for those.

I found this issue which made me realize all the sites I've reproduced this issue on used mpm-itk, so maybe that's the other import key:
https://lists.err.no/pipermail/mpm-itk/2015-August/000889.html

**Comment by kainjow** [comment]
Our .htaccess file now looks like this:

    BrowserMatch "Safari" nokeepalive
    BrowserMatch "AppleWebKit" nokeepalive
    BrowserMatch "CFNetwork" nokeepalive

because we have the same problem with WebKit controls and raw NSURLConnection. Fortunately we are moving to nginx soonish so this will no longer be a problem.

**Comment by hmoffatt** [comment]
Is this still known to be an issue with iOS 9 and 10?

**Comment by JefferE** [comment]
I'm having this problem right now and its preventing me from leaving on vacation...

Trying to access our HTTPS site on Apache 2.4.7 on Ubuntu 14.04 LTS

Works on iPhone 5; iOS 10.2.1  on Wifi and Verizon cellular

Works on iPhone 6; iOS 10.2.1  on Wifi **but not** on ATT cellular

Tried all the setting changes that are in this thread. Any other suggestions?
