### ISSUE TITLE
add_to_cart shortcode override

### ISSUE THREAD

**Issue by cyrildc** [woothemes/woocommerce#7177]
Hi,

Is there a way to override the add_to_cart shortcode ?
I don't see any filter...

Thanks

**Comment by mikejolley** [comment]
There is no filter for the output of this shortcode. If you need something different, make your own shortcode based on this one with a different name, or remove it and add one in its place.

http://codex.wordpress.org/Function_Reference/add_shortcode

**Comment by claudiosmweb** [comment]
For remove http://codex.wordpress.org/Function_Reference/remove_shortcode ;)
