### ISSUE TITLE
404 Issues when My Account page is a child of main Store page

### ISSUE THREAD

**Issue by beckyresler** [woothemes/woocommerce#7178]
I am in the middle of setting up a store for a client where I want the structure of the WooCommerce pages to be as follows ...

* Store => store
  * Cart => store/cart
  * Checkout => store/checkout
  * My Account => store/my-account

The reason I want to do this is because the store is only a small portion of the website that is generally only utilized by employees of the client, and I want to keep the site as uncluttered and un-confusing as possible.

I have the permalinks for WordPress and WooCommerce set up as follows ...

* WordPress permalink => Day and name (i.e. /%year%/%monthnum%/%day%/%postname%/ )
* Product category base => store/category
* Product tag base => store/tag
* Product permalink base => Shop base with category (i.e. store/%product_cat%)

With this setup, the store pages, the shopping cart, and the checkout page all function properly. However, when I place an order, the confirmation page results in a 404. The account pages to edit an account, change a password, etc also result in a 404 page as does the "forgot password" page if a user isn't logged in.

To ensure that none of the plugins on the site were causing issues, I set up a test site (in my local development environment) with a fresh install of WordPress with no plugins and the 2014 theme. I installed WooCommerce and set up a couple products so that I could test things. I left all of the WooCommerce pages as top level pages, which is where WooCommerce creates them. The only change I made was to change the permalink for the main Store page from "shop" to "store".

When I placed an order, the confirmation page displayed for me as did the order details. All of the other pages that gave me a 404 before now load successfully.

To test my theory, I made the **My Account** page a child of the main Store page [and made sure the Permalinks were updated]. This resulted in the order details and other account related pages giving me a 404 page again.

Is my setup causing some sort of permalink conflict or is it just not possible to make the **My Account** page a child of another page?

**Comment by beckyresler** [comment]
After doing some additional debugging, it appears that my problems stem from my **Product permalink base**. I have changed that to "Shop base" (i.e. store). After doing this, my order detail and other account related pages are loading. The rest of my store appears to be functioning properly as well. I just don't have the URL structure that I wanted. But for this particular case, having the simpler URLs should be just fine.

**Comment by serdarozbilen** [comment]
You solved my problem. Thank you :)

**Comment by serdarozbilen** [comment]
You solved my problem. Thank you :)
