### ISSUE TITLE
Anonymous function in emogrifier.php

### ISSUE THREAD

**Issue by mharis** [woothemes/woocommerce#7179]
Localhost on PHP 5.2 and Woocommerce 2.3 beta checkout from repo.

Error under Woocommerce Email tab and after ajax checkout call:

"Parse error: syntax error, unexpected T_FUNCTION in woocommercer/includes/libraries/class-emogrifier.php on line 255"

Issue: anonymous functions are not supported on minimum requirements of WordPress / Woocommece

               $normalizedOriginalStyle = preg_replace_callback(
                    '/[A-z\\-]+(?=\\:)/S',
                    function (array $m) {
                        return strtolower($m[0]);
                    },
                    $node->getAttribute('style')
                );

**Comment by jconroy** [comment]
Just confirming that I also get the same error when simply attempting to view the email tab with PHP 5.2.17 / WooCommerce 2.3.0-beta-1 / WordPress 4.1. No other plugins activated or installed.

---

Additional warnings I also see:

```
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /woo/wp-content/plugins/woocommerce/includes/libraries/class-emogrifier.php on line 180
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /woo/wp-content/plugins/woocommerce/includes/libraries/class-emogrifier.php on line 237
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /woo/wp-content/plugins/woocommerce/includes/libraries/class-emogrifier.php on line 241
```
