### ISSUE TITLE
Calculating cart totals always invalidates the session even when unchanged

### ISSUE THREAD

**Issue by deltafactory** [woothemes/woocommerce#7182]
Due to the complex nature of `WC_Cart::calculate_totals()` this is probably a very difficult fix.

This function calls the following functions:
* `WC_Cart::reset()` clears out the cart's session data.
* `WC_Cart::set_session()` sets the recalculated totals.

What are the blockers to avoiding the `reset()` and only call `set_session()` if the result is different from the existing state? As it stands, any call to `calculate_totals()` invalidates the cached version of the session.

Because of the use of `reset()`, the separate optimization to only make a `WC_Session->set()` when the value is different will fail for non-empty carts, since it's being zeroed and reset.

**Comment by deltafactory** [comment]
FYI @heydonovan, since you were interested in session performance concerns.

**Comment by mikejolley** [comment]
That should help.

The session data isn't cleared before calculation, just the local cart data. If after the calculation the data is unchanged, the session class set method won't dirty the session.

Reset will clear session data if emptying the cart.

**Comment by deltafactory** [comment]
I'm not following the patch. I think I see where you're going but the execution path doesn't look like any different with regard to dirtying the session via the `unset()`.

**Comment by mikejolley** [comment]
Derp, missing a line. Lemme change it when I get back. The unset needs to be based on the passed in arg
