### ISSUE TITLE
Localisation issue

### ISSUE THREAD

**Issue by ashmatadeen** [woothemes/woocommerce#7189]
With language set to English (United States), the built in Wordpress Featured Image metabox title in the admin screen is renamed to "Product Image" for the product custom post type but not for any other existing post types. This is the expected behaviour.

Change the  language to English (UK), however and WooCommerce updates the title for the Featured Image metabox to "Product Image" for ALL custom post types. This should only happen for the product custom post type or at the very least for all post types that belong to WooCommerce.

**Comment by claudiosmweb** [comment]
Fixed in WC 2.3.

**Comment by ashmatadeen** [comment]
thanks @claudiosmweb
