### ISSUE TITLE
(2.3) All VAT / invoice related problems are solved in 2.3 (shipping / discounts / refunds)? Details inside

### ISSUE THREAD

**Issue by RicaNeaga** [woothemes/woocommerce#7190]
Hello!

I've opened a ticket some time ago, however you've closed it, due to my lack of providing additional info. Sorry for that, and here is (I hope) a comprehensive explanation of my previous ticket ( https://github.com/woothemes/woocommerce/issues/6541 ), that was about how there were some legal issues in my contry (Romania - EU member) regarding how VAT was applied and how some elements should appear on the invoice.

A.  VAT must be applied to discounts, the same as with the shipping, and both should be found on the invoice the same as regular products. Here is a simple example (discount has the same value as the shipping costs):

![woo1](https://cloud.githubusercontent.com/assets/1704092/5875593/94915d9a-a317-11e4-888d-a6425eee219a.png)

Will you have in woocommerce 2.3 the needed hooks so an invoice plugin would display those elements in the above described manner?

B. Refunds are shown on the invoice as ''storno'' - that means showing either the invoice that is refunded, either the product, with its exact value with - in front (negative value).

See below an example, soory it's in romanian, but this time things are simpler than at the above point.

![woo2](https://cloud.githubusercontent.com/assets/1704092/5875678/84a7c418-a318-11e4-9379-20136fc15c2f.gif)

Again, do you have the needed hooks in woo 2.3 so an advanced invoice plugin would diplay that invoice in a similar manner?

Thank you again, and sorry if I made a mistake by tagging this issue as woocommerce 2.3 related, but I consider it rather urgent since its a legal / accounting issue, so I'm hoping you'd consider solving it asap :)

**Comment by Sounddesigner** [comment]
Great you're giving it a try. Gave up on this issue a while ago.

**Comment by mikejolley** [comment]
I think it might be a good idea to get a Romanian developer to look at this for you - if they know what they are doing they can request anything new required to implement this. We cannot change the default behaviour for this one jurisdiction.

I will use your above example and show you how its handled in 2.3 anyway. Note - I've set prices excl. vat for this example.

## Cart Display
https://dl.dropboxusercontent.com/s/wq4zyb89evstld3/2015-01-23%20at%2014.15%202x.png?dl=0

## Order Display
https://dl.dropboxusercontent.com/s/dlhpyoxdmrgkthx/2015-01-23%20at%2014.17%202x.png?dl=0

## WooCommerce Print Invoice & Delivery Note Plugin
https://dl.dropboxusercontent.com/s/il15gr3ao9ybqax/2015-01-23%20at%2014.20%202x.png?dl=0

The main problem with your request is the discount row. In WC 2.3, discounts are applied before taxes, applied to cart items, and are split between all items in the cart. 

That said, it should be possible to format like it is in your example by summing all discounts (from the lines) for both the vat and the cost. e.g. line total - line subtotal = discount, and line tax total - line subtotal tax total = discount tax

Hope that helps.

**Comment by RicaNeaga** [comment]
Thank you for your reply. So it's possible somehow to show both the discount total, and also the VAT value for the discount?

Also, it's possible to show negative values on the invoice? I mean woocommerce allows this (hooks, other code etc)?

Thanks again :)

**Comment by mikejolley** [comment]
See my note how how to calculate the totals - once you have that you should be able to display it however you want on an invoice.

**Comment by RicaNeaga** [comment]
Ok, thank you very much. Since everything ''is there'' codewise, I'll talk to a developer. However, I first wanted to make sure that no changes are needed to the woocommerce ''core'' functionalities, for my above requests to be shown on the invoice exactly in that manner.

Oh... and good luck with the 2.3 launch! Hope no big bugs arise right after the launch. I'm also going to test the RC once it's out and be back with any issue I encounter ;)
