### ISSUE TITLE
Variable Products now showing as 'Free' in WC 2.3 Beta-1?

### ISSUE THREAD

**Issue by rossagrant** [woothemes/woocommerce#7193]
Hi guys!

Wanted to run this passed you.

I'm about to launch a site and have installed WC 2.3 beta-1 to be totally up to date.

All works great EXCEPT my variable products show a price of 'Free' in BOTH the backend 'products' summary tab and on the front end too.

I thought it would be a theme issue, but doubt that would affect the backend of WC too?

If I actually add a 'Free' product to my basket, it shows the correct price and I can checkout just fine.

The issue is that it's just showing 'Free' initially in archive and single product view.

If I add a sale price, that shows just fine, but a regular one doesn't.

I'm not using any currency symbols or anything like that - just a regular number where you set the price in each variable.

Could someone let me know if this is the beta version with a bug or still maybe my theme?

Thanks so much!

Ross :)

**Comment by mikejolley** [comment]
Will be resolved in beta 2
