### ISSUE TITLE
add_theme_support still producing error

### ISSUE THREAD

**Issue by dovy** [woothemes/woocommerce#7196]
With the newest code in this repo, my theme admin is suddenly producing this alert:

![screen shot on 2015-01-23 at 10-26-21](https://cloud.githubusercontent.com/assets/890963/5877706/be4a6520-a2de-11e4-9755-939a327b798d.png)

I have add_theme_support('woocommerce') properly set, but it still isn't functioning as expected.

**Comment by slash1andy** [comment]
https://github.com/woothemes/storefront/issues/108

I logged this in the Storefront repo, as it looked to be an issue there, but it seems that it's a WooCommerce issue.

**Comment by dovy** [comment]
@slash1andy Glad we're not the only ones.  ;)

**Comment by jameskoster** [comment]
So is this fixed or not? I was unable to replicate.

**Comment by claudiosmweb** [comment]
@jameskoster fixed now.

**Comment by jameskoster** [comment]
:shrek:
