### ISSUE TITLE
Shipping option on Checkout Page not Styled

### ISSUE THREAD

**Issue by dovy** [woothemes/woocommerce#7197]
With the code in this repo (from yesterday) it looks like when you check the box to ship to another place than the billing address, the country select styling isn't being initialized.

It only applies to the billing country, not shipping as well.

**Comment by slash1andy** [comment]
That sounds more like a theme issue. Have you tried it on another theme like storefront or 2012? I am running latest Storefront and latest WooCommerce, and it seems to look fine.

**Comment by claudiosmweb** [comment]
Show an example.

**Comment by claudiosmweb** [comment]
@dovy ?

**Comment by claudiosmweb** [comment]
Works fine:

![screenshot from 2015-01-26 10 38 43](https://cloud.githubusercontent.com/assets/1264099/5899740/85873a7c-a547-11e4-851d-360a68776619.png)

**Comment by dovy** [comment]
My bad. Thanks.
