### ISSUE TITLE
Product Category Disappeared 

### ISSUE THREAD

**Issue by mradjoy** [woothemes/woocommerce#7199]
Hi, 
I hope someone can help me find a solution to my problems caused by woocommerce or something else on my website, http://retailtherapyonline.com, I have the latest version of woocommerce installed and it's been working fine until few days ago when I discovered that the product categories were not displaying anymore.

From the backend going to product category link it only shows the pagination of all the various categories we have but without showing the categories itself, from the frontend the category menus are there but clicking on it will not display products under this category, saying 'No products were found matching your selection'.
At first, I thought it's database issue so I deleted the current database and re-import from the backup, but still did not change anything.

Now, what I noticed about this issue again is that even when I tried to create a new menu where all there menu links goes it says menu already exist and also creating a new product category with the same name wouldn't work either saying  'The slug “women” is already in use by another term'.

What all of these simply tells me is that we still have these things in the database, but where are they hiding?
Please I'd appreciate your help to get me out of this mess that I have been with for 2 days now.

Thank you.

Adeyemi

=====================System Report===================

### Environment ###

Home URL:                http://retailtherapyonline.com
Site URL:                http://retailtherapyonline.com
WC Version:              2.2.10
WC Database Version:     2.2.10
WP Version:              4.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips DAV/2 mod_bwlimited/1.4
PHP Version:             5.4.36
MySQL Version:           5.5.40
WP Active Plugins:       45
WP Memory Limit:         128 MB
WP Debug Mode:           No
WP Language:             en_US
WP Max Upload Size:      2 MB
PHP Post Max Size:       8 MB
PHP Time Limit:          300
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
WC Logging:              Log directory (/home/retailth/public_html/wc-logs/) is writable.
Default Timezone:        Default timezone is UTC
fsockopen/cURL:          Your server has fsockopen and cURL enabled.
SOAP Client:             Your server has the SOAP Client class enabled.
WP Remote Post:          wp_remote_post() was successful - PayPal IPN is working.

### Locale ###

decimal_point:           .
thousands_sep:           N/A
mon_decimal_point:       N/A
mon_thousands_sep:       N/A

### Plugins ###

Installed Plugins:       Advanced Custom Fields: Gallery Field by Elliot Condon version 1.1.1
                         Advanced Custom Fields: Repeater Field by Elliot Condon version 1.1.1
                         Advanced Code Editor by BaInternet version 2.2.6
                         Advanced Custom Fields by Elliot Condon version 4.3.9
                         All In One WP Security by Tips and Tricks HQ
                         Peter
                         Ruhul
                         Ivy version v3.8.9
                         Ninja Popups Themes Pack by ARSCode version 1.4
                         Ninja Popups by ArsCode version 3.5
                         Brankic Photostream Widget by Brankic1979 version 1.3
                         Contact Form 7 by Takayuki Miyoshi version 4.0.3
                         Envato WordPress Toolkit by Envato version 1.7.1
                         GetKudos Widget by Zopim version 0.0.1
                         WooCommerce GTPay Gateway by Oluwarufus version 1.0.4
                         WooCommerce Quickview by James Kemp version 3.0.7
                         jQuery Mega Menu by Lee Chestnutt version 1.3.10
                         WPBakery Visual Composer by Michael M - WPBakery.com version 4.3.4
                         Live Chats by Chudesnet version 1.2.4
                         MPC Extensions by MassivePixelCreation version 2.0.5
                         MPC Shortcodes by MassivePixelCreation version 2.0
                         MPC Widgets by MassivePixelCreation version 1.2.3
                         PayPal Currency Converter PRO for WooCommerce by Intelligent-IT.asia version 1.5
                         Revolution Slider by ThemePunch version 4.6.3
                         Shortcodes Ultimate by Vladimir Anokhin version 4.9.3
                         Smart Manager for e-Commerce by Store Apps version 3.9.2
                         Smart Refunder by Store Apps version 1.4
                         Smart Reporter for e-commerce by Store Apps version 2.7.3
                         Subscribe2 by Matthew Robinson
                         Tanay Lakhani version 10.18.2
                         Visitor Maps and Who's Online by Mike Challis version 1.5.8.6
                         VoguePay Payment Gateway For WooCommerce by VoguePay version 1.2.3
                         White Label Branding for WordPress by Alberto Lau (RightHere LLC) version 3.3.1.54694
                         WooCommerce Multi Vendors by Themology version 1.0.0
                         WooCommerce Customer Relationship Manager by Actuality Extensions version 2.5.5
                         WooCommerce Print Invoice & Delivery Note by Triggvy Gunderson version 4.0.2
                         WooCommerce Nigeria States by Alexander Asomba version 1.0.1
                         WooCommerce PDF Invoices & Packing Slips by Ewout Fernhout version 1.5.2
                         WooCommerce Pretty Emails by MB Création version 1.4
                         WooCommerce Sequential Order Numbers by SkyVerge version 1.3.4
                         WooCommerce Sold Out Products by Gerhard Potgieter version 1.0.4
                         WooCommerce by WooThemes version 2.2.10
                         WooDojo by WooThemes version 1.5.4
                         WooSidebars by WooThemes version 1.3.1
                         WordPress Importer by wordpressdotorg version 0.6.1
                         WordPress SEO by Team Yoast version 1.7.1
                         WP Smush.it by WPMU DEV version 1.7
                         YITH WooCommerce Ajax Navigation by Your Inspiration Themes version 1.4.1
                         YITH WooCommerce Wishlist by Your Inspiration Themes version 1.1.7

### Settings ###

Force SSL:               No

### WC Pages ###

Shop Base:               #6 - /shop/
Cart:                    #7 - /cart/
Checkout:                #8 - /checkout/
My Account:              #9 - /my-account/

### WC Taxonomies ###

Product Types:           

### Theme ###

Theme Name:              rtoltd-child
Theme Version:           1.0
Theme Author URL:        http://retailtherapyonloine.com
Is Child Theme:          Yes
Parent Theme Name:       rtoltd
Parent Theme Version:    2.0.6
Parent Theme Author URL: http://retailtherapyonloine.com
WooCommerce Support:     Yes

### Templates ###

Template Overrides (WooCommerce):rtoltd/woocommerce/archive-product.php
                         rtoltd/woocommerce/cart/cart-empty.php
                         rtoltd/woocommerce/cart/cart-shipping.php
                         rtoltd/woocommerce/cart/cart-totals.php
                         rtoltd/woocommerce/cart/cart.php
                         rtoltd/woocommerce/cart/cross-sells.php
                         rtoltd/woocommerce/cart/mini-cart.php
                         rtoltd/woocommerce/cart/shipping-calculator.php
                         rtoltd/woocommerce/checkout/form-billing.php
                         rtoltd/woocommerce/checkout/form-checkout.php
                         rtoltd/woocommerce/checkout/form-shipping.php
                         rtoltd/woocommerce/content-product.php
                         rtoltd/woocommerce/content-product_cat.php
                         rtoltd/woocommerce/content-single-product.php
                         rtoltd-child/woocommerce/emails/admin-new-order.php
                         rtoltd-child/woocommerce/emails/customer-completed-order.php
                         rtoltd-child/woocommerce/emails/customer-invoice.php
                         rtoltd-child/woocommerce/emails/customer-new-account.php
                         rtoltd-child/woocommerce/emails/customer-note.php
                         rtoltd-child/woocommerce/emails/customer-processing-order.php
                         rtoltd-child/woocommerce/emails/customer-reset-password.php
                         rtoltd-child/woocommerce/emails/plain/admin-new-order.php
                         rtoltd-child/woocommerce/emails/plain/customer-completed-order.php
                         rtoltd-child/woocommerce/emails/plain/customer-invoice.php
                         rtoltd-child/woocommerce/emails/plain/customer-new-account.php
                         rtoltd-child/woocommerce/emails/plain/customer-note.php
                         rtoltd-child/woocommerce/emails/plain/customer-processing-order.php
                         rtoltd-child/woocommerce/emails/plain/customer-reset-password.php
                         rtoltd/woocommerce/loop/add-to-cart.php
                         rtoltd/woocommerce/loop/loop-end.php
                         rtoltd/woocommerce/loop/loop-start.php
                         rtoltd/woocommerce/loop/no-products-found.php
                         rtoltd/woocommerce/loop/pagination.php
                         rtoltd/woocommerce/loop/result-count.php
                         rtoltd/woocommerce/loop/sale-flash.php
                         rtoltd/woocommerce/myaccount/form-add-payment-method.php
                         rtoltd/woocommerce/myaccount/form-edit-address.php
                         rtoltd/woocommerce/myaccount/form-login.php
                         rtoltd/woocommerce/myaccount/my-address.php
                         rtoltd/woocommerce/myaccount/my-orders.php
                         rtoltd/woocommerce/notices/error.php
                         rtoltd/woocommerce/notices/notice.php
                         rtoltd/woocommerce/notices/success.php
                         rtoltd/woocommerce/order/order-details.php
                         rtoltd/woocommerce/order/tracking.php
                         rtoltd/woocommerce/single-product/add-to-cart/variable.php
                         rtoltd/woocommerce/single-product/meta.php
                         rtoltd/woocommerce/single-product/product-image.php
                         rtoltd/woocommerce/single-product/product-thumbnails.php
                         rtoltd/woocommerce/single-product/related.php
                         rtoltd/woocommerce/single-product/review.php
                         rtoltd/woocommerce/single-product/sale-flash.php
                         rtoltd/woocommerce/single-product/tabs/additional-information.php
                         rtoltd/woocommerce/single-product/tabs/description.php
                         rtoltd/woocommerce/single-product/tabs/tabs.php
                         rtoltd/woocommerce/single-product/up-sells.php
                         rtoltd/woocommerce/single-product-reviews.php

**Comment by roykho** [comment]
Hello,

So this is really not the place for you to ask for help but rather a place to report bugs/fixes.  I suggest you open up a ticket with us on your issue so that it can be properly handled.

**Comment by mradjoy** [comment]
oh I am sorry for that, opened a support ticket with woocommerce.

Thanks
