### ISSUE TITLE
Two 500€ purchases set total to 10k€

### ISSUE THREAD

**Issue by Gjordis** [woothemes/woocommerce#7203]
I have a test product which costs 500€. I have 2 of them in stock. If I add them to my car :  

First i get cart at 500€ after adding the first,
and after adding the second one, the cart is at 10000€. 

This goes all the way to orders and billings. Its not just an UI-clitch.
![2x500is10k](https://cloud.githubusercontent.com/assets/1763799/5888800/f8694842-a415-11e4-89ec-da62d3bd0c82.png)

I have not been able to reproduce this on any other price, but it happens every time with this price, even on different products.

Woocommerce : Version 2.2.10 
WordPress 4.1

**Comment by claudiosmweb** [comment]
I can't reproduce this error.
Maybe you are wrong set the decimal numbers. Maybe you're wrong using the "Decimal Separator" or some plugin this your changing that.

**Comment by Gjordis** [comment]
Ok, i found the issue when i was trying to confirm if it was about the seperator.
I was using a space as a decimal seperator, according to finnish locale, but on last update(or something), it had reseted as a 0, these 500 prices, were the only ones I tested with, that went over 1k. Apparrently space is not allowed as a seperator, form validation propably considers it as an empty value and fallbacks to 0 or last value set.(didn't check code.)

**Comment by claudiosmweb** [comment]
I can confirm that in WooCommerce 2.3, space as decimal separator works fine.

**Comment by Gjordis** [comment]
OK, it had reseted to zero for me, and now it wont accept any values... First loads as the set value, then shows the 0 again and then when i see settings again, it shows as empty, no matter what i set it as. Something broken on my shop apparrently.
