### ISSUE TITLE
Apigen on Windows issue via Grunt task

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#7204]
Using Apigen.phar for Windows system results issue with `grunt docs` have a look to below screenshot but if command `apigen generate` is used no issue.;)

![error](https://cloud.githubusercontent.com/assets/3774827/5889935/f8f697ae-a467-11e4-971d-d65c015312fb.png)

**Comment by claudiosmweb** [comment]
These commands are for our development.
But good luck with Windows.
