### ISSUE TITLE
Rounding with Shipping

### ISSUE THREAD

**Issue by arma77** [woothemes/woocommerce#7205]
Hi,

i need to present 9,80 (EUR) including 19% VAT as shipping.
I've put 8.2352941176 as gross-shipping. VAT is set to 19 percent. But i cant manage to get 9,80€. It only shows either 9.79 or 9.81, when playing around with numbers.

Something is strange with rounding...

Any Clues?

**Comment by mikejolley** [comment]
Nothing strange with rounding, you just cannot have half a cent. 8.24 * 1.19 is 9.81. Shipping costs are rounded. Keep an eye on https://trello.com/c/cjHijcxy/19-shipping-inc-tax-prices-4425
