### ISSUE TITLE
Submenu disappears when WooCommerce is activated

### ISSUE THREAD

**Issue by bayadwa** [woothemes/woocommerce#7206]
I tried uninstalling all my plugins, but my submenu disappears only when woocommerce is installed and active.

Can anyone help?

**Comment by claudiosmweb** [comment]
Submenu where? Admin? Frontend? Tried to changed the theme? Really tried to disable all plugins?

**Comment by claudiosmweb** [comment]
If you still have this problem let me know that we open again.

**Comment by bayadwa** [comment]
The problem is with the theme's slider.  Woocommerce causes my slider to not work and my menu's sub menu not to work.

What is the issue?

i deactivated all the plugins and woocommerce is the problem.

**Comment by bayadwa** [comment]
I am very happy to say, I fixed the problem.

I found another plugin 

jQuery Updater and that updated to the latest jquery and it fixed everything. Thanks
