### ISSUE TITLE
Updating orders not working via REST API v2

### ISSUE THREAD

**Issue by pompa** [woothemes/woocommerce#7207]
Sending an update (PUT) command for an order using the REST API v2 returns a 200 response but none of the values are changed. However, using the same API call but changing the version of the endpoint to v1 works.

Example:
curl -X PUT -H "Authorization: Basic <auth hash>" -H "Content-Type: application/json" -d '{"status":"completed"}' http://www.example.com/wc-api/v2/orders/<order no>

The curl command above returns 200 but the values are not changed at all. If I change the versioning of the endpoint, it returns 200 as well, but the response body has the correct output:

curl -X PUT -H "Authorization: Basic <auth hash>" -H "Content-Type: application/json" -d '{"status":"completed"}' http://www.example.com/wc-api/v1/orders/<order no>

**Comment by claudiosmweb** [comment]
Works only in v2 and you need to write the JSON right!

```shell
curl -X PUT -H "Authorization: Basic " -H "Content-Type: application/json" -d '{"order": {"status":"completed"}}' http://www.example.com/wc-api/v2/orders/
```

**Comment by pompa** [comment]
Ah. Make sense. Thanks.

**Comment by maxrice** [comment]
@pompa you can do this in the v1 with:

`curl -X PUT -H "Authorization: Basic " -H "Content-Type: application/json" -d '{"status":"completed"}' http://www.example.com/wc-api/v1/orders/`

If it's returning 200 but the data isn't updated, it's likely due to a plugin conflict on your site. Try deactivating everything but WooCommerce and if it works properly then, it's an issue with one of the other plugins :)

**Comment by NickDomanti** [comment]
I deactivated every plugin but WooCommerce, but still, can't update order status, not in v1 nor v2 nor v3

**Comment by altunyurt** [comment]
In my case, we were redirecting www.example.com -> example.com and nothing i've tried via 
``` curl -X PUT www.example.com/ ... {'status': 'completed'} ```
was working. Trying without the www worked. 

I'm using the python api and apparently it has the same problem, not following the redirects, so it fails silently but works with direct requests as well.
