### ISSUE TITLE
Not processing automatically orders that are paid with paypal

### ISSUE THREAD

**Issue by PatrikMedia** [woothemes/woocommerce#7209]
The orders that my clients pay with paypal, are not processed automatically from Payment pending to Processing,  I have to do it manually. Any idea on how I can solve this? 

Thanks very much.

**Comment by mikejolley** [comment]
See http://docs.woothemes.com/document/paypal-standard/ "Debugging IPN issues"

You can also enable PDT which is a setting in the gateway. This transfers payment details as the user returns.

Closing as this isn't a bug, just a server/config issue.
