### ISSUE TITLE
Change Variable Product back to Simple Product leaves "_min_price_variation_id" populated in database

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#7211]
Just working with a plugin that uses:

`$variation_id = get_post_meta( $product->id, '_min_price_variation_id', true );`

To detect if the product is a variation, however, if a product __was__ a variable product, but has since been change to a simple product, `_min_price_variation_id` in the database remains populated & shows up in the list of variable products.

Is this bad practise for the plugin, or something that should change in the core?

**Comment by claudiosmweb** [comment]
> To detect if the product is a variation
Don't do that!

You need to really check the product type.

We can't delete the variation data, because the user may have made a mistake and try to make a change again, he'll have lost everything.
