### ISSUE TITLE
[2.3] Media Dialog doesn't work

### ISSUE THREAD

**Issue by lmartins** [woothemes/woocommerce#7212]
Since I installed 2.3 Beta 1 on my dev setup I've started getting an error on the top of the page:
```
Warning: array_key_exists() expects parameter 2 to be array, boolean given in /Users/luismartins/Sites/webipack.dev/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-notices.php on line 167
```
And besides that i've noticed that none of the media attachment dialogs work. The "Add Media" to TinyMCE simply does nothing and the Featured Image selector opens with the follow presentation:
![screen shot 2015-01-26 at 14 21 35](https://cloud.githubusercontent.com/assets/151981/5901042/fe225df8-a566-11e4-8da8-206d5e981fb6.png)

Not really sure what's going on but im guessing these issues are related to 2.3

**Comment by mikejolley** [comment]
Fixed in beta 2

**Comment by lmartins** [comment]
Hi Mike, that was quick.
Is the Beta 2 available anywhere? Not finding it in releases...

**Comment by mikejolley** [comment]
Will be tagged in a few hours.

**Comment by lmartins** [comment]
Cool, thanks.

**Comment by lmartins** [comment]
Just tried the Beta 2 tag, the error message is gone but the gallery still opens with that weird presentation. The button to add media to TinyMCE still doesn't do anything either (only in products).

Im getting a lot of JS errors in the console, probably related to this:
![screen shot 2015-01-26 at 15 48 31](https://cloud.githubusercontent.com/assets/151981/5902494/de9487fc-a572-11e4-8807-50a77f57276a.png)

**Comment by mikejolley** [comment]
Subscriptions needs an update for 2.3 - ajaxChosen related
