### ISSUE TITLE
Remind Users to Review WooCommerce on WordPress.org

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce#7213]
It would be great to remind customers to review WooCommerce. I was talking to some developers at PressNomics and they mentioned that they had a huge increase in the number of reviews they got when they put a reminder in the admin. Here's an example:

![forms_ _nf_2_8_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/5904858/e7541fda-a548-11e4-81b7-bd2689b12e19.png)

They hooked into the default `Thank you for creating with WordPress.` message in the footer and they only put it on their own admin pages.

Since we're replacing the default footer message we aren't adding much to the admin and I think it could help get more reviews. Thoughts?

**Comment by claudiosmweb** [comment]
+1

**Comment by greguly** [comment]
+1

**Comment by BFTrick** [comment]
@claudiosmweb I see you added the 2.4 milestone. I'd like to get this in earlier and it's a pretty small change. Can I submit a PR today so it can get in before the 2.3 RC-1?

**Comment by claudiosmweb** [comment]
@BFTrick yes, please :)
