### ISSUE TITLE
JS error on checkout page

### ISSUE THREAD

**Issue by bporcelli** [woothemes/woocommerce#7215]
I am running WooCommerce 2.3 beta 1 on a clean install of WP 4.1 and this error message is being thrown in select2.min.js on the checkout page: "Uncaught TypeError: Cannot read property 'find' of null."  I am using an unmodified copy of the Twenty Fifteen theme and have confirmed that the error is thrown when only WooCommerce is activated. At the moment, this error is preventing the coupon form from being displayed, and breaks JavaScripts loaded by other plugins. My apologies if this has already been dealt with.

**Comment by claudiosmweb** [comment]
I guess this is fixed in beta-2.
Try the beta-2, if the errors continues, let me know.
