### ISSUE TITLE
Grammar corrections to .pot files

### ISSUE THREAD

**Issue by LewisR** [woothemes/woocommerce#7216]
Some of the English grammar is truly in need of some attention. Mainly, I've found these issues to involve disagreement between subject and antecedent (customer order...their = wrong / customer order...his or her = right).

Examples (corrected):

woocommerce.pot:

line 6830:

    #: includes/emails/class-wc-email-customer-reset-password.php:41
    msgid ""
    "Customer reset password emails are sent when a customer resets his "
    "or her password."
    msgstr ""

line 7173:

    #: includes/gateways/paypal/class-wc-gateway-paypal.php:28
    msgid ""
    "PayPal standard works by sending the user to PayPal to enter his or her payment "
    "information."
    msgstr ""

line 8151:

    #: includes/shipping/local-pickup/class-wc-shipping-local-pickup.php:25
    msgid ""
    "Local pickup is a simple method which allows the customer to pick up the "
    "order for him or herself."
    msgstr ""

line 9143:

    #: templates/emails/admin-new-order.php:18
    #: templates/emails/plain/admin-new-order.php:16
    msgid "You have received an order from %s. The order is as follows:"
    msgstr ""

I'm not clear as to how to properly submit these suggested changes. There are other more awkward wordings in the admin pot file.

**Comment by roykho** [comment]
Grammatically, I don't see anything wrong with using "their".  Do you have any source that states it is grammatically incorrect?

**Comment by LewisR** [comment]
"The customer" is singular. "Their" is plural. There must be agreement in number between the two, unless we completely throw away the rules of English Grammar. 

(My mother had a doctorate in Education and taught English at the college level for many years. I couldn't even get a paper to school without her going through it with a fine-toothed comb. This stuff was engrained in me from an early age. This is why stuff like this is like fingernails down a blackboard to me.)

A cursory Google search for "subject antecedent agreement" or "pronoun antecedent agreement" should bring up all of the proof you need, but here are a couple sources:

http://www.towson.edu/ows/pro_antagree.htm
http://www.clarkson.edu/writingcenter/docs/subject_verb.pdf
http://writingcommons.org/open-text/style/grammar/708-subject-pronoun-agreement

I'm happy to help with this in any way I can. Seeing emails come in to me telling me that *the* customer has ordered *their* products makes me nuts. :-D

**Comment by franticpsyx** [comment]
"Their" is commonly used as a gender-neutral alternative to *his/her*, but usually with *someone, anyone, everybody, nobody*, especially when the pronoun could imply a reference to more than one person. It's an accepted form. You'll find this "exception" in many grammar books.

There's a discussion here:
http://forum.wordreference.com/showthread.php?t=324472

Using *his/her* is the more "purist" approach and although it's grammatically more "correct", it is less commonly used.

Personally, I'd always write *their* with *someone, anyone, everybody, nobody*. I certainly don't like how it sounds next to *customer*. To avoid being sexist or sounding alien, passive voice is commonly preferred in formal or written use.

In case it makes any difference, my spoken english has gone downhill in the last few years since it's rarely used anymore, but I still read and use English everyday as it's my primary working language. For the record, I'm not a native speaker, but I'm qualified to teach English as a foreign language.

**Comment by claudiosmweb** [comment]
Submit a Pull Request.

**Comment by LewisR** [comment]
Without getting into a discussion of why passive voice is *never* a good idea and should *never* be used, as well as why any reference stating that gender-neutrality in a language which maintains more than one gender is a nonsequitor, I'll just make this change for my own installation and leave the project to go off on its own. Sorry for the noise.

Also, while I don't mind submitting patches, I deplore github, so making a pull request simply isn't going to happen.

Cheers, all.

**Comment by mikejolley** [comment]
You'd rather maintain a separate codebase than use git? :) I'll reopen. Can we pluralise instead of using his or her though. E.g.

`"Customer reset password emails are sent when a customer resets his "
"or her password."`

To:

`"Customer 'reset password' emails are sent when customers reset their passwords."

Does that work for you?

**Comment by franticpsyx** [comment]
>Customer reset password emails are sent when...

What about the passive voice monster lurking in there? 
Works for me, way better than anything else.

**Comment by bekarice** [comment]
I'd probably tend towards @mikejolley 's solution of simply making everything plural for correct pronoun-antecedent agreement. 

I'm willing to bet that introducing gender (his / her) may make translations more difficult in languages where the possessive determiners change depending on the gender and number of the thing that's owned. Making this plural will probably help in these languages, as you'd only have to worry about one pronoun vs multiple pronouns (German comes to mind, but I don't speak very much of it). @ragulka is more of an expert than I am, as I'm sure he can think of some fun examples in Estonian :)

**Comment by LewisR** [comment]
@franticpsyx:

>>Customer reset password emails are sent when...

>What about the passive voice monster lurking in there? 

Passive voice: "The window was then shut, causing the air in the room to grow stale." Shut by whom? In a class of 30 people, how could one even guess *who* shut the window?

Active voice: "Customer reset password emails are sent when..." It is understood that the *system* is sending these emails (unless implied elsewhere). Thus, I don't see this as passive. ;-)

In general, I would agree that plurality makes sense, as many of these phrases would quickly become cumbersome (there is a name for that figure of speech which is escaping me - no pun on the "escaping" comment intended).

@mikejolley:

>Customer 'reset password' emails are sent when customers reset their passwords.
>Does that work for you?

Indeed, Mike. That's fine, and makes perfect sense.

Again, I'm happy to provide a diff or we can collect phrases and hash them out here and one of you may then land the changes (which would have to be done anyway, I guess).

As for my comment regarding github, it's not git which I dislike, it's github (just not my cup of tea, that's all).

Cheers, all, and thanks for considering my issue. I hope I didn't come off sounding snarky or otherwise aloof. My mom is gone since 2006, and yet she still seems to follow me wherever I read (or listen). ;-)

**Comment by ragulka** [comment]
In Estonian, there is no gender in the pronouns, so I can't speak for the languages that have them. We would always say "tema" (sinular) or "nemad" (plural). So this part does not really affect Estonian, Finnish and other gender-neural languages as much. 

However, it's a good idea to think about genders and counts when forming sentences. Here's a presentation for anyone who's interested: https://docs.google.com/presentation/d/1ZyN8-0VXmod5hbHveq-M1AeQ61Ga3BmVuahZjbmbBxo/pub?start=false&loop=false&delayms=3000&slide=id.g1bc43a82_2_61

The above presentation pretty clearly shows that gettext falls short in oh-so-many places. ICU MessageFormat or [Mozilla l20n](http://l20n.org/) are far superior when dealing with genders and plurals, and ordinals and whatnot.

Having said that, gettext is still the easiest of them to implement and probably much more widely used.

**Comment by mikejolley** [comment]
Open new issues if more are spotted with line nums. I went through the emails.

**Comment by LewisR** [comment]
Sorry, and while I hate getting back into a closed ticket, there's a quick tweak needed to one of the edits you made (typo):

emails/class-wc-email-customer-completed-order.php, line 29:

Order complete emails are sent to customers when their orders are marked completed and usually indicate that their orders have been shipped.

(Currently reads: "...sent to customers when their order are marked...")
The rest look just great. Thanks. I'll open additional tickets should I find anything else.
