### ISSUE TITLE
Monthly Sales not matching up

### ISSUE THREAD

**Issue by kelechiea** [woothemes/woocommerce#7217]
Hello, My monthly sales are not matching up. What i see on the dashboard (under WooCommerce Status) and what i see on the reports page are very different. Screen shots below. please help!

![screen shot 2015-01-26 at 10 18 57 pm](https://cloud.githubusercontent.com/assets/10719262/5913069/85a7e286-a5ab-11e4-92c8-7a0085a9a39e.png)
![screen shot 2015-01-26 at 10 19 03 pm](https://cloud.githubusercontent.com/assets/10719262/5913068/85a6aba0-a5ab-11e4-9ec5-427acd33d905.png)

**Comment by mikejolley** [comment]
The widget doesn't include things such as refunds. These are made consistent in 2.3 so look out for that update within the next few weeks.

**Comment by kelechiea** [comment]
but i haven't given any refunds, so it still doesn't make sense why the numbers don't match. They were matching fine before your last update.
