### ISSUE TITLE
Ability to add draft status products to cart manually

### ISSUE THREAD

**Issue by carlaiau** [woothemes/woocommerce#7220]
Upon moving items back to 'draft' status, they can still be manually added to the cart via changing the add-to-cart=ID query to the product ID. This wouldn't be a problem usually as customers wouldn't be able to find the draft products to put into their carts, 

The problem is if people reorder backorders that contain the product that is now draft, it can still be added to the cart as all the product ID information is stored in the previous order.

We have prevented this from happening in our application by also assigning the draft products to have 'Out of Stock'. I don't think it's a deal breaker, but could catch the odd person out.

**Comment by mikejolley** [comment]
Needs validation in the handler.
