### ISSUE TITLE
Pull pricing from external site

### ISSUE THREAD

**Issue by solex67** [woothemes/woocommerce#7221]
I am looking for a way to pull live pricing from a duplicate site in aspx.
I have over 25K products & 3K customers with different pricing depending on login.
I have built a duplicate site in Woocommerce and would like to pull pricing based on login
without hardcoding individual products

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:
 
* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
