### ISSUE TITLE
Cart Total Table does not have required padding

### ISSUE THREAD

**Issue by sjeden** [woothemes/woocommerce#7223]
I have no idea how to use this thing to submit pull requests.

but the following css classes require the following to match in with all other woocommerce tables / styles.

FROM
.woocommerce-cart .cart-collaterals .cart_totals table th {
padding: 6px 12px 0 0;
width: 25%;
}

TO
.woocommerce-cart .cart-collaterals .cart_totals table th {
padding: 9px 12px;
width: 25%;
}

FROM
.woocommerce-cart .cart-collaterals .cart_totals table td, .woocommerce-cart .cart-collaterals .cart_totals table th {
vertical-align: top;
}

TO
.woocommerce-cart .cart-collaterals .cart_totals table td, .woocommerce-cart .cart-collaterals .cart_totals table th {
vertical-align: middle;
padding: 9px 12px;
}

Thanks

**Comment by claudiosmweb** [comment]
@jameskoster do you want to check it?

**Comment by jameskoster** [comment]
Looks fine to me http://cl.ly/image/1G1b2W1k180z

Perhaps your theme is added a border where there shouldn't be one in which case we'd just need to tweak the border styles. Could you share a screenshot or url?

**Comment by sjeden** [comment]
default twenty fourteen theme. 

http://wordpress.edenfamily.co.uk/?page_id=5

**Comment by sjeden** [comment]
i have tweaked it on my live production site also which is https://www.autoelectrical.parts

**Comment by jameskoster** [comment]
As I suspected, the theme is adding the borders. I'll tweak.

**Comment by sjeden** [comment]
If you add the padding it will stop the issue if there is a border anyway :)

**Comment by jameskoster** [comment]
The padding unnecessarily squishes the content. Removing the border would be better imo.

**Comment by sjeden** [comment]
Thanks :)
