### ISSUE TITLE
Color Coded Order Notes

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#7225]
I think it would be good to add different colors to the order notes depending if they are system triggered or user triggered.  Currently you have to look at the tiny text that says "by" to know if it was triggered by the system or user.

**Comment by mikejolley** [comment]
https://trello.com/c/Hg5FKase/64-new-order-note-type-for-system-notes-with-unique-color-and-properties

**Comment by ItsMePN** [comment]
I see following in tag 2.5 

```$note_classes = apply_filters( 'woocommerce_order_note_class', $note_classes, $note );```

That will really help in customizing the color of different type of order notes. Quick [example usage can be seen here] (https://wordpress.org/support/topic/is-there-any-way-to-change-order-note-color-in-admin-panel?replies=5#post-7865619)
