### ISSUE TITLE
WC_Admin_Report::sales_sparkline() - Killing large site with 56,000 orders

### ISSUE THREAD

**Issue by emmixaustralia** [woothemes/woocommerce#7228]
This query SELECT SUM( meta__order_total.meta_value) as sparkline_value, posts.post_date as post_date FROM wp_p is killing our site on an hourly (approx) basis. 

Can the sparkline query be made more efficient (given the site has 56,000 orders)? Is there a patch for this query and a site with this many orders?

------

As you can see in the logs below, after this query, every other query is locked. This query then eventually leads to the server crashing.

| 288731 | hidden | localhost | hidden _live | Query   | 9    | Copying to tmp table | SELECT SUM( meta__order_total.meta_value) as sparkline_value, posts.post_date as post_date FROM wp_p |

| 288802 | hidden | localhost | hidden_live | Query   | 6    | Locked               | SELECT post_id, meta_key, meta_value FROM wp_postmeta WHERE post_id IN (250507,250937,252026,252695, |

| 288817 | hidden | localhost | hidden_live | Query   | 6    | Locked               | SELECT post_id, meta_key, meta_value FROM wp_postmeta WHERE post_id IN (163859) ORDER BY meta_id ASC |

etc etc

**Comment by bryceadams** [comment]
Hey @emmixaustralia - which version of WC are you using?

**Comment by emmixaustralia** [comment]
Hey Bryce. Using WC v 2.1.11

**Comment by bryceadams** [comment]
hey @emmixaustralia - ah, well we're currently on 2.2.10 with 2.3.0 coming out any day now, so I'd recommend testing it with that and letting us know if it's any better :)

**Comment by emmixaustralia** [comment]
We're about a week from upgrading all of the plugins on the site as well (including WC), however in the meantime the site is crashing almost hourly. It's a relatively popular site with ~20,000 sessions per day also. So downtime is not unnoticed.

And I've taken a look at the changelogs of WC and can't see anything specific to the WC Admin Reporting that would solve the issue we're experiencing. I may be wrong, though.

I think it has a lot to do with the fact that there are 56,000+ WC orders, and it takes a long time to compute that query..

**Comment by bryceadams** [comment]
@emmixaustralia - the `sales_sparkline` method doesn't exist in the most recent version so I'm thinking it's definitely version-related. Please try update and try out the latest version :)

**Comment by emmixaustralia** [comment]
Ok thank you @bryceadams will update it as soon as we can and hopefully it's sorted! Thanks
