### ISSUE TITLE
tax label missing when order has a refund

### ISSUE THREAD

**Issue by piffpaffpuff** [woothemes/woocommerce#7229]
On the Order Total line in the My account -> View order page the tax label is missing for refunded orders:

https://github.com/woothemes/woocommerce/blob/master/templates/order/order-details.php#L102

Normally you see the Order Total with a tax label behind it, that is generated by the abstract-wc-order.php:

https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L1789-L1807

The issue seems a bit too complex to send a pull request, but I'm sure you will find the best solution to fix this ;-). The tax settings to test it: 
- Prices are entered with tax included
- The cart and checkout show the prices with tax included
- Taxes are displayed as one total item (not per item)

**Comment by claudiosmweb** [comment]
![screenshot from 2015-01-29 18 50 26](https://cloud.githubusercontent.com/assets/1264099/5965994/be5acb6e-a7e7-11e4-81ff-14813a69eaa8.png)

**Comment by piffpaffpuff** [comment]
@claudiosmweb thanks for the fix. but are you sure to put this much output logic in the template? like this the refund isn't part of the totals array and can't be filtered with 'woocommerce_get_order_item_totals'.

**Comment by claudiosmweb** [comment]
I'll change it later, bcausee needs to be redone other methods to improve it.
