### ISSUE TITLE
Make the functions really pluggable. Aka "use plugins_loaded"

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#7230]
We try to do this today, but caused some problems:
https://github.com/woothemes/woocommerce/commit/725d5e2

Let's leave that to 2.4 and warn the extensions authors.

**Comment by mikejolley** [comment]
https://trello.com/c/GVvoLjVX/57-make-the-functions-really-pluggable-aka-use-plugins-loaded
