### ISSUE TITLE
'Lower sale prices' results in zero-values for sale start and sale end dates

### ISSUE THREAD

**Issue by ewijdemans** [woothemes/woocommerce#7237]
When using the 'lower sales prices' function, the sale start and end dates are set to zero values.
Because the agenda function for the sale is NOT clicked (and thus closed), you _cannot_ see any error occuring there (for the sake of clarity, the screenshot has the agenda openend).
I found the bug via the console where the error is the same as reported here: http://stackoverflow.com/questions/7168645/invalid-form-control-only-in-google-chrome

![image](https://cloud.githubusercontent.com/assets/1649343/5956385/b032dab6-a7ad-11e4-9265-573295c1fd2b.png)

**Comment by mikejolley** [comment]
This issue does not occur in 2.3 master. Appears fixed.
