### ISSUE TITLE
Two "Customer Note" labels. Recommendation to Relabel one

### ISSUE THREAD

**Issue by rtddev** [woothemes/woocommerce#7239]
Matty suggested I post this observation/request here.

WC Order page has two "Customer Note" labels, making it slightly confusing to distinguish btw the two in writing instructions for CS.

Order Section > Customer Note
https://www.dropbox.com/s/3l9fd1uuo9b0i06/order-section-customer-note.PNG?dl=0

Order Notes > Customer Note
https://www.dropbox.com/s/9h4sti7q80cti9s/order-notes-customer-note.PNG?dl=0

Possibly consider renaming the Order Notes > Customer Note to "Public Note", which would be complimentary to "Private Note". The help (?) could be updated too, making it clear what a "Public Note" is.

This is very similar to how ticketing systems name ticket notes; public or private.

**Comment by SiR-DanieL** [comment]
I think we should change instead the one in Order Section > Customer Note.

The customer note in Order Notes makes sense to be "Customer note" because you are sending a note to the customer which easier to understand rather than a generic "Public note".

While we can use "Additiona note" or "Order note" to the order section.

Do you like it?

**Comment by roykho** [comment]
ref #7225

**Comment by rtddev** [comment]
@SiR-DanieL -- just my 2cents.

There is already a "Order Notes" section below, so if you call the top one "Order Note" that would also be confusing, I think.

Another suggestion.

Order Section > "Order Notes" (instead of "Customer Note")

Rename "Order Notes" to just "Notes"
Use Public/Private or Internal/External for the type of Note.

"Customer Note" itself generally refers to a note that the Customer provides, not one that goes to the Customer.

**Comment by SiR-DanieL** [comment]
That's ok for me, i'm just not convinced about this

> Use Public/Private or Internal/External for the type of Note.

**Comment by mikejolley** [comment]
Punting this to 2.4
