### ISSUE TITLE
Bug with query

### ISSUE THREAD

**Issue by emmixaustralia** [woothemes/woocommerce#7241]
Our server admin has found this query that's killing our server. He's adamant it's a bug - it took down the site by causing table locks and 100's of queries to pile up.

See http://pastebin.com/dytGM6kK

The issue with this query is probably coming to light because we're using woocommerce on a site with 56,000+ orders.

We are running latest WordPress + latest WooCommerce (2.2.10)

**Comment by emmixaustralia** [comment]
We are running latest WordPress + latest WooCommerce (2.2.10)

**Comment by kieranbarnes** [comment]
That looks like a query generated by the Subscriptions plugin. You'll probably need to raise a ticket with Woo as it isn't directly related to the WooCommerce core.

Devs will confirm.

**Comment by mikejolley** [comment]
Please raise a ticket on support.woothemes.com so the subs dev/support staff can look into this. This issue tracker is for core only.
