### ISSUE TITLE
Deleting a variable product doesn't delete variations

### ISSUE THREAD

**Issue by kieranbarnes** [woothemes/woocommerce#7242]
Poking this issue again... It's closely related to #7077 
Another use case similar to #7077 

- Store has a variable product with SKUs set.
- Variable product is deleted
- **Product Variations and associated postmeta still exist in DB**
- Store owner can't create those products with those SKUs ever again.

We have to manually remove those posts from the DB. 

Example; Deleted post ID 3690. 

```
Query: SELECT * FROM wp_posts WHERE id = 3690
0 row(s) returned
```

This query returns zero as expected, the post is deleted

```
Query: select * from wp_posts where post_parent = 3690
2 row(s) returned
```

This query returns 2 rows (3696,3697) which are the old variations. In turn they have postmeta

```
Query: select * from wp_postmeta where post_id in (3696,3697)
18 row(s) returned
```

So, two issues;
- This leaves orphaned data in the database.
I partially agree with @claudiosmweb from #7077 
that saving this info can be helpful if the product is accidently deleted, however what if it was deleted purposely? 
- This means the store owner can never add the same product again with the same SKUs?

**Comment by mikejolley** [comment]
There is logic that deletes variations when a parent is deleted. Are you leaving the product in trash?

**Comment by kieranbarnes** [comment]
It's not in trash. If it was I'd expect the first query to return a result.

I wonder if the product is changed from variable to simple then deleted.
More testing...

**Comment by mikejolley** [comment]
Steps I tried:

- Create variable product with 3 children
- Trash
- Empty trash

Var dumps show the loop deleting variation children: https://dl.dropboxusercontent.com/s/fiz0p8uzpnfrcxz/2015-01-30%20at%2013.13%202x.png?dl=0

From https://dl.dropboxusercontent.com/s/va0o0me9e462hnt/2015-01-30%20at%2013.14%202x.png?dl=0

**Comment by kieranbarnes** [comment]
Try this;

- Create variable product with 3 children
- Change to a simple product
- Trash
- Empty Trash

I've spent a day clearing up ~100 products from a customer store with this issue, but I don't seem to be able to reliably replicate it.

**Comment by mikejolley** [comment]
Just tried that on a clean install; they were still removed as expected. Sorry :)

**Comment by kieranbarnes** [comment]
Agreed. I can't replicate too well either. No idea how 2 customers have ended up like this!

**Comment by larkin71** [comment]
I've run into this issue, but when deleting the entire product. I've simply deleted a variation and the data has remained in the DB.

**Comment by tommy83** [comment]
We have the same issue. Also in fresh wp + woo setup without any other plugin. Tested with wp default theme.

**Comment by tommy83** [comment]
@kb6673  @mikejolley 
We can reproduce this issue in every fresh installed woocommerce environment.
We also asked other users in other forum - and all webmaster who we asked to check confirmed this issue.
We manage +60 stores and all have the same problem.

Please ping me, because we have to found a solution here. Because this problem cause many more problems: blocking skus and  many more. If you can not help us: Which person we can ping here to find a solution please?
