### ISSUE TITLE
Basket Serialisation

### ISSUE THREAD

**Issue by kieranbarnes** [woothemes/woocommerce#7245]
We're running some external validation on basket contents.
(Using `woocommerce_check_cart_items` to check items against an ERP system)

In short, it reads the serialised basket contents from  *wp_options.option_value*
Most of the baskets unserialize correctly, eg

```{s:10:"product_id";i:8865;``` (Snippet)

However some baskets store the product_id as a string, however all product_ids are integers

```{s:10:"product_id";s:4:"8525"```(Snippet)

We're wondering whether this is a Woo, WP or PHP bug within the basket serialization.

**Comment by mikejolley** [comment]
There is no type casting on product_id. Will make them consistent in 2.4.
