### ISSUE TITLE
js error on edit product screen

### ISSUE THREAD

**Issue by jameskoster** [woothemes/woocommerce#7246]
`Uncaught TypeError: undefined is not a function`

Referencing `jQuery("select.ajax_chosen_select_coupons").ajaxChosen({`

**Comment by jameskoster** [comment]
smart coupons

**Comment by ginsterbusch** [comment]
Experiencing the same error, but "smart coupons" doesnt help as a "solution". Whatever that might be (guessing its the name of a plugin?).

cu, w0lf.

**Comment by claudiosmweb** [comment]
@ginsterbusch the error is in the Smart Coupons plugin ;)

**Comment by jknight2014** [comment]
Was there a solution to this error? I can not seem to find anything else relating to this error anywhere. It definatly is smart coupons but I can not figure out exactly whats wrong with it.
