### ISSUE TITLE
My Account - Login Form not outputting Error details just woocommerce-message box

### ISSUE THREAD

**Issue by sjeden** [woothemes/woocommerce#7247]
My live production site is https://www.autoelectrical.parts 

My site is not outputting the error just the red message box.

Here is the logs, - i have tried disabling all plugins to see if it resolved and cannot get it too. - Latest pull from here also.

### WordPress Environment ###

Home URL: https://www.autoelectrical.parts
Site URL: https://www.autoelectrical.parts
WC Version: 2.3.0
WC Database Version: 2.3.0
Log Directory Writable: ✔ /home/****/wp-content/uploads/wc-logs/
WP Version: 4.1
WP Multisite: –
WP Memory Limit: 96 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.3.28
PHP Post Max Size: 200 MB
PHP Time Limit: 600
PHP Max Input Vars: 20000
SUHOSIN Installed: –
MySQL Version: 5.5.40
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
Remote Post: ✔
Remote Get: ✔

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (22) ###

iThemes Security: by iThemes.com – 4.6.4
Contact Form 7: by Takayuki Miyoshi – 4.1
Relevanssi: by Mikko Saari – 3.3.8
Testimonials: by WooThemes – 1.5.3
Username Changer: by Daniel J Griffiths – 2.0.5
WooCommerce Colors: by WooThemes – 1.0.1
WooCommerce Dynamic Pricing: by Lucas Stark – 2.9.1
WooCommerce Purchase Order Payment Gateway: by WooThemes – 1.1.0
WooCommerce SagePay Form Gateway: by Add On Enterprises – 2.2.3
WooCommerce Google Analytics Integration: by WooThemes – 1.3.0
WooCommerce Print Invoice/Packing list: by SkyVerge – 2.4.4
WooCommerce Product Archive Customiser: by jameskoster – 0.5.0
WooCommerce Product Details Customiser: by jameskoster – 0.2.0
WooCommerce Role Based Methods: by WPBackOffice – 2.0.3
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.6.5
WooCommerce Table Rate Shipping: by Mike Jolley – 2.7.1
WooCommerce: by WooThemes – 2.3-beta-2
WooThemes Helper: by WooThemes – 1.4.1
WordPress SEO: by Team Yoast – 1.7.1
WP Smush.it: by WPMU DEV – 1.7
WPFront User Role Editor: by Syam Mohan – 2.3
Yoast WooCommerce SEO: by Team Yoast – 1.1.5

### Settings ###

API Enabled: ✔
Taxes Enabled: ✔
Shipping Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Shop Base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Durite Online Theme
Version: 0.0.1
Author URL: http://www.duriteonline.co.uk
Child Theme: ✔
Parent Theme Name: Twenty Fourteen
Parent Theme Version: 1.3
Parent Theme Author URL: http://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: twentyfourteen-child/woocommerce/archive-product.php
twentyfourteen-child/woocommerce/cart/cart-empty.php
twentyfourteen-child/woocommerce/cart/cart-item-data.php
twentyfourteen-child/woocommerce/cart/cart-shipping.php
twentyfourteen-child/woocommerce/cart/cart-totals.php
twentyfourteen-child/woocommerce/cart/cart.php
twentyfourteen-child/woocommerce/cart/cross-sells.php
twentyfourteen-child/woocommerce/cart/mini-cart.php
twentyfourteen-child/woocommerce/cart/shipping-calculator.php
twentyfourteen-child/woocommerce/checkout/cart-errors.php
twentyfourteen-child/woocommerce/checkout/form-billing.php
twentyfourteen-child/woocommerce/checkout/form-checkout.php
twentyfourteen-child/woocommerce/checkout/form-coupon.php
twentyfourteen-child/woocommerce/checkout/form-login.php
twentyfourteen-child/woocommerce/checkout/form-pay.php
twentyfourteen-child/woocommerce/checkout/form-shipping.php
twentyfourteen-child/woocommerce/checkout/payment-method.php
twentyfourteen-child/woocommerce/checkout/payment.php
twentyfourteen-child/woocommerce/checkout/review-order.php
twentyfourteen-child/woocommerce/checkout/thankyou.php
twentyfourteen-child/woocommerce/content-product.php
twentyfourteen-child/woocommerce/content-product_cat.php
twentyfourteen-child/woocommerce/content-single-product.php
twentyfourteen-child/woocommerce/content-widget-product.php
twentyfourteen-child/woocommerce/emails/admin-cancelled-order.php
twentyfourteen-child/woocommerce/emails/admin-new-order.php
twentyfourteen-child/woocommerce/emails/customer-completed-order.php
twentyfourteen-child/woocommerce/emails/customer-invoice.php
twentyfourteen-child/woocommerce/emails/customer-new-account.php
twentyfourteen-child/woocommerce/emails/customer-note.php
twentyfourteen-child/woocommerce/emails/customer-processing-order.php
twentyfourteen-child/woocommerce/emails/customer-reset-password.php
twentyfourteen-child/woocommerce/emails/email-addresses.php
twentyfourteen-child/woocommerce/emails/email-footer.php
twentyfourteen-child/woocommerce/emails/email-header.php
twentyfourteen-child/woocommerce/emails/email-order-items.php
twentyfourteen-child/woocommerce/emails/email-styles.php
twentyfourteen-child/woocommerce/emails/plain/admin-cancelled-order.php
twentyfourteen-child/woocommerce/emails/plain/admin-new-order.php
twentyfourteen-child/woocommerce/emails/plain/customer-completed-order.php
twentyfourteen-child/woocommerce/emails/plain/customer-invoice.php
twentyfourteen-child/woocommerce/emails/plain/customer-new-account.php
twentyfourteen-child/woocommerce/emails/plain/customer-note.php
twentyfourteen-child/woocommerce/emails/plain/customer-processing-order.php
twentyfourteen-child/woocommerce/emails/plain/customer-reset-password.php
twentyfourteen-child/woocommerce/emails/plain/email-addresses.php
twentyfourteen-child/woocommerce/emails/plain/email-order-items.php
twentyfourteen-child/woocommerce/global/breadcrumb.php
twentyfourteen-child/woocommerce/global/form-login.php
twentyfourteen-child/woocommerce/global/quantity-input.php
twentyfourteen-child/woocommerce/global/sidebar.php
twentyfourteen-child/woocommerce/global/wrapper-end.php
twentyfourteen-child/woocommerce/global/wrapper-start.php
twentyfourteen-child/woocommerce/loop/add-to-cart.php
twentyfourteen-child/woocommerce/loop/loop-end.php
twentyfourteen-child/woocommerce/loop/loop-start.php
twentyfourteen-child/woocommerce/loop/no-products-found.php
twentyfourteen-child/woocommerce/loop/orderby.php
twentyfourteen-child/woocommerce/loop/pagination.php
twentyfourteen-child/woocommerce/loop/price.php
twentyfourteen-child/woocommerce/loop/rating.php
twentyfourteen-child/woocommerce/loop/result-count.php
twentyfourteen-child/woocommerce/loop/sale-flash.php
twentyfourteen-child/woocommerce/myaccount/form-add-payment-method.php
twentyfourteen-child/woocommerce/myaccount/form-edit-account.php
twentyfourteen-child/woocommerce/myaccount/form-edit-address.php
twentyfourteen-child/woocommerce/myaccount/form-login.php
twentyfourteen-child/woocommerce/myaccount/form-lost-password.php
twentyfourteen-child/woocommerce/myaccount/my-account.php
twentyfourteen-child/woocommerce/myaccount/my-address.php
twentyfourteen-child/woocommerce/myaccount/my-downloads.php
twentyfourteen-child/woocommerce/myaccount/my-orders.php
twentyfourteen-child/woocommerce/myaccount/view-order.php
twentyfourteen-child/woocommerce/notices/error.php
twentyfourteen-child/woocommerce/notices/notice.php
twentyfourteen-child/woocommerce/notices/success.php
twentyfourteen-child/woocommerce/order/form-tracking.php
twentyfourteen-child/woocommerce/order/order-again.php
twentyfourteen-child/woocommerce/order/order-details.php
twentyfourteen-child/woocommerce/order/tracking.php
twentyfourteen-child/woocommerce/product-searchform.php
twentyfourteen-child/woocommerce/single-product/add-to-cart/external.php
twentyfourteen-child/woocommerce/single-product/add-to-cart/grouped.php
twentyfourteen-child/woocommerce/single-product/add-to-cart/simple.php
twentyfourteen-child/woocommerce/single-product/add-to-cart/variable.php
twentyfourteen-child/woocommerce/single-product/meta.php
twentyfourteen-child/woocommerce/single-product/price.php
twentyfourteen-child/woocommerce/single-product/product-attributes.php
twentyfourteen-child/woocommerce/single-product/product-image.php
twentyfourteen-child/woocommerce/single-product/product-thumbnails.php
twentyfourteen-child/woocommerce/single-product/rating.php
twentyfourteen-child/woocommerce/single-product/related.php
twentyfourteen-child/woocommerce/single-product/review.php
twentyfourteen-child/woocommerce/single-product/sale-flash.php
twentyfourteen-child/woocommerce/single-product/share.php
twentyfourteen-child/woocommerce/single-product/short-description.php
twentyfourteen-child/woocommerce/single-product/tabs/additional-information.php
twentyfourteen-child/woocommerce/single-product/tabs/description.php
twentyfourteen-child/woocommerce/single-product/tabs/tabs.php
twentyfourteen-child/woocommerce/single-product/title.php
twentyfourteen-child/woocommerce/single-product/up-sells.php
twentyfourteen-child/woocommerce/single-product-reviews.php
twentyfourteen-child/woocommerce/single-product.php
twentyfourteen-child/woocommerce/taxonomy-product_cat.php
twentyfourteen-child/woocommerce/taxonomy-product_tag.php

**Comment by claudiosmweb** [comment]
WHy you are using a beta version in production?

**Comment by sjeden** [comment]
i have a backup of my old site :) 2.3 works better than 2.2 :) 

This site is functioning great with 2.3 loaded.

**Comment by claudiosmweb** [comment]
Tested in Twenty Fourteen and works fine.

**Comment by mikejolley** [comment]
Possibly a setting in the security plugin. Some plugins hide messages to avoid the user guessing usernames.

**Comment by sjeden** [comment]
The register form works okay, let me check the settings for it.

**Comment by sjeden** [comment]
Yes, i have disabled the plugin and it now shows error, let me find the rogue setting for knowledge
