### ISSUE TITLE
Add the Terms and Conditions checkbox on order-pay

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7252]
It would be useful for some customers to have the terms&cond checkbox in the Pay order page.

It'useless when you place an order and the status is pending payment, but when you create the order as admin and send the pay URL to the customer, it would be useful.

Maybe we can check this or enable the checkbox only when the order has been created by an admin?

**Comment by mikejolley** [comment]
https://trello.com/c/l7GQsmpi/58-add-the-terms-and-conditions-checkbox-on-order-pay
