### ISSUE TITLE
Feature Request:  Include business/income tax calculation.

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#7257]
it would be great for those using this plugin to be able to do most of their accounting with it for tax return etc...  it would really help those who don't know anything about taxes.

**Comment by jshand2015** [comment]
also would be great to add calculation for student loan repayment percentage as well.

many thanks

**Comment by mikejolley** [comment]
We already include tax reports, but this isn't a full accounting solution. This would need to vary between jurisdictions and would thus be extension territory.
