### ISSUE TITLE
CSV exported reports show incorrect date

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#7276]
It seems as though the exported CSV records are listed as a day behind.

Reports screen for February 2: http://cld.wthms.co/1e1K6
CSV export for that date shows as February 1: http://cld.wthms.co/1cNF4

**Comment by michaeltieso** [comment]
I can reproduce with 2.2. Haven't tested with 2.3 yet.
http://cld.wthms.co/17CNV
http://cld.wthms.co/vbRQ
