### ISSUE TITLE
View List Of Products Return Just 1 (one) Product

### ISSUE THREAD

**Issue by alexrusenhack** [woothemes/woocommerce#7281]
The GET method on "/wc-api/v2/products" just return the first product of the list and not the entire list as supposed. I'm using the [REST API Client Library](https://github.com/kloon/WooCommerce-REST-API-Client-Library) customized for the version 2.

**Comment by bryceadams** [comment]
@alexrusenhack i am testing this locally and it works for me. What is the entire code you're using to make the call?

**Comment by bryceadams** [comment]
I'm going to close this at the moment because it definitely works for me but feel free to reply with more info and I can try help debug.

**Comment by claudiosmweb** [comment]
Probably because this set as well in your WordPress.
You can use the `limit` parameter to query for more products:
http://woothemes.github.io/woocommerce-rest-api-docs/#pagination

**Comment by alexrusenhack** [comment]
@claudiosmweb thanks to explain. But how can I GET without limit?

**Comment by alexrusenhack** [comment]
@bryceadams and @claudiosmweb 

Works with this solution:
```
get_products ( array ( "filter[limit]" => 1000 ) );
```
Solved! Thanks all.

**Comment by bryceadams** [comment]
@alexrusenhack for no limit:

```
get_products ( array ( "filter[limit]" => -1 ) );
```

**Comment by alexrusenhack** [comment]
So close! =)

@bryceadams thanks.
