### ISSUE TITLE
View a Product's Orders Endpoint

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#7285]
Similar to the 'view a customer's orders' endpoint, this would be useful to view all orders that a product was purchased in.

**Comment by cklosowski** [comment]
Would love to take this on, but the API isn't seeming to like my signatures, no matter what order they are tokenized in. How are you guys using the API Locally to test it out?

**Comment by cklosowski** [comment]
Found a way around it, it'd be nice if there was a way to invoke the basic auth for developers with a constant or something, so it checks both `is_ssl()` and a defined constant, using things like POSTMan for Chrome is easier to do while testing/development on the API is happening.

**Comment by maxrice** [comment]
@cklosowski you can override the auth locally with something like:

```php
add_filter( 'woocommerce_api_check_authentication', function() { return new WP_User( 1 ); } );
```

**Comment by cklosowski** [comment]
Nice, thanks @maxrice.

**Comment by cklosowski** [comment]
@bryceadams @claudiosmweb would love to get some feedback. First time working with WooCommerce codebase and API, so let me know if there's anything that needs changing for following your standards.
