### ISSUE TITLE
Need updates to user meta _money_spent / _order_count

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#7286]
We've changed the way the 'customer' API end point gets a customer's `order_count` and `total_spent`, so now it's using the new functions `wc_get_customer_order_count` and `wc_get_customer_total_spent`.

The issue is that in those functions we are checking if the user meta already exists before doing the new DB query for this data. I think we will need to update this when someone updates to 2.3, basically doing the queries from those two functions and updating the user meta to what it should be.

**Comment by mikejolley** [comment]
Clear db on upgrade
