### ISSUE TITLE
[2.3]JS errors on product page when no internet connection

### ISSUE THREAD

**Issue by kloon** [woothemes/woocommerce#7287]
When you have no internet connection and browse the product add/edit screen there are JS error present and the screen fails to load correctly http://cld.wthms.co/LaHy

This will cause issues for sites where WooCommerce are used on intranets for example.

**Comment by mikejolley** [comment]
Whats in the console?

**Comment by kloon** [comment]
@mikejolley seems to be related to the enhanced select script http://cld.wthms.co/HuLq

**Comment by claudiosmweb** [comment]
@mikejolley the culprit is select2 by CDN xD
