### ISSUE TITLE
Ability to change chart_groupby when querying API reports

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#7293]
This uses `WC_Admin_Report->chart_groupby` and if the 'period' between 2 dates is greater than 90 days, it returns report data in periods of months. It should be possible to override this and make it by days for lengthy periods.

**Comment by barrykooij** [comment]
Yeah, noticed the same thing. Think this is done for performance. @maxrice @mikejolley you guys see any performance breaking issues if we make that period overridable?

**Comment by maxrice** [comment]
I think it'd be fine :+1:

**Comment by mikejolley** [comment]
https://trello.com/c/qw56Wc2v/61-rest-api-change-chart-groupby-when-querying-api-reports
