### ISSUE TITLE
Free shipping coupon with max amount not allowed

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7294]
I created a free shipping coupon with min order amount 18$ and max 36$.

When i add a product of 18$ into the cart and apply the coupon, everything works fine.
If i increase the cart value to 36$, the coupon is removed because invalid.

If i change the coupon max value to 36.01$ the result is the same

![](http://cld.wthms.co/zYCp+)

http://cld.wthms.co/zYCp

**Comment by mikejolley** [comment]
As discussed, this is due to other costs (coupon checks are based on order total).
