### ISSUE TITLE
Action "woocommerce_refund_created" not in release?

### ISSUE THREAD

**Issue by harisb** [woothemes/woocommerce#7295]
Why is the woocommerce_refund_created action not in the official release but it is here on Github?  I end up having to manually add it in every time I update WooCommerce because I have some functionality that runs when refunds are created.

Is this left out intentionally or is it a bug?

https://github.com/woothemes/woocommerce/blob/9bc1b09fc5f2efc9c0168b24d6407351a0815385/includes/wc-order-functions.php#L685

**Comment by mikejolley** [comment]
Because github master is 2.3 and stable is 2.2.
