### ISSUE TITLE
Warning when using [product_categories] shortcode

### ISSUE THREAD

**Issue by jameskoster** [woothemes/woocommerce#7298]
`Warning: array_map(): Argument #2 should be an array in /srv/www/wordpress-default/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php on line 220`

**Comment by bryceadams** [comment]
This was fixed in https://github.com/woothemes/woocommerce/commit/5bb4b7739f2540c8a564288674d4889d94851f6f#diff-455864a907bfbe38bd4304a8fd65c24d

@jameskoster are you using RC1?

**Comment by jameskoster** [comment]
Yes I am ;p
