### ISSUE TITLE
Creating Product W/ Attributes gives http 201 error

### ISSUE THREAD

**Issue by DanielFris** [woothemes/woocommerce#7300]
API v2 using SSL on localhost. Using the PHP Wrapper by Kloon.  

I can create simple products fine. Trying something like this returns 201 error: 
```
// Initialize the class
$wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );

$attributes = new stdClass;
$attributes->name = 'any';
$attributes->slug = 'any';
$attributes->position = '1';
$attributes->visible = TRUE;
$attributes->variation = TRUE;
$attributes->options = array(
	'some','thing',
);

$attribute_array[] = $attributes;

$products_to_add = array(
	'product' => array(
		'title' => 'Booty',
		'type' => 'variable',
		'regular_price' => '21.99',
		'sku'=>'biz-mc-06',
		'attributes'=> $attribute_array,
	),
);
$add_products = $wc_api->add_products($products_to_add);
```

Which actually creates the product as a 'draft' but returns this as well 

```
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => 201
                    [message] => cURL HTTP error 201
                )

        )

)
```

**Comment by claudiosmweb** [comment]
Wrong url or don't have SSL or SSL configured wrong!
This is the cURL error and not a WooCommerce error.

**Comment by necro369** [comment]
I have the same problem.

Product example. Good result:

```
object(stdClass)[6]
  public 'title' => string 'Premium Quality' (length=15)
  public 'type' => string 'simple' (length=6)
  public 'regular_price' => string '21.99' (length=5)
  public 'description' => string 'Example' (length=7)
  public 'short_description' => string 'Example' (length=7)
```

Product example. 201 error:

```
object(stdClass)[6]
  public 'title' => string 'Premium Quality' (length=15)
  public 'type' => string 'simple' (length=6)
  public 'regular_price' => string '21.99' (length=5)
  public 'description' => string 'Example' (length=7)
  public 'short_description' => string 'Example' (length=7)
  public 'categories' => 
    array
      0 => string 'Clothing' (length=8)
      1 => string 'T-shirts' (length=8)
```

**Comment by DanielFris** [comment]
And if you remove the attribute / variation data it passes without error as response. So how would that be an SSL misconfiguration? Would appreciate more information and / or a reopen of this ticket.

**Comment by maxrice** [comment]
It looks like you've customized the wrapper to allow POST requests without editing the cURL section to accept both 200 and 201 HTTP response codes :smile: HTTP 201 means the resource was created successfully, so it's not an error.

**Comment by DanielFris** [comment]
Okay! Thank you!

What about the product being created with status of 'draft'  ( even if 'publish' is declared ) when including attribute / variation data?

**Comment by necro369** [comment]
This is what it returns cURL for the error 201. I hope it can help you.

```
string '<br />
<b>Notice</b>:  Array to string conversion in <b>/var/www/wp-includes/class-wp.php</b> on line <b>281</b><br />
{"product":{"title":"Premium Quality","id":3364,"created_at":"2015-02-06T09:00:17Z","updated_at":"2015-02-06T09:00:17Z","type":'... (length=1700)
```

**Comment by DanielFris** [comment]
Sorted that creating the product as type=variable w/out filling in variable / attribute data in full will cause post to sit at status=draft.
