### ISSUE TITLE
Create Products

### ISSUE THREAD

**Issue by IcuScc** [woothemes/woocommerce#7309]
Hi,
I want to create & update products (simples or with variations)
have anybody an example?

Thanks a lot

**Comment by mikejolley** [comment]
Don't log support questions on our issue tracker please.

http://woothemes.github.io/woocommerce-rest-api-docs/#products

**Comment by IcuScc** [comment]
thanks. @mikejolley 
i dont have ssl

**Comment by claudiosmweb** [comment]
@IcuScc So use OAuth http://woothemes.github.io/woocommerce-rest-api-docs/#authentication ;)

**Comment by IcuScc** [comment]
Thanks @claudiosmweb  i go to try it. but it is so difficult to me. 
best regards

**Comment by IcuScc** [comment]
Hi again, friends. @mikejolley @claudiosmweb 
I think that I got it, but it doesn't works...  i retrieve null result. Can you help me?? i show you my code

-------------------------------------------------------------------------------------------------------------------------------
I put this function in WC_API_Client class
-------------------------------------------------------------------------------------------------------------------------------
 public function crear_producto( $data = array() ) 
 {
	$jsonInfArt=json_encode($data);
	return $this->_make_api_call( 'products/' .  $jsonInfArt, 'POST' );
 }

after in my php file i have this code
--------------------------------------------------------------------------------------------------------------------------------
<?php
error_reporting( E_ALL );
ini_set( 'display_errors', 'On' );
require_once( '../../wp-load.php' );
require_once "../class-wc-api-client_v2.php";

$aInfArt=array('product'	=>array(
			'title'				=> 'icu',
			'type'              => 'simple',
			'sku'               => 'icusky',
			'regular_price'		=> '100',
			'description'		=> 'Descripcion Larga',
			'short_description'	=> 'Descripcion Corta',
			'categories'	=>array('General'),
		));

if(isset( $_GET[ 'infart' ] ))
{
	$aInfArt = $_GET['infart'];
}

function returnWC_API()
{
	$consumer_key = 'ck_My'; 
	$consumer_secret = 'cs_My'; 
	$store_url = 'http://www.my.es/'; 

    $wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
    return $wc_api;
}

function crea_producto($aInfoProducto)
{
	$productInfo = returnWC_API()->crear_producto($aInfoProducto)->{"product"};
	return $productInfo;
}

$aResultado=crea_producto($aInfArt) ;
print_r(json_encode($aResultado)) ;

?>

I get null result
whats wrong?? can you help me??

Thanks a lot

**Comment by claudiosmweb** [comment]
`class-wc-api-client_v2.php`?

I know this class, do not know what it is she and I suggest you review your code.

**Comment by IcuScc** [comment]
hi @claudiosmweb 

yes.. in    class-wc-api-client_v2.php i have the code for call api V2 whith OAuth.  I get this code in this link: https://github.com/kloon/WooCommerce-REST-API-Client-Library

i change v1 by v2 in API_ENDPOINT property

with this class, i can delete products, update orders status, get products, etc... but when i create product i retrieve null result and i no see why?

the parameter array product,  How will it be?, i think that not work for array product.

Thanks a lot, @claudiosmweb

**Comment by claudiosmweb** [comment]
@IcuScc http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product
Just read the docs and review your code. It's very simple!

**Comment by IcuScc** [comment]
Thanks. @claudiosmweb 
i revised my code and i make a couple of changes, but nothing.
can you help me? i pay you some money. if you want, wen can talk in private

**Comment by claudiosmweb** [comment]
@IcuScc nop!

**Comment by IcuScc** [comment]
thanks @claudiosmweb 
how can i get help about this?
