### ISSUE TITLE
WooCommerce API Find Product by SKU

### ISSUE THREAD

**Issue by vlutton** [woothemes/woocommerce#7311]
I am trying to find products by SKU in order to update them, every other route is working fine, but finding product by sku is returning the following:
{"errors":[{"code":"woocommerce_api_no_route","message":"No route was found matching the URL and request method"}]}

I have double-checked the route multiple times and tried every other route listed in the API to ensure I am setting up my method correctly, but this is the only one that is not working for me.

**Comment by claudiosmweb** [comment]
Available in WC 2.3, that will be released next week.

**Comment by grandslambert** [comment]
"Next Week" as in what day next (this) week? I need this feature as well and would love to know when I can actually start using it. Kind of annoying that it's already in the API Docs but it doesn't work.

**Comment by claudiosmweb** [comment]
@grandslambert Understand that will be released on the bugs are fixed, we are working here every day fixing bugs and trying to launch this version as soon as possible.
In the meanwhile you can help us fix the issue or I can remove from the docs for you.
