### ISSUE TITLE
add_to_cart_fragments deprecated?

### ISSUE THREAD

**Issue by XanderRock** [woothemes/woocommerce#7314]
Hi,

As I see in the new version 2.3 "add_to_cart_fragments" filter deprecated. Will there be another filter for this? Or it will be completely removed and ajax will not be supported in the next (maybe 2.4) version? That may cause a lot of functions to not work on the next release.

**Comment by ctalkington** [comment]
i believe they are fixing the naming only. ie now prefixed with `woocommerce`

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-ajax.php#L93

theres also backcompat from looks:

https://github.com/woothemes/woocommerce/blob/25840417009abd23e23b988ae0fa01892dc6d875/includes/wc-deprecated-functions.php#L513

**Comment by mikejolley** [comment]
^ correct

**Comment by XanderRock** [comment]
Hi,

Thanks for the details. It's good to know it's not going anywhere. I couldn't find any docs regarding this new named hook. Is there any doc that details these changes or you found it in the codes by yourself?

**Comment by mikejolley** [comment]
http://docs.woothemes.com/wc-apidocs/deprecated.html

**Comment by mikejolley** [comment]
Ah thats functions not hooks. No, I'll see if we can put something together, or you can search codebase for `@deprecated`
