### ISSUE TITLE
wc_customer_bought_product sql query is a Performance Nightmare

### ISSUE THREAD

**Issue by 30suns** [woothemes/woocommerce#7322]
The query in `includes/wc-user-functions.php ` `wc_customer_bought_product` is a performance nightmare on the single product page when a reasonable number of orders exist. I've profiled it eating up 2-3 seconds in the database on a single product that has say, several hundred orders. I haven't investigated whether it can be optimized, or mysql indexes added to fix it, I've just added a custom line  to `return false;` before the query runs, but it would be nice if it could be fixed properly in mainline.

**Comment by mikejolley** [comment]
Not much can be done tbh due to the joins required. I've done what I can to the query, and will have to add transient caching.
