### ISSUE TITLE
Shipping costs not updating correctly when changing custom billing/shipping field

### ISSUE THREAD

**Issue by Rajapress** [woothemes/woocommerce#7325]
Am using woocommerce_checkout_fields filter to create my custom shipping field.

There are two options for shipping for my store
1) Rush  2) Normal

add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );
function custom_override_checkout_fields( $fields ) {
    $fields['shipping']['shippping_nature'] = array(
        'label' => 'Shipping Type',
        'required' => 1,
        'type' =>'select',
        'options'     => array(
        'normal' => __('Normal', 'woocommerce' ),
        'rush' => __('Rush', 'woocommerce' ),  
        ),
        'class' => array ('address-field', 'update_totals_on_change' )
        //'class' => array ('form-row-last validate-required', 'update_totals_on_change' )
    );

    return $fields;
} 

This is the checkout flow
a) Shipping_nature key gets uploaded to the post_data on ajax call.
b) I extract post_data and i calculate shipping costs based on the shipping nature value. 
c) Am using Local delivery module.

Ajax call is only updating the shipping price if any of the core fields get changed, but not when my custom field gets changed.

Why this is happening ? Anyone having suggestions or faced similar issues. Let me know

Woocommerce Version 2.2.8

**Comment by mikejolley** [comment]
A class of update_totals_on_change should be enough. Check the source to ensure its set correctly, and also ensure the console has no JS errors.

This however isn't a bug issue report - please don't use github for support. https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

**Comment by leocheungswell** [comment]
This seems to be broken for v3.4.6.

`woocommerce_form_field( 'checkout_customer_ship_acct', array(
                    'label' => __("Customer's Shipping Account No. <abbr class='required' title='required'>*</abbr>", SWELL_THEME),
                    'type' => 'text',
                    'required' => false,
                    'class' => array('update_totals_on_change'),
                    'placeholder' => __('Enter Shipping Account No.', 'theme'),
));`

and it's not calling the calculate_shipping() in our custom shipping method.
