### ISSUE TITLE
New order email not sent on other languages besides English

### ISSUE THREAD

**Issue by ghunti** [woothemes/woocommerce#7328]
Hi.
I have Woocommerce 2.2.11 and WooCommerce Multilingual 3.5.1, and I've been having an issue for some time now.
My website has two languages EN and PT (default), and if a user places an order in English the "New Order Email" is triggered, but if the order is placed in Portuguese no emails are sent.

After some debugging, I've came across a piece of code that seems a bit odd. Since I've never developed for WP, I don't know if the problem is in this piece of code, or elsewhere.

If you open the class `WC_Email`, it's possible to see this line on the `__construct()`:
`$this->enabled     = $this->get_option( 'enabled' );`
if we analyze the `get_option()` method we learn that it wraps a parent call for the same method inside a translation function `__( parent::get_option(...))`.

Latter if we check the method `is_enabled` we see that we always compare the `$this->enabled` with "yes".:
```
public function is_enabled() {
		$enabled = $this->enabled == "yes" ? true : false;
``` 
The problem in my case is that every time an order is placed in Portuguese the `$this->enabled` variable will have the value "sim" which is the translation from "yes".

Is this problem from Woocomerce or might this be some problem with my translation system? 
Thanks

**Comment by claudiosmweb** [comment]
Don't translate the `yes` and `no`, this is only used in the `enabled` option.

**Comment by claudiosmweb** [comment]
And this have a filter: https://github.com/woothemes/woocommerce/blob/afb19715d48dc08b2fbec9a87c2f093855c7d1a2/includes/emails/class-wc-email.php#L335-L344

You can fix this behavior.

**Comment by ghunti** [comment]
I've used the filter.
But isn't the solution "don't translate the word yes" a bit odd? If its not supposed to be translated then it shouldn't be sent to translation or you should make the code compare the fetched value (which is possibly translated) with the translation of "yes".
Why not make the "enabled" a true/false value?
Cheers
