### ISSUE TITLE
Add a mass product update endpoint to REST API

### ISSUE THREAD

**Issue by lamosty** [woothemes/woocommerce#7329]
It would be nice if we could **mass update the products** with WC REST API. Currently, we can only update a single product with its ID by doing a PUT request to  `/wc-api/v2/products/<id>`. However, it would help if we could do a PUT request to `/wc-api/v2/products` with all the products we want to update specified in the JSON data. Products could be identified and matched by their SKU.

**Comment by mikejolley** [comment]
Wouldn't this just be moving the 'loop' from your code calling the API, to the API itself? I'm not certain this would be worth the extra logic/endpoints/code required. @claudiosmweb?

**Comment by claudiosmweb** [comment]
Yeah, the best is you create a loop in your side.

**Comment by maxrice** [comment]
I think this is worth putting on the roadmap, as the overhead involved with hundreds or thousands of HTTP requests is pretty significant. Imagine updating the price for thousands of products, without a bulk update endpoint, you'd have to make thousands of API calls, with at least 500ms overhead per request, vs. a single request for a bulk update.

Probably somewhat of a niche feature right now but as more people integrate with the API, bulk updates will be more important :smile_cat:

**Comment by lamosty** [comment]
@mikejolley Yes, it would be. However, as @maxrice pointed out, there is a huge overhead per each request. Imagine you have 2,500 products and need to create them one by one through the API. Same goes for updating them. This scenario could be applied to other parts of WooCommerce, such as orders. 

The code needed for mass create/update/etc should not be that big and maybe worth putting into future releases of WooCommerce. Thanks.
