### ISSUE TITLE
Changing an attribute's 'default sort order' doesn't update the order of existing attributes

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#7332]
1. Create an attribute with 'Custom Ordering'.
2. Add several attributes and put them in a random order.
3. Change the attribute's default sort order to 'Name' and save.

At this point, the attributes should be re-sorted into name order but they remain in customer order.

We should probably run an update when an attribute's settings are changed.

Ref: https://woothemes.zendesk.com/agent/tickets/255218

**Comment by mikejolley** [comment]
Not supposed to - the sort order is a display option. It will not do anything to the actual terms. 

If you view the column which lists the terms, you should see them reorder after changing this setting :)
