### ISSUE TITLE
[WC 2.3] Add new product is tax displayed as tax exclusive when tax settings are tax inclusive

### ISSUE THREAD

**Issue by om4james** [woothemes/woocommerce#7334]
When adding a new product in WooCommerce 2.3 when the store is configured to input and display prices including tax (10% GST in Australia), the product is displayed excluding tax.

Steps to reproduce:
1. Configure tax settings as per the screenshots below (tax inclusive with a 10% standard rate)
2. Add New Product, using $11 as the price (for example).
3. Save the product draft.
4. Preview the product.
5. Using WC 2.2.x, the product is displayed as $11. In WC 2.3.x the product is displayed as $10 (i.e. tax exclusive)

I noticed this issue after upgrading a store from WC 2.2.11 to WC 2.3 (master).

i.e. there is a change in behaviour between 2.2.x and 2.3.x.

I also tried saving the tax settings after noticing this, but it hasn't made a difference.

Existing product seem to display the same - it only seems to affect products that are added in WC 2.3.

Settings:
 ![wc-2 3-tax-settings1](https://cloud.githubusercontent.com/assets/108233/6101120/4ab448d2-b059-11e4-9561-383d59b94941.png) and 
![wc-2 3-tax-settings2](https://cloud.githubusercontent.com/assets/108233/6101127/6385d952-b059-11e4-9795-d5bc357b3f98.png)

**Comment by om4james** [comment]
In WC 2.2, I think if "Default Customer Address" was set to "No address", WooCommerce used to use the store's base location as the default address:

https://github.com/woothemes/woocommerce/blob/2.2/includes/class-wc-customer.php

However in WC 2.3, if "Default Customer Address" is set to "No address", then no location is used by default (which means the product gets displayed ex tax):

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-customer.php

**Comment by mikejolley** [comment]
Thats correct - no address will mean no tax is calculated. Lets change this setting to store base address on upgrade for existing users so that existing tax display is maintained.

**Comment by om4james** [comment]
Thanks @mikejolley, this is a good solution I think.

Preserves backwards compatibility with stores upgrading from 2.2.x to 2.3.

Thank you.
