### ISSUE TITLE
[WC 2.3] Customer emails not adhering to override templates.

### ISSUE THREAD

**Issue by sjeden** [woothemes/woocommerce#7336]
I have changed the email template:

customer-completed-order.php in twentyfourteen-child/woocommerce/emails/ folder

the system is not adhering to this and sending out the copy from the plugins directory.

**Comment by mikejolley** [comment]
Tried one via child theme - worked fine https://dl.dropboxusercontent.com/s/vl8eajs1atermoy/2015-02-10%20at%2011.40%202x.png?dl=0

**Comment by Amelandbor** [comment]
I'm having the same problem, only customer-compler-order is affected it seems. Is there a way to debug this?

**Comment by mikejolley** [comment]
Add something random to the email templates in core/theme, trigger the email, see which was sent. You may just have the override in the wrong place.

**Comment by Amelandbor** [comment]
Did that, core email is sent every time. Theme never.

**Comment by mikejolley** [comment]
Are you using child theme? Screenshot me your structure so I can see where you've put the template.

**Comment by Amelandbor** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/457756/6158449/bcfbea38-b24a-11e4-9208-47bfcce3cd44.png)

admin-new-order.php is working as expected.

**Comment by mikejolley** [comment]
To trigger this one must make an order go from processing to completed. I'm able to override this one and they all share identical code.

**Comment by Amelandbor** [comment]
When I change stuff in the core and resend the completed email it works. Just not for the template, which I completely copied.

**Comment by mikejolley** [comment]
Found the issue - patching soon.

**Comment by Amelandbor** [comment]
Thanks!

**Comment by jcrawford** [comment]
I am having this same issue while using a child theme

jcrawford@localhost:~/projects/heytix_wordpress/src/wp-content/themes/fitness-child/woocommerce/emails$ pwd
/home/jcrawford/projects/heytix_wordpress/src/wp-content/themes/fitness-child/woocommerce/emails
jcrawford@localhost:~/projects/heytix_wordpress/src/wp-content/themes/fitness-child/woocommerce/emails$ ls
customer-processing-order.php

I added a +1 in my template next to the label but it is not showing in the email.  If I add it to the core file in woocommerce then it works just fine.  What am I missing here?

**Comment by rolfnilsson** [comment]
Is this completely solved? I have the same problem, all my overrides works except for customer-completed-order.php. I am on Woocommerce 2.4.4.
