### ISSUE TITLE
[Feature Request] a filter for $product->get_rating_html() 

### ISSUE THREAD

**Issue by justnorris** [woothemes/woocommerce#7337]
https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L1087-L1105

I'd very much love to filter or completely replace that HTML.

A filter would be useful, because I wouldn't have to re-declare all of Woo Widgets just because I want to display the ratings differently.

**Comment by bryceadams** [comment]
@mikejolley this should probably be in a template file?

**Comment by justnorris** [comment]
Oh, that would be even better :)

**Comment by mikejolley** [comment]
Filter probably - moving to 2.4

**Comment by justnorris** [comment]
2.4 is a long time away. 
Can I help to speed it up a bit ? Like.... 2.3 ? I can submit a pull, it's a quite tiny modification with huge impact, that isn't going to break any backwards compatibility.

**Comment by justnorris** [comment]
Woooooo! :+1:
