### ISSUE TITLE
Custom Report Page In Woocoomerce Using Plugin

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#7340]
Hi,

Currently i am creating custom plugin. in which i need a custom report page which should looks like WC Report page.. now i can do this..

please help me for about past 1 month i  am search for it.. as i am not strong in WC. still searching

Soulition I found
`class-wc-admin-report.php` for report page template but in don't know how to use it

**Comment by bryceadams** [comment]
@technofreaky sorry but this is not the place to get support / custom dev help - only for fixing bugs. Look at https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-reports.php and the filters available like `woocommerce_admin_reports` /  `wc_admin_reports_path`, and try look for other free plugins that have extended the reports and see how they did it.
