### ISSUE TITLE
Order details not displaying in confirm email when checking out with Paypal standard

### ISSUE THREAD

**Issue by Spendare** [woothemes/woocommerce#7342]
When someone checks out with Paypal standard, the confirm email does not display all the items they have ordered.  It only happens with PP standard though, also using Payment Pro and this works fine.

We have verified all PP set up is correct and it seems admin confirmation email template used by default and all seems fine.  The problem seems to be that the data isn't been picked up from Paypal

**Comment by mikejolley** [comment]
The email from paypal you mean? Items are only sent to paypal if your store excludes tax, otherwise the order is sent as a whole. See the docs for details.

**Comment by Spendare** [comment]
Hi, no it's the order from Woocommerce / WP.  It includes some of the items but cuts the listing off short and does not show the shipping/delivery address etc.  See images, first one is from an order going through PP (with the info missing) the second one is an order using Payment Pro - this shows all the details  (Also thanks for the quick reply)
![order_confirm_email](https://cloud.githubusercontent.com/assets/10939338/6126402/3925e0ac-b118-11e4-933a-11d22f81b2c2.jpg)
![order_confirm_email_complete](https://cloud.githubusercontent.com/assets/10939338/6126419/71f68300-b118-11e4-8af8-f5722baad59c.jpg)

**Comment by mikejolley** [comment]
It looks like something is triggering an error at that point. Check your error logs - I don't think its related to gateway because those product rows are output elsewhere.
