### ISSUE TITLE
wc-refunded orders not calculated correctly on some reports page

### ISSUE THREAD

**Issue by LindsayHeydon** [woothemes/woocommerce#7343]
In your documentation here refunds are shown in Order Items after the refund as a positive (i.e. original order) then a minus figure to show the corresponding debit. http://docs.woothemes.com/document/woocommerce-refunds/ (see picture below)
![automatic-refund-final](https://cloud.githubusercontent.com/assets/10940158/6126749/a0061050-b11b-11e4-8221-62929093407c.png)
![order](https://cloud.githubusercontent.com/assets/10940158/6126921/4d574458-b11d-11e4-8993-937ec473e4fc.jpg)

I refunded automatically and everything is absolutely fine, except there are no red negative numbers in the item and delivery lines. Could this be making the Taxes reports wrong. For example I look for Taxes > Taxes by date > This Month and I have three orders/refunds. When I should really have four, three orders and one refund. 

![tax-report](https://cloud.githubusercontent.com/assets/10940158/6126693/0ad4f320-b11b-11e4-9c61-6aa7de98a093.jpg)

So to clarify on the 4th I had an order for £35.00 AND £55.00. The £55.00 was refunded on the 5th, but it looks like my total is £51.00, when in fact it should be 71+35+55-55 which is £106.... and the shipping should have a positive and negative figure (balance still 0) and also the tax...

This report does at least show the correct total of original sales (i.e. 71+35+55 = 161) and the refund itemised separately
![orders](https://cloud.githubusercontent.com/assets/10940158/6126852/7f22c288-b11c-11e4-84b3-28a00470260c.jpg)
...

**Comment by mikejolley** [comment]
Hi Lindsy

When you did the refund, did you just enter '55' in the refund total box, or did you refund qty 1 on the line item? If you don't do it per line item, it won't know how much of your refund is item cost and how much is tax, so the reports will be off.

If you delete that refund, and refund the lines (manually) it should correct your reports?

**Comment by LindsayHeydon** [comment]
Ah, it's my client actually and I think not. And watching the video http://docs.woothemes.com/document/woocommerce-refunds/ I missed where you had to do the line entries individually. So sincere apologies for wasting your time and I'll pass on to my client.  WooCommerce is brilliant by the way, the ecommerce software I recommend my clients to use :)

**Comment by mikejolley** [comment]
Thanks :)

**Comment by LindsayHeydon** [comment]
Actually, I did the manual refund as you suggested... and that has worked fine. BUT the original order on the 4th still doesn't seem to appear. That is Feb 4 there should be two orders 35.00 AND 55.00 (of course today the 55.00 has been refunded...) but the original still doesn't seem to be there?
![taxes - this month](https://cloud.githubusercontent.com/assets/10940158/6130822/bfb387c4-b13f-11e4-96bf-f06597fcba96.jpg)

**Comment by mikejolley** [comment]
Looking into this..

**Comment by LindsayHeydon** [comment]
Just to say I've updated and the new report is fine for Taxes by date... (many thanks)
![taxes by date](https://cloud.githubusercontent.com/assets/10940158/6166207/02e44bde-b2a6-11e4-8584-76aeeac74275.jpg)

But the Taxes by code is incorrect.
![taxes by code](https://cloud.githubusercontent.com/assets/10940158/6166217/20a73672-b2a6-11e4-9ff1-fef3c003d1a7.jpg)

Thanks, Lins
