### ISSUE TITLE
Comparing Sale Price to Price without noting type conversions in PHP

### ISSUE THREAD

**Issue by mtantawy** [woothemes/woocommerce#7344]
In the function that decides whether a product is on sale or no, its logic is as follow:
* if Sale Price NOT Equal Regular Price ($this->get_sale_price() != $this->get_regular_price())  
AND
* if Sale Price Equals Price ($this->get_sale_price() == $this->get_price())
Then the product is on sale.

The issue happens when a product has price of 0 'zero', and there is no sale price, then the second comparison becomes comparing
* Sale Price, which is an empty string as there is no sale price set  
To
* Price, which is 'zero' 0

Using == as comparison operator instead of === invokes type conversion, which converts empty string to number 0 and the comparison results in True and the item is marked as On Sale.

I think it is recommended to almost always use === instead of == unless type conversion is intended, which is not the case here, i believe.

What do you think? Should i make a fork and do a pull request?

**Comment by mikejolley** [comment]
I think you're correct on the second conditional - that check needs to ensure the main price is not the sale price, so === makes sense. I'll push in a fix.
