### ISSUE TITLE
add_order_note not using the filtered comment

### ISSUE THREAD

**Issue by vinnyusestrict** [woothemes/woocommerce#7349]
In `includes/abstracts/abstract-wc-order.php` method `add_order_note()` allows filtering of the commentdata before inserting the comment. However, when doing action `woocommerce_new_customer_note`, it passes the original note and disregards any changes to `$commentdata['comment_content]` that occurred in the `apply_filters` call.

Current code:
```php
if ( $is_customer_note ) {
			do_action( 'woocommerce_new_customer_note', array( 'order_id' => $this->id, 'customer_note' => $note ) );
		}`
```
It should be:
```php
if ( $is_customer_note ) {
			do_action( 'woocommerce_new_customer_note', array( 'order_id' => $this->id, 'customer_note' => $commentdata['comment_content'] ) );
		}
```

**Comment by vinnyusestrict** [comment]
Thanks! Any idea when this will go into production?

**Comment by claudiosmweb** [comment]
If all goes well... this week.

**Comment by vinnyusestrict** [comment]
Awesome. I added a workaround to my plugin and will make it version-dependent once the fix comes out. Thanks for the quick turnaround!
