### ISSUE TITLE
[2.3] Geolocation Transient garbage collection

### ISSUE THREAD

**Issue by om4james** [woothemes/woocommerce#7353]
The new Geolocation feature in 2.3 is likely to result in quite a few transients being added to the database, such as:

`geoip_123.123.123.123`
`external_ip_address_123.123.123.123`

For a busy store, this could result in thousands of `geop_*` transients being stored in the database (one for each unique IP address that visits the store).

Is it likely to be a problem given that [WordPress only garbage collects those when they are accessed](http://core.trac.wordpress.org/ticket/20316)?

At a bare minimum, I'm thinking the `System Status -> Clear Transients` button should also clear out these transients?

What do you think @mikejolley ?

**Comment by mikejolley** [comment]
I don't think this will be a major issue for users tbh:

1. external_ip_address will only affect you if running locally.
2. the geo_ip transient is only set if using API based geolocation

All other instances use the geolite DB and store to the session - no transient is used.

Both transients above are set to expire in 1 week, so the 'clear expired transients' button in system status will clear these if needed.

:)
