### ISSUE TITLE
Product category basis Permalinks

### ISSUE THREAD

**Issue by adnanoner** [woothemes/woocommerce#7357]
When shop/product-category/sample-product/ is selected as a base, for SEO and practical purposes I would expect the product:
**Product-name:** Clubmaster
**Product-category:** sunglasses
**Base:** Products

to have the following urls:
**product-url:** /products/sunglasses/clubmaster/
**product-category:** /products/product-category/
**base:** /products/

The product-url and base work as expected, however the product-category url is: /products/product-category/ . The (to me) expected url: /products/sunglasses/ produces a 404.

Is this the expected behaviour of woocommerce? And if so, isn't the behaviour proposed above favoured?

**Comment by mikejolley** [comment]
WordPress needs unique bases on permalinks in order to identify what is being shown.

[There are ways around it](https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=remove%20category%20base%20wordpress) but they can cause 404s, general bugs, and performance issues. Use at your own risk.

**Comment by adnanoner** [comment]
Thanks for getting back to me so quick. However I don't see how /products/sunglasses/ and /products/sunglasses/clubmaster are not both unique.
You should be able to distinguish the page is related to woocommerce (=products), it's category (=sunglasses) and it's according product (=clubmasters). Nothing really weird to expect right and the bases are not removed?

**Comment by mikejolley** [comment]
@adnanoner So you have a 'womens' category under sunglasses. That becomes `/products/subglasses/womens`. Is 'womens' a product or a category? Hence the issue, and why we won't be tackling this in core.

**Comment by adnanoner** [comment]
Thanks Mike, makes sense :+1: . I don't have subcategories and am migrating from wp-ecommerce so will have to see if I can make this work :)
