### ISSUE TITLE
WooCommerce Table Rate Shipping / WC 2.3.1 Fatal error:  Class name must be a valid object or a string in class-wc-shipping.php on line 143 

### ISSUE THREAD

**Issue by aplatform** [woothemes/woocommerce#7368]
`PHP Fatal error:  Class name must be a valid object or a string in /wp-content/plugins/woocommerce/includes/class-wc-shipping.php on line 143`

When viewing both cart and checkout pages.

Seems to be related to WooCommerce Table Rate Shipping v2.8.0, after deactivating this plugin and then reactivating the error went away.

This was after an update from WC 2.2.11 to  2.3.1.

Edit: Error also comes back after a save to shipping settings.

**Comment by claudiosmweb** [comment]
Issue in WooCommerce Table Rate Shipping.

Will be fixed in WooCommerce Table Rate Shipping v2.8.1.
