### ISSUE TITLE
TEMPLATES OVERRIDING THESE TEMPLATES WILL NEED TO UPDATE THEIR FILES.

### ISSUE THREAD

**Issue by pjv** [woothemes/woocommerce#7369]
... is confusing me.

First, is that intended to mean *Themes* overriding these templates...?

Second, which exact templates is this referring to? Filenames would be more handy here than the generic "order summary and payment section of the checkout".

**Comment by claudiosmweb** [comment]
You can see in the System Status!

**Comment by pjv** [comment]
Sorry, but I don't see how your answer answered the two questions I asked.

I do have some of my own code in some of the checkout template files which I am overriding in my child theme. How can I know whether the files I am overriding are ones that this change will affect?

**Comment by claudiosmweb** [comment]
Better now:

Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:
 
* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
