### ISSUE TITLE
v2.3.1: Select all check box not functioning on Orders page

### ISSUE THREAD

**Issue by alexholodak** [woothemes/woocommerce#7372]
I've tried Firefox and Chrome and both aren't working.

I just updated to WooCommerce v2.3.1 on Avada theme v3.7.3 on WordPress v4.1.
Orders page - select all check box is not working. However it does work on Coupons, Subscriptions, etc.

**Comment by claudiosmweb** [comment]
Look the console in your browser for errors.

**Comment by bentasm1** [comment]
Works fine here using Chrome.

**Comment by mikejolley** [comment]
Working here too - no doubt a theme/plugin conflict. If you go to View > Developer > Javascript console in chrome you can see what is causing the error and fix/remove it. Let us know what you find/which plugin was responsible.

Cheers
