### ISSUE TITLE
Woocommerce show the shop page on taxonomy archives

### ISSUE THREAD

**Issue by An-tonio** [woothemes/woocommerce#7373]
Woocommerce show the shop page on taxonomy archives when the term id is the same as the shop page id.

Woocommerce Version 2.3.1

How to reproduce:

- Install woocommerce plugin and create all woocommerce page
- Create a new term in any taxonomy (category, tag or custom) with the same wordpress id has the shop page id from woocommerce.
- Access to the term archive and you will get the shop page from woocommerce.

I fixed for my install as follow:

On file woocommerce/includes/class-wc-query.php I changed line 217 from:

`if ( $GLOBALS['wp_rewrite']->use_verbose_page_rules && isset( $q->queried_object_id ) && $q->queried_object_id === wc_get_page_id('shop') ) {`

to:

`if ( (!is_object($q->tax_query)) && $GLOBALS['wp_rewrite']->use_verbose_page_rules && isset( $q->queried_object_id ) && $q->queried_object_id === wc_get_page_id('shop') ) {`

**Comment by mikejolley** [comment]
This is not happening for me. What are your permalink settings?

**Comment by An-tonio** [comment]
My permalink settings:

- wordpress: /%postname%/
- Product category base: marketplace-category
- Product tag base: marketplace-tag
- Product permalink base: /marketplace

the others permalink settings are unset (category, tag...)

I think the problem maybe related with "use_verbose_page_rules" that is set to true when wordpress permalink is set to /%postname%/

**Comment by mikejolley** [comment]
Not happening here even with that setup and verbose rules on.

Also, if you var dump $q->tax_query, its actually an object on ALL pages. So this won't be a fix.

**Comment by An-tonio** [comment]
Hummm, estrange, not in my wordpress install, tax_query is not an object on pages only on taxonomy queries.

I will check.

Thanks.

**Comment by mikejolley** [comment]
You should test running twenty twelve and not other plugins to ensure you get accurate results.

**Comment by An-tonio** [comment]
Well, the problem is with the $q->queried_object_id, on all my queries it's set, on pages and on terms and this is why it get evaluated as true on the if. On a clean wordpress install with only woocommerce installed queried_object_id is only set for pages and post, not terms... but I don't find where this var is set for terms in wp_query on my custom wordpress.

Really estrange, I will try to find where this var is set,
Thanks for all.
