### ISSUE TITLE
Woocommerce 2.3.1 Shipping Via Flat Rate shows $0 when attempting to pay

### ISSUE THREAD

**Issue by jeasysehgal** [woothemes/woocommerce#7374]
Hi Mike,

Just updated woocommerce to the latest version 2.3.1, everything seems to be working alright, however when I add a product to the cart it shows the flat rate shipping we have setup on the site, proceed to checkout, it still shows the shipping rate, click on pay via PayPal and go to PayPal, the shipping via flat rate shows Shipping via Flat Rate Item price: $0.00Quantity: 1

Could you please help. www.Imperialswords.com

Thanks, Jeasy

------------------------------------------------------------------------------

### WordPress Environment ###

Home URL: http://imperialswords.com
Site URL: http://imperialswords.com
WC Version: 2.3.1
WC Database Version: 2.3.1
Log Directory Writable: ✔ /home/imperil5/public_html/wp-content/uploads/wc-logs/
WP Version: 4.1
WP Multisite: –
WP Memory Limit: 96 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.28
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.40
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
Remote Post: ✔
Remote Get: ✔

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (23) ###

Akismet: by Automattic – 3.0.4
All 404 Redirect  to Homepage: by Fakhri Alsadi – 1.3
BruteProtect: by Automattic – 2.4
ContestHopper for WordPress: by Webikon (Matúš Čerman) – 0.9.5
Jetpack by WordPress.com: by Automattic – 3.3.1
Monarch Plugin: by Elegant Themes – 1.2
Muut: by Muut
Inc. – 3.0.4

Optin Forms: by Codeleon – 1.1.4
RSS Image Feed: by Waldemar Stoffel – 4.1
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
Soundest: by Soundest – 1.3
Unsplash WP: by Darren Cooney – 1.1
WooCommerce auto added coupons: by Jos Koenis – 1.1.1
WooCommerce Smart Sale Badge: by Hugh Lashbrooke – 1.0
WooCommerce Sold Out Products: by Gerhard Potgieter – 1.0.4
Yotpo Social Reviews for Woocommerce: by Yotpo – 1.1.3
WooCommerce: by WooThemes – 2.3.1
Wordfence Security: by Wordfence – 5.3.6
WordPress PopUp: by WPMU DEV – 4.7.0.3
WordPress SEO: by Team Yoast – 1.7.1
WP-Optimize: by Ruhani Rabin – 1.8.9.7
Clef: by Clef – 2.2.9.1
WPDBSpringClean: by WPSolutions-HQ – 1.6

### Settings ###

API Enabled: ✔
Taxes Enabled: –
Shipping Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### WC Pages ###

Shop Base: #11 - /shop/
Cart: #12 - /cart/
Checkout: #13 - /checkout/
My Account: #14 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: StylezShoper
Version: 2.0
Author URL: http://www.graphicmonk.com/
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Found the issue. Fix here: https://github.com/woothemes/woocommerce/commit/afff86c0333b36496174b79c8106fde6cda823ba Will put that live tommorrow.
