### ISSUE TITLE
MySQL errrors with utf8mb4

### ISSUE THREAD

**Issue by korobochkin** [woothemes/woocommerce#7376]
Hi. I know what development is hard and utf8mb4 is not default charset for WordPress but we use it for saving Apple Emoji (4 bytes symbols which can't be saved in utf8). I'm not the MySQL guru. I'll be very thankful if you help (advices or something) to solve these issues. In server logs all time I see this errors:

```mysql
[24-Oct-2014 21:16:04 UTC] MySQL returns the error...
Specified key was too long; max key length is 1000 bytes в ответ на запрос 
	CREATE TABLE wp_woocommerce_tax_rate_locations (
	  location_id bigint(20) NOT NULL auto_increment,
	  location_code varchar(255) NOT NULL,
	  tax_rate_id bigint(20) NOT NULL,
	  location_type varchar(40) NOT NULL,
	  PRIMARY KEY  (location_id),
	  KEY tax_rate_id (tax_rate_id),
	  KEY location_type (location_type),
	  KEY location_type_code (location_type,location_code)
	) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, from activate_plugin, do_action('activate_woocommerce/woocommerce.php'), call_user_func_array, WC_Install->install, WC_Install->create_tables, dbDelta
```

This happening because `utf8mb4` needs `ROW_FORMAT = DYNAMIC` on create statement. I fixed it manually. 

Two another ones.

```mysql
[11-Feb-2015 23:47:26 UTC] Duplicate key name 'meta_key' в ответ на запрос ALTER TABLE wp_woocommerce_termmeta ADD KEY meta_key (meta_key), выполненный do_action('admin_init'), call_user_func_array, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta
[11-Feb-2015 23:47:26 UTC] Duplicate key name 'meta_key' в ответ на запрос ALTER TABLE wp_woocommerce_order_itemmeta ADD KEY meta_key (meta_key), выполненный do_action('admin_init'), call_user_func_array, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta`
```

MySQL settings:
* Default storage Engine = InnoDB
* File format = Barracuda
* InnoDB Large Prefix = TRUE

**Comment by claudiosmweb** [comment]
This is very specific to what you are doing.
And not really a matter of WooCommerce but with the database that you are changing.

**Comment by korobochkin** [comment]
WordPress core carring about utf8mb4 and your plugin not. @claudiosmweb you are not friendly

**Comment by mikejolley** [comment]
@korobochkin WC tables use whatever char set WordPress passes to it.

Plus WC uses dbdelta function for creating tables, which WP uses.

I see no 'ROW_FORMAT' in WP core either.

If you want to make a patch/pull request go ahead, but I don't think the majority of users need it.

**Comment by korobochkin** [comment]
`ROW_FORMAT` is not only solution for this issue but its the best trick for users — just one SQL query and all ok (and change some MySQL server settings on VPS to support long indexes — 767 vs 3072 with `innodb_large_prefix`). We talking about it in WordPress core slack channel. WordPress solution is decrease the indexes sizes for "big" indexes instead `ALTER TABLE` queries for WordPress 4.2.

https://wordpress.slack.com/archives/core/p1421942631001598
https://core.trac.wordpress.org/attachment/ticket/21212/21212-utf8mb4.4.diff
And you can join core channel in Slack and search `utf8mb4` — many talks about it.
