### ISSUE TITLE
2.3 empty cart after proceed to checkout

### ISSUE THREAD

**Issue by aburn1** [woothemes/woocommerce#7377]
I can add an item, but as soon as I do it takes me to an empty cart. I also had to adjust the PHP memory to 512 first, otherwise I'd get a white screen.

**Comment by mikejolley** [comment]
Please rule out plugin and theme conflicts (disable, test).

**Comment by aburn1** [comment]
I've disabled all plugins and have reinstalled the theme and woo immerse.
Same issue. It's your theme, so if there are conflicts are you familiar
with what they might be? Hosting provider has checked memory and sessions
and isn't sure what it could be. 2.2 was fine.

Thanks,

Adam



On Feb 12, 2015, at 3:59 AM, Mike Jolley <notifications@github.com> wrote:

Please rule out plugin and theme conflicts (disable, test).

—
Reply to this email directly or view it on GitHub
<https://github.com/woothemes/woocommerce/issues/7377#issuecomment-74059900>
.

**Comment by mikejolley** [comment]
*ALL* plugins? That includes WC plugins which may or may not have been updated. Use Twenty Twelve theme to test.

**Comment by aburn1** [comment]
Okay. It works with 2012. Then I went to go activate Canvas again and now I
have the White Screen of Death. How to I go about finding the Canvas
conflict? And wouldn't this support your themes out of the box? Thanks for
the help. Learning as I go here.

Adam

**Comment by mikejolley** [comment]
What version of canvas? There was an update yesterday I'm told.

**Comment by aburn1** [comment]
I have version 5.9.1. Didn't see an update yesterday. Right now the site is
down and I can't access the dashboard. The only plugins that are active are
WooCommerce and WooThemes Helper.

**Comment by mikejolley** [comment]
Ok - have you checked the server error logs to see what the actual error is yet?

**Comment by aburn1** [comment]
These are all the errors from today. Not sure where the unknown user is
coming from. and there is some code on my functions.php that calls the
WooCommerce tickets plugin, which is not active currently.

[12-Feb-2015 03:54:24 UTC] PHP Fatal error:  Call to undefined
function woo_get_dynamic_values() in
/home/becompas/public_html/wp-content/plugins/cx-mobile-menu-customizer-2.0/pootlepress-mobile-menu-manager-functions.php
on line 169
[12-Feb-2015 03:54:27 UTC] PHP Fatal error:  Call to undefined
function woo_get_dynamic_values() in
/home/becompas/public_html/wp-content/plugins/cx-mobile-menu-customizer-2.0/pootlepress-mobile-menu-manager-functions.php
on line 169
[12-Feb-2015 03:54:35 UTC] PHP Fatal error:  Call to undefined
function woo_get_dynamic_values() in
/home/becompas/public_html/wp-content/plugins/cx-mobile-menu-customizer-2.0/pootlepress-mobile-menu-manager-functions.php
on line 169
[12-Feb-2015 03:54:51 UTC] PHP Fatal error:  Call to undefined
function woo_get_dynamic_values() in
/home/becompas/public_html/wp-content/plugins/cx-mobile-menu-customizer-2.0/pootlepress-mobile-menu-manager-functions.php
on line 169
[12-Feb-2015 03:54:54 UTC] PHP Fatal error:  Call to undefined
function woo_get_dynamic_values() in
/home/becompas/public_html/wp-content/plugins/cx-mobile-menu-customizer-2.0/pootlepress-mobile-menu-manager-functions.php
on line 169
[12-Feb-2015 04:07:52 UTC] PHP Fatal error:  Call to undefined
function woo_get_dynamic_values() in
/home/becompas/public_html/wp-content/plugins/cx-mobile-menu-customizer-2.0/pootlepress-mobile-menu-manager-functions.php
on line 169
[12-Feb-2015 04:07:58 UTC] PHP Fatal error:  Call to undefined
function woo_get_dynamic_values() in
/home/becompas/public_html/wp-content/plugins/cx-mobile-menu-customizer-2.0/pootlepress-mobile-menu-manager-functions.php
on line 169
[12-Feb-2015 04:08:02 UTC] PHP Fatal error:  Call to undefined
function woo_get_dynamic_values() in
/home/becompas/public_html/wp-content/plugins/cx-mobile-menu-customizer-2.0/pootlepress-mobile-menu-manager-functions.php
on line 169
[12-Feb-2015 04:17:10 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 147
[12-Feb-2015 04:17:47 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 147
[12-Feb-2015 04:17:47 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 147
[12-Feb-2015 04:56:29 UTC] PHP Warning:  Unknown user in
/home/becompas/public_html/wp-content/plugins/jetpack/class.json-api-endpoints.php
on line 1050
[12-Feb-2015 04:56:29 UTC] PHP Warning:  Unknown user in
/home/becompas/public_html/wp-content/plugins/jetpack/class.json-api-endpoints.php
on line 1050
[12-Feb-2015 16:29:45 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:30:02 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:34:35 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:34:39 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:34:39 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:34:39 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:35:02 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:40:01 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:41:14 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148
[12-Feb-2015 16:43:16 UTC] PHP Fatal error:  Class 'TribeWooTickets'
not found in /home/becompas/public_html/wp-content/themes/canvas/functions.php
on line 148

**Comment by mikejolley** [comment]
Those are all from extensions. Can you remove your customisations from functions.php in case they are affecting this?

**Comment by aburn1** [comment]
Ahh okay. Canvas theme loads now and the cart loads. Thanks for the help!
I'll review my code.
