### ISSUE TITLE
 [2.3] Duplicate or triplicate product checkout and payment

### ISSUE THREAD

**Issue by soulpawa** [woothemes/woocommerce#7383]
I upgrade to 2.3 and now I have this problems:
![woocomerce1](https://cloud.githubusercontent.com/assets/6342029/6164244/82d1dfc2-b29d-11e4-93c2-e5551e06ee79.JPG)
![woocomerce2](https://cloud.githubusercontent.com/assets/6342029/6164243/82cfee60-b29d-11e4-8b70-b66a7dde6bd5.JPG)

**Comment by claudiosmweb** [comment]
Try with a WordPress default theme and check the System Status for deprecated templates.

**Comment by mikejolley** [comment]
Yep this is definitely theme related - look for an update from the author for 2.3.

**Comment by soulpawa** [comment]
It's true, updating the theme, problem resolved.
