### ISSUE TITLE
WooCommerce Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by ksujan** [woothemes/woocommerce#7384]
Having this issue after updating the woocommerce plugin today. Specifically I am getting this when I am going to activate the plugin. This is the exact error screenshot: https://docs.google.com/file/d/0B4BmEpV1_Fa7bFBvOFV4ckdoMUU/edit?usp=drivesdk

What I have tried:

1. Changing the WP_Memory_Limit value
2. Deleting and reinstalling WooCommerce
3. Changing the theme and trying to activate it again.

But no luck! Can anyone help me in fixing this ASAP?

**Comment by mikejolley** [comment]
Check your error log to see *what* fatal error. No doubt its an extension conflict.

**Comment by mikejolley** [comment]
reply on .org please, I notice you have a thread there too.
