### ISSUE TITLE
Product % Discount - Coupon

### ISSUE THREAD

**Issue by LindsayHeydon** [woothemes/woocommerce#7389]
Changes since latest update 2.3.2

When applying a coupon Product % Discount - if you've added BOTH Products and Product Categories (nothing in the Exclude sections btw) the Category is ignored at checkout and the discount will only apply to the individual Product.

If in your basket you only have something in there that belongs to the Category of the coupon you get the error 'Sorry, this coupon is not applicable to your basket contents.'

They work independently, just not together anymore.  They did work together before the update.

**Comment by mikejolley** [comment]
This logic is the same in 2.2.
