### ISSUE TITLE
After Upgrade to 2.3.2 - Order Admin Header Showing Multiple Fields Mis-Aligned - Settings Showing Multiple Fields

### ISSUE THREAD

**Issue by JoseRaffucci** [woothemes/woocommerce#7390]
After the upgrade to version 2.3.2 we started noticing some issues with the administration pages:

Order Screen Header:
When I search for a user at the bottom of the page aligned behind the admin menu I see the data that should be part of the drop down.
![Image of Yaktocat](http://i.imgur.com/aIqnQjR.png)

General Settings:
You can see here multiple fields for the same option:
![Image of Yaktocat](http://i.imgur.com/J8wayGk.png)

Product Settings:
Same as above more double fields for the same option:
![Image of Yaktocat](http://i.imgur.com/nDD8bz6.png)

I am not detecting any browser errors like javascript or missing resources.  This is a big headache for a live store, please advise.

**Comment by mikejolley** [comment]
Clear all caches - you're not seeing the new scripts.

**Comment by JoseRaffucci** [comment]
I have done this multiple times.  I will try so again.

**Comment by JoseRaffucci** [comment]
Thank you for the quick reply.

**Comment by JoseRaffucci** [comment]
I have cleared all caches, used 3 (Chrome, IE, Firefox) different browsers, disabled my caching engines.  Restarted PHP and NGINX.  

Cleared everything I could, we are still having the same issue.  
It also appears on the order page:
![Image of Yaktocat](http://i.imgur.com/264av1P.png)

What else could I try, could something have failed during the update?  

Do you need to see my status report?

**Comment by JoseRaffucci** [comment]
There was one place that I did not check, that was Cloudflare,  I purged the cache.  Problem solved.

I apologize for this annoyance...Thank you for your help.
