### ISSUE TITLE
Attribute names not displayed post upgrade to 2.3.2

### ISSUE THREAD

**Issue by edbloom** [woothemes/woocommerce#7391]
Hi there,

Seeing this issue on a few sites (not all though - i've done approx. 10 updates so far)

e.g. of issue

http://captivabeta.captivate.io/produkt/shark-snack-tee/

Variation attribute "Size" is displayed as "Pa_size"

I've switched the site to run TwentyTwelve and disabled all but a few minor plugins.

Any ideas?

Colm

**Comment by claudiosmweb** [comment]
I can't reproduce this issue.
Try disabling all plugins one by one until you find which this changing that.
Also look for outdated templates in your theme.

**Comment by edbloom** [comment]
all plugins now deactivated - except WooCommerce.
No template overrides present - as per the original submission - the theme is TwentyTwelve

**Comment by claudiosmweb** [comment]
Check the attribute name in the admin.

**Comment by mikejolley** [comment]
No issues here either. What version did you upgrade from, and have you 'saved' the attribute again in Products > Attributes to see if its that?

**Comment by edbloom** [comment]
hi @mikejolley - busy day for you :) Congrats to everyone on the 2.3 Release!

Upgraded path was 2.2.11 -> 2.3.0 -> 2.3.2

Issue occurred at 2.3.0 

Re-saving the attributes didn't work.

I have a backup of another site where the issue occurred which is still running 2.2.11. This site is is now on 2.3.2 and the issue is identical. 

I've dug deeper myself as a result and I think this is bigger issue than an incorrect label display.

The entire attribute set for the 2 sites are gone post upgrade! (i ran the WC DB update prompt that appeared post the original update).

Very worrying that the attributes would vanish.

What do you need from me to help resolve this one? I'm on colm@commercegurus.com if you want to take this elsewhere for db details etc.

Colm

**Comment by mikejolley** [comment]
You say the attributes were gone? Did you by any chance run the 'delete' in admin - this would run the uninstall script and cause attributes to be dropped.

The terms will still be there though so re-adding the attribute will link them up again.

**Comment by edbloom** [comment]
Mike you are a mind reader!
Solved :) 

I did delete and re-install a fresh instance as the update initially failed and showed a notice saying there might be issues like headers already sent etc.. so I decided a clean instance would be prudent. I didn't realise that attribute data was/is deleted upon uninstall. Is there a way of stopping that from happen?

Close this puppy :)

**Comment by mikejolley** [comment]
2.3.3 I've tweaked the uninstaller to only run if you go to System Status > Tools and check a box first.
