### ISSUE TITLE
Double cart button and payment method

### ISSUE THREAD

**Issue by maxoutweb** [woothemes/woocommerce#7392]
It seems that when I install the new version of woocommerce, I get a double place order button (cart page) and, on the next page, the checkout page, I get double payment method options. I had to remove the update until I figure out why. Any ideas?

**Comment by claudiosmweb** [comment]
This is an issue with your theme.

**Comment by mikejolley** [comment]
Please report this to your theme author and await their 2.3 update. Looks like some authors failed to update despite warnings.

**Comment by maxoutweb** [comment]
TY. Was afraid of that!

Philippe Deray
(412)726-0219
contact@maxoutweb.com
maxoutweb.com
Web developement & Digital Marketing
