### ISSUE TITLE
different checkout after upgrade ? 2.3.2

### ISSUE THREAD

**Issue by soulpawa** [woothemes/woocommerce#7393]
I attach screenshots, with how It was shown before, with just the billing adress on the left and my order on the right, now, appears shipping address on the right, and all my order on the bottom, and I have the same configuration. What could be?
![billing3](https://cloud.githubusercontent.com/assets/6342029/6170501/6cb4db8a-b2d5-11e4-9aa3-58dbe119112c.JPG)
![billing2](https://cloud.githubusercontent.com/assets/6342029/6170502/6cb692cc-b2d5-11e4-9636-40c4136c8e16.JPG)
![billing1](https://cloud.githubusercontent.com/assets/6342029/6170503/6cb6c99a-b2d5-11e4-9298-6c98f076c642.JPG)

**Comment by claudiosmweb** [comment]
Need to update your theme.

**Comment by soulpawa** [comment]
my theme it's already updated. to the last version availble ¿any other idea?
