### ISSUE TITLE
Quantity buttons

### ISSUE THREAD

**Issue by mathew07** [woothemes/woocommerce#7394]
I upgraded my woocommerce store but I don't wan't to resign from quantity plus/minus buttons. I installed plugin which you recomended (https://wordpress.org/plugins/woocommerce-quantity-increment/) but the quantity buttons doesn't looks like my old ones. You can see my old quantity button here http://www.dalbeshop.eu (this is my old testing site, but still with great quantity buttons). Now at my main site http://www.dalbeshop.pl I have really bad looking buttons and completely doesn't know how to fix them. I think that it is css settings issue, but I can't change it to the previous version (don't know how). Pleas help me achieve that, Mat.

**Comment by claudiosmweb** [comment]
Please, report this issue in https://github.com/woothemes/WooCommerce-Quantity-Increment
Thanks.
