### ISSUE TITLE
Update to #7343

### ISSUE THREAD

**Issue by LindsayHeydon** [woothemes/woocommerce#7397]
Just to say I've updated and the new report is fine for Taxes by date... (many thanks)
![taxes by date](https://cloud.githubusercontent.com/assets/10940158/6166260/840b7bba-b2a6-11e4-8853-a3533b9c320c.jpg)

But the Taxes by code is incorrect.
![taxes by code](https://cloud.githubusercontent.com/assets/10940158/6166217/20a73672-b2a6-11e4-9ff1-fef3c003d1a7.jpg)

Thanks, Lins

**Comment by mikejolley** [comment]
Actually this needs some more work.

Partial refunds need subtracting.
Partial refunds inside fully refunded orders need ignoring.
