### ISSUE TITLE
woocommerce_breadcrumb_home_url filter no longer working

### ISSUE THREAD

**Issue by Creekjumper** [woothemes/woocommerce#7398]
It looks like that the 2.3 update removed the `woocommerce_breadcrumb_home_url` filter. Is there a new method in place for changing the breadcrumb home url?

**Comment by Creekjumper** [comment]
It looks like this was just fixed in 5772356eb2d90c5890935b08e25ca68e81ee2394. Thanks!

**Comment by claudiosmweb** [comment]
;)
