### ISSUE TITLE
Cannot redeclare class WC_Email in 2.3.3

### ISSUE THREAD

**Issue by solepixel** [woothemes/woocommerce#7399]
When upgrading to 2.3.0 or 2.3.3, I keep getting this error:

Fatal error: Cannot redeclare class WC_Email in ~/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php on line 819

Is this happening to anyone else?

**Comment by claudiosmweb** [comment]
Have you tried to disable all other plugins?

**Comment by solepixel** [comment]
Not yet. I'll give it a shot, but a ran a check through wp-content folder for "class WC_Email" and didn't come up with any results other than what's in the WooCommerce plugin folder.

**Comment by claudiosmweb** [comment]
Maybe some plugin included the file twice. Because we are not having this problem and you were the first person report this so far.

**Comment by solepixel** [comment]
Roger. I'll let you know of my findings.

**Comment by mikejolley** [comment]
I'd expect this to be a plugin including it.

**Comment by Melaa24** [comment]
I just did the upgrade 4 days ago and am also receiving this error.  I have disabled all plugins and the error still persists.  I checked my file against the change Mike made and I am using the updated version.  Please help.

**Comment by Spreeuw** [comment]
I've had two reports of users with this problem, and both were the result of manual updates of WooCommerce via FTP: those users had both the old `woocommerce/includes/abstracts/abstract-wc-email.php` and the new `woocommerce/includes/emails/class-wc-email.php` files in their woocommerce folder, and I guess the autoloader would load them both. The error wouldn't pop up until WC_Email was called.

**Comment by Melaa24** [comment]
I figured out that my issue is a conflict with the woocommerce distance rate shipping plugin.  It took deactivating and reactivating everything numerous times before it was clear that was the cause.  Unfortunately I can't get rid of this one as its vital to the business.

**Comment by Spreeuw** [comment]
@Melaa24 the fact that deactivating this plugin gets rid of the error does not necessarily mean that it is the root cause - it may just be that this plugin is using the WC_Email class, and it doesn't load until you activate that plugin. I would suggest deleting the entire woocommerce plugin folder from your site and reinstalling/reuploading the latest version.

**Comment by solepixel** [comment]
I can confirm that my problem was in fact a conflicting plugin Distance Rate Shipping on CodeCanyon:
http://codecanyon.net/item/woocommerce-distance-rate-shipping/5586711

The latest version of Distance Rate Shipping resolved the issue.

Steps I took to update:
1. Delete "woocommerce" from plugins folder
2. Delete "woocommerce-distance-rate-shipping" from plugins folder
3. Copy updated "woocommerce" and "woocommerce-distance-rate-shipping" plugins into plugin directory.
4. Visit WP Admin and proceed to run WooCommece Database update.

Now both plugins are up-to-date and no errors or conflicting class declarations. Hope this helps someone.

**Comment by tivnet** [comment]
@claudiosmweb So, the `abstract-wc-email.php` is obsolete, and should be removed from the repo? Any plugins that were including it, show now include the `class-wc-email.php` - correct?
Thank you!

**Comment by claudiosmweb** [comment]
@tivnet we don't have the `abstract-wc-email.php` anymore:
https://github.com/woothemes/woocommerce/tree/master/includes/abstracts

And you don't need to include the `class-wc-email.php`, just use the `woocommerce_email_classes` fiter:

https://github.com/woothemes/woocommerce/blob/2726c270b8c075378b88ec6302d64fef0b25fbed/includes/class-wc-emails.php#L116-L139

**Comment by tivnet** [comment]
@claudiosmweb Thank you!

P.S. The abstract is still on WP.org and causing fatal errors in some cases:
http://plugins.svn.wordpress.org/woocommerce/tags/2.3.7/includes/abstracts/abstract-wc-email.php
and the fastest fix of old plugins and themes to me was to include the new class.

**Comment by claudiosmweb** [comment]
@tivnet good to know xD
I'll fix it.
Thanks.
