### ISSUE TITLE
Customer bug report: Quantity Input Arrows Missing

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#7400]
I've been seeing a lot of customer reports because their cart page and product pages have the arrows missing for the quantity selector. I ran a few test on my local sites and got the same results with Woo Themes. 

It seems that: 
`<input type="button" value="-" class="minus">`
and 
`<input type="button" value="+" class="plus">`
are no longer in the code. 

http://cld.wthms.co/1hhGZ

**Comment by ctalkington** [comment]
fyi it was noted on the dev blog,

http://develop.woothemes.com/woocommerce/2015/02/v2-3-handsome-hippo/
https://wordpress.org/plugins/woocommerce-quantity-increment/

**Comment by mikejolley** [comment]
Thanks Chris.
