### ISSUE TITLE
Products filtering by attributes from url not working in 2.3 version

### ISSUE THREAD

**Issue by alaarihan** [woothemes/woocommerce#7401]
I was developed a plugin to filter products by attributes and custom taxonomies and it was working well before version 2.3 the url was like this
http://mysite.me/product-category/clothes/?pa_color=green

this will show products in clothes category which have color attribute with value "green"

but now it just shows all products in clothes category without filtering

**Comment by mikejolley** [comment]
Ensure the archive is enabled for the attribute - edit the attribute and check the box. This is a new option.

**Comment by alaarihan** [comment]
Yes I'm sure, the archive option for the attribute is checked.

**Comment by mikejolley** [comment]
kk. This was only ever working due to a fluke and was never intended to be used like this. You will need to use the highlighted filter and set query_var to true for each attribute you want to filter like this http://glui.me/?i=fydr5fkyjmbuymp/2015-02-12_at_23.11.png/

**Comment by alaarihan** [comment]
Thank you for your help.
