### ISSUE TITLE
SCREENCAST ADDED: Product stuck on out of stock even after selecting in stock and updating, reverts back to Out of Stock

### ISSUE THREAD

**Issue by jeasysehgal** [woothemes/woocommerce#7402]
Hi Mike,

On our site: www.ImperialSwords.com and after updating to woocommerce 2.3.3 found a little bug which I am sure others will find soon. 

I have Enable stock management at product level selected and under Inventory tab for individual product, I go and change the Stock Qty from 0 to 1 and Stock status from Out of Stock to In Stock and update the product, The product is updated however the Stock status reverts back to Out of Stock, Have to manually do it again and on second time selecting Stock status from Out of Stock to In Stock and pressing Update, the Stock status updates. Not sure why in the first instance it is not doing so. 

Have attempted to use default theme and all other plugins switched off, same thing.

Your help would be appreciate.

Cheers,

Jeasy

**Comment by jeasysehgal** [comment]
Noticed that this issue only occurs on pre-existing products prior to the update. any new products created after the update work fine. Really need help with this.

**Comment by mikejolley** [comment]
Product type?

Just switched to 2.2, made the product out of stock, no checkbox, 0 stock.

Switched back to 2.3, did what you said, stock status stuck.

**Comment by jeasysehgal** [comment]
Hi Mike,

Product type simple. Product inventory enabled. Preexsisting product that was out of stock before updating to 2.3.3. The product is now back in stock and went and updated the inventory quantity, changed stock status from out of stock to in stock and updated product, product inventory quantiy updated, however, stock status reverts back to out of stock instead of staying on in stock.

Hope this helps. Am out of town till Monday. Will try and take snapshots to show what I mean if I am not being clear.

**Comment by jeasysehgal** [comment]
Hi Mike,

Any progress on this ticket yet. It causing a lot of double handling on our store with over 240 products and managing inventory stock every day.

WOuld really like to see a solution. Please help!

**Comment by jeasysehgal** [comment]
Hi Mike,

I have recorder a screencast of the issue. As you can see from the video, The first time you update a product status from Out of Stock to In Stock or Vice a versa, Woocommerce does not recognise it and reverts back, then on a second attempt, it registers it. Hope this helps to explain better. 

Here is the video link: https://www.dropbox.com/s/7uafwdeqe1evcqd/Product%20Status%20Not%20Updating.mp4?dl=0

Looking forward to hearing from you with a solution as it is affecting our work load tremendously.

**Comment by jeasysehgal** [comment]
Just reverted back to 2.2.11 and everything working fine, updated to 2.3.3 and the issue is back. not sure how to fix it????
