### ISSUE TITLE
Woocommerce 2.3.3 Coupons Misbehaving / not working as needed

### ISSUE THREAD

**Issue by jeasysehgal** [woothemes/woocommerce#7403]
Hi Mike,

Another Bug found. in Woocommerce 2.3.3, the coupons are not working properly.

I created a product % discount coupon to give 10% discount on purchases over $150, selected Individual use only and Exclude sale items and published, on testing in the shopping cart, no coupon is applied, if UnCheck Exclude sale items, then coupon is applied but also applies to sale items.

I don't wish to give further discount on items already on sale otherwise it voids the purpose of having a sale price for individual products.

Please Help.

www.ImperialSwords.com

**Comment by mikejolley** [comment]
This may have been fixed by the other coupon thing I patched in master, but I cannot replicate an issue with this one.

If exclude sale products is checked, only the non sale product gets discounted and it applies as normal.

If only sale goods are in the cart, the coupon won't apply.
