### ISSUE TITLE
Sidebar behaves strange

### ISSUE THREAD

**Issue by AdriOosterwijk** [woothemes/woocommerce#7405]
In my site (I'm developing locally) I have changed the behavior of the WooCommerce single product page. The site is in English and Dutch. I removed the product summary from the product area and I show it in the sidebar. Here is the code of the sidebar:

    	<?php if ( is_active_sidebar( 'sidebar-1' ) ) : ?>
		<div id="secondary" class="widget-area" role="complementary">
                
                <?php if ( !is_product() ) 
                    {

                    }
                
                else 
                    {?>                        
                        <aside id="product-summary" class="product-summary-custom widget">   
                        <?php if ( is_product() ) {?>
                        <h3 class="widget-title"><?php printf(__('buy this photo:')) ;?></h3>    
                        <?php do_action( 'woocommerce_single_product_summary' );?>
                        </aside>
                    <?php }
                    }
               
                    dynamic_sidebar( 'sidebar-1' ); ?>                        
 
		</div>
	<?php endif; ?>

The problem is that it shows only in the English site and when I change the language to Dutch it disappear. Changing back to English let it appear again.
The site is translated with use of the WPML plugin.

The first screenshot is how it should looks, the second one shows the wrong result.

![How it should look][1]
![How it looks -> the Buy This Photo box is gone][2]

This strange behavior is occurring since the update of Woocommerce to 2.2.3. Updated today. A quick fix is more than welcome.

  [1]: http://i.stack.imgur.com/Y2tNo.png
  [2]: http://i.stack.imgur.com/QBucr.png

**Comment by claudiosmweb** [comment]
This is a custom code and an issue with WPML.

**Comment by AdriOosterwijk** [comment]
Found it! The permalink settings for products were wrong in WPML. Why they are changed after the update? Really no idea!
