### ISSUE TITLE
Reports totals_grouped_by week + hour

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#7406]
Ties in with #7293, but it'd be nice to extend how reports are grouped by in 2.4.

Currently they are grouped by day, unless the 'interval' between two dates is greater than 3 (4) months, in which case they are grouped by month.

Week would be a nice addition, which can be done using the ISO-8601 week number of year (`date( 'W' )`).

Additionally, and this is more useful to larger stores but by hour. It may be overkill, but the argument is there for stores with huge volume, where they would like easily see their sales in an hour period. This could be returned like `yyyy-mm-dd-hh`, eg. `2015-02-15-22` (would be the 15th Feb 2015 at 10pm until 11pm).

This will be useful in the API too.

**Comment by mikejolley** [comment]
https://trello.com/c/tcYuPJwV/62-reports-totals-grouped-by-week-hour
