### ISSUE TITLE
after upgrade 2.3.3 UPGRADE button disappear from CART

### ISSUE THREAD

**Issue by soulpawa** [woothemes/woocommerce#7409]
![update](https://cloud.githubusercontent.com/assets/6342029/6186130/0a568050-b376-11e4-8023-8c9774b3549e.JPG)

And I continue the problems with checkout page,with my theme updated:
![updated](https://cloud.githubusercontent.com/assets/6342029/6186138/29500d50-b376-11e4-97f9-1b8bd4d65075.JPG)
![billing1](https://cloud.githubusercontent.com/assets/6342029/6186142/34fdd088-b376-11e4-9e49-101b604a174d.JPG)
![billing3](https://cloud.githubusercontent.com/assets/6342029/6186144/35013a84-b376-11e4-9ab6-57cc76a9559a.JPG)
![billing2](https://cloud.githubusercontent.com/assets/6342029/6186143/34ff5b1a-b376-11e4-9e6c-d12aff0b11d8.JPG)

**Comment by claudiosmweb** [comment]
Still a problem in your theme, Talk to the author of your theme or test with a different theme.

**Comment by soulpawa** [comment]
Ok thank you so much, I'm gonna ask them.
