### ISSUE TITLE
Fatal error after updating to WC 2.3.3

### ISSUE THREAD

**Issue by shaolinshaosson** [woothemes/woocommerce#7410]
I get this error when trying to access Webhooks in: page=wc-settings&tab=webhooks

Fatal error: Access level to WC_Admin_Webhooks_Table_List::get_views() must be public (as in class WP_List_Table) in ... wp-content/plugins/woocommerce/includes/admin/class-wc-admin-webhooks-table-list.php on line 309

**Comment by claudiosmweb** [comment]
I don't have this error and WordPress says it is protected:

https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-list-table.php#L345-L356
https://github.com/WordPress/WordPress/blob/9c69213f2b692e2889acd8c2bc150def15ce1c58/wp-admin/includes/class-wp-plugin-install-list-table.php#L207-L220
https://github.com/WordPress/WordPress/blob/62a197d6bff274ee7755d8e02e4ada0d9b05ac53/wp-admin/includes/class-wp-ms-users-list-table.php#L89-L103
https://github.com/WordPress/WordPress/blob/02a1f35ac8c6b65b9e96562e979294ec3f4926ed/wp-admin/includes/class-wp-media-list-table.php#L60-L90

This leads me to believe that you changed the code of your WordPress installation.

**Comment by shaolinshaosson** [comment]
Forgot to attach WP and WC version.
I use WC 2.3.3 and still using WP 3.9 and that was causing the error, since wp 3.9 in that class, doesn't type functions (public, protected, private)

**Comment by claudiosmweb** [comment]
Just upgraded our WP required version.
