### ISSUE TITLE
Cannot proceed to checkout when coupon applied

### ISSUE THREAD

**Issue by whitemint** [woothemes/woocommerce#7411]
The coupon is accepted perfectly, but when you click to pay this following error occurs and the customer cannot proceed any further unless you remove the discount:

•Mijireh error:{"total":["must add up correctly to the items, discount, tax and shipping costs"]}Mijireh_Order Object ( [_data:protected] => Array ( [partner_id] => woo [order_number] => [mode] => [status] => [order_date] => [ip_address] => [checkout_url] => [total] => 18 [return_url] => http://www.whitemint.co.uk/wc-api/WC_Gateway_Mijireh/ [items] => Array ( [0] => Array ( [name] => Order 2442 - Personalised Mr & Mrs Large Glass Kilner Jar x 1 [price] => 18.00 [quantity] => 1 [sku] => [total] => 18.00 ) ) [email] => maria_litras@hotmail.com [first_name] => Maria [last_name] => Litras [meta_data] => Array ( [wc_order_id] => 2442 ) [tax] => [shipping] => [discount] => 2 [shipping_address] => Array ( [first_name] => Maria [last_name] => Litras [street] => 89 Albert Embankment [city] => London [state_province] => London [zip_code] => EN4 8LE [country] => GB [company] => Macmillan Cancer Support [apt_suite] => [phone] => ) [billing_address] => Array ( [first_name] => Maria [last_name] => Litras [street] => 52 Ferney Road [city] => East Barnet [state_province] => Hertfordshire [zip_code] => EN4 8LE [country] => GB [company] => [apt_suite] => [phone] => 07443520342 ) [show_tax] => ) [_errors:protected] => Array ( ) )

**Comment by claudiosmweb** [comment]
Please report this issue in https://github.com/woothemes/woocommerce-gateway-mijireh-checkout/issues
And show me the coupon.

**Comment by whitemint** [comment]
Hi Claudio, I have added this to the page as requested.

Thanks


On 13 February 2015 at 11:59, Claudio Sanches <notifications@github.com>
wrote:

> Closed #7411 <https://github.com/woothemes/woocommerce/issues/7411>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/7411#event-235339425>.
>



-- 
Paul Cheshire
White Mint Contemporary Home Accessories & Gifts
www.whitemint.co.uk
