### ISSUE TITLE
Remove product issue

### ISSUE THREAD

**Issue by jmeyer2485** [woothemes/woocommerce#7415]
After adding a product to the cart then clicking the X to remove it, it redirects me to the Wordpress Login screen.

Then I got this error

wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 391

**Comment by mikejolley** [comment]
What is the full error message?

**Comment by jmeyer2485** [comment]
Fatal error: Call to a member function get_title() on a non-object in /home/PRIVATE/public_html/PRIVATE/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 391

I added 'Private' to my information, the error comes up after I try to delete product and it redirects me to the Wordpress login screen, then I click back and then try to delete product again.

**Comment by mikejolley** [comment]
Is this from cart screen or widget? And have you yet ruled out plugin and theme conflicts?

**Comment by jmeyer2485** [comment]
Yes, cart screen and I have the newest version of the theme from the dev (not in wp theme directory yet but emailed it to me) and turned off plugins and still have issue.

**Comment by mikejolley** [comment]
Could you quickly check with Twenty Twelve theme so I actually know if its reproducible.

**Comment by jmeyer2485** [comment]
Issue still happens on Twenty Twelve

**Comment by mikejolley** [comment]
In that file, if you do this:

`
var_dump( $product );
`

On line 390, what do you get?

**Comment by jmeyer2485** [comment]
Here is line 391, where do you want me to add that code?

wc_add_notice( sprintf( __( '%s removed. %sUndo?%s', 'woocommerce' ), $product->get_title(), '<a href="' . $undo . '">', '</a>' ) );

**Comment by jmeyer2485** [comment]
It crashes the site get this code when I add that code to line 390

object(WC_Product_Simple)#450 (6) { ["id"]=> int(2857) ["post"]=> object(WP_Post)#449 (24) { ["ID"]=> int(2857) ["post_author"]=> string(1) "2" ["post_date"]=> string(19) "2015-01-28 13:11:48" ["post_date_gmt"]=> string(19) "2015-01-28 19:11:48" ["post_content"]=> string(0) "" ["post_title"]=> string(44) "Apprentice 3 Piece Silicone Anal Trainer Set" ["post_excerpt"]=> string(730) "This set of 3 smooth, softly graduated plugs are great for gentle introduction into anal play. The ergonomic design mimics the natural curves of the body, and the firm yet soft silicone is comfortable enough for long term wear. The softly rounded tips and non-threatening size are perfect for training or working up to the next size. The suction cup base lets you stick each plug to a smooth, hard surface for hands-free insertion. Measurements: Small: 4 inches in total length, 3.5 insertable, 1 inch in diameter; Medium: 4.5 inches in total length, 4 insertable, 1.1 inches in diameter; Large: 5 inches in total length, 4.25 insertable, 1.25 inches in diameter Material: Silicone Color: Black Note: 3 plugs included " ["post_status"]=> string(7) "publish" ["comment_status"]=> string(4) "open" ["ping_status"]=> string(6) "closed" ["post_password"]=> string(0) "" ["post_name"]=> string(44) "apprentice-3-piece-silicone-anal-trainer-set" ["to_ping"]=> string(0) "" ["pinged"]=> string(0) "" ["post_modified"]=> string(19) "2015-01-28 13:11:48" ["post_modified_gmt"]=> string(19) "2015-01-28 19:11:48" ["post_content_filtered"]=> string(0) "" ["post_parent"]=> int(0) ["guid"]=> string(60) "http://www.MYURL.com/?post_type=product&p=2857" ["menu_order"]=> int(0) ["post_type"]=> string(7) "product" ["post_mime_type"]=> string(0) "" ["comment_count"]=> string(1) "0" ["filter"]=> string(3) "raw" } ["product_type"]=> string(6) "simple" ["dimensions":protected]=> string(0) "" ["shipping_class":protected]=> string(0) "" ["shipping_class_id":protected]=> int(0) }

**Comment by mikejolley** [comment]
Thats fine. Its supposed to return a product (get_title would work on that).

**Comment by jmeyer2485** [comment]
So should I edit the cod you gave me?

**Comment by mikejolley** [comment]
Remove it; I'll do some more digging.

**Comment by jmeyer2485** [comment]
OK sounds good.. I'll wait here lol

**Comment by mikejolley** [comment]
I cannot replicate this, but I can see a case where if remove_item was in the querystring with a valid nonce, but the cart item was not found, it could try to remove it again. Will wrap in a check.

**Comment by jmeyer2485** [comment]
Problem still happening.

**Comment by mikejolley** [comment]
@jmeyer2485 did you implement the code correctly?

**Comment by jmeyer2485** [comment]
Yes, I copied the whole code you had

**Comment by mikejolley** [comment]
Paste the error you get now?

**Comment by jmeyer2485** [comment]
No error, just keeps taking me back to the Wordpress login screen now

**Comment by mikejolley** [comment]
Where you var_dumped last time, see what this outputs:

```
var_dump( wp_get_referer() );
var_dump( WC()->cart->get_cart_url() );
exit;
```

**Comment by jmeyer2485** [comment]
bool(false) string(38) "http://www.bestxxxsextoys.â€‹com/cart/"

**Comment by mikejolley** [comment]
Was the link you made private valid? i.e. was it the correct cart link?

**Comment by jmeyer2485** [comment]
No I do that to not display the clients URL

**Comment by mikejolley** [comment]
I know - I mean, was the link it showed actually a working link :) Thats where it should send you - not the login page.

**Comment by jmeyer2485** [comment]
It just showed up a white page with that on it

**Comment by mikejolley** [comment]
I don't think we're on the same page.

I just wanted to confirm that your cart page URL was corrected, because after removing an item from the cart **thats where the code will send you**. If this isn't happening, some other code must be preventing this if as you say the link was valid. There do not appear to be issues with core itself.

**Comment by jmeyer2485** [comment]
'http://www.PRIVATE.com/cart/' is a valid url if that's what you mean, sorry for the confusion, do you just want access to the site?

**Comment by mikejolley** [comment]
Are you 100% that link was on the same domain as the rest of the site, because read the description of http://codex.wordpress.org/Function_Reference/wp_safe_redirect

You can try swapping the wp_safe_redirect to wp_redirect but there may still be a config issue.

**Comment by WordCommerce** [comment]
Is there a known plugin conflict? Because "undo link" doesn't appear in notice bar on my site.

**Comment by jmeyer2485** [comment]
I deactivated all plugins and still have the issue

**Comment by WordCommerce** [comment]
I found..
There is a conflict about the Yoast SEO plugin. 
Undo link appeared when I disable Yoast SEO.

**Comment by jmeyer2485** [comment]
I disabled Yoast and still have issue

**Comment by jmeyer2485** [comment]
I found that even if I enter the quantity to 0 and update the cart it also sends me to the Wordpress Login

**Comment by jmeyer2485** [comment]
@mikejolley I replaced the wp_safe_redirect to wp_redirect and it worked, but now the undo? link goes to wp login, can I change something else also to edit that?

**Comment by mikejolley** [comment]
@jmeyer2485 Are your site url and home url's the same in settings? wp_safe_redirect should work - you are redirecting to the same domain.

**Comment by jmeyer2485** [comment]
Yes, they are the same

**Comment by mikejolley** [comment]
Email me login details/possibly FTP. I need to see why http://codex.wordpress.org/Function_Reference/wp_validate_redirect is failing and whether its a bad site config, or a plugin issue. mike.j@woothemes.com

**Comment by jmeyer2485** [comment]
Set it over

**Comment by jmeyer2485** [comment]
@mikejolley Did you get the login info

**Comment by mikejolley** [comment]
@jmeyer2485 yes but email, I need to add some code to test and don't want to break the site :)

**Comment by jmeyer2485** [comment]
@mikejolley if you do just send me to original and I can edit it in ftp back to original.

**Comment by mikejolley** [comment]
@jmeyer2485 fixed. Don't ask me why, but your home_url was malformed and had a special char in. I retyped the home url and it fixed itself...

**Comment by jmeyer2485** [comment]
Now my site stuck in Maintenance mode

**Comment by mikejolley** [comment]
@jmeyer2485 no it's not... re-login. Thanks would be nice :p

**Comment by jmeyer2485** [comment]
So sorry, yes thank you VERY much! 

Where was that home_url messed up at?

Because it crashed my Jetpack plugin also.

**Comment by mikejolley** [comment]
No idea, maybe a copy paste from something.

**Comment by jmeyer2485** [comment]
@mikejolley Sorry, I mean where did you edit to make it work?

**Comment by mikejolley** [comment]
Settings > General.

**Comment by jmeyer2485** [comment]
@mikejolley OK Thanks again very much for all your time and help!

**Comment by jorisw** [comment]
In my case my Nginx config didn't pass through the query vars. See bottom of https://github.com/woocommerce/woocommerce/issues/8188
