### ISSUE TITLE
Wootique child theme broken after 2.3

### ISSUE THREAD

**Issue by EgbertJan** [woothemes/woocommerce#7419]
Hi, I noticed that my site looks quite different after 2.3.x upgrades. I have only a few css changes in a custom.css but they seen to be overridden by woocommerce-layout.css?ver=2.3.3:1. Is it now completely impossible to enter small tweaks/corrections in custom.css? Wootique is still supported with 2.3.x, is it? It fulfills the needs we have and I would rather not change to something else less suited.Is there a way to be in control again and that I can overrule the woocommerce-layout.css?
Egbert Jan, NL, speldorado.vandenbussche.nl

**Comment by michaeltieso** [comment]
This question might be best suited at our support channels but curious if you have the latest version of Wootique? And if so, can you update and see if that helps?

**Comment by EgbertJan** [comment]
That is fast! Hi Micheal.

Yes I'm fully up to date. I think Wootique is on 1.6.5 and I have not
seen many updates The framework was recently updates if I recall right.
I cloned the child from 1.4.1 but the style files point to the Wootique
directory. I see what I described on github in Chrome Developer tools.
several settings i did in the childs custom.css. are overruled bij the
woo.. css.

I've just performed a small test: I want 5 columns on the procuct
archive pages (categories that is in my case) and got a repeating line
of 3 and a line of 2. I changed the value 22.05 in the
woocommerce-layout.css to 16.95 and bingo: I have lines of 5 products
again! (this is on line 147 of the scss version but I edited in the
uglified css offcause.
 
I have the impression that the parent/child mechanism does not work
anymore. Alteast not for selfmade css in custom.css.

TNX
Egbert Jan

Michael Tieso schreef op 13-2-2015 om 22:04:

**Comment by EgbertJan** [comment]
Hi. I was wrong. Wootique was not up to date. For som reason I never got update triggersafter 1.6.5. I've "purchased" the free theme and now I have a acrivation key. Latest is 1.6.10 and is installed now. I will first rebuild the child theme. The proper way to do it was also changed according to the Woo codex..
CU
Egbert Jan

**Comment by michaeltieso** [comment]
Glad to hear you were able to fix this!

**Comment by EgbertJan** [comment]
Yes all seems back to normal with the new-style setup of the child
theme. My child theme was made with the knowledge at the time of version
Wootique 1.4.1. I'm now checking all settings to see if they are still
needed.
TNX
Egbert Jan

Michael Tieso schreef op 14-2-2015 om 19:46:
