### ISSUE TITLE
Use post_class() in product-category entry

### ISSUE THREAD

**Issue by wpexplorer** [woothemes/woocommerce#7421]
post_class is used for main loops (which is great) but it's not used in content-product_cat.php.

Thanks!

**Comment by mikejolley** [comment]
Because categories are not posts. post_class is designed for posts/post types only.

**Comment by mikejolley** [comment]
https://core.trac.wordpress.org/browser/tags/4.1/src/wp-includes/post-template.php#L405

**Comment by wpexplorer** [comment]
Then maybe we could at least add filter so the classes can be tweaked? Thanks. Copying the whole template part just to alter the product entry classes seems a bit much, but the only way atm.

**Comment by mikejolley** [comment]
yeah can add a filter - want to submit a pull request?
