### ISSUE TITLE
Latest 2.3.3 - Not showing plus and minus button in quantity!

### ISSUE THREAD

**Issue by Ansif** [woothemes/woocommerce#7425]
Hi,

I've just updated to the latest version of woocommerce, it's not showing a plus and minus buttons in single product page.

Before :
![screen shot 2015-02-14 at 1 07 41 pm](https://cloud.githubusercontent.com/assets/5621180/6198976/e44b1940-b44a-11e4-9e57-0cf7925d9a5c.png)

Now :
![screen shot 2015-02-14 at 1 08 30 pm](https://cloud.githubusercontent.com/assets/5621180/6198980/ed2a9126-b44a-11e4-8557-d4d6685f730e.png)

Thanks,
Ansif

**Comment by kloon** [comment]
https://wordpress.org/plugins/woocommerce-quantity-increment/

**Comment by saqibsarwar** [comment]
Thanks Kaloon, 

This is really helpful.

Regards
