### ISSUE TITLE
Add to cart in the internet explorer

### ISSUE THREAD

**Issue by Track77** [woothemes/woocommerce#7429]
The function "Add to cart" did not work in the internet explorer (v 11.0.96900.17358)
Steps to reproduce
1) Go to product page
2) Add to cart
3) Go to cart page - the cart is empty
4) Refresh page for see the product.

P.S. Any problems in the Chrome 
And any problems in the Woo version 2.2 

### WordPress Environment ###

Home URL: http://3ddkstudio.com
Site URL: http://3ddkstudio.com
WC Version: 2.3.3
WC Database Version: 2.3.3
Log Directory Writable: ✔ D:\My Documents\My Web Sites\3ddkstudio.com/wp-content/uploads/wc-logs/
WP Version: 4.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: ✔
Language: ru_RU

### Server Environment ###

Server Info: Apache/2.4.10 (Win32)
PHP Version: 5.6.3
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.35
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
Удалить запись: ✔
Удалённое получение: ✔

### Server Locale ###

decimal_point: .
thousands_sep: Н/Д
mon_decimal_point: Н/Д
mon_thousands_sep: Н/Д

### Active Plugins (58) ###

AddQuicktag: от Frank Bültge – 2.4.1
Custom Admin-Bar Favorites: от Robert Wise – 0.1
Admin Menu Editor: от Janis Elsts – 1.4.2
All In One SEO Pack: от Michael Torbert – 2.2.5.1
Analytics360: от Crowd Favorite – 1.3.2
BackUpWordPress: от Human Made Limited – 100.2.3
Basic User Avatars: от Jared Atchison – 1.0.0
WP Check No JavaScript or Cookie: от Tips and Tricks HQ – 1.2
Display Widgets: от Strategy11 – 2.03
Advanced Download Counter: от Andy Staines – 1.3
Duplicate Post: от Enrico Battocchi – 2.6
FCC Ribbon Manager: от Fullo – 0.3
Flexible FAQ: от S. Bage – 0.2
Google XML Sitemaps: от Arne Brachhold – 4.0.8
Improved User Search in Backend: от David Stöckl – 1.2.6
Link Library: от Yannick Lefebvre – 5.9.2.2
Login LockDown: от Michael VanDeMar – v1.6.1
Logo Slider: от Enigma Digital – 2.1
Мета слайдер: от Matcha Labs – 3.2.1
My Link Order: от Andrew Charlton – 3.5
New User Email Setup: от Alex Cragg – 0.5.2
Feed by Mail Extension for Newsletter: от Stefano Lissa – 2.2.0
Newsletter Popup Extension: от Stefano Lissa – 2.2.0
Newsletter Reports Extension: от Stefano Lissa – 2.2.1
Newsletter: от Stefano Lissa – 3.6.7
Plugin Notes: от Mohammad Jangda – 1.1
Post Tags and Categories for Pages: от curtismchale – 1.3
Redirection: от John Godley – 2.3.14
Search Regex: от John Godley – 1.4.15
Search Replace in files: от  –
Simple Ajax Contact Form (SACF): от H3 Fuzion – 1.0.4
Simple:Press: от Andy Staines & Steve Klasen – 5.5.4
Simple Yearly Archive: от Oliver Schlöbe – 1.7.1.2
Smart Manager for e-Commerce: от Store Apps – 3.9.2
Testimonials Widget: от Michael Cannon – 3.15.1(2.15.1)
To-Dos: от Johan Ström (Updated: Alex Kramer) – 1.2
Ultimate Tag Cloud Widget: от Rickard Andersson – 2.7.2
Редактор ролей пользователей: от Vladimir Garagulya – 4.18.2
User Switching: от John Blackbourn – 1.0.3
WooCommerce Admin Bar Addition: от David Decker - DECKERWEB – 2.7.0
WooCommerce Bulk Discount: от Rene Puchinger – 2.5.1
WooCommerce Cross-Sale Discount: от Alex Kramer – 0.2
WooCommerce Currency Converter Widget: от Alex Kramer – 0.4.2 – 1.3.1 доступно
WooCommerce Custom Product Tabs Lite: от SkyVerge – 2.2.5
WooCommerce Grid / List toggle: от jameskoster – 0.4.0
WooCommerce New Product Badge: от jameskoster – 0.3.0
WooCommerce Prices: от sydcode – 1.0.1
Woocommerce Products Per Page: от Jeroen Sormani – 1.1.4
WooCommerce Sales by Country: от MH Mithu – 1.1.0
WooCommerce: от WooThemes – 2.3.3
WP Code Syntax Highlighter: от Dennis Bri – 1.1
WP Easy Uploader: от Chris Jean – 1.0.11
WP Editarea: от Takien – 0.4
jQuery lazy load plugin: от Andrew Ng – v0.21
WP Mantis: от Niklas Rother – 1.2.2
WP-SimpleViewer: от SimpleViewer Inc. – 2.3.2.4
WP User Frontend: от Tareq Hasan – 1.3.2
WP YouTube Lyte: от Frank Goossens (futtta) – 1.5.0

### Settings ###

API Enabled: ✔
Taxes Enabled: –
Shipping Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Ссылка магазина: #65 - /shop/
Корзина: #66 - /cart/
Оплата: #67 - /checkout/
Мой профиль: #68 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: WP Opulus Child
Version: 2.4.1
Author URL: http://nimbusthemes.com/
Child Theme: ✔
Parent Theme Name: WP Opulus
Parent Theme Version: 2.5.9
Parent Theme Author URL: http://nimbusthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: kstudio/woocommerce/cart\cross-sells.php
kstudio/woocommerce/emails\email-footer.php
kstudio/woocommerce/emails\email-header.php версия 2.0.0 устарела. Версия ядра 2.3.0
kstudio/woocommerce/myaccount\form-login.php
kstudio/woocommerce/single-product\meta.php
kstudio/woocommerce/single-product\price.php
kstudio/woocommerce/single-product\related.php
kstudio/woocommerce/single-product\title.php
kstudio/woocommerce/single-product\up-sells.php

: Узнать
как обновить устаревшие темы

**Comment by technofreaky** [comment]
Hi,

Do you get any js error in Internet Explorer .?
I tried to open your website here. but its not working.

***Try The Following.***
Try Activating Default WordPress Twenty Fifteen Theme / Fourteen Theme And Try To Added A Product To Cart if this work's then there is some js issue in your **kstudio** theme

**Comment by mikejolley** [comment]
Please do this before raising an issue https://wordpress.org/support/topic/how-to-debug-issues-after-updates?replies=1 - it's likely the theme or a plugin not being fully compatible yet. Thanks!
