### ISSUE TITLE
Unable To Get Orders Using WP_Query

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#7430]
Hi,

I am trying to get shop orders using WP_Query. in WordPress. but it returns only null. i have even tried reinstalling WooCommerce & WordPress. But no use

My Code
`$query = new WP_Query( array('post_type'=>'shop_order'));
 $post = $query->the_post(); var_dump($post); `

**Comment by mikejolley** [comment]
You need to add "post_status" to your query and retrieve orders with an order status (default is publish which orders don't use).
