### ISSUE TITLE
Easier way to get order counts for every order status

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#7433]
At the moment if you want to get the order count for each order status (in core, 7 of them), you'd have to make 7 API calls I believe, each time filtering the post_status, which is a bit overkill.

We could extend the orders/count endpoint to return an array of all statuses and their order counts.

**Comment by maxrice** [comment]
:+1: I think the best way to do this is to make it so the `any` status returns an array of all statuses and their counts, rather than just a pure count.

**Comment by bryceadams** [comment]
@maxrice excellent idea, I'll add it today.
