### ISSUE TITLE
Nginx Errors

### ISSUE THREAD

**Issue by benhartwich** [woothemes/woocommerce#7434]
Hi,

I´ve got the following nginx errors at my log. If you need further information please ask for it.
 [error] 12466#0: *104976 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function get() on a non-object in /var/website/wp-content/plugins/woocommerce/includes/class-wc-cart.php on line 208" while reading response header from upstream, request: "POST /wp-cron.php?doing_wp_cron=1424018495.5671238899230957031250 HTTP/1.0"

**Comment by mikejolley** [comment]
You have a plugin/theme calling the cart before 'init'. Thus the session object doesn't exist yet.

Check your code/disable plugins to find the exact cause.
