### ISSUE TITLE
Repeated menu items everywhere when used "wp_nav_menu"

### ISSUE THREAD

**Issue by arl1nd** [woothemes/woocommerce#7445]
Here is the this issue in words:

http://demo.oxygentheme.com/my-account/lost-password/

This issue happens also to other pages and other themes and was introduced in WooCommerce v2.3.x I guess

**Comment by mikejolley** [comment]
This is not a core bug, and cannot be replicated my side, but I know what code will be doing it:

`
function wc_page_endpoint_title( $title ) {
	if ( is_main_query() && in_the_loop() && is_page() && is_wc_endpoint_url() ) {
		$endpoint = WC()->query->get_current_endpoint();
		if ( $endpoint_title = WC()->query->get_endpoint_title( $endpoint ) ) {
			$title = $endpoint_title;
		}
	}
	return $title;
}
add_filter( 'the_title', 'wc_page_endpoint_title' );
`

Something on your site, possibly a plugin if you say it happens in Twenty Twelve theme, is making those conditionals return true.

is_main_query() and in_the_loop() should only return true for the main content area (so the main page title is changed and nothing else). In your case, these are returning true too early before the nav is displayed.

Temp fix while you figure out whats doing this, would be to add:

`
remove_filter( 'the_title', 'wc_page_endpoint_title' );
`

**Comment by arl1nd** [comment]
Hi Mike

Thanks for send the fix, it is strange why this doesn't work on my side, but I think its better to wait for few days/weeks and see if other themes are having the same issue and provide a patch for this, because I normally call wp_nav_menu function in the header.php so I don't know why this is being applied to menu items.

Cheers
