### ISSUE TITLE
Enqueue WooCommerce Style And Script In Custom Admin Page

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#7448]
Is there any possibility to enqueue Style and script which loads in WooCommerce Order Listing Page. in a custom admin page ?

**Comment by mikejolley** [comment]
Yes; define your screen's id as a WC screen. woocommerce_screen_ids filter.

**Comment by technofreaky** [comment]
@mikejolley 

I have added below code. in my plugin but this dint work. ? what to do
`
 add_filter('woocommerce_screen_ids',array($this,'set_wc_screen_ids'));
public function set_wc_screen_ids($screen){
        $screen[] = 'edit-donation';
        return $screen;
    }`

`set_current_screen('edit-donation' );`

**Comment by technofreaky** [comment]
Its. Working Please Close This

i have just removed set_current_screen and added the original screen id in wc screen id filter
