### ISSUE TITLE
Bug: Restocking items in a refund doesn't check to see if the refund was successful

### ISSUE THREAD

**Issue by bekarice** [woothemes/woocommerce#7449]
It looks like refunds are checking for a `WP_Error`, but after they've already restocked items: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-ajax.php#L1882

When a refund via credit card is submitted, the items are still restocked even if the refund fails. Example order notes for reference:
![](https://cldup.com/JQUU3BF_5s.png)

It seems that this should check for a successful refund first, and then restock items once the refund is confirmed to be successful.

**Comment by maxrice** [comment]
@bekarice please deactivate all plugins and switch to 2012 and let us know if this issue persists...![troll](https://pbs.twimg.com/profile_images/2327630295/avatar_6feb8634e3d0_128.png)

**Comment by bekarice** [comment]
<img src="http://cdn.alltheragefaces.com/img/faces/png/angry-dark-stare.png" alt="stare" width="175" height="auto">

**Comment by maxrice** [comment]
@mikejolley one minor change here I think worth making is the moving [this line](https://github.com/woothemes/woocommerce/blob/4feb5fbda99ed5e62889a1b36bcaeebf53e0e1cc/includes/class-wc-ajax.php#L1909) after the API result check.

**Comment by mikejolley** [comment]
@maxrice Unsure about that one - a gateway can do something after success or failure where it is, otherwise it would be success only.

**Comment by maxrice** [comment]
maybe two actions? the action signature `woocommerce_refund_processed` implies that the refund was indeed processed, but really it may not have if there was a gateway error. something like `woocommerce_api_refund_attempted` and `woocommerce_api_refund_processed` could work :smile_cat:

**Comment by mikejolley** [comment]
Even if it fails it was still processed kind of :p 

I found one plugin using it in this way; follow up emails. It sends a different follow up on success or fail.

**Comment by maxrice** [comment]
a fair point :)
