### ISSUE TITLE
2.2.3 upgrade to 3.3 Product Bundles Broken

### ISSUE THREAD

**Issue by clay123** [woothemes/woocommerce#7450]
While updating a clients website from 2.2.3 to 3.3 we realized that we are no longer able to add new products to create product bundles.

**Comment by bryceadams** [comment]
Make sure you're running the latest WooCommerce & latest Product Bundles (http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-product-bundles/changelog.txt). If there's still an issue, please open an official support ticket - this is just for core bug reports.
