### ISSUE TITLE
Product Visibility No Longer Works After Upgrading to 2.3

### ISSUE THREAD

**Issue by adamfisher** [woothemes/woocommerce#7452]
I upgraded WooCommerce to version 2.3 and when i go to edit a product, the Edit link next to visibility no longer works. I want to set a product's visibility to private.

![image](https://cloud.githubusercontent.com/assets/1834711/6222740/89ad2e86-b627-11e4-9c57-d71f3e5cf738.png)

**Comment by bryceadams** [comment]
I just tested with 2.3.3 and it works:

![see screen shot](http://cld.wthms.co/1loxl+)

Can you please switch to the default Twenty Twelve theme and also deactivate all plugins that aren't WooCommerce official ones and then try it again.

**Comment by adamfisher** [comment]
The culprit appears to be WooCommerce Subscriptions v1.5.11.

**Comment by bryceadams** [comment]
Time to update to 1.5.17 then :) http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-subscriptions/changelog.txt
