### ISSUE TITLE
In render_product_columns(), get_image() uses 'thumbnail'

### ISSUE THREAD

**Issue by qkevinto** [woothemes/woocommerce#7453]
Commit ed1d64fc632b41201b733d35e0bbd26273cc5590 uses `thumbnail` size to retrieve thumbnail image in  `get_image( 'thumbnail' )`. This causes thumbnails in the post type's product column to reference WordPress' thumbnail size (Settings > Media > Thumbnail Size).

Is this desirable? Post Thumbnails can be in different proportions to product's thumbnails, i.e. post thumbnails can be elongated landscape.

**Comment by bryceadams** [comment]
Typically the post thumbnail is quite small like 50x50 right?

**Comment by qkevinto** [comment]
Yeah, in most causes it could be. Though considering it's user configurable and could be of any value, do you think there is a better way to determine a thumbnail size? Maybe we could reference WooCommerce's product thumbnail sizes?

**Comment by mikejolley** [comment]
I don't think this is important/needs patching. You could say the same for any size defined in WP - even our product thumbnail sizes are user configurable.

The CSS will scale them anyway to ensure the layout remains intact.
