### ISSUE TITLE
class-wc-tracker.php using deprecated get_theme_data()

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#7456]
was deprecated in WP version 3.4. Use `wp_get_theme()`

**Comment by kloon** [comment]
@helgatheviking you'll see I do a version check for 3.4 here https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-tracker.php#L134-L138

Just to ensure backward compatibility with older versions of WP :smile:

**Comment by helgatheviking** [comment]
is there a face!palm emoticon? ;)

**Comment by kloon** [comment]
haha, no problem
