### ISSUE TITLE
Yoast SEO Conflict

### ISSUE THREAD

**Issue by WordCommerce** [woothemes/woocommerce#7457]
Undo link doesn't appear on cart page when I activated the Yoast SEO plugin.

**Comment by mikejolley** [comment]
Enabling SEO did not affect the undo link on my install. 

See if you can narrow down to a setting or anything - I tried on a clean install.

Thanks

**Comment by WordCommerce** [comment]
Thanks for the suggestion Mike
The following setting prevents undo link:

![undo](https://cloud.githubusercontent.com/assets/9597926/6230566/69b17658-b6c9-11e4-9038-0676b3b7158d.jpg)

**Comment by mikejolley** [comment]
Checking...

**Comment by mikejolley** [comment]
@WordCommerce Thats enabled by default - its not affecting my install..

**Comment by n13s013** [comment]
I don't know Mike.
It is effecting my install.
Anyway I already disable it.

2015-02-17 18:24 GMT+02:00 Mike Jolley <notifications@github.com>:
