### ISSUE TITLE
REST API - HTTP + JavaScript + GET: Cannot pass query parameters such as filters.

### ISSUE THREAD

**Issue by gongiskhan** [woothemes/woocommerce#7460]
I'm trying to get a list of products from the REST API using JavaScript, as I need to do this from a mobile app, so can't use the PHP clients out there.

I can get it using a GET to http://www.bestripvouchers.com/wc-api/v2/products
Note I don't have SSL, so I'm passing the OAuth parameters also, which works fine.

Now, my problem is, I cannot pass a filter query parameter (filter[limit]=50) over HTTP GET, because the OAuth autorization does not allow for extra parameters other than the ones for OAuth.

So I only get 10 products and that's it. I'm stuck...

I'm guessing your answer is that there is no solution for this at present. So what I would ask you to help me with, is understanding how I can change the code in class-wc-api-authentication.php, in order to accept query parameters in this scenario (HTTP+GET), as a temporary solution.

Or if you can think of another way for me to get more than 10 products (again, in the given scenario), that works too.

**Comment by claudiosmweb** [comment]
Please, read: http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

You can pass filters too.

**Comment by gongiskhan** [comment]
Hi Claudios,

Thanks for the quick reply, but what the documentation states is that OAuth query parameters are accepted. What it omits is that only OAuth parameters are accepted. Which seems to be the case.

I don't believe it's a problem with the parameter byte-order as I've tried in several positions and it would only make sense for the order to be used by the authentication class.

It's easy to see the issue... 
If you hit :

http://www.bestripvouchers.com/wc-api/v2/products?oauth_consumer_key=ck_c70620672ff7b41822521d0d4cecaf54&oauth_nonce=1.059589838251844&oauth_signature=T%252F9HeyLXosCLSU1BNt8TLlf8mOg%253D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1424184997

(you might have to update the timestamp)

you can see the products. But if you hit it with (only including the filter parameter):

http://www.bestripvouchers.com/wc-api/v2/products?oauth_consumer_key=ck_c70620672ff7b41822521d0d4cecaf54&oauth_nonce=0.6705808136718814&oauth_signature=qbTcjIb9%252F1FnPcJ089rInWQVykY%253D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1424185045&filter[limit]=50

you get unauthorized:

{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}

And really, this is not a case of a ninja developer messing with the code and breaking it. I have not changed anything in the woo-commerce plugin.

**Comment by claudiosmweb** [comment]
Tested and works very well!

For example:
```
http://test.woo.com/wc-api/v2/orders?filter%5Blimit%5D=20&oauth_consumer_key=ck_39880809110351d7cbf8f37b20af5deb&oauth_timestamp=1424185613&oauth_nonce=9e60b6c66c544f76dbe36de8743cddd6bd517d82&oauth_signature_method=HMAC-SHA256&oauth_signature=liaX09r%2Bo070og43FTLwCQITWEh0mFrVy03VM4D4kHw%3D
```

You can get some tools to help you in your docs:

![screenshot from 2015-02-17 13 08 35](https://cloud.githubusercontent.com/assets/1264099/6230350/2d3e53da-b6a6-11e4-94eb-7dead7bd3f72.png)

Try: http://developer.linkedinlabs.com/oauth-test/

**Comment by maxrice** [comment]
@gongiskhan if you're seeing an invalid signature message and you're sure that you're generating it correctly client-side, it's probably an issue with your server adding something to the request URL. Try using the [PHP client library](https://github.com/kloon/WooCommerce-REST-API-Client-Library) and if that works, then you know it's a server issue.

**Comment by gongiskhan** [comment]
Sorry I was away for a while.

It seems like it is indeed something I'm doing wrong. The PHP client library also works with filters (although it seems to be using v1...) .

Thank you both and sorry for wasting your time raising an issue. I hate when people do that without trying everything they can. But really I thought I did.

I'll keep trying to figure out what I'm doing wrong and post it back here just for future reference.

Cheers,
Goncalo

**Comment by maxrice** [comment]
@gongiskhan no worries, signature issues are very challenging to troubleshoot and it can take a bit of time to get the code just right :)

**Comment by claudiosmweb** [comment]
No worries ;)

**Comment by gongiskhan** [comment]
Right, so here's the working code.
I'm now placing the extra query parameter (in this case the filter) in the object for generating the signature.

```javascript
    jQuery(document).ready(function(){
        var oauth = new OAuth({
            consumer: {
                public: 'ck_3163b...',
                secret: 'cs_e24d3...'
            },
            signature_method: 'HMAC-SHA1'
        });

        //overide for testing only !!!
        oauth.getTimeStamp = function() {
            return Math.round(+new Date()/1000);
        };

        //overide for testing only !!!
        oauth.getNonce = function(length) {
            return Math.random()*1.2483;
        };

        var request = {
	    url: 'http://www.bestripvouchers.com/wc-api/v2/products',
            method: 'GET'
        };

        var oauth_data = {
            oauth_consumer_key: oauth.consumer.public,
            oauth_nonce: oauth.getNonce(),
            oauth_signature_method: oauth.signature_method,
            oauth_timestamp: oauth.getTimeStamp()
        };

        oauth_data['filter[limit]'] = 200;

        oauth_data.oauth_signature = oauthSignature.generate( request.method, request.url,     oauth_data, oauth.consumer.secret ),

        jQuery.get(
		request.url+'?'+oauth.getParameterString(request, oauth_data),
		function(data) {
		    console.log( data);
		}
        );

    });
```

Just to provide the full picture, I'm importing the following scripts:

    <script src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/hmac-sha1.js"></script>
    <script src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/components/enc-base64-min.js"></script>
    <script type="text/javascript" src="oauth.js"></script>
    <script src="oauth-signature.min.js"></script>

oauth.js comes from https://github.com/ddo/oauth-1.0a/blob/master/oauth-1.0a.js 
oauth-signature.min.js comes from code.google.com/p/crypto-js

Cheers,
Goncalo

**Comment by DilipRajkumar** [comment]
@gongiskhan Still I am getting same error "Invalid Signature - provided signature
 does not match"... any ideas?

**Comment by JoshuaTse** [comment]
here is the solution,  It WORK ~~ 
refer to : https://github.com/woothemes/woocommerce/issues/6493

 https://github.com/bettiolo/oauth-signature-js/blob/master/dist/oauth-signature.js#L263 with :
replace 
"this._key = this._rfc3986.encode(consumerSecret) + '&' + this._rfc3986.encode(tokenSecret);"
to
"this._key = consumerSecret;"

and use gongiskhan 's code and generate the signature ~

**Comment by DilipRajkumar** [comment]
Thank you @JoshuaTse I debugged and figured it out.. Thank you so much..

**Comment by jeffceriello** [comment]
Hi @gongiskhan, how can I get a single product by ID using your approach?

I have tried

http://wardrobeicons.com/wc-api/v3/products/22175?oauth_consumer_key=ck_0369d2e64cd63edf4ba686ab710817b5018a520b&oauth_nonce=0.07115150265051876&oauth_signature=10vTTDJ%252FRU8dkSk77WZb7GP2oxk%253D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1455528864

But this doesn't work and gives me an "Invalid signature" error.

Thank you
Jeff
