### ISSUE TITLE
Possible issue with default downloading of Maxmind database

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#7465]
The author of the "GeoIP Detect" plugin in the wordpress.org directory had his plugin pulled from there this week, because it automatically downloads the MaxMind database, when installed. He's been told that it won't be allowed back until he's changed that.

He told me that he was told that automatic downloading of a CC-licensed database is not allowed by a GPL-licensed plugin.

I don't understand that explanation - the GPL has no problem with downloading data. Data is not code. Presumably there is more to the prohibition than what I have understood. However, whatever it is, will likely affect the current WC release also, as WC does exactly the same. Indeed WC_Geolocation::update_database() is adapted from that very plugin, as noted in the inline documentation.

So, I think you'll want to reach out to the keepers of the wordpress.org repository to clarify the situation with automatic downloading of the MaxMind database, before the same happens to WooCommerce. Personally I can't understand why there could be a problem - but that's not the issue; apparently, there is a problem.

**Comment by mikejolley** [comment]
We've reached out to the team at WordPress.org for clarification and will patch if necessary. Thanks for the heads up.
