### ISSUE TITLE
Issue regarding regular price in product listing.

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#7468]
When i go to add a product in simple product terms, i add the regular price and then select publish.  however, when i take a look at the product list, the price is invisible.  as a work around, i temporarily entered a price for the sales price.  i am currently using wordpress 4.1 and woocommerce 2.3.4.

not too sure if this bug is just for simple product or variable product or both.

Please investigate this.

**Comment by mikejolley** [comment]
Tested by adding new product with regular price 10 - this was shown in admin and on the frontend with no issue.

Please go through https://wordpress.org/support/topic/how-to-debug-issues-after-updates?replies=1

Thanks
