### ISSUE TITLE
Pagination broken with NON default permalinks

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7472]
Maybe related to #7031

I'm not able to reproduce it on my localhost, but i tested on the customer site with only WooCommerce enabled and Storefront.
When the home page is the shop page and Post name are used as permalinks, the pagination is broken.

Going to page 2 (or next) returns a media instead of the page 2.
Works fine with default permalinks.

https://woothemes.zendesk.com/agent/tickets/259628

**Comment by mikejolley** [comment]
Unable to reproduce, will get access via customer.
