### ISSUE TITLE
AJAX calls breaking current-menu states for multiple menus

### ISSUE THREAD

**Issue by pkostadinov-2create** [woothemes/woocommerce#7473]
I have noticed that there is some sort of AJAX calls every time a page is loaded. For that reason sometimes the current-menu-item class disappears. I have noticed this happening for Shop link (always) and for some categories (not all).

The shop link, I was able to trace to "wc-cart-fragments", forcing me to use:

```
// Fix WooCommerce destroying "current-menu-item" class
if ( class_exists('WooCommerce') ) {
	wp_dequeue_script( 'wc-cart-fragments' );
}
```

**Comment by mikejolley** [comment]
Cart Fragments update certain areas to prevent static caching. 

By default we only have 1 fragment which replaces 'div.widget_shopping_cart_content' and nothing else. Check that your theme does not wrap your nav with that class, and ensure the theme is not adding its own fragments.

Thanks
