### ISSUE TITLE
2.3.4 Parses download links and kills shortcodes (S3 downloads)

### ISSUE THREAD

**Issue by andrewfitz** [woothemes/woocommerce#7474]
All my shortcuts used in digital download products are parsed out into a URL. No shortcodes remain, and everything becomes http://shortcode

I'll have [shortcode] in the field, and upon updating the product it becomes http://shortcode.

This has literally just killed all of my products from being downloaded... whatever changes have been made to downloaded product file URL handing needs to be reverted. I have duplicated this issue on another site by simply updating to 2.3.4 and just clicking "update" on the product and all the file download URLs are ruined.

This appeared to be the same as #7442 and included in 2.3.4 patch but the problem persists for me in latest version. Ideas?

Update: it seems that 2.2 does this the same way with wc_clean, perhaps it was changed from 2.1? I can't imagine this would have gone unnoticed for an entire release cycle... maybe something else going on?

The top is how it should be before, then after updating/saving product:
![screen shot 2015-02-18 at 2 01 28 am](https://cloud.githubusercontent.com/assets/46656/6245313/240a86e6-b712-11e4-9f1c-6c44cd34e386.png)

**Comment by andrewfitz** [comment]
Is this an issue with database storage? I see that in the database file URLs are stored in text objects wrapped in double quotes, so the code I've been using has double quotes in the shortcode won't work even if just bypassed and stored as unsanitized. Has the storage of file URLs in the database changed in 2.2 or 2.3 from 2.1? I'm using MYSQL and InnoDB.

**Comment by mikejolley** [comment]
@kloon Should we try to detect the content of the field and apply relevant sanitisation, or do you want to handle this in s3?

**Comment by andrewfitz** [comment]
Not to step on any toes @mikejolley, just a humble suggestion, I would think handing this in the logic of wc_clean rather than changing it esc_url_raw would make sense.

Update: Fix: changing it back to wc_clean has fixed my problem. This then seems as if it was a bug only introduced in 2.3.4 with commit 7899dd9

**Comment by wannabeapilot** [comment]
I am still having an issue from before this commit was made with dropbox urls.

For example if i use this link:

https://www.dropbox.com/s/ror1fysfgvt9rvl/EVHS%20-%20Beauty%20and%20the%20Beast%202015%20Part%201%20-1080p.zip?dl=1

It is valid, and the download will begin.

when I click update it distorts the url into this:

https://www.dropbox.com/s/ror1fysfgvt9rvl/EVHS-BeautyandtheBeast2015Part1-1080p.zip?dl=1

Which then results in a 404

This happened before, and after the update with either wc clean or  esc url raw
