### ISSUE TITLE
Variable item selection broken in Firefox (woocommerce 2.2.11, 2.3.4)

### ISSUE THREAD

**Issue by mithodin** [woothemes/woocommerce#7476]
Affected page: http://klaptek.de/home/?product=klaptek-klassisch
Item cannot be added to the cart even when a variation has been selected, even if "add to cart" button is made visible by hand (so it's not just a css bug).
The same works fine in Google Chrome and Internet Explorer. It also worked before the update to 2.2.11.

**Comment by claudiosmweb** [comment]
Congratulations, you have a JS bug in your theme :)

![screenshot from 2015-02-18 15 26 27](https://cloud.githubusercontent.com/assets/1264099/6252606/bb0dba48-b782-11e4-89eb-e487238034aa.png)
![screenshot from 2015-02-18 15 26 38](https://cloud.githubusercontent.com/assets/1264099/6252607/bb0f838c-b782-11e4-9efc-a03e9da67336.png)
![screenshot from 2015-02-18 15 27 11](https://cloud.githubusercontent.com/assets/1264099/6252608/bb0f7522-b782-11e4-8c43-57f61ee5d916.png)

**Comment by mithodin** [comment]
...thanks. It's a little embarassing that I did not catch that, especially since I saw that error message before.

**Comment by claudiosmweb** [comment]
This error is affecting everything else, I recommend you fix it or change the subject.

**Comment by mithodin** [comment]
I have fixed the script and created a pull request with the maintainer of the theme.
