### ISSUE TITLE
Country & State Selector Not Working In WP User Edit Page [wp-admin/user-edit.php]

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#7477]
![profile_issue](https://cloud.githubusercontent.com/assets/1884287/6250684/91f0da9a-b7b5-11e4-917f-06e4eb2f4dba.png)

Country & State Field are repeated 2 times and when i click it just scrolls down. unable to enter the data.

**Comment by technofreaky** [comment]
WC Support Information


### WordPress Environment ###

Home URL: http://192.168.1.4/wpp
Site URL: http://192.168.1.4/wpp
WC Version: 2.3.3
WC Database Version: 2.3.3
Log Directory Writable: ✔ C:\xampp\htdocs\wpp/wp-content/uploads/wc-logs/
WP Version: 4.1
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11
PHP Version: 5.5.11
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.16
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
Remote Post: ✔
Remote Get: ✔

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (3) ###

Woocommerce Quick Buy: by Varun Sridharan – 0.5
Woocommerce Quick Donation: by Varun Sridharan – 0.4
WooCommerce: by WooThemes – 2.3.3

### Settings ###

API Enabled: ✔
Taxes Enabled: ✔
Shipping Enabled: ✔
Force SSL: –
Currency: INR (Rs.)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Mystile
Version: 1.3.4
Author URL: http://www.woothemes.com
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by claudiosmweb** [comment]
Fixed in WooCommerce 2.3.4

**Comment by technofreaky** [comment]
is that got released ?

**Comment by claudiosmweb** [comment]
@technofreaky YES!

**Comment by technofreaky** [comment]
I dint get any update notice in my wp
Sent using CloudMagic
On Wed, Feb 18, 2015 at 10:23 pm, Claudio Sanches <notifications@github.com> wrote:@technofreaky YES!

**Comment by claudiosmweb** [comment]
If you let your laziness aside and visit this page, you will see that the version was released: http://wordpress.org/plugins/woocommerce/
