### ISSUE TITLE
Twitter button on the Welcome page

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7480]
The Twitter button on the welcome page is not aligned

![](http://cld.wthms.co/1gzSW+)

**Comment by michaeltieso** [comment]
What browser are you using? I'm seeing this:

![screenshot](http://cld.wthms.co/10Ry0+)

**Comment by shivapoudel** [comment]
Twitter Share Button is aligned perfectly for me. But is this intentional ;)
> Your Tweet was over 140 characters. You'll have to be more clever.

![welcome](https://cloud.githubusercontent.com/assets/3774827/6254723/e72ef722-b7d2-11e4-88d5-4c72403304ba.Png)

**Comment by SiR-DanieL** [comment]
On chrome, with windows

**Comment by shivapoudel** [comment]
It's working on chrome, with Windows.

**Comment by claudiosmweb** [comment]
Works fine for me in Chromium, Chrome and Firefox on Ubuntu.
