### ISSUE TITLE
Tweet button has too many characters

### ISSUE THREAD

**Issue by michaeltieso** [woothemes/woocommerce#7481]
![screenshot](http://cld.wthms.co/5J18+)

Seen by going to:
http://yoursite.com/wp-admin/index.php?page=wc-about

> A open-source (free) #ecommerce plugin for #WordPress that helps you sell anything. Beautifully. http://www.woothemes.com/woocommerce/ #WooCommerce via @WooThemes

That's a total of 147 characters which is over 7 characters of Twitter's limit. I think it'd be useful to also revise that tweet to something better. Removing most of those hashtags, etc.

**Comment by MindyPostoff** [comment]
What about this? It's 136 characters.

> #WooCommerce is a free shopping cart plugin for #WordPress to help you sell anything. Beautifully. http://www.woothemes.com/woocommerce/ via @WooThemes

**Comment by hlashbrooke** [comment]
Side note to keep in mind because the original tweet text isn't accurate - `open-source != free` :)

Perhaps a better way of doing it is what Dropbox does - it picks a random tweet from a selection of pre-written ones each time you click their tweet button. Plus, all the tweets are natural language - not marketing language - so they don't look spammy. The current tweet just sounds like a tag line and not something that an individual would naturally write.

Something like this is more natural I think:

> I just installed WooCommerce to kickstart my online store - it's free and it's awesome: http://www.woothemes.com/woocommerce/ @WooThemes

Needs some work, but you get the idea.

Or maybe I'm just overthinking things - that's usually the case :)

**Comment by MarinaWoo** [comment]
#WooCommerce is a free #eCommerce plugin for #WordPress that helps you sell anything. Beautifully. http://www.woothemes.com/woocommerce/ via @WooThemes

(slight adaptation of @MindyPostoff's, which rocks)

**Comment by MindyPostoff** [comment]
I like the human-ness of @hlashbrooke's idea. +1 for that

**Comment by michaeltieso** [comment]
> Perhaps a better way of doing it is what Dropbox does - it picks a random tweet from a selection of pre-written ones each time you click their tweet button. Plus, all the tweets are natural language - not marketing language - so they don't look spammy. The current tweet just sounds like a tag line and not something that an individual would naturally write.

I'm a fan too! +1

**Comment by hlashbrooke** [comment]
A few options that we can give people (or just randomly select one on each click of the tweet button):

> I just installed WooCommerce to kickstart my online store - it's free and it's awesome: http://www.woothemes.com/woocommerce/ @WooThemes

> WooCommerce is incredible - simply the best WordPress eCommerce plugin available: http://www.woothemes.com/woocommerce/ plus it's free from @WooThemes!

> Loving WooCommerce by @WooThemes: http://www.woothemes.com/woocommerce/ - makes it super easy to get your store online in no time.

> I never knew selling online would be this easy - WooCommerce by @WooThemes is simply beautiful: http://www.woothemes.com/woocommerce/

I'm not a marketer, but I will *always* ignore tweets that just look like a tag line and are full of hashtags. This kind of natural language thing makes more sense I think.

**Comment by MarinaWoo** [comment]
I totally agree on the humanness and natural language, such good points guys. Personally I don't like it when brands try to 'speak' on my behalf and put words in my mouth, I'd auto-share trivia or something sort of declarative about a product (i.e. value statement) but I wouldn't want a brand to write an 'I' statement for me.Maybe we could give them options (love your work Hugh, slight re-words below) and then have an empty field that says something like 'Tell the world about WC in your own words".

> WooCommerce kickstarts online stores. It's free and has been downloaded over 6 million times.  http://www.woothemes.com/woocommerce/ @WooThemes

Building an online store? WooCommerce is the leading #eCommerce plugin for WordPress (and it's free) : http://www.woothemes.com/woocommerce/ @WooThemes

WooCommerce is a free #eCommerce plugin for #WordPress for selling #allthethings online, beautifully: http://www.woothemes.com/woocommerce/ @WooThemes 

Ready to ship your idea? WooCommerce is the fastest growing #eCommerce plugin for #WordPress on the web: http://www.woothemes.com/woocommerce/ @WooThemes 

{YOUR OWN THOUGHTS HERE} : http://www.woothemes.com/woocommerce/ @WooThemes
>

M

**Comment by hlashbrooke** [comment]
Sounds good to me :)

**Comment by MarinaWoo** [comment]
Someone just tweeted one! Haha. https://twitter.com/FantronM/status/568341040421318656

**Comment by mikejolley** [comment]
These need to be kept to 102 chars. Make a pull request if you want to change the 4 I added from above.
