### ISSUE TITLE
Mariadb 5.x

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#7483]
I am wondering if woocommerce is fully compatible with mariadb??  the issue i put on here last night was about the regular price and the sales price.  if you only put the regular price, it didn't seem to record that information at all and was not listed in product list.  to fix that, you had to add the price again to sales.

i am currently running opensuse 13.1 x64_86 with all software defaults, being mariadb as default database.

Any help would be appreciated

**Comment by claudiosmweb** [comment]
Why not?
MariaDB was built to support applications that used MySQL in the same way without undergoing any changes.
WordPress works perfectly with MariaDB or Percona (another MySQL fork)!
With that WooCommerce works perfectly well.

I particularly MariaDB use only been two years.
However for your question... it seems to me that you have no idea how it works MariaDB, so I recommend you study it.
