### ISSUE TITLE
No option to disable auto complete on virtual products

### ISSUE THREAD

**Issue by mikemcguire** [woothemes/woocommerce#7486]
The plugin assumes that I want orders to auto complete themselves for virtual products. This isn't always the case, there should be an option to not auto complete virtual orders. Or at the very least allow products to be downloadable, not virtual, that don't require shipping.

**Comment by slash1andy** [comment]
Mike, the "virtual" designation does not auto-complete the order. 

Order with only virtual product: http://cld.wthms.co/14y74

Admin: http://cld.wthms.co/19Lsk

Check a plugin that might be modifying the default behavior.

**Comment by mikemcguire** [comment]
Hmm thanks Andy, I'll take a look.

**Comment by mikemcguire** [comment]
So disabling my plugins I was able to narrow down my issue. The issue is that free products are automatically set to completed. Is there anyway to set free products as processing. I want to prevent the download link being sent to the user until the admin has explicitly set the order to completed.

**Comment by slash1andy** [comment]
There's a lot of snippets here that you could customize to do what you are trying to do: http://bryceadams.com/autocomplete-orders-woocommerce/

Look at the last one there.

**Comment by Vering** [comment]
@mikemcguire: Did you ever find a solution here? I have the exact same situation as you. I do not want the virtual item to be downloaded before I have processed the order myself.

**Comment by mikemcguire** [comment]
I modified the code in the link provided by Andy. 
In the last snippet of code just replace "completed" with "processing"
