### ISSUE TITLE
PUT Product Fails to Update Inventory

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#7487]
Hi,

I am trying to update a product to a stock quantity of 6, however, its inventory fails to change. Here is my request and response

PUT https://finess.dptr.co/wc-api/v2/products/208?stock_quantity=6&consumer_key=ck_87e7ad4400a8aa30057d49bf6a59947d&consumer_secret=cs_b88258fa9cfce1fdef16ef656fb70f4d HTTP/1.1
Authorization: Basic Y2tfODdlN2FkNDQwMGE4YWEzMDA1N2Q0OWJmNmE1OTk0N2Q6Y3NfYjg4MjU4ZmE5Y2ZjZTFmZGVmMTZlZjY1NmZiNzBmNGQ=
Content-Type: application/x-www-form-urlencoded
Host: finess.dptr.co
Content-Length: 20
Expect: 100-continue
Connection: Keep-Alive

{"stock_quantity":6}

HTTP/1.1 200 OK
Server: nginx/1.2.7
Date: Thu, 19 Feb 2015 02:39:48 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.5.21
Vary: User-Agent

77d
{"product":{"title":"Finess 36-pack. Value, convenience and sophistication.","id":208,"created_at":"2015-01-10T00:12:10Z","updated_at":"2015-02-18T20:16:27Z","type":"simple","status":"publish","downloadable":false,"virtual":false,"permalink":"https:\/\/finess.dptr.co\/product\/finess-36pack\/","sku":"36P","price":"21.99","regular_price":"21.99","sale_price":null,"price_html":"<span class=\"amount\">&#36;21.99<\/span>","taxable":true,"tax_status":"taxable","tax_class":"","managing_stock":true,"stock_quantity":12,"in_stock":true,"backorders_allowed":false,"backordered":false,"sold_individually":false,"purchaseable":true,"featured":false,"visible":true,"catalog_visibility":"visible","on_sale":false,"weight":null,"dimensions":{"length":"","width":"","height":"","unit":"in"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"36-pack","shipping_class_id":16,"description":"<p>The Finess 36-pack features a discreetly elegant designer box containing 36 Finess each packaged individually and ready to take out for immediate use or to carry in your purse for the day. The sliding tray is quiet and easy to open - no need to rip or tear anything apart. For your privacy it is delivered to your home inside a nondescript shipping container.<\/p>\n","short_description":"","reviews_allowed":false,"average_rating":"0.00","rating_count":0,"related_ids":[],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"categories":[],"tags":[],"images":[{"id":209,"created_at":"2015-01-10T00:45:12Z","updated_at":"2015-01-10T00:45:12Z","src":"https:\/\/finess.dptr.co\/wp-content\/uploads\/2015\/01\/finess-36pack.png","title":"finess-36pack","alt":"","position":0}],"featured_src":"https:\/\/finess.dptr.co\/wp-content\/uploads\/2015\/01\/finess-36pack.png","attributes":[],"downloads":[],"download_limit":0,"download_expiry":0,"download_type":"","purchase_note":"","total_sales":148,"variations":[],"parent":[]}}
0

**Comment by claudiosmweb** [comment]
Please first of all, change your keys, you just expose them to everyone in this repository.
It is just possible to make any change in your store the keys you sent.

**Comment by claudiosmweb** [comment]
This request is wrong, please read the docs:
http://woothemes.github.io/woocommerce-rest-api-docs/#update-a-product
