### ISSUE TITLE
All menu items have the same labels

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7488]
https://woothemes.zendesk.com/agent/tickets/259761  @ChromeOrange @mikejolley 

This issue was replicated on a local setup with only WooCommerce 2.3.4 activated with 2012 theme,

here are steps to replicate:

- Create a standard WP menu 'Account Menu', with, say one item, 'Help'. It's not assigned to any menu position. 
- Add the shortcode code at the end of the post in functions.php 

```
function show_menu ( $atts, $content = null ) { 
extract(shortcode_atts(array( 
'name' => '', 
'id' => '' 
), $atts));

$container_class = 'in-page-menu cf';

if ($id) { 
$html = wp_nav_menu( array( 
'container_class' => $container_class, 
'echo' => false, 
'menu_id' => $id)); 
} 
elseif ($name) { 
$html = wp_nav_menu( array( 
'container_class' => $container_class, 
'echo' => false, 
'menu' => $name)); 
} 
else { 
$html = ''; 
} 
return $html; 
}

add_shortcode( 'menu', 'show_menu' );
```
- Add the menu to the WordPress account pages via the shortcode [menu name="Account Menu"] 
- View, for example, .../my-account/edit-address/billing/ 
- The menu item text/label turns into the page currently being viewed while the links show up fine. ![](http://cld.wthms.co/12IjA+)

**Comment by hexagongirl** [comment]
Thanks @spraveenitpro!

@ChromeOrange @mikejolley - in case it helps troubleshooting... this issue is new to WC 2.3; menus were working fine before upgrading last week.

**Comment by hexagongirl** [comment]
@mikejolley thanks for this.  This does however mean that if ```<?php the_title(); ?>``` is not present in the theme (as was the case with the one I'm working on), the filter (```wc_page_endpoint_title```) is not removed - and so the issue persists.

I have fixed the issue locally by removing the filter within my shortcode, but wonder whether there's another way around this?

**Comment by extrapixel** [comment]
this still doesn't work. menus other than main menu don't work. something's messing with the title/string of the first menu entry.

so this:
>The menu item text/label turns into the page currently being viewed while the links show up fine. 

is still true for every first item in menus.
