### ISSUE TITLE
Shipping - Free Shipping. Minimum Order

### ISSUE THREAD

**Issue by LindsayHeydon** [woothemes/woocommerce#7492]
On latest version 2.3.4.

Minimum Order Amount is not being applied, so a delivery fee is not being added if an order is beneath the specified amount.

This was working on 2.3.0 (I haven't changed any Shipping settings and definitely working before recent upgrades).

**Comment by claudiosmweb** [comment]
All options tested and works really fine:

![screenshot from 2015-02-19 10 31 33](https://cloud.githubusercontent.com/assets/1264099/6266580/8fd325d4-b822-11e4-94e5-ce14334f85b5.png)

**Comment by LindsayHeydon** [comment]
I have tested this on four sites now and having same issue on all of them (they are not using the same theme and one is using Artificer - without template changes). Absolutely categorically working before recent updates.
![shipping](https://cloud.githubusercontent.com/assets/10940158/6266801/cab2c584-b835-11e4-9fc6-b1459b304a2a.jpg)

**Comment by claudiosmweb** [comment]
Perhaps the error might be generated by another plugin.
Just checking: Are you testing with addresses in UK or Isle of Man?

**Comment by LindsayHeydon** [comment]
Yes definitely checking with correct address. What makes me think I have the settings correct is that this was absolutely working just before the update (one of my clients had specifically requested this functionality. I tested it well and it was fine.) JFYI I'm not using any other shipping plugins. I've disabled all plugins (except WooCommerce) on the site that uses Artificer and same issue.. See below
![free shipping under 10](https://cloud.githubusercontent.com/assets/10940158/6267529/b6da6fba-b83c-11e4-8708-53b0f1179130.jpg)
![free shipping over 10](https://cloud.githubusercontent.com/assets/10940158/6267528/b6da811c-b83c-11e4-83b7-6104f7fda857.jpg)

Many thanks for your support.

**Comment by mikejolley** [comment]
I don't see an issue locally or in your screenshots. In your shots, where minimum order amount is 10, you don't get 'free shipping' until the subtotal is £13..

Your only other method (local) is also free, but thats a separate method.

**Comment by LindsayHeydon** [comment]
That's true - but before the update my Flat Rate would kick in if the total was less than 10.00. As surely the whole point of having a minimum order amount is that you charge for anything smaller. I should have been clearer, so apologies. I'd think it was me and something in my settings if this hadn't absolutely worked before the update.

![flat rate](https://cloud.githubusercontent.com/assets/10940158/6268877/af573ce0-b847-11e4-9b8b-92274bf61753.jpg)

**Comment by mikejolley** [comment]
Seems to be the per class option.

**Comment by mikejolley** [comment]
Ok - to fix, enter cost for any class to 0. Right now, since your item in the cart has no shipping class, none of the rules match, so no cost is applied. If you set any class to 0, it will match and give you a rate.

**Comment by LindsayHeydon** [comment]
Ahhh, yes. That's it. It must have worked previously with N/A so I didn't look further than the end of my nose!  Thank you for the fix. Much appreciated.
