### ISSUE TITLE
Item Meta not being collected

### ISSUE THREAD

**Issue by LiamBailey** [woothemes/woocommerce#7495]
Hi,

On the $order->get_items() function the item_meta array is no longer being filled - I have traced it to the get_metadata function not working as it used to. As a result the product_id and variation_id aren't filled into the items array and $order->get_product_from_item can't work.

**Comment by mikejolley** [comment]
You should rule out extension conflicts because if this wasn't working, hardly any of our extensions would be functioning right now...

**Comment by LiamBailey** [comment]
I will do so - I found it on a couple of seperate environments, but I will run a test on a new dev env I setup yesterday with no extensions - thanks for now Mike.

**Comment by LiamBailey** [comment]
Yeah - my bad apologies Mike I should have checked this first but as I said coming across it 3 times in different places I really thought it was latest version problem - (admittedly one of the places was the Woothemes Export CSV extension at a point when it had actually constructed its own $item array with only name, sku, quantity, total and meta. Anyway, I will close with this comment. Thanks.
