### ISSUE TITLE
[2.3.4] "Add products" popup hides select2 results box in Manually Adding Orders form

### ISSUE THREAD

**Issue by heynad** [woothemes/woocommerce#7497]
See this screenshot:

![manually_add_products](https://cloud.githubusercontent.com/assets/11075318/6267754/247f450e-b847-11e4-95f1-878a043c8cad.png)

I am struggling with the UI for manually adding an order that I got by phone: First I click on "Add line item(s)", then on "Add product(s)". Then I have the problem that I cannot choose a product because the popup box overlays the results, see the above screenshot.

**Comment by mikejolley** [comment]
What browser?

**Comment by heynad** [comment]
Firefox 35.0.1 (on Ubuntu 14.04)

**Comment by mikejolley** [comment]
Clear caches/disable other plugins - I tested on Firefox, and I know Claudio also uses Ubuntu/FF: https://dl.dropboxusercontent.com/s/cg76s14tb2kzf3o/2015-02-19%20at%2016.22%202x.png?dl=0

**Comment by heynad** [comment]
It's an issue caused by the Virtue theme by its:
```
.select2-drop {
    z-index: 100108 !important;
}
```
in its file `kad-short-pop.css`

Sorry, for the inconvenience I'll doublecheck in the future if its a plugin/theme issue. I thought it cannot be because it is on the backend, next time I'll know better.
