### ISSUE TITLE
Add filter to support changing number of items loaded in shop order page

### ISSUE THREAD

**Issue by adnanoner** [woothemes/woocommerce#7499]
It would be nice if there was a filter to change the number of items shown in the shop order list page. The default is currently 20 which is pretty inconvenient when you need to process +100 orders and want to print / edit them. Not sure where the wp-list-table is generated so maybe I've missed the filter/action.

**Comment by jackgregory** [comment]
@adnanoner Use the per page input under screen options.

![screen shot 2015-02-19 at 23 02 43](https://cloud.githubusercontent.com/assets/4092564/6278038/7faa081c-b88b-11e4-8003-c2932638c466.png)

**Comment by adnanoner** [comment]
Hi sorry, totally missed that! Issue can be marked as closed :+1:
