### ISSUE TITLE
Ability to wrap <label> and field elements in woocommerce_form_field

### ISSUE THREAD

**Issue by indextwo** [woothemes/woocommerce#7501]
As it stands, the function `woocommerce_form_field` currently exports a `<p>` tag that contains the `label` and `input` (or similar) elements for the checkout.

Due to particular design and functionality requirements, I want to be able to rearrange the checkout form elements *and* wrap the labels and fields (input, select, etc.) in separate `<div>` or similar block-level elements (in this instance, the fields need psuedo `:before` and `:after` classes, which can't be used on non-container elements).

I am able to rearrange the form output using `add_filter('woocommerce_checkout_fields')` and I know I can change the classes of the wrapping `<p>` tag and the child `label` and `input` elements, but beyond that I can't do anything to affect the *structure*. 

At the moment I'm using DOMDocument and a series of loops to try to achieve this (in `/checkout/form-billing.php`):

	<?php
	foreach ($checkout->checkout_fields['billing'] as $key => $field) {
		// ['return'] = true set on each field in the woocommerce_checkout_fields filter

		$theField = woocommerce_form_field($key, $field, $checkout->get_value($key));

		$dom = DOMDocument::loadHTML($theField);
		
		foreach($dom->getElementsByTagName('label') as $element) {
			$divWrapper = $dom->createElement('div');
			$divWrapper->setAttribute('class', 'box six');
			$element->parentNode->replaceChild($divWrapper, $element);
			$divWrapper->appendChild($element);
		}
		
		foreach($dom->getElementsByTagName('input') as $element) {
			$divWrapper = $dom->createElement('div');
			$divWrapper->setAttribute('class', 'box six');
			$element->parentNode->replaceChild($divWrapper, $element);
			$divWrapper->appendChild($element);
		}
		
		foreach($dom->getElementsByTagName('select') as $element) {
			$divWrapper = $dom->createElement('div');
			$divWrapper->setAttribute('class', 'box six');
			$element->parentNode->replaceChild($divWrapper, $element);
			$divWrapper->appendChild($element);
		}
		
		$theField = $dom->saveHTML();
		
		echo $theField;
	}
	?>

...however, strictly a `<p>` tag cannot contain block-level elements, which causes issues with this method. Regardless I'm not sure how well the ajaxified dropdowns will work with it.

Is there any real (read:*better*) way to achieve this? Or perhaps change the type of wrapping element (from `<p>` to `<div>` maybe?) If not, is it something that's in scope? Otherwise, is there any issue with me hard-coding the fields into the template so that I have more direct control over them?

**Comment by jameskoster** [comment]
Well, you could plug `woocommerce_form_field()`, but it's a pretty big function that will hopefully be refactored soon so that might not be advisable. It would be a quick and dirty way of changing the `p`'s to `div`'s though.

What exactly are you trying to do? From the code you pasted it looks like you're aligning elements to a grid? Couldn't you just use a css preprocessor to add the styles to the `.form-row` class? Or add the classes to your grid stylesheet?

**Comment by indextwo** [comment]
I had seen a similar answer by someone on SO who pretty much cloned the entire `woocommerce_form_field()` function and then modified it which, I agree, isn't ideal.

In the meantime I actually used a `str_replace` to swap out the `<p>` tags for `<div>`s but this is still a pretty hacky solution.

The reason for wanting wrappers around the `<label>` and `<input>` elements is not just for alignment (which I agree can be achieved in other ways), but also because I need to use pseudo-classes (both `:before` and `:after`) for the both the fields and labels, but these cannot be applied directly to non-containing elements like `<input>`.

**Comment by jameskoster** [comment]
You can apply pseudo elements to the parent `p`, though? Or are you saying you need to wrap the `p` in an additional `div`?

**Comment by indextwo** [comment]
I *can* add pseudo-elements to the parent `<p>`, but in this instance it won't be particularly helpful; each field has live error checking, so we want to be able to show error/okay icons (with `:after`) and inline hints (with `:before`). 

As you noted, they are also supposed to be grid-aligned, so adding these pseudo-elements to the parent `<p>` gets unnecessarily complicated when it comes to alignment and responsive behaviour. There are, unfortunately, a number of instances where 2 inline elements in a paragraph tag just aren't enough to exercise real control (although I get why that may sometimes be a bad thing).

With regards to my point above: I did actually get it working exactly as I'd hoped, using `DOMDocument` and `str_replace` to replace the `<p>` tag and add wrapping `<divs>` to the label and inputs; however as I suspected, this seemed to break the dynamic updates of State/Zip when changing the Country field.

**Comment by jameskoster** [comment]
I think we'll leave this until `woocommerce_form_field()` is refactored (please feel free to create a new issue for that), we can then introduce some filters to make these elements more customisable.

**Comment by indextwo** [comment]
No problem, that makes sense to me - it does seem like a fairly big task. In the meantime I did get the fields to look *almost* how I wanted them using some PHP trickery (as noted above, for anyone interested), and settled for jQuery adding and removing elements as needed to the parent `<p>` (rather than pseudo-elements directly around the inputs).

**Comment by nicmare** [comment]
I know this is an old issue but problem is not solved until now. there is a hook for each field type. the easiest way to change the code is like this:
```php
function wrap_div_around_field_text($field){
    $field = "<div>".$field."</div>";
    return $field;
}
add_filter("woocommerce_form_field_text","wrap_div_around_field_text");
add_filter("woocommerce_form_field_email","wrap_div_around_field_text");
add_filter("woocommerce_form_field_tel","wrap_div_around_field_text");
```

**Comment by maketimetodesign** [comment]
Hey @nicmare thanks for posting this, it doesn't actually allow you to change the p to a div, but it's still helped me out nonetheless. My problem is with styled select's, select2 creates a div which can't be nested within a p so screws up the layout. Also, the above doesn't appear to work for selects?

I assumed woocommerce_form_field_select would work? But can't find any further documentation on it, any help would be gratefully received! 

Thanks, 
Tom

**Comment by nicmare** [comment]
try:
woocommerce_form_field_country
woocommerce_form_field_state
instead of
woocommerce_form_field_select

**Comment by maketimetodesign** [comment]
Nice one thanks for that!

**Comment by monecchi** [comment]
I haven't tested WooCommerce 3.0 yet, so I'm not sure if it has refactored `woocommerce_form_field()` or not, but I know about a [function](http://stackoverflow.com/a/25469530/1152876) which helps you to completely re-build the checkout fields output, this way one could adapt the output according to a theme's structure to better fit some framework's design principals, e.g Bootstrap, Foundation, you name it.

I also had to face a similar issue while trying to add custom css classes to all the checkout form fields at once. Fortunately, I've come up with a pretty straight forward [solution](http://stackoverflow.com/a/36724593/1152876) that is taken from WooCommerce functions, although it does not offer a proper method in order to achieve that kind of stuff.

**Comment by DhruveShah** [comment]
Has anyone been able to change the markup from a `<p>` to anything else, without requiring the function @monecchi wrote?

It seems a bit overkill in my opinion to rewrite the checkout fields just to change the p tags to divs and add some classes

**Comment by indextwo** [comment]
@DhruveShah I use the following in my template overrides. Note that this has to be done for each of the different field sets (`billing`, `'shipping`, `account`, etc.), but the code is the same for all of them:

	<?php foreach ($checkout->get_checkout_fields('shipping') as $key => $field) : ?>
		
		<?php
			$field['return'] = true;	//	Returning it to a string to I can run a str_replace and change the hard-coded <p> tags for <divs>
			
			if (isset($field['country_field'], $fields[$field['country_field'] ])) {
				$field['country'] = $checkout->get_value($field['country_field']);
			}
			
			$theField = woocommerce_form_field($key, $field, $checkout->get_value($key));
			
			$theField = str_replace('<p', '<div', $theField);	//	Add your classes here too, if you want
			$theField = str_replace('</p', '</div', $theField);
			
			echo $theField;
		?>
		
	<?php endforeach; ?>

**Comment by DhruveShah** [comment]
@indextwo Thanks for that!

**Comment by aminta** [comment]
Hi!

I've read all the thread but I can't get understand how to correctly wrap the Woocommerce fields...

Each field of the default Woocommerce form checkout has this markup: 

    <p class="form-row form-row-first validate-required" id="billing_first_name_field" data-priority="10">
         <label for="billing_first_name" class="">Name&nbsp;
               <abbr class="required" title="required">*</abbr>
         </label>
         <span class="woocommerce-input-wrapper">
              <input type="text" class="input-text " name="billing_first_name" id="billing_first_name" placeholder="" value="" autocomplete="given-name">
         </span>
    </p>

Now, I want:

 1. Wrap each field in a wrapper like `<div class="single-field-wrapper"><p [...] </div>`
 2. Wrap the first two fields, 'billing_first_name' and 'billing_last_name' in a wrapper like `<div class="first-and-second-field-wrapper"> [...] </div>`


To achieve this, I've tried to use the filter hooks made available by `function woocommerce_form_field( $key, $args, $value = null ) ` called in `form-billing.php` template in this way:

    <?php
			$fields = $checkout->get_checkout_fields( 'billing' );

			foreach ( $fields as $key => $field ) {
				if ( isset( $field['country_field'], $fields[ $field['country_field'] ] ) ) {
					$field['country'] = $checkout->get_value( $field['country_field'] );
				}
				woocommerce_form_field( $key, $field, $checkout->get_value( $key ) );
			}
		?>

So in `functions.php` I wrote:

    function change_woocommerce_field_markup($field, $key, $args, $value){
	   
      

      if($key === 'billing_first_name') {

	      $field = '<div class="first-and-second-field-wrapper">'.$field;
       }
      else if ($key === 'billing_last_name') {

	      $field = $field.'</div>';
       }

	   else {
		  $field = $field;
       }

	    return $field;
       } 
      
      add_filter("woocommerce_form_field","change_woocommerce_field_markup", 10, 4);


Unexpectedly, I get this markup:

    <div class="first-and-second-field-wrapper">
           <div class="single-field-wrapper">
                <div class="single-field-wrapper">
                [here there are all the fields, one under the other ]
                </div>
           <div class="single-field-wrapper"></div> 
           <div class="single-field-wrapper"></div> 
           <div class="single-field-wrapper"></div> 
           <div class="single-field-wrapper"></div> 
           <div class="single-field-wrapper"></div>   
           <div class="single-field-wrapper"></div> 
           <div class="single-field-wrapper"></div> 
           <div class="single-field-wrapper"></div> 
     </div>


Anyone can explain why this unexpected behavior?

**Comment by monecchi** [comment]
Just referencing @aminta latest comment to this StackExchange [answer](https://wordpress.stackexchange.com/questions/309700/how-to-hook-on-a-woocommerce-checkout-field).
