### ISSUE TITLE
Add to cart - cart forgotten?

### ISSUE THREAD

**Issue by canfiax** [woothemes/woocommerce#7506]
I have this piece of code in my functions.php:

	add_action('init', function() {
		global $woocommerce;

		/**
		 * Add to cart
		 */
		
			if(isset($_GET['js-add-to-cart'])) {
				$woocommerce->cart->add_to_cart($_GET['js-add-to-cart']);
				
				exit(json_encode(array('cart' => $woocommerce->cart->get_cart_total()), true));
			}

	});

It works perfectly! However, if I am logged out (i.e incognito mode), the cart is reset upon every page refresh.

Say I ping this file 5 times when logged in, the price increase every time. But if I log out, and do the same, the product only exist ONCE no matter how many times I've added it.

**Comment by mikejolley** [comment]
I reckon you may be causing notices with that above code, and that will prevent cookies from being set. No cookie = no cart. Test with WP_DEBUG and WP_DEBUG_LOG enabled and see what you're triggering.

The above is not the correct way to handle ajax add to cart either btw- use wordpress' ajax system/hooks.

Closing as this isn't a bug report for core.

**Comment by canfiax** [comment]
Thanks for your quick reply. Can you show me an example of which ajax request I can send, to add a specific product id to cart?

**Comment by canfiax** [comment]
I figured out why above code did not. The "init" hook was too early. Switching to "wp_loaded" solved the issue. Like so:

	add_action('wp_loaded', function() {
		global $woocommerce;

		/**
		 * Add to cart
		 */
		
			if(isset($_GET['js-add-to-cart'])) {
				$woocommerce->cart->add_to_cart($_GET['js-add-to-cart']);
				
				exit(json_encode(array('cart' => $woocommerce->cart->get_cart_total()), true));
			}

	});
