### ISSUE TITLE
'woocommerce_button_proceed_to_checkout' as a template

### ISSUE THREAD

**Issue by oropesa** [woothemes/woocommerce#7507]
Hi Woo,

In the new Update you added the function 'woocommerce_button_proceed_to_checkout'. I know that if I want to custom this button I only have to declare the 'woocommerce_button_proceed_to_checkout' function, but it would be easier if there would exist the template 'templates/cart/button-proceed-to-checkout.php'.

Just that =)

Thanks for improve this awesome plugin.

**Comment by jameskoster** [comment]
Kinda feels like overkill, but we can add it for the next release :-P

**Comment by oropesa** [comment]
Thank you =)
