### ISSUE TITLE
Too many "!important" declarations in CSS

### ISSUE THREAD

**Issue by oropesa** [woothemes/woocommerce#7508]
Hi Woo again,

I'm updating my woo-themes and I saw too many "!important" declaration in several properties (mostly in colors) and it is a bit annoying to work with this. I feel a little bad for to open this issue, so if you don't consider this relevant it's ok, If you could remove this declarations I (and maybe the web designers) would appreciate it a lot =)

Thanks!

**Comment by claudiosmweb** [comment]
10 to be honest: https://github.com/woothemes/woocommerce/blob/master/assets/css/woocommerce.scss

**Comment by claudiosmweb** [comment]
And just 3 for colors.

**Comment by oropesa** [comment]
Hahaha before I felt bad, now I feel stupid. Sorry =)
