### ISSUE TITLE
Product options meta not showing on order line items when retrieved via API

### ISSUE THREAD

**Issue by mindsize** [woothemes/woocommerce#7509]
We're working with a third-party provider for shipping software, and we're missing product options on our order details. In working with them to try to resolve the issue, I sent over the example from the WC API that shows product meta being included in order details as an array of named values. They sent back a response from their logs, which I've independently verified in Postman, showing that the meta property is not being included the line items for our orders.

The WC API Docs show line items structured as follows:
{
        "id": 505,
        "subtotal": "19.99",
        "subtotal_tax": "1.00",
        "total": "19.99",
        "total_tax": "1.00",
        "price": "19.99",
        "quantity": 1,
        "tax_class": null,
        "name": "Ship Your Idea",
        "product_id": 613,
        "sku": "",
        "meta": [
          {
            "key": "pa_color",
            "label": "Color",
            "value": "Black"
          }
    ]
}

The response we're getting on our live site for a product with variations meta is:

{
    "id": 7810,
    "subtotal": "24.99",
    "total": "24.99",
    "total_tax": "1.69",
    "price": "24.99",
    "quantity": 1,
    "tax_class": null,
    "name": "Lifeline XL",
    "product_id": 1812,
    "sku": "LL-01-04"
}

These products were created with the attribute values defined on each product, though we do use the same values for 3 products. The API does return the attributes when requesting the product (/wc-api/v2/products/<id>):

"attributes": [
{
    "name": "Inside Color",
    "slug": "Inside Color",
    "position": "0",
    "visible": true,
    "variation": true,
    "options": [
        "Black",
        "White",
        "Olive Drab",
        "Pink",
        "Foliage Green",
        "Multi Cam",
        "ACU",
        "Coyote",
        "Desert Sand",
        "Harmony",
        "Woodland Camo",
        "Red",
        "Blue",
        "Turquoise",
        "Navy Blue",
        "Orange",
        "Neon Green",
        "Vietnam",
        "Pink Camo"
    ]
}

**Comment by claudiosmweb** [comment]
The slug can't be `Inside Color`, maybe `inside-color` but not `Inside Color`.
Probably you are creating this the wrong way.
Please read the API docs: http://woothemes.github.io/woocommerce-rest-api-docs/
The API is working perfectly.

**Comment by mindsize** [comment]
They're being created in the Attributes editor in the admin.

https://www.dropbox.com/s/4xfuaf15d3nxv3m/Screenshot%202015-02-20%2011.31.59.png?dl=0

**Comment by maxrice** [comment]
@mindsize is the 3rd party provider using the v2 API? or v1? The v1 order response doesn't include line item meta (:frowning:) so that's the most likely culprit here.

**Comment by mindsize** [comment]
That appears to be the issue. Thank you @maxrice, I'll follow up with them now. I'm curious about the slug issue, too, though. Is this a bug?

**Comment by claudiosmweb** [comment]
@mindsize Go to the WordPress dashboard and try to edit some slug for any taxonomy, by default WordPress will replace spaces with `-`.

**Comment by mindsize** [comment]
I'm aware that the normal behavior is to add dashes. This is a site that was upgraded to WC 2.0 recently, and the attributes were added in WooCommerce from the WordPress admin before my time, and you saw the result. I'm just trying to determine if this was a database upgrade issue that has been fixed in newer versions of WC, or if it's still an active issue (which I can test with a clean WC install). I can assure you that we've never used the API for anything until very recently. This product was created in December of 2012, well before WC 2.x.
