### ISSUE TITLE
Coupon calculation after tax is incorrect

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#7510]
To recreate...

Tax Options: http://cld.wthms.co/13eaT
Standard Tax Rates: http://cld.wthms.co/1iGl8
Coupon: 10% Cart Discount

Cart View: http://cld.wthms.co/1c5tC

**Comment by mikejolley** [comment]
@MindyPostoff Coupons are always before tax...

**Comment by MindyPostoff** [comment]
@mikejolley In that case, isn't the total off?

If my product costs $6 (incl $1 tax), the discount is correct at $0.50. Wouldn't the total need to be $5.50?

**Comment by mikejolley** [comment]
No because then you'd be charging tax on money that didn't change hands. 5.00 - 0.50 - 4.50, 4.50 * 1.2 = $5.40

**Comment by martinkarls** [comment]
Well, the mathematic is logical and correct. But what is not logical is that the coupon value is showed excluding tax. The coupon should of course inherit it's settings from the price settings. If price is set to be viewed including tax so should the coupon. This would not affect the logic of the mathematics or the tax calculation but it sure would make a whole lot more sense for the customers.

**Comment by addedlovely** [comment]
Coupon codes also take into consideration tax, when tax is disabled.

We had VAT @ 20% setup, but tax disabled, and coupon applied to the price minus VAT.

**Comment by MindyPostoff** [comment]
@addedlovely I believe the issue you've mentioned is a different problem. Can you please open a new issue for our developers to review?  Thanks  :)

**Comment by addedlovely** [comment]
@MindyPostoff Sorry didn't notice this ticket was closed. Raised a new ticked #8267 with steps to reproduce.
