### ISSUE TITLE
SalesTaxAmount format error in quickbooks payment

### ISSUE THREAD

**Issue by michaelpillari** [woothemes/woocommerce#7512]
SalesTaxAmount format error...looks like field is not being accepted by quickbooks payments

**Comment by mikejolley** [comment]
Hello. This is the issue tracker for WooCommerce core - you'll need to let the developer of quickbooks know. Thanks

**Comment by michaelpillari** [comment]
The data coming from woo commerce "SalesTaxAmount" is not formatted correctly
