### ISSUE TITLE
inconsistency with get_weight() and get_dimensions()

### ISSUE THREAD

**Issue by pixelpeter** [woothemes/woocommerce#7516]
In my opinion both of this function should be handled the same.

That's why I'm wondering why `get_dimensions()` will return the value **with** the unit e.g. *1x2x3 cm*
but `get_width()`will **only** return the value e.g. *18* instead of the expected *18 kg*

My suggested workaround:

```
public function get_weight() {
		return apply_filters( 'woocommerce_product_get_weight', $this->weight ? $this->weight.' '.get_option( 'woocommerce_weight_unit' ) : '' );
	}
```

Currently using WooCommerce 2.3.5

**Comment by Akilez** [comment]
I'm pretty sure that you will find the get_dimensions method is for displaying dimensions to the user. There is no calculations made on width, height or length so a specific get_width method wasn't strictly needed. 

Whereas get_weight is used in calculations so returning the raw number aids in that process.

**Comment by mikejolley** [comment]
get_dimensions() gathers 3 sets of dimensions for display.
get_weight() just gets the value.

These methods have different uses and shouldn't be the same, but if anything we could have separate methods for width, height, and length which returns a value without formatting.
