### ISSUE TITLE
v 2.3.5 | Fatal error: Uncaught exception 'BadMethodCallException'

### ISSUE THREAD

**Issue by pjv** [woothemes/woocommerce#7518]
Getting this error in the hphp error log running under HHVM 3.5.1 with WC 2.3.5:

    Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function get_formatted_name() on a non-object (boolean)' in .../wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php:484\nStack trace:\n#0 .../wp-admin/includes/template.php(1044): WC_Meta_Box_Product_Data::output()\n#1 .../wp-admin/edit-form-advanced.php(600): do_meta_boxes()\n#2 .../wp-admin/post.php(209): include()\n#3 {main}

the code referenced in the error looks like this:

    foreach ( $product_ids as $product_id ) {
        $product = wc_get_product( $product_id );
        $json_ids[ $product_id ] = wp_kses_post( $product->get_formatted_name() );
    }

does it just need an `if is_object($product)`?

**Comment by pjv** [comment]
i have a fix. will submit a PR in a bit.

**Comment by nathanielks** [comment]
Hey all! This error has popped up again. Resolved in #7842
