### ISSUE TITLE
Memcached and far future expiring transients broken

### ISSUE THREAD

**Issue by mgmartel** [woothemes/woocommerce#7519]
Hi,

I found a problem with the WordPress Memcached plugins, causing them to never cache values with a time to live of more than 30 days in the future. I contacted the authors of the Memcached and the Memcached Redux plugin to see if the simple fix can be included in the plugins in the WP.org repo.

The problem affects the WooCommerce + Memcached combination heavily, because Woo stores quite a few important transients for a whole year. For a full description [look here](https://remaintenance.io/blog/2015/02/fixing-woocommerce-memcached-performance/).

This problem is clearly not caused by WooCommerce, but considering that Memcached is a very popular persistent cache backend, and that upgrading `object-cache.php` is not as straight forward as simply updating a plugin, I propose to patch this problem also on the WC side. 

The fix is to pass unix timestamps instead of a TTL when the expiry is more than 30 days in the future. In WC this is only ever `YEAR_IN_SECONDS`. So we could define an alternative constant (`WC_EXPIRE_YEAR_IN_SECONDS`) that is `time() + YEAR_IN_SECONDS` iff a problematic Memcached plugin is detected, and `YEAR_IN_SECONDS` otherwise.

I will make a PR with my proposed fix now.

Mike

**Comment by mikejolley** [comment]
See #7520
