### ISSUE TITLE
WooCommerce Latest Version: Removed Quantity + -

### ISSUE THREAD

**Issue by premiumwd** [woothemes/woocommerce#7523]
Hi,

Can you tell me why you removed + - input buttons from cart and product single when selecting an item?

**Comment by om4james** [comment]
Please see http://develop.woothemes.com/woocommerce/2015/02/v2-3-handsome-hippo/ for details.

This functionality has been moved into its own plugin: https://wordpress.org/plugins/woocommerce-quantity-increment/

**Comment by roykho** [comment]
Thanks @om4james

**Comment by premiumwd** [comment]
Much appreciate thabks @om4james
