### ISSUE TITLE
pre_get_product_search_form filter not correct

### ISSUE THREAD

**Issue by maximus80** [woothemes/woocommerce#7526]
Hey guys!

In wc-deprecated-functions.php, in the $wc_map_deprecated_filters variable, the mapping from get_product_search_form to pre_get_product_search_form filter us done.

However, in wc-template-functions.php, in the get_product_search_form() function only the action is updated to the new name, but the filter is still on old name:
$form = apply_filters( 'get_product_search_form', ob_get_clean() );

So using new filter name won't work, until above line is updated.
Thanks!

Mark

**Comment by mikejolley** [comment]
The action was renamed, not the filter, in this case.

**Comment by maximus80** [comment]
Yeah ok, but still it is in the deprecated filters array. So if we still use get_product_search_form filter it will add a deprecated note to the logs, and if we use pre_get_product_search_form, it won't work.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/2ffcc65cd5853f3f798073b851f5206577a41794

**Comment by maximus80** [comment]
perfect, thx.
