### ISSUE TITLE
Capability problem in new release

### ISSUE THREAD

**Issue by andymax** [woothemes/woocommerce#7528]
A new problem with the 'view_woocommerce_reports' capability, not showing the 'Reports' link in the left menu bar.

**Comment by mikejolley** [comment]
Need more details than that. What role, what caps does the role have, what menus do show...

**Comment by andymax** [comment]
It's a custom role (Shop Assistant) with theese capabilities:

- Activate plugins
- Add users
+ Assign product terms
+ Assign shop coupon terms
+ Assign shop order terms
+ Assign shop webhook terms
- Create users
- Delete others pages
- Delete others posts
+ Delete others products
+ Delete others shop coupons
+ Delete others shop orders
+ Delete others shop webhooks
- Delete pages
- Delete plugins
- Delete posts
- Delete private pages
- Delete private posts
+ Delete private products
+ Delete private shop coupons
+ Delete private shop orders
+ Delete private shop webhooks
+ Delete product
+ Delete product terms
+ Delete products
- Delete published pages
- Delete published posts
+ Delete published products
+ Delete published shop coupons
+ Delete published shop orders
+ Delete published shop webhooks
+ Delete shop coupon
+ Delete shop coupon terms
+ Delete shop coupons
+ Delete shop order
+ Delete shop order terms
+ Delete shop orders
+ Delete shop webhook
+ Delete shop webhook terms
+ Delete shop webhooks
- Delete themes
- Delete users
- Edit dashboard
- Edit files
- Edit others pages
- Edit others posts
+ Edit others products
+ Edit others shop coupons
+ Edit others shop orders
+ Edit others shop webhooks
- Edit pages
- Edit plugins
- Edit posts
- Edit private pages
- Edit private posts
+ Edit private products
+ Edit private shop coupons
+ Edit private shop orders
+ Edit private shop webhooks
+ Edit product
+ Edit product terms
+ Edit products
- Edit published pages
- Edit published posts
+ Edit published products
+ Edit published shop coupons
+ Edit published shop orders
+ Edit published shop webhooks
+ Edit shop coupon
+ Edit shop coupon terms
+ Edit shop coupons
+ Edit shop order
+ Edit shop order terms
+ Edit shop orders
+ Edit shop webhook
+ Edit shop webhook terms
+ Edit shop webhooks
- Edit theme options
- Edit themes	 Edit users
- Export
- Import
- Install plugins
- Install themes
- List users
- Manage capabilities	Manage categories
- Manage links
- Manage options
+ Manage product terms
+ Manage shop coupon terms
+ Manage shop order terms
+ Manage shop webhook terms
- Manage woocommerce
+ Manage woocommerce pos
- Moderate comments
- Promote users
- Publish pages
- Publish posts
+ Publish products
+ Publish shop coupons
+ Publish shop orders
+ Publish shop webhooks
+ Read
- Read private pages
- Read private posts
+ Read private products
+ Read private shop coupons
+ Read private shop orders
+ Read private shop webhooks
+ Read product
+ Read shop coupon
+ Read shop order
+ Read shop webhook
- Remove users
- Switch themes
+ Unfiltered html
- Unfiltered upload
- Update core
- Update plugins
- Update themes
+ Upload files
+ View woocommerce reports
- Wpseo bulk edit

**Comment by andymax** [comment]
I did a quick-fix like this:

function amx_add_woo_reports_menu() {
	if(current_user_can('view_woocommerce_reports') && !current_user_can('manage_woocommerce')) {
		add_menu_page('Rapporter', 'Rapporter', 'view_woocommerce_reports', 'menu-posts-reports', null, null, '55.6');
	}
}
add_action('admin_menu', 'amx_add_woo_reports_menu', 9);

**Comment by andymax** [comment]
Before the 'WooCommerce' -> 'Reports' menu was available. Now the 'WooCommerce' menu just have an empty placeholder.
