### ISSUE TITLE
Coupon calculation confusing customers

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7532]
Maybe related to #7510 

I have the same settings and a coupon of 100% discount.

So, prices excluding taxes, but show prices including tax on products and cart/checkout pages.

In the cart, if i apply a 100% coupon, it discounts correctly 20$ (the price of the product) but the totals show tax included for the product, but not for the coupon because it's applied before taxes.

So it shows 24.40$ (subtotal) - 20$ (coupon) = 0$ (total) which is confusing for customers

http://cld.wthms.co/YNle+

Can we add a text or something to inform the customer about the coupons applied before the taxes so it explains why 24.40 - 20 = 0 ?

**Comment by martinkarls** [comment]
The only reasonable solution for this would be for the coupons to inherit the settings from the price settings. If price is set to be viewed including tax then the coupon value should also be viewed including tax. The taxes would still be calculated in the same way but it would make a lot more sense for the customers.

I have not visited a single store where coupons is displayed in such a confusing manner so I'm having a hard time understanding why the WooCommerce developers think that this is a good way of doing it.

**Comment by martinkarls** [comment]
Thank you for the fix mikejolley!
