### ISSUE TITLE
Variations meta data not available on cart/checkout pages

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#7533]
It seems that since 2.3.3 variations meta data (weight, dimensions) aren't available on cart & checkout pages. Tested locally with WC 2.3.5.

At variation level:

![](http://cld.wthms.co/1kQ1u+)

At product level:

![](http://cld.wthms.co/1czTx+)

On cart page, var_dump( $_product ):

![](http://cld.wthms.co/ooGo+)

And checking package using:

````
function custom_woocommerce_cart_shipping_packages( $packages ) {

    foreach ( $packages[0]['contents'] as $item_id => $values ) {
        $product = $values['data'];

        var_dump( $product->get_dimensions() );
        var_dump( $product->get_weight() );
    }

    return $packages;
}

add_filter( 'woocommerce_cart_shipping_packages', 'custom_woocommerce_cart_shipping_packages' );
````

prints:

![](http://cld.wthms.co/17pMh+)

cc @mikejolley

**Comment by claudiosmweb** [comment]
Not really a problem. This is a protected variable.
You need to get this data from the package.

An example:

```
function custom_woocommerce_cart_shipping_packages( $packages ) {

    foreach ( $packages[0]['contents'] as $item_id => $values ) {
        $product = $values['data'];

        var_dump( $product->weight );
        var_dump( $product->length );
        var_dump( $product->width );
        var_dump( $product->height );
    }

    return $packages;
}

add_filter( 'woocommerce_cart_shipping_packages', 'custom_woocommerce_cart_shipping_packages' );
```

**Comment by corsonr** [comment]
Hey @claudiosmweb your snippet does return the package values for simple product, but **not for variation**
