### ISSUE TITLE
Product data table broken

### ISSUE THREAD

**Issue by insightint** [woothemes/woocommerce#7535]
After upgrading to the 3 newest versions of WooCommerce, I have not been able to add product data in correctly, most importantly, dealing with variations. I've tried downgrading versions and upgrading to the newest ones as you release them and nothing has fixed this. I cannot edit variations, create, or delete them and every field is expanded.

**Comment by mikejolley** [comment]
Sounds like a javascript error. See https://wordpress.org/support/topic/how-to-debug-issues-after-updates?replies=1

Thanks
