### ISSUE TITLE
Products with numeric titles aren't found in json_search_products 

### ISSUE THREAD

**Issue by osadi** [woothemes/woocommerce#7536]
WooCommerce: 2.3.5
A product with a title of say '1000' wont be found by the Up-Sells and Cross-Sells search on the Edit Product page.
It's treated as a numeric in the if/else and thus 's' is never passed in the $args to get_posts() in [json_search_products](https://github.com/woothemes/woocommerce/blob/966ca94e41a7a0b21b6237223e883a2f3f2d9769/includes/class-wc-ajax.php#L1543).

**Comment by claudiosmweb** [comment]
Just fixed in 742a48c3ebd064e320f4cab71bb2922e9d3522b1
