### ISSUE TITLE
Latest WooCommerse: Payment Method Duplicate

### ISSUE THREAD

**Issue by premiumwd** [woothemes/woocommerce#7539]
Hi,

When I installed latest version payment method shows twice.

**Comment by claudiosmweb** [comment]
Have you tried the default WordPress theme?
This is an issue with your outdated theme.

**Comment by premiumwd** [comment]
I create WordPress themes, so I am guessing I need to update the checkout file. You guys...

**Comment by claudiosmweb** [comment]
Check your system status for outdated templates.

**Comment by mikejolley** [comment]
And only include template files in your theme if you *actually* need to change them. Don't copy them all over.

**Comment by premiumwd** [comment]
I are you calling it in a hook now? Because it is happening also in my main website where I only added div classes for styling.
