### ISSUE TITLE
Return after custom woocommerce_add_to_cart_handler_

### ISSUE THREAD

**Issue by sebastianhaas** [woothemes/woocommerce#7543]
Hey!

I was wondering whether the return in [class-wc-form-handler.php:711](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-form-handler.php#L711) is really necessary. It makes it hard to implement a handler for an an additional product type without having a lot of redundant code. 
For example, the entire redirection part in `add_to_cart_action()` would have to be copied to the new handler function.

**Comment by mikejolley** [comment]
Yes its needed. Your action wouldn't be able to set $was_added_to_cart anyway, as that is only defined within the add_to_cart_action method.

**Comment by sebastianhaas** [comment]
Then why not pass `$was_added_to_cart` to `add_to_cart` in favor of `$url`? That way, the redirecting code could be kept in the original place.

**Comment by mikejolley** [comment]
Make a pull req if you have an idea. The hook you're talking about is an action though so you cannot pass in/back vars without globals which is messy.
