### ISSUE TITLE
checkout fails to submit

### ISSUE THREAD

**Issue by LucAwater** [woothemes/woocommerce#7545]
My woocommerce checkout is showing and up till this morning was working fine. But now when I try to submit the form I get this message: "We were unable to process your order, please try again". I haven't changed anything in the settings or plugins. I have updated woocommerce recently to 2.3.5. But still, everything worked perfectly after that. I really don't get what's going on here. I hope someone can help me out.

Thanks!

PS: I get this error message with everything, even when I leave a billing field open...

**Comment by LucAwater** [comment]
I found the function which throws the error message:
__________________
if ( empty( $_POST['_wpnonce'] ) || ! wp_verify_nonce( $_POST['_wpnonce'], 'woocommerce-process_checkout' ) ) {
    WC()->session->set( 'refresh_totals', true );
    throw new Exception( __( 'We were unable to process your order, please try again.', 'woocommerce' ) );
}
_________________
It's on line 351 in woocommerce/includes/class-wc-checkout.php

**Comment by mikejolley** [comment]
You have a nonce issue meaning either;

- you have a template override in the theme which doesn't output the nonce
- your checking is being cached (server or plugin caching)

This is not a core WC bug. https://wordpress.org/support/topic/how-to-debug-issues-after-updates?replies=1

**Comment by LucAwater** [comment]
Thanks for the feedback, i'll look into that.
