### ISSUE TITLE
Different taxes total if by date or code filter on same period

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#7546]
The following reports tabs do not return the same values on the same date range:

![](http://cld.wthms.co/12fSe+)

Taxes by code:

![](http://cld.wthms.co/142BY+)

Taxes by date:

![](http://cld.wthms.co/1ld0F+)

Both for "last month".

**Comment by mikejolley** [comment]
@corsonr You'll need to obtain a data dump and look into the orders. The reports do use different meta - the taxes by date uses the tax_total meta data, whereas taxes by code uses the line item tax totals. One of these will be mismatching in an order, possibly due to editing.
