### ISSUE TITLE
Fatal Error - Product Attributes

### ISSUE THREAD

**Issue by phillipsrw** [woothemes/woocommerce#7547]
Using Woocommerce and stylemag theme.

When I apply simple product attributes I get this error at the bottom of the page, and it doesn't show any attributes on the page. Any thoughts?

Fatal error: Call to undefined method WooCommerce::attribute_label() in /home/content/p3pnexwpnas10_data01/30/2481430/html/wp-content/themes/stylemag/woocommerce/single-product/product-attributes.php on line 54

**Comment by slash1andy** [comment]
Sounds like your theme is using an outdated WooCommerce template. You can disable that to fix this, but contact your theme dev. It's a theme issue, not a WooCommerce one.
