### ISSUE TITLE
Add WP CLI Support

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce#7551]
It would be great if we can add WP-CLI support for WooCommerce. That way developers who want to do things via the command line can do so. A good starting point would be doing the following:

* list products
* list coupons
* list customers
* list orders

Parameters can be passed along with the command to restrict those lists. Ex. you should be able to pass in an ID and it will list just that one product.

There are a million things we can do with WP-CLI but I think this is a good start.

**Comment by DavidAnderson684** [comment]
Is the effort better invested in WP-CLI, or in building a text-based client for the REST API? WP-CLI has the weakness of being something you can only run on the same machine as the website is on. A text-based client using the REST API could run from anywhere.

**Comment by maxrice** [comment]
Might be cool to have both, since they're really separate usages (local vs. remote) -- @DavidAnderson684 can you open an issue on https://github.com/kloon/WooCommerce-REST-API-Client-Library for a command line client?

**Comment by DavidAnderson684** [comment]
Will do. But, doesn't a command-line client that uses the REST API make any other command-line client redundant? Since "remote" really means "use from anywhere", rather than meaning "can't use locally".

**Comment by claudiosmweb** [comment]
@DavidAnderson684 this decided that we will integrate with WP-CLI. Now please, do what @maxrice said we can consider your idea.

**Comment by maxrice** [comment]
Yup you're right, though if someone's already comfortable working within WP-CLI they may prefer to continue using that vs. having to learn whatever set of commands the PHP client library offers :smile:

**Comment by aj-adl** [comment]
I feel as though listing things like mentioned above would have little use for developers, I would much rather expose woocommerce options and the data and tools listed under system status.

YMMV but I feel like I'd use this stuff (flush shop transients, clear sessions, check system status etc) much more from the command line than list products.

**Comment by mikejolley** [comment]
This one needs dev feedback and votes before scheduling in a milestone. I've moved to roadmap since I don't see this as a 2.4 item https://trello.com/c/bndJlemk/60-wp-cli-support

**Comment by stewarty** [comment]
I'd like to agree with @aj-adl.  WP-CLI support for the tools would be much more useful.

We currently have a situation where after every deploy we do, we need to clear the transients and user sessions.  Would be great to be able to build that into our deployment process via WP-CLI.
