### ISSUE TITLE
Filter to disable enhanced form selects

### ISSUE THREAD

**Issue by Einkoro** [woothemes/woocommerce#7554]
Previously there was a filter to disable enhanced selects:
https://github.com/woothemes/woocommerce/commit/0fdd24c526f113a30fd8b2996e1a82f88dd44db2#diff-e37d0d13a6cc8f7f5761f826b6534520

This no longer seems to be the case after moving from chosen to select2 and I need to disable it as I use a front end framework (Semantic UI) that provides its own dropdowns: http://semantic-ui.com/collections/form.html#search-selection-dropdown

**Comment by mikejolley** [comment]
No need for a filter - you can use http://codex.wordpress.org/Function_Reference/wp_dequeue_script to dequeue select2 on the frontend. Same amount of code required.
