### ISSUE TITLE
Account Page Endpoints Not Working

### ISSUE THREAD

**Issue by adamfisher** [woothemes/woocommerce#7556]
I have WooCommerce 2.2.10 installed. When you go to the page containing the [woocoommerce_my_account] shortcode and try to click the edit link for shipping or billing address, I get a 404 error.

I followed the directions in this article. I have tried flushing the permalinks and verified I don't have any of those pages already defined. I also disabled all plugins except for WooCommerce and flushed the cache with no resolution.

http://docs.woothemes.com/document/woocommerce-endpoints-2-1/

If I add code to my theme functions.php file to flush the permalinks on every page load then the edit pages show up.

**Comment by mikejolley** [comment]
> If I add code to my theme functions.php file to flush the permalinks on every page load then the edit pages show up.

This is indicative of another plugin, or the theme, also doing a permalinks flush at an incorrect time. If this happens, any endpoints will be broken.

Switch to twenty twelve, remove any 'fixes' you've made, save permalinks and retest.

Closing this as it isn't a core bug (no other reports, 2.2.10 has been around for months) and this isn't a support area. Thanks.

**Comment by Rezamae** [comment]
Hi I also have a problem with woocommerce my account. When I go to  /my-account/edit-account, nothing happens. Can you help me to this? Thank you!
