### ISSUE TITLE
Variations disappear when "hide out of stock items from the catalog" option checked

### ISSUE THREAD

**Issue by mikesmith778** [woothemes/woocommerce#7557]
Hi,

I have dozens of products that are discontinued, but I don’t want to delete them for SEO reasons. As a result, I have to check the “Hide out of stock items from the catalog” option under Wommerce > settings > Products > Inventory so they’re not visible to customers.

This works out pretty well, but I am now running into another problem: a lot of our shirt sizes we sell go out of stock regularly. We are using a plugin that allows users to enter their email when a size (variation) goes out of stock. With the "out of stock" option now checked, though, the variations that are out of stock now do not appear on our dropdown.

For example, if I am listing a shirt with sizes s, m, lg, xl, and s, m and lg are in stock, but xl is out of stock, the xl variable doesn't show up under the product dropdown.
 
This ONLY happens when the "out of stock" option is checked, like mentioned above. When it's not checked, the xl size does appear and a customer is able to enter their email.

Is there is a workaround for this? Checking the “hide out of stock items from catalog” option is vital for us, but at the same time, we obviously want customers who stumble upon a product to add their email address for an out of stock item.

Thanks!

**Comment by mikejolley** [comment]
Workaround would be to not hide out of stock products, and instead change the 'visibility' of your only-for-seo products to 'hidden', so that are not visible in the actual shop pages. Look by the save button for the visibility option.
