### ISSUE TITLE
Discount amount  problem with round 

### ISSUE THREAD

**Issue by theminjus** [woothemes/woocommerce#7560]
After applying coupon that has 10 % discount on cart  i have amount mismatch with 0.01 
coupon is 12.6455  not 12.65

in order total is calculated as 12.64 

![wordpress](https://cloud.githubusercontent.com/assets/2241448/6365859/e23e13d4-bcbd-11e4-9e29-eed05057b657.JPG)

**Comment by mikejolley** [comment]
Prices defined inc or ex tax?

**Comment by theminjus** [comment]
Exclude tax

**Comment by theminjus** [comment]
is checked as  inclusive

**Comment by mikejolley** [comment]
The amounts will have .005 rounding. If prices are inclusive of tax, this will be rounded half down to keep taxes correct. 

That said, I'm unable to replicate your issue so it has to be something specific to your tax and country setup. This is my result:

https://dl.dropboxusercontent.com/s/7m1hgdr97y8e24i/2015-03-02%20at%2012.30%202x.png?dl=0

You may want to show prices and totals inc. tax to reduce the likelihood of a display error - this is a maths issue though, not a bug afaik
