### ISSUE TITLE
Issues with Select2 in IE

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#7563]
Maybe this is just in themes based on Bootstrap:

![10984200_763592350385792_8833680133914736967_o](https://cloud.githubusercontent.com/assets/1264099/6373713/2a595d54-bceb-11e4-872e-00507a9a0fdc.jpg)

**Comment by jameskoster** [comment]
What's the issue? Just that it overlaps the navigation?

If this is a live site please share the link (or just tell me the theme) and we can adjust the `z-index` accordingly.

**Comment by claudiosmweb** [comment]
@jameskoster this state select2 input don't close or works. Just floating on the screen on top of all the other fields.

**Comment by jameskoster** [comment]
o_O

Is that the same for all instances of select2, or just this one? Latest IE?

**Comment by claudiosmweb** [comment]
It seems so, but I could not test this. Seems to be wrong in IE 9 to 11.
Some people complained about this to me, but I have IE to test xD

**Comment by jameskoster** [comment]
I guess I better fire up BrowserStack then xD

**Comment by claudiosmweb** [comment]
@jameskoster same problem ^

**Comment by claudiosmweb** [comment]
Seems to be fixed in 6658c88adc515b04d5b0cc709fe1f233f188be76
