### ISSUE TITLE
Coupons need to be applied after Tax for Canada

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7564]
As per Canadian [Tax laws](http://www.taxtips.ca/gst/coupons.htm) , Coupons need to be applied after the application of tax on the regular price. Currently Taxes are being calculated on the price after the discount has been applied.

Here is the tax before the coupon is applied  
![image](https://cloud.githubusercontent.com/assets/552016/6376002/ead66e50-bd40-11e4-9fb9-574c560e43f6.png)

Once Coupon discount is applied we get ![](http://cld.wthms.co/10WFk+)

Thus the tax is calculated on the price after the discount is applied, this needs to be changed for Canada. 

https://woothemes.zendesk.com/agent/tickets/263007  @seanreloaded @mikejolley

**Comment by mikejolley** [comment]
Only reimbursable coupons need to be applied this way - discounts with not equal monitory value do it out way according to the laws.

**Comment by mikejolley** [comment]
Non-reimbursable coupons

> These coupons are issued by the vendor, so the vendor is not being reimbursed by some other entity for the value of the coupon.  The coupon may entitle the customer to a reduction of a fixed dollar amount or a percentage amount.  With this type of coupon, the vendor can either
>
> - reduce the price of the item before calculating the GST or HST, so the tax charged is lower, or
bullet	
> - treat the coupons in the same manner as a reimbursable coupon, and charge the GST or HST on the full price of the item before deducting the coupon amount.

http://www.taxtips.ca/gst/coupons.htm

User can use smart coupons for the other type/gift certs.
