### ISSUE TITLE
update_totals_on_change issue for custom checkout field

### ISSUE THREAD

**Issue by Rajapress** [woothemes/woocommerce#7565]
1) Added a  custom checkout field using **woocommerce_checkout_fields** filter.
2) Added the class **update_totals_on_change** for the field to handle the update_order_review ajax call. 
3) Update order review is working only when i do change any of the core fields after changing the value of the custom field. Ajax call for the custom field  is normal as like the core field, (no js errors in the console).
4) When changing the custom field, it is not at all getting into the My Shipping module's **calculate_shipping()** method.

P.S Changing the value of Core field does enters in to calculate_shipping() method.
Please refer #7325 for detailed information.

Let me know if anything needs to be fixed. Thanks

**Comment by mikejolley** [comment]
There is no bug here sorry. I just added a field:

`
$this->checkout_fields['order']['test'] = array(
			'type'        => 'text',
			'class'       => array( 'update_totals_on_change' ),
			'label'       => 'Test',
			'placeholder' => 'Test'
		);
`

Changing the value does update totals - you can see the blockui overlay and totals refresh when doing this. Your problem has to be elsewhere.

**Comment by dokker** [comment]
I have the same problem.
The updating works as expected but the value of the custom field not reachable inside the calculate_shipping() method.

**Comment by saurabhj91** [comment]
@dokker Were you able to  get the custom field he calculate_shipping() method?

**Comment by dokker** [comment]
Finally I have approached my task from another direction. So no solution at me sorry.
