### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by Breeakker** [woothemes/woocommerce#7566]
Hello,

I have done the latest update on woocommerce.
Now I see in my shop just the productcategories but after that no products show up!
What now? Please help.

shop: 
zonnepaleis.nl/winkel/

**Comment by roykho** [comment]
So this is not the place to get support.  It is for bug reporting only.  I suggest you try saving out your permalinks again and see if they again.  Either that or try switching to 2012 theme and re-test.

**Comment by Breeakker** [comment]
Ok, get it.

BTW, old files replaced and shop is working again.

 

Thanx

 

Van: Roy Ho [mailto:notifications@github.com] 
Verzonden: woensdag 25 februari 2015 20:27
Aan: woothemes/woocommerce
CC: Breeakker
Onderwerp: Re: [woocommerce] Woocommerce (#7566)

 

So this is not the place to get support. It is for bug reporting only. I suggest you try saving out your permalinks again and see if they again. Either that or try switching to 2012 theme and re-test.

—
Reply to this email directly or view it on GitHub <https://github.com/woothemes/woocommerce/issues/7566#issuecomment-76036150> .  <https://github.com/notifications/beacon/AKriOAMnCrPzBif5J5Wl13H7PmiKKsfuks5nvhl9gaJpZM4Dl0do.gif> 



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
http://www.avast.com
