### ISSUE TITLE
Export report as CSV

### ISSUE THREAD

**Issue by richmilns** [woothemes/woocommerce#7568]
It seems that when I try to 'export as csv' from the reports screen, the downloaded csv file contains the HTML source code for the page rather than and CSV data?

Here is an example of what I mean:

![image](https://cloud.githubusercontent.com/assets/3609772/6388582/69fdbf2e-bd93-11e4-8b42-131625adbb38.png)

Seems to only affect the 'orders' reports tab.

I am using WooCommerce 2.3.5 with Wordpress 4.1.1.

WP Memory Limit: 64M - no warnings or errors on the WooCommerce status page.

**Comment by claudiosmweb** [comment]
Tested and works fine.
Try to check if it is not conflict with any plugin.

**Comment by richmilns** [comment]
Thanks for checking, I will investigate and report back.

**Comment by mikejolley** [comment]
#7580

**Comment by nicki-prestwick** [comment]
@mikejolley I'm having this same issue - I updated my reports.js and reports.min.js files like you suggested [here] (https://github.com/woothemes/woocommerce/commit/89704ef36ab064cceaecb5ff5b2b76b3ff8de859), but I'm still getting a CSV file that is made up of HTML exactly like the screenshot that Rich started this issue with. Anything else I should be looking for?
