### ISSUE TITLE
Auto-insertion of webhooks upon visual API authentication

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#7569]
Related to #6930.

When the store owner goes to authenticate a username for a particular service, it could be really useful to have the service be able to instruct WooCommerce to load URLs into specified webhooks.

This could be messaged on the login screen, as well as inside WooCommerce, with an option to not do this auto-insertion, affording the store owner control over doing this insertion manually.

This would remove a step for the store owner and make "installation" a non-issue, as there is no further action required from the store owner other than logging in with a WooCommerce username. :)

Thoughts @mikejolley @claudiosmweb @barrykooij @BFTrick ?

**Comment by maxrice** [comment]
if #6930 is implemented and the service obtains valid API keys, would it be easier for the service to make the necessary API calls to create the webhooks?

**Comment by mattyza** [comment]
Could be. Something to consider when we get to development of this.

The main objective is to ensure the customer has the option to have the
webhook auto-added upon authentication. :)

On Thursday, February 26, 2015, Max Rice <notifications@github.com> wrote:

> if #6930 <https://github.com/woothemes/woocommerce/issues/6930> is
> implemented and the service obtains valid API keys, would it be easier for
> the service to make the necessary API calls to create the webhooks?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/7569#issuecomment-76236508>
> .
>


-- 
Matt Cohen
Chief Product Officer, WooThemes

http://woothemes.com/
http://matty.co.za/

Ask me questions via Clarity: https://clarity.fm/mattcohen/

**Comment by mikejolley** [comment]
That actually makes sense. Lets continue discussion in #6930 - @claudiosmweb will be looking at that soon :)
