### ISSUE TITLE
Should $cart_item_data be considered when generating $cart_id for products sold individually?

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#7576]
I just got a second ticket concerning individually-sold products and Name Your Price. NYP filters the cart item data to store some info about the entered price. 

In turn this data is part of the data used by the `generate_cart_id()` method to create a unique cart key. The side-effect being that if a customer enters a new price, a different cart ID is generated, so the existing cart item isn't found and the item is added a second time even if it is marked as "sold individually". 

from [`includes/class-wc-cart.php`](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L864-L871):

```
// Load cart item data - may be added by other plugins
$cart_item_data = (array) apply_filters( 'woocommerce_add_cart_item_data', $cart_item_data, $product_id, $variation_id );

// Generate a ID based on product ID, variation ID, variation data, and other cart item data
$cart_id        = $this->generate_cart_id( $product_id, $variation_id, $variation, $cart_item_data );

// Find the cart item key in the existing cart
$cart_item_key  = $this->find_product_in_cart( $cart_id );
```

If an item is sold individually, then does the `$cart_item_data` really matter? Shouldn't it depend solely on the product and variation IDs? 

I don't know if this is something that other plugins are seeing.. I would think anybody who is filtering the `woocommerce_add_cart_item_data` would run into the same issue.

**Comment by mikejolley** [comment]
"sold individually" can work in a few different ways. For example, I have an extension that sells job packages. They are sold individually so that you can have a 1:1 relationship between a new listing and a package, however, you can add another package of the same ID with a 1:1 relationship between the package and a different listing. Sold Individually prevents qty edits per line.

Maybe you need a way to filter the cart_id instead so ensure this data is not taken into consideration? Feel free to do a PR for that and I'll review.

**Comment by helgatheviking** [comment]
That's a decent idea. I will try to look at it when I am not in training camp. 

I temporarily solved it for the ticket with a filter on `add_to_cart_validation` that loops through everything in the cart and checks the current item's `product_id` and `variation_id` against what is in the cart. I don't know if I want to make that a permanent part of NYP as it loops through the cart every single time *and* it could have implications with something like your jobs plugin.
