### ISSUE TITLE
lightbox image displays the alt-text and not the caption text

### ISSUE THREAD

**Issue by paddydaddy** [woothemes/woocommerce#7578]
Hi, 
In Canvas theme with woocommerce on a product page when selecting a lightbox image it displays the alt-text and not the caption text. The only way I can display the caption text is to leave the alt-text box clear.
here is the relevant page: http://stoneengravings.co.uk/sewp/product/sandstone-rockborder-housesigns
I raised a ticket about his with woothemes and the guy there reported back to me that this is a bug or a fault with the woocommerce code and should be reported to you guys. My apologies if I am doing this wrong, I am not a developer and I am a bit out of my depth here!
The woo guy tested this and reproduced the problem.
Regards steve

**Comment by jameskoster** [comment]
Fixed in https://github.com/woothemes/woocommerce/commit/0973dec1e33ed153441d8e5bd3976e5f4f4affe5

**Comment by paddydaddy** [comment]
Hi, as I said in my posting I am out of my depth here. I am guessing that you have fixed the code and that the lightbox will work correctly after the next update. Thank you for taking an interest and making the effort!
regards Steve

**Comment by jameskoster** [comment]
@paddydaddy, that's correct :-)
