### ISSUE TITLE
Receiving a PHP json_decode() "NULL" error 

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7579]
I keep receiving a PHP json_decode() "NULL" error 
Here's the code to which I'm referring:
```
$line_tax_data = json_decode($item_meta['_line_tax_data'][0]); 
var_dump($line_tax_data);
```
The above returns "NULL" likely because it's invalid JSON.

Here's a JSON string I receive if I attempt to print out:
```
a:2:{s:5:"total";a:0:{}s:8:"subtotal";a:0:{}}
```

When I run this through http://jsonlint.com/, I get an error.

https://woothemes.zendesk.com/agent/tickets/263026 @mikejolley @seanreloaded

**Comment by maxrice** [comment]
That data isn't JSON, it's serialized -- try `unserialize()` instead :smile:
