### ISSUE TITLE
Product Attribute order by custom ordering doesn't work

### ISSUE THREAD

**Issue by thasmin** [woothemes/woocommerce#7582]
I have a product attribute with the Order By set to Custom ordering. I've reordered the attributes on the variation tab to the way I want them and they don't reorder on the product page.

Looking at the code, it looks like Wordpress doesn't support ordering terms by menu_order. wc_get_product_terms changes the $args argument if orderby is 'menu_order' and then calls get_terms. get_terms doesn't support menu_item in its own $arg. It also doesn't allow 'menu_order' in its order_by.

http://codex.wordpress.org/Function_Reference/get_terms

**Comment by mikejolley** [comment]
You are correct about get_terms, but we don't use get_terms only. We use 'wc_get_product_terms' which handles the ordering. I've checked and this is working in both product attributes and with variations, so perhaps you're using a theme which does not make use of wc_get_product_terms.

**Comment by thasmin** [comment]
Confirmed, sorry about that.

**Comment by thasmin** [comment]
What confused me is that I was reordering the variations on the product page in the meta box. I have since found out that I should have been changing the order on the attribute page. 

The variations on the product page can be reordered when the page loads but changing the attributes removes that ability. Should that be filed as a separate bug?
