### ISSUE TITLE
Shipping calculator switches back on if you forget a field

### ISSUE THREAD

**Issue by asalkey** [woothemes/woocommerce#7583]
Here is my code:     
    add_filter('woocommerce_cart_needs_shipping', 'turn_off_delivery'); 

     function turn_off_delivery() {
         if($_SESSION['location-id']){
            $switch = false;
         }else{
            $switch = true;
      }
	        return $switch;
      }

When a user has a location-id session and forgets to fill out a field, they get an error and when they go back to fill out the missing field they then click checkout the calculator sets back to true some how giving them a delivery charge.

**Comment by mikejolley** [comment]
I don't see how this has any relevance to WC core. WooCommerce does not use $_SESSION['location-id'], nor PHP sessions for that matter.
