### ISSUE TITLE
oAuth issue

### ISSUE THREAD

**Issue by YasKuraishi** [woothemes/woocommerce#7584]
I am trying to use WooCommerce API but have not been able to go past authentication. My base string looks exactly as on http://developer.linkedinlabs.com/oauth-test/ when I key in same values but it still does not work. Even the signature generated via linkedlabs.com url do not work either and comes back with following authentication error:

`{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}`

Here is how whole oAuth signature and url is being generated:

    string nonce        = WooCommerceSecurity.GenerateNonce(32);
    string expires      = WooCommerceSecurity.UtcTimestamp(new TimeSpan(0, 5, 0)).ToString();
    string parameters   = string.Format("oauth_consumer_key={0}&oauth_nonce={1}&oauth_signature_method={2}&oauth_timestamp={3}", consumerKey, nonce, signatureMethod, expires);
    string stringToSign = string.Format("{0}&{1}&{2}", method, HttpUtility.UrlEncode(url), HttpUtility.UrlEncode(parameters));
    string signature    = WooCommerceSecurity.Sign(stringToSign, consumerSecret);
    string endpoint     = string.Format("?oauth_consumer_key={0}&oauth_nonce={1}&oauth_signature={2}&oauth_signature_method={3}&oauth_timestamp={4}", consumerKey, nonce, signature, signatureMethod, expires);

And here is WooCommerce class:

    public class WooCommerceSecurity
    {
        public static string Sign(string value, string key)
        {
            HMACSHA1 myhmacsha1 = new HMACSHA1(Encoding.UTF8.GetBytes(key));
            byte[] byteArray    = Encoding.UTF8.GetBytes(value);
            MemoryStream stream = new MemoryStream(byteArray);
            byte[] hashValue    = myhmacsha1.ComputeHash(stream);

            return HttpUtility.UrlEncode(Convert.ToBase64String(hashValue));
        }

        public static int UtcTimestamp( TimeSpan timeSpanToAdd)
        {
            TimeSpan ts = (DateTime.UtcNow.Add(timeSpanToAdd) - new DateTime(1970,1,1,0,0,0));
            int expires_int =  (int) ts.TotalSeconds;
            return expires_int;
        }

        public static string GenerateNonce(int length)
        {
            var nonceString = new StringBuilder();
            for (int i = 0; i < length; i++)
            {
                nonceString.Append(validChars[random.Next(0, validChars.Length - 1)]);
            }

            return nonceString.ToString();
        }
    }

**Comment by claudiosmweb** [comment]
The oAuth works fine.
You can have some examples how work with this in https://github.com/kloon/WooCommerce-REST-API-Client-Library/blob/master/class-wc-api-client.php#L324-L348

**Comment by maxrice** [comment]
@YasKuraishi what does your string to sign look like?

**Comment by YasKuraishi** [comment]
Hi, here is how the base string is looking like. Similar code works on another website but not on WooCommerce.

    GET&http%3a%2f%2fwaterway.lelander.com%2fwc-api%2fv1%2forders&oauth_consumer_key%3dck_9e680bf87f7ad53c661a6e9dc9ec4188%26oauth_nonce%3drsnBtjZPyA8K5iK2iduNvzxYaIUuSrde%26oauth_signature_method%3dHMAC-SHA1%26oauth_timestamp%3d1424999027

**Comment by maxrice** [comment]
Yeah that looks correct to me -- it could be your server that's calculating the signature incorrectly. Can you try on another server and see if it works?

**Comment by YasKuraishi** [comment]
@maxrice thanks man. Any suggestion about what could possibily be wrong with the server? 

Somebody else installed it on the server so I am gonna have to help her figure out what could possibly be wrong?

**Comment by maxrice** [comment]
@YasKuraishi unfortunately it's pretty hard to track down signature issues, typically I've found it's the theme or some plugin errantly filtering `get_home_url()`. Easiest way to confirm is to add `echo $string_to_sign; die;` [here](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L244) which'll tell you if what the server is calculating differs from the client side. good luck :smile_cat:
