### ISSUE TITLE
wp_lostpassword_url() returns not escaped url

### ISSUE THREAD

**Issue by dingo-d** [woothemes/woocommerce#7586]
When I have woocommerce enbled, `wp_lostpassword_url()` returns a `/?page_id=xxx&lost-password` where xxx is the page id of my account page with lost password option, and the & character is not inputted as `&amp;` but just as &, which gives error on validation 

`Error: & did not start a character reference. (& probably should have been escaped as &amp;.)`

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce/search?utf8=%E2%9C%93&q=wc_lostpassword_url

Escaped in the templates, has should be with `esc_url()`.

http://codex.wordpress.org/Function_Reference/esc_url

>This function encodes characters as HTML entities: use it when generating an (X)HTML or XML document. Encodes ampersands (&) and single quotes (') as numeric entity references (&#038, &#039).

Fix your theme ;)

**Comment by dingo-d** [comment]
Yeah, just realized that myself. Thanks anyway :)
