### ISSUE TITLE
Reviews rich snippet

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7587]
Reviews are missing the rich snippet `itemReviewed` which is required: https://developers.google.com/structured-data/rich-snippets/reviews?&hl=it

**Comment by mikejolley** [comment]
> If review is embedded into another schema.org type, using review property, then there is no need to mark up the itemReviewed property.

Just missing itemprop 'review' - we have 'reviews'

**Comment by jcastro91** [comment]
Although you changed `itemprop="review"` The issue is still there. The structured data tool is still showing an error: http://prntscr.com/9ouo38
