### ISSUE TITLE
Mail configuration: Different colors for header background and headlines

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7588]
I'd like to be able to setup a different color for the background color of the mail heading and for the headlines themselves:

![2015-02-27 16_53_57-roundcube webmail __ bestatigung deiner bestellung bei five roasters vom 23 feb](https://cloud.githubusercontent.com/assets/3307404/6415813/b4a84508-bea1-11e4-8401-1aa23f542a5b.png)

In this case the background color should stay as pink as it is configured, but the headlines should be black/grey. I do not have a color option under WC > Settings > Emails for setting up the color of the headlines, could this be added?

**Comment by mikejolley** [comment]
I'm not sure we need fine grain control over all headings/texts in emails. It certainly hasn't been asked for before as far as I can tell, and I'd hate for people to frankenstein their emails with clashing colours :)

If you want to tweak all styles, override the email-styles.php template via your theme. That contains the CSS rules for emails.
