### ISSUE TITLE
Feature request: Hook to separate sub categories from products on catalog pages

### ISSUE THREAD

**Issue by chrisvallely** [woothemes/woocommerce#7589]
When using the 'show sub categories and products' option, both are automatically added to the woocommerce loop with no hooks to separate the two. I'm trying to put them in two separate unordered lists and possibly put code between them but am having trouble figuring out any way to do this. It would be nice to have a hook or option available to let people separate the two as customers get confused when categories look just like products.

I made the categories take up two columns, but the column counter breaks the layout this way.

**Comment by mikejolley** [comment]
http://docs.woothemes.com/document/template-structure/

archive-product.php can be modified for this purpose.

**Comment by ralphonz** [comment]
Seems odd to put categories and products into the same unordered list.  Not very semantic.

**Comment by jaydeesigns** [comment]
I agree, it is odd and not semantic!

I ran across this request looking for a solution and ended up implementing a jQuery approach, maybe someone will find it useful:

Since all elements are in the same unordered list, I called for the last li element with the class ".product-category", and inserted a separator right after it:

```
var lastCat = jQuery('.products .product-category').last();
 jQuery('<div class="category-separator"></div>').insertAfter(lastCat);
```

after this I just needed to add css styles to my new separator div

`.category-separator {display: block; width:100%; overflow: hidden; height:0; border:1px solid #000; margin-bottom: 2.992em;}`

**Comment by andy-tschiersch** [comment]
Just copy archive-product.php from plugin-directory/template folder to your theme-folder/woocommerce to override them and do following changes to this file:

Original from Line 51 till 71:
`		<?php if ( have_posts() ) : ?>

			<?php
				/**
				 * woocommerce_before_shop_loop hook.
				 *
				 * @hooked woocommerce_result_count - 20
				 * @hooked woocommerce_catalog_ordering - 30
				 */
				do_action( 'woocommerce_before_shop_loop' );
			?>

			<?php woocommerce_product_loop_start(); ?>

				<?php woocommerce_product_subcategories(); ?>

				<?php while ( have_posts() ) : the_post(); ?>

					<?php wc_get_template_part( 'content', 'product' ); ?>

				<?php endwhile; // end of the loop. ?>`

Modify to:
`		<?php if ( have_posts() ) : ?>

			<?php
				/**
				 * woocommerce_before_shop_loop hook.
				 *
				 * @hooked woocommerce_result_count - 20
				 * @hooked woocommerce_catalog_ordering - 30
				 */
				do_action( 'woocommerce_before_shop_loop' );
			?>
			
			<?php
				// Kategorien im eignen ul-Container
				ob_start();
				woocommerce_product_subcategories();
				$subcats = ob_get_clean();
				if ( $subcats ) {
					echo '<ul class="subcategories">';
					echo $subcats;
					echo '</ul>';
				}
			?>
			
			<?php woocommerce_product_loop_start(); ?>

				<?php //woocommerce_product_subcategories(); ?>
				
				<?php while ( have_posts() ) : the_post(); ?>
					<hr style="clear:both;">
					<?php wc_get_template_part( 'content', 'product' ); ?>					

				<?php endwhile; // end of the loop. ?>`

**Comment by retroriff** [comment]
Overriding archive.php is not a good practice. It would be great to filter the archive products.

**Comment by jaydeesigns** [comment]
Hey @retroriff, @andy-tschiersch's is the recommended practice, copying the file from your WooCommerce templates folder and adding it to yourtheme/woocommerce/ will let you edit the template without the risk of losing changes when woocommerce gets updated.

**Comment by retroriff** [comment]
Hi @jaydeesigns, I know what you mean but I disagree. When WC launches a new update you are forced to update your duplicate templates. It is more risk free to use filters and hooks. Category archives are very important landing templates, with which sites get many visitors, therefore developers should be able to customize them as much as possible.

My opinion is that merging subcategories and products in the same <ul> is not a common practice, and should be optional. I really would appreciate more options filtering their content.

**Comment by studiolxv** [comment]
Cool idea jaydeesigns, tried it but ran into some weird woocommerce grid errors. Solved this with jQuery,  create a new ul before the product ul and send all li.product-category's inside of it. 

```
(function ($) {
    $(document).ready(function () {
        // create a new ul before the product ul
        $("ul.products").before($("<ul class='products product-categories columns-3'></ul>"));
        // send all li.product-category's inside of it.
        $("li.product-category").prependTo("ul.product-categories");
    });
})(jQuery);
```

**Comment by twoelevenjay** [comment]
I know this is 3 years old but this can be helpful if anyone else ends up here looking for this solution.

@andy-tschiersch, I try to avoid overriding template files as much as possible.

@studiolxv I also don't like the idea of using jQuery to rebuild the DOM when not necessary.

Here are the hooks / filters that the OP asked for.:

<script src="https://gist.github.com/twoelevenjay/a2195b052c4feb046d7f71fcae5c4d1b.js"></script>

**Comment by millionleaves** [comment]
@twoelevenjay Thanks for this - I'm going your route rather than overriding the template.

<vent>That said, why the code from @andy-tschiersch isn't in core boggles my mind. When was the last time someone said "Gee I'm really glad that my subcategories and products all run together in a single block"? </vent>

**Comment by shoaibgits** [comment]
@jaydeesigns what if we switch between Grid and List View?
