### ISSUE TITLE
guest unable to view cart if guest checkout is disabled

### ISSUE THREAD

**Issue by BHEADRICK** [woothemes/woocommerce#7590]
If guest checkout is disabled, a user can add an item to the cart and see that it's in the cart tab, but when visiting the cart page, the page says the cart is empty. - this is even with no caching enabled. 

This was introduced in 2.3.5

rolling back to 2.3.4 resolved the issue.

**Comment by roykho** [comment]
I can't reproduce this issue.  I tried it logged in and not logged in with no guest checkout.  Is this with no other plugins activated and default WP themes?

**Comment by mikejolley** [comment]
Same here - no issue.

Guest checkout has no bearing to the add to cart events - it simply enforces registration during checkout. I suspect your version change/issue is purely coincidental.

**Comment by BHEADRICK** [comment]
I tried reproducing this on a local install, and I wasn't able to reproduce either. I'm still not sure what was causing the problem, but it appears to be resolved now and I'm back on the latest version.
