### ISSUE TITLE
$wp_query->query['post_type'] returns null in Shop

### ISSUE THREAD

**Issue by chvillanuevap** [woothemes/woocommerce#7591]
Hi,

I encountered a PHP bug in my theme today.

I tried to access the post_type through the $wp_query in my Shop like so:

$wp_query->query['post_type']

However, this returns null. Upon further inspection, I realized that $wp_query->query returns:

Array ( [page] => [pagename] => catalog [wc_query] => product_query ) 

I switched to the theme Twenty-Thirteen and uninstall all of my plugins. However, the issue persisted. Is this intended behavior?

**Comment by technofreaky** [comment]
Hi,

Are you trying to get products using  wp_query. ?

**Comment by chvillanuevap** [comment]
Actually, the error is coming from the WordPress SEO plugin from Yoast.

In the plugin's latest version, in wp-content/plugins/wordpress-seo/frontend/class-breadcrumbs.php on line 325, the plugin tries to access the post type by doing $wp_query->query['post_type']. Of course, this call is done after performing a check with is_post_type_archive(), which returns true as we are in the Shop.

However, the interesting thing is that $wp_query->query_vars['post_type'] does return 'product' correctly.

**Comment by chvillanuevap** [comment]
Should the query not contain the same information as query_vars? Is this intended behavior?

**Comment by mikejolley** [comment]
Because the 'shop' page is a post type archive, BUT has a 'page' placeholder with content etc as well, these values may not match other post type archives.

Having said that, post_type does appear to be set correctly in my tests: https://dl.dropboxusercontent.com/s/h8s7wlal7mgkds7/2015-03-02%20at%2010.14%202x.png?dl=0

WooCommerce "fixes" the query before the main pre_get_posts - so perhaps you're just hooking in too early before this is set. See class-wc-query.php to see the logic.

**Comment by chvillanuevap** [comment]
In class-wc-query.php, in the function pre_get_posts( $query ), WooCommerce sets multiple values, for example:

$q->set( 'post_type', 'product' );
$q->set( 'page', '' );
$q->set( 'pagename', '' );

The function 'set' is defined in wp-includes/query.php, which modifies the query_vars variable, not the query variable.

So, if I print $wp_query->query['post_type'] I get a null because I am in page, but if I print $wp_query->query_vars['post_type'], I get 'product', which is correct.

Is this consistent with what you see? If so, the issue is related to the way WordPress SEO retrieves the post_type information.
