### ISSUE TITLE
API: cannot fetch by SKU containing "/" characters

### ISSUE THREAD

**Issue by consilience** [woothemes/woocommerce#7592]
REST in general has a bit of an issue with "/" characters in IDs, because you cannot [generally] add a slash to a path part without the web server interpreting it as a path part separator.

If you try to encode the slash (%1F) then an apache web server will either truncate the entire path at that point, or decode it into a "/", depending on its security settings. There is an option to "not decode", but then I believe WordPress does some decoding of the URL while calculating its routing. So it's a bit of a problem.

Taking a step back, some background. The REST API can give you a product by its ID or its SKU. The endpoint looks like this: /products/{id} or /products/sku/{sku} This means the SKU must be a part of the endpoint path. Slashes in SKUs are very common; they are a natural way of separating the logical parts of an SKU.

So we want to get product with SKU "MUSIC/CD/1234578". The API endpoint would be: /products/sku/MUSIC/CD/1234578. We could encode it to be /products/sku/MUSIC%1FCD%1F1234578 Neither work. We either get an "unknown route" or "missing consumer key" depending on whether the web server has truncated the URL at the first %1F or treated those characters as "/"s.

**Comment by consilience** [comment]
A workaround could be to allow SKU in the product filter. It is not there at present.

A workaround may be to replace slashes with the single-character SQL wildcard (_) but I have not tried this yet.

**Comment by consilience** [comment]
Here are some examples:

> curl --insecure 'https://example.com/wc-api/v2/products/sku/FX2-1%2F8X2-7%2F8X6?consumer_key=ck_3fb583a50073fc1ceeb5a3xxxxxxxxxx&consumer_secret=cs_2f4306e4f1e734a2765942xxxxxxxxxx'
> 
> {"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer Key is missing"}]}

> curl --insecure 'https://example.com/wc-api/v2/products/sku/FX2-1/8X2-7/8X6?consumer_key=ck_3fb583a50073fc1ceeb5a3xxxxxxxxxx&consumer_secret=cs_2f4306e4f1e734a2765942xxxxxxxxxx'
> 
> {"errors":[{"code":"woocommerce_api_no_route","message":"No route was found matching the URL and request method"}]}

**Comment by consilience** [comment]
Just tried using an underscore to match the slashes. and et the "no route" error again, which is a bit bizarre, because it works otherwise with valid SKUs, and as expected with invalid SKUs.

> curl --insecure 'https://greatfilters.com/wc-api/v2/products/sku/XXX?consumer_key=ck_3fb583a50073fc1ceeb5a3fdxxxxxxxx&consumer_secret=cs_2f4306e4f1e734a276594272xxxxxxxx'
> 
> {"errors":[{"code":"woocommerce_api_invalid_product_sku","message":"Invalid product SKU"}]}

Just checked, and it seems "-" is not handled in the routing well either. So a SKU of "XXX-XXX" gives an invalid route error.

My SKU is "FW2-5/8X2-7/8X4". 

* "FW2-5/8X2-7/8X4" returns an invalid route.
* "FW2-5_8X2-7_8X4" also returns an invalid route (can't explain that one).
* "FW2_5_8X2_7_8X4" returns an invalid SKU (presumably the _ character is being escaped).

So how do we work around this? Can SKU be added to the filter that is available for all API GET requests?

**Comment by maxrice** [comment]
IMO the best solution here is to allow searching for products via SKU as a GET /products filter, rather than trying to work around route handling. Reserver chars would be URL encoded then, which should fix this :smile_cat:

**Comment by claudiosmweb** [comment]
@maxrice I'm thinking about it, will be much simpler.

**Comment by judgej** [comment]
I was thinking about an extension to the filter too.

**Comment by judgej** [comment]
That "/" encoding should have been %2F, not %1F.

**Comment by claudiosmweb** [comment]
@judgej Very well observed.

But I'll leave it open to turn this into a filter in next version

**Comment by Nils-Fredrik** [comment]
@claudiosmweb Have you made any progress on this one? Do you want or need any help? I really need it, so I need to solve it anyway. I give the filter alternative +1.

**Comment by Nils-Fredrik** [comment]
Use `filter[sku]=<sku>` to test the proposed fix in  https://github.com/woothemes/woocommerce/commit/686c40919be64e4a9a17c77fcb86cb4e08a6c5db

**Comment by mac2000** [comment]
@Nils-Fredrik s patch works, thank you

**Comment by judgej** [comment]
Not had a chance to test it myself yet, but should do in a few weeks. Thanks for the feedback though - gives me hope :-)

**Comment by inventionlabsSydney** [comment]
Hi guys,

Is @claudiosmweb 's sku filter include going to be merged into master at anypoint? we're currently having a massive problem dealing with sku's with hyphens.

Please let me know.

**Comment by claudiosmweb** [comment]
@inventionlabsSydney the sku filter is present in 2.3.9. https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L592-L603

You can use:

```
wc-api/products?filter[sku]=YOUR-SKU-HERE
```
