### ISSUE TITLE
REST API: create product with custom metadata (FR)

### ISSUE THREAD

**Issue by consilience** [woothemes/woocommerce#7593]
Unless I am missing it, I cannot see anything in the documentation describing how to create a product with custom meta fields.

The `add_post_meta()` function can be used so long as the products are being created on the local site (that is my workaround, and only works for me because I am creating products on-the-fly through the API looped back to the local site).

It may be just something missing from the docs - http://woothemes.github.io/woocommerce-rest-api-docs/#parameters - but if not, could custom product metadata be supported by the products POST API route?

**Comment by claudiosmweb** [comment]
We have some actions like: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L1119

feel free to create the custom fields you want.

**Comment by consilience** [comment]
Unless I have totally misunderstood, how do I run these hooks on a remote WooCommerce site? I only have the API to send requests through, and those hooks are surely in a remote site that I may not own nor have the ability to add plugins or hook handlers to.

**Comment by consilience** [comment]
How do I reopen a ticket? It seems to have been closed on a misunderstanding of the problem, with no further discussion or clarification.

**Comment by claudiosmweb** [comment]
I understand perfectly, but you who were not able to understand.
Or you create a plugin to handle the data you want or you will play with the data that the API already accepted.

**Comment by consilience** [comment]
No sorry, what you say does not make sense to me. You have not explained how I can set custom meta fields for a product through an API if that API does not accept or do anything with those meta fields. If I am sending through an API from a platform that *may not even be WordPress* then how can a WordPress plugin help the sender deliver that data?

I fully understand what you are saying, and you are saying that I must install a plugin on the destination WooCommerce site, which may NOT be in my control. The API sender should not have to know what plugins may or may not have been installed in the recipient WC site.

If there is an official WC statement that says it has no intention of supporting custom meta field data through the API, then fine, but you are not pointing me to this. You are just giving me a workaround. I can apply a workaround myself without having to ask the project. What I am asking is whether WC will see itself to supporting this through the standard API.

**Comment by claudiosmweb** [comment]
We will not support save any data that is not predefined in our API.

We can't just save everything that comes through the API without proper validation and sanitization.
As I said, there alternatives for you.
Feel free to work with them.

**Comment by vlutton** [comment]
I have the same issue as consilence, we manage our products in our point of sale system and switch up our menu often and have quite a bit of metadata.  What are some of the other options out there?  I would really like to be able to automate the creation/update of the products through the api to ensure that our product catalog stays synchronized on both systems.  Thank you so much for your help!

**Comment by judgej** [comment]
@vlutton I did knock up a quick plugin to support this. You can find it here:

https://github.com/judgej/wc-api-custom-meta

It is installed on the WC site that needs to be updated via the API, and will accept data for any metafields. It is very simple and does not put any restrictions on what metadata can be updated. It's a start, it works, and we can take on from here if there are features that need adding. It is just on github - not released on wordpress.org - just download the zip file and install it.

The release zip file has the release number tagged onto the end, which is not ideal - remove that suffix from the plugin directory if you are trying this out.
