### ISSUE TITLE
Be able to find orders for a particular coupon

### ISSUE THREAD

**Issue by krogsgard** [woothemes/woocommerce#7594]
It would be really nice in WooCommerce to be able to get information of orders based on what coupon was used. Finding who used a particular coupon is really hard. It would be nice to filter orders by coupon used in WP List Posts, plus also something like Remi does here: http://www.remicorson.com/woocommerce-display-coupons-used-in-an-order-in-the-confirmation-email/

I'd qualify this as an "enhancement" but it sure would make tracking coupons easier.

**Comment by claudiosmweb** [comment]
Works with the search and going by the list of coupons you can check see orders:
![screenshot from 2015-03-01 23 10 11](https://cloud.githubusercontent.com/assets/1264099/6434465/3d121244-c068-11e4-808d-ca7c357ef246.png)

Just click and will filter like:

```
edit.php?s=COUPON_CODE&post_status=all&post_type=shop_order
```

**Comment by mikejolley** [comment]
They are also shown here: https://dl.dropboxusercontent.com/s/s2tqpb2s54uuadl/2015-03-03%20at%2011.00%202x.png?dl=0 :)

**Comment by krogsgard** [comment]
I looked for a really long time and never found this. Additionally, when I overview orders, this would mean I have to either go into the order or go to the coupons page to see what coupon was used for what. Imagine if 10 coupon orders came in... trying to filter out would be (and is) very difficult.

Would there be a way to do a filter on the main Orders listing to filter by a particular coupon? When I'm doing reporting and otherwise trying to figure out what's what in my store, I'd find that very useful.

**Comment by bekarice** [comment]
Thought this sounded interesting, wrote it: https://github.com/bekarice/woocommerce-filter-orders

**Comment by claudiosmweb** [comment]
Great work @bekarice

**Comment by bekarice** [comment]
thanks @claudiosmweb :)

**Comment by krogsgard** [comment]
@beka, You are awesome :) On it! I'll install and test it out. I still
propose it could be a decent core feature...

Brian Krogsgard
Krogsgard@gmail.com
Krogsgard.com
251.709.2224
