### ISSUE TITLE
Order processes without payment processor when no payment processor set as default

### ISSUE THREAD

**Issue by renegadesk** [woothemes/woocommerce#7595]
If a payment processor is set as default, but then deleted, a customer can checkout successfully without selecting a payment method and this puts the order into the status of processing without any payment processor mentioned in the order notes.

**Comment by mikejolley** [comment]
Steps I tried:

1. Activated and configured Stripe Payment Gateway - set as default.
2. Different browser, logged out, checked out. Added all data, before pressing place order....
3. Deactivated stripe gateway
4. Placed order
5. "Invalid payment method." error shown as intended.

The order did not go through. This is using 2.3.x master.

**Comment by renegadesk** [comment]
OK I'll post back when I get a fresh install and can replicate it again
