### ISSUE TITLE
Variation options not appearing in order emails or admin order list

### ISSUE THREAD

**Issue by rockethouse** [woothemes/woocommerce#7596]
This has only just started to happen. The email to admin and to the customer shows the Variations but no options / data - its just blank.

Its also blank when you click on the Items in the order list in the backend and hover over the [?]

BUT...

They appear when you click into the order in admin... so the data is being saved but just not being displayed in two areas...

I'm using the Addons plugin and both that and WP and WC are all up to date.

EMAIL (blank):
![image](https://cloud.githubusercontent.com/assets/5466694/6435763/4b4bcea4-c0f4-11e4-9e2a-1defab9a326a.png)

ADMIN ORDER LIST (blank):
![image](https://cloud.githubusercontent.com/assets/5466694/6435773/640d73c0-c0f4-11e4-8805-d760d998c202.png)

EDIT ORDER (appears!):
![image](https://cloud.githubusercontent.com/assets/5466694/6435777/7460146c-c0f4-11e4-9f51-c7b8681e9794.png)

Cheers

**Comment by mikejolley** [comment]
This is a bug in add-ons - working on a new version now.

**Comment by rockethouse** [comment]
Any ETA on this bugfix? I have a site waiting to go live that's all!? :)
