### ISSUE TITLE
Constant nag to update English US  Translation in the dashboard

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7599]
Getting constant Nag to download Latest update of EN_US translation

![](http://cld.wthms.co/1cuZK+)

Upon clicking the "Update translation", we get:

![](http://cld.wthms.co/sY13+)

Upon clicking the "Force Update Translation",  we get the below:

![](http://cld.wthms.co/19NCT+)

This is happening repeatedly in a loop.

https://woothemes.zendesk.com/agent/tickets/257623   @mikejolley  @seanreloaded

**Comment by claudiosmweb** [comment]
The native language is already en_US, no need to upgrade.
However, this user has changed language, have not installed it and went back to en_US.
You can just click to disable this message.
But I'll improve this feature to prevent show this message when linguage is en_US.
