### ISSUE TITLE
Re order of variable product causes disappearance of Attributes from the Order Backend and frontend

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7601]
Adding the test variable with 3 attributes for the first time:

![](http://cld.wthms.co/1hGxE+)

Once the order has been successful this is what we see in the back end, 

![](http://cld.wthms.co/4QfM+)

Observe the attributes of the variable product in the frontend :

![](http://cld.wthms.co/12QiI+)

Once we click the **Order Again** button that appeared above we get:

![](http://cld.wthms.co/5BxE+)

Here is the Re ordered order in the backend:

![](http://cld.wthms.co/1cNR1+)

Observe the attributes of the Re ordered variable product in the frontend :

![](http://cld.wthms.co/uBoC+)

https://woothemes.zendesk.com/agent/tickets/262888 @mikejolley  @seanreloaded

**Comment by mikejolley** [comment]
Can you replicate this @claudiosmweb? Mine are carrying over.

**Comment by claudiosmweb** [comment]
Working fine to me too.

**Comment by spraveenitpro** [comment]
Hi @claudiosmweb @mikejolley 

Please try with 3 custom attributes as I am again able to replicate it on local today.

**Comment by spraveenitpro** [comment]
Here is the System Status of the test setup:


```

### WordPress Environment ###

Home URL: http://localhost/learn
Site URL: http://localhost/learn
WC Version: 2.3.5
WC Database Version: 2.3.5
Log Directory Writable: ✔ /Users/Praveen/Sites/learn/wp-content/uploads/wc-logs/
WP Version: 4.1.1
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.2
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (2) ###

WooCommerce: by WooThemes – 2.3.5
WordPress Importer: by wordpressdotorg – 0.6.1

### Settings ###

API Enabled: ✔
Taxes Enabled: –
Shipping Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Shop Base: #1388 - /?page_id=1388
Cart: #1389 - /?page_id=1389
Checkout: #1390 - /?page_id=1390
My Account: #1391 - /?page_id=1391

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Twelve
Version: 1.6
Author URL: http://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –


```

**Comment by ChromeOrange** [comment]
@mikejolley @claudiosmweb Create a product with attribute like this https://dl.dropboxusercontent.com/s/ul5uk6w8bkipbt0/2015-03-04%20at%2012.34.png?dl=0 and variations like this

First Order : https://dl.dropboxusercontent.com/s/kw0zryw2c23nte5/2015-03-04%20at%2012.39.png?dl=0

Re-Order : https://dl.dropboxusercontent.com/s/jr57j5a8woa5e7z/2015-03-04%20at%2012.40.png?dl=0

@spraveenitpro you need to provide more info :)

**Comment by spraveenitpro** [comment]
sure @ChromeOrange  thanks :)

**Comment by mamamamia** [comment]
Could this bug be fixed ?

**Comment by mamamamia** [comment]
Sorry, I still do not know what to do with custom attributes, could someone let me know how to set it correctly? Thank you very much. Up til now I have done what ChromeOrange did as the attached images.

**Comment by daysie** [comment]
we find the problem ,  products add-on does not support variable product it’s so strange product add-on in conflict with woo commerce made by the same people …???
