### ISSUE TITLE
'States' Dropdown on the checkout page when Country is 'India' not working on IE 11.0.9600.17633

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7602]
When the customers select a shipping and billing address with India as country, the checkout page opens a drop down menu for "Select State" .
Now no matter how many times you click on 'the State',  the drop down never closes and the customer cannot continue the checkout.

![](https://woothemes.zendesk.com/attachments/token/1tzyvABp2ezLqngBEwPFFarXb/?name=Capture2.PNG)

https://woothemes.zendesk.com/agent/tickets/261630   @mikejolley @seanreloaded

**Comment by claudiosmweb** [comment]
We have see this before in #7563
