### ISSUE TITLE
Custom price input qty

### ISSUE THREAD

**Issue by michaeltieso** [woothemes/woocommerce#7604]
![screenshot](http://cld.wthms.co/197a6+)

I'm not sure if this is intended. I'm using **Custom Price Input** add-on. Adding to the qty will multiply whatever value I have in my input. Can we have the option to not do that? Only the first time seeing this from a customer so not sure it's something that's needed much attention if it's anything too complicated.

**Comment by mikejolley** [comment]
@michaeltieso this is the wrong place to log such an issue, plus this is product addons, not 'custom price input' addon? The above makes sense  - you define the product price as 2, so if you buy 2 it must double. To disable qty, check the 'sold individually' box.

**Comment by michaeltieso** [comment]
@mikejolley Please forgive me. It was logged in the wrong repository.
I understand why it occurs which is why I logged this issue.
