### ISSUE TITLE
woocomerce cart is empty after adding products

### ISSUE THREAD

**Issue by aidadev** [woothemes/woocommerce#7606]
I use woocommerce on wordpress, have one problem with checkout. both 2 buttons("Update Cart" and "Proceed to checkout") aren't working, they redirect to empty cart page. I noticed that all is working after some minutes. This make me think that something is wrong with sessions or cookies. I use 2.1.12 version of woocommerce.

Thanks.

**Comment by SiR-DanieL** [comment]
Please update WooCommerce to the latest version and test this again. Thanks!

**Comment by aidadev** [comment]
ok really think this will be quick solution. thanks

**Comment by aidadev** [comment]
Hi again, I've updated but now there is one problem that when I'm logged in only in that time I can see items in cart, but when I'm logged out cart is empty. How can I show cart for both case?

**Comment by mikejolley** [comment]
It sounds like you have a caching issue - either a plugin or server cache. The cart/checkout etc pages need to be excluded from cache. 

http://docs.woothemes.com/document/configuring-caching-plugins/

**Comment by aidadev** [comment]
But what can be the problem if I don't use any caching plugin?

**Comment by mikejolley** [comment]
Pretty sure you will be..
