### ISSUE TITLE
Coupons providing Free shipping to all the products even though their usage is restricted to Specific Products

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7607]
I have a coupon that is restricted to Product A and Product B while providing Free shipping:

![](http://cld.wthms.co/1dYRv+)

![](http://cld.wthms.co/1e1t6+)

Now when checkout with Product D for which the coupon does not apply, when I enter the coupon It adds free shipping for Product D

![](http://cld.wthms.co/15Llk+)

https://woothemes.zendesk.com/agent/tickets/265548

@mikejolley @seanreloaded @claudiosmweb @ChromeOrange

**Comment by mikejolley** [comment]
@spraveenitpro free shipping doesn't work like that. Free shipping is a shipping method which must apply to the ensure cart. The coupon makes the user eligible for free shipping. All the other coupon options do not apply to this - those are only for the actual value of said coupon.
