### ISSUE TITLE
Payment with a coupon code not working properly with Paytrail (Finland)

### ISSUE THREAD

**Issue by Karkelo** [woothemes/woocommerce#7608]
I went through the records and noticed that starting from 16.02.2015 all the orders with coupon codes paid through Paytrail have problems.

Here is what happens:

When making a purchase, the webstore shows the correct price. But when the customer moves to Paytrail to make the payment, there is an additional reduction to the price. The reduction seems to be approx. the same as Finnish VAT which is 24%.

Our Woocommerce dashboard shows the right amount, but Paytrail does not. Paytrail then sends us the amount of money that is in their system.

We are using up to date Woocommerce and Paytrail payment gateway.

**Comment by mikejolley** [comment]
PayTrail sends the prices and may need an update. Update to the latest release, and put a ticket in with support if its the WooThemes PayTrail extension support.woothemes.com
