### ISSUE TITLE
WooCommerce overrides 2 Things...

### ISSUE THREAD

**Issue by ranulheinzberg** [woothemes/woocommerce#7612]
Hi there! :-)
I've installed WooCommere and it was like woow! – There is only one thing that it overwrites
- the "Hide Page Title" and
- one PlugIn called "Custom Sidebars" - so the customization does not take place anymore.

So please tell me what to do!
Best regards,
Wolfgang Schmidt

If it is helpfully for you – here is my ### WordPress Environment ###

Home URL: http://www.ranulheinzberg.at
Site URL: http://www.ranulheinzberg.at
WC Version: 2.3.5
WC Database Version: 2.3.5
Log Directory Writable: ✔ /home/www/web528/html/wp-content/uploads/wc-logs/
WP Version: 4.1.1
WP Multisite: –
WP Memory Limit: 96 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.26
PHP Post Max Size: 32 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.40
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (15) ###

Akismet: by Automattic – 3.0.4
Contact Form 7: by Takayuki Miyoshi – 4.1
Custom Sidebars: by WPMU DEV – 2.1.0.2
Get page IDs: by Ionut Staicu – 1.0.2
Image Widget: by Modern Tribe
Inc. – 4.1

Really Simple CAPTCHA: by Takayuki Miyoshi – 1.8.0.1
SoundCloud Shortcode: by SoundCloud Inc. – 3.0.2
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri
INC – 1.7.6

WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0
WooCommerce German (de_DE): by David Decker - DECKERWEB – 3.2.0
Woocommerce Poor Guys Swiss Knife: by Uli Hake – 2.2.4
WooCommerce: by WooThemes – 2.3.5
WP-FileManager: by Anant Shrivastava
Johannes Ries – 1.4.0

WP to Twitter: by Joseph Dolson – 3.0.0
xfile: by xfile – 1.7

### Settings ###

API Enabled: ✔
Taxes Enabled: –
Shipping Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### WC Pages ###

Shop Base: #4191 - /shop/
Cart: #4192 - /cart/
Checkout: #4193 - /checkout/
My Account: #4194 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Music
Version: 1.1.9
Author URL: http://www.themify.me
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Hi @ranulheinzberg. This is our bug tracker, not a support area. 

I assume the 2 plugins you are talking about affect your theme's templates - WC has its own single and archive templates for products so you may need to customise these, or ensure your plugins support custom post type archives (e.g. the shop page is not a page, its a custom post type archive which can affect conditional logic).

Good luck.

**Comment by ranulheinzberg** [comment]
Thanks for your quick reply!
Best greetings!
