### ISSUE TITLE
Updated Dutch translation

### ISSUE THREAD

**Issue by 10tje** [woothemes/woocommerce#7614]
After the latest update of WooCommerce I missed some translation in the Dutch language file. Also some translation are not translated as we use it in Dutch. So I updated the language file for Dutch.

Couldn't find a place where to submit it, so the right place is here I guess. You can download/use the translation here: http://www.ten.sh/woo/woocommerce-nl_NL.zip

**Comment by claudiosmweb** [comment]
The right place is on Transifex: https://www.transifex.com/projects/p/woocommerce/
