### ISSUE TITLE
[FR] Provide access to WC_Product::get_dimensions() formatting

### ISSUE THREAD

**Issue by judgej** [woothemes/woocommerce#7617]
The get_dimensions() method provides the dimensions for a product, formatted in a set order, with set separators and always with the dimension units on the end.

https://github.com/woothemes/woocommerce/blob/f2fc3b151f7e4a9273f81e195910afb1fdb0d2ea/includes/abstracts/abstract-wc-product.php#L1416

It would be helpful to be able to provide an alternative format for sites or products that need it.

For example, when selling filters (and I am setting up a shop with 1.7 million of the things) the order of the dimensions is generally "width x length x depth" and not the WC built-in "length x width x depth".

Other extensions that a shop may want to add, is to provide alternate units for the dimensions, so it could display in both inches and cm. Other sites may want to display UTF-8 fractions instead of decimals (e.g. my filter files 9⅞ instead of 9.875).

I would suggest a filter could do this, given $this (WC_Product) as a parameter. The filter could overwrite the dimensions string entirely if a different format is needed. Or maybe a pre-filter, so an alternate format can be injected at the start, to avoid creating the default format that subsequently gets thrown away.

I realise this can all be taken out to the theme, but since WC goes to all the trouble of formatting the dimensions in a core method, it seems a shame to have to duplicate a bunch of templates for customising for the sake of a filter.

**Comment by judgej** [comment]
Cool - perfect - thanks.

**Comment by ESiebrandt** [comment]
This is a great addition - thanks. One thing though: With the formatted dimensions, JS updates the values on the fly if a variable product's variations are changed. Possible to have this with unformatted values as well?
