### ISSUE TITLE
Woocommerce store manager role bug

### ISSUE THREAD

**Issue by Tetragon** [woothemes/woocommerce#7619]
When updated to woocommerce 2.3.5 the store manager role isn't able to edit or roll out the "product data" fields.
Same for adding a new product, also not possible to open the "product data" field.

Working with Wordpress 4.1.1 and Woocommerce 2.3.5. Before update of WC 2.3.5 everything was working well.

**Comment by mikejolley** [comment]
Sounds like a javascript error possibly caused by an outdated extension. Update/disable other plugins, or check your browser javascript console to view the error.

**Comment by Tetragon** [comment]
Can you help with the errors?
