### ISSUE TITLE
wc_print_notices and related fail tests

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7624]
`wc_print_notices`, `wc_print_success_notice`, `wc_print_error_notice` and `wc_print_info_notice` always fails for me with this error

![](http://cld.wthms.co/1artV+)

It's because we have the indentation in the notices templates. We should remove the tabs when printing them.

**Comment by mikejolley** [comment]
@barrykooij Is going to review this and the other tests tomorrow.

**Comment by barrykooij** [comment]
![983](https://cloud.githubusercontent.com/assets/2846594/6503295/d075689a-c32b-11e4-88a7-31f9e5e858f2.gif)

**Comment by barrykooij** [comment]
f699f5102cbb1d5ff8f027d6f932073a7b303364

**Comment by barrykooij** [comment]
Fixed.
