### ISSUE TITLE
Allow REST API only over HTTPS

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7626]
Since seems that using API on HTTP without an SSL certificate mostly causes issues with the connection, can't we allow only HTTPS to use the API?

This would save both us and users a lot of headcaches.

Any thought @claudiosmweb ?

**Comment by claudiosmweb** [comment]
The API works perfect with HTTP, you just need to use oAuth.
Don't have any issues with the connection, but I see just with people who do not know to use oAuth.

Allow HTTPS only will close the door to a lot of people, we can't do something like this.

**Comment by ChromeOrange** [comment]
@claudiosmweb can you improve the docs for oAuth then please - there a lot of people who can't get it to work

**Comment by claudiosmweb** [comment]
@ChromeOrange The current documentation is enough, what changes is the way they do in every programming language.
http://woothemes.github.io/woocommerce-rest-api-docs/#over-http
