### ISSUE TITLE
woocommerce_recently_viewed cookie makes varnish caching impossible on most hosting platforms

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7628]
I use the varnish that comes with my hoster. I use gandi.net, but DreamHost, wpengine and pathogen have the same setup: I can use the "global" varnish cache infront of my hoster and "configure" it with Cache-Control and Purge but I cannot directly setup my own varnish vcl config.

I do not use the Recently Viewed products widget. 

I have the problem that whenever a user visits any product page the `woocommerce_recently_viewed` cookie is set, meaning that thereafter caching does not happen anymore. 

I guess you have no chance to notice whether the Recently Viewed products widget is used or not, right? If you could, you might only set this cookie if done so.

Otherwise, could you provide another way to disable setting this cookie. Maybe an extra option under WC > settings in the admin backend, or just a variable in wp-config.php would also do imho.

**Comment by jnachtigall** [comment]
After looking at [these lines of code](https://github.com/woothemes/woocommerce/blob/d9455994c8399c151c2d749a895bc307963515e3/includes/wc-product-functions.php#L485) it seems like I just need to remove this action from within my child theme's function.php:
```
// disable setting of woocommerce_recently_viewed cookie for easier caching with varnish
remove_action( 'template_redirect', 'wc_track_product_view', 20 );
```

**Comment by HOSTED-POWER** [comment]
Still suffering from this today, isn't there any better way of supporting this?

**Comment by kevin25** [comment]
The same for me. I can't remove woocommerce_recently_viewed
