### ISSUE TITLE
Issue with wc_update_product_stock_status()?

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7630]
I can't get this test to pass. It passes the first assert but then does not change the stock status back to `instock` and fails the second assert.

Any idea why? Is there any issue with the function or with the test?

```
	/**
	 * Test wc_update_product_stock_status()
	 *
	 * @since 2.3
	 */
	public function test_wc_update_product_stock_status() {
		$this->_get_product();

		update_post_meta( $this->_product->id, '_manage_stock', 'yes' );

		wc_update_product_stock_status( $this->_product->id, 'outofstock' );
		$this->assertEquals( 'outofstock', $this->_product->stock_status );

		wc_update_product_stock_status( $this->_product->id, 'instock' );
		$this->assertEquals( 'instock', $this->_product->stock_status );

		$this->_delete_product();
	}
```

**Comment by mikejolley** [comment]
The function gets a product and sets status:

`
$product = wc_get_product( $product_id );
$product->set_stock_status( $status );
`

Your product object will be out of date after running this.
