### ISSUE TITLE
How to manage stock in variations

### ISSUE THREAD

**Issue by sylviafit** [woothemes/woocommerce#7632]
I'm wondering if someone here can help me.

I have my woocommerce online since a couple weeks and I can't find a way to set the inventory stock in the variations. For example. I sell swimsuits/bikinis I sell the top and the bottom in the same product page but my clients can choose from different sizes for top and bottom, some styles have different colors as well. How can I manage the stock if I have for example only one top in small pink? it can be bought with any sizes of bottom but when it sold that small pink top has to turn out of stock. I tried and tried but I can't find how to do this and I really need it to work.

Thanks for your help.

**Comment by mikejolley** [comment]
You would need an explicit variation per stock managed variation. i.e. small + pink, set stock a variation level. This would be needed for all combinations.
