### ISSUE TITLE
Why is select2 not used on a WooCommerce selects?

### ISSUE THREAD

**Issue by wpexplorer** [woothemes/woocommerce#7633]

**Comment by claudiosmweb** [comment]
?

**Comment by bordoni** [comment]
Because it's a huge change to go from Chosen to Select2 without creating bugs, but I think they have the intention of doing.

**Comment by wpexplorer** [comment]
@bordoni - ah nice. Yes because it looks strange having some selects look "nice" while others are just plain browser selects.
