### ISSUE TITLE
Welcome Page Badge

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#7634]
IMO Welcome Page WooCommerce badge should be responsive in smallscreen devices. Additionally enqueue the stylesheet rather than using `admin_head` hook for WC welcome dashboard pages as all the admin pages is printing those style rules.

![capture](https://cloud.githubusercontent.com/assets/3774827/6502747/5bf0e7ec-c34e-11e4-9f09-290b1b72d54e.PNG)

**Comment by mikejolley** [comment]
This is likely to change in #7829
