### ISSUE TITLE
Totals are not updated in mini-page.php

### ISSUE THREAD

**Issue by adnanoner** [woothemes/woocommerce#7635]
I'm loading the shopping cart as a sidebar through the mini-page.php template. Totals are only updated when we are in checkout or cart page. Would be nice to also update totals when we're on the mini-page. Is there a reason why this is not done?

`if ( is_checkout() || is_cart() || defined('WOOCOMMERCE_CHECKOUT') || defined('WOOCOMMERCE_CART') ) {`

https://github.com/woothemes/woocommerce/blob/7fa0ee5004b3980603faa4589b83fc289f334fdf/includes/class-wc-cart.php#L1290

**Comment by mikejolley** [comment]
To avoid running all calculations/getting shipping quotes on each and every calculate event.

**Comment by adnanoner** [comment]
Hi Mike, sorry to open this up, but how would I calculate the shipping in the mini-cart? I'm using your table rate plugin. I thought I could update the shipping by using:

	WC()->shipping->calculate_shipping( WC()->cart->get_shipping_packages() );

However get_shipping_packages is returning an empty rates array.

P.s. I still think that you should be able to do shipping calculations in the mini-cart page. Just selecting the cheapest option will ensure the customer knows the shipping costs upfront.
