### ISSUE TITLE
Shipping Calculator Postal Code Not Required

### ISSUE THREAD

**Issue by nobleclem** [woothemes/woocommerce#7637]
The shipping calculator doesn't seem to obey the postal code local settings.  Its always requiring a postal code for all countries.  This causes a problem when doing shipping rate lookups with the UPS extension and I am sure other shipping extensions as well.

Reproduce with:
Select Bahamas as your country.  Now its requiring Postal code when this country has no postal codes. However if you select Bahamas on the checkout page the postal code field disappears as it should.

**Comment by bryceadams** [comment]
@mikejolley @ChromeOrange looks like this is also impacting on UPS, as we're checking for the post code before returning a rate but of course in these cases, a post code isn't required or even input, so the rate can't be calculated.

We should probably get this into a minor update before the next point release.
