### ISSUE TITLE
Update Product Variations

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#7642]
Hi,

I have a customer who uses product variations. Each half an hour, he wants to update their stock programmatically. Will this code work for product variations? I know it works for products.

PUT https://www.XX.ca/wc-api/v2/products/2823?stock_quantity=109&consumer_key=X&consumer_secret=X HTTP/1.1
Authorization: Basic XX=
Content-Type: application/x-www-form-urlencoded
Host: www.XX.ca
Content-Length: 36
Expect: 100-continue
Connection: Keep-Alive

{"product": {"stock_quantity":109} }

**Comment by claudiosmweb** [comment]
Use the variation ID.
