### ISSUE TITLE
Wp-Lister and Woocommerce Interaction issue

### ISSUE THREAD

**Issue by ABDpromotions** [woothemes/woocommerce#7645]
WooThemes ticket #266965 was opened by customer to investigate a possible bug in how WooCommerce handles orders processed by WP-Lister. 

Their concern is that they recently received an order for the same product twice. Once from WP-Lister and the other from WooCommerce, even though the WP-Lister order was processed a few minutes earlier than the WooCommerce order was received. The product was set to not allow backorder, yet after both transactions were completed the quantity in WooCommerce was -1.

Below is a detailed description as provided by the customer on the ticket:
There has been another occasion where two orders for the same product were very close together - within about 5 minutes. The last time, the product was purchased first on eBay - and within the time it took until WP-Lister fetched new orders again (< 5min) it was purchased on WooCommerce as well.

This time however, wasn't WP-Lister doing anything wrong at all: The item was purchased on eBay at 7:05pm - and this order was processed 1 minute later by WP-Lister, at which time the stock was reduced from 1 to 0:

But regardless the fact that the stock for this product was zero at 7:06pm, WooCommerce still allowed another customer (who obviously had added the item to the cart before 7:06) to purchase the same product at 7:11pm:

If even says in the order notes "Item #134731 stock reduced from 0 to -1. added on February 28, 2015 at 7:12 pm". Mind you: that order note was created by WooCommerce itself - which effectively sold a product which wasn't in stock at that time!

**Comment by mikejolley** [comment]
This is related to https://github.com/woothemes/woocommerce/issues/5966

When you pay via paypal, between checkout, payment, and the IPN coming back there will be a short period where stock is not reduced. Issue #5966 explains it - will be tackled in the future. Shop owner could increase out of stock level to say 1 instead of 0 to reduce the likelihood of this occurring since they are selling from outside too.
