### ISSUE TITLE
"Hide shipping costs until an address is entered" not behaving as expected

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#7650]
@jameskoster , @mikejolley is blaming you for this :)

Basically, if the "Hide shipping costs until an address is entered" and I'm logged out then there is no where for me to actually enter my address :/ In both of these screen shots I am logged out on the cart page

![](https://dl.dropboxusercontent.com/s/ep86jpk97rpn5ws/2015-03-06%20at%2011.08.png?dl=0)

![](https://dl.dropboxusercontent.com/s/dyktlhu6ix57ec6/2015-03-06%20at%2011.09.png?dl=0)

**Comment by jameskoster** [comment]
Could you give that a try please @ChromeOrange ? `shipping-costs` branch.

**Comment by ChromeOrange** [comment]
@jameskoster think I'm going to say no with that one :)

1[](https://dl.dropboxusercontent.com/s/5skkvpq01ly9q8i/2015-03-06%20at%2014.06.png?dl=0)

**Comment by jameskoster** [comment]
wat, I'm not seeing that o_O

**Comment by ChromeOrange** [comment]
@jameskoster @mikejolley This works, thanks James
