### ISSUE TITLE
Decimal precision of totals in REST API response

### ISSUE THREAD

**Issue by stayhero** [woothemes/woocommerce#7652]
We have an online invoicing SaaS service used by a couple of Woocommerce merchants and we have the following issue:

The decimal precision in the wp-api/orders REST method is rounded to 2 decimals. This is a problem as the line items are returned as net prices. Under some circumstances we see rounding errors. Example:

VAT (Tax rate): 19% 
The merchant needs to enter the final price as gross price (incl. taxes).

Product A should cost €84.00
Product B should cost €10.00
Product C should cost €8.50

Add this up and you get a gross total of €102.50. This is the final price the buyer pays. 

On the other hand the API is returning these prices as net prices in the wp-api/orders call like this (see https://gist.github.com/stayhero/20fd1420a2c654a26b75).

Product A net total: €70.59
Product B net total: €8.40
Product C net total: €7.14

The net prices sums up to a net total of €86,13. Add 19% VAT (86.13*1.19) and you get a gross total of €102,4947, which is rounded to €102.49. This a cent lesser than the correct total should be.
To properly calculate the taxes and use the net product prices we would need the net prices with a higher precisions (like 5):

Product A, gross: €84, precise net: €70.58823
Product B, gross: €10.00, precise net: €8.40336
Product C, gross: €8.50, precise net: €7.14286

Which adds up to €86.13445 net, or 86.13445*1.19 to €102.49999 gross, or rounded to €102.50.

Is there a specific reason why the API rounds the totals to a precision of 2 ?

You might think that we could calculate the original gross product price by adding the total and total_tax values. Unfortunately this is not a reasonable option because e.g. in case the merchant is using Coupons (using a Plugin) the coupon value is already substracted from the total. 

Another alternative would be to include the original gross prices in the API results. Both options would be the most straight forward way to let third party applications properly calculate the taxes (VAT). Everything else (like adding total and total_tax) is more kind of a hack.

Additionally, the API should also return the applied VAT rate for each line item in the result. Currently we calculate the VAT rate by dividing the tax amount by the net amount ( total_tax / total ). In the above example for the product costing €84 gross the result is 13.41/70.59*100 = 18.997. We round that amount to 19.0 but... that's again a bit of a hack. 

Cheers
Christian

**Comment by barrykooij** [comment]
@stayhero did you set the 'Number of Decimals' option in WooCommerce settings to 5?

@claudiosmweb I'll pick this one up.

**Comment by stayhero** [comment]
@barrykooij  Yes. The shop of the affected merchant is running on WooCommerce V2.3.5. The changes on the "Number of Decimals" setting had no effect. 

From a quick glance, if I'm not totally wrong, the rounding is done in 
https://github.com/woothemes/woocommerce/blob/master/includes/api/v1/class-wc-api-orders.php#L125

and is therefore hardcoded to 2?  

Honestly I think most merchants would not like to see their prices and order confirmations with a higher precision than 2. But internally it should calculate with a higher precisions (and return this higher precision via the API). Although I'm not sure if other API consumer rely on retrieving the rounded amount? 

That said, I guess there should be separate option for a precision in the API, or, by default, do not round the prices in the API at all. 

If that is not an option I personally would prefer to simpy retrieve the gross price on a line item level via the API.

**Comment by stayhero** [comment]
Correction: The rounding for API v2 happens here:

https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-orders.php#L1452

Still hardcoded. BTW: I tested with API versions v1 and v2.

**Comment by claudiosmweb** [comment]
@barrykooij go ahead <3

**Comment by claudiosmweb** [comment]
@barrykooij maybe can help you https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L536

**Comment by stayhero** [comment]
@barrykooij @claudiosmweb  Again, I would really vote against using the decimal precisions from the settings because for most/all european merchants this is a very sane default. 

And if it is required to change the default precision to five (to retrieve the higher precision net prices), I can already hear the phone calls of merchants who explicitly do not want their prices to be shown on the frontend with anything other then two decimals.  :crying_cat_face: Which is understandable of course. 

In my opinion there are these options:

a.)  If it would not break backwards compatiblity I would say, remove the wc_format_decimal wrapper from the API result method and leave the net prices untouched.

b.) Add another setting for internal decimal precision for the API (but this would probably affect other API methods as well).

or
c.) Return the gross item price in the API results.

**Comment by barrykooij** [comment]
I don't want to break backwards compatibility of the API and a and c will do this. I also don't like adding a new setting just for this.

I suggest a query arg that can be set in API calls to define decimal precision. This arg will default to 2 and thus be backward compatible.

Agree @claudiosmweb @mikejolley ?

**Comment by stayhero** [comment]
@barrykooij Although adding the gross item price as additional item (like total_gross or price_gross) would not break compatibility, I guess letting the API consumer decide about the decimal precision is probably the way to go. :+1:

**Comment by claudiosmweb** [comment]
I think we have create a filter for it, like:

```
filter[decimals]=2
```

And use `wc_get_price_decimals()` has fallback.

**Comment by barrykooij** [comment]
@claudiosmweb exactly what I meant with query arg :)

**Comment by barrykooij** [comment]
Fixed in master, this will be included in 2.4
