### ISSUE TITLE
Unit Tests: Convert Helper classes to Factory classes

### ISSUE THREAD

**Issue by barrykooij** [woothemes/woocommerce#7653]
https://github.com/woothemes/woocommerce/tree/master/tests/framework/helpers

![c233a5a7141682326420336898_700wa_0](https://cloud.githubusercontent.com/assets/2846594/6526719/4f5e87a6-c415-11e4-89be-e40c618b3bd9.gif)

**Comment by mikejolley** [comment]
Helpers are adequate for now. We need to focus on increased coverage and start making new tests part of our dev process, every time.
