### ISSUE TITLE
PUT Request Update Product Variant Fails

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#7659]
Hi,

I am trying to update the stock quantity of a product variant. ID 371 is the product variant ID. Please see attached. My update is failing. Is something wrong with my request?

![pv](https://cloud.githubusercontent.com/assets/1679993/6539694/eb4d8ab2-c448-11e4-8c94-48aefbeab010.jpg)

Request

PUT https://XX.azurewebsites.net/wc-api/v2/products/371?stock_quantity=4&consumer_key=XX&consumer_secret=XXHTTP/1.1
Authorization: Basic XX
Content-Type: application/x-www-form-urlencoded
Host: XX.azurewebsites.net
Content-Length: 34
Expect: 100-continue

{"product": {"stock_quantity":4} }

Response

{"product":{"title":"5063-511","id":371,"created_at":"2015-01-22T16:03:47Z","updated_at":"2015-03-07T02:26:24Z","type":"variation","status":"publish","downloadable":false,"virtual":false,"permalink":"\/wc-api\/v2\/products\/371?stock_quantity=4&consumer_key=XX&consumer_secret=XX&=https:\/\/XX.azurewebsites.net\/product\/5063-511\/","sku":"5063-122-11","price":"0.00","regular_price":"0.00","sale_price":null,"price_html":"","taxable":true,"tax_status":"taxable","tax_class":"","managing_stock":true,"stock_quantity":1,"in_stock":true,"backorders_allowed":false,"backordered":false,"sold_individually":true,"purchaseable":false,"featured":false,"visible":true,"catalog_visibility":"visible","on_sale":false,"weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":null,"description":"<p>test product<\/p>\n","short_description":"","reviews_allowed":true,"average_rating":"0.00","rating_count":0,"related_ids":[],"upsell_ids":[],"cross_sell_ids":[],"categories":[],"tags":[],"images":[{"id":0,"created_at":"2015-03-07T02:31:18Z","updated_at":"2015-03-07T02:31:18Z","src":"https:\/\/XX.azurewebsites.net\/wp-content\/plugins\/woocommerce-2.1.0-beta-3\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"featured_src":false,"attributes":[],"downloads":[],"download_limit":0,"download_expiry":0,"download_type":"","purchase_note":"","total_sales":1,"variations":[],"parent":{"title":"5063-511","id":341,"created_at":"2015-01-22T16:03:47Z","updated_at":"2015-03-07T02:26:24Z","type":"variable","status":"publish","downloadable":false,"virtual":false,"permalink":"https:\/\/XX.azurewebsites.net\/product\/5063-511\/","sku":"5063-5112","price":"100.00","regular_price":"0.00","sale_price":null,"price_html":"<del><span class=\"amount\">&#36;0.00<\/span><\/del> <ins><span class=\"amount\">&#36;100.00<\/span><\/ins>","taxable":true,"tax_status":"taxable","tax_class":"","managing_stock":true,"stock_quantity":0,"in_stock":true,"backorders_allowed":false,"backordered":false,"sold_individually":true,"purchaseable":true,"featured":false,"visible":true,"catalog_visibility":"visible","on_sale":true,"weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":null,"description":"<p>test product<\/p>\n","short_description":"","reviews_allowed":true,"average_rating":"0.00","rating_count":0,"related_ids":[],"upsell_ids":[],"cross_sell_ids":[],"categories":[],"tags":[],"images":[{"id":0,"created_at":"2015-03-07T02:31:18Z","updated_at":"2015-03-07T02:31:18Z","src":"https:\/\/XX.azurewebsites.net\/wp-content\/plugins\/woocommerce-2.1.0-beta-3\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"featured_src":false,"attributes":[{"name":"Size","position":"0","visible":false,"variation":false,"options":["Large"]}],"downloads":[],"download_limit":0,"download_expiry":0,"download_type":"","purchase_note":"","total_sales":1,"variations":[],"parent":[]}}}

**Comment by claudiosmweb** [comment]
Just tested and works great!

**Comment by jmawebtech** [comment]
Hi,

was this a coding issue that was just resolved?

**Comment by claudiosmweb** [comment]
Have no issue, it is working.
