### ISSUE TITLE
Product shortcodes do not render product page correctly

### ISSUE THREAD

**Issue by paulgambill** [woothemes/woocommerce#7661]
I've been using the Divi theme by Elegant Themes and had built a page so that I could use the url: thehappycrate.com/subscribe on my site. I don't like having to include the /product/ or /shop/ in the url. So on that page I had used the product shortcode [product_page id="number"].

The only real issue used to be that the tabs and a few small details didn't look great. But when I installed Product Reviews Pro extension, the Discussion tab became horribly misrendered. See screenshot.

I opened a support ticket (#265606), and we eventually determined that the cause of the issue was that I was using a shortcode instead of the actual product page.

I believe this is a bug in the way shortcodes are built. I found several other similar complaints on the community forums. As a user, my expectation was that a product shortcode would display the same way a product page does - otherwise why have shortcodes at all?
![custom page with shortcode](https://cloud.githubusercontent.com/assets/1007027/6539977/eb5a92a0-c43b-11e4-9a23-b031b685141a.png)
![product page](https://cloud.githubusercontent.com/assets/1007027/6539976/eb5959bc-c43b-11e4-8a32-f7d3f1ee6feb.png)

**Comment by mikejolley** [comment]
Product reviews pro needs to ensure its styles/scripts are loaded with that shortcode - the core page is styled fine when used via shortcode. Will add to the ticket on support and cc them in. Closing here as its not core.
