### ISSUE TITLE
umlauts in order item meta are still escaped in order-received and view-order

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7662]
This is a followup to #6550 

In cart and checkout it is correct:
![auswahl_025](https://cloud.githubusercontent.com/assets/3307404/6541243/4d7ec516-c4c6-11e4-8218-c6eb70d4c490.png)

However, in order-received and view-order it is still `Fuellmenge` instead of `Füllmenge` (following screenshot with storefront theme:

![auswahl_026](https://cloud.githubusercontent.com/assets/3307404/6541255/930371a4-c4c6-11e4-890d-9651d336b00c.png)

**Comment by mikejolley** [comment]
This only affects 'text' attributes.
