### ISSUE TITLE
POST /wc-api/v2/orders?  Customer Id is Invalid Error

### ISSUE THREAD

**Issue by maltacode** [woothemes/woocommerce#7666]
```
$data = '{
  "order": {
    "status": "processing",
    "currency": "",
    "billing_address": {
      "first_name": "",
      "last_name": "",
      "company": "",
      "address_1": "",
      "address_2": "",
      "city": "",
      "state": "",
      "postcode": "",
      "country": "",
      "email": "",
      "phone": ""
    },
    "shipping_address": {
      "first_name": "",
      "last_name": "",
      "company": "",
      "address_1": "",
      "address_2": "",
      "city": "",
      "state": "",
      "postcode": "",
      "country": ""
    },
    "line_items": [
      {
        "id": null,
        "quantity": 1,
        "product_id": 271,
      },
	  {
        "id": null,
        "quantity": 3,
        "product_id": 273,
      }
    ],
  }
}';
```

$data is sent via curl using a json_encode and is returning

'{"errors":[{"code":"woocommerce_api_invalid_customer_id","message":"Customer ID is invalid"}]}' 

What is the cause of this error please?

**Comment by maltacode** [comment]
Seems like the customer id was a required field. I added a customer in users and added to the json
string, 

"customer_id": 6,

Order was successfully added to woocommerce via api. Please close this ticket.

**Comment by maxrice** [comment]
Yep customer ID is required. For a guest purchase, simply use `0` as the customer ID :smile_cat:

**Comment by barrykooij** [comment]
@mikejolley @claudiosmweb is this documented?

**Comment by claudiosmweb** [comment]
@barrykooij I just fixed:

![screenshot from 2015-03-10 15 10 08](https://cloud.githubusercontent.com/assets/1264099/6581767/a7873b10-c737-11e4-887c-e415a2d3e000.png)
