### ISSUE TITLE
My account - edit account derication in Dutch Woocommerce version

### ISSUE THREAD

**Issue by dutchfte** [woothemes/woocommerce#7668]
Dear sir madam,

Please look first to the attached images, especially the url's.
![mijn account - edit account 1](https://cloud.githubusercontent.com/assets/11376333/6546125/17d6bb6c-c5a7-11e4-815b-f61c066bd9e5.png)
![mijn account - edit account 2](https://cloud.githubusercontent.com/assets/11376333/6546123/17d63926-c5a7-11e4-8f36-3d1da6049413.png)
![my account - edit account](https://cloud.githubusercontent.com/assets/11376333/6546124/17d6901a-c5a7-11e4-8afb-7361486a2f75.png)

If I want to edit account and I follow the step of image 'mijn account - edit account 1' I get directed to 'mijn account - edit account 2'. Which is perfect.

However if I would like to edit my account via the my account menu, see image 'my account - edit account', I receive an error. This is because the URL is not consistent. 'My-account' in the URL has to bij 'mijn-account'. 

How can I change this error? 

Kind regards,

Sander

**Comment by mikejolley** [comment]
The edit account link in the menu is one that you've added to your 'appearance menus' section. You should edit/remove that - wc doesn't add the link.
