### ISSUE TITLE
Usuability: "Please choose product options…" is too unspecific

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7670]
I think this is a minor usuability issue. I use the virtue theme but the issue's source is within WC. If I go to a variation product like http://themes.kadencethemes.com/virtue-premium/product/lighthouse-clothing-t-shirt/ and click on add to cart *without* previously selecting a size than it as “Please choose product options…”:

http://storage2.static.itmages.com/i/15/0307/h_1425721750_5828904_ade6b7b317.png

This is confusing and could be more specific. A customer does not know what a “product option” is (translated to german it sounds even more strange). In real human (not machine) language one would not speak of the "product option" that has been forgotten but of name the thing, in this case the "size".

The message comes from https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-form-handler.php#L601

Can this be changed to something specific like:
`Please choose a product option for <name_of_option>.`
e.g.
`Please choose a product option for sizes.`

If there a are multiple options then:
`Please choose product options for optionA, optionB and optionC.`
e.g.
`Please choose product options for sizes and colors`

PS
Ideally it would be simple "Please choose a <option-name>" but this is impossible to translate because in languages like French or German, the "a" could be ein/eine or un/une depending on the option's grammatical gender.

**Comment by mikejolley** [comment]
Why do you have an add to cart button without chosen options? Seems like an err in your theme.

**Comment by jnachtigall** [comment]
> Why do you have an add to cart button without chosen options? Seems like an err in your theme.

This is done on purpose. The virtue theme author told me: 
> I have changed woocommerce’s default to hide the add to cart. I think it’s more confusing than anything to arrive at a product page and not see a clear ending add to cart button. To me it makes it look like the product is unavailable.

...and I totally agree with that ;-)
