### ISSUE TITLE
Variation dissapeared after langauage change

### ISSUE THREAD

**Issue by ivominchev** [woothemes/woocommerce#7671]
Hi, 
I made a German online shop with WooCommerce. I did not know German. That's why I created all products in English (I switched it from Settings - Site Language). The shop sells mattresses. Every mattress has lot of variations - sizes.When I was ready with all the products and variations I switch the language to German again. After that I saw that all my variations are gone. I have to recreate them again. 
When I switch the language back to English everithing is OK, but the problem is that the frontend is not localised in German in this way.
The problem is with the name of the variation attribute in my case is the word "Größe", which contains special characters.
![untitled1](https://cloud.githubusercontent.com/assets/9106199/6548280/f3af11e4-c5fb-11e4-8c7f-fd376f2dc79a.png)
![untitled3](https://cloud.githubusercontent.com/assets/9106199/6548281/f3afbf04-c5fb-11e4-8abc-1eb4f61b2888.png)

**Comment by mikejolley** [comment]
I have found the reason for this. I will document it here for future reference.

Attribute names in WooCommerce are sanitised using the sanitize_title() function. Lets take an example attribute named: Test Germän

In english, the santiized form of this would be 'test-german'. However, WordPress seems to have some funky handling for german language only:

https://dl.dropboxusercontent.com/s/l317tchuk30iy7w/2015-03-09%20at%2016.22%202x.png?dl=0

This makes it 'test-germaen', thus making the data mismatch with what is saved. Saving the product resolves this, but going back to english will cause the same glitch.

For the moment this has to be a wontfix item - adjusting the santiization used would be destructive to stores, and switching between eng and de should be an edge case.

cc @barrykooij @claudiosmweb
