### ISSUE TITLE
[API] Product StockQuantity (Inventory Level) Updates via the REST API

### ISSUE THREAD

**Issue by euan-am** [woothemes/woocommerce#7673]
Currently it seems that in order to update the stock quantity (inventory level) for a product through the REST API, the product needs to be updated using a PUT to /wc-api/v2/products/<id> with the "product.stockQuantity" set to the new value.

This mechanism of updating stock quantity can lead to a problem if the product stock quantity is updated while orders are being processed by Woocommerce simultaneously. This may lead to the incorrect stock quantity being set which may lead to orders being processed for stock that is not available.

I would like to propose an alternative mechanism to updating stock quantity to try an work around this problem. 

It may be beneficial to add functionality to the Woocommerce REST API to allow a stock quantity update to be done using a stock quantity delta value instead of just purely setting the stock quantity. The delta could represent the quantity to increase or decrease the stock quantity in Woocommerce. Woocommerce can then safely apply the delta to the current stock quantity value.

I have recently spoken to @mattyza about this proposal. I believe this type of functionality will greatly benefit 3rd party fulfilment providers who are responsible for Inventory Management.

**Comment by mattyza** [comment]
@maxrice @claudiosmweb @mikejolley Perhaps an `inventory_delta` key on this API endpoint would be sufficient? Should we explore dedicated inventory endpoints?

**Comment by maxrice** [comment]
Adding `inventory_delta` makes sense to me :smile: Just need to make sure the 2 ways to set stock quantities are documented and explained.

**Comment by theinventor** [comment]
Please excuse my ignorance on the subject, how come the create action can't do the StockQuantity?

**Comment by maxrice** [comment]
@theinventor you should be able to set the stock when creating a product, try using `stock_quantity`

**Comment by mikejolley** [comment]
@claudiosmweb I assume this is the do things such as 'increase stock by 10'?
