### ISSUE TITLE
Custom Fields For Variation Data , not displayed on back-end

### ISSUE THREAD

**Issue by barakd** [woothemes/woocommerce#7675]
Hey, after the update, custom fields i used to save on my product variations, are not being retrived on the admin panel.
They do get saved , as I checked they are saved to the db.
But they won't apper in the $variation_data array, when I hook on the action:
woocommerce_product_after_variable_attributes
The reason for that is, the if condition at the file 
woocommerce\includes\admin\meta-boxes\class-wc-meta-box-product-data.php
on line 784:
foreach ( $variation_meta as $key => $value ) {
								if ( false !== strpos( $key, 'attribute_' ) ) {
									$variation_data[ $key ] = $value;
								}
The reason is that my meta data wasn't saved with the attribute prefix,
This is my suggested fix:
	foreach ( $variation_meta as $key => $value ) {
								if ( !array_key_exists($key,$variation_fields) ) {
									$variation_data[ $key ] = $value;
								}
Thanks.

**Comment by mikejolley** [comment]
Rather than rely on $variation_data (which contains core data only at present) why not use get_post_meta? Then you're guaranteed to be able to retrieve your data and also format it however you need.

**Comment by barakd** [comment]
Thats not true, because when i am inside the action hook of woocommerce_product_after_variable_attributes and woocommerce_product_after_variable_attributes_js
I only have access to $loop id and $variation_data.
I don't know the id of the current variation and therefore can't use get_post_meta.

**Comment by mikejolley** [comment]
You have access to `$variation_id`

**Comment by cannect** [comment]
@mikejolley 

I see in `wp-content\plugins\woocommerce\includes\admin\meta-boxes\views\html-variation-admin.php` this action firing: `do_action( 'woocommerce_product_after_variable_attributes', $loop, $variation_data, $variation );`

I think  you mean that last variable `$variation`.  
However when I use `$variation` I get an error: `Warning: Missing argument 3 for my_function()` And my function has three arguments.

So I think something is really broken here.
