### ISSUE TITLE
Reports: missing export buttons on some browsers

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#7676]
Dependong on the browser used the export button doesn't show in the reports section. Here is an example with Google Chrome and Safari. The export link is displayed not Chrome, not in Safari:

![](http://cld.wthms.co/5g3e+)

**Comment by mikejolley** [comment]
Hidden for browsers without support for the 'download' property https://github.com/woothemes/woocommerce/blob/89704ef36ab064cceaecb5ff5b2b76b3ff8de859/assets/js/admin/reports.js#L122
