### ISSUE TITLE
Filters needed for tax options

### ISSUE THREAD

**Issue by dbarproductions** [woothemes/woocommerce#7681]
With all the new tax laws, especially in European countries, it would be VERY helpful if there were filters that were applied to the various tax settings, specifically for the options:

woocommerce_prices_include_tax
woocommerce_tax_display_shop
woocommerce_tax_display_cart

An easier way to filter/change tax class per user or role would be nice also, but that is relatively easy to do compared to the problems the above options cause.

Explanation:
For plugins, like mine, where different types of users get different pricing, the tax options may need to be set differently. For example, I had to implement those 3 options separately in my wholesale ordering extension to make it work with clients in Germany that needed to enter and display prices/taxes differently for retail (B2C) and wholesale (B2B) customers, and this became a big nightmare to get working as there were no easy hooks to override these settings since they are usually pulled right from the options. I had to directly modify the cart object, and then force some recalculations in cart/checkout for certain combinations of tax settings, by basically duplicating existing functions from Woocommerce, but with the correct settings for wholesale customers.

I think this is going to be an issue that crops up more often now with the newer tax and internet business compliance laws in some countries.  Would be a whole lot easier, and less likely to break things, if other plugins were allowed to modify those settings!

It would also be a very easy fix/update to simply add some apply_filter hooks around areas where those values are retrieved.  At least the first one is done in the wc_conditional_functions.php file (line 341), so very easy to add an apply filters around that.  Perhaps the other 2 where they are grabbed from the options table as needed could also be set to go through a conditional function with apply_filters around the return value?

Thanks for considering!!

**Comment by mikejolley** [comment]
2 points around this;

1. filtering woocommerce_prices_include_tax is a bad idea. This is how **prices are input** so if you're changing that on the fly, your pricing is going to be wrong.
2. Filtering the second too (ignoring the setting) could potentially be confusing if settings are not respective.

That said, you can 'filter' these without a dedicated filter - pre_option http://codex.wordpress.org/Plugin_API/Filter_Reference/pre_option_%28option_name%29

**Comment by dbarproductions** [comment]
Thanks for the fast response Mike!

I understand, and will look into doing it with the pre_option.

Although I would agree that filtering woocommerce_prices_include_tax is a bad idea when you have only one type of customer and are getting the price from just the normal postmeta fields, in the case of wholesale customers in my plugin, there is a separate _wholesale_price postmeta value for each product that is shown only to wholesale customers (replaces regular prices via the get_price filters when the user is a wholesale customer). In those situations, particularly for my clients in Germany, they wanted to enter retail prices excluding taxes, but wholesale prices including tax (or perhaps the other way around)... so, it wasn't the same for the 2 sets of prices, which then throws off tax calculations on the wholesale prices, and required a lot of work around. 

I had not tried the pre_option hook, so that may be a good method to explore for the next update of my plugin, so thanks for pointing me in that direction!  Spent too much time combing through Woocommerce code instead of core code.
