### ISSUE TITLE
WooCommerce prettyPhoto conflict on RTL sites

### ISSUE THREAD

**Issue by ABDpromotions** [woothemes/woocommerce#7686]
When operating a site in Right to Left mode, the WooCommerce prettyPhoto popup contains CSS error that does not allow hover buttons to display properly:
[Screencap Here](http://content.screencast.com/users/SteveTested/folders/Jing/media/aa048f4a-57c4-423d-bcff-30a2cb302979/2015-03-10_1236.png)

Current CSS:

```
.pp_content_container {
    position: relative;
    text-align: left;
    width: 100%;}
```

Proposed fix:

```
.pp_content_container {
    position: relative;
    text-align: right;
    width: 100%;}
```

**Comment by jameskoster** [comment]
That isn't a fix, that will just cause the same thing to happen on ltr web sites :p 

We'll just need to use the `rtl` class wp adds and add some more specific selectors.
