### ISSUE TITLE
add_to_cart giving me fatal error

### ISSUE THREAD

**Issue by twixchopra** [woothemes/woocommerce#7688]
I want to add product to the cart with quantity as well. 
Eg. `www.mysite.com/?product=white-t-shirt&add-to-cart=8&set-cart-qty_8=5`

So for that I have added below code to my `functions.php` :

		function woocommerce_set_cart_qty_action() { 
		  global $woocommerce;
		  foreach ($_REQUEST as $key => $quantity) {
			// only allow integer quantities
			if (! is_numeric($quantity)) continue;

			// attempt to extract product ID from query string key
			$update_directive_bits = preg_split('/^set-cart-qty_/', $key);
			if (count($update_directive_bits) >= 2 and is_numeric($update_directive_bits[1])) {
			  $product_id = (int) $update_directive_bits[1]; 
			  $cart_id = $woocommerce->cart->generate_cart_id($product_id);
			  // See if this product and its options is already in the cart
			  $cart_item_key = $woocommerce->cart->find_product_in_cart( $cart_id ); 
			  // If cart_item_key is set, the item is already in the cart
			  if ( $cart_item_key ) {
				$woocommerce->cart->set_quantity($cart_item_key, $quantity);
			  } else {
				// Add the product to the cart 
				$woocommerce->cart->add_to_cart($product_id, $quantity);
			  }
			}
		  }
		}

		add_action( 'init', 'woocommerce_set_cart_qty_action' );

It is working as expected when Cart is not empty but when cart is empty it is giving me an error :

**Fatal error: Maximum function nesting level of '100' reached, aborting! in** and the line number it is pointing is `$woocommerce->cart->add_to_cart($product_id, $quantity);`

What might be the issue here ?

Theme : Twenty Twelve
woocommerce : 2.3.5

**Comment by mikejolley** [comment]
You do realise the add to cart handler supports a 'quantity' query string arg :)

**Comment by twixchopra** [comment]
Thanks for your quick reply. 

Last question .. I am running web store using woocommerce and I have enabled Review on product.

What I want is to have different color to define ratings. Say for eg. If someone gives only 1 star to product, then star should be filled with RED color(To indicate poor quality) and for 2 and 3 star default woocommerce color and for 4-5 star GREEN color.

What hook should I use to achieve this ?
