### ISSUE TITLE
#screen-options-wrap it's not working editing a single product 

### ISSUE THREAD

**Issue by soulpawa** [woothemes/woocommerce#7692]
I have a problem when I want to edit a single product, but I can't, seems like javascript on my single product it's not working, It doesn't wok the screen options, or the help, if I want to add a short product comment I can't, nothing happend when I press the arrow, just when I want to edit a single product, the console shows this error:

 Failed to load resource: the server responded with a status of 404 (Not Found)
4load-scripts.php:267 Uncaught TypeError: Cannot read property 'hasClass' of undefined
post.php?post=205&action=edit&lang=en:1 Denying load of chrome-extension://gkojfkhlekighikafcpjkiklfbnlmeio/js/jquery.min.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
13load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,wp-ajax-response,jquery-color,wp-lists,jqu…:267 Uncaught TypeError: Cannot read property 'hasClass' of undefinedload-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,wp-ajax-response,jquery-color,wp-lists,jqu…:267 (anonymous function)load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:3 m.event.dispatchload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:3 r.handleload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:3 m.event.triggerload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:8 e.event.triggerload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:3 (anonymous function)load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:2 m.extend.eachload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:2 m.fn.m.eachload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:3 m.fn.extend.triggerload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:603 (anonymous function)load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:2 jload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:2 k.fireWithload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:4 xload-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,farbtastic,thickbox,util…:4 b

any idea why I can't edit or open the java in this page?

thanks in advanced

**Comment by slash1andy** [comment]
That sounds like an issue with an extension you have in Chrome, or on your server. 

First thing I would do is switch browsers to one that doesn't have extensions.
Then contact your host.
If that doesn't work, check for theme/plugin conflicts

**Comment by soulpawa** [comment]
I checked with different computers + different browsers, always the same problem, it happens since I migrate from a shared hosting to a VPS, and I don't really don't know why it's just in one page, on single products... I changed theme, still same problem, and plugins didn't add any new plugin, so seems like a server problem. Thanks for your answer.

**Comment by soulpawa** [comment]
I fixed, removing all woocommerce plugin and installed again, working like a charm, thanks
