### ISSUE TITLE
Variable Products shipping info not showing

### ISSUE THREAD

**Issue by panploenes** [woothemes/woocommerce#7693]
Hey

When creating a product with variations, the shipping info values, set for each variation, are only displaying in the front office tab if the values for the parent product are not empty or zero.

They really should be displayed whenever a value is set for weight or dimensions.

EDIT:
I guess the "has_weight" and "has_dimensions" functions dont return true if only the variation of a product has values set.
https://github.com/woothemes/woocommerce/blob/master/templates/single-product/product-attributes.php#L23-L39

**Comment by mikejolley** [comment]
I think this is correct. If only 1 variation for example of many inside the product has a weight, it wouldn't make sense to show the weight data at product level?

**Comment by panploenes** [comment]
It should display the weight and dimension data for the selected variation if there is any.
At the moment it only will do so, if there is also weight data set for the parent product.

Lets say I have a variable product "brick". With variations of size and weight. I would not enter any weight data for the parent product since the parent product is only some kind of a container for the variations. The parent it self is not a product you can buy therefore no weight no dimension. But atm its required to set some value...

**Comment by mikejolley** [comment]
K, this will need looking at and will require some template changes. Moving to 2.4

**Comment by mikejolley** [comment]
Since this was reported we have added a 'variation description' field which can be used for variation level data display needs. 

![2015-10-01 at 14 55](https://cloud.githubusercontent.com/assets/90977/10221115/935bc3fc-684c-11e5-92e5-18fac1620cc3.png)
