### ISSUE TITLE
PayPal Standard can't write to error log in /wp-content/uploads/

### ISSUE THREAD

**Issue by a3rev** [woothemes/woocommerce#7696]
Hi Guys

Just letting you know that since the PayPal standard Error logs folder was moved from root folder /public_html/ to /public_html/wp-content/uploads/ the logs are no longer being written to.

Works fine with PayPal express extension - but not the wc core PayPal standard.

Have not dug into the code to see why that is - just reporting the issue, I'm pretty sure its a simple Tweak to fix it.

Steve

**Comment by roykho** [comment]
I am not seeing this issue, works for me.

**Comment by a3rev** [comment]
Hi Roy

We have checked it on 3 different live sites on 3 different servers (all LAMP stacks) - all of those sites use PayPal standard and none of them are having the Error Logs written too.

I am not sure in which version  the logs folder position changed ? But it is the only thing we can see that when the folder position changed the logs are not being written too. - One of those sites has PayPal Express extension - When it is activated the logs are written too - when it is deactivated and standard PayPal is used - no logs? 

So I am not sure why it is working for you and not is our sites - all running WP 4.1.1 and WC 2.3.5

**Comment by roykho** [comment]
@a3rev within your path, are you seeing the wc-logs folder? So are you seeing wp-content/uploads/wc-logs/ or does this not exist?

**Comment by a3rev** [comment]
@roykho 

yes - see the file and it exists. Where are you seeing the PayPal logs on the install you checked. We have Debug Log [ ] Enable logging turned enabled in the Checkout > PayPal settings and the help text under it says

Log PayPal events, such as IPN requests, inside /home/a3rev/public_html/wp-content/uploads/wc-logs/paypal-xxxxxxxxxxxxxxxxxxxxxxxxxx.log

The file is there - just not logs are written to it > (Logs are generated each time there is a sale via the PayPal gateway. All 3 sites are using PayPal IPN.

Logs used to be written - now they are not - As I said works fine with the PayPal Express Extension.

**Comment by DorianListens** [comment]
This same behaviour occurs for me. My woocommerce system status page says that the log directory is writeable, and there is an empty test log file, but no actual logs are written.

**Comment by a3rev** [comment]
@mikejolley - 
V 2.3.6
* Fix - Paypal debug option.

Thank you.
