### ISSUE TITLE
Using custom attributes in menus not working

### ISSUE THREAD

**Issue by davidandrew** [woothemes/woocommerce#7701]
Hi people

For love nor money can I get this working. Has any one got this working with the current version of WC?

http://docs.woothemes.com/document/using-custom-attributes-in-menus/

Looks like I am not the only one:

http://stackoverflow.com/questions/28833380/cannot-get-custom-attribute-to-work-in-menu

Is this feature in this version of WC borked?

Regards

Dave

**Comment by mikejolley** [comment]
I have submitted a doc report. This needs to mention that attributes also need enabling for the filter to work (https://dl.dropboxusercontent.com/s/p0g4hve0uwufhsk/2015-03-12%20at%2019.04.png?dl=0).

**Comment by davidandrew** [comment]
Thanks :)

I have just given a write up to someone who was having a problem with attributes as menu items

http://stackoverflow.com/questions/28833380/cannot-get-custom-attribute-to-work-in-menu/29022089#29022089
