### ISSUE TITLE
Cancelled subscriptions breaks download links of other products

### ISSUE THREAD

**Issue by andrewfitz** [woothemes/woocommerce#7706]
I sell a virtual downloadable product and a virtual subscription product together in one order. When I cancel the subscription product, all links to download the files (for the other digital product purchased along side of it) fail with the error "Invalid order".

Perhaps because the referenced order of the download links is based on the subscription product? Doesn't make sense though.

Using the latest subscription and woocom plugins.

**Comment by andrewfitz** [comment]
If I delete the canceled subscription from the customer's order itself, the error goes away.

**Comment by mikejolley** [comment]
Would you mind posting this on support.woothemes.com please - if its a subscriptions related issue we'll most likely want access and will need to CC in the developers.

Thanks
