### ISSUE TITLE
Variation Product Stock

### ISSUE THREAD

**Issue by jawad-ahmed** [woothemes/woocommerce#7710]
Hi,

Despite having 0 products using variation product stock management, it shows 'in stock'? Bug or not?

![screen_shot_2015-03-12_at_21_27_27](https://cloud.githubusercontent.com/assets/8149510/6628987/519352a8-c902-11e4-8722-deda855a5344.png)

**Comment by mikejolley** [comment]
Really it depends on the product setup. e.g. if backorders are enabled, the products are still classes as in stock. Same if the 'out of stock level' is < 0. Check the products.
