### ISSUE TITLE
Tax added from order->add_tax() amount deleted upon updating order from admin

### ISSUE THREAD

**Issue by ikariiwarrior** [woothemes/woocommerce#7712]
Using the function add_tax() on the order object does not persist the tax in a way that it survives updates in the order detail view of wp-admin.

Server-based changes (such as status changes from the order list page) do not have any impact. However any change made in the detail screen (calculate totals, save order, update status, perform action) will subsequently delete the value in the meta_value field from the wp_woocommerce_order_itemmeta table.

This does not appear to impact the default configuration for WooCommerce where it is using built-in tax features. However any plug-in that does not leverage built-in mechanisms (eg;  TaxJar) will result in aforementioned behavior. 

I have reproduced this behavior by simply adding the following line to the default thankyou.php template: <?php $order->add_tax( 1, 5.55 ); ?>

When reviewing the order in wp-admin, the $5.55 tax information is displayed - upon simply saving the order that information is zeroed out.

So far, it looks like this is due to the way jQuery is calculating order totals before submitting ajax to the server. Order-level tax is NOT getting calculated, but item-level tax is.

This is reproducible on the latest version of WordPress and WooCommerce in a brand new Ubuntu VPS spun on Digital Ocean.

**Comment by mikejolley** [comment]
Taxes need to be assigned to line items also - I believe it sums these to form a total on save. @barrykooij you made taxamo, any advice?

**Comment by ikariiwarrior** [comment]
Hi @mikejolley - Thanks for following up on this, but I'm not sure I understand how this is supposed to work if WooCommerce only supports tax at the line item level. If I want to add a dollar amount to an order as tax (based on the order subtotal) how would I distribute that amount across all the items in the order? And if that's the case, why does order->add_tax() exist if not to add tax to the order as opposed to line items? Can you describe how this would be done correctly if add_tax() is not appropriate? The documentation is vague in this dept. 

Thank you!

**Comment by ikariiwarrior** [comment]
Also, I should reiterate to be clear, the tax disappears ONLY if the order is updated from the detail screen. All other updates to the order work just fine - such as the bulk updates on the order list page. It appears that the javascript functions that calculate the subtotals, tax, fees, shipping fail to grab order-level tax and include it in its calculations. Server-side updates (which occur elsewhere) seem to find and include this tax value just fine.

**Comment by mikejolley** [comment]
Tax cannot just magically be charged - it's always based on *something*. That is, its applied to items. So why does it have to be at subtotal level?

**Comment by ikariiwarrior** [comment]
@mikejolley Thanks for your feedback, but I have concerns based on your response.

1) WC_Abstract_Order->add_tax( $tax_rate_id, $tax_amount, $shipping_tax_amount ) should be deprecated or the documentation should be amended, because it is currently misleading. What you are saying is that tax can not be applied to an order holistically, which is exactly what this function does (and claims to do). Source: http://docs.woothemes.com/wc-apidocs/source-class-WC_Abstract_Order.html#300-333

2) I think you are confusing my test to verify behavior with real world implementation. My submission was meant to illustrate how to reproduce the issue in a vanilla fresh install with minimal code manipulation. There is no "magic" in my real world implementation - tax *is* based on *something*. That something is the aggregate value of taxable items in the order (in this case, the subtotal). 

Regardless, WooCommerce working correctly (by not deleting tax amounts) when tax is applied to each item individually is irrelevant. It should also work correctly when there is order-level tax on the order, *especially* since the built-in API provides the facilities to add independent tax line items. Again, if add_tax() is temporal it should be either deprecated or amended with appropriate documentation.

3) Re-iterating what I've already explained - The *only* place that WooCommerce deletes order-level tax is on the order detail page when it performs any re-calculations in javascript and then sends the results via ajax to the server. In every other case, where the order is updated/modified or otherwise manipulated and saved, the tax information remains in tact because server-side calculations include order-level tax line items (which add_tax() creates). The behavior of tax amount being zeroed out on the detail screen is in the minority and therefore leads me to believe this is a bug.

**Comment by mikejolley** [comment]
If you click 'add tax' when editing an order maybe that will give you a better idea on what this method is for.

You'll see a new column is added for each line item, and a new total row. The values you can pass in optional are totals:

`add_tax( $tax_rate_id, $tax_amount = 0, $shipping_tax_amount = 0 )`

When the order is saved, the line item taxes are totalled up and store in this tax line item. If the line items have no taxes, the totals are zero'd.

**Comment by AGDesignStudio** [comment]
Having issues with add_tax() when creating an order using wc_create_order()

@mikejolley any ideas where I have gone wrong?
