### ISSUE TITLE
product meta total sales is duplicated when duplicating products

### ISSUE THREAD

**Issue by aj-adl** [woothemes/woocommerce#7713]
The duplicate product function is really useful however I've noticed it also copies over total_sales from the original product - thinking about it there may be a few select use cases where this is useful (duplicate product ends up superceding original product after revisions etc) but I think that would account for 5-10% of use cases, for the other 90% it likely just throws off reporting 

Happy to do a pull request to fix the issue, just wanted to make sure it should be fixed first.

**Comment by mikejolley** [comment]
This is patched in master.
