### ISSUE TITLE
Conflict with the essential grid plugin

### ISSUE THREAD

**Issue by nicolas92** [woothemes/woocommerce#7716]
Hello, there is a small problem with the essential grid plugin, I created a client grid, it's a logo over a picture as you can see via the following URL: http://essential.themepunch.com/clients-grid-lyndon/, but when WooCommerce is enabled, the logos do not appear, however, before everything worked, of course, I contacted the plugin support who will talk with the developers, and they have said to contact you, you have an idea of what could cause this error?
Thank you very much.

**Comment by shivapoudel** [comment]
@nicolas92 I have surf your website and found that logo within the Clients Grid Lyndon are loaded. You also have activated the WooCommerce plugin too ;)

**Comment by nicolas92** [comment]
No, this is not my website, the plugin demo site, do you have an email so I can send you the URL of my site in private?
Thank you.

**Comment by shivapoudel** [comment]
See my profile you can get the email xD

**Comment by nicolas92** [comment]
Thanks, I send email you.

**Comment by shivapoudel** [comment]
xD

**Comment by mikejolley** [comment]
I'd guess its just a CSS conflict, in which case extra CSS would need adding to rectify. Without a public link it cannot be checked though. @shivapoudel let us know if its really a 'bug'.

**Comment by shivapoudel** [comment]
@mikejolly I am looking on this bug in his private link site. Sure I will let the team know if it's really a 'bug' xD

**Comment by shivapoudel** [comment]
@mikejolley It was the bug within the Essential Grid not on WooCommerce xD
