### ISSUE TITLE
Defaulting to local pickup under all circumstances

### ISSUE THREAD

**Issue by byronyasgur** [woothemes/woocommerce#7721]
If local pickup and free shipping are both enabled then local pickup becomes the default regardless of which method is selected for default in 

**Woocommerce>>Settings>>Shipping>>Shipping Options>>Shipping Methods**

Tested using a clean WP 4.1.1  and Woo 2.3.6  install on AMPPS local server and methods **local pickup**, **free shipping** and **flat rate**

**Comment by mikejolley** [comment]
I tested this without issue. It set the default to my setting (I had flat, free, local) for a new session. Important to note; once you've calculated shipping, or chosen a method, or gone to cart/checkout, the selected method will stick and override your default.

**Comment by byronyasgur** [comment]
Thanks I was definitely having problems and need to get to the bottom of this. For my testing can you tell me is there a simple way to guarantee the selected method in that case has been reset from the user input. I was trying various combinations of hard refresh/incognito mode/ re opening the browser/clearing cookies/transients etc but I can't be sure of a simple reliable way to reset it so I can test properly.

**Comment by byronyasgur** [comment]
I'm still getting this problem, and I've tested it extensively  ... it defaults to local pickup ( which in my case ... and I imagine others too ... it's dangerous as the customer may not read, and think they're getting shipping but in actual fact not ... they're opting for local pickup) . _To my mind it should never default to local pickup ... it's the most unlikely method in many cases, and most customers will not expect it to default to that._

__I started from scratch with a new WordPress install, no other plugins except woocommerce, default WordPress settings, and default woocommerce settings except for the shipping setup. __

As you can see from the __video__ it works fine until I enable local pickup, then it defaults to that no matter what is chosen in the default radio

_I found two cases that do not exhibit this ... one is where the free shipping value does actually qualify the shopper for free shipping ... and the other is if flat rate is chosen as the default ( this is of no use to me as my client requires that free shipping is automatically chosen if the visitor qualifies ) _

https://www.youtube.com/watch?v=S2sLiMC9suc
