### ISSUE TITLE
Add Slider Type in WooCommerce Settings

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce#7722]
It would be great to have a slider setting available on the settings pages. That way some of our admin interfaces could be a bit prettier:

![](https://cloud.githubusercontent.com/assets/1065372/6238963/65c78f44-b6bc-11e4-8032-ba7571111475.png)

**Comment by mikejolley** [comment]
I personally hate sliders, and core doesn't need one :p Whats wrong with number input for the above?

@jameskoster

**Comment by claudiosmweb** [comment]
You can solve this with HTML5:

```php
'range' => array(
	'title'    => __( 'Range', 'textdomain' ),
	'type'     => 'range',
	'custom_attributes' => array(
		'min'  => '0',
		'max'  => '1',
		'step' => '0.1',
	)
),
```

**Comment by BFTrick** [comment]
For things on a continuum I think it makes the most sense to show a continuum and you can pick where you want to be on that line. 

The number input in the original screenshot works but isn't terribly easy to use. What if you want to set the opacity to .85? 

No use for this in core yet but for the sake of consistency would be great to put it in core so a couple of extensions can try out the slider type and see how people like it.

**Comment by jameskoster** [comment]
In this case, if you want to set a specific value nothing is going to work better than a regular ol' text input.

I think a slider input is a fairly niche requirement and the `range` input type should be adequate for those cases. I don't think we should add any extra script to core to handle something like this.

**Comment by BFTrick** [comment]
I'd be fine with the range input type. Doesn't need to be fancier than that. As long as you can set the step as part of the setting.

Should we put the range type in core or just make extensions make a custom setting?
