### ISSUE TITLE
Unable to update Products

### ISSUE THREAD

**Issue by marco-hoyer** [woothemes/woocommerce#7724]
I'm trying to issue an update on a product. A POST request looks the same and works perfect but doing the following always responds an error. I might do something wrong but this looks equal to the example in the documentation. Any idea so far?

## Request:
```
PUT /wc-api/v2/products/610?oauth_signature=u%2F2uRVVH6T2y4DNBM4mAUE3usQk%3D&oauth_consumer_key=ck_4fdadb2805cb23adb390f9971808670e&oauth_signature_method=HMAC-SHA1&oauth_nonce=NFY5QkpKWU1GUllPRzVRMDIxSjQwMUhLMEJEUVo0VUo&oauth_timestamp=1426289027 HTTP/1.1
Host: test.shop.de
Content-Length: 37
User-Agent: python-requests/2.5.3 CPython/2.7.9 Darwin/14.3.0
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate

{"product": {"regular_price": 12.22}}
```

## Response: 
```
{"errors":[{"code":"woocommerce_api_missing_callback_param","message":"Fehlender Parameter data"}]}
```

**Comment by maxrice** [comment]
Either your hosting provider is blocking PUT requests, or you have a plugin conflict. Try deactivating all plugins except WC and see if you can make the request then :)

**Comment by marco-hoyer** [comment]
I deactivated all plugins but woocommerce and double checked if there is anything getting blocked but the system persists. Is there anything I can do to debug this issue? Maybe activate debug logging for woocommerce or so? I also don't think that there is anything blocking PUT request, since the response contains a woocommerce error message.

I'm running the Server on Debian Linux 7.8 with Apache/2.2.22.

What does it mean that the data parameter is missing? Do I need to add anything in the header or as request param?

**Comment by marco-hoyer** [comment]
From my very little understanding of php, it seems as if the error occurs in sort_callback_params() from includes/api/class-wc-api-server.php. If I add some debug statements, I can see, that the $required contains id and data. Sounds logical for an update_product function. In $provided I can see an empty data field.

```
Array\n(\n    
[0] => /customers/3\n   
[id] => 3\n   
[1] => 3\n    
[oauth_signature] => my_signature=\n    
[oauth_consumer_key] => my_key\n    
[oauth_signature_method] => HMAC-SHA1\n    
[oauth_nonce] => Skk0Rk9CWkhVNlRZR1M1TlhZMTlGUEs5N0dYTFBNWDQ\n    
[oauth_timestamp] => 1426508942\n    
[data] => \n    
[_method] => 4\n    
[_route] => /customers/(?P<id>\\d+)\n    
[_path] => /customers/3\n    
[_headers] => ...
```

May it be that I have to add data as request parameter?

**Comment by marco-hoyer** [comment]
This problem occurs with oauth and basic auth.

**Comment by maxrice** [comment]
Yep, you're correct in that the error message is due to the `data` parameter being empty. There are only 2 causes for this:

1) your server is blocking or filtering PUT requests. You can test this by creating a file in your root directory like:

```php
<?php
print_r( file_get_contents( 'php://input' ) );
```

and PUT'ing your request to that file instead. If the response is the PUT data like you expect, then the issue is:

2) a plugin or your theme is reading the PUT data and not setting the super global. I've seen this in a handful of plugins.

hope this helps :)

**Comment by marco-hoyer** [comment]
Thanks for your help. Number one works like a charm. I get back all the data I submitted. I already tried to disable all plugins but woocommerce. Do you have any Idea how to find the plugin causing this problem?

**Comment by maxrice** [comment]
Make sure you switch to the default theme as well, it's absolutely your theme or a plugin causing this issue then.

**Comment by marco-hoyer** [comment]
Hmm, damn. Even if I disable all plugins and change the theme to default, it doesn't work. I also tried to issue a GET request with parameter "_method=PUT" but the problem still exists. From my point of view this can't be a problem of something blocking data on PUT, since I used a GET request and see the same error.

**Comment by maxrice** [comment]
Not sure what else to try here, other than a different server and deleting/re-installing WC :/

**Comment by marco-hoyer** [comment]
Thanks for your time. I found out that my problem is getting caused by the InfiniteWP Client Plugin. I reported this to the developers.

**Comment by amityweb** [comment]
Hi Marco, I know this is old, sorry, but having same issue. As you said you disabled all plugins, was InfiniteWP blocking the PUT even though its disabled? We use IWP and other plugins like ithemes which is known to block PUT, but when I disable them all it's still blocked. As you said you disabled them all and still failed, but it was IWP, I am wondering if IWP is blocking it even when disabled? 
Thanks

**Comment by claudiosanches** [comment]
@amityweb generally when something like this is "blocked" is always by `.htaccess` or nginx config, so disabling the plugin will change the `.htaccess`? Have you checked the `.htaccess`?

**Comment by amityweb** [comment]
Good point, we use Boilerplate .htaccess https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess?ts=2, using default Wordpress is not suitable or recommended to leave as is. I will revert to the default to see if anything in boilerplate is blocking it.

**Comment by claudiosanches** [comment]
@amityweb that boilerplate does not block anything like it, but if a plugin introduced any line of code on the file, for sure will remain there after deactivated.
