### ISSUE TITLE
Uncaught ReferenceError: wc_select_params is not defined

### ISSUE THREAD

**Issue by alemarengo** [woothemes/woocommerce#7726]
After upgrading to woo 2.3.6, I cannot set Screen Options anymore since there's the error as in the subject. :(

**Comment by SiR-DanieL** [comment]
Same issue here

**Comment by mikejolley** [comment]
Can you flush all cache - wc_select_params was replaced.

https://github.com/woothemes/woocommerce/search?q=wc_select_params&type=Code&utf8=%E2%9C%93

**Comment by SiR-DanieL** [comment]
Yeah i see, flushed all the cache in the browser and also in plugins but i still get that error.

The script is loaded properly, but there's something that prints the old script into the HTML directly

![](http://cld.wthms.co/1iAcL+)

**Comment by alemarengo** [comment]
Seriously guys, this is very bad for my ecommerces... Neither images can be added. Themes' meta boxes are unavailable too. :(

**Comment by alemarengo** [comment]
Moreover, I cannot attach images to products... Please, see screenshot to see what happens when I click  on Feature Image.
![schermata 03-2457096 alle 13 19 02](https://cloud.githubusercontent.com/assets/6282043/6651649/c7c2c3e6-ca4c-11e4-8505-fe9ef3bc9e25.png)

**Comment by mikejolley** [comment]
Core doesn't reference that variable (see link), so is it an add on?

**Comment by alemarengo** [comment]
mmm... should I disable all the plugin one at a time as usual?

**Comment by alemarengo** [comment]
Ok guys, I've found what it caused it: Woocommerce Smart Coupons, by Skyverge.
By deactivating it, everything in product page editor came back to work!
Now I'm opening a ticket to support. 
Thanks anyway.

**Comment by mikejolley** [comment]
I'll email skyverge about it.

**Comment by bekarice** [comment]
Smart Coupons is from Store Apps :) May want to loop Nirav in.

**Comment by alemarengo** [comment]
waiting for skyverge reply through woothemes ticket system, then I'll mark this thread close

**Comment by mikejolley** [comment]
They have told me an update is going out soon.

**Comment by alemarengo** [comment]
Thanks guys.

**Comment by mindsize** [comment]
Having this issue as well. Doesn't seem to have been patched by the last update.
