### ISSUE TITLE
Create/Update Categories with category images

### ISSUE THREAD

**Issue by marco-hoyer** [woothemes/woocommerce#7727]
Hi,

I would like to have the possibility to create categories with their category images. I implemented this using the wordpress xml-rpc API but adding images is not possible this way. It seems that category images are special to woocommerce. Having this in the woocommerce api would be great. 

Greets,
Marco

**Comment by mikejolley** [comment]
I've moved this request to the roadmap to collect feedback and votes https://trello.com/c/ohklYo3m/54-rest-api-add-category-images
