### ISSUE TITLE
WC 2.3.6 invoice coupon tax display

### ISSUE THREAD

**Issue by mensmaximus** [woothemes/woocommerce#7728]
Version 2.3.6 announced
Fix - Saving an order needs to save the discount amount ex. tax like the cart
Tweak - Show discounts inc. tax when showing order totals inc. tax.

Issue:
After the update coupons get applied with the correct amount but show up plus tax on the invoice (thank you page and emails). However the coupons are stored correct in the database and show up with the right amount in the backend order management:

Order Details:
[cartdiscount] => 10
[cartdiscount_tax] => 0.6542

Order Coupon(Item) Details:
[discountamount] => 9.3458
[discountamount_tax] => 0.6542

Coupon Details:
[discounttype] => fixedcart
[coupon_amount] => 10

If you add the coupon to the cart it shows the amount of -10.00
On the invoice it shows the amount of -10.65
The total amount on the invoice is calculated correct (-10.00)
In wp-admin on the order management it displays -10.00

The cart contains one product including 7% tax

The system status does not report any template overrites. In fact this is a vanilla installation of wordpress with woocommerce only for testing.

The issue is born from function get_total_discount() in class WC_Abstract_Order because the logic has changed from 2.3.5 to 2.3.6:

2.3.6
```
public function get_total_discount( $ex_tax = true ) {
	if ( $ex_tax ) {
		return apply_filters( 'woocommerce_order_amount_total_discount', (double) $this->cart_discount, $this );
	} else {
		return apply_filters( 'woocommerce_order_amount_total_discount', (double) $this->cart_discount + (double) $this->cart_discount_tax, $this );
	}
}
```	
	
2.3.5
```
public function get_total_discount( $ex_tax = true ) {
	if ( $ex_tax ) {
		return apply_filters( 'woocommerce_order_amount_total_discount', (double) $this->cart_discount - (double) $this->cart_discount_tax, $this );
	} else {
		return apply_filters( 'woocommerce_order_amount_total_discount', (double) $this->cart_discount, $this );
	}
}
```

The logic in 2.3.6 assumes the coupon amount is stored without tax in the database and does not take into account whether get_option( 'woocommerce_prices_include_tax' ) is true (from Woocommerce setting 'Yes, I will enter prices inclusive of tax'). 

Proof:
Add following function to your themes functions.php

```
add_filter( 'woocommerce_order_discount_to_display', 'mmx_display_coupon_incl_tax', 10, 2 );
function mmx_display_coupon_incl_tax( $price, $order ) {
    $discount = get_post_meta( $order->id, '_cart_discount', true );
    $debug['price'] = $price;
    $debug['discount'] = wc_price( $discount );
    $debug['taxinc'] = get_option( 'woocommerce_prices_include_tax' );
    $html = '<pre>' . print_r( $debug, true ) . '</pre>';
    return $html;
}
```

The invoice will now show a formatted array instead of the discount value containing the original (wrong) discount, the new (correct) discount value and the current setting of woocommerce_prices_include_tax. 

As for now customers can fix the display using a filter their themes functions.php:

```
/*
	Fix discount display in invoices if prices are entered inclusive tax
	For Woocommerce 2.3.6 only!
*/	

function mmx_display_coupon_incl_tax( $discount, $order ) {
	if ( get_option( 'woocommerce_prices_include_tax' ) == true ) {
		$discount = get_post_meta( $order->id, '_cart_discount', true );
		return wc_price( $discount );
	}
	return $discount;
}
add_filter( 'woocommerce_order_discount_to_display', 'mmx_display_coupon_incl_tax', 10, 2 );
```

This is a quick fix. Therefore I just fetch the correct discount from the post_meta table instead of searching for a maybe better woocommerce function. Please feel free to optimize the code.

This bug should be fixed asap.

**Comment by mikejolley** [comment]
@ChromeOrange @claudiosmweb @barrykooij Can I have feedback on the above commit please?

**Comment by mensmaximus** [comment]
The comitted fix is working in my tests. The coupon amount is now displayed with the correct value.
