### ISSUE TITLE
CRITICAL:  State Selector Field kills checkout w/ Internet Explorer 11

### ISSUE THREAD

**Issue by bentasm1** [woothemes/woocommerce#7729]
When using MIcrosoft Internet Snorer, errr excuse me, Internet Explorer 11, customers are not able to checkout because the state selector field can not be closed.

Others have reported this issue in the WordPress forums:

https://wordpress.org/support/topic/checkout-page-state-select-dropdown-bug-in-ie11

Temporary fix:  "I was able to get around this temporarily by commenting out the files for the select2 JavaScript library inside the woocommerce plugin folder. That disables the state selectors."

**Comment by bentasm1** [comment]
https://wordpress.org/support/topic/state-selector-not-working-in-236-in-internet-explorer?replies=7

**Comment by tipsytopsy** [comment]
Or edit this file:
/wp-content/plugins/woocommerce/includes/class-wc-countries.php

And for all countries you sell to - comment out the placeholder tag in the state section. I only sell in US so it was easy for me.

For example in line 861, for US:

This:
```php
'US' => array(
	'postcode'  => array(
		'label'       => __( 'Zip', 'woocommerce' ),
		'placeholder' => __( 'Zip', 'woocommerce' ),
	),
	'state'     => array(
		'label'       => __( 'State', 'woocommerce' ),
		'placeholder' => __( 'State', 'woocommerce' ),
	)
),
```
becomes
```php
'US' => array(
		'postcode'  => array(
		'label'       => __( 'Zip', 'woocommerce' ),
		'placeholder' => __( 'Zip', 'woocommerce' ),
	),
	'state'     => array(
		'label'       => __( 'State', 'woocommerce' ),
		/*'placeholder' => __( 'State', 'woocommerce' ),*/
	)
),
```

**Comment by karpstrucking** [comment]
This can be patched temporarily without modifying core by adding the following to the active theme's `functions.php` or to a new plugin. You could also add an if-check to only do this for version 2.3.6 I suppose.

```
add_filter( 'woocommerce_get_country_locale', 'gowp_fix_wp_issue_7729', 99 );
function gowp_fix_wp_issue_7729( $locales ) {
        if ( 'specific' == get_option( 'woocommerce_allowed_countries' ) ) {
                $countries = get_option( 'woocommerce_specific_allowed_countries' );
                foreach ( $countries as $country ) {
                       	$locales[$country]['state']['placeholder'] = "";
                }
        } else {
                foreach ( $locales as $key => $locale ) {
                        $locales[$key]['state']['placeholder'] = "";
                }
        }
        return $locales;
}
```

**Comment by jameskoster** [comment]
Seems to be a bug in select2. 4.0.0 is almost ready but not there yet. All we can really do is remove the placeholder attribute on state `select`s.

**Comment by lschatzkin** [comment]
Thanks for the fix, @karpstrucking !

**Comment by mclanecreative** [comment]
This helped me today. Thanks!
