### ISSUE TITLE
WordPress site Completely not working after installing WooCommerce - excelling eCommerce plugin

### ISSUE THREAD

**Issue by prav9884** [woothemes/woocommerce#7730]
Hi Team,

I have installed this plugin (WooCommerce - excelling eCommerce) and my site is down. When I remove this plugin the site works well. 

When I again install it then I get error message as page not found. I really do not have any idea about what is happening after installing this plugin.

Thanks,
Praveen N

**Comment by mikejolley** [comment]
To debug,

- enable http://codex.wordpress.org/WP_DEBUG
- or check server error logs

Once you've done this look for a useful error message. It may just be a memory limit issue http://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP

Closing as this is a support request, not an bug/issue.
