### ISSUE TITLE
Delivery time is missing

### ISSUE THREAD

**Issue by Ninos** [woothemes/woocommerce#7736]
EDIT: I'm sorry, the delivery time is from the woocommerce german market plugin. But I recommend to implement a delivery time into woocommerce . I think such option should be available for all shops.

**Comment by mikejolley** [comment]
I believe this is add-on territory.

**Comment by Ninos** [comment]
I believe the sale price is also add-on torritory.. Joke aside, why you want to ship core features as plugins? Every shop software has a delivery time, because it's needed. If you or your team don't want to implement it, because it's too much work (I don't think that it takes so much time), just let the community know and we'll try to help you out. I'm sure in the next few weeks I could create a pr... :)

**Comment by mikejolley** [comment]
Thats not true though is it. I run stores selling digital goods and I don't need delivery times. I shop on stores which don't provide delivery time pickers.
