### ISSUE TITLE
variations bulk image update

### ISSUE THREAD

**Issue by altatof** [woothemes/woocommerce#7737]
ability to bulk update image variation

**Comment by claudiosmweb** [comment]
You need to put one image for each variation, but if you have some "bulk update" the images will be same... at least is that happens with all variations bulk update actions... So if you want de same image for all products, just don't add any image, because will use the parent product image.

**Comment by altatof** [comment]
imagine my case : about 1200 variations, but 4 images (depends on the first attribute)... how do you manage it without bulk update ? (and of course a pagination for variants...)
