### ISSUE TITLE
New update screws up the teacher privileges for Sensei

### ISSUE THREAD

**Issue by martinkarls** [woothemes/woocommerce#7740]
Just updated to WooCommerce 2.3.6 and since this, users with teacher capabilities in Sensei can't access admin panel. They are just redirected back to their profile page.

My guess is that this has something to do with the following tweak in WooCommerce 2.3.6:
"Tweak - Move default customer location to general settings tab." ?

Am I way off here or did you forget to sync this tweak with Sensei? For now none of the teachers are able to handle learners or grade quizzes.

**Comment by mikejolley** [comment]
Way off; moving a setting won't affect user roles.

**Comment by martinkarls** [comment]
Well, maybe I don't read the developer lingo properly, but something in the new WooCommerce update has made it impossible for user with teacher roles to access the admin panel.

Could it be this?

![skarmavbild 2015-03-17 kl 11 13 57](https://cloud.githubusercontent.com/assets/11160218/6684998/94819006-cc96-11e4-84ff-db49ef9e9c35.png)

**Comment by claudiosmweb** [comment]
@martinkarls I just fix this function for compatibility with older versions of WooCommerce. It was wrong, so if you could access before was because it had a bug before and has not now.

And you is free for use the `woocommerce_prevent_admin_access` filter to allow any user level you want.

cc @hlashbrooke @danjjohnson

**Comment by martinkarls** [comment]
Ok, then I guess that the problem is in Sensei. The Teacher role that you assign in Sensei is allowed to handle learners och grading quizzes. But they are not allowed to edit posts. So, if I understand this correctly, with the prevent_admin_access function in WooCommerce Teachers in Sensei is considered customers and are redirected to the my account page as soon as they try to reach the admin area.

This makes WooCommerce and Sensei no longer compatible "out of the box".

Well, I guess I have to move this over to the Sensei developers and hope that they can come up with a solution.

**Comment by claudiosmweb** [comment]
Just need to use the `woocommerce_prevent_admin_access` filter for it.
Can test in your theme or in Sensei for the Teacher role and allow to see the admin.

**Comment by claudiosmweb** [comment]
@martinkarls I'm opening a ticket about it on Sensei.
