### ISSUE TITLE
Digital download counter fails to increase

### ISSUE THREAD

**Issue by agarwalc** [woothemes/woocommerce#7741]
Since the 2.3 update, the download counter which we see on Edit Order page does not increase when the customer downloads the file.

**Comment by mikejolley** [comment]
Maybe you're looking at the wrong permissions - just checked and the counter increases https://dl.dropboxusercontent.com/s/4d4fniv1wkiwh3o/2015-03-17%20at%2014.45%202x.png?dl=0
