### ISSUE TITLE
Discount price is wrong - coupon code

### ISSUE THREAD

**Issue by Ninos** [woothemes/woocommerce#7742]
Hey there,
I really don't understand the discount. I've used a 20 € coupon code and get following tables:
![screenshot - my account](https://cloud.githubusercontent.com/assets/1012403/6685909/71426158-cc9e-11e4-9020-e4b937514d97.png)
![screenshot - admin](https://cloud.githubusercontent.com/assets/1012403/6685910/7143938e-cc9e-11e4-988e-2cbeb423a801.png)

Now I don't understand where the 20 € are and on "my account -> order" area how you get the -23,19 € discount price. I'm really confused about that and think there's somewhere a bug.

**Comment by mikejolley** [comment]
Can you reference https://github.com/woothemes/woocommerce/issues/7728

**Comment by Ninos** [comment]
Should be the same problem. I'll close this ticket.. :)
