### ISSUE TITLE
After upgrading to the Latest Woocommerce, Account Funds(Manual Payments) during checkout always returns "Coupon Does Not Exists"

### ISSUE THREAD

**Issue by JoseRaffucci** [woothemes/woocommerce#7744]
After upgrading to the Latest Woocommerce, Account Funds(Manual Payments) during checkout always returns "Coupon Does Not Exists".

I have submitted a ticket on woothemes, the first ticket in the system disappeared or was deleted without a response, I had to resubmit the ticket but no response.

This is a critical issue as we have had to turn off manual payments on our website causing problems for our customers and lost sales for our business.

**Comment by mikejolley** [comment]
Post the ticket ID, I'll have @ChromeOrange take a look.

**Comment by JoseRaffucci** [comment]
The current ticket id is:  271805

The ticket id that was removed or deleted without notification is: 271642

Thank you for following up, hoping to get this resolved ASAP.
