### ISSUE TITLE
esc_url_raw problem?

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#7746]
> I didn’t want to open a brand new issue on the Github, but I ran into a problem caused by one of the changes submitted by you. Here is more info https://support.woothemes.com/hc/communities/public/questions/202551325-Absolute-file-path-issue-on-downloadable-products-. I think esc_url_raw is the culprit and returns an empty string when you pass a file path for whatever reason.

**Comment by claudiosmweb** [comment]
`_wc_file_urls` expects to receive paths, not just URLs?

**Comment by mikejolley** [comment]
I think it can work with both..

**Comment by claudiosmweb** [comment]
So `_wc_file_urls` is a weird name for it :p
