### ISSUE TITLE
Customer stats&reporting when orders are made by users which belong to another "blog" in a Wordpress Multisite setup

### ISSUE THREAD

**Issue by luciancapdefier** [woothemes/woocommerce#7750]
Hi,

In the scenario is: site.com is a main site and abc.site.com is a secondary site, for which user XYZ is a user registered as administrator and affiliated just with abc.site.com, so the secondary site and the main site, site.com runs woocommerce and sells something. Problem: when user XYZ buys something from site.com, the statistics do not show that user XYZ have made a sale; you cannot find it in the customer list, nor in the reports. I assume it has to do with a broader problem - because user XYZ does not even get listed in the admin panel, under Users, in dashboard of site.com.

My expected behaviour would have been that user XYZ would get at least subscriber/customer role for site.com and show-up in the statistics, etc.

Let me know if this has to do with woocommerce or you would rather see it as a broader problem.

Thx,

**Comment by mikejolley** [comment]
Partially related to https://trello.com/c/0rsdFZMS/47-manage-all-multisite-orders-in-main-site and other plans for mulitsite compat. WC works on a per-site basis currently.

**Comment by luciancapdefier** [comment]
Cheers!

In case this helps - this is resolvable with plugin 
Join My Multisite


1. You activate it across the network.
2. Set your site.com <http://site.com/> plugin for auto registration, under Customer role.

All seem to work after this, which is user is seen in site.com <http://site.com/> User’s list and also in WooCommerce reports, etc.
