### ISSUE TITLE
Chile Bug?

### ISSUE THREAD

**Issue by sexpressed** [woothemes/woocommerce#7754]
At the present time customers from Chile are unable to enter their postcode/zip code during checkout on any of my WooCommerce sites. When you select Chile from the country drop-down box, the text box where you would put your zip code is not there. It appears to be there for every other country, just not Chile. Since I have WooCommerce set to not let anyone check out without first entering their zip code (which my CC merchant account will then check and approve before fulfilling the transaction) this effectively means that no one from Chile can buy things from my store. Anyone else have this issue? I am on WooCommerce 2.3.6 and running the latest WordPress.

**Comment by slash1andy** [comment]
Chile has postal codes, but they are rarely used, so it's not a bug. It's done that way on purpose.

**Comment by mikejolley** [comment]
@slash1andy are you from chile? :p 

http://www.alliescomputing.com/innovation/address-format/Chile

Seems to be used sometimes, so I'll make it non-required but present.

**Comment by sexpressed** [comment]
But it IS required. WooCommerce looks for a zip code to be entered...if one is not entered, the customer cannot complete the transaction. I've had a customer from Chile trying to do everything to make it work, but it won't even get to the point of the transaction being sent to my CC merchant for approval...it just won't send.

**Comment by mikejolley** [comment]
@sexpressed WC will not enforce postcode if not required, so maybe its your payment processor with this requirement.

**Comment by sexpressed** [comment]
That's what I originally thought but there are no records with my CC merchant provider that a transaction has even been sent to them for approval. And, even if it did make it for approval, they would most likely reject it based on there being no zip code to match to the CC to avoid fraudulent transactions.

**Comment by mikejolley** [comment]
What gateway is it? test another?

**Comment by sexpressed** [comment]
I only use one gateway, the Authorize.net AIM one from WooThemes. My site is considered "high risk" so that's the only gateway I'm allowed to use for now.

Clearly this issue is not affecting other users like it is me, so I don't want to take up too much of your time. If a zip code entry can be added to Chile's checkout that would be great, and I'll just add my own code into my functions.php to let anyone who chooses Chile as their billing country know that the zip code entry is mandatory. Thanks.
