### ISSUE TITLE
Cannot identify which order items belong to shipping rate in order items metabox

### ISSUE THREAD

**Issue by cloudratha** [woothemes/woocommerce#7755]
I'm writing a plugin that can separate your order into multiple packages, with an option to consolidate them. Following the guide by Mike here : http://mikejolley.com/2013/12/manipulating-shipping-packages-woocommerce-2-1/

My issue now is on the order item metabox which displays the order items with the shipping rate It is impossible for me to see which order items belong to which shipping rate. Any ideas on how I could link the two?

**Comment by mikejolley** [comment]
Might require some core edits to store this data on the shipping line item. checkout class, line 260. Feel free to submit a pull request if you have a good solution.
