### ISSUE TITLE
Rest API 1

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#7759]
Hi,

I am trying to set-up a client to use the REST API. When I visit the page, I get a 1:

https://www.fermetournesol.qc.ca/en/wc-api/v1

He said he enabled the API. Do you know what's wrong?

**Comment by claudiosmweb** [comment]
Recommend stop using v1 API, so this depreciated and soon we get support.
In your problem seems to be the plugin you are using for multi language.

When the API this off you should see:
```json
{"errors":{"code":"woocommerce_api_disabled","message":"The WooCommerce API is disabled on this site"}}
```

**Comment by jmawebtech** [comment]
Hi,

Is there a special URL for multi-language? What should the base URL be, Claudio?

**Comment by claudiosmweb** [comment]
I don't know, need to test with your plugin. I never used this plugin before.

**Comment by jmawebtech** [comment]
Hi,

I need the URL to just return JSON. Here is an example:

https://jmawoocommercetest.azurewebsites.net/wc-api/v2

If the customer uses a multi-lingual site, what is the endpoint for the API?

{"store":{"name":"WooCommerce Test","description":"Just another WordPress site","URL":"http:\/\/jmawoocommercetest.azurewebsites.net","wc_version":"2.2.0","routes":{"\/":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/"}},"\/customers":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/customers"},"accepts_data":true},"\/customers\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/customers\/count"}},"\/customers\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/customers\/email\/<email>":{"supports":["HEAD","GET"]},"\/customers\/<id>\/orders":{"supports":["HEAD","GET"]},"\/customers\/<id>\/downloads":{"supports":["HEAD","GET"]},"\/orders":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/orders"},"accepts_data":true},"\/orders\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/orders\/count"}},"\/orders\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/orders\/<order_id>\/notes":{"supports":["HEAD","GET","POST"],"accepts_data":true},"\/orders\/<order_id>\/notes\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/products":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/products"},"accepts_data":true},"\/products\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/products\/count"}},"\/products\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/products\/<id>\/reviews":{"supports":["HEAD","GET"]},"\/products\/categories":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/products\/categories"}},"\/products\/categories\/<id>":{"supports":["HEAD","GET"]},"\/coupons":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/coupons"},"accepts_data":true},"\/coupons\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/coupons\/count"}},"\/coupons\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/coupons\/code\/<code>":{"supports":["HEAD","GET"]},"\/reports":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/reports"}},"\/reports\/sales":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/reports\/sales"}},"\/reports\/sales\/top_sellers":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/reports\/sales\/top_sellers"}},"\/webhooks":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/webhooks"},"accepts_data":true},"\/webhooks\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/jmawoocommercetest.azurewebsites.net\/wc-api\/v2\/webhooks\/count"}},"\/webhooks\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/webhooks\/<webhook_id>\/deliveries":{"supports":["HEAD","GET"]},"\/webhooks\/<webhook_id>\/deliveries\/<id>":{"supports":["HEAD","GET"]}},"meta":{"timezone":"Africa\/Abidjan","currency":"USD","currency_format":"&#36;","tax_included":false,"weight_unit":"kg","dimension_unit":"cm","ssl_enabled":false,"permalinks_enabled":true,"links":{"help":"http:\/\/woothemes.github.io\/woocommerce\/rest-api\/"}}}}

**Comment by claudiosmweb** [comment]
@jmawebtech is the *multi-lingual site* a WooCommerce native feature?

**Comment by jmawebtech** [comment]
Hi,

They are using WPML.

**Comment by claudiosmweb** [comment]
@jmawebtech So maybe you are asking the wrong place.

**Comment by bekarice** [comment]
Hey @jmawebtech this sounds like the same issue we've seen with the iOS app where WPML breaks the REST API with a certain setting. [Check the details out here](https://support.woothemes.com/hc/en-us/articles/203667749-iOS-App-Troubleshooting-Known-Conflicts) for a potential fix, but they really do need to fix this on their end, as it will almost certainly break the WordPress REST API when it's in core as well.

**Comment by claudiosmweb** [comment]
@bekarice thanks :)
