### ISSUE TITLE
Cart Page Goal Conversion

### ISSUE THREAD

**Issue by michaelbroper** [woothemes/woocommerce#7760]
After upgrading to 2.3, my conversion took a pretty big hit. Using Hotjar I found the 'proceed to checkout' conversion dropped from 52.5% to 30.4%.

I got help from Patrick Garman here: https://www.facebook.com/groups/advanced.woocommerce/permalink/1042821859065566/

We hacked together a little piece of code to replace the 'proceed to checkout' button to it's original location in 2.2. I also had my designer tweak and make it fit properly. Conversion returned to normal.

It just makes sense to not have the main action button so far down the page. People are lazy and don't search that far to take the next step. At the very least on mobile devices, it should be right underneath the products, full width, easy to click, no scrolling required.

I would suggest at the very least to have an option to display/hide the original button location in WooCommerce' settings.

**Comment by claudiosmweb** [comment]
You can change this in your template as you did, no need an extra option for it.
On converting this is relative, especially because now client down to click on the button you can use best Cross-Sales options.

**Comment by michaelbroper** [comment]
That's a dangerously incorrect assumption the client will scroll down to even view the cross-sales. That doesn't happen. I have data to prove it. Those offers never converted at any meaningful amount, even pre Woo 2.3. I'm trying to make Woo as a whole better, not just my stores. Store owners will be upset when their conversions drop and they have no idea why. Eventually they will figure out it was a WooCommerce update without any conversion data to back up changes. Right now you are running on theory. I have test results proving otherwise. I have software to track with the traffic volume to have enough data to measure these changes and get accurate data as to the causes of a conversion drop. It's clear it's your 'proceed to cart' button move is a mistake. Hopefully people don't lose money. I lost a few grand in a couple days from the update. Smaller businesses won't see it for months down the road. I'm trying to help them out here.

**Comment by claudiosmweb** [comment]
@michaelbroper this happens in my stores. And several other examples of shops or platforms so does.
Only the WooCommerce had the button above.

**Comment by michaelbroper** [comment]
@claudiosmweb Do you have Woo shops with over 2k visitors a day, and software tracking their completion to /checkout/order-received at each step of the way? And you've seen no dropoff of visitors going to checkout?

I don't care if other shops and platforms have the button further down. I care because sales dropped and the data pointed to one specific page being an issue. I added the proceed to checkout button again and it fixed the issue. It is an on/off switch for sales. I'm sure other business owners will eventually come to the same conclusion.

The fact is the move is a bad design change. It doesn't matter if Amazon and every other big player has a 'proceed' button lower on the page. If you want to talk about UX, make it so they don't have to scroll to click 'proceed'. WooCommerce had something that worked really well and changed it to seemingly "fit in" with modern design trends. That's a mistake.

Businesses do not care how things look. Businesses care about sales, conversion, and money. Usually the way things look and function improve those metrics. In this case, it clearly didn't. If WooCommerce continues to make changes like this, webmasters will switch to other platforms because they will make more money elsewhere without having to make special hooks to get a decent conversion rate.

**Comment by mikejolley** [comment]
This is very subjective. @BFTrick @jameskoster any thoughts on this?

**Comment by claudiosmweb** [comment]
@michaelbroper it seems that you reported the problem day 2 days ago and today has changed the button and surprising this saved all your conversion rate...
But all I see is you aggressively complaining about it and as I said, if you are not satisfied with the position of the button, just change it in your theme.

**Comment by michaelbroper** [comment]
@claudiosmweb I had the fix in yesterday. I didn't wait around. I have enough data to see a bounceback quickly. I know the sales patterns well enough to accurately measure which changes have an effect. 

If it's "aggressively complaining" and "subjective" to use real data to come to a conclusion that affects my bank account - well, so be it.

**Comment by claudiosmweb** [comment]
@michaelbroper as I said, I'm also using and not had this problem. But you are saying that you are right in all instances, no matter what I say or show you, you will continue aggressively telling you this right.
At your topic on Facebook you were already acting aggressively, it would be no different here.
This is not the way to solve things, much less convince someone you're right.

**Comment by BFTrick** [comment]
@michaelbroper @claudiosmweb - hey guys. We're going to talk about this issue during our WooCommerce dev meeting this week and how we want to handle future items like this.

We do need usage stats for changes. That's why we put the tracker in the last release. It doesn't help us with this use case but we are well aware we need data. 

Give us a few days @michaelbroper and I'll see if there's a good way to get the necessary data for decisions like this.

**Comment by claudiosmweb** [comment]
@BFTrick For me this entire screen to be redrawn, especially if we turn this into Ajax with #6734

AS @michaelbroper on Facebook:
>There's no way Woo tested that change before putting it out. They need to test out function before design. Just because Jonathan Ive makes a new design trend doesn't mean it's good for business.

But maybe the apple store cart can be a great idea:
![screenshot from 2015-03-18 14 58 27](https://cloud.githubusercontent.com/assets/1264099/6715750/62bddba8-cd7f-11e4-8b2d-990d51920951.png)

**Comment by michaelbroper** [comment]
@BFTrick Metrilo and Hotjar with a 4 step URL identifier are the best ways I've found to track. Google Analytics doesn't quite do it. 

It would be nice to have an official Product View -> Cart -> Checkout -> Completion table we could measure. 

@claudiosmweb You know Tim Cook will make Apple's store convert as best it can! :+1: I love that design. Just needs tested in the Woo environment.

**Comment by jameskoster** [comment]
We moved the button for a couple of reasons.

* It crowds the action bar on the cart table, especially when you have coupons enabled and gateways which add extra buttons like PayPal Express.
* Some folks were complaining about proceeding to checkout without seeing the totals.

Data from a single store isn't enough to clarify this as a mistake. WooCommerce powers thousands of shops, if this was a huge deal there would be more noise. 

I'll monitor this, but it's unlikely to change in core. Luckily changing it back is a very simple tweak for you.
