### ISSUE TITLE
Custom fields not showing for Product Variations in the Dashboard

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7762]
Custom fields  for product variations are not loading in the backend after saving, I have recreated this on the local server and the custom field data doesn't load under the **Products >> Edit  Product >> Product Data >>  Variations >> Custom field** after pressing **Update**. I am using [this snippet](https://gist.github.com/kloon/4228021) for creating a custom field for product variations.

![](http://cld.wthms.co/11KDW+)

@mikejolley @claudiosmweb @seanreloaded 
https://woothemes.zendesk.com/agent/tickets/269033

**Comment by mikejolley** [comment]
I don't think variation_data is set any more. Use get_post_meta. This is a custom snippet, not core.
