### ISSUE TITLE
$order->calculate_taxes()

### ISSUE THREAD

**Issue by des79** [woothemes/woocommerce#7765]
I'll try to create an order programmtically like this http://stackoverflow.com/questions/26581467/creating-woocommerce-order-with-line-item-programatically#26588393

woocommerce_tax_based_on is set to billing but when I create order without billing data (customer populate them after), order has tax item to 0 instead of XX when I call $order->calculate_totals();

I think is better replace "if" statement with "switch" on class WC_Abstract_Order->calculate_taxes()
and move default args to base_location like this:
<pre>
$tax_based_on = get_option( 'woocommerce_tax_based_on' );
switch($tax_based_on ) {
	case 'billing':

		$country  = $this->billing_country;
		$state    = $this->billing_state;
		$postcode = $this->billing_postcode;
		$city     = $this->billing_city;
		break;
	case 'shipping':
		$country  = $this->shipping_country;
		$state    = $this->shipping_state;
		$postcode = $this->shipping_postcode;
		$city     = $this->shipping_city;
		break;

	default :
		$default  = wc_get_base_location();
		$country  = $default['country'];
		$state    = $default['state'];
		$postcode = '';
		$city     = '';
		break;
}
</pre>
what do you think?

Thanks.
David

**Comment by des79** [comment]
Or better,

if $country is empty in default if else statement, set it to default base location, otherwise order is created without tax item.

**Comment by mikejolley** [comment]
I think if you explicitly set woocommerce_tax_based_on based on shipping or billing, you need to respect this during order creation, not default to base because ultimately the taxes may be wrong. What is the issue with setting address during order creation?

**Comment by des79** [comment]
Hi @mikejolley,

thank you for your response, but I've 2 different case, during checkout and programmatically. Via checkout customer compile data and woocommerce_tax_based_on is correctly to billing but programmatically, when I import csv, the customer fill out billing data at a later time. In this case _billing_country is empty and tax calculation is wrong. 

In the calculate_taxes method comment said "Will use the base country unless customer addresses are set."
