### ISSUE TITLE
Shop Page - Show Products by Category

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#7766]
Another enhancement would be to add an option which would allow you to view products by their certain category.  this would be most helpful in situations with many products

many thanks

**Comment by claudiosmweb** [comment]
You can just create a page and use your shortcodes for it:
http://docs.woothemes.com/document/woocommerce-shortcodes/

Example:

```
<h2>Clothing</h2>

[product_category category="clothing" per_page="4"]

<h2>Music</h2>

[product_category category="music" per_page="4"]
```

![screenshot from 2015-03-18 16 15 39](https://cloud.githubusercontent.com/assets/1264099/6717290/3d6e622c-cd8a-11e4-862b-9113a1aa6f39.png)
