### ISSUE TITLE
Update Shipment Tracking 

### ISSUE THREAD

**Issue by mfishbowl** [woothemes/woocommerce#7767]
Is their a Rest API call that I can use to update tracking information? I see there is a call to update order status but I do not see a way to update tracking and carrier information. I am writing an application using C#.
The link http://woothemes.github.io/woocommerce-rest-api-docs/#version are all the calls I see and I do not see a call for update tracking

Please help!

**Comment by claudiosmweb** [comment]
This **Shipment Tracking** is not a WooCommerce native feature, so we don't have any API for it.
Need to be done in the plugin that provide this feature.
