### ISSUE TITLE
Shipping taxes calculated incorrectly

### ISSUE THREAD

**Issue by webbisivut** [woothemes/woocommerce#7768]
From version 2.3.5 WooCommerce has been calculating taxes incorrectly for shipping methods. If I choose to input shipping costs including taxes, it will calculate total cost anyway excluding taxes.

Like if I want the total shipping cost to be 10€ including VAT 24%. The total cost will be 12.40€, instead of 10€. Im also aware of setting up tax classes table, but that does not fix this issue. WooCommerce seems to ignore the settings i set in there.

**Comment by mikejolley** [comment]
Shipping costs have *always* be defined excl. of VAT regardless of settings. This is explained in the inline tooltips. An item to change this is on the roadmap.
