### ISSUE TITLE
CSS and JS files doesn't get added in custom theme

### ISSUE THREAD

**Issue by hajindersingh645** [woothemes/woocommerce#7770]
Hi Team,

First of all thanks for such great plugin. 

I have been developing custom theme for my client using WordPress, even i have copied the template folder into custom theme folder and than renaming it **woocommerce** [custom-theme/woocommerce/]. 

But when ever check the product page or any page that is connected with **woocommerce**, no js file 
has been included into the pages, default ones that come with the plugin. Only three **CSS** files has been included in every page **woocommerce-layout.css, woo commerce-smallscreen.css and woocommerce.css**

Lastly it's even more interesting that whenever i switch back to **twintyfifteen** theme, all files gets included.

Is there any thing that i'm missing in my custom theme, any code. Kindly help me out of this situation. It's been three days i have looking for answers.

Cheers
Harjinder

**Comment by claudiosmweb** [comment]
Your theme need to have http://codex.wordpress.org/Function_Reference/wp_footer and http://codex.wordpress.org/Function_Reference/wp_head

**Comment by hajindersingh645** [comment]
@claudiosmweb Thanks for quick reply. Can i know what does this means to have both in respective files.

**Comment by shivapoudel** [comment]
Check if you forgot to trigger below action hooks in your theme template:
- `wp_head()`: Put this template tag immediately before`</head>` tag in a theme `header.php`.
- `wp_footer()`: Put this template tag immediately before `</body>` tag in a theme `footer.php`.

**Comment by shivapoudel** [comment]
@hajindersingh645 you can read the example snippets on codex if you surf the above links provided by @claudiosmweb for more details ;)

**Comment by hajindersingh645** [comment]
@claudiosmweb 
@shivapoduel

Thanks for information, I might have forgot to add these.

Cheers :)
Happy Coding
