### ISSUE TITLE
Ability to configure product fields in manual orders

### ISSUE THREAD

**Issue by franticpsyx** [woothemes/woocommerce#7776]
Currently, the core doesn't provide an infrastructure for configuring products when adding a product manually into an order. All we can do is add a single line item - no form/fields can be added to trigger extension-specific actions such as adding custom order meta or adding extra line items / fees linked to the initially-added product.

This affects the core *and* many extensions -- variable products, composites, add-ons, bundles, grouped products, to name a few. 

At the moment, most shop managers go around this issue/limitation by creating an order in the front end, and then assigning the right customer to it.

Is there any interest/ideas for developing that sort of functionality in core, or should this be developed on a extension-specific basis?

I was thinking about taking a shot at it and send a pull request, but it might make more sense to brainstorm some ideas about it first, before doing any actual work.

From a UX perspective, one way to do this would be to provide a "Set product options" button under "Add meta", which would display a set of extension-specific fields added by extensions via hooks. The core will simply allow posting this field content and provide an ajax handler where extensions could hook into to intercept their data and modify the order. The handler could then return the updated order content (line items, meta + fees).

In core, this infrastructure would be used to allow selecting variable product attributes, or to configure a grouped product. Extensions could do whatever they want with it.

Thoughts? CC @BFTrick

**Comment by mikejolley** [comment]
I've moved this to roadmap too. This would be a useful one IMO, especially for plugins like product addons. https://trello.com/c/UlW3M1Ha/69-configurable-product-fileds-in-orders-backend
