### ISSUE TITLE
Cart fragments script cause resource use to double on every page load when cart is non-empty

### ISSUE THREAD

**Issue by forsvunnet** [woothemes/woocommerce#7777]
In woocommerce/includes/class-wc-frontend-scripts.php on line 161
```
self::enqueue_script( 'wc-cart-fragments', $frontend_script_path . 'cart-fragments' . $suffix . '.js', array( 'jquery', 'jquery-cookie' ) );
```
We encountered this today when one of our clients websites had a traffic spike. By looking through the network tab in chrome I noticed wp-admin/admin-ajax.php loaded on every page load, and by looking at the response i deduced cart-framents to be the culprit.
By dequeueing the wc-cart-fragments script we halved the servers resource usage for the website.

We tested the shop before and after and could not detect any feature loss after deactivating the script.

I'm not familiar with the code, but it looks like the script is only used by a widget.
If this is the case then there should be some logic here which checks wether the widget is active or not before enqueuing the script.

**Comment by mikejolley** [comment]
This is used by themes too which show cart information on pages. This is basically a static cache busting script required to show uncached cart data on all pages.

**Comment by forsvunnet** [comment]
I would suggest then that themes that use this feature should declare use of it through the 'add_theme_support' function. This feature left unchecked is a performance killer for the unwary theme.

I'm leaving a code snippet here as a workaround for developers looking for a quickfix/workaround for current versions of woocommerce:

```
/**
 * Dequeue wc-fragments
 * Removes synchronous wp-admin/ajax request that happened on every page load when cart is non-empty.
 * This script is not in use and should be safe to disable.
 */
function dequeue_wc_fragments() {
    wp_dequeue_script( 'wc-cart-fragments' );
}
add_action( 'wp_enqueue_scripts', 'dequeue_wc_fragments', 100 );
```

**Comment by mikejolley** [comment]
This isn't ideal because themes will break until they notice we've removed the script.

There may be a bug causing it to load on each page; I added a fix and speed improvements to this branch https://github.com/woothemes/woocommerce/tree/wc-ajax-endpoint

**Comment by forsvunnet** [comment]
I've checked the changes, but I don't think this is a permanent solution.
The problem is intrinsic to the purpose of the script. Punching through the cache and loading wp (even if it's async) can quickly bog down the server because all plugins are initialised and loaded before the ajax output is generated.

There are pretty much only two options for permanently solving this issue. One is to deprecate the enqueuing of the script, the other is to detect whether the plugin is using the script. I suggested the former because the latter is pretty difficult to do.

Our case was that one of our clients received national press coverage and he suddenly had 250 000 visitors pouring in. We had over 4000 orders on one day. That number would have been significantly lower had we not dequeued the fragments-script.

**Comment by yratof** [comment]
With the the small amount of themes that might use this, can you not depreciate it & put a warning in the update? Server load on a site where fragments isn't being used but is requesting cuts someones traffic down by half, halting the sales that they can make & cutting git down a bunch. Ultimately, costing the client money for no reason

**Comment by mikejolley** [comment]
@yratof we're not deprecating something themes and core both use. It is much more difficult (and prone to error) for themes to add their own custom solution than it is to dequeue a script with 1 line of code.

**Comment by jessuppi** [comment]
If anyone is interested, we made a free WordPress plugin based on this GitHub issue:

[https://wordpress.org/plugins/disable-cart-fragments-littlebizzy/](https://wordpress.org/plugins/disable-cart-fragments-littlebizzy/)

**Comment by yratof** [comment]
@jessuppi plugin mentions 'huge boost in loading speed', are there any instances where you've found it to actually give noticeable performance boosts?

**Comment by jessuppi** [comment]
@yratof This client shaved off 37 seconds immediately from this plugin alone:

https://www.littlebizzy.com/blog/37-secs-woocommerce

**Comment by yratof** [comment]
37 seconds from Fragments??

**Comment by buckneri** [comment]
Yeah i'm looking at a site right now that its causing 5 additional seconds of load time just for the cart fragments.  On another site that actually uses the fragments (cart popup when you add things to the cart, and to update the cart on the menu bard) its adding only 2.5 seconds, but on a page that has 8 seconds of load time 2.5 is a large chunk of its load time to just check whats in the damn cart. 

I'm betting i can save that info to the database or browser local storage and retrieve it when needed rather than trying to ajax update all the time.

**Comment by makeonlineshop** [comment]
hello,

Can you confirm that this code is still ok to use ? Thank you for your help.


add_action( 'wp_print_scripts', 'nuke_cart_fragments', 100 );
function nuke_cart_fragments() {
    wp_dequeue_script( 'wc-cart-fragments' );
    return true;
}

**Comment by coffeeholick** [comment]
@makeonlineshop i used that code and it had absolutely no effect, positive or negative, whatsoever. 

i'm running the latest version of WooCommerce (3.5.2)....

i've tried plugin after plugin; nothing works.

**Comment by coffeeholick** [comment]
...also: i tried the webnots code solution (all of them) and also the code from a "bearded guy" named jeff as he refers to himself (jeff matson i believe)....nada, nothing at all

**Comment by makeonlineshop** [comment]
So there is no working code to disable cart fragment ?!

**Comment by makeonlineshop** [comment]
And why is this plugin closed now ? Wordpress gestapo doing its job ?!
https://wordpress.org/plugins/disable-cart-fragments-littlebizzy/

**Comment by rrennick** [comment]
> And why is this plugin closed now ?

WordPress.org shuts down plugins if the plugin author requests it or they contain malware, security vulnerabilities, etc.

**Comment by jessuppi** [comment]
The plugin still works and is still available (some basic research helps):

https://github.com/littlebizzy/disable-cart-fragments
https://www.littlebizzy.com/plugins

Using search engines and following instructions tends to go a long way. Review the plugin readme and if you are having issues, try seeking support as described there.
