### ISSUE TITLE
Hide quantity input for individually sold variable products

### ISSUE THREAD

**Issue by andi98** [woothemes/woocommerce#7778]
In the template [single-product/add-to-cart/variable.php](https://github.com/woothemes/woocommerce/blob/master/templates/single-product/add-to-cart/variable.php#L77-L80) it should be checked if the product is sold individually to show/hide the quantity input as in [simple.php](https://github.com/woothemes/woocommerce/blob/master/templates/single-product/add-to-cart/simple.php#L38).
Thank you!

**Comment by mikejolley** [comment]
This is already taken care of by the javascript. See https://dl.dropboxusercontent.com/s/s17bhexcmtjddmx/2015-03-20%20at%2015.07%202x.png?dl=0
