### ISSUE TITLE
SQL Query issue with reports

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7781]
On some installation seems that there's a limit with SQL query size.

This is the screenshot of the query result for last 7 days sales report: http://cld.wthms.co/2Thu

Can we run `SET SQL_BIG_SELECTS=1` before these queries in order to ensure that it works?

**Comment by mikejolley** [comment]
I think it would be better for the end-user to set this if their configuration requires it. Doing this ourselves could cause compatibility problems with other environments, such as permission issues. @SiR-DanieL Would you mind writing a help doc for docs.woo?  cc @barrykooij

**Comment by SiR-DanieL** [comment]
Ok, will check it later and will write a doc.

**Comment by SiR-DanieL** [comment]
@mikejolley i'm seeing this issue more frequently now. There's nothing we can do without breaking the permissions on other environments?

I was not able to write a doc on WooThemes because i was not able to fix it with a snippet yet.
