### ISSUE TITLE
WooCommerce + Social Login Update Order may cause blank screen

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#7784]
Ticket : https://woothemes.zendesk.com/agent/tickets/272000

From the customer:
When updating woocommerce to 2.3.6 with social login plugin still on 1.3.2, admin and front end display only blank pages. Removing the social login plugin via FTP and re-installing the latest 1.4.0 fixes this again. Therefore social login should be updated to 1.4.0 before updating woocommerce to 2.3.6 
Just thought I'd let you know in case someone else gets this too.

I'd imagine this was fixed with 2.3.7 or another update, but I wanted to pass it along.

**Comment by ChromeOrange** [comment]
Hey @DanielSantoro 

2015.02.09 - version 1.4.0
 * Misc - WooCommerce 2.3 Compatibility

there will be some deprecated functions etc that cause a fatal error etc, that's why we always recommend updating the plugins first.

It's not an issue with WC
