### ISSUE TITLE
"ex. tax" appearing in email notifications

### ISSUE THREAD

**Issue by vegaix9** [woothemes/woocommerce#7788]
In customer invoice and new order notifications, the label "ex. tax" now appears below the product price and subtotal with the release of 2.3.7.

I'm curious to know the reason for this addition, and what method there is to disable it.

**Comment by plainestudios** [comment]
What is the fix for this?  I see it was closed, but don't see a fix.

**Comment by ChrisMcKay** [comment]
In the linked file, is the ==='yes' supposed to be a 'no' in order to remove the ex tax from the invoice or is it a verbatim fix?

**Comment by mikejolley** [comment]
The === yes is because the meta stores a string (yes or no) and we need to convert this to a boolean value.

**Comment by ChrisMcKay** [comment]
This worked for me, thanks @mikejolley
