### ISSUE TITLE
Override add to cart in Woo Commerce.

### ISSUE THREAD

**Issue by gobnet14** [woothemes/woocommerce#7789]
Hi, Just wondering if anybody can direct me on this. I am trying to display up to 50 sizes per product in a Woo Commerce Shop Product Page. I do not want to display them in a drop down menu as is the norm with variable products I want to set the item information in a table format

e.g. Product Name  Size  Specifications  Price   Quantity Required   Add to Cart Button.
    
I want the front end to look something like this

http://kitchenwarehouseltd.com/replacement-kitchen-doors/high-gloss/high-gloss-cream

My problem is that when I set my table as above and copy and paste code for the "Quanities Counter and Add To Cart Button"  it all looks well on the page but unfortunately when I click the add to cart button it adds the price that is set in the Simple Product and not the price that is set on the row in the table. If I remove the Simple Product Price then the Product does not show in the category page.

Can somebody direct me somewhere where I can find a solutions to my problem.

Thanks.

**Comment by mikejolley** [comment]
Please don't use Github to ask for help - this is for bug reports only.

Look at http://www.woothemes.com/products/bulk-variation-forms/
