### ISSUE TITLE
***ISSUE*** with Country/State Select option on Checkout & Registration page

### ISSUE THREAD

**Issue by graphitivity** [woothemes/woocommerce#7790]
Hello guys

Is it only me or everyone else experience the same on Win8 IE11 and on Mac...? The checkout as a guest option has an issue because as soon as you select the country the state dropdown pop's up unnaturally. The rest of the fields become red when you try to select one of the states nothing get's selected so you keep clicking on it but it wont take the input and wont let the users fill other fields so one cannot checkout. 

Please see this video https://www.youtube.com/watch?v=JnKp-CfmC5M 

I checked canvas theme on IE11 and mac and it's exactly same problem.

Same issue on the register as a new user and checkout as the dropdown pop's up to create new account and never take any input and all other fields show red.

This works fine in chrome but has problem in IE11 and MAC it's an urgent issue as all of them who are using this theme cannot checkout or register using IE11 and MAC please help!

**Comment by mikejolley** [comment]
This theme/site is not running the latest (fixed) version. It's to do with select2 + placeholders.

**Comment by graphitivity** [comment]
I'm running version 2.3.7 the issue in this video https://www.youtube.com/watch?v=JnKp-CfmC5M still exist on IE11 & Mac browsers.
