### ISSUE TITLE
A formal parent-child model for cart and order items

### ISSUE THREAD

**Issue by franticpsyx** [woothemes/woocommerce#7791]
In many product types (core & non-core) a parent/child relationship is implied between a container item and one or more grouped (child) items, such as:

- Variable products + variations
- Grouped products
- Bundles
- Composites
- Mix and match products

In all of these types, the parent / child relationship includes some form of grouping (or inheritance) in relation to:

- Accounting -- static value, content-based value, or combination
- Inventory -- managed at parent level, child level or both
- Shipping -- parent is a physical item with a static weight (or a content-based weight), children are physical items with properties defined at child level, or a combination of both
- Reporting -- ability to report totals/sales at parent level or child level, without affecting order totals
- Payment -- payment gateways should see the parent or the children (with some helpful meta attached), but not both in most cases
- Formatting -- cart, order, e-mail templates

These product types could all benefit from a formal definition and implementation of a product group model in core, possibly including:

An abstract product group class with suitable abstract methods (such as `get_{min/max}_{regular/sale}_price`, `is_priced_per_item`, `is_shipped_per_item`, etc)
Cart methods for container vs contained items, as well as methods for establishing links between them and methods to abstract products from cart items (such as `get_cart_item_price`, `get_cart_item_weight`, `get_cart_item_children`, `has_cart_item_children`, `get_cart_item_container`, `is_cart_item_grouped`, `cart_item_needs_shipping`, etc)
Similar order methods
Possibly amendments to the reporting classes

At the moment, not having a formal parent/child model makes integrations with 3rd party shipping / inventory management providers/systems difficult, because all the above needs to be implemented on a type-and-extension/integration-specific manner. 

The biggest issue is at the order/reporting level, where the lack of a formal parent/child api means that it is difficult to maintain complete accounting, inventory, shipping, reporting and formatting consistency without sacrificing flexibility, and even more difficult for 3rd parties to access meaningful order content when such functionality is provided at extension-level.

It's a huge undertaking, but is there any medium/long term interest for this, or is it too complex / out-of-scope to include in core?

loosely related: #7776

**Comment by mikejolley** [comment]
Definitely an interesting one. I wonder if there is room to standardize these across extensions before rolling into core? Moving the discussion to https://trello.com/c/5fuuDTBg/68-a-formal-parent-child-model-for-cart-and-order-items for voting an discussion since this isn't ready to be assigned to a milestone :)
