### ISSUE TITLE
hook in to wc_trim_zeros

### ISSUE THREAD

**Issue by josh1324** [woothemes/woocommerce#7792]
Shouldn't there be a filter in this function in case someone wants to have is price formatted like this: €20,-

function wc_trim_zeros( $price ) {
	return preg_replace( '/' . preg_quote( wc_get_price_decimal_separator(), '/' ) . '0++$/', '', $price );
}

**Comment by mikejolley** [comment]
wc_trim_zeros has one purpose - trimming end zeros. So having a filter on that doesn't make sense IMO.
