### ISSUE TITLE
Call to undefined method WooCommerce::logger() 

### ISSUE THREAD

**Issue by WevNaves** [woothemes/woocommerce#7794]
I've installed a Brazilian payment method plugin, and after saving the setting for the first time, I've gotten this message:

Fatal error: Call to undefined method WooCommerce::logger() in /home/weverton/public_html/ecogroup/wp-content/plugins/wpwcpagseguro/wpwcpagseguro.php on line 117

Everty time now when I'm acessing the WooCommerce configuration page I get this message.
When I desactivate the plugin, Woocommerce come back to normality.

Could you help me?
tks.

**Comment by claudiosmweb** [comment]
The error is in the plugin you have installed.
