### ISSUE TITLE
woocommerce payment failed page

### ISSUE THREAD

**Issue by raminnorouzi** [woothemes/woocommerce#7797]
Hello,
I'm using a custom payment gateway for woocommerce on my website (http://www.jikaseh.com). It works fine when customer's payment is successful and redirects back to my website with a "Your order has been received" note. But when the customer's payment is failed or rejected due to any reason, the customer is redirected back to the "Cart" page with a note about failed payment on top of the cart. The problem is that if the customer wants to try paying again, he will click on "Proceed to checkout" button in the Cart page; then will click on "Place order" button in checkout page and this will lead to an order with the same order number as the failed order. Since the order number is the same as the failed order number, the payment is not possible on the payment processor's website and shows a message: "The order exists or is expired".
I think this issue has 2 solutions:
1. when customer click on "place order"  button, the failed order must get cancelled and a new order with new order number must be generated.
2. If solution (1) is not possible, then solution (2) would be: change the page which customer is redirected to; after failed payment. the reason is that there is no "cancel order and restore cart" button in the cart page, so when the payment fails and the customer is redirected to Cart page, he has no way to cancel his failed order and trying to pay again will lead to the issue I described in first paragraph.
I really appreciate if anyone can help me and show me how to solve this issue.
Here is part of the code:
						//if(substr_count(get_permalink(get_option('woocommerce_view_order_page_id')),'?page_id=')) $url_pre = '&'; else $url_pre = '?'; 

					} elseif( $response["@attributes"]["primaryRC"] == 34 && $response["@attributes"]["secondaryRC"] == 1014 ) {
						$m = __('Payment failed, please contact your card-issuing bank.', 'themewoocommerce');
						$order->add_order_note( $m );
						$this->comp_woocomerce_mess_error($m);
						wp_clear_scheduled_hook( 'WC_arca_cron', array($order_id) );
						wp_redirect($order->get_cancel_order_url());
						return;

**Comment by mikejolley** [comment]
This would be down to the payment gateway to handle. This won't be a limitation of all gateways; some allow you to retry payment.

Rather than fail payment for a generated order, your gateway will need to either 'cancel' it instead so its not re-used, OR add something unique to your passed order references such as a timestamp.
