### ISSUE TITLE
Products RSS Feed

### ISSUE THREAD

**Issue by dzeriho** [woothemes/woocommerce#7800]
Hello!

When the feed function is called with the URL parameters like these <code>product_cat=cat1,cat2</code> or the <code>product_cat=cat1+cat2</code> in WooCommerce 2.3.7 (and previous versions) in the <code>wc-template-functions.php:114 function wc_products_rss_feed()</code> this notice appears <code>Notice: Trying to get property of non-object</code>. In the function terms are retrieved like this <code>$term = get_term_by('slug', esc_attr( get_query_var('product_cat') ), 'product_cat');</code> Then the <code>get_query_var('product_cat')</code> treats these terms as a single term like <code>cat1,cat2</code> or the <code>cat1+cat2</code>.

Can this be supported?

Thanks!
Nenad

**Comment by mikejolley** [comment]
These feeds are used on term archives, so they are designed to support a single category (you cannot have term archives for multiple-terms).

If you need multiple terms, either build a custom feed, or log the idea on ideas.woothemes.com to judge demand.

Thanks

**Comment by dzeriho** [comment]
Hi,

Ok thanks for the answer! I'm not using this feed in theory, but developing an filtering plugin for the WooCommerce which is using WP queries to filter out results. On archives and shop pages this happens when certain filter is used in the described manner. This might occur more in the future with other developers as these are default Wordpress query arguments. I might try to log on to ides.woothemes.com and see what the response from them will be on the issue.

Thanks again!

Nenad
