### ISSUE TITLE
checkout/review-order.php: issue with CSS classes in coupon row

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#7802]
Hi! 

In checkout/review-order.php:

```php
<?php foreach ( WC()->cart->get_coupons() as $code => $coupon ) : ?>
	<tr class="cart-discount coupon-<?php echo esc_attr( $code ); ?>">
		<th><?php wc_cart_totals_coupon_label( $coupon ); ?></th>
		<td><?php wc_cart_totals_coupon_html( $coupon ); ?></td>
	</tr>
<?php endforeach; ?>
```

The coupon name is used to form extra CSS classes for each row. Something we've hit up against are problems with our more creative coupon names - if for instance we have "You were right" as a coupon code then any rules targetting `.right` will impact and can destroy the formatting.

Would it be possible to "slugify" things to avoid this?

```php
<?php foreach ( WC()->cart->get_coupons() as $code => $coupon ) : ?>
	<tr class="cart-discount coupon-<?php esc_attr_e( sanitize_title( $code ) ); ?>">
		<th><?php wc_cart_totals_coupon_label( $coupon ); ?></th>
		<td><?php wc_cart_totals_coupon_html( $coupon ); ?></td>
	</tr>
<?php endforeach; ?>
```

That way (or with some equivalent code) we'd have, for example, `coupon-you_were_right` rather than `coupon-You were right`.

Thanks for taking a look!

**Comment by barryhughes** [comment]
...realizing `sanitize_title()` will replace spaces with hyphens rather than underscores ... obviously not the right function here ... in principle though this would still be a nice change :-)

**Comment by mikejolley** [comment]
sanitize_title is fine IMO, as long as there are no spaces.

**Comment by om4james** [comment]
hi @mikejolley, I think `sanitize_html_class()` is probably the best function to use here?
