### ISSUE TITLE
I'm having a couple of problems with my product page in WooCommerce

### ISSUE THREAD

**Issue by bkfirvine** [woothemes/woocommerce#7803]
Hello....I'm contacting you regarding a plugin that a coworker of mine bought recently called Fancy Product Designer for WooCommerce. The maker of the plugin (radykal) referred me to you, because he said that my problem is related to WooCommerce. Anyway, my problem is that on the Product Page, the select box I created isn't populated with any of the values that I created for it. Right below that select box is a line that reads "SKU: N/A". In response to this issue, I updated my versions of Wordpress, the theme that I'm using (Minimaze) and WooCommerce. I also tried the solutions on the "Third party / custom / non-WC theme compatibility" page on your website, but those solutions didn't work. Also, I activated Debug Mode so that, when I load the Product Page, it gives an error message that reads: 

"Theme Check 

woocommerce_before_single_product_summary hook was found. 

woocommerce_single_product_summary hook was found. 

woocommerce_before_add_to_cart_button hook was found. 

body_class filter was found. 

If a hook or filter is missing in your theme, you can try fo fix it by yourself. This is a theme issue, because authors of themes should follow the woocommerce codex and should not remove the default woocommerce hooks in the templates files. If you can not fix it by yourself after reading the "Troubleshooting" page, please contact the theme author.
 I (developer of Fancy Product Designer) will not fix these issues for you." 

I'd rather not have to change themes, because (as far as I'm concerned) that would give me a bit more work to do on the website. I'd have to start over with another theme, which would create more work for me....Thanks in advance.

**Comment by roykho** [comment]
Unfortunately this is not a place to get support.  This is for bug reports/fixes only.  From reading your description, it would seem your issue is with your theme.  You would need to contact your theme author about this.

**Comment by bkfirvine** [comment]
Hello, Roy....Thanks for your feedback.  I'll contact the theme author about this issue....Take care.

**Comment by abovethetime** [comment]
Hi bkf irvine. 
I have the same problem. But we view our theme manager. plugin is not said by theme. He can not help message. The problem is that the resolution did not give any response. Can I ask you how you solve this problem? Thank you for your help.

**Comment by bkfirvine** [comment]
Hello....Since I don't know which problem you're referring to, I can't
comment on how I solved that problem.  To be honest, I don't even know if I
did get the problem solved.  Anyway, I hope you're able to find someone
else to help you with this problem....Take care.

**Comment by abovethetime** [comment]
Thanks Bkfirvine. Expect your good news.

**Comment by bkfirvine** [comment]
Hello, again....I was able to find my original post about the problem in
question.  After looking at that post, I realize that I probably had a
programmer that I hired to help me fix (or try to fix) this problem.  In
any case, I don't have the expertise (as of yet) to help you with this
issue....Take care.

**Comment by abovethetime** [comment]
I started now the programmer specialization. :)
Thanks for your concern.

**Comment by bkfirvine** [comment]
No problem!
