### ISSUE TITLE
Allow plugins to tell if anything was changed in wc_save_order_items function

### ISSUE THREAD

**Issue by slobodan** [woothemes/woocommerce#7804]
#6333 introduced a hook - ```woocommerce_saved_order_items``` - that allows plugins to do their thing with saved order items.

However, it doesn't let you detect if there were any changes to order items, and is fired every time you save an order. 

Maybe I'm missing something, but it seems like there's no way to check if anything has been updated. ```$order_id``` is passed as parameter, but by the time hook is fired, the order has already been updated. 

Here's a dirty way of allowing this, by simply passing previous version of order to ```woocommerce_saved_order_items``` hook:

https://github.com/slobodan/woocommerce/commit/82ff3263eb378d77d350bb9d412ab00f257f142e?diff=unified

But ideally, the check would be performed inside the function, so no database writes would be performed if nothing in the order has changed.

Sorry I'm missing something obvious here, but I couldn't find another hook that would allow me to do this.

**Comment by slobodan** [comment]
Looked into this some more, and a hook similar to ```pre_post_update``` would be very handy here.

https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L3377

Could be placed at the top of ```wc_save_order_items``` and accept the same arguments (order id and items). I'd be happy to create pull request if you think this would be useful.

**Comment by mikejolley** [comment]
Yep create a pull request and we'll review it :+1:

**Comment by slobodan** [comment]
Thanks @mikejolley, I'll do that.

**Comment by slobodan** [comment]
Turns out there is a better way to do this, by using ```woocommerce_new_order_item```, ```woocommerce_update_order_item``` and ```woocommerce_delete_order_item``` hooks from ```wc-order-functions.php```.

Found a way to improve functions those hooks are in, so I'll do that instead.
