### ISSUE TITLE
After Upgrading to the Latest Woocommerce, Account Funds returns "Coupon Not Found" on checkout.

### ISSUE THREAD

**Issue by JoseRaffucci** [woothemes/woocommerce#7811]
Hi Guys, 

I've been trying to get help with this issue now for a week.  I submitted a ticket and have not had a response now in 5 days going on 6.  This issue occurred after upgrading WooCommerce for security vulnerabilities and we have been forced to disable Account funds causing us a lot of problems for us and our customers, resulting in refunds of account funds etc...  

I created an additional ticket to see if someone would respond but no one still has updated us.  I have even messaged WooThemes on twitter, no response. This is very critical for our business to get it working.  I have been very disappointed by the lack of responsiveness for a paying customer, we have purchased 7 extensions (where planning on purchasing more) would like to continue to use WooCommerce and its Extensions but if we can't get timely support on issues we may have to start looking elsewhere.

Support Tickets:
 #271805 (Original Waiting for 5 days for a response)
#274722 (Second ticket to see if someone would even respond)

I believe @ChromeOrange was helping us but again no updates or responses.  Please Advise.

**Comment by ChromeOrange** [comment]
Hi @JoseRaffucci 

I have responded to your ticket this morning. This is not a WooCommerce issue and, so far, I have been unable to recreate the issue on your dev site.
