### ISSUE TITLE
"Download Log" feature

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7812]
Can we add a "Download Log" button after each log text area?

In System Status > Logs

**Comment by mikejolley** [comment]
https://trello.com/c/DBPaucz8/67-add-ability-to-download-logs-from-logs-section

**Comment by j-falk** [comment]
Having a easier way to download log files (and system report) would make it much easier to share log files.

And then we wouldn't have to have complicated how to videos like this:
https://docs.krokedil.com/krokedil-general-support-info/prepare-a-support-ticket/#3-logs 😄 

Is there any reasons why this haven't been implemented already? Eg security or UX reasons that needs to be tackled?
