### ISSUE TITLE
Bug in woocommerce.php and affects the translation

### ISSUE THREAD

**Issue by healiny** [woothemes/woocommerce#7814]
I found a bug that affects the translation, in file woocommerce.php
In function - load_plugin_textdomain.

<h2>The original function:</h2>
-------------------------

public function load_plugin_textdomain() {
$locale = apply_filters( 'plugin_locale', get_locale(), 'woocommerce' );

if ( $this->is_request( 'admin' ) ) {
<b>load_textdomain</b>( 'woocommerce', WP_LANG_DIR . '/woocommerce/woocommerce-admin-' . $locale . '.mo' );
<b>load_textdomain</b>( 'woocommerce', WP_LANG_DIR . '/plugins/woocommerce-admin-' . $locale . '.mo' );
}

<b>load_textdomain</b>( 'woocommerce', WP_LANG_DIR . '/woocommerce/woocommerce-' . $locale . '.mo' );
load_plugin_textdomain( 'woocommerce', false, plugin_basename( dirname( __FILE__ ) ) . "/i18n/languages" );
}

------------------------

I repalced the "load_textdomain" with "load_plugin_textdomain"
<h2>Looks like this:</h2>

-------------------------
if ( $this->is_request( 'admin' ) ) {
<b>load_plugin_textdomain</b>( 'woocommerce', WP_LANG_DIR . '/woocommerce/woocommerce-admin-' . $locale . '.mo' );
<b>load_plugin_textdomain</b>( 'woocommerce', WP_LANG_DIR . '/plugins/woocommerce-admin-' . $locale . '.mo' );
}

<b>load_plugin_textdomain</b>( 'woocommerce', WP_LANG_DIR . '/woocommerce/woocommerce-' . $locale . '.mo' );
<p>load_plugin_textdomain( 'woocommerce', false, plugin_basename( dirname( __FILE__ ) ) . "/i18n/languages" );</p>
------------------------

Without change there is a problem of translation .mo files.

**Comment by SiR-DanieL** [comment]
This is not a bug. We use `load_textdomain` to load languages files from other locations rather than the default plugin folder in order to support languages overrides for updates.

This way if you customize your languages files and you put them in wp-content/languages/ they won't be overridden when updating WooCommerce.

There's a fallback to `load_plugin_textdomain` if those custom files do not exist.

**Comment by healiny** [comment]
I realized where I went wrong,
It arranged, thanks
