### ISSUE TITLE
Bug "product" links

### ISSUE THREAD

**Issue by healiny** [woothemes/woocommerce#7815]
After I fixed a bug that belongs to - load_plugin_textdomain <a href="https://github.com/woothemes/woocommerce/issues/7814" target="_blank">(click here)</a>

<h3>I have a problem link to product pages:</h3>
----------------------
<p>http://www.my-site.com/<b>product</b>/my-product.</p>
Instead of relating to the "product", is linked to translate the word.
<p>"product" ==> translate "product" ==> error link</p>
------------------------

<h3>I fixed it temporarily, but need a permanent solution to it.</h3>

In Wordpress --> Srttings --> Permalink

in the page -
In "Product permalink base" coose "Custom Base" with "/product"

**Comment by claudiosmweb** [comment]
You changed the translation, then needed to flush the rewrite rules.

**Comment by healiny** [comment]
I use a plugin, I try do it again with poedit.

**Comment by healiny** [comment]
It arranged, thanks
