### ISSUE TITLE
Add Product in Edit Order issue

### ISSUE THREAD

**Issue by LindsayHeydon** [woothemes/woocommerce#7816]
Noticed that when in Edit Order and clicking Add Product that the Size variation value is not picked up? As all other variations are, so just wondered if an issue?

Selections are perfectly fine in the front end.

See image - all other variations 
![variations - edit order](https://cloud.githubusercontent.com/assets/10940158/6824413/f73dbd38-d2e9-11e4-83da-8b4c1c3eab4e.jpg)
are found...

**Comment by mikejolley** [comment]
Does the variation you're selecting have a value set for the size, or is it set to 'any'.

**Comment by LindsayHeydon** [comment]
Ahhh, yes. Any Size. Apologies - I can see why now. Many thanks.
