### ISSUE TITLE
Allow different orders in Customer List report

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7817]
In the report Customer List there's no way to reorder the table, in example by number of orders.

**Comment by mikejolley** [comment]
Should be part of https://trello.com/c/JSjsyRTs/66-mini-customer-relationship-management-crm

**Comment by SiR-DanieL** [comment]
but we already have the Customer List report in WooCommerce > Reports. Should we add the sort feature in a new extension also for reports?

**Comment by mikejolley** [comment]
CRM will likely replace this.

**Comment by aneeshjajodia** [comment]
@mikejolley - Are there any plans on getting an integrated CRM into WC?

**Comment by claudiosmweb** [comment]
@aneeshjajodia no need, you can integrate any CRM with WooCommerce.
