### ISSUE TITLE
Add "Continue shopping" button to add-to-cart message

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7819]
This is a follow-up issue from the pull request at #7658. The pull request was declined as its only working for small shop with few articles. But it should also work for bigger shops where articles might be added from archive pages too.

Please the @jameskoster 's comments in #7658

**Comment by jameskoster** [comment]
Discussed this in our weekly meeting and we decided not to add this. "Continue shopping" is open to interpretation and this functionality would involve additional load that we feel isn't worth it.

Best left to a customisation for now.

**Comment by jnachtigall** [comment]
@jameskoster ok, thanks the explanation and for discussing this (albeit I don't like the verdict ;-) Could you give me a pointer on how I would most easily and without too many possible (upgrading) side effects add such a customization using my child theme? Am I right that using the `wc_add_to_cart_message` filter would be best option?

**Comment by jameskoster** [comment]
Yep, that would be the best option. If you're happy just linking back to the shop it's easy to do. Please post on the wordpress.org forums, github is not the place for this kind of thing. Thanks.
