### ISSUE TITLE
Big changes in REST-API without changing API version number

### ISSUE THREAD

**Issue by krautnerds** [woothemes/woocommerce#7824]
Hi everybody,

we are really struggling with the latest major Woocommerce update because of so many changes in the REST API 2.0 - Is it possible to introduce new version numbers for every major release of woocommerce? e.g. REST API 2.3 for Woocommerce 2.3.x so that there is a stable interface to communicate with over the release of new woocommerce versions?

Thanks!
krautnerds

**Comment by maxrice** [comment]
@krautnerds which specific changes are causing a conflict for you? There we some endpoint additions and minor fixes but I didn't think there was any large change between the v2 API in WC 2.2-2.3

**Comment by claudiosmweb** [comment]
Closed in favor to #7771
