### ISSUE TITLE
Variation attributes not saving

### ISSUE THREAD

**Issue by jeremyroberts0** [woothemes/woocommerce#7825]
The attributes of a variation are not saving when creating a product with the JSON API.

I've tested using the sample API call for creating variable products from the WooCommerce API Documentation here:
http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product

The response to the API call is missing the attributes in the variations that were in the original call and logging into the WooCommerce instance shows no attributes selected for the variations of the product.

Here's the request from the documentation (I've removed the images to avoid download errors).  You'll need to enter your domain and credentials to test:
```bash
curl -X POST https://example.com/wc-api/v2/products \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "product": {
    "title": "Ship Your Idea",
    "type": "variable",
    "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "categories": [
      "Clothing",
      "T-shirts"
    ],
    "images": [ ],
    "attributes": [
      {
        "name": "Color",
        "slug": "color",
        "position": "0",
        "visible": false,
        "variation": true,
        "options": [
          "Black",
          "Green"
        ]
      }
    ],
    "default_attributes": [
      {
        "name": "Color",
        "slug": "color",
        "option": "Black"
      }
    ],
    "variations": [
      {
        "regular_price": "19.99",
        "image": [ ],
        "attributes": [
          {
            "name": "Color",
            "slug": "color",
            "option": "black"
          }
        ]
      },
      {
        "regular_price": "19.99",
        "image": [ ]
      }
    ]
  }
}'
```

**Comment by chrille112** [comment]
I'm able to reproduce this problem. It is happening because you haven't created the "black" attribute item. You need to do that manually under products => attributes. The API isn't capable of creating them.

**Comment by jeremyroberts0** [comment]
Thanks!  This worked great, I just needed to create the Color attribute and set it's type to Text for this to work for me, adding "black" as an attribute item was not necessary.  It'd be great if this was called out in the documentation for creating variable products.

**Comment by claudiosmweb** [comment]
This works, but you need to have registered the attributes in your WooCommerce before.

**Comment by claudiosmweb** [comment]
Docs updated in https://github.com/woothemes/woocommerce-rest-api-docs/commit/558ea00fe98b29a4d5dc17bce7994ce1ed118650

**Comment by Zmash** [comment]
Is there really no way to register any attribute via rest api (Plugin or something)? I would like to create and update my products automatically from my software. To set anything manually is not an option for me :-(

**Comment by claudiosmweb** [comment]
Ready for WooCommerce 2.4:
https://github.com/woothemes/woocommerce/pull/8053

**Comment by robertobandini** [comment]
Hi, I had the same problem and the same need of Zmash: insert variable product with their attributes via API without do anything manually.
First I tried to do the same in the docs example, without read about need to set the attributes before.
(I think you have to write it maybe under the json example directly, so will be more clear)
Anyway, I'd set name, slug and option for every attribute of any variation, and I saw that no attributes results... so I check every row of code of the interested part of API and I've see that if slug was present no taxonomy was found, but if you don't set the slug, so attribute is searched by "name" (sanitized), then all works in right way... so if I enter via API a variable product with variation and their attributes now I see all ok... product, attributes, variation with attribute selected...
I just tried this right now so... it seems to work... what do you think?
(Sorry for my English)
