### ISSUE TITLE
Maxthon browser font issue

### ISSUE THREAD

**Issue by shawaj** [woothemes/woocommerce#7826]
Using the mystile theme, woocommerce cart, checkout, prices etc do not display on the Maxthon browser.

This happens even on your demo version of mystile.

Appears to be an issue with the open sans font in use.

Is there a way to fix this?

Thanks

**Comment by mikejolley** [comment]
I've moved this to the correct repo. Only WC core issues should be reported here.

**Comment by jameskoster** [comment]
@shawaj does this happen for you on any site that uses Open Sans?
