### ISSUE TITLE
Mobile Keyboards

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/woocommerce#7827]
After reading articles from Lema and Zurb, I decide I wanted to make the correct keyboards come up on tablets and cell phones.  Bring up a checkout page on your table or phone. Now tap in the email field.  This code <input type="email"> brings up a specific keyboard.  Now go to the name field.  This code <input type="text"> brings up a different keyboard. Now check out this image
![keyboard-inputs](https://cloud.githubusercontent.com/assets/6208757/6855246/8746eb40-d3c4-11e4-8b9d-4809cd35e94a.png)

The bottom right (D) is the correct keyboard that I had to force open, but needs to come up _*by default*_ for both the Credit Card & CVC field.
Here's what I've tried:
1. `<input type="number">`
2. `<input type="number" pattern="[0-9]*">`
3. `<input type="text" pattern="[0-9]*">`
4. `<input type="number" pattern="[0-9]* pick_20_more_variations">`
5. I even went out on a limb and did `<input type="tel">`

### Alas! The damn thing will not change!

So... How in the dickens do 'other folks' manage to pop up just the numeric keypad to enter digits?

**Comment by maxrice** [comment]
seems like this is challenging to get working consistently, see http://stackoverflow.com/questions/3372380/how-to-force-keyboard-with-numbers-in-mobile-website-in-android

**Comment by BurlesonBrad** [comment]
pfft.  hell yeah it's a challenge. ;-)  i should post every stinkin' article I've got open. HA! 
ok, enough of the 'challenge' part. 

## Let's figure out a solution!

**Comment by BurlesonBrad** [comment]
@maxrice , I've also tried [this article by Brad Frost](http://bradfrost.com/blog/mobile/better-numerical-inputs-for-mobile-forms/) to no avail.  Then there's [this *humorous* article as well](http://seesparkbox.com/foundry/cracking_the_code_for_a_numeric_keyboard) where this dude tried everything under the sun ~ a bit like I'm _still_ doing. :+1: 

...I tried messing around with this as well, and I got nowhere
input type="number" inputmode=”numeric” pattern="[0-9]*"

Look at what Amazon Mobile brings up.  This is *EXACTLY* how it's supposed to be done!
![amazon-ck-out-keyboards](https://cloud.githubusercontent.com/assets/6208757/6857289/b19d1432-d3d3-11e4-9fab-04b0bce41113.png)

## If Amazon.com can make it come up, then we can too!

...uh..ok, now...how?

**Comment by majemedia** [comment]
Looks like Amazon is using `type='tel'` without any pattern matching.

**Comment by BurlesonBrad** [comment]
![amazon-ck-out-discovered](https://cloud.githubusercontent.com/assets/6208757/6857512/38197da6-d3d5-11e4-943e-6ff5d924213d.png)

# *EXACTAMUNDO*

**Comment by BurlesonBrad** [comment]
I've emulated this a few times but none of these iPhone emulators are actually emulating / opening the keyboards.   If anyone wouldn't mind, check out https://networksharedmedia.com, throw the DL into your cart so that you'll get to the checkout page, and then tell me what it does on an iPhone, iPad (sorry, all I've got are Androids)

Wait, what am I missing here?  Shouldn't this be showing "tel"?  Something makes me think / wonder if I'm even in the right file to begin with.
![text_vs_tel](https://cloud.githubusercontent.com/assets/6208757/6858053/8a6ed570-d3d9-11e4-9fb4-2490a1b6ed3f.png)

**Comment by mikejolley** [comment]
There is no way I'm going to abuse input types to get a keyboard to popup. "tel" is clearly for telephone numbers, not credit card data, and we have no idea what implications this could have in the future when browsers catch on and implement correct handling for html5 input types :) 

Number should equal numeric keyboard - IMO we should let the browser developers catch up before adding dirty hacks.

**Comment by maxrice** [comment]
Stripe seems to sort of advocate for using the `tel` input type, at least in their jQuery.payment library: https://github.com/stripe/jquery.payment#mobile-recommendations

even with that, it seems like it's still very inconsistent across mobile browsers so I'm not sure it really buys you much.

**Comment by BFTrick** [comment]
I'm all for the correct keyboard popping up but I don't think it's worth going against standards to do so. The phone's browser controls which keyboard pops up when a user clients in an input field. The only thing we can do is give the phone the input type. If we hax0r this there could definitely be issues down the road.

Amazon.com can instantly change their checkout. We'd have to put out a release which some users would ignore. Add on top of that theme's which override our templates and never update it. I don't think this is something we can responsibly do. 

Two things you can do here:

1. You can report this to your mobile browser and suggest they change it.
2. You can use a [template override](http://docs.woothemes.com/document/template-structure/). Although it's obviously up to you to maintain it once you put it in a child theme. You may have to change it back someday.

I vote we close this.

**Comment by mikejolley** [comment]
Also to add to the point made by @BFTrick, if one day browsers start validating phone inputs, thats instabreak for credit card numbers.

**Comment by BurlesonBrad** [comment]
Grab your phone or tablet and bring this up, then go to checkout and watch.  Give it a whirl.
https://dev.networksharedmedia.com/product/a-can-of-jolly/
### Pay attention to the zip code field. ###

Ok, now what happens to the *checkout process* when all email fields are changed to `type="email"` all number fields are changed to `type="number"` (or `type="tel"` ~still testing the validation)?
I get that this will throw a loop to some of the folks who are into code.  *BUT* you've got to focus on maximizing sales via every aspect ~ including the checkout process.  Sorry if it throws some of the _coding folks_ for a loop, but
* It does work
* It does help
* And, (unless someone can find a contradicting incident) it *IS* validating!
:+1:

**Comment by claudiosmweb** [comment]
@BurlesonBrad Postcode/zip in UK can accepts letters too and this number validating it wrong, you just stop customers to buy in your store!
See how easy it is to break something for some customers?
http://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom

**Comment by barrykooij** [comment]
Dutch ZIP always has 4 numbers and 2 letters.

**Comment by mikejolley** [comment]
@BurlesonBrad You're missing my point.

Take the email field as an example. Browsers validate this for you:

![2015-04-01 at 14 48 2x](https://cloud.githubusercontent.com/assets/90977/6942269/4644fdc6-d87e-11e4-9c03-caf92424ea54.png)

Now lets assume we do it your way and add 'tel' to the credit card number field. Then a browser update for chrome introduces phone number validation in the same way as the email field does email validation.

What would the result be? Thats right! No sales because users cannot input their 16 digits.

Abusing HTML5 input types *will* have implications in the future.

**Comment by BurlesonBrad** [comment]
Of course it's not gonna work until you put in an '@' sign.  Isn't that Exactly what it's supposed to do?

Look, you guys can code circles around me, and I'm not quite understanding what I'm missing.
So, you're saying that in a few years, a browser update wold validate a phone number? ...and that's justification for not using `type="number"`?

So..... what's the *universal* phone-number-hypothetical-update that a browser would update to?
`123-456-7890` would be the validation for a US number, right?
Canada is different, Mexico is different, Singapore is unique, _ok, the examples can go on forever_ So, how exactly would a browser validate a phone number on a world wide level?  It seems like an impossible hypothetical.
So.... tell me more about this hypothetical-update-to-browsers, that could validate phone numbers for only one format?

**Comment by BurlesonBrad** [comment]
Tell ya what.  Change the input types to `"number"` (**_not_** `tel`), run some tests, and see if it does NOT work.  _**Then**_ let's throw some some hypothetical around.

Does it work on all phones and tablets?
~and~ 
Does it the order still go through?

**Comment by mikejolley** [comment]
Look above - https://github.com/woothemes/woocommerce/issues/7827#issuecomment-86724080 it was suggested that "TEL" would be suitable for CC fields. But its not for the points raised.

Numeric is also not really ideal for CC fields - users may want to input dashes and spaces for example (our CC script formats the numbers, but the user should still be able to input a number however they want). I'm also fairly certain numeric inputs strip prepending zeros. And the increment controls on a number field are also not required.

This is probably the closest thing we're going to consider adding: http://www.wufoo.com/html5/attributes/23-inputmode.html

**Comment by mikejolley** [comment]
> numeric for numeric input that isn't a number, like zip codes, credit card numbers, when you want numeric values, but don't want the GUI of a number spinner,

**Comment by claudiosmweb** [comment]
@BurlesonBrad Here you can learn a little of HTML5:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-inputmode

**Comment by BurlesonBrad** [comment]
see, that's how genius I am. I accidentally closed it.
HA!

**Comment by BFTrick** [comment]
Good discussion guys. Not much we can do right now. Close?

**Comment by BurlesonBrad** [comment]
Thanks @claudiosmweb , I've read a lot, and that's, yet, another great article that, I think, sheds a bit more light as to why amazon.com is using 'tel' and not 'number'.
![no-other-synatx](https://cloud.githubusercontent.com/assets/6208757/6942941/7c86ab06-d850-11e4-98c9-7d9d79546e8e.png)

and a bit further down that same page @claudiosmweb it, again, reinforces the use of "number".  Yet this time, it specifically points out credit cards
![use-number](https://cloud.githubusercontent.com/assets/6208757/6943030/02a83ec0-d851-11e4-9865-bd778b1a62e6.png)

I don't really want to argue it.  I would like to _understand_ it. I just figured git was the place to tell 'ya about a suggestion.

**Comment by claudiosmweb** [comment]
@BurlesonBrad Tel is not for credit card numbers, nowhere is saying that should be used for credit card, just read and interpret the scope.

I can't find any reference in the W3C saying is to use `tel` for credit card numbers:
http://www.w3.org/TR/html-markup/input.tel.html

> For actual number, prefer using <input type="number">

Good, because it really is not the case :)

Read that @mikejolley said:

>Numeric is also not really ideal for CC fields - users may want to input dashes and spaces for example (our CC script formats the numbers, but the user should still be able to input a number however they want). I'm also fairly certain numeric inputs strip prepending zeros. And the increment controls on a number field are also not required.

And read this:
>e.g. credit card numbers.

I fully support this:
>This is probably the closest thing we're going to consider adding: http://www.wufoo.com/html5/attributes/23-inputmode.html

**Comment by BurlesonBrad** [comment]
right, so that we all agree, and are all on the same page:
the correct `input type` _**should be**_ 
#### number
right?

**Comment by claudiosmweb** [comment]
@BurlesonBrad please test it http://www.wufoo.com/html5/attributes/23-inputmode.html

**Comment by jameskoster** [comment]
`number` is not correct for credit cards. A credit card number is not actually a 'number', IE you would never type it like 4,242,424,242,424,242.

`tel`, while not semantically correct is pretty safe. Safe enough for Amazon and Stripe anyway. The only validation is line breaks, the same as `text`.

**Comment by claudiosmweb** [comment]
@jameskoster Yeah, I agree.
But Credit Card is not a `tel` yet and we just need "numeric mobile keyboards".
For "numeric mobile keyboards" we can use `<input type="text" inputmode="numeric" ...`

**Comment by jameskoster** [comment]
I agree @claudiosmweb.

**Comment by BurlesonBrad** [comment]
@claudiosmweb here 'ya go:

![claud](https://cloud.githubusercontent.com/assets/6208757/6944018/3a043260-d857-11e4-9412-ccbef4973ae4.png)

So, `numeric` brings up the typical `text` keyboard.

I've got a question for all you much-smarter-than-me folk.  I'm just a simpleton from smallville; I don't do tweeder too often, and I don't even do the git thing too often either.  But here's my point / question
Is anyone actually testing these different types to see which one's do and do not work?
I have! I mean this in the most honest way.  I have tested 'em! All the way through to completing the order!!  So.. as various folks comment, are y'all commenting out of hypothetical theory, or are you commenting  after changing the type and actually running the various types through the 'ordering process'?

**Comment by BurlesonBrad** [comment]
I wanted to also show ya what happens when the zip field is changed to:
```php
// Change field type to number woocommerce checkout

function add_jscript() {
echo "<script>document.getElementById('billing_postcode').type = 'number';</script>";
}

add_action( 'woocommerce_after_checkout_form', 'add_jscript');`
```
#### From my phone:
![screenshot_2015-04-01-10-18-30](https://cloud.githubusercontent.com/assets/6208757/6944449/5dbeffee-d859-11e4-8852-07a825b3a02a.png)
#### And my tablet:
![screenshot_2015-04-01-10-25-49](https://cloud.githubusercontent.com/assets/6208757/6944458/69a16bb2-d859-11e4-83b4-1bee6ec3fde0.png)
#### And the order that went through:
![goesthrough](https://cloud.githubusercontent.com/assets/6208757/6944592/17dd8e2c-d85a-11e4-8600-109149cd7d09.png)

**Comment by mikejolley** [comment]
It would go through; you're US based and US ZIP codes are numbers. What about the rest of the world :p

**Comment by BurlesonBrad** [comment]
uh... ok
Good point. 
So, let's ditch the **main point** via the _zip code_ field (Canada uses numbers, eh!?!?)

### And let's put it on all the other appropriate fields.
Forget about this one for a second
![2015-04-01 15 52 47](https://cloud.githubusercontent.com/assets/6208757/6945383/fd0202e0-d85e-11e4-9263-beb1b674e336.png)
#### Look at how the keyboard changes when `input type="email"`
![2015-04-01 15 53 13](https://cloud.githubusercontent.com/assets/6208757/6945385/fd0404fa-d85e-11e4-96e6-c0ada5abe8cb.png)
#### Now, let's go for the Telephone field with `input type="tel"`
![2015-04-01 15 53 51](https://cloud.githubusercontent.com/assets/6208757/6945384/fd03f4e2-d85e-11e4-8bdf-9e3dcdfd535c.png)

Just like before, it validates, the order goes through, and it works fine.

**Comment by jameskoster** [comment]
I already updated the email inputs. We can update the phone inputs to the `tel` type.

**Comment by BurlesonBrad** [comment]
James, you are a sexy beast, hot mess, and I want to bear your children.

It's the commitment to ALL the little details that take an average e-commerce site to a bad ass WooCommerce site!
