### ISSUE TITLE
Variable product variations disappeared (price, sku, etc)

### ISSUE THREAD

**Issue by insightint** [woothemes/woocommerce#7828]
I have been working on a website that sells flags and imported hundreds of products manually with SKUs, different sizes, materials, and prices. For some reason on a bunch of them with multiple sizes (i.e. 3x5, 4x6, 5x8), only 5x8 is left when someone navigates to say, Canada. When they try to add the only size option to their cart, they get "Sorry, this product is unavailable. Please choose a different combination."

If I edit the product, I see empty variation boxes that have lost their attribute (size i.e. 4x6), price and SKU. The 5x8 box still has its information but doesn't work on the front end (the error I mentioned). I tried adding pricing information back into one of the variations that was empty and it comes up correctly on the front end for purchase but I am concerned this will happen again and I will lose everything. 

Is there any way to recover all of the prices that were lost or a way to bulk add them back? The prices for each item size is not always the same if that changes the method. Also is there a way to back up products so I could quickly re-add them if something does occur?

**Comment by mikejolley** [comment]
If the data was lost I don't think you'll get it back. How it was lost, I would guess either:

1. A borked import
2. http://docs.woothemes.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/
3. A plugin

I would recommend you monitor products whenever you update them and keep an eye on extensions. Also, remember that if you remove or rename an attribute globally, it may cause products using that attribute to 'lose' it.
