### ISSUE TITLE
Onboarding / Setup Wizard

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#7829]
Final items:
- [x] Add links for learn more items
- [x] Add nonces to forms

Items:

- [x] Setup paypal
- [x] Sidekick
- [x] Main CTA on final step
- [x] Install pages
- [x] Settup main options
- [x] Geolocate user installing
- [x] Disabled via filter
- [x] Best practice links on last step
- [x] Product page pointers
- [x] tracking opt in
- [x] Trigger wizard on install (new)
- [x] Remove no longer required notices
- [x] Load settings from DB in case of re-run
- [x] Install test product

List of settings that can be set via wizard:

- [x] Base Location
- <del>[ ] Selling locations</del>
- [x] Currency - select other options based on the chosen currency
- <del>[ ] Enable stock management?</del>
- [x] Enable tax?
- [x] Inc or ex tax prices?
- [x] Allow guests / registration?

We will need a DB of locale settings e.g. GB country = GBP by default and has X taxes. These will set:

- [x] Currency formatting settings
- [x] Weight and length units [?]
- [x] Inc or ex tax prices -> prices display in shop the same by default

**Comment by mikejolley** [comment]
List of settings that can be set via wizard:

- [ ] Base Location
- [ ] Selling locations
- [ ] Default Customer Address - Enable geolocation?
- [ ] Currency - select other options based on the chosen currency
- [ ] Enable stock management?
- [ ] Enable tax?
- [ ] Inc or ex tax prices?
- [ ] Allow guests / registration?

We will need a DB of locale settings e.g. GB country = GBP by default and has X taxes. These will set:

- [ ] Currency formatting settings
- [ ] Weight and length units [?]
- [ ] Inc or ex tax prices -> prices display in shop the same by default

**Comment by mikejolley** [comment]
Branch for development is here https://github.com/woothemes/woocommerce/tree/onboarding

**Comment by BFTrick** [comment]
Hey @mikejolley - just letting you know that @avivapinchas and myself are thinking about letting users opt-in to a drip campaign all about using WooCommerce. Should focus on core and only touch on extensions at the end.

Shouldn't be hard to add an extra step right? Would just be a link to an opt-in page on Woo.com. We wouldn't have to actually do the opt-in within WooCommerce.

**Comment by avivapinchas** [comment]
Hey @BFTrick & @mikejolley - Just checking in on this. Any update? Can we do it?

**Comment by BFTrick** [comment]
@mikejolley I see you added setup Paypal. That will be it's own step right? Would be hard to cram into an existing step.

**Comment by BFTrick** [comment]
Some more feedback:

The page creation step is one of the first things we ask them to do. All that we really need to do is have they press `yes please install pages

**Comment by mikejolley** [comment]
@BFTrick Added those changes if you want to retry. Wanted to keep payment step as light as possible - let me know if you feel we should add more BACS options

**Comment by BFTrick** [comment]
Love the way you did payments @mikejolley ! Super sleek. :)

On the final page. The `Return to the WordPress Dashboard` link is basically a back button. We should put it beneath the white pane (with the rest of the links) and make it a grey color. Basically indicate that it's the action we don't want them to take but should still be there.

![woocommerce_ _setup_wizard](https://cloud.githubusercontent.com/assets/1065372/8047123/a168cb5a-0dfe-11e5-8a0d-cd734606d9b7.png)

We have two links to walkthroughs. The video series and the sidekick series. At this point we should recommend one option. Most of our users won't know how to make that decision. I think we should recommend sidekick tutorials and if people are begging for more walk throughs we can add the video walkthroughs back in.

Having an email course for our customers is one of the best things we can do for their longterm success. Any thoughts on how we can make the `Take a course about WooCommerce` stand out? Right now we have two call to actions. The tracking opt-in and the button to create a new product. Any thoughts on good ways to add this? We're quickly approaching the point where we're trying to make everything stand out and then nothing stands out. :(

Perhaps another box that fades away when you optin? Maybe for the sake of ease we use the admin email address and sign them up rather than direct them to a signup page where they get lost and never come back.

Ex.

> **Make the most of WooCommerce**
If you’d like more advice as you get started with selling, sign up to get our best tips for building your WooCommerce store delivered to your inbox for the next X days. Sign me up

Thoughts?

**Comment by mikejolley** [comment]
> We're quickly approaching the point where we're trying to make everything stand out and then nothing stands out.

Thats why I don't want the others to stand out :p 

Tracker is prominent until dismissed. Create first product is the 'best' option they can take. Those are the only ones I feel should be given special treatment. Read or ignore the others; does not matter.

**Comment by mikejolley** [comment]
@BFTrick @jobthomas gave feedback on those 4 links.

>>>
bobWP did some research and found that almost all people fall in one of the three categories for learning: Reading about it, watching a vid, or getting 1on1 training, will be nice if we indeed offer all of those (sidekick is kinda 1on1 training)

will also discuss with ryan if we can have a page with only the WC101 vids on

a fourth option which would suit nicely is
```Follow a course about WooCommerce```(busy making a page similar to hosting solutions with educational partners, should be up within the next few weeks)
>>>

I kinda want to promote our own videos, but Sidekick is also necessary ...

**Comment by jobthomas** [comment]
So the idea at the moment would be to have one "Learn More" button, with a short text added to this ...

Draft proposal:

```Your store is ready, but there is a lot more to learn. Read through our guides, watch the video tutorials, follow the [SIDEKICK walkthroughs](insertURL) or follow a course by one of our partners.```

Button text: `Learn More`

**Comment by BFTrick** [comment]
Hey @mikejolley just wanted to confirm what @jobthomas said. I chatted to @jobthomas @avivapinchas & @garymurray and we want to have a short paragraph 2-4 sentences describing what people can learn more about and then go to a page on Woo.com. This way we can change things up on Woo.com any time we want without having to ship more code.

So remove all the existing links. Add that short paragraph + button to Woo.com.

**Comment by jobthomas** [comment]
@mikejolley @BFTrick would be nice to have the input of @garymurray on the copy - I already have one edit:

> Your store is ready, but there is a lot more to learn. Read through our guides, watch the video tutorials, follow the SIDEKICK walkthroughs or *take* a course by one of our partners.

(otherwise twice "follow" too close to each other)

**Comment by mikejolley** [comment]
@jobthomas @BFTrick I think a list is better than paragraph personally. The wizard is fairly text heavy and a p on the last step will probably go ignored. Also, this was modelled after the WordPress next steps widget on the admin dashboard after install, which the user will recognise as its a similar pattern.

**Comment by BFTrick** [comment]
@mikejolley after discussion with some accountants they recommended that we limit US taxes to just the state that your store is based in. So if my store is based in Colorado then load those taxes. Don't bother loading Texas taxes.

If a store has nexus in both CO and TX then they'll have to add the TX rates manually. I think most stores will only have nexus in one state so this way is the fastest for the most number of stores.

**Comment by jobthomas** [comment]
Just to make sure it's documented outside of email. Here are the URLs for the list of suggested resources:

* http://docs.woothemes.com/documentation/plugins/woocommerce/getting-started/?utm_source=WooCommerce&utm_medium=Wizard&utm_content=Docs&utm_campaign=Onboarding
* http://docs.woothemes.com/document/woocommerce-101-video-series/?utm_source=WooCommerce&utm_medium=Wizard&utm_content=Videos&utm_campaign=Onboarding
* http://sidekick.pro/woocommerce/?utm_source=WooCommerce&utm_medium=Wizard&utm_content=Sidekick&utm_campaign=Onboarding
* http://www.woothemes.com/educational-partners/?utm_source=WooCommerce&utm_medium=Wizard&utm_content=Partners&utm_campaign=Onboarding

**Comment by BFTrick** [comment]
Hey @jobthomas ,

We are only going to have 4 links on the page. We shouldn't add another link to education partners.

I don't think we should link directly to [sidekick.pro](http://sidekick.pro/woocommerce/?utm_source=WooCommerce&utm_medium=Wizard&utm_content=Sidekick&utm_campaign=Onboarding). It makes more sense to link to woothemes.com and redirect to sidekick in case we ever need to change the link. Is that something you can help with @kloon ?

**Comment by jobthomas** [comment]
@BFTrick 

* Sounds good on redirect from SIDEKICK (that way we also have more control over the URL)
* Can the partners be mentioned in the help tab or is that not necessary?

**Comment by BFTrick** [comment]
> Can the partners be mentioned in the help tab or is that not necessary?

Let's keep it lean for right now. We can get people's reactions after launch and see if we need more resources.

**Comment by kloon** [comment]
Yep, I can add a redirect for you. Just give me the url you want to use and where you want to redirect to and I'll get it set up.

**Comment by BFTrick** [comment]
@kloon how about woothemes.com/sidekick ? And then redirect to [here](http://sidekick.pro/woocommerce/?utm_source=WooCommerce&utm_medium=Wizard&utm_content=Sidekick&utm_campaign=Onboarding)?

**Comment by kloon** [comment]
Okay done, link to http://www.woothemes.com/sidekick/

**Comment by jobthomas** [comment]
@kloon @BFTrick just a check: should the UTM tracking not be on the woothemes.com/sidekick instead of on the sidekick.pro URL?

**Comment by BFTrick** [comment]
I don't think the UTM tags will do anything for that link. Aren't they mostly used for Google Analytics? I don't believe GA will even see the hit because the page will be redirected immediately (unless we have some sort of fancy GA setup).

**Comment by kloon** [comment]
Yea as @BFTrick says, it is a redirect so GA wont even be triggered here, if we want to do tracking on this we should perhaps look into a landing page then instead that links to the sidekick pages.

That being said, the UTM links will be passed to sidekick so they can provide us with stats if we ask them?

**Comment by BFTrick** [comment]
I think it's fine for now. This is the only place that's linking to that url. For right now we don't need any fancy tracking. :shipit: and then we can modify down the road.

**Comment by jobthomas** [comment]
@kloon Yeah, I'm very sure that sidekick will be okay with providing those stats to us. I'll share this with them as well. At the moment there's a few other things we want to do first instead of the landing page. We might in the future make it ourselves.

@BFTrick we do want some good tracking to find out if we should continue with Sidekick. So it doesn't need to be fancy, but I'd like to see some stats. :smiley:

**Comment by BFTrick** [comment]
@kloon one more link. Just talked to @avivapinchas about the email link which will link to a MailChimp or GetDrip sign up form. TBD. Can we setup another redirect so we can change the url later without having to change the code?

How about woothemes.com/woocommerce-onboarding-email/ ? Destination url TBD.

**Comment by mikejolley** [comment]
@BFTrick @kloon I'll add http://www.woothemes.com/woocommerce-onboarding-email/ to the page - please use that to redirect :)

**Comment by mikejolley** [comment]
Merged :shipit:

**Comment by roykho** [comment]
Well done! :+1:

**Comment by shivapoudel** [comment]
+1

**Comment by jobthomas** [comment]
![Divide and Conquer](http://memecrunch.com/meme/4MM04/divide-and-conquer/image.jpg)

**Comment by BFTrick** [comment]
Ran the wizard after a brand new install (with debug mode on) and got this error which prevented page 2 of the wizard from running. :(

> Warning: Cannot modify header information - headers already sent by (output started at /woocommerce/wp-content/plugins/woocommerce/includes/wc-template-functions.php:2) in /woocommerce/wp-includes/pluggable.php on line 1207

**Comment by gedex** [comment]
@BFTrick I'm not able to reproduce the issue on fresh install with `WP_DEBUG` and `WP_DEBUG_DISPLAY` set to `true`. Any additional info to reproduce the issue?

**Comment by claudiosmweb** [comment]
I also could not reproduce this error...

**Comment by allendav** [comment]
I also could not reproduce the error.  Tested with WP_DEBUG true, using the WooCommerce Beta Tester plugin to load Version 2.4.0-beta-3 on a clean/fresh subdirectory install of WordPress 4.2.2 running Twenty Fifteen theme on Bluehost.

**Comment by claudiosmweb** [comment]
Maybe it was that blank line that @BFTrick removed.

**Comment by BFTrick** [comment]
Yeah removing the blank line before any php code (so it was just a blank line of HTML output to the browser) produced that error. Weird that you guys couldn't reproduce it.

**Comment by avivapinchas** [comment]
@BFTrick @kloon Have the URL for that redirect: http://www.woothemes.com/woocommerce-onboarding-email/ should go to https://www.getdrip.com/forms/3553204/submissions/new

**Comment by BFTrick** [comment]
Hey @avivapinchas - thanks for that. Since this doesn't relate to WooCommerce itself let's keep this out of GitHub. In the future I'd just ping @kloon directly for this. :)
