### ISSUE TITLE
Wrong position of countries list when user is logged in

### ISSUE THREAD

**Issue by waka8** [woothemes/woocommerce#7831]
There is a problem in displaying countries list on checkout page. When you are logged in, this list has its top value larger than it has to be because of wordpress stick menu.

**Comment by mikejolley** [comment]
I don't understand the issue. Ensure the issue occurs with Twenty Twelve theme and no other plugins active and provide more details if it does please. If it doesn't happen with twenty twelve, its not a core bug.
