### ISSUE TITLE
Problem with normalizing parameters for oauth when using nested parameter arrays

### ISSUE THREAD

**Issue by joe15000** [woothemes/woocommerce#7833]
When using HTTP oauth 1-legged authentication and using the API Enpoint "Create Order Note", when sending the required nested parameter array, the "normalize_parameters" function in the API class 'class-wc-api-authentication.php' fails at line 282 with the following warning: 

Warning: rawurldecode() expects parameter 1 to be string, array given in /home/mysite/wp-content/plugins/woocommerce/includes/api/class-wc-api-authentication.php on line 282

The parameter array for the API Call as per documentation:
{
  "order_note": {
    "note": "Order ok!!!",
    "customer_note": false
  }
}

Since the normalize_parameters function goes through a one-dimensional array and normalizes the key and value by using 

$value = str_replace( '%', '%25', rawurlencode( rawurldecode( $value ) ) );

the above warning is generated because the "$value" of 

{
    "note": "Order ok!!!",
    "customer_note": false
}

is not a string.

This requires any client library to follow the same logic in letting rawurldecode fail on trying to convert an array to a string (or just rawencode a null value if $value is an array), otherwise authentication will fail.

Is this intended? Does the normalize_parameters function need to be recursive?

The above generated warning is included in the API response as long as E_WARNING is turned on.

**Comment by maxrice** [comment]
When creating a resource, you must include the request in the body, not as a query parameter. So the request would look something like:

```
POST http://yoursite.com/wc-api/v2/orders/order_notes

request body (JSON):
 {
"order_note": {
"note": "Order ok!!!",
"customer_note": false
}
}
```

**Comment by joe15000** [comment]
@maxrice: Of course,  that is how a POST request works. This is not the issue. For the 1-legged OAuth process the normalized parameters are also passed as a query string with some hashes in parallel.  The decoding of this on the API side is where the error occurs.

**Comment by maxrice** [comment]
@joe15000, just tested this and it worked as expected. Can you put your code/requests here so I can take a look? For reference, this is what a successful request looks like:

```
POST http://wcdev.com/wc-api/v2/orders/21538/notes?oauth_consumer_key=ck_2f1c8f740f1288fadf3310a9e4612601&oauth_timestamp=1427739629&oauth_nonce=6b734ec981d6290c61f41a095f79b0750940f425&oauth_signature_method=HMAC-SHA256&oauth_signature=9CFQe%2FcXwajgKhkcd%2By2gYwD9opTYifOjvw%2FdOtRQnw%3D
```

with request body:

```json
{  
   "order_note":{  
      "note":"woohoo!",
      "customer_note":false
   }
}
```

The request body is never included in the signature calculation, only GET parameters are, see [here](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L136).

**Comment by JohnZeat** [comment]
@joe15000, The problem is in the v1 api client library. it combines request body with the signature $params array, as a result it tries to normalize the request data which ends up returning the error. after much research, i found that @maxrice solved a similar problem [here] (https://github.com/woothemes/woocommerce/issues/6174), in which he makes a modification to the make_api_call function and separates the oauth $params from the request data. Here is the code I ended up with which works like a charm. notice the $data array being passed from the calling procedure but he $params array being declared as an empty array. I tested this with GET and PUT requests but not DELETE or POST. 

```PHP
private function _make_api_call( $endpoint, $data = array(), $method = 'GET') {
        $ch = curl_init();

        $params = array();
        // Check if we must use Basic Auth or 1 legged oAuth, if SSL we use basic, if not we use OAuth 1.0a one-legged
        if ( $this->_is_ssl ) {
                curl_setopt( $ch, CURLOPT_USERPWD, $this->_consumer_key . ":" . $this->_consumer_secret );
        } else {
                $params['oauth_consumer_key'] = $this->_consumer_key;
                $params['oauth_timestamp'] = time();
                $params['oauth_nonce'] = sha1( microtime() );
                $params['oauth_signature_method'] = 'HMAC-' . self::HASH_ALGORITHM;
                $params['oauth_signature'] = $this->generate_oauth_signature( $params, $method, $endpoint );
        }

        if ( isset( $params ) && is_array( $params ) ) {
                $paramString = '?' . http_build_query( $params );
        } else {
                $paramString = null;
        }

        // Set up the enpoint URL
        curl_setopt( $ch, CURLOPT_URL, $this->_api_url . $endpoint . $paramString );
        curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, false );
        curl_setopt( $ch, CURLOPT_CONNECTTIMEOUT, 30 );
        curl_setopt( $ch, CURLOPT_TIMEOUT, 30 );
        curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );

        switch ($method) {
            case 'POST':
                curl_setopt($ch, CURLOPT_POST, true);
                curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
                break;
            case 'DELETE':
                curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');
                break;
            case 'PUT':
                curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
                curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
                break;
        }

        $return = curl_exec( $ch );

        $code = curl_getinfo( $ch, CURLINFO_HTTP_CODE );

        if ( $this->_return_as_object ) {
                $return = json_decode( $return );
        }

        if ( empty( $return ) ) {
                $return = '{"errors":[{"code":"' . $code . '","message":"cURL HTTP error ' . $code . '"}]}';
                $return = json_decode( $return );
        }
        return $return;
}
```

**Comment by uresh** [comment]
solved the prob thnaks

**Comment by uresh** [comment]
solved the prob thanks
