### ISSUE TITLE
Email admin template

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7835]
Actually `WC_Email::admin_options` prints HTML code from the method.
Can't we move it into a template like we do for other admin pages?

**Comment by BFTrick** [comment]
You want to have template for the admin settings screens? Why is that? Theme's have no place editing backend settings pages. If you want to edit those I would do so with hooks.

Or am I missing something?

**Comment by SiR-DanieL** [comment]
It's not for editing settings pages. All the other parts have templates, for consistency i think we should have one for this too.

**Comment by BFTrick** [comment]
Editing the settings screen is that code I saw. Where does this code show up on the front end? What does it do? We must be looking at different things.

**Comment by SiR-DanieL** [comment]
For example we have these templates for the admin: https://github.com/woothemes/woocommerce/tree/master/includes/admin/views

each of them print a section of the admin side. While for the emails we print them in the class and there's not a template.

I do not want the template to be overrideable, or show it on the frontend. I just want all the things equal.

We have templates for the admin in most sections, so we can switch this part in a template too.

**Comment by BFTrick** [comment]
I believe the email code you're talking about already uses the `html-admin-settings.php` view doesn't it? Don't most of the settings use that view? Won't this just be redundant then?

**Comment by SiR-DanieL** [comment]
I'm not sure. Most methods are like this: https://github.com/woothemes/woocommerce/blob/c6dae2b2866dfd42db2b092a426d01d1f3b49892/includes/abstracts/abstract-wc-settings-api.php#L75

This one instead has more code to print other stuff too.

**Comment by BFTrick** [comment]
I don't think this is that important. I'll reopen and let the dev team decide what they want to do.

**Comment by mikejolley** [comment]
I imagine these may be refactored in the future, but right now all admin_options(), even the abstract, output html so this is no exception.
