### ISSUE TITLE
Emails look bad in Outlook

### ISSUE THREAD

**Issue by saulfautley** [woothemes/woocommerce#7841]
This is the preview of the email template I've just configured:

![2015-03-28_141247](https://cloud.githubusercontent.com/assets/2036475/6881181/58d6de92-d55d-11e4-8a0d-a0ac229091d7.png)

This is what an email using the template looks like in my online webmail client:

![2015-03-28_144420](https://cloud.githubusercontent.com/assets/2036475/6881115/54b4bb5c-d55a-11e4-8a10-e595b638475b.png)

And this is the same email in Microsoft Outlook 2013:

![2015-03-28_145408](https://cloud.githubusercontent.com/assets/2036475/6881119/77e1b882-d55a-11e4-9fa0-7ee84da54e7e.png)

Note the:

- background color
- text color
- link color
- font family
- spacing of heading
- border around heading

**Comment by BFTrick** [comment]
I [refactored the emails for 2.3](http://develop.woothemes.com/woocommerce/2014/10/2-3-emails/). The same CSS should be applied to the preview emails that is applied to emails that are actually sent.

Email clients are notorious for handling CSS differently from every other email client. Most of them only handle CSS2. This means a beautiful web page might look horrible and different in each email client.

We added the CSS Inliner which should help with some of these CSS issues but it can't fix email clients. Creating beautiful emails is an art in itself. If you want there's a huge list of resources here: http://stackoverflow.com/questions/2229822/best-practices-considerations-when-writing-html-emails

I hope that helps! :)

**Comment by saulfautley** [comment]
I'm quite familiar with coding HTML emails that display correctly and consistently across email clients and degrade gracefully for the less-capable ones.

Your CSS Inliner feature is great, don't get me wrong. I'm merely suggesting that the default email styles could be improved to work better for popular, albeit incapable, email clients.

For instance, if you simply changed the `#body_content_inner` selector to `#body_content_inner, p, table`, you would already eliminate any unstyled text in the email.

**Comment by BFTrick** [comment]
Thanks for that. Will investigate.

**Comment by jameskoster** [comment]
@BFTrick I don't have outlook. :p

We'll need help with this.

**Comment by saulfautley** [comment]
@jameskoster you could use [Litmus](https://litmus.com/email-testing) to preview code across multiple email clients. They even have a 7 day free trial.

**Comment by jameskoster** [comment]
Good thinking batman.

Will look into this for 2.4.

**Comment by rochow** [comment]
FYI Outlook needs font defined for every <td>. For whatever reason it won't inherit!

**Comment by deepankarpathak** [comment]
You can also try <a href="https://putsmail.com/">Putsmail</a> to test your HTML emails before sending them.

**Comment by ILLUMINICE** [comment]
I'm very glad to see this issue posted here, as I've been corresponding with WC support about this exact problem. I noticed some troubling changes to email in Microsoft Outlook after updating from WC version 2.2 to 2.3. In fact, we noticed something else not reported here.

This screenshot below is what WC emails used to look like prior to the version 2.3 update in Outlook 2010 (yes, I know that's an older Outlook version, but not much changed between 2010 and 2013). Specifically what needs to be noted here is the kerning (space between letters), and also the email title (at the top of the email with the red background).

![originaltextformatting](https://cloud.githubusercontent.com/assets/11562655/8088509/b49618b4-0f56-11e5-9be8-05d98b8f05a3.jpg)

Now take a look at this screenshot below. The most obvious problem is the encoded/scrambled text in the title. This is a very strange issue. It only seems to occur in Outlook and is also intermittent. I've found that if you click to another email, and back to this email again, the scrambled title will display normally. This issue never happened in WC version 2.2 emails.

Secondly, notice the kerning of the text and how compressed it now looks. While we do like the new margin (more or less), the kerning is really making this hard to read compared to the original (see above). This seems to be a Microsoft Outlook issue, as I haven't seen this in other clients.

![scrambledemailtitles](https://cloud.githubusercontent.com/assets/11562655/8088552/0296b3b6-0f57-11e5-96ff-2bd81f2b5229.jpg)

We noticed a few other more favorable changes in Outlook, like some of the section headers now using the highlight color (billing address, etc). This is great. But these two issues above, the kerning and the scrambled titles, really are a problem that must be addressed.

I realize every email client handles the code differently, but so many people are using Outlook, and I think this deserves special attention for that reason.

Hope this all helps!

~ Michael

**Comment by jameskoster** [comment]
I'll be looking into this soon.

If it corrects itself, then the scrambled text is most likely an outlook issue, though. I quickly googled and got lots of results for scrambled text in outlook 2013.

**Comment by ILLUMINICE** [comment]
Hi James,

The scrambled text is actually occurring in Outlook 2010. I'm still using that version at the moment, as I've put upgrading off a while. Of course this may also be happening in Outlook 2013 as well.

What is strange to me is that I never saw this scrambled text issue until we upgraded to WC V.2.3. The WC emails from V.2.2 never demonstrated this problem. This may not be a coincidence.

I'm sure you read about the other issues, namely the compressed text (kerning), and thank you for looking into this for all us Outlook users.

I'm at your disposal for any testing in Outlook.

~ Michael

**Comment by jameskoster** [comment]
I've been working on this a bit today, using Litmus to test Outlook. I was unable to replicate the scrambled header, or the kerning issues that you're seeing @ILLUMINICE but I was able to fix a bunch of stuff.

Will take a look at and improve mobile styling tomorrow.

**Comment by ILLUMINICE** [comment]
Hi James,

Your efforts are very much appreciated. I'm not surprised you weren't able to reproduce the scrambled text on your end. It's an intermittent issue even on my end. This may be Outlook version specific too.

The fact you don't see the kerning change is interesting though. You can clearly see the change between my two screenshots. It may actually be using a different font-family too.

I can only confirm this change happened immediately when updating from WC 2.2 to 2.3. I'm pretty sure it has something to do with the email formatting between those two versions.

In any case, I'm glad you're giving Outlook some special attention. The better these emails look in Outlook the better off many of us will be. If I can be of any help to you for testing, please let me know.

~ Michael

**Comment by jameskoster** [comment]
We did introduce a different font family in 2.3. But it's a system font, with a fallback for other system fonts. So I'm really not sure what's happening on your computer.

If you have time, please give the updated email templates a test. It's as simple as taking each template file from https://github.com/woothemes/woocommerce/tree/master/templates/emails and uploading them to your test environment. I'd appreciate it.

**Comment by Dooza** [comment]
I was getting a server 500 error in admin-ajax.php on the checkout page until I put an extra line at the bottom of email-styles.php.

**Comment by jameskoster** [comment]
@Dooza do you mean after the uploading the updated templates? Any feedback beyond that? :p
