### ISSUE TITLE
Custom shipping fields gets hidden when the checkbox ship to the billing address is checked

### ISSUE THREAD

**Issue by ninio** [woothemes/woocommerce#7843]
**Steps to reproduce:**
Add a custom shipping field
On the checkout page: Make sure the checkbox  "Ship to a different address" is not checked

**Result:**
The custom shipping field gets also hidden

**Expected:**
The custom added fields should persist. (Or at least the ones that are not present in the billing form)

For now the only solution I can think of is adding this field as a billing one despite the fact that it's shipping related. Any idea for other possible one?

**Comment by BFTrick** [comment]
Have you looked at adding the field to the "custom fields" section (not visible by default)? You can see how to do it here: http://docs.woothemes.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/#section-4
