### ISSUE TITLE
Variation Upload Image Hard to See

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce#7844]
During WordCamp Atlanta @DanielSantoro and myself were at the Happiness Bar and two users thought you had to buy [Variation Swatches](http://docs.woothemes.com/document/woocommerce-color-and-image-swatches/) to upload an image for each variation. I think this is because the variation uploader icon is a bit hard to see. And the icon doesn't scream "image" when you look at it (without hovering).

Can we change the icon or do something else to make this stick out a bit more? It's a shame when people think they have to buy plugins to do stuff they could do for free.

![edit_product_ _woocommerce_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/6889517/90105c68-d665-11e4-8915-49917275b0d6.png)

**Comment by bryceadams** [comment]
100% agree and I've seen this before with several customers.

**Comment by jameskoster** [comment]
Any suggestions? Maybe just reveal the icon all the time, instead of just on hover? We could make it bigger, but it lines up nicely at that size ^^

**Comment by BFTrick** [comment]
Well James you're the UI guy so I'll leave it up to you. I do think having a brighter more noticeable icon would help. Unfortunately the icon doesn't scream "image". :/

![droplr_draw_app](https://cloud.githubusercontent.com/assets/1065372/6970450/c700a640-d932-11e4-8c9c-e93f7f01828b.png)

Think we can get an icon more representative of an image?

**Comment by DanielSantoro** [comment]
I like the mockup picture Patrick put so something like that with a darker border would definitely help make it stand out. Or, we could instead of the icon have it say "Variation Image..." in that box so they can essentially read the field title.

FontAwesome also has some good photo-related icons:

Camera: http://fontawesome.io/icon/camera/
Image Filetype: http://fontawesome.io/icon/file-image-o/
Picture: http://fontawesome.io/icon/picture-o/

I love FontAwesome <3

**Comment by roykho** [comment]
WordPress already includes dashicons https://developer.wordpress.org/resource/dashicons/#editor-insertmore

Use one of those...

**Comment by franticpsyx** [comment]
Since all fields have labels, it wouldn't hurt to have a label there, too, apart from a beefed-up version of the WC placeholder image, or a better one.

**Comment by jameskoster** [comment]
That is a dashicon ;-)

I'll use an image icon and make it visible all the time, not just on hover.

**Comment by roykho** [comment]
No, that is not what I meant.  Danny mentioned to use Fontawesome.  So i am stating why use that when dashicon is available.

**Comment by jameskoster** [comment]
Hopefully that's a bit clearer.

**Comment by BFTrick** [comment]
I like it!

![edit_product_ _woocommerce_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/7046732/1cbf809c-ddc5-11e4-8e20-6100ad0f7933.png)

**Comment by franticpsyx** [comment]
:+1:
