### ISSUE TITLE
Variation Images Not Saving in WC 2.3.7

### ISSUE THREAD

**Issue by jprummer** [woothemes/woocommerce#7846]
When attempting to attach images to some variations in WooCommerce 2.3.7 some of them are not updating properly. Note: This is for products that were previously set properly.

Here is the process:

I select a variation with a blank image

![blankimage](https://cloud.githubusercontent.com/assets/5695617/6890585/71ce3436-d66b-11e4-9032-fa7c8c702964.PNG)

I then add the image. Notice that the id is properly attached to the input:

![imageidset](https://cloud.githubusercontent.com/assets/5695617/6890588/832da7ca-d66b-11e4-9c71-57c4785bd13e.PNG)

However, when I 'update' the product, the post data shows zero for that field instead of the id set in the previous image.

![postdata](https://cloud.githubusercontent.com/assets/5695617/6890594/9dc0216c-d66b-11e4-8be2-2fcd88547b01.PNG)

I'm not sure if this is actually an issue with WooCommerce core or not, but I thought you could at least give me some next steps for trying to debug how the input is properly set, but becomes blank on save. Oh, and I also tried the technique here http://docs.woothemes.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/ and this doesn't seem to be the issue.

Thanks!

**Comment by roykho** [comment]
I am not able to replicate this issue.  Please try turning off all plugins except WooCommerce and re-test.  Also try switching your theme to 2012 and re-test.  Closing for now.
