### ISSUE TITLE
Coupon calculated wrongly with taxes included

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7847]
If i have prices with taxes included and show them also tax incl. the discount is calculated after applying taxes.

Product Price: 305 (tax incl)
Tax rate: 21%
Discount: 10%

![](http://cld.wthms.co/1eole+)

The discount should be applied before taxes.

Ticket #/274122

**Comment by mikejolley** [comment]
The above handling is correct with tax inc prices. 

305 - 30.5 = 274.50, then work out tax backwards from that.

If I went into a shop in the UK (where we use tax inc prices) and had 10% off, I would expect £1 off a £10 product.
