### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by MandelkindC** [woothemes/woocommerce#7850]
Hi all

I still have problems with the permalinks for the WooCommerce Products.
I always get an Error 404 when i activate the permalinks via the WP Settings.
It doesn't matter which settings / base I activate. Nothing works.
I tried different plugins without success.

Can you help me ?
Thank you in advance.

Additional info: WP and WooCommerce Plugin are up to date.

Greets
MandelkindC

**Comment by WPprodigy** [comment]
Hi MandelkindC, 

Could you open up a support ticket here: http://woothemes.zendesk.com/requests/new

Please provide your WC status report, and any other further details that you can provide:)

**Comment by BFTrick** [comment]
Yep this isn't an error I can reproduce. We need *reproducible* steps to investigate the issue. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
