### ISSUE TITLE
WC round up prices

### ISSUE THREAD

**Issue by whoaloic** [woothemes/woocommerce#7855]
Hello,
I import product through CSV and I have prices with decimals (i.e 540.60) but prices are rounded (540.00)  in the frontend and in the admin list of product (not in the admin single product).
Any idea to resolve this?
Cheers.

**Comment by mikejolley** [comment]
Sounds like you may have used commas for decimals in the CSV - that would cause 'rounding' (discarding the decimal), or it could be your currency settings.

Look into the above. If you cannot solve it, raise a ticket on the help desk if this is product csv import suite plugin.

**Comment by whoaloic** [comment]
Thank you Mike :)
