### ISSUE TITLE
Featured Image not displaying Title

### ISSUE THREAD

**Issue by LindsayHeydon** [woothemes/woocommerce#7857]
This is a tiny thing I noticed, but when clicking on the Featured image (using WooCommerce) when on a single product page, the lightbox effect is fine, but for the Featured image only it does not display the Title. The Product Gallery is fine and displays the titles as expected (even if the same image as the Featured image is included in the thumbnails). 

I've tested this in a Genesis theme and also the default WordPress Twenty Fifteen theme using WooCommerce.

It seems that WooCommerce grabs the description for the first featured image from the image caption, and then uses the image title for subsequent product images.

The issue with this is remembering to use a caption for featured images and titles for everything else.

**Comment by jameskoster** [comment]
Working fine here: http://cl.ly/image/0w0Y1k1W3i2M But the gallery has the caption and the title the wrong way around. Will fix that.

**Comment by LindsayHeydon** [comment]
That's what I'm saying, the caption works for Featured image and Titles for gallery, so there is a mix.

Oh my, if you change (which I agree you should) my poor client has used the Title as explained and the captions are empty... as titles displayed for the gallery (and so worked for the majority of images).  Is there an easy way to copy the titles to the empty captions now as over 500 products! Many thanks....

Lins

On 2 Apr 2015 18:36, James Koster <notifications@github.com> wrote:
Working fine here: http://cl.ly/image/0w0Y1k1W3i2M But the gallery has the caption and the title the wrong way around. Will fix that.

---

**Comment by jameskoster** [comment]
Hey,

Hmm, there's not really much I can recommend that doesn't involve a little dev.

It should be possible to write a script to do the conversion, if you're handy at that kind of thing.

Probably not what you wanted to hear, sorry about that :-(

**Comment by LindsayHeydon** [comment]
OK, thanks, at least I know. I'll have to look into the script... :)
