### ISSUE TITLE
Variable product issues after changing from Simple product

### ISSUE THREAD

**Issue by DeboMediaGroup** [woothemes/woocommerce#7860]
I recently changes all 9 of the products on my site from "Simple products" to "Variable products"

I added the "Quantity" attribute to all 9 products which contains two different variations.

"TWO (2) seeds" and "SIX (6) seeds" are the two variations, each having a different price.

I received my first order since I made these changes and noticed issues in the "New Order" email.

Below is a screenshot of the "New Order" email.
![screen shot 2015-03-31 at 12 18 33 pm](https://cloud.githubusercontent.com/assets/11737854/6923462/e22a9be0-d79f-11e4-926b-cb1d57774932.png)

Notice the products "Jigsaw" and "Midnight Express" DO NOT show the quantity that was selected, even thought "TWO (2) seeds" were selected for both products based on the price that is showing.

Below are screenshots of both the "Jigsaw" and "Midnight Express" products BEFORE and AFTER a Quantity is selected:
![screen shot 2015-03-31 at 12 21 54 pm](https://cloud.githubusercontent.com/assets/11737854/6923569/85fad8c0-d7a0-11e4-8f25-4264d8b93520.png)

![screen shot 2015-03-31 at 12 22 18 pm](https://cloud.githubusercontent.com/assets/11737854/6923578/8b52ebd2-d7a0-11e4-809e-608181303fd0.png)

![screen shot 2015-03-31 at 12 23 08 pm](https://cloud.githubusercontent.com/assets/11737854/6923586/8fa5b87c-d7a0-11e4-81b2-6d446bc124a6.png)

![screen shot 2015-03-31 at 12 23 14 pm](https://cloud.githubusercontent.com/assets/11737854/6923590/93ebaea0-d7a0-11e4-8355-fe0d6efbbc6f.png)

Along with that, here are screenshots of what the order looks like in the backend:
![screen shot 2015-03-31 at 12 25 15 pm](https://cloud.githubusercontent.com/assets/11737854/6923630/e4576b7c-d7a0-11e4-87e5-93eb2771996b.png)

![screen shot 2015-03-31 at 12 25 33 pm](https://cloud.githubusercontent.com/assets/11737854/6923634/e85fb13e-d7a0-11e4-845c-fda4a0f2a686.png)

**Comment by mikejolley** [comment]
Without product access I can only assume here, but it looks like your 'jigsaw' and 'midnight' products won't have the attributes assigned to the variations. If its set to 'all' rather than a specific attribute, the data won't be shown.

However, user selections should be stored and this isn't happening in your case which could indicate a plugin conflict.

I cannot replicate any issues with variations in the current build so I will close this, but you can let us know what you find.

**Comment by DeboMediaGroup** [comment]
I am not sure I understand what you mean by "it looks like your 'jigsaw' and 'midnight' products won't have the attributes assigned to the variations. If its set to 'all' rather than a specific attribute, the data won't be shown."

If **what** is set to 'all'?

**Comment by mikejolley** [comment]
The attributes per variation. Edit the variable product and look at its variations tab.

**Comment by DeboMediaGroup** [comment]
This is what I see...

Jigsaw
![screen shot 2015-04-14 at 11 27 16 am](https://cloud.githubusercontent.com/assets/11737854/7140365/e626d3c2-e298-11e4-991a-baf407e98eef.png)

Midnight Express
![screen shot 2015-04-14 at 11 28 11 am](https://cloud.githubusercontent.com/assets/11737854/7140396/05744750-e299-11e4-92b8-ec8daea98e58.png)
