### ISSUE TITLE
Incorrect message given when user uses bulk edit to adjust sale price on variable product

### ISSUE THREAD

**Issue by byronyasgur** [woothemes/woocommerce#7867]
When I try to change the price on a variable product the message gives the impression that the sale price has been applied, but it hasn't, because woocommerce doesn't support this currently ... https://github.com/woothemes/woocommerce/issues/4076

**Comment by mikejolley** [comment]
Improving bulk edit is part of https://github.com/woothemes/woocommerce/issues/6995
