### ISSUE TITLE
Adding discount on Manually Adding Order page is not possible with 2.3

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7869]
I recently upgraded a shop from 2.1 to 2.3. In 2.1 it was possible to add a discount from the Manually Adding Order page. Now in 2.3 this feature seems to have gone. Could we get this back?

From time to time a customer get's a certain, say 10 € discount, and now there seems to be no way of adding this discount via a manually added order (admin page > WooCommerce > Order > Add Order).

**Comment by mikejolley** [comment]
I think you're referring to the edit button next to the discount amount - but these discounts were after tax, something we no longer support (and should probably never have been used in your client's case if they used taxes).

You can edit line items to adjust costs. If you use the subtotal/total field this will calculate/show the correct discount to the customer on their invoice.

**Comment by jnachtigall** [comment]
> You can edit line items to adjust costs. If you use the subtotal/total field this will calculate/show the correct discount to the customer on their invoice.

whooha, that's something really not so easy to understand ;-) I need to click on editing the total and the tax of a line item to effectively add a discount. Anyway, thanks, I'll let the shop users know.

> ... but these discounts were after tax, something we no longer support ...

On a related note: From a conceptional/comprehension point of view I think this was really a mistake. In Germany, and I think also the rest of the EU, something like discounts before tax is something totally unheard of... Discounts after tax are not only the default, it is the only thing that exists.

**Comment by mikejolley** [comment]
@jnachtigall I think you may have that backwards. I highly doubt any EU state would discount after tax - tax is based on the amount of the sale, not what the sale "may" have been.

**Comment by samazgor** [comment]
"**Add Fee**" by the negative value. it can bypass VAT :rofl: 

![screenshot from 2017-06-20 00-29-51](https://user-images.githubusercontent.com/2386485/27300093-5ba6548e-5550-11e7-9455-29051908dde1.png)
