### ISSUE TITLE
Make WooCommerce update styling and message consistent

### ISSUE THREAD

**Issue by thegdshop** [woothemes/woocommerce#7874]
Would it be possible to get this type of styling and message - http://cld.wthms.co/12zjD in the dashboard area? http://cld.wthms.co/12WKp

**Comment by kloon** [comment]
If I can add some feedback on this, this is not possible unfortunately. WordPress strips out all tags for the message on the core update dashboard.

**Comment by msdesign21** [comment]
Sounds like a good reason to request this feature for WP core.
