### ISSUE TITLE
Product categories with description display

### ISSUE THREAD

**Issue by SaranKS** [woothemes/woocommerce#7875]
Hi team,

I am using current version of woocommerce plugin. I need to display all the product categories and its image with its description in a page with two column display. 

I just want to display the following details in a page with two column layout

1. Category name or title
2. Category Image
3. Category Description

Is there any possible ways to display these details using shortcode?

If it is not, where can I customize the code.

Please help to fix this issue, as soon as possible.

Thank you,

With regards,
Saran Sakthi

**Comment by mikejolley** [comment]
Github should be used for issue reports only; not support requests. Therefore I am closing this.

FYI you can do a template override and edit the category template file. https://github.com/woothemes/woocommerce/blob/master/templates/content-product_cat.php Add your description in there.
