### ISSUE TITLE
Kosovo missing from country list

### ISSUE THREAD

**Issue by aprintbuyer** [woothemes/woocommerce#7876]
when i was building a list of European Countries I noted that Kosovo was missing from list

Many thanks

**Comment by 50LinesOfCode** [comment]
I also noticed this just now when trying to do the same thing. But according to some websites, Kosovo has not yet been officially assigned an ISO Country Code.
But if you look here http://en.wikipedia.org/wiki/Kosovo you can see it has the code XK. Thats what I will be using.

**Comment by mikejolley** [comment]
When its officially recognised, it will be added (http://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements).

Until then, you can add the country to your list via a small snippet.

**Comment by lkraav** [comment]
It's almost 2023 now. What's the latest on this? I have a customer online right now asking about why Kosovo is missing.

**Comment by ErjonTafaj** [comment]
Do you know if this has been solved?

**Comment by sverleis** [comment]
For anyone wanting to add a country via a snippet, the WooCommerce documentation covers it via https://woocommerce.com/document/add-a-new-country-to-countries-list
