### ISSUE TITLE
Product reviews template is in wrong place, I think

### ISSUE THREAD

**Issue by fernandoacosta** [woothemes/woocommerce#7877]
The file templates/single-product/reviews.php don't exists, but is called in woocommerce_product_reviews_tab function => https://github.com/woothemes/woocommerce/blob/master/includes/wc-template-functions.php#L914-L924

If I create this file in my template nothing happens in product tabs. The right file is single-product-reviews.php. 

It's ok? woocommerce_product_reviews_tab is unnecessary function? Thanks!

**Comment by mikejolley** [comment]
Must be legacy

**Comment by claudiosmweb** [comment]
@mikejolley We do not use it since 2.0
