### ISSUE TITLE
Product categories columns is not working

### ISSUE THREAD

**Issue by SaranKS** [woothemes/woocommerce#7878]
Hi,

I am using following shortcode to display categories in a page.I need to display two items per row. But it displays only one column in each row.
 
[product_categories number="12" parent="0" columns="2"]

**Comment by mikejolley** [comment]
Sounds like a theme styling issue. I just tested the above with no issues https://dl.dropboxusercontent.com/s/xisbwomt5i71zj1/2015-04-09%20at%2013.02%202x.png?dl=0
