### ISSUE TITLE
Creating different user roles on the basis of account registration parameters with Woocommerce

### ISSUE THREAD

**Issue by elena18** [woothemes/woocommerce#7880]
I have to solve the following problem to which I didn't find any solution by now.

I am working on a Wordpress site, on which I implemented Woocommerce. Besides the possibility of buying products, I would like to let teh customers downloading a pdf catalogue. However the catalogue may be for customers or for resellers, according to the parameters they specify when the register their account (I already customized the account fields in the Woocommerce registration form).

I used the WP Download Manager plugin, which permits to donwload files according to the user role. Hence the idea is to create user roles according to the parameters specified in the registration form. Hence if a reseller checks the "reseller checkbox" a user role "reseller-customer" will be created; otherwise if the client is a private, the "reseller checkbox" won't be checked and the user role thus created will be "private-customer".

Is that possible?

**Comment by roykho** [comment]
Unfortunately this is not a place to get support.  This is for bug reports/fixes only.  I would suggest you open up a ticket with us instead https://support.woothemes.com/hc/en-us/requests/new
