### ISSUE TITLE
Issue with v2 API product creation

### ISSUE THREAD

**Issue by dphaener** [woothemes/woocommerce#7883]
I am having an issue during product creation, and/or update with the v2 API. I have a script that runs nightly to create or update products via the API. When this script runs, at times images are randomly erased from the images folder, i.e. `wp-content/uploads/2015/04`. I'm not really sure what is happening here, but I am doing nothing to that folder directly, the only thing I am doing is creating and updating products. During the update phase, I am only updating quantities.

**Comment by Umakant-DM** [comment]
HI dp,

Can you give me a help,

I want to access rest api in WooCommerce , when i want to open orders in using this url domain.com/wc-api/v2/orders , it shows this error. "{"errors":[{"code":"woocommerce_api_authentication_error","message":"oauth_cons‌​umer_key parameter is missing"}]} " .

Please help me.

**Comment by dphaener** [comment]
@Umakant-DM Looks like you're missing the consumer_key in your request. I would check this out: http://woothemes.github.io/woocommerce-rest-api-docs/#authentication. If you're having issues and/or difficulties with oath, you can use basic authentication as long as it's over https. Also, I would try to ask questions like this on Stackoverflow or a similar forum. This is really for issues and bugs, not technical difficulties.

**Comment by claudiosmweb** [comment]
When it fails to create the product, the attachments are deleted.

**Comment by dphaener** [comment]
Ok, but there are other, non product images that are being removed as well.

**Comment by claudiosmweb** [comment]
Some products must be failing and so deleting your images.
I'll try to fix it, to delete only new items.

**Comment by claudiosmweb** [comment]
Well, I was wrong xD
If the images already exist on your site, they can not be deleted, only new uploads.
So this is not the problem.

Show me what you are doing, maybe I have some idea.

**Comment by claudiosmweb** [comment]
Closed by the lack of feedback.
