### ISSUE TITLE
Bug: Specific countries (including Mexico and Brazil) are unable to checkout using IE 11 with WooCommerce 2.3.7

### ISSUE THREAD

**Issue by shaunkuschel** [woothemes/woocommerce#7885]
While using WooCommerce 2.3.7 and Internet Explorer 11, certain countries are not able to select a state in the menu on the checkout page. This has been verified with both Mexico and Brazil. As soon as customers reach the checkout page, the state selection menu(s) are expanded but nothing can be selected. This also causes the customers to not be able to enter any other information or complete the checkout process.

Steps to reproduce:
- In the General Options of WooCommerce 2.3.7, set the Selling Location(s) to 'Sell to all countries' or 'Sell to specific countries' and specify Mexico and Brazil.
- Using Internet Explorer 11, go through the checkout process and calculate shipping to either Mexico or Brazil.
- Continue to checkout page and observe that the state selection menus will be immediately expanded and will not allow selections to be made.

![mexico](https://cloud.githubusercontent.com/assets/10855013/6989078/296f55c0-da1d-11e4-8e84-796e70c294fe.jpg)
![brazil](https://cloud.githubusercontent.com/assets/10855013/6989080/33c32c9a-da1d-11e4-8058-736d4c268018.jpg)

**Comment by ChromeOrange** [comment]
@jameskoster this one is for you I believe

**Comment by jameskoster** [comment]
Isn't this the same as https://github.com/woothemes/woocommerce/issues/7729 ?

**Comment by ChromeOrange** [comment]
If it is then it's not fixed, my tests and Shaun's tests were using 2.3.7

**Comment by jameskoster** [comment]
Looks like the placeholder is being applied based what was selected in the shipping calculator. I thought we removed all the placeholder attributes though. I'll investigate tomorrow.

**Comment by jameskoster** [comment]
Fixed on the 2.3 branch for next release.
