### ISSUE TITLE
Wrong  slug attributes in product/<id>

### ISSUE THREAD

**Issue by abada** [woothemes/woocommerce#7891]
[
{
name: "Chocolate Dipped?",
slug: "Chocolate Dipped?",
position: "0",
visible: true,
variation: true,
options: [
"No",
"Yes"
]
},
{
name: "Size",
slug: "size",
position: "1",
visible: true,
variation: true,
options: [
"Large",
"Regular",
"Small"
]
}
]

In first attribute slug is the same name

slug must be chocolate-dipped 

like variations

[
{
name: "Chocolate Dipped",
slug: "chocolate-dipped",
option: "no"
},
{
name: "Size",
slug: "size",
option: "small"
}
],

**Comment by mikejolley** [comment]
This is a text/custom/product-level attribute, not a real taxonomy based attribute, therefore it has no real slug. 

`
'slug'      => str_replace( 'pa_', '', $attribute['name'] ),
`
