### ISSUE TITLE
[Improvement Request] Layered Nav Widget uses term_id in filter URL. For SEO purposes could the term name be used?

### ISSUE THREAD

**Issue by majemedia** [woothemes/woocommerce#7892]
## Example:

* Attribute Name(slug): Color(color)
* Terms(id): red(1), blue(2), green(3)

Currently when you filter by "red" the URL is populated with `filter_color=1`. Could this instead be `filter_color=red`.

## Links:
* Moz: http://moz.com/ugc/guide-to-ecommerce-facets-filters-and-categories
* Practical eCommerce: http://www.practicalecommerce.com/articles/3857-SEO-When-Product-Facets-and-Filters-Fail
* Search Engine Watch: http://searchenginewatch.com/sew/how-to/2235290/ecommerce-seo-filtering-and-segmentation#

**Comment by mikejolley** [comment]
Should be possible. Made part of https://github.com/woothemes/woocommerce/issues/7806

**Comment by claudiosmweb** [comment]
I liked it.
