### ISSUE TITLE
Capability bug

### ISSUE THREAD

**Issue by vinnyusestrict** [woothemes/woocommerce#7893]
Hi,

I want to allow a role to view reports but not have access to the Settings. Using user-role-editor plugin, I can set a role to have 'view_woocommerce_reports' capability and not 'manage_woocommerce'. The result is a blank space in the sidebar menu where 'WooCommerce' entry should be, and no drop-down.

Expected result: If any capability that enables an item in the WooCommerce submenu is selected, the top-level WooCommerce item should be generated.

Thanks,
Vinny

**Comment by mikejolley** [comment]
This was added in WC 2.3.6
