### ISSUE TITLE
WooCommerce Eway extension prevents use of custom credit card template

### ISSUE THREAD

**Issue by ABDpromotions** [woothemes/woocommerce#7896]
Issue reported in ZD [Ticket 277208](https://woothemes.zendesk.com/agent/tickets/277208).

Possible bug in the eway extension that prevents the implementation of custom credit card form template...

Line 256 in class-wc-gateway-eway.php reads:

woocommerce_get_template( 'eway-cc-form.php', array(), 'eway/', plugin_dir_path( __FILE__ ) . '../templates/' );

When it should (like for the saved cc form) read

woocommerce_get_template( 'eway-cc-form.php', array(), 'woocommerce-gateway-eway/', plugin_dir_path( __FILE__ ) . '../templates/' );

**Comment by roykho** [comment]
@ABDpromotions - please post this in the correct repo https://github.com/woothemes/woocommerce-gateway-eway
