### ISSUE TITLE
WC_MAX_LINKED_VARIATIONS only partially working

### ISSUE THREAD

**Issue by JoeKendall** [woothemes/woocommerce#7897]
I have noticed on a few occasions when upping the `WC_MAX_LINKED_VARIATIONS` value from 50, even to a figure like 55, the auto linking works fine (Although the ordering is different to a less than 50 batch) however when then batch editing the created variation, it will only update the first 50.

Turning on debugging, the error notice: `Notice: Undefined offset: 50 in /home/USER/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php on line 1366` is shown. 
This same error occurs on a subsequent 5 or 6 lines. 

I can reproduce this 100% of the time, please let me know if you need more info. 

Thanks, Joe.

**Comment by JoeKendall** [comment]
Versions info: 
Wordpress: Version 4.1.1
WooCommerce: Version 2.3.5
WooCommerce Product Add-ons: Version 2.7.0

**Comment by mikejolley** [comment]
Sounds like http://docs.woothemes.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/

WC_MAX_LINKED_VARIATIONS only affects the linking of said variations, it does not affect the meta box itself.
