### ISSUE TITLE
The product variation is invalid

### ISSUE THREAD

**Issue by abada** [woothemes/woocommerce#7898]
I create a new order with product variations on the api. This example works:

```
"variations":
{
    "pa_size": "regular"
}
```

But with this data it is not working:

```
"variations": [
    {
        "pa_size": "regular"
    },
    {
        "pa_chocolate-dipped": "no"
    }
]
```
I think it only accepts a single variation and not a collection (array).

**Comment by abada** [comment]
It works but in this case

for example

variations": 
{
"pa_size": "regular"
}

But not working in this case

variations": [
{
"pa_size": "regular"
},
{
"pa_chocolate-dipped": "no"
}
]


I think it accept one single variation not array

**Comment by claudiosmweb** [comment]
Just use:

```json
"variations": {
  "pa_size": "regular",
  "pa_chocolate-dipped": "no"
},
```

**Comment by abada** [comment]
http://woothemes.github.io/woocommerce-rest-api-docs/#orders-properties

variations	array	

List of product variation attributes. e.g: 

```
 "variation": [{"pa_color": "Black"}, {"pa_size": "XGG"}] 
```

(Use pa_ prefix when is a product attribute)


Can you please update docs :)

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce-rest-api-docs/commit/49e75acf803738ed7c17f3c0f77d14ae7bda7734

**Comment by abada** [comment]
@claudiosmweb Thank you :)
