### ISSUE TITLE
Display Dynamic Content For Each Product Variation

### ISSUE THREAD

**Issue by whoaloic** [woothemes/woocommerce#7899]
Hello.
I would like to know how to add custom fields to product variations and then showing/hidding the custom field data per the respective product variation selected by the user (like SKU or price).
I was able to to add custom fields to each product variation but I'm still looking for a way to display these values in the frontend.

I've found this piece of code but something goes wrong.
https://gist.github.com/kloon/4228021#comment-1177265

Any help would really appreciated.
Cheers.

**Comment by mikejolley** [comment]
We have something in the works, #7121

**Comment by whoaloic** [comment]
I do see with Firebug an array of the custom field variation values per variable product but I can't display them on frontend based on selected variation.
Cheers.
