### ISSUE TITLE
Change ALL extension update messages

### ISSUE THREAD

**Issue by thegdshop** [woothemes/woocommerce#7902]
We need to really work on changing customer expectations. A first good step would be to change all extension update messages.

Two key points we must communicate to all users:
- Make a backup of EVERYTHING.
- Test in a "Testing Environment" before updating the live site.

The WooCommerce core update message could be a good model - http://cld.wthms.co/12zjD
Current extension update notice has no mention of the key points above - http://cld.wthms.co/dzkR

**Comment by mikejolley** [comment]
@thegdshop Could you log this in the correct place please (https://github.com/woothemes/woothemes-updater/issues) - extensions != core. Cheers :)
