### ISSUE TITLE
Ability to override HTML in hard coded notice messages

### ISSUE THREAD

**Issue by jameslnewell** [woothemes/woocommerce#7905]
Hi. This is my first WooCommerce project. It's coming together much more easily than with the alternates I tried to skin. Thanks!

---

I'm writing a heavily customised theme for my client. By overriding the templates in my theme folder I've been able to change most of the button styling to re-use existing classes as used throughout the rest of the project. However there seems to be a few instances of the buttons hardcoded around the place e.g.

- https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L889
- https://github.com/woothemes/woocommerce/blob/master/includes/wc-cart-functions.php#L87

Can these instances be updated to be skinable some how (filters/templates/whatever)?

**Comment by claudiosmweb** [comment]
This is just CSS, you can just write CSS for this classes. Oo

WooCommerce has styles in SCSS and you can simply replace the `woocommerce-general` styles location.

Like:

```php
function custom_woocommerce_enqueue_styles( $styles ) {
	$style['woocommerce-general']['src'] = str_replace( array( 'http:', 'https:' ), '', get_stylesheet_directory_uri() ) . '/woocommerce.css';

	return $style;
}

add_filter( 'woocommerce_enqueue_styles', 'custom_woocommerce_enqueue_styles' );
```

Then you can copy the SCSS files to your template, edit and compile :)

**Comment by jameslnewell** [comment]
Hi claudiosmweb. We have existing styles using the BEM naming standard and our `.button` class only applies common button styles. We need to add `.button--primary` etc classes to apply our full button styling.

Applying our styles to the `.button` class as you suggest will break all the other buttons on the site. I've already dequeued the default WooCommerce stylesheets.
