### ISSUE TITLE
Wrong product status for Vietnamese 

### ISSUE THREAD

**Issue by 5ngua** [woothemes/woocommerce#7906]
It happens when Variation product is stock managed at product level. When I set the product quantity as 5 (or something more than 0), the product status should be "Còn hàng" (In stock), but in the current version, it is "Hết hàng" (Out of stock) even though people still can order. 

So this is just a translation mistake. Please fix this. Thanks

**Comment by SiR-DanieL** [comment]
Thanks for reporting! You can fix the Vietnamese translation here: https://www.transifex.com/projects/p/woocommerce/

**Comment by 5ngua** [comment]
sorry, I tried to create an account and find the translation mistake but I couldn't. All "In stock" has been correctly translated to "Còn hàng". Maybe not a translation mistake.
