### ISSUE TITLE
Please let the Canceled order notification sent to customer's inbox 

### ISSUE THREAD

**Issue by 5ngua** [woothemes/woocommerce#7907]
Currently, Canceled order notification email is sent to admin's inbox, but I think it's good idea to send notification to customer's inbox too.

**Comment by mikejolley** [comment]
A cancelled order notification is to make admin aware of the cancellation. In most cases, either the customer triggered the action, or simply didn't pay. In both cases, they do not need to be notified about this event.

**Comment by natko1** [comment]
> A cancelled order notification is to make admin aware of the cancellation. In most cases, either the customer triggered the action, or simply didn't pay. In both cases, they do not need to be notified about this event.

Any chance to reconsider? As an option? It's important that the customer also received this notification. Most of the time they are requesting it.
