### ISSUE TITLE
Add more translation checks to transiflex

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7912]
I just recently updated the German translation on transiflex. There were some very serious problem like:
* `%s` being translated to `%` or `% s` (space), `s` or forgotten
* `%qty%` being translated to `%%`
* The input placeholder `YYYY-MM-DD` being translated to `DD-MM-YYYY`
* Some really, really wrong translations instructing the shop manager (admin) or customer (frontend) to do stuff that's really not meant to be working in this way. Plus inconsistent translations and some really "funny" wording sometimes :)

I think there is not much one can do about the last point. Transiflex has some reviewer role, so with this at least some kind of QA process is there already, albeit this is relying on a good translation community with reviewers doing their job... (which has not totally been the case for German in the last half year)

Anyway for the first 3 points: Transiflex offers [customizable translation checks](http://docs.transifex.com/faq/#how-does-transifex-assure-the-quality-of-the-translations) like `Variable substitution specifiers (like "%s") are preserved in the translations`. See this [blog post](https://www.transifex.com/blog/2013/customize-translation-checks-for-your-files/) for info about it.

Where it makes sense, could you please turn on as many of these for the woocommerce project on transiflex. I think adding these as `Warning` is sufficient, but maybe for `Variable substitution specifiers (like "%s") are preserved in the translations` it should be even added as type `Error`.

I think only the project maintainers are able to add these checks.

**Comment by mikejolley** [comment]
Looks like these are now 'on'
