### ISSUE TITLE
Better UX for registration on "My Account" page

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7913]
I really like to have a way for customers to create an account even if they have not bought anything before. For this there is `woocommerce_enable_myaccount_registration`, but I do not like the way it is currently done for UX reasons:

1. It is confusing to have two username/password forms next to each other (left for login, right one for register
2. Even if customers register they would then still need to enter required fields like billing or shipping address on the next page. There are no instruction that tell users this. 

I would propose to change this in the following way:

1. No "partial" registration anymore on "My Account" but instead only a link like `No account yet? Register here` 
2. `Register here` links to a form (with an endpoint like my-account/register) which is very similar to the current checkout form which asks the customer to enter all required and optional fields like address and tel. (not just mail and password)

![auswahl_038](https://cloud.githubusercontent.com/assets/3307404/7053927/3b121dec-de39-11e4-9b3d-0d4dd33c738b.png)

![auswahl_039](https://cloud.githubusercontent.com/assets/3307404/7053963/87c94944-de39-11e4-9dc8-3da27f2beae0.png)

Sorry for the screenshots being in German, I guess you still get the idea

**Comment by claudiosmweb** [comment]
Since WC 2.1 you can customize it: https://support.woothemes.com/hc/en-us/articles/203182373-How-to-add-custom-fields-in-user-registration-on-the-My-Account-page

Anyway, on this page the customer will register before you buy.
I don't see why force the customer entering an address and personal data before actually buying something.

**Comment by jnachtigall** [comment]
From a user point of view, I think it is still confusing and quite uncommon (that is against learnt behaviour) to have the login and register form on the same page. I'd prefer to have the register form on a separate page. Then focus would be much clearer.
