### ISSUE TITLE
API create_product and edit_product 

### ISSUE THREAD

**Issue by Nils-Fredrik** [woothemes/woocommerce#7914]
Hi,

Line 186 (https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L186) and 283 (https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L283) does this: 
```$data = isset( $data['product'] ) ? $data['product'] : array();```

Then execution continues. When is it ok for $data to be an empty array? As far as I can see this only leads to an exception which does not explain the real problem (https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L294): 
```
if ( ! isset( $data['title'] ) ) {
    throw new WC_API_Exception( 'woocommerce_api_missing_product_title', sprintf( __( 'Missing parameter %s', 'woocommerce' ), 'title' ), 400 );
}
```

In my opinion line 186 and 283 should be: 
```
if( isset( $data['product'] ) ) {
    $data = $data['product'];
} 
if( count( $data ) == 0 ) {
    throw new WC_API_Exception( 'woocommerce_api_missing_product_data', sprintf( __( 'No product data specified to create product', 'woocommerce' ), 'title' ), 400 );
}
```

The above change will also allow sending the following array as parameter $data to create_product and edit_product:
```$data = array( 'title' => 'Dummy title', 'sku' => '123'); ```
The current way of sending product data will still work:
```$data = array( 'product' => array( 'title' => 'Dummy title', 'sku' => '123') ); ```

I will make a pull request, hopefully you get the chance to review and comment this before 2.4 is out. :-)

Nils-Fredrik Winther-Kaland
http://twitter.com/nilsfredrik

**Comment by maxrice** [comment]
Probably should be an exception of the product data is missing, though I'd caution against allowing both of those arrays to create/edit a product. The goal (particularly when editing) is to allow a client to get the product, change the data, and then PUT it back without requiring any additional translation.

**Comment by Nils-Fredrik** [comment]
@maxrice I see your point, but since the suggested fix/feature/bug does not interrupt with the get, change and put sequence I think this should be allowed. 

We are using the API quite a lot, but we keep on doing this same mistake: forgetting the 'product' key. I think the world of WC developers will save 1500 hours the next few years by allowing to update/insert both with and without it. :-)

**Comment by maxrice** [comment]
@Nils-Fredrik yeah I see what you mean, probably worth changing this in the next API version so either approach works :)
