### ISSUE TITLE
API bulk update / insert

### ISSUE THREAD

**Issue by Nils-Fredrik** [woothemes/woocommerce#7915]
When working with large amount of products and frequent updates its really needed to get rid of the product-by-product updates. 

I would love to see the following method implemented in WC_API_Products: 

```
	
	/**
	 * Bulk update or insert products
	 * Accepts an array with products in the formats supported by
	 * WC_API_Products->create_product() and WC_API_Products->edit_product()
	 *
	 * @param array $products
	 * @throws Exception
	 * @return array
	 */
	public function bulk( $data )    {
	    $products = array();
	    foreach ( $data as $_product )   {
	        try {
	            $existing = $this->get_product_by_sku( $_product['sku'] );
	            if(is_wp_error($existing) && $existing->get_error_code() === "woocommerce_api_invalid_product_sku") {
	                // SKU not found, go ahead and crate!
	                $result = $this->create_product($_product);
	            } else {
	                // Assume existing, update
	                $result = $this->edit_product( $existing['product']['id'], $_product );
	            }
	            if(is_wp_error($result))   {
	                // if it fails, add the error message to the return object. Do not! stop further execution.
	                $products[ $_product['sku'] ] = array( 'error' => array( 'code' => $result->get_error_code(), 'message' => $result->get_error_message() ) );
	            } else {
	                // If everything is well, add the updated or created product to the return array
	                $products[ $_product['sku'] ] = $result;
	            }
	        } catch(Exception $e)  {
	            $products[ $_product['sku'] ] = array( 'error' => array( 'code' => $e->getCode(), 'message' => $e->getMessage() ) );
	        }
	    }
	    return array('products'=>$products);
	}
```

It does not walk side by side with get_products since we need to handle failed updates or inserts from individual products. This can solved by returning an array with the sku as key and either the product or an error as the value. This way the user of the bulk method can check which updates/inserts was successfull and which was not. 

Nils-Fredrik Winther-Kaland
http://twitter.com/nilsfredrik

**Comment by Nils-Fredrik** [comment]
Looks like some code from #7914 was mixed into this commit.

**Comment by claudiosmweb** [comment]
@maxrice what you think?

**Comment by Nils-Fredrik** [comment]
Comment: I have used the patch in production the last week. On sites with 5000+ products being updated a few times a day, sending bulks of 10 and 10 products, the load on the server has been reduced, and the total time updating all products has been cut to 20%. Increasing the bulksize reduces the load even more.

**Comment by claudiosmweb** [comment]
@Nils-Fredrik great! But thinking how to approach this as best we can, because we'll do to all endpoints.

**Comment by maxrice** [comment]
@Nils-Fredrik @claudiosmweb I like the approach :) Some thoughts:

* should accept both PUT/POST requests to the `bulk` endpoint
* we may want to consider a soft resource limit (say, update up to 100 products per API call, filterable) to prevent weird issues when servers kill longer-running requests. This is a particularly messy situation as there'd be no response (other than a likely HTTP 500 error) and you wouldn't have a good way of knowing which products were successfully updated and which weren't.
* also consider limiting bulk updates/creation to select resources first (like products and orders) and then add other resources later once we better understand how they're used

**Comment by Nils-Fredrik** [comment]
@maxrice great!

* Regarding the limiting: I do not think it should be limited by default. It should be documented that this is a bulk operation and for large updates you should consult your serveradmin and implement your own logik for sending bulks of for example 100 products. 
* Products is definitely the most important endpoint. Its far more common to update 1000s of products every day than orders.

**Comment by maxrice** [comment]
@Nils-Fredrik I think for the majority of API consumers (and particularly for client implementations, say a mobile app) won't have a great understanding of what their server environment is capable of so it's much safer to default to reasonable limit that will ensure there are no timeouts with most server configuration.

The benefit then to making it filterable is that for implementations like yours, you can change that to effectively have no limit.

The main goal with a limit is to impose consistency on the API across varied server configurations so anyone integrating with the API can assume a bulk update request will complete successfully, regardless of whether the site is hosted on shared or dedicated hosting :smile_cat:

**Comment by Nils-Fredrik** [comment]
@maxrice you are probably right!

**Comment by claudiosmweb** [comment]
@Nils-Fredrik sorry xD I just editing almost everything you did.

@maxrice Please see my changes, tell me what you think :)

**Comment by Nils-Fredrik** [comment]
@claudiosmweb it looks good! Thanks. :+1:

**Comment by maxrice** [comment]
@claudiosmweb left a few comments on the [commit](https://github.com/woothemes/woocommerce/commit/bcfdbcdd0a2c3719151876c5e6f8031d84c2b0eb), looks great :+1:

**Comment by claudiosmweb** [comment]
@maxrice thanks :)

**Comment by claudiosmweb** [comment]
TODO:

- [ ] Bulk endpoint for Orders
- [ ] Bulk endpoint for Customers
- [ ] Bulk endpoint for Coupons

**Comment by claudiosanches** [comment]
@U1timatePeter how? have you skipped things like "Batch update products"?
Check the REST API documentation, there is very complete, with examples and so on.
Thanks.
