### ISSUE TITLE
Need a way to get the effective tax rate during woocommerce_cart_calculate_fees()

### ISSUE THREAD

**Issue by isarmstrong** [woothemes/woocommerce#7916]
Hey Mike & Co,

I've spent days on this now. We've got a hardware discount on a subscription product - like cell phones - which is working just fine with Force Sells (although I had to unpack all the variations to make it work). The problem I'm running into starts with the California FTB.

http://articles.latimes.com/2010/oct/25/business/la-fi-lazarus-20101026

If someone buys a smart irrigation controller with a 3 year contract at $35/mo, the $249 hardware is free. Woo gleefully reports no tax on the item, which would be great if it was a T-Shirt. The problem is that this is like a cellphone, where we're required to bill sales tax on the full value of the hardware item ($249).

It's easy enough to grab the original price and sale price of the item and take the difference. The problem is that woocommerce_cart_calculate_fees() literally runs right before the tax calculations, and there doesn't seem to be an API method for grabbing the effective tax rate.

I need something like WC()->cart->tax_rate;

That way I can take:

$thisproduct = wc_get_product($value);

Then take:

$thisproduct->regular_price - $thisproduct->sale_price

And multiply the result by WC()->cart->tax_rate;

In a perfect world, we'd just add California bundled/unbundled tax law into the subscriptions extension, while adding the option to make the up-front a real product, and then we'd make the recurring subscription virtual (so it doesn't incur shipping costs). In that case we could bundle the whole thing into a variable subscription and trap California's tax laws on checkout.

It's not a perfect world though.

I need a way to capture the effective tax rate on the cart. Only then will I be able to apply California sales tax to the discounted hardware.

Any advice on this one?

**Comment by isarmstrong** [comment]
Also, even when it calculates properly on orders that don't discount down to zero, I have no idea what causes it to place the fee on month vs up front in subscriptions. The woocommerce_cart_calculate_fees feels almost random. It's gone back and forth on nearly identical code a few times this week.

All in all, dealing with the California bundled/unbundled tax in Woo subscriptions is a nightmare under the current implementation. I'll happily write up every sticking point I've hit for the devs as a post-mortom but first I need the issue resolved :(

![order](https://cloud.githubusercontent.com/assets/1513378/7059219/25c00790-de22-11e4-836f-5608c230464d.png)

**Comment by isarmstrong** [comment]
This is my current totally non-refactored code. Excuse the bloat, I'm iterating in real time here.

```php
/**
 * WooCommerce Extra Fee
 * Add a custom fee to the cart. This should take the coupon discount multiplied by the sales tax rate
 */

global $cart_math;
$cart_math = array();

function etw_calculations() {
    global $cart_math;

    // Initialize the variables we need in order to calculate the fee.

    $etw_term = null;
    $etw_subsidy = null;
    $etw_rate = null;

    global $order_vitals;
    $order_vitals = array();

    // Get the necessary objects to extract data
    $cartstuff = WC()->cart->get_cart();
    $cartcontents = WC()->cart->cart_contents;

    // First, let's fetch the subscription term in months and set $etw_term
    foreach($cartstuff as $hash => $data) {
        // Inception: the dream within the dream. Go.
        foreach ($data as $key => $value) {
            // Get the product by ID so we can test against it
            $thisproduct = wc_get_product($value);
            if( 'subscription' == $thisproduct->product_type ) {
                $etw_term = $thisproduct->subscription_length;
                $order_vitals['subscription_term'] = $thisproduct->subscription_length;
            }
        }
    }

    // Second, calculate the discount
    foreach($cartstuff as $hash => $data) {
        // Inception: the dream within the dream. Go.
        $do_one_time = 0;
        foreach ($data as $key => $value) {
            // Get the product by ID so we can test against it
            $thisproduct = wc_get_product($value);
            if( 'simple' == $thisproduct->product_type && $do_one_time < 1 ) {
                if( 0 != ($thisproduct->regular_price - $thisproduct->sale_price) ) :
                    $order_vitals['regular_price'] = $thisproduct->regular_price;
                    $order_vitals['sale_price'] = $thisproduct->sale_price;
                    $order_vitals['sku'] = $thisproduct->sku;

                    $cart_math[$thisproduct->sku] = array(
                        'regular_price' => $thisproduct->regular_price,
                        'sale_price' => $thisproduct->sale_price
                    );

                    if( !empty($order_vitals['sale_price']) ) {
                        $order_vitals['discount'] = ($thisproduct->regular_price - $thisproduct->sale_price);
                        $etw_subsidy = ($thisproduct->regular_price - $thisproduct->sale_price);
                    } else {
                        $order_vitals['discount'] = 0;
                        $etw_subsidy = 0;
                    }
                    $do_one_time++;
                endif;
            }
        }
    }

    // Third, we need our effective tax rate. We have to reverse engineer it because Woo lacks a get rate method on the cart as of 2.3
    $do_one_time = 0;
    foreach ($cartcontents as $k => $v) {
        if ($do_one_time < 1) {
            $the_cost = $v['line_total'];
            $the_tax = $v['line_tax'];

            $order_vitals['total_cost'] = $v['line_total'];
            $order_vitals['total_tax'] = $v['line_tax'];

            // Round the result to the nearest hundredth - should get us our exact tax rate used
            $etw_rate = round(ceil(($the_tax / $the_cost)*1000)/1000,2);
            $order_vitals['tax_rate'] = round(ceil(($the_tax / $the_cost)*1000)/1000,2);

            // Increment the counter so this only runs once
            $do_one_time++;
        }
    }

    $order_vitals['final_fee_front'] = round(ceil((($etw_subsidy * $etw_rate))*1000)/1000,2);
    $order_vitals['final_fee_month'] = round(ceil((($etw_subsidy * $etw_rate) / $etw_term)*1000)/1000,2);

    return $order_vitals;
}

add_action( 'woocommerce_cart_calculate_fees','subsidy_tax' );
function subsidy_tax() {
    global $woocommerce;
    global $cart_math;
    $vitals = etw_calculations();

    $price_origin = 0;
    $price_sale = 0;
    $total_discount = 0;

    foreach( $cart_math as $sku => $data ) {
        $price_origin = $price_origin + $data['regular_price'];
        $price_sale = $price_sale + $data['sale_price'];
    }

    $total_discount = $price_origin - $price_sale;

    $bundletax = $total_discount * $vitals['tax_rate'];
    if ( empty($bundletax) ) {
        $bundletax = $total_discount * .09;
    }

    if ( is_admin() && ! defined( 'DOING_AJAX' ) )
        return;

    if ( 'CA' == WC()->customer->get_shipping_state() && !empty($total_discount) ) {
        $woocommerce->cart->add_fee( 'California Bundle Tax', ($bundletax / $vitals['subscription_term']), false );
    }
}
```

**Comment by isarmstrong** [comment]
More directly, why does this return an empty array?

$testtax = WC_Tax::calc_tax('249', 'standard');

I've clearly misinterpreted the nature of the WC_Tax class structure.

**Comment by isarmstrong** [comment]
Seems the answer is this:

$get_rates = WC_Tax::find_rates(WC()->session->get( 'customer' ));

But that was tricky to figure out because the session gets destroyed on refresh unless I let the address go through (testing private session for maximum failure probability).

Will refactor the final code and post, assuming nothing else blows up on me.

**Comment by isarmstrong** [comment]
This should probably be a class... and would need a category check if another shop wanted to use it (in the comments):

/**
 * WooCommerce Extra Fee for California's bundled product tax
 * @author Ian Armstrong (@imperativeideas)
 * -------------------------------------------
 * California (and possibly other states) are a pain in the ass.
 * Reference: http://articles.latimes.com/2010/oct/25/business/la-fi-lazarus-20101026
 * We are selling a bundled product, discounted by a subscription plan, so we need to bill the sales tax on the
 * declared full value of that product. WooCommerce doesn't make this easy. The extra fee needs to be assessed
 * on the woocommerce_cart_calculate_fees() hook, which runs twice (once for the product, once for the subscription) -
 * and this would have to be further refined if we were expecting other non-bundled items in the cart. We only do this
 * for the bundled hardware!
 *
 * Anyway... we need to take the original product value, subtract the sale value, and calculate California sales tax on
 * the result. The tax is calculated via AJAX using the WooCommerce session, built in the constructor of the WC_Customer
 * class. That took me days to figure out. That's why WC_Tax::find_rates(WC()->session->get( 'customer' )); runs inside
 * of the execution hook and not inside of the etw_calculations function. The session is also wiped out on refresh, unless
 * it was just set before ctrl-R, making getting the debug value really confusing if you don't know that!
 */

// woocommerce_cart_calculate_fees runs twice so we globalize a variable to hold both iterations
global $cart_math;
$cart_math = array();

// These are the base calculations needed to make our system work
function etw_calculations() {
    global $cart_math;

    // Initialize the variables we need in order to calculate the fee.
    $etw_term = null;
    $etw_subsidy = null;
    $etw_rate = null;

    // Create the order vitals, to be stored inside of $cart_math as a subarray
    global $order_vitals;
    $order_vitals = array();

    // Get the cart contents
    $cartstuff = WC()->cart->get_cart();

    // First, let's fetch the subscription term in months and set $etw_term
    foreach($cartstuff as $hash => $data) {
        // Inception: the dream within the dream. Go.
        foreach ($data as $key => $value) {
            // Get the product by ID so we can test against it
            $thisproduct = wc_get_product($value);
            if( 'subscription' == $thisproduct->product_type ) {
                $etw_term = $thisproduct->subscription_length;
                $order_vitals['subscription_term'] = $thisproduct->subscription_length;
            }
        }
    }

    /** Second, calculate the discount. This is a bit of hack... we only do it on the first product. In a more robust
        cart we would want to test the product CATEGORY as well, assigning all bundled products to it **/
    foreach($cartstuff as $hash => $data) {
        // Inception: the dream within the dream. Go.
        $do_one_time = 0;
        foreach ($data as $key => $value) {
            // Get the product by ID so we can test against it
            $thisproduct = wc_get_product($value);
            if( 'simple' == $thisproduct->product_type && $do_one_time < 1 ) {
                if( 0 != ($thisproduct->regular_price - $thisproduct->sale_price) ) :
                    $order_vitals['regular_price'] = $thisproduct->regular_price;
                    $order_vitals['sale_price'] = $thisproduct->sale_price;
                    $order_vitals['sku'] = $thisproduct->sku;

                    $cart_math[$thisproduct->sku] = array(
                        'regular_price' => $thisproduct->regular_price,
                        'sale_price' => $thisproduct->sale_price
                    );

                    if( !empty($order_vitals['sale_price']) ) {
                        $order_vitals['discount'] = ($thisproduct->regular_price - $thisproduct->sale_price);
                        $etw_subsidy = ($thisproduct->regular_price - $thisproduct->sale_price);
                    } else {
                        $order_vitals['discount'] = 0;
                        $etw_subsidy = 0;
                    }
                    $do_one_time++;
                endif;
            }
        }
    }

    // Return the order vitals array
    return $order_vitals;
}

// Now to assess the actual fee
add_action( 'woocommerce_cart_calculate_fees','subsidy_tax' );
function subsidy_tax() {
    // Need this in order to call add_fee()
    global $woocommerce;

    // Grab that global array (yes, this should be a class but whatever... next refactor)
    global $cart_math;

    // Run the calculations that populate the global array.
    $vitals = etw_calculations();

    // Initialize the variables so the IDE doens't yell at us
    $price_origin = 0;
    $price_sale = 0;

    // For each iteration of the hook, grab the price. This exists in case TWO subscription products are added to the cart.
    foreach( $cart_math as $sku => $data ) {
        $price_origin = $price_origin + $data['regular_price'];
        $price_sale = $price_sale + $data['sale_price'];
    }

    // Calculate the discount
    $total_discount = $price_origin - $price_sale;

    // Get the tax data based on the user's zip code (as entered)
    $get_rate = WC_Tax::find_rates(WC()->session->get( 'customer' ));

    // Return the rate as an percentage (integer)
    foreach( $get_rate as $taxrate ) {
        $vitals['tax_rate'] = $taxrate['rate'];
    }

    // Multiply the total discount by the tax rate (as a fractional value)
    $bundletax = $total_discount * ($vitals['tax_rate'] / 100);

    // Get this as a monthly value for the life of the subscription, round to nearest cent
    $monthlytax = round(ceil(($bundletax / $vitals['subscription_term'])*1000)/1000,2);

    /** useful for debugging **/
//    echo '<h3>Debug Info</h3>';
//    echo '<p>This should run twice, once for the hardware and again for the subscription. The latter will not overwrite the former because it is null. ';
//    echo 'If the tax is empty, enter your information and hit enter, then refresh. You need an active session in order to see it.</p>';
//    echo '<ul>';
//    echo '<li>Bundle Tax: ' . $bundletax . '</li>';
//    echo '<li>Subscription Term: ' . $vitals['subscription_term'] . '</li>';
//    echo '<li>Original Price: ' . $price_origin . '</li>';
//    echo '<li>Sale Price: ' . $price_sale . '</li>';
//    echo '<li>Discount: ' . $total_discount . '</li>';
//    echo '<li>Tax Percentage: ' . $vitals['tax_rate'] . '</li>';
//    echo '<li>Tax as Decimal: ' . $vitals['tax_rate'] / 100 . '</li>';
//    echo '<li>Bundle Tax: ' . $bundletax . '</li>';
//    echo '<li>Per Month Tax: ' . $monthlytax . '</li>';
//    echo '</ul>';
//    echo '<hr />';

    // Standard AJAX check when adding a fee
    if ( is_admin() && ! defined( 'DOING_AJAX' ) )
        return;

    // If we are in California and a discount exists...
    if ( 'CA' == WC()->customer->get_shipping_state() && !empty($total_discount) ) {
        // Divide the calculated tax by the subscription term and add a line item fee
        $woocommerce->cart->add_fee( 'California Bundle Tax', $monthlytax, false );
    }
}

**Comment by isarmstrong** [comment]
Oddly, the whole function echoes out $monthlytax but $woocommerce->cart->add_fee sees it as a zero a couple of lines later.

Le sigh.

**Comment by isarmstrong** [comment]
... because it's running against the subscription fee and overwriting the simple product fee. FML.

**Comment by isarmstrong** [comment]
I give up.

```php
// If a session in California returns a blank rate because Woo Sessions are finicky awful things that should feel bad about themselves...
        if ( empty($bundletax) ) {
            $bundletax = $total_discount * .09;
        }
```

Error trapped it and rounded to the average. Echo returns a value, but add_fee() iterates across a zero value. If a developer cares to comment, I'm all out of ideas.

**Comment by mikejolley** [comment]
This is a helluva long ticket, so if I have missed something apologies. There is no function to get an effective tax rate. Items can have multiple taxes at once, so a single rate is not calculated, and thats not how taxes get applied.

The facts about the problem I understand as:

1. Tax on the subscription itself is regular
2. The phone itself is 'free'...
3. ...but you have to pay the tax on the phone

So in a sense, 2 and 3 require an after tax discount. Rather than use fees, how about this:

1. Have a subscription for the tariiff
2. Have a product for the phone, priced at $249
3. Link the two products somehow with forced sells, or don't, up to you
4. Have a function that hooks into the cart_calculated_totals - this is after tax - and if the cart qualifies, discount $249

The subscription will be unaffected and taxed correctly. The cost of the phone will be wiped. The tax for the phone will remain.

I also tested the above with what maybe could be considered a hack, but works. Negative fee:

`
$this->add_fee( 'Discount', -249, false, '' );
`

That wipes the cost of the phone, but tax remains.

Hope this sets you on a path to solve the issue.

**Comment by isarmstrong** [comment]
Yeah sorry about that Mike. I've been on a very tight deadline so I was walking through my process and hoping for guidance. This is great, will try it out in staging.

**Comment by isarmstrong** [comment]
The trick here is that it should really be done with a variable subscription.

1 year, retrofit install : $249 (full price)
2 years, retrofit install : $99
3 years, retrofit install : $0
1 year, new install : $599 (full price)
2 years, new  install : $399
3 years, new install : $199

So what I have is two types of hardware and 3 subscription terms. Force sells don't recognize variables, neither do bundles. That means I'll have lots of flaming hoops to dance through in order to get the appropriate discount if I don't use a sale price.

Will play around with the options as you laid them out and see what I can work out.

**Comment by isarmstrong** [comment]
Honestly, bundled subscriptions is probably a decent plugin candidate all by itself. Nothing on the market is making it easy to have a physical product followed by a recurring service term. The current subscriptions extension add shipping on both ends because the sub can't be made virtual.

Won't be in time to help me but it could be a good market angle for you guys.
