### ISSUE TITLE
Set variation out of stock if stock is set to zero

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#7918]
When we set the quantity of a product variation to 0 manually, it automatically set the status to out of stock and hides it from the front-end.

However, when an order is placed for that variation, the quantity is reduced to 0 but the variation is still set to In Stock and thus available on the frontend.

**Comment by mikejolley** [comment]
1. Enabled hide our of stock items
2. Setup variable product - no stock management product level
3. Setup variations - 1 in stock
4. Bought variation with BACS
5. Go back to product page, variation bought no longer available.

Does not seem to be an issue. If you have a different setup you'll need to be more specific on how to reproduce this.
