### ISSUE TITLE
Woocommerce too many variations causes connexion reset

### ISSUE THREAD

**Issue by whoaloic** [woothemes/woocommerce#7921]
I have a product with +20 variations.
The connexion was reset while attempting to go to the product page.
When I remove some variations (maximum 20), it works.

I've increased memory limit :
define('WP_MEMORY_LIMIT', '96M');
but I still get the issue.

Please could anybody help me on this?
Regards.

**Comment by SiR-DanieL** [comment]
https://github.com/woothemes/woocommerce/issues/6995

**Comment by maksbd19** [comment]
I think this is an issue with suhosin patch for PHP. If I am correct you might be benefited by looking in the following links-

http://suhosin.org/stories/configuration.html
https://journalxtra.com/wordpress/wordpress-php-suhosin-out-of-memory-and-execution-timeouts/

**Comment by mikejolley** [comment]
Also see http://docs.woothemes.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/

Closing in favour of #6995

**Comment by whoaloic** [comment]
All right It was a firewall issue !
