### ISSUE TITLE
Search by SKU - Variable Products

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#7926]
When searching for an SKU in the product's admin area, the sku's on a variation level do not show up in search results.
____
### Steps to Reproduce: 
1. Create Variation Product w/ 1 or more variations
2. Give the variations a different SKU than their parent
3. Search for that SKU in the admin

**Comment by mikejolley** [comment]
Added to https://github.com/woothemes/woocommerce/issues/6995

**Comment by claudiosmweb** [comment]
This would be in the product list. So is not part of #6995.
I'll leave open for now to examine and perhaps include in a future milestone.
