### ISSUE TITLE
Non Conformance OAUTH 1.0 Specification

### ISSUE THREAD

**Issue by paulogr** [woothemes/woocommerce#7927]
Hi,

I'm new using woocommerce and I played with the Rest API today all day long.

I tried to use some libs to generate the signature to pass the OAUTH 1.0 authentication but without success.

I tried the follow libraries:

https://github.com/nraboy/ng-cordova-oauth
https://github.com/bettiolo/oauth-signature-js
http://oauth.googlecode.com/svn/code/javascript/example/signature.html

So then I see this comment on an issue here

https://github.com/woothemes/woocommerce/issues/6493#issuecomment-58730042

He (@ravinderk) removed the token secret from signature, and then it works. I did that too on ng-cordova-oauth lib and it works too.

But, I think that those libraries are right, the token secret must be included on key even if you are not using it, according to OAuth 1 specification:

http://tools.ietf.org/html/rfc5849#section-3.4.2 

So I think that the WooCommerce API has non conformance with OAuth 1 specification.

Can you confirm that for me ?

Thanks

**Comment by claudiosmweb** [comment]
Just follow these steps: http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

I'm working on a client API for Node.js, should be ready no later than the end of the month.

**Comment by claudiosmweb** [comment]
Just to make clear, is "OAuth 1.0a “one-legged” authentication".

**Comment by paulogr** [comment]
I saw that is one-legged auth, the rfc linked from the page of woocommerce documentation said that you need to include the token secret

http://tools.ietf.org/html/rfc5849#section-3.4.2

This link is on your documentation, I think something is wrong.

This another link refer the oauth 1.0a and say the same.

http://oauth.net/core/1.0a/#anchor15

You cannot just close this issue.
