### ISSUE TITLE
Non Conformance OAUTH 1.0 Specification 2

### ISSUE THREAD

**Issue by paulogr** [woothemes/woocommerce#7928]
Ref https://github.com/woothemes/woocommerce/issues/7927

I saw that is one-legged auth, the rfc linked from the page of woocommerce documentation said that you need to include the token secret

http://tools.ietf.org/html/rfc5849#section-3.4.2

This link is on your documentation, I think something is wrong.

This another link refer the oauth 1.0a and say the same.

http://oauth.net/core/1.0a/#anchor15

Tell me one open-source oauth 1.0 client that works with WOO Commerce API  ?

**Comment by claudiosmweb** [comment]
It works, just follow the docs.
I was able to make it work with JavaScript, you will get well.
As I told you, I'm building something for Node.js that by the end of month will be available to everyone.
Closing because it is not a issue, it actually works, you just need to know some JavaScript.

**Comment by paulogr** [comment]
it works, but has non conformance with OAUTH 1.0a.

To be OAUTH 1.0a you just need to appedend a '&' at the end of your secret key before get HMAC. It's not that difficult.

I saw a lot of people having issues here about generate the signature, and you lost a lot of integration with another systens because you have a non conformance API.

At least you should update your documentation and remove the rfc link from there,

**Your API its not OAUTH 1.0a.**

**Comment by paulogr** [comment]
You need to know that you developing an API, not a PHP script, and to make it work you need to follow the patterns, anyone oauth 1.0 library will change it self because of woocommerce api.

**Comment by claudiosmweb** [comment]
@paulogr This follows the standards, so I was able to make it work in Python, Ruby, JavaScript and PHP.
I found no problem in any of these programmming languages.

@maxrice was the one who created it, if you want it can take more doubts you.

**Comment by maxrice** [comment]
@paulogr Yeah I think you're correct here, the key is this:

>separated by an '&' character (ASCII code 38) **even if empty** (emphasis mine)

As you can see [here](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L247), we use the consumer secret for calculating the signature and it does not include the ampersand character. I read the spec very carefully when I wrote the OAuth implementation but looks like I missed it :frowning: 

Unfortunately this isn't something we can change now, as there's a lot of client libraries and implementations that expect the signature to be calculated our way. Ideally when the WP-API hits WordPress core, we'll revamp the authentication to be spec-compliant, but I wouldn't expect this until WC 2.5 at the earliest.

Incidentally, as @claudiosmweb mentioned, there's a fair bit of libraries that either also do OAuth 1.0 incorrectly, or allow you to override how the signature is calculated such that it's not too burdensome to conform to what I'll dub "WooCommerce OAuth 1.0a" :stuck_out_tongue_winking_eye:

**Comment by paulogr** [comment]
Hi @maxrice, thanks for reply !

I know that's a tough decision to update your API with a lot of clients already using it.

As sugestion, maybe, update the WooCommerce API documentation to make it clear about this issue helps. Make clear that you must implement your own HMAC signature without the '&' at the end of you secret key a removing the RFC link, because this make people think that could use any OAUTH 1.0a library.

It's up to you guys, I'm just telling that because I've wasted some good hours until figure out that and may be others should have the same problem.

Thanks @claudiosmweb and @maxrice

**Comment by sparkweb** [comment]
I wasted a lot of time trying to figure this out too... :)

One other idea might be to actually create two signatures (one without the & and then a backup with the &) and if the first fails, to check it against the second one.

The other Oauth spec problem that gave me fits was the re-ordering of filter items. Seems that converting to a string and re-ordering wasn't supported at least by the library I used. The spec doesn't seem to be very specific on this point.

Here's the notes/PR that I made on the Guzzle library: https://github.com/guzzle/oauth-subscriber/pull/32

**Comment by maxrice** [comment]
Yeah tbh I'm not crazy about comparing against multiple signatures, I'd rather implement the spec properly in a new version and then clients can update their implementations as needed.

**Comment by justinshreve** [comment]
#8415 addresses the issues mentioned in this thread. cc @sparkweb @paulogr.

**Comment by paulogr** [comment]
Glad to see this fix

Really thanks for the good work!

**Comment by claudiosmweb** [comment]
@paulogr here your node module:
https://github.com/woothemes/wc-api-node

And here how to set up for work with v1 or v2:
https://github.com/woothemes/wc-api-node/blob/master/index.js#L78-L80
