### ISSUE TITLE
Filter rest api products list like by stock status, attributes

### ISSUE THREAD

**Issue by rockypb** [woothemes/woocommerce#7929]
Thank you guys for the awesome rest api client library.

I am using V2 version APIs. I am able to filter products by keyword and order as I like But How can I search products based on stock status or other attributes? If its already there How can I do it?

Please let me know direction.

**Comment by claudiosmweb** [comment]
This is not yet possible.
Maybe in a future version.

**Comment by mikejolley** [comment]
I've moved this to the roadmap here: https://trello.com/c/dVXgAaPU/71-rest-api-filter-products-by-attributes-and-stock-status
