### ISSUE TITLE
Tax calculation incorrect

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7930]
I have 2 taxes

NL 21%
IT 22%

And these settings

![](http://cld.wthms.co/11J53+)

Calculation based on the customer billing address.

If i checkout a product and the customer address is based in IT then the produce price is 119.98, while if i choose NL the price is 119.

It should be always 119 as per the product settings.

**Ticket #278310**

**Comment by ChromeOrange** [comment]
@SiR-DanieL 

>It should be always 119 as per the product settings.

nope. 

Entering the price including tax does not mean it's fixed at that price. It means that's how much it is in your tax jurisdiction
