### ISSUE TITLE
Coupon usage not multiplied by quantity

### ISSUE THREAD

**Issue by jknight2014** [woothemes/woocommerce#7940]
My coupons usage count is not being increased more than once per order. ex:

Coupon applies 100% product discount with a usage limit of ten. 

Product x is sold individually (required for PDF Vouchers) and applied to the cart twice. 
The discount is applied to both lines and the order total is $0 as expected. 

Coupon usage only shows 1/10

From other issues I have read the usage should be multiplied by the quantity. I have not tried an item that is not sold individually. I will try that as well as setting the usage limit to 1 and trying two items.

**Comment by jknight2014** [comment]
I set a simple product and a 100% coupon with a limit of 2. I was able to get a discount on 4 (any quantity) and the usage was only raised 1% 

There is no sales tax so apply before sales tax is not an option. I saw this was related to an issue last year.

**Comment by jknight2014** [comment]
It appears maybe the function is the issue, `$count` appears to be set statically to `1` instead of the quantity passed to it. I cant remember if a variable in the use of the function will override the `= 1`

                private function increase_coupon_applied_count( $code, $count = 1 ) {
                        if ( empty( $this->coupon_applied_count[ $code ] ) ) {
                                $this->coupon_applied_count[ $code ] = 0;
                        }
                        $this->coupon_applied_count[ $code ] += $count;
                }

This is the line using that function:

     $this->increase_coupon_applied_count( $code, $values['quantity'] );

**Comment by jknight2014** [comment]
Removing the ` = 1` made no change.

**Comment by mikejolley** [comment]
This is intended to be 1. The coupon is *applied* once - the number of products it applies to is irrelevant. If you'd like to see this change I might suggest putting it on ideas.woothemes.com to see if other store owners want the same thing.
