### ISSUE TITLE
Paypal for Korean Won

### ISSUE THREAD

**Issue by kimyoungae** [woothemes/woocommerce#7941]
Hi

We use woocommerce and many extension for out shopping mall.

We heard PayPal could support Korean Won already, so we use PayPal for our mall.
But we can't use PayPal checkout. We receive error message and I attached image with this issue.

If woocommerce can't support Korean Won currency yet, please support Korean Won for PayPal.

Thanks.

![korean currency for paypal](https://cloud.githubusercontent.com/assets/11921195/7112569/ec81f83e-e205-11e4-8d8a-2538d6ff6401.png)
![korean currency for paypal_2](https://cloud.githubusercontent.com/assets/11921195/7112568/ec7f3b9e-e205-11e4-921e-61796a0fc5f6.png)

**Comment by ChromeOrange** [comment]
Hi

Do you have a link to any documentation from PayPal that shows support for accepting payments in Korean Won

This is the document we use to determine if a currency is supported https://www.paypal.com/multicurrency

**Comment by kimyoungae** [comment]
Here is the email that we have received from PayPal

-----------------------------------------------------------------------

Thank you for taking the time to contact us with your concerns. I am happy to assist you further.  You can sell items online in KRW, however, you main currency of choice will convert any payments to what you have on your PayPal account, i.e. if your account accepts USD, then and KRW paid will automatically be converted to USD as it comes in automatically, and vice versa.  If you wish to have the funds come in and stay in that specific currency then you can add whatever currencies that you wish to accept into your PayPal account.

New Business Website

Here's how to accept money in a new currency:

Log in to your PayPal account.
Click Currencies under your PayPal account balance.
Open the Select new currency dropdown.
Select the currency you want.
Click Add Currency.
Note:

When you accept money in multiple currencies, you have multiple account balances.
When a buyer sends money in a currency you accept, the money automatically appears in that currency’s balance.
When a buyer sends money in a currency you don’t accept, you’ll be asked to ‘Accept’ or ‘Deny’ the payment.
Your primary currency is the currency that you use to send and request payments.
We appreciate your continued use of the Payflow Gateway and thank you for your business.

Sincerely, 
Cory
Merchant Services
PayPal, an eBay Company

**Comment by ChromeOrange** [comment]
ok, there is a filter you can use to add any currency to the the supported list, can you add this code to your theme functions.php file please - you'll want to place at least one test order to make sure everything works

```
add_filter( 'woocommerce_paypal_supported_currencies', 'custom_woocommerce_paypal_supported_currencies' );
function custom_woocommerce_paypal_supported_currencies( $paypal_currencies ) {
	
	if( $paypal_currencies ) {
		$paypal_currencies[] = 'KRW';
		return $paypal_currencies;
	}
	
}
```

**Comment by mikejolley** [comment]
Snippet must be used until listed on https://www.paypal.com/multicurrency

**Comment by marimbatu** [comment]
우커머스 문제가 아니라, 페이팔 자체적으로 한국(원화)를 지원하지 않아요. 
우커머스에서 아무리 원화 세팅해봐야 페이팔에서 원화로 결제받을 수 없어요.
우커머스에서 원화세팅한다고 해결될 문제가 아니예요.
달라로 결제받는수밖에 없습니다.
