### ISSUE TITLE
Custom attributes of variable products can't change value in the variations

### ISSUE THREAD

**Issue by rocketeer76** [woothemes/woocommerce#7944]
In WooCommerce it’s not possible to change values of the custom attributes within the variants. The custom attributes for the children products are always equal to the parent product. This introduces a problem when the custom attributes has to change for some or all variants.

The solution would be to be able to add custom attributes to each and every variation. If none are added the custom attributes from the parent shall be used as before. Only those custom attributes that are added should change value when the corresponding variation of the parent is displayed in the front-end. All others should be displayed as the parent. It should also be possible to determine the display order of the added custom attributes if they are not present in the parent.

![1](https://cloud.githubusercontent.com/assets/7510893/7120891/db389cbc-e210-11e4-9b58-4fe1cff51926.png)

![2](https://cloud.githubusercontent.com/assets/7510893/7120892/df656af4-e210-11e4-813d-c584e99d67de.png)

**Comment by mikejolley** [comment]
We are not planning on adding variation-level attributes. Attributes are product level only - remember these are also used for the actual attributes of each variation. e.g. color attribute blue, red, assigned to a different variation for each.

ideas.woothemes.com if you want to log an idea for this, however our variation descriptions coming soon may help if you need a variation level-description.

**Comment by rocketeer76** [comment]
I'm aware that attributes are used to create the variations. These attributes would have been excluded. Adding or changing attributes on the variation-level would have been carried out after the creation of the variations. So it would have been easy to exclude those attributes from the drop-down list at the variation level.

Missing this feature makes WooCommerce a bit less advanced. Say you have a t-shirt in two colors. In a product management perspective these two t-shirts might have custom attributes like:

Production code
Manufacturer code
EAN-code

etc. Now you can only distinguish the two colors by SKU. Taking it further in the order confirmation you have to make an extra step to find out e.g. Manufacturer code when you only have the SKU, if SKU is not equal to Manufacturer code. Variation description will not help in this case. But I guess if you want to be a bit more advanced you connect an ERP system and this will be solved mapping SKU to other attributes in the ERP system instead.

Regardless I see variation-level attributes a must for any mature e-commerce system and a feature for WooCommerce core.

Thanks!

**Comment by mikejolley** [comment]
Then I'd suggest putting this on ideas.woothemes.com for feedback :)

**Comment by codesolutions** [comment]
@rocketeer76 did you find anything to solve this issue by yourself? I'm struggling with the same problem and cannot find the solution.

**Comment by rocketeer76** [comment]
No! I didn't find anything. It's added to ideas.woothemes.com.

**Comment by gentleShark** [comment]
splendid idea!!!

**Comment by dfarin** [comment]
Hey, this feature is really important like rocketeer76 already said. Especially for marketing. For Example, u cant use Google Shopping if there is no unique EAN/GTIN for the variation. So i think individual attributes for variations are a must have..

**Comment by mikejolley** [comment]
EAN/GTIN are unique codes, not attributes. I think you're asking for something else here but thinking attributes are the answer. They are not :)

**Comment by Gioware** [comment]
Did someone find anything on this other than WC team excuses of course?!
