### ISSUE TITLE
Orders periodically don't generate emails

### ISSUE THREAD

**Issue by majemedia** [woothemes/woocommerce#7946]
This is the information I have:

2 out of the last 300 orders have failed to get to the point of generating emails.

The similarities:
- Both orders have the following customer notes:
 - `Payment to be made upon delivery. Order status changed from Pending Payment to Processing.`
- Both orders are *missing* the next common note (as seen in my other orders)
 - `Order item stock reduced successfully.`
- There is nothing in my apache error or php error logs during that time period
- I use mailgun for email to which I've enabled (a long time ago) extra logging in case of missed emails but it looks like the code never got to the point of trying to send mail.
- The two order issues have occurred on two different versions of WooCommerce: 2.3.6 & 2.3.7
- No race condition potential since the previous and next order around these were 5 minutes apart
- There's no credit card processing on the site (everything is done via COD gateway)
- No shipping gateway APIs to get in the way (no deliver charge) it's a wholesale site.

The differences:
- The two orders in question did not contain the same products
- The two orders were placed by two different people
- The two orders were placed on different days at different times of the day

I spent a few hour originally with the first order going through code and couldn't get a lead on where the failure might occur since there's nothing in the log.

I'd very much appreciate a lead on this as I can do more thorough testing on my side, but I haven't been able to duplicate the issue at all.

I should also note that these are the only two orders out of 3,416 orders that have failed to send email through not the fault of one of my mail plugins. The previously mentioned error logging I added for Mail Gun was due to some issues they were having at the time with slow emails or emails stuck in their queue which has since been resolved.

**Comment by mikejolley** [comment]
Without steps to reproduce this effectively, or an error, I do not see how this can be looked into our side. 

You need to ensure you have server error logs available + WP_DEBUG_LOG switched on. When this next occurs, check those logs for a clue - be it timeout, memory shortage or actual error message.

https://codex.wordpress.org/Debugging_in_WordPress#WP_DEBUG_LOG

Let us know when you have something we can look at.

**Comment by majemedia** [comment]
Just updating this in case someone comes across it.

This was an issue with **MailGun**, **NOT WooCommerce**. It took a LOT of debugging to discover the issue. Turns out the mailgun plugin would periodically error on request and try to put a WP_Error object through.
