### ISSUE TITLE
Import Sets Positive Stock Qtys, Variations Still Set as Out of Stock

### ISSUE THREAD

**Issue by co50** [woothemes/woocommerce#7947]
I've been reading other issues users have posted regarding the way WooCommerce handles stock quantities....what I found shows inconsistent behavior:

-- In the Admin --
If an item is IN STOCK and Qty is changed from [positive number] to 0, its status is not changed to OUT OF STOCK
but
If an item is OUT OF STOCK and Qty is changed from 0 to [positive number], its status is changed to IN STOCK. 

This is inconsistent and doesn't make sense. If the admin is using stock qtys at all, the stock status should always match up. Alternatively, if the admin doesn't wish to use stock qtys and would rather just use the stock status, they should leave the Qty blank and then WooCommerce would know not to mess with it - it would be manually controlled.

-- Using WooThemes CSV Import Suite --
If an item is IN STOCK and Qty imported is 0, its status is not changed to OUT OF STOCK
and
If an item is OUT OF STOCK and Qty imported is [positive number], its status is not changed to IN STOCK. 

WooCommerce's AI turns off completely with regards to importing. This does not affect actual purchasing on the store since a positive qty will show the items as in stock and a 0 will show them as backordered. But the status is not accurately shown in the admin and any plugins that read the Stock Status rather than Stock Qty will report the item as whatever the Stock Status is rather than looking at the Qty. Sure, they can be programmed to read the Qty instead but for consistency's sake and for the many plugins that do not, shouldn't WooCommerce have logic built in to force a 0 -always- sets Status to Out of Stock and a >0 always In Stock?

So this could be solved three ways:

1) WooCommerce forces stock qty to determine stock status. Then if an admin wants to force something in stock, they can just change the Qty to 1000 or some high number. Done.

2) WooCommerce ignores the qty field if blank. Then if an admin doesn't want to use qty and just wants to set it in or out of stock, they can do so. 

3) WooCommerce create an option in the admin that determines how stock is treated (i.e. (  ) Respect Stock Qty, (  ) Ignore Stock Qty. Logic would then be handled as above based on the option chosen.

**Comment by mikejolley** [comment]
Some stores require control of stock status independently of stock level. Some stores may also want 'out of stock' to be mapped to something other than 0, if they want to prevent over-ordering for example. This is something we decided to include based on Magento in the early days.

The auto-switching of stock status is necessary since an admin isn't going to switch this manually. So that part is based on your stock settings. Also important to note, when backordering is turned on, -ve stock can still be listed 'in stock'. Your solutions could prevent this.

Following on from that, when you're importing *you* control the stock_status. If it was automatically changed to in-stock, you would lose the control and including the column in your CSV would be pointless.

Hope this makes sense. cc @ChromeOrange

**Comment by co50** [comment]
Mike,

Thanks for the response. I guess what I am trying to get across is that implementing options in the admin to account for these scenarios might not be a bad idea. We run a very large e-commerce operation on Woo and we use an import CSV with accurate stock qtys. We tried not including the In Stock field and it simply leaves every items as is. But if we include the "In Stock" column, it means we have to manually set every single variation to in-stock or out of stock when it would be quite beneficial if Woo simple did this automatically. Sure, there are stores that may want Qty 0 to not mean out of stock and I don't know, Qty >0 to mean not in stock (?) but these are the minority of stores. I've been in E-Commerce since 1995, ran many unique operations and have never encountered this, but I certainly agree there are instances where it makes sense.

My point is for stores doing it the common sense way, simply listing the qty in stock in the front-end so end users know how many are available, setting backorders yes/no and setting "low stock" alerts in the admin, WooCoomerce does not accommodate it properly.

All I am saying is that an option in the admin to either do it the current way (Qty does not change the in-stock field) or the more common way (Qty updates in-stock field) would be quite beneficial to a majority of stores using inventory management.
