### ISSUE TITLE
[Unit Test] Failed to install WP Unit Test lib

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#7952]
Failed to install WP Unit Test lib on windows. PHPUnit is installed :worried: 
![capture](https://cloud.githubusercontent.com/assets/3774827/7136045/6333a56a-e2cc-11e4-951c-43449590bbfd.PNG)

`tests/bin/install.sh woocommerce_tests test test`

**Comment by SiR-DanieL** [comment]
I get the same error if i try using WIndows. Using Vagrant and VVV on a linux machine everything works perfectly.

**Comment by claudiosmweb** [comment]
[Bash script](http://en.wikipedia.org/wiki/Bash_%28Unix_shell%29) does not work on Windows, so it will never work.
**Maybe** you can have some luck with [Cygwin](https://www.cygwin.com/)

**Comment by shivapoudel** [comment]
@SiR-DanieL and @claudiosmweb Shifted to [PuPHPet](https://puphpet.com/), installed the PHPUnit and ApiGen via `composer.json` seems to solve me the issue.

**Comment by shivapoudel** [comment]
> Warning: Using a password on the command line interface can be insecure.

@claudiosmweb I had used PuPHPet for Unit Test. Yesterday I didn't got any error but today I have run the `vagrant up` after `vagrant suspend` yesterday night and got this warning. If you have some idea or tip for this can you please help how can I suppressed it.

**Comment by claudiosmweb** [comment]
This is no longer an issue with the WooCommerce.
