### ISSUE TITLE
Shipping costs not shown when negative (refunds)

### ISSUE THREAD

**Issue by Spreeuw** [woothemes/woocommerce#7953]
when using `$order->get_shipping_to_display()` for refunds, it never displays the cost (negative) because it checks if the value is bigger than 0:

```php
if ( $this->order_shipping > 0 ) {
```

**Comment by mikejolley** [comment]
In the backend it shows like this: https://dl.dropboxusercontent.com/s/ssag0xpmos92163/2015-04-17%20at%2010.45%202x.png?dl=0

Frontend: https://dl.dropboxusercontent.com/s/wuqk6599kafzaq6/2015-04-17%20at%2010.45%202x%20%281%29.png?dl=0

There does not seem to be a need to show negative values - they are not shown anywhere.

**Comment by Spreeuw** [comment]
Well it does make sense. Just as `$refund->get_formatted_order_total()` returns an amount, I think it should also return an amount when using `$refund->get_shipping_to_display()`. Why should refunds be different in this aspect?

Note that I am not using this function directly, but when retrieving the totals using `$refund->get_order_item_totals()`, the shipping cost (which created by the aforementioned function) is omitted completely.

**Comment by mikejolley** [comment]
If you want to submit a pull request for us to review (so you can check it works as intended) go right ahead.
