### ISSUE TITLE
Cart function for themes 

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#7954]
Currently the code we use for our themes to display the cart count/totals in our theme's header do not update when on the cart/checkout pages e.g.

![](https://dl.dropboxusercontent.com/s/g2v7zsjp3tpy1sd/2015-04-14%20at%2013.32%202x.png?dl=0)

![](https://dl.dropboxusercontent.com/s/cvdsvzy5lyn4q8m/2015-04-14%20at%2013.34%202x.png?dl=0)

What about a function that can be used in this area that would update when the totals change e.g., address is changed or shipping method is updated

**Comment by mikejolley** [comment]
Updating other areas in the checkout sounds like a large/slow task - I think in the above case Coquette should be hiding the cart widget during checkout. Once you're checking out, you don't need the distraction or widget, and values will always change once taxes and user location are added. cc @jameskoster
