### ISSUE TITLE
Need Password Strength Improved

### ISSUE THREAD

**Issue by balance-global** [woothemes/woocommerce#7956]
It is essential in the day and age that on the Woocommerce buyer registration form that the password setting field has the following 

- Strength Meter
- Minimum number of characters of 8
- Upper and lower case plus one non text or numeric charactor

At the moment a customer can set their account password with the just one charactor. To be honest this is an open inviatation to get hacked. Please Please can someone make this simple fix /improvement.You guys above all bearing in mind your transactional related work should realise this is a key issue which needs to be fixed.

**Comment by claudiosmweb** [comment]
There plugin to do what you want: https://wordpress.org/plugins/woocommerce-enforce-strong-password/

**Comment by balance-global** [comment]
i have tried this. it does not work

**Comment by balance-global** [comment]
AT ALL

**Comment by balance-global** [comment]
It only works on Admin passwords and is not applied to the Registration Password field at checkout. I am really concerned that you guys are taking this seriously. Which is very very very shocking. This is a serious security breah. I am so concerned about the lack of concern even though this could threaten your business through user accoutn hacking I am thinking of wiritng a few blog articles about this. Its frankly a real SHOCKER !!

**Comment by Kenshino** [comment]
Not everyone uses WooCommerce as a full fletched e-commerce system, eg - password strength, meters and what not might not be a big deal to a store owner who only processes cash payment for booking services.

Security is definitely important, but this can be easily done by the developer who uses WooCommerce to create an e-commece store.

Adding it to core is a serious consideration. Not one that can be helped by your dramatic antics. Provide a pull request and I'm sure the team will consider it fairly

**Comment by balance-global** [comment]
Nope but many do. Security is a big consideration these days. If your product was to be underminded by hackers you would have some serious publicity to have to contend with. Anyway not going to have a battle with somehting that should be in your commercial interests to fix. Still amazed at this when WPLMS which bundles your software in their theme have users taking 25,000 course members a year and you regard them as unimportant for such a simple change. I will creaty a PULL request but supprised I have to do this. I am going back to the WPLMs forum to feed all this back to the community. Still very surprising.

**Comment by claudiosmweb** [comment]
@balance-global fell free to submit a pull request or create a new plugin for it.

**Comment by claudiosmweb** [comment]
I'm starting a plugin for it https://github.com/claudiosmweb/woocommerce-password-strength-meter
