### ISSUE TITLE
WooCommerce Does not use user_identity from current_user

### ISSUE THREAD

**Issue by cancan101** [woothemes/woocommerce#7958]
`get_currentuserinfo` sets  on `current_user` a `$user_identity` [(User's name, displayed according to the 'How to display name' User option (since 3.0))](https://codex.wordpress.org/Function_Reference/get_currentuserinfo) but this does not seem to be used by WooCommerce when showing the users addresses.

**Comment by claudiosmweb** [comment]
In users addresses when get the customer name from the address...
In this cache need to show the name of the billing or the delivery address and not the user name.
In addition, the customers do not have access by default to `wp-admin`, making it impossible to configure the "Display name" option.
