### ISSUE TITLE
WooCommerce Pre Orders 1.4.1 Cannot Change Release Date

### ISSUE THREAD

**Issue by Darfuria** [woothemes/woocommerce#7960]
When attempting to change the release date of a product at `/admin.php?page=wc_pre_orders&tab=actions&section=change-date` the product release date is not updated, and neither is the availability_date for the pre-orders.

When I attempt to change the release date, the page just reloads and the URL changes to `/admin.php?page=wc_pre_orders&tab=actions&section=change-date&success=?phpechoesc_attr(current_section);?`

**Comment by claudiosmweb** [comment]
This forum is for issues with WooCommerce core only.
Please contact the WooThemes support to talk about premium extensions: https://support.woothemes.com/hc/en-us/articles/203112147-How-to-Get-Help
