### ISSUE TITLE
Wordpress / woo commerce theme development - query.blockUI.js causing infinite loading on checkout page approximately resolved

### ISSUE THREAD

**Issue by charlyox** [woothemes/woocommerce#7963]
I spent the last 48 hours trying to resolve an in-understandable trouble on my website. I am posting this because I found the solution, even if this solution does not satisfy me completely.

I am developing a marketplace website along with woo commerce, the toolset suite, and with my own toolstrap-based theme.

When logged in as an admin, everything worked fine: after cart, the checkout page would display correctly and I could chose my mean of payment.

When not logged in, this checkout page would display an infinite spinner forbidding me to access this payment choice. 

- I tried all the trouble shooting, that is deactivating all my plugins, activating them one by one. Nothing. Then after changing to twenty fifteen it worked.

Gosh. It comes from my theme then.

I scanned my theme files for any problematic instruction, including possibly problematic script calls. Still had the issue.

I found a topic on the WordPress forum (thanks to @nonick80) saying some trouble might come from the jQuery.blockUI.js. I downloaded the latest version of this script on GitHub, and replaced it in the  woo commerce plugin. 

This solved my problem.

Obviously I am not totally happy with that for my next woo commerce update might be problematic except if I do the same operation.

That's why I wanted to post this thing here, for somebody might indicate me what is missing in my WP theme for it to work correctly with woo commerce.

Have a good day.

**Comment by mikejolley** [comment]
@charlyox WooCommerce core uses 2.70.0-2014.11.23 - this is the identical version to that on github.

**Comment by charlyox** [comment]
Hello @mikejolley, thanks for your answer,  
I tested again and found (thanks to you) that my bug is still here with the github version... Back at the start for me... The only way to get rid of this bug is to get rid of jQuery-blockui! That's what I did for a short-term fix. 

Any way the minified version seems to be a little smaller: 
* Block-ui-min:
** Woocommerce: 9555 Bytes
** Github: 9262 Bytes

Do you know if getting rid of BlockUI may induce any  unwanted client side behavior? For the moment my site doesn't seem to miss anything... ;-)

Thanks again
Charles

**Comment by mikejolley** [comment]
Have you actually ruled out your theme, or plugins yet? Because I would start there and see whats triggering it. If you also check your error console when it freezes up (in chrome, View > Developer > Console) this will give you more info.

Block UI will be needed to prevent people clicking during ajax updates of fields.
