### ISSUE TITLE
Checkout Email field is NOT set to 'type=email' to support mobile devices

### ISSUE THREAD

**Issue by mintyh** [woothemes/woocommerce#7964]
Would it not make sense for the Email field in the Checkout page to be set to "type=email" (rather than type=text) so that the keyboard with the @ symbol pops up on mobile devices, to make entry easier?

It seems silly to make those customers have to go through more hassle with their onscreen keyboards than necessary.

Any chance of that small change being implemented?

**Comment by slash1andy** [comment]
Hey there Minty! 

I would recommend that you submit a Pull Request for this :)

**Comment by mintyh** [comment]
I have no idea how to do this.


On 16/04/2015 4:51 p.m., Andrew Wikel wrote:
>
> Hey there Minty!
>
> I would recommend that you submit a Pull Request for this :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/woothemes/woocommerce/issues/7964#issuecomment-93640258>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by claudiosmweb** [comment]
This already ready for version 2.4 which will be released in a few months.
