### ISSUE TITLE
i cant replace image

### ISSUE THREAD

**Issue by Dewilas** [woothemes/woocommerce#7968]
there is my issue, pls help

http://stackoverflow.com/questions/29646900/how-to-add-image-woocommerce-api

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
