### ISSUE TITLE
[Woocommerce Api v2] Create an order with coupon =>Wrong Totals

### ISSUE THREAD

**Issue by bzhvince** [woothemes/woocommerce#7969]
Hi,

I create an order with coupon through the REST API v2 : 
{
 "order": {
 ...
        "coupon_lines": [
            {
                "code": "foc",
                "amount": "34.90"
            }
        ]
 ... 
 }
}

The coupon is taken into account and I can see it in the order but it has no effect on the totals calculation.
The order discount should be at 34.90 and the total should be decremented of the discount amount?

Vincent

**Comment by claudiosmweb** [comment]
@mikejolley I need your help here.
We have this https://github.com/woothemes/woocommerce/blob/30d2ab8af8474302c60c398f7e1cea78dc02f20a/includes/abstracts/abstract-wc-order.php#L783-L784
But not any coupon is calculated.
Also not been able to find a method to calculate anything from coupons.

**Comment by mikejolley** [comment]
There are no backend/api methods for automatic coupon calculation. This would need to be applied manually to the product line items by setting their subtotals/totals. Related https://trello.com/c/OPEAzgIw/4-allow-coupons-to-be-added-edited-from-orders-with-discount-calc-4404
