### ISSUE TITLE
Error in reports with partial refunds

### ISSUE THREAD

**Issue by lobotomiatbm** [woothemes/woocommerce#7972]
I have an issue regarding the refund feature and reports

When a partial refunds is done in a order, the reports show erroneus data, if status is "refunded" it show total import as refunded, then if status is "completed" it show an erroneus value.

**Comment by mikejolley** [comment]
Screenshots? Examples? More info would be welcome.

An order with status refunded is considered 100% refunded regardless of any partial discounts inside.

**Comment by lobotomiatbm** [comment]
This is report for last 7 days ![ottodame-report-errato](https://cloud.githubusercontent.com/assets/11996303/7235874/88ad77e8-e791-11e4-9678-9d7ec3309759.png)
But really (partially) refund is 872 euro.

All is ok whit completely refunded (with status refund), but not with partially refunded, with any status.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/a2a0e6f10d23e60127a800293c56113a713b1de3

**Comment by lobotomiatbm** [comment]
There is already a problem. Now Are reported only refunds when month of order and month of refund is the same.

Example:
I have received 2 order in march and 1 in april. 
Refund of march's order are of 274 + 249 euro.
Refund of april's order are 349 euro.
I have partially refunded this 3 order in april.

In report i see only 349 euro of refund.

**Comment by mikejolley** [comment]
@lobotomiatbm I added fixes above - I assume you are not running the new code yet as its unreleased.

**Comment by lobotomiatbm** [comment]
@mikejolley i have already fix by manually edit of includes/admin/reports/class-wc-report-sales-by-date.php

**Comment by mikejolley** [comment]
Can you illustrate the issue better? Difficult to see whats happening when numbers are thrown at me :)

**Comment by lobotomiatbm** [comment]
Ok, i try to explain to you (eith my poor english)

If refund is complete (with status refund) all is ok.
If refund is partially (with status complete), if order date and refund date is in the same month, it is reported graph, but if order date and refund date are in different month, it is not reported to graph.

Is clear now?

**Comment by mikejolley** [comment]
Partial refunds should be reported in the month they were granted. So if I had an order in January, and refunded it in February, I would see that refund in February reports.

**Comment by mikejolley** [comment]
I see some issues around fully refunded orders. I will create a new issue - this is quite complex.

**Comment by lobotomiatbm** [comment]
@mikejolley  i know that Partial refunds should be reported in the month they were granted, but it works only if refunds month and order month is the same.

**Comment by lobotomiatbm** [comment]
Any news about this?
