### ISSUE TITLE
REST API does not fetch attribute "product_url" even for products of type external

### ISSUE THREAD

**Issue by dealsheep** [woothemes/woocommerce#7974]
Hello there,

We are trying to use the REST API to power a mobile app to go along with our website.

Most our products are from the affiliate/external type because we send the users to partner websites to complete a purchase.

For some reason the attribute "product_url" that contains the link we need in the app is not fetched. In case this matters, the API even correctly sends back "type" : "external", for which the product_url should be relevant.

Any ideas?

**Comment by claudiosmweb** [comment]
Will be available in WooCommerce 2.4.

**Comment by dealsheep** [comment]
Thanks claudio, that is great news.
