### ISSUE TITLE
Product coupons applied even when specific products are not in cart

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#7975]
To recreate:

1. Add new Product % Discount coupon for a specific product (http://cld.wthms.co/1aNzC)
2. Add a different product to your cart
3. Apply coupon in cart (http://cld.wthms.co/1ag3c)

I understand that the coupon remains attached to the cart, so the discount will apply correctly if I add the coupon-specific product afterwards, but I think it's confusing. Perhaps there should be a message that says "Coupon is not applicable to the products in your shopping cart" ?

**Comment by roykho** [comment]
@MindyPostoff is this related?  https://github.com/woothemes/woocommerce/issues/7936

**Comment by MindyPostoff** [comment]
@roykho it is indeed the exact same issue. Good to know it's been fixed  :)
