### ISSUE TITLE
Shipping calculated before discounts

### ISSUE THREAD

**Issue by l3hworks** [woothemes/woocommerce#7977]
In the core Woommerce functionality you don't get to actually manage cart price based shipping methods, but there's several plugins like "Table Rate Shipping" out there that does it, and all of them seems unable to get around this limitation.

Right now the only solution we have is to advertise our coupons as discounts in both the product and shipping in products until X price (and simply lose money), and only on product after Y price. Which is not really a solution but just a compromise...

Calculating shipping before discounts can be a good option for some cases but that should be entirely optional and certainly not the default option in my opinion.

**Comment by mikejolley** [comment]
I don't understand the issue/what product the issue surrounds? calculate_shipping runs after discounts so a plugin could calc the after-discount amount if it wanted to.

**Comment by mikejolley** [comment]
related https://github.com/woothemes/woocommerce/issues/8020
