### ISSUE TITLE
Please extend note about language codes on transiflex

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7979]
Currently the description is:

> Here you can contribute localisations to WooCommerce. Please when requesting a translation, ensure you use the WordPress codes from http://wpcentral.io/internationalization/ e.g. es_ES (Spanish Spain) over just es.

Could this be extended to:

> Here you can contribute localisations to WooCommerce. Please when requesting a translation, ensure you use the WordPress codes from http://wpcentral.io/internationalization/ e.g. es_ES (Spanish Spain) over just es.
> 
> There is one exception to this rule:
> - de_DE (German (Germany)) is the formal "Sie" variant of German
> - de (German) is the informal "du" variant of German

Actually I think it is even more then one exception here, because there is [Finnish](https://www.transifex.com/projects/p/woocommerce/language/fi/) and [Finnish (Finland)](https://www.transifex.com/projects/p/woocommerce/language/fi_FI/) on transifex, too. And both are translated by 100%. I think you should ask the finnish translators what's this about.

Unfortunately, it is not possible to add descriptions or notes on the lower language levels. And I think it is good to have such notes available *on site* because otherwise people really easily mess up translations because they do not know better.

**Comment by glueckpress** [comment]
+1
