### ISSUE TITLE
Very delayed "undo dialog" after removal of product form mini cart popup 

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7980]
The `<product> removed. Undo?` seems to be stored for very long time.

**Steps to reproduce:**
1. Go to http://demo2.woothemes.com/storefront/product-category/clothing/hoodies/ and add a few products
2. Click on the blog (any non-product page) at http://demo2.woothemes.com/storefront/blog/
3. Hover over mini cart and remove items while you're on a non-product page
4. Stay whithin any blog pages, and browse through these
5. Eventually - after some time - return to a shop page, e.g. on the menu Shop > Clothing > T-shirts at http://demo2.woothemes.com/storefront/product-category/clothing/t-shirts/

Then with a lot of delay the undo messages show up:
`Ninja Silhouette removed. Undo?`

**Suggested behaviour:**

Either

*  show the "Undo" dialog immediately, e.g. also on blog pages that is immediately after removal in step 3 

or (if that's technically not possible then)

* If not on a product/shop page while removing an article from cart, then do not show the "Undo" dialog. That is, do not save the "state" here.

**Comment by mikejolley** [comment]
Notices are stored in the session and are kept until they are output. A notice output function or shortcode would need adding to other page types - this cannot be done consistently for all themes.

Pinging @jameskoster to add this to storefront.
