### ISSUE TITLE
Add a filter in the admin profile meta field

### ISSUE THREAD

**Issue by maksbd19** [woothemes/woocommerce#7985]
In this page  woocommerce/includes/admin/class-wc-admin-profile.php on line 179 the user meta data is directly printed on. I think we should have a filter in this place to allow plugins to filter the data is printing.

**Comment by mikejolley** [comment]
This data is printed as-is because it is editable. If it were filtered, you would not be editing the value as-saved.

If you have a different use case that requires this, send a pull req if you want with more details + justification. We will review it.
