### ISSUE TITLE
Order Status doesn't change

### ISSUE THREAD

**Issue by agikluffy** [woothemes/woocommerce#7986]
I have woocommerce website and i want change order status via Rest API. I use client lib https://github.com/kloon/WooCommerce-REST-API-Client-Library to call my Rest API.

When i call API with GET method (ex. view order, get single order), it work correctly. But, when i call API with POST/DELETE method (ex. update order status , delete order), it not running well.

Anybody has idea why this is happen? And from where I must check?

Thanks and forgive me for bad english.

**Comment by claudiosmweb** [comment]
This is not the forum of https://github.com/kloon/WooCommerce-REST-API-Client-Library
Here our Rest API Docs http://woothemes.github.io/woocommerce-rest-api-docs/
