### ISSUE TITLE
Refund Button not working with Simplify Commerce

### ISSUE THREAD

**Issue by jeffro84** [woothemes/woocommerce#7989]
A few customers have placed duplicate orders, so we have wanted to refund the extra order.  The order details screen has a refund button, but when an amount is entered to refund and "Refund with Simplify Commerce" is selected, the call fails.  Perhaps there is some sort of API issue?  Checking out works just fine and transactions show up in WooCommerce, but this functionality is not working.

**Comment by mikejolley** [comment]
@claudiosmweb can you check this?

**Comment by claudiosmweb** [comment]
Tested and works fine!

Order items in WooCommerce:
![screenshot from 2015-04-24 15 29 52](https://cloud.githubusercontent.com/assets/1264099/7325730/c7de54e8-ea96-11e4-9db4-eb647310179c.png)

Payment details in Simplify Commerce dashboard:
![screenshot from 2015-04-24 15 30 25](https://cloud.githubusercontent.com/assets/1264099/7325746/e2f4cc4e-ea96-11e4-8454-1d51f356474f.png)
