### ISSUE TITLE
breadcrumb : translation improvement

### ISSUE THREAD

**Issue by PM33** [woothemes/woocommerce#7997]
Hi There, 
Some expression are not automatically translated or not provided in POT file. for example : 
File : \wp-content\plugins\woocommerce\templates\global\breadcrumb.php OR woosidebar.php
Line 72 : 'Products tagged &ldquo;'
Line 100 : 'Search results for &ldquo;' 
Any idea?

**Comment by claudiosmweb** [comment]
We dont have an `woosidebar.php` file in WooCommerce and translations are in Transifex: https://www.transifex.com/projects/p/woocommerce/
