### ISSUE TITLE
Drag & drop variations won't work after attribute edit

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#7999]
Steps to reproduce: 
1. edit a variable product that already has variations 
2. go to Attributes, then Save Attributes (doesn't matter if you actually add or remove any) 
3. click to the Variations tab and attempt to drag and drop reorder variations. (it will not work)

Once you update the product and the page refreshes, drag and drop variations work again.

**Comment by mikejolley** [comment]
Since these are being refactored in 2.4 and its minor, I have moved the issue to https://github.com/woothemes/woocommerce/issues/6995
