### ISSUE TITLE
single-product.js conflicts with bootstrap

### ISSUE THREAD

**Issue by whatthefork** [woothemes/woocommerce#8000]
In the single-product.js file there is code like this to hide product tab panels:

```
	$( '.woocommerce-tabs .panel' ).hide();

	$( '.woocommerce-tabs ul.tabs li a' ).click( function() {

		var $tab = $( this ),
			$tabs_wrapper = $tab.closest( '.woocommerce-tabs' );

		$( 'ul.tabs li', $tabs_wrapper ).removeClass( 'active' );
		$( 'div.panel, $tabs_wrapper ).hide();
		$( 'div' + $tab.attr( 'href' ), $tabs_wrapper).show();
		$tab.parent().addClass( 'active' );

		return false;
	});
```

This is in place to hide product info tabs, which is fine. Except that as you can see it will hide any div with a class of "panel" when that element is inside a panel - such as the product description panel. Interestingly enough, the widely used Bootstrap framework has a panel component that uses the panel class name. So if a Bootstrap panel is embedded into a product description tab then clicking a product info tab hides it - and any other divs with that class. 

The jQuery selector is far too broad. Please narrow the scope on that so that it only pertains to the product tabs.  Something like will work:

```
	$( '.woocommerce-tabs .panel.entry-content' ).hide();

	$( '.woocommerce-tabs ul.tabs li a' ).click( function() {

		var $tab = $( this ),
			$tabs_wrapper = $tab.closest( '.woocommerce-tabs' );

		$( 'ul.tabs li', $tabs_wrapper ).removeClass( 'active' );
		$( 'div.panel.entry-content', $tabs_wrapper ).hide();
		$( 'div' + $tab.attr( 'href' ), $tabs_wrapper).show();
		$tab.parent().addClass( 'active' );

		return false;
	});
```

Thanks!

**Comment by whatthefork** [comment]
Hi, check your related CSS too, it also has definitions that are too broad for the WC product tabs. For example, it enforces a bottom border on any UL list inside the product description. Please remedy that. Thanks!

**Comment by AminulBD** [comment]
This problem is still now in latest version of woo commerce.

If i used bootstrap panel inside woocommerce tab then i automatically add "display:none"

here is example: 
![screenshot-panel](https://cloud.githubusercontent.com/assets/5006546/7720156/d832e0c0-feeb-11e4-95bf-931181ca77ad.png)
