### ISSUE TITLE
upgdarte from 2.1 to 2.3 crash wordpress

### ISSUE THREAD

**Issue by cosmospuglisi** [woothemes/woocommerce#8004]
Hi all,

trying to upgrade the plugin woocommerce from 2.1.12 to 2.3.7, the wordpress admin and wordpress itself become unreachable. rolling back the db I can acces the wordpress, but for the full site I need to rollback the plugin dir too. 
BR
cosmos

**Comment by roykho** [comment]
Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

**Comment by ChromeOrange** [comment]
@cosmospuglisi check your error logs, that will tell you where any problems are, make sure your theme and plugins are up to date
