### ISSUE TITLE
Admin order page load billing/shipping data limit

### ISSUE THREAD

**Issue by des79** [woothemes/woocommerce#8005]
Hi everybody,

I would like to compile custom user data on new order page but I think there is a limit when we click on load billing address button. 

I can filters data via woocommerce_found_customer_details but my custom data is not used to compile billing input why load_billing method (meta-boxes-order.js) has a fixed jquery selector.

I think is better use a loop function over json response like this

$.each(info, function(k, v) {
	$( 'input#_'+k ).val(v).change();
});

So we can load billing custom data.

What do you think?

David

**Comment by des79** [comment]
Or trigger a jquery event passing info object so we can use our function to load data

**Comment by claudiosmweb** [comment]
@des79 you can just do like me: https://github.com/claudiosmweb/woocommerce-extra-checkout-fields-for-brazil/blob/master/assets/js/admin/write-panels.js#L10-L60
Show a new dialog and copy the fields that you need.

If you believe you have a better way to do this, feel free to send a Pull Request.

**Comment by des79** [comment]
Thank you Claudio, 

With your code we load ajax request and db call twice. I think is better a code like this (I share this if someone need it)

$( 'button.load_customer_billing' ).on( 'click', function () {
	$( document ).ajaxComplete(function(event, request, settings) {
		$.each($.parseJSON(request.responseText), function(k, v) {
			if($( 'input#_'+k ).val() == '') // set value only if is empty (custom data purpose)
				$( 'input#_'+k ).val(v).change();
		});
		$(event.currentTarget).unbind('ajaxComplete');
	});
});

With this code we avoid to call woocommerce_get_customer_details twice and we can use ajax response.
