### ISSUE TITLE
Search bar ignoring product tags, odd behavior

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#8006]
Ticket reference: https://woothemes.zendesk.com/agent/tickets/284089

The client is selling t-shirts on their site. When a user searches "t-shirt", the products listed fine - all 10 of them. However, when a user searched for "t-shirts", it gave no results, even though the plural was a tag.

The solution was to go into each individual t-shirt and in the short description instead of using "shirts", I used "t-shirts". 

I don't know if this is expected behavior from the search, but it definitely seems like a big inconvenience - wanted to make sure it was known!

**Comment by mikejolley** [comment]
WordPress searches on titles + content, not term names. The style of search is %term%, so t-shirts would not match t-shirt. This can be extended by plugins.
