### ISSUE TITLE
WooCommerce Refund Reporting Error

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#8010]
### Scenario 1: Refunding by line items

If I do a line item item wise refund; the amount refunded is automatically calculated. The reports screen shows a number way higher than the amount refunded on the "Refunded" bar graph:

1. Initial Order: ![](http://cld.wthms.co/1j5LJ+)

2. Initial Report, everything looks good: ![](http://cld.wthms.co/1i9lz+)

3. Line Item wise refund: ![](http://cld.wthms.co/1lsnD+)

4. After performing the Line Item wise refund: ![](http://cld.wthms.co/1jehD+)

5. Revised Reports for the last 7 days after issuing the refund: ![](http://cld.wthms.co/1jDMq+)

If I do a refund on the total and not on the individual items, then the report section of WooCommerce shows that NO REFUNDS were given, however the total store sales is correctly calculated and no bar graph for refunds is shown.

### Scenario 2: Refunding on Whole order

1. Initial Order in the Backend: ![](http://cld.wthms.co/19xh1+)

2. Initial Report for the above order: ![](http://cld.wthms.co/eTsE+)

3. After completing the Manual Refund on the Order total: ![](http://cld.wthms.co/6F7G+)

4. Reports for last 7 days refreshed after above refund: ![](http://cld.wthms.co/8p2i+)

@ChromeOrange @mikejolley @ABDpromotions

**Comment by lobotomiatbm** [comment]
I already have problem with refund, partial refund are not correctly counted.
