### ISSUE TITLE
PayPal Standard Form Submission Method?

### ISSUE THREAD

**Issue by vicky081** [woothemes/woocommerce#8015]
Hi,

In my client side they using old version of woocommerce, and i recently updated woocommerce to latest and seems everything working fine, except one problem, previously they select "Use Form Method " in paypal standard, but now with latest version i couldn't see that option which is available, can you please explain me where it is ? Is that option is deprecated? or it is the bug?

Thanks in advance.

**Comment by mikejolley** [comment]
Not required; we do the redirect using a querystring now.

**Comment by vicky081** [comment]
Thanks for your info, is there any alternate or any hook avail to support again form submission?

**Comment by mikejolley** [comment]
There is really no need. They do exactly the same job.
