### ISSUE TITLE
Minimum order amount for Free Shipping calculated before coupon

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#8020]
Let's say that Free Shipping is available for orders where the minimum amount is $50. If a customer adds $80 worth of products to their cart, they'll get the option for Free Shipping. However, if the customer applies a coupon code for 50% off, their total is now $40, and below the minimum order threshold amount.

Currently, it looks as though WooCommerce calculates the product total and bases the availability of the Free Shipping method on that amount. However, I wonder if it makes more sense to have that shipping method look to the overall shipping total (discounts included).

**Comment by mikejolley** [comment]
Since we dumped after-tax discounts we can do this now I guess (https://github.com/woothemes/woocommerce/issues/3522).

**Comment by abjetz** [comment]
Thanks guys, any idea when we could have a fix/update for this one?

**Comment by MindyPostoff** [comment]
@abjetz - our developers have added it to the 2.4 milestone, so we'll be trying to include this in in the WooCommerce 2.4 version. At this point, we're still not sure when we'll be releasing this update, but you can keep up to date with all of our development news for WooCommerce here: http://develop.woothemes.com/woocommerce/

Thanks  :)

**Comment by mikejolley** [comment]
Strange. just went to build this and we already do it. Is available is based on 'cart_contents_total'. This is after discount.

Confirmed working in master/2.3.

**Comment by russoanthony** [comment]
Has this been implemented?  I'm still seeing Table Rate Shipping calculated on subtotal.

**Comment by taysa** [comment]
I have this same issue, woocommerce doesn't include discount based on payment gateway for the shipping calculation. I tried plenty of discount plugins but none is able to solve the problem, so I think woocommerce shipping calculation is the point. Is it possible to provide a snippet to deal with it? thank you

**Comment by huykon** [comment]
How to get minimum order amount for free shipping in woocommerce checkout page ?
I have used: 
`$free_shipping_settings = get_option( 'advanced_free_shipping_settings' );
$min_amount = $free_shipping_settings['min_amount'];`
but it return NULL result. what is that error and how to fix it ?

**Comment by b-nik** [comment]
> Strange. just went to build this and we already do it. Is available is based on 'cart_contents_total'. This is after discount.
> 
> Confirmed working in master/2.3.

@mikejolley I can't seem to find an option to do this, when creating a shipping rule. There' s only the "Order Subtotal" option which takes the coupon into account for the shipping rule. Maybe the feature was removed since this old issue?
