### ISSUE TITLE
WC 4.2 Issue with List Tables

### ISSUE THREAD

**Issue by bolderelements** [woothemes/woocommerce#8022]
I have extended the WP_List_Table class to work within a few places in my WooCommerce settings. After upgrading to WordPress 4.2, my tables stopped populating. I discovered that when I add var_dump( $this ) to my table's constructor, it returns the WooCommerce class, not my list-table's class.

Any ideas why I suddenly cannot do this anymore?

**Comment by bolderelements** [comment]
Never mind. Much confusion between WP support and my own haste. A poor coding job did not meet up to some of their new requirements so it stopped working.

**Comment by claudiosmweb** [comment]
xD
