### ISSUE TITLE
just update to woocommerce 2.3.8 missing subsequent pages navigation under reports section in admin

### ISSUE THREAD

**Issue by jeasysehgal** [woothemes/woocommerce#8023]
Hi Guys,

Jeasy from www.Imperialswords.com here. Just updated to the latest version of woocommerce, Everything seems to be working fine apart from a few issues.

1. The coupon issue still exists as in if you make a coupon with product % and put not valid for on sale items and put a price value for minimum amount, it doesn't apply on any products, Untick the not valid for on sale items option and the coupon works but applies the discount on all items on sale or full price. We've submitted this bug since Version 2 onwards.

2. Went to the admin section under Woocommerce>Rports>Stock>Low Stock. There are currently 120 stock with status out of stock, he reporting section shows up with about 20 products and then we can't access the subsequest pages as the next page navigation is missing. I think, It just needs to be activated. Can you please help with this fix, No idea trying to do inventory when you can't access the entire inventory and just stuck on one single page.

Thanks and looking forward to a quick fix.

Jeasy Sehgal

**Comment by jeasysehgal** [comment]
Just tried de activating all plugins but woocommerce, switched to twntytwelve theme and same thing. Inface the pages navigation is missing all all reporting sections. Really need the fix for this as I can do inventory if I can't access the pages and stock. Going and doing it through the product page defies the purpose although that what we have to do now. Have a big stock take coming up.

Also can we please have a fix for the coupons... We cant use them as they are not working correctly at the moment.

Thanks.

**Comment by mikejolley** [comment]
1.
Coupon options: https://dl.dropboxusercontent.com/s/ncjv8im33zfhpj0/2015-04-24%20at%2011.46%202x.png?dl=0
Coupon options2: https://dl.dropboxusercontent.com/s/sw1t2yyd3k36eeq/2015-04-24%20at%2011.47%202x.png?dl=0
Result: https://dl.dropboxusercontent.com/s/zbps1nwt45gfk0g/2015-04-24%20at%2011.47%202x%20%281%29.png?dl=0

No issue with coupons.
