### ISSUE TITLE
Can not remove product from the shopping cart, if language is set to Greek

### ISSUE THREAD

**Issue by AgentGod** [woothemes/woocommerce#8025]
Hi, 
on the latest release there is a strange bug. When the language is set to Greek and translation files in Greek  for woocommerce are downloaded, it's not possible to remove product from the shopping card anymore. 
When the language in WP is set to something else, lets say Bulgarian, the problem disappears. 
The problem appears only when the Greek translations for Woocommerce are downloaded.

**Comment by mikejolley** [comment]
Download the new po/mo from https://www.transifex.com/projects/p/woocommerce/ There was a missing %s which was breaking it.

**Comment by AgentGod** [comment]
Hi, 
I have downloaded the new po files and the problem is still there.
Can you tell me which string cause the problem?

**Comment by mikejolley** [comment]
`"%s removed. %sUndo?%s"`

**Comment by AgentGod** [comment]
Sorry Mate, it was my mistake, I did not uploaded the .mo files.
Problem is solved.
