### ISSUE TITLE
Show the welcome page for major updates only - not for point releases

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8026]
Moving this to major update since the rewrite flush code also needs a rework.

**Comment by bryceadams** [comment]
🎉

**Comment by bradt** [comment]
:+1:

**Comment by growdev** [comment]
::throws flowers at @mikejolley ::

**Comment by mikejolley** [comment]
Taken care of in the branch for https://github.com/woothemes/woocommerce/issues/7829
