### ISSUE TITLE
Invalid "What is Paypal" URL

### ISSUE THREAD

**Issue by polp6880** [woothemes/woocommerce#8030]
Hello!

I just noticed that if you have paypal as one of the payment methods selected, on the Checkout page the "What Is Paypal" link URL is going to https://www.paypal.com/mt/webapps/mpp/paypal-popup - which is showing what seems to be a 404 page. Can an alternative URL be introduced?

Bdw, i'm using woocommerce version 2.3.8

Thanks!

**Comment by polp6880** [comment]
Works perfectly. Thanks!

**Comment by noskule** [comment]
I have still this problem with
* Version 2.3.8
* Language: German
* Country: Switzerland

Should I oben another issue or is this post ok?

**Comment by claudiosmweb** [comment]
@noskule Best open a new one, but I've just fix anyway.

**Comment by noskule** [comment]
@claudiosmweb thanks. So I guess this will be fixed within the next update? You sure I have to open a Issue if you allready fixed it?

**Comment by claudiosmweb** [comment]
@noskule I'll be fixed for WooCommerce 2.3.9 (this week, maybe...)

**Comment by dk9** [comment]
Hi there, I also have this problem. Running:

Version 2.3.9
Language: Hebrew
Country: Israel

The link leads to: https://www.paypal.com/il/webapps/mpp/paypal-popup 
and its a dead link \:
Any solution for that, or how I change it manually?

Thanks :)
