### ISSUE TITLE
[API] Get/create/edit/delete attributes

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#8031]
We need something to be able to create attributes for the API.
Today you can only create terms within an attribute, but can not create the attribute.

Ref: #7825

**Comment by Dewilas** [comment]
@claudiosmweb how to delete product variations?

**Comment by claudiosmweb** [comment]
@Dewilas reading the docs and not asking questions in the wrong place ;)

**Comment by Dewilas** [comment]
@claudiosmweb sorry, but i cant found in API docs how to delete product variations.

**Comment by Freshclicks** [comment]
@claudiosan will this change allow those global attributes to be assigned to products as apposed to product specific attributes?
