### ISSUE TITLE
VARIABLE PRODUCTS NOT WORKING PROBABLY. 

### ISSUE THREAD

**Issue by Jojiss** [woothemes/woocommerce#8036]
ADD TO CART BOTTOM IS DISAPPEARED FOR VARIABLE PRODUCTS

**Comment by roykho** [comment]
Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com
