### ISSUE TITLE
Attributes Error message not formatted

### ISSUE THREAD

**Issue by ibndawood** [woothemes/woocommerce#8040]
When adding an attribute with a reserved term, the error message displayed is not formatted. 

Steps to reproduce the error : 

1. Navigate to Products > Attributes
2. Try adding a reserved attribute name like "author".
3. The error message displayed is something like this : 

``Slug "%s" is not allowed because it is a reserved term. Change it, please.``

Screenshot Reference : https://docs.google.com/a/transvelo.com/file/d/0BxmC16gQK81fTzFjWTloZkNZWG8/edit?usp=drivesdk

**Comment by shivapoudel** [comment]
:+1:
