### ISSUE TITLE
White screen instead of dashboard - subscriber / customer

### ISSUE THREAD

**Issue by martinsnajdr** [woothemes/woocommerce#8042]
I have a fresh installation of the Wordpress 4.2 and after I installed the latest WooCommerce 2.3.8, I'm getting a blank white page when I want to log to dashboard as a user with subscriber / customer role. Without WooCommerce, the subscriber role works just fine. 

Any solutions?

**Comment by martinsnajdr** [comment]
It seems to be a problem since the 2.3.6 version.

**Comment by claudiosmweb** [comment]
Turn on the WordPress DEBUG mode and show me the errors from the white page!

**Comment by mikejolley** [comment]
Enable http://codex.wordpress.org/WP_DEBUG and tell us the error you see.

**Comment by mikejolley** [comment]
Closing due to lack of feedback.
