### ISSUE TITLE
'undefined' placeholder in User profile page of admin dashboard

### ISSUE THREAD

**Issue by ibndawood** [woothemes/woocommerce#8043]
In admin dashboard under Users > Your Profile, the state field of "Customer Billing Address" and "Customer Shipping Address" has an "undefined" placeholder when no country is selected.

Screenshot reference : https://docs.google.com/a/transvelo.com/file/d/0BxmC16gQK81fRVhSdDRZSUx6MEE/edit?usp=drivesdk

**Code causing the issue :**

[woocommerce/assets/js/admin/users.js](https://github.com/woothemes/woocommerce/blob/master/assets/js/admin/users.js) and here is the code : 

```javascript
$state = $this.parents( '.form-table' ).find( ':input.js_field-state' ),
$parent = $state.parent(),
input_name = $state.attr( 'name' ),
input_id = $state.attr( 'id' ),
value = $this.data( 'woocommerce.stickState-' + country ) ? $this.data( 'woocommerce.stickState-' + country ) : $state.val(),
placeholder = $state.attr( 'placeholder' );
```

The cause of the issue is that the element js_field-state does not have a placeholder attribute and hence `undefined`. 

The js_field-state element is generated from `add_customer_meta_fields` method of `WC_Admin_Profile` class in file : [woocommerce/includes/admin/class-wc-admin-profile.php](https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-profile.php). The issue can be resolved by either removing placeholder in the js file or adding placeholder while generating.

I also found similar piece of code in [/woocommerce/assets/js/admin/meta-boxes-order.js](https://github.com/woothemes/woocommerce/blob/master/assets/js/admin/meta-boxes-order.js) but I am not sure where it occurs.

**Comment by bryceadams** [comment]
@ibndawood you should consider making a PR :)

**Comment by ibndawood** [comment]
@bryceadams - I am not sure which approach to take the javascript approach or just adding an empty placeholder in the `add_customer_meta_fields` method. If I get some directions, I will make a PR :)

**Comment by mikejolley** [comment]
@jameskoster is this related to your fixes?

**Comment by jameskoster** [comment]
yeah, will be because we removed placeholders to fix that IE11 issue. We can safely remove this placeholder for now as well.
