### ISSUE TITLE
Slashes in variation value

### ISSUE THREAD

**Issue by juanvillegas** [woothemes/woocommerce#8044]
Hi All,

I have a WC_Product of type=Variable. One of the attributes have fractional number (ie: 1/7, 2/5, 3/2, etc), that is, they include a slash ("/"). I created the variations, and the slash appears correctly (admin area). But then, when displayed in the frontend, the slash doestn appear. It looks like its sanitized or something like that.

Any ideas how to get "slashes" to appear in the value? The problem is somewhere in the "save variation" function as the value is stored incorrectly in the database.

Thanks!
Juan

**Comment by mikejolley** [comment]
Look at versions/theme - I tested with both custom text attributes and global attributes and the values were displayed as intended:

https://dl.dropboxusercontent.com/s/2s8dljeg95cxjr2/2015-04-27%20at%2010.52%202x.png?dl=0

**Comment by juanvillegas** [comment]
Theme is storefront. Plugin's version is the latest.
Yes, it works in the variation selector (the combo boxes).
But if you try to retrieve variations in your code, the slashes are
stripped.

This is the backend:
https://www.dropbox.com/s/03wp4y7ntzagx0r/Screenshot%202015-04-27%2009.55.25.png?dl=0

And I found this in the functions that saves variations
(class-wv-meta-box-product-data.php around line 1534 (*removing the
stripslashes() wrap fixes it..*)
https://www.dropbox.com/s/g5ubmgdf2d0neiu/Screenshot%202015-04-27%2009.55.59.png?dl=0

**Comment by mikejolley** [comment]
What code are you using so I can reproduce?

**Comment by juanvillegas** [comment]
sure, its basically a loop like the following ($product is an instance of
*WC_Product_Variable*):

$available_variations = $product->get_available_variations();
$attributes = $product->get_attributes();

foreach ($available_variations as $prod_variation) : ?>
<tr data-variation-id="<?php echo $prod_variation->variation_id; ?>">
<?php foreach ($attributes as $attr_name) : ?>
<td>
<?php $attr_value = $prod_variation['attributes']['attribute_' .
$attr_name];
echo $attr_value; ?>
</td>
<?php endforeach; ?>
</tr>
<?php endforeach; ?>

code
<https://www.dropbox.com/s/7ru82243ouybein/Screenshot%202015-04-27%2010.10.27.png?dl=0>
image
<https://www.dropbox.com/s/7ru82243ouybein/Screenshot%202015-04-27%2010.10.27.png?dl=0>

**Comment by juanvillegas** [comment]
Basically, my question is why are you stripping slashes from the value? Is
there a specific reason?

**Comment by juanvillegas** [comment]
Following on this: how is that the following is not a bug? If I have, for example, 1/2 and 12, then the variations selector becomes: https://www.dropbox.com/s/9ad4vnjw4ugwlfv/Screenshot%202015-04-29%2002.08.23.png?dl=0
Notice they use the same "value" attribute. So for Woocommerce its the same thing.. If I select 1/2 in attr A, then it will search for attr B candidates in all variations where attr A = 1/2 OR 12, which is incorrect as it should only look for 1/2.

Am I making sense?

**Comment by mskogsrud** [comment]
I am also having issues with this. What is the reason it saves with stripslashes() - when I want to display the attributes i have no chance of splitting the string as no replacement is added with stripslashes - it simply return the attributes as a long word with no whitespace. In my case it ends up having attribute names that make no sense, i.e. bolivarhabannatrinidad (Should be Bolivar/Habanna/Trinidad)

**Comment by mikejolley** [comment]
This has nothing to do with stripslashes.

**Comment by mikejolley** [comment]
Branch working on fix here: https://github.com/woothemes/woocommerce/tree/text-attribute-handling

**Comment by jonyking** [comment]
I think the problem still existing. We have the problem also. Everything is up-to-date and product variations with slashes e.g. "116/120" are placed to 116-120. When can it be fixxed?

**Comment by hybridwebdev** [comment]
It's now August 2022, and this still remains an issue. 

![image](https://user-images.githubusercontent.com/7633708/180678703-c970293b-25d8-41f1-88d6-eed616fb3f35.png)


When woo is displaying the variations we create, it's formatting them incorrectly. As you can see, the values are being mangled when outputting the variation list. 

As mentioned by OP this is obviously an issue being caused by stripslashes, despite @mikejolley rudely dismissing that it's not.

The fact this issue was raised 7 years ago and still remains ignored, having been rudely dismissed, is ridiculous.
