### ISSUE TITLE
Checkout page: Missing address fields

### ISSUE THREAD

**Issue by xlocalx** [woothemes/woocommerce#8045]
hi,
my checkout page seen like this: http://prntscr.com/6ylwgr
how can i add address fields and shipping details. please help me

**Comment by mikejolley** [comment]
This hasn't been reported by anyone else so its something on your install - either a checkout field plugin (misconfigured) or the fields are hidden due to the theme.

Test with Twenty Twelve/plugins off.

Closing this as its not a valid bug report.

**Comment by xlocalx** [comment]
i try it, but its not work..
