### ISSUE TITLE
huge admin-ajax load time

### ISSUE THREAD

**Issue by shawaj** [woothemes/woocommerce#8046]
Woocommerce plugin causes huge wait time on admin-ajax.php

Disabling woocommerce fixes the problem immediately so definitely is a problem with woocommerce.

Many other people suffering same issue - https://support.woothemes.com/hc/communities/public/questions/201220087-Woocommerce-Causes-Slow-admin-ajax-php-Load-Times?page=2

**Comment by mikejolley** [comment]
Ajax requests have the overhead of loading WP admin + plugins during each request. You can reduce what you have installed + disable heartbeat API for a small improvement.

WC 2.4 will likely include its own ajax endpoint which will reduce this overhead and speed up requests.

**Comment by shawaj** [comment]
It has nothing to do with other plugins. The other plugins make no
difference.

Only plugin that makes a difference when deactivated is woocommerce.

Disabling heartbeat API does nothing to improve this, and removes a lot of
core WordPress functionality. It's a workaround not a fix. And it doesn't
even work.

Why are you guys ignoring this error?

Thanks

**Comment by mikejolley** [comment]
Did you not read my whole comment?

**Comment by mikejolley** [comment]
And we're talking about speed - something affected by many factors - not an error with a clear solution.

**Comment by shawaj** [comment]
Yes, read the whole thing.

I'm not sure why it is not possible to confirm this is a quite troublesome
issue, and caused by woocommerce, not other plugins.

I love woocommerce but this makes it pretty unusable for any serious web
shop, and has been an issue for a long time.

Anyway, thanks for your hard work on woocommerce - this is just supposed to
be constructive criticism.

I'll look forward to version 2.4

**Comment by mikejolley** [comment]
Should also note, anything with a WooCommerce **dependency** will also stop functioning when WC is disabled. So its more than just turning off WC core - you're also turning off all extensions for WC.

**Comment by shawaj** [comment]
Maybe not a clear solution, rarely is with code.

But certainly a blatantly obvious cause...the only plugin that when you
disable it reduces page load times by 50%+ across the entire site.

This happens on every woocommerce instance I have installed. Whether on a
shared platform or a dedicated box.

**Comment by shawaj** [comment]
Yes - but turning off all the dependent plugins, but leaving WooCommerce
activated, makes no difference - slow load still remains.

Turn off WooCommerce and the problem disappears immediately.

**Comment by mikejolley** [comment]
Why not enable query monitor plugin and see if you can spot anything slow? On clean installs with the dummy data there is very little different in loading time, and around 2mb increase in memory usage.

**Comment by shawaj** [comment]
I'll give that a go - although I've tried with dummy data before on a clean
install and still see the same thing.

Thanks, for your quick responses and the great plugin. I'll look forward to
2.4

**Comment by potasium56** [comment]
This issue still is happening, this dam admin,ajax is effect my page speed making it load at 3+ seconds here is a screen shot of whats causing it on waterfall - im not sure how to fix this heartbeat control doesn't work or fix the issue please someone help me 
![88ef548b40ace2006431efa9d04a096f](https://user-images.githubusercontent.com/13303466/32239463-394aa9e6-be30-11e7-8695-b42255b68e20.png)

**Comment by jodyshop** [comment]
Hi potasium56,

I get this issue too but in my case loading time 9.5 seconds (disaster) and no one admitting this.

**Comment by shawaj** [comment]
We are about to move to Shopify due to the unreliability of WooCommerce. 

 In our experience it just doesn't work very well for large stores with lots of items and functionality and lots of orders.

It's a real shame because it truly is a fantastic concept.

**Comment by jodyshop** [comment]
Sure thing, everything was working cool after my store reached 16k (16000 items) everything destroyed). The website takes decades to load! 9.5 seconds (on VPS with 4GB Ram)... Wow! almost customer can go out for a picnic and back till the page loading - what a shame :-1:

**Comment by jodyshop** [comment]
Anyway, you might change your theme! sometimes it causes this issues.
