### ISSUE TITLE
Issue with WC_API_Authentication::normalize_parameters()

### ISSUE THREAD

**Issue by GaryPEGEOT-WIC** [woothemes/woocommerce#8048]
This method cause an Array to string conversion notice if there is an array in params

**Comment by claudiosmweb** [comment]
So, It's working as it should.
Show me an example of what you're doing.

**Comment by GaryPEGEOT-WIC** [comment]
I'm trying to update a product with variations:
url : http://localhost/Local/wordpress/wc-api/v2/products/1728?product[title]=Miaou&product[variations][0][id]=1743&product[variations][0][title]=...
and i'm getting this warning:
b>Warning</b>:  rawurldecode() expects parameter 1 to be string, array given in <b>/var/www/default/Local/wordpress/wp-content/plugins/woocommerce/includes/api/class-wc-api-authentication.php</b> on line <b>283</b>.

Maybe try with http_build_query ?

**Comment by claudiosmweb** [comment]
Please, ready the documentation: http://woothemes.github.io/woocommerce-rest-api-docs/
You need to sent and json!

**Comment by GaryPEGEOT-WIC** [comment]
I'm using https://github.com/kloon/WooCommerce-REST-API-Client-Library to make API calls, but i'm getting errors with the normalize_parameters method.

I tried this to avoid errors:
`
$query_string = rawurlencode(rawurldecode(http_build_query($params)));
$query_string = str_replace('%', '%25', $query_string);
$query_string = str_replace('%253D', '%3D', $query_string);
$query_string = str_replace('%2526', '%26', $query_string);
`
No warning error, but i get a 401 response if i use array

**Comment by claudiosmweb** [comment]
Great, WooCommerce-REST-API-Client-Library is just for consults, GET methods.
You can not sent data. And you don't have filters like `product[title]=Miaou&product[variations][0][id]=1743&product[variations][0][title]`.
You still is using the API wrong!

**Comment by claudiosmweb** [comment]
Read the docs http://woothemes.github.io/woocommerce-rest-api-docs/ !
