### ISSUE TITLE
Issue with WC_API_Authentication

### ISSUE THREAD

**Issue by GaryPEGEOT-WIC** [woothemes/woocommerce#8049]
Hi, 

I'm using PUT method to update a product with variations on API v2 endpoints:
`*endpoint url:* /wc-api/v2/products/:product_id`

I'm using https://github.com/kloon/WooCommerce-REST-API-Client-Library to perform curl requests.
My test website do not use SSL, so i have to use oauth authentication, the normalize_parameters method use rawurlencode, so it won't work with array(s), and i'm getting a warning.

I corrected error by updating *generate_oauth_signature* method:
```php
$query_string = rawurlencode(rawurldecode(http_build_query($params)));
$query_string = str_replace('%', '%25', $query_string);
$query_string = str_replace('%253D', '%3D', $query_string);
$query_string = str_replace('%2526', '%26', $query_string);
```

To generate a valid signature, but i'm getting an error on woocommerce (401 error, invalid signature), because array bug is also present on WC_API_Authentication::check_oauth_signature().

( I read the doc, and i'm using correct method PUT with API doc endpoint)

Best regards

**Comment by claudiosmweb** [comment]
Not a WooCommerce issue and WooCommerce-REST-API-Client-Library don't works for PUT yet.
