### ISSUE TITLE
oauth key with array

### ISSUE THREAD

**Issue by GaryPEGEOT-WIC** [woothemes/woocommerce#8050]
Hi,

I had an issue when updating a product with variations: update works properly, but because there is an array in my params and i'm not using SSL, WooCommerce plugin is showing a php warning, so JSON reponse won't parse correctly:

```html
   <b>Warning</b>:  rawurldecode() expects parameter 1 to be string, array given in <b>/var/www/default/Local/wordpress/wp-content/plugins/woocommerce/includes/api/class-wc-api-authentication.php</b> on line <b>281</b><br />
```
In fact, in PHP doc, you can read **string rawurlencode ( string $str )**, so it will only work with string

**Comment by claudiosmweb** [comment]
Show me the json used to the request.
