### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by healiny** [woothemes/woocommerce#8051]
There are strings that can not be translated into,
I also can not find them in the code.

They are listed under "class = woocommerce-error"
Appear in Checkout Page

For example:
ERROR: The username or password you entered is incorrect. Lost your password?

Or

     First Name is a required field.
     Last Name is a required field.
     Address is a required field.
     Town / City is a required field.
     Postcode / zip is a required field.
     Phone is a required field.

**Comment by claudiosmweb** [comment]
All strings are available for translation on [Transifex](https://www.transifex.com/projects/p/woocommerce/)

The correct string for it is a plural:

```
#: includes/class-wc-form-handler.php:643
msgid "%s is a required field"
msgid_plural "%s are required fields"
msgstr[0] ""
msgstr[1] ""
```

**Comment by healiny** [comment]
<p>I translated the strings you showed (The example below)</p>
It works in Cart page, and does not work for the Checkout page.

<p>And have the second string you did not mention it -</p>
-------------------------
 <h3> ERROR: The username or password you entered is incorrect. Lost your password?</h3>
--------------------------
--------------------------
#: includes/class-wc-form-handler.php:643
#, php-format
msgid "%s is a required field"
msgid_plural "%s are required fields"
<h3>msgstr[0] "%s - שדה חובה"</b></h3>
<h3>msgstr[1] "%s - שדות חובה"</b></h3>
------------------------------------
#: includes/class-wc-checkout.php:446 includes/class-wc-form-handler.php:85
msgid "is a required field."
<h3><b>msgstr "הינו שדה חובה"</b></h3>

**Comment by claudiosmweb** [comment]
If you just translate, will only be available in the next version of WooCommerce.

**Comment by healiny** [comment]
OK thanks.
When the next version be released?
Did you update here that fix the problem?

**Comment by amastaneh** [comment]
+1
