### ISSUE TITLE
Fatal Error: Call to undefined function wc_get_screen_ids() in includes/admin/class-wc-admin.php

### ISSUE THREAD

**Issue by SanchoPoncho** [woothemes/woocommerce#8057]
Hello!
We are regularly getting this Fatal Error: Call to undefined function wc_get_screen_ids() in includes/admin/class-wc-admin.php on line 151 on fresh wordpress installs, especially on php 5.3 
What could possibly be the reason?

**Comment by moldcraft** [comment]
Version 2.6.11

![staticshot_04-01-2017_10-42-27](https://cloud.githubusercontent.com/assets/1475489/21636287/b8983cca-d26a-11e6-97b1-449ac5887bfd.png)

**Comment by MMaKenZi** [comment]
@moldcraft 
Which plugin you are using? for that information about fatal error

**Comment by moldcraft** [comment]
It's just a styled error message

```sh
sudo apt install php-xdebug
```

**Comment by mikejolley** [comment]
Not sure what is generating that page or why it's doing things manually, but our admin class includes that function/file during `init`. The same class handles footer text. Maybe it's calling hooks manually?

**Comment by moldcraft** [comment]
Here is a test theme to reproduce the problem

[test-theme.zip](https://github.com/woocommerce/woocommerce/files/684495/test-theme.zip)
