### ISSUE TITLE
SSL Verify on Win and Yosemite OS X servers

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8058]
There's an issue with the SSL on these 2 kind of servers.

PayPal and Stripe use self signed certificates and these servers are not able to verify them because the verification is disabled.

This is what Stripe returns, similar error appears with PayPal

> 04-22-2015 @ 09:26:47 - Error response: SSL: CA certificate set, but certificate verification is disabled

Fixed in Stripe changing the file wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php and find this code on line 644

`'sslverify'  => false,`

Replace it with

`'sslverify'  => true,`

cc @mikejolley 

But for PayPal?

If you need more info check the ticket #283854

**Comment by maxrice** [comment]
I think `sslverify` used to cause a lot of issues with improper cURL configurations, but apparently as of WP 3.7, CA certs are bundled and it's fine to set `sslverify` to true. see http://wordpress.stackexchange.com/a/167947

**Comment by mikejolley** [comment]
@maxrice thats great to know. I believe I've always used false due to those issues  - didn't realise it was fixed.

**Comment by claudiosmweb** [comment]
Also `sslverify` as `true` will take a little more time to make the connection, which sometimes is not necessary, because we trusted in API URLs from payment gateways like Stripe and PayPal.
But with this error on Windows and OSX, is valid to try to put as `true` or exclude the `sslverify` (use the WordPress default).

**Comment by maxrice** [comment]
@claudiosmweb I disagree, given that WP is bundling certs, there's no reason to set it to `false` now, as arguably it's a security risk when you're not verifying the remote host is actually who they say they are :smile_cat:

**Comment by claudiosmweb** [comment]
@maxrice yeah, if WP really is working, this will be great.
But I don't know. For example one guy just reported this in one of my plugins (the plugin is question use `sslverify` as `true`):

![screenshot from 2015-04-28 15 06 10](https://cloud.githubusercontent.com/assets/1264099/7376741/306aa0a6-edb8-11e4-9be1-a8c493ac0406.png)

> Log: "The SSL certificate for the <i>host</i> could not be verified."

**Comment by maxrice** [comment]
@claudiosmweb yeah you'd have to dig into that specific host and see what the issue was -- in general my feeling is that it's better to err on the side of verifying even if that still causes with some hosts/server setups.

**Comment by claudiosmweb** [comment]
Yes, of course. Better always verify the SSL.
We have no fault with outdated servers :p
