### ISSUE TITLE
REST API Multiline JSON for product desription and short_description.

### ISSUE THREAD

**Issue by bigtomjp** [woothemes/woocommerce#8059]
I have tried a bunch of things to get multiple lines in product descriptions and short descriptions working with the REST API. 

    text1\ntext2
    
    text1\\ntext2
    
    text1\r\ntext2

None of these work.

When I GET the JSON reply from the API after creating a product manually in wordpress with multiple lines it shows 
    

    <p>text1<\/p>\n<p>text2<\/p>
There is even a spot with a page break in the returned JSON.
`<br \/>\n`

I cannot seem to reproduce this when creating a post with the API.
When trying to replicate this exactly I end up with:

    <p>text1 text2<\/p>\n

Which is not the desired result at all. I am only getting single line entries. Is there support for multi-line entries in the API? If not It really should be there.
I tried an array, but that did not work either.

**Comment by claudiosmweb** [comment]
Send with the values:

```json
"enable_html_description": true,
"enable_html_short_description": true
```

This will allow the HTML.
I'm sorry, I forgot to put this in the docs.
I'm updating the docs now.

**Comment by claudiosmweb** [comment]
Docs updated http://woothemes.github.io/woocommerce-rest-api-docs/#products-properties

**Comment by bigtomjp** [comment]
Excellent! I am glad there was a quick answer for this.

**Comment by bigtomjp** [comment]
Claudio,
Do you have an example of how the HTML is passed? I am using the HTML enable but it is still wiping all the HTML tags out of the text.
