### ISSUE TITLE
No REST API support for _guid or _uuid columns in wp_posts

### ISSUE THREAD

**Issue by bigtomjp** [woothemes/woocommerce#8061]
I use the post _guid as a UUID field for integrations. From my experience WP does not allow editing the _guid value and I have had to manage this directly in the tables. It would be very useful if some kind of unique identifier could be used for products as this really provides easier implementation of multi-chanel sales. A UUID for users could be used for easily integrating customers into multiple stores with the same login info and profile information.

I also have a duplicated value in _uuid column that is added to the wp_posts table. All the values have been stable and safe through many updates of WP and WooCommerce. There was some talk at some point of WP implementing a usable UUID field natively, but it has not happened yet.

Is there any way you could allow for the API to recognize and use _uuid if it was added to the wp_posts table? Granted, this is not for everyone but would be very nice for the those who would use it.

**Comment by claudiosmweb** [comment]
API has filters and actions that allow you to add any type of data :)

**Comment by bigtomjp** [comment]
Got it.
