### ISSUE TITLE
Issue with WC_API_Authentication::normalize_parameters()

### ISSUE THREAD

**Issue by GaryPEGEOT-WIC** [woothemes/woocommerce#8069]
If a shop is not using SSL, you have to generate an oauth signature, based on query params your want to get/submit.

In `includes/api/class-wc-api-authentication.php` , line 224, plugin use `normalize_parameter()` method.

This method use `rawurlencode( rawurldecode( $value )`, but if $value is an array, like product['variations'] for exemple, this will throw a warning notice, that prevent JSON to be parsed correctly if WP_DEBUG is active.

Using `http_build_query()` instead can prevent this bug, and create a proper signature. (If WP_DEBUG is inactive, requests work fine but signature is not really valid, because query_string is stopped where array begin).

**Comment by GaryPEGEOT-WIC** [comment]
Here is an exemple of request :
```json
{
  'product': {
    'title': 'Test',
    variations: [
      {
        id: 1743,
        sku: 3001230000027
      },
      {
        id: 1744,
        sku: 3001230000034
      }
    ]
  }
}
```
(PUT request to update a product)

**Comment by maxrice** [comment]
Can you post your query params in addition to that request body? `normalize_parameters()` intentionally does not work with arrayed query params

**Comment by claudiosmweb** [comment]
This is a invalid json data...
Here fixed for you:


```js
{
  "product": {
    "title": "Test",
    "variations": [
      {
        "id": 1743,
        "sku": "3001230000027"
      },
      {
        "id": 1744,
        "sku": "3001230000034"
      }
    ]
  }
}
```
