### ISSUE TITLE
Woocommerce slow or unresponsive after WP 4.2 update

### ISSUE THREAD

**Issue by 07dcolem** [woothemes/woocommerce#8070]
I was doing some searching the other day to see if anyone had issues when updating to the new Wordpress 4.2 and came across this thread in the Woocommerce support forums. I have a shop with around 2000 products and this makes me hesitant to upgrade. It seems that some pages in the backend have become slow or unresponsive after the 4.2 update. Has anyone else run into or addressed this? https://wordpress.org/support/topic/woocommerce-extremely-slow-after-wordpress-42-update

**Comment by mikejolley** [comment]
I looked at the thread but no issues or queries stand out. I've noticed no slow down on my own stores, but I don't have 2k products. You'll have to let us know if you notice anything.
