### ISSUE TITLE
Choose countries allowed for selling

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8072]
I don't remember where i've seen this exactly (maybe Table Rate Shipping), but in a similar field we have buttons on the bottom like "EU", "US" and when you click them it auto-populate the list of countries with all the countries in EU or US.

Can we do the same for this setting?

![](http://cld.wthms.co/13ZQm+)

**Comment by mikejolley** [comment]
I think this has less usefulness for this setting. I obviously have no stats on this, but how many people would you say only sell to EU? @jameskoster ?

**Comment by SiR-DanieL** [comment]
I see a lot of people selling only in US and know that certainly a lot of EU shops would sell only in EU.

**Comment by jameskoster** [comment]
I agree with Mike, this is less useful. 

For people selling only to the US, they just select one country so we don't need a button for that. 

Seems really niche that a store would sell to _all_ of Europe?

Personally, I'm not sure it's worth adding.

**Comment by panploenes** [comment]
Hey guys

I am from Germany and i think it makes lots of sense to have a button for Europe and one for the European Union as well.

**Comment by jameskoster** [comment]
Yeah that's kinda what I mean, if you include buttons for extra groups (such as the EU) it starts to be more useful. But then down the road we may have to start considering Asia, Africa, etc etc. Could get messy quickly. Personally I think we should keep core clean. It can't be that hard to find a comma separated list of countries to copy / paste?

**Comment by jameskoster** [comment]
Gonna close this, I don't think core is the place.

**Comment by bchevreau** [comment]
Is this really closed ? I spent 3 hours on adding every single country in the Europe zone, then selecting only European Union as a client wants to sell to only Europe, with separate shipping for EU. This is SILLY. I Please take it into consideration, it's the second shop I have to do this for, and it doesn't seem like a hard thing to add (allow for a listing by continent maybe ?).

**Comment by pascalknecht** [comment]
@bchevreau I created a sql script you might find useful here:
https://gist.github.com/pascalknecht/8d94babbea537ab16b5f98a460c43301
Maybe someone wants to create a plugin out of it?

**Comment by wordxpression** [comment]
Plus one!
