### ISSUE TITLE
Products should only display in selected categories

### ISSUE THREAD

**Issue by rightlook** [woothemes/woocommerce#8073]
I see WooCommerce displays products based on a hierarchical process within categories. I understand that the John Doe Shoe is not categorized as "Apparel", but since it has the "Shoes" category and "Shoes" is a child of "Apparel" category, John Doe Shoe will display on the Apparel category page even though I have not checked the parent level category.

Most of the time this process is fine, but there are many requests from clients that don't necessarily want child category products showing on the parent category page. And it's a bit confusing when I've gone and made a product and selected the categories I'd like it to appear in, yet the product still technically appears in categories that I have not selected.

**Comment by mikejolley** [comment]
We have no plans to change the hierarchical nature of categories. WordPress handles posts in the same way. You can however edit your 'apparel' category in admin and set it to show sub-categories instead of products.
