### ISSUE TITLE
Bulk edit tool to remove sale price from products adding "0" instead of null

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#8076]
When using the bulk "Edit" action for selected products (http://cld.wthms.co/13ZJc) to remove the sale price by changing it to empty (http://cld.wthms.co/1fzaB), a value of "0" is put into the sale price field. The product doesn't seem to pay attention to this until the product is updated within the Edit Product page. If it goes unnoticed by the store admin, the product is free (http://cld.wthms.co/1h7t7).

**Comment by roykho** [comment]
@MindyPostoff is this with 2.3.8?  I was not able to reproduce this with master.

**Comment by MindyPostoff** [comment]
@roykho Yes, I'm running 2.3.8

**Comment by roykho** [comment]
@MindyPostoff can you please try from master and see if you get the same issue.

**Comment by MindyPostoff** [comment]
@roykho Still happens in master.

**Comment by roykho** [comment]
@MindyPostoff ah, ok I missed a step from your description.  After performing the steps, I did not go back into the product and click update.  Without this step, the quick edit works fine.  Its only AFTER you go back again to the product and click update is when this will happen...
