### ISSUE TITLE
Manual Order Unable to Choose Past Date

### ISSUE THREAD

**Issue by slash1andy** [woothemes/woocommerce#8078]
If you try to set an order to a past date when inputting it (in this instance, to record a sale from Amazon), you are unable to, and when you save the order, it defaults back to today's date. 

You are completely unable to select a previous date while the status is "Pending Payment". If you change the status to something like "Processing", then you can (after saving again to change status) change the date to a previous date.

Ticket #288286 for reference.

**Comment by seb86** [comment]
I had this exact same issue earlier today.

**Comment by mikejolley** [comment]
'pending' status was incorrectly set - this was already fixed in master. Next part is the set the date later (commit incoming). This will be resolved in the 2.4 release.
