### ISSUE TITLE
Being advised to install the already-active WooCommerce Colors plugin

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#8081]
I have a site that I've upgraded from WC 2.2.11 to 2.3.8. The dashboard shows the notice advising to install the "WooCommerce Colors" plugin - even after I've installed, activated and configured it (and reloaded the dashboard page showing the notice, of course).

It looks like the code in WC_Admin_Notices::reset_admin_notices only calls WC_Admin_Notices::has_frontend_colors() which just checks for settings and doesn't involve checking if the recommendation in the notice has already been followed. (The button in the notice attempts to install the plugin again). 

Obviously I can just dismiss the notice, and will do so. Just thought I'd log the issue.

**Comment by mikejolley** [comment]
I've taken this notice out of the 2.4 dev branch so this won't be an issue after that :)
