### ISSUE TITLE
After update wordpress 4.2.1, Missing billing details in woocomerce checkout page

### ISSUE THREAD

**Issue by xcolomer** [woothemes/woocommerce#8082]
After update to wordpress 4.2.1, Missing billing details in woocomerce checkout page

**Comment by roykho** [comment]
Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

Meanwhile try deactivating all plugins except WooCommerce ( 2.3.8 ) and switch your theme to a WordPress default theme such as 2015 theme.

**Comment by xcolomer** [comment]
Thank's
