### ISSUE TITLE
Is there any way to insert JS code within order-received endpoint?

### ISSUE THREAD

**Issue by MarceloPedra** [woothemes/woocommerce#8085]
Hello! I need to add a conversion pixel to the order-received page. Since it is a URL created by WooCommerce with no associated physical page, I'm not finding a way to do it. 
Is there any filter or action I can use?

And what about using a PHP snippet to detect the REQUEST_URI? and if the URL contains "order-received" print the JS code... Should it work?

Thanks in advance. I'm desperately in a hurry with this. All help will be appreciated.

**Comment by maxrice** [comment]
https://github.com/woothemes/woocommerce/blob/master/templates/checkout/thankyou.php#L63 :smile_cat:

**Comment by claudiosmweb** [comment]
You can use `wp_enqueue_scripts` action and the `is_order_received_page()` conditional function.

**Comment by MarceloPedra** [comment]
Thank you Claudio!!! But...
if is_order_received_page=true , how can I test if the purchase was succesful or failed? any filter to retrieve and test the order status?

**Comment by claudiosmweb** [comment]
You can use:

```php
global $wp;

$order_id = isset( $wp->query_vars['order-received'] ) ? intval( $wp->query_vars['order-received'] ) : 0;
$order      = wc_get_order( $order_id );
```

And test the status with:

```php
$order->get_status();
```

**Comment by bekarice** [comment]
Use the action @maxrice linked to since it gives you the order ID.  Use it to get the order object, and then you can access anything about the order.

**Comment by bekarice** [comment]
@claudiosmweb and I had roughly the same idea apparently :smile_cat:

**Comment by claudiosmweb** [comment]
We do the same with Google Analytics integration: https://github.com/woothemes/woocommerce-google-analytics-integration/blob/master/includes/class-wc-google-analytics.php#L114-L141

**Comment by MarceloPedra** [comment]
Thank you very much guys!!!! You rock! :)
