### ISSUE TITLE
WooCommerce returns JSON with text/html header

### ISSUE THREAD

**Issue by CTassisF** [woothemes/woocommerce#8086]
Hey,

I am seeing this issue in checkout:

![WooCommerce Bug](https://cloud.githubusercontent.com/assets/325517/7419469/9dd081c6-ef4b-11e4-87cd-93ab05d46630.png)

After a few minutes debugging I found the issue:

WooCommerce POSTs to wp-admin/admin-ajax.php and then returns the corresponding JSON (with error messages, redirect URLs etc).

However, as you can see here [1], wp-admin/admin-ajax.php forces the Content-Type header to text/html.

You should never return JSON with text/html header. It is a bad practice and it should be avoided. This practice breaks many reverse proxy and load balancing solutions, including, but not limited to, Google PageSpeed Service (which I use) and CloudFlare, because those services try to optimize the returned JSON as if it were HTML.

After blacklisting wp-admin/admin-ajax.php in Google PageSpeed Service everything seems to work fine.

I really don't know if this bug is related to WordPress core or your plugin. Maybe you need to stop using wp-admin/admin-ajax.php to return JSON, maybe WordPress needs to change that header in wp-admin/admin-ajax.php.

Can you please help me?

Thanks in advance.

[1] https://github.com/WordPress/WordPress/blob/master/wp-admin/admin-ajax.php#L37

**Comment by claudiosmweb** [comment]
Starting WooCommerce 2.4 we'll have our own ajax endpoint: https://github.com/woothemes/woocommerce/blob/17f1536ed3d1e6fb8ee95430de15b5a72aab57df/includes/class-wc-ajax.php#L18-L81

However we use `wp_send_json()` to return your json data for almost the requests with `wp-admin/admin-ajax.php`.

https://github.com/WordPress/WordPress/blob/cb1ad98015ea8e75474e22c39d77e4aaf3d008ab/wp-includes/functions.php#L2780-L2795

WordPress does the same:
https://github.com/WordPress/WordPress/blob/60706015e10e46a0534a84431917d72a30df5224/wp-admin/includes/ajax-actions.php

**Comment by claudiosmweb** [comment]
@mikejolley will be a great idea set the header for https://github.com/woothemes/woocommerce/blob/17f1536ed3d1e6fb8ee95430de15b5a72aab57df/includes/class-wc-ajax.php#L426-L437 or https://github.com/woothemes/woocommerce/blob/62c58360c24ea3f047019fc36eafa5515753378b/includes/class-wc-checkout.php#L350
