### ISSUE TITLE
REST API HTML description issue. Tags still being cleaned.

### ISSUE THREAD

**Issue by bigtomjp** [woothemes/woocommerce#8090]
I have been trying to use the following options without any luck. The API keeps clearing out all the HTML tags. Max suggested I raise an issue here as this should be working.

`“enable_html_description”: true`
`“enable_html_short_description”: true`

Specifically I have tried
`"short_description": "text1<br \/>\ntext2","enable_html_short_description": true`
`"short_description": "text1<br \/>text2","enable_html_short_description": true`
`"short_description": "text1<br />text2","enable_html_short_description": true`
`"short_description": "<p>text1<\/p>\n<p>text2<\/p>","enable_html_short_description": true`
`"short_description": "<p>text1</p>\n<p>text2</p>","enable_html_short_description": true`
`"short_description": "<p>text1<\/p><p>text2<\/p>","enable_html_short_description": true`
`"short_description": "<p>text1<\/p>\\n<p>text2<\/p>","enable_html_short_description": true`
`"short_description": "<p>text1</p><p>text2</p>","enable_html_short_description": true`
Maybe a few others, but you get the idea.

I also tried the enable parameter before the description parameter and got the same results.

All are returning single line text:
`"short_description": "<p>text1 text2<\/p>\n"`

**Comment by claudiosmweb** [comment]
Sorry, now I see the problem xD

**Comment by bigtomjp** [comment]
Claudio,
I am using the new class-wc-api-products.php and still having the same issue. Can you confirm the actual format of the HTML description that works?

**Comment by claudiosmweb** [comment]
Now need to works like `wp_insert_post()` or `wp_update_post()`.

**Comment by claudiosmweb** [comment]
Now need to works like `wp_insert_post()` or `wp_update_post()`.

**Comment by claudiosmweb** [comment]
Now need to works like `wp_insert_post()` or `wp_update_post()`.

**Comment by bigtomjp** [comment]
Does the API actually access `wp_insert_post()` or `wp_update_post()`? They are known to have a filter as well. Does that filter need to be disabled? Still I am having issues getting the tags to stay in the content.

**Comment by claudiosmweb** [comment]
Need filters to be safe.
But now you can sent HTML.

Here my example data:

```js
{
  "product": {
    "description": "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. <\/p>\n<p>Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. <\/p>\n<p>Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. <\/p>\n<p>Mauris placerat eleifend leo.<\/p>\n",
    "enable_html_description": true
  }
}
```

**Comment by bigtomjp** [comment]
This is the exact parameter I am using for testing:
`"enable_html_description": true,"description": "<p>text1 <\/p>\n<p>text2<\/p>","short_description": "<p>text1 <\/p>\n<p>text2<\/p>","enable_html_short_description": true`

This is still returning single line text
`"description":"<p>text1 text2<\/p>\n","short_description":"<p>text1 text2<\/p>\n"`

I can write to the MySQL table directly to provide the correct result but I expected the API would allow me to avoid doing this anymore. I am not sure why this is working for you and not working for me.

**Comment by bigtomjp** [comment]
So this is confirmed working and and this simple code is not working for me only?

**Comment by IcuScc** [comment]
Claudio.. is perfect!!
Thanks a lot.
