### ISSUE TITLE
Save paypal fee per transaction

### ISSUE THREAD

**Issue by scottrpaterson** [woothemes/woocommerce#8091]
Hi,

Would it be possible to get the IPN mc_fee value from PayPal. This value is used to store the PayPal fee charged for the transaction.

It appears this was required in 2011, added, then closed (https://github.com/woothemes/woocommerce/issues/208)  but after reviewing the code, it appears by mistake that it was not actually added.

Thanks,
Scott

**Comment by Babelfisch** [comment]
It does only work on IPN but not on PDT. All PayPal payments via Payment Data Transfer have no meta data for fee, email, etc. pp.

Could you please add the same for PDT notifications?
