### ISSUE TITLE
WC_TEMPLATE_DEBUG_MODE still not working

### ISSUE THREAD

**Issue by sosukeinu** [woothemes/woocommerce#8093]
I couldn't figure out why my template overrides were not working, but even after going into admin and setting debug mode to false, woocommerce_status_options is empty, and none of my overrides are loading. This only seems to effect the last couple versions, but I'm assuming it occurred when the activation hook was changed to set debug mode true by default. 2.3.8

**Comment by mikejolley** [comment]
WC_TEMPLATE_DEBUG_MODE only works for admin users. This disables all overrides.

You can force it off through your wp-config.php file:

`
define( 'WC_TEMPLATE_DEBUG_MODE', false );
`

If overrides are not working it could be either:

- they are named wrong
- they are placed in the wrong directory
- they are being added to the wrong theme/child theme

I've had not other reports of this issue occurring.
