### ISSUE TITLE
Select2 - update to version 4 (now released)

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#8095]
Version 4.0 of Select2 has been released, and has some breaking changes - https://select2.github.io/announcements-4.0.html.

**Comment by shivapoudel** [comment]
:+1:

**Comment by claudiosmweb** [comment]
Great new \o/

**Comment by roykho** [comment]
Good god...we can now finally get rid of the hidden input fields...

**Comment by roykho** [comment]
ref: https://github.com/woothemes/woocommerce/pull/8123

**Comment by claudiosmweb** [comment]
Closed in favor to #8123
