### ISSUE TITLE
Fade class on WC_Admin_Meta_Boxes errors

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#8096]
By default errors added for the `WC_Admin_Meta_Box` class come wrapped with a `fade` class. WooCommerce doesn't ever seem to actually fade the box out. Which is great, because I think it is ideal for the error message to stay so it can be read.  

```
<div id="woocommerce_errors" class="error fade"><p>Mix &amp; Match supports simple products and product variations with all attributes defined. Other product types and partially-defined variations cannot be added to the Mix &amp; Match container.</p></div>
```

But I was just working on a ticket for Mix and Match where the client couldn't save any items into his MNM container and he didn't know why. It looks like MNM isn't working, but it is because something *else* is latching on to the `fade` class and hiding the message very quickly. I saw it blip on the screen because I was looking for it, but otherwise you won't see it.

Anyway, if WC isn't fading the item away, should we do away with the `fade` class?

**Comment by mikejolley** [comment]
Seems to be legacy. Lets dump it.
