### ISSUE TITLE
API order status update to Processing sends email notification

### ISSUE THREAD

**Issue by emrahu** [woothemes/woocommerce#8100]
Using the API, when you change an order status to Processing, the API sends a new order email to the admin. This is an issue when changing the status of the old orders. 

From the documentation 
curl -X PUT https://example.com/wc-api/v2/orders/645 \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "order": {
    "status": "processing"
  }
}'

**Comment by claudiosmweb** [comment]
Need set as paid http://woothemes.github.io/woocommerce-rest-api-docs/#orders-properties
