### ISSUE TITLE
Manually edited item prices not updated in My Account -> View order

### ISSUE THREAD

**Issue by piffpaffpuff** [woothemes/woocommerce#8101]
If an item price is manually edited in the admin, the new price isn't showing in My account -> View order.

**Comment by mikejolley** [comment]
Because the order has already been placed. You cannot change prices retrospectively.

**Comment by piffpaffpuff** [comment]
thanks for the info. but the recalculated totals are shown in the front-end. shouldn't they also be the original ones?
