### ISSUE TITLE
loop/add-to-cart.php not working as expected

### ISSUE THREAD

**Issue by LastRose** [woothemes/woocommerce#8102]
This template file isn't working as expected - ignored all changes to the Add to Cart button text, and would show up as a variable item for some reason. 
changed 
`echo apply_filters( 'woocommerce_loop_add_to_cart_link',`
to
`echo apply_filters( 'woocommerce_loop_add_to_cart',`

 and it seemed to fix the problem.

**Comment by mikejolley** [comment]
Changing the hook name is not a fix - something you have installed must be filtering on woocommerce_loop_add_to_cart_link and changing the markup. You would need to identify what and why.
