### ISSUE TITLE
Using woocommerce_wp_text_input() for variations

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#8103]
You get an warning/notice when adding a new variation if you try to use `woocommerce_wp_text_input()` to add a field via the `woocommerce_product_after_variable_attributes` hook. 

>Notice: Trying to get property of non-object in /srv/www/wordpress-default/wp-content/plugins/woocommerce/includes/admin/wc-meta-box-functions.php on line 22

I believe this is because the `$post` variable is not set up.when `woocommerce_wp_text_input()` looks for a `$post->ID`.

It would be convenient to be able to use the built-in text, checkbox, select field types for variations.

**Comment by mikejolley** [comment]
@claudiosmweb is revising variations for 2.4 https://github.com/woothemes/woocommerce/issues/6995

**Comment by technofreaky** [comment]
@mikejolley 
is this issue is resolved.  ??
