### ISSUE TITLE
What is the right way to validate the settings fields in the Settings API?  

### ISSUE THREAD

**Issue by wsenjer** [woothemes/woocommerce#8104]
Hi, 
I'm developing a shipping method, in the settings page of the method I want to validate the fields before saving them into the DataBase. I looked into the Settings API abstract and I found that I have to implement a method with the name `validate_[FIELD_ID]_field`. 
I wrote something like this: 
```PHP
public function validate_myfield_field($key){
  if( ... ){
    // validated
    return $value;
  }else{
      //not validated
      add_settings_error($key, 'settings_updated', 'Value is empty', 'error');
  }
}

```

But it doesn't work, my question is about the right way to implement the `validate_[FIELD_ID]_field` method?

Thanks.

**Comment by mikejolley** [comment]
You can name your method either for the option name (validate_NAME_field) or for a type of field (validate_TYPE_field).

On success, return the value.

On fail, add an error to $this->errors. We don't have a add_settings_error method.

Thanks

**Comment by nikitamekh** [comment]
This is not working with payment gateway settings. Settings validation errors are truly collected in **$this->errors** array, but  **display_errors()** method is nowhere called. Looks like a bug.

**Comment by nikitamekh** [comment]
Yes, we have to call display_errors ourselves.
I made it by adding hook:
```php
add_action('woocommerce_update_options_payment_gateways_helloworld', array($this, 'display_settings_errors'));
....
public function display_settings_errors() {
        $this->display_errors();
}
