### ISSUE TITLE
Payment method error

### ISSUE THREAD

**Issue by jakeshep** [woothemes/woocommerce#8105]
On my theme since the new update, there has been an issue with two of the same payment methods displaying. (Ie. Paypal option and proceed to paypal button both displaying twice)

I dont know if anyone has a solution to this?

**Comment by roykho** [comment]
Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

A possible issue is that your theme is using out of date WooCommerce template files.  Try switching to a default WordPress theme such as 2015 and see if it works then.
