### ISSUE TITLE
Rest API: allow Basic Auth without SSL

### ISSUE THREAD

**Issue by enricodeleo** [woothemes/woocommerce#8106]
Hi!
I'm  trying to take advantage of the WooCommerce rest apis built in (I already use wp-json).
As far as I've seen I can use oAuth only if I manually enable consumer and secret key on per-user basis or I can use Basic Auth if my website is under SSL (without manually enabling each user I suppose).
Since I'm just developing the new app and don't care about SSL on dev environment (it causes more troubles than benefits, even because windows users have troubles with self signed certificates), can I enable basic auth under clear http? Any hint?

Thank you very much!

**Comment by claudiosmweb** [comment]
https://en.wikipedia.org/wiki/Basic_access_authentication

http://tools.ietf.org/html/rfc2617

**Comment by maxrice** [comment]
@enricodeleo for development, you can disable authentication using a code snippet like this:

`add_filter( 'woocommerce_api_check_authentication', function() { return new WP_User( 1 ); } );`
