### ISSUE TITLE
What is the correct code to empty the notices buffer?

### ISSUE THREAD

**Issue by MarceloPedra** [woothemes/woocommerce#8109]
I'm needing to programatically hide the notices in a checkout page for cosmetic purposes.
I used the below instruction within theme's functions.php but it throws a PHP error when you navigate a page without notices:
> add_filter( 'woocommerce_init', 'wc_clear_notices');

Is there a way to check for notices before asking to clear them? What is the right way? Compatible with WC 2.1 and 2.3?

Thanks in advance!

**Comment by mikejolley** [comment]
wc_clear_notices() is fine but it needs to come after woocommerce_init

`
add_action( 'init', 'wc_clear_notices', 20 );
`

**Comment by MarceloPedra** [comment]
Hi! Well it worked ok muting the notices, but it is throwing a PHP error on any hit to any page:

> [05-May-2015 13:11:33 UTC] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'wc_clear_notices' not found or invalid function name in /home/acade/public_html/dev/wp-includes/plugin.php on line 496 

I guess it's happenning when you navigate pages without any notices to be cleared.
So, I restricted the execution to the checkout page using 

```if( is_checkout() ){
	add_action( 'init', 'wc_clear_notices', 20 );
}```

And it works well now. Thanks!
