### ISSUE TITLE
Download permission fallback

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8112]
When you try to grant access to an order without the biling email setted there's an error message which does not allow you to do it.

Can we fallback to the account email address instead?
Maybe ask for this before to use that email.

**Comment by SiR-DanieL** [comment]
Any feedback on this @mikejolley ?

**Comment by mikejolley** [comment]
Many of the related functions, such as generating the actual download link, rely on billing email as a source. Its the one reliable piece of data for guest and user orders.

Even with a fallback, it would still require the admin to choose a user before granting access. I believe we should continue with this requirement.

1 enhancement we can make though would be to update billing details after choosing a user, so some data is prefilled (including this). I'll do this now.

**Comment by SiR-DanieL** [comment]
> Even with a fallback, it would still require the admin to choose a user before granting access. I believe we should continue with this requirement.

Yes obiviously if there's no customer selected and neither a billing email, we can't do anything. But we could fallback to the customer email.

> 1 enhancement we can make though would be to update billing details after choosing a user, so some data is prefilled (including this). I'll do this now.

Thanks!
