### ISSUE TITLE
duplicate incomplete order

### ISSUE THREAD

**Issue by trong291990** [woothemes/woocommerce#8113]
Customers checkout the order and choose to make a payment by paypal ( go to paypal site), but they dont pay and back to shop. They add products and checkout again, now we have two order, have any way to fix it ? I want to one order only in this case.
Thanks

**Comment by mikejolley** [comment]
Really this depends on the user. If they still have a session, the previous order will be overwritten if its still pending payment.

If they do no have a session, there is not choice but to start a new order. Removing the old one would be too destructive if say, IPN was down.
