### ISSUE TITLE
Label for dropdown for variable products forced to capitalised.

### ISSUE THREAD

**Issue by SeenNotHurd** [woothemes/woocommerce#8114]
At the moment if you create a custom product attribute that is used for variations, the name of the attribute is output in 'sentence case' (every word/major word has the first letter capitalised), regardless of how it is entered in the attributes panel.

This is a problem for languages where 'sentence case' is not used. Would be great if the output matched the input...

**Comment by roykho** [comment]
@SeenNotHurd I am not seeing this.  At what point are the attribute names are different?  Example on which page?  Using WooCommerce 2.3.8?

**Comment by roykho** [comment]
Closing for now, please submit evidence and we'll revisit this..
