### ISSUE TITLE
add_to_cart() doesn't work if the cart is empty

### ISSUE THREAD

**Issue by tmyie** [woothemes/woocommerce#8115]
```add_to_cart()``` doesn't seem work properly if the cart is empty. It gives me this error: ```Fatal error: Maximum function nesting level of '100' reached, aborting!```

However, even if I set the nesting level too 600 or so, it keeps matching the limit. This only happens if the cart is empty and I'm adding a product for the first time.

This is the code that I'm using: ```$woocommerce->cart->add_to_cart($product_id = 82, 1, $variation_id = 92);```

It happens on both simple and variable products. Also, if I'm logged in as admin or not.

This is the documentation I'm following: http://docs.woothemes.com/wc-apidocs/class-WC_Cart.html

Any idea? Is it something to do sessions?

**Comment by mikejolley** [comment]
It depends when you run that - where is your code? if its too late, no session will exist. too early, you'll cause errors. Try after wp_loaded action.

**Comment by tmyie** [comment]
Thanks, it was being called before everything was set up properly. Apologies.
