### ISSUE TITLE
Webhook missing triggers

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8116]
When bulk updating orders (or changing the status via Actions buttons), or updating them via API, the webhook is not triggered.

Ticket #289909

cc @claudiosmweb

**Comment by claudiosmweb** [comment]
@maxrice is ok in adding these new triggers?

**Comment by maxrice** [comment]
updating via the API should trigger the webhook, see https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-webhook.php#L556-L564

Not sure about bulk updates in the admin or status changes, but yeah it would make sense to me to trigger updates when those actions occur :smile_cat:

**Comment by mikejolley** [comment]
@justinshreve and #2

**Comment by justinshreve** [comment]
I have verified and tested that updating via the API does trigger the webhook.

Bulk status updates do not currently trigger the hook, but I have addressed this in #8303.
