### ISSUE TITLE
Products section for adding bulk products to category

### ISSUE THREAD

**Issue by DougDrago** [woothemes/woocommerce#8118]
It seems if you go to the Products section ( it shows then a list) then on Left hand side is a box to check off to select, then a the top you can choose a category from the drop menu. This is for bulk and then  hit apply. But does not seem to be working. wondering if its a bug.
My site is www.mrherbalist.com
Go to Herb Formulas and or Single Herbs, under that I have category for " total herbs " So the drop down menu is not so long.
-Doug

**Comment by claudiosmweb** [comment]
Tested and works fine.
This is a just standard taxonomy selection feature from WordPress.
Don't have any changes for WooCommerce.
