### ISSUE TITLE
Why _x( 'product-category', 'slug', 'woocommerce' ) ?

### ISSUE THREAD

**Issue by tivnet** [woothemes/woocommerce#8122]
In `class-wc-post-types.php` :: `register_taxonomy`, the slug is translated. See the code snippet below.
If I switch the site language to `ru_RU`, for example, I am getting 404 on these URLs:
`/товарная-категория/clothing/`

When I need to go to the Settings->Permalinks and explicitly set `product-category` there. So, what's the point of translating the slug in the `register_taxonomy`?

Thank you!

```
register_taxonomy( 'product_cat',
...
	'rewrite'               => array(
		'slug'         => empty( $permalinks['category_base'] ) ? _x( 'product-category', 'slug', 'woocommerce' ) : $permalinks['category_base'],

...
```

**Comment by claudiosmweb** [comment]
This is for SEO questions, this works perfect to Portuguese, Spanish, French and other languages based on Roman script (Latin script).

So it depends on the people who translate into their language, find the best way to do this.

**Comment by tivnet** [comment]
Sorry @claudiosmweb, it does not "work perfect" for me.

I changed the language to French, went to Woo Tools, forced upgrade language, and got the shop in French, with category URL `/categorie-produit/clothing/` producing 404.

(I am checking this on a clean site, with the Storefront theme, WooCommerce and nothing else.)

**Comment by claudiosmweb** [comment]
Yeah, when you change your language you need to flush rewrite, because the translation.

**Comment by tivnet** [comment]
How exactly (without writing code)?
I went to settings-permalinks, did save - and still getting 404.

**Comment by tivnet** [comment]
deactivate/activate WC does not help either... 404.

**Comment by tivnet** [comment]
Only when I wrote `flush_rewrite_rules();` right after registering taxonomies, it started working. But, a regular user wouldn't know that, correct @claudiosmweb ?

**Comment by claudiosmweb** [comment]
You just can go to WooCommerce Admin > Settings > Permalinks and click in the "Update" button.

**Comment by tivnet** [comment]
@claudiosmweb (as I wrote before, just clicking Update did not work)

My humble opinion:
Having this translation causes only confusion.
If someone wants to have a slug different from the default, there is a way to do it in the Permalinks.
If you install WordPress in default (en_US) locale, install WooCommerce and then switch language - you get 404s. 
Permalinks should stay English in the code, and people should use Settings to change them for SEO purpose.
