### ISSUE TITLE
Issues with get_order_total();

### ISSUE THREAD

**Issue by mikakaltoft** [woothemes/woocommerce#8124]
Hey,

I have created a plugin and want to grap the total of the order with the code:

add_action( 'woocommerce_thankyou', 'rocapress_tracking_dev' );
function rocapress_tracking_dev( $order_id ) {

$order = wc_get_order( $order_id );

$total = $order->get_order_total();

echo $total;

}

However, I get this error: Fatal error: Call to undefined method WC_Order::get_order_total() in .../wp-content/plugins/my-plugin/my-plugin.php on line 32

Can you tell me why get_order_total() gives me that error? And how can I possible fix it?

I believe that this could possible be a bug since I am using the latest version of WooCommerce and WordPress.

Sincerely,
Mika

**Comment by claudiosmweb** [comment]
Don't exists any `get_order_total()`.
Try `$order->get_total()`.

**Comment by mikakaltoft** [comment]
Yep, worked perfectly! Thanks!

Is it possible that there isn't either a method I can call to get the shipping total?
