### ISSUE TITLE
No way to calculate Shipping Costs via the REST API

### ISSUE THREAD

**Issue by nikolov-tmw** [woothemes/woocommerce#8126]
We have two separate WordPress sites, one of which has the latest version of WooCommerce installed and the other one doesn't have WooCommerce at all. On the one that doesn't have WooCommerce, the client decided that they want to add products from the WooCommerce site as part of a custom checkout process(written from scratch).

So, we enabled the REST API, generated the keys for the admin user and started creating orders with v2 of the API. Order creation works just fine, however looking through the documentation we didn't find a way to calculate the delivery price for a given order and a given delivery address.

So what happens is that the order is created, but no shipping is calculated.

Am I missing something, or is it just not currently possible to calculate shipping rates via the API? I would expect to give a shipping address to the API and then get an array of shipping options with information about each option - name, id, price. Then I can present those to the user and they can select the one they want to use and I'll forward that to the POST /orders request.

**Comment by mikejolley** [comment]
The API does not include shipping calculations (nor coupons FYI). You need to *tell* it the cost to use.

I've logged this on the roadmap since it would be a cool feature to have https://trello.com/c/CA3foFd9/74-rest-api-shipping-calculation-via-api

**Comment by nikolov-tmw** [comment]
@mikejolley - any idea why the card in Trello that you created got archived? Was there another one created that I didn't see or the idea got dumped?
Because, come on - the main focus of WooCommerce was/is selling physical products that would most of the time need to be shipped. Not being able to calculate how much shipping would cost for a new order is kind of silly :smiley: . How am I supposed to write an app that would let users purchase stuff? Or use the API from another website to allow users to purchase through that other website?

Sorry for commenting on a closed issue, but I'm just curious about this.

**Comment by mikejolley** [comment]
The API is geared towards getting and manipulating data - not managing user carts. Might change in the future,  but thats the main focus.

**Comment by nikolov-tmw** [comment]
But I wasn't talking about managing a user's cart - that would most-definitely happen on the consumer side(be it another website or an actual app).

I'm talking about creating a new order - an important part(in my opinion) of creating the order is figuring out shipping, so it would make sense that if you're creating an order on the site that has the API you would want to use the shipping settings for that site(instead of calculating them on your own). Obviously I can hard-code the shipping settings on the consumer side, but if I were to change them on my live site, I'd have to release an update for the consumer as well.

I'm going to stop here, as I've explained my thinking above and I don't want to continue spamming on a closed issue :smiley: 
Also if the need arises, I'm pretty certain that I can create a custom API endpoint that would do shipping calculations.

**Comment by claudiosmweb** [comment]
@nikolov-tmw feel free to help sending a Pull Request for it :smiley:

**Comment by nikolov-tmw** [comment]
@claudiosmweb for sure! I haven't dwelved much into WooCommerce's source code, but there's always a first time :smiley: 

Do you have any suggestions on what endpoint to create? Perhaps something like `/wc-api/v3/shipping_calculator` that would accept a `GET` or `POST` request? `POST` since you might have to pass a lot of data(an object of product ID's with their quantity perhaps?).

I'll look into how shipping options are calculated via AJAX during the checkout process.

**Comment by Mr-AjayM** [comment]
@mikejolley @claudiosanches  Any progress for count the shipping rates and coupon discount in woocommerce rest API ?

**Comment by claudiosanches** [comment]
@Mr-AjayM no and probably it's better you create our own integrations for it on your app side.
