### ISSUE TITLE
Wrong rounding in invoice and email

### ISSUE THREAD

**Issue by mdevdk** [woothemes/woocommerce#8127]
We have stumbled upon an issue that we, quite annoyingly, cannot find a solution for.

During cart check-out and payment, all prices are shown correct, with or without tax.
However, when the invoice is shown, prices are incorrect and we've worked it down to the rounding applied - somewhere.

Example:
Customer buys 4 items valued at 46. 4x46=184 of which 36.8 (or 25%) is taxes. Everything is correct here, even during check-out, payment, etc.

However, in the order detail page the product price and subtotal is 183.
Though order total price is 184, the tax applied is wrongly set to 36 (should be 36.8 as shown above).

Woocommerce version: 2.1 (no options to upgrade at this time).

Is there any solution to this peculiar problem?

**Comment by claudiosmweb** [comment]
Sorry, but this is fixed in recent versions.
I recommend you update.
