### ISSUE TITLE
Star ratings showing as quotation marks

### ISSUE THREAD

**Issue by pwz2k** [woothemes/woocommerce#8128]
For leaving reviews on products, what should be stars are instead showing as quotation marks for selecting a star rating. Does someone know how I can fix the issue?

![joy](https://cloud.githubusercontent.com/assets/3035945/7522278/1f508068-f4c2-11e4-980e-a35726e10feb.png)

**Comment by jameskoster** [comment]
Hi, could you share a URL?

This could be a couple of things:

* Your theme might be forcing the font of this element so that it doesn't use our bundled star icon font
* The font might not be loading

A URL will help me debug.

Thanks

**Comment by jameskoster** [comment]
@pwz2k any update on this?

**Comment by pwz2k** [comment]
Thanks for checking in. No fix yet, but you can view the page with the issue here:

http://eatuberbacon.com/product/cambridge-v/

**Comment by jameskoster** [comment]
Hey,

Your site isn't actually loading the default WooCommerce CSS. I suggest talking to your theme author.
