### ISSUE TITLE
Price Filter on Main Menu

### ISSUE THREAD

**Issue by JoaoRFerreira** [woothemes/woocommerce#8130]
Hi there,

I don't know if is already on other post, but i'm trying to create a price filter on my main menu adding on the URL

<50: .../?max_price=50&min_price=0
50 to 100: .../?max_price=100&min_price=50
and so on...

But this show all the products and don't filter.
Can i do the price filter this way?

Best regards

**Comment by mikejolley** [comment]
You need to have the price filter widget active for this logic to run as far as I know. Also, link to the shop page with these args appended.
