### ISSUE TITLE
When transient version increases (to clear cache) clear old transients

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8131]
https://wordpress.org/support/topic/too-many-wc-transients-created-in-db?replies=11#post-6926347

**Comment by sjeden** [comment]
+1 - 140k rows in my options table.

**Comment by sjeden** [comment]
Showing rows 0 - 24 (448011 total, Query took 0.0007 sec)
SELECT * FROM '***_options`

**Comment by sjeden** [comment]
This has risen to 466k after clearing all session data via the tools page it has now dropped to 360k

**Comment by sjeden** [comment]
Just updated to 2.3.10 and it removed 30k lines in my options table -after this i cleared all shop transients from the tools page - 

I still have in excess of 390k records.

**Comment by mikejolley** [comment]
The records can include real transients and customer sessions. We need those ;)

**Comment by nielsvr** [comment]
It seems to got worse lately. I even got sites where I have to clean the transients, because the site is getting to slow and the database way to big causing timeouts. I'm not against transients, but this is too much if it causes serious loading issues. I got around 3 or 4 shops under maintenance which have the same issue regular.

Maybe a filter for limiting the transient usage? If it's causing more issues then disabled, I'd rather have the choice.

**Comment by mdmoore** [comment]
I'm having issues with this as well.  Category pages are taking anywhere between 5 - 20 seconds to insert transients on every page load.  I'm using WordPress 4.3 and WooCommerce 2.4.6 with around 420 products.  

Clearing transients does seem to help but they continue to build up.  Is there a way around this?

**Comment by CyberCr33p** [comment]
How do you clear transients ?

**Comment by mdmoore** [comment]
Go to WooCommerce->System Status->Tools and click Clear transients.

**Comment by DaDre** [comment]
Clearing transients every day is not a viable solution. We have a high traffic site that fills up with over 250k transients per day that are not clearing automatically, which also leads to carts not being emptied after session is over, customers are coming back weeks later and are able to checkout with a cart from 2 weeks ago where products could be discontinued, or not in stock, causing backorders.

**Comment by icanoop** [comment]
Our site has gone down several times over the past few months and we've traced it back to this issue. WooCommerce is creating thousands of transients per day called wc_average_rating and wc_rating_count. Eventually it starts to slow the site down and when it hits a certain threshold the site just crashes.

I can set up a daily job to delete these transients as a temporary solution but is this problem being fixed? Surely this can't be considered correct behaviour. I'm on WooCommerce 2.4.10.

**Comment by claudiosmweb** [comment]
@icanoop it's being upgraded to version 2.5.0.
https://woocommerce.wordpress.com/2015/11/09/woocommerce-2-5-beta-1/
https://woocommerce.wordpress.com/2015/10/07/new-session-handler-in-2-5/
