### ISSUE TITLE
woocommerce my account bug in German

### ISSUE THREAD

**Issue by gameover2015** [woothemes/woocommerce#8136]
Hello,I am a developer and manage several websites in several languages on behalf of my customers.
I just updated woocommerce to the last version on every website and an address issue in the German version persists.
The customers after logging in their accounts cannot update their billing and shipping addresses both for a mismatching link. Clicking on the link (Bearbeiten)
![bug](https://cloud.githubusercontent.com/assets/12380306/7554043/3f2aec60-f716-11e4-864b-f42be9de19ad.jpg)
the same page is downloaded again. This IS NOT HAPPENING in the English version where the customer is redirected correctly to the selected page to update his/her account address. 
It is not the first time I see a link mismatching in the German version (before an alike issue happened addressing the categories of products, but this is luckily over).

Please, take care of it.
Best regards

**Comment by panploenes** [comment]
Hey
This issue maked me concerned, but I cannot reproduce it on two websites running the latest wordpress, woocommerce and Germanized versions. I checked the "edit" button on the my account page and theybare just working fine. I had a similar issue before and found a mistake with a SEO plug-in and the redirects it made.

**Comment by gameover2015** [comment]
Thanks for the hint, I disabled my SEO plugin but without results. I think the issue depends on the woocommerce link translation.

**Comment by mikejolley** [comment]
Have you tried going into Settings > Permalinks and saving?

**Comment by gameover2015** [comment]
Oh yes, of course

**Comment by Tobias-Conrad** [comment]
Here ist is working to edit customers data. I also use german and enfold theme.
please try with wordpress default theme.

**Comment by mikejolley** [comment]
I just downloaded our latest german translation and clicked the link - it went to '/edit-address/shipping/' and worked as intended.

The problem is in your po/mo file. cc @claudiosmweb

**Comment by gameover2015** [comment]
thank you!
