### ISSUE TITLE
Sales items not coming down. 

### ISSUE THREAD

**Issue by mariahclark** [woothemes/woocommerce#8137]
I scheduled a couple sales they ran and like clock work and when they were over the sales prices and the badge saying sale came down, but the items were still listed under my for sale items section. I went into products -> edit and looked at the product it looked just like a regular non sale item. There wasn't a sale price listed. I didn't change anything, but hit update and the problem was fixed. I do not want to manually update every item after every sale. Is there a way to fix this bug.

Also I am using the pos for woocommerce and the products remained sale items and on sale until I manually updated the products.

**Comment by mikejolley** [comment]
I've checked and we do clear "wc_products_onsale" transient whenever the cron job runs to disable sales. Our shortcode for sale products uses this.

What powers your sale section?

**Comment by mariahclark** [comment]
I am using woocommerce for sales. Is that what you are asking. The problem is still happening. You can see it at stitchamour.com. Right now there is a class showing up under sales even though the sale is over. Also if I ring the item up in my pos system it is till showing the old sale price. even though the price is correct on the website.

**Comment by mariahclark** [comment]
Here is the code for the sale section.

$args = array(
            'post_type' => 'product',
            'product_cat' => $category,
            'posts_per_page' => $products_per_page,
            'meta_query'     => array(
                'relation' => 'OR',
                array( // Simple products type
                    'key'           => '_sale_price',
                    'value'         => 0,
                    'compare'       => '>',
                    'type'          => 'numeric'
                ),
                array( // Variable products type
                    'key'           => '_min_variation_sale_price',
                    'value'         => 0,
                    'compare'       => '>',
                    'type'          => 'numeric'
                )
            )
        );

**Comment by mikejolley** [comment]
This isn't a core issue then. When the cron job triggers to reset the sale price (after its ending) your POS needs to be notified and your queries (if they use transients) need to be cleared.

We have a sale shortcode - if you add that to a page you won't see the same issue because the transient we use is cleared. [sale_products] if you want to confirm this.

**Comment by mariahclark** [comment]
Do you have any documentation explaining how to implement your short code.
