### ISSUE TITLE
[API] Payment gateway eSewa has no support for notify URL

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#8138]
[eSewa](https://esewa.com.np/) is a Nepali Digital Payment Portal developed by fonepay. It doesn't support the `notify_url` args and has `su` & `fu` which are Success URI and Failure URl respectively. So how can I use the Success URI for **Payment listener/API hook**:

```php
add_action( 'woocommerce_api_wc_gateway_esewa', 'callback_handler' );
```
I am unable to use `WC()->api_request_url( 'WC_Gateway_eSewa' );` as `notify_url` is not supported and have use eSewa success and failure uri args like this:

```php
return apply_filters( 'woocommerce_esewa_args', array(
    // This are success and failure uri :)
	'su'    => esc_url_raw( add_query_arg( 'wc-api', 'WC_Gateway_eSewa', $this->gateway->get_return_url( $order ) ) ),
	'fu'    => esc_url( $order->get_cancel_order_url() ),
), $order );
```
https://github.com/axisthemes/woocommerce-esewa/commit/b3bf1d02e1b0f9efdd69ad3a85cc5e3bfd5808ae

But because of above `su` instead of getting thankyou page I have got the blank page.

##### Transaction details for eSewa Implementation: #####
- Plugin Repo: https://github.com/axisthemes/woocommerce-esewa
- Service Code for eSewa Sandbox Mode: `Woo`

![capture](https://cloud.githubusercontent.com/assets/3774827/7556827/ada4f552-f7a0-11e4-995b-87b581003619.PNG)

**Comment by claudiosmweb** [comment]
Very easy, just be smart ;)

You can use `WC()->api_request_url( 'WC_Gateway_eSewa' )` for both.

Just set query args, for example:
```php
$request_url = WC()->api_request_url( 'WC_Gateway_eSewa' );

return apply_filters( 'woocommerce_esewa_args', array(
    // This are success and failure uri :)
    'su'    => add_query_arg( array( 'order_id', $order_id, 'success' => '1' ), $request_url ),
    'fu'    => add_query_arg( array( 'order_id', $order_id, 'success' => '0' ), $request_url ),
), $order )
```

And then you can use the callback for it:

```php
public function callback_handler() {
	@ob_clear();

	if ( ! isset( $_REQUEST['success'] ) && ! isset( $_REQUEST['order_id'] ) ) {
		wp_die( __( 'Invalid request!' ), __( 'Invalid request!' ), array( 'response' => 400 ) );
	}

	$success  = absint( $_REQUEST['success'] );
	$order_id = absint( $_REQUEST['order_id'] );
	$order    = wp_get_order( $order_id );

	if ( ! is_object( $order ) ) {
		wp_die( __( 'Invalid order number!' ), __( 'Invalid order number!' ), array( 'response' => 400 ) );
	}

	if ( 'pending' !== $order->get_status() ) {
		wp_die( __( 'Order has been processed!' ), __( 'Order has been processed!' ), array( 'response' => 400 ) );
	}

	if ( $success ) {
		$order->payment_complete();
	} else {
		$order->update_status( 'failed', __( 'Order failed!' ) );
	}

	wp_redirect( esc_url_raw( $this->get_return_url( $order ) ) );
	exit;
}
```

The thankyou template is prepared to deal with failed orders: https://github.com/woothemes/woocommerce/blob/master/templates/checkout/thankyou.php#L16

As I said, just be smart ;)

**Comment by shivapoudel** [comment]
Thanks @claudiosmweb !
