### ISSUE TITLE
Name attibuto not visible

### ISSUE THREAD

**Issue by pinolarocca** [woothemes/woocommerce#8141]
Good evening, I created products with variable attributes, but the name of these is not visible on the product page.
thanks

**Comment by roykho** [comment]
Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

Meanwhile please try turning all plugins off except WooCommerce and switch your theme to TwentyTwelve and re-test.

**Comment by pinolarocca** [comment]
Thank you very much for your answer, I formulated my question on the forum of Woocommerce.
thanks
