### ISSUE TITLE
Lost info from WooCommerce Checkout Manager

### ISSUE THREAD

**Issue by GregoireG** [woothemes/woocommerce#8144]
Hi,

I export information from woocommerce with store export but i got 2 fields from WooCommerce Checkout Manager are always empty when i export. The field wasn't empty... Maby a problem ?

Can you help me with this ?

Thank's

Grégoire

**Comment by mikejolley** [comment]
This is not a support area for 3rd party plugins such as "WooCommerce Checkout Manager". Please report core issues here only.
