### ISSUE TITLE
Prices not showing for variations when using the same price

### ISSUE THREAD

**Issue by StefanJson** [woothemes/woocommerce#8149]
It seems like there are a couple of bugs in Woocommerce 2.3.8. They may already be known? It involves variable products. If you have a variable product and you have the same price on all variants no price is displayed on the product page or category page, and not when you select a variant. When you put it in the shopping cart it appears. When putting a different price on each variant the price shows as it should on both the product side and the category page, provided that there are at least two variants in stock. Have you for example five variants with different prices, but only one variation in stock, so the price is not shown.

**Comment by roykho** [comment]
I cannot replicate this issue.  It shows up fine for me please see
![](http://cld.wthms.co/CSum+)

![](http://cld.wthms.co/1lGv1+)

Try switching your theme to TwentyTwelve and re-test.

**Comment by StefanJson** [comment]
Ok.

Then I have to try with TwentyTwelve and test again.
I’m using Canvas 5.9.3 and the child-theme Fashionable 1.1.0 fyi.

Yours sincerely
Stefan Johansson
DreamRooms Handelsbolag
Munters väg 3
438 96 Hällingsjö
Sweden

**Comment by roykho** [comment]
Also try deactivating all your plugins except WooCommerce as there could be a possible conflict.  Closing for now until this can be replicated.
