### ISSUE TITLE
Export CSV for IE on Sales Reports

### ISSUE THREAD

**Issue by vaandefanel** [woothemes/woocommerce#8150]
Export CSV in Sales Reports page doesn't work on Internet Explorer, can you add this feature ?
The export CSV button is visible on IE9 (I suppose it shouldn't be visible).
It looks like you use download attribute : http://caniuse.com/#feat=download

**Comment by mikejolley** [comment]
`
var a = document.createElement('a');

	if ( typeof a.download == "undefined" ) {
		$('.export_csv').hide();
	}
`

should hide it. I'll get someone to check IE.

**Comment by mikejolley** [comment]
Andrew confirmed the button is hidden in IE9

**Comment by vaandefanel** [comment]
My bad open the bad brower on my IE9-Win7 virtualbox.
No support'll be added for IE in the futures releases?
