### ISSUE TITLE
Filter on the category listing classes

### ISSUE THREAD

**Issue by marcperel** [woothemes/woocommerce#8153]
Hey Guys,

We'd really like to see a filter added to the `<li>` class in `templates/content-product_cat.php`. In Layers we use `post_class` to filter the product listing classes, but when a user switches to listing categories &  sub categories we'd like to have a similar class filter. 

We could make a custom template but that would mean keeping it up to date, a filter would be much better.

**Line 29 /templates/content-product_cat.php:**

``` <li class="product-category product<?php
    if ( ( $woocommerce_loop['loop'] - 1 ) % $woocommerce_loop['columns'] == 0 || $woocommerce_loop['columns'] == 1 )
        echo ' first';
	if ( $woocommerce_loop['loop'] % $woocommerce_loop['columns'] == 0 )
		echo ' last';
	?>">```

**Comment by mikejolley** [comment]
We have something in master for 2.4 https://github.com/woothemes/woocommerce/blob/master/templates/content-product_cat.php#L31

**Comment by marcperel** [comment]
Awesome thanks Mike
