### ISSUE TITLE
Notification on PP Settings page if fsockopen/cURL or Remote Post is not working

### ISSUE THREAD

**Issue by slash1andy** [woothemes/woocommerce#8158]
I think that if we had a (dismissible) notice on the settings page if the System Status Report detected an issue that would prevent PP from functioning, it would help customers before they had a week of failed orders. 

The message could say something like this:

"Your server does not have fsockopen/cURL or Remote Post enabled or working. PayPal uses this method of communicating when sending back transaction information. You can find out more info [here](http://docs.woothemes.com/document/paypal-standard/#section-9)" 

Or perhaps just a note on setting up PDT in the notice, but I think the IPN debugging might be more beneficial. It has the PDT instructions in it.

**Comment by mikejolley** [comment]
Doing this kind of check outside of the status page would have implications for performance. This is a remote request.

We've also had lots of feedback about having too many notices so I'd like to avoid that if possible. Lets add more inline docs for PP.

**Comment by slash1andy** [comment]
Adding in more about IPN issues on the settings page type of thing?

**Comment by mikejolley** [comment]
yes
