### ISSUE TITLE
he email with the processing status is being sent to on-hold status

### ISSUE THREAD

**Issue by yardz** [woothemes/woocommerce#8160]
The email with the processing status is being sent to waiting status.
This is getting really weird with bank tikets.

When someone buys using banking tiket he gets the email as processing status

**Comment by mikejolley** [comment]
If a customer makes a payment, even through a gateway which sets it on-hold, they still need the order details to come through via email. This is the most suitable email. 

This email also uses the text "Thank you for your order" so its not specific to processing orders.

**Comment by yardz** [comment]
The client does not receive any warning when the payment is approved . There should be a way to tell him.

**Comment by mikejolley** [comment]
How could there be if this is offline? The order status in the backend is on-hold.

If you're saying the order status is not on-hold in the backend **then this is down to your payment gateway**. Our bacs gateway uses on-hold status.

**Comment by yardz** [comment]
Well I think that I could not express myself properly.

The e- mail name is as " processing " the request is put "on- hold" . In the case of bank tikets , after paying customer it takes up to 4 days to be confirmed . In some cases can be confirmed on the same day in other 4, this depends on the bank.

Guests paying in slip keep calling or sending e- mail to see if the request has been confirmed . I just made a plugin that sends an e-mail only when the transaction goes for " processing " .

The problem is not to send the details of the order , but tell if it was confirmed or not. In cases of credit scolding , there are no problems , however in ways that payment takes to be confirmed this problem occurs .

I am suggesting that in future versions , there is the ability to configure e-mail " when making the payment " and " confirming the payment "

**Comment by yardz** [comment]
Just to explain . After I paid the ticket for my gatway it is changing the status to " processing " the problem is that the WooCommerce does not prompt for my clients that the payment was confirmed .

The problem is not status but the times that messages are sent.

**Comment by mikejolley** [comment]
Right; but the email does not say its been paid. It says the order has been received.

**Comment by yardz** [comment]
yes i know, but the title in configuration tab is "processing order". This is very confused because i tink the email shuld be send when the order gets state "processing".

Maybe you change the tab name for something like "Order Received"
