### ISSUE TITLE
WooCommerce interfering with theme slider

### ISSUE THREAD

**Issue by insightint** [woothemes/woocommerce#8163]
I contacted the developer of the theme we are using and they said there is a JavaScript error caused by WooCommerce plugin. It is making the slider images on the site squish to the left and not appear and scroll through. I deactivated it and indeed that did fix the problem we are having but we use the WP Job Manager and WP Job Manager - WooCommerce Paid Listings plugins. Do we need WooCommerce running in order to use these plugins (I assume so) and can you recommend a solution to what might be going wrong? The site is dptaonline.com

**Comment by mikejolley** [comment]
You are being affected by this: http://docs.woothemes.com/document/jquery-cookie-fails-to-load/
