### ISSUE TITLE
WooCommerce thankyou.php action woocommerce_thankyou is called even when order has not been paid

### ISSUE THREAD

**Issue by nickkuijpers** [woothemes/woocommerce#8171]
Hello,

I've been trying to auto complete orders when they are paid and i used the woocommerce_thankyou action for this. After some problems with orders been send without being paid i've checked the thankyou.php and i see that the action is being called everytime the page is loaded. So even if the status is failed. 

Should it not be only called up when completed?

**Comment by claudiosmweb** [comment]
We pass the `$order_id`, so you can use `wc_get_order()` to get the order details and compare the status.

**Comment by nickkuijpers** [comment]
Ah ofcourse i'm sorry.

Thanks!

**Comment by nickkuijpers** [comment]
For other people with this question, its $order = new WC_Order( $orderid );	 instead of wc_get_order, thats the old one
