### ISSUE TITLE
Payment method not showing description

### ISSUE THREAD

**Issue by ccsliinc** [woothemes/woocommerce#8173]
When the payment method is changed on checkout it is not showing the description field.  I believe the error is due to a code error on wp-content/plugins/woocommerce/assets/js/frontend/checkout.js, line 22.

I believe this should be 

this.$checkout_form.on( 'click', 'input[name=payment_method]', this.payment_method_selected );

instead of

this.$order_review.on( 'click', 'input[name=payment_method]', this.payment_method_selected );

**Comment by roykho** [comment]
I am not seeing this issue.  This is what I see after clicking around different payment methods.

![](http://cld.wthms.co/HEPQ+)

Perhaps you want to try switching to Twenty Twelve theme and re-test?

**Comment by danielgomon** [comment]
I have a problem with the order-received page, it's no showing any details of the order, just a blank thank you page
![captura de pantalla de 2015-05-19 12 36 10](https://cloud.githubusercontent.com/assets/757434/7710823/a47186d8-fe23-11e4-9ca2-45bde1e1ac53.png)

**Comment by roykho** [comment]
Not seeing an issue and no reply from OP so closing for now.
