### ISSUE TITLE
Unable to Change the No. of Related Posts on Single Product Page

### ISSUE THREAD

**Issue by rohitink** [woothemes/woocommerce#8174]
First i read this: http://docs.woothemes.com/document/change-number-of-related-products-output/
Then i realized it wont work of > 2.0.

So, I tried the following:

    function woocommerce_output_related_products() {

	$args['posts_per_page'] = 3; 
	$args['columns'] = 1; 
	woocommerce_related_products( $args); 
    }

This doesn't work either. If someone could point me in the right direction or if this is a bug indeed.

**Comment by roykho** [comment]
```
add_filter( 'woocommerce_output_related_products_args', 'change_related_products_count' );

function change_related_products_count( $args ) {
     $args['posts_per_page'] = 3;
     $args['columns'] = 1;

     return $args;
}
```

If that doesn't work, it could mean your theme is overriding it somewhere.

**Comment by rohitink** [comment]
The theme is not overriding it. Because, I am the theme Developer and I know it. The thing is, following classes are not being added to the related product li.

.columns-1, .columns-2, etc.

However, the .first and .last classes are being correctly added.

**Comment by roykho** [comment]
So now you're changing your question.  Your title states you're having issues with the number of related products.  Is this no longer an issue?

**Comment by rohitink** [comment]
It is still an issue. Since, the posts are not being displayed in the 3 columns, i desire. They are still showing up in 2.

**Comment by rohitink** [comment]
I am not sure, if the filter you suggested is working correctly. Because, the filter should add a class `columns-3` to the related product li, which it is not.

**Comment by roykho** [comment]
So you're returning 3 as the number of posts.  Is it returning 3 in the source?  After knowing if this is working then we can look at your other issue.

**Comment by rohitink** [comment]
Here is the Code:
```
add_filter( 'woocommerce_output_related_products_args', 'change_related_products_count' );

function change_related_products_count( $args ) {
     $args['posts_per_page'] = 3;
     $args['columns'] = 3;

     return $args;
}
```

It Correctlys return 3 products. The first product has a class `first` and the last one has the `last` class. Uptil here, there are no issues.

But, the width for each product is still set to `48%`. Because the class `columns-3

**Comment by rohitink** [comment]
In the woocommerce layout's scss file there is:
```css
	/**
	 * Product loops
	 */
	.related,
	.upsells.products {
		
		ul {
			li.product {
				width: 48%;
			}
		}
	}
```

And this value of 48% holds. Because of this the Related Products wont show in 3 columns. So, do I have to force the width in the theme's css file? Shouldn't it be changed like its changed for other products in columns using woocommerce's default layout.

**Comment by roykho** [comment]
So I don't believe related products have the class "columns" added to it.  It is currently only on shortcodes.

**Comment by rohitink** [comment]
Okay. Thanks for that clarification. I would suggest the class `columns` should be added to related products as well.

**Comment by roykho** [comment]
So for now, you can just adjust the width and it will look like this http://cld.wthms.co/1hXGZ

**Comment by rohitink** [comment]
Yes. That's what i did. Thank your the timely responses. :)
