### ISSUE TITLE
REST API V2 - /products/categories

### ISSUE THREAD

**Issue by theinventor** [woothemes/woocommerce#8177]
Hey, I hope this is simple..

I add a category in the /wp-admin UI, 

I do a get categories API call and it's empty:

```
2.1.5 :052 > client.get_products_categories
 => {"product_categories"=>[]} 
```

I click the category in the web UI to get the ID out of the URL, it shows tagID=6, so I get the REST endpoint for a specific category and it appears:

```
2.1.5 :051 > client.get_product_category(6)
 => {"product_category"=>{"id"=>6, "name"=>"Testing", "slug"=>"testing", "parent"=>0, "description"=>"", "count"=>1}} 
```

When will it show up in the /products/categories list????

**Comment by theinventor** [comment]
it showed up 20 minutes later.. oh well

**Comment by maxrice** [comment]
@theinventor Do you have caching plugins installed on the site? It's possible they cached the previous product categories results.

Also, looks like you built a ruby client library? Any interest in sharing that?

**Comment by theinventor** [comment]
I'll check the plugins - it was a one click install from cloudways

I just forked the gem someone already has on github and changed it to v2
and added a couple endpoints

I'll link it here in a day or two when it's got everything I'm using

**Comment by theinventor** [comment]
Here is the wrapper I'm using, I'll update the gist as it evolves.

https://gist.github.com/theinventor/5e5c6091cdaf83ec2cbb

@maxrice how come I have to use PUT /products/:id to get the stock/quantity stuff to work? Is there a tech reason on the WP side, or you guys just need some time/resources to fix that up?

I'd be happy to hire a php dev to put in a chunk of hours on this if that's all it needs..

**Comment by maxrice** [comment]
@theinventor replied on the other issue, but look [here](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L1042-L1102) to see the options available for setting stock. You should be able to do this during creation, if not that's probably a bug :smile_cat:
