### ISSUE TITLE
REST API V2 - GET /products/sku/ABC-123

### ISSUE THREAD

**Issue by theinventor** [woothemes/woocommerce#8179]
It seems if I set a SKU of "ABC-123" and try to do a get /products/sku/ABC123 I get an error about "No Route was found", if I try a SKU that doesn't exist, I get an error about Invalid product SKU

```
2.1.5 :066 > client.get_product_by_sku("ABC-123")
 => {"errors"=>[{"code"=>"woocommerce_api_no_route", "message"=>"No route was found matching the URL and request method"}]} 
2.1.5 :067 > client.get_product_by_sku(123)
 => {"errors"=>[{"code"=>"woocommerce_api_invalid_product_sku", "message"=>"Invalid product SKU"}]} 
2.1.5 :068 > client.get_product_by_sku("123")
```

Where is a valid SKU defined? The web UI allows me to create the SKU ABC-123.

Also seems the error messages aren't quite right, maybe they should both be returning:

"Product not found"

**Comment by claudiosmweb** [comment]
It will not work for sku with spaces, dashes and underscores. Will be deprecated in WooCommerce 2.4 too.

**Comment by theinventor** [comment]
@claudiosmweb thanks! So I'll use ABC123, that should work?

**Comment by lkraav** [comment]
@theinventor apparently I wasn't able to find this before filing #8220 myself. Yes, just removing the dash is what I did.

**Comment by claudiosmweb** [comment]
This will be available in 2.4 https://github.com/woothemes/woocommerce/commit/9c5cd0e5250434f30e1d6a35986b9367566e4afb

**Comment by lkraav** [comment]
Thanks. Can you enlighten me on the reason for deprecation?

**Comment by brandonros** [comment]
I'm experiencing the same issue with an order.

`/wc-api/v2/orders/AU-1479/notes`

**Comment by claudiosmweb** [comment]
@brandonros because this endpoint don't exists.

**Comment by brandonros** [comment]
I was using order_number, not order_id. Sorry!
