### ISSUE TITLE
mgCover in wrong position in my product-cart (bug?)

### ISSUE THREAD

**Issue by soulpawa** [woothemes/woocommerce#8181]
n my woocommerce store, in my cart, the first time when someone enter on my website, it works well, but the second time than goes to main page again, after visit a product, a imgcover appears into my small window, but in the wrong position, on the top rated products, the image cover works perfectly.

http://uploadpie.com/qeaP4
http://uploadpie.com/PJsTD
http://uploadpie.com/BzjEe

Here I add few screeshots with my problem.

https://wordpress.org/plugins/woocommerce/

**Comment by claudiosmweb** [comment]
This is an issue in your theme, not in WooCommerce.
