### ISSUE TITLE
GeoLocation not using IPv6 database

### ISSUE THREAD

**Issue by hifiberry** [woothemes/woocommerce#8184]
The GeoLocation module does not seem to use the GeoLite IPv6 database. For IPv6 addresses, the country returned is always Germany.
As GeoLite supports also IPv6, this should be easy to implement.

**Comment by DavidAnderson684** [comment]
This is happening because WC is currently using the legacy MaxMind API, which doesn't support IPv6. Here's an example of a plugin using the current API, which supports IPv6: https://wordpress.org/plugins/geoip-detect/

**Comment by hifiberry** [comment]
Do you plan to change this soon? We see already between 5 and 10% of our orders from IPv6 addresses.

**Comment by DavidAnderson684** [comment]
@hifiberry: I'm not a WooThemes developer.

**Comment by hifiberry** [comment]
Thanks. I guess this will be part of the next official woocommerce version - right?

**Comment by claudiosmweb** [comment]
@hifiberry will be available on WooCommerce 2.4.0.
