### ISSUE TITLE
woocommerce_update_order_review action only work for admin user

### ISSUE THREAD

**Issue by jigneshkailam** [woothemes/woocommerce#8185]
I am using Express checkout gateway, on the order review page before login ( guest check ) when I change shipping method it working fine.

On Order review page, I am trying with change shipping method as admin user also working fine.

Finally when I trying with customer login to change shipping method order total will not updated.

I am debug the code, I got the problem related to  check_ajax_referer( 'update-order-review', 'security' );  it will false the and return the same.

**Comment by mikejolley** [comment]
Sounds like caching of the nonce causing the security check to fail. Exclude your checkout pages from static caching for guest and logged in users.
