### ISSUE TITLE
Memory Exhausted while using filter on orders

### ISSUE THREAD

**Issue by lukasjuhas** [woothemes/woocommerce#8186]
While searching through approx 400 orders, I got fatal error memory exhausted. Using query monitor I detected that query that runs for filtering making around 16 000 results which with 256mb memory limit kills page. I have tracked down the query in code and just added "DISTINCT" in to query which worked like a charm. Thank you

**Comment by mikejolley** [comment]
Do you want to raise a pull request based on your commit?

**Comment by mikejolley** [comment]
nvm found it
