### ISSUE TITLE
Can't remove products from cart

### ISSUE THREAD

**Issue by danielgomon** [woothemes/woocommerce#8188]
I can't remove items from the cart, the only thing that seems to work is update quantity to 0, tried to downgrade to 2.37 and 2.36 with no luck.

Tried this, doesn't work: http://www.exentric.gr/web-design-blog/wordpress-tutorials/can-not-delete-products-from-cart-solved.htm

Also tried to use WordPress in english, Woocommerce too, no luck...

The order-received endpoint with the order details doesn't seems to work too, only shows a thank you message, but no order info
![captura de pantalla de 2015-05-19 12 36 10](https://cloud.githubusercontent.com/assets/757434/7710957/c93c008c-fe24-11e4-95d1-aa26cb00d40b.png)

**Comment by Jeroi** [comment]
I cannot reproduce this with latest wordpress and woocommerce. Removing cart objects work for me.

**Comment by danielgomon** [comment]
Never mind, was a misconfiguration in the nginx file, I just changed the line:

 try_files $uri $uri/ /index.php;

to

try_files $uri $uri/ /index.php?$args;

and now it's working, thanks.

**Comment by tcsoft** [comment]
Thanks @danielgomon that has fixed this for me too.

**Comment by idhacktools** [comment]
@danielgomon good , work for me :D :+1:  Thanks
