### ISSUE TITLE
Unsafe use of $ in jquery.payment.js

### ISSUE THREAD

**Issue by swiderski** [woothemes/woocommerce#8191]
Original post https://wordpress.org/support/topic/unsafe-use-of-in-jquerypaymentjs?replies=1

In file assets\js\jquery-payment\jquery.payment.js line 7 you have such code
`$ = jQuery;`
It is unsafe use of it, as later call of `jQuery.noConflict();`, that can occur in theme or plugin script, breaks your plugin.
You should put your code in
```javascript
( function( $ ){
//your code
}( jQuery ) );
```
Just like you do in other files.

Currently this breaks Stripe for WooCommerce plugin.

Hope for hotfix.

With kind regards.

**Comment by mikejolley** [comment]
This is a 3rd party script, FYI

**Comment by swiderski** [comment]
Hmmm, but will you fix your copy? 

I have posted issue on this plugin github https://github.com/stripe/jquery.payment/issues/161

With kind regards.

**Comment by swiderski** [comment]
I have checked new code and it works nicely! Thank you!
