### ISSUE TITLE
Conflicts caused by WooCommerce including external CSS in WP admin

### ISSUE THREAD

**Issue by mihaigrigori** [woothemes/woocommerce#8192]
WooCommerce enqueues a custom (and external) CSS for the jQuery-ui-dialog.
This is done by \WC_Admin_Assets::admin_styles: 

`wp_enqueue_style( 'jquery-ui-style', '//code.jquery.com/ui/' . $jquery_version . '/themes/smoothness/jquery-ui.css', array(), $jquery_version );`

This is causing conflicts with other plugins (WPML at least) that use the core WordPress CSS for the UI dialog.

Comment that line, of course the CSS conflicts are gone.

I suggest using unique scopes for custom CSS, so to avoid this sort of conflicts.
jQuery UI provide means to use the very same "Smoothness" theme, with a CSS context: http://jqueryui.com/download/

**Comment by mikejolley** [comment]
This script is a jquery-ui css file. 

> I suggest using unique scopes for custom CSS, so to avoid this sort of conflicts.

Surely that would be for your plugin (which is being styled) to resolve in that case?

**Comment by mihaigrigori** [comment]
This was a misunderstanding on our end Mike. It is actually something that we need to fix.
Sorry for the time waste. Can we delete this issue? Thanks!
