### ISSUE TITLE
Adding categories doesn't update list and form

### ISSUE THREAD

**Issue by lmartins** [woothemes/woocommerce#8194]
This is probably a bug with WordPress itself, posting here so that you can check if that is indeed the case  please.

What happens is that when you push the "Add new Product Category" button, the page seemingly does nothing. The categories list doesn't get updated, nor the form is cleared. If we then refresh the page though, the added category is then shown in the categories list.

**Comment by claudiosmweb** [comment]
Works fine: http://cl.ly/3A1W3v1F3K2Y?_ga=1.99537944.783001725.1429298194
