### ISSUE TITLE
HTML in variation title breaks cart layout

### ISSUE THREAD

**Issue by andi98** [woothemes/woocommerce#8197]
Hi @ all,

sometimes I use HTML in variation titles, for example like this:
![screenshot 2015-05-21 at 17 19 04](https://cloud.githubusercontent.com/assets/6323836/7752049/af91dce6-ffdd-11e4-8c7a-208a397c50b4.png)

When I add this variation to the cart, the cart layout is broken, because the title isn't shown correct:
![screenshot 2015-05-21 at 17 21 14](https://cloud.githubusercontent.com/assets/6323836/7752077/d1b839b4-ffdd-11e4-9581-1f13a408c104.png)

I looked a bit around in the code and I think it's a problem with the "a href"-links. I'm not sure, if this is an WC or an WP bug, because WC just uses get_permalink for the broken links. So if this is the wrong place for the issue, please tell, then I will submit it to WP.

Thanks!

**Comment by claudiosmweb** [comment]
@andi98 Thank you for reporting it now escape any HTML in the title of products or variations.
