### ISSUE TITLE
Bounds testing problem with shopping cart

### ISSUE THREAD

**Issue by zombietools** [woothemes/woocommerce#8198]
An adventurous customer of ours has identified a possible bounds testing problem:

From shopping cart screen with an item in it, attempt to input as large a value as possible into the quantity field. The limit of our field appears to be 9999. Upon attempting to update cart with max quantity, site serves up a blank screen.  Upon returning to home screen, the little cart icon at top of page shows 99999999 items and the cart continues to be inaccessible until the cart timeout lapses.

Our site: http://www.zombietools.net/

Thanks for continuing to improve Woo Commerce!

Chris
Zombie Tools

**Comment by mikejolley** [comment]
I am not getting this issue locally https://dl.dropboxusercontent.com/s/vxg2emph53n6ydj/2015-05-26%20at%2017.03%202x.png?dl=0

Are you using any extensions, such as dynamic pricing, which may have logic based on qty? Or shipping extensions? Disable them to rule out.

**Comment by zombietools** [comment]
Issue does seem to be connected with a plugin. Thanks.

**Comment by mikejolley** [comment]
Which one was it for my reference?

**Comment by zombietools** [comment]
I believe it is Woo Commerce Purchase Limits.
