### ISSUE TITLE
WooCommerce doesn't recognize Twenty Twelve as a supported theme

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#8208]
There have been a few tickets lately where customers argue our findings when we say we test with [WordPress Twenty Twelve Theme](https://wordpress.org/themes/twentytwelve) because an error appears at the top that claims it's not compatible. If we can fix this it'd definitely help save us support guys a heart attack or two :)

**Comment by mattyza** [comment]
Thanks @DanielSantoro. I'll explore this one further, perhaps with a way to hide the "theme support" admin notice for themes which WooCommerce core supports out of the box.

cc @mikejolley
