### ISSUE TITLE
What is PayPal? broken link to PayPal

### ISSUE THREAD

**Issue by rolandinsh** [woothemes/woocommerce#8211]
On checkout page "What is PayPal?" links to broken PayPal's pop-up link

**Comment by slash1andy** [comment]
What country are you based in?

**Comment by rolandinsh** [comment]
original link was for Latvia: https://www.paypal.com/lv/webapps/mpp/paypal-popup

**Comment by slash1andy** [comment]
@claudiosmweb this is the same thing as https://github.com/woothemes/woocommerce/issues/7417

**Comment by rolandinsh** [comment]
look like there are more European courties with broken links - Romania, Malta, Montenegro, ... and so on

**Comment by mikejolley** [comment]
@claudiosmweb "/cgi-bin/webscr?cmd=xpt/Marketing/general/WIPaypal-outside" works in more places. Making that default.
