### ISSUE TITLE
Product Pages are Un-Cacheable since they always set a cookie

### ISSUE THREAD

**Issue by jeichorn** [woothemes/woocommerce#8212]
In includes/wc-product-functions.php wc_track_product_view() any singular view of a product page sets the woocommerce_recently_viewed cookie.  This means that you can't cache these pages with a standard http cache.

This cookie should only be set if you are using the matching Recently Viewed Widget.  Otherwise you are just angering the performance gods for no reason.

**Comment by kevin25** [comment]
I got the same issue.
