### ISSUE TITLE
shipping address missing from new order emails

### ISSUE THREAD

**Issue by foxglove666** [woothemes/woocommerce#8213]
hi,

thanks for your help on this.

the new order received email has always had both the billing address and shipping address at the bottom. until recently as it now only shows the billing address. i really need this to show the shipping address.

can this be fixed please.

**Comment by claudiosmweb** [comment]
Tested and works fine.
Maybe you have changed this option:

![screenshot from 2015-05-27 14 29 39](https://cloud.githubusercontent.com/assets/1264099/7842956/e70e2aaa-047c-11e5-9cf0-e19196ab5d15.png)

Or the order is for virtual/digital products.
