### ISSUE TITLE
Refund Reports not showing actual refunds made

### ISSUE THREAD

**Issue by colighto** [woothemes/woocommerce#8214]
Hello,

I have updated our plugin to latest version woocommerce 2.3.9. When we do a refund for a particular order the refund reflects on the order list but not on the reports on Woocommerce > Reports. 
"in refunds" is showing 0 and also a previous refund that we have done just few days ago is not showing on reports too.

**Comment by mikejolley** [comment]
Full refund? Partial? Showing the period in reports when the order was made?

**Comment by colighto** [comment]
its a partial refund. I think I know what happened already its the same thing with completed orders they don't reflect on when the order was completed or refunded but the reporter will show it on when the order was created the order was created last march and the refund was done just 10 days ago to see the refund report or completion I need to set the reporter to show the sales report on the month of march.

**Comment by mikejolley** [comment]
Got it; we're working on this in 2.4  https://github.com/woothemes/woocommerce/issues/8028

**Comment by colighto** [comment]
great thanks for the update
