### ISSUE TITLE
V2 REST API Shipping Methods endpoint

### ISSUE THREAD

**Issue by GaryPEGEOT-WIC** [woothemes/woocommerce#8216]
Hi all,

I would like to list all the active shipping methods of a shop, with an endpoint like:
`orders/shipping_methods`
and to get a json response listing like :

```json
{
  "shipping_methods": {
    "method_id": "method_title"
  }
}
```

Or eventually with associated shipping cost

Is there a whay to do that ?

Thank you

**Comment by claudiosmweb** [comment]
There is nothing ready for it.

But I added your suggestion to vote: https://trello.com/c/Qm1E6Dsh/75-api-shipping-methods-endpoint-8216
