### ISSUE TITLE
Product categories, product tags, woocommerce endpoints not appearing in Admin Menu Manager

### ISSUE THREAD

**Issue by ioncakephper** [woothemes/woocommerce#8218]
Two weeks ago I installed WooCommerce, Jetpack and Storefront theme in a test site. With that installation I noticed that in the Menu Manager the Product Categories, Product Tags, and Woocommerce Endpoints appeared as sources of links for the menu items.

![wc-shows-pc](https://cloud.githubusercontent.com/assets/540846/7788000/99fc21e2-0231-11e5-9ad4-f9ce76820f54.PNG)

Last week, I performed the same action, but the Menu Manager did not show the Product categories, Product tags, WooCommerce Endpoints.

![wc-notshowing-pc](https://cloud.githubusercontent.com/assets/540846/7788007/ae300b60-0231-11e5-9763-eee5fe4aa687.PNG)

Could anyone suggest why this may happen? In both installation I was the admin of the site, and used a minimal number of additional plugins.

Thank you.

**Comment by roykho** [comment]
Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

Meanwhile to give you a hand this time, go to your top right of your screen and click on "screen options" and your choices will be there.

**Comment by ioncakephper** [comment]
Thank you so much! Both for suggesting the appropriate channel and for the solution!
