### ISSUE TITLE
/wc-api/v2/products/sku query returns "No route" error for SKU's with dashes in them

### ISSUE THREAD

**Issue by lkraav** [woothemes/woocommerce#8220]
Query: https://server.com/wc-api/v2/products/sku/DK-43010
Result: {"errors":[{"code":"woocommerce_api_no_route","message":"No route was found matching the URL and request method"}]}

Query: https://server.com/wc-api/v2/products/sku/DK43010
Result: {"errors":[{"code":"woocommerce_api_invalid_product_sku","message":"Invalid product SKU"}]}

After API allowed the insertion of all SKU-s with dashes with no errors, this is a very strange result.

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce/issues/8179#issuecomment-102870334
