### ISSUE TITLE
Tax on Refunds Error

### ISSUE THREAD

**Issue by jws29378** [woothemes/woocommerce#8222]
When an order is refunded, despite the correct total being shown, the tax column is not updated. This causes issues later down the line as when exporting to CSV the wrong amount is shown.

**Comment by mikejolley** [comment]
Screenshot? Need more details.

**Comment by jws29378** [comment]
![screen shot 2015-05-30 at 15 50 38](https://cloud.githubusercontent.com/assets/12595114/7897828/c0e0d526-06e3-11e5-9785-ab7d2110a225.png)
As you can see, a refund has been issued. The correct total refund amount has been calculated. However, the VAT total has not updated.

**Comment by jws29378** [comment]
Why has this been closed?

**Comment by jws29378** [comment]
Sorry new to GitHub so don't really understand!

**Comment by mikejolley** [comment]
@jws29378 because a patch has been committed. Read the ticket :)

**Comment by jws29378** [comment]
Oh clever! Will this then appear in thence update version?

**Comment by mikejolley** [comment]
2.4

**Comment by jws29378** [comment]
Cheers Mike!
