### ISSUE TITLE
In variable product, the selected attribute values are not captured properly when adding variation

### ISSUE THREAD

**Issue by jobthomas** [woothemes/woocommerce#8225]
I select two attribute values and when I click Add Variable, the two values are not longer visible and need to be selected manually again.

http://cld.wthms.co/dLVw

WC v2.3.9
Storefront 1.4.5
Tested in Safari

**Comment by claudiosmweb** [comment]
See the "Defaults" description:
![screenshot from 2015-05-25 12 42 07](https://cloud.githubusercontent.com/assets/1264099/7799370/b2836900-02db-11e5-9abe-c1b82d15f747.png)

So everything is working as it should work ;)

**Comment by jobthomas** [comment]
@claudiosmweb thanks for the reply: can I suggest a UI edit wherein Add Variation is not on the same line as the default options? Because this way it seems like one first has to select the values before clicking "Add Variation".

**Comment by claudiosmweb** [comment]
Yes, I'm changing some things on this screen to 2.4.

**Comment by jobthomas** [comment]
Awesome. Thanks.
