### ISSUE TITLE
Incorrect rounding when applying discount

### ISSUE THREAD

**Issue by EML-github** [woothemes/woocommerce#8229]
Originally asked on [StackOverflow](http://stackoverflow.com/questions/30258707/woocommerce-incorrectly-rounding-when-applying-discount), with no response.

Note that this is unrelated to errors when rounding tax, which was apparently [fixed in 2.1][1]. I'm on 2.3.7.

If you return a discount in the `woocommerce_get_discounted_price` hook, then the order details total is sometimes incorrect:
![woocommerce rounding error][2]

My hook code does this:

    ...calculate $refund
    $retval = (float)$price;     
    $cart->discount_cart = $refund;
    $retval -= $refund/$item['quantity'];
    return ($retval <= 0)? 0 : $retval;

where `$refund` in this case is 3.8219178082192, the quantity is 420, and the `$price` input parameter to the hook is 4.50. 

  [1]: https://github.com/woothemes/woocommerce/issues/3409
  [2]: http://i.stack.imgur.com/CG0lF.jpg

**Comment by mikejolley** [comment]
I think the logic you've posted above is wrong. 420 * 4.50 = 1890, not 315 in your screenshot. And your code sets one discount so any others will be ignored.

get_discounted_price() is also for 1 item, so the rounding error will be coming from there if present. You may want to test this against master where rounding for discounts was adjusted recently.

**Comment by EML-github** [comment]
My mistake - the quantity wasn't 420 - it was 70.19. Nevertheless, this is a real issue, which I'll explain in 3 different ways below, with real numbers, which I've just regenerated. First, though, I'll just point out that there are no other discounts involved - the point of using `woocommerce_get_discounted_price` here was to find a dynamic alternative to coupons, which are specific to products, not customers.
## (1)
Heuristically, with no numbers: the result is by definition wrong. Whatever rounding is or isn't used, the software must ensure that a displayed sub-total, plus a displayed discount, must equal the displayed total. If they don't, then something has gone wrong.
## (2) 
not an explanation, but an observation, with a possible explanation. In this case, my debug output (`print_r($item)`) shows
```
[line_total] => 312.0331
[line_subtotal] => 315.855
```
The total discount is 3.8219178082192. If we assume that you've somehow stored the discount internally to 4 places, we get a discount 3.8219, and the 3 numbers add exactly. Here's the problem: the fractional part of the sum of the discount and the total is exactly 0.855. However, you've rounded up the `line_subtotal` for display (see the image) to 315.86, but you *haven't* subtracted a penny from either of the other 2 figures to take this into account. You can't just round: you have to apply logic and correct afterwards.
## (3)
The real code, with the real numbers:
```
add_filter(
   'woocommerce_get_discounted_price', 'sa_get_discounted_price', 10, 3);
function sa_get_discounted_price($price, $item, $cart) {
   ...set $refund from the session data
   $retval = (float)$price;
   $cart->discount_cart = $refund;
   $retval -= $refund/$item['quantity'];
   return ($retval <= 0)? 0 : $retval;
}  // sa_get_discounted_price()
```
The values of the variables, and the return value, are:
```
$refund               3.8219178082192
$price                  4.50
$item['quantity']   70.19
return value         4.4455489698216
```
In other words, I want to apply a discount of ~3.82 for this customer, but the code won't let me do this, so I have to split it up over the quantity of 70.19.
So, somewhere later in the code, you're multiplying the return value by 70.19, and rounding to 4 places, to get the observed value of 312.0331.  
I take your point about the pototential rounding error from applying a discount to one item, and that was also my initial thought. However, I don't have any alternative (that I'm aware of); this appears to be the only route to apply a non-coupon discount. And, second, this would only be an issue when mixing precisions in some non-obvious way.

## Master
I can't really test against head/whatever - this is a production system. However, if you can let me know where the rounding code is, I  can test this particular case agaist the current 2.3.7, and then apply any rounding-related changes.

Thanks.

**Comment by mikejolley** [comment]
@EML-github just to confirm - you have a non-integer qty of 70.19?

**Comment by EML-github** [comment]
Yes, that's right - radical, I know... :)
It's a virtual product, priced per member-year, with variable start and end dates, so it never ends up as an integer. I did some Googling on this some time ago and it seems to be common.

**Comment by mikejolley** [comment]
@EML-github

> In other words, I want to apply a discount of ~3.82 for this customer, but the code won't let me do this, so I have to split it up over the quantity of 70.19.

I think thats false. You want to discount the user 3.82, but the cart itself will spread this across the items for you. If I substitute 3.82 as the $refund I get this:

https://dl.dropboxusercontent.com/s/2g7onn5sd07h66p/2015-05-29%20at%2015.25%202x.png?dl=0

That appears correct.
