### ISSUE TITLE
Woocommerce mobile CSS configuration does not show remove product link

### ISSUE THREAD

**Issue by milque** [woothemes/woocommerce#8231]
This is what we've uncovered from CSS:

media="all"
@media only screen and (min-width: 768px)
table.cart .product-remove, table.cart .product-thumbnail, table.cart .product-price {
  display: table-cell;
}
media="all"
table.cart .product-remove, table.cart .product-thumbnail, table.cart .product-price {
  display: none;
}

We can (sort of) guess and see some logic in removing pictures from the mobile cart (e.g. speed, although these days visual cues are good converters), but why the product cannot be removed from a mobile device is strange.

Can we recommend that this is re-assesed. Thanks.

**Comment by jameskoster** [comment]
Are you using the latest version of WooCommerce?

In previous versions the only way to remove products from the cart was to set the quantity to 0. But that didn't work for single-quantity-purchasable products so we added the remove button back.

Should look like this: https://www.dropbox.com/s/zz9lo9qu1o9qzuj/Screenshot%202015-05-28%2011.34.57.png?dl=0

I suspect that CSS is coming from your theme.

**Comment by milque** [comment]
The CSS might well come from the Definition theme. Have those changes made in WooCommerce been communicated to colleagues in WooThemes? We're using the latest versions of both.

Thanks again.

**Comment by jameskoster** [comment]
Our WooCommerce themes roll their own CSS. I'll open an issue on the Definition theme to address this in the next release. For now I suggest making this tweak in a child theme / custom CSS plugin.

**Comment by milque** [comment]
Appreciated James.

**Comment by ivans90** [comment]
<?php
echo apply_filters( 'woocommerce_cart_item_remove_link', sprintf( '<a href="%s" title="%s"><i class="pe-7s-close">xxxx</i></a>',

 esc_url( WC()->cart->get_remove_url( $cart_item_key ) ), __( 'Remove this item', 'woocommerce' ) ), $cart_item_key );
						?>

**Comment by ivans90** [comment]
why is this not working on mobile? Seems fine on pc.
