### ISSUE TITLE
Hold stock input too short

### ISSUE THREAD

**Issue by kieranbarnes** [woothemes/woocommerce#8233]
If we want to hold stock for more than 99 minutes the subsequent digits aren't visible in the input field
Example, 10080 minutes is set here (7 days), only 100 is shown, it's hard to see the actual number

![wordpress](https://cloud.githubusercontent.com/assets/1001484/7841206/ede74fda-0492-11e5-92ea-7dc309395e56.png)

There is an inline style `style="width: 50px;"`. Consider changing to something larger?

**Comment by claudiosmweb** [comment]
f503cda8745bed2410ec0086971232ae759e2ef5
