### ISSUE TITLE
Maximum spend limit error

### ISSUE THREAD

**Issue by seanreloaded** [woothemes/woocommerce#8234]
When trying to use a coupon with a maximum spend limit, even if your order subtotal is below the spend limit, an error is triggered: http://cld.wthms.co/15Kuk

To recreate the error:
1. Create a new coupon, using either amount or percentage as the discount, and assign it to a particular product. Set the spend limit to more than the product's price.
2. Put the product in your cart, and try to use the coupon from the cart page. Then you'll see that maximum spend limit error.

@ChromeOrange

**Comment by mikejolley** [comment]
Please search past issues ;) https://github.com/woothemes/woocommerce/issues/8207

**Comment by seanreloaded** [comment]
Argh, sorry @mikejolley. I realized that when I searched I was only looking at open issues. :(
