### ISSUE TITLE
Required shipping fields not checked for virtual products when using woocommerce_cart_needs_shipping_address

### ISSUE THREAD

**Issue by n-dawson** [woothemes/woocommerce#8235]
Shipping fields that are marked as required aren't being checked for virtual products when 'woocommerce_cart_needs_shipping_address' is set to true.

This also means that the shipping address is blank in the admin.

**Comment by mikejolley** [comment]
How would we replicate this? Are you forcing woocommerce_cart_needs_shipping_address true? Virtual goods don't ship.

**Comment by n-dawson** [comment]
I'm going to setup a blank installation to verify it's definitely in WC and not a conflict elsewhere.

In our theme's functions.php we've used:

    add_filter( 'woocommerce_cart_needs_shipping_address', true, 50 );

We're using this to allow free shipping on certain products but not all. If a user adds a product to their cart that's set to virtual we want it to be shipped for free. If their cart contains a virtual product and a regular product we're expecting shipping to be calculated on the regular product.

If "ship to a different address" is selected when going through the checkout the shipping details aren't saved. In the admin a message is displayed on the product stating "No shipping address set". Even when the shipping address fields are set the information isn't saved.

If however you leave "ship to a different address" unchecked the shipping address shows the billing details as you'd expect.

I've checked in the database and the shipping fields are empty under the order post meta.

**Comment by n-dawson** [comment]
I've been able to replicate this issue on a blank installation.

Setup:

WordPress 4.2.2
WooCommerce 2.3.9

Theme: TwentyFifteen

1. Add the need shipping address filter to the bottom of functions.php

    add_filter( 'woocommerce_cart_needs_shipping_address', '__return_true', 50 );

2. Create a test product that's virtual and free.

3. Purchase the product and fill in your billing details. Leave "ship to a different address" checked but don't enter any shipping information.

The required fields are ignored and the order is processed. In the admin the shipping information will be blank.

If you repeat this process but uncheck "ship to a different address" the shipping information displays correctly.
