### ISSUE TITLE
[bug] shipping method class namespace

### ISSUE THREAD

**Issue by andrewmclagan** [woothemes/woocommerce#8237]
It seems woocommerce does not handle PHP namespaces very well

Just created a shipping method within a plugin (my first foray into woocommerce)

the shipping method class has a name space: `CompanyName\Shipping\ShippingMethod`

and now when in the admin and clicking on the settings page for this shipping method i get a blank screen:

Although.. in the address bar the url shows `...section=companyshippingshippingmethod` which by my assumption, woocommerce is trying to use the class name to initialise the shipping method, although no-one has ever considered namespaces?

I have not looked too deeply although this seems to be the case...

**Comment by roykho** [comment]
PHP namespaces support is 5.3 +.  There are still some hosts that are using 5.2...

**Comment by andrewmclagan** [comment]
Yes but why not support namespaces anyway its possible to support both.

Any PHP half decent PHP dev is using namespaces. 

The issues is in `line 178` of class `WC_Settings_Shipping`.

`if ( strtolower( get_class( $method ) ) == strtolower( $current_section ) && $method->has_settings() ) {`

this can be easily fixed...

**Comment by andrewmclagan** [comment]
please re-open this issue and i will do a PR

**Comment by andrewmclagan** [comment]
the fix would be 

`if ( strtolower( stripslashes(get_class( $method )) ) == strtolower( $current_section ) && $method->has_settings() ) {`

**Comment by andrewmclagan** [comment]
created pull request

**Comment by andrewmclagan** [comment]
The more I look into this bug, the more I realise how moving forward is going to be a big problem with namespaces. The namespace concept is definitely a huge leap forward, the broader PHP community has been using for some time now.

Simple using a class name as the $current_section id is a very bad idea, and even presents a security risk. Classes are being directly instantiated via this variable which basically comes from a URL string, pretty bad practice in my opinion.

"PHP namespaces support is 5.3 +. There are still some hosts that are using 5.2..."

That is not an excuse. Holding back development simply because some people are on legacy servers, that is always going to be the case.... Supporting namespaces will not require a breaking change for these legacy PHP 5.2 - systems.

This pull request will be updated to reflect a "best practice approach" to the issue.

**Comment by andrewmclagan** [comment]
To work-around the current shortcommings of WooCommerce in relation to modern PHP namespacing and best practices here is my suggestion for those developers:

* Namespace all your classes as per normal PSR-0 though to PSR-4... whatever you want
* create a folder called `./Legacy` or something similar
* create a class and extend it from the namespaced version e.g:

	<?php 
	
	use RipeAndRaw\Shipping\ShippingMethod;
	
	include_once __DIR__.'/../woocommerce/includes/abstracts/abstract-wc-settings-api.php';
	include_once __DIR__.'/../woocommerce/includes/abstracts/abstract-wc-shipping-method.php';
	
	/**
	 * Legacy non-namespaced shipping method
	 *
	 * @class  RAR_ShippingMethod
	 * @author Andrew McLagan <andrewmclagan@gmail.com>
	 */
	
	class RAR_ShippingMethod extends ShippingMethod 
	{
		/**
		 * Constructor
		 *
		 * @return void
		 */
		public function __construct() 
		{
			parent::__construct();
		}
	}

**Comment by mikejolley** [comment]
@andrewmclagan Whilst we'd all love to drop 5.2, we cannot so long as WordPress itself supports 5.2 as the minimum version. https://wordpress.org/about/requirements/

When WP drops 5.2 support officially, we'll do the same. Right now however, and based on our stats which does show a large proportion of users on 5.2, our hands are tied.

Note: we also made the decision to follow WP Coding Standards on class naming conventions just so you're aware https://make.wordpress.org/core/handbook/coding-standards/php/

**Comment by andrewmclagan** [comment]
Although we could support addons that use namespacing with very little work.

There would be no BCs

**Comment by Ganganation** [comment]
@andrewmclagan thank you for your example it really helped! I think it would be great if Woocommerce would support namespaces in this fashion. Like you said trough addons would already be awesome.
