### ISSUE TITLE
available_payment_gateways seem to misfunction

### ISSUE THREAD

**Issue by vonsch76** [woothemes/woocommerce#8239]
Hi, available_payment_gateways function seem to run for each item in the cart. This would not be a problem but it seem to start from scratch - so modified data is not committed. 

I have the following filter in functions.php that removes a gateway if coupons are applied.

```
// remove gateways if coupon as a payment is not allowed
add_filter('woocommerce_available_payment_gateways','filter_gateways',1);

function filter_gateways($gateways){
	global $woocommerce;
	foreach ($gateways as $gateway)  // inserted for debug.
		echo gateway . $gateway->id;

	// remove kupon gateway if voucher is applied
	if( ! empty($woocommerce->cart->applied_coupons) ) {
		unset($gateways['wcCpg1']);
		$warningmessage = qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage( '[:hu]hajoznijo.hu vouchernél kupon nem érvényesíthető.[:en]Coupon(s) and hajoznijo.hu vouchers can not be applied together.[:]');
		wc_print_notice( $warningmessage , 'error' );
		foreach ($gateways as $gateway) 
			echo gw_changed_kupon . $gateway->id;
		return $gateways;
	}
}
```

In WC 2.3 this generates the following output (4 items in cart)

gateway bacs gateway paypal gateway wcCpg1

 (error message)   Coupon(s) and hajoznijo.hu vouchers can not be applied together.

gw_changed_kupon bacs gw_changed_kupon paypal

(edited the first iteration to make it better visible)

gatewaybacsgatewaypaypalgatewaywcCpg1

    Coupon(s) and hajoznijo.hu vouchers can not be applied together.

gw_changed_kuponbacsgw_changed_kuponpaypal 
gatewaybacsgatewaypaypalgatewaywcCpg1

    Coupon(s) and hajoznijo.hu vouchers can not be applied together.

gw_changed_kuponbacsgw_changed_kuponpaypal
gatewaybacsgatewaypaypalgatewaywcCpg1

    Coupon(s) and hajoznijo.hu vouchers can not be applied together.

gw_changed_kuponbacsgw_changed_kuponpaypal

The problem is that although wcCpg1 gateway was removed in the very first iteration, it returns (!!!) in the second.

In WC 2.2 the output is the correct one (3 items in the cart)

gatewaypayupaisagatewaybacsgatewaypaypalgatewaywcCpg1

    Coupon(s) and hajoznijo.hu vouchers can not be applied together.

gatewaypayupaisagatewaybacsgatewaypaypal 

The error messages are standard WC messages, do did not include as an image, sure you can imagine it. Can you please check?
Thanks, Kornel

**Comment by mikejolley** [comment]
It does not run for all items in the cart. It just happens to be called via get_available_payment_gateways() 4 times during checkout.

Use https://github.com/woothemes/woocommerce/blob/10dac6fedd911e0890253412d98d0d6bc843a14d/includes/wc-notice-functions.php#L57 to see if its already added.

**Comment by vonsch76** [comment]
Mike, thanks, but unfortunately this will not solve my problem. As the
wc_print_notice() displays the notice immediately, the spool will be empty.

The issue seem to be similar with wc_add_notice() as the message is
displayed and the spool gets empty.

Is there a way to display only one warning and turn off a payment gateway
parallel?

Kornel

**Comment by mikejolley** [comment]
You could set a global once you've output your message and check for this. This is a getter function so you cannot stop it running multiple times.

**Comment by vonsch76** [comment]
I see that, unfortunately global also does not work it seem to have 2x2
iterations. Kornel
