### ISSUE TITLE
How to change Sender's Email in WooCommerce?

### ISSUE THREAD

**Issue by heartbreakkid58** [woothemes/woocommerce#8240]
WooCommerce -> Settings -> EmailS -> the first two options, "FROM: Name, FROM: Email", are the Senders email and name. When order is placed notification email sent to both Shop Manager and Customer from the same Sender's email and name (which we set from admin dashboard).

When Customer replies to that email, he basically reply to Shop Manager and it works fine.

But Shop Manager receives the notification email from his (given) email address, in actually there would be client's email.

P.S: I want that Shop Manager gets email from customers billing email, and customer gets it from Shop Manager's given email.

https://wordpress.org/plugins/woocommerce/

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
