### ISSUE TITLE
Link All Variations creating duplicates of first 50 variations

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#8241]
When attributes have been added to a product, where the combination of their terms would equal more than 50 variations, the Link All Variations button will add the first 50 as expected. However, the next time you click Link All Variations, it should link variations 51-100, but it seems to duplicate the first 50.

**Comment by keninbassart** [comment]
Seems as if this can be avoided by hitting save in between linking variations but with large number of variations can be difficult/confusing to track which ones were/ were not created
