### ISSUE TITLE
Clean up Flat Rate Shipping UI + labelling

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8243]

**Comment by mikejolley** [comment]
Looking at this the only way I see of making meaningful improvements would be through #8294 so we can get rid of some of the existing options. Can only do small tweaks in this milestone.

**Comment by mikejolley** [comment]
Worked on a simplified UI which removes the old addon and additional rates causing issues in support.

Still todo in branch:

- [ ] Upgrade routine
- [ ] Upgrade notice (if using dropped feature)
- [ ] Apply changes to international shipping
- [ ] Apply changes to on-boarding wizard

**Comment by franticpsyx** [comment]
@mikejolley - should we expect people who use Add-on Flat Rates to add them back in using the new hook?

It definitely makes things easier to move with #8294 by dropping the current way Add-On flat rates work, but are we going to provide a (temporary) solution for the loss of functionality (if any)? Perhaps a .org plugin that will add back a "friendlier" version of the old UI for creating Add-on flat rates? Can you share some details about what you have in mind, or should I just wait for the missing parts of the picture (todo in branch)? Cheers

**Comment by mikejolley** [comment]
@franticpsyx either a functionality plugin, pure snippets only, or having the field only if set (existing users).

**Comment by franticpsyx** [comment]
>having the field only if set (existing users)

Just went through the flat-rate branch. Good call :+1:
