### ISSUE TITLE
[bug] [security] shipping method class namespace v2

### ISSUE THREAD

**Issue by andrewmclagan** [woothemes/woocommerce#8248]
Im re-opening this issues ref #8237.

I believe there is a latent security issue with the current methodology of admin settings sections. Also this issue causes a lack of support for class namespacing in extensions.

## ISSUE 1
Currently there is a global variable called `$current_section`  that is used as a direct reference to the current section of a  settings page. This variable is assumed to be a class name and directly instantiated. Even worse this is defined in user-land via a URL parameter. A very quick test reveals i cant easily instantiate an instantiate of `\mysqli`. A built in MySQL db connector object.

## ISSUE 2
The little validation that is run over this variable strips away any namespace that is applied to the class.

### Solution

Use the `$class->id` parameter of the class as an identifier and then instantiate any classes via the `ExampleClass::CLASS` static, or something similar. This would also support PHP 5.3+ name-spacing.

![screen shot 2015-05-29 at 10 35 40 am](https://cloud.githubusercontent.com/assets/1073259/7874114/798be7b0-05ee-11e5-8b37-12ef9787e18f.png)

![screen shot 2015-05-29 at 10 37 13 am](https://cloud.githubusercontent.com/assets/1073259/7874127/b04fa192-05ee-11e5-9097-fcd64cb71e14.png)

**Comment by mikejolley** [comment]
@andrewmclagan can you elaborate on your solution a bit more? Bare in mind, any class changes are going to break *a lot* of extensions.

**Comment by mikejolley** [comment]
Nvm

**Comment by mikejolley** [comment]
Resolved here: https://github.com/woothemes/woocommerce/commit/1e3fcd0e6dcf765008b87178bc63d38907b48259
