### ISSUE TITLE
API - custom taxonomies

### ISSUE THREAD

**Issue by PetterRuud** [woothemes/woocommerce#8249]
I was wondering if there would a feature for adding custom taxonomies to the create product endpoint.
I use a brand plugin and want to add brand in the API.

ex.
	'title'=> $front_product->Name,
	'type'  => 'variable',
	'managing_stock' => true,
	'stock_quantity' => 2,
	'brands' => 'BrandName',

Thanks in advance

**Comment by claudiosmweb** [comment]
The brand plugin need to create an endpoint or methods to allow this.
Or you can use the WordPress Rest API for generic this.
