### ISSUE TITLE
Product Price not Visible on Single Product page

### ISSUE THREAD

**Issue by ankitbaid** [woothemes/woocommerce#8253]
Hi,

I updated to woocommerce 2.3.9 and after updation I am unable to see prices of simple products on single Product page.Prices are seen in the product pages but not on the single product page

Can you please help me

![no price](https://cloud.githubusercontent.com/assets/7249166/7885347/f163e0ec-0640-11e5-942f-1dd53ed05621.JPG)
![price there](https://cloud.githubusercontent.com/assets/7249166/7885355/06619430-0641-11e5-8c37-5601bd6edd17.JPG)

**Comment by mikejolley** [comment]
This will most likely be a bug in your theme, since this is not affected other stores. Confirm by switching to the Twenty Twelve theme, then contact the theme developer for assistance.

**Comment by ankitbaid** [comment]
Hi Mike,

It would be very helpful if you could tell me what to look for and where for the same so that I can correct it myself.

**Comment by mikejolley** [comment]
Without debugging your theme I cannot tell you the exact location of the issue..

**Comment by ankitbaid** [comment]
What do you need? I can provide you with the theme

**Comment by mikejolley** [comment]
It isn't really my place to debug 3rd party themes sorry. Ensure its that first (as stated above) and go to the developer please.
