### ISSUE TITLE
closest('div') in country-select.js

### ISSUE THREAD

**Issue by cdukes** [woothemes/woocommerce#8255]
Searching for the closest div in https://github.com/woothemes/woocommerce/blob/master/assets/js/frontend/country-select.js breaks state/province replacement when using a select form element replacement (like uniform.js)

This was a tricky issue to hunt down, and maybe it would be better to use a more descriptive selector here? `.woocommerce-billing-fields, .woocommerce-shipping-fields` are included in the standard templates, make it clear at a glance what the code is doing, and are unlikely to be overwritten/interrupted.

**Comment by mikejolley** [comment]
Not really possible because these fields can be used in other locations other than checkout. Maybe we can target a closer selector first to ensure it 'breaks out' of the select field itself.

**Comment by cdukes** [comment]
Great, thanks.

**Comment by sandrodz** [comment]
I don't like this solution, it means we have to stick to html structure predefined by woo default template. What if we want to use bootstrap? bootstrap has nested input structure (it would need extra parent() on the selector).

I think it should be abstracted, and grouped via class, that way html structure is not dictated.

**Comment by mikejolley** [comment]
@sandrodz form-row is the wrapping p element. Extra divs around inputs wouldn't matter.

**Comment by sandrodz** [comment]
@mikejolley  well, look at this: 
![screen shot 2016-02-03 at 1 38 02 pm](https://cloud.githubusercontent.com/assets/8479569/12778286/68b1e71c-ca7b-11e5-975e-53195272d19f.png)

`$wrapper` inside `country-select.js` equals to div with class `u-marginBottom-xs` now, and this wrapper only contains 1 input, thus script fails.

**Comment by sandrodz** [comment]
and don't get me started with the inputs hardcoded in this file... this approach is not very customisable. 
![screen shot 2016-02-03 at 1 43 02 pm](https://cloud.githubusercontent.com/assets/8479569/12778432/10285814-ca7c-11e5-8a47-ff897b820e2b.png)

**Comment by mikejolley** [comment]
Why would you need to wrap the p in a div instead of adding the class to the actual element? It's just extra markup for no reason?

If you can suggest a more flexible way which works across all themes, go ahead. But I fear if you rely on a certain classnames, some themes might not have it and will break anyway.

**Comment by reigelgallarde** [comment]
it's hard making this flexible across all themes. We can try to improve relating to this 2 lines though.
````
$wrapper  = $( this ).closest('.form-row').parent(),
$statebox  = $wrapper.find( '#billing_state, #shipping_state, #calc_shipping_state' ),
````
we can add:

````
while ($statebox.length < 1) { // it field to locate these state boxes
       // let's move up. we're not afraid to move up, we started from .form-row
       $wrapper = $wrapper.parent(); 
      // find state boxes again.
      $statebox  = $wrapper.find( '#billing_state, #shipping_state, #calc_shipping_state' );
}

**Comment by sandrodz** [comment]
@mikejolley well, that's another limitation of wc, namely `woocommerce_form_field()` generator. and as you can see class I use there is purely of visual character `u-marginBottom-xs`, I don't want `woocommerce_form_field()` to output it cause on some other pages where `woocommerce_form_field()` is used I need different margin or no margin at all.

**Comment by mikejolley** [comment]
@reigelgallarde Looks less efficient, for something edge case.

@sandrodz You know CSS can target `.checkout p.form-field`, vs some other page's form-field? CSS can do everything you're hacking in with markup changes.

Markup should not be used purely for styling purposes.

**Comment by sandrodz** [comment]
@mikejolley oh no, thank you :) this is not how we write modern component-level encapsulated front-end.

**Comment by mikejolley** [comment]
.woocommerce-billing-fields would have been a good class to find (closest) however, it relatively new and themes might lack it.

@reigelgallarde maybe thats the best way. Use that class (closest) and if its not found, do the parent() thing.

**Comment by reigelgallarde** [comment]
I have doubts about its efficiency... but this is how it will be then..

````
$wrapper  = $( this ).closest('.woocommerce-billing-fields, .woocommerce-shipping-fields'),
$statebox  = $wrapper.find( '#billing_state, #shipping_state, #calc_shipping_state' ),
````

then down below...

````
if ($statebox.length < 1) { // it failed to locate these state boxes
       $wrapper  = $( this ).closest('.form-row').parent();
       while ($statebox.length < 1) { 
             // let's move up. we're not afraid to move up, we started from .form-row
             $wrapper = $wrapper.parent(); 
             // find state boxes again.
             $statebox  = $wrapper.find( '#billing_state, #shipping_state, #calc_shipping_state' );
      }
}

**Comment by reigelgallarde** [comment]
I have another suggestion....

why don't we just create custom events/triggers that expect these variables...
then call that trigger on the change event...

here's a simple example of what I mean: https://jsfiddle.net/zvwkwygq/
and here's how other plugins can change the variables without problems: https://jsfiddle.net/zvwkwygq/1/

try changing the value of the select to spot the difference...

**Comment by iansvo** [comment]
I opened a duplicate issue on this a couple of days ago which ultimately related to Bootstrap (like some of the above posters). 

That being said, I thought I'd drop in a quick workaround for anyone using Bootstrap and WooCommerce that I found useful for my own purpose.

> form-billing.php

````
<?php foreach ( $checkout->checkout_fields['billing'] as $key => $field ) : ?>
<?php 
	ob_start();
	woocommerce_form_field( $key, $field, $checkout->get_value( $key ) );
	$form_field = ob_get_clean();
	$form_field = preg_replace('/form-row form-row/', 'form-row form-group clearfix', $form_field);
	echo $form_field;
?>
<?php endforeach; ?>
````

> form-shipping.php

````
<?php foreach ( $checkout->checkout_fields['shipping'] as $key => $field ) : ?>
<?php 
    ob_start();
    woocommerce_form_field( $key, $field, $checkout->get_value( $key ) );
	$form_field = ob_get_clean();
	$form_field = preg_replace('/form-row form-row/', 'form-row form-group clearfix', $form_field);
	echo $form_field;
?>
<?php endforeach; ?>
````

>your-theme-scripts.js
````
    function checkoutLayout()
    {
        $('.woocommerce-checkout form .form-group:not(.exclude-styles)').children('label').wrap('<div class="form-item-wrap fluid-col-xs-16 fluid-col-md-4"></div>');
        $('.woocommerce-checkout form .form-group:not(.exclude-styles)').children('input').wrap('<div class="form-item-wrap fluid-col-xs-16 fluid-col-md-12"></div>');
        $('.woocommerce-checkout form .form-group:not(.exclude-styles)').children('.select2-container').addClass('form-item-wrap fluid-col-xs-16 fluid-col-md-12');
        $('.woocommerce-checkout form .form-group:not(.exclude-styles)').children('textarea').wrap('<div class="form-item-wrap fluid-col-xs-16 fluid-col-md-12"></div>');
        $('#billing_address_2_field').prepend('<div class="form-item-wrap fluid-col-xs-16 fluid-col-md-4">&nbsp;</div>');
        $('#shipping_address_2_field').prepend('<div class="form-item-wrap fluid-col-xs-16 fluid-col-md-4">&nbsp;</div>');
    }

````

**Note**

1. Notice the selectors include a (not perfectly optimized) `:not` qualifier. This was done for styling purposes of my own and isn't an actual WC/BS thing.
2. Note that the actual column classes are custom (fluid-col-XX-XX). This setup was done for the form styling themselves.

Overall it's not a super elegant solution and I'm sure it could be improved. This is just a modification I've made to some existing older code we've been using, so again you may want to review it for your own usage. 

Hope that helps someone while we work on a more official solution for this type of thing.

**Comment by m-f-work** [comment]
Code we make the update more dynamic by updating these lines?

> woocommerce/assets/js/frontend/country-select.js

`var $country_input = $( this ).find( '#billing_country, #shipping_country, #calc_shipping_country' );`
to
`var $country_input = $( this ).find( 'select[id*="_country"' );`
and this:
`$statebox = $wrapper.find( '#billing_state, #shipping_state, #calc_shipping_state' );`
to 
`$statebox = $wrapper.find( '#billing_state, #shipping_state, #calc_shipping_state' );`

The point here is:
I'm trying to add extra addresses to Wooommerce by this link:

> my-account/edit-address/addr_prefix

everything is working as expected only the country isn't updating the state because the ids are written static

Thanks in advance
