### ISSUE TITLE
how to add a variable product into an order

### ISSUE THREAD

**Issue by crazypepper** [woothemes/woocommerce#8257]
I tried to add an variable product into an order
    $my_order = wc_create_order(array('status'=>'processing','customer_id'=>$order->get_user_id()));
    $my_product= new WC_Product($item['variation_id']);
    $my_order->add_product( $my_product, 1 ); 
    $my_order->set_address( $billing_address, 'billing' );
    $my_order->set_address( $shipping_address, 'shipping' );
    $my_order->calculate_totals();
 when I check order i just create, variable selection will not be display in order details,however, the price is correct. How to fix that?

**Comment by roykho** [comment]
Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com
