### ISSUE TITLE
COD orders are showing Rs 0 at backend. 

### ISSUE THREAD

**Issue by ankitbaid** [woothemes/woocommerce#8259]
Hi,

I placed an order and used payment gateway as COD. The problem I am facing is that at the backend when I view the order from admin It shows amount as 0. I am attaching a screenshot for the same.

Regards,
Ankit
![error in cod](https://cloud.githubusercontent.com/assets/7249166/7910517/0c626d30-0873-11e5-84c2-d05d2bf7c2d6.JPG)

**Comment by mikejolley** [comment]
I don't think this has anything to do with COD. COD gateway has no price altering logic. 

https://github.com/woothemes/woocommerce/blob/master/includes/gateways/cod/class-wc-gateway-cod.php

Check other plugins. 

Here is a working example from my side https://dl.dropboxusercontent.com/s/1gqxilpdbr0d3t7/2015-06-01%20at%2011.08%202x.png?dl=0

**Comment by ankitbaid** [comment]
The thing is that Woocommerce PDF Invoices plugin for creating invoices is showing correct amount but on orders page Total is showing 0 for COD as well as Direct Payment.

**Comment by ankitbaid** [comment]
![cod](https://cloud.githubusercontent.com/assets/7249166/7911566/d9bf1cd4-087c-11e5-9844-aef352fbc6f5.JPG)
![cod 12](https://cloud.githubusercontent.com/assets/7249166/7911569/df612632-087c-11e5-9a41-e655e95e0a53.JPG)

Please refer the above images.

**Comment by mikejolley** [comment]
Rule out the other plugins; I doubt this is core.

**Comment by ankitbaid** [comment]
Another thing.. for dollars its showing correct but for Indian Rupees its showing Rs0.

Please check the screenshots.

![cod dollar](https://cloud.githubusercontent.com/assets/7249166/7912040/70febaf6-0881-11e5-93e1-5443c714a17a.JPG)

**Comment by ankitbaid** [comment]
Hi Mike,

I was able to get arround it.. problem was with the currency switcher. I had put IND currency to 0.

Thanks for the help.
Regards,
Ankit
