### ISSUE TITLE
How do I get the API faster?

### ISSUE THREAD

**Issue by fabianhenzler** [woothemes/woocommerce#8262]
DB Query of all products takes 6ms
WP_Query takes 1000ms
WooCommerce API takes more than 5000ms

**Comment by claudiosmweb** [comment]
The API does a lot more than consult like WP_Query, are sanitized data, hooks are triggered and etc ;)
If you have suggestions for improving performance, send an Pull Request.

**Comment by maxrice** [comment]
@fabianhenzler there's quite a bit of overhead in the HTTP request which likely accounts for most of that 5000ms.
