### ISSUE TITLE
Checkout Address UI: Account / Address / Country

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#8263]
Who put the Country as the first field on the addresses of Woocommerce? 

Who thought it made sense to say "United Kingom, Andrew Lazarus, Eve, 51 Notingham..."? I've never once written a letter addressed to a country before a person, nor have I even had an invoice that read that way too.

It makes no sense, and I put forward an issue to have it placed in a contextual location, such as with the actual address.

**Comment by mikejolley** [comment]
@yratof Address fields vary from country to country. How is it good UI to have country last, and then have all the fields you've already (attempted) to fill, change?

**Comment by claudiosmweb** [comment]
Each country has a format: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-countries.php#L347-L380

**Comment by mikejolley** [comment]
Asked @jameskoster to review too for feedback as he is UI guy. If you have suggestions based on the above info, go wild :)

**Comment by yratof** [comment]
it needs to be with the address; It can still go first in order of the address section – It doesn't affect your name or company when you change country.

Can you find another example where putting the country first works? For me, it's confusing, especially when trying to style this forms. If you go for a two column layout, it doesn't make sense that it reads `country | name". In fact, it works for no layouts other that single columns stacked.

I'm not the only one that thinks this right?

**Comment by mikejolley** [comment]
It can affect certain locales. e.g. China where they have last name before first name traditionally.

**Comment by mikejolley** [comment]
p.s. I've renamed the issue title to be a bit more polite..

**Comment by jameskoster** [comment]
It's been like this since version 1. You're the first person to mention it so it's probably not a big deal. Definitely not worth being rude about.

I agree with you though, it would make more sense to place the country input with the other address fields. We can tweak this in the next major release.

Please think before you post. Adding "Who the heck is in charge of UI?" to your issue title makes you look a bit of a dick. WooCommerce is an open source project, we're collectively in charge of all aspects of the project. Be constructive and help enhance the community :-)

**Comment by yratof** [comment]
yeah, I knew from the moment I wrote it it was going to cause issues – Not intending to be rude though, so i'm sorry everyone. But I do think country belongs with it’s siblings in the address area – shipping & bill addresses, checkout and account.

On a global scale – It might not be so easy to cater for languages that swap around first name and surname, I can only picture that with CSS you could swap the fields around. The only suggestion to make these forms universal is to give control to them in the dashboard. Perhaps in the settings you can add set fields, maybe even custom ones. That way, you can reorder it all. That is a much bigger issue than moving one <select> box though, so I’ll leave that for another issue.

Cheers James
