### ISSUE TITLE
Plural forms need in class-wc-admin-post-types.php

### ISSUE THREAD

**Issue by Almaz** [woothemes/woocommerce#8264]
:boom:There are some strings that create inconvenience for some difficult languages (like Russian) [here](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-frontend-scripts.php):
```
%qty% results are available, use up and down arrow keys to navigate.
Please enter %qty% or more characters
Please delete %qty% characters
You can only select %qty% items
```

:sparkles:I offer to use plural forms for them.

**Comment by claudiosmweb** [comment]
Don't can because it depends on JavaScript, the two ways must be available.
