### ISSUE TITLE
Stuck on wc-about

### ISSUE THREAD

**Issue by chrisvanpatten** [woothemes/woocommerce#8265]
Every time I upgrade WooCommerce, I get stuck on the wc-about screen. Any admin requests end up redirecting me to this page, and it's not possible to view any other page in the admin.

This has happened on the upgrades to WC 2.3.9 and 2.3.10. The only way to fix it seems to be reverting to the previous version and then re-running the upgrade.

**Comment by chrisvanpatten** [comment]
Worth noting that I'm managing plugin dependencies via Composer, not via the built in WordPress updater.

**Comment by mikejolley** [comment]
Using anything like memcache as well?

**Comment by chrisvanpatten** [comment]
Nope. The stack is... Pound, Varnish (although it's set to pass-through on wp-admin), PHP-FPM, nginx, and MariaDB. I can get specific version numbers if you think it'd help.

**Comment by mikejolley** [comment]
I was thinking it may be something similar to https://github.com/woothemes/woocommerce/commit/c9d4655ef11e57ac3543f96ab40ad92c69b3c06f

There is a transient set which forces the redirect. it's deleted here: https://github.com/woothemes/woocommerce/blob/2febc8f20a645b2fd56148544ca86530ab465518/includes/admin/class-wc-admin-welcome.php#L435 In your case, I don't think this is happening for some reason..

**Comment by chrisvanpatten** [comment]
I'll try to recreate this and look at the database for the transient to try to get a sense of what's happening. I'll report back.

**Comment by chrisvanpatten** [comment]
I'm definitely still getting this issue, after upgrading from 2.3.9 to 2.3.11. The database doesn't show any record of the `_wc_activation_redirect` transient either.

What's strange now is that I only get redirected to wc-about semi-randomly. The core WooCommerce settings pages seem to work without issue. Some other pages (update-core.php, plugins.php, and others) randomly redirect to wc-about, or don't... and I can't figure out why.

Also strange: my only working theory previously was that I was causing this problem by deploying plugins via Composer, but I ran this update directly with the WordPress plugin updater, and it still caused the issue.

Going to poke through server logs to see if I can find more...

**Comment by chrisvanpatten** [comment]
Further information: I'm debugging a bit, and noticing that the issue is that `get_transient( '_wc_activation_redirect' )` is returning true/1, even though the transient definitely does _not_ exist in the database. The question is why... I'll keep researching.

**Comment by chrisvanpatten** [comment]
So I think I can trace this back to something to do with the `woocommerce_version` option. For some reason, on my server, it's bouncing back and forth between 2.3.9 and 2.3.11, which is [triggering the installation process](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-install.php#L81) after the [version check](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-install.php#L35).

I have a theory about why this is happening, but I need to do some more research before I reach any conclusions.

**Comment by chrisvanpatten** [comment]
Final result: turns out this is a problem with nginx and php-fpm caching and resolving symlinks improperly, causing old versions of the site to load. (We use Capistrano to deploy, which is why we have symlinks in our paths.)

The simple fix is to replace references to `$document_root` with `$realpath_root` in your nginx fastcgi config. (Further reading: [this StackOverflow thread](https://stackoverflow.com/questions/19808884/nginx-and-or-php5-fpm-remembers-symlinked-root-directory) and this [GitHub issue](https://github.com/zendtech/ZendOptimizerPlus/issues/126) explain the issue in more detail.)

Ultimately, this is not a WooCommerce issue, so I'm going to close it up. Hopefully this is helpful to someone in the future though!
