### ISSUE TITLE
Move notices on Checkout 

### ISSUE THREAD

**Issue by anteksiler** [woothemes/woocommerce#8268]
I would like to move the notices inside checkout page. But I am not talking about "checkout notices", they are printed using ```wc_print_notices()```, but login errors like "ERROR: Invalid username. Lost your password?" are printed above everything else. I would like to move them inside the checkout page.

**Comment by mikejolley** [comment]
All notices go through a wc_print_notices function call. There happens to be one at the top of the checkout shortcode:

https://dl.dropboxusercontent.com/s/m21ro7m94xktio1/2015-06-05%20at%2011.05%202x.png?dl=0

That is where notices will appear. 

Other messages triggered from the checkout itself will be prepended above the checkout form:

https://dl.dropboxusercontent.com/s/xo53vg4mfou250t/2015-06-05%20at%2011.07%202x.png?dl=0

This cannot be changed.

**Comment by anteksiler** [comment]
Hi @mikejolley, but that is incorrect in my experience. I have added a login form to the start of the checkout. (Copied the login form on my account page to do this). When an incorrect username is entered, the message is display on top of the checkout page (not wc_print_notices)

**Comment by mikejolley** [comment]
If you're added the form code, you should be able to trace where the errors are coming from. If they are formatted like WC notices, it will be from a wc_print_notices function somewhere..

**Comment by anteksiler** [comment]
Here, please test this file: http://inft.ly/3h9pHDk (form-checkout.php file, with login form added). The errors are on top, not where wc_print_notices is run.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/d1e459bf5ddcb45d4d816a0976cc98f1b742310d/includes/class-wc-form-handler.php#L812

**Comment by anteksiler** [comment]
So login errors are not included in wc_print_errors? Any way to include them?

**Comment by mikejolley** [comment]
Yes they are included in wc_print_errors, just possibly a different call to wc_print_errors and not the one you have in your template.

Please note; github is for bug reports, not customisation help.

**Comment by anteksiler** [comment]
I think this is a bug, since users do not have any function other than "wc_print_errors" to display the errors?

**Comment by mikejolley** [comment]
I think you're misunderstanding me.

wc_print_errors() *is* used. It's just likely an earlier call to wc_print_errors, not the one in your template file.

**Comment by anteksiler** [comment]
Thanks for the clarification, but I thought checkout page only displays the form-checkout.php on load? Only other file that seems possible is cart-errors.php, which is not for checkout page but for cart page?

**Comment by mikejolley** [comment]
You could maybe add a debug_backtrace to wc_print_notices() - they you can see what is calling your notices exactly ;)
