### ISSUE TITLE
Pages Can't Be Created Because WC Thinks They Exist

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce#8269]
A few days ago I deleted my pages for some reason and wanted to recreate them. I go to `WooCommerce -> System Status -> Tools` and click `Install pages`.

![woocommerce_status_ _woocommerce_demo_store_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/7938990/d179ebf6-0905-11e5-900e-77706b5c7178.png)

I get the success message and attempt to load my cart page. I get a 404 error.

On the System Status page I see the pages are supposed to exist.

![woocommerce_status_ _woocommerce_demo_store_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/7939033/0ecbe05e-0906-11e5-8abd-b79f1d881eea.png)

The shop page works. All the rest bring up 404 errors. The pages aren't present under Pages.

I believe what's happening is that WooCommerce still believes those pages exist so it doesn't recreate them. We should make sure that we check to make sure the pages still exist.

**Comment by BFTrick** [comment]
Just wanted to add that I found the pages in the Trash.

Undeleting them fixes the issue. Is there a way to let the user know that the pages are in the trash? Or to go ahead and recreate them?

**Comment by claudiosmweb** [comment]
@BFTrick The pages need to be actually deleted, not just in the trash, I think we have notes on it somewhere.

**Comment by claudiosmweb** [comment]
Maybe we can delete the pages create it again (every time this button is clicked) and improve this button notes.

**Comment by BFTrick** [comment]
Yeah users don't know that the pages have to be permanently deleted. We could restore the pages that were in the trash. That's basically the same as deleting the pages and recreating them without having to deal with permalinks changing.

**Comment by claudiosmweb** [comment]
But if the shortcodes have been removed will have some problems, I've seen people generating pages again for having removed the shortcodes...

Do you think if is a good idea to take the pages back from trash, delete content and add the shortcode again?

So I think we can solve all problems.

**Comment by BFTrick** [comment]
Here's what I think would solve the problem:

* If no pages exist (published or trash) create new pages
* If a page is in the trash with the appropriate shortcode pull it out of the trash.
* If a page is in the trash without the shortcode leave it there and create a new page

**Comment by yratof** [comment]
What about if page is in the trash, permanently delete it & replace with fresh page – Showing a warning "This page exists in the trash, it will be permanently deleted are you sure you want to install pages?"

**Comment by BFTrick** [comment]
I'd rather make the choice for the user. Just pull it out of the trash as is.

**Comment by mehulkaklotar** [comment]
#8299 fixes the issue. 
Showing a warning to user seems bit confusing for user when page found in trash. Let the pages pull out of trash as it is changing their post status to publish is more convenient option.

**Comment by davidlenehan** [comment]
The fix above now accounts for all of the cases mentioned by @BFTrick...

> * If no pages exist (published or trash) create new pages
> * If a page is in the trash with the appropriate shortcode pull it out of the trash.
> * If a page is in the trash without the shortcode leave it there and create a new page
