### ISSUE TITLE
Amount in Refunds is displaying incorrectly

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#8272]
Once you have completed the order and then make a refund of some sort, this will record correctly.  however, when you to add another order and then complete that order, the refunded amout is no recorded in woocommerce reports.  i have not attemtped any other ways for this bug to appear.

thanks heaps

ps i am currecntly using woocommerce version 2.3.10 and wordpress version 4.2.2

**Comment by mikejolley** [comment]
Fully refunded orders will show up in the report date range of the original order. This is being fixed in 2.4.
