### ISSUE TITLE
Woocommerce Messages and Alerts

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#8275]
Looking at the markup for an alert with woocommerce, would it be worth wrapping the message in a `<span>` or similar element so we are able to target the button and the message separately?

Working on a mobile at the moment, the current markup is:
```
  <div class="woocommerce-message">
    <a class="button wc-forward" href=/cart/">View Cart</a> "Product Name" was successfully added to your cart.
  </div>
```
Which means on mobile, the button is large and the text inline with it doesn't flow nicely.

If we wrap the message in a span, we can then target this text and style it appropriately for other scenarios where the message isn't large enough to contain the button and text.

```
// Target the message, not the button
.woocommerce-message span {
  display: block;
  font-size: 0.8rem
}
```

**Comment by jameskoster** [comment]
I've considered this a few times myself. I'm unsure as to whether there are enough scenarios where the wrapper is relevant though. 

You could for example achieve the same thing with a couple extra lines of css;

`.woocommerce-message {
  font-size: 0.8rem;
}

.woocommerce-message .button {
  font-size: 1rem;
}`

In a case of occasionally using a few lines of extra css vs adding additional markup to every single message, I think just adding the CSS is probably better.

Can you think of a situation besides this where having the extra wrapping element might be useful?

**Comment by yratof** [comment]
I don't want to keep undoing everything with CSS ideally.

The issue is that without the message being wrapped, even if just by <em> or anything, is that it limits how you can style it.

Some examples:

Try limiting the width of the message without affecting the width of the message box.

Try putting an icon after the message to emphasise error or success messages.

.button class is uniform throughout the site, applying any styles within the message overwrites the buttons styles unless moved further down the CSS, this could be avoided if the text was targetable. 

Kind regards
Andrew

**Comment by jameskoster** [comment]
> Try limiting the width of the message without affecting the width of the message box.

> Try putting an icon after the message to emphasise error or success messages.

You can do both of those things without wrapping the message in another element. 

We could make the message content filterable. That way, if your theme needs to include a wrap, it can. Open a new issue for that if you like.

**Comment by lmartins** [comment]
It is really puzzling why the markup for these notification it is still so inflexible.
