### ISSUE TITLE
Logout redirection

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#8276]
The documentation at WooThemes lists the old way of changing the redirection after logging out: https://support.woothemes.com/hc/en-us/articles/202819256-Redirect-to-a-custom-page-after-logging-out

I think that there should be a logout URL in the admin settings of woocommerce.

`/wp-admin/admin.php?page=wc-settings&tab=account`

This way, we could have the redirection to the account page, which when not logged in, shows the login form styled for the website and not the default wordpress login.

Alternatively, we could have it redirect to home as standard with a woocommerce-message saying `"You have successfully logged out"`.

I'm finding that customers are confused when they log out and it takes them to a completely different looking website.

**Comment by mikejolley** [comment]
WC does not and should not hijack all logout links. The logout link WooCommerce is responsible for is the one on the account page:

https://dl.dropboxusercontent.com/s/758towyypoeq9ih/2015-06-05%20at%2011.45%202x.png?dl=0

This goes to:

`
https://local.wordpress.dev/?page_id=7&customer-logout
`

By default this redirects back to the account page (with login form).

Other logout links handle their own redirect and it would be down to the store owner/developer to define the redirect. or you can use our customer-logout endpoint.

**Comment by mikejolley** [comment]
Additional; that doc is out of date. https://github.com/woothemes/woocommerce/blob/master/templates/myaccount/my-account.php#L21
