### ISSUE TITLE
Product setup not displaying correctly

### ISSUE THREAD

**Issue by Mikehollingsworth** [woothemes/woocommerce#8280]
Since applying the latest Woocommerce update, the product setup is not displaying correctly - see screen shot attached!

It looks as though the columns are set to small so the text wraps vertically?

I have attached the system status log.

Many thanks in advance.

![screen shot 2015-06-03 at 19 33 37](https://cloud.githubusercontent.com/assets/12736015/7968272/90380e98-0a27-11e5-8b0e-d2469e54953a.png)

### WordPress Environment ###

Home URL: http://www.theflowershoppe.co.uk
Site URL: http://www.theflowershoppe.co.uk
WC Version: 2.3.10
WC Database Version: 2.3.10
Log Directory Writable: /homepages/21/d358429071/htdocs/clickandbuilds/WordPress/TFS/wp-content/uploads/wc-logs/
WP Version: 4.2.2
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.24
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.1.73
Max Upload Size: 8 MB
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Remote Post: 
Remote Get: 

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (22) ###

1&1 WP Wizard: by 1&1 – 2.0.1
Contact Form Builder: by WebDorado – 1.0.20
Contact Form by BestWebSoft: by BestWebSoft – 3.90
Disable Comments: by Samir Shah – 1.3.1
Google Analytics Dashboard for WP: by Alin Marcu – 4.7.3
Hide Title: by Brandon Kraft & Randall Runnels – 1.0.4
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
WooCommerce Table Rate Shipping Plus: by mangohour – 1.6.0
PayPal for WooCommerce: by Angell EYE – 1.1.6.2
PayPal Pro Credit Card gateway for WooCommerce: by johnwickjigo – 1.2.2
Regenerate Thumbnails: by Viper007Bond – 2.2.4
Responsive Lightbox: by dFactory – 1.4.14
Scroll Back to Top: by Joe Sexton – 1.1.3
Simple Wp Sitemap: by Webbjocke – 1.0.8
WooCommerce Checkout Manager: by Ephrain Marchan – 3.6.8
WooCommerce Customizer: by SkyVerge – 2.1.0
Woocommerce Poor Guys Swiss Knife: by Uli Hake – 2.2.4
Woocommerce Product Shippings: by Marco van Loghum – 1.2.0
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce: by WooThemes – 2.3.10
WooSidebars: by WooThemes – 1.4.2
WordPress SEO: by Team Yoast – 2.1.1

### Settings ###

API Enabled: –
Taxes Enabled: –
Shipping Enabled: 
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Shop Base: #706 - /shop-2/
Basket: #22 - /cart/
Checkout: #23 - /checkout/
My Account: #24 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: ThemeAlley.Business.Pro
Version: 1.0.7
Author URL: http://www.themealley.com/
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: Not Declared

### Templates ###

Overrides: –

**Comment by claudiosmweb** [comment]
This is happening because other plugins are adding more columns, simply hide the columns of other plugins within "Screen Options" menu.
