### ISSUE TITLE
Product Image Gallery Missing After Upgrading from 1.6.6 to 2.x

### ISSUE THREAD

**Issue by Luke-Lau** [woothemes/woocommerce#8285]
Just upgrading a WooCommerce 1.6.6 to the latest 2.3.10. Product image gallery disappears after the upgrade. I have tried upgrading from 1.6.6 to 2.05 first, then to 2.1.9, to 2.2.9, to 2.3.0, and finally to 2.3.10 (and many different combinations). No combinations worked. As soon as it hit 2.3.0, it disappears.

From my investigation, in 1.6.6, additional product images were just basic WordPress attachments of the product. In 2.x, there is new a separate meta box to upload/manage additional product images (Product Gallery). I also found a new meta key (_product_image_gallery) was created in 2.0.

None of the the 2.x (including the latest 2.3.10) updates (when I was asked to click the Run Updater button) appear to convert the 1.6.6 way of storing product images to the new way. Before 2.3.0, I was able to find code in the method get_gallery_attachment_ids (in abstract-wf-product.php) handling the backward compatibility. This backward compatibility code was removed in 2.3.0 and no update script to convert the data.

Would it be possible to get an update script to convert the data?

Thanks,

Luke

**Comment by mikejolley** [comment]
We don't have an update script for this - it was changed about 2 years ago.

If you want to write your own,

1. Use get_posts to get all products. Loop over them
2. Use https://codex.wordpress.org/Function_Reference/get_children to get attachment ids 
3. Update the gallery ids meta https://codex.wordpress.org/Function_Reference/update_post_meta

_product_image_gallery wants a string - comma separated list of attachment ids

**Comment by Luke-Lau** [comment]
I understand the change was two years ago. Anyone that have upgraded in the past and have not changed some of the products will have an issue when they upgrade to release 2.3.x. If products were updated or will be updated in 2.3.x, no problem. If someone has lots of products and will not be updating them, they will run into this problem.

The logic you have provided confirm (somewhat similar) to what I wrote. In case you would like to include in the next release (as an updater) or anyone needs this migration, here is the snippet I wrote:

$all_woocommerce_product_ids = new WP_Query(
		array(
			'post_type'      => 'product',
			'post_status'    => 'publish',
			'nopaging'       => TRUE,
			'posts_per_page' => 1,
			'fields'         => 'ids')
		);
if ($all_woocommerce_product_ids->have_posts()) {
	while ($all_woocommerce_product_ids->have_posts()) {
		$all_woocommerce_product_ids->the_post();
		$woocommerce_product_attachment_ids = array_diff(
				get_posts(
						array(
							'post_parent'    => get_the_ID(),
							'posts_per_page' => -1,
							'post_type'      => 'attachment',
							'orderby'        => 'menu_order',
							'order'          => 'ASC',
							'post_mime_type' => 'image',
							'fields'         => 'ids',
							'meta_query'     => array(array('key' => '_woocommerce_exclude_image', 'value' => 0)))
						),
				array(get_post_thumbnail_id()));
		$woocommerce_product_image_gallery = implode(',', $woocommerce_product_attachment_ids);
		update_post_meta(get_the_ID(), '_product_image_gallery', $woocommerce_product_image_gallery);
	}
}
