### ISSUE TITLE
Importing Images for Woocommerce Products via WPAllimport Error

### ISSUE THREAD

**Issue by deepankarpathak** [woothemes/woocommerce#8286]
When we are trying to import content in CSV format as Woocommerce Products using WPAllimport for woocommerce - it is generating the duplicate image - which is unfortunately increasing the size of my disk usage.

Screenshot of WPAllimport Image Mapping - http://snag.gy/BFmj2.jpg

Any suggestions, how to manage it so that WP All import will not create multiple images.

**Comment by claudiosmweb** [comment]
Seems to be a WP All import issue and not a WooCommerce issue.
