### ISSUE TITLE
mistyped variable

### ISSUE THREAD

**Issue by vonsch76** [woothemes/woocommerce#8288]
A minor issue, but seems that product variation and child product is mixed with stock.

#6039 termék variáció készlete csökkentve: 6302 volt, majd 28 lett.

so 
product variation #6039 stock was reduced from 6302 to 28.

6302 is the main product, the real stock was 30.

**Comment by claudiosmweb** [comment]
It does not seem to have any problem: https://github.com/woothemes/woocommerce/blob/release/2.3/includes/class-wc-ajax.php#L1260-L1266

**Comment by vonsch76** [comment]
Claudio,

Yes the code looks ok, still the output is not the intended.

Here is an example. (Admin is in Hungarian.) Bottom-up, the first 2 message
is from a gateway, 6303 is the variation id. (The first message states the
number of available coupons.) The top message is the one I sent. 6039 is
the main product id, 6303 variation id, reduced stock 29.

[image: Inline images 1]

[image: Inline images 2]

Can provide you access to a staging environment which does exactly the
same, just drop me a mail.

Kornel

**Comment by mikejolley** [comment]
This is an issue with the localisation. You can change that/contribute to this here: https://www.transifex.com/projects/p/woocommerce/

**Comment by vonsch76** [comment]
Mike, thanks will check and try to modify in the translation. Kornel
