### ISSUE TITLE
When editing a order, the correct values are not shown on the emails

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#8289]
When we change a product value on the order edit screen that value is not shown correctly on the emails the client receives.

![image](https://cloud.githubusercontent.com/assets/6853605/7983481/9f941f94-0ab8-11e5-87c7-4e98625ee329.png)

On woocommerce/templates/emails/email-order-items.php we should test if the line_subtotal != from line_total and show the previous value with <del>del</del> and then show the new value with get_item_total (exactly as it's done on woocommerce/includes/admin/meta-boxes/views/html-order-item.php ).

I've fixed this for myself copying the template into my theme, but I really think this should be the default behaviour. At least the correct/new value should be shown instead of the old one.

**Comment by mikejolley** [comment]
I think you're misusing those 2 fields.

The subtotal/total is for discounts on the line. Your subtotal (before discount) is lower than the total. I think this is a mistake.

The template uses ->get_formatted_line_subtotal(). The subtotal in your case is 5.97

**Comment by webdados** [comment]
Yes, in this example I've changed the value to a higher value and not a lower one. My bad. It was just a test

The problem still exists.

Here's the real life example that made us aware of this problem:

![image](https://cloud.githubusercontent.com/assets/6853605/8005608/ef566a20-0b83-11e5-9577-ebdc527fed37.png)


If the product is ultimately being sold at 8,85 and not it's original 9,96 value, than that's the value the email should reflect.

Or else it doesn't make sense because:

8,32+1,08 (9,40)
+
8,01+1,09 (9,50)
+
8,85 + 1,15 (10)
= 
28,90  (+0,01 of rounding problems?!)

The email is just showing up the original product price (wrongly without tax) and then showing a 0,04 discount when in fact the discount is 1,11€ as you can see in the order screen.

Ultimately, IMHO, the email must reflect the same values as the order screen.

**Comment by mikejolley** [comment]
@webdados The emails reflect the frontend cart/checkout/order screens. Subtotal is shown in the table (before discount) and then the actual discount is shown in the totals section below. This is how it looks in-store.
