### ISSUE TITLE
Rounding problem with percent-off coupon

### ISSUE THREAD

**Issue by PeterGrand** [woothemes/woocommerce#8291]
I'm running into a case where the order total is not matching the sum of the items in the order when a percent-off coupon is applied.

Here is the cart:
Item A $13.49
Item B $14.49
Subtotal $27.98

Coupon: -$6.75 (50% off Item A)
Shipping: Free
Sales Tax: $1.59
Total: $22.83

If I add up the total manually, it comes out to $22.82.

Perhaps it is rounding the coupon value to $6.74 someplace?

But, if I take Item B out of the cart, the math all works out and listed total is accurate.
Here is the cart without Item B:
Item A $13.49
Subtotal $13.49

Coupon: -$6.75 (50% off Item A)
Shipping: Free
Sales Tax: $0.51
Total: $7.25

This is WooCommerce v2.3.10. Occurs with or without the Smart Coupons addon enabled.

Another example has shown up:
Item C x5 $14.49
Subtotal: $72.45
Coupon: -$7.25 (10% off entire order)
Shipping: free
Total: $65.21

Total should be $65.20.

Paired with the Mijireh payment module, this bug means users are unable to complete their orders, getting frustrated, and sending us complaints.

**Comment by mikejolley** [comment]
Rounding of these coupons will be improved in 2.4. This is from 2.4:

https://dl.dropboxusercontent.com/s/dglbkfbhu31ej66/2015-06-05%20at%2012.12%202x.png?dl=0

**Comment by melbwebdesign** [comment]
@mikejolley Hi Mike, did this rounding issue get resolved?  I'm still seeing it in WC 2.4.12, the line total in the attached screenshot 
![gtx50_coupon_rounding_issue](https://cloud.githubusercontent.com/assets/6956381/13802293/7f2b7344-eb8e-11e5-9496-e5d7ca4fbb99.jpg)
should be $24.51 not $24.50
