### ISSUE TITLE
wc_print_notice is stripping question marks from strings

### ISSUE THREAD

**Issue by reidbiztech** [woothemes/woocommerce#8292]
wc_print_notice (or one of the functions it calls) is stripping question marks from strings.

e.g.: 
```php
$info_message = apply_filters( 'woocommerce_checkout_coupon_message', __( 'Have a coupon?', 'woocommerce' ) . ' <a href="#" class="showcoupon">' . __( 'Click here to enter your code', 'woocommerce' ) . '</a>' );
wc_print_notice( $info_message, 'notice' );
```

results in:
>Have a voucher or coupon Click here to enter your code

Actually it looks like this function only calls a template which in turn calls wp_kses_post which in turn calls wp_kses which in turn calls five other  wp_kses_* functions (what a mess) so that must be where the bug is... 

Someone want to pass it on to WordPress, I don't have time to type this out again.

**Comment by mikejolley** [comment]
No, your code gives:

https://dl.dropboxusercontent.com/s/542mrxu1pmoceeg/2015-06-05%20at%2010.22%202x.png?dl=0

The message you said it results in does not event match your string. Translation maybe?

There is no bug in WP core - wp_kses is used to sanitise strings with allowed HTML.
