### ISSUE TITLE
Checkout form validation messages next to the form fields

### ISSUE THREAD

**Issue by pawelkmpt** [woothemes/woocommerce#8297]
Validation error messages for checkout form currently appear above the form on the list, what is not the best user experience. Ideally every message should be displayed next to/above/below the invalid field, so user can easily notice what and where is wrong.

I thought that maybe it's possible to easily match error messages printed by built-in WooCommerce validator using JavaScript and display them next to the fields, but unfortunately - error messages are on the list and none of them have any id, class or anything that could help me to do so.

I also wanted to match messages with fields using labels, as it's the only useful attribute passed to the `woocommerce_add_error` filter, but that's also bad idea, because labels in billing and shipping sections are the same, so it's not obvious to which field message applies.

I noticed similar question in #6353 and now I know that you don't support this kind of functionality. Have you thought about making some changes in validation process and giving developers more flexibility in this module?

**Comment by jameskoster** [comment]
Inline validation messages is a good idea. Reckon we can include this in 2.4 @mikejolley ?

**Comment by mikejolley** [comment]
If you do it @jameskoster  :p

**Comment by jameskoster** [comment]
Not sure if I'll have time now. It's not essential though, we can add it in 2.5.

**Comment by sjeden** [comment]
Tried this back in 2102 #2031

**Comment by extended83** [comment]
Yes, it's very good idea to set error messages next or below to textfield. It will be more user-friendly.

**Comment by forlini** [comment]
Can I do anything to help, this is a very important issue for me and probably many alike.

**Comment by jameskoster** [comment]
@forlini you can submit a pull request :-)

**Comment by EdgarSpongolts** [comment]
It has been 2+ years in the making? Any ETA updates?

**Comment by claudiosanches** [comment]
@EdgarSpongolts yes, you can check #10672

**Comment by comebesse** [comment]
@claudiosanches  #10672 doesn't seem to resolve the problem, unless i missed something ... ? :) Any news for inline error messages ?

**Comment by claudiosanches** [comment]
@comebesse inline error messages should be come with our new checkout flow, we are not doing any change that can be changed again after we revise our checkout flow.
