### ISSUE TITLE
Proposal: Not using postmeta or using options for sessions and transients but own db tables

### ISSUE THREAD

**Issue by standardplumbing** [woothemes/woocommerce#8300]
The postmeta data for standardplumbing.com is about 5 million. So any query that doesn't use index fields on the postmeta will be slow.  

It seems like WooCommerce is sorting the products the "round about" way which is a lot slower.

Trying to find a solution for store which have a high level of products, the live site www.standardplumbing.com has 110,116 published products.      

Any suggestions would be greatly appreciated.

Thanks in advance
Luke

**Comment by mikejolley** [comment]
Sessions: https://github.com/woothemes/woocommerce/issues/6846

As for transients, we're not building custom transients - WP handles it. Use memcache if worried about transient performance.

**Comment by standardplumbing** [comment]
What about postmeta?

If all the item data is stored in one table it makes it a lot faster to get data. 

Cheers
Luke
