### ISSUE TITLE
Proposal: Not using postmeta but own db tables for WooCommerce

### ISSUE THREAD

**Issue by standardplumbing** [woothemes/woocommerce#8301]
The postmeta data for standardplumbing.com is about 5 million. So any query that doesn't use index fields on the postmeta will be slow.

It seems like WooCommerce is sorting the products the "round about" way which is a lot slower.

Trying to find a solution for store which have a high level of products, the live site www.standardplumbing.com has 110,116 published products.

Any suggestions would be greatly appreciated.

Thanks in advance
Luke

**Comment by standardplumbing** [comment]
If all the item data is stored in one table it makes it a lot faster to get data.

**Comment by mikejolley** [comment]
Sorry, but postmeta is the "WordPress way". Adding custom tables would be a step backwards for us. Implement static caching - W3 Total Cache plugin - to start.

**Comment by standardplumbing** [comment]
Yep postmeta is a the way that WordPress does it but querying data from one db table against, post and then multiple keys in postmeta takes a lot longer. Already using Varnish and will be using Redis for object caching.

**Comment by standardplumbing** [comment]
Postmeta works fine when working with smaller product ranges on a store, but when you get into having over 100,000 products on a store it does become an issue. Thanks for the response Mike.

**Comment by mikejolley** [comment]
@standardplumbing I get that. But going back to custom tables for post meta would be a step backwards, and we'd pretty much be rewriting what WP already does for us. I can imagine this change would not go down well to say the least :p 

Plus you'd lose the ability to do queries by meta using the WP API, it would break all plugins, and integrations would be more difficult.

**Comment by standardplumbing** [comment]
What about for all products to use there own custom db table and not to use post and postmeta. Search queries would just be run on the custom db table instead of having to do the query through postmeta key for example. I think WooCommerce is awesome, just running into issues on heavy product levels 110,000+ products. Thanks Mike.

**Comment by Luke-Lau** [comment]
@standardplumbing, I too think WooCommerce is awesome. One of my clients has about half of your numbers (5500+ product records, 44000+ product_variation records, and 2.4+ million postmeta records). They ran into performance issue after importing a majority of their products. At the end, they switched hosting provider (now with Amazon), switch out Apache with Nginx, and implemented W3 Total Cache. That appears to be working for them (for the most part).
