### ISSUE TITLE
German language not supportet

### ISSUE THREAD

**Issue by uschroeder77** [woothemes/woocommerce#8307]
Hello,

we are using Loco Translate plugin to translate Woocommerce, Kingdom Theme and Woozone addIn to German language. Because of not every label of Woocommerce functionality is transferd correctly as attributes from the native code to pot, po, mo files there are some frontend bugs:

![issue02](https://cloud.githubusercontent.com/assets/12762795/8012054/88d735f0-0bbe-11e5-8107-3f44b1a399c5.JPG)
![issues01](https://cloud.githubusercontent.com/assets/12762795/8012055/88de9e12-0bbe-11e5-8654-f3896b5d7ed4.JPG)

The "as of" timestamp issue will be fixed by the Woozone Team. The other bugs are rejected as related to Woocommerce Plugin. I'am sure that there are many other labels of the Woocommerce plugin that does not work properly with other languages. 

I will be realy happy for a fast fix. Please check the issues for fixes.

Best regards,
Uwe

### WordPress Environment ###

Home URL: http://wp-test.h2436908.stratoserver.net
Site URL: http://wp-test.h2436908.stratoserver.net
WC Version: 2.3.10
WC Database Version: 2.3.10
Log Directory Writable: /var/www/shops/test/wordpress/wp-content/uploads/wc-logs/
WP Version: 4.2.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 5.5.9-1ubuntu4.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.43
Max Upload Size: 4 MB
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Remote Post: 
Remote Get: 

### Server Locale ###

decimal_point: .
thousands_sep: k.A.
mon_decimal_point: k.A.
mon_thousands_sep: k.A.

### Active Plugins (16) ###

AA Backup Manager: von Andrei D. - www.aa-team.com – 1.0
AJAX Thumbnail Rebuild: von junkcoder – 1.12
Broken Link Checker: von Janis Elsts – 1.10.8
Contact Form 7: von Takayuki Miyoshi – 4.1.2
Google Analytics by Yoast: von Team Yoast – 5.4.2
Kingdom - Shortcodes plugin: von AA-Team – 1.0
Loco Translate: von Tim Whitlock – 1.5.1
Recent Posts Widget Extended: von Satrya – 0.9.9
Revolution Slider: von ThemePunch – 4.6.92
WooCommerce Germanized: von Vendidero – 1.3.2
WooCommerce: von WooThemes – 2.3.10
WooZone - WooCommerce Amazon Affiliates: von AA-Team – 8.1.2
WordPress HTTPS: von Mike Ems – 3.3.6
WordPress Importer: von wordpressdotorg – 0.6.1
WordPress SEO: von Team Yoast – 2.1.1
YITH WooCommerce Ajax Navigation: von Your Inspiration Themes – 1.4.1

### Settings ###

API Enabled: 
Taxes Enabled: 
Shipping Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### WC Pages ###

Shop-Basis: #1044 - /shop/
Warenkorb: #1045 - /warenkorb/
Kasse: #1046 - /kasse/
Mein Konto: #1047 - /mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Kingdom - Woocommerce Amazon Affiliates Theme
Version: 1.5.7
Author URL: http://themeforest.net/user/AA-Team/portfolio?ref=AA-Team
Child Theme: ✕ – Wenn Sie WooCommerce oder ein Parent Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie Sie ein Child Theme erstellen (engl.)

WooCommerce Support: 

### Templates ###

Overrides: kingdom/woocommerce/archive-product.php
kingdom/woocommerce/cart/cart-empty.php
kingdom/woocommerce/cart/cart-item-data.php
kingdom/woocommerce/cart/cart.php
kingdom/woocommerce/cart/cross-sells.php
kingdom/woocommerce/cart/mini-cart.php
kingdom/woocommerce/cart/shipping-calculator.php
kingdom/woocommerce/checkout/cart-errors.php
kingdom/woocommerce/checkout/form-billing.php
kingdom/woocommerce/checkout/form-login.php
kingdom/woocommerce/checkout/form-pay.php
kingdom/woocommerce/content-product.php
kingdom/woocommerce/content-product_cat.php
kingdom/woocommerce/content-single-product.php
kingdom/woocommerce/content-widget-product.php
kingdom/woocommerce/global/form-login.php
kingdom/woocommerce/global/quantity-input.php
kingdom/woocommerce/global/sidebar.php
kingdom/woocommerce/global/wrapper-end.php
kingdom/woocommerce/global/wrapper-start.php
kingdom/woocommerce/loop/add-to-cart.php
kingdom/woocommerce/loop/loop-end.php
kingdom/woocommerce/loop/loop-start.php
kingdom/woocommerce/loop/no-products-found.php
kingdom/woocommerce/loop/orderby.php
kingdom/woocommerce/loop/price.php
kingdom/woocommerce/loop/rating.php
kingdom/woocommerce/loop/result-count.php
kingdom/woocommerce/loop/sale-flash.php
kingdom/woocommerce/myaccount/form-add-payment-method.php
kingdom/woocommerce/myaccount/form-edit-address.php
kingdom/woocommerce/myaccount/form-login.php
kingdom/woocommerce/myaccount/my-account.php
kingdom/woocommerce/myaccount/my-downloads.php
kingdom/woocommerce/notices/error.php
kingdom/woocommerce/notices/notice.php
kingdom/woocommerce/notices/success.php
kingdom/woocommerce/order/form-tracking.php
kingdom/woocommerce/single-product/add-to-cart/external.php
kingdom/woocommerce/single-product/add-to-cart/grouped.php
kingdom/woocommerce/single-product/add-to-cart/simple.php
kingdom/woocommerce/single-product/add-to-cart/variable.php
kingdom/woocommerce/single-product/meta.php
kingdom/woocommerce/single-product/price.php
kingdom/woocommerce/single-product/product-attributes.php
kingdom/woocommerce/single-product/product-image.php
kingdom/woocommerce/single-product/product-thumbnails.php
kingdom/woocommerce/single-product/related.php
kingdom/woocommerce/single-product/review.php
kingdom/woocommerce/single-product/sale-flash.php
kingdom/woocommerce/single-product/share.php
kingdom/woocommerce/single-product/short-description.php
kingdom/woocommerce/single-product/tabs/additional-information.php
kingdom/woocommerce/single-product/tabs/description.php
kingdom/woocommerce/single-product/tabs/tabs.php
kingdom/woocommerce/single-product/title.php
kingdom/woocommerce/single-product/up-sells.php
kingdom/woocommerce/single-product.php
kingdom/woocommerce/taxonomy-product_cat.php
kingdom/woocommerce/taxonomy-product_tag.php

**Comment by claudiosmweb** [comment]
You fix the German translation on Transifex https://www.transifex.com/projects/p/woocommerce/
