### ISSUE TITLE
Issue with Variable Product

### ISSUE THREAD

**Issue by synry63** [woothemes/woocommerce#8312]
I having an issue after create a variable product via the woocommerce API. I just add the example product given at : http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product

So this one : 
curl -X POST https://example.com/wc-api/v2/products \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "product": {
    "title": "Ship Your Idea",
    "type": "variable",
    "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "categories": [
      "Clothing",
      "T-shirts"
    ],
    "images": [
      {
        "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-black-front.jpg",
        "position": 0
      },
      {
        "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-black-back.jpg",
        "position": 1
      },
      {
        "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-green-front.jpg",
        "position": 2
      },
      {
        "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-green-back.jpg",
        "position": 3
      }
    ],
    "attributes": [
      {
        "name": "Color",
        "slug": "color",
        "position": "0",
        "visible": false,
        "variation": true,
        "options": [
          "Black",
          "Green"
        ]
      }
    ],
    "default_attributes": [
      {
        "name": "Color",
        "slug": "color",
        "option": "Black"
      }
    ],
    "variations": [
      {
        "regular_price": "19.99",
        "image": [
          {
            "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-black-front.jpg",
            "position": 0
          }
        ],
        "attributes": [
          {
            "name": "Color",
            "slug": "color",
            "option": "black"
          }
        ]
      },
      {
        "regular_price": "19.99",
        "image": [
          {
            "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-green-front.jpg",
            "position": 0
          }
        ],
        "attributes": [
          {
            "name": "Color",
            "slug": "color",
            "option": "green"
          }
        ]
      }
    ]
  }
}'

The product add well. The problem is that I can't select any variation (here colors) on the page of the product 
![screenshot 2015-06-06 08 32 58](https://cloud.githubusercontent.com/assets/1159213/8019800/bb70c84c-0c26-11e5-94d3-cc6f24b9665e.png)

Updating the product on the admin panel actually fix this issue,  So it make me think that something is missing on the API call, but I have no idea what.

**Comment by claudiosmweb** [comment]
This must be because your attribute has another slug.

**Comment by nganhtuan63** [comment]
For options or option values, you should use "option slug" instead of "option name". It worked well for me with "option slug".
