### ISSUE TITLE
Hide multiple options using select

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#8313]
How to hide multiple `fieldset` and `tr` using select. Currently only next `tr` is hidden by using select `availability` class [here](
https://github.com/woothemes/woocommerce/blob/master/assets/js/admin/woocommerce_admin.js#L183-L190). It would be helpful if select hide options just like how checkbox does [here](https://github.com/woothemes/woocommerce/blob/master/assets/js/admin/woocommerce_admin.js#L192-L211)

**Comment by mikejolley** [comment]
You can enqueue custom JS to handle advanced showing/hiding like this. Doing so with class names will never be as powerful, and 'availability' is a specific use case.
