### ISSUE TITLE
Update variations prices with API

### ISSUE THREAD

**Issue by synry63** [woothemes/woocommerce#8314]
Can someone confirm me that it is possible to replace old value in "regular_price" and "sale_price" of a variations product with a PUT request ?

I am sending a a new data like :
curl -X PUT https://example.com/wc-api/v2/products/546 \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "product": {
      "variations":[{"regular_price":18.40,"sale_price":3.6,"attributes":         [{"name":"Talla","slug":"talla","option":"6 (XXS)"}]}]
     }
}'

After the request the product still have old value on "regular_price" and "sale_price"

**Comment by claudiosmweb** [comment]
Yes you can, but you forgot the variation ID to indicate which variation is being changed.

**Comment by synry63** [comment]
you are right ! thx for the answer
