### ISSUE TITLE
i have some strange error with woocommerce in my multisite

### ISSUE THREAD

**Issue by foxpcteam** [woothemes/woocommerce#8317]
i have some strange error with woocommerce in my multisite.

no matter what i try to do i get every time the same error (only the gateway file change and line code change) when i click on " woocommerce_checkout_place_order button" on cart page.

no matter what payment i select always the same error.
Fatal error: Call to a member function update_status() on a non-object in /home/public_html/wp-content/plugins/woocommerce/includes/gateways/bacs/class-wc-gateway-bacs.php on line 334

in the chrome console i see this error:
http://test.site.co.il/wp-admin/admin-ajax.php?action=woocommerce_checkout Failed to load resource: the server responded with a status of 500 (Internal Server Error)

but, the strange thing is, if i refresh the page and click again on " woocommerce_checkout_place_order button" the order is created and all seems working.

my multisite using Multi-DB plugin https://premium.wpmudev.org/project/multi-db/
and domain maaping plugin: https://premium.wpmudev.org/project/domain-mapping/

what i have tried?
i have disable all plugins.
i have try to use default theme
i removed all plugins from mu-plugins folder
i tried to create new site (in multisite)
i check that all configuration in woocommerce are fine
in wp-config i set: define( 'WP_MAX_MEMORY_LIMIT', '256M' );
in php ini i see 256M
i have deleted woocommerce and installed the plugin again
i speak with the hosting siteground and they said that this is not server problem

i tried to disable checkout script:

function so_27023433_disable_checkout_script(){
    wp_dequeue_script( 'wc-checkout' );
}
add_action( 'wp_enqueue_scripts', 'so_27023433_disable_checkout_script' );

any suggestions what this can be and how to fix this?

Thanks in advance

**Comment by foxpcteam** [comment]
After long debugging i have install new clean multi site with only Multi-db plugin and Woocommerce plugin.

i have set Multi-db without any problems (this is not my first).

then i just create demo product and try to create new order. guess what? the same problem the same error!

then, i removed the db-config.php and db.php files. activated Woocommerce and create new product.

then i try to create new order and guess what? all working without any problem!

any fix to this conflict?

**Comment by mikejolley** [comment]
This means https://github.com/woothemes/woocommerce/blob/master/includes/gateways/bacs/class-wc-gateway-bacs.php#L331 is not returning the order object you're checking out.

wc_get_order() https://github.com/woothemes/woocommerce/blob/79629c5928acb89939392112c3fd0e34f8b4bbfa/includes/wc-order-functions.php#L53

Order factory: https://github.com/woothemes/woocommerce/blob/5ef335b169ff4e19a4c5b393963a369446922b0c/includes/class-wc-order-factory.php#L21

Note that this is simply a `get_post()` which is a WP function which should return the post object. Multi-DB must be preventing this from returning a post object for some reason.

I see you posted via https://premium.wpmudev.org/forums/topic/multi-db-plugin-conlict-with-woocomerce?nlv=d&utm_expid=3606929-35.im_xHH3rTkmdlc6O7wpMUQ.3&utm_referrer=https%3A%2F%2Fwww.google.co.uk%2F as well so please await a response from Multi DB. I don't know enough about their plugin to recommend a fix.
