### ISSUE TITLE
Possible XSS issue with layered nav widgets

### ISSUE THREAD

**Issue by krautnerds** [woothemes/woocommerce#8320]
Hi everybody,

in our last security check there was a big issue with the layered nav widgets uncovered:
https://github.com/woothemes/woocommerce/blob/master/includes/widgets/class-wc-widget-layered-nav.php#L241

This line leads to possible XSS attacks.

Steps to reproduce:
If there is a shop url:
https://SHOPURI/category/subcategory/
the problematic url would be:
https://SHOPURI/category/'-alert(1)-'subcategory/

The problem is that esc_url_raw doesn't remove single quotes..

How can we fix that for the next release?

**Comment by mikejolley** [comment]
@krautnerds Is this speculative, or reproducible? Because https://SHOPURI/category/'-alert(1)-'subcategory/ will always 404

**Comment by krautnerds** [comment]
For me its reproducible as I wrote above. I will set up a demo page if you can't reproduce it.

With the manipulated link I get the normal category page and if I choose an option in the layered nav I get an js alert which alerts "1"

**Comment by claudiosmweb** [comment]
I could reproduce, but the way you described is still wrong!

**Comment by krautnerds** [comment]
Just as a side note: I'm seeing this with the latest release 2.3.10

**Comment by krautnerds** [comment]
@claudiosmweb Oh sorry, what was described wrong?

**Comment by claudiosmweb** [comment]
This:

> https://SHOPURI/category/'-alert(1)-'subcategory/

Impossible to reproduce with this URL.

But it's possible to reproduce the issue in other ways.

**Comment by krautnerds** [comment]
Thank you for the quick fix! @claudiosmweb
