### ISSUE TITLE
Coupons restricted to exclude sale items don't work on variations not on sale.

### ISSUE THREAD

**Issue by slash1andy** [woothemes/woocommerce#8324]
Ticket #297357 

You can see the issue there, but here are the steps to reproduce:

* Add an item to the cart (not on sale)
* Add an item to the cart that is variable, and pick a variation on sale
* Add an item from the variable product above, but pick the variation not on sale (Make this the highest priced item in the cart.)
* Set up a coupon using these settings:

![](http://cld.wthms.co/1fA1S+)
![](http://cld.wthms.co/1gCjL+)

The discount should come off the highest priced item not on sale, which would be the last variation. It will instead compute off the simple product.

**Comment by mikejolley** [comment]
This appears to be reported wrong, or fixed in master.

![2015-06-09 at 10 47 2x](https://cloud.githubusercontent.com/assets/90977/8055082/f48e756e-0e94-11e5-9f94-d98ce3fa494c.png)

Also tested the other way round in case you're wording was backwards.

**Comment by slash1andy** [comment]
@mikejolley the product that should be the most money should be a variation of the same product that has a variation on sale. The restriction on coupons looks at all variations as on sale, if one is.

The product above is a simple product, right? That wouldn't replicate it.

**Comment by mikejolley** [comment]
>  It will instead compute off the simple product.

You mentioned simple products though? @slash1andy

**Comment by slash1andy** [comment]
Yes, but in the initial scenario, there are 3 products. 

One is a simple product ($10 for example)
One is a variation ($12)
One is a variation of the same product above, but on sale ($9)

The coupon should come off the middle variation as the highest priced item, but instead it will come off the simple product, and it's because the variable product has one variation on sale.
