### ISSUE TITLE
SSLv3 and TLSv1 (1.0)  expiry notices to be displayed to the customers

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#8329]
PCI Compliance dictates that SSLv3 and TLSv1 to be discontinued at the latest of June 30, 2016.
Hence can we display a notice on the browsers using the above standards with 

```
/* notify users that we will no longer support these protocols */ 
if ($_SERVER['SSL_PROTOCOL'] == "TLSv1" || $_SERVER['SSL_PROTOCOL'] == "SSLv3") { printf("<font color=\"white\" size=\"5\">"); 
printf("Your browser is using the insecure protocol %s for encryption and is end of life, upgrade now.</font>\n", $_SERVER['SSL_PROTOCOL']); 
printf("<p>\n"); 
}
```

More info [Here](https://www.pcisecuritystandards.org/documents/Migrating_from_SSL_Early_TLS_Information%20Supplement_v1.pdf).

Concerned Ticket [Here](https://woothemes.zendesk.com/agent/tickets/301221)

@BFTrick @ABDpromotions

**Comment by mikejolley** [comment]
@spraveenitpro Customers are not likely to even understand what these things are, let alone how to fix the issue. They are non-technical. It is the responsibility of the store owner + hosting provide to disable these old insecure protocols from use.

http://disablessl3.com
