### ISSUE TITLE
Multiple Layered Nav Dropdowns destroyed by XSS fix

### ISSUE THREAD

**Issue by krautnerds** [woothemes/woocommerce#8332]
@claudiosmweb Referring to #8320

Now we got a problem with multiple layered nav dropdowns on one page... The ampersands from the original query get now escaped and so the already set filter don't work anymore.

Steps to reproduce:
1.) Filter your shop page with the query
``` ?filtering=1&filter_ATTRIBUTE1=VALUE1 ```

2.) Choose a second filter value by selecting another layered nav filter dropdown value

=> Results in the following query args:
``` ?filtering=1&amp;filter_ATTRIBUTE1=VALUE1&filter_ATTRIBUTE2=VALUE2 ```

**Comment by krautnerds** [comment]
Really? That looks like the hack of the hack of the hack :(

**Comment by krautnerds** [comment]
Wouldn't it be possible to introduce "allowed query args" which are registered in WP which are then used to build up a valid query string which can be used to redirect to the right filtered page?

**Comment by claudiosmweb** [comment]
@krautnerds we need to handler with pagination, non nice permalinks and lot of another things.
For me the best thing would be to have no dropdown and so end any problems with JS.
