### ISSUE TITLE
"Manage Stock" is always checked for variations

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#8336]
No matter if I uncheck the "manage stock" checkbox and update the post, on reload the checkbox is still checked. It seems that it is checked whether the variation's meta key for `_manage_stock` is `yes` or `no`. And I think I tracked it down to this in [class-wc-meta-box-product-data.php](https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L805-808):
```
// Stock BW compat
if ( '' !== $variation_data['_stock'] ) {
	$variation_data['_manage_stock'] = 'yes';
}
```

Before this the `$variation_data['_manage_stock']` value reflects the meta's actual value. After, it is always yes.

I didn't track down `$variation_data['_stock'] ` or why it is always non-null. I am using the bleeding edge of the main branch.

**Comment by mikejolley** [comment]
When saved without manage stock, _stock should be reset to ''. Maybe its the formatting we added a few days ago.
