### ISSUE TITLE
remove action wc_send_frame_options_header doesn't seems to work

### ISSUE THREAD

**Issue by Romano83** [woothemes/woocommerce#8340]
Since the last release, `wc_send_frame_options_header` function was added to prevend checkout and account pages from being used in iFrames. This is a good things !
However, I display my webshop with an iFrame in another website (not same domain name) and I can't remove this function using `remove_action( 'template_redirect', 'wc_send_frame_options_header' );`. 
When I `var_dump` this, the hook always return false...

**Comment by mikejolley** [comment]
This code is hooked during:

```
add_action( 'after_setup_theme', array( $this, 'include_template_functions' ), 11 );
```

Ensure you unhook this after it has taken place.
