### ISSUE TITLE
Problem if you add to product gallery PDF file

### ISSUE THREAD

**Issue by darkwindcz** [woothemes/woocommerce#8344]
I tried to attach PDF file to product gallery and there are two main problems with that.

1) there is no thumbnail for it in administration (small, irelevant issue)
2) you can not "un-attach" it. If you try it, it dissapear from admin, but frontend returns in attachments array (bigger problem...)

Any help with that? Sure I can delete it directly from database, but... it is not very nice solution.

**Comment by claudiosmweb** [comment]
Gallery is designed to accept only images.

**Comment by claudiosmweb** [comment]
I just try to add a PDF and nothing happened, did not work out.

**Comment by darkwindcz** [comment]
If you try to add PDF, it will accept it (is inserted to database, sometimes it appear in admin without thumbnail, sometimes not). So this is potential problem.

Is there any way how to add some PDF (with instructions) to the product?

**Comment by claudiosmweb** [comment]
As I said, add a PDF does not work, see: http://cl.ly/1U1c1g1U2X0p

> Is there any way how to add some PDF (with instructions) to the product?
Yes, use custom fields.
