### ISSUE TITLE
Out of stock report page only shows the first page

### ISSUE THREAD

**Issue by tdawebdesign** [woothemes/woocommerce#8354]
Hi Guys,

We have discovered a bug with the Out of stock reporting it only shows 1 page or first 20 products so when you have more that this it doesn't have the option to view page 2,3 ect they are just missing

See screenshots from /wp-admin/admin.php?page=wc-reports&tab=stock&report=out_of_stock

It has 69 but only shows the first 20 and you can't see the other products out of stock

![image](https://cloud.githubusercontent.com/assets/12841306/8101438/83e53df8-105a-11e5-8c26-3498efc1926c.png)

**Comment by justinshreve** [comment]
Hi @tdawebdesign - I can't seem to reproduce.

On that page, with more than 20 products I see pagination options at the bottom:

![pagination on out of stock report](https://cldup.com/kAmBxkR5Bf-3000x3000.png)

If you don't see the pagination options, could you let me know which version of WooCommerce you are using?

**Comment by tdawebdesign** [comment]
Hi Justin,

Thanks for the response.  We were running an older version of woocomerce.  We have upgraded our woocommerce to the latest version which has resolved the problem.

Thanks again for your response.

Tim
