### ISSUE TITLE
Prevent redirects to about page

### ISSUE THREAD

**Issue by foxpcteam** [woothemes/woocommerce#8359]
Hi,
​can you add the same as yoast did with "about page" (prevent redirects to about page).
​look here:
​http://kb.yoast.com/article/246-prevent-redirects-to-about-page-and-intro-tours
​
this can really help to many users
​​
​Thanks

**Comment by mikejolley** [comment]
Already adjusted in 2.4, but not totally removed. Removed for minor updates.
