### ISSUE TITLE
Cart Item data customized with woocommerce_add_cart_item_data does not get returned from WC_Cart::get_item_data

### ISSUE THREAD

**Issue by ammist** [woothemes/woocommerce#8361]
I'm trying to customize the item information that is displayed on the cart, checkout, order emails, etc.

I am able to add my specially-formatted fields to the cart item using a filter on `woocommerce_add_cart_item_data`, but these values are not displayed where they are supposed to, because the function get_item_data does not return them.  Instead, `get_item_data` returns the unformatted values from looking up attribute names.

It looks like I could use the filter 'woocommerce_get_item_data' to add my custom data, but this filter does NOT allow me to throw out the item_data I don't want to use, so my attributes get displayed twice - once properly formatted, and once incorrectly formatted.

**Comment by mikejolley** [comment]
What are you trying to change? Terms names to something custom?

**Comment by mikejolley** [comment]
Closing due to lack of feedback.

**Comment by ammist** [comment]
Hi @mikejolley.  Apologies, I didn't see the original feedback (just the "closing") message.

What I'm trying to do is this:

1) Hide some of the attribute names.  In this example, we have an attribute that measures whether the size is in millimeters or inches.  When users are configuring the product, this is the first choice they make, but after that,  sizes have their units specified.  In the cart, I just want to show  `Diameter: 0.5"`.  Not `Units: Inches; Diameter 0.5"`

2) Add a "Variant name" to the cart item.  Our variants are described by the combination of size, colors, and measurement units.  We can generate a name for this product based on the variant attributes, and it's easiest if I can just put this name in the cart as cart data, rather than having to regenerate it everywhere the item name is supposed to be displayed.  I do know about the product name filter (and am using it), but this also seems to generate a link to the product page, which I don't want on the checkout page or the order review screen.  

OR

3) Re-format the SKU as its displayed to the user.  For the our bookkeeping system, we have skus in the form 004m175ga, but for display, we want to show 4mm1.75ga.  The latter is is a convention used by the customers to refer to our products quickly, and we have invested some time in training them to use this convention, over the last 15 years this store has been in operation.

At the moment I am doing some crazy globals gymnastics to change the cart_item_data, but it would be much easier if there were a simple way for me to get the data out that I put in.
