### ISSUE TITLE
File type validation for downloadable product URLs checking allowed media mimetypes

### ISSUE THREAD

**Issue by Einkoro** [woothemes/woocommerce#8362]
Related to #8316 – in 2.3.10 it looks like URLs are checked against ``get_allowed_mime_types`` rather than just uploads to the media library. Shouldn't direct URLs be excluded from this check? All our downloads are on a separate subdomain and they are almost entirely exe or dmg which we don't want to allow being uploaded into the media library so filtering the allowed mimetypes is not practical.

**Comment by mikejolley** [comment]
If it didn't check all mime types, you (or another user) could enter a URL to a non-allowed file on your server and have access to it.

**Comment by MarcinKoni** [comment]
I'd like to re-open this issue. I sell digital items through my store, and now I cannot link users to the executable files after selling them my program.
1) only an admin could change the URL and the file would have been uploaded and available already so the protection seems entirely moot
2) adding these files to the allowed mimetypes is a far greater risk if you use plugins that allow users to upload images and other attachments in bbpress, galleries or anywhere else. Not a remotely viable work around.
3) this breaks existing websites without warning forcing them to stay on old versions and ignore security updates, I've seen other users discuss this, and people are just rolling back to older versions of woocommerce, which is a bad idea.

**Comment by Einkoro** [comment]
It also looks like this breaks using protocol relative URLs for downloads. Prior to 2.3.10 we were able to specify our downloads using ``//domain.tld/path/to/file.ext`` but now it will result in the following notice being printed:
> The downloadable file //domain.tld/path/to/file.ext cannot be used as it does not exist on the server.

**Comment by mikejolley** [comment]
@MarcinKoniSuggest a solution over than removing the validation then... without validation, a user (lets say store manager) could add a downloadable wp-config.php file and download it. Thats why the mime check needs to stick around.

**Comment by Einkoro** [comment]
@mikejolley The web server should not serve up php files as a download unless its misconfigured. 

I would also argue: 
1) wp-config.php should not be in a web accessible directory in the first place to protect against an error like this or ideally you should be using something like dotenv to pass sensitive details into wp-config.php; 
2) admins and shop managers should know better.

**Comment by sluther** [comment]
>If it didn't check all mime types, you (or another user) could enter a URL to a non-allowed file on your server and have access to it.

Wat?

If only admins and shop managers can set the URL, why does this matter? If someone sets the wrong URL, that's their problem. If you absolutely must do this, why not have a separate restriction for uploads & links? It sounds like you're trying to protect your users from being stupid, and instead you're hindering them. Besides, your point relating to wp-config is moot because if that were the case, PHP wouldn't be getting executed at all, would it?

**Comment by mikejolley** [comment]
@Einkoro @sluther In a traditional setup yes. But there are other use cases which could be vulnerable. A site which has vendors for example.

**Comment by mikejolley** [comment]
Would a filter around allowed types help?

**Comment by Einkoro** [comment]
A filter would work. Basically duplicating upload_mimes but specific to digital downloads in WooCommerce to avoid allowing the mimetypes elsewhere in WordPress. 

Would it be possible to allow protocol relative URLs again? 

----
Jan Pingel
jan.pingel@me.com
+1 (778) 678 2248

**Comment by kainjow** [comment]
I think there is a bug with this filter. When wp_check_filetype() is called to get the filetype, wp_check_filetype uses the default list of mimes so if you provide a custom mime type for downloading, it doesn't get used for the file type, so then it gets rejected again. I believe a fix would be to call wp_check_filetype and pass in $allowed_file_types as the second parameter.

Also similarly to @Einkoro we use relative URLs, and these are now broken. Fortunately I was able to override woocommerce_downloadable_file_exists and just return true but that is hacky.
