### ISSUE TITLE
Huge delays after clicking "Checkout"

### ISSUE THREAD

**Issue by theschtickler** [woothemes/woocommerce#8364]
Hey guys, I'm currently experiencing enormous delays after clicking checkout. We have 3 payment methods:
Paypal - 7 secs to redirect to paypal
CreditCard on page (paypal payflowpro) - 27 secs to process
Wholesale preorder (no gateway) - 27 secs to process

Any ideas whats going on? The install is on a very powerful server, this is the only thing that goes slow.

Thanks.

**Comment by claudiosmweb** [comment]
Well this depends.
When you press this button, the WooCommerce will create a new order, the payment method will connect to an external API, either PayPal or whatever and wait for the API response, 
sometimes still occur at the same time order status change, where the stock goes down also. Not to mention the emails can be fired for the customer and for you.

So you have two things that can take a long time to load...
The first to payment gateway API response and the second is to send emails, especially depending on how you set it on your server.
