### ISSUE TITLE
Critical: Taxes don't get calculated on clean install

### ISSUE THREAD

**Issue by RVandenbussche** [woothemes/woocommerce#8367]
Just made a clean install of wordpress and woocommerce and it seems that the taxes do not get calculated. For example on checkout it says: Total £321.00 (Includes £0.00 VAT) with a standard of 21% tax enabled. I reproduced it on every install and different domains.

**Comment by mikejolley** [comment]
This has the be a setup issue or we'd have more reports (and my own site would be broken :).

Screenshot your taxes.

**Comment by RVandenbussche** [comment]
Well I could reproduce it on several domains. Reinstalled wordpress and woocommerce and I have the same settings as my sites that show taxes.

**Comment by mikejolley** [comment]
Check your database - ensure you have the tax and tax_location tables.

**Comment by RVandenbussche** [comment]
I don't have the woocommerce_tax_rate_locations table but added it and didn't change anything.

**Comment by mikejolley** [comment]
Once its added, go save your tax rates again..

**Comment by RVandenbussche** [comment]
Works! Thanks big time! Very weird that on all the different domains the tax_rate_locations table wasn't there. I've reinstalled everything 6 times now and never worked out of the box. Importing the woocommerce_tax_rate_locations table from an domain that it was working for and then saving the taxes again made it work.

**Comment by mikejolley** [comment]
@ChromeOrange was this to do with table name length last time it occurred?

**Comment by ChromeOrange** [comment]
@mikejolley no. I haven't reviewed any logs but the ones I have seen are using wp_ and I can give them a snippet to create the table which always works. Probably timing out. The table check in 2.4 will help with this

**Comment by justinshreve** [comment]
Getting this error on install:

`WordPress database error Specified key was too long; max key length is 1000 bytes for query `

I'll fix it :)

**Comment by RVandenbussche** [comment]
Great job guys!

**Comment by Kberghe** [comment]
Hello! I am having the same problem as @RVandenbussche for my recently installed woocommerce site. After checking my database I figured out it is missing the woocommerce_tax_rate_locations table for some reason.

I am quite new to wp and woocommerce so my question is: where can I find this table and how do I add it to my db?

All help is welcome, I have been struggling with this issue for a few days now.

Thank you.
