### ISSUE TITLE
New user registration at checkout, overrides global disable registration

### ISSUE THREAD

**Issue by frozonfreak** [woothemes/woocommerce#8369]
I have a multisite set up with registration disabled for all sites. 

Woocommerce still allows for users to register at checkout page. Is this part of woocommerce design ?

**Comment by claudiosmweb** [comment]
They are two different registration and is designed to work separately with the WordPress options.
Frankly it is best to not allow users to be registered in WordPress, so all users entries by WooCommerce always have the "customer" rule and not "subscriber".

But you can disable the customer registration in WooCommerce settings too.
