### ISSUE TITLE
HTML 5 Input types

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#8370]
At all the forms (login, registration, my account > addresses, my account > account details, checkout, etc...) HTML input types (email, number, tel, etc...) should be used.

http://www.w3schools.com/html/html_form_input_types.asp

If it's not "safe" to use number and tel types, at least the email one should be used.

**Comment by roykho** [comment]
Thanks, this is already done in master branch

**Comment by claudiosmweb** [comment]
And you can chance this by following this: http://docs.woothemes.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/#section-2

**Comment by webdados** [comment]
@claudiosmweb I know that. It just doesn't make sense. Also, to set a different "type" attribute you have to change this -> "type – type of field (text, textarea, password, select)" into something that woocommerce does not recognize, so you have to create special custom types functions.... It's just too much hassle to something that should be part of the core.

**Comment by claudiosmweb** [comment]
@webdados and yes, this part of core now. You can wait for us or do now using this filters.
