### ISSUE TITLE
Broken Attribute functionality in API/docs

### ISSUE THREAD

**Issue by DominoTree** [woothemes/woocommerce#8374]
Now that attributes seem to be handled in post meta rather than taxonomies/terms, a number of functions in the API have stopped working such as WC_Product_Variable->get_variation_attributes() and WC_Product->get_attribute() and so forth.

I spent some time trying to figure out why these functions were broken until I finally looked at the source for one of the functions that worked properly, and saw that there was a fundamental change made at some point.  The functions are still listed in http://docs.woothemes.com/wc-apidocs/class-WC_Product.html without any notice that they don't work.

The remaining functions should either be deprecated or refactored.

**Comment by mikejolley** [comment]
This report is too vague. There is no mention of the functions from http://docs.woothemes.com/wc-apidocs/class-WC_Product.html which you think do not work. 

get_variation_attributes and get_attribute both work and are used throughout the core codebase.
