### ISSUE TITLE
API Showing Discounted Item Price on Line Items

### ISSUE THREAD

**Issue by sparkweb** [woothemes/woocommerce#8376]
I believe that version `2.3.7` or `2.3.8` changed how the line item price is displayed in the API. Previously, all my prices were the full item price. Now the price field is showing the price minus the item discount. The result is that I'm seeing double discounts because I'm setting a discount for the whole order + using the line item price field as the per product price.

Line Item 1 Example:
```
[id] => 29508
[subtotal] => 13.50
[subtotal_tax] => 0.00
[total] => 11.47
[total_tax] => 0.00
[price] => 11.47
[quantity] => 1
```

and line item 2 example:
```
[id] => 29509
[subtotal] => 15.00
[subtotal_tax] => 0.00
[total] => 12.75
[total_tax] => 0.00
[price] => 12.75
[quantity] => 1
```

Couple lines
```
[coupon_lines] => Array
    (
        [0] => Array
            (
                [id] => 29511
                [code] => 100days
                [amount] => 4.28
            )

    )
```

**Comment by mikejolley** [comment]
Core has always applied coupons to line items, never to the order as a whole, so this (if it changed) would have been a bug fix and will not be reverted.

subtotal + subtotal_tax is before discount
total + total_tax is after discount

Discounts are applied to lines so taxes are discounted fairly with coupons being split between lines.
