### ISSUE TITLE
Woocommerce Product Shortcodes

### ISSUE THREAD

**Issue by dmayembe** [woothemes/woocommerce#8378]
Hi. I created a page My Suits Page on my site (link below), to display product categories using woocommerce short-codes. You can see my items are not aligned properly, it is all a big mess, i changed the pictures sizes and tried anything I could but with not change. And the pagination is missing. Here is the code I used on the page. I really need help with this. 
Thank you.
Dee
[product_category category="suits" per_page="12" columns="3" orderby="price" order="desc"]

http://www.maleegomenswear.com/my-suits-page

**Comment by roykho** [comment]
Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

**Comment by michaeltieso** [comment]
I'm afraid the issue here is with your theme. Try using a different theme that supports WooCommerce.

**Comment by dmayembe** [comment]
I am using TopShop which support woocommerce. 
Thank you

**Comment by michaeltieso** [comment]
@dmayembe Try contacting the developers of TopShop as that's not a theme of ours.
