### ISSUE TITLE
Structured Data concerning offers are marked up as product

### ISSUE THREAD

**Issue by FairJoe** [woothemes/woocommerce#8379]
In wp-content/plugins/woocommerce-german-market/inc/WGM_Template.php Line 535 price, currency and availabilty are marked up as itemtype="http://schema.org/Product" but "Product" has no price, currency and availability. These properties belong to itemtype="http://schema.org/Offer".
I'm referring to WooCommerce/Templates version 1.6.4

**Comment by claudiosmweb** [comment]
Please open an issue on WooCommerce German Market repository.
Here is for WooCommerce issues only.
Thank you.
