### ISSUE TITLE
Bug in string translation 

### ISSUE THREAD

**Issue by ProjectKarol** [woothemes/woocommerce#8382]
I am not developer, but I thing I found bug in translation strings:
The path to file is:
wp-content/plugins\woocommerce\includes\admin\meta-boxes\class-wc-meta-box-product-images.php

In line:  58
``
<a href="#" data-choose="<?php _e( 'Add Images to Product Gallery', 'woocommerce' ); ?>" data-update="<?php _e( 'Add to gallery', 'woocommerce' ); ?>" data-delete="<?php _e( 'Delete image', 'woocommerce' ); ?>" data-text="<?php _e( 'Delete', 'woocommerce' ); ?>"><?php _e( 'Add product gallery images', 'woocommerce' ); ?></a>
``
I changed from 'woocommerce' to 'woocommerce-admin'  :+1: 
``
<a href="#" data-choose="<?php _e( 'Add Images to Product Gallery', 'woocommerce-admin' ); ?>" data-update="<?php _e( 'Add to gallery', 'woocommerce-admin' ); ?>" data-delete="<?php _e( 'Delete image', 'woocommerce-admin' ); ?>" data-text="<?php _e( 'Delete', 'woocommerce-admin' ); ?>"><?php _e( 'Add product gallery images', 'woocommerce-admin' ); ?></a>
``

I found that translatable string eg "Add to gallery" was in woocommerce-admin.pot not in woocommerce.pot

**Comment by claudiosmweb** [comment]
We have just the `woocommerce` textdomain.
And divided the translations in two files. Just to load some information just in the right place.
https://github.com/woothemes/woocommerce/blob/master/woocommerce.php#L316-L326
