### ISSUE TITLE
woocommerce conflict with new "submit_button"

### ISSUE THREAD

**Issue by foxpcteam** [woothemes/woocommerce#8384]
Hi,
i have replace the submitdiv meta box (publish box) with just one simple save button.
all working fine with post/page and custom post type (plugins that i have install that create  custom post type)

The problem is when i try to create new product. all the data saved and i see the product i have created in the wp-admin.

the product status is "publish"

Also, i can see the product itself if i click "viewed product" or access direct to product by url.

But the problem is if i go to "shop" url where i need to see all the products i have created. i don't see any product.

But, if i restore the submitdiv meta box (publish box) and click on the original "publish" button the product appear right away in the frontend (store).

What makes woocommerce to make this conflict or something wrong with my code?

Here is my code:

```php
submit_button( $text = NULL, $type = 'primary', $name = 'newsubmit', $wrap = true, $other_attributes = NULL );

add_filter( 'wp_insert_post_data', 'cs_force_published' );
function cs_force_published( $post ) {

        if (isset($_POST['newsubmit'])){
		  if (get_post_type($_REQUEST['post_id']) != 'shop_order') {
		   $post['post_status'] = 'publish';
		   }
        }
        return $post;

}

function disableAutoSave(){
     wp_deregister_script('autosave');
}
add_action( 'wp_print_scripts', 'disableAutoSave' );
```

**Comment by claudiosmweb** [comment]
You are doing it and probably going over of some WooCommerce nonce.
https://github.com/woothemes/woocommerce/blob/ecac3fba413afeaa7dc7c6ddd7d49cf4fc7e7b45/includes/admin/class-wc-admin-meta-boxes.php#L166-L210
