### ISSUE TITLE
Reports -> Customer -> Customer List: Name (Last, First) not appearing

### ISSUE THREAD

**Issue by designerken** [woothemes/woocommerce#8387]
When viewing the customer list all the details are available except the 'Name (Last, First)' column that has a "-" in its place.

**Comment by claudiosmweb** [comment]
This will be filled when the customer make the registry at Checkout or can be changed in My Account page:

![screenshot from 2015-06-16 11 08 23](https://cloud.githubusercontent.com/assets/1264099/8185017/117b7a7c-1418-11e5-9783-e4fcf7b4de96.png)

![screenshot from 2015-06-16 11 08 41](https://cloud.githubusercontent.com/assets/1264099/8185022/1494ceca-1418-11e5-9965-ffe34949b33f.png)

**Comment by designerken** [comment]
Sorry for that, So I did see if they just "register" they can create an account without a first/last name.

But if they place an order does it then use the billing name in the report? or must they go to edit account details?
