### ISSUE TITLE
WooCommerce Slow  Queries

### ISSUE THREAD

**Issue by standardplumbing** [woothemes/woocommerce#8389]
Hope this might help

http://codeshare.io/jwLhr

These are some of the slow query issues we are seeing turning slow query logging on the MySQL server for a live site.

Thanks in advance
Luke

**Comment by mikejolley** [comment]
This is another I see in multiple channels. It is not a bug report. 

[Please review our guidelines before submitting any further tickets](https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md)

Some of these queries are generic WP queries, some are from Relevenssi, and some are from WC. If you identify a particular WC query that could be improved report that alone, just be aware we're bound by the structure of the WP tables. e.g. postmeta needs multiple joins when comparing different meta keys at the same time.

**Comment by standardplumbing** [comment]
Okay will bot post anything which is support related in future. Will do with any WC query that could be improved.
