### ISSUE TITLE
Add Product to Order

### ISSUE THREAD

**Issue by standardplumbing** [woothemes/woocommerce#8392]
![add-product-to-order-not-working](https://cloud.githubusercontent.com/assets/12717086/8194625/f66d7b8c-1439-11e5-98c4-689fea390d27.jpg)

When trying to search for a product by SKU the SKU is also in the product title, it comes up with a Loading Failed error message.

The products are on the site and setup correctly.

Any help would be appreciated.

**Comment by mikejolley** [comment]
Please don't post support questions here. Also posting to multiple channels is not good as it can waste time. I see on facebook you've simply got a memory limit issue which can be resolved with an edit to your wp-config file.
