### ISSUE TITLE
Remove tax-exclusive on certain products

### ISSUE THREAD

**Issue by anderskristo** [woothemes/woocommerce#8393]
Hi,

How do i remove tex-exclusive on certain products?

ex. If a value is true then remove tax-exclusive on that product.

**Comment by roykho** [comment]
Hi @anderskristo 

Unfortunately this is not a support channel.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com
