### ISSUE TITLE
Downloadable Files: File URL breaks download links upon updating product

### ISSUE THREAD

**Issue by Soundae** [woothemes/woocommerce#8402]
Hi,

Just updated to WC v2.3.11 and found File URLs will no longer work if any update is done to a Product. Spaces and special characters will be stripped off hence returning 404 to the customer.

Original Path: http://mysite.com/this is my download [EXE].zip
Updated Path by WC: http://mysite.com/thisismydownloadEXE.zip -> 404

I tried entering URL-safe encoded addresses but they also return 404; the only temporary solution I found was to manually edit wp_postmeta in MySQL with a re-serialized, correct URL (PHP Re-serializer: https://www.functions-online.com/serialize.html)

s:47:"http://mysite.com/this is my download [EXE].zip";

Regards,

Soundae

**Comment by mikejolley** [comment]
esc_url_raw will not allow spaces. They are invalid.

Use %20 instead. These will not be stripped on save.

**Comment by Soundae** [comment]
I tried URL-safe encoded addresses as well but forgot to put an example on my original post. If paths are entered as follows, WC returns 404.

http://mysite.com/this%20is%20my%20download%20%5BEXE%5D.zip

**Comment by mikejolley** [comment]
What about accessing that URL via browser?

**Comment by Soundae** [comment]
Sorry if I said WC returns 404, the product is updated successfully and the WC UI displays no error.

If the file was entered via WC UI using safe encoding and a customer wants to download it via a completed order, the browser returns 404. 

On the other hand, if the file was modified directly in MySQL, same order which just failed, the download proceeds successfully.

So even if the URL goes through as entered via UI using safe encoding, the download will fail. On previous versions, spaces and special characters were not removed therefore paths would remain as-is on the database. All files are inside woocommerce_uploads folder so they are not accessible for the public.

**Comment by mikejolley** [comment]
Spaces are not valid, so allowing them is not an option. Ill do a test with a file with spaces locally and see if it occurs for me.

**Comment by Soundae** [comment]
OK will try with spaces only in a sec (no '[ ]' ). Perhaps the problem is at download; I'm not familiar with WC's code and haven't traced the function calls to debug. 

I'm using this tool to quickly encode URLs: http://www.blooberry.com/indexdot/html/topics/urlencoding.htm

**Comment by claudiosmweb** [comment]
WordPress by default when you make an upload will convert the spaces to `-`.
I just tested that encoded one and works fine.

https://cloudup.com/cNtk41L4k6p

But not recommend using spaces and `[]` in a URL.
It should only be `a` to `z`, dots and dashes.
