### ISSUE TITLE
Invalid Key or Secret - Invalid signature - provided signature does not match woocommerce APP

### ISSUE THREAD

**Issue by soulpawa** [woothemes/woocommerce#8405]
I have the woocommer app, and when I want to log in with  my API credentials, and always show the same error,I tried everything, without success.

any idea?
![img_5433](https://cloud.githubusercontent.com/assets/6342029/8232871/19906e40-15d3-11e5-99cb-7143852eed28.PNG)

**Comment by maxrice** [comment]
Can you [submit a ticket](https://woothemes.com/my-account/create-a-ticket/) for this? thanks :)

**Comment by soulpawa** [comment]
done, thanks
