### ISSUE TITLE
Name, surname and company name not displaying on invoice

### ISSUE THREAD

**Issue by Roy1980** [woothemes/woocommerce#8411]
I use the listify theme with woocommerce + woocommerce PDF Invoices plugin. 

On the order screen woocommerce displays name, surname, company name and full adres. However, the invoices only display the full adres. Name, surname and company name is gone.

In the woocommerce iOS app the same order shows name, surname and full adres. Just not the company name......

Weird.

**Comment by mikejolley** [comment]
The data is stored, but its down to the plugin to pull the data and display. Check with the author of PDF invoices directly.

**Comment by ChromeOrange** [comment]
It's the theme in this case

**Comment by Roy1980** [comment]
What does that exactly mean? That is isn`t possible to get this to work?

**Comment by ChromeOrange** [comment]
I've just updated your ticket. You will need to contact Astoundify about this.
