### ISSUE TITLE
HTTPS Loop after installing Woocommerce

### ISSUE THREAD

**Issue by saimana** [woothemes/woocommerce#8414]
Second day I am experiencing this issue ot a server without SSL certificate. 
After activating the plugin WP redirect me to wp-login.php under HTTPS, and all links in front-end everithing is forced to HTTPS. 
What to do? 
Thank you.

**Comment by mikejolley** [comment]
You may have this on https://codex.wordpress.org/Editing_wp-config.php#Require_SSL_for_Admin_and_Logins, or you may have a plugin for SSL, or you may have this checked https://dl.dropboxusercontent.com/s/5k0fjie2cdnot0w/2015-06-19%20at%2016.33.png?dl=0

**Comment by saimana** [comment]
No, It's clean install without plugins installed and I can't even load the settings page of Woocommerce.

**Comment by mikejolley** [comment]
Definitely check your config. WC does not force HTTPS in admin. Only checkout pages (if enabled, its off by default).

**Comment by standardplumbing** [comment]
Probably check the WC settings for forcing HTTPS.
http://docs.woothemes.com/document/ssl-and-https/

**Comment by standardplumbing** [comment]
Probably if WC is not loading, if it is whitescreen then there is a plugin conflict or a memory issue. You could just rename the plugin folder on the server and then load the plugins in the dashboard. Make a not of the plugins you have active. Then rename the plugins folder back and refresh the plugin page. Then just activate have WC being the only active plugin and if it load checking WooCommerce>Settings>Checkout (Force secure checkout) to see if it checked out not.

**Comment by mikejolley** [comment]
#8434
