### ISSUE TITLE
PayPal is not automatically redirecting to "thank you" page

### ISSUE THREAD

**Issue by bhouszka** [woothemes/woocommerce#8416]
After successfull payment with PayPal on other sites I am always taken to thank you page. I have been playing with Woocommerce PayPal Standard and I have not been redirected.

**Comment by mikejolley** [comment]
PayPal handles the redirect back to your site. The thanks page must exist however, ensure you have the endpoints setup and working correctly in Settings > Checkout

For an auto redirect you also need to enable this http://docs.woothemes.com/document/paypal-standard/#section-7
