### ISSUE TITLE
Paging does not work for getting list of customers from REST API 

### ISSUE THREAD

**Issue by jeffkirby** [woothemes/woocommerce#8418]
In the [WooCommerce REST API v2](http://woothemes.github.io/woocommerce-rest-api-docs/), the "Get a List of Customers" service does not support paging correctly. (The paging in "Get a List of Products" does appear to work well, for example).

**To Reproduce**
1. Create more than 10 customers
2. Execute `GET https://host/wc-api/v2/customers`

**Expected Results**
Works like the "get all products" API where you get 10 customers in first page with: 
1. a response header `Link` marked with `rel="next"` and containing the URL to the next page
2. a response header `Link` marked with `rel="last"` and containing the URL to the last page of results
3.  a response header `X-WC-TotalPages:` with the number of pages

**Actual Results**
10 customers in first page with
1.  _no_ response header `Link` marked `rel="next"` and containing the URL to the next page. 
2.  a response header `Link` marked `rel="last"` and containing a URL to the **first** page (the one that I just called!) 
3. a response header `X-WC-TotalPages:` with a **blank** value

**More Detail**
For an example of how it should work, if you execute "Get a List of Products" you get correct output like the following.  There is a response header `Link: <https://shop.example.com/wc-api/v2/products?page=2>; rel="next"` that tells me where to get the next page of products. There is a response header `Link: <https://shop.example.com/wc-api/v2/products?page=5>; rel="last"` that tells me where to get the last page of products. And there is a response header `X-WC-TotalPages: 5` that tell me how many pages there are

```
Request DefaultHttpRequest(chunked: false)
GET /wc-api/v2/products HTTP/1.1
Authorization: Basic XXXXXX
Connection: keep-alive
Host: shop.example.com
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: true)
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 19 Jun 2015 17:51:07 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Link: <https://shop.example.com/wc-api/v2/products?page=2>; rel="next"
Link: <https://shop.example.com/wc-api/v2/products?page=5>; rel="last"
X-WC-Total: 50
X-WC-TotalPages: 5
```

If you call "Get a List of Customers", then you get the following. There is only the `Link` response header `Link: <https://shop.example.com/wc-api/v2/customers>; rel="last"` which incorrectly gives the first page that I just called. There is no  `Link` response header with `rel="next"` like `Link: <https://shop.example.com/wc-api/v2/customers?page=XXX>; rel="next"`. And the response header `X-WC-TotalPages:` is blank.

```

Request DefaultHttpRequest(chunked: false)
GET /wc-api/v2/customers HTTP/1.1
Authorization: Basic XXXXXX
Connection: keep-alive
Host: shop.example.com
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: false)
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 19 Jun 2015 17:51:06 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 6356
Connection: keep-alive
Link: <https://shop.example.com/wc-api/v2/customers>; rel="last"
X-WC-Total: 116
X-WC-TotalPages: 
```

**Comment by justinshreve** [comment]
I went to start debugging this and it was brought to my attention that it was already fixed in master. Relevant commit: https://github.com/woothemes/woocommerce/commit/994e4104e92cf454232bf96f5b3c032fafaa1d39

I did a quick check and confirmed the headers look correct now.

**Comment by jeffkirby** [comment]
cool

**Comment by jeffkirby** [comment]
Another thing that I noticed about the "Get a List of Customers" API is it only returns users with `role=Customer`. Is it possible to use it to get all the users, including `role=Seller` or `role=Subscriber`?  

For example, in one of my test instances I have 500 users with role=seller and I like to purge them using the API. But I can't find a way to retrieve them using the API.

Looking at the documentation it says 

> AVAILABLE FILTERS
> Filter	Type	Description
> role	string	Customers by status. eg: customer or subscriber

Should I file another bug?
Or is this already fixed?
Or am I misinterpreting the documentation?
