### ISSUE TITLE
Orders REST API uses a deprecated function

### ISSUE THREAD

**Issue by justinshreve** [woothemes/woocommerce#8419]
Something in the Orders API is calling something with legacy arguments:

    PHP Notice:  get_formatted_legacy is <strong>deprecated</strong> since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in wp-includes/functions.php on line 3391

**Comment by claudiosmweb** [comment]
@mikejolley we'll need your help here.
This kind of notices break the API json response.

**Comment by justinshreve** [comment]
I started looking into it a couple days ago but wasn't quite sure why it was happening (it looked like the function was being called correctly) so some insight is definitely welcome :).

**Comment by mikejolley** [comment]
Stems back to this: https://github.com/woothemes/woocommerce/commit/77941a57c511ed09823c94573f38ec0d0f403231

We used to pass just item_meta values into that class which made it difficult to work with. This was changed, and some legacy handling code left in place for backwards compatibility.

It's easy to fix in the API. Committing now.

**Comment by fabianhenzler** [comment]
we're also having this issue in class-c-order-item-meta.php
```
public function get_formatted( $hideprefix = '_' ) {
		if ( $this->legacy ) {
			return $this->get_formatted_legacy( $hideprefix );
		}
```

**Comment by mikebronner** [comment]
This issue is still persisting. Is there a work-around? I have the same issue as @fabianhenzler

**Comment by modernmediagrp** [comment]
Same issue here

**Comment by mikejolley** [comment]
If you see this message its likely coming from a plugin with old handling and needs patching there, not in core. Core doesn't use legacy any longer - if it does, raise an issue with line numbers. Otherwise patch your plugins.

Locking topic as "me too" adds no value.
