### ISSUE TITLE
Tsousand separator can`t be an unicode character

### ISSUE THREAD

**Issue by Ohar** [woothemes/woocommerce#8423]
I can\`t set thousand separator as `&thinsp;`, `&nbsp;` or `/u00a0` for example.

**Comment by mikejolley** [comment]
Tested master. The entity is decoded, but is saved and working: https://dl.dropboxusercontent.com/s/92h7wvi7nji15k0/2015-06-22%20at%2011.13.png?dl=0

**Comment by Ohar** [comment]
I have very different situation.
- `/u00a0` 
![`/u00a0`](http://puu.sh/iDApZ/c40c778ae6.png)
- `&thinsp;` 
![`&thinsp;`](http://puu.sh/iDAhS/4e5a32b5ba.png)
- `&thinsp;` as unicode symbol
![`&thinsp;` as unicode symbol](http://puu.sh/iDAdL/edb9a72ba5.png)

Woocommerce 2.3.11
