### ISSUE TITLE
Add to cart button disabled after clicking back in the browser

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#8424]
This issue is browser specific.  It works in Chrome but not in Firefox or Safari.

Steps to reproduce this issue:

1. Open up Firefox ( latest ) or Safari ( latest ) and navigate to the single product page.

2. Click on add to cart button.  Everything works and you see a successful message.

3. Click back on your browser and try to add the product again and you will see the add to cart button has been disabled like this http://cld.wthms.co/1kK91/RplcctRt

In Chrome it works fine as seen here http://cld.wthms.co/IWus/ZlWIYyKI

Original reported issue: https://wordpress.org/support/topic/very-serius-bug-cannot-press-add-to-cart-button-when-you-go-back?replies=8

**Comment by panbill** [comment]
After some research i found out that this bug has to do with with the following js file.
/plugins/woocommerce/assets/js/frontend/single-product.min.js
And to be more precise i think it has to do with the .attr("disabled","disabled") at the end of the file.
Anyway. I am not sure so just take it as a simple opinion that may help.
Btw (If you remove that file it works but i am not sure if it is a good idea to do that)
