### ISSUE TITLE
Postage per item not working

### ISSUE THREAD

**Issue by RetroWill** [woothemes/woocommerce#8425]
I have a loads of products added but for some reason I cannot combine the postage per item. For each item there is a shipping fee of €4 but the total postage is always €4 even though there are multiple items in the cart.

In woocommerce I have 'Flat Rate' selected as the shipping method. Within 'Flat Rate' settings I have the option 'Per Item, charge shipping for each item individually' selected but it still doesn't calculate per item for some reason.

Any advice appreciated.

**Comment by mikejolley** [comment]
Set this one: https://dl.dropboxusercontent.com/s/qzj78f4m205c3ba/2015-06-22%20at%2010.58.png?dl=0

This interface is being cleaned up in 2.4
