### ISSUE TITLE
Product Admin Grid Thumbnails served over http when FORCE_SSL_ADMIN true

### ISSUE THREAD

**Issue by bdgeorge** [woothemes/woocommerce#8426]
If the site only uses **https** for the admin area (and checkout page) via the "FORCE_SSL_ADMIN" constant, product thumbnails in the Products Admin grid are still served over http resulting in Mixed Content errors.

**Comment by mikejolley** [comment]
Sounds like you have SSL by proxy? If WordPress' is_ssl() function returns false on your page, it cannot detect HTTPS.

**Comment by bdgeorge** [comment]
Hmm, no and sort of - on my test server it's a self-signed cert and is_ssl() returns true but it still errors. 
On production I have it via cloudflare but in strict mode so it really is SSL at the prod server still - both give the same result.

In the screenshot below I've dumped is_ssl() and died immediately after the thumbnail should appear, you should be able to see the mixed-content error there as well.

![image](https://cloud.githubusercontent.com/assets/562621/8273937/6bb1648c-18c5-11e5-8163-1e9b75de919a.png)

**Comment by mikejolley** [comment]
WP core issue, seems to be patched but not live yet. https://core.trac.wordpress.org/ticket/15928
