### ISSUE TITLE
Woocommerce Booking Plugin not Workin

### ISSUE THREAD

**Issue by neeraj10786** [woothemes/woocommerce#8429]
Hi,

when i am some one clicking on add to cart button following error showing in error box. even product not going for order or payment

PHP Warning:  Invalid argument supplied for foreach() in /home/../public_html/wp-content/plugins/brs-booking-reservation-system-woocommerce/templates/single-product/add-to-cart/uou_booking.php on line 21

**Comment by mikejolley** [comment]
This is the issue tracker for WooCommerce core - we do not author or support "brs-booking-reservation-system-woocommerce".
