### ISSUE TITLE
Send Payment Link for Unpaid Orders (Pending Payment)

### ISSUE THREAD

**Issue by rtddev** [woothemes/woocommerce#8430]
Allow an admin to create an order for a customer on the back end, but then send them a payment link to complete payment for the order.

Essentially the payment link would take the shopper to the Checkout page, with the order information all filled out (cart items, prices, discounts, shipping options, bill to, ship to, default payment method type, etc.).  The only thing the customer would need to do is complete payment via their preferred payment method.

Example (shown on unpaid orders)
![payment-page-link](https://cloud.githubusercontent.com/assets/1872898/8283138/40eaff08-18aa-11e5-8d29-e9fd9e23b53c.jpg)

Additional Details:

Variants of this idea could be:
1. Don't show the Payment Page link (in Admin) until an order has met a minimum data criteria (bill to, ship to, order items, shipping method, payment method).
2. Allow the payment link to be shown/used with only line items added to the order (+ line item discounts/notes, if any), allowing the customer to complete the rest of the order information

Our use cases:
1. Customer is exchanging item, but upgrades to higher priced item where they need to pay the difference. We create new order, apply credit from original order to new order, and send payment link to customer to pay difference.
2. We offer customer special offer/discount that is not managed by the coupon management system. We apply discount to order, send customer link to pay.
3. We promote items that are not listed in our catalog, and allow the customer to email in a request for those items. In the back end, we've defined a generic product (i.e. "Special Line Item" or "Stash Drawer Item") that we use, along with line item notes, to handle these request.

**Comment by mikejolley** [comment]
We already allow this. Create an order and choose 'customer invoice' in the email dropdown. Customer will get an email + payment link.

**Comment by rtddev** [comment]
@mikejolley Wow, very cool. Thx.

**Comment by pratikpai21** [comment]
Is this possible for Guest Order Checkout? @mikejolley
