### ISSUE TITLE
Deleting old transient could timeout the server

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8431]
We use this code to delete old transient from past versions

```php
$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->options} WHERE option_name LIKE %s;", "\_transient\_%" . $version ) );
```

This code could kill the database if there are a lot of products in the website.
The example is with 23k products on the site.

Any way to improve it?

Ticket Ref #300581

**Comment by BuggeringHell** [comment]
A similar issue: https://github.com/Yoast/wordpress-seo/issues/2047

**Comment by mikejolley** [comment]
@SiR-DanieL It's this or leaving transients in the DB which is just as bad I would expect.. maybe they should look into using object caching?

This query looks to be as simple as possible. cc @davidlenehan @claudiosmweb @justinshreve So not sure if we can do more.

@BuggeringHell We already have a wp_using_ext_object_cache() check in place. Product transients themselves are not optional.

**Comment by davidlenehan** [comment]
Can't think of a faster way to delete this data, if it is causing timeouts we could try deleting it in chunks but I am not sure how you would restart the process after the first chunk is deleted. It wont speed things up but it will stop timeouts.

**Comment by mikejolley** [comment]
@davidlenehan How would we handle the remnants after that? Cron?

**Comment by BuggeringHell** [comment]
This isue still persists for me. 

> # Time: 150817 15:25:01
> # User@Host: root[root] @ localhost []
> # Query_time: 812.742799  Lock_time: 35.457407 Rows_sent: 0  Rows_examined: 15202631
> SET timestamp=1439825101;
> DELETE FROM wp_options WHERE option_name LIKE '\\_transient\\_%1439823277' ORDER BY option_id LIMIT 1000;
