### ISSUE TITLE
Add arg to wc_create_refund to automatically process refund through payment gateway

### ISSUE THREAD

**Issue by adnanoner** [woothemes/woocommerce#8432]
Would be interesting if there was an extra argument added to wc_create_refund so that we can process the refund automatically through the payment gateway (if this is supported). Also great for the REST-api

**Comment by kloon** [comment]
See http://develop.woothemes.com/woocommerce/2014/08/wc-2-2-payment-gateways-adding-refund-support-and-transaction-ids/ on how to do refund via payment gateways.

**Comment by adnanoner** [comment]
Hi Kloon. Not sure if you understood me. I know that it is possible to automatically refund through a payment gateway. However I'm talking about the [function wc_create_refund](https://github.com/woothemes/woocommerce/blob/8dbd30e76be5af23eeb6e8208f661aa532fb4a66/includes/wc-order-functions.php#L602 ) to create a refund programatically.

It would be great if the functionality of wc_create_refund could be extended to have the option to automatically process the refund through it's payment gateway or to do it manually (in the case that you would send a gift card).

**Comment by kloon** [comment]
There is the woocommerce_refund_created hook which you can work into your payment gateway, you will probably just need to look up if the order was paid via your gateway, which might be problematic as the action does not pass on the order id, so it is possible, but then it will fire with every refund even if it was made with another gateway as there is no way to see what the order id is that is attached to the refund.

An easy contribution you can do is to submit a PR to change the action here https://github.com/woothemes/woocommerce/blob/master/includes/wc-order-functions.php#L729 to `do_action( 'woocommerce_refund_created', $refund_id, $args );` :smile:
