### ISSUE TITLE
Can't apply multiple taxes to local pickup

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8435]
I can't find a way to do this.

I have local pickup enabled. My store location is Colorado (CO).

I have 3 tax rules with 3 different priorities, one for CO, one for some zip codes, and one for the city.
When i use local pickup as shipping method, i want all these 3 taxes to be applied.

Screen: http://cld.wthms.co/i4W79/4RmPALgc

It seems to be not possible since it only applies the tax for the state since there's no way for me to specify the base address, but only the state.

**Comment by mikejolley** [comment]
There are no settings for these at present, but there are 2 filters.

woocommerce_countries_base_postcode
woocommerce_countries_base_city

Can you do a docs report @SiR-DanieL?

**Comment by SiR-DanieL** [comment]
Fixed in https://github.com/woothemes/woocommerce/commit/00d574a

Submitted doc report for http://docs.woothemes.com/document/local-pickup/
