### ISSUE TITLE
Bug when sorting on popularity

### ISSUE THREAD

**Issue by Peter4576** [woothemes/woocommerce#8436]
I spent a week trying to find a bug causing all my searches to return 0. It turned out I had selected "Sort by most popular". And probably because there was no sales history there was nothing to sort upon. However, there MUST always be a fallback in such case! the results should always be the same, and this selection should only affect the order in which the products are displayed.

Further more you dont describe whether it is TOTAL sales or "on number of orders this products has been found". There is a huuuge difference!

thanks

**Comment by mikejolley** [comment]
This falls back to post date.

total_sales is the meta key which gets sorted, and this MUST EXIST for the WP query to return results. The save function in WooCommerce will add this meta whenever a product is saved.

If total_sales is missing, whatever you used to import products into your store must not have added this key. When importing, set total_sales to 0.

total_sales is total sales, not total orders. i.e. If 5 are purchased, total_sales is 5.

**Comment by Peter4576** [comment]
AAaaah ok, cool. I will pass this onto the WP ALL IMPORT guys. Thanks
