### ISSUE TITLE
VAT on each line in basket + productlisting

### ISSUE THREAD

**Issue by Peter4576** [woothemes/woocommerce#8437]
Hi. I have written every best selling WooCommerce Theme Author on Themeforest. And they all report back that THIS IS NOT a default function. However, I have not been able to find any plug-ins for it!

By law the VAT-amount should be listed on the product, even when the product is listed without VAT. You should always be able to see how much VAT that will be put on top of the price.

Therefore I urge you to make a VAT option to display the % VAT underneath (small letters) the price throughout the shop.

**Comment by mikejolley** [comment]
In tax settings there is an option to append a suffix to prices for this purpose. WC > Settings > Tax

**Comment by Peter4576** [comment]
Hi there. Sorry but you missed my point.

I do have a suffix already saying "ex TAX" on each product. But I need the actual number to be displayed. If a product costs 100 kr. I need to display that the tax which will be added is 25% on top. AKA it should say 125 inkl. moms. below in small letters. This is how law says it must be displayed in Denmark and rest of EU I believe, to be honest.

Thanks!

Peter

**Comment by mikejolley** [comment]
If you look at the tooltip via the suffix option, it lets you add stuff like this e.g the tax inclusive price
