### ISSUE TITLE
Country Dropdown issue on checkout page

### ISSUE THREAD

**Issue by darthsaini** [woothemes/woocommerce#8438]
![drop down issue](https://cloud.githubusercontent.com/assets/13016107/8304632/6051595c-19c5-11e5-8f6a-2961e2509c80.PNG)
Dropdown is not working. Not showing any value to choose . ALL countries is enabled in settings.
Browser: Chrome, IE11

**Comment by mikejolley** [comment]
Your theme looks like its cutting it off with overflow:hidden. Try another theme to confirm the issue and if its a WC theme, contact the author for support.
