### ISSUE TITLE
'Default' product permalink base is useless when pretty permalinks are on

### ISSUE THREAD

**Issue by slimndap** [woothemes/woocommerce#8442]
The 'default' option for the product permalink base is not doing anything when you're not using 'default' permalinks for Wordpress. Which is probably the case for 99% of the users.

Also, the example shown next to the option is wrong:
`http://www.example.com/?product=sample-product`

Instead WooCommerce automatically defaults to the 'product' slug:
`http://www.example.com/product/sample-product/`

To reproduce:

1. Go to Settings / Permalinks.
1. Select 'Post name' under 'Common Settings'.
1. Select 'Default' under 'Product permalink base'.
1. Save changes.

The link for your products will look like this:
`http://www.example.com/product/sample-product/`

I'm using WooCommerce 2.3.11.

**Comment by mikejolley** [comment]
This may actually be forced by WP so we should probably clarify that the 'default' option is to either match WP's querystring based permalinks, or to just use '/product/sample-product/'.

I don't think there is a use case for using `?product=sample-product` when WP is not using default?

**Comment by slimndap** [comment]
I agree. Maybe you can even hide some options based on WP using default or not.

**Comment by mikejolley** [comment]
Plan: Hide product permalink settings when 'default' is chosen for WordPress permalinks, and combine default and product options if not.
