### ISSUE TITLE
wc_get_product_id_by_sku

### ISSUE THREAD

**Issue by nuvoPoint** [woothemes/woocommerce#8445]
Hey there,

The function wc_get_product_id_by_sku in /includes/wc-product-functions.php needs to take in to concern that there can be trashed products with the SKU that's getting retrieved from the database.

Please add "AND posts.post_status = 'publish'" to the SQL query:

SELECT posts.ID
		FROM $wpdb->posts AS posts
		LEFT JOIN $wpdb->postmeta AS postmeta ON ( posts.ID = postmeta.post_id )
		WHERE posts.post_type IN ( 'product', 'product_variation' )
		AND postmeta.meta_key = '_sku' AND postmeta.meta_value = '%s'
		AND posts.post_status = 'publish'
		LIMIT 1

Also please make sure to either update the REST API docs or make sure that the SKU filter on products actually works: http://woothemes.github.io/woocommerce-rest-api-docs/#view-list-of-products

Best regards
Aydin BK

**Comment by claudiosmweb** [comment]
If trashed... the product still exists.
Apart from that if you remove it from the trash, then your will have duplicate SKUs.

**Comment by nuvoPoint** [comment]
If you have a trashed product and a active product with the same SKU then there is a chance that you get the ID of the trashed one, because the SQL has a LIMIT 1.

As a work around I tried to use the GET /wc-api/v2/products?sku=123 to get all the products with the same SKU, but that filter does not work even do it is specified in the docs. See: http://woothemes.github.io/woocommerce-rest-api-docs/#view-list-of-products

**Comment by claudiosmweb** [comment]
@nuvoPoint Of course don't works, because you did not read the documentation!

http://woothemes.github.io/woocommerce-rest-api-docs/#parameters

Need to use as:

```bash
GET /wc-api/v2/products?filter[sku]=123
```

**Comment by nuvoPoint** [comment]
Try the GET /wc-api/v2/products?filter[sku]=123 yourself and see if it works?!? 

When I do that it returns ALL products and not only the ones with SKU=123

**Comment by claudiosmweb** [comment]
@nuvoPoint yes, works fine for me.

**Comment by nuvoPoint** [comment]
Well that's not the case here and I'm running WooCommerce Version 2.3.11 wich is the only active plugin and StoreFront as the theme?

The type and category filters work fine, but the sku filter gives me a list of all products regardless of sku.

**Comment by rrNuvoPoint** [comment]
@claudiosmweb i have the same issue. When i ask on a SKU via the API i want the product with the status that is NOT trashed. This is not possible yet.

**Comment by rrNuvoPoint** [comment]
the sku filter dose not seem to work. Created one myself.

**Comment by claudiosmweb** [comment]
@nuvoPoint This has no influence on the theme.
