### ISSUE TITLE
Grouped Products only allow you to add even number of products

### ISSUE THREAD

**Issue by DragonflyRacingDrones** [woothemes/woocommerce#8446]
I've added a Group Product and when you click the + symbol to add items when checking out it only allows you to add even numbers...

### WordPress Environment ###

Home URL: http://www.dragonflyracingdrones.com
Site URL: http://www.dragonflyracingdrones.com
WC Version: 2.3.11
WC Database Version: 2.3.11
Log Directory Writable: /home1/easincus/public_html/dragonflyracingdrones/wp-content/uploads/wc-logs/
WP Version: 4.2.2
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.40
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
Max Upload Size: 50 MB
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Remote Post: 
Remote Get: 

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (16) ###

LayerSlider WP: by Kreatura Media – 5.4.0
Akismet: by Automattic – 3.1.2
Breadcrumb NavXT: by John Havlik – 5.2.2
Google Analytics: by Kevin Sylvestre – 1.0.6
Hello Dolly: by Matt Mullenweg – 1.6
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.5.2
MOJO Marketplace: by Mike Hansen – 0.6.1
Revolution Slider: by ThemePunch – 4.6.93
Screets Live Chat: by Screets Team – 1.5
Weight Based Shipping for Woocommerce: by dangoodman – 2.6.8
WooCommerce Composite Products: by WooThemes – 3.1.2
WooCommerce Stacked Add-to-Cart Product Forms: by franticpsyx
SomewhereWarm – 1.1.1

WooCommerce Quantity Increment: by WooThemes
Bryce Adams – 1.0.0

WooCommerce: by WooThemes – 2.3.11
WooThemes Helper: by WooThemes – 1.5.7
WordPress Importer: by wordpressdotorg – 0.6.1

### Settings ###

API Enabled: 
Taxes Enabled: 
Shipping Enabled: 
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Shop Base: #2033 - /shop/
Cart: #2034 - /cart/
Checkout: #2035 - /checkout/
My Account: #2036 - /my-account/

### Taxonomies ###

Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Creativo 5.0
Version: 5.5.2
Author URL: http://rockythemes.com
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: 

### Templates ###

Overrides: creativo/woocommerce/archive-product.php
creativo/woocommerce/cart/cart-empty.php
creativo/woocommerce/cart/cart-item-data.php
creativo/woocommerce/cart/cart-shipping.php
creativo/woocommerce/cart/cart-totals.php
creativo/woocommerce/cart/cart.php
creativo/woocommerce/cart/cross-sells.php
creativo/woocommerce/cart/mini-cart.php
creativo/woocommerce/cart/shipping-calculator.php
creativo/woocommerce/checkout/cart-errors.php
creativo/woocommerce/checkout/form-billing.php
creativo/woocommerce/checkout/form-checkout.php
creativo/woocommerce/checkout/form-coupon.php
creativo/woocommerce/checkout/form-login.php
creativo/woocommerce/checkout/form-pay.php
creativo/woocommerce/checkout/form-shipping.php
creativo/woocommerce/checkout/payment-method.php
creativo/woocommerce/checkout/payment.php
creativo/woocommerce/checkout/review-order.php
creativo/woocommerce/checkout/thankyou.php
creativo/woocommerce/content-product.php
creativo/woocommerce/content-product_cat.php
creativo/woocommerce/content-single-product.php
creativo/woocommerce/content-widget-product.php
creativo/woocommerce/global/breadcrumb.php
creativo/woocommerce/global/form-login.php
creativo/woocommerce/global/quantity-input.php
creativo/woocommerce/global/sidebar.php
creativo/woocommerce/global/wrapper-end.php
creativo/woocommerce/global/wrapper-start.php
creativo/woocommerce/loop/add-to-cart.php
creativo/woocommerce/loop/loop-end.php
creativo/woocommerce/loop/loop-start.php
creativo/woocommerce/loop/no-products-found.php
creativo/woocommerce/loop/orderby.php
creativo/woocommerce/loop/pagination.php
creativo/woocommerce/loop/price.php
creativo/woocommerce/loop/rating.php
creativo/woocommerce/loop/result-count.php
creativo/woocommerce/loop/sale-flash.php
creativo/woocommerce/myaccount/form-add-payment-method.php
creativo/woocommerce/myaccount/form-edit-account.php
creativo/woocommerce/myaccount/form-edit-address.php
creativo/woocommerce/myaccount/form-login.php
creativo/woocommerce/myaccount/form-lost-password.php
creativo/woocommerce/myaccount/my-account.php
creativo/woocommerce/myaccount/my-address.php
creativo/woocommerce/myaccount/my-downloads.php
creativo/woocommerce/myaccount/my-orders.php
creativo/woocommerce/myaccount/view-order.php
creativo/woocommerce/notices/error.php
creativo/woocommerce/notices/notice.php
creativo/woocommerce/notices/success.php
creativo/woocommerce/order/form-tracking.php
creativo/woocommerce/order/order-details.php
creativo/woocommerce/order/tracking.php
creativo/woocommerce/single-product/add-to-cart/external.php
creativo/woocommerce/single-product/add-to-cart/grouped.php
creativo/woocommerce/single-product/add-to-cart/simple.php
creativo/woocommerce/single-product/add-to-cart/variable.php
creativo/woocommerce/single-product/meta.php
creativo/woocommerce/single-product/price.php
creativo/woocommerce/single-product/product-attributes.php
creativo/woocommerce/single-product/product-image.php
creativo/woocommerce/single-product/product-thumbnails.php
creativo/woocommerce/single-product/rating.php
creativo/woocommerce/single-product/related.php
creativo/woocommerce/single-product/review.php
creativo/woocommerce/single-product/sale-flash.php
creativo/woocommerce/single-product/share.php
creativo/woocommerce/single-product/short-description.php
creativo/woocommerce/single-product/tabs/additional-information.php
creativo/woocommerce/single-product/tabs/description.php
creativo/woocommerce/single-product/tabs/tabs.php
creativo/woocommerce/single-product/title.php
creativo/woocommerce/single-product/up-sells.php
creativo/woocommerce/single-product-reviews.php
creativo/woocommerce/single-product.php
creativo/woocommerce/taxonomy-product_cat.php
creativo/woocommerce/taxonomy-product_tag.php

**Comment by claudiosmweb** [comment]
Works fine https://cloudup.com/cNPmwERa5Yz

**Comment by DragonflyRacingDrones** [comment]
Would you be able to tell me what settings to check on my end then? Because mine doesn’t work fine.  

 

Holly Clark

 <http://www.dragonflyracingdrones.com/> DragonFLY Racing Drones

**Comment by claudiosmweb** [comment]
@DragonflyRacingDrones don't have any setting for it.
You are probably in trouble because of some other plugin or your theme. So you need to test each one.
