### ISSUE TITLE
API - Variations attributes, certain characters is being removed

### ISSUE THREAD

**Issue by PetterRuud** [woothemes/woocommerce#8447]
Lets say i have a product with this options
[1] => Array
                (
                    [name] => Size
                    [slug] => size
                    [visible] => 1
                    [variation] => 1
                    [options] => Array
                        (
                            [0] => 40,5
                            [1] => 40/40
                            [2] => 39,5
                            [3] => 36/34
                        )

                )

The API seems to remove the "," and the "/" before inserting. its using wordpress sanitize_title() function.
Is there a way to get around this, have tried urlencode and htmlentities with no luck.

Thanks in advance

**Comment by mikejolley** [comment]
This is a known issue with text based attributes fixed in 2.4. Use global (term based) attributes to work around this for the time being. cc @claudiosmweb

**Comment by PetterRuud** [comment]
Sorry to ask, but what do you mean by that?

**Comment by mikejolley** [comment]
@PetterRuud There are two types of attributes in WC. The ones you define in Products > Attributes, and then text based product level attributes. The latter cannot contain slashes right now because they are converted to slug format.

@claudiosmweb thats right, yes?

**Comment by claudiosmweb** [comment]
@PetterRuud use the attribute slugs.
