### ISSUE TITLE
Products not displayed correctly

### ISSUE THREAD

**Issue by rssjr** [woothemes/woocommerce#8448]
I create my products using a REST API. The products are created, but not displayed in products page or in your category page (woocommerce category).

I verified, and products are send:

Status: Published
Visibility: Public
Catalog visibility: Catalog/search, Featured

Now, the most strange. If I go to admin (wordpress), I can see the product in "products", if I open a "edit page" of a product and save this (without modify), the product is displayed...

How fix it?

**Comment by claudiosmweb** [comment]
Create a product in admin and another by API then compare the result of them using the API.
This way you will know what they are doing differently.

**Comment by rssjr** [comment]
I did, but don't see difference apparent.

Can help me, saying in which DB table I check these differences?

Thanks
