### ISSUE TITLE
Price of metadata is output without tax if the price entry in the backend is done as net price.

### ISSUE THREAD

**Issue by datenwerkstatt** [woothemes/woocommerce#8452]
Price of metadata is output without tax if the price entry in the backend is done as net price. Google provides search results in the wrong price represents.
Ich fixed it: /single-product/price.php line 21
old: `<meta itemprop="price" content="<?php echo $product->get_price(); ?>" />`
new: `<meta itemprop="price" content="<?php echo $product->get_price_including_tax(1,$product->get_price()); ?>" />`

**Comment by mikejolley** [comment]
This was discussed here https://github.com/woothemes/woocommerce/issues/7895 Including tax will always vary and is not suitable for this file.

You can override the template if you want to change the value for your case.
