### ISSUE TITLE
Update Order Status to Complete via Code doesn't send a Complete Email?

### ISSUE THREAD

**Issue by vicky081** [woothemes/woocommerce#8454]
Hi,

I am trying to change the order status via code, for direct bank transfer i finished set of code is working to change order become complete and for order completed email is not even comes up, when i manually make the order to complete via admin dashboard is working perfectly, seems there is some problem with woocommerce i am using woocommerce 2.3.11, this similar problem previously arised in 2.3 older and i hear about that fix has been taken care with version 2.3 (long time back), is there is a bug or anything i need to do other than that?
```
add_action('woocommerce_thankyou','order_status_bacs_change',10,1);
function order_status_bacs_change($order_id) {
$order = new WC_Order($order_id);
 if($order->payment_method=='bacs') {
  $order->update_status("completed");
 }
}
```

**Comment by claudiosmweb** [comment]
Nop, don't send the completed email.
To be honest a Payment Gateway should just put the order to "processing" using the `$order->payment_complete()` method.
If you want to shoot an email, so feel free to do so.
