### ISSUE TITLE
Variation title not showing admin order page?

### ISSUE THREAD

**Issue by tmyie** [woothemes/woocommerce#8456]
Currently, it shows a thumbnail and product ID on hover, but I need the shop owner to be able to see the variation title. 

On previous installs of WooCommerce, the variation title was shown on the admin order panel. Any reason as to why it's gone?

Thanks in advance for you help!

(Using the latest version of WooCommerce, updated today)

**Comment by claudiosmweb** [comment]
We don't have variation title, just the attributes names.
![screenshot from 2015-06-26 12 36 23](https://cloud.githubusercontent.com/assets/1264099/8381070/0294b3f8-1c00-11e5-9681-4439a8c38315.png)
