### ISSUE TITLE
Product Attributes are not added to product

### ISSUE THREAD

**Issue by fabianhenzler** [woothemes/woocommerce#8464]
```
wp_set_object_terms($product_id, 39, 'product_cat');
wp_set_object_terms($product_id, array('Empirum'), 'pa_platform');
wp_set_object_terms($product_id, array('15.1'. '16.0') , 'pa_empirum-compatibility');
wp_set_object_terms($product_id, $software_vendor, 'pa_software-vendor', yes);
```

[code](https://www.dropbox.com/s/e6h4bnld1uslzfm/Voila_Capture%202015-06-26_10-35-05_vorm.png)
[product_attributes](https://www.dropbox.com/s/wl0z7iwzfmthoe6/Voila_Capture%202015-06-26_10-54-07_vorm.png?dl=0)

this is what I'm doing. But only the `product_cat` and the `pa_platform` are added to the product as you can see [here](https://www.dropbox.com/s/1hqcehlnterpt56/Voila_Capture%202015-06-26_10-35-19_vorm.png?dl=0)

Am I doing something wrong?

**Comment by claudiosmweb** [comment]
Please don't use this for support custom code.
This is just `wp_set_object_terms()` and works like the same.
