### ISSUE TITLE
How to report a security issue?

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#8465]
Hi,

I have a security issue to report in an official WooCommerce extension. I can't find any info on the WooThemes site about how best to report these. I tried a ticket, but the system refused to accept my ticket because of the missing data that wasn't relevant (e.g. provide a copy of your system status report). Please can you advise?

David

**Comment by claudiosmweb** [comment]
Send to me claudio@woothemes.com

**Comment by dave1010** [comment]
Is emailing claudio@woothemes.com still the official way to report security issues? Thanks

**Comment by claudiosmweb** [comment]
@dave1010 not totally "official", but, yes, you can send me and I'll report internally.

**Comment by grazing-llama** [comment]
Is it still acceptable to email you at claudio@woothemes.com with security issues?

**Comment by claudiosanches** [comment]
@grazing-llama Please see README.md

![screenshot from 2017-03-02 15-56-25](https://cloud.githubusercontent.com/assets/1264099/23522198/d91f7440-ff60-11e6-939d-3dbb69ee0ec9.png)

https://hackerone.com/automattic/
