### ISSUE TITLE
Add my own functions to WooCommerce REST API by create a plugin - Is that possible?

### ISSUE THREAD

**Issue by mnbnour** [woothemes/woocommerce#8466]
Hello,
Sorry if this is the wrong place to post my question, but I'm working on an integration between WooCommerce and ERP system.

The problem is that i need a lot of API calls which is not exist like:

1. List of shipping methods
2. List of payment methods
3. List of customer roles.

.....etc (long list :( )

So i'm looking for a way to add more methods/functions to REST API of WooCommerce by creating a plugin is that possible, and if yes how I should start?

Thank you.

**Comment by hansott** [comment]
Take a look at http://docs.woothemes.com/document/wc_api-the-woocommerce-api-callback/

**Comment by claudiosmweb** [comment]
@mnbnour you can create new methods and endpoints.

For example:

```php

add_action( 'woocommerce_api_loaded', 'my_plugin_load_api' );
add_filter( 'woocommerce_api_classes', 'my_plugin_add_api' );

function my_plugin_load_api() {
	include_once 'your-api-endpoint-class.php';
}

function my_plugin_add_api( $apis ) {
	$apis[] = 'YOUR_API_ENDPOINT_CLASS_NAME';
	return $apis;
}
```

Then in your class file:

```php
class YOUR_API_ENDPOINT_CLASS_NAME extends WC_API_Resource {
     // Your methods here
}
```

**Comment by JosephMendez** [comment]
how to add endpoint inside the new class file?

**Comment by amjad** [comment]
How to add date filter?

**Comment by strarsis** [comment]
@claudiosan: `woocommerce_api_loaded` doesn't fire - not when the REST API is invoked.

**Comment by claudiosanches** [comment]
@strarsis this is for our legacy REST API, now you should use the WordPress REST API like we are doing: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/
