### ISSUE TITLE
Action in checkout is running twice in 2.3.x

### ISSUE THREAD

**Issue by pavelevap** [woothemes/woocommerce#8468]
You can test following snippet:

`add_action( 'woocommerce_review_order_after_shipping', 'testing_woocommerce_test' );
function testing_woocommerce_test() {
var_dump("Test");
$available_shipping = WC()->shipping->get_shipping_methods();
var_dump($available_shipping);
}`

When you go to checkout, result of this action is running twice?
I noticed it when using `WC()->shipping->get_shipping_methods()` inside this action and for the first time there was only `NULL`.
I am not sure if I am missing something, but it could be some kind of bug, I guess.
In 2.2.x there was only one call.

**Comment by mikejolley** [comment]
Same as this? https://github.com/woothemes/woocommerce/issues/7787
