### ISSUE TITLE
Changing Product order doesn't reset page count

### ISSUE THREAD

**Issue by krautnerds** [woothemes/woocommerce#8470]
Hi everybody,

I just recognized, that changing the product oder by the order-by widget dropdown doesn't reset the page count - In my opinion thats not the desired functionality - it should reset the page count and redirect to the first page. But I'm open to a small discussion about this usability issue ;)

**Comment by jameskoster** [comment]
There are arguments for both behaviours. 

I think adding a filter to do this might be the way forward. I don't want to change default core behaviour for something as subjective as this.
