### ISSUE TITLE
Shop page crashes when have thousands of products.

### ISSUE THREAD

**Issue by davteks** [woothemes/woocommerce#8476]
I have 75k products in the database and when I load the shop page I'm getting this error: 
WordPress database error MySQL server has gone away for query INSERT INTO `9NaJxW14_options`

http://alldadelawnmowers.com/shop

**Comment by mikejolley** [comment]
Please review all logs to identify problem queries. From the issue you've given it's impossible to say what could be causing it - options is a WordPress database table used by all plugins and WordPress core.

https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

**Comment by davteks** [comment]
I moved same database (170MB) to a mysql dedicated server and now it works fine. It should be something related to web server limitation for mysql
