### ISSUE TITLE
Improve Performance of large numbers of variations on the frontend

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8477]
When showing a number of variations over the (set) max threshold, load variations via ajax after selecting all attributes.

- [x] Set filterable threshold for max number of variations to load on the frontend. 50? 25?
- [x] If threshold is met, do not load all variation products at once - instead show the attribute dropdowns and do an ajax request once all attributes have been chosen and display the result.

This issue was split from #6995 to separate it from the backend improvements.

**Comment by mikejolley** [comment]
p.s. ironically this was how v1.0 worked 3 years ago before optimising with JS :p

**Comment by mikejolley** [comment]
Forgot about @justinshreve going away :) I'll take care of this one.

**Comment by justinshreve** [comment]
Thanks :). I started investigating a bit and moved some stuff around on the PHP side (to prepare the template for handling the case of not having `$available_variations`). But I didn't get to the AJAX or JS stuff. It's at https://github.com/woothemes/woocommerce/compare/master...justinshreve:variations-8477 if there is anything useful for you.

**Comment by mikejolley** [comment]
@justinshreve thanks I'll take a look :)

**Comment by lucasstark** [comment]
@mikejolley Am I correct in understanding that when ajax is being used for the variations form, attribute combinations which are not available are still selectable by the user?    Rather than disabling the options we are just telling them that the attribute combination is not valid after the ajax check?

**Comment by kevin25** [comment]
I still see that the variants of woocommerce 3.x are till slow.

**Comment by mmjjb** [comment]
The original report of slow variations was made in 2014 and in the latest version it is still extremely slow...

**Comment by claudiosanches** [comment]
This has been already improved, before our last changes used to be more slow. And there is always space for be improved, so please feel free to share ideas or submit Pull Requests.
