### ISSUE TITLE
Spanish language "Up-Sells & Cross-Sells" bug

### ISSUE THREAD

**Issue by creativo** [woothemes/woocommerce#8478]
There is an important bug on the admin spanish translation that prevents Up-Sells and Cross-Sells Select2 titles to generate properly.

Transifex don't let me to apply for contribute with the project, so I want to post it here:

`%s &ndash; %s ---> %s y %s%s`

Is not just the string is poorly translated _(in spanish is exactly same as source)_. The bug produces an error in `sprint_f()` in `get_formatted_name()` function from `WC-Product` class, preventing to use the feature.

**Comment by mikejolley** [comment]
Seems ok http://glui.me/?i=deoe8n6l8qgznns/2015-06-29_at_12.36.png/

Anyone can join a team on transifex - no approval needed. Maybe give it another go?
