### ISSUE TITLE
Performance: validate_user_usage_limit()

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8482]
This was bought up in conversation with @pmgarman.

Issue is every time a coupon is used, a meta value is stored in _used_by. Coupons used hundreds of thousands of times cause issue on load.

We should look into a better way of storing this data.

**Comment by pmgarman** [comment]
I posted in my [dev blog](https://so.much.pizza/woocommerce-and-coupon-_used_by-logging/) a bit of background on how this can cripple a site in an edge case.

**Comment by memtoko** [comment]
IMO use different table for that.

**Comment by pmgarman** [comment]
That's my opinion as well

**Comment by mikejolley** [comment]
@georgestephanis

**Comment by georgestephanis** [comment]
Having this stored as meta on the coupon also makes it difficult to track down what coupons a given user has used.  Let me look into the schema and see what I can come up with.

**Comment by georgestephanis** [comment]
Okay, first swing at this completed:

When calling `validate_user_usage_limit()` -- we really don't need all the data for all usages, so I simplified the check in e6b7d5c49ab8279b773c87b161810f7a17741442

I also optimized some calls we're using in `populate()` with 6ef4cf0d182062e7e33b9653dd3370e1d93c84e4

Pull request generated as #8940

**Comment by pmgarman** [comment]
:raised_hands:
