### ISSUE TITLE
Register all styles and scripts before enqueuing them

### ISSUE THREAD

**Issue by bizzthemes** [woothemes/woocommerce#8488]
Some styles and scripts are directly enqueued, instead of being registered first, look inside `\includes\class-wc-frontend-scripts.php` where some are registered and some are directly enqueued. Same goes for `\includes\admin\class-wc-admin-assets.php`.

All should be registered first as they're easier to work with. If developer wants to use one script or style, they should simply enqueue it and not call the full path to them again.

**Comment by mikejolley** [comment]
Which ones inparticular are you looking to use?

**Comment by bizzthemes** [comment]
Select2 in particular, but I see no reason why you shouldn't registers all styles and scripts before enqueuing them. For instance, if developer want to use Select2 styles from WooCommerce they need to enqueue the full path to stylesheet in WC directory instead of simply enqueuing the stylesheet name.

**Comment by claudiosmweb** [comment]
We need move the external libraries too.
Need to move `jquery.flot*.js`, `accounting.js` and `round.js` from `assets/js/admin` to new directories.
