### ISSUE TITLE
Any plans to release the latest version of class-wc-api-orders.php ?

### ISSUE THREAD

**Issue by guillegette** [woothemes/woocommerce#8489]
Hi guys, 

An issue probably is not the best way to ask this (do you have an IRC?) but why is that class-wc-api-orders.php latest changes are being left outside of the releases? 

Thanks

**Comment by mikejolley** [comment]
@guillegette Only fixes will be picked into 2.3 branch. Features/enhancements need to wait for a feature release, which so happens to be 2.4 coming this month.
