### ISSUE TITLE
WooCommerce Multi-site Checkout page wont work after adding new multisite

### ISSUE THREAD

**Issue by nickkuijpers** [woothemes/woocommerce#8491]
Hi,

When adding a new site to a multi site installation with woocommerce installed as network, the checkout page wont work. It says 404. If i login to each site on the network and go to WooCommerce -> Settings -> Checkout and i click on save, just save, its working again.

**Comment by mikejolley** [comment]
Permalinks will need to be saved for the endpoints to register. Going to Settings > Permalinks and saving will do the same.

WC should ideally be per-site activated, not network activated. You'll have issues with extensions if networked activated.

Multisite compatibility may be enhanced further in the future.

**Comment by nickkuijpers** [comment]
Thanks!
