### ISSUE TITLE
Tabbed "My Account" area

### ISSUE THREAD

**Issue by bekarice** [woothemes/woocommerce#8492]
I think an update of the "My Account" section would be welcomed by both devs and customers, and could be a change to investigate for 2.5/2.6 (depending on when shipping method changes from #8294 are tackled I suppose). 

Currently the My Account page can become a huge, very long page if you have extensions installed. For example, in my test store, I have these sections, each with lots of information:

 - My Subscriptions
 - My Memberships
 - My Social Login Accounts
 - Recent Orders
 - My Addresses
 - Manage My Payment Methods

Once you get past a few orders, this page can require a lot of scrolling to find the information I want, especially if I'm just trying to change my address.

### New Account Section

I think a tabbed account section could make more sense here, as makes it easier for the customer to navigate the account page and view only what they'd like to at a given time. Plugins can add their own tabs if required (thinking of plugins that interact a lot with accounts such as Subscriptions and Memberships) or use the existing ones.

I'd propose core tabs for:

 - My Orders (includes recent orders)
 - My Profile (includes addresses, link to reset password / details, and other plugins could add custom fields or sections here, i.e., social login)
 - My Payments (manage and add saved payments) -- could be an opportunity to standardize how saved payment methods are handled & add them all in the same table

Plugins could then add sections to each tab as needed, or add their own tabs if warranted.

@mikejolley @jameskoster not sure if this should be moved to Trello or who else to tag for consideration; tag away if you think it's something worth investigating for an upcoming version :smiley_cat:

**Comment by claudiosmweb** [comment]
Perhaps this may come along with the ability to add custom endpoints to "My Account" page.
I agree that this page may end up getting huge and complicated for the customers.

**Comment by jameskoster** [comment]
Great idea, +1 from me.

**Comment by mehulkaklotar** [comment]
I think it is a great idea. I have a account section with lot of tabs which i have styled my self to work with easy of use.
![screenshot from 2015-07-02 19 20 20](https://cloud.githubusercontent.com/assets/4090336/8478540/cb4b1ce4-20ef-11e5-9618-85e63babd35b.png)

**Comment by jskandhari** [comment]
Recently joined the Wordpress Woocommerce Wagon and yes I have felt the need to Tabbed My Account area since the first day I was exposed to it !

**Comment by krbvroc1** [comment]
I would also suggest a separate My Downloads section too for the long list of downloadable items which really makes the page long.

**Comment by bolderelements** [comment]
Definitely a good idea! I am trying to modify the account page right now but I am running into limitations. The length of the page is getting crazy adding more details, but I have found I cannot add any sub-pages which is disappointing. Each section has a link to modify the information on it's own page. Could we possibly extend this and add some of our own pages in addition to our custom account sections?

**Comment by justintucker** [comment]
Tabbed would be nice, but custom my account endpoints would be fantastic.

**Comment by bentasm1** [comment]
Don't forget the "Downloads" tab. :-)

**Comment by JasonMarsteller** [comment]
Totally agree.  When WooThemes has an amazing My Account look, they should provide some of that customization for the core product.

**Comment by helgatheviking** [comment]
+1 I duplicated the WooThemes my account look for a client once. I agree that the WooThemes My account area is a lot cooler than the WooCommerce default.

**Comment by mindsize** [comment]
+1

**Comment by claudiosmweb** [comment]
Closed in favor of #10110
