### ISSUE TITLE
Stock Display Format can't be hidden

### ISSUE THREAD

**Issue by micha-b-l** [woothemes/woocommerce#8493]
Hi there,

I'm not able to hide the stock info completely.
WooCommerce > Settings > Product > Inventory > Stock Display Format: Never show stock amount
German translation still shows "Verfügbar" (available).

Maybe the German translation is misleading a bit. It says "never show stock"
I did hide the message with css. 

.woocommerce div.product .in-stock {
   display: none;
}

Is this option to hide stock info completely or only to hide the amount?

Thanks a lot.
Cheers
Micha :)

**Comment by scotcrop** [comment]
@micha-b-l that option is to control the display only, it will only hide the amount. So the options are -

- Always show the actual stock count.
- Only show the actual stock count when its lower than your 'Low Stock Threshold'
- Only show In Stock or Out of Stock. The latter only depending on the 'Out Of Stock Visibility' setting.

If you never want to show the product stock text then you're approach hiding it via CSS works fine or you can use the filter - woocommerce_get_availability see (line 673 specifically) -

http://docs.woothemes.com/wc-apidocs/source-class-WC_Product.html#610-674

**Comment by mikejolley** [comment]
Thanks for explaining this @scotcrop

**Comment by micha-b-l** [comment]
@scotcrop: Thanks for explaining. :)
