### ISSUE TITLE
How to apply coupon via WooCommerce REST API v2

### ISSUE THREAD

**Issue by suifengtec** [woothemes/woocommerce#8494]
How to apply coupon via WooCommerce REST API v2?

`                                "coupon_lines"=>array(
                                    array(
                                    'code'=>'off-12',
                                    'amount'=>'12'
                                    )
                                )
`
the above parameters do not work fine!

`                                "coupon_lines"=>array(
                                    array(
                                    'id'=>'18',
                                    'code'=>'off-12',
                                    'amount'=>'12'
                                    )
                                )
`
the above parameters do not work fine yet!

Anyone reply ?
Thank you!

**Comment by claudiosmweb** [comment]
Please read the documentation: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by suifengtec** [comment]
@claudiosmweb 
Hi,Claudio Sanches!
Thanks for your reply!
I've read the above documentation,but I do not know the format of the coupon for new order endpoint of WooCommerce REST API v2, Could you give me some help?

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
