### ISSUE TITLE
May be a little issue: $this->$set_item( $order, $item, 'create' ); 

### ISSUE THREAD

**Issue by suifengtec** [woothemes/woocommerce#8496]
Line 411 of ` includes/wc-api/class-wc-api-orders.php`:
` $this->$set_item( $order, $item, 'create' );
`
I think it should be:
` $this->set_item( $order, $item, 'create' );
`

**Comment by claudiosmweb** [comment]
Nop, see https://github.com/woothemes/woocommerce/blob/817e5355fd99a6470f69075caf0f9415bf106208/includes/api/class-wc-api-orders.php#L434

**Comment by suifengtec** [comment]
thanks!
