### ISSUE TITLE
Both shipping methods show for all products but shouldn't

### ISSUE THREAD

**Issue by thepartsshoppe** [woothemes/woocommerce#8497]
Under shipping; I have defined 2 shipping methods -Flat Rate Shipping and Free Shipping. All products except one have Flat Rate Shipping defined. Only one product (eBook) has Free shipping defined. Regardless of what you add into the cart, both shipping methods show up and are selectable. This is a bug.

1.All products (except ebook) should show only the Flat Rate shipping method. 
2.If only the ebook is in the cart, it should only be free shipping 
3.If combined products (ebook + a flat rate shipping product), Flat Rate shipping should be the only one showing up.

**Comment by thepartsshoppe** [comment]
![2015-07-01-cart _ the parts shoppe - internet explorer](https://cloud.githubusercontent.com/assets/13139673/8462158/9d79487c-1fe6-11e5-9b95-e51dd5717e4a.png)

**Comment by mikejolley** [comment]
Shipping classes are not used to restrict shipping methods.

**Comment by thepartsshoppe** [comment]
Then why does each product have their own shipping class selection?

**Comment by scotcrop** [comment]
@thepartsshoppe see http://docs.woothemes.com/document/product-shipping-classes/
