### ISSUE TITLE
Order totals & Discounts

### ISSUE THREAD

**Issue by pf62** [woothemes/woocommerce#8500]
We are using the API in an app developed in c# to create orders through. My questions/issue is in two parts:

1) If we want to provide a discount (either % or value) against the entire order, not just one item, what is the official way of doing so? We are currently adding a negative fee and negative fee tax to discount the order by the amount required.

2) When we add an order through the API, with or without a negative fee (we have tried this with negative and positive value fees) the order gets added but the tax line value and total order value are wrong. to correct the issue we have to go into the order and manually press calculate tax and calculate totals (through wp-admin) for it to correct and update all the figures. I don't understand why it isn't working out the correct values when the order is first added in via API.

Thanks!

**Comment by scotcrop** [comment]
@pf62 I'd say the best way is to create a new coupon using the API or use an existing coupon code that provides the % or value you want to give off the cart total.  

The following links should get you started -

To create a coupon - 
https://woothemes.github.io/woocommerce-rest-api-docs/#create-a-coupon

When creating the order add the coupon ( see coupon lines ) - 
https://woothemes.github.io/woocommerce-rest-api-docs/#create-an-order
https://woothemes.github.io/woocommerce-rest-api-docs/#orders
https://woothemes.github.io/woocommerce-rest-api-docs/#orders-properties

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.

**Comment by pf62** [comment]
@claudiosan isnt my point 2 considered an issue? calculations are wrong despite correct values in the lines above.
