### ISSUE TITLE
Trying To Use WP Dialog In WooCommerce Product Page [WP-ADMIN]

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#8502]
I am trying to use wordpress dialog popup script in product post type. [WP-ADMIN] but it dose not work because WooCommerce Enque `jQuery-UI-Style` do to that i am getting wrong style output

1. Valid Style Output 
![valid](https://cloud.githubusercontent.com/assets/1884287/8469602/2ed5c958-209b-11e5-8ceb-9e8bd03d84b9.png)

2. Invalid Style Output [Getting In WooCommerce Product Add / Edit Page in WP-ADMIN]
![invalid](https://cloud.githubusercontent.com/assets/1884287/8469601/2ecf6644-209b-11e5-9959-110f892ea048.png)

how i can fix and get this done. :-(

Code I Used
`wp_enqueue_style (  'wp-jquery-ui-dialog');   wp_enqueue_script( 'jquery-ui-dialog' );  `

` var ajaxloading = jQuery("<div id='loading' />").html('Tedsting').appendTo("body"); 
  ajaxloading.dialog({
        'dialogClass' : 'wp-dialog',
        'modal' : true,
        'autoOpen' : false,
        'closeOnEscape' : false,
        'width' :'auto',
        'title':'Loading Css Please Wait',
        'buttons' :''
    });  
    ajaxloading.dialog('open');
`

**Comment by prionkor** [comment]
Can you try a higher priority for the `wp-jquery-ui-dialog` to make sure it loads after the jquery UI css?

**Comment by technofreaky** [comment]
i also tried it but not working. :(

**Comment by prionkor** [comment]
Can you post more code? The add action and callback for the style enqueue?

**Comment by technofreaky** [comment]
code i used

```php
        add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_styles' ) );
        add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_scripts' ) );
        /**
	 * Register the stylesheets for the admin area.
	 */
	public function enqueue_styles() {  
		wp_enqueue_style(WC_RBP_NAME,plugins_url('css/style.css',__FILE__) , array(), WC_RBP_VERSION, 'all' );
        wp_enqueue_style (  'wp-jquery-ui-dialog'); 
	}
	
    /**
	 * Register the JavaScript for the admin area.
	 */
	public function enqueue_scripts() {
		wp_enqueue_script(WC_RBP_NAME, plugins_url('js/script.js',__FILE__), array( 'jquery' ), WC_RBP_VERSION, false );
        wp_enqueue_script( 'jquery-ui-dialog' );  
        
	}
```

**Comment by prionkor** [comment]
What happens if you use 

`add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_styles' ), 999 );`

**Comment by technofreaky** [comment]
tried it but the exact style not working because jquery ui style is included in the page. if remove it.. it works prefect...

**Comment by prionkor** [comment]
Style files may be printing in wrong order. Can you check which order they are added in the page.

**Comment by technofreaky** [comment]
no i checked It

jquery-ui-style loads 1st and the only the wp-jquery-ui-dialog loads

**Comment by prionkor** [comment]
Order should be like this 

1. jquery-ui-style
2. wp-jquery-ui-dialog
3. Your plugin style

Did you tried my modification for enqueue function? You put `wp_enqueue_style (  'wp-jquery-ui-dialog');` after your plugin css enqueue before. Check if that works. Otherwise you may need to add styles manually targeting the id.

**Comment by technofreaky** [comment]
This is the order i get it sir :(
```
<link rel='stylesheet' id='jquery-ui-style-css'  href='//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css?ver=1.11.4' type='text/css' media='all' />
<link rel='stylesheet' id='wp-jquery-ui-dialog-css'  href='http://192.168.1.3/wpp/base/wp-includes/css/jquery-ui-dialog.css?ver=4.2.2' type='text/css' media='all' />
<link rel='stylesheet' id='WC Role Based Price-css'  href='http://192.168.1.3/wcrbp/wp-content/plugins/woocommerce-role-based-price/admin/css/style.css?ver=1.3' type='text/css' media='all' />
```

**Comment by prionkor** [comment]
hmm.. I think `wp-jquery-ui-dialog.css` is not written to override jquery ui styles. You may need to manually target and restyle.

**Comment by technofreaky** [comment]
i also try it using manual override but if the jquery ui style present the style applies only 50%

**Comment by mikejolley** [comment]
We are forced to load in jquery-ui styles as WP core has no for things like datepickers and sliders.

http://stackoverflow.com/questions/8849684/wordpress-jquery-ui-css-files

You would need to unregister/deenqueue ours (named 'jquery-ui-style') if you don't want it. That style includes all jquery ui components.

**Comment by technofreaky** [comment]
if i unregister/deenqueue it wont affect Woo Commerce product Edit Page Layout ?

**Comment by mikejolley** [comment]
It could affect datepickers etc so you'd need to enqueue your own jquery UI styles.
