### ISSUE TITLE
Cart session remains when changing user

### ISSUE THREAD

**Issue by neovea** [woothemes/woocommerce#8504]
Hi I just updated from 2.1 to 2.3.11 and a strange behaviour is happening : When I add someting to cart with user A and logout, then loggin with user B, user's A cart remains and appears in user's B cart.
It happens when loggin in through the same navigator. If I loggin with another one, the cart remains empty. 
I'm using session_start() in one of my plugins, but removing this doesn't resolve this issue.

**Comment by mikejolley** [comment]
Are you doing any static caching?

**Comment by neovea** [comment]
Hi, there is no caching system at all.

**Comment by neovea** [comment]
I assume that cart are persistent. However, this behaviour still doesn't happen on our production env. By the way, I tried with different items on both accounts.

**Comment by neovea** [comment]
I go on with this issue. I tried to dump `$woocommerce->session->get_session_cookie()` under two different accounts. The customer_id, session_expiration, session_expiring and cookie_hash are exactly the same.

**Comment by mikejolley** [comment]
@neovea Have you seen how customer IDs are generated? https://github.com/woothemes/woocommerce/blob/ecac3fba413afeaa7dc7c6ddd7d49cf4fc7e7b45/includes/class-wc-session-handler.php#L126

I've only ever seen this happen when using caching. Varnish.

**Comment by mikejolley** [comment]
Ok. Did some more testing and cannot find an issue.

1. If you're logged out, and then log-in, your cart will remain. It's preserved (feature).
2. if you're logged in with user A, and log out. The cart is removed. Logging in with user B will not restore user A's cart.
3. If you log-in with the user A after the above case, the cart is restored.

**Comment by karthikesav** [comment]
But for me this issue still persists.
As you said 
1. If you're logged out, and then log-in, your cart will remain. It's preserved (feature). - **This is OK**
2. if you're logged in with user A, and log out. The cart is removed. Logging in with user B in same browser window, restore's user A's cart.
3. So if you log-in with the user A after the above case, the cart remain same.

**Comment by webkitvn** [comment]
@karthikesav same issue

**Comment by karthikesav** [comment]
@webkitvn, is somebody's gonna see this issue?, because this thread is closed and i'm not sure @mikejolley will see this. And by the way the issue still persists..

**Comment by itsgauravjain22** [comment]
Mentioned issue is still present in WordPress 4.9.2 and woocommerce 3.2.6.
Please suggest a workaround for this issue as it's very critical.

**Comment by kiwiot** [comment]
All sorts of weirdness has been happening with cart sessions lately - Im seeing carts being shared between browsers with different logged in users and have made a screencast as proof but do not want this public as it is for a site under development - I have sent this privately.

This problem is being reported by other developers on the project and I have also seen it on other sites so its not build specific.

Both sites are running 
WP 4.9.4
WC 3.3.1

**Comment by Distysoftware** [comment]
I can confirm what Jared said. In the past week I've had to do about $2300 in refunds from cart ""contamination"" The users do not see another persons items when they go to check out.
After the final click they get a surprise. 

One customer had 1 item at $251 in his cart and was charged for 3 items at $1700. 
Had another customer end up with a payment plan of $1600 the very next day (yesterday)

A customer said he thought that we we're shady and adding things to baskets and I simply had no response because no matter what we say, you cant call a cart secure if someone else's stuff ends up in it. 

I have a very uneasy feeling about the state of Woo right now.

**Comment by mikejolley** [comment]
The last person who said they were reproducing this were on the same browser/different profiles. So I'm still certain this is not a bug but is indeed **server caching.** No eCommerce plugin can get around the caching rules imposed by your server.

**Comment by Distysoftware** [comment]
This happened between 2 computers 7000 miles apart Mike ...

**Comment by Distysoftware** [comment]
We do not have caching enabled . And we block the fragments because they are so slow .... and kill gtmetrix scores

**Comment by kiwiot** [comment]
Ive not been able to reproduce errors again (yet) - may have come down to Local Storage being used in separate browsers.

As soon as I can reliably recreate the issue tho I will post it here

**Comment by mikejolley** [comment]
@Distysoftware I'm not talking about a caching plugin. I'm talking about caching on your server. e.g. vagrant. Some hosts enable this by default and need rules in place to avoid sessions being shared.

https://docs.woocommerce.com/document/configuring-caching-plugins/

**Comment by Distysoftware** [comment]
Host says no server side caching and to go talk to the developer which is you sir I'm told. 
Didn't know that and didn't mean to offend in any way. I hope my issue disappears as mysteriously as the last guy's did too.

Well I un-min'd everything. Did tonight's update. The girl who sits behind me logged in to update some items and there were 2 products in HER cart. So i don't think i helped very much.

**Comment by mikejolley** [comment]
Not come across that one so cannot say. Disable and rule it out?

**Comment by Distysoftware** [comment]
Will do, thx. I’m totally reaching but anything is worth a try

**Comment by Distysoftware** [comment]
I never got my issue resolved … Woo blamed host, Host blamed Woo

No caching anywhere that I can see. 

Carts persists beyond cache for whatever reason…

I did a test and created 2 accounts to affirm that I’m not crazy. 
Logged in as user1 and added 10 items to the cart and logged off.
Login as user 2 and all 10 items indeed are there for next guy. 

 

This isn’t a once in a while thing. It seems to be most of the time or all of the time.

Can’t tell shoppers to clear cache and cookies before using the store.

Can’t do it for them either which seemed most logical.

 

Setting Expiration doesn’t help either because I turned off all caching..

This is called Stuck…between that proverbial Rock and Hard Place

**Comment by Distysoftware** [comment]
Windows Chrome and Edge…

**Comment by mdharrington** [comment]
just checked with siteground, they said zero caching on there end with everything disabled and flushed......will now try to exclude caching of certain pages in cloudflare....or disable persistent cart

I just tried with edge and it is ok on my end....strictly safari right now

**Comment by mikejolley** [comment]
I suggested to Disty it was persistent cart which is a different thing. But the shared cart when not logging in/out is down to shared cookies due to caching. Post on help desk - they can see what's active and check if caching headers are present.

**Comment by Distysoftware** [comment]
We actually shut the site down 2 days ago to get a handle on things. Woo support bailed completely the second they found
out we spoke with Mr Jolly. 


We ran into a bigger issue with the SkyVerge merchant gateway having Jquery conflict with woo. 
As if that wasn’t enough Visitor Track did too and then WP Projects.. You can turn off every single plugin except Woo
and works as expected. Turn on the gateway boom conflict. Terms box don’t open no more, cant enter a CC
Cant add one in my-account either. Pretty much same deal with WP Projects and Reversed. Leave WPP on 
turn on woo and bam…no more pretty project for you.



With Visitor Track WPAdmin just fine. Turn On Woo lose your admin. Turn VT off get it back.  
Visitor Track just said F*** it and just decided to not support Woo installations anymore and gave me our $ back.

 

But I don’t blame Woo… I blame Wordpress for allow these plugin guys to go off and use whatever they think is good nuff for jquery 
and expect migrate to pick up the slack.

 

We are in an all or nothing though situation though. I never  expected a plugin purchased off woo to be in conflict
Been trying to stay away from edd because we have over a thousand invested in woo plugins but like I said b4 
We are very bearish on Woo outlook right now... Its grim and man their support just doesn’t get it done

**Comment by Distysoftware** [comment]
Don’t get me wrong though - I’m still their biggest fan

 

One thing I’ve learned over the past 2 decades in the software industry is that it doesn’t matter what 

language you write in, big updates suck (for both sides) and we have seen quite a few lately

**Comment by glagonikas** [comment]
I've been following this thread for quite a while as it's something we've been experiencing too. At first i blamed Redis, but I've disabled completely and it still happens regularly. I first noticed in Q4 2017 and we're still in 3.2.

I often notice random products added to my cart when i haven't added any. It doesn't appear to happen on incognito windows, which makes me think it's related to session handling for logged-in users only. Hope this is limited to cart sessions only and is not a security threat that exposes any details to the wrong user.

I often have a few deadlocks on our logs, similar to ` WordPress database error Deadlock found when trying to get lock; try restarting transaction for query REPLACE INTO `wp_woocommerce_sessions` ` but i'm yet to find any links to this issue.

From the looks of it, the issue affects a limited amount of sites. Could you all post the details of your server and any other official WC plugins you might have? This might help identify a common pattern.

For example we're using Nginx cache and WC Composite Products, WC Subscriptions and WC Subscribe All The Things.

**Comment by mdharrington** [comment]
100% does not happen on incognito.

Disabled all plugs for troubleshooting, except woo and Divi. Lots of plugins listed...but currently all disabled.
Server is siteground...

`
### WordPress Environment ###

Home URL: https://sainth.ca
Site URL: https://sainth.ca
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.28
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wpm7_
MaxMind GeoIP Database: ✔
Total Database Size: 14.31MB
Database Data Size: 12.27MB
Database Index Size: 2.04MB
wpm7_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB
wpm7_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpm7_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpm7_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpm7_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpm7_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpm7_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpm7_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpm7_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpm7_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpm7_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpm7_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpm7_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpm7_woocommerce_log: Data: 0.02MB + Index: 0.02MB
sib_model_contact: Data: 0.02MB + Index: 0.00MB
wpm7_404_to_301: Data: 0.02MB + Index: 0.00MB
wpm7_amzFulfillment_fulfillment: Data: 0.02MB + Index: 0.02MB
wpm7_amzFulfillment_inventory: Data: 0.02MB + Index: 0.02MB
wpm7_amzFulfillment_log: Data: 0.02MB + Index: 0.00MB
wpm7_amzFulfillment_orderUpdateTime: Data: 0.02MB + Index: 0.02MB
wpm7_amzFulfillment_package: Data: 0.02MB + Index: 0.02MB
wpm7_commentmeta: Data: 0.02MB + Index: 0.03MB
wpm7_comments: Data: 0.02MB + Index: 0.09MB
wpm7_feedmanager_channel: Data: 0.02MB + Index: 0.03MB
wpm7_feedmanager_country: Data: 0.02MB + Index: 0.03MB
wpm7_feedmanager_errors: Data: 0.02MB + Index: 0.00MB
wpm7_feedmanager_feed_status: Data: 0.02MB + Index: 0.03MB
wpm7_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB
wpm7_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB
wpm7_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB
wpm7_feedmanager_source: Data: 0.02MB + Index: 0.03MB
wpm7_instock_email_alert: Data: 0.02MB + Index: 0.00MB
wpm7_links: Data: 0.02MB + Index: 0.02MB
wpm7_options: Data: 2.30MB + Index: 0.08MB
wpm7_postmeta: Data: 1.52MB + Index: 0.28MB
wpm7_posts: Data: 6.52MB + Index: 0.14MB
wpm7_sib_model_forms: Data: 0.02MB + Index: 0.00MB
wpm7_sib_model_users: Data: 0.02MB + Index: 0.00MB
wpm7_termmeta: Data: 0.02MB + Index: 0.03MB
wpm7_terms: Data: 0.02MB + Index: 0.03MB
wpm7_term_relationships: Data: 0.02MB + Index: 0.02MB
wpm7_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpm7_usermeta: Data: 0.02MB + Index: 0.03MB
wpm7_users: Data: 0.02MB + Index: 0.05MB
wpm7_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpm7_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpm7_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wpm7_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wpm7_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wpm7_wfBlocks: Data: 0.02MB + Index: 0.02MB
wpm7_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wpm7_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wpm7_wfConfig: Data: 0.06MB + Index: 0.00MB
wpm7_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wpm7_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wpm7_wfFileMods: Data: 0.02MB + Index: 0.00MB
wpm7_wfHits: Data: 0.36MB + Index: 0.17MB
wpm7_wfHoover: Data: 0.02MB + Index: 0.02MB
wpm7_wfIssues: Data: 0.02MB + Index: 0.06MB
wpm7_wfKnownFileList: Data: 0.02MB + Index: 0.00MB
wpm7_wfLeechers: Data: 0.02MB + Index: 0.00MB
wpm7_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wpm7_wfLocs: Data: 0.02MB + Index: 0.00MB
wpm7_wfLogins: Data: 0.02MB + Index: 0.03MB
wpm7_wfNet404s: Data: 0.02MB + Index: 0.02MB
wpm7_wfNotifications: Data: 0.02MB + Index: 0.00MB
wpm7_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wpm7_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wpm7_wfScanners: Data: 0.02MB + Index: 0.00MB
wpm7_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wpm7_wfStatus: Data: 0.02MB + Index: 0.03MB
wpm7_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wpm7_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wpm7_wpml_mails: Data: 0.02MB + Index: 0.00MB
wpm7_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
wpm7_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 136
custom_css: 1
customize_changeset: 4
et_pb_layout: 23
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 8
o-discount: 1
o-list: 1
page: 10
post: 3
product: 18
product_variation: 30
revision: 537
wafs: 1
was: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #50319 - /cart/
Checkout: #50320 - /checkout/
My account: #50321 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: SaintH_v1.0
Version: 3.0.90
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.106
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by glagonikas** [comment]
Hmm interesting... I notice your web server is on Apache, but the response headers of your page mention
```
server: nginx
x-proxy-cache: MISS
```
It therefore seems that you have Nginx cache (like we do). Let's see if the others use it also.

**Comment by mdharrington** [comment]
Siteground supercacher is Nginx I believe.

**Comment by mdharrington** [comment]
Just to clarify, my issue is for non logged in users getting shared cart updates. Right now seems isolated to safari on iphones...and not universal. 3 out of 4 phones tested have this issue today. Yesterday was 5/5

**Comment by karthikesav** [comment]
@mdharrington, yes for me too, the problem i faced even with logged in user and the problem comes in localhost too..

**Comment by Distysoftware** [comment]
Litespeed (no plugin)  
Divi, 
Awesome Support, 
Subscriptions, 
SkyVerge Payeezy, 
WP Proejects Pro, 
BasePress Pro, 
DWQA Pro, 
Content Aware Sidebars (Pro)

Redux, 
Quick Lic Manager, 
Woo Endpoint Manager, 
Deposits, 
NavXT, 
PageNavi

WC Drain Speed Repair, 
Gonzales

WP Optimize

Memberships (Disabled)

WooCommerce Subscription Downloads (Disabled)

AIO Migration (Disabled)

**Comment by mdharrington** [comment]
with all plugins disabled, and caching off for 24 hours....this is now a non issue.
Will slowly enable caching and start re-enabling plugins and see.

Siteground has a memory cacher that stores objects and API calls....this one kinda scares me to re-enable

**Comment by RubenBarriosFuentes** [comment]
I had the same issue, the thing is that I didn´t save the Cart content and then Destroy the session at logout.
I use the Cart::store($user_id) every time that i modify the cart content, and also before logging out and when logging in (important, otherwise, the cart will be deleted if you login and logout without modifying it).
And used the Cart::destroy($user_id) when logout to destroy the token that it generates in the browser.

Hope you find it usefull.

**Comment by ethan-tqa** [comment]
Here I am, reporting yet another casualty caused by the bug (or a related bug). I have a simple site, with caching disabled. What I noticed is that when user logs out, the cart session cookie remains on the browser storage. If this user is logged in on a different browser and start adding items to his cart, the logged out browser can see new cart content after a refresh! This is absolutely unacceptable. At the minimum the cookies must be deleted after logout. I’m not sure if caching is to blame for this one.

**Comment by glagonikas** [comment]
Hi @ethan-tqa can you list your plugins and the name of your host to see if there are any patterns? Some hosts have their own caching.

Also, it would be great if you could list the exact steps to reproduce your issue. I tried them on our server without any caching and just WC and WP running on StoreFront and i couldn't reproduce it but i might have missed a step.

**Comment by mikejolley** [comment]
Cookies are destoyed on logout:

https://github.com/woocommerce/woocommerce/blob/1743c13225e8c37176f7447296f5c138157d4750/includes/class-wc-session-handler.php#L74

And:

https://github.com/woocommerce/woocommerce/blob/1743c13225e8c37176f7447296f5c138157d4750/includes/class-wc-session-handler.php#L243-L260

On logout, the session is deleted from the database, and the cookie is unset.

**Comment by ethan-tqa** [comment]
Hi @glagonikas and @mikejolley, I’m not entirely sure why it did not delete the cookies, when I tested in Chrome Incognito and Safari. It appears that only the cart related cookie is left behind. Right now I do not have time to test so I had to disable persistent cart. I run my server on DigitalOcean, with OpenLitespeed droplet image but when the bug happened, I had debug mode of LiteSpeed Cache plugin turned on, which disables all caching.

**Comment by ethan-tqa** [comment]
After some further testing, it seems like function destroy_session() in session handler is not called when user logout. Then I found out that there is a plugin which hooks onto wp_logout and redirects user to home page. This plugin happened to use default priority, and get called before Woocommerce session handler, so the session handler did not have a chance to clean up the session. So it was my fault for not checking for this. However, I think it highlights the fact that this issue cannot be pinned solely on caching.

**Comment by Jbezza** [comment]
> Cookies are destoyed on logout:
> 
> [woocommerce/includes/class-wc-session-handler.php](https://github.com/woocommerce/woocommerce/blob/1743c13225e8c37176f7447296f5c138157d4750/includes/class-wc-session-handler.php#L74)
> 
> Line 74 in [1743c13](/woocommerce/woocommerce/commit/1743c13225e8c37176f7447296f5c138157d4750)
> 
>  		add_action( 'wp_logout', array( $this, 'destroy_session' ) ); 
> And:
> 
> [woocommerce/includes/class-wc-session-handler.php](https://github.com/woocommerce/woocommerce/blob/1743c13225e8c37176f7447296f5c138157d4750/includes/class-wc-session-handler.php#L243-L260)
> 
> Lines 243 to 260 in [1743c13](/woocommerce/woocommerce/commit/1743c13225e8c37176f7447296f5c138157d4750)
> 
>  	public function destroy_session() { 
>  		$this->delete_session( $this->_customer_id ); 
>  		$this->forget_session(); 
>  	} 
>   
>  	/** 
>  	 * Forget all session data without destroying it. 
>  	 */ 
>  	public function forget_session() { 
>  		wc_setcookie( $this->_cookie, '', time() - YEAR_IN_SECONDS, apply_filters( 'wc_session_use_secure_cookie', false ) ); 
>   
>  		wc_empty_cart(); 
>   
>  		$this->_data        = array(); 
>  		$this->_dirty       = false; 
>  		$this->_customer_id = $this->generate_customer_id(); 
>  	} 
>   
> On logout, the session is deleted from the database, and the cookie is unset.

Hi, this code fixed the issue of carts being duplicated for our site.  However, we cant see this in the latest release 3.5.6?  When will this code be put into the main release version? As without this code the error was having a very detrimental effect on our site.  Thanks.

**Comment by mikejolley** [comment]
It is in current version.

**Comment by Jbezza** [comment]
> It is in current version.

Hi Mike, I cant find the forget_session() function in the class-wc-session-handler.php.  Has this been put in a different location?

**Comment by mikejolley** [comment]
Thats new (3.6). The `destroy_session` logic is not though.

**Comment by PyramidMDT** [comment]
Hello, I guess over a year later this is still happening, New site, on siteground, Caching turned off urls for account, cart and checkout blocked from cach and customers are seeing previous customers order information in checkout page. Separate machines, Separate sessions, miles apart. not a high level of confidence on this over this amount of time. Has anyone on this thread cured the problem?

**Comment by doubleo2** [comment]
@PyramidMDT I am seeing the same issue. I'm using Wordpress and MultilingualPress to host two shops in different subdirectories - minimal other plugins - hosted on Kinsta. Cart and checkout pages are excluded from caching and user accounts are disabled. Users are seeing items being added to their carts and other user's billing information pre-populated on the checkout page.

**Comment by nadvertexsupport** [comment]
Cart empty issue for logged in user on different browsers and devices cart got empty.

https://drive.google.com/file/d/1qTZjIkGKpZkrZd-pS4-FGpCt_FOhF6np/view
