### ISSUE TITLE
API - Taxonomies and meta data.

### ISSUE THREAD

**Issue by mikaelmattsson** [woothemes/woocommerce#8505]
I'm syncing two external product system with WooCommerce and I need some kind of way to set the taxonomies and meta data on a product (write only). Not just categories and tags. 
This was requested in #8249 and declined. claudiosmweb makes a good point that whoever registers a taxonomy should have to create an endpoint for that. But this sets a big limitation. And what about meta data? Metadata isn't registered. Should you really have to manually create an endpoint for that?

I'm so close to being able to integrate the external product systems with any site without having to install any plugins.

**Comment by claudiosmweb** [comment]
@mikaelmattsson you can create endpoints or use your filters and actions.
For example for products, you can save fields using the `woocommerce_api_create_product` action:
https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L285

Edit with `woocommerce_api_edit_product`:
https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L374

And show with `woocommerce_api_product_response`:
https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L169

**Comment by mikaelmattsson** [comment]
I understand that this is doable. But i don't want to have to write specific code fo all my sites.
