### ISSUE TITLE
Post ID Error when using woocommerce_wp_text_input in ajax

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#8507]
I am using woocommerce_wp_text_input and other related function in ajax which creates an below 
![wc_error](https://cloud.githubusercontent.com/assets/1884287/8498201/c499ca3c-21a1-11e5-9df9-67dfad88ce30.png)

i was check the issue with `var_dump()` in file `woocommerce/includes/admin/wc-meta-box-function.php` so the line number is changed to 39 for your reference

 kindly check the screenshot below

![wc_error1](https://cloud.githubusercontent.com/assets/1884287/8498255/2d97be9a-21a2-11e5-9c89-f0b3ae0bee5a.png)

**Comment by claudiosmweb** [comment]
@technofreaky This function is for use only within loops or where has the `WC_Post` object.

**Comment by mikejolley** [comment]
These methods are only intended for use in writepanels. Your fix would work for your case, but in reality these functions need refactoring as part of https://github.com/woothemes/woocommerce/issues/6361

We'll see about doing this in 2.5. The current functions need to be unified.

**Comment by technofreaky** [comment]
Then i can use in plugin ?

**Comment by mikejolley** [comment]
If its via ajax, don't. Pretend the functions don't exist. You can output input boxes yourself.

**Comment by technofreaky** [comment]
i am trying to use this in variable product edit form in product edit page

**Comment by claudiosmweb** [comment]
@technofreaky don't works on variable product edit. WE don't use for variable edit. See:
https://github.com/woothemes/woocommerce/blob/release/2.3/includes/admin/meta-boxes/views/html-variation-admin.php

**Comment by technofreaky** [comment]
No I hooked my plugin to that

On Tue, Jul 07, 2015 at 7:56 pm, Claudio Sanches < notifications@github.com [notifications@github.com] > wrote:
@technofreaky [https://github.com/technofreaky] don't works on variable product edit. WE don't use for variable edit. See:

https://github.com/woothemes/woocommerce/blob/release/2.3/includes/admin/meta-boxes/views/html-variation-admin.php
[https://github.com/woothemes/woocommerce/blob/release/2.3/includes/admin/meta-boxes/views/html-variation-admin.php]

—
Reply to this email directly or view it on GitHub
[https://github.com/woothemes/woocommerce/issues/8507#issuecomment-119220802] .[https://github.com/notifications/beacon/ABzAf1Q0ia7mwYMGDRhxwOrK_R7Mgx6pks5oa9kRgaJpZM4FRZpv.gif]

**Comment by claudiosmweb** [comment]
@technofreaky ?

**Comment by technofreaky** [comment]
I am adding some fields using action in variable meta box filter

On Tue, Jul 07, 2015 at 8:07 pm, Claudio Sanches < notifications@github.com [notifications@github.com] > wrote:
@technofreaky [https://github.com/technofreaky] ?

—
Reply to this email directly or view it on GitHub
[https://github.com/woothemes/woocommerce/issues/8507#issuecomment-119223706] .[https://github.com/notifications/beacon/ABzAfxaVccBXl6X05KYol9lqgvdJcwE9ks5oa9uXgaJpZM4FRZpv.gif]

**Comment by claudiosmweb** [comment]
@technofreaky Have not you read what I said?
This is the view for variable meta box https://github.com/woothemes/woocommerce/blob/release/2.3/includes/admin/meta-boxes/views/html-variation-admin.php

See we do not use any of these functions there!

**Comment by technofreaky** [comment]
I know I used the same..... You can download my plugin
http://wordoress.Org/plugins/woocommerce-role-based-pricing


And enable debug mode in u r wp and create a variable product there u can see
the error

On Tue, Jul 07, 2015 at 9:35 pm, Claudio Sanches < notifications@github.com [notifications@github.com] > wrote:
@technofreaky [https://github.com/technofreaky] Have not you read what I said?
This is the view for variable meta box 
https://github.com/woothemes/woocommerce/blob/release/2.3/includes/admin/meta-boxes/views/html-variation-admin.php
[https://github.com/woothemes/woocommerce/blob/release/2.3/includes/admin/meta-boxes/views/html-variation-admin.php]

See we do not use any of these functions there!

—
Reply to this email directly or view it on GitHub
[https://github.com/woothemes/woocommerce/issues/8507#issuecomment-119250961] .[https://github.com/notifications/beacon/ABzAf5AzokW3WCoFoRZWHJk4-AMyU3c-ks5oa_BdgaJpZM4FRZpv.gif]

**Comment by claudiosmweb** [comment]
@technofreaky No, you did not read what I said and not checked the file I'm showing you.
