### ISSUE TITLE
Proposal: Adding a filter to the description text on the emails settings tabs

### ISSUE THREAD

**Issue by leglesslizard** [woothemes/woocommerce#8509]
While developing our own extension to Woocommerce (Woocommerce Waitlist) we are using Woocommerce's own methods to send out emails.  Being able to filter the description text to notify the user of when these emails will be sent out would be helpful.

Screenshot below highlights the text on the settings page with the filter applied
![wc-settings](https://cloud.githubusercontent.com/assets/6690398/8501018/92e9558c-2199-11e5-8df8-d5975e19a232.png)

Pull request incoming.

**Comment by mikejolley** [comment]
This should be filterable using gettext filters in WordPress :) Or the message can be made more generic so no text change is needed? Will await suggested pull request but its already possible.
