### ISSUE TITLE
Checkout page trigger click on first method payment and browser scroll to this input

### ISSUE THREAD

**Issue by GastonPowered** [woothemes/woocommerce#8510]
Hi,

I got a problem on my checkout page. When I access it, the page automatically scroll to the payment options.

After some investigation, I found the line 288 in checkout.js `$( '.woocommerce-checkout' ).find( 'input[name=payment_method]:checked' ).eq(0).trigger( 'click' );` which trigger a click and the browser scroll to that input.

I'm not sure why we need the click (I'm guessing IE support) but I think this line goes in the condition just before like this 
```
if ( $( '.woocommerce-checkout' ).find( 'input[name=payment_method]:checked' ).size() === 0 ) {
  $( '.woocommerce-checkout' ).find( 'input[name=payment_method]:eq(0)' ).attr( 'checked', 'checked' );
  $( '.woocommerce-checkout' ).find( 'input[name=payment_method]:checked' ).eq(0).trigger( 'click' );
}
```

Only if no payment method is chosen, it selects the first one and click on it.

**Comment by mikejolley** [comment]
I think this is needed to open the information area when the checkout loads.

Sounds like you may have a script such as 'scrollto' installed on the site. Test on a clean install/our demo install. I don't think its a general issue. Ping me if thats not the case.
