### ISSUE TITLE
Variations scheduled sale price date range incorrect

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#8515]
When setting up a starting and ending date for scheduled sale price for a variation, following variations are restricted to the same dates range, and that shouldn't be the case.

@claudiosmweb

**Comment by claudiosmweb** [comment]
@corsonr I did not quite understand what you meant, but I saw some mistakes with the dates they are being deleted by clicking save twice.

**Comment by corsonr** [comment]
if you set up a range of dates for variation 1, variation 2 will be restricted to variation 1 dates range  @claudiosmweb

**Comment by claudiosmweb** [comment]
@corsonr So I'm not able to simulate this behavior

**Comment by corsonr** [comment]
here is a video, latest WC, latest, WP, Twenty something, no other plugin:

http://cld.wthms.co/bxy/4TLvkUWz

**Comment by claudiosmweb** [comment]
@corsonr I was looking for issues on the frontend, I had not noticed that the problem was with the Datepicker xD

I'm fixing it right now :)

**Comment by claudiosmweb** [comment]
This can be a little complicated to do...

I see that to fix it'll probably break compatibility with any plugin that you use our datepicker.

cc @mikejolley
