### ISSUE TITLE
Refund deleted hook parameter error on version 2.3.11

### ISSUE THREAD

**Issue by Sk-Shaikat** [woothemes/woocommerce#8517]
On 2.3.11 version file 'class-wc-ajax.php', The hook "do_action( 'woocommerce_refund_deleted', $refund_id );" has parameter '$refund_id' dose not trigger in action due to deleted that post. This should set '$order_id' as parameter

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/pull/8516
