### ISSUE TITLE
Bank Details supposed to be as a template 

### ISSUE THREAD

**Issue by abouolia** [woothemes/woocommerce#8531]
https://github.com/woothemes/woocommerce/blob/master/includes/gateways/bacs/class-wc-gateway-bacs.php#L260

Bank details wrapper inside Thank-you page supposed to be as a template to allow to developers to override it. if there's way to do that please show me. Thanks!

**Comment by abouolia** [comment]
Even https://github.com/woothemes/woocommerce/blob/master/includes/gateways/bacs/class-wc-gateway-bacs.php#L121

**Comment by claudiosmweb** [comment]
Not for payment gateways.
And you can change using filters and actions.
