### ISSUE TITLE
WC overwrites display_name

### ISSUE THREAD

**Issue by krbvroc1** [woothemes/woocommerce#8532]
The WC_Form_Handler::save_account_details() is invoked from the 'Edit Account' endpoint.

I have no idea why, but that routine sets
```$user->display_name = $user->first_name;```

This blindly overwrites whatever was stored from other plugins or via the  WP Admin Users panel (Display name publicly as) selection.

In my case, for anonymity, my site stores a separate value in the display_name. Once a user hits 'Save changes' on the WC Edit Account endpoint, any existing display_name value is overwritten. In my case this results in private information disclosure.

Additionally, I found it confusing that 'user_profile_update_errors' is called from the form-handler. I had always assumed that hook was an admin side, not frontend action. Any handlers I had were only registered under the is_admin() so they were not invoked.

**Comment by mikejolley** [comment]
It was a workaround for https://github.com/woothemes/woocommerce/issues/3460

**Comment by krbvroc1** [comment]
@mikejolley You sure this is the correct change? The comment 'Allow plugins to return their own errors.' for `user_profile_update_errors' understates what is being done.That routine actually updates the user via the 'wp_update_user( $user );' in admin.php, the same action taken when someone hits 'save' on the User panel on the backend. Now that you removed the call, there is no wp_update_user being called so the user email and first/last name are not being updated anymore. The above becomes a no-op. Did you mean to replace it with another call?

**Comment by mikejolley** [comment]
@krbvroc1 It's my understanding thats for adding errors only.

We trigger the save https://github.com/woothemes/woocommerce/blob/8bf44691781bd3940247faf3985cd1b38730a33d/includes/class-wc-form-handler.php#L224

**Comment by krbvroc1** [comment]
@mikejolly Yep, you are correct. I was confusing two different things.
