### ISSUE TITLE
Add Product Variation Datepicker not working?

### ISSUE THREAD

**Issue by vicky081** [woothemes/woocommerce#8533]
Hi there,

Today I updated 2.3.13 of woocommerce, i tested this in my side of firefox for Variable Product Datepicker is not working properly, as soon as i created the attributes and save variations, i noticed that scheduling datepicker is not even working unless i save the product, it should not be the case right? 

Take a look at it, i attached screenshot
![firefox_screenshot_2015-07-08t05-59-08 737z](https://cloud.githubusercontent.com/assets/5364600/8564126/b5924d6c-2565-11e5-9f26-1efea6165759.png)

**Comment by mikejolley** [comment]
Looks related to the fix to make each picker independent. It's not critical; you can enter the date manually in the meantime. yyyy-mm-dd format.

**Comment by vicky081** [comment]
Thanks for letting me by :) Such response want me to test more ;)

**Comment by vicky081** [comment]
Hi @mikejolley and @claudiosmweb  i just checked with beta version of 2.4.0, that datepicker problem still persist, is something you guys work around?

**Comment by claudiosmweb** [comment]
@vicky081 works fine in 2.4.0

**Comment by roykho** [comment]
@vicky081 I concur, it works fine in my testing as well.

**Comment by vicky081** [comment]
@roykho @claudiosmweb 
Yes it works when i published the product, see the screenshot now i added, without publish it won't work (Note: if i select create variations from all attributes it works perfectly even if i doesn't publish)
![firefox_screenshot_2015-07-15t13-34-24 910z](https://cloud.githubusercontent.com/assets/5364600/8700031/2ac46068-2b27-11e5-8a91-ad61e2c5c6cd.png)

Image 2
![screenshot from 2015-07-15 19 12 32](https://cloud.githubusercontent.com/assets/5364600/8700219/3d40a89a-2b28-11e5-9886-83b314652662.png)

**Comment by roykho** [comment]
@vicky081 in my testing I created a new variable product ( did not publish ) and manually added one variation ( not create all ) and then I proceed to enter the prices and clicked on schedule.  Lastly I entered the start/end date and clicked save at the bottom of the variations and all is working fine. Perhaps you want to be more descriptive as to what "not working" means so we can better help?

**Comment by vicky081** [comment]
@roykho @claudiosmweb 
Checkout this video https://www.dropbox.com/s/77z2ibkojuo6916/out.ogv?dl=0

**Comment by roykho** [comment]
@vicky081 ok we did different tests.  In my test, I used the global attributes that is already defined but in your test, you're using custom attributes.  Can you please test again but this time with attributes that already exists and let me know if it then works for you?

**Comment by vicky081** [comment]
@roykho 

Yes it is working for global attributes as well, i noticed there is some commit may fix this problem, will check and post it again.

Thanks.

**Comment by vicky081** [comment]
@claudiosmweb  @mikejolley  @roykho :+1:  working fine :smiley:
