### ISSUE TITLE
No documentation about WC-API and WPML or Multi Site

### ISSUE THREAD

**Issue by bigtomjp** [woothemes/woocommerce#8534]
I understand this may not be a truly core functionality and this may not be the best place to bring this, but use WC is certified to work with WPML and there should be some information on how this works. For example, editing multiple language values in one call is possible or not?

I sent a support question through the Woo website and have had no response in 5-6 days or so.

I have asked WPML about this and they have dodged the question. Answered all my questions except this one.

**Comment by mikejolley** [comment]
We don't document WPML functionality in our own docs. WPML have a section on the site for the bridge plugin they offer. That would be here: https://wpml.org/documentation/related-projects/woocommerce-multilingual/

Just to clarify, the WC addon for WPML is sold and maintained by WPML themselves.

Thanks

**Comment by bigtomjp** [comment]
I understand this.  Like I said this is likely not the best place to bring this about WPML.

Although I do recall some mention of something in the API recently being changed to allow getting products in a specific language with WPML. I do not seem to find the mention of it now. 

There is also the topic of multi site. Which was not addressed.

**Comment by mikejolley** [comment]
@bigtomjp WC needs to be activated per-site. Multisite causes issues with extensions.
