### ISSUE TITLE
Broken Sass Import

### ISSUE THREAD

**Issue by aaemnnosttv** [woothemes/woocommerce#8538]
```
Error: File to import not found or unreadable: bourbon.
        on line 10 of ../../plugins/woocommerce/assets/css/woocommerce.scss
```

https://github.com/woothemes/woocommerce/blob/c0ca144d57e09377147870f56df14241cda57012/assets/css/woocommerce.scss#L10

Indeed, it's not there!

**Comment by claudiosmweb** [comment]
http://bourbon.io/
