### ISSUE TITLE
Should there be a time limit on how long an order can be 'pending payment' ?

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#8539]
Whilst running our quarterly report, our EU VAT plugin flagged up a single order that appeared to have been created with a WooCommerce version from before 2.2 (which is significant because those orders don't have line tax items recorded in the same way, and so the specific table that the plugin outputs then has reduced data).

This seemed impossible, as we'd been running WC 2.2 onwards since before 2015 began.

The order number appeared to indicate it was an order from March 2014; but when we looked at the data, the data was all 31st May 2015.

We eventually found the cause. Long story short: the customer ordered a product in March 2014. He went through to PayPal, but did not complete payment. The order thus remained in a "Pending" state until 31st May 2015... at which point, he logged in to his updraftplus.com account, and completed payment (via a different gateway, but that doesn't matter). The order then was completed.

The unexpected / unwelcome consquence of this is that his order data in the posts/postmeta/etc. tables are all in WooCommerce 2.0 format. (WooCommerce 2.1 was released in February 2014 - we'd not completed testing and updating by the time of his order in mid-March 2014). Hence the warning from our EU VAT plugin.

Having orders remain in a "Payment Pending" state for 14 months seems undesirable, because a site could (and should) go through a few major WC version upgrades in this time. I realise that I could manually delete all such orders that reach a certain age, to prevent this (I had no idea it could cause a problem). But I wonder if it should be considered a bug, and that either:
a) WooCommerce should automatically remove orders like this, or
b) WooCommerce should automatically update the order's format? (That could get ugly/problematic easily, I suppose)

What do you think?

**Comment by DavidAnderson684** [comment]
By the way... when this occurs...

1) the customer's order email has the original date from when the order was placed in the subject and email.
2) the customer gets to pay the old price, ignoring any price increases since he placed his order in the 'pending' state.

Screenshot: note that this customer received this email on May 31st 2015, whilst the email has March 2014 everywhere: http://snag.gy/KuxzW.jpg

And... note that this can be used as a cunning way to lock-in prices of items you might want to buy in future. Do this on a shop where you don't want to buy now, but do want to lock in the price:
1) Put item in cart; go to check-out; pay via PayPal; don't complete payment. Result: order is now saved, in "Payment pending" state
2) Come back later, when you want to complete payment - you get to pay at the old price of your 'pending' order.

This particular customer saved himself $10, which nobody will begrudge him. But it seems like something that shouldn't be possible!

**Comment by greguly** [comment]
Interesting problem, I am interested in the outcome. 

BTW lock in prices can work both ways, as your prices could have gone down. 

What about the product not being available any more? How would you deal with it? 

(I noticed your $85 product was named Premium and now you have $95 Business, so most likely you just edited the product. )

**Comment by claudiosmweb** [comment]
![screenshot from 2015-07-08 17 49 07](https://cloud.githubusercontent.com/assets/1264099/8581860/bba7d652-2599-11e5-8125-1a5581486284.png)

**Comment by GermanTorresGray** [comment]
Hi Claudio. I'm wondering how you can set those minutes to each products independently? Regards.
