### ISSUE TITLE
wc_customer_bought_product() query is slow

### ISSUE THREAD

**Issue by chvillanuevap** [woothemes/woocommerce#8549]
A few days ago, I updated WooCommerce to version 2.3.13. I use WordPress 4.2.2 with PHP 5.5.22 and mySQL 5.6.19. I use a custom-built Genesis child theme, with the Genesis Connect for WooCommerce plugin. I have the option `Show "verified owner" label for customer reviews` in WooCommerce >> Settings >> Products set to `true`.

After the update, the single product pages started taking 20+ seconds to load. I ran PageSpeed and YSlow to check what was slowing down my site. According to the report, 90% of the time was spent on waiting for the server to send the info. Based on this information, I installed the Query Monitor plugin to see which queries were being slow. After running a diagnosis on the page, I noticed that the `wc_customer_bought_product()` query was taking about 1+ seconds per customer review. I have 13 customer reviews on the product page, so this is what caused the page to load slowly.

The query looks as follows:

```
SELECT COUNT( DISTINCT order_items.order_item_id ) 
FROM wp_woocommerce_order_items as order_items 
LEFT JOIN wp_woocommerce_order_itemmeta AS itemmeta
ON order_items.order_item_id = itemmeta.order_item_id 
LEFT JOIN wp_postmeta AS postmeta
ON order_items.order_id = postmeta.post_id 
LEFT JOIN wp_posts AS posts
ON order_items.order_id = posts.ID 
WHERE posts.post_status IN ( 'wc-completed', 'wc-processing' )
AND itemmeta.meta_value = '8887'
AND itemmeta.meta_key IN ( '_variation_id', '_product_id' )
AND postmeta.meta_key IN ( '_billing_email', '_customer_user' )
AND ( postmeta.meta_value IN ( 'moreton@charter.net' )
OR ( postmeta.meta_value = '0'
AND postmeta.meta_value > 0 ) )
```

The call stack is:

```
wc_customer_bought_product()-
wc_get_template()
woocommerce_comments()
Walker_Comment->start_el()
Walker->display_element()
Walker_Comment->display_element()
Walker->paged_walk()
wp_list_comments()
comments_template()
wc_get_template()
woocommerce_output_product_data_tabs()
do_action('woocommerce_after_single_product_summary')
gencwooc_single_product_loop()
do_action('genesis_loop')
genesis()
```

I turned off the option to check for verified owners, and the loading time returned to normal. I did not encountered this issue prior to the latest update. I have 5,832 users with the role of Customer, and 25,796 total orders. The `wp_posts` table has 27,078 rows, and the `wp_postmeta` table has 727,501 rows.

**Comment by mikejolley** [comment]
#8458
