### ISSUE TITLE
Layered Nav Widget not removing "add-to-cart" query arg

### ISSUE THREAD

**Issue by KissWebMedia** [woothemes/woocommerce#8554]
Hello,

On both the "WooCommerce Layered Nav" and "WooCommerce Layered Nav Filters" widgets the URLs do not seem to be removing the "add-to-cart" URL arg.

This means that if a user adds a product to the cart on the Product Archive page (non-Ajax) and then uses the layered nav to filter products further then the product is added to the cart again.

There are a few calls to the "remove_query_arg()" function in the "class-wc-widget-layered-nav.php" and "class-wc-widget-layered-nav-filters.php" files. I believe that in these places the "add-to-cart" arg should also be tested and removed if it exists.

Thanks,
Steven

**Comment by mikejolley** [comment]
This only occurs in filters.
