### ISSUE TITLE
Coupon discount calculation not as expected

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#8558]
To recreate:

1. A simple/virtual product exists, its price is 100
2. two separate coupon codes exist
3. Each coupon is a "Product Discount" coupon
4. Each coupon is restricted to the aforementioned product
5. Each coupon offers a discount of 100 

Add a quantity of 2 of the simple product to the cart, apply the first coupon code - 100 is deducted from the cart total as expected. Apply the second coupon code to the cart - this coupon now only deducts 50 from the cart total when the expectation is that it would also deduct 100 and that my cart total would be 0 (assuming no other products are in the cart)

**Comment by mikejolley** [comment]
This was fixed and refactored in 2.4 release :)
