### ISSUE TITLE
/wc-api/v2/customers/<ID>/orders fails to recognise a valid customer ID

### ISSUE THREAD

**Issue by gtawebb** [woothemes/woocommerce#8561]
When I call:

/wc-api/v2/customers/172/orders

I get the following error response:

{"errors":[{"code":"woocommerce_api_invalid_customer_id","message":"Invalid customer ID"}]}

But when I call:

/wc-api/v2/customers

It shows that the customer ID does exists:

{"customers":[{"id":172,"created_at":"2015-07-10T17:32:40Z","email":"support@xxx.com","first_name":"","last_name":"","username":"support","role":"customer","last_order_id":"1723","last_order_date":"2015-07-11T10:51:27Z","orders_count":4,"total_spent":"12.00","avatar_url":"https:\/\/2.gravatar.com\/avatar\/?s=96","billing_address":{"first_name":"G","last_name":"W","company":"","address_1":"1 impasse grande terre","address_2":"","city":"xx","state":"","postcode":"xx","country":"FR","email":"support@xxx.com","phone":"1234567"},"shipping_address":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":""}}]}

The customer ID exists and it has made orders but I'm unable to access the customer orders via the /wc-api/v2/customers/<ID>/orders API call which is a major blocker for me, it just returns an invalid customer error.

**Comment by gtawebb** [comment]
I am contin

**Comment by gtawebb** [comment]
It seems that the ID isn't being passed through properly because if I hard code it within the class 'class-wc-api-customers.php' it then works properly.

I am currently using chrome extension "Advanced Rest Client" to test this and I'm making the call in the following format: 
https://www.XXX.com/wc-api/v2/customers/172/orders?consumer_key=XXX&consumer_secret=XXX

Can anyone explain why the order number isn't being understood by the API, does it need to be encoded somehow?

**Comment by gtawebb** [comment]
I'm getting the same results using CURL

**Comment by gtawebb** [comment]
https://www.xxx.com/wc-api/v2/customers/172 works fine, https://www.xxx.com/wc-api/v2/customers/172/orders doesn't.

**Comment by claudiosmweb** [comment]
What WooCommerce version?

**Comment by gtawebb** [comment]
WooCommerce - Autocomplete Order: by Mirko Grewing – 1.1
WooCommerce Stripe Gateway: by Mike Jolley – 2.5.1
WooCommerce Subscriptions: by Prospress Inc. – 1.5.28
WooCommerce: by WooThemes – 2.3.11
WooThemes Helper: by WooThemes – 1.5.9

**Comment by gtawebb** [comment]
WooCommerce - Autocomplete Order: by Mirko Grewing – 1.1
WooCommerce Stripe Gateway: by Mike Jolley – 2.5.1
WooCommerce Subscriptions: by Prospress Inc. – 1.5.28
WooCommerce: by WooThemes – 2.3.11
WooThemes Helper: by WooThemes – 1.5.9

**Comment by gtawebb** [comment]
I've updated to Version 2.3.13, the issue persists.

**Comment by claudiosmweb** [comment]
I just tested and works fine.
Check the docs: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by maxrice** [comment]
@gtawebb which role do these customers have? subscriber?

**Comment by gtawebb** [comment]
Hi, the role is set to 'customer.' Please see the attached image. I have read the docs and I have tried with both your api's. 

If the role is set to subscriber then neither https://www.xxx.com/wc-api/v2/customers/172 nor https://www.xxx.com/wc-api/v2/customers/172/orders work.

If the role is set to customer https://www.xxx.com/wc-api/v2/customers/172 does work but https://www.xxx.com/wc-api/v2/customers/172/orders does not work.

I'm a bit disappointed @claudiosmweb has closed the issue so abruptly without a resolution. I'm using the commands that are documented. Just because it works on one device and not another does not mean that there is not an underlying issue. Any further support would be appreciated as I've purchased an array of woocommerce plugins from woothemes, however if I can't get the API to work it will be money wasted and I'll need to look for a different solution.

![screen shot 2015-07-13 at 14 35 52](https://cloud.githubusercontent.com/assets/2797452/8649664/9cad25b4-296c-11e5-9147-f3d9d0fc33d9.png)

**Comment by gtawebb** [comment]
It seems that the ID isn't being passed through properly because if I hard code it within the class 'class-wc-api-customers.php' it then works properly.

**Comment by claudiosmweb** [comment]
@gtawebb I close because it works fine and don't have any issue on it.
I tested on your current master and WooCommerce 2.3.13.

**Comment by gtawebb** [comment]
It doesn't appear to work fine under all circumstances which is why I have raised the ticket. 
As stated I am making the appropriate call which returns 'Invalid Customer ID' however if I hardcode the ID into class-wc-api-customers.php it works fine. I know the customer is valid and that he has made orders. Something is not working properly, can we re-open the ticket and help investigate it?

**Comment by claudiosmweb** [comment]
@gtawebb Prove to me that has a bug and then we can open again.
But in any way I can reproduce the error you're saying.

**Comment by gtawebb** [comment]
I have provided details of the issue, the specific call, the error and a way in which to circumvent it, what I find interesting is that the user ID isn't getting through, can you think of a reason this may be?

I appreciate that you may be too busy to give it much time but at least if we keep the issue open until we find a resolution it will allow other people to view and contribute instead of just hiding it away.

**Comment by gtawebb** [comment]
@maxrice I confirm that they user ID 172 has a customer role.

**Comment by claudiosmweb** [comment]
@gtawebb https://cloudup.com/cRu9kjXxYnC

**Comment by claudiosmweb** [comment]
@maxrice go ahead

**Comment by maxrice** [comment]
>If the role is set to customer https://www.xxx.com/wc-api/v2/customers/172 does work but https://www.xxx.com/wc-api/v2/customers/172/orders does not work.

@gtawebb what's the result of GET https://www.xxx.com/wc-api/v2/customers/172/ ? Does it return a valid customer object?

**Comment by gtawebb** [comment]
Hi, thanks for getting back to me. I'm still trying to get to the bottom of this. I have also tried with a different user following the steps in @claudiosmweb video where he users a simple product (no subscription or variants) as well as a direct bank transfer. However this still doesn't help. If there is any debugging you'd like me to add to the PHP I'll be happy to give it a try. As previously stated 

The raw response to:
/wc-api/v2/customers/172/orders
is: 
{"errors":[{"code":"woocommerce_api_invalid_customer_id","message":"Invalid customer ID"}]}

However the response to:
/wc-api/v2/customers/172/
is:
{"customer":{"id":172,"created_at":"2015-07-10T17:32:40Z","email":"support@revisionbuddies.com","first_name":"","last_name":"","username":"support","role":"customer","last_order_id":"1723","last_order_date":"2015-07-11T10:51:27Z","orders_count":4,"total_spent":"12.00","avatar_url":"https:\/\/0.gravatar.com\/avatar\/?s=96","billing_address":{"first_name":"George","last_name":"Webb","company":"","address_1":"1 impasse grande terre","address_2":"","city":"rognonas","state":"","postcode":"13870","country":"FR","email":"support@revisionbuddies.com","phone":"1234567"},"shipping_address":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":""}}}

In that response the last_order_id is 1723.

SO, the response to:
/wc-api/v2/orders/1723
is:
{"order":{"id":1723,"order_number":1723,"created_at":"2015-07-11T10:51:27Z","updated_at":"2015-07-11T10:51:27Z","completed_at":"2015-07-11T10:51:27Z","status":"completed","currency":"GBP","total":"0.00","subtotal":"0.00","total_line_items_quantity":1,"total_tax":"0.00","total_shipping":"0.00","cart_tax":"0.00","shipping_tax":"0.00","total_discount":"0.00","shipping_methods":"","payment_details":{"method_id":"stripe","method_title":"Credit card (Stripe)","paid":true},"billing_address":{"first_name":"George","last_name":"Webb","company":"","address_1":"1 impasse grande terre","address_2":"","city":"xxx","state":"","postcode":"xxx","country":"FR","email":"support@revisionbuddies.com","phone":"1234567"},"shipping_address":{"first_name":"George","last_name":"Webb","company":"","address_1":"1 impasse grande terre","address_2":"","city":"xxx","state":"","postcode":"13870","country":"FR"},"note":"","customer_ip":"90.8.6.65","customer_user_agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/43.0.2357.130 Safari\/537.36","customer_id":172,"view_order_url":"https:\/\/www.xxx.com\/my-account\/view-order\/1723","line_items":[{"id":27,"subtotal":"0.00","subtotal_tax":"0.00","total":"0.00","total_tax":"0.00","price":"0.00","quantity":1,"tax_class":null,"name":"GCSE History","product_id":1612,"sku":"gcsehistory","meta":[]}],"shipping_lines":[],"tax_lines":[{"id":28,"rate_id":"1","code":"VAT-1","title":"VAT","total":"0.00","compound":false}],"fee_lines":[],"coupon_lines":[],"customer":{"id":172,"created_at":"2015-07-10T17:32:40Z","email":"support@revisionbuddies.com","first_name":"","last_name":"","username":"support","role":"customer","last_order_id":"1723","last_order_date":"2015-07-11T10:51:27Z","orders_count":4,"total_spent":"12.00","avatar_url":"https:\/\/0.gravatar.com\/avatar\/?s=96","billing_address":{"first_name":"George","last_name":"Webb","company":"","address_1":"1 impasse grande terre","address_2":"","city":"xxx","state":"","postcode":"xxx","country":"FR","email":"support@revisionbuddies.com","phone":"1234567"},"shipping_address":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":""}}}}

I confirm that user 172 still has a customer role.

**Comment by gtawebb** [comment]
I've added some debugging to 
I've added some debugging to woocommerce/includes/api/class-wc-api-customers.php line 708 and it seems that $id is being read as 'orders' instead of the id number. Maybe this gives a clue?


      protected function validate_request( $id, $type, $context ) {

		try {
			throw new WC_API_Exception( 'woocommerce_api_invalid_customer_id'.'$id='.$id, __( 'Invalid customer ID', 'woocommerce' ), 404 );
			$id = absint( $id );

Output = {"errors":[{"code":"woocommerce_api_invalid_customer_id$id=orders","message":"Invalid customer ID"}]}

Notice the value of $id that I've added to the above forced error.

**Comment by claudiosmweb** [comment]
@gtawebb Product type or payment method will have no influence on it!

**Comment by gtawebb** [comment]
@claudiosmweb I wouldn't have thought they would either, just trying to rule things out and match your working example.

**Comment by maxrice** [comment]
@gtawebb are you testing this with all plugins deactivated and twentytwelve theme? Need to make sure there's nothing conflicting

**Comment by gtawebb** [comment]
@maxrice Yes I have tried that. I will try it again this evening double checking the debug output. 

If we are unable to find a solution is it possible for me to add the ID as a parameter and then access that parameter within class-wc-api-customers.php as a temporary workaround?

**Comment by gtawebb** [comment]
@maxrice I confirm that I have again tried disabling all plugins apart from woocommerce and that I have switched to the twentytwelve theme. The problem is still exactly the same.

Do you have any suggestions for debugging the issue? Or any workarounds?

**Comment by maxrice** [comment]
@gtawebb can you send me an email with admin/FTP creds? max@skyverge.com

**Comment by maxrice** [comment]
for anyone reading this issue in the future, the issue turned out to be a line in the .htaccess that was overwriting the `id` GET variable.

**Comment by claudiosmweb** [comment]
@gtawebb As I said, this was not an issue in WooCommerce...
