### ISSUE TITLE
Bug w/ Taxes

### ISSUE THREAD

**Issue by digisavvy** [woothemes/woocommerce#8562]
Hey there, 
I've got an issue that I haven't been able to reproduce elsewhere, but I feel may be a bug and possible related here: https://github.com/woothemes/woocommerce/issues/8367

Issue summary:
Some products are not getting a sales tax applied, some products are. The products that do and don't get taxed do not appear to be configured differently.
All products are taxable, using the standard tax class. This applies to variations, too.

In reporting the issue to woo you can share the following:
Turned off all other plugins except for woocomm, issue still happened

Verified Tax Settings
Variations Tax is set, too: https://www.evernote.com/l/AALG3Tbk6mtIkKcJ42r5MBZ1kDHq_7vW2js
Tax Options: https://www.evernote.com/l/AAKVt5cRbcFLL7u51U44owCHJew_wcMOtQo
Tax Rates: https://www.evernote.com/l/AAI04K8CMjdN8rXfLtjy0iKYk-7ZvUumij4
Only some products get taxed: https://www.evernote.com/l/AAKE9SrufWhGoYegQgcYtbgQaG6rw1n5Q-c
DB Tables: https://www.evernote.com/l/AAKE9SrufWhGoYegQgcYtbgQaG6rw1n5Q-c

**Comment by mikejolley** [comment]
These are variable products. Have you looked at tax class and status at variation level?

**Comment by digisavvy** [comment]
Definitely did, sorry for not posting that screenshot. The product that does get taxed compared to the others that don't do not appear to be configured differently and each variation is using the appropriate tax class.

**Comment by mikejolley** [comment]
Screenshot all variations of the product that is not taxes, expanded so we can see settings and attributes used.

**Comment by digisavvy** [comment]
Thanks Mike. 
Just to be clear, all products are taxable and all are set to use the standard tax rate/class
https://www.evernote.com/l/AALMbn4H11ZMU58apiu3EljzsiHkgsnRlWI

**Comment by mikejolley** [comment]
Just 2?

**Comment by mikejolley** [comment]
Obviously I am not able to replicate this locally, and this is the only report of its kind. I think what will be happening is those variable products have a variation, below those 2 screenshot, matching without tax class set.

Can you check this, resave, and if not export your products or give one of us access to investigate further.

**Comment by digisavvy** [comment]
Hey Mike,
Sorry, I'm not trying to limit the info provided. I think in this case it might be better to take a closer look. Is there an address I can email site creds to? This is happening with several products.

**Comment by mikejolley** [comment]
mike.j@woothemes.com

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/f42fa85eabc52eac74d78944bdb19ea800aa5a3d
