### ISSUE TITLE
Out of stock items hidden but still counteed

### ISSUE THREAD

**Issue by uzyrnet** [woothemes/woocommerce#8567]
Hi, 
I have looked for the solutions everywhere before posting this. Basically in my categories out of stock products are being counted and if there is 10 items on page 1 only 3,4 are being displayed and count says 
displaying 1-10 items
I have already checked the option to hide. Have also recounted products and all the other stull in system status 
SCREENSHOT: http://screencast.com/t/Uxtfuhxp

**Comment by uzyrnet** [comment]
I have more than 13,000 products and almost half are out of stock.

**Comment by mikejolley** [comment]
That tyre search - custom?

**Comment by uzyrnet** [comment]
It is. I spoke to it's developers and they say it's not the search + I have tried a few other search plugins. Same with all of them.

**Comment by uzyrnet** [comment]
No filter applied here. Just a product category http://screencast.com/t/46vKVQpK

**Comment by mikejolley** [comment]
If the custom search is hooking in, it could still affect results counts, especially if they get cached. Switching themes, then cleaning cache, including the term counts cache in WooCommerce > System Status Tools, would help. See if it makes a difference.

**Comment by uzyrnet** [comment]
Just tried it Mike, It's till the same :( 
The thing is it does it even if I just open a product category. 
Try it mate
http://www.speedyswheels.co.uk/product-category/nt/

**Comment by mikejolley** [comment]
I can see it, but the exclusion of out of stock products is done via the queries. So you should always have 10 results on page 1.

I still think its theme or plugin related. I would need your data to actually check locally.

**Comment by uzyrnet** [comment]
Hi Mike, 
What data will you need? I can post it here

**Comment by mikejolley** [comment]
All product data ideally so I can import.

**Comment by uzyrnet** [comment]
Most of the product data can be uploaded from this file http://speedyswheels.co.uk/wp-content/uploads/wpallimport/files/EXP49330T.CSV

**Comment by mikejolley** [comment]
This is no good, it has no parent info. Tools > Export. I need the XML.

**Comment by uzyrnet** [comment]
http://www.speedyswheels.co.uk/wp-content/uploads/2015/07/speedyswheels.wordpress.2015-07-14.xml

**Comment by mikejolley** [comment]
@uzyrnet struggling to import this. Can I get access instead? Email mike.j@woothemes.com

**Comment by uzyrnet** [comment]
Hi Mike,
Done that. You should receive login info on your email.

**Comment by mikejolley** [comment]
Replying via email. Its not core.
