### ISSUE TITLE
Language updater bug?

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8568]
I'm not sure if this is a bug or not, but after manually updating WC to the 2.4 beta 1 i received the translation update notice.

I clicked on "Update Translation" and i got this

![](http://cld.wthms.co/195Dq/l5n1WqD1+)

The language is English US

**Comment by claudiosmweb** [comment]
@SiR-DanieL Maybe you tested before I had added the tag on Github:
https://github.com/woothemes/woocommerce-language-packs/releases

I tested and works fine, but this method need some improvements.

Please test for me:

- delete `woocommerce_language_pack_version` wp_option from your database
You can use `delete_option( 'woocommerce_language_pack_version' )`
If you use WP-CLI you can delete with: `wp option delete woocommerce_language_pack_version`

- Try update: `wp-admin/update-core.php?force-check=1` (maybe need to try twice for the update show)

I'm doing some improvements that will commit now, if you is able to test before and after that changes I thank you.

**Comment by SiR-DanieL** [comment]
@claudiosmweb i tested right now and i still have the same issue.

This time i tested with 2015 active, last test was with Storefront instead.

I deleted `woocommerce_language_pack_version` and then ran `wp-admin/update-core.php?force-check=1` multiple times.

It does not show any update, but the translation update notice shows yet.
If i click on "Update Translation" i get that error, if i click on "Force Update Translation" i get this error

`Failed to install/update the translation: Sorry but there is no translation available for your language =/`
