### ISSUE TITLE
Variable products problem

### ISSUE THREAD

**Issue by funkman733** [woothemes/woocommerce#8572]
Hi, I found some problem to set the variable protucts. So, if I have a T-Shirt with many size (s, m, l, xl, xxl) but all size t-shirt size have the same price, in single product page the single variation price was not displayed.

To solve the problem I have changed the includes/class-wc-product-variable.php code in line 480 from:
'price_html'            => $variation->get_price() === "" || $this->get_variation_price( 'min' ) !== $this->get_variation_price( 'max' ) ? '<span class="price">' . $variation->get_price_html() . '</span>' : '',

to:
'price_html'            => $variation->get_price() === "" || $this->get_variation_price( 'min' ) || $this->get_variation_price( 'max' ) ? '<span class="price">' . $variation->get_price_html() . '</span>' : '',

I don't know if it is correct but now it display the price in single product page.

Other question, if I want to display the variations list with a custom order in drop-down selector in single product page, the list are only displayed in alphabetical order.... what should I do to solve the problem?

**Comment by mikejolley** [comment]
Sort order is controlled by editing the product attribute (products > attributes).

As for the issue, this is intended - if all prices are the same, the price is shown under the title (same position as regular products). if this is not happening for you, its your theme.
