### ISSUE TITLE
Search tax rate

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8587]
Could be useful to have a search form in the tax rates table page.
When you have a lot of different tax rates it's hard to find the one you are looking for.

**Comment by mikejolley** [comment]
One @georgestephanis can maybe look into (sent invitation to a team so issues can be assigned your way)

**Comment by georgestephanis** [comment]
Sure.

Do we have any idea what the max number of tax rates any site could reasonably be expected to use would be?  More in the realm of double digits, or could it go into thousands?

**Comment by SiR-DanieL** [comment]
i've seen sites using hundreds of rates. Maybe wrongly because they could use wildcards characters, but some don't use them and declare each single tax rate.

**Comment by mikejolley** [comment]
100's spanning multiple pages. Depends where the user is - some users need to define rates per zip code.

**Comment by georgestephanis** [comment]
Okay, I just wanted to make sure we weren't up into the thousands or tens of thousands that would be problematic to store in js.  Thanks!

**Comment by georgestephanis** [comment]
I'm playing around with this in the `issue/8587` branch at the moment.  As I don't currently know what precisely we want it to actually be searchable on, I'm searching on all the fields, and as I don't want to mess up the ordering of the tax rates, I'm highlighting the results, rather than showing only the results.

It's also running purely in JS, as opposed to any server side php.  I still need to do some testing as to how pagination works with this (if at all) -- as well as possibly only showing the search form if the site has over 5 tax rates or the like.

https://github.com/woothemes/woocommerce/compare/issue/8587

**Comment by mikejolley** [comment]
@georgestephanis pagination is not JS based in this case. Uses WP pagination functions and PHP.

**Comment by georgestephanis** [comment]
My worry about adding search in PHP is that drag sorting on a search results page would get really messy really quick.

Would you have any objection to my switching the entire table over to a Backbone / Underscores templating system?

**Comment by mikejolley** [comment]
No issue with that at all :) Sorting may get message however you do it though? I mean, unless you're showing the entire result set (which we should not do). Or disable sort during search..

**Comment by georgestephanis** [comment]
I was thinking automatically change to the page with the first matched result, and let the forward/backward only paginate to pages that have found results.

**Comment by georgestephanis** [comment]
Much more progress on the branch in question:

https://github.com/woothemes/woocommerce/compare/issue/8587

Rendering works
Pagination works (granted, by default it paginates per 100 items, so few sites likely actually use pagination),
When form field values are changed in the dom, they automatically update in the Backbone model as well, which tracks what has changed, to make saving easier.
I've added a confirmation prompt if the user has made changes to the table but not saved them.

Things I still need to add in:
[ ] Newer ajax saving method that only pushes the changed fields.  Less worry about max number of post fields. (should be quick, nearly there)
[ ] Reordering (and how reordering should work cross-page?  That could be a tricky one. Not a regression, so may skip that aspect for now)
[ ] Changing over how adding new rows works with Backbone and mapping to the data structure. (should be quick)
[ ] Search.  (yes, the one thing that was actually needed) (also probably should be quick once everything else finishes.)

**Comment by georgestephanis** [comment]
Branch now needs testing, anyone willing or able, please let me know what you find!  Search works, and just disables sorting while the search is active.
