### ISSUE TITLE
Store Notice isn't optimal for screen readers

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#8588]
I have just enabled a _Store Notice_ for a client and noticed that the defalt rendering position of the text is at the end of the site, after everything.

**Would it be possible to have this at the very top of the page instead?** 
This is not for style purposes, but for screen readers and accessability.

If there's an important message in the _Store Notice_, it's the last thing screen readers will read, and they might not get that far down the page.

It would be quite frustrating not being able to hear a message that says `Site currently closed until X date` having listen to everything on the whole page.

**Comment by mikejolley** [comment]
This cannot be changed sadly - there is no reliable, cross-theme-compatible way to call a block of HTML under/after the HEAD section. wp_head hook is inside the header.

`
add_action( 'wp_footer', 'woocommerce_demo_store' );
`

If you unhook this and call it manually in your template you can do it for your users. cc @jameskoster
