### ISSUE TITLE
Download Permissions Performance

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8589]
This is another area where many records can slow the site to a halt (#8570).

- [ ] Paginate the download permissions, ajax saving etc like variations (@claudiosmweb)
- [ ] When generating permissions, do so in chunks or a separate request to prevent timeouts

**Comment by fabianhenzler** [comment]
Is there a possible workaround by assigning more memory to Wordpress/WooCommerce?

**Comment by mikejolley** [comment]
@fabianhenzler yes but it isn't helping your case due to the volume of downloads.

**Comment by fabianhenzler** [comment]
@mikejolley I know this question is awkward =) ...but when can we expect a hotfix for this?

**Comment by mikejolley** [comment]
Punting this to be part of a larger issue/goal. Will reference.
