### ISSUE TITLE
Paypal shouldn't be rounding to 2 decimals

### ISSUE THREAD

**Issue by rochow** [woothemes/woocommerce#8590]
Paypal rounds to 2 decimal places irrespective of the decimal setting in the admin.

This causes a problem for currencies such as the Japanese Yen which Paypal does not accept decimal points. The 2 is hard-coded throughout /includes/gateways/paypal/class-wc-gateway-paypal-request.php I couldn't see any hooks to change that (the price could be hooked earlier in the process but it'd still add .00 to the end).

Due to the decimal setting being 0 prices in the admin & shipping are all round numbers but tax can create decimals. Even though in the checkout & admin it shows 2604 for example, it'll pass 2604.67 to Paypal. I'm assuming in the database it's saving the full value then only stylising being rounded on the front-end? Seems like it really should be saving based on the current settings, if I processed payments for whole amounts, then changed my decimal settings, I'd have payments not matching the order totals? I didn't delve deep into this just fixed my issue quickly :)

**Comment by mikejolley** [comment]
Pretty sure PP api only supports 2dp

**Comment by rochow** [comment]
https://developer.paypal.com/docs/classic/api/currency_codes/
"Japanese Yen 
Note This currency does not support decimals. Passing a decimal amount will throw an error."

**Comment by claudiosmweb** [comment]
@rochow please test this branch (in a dev environment, of course) https://github.com/woothemes/woocommerce/tree/paypal-use-price_num_decimals-option

**Comment by rochow** [comment]
Maybe too slow as that links 404 now. If it uses no decimals should be sweet :)

**Comment by claudiosmweb** [comment]
@rochow Don't worry. I deleted the branch, but now is fixed.
Please test if you have sometime and let know if is working (test in a development environment, of course).

https://github.com/woothemes/woocommerce/archive/6cac5e0f4789be74dd0d2fc40ebcad25efddc444.zip

**Comment by rochow** [comment]
Thanks, Will let you know if any dramas.

Does the underlying logic need tweaking? Seems better if currency is whole to keep all figures in whole then only round right at the payment step? That way if the order is being saved as 25.95 for example Xero won't be using that figure while only Paypal is using 26 etc.
