### ISSUE TITLE
The Åland Islands have no states, but both state and city are required during checkout

### ISSUE THREAD

**Issue by marcusforsberg** [woothemes/woocommerce#8594]
Since Åland isn't in itself a country, but rather a "state" of Finland, it's impossible to provide both a city and a state when choosing Åland as a country.

Currently, state and city are both mandatory during checkout, so you'd have to first select Åland as your country and then type in Åland again as your state in order to complete the checkout - kind of annoying. :)

This could be solved either by removing the state field when choosing Åland (it never makes sense to have it there for Åland so just making it non-mandatory doesn't help) or by completely removing Åland as a country in Woocommerce since it isn't actually a country (although those of us who live here do appreciate it when Åland is available as a country on websites!).

**Comment by mikejolley** [comment]
What would you say is 'normal' - remove it or leave it in?

**Comment by marcusforsberg** [comment]
Normal is hard to define, I guess. It's not an actual country so technically it shouldn't be available as one, but being able to choose it from the dropdown is way easier for the user than choosing Finland and typing in Åland as a state, so I'd personally find it ideal if Åland Islands stays as a country after all, but without the "state" field (i.e state field hidden completely for Åland, if possible).

**Comment by claudiosmweb** [comment]
I did some research and seem to be very complicated.

@marcusforsberg Hide the Status field is very simple, we can do it like we did with Afghanistan.
But from what I read, it makes more sense to become a province of Finland (I'm sorry if I misunderstood):
https://en.wikipedia.org/wiki/Provinces_of_Finland#Provinces_of_Finland_as_at_abolition

But it also seems that we have no field for the province when selected Finland...

![screenshot from 2015-07-17 16 17 05](https://cloud.githubusercontent.com/assets/1264099/8755189/67e3820c-2c9f-11e5-87cc-ad256fc1947f.png)

How do you usually do?

**Comment by greguly** [comment]
"The provinces were eventually abolished at the end of 2009."
https://en.wikipedia.org/wiki/Provinces_of_Finland

**Comment by claudiosmweb** [comment]
@greguly Yeah and I just saw that Amazon uses it as a Country and State is not a required field.

**Comment by greguly** [comment]
So either make Åland like Finland, with no State selection or remove Åland from countries list. :-)

**Comment by claudiosmweb** [comment]
@greguly I'm doing the first option :p

**Comment by claudiosmweb** [comment]
@marcusforsberg please tell me if this works fine for you:

![screenshot from 2015-07-17 16 27 57](https://cloud.githubusercontent.com/assets/1264099/8755388/f55816d8-2ca0-11e5-9d75-d7a65a207c2b.png)

**Comment by marcusforsberg** [comment]
Looks perfect! Thank you :)
