### ISSUE TITLE
"Related Products" heading text not filterable

### ISSUE THREAD

**Issue by slushman** [woothemes/woocommerce#8596]
Almost every string in WooCommerce is filterable, but it appears this one was overlooked. While one could use the gettext filter, per Patrick Rauland's suggestion, it seems wiser to just include a filter for the text itself.

**Comment by mikejolley** [comment]
I disagree. It's filterable through gettext  and via template overrides. Why is a 3rd method needed? Why would it be changed anyway?

**Comment by slushman** [comment]
I can think of several reasons for changing it:
* Maybe "Related Products" doesn't match the phrasing or tone on the site: "More stuff to buy from us", "Check out our other items", "Related items you might be interested in...", etc
* Maybe the phrase should dynamically include the product type: "Related T-Shirts", "Related Ironman Clothing", "Related Auto Parts", etc
* Maybe do something even more dynamic there, like products in one category would say "Related Products", but products in this category would say "Spare parts".

While something static could be done in the template, dynamic content is easier to generate using a filter and function. While it can be filtered using gettext, Pippin pointed out gettext could lead to site-crashing problems (if its misused, abused, or just done poorly). So to avoid that altogether and be more consistent with the rest of WooCommerce, add a filter on this text. This wouldn't be a third method, it would the primary method, just like filtering the "Add to Cart" button text, or any other text string in WooCommerce.

**Comment by claudiosmweb** [comment]
Better do this with custom template.

**Comment by slushman** [comment]
Gotcha. Thanks for the feedback, guys.
