### ISSUE TITLE
Cannot override title markup for Product Archive

### ISSUE THREAD

**Issue by JodiWarren** [woothemes/woocommerce#8601]
The Product Archive template, `content-product.php`, hardcodes in the product title like so:

[`<h3><?php the_title(); ?></h3>`](https://github.com/woothemes/woocommerce/blob/master/templates/content-product.php#L61)

I find it's typically best to stick to the core templates for ease of upgrades, but this one little restriction has caused me to override `content-product.php` numerous times just to add a class or change it to an h2 or whatnot.

I think there are two sensible and low-friction solutions here. 

A *good* solution would be a function tied to a new `woocommerce_shop_loop_item_title` action.

The *easiest* solution would be a filtered title call, like `<?php echo apply_filters( 'woocommerce_shop_loop_item_title', '<h3>'. the_title() . '</h3>' ); ?>`

For both ways, the default output wouldn't change, but it would keep the principle of modular changes.

There's also a third solution, which might be the best long term. That would be to drop the concept of before and after title actions entirely, and have the whole body of the product enqueued as a set of actions fired by `woocommerce_shop_loop_item`. That would allow for much easier manipulation of the structure of items. However, it would crucially not be backwards compatible, so I don't think it's the best answer at this time.

**Comment by claudiosmweb** [comment]
Yes, you can.
You can override this template on your theme, by creating a new `content-product.php` inside your theme:

http://docs.woothemes.com/document/template-structure/

**Comment by JodiWarren** [comment]
@claudiosan I do believe this would be a genuine enhancement. As I mentioned in my second paragraph, I've overridden `content-product.php` in my themes several times, and always specifically for this reason. I don't understand why this needs to be so firmly hard-coded. The solutions that I suggested would produce exactly the same output, they would just also allow theme developers or plugins to override that part of the default template without entirely replacing it. 

Considering how much of the templates are constructed with action hooks, I believe it's both entirely in the spirit and letter of the WooCommerce templates to make the title also editable with a hook.

**Comment by JodiWarren** [comment]
I'm happy to whip it up myself with a pull request if that'd be helpful.

**Comment by JodiWarren** [comment]
I've placed it on the ideas board for now: http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/8917936-hooked-title-in-the-content-product-php-template
