### ISSUE TITLE
Additional template actions related to displaying variations.

### ISSUE THREAD

**Issue by manifestcreative** [woothemes/woocommerce#8602]
I have the following usage scenario. When a customer selects a specific variation attribute, they need to be able to specify certain details regarding that attribute. In this case if they select a candy flavor of "Custom Assortment" they then need to select which specific flavors they wish to include. This option is closely related to the attribute in question, so should also be displayed in very close proximity to that variation.

![screen shot 2015-07-17 at 11 55 56 am](https://cloud.githubusercontent.com/assets/235868/8753823/070362b8-2c7c-11e5-8c72-55e74260b2a9.png)

The current template file (single-product/add-to-cart/variable.php) offers several filters for modifying the values that are displayed within each select field, as well as the 'woocommerce_before_add_to_cart' action that allows a developer to add additional configuration options.

However, if one wishes to add content closer to each select field (within each table.variations td element) their only option is to modify the template file. I propose adding 2 additional actions:
* 'woocommerce_before_variation_select_field'
* 'woocommerce_after_variation_select_field'

Thoughts?

**Comment by claudiosmweb** [comment]
It seems to me this very specific problem, so the best would be to override the template.
I'm opening it to vote on your trello roadmap: https://trello.com/c/l8MTjdiA/76-additional-template-actions-for-attributes-select-fields
If interest from other users, so you can add it.

**Comment by manifestcreative** [comment]
You're right that it is a fairly specific use case. However, I think that it would be a useful action; one that isn't necessarily supported elsewhere by WooCommerce core.

I'll pop over to the Trello roadmap.
