### ISSUE TITLE
Products pagination count doesn't include stock quantity

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#8605]
When a product has *stock quantity* set to *zero* and *stock status* set to *in stock*, then product is taken into account in the products page pagination:

![](http://cld.wthms.co/Li4S/f8DmrtoM+)

That produces this kind of situation, site displaying 3 products with a wrong pagination count:

![](http://cld.wthms.co/cOJv/Q73Svzn1+)

**Comment by WPprodigy** [comment]
Hmm, I wonder if this would resolve the issue: http://cld.wthms.co/1iSKD/FXXYZ89v

If so, maybe when a product hits the 0 / in stock point, that action should be run to recount.

**Comment by mikejolley** [comment]
The problem is the stock status. That's used in queries. If stock status if not changing automatically, stock may be being set or imported wrongly.

**Comment by WPprodigy** [comment]
In what use case would you even need to have "in stock" set when the stock is 0? Perhaps something could auto-trigger the "in stock" status to change upon saving the page?

**Comment by mikejolley** [comment]
We do this. It sounds like in this case the stock was set by something else or manual.
