### ISSUE TITLE
How to apply coupons for a new order via WooCommerce REST API v2 

### ISSUE THREAD

**Issue by kashyapkamaliya** [woothemes/woocommerce#8608]
{
 "order": {
   "payment_details": {
     "method_id": "bacs",
     "method_title": "Direct Bank Transfer",
     "paid": true
   },
   "billing_address": {
     "first_name": "John",
     "last_name": "Doe",
     "address_1": "969 Market",
     "address_2": "",
     "city": "San Francisco",
     "state": "CA",
     "postcode": "94103",
     "country": "US",
     "email": "john.doe@example.com",
     "phone": "(555) 555-5555"
   },
   "shipping_address": {
     "first_name": "John",
     "last_name": "Doe",
     "address_1": "969 Market",
     "address_2": "",
     "city": "San Francisco",
     "state": "CA",
     "postcode": "94103",
     "country": "US"
   },
   "customer_id": 226,
   "line_items": [
     {
       "product_id": 251,
       "quantity": 2
     }
   ],
   "shipping_lines": [
     {
       "method_id":"flat rate",
       "method_title": "Flat Rate",
       "total": 10
     }
   ],
    "coupon_lines": [
     {
      
       "code": "loveharvey",
      
       "amount": "26"
     }
   ]
 }
}
response geting:
{
order: {
id: 1563
order_number: "HPO801332"
created_at: "2015-07-18T12:54:06Z"
updated_at: "2015-07-18T12:54:06Z"
completed_at: "2015-07-18T12:54:06Z"
status: "processing"
currency: "USD"
total: "62.00"
subtotal: "52.00"
total_line_items_quantity: 2
total_tax: "0.00"
total_shipping: "10.00"
cart_tax: "0.00"
shipping_tax: "0.00"
total_discount: "00.00"
shipping_methods: "Flat Rate"
payment_details: {
method_id: "bacs"
method_title: "Direct Bank Transfer"
paid: true
}-
billing_address: {
first_name: "John"
last_name: "Doe"
company: ""
address_1: "969 Market"
address_2: ""
city: "San Francisco"
state: "CA"
postcode: "94103"
country: "US"
email: "john.doe@example.com"
phone: "(555) 555-5555"
}-
shipping_address: {
first_name: "John"
last_name: "Doe"
company: ""
address_1: "969 Market"
address_2: ""
city: "San Francisco"
state: "CA"
postcode: "94103"
country: "US"
}-
note: ""
customer_ip: "103.7.81.188"
customer_user_agent: "Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"
customer_id: 226
view_order_url: "https://www.harveyprince.com/my-account/view-order/1563"
line_items: [1]
0:  {
id: 3374
subtotal: "52.00"
subtotal_tax: "0.00"
total: "52.00"
total_tax: "0.00"
price: "26.00"
quantity: 2
tax_class: null
name: "Petaly Noir"
product_id: 251
sku: "Petaly Noir 8.8ml Tall Spray"
meta: [0]
}-
-
shipping_lines: [1]
0:  {
id: 3375
method_id: "flat rate"
method_title: "Flat Rate"
total: "10.00"
}-
-
tax_lines: [0]
fee_lines: [0]
coupon_lines: [1]
0:  {
id: 3376
code: "loveharvey"
amount: "26.00"
}-
-
customer: {
id: 226
created_at: "2015-07-17T11:56:27Z"
email: "dddd@dd.com"
first_name: "aaaa"
last_name: "aa"
username: "aaaa"
role: "subscriber"
last_order_id: "1563"
last_order_date: "2015-07-18T12:54:06Z"
orders_count: 1
total_spent: "62.00"
avatar_url: "https://secure.gravatar.com/avatar/?s=96"
billing_address: {
first_name: "John"
last_name: "Doe"
company: ""
address_1: "969 Market"
address_2: ""
city: "San Francisco"
state: "CA"
postcode: "94103"
country: "US"
email: "john.doe@example.com"
phone: "(555) 555-5555"
}-
shipping_address: {
first_name: "John"
last_name: "Doe"
company: ""
address_1: "969 Market"
address_2: ""
city: "San Francisco"
state: "CA"
postcode: "94103"
country: "US"
}-
}-
}-
}

total_discount always geting 0.0 .
thank you in advance.
plz help .........:)

**Comment by claudiosmweb** [comment]
Duplicated of #8609
