### ISSUE TITLE
Failed payment email

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8617]
Should we handle the failed payment email?
Some payment gateways send it, but some others don't.

I'd like to have something to inform customers about this, maybe disabled by default so the admin can choose to have it or not based on what payment gateway they will use on the site.

**Comment by claudiosmweb** [comment]
Failed status should appear to the customer when it happens (when the customer is completing the order). For example with credit card... When is denied the order need to set to failed so the customer can try again.

I believe that out of this case should be handled by the payment gateway.

**Comment by SiR-DanieL** [comment]
Not sure about that @claudiosmweb i still think we should handle the email.

When you pay with PayPal you may have a delay (even of some hours). Also other shops send you an email personally, even if the gateway sends one too.

Like Amazon, or Moleskine store. They send you an email after few minutes if your payment fails.

**Comment by claudiosmweb** [comment]
@SiR-DanieL yeah, we can do it, but maybe better leave for 2.5.

**Comment by mikejolley** [comment]
@georgestephanis

**Comment by georgestephanis** [comment]
Not having looked into it at all yet, I'm thinking it would need a core action that fires at the bare minimum, but it feels at first blush that it would probably fit best in each payment processor module to determine whether or not to send an email when it fails.  Either an opt-in or opt-out (I'm thinking opt-out, better to notify too often than not enough), and then WC Core actually sends the email.

**Comment by maxrice** [comment]
for reference, our payment gateway framework [explicitly marks the order as `failed`](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/class-sv-wc-payment-gateway.php#L1883-L1913) when payment has failed. Definitely agree that WC core should probably handle sending the email when the order status is changed to that.

**Comment by georgestephanis** [comment]
I'm just thinking that -- as noted above -- some gateways will send the emails on their own, for some it may be preferable for WooCommerce core to be able to note the failure, but know that the email is already being handled from the processor, so it shouldn't send a duplicate.

**Comment by SiR-DanieL** [comment]
@georgestephanis i think the email should be disabled by default, so if the customer does not have a gateway that sends one, he can enable it and let WooCommerce handle the failed order email.

**Comment by Kenshino** [comment]
Why wouldn't the Shop send their own version even if the Gateway sends it?

Eg. Paying by Paypal gets you an email for payment from PayPal and also one from WooCommerce.

**Comment by SiR-DanieL** [comment]
You could do that. You can enable/disable the email, so...

**Comment by georgestephanis** [comment]
Alrighty, so plan is to add functionality to send payment failed emails, disabled by default, but enable by an option in the admin.  Groovy.

**Comment by SiR-DanieL** [comment]
Yes @georgestephanis, if you check the other email settings the workflow is already there, Just need to change the option names ;)

**Comment by nishitlangaliya** [comment]
@SiR-DanieL, Here what I understood is from above conversion. I have attached the screenshot. would you please see when you get a chance? please let me know your thoughts for the same. 

![8617](https://cloud.githubusercontent.com/assets/11435772/10535762/28a929c4-7403-11e5-91f7-c28b6a1cfba2.png)

**Comment by SiR-DanieL** [comment]
Yes @nishitlangaliya correct

**Comment by nishitlangaliya** [comment]
@SiR-DanieL , Thanks for reply . Once I am done with the code will do PR for review :)

**Comment by mikejolley** [comment]
When a payment fails the user is usually notified via the UI. This email notification would (and will be) much more useful for the admin who can follow up with the user if needed. https://woo.uservoice.com/admin/forums/133476-woocommerce/suggestions/4109367-failed-order-alerts Otherwise you'll spam the user with emails even if they are in the process of retrying which could be misleading.

On top of this we need to re-think that order email screen because its becoming unmanageable.
