### ISSUE TITLE
Checkout screen "whites out" when there is an error

### ISSUE THREAD

**Issue by trader4300** [woothemes/woocommerce#8618]
During checkout, if I encounter an error such as an invalid credit card date, I get the error message above the entry fields that says there is an error, but it does not specify WHAT error. I would expect the software to know that the invalid date in the date field caused the error and would say so in the error message so the user could easily go to that field and correct it. Instead, what happens is that all the user fields are "white out" and cannot be entered. There is no button present to clear the error and no indication of what to do to clear this error message. I have tried a couple things, all with undesirable affects in order to get back to my checkout window. So, with no indication of what to do to clear this error, I tried refreshing the page. This then wipes out my user info and I need to log in again. But my cart is still valid. The second thing I tried when presented with this error message is to try clicking on the CART. This then takes me to the cart, however my user information is wiped clean and I again need to log in. Obviously, this is not a desirable action you want the user to go thru if they encounter an error during checkout. This business of the checkout screen turning WHITE and freezing up where one cannot go in and modify fields bothers me. It does not appear as a normal operating mode, rather appears as a fault in the coding. I hope I have explained this correctly.
Yes, I have all the current updates and upgrades. Everything else appears normal. What do you folks suggest might be wrong? Have any of you experienced this before?

**Comment by claudiosmweb** [comment]
From what you are saying it seems you have problem with the plugin using this payment gateway or with your theme.

**Comment by trader4300** [comment]
I have narrowed it down to the paypal gateway. If that is enabled along 
with any other gateways, the checkout fault checking
process is broken. Not sure who to report this to.
John

**Comment by trader4300** [comment]
Why is this closed.

**Comment by claudiosmweb** [comment]
@trader4300 because works perfect and you have some issue on your theme or plugins.

**Comment by trader4300** [comment]
It is your standard paypal gateway and your standard check gateway. If the paypal gateway is enabled, the fault checking on the checkout screen messes up. I have verified this simply by not checking the "read and accept terms" checkbox, the checkout screen will freeze up if the paypal gateway is enabled along with any of your other standard gateways. Please help determine why this happens.

**Comment by claudiosmweb** [comment]
> During checkout, if I encounter an error such as an invalid credit card date

Standard paypal gateway don't have any credit card field in WooCommerce.

Please check what I say!

**Comment by trader4300** [comment]
Let me clarify. If I enable the standard paypal gateway, either all by itself or with another gateway, the checkout screen freezes up. I have given you admin rights. Please help figure this out. Thank-you

**Comment by claudiosmweb** [comment]
@trader4300 I've helped. But it seems that you just ignored what I said.

**Comment by mikejolley** [comment]
PayPal standard has no credit card number/date fields. Check the actual gateway you are using or disable it.

**Comment by trader4300** [comment]
The credit card number has nothing to do with the issue. Dont know where your getting this from. Claudiosmweb, why are you being so rude. I thought I explained this pretty clear. If the paypal gateway is enabled, the checkout screen does not process the errors correctly. OK, with that being said, it seems the problem is with the paypal gateway. For your information, so perhaps this discussion can help others, I found the email address that was entered into the Receiver Email field to be wrong. When I cleared this field out, the Checkout screen processed all the errors correctly. So an incorrect setting in the paypal gateway can effect the checkout screen in this way, and still allow paypal payments to successfully process payments if there are no errors. That is sort of a wierd process, but that is how it works. Hope this explanation helps somebody down the road, as I spent several hours finally figuring it  out. 
Mark as closed please.

**Comment by claudiosmweb** [comment]
![screenshot from 2015-07-20 13 57 33](https://cloud.githubusercontent.com/assets/1264099/8781766/6b7874fa-2ee7-11e5-86d3-3d14e2868fe1.png)
