### ISSUE TITLE
DB Error in Keys/Apps list

### ISSUE THREAD

**Issue by gedex** [woothemes/woocommerce#8619]
## Steps to reproduce

* Go to `/wp-admin/admin.php?page=wc-settings&tab=api&section=keys`
* You should get db error message:
   <img width="1244" alt="screen shot 2015-07-20 at 11 58 22 pm" src="https://cloud.githubusercontent.com/assets/78313/8781800/7cc19eb8-2f3b-11e5-9550-fd4a4a57bb77.png">

@claudiosmweb Since the addition of `truncated_key` col is introduced recently, per https://github.com/woothemes/woocommerce/commit/eebd47ecf8953acf29788eac7393abaca8f1efb3, I think it's expected to get this error message when working on `master`. Feel free to close this if user wouldn't get the error after upgrading.

**Comment by claudiosmweb** [comment]
@gedex yeah, for beta versions we will have this problem.
But who upgrade to 2.4 will not have this problem.
