### ISSUE TITLE
API authentication problems over https

### ISSUE THREAD

**Issue by AlwaysQuads** [woothemes/woocommerce#8622]
Hello,

Ive been reading all previous issues and tried numerous 'fixes' from all over. I cant get this to work and its driving me crazy.

We have 2 servers and 1 is working as intended the other is not. The difference between the two is that server A's webshop has SSL and is running on nginx, server B's webshop has no SSL and is running on apache.

Ive let my system admin check out the possible nginx issue but he said there is nothing wrong there. When i try https://www.thephonestore.be/wc-api/v2/orders?consumer_key=keyhere&consumer_secret=secrethere it gives me an error about the consumer key, but i triple checked everything is correct. The curl command with the user and pass after -u is giving the same error..

These are my woocommerce system info :
 
### WordPress Environment ###

Home URL: https://www.thephonestore.be
Site URL: https://www.thephonestore.be
WC Version: 2.3.13
WC Database Version: 2.3.13
Log Directory Writable: /usr/home/thephonestore.be/web/wp-content/uploads/wc-logs/
WP Version: 4.2.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
Language: nl_NL

### Server Environment ###

Server Info: nginx/1.8.0
PHP Version: 5.5.26
PHP Post Max Size: 50 MB
PHP Time Limit: -1
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.24
Max Upload Size: 50 MB
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Remote Post: 
Remote Get: 

### Server Locale ###

decimal_point: .
thousands_sep: niet beschikbaar
mon_decimal_point: niet beschikbaar
mon_thousands_sep: niet beschikbaar

### Active Plugins (39) ###

WooCommerce (nl): door Pronamic – 1.1.6
WooCommerce Back In Stock Notifier: door Fantastic Plugins – 6.5
Contact Form 7: door Takayuki Miyoshi – 4.2.1
IDEUM - DHL - Bestellingen in CSV: door Bob Deckx – 1.0
IDEUM - DPD - Bestellingen in CSV: door Bob Deckx – 1.0
IDEUM export naar custom CSV: door Bob Deckx – 1.0
WPBakery Visual Composer: door Michael M - WPBakery.com – 4.6
MailChimp for WordPress Lite: door ibericode – 2.3.7
Multisafepay: door Multisafepay – 1.0.6
Multisafepay Banktransfer: door Multisafepay – 2.1.0
Multisafepay Giropay: door Multisafepay – 2.1.0
Multisafepay iDEAL: door Multisafepay – 2.1.0
Multisafepay Maestro: door Multisafepay – 2.1.0
Multisafepay MisterCash: door Multisafepay – 2.1.0
Multisafepay Sofort: door Multisafepay – 2.1.0
Multisafepay VISA: door Multisafepay – 2.1.0
Options Framework: door Devin Price – 1.8.4
WooCommerce Product Filter: door Mihajlovic Nenad – 4.0.6
Regenerate Thumbnails: door Viper007Bond – 2.2.4
Revolution Slider: door ThemePunch – 4.6.92
WPML Multilingual CMS: door OnTheGoSystems – 3.1.9.7
Ultimate Tweaker: door Amino-Studio  – 1.3.5
Woocommerce Advanced Bulk Edit: door George Iron – 3.2.5
WooCommerce Custom Order Status & Actions: door Actuality Extensions – 1.6.9
WooCommerce MultiStep Checkout: door Mubashir Iqbal – 2.2.4
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 1.5.15
WooCommerce Predictive Search PRO: door A3 Revolution – 2.4.2
WooCommerce Table Rate Shipping: door Mike Jolley – 2.9.0
WooCommerce TM Extra Product Options: door themecomplete – 3.0.11
WooCommerce Widget Product Slider: door A3 Revolution – 1.2.0
WooCommerce: door WooThemes – 2.3.13
WP All Import Pro: door Soflyy – 4.1.1
WP-Mail-SMTP: door Callum Macdonald – 0.9.5
WPML Media: door OnTheGoSystems – 2.1.9
WPML String Translation: door OnTheGoSystems – 2.1.2
WPML Translation Management: door OnTheGoSystems – 1.9.11
YITH WooCommerce Compare: door Yithemes – 2.0.0
YITH WooCommerce Wishlist: door Yithemes – 2.0.8
YITH WooCommerce Zoom Magnifier: door Yithemes – 1.2.4

### Settings ###

API Enabled: 
Taxes Enabled: 
Shipping Enabled: 
Force SSL: 
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Winkel basis: #21018 - /alle-producten/
Winkelwagen: #5 - /cart/
Afrekenen: #6 - /checkout/
Mijn account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Bigshop
Version: 1.8 Updated 4-Jun-2015
Author URL: http://bit.ly/opalwp
Child Theme: ✕ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: 

### Templates ###

Overrides: bigshop/woocommerce/archive-product.php
bigshop/woocommerce/cart/cart-empty.php
bigshop/woocommerce/cart/cart-shipping.php
bigshop/woocommerce/cart/cart-totals.php
bigshop/woocommerce/cart/cart.php
bigshop/woocommerce/cart/mini-cart.php
bigshop/woocommerce/cart/shipping-calculator.php
bigshop/woocommerce/checkout/cart-errors.php
bigshop/woocommerce/checkout/form-billing.php
bigshop/woocommerce/checkout/form-checkout.php
bigshop/woocommerce/checkout/form-coupon.php
bigshop/woocommerce/checkout/form-login.php
bigshop/woocommerce/checkout/form-pay.php
bigshop/woocommerce/checkout/form-shipping.php
bigshop/woocommerce/checkout/payment-method.php
bigshop/woocommerce/checkout/payment.php
bigshop/woocommerce/checkout/review-order.php
bigshop/woocommerce/checkout/thankyou.php
bigshop/woocommerce/content-product.php
bigshop/woocommerce/content-product_cat.php
bigshop/woocommerce/content-single-product.php
bigshop/woocommerce/content-widget-product.php
bigshop/woocommerce/emails/admin-cancelled-order.php
bigshop/woocommerce/emails/admin-new-order.php
bigshop/woocommerce/emails/customer-completed-order.php
bigshop/woocommerce/emails/customer-invoice.php
bigshop/woocommerce/emails/customer-new-account.php
bigshop/woocommerce/emails/customer-note.php
bigshop/woocommerce/emails/customer-processing-order.php
bigshop/woocommerce/emails/customer-reset-password.php
bigshop/woocommerce/emails/email-addresses.php
bigshop/woocommerce/emails/email-footer.php
bigshop/woocommerce/emails/email-header.php
bigshop/woocommerce/emails/email-order-items.php
bigshop/woocommerce/emails/email-styles.php
bigshop/woocommerce/emails/plain/admin-cancelled-order.php
bigshop/woocommerce/emails/plain/admin-new-order.php
bigshop/woocommerce/emails/plain/customer-completed-order.php
bigshop/woocommerce/emails/plain/customer-invoice.php
bigshop/woocommerce/emails/plain/customer-new-account.php
bigshop/woocommerce/emails/plain/customer-note.php
bigshop/woocommerce/emails/plain/customer-processing-order.php
bigshop/woocommerce/emails/plain/customer-reset-password.php
bigshop/woocommerce/emails/plain/email-addresses.php
bigshop/woocommerce/emails/plain/email-order-items.php
bigshop/woocommerce/global/breadcrumb.php
bigshop/woocommerce/global/form-login.php
bigshop/woocommerce/global/wrapper-end.php
bigshop/woocommerce/global/wrapper-start.php
bigshop/woocommerce/loop/add-to-cart.php
bigshop/woocommerce/loop/loop-end.php
bigshop/woocommerce/loop/loop-start.php
bigshop/woocommerce/loop/orderby.php
bigshop/woocommerce/loop/pagination.php
bigshop/woocommerce/loop/price.php
bigshop/woocommerce/loop/result-count.php
bigshop/woocommerce/loop/sale-flash.php
bigshop/woocommerce/myaccount/form-add-payment-method.php
bigshop/woocommerce/myaccount/form-login.php
bigshop/woocommerce/myaccount/my-account.php
bigshop/woocommerce/notices/error.php
bigshop/woocommerce/notices/notice.php
bigshop/woocommerce/notices/success.php
bigshop/woocommerce/order/order-again.php
bigshop/woocommerce/product-searchform.php
bigshop/woocommerce/single-product/add-to-cart/external.php
bigshop/woocommerce/single-product/add-to-cart/grouped.php
bigshop/woocommerce/single-product/add-to-cart/simple.php
bigshop/woocommerce/single-product/add-to-cart/variable.php
bigshop/woocommerce/single-product/meta.php
bigshop/woocommerce/single-product/price.php
bigshop/woocommerce/single-product/product-attributes.php
bigshop/woocommerce/single-product/product-thumbnails.php
bigshop/woocommerce/single-product/rating.php
bigshop/woocommerce/single-product/related.php
bigshop/woocommerce/single-product/review.php
bigshop/woocommerce/single-product/sale-flash.php
bigshop/woocommerce/single-product/share.php
bigshop/woocommerce/single-product/short-description.php
bigshop/woocommerce/single-product/tabs/tabs.php
bigshop/woocommerce/single-product/title.php
bigshop/woocommerce/single-product/up-sells.php
bigshop/woocommerce/single-product-reviews.php
bigshop/woocommerce/single-product.php

**Comment by claudiosmweb** [comment]
Use basic authentication

**Comment by claudiosmweb** [comment]
Note:

![screenshot from 2015-07-20 18 27 02](https://cloud.githubusercontent.com/assets/1264099/8787891/10d3a418-2f0d-11e5-9cf9-dfbece6b6323.png)

It's not your case, so you need to use Basic Auth ;)

**Comment by AlwaysQuads** [comment]
It works when i curl on /wc-api/v2/ but it gives the error when i try /wc-api/v2/orders

![screenshot from 2015-07-20 23 32 12](https://cloud.githubusercontent.com/assets/13424668/8787979/98c5c250-2f37-11e5-9245-d944ec3f5c57.png)

**Comment by AlwaysQuads** [comment]
My syntax was wrong, this message can be closed. Thanks for the support
