### ISSUE TITLE
Password fields being over cleaned

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#8627]
Install Stamps.com and enter

```
Mp$%312958
```

as your password

it gets truncated to

```
Mp$2958
```

obviously %31 is being stripped out because it's a HTML character

**Comment by ChromeOrange** [comment]
Same issue can be seen in any extension with a password field e.g. UPS

**Comment by claudiosmweb** [comment]
To be honest this can be fixed in the plugin.

The Payment Gateway, Shipping Method for Integration can change this behavior by override this method:

```php
	/**
	 * Validate Password Field.
	 *
	 * Make sure the data is escaped correctly, etc.
	 *
	 * @param  mixed $key
	 * @since  1.0.0
	 * @return string
	 */
	public function validate_password_field( $key ) {

		$text  = $this->get_option( $key );
		$field = $this->get_field_key( $key );

		if ( isset( $_POST[ $field ] ) ) {
			$text = wc_clean( stripslashes( $_POST[ $field ] ) );
		}

		return $text;
	}
```

For Stamps will be better use like:

```php
	public function validate_password_field( $key ) {

		$text  = $this->get_option( $key );
		$field = $this->get_field_key( $key );

		if ( isset( $_POST[ $field ] ) ) {
			$text = trim( stripslashes( $_POST[ $field ] ) );
		}

		return $text;
	}
```


In WooCommerce core is better to keep as we do today, for a change so can cause unexpected problems for the extensions already work today.

**Comment by ChromeOrange** [comment]
@claudiosmweb are you volunteering to help fix all of the WooThemes extensions?

**Comment by claudiosmweb** [comment]
@ChromeOrange just tell me what extensions need to be fixed.

@mikejolley do you think is a good idea we change this in WooCommerce?

**Comment by ChromeOrange** [comment]
oh, BTW, text fields are fine, it just seems to affect password fields

![](https://dl.dropboxusercontent.com/s/iojtqs3bgt5rb9i/2015-07-21%20at%2019.57.png?dl=0)

**Comment by claudiosmweb** [comment]
@ChromeOrange for text we use: https://github.com/woothemes/woocommerce/blob/753a22734f5cee934d6a3a9cd6aa81c736261dc1/includes/abstracts/abstract-wc-settings-api.php#L769-L787

**Comment by ChromeOrange** [comment]
I fully appreciate that we have to make sure that data is safe but we can't literally remove characters from passwords. I'm just sitting here thinking about all those tickets we've had where the customer is adamant they are using the right password or API key or anything else that has to be added to a type="password" field

**Comment by maxrice** [comment]
Agreed, the password field should not strip valid ASCII characters.

**Comment by claudiosmweb** [comment]
@ChromeOrange ok, I'll change it.

**Comment by ChromeOrange** [comment]
Awesome, thanks @claudiosmweb

**Comment by claudiosmweb** [comment]
@ChromeOrange not thanks me yet xD
I talked to Mike and I'll change the way it is sanitized, if have any problems, it simply fails to save xD
