### ISSUE TITLE
Wc order date admin 

### ISSUE THREAD

**Issue by worldsdream** [woothemes/woocommerce#8628]
WC order date admin should be taken from the default wordpress date. If not, we should be able to edit it. In europe it's d m y. In usa y m d i guess? Thanks

**Comment by worldsdream** [comment]
I tried this: http://www.remicorson.com/customize-woocommerce-admin-orders-date-format/

It does NOT work. Maybe it used to work on older wc or wordpress versions.

**Comment by michaeltieso** [comment]
Posts and Pages on WordPress work in the same fashion. You can change the output seen on the front-end by going to Settings > General > Date Format. Might be a good idea to add your idea [to our ideas board](http://ideas.woothemes.com/forums/133476-woocommerce).

**Comment by worldsdream** [comment]
@michaeltieso I do know that you can change that in wordpress. But WC should take those settings from WP as default or put an option to change it for the users. I dont mind if there is a code to put. But I dont know it and I can't find it.

**Comment by worldsdream** [comment]
I dont think that this is an idea? This should be standard in WC. Dont know why nobody talked about this earlier. I guess the most dont use the admin new order panel that much? Well in my country it's default dd/mm/yyyy.

**Comment by claudiosmweb** [comment]
WordPress standards... WordPress does the same for posts, see:

![screenshot from 2015-07-22 12 09 56](https://cloud.githubusercontent.com/assets/1264099/8828893/b94421d2-306a-11e5-993b-4ed454ed7f0a.png)

If you want use a custom format, you can use this:

```php
function woo_custom_post_date_column_time( $h_time, $post ) {
	return get_the_time( __( 'd/m/Y', 'woocommerce' ), $post );
}

add_filter( 'post_date_column_time' , 'woo_custom_post_date_column_time', 10, 2 );
```

**Comment by worldsdream** [comment]
@claudiosmweb Yes this code does change the admin columns. I have that code. But i am looking for this screen: Admin order. 
![screen](https://cloud.githubusercontent.com/assets/12443285/8833326/2c187472-30ae-11e5-827a-ac75496655f9.jpg)

Do you have the code for that one?

**Comment by claudiosmweb** [comment]
@worldsdream this need to be in this format.

**Comment by LadyPhoenix66** [comment]
I'm looking for the same solution too - I want to be able to change the order date from 2015-07-30 to 30-7-2015 - is there really no way to do it?  It's really confusing for my client who is taking order for her floristry business.

**Comment by carasmo** [comment]
This doesn't work in 3.x. Thanks!
```
function woo_custom_post_date_column_time( $h_time, $post ) {
    return get_the_time( __( 'd/m/Y', 'woocommerce' ), $post );
}

add_filter( 'post_date_column_time' , 'woo_custom_post_date_column_time', 10, 2 );
```

**Comment by mensmaximus** [comment]
@carasmo the filter hook 'post_date_column_time' has been removed. Unfortunately it is not mentioned in the deprecated filters section at https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes.

**Comment by carasmo** [comment]
Thanks for the update. If anyone looks on this page, this works:

```
/* Filter Shop Order Post Type Date Format */
function prefix_woo_post_order_date_format_filter( $j, $req_format, $i, $gmt ){
	if ( 'shop_order' == get_post_type() ) {
		$j = @date( 'd/m/Y', $i );
	}
	return $j;
}
add_filter( 'date_i18n', 'prefix_woo_post_order_date_format_filter', 10, 4 );

```

**Comment by mensmaximus** [comment]
This is a different filter hook. Regarding 'post_date_column_time' Please see https://github.com/woocommerce/woocommerce/issues/14215

**Comment by mikejolley** [comment]
Also not compatible since the code above uses $post as a WP_Post. 3.0 needs to use the CRUD for future compatibility.

**Comment by carasmo** [comment]
Okay. I'll remove.
