### ISSUE TITLE
[WC 2.4 Beta 3] PHP Warning: Wrong parameter count for round()

### ISSUE THREAD

**Issue by maxrice** [woothemes/woocommerce#8629]
`PHP Warning:  Wrong parameter count for round() in /wp-content/plugins/woocommerce/includes/class-wc-cart.php on line 2159`

You'll see this error in PHP 5.2, as `$mode` for [`round()`](http://php.net/manual/en/function.round.php) was introduced in PHP 5.3. Not sure what the ideal fix is.

**Comment by claudiosmweb** [comment]
Well, this use `WC_DISCOUNT_ROUNDING_MODE` equal to `2` (same as `PHP_ROUND_HALF_DOWN` ) so this is equal to `floor()` :p

I will create a function to it and avoid problems with PHP 5.2.

**Comment by mikejolley** [comment]
@claudiosmweb don't use floor. I think it will upset our tax system. Use PHP_ROUND_HALF_DOWN/2 if supported, or leave it to default round().

**Comment by claudiosmweb** [comment]
@mikejolley see my next commit

**Comment by mikejolley** [comment]
@claudiosmweb I'd feel better leaving PHP to handle the advanced rounding modes tbh. I think we should support 5.3+ for this feature, and for 5.2 only support regular round up via round().

**Comment by claudiosmweb** [comment]
Right :)
