### ISSUE TITLE
[WC 2.4 Beta 3] PHP Notice:  Undefined variable: tax_display

### ISSUE THREAD

**Issue by maxrice** [woothemes/woocommerce#8630]
`PHP Notice:  Undefined variable: tax_display in /wp-content/plugins/woocommerce/includes/class-wc-order.php on line 28`

Looks like it can be switched to `$this->tax_display_cart`

**Comment by claudiosmweb** [comment]
Seems that @mikejolley fixed this in https://github.com/woothemes/woocommerce/commit/7285ce74e60e6a669aa07d01c619d85d2bc6a2cb#diff-d40ff36ba2766206bbf9818c26167af8
