### ISSUE TITLE
Setting order date for new order is ignored

### ISSUE THREAD

**Issue by barrykooij** [woothemes/woocommerce#8633]
Setting the order date for a new order (via backend) isn't working, the date is always _now_. setting a date for an existing order works.

**Comment by sjeden** [comment]
+1

**Comment by claudiosmweb** [comment]
Hey @barrykooij works fine (at least for 2.4/master that I tested): https://cloudup.com/cE7e9r8nyLM

**Comment by barrykooij** [comment]
@claudiosmweb this must have been fixed in 2.4/master then, sorry about that! Happy it's fixed :)

**Comment by claudiosmweb** [comment]
@barrykooij No worry, but I'll not try test with 2.3.13 because we are very close 2.4 release :p

**Comment by lubosj** [comment]
I have exactly the same issue on WooCommerce 2.5.5

**Comment by ramon-villain** [comment]
I'm having the same issue with the 3.0 version. Anyone else is facing this issue?
