### ISSUE TITLE
Implement grouped variable products

### ISSUE THREAD

**Issue by pawelkmpt** [woothemes/woocommerce#8634]
As I already found - it's not possible to group variable products. I was looking for some workaround, checked different types of products in following article http://docs.woothemes.com/document/chained-products-vs-product-bundles-vs-force-sells-vs-grouped-products/ and I didn't find any solution.

**Use case**
We have 2 types of products:
* Hotels - description, attributes, photos etc. are constant. The only difference is price, so variable product is perfect solution for that.
* Campaigns - campaign contains many hotel offers grouped together by theme or place (eg. Sunny Travel, hotels in Greece, etc.), so grouped product is the thing I'm looking for.

The problem I'm facing is that hotels have different prices for different campaigns, so I'd like to link particular hotel variable with campaign, what basically means linking variable product with grouped product. And it's not possible. Do you plan to implement such a functionality? Or maybe you have some tip how to achieve that in different way? Any workaround?

**Comment by lkraav** [comment]
I'd be interested in knowing what implementation complexities have stopped this from being part of core functionality already.

**Comment by claudiosmweb** [comment]
Moved for our roadmap for voting: https://trello.com/c/olHZ3qcp/78-grouped-variable-products

**Comment by lkraav** [comment]
ITMW, Product Bundles plugin does what we need. Totally worth every cent. (y)
