### ISSUE TITLE
i18n for russian language creates russian url which can't be resolved

### ISSUE THREAD

**Issue by rstormsf** [woothemes/woocommerce#8635]
when I switched to Russian language in wordpress settings,
woocommerce automatically translates all url from 'shop' to 'товар'
:-(
http://plitka74.tk/home/

how do I make things working? 
Is this Divi theme problem or woo problem?

**Comment by claudiosmweb** [comment]
This need to be changed on Transifex:
https://www.transifex.com/projects/p/woocommerce/

You guys need to find the best way to translate or not this slugs.
And you can change this by the WooCommerce settings too!

**Comment by rstormsf** [comment]
so WooCommerce can't work in Russian? Or maybe something needs to be done in order to allow Cyrillic urls

**Comment by rstormsf** [comment]
there is just a problem in link building in html code somewhere `href` that uses Russian language instead of native

**Comment by rstormsf** [comment]
Ohhh - never mind
it works

**Comment by claudiosmweb** [comment]
@rstormsf I accept your apology.
