### ISSUE TITLE
Creating order via WC API does not grant access to downloads

### ISSUE THREAD

**Issue by nvartolomei** [woothemes/woocommerce#8638]
Hello,

I'm trying to create an order through WC API, status is completed and this does not trigger `wc_downloadable_product_permissions`. So clients do not have access to downloads. 

For now I'm creating an order with status = processing and then via another API call change it to completed, then `woocommerce_order_status_completed` will be triggered and access to downloadable files will be granted.

:moneybag:

**Comment by claudiosmweb** [comment]
So everything is works as it should :p
If you want to mark the order as paid should not change the status of it and instead use:

```js
  "order": {
    "payment_details": {
      "method_id": "bacs",
      "method_title": "Direct Bank Transfer",
      "paid": true
    },
...
```

This will trigger the `$order->payment_complete()`: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-orders.php#L457-L460

Here you can see how `$order->payment_complete()` works: https://github.com/woothemes/woocommerce/blob/7285ce74e60e6a669aa07d01c619d85d2bc6a2cb/includes/abstracts/abstract-wc-order.php#L2283-L2357

In your docs we do the same showing how create a paid order: http://woothemes.github.io/woocommerce-rest-api-docs/#create-an-order

**Comment by claudiosmweb** [comment]
Check too http://woothemes.github.io/woocommerce-rest-api-docs/#orders-properties

**Comment by nvartolomei** [comment]
Are you sure I need to add payment details? Because I don't want to, I just
created order with status completed, what you say looks to me like a
workaround.

Also creating a order from wp admin wth status completed without any
payment details grants access to downloads.

Shouldn't these behave the same and have exactly the same result?

On Saturday, July 25, 2015, Claudio Sanches <notifications@github.com>
wrote:

> Closed #8638 <https://github.com/woothemes/woocommerce/issues/8638>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/8638#event-364953122>.
>


-- 
Nicolae Vartolomei, http://nvartolomei.com/

**Comment by claudiosmweb** [comment]
@nvartolomei nop, if you want to complete the payment, you need to set it!

**Comment by nvartolomei** [comment]
@claudiosmweb then why it allows me to create a completed order without providing payment fields? Put a constraint and reply with Bad request.

This is still an issue to me, but you have to decide in which component and make behaviour the same.

As I said:
> Creating a order from wp admin wth status completed without any
payment details grants access to downloads.

**Comment by claudiosmweb** [comment]
@nvartolomei If you want to complete the payment you need to set it as paid!
