### ISSUE TITLE
ajax calls not working ????

### ISSUE THREAD

**Issue by InoPlugs** [woothemes/woocommerce#8639]
I just downloaded the latest WC version from Github for testing it with our
plugins (Additional Fees and E-Mail Attachment).

I also upgraded WP to 4.2.2 and tried standard WP Theme 2014 and 2015 and only WC
activated.

But the ajax calls do not work. When using AddToCart button on the shop page and
when going to the checkout page with the payment methods I only have a spinning
wheel.

**Comment by claudiosmweb** [comment]
It's working.
Can you give me more details?
Tested with WP_DEBUG?
Have you seen the "spinning wheel", but tried to check the browser console what happened and what returned the ajax call?
What is the status returned by ajax call?
Have tried to flush your rewrite rules?

**Comment by InoPlugs** [comment]
Thanks, probably a problem of the permalink. Changing the pernalink structure solved the problem
