### ISSUE TITLE
"On hold" is not translated

### ISSUE THREAD

**Issue by Almaz** [woothemes/woocommerce#8642]
On the Orders page (wp-admin/edit.php?post_type=shop_order) "On hold" link of filter is not translated (if I use non-english interface of my WordPress).
You have to create one order with "On hold" status to see the link.

**Comment by Almaz** [comment]
I think it is necessary to update the .pot file on Transifex.com.

**Comment by claudiosmweb** [comment]
@Almaz the strings on Transifex is now for version 2.4 which will be released in the coming days.
