### ISSUE TITLE
Tax Status Not Cascading to Variable Products when Editing on Parent

### ISSUE THREAD

**Issue by pdcable** [woothemes/woocommerce#8643]
Whatever the current Tax Status (not tax class) of the Original Product Parent is when creating a variable product, is what the variable product Tax Status is set to.

Changing the Tax Status on the parent product does not cascade to current existing Variations.

There is no option to change Tax Status on the variation, only Tax Class.

The problem with this is if I want to make a currently un-taxable variation taxable, or vice versa.  There is no way to do that.   I am assuming the expected behavior is that any changes to the Tax Status on the Product, should cascade to the variations on update.

**Comment by pdcable** [comment]
Assuming you have already created thousands of variations, and need all the items and all variations to be taxable, there is an easy SQL fix.

update wp_postmeta set meta_value = 'taxable' WHERE meta_key = '_tax_status'

**Comment by mikejolley** [comment]
This is actually not true. Variations don't save '_tax_status' meta data. Its inherited.

If you do an import and save it to variation level for any reason, it will break.

2.4 has a workaround.

**Comment by pdcable** [comment]
Hrm..we used All Import Pro to pull in the data, it is a fact that they did write _tax_status for all variations.  Evidently the 'breaking" was that it ignored the parent status.  Thanks for clearing that up.

**Comment by mikejolley** [comment]
@pdcable if that is how the import plugin works you may want to report this. _tax_status should not be set on variations.
