### ISSUE TITLE
Error: Invalid Signature

### ISSUE THREAD

**Issue by ascottmccauley** [woothemes/woocommerce#8644]
I am currently trying to set this up on siteground's shared hosting (without ssl), but keep receiving the following error:

```Error: Invalid Signature - provided signature does not match [woocommerce_api_authentication_error] 401 stdClass Object ( [headers] => Array ( [0] => Accept: application/json [1] => Content-Type: application/json [2] => User-Agent: WooCommerce API Client-PHP/2.0.1 ) [method] => GET [url] => http://staging2.marathon-co.com/wc-api/v2/products?oauth_consumer_key=ck_3b0775f0717331fa3a4e11faa5660c6e&oauth_timestamp=1437667663&oauth_nonce=59b468ce5c3978e1dd02b590cee293d4f48f8301&oauth_signature_method=HMAC-SHA256&oauth_signature=Xsf1YY38HgS0uNgJXGKEAZ4BRrwVGC%2BHUYXfesLSfgc%3D [params] => Array ( [oauth_consumer_key] => ck_3b0775f0717331fa3a4e11faa5660c6e [oauth_timestamp] => 1437667663 [oauth_nonce] => 59b468ce5c3978e1dd02b590cee293d4f48f8301 [oauth_signature_method] => HMAC-SHA256 [oauth_signature] => Xsf1YY38HgS0uNgJXGKEAZ4BRrwVGC+HUYXfesLSfgc= ) [data] => Array ( ) [body] => [duration] => 0.47847 ) stdClass Object ( [body] => {"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]} [code] => 401 [headers] => Array ( [Server] => nginx/1.7.9 [Date] => Thu, 23 Jul 2015 16:07:44 GMT [Content-Type] => application/json; charset=UTF-8 [Content-Length] => 126 [Connection] => keep-alive [X-Cache-Enabled] => True [Set-Cookie] => Array ( [0] => Array ( [0] => wpSGCacheBypass=0; expires=Thu, 23-Jul-2015 15:07:44 GMT; Max-Age=-3600; path=/ [1] => new_user=0; expires=Sat, 31-Oct-2015 16:07:44 GMT; Max-Age=8640000; path=/ ) [1] => cached=1436903226; expires=Sat, 31-Oct-2015 16:07:44 GMT; Max-Age=8640000; path=/ ) [Vary] => Accept-Encoding,User-Agent [Host-Header] => 192fc2e7e50945beb8231a492d6a8024 ) )```

I have made sure that the consumer_key and consumer_secret are accurate. I have made sure that the API is enabled, and accessible at `http://staging2.marathon-co.com/wc-api/v2/`
I have tried changing the site from multi-site to single, and changed the permalinks to 'post name'.
I have no troubles setting everything up on my local machine with vvv, and I'm tired of banging my head on the desk, so I'm looking for any troubleshooting help here.

**Comment by maxrice** [comment]
Signature mismatches are hard to troubleshoot -- you can try echo'ing the [`$string_to_sign`](https://github.com/woothemes/woocommerce/blob/2.3.13/includes/api/class-wc-api-authentication.php#L239) and then `die;` immediately afterwards. My guess is that you'll see some extra parameters being added to that string that shouldn't be there :smile_cat:

**Comment by claudiosmweb** [comment]
Please follow this guide for authentication: http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

You can also use one of our wrappers: http://woothemes.github.io/woocommerce-rest-api-docs/#official-libraries
