### ISSUE TITLE
Oauth Timestamp Timezone

### ISSUE THREAD

**Issue by GeorgeMac** [woothemes/woocommerce#8645]
We're having OAuth issues authenticating against woocommerce endpoints. Looking at the implementation you are using, it would suggest that UTC+0 isn't inforced:

https://github.com/woothemes/woocommerce/blob/bb0811643c0e9d684de6aa69f46eedba6acf7a36/includes/api/v1/class-wc-api-authentication.php#L329

However, it may be defined somewhere else in the codebase. We're using UTC+0 timezone for all our requests. However, immediately after a request to one woocommerce instance we get timestamp invalid error. However, this isn't the case for other instances we communicate with.

I might be jumping to the conclusions, but it would appear that for one of our woocommerce clients, they might be hosting under a different timezone. 

So really I am just trying to clarify whether you enforce UTC+0 in your codebase or whether I am barking up the wrong tree. 

Cheers!

**Comment by maxrice** [comment]
`time()` is UTC -- believe it or not though, I've seen some servers where `time()` was incorrect because the server time was wrong which is almost certainly the case here :)

**Comment by claudiosmweb** [comment]
WooCommerce not force any time zone. This can only be related to your server.

**Comment by GeorgeMac** [comment]
Thats kind of what I expected. So you have to know the timezone of any woocommerce API you're connecting too. In order to auth properly. Thats a shame.

**Comment by maxrice** [comment]
@GeorgeMac in order to do authentication you don't need to know the timezone -- simply use UTC for the timestamp. If you're seeing timestamp errors from a particular site, it's because the server has it's internal date set incorrectly.

**Comment by ikennaokpala** [comment]
Hi there,
I suggest that your (woo-commerce) API provides an endpoint for timezone.

This way the requesting call can adjust to the timezone of the responding server.

**Comment by maxrice** [comment]
@ikennaokpala you do not need the timezone for authentication, it is UTC. The API index does return the timezone if you'd like to convert the times provided in API responses to the site's local time :smile_cat:
