### ISSUE TITLE
Changing the structure of the review-order.php table makes the subtotals show up multiple times in the checkout page

### ISSUE THREAD

**Issue by ammist** [woothemes/woocommerce#8648]
I wanted to format the checkout page a little bit differently, so I moved the "cart-totals" rows out of the tfoot and into a separate subtable.  Here's a link to the template that I modified in my theme:

https://github.com/woothemes/woocommerce/blob/master/templates/checkout/review-order.php#L49

I just wrapped the contents of the tfoot referenced above into another table so I could change the width of the columns.

This looks great the first time, but, if I change the shipping information, the order review table dims, and another instance of the subtotal, tax, shipping and totals appear below.  

I really love how the tax & totals update after I change the shipping address or method, but I don't love having multiples of those.  I'm using WooCommerce version 2.3.13.

**Comment by claudiosmweb** [comment]
This happens because of the ajax request, if you will customize this, should use our triggers to remove the elements called by ajax.
Not a problem in WooCommerce but your custom code that needs improvement.

**Comment by ammist** [comment]
Yes, I know this happens because of the ajax request, though i haven't figured out yet where the triggers are to remove the duplication.  

I don't think that it's a good idea to put the shipping options in the same (narrow) column that's supposed to include the line item totals.

**Comment by ammist** [comment]
@claudiosmweb I know that this happens because of AJAX, but I haven't figured out how to remove the duplicate elements.  Ajax is updating the totals correctly, but ALSO making a second copy of the element, so this is really unexpected behavior.

Can you be more specific about which "triggers" to update?

**Comment by claudiosmweb** [comment]
@ammist here is not a support channel...

But check your checkout.js:

https://github.com/woothemes/woocommerce/blob/release/2.3/assets/js/frontend/checkout.js

We have:

- `init_checkout`
- `update_checkout`
- `updated_checkout`
- `checkout_error`

**Comment by ammist** [comment]
@claudiosmweb Thank for your help - I know this is not the support channel, this is the "I found a bug channel".

The bug is that doing "update_checkout" duplicates elements on the page, instead of just changing their value.  I can definitely fix that, but I'd have to change checkout.js (bad), or make my own copy (annoying later), or write some script that goes back and cleans up the duplicate elements.

I'm going to experiment more w/ changing the shipping information in some of the other templates to see if I can figure out exactly what's happening and give you more detail in a different bug report.

**Comment by claudiosmweb** [comment]
@ammist custom code !== bug.
