### ISSUE TITLE
Using !important in the primary CSS file

### ISSUE THREAD

**Issue by bolderelements** [woothemes/woocommerce#8649]
Is there a reason why we cannot modify certain colors in the stylesheet? I've tried multiple things including inline CSS and adding a stylesheet before this one also using the !important tag, but still no change in Chrome. Why are we being blocked from editing colors that appear in parts of the website, or in my case, the cart page?

**Comment by claudiosmweb** [comment]
You should not be using CSS correctly, because you can change anything by CSS.

**Comment by bolderelements** [comment]
Well generally yes but CSS invented the !important tag for a reason. It prevents anyone from overwriting the value.

woocommerce.css:
a.remove { color: red!important; }

My client detests red but since version 2.3, my CSS code stopped working on this and another area, both of which the !important clauses were added. I'm just trying to figure out if there is a purpose to this. If I modify the woocommerce.css to remove the !important it works just fine:

a.remove { color: red; }
(Now I can change it to whatever color I please, wherever I want to)

**Comment by claudiosmweb** [comment]
Simply just call your stylesheet after our and you will not have any problem.

**Comment by Kenshino** [comment]
You need a little more training with CSS.

You just need a more specific selector ;/

Or use !important too in your child theme. But !important is bad :(

**Comment by claudiosmweb** [comment]
cc: @jameskoster

**Comment by mikejolley** [comment]
Make a pull request if you can solve it gracefully.

**Comment by jameskoster** [comment]
@bolderelements as others have said, you can still overrule a style that has an `!important` declaration.

As for the reason why we use `!important` here: Red is generally the color associated with buttons of this nature. Using `!important` rules out any theme styles from being inherited and the color changing.
