### ISSUE TITLE
Item fulfillment or shipment 

### ISSUE THREAD

**Issue by shahshyam** [woothemes/woocommerce#8650]
Hi Dev,
Regarding item fulfillment  or shipment, current version of api documentation does not contains information about item shipment  such as how to add item tracking number, shipment item and carrier service . For example 
https://docs.shopify.com/api/fulfillment

**Comment by claudiosmweb** [comment]
@shahshyam Is not within the scope of WooCommerce and will depend on the plugin that you use to fulfillment or shipment.
