### ISSUE TITLE
GetList Filter by ID 

### ISSUE THREAD

**Issue by shahshyam** [woothemes/woocommerce#8651]
Hi Dev
Regarding Filter issue, Current version of Woocommerce api does not support filter by id in product, order, customer and other while View List Of Products, orders , customer and other. It must be support less than , equal to and greater that operation.

I hope you will implement it

**Comment by claudiosmweb** [comment]
Moved for our roadmap for voting: https://trello.com/c/IiSicWuq/79-rest-api-filters-by-ids
