### ISSUE TITLE
Create Product category in woocommerce api

### ISSUE THREAD

**Issue by shahshyam** [woothemes/woocommerce#8653]
Hi Dev Team

On study of Woocommerce API documentation, It does not allow to create category via api. could you please add  support for creating Product category in Woocommerce ?

Thanks
Shyams

**Comment by claudiosmweb** [comment]
@shahshyam It will be supported in 2.4.

**Comment by shahshyam** [comment]
Hi  Dev, 
Regarding this issue , Woocommerce API v3 does not contains Category end point for Create category. Could you please review your documentations ?

Thanks 
Shyams
