### ISSUE TITLE
Dashboard product list filter count inconsistencies

### ISSUE THREAD

**Issue by jconroy** [woothemes/woocommerce#8654]
Filtering by product type on the dashboard product page doesn't count draft items in the dropdown count but shows them in the list of products whilst the default count on the top right hand side of the list/table includes them http://cl.ly/image/1f473g2D1N1I and http://cl.ly/image/3b2j3v0f1X0Q. 

Similarly if you only have draft items of a product type they don’t appear as filterable in the dropdown until one is published - but when you do all the drafts are visible when filtering.

I've been able to replicate this in both 2.3.13 and master (2.4)

**Comment by claudiosmweb** [comment]
@jconroy I removed the count, did not make much sense to have it, especially if you were filtering by category too, the values were not going to work.
In addition to not count the products in categories filter.
