### ISSUE TITLE
Email Template Border Colours

### ISSUE THREAD

**Issue by jconroy** [woothemes/woocommerce#8655]
I've been testing out 2.4/master branch today and noticed that there appears to be some darker borders appearing in some 2.4 emails templates such as the 'Thank you for your order / Order Being Processed' template.

For comparison this is using the default templates (i'm using storefront to test) displayed in gmail/google for work:
* 2.4 http://cl.ly/image/2t2U0r1D1j0S vs
* 2.3.13 http://cl.ly/image/3g0W0S2V0m14

I've haven't had a chance to look into it too thoroughly yet but it could be related to recent changes like https://github.com/woothemes/woocommerce/commit/7dbdbdaf13bfa902528f0a6e50e01d9b57aa3704

**Comment by claudiosmweb** [comment]
@jameskoster can you check it?

**Comment by mehulkaklotar** [comment]
Gmail is scrapping the td styles here.

**Comment by jameskoster** [comment]
@mikejolley with no `font-family` declaration many table cells were rendering in Times in Outlook. FYI :p

**Comment by mikejolley** [comment]
@jameskoster I'm sure outlook users love Times new roman.
