### ISSUE TITLE
Order By problem in Product Categories - Thumbs

### ISSUE THREAD

**Issue by markusfergus** [woothemes/woocommerce#8659]
In the "Product Categories - Thumbs" element, the "Menu Order" option for the "Order By" drop-down is not working correctly. It should be ordering the categories in the order that I've dragged and dropped them on the Product > Categories page, but they seem to be ordering alphabetically instead.

Thanks,
Mark

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/tem63y2wdzodyzd/2015-07-27%20at%2012.14.png?dl=0

https://dl.dropboxusercontent.com/s/9byucon47vaehxk/2015-07-27%20at%2012.14%20%281%29.png?dl=0

Seems to be working.

**Comment by markusfergus** [comment]
Hi Mike,
It's not working for me. As you can see by the attached images, I've got the Categories in a specific order, the Store: Edit page is set to "Menu Order", but the store front is being sorted alphabetically.
I changed the theme to Twenty Fifteen and it made no difference, so appears to be a Woocommerce problem. 
Can you please check this out? Let me know what you need me to do, if anything.
Thanks,
Mark
![categories_page](https://cloud.githubusercontent.com/assets/11214762/8907963/5803a010-3447-11e5-8254-b39943ff9fd3.gif)
![store_edit_page](https://cloud.githubusercontent.com/assets/11214762/8907966/584fc2ce-3447-11e5-8c2e-77c0e8ded7fd.gif)
![store_front](https://cloud.githubusercontent.com/assets/11214762/8907965/5839458a-3447-11e5-9b3a-1f9ded6c344e.jpg)

**Comment by mikejolley** [comment]
This is not generated by WC

**Comment by claudiosmweb** [comment]
@markusfergus See your second image. We don't have any "Product Categories - Thumbs Settings". It seems that you are using another plugin for it and then you are reporting the error in the wrong place.
