### ISSUE TITLE
Double quotes are not escaped in json send to webhook by WooCommerce

### ISSUE THREAD

**Issue by snijbonenmolen** [woothemes/woocommerce#8661]
I'm currently implementing a webhook for a client, for testing purposes I pasted a random text into the note field containing double quotes. When my webhook failed I took a better look at the json wooCommerce send to the hook and it contained the complete note as I pasted it, the double quotes were appearantly not escaped, which led to a faulty piece of json.

I cannot work around this in my own webhook's code, since that would also mess up the json even further, so the escaping will probably have to happen on the side of woocommerce.

**Comment by claudiosmweb** [comment]
@snijbonenmolen I just tested and the output is: `"note":"Testing this \"note\""`.
We use `json_encode()` so double quotes will be escaped.
