### ISSUE TITLE
Custom Taxonomy and Category Count

### ISSUE THREAD

**Issue by chmchm** [woothemes/woocommerce#8664]
I have products set up in WooCommerce, with a custom taxonomy. The taxonomy is status, the possible tax items are  - available, discontinued and call-for-price. I want to filter out the discontinued items set up in status. But I want to keep them in the structure of the other regular categories. So. I have a pre_get_posts filter that is working. I have the shop set up so that I see both categories and subcategories.  BUT, when the subcategory count displays on the archive page, it shows there are products in the subcategory but then you click thru and there are no products available.  It's as if the count is incorrect. I have done the 
As you can see, I need to show the discontinued products on their own pages.
What am I missing?

The code for pre_get_posts is this:

function custom_pre_get_posts_query( $q ) {
     if( ! is_admin() && $q->is_main_query() && !is_tax('status', 'discontinued')  ) {
    
     $tax_obj = $q->get_queried_object();

         $tax_query = array(
            'taxonomy' => 'status',
            'field' => 'slug',
            'terms' => array( 'discontinued' ), // Don't display products in the category on the shop page
            'operator' => 'NOT IN'
        );
  $q->tax_query->queries[] = $tax_query;
   $q->query_vars['tax_query'] = $q->tax_query->queries;

  } // return $q;
}

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
