### ISSUE TITLE
sorry！About Generate or acquire oauth_signature ！

### ISSUE THREAD

**Issue by githubzhaoqian** [woothemes/woocommerce#8667]
sorry！About Generate or acquire oauth_signature ！
You can help me with how to obtain request oauth_signature?
linux server !
Actually I am a green hand!

oauth_signature=zkghadmin518 is wrong! Or I don't know what is this!

/wc-api/v2/orders
?oauth_consumer_key=ck_6dc9fda9246ffa53d3fa8fc56215a95b&oauth_timestamp=1438072913
&oauth_nonce=cs_83448441fb8817d446f4ae749fbab84c
&oauth_signature=zkghadmin518
&oauth_signature_method=HMAC-SHA1
&consumer_key=ck_6dc9fda9246ffa53d3fa8fc56215a95b
&consumer_secret=cs_83448441fb8817d446f4ae749fbab84c

**Comment by mikejolley** [comment]
Please review the [API documentation](http://woothemes.github.io/woocommerce-rest-api-docs/#authentication). Github is for bug reports, not general support sorry.
