### ISSUE TITLE
Woocommerce – Hide out of stock items that appears using “Layered nav: filter

### ISSUE THREAD

**Issue by velicuicristian** [woothemes/woocommerce#8669]
Hello,

As the topic says there are problems with filtering products .

If out of stock it still looks in filters.

I tried this variant http://www.stimart.net/web/woocommerce-hide-out-of-stock-items-that-appears-using-layered-nav-filter-widget-solution-3/

I did the last update woocommerce and no results .

I tried and filter for filtering provided by woocommerce plugin and WooCommerce Ajax Navigation YITH .
For additional verifications will leave and website address . http://goo.gl/ASFJSR

I look forward technical solutions

thanks

https://wordpress.org/plugins/woocommerce/

**Comment by mikejolley** [comment]
Tested:

2 filters 2 products https://dl.dropboxusercontent.com/s/tpe5fppumi8osm3/2015-07-28%20at%2011.47.png?dl=0

Marked 1 out of stock: https://dl.dropboxusercontent.com/s/prdry7p36u9jvzi/2015-07-28%20at%2011.48.png?dl=0

Refreshed page: https://dl.dropboxusercontent.com/s/7rkebzaq2xfocip/2015-07-28%20at%2011.48%20%281%29.png?dl=0

So this appears to be working. Your issue may be related to https://github.com/woothemes/woocommerce/issues/8605 which should be synced more reliably in 2.4
