### ISSUE TITLE
Variations tab active even if there is no attributes defined.

### ISSUE THREAD

**Issue by allysonsouza** [woothemes/woocommerce#8673]
When you create some attributes to be used as variations, and then you remove all these attributes and save, the variations tab remain activated allowing the creation of new variations, even if there is no attributes defined.

### Causing the error
1. Create an attribute checking "used for variations".
2. Save the attributes.
3. Go to the variations tab and see that your variations have been created.
4. Go to the attributes tab and remove the previously created attribute.
5. Create a new attribute (don't check "used for variations" field).
6. Save the attributes.
7. Go to the variations tab and see that it is still active.

**Comment by claudiosmweb** [comment]
I just test this against our dev-master and seems that we don't have this problem anymore.
Then we can consider fixed for WooCommerce 2.4.

**Comment by allysonsouza** [comment]
:+1:
