### ISSUE TITLE
Zip field during checkout won't accept NZ postcode beginning with '0'

### ISSUE THREAD

**Issue by jjbbrr** [woothemes/woocommerce#8674]
My New Zealand postcode (aka zip) is 0626 and normally includes the 0 at the beginning whenever I use it. However Woocommerce just now didn't accept it unless I removed the initial zero, it just gave the error message saying the zip is a required field. When I removed the zero and just put the postcode as 626 it went through fine. This wouldn't be obvious to users who are used to including the opening '0' so it needs to accept it with that in place.

**Comment by mikejolley** [comment]
You must have some extra validation or plugins in place because NZ postcodes are not validated in core.

https://dl.dropboxusercontent.com/s/gcoq6os1up567ae/2015-07-29%20at%2010.17.png?dl=0

https://dl.dropboxusercontent.com/s/3hvm70koopuauat/2015-07-29%20at%2010.18.png?dl=0

^ no error
