### ISSUE TITLE
Displaying items in stock only

### ISSUE THREAD

**Issue by jeffpa** [woothemes/woocommerce#8676]
Hi

If I set the catalogue to show all items in stock, from the customer perpective on the first page they get 21 items and the page displays "showing items 1-21 of 190". Let's say the SKU for the last item on the first page shown is A111.

If I then change woocommerce options to show only those items I have in stock: the same customer page as detailed above now shows only 10 items but the page still displays "showing 1-21 of 185" . And the last item on the page is again A111. (As an aside, I don't know why the nubers have altered from 190 to 185 it's nothing I can work out)

It seems setting the option to only show the items in stock simply hides the items out of stock and doesn't update the counts on the displayed page. 

Is this by design, because it's very confusing for the customers.

Thanks

Jeff

**Comment by mikejolley** [comment]
Search first please. Closed same issue last week https://github.com/woothemes/woocommerce/search?q=stock+pagination&type=Issues&utf8=%E2%9C%93

**Comment by jeffpa** [comment]
Sorry MIke I did do a search. Think pagination must have thrown me.
Thanks
Jeff
