### ISSUE TITLE
Price for variations is now showing as Free! Help me fix this.

### ISSUE THREAD

**Issue by jonathanober** [woothemes/woocommerce#8677]
I just switched to the beta since I was having so much issues with variations...which the beta fixed. But now my prices for products I set up with the previous version are showing up as FREE! Any ideas what happened that all the sudden the prices which are there in the variations are shown as free? This site - http://abacussurfaces.com.s136952.gridserver.com/order-online/ is in development and won't launch for a few months, but I thought I would get a jump on the newest version of Woo anyways.

Thanks for any and all help.

**Comment by bekarice** [comment]
FWIW I also saw this happen in a test site where I imported dummy data -- can replicate on a fresh install of WC 2.4 with dummy data imported via WP Importer (see "Ship your idea" hoodie specifically). Did a cursory look through but I wasn't able to pinpoint anything, figured initially it might be an issue with the dummy data itself. A bit above my level :smile_cat: 

The price in the catalog displays as "Free!", but then when the variation is selected, the correct price is used for the cart / order.

@jonathanober when you view the product page and select the variation, is the right price displayed / used when you add it to the cart?

**Comment by jonathanober** [comment]
@bekarice when I go here - http://abacussurfaces.com.s136952.gridserver.com/product/regupol-aktiv-core-series/ - and select anyone of the variations the price does not change. You can see in my product page backend that the variation price is listed https://cloudup.com/cjXtw1BSMkV so I am not sure...and really super confused...why it's showing as FREE on the front end.

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.

**Comment by jonathanober** [comment]
I was asking for help with WooCommerce core issues. Did you read my post? I updated to the beta 2.4 release and the prices for all of my items said FREE. They went from what they should have been to FREE.  I have since spent the day just deleting all my variations and working through putting all of them back in, which seemed to have resolve the issue. My guess is the database when the update happened did away with any variations in the pricing.

**Comment by claudiosmweb** [comment]
>Price for variations is now showing as Free! Help me fix this

**Comment by claudiosmweb** [comment]
I stopped in the title, if you are reporting a bug, then you need to edit it all, because nothing looks like a bug and just a support request!

**Comment by jonathanober** [comment]
I apologize for not writing a great work of fiction in my heading. I figured out the bug happened when updating to the beta and losing the variations I had added. I fixed them manually by deleting the products and reuploading. Next time I will use support for support and this git for bugs that I find and write clearer.

**Comment by claudiosmweb** [comment]
@jonathanober Report a bug is quite different from making a support request. To start with the title, it will you describe the bug as opposed to say "Help me fix this"... And in the message you will describe the steps to reproduce the bug, how you created the product, which version you were using, which plugins are installed and so on.
