### ISSUE TITLE
Adding Simple products via api failed attribues

### ISSUE THREAD

**Issue by Freshclicks** [woothemes/woocommerce#8678]
I'm trying to add a simple product via the API and can't seem to get global product attributes to stick.

Example:
> 'attributes' => array(
>                        array(
>                            'name' => 'manufacturer',
>                            'option' => 'sony'
>                        )
>                    )

'sony' is a slug option for manufacturer. 
Also tried pa_maufacturer.

**Comment by claudiosmweb** [comment]
Please read our docs: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by Freshclicks** [comment]
Documentation doesn't have anything about adding attributes to simple products... The example also just shows,  "attributes": [],

**Comment by Freshclicks** [comment]
@claudiosmweb please don't close the issue as it is still unresolved. Its either a bug or missing documentation.

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
