### ISSUE TITLE
Attributes fail when adding or getting Simple products via api

### ISSUE THREAD

**Issue by Freshclicks** [woothemes/woocommerce#8679]
When adding a simple product via the API and can't seem to get global product attributes to stick.

Example:
>    'attributes' => array(
>    array(
>    'name' => 'manufacturer',
>    'option' => 'sony'
>           )
>    )

'sony' is a slug option for manufacturer. Also tried pa_maufacturer and including tried including position and visible too with no luck.

Also, if I add an attribute via the admin UI, and then use the api to get the product, the attributes are not being reported. 

> $client->products->get_by_sku('1'));

Documentation doesn't specify adding attributes to simple products... The example also just shows, "attributes": [],
This is not a support request, Its an issue with attributes NOT working when adding simple products through the API.

**Comment by claudiosmweb** [comment]
Tested and works fine!

Read the docs: http://woothemes.github.io/woocommerce-rest-api-docs/#products-properties
