### ISSUE TITLE
Manually creating new order with past date

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#8680]
When manually creating a new order with a past date, it reverts to today's date upon saving. However, if the order date is changed to a past date again and re-saved, the date is stored correctly. 

Is there any reason why backdating an order should not be allowed? If not, then it should be saved during the first attempt.

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce/issues/8633#issuecomment-123856935
