### ISSUE TITLE
Site-wide notice covers admin bar

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/woocommerce#8682]
When you have the Site-wide notice enabled under WooCommerce > Settings, it overlaps the admin bar on the front-end of the site.

Example:
![screen shot 2015-07-29 at 1 56 03 pm](https://cloud.githubusercontent.com/assets/3220162/8969703/fb762e1c-35f9-11e5-9d02-19299ac162c0.png)

**Comment by claudiosmweb** [comment]
Works great:

![screenshot from 2015-07-29 19 26 03](https://cloud.githubusercontent.com/assets/1264099/8971557/d92433da-3627-11e5-8109-2432124ce65a.png)

Seems to be a theme issue.

**Comment by WordCommerce** [comment]
I think this bar should push down the site, should have the close button and should have background color setting. These are just my thoughts..

![sitebar](https://cloud.githubusercontent.com/assets/9597926/8978983/6f9f2252-36af-11e5-9eaf-528d7a5f1422.jpg)

**Comment by Kenshino** [comment]
You can do all these with CSS. No need for a setting.

**Comment by WordCommerce** [comment]
Maybe you can, maybe I can do well, but not everyone. I think, It would be better to simplify people's lives. I'm not using this bar as a store owner, I've never used because it is not useful at all and also covered up the site logo.
