### ISSUE TITLE
Provide checkout object data to woocommerce_checkout_customer_id filter

### ISSUE THREAD

**Issue by brichards** [woothemes/woocommerce#8683]
As it stands, this filter isn't tremendously practical because it passes along no data about the current checkout state. If it passed `$this` along in addition to the current user ID I think it would be a lot more helpful.

Filter shown here: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-checkout.php#L582

I'll circle back with a PR for this in the near future.

**Comment by mikejolley** [comment]
I don't think this one is 100% necessary @brichards. Checkout is essentially a singleton, so you can grab the checkout instance with `WC()->checkout()` or `WC_Checkout::instance()` :)

**Comment by brichards** [comment]
Ah yeah, right, that :)

All the data I wanted is in $_POST at this point anyway. Carry on!
