### ISSUE TITLE
Pass full $order object to woocommerce_new_order and woocommerce_resume_order hooks

### ISSUE THREAD

**Issue by brichards** [woothemes/woocommerce#8684]
A full $order object has already been instantiated at the times these hooks fire but they only pass along the $order_id. If a function attached to these hooks needs other order data it will need to prop up its own separate object to access that data. Instead, we could pass $order along as a second arg and attached functions could get this data for free.

Referenced hooks exist here: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-checkout.php#L200 and here: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-checkout.php#L211

Any reason to specifically _not_ pass the object along through the hook? If not, I'll be happy to provide a PR.

**Comment by maxrice** [comment]
I've often wondered this myself, as it does seem like it'd be more convenient to not have to instantiate objects and it *seems* like it should be more performant. One argument against is that the established standard for hooks that pass instantiated data as an argument seems to always be the ID, see [Abstract WC_Order](https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php) -- all the actions use `$this->id`.

The other argument is that args in actions are passed with reference, so poorly-coded implementations could potentially muck up the object, whereas if they instantiate their own object there's no risk.

**Comment by brichards** [comment]
> The other argument is that args in actions are passed with reference, so poorly-coded implementations could potentially muck up the object, whereas if they instantiate their own object there's no risk.

This was my reason for pause as well. The _potential_ performance gains (if any, I haven't attempted any benchmarking here) might not offset the very real threat of bad code breaking checkout.

Curse you, passing by reference! You're extremely useful except in some isolated circumstances when you're not.

I'll leave the fate of such a modification to these hooks up to bigger brains than mine to consider and decide.

**Comment by mikejolley** [comment]
For consistencies sake/bw compat you'd only have the option to add a second arg to these actions. 

What is the intended use? What do you all use `woocommerce_resume_order` and `woocommerce_new_order` to do?

**Comment by mikejolley** [comment]
@brichards have any more feedback?

**Comment by brichards** [comment]
The general use case is to get at all of the different bits of order data without needing to prop up another new instance of the order object (assumed marginal performance gains at scale). I figured that, since the data was already ripe, it might as well get passed along, too.

However, given the concerns @maxrice pointed out – that objects are passed through hooks by reference – I'm a bit leery to expose the canonical order object to external processes. Not only for fear that someone else's code might break the store, but for fear that I might inadvertently break it myself.

**Comment by mikejolley** [comment]
Got it :)
