### ISSUE TITLE
Introduce wc_create_order_args filter to wc_create_order() function

### ISSUE THREAD

**Issue by brichards** [woothemes/woocommerce#8685]
There isn't yet a single convenient filter during the order creation process to capture and manipulate several pieces of new order meta in a single step.

It's possible to modify the data that is written to the posts table using the `woocommerce_new_order_data` filter. It's also possible to filter individual pieces of the new order args at various stages (some during the checkout process, like `woocommerce_checkout_customer_id`).

I propose adding a filter named `wc_create_order_args` at the parse_args step of `wc_create_order()` (here: https://github.com/woothemes/woocommerce/blob/master/includes/wc-core-functions.php#L65) to make this process a little less unwieldy.

If such a filter is welcome I'm happy to contribute a PR.

**Comment by mikejolley** [comment]
New order data can be changed right here https://github.com/woothemes/woocommerce/blob/master/includes/wc-core-functions.php#L96

**Comment by brichards** [comment]
Aye, the _post_ data can be changed right there but neither the customer ID nor customer note can be altered at this stage. I know that filters exist elsewhere for tapping into these different pieces of data, and the other args have filters that can be utilized, but to change each separate args would require tapping into several other filters separately.

My thought was that a single args filter would make this process cleaner and that introducing it at the point where the args are parsed would still allow for the more specific filters to operate and override like their current behavior.

**Comment by mikejolley** [comment]
Ah, I get you. Ok, happy if you contribute a PR for that.
