### ISSUE TITLE
woocommerce Version 2.3.13 product categories disappeared

### ISSUE THREAD

**Issue by ghensh** [woothemes/woocommerce#8686]
I have the latest version of woocommerce installed.

I've just imported a site over to a new server, everything came across fine apart from the product categories. These seem to have all disappeared and when I go to manually add one back, click save... it immediately disappears again.

Could someone please help??

**Comment by mikejolley** [comment]
If this was working on the previous site, I don't see how its a WooCommerce issue/bug. Categories are handled by WordPress core. Your import must not have been successful. 

https://deliciousbrains.com/wp-migrate-db-pro/ is a good option if you're migrating everything.
