### ISSUE TITLE
"My account" link should change to something personal when logged in (e.g. "<username>'s account")

### ISSUE THREAD

**Issue by gerdneuman** [woothemes/woocommerce#8688]
Currently, even after a customer has logged in using the "My Account" link in the menu (e.g. with Storefront), the text and link stays as it is. So customers do not easily see whether they are logged in or not already. There is no visual feedback. This is even more confusing if you come back later and are still logged in.

Other shopping sites like ebay or amazon change the "My Account" button to something personal (e.g. username) after the login has been done.

My Proposal: The "My Account" link should change to something like ` <username>'s account` or even better  `<username>'s account (logout)` (where `<username>'s account` links to `/my-account/` and  `logout` links to `/my-account/customer-logout`).

Maybe this could be done when handling #8492

**Comment by mikejolley** [comment]
This isn't something WC itself should be manipulating - "My Account" is the page name. Some users will likely object if this name was filtered in all cases.

If a custom account link, with username display, is needed, this should be coded into the theme header.php and avoiding the use of menus. This kind of functionality would not be difficult to code in.

**Comment by marwah1212** [comment]
> This isn't something WC itself should be manipulating - "My Account" is the page name. Some users will likely object if this name was filtered in all cases.
> 
> If a custom account link, with username display, is needed, this should be coded into the theme header.php and avoiding the use of menus. This kind of functionality would not be difficult to code in.

where can I get the code,
and in me putting it,
I also need like the question above
