### ISSUE TITLE
[API] Parent not set on variations

### ISSUE THREAD

**Issue by Nils-Fredrik** [woothemes/woocommerce#8691]
Hi,
I am not sure why this error occurs. But I have come across the following situation: 

When reaching https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L159:

```
		if ( $product->is_type( 'variation' ) ) {

			$product_data['parent'] = $this->get_product_data( $product->parent );
		}
```

The `$product->parent`is not set. This ends up in the error log as:
`PHP Fatal error:  Call to a member function get_title() on a non-object in class-wc-api-products.php on line 626`. 

As said, I dont know why the parent post does not exist. But, we should obviously handle situations where it does not. The API only gives a 500 error without any explanation, so API consumers are without any clue. 

My suggested fix is simply checking if parent exists before trying to use it: 
```
		if ( $product->is_type( 'variation' ) && $product->parent ) {

			$product_data['parent'] = $this->get_product_data( $product->parent );
		}
``` 

Nils-Fredrik

**Comment by claudiosmweb** [comment]
Closed in favor of #8692
