### ISSUE TITLE
[API] filtered attribute ignored when adding new products

### ISSUE THREAD

**Issue by Freshclicks** [woothemes/woocommerce#8693]
Unlike adding global attributes using the admin UI, when adding products via the API they are not associated with the global attributes used for filtering products.

When using $client->products->get_by_sku(); the returned values look identical

Added via the API
> {"name":"manufacturer","slug":"manufacturer","position":0,"visible":true,"variation":false,"options":["Sony"]}

Added via the admin interface:
>{"name":"manufacturer","slug":"manufacturer","position":"6","visible":true,"variation":false,"options":["Sony"]}

**Comment by claudiosmweb** [comment]
It seems that you are still using it the wrong way.
You can use without any problem the global attributos as long as you sign correctly!

**Comment by Freshclicks** [comment]
Ok. Sorry I'll keep trying, but i thought i had it right this time!

**Comment by Freshclicks** [comment]
@claudiosmweb how do you sign it correctly? 

I'm using...
> 'attributes' => array(
>                          array(
>                              'name' => 'manufacturer',
>                              'options' =>
>                                  array(
>                                      'sony'
>                                  ),
>                              'visible' => true,
>                              'variation' => false,
>                        )
>),
