### ISSUE TITLE
Dual plugin conflict breaks REST API

### ISSUE THREAD

**Issue by douglsmith** [woothemes/woocommerce#8694]
I've run into a case where any use of the REST API returns the following error:

> Fatal error: Call to a member function get_page_permastruct() on a non-object in /home/mysite/public_html/wp-includes/link-template.php on line 358

The error only happens when two other plugins are active: [JSON Basic Authentication](https://github.com/WP-API/Basic-Auth) 0.1 from the WordPress REST API project, and [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/) free or premium 2.3.2. These plugins only cause the error when active together and not individually.

I've confirmed the error on a new test site with a fresh install of WordPress 4.2.3 and WooCommerce 2.3.13. The only other plugins active are the two mentioned above.

Let me know if there is other information you would like me to collect. I'd be happy to help or make the test site available if needed.

**Comment by claudiosmweb** [comment]
Well, we don't use any function called `get_page_permastruct()`.
But if your WordPress is throwing error messages, of course will break our JSON API as well.

**Comment by douglsmith** [comment]
None of the three plugins in question or the Twenty Fifteen theme call `get_page_permastruct()`. However WordPress calls that function from `page_rewrite_rules()`, which is used in `/woocommerc/includes/wc-core-functions.php` in the `wc_fix_rewrite_rules()` function on line 607.

I don't know if it's the correct solution, but adding the following to that file outside of that function makes the error go away.

````
global $wp_rewrite;
$wp_rewrite = new WP_Rewrite();
````

BTW, I'm not seeing errors anywhere in WordPress other than the result of calling the WC JSON API.

**Comment by douglsmith** [comment]
Looking at this from a different angle, I'm trying to figure out what the JSON Basic Authentication plugin had to do with this. It's a fairly simple plugin and it doesn't doe any rewrites. But the error goes away if either this or Yoast SEO are disabled.

It calls `wp_authenticate()`, which is in `/wp-includes/pluggable.php/` at line 547. I narrowed it down to line 563:

````
$user = apply_filters( 'authenticate', null, $username, $password );
````

If I comment out that line the error also goes away. I'm not yet sure why, though. I tried removing filters on `authenticate` from WooCommerce but that didn't make any difference. Neither of the other plugins filter that.

**Comment by douglsmith** [comment]
From the perspective of Yoast SEO, I can modify `wp-seo-main.php` and also make the error go away. Starting at line 300 there are three instances of adding actions to `'plugins_loaded'`. If I replace the first and last one with `wp_loaded`, it fixes it.

````
if ( ( ! defined( 'WP_INSTALLING' ) || WP_INSTALLING === false ) && ( $spl_autoload_exists && $filter_exists ) ) {
	add_action( 'plugins_loaded', 'wpseo_init', 14 );

	if ( is_admin() ) {
		if ( defined( 'DOING_AJAX' ) && DOING_AJAX ) {
			require_once( WPSEO_PATH . 'admin/ajax.php' );
		}
		else {
			add_action( 'plugins_loaded', 'wpseo_admin_init', 15 );
		}
	}
	else {
		add_action( 'plugins_loaded', 'wpseo_frontend_init', 15 );
	}

	add_action( 'admin_init', 'load_yoast_notifications' );
}
````

Those are calling some functions that are involved in rewrites so maybe it's a problem of the global `$wp_rewrite` not existing when `plugins_loaded` fires. But if that's the case, I don't know why it's not a problem all the time.

**Comment by douglsmith** [comment]
At this point I'm not sure what is the cause and what is just a symptom. I'm (temporarily) at the end of what I can do but I hope it helps with some clues.

**Comment by douglsmith** [comment]
Another data point I just noticed is that an error is not returned if you hit the API's URL without authentication. Anything other than the root URL will tell you to authenticate, of course.

**Comment by douglsmith** [comment]
I have tested the code @claudiosmweb submitted to the Yoast/wordpress-seo repository and can confirm that it fixed the problem on my sites.

Thank you so much for the help even though it didn't end up being a WC problem!

**Comment by enricodeleo** [comment]
I have the very same problem but seems to be related to WC Vendors.

The stacktrace of the error is the following, any ideas?

```
…ww/website.dev/releases/20151218152000/web/wp/wp-includes/
link-template.php(314): _get_page_link()
…ww/website.dev/releases/20151218152000/web/wp/wp-includes/
link-template.php(143): get_page_link()
…eases/20151218152000/web/app/plugins/woocommerce/includes/
wc-page-functions.php(72): get_permalink()
…eases/20151218152000/web/app/plugins/woocommerce/includes/
#3 /srv/www/website.dev/releases/20151218152000/web/app/plugins/woocommerce/includes/wc-page-functions.php
wc-page-functions.php(139): wc_get_page_permalink()
… /srv/www/website.dev/releases/20151218152000/web/wp/wp-includes/
plugin.php(235): wc_lostpassword_url()
…website.dev/releases/20151218152000/web/wp/wp-includes/
general-template.php(523): apply_filters()
#6 /srv/www/website.dev/releases/20151218152000/web/wp/wp-includes/user.php(141): wp_lostpassword_url()
… /srv/www/website.dev/releases/20151218152000/web/wp/wp-includes/
plugin.php(235): wp_authenticate_username_password()
…rv/www/website.dev/releases/20151218152000/web/wp/wp-includes/
pluggable.php(587): apply_filters()
…m/releases/20151218152000/web/app/plugins/json-basic-auth/
basic-auth.php(32): wp_authenticate()
… /srv/www/website.dev/releases/20151218152000/web/wp/wp-includes/
plugin.php(235): json_basic_auth_handler()
…rv/www/website.dev/releases/20151218152000/web/wp/wp-includes/
pluggable.php(125): apply_filters()
…rv/www/website.dev/releases/20151218152000/web/wp/wp-includes/
pluggable.php(66): get_currentuserinfo()
…www/website.dev/releases/20151218152000/web/wp/wp-includes/
capabilities.php(424): wp_get_current_user()
…/20151218152000/web/app/plugins/wc-vendors/classes/admin/
class-product-meta.php(19): current_user_can()
…ics.com/releases/20151218152000/web/app/plugins/wc-vendors/
class-wc-vendors.php(202): WCV_Product_Meta->__construct()
… /srv/www/website.dev/releases/20151218152000/web/wp/wp-includes/
plugin.php(525): WC_Vendors->include_core()
#17 /srv/www/website.dev/releases/20151218152000/web/wp/wp-settings.php(276): do_action()
#18 /srv/www/website.dev/releases/20151218152000/web/wp-config.php(9): include()
#19 /srv/www/website.dev/releases/20151218152000/web/wp/wp-load.php(42): include()
#20 /srv/www/website.dev/releases/20151218152000/web/wp/wp-blog-header.php(12): include()
#21 /srv/www/website.dev/releases/20151218152000/web/index.php(11): include()
#22 {main}
```
