### ISSUE TITLE
API - Update variable product

### ISSUE THREAD

**Issue by PetterRuud** [woothemes/woocommerce#8699]
Getting this error message when updating a variable product.
Using https://github.com/kloon/WooCommerce-REST-API-Client-Library as a PHP wrapper

I have tried for a few hours now with smaller and smaller tests.

Data being sent
Array
(
    [method] => PUT
    [url] => https://bogartstore.no/wc-api/v2/products/19198
    [data] => Array
        (
            [product] => Array
                (
                    [title] => test100var
                    [type] => variable
                    [reviews_allowed] => 0
                    [brands] => Array
                        (
                            [0] => testcat
                        )

                    [categories] => Array
                        (
                            [0] => div-accessories
                        )

                    [attributes] => Array
                        (
                            [0] => Array
                                (
                                    [name] => Color
                                    [slug] => color
                                    [visible] => 
                                    [variation] => 
                                    [options] => Array
                                        (
                                            [0] => white
                                        )

                                )

                            [1] => Array
                                (
                                    [name] => Size
                                    [slug] => size
                                    [visible] => 1
                                    [variation] => 1
                                    [options] => Array
                                        (
                                            [0] => 34
                                            [1] => 32
                                            [2] => 30
                                        )

                                )

                            [2] => Array
                                (
                                    [name] => Color code
                                    [slug] => colorcode
                                    [visible] => 
                                    [variation] => 
                                    [options] => Array
                                        (
                                            [0] => white
                                        )

                                )

                            [3] => Array
                                (
                                    [name] => Season
                                    [slug] => season
                                    [visible] => 
                                    [variation] => 
                                    [options] => Array
                                        (
                                            [0] => 1501
                                        )

                                )

                            [4] => Array
                                (
                                    [name] => Color Variant
                                    [slug] => color-variant
                                    [visible] => 
                                    [variation] => 
                                    [options] => Array
                                        (
                                            [0] => white
                                        )

                                )

                            [5] => Array
                                (
                                    [name] => Front ID
                                    [slug] => front-id
                                    [visible] => 
                                    [variation] => 
                                    [options] => Array
                                        (
                                            [0] => 100
                                        )

                                )

                            [6] => Array
                                (
                                    [name] => Number
                                    [slug] => number
                                    [visible] => 
                                    [variation] => 
                                    [options] => Array
                                        (
                                            [0] => W15107+-+133
                                        )

                                )

                        )

                    [variations] => Array
                        (
                            [0] => Array
                                (
                                    [regular_price] => 200
                                    [sku] => 101
                                    [managing_stock] => 1
                                    [stock_quantity] => 0
                                    [weight] => 1.00
                                    [dimensions] => Array
                                        (
                                            [length] => 1
                                            [width] => 1
                                            [height] => 1
                                        )

                                    [attributes] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [name] => Size
                                                    [slug] => size
                                                    [option] => 34
                                                )

                                        )

                                )

                            [1] => Array
                                (
                                    [regular_price] => 200
                                    [sku] => 102
                                    [managing_stock] => 1
                                    [stock_quantity] => 0
                                    [weight] => 1.00
                                    [dimensions] => Array
                                        (
                                            [length] => 1
                                            [width] => 1
                                            [height] => 1
                                        )

                                    [attributes] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [name] => Size
                                                    [slug] => size
                                                    [option] => 32
                                                )

                                        )

                                )

                            [2] => Array
                                (
                                    [regular_price] => 200
                                    [sku] => 103
                                    [managing_stock] => 1
                                    [stock_quantity] => 0
                                    [weight] => 1.00
                                    [dimensions] => Array
                                        (
                                            [length] => 1
                                            [width] => 1
                                            [height] => 1
                                        )

                                    [attributes] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [name] => Size
                                                    [slug] => size
                                                    [option] => 30
                                                )

                                        )

                                )

                        )

                )

        )

    [consumer_key] => CONSUMER_KEY
    [consumer_secret] => CONSUMER_SECRET
    [options] => Array
        (
            [timeout] => 3600
            [ssl_verify] => 1
            [json_decode] => object
            [debug] => 1
        )

)

Error 
Fatal error: Uncaught exception 'WC_API_Client_HTTP_Exception' with message 'Error: The SKU already exists on another product [woocommerce_api_product_sku_already_exists]' in /Users/petter/Dropbox (Personal)/Web/gmdev/pocketcomms/bogart/importer/woocommerce-api/class-wc-api-client-http-request.php:211 Stack trace: #0 /Users/petter/Dropbox (Personal)/Web/gmdev/pocketcomms/bogart/importer/woocommerce-api/class-wc-api-client.php(288): WC_API_Client_HTTP_Request->dispatch() #1 /Users/petter/Dropbox (Personal)/Web/gmdev/pocketcomms/bogart/importer/woocommerce-api/resources/abstract-wc-api-client-resource.php(122): WC_API_Client->make_api_call('PUT', 'products/19198', Array) #2 /Users/petter/Dropbox (Personal)/Web/gmdev/pocketcomms/bogart/importer/woocommerce-api/resources/class-wc-api-client-resource-products.php(107): WC_API_Client_Resource->do_request() #3 /Users/petter/Dropbox (Personal)/Web/gmdev/pocketcomms/bogart/importer/importer.php(529): WC_API_Client_Resource_Products->update(19198, Array) #4 /Users/petter/Dropbox (P in /Users/petter/Dropbox (Personal)/Web/gmdev/pocketcomms/bogart/importer/woocommerce-api/class-wc-api-client-http-request.php on line 211

**Comment by claudiosmweb** [comment]
Here is the cause: "Error: The SKU already exists on another product".
SKU must be unique for each product.

**Comment by PetterRuud** [comment]
The skus for each variation are unique,  [sku] => 101,  [sku] => 102,  [sku] => 103. So you cant update a entire variable product the way I have done it, you have to update each variation for itself?

**Comment by claudiosmweb** [comment]
Some of the SKU are not unique `woocommerce_api_product_sku_already_exists`.
Whether the variations are not unique, if you have any other product or variation with SKU `101` then you can no longer use it in another product/variation.

**Comment by mikylucky** [comment]
Same problem here.
I am updating a variable product, it throws me the sku error even if there are no other products with the same sku

**Comment by roykho** [comment]
@mikylucky check to see if you have products in the trash that has same SKUs.

**Comment by mikylucky** [comment]
@roykho already checked. It's all afternoon I try to figure out which is the problem. I even tried cleaning the database

**Comment by roykho** [comment]
@mikylucky I would suggest you access your database and go to postmeta table and search for the key `_sku` and double check if any of the value already exists from what you're trying to create.

**Comment by mikylucky** [comment]
Nada, just one record.
Just for reference, I'm using v3 bulk function, but I saw the code throwing that error is the same

**Comment by mikylucky** [comment]
Solved, I forgot to add the ID to the variation in order to update it.
But here is my question.
If I want to bulk update/create 1000 products/variation, I need to make 1000 api call in order to check if a product sku is present in the database.
That's a huge load for the server!
Is there a workaround?
