### ISSUE TITLE
billing_postcode and shipping_postcode digit limit

### ISSUE THREAD

**Issue by standardplumbing** [woothemes/woocommerce#8701]
Not so much as an issue but would it be helpful for being able to limit the digit length for billing_postcode and shipping_postcode. This is where a customer is trying to enter a 9 digit zipcode  it will not calculate the tax, but it will do if you limit the digits to 5. This could be setting in WooCommerce>Settings>Checkout.

Thanks in advance
Cheers
Luke

**Comment by slash1andy** [comment]
I'm pretty sure that using the * to wildcard it (as mentioned in the FB group) would be the best thing here.

**Comment by standardplumbing** [comment]
But not all users would know how to do that, you get users of all levels of tech understanding and experience using WooCommerce for building stores.

**Comment by slash1andy** [comment]
To be a bit brutally honest, I don't see us adding in an option for people that don't read the documentation. http://docs.woothemes.com/document/setting-up-taxes-in-woocommerce/

**Comment by claudiosmweb** [comment]
@standardplumbing limit that will not work for the whole world.
You can add some validation for each country: https://github.com/woothemes/woocommerce/blob/ef0f527b40dba539e982efff26211fa577a24cf9/includes/class-wc-validation.php#L37-L72

You can use the filter or send a Pull Request with code for validation for your country.

**Comment by standardplumbing** [comment]
Okay fair enough. Just a suggestions and not an issue. 

Thanks

**Comment by claudiosmweb** [comment]
@standardplumbing you can too use http://igorescobar.github.io/jQuery-Mask-Plugin/
We use this in Brazil with a plugin that customize the checkout process just with brazilian things.

**Comment by claudiosmweb** [comment]
@standardplumbing you can use this to limit too:

```php
function my_wc_custom_billing_fields( $fields ) {
	$fields['billing_postcode']['maxlength'] = 5;

	return $fields;
}

add_filter( 'woocommerce_billing_fields', 'my_wc_custom_billing_fields' );

function my_wc_custom_shipping_fields( $fields ) {
	$fields['shipping_postcode']['maxlength'] = 5;

	return $fields;
}

add_filter( 'woocommerce_shipping_fields', 'my_wc_custom_shipping_fields' );
```

**Comment by claudiosmweb** [comment]
This helps too http://www.woothemes.com/products/postcodeaddress-validation/

**Comment by sanotronics** [comment]
@claudiosanches where should those functions be placed in order to set the maxlength for the postcodes?

**Comment by claudiosanches** [comment]
@sanotronics where works better for you. Since you can even create a plugin for it https://codex.wordpress.org/Writing_a_Plugin

**Comment by sanotronics** [comment]
but wouldn't it be better if they are placed within the woocommerce plugin? what I see, is an input field with a max length of 4 characters, but the html entity declared in shipping-calculator.php, line 91, doesn't set it, and I can't find where it does set this

```html
<p class="form-row form-row-wide" id="calc_shipping_postcode_field">
    <input type="text" class="input-text" 
    value="<?php echo esc_attr( WC()->customer->get_shipping_postcode() ); ?>" 
    placeholder="<?php esc_attr_e( 'Postcode / ZIP', 'woocommerce' ); ?>" 
    name="calc_shipping_postcode" id="calc_shipping_postcode"/>
</p>
```

![2017-04-12 14_45_55-carrito yaeltex](https://cloud.githubusercontent.com/assets/4588575/24971617/f030a782-1f8e-11e7-883f-a208dc4f6c7a.png)

**Comment by claudiosanches** [comment]
> but wouldn't it be better if they are placed within the woocommerce plugin?
Well if of update the WooCommerce you will lose your changes, so better you write your own plugin for this custom code.
