### ISSUE TITLE
Unable to POST and PUT operation 

### ISSUE THREAD

**Issue by shahshyam** [woothemes/woocommerce#8703]
Dear client 
I am consuming your Woocommerce REST API in C# using RESTSharp. It does not accept API key and secret token in C#. 

       Method method = Method.POST;
        string result = "";
        string endpoint = "products";
        var client = new RestClient(ApiUrl);
          client.Authenticator = new HttpBasicAuthenticator(UserApiKey, UserPassword); 
        request.RequestFormat = DataFormat.Json;
        request.AddJsonBody(new Product { title = "eeee2", type = "simple", regular_price = "777", description = "Descr" });       
        result = client.Execute(request).Content;
        return result;

The error is 

{"errors":[{"code":"woocommerce_api_authentication_error","message":"oauth_consumer_key parameter is missing"}]}

Thanks 
Shyams

**Comment by claudiosmweb** [comment]
Please read the documentation: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by maxrice** [comment]
@shahshyam you'll typically see this issue when trying to use HTTP Basic Auth over plain HTTP. You'll need to connect over SSL if you want to use basic auth.

**Comment by shahshyam** [comment]
Thanks

**Comment by shahshyam** [comment]
Hi
I am using https and again get same issue. could you please help me

**Comment by shahshyam** [comment]
Even  I used api v3 but not working . Please check your documentation and update it.

 request.RequestFormat = DataFormat.Json;
            request.AddParameter("Accept", "application/json", ParameterType.HttpHeader);
            request.AddParameter("User-Agent", _Configuration.UserAgent, ParameterType.HttpHeader);


            ((RestClient)restClient).AddHandler("application/json", new Deserializers.NewtonSoftJsonDeserializer());

            var client = restClient;
            client.Authenticator = new HttpBasicAuthenticator(_Configuration.UserApiKey, _Configuration.UserPassword);
            client.Timeout = _Configuration.RequestTimeout;

            var response = client.Execute<T>(request);
