### ISSUE TITLE
Proposal: Shipping Prices Including Tax

### ISSUE THREAD

**Issue by bolderelements** [woothemes/woocommerce#8705]
It might seem small but it's something I keep hearing from users overseas so I thought I would mention it. As an example, I had a client in Germany whose had a tax rate of 19%. One of his shipping prices was $4.90, inclusive of tax. This means he would enter the shipping cost as $4.118 so that together with the 19% tax rate (which equaled $0.78) it would equal $4.90. When you have several rates to enter, it can be a tedious process to calculate the specific numbers you need.

I think some users could benefit from this option, maybe not on a site-wide basis from the Tax settings, but as an option within the Shipping Method class similar to the ability to disable taxing on certain methods.

**Comment by mikejolley** [comment]
This one is already on the roadmap https://trello.com/b/YgRbpuze/woocommerce-roadmap Not high-high priority, and may affect bw compat unless a separate option, but its logged :)
