### ISSUE TITLE
Woo Commerce Variations Order

### ISSUE THREAD

**Issue by gobnet14** [woothemes/woocommerce#8706]
Anybody tell me how to keep my variations in order in the back end and the front end. This issue has been promininent and I wrote about it 2 years ago and more. Anybody got a fix for this? We have between 65 and 130 variations per product. All the attributes are in the right order and all the sizes are in the right order but when they are loaded into WC they seem to be set randomly all over the place. We are building a new version of our web site www.kitchens4u.ie and this seems to still persist. Anybody ever found a fix for this. Been searching the net with no success.

**Comment by claudiosmweb** [comment]
Tested and works fine.

The order will be defined by your attributes:

![screenshot from 2015-08-03 12 25 33](https://cloud.githubusercontent.com/assets/1264099/9040828/fa9e9f1c-39da-11e5-897d-3130d23cfa2e.png)

You can define the order by using this option:
![workspace 1_001](https://cloud.githubusercontent.com/assets/1264099/9040903/79e097d0-39db-11e5-970f-8255102833ca.png)
