### ISSUE TITLE
admin-ajax Broken after update

### ISSUE THREAD

**Issue by mikemcguire** [woothemes/woocommerce#8709]
Hello,
   Recently upgraded woocomerce on a clients site and now any use of wp-admin/admin-ajax is being forced to use https and is no longer working. The site is hosted on a pantheon server and I did see the issue with is_ssl and load balanced sites. added the fix to my wp-config, still broken. Also broken on my local mamp server. NGINX gives 502 bad gateway, Apache just times out. Now anything that uses admin-ajax is broken, can't view media library, can't modify Menus, WP Migrate DB pro no longer works, so on and so fourth. 

This appears to be related to a setting within the Database as everything was working as expected until I pulled the database from production. I've disabled force ssl in the woocommerce settings to no avail. The only fix modification that has any impact is disabling woocomerce. Obviously not on option. 

Issue is happening on multiple OS, browsers, networks and Servers. 

Let me know if / how I can provide more info. Thanks.

**Comment by mikejolley** [comment]
Nothing in WC forces ajax to be over https. The only code which does any kind of SSL redirect is the option for the checkout. 

https://github.com/woothemes/woocommerce/search?q=woocommerce_force_ssl_checkout&type=Code&utf8=%E2%9C%93

Some hosts do however. Should also check you're using the latest 2.3 release to work around a chrome bug which forced some resources https.

**Comment by mikemcguire** [comment]
Hmmm, well this wouldn't be a host issue since we are seeing the issue on both a NGINX server and an Apache server. And after having just upgraded Woocommerce on another website we've run into this issue a second time. Considering the fact that disabling woocommerce fixes the issue, and that upgrading woocommerce is what has caused the issue, I am only given the option to believe that woocommerce is the culprit if not partially.

I am hoping I will have some more time today to isolate the issue and report back. Thanks for reading my message and looking into this issue.

**Comment by mikejolley** [comment]
Ok let us know. defo check its latest though; there were some chrome issues previously. And check WC extensions, because once core is disabled, they disable themselves too which could give misleading results.

**Comment by kstohr** [comment]
having same issue... did you find a resolution?

**Comment by mikemcguire** [comment]
Really sorry I usually try to follow up on my outstanding issues. I can't even remember what project I was working on here for sure. Loading admin-ajax via https is permissible. If I were you I would request that file directly in your browser and see if anything comes up on your server's error logs. I vaguely remember having an issue where some of my custom theme code relied on the objects created by woocommerce which was performing very slowly due to some badly arranged left joins in a custom mysql query that was causing a timeout. Which would explain why disabling woocommerce resolved the issue. Requesting admin-ajax is already a cumbersome request for the wordpress application so it doesn't play nicely with badly performing code.  I haven't had the issue ongoing with any of my other projects, a lot of them are woocommerce and would say this isn't an issue with woocommerce itself. If you're using MAMP you can find instructions on how to enable https for your hosts, or you may need to just make sure your apache virtual host will route port 443 properly. I do remember confirming that it wasn't due to the chrome issues that had been noted in the changelog. 

Also some projects have bloated .htaccess files, I remember recently inheriting some code that handled https requests in weird wasys and just trying to do a  find for 443, SSL, or HTTPS inside of my .htaccess didn't help me find a hidden directive that was handling https weird. 

Best of luck, apologies for not following up on this sooner.

**Comment by kstohr** [comment]
Mike-- huge thanks for the response... worked it out ... was actually an
ssl issue caused by upgrading our server environment. Resolved.
