### ISSUE TITLE
update_order_review and checkout form submit on enter key 

### ISSUE THREAD

**Issue by mehulkaklotar** [woothemes/woocommerce#8711]
when changing address fields and then pressing enter key asap submits checkout form without the update order review action request being complete. There should be priority or check for request that if update order review request is on then form checkout should not be submitted.

**Comment by mikejolley** [comment]
This shouldn't be an issue. If you submit it immediately or press placeholder also, the data is still posted correctly through to the order. Just tested this and the data was correct.

**Comment by mehulkaklotar** [comment]
what if I have a hook in update order review process that takes like more time to load on page then I have a wrong data on checkout page and my checkout commences before the update order review process. I am working on site which has this type of issue. 
https://snapboxprints.com/checkout

**Comment by mikejolley** [comment]
Does your code not handle post? What if JS is disabled?

**Comment by mehulkaklotar** [comment]
There will not be any case where js will be disabled. And update order review is fetching shipping options from other sources like USPS, fedex APIs. So those requests will take time to fetch data and display shipping methods accordingly. So Here if I change address then update order review will fire and checkout form will also submitted with wrong details of shipping because customer has changed the address and that address has other shipping options which is yet not rendered on page.
