### ISSUE TITLE
Proposal: Add filters for product price suffix

### ISSUE THREAD

**Issue by NZSmartie** [woothemes/woocommerce#8713]
Needing a way to include product unit information in the store that also works with the global price suffix setting. 

At the moment, existing filters like `'woocommerce_get_price_html'`returns the price with the suffix included. Adding a unit *such as per Kg* may end up looking like `$25.00 (incl. Tax) Per Kg` which may not suit the client's needs.

Additional filters for the suffix would allow unit information to be appended before the global suffix to the price to get a result that looks like `$25.00 Per Kg (Incl. Tax)`

**Comment by JeroenSormani** [comment]
@NZSmartie did you try using this filter? https://github.com/NZSmartie/woocommerce/blob/0ecd59e0bab709233f5071fa448281d9f68a4e6a/includes/abstracts/abstract-wc-product.php#L926

It seems redundant to add all those extra filters when that one exists. Though I haven't dived into it fully.

**Comment by mikejolley** [comment]
woocommerce_get_price_suffix is indeed suitable.
