### ISSUE TITLE
Variation data in email notification

### ISSUE THREAD

**Issue by nayemDevs** [woothemes/woocommerce#8716]
Can you please tell me how does WooCommerce send variation data in email notification to the seller?. Example - Customer purchased a black color t-shirt ( from color variation) now how does the seller will inform about that?.

**Comment by claudiosmweb** [comment]
Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
