### ISSUE TITLE
System Status Active Plugins and Multisite

### ISSUE THREAD

**Issue by muzza78** [woothemes/woocommerce#8721]
The Woocommerce system status only shows active plugins per site on WPMU. I have 5  network active plugins in WPMU and none show in the Woocommerce System Status.

**Comment by gedex** [comment]
@muzza78 Could you try this branch: [issues/8721-fix-network-activated-plugins-not-showing-up](https://github.com/woothemes/woocommerce/tree/issues/8721-fix-network-activated-plugins-not-showing-up)? It should list all network activated plugins.
