### ISSUE TITLE
Strip HTML from shipping label in admin panel

### ISSUE THREAD

**Issue by Noja13it** [woothemes/woocommerce#8723]
I'm working on a shipping module for WooCommerce and my labels for the shipping options contain a few HTML tags, mostly \<br/> tags,  to make it look nicer. However, when looking at the orders in the admin panel, the tags are visible and makes the information difficult to read.

Is there any way to strip the label of the HTML tags on the "Orders" page in the admin panel?

**Comment by mikejolley** [comment]
No you'd need to conditionally set the label for the shipping method. Possibly based on is_admin().

Labels are not intended to contain HTML.
