### ISSUE TITLE
From price not visible in cart

### ISSUE THREAD

**Issue by Willem-Siebe** [woothemes/woocommerce#8726]
Original price: 250
Discount price: 200

This is not visible in cart:

![2015-08-05_13-13-53](https://cloud.githubusercontent.com/assets/5107354/9084443/12bfb0dc-3b74-11e5-8e04-2e6adba4f8e5.jpg)

**Comment by mikejolley** [comment]
Intended; showing from price or other info would be undesirable due to space and confusion. Cart shows the actual price to be paid.

**Comment by Willem-Siebe** [comment]
@mikejolley I have checked four big dutch ecommerce sites (bol.com, wehkamp.nl, coolblue.nl and conrad.nl) and I have to agree that 3 of them do it the same way as woocommerce and don't show the original price. Still I think I prefer to show the original price as well... why not offer this as a setting?

**Comment by mikejolley** [comment]
We don't believe in adding extra settings for the minority. If you want it, customise the template files. Then you can have it however you want.
