### ISSUE TITLE
Taxes total filter not reflected after order has been placed

### ISSUE THREAD

**Issue by jessor** [woothemes/woocommerce#8728]
I use the `woocommerce_cart_taxes_total` filter to add an amount of money to the "(Includes £ X.XX VAT)" line. It works great until the order is placed. It's not applied on Order Details or the Thank you emails.

I'm not sure if this is a bug or it's me who's missing something.

WordPress 4.2.4, WooCommerce 2.3.13

**Comment by mikejolley** [comment]
`woocommerce_cart_taxes_total` applies to the cart only.

You will likely need woocommerce_get_order_item_totals for order totals.
