### ISSUE TITLE
Tax rate wild cards can't be empty

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#8736]
WooCommerce 2.3

![](https://dl.dropboxusercontent.com/s/pkfwd87cvukq0tn/2015-08-06%20at%2008.42.png?dl=0)

WooCommerce 2.4 

![](https://dl.dropboxusercontent.com/s/f0i8kcwtq2r6vky/2015-08-06%20at%2008.46%20%281%29.png?dl=0)

This makes accounting for 9 digit zip codes difficult

![](https://dl.dropboxusercontent.com/s/iq296bx664by37c/2015-08-06%20at%2008.48.png?dl=0)

**Comment by evandon** [comment]
this would be great
