### ISSUE TITLE
Checkout → Review Order problem

### ISSUE THREAD

**Issue by MBalazs90** [woothemes/woocommerce#8741]
When I click on Checkout → Review Order submenu, the page shows the code only
[woocommerce_review_order] . Site: wordpress 4.4.3/ theme: twenty thirteen/ woocommerce 2.3.13
of course the cart was not empty..
![error](https://cloud.githubusercontent.com/assets/6899680/9125675/309dab74-3ca3-11e5-9f20-6776835fe1de.jpg)

**Comment by claudiosmweb** [comment]
We don't have any `[woocommerce_review_order]` shortcode.

Check your "Checkout Pages" and "Checkout Endpoints" settings.
