### ISSUE TITLE
Products - Simple Product Error

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#8743]
When you go to add a product as a simple product and then put in the price (not the sale price), it adds it fine, however, when you go to view the product list, the price is missing.  also when you go into shop and then view the product, there is no price or add button.

if you need further information, please leave a message

**Comment by jshand2015** [comment]
below are the backends i use:

mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux (x86_64) using  EditLine wrapper

PHP 5.6.9 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
    with Suhosin v0.9.36, Copyright (c) 2007-2014, by SektionEins GmbH

**Comment by mikejolley** [comment]
This does not look or sound like a core issue; most likely a theme or plugin conflict. Here shows it working as intended:

http://g.recordit.co/RGSOhl1RcR.gif
