### ISSUE TITLE
[API] Products tag endpoint

### ISSUE THREAD

**Issue by murdockcrc** [woothemes/woocommerce#8744]
I found this issue (https://github.com/woothemes/woocommerce/issues/6241), related to filtering products by their category.

I have not found a way to do the same type of filtering with tags. Our products include tag information that turns out to be crucial for filtering for our clients that consume the REST API.

I am not sure if this feature is missing or if I am overseeing something in the way the filters work in the current version of the API.

**Comment by yyhmsg** [comment]
For what it's worth, I would very much like to see this added as well....

Both the ability to do:
https://example.com/wc-api/v3/products/tags
as you can with:
https://example.com/wc-api/v3/products/categories

and getting a product list with certain tags:
https://example.com/wc-api/v3/products?filter[tags]=this-tag

like you can with categories:
https://example.com/wc-api/v3/products?filter[categories]=this-category

**Comment by claudiosmweb** [comment]
@yyhmsg This is already part of the plans. No worry ;)

**Comment by mikejolley** [comment]
Same as #8971

**Comment by claudiosmweb** [comment]
@mikejolley nop :P
Here is to create a new endpoint for tags and #8971 is for add a filter in products endpoint for tags and attributes.

**Comment by NishithGit** [comment]
Ho to filter products based on some other parameters such as price , brand etc ?
