### ISSUE TITLE
Products - Simple and Variable Products

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#8749]
I have the latest version of storefront installed 1.4.6.

i only have woocommerce installed and no other plugins installed.

the problem still exists in regards to the price and it not showing up in the product list.  to be exact, the products show, but prices are all missing

**Comment by jshand2015** [comment]
you actually have to enter the price also in sale price for it to show

**Comment by jshand2015** [comment]
i must say that i am using the latest release 2.3.13

**Comment by mikejolley** [comment]
Why post a new topic - same as this one https://github.com/woothemes/woocommerce/issues/8743 ? cc @jameskoster

**Comment by jshand2015** [comment]
i'm starting to wonder if mariadb is compatible with woocommerce.  in theory it should be as it is an upstream of mysql.  i tried to add a new product with the regular price and it didn't show in the product list.  to work around that problem, i had to add the price again in sale price and then viewed the product list, and the price was listed.

**Comment by claudiosmweb** [comment]
@jshand2015 By two years I just MariaDB use for both development and production.
And I'm not able to produce the error you're talking about.

**Comment by jshand2015** [comment]
is there a way to send pictures on here mike?  can i send them to you, just to show you what happens.  notice the update button instead of publish

**Comment by claudiosmweb** [comment]
![screenshot from 2015-08-08 21 06 38](https://cloud.githubusercontent.com/assets/1264099/9152873/9401ee40-3e11-11e5-931f-6c7acb1d2d58.png)

**Comment by claudiosmweb** [comment]
@jshand2015 show your currency settings.

**Comment by jshand2015** [comment]
![currencysettings](https://cloud.githubusercontent.com/assets/10791292/9153283/647dc866-3ea1-11e5-96ad-571471306a36.png)

My Currency settings.  let me know if you need anything else.

**Comment by mikejolley** [comment]
Email login details so I can add some debug code. mike.j@woothemes.com

**Comment by mikejolley** [comment]
via email..
