### ISSUE TITLE
[possible bug] REST API POST not working with OAuth 1.0

### ISSUE THREAD

**Issue by mahnuh** [woothemes/woocommerce#8750]
Hi,

I am struggling with this for days now and I think I maybe found a bug.

I am trying to built a small app with angular, that uses the woocommerce api. After a few experiments I got oauth working with javascript, calling GET /orders works fine for example. So I tried POST /orders/<id>/notes and here we go.
First I always got 401, signature does not match. So I  printed the signature class-wc-api-authentication.php creates and compared it to the signature I created on the javascript side, they matched! But still only 401.
After some more testing, I realised, that sometimes it works just fine and the note is created, about 1 in 10 times. So I did a little digging and found out, that it only works, if there is no '+' in the signature I send to the api. After doing print $params['oauth_signature']; in class-wc-api-authentication.php (line 147) I found out, that a '+' gets replaced by a space. And when woocommerce tries to compare the two signatures, they obviously do not match.

What is going on there? Am I missing something? Did I find a bug?

Maybe someone can help and save my weekend. ;-)

Best regards
Manuel

**Comment by claudiosmweb** [comment]
Tested and works fine POST and OAuth 1.0.

See our API docs: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by maxrice** [comment]
@mahnuh try using a new version of the endpoint, the latest (v3) explicitly does a `rawurldecode()` on the consumer signature which does *not* replace plus characters with a space. see https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L236
