### ISSUE TITLE
[2.4]Update Changed displayed price of variable products to "free" and doesn't update when front-end user chooses new prod from drop down 

### ISSUE THREAD

**Issue by hellbertos** [woothemes/woocommerce#8757]
Running an uncustomized version of Woocommerce running w/o additional plugins; very vanilla (it has worked fantastically well up to this point too. Thank you!!). Updated  this morning and found that prices for many of the products with variations display in the store as "Free!". When I examined the products+variations individually from the admin panel, all the prices were still there. I tried changing the default variation, and that just shifted the price to the first variation's price; regardless of which I picked.

In the store front, the cart selection seems to work, even though the price does not update. Also, when adding the selected product to the cart, the price shows up correctly, but ALL the variations are represented, so the user would have no idea what they chose.

Hope there's a fix coming soon. I don't know how to roll it back sadly. Thanks

**Comment by claudiosmweb** [comment]
Have you used something for import products?

**Comment by hellbertos** [comment]
No I have not used an "import" scripts. These were all existing products which were entered manually when I launched the small shop.

**Comment by claudiosmweb** [comment]
Which version you started the shop and which version you upgraded to WooCommerce 2.4?

**Comment by hellbertos** [comment]
Launched the shop about a year ago, so started w/ 2.x. Updated from last 2.3

**Comment by hellbertos** [comment]
For what its worth, I just updated another site from 2.3.13 to 2.4 on the staging area. This site runs on a Woo Theme and it exhibits the exact same behavior.

**Comment by claudiosmweb** [comment]
I need more details of what you are doing, because I did tests with updates and all going well.

**Comment by claudiosmweb** [comment]
Have you clicked on the "Run Update" button?

**Comment by hellbertos** [comment]
OK. And, thank you for the interest/help.

I'm not sure what details you're after though. I these are really pretty simple installs. I did click the "Run Update" button, though it did not change anything.

Perhaps logging in to the Wootheme Install yourself would help? Sorry, I'm at a loss here.

I just went through the basic install process, as I've done in the past. Perhaps, I should reinstall 2.3.13 then re-upgrade?

**Comment by claudiosmweb** [comment]
Show me your system status report.

**Comment by hellbertos** [comment]
### WordPress Environment ###

Home URL: http://caiacoopman.staging.wpengine.com
Site URL: http://caiacoopman.staging.wpengine.com
WC Version: 2.4.0
Log Directory Writable: ✔  /nas/wp/www/staging/caiacoopman/wp-content/uploads/wc-logs/
WP Version: 4.2.4
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.9-1ubuntu4.11
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.25
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.0
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (9) ###

Share Buttons by AddToAny: by AddToAny – 1.6.3
GigPress: by Derek Hogue – 2.3.10
Manual Image Crop: by Tomasz Sita – 1.10
WooCommerce Colors: by WooThemes – 1.0.6
WooCommerce Table Rate Shipping: by Erica Dion – 3.5
WooCommerce: by WooThemes – 2.4.0
WooSidebars: by WooThemes – 1.4.2
WordPress Importer: by wordpressdotorg – 0.6.1
WP Maintenance Mode: by Designmodo – 2.0.3

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #38 - /shop/
Cart: #39 - /cart/
Checkout: #40 - /checkout/
My Account: #42 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Whitelight-1-4-Child
Version: 1.4.20
Author URL: http://www.woothemes.com
Child Theme: ✔
Parent Theme Name: Whitelight
Parent Theme Version: 1.4.20
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –


WordPress Environment
Home URL:	[?]	http://caiacoopman.staging.wpengine.com
Site URL:	[?]	http://caiacoopman.staging.wpengine.com
WC Version:	[?]	2.4.0
Log Directory Writable:	[?]	✔ /nas/wp/www/staging/caiacoopman/wp-content/uploads/wc-logs/
WP Version:	[?]	4.2.4
WP Multisite:	[?]	–
WP Memory Limit:	[?]	40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode:	[?]	–
Language:	[?]	en_US
Server Environment
Server Info:	[?]	Apache
PHP Version:	[?]	5.5.9-1ubuntu4.11
PHP Post Max Size:	[?]	100 MB
PHP Time Limit:	[?]	3600
PHP Max Input Vars:	[?]	1000
SUHOSIN Installed:	[?]	–
MySQL Version:	[?]	5.6.25
Max Upload Size:	[?]	50 MB
Default Timezone is UTC:	[?]	✔
fsockopen/cURL:	[?]	 ✔
SoapClient:	[?]	 ✔
DOMDocument:	[?]	 ✔
GZip:	[?]	 ✔
Remote Post:	[?]	 ✔
Remote Get:	[?]	 ✔
Database
WC Database Version:	[?]	2.4.0
woocommerce_api_keys	 	✔
woocommerce_attribute_taxonomies	 	✔
woocommerce_termmeta	 	✔
woocommerce_downloadable_product_permissions	 	✔
woocommerce_order_items	 	✔
woocommerce_order_itemmeta	 	✔
woocommerce_tax_rates	 	✔
woocommerce_tax_rate_locations	 	✔
Active Plugins (9)
Share Buttons by AddToAny	 	by AddToAny – 1.6.3
GigPress	 	by Derek Hogue – 2.3.10
Manual Image Crop	 	by Tomasz Sita – 1.10
WooCommerce Colors	 	by WooThemes – 1.0.6
WooCommerce Table Rate Shipping	 	by Erica Dion – 3.5
WooCommerce	 	by WooThemes – 2.4.0
WooSidebars	 	by WooThemes – 1.4.2
WordPress Importer	 	by wordpressdotorg – 0.6.1
WP Maintenance Mode	 	by Designmodo – 2.0.3
Settings
Force SSL:	[?]	–
Currency	[?]	USD ($)
Currency Position	[?]	left
Thousand Separator	[?]	,
Decimal Separator	[?]	.
Number of Decimals	[?]	2
API
API Enabled:	[?]	✔
API Version:	[?]	3.0.0
WC Pages
Shop Base:	[?]	#38 - /shop/
Cart:	[?]	#39 - /cart/
Checkout:	[?]	#40 - /checkout/
My Account:	[?]	#42 - /my-account/
Taxonomies [?]
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:	[?]	Whitelight-1-4-Child
Version:	[?]	1.4.20
Author URL:	[?]	http://www.woothemes.com
Child Theme:	[?]	✔
Parent Theme Name:	[?]	Whitelight
Parent Theme Version:	[?]	1.4.20
Parent Theme Author URL:	[?]	http://www.woothemes.com
WooCommerce Support:	[?]	✔

**Comment by hellbertos** [comment]
Would it help if I gave you the System Status from the live "un-updated" site?

**Comment by hellbertos** [comment]
This is what it looks like:

![woocomm-2-4-free](https://cloud.githubusercontent.com/assets/1234806/9179237/060ebbc8-3f50-11e5-8c0e-942b8f436b6d.jpg)

**Comment by hellbertos** [comment]
I guess its time to attempt reinstalling WC2.3.13... 

Thanks for looking into it. Hope this issue gets resolved in the not too distant future. Thanks for all the hard work! Its an awesome plugin when its working!

**Comment by claudiosmweb** [comment]
@hellbertos I just fixed it, release the WooCommerce 2.4.1 now.
Thanks.

**Comment by hellbertos** [comment]
Thank you Claudio! Works GREAT! You rule dude!!!

**Comment by pixedelic** [comment]
Same problem with 2.4.1 on four different themes (included TwentyEleven). Any advice?

**Comment by pixedelic** [comment]
Shame on me, haven't run the updater, many apologies :P
