### ISSUE TITLE
Variations Won't Expand in Firefox 39.0.3 (OS X)

### ISSUE THREAD

**Issue by arrjaytea** [woothemes/woocommerce#8759]
Currently unable to modify or even see variations to products in the admin back end in Firefox 39.0.3 on OS X.

Attempted to view current products after update, and could not get the options to toggle open.  Then checked in Chrome 44.0.2403 and everything functioned as expected.

Front end is unaffected.  Products display and add as normal.

**Comment by mikejolley** [comment]
Just tested FF on mac on my local install without issue.

Link?

**Comment by mikejolley** [comment]
Hold on your said backend..testing again..

**Comment by mikejolley** [comment]
No issue there either: https://dl.dropboxusercontent.com/s/gd57cmic45aus2a/2015-08-10%20at%2022.16%20%281%29.png?dl=0

https://dl.dropboxusercontent.com/s/1ay65r3g8gj4av0/2015-08-10%20at%2022.16%20%282%29.png?dl=0

If its working in Chrome, its likely just aggressive browser caching. Flush it.

**Comment by arrjaytea** [comment]
100% an aggressive cache issue.  My apologies.  Thanks guys.
