### ISSUE TITLE
Partial Refund Email Sent During "WooCommerce Data Update Required"

### ISSUE THREAD

**Issue by treyrich2001** [woothemes/woocommerce#8761]
In trying to upgrade to woocommerce 2.4 I selected 'Run Updater' under "WooCommerce Data Update Required", so far this has never completed successfully, and provides no reason for being unsuccessful.

Despite being unsuccessful we have customers reporting that they're receiving emails about a 'Partial Refund' despite having received a full refund over a year ago.

It seems there's a pretty severe bug here that's sending automated emails to past customers with no warning. Additionally the updater is failing to complete and not reporting why this is the case.

**Comment by claudiosmweb** [comment]
Fixed on WooCommerce 2.4.1.
