### ISSUE TITLE
woocommerce_variation_option_name filter not executing in first load variations

### ISSUE THREAD

**Issue by allysonsouza** [woothemes/woocommerce#8762]
I'm developing a plugin, so I updated to WooCommerce 2.4.1, to test if everything is working.

In my plugin, I'm filtering the variations using the "woocommerce_variation_option_name" hook, but in the first variations load, on admin panel, the hook is not executed. It only runs when I create a new variation, making the new variation select field with filtered content, and the firstly loaded variations without filtered content.

**Comment by allysonsouza** [comment]
![woocommerce_2 4 1_variations](https://cloud.githubusercontent.com/assets/2000638/9188637/afce3a9e-3fb4-11e5-9d85-95d1d69f48e9.png)

**Comment by mikejolley** [comment]
The same file/filters are used for both events. It's probably more likely is that your function is hooked in too late or in the wrong place.

https://github.com/woothemes/woocommerce/blob/1a2ccd741b5bc6efa5e8906e6ff0ec4a00f88e15/includes/admin/meta-boxes/views/html-variation-admin.php#L41

cc @claudiosmweb
