### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by littlepackage** [woothemes/woocommerce#8763]
Hello,

My Woocommerce 2.4.1 System Status is clear.
Wordpress 4.3-beta1 and Twentyfifteen play nice.

However, Wordpress 4.3-beta1 and both Mystile and Hustle themes bring up an error alert/message upon checkout:

`SyntaxError: Unexpected token <`

Instead of a success alert/message (like it gets with Twentyfifteen or any other usual time).

No other errors or notices pop up when this occurs, and the order goes through for all themes (confirmation emails received, order posted, etc). Is there something with your themes that will also need to be updated with Woo 2.4 and WP 4.3?

**Comment by claudiosmweb** [comment]
Please, show the full error message.

**Comment by littlepackage** [comment]
That is the full error message.

**Comment by littlepackage** [comment]
SyntaxError: Unexpected token <

**Comment by claudiosmweb** [comment]
@littlepackage in what file?

**Comment by littlepackage** [comment]
Also, for the record, I have no other plugins but WooCommerce activated. It
seems to be a theme problem, but these are both Woo themes, so I'm putting
this out there.

**Comment by littlepackage** [comment]
I cannot tell. It's just bringing that up as a woo message upon checkout,
instead of showing an order success message.

**Comment by maxrice** [comment]
I think this error is due to a plugin producing output during the checkout, particularly if there was PHP warnings or notices. The PHP error log should point to the problem file :)

**Comment by littlepackage** [comment]
Nope. Like I said, the only plugin I have running is WooCommerce. There is
nothing about it in the error log.

**Comment by mikejolley** [comment]
Framework related. Looking for a fix.

In meantime, if this is a live site turn off WP_DEBUG/error reporting and you won't get the issue.

**Comment by riseofweb** [comment]
I am receiving the same error message on checkout  WooCommerce v2.4.1, WP Version 4.2.4,
Theme Twenty Twelve.  Nothing in my error log, WP_DEBUG is set to false, yet here is the error...

![error-message](https://cloud.githubusercontent.com/assets/10745370/9203862/83dd78dc-400e-11e5-9633-dae44636a287.jpg)

Mike, is your fix in the latest version yet?  If not, do you know when it will be?

**Comment by claudiosmweb** [comment]
@riseofweb new release later today.

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Editing_wp-config.php#Configure_Error_Logging
