### ISSUE TITLE
Variable Products: text attribute option value is lowercase 2.3 but capitalized in 2.4

### ISSUE THREAD

**Issue by eliorivero** [woothemes/woocommerce#8765]
Hi, in previous versions, when you entered a custom product attribute, the option value in front end was sanitized:
<img width="579" alt="wc-2 3 13" src="https://cloud.githubusercontent.com/assets/1041600/9190668/4afecb50-3fce-11e5-914f-eee15e5acea1.png">

but in 2.4 (and 2.4.1 so far), it's not:
<img width="572" alt="wc-2 4 1" src="https://cloud.githubusercontent.com/assets/1041600/9190669/4b004da4-3fce-11e5-893d-64b5cff4cd66.png">

I have a plugin that changes the select values according to a user interaction. To do that I was comparing the product attribute and its terms following the sanitized standard version. Of course, I've just found that they don't work and now I must check if it's WC 2.4 or 2.3 and compare unsanitized or sanitized versions respectively.

Is this a bug that will be rectified later or this unsanitized version will be the new standard?

Cheers.

**Comment by mikejolley** [comment]
This will be the standard going forward. If you wonder why, take 2 custom attribute values: 12 and 1/2

When sanitised these both become 12.

This is not a problem for global attributes because WP makes and stores unique slugs e.g 12, 12-2

**Comment by eliorivero** [comment]
Hi Mike, got it, thanks for the explanation.
