### ISSUE TITLE
version 2.4.0 & 2.4.1 breaks page on attribute

### ISSUE THREAD

**Issue by jeroenvdbosch** [woothemes/woocommerce#8767]
after the update to 2.4.0.an 2.4.1 my product page breaks on an attribute. 
If have a dimension attribute with values like (20 x 20 x 20 cm). My page breaks on those attributes, deleting only the dimension attribute solves the problem, so other attributes work fine. 
Now I downgraded to 2.3.13 and it works again. 

Example on: http://test.woodzs.nl/product/buitenleven/vuurzuil-tyr/ (see extra info -> Afmetingen)

**Comment by jeroenvdbosch** [comment]
the error comes from: 

Catchable fatal error: Object of class stdClass could not be converted to string in /.../.../.../.../wp-content/plugins/woocommerce/templates/single-product/product-attributes.php on line 56

**Comment by mikejolley** [comment]
Any special steps to replicate?

Seems to be working my side https://dl.dropboxusercontent.com/s/o2fv5edi2xgwj69/2015-08-11%20at%2013.31.png?dl=0

**Comment by jeroenvdbosch** [comment]
I noticed a difference between "attributes" and "custom attributes", the last one also works fine...
but I shall look into it, how to replicate it...

**Comment by mikejolley** [comment]
Ping me if you find a way to trigger it. No one here is having any luck causing the error.
