### ISSUE TITLE
Issue when adding attributes to existing variable products

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8769]
I had an extisting variable product on Wc 2.3, then on Wc 2.4 i decided to add a new attribute.

When doing that, the variations list hides all the exisitng variations, while before it used to show the new attribute dropdown

![](http://cld.wthms.co/BA8H/4Luiapxa+)

Saving the product fix the issue

**Comment by ChromeOrange** [comment]
@SiR-DanieL are you using attributes or custom product attributes?

**Comment by SiR-DanieL** [comment]
I added a new Custom attribute with name is "Format" and the value is "Men's | Women's"

**Comment by ChromeOrange** [comment]
@SiR-DanieL are you doing this on localhost or on your DO site?

I can't replicate this

**Comment by SiR-DanieL** [comment]
Localhost @ChromeOrange 
I'll try later with a fresh install

**Comment by SiR-DanieL** [comment]
Can't be reproduced on Digital Ocean.
