### ISSUE TITLE
Bug with product variations in Woocommerce after upgrading to 2.4 (and 2.4.1. after that)

### ISSUE THREAD

**Issue by monkshop** [woothemes/woocommerce#8772]
There’s a strange bug in our webshop after upgrading to WC 2.4 (and to 2.4.1. after that, hoping it would fix the bug). All our half sizes in product variations don’t show up anymore in the front. They are still there in the backend but do not show on web. See attachments as well. Website is live and working here: http://monkshop.eu.

Hope you can help!
Cheers,
<img width="1344" alt="schermafdruk 2015-08-10 21 46 07" src="https://cloud.githubusercontent.com/assets/13746655/9195501/9e682e30-4023-11e5-9773-417a80a237f2.png">
<img width="471" alt="schermafdruk 2015-08-10 21 46 11" src="https://cloud.githubusercontent.com/assets/13746655/9195503/9e6af318-4023-11e5-921c-759897026a4c.png">
<img width="827" alt="schermafdruk 2015-08-10 21 46 40" src="https://cloud.githubusercontent.com/assets/13746655/9195504/9e70130c-4023-11e5-8c7b-e1c3697a74b2.png">
<img width="817" alt="schermafdruk 2015-08-10 21 46 49" src="https://cloud.githubusercontent.com/assets/13746655/9195502/9e690f94-4023-11e5-8b40-74605d758ade.png">

**Comment by claudiosmweb** [comment]
What is the stock status of these variations that do not appear?

**Comment by monkshop** [comment]
Varies from 0 to 3.
It's the same problem with all products that have half-sizes. We have over 50 of them. I thought it could have something to do with the ',' or '.' issue. We always use ',' as 8,5, but in the US they often use 8.5. You can set it and we didn't made any changes, but maybe there's a conflict after upgrading ...?

**Comment by mikejolley** [comment]
Tried this local without issue https://dl.dropboxusercontent.com/s/65y6yvz8l5f7dc3/2015-08-11%20at%2015.18.png?dl=0

@monkshop looks to be theme related. I think its an outdated version of templates/single-product/add-to-cart/variable.php

Switch to default WP theme to confirm. Then look for an update from the author or replace/delete that template file from the theme to revert to our new 2.4 version.

Good luck!
