### ISSUE TITLE
Why WC_API_Products.get_attributes returns non sanitized value of slug

### ISSUE THREAD

**Issue by zzlalani** [woothemes/woocommerce#8773]
The function `get_attributes()` in class `WC_API_Products` in [file] (https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L1890) returns the name of the attributes in both cases rather of the sanitized slug

	private function get_attributes( $product ) {
		$attributes = array();
		if ( $product->is_type( 'variation' ) ) {
			// variation attributes
			foreach ( $product->get_variation_attributes() as $attribute_name => $attribute ) {
				// taxonomy-based attributes are prefixed with `pa_`, otherwise simply `attribute_`
				$attributes[] = array(
					'name'   => wc_attribute_label( str_replace( 'attribute_', '', $attribute_name ) ),
					'slug'   => str_replace( 'attribute_', '', str_replace( 'pa_', '', $attribute_name ) ),
					'option' => $attribute,
				);
			}
		} else {
			foreach ( $product->get_attributes() as $attribute ) {
				// taxonomy-based attributes are comma-separated, others are pipe (|) separated
				if ( $attribute['is_taxonomy'] ) {
					$options = explode( ',', $product->get_attribute( $attribute['name'] ) );
				} else {
					$options = explode( '|', $product->get_attribute( $attribute['name'] ) );
				}
				$attributes[] = array(
					'name'      => wc_attribute_label( $attribute['name'] ),
					'slug'      => str_replace( 'pa_', '', $attribute['name'] ),
					'position'  => (int) $attribute['position'],
					'visible'   => (bool) $attribute['is_visible'],
					'variation' => (bool) $attribute['is_variation'],
					'options'   => array_map( 'trim', $options ),
				);
			}
		}
		return $attributes;
	}

In my case it returns

    Array
        (
            [name] => Variation 1
            [slug] => Variation 1
            [position] => 0
            [visible] => 1
            [variation] => 1
            [options] => Array
                (
                    [0] => Var11
                    [1] => Var12
                )

        )

and what I expect it should be rather this

    Array
        (
            [name] => Variation 1
            [slug] => variation-1
            [position] => 0
            [visible] => 1
            [variation] => 1
            [options] => Array
                (
                    [0] => Var11
                    [1] => Var12
                )

        )

**Comment by mikejolley** [comment]
It's referring to these https://dl.dropboxusercontent.com/s/mhkgbxac5uhkp22/2015-08-11%20at%2012.59.png?dl=0

For custom product attributes (the manual kind) it will be however its entered - they have no slugs.

**Comment by zzlalani** [comment]
so what you say is in attributes the values for name and slug will always be same?

**Comment by mikejolley** [comment]
For custom text attributes yes.
