### ISSUE TITLE
Regular Price and Sale Price Problem in Product Creation

### ISSUE THREAD

**Issue by vicky081** [woothemes/woocommerce#8775]
Hi,

I updated WooCommerce Version 2.4.1 with that i checked by entering regular price as 10 and the sale price as 50, when i enter 50 it shows error message saying please enter value less than regular price, after that it allows to publish the product(i hope it shouldn't)

Which should not happen right? or something i missed?

Thanks.

**Comment by mikejolley** [comment]
It warns you, but ultimately your responsibility. HTML5 validation like this shouldn't disable the publish/save button - the panel may not be visible. Hope that makes sense :)

**Comment by harmancheema93** [comment]
Hi,
I want to implement same functionality where I can add sal price greater then regular price, If I do it forcefully then Woocommerce cart not let me add that product in cart. Any solution for this update?

Thanks.
