### ISSUE TITLE
mod_security and shipping class slugs

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#8777]
When saving the Flat Rate Shipping settings there will be a white screen of death if long shipping class slugs have been used due to the limitations set by mod_security.

Current fix is to edit the shipping class slugs - THIS WILL REMOVE ANY COSTS THAT HAVE BEEN ADDED TO THE FLAT RATE SETTINGS SO TAKE A SCREEN SHOT FIRST!

**Comment by mikejolley** [comment]
Needs to be monitored - would require a data upgrade to convert slugs to ids.

I think it may be edge case - only if the user has entered a long string for class names + has mod sec configured in a certain way.

If we do work on it, it will need a data upgrade.

**Comment by ChromeOrange** [comment]
This issue is not being fixed in a point release because it will need another database update.

If it generates a lot of tickets then @mikejolley will review.

cc @BFTrick
