### ISSUE TITLE
checkout.js expects payment methods to be located in #order_review

### ISSUE THREAD

**Issue by EmilEriksen** [woothemes/woocommerce#8779]
I don't see a reason for this. I want to move payment method selection outside #order_review but then I have to copy the code for payment methods in checkout.js which is silly.

I've also seperated the place order row from payment in payment.php but I don't see any reason why these are tied together and why the place order row should be fetched via ajax every time payment is.

**Comment by jameskoster** [comment]
Fair points. We'll look into this for 2.5.

**Comment by EmilEriksen** [comment]
Sounds great! Would you consider changing checkout.js to look for payment methods in the checkout form instead in a 2.4 release since it's backwards compatible and a minor change?

**Comment by jameskoster** [comment]
If we're confident we can make this 100% backwards compatible we'll probably include it, yes :-) Will decide when we look into it.

**Comment by EmilEriksen** [comment]
Awesome! Thank you.

**Comment by jameskoster** [comment]
Also, if you want to see this included sooner, feel free to send a PR ;-)
