### ISSUE TITLE
Impossible to call $.ajax( $fragment_refresh ); at a theme level

### ISSUE THREAD

**Issue by webdados** [woothemes/woocommerce#8780]
Due to the way the javascript is being compressed to the min.js versions is now not possible to call `$.ajax( $fragment_refresh );` (and I suppose other functions) at a custom theme level because the function is now called `d`.

**Comment by mikejolley** [comment]
I cannot think of any reason why an external script would need to do this, and accessing properties like that is not a good idea. If you need this for a valid reason, propose a new trigger event. We need more details.

**Comment by webdados** [comment]
You are absolutely right and we were using this in a way that we shouldn't.

We use some custom ajax calls to:
- Remove items from our minicart (I guess we should use the "remove_order_item" woocommerce ajax endpoint)
- Updating quantity of a specific item on the minicart (Is there a way to do this?)
- Add and remove coupon on the minicart (Is there a way to do this?)
And we call `$.ajax( $fragment_refresh );` after these actions to update the fragments.

**Comment by mikejolley** [comment]
If you update the widget via your own code, you don't need to touch fragments. They will refresh next page load.

**Comment by webdados** [comment]
I need to get the fragments because there's the total on the top of the page that must be updated also. Check here: https://www.vinha.co.uk/ Add an item to the cart and then use the minicart input boxes to update the quantity and/or remove items from the minicart.

I would suggest a new trigger that would just refresh the fragments that we could use on this kind of situations.

**Comment by mikejolley** [comment]
You can trigger it yourself for now by using lines 21 to 38 in your own script.

**Comment by webdados** [comment]
That's exactly what I did on my dev install. Thanks.
