### ISSUE TITLE
Fatal error when running updater 2.4.1 from 2.3.13

### ISSUE THREAD

**Issue by MarioKnight** [woothemes/woocommerce#8781]
I'm going through clients' sites updating from 2.3.13 to 2.4.1, and while most have been updated with no issues, on one site I receive a fatal error:

Fatal error: Uncaught exception 'Exception' with message 'Refund failed: ' in /home/jimapco/public_html/wp-content/plugins/woocommerce-wootax/classes/class-wc-wootax-refund.php:184 Stack trace: #0 /home/jimapco/public_html/wp-content/plugins/woocommerce-wootax/classes/class-wc-wootax-refund.php(38): WC_WooTax_Refund::process_refund(Object(WC_WooTax_Refund)) #1 /home/jimapco/public_html/wp-content/plugins/woocommerce/includes/wc-order-functions.php(715): WC_WooTax_Refund->calculate_totals(false) #2 /home/jimapco/public_html/wp-content/plugins/woocommerce/includes/updates/woocommerce-update-2.4.php(174): wc_create_refund(Array) #3 /home/jimapco/public_html/wp-content/plugins/woocommerce/includes/class-wc-install.php(176): include('/home/jimapco/p...') #4 /home/jimapco/public_html/wp-content/plugins/woocommerce/includes/class-wc-install.php(58): WC_Install::update() #5 [internal function]: WC_Install::install_actions('') #6 /home/jimapco/public_html/wp-includes/plugin.php(496): call_user_func_array(Array, Array) #7 /home/jim in /home/jimapco/public_html/wp-content/plugins/woocommerce-wootax/classes/class-wc-wootax-refund.php on line 184

If someone could please provide insight, that would be greatly appreciated.  Thank you.

**Comment by mikejolley** [comment]
This error is coming from a plugin called 'woocommerce-wootax'. Looks like its conflicting with the update routine. Disable the woocommerce-wootax extension.

**Comment by MarioKnight** [comment]
That was it, thank you for pointing me in the right direction!
