### ISSUE TITLE
Order received page affecting menu

### ISSUE THREAD

**Issue by swiderski** [woothemes/woocommerce#8783]
There is an issue that on pages "order details" and "view order"(example link http://site.com/wordpress/shop/my-account/view-order/6432/ ) will affect name of first link in page menu. It will change it either to "Order received" or "Order #6432".

## When it happens
In short: when in page.php `the_post()` is called before `wp_nav_menu()`

Edited page.php template of theme twentyfifteen to recreate issue
```php
<?php
/**
 * The template for displaying pages
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages and that
 * other "pages" on your WordPress site will use a different template.
 *
 * @package WordPress
 * @subpackage Twenty_Fifteen
 * @since Twenty Fifteen 1.0
 */
the_post(); //moved post call
get_header(); ?>

	<div id="primary" class="content-area">
		<main id="main" class="site-main" role="main">

		<?php
		// Start the loop.
//		while ( have_posts() ) : the_post(); //we moved it above

			// Include the page content template.
			get_template_part( 'content', 'page' );

			// If comments are open or we have at least one comment, load up the comment template.
			if ( comments_open() || get_comments_number() ) :
				comments_template();
			endif;

		// End the loop.
//		endwhile;
		?>

		</main><!-- .site-main -->
	</div><!-- .content-area -->

<?php get_footer(); ?>
```

## Why anyone would like to call the_post before menu?
It doesn't matter, as this is clearly some uncleaned query, as this issue only happens on mentioned pages. However :-) I will post use case 

In my theme I use such construction

```php
the_post();

if(post_password_required()){
	//then go and show some fancy password required page, it will use get_header() in its own time
}
else{
	get_header(); //here is menu called
	the_content(); 
	get_footer();
 }//end of if password_protected
```

If I can help any more, please tell me.

**Comment by mikejolley** [comment]
The above is invalid. You have no loop.

We have a function called wc_page_endpoint_title - this filters the_title allowing us to dynamically replace a page title.

We are very specific to what titles are affected:

`if ( ! is_null( $wp_query ) && ! is_admin() && is_main_query() && in_the_loop() && is_page() && is_wc_endpoint_url() ) {`

Main query. In the Loop. On a page. When showing an endpoint.

By calling the the_post(); outside of the loop you break all of the above WordPress conditionals.

cc @claudiosmweb

**Comment by swiderski** [comment]
I understand by loop you mean call of function `have_posts()`  cause it is only one that affects  anything that you can check.

Or I just must not use `the_post` before header? 

Still if so, then can you point me which page of WC will also produce issue according to this `if` as I would like to verify your theory?

**Comment by mikejolley** [comment]
The code is here https://github.com/woothemes/woocommerce/blob/53916e38bb44e7aaca7368bb0170ade44a75cd1e/includes/wc-page-functions.php#L18

https://codex.wordpress.org/Function_Reference/the_post

> Iterate the post index in The Loop. Retrieves the next post, sets up the post, sets the 'in the loop' property to true.

So both :)

**Comment by swiderski** [comment]
Thanks for clarification, I will fix my thinking about the loop.

With kind regards.

**Comment by Joe-Bloggs** [comment]
Hey guys, @mikejolley,

I came across to the exact same issue. Here is a [screenshot of my footer](https://ibb.co/sHNcVx1) 
On the Thank you page (Order received) the first link in the menu is somehow hijacked and the menu item title which normally reads 'Privacy' now changes to 'Order received'

My site uses Elementor Footer, but otherwise pretty simple, mostly kept to default, no custom code.

Any ideas what to do to fix that?
