### ISSUE TITLE
Problem with checkout Local Delivery

### ISSUE THREAD

**Issue by kingkong22** [woothemes/woocommerce#8785]
There is a problem in the Checkout when I've set the Allowed Zip/Post Codes at local delivery and with account logon. The Local Delivery didn't appear when I've enter the zipcode that meet the condition but when I tick and untick the "Ship to a different address?" then the option appear.
It seem some javascript binding problem. Please check and fix it. Thanks

**Comment by mikejolley** [comment]
Do you have a link to a site with this issue, and what zip do we try?

**Comment by kingkong22** [comment]
I seem ok now.. maybe I didn't remove cache after update to latest version 4.0.1
Sorry about that.
