### ISSUE TITLE
Bug with Variations

### ISSUE THREAD

**Issue by stevewoody82** [woothemes/woocommerce#8786]
I've updated to Woocommerce 2.4.1 and also updated WooSubscriptions. 

The challenge I have is when I try to access a product using the variations. It throws up an error that there are no variations and won't let me select them on the front end. I rebuilt the product thinking that they update would have affected it but there was still a challenge. I couldn't get variations to work. I had to revert back to the old install but happy to recreate the situation as a way to help identify a fix.

**Comment by mikejolley** [comment]
Any of your variation attributes contain quotes? 2.4.2 would resolve that if so.

**Comment by stevewoody82** [comment]
I'll check now Mike but there was only two very simple variations. 

Just about to test 2.4.2

**Comment by stevewoody82** [comment]
Ok I updated everything else. including woosubscription to 1.5.29 and it was working perfect.

As soon as I upgraded woocommerce to 2.4.2 it threw up the same error 

Sorry, no products matched your selection. Please choose a different combination.

**Comment by mikejolley** [comment]
Which theme is this?

**Comment by stevewoody82** [comment]
I'm using the X themes from Themeco

**Comment by mikejolley** [comment]
Can you check what I posted here https://wordpress.org/support/topic/24-common-issue-variations-missing-on-product-pages?replies=1

**Comment by stevewoody82** [comment]
Did that, Bug still seems to be active on the site, no change.

**Comment by stevewoody82** [comment]
Ahh my bad. I was on the plugin not the theme. Have done as you requested now.

How could I grab the latest variable.php file :(

**Comment by stevewoody82** [comment]
After deleting yourtheme/woocommerce/single-product/add-to-cart/variable.php it worked fine
