### ISSUE TITLE
WooCommerce 2.4.2: Simple Product Error

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#8787]
At this stage i have added the product to the list.  you will see the update button instead off publish.

![productpage](https://cloud.githubusercontent.com/assets/10791292/9214625/5901aaa2-40f4-11e5-9b04-c2ebb06afa35.png)

i then checked the product list, and there was no price for the product i just added

![productlist](https://cloud.githubusercontent.com/assets/10791292/9214642/768b7706-40f4-11e5-853a-74f0e880cdd3.png)

Then i went to the shop page and selected the product and got this result.  notice that there is no price in view

![shoppage](https://cloud.githubusercontent.com/assets/10791292/9214660/a29829de-40f4-11e5-8e56-c7c6891a261f.png)

**Comment by mikejolley** [comment]
This is the 3rd time you have posted this now. As I told you via email, this is not reproducible, and we cannot investigate your local host. It is a problem in your environment. Feel free to use a site that is publicly accessible and repeat your test and report if needed, *but not until then.*
