### ISSUE TITLE
Variable product doesn't keep track of the existing variables.

### ISSUE THREAD

**Issue by michaelbeers** [woothemes/woocommerce#8788]
A client of mine created a variable product since 2.4.1. The product has 13 "size" variations and 4 "heel size" variations. When attaching new variations using the new dropdown list it is possible to add more than 300 variations on that single product... which should be 52 (13*4) max, because then you have all the possible variations attached.

Screenshot 1
![Screenshot1](https://i.gyazo.com/28aa4d3193921405957029a5fff3b075.png)

Screenshot 2
![Screenshot2](https://i.gyazo.com/23927cc2ed96862377bfc598acf98f45.png)

**Comment by mikejolley** [comment]
2.4.2 should resolve. Tested - 1st run made 50. 2nd run made 2.

**Comment by michaelbeers** [comment]
I updated to 2.4.2 aswell:

- Deleted ALL the variations
- 1st run 50
- 2nd run still 50

Deleted the product and created a new one:

- 1st run 50
- 2nd run still 50

What can be wrong?

**Comment by mikejolley** [comment]
I setup exact same variations attributes as you. On the 2nd run of 50, have you looked at what is being created?

**Comment by michaelbeers** [comment]
It create doubles, but since update 2.4.3 it seems to be resolved.

1st run in 2.4.3 = 50
2nd run in 2.4.3 = 2
