### ISSUE TITLE
Woo Commmerce 2.4

### ISSUE THREAD

**Issue by whitemint** [woothemes/woocommerce#8789]
Hi,

We have updated our website (www.whitemint.co.uk) to the latest version of Woocommerce, and are getting an error when clicking to proceed to the payment gateway. 

The error we receive is "SyntaxError: Invalid character"

Does anyone know what would cause this?

Thanks

**Comment by stephangriesel** [comment]
What payment gateway are you using?

**Comment by whitemint** [comment]
We use Mijreh and Paypal.

**Comment by mikejolley** [comment]
I've just posted here about it https://wordpress.org/support/topic/24-common-issue-syntaxerror-unexpected-token?replies=1
