### ISSUE TITLE
Fatal Error w/ shipping after updating

### ISSUE THREAD

**Issue by joshzandman** [woothemes/woocommerce#8790]
Website: http://saltygirljewelry.com

Hi, I just updated woocommerce to 2.4.2 and I get the following errors when trying to check out:

After submitting billing address (shipping defaults to billing) and clicking the PayPal checkout button, I get this error:
SyntaxError: JSON Parse error: Unrecognized token '<'

Then when I refresh the cart page or try to delete and add another product, I get this error:
Fatal error: Unsupported operand types in /home/jzhawaii/public_html/saltygirljewelry.com/wp-content/plugins/woocommerce/includes/class-wc-shipping.php on line 321

I use Advance Shipping plugin - I deactivated it and still produced the same error.

When I disable 'enable shipping' in the settings, the error goes away and I'm able to connect with PayPal, but naturally there's no option to ship it anywhere.

Thanks for your help

**Comment by mikejolley** [comment]
Not sure why you're posting this in multiple places - just making more work for me :p

Turn off all shipping extensions and check the log I mentioned. From the fatal error, something is changing some variables for some reason. I'll see if that line can be tweaked to prevent that occurring.

**Comment by joshzandman** [comment]
Sorry man :)

I'll try that, thanks

**Comment by mikejolley** [comment]
^ That patch should work around it if the shipping method borks taxes.

**Comment by joshzandman** [comment]
Thanks Mike. After updating class-wc-shipping.php this is the error it's giving me now:

Parse error: syntax error, unexpected 'foreach' (T_FOREACH) in /home/jzhawaii/public_html/saltygirljewelry.com/wp-content/plugins/woocommerce/includes/class-wc-shipping.php on line 322

**Comment by mikejolley** [comment]
so something is changing '$this->shipping_taxes' from an array? urgh ok. Doing some more digging

**Comment by mikejolley** [comment]
Actually, are you sure you applied that patch correctly? Copy the entire raw file and replace what you have @JoshKoberstein

**Comment by joshzandman** [comment]
I just copied the update and replaced:

		if ( ! empty( $rate->taxes ) && is_array( $rate->taxes ) ) {
+						foreach ( array_keys( $this->shipping_taxes + $rate->taxes ) as $key ) {
+							$this->shipping_taxes[ $key ] = ( isset( $rate->taxes[$key] ) ? $rate->taxes[$key] : 0 ) + ( isset( $this->shipping_taxes[$key] ) ? $this->shipping_taxes[$key] : 0 );
+						}
				}
			}
		}
}

**Comment by mikejolley** [comment]
If it errors after that I'll ask that you var_dump $rate->taxes and $this->shipping_taxes so we can see whats there.

**Comment by joshzandman** [comment]
That worked! I do get an Invalid Shipping alert, but I'm sure that's something on my end/settings.

**Comment by toxictrend** [comment]
Invalid Shipping method keeps coming up on my woo commerce and my clients cant purchase our products

**Comment by toxictrend** [comment]
is there any fix for this
