### ISSUE TITLE
Tabs doesn't hide on changes anymore on 2.4.2

### ISSUE THREAD

**Issue by nextime** [woothemes/woocommerce#8791]
Change at line 32 of file assets/js/frontend/single-product.js in commit 03f16d68336f8a2357b43afff75df93bcced5891 
add .woocommerce-tabs class to this line:

$tabs_wrapper.find( '.wc-tab, .woocommerce-tabs .panel:not(.panel .panel)' ).hide();

This make the tabs doesn't hide at all, cause in $tabs_wrapper we are already "inside" the .woocommerce-tabs class, and then nothing is selected this way. This is a regression from 2.4.1 and need to be fixed by reverting the change for this line. to the previous version

**Comment by edbloom** [comment]
Yip i had the same issue. What I found though was I was using an override for my tabs and the markup in the override was missing a newer class wc-tab - once I added that all was ok again. But agreed - I'm sure lots of theme devs will get bitten by this - ironic that a change was made to prevent theme conflicts has probably triggered lots of grey hairs for theme devs today :)

**Comment by edbloom** [comment]
But you're right about the .woocommerce-tabs bug - bit annoying that this was changed in a subpoint release.

**Comment by mikejolley** [comment]
it was changed because users with themes adding .panel to other divs were finding them hidden.

**Comment by mikejolley** [comment]
@nextime 

This one is correct:

`
$( '.wc-tab, .woocommerce-tabs .panel:not(.panel .panel)' ).hide();
`

The other is not. Patching now.
