### ISSUE TITLE
get_related limitation?

### ISSUE THREAD

**Issue by edbloom** [woothemes/woocommerce#8792]
I'm not sure if this is a bug or a constraint of the current get_related function but here goes.

Use Case: 
Product category with 100 items
Theme: Storefront - latest version - no child theme. No overrides. Plain Storefront out of the box.
WC version - 2.4.2 - no other plugins active.

Issue description
For a given product (in this case below id = 70) in a given product category (in this case id = 13) the get_related function generates this query (transients cleared before loading the page)

 
`SELECT DISTINCT ID FROM wp_posts p INNER JOIN wp_postmeta pm ON ( pm.post_id = p.ID AND pm.meta_key='_visibility' ) INNER JOIN wp_term_relationships tr ON (p.ID = tr.object_id) INNER JOIN wp_term_taxonomy tt ON (tr.term_taxonomy_id = tt.term_taxonomy_id) INNER JOIN wp_terms t ON (t.term_id = tt.term_id) WHERE 1=1 AND p.post_status = 'publish' AND p.post_type = 'product' AND p.ID NOT IN ( 0,70 ) AND pm.meta_value IN ( 'visible', 'catalog' ) AND ( tt.taxonomy = 'product_cat' AND t.term_id IN ( 0,13 ) ) OR ( ( tt.taxonomy = 'product_tag' AND t.term_id IN ( 0 ) ) AND p.ID NOT IN ( 0,70 ) ) LIMIT 3`

This returns 3 rows as expected by this query. 

The problem I have is that the scope of the query is quite limited. 

i.e. If I have a category with 100 products, the same 3 items will be shuffled each time this query is generated. Even if the limit is increased to say 10 items, this still isn't a resolve, as it will still exclude the other 90 items below the limit - meaning it's the same 10 items always being shuffled.

Is this by design to ensure this page loads fast or is this a bug? I would expect products from across the full category range to be candidates to be displayed in related products.

**Comment by mikejolley** [comment]
This is by design because a full-scope related posts query on each page load would (and used to) kill performance. RAND() is slow as well so thats not an option.

The function is pluggable if you want your own slow website version :)

**Comment by edbloom** [comment]
Cheers @mikejolley for the clarification. I'll stick with the fast version :) I was pretty sure it used to work differently but thought I was going mad. Might be nice territory for a plugin to do an enhanced Related Products that builds wider scope related items via wp-cron a couple of times a day. I'll play around with it at some stage (hopefully!). Thanks again - great work on 2.4!
