### ISSUE TITLE
order_total in invoice email for refunded orders

### ISSUE THREAD

**Issue by Spreeuw** [woothemes/woocommerce#8793]
In WC2.3, refunds were not taken into account in the invoice email when it was sent out to the customer. That makes sense from an accounting point of view, since an original invoice should not be changed.
Now in WC2.4 the totals from the original invoice email seem to have changed.

This is the invoice email (WC2.4):
 <img width="558" alt="invoice-email" src="https://cloud.githubusercontent.com/assets/3217773/9223287/094128a8-40f9-11e5-9973-6f19ae5586b6.png">

And this the refund email (WC2.4):
<img width="535" alt="refund-email" src="https://cloud.githubusercontent.com/assets/3217773/9223290/1b811c94-40f9-11e5-943e-36faabb50d20.png">

My vote would go out to keep the original WC2.3 behavior (treating invoices and refunds as separate entities), as it is much more intuitive.

**Comment by Spreeuw** [comment]
It also looks like in the refund email, the $refund object is not loaded, thereby ignoring the "Amount refunded" part of the totals: https://github.com/woothemes/woocommerce/blob/master/templates/emails/customer-refunded-order.php#L48-L54

**Comment by mikejolley** [comment]
$refund is global. Passed into the file via include.

The order emails are not true invoices though; I think they should reflect the amounts actually used. Do you not use something like https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/ instead?

**Comment by Spreeuw** [comment]
for some reason, $refund doesnt to be passed properly though, as amount refunded does not appear in my email. It also looks like the <del> element is not included in the invoice email (see screenshots above), though I can't figure out why from looking at the code. (I doubled checked and I'm not using any override templates).

Yes, I use PDF invoices & packing slips. However, I was referring to the "customer invoice" email, not any of the order emails.

Ideally, get_formatted_order_total would accept a switch as to whether or not it should take refunds into account. I will create a pull request so you can review.
