### ISSUE TITLE
Danish currency symbol was changed to DKK

### ISSUE THREAD

**Issue by EmilEriksen** [woothemes/woocommerce#8794]
https://github.com/woothemes/woocommerce/commit/928b1cca2fa8c60e51c330febfb2bea01d927155

@mikejolley Why the change? "kr." is the correct Danish currency symbol.

**Comment by mikejolley** [comment]
Because some danish gateways enforce DKK. This came from user feedback via support.

**Comment by EmilEriksen** [comment]
Sorry to reopen but that doesn't really make sense to me. Then those gateways are poorly coded. Surely poor plugin code shouldn't rub off on core WC code.

**Comment by mikejolley** [comment]
It was a merchant restriction.

> i can't get my Cartholder/Payservice "Nets" who provides Dankort as a pay method for my customers, up and running before i've change my valuta from "kr" to "DKK.-"

Several tickets about this.
