### ISSUE TITLE
After updating to woocommerce 2.4.2, variations stopped showing

### ISSUE THREAD

**Issue by empiremachinery** [woothemes/woocommerce#8795]
After we updated the woocommerce, variations stopped showing in all the variable products. For example: 
http://www.empire-machinery.com/equipment/cleat-benders/em-pro-pneumatic-cleat-folders/
You woudl see there are the options in drop down form for bending capacity. But i update woocommerce to 2.4.2, it doesn't show any option... Please see this matter is really serious.

Thanks

**Comment by claudiosmweb** [comment]
https://wordpress.org/support/topic/24-common-issue-variations-missing-on-product-pages?replies=1

**Comment by empiremachinery** [comment]
Thanks. You guys are so quick. Please remain online until i do this. Please its my request. OUr website is big an don't want any issue on this.

**Comment by empiremachinery** [comment]
Thank you very much. You guys are life savers. It helped resolving my issue.

Thanks a lot.

**Comment by claudiosmweb** [comment]
:)

**Comment by empiremachinery** [comment]
On emore prob i testted while putting an order:
Example:http://www.empire-machinery.com/equipment/ironworkers/pre-owned-ironworker/
"Get instant quote" is actually a "add to cart".. after that when i fill a form and submit it..it shows following error. Please check.

SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 127 of the JSON data

**Comment by claudiosmweb** [comment]
https://wordpress.org/support/topic/24-common-issue-syntaxerror-unexpected-token?replies=1
