### ISSUE TITLE
Empty Product Attributes In Order Line Item Details

### ISSUE THREAD

**Issue by rtddev** [woothemes/woocommerce#8796]
Hey Guys,

Ever since the new update, we're now seeing empty product attributes within the line items of the order. These are product attributes for display only on the front end, and not used in product variations.

![image](https://cloud.githubusercontent.com/assets/1872898/9226366/21fde592-40c3-11e5-93e5-abf871fcd3a3.png)

![image](https://cloud.githubusercontent.com/assets/1872898/9226446/9409437a-40c3-11e5-9adf-2e541a9d3c63.png)

Seems as though there is no useful purpose for these being shown in the line items of the order, since they will always be blank.

Is there any business purpose for having this within the order detail? If not, can it be removed? 

Is there any way for us to filter out that information through the API? 

It's rather distracting and also affecting how we display information in our PickingPal interface.

LMK. Thanks.

**Comment by rtddev** [comment]
Note, here is how it shows in our PickingPal interface when we're pulling in the line item detail.

![image](https://cloud.githubusercontent.com/assets/1872898/9227624/6bed5e7a-40c9-11e5-854b-50962580db84.png)

**Comment by mikejolley** [comment]
@rtddev just tested this and only the variation attribute is saved:

https://dl.dropboxusercontent.com/s/h91qlse69sbfa2e/2015-08-12%20at%2017.27.png?dl=0

https://dl.dropboxusercontent.com/s/1tt1kccudo81ncj/2015-08-12%20at%2017.27%20%281%29.png?dl=0

**Comment by rtddev** [comment]
@mikejolley Maybe it's a by-product of pre-existing global product attributes associated to products?

We've had those attributes on our Products since the beginning, and haven't done anything other upgrade to the new version.

I even tried to add a new attribute, save, remove it, then save the attributes again, but that didn't fix it either.

Thoughts?

**Comment by rtddev** [comment]
@mikejolley thx.
