### ISSUE TITLE
Error - Call to a member function has_status() on a non-object

### ISSUE THREAD

**Issue by cryptoapi** [woothemes/woocommerce#8798]
Some our clients receive error -

Fatal error:  
Call to a member function has_status() on a non-object in <b>/home/vpn/www/wp-content/plugins/woocommerce/includes/wc-order-functions.php on line 311

I think it happened when external plugin call - $order->payment_complete(); in some cases.

-----
File wc-order-functions.php have - 
---
	$order = wc_get_order( $order_id );
	if ( $order->has_status( 'processing' ) && get_option( 'woocommerce_downloads_grant_access_after_payment' ) == 'no' ) {
		return;
	}
------

Please change to  -
if ( is_object($order) && $order->has_status( 'processing' ) ....

-----------------
Testing configuration - 
WooCommerce - https://wordpress.org/plugins/woocommerce/
GoUrl Bitcoin Gateway - wordpress.org/plugins/gourl-bitcoin-payment-gateway-paid-downloads-membership/
GoUrl WooCommerce Addon - https://wordpress.org/plugins/gourl-woocommerce-bitcoin-altcoin-payment-gateway-addon/

**Comment by Manojmahajan119** [comment]
Fatal error: Call to a member function has_status() on boolean in woocommerce/templates/order/order-details.php on line 25

**Comment by Manojmahajan119** [comment]
how we are fixed this issue
