### ISSUE TITLE
wc_customer_bought_product issues with previous purchases 2.4.3 

### ISSUE THREAD

**Issue by escobar022** [woothemes/woocommerce#8802]
There seems to be an issue when using the wc_customer_bought_product() function with existing purchases purchased prior to upgrading from 2.3.x. Line 221 below seems to return 0 but not passing.
```php
$transient_name = 'wc_cbp_' . md5( $customer_email . $user_id . $product_id . WC_Cache_Helper::get_transient_version( 'orders' ) );
	if ( false === ( $result = get_transient( $transient_name ) ) ) {...}
```
However, when I removed the validation it worked. And then put it back it worked.

Is it possible that the transients need to be updated on init?

**Comment by mikejolley** [comment]
This is likely cached from before the patch. As soon as you get a new order, get_transient_version will change and the issue will no longer occur going forward.
