### ISSUE TITLE
Cannot remove item in mini cart that hasn't been reloaded in 24 hours

### ISSUE THREAD

**Issue by DustinWoods** [woothemes/woocommerce#8804]
This issue only affects browsers that support html5 session storage.

When a user has fragments stored in html5 storage, the fragments will persist as long as the cookie's cart hash matches the session storage cart hash. The issue is that the fragments likely contain nonce links that will expire in less than 24 hours. After 24 hours, the user will not be able to use the nonce links in the mini cart unless the cart fragments are forced to refresh (ie, cart hash changes).

The solution seems like it was almost implemented; cart-fragments.js will only reload cart fragments with an ajax request if the cart fragments aren't present in session storage, or if the hashes don't match. So we can force refresh the cart fragments by setting an expiration on the cart hash cookie. This is my solution.

I will submit a pull request soon, but all that needs to change is adding an expiration date in set_cart_cookies in class-wc-cart.php. No more than 24 hours would fix the nonce issue.

**Comment by mikejolley** [comment]
@DustinWoods Sounds good to me. Awaiting PR.

**Comment by DustinWoods** [comment]
I've changed my mind how to fix this. I'd rather not expire the cookie, since it may be used for another purpose later. Instead, it would be best to update cart-fragments.js, since we actually want to expire cart fragments.

**Comment by mikejolley** [comment]
Plan: Store expiry in sessionStorage variable, and reload after 24 hours.

**Comment by mikejolley** [comment]
@jeffstieler
