### ISSUE TITLE
Additional characters appearing with URL's inserted at Product Data >> Advanced >> Purchase Note

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#8806]
1. I am inserting the following in the Purchase Note field of the Product Data: ![](http://cld.wthms.co/gk2G/15mB4coU+)

2. Now upon completing the purchase the customer gets the order completion email with the above link with additional characters appended to the end of the URL such as:

![](http://cld.wthms.co/1aZU7/3mvjhXFX+)

In the above email the highlighted link should link to ```http://104.131.116.80/praveen/‎``` but it is linking to  ```http://104.131.116.80/praveen/%E2%80%8E```

**Reference Ticket**

https://woothemes.zendesk.com/agent/tickets/322806

**CC**

@BFTrick @stevetested @slash1andy @tommyshellberg

**Comment by mikejolley** [comment]
No issues my side: https://dl.dropboxusercontent.com/s/umfbraohqxfg8j7/2015-08-13%20at%2016.24.png?dl=0

Field may have had some hidden chars pasted somehow. Re-input the URL/try a different string.
