### ISSUE TITLE
shop_coupon limit_usage_to_x_items

### ISSUE THREAD

**Issue by martin-pettersson** [woothemes/woocommerce#8812]
When the meta field limit_usage_to_x_items is left blank a discount of type product_percent won't apply to all products in the cart but setting it to a value greater or equal to the number of products will.
eg. 999999 will work but 0 (blank) won't.

**Comment by mikejolley** [comment]
Not an issue I can see. Setting to 0 or blank clears the field.

Then coupons apply to all. This example is 10% product discount https://dl.dropboxusercontent.com/s/zze32fl244fiftb/2015-08-13%20at%2016.39.png?dl=0

**Comment by martin-pettersson** [comment]
There must be some other issue I'm overlooking, thanks.
