### ISSUE TITLE
New Update Not Displaying Variations on Frontend

### ISSUE THREAD

**Issue by Fluffyghost** [woothemes/woocommerce#8815]
Hi,

Just updated to the latest version of Woocommerce 2.4.0 from version 2.3.13 and noticed it's not displaying my product variations. 
The variations are all set up in the CMS side, however when selecting them from the front end shop I get a pop up message stating there aren't any products matching those specifications.
I've now had to resort back to version 2.3.13. As soon as I reverted back my product variations are working again.

My website is: http://therooflightsuperstore.co.uk

Thanks,
Sadie

**Comment by mikejolley** [comment]
You've been messing with the files?

> size	
Fatal error: Call to undefined method WC_Product_Variable::get_variation_default_attribute() in /home/roofl266/public_html/wp-content/plugins/woocommerce/templates/single-product/add-to-cart/variable.php on line 32

Revert that to the core version. Its the version in the THEME with the issues too, not the plugin version.

**Comment by Fluffyghost** [comment]
Thanks for the super fast reply! 

I've updated to the latest version 2.4.0 so the core files will have been rewrote to the core.
I've deleted all my over rides and I still get that error.

Can you advise further, still very new to Woocommerce.

**Comment by Fluffyghost** [comment]
Had to revert back, I can't leave it not working as customers may be online. Freaking out as need to update!

**Comment by mikejolley** [comment]
Ok. I'd suggest testing on a separate install if you can. But wait for updates from your theme/plugin authors to ensure you're using compatible versions. We also had some variation fixes in the minor point releases after 2.4.0.

Good luck - ping me if you try again and the above doesn't work for you.

**Comment by Fluffyghost** [comment]
Ok, I will test that out and let you know. :) Thank you. Do you have an email I can message?

**Comment by mikejolley** [comment]
Just reply here @mikejolley and I'll see it.
