### ISSUE TITLE
Add spinner/loading indication between onboarding steps

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8816]
When it sites there doing nothing there is no indication that anything is happen, aside from the loading indicator in the browser. We should block the interface and show a spinner so users know to wait.

**Comment by designsimply** [comment]
Short screencast for reference: [55s](https://cloudup.com/cGPtL3aozKW)
<sup>(It took me ~8s to go from the Page Setup to the Store Locale step—this was probably the longest time between steps in my case/example.)</sup>
