### ISSUE TITLE
Add tooltips to explain 'tax class' and 'tax status' in product admin

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8817]

**Comment by designsimply** [comment]
Screenshot for reference:

<img width="1174" alt="screen shot 2015-08-14 at fri aug 14 5 04 49 pm" src="https://cloud.githubusercontent.com/assets/1119271/9284113/0f66e236-42a7-11e5-9fc9-a42914c06f17.png">
<sup>Seen at http://disambiguously.com/wp-admin/post-new.php?post_type=product&tutorial=true using Chrome 44.0.2403.155 on Mac OS X 10.10.4 hosted at SiteGround.</sup>
