### ISSUE TITLE
WC_Product_Variable::get_children() may return incorrect results, as it looks at their _price meta

### ISSUE THREAD

**Issue by daigo75** [woothemes/woocommerce#8820]
Method `WC_Product_Variable::get_children()` filters out child products that don't have a `_price` meta if the `$visible_only` flag is set. This is probably based on the incorrect assumption that an empty `_price` meta in the database means that the product cannot be purchased, when this is not true. It might work in some cases, but it fails when the product has more than one price, as its additional prices are not stored in `_price`. In this multi-price scenario, products whose price was going to be generated dynamically are discarded before they can be processed by 3rd parties, leading to incorrect results.

Affected code
--
File `class-wc-product-variable`, line 150

~~~
if ( $visible_only ) {
	$args['meta_query'] = array(
		'relation' => 'AND',
		// Price is required
		array(
			'key'     => '_price', // This filter is based on an incorrect assumption
			'value'   => '',
			'compare' => '!=',
		)
	);
	// Must be in stock?
	if ( 'yes' === get_option( 'woocommerce_hide_out_of_stock_items' ) ) {
		$args['meta_query'][] = array(
			'key'     => '_stock_status',
			'value'   => 'instock',
			'compare' => '=',
		);
	}
}
~~~

Solution 1 - Remove the additional check
--
Only check if products are in stock, do not filter based on the `_price` field. This is what WooCommerce 2.3 and earlier did.

Solution 2 - Add a filter to allow 3rd parties to remove the extra check
--
Allow 3rd parties to require the children to be loaded, regardless of the `_price` meta, by adding a filter for the query arguments, as follows:

~~~
if ( $visible_only ) {
	$args['meta_query'] = array(
		'relation' => 'AND',
		// Price is required
		array(
			'key'     => '_price',
			'value'   => '',
			'compare' => '!=',
		)
	);
	// Must be in stock?
	if ( 'yes' === get_option( 'woocommerce_hide_out_of_stock_items' ) ) {
		$args['meta_query'][] = array(
			'key'     => '_stock_status',
			'value'   => 'instock',
			'compare' => '=',
		);
	}
}

$this->children[ $key ] = get_posts( apply_filters( 'woocommerce_get_children_query_args', $args, $this, $visible_only ) );
~~~
This would be a bit complicated for 3rd parties to handle, as the structure of the `meta_query` array is not easy to parse and manipulate, but it would still allow to alter the criteria to retrieve the data.

**Comment by mikejolley** [comment]
@daigo75  I believe _price has always been a requirement. How does the plugin in question handle things like price filters?

For products which don't have price, e.g. variable, we always set _price to something such as min variation price.

In fact, we're talking about variable products here. So get_children pull variations and PRICE is required for variations. Are you extending variable products, and if so, why don't you have your own get_children method?

**Comment by daigo75** [comment]
The price is a requirement, but the field itself may not be, as there may be more than one, and some of them could be calculated dynamically. The fact that there isn't a value stored in one field, it doesn't mean that the value corresponding to that field will be empty. I will take a screenshot of a settings page, what I mean will be clearer.

**Comment by mikejolley** [comment]
@daigo75 there is no 'price' field. its set based on regular or sale price. And that is clearly marked required in the UI

**Comment by daigo75** [comment]
I know that, I've been working with it for years now. And, yet, the price it can be empy in the database, and the product still have a price, as another price will be used generate that missing value. Perhaps this screenshot will make things clearer: http://i.imgur.com/wQSAuCI.png.

**Comment by daigo75** [comment]
Speaking of raw data, `_regular_price`, `_sale_price` and `_price` are all empty. This, however, does not mean that the product doesn't have a price. It **does** have one, which is calculated on the fly from another one, instead of being retrieved from the database.

This function is invaluable to merchants who buy in multiple currencies and sell in another. For example, they buy from supplier A in USD, from supplier B in EUR and from supplier C in GBP, but they want to sell in EUR. What they do is, simply:
- Set shop's base currency to EUR (this is where the original regular and sale prices are stored, and are left blank).
- Products from supplier A: set base currency to USD, apply sale markup to purchase price and enter USD price.
- Products from supplier B: set base currency to EUR, apply sale markup to purchase price and enter EUR price.
- Products from supplier C: set base currency to GBP, apply sale markup to purchase price and enter GBP price.

All EUR prices, for all products, will be calculated dynamically. They are "empty" in the database for products from suppliers A and C, but they are populated on the fly for customers, when they reach the site.

**Comment by daigo75** [comment]
Bottom line: I agree that a product must have a price to be purchasable. This is a functional requirement. The issue, instead, is technical, as such required price may not be stored in a specific location in the database. Therefore, the filtering cannot always be done directly on the query. It's simple, actually :)

**Comment by daigo75** [comment]
By the way, adding a filter for the query would also make things more consistent, as there is already a similar logic implemented for class `WC_Product_Grouped`.

~~~
$args = apply_filters( 'woocommerce_grouped_children_args', array(
	'post_parent' 	=> $this->id,
	'post_type'		=> 'product',
	'orderby'		=> 'menu_order',
	'order'			=> 'ASC',
	'fields'		=> 'ids',
	'post_status'	=> 'publish',
	'numberposts'	=> -1,
) );
~~~

**Comment by mikejolley** [comment]
If you want to submit a PR for filtering the query, go ahead.

**Comment by mikejolley** [comment]
cc @claudiosmweb to review

**Comment by daigo75** [comment]
Ok, will do.
