### ISSUE TITLE
WooCommerce 2.4.4

### ISSUE THREAD

**Issue by whitemint** [woothemes/woocommerce#8824]
Hi
We have the latest version of woocommerce installed with a "Store" theme.

when proceeding to the payment gateway (Mijreh & Paypal) we get the following error

"•We were unable to process your order, please try again."

any ideas what would cause this and how to fix it?

Thanks

**Comment by mikejolley** [comment]
Your theme is causing it; there are missing "nonces" on your checkout page. Switch themes/check for updates.
