### ISSUE TITLE
hide unavailable veriations from dorpdown

### ISSUE THREAD

**Issue by AGDesignStudio** [woothemes/woocommerce#8825]
Hi, I have a a small issue with product variations, The site is using the latest WordPress and WooCommerce..

We have two dropdowns on a product page: Size and colour.
The sizes go from XS to 4XL and there is a selections of different colours..

The issue is on the product size 4XL for example only four colours are available for that size (there is 14 to pick from)

When 4XL is selected all 14 colours are in the dropdown.. but when you select the colour (a colour that is not set for that size) and add to the basket we get this Woo error note "Please choose product options.."

What should happen is the unavailable colours should not be viable in the dropdown..

Has anyone got any ideas how to fix? 

I tried the grey_out_variations_when_out_of_stock function but no joy.

Thanks.

Aaron

**Comment by mikejolley** [comment]
If there are greater than 20 variations in the product, it will use ajax to find matches and won't hide combinations (because doing so would mean loading all variations before display).

**Comment by AGDesignStudio** [comment]
Hi Mike, thanks for the super quick reply..

There is about 150 for this said product...

Is there a work around for this?

Thanks

**Comment by mikejolley** [comment]
https://gist.github.com/claudiosmweb/6f91ad228c2176b986b2

But will be slower. Change to 150.

**Comment by AGDesignStudio** [comment]
Thank you Mike!! a true super star!! Works like a charm!

**Comment by harkalygergo** [comment]
Claudio’s nickname changed to claudiosanches, so the required link: https://gist.github.com/claudiosanches/6f91ad228c2176b986b2

**Comment by rahulkhosla** [comment]
Found a useful guide on [making the variations work](https://wpza.net/unavailable-variations-wont-hide-in-woocommerce/).

I hope it helps others too!
