### ISSUE TITLE
star rating on the review form

### ISSUE THREAD

**Issue by jameskoster** [woothemes/woocommerce#8826]
They're currently 5 separate buttons. This was the best solution given the browsers we were supporting at the time.

Since IE10 now has only .8% market share, and IE11 4.2% we can probably revisit this.

http://www.w3schools.com/browsers/browsers_explorer.asp

**Comment by paulwilde** [comment]
FWIW: w3schools isn't a good indicator of browser marketshare as the statistics come from their own website, and the website has a major website development demographic which would have a modern browser bias.

[Statcounter](http://gs.statcounter.com/#all-browser_version-ww-monthly-201506-201506-bar) would probably be a better indication.
