### ISSUE TITLE
Removing sale price via REST API not possible

### ISSUE THREAD

**Issue by oscware** [woothemes/woocommerce#8828]
We tried to remove the sale_price from a product with the REST API. Therefore we are sending a null-value (PUT Request) for this field. Unfortunately null-values are ignored, other values are working correctly. Here is our request:

Not working:
{
  "product": {
    "id": 59,
    "sale_price": null
  }
}

Working:
{
  "product": {
    "id": 59,
    "sale_price": 5
  }
}

The problem is the file: includes/api/class-wc-api-products.php in function save_product_meta on line 944:

// Sale Price
if ( isset( $data['sale_price'] ) ) {
	$sale_price = ( '' === $data['sale_price'] ) ? '' : wc_format_decimal( $data['sale_price'] );
	update_post_meta( $product_id, '_sale_price', $sale_price );
} else {
	$sale_price = get_post_meta( $product_id, '_sale_price', true );
}

You are checking with "isset( $data['sale_price'] )" if a sale_price is defined in the $data array AND if it is not null. This is wrong because null is a valid value. Instead you should use "array_key_exists( 'sale_price', $data )" that only checks if the key is available.

Correct code:

// Sale Price
if ( array_key_exists( 'sale_price', $data ) ) {
	$sale_price = ( '' === $data['sale_price'] ) ? '' : wc_format_decimal( $data['sale_price'] );
	update_post_meta( $product_id, '_sale_price', $sale_price );
} else {
	$sale_price = get_post_meta( $product_id, '_sale_price', true );
}

**Comment by claudiosmweb** [comment]
Just use a empty string:

```json
{
	"product": {
		"id": 59,
		"sale_price": ""
	}
}
```

**Comment by oscware** [comment]
It's a possible way, but in my eyes not the correct one. I think only null and numeric values should be allowed, an empty string is not a valid value. I recommend to use 'array_key_exists'.

**Comment by claudiosmweb** [comment]
@oscware thanks for your input, but we'll keep it that way for now.

**Comment by mbrn01** [comment]
Just found it. Put Sale price the same as regular price. This way, it removes the sale price as they are the same.

**Comment by turpoint** [comment]
I've tried `""`, `false` and `null`. None of these seem to work. The API call itself works if i put `3.00` as a string it gets updated, but I can't find a way to remove the sale price.

**Comment by Monu-ghorela** [comment]
> Just found it. Put Sale price the same as regular price. This way, it removes the sale price as they are the same.

will it work?
