### ISSUE TITLE
Variations Bug - All Variations Load Even If Not Available With A Specific Selection

### ISSUE THREAD

**Issue by SERVICEFREAKS** [woothemes/woocommerce#8832]
Previously WooCommerce would remove non-available selection dependent upon your current selections. This functionality is extremely helpful to the customer especially to not have confusion of the available options depending on other selections.

Please fix this bug ASAP

**Comment by claudiosmweb** [comment]
Please: 
![screenshot from 2015-08-15 18 01 34](https://cloud.githubusercontent.com/assets/1264099/9290836/b15b84ae-4377-11e5-9f86-4779facc18b7.png)

**Comment by claudiosmweb** [comment]
And check it: https://woocommerce.wordpress.com/2015/07/13/improving-the-variations-interface-in-2-4/

**Comment by SERVICEFREAKS** [comment]
There is an issue still even with this option selected.

When I select 14pt/100lb paper option there are different quantity options available and this causes issues because ALL quantity options appear even if they are non-existent.

Please advise as this issue did NOT exist prior to the new 2.4 woocommerce

**Comment by claudiosmweb** [comment]
> And check it: https://woocommerce.wordpress.com/2015/07/13/improving-the-variations-interface-in-2-4/

If you have more than 20 variations, all will be loaded and will be checked by ajax content of each.
This was done to improve the performance of product pages with many variations.

**Comment by SERVICEFREAKS** [comment]
Is there a way I can manage this? It will confuse customers because quantities are not available in all options….

**Comment by claudiosmweb** [comment]
>And check it: https://woocommerce.wordpress.com/2015/07/13/improving-the-variations-interface-in-2-4/

If you read this post, yes, I'll find a way ;)

**Comment by SERVICEFREAKS** [comment]
I really like Ajax could you put in for us to be able to manage ajax by attribute field instead of by number of variations?

This would be really helpful for performance issues but still allow us to not have the changing attribute options based on selections modify as needed.

**Comment by tavoweb** [comment]
hello so how to solv the problem then adding more then 30 variations in front end showing all posible variations ..
