### ISSUE TITLE
Subscription Coupon Issue in Checkout

### ISSUE THREAD

**Issue by JaWeyer** [woothemes/woocommerce#8836]
I went through the whole recommended troubleshooting process on my local machine to no avail last night. Disabled all plugins, reverted to base theme. 

Basically the issue I'm running into is a problem with a Cart % discount being applied in /checkout when there is a single recurring subscription product (Not a synchronized subscription, which is not supported!)

Oddly enough the discount will apply when a user is on the /cart page. It will also apply on the /checkout page when there is a non-recurring item in the cart. The coupon code entered is also appearing in the WC->cart() object when dumped on the page, but is not applying.

If I'm being dumb and missed something blatant please tell me, otherwise I think it might be a bug.

**Comment by claudiosmweb** [comment]
@JaWeyer better report it on http://support.woothemes.com/ since is a subscription issue.

**Comment by JaWeyer** [comment]
That was where I started and they sent me here...

**Comment by JaWeyer** [comment]
Any help on this @claudiosmweb? I've been redirected by both you and the support staff on the error.
