### ISSUE TITLE
Product thumbnails layout changed after 2.4.4 update

### ISSUE THREAD

**Issue by farhan511** [woothemes/woocommerce#8837]
I have just updated woocommerce to 2.4.4 and my products thumbnails on shop page and everywhere looking disturbed.
This is shop page view after update
![products archive youtube bulk views](https://cloud.githubusercontent.com/assets/7799228/9282679/938eedd4-42e7-11e5-843b-38599d53a771.png)

This is another page
![facebook likes youtube bulk views](https://cloud.githubusercontent.com/assets/7799228/9282728/f887ae7e-42e7-11e5-8758-0eabb49b53da.png)

However homepage thumbnails are looking fine.
![home youtube bulk views](https://cloud.githubusercontent.com/assets/7799228/9282745/11b54a3c-42e8-11e5-8761-bd47f63fbe87.png)

**Comment by claudiosmweb** [comment]
Sorry, but we did any changes that could influence with thumbnails.
Try to activate another theme or go disabling your plugins one by one.
