### ISSUE TITLE
Google rich snippets not working for Variable products

### ISSUE THREAD

**Issue by bhouszka** [woothemes/woocommerce#8840]
Hi,

Wanted to verify Google rich snippets for my variable products. It did not pass through. Here is a screenshot
![image](https://cloud.githubusercontent.com/assets/3737755/9289248/b459f9aa-4369-11e5-9f88-fc660aaaa998.png)
I believe you could make it display the price of default variation.

Reards
Bogusz

**Comment by mikejolley** [comment]
Seems to be a theme issue/out of date template or invalid data.

https://github.com/woothemes/woocommerce/blob/5ef335b169ff4e19a4c5b393963a369446922b0c/templates/single-product/price.php#L21

This uses get_price(). For variable products this is set to the price of the cheapest variation. Confirmed this works, and checked rich snippet validator.

**Comment by bhouszka** [comment]
OK, thanks I will talk to theme support.
