### ISSUE TITLE
Query parameter for product search returns erroneous api authentication error

### ISSUE THREAD

**Issue by murdockcrc** [woothemes/woocommerce#8842]
I am using the NodeJS SDK to interact with the lastest version of WooCommerce (2.4.4, API v3).

Issue: I run the following query against the API:
```javascript
var queryUrl =  util.format('products?filter[q]=%s&filter[limit]=500', encodeURIComponent(displayName));
	debug(queryUrl);
	_wooHelper.get(queryUrl, callback);
```
This returns the following error:
```
"errors": [
        {
            "code": "woocommerce_api_authentication_error",
            "message": "Invalid Signature - provided signature does not match"
        }
    ]
```

However, if I remove the limit filter, the API returns the expected result. This is the code that works:
```javascript
var queryUrl =  util.format('products?filter[q]=%s', encodeURIComponent(displayName));
	debug(queryUrl);
	_wooHelper.get(queryUrl, callback);
```

By trial and error with this query, I have not been able to find a way to add the LIMIT filter without the systems return the api_authentication error. So the purpose of this issue submissions is to report that a) the API is returning an api_authentication error, when this seems not to be the problem and b) it seems one cannot mix the LIMIT filter with other parameters in a search query.

**Comment by claudiosmweb** [comment]
Use the Node SDK repo for report this kind of issues.

**Comment by murdockcrc** [comment]
OK, reported on the nodejs repo. Thanks.
