### ISSUE TITLE
bulk image update not updating

### ISSUE THREAD

**Issue by christechno25** [woothemes/woocommerce#8843]
Hi everybody. I am using v3 REST API of Woocommerce. One of the nicest things added is the ability to update in bulk. Everything works fine when adding a new set of products, but when I update the images for an existing product, nothing gets updated. Say I previously saved 3 images and now I'm updating it to have only 2 images, the update does not return any error and my JSON is all correct but it does not update the image count. It does update a changed featured image but that's it. Is there ant fix on this? Thank you!

**Comment by mikejolley** [comment]
#8853
