### ISSUE TITLE
Create/Update Multiple Products Image Hotlinks Prevent automatic save to Uploads folder

### ISSUE THREAD

**Issue by christechno25** [woothemes/woocommerce#8844]
Hi everybody. I have a server that contains all the images for my products. When I create a product using the API and pass on hotlinks images for products the images automatically get saved in the official wordpress media folder. I don't want this to happen. I checked the image sources and even if I gave the hotlinks, the product images point to the official wordpress media folder. Is there any way I can prevent this and just stay with my dedicated image server? Thank you!

**Comment by mikejolley** [comment]
WordPress will do this by default for any image; to be an attachment it imports into the media library.

If you try to 'set featured image' manually, you'll see the only options are to upload or choose an existing image from the library. So I don't think its possible.

If you're trying to do this for performance, use a CDN plugin.

**Comment by christechno25** [comment]
Thank you so much for this answer Sir.
