### ISSUE TITLE
Option to prevent wc_create_new_customer triggering woocommerce_created_customer action

### ISSUE THREAD

**Issue by SteveHoneyNZ** [woothemes/woocommerce#8845]
I'll detail the use case where I ran into this issue and reasoning behind proposed fix. I appreciate it's an edge-case but I can imagine developers of other plugins/3rd party applications running into similar issues so believe it warrants a discussion at least. 
I'm fairly new to this so please accept my apologies in advance if I'm being short sighted or this change would cause issues I've not foreseen.

In a scenario where customer data is being push+pulled between WC and a 3rd party app (in my case Vend) when the `wc_create_new_customer` function is used by the 3rd party app via the plugin then the internal  WC `woocommerce_created_customer` action is triggered. 

This presents the problem that `woocommerce_created_customer` is also the obvious action to hook in order to sync customer creation in the opposite direction. So it is impossible to create the new customer in WC without un-necessarily triggering the action to then sync the data in the opposite direction.

In order to mitigate for this set up I propose extending the `wc_create_new_customer` function to have a 4th argument of `$prevent_action` set to `false` by default and conditionally check before firing the action. By then setting this argument to `true` when calling the function we can prevent the action being fired. This is a lot more concise than basically replicating the entire `wc_create_new_customer` function in a plugin.

It also allows other plugins to make use of the `$prevent_action = true` option to use `wc_create_new_customer` without triggering the `woocommerce_created_customer` action if they wish.

Any current use of `wc_create_new_customer` wouldn't be impacted as the default behavior remains exactly as it is.

**Comment by mikejolley** [comment]
This would prevent other scripts from detecting new users with the hook.

**Comment by SteveHoneyNZ** [comment]
Yep in hindsight it probably would have too many potential issues with other plugins then not detecting the new user...
Feel free to close.

**Comment by strarsis** [comment]
So rather unhook the email sending action before invoking `wc_create_new_customer` ?
