### ISSUE TITLE
Changing review stars size causes issues

### ISSUE THREAD

**Issue by bhouszka** [woothemes/woocommerce#8847]
Hi,

When I have increased size of the review stars say to 18px the number of stars was not reflecting the real number. It was supposed to be 4.5 and it was showing something like 3.1. Would be nice if the algorythm was taking into account the star size.

Regards
Bogusz

**Comment by jameskoster** [comment]
It should do, everything is set in `em`. Try using that as your font size unit.

https://github.com/woothemes/woocommerce/blob/master/assets/css/woocommerce.scss#L824
