### ISSUE TITLE
""PHP Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version."

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8848]
https://wordpress.org/support/topic/automatically-populating-http_raw_post_data-is-deprecated?replies=3

`
if ( ! isset( $HTTP_RAW_POST_DATA ) ) {
	$HTTP_RAW_POST_DATA = file_get_contents( 'php://input' );
}
`

This code is in the API classes and may be responsible.

@maxrice @claudiosmweb

**Comment by claudiosmweb** [comment]
I just read this:
> Warning: This feature has been DEPRECATED as of PHP 5.6.0 and REMOVED as of PHP 7.0.0.

And this:

>  In general, `php://input` should be used instead of `$HTTP_RAW_POST_DATA`.

Ref: http://php.net/manual/en/reserved.variables.httprawpostdata.php

So I'll follow the documentation :)

**Comment by claudiosmweb** [comment]
Another note about it: http://php.net/manual/pt_BR/ini.core.php#ini.always-populate-raw-post-data

> Always populate the `$HTTP_RAW_POST_DATA` containing the raw POST data. Otherwise, the variable is populated only with unrecognized MIME type of the data. However, **the preferred method for accessing the raw POST data is php://input**. $HTTP_RAW_POST_DATA is not available with enctype="multipart/form-data".

**Comment by claudiosmweb** [comment]
And here: http://php.net/manual/en/wrappers.php.php#wrappers.php.input xD

> `php://input` is a read-only stream that allows you to read raw data from the request body. In the case of POST requests, it is preferable to use `php://input` instead of `$HTTP_RAW_POST_DATA` as it does not depend on special php.ini directives. Moreover, for those cases where `$HTTP_RAW_POST_DATA` is not populated by default, it is a potentially less memory intensive alternative to activating `always_populate_raw_post_data`. `php://input` is not available with enctype="multipart/form-data".

**Comment by claudiosmweb** [comment]
`always_populate_raw_post_data` is disabled by default:

![screenshot from 2015-08-17 12 47 18](https://cloud.githubusercontent.com/assets/1264099/9309139/20746768-44de-11e5-97bb-5b32fbc8de76.png)

All this time we have used almost always `php://input`...

**Comment by maxrice** [comment]
SHA a12552dbf18f7ac021fc221737db75f2469196c4 looks good, the one thing to consider is that if another plugin reads `php://input` prior to WC and *does not* set the global, `php://input` will be empty. As of PHP 5.6, the input stream can be re-read but in versions prior to that we might consider reading the global first, and then `php://input`.

**Comment by claudiosmweb** [comment]
@maxrice ^

**Comment by maxrice** [comment]
:heart:

**Comment by vinamelody** [comment]
Hi, what's the solution for this? I'm using the latest woocommerce but error_log still output this lines
