### ISSUE TITLE
2.4 All variable products on sale now display as free since upgrade

### ISSUE THREAD

**Issue by Wildebees** [woothemes/woocommerce#8849]
Upgraded to latest version this morning, but all variable products (available in three currencies) on sale now display as FREE.

Products that are not on sale work normally.

**Comment by mikejolley** [comment]
What is handling multi-currency? May be that  -we only handle one in core.

**Comment by Wildebees** [comment]
I am using Aelia Currency Switcher for WooCommerce. It might be that, but all the products not on sale display prices correctly.

**Comment by mikejolley** [comment]
If you turn that off, does an on-sale product display correctly?

**Comment by Wildebees** [comment]
Correct, it seems to solve the issue.

**Comment by Wildebees** [comment]
Thanks for you help, Aelia support is in contact with me.

**Comment by mikejolley** [comment]
:+1:

**Comment by daigo75** [comment]
All done, thanks @mikejolley :+1:
