### ISSUE TITLE
No email confirmation after payment is done.

### ISSUE THREAD

**Issue by bhouszka** [woothemes/woocommerce#8850]
Hi,

Try to configure the emails and I found following issue:

1. When I place an order and set "pay on delivery" as payment option order is automatically  in processing  status and the proper mail is sent.

2. When I place an order and set "bak transfer" as payment option, order is set to on hold and an email is sent to customer saying it is being processed. This is totally not true as it is waiting for payment and not being proccessed.

So here is possible solution:

I rename "order in progress" emails to someting like "new order confirmation". In payment options I could adtionally describe that for "pay on delivery" the order is already in progress and for "bank transfer" we are waiting for money. But when I get the payment throught bank tranfer, I will move the status from "on-hold" to "in progress" and I want woocommerce to send an email to customer that we have received the payment and order is in progress now. 

**There is no such email currently and I strongly recommed you should add it.**

Regards
Bogusz

**Comment by mikejolley** [comment]
I think processing is still valid wording for this. It's a confirmation that the order is on the system.

BACS has a setting to add extra details with payment instructions to this email - use that to add the instructions.
