### ISSUE TITLE
Limit one review per customer account

### ISSUE THREAD

**Issue by samadmalik** [woothemes/woocommerce#8852]
Hi. After purchasing any product from my site, the verified owner can rate that product multiple times. That doesnt make sense. How can I fix it?

**Comment by mikejolley** [comment]
Log on ideas.woothemes.com if you'd like to see an option in the plugin itself.

Right now you can adjust the single-product-reviews.php template file and add a conditional check. http://wordpress.stackexchange.com/questions/137799/how-to-limit-users-to-one-comment-per-post
