### ISSUE TITLE
How to delete gallery images of a product

### ISSUE THREAD

**Issue by christechno25** [woothemes/woocommerce#8853]
Hi everybody, I've been working on this for 2 weeks and this is the only thing left unsolved. How do I delete gallery images of a product? I tried updating images using the API like say the product already has 2 images and I'd like to remove one by sending only 1 image source under the image array, but when I check product information the gallery images are all still there and the only way it works is by manually deleting it through the browser. How do I do this via the API? Thank you very much.

**Comment by claudiosmweb** [comment]
You can use:

```json
{
  "product": {
    "images": ""
  }
}
```

This will remove all images.

Or you can make a GET query, pick up the current image data and send it back without images you do not want anymore.

**Comment by christechno25** [comment]
Hello Sir, thank you for the reply. I actually did what you suggested. I sent a JSON string with just the images that I want but still not 1 image gets removed :( So say I already have 3 images of the product and I resend a JSON string that contains only 2 images, the 3rd image still does not get removed. Am I doing it right? Thank you!

**Comment by itphil** [comment]
Hello,

I'm sending an empty string for images to the API, but there are no images deleted.
How can I delete product images?

**Comment by mgm5089** [comment]
We are using v1 of rest API and have same issue as @itphil

**Comment by itphil** [comment]
@mgm5089 Hello Mike, we resolved the problem downloading and installing the newest version of WooCommerce here from github.

**Comment by vinigarcia87** [comment]
I got the same error.
Can't delete any images :S

**Comment by ValerioFR** [comment]
Hi guys, I have same issue.... if I want to delete an image I send images without that but not do nothing. Any ideas?

**Comment by mgm5089** [comment]
You can use the latest version on github where this bug is fixed.
