### ISSUE TITLE
No values for Gross and Net sales in reports

### ISSUE THREAD

**Issue by aerialreports** [woothemes/woocommerce#8854]
I'm able to see the dollar amount of total sales for this month on the dashboard but when I go to the reporting option, it does'nt show any value for Gross sales or Net sales for either weekly/monthly/yearly tabs. It shows $0.00 in all rows. Custom dates or Export to CSV has $0.00 as well.
![sales this month](https://cloud.githubusercontent.com/assets/13825315/9297116/1d7dba8a-4468-11e5-8964-87025e5a6c09.PNG)
![this year](https://cloud.githubusercontent.com/assets/13825315/9297117/1f0be2aa-4468-11e5-91d2-27dcd17258d0.PNG)

**Comment by mikejolley** [comment]
What status do your orders have?

Does saving an order flush the report cache for you and fix display?

**Comment by aerialreports** [comment]
Orders are delivered and in completed state. the reporting feature worked flawlessly last financial year. 
The dashboard will display the sales for this month accurately and as soon as the month ends, there's no way to look at last month's sale.

Didn't quite understand your second question "Does saving an order flush the report cache for you and fix display?"

**Comment by mikejolley** [comment]
Whats with the big refund spike? Almost looks as though the orders in that range were wiped?

**Comment by aerialreports** [comment]
Nah, that's not the case. Refund is just $200 for that month. It shows $0.00 for the entire year and past year. It used to work because i used this information in march 2015 while filing for tax returns. It has stopped working for the past 3 months with one of the updates.

**Comment by mikejolley** [comment]
Are you able to send me access for this? Email mike.j@woothemes.com

**Comment by aerialreports** [comment]
i'll create an account for you and send you login details to your email

**Comment by aerialreports** [comment]
check your inbox and let me know if you are unable to access. 
www.aerialreports.com

**Comment by mikejolley** [comment]
I got it.

**Comment by mikejolley** [comment]
I don't have access to the plugins section; have you ruled out conflicts yet?

**Comment by aerialreports** [comment]
you have shop manager access. do you want admin access?
 what does ruled out conflicts mean?

**Comment by mikejolley** [comment]
@aerialreports yes. Ruled out by disabling other plugins.

**Comment by mikejolley** [comment]
@aerialreports news?

**Comment by aerialreports** [comment]
yes, ruled out by disabling other plugins

**Comment by mikejolley** [comment]
Can you update the account you sent to view that section?

**Comment by aerialreports** [comment]
Its a live in production website. I'm updating the account in 5 min.

**Comment by aerialreports** [comment]
![1](https://cloud.githubusercontent.com/assets/13825315/9412254/be1ff802-47f8-11e5-93d6-5b7b4131d40f.PNG)
![2](https://cloud.githubusercontent.com/assets/13825315/9412256/c024c9e8-47f8-11e5-8008-48e62ccd4a89.PNG)

**Comment by aerialreports** [comment]
Done. let me know if you are making any changes

**Comment by mikejolley** [comment]
You know running 'pirate' plugins is dangerous right :) Never know whats been changed. In fact thats pretty careless on a production site.

**Comment by mikejolley** [comment]
@aerialreports I need to do some testing on the queries to see if they are actually pulling data. If you can mail FTP access please do. I don't want to do it via the backend editor.

**Comment by aerialreports** [comment]
Sure, Can you elaborate on the plugins that you mentioned? I had a someone manage my site earlier and took over the control  sometime back. Let me know what needs attention and i'll get it right asap.
I'll setup your FTP account in 5 min.

**Comment by mikejolley** [comment]
Please email it through.

**Comment by mikejolley** [comment]
Closed due to lack of feedback.

If its any help, just dealt with a similar issue on woo support and it was caused by custom order statuses not having the 'include in reports' checkbox checked.

**Comment by getta310** [comment]
I'm having this same issue. Tried in WooCommerce v2.4.8 as well as the latest v2.5.5. I have removed all other plugins so there isn't a conflict. WordPress is up to date.  I'm not sure what could be the cause.
