### ISSUE TITLE
[2.4.4] Postal code on checkout is not required field anymore

### ISSUE THREAD

**Issue by gerdneuman** [woothemes/woocommerce#8857]
After updating to 2.4.4 on the checkout page the fields `billing_postcode` and  `shipping_postcode` are not mandatory anymore. They were before. I cannot find any information about this change (and also no information about how to get back the old behaviour). 

Also (at least for Germany) this is absolutely wrong: The zip/postal code is a totally required field, otherwise shipping is impossible. 

Googling for the issue just reveals one (unanswered) [support request](https://wordpress.org/support/topic/postal-code-required-field) for this (not by myself ;)

**Comment by ChromeOrange** [comment]
@mikejolley looks like it happens to any country with 

```
'postcode_before_city' => true,
```
