### ISSUE TITLE
Set variable product virtual by default

### ISSUE THREAD

**Issue by pawelkmpt** [woothemes/woocommerce#8858]
I'm wondering if it's possible to set variable product as virtual by default. I found the way to do that with simple product (`product_type_options` filter), but the same thing for variable products seems to be currently not possible.

What I've found so far is `woocommerce_create_product_variation` action in `WC_AJAX::add_variation()` might be a good place to somehow deal with it. I was thinking that I could use following code in this action: `add_post_meta( $variation_id, '_virtual', 'yes' )`, as in one of the further lines all post meta are retrieved from db, than passed to `html-variation-admin.php` and exploded there.

Unfortunately it doesn't help, because value in `$variation_data` for `_virtual` key is `array( 'yes' )` instead of just `yes` string, what simply means that this value was not unserialized.
Comparing it to `WC_AJAX::load_variations()` - all retrieved meta values are unserialized (line 2530) before using them in template.

Any idea how I could achieve virtual by default?

**Comment by mikejolley** [comment]
Use the woocommerce_create_product_variation action, and use add_post_meta so its only added once.

**Comment by pawelkmpt** [comment]
Well, yeah it'll be set as virtual, but checkbox is still unchecked and this is what I wanted to achieve.

**Comment by lemoslincoln** [comment]
@pawelkmpt , You could make this work?

**Comment by pawelkmpt** [comment]
Yes, but I achieved it using `woocommerce_product_after_variable_attributes` hook and invoking there JavaScript function which sets the checkbox checked.

**Comment by lemoslincoln** [comment]
Can you share the code? My javascript is sux!

**Comment by pawelkmpt** [comment]
```
// This sits in my plugin .php file
public function my_woocommerce_product_after_variable_attributes( $loop, $variation_data, $variation ) {
    echo <<<SCRIPT
    <script>
    setupVariation($loop);
    </script>
SCRIPT;
}

add_action( "woocommerce_product_after_variable_attributes", "my_woocommerce_product_after_variable_attributes" ), 10, 3 );
```

```
// this is JS
setupVariation = function( variationId ) {
    $( 'input[name="variable_is_virtual[' + variationId + ']"]' ).attr( 'checked', 'checked' ).trigger( 'change' );
}
```
