### ISSUE TITLE
Not able to Manage Category Hierarchy while creating Department/Category/Subcategory

### ISSUE THREAD

**Issue by manojtiwari007** [woothemes/woocommerce#8859]
Hi,

While working with Woocommerce API, we are not able to create/update Category Hierarchy like Department/Category/Subcategory.

**Comment by claudiosmweb** [comment]
It's not possible.
We will try to implement in WooCommerce 2.5.

**Comment by gspereira** [comment]
Im very new to woocommerce and php .. but it looks like this might be related to the api/class-wc-api-products.php page where it says :

                // Product categories
                if ( isset( $data['categories'] ) && is_array( $data['categories'] ) ) {
                        $term_ids = array_unique( array_map( 'intval', $data['categories'] ) );
                        wp_set_object_terms( $product_id, $term_ids, 'product_cat' );
                }

                // Product tags
                if ( isset( $data['tags'] ) && is_array( $data['tags'] ) ) {
                        $term_ids = array_unique( array_map( 'intval', $data['tags'] ) );
                        wp_set_object_terms( $product_id, $term_ids, 'product_tag' );
                }

I think it should be $data['categories'] or $data['tags'] being given as a parameter to wp_set_object_terms instead of $term_ids

**Comment by claudiosmweb** [comment]
Fixed by #9100
