### ISSUE TITLE
String used as array

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8861]
In class-wc-ge-ip.php on line 1517 we use `$buf` as an array but it seems to be a string instead.
This could return errors on some websites, like

> Notice: Uninitialized string offset: 0 in public_html/woo/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1517

**Comment by claudiosmweb** [comment]
Not really a string. 

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-geo-ip.php#L1511

Maybe this is just the symptom of not having downloaded `GeoIPv6.dat` file.
You need to check for other error messages because only with that particular line everything is ok.

**Comment by SiR-DanieL** [comment]
The error is that the file is missing. I'm investigating more to check why it's not downloaded. We can close this issue for now. I'll reopen it if the issue is with WooCommerce. Thanks @claudiosmweb
