### ISSUE TITLE
woocommerce update 2.4 variation problems

### ISSUE THREAD

**Issue by NaterFocus** [woothemes/woocommerce#8863]
After updating to Woocommerce 2.4 and up, my variations have stopped working. 
I've seen others having this problem as well. The site is at www.natermusic.com for now while it is in development.

I tried deactivating the other plugins & changed the theme to 2015 but that did not help. I am currently using the Ultra theme by Themify. I did not deactivate FoodPress, as we need that for the orders, could that be the problem?

I searched for yourtheme/woocommerce/single-product/add-to-cart/variable.php and couldn't find it. These are the files I have with variable.php in the title. 

/public_html/natermusic/wp-content/plugins/foodpress-onlineorder/templates/template-add-to-cart-variable.php
	
/public_html/natermusic/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php
	
/public_html/natermusic/wp-content/plugins/woocommerce/templates/single-product/add-to-cart/variable.php

Reverting to 2.3.13 fixed the problem... For now. But I would like to keep current on updates if possible. This site is still in development, but needs to be off the ground by next month.

Thanks for any help you can give.

**Comment by mikejolley** [comment]
templates/template-add-to-cart-variable.php sounds suspect. If changing themes fixes the issue, which it sounds like in your case, the theme author needs to release an update.

**Comment by NaterFocus** [comment]
I changed themes, and that did NOT fix the issue.

**Comment by mikejolley** [comment]
Changed to...?

**Comment by NaterFocus** [comment]
I changed it to the 2015 theme.

**Comment by mikejolley** [comment]
^

**Comment by mikejolley** [comment]
This: https://dl.dropboxusercontent.com/s/y6qs76tomp201s1/2015-08-19%20at%2011.48.png?dl=0

Is a custom variation form. It is not compatible. I assume thats foodpress? It needs an update to work with the variation data structure in 2.4.

**Comment by NaterFocus** [comment]
Yes. That was exactly it, I just found this on Foodpress' support site today. 
http://support.ashanjay.com/topic/foodpress-and-woocommerce-2-4-x/
