### ISSUE TITLE
proceed to checkout button is not a button

### ISSUE THREAD

**Issue by SanderKers** [woothemes/woocommerce#8865]
Dear sir/madam,

After the latest update of woocommerce the proceed to checkout button at the 'cart' page disappeared. It changed just into 'words', so you really have to search for it. Is there something I can change in the .php file?

Kind regards,

Sander

![proceed to checkout button](https://cloud.githubusercontent.com/assets/13840696/9316805/abf0e420-4537-11e5-8c6b-0d77ffe2b3c5.png)

**Comment by mikejolley** [comment]
Responded on .org.
