### ISSUE TITLE
Webhook not working

### ISSUE THREAD

**Issue by sfabriece** [woothemes/woocommerce#8867]
I have a setup woocommerce on godaddy. I have a webhook that i want to be hit when an order is created. The logs show that it is being hit. But It is not reaching the server.

**Comment by claudiosmweb** [comment]
Are you sure it is not getting on the another server?
Are you sure that the another server is not using `mod_security`, CloudFlare, blocking `user-agents` or something?
What have you done so far to debug?

**Comment by sfabriece** [comment]
I can reach the server manually. I thought it might have something to do with the api server not being behind ssl, but that seemed not to matter.

**Comment by claudiosmweb** [comment]
Manually of course it's possible, but tried to do this using [`wp_remote_post()`](https://codex.wordpress.org/Function_Reference/wp_remote_post)?

**Comment by sfabriece** [comment]
Hi, I'm not a php dev, so it took me time to figure out how to do it. I got connection refused when I run wp_remote_post.
![wp_fail](https://cloud.githubusercontent.com/assets/3108592/9388518/46c920cc-4766-11e5-9826-8d1b7c438a8d.png)

**Comment by claudiosmweb** [comment]
Seems to me that the problem is on your server.
Try to install the cURL again on the server.
But this is not an issue with the WooCommerce.

**Comment by sfabriece** [comment]
Thanks for your help.
