### ISSUE TITLE
[Feature-Request] Minify and concatenate all scripts

### ISSUE THREAD

**Issue by andrewmclagan** [woothemes/woocommerce#8868]
I would suggest minifying of all scripts (dependent on the SCRIPT_DEBUG constant) and then concatenating them all into a single script.

**Why?**

Simple. To reduce the VERY large amount of HTTP requests. This severely effects page load speeds and SEO results of WooCommerce sites.

There are 12 separate scripts on the checkout page alone, not including theme and plugins.

**Comment by mikejolley** [comment]
This is in plugin territory, and there are pros and cons to both methods.

Cons to concatenating:
- Can no longer enqueue conditionally on pages
- If a script is required in say CART js and CHECKOUT js, you either need to keep it separate or duplicate the script
- 1 huge script is not necessarily faster to load than several. Scripts are cached either way by the browser.
- If another plugin has the same dependencies, it will either load multiple versions of that script or conflict and break.

cc @jameskoster

**Comment by andrewmclagan** [comment]
Yes, perhaps. 

Although on the cons:

* **Can no longer enqueue conditionally on pages** well actually most customers would download each library most likely over the life of their session on a woocommerce site.
* **If a script is required in say CART js and CHECKOUT js, you either need to keep it separate or duplicate the script** Really? Would it not just be loaded once in a single script?
* **1 huge script is not necessarily faster to load than several. Scripts are cached either way by the browser.** Wrong, the overhead of the extra HTTP requests incur a data penalty. Without even considering response and routing times.
* **If another plugin has the same dependencies, it will either load multiple versions of that script or conflict and break.** True. Although good developers should be aware of this and avoid plugin spaghetti.

Cheers! :-)

**Comment by mikejolley** [comment]
> Although good developers should be aware of this and avoid plugin spaghetti.

How can they avoid it? wp_enqueue_script won't know if scripts are bundled together.

**Comment by andrewmclagan** [comment]
easily....

```
(function(variables,you,want) {

    // WooCommerce JS

})(variables,passed,toFn);
```

Completely isolated.

**Comment by mikejolley** [comment]
I think we're talking about different things.

I'm saying if for example we bundle select2, and then another plugin enqueues select 2 (https://codex.wordpress.org/Function_Reference/wp_enqueue_script) thats going to be loaded in twice.

**Comment by andrewmclagan** [comment]
No I was thinking along the liens of:

easily....

```
(function(variables,you,want) {

    // Select 0.2.0

    // AnotherDep 0.1.x

    // WooCommerce

})(variables,passed,toFn);
```

etc...

Although yes, this would be doubling up in a small number of cases. I guess my issue at present is the SEO impact of high amounts of HTTP requests. 

Thinking over the issue more it could actually be a core Wordpress issue? Let me explain:

Rather then each script declaring it key with the wordpress enqueue function e.g.`wp_enqueue_script('select2', './assets/js/select.js', ['jquery,'underscore']);` wordpress could declare an array of script keys that are contained within the compiled file e.g.

`wp_enqueue_script(['select2','jqueryUI,'myPlugin'], './assets/js/app.min.js', ['jquery']);`
