### ISSUE TITLE
Products show different pricing

### ISSUE THREAD

**Issue by Sprint6m** [woothemes/woocommerce#8869]
If you are logged into the site it shows the NEW updated pricing - but if you are logged out of the site it shows the OLD pricing, have tried cache flushing and different browsers but its the same on all of them?
![desctop screenshot](https://cloud.githubusercontent.com/assets/13843893/9321386/d121cc38-4522-11e5-963e-f6873fc2c848.png)
![glacier diesel power archives - canadian diesel online 2015-08-16 21-09-33](https://cloud.githubusercontent.com/assets/13843893/9321387/d1264786-4522-11e5-9f09-618ea17252d8.jpeg)
the whole bottom row?

**Comment by LeGaS** [comment]
Do you use taxes? If so, try setting the **Calculate Tax Based On:** option to Shop base address (or whatever you prefer) on the Tax settings page.

**Comment by mikejolley** [comment]
This is most certainly either due to:

1. Caching
2. Customer default address/geolocation

You can view the page source and look at the footer to see if its static caching. Some hosts also show cached results.

**Comment by Sprint6m** [comment]
Here was the fix.
It appears related to your : wfcache/ folder under the following:
/home/cdonline/public_html/wp-content

When we renamed that wfcache to wfcache.old (and recreated new wfcache folder), our products pages started showing correct pricing:

Thanks Everyone
