### ISSUE TITLE
Webhooks deactivate when posting returns an error

### ISSUE THREAD

**Issue by murdockcrc** [woothemes/woocommerce#8876]
System is running WC 2.4.4.

Reproduction steps:
1. Configure a webhook (in my case, I am using order created).
2. Set an invalid url in the webhook (I am using http://10.0.0.16:3000/store/orders/new, which is a valid host in the network and the url works, but WC interprets the url as invalid)
3. Set the webhook as active and fire it.
4. Refresh the webhook configuration screen. You will see that the webhook's status has been changed to Deactivated.

It might be a behavior by design, as I suppose WC is deactivating the webhook due to the invalid url error. I am also assuming that other errors (such as network error or host not found errors), would not deactivate the hook, but would like someone from the product team to confirm this.

Also, it might be worthwhile for the product team to troubleshoot why WC considers http://10.0.0.16:3000/store/orders/new an invalid URL.

**Comment by claudiosmweb** [comment]
This is a standard behavior: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-webhook.php#L401-L420

Happens when the webhook fails five times.
