### ISSUE TITLE
[WC 2.4.4] Not possible to override customer-completed-order.php

### ISSUE THREAD

**Issue by rolfnilsson** [woothemes/woocommerce#8880]
I have overriden most of the email templates in /themes/Divi-child/woocommerce/emails but then I try to override customer-completed-order.php and woocommerce just uses the template in plugins/woocommerce/templates/emails. I found this old issue (link in bottom) and he has the same problem but the bug is fixed. Any idea why?

https://github.com/woothemes/woocommerce/issues/7336

**Comment by mikejolley** [comment]
yes it works fine. Ensure the name is correct:

https://github.com/woothemes/woocommerce/blob/master/includes/emails/class-wc-email-customer-completed-order.php#L34-L35

And the file is readable (file permissions).
