### ISSUE TITLE
Pagination still not working entirely in REST API for getting all customers

### ISSUE THREAD

**Issue by jeffkirby** [woothemes/woocommerce#8882]
In the latest version of Woocommerce v2.4.4 I see that the Link headers for pagination are now present which is good and fixes my prior bug report https://github.com/woothemes/woocommerce/issues/8418 

Now though I still see that the totals are not right. For example, right now I have a test system that has 811 users. When query get all users with no filter set, then I get zero customers. I would expect to get a full page with response headers linking me to 8 more pages and a `X-WC-Total` of 811.

If I set `filter[role]=seller`, I get a response header `X-WC-Total=293` rather than 799 and the "last" link is page 3 rather than page 8.

**Comment by claudiosmweb** [comment]
Here is your mistake:

> Now though I still see that the totals are not right. For example, right now I have a test system that has 811 users. **When query get all users with no filter set**, then I get zero customers.

Without filters will search only for "customers" and not by "users"... So this means that you have no user with the "customer" role in your site.

See:
https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-customers.php#L540-L546

**Comment by jeffkirby** [comment]
Ok, so that explains the first item. The second item, then is still unaddressed: that I only get 293 of the customers with role=seller.

**Comment by claudiosmweb** [comment]
@jeffikus by default we don't have any `seller` roles on WooCommerce.
I've tested this with other roles and working fine. This uses WP_User_Query then must return the correct value.

**Comment by jeffikus** [comment]
@claudiosmweb i think you meant @jeffkirby ;-)
