### ISSUE TITLE
Totals are not correct in REST API get list of customers

### ISSUE THREAD

**Issue by jeffkirby** [woothemes/woocommerce#8885]
I am seeing that the totals are not right when querying a list of customers. For example, right now I have a test system that has 811 users. 

If I set filter[role]=seller, I get a response header X-WC-Total=293 rather than 799 and the "last" link is page 3 rather than page 8.

**Comment by claudiosmweb** [comment]
As I said in another thread, it uses [`WP_User_Query`](https://codex.wordpress.org/Class_Reference/WP_User_Query).
And should return the correct value, you sure you're doing everything right?
Have you tried debugging this query?

**Comment by jeffkirby** [comment]
This screen shot shows the current roles.
![screen shot 2015-08-18 at 11 02 36 am](https://cloud.githubusercontent.com/assets/1360695/9339933/a3d9bc66-45a1-11e5-89ce-1c84b516dc97.png)

This screen shot shows the response from the server.
In this case I have queried `https://host/wc-api/v3/customers?filter[role]=seller&filter[limit]=100`
![only 293 results](https://cloud.githubusercontent.com/assets/1360695/9339988/0287bc9a-45a2-11e5-90a0-40ad0fd72294.png)

**Comment by claudiosmweb** [comment]
@jeffkirby try comment this two lines: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-customers.php#L607-L608

**Comment by jeffkirby** [comment]
You mean try `filter[limit]=-1`?

**Comment by claudiosmweb** [comment]
Nop, change to:

```php
// $query->total_pages = ( $args['limit'] == -1 ) ? 1 : ceil( $query->get_total() / $users_per_page );
// $query->page = $page;
```

**Comment by claudiosmweb** [comment]
But I'm still testing and everything works fine...

**Comment by claudiosmweb** [comment]
Closing for lack of feedback.
