### ISSUE TITLE
Add Bangladeshi Locale Information

### ISSUE THREAD

**Issue by mkrdip** [woothemes/woocommerce#8886]
Currency Code: BDT, Position: Left,
Weight Unit: Kilogram, 
Dimension Unit: Inch, 
Tax Rate: 15%, Name: VAT
Country Code: BD

**Comment by shivapoudel** [comment]
@mkrdip You should probably create a pull request.

**Comment by shivapoudel** [comment]
:smiley:

**Comment by mkrdip** [comment]
Yes, Thanks! @shivapoudel 

https://github.com/woothemes/woocommerce/pull/8887

**Comment by claudiosmweb** [comment]
Closed in #8887
Thanks.
