### ISSUE TITLE
Filter for "Choose an Option" in variation select.

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#8888]
Previously, you were able to override the template and customize this text with say, `Choose a $attribute_name` - https://github.com/woothemes/woocommerce/blob/2.3.13/templates/single-product/add-to-cart/variable.php#L27

With https://github.com/woothemes/woocommerce/commit/9a7893ba23631ab523d9727e8da19db6f5f7c8f8 though, this section is now found here: https://github.com/woothemes/woocommerce/blob/master/includes/wc-template-functions.php#L1915.

Would is be possible to have a filter here so that customizations can still easily be done?

**Comment by mikejolley** [comment]
It's wrapped in __() so its inherently filterable.
