### ISSUE TITLE
woocommerce_mini_cart() & cart_contents_count seem to be cached

### ISSUE THREAD

**Issue by indextwo** [woothemes/woocommerce#8893]
I've been tearing my hair out over this for two days, and every time I think I've solved it, it just pops up again.

In my `header.php` I have the following code for displaying the number of items in the cart, and a simple show/hide div displaying the items themselves, along with a total:

	<a id="minicart" href="<?php echo WC()->cart->get_cart_url(); ?>" class="cart icon red relative">
		<div class="number bold">
			<?php echo sprintf('%d', WC()->cart->cart_contents_count); ?>
		</div>
		
		<div>
			<?php returnIcon('cart');	// This function simply displays an inline SVG  ?>
		</div>
		
		<div id="cartcontents">
			<div class="widget_shopping_cart_content">
				<?php woocommerce_mini_cart(); ?>
			</div>
		</div>
	</a>

I also have a filter to return the cart fragments via AJAX when a new item is added:

	function woocommerce_header_add_to_cart_fragment($fragments) {
		
		ob_start();
		
		?>
			<div class="number bold">
				<?php echo sprintf('%d', WC()->cart->cart_contents_count); ?>
			</div>
			
		<?php
		
		$fragments['#minicart .number'] = ob_get_clean();
		
		return $fragments;
	}

	add_filter('woocommerce_add_to_cart_fragments', 'woocommerce_header_add_to_cart_fragment');

The filter always works - I've never had a problem with that. What's totally throwing me is that the standard, pre-processed calls in the header (`cart_contents_count` & `woocommerce_mini_cart()`) seem to be totally cached. If I add a new item, the AJAX will update both to display **1** and the actual item added; but if I change the page or refresh, it defaults back to **0** and **No items**. If I go to my cart, despite the mini-cart still saying I have nothing, the *actual* cart page displays the cart contents correctly.

It only appears to update if I go to my cart page and delete something from my cart; for example, if I've _actually_ got 7 items in my cart but the minicart displays 0, and then delete an item from my cart, suddenly the minicart will corectly display 6. However, from that point it will stay at 6, even if I add another dozen items. 

Here's what I've tried:

* **Change the classes/IDs of the elements** (i,e, `#minicart` to `#tinycart`, etc.) - works once, then immediately starts caching again.
* **Turned off the filters:** This has no effect, since the filter is only for returning fragments when new items are added. Also worth noting that there doesn't appear to be any kind of AJAX call fired at page load that would interfere with the minicart display.
* **Turned off all plugins except WooCommerce:** made no difference.
* **Turned off 'Enable AJAX add to cart buttons on archives' in WC settings:** This _kinda_ works, insofar as it reloads the entire page when an item is added, and the minicart displays number of cart items correctly (_hooray!_), but obviously disables the ability to add items via AJAX, which is a requirement of the site (_boo._)
* **Deleting my own `mini-cart.php` template file:** Just in case, to see if that was an issue. Made no difference.
* **Putting the `woocommerce_mini_cart() function literally anywhere else:** This, infuriatingly, works. If I take this function and the `echo sprintf('%d', WC()->cart->cart_contents_count)` line and put them _anywhere_ - within the header, within the page body, even inside the _same element_ that's getting 'cached', they work. They display the correct number of items, and the correct list of items. But the other calls to this function, as noted above, still appear to be cached.

As noted, this occurs even with no other plugins running; it happens both locally (a completely standard XAMPP installation on Windows) and remotely (a niftier nginx setup, slightly newer PHP version), and neither have any kind of caching enabled. 

Any suggestions would be very gratefully received, as I have totally lost my mind on this one.

**Comment by claudiosmweb** [comment]
Here's to report bugs with WooCommerce and what you are saying is about custom code...
Check how Storefront does this https://github.com/woothemes/storefront

**Comment by indextwo** [comment]
@claudiosmweb Sorry - I wasn't aware that it was considered 'custom code', as it was taken directly from @mikejolley's gists: [2044101](https://gist.github.com/mikejolley/2044101) & [2044109](https://gist.github.com/mikejolley/2044109). Surely if `woocommerce_update_cart()` is subject to some kind of caching, that's an issue? The only reason I suspected something like this is because, when an AJAX function _is_ called to fetch a fragment, it returns what I assumed was a cache-busting cart hash.

**Comment by mikejolley** [comment]
@indextwo can you look at your console for JS errors? Fragments will be updated when cart contents change, and cached in local storage. 

If the cart changes, the hash changes.

If the hash changes, the fragments refresh with javascript.

Claudio is correct about this being custom code so I can only 'guide'. We're busy this week as you can imagine with core, so looking into customisations is not a priority :)

**Comment by indextwo** [comment]
@mikejolley No problem - sorry, genuinely didn't think it was custom code, as I thought `woocommerce_mini_cart()` was a core function(?). As I mentioned, it's not the AJAX functions that are the issue, but that function and the `WC()->cart->cart_contents_count` that seem to be getting cached, but only in a particular location.

With regards to console feedback: that was the first thing I thought of. When I noticed it happening, I assumed it was an AJAX callback that was either caching or throwing back erroneous information on initial load; but there are _no_ callbacks on initial page load. The only time an AJAX call is fired is when something is added to the cart, and then it works. 

What's even weirder is that _sometimes_ it will show the **correct** number of items in the minicart for a split second, then immediately switch back to the incorrect cached number. But again; no AJAX callbacks take place, nothing on the console, and that's with all other plugins disabled. It's unlikely to be a jQuery hangover either, as I've been screwing with div IDs and class names, which should have broken any references to those divs (besides which, I can't find any). 

The only immediate solution I can think of is to manually make an AJAX callback to refresh the minicart details on initial load, but obviously it's not ideal. But for the life of me can't see why the AJAX calls work fine, but the standard preprocessed function returns a cached value.

**Comment by claudiosmweb** [comment]
@indextwo You tried to do what I said or just going to ignore me?

**Comment by indextwo** [comment]
@claudiosmweb I didn't ignore you - I replied to you; hence the reply earlier. I have downloaded the `storefront` theme and will take a look at it (although as it's currently 8pm GMT, I will most likely take a look tomorrow). Thanks for the earlier suggestion; perhaps not-so-much for the more recent reply :/

**Comment by claudiosmweb** [comment]
You clearly is not willing to be helped, you are ignoring my guidance and is here to cause problems.

**Comment by mikejolley** [comment]
Remember woocommerce_mini_cart() is just PHP. Without the JS/fragments, yes it will always be cached.

**Comment by indextwo** [comment]
Got it. Tomorrow I'll take a proper look through storefront as per Claudio's suggestion, and maybe try to implement my own cache-busting/fragment load for it. Sorry for the confusion.

**Comment by str** [comment]
Is there a way to disable the JS/fragment cache for development environments?
