### ISSUE TITLE
[API] OAuth: /wc-auth/v1/authorize returns 'A valid URL was not provided'

### ISSUE THREAD

**Issue by rsaftoiu** [woothemes/woocommerce#8898]
Hi there,

I have a VM running WordPress 4.3 w/ WooCommerce 2.4.4, REST api is enabled, I can make requests if I manually create API keys in the admin area. However, I am trying to use the new authorize endpoint.

The only documentation I have been able to find for using the /wc-auth/v1/authorize endpoint is here: https://woocommerce.wordpress.com/2015/08/07/api-settings-and-the-api-authentication-endpoint-in-2-4/

My wordpress VM is on https://devel.wordpress.net and my own app is running on https://devel.api.thriveapp.net:8443

I followed the instructions as provided, and I get the prompt asking to grant access to my app, but on the next screen I get redirected to the following url:

https://devel.wordpress.net/wc-auth/v1/access_granted?app_name=Thrive&user_id=5&return_url=https%3A%2F%2Fdevel.api.thriveapp.net%3A8443%2Fwoocommerce%2Fauthorization%2F&callback_url=https%3A%2F%2Fdevel.api.thriveapp.net%3A8443%2Fwoocommerce%2Fauthorization%2F&scope=read&wc_auth_nonce=76e9c39ce0

And the page says: Error: A valid URL was not provided.

**Comment by claudiosmweb** [comment]
Just test and everything works fine.
I'll write detailed documentation about it next week.

**Comment by jconroy** [comment]
hi @claudiosanches I've just his the exact same problem as above, wondering if you can save me some time and point me towards the detailed documentation you mention?

**Comment by claudiosanches** [comment]
@jconroy needs a valid URL for the `callback_url`, since will trigger `wp_safe_remote_post()` to set the keys.

**Comment by jconroy** [comment]
thanks @claudiosanches, I'll have to filter that for local development/testing.

**Comment by abishekrsrikaanth** [comment]
@claudiosanches @jconroy, I am facing this issue. Do both the url's need to be url encoded?

**Comment by claudiosanches** [comment]
Hello @abishekrsrikaanth,

Yes both need to be encoded, you can see details in our documentation, we also include examples in bash script, PHP, JavaScript, Ruby and Python showing how to encode: http://woocommerce.github.io/woocommerce-rest-api-docs/?php#rest-api-keys

I hope it helps.

**Comment by ArvindhMangoleap** [comment]
Hello @claudiosanches I am facing this issue.
Here is my URL
`https://wooshop.gallabox.dev/wc-auth/v1/authorize?app_name=Gallabox&scope=read_write&user_id=eyJhY2NvdW50SWQiOiI2MDA2YjQxZGJlMGQyZTc1Mjg5YTI4Y2EiLCJ1c2VySWQiOiI2MDA2YjY3M2JlMGQyZTc1Mjg5YTI4Y2QiLCJwcm92aWRlcklkIjoiNjIxNGQ2NzNjMDVjYjZiY2EzMDRjMzc3Iiwic2hvcCI6Imh0dHBzOi8vd29vc2hvcC5nYWxsYWJveC5kZXYifQ%3D%3D&return_url=https%3A%2F%2Fapp.gallabox.dev%2Fintegration%2Fwoocommerce&callback_url=https%3A%2F%2F0d45-49-204-128-13.ngrok.io%2Fauth%2Fintegrations%2Fwoocommerce%2Fcallback`

My NodeJs code

```
        const endpoint = "/wc-auth/v1/authorize";
        const params: IWooCommerceAuth = {
            app_name: "Gallabox",
            scope: "read_write",
            user_id: stateString,
            return_url: `https://app.gallabox.dev/integration/woocommerce`,
            callback_url: `${process.env.HOST_URL}/auth/integrations/woocommerce/callback`,
        };
        const queryString = querystring
            .stringify((params as unknown) as querystring.ParsedUrlQueryInput)
            .replace(/%20/g, "+");
        const uri = `${storeUrl + endpoint}?${queryString}`;```

**Comment by AliBayatpour** [comment]
Hi, I would appreciate it if someone could help. I'm trying to use the 
I'm trying to get API keys using the Application Authentication Endpoint, but I get access denied. Error: A valid URL was not provided after I approve the access. 
Here is my piece of code:
```
 const PARAMS = {
    app_name: "My App Name",
    scope: "read_write",
    user_id: 123,
    return_url: "http://localhost:5650",
    callback_url: "https://localhost:7104/woo-commerce-test",
  };

  const queryString = Object.keys(PARAMS)
    .map(
      (key) => encodeURIComponent(key) + "=" + encodeURIComponent(PARAMS[key]),
    )
    .join("&");

  const formattedQueryString = queryString.replace(/%20/g, "+");

  const requestUrl = STORE_URL + ENDPOINT + "?" + formattedQueryString;

  console.log(requestUrl)

```

I use this request URL to get access to the store and after approving the access I get the error URL invalid access denied.
I really need help thank you in advance
