### ISSUE TITLE
COD Option for default payment gateway missing in 2.4.4

### ISSUE THREAD

**Issue by samsid93** [woothemes/woocommerce#8903]
Hi.

I have my store running on woocommerce and my local customers are comfortable with COD. Now what happen in 2.4.4 is after applying all appropriate settings when user enters details like zip code then it shows COD option as the system analysis the shipping option at that time only.  

This create confusion in customer's mind that may be COD option is not available so it effects the sale.
Why it is not possible to show COD option on default country select. Why it is needed to enter zip code to enable COD option ? Any way out ? solution ? to show the COD option by default without taking and info from user or when they select the country where COD is not applicable then it may disappear rather then appearing so late ? 

Thanks and Best Wishes !

**Comment by mikejolley** [comment]
Screenshot your COD settings

**Comment by samsid93** [comment]
![cod settings](https://cloud.githubusercontent.com/assets/13887390/9403423/7442a2b8-4800-11e5-9401-cb3fdf7dc8a0.PNG)
![local delivery settings](https://cloud.githubusercontent.com/assets/13887390/9403427/7a34040a-4800-11e5-954c-42d614e918c7.PNG)

**Comment by mikejolley** [comment]
This is to be expected.

COD requires Local Delivery
Local Delivery requires Pakistan

So all the above is dependent on the user first inputting their address details and having the order totals box appear. 

You can set the default customer address to Pakistan/base country to have it show earlier.

**Comment by samsid93** [comment]
Hi Mike

Thanks for your help. I have resolved the issue last night. It was
happening because there was a check mark on the option in shipping setting

 " Hide shipping costs until an address is entered" .

after making it unchecked and set the priority of COD = 1 it becomes normal
:) I appreciate your response , will be your great thankful :)
have a nice day ! Best wishes and greetings from PAKISTAN !

**Comment by samsid93** [comment]
Hey,

I just signed the petition "www.nobelpeaceprize.org/: Nomination of Prime
Minister of Pakistan, Mr. Imran Ahmed Khan for the Nobel Peace Prize" and
wanted to see if you could help by adding your name.

Our goal is to reach 50,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/cbDqCbVvvL

Thanks!
usama
