### ISSUE TITLE
preventDefault() instead of return false; for product data tabs

### ISSUE THREAD

**Issue by pawelkmpt** [woothemes/woocommerce#8905]
I wanted to attach event handler to tabs (`.wc-tabs a`) in *Product Data* section on the product edit page and I found that handler function from WooCommerce core uses `return false;` so my events are never invoked, as this piece of code stops propagation. Could you change it to `event.preventDefault()`?

Code I'm talking about is located in `meta-boxes.js` starting from line 37.

```
$( document.body ).on( 'wc-init-tabbed-panels', function() {
    $( 'ul.wc-tabs' ).show();
    $( 'ul.wc-tabs a' ).click( function() {
        var panel_wrap = $( this ).closest( 'div.panel-wrap' );
        $( 'ul.wc-tabs li', panel_wrap ).removeClass( 'active' );
        $( this ).parent().addClass( 'active' );
        $( 'div.panel', panel_wrap ).hide();
        $( $( this ).attr( 'href' ) ).show();
        return false;
    });
    $( 'div.panel-wrap' ).each( function() {
        $( this ).find( 'ul.wc-tabs li' ).eq( 0 ).find( 'a' ).click();
    });
}).trigger( 'wc-init-tabbed-panels' );
```

Useful reading:
https://css-tricks.com/return-false-and-prevent-default/
http://www.simoahava.com/gtm-tips/fix-problems-with-gtm-listeners/

**Comment by mikejolley** [comment]
Closed in fav of #8921
