### ISSUE TITLE
2.4.5 Variation and Grouped Products Stopped Working

### ISSUE THREAD

**Issue by BrandonShutter** [woothemes/woocommerce#8908]
Upon upgraded from `2.4.4` to `2.4.5`, I would get the error message: `Sorry, this product is unavailable.`

Downgrading back to `2.4.4` they work again.

**Comment by mikejolley** [comment]
When? On view? On add to cart?

**Comment by mikejolley** [comment]
I cannot see any obvious changes between versions; nothing on the frontend anyway.

**Comment by BrandonShutter** [comment]
This was created directly from add to cart urls. Examples of a product page that didn't work: https://www.caltonnutrition.com/product/nutreince-all-varieties/
https://www.caltonnutrition.com/product/skinnyfat-all-varieties/

Again, downgrading made it work.

**Comment by mikejolley** [comment]
Confirmed for grouped products, not for variations.

**Comment by BrandonShutter** [comment]
Confirmed that variations are not a problem.
