### ISSUE TITLE
Add to Card via REST

### ISSUE THREAD

**Issue by rotherfuchs** [woothemes/woocommerce#8909]
It would be splendid if you could provide a way to add a product to the card via the REST API, for instance a POST on `/wc-api/v3/products/cart` providing the product ID as payload argument.

**Comment by WPprodigy** [comment]
The REST API kind of skips the cart process though. It is used for viewing products, and then creating orders.

You can do this via a url like this though: `http://yourproducturl[dot]com/checkout/?add-to-cart=%ID%`. And here is a guide for adding variation products to cart with pre-set attributes: http://www.remicorson.com/add-woocommerce-variable-product-with-variations-to-cart/

**Comment by claudiosmweb** [comment]
Use the order endpoint.
We not will have any API for sessions or cart.

**Comment by rotherfuchs** [comment]
That absolutely does what is required! Thanks!

**Comment by niwinnm** [comment]
@claudiosan I used the create order endpoint to create a new order. I am getting a successful response, but if I try sending the user to the "view_order_url" returned by the Create order API, the website says "Invalid Order"

**Comment by markoheijnen** [comment]
Order endpoint could be to late. If you have low stock then the ability to add it to a card so it can be reserved would be great. I found this ticket since I was looking how to do it inside a native app. I guess I could use `http://yourproducturl[dot]com/checkout/?add-to-cart=%ID%` and catch/send the cookie data.

**Comment by claudiosmweb** [comment]
> Order endpoint could be to late. If you have low stock then the ability to add it to a card so it can be reserved would be great.

Not too late, since we don't reserve stock before the checkout, in fact we decrease stock only after payment confirmed. So have only an order endpoint it isn't a problem.

**Comment by markoheijnen** [comment]
My bad. Always forget about when it is reserved.
