### ISSUE TITLE
Possible variable product "sold individually" issue

### ISSUE THREAD

**Issue by DeboMediaGroup** [woothemes/woocommerce#8917]
I have a variable product created with 1 attribute and 6 variations for that attribute.

I have the "Sold Individually" check box checked under the Inventory tab.

I can add the product to the cart 6 times, as long as I select a different variation each time. When I select a variation that was already added to the cart though, it errors out saying you can not add another one of those products to the cart.

Shouldn't it only allow me to add 1 of that variable product to the cart, not matter what variation is selected the second time around?

**Comment by mikejolley** [comment]
No, we treat each variation independent. So you could have a Red t shirt and a blue t shirt, but not 2 red t shirts.
