### ISSUE TITLE
No Generate API Keys Showing

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#8920]
Hi,

I have a customer using WooCommerce 2.4. The REST API has been enabled. There is no option to create API keys for the admin user. 

Site: http://www.pawsitivecanineconnection.com/wc-api/v2

![attendeeviewerimage001](https://cloud.githubusercontent.com/assets/1679993/9411429/e7cc08d0-47f3-11e5-93cd-17d70a78b84d.jpg)
![attendeeviewerimage002](https://cloud.githubusercontent.com/assets/1679993/9411430/e7cf1c00-47f3-11e5-8be0-db5bfa8b83c5.jpg)

**Comment by mikejolley** [comment]
WooCommerce > Settings > API

**Comment by jmawebtech** [comment]
Hi,


The setting has been enabled. See attached.


Joseph Anderson

Director, Customer Success

JMA Web Technologies, Inc.

P: (781) 330-0737

Web: http://www.jmawebtechnologies.com

Store: http://www.jmawebstore.com


________________________________

**Comment by mikejolley** [comment]
That is also where keys are generated.

**Comment by claudiosmweb** [comment]
@jmawebtech good reading: https://woocommerce.wordpress.com/2015/08/07/api-settings-and-the-api-authentication-endpoint-in-2-4/
