### ISSUE TITLE
Webhook diactivated after first try

### ISSUE THREAD

**Issue by sfabriece** [woothemes/woocommerce#8922]
A webhook on order.created is being deactivated after firing the first time. Is there a requirement on the response from the server receiving the payload from woocommerce?

**Comment by claudiosmweb** [comment]
I just tested it and works fine.

**Comment by sfabriece** [comment]
My question is whether there is a requirement on what type of response expected from the server?

**Comment by claudiosmweb** [comment]
@sfabriece any non-2xx response.

**Comment by sfabriece** [comment]
I actually figured out the problem. In the logs, The payload being sent is not being wrapped so it is pushing the response to the right, with no horizontal scroll bar. So I didn't realize that there was a reponse to look at. If you can look into this that would be awesome.

Thanks for your help.
