### ISSUE TITLE
Updating WooCommerce results in 403 Errors for downloadable products set to "redirect only"

### ISSUE THREAD

**Issue by kirbydoss** [woothemes/woocommerce#8923]
When updating WooCommerce, a 403 error is being displayed for previously purchased and newly purchased downloadable products, until an admin goes into Woocommerce-> Settings -> Products -> Downloadable Products and clicks the "Save Changes" button.

**Comment by mikejolley** [comment]
What is the error description? Or you just get 403 in browser?

And what is the file path if you can share? Is it accessible directly?

**Comment by kirbydoss** [comment]
It is all the files for all users, past and current.

I've already resolved the issue, as the site is in production.

I can provide you with a coupon code on the next update to purchase a
product and see the error.

No errors other than the 403 in the browser.
