### ISSUE TITLE
Stock/Out of stock quirk.

### ISSUE THREAD

**Issue by dcm13** [woothemes/woocommerce#8928]
I have a hiccup i think.. In order for a product to show as being 'in stock' i have to set the number available to 2 items. if i set it to 1 item, it shows on the front end as out of stock. As i dont have a large store this is not a huge issue - i.e. if someone purchases that one item i can go in same day and just remove it from the site --but it would be great to not have to do this manually. the in stock/out of stock has never worked.. i've tried the 2012 theme, as well as 2 other purchased themes and have tried turning off all plugins without results.

**Comment by mikejolley** [comment]
In settings, what do you have here https://dl.dropboxusercontent.com/s/5mi6un176bxkgd2/2015-08-22%20at%2011.54.png?dl=0

**Comment by dcm13** [comment]
same as your screen shot.


![screenshot 2a](https://cloud.githubusercontent.com/assets/13913540/9424747/d777587c-48ac-11e5-8517-fb6510ae5ee6.jpg)

**Comment by mikejolley** [comment]
I wonder, do you have some pending orders? These can 'hold stock' until purchased..

**Comment by dcm13** [comment]
Hi Mike. No pending orders. I have some examples of pending orders in the theme dummy content but their examples are clothing and mine is jewelry so that shouldn't make a difference. Theirs re in draft mode in case I need the example at some point but I could delete them if that might help

**Comment by mikejolley** [comment]
Make a test product with 1 stock. After saving, see if stock status is still set to 'in stock' in the backend (there is a dropdown under inventory tab) and send the link to the product here.

**Comment by dcm13** [comment]
ok this one worked! http://nightmaircreations.com/product/skull-cross-earrings/ (it was pre existing on the site)

tried a new one here: http://nightmaircreations.com/product/bass-string-and-heart-necklace/ it worked too. consider resolved unless it hiccups again. not sure what was going on!
