### ISSUE TITLE
Create Product - POST categories are not added

### ISSUE THREAD

**Issue by yatanasov** [woothemes/woocommerce#8933]
When you create a new product and supply array of strings (existing categories in wordpress) using the API (both v2 and v3) the categories are not added to the product.

Example:
POST to: 
https://site.com/wc-api/v3/products/?consumer_key=ck&consumer_secret=cs

JSON Data:
{
  "product": {
    "status": "draft",
    "description": "",
    "regular_price": 79,
    "price": 79,
    "managing_stock": "true",
    "categories": [
      "\u0414\u0430\u043c\u0441\u043a\u0438 \u043e\u0431\u0443\u0432\u043a\u0438",
      "\u0422\u0430\u0440\u0430"
    ],
    "sku": "15348-\u0447\u0435\u0440",
    "title": "15348-\u0447\u0435\u0440   \u0426\u0415\u041d\u0410 :    79.0",
    "variations": [
      {
        "attributes": [
          {
            "visible": "true",
            "name": "\u0420\u0430\u0437\u043c\u0435\u0440",
            "option": "39",
            "slug": "size"
          }
        ],
        "price": 79,
        "regular_price": 79
      },
      {
        "attributes": [
          {
            "visible": "true",
            "name": "\u0420\u0430\u0437\u043c\u0435\u0440",
            "option": "38",
            "slug": "size"
          }
        ],
        "price": 79,
        "regular_price": 79
      },
      {
        "attributes": [
          {
            "visible": "true",
            "name": "\u0420\u0430\u0437\u043c\u0435\u0440",
            "option": "37",
            "slug": "size"
          }
        ],
        "price": 79,
        "regular_price": 79
      },
      {
        "attributes": [
          {
            "visible": "true",
            "name": "\u0420\u0430\u0437\u043c\u0435\u0440",
            "option": "36",
            "slug": "size"
          }
        ],
        "price": 79,
        "regular_price": 79
      },
      {
        "attributes": [
          {
            "visible": "true",
            "name": "\u0420\u0430\u0437\u043c\u0435\u0440",
            "option": "40",
            "slug": "size"
          }
        ],
        "price": 79,
        "regular_price": 79
      },
      {
        "attributes": [
          {
            "visible": "true",
            "name": "\u0420\u0430\u0437\u043c\u0435\u0440",
            "option": "41",
            "slug": "size"
          }
        ],
        "price": 79,
        "regular_price": 79
      },
      {
        "attributes": [
          {
            "visible": "true",
            "name": "\u0420\u0430\u0437\u043c\u0435\u0440",
            "option": "35",
            "slug": "size"
          }
        ],
        "price": 79,
        "regular_price": 79
      }
    ],
    "short_description": "\u0414\u0430\u043c\u0441\u043a\u0438 ",
    "attributes": [
      {
        "visible": "true",
        "options": [
          "39",
          "38",
          "37",
          "36",
          "40",
          "41",
          "35"
        ],
        "name": "\u0420\u0430\u0437\u043c\u0435\u0440",
        "variation": "true",
        "slug": "size"
      }
    ],
    "stock_quantity": "4",
    "type": "variable"
  }
}

Response is OK, but categories is an empty array [].

(Sorry for the unicode)

**Comment by claudiosmweb** [comment]
Because you need to send the categories IDs:

![screenshot from 2015-08-24 13 16 02](https://cloud.githubusercontent.com/assets/1264099/9445394/4d81d75c-4a62-11e5-8a9a-9a919f92a984.png)
