### ISSUE TITLE
Shipping management problems with the new version 4.3

### ISSUE THREAD

**Issue by elviorossi** [woothemes/woocommerce#8934]
Good morning, with the latest update of woocommerce (ver 4.3 italian) I noticed a serious problem on the management of shipments.
For some reason, the software sets the default withdrawal in place and does not allow the use of any other costs (to me comes up with the management of the single tariff).
Also going to put the check on single tariff and recalculating the setting remains withdrawn at home and is not calculated the cost of shipping additional.
I hope this communication is to your help to improve this beautiful plug-in

Sorry for the bad machine translation

Greetings
Elvio Rossi - Igrodry.com

**Comment by mikejolley** [comment]
Sorry, thats not clear @elviorossi. Can you explain better with screenshots?

**Comment by elviorossi** [comment]
Inform you that the problem had never occurred before, and now you are presented only with the latest update 3 days ago (in fact a purchase of 08/21/2015 has been running smoothly and was not made any changes by more than one igrodry.com month to the site).
As the figure in the version 4.3 if you enable both the "in-store pick up" the "flat rate", in the basket are displayed both choices, but is set as the default choice in the withdrawal; if you try to change and apply a single tariff, and you refresh the page, returns to the withdrawal within and still not be calculated the shipping costs.
To restore it just remove the selection in the withdrawal, in this case in the basket are regularly calculated the shipping costs.
Unfortunately for us the "pick in store" for us it is important.

![idcartgood](https://cloud.githubusercontent.com/assets/3388849/9435198/d94b5f28-4a45-11e5-8289-fbbda8788731.jpg)
![idcartnogood](https://cloud.githubusercontent.com/assets/3388849/9435199/d95616de-4a45-11e5-9800-757082a26200.jpg)
![idsetgood](https://cloud.githubusercontent.com/assets/3388849/9435200/d95c60de-4a45-11e5-804c-7bb42113037d.jpg)
![idsetnogood](https://cloud.githubusercontent.com/assets/3388849/9435201/d9611278-4a45-11e5-8604-839550755dae.jpg)

**Comment by mikejolley** [comment]
To have flat rate default, set these: https://dl.dropboxusercontent.com/s/80mapf4n95n6v34/2015-08-24%20at%2010.50.png?dl=0

Set flat rate to 1, and in store pickup to 2. Flat rate will be default.

**Comment by elviorossi** [comment]
tank you
