### ISSUE TITLE
Smartcoupon Checkout Send to different People Error Warning: html_entity_decode()

### ISSUE THREAD

**Issue by hollowplayer** [woothemes/woocommerce#8935]
we have woocommerce subscription and smart coupon installed. When customer add 2 or more gift certificates for checkout and click on send to different people the following error show up. Please check snapshot for error. Please help!

Warning: html_entity_decode() expects parameter 1 to be string, array given in public_html/wp-includes/plugin.php on line 213

    $value = call_user_func_array($the_['function'], array_slice($args, 1, (int) $the_['accepted_args']));

screenshot are following.

![ztg9xqb](https://cloud.githubusercontent.com/assets/13937175/9432045/290dfe28-49ea-11e5-99ec-2e4c9f01bcab.png)
![yb3rrzf](https://cloud.githubusercontent.com/assets/13937175/9432048/2b4bf2d0-49ea-11e5-9704-6334df218543.png)

**Comment by mikejolley** [comment]
I've logged this with the Smart Coupons dev.
