### ISSUE TITLE
If password field is enabled, enforce strong passwords

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8938]

**Comment by WPprodigy** [comment]
There is also `wp_generate_password()` now that could be used to generate an optional default password for the customer.

**Comment by gedex** [comment]
@mikejolley What's the context of password field here? Are you referring to account creation during the checkout?

<img width="408" alt="screen shot 2015-09-21 at 11 08 09 am" src="https://cloud.githubusercontent.com/assets/78313/9997322/1fc9437c-6051-11e5-8a4f-e3ee60e8b040.png">

and show strong password strength indicator like following:

<img width="385" alt="screen shot 2015-09-21 at 11 16 22 am" src="https://cloud.githubusercontent.com/assets/78313/9997540/5257eafe-6052-11e5-8e8e-eb8c707c0767.png">

**Comment by claudiosmweb** [comment]
@gedex yep, checkout and my account page.

**Comment by nishitlangaliya** [comment]
As per above fixes ref # 2dcd391 the front end changes will look like below attached images :

1. Checkout Page: 
![checkoutpage](https://cloud.githubusercontent.com/assets/11435772/10338265/c983a230-6d22-11e5-9213-a7a8f3c68177.png)

2. My Account Page

![myaccountpage](https://cloud.githubusercontent.com/assets/11435772/10338287/e3da28c0-6d22-11e5-9025-2c0d70a9ac08.png)

**Comment by gedex** [comment]
@nishitlangaliya, PR are always welcome. Are you planning to issue PR to us? If not, I'll be working on this.

**Comment by nishitlangaliya** [comment]
@gedex, I have already Fork the repository and commit the changes ref # 2dcd391. for review.

**Comment by gedex** [comment]
@nishitlangaliya Please take a look at [How to Submit a PR](https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md#how-to-submit-a-pr). I'll do the review once you issued a PR.

**Comment by nishitlangaliya** [comment]
@gedex I have Submit a PR https://github.com/woothemes/woocommerce/pull/9305 can you please check for the same

**Comment by claudiosmweb** [comment]
Closed by #9319
