### ISSUE TITLE
Description not showing on all category pages 

### ISSUE THREAD

**Issue by gabthemonster** [woothemes/woocommerce#8941]
I have added descriptions to my Woocommerce product categories and they show up fine. However, because I have several products, the category has multiple pages, such as 1, 2 and 3. The description only shows on the main category page but not on the sub pages.

Is this a bug or working as intended? 

Thank you.

**Comment by claudiosmweb** [comment]
This is expected behavior... See:

https://github.com/woothemes/woocommerce/blob/fd22334fe6db58311ebd591c8ed90455c4777256/includes/wc-template-functions.php#L527

You can change this behavior in your theme, placing it in the `functions.php`:

```php
function woocommerce_taxonomy_archive_description() {
	if ( is_tax( array( 'product_cat', 'product_tag' ) ) ) {
		$description = wc_format_content( term_description() );
		if ( $description ) {
			echo '<div class="term-description">' . $description . '</div>';
		}
	}
}
```

**Comment by gabthemonster** [comment]
Awesome!!!! Worked perfectly. 

Thanks,

**Comment by claudiosmweb** [comment]
;)
