### ISSUE TITLE
Proposal: Minimum Template Versions

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#8942]
The idea is pretty simple, the implementation may not be though.

When there is a big update to a template that effects functionality and makes past templates cause issues, what if we overrode the overwritten template? This way sites will not just flat break. Instead there would maybe be some styling issues that the theme authors would then have to fix. But at least the site doesn't break.

So essentially every time `wc_get_template_part()` is called in core, there could be an extra parameter for 'minimum-version'. If the theme's template does not meet the deemed required version, then it routes back to the core woocommerce folder to retrieve the template.

This 'minimum-version' would not need to be the latest on most occasions, but just a fallback to the last major functionality change to the template.

**Comment by mikejolley** [comment]
Might be bad to check the version every load..

**Comment by paulwilde** [comment]
Would need some form of caching with a button in `System Status > Tools` to flush the cache, and then every time a new version of WooCommerce is installed that cache is automatically flushed.

**Comment by nvartolomei** [comment]
Oh, how much I don't like this...

>  template that effects functionality

Why a template should have functionality beside displaying content? What about users who don't write versions in their template files? This would be a ton times harder to debug and to understand what happens, especially for newer developers and advanced users.

Yeah there might be some problems but this is not a solution.

Next move, start versioning filters and actions...

**Comment by BFTrick** [comment]
@WPprodigy we talked about this quite a bit at our meetup and it's going to be tricky no matter which way we proceed. There's not great solution. However, I would look to explore this again down the road.
