### ISSUE TITLE
default payment method is not selected by default

### ISSUE THREAD

**Issue by yoramz** [woothemes/woocommerce#8944]
Hi,
since 2.4.4, when you removed the option to define the default payment method in the UI, the default payment method is also NOT selected by default.
i'm using paypal as the only payment method and used to hide it in my billing form (as it was selected by default). since version 2.4.5 - the default gateway radio button is no more selected by default.
any chance you can release a patch or guide me how to implement a work around?

thx,
yoramz

**Comment by mikejolley** [comment]
Drag and drop it to the top of the list of gateways in settings; top = default.

**Comment by yoramz** [comment]
already did that but - i got the paypal payment method on my billing/checkout page but still not selected (the paypal payment method is a radio button and used to be selected by default when this is the only one. not any more...)

**Comment by mikejolley** [comment]
Checking..

**Comment by mikejolley** [comment]
It remembers. If you try a new session in new browser it will be default.

**Comment by wedesignla** [comment]
I'm sorry but this still isn't working for me. I have two gateways, standard PayPal and Stripe (using Woocommerce's extension for this). Stripe is at the top of the list, however when I go to checkout, although it shows Stripe Credit Card form first, the PayPal radio button is selected first.

I've cleared cache, try incognito mode and even different browsers.
I am logging in with the same user account (as I don't have guest checkout), but I doubt you are saving something to my account settings for this (or are you :) )

What am I missing or is this really a bug still?

**Comment by refschool** [comment]
i have the same problem the top is not the default, and display of the payment order is not consistent in the backend

**Comment by phylaxis** [comment]
I'm with @wedesignla and @refschool I'm also still having this issue.

**Comment by ConsciousCrafties** [comment]
and me!

**Comment by mikejolley** [comment]
As we keep saying, once chosen it's saved in session. You need to be on a new session/new browser for the default to be selected. The first listed gateway is the default.
