### ISSUE TITLE
Refund Failed

### ISSUE THREAD

**Issue by hassanasad** [woothemes/woocommerce#8945]
We were recently trying to issue refunds from the woocommerce order interface via paypal and were receiving an error "Refund failed". After spending quite alot of time trying to understand why it was happening, i setup a breakpoint in code. The error from paypal was *"You are over the time limit to perform a refund on this transaction"*. I believe these valuable error messages should be shown back to the users. Can you please implement them :) ?

**Comment by mikejolley** [comment]
Yes this should be useful. Adding to 2.5.

**Comment by hassanasad** [comment]
Thanks :)
