### ISSUE TITLE
get_shipping_methods() returns empty array?

### ISSUE THREAD

**Issue by pavelevap** [woothemes/woocommerce#8949]
Hi,

I am using `woocommerce_review_order_after_shipping` action.

In my custom function I used following code with `get_shipping_methods()` function:

`$available_shipping = WC()->shipping->get_shipping_methods();`

But using WordPress 4.3 and latest WooCommerce 2.4.6 it returns empty `array()`.

When I use similar `load_shipping_methods()` function:

`$available_shipping = WC()->shipping->load_shipping_methods();`

Everything works well and all registered methods are returned.

**Comment by pavelevap** [comment]
And it works well when I enabled "Shipping Debug Mode".

And does not work when disabled, strange...

Also when I deactivate custom plugin with additional shipping method, this method is still enabled for all customers. Tested in anonymous browser window, only Twenty Fifteen and WooCommerce.

**Comment by mikejolley** [comment]
This is for performance reasons - shipping methods are only loaded when they are needed to get prices.

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-shipping.php#L353-L358

Once calculated, rates are cached. Thats why you see them with shipping debug mode on - no cache.

If you have logic that needs to be executed everywhere, not just during shipping quotes, move it outside of the shipping class you have made.

**Comment by pavelevap** [comment]
```
add_action( 'woocommerce_review_order_after_shipping', 'woo_shipping_test' );
function woo_shipping_test() {
  $available_shipping = WC()->shipping->get_shipping_methods();
  var_dump($available_shipping);
}
```

Yes, but this snippet should work? Function `get_shipping_methods()` should return cached results and not empty `array()`?
