### ISSUE TITLE
Filtering variation value in order page

### ISSUE THREAD

**Issue by allysonsouza** [woothemes/woocommerce#8953]
Hi, I'm filtering some specific variations to have custom display in product -> variations select, and also in front product page select.

But, there's no hook to filter/modify my variations value in order page. There's other way to do it? Or maybe it's a possibility add a hook in https://github.com/woothemes/woocommerce/blob/1a2ccd741b5bc6efa5e8906e6ff0ec4a00f88e15/includes/admin/meta-boxes/views/html-order-item.php#L93

**Comment by WPprodigy** [comment]
For the front page select, you can edit it in this template: https://github.com/woothemes/woocommerce/blob/master/templates/single-product/add-to-cart/variable.php#L32-L34

And you can override the function being called in that template as well: https://github.com/woothemes/woocommerce/blob/master/includes/wc-template-functions.php#L1898

Not sure about the backend. Most use cases don't need extend that functionality.

**Comment by mikejolley** [comment]
No hook for values, only labels. If you can justify a scenario where it is beneficial to show something differing from what is stored, please make a PR.

**Comment by allysonsouza** [comment]
If I can change what I'm displaying to user in additional information tab with filters (https://github.com/woothemes/woocommerce/blob/1a2ccd741b5bc6efa5e8906e6ff0ec4a00f88e15/templates/single-product/product-attributes.php#L62), maybe would be good to have filters to change attributes display in every place (front end/admin) that they are displayed, or not?

(For example, I can change the display format in additional information tab, but in order details after the chekout the user will see other format, because there's no hook to apply the same filter - https://github.com/woothemes/woocommerce/blob/1a2ccd741b5bc6efa5e8906e6ff0ec4a00f88e15/includes/class-wc-order-item-meta.php#L68)
