### ISSUE TITLE
Variations tab active when there's only attributes not marked to be used as variation

### ISSUE THREAD

**Issue by allysonsouza** [woothemes/woocommerce#8954]
I don't know if it's just in my installation, but when I creates a new product, then select product type as variable product and create an attribute, but doesn't check "use for variations", if I go to Variations tab, it is active, making possible to create variations without define an attribute to be used for variations.

![variable-product](https://cloud.githubusercontent.com/assets/2000638/9483374/e67890e0-4b75-11e5-8074-506c76e7e8e0.png)

**Comment by WPprodigy** [comment]
I was able to replicate this.

Something must be going wrong with this check: https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L608
