### ISSUE TITLE
ob_start without ob_get_clean in top_rated_products shortcodes causing themes to break.

### ISSUE THREAD

**Issue by ibndawood** [woothemes/woocommerce#8956]
Here : https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-shortcodes.php#L578

The code has `ob_start ` which does not have a `ob_get_clean`. However line 583 calls product_loop method which has `ob_start` and `ob_get_clean`. This is causing lot of themes to break.

**Comment by langan** [comment]
I think this commit https://github.com/woothemes/woocommerce/commit/ffc941fcb188ea187e8cab5cc0a3ec154cdaf2e2 has added the ob_start call back
