### ISSUE TITLE
Simplify Commerce: Add support for Ireland

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#8960]
Simplify Commerce is now available in Ireland.

PR coming in shortly to add support for this.

**Comment by ChromeOrange** [comment]
@mattyza This should include a filter so more countries can be added without a WC point release

**Comment by mattyza** [comment]
Filter added in #8962 @ChromeOrange .

**Comment by claudiosmweb** [comment]
Closed in #8961
