### ISSUE TITLE
One Page Checkout -  "Please choose product options" error.

### ISSUE THREAD

**Issue by Harryb17** [woothemes/woocommerce#8965]
I have verified this error on two completely fresh installs of wordpress.

When trying to add a variable product to the cart using the one page checkout plugin, I am prompted with the "Please choose product options…" dialogue even though an option is definitely selected.

My test configuration.....
Fresh version of wordpress installed on local machine using apache and also tested on a Nginx server  with only Woocommerce and One Page checkout plugin installed. Variable product created with one attribute with two options. 

This issue appears when you then use the following two methods...
Tick the "One Page Checkout" tick box on the edit product page.
Create a fresh page with the following shortcode....
[woocommerce_one_page_checkout template="product-single" product_ids="14"]

However the product gets successfully added to the cart if you add the [woocommerce_one_page_checkout] shortcode to the product description. But this reloads the page.

**Comment by mikejolley** [comment]
support.woothemes.com please if you have not posted already - github is for core issues only.
