### ISSUE TITLE
Geolocation redirects searches

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8967]
https://wordpress.org/support/topic/geolocation-with-page-caching-support-enabled-breaks-product-wp-search?replies=1

Exclude POST requests?

**Comment by mikejolley** [comment]
Another test case:

> Customers were reporting that when they asked for a password reset they would get the link to reset the password and when they clicked on it they weren't given the option to enter a new password and instead all they saw was the section to enter their email address.
>
>After a day of pulling out my hair, I found out that the problem is with the new 'Default Customer Address' option in WooCommerce. If you select Geolocate Woocommerce appends a string to all urls ?v=XXXXXXXXXXXX. For some reason this breaks the password reset sections. Once disabled my customers are able to reset their passwords and enter a new password once the URL in the email is clicked.

**Comment by galbaras** [comment]
I've had a case where post previewing didn't work with this option turned on. Seemed like WC was overriding URL parameters, rather than extending them, and doing it even on admin pages, which is weird.

**Comment by mikejolley** [comment]
2.4.7 has some tweaks to control 'when' redirects occur. It will now exclude POST requests and will tweak forms on the page to ensure v is present when needed.
