### ISSUE TITLE
[2.4.6] Payment Gateways: All set to null, not able to select a default gateway

### ISSUE THREAD

**Issue by nbyloff** [woothemes/woocommerce#8968]
Running WooCommerce 2.4.6 and I noticed that all payment gateway options are set to display:none. It appears in payment-method.php, when it's checking $gateway->chosen, all Gateways chosen values are set to null.

When I look at line 156 in class-wc-payment-gateways.php, the $default value is an empty string. So I go into the Woocommerce admin settings, and click on checkout. And I no longer see the radio button for setting default gateway? Is this a bug or has it moved?

**Comment by mikejolley** [comment]
Settings > Checkout, top listed gateway is default. They can be drag dropped.

**Comment by mikejolley** [comment]
Confirmed as working - defaults to top listed method.
