### ISSUE TITLE
Cant add featured images/ thumbnails to product

### ISSUE THREAD

**Issue by Sjardo** [woothemes/woocommerce#8969]
Hi guys,

Somehow my thumbnails/featured images cant be added to a product. The theme has support on it (The well known Flatsome-theme). 

It used to work, cause i tried it couple days ago... 

Any idea's?

Systemstatus:

### WordPress Environment ###

Home URL: http://130.211.85.194
Site URL: http://130.211.85.194
WC Version: 2.4.6
Log Directory Writable: ✔ /opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wc-logs/
WP Version: 4.3
WP Multisite: ✔
WP Memory Limit: 64 MB
WP Debug Mode: –
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.26
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.25
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.6
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (3) ###

Contact Form 7: door Takayuki Miyoshi – 4.2.2
Google Analytics door Yoast: door Team Yoast – 5.4.6
Rabo OmniKassa: door Paytium – 1.0.0 – 1.0.1 is beschikbaar

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Winkel basis: #6 - /shop/
Winkelwagen: #7 - /cart/
Afrekenen: #8 - /checkout/
Mijn account: #9 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http://www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.5.6
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome-child/woocommerce/archive-product.php
flatsome-child/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome-child/woocommerce/content-product.php versie 1.6.4 is verouderd. De core versie is 2.4.0
flatsome/woocommerce/content-product_cat.php versie 1.6.4 is verouderd. De core versie is 2.4.0
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php
flatsome/woocommerce/single-product/add-to-cart/simple.php
flatsome-child/woocommerce/single-product/add-to-cart/variable.php
flatsome-child/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php versie 2.0.0 is verouderd. De core versie is 2.4.0
flatsome-child/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

**Comment by mikejolley** [comment]
>  flatsome-child/woocommerce/content-product.php versie 1.6.4 is verouderd. De core versie is 2.4.0
>flatsome/woocommerce/content-product_cat.php versie 1.6.4 is verouderd. De core versie is 2.4.0

**Comment by Sjardo** [comment]
Even with the files updated to the core files from woocommerce, its not working. Using a other theme wont help either. 


### WordPress Environment ###

Home URL: http://130.211.85.194
Site URL: http://130.211.85.194
WC Version: 2.4.6
Log Directory Writable: ✔  /opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/wc-logs/
WP Version: 4.3
WP Multisite: ✔
WP Memory Limit: 64 MB
WP Debug Mode: –
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.26
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.25
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.6
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (4) ###

Contact Form 7: door Takayuki Miyoshi – 4.2.2
Google Analytics door Yoast: door Team Yoast – 5.4.6
Rabo OmniKassa: door Paytium – 1.0.0 – 1.0.1 is beschikbaar
WooCommerce: door WooThemes – 2.4.6

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Winkel basis: #6 - /shop/
Winkelwagen: #7 - /cart/
Afrekenen: #8 - /checkout/
Mijn account: #9 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http://www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.5.6
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome-child/woocommerce/archive-product.php
flatsome-child/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome-child/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php
flatsome/woocommerce/single-product/add-to-cart/simple.php
flatsome-child/woocommerce/single-product/add-to-cart/variable.php
flatsome-child/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php versie 2.0.0 is verouderd. De core versie is 2.4.0
flatsome-child/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

: Meer informatie over het bijwerken van verouderde templates

**Comment by mikejolley** [comment]
So what exactly happens? Errors? Have you tried adding images to posts?

**Comment by mikejolley** [comment]
Will need feedback or I'll have to close this. No other reports.

**Comment by iffifan** [comment]
today i faced same issue with Travelo - Travel/Tour Booking WordPress Theme
http://themeforest.net/item/travelo-traveltour-booking-wordpress-theme/9806696
Before installing wooccommerce everything was fine but after installation i i cannot set featured images even in posts and other pages.
