### ISSUE TITLE
[API] Filter products by tags, attributes or custom taxonomies

### ISSUE THREAD

**Issue by gspereira** [woothemes/woocommerce#8971]
I had a need to query the products I had based off a product attribute (vendor) which I had created to keep track of each products vendor.

The function query_products wasnt acknowledging the "tax_query" array element I sent out, so i made a small change to help with this, and I thought I should share (in case its worth adding .)

        private function query_products( $args ) {

                // Set base query arguments
                $query_args = array(
                        'fields'      => 'ids',
                        'post_type'   => 'product',
                        'post_status' => 'publish',
                        'meta_query'  => array(),
                );

                if ( ! empty( $args['type'] ) ) {

                        $types = explode( ',', $args['type'] );

                        $query_args['tax_query'] = array(
                                array(
                                        'taxonomy' => 'product_type',
                                        'field'    => 'slug',
                                        'terms'    => $types,
                                ),
                        );

                        unset( $args['type'] );
                }

                // Below is the section I added in to help with my query
                if ( ! empty( $args['tax_query'] ) ) {
                        if ( ! empty( $query_args['tax_query'] ) ) {
                                $query_args['tax_query'] = array_merge($query_args['tax_query'], $args['tax_query']);
                        }
                        else {
                                $query_args['tax_query'] = $args['tax_query'];
                        }
                if ( ! empty( $args['tax_query'] ) ) {
                        if ( ! empty( $query_args['tax_query'] ) ) {
                                $query_args['tax_query'] = array_merge($query_args['tax_query'], $args['tax_query']);
                        }
                        else {
                                $query_args['tax_query'] = $args['tax_query'];
                        }

                }

**Comment by claudiosmweb** [comment]
I'll check it for 2.5

**Comment by gedex** [comment]
To make filter consistent with existing product filters (e.g, `category`), I'd propose followings:

filter | type | description
------ | ----- | ---------------
tag | string | Filter products by tag
shipping_class | string | Filter products by shipping class
pa_{attribute} | string | Filter products by attribute

instead of `tax_query` as proposed by @gspereira. Of course, the prefix of attribute can be anything other than `pa_`. However, `pa_` should be more [familiar for REST API consumer](http://woothemes.github.io/woocommerce-rest-api-docs/#line-items-properties).

Thoughts @claudiosmweb @mikejolley ?

**Comment by claudiosmweb** [comment]
@gedex I totally agree :)

**Comment by gspereira** [comment]
Would it be make sense to allow for post_status in the filter too ? It seems to be set to query only published posts at the moment.

**Comment by claudiosmweb** [comment]
@gspereira nop, because we already have a `post_status` filter.
