### ISSUE TITLE
Bug prices for delivery in the new WooCommerce 4.3

### ISSUE THREAD

**Issue by gdgdd** [woothemes/woocommerce#8973]
Since the new update WooCommerce 4.3 there is no longer an option for "postage
for each individual article ", but only two possibilities by
"Class" or "command". Customers pay less for shipping, which is a big
problem!.

**Comment by mikejolley** [comment]
Flat rate?

Use for example `10 * [qty]`

**Comment by mikejolley** [comment]
The example above I gave charges per item.

**Comment by gdgdd** [comment]
The capture (2) is the old version!

**Comment by mikejolley** [comment]
You're not listening to me. The per-item option is not needed. Add * [qty] to your prices.

**Comment by gdgdd** [comment]
I am French, which is why it is a little difficult :)
How do I add  [qty] ?
Thank You

**Comment by mikejolley** [comment]
In the price fields.

**Comment by gdgdd** [comment]
I'm not webmaster, why the update has not done? Is it possible to do the same to you on the site if I give you my codes? S 'Please, it's very hard for me!

**Comment by mikejolley** [comment]
Send me a screenshot of the entire settings page. I'll show you where.

**Comment by gdgdd** [comment]
![cap 1](https://cloud.githubusercontent.com/assets/14005450/9550584/e28a9a82-4db4-11e5-80bc-c98d12cc5d13.PNG)
![cap 2](https://cloud.githubusercontent.com/assets/14005450/9550588/e7c3e904-4db4-11e5-8e48-aef01c00da33.PNG)
![cap 3](https://cloud.githubusercontent.com/assets/14005450/9550597/ed35ad96-4db4-11e5-836f-c5f6b4d559c0.PNG)

**Comment by gdgdd** [comment]
![cap 4](https://cloud.githubusercontent.com/assets/14005450/9550642/29f15d5c-4db5-11e5-832b-b3ccd11703bb.PNG)
![cap 5](https://cloud.githubusercontent.com/assets/14005450/9550647/2e73d9f4-4db5-11e5-8478-ac0b92f234b5.PNG)

**Comment by mikejolley** [comment]
Of the shipping costs you're trying to setup, not the other screens.

**Comment by gdgdd** [comment]
Hello Mike,

Excuse me for this late reply, can you send me a screenshot, or must parameterize because I did not understand our theme the Superstore; Otherwise it is possible to return to the old version, because it is very complicated

**Comment by gdgdd** [comment]
Mike !!
Whaouu I found !!
I'm glad I aujouté "QTY" (yellow) ais ja how to make the price Hours of Operation either with each product as a jewel does not have the same weight as a beauty cream jar?

![qty](https://cloud.githubusercontent.com/assets/14005450/9563394/00ea1986-4e8b-11e5-9910-a8a35bf7748a.PNG)

**Comment by gdgdd** [comment]
I want a fixed price of € 1.50 per order + another prize by item number bought by category.

**Comment by gdgdd** [comment]
Here's what I did? Is it ok? Because I want a fixed price of € 1.50 per order + a price by product and category?

![qty2](https://cloud.githubusercontent.com/assets/14005450/9563618/da5a2c82-4e91-11e5-883d-97373d77f58c.PNG)

**Comment by gdgdd** [comment]
This is Ok, thank you very much :)
