### ISSUE TITLE
Old order download links broken

### ISSUE THREAD

**Issue by douglsmith** [woothemes/woocommerce#8976]
I've gotten occasional customer complaints about download links on older orders not working from the _My Account_ page for a long time. I finally took the time to investigate and collect the details of the problem.

The bad links are in this form. Note that the key parameter is missing. (If it matters, these are all downloads set up using the Amazon S3 extension shortcode.)

`https://example.com/?download_file=766&order=order_509193a262381&email=redacted@hotmail.com&key`

If I edit an order and re-send the _Completed order_ e-mail, that message has a working download link in it.

The orders actually have two rows for the product in the _Downloadable Product Permissions_ section.

<img width="937" alt="pastedgraphic-5" src="https://cloud.githubusercontent.com/assets/2446310/9531751/4532032a-4ccd-11e5-9b9d-2466e79d9e54.png">
 
I see the two records in the database `woocommerce_downloadable_product_permissions` table as well. The older one has a blank or 0 value  in the `download_id` column.

<img width="1311" alt="pastedgraphic-9" src="https://cloud.githubusercontent.com/assets/2446310/9531912/0acddea6-4cce-11e5-9c77-f97a9f60532a.png">

Based on the seeing a large number of records with the same date, I believe the additional records were created by a WooCommerce update. The dates would be consistent with my upgrade to the WooCommerce 2.0.x series, which did change how downloads were handled. I have no idea if the links were a problem back then, though; only that they are broken now.

I determined through experimentation that the _My Account_ page links are pulled from the first database record that is encountered. Even though there is a newer, correct record, that isn't used.

However, e-mailed order receipts use the more recent record so they have a working link.

**Comment by mikejolley** [comment]
I had a quick look and couldn't find it but I do recall some BW compat code for this a long time ago, however, that was just to support these links without keys. It's likely been removed now.

I assume your only resolution is resaving? What % of users does this affect?

**Comment by douglsmith** [comment]
Unfortunately, it's way more than is practical to handle manually. It affects nearly 40% of our customers and 28,677 orders. There are 58,651 rows in my woocommerce_downloadable_product_permissions table with a blank or zero download_id.

**Comment by mikejolley** [comment]
Checked the code base, we actually still have the compatibility code I mentioned.

Found some update logic in 2.0.x which UPDATED old rows, which should not have left the empty rows intact.

Qu; do all broken downloads have the 2 rows? By that logic, would removing all download_id'less rows fix your case?

**Comment by douglsmith** [comment]
Thanks for investigating, @mikejolley. I just checked and pretty much all broken downloads do have the additional row. There are less than 100 that don't, which are probably from where we legitimately removed permission or something. So that should fix it for my case.

**Comment by mikejolley** [comment]
Good to hear. I cannot trace back why this happened; as a said the updater should have done an 'update'. But as it's legacy I'll just keep an eye for more reports in the future. Sorry about the trouble.
