### ISSUE TITLE
Call to undefined function wc_api_hash()

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#8977]
Hi,

I am working with a customer using WooCommerce 2.19. When the user goes to

https://www.schoolsforchiapas.org/wc-api/v1/orders?filter%5Bcreated_at_min%5D=2015-08-26T15:01:41Z&filter%5Bcreated_at_max%5D=2015-08-26T15:01:41Z&consumer_key=XX&consumer_secret=XX&page=1&filter%5Blimit%5D=100&filter%5Bmeta%5D=false

They get this error:

<br />
<b>Fatal error</b>:  Call to undefined function wc_api_hash() in <b>/home/schosorg/public_html/wp-content/plugins/woocommerce/includes/api/class-wc-api-authentication.php</b> on line <b>169</b><br />

The customer is using WooCommerce 2.19. Other than upgrading Woocommerce, how can they resolve this error?

**Comment by claudiosmweb** [comment]
We don't have a 2.19 version.
