### ISSUE TITLE
Woocommerce 2.4.6 - redirect loop on checkout pages

### ISSUE THREAD

**Issue by wsiodelski** [woothemes/woocommerce#8978]
Since I installed woocommerce 2.4.6 yesterday I get redirect loop on My Account page if HTTPS is enabled. If I disable HTTPS it works fine.

**Comment by lbumbalo** [comment]
After installing woocommerce 2.4.6 I get, on checkout page, ajax spinner on shipping method and payment method not disappearing preventing to proceed. If i inspect the page i get a 404 for ?wc-ajax=update_order_review.

**Comment by mikejolley** [comment]
@lbumbalo check for security plugins, and try accessing the endpoint directly. Its just the checkout URL with an extra query string var appended.

@wsiodelski are you using plugins to enable HTTPs on certain pages? What about the force SSL options in WC?

**Comment by wsiodelski** [comment]
hi mikejolley

I had been using Woocommerce but now it gives re-direct loop so instead I had to put a workaround Wordpress HTTPS plugin and specify 3 WC pages:

my account
cart
checkout

At the same time not ticking "force SSL on Checkout at WC level" - it still causes Redirect Loop

At the moment HTTPS works but not displaying the website correctly until I click "allow unsecure content"

So i need to figure out  how I get rid of unsecured content from WC pages which is likely to be a nightmare if not impossible :(

**Comment by wsiodelski** [comment]
so I can force redirection to https://peakart.co.uk/my-account/   via HTTPS plugin but it looks dodgy on the screen until I download unsecured external scripts which by default are blocked

I start doubting it worked properly before WC and Wordpress update I have done recently

**Comment by mikejolley** [comment]
@wsiodelski your issue is your CDN plugin. it's serving everything over HTTP rather than detecting HTTPS. View your page source and you'll see.

**Comment by lbumbalo** [comment]
hi mikejolley,
i don't have any security plugins installed. I'll try to find what is causing the issue.
