### ISSUE TITLE
total_sales meta

### ISSUE THREAD

**Issue by sjeden** [woothemes/woocommerce#8979]
Not sure when this happened or even if its suppose to be right, but it looks like duplicate size in the SQL database that isn't needed.

When i have a product that has not been sold i have in my custom fields section

http://s9.postimg.org/tuaryal4f/Screen_Shot_2015_08_28_at_09_20_52.png

however, when i have a sales i have this for instance

http://s9.postimg.org/b38uo4qjz/Screen_Shot_2015_08_28_at_09_20_38.png

This is on all products.

**Comment by mikejolley** [comment]
Bad import?

We have:

`
add_post_meta( $post_id, 'total_sales', '0', true );
`

The true means $unique flag is set. This prevents multiple meta rows being added.

**Comment by sjeden** [comment]
i can confirm there are multiple meta values in the table too.

http://s24.postimg.org/phn487ow5/Screen_Shot_2015_09_01_at_12_44_14.png

I will take a look at the imports, all done  an completed successfully via csv import suite - i have imported 3 times.

when importing i ignore most columns and just import the fresh stuff.

any information on how to remove this?
