### ISSUE TITLE
Out of stock badge displayed

### ISSUE THREAD

**Issue by esucces** [woothemes/woocommerce#8980]
Out of stock bagde displayed on newly added products even if the status say In stock on backend.

Seems to be a problem for many according to this thread:
http://www.woothemes.com/2015/08/woocommerce-2-4-release/

**Comment by mikejolley** [comment]
Bit of a vague issue report don't you think? https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

**Comment by mikejolley** [comment]
@esucces going to need more details or this ticket will be closed.

**Comment by esucces** [comment]
Sorry for the vague description, here are more details.

Have a look at these products added after update to Woo 2.4.6:
http://www.sportyme.dk/shop/?s=craft+active+comfort
Out of stock message/badge is shown: http://prntscr.com/8a83fx
(on live i temporary changed the text from Out of stock to NYHED (NEW) so that I don't confuse the users)

Looking at a specific product, no badge/message:
http://www.sportyme.dk/shop/craft-active-comfort-rn-kae/

It's variable products, on backend, the product is setup to be in stock.
http://prntscr.com/8a82cc
http://prntscr.com/8a82jp
http://prntscr.com/8a8302

This happens ONLY for newly added products AFTER update to 2.4.6. Products added before update are not affected.

**Comment by mikejolley** [comment]
I tried replicating this the other day without luck.

Can you apply this change and see if it resolves on your store? 1 line to add https://github.com/woothemes/woocommerce/commit/7643712a52803a1971564ff0570972bd43a1a598

**Comment by esucces** [comment]
Added the line, no change :-/

**Comment by mikejolley** [comment]
You have to try a new product or saving existing.

**Comment by esucces** [comment]
Great Mike, saving the product made the problem disappear, thanks for action action so fast!

**Comment by CXON** [comment]
I tried adding this code and also tried making a new product with 24 variations, still no luck. Care to offer any insight? Thanks!

**Comment by mikejolley** [comment]
@CXON you should go through all other suggestions (theme, plugin conflict, above, and read https://wordpress.org/support/topic/24-handling-for-20-variations?replies=1)

@esucces thanks for letting me know. Still odd I cannot do the same, but will be in next release.
