### ISSUE TITLE
Revise how variation selections work.

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8983]
https://wordpress.org/support/topic/multiple-variations-bug?replies=12

cc @jameskoster

**Comment by franticpsyx** [comment]
This is a usual issue when dealing with cascades of dropdowns/steps that have dependent options. The alternative approach is to exclude options based on the selections of previous steps/dropdowns only, and reset any incompatible subsequent selections. This approach, though, works better when enforcing a sequential selection sequence, which is not always ideal (people may want to start with a later option and then go back).

As usual, there is no single approach that works in all cases.

**Comment by jameskoster** [comment]
My gut feel is that changing this behaviour will create more trouble than it's worth. Like @franticpsyx says there's never going to be a one-size-fits-all solution to this.

A separate plugin would be the way forwards imo.
