### ISSUE TITLE
Dynamic Pricing

### ISSUE THREAD

**Issue by luciendub** [woothemes/woocommerce#8985]
![screenshot](https://cloud.githubusercontent.com/assets/5545619/9552434/0c9e92e4-4d86-11e5-9982-066f9a55e138.jpg)

When using Dynamic pricing (official plugin) for specific variations, it seems we can't select the proper variation. I think it should be investigated.

Addition: When searching around, some pretend that last Woocommerce updates broke the plugin-woocommerce compatibility.

**Comment by mikejolley** [comment]
Addon issues need to go via support.woothemes.com so the developers can get involved - this issue tracker is purely for core.

cc @lucasstark
