### ISSUE TITLE
Scheduled Product Publishing Misses Schedule

### ISSUE THREAD

**Issue by bentasm1** [woothemes/woocommerce#8986]
Happens often.  Too often.  Scheduled products miss their schedule an then don't get posted.  High traffic sites, cron enabled, all that fun stuff.  I think it's a good idea for WooCommerce to periodically check for missed scheduled product posts and make them live.  This has been a problem with WordPress for years, so let's figure out a way not to have to rely on their system and provide a fallback.

Thanks!

**Comment by WPprodigy** [comment]
I'm not sure if this is something that belongs in WooCommerce, since the issue seemingly lies with WordPress / Cron jobs, which inherently turns into a server config issue.

This post highlights some good alternatives: http://www.narga.net/how-to-fix-wordpress-posts-missed-schedule-problem/

**Comment by bentasm1** [comment]
I've used that guide before, and do run cron jobs once a minute on the servers.  Still, posts get missed.  The sites average around 60,000 pageviews per day, it's not a low traffic issue.  Quite the high volume stores.

Whether or not the problem is inherent with WordPress (and has been for many, many years), there's no reason we cant code up a little snippet to perform a check by Woo.

**Comment by claudiosmweb** [comment]
This is not a WooCommerce issue, we make no changes to the WordPress publishing scheduling system.
Do as @WPprodigy said.
