### ISSUE TITLE
Product % Coupon not calculating correctly.

### ISSUE THREAD

**Issue by mariahclark** [woothemes/woocommerce#8987]
I have a 10% off one item coupon. I was correctly taking 10%off the most expensive non sale item, but now it is taking the 10% off the first item in the cart. I didn't change anything on the coupon, so it must be a bug.

**Comment by WPprodigy** [comment]
Hi mariahclark,

What settings are you using that says the coupon will only apply to one item in the cart? Is there perhaps a different plugin that added this ability?

**Comment by mariahclark** [comment]
No plugin just standard woocommerce coupon option.

**Comment by mariahclark** [comment]
This is how you limit it to one item, but that isn't the problem at all. 
![usage](https://cloud.githubusercontent.com/assets/8061537/9579569/a9f44eca-4fc1-11e5-8605-000117f7e2d9.PNG)

The problem is which item it is discounting. It is still only discounting 1 item, but now it is discounting the first one added not the most expensive like it did in older versions of woocommerce.
![coupon](https://cloud.githubusercontent.com/assets/8061537/9579704/84d487f8-4fc2-11e5-9482-38d1d7fb42ad.PNG)
Please note the coupon is taking $.50 off not $.65.

**Comment by WPprodigy** [comment]
What version of WooCommerce are you using? 

This is what the current usage restrictions tab looks like: 

![](http://cld.wthms.co/1fkqI/1w3ob0aj+)

**Comment by mariahclark** [comment]
Version 2.4.6

**Comment by mariahclark** [comment]
Mikejolley, I don't understand your post. How do I fix the problem? Is this a new woocommerce bug that they are working on?
