### ISSUE TITLE
"Order Actions" Translation

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#8988]
Hi guys,

RE: https://woothemes.zendesk.com/agent/tickets/327607 

> When viewing an order in WooCommerce admin, there is a translation issue in the box where you save the order.
> 
> The box header says "Order Actions" and the save button says "Save Order".
> 
> In danish i need to use small letters for second work, like "Order actions" and "Save order".
> 
> But the word "Order" is the same in the translation file, so i can't use a small letter for the first character for only one of the occurrences. Can you please split them up in the code, so they can be translated individually?

**Comment by mikejolley** [comment]
@DanielSantoro How does case affect translation?

**Comment by KasperTA** [comment]
The translatable word "Order" is used 2 different places as a part of ["Order" "Actions"] and ["Save" "Order"], so it can't be translated individually. In danish i need to use capital O at the first translation and small o at the second. I can't do that as it is now, so i need you to instead create them as two separate translation texts.

**Comment by mikejolley** [comment]
Both of these 'order' strings mean the shop order and come from the post type:

`
<input type="submit" class="button save_order button-primary tips" name="save" value="<?php printf( __( 'Save %s', 'woocommerce' ), $order_type_object->labels->singular_name ); ?>" data-tip="<?php printf( __( 'Save/update the %s', 'woocommerce' ), $order_type_object->labels->singular_name ); ?>" />
`

I'll add context to the post type translation.
