### ISSUE TITLE
More detailed permissions

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8991]
Can we add more detailed permissions to each API key?

For example I have an app that should be able to read and write products, but not orders or coupons.
Now if I create a read/write API key I can read and write everything.

**Comment by SiR-DanieL** [comment]
I checked the code, i see that it already checks if `current_user_can( 'something' )`. I assume this is already implemented this way, right?

**Comment by mikejolley** [comment]
https://trello.com/c/RHBw4sjr/39-rest-api-add-fine-grain-api-access-control
