### ISSUE TITLE
update_checkout isn't properly run in IE 11 during init_checkout

### ISSUE THREAD

**Issue by EmilEriksen** [woothemes/woocommerce#8992]
This is probably more of an IE bug. You can visually confirm this by visiting the checkout on the [Storefront demo](http://demo2.woothemes.com/storefront/) in IE 11. The BlockUI overlay is missing from order review on load. It happens in both Windows 7 & 8.

**Comment by mikejolley** [comment]
This issue is just a missing overlay, or a loss in functionality?

**Comment by EmilEriksen** [comment]
Unfortunately the fragments aren't replaced. I'm not exactly sure why WC updates the checkout via AJAX on page load but I assume there's a good reason for it so it's a loss in functionality.

This only happens during init_checkout BTW. If update_checkout is triggered at a later point like when you switch shipping methods the fragments are replaced just fine.

**Comment by mikejolley** [comment]
@jameskoster will you take a look?
