### ISSUE TITLE
WC_HTTPS:init() function is running too early

### ISSUE THREAD

**Issue by sh-guti** [woothemes/woocommerce#8994]
I'm working on an e-commerce theme. Trying to hook into the "pre_option_woocommerce_force_ssl_checkout" in order to take the control of the "force checkout ssl" option.
The problem is that `WC_HTTPS:init()` is running too early so my hooks can't take effect.

Maybe the WC_HTTPS::init(); static call should be called like this:
`add_action( 'init', array( 'WC_HTTPS', 'init' ) );`

**Comment by mikejolley** [comment]
@sh-guti Why would a theme need to take over this?

**Comment by claudiosmweb** [comment]
It's necessary for this to work early and maybe it can manipulate the priority (third parameter) of [`add_filter()`](https://codex.wordpress.org/Function_Reference/add_filter).

**Comment by mikejolley** [comment]
Theme's shouldn't be changing this anyway. Force SSL checkout is an option. If it needs to be changed, set the option and hide it.

**Comment by sh-guti** [comment]
Thanks for the response.
@mikejolley, I dont agree with "Theme's shouldn't be changing this anyway" . Every option that from our opinion considered as "untouchable option" or option that can break the website shouldn't be set in the backend, even  by the admin.
For example, you can say the same about the option to "disable woocommerce css",  why dont let the admin the option to disable or enable woocommerce default css ? 
The simple answer is that the line that separate between options that legitimate be in the control of the admin and those that aren't is a matter of point of view.
I understand if to move this hooks ahead is a beat complex and required some additional work, but is something that at least worth to consider.
To hide this option is not a real solution for me.

Thanks anyway.

**Comment by mikejolley** [comment]
@sh-guti It's hooked in early for a reason. Set the option if you don't want the option to be enabled/disabled.
