### ISSUE TITLE
Mobile Admin View

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#8996]
I'm not sure if this is a WordPress thing more than a WooCommerce issue, but the products management section gets a little whacky on mobile.

Posts: http://cld.wthms.co/1iLsO/2m8my7yf
Products: http://cld.wthms.co/15GBE/1rqXDOCs

This is with all columns hidden except for image and title. When you disable the image column, things look a bit better, and the image still shows:

Products w/o image column: http://cld.wthms.co/HH8l/56rNwhGo

I believe WordPress automatically drops the columns on posts down to just the name/title column on mobile, but seems the products image column is not playing nice.

This also applies to the orders page when the "status" column is enabled.

**Comment by SiR-DanieL** [comment]
Same for the orders: http://i.imgur.com/H6OmXXy.png
