### ISSUE TITLE
Needs improvement for order subtotal

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#8997]
Allow us to get the order amount subtotal without any total discount included. The `WC_Order::get_subtotal()` should support the parameter to include or exclude total discount made as our eSewa nepali payment gateway needs both total amount and subtotal amount without any total discount:

> 'tAmt' => WC_Order::get_total()
'amt'  => WC_Order::get_subtotal(), // Here we need the subtotal with all total discount reduced

**Comment by mikejolley** [comment]
The subtotal is WooCommerce's subtotal i.e. what it displays. If you need a different value, you should do the subtraction via your code.
