### ISSUE TITLE
new feature request

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#8999]
Hi there.  in general setting in wordpress has the setting checked "anyone can register" and the bolow setting is set to "customer", it would be a good idea to add a feature that checks the email entered isn't already on the list and whether or not the customer has verified their email address.  this would prevent bogus usernames being created.  so in short, the new customer will need to verifiy their email address, if they don't within lets say an hour, delete that user from the list of users

**Comment by mikejolley** [comment]
Account approvals is plugin territory I think. It would also be quite bad to remove accounts if they make actual orders, because they are paying customers?

perhaps post more details on ideas.woothemes.com so others can back this.

Thanks!
