### ISSUE TITLE
How to save custom meta when creating new customer

### ISSUE THREAD

**Issue by alizainprasla** [woothemes/woocommerce#9002]
how to save custom meta when creating new customer
**https://test.com/wc-api/v3/customers/?consumer_key=123&consumer_secret=123&filter[meta]=true**
{
  "customer": {
    "created_at": "2015-08-31T11:24:56Z",
    "email": "ollee123@example.com",
    "first_name": "John",
    "last_name": "",
    "username": "jkohn.dkkkkkllkknbnlkkoe",
    "password":"asdasd",
    "customer_meta": {
      "custom_field": "1"
    }
  }
}

customer create successfully but custom meta was not there

**Comment by claudiosmweb** [comment]
You don't save any custom data.
If you want more data, you should extend the API by creating a plugin for it.

**Comment by alizainprasla** [comment]
@claudiosan  Thanks you for your advice. Can you please guide me some tutorial or Class to extend WC Rest API?

**Comment by claudiosmweb** [comment]
@alizainprasla need to use `add_action()` and `add_filter()`.
You can see the actions and filters in the classe:
https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-customers.php

**Comment by alizainprasla** [comment]
@claudiosan Thanks for your guidance. 
Its working good as per my require but what should i do for custom route?
