### ISSUE TITLE
Error on checkout page after updating

### ISSUE THREAD

**Issue by superchoward** [woothemes/woocommerce#9004]
Hi,

I have an error on my site which is www.specialistskincare.co.uk which is returned as:

SyntaxError: JSON Parse error: Unrecognized token '<'

This occurs when I go through the checkout process as I enter my billing details and card information which are all entered on the same page.

Any help would be greatly appreciated!

**Comment by claudiosmweb** [comment]
Please, read this https://wordpress.org/support/topic/24-common-issue-syntaxerror-unexpected-token?replies=1
