### ISSUE TITLE
Template override philosophy

### ISSUE THREAD

**Issue by dominic-p** [woothemes/woocommerce#9005]
I'm not sure if this is the appropriate venue for this thought, so feel free to close this and point me elsewhere.

I have noticed in the last 2 major releases a transition from using template overrides to pluggable functions. For example, the HTML for the "Add to Cart" button for variable products used to be located in the variable.php template file (which could be overridden by a theme). As of 2.4, that code is now in a function called `woocommerce_single_variation_add_to_cart_button` which can be overridden by defining a function of the same name.

My 2 cents would be that this is not a helpful change. WooCommerce already has a robust template override system which notifies developers when their overrides are out of date. With the new system, how will devs know if the HTML in their override function needs to be updated? The other issues is that this scatters template HTML over more locations instead of keeping it centralized.

Given the frequency that breaking changes are made to the templates (pulls hair out), this new philosophy could make maintenance a lot harder. I'm imagining a scenario where something breaks after an update, then the theme developers checks out the status page and sees all the template override files are up to date. Now, it becomes a hunt to try to find out which pluggable function was modified. Of course, the version number of the relevant template could be bumped without actually changing the template file (only the underlying pluggable functions), but that would be even more confusing as developers search in vain for a change that isn't there.

Thoughts? Backlash? :)

**Comment by mikejolley** [comment]
Theme authors continue to override/bundle all template files. This is an attempt to move things out of template files which core should control at all times. For example:

https://github.com/woothemes/woocommerce/blob/fd22334fe6db58311ebd591c8ed90455c4777256/includes/wc-template-functions.php#L1906

Thats been broken by themes at least twice in the past, so now its external to the template.

woocommerce_single_variation_add_to_cart_button does not need to be overridden at function level; themes can unhook it, use their own, or include the inputs in their template. Obviously not ideal either, but give this code can change it beats putting it in a template where the theme can break it.

> The other issues is that this scatters template HTML over more locations instead of keeping it centralized.

The above example of wc_dropdown_variation_attribute_options is an example of moving logic out of template files, not just HTML.

> I'm imagining a scenario where something breaks after an update, then the theme developers checks out the status page and sees all the template override files are up to date. Now, it becomes a hunt to try to find out which pluggable function was modified.

If they use pluggable functions then thats at their own risk, and they should be familiar with their own codebase.

**Comment by dominic-p** [comment]
Thanks for the explanation. So, if I understand you right, by moving the code outside of templates, WC is essentially saying "Don't touch this code as it's liable to change." Correct?
