### ISSUE TITLE
WooCommerce new version issue

### ISSUE THREAD

**Issue by nomansbeauty** [woothemes/woocommerce#9006]
Hi,

I am getting this error while theme checking:

WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'woocomerce'

Code can be seen here:
https://www.dropbox.com/s/a1bth4j596sydxr/11.docx?dl=0

We copied templates files from plugin into our theme, rest strings pass well but this one is showing warning. Please help. We searched through files and found its same in WC plugin files too, if we remove text-domain warning goes away but it wont translate the string then.

Please tell us how to resolve it properly so it pass Theme Check?
Thanks alot

**Comment by claudiosmweb** [comment]
This is to help with the WPML, if you are copying to your theme, feel free to change them.

**Comment by nomansbeauty** [comment]
Thanks, but if we remove __ , will it translate?

**Comment by claudiosmweb** [comment]
@nomansbeauty if I'm not mistaken it was added at the request of WPML, then will be without support.

**Comment by nomansbeauty** [comment]
Yes WPML requires it. Also ThemeForest mentioned to add this. But what I am seeing that customers will see problem as the string wont translate then or it will translate even without it?
