### ISSUE TITLE
"SyntaxError: Unexpected number"

### ISSUE THREAD

**Issue by alemarengo** [woothemes/woocommerce#9008]
Hi.
Since 2.4.5 I noticed that customers on my ecommerce can complete an order, but they are stuck on checkout page, showing "SyntaxError: Unexpected number" error.
This happens using BACS payment method.
I did not try paypal. Using paypal payment method, I tried this: go until paypal page, cancel and come back to website: well, a list of n errors appears like never before (as attached screenshot). :(
![screenshot 2015-08-30 09 53 52](https://cloud.githubusercontent.com/assets/6282043/9596849/d20fdf78-507a-11e5-87ab-d0f5e5060be0.png)
Now, I made some tests unsuccessfully, by disabling selectively or totally all plugins and removing snippets. Error always appears after clicking "Place order". The only thing I didn't is change theme, but theme support replied to me they tested latest theme release and latest woo perfectly.
I tried also what you suggest here (https://wordpress.org/support/topic/24-common-issue-syntaxerror-unexpected-token?replies=1) but no way guys :(
This time is the hardest I've ever seen. I do not know what to do.
I always update plugins and make backups, I'm thinking about a woo downgrade. But never done before.
I think the much important thing is to save orders data. Export/import of catalogue would be ok for me.

**Comment by alemarengo** [comment]
Today I received an order with Paypal payment, everything went fine! :)
I think there's something related to different shipment classes I used to set in functions.php (but now are off) to get free shipment in some conditions.
Difficult for me to have an answer about it... :(

**Comment by mikejolley** [comment]
Looks like an issue with your SMTP mail server.

I recommend using MANDRILL and WP SMTP plugin. More reliable, offsite.

**Comment by alemarengo** [comment]
Ok Mike, thanks for your reply.
Anyway, "SyntaxError: Unexpected number" is still there, paypal or not, smtp or not. :(

**Comment by mikejolley** [comment]
@alemarengo it's coming from a gateway. In chrome, if you open up console, network tab, XHR and click on the ajax request, you can see the response. Anything other than JSON is invalid.

**Comment by natsukiss** [comment]
Did you resolve this problem ??????

I've got the same but in two methods of payment.. 

I checked my shop on localhost and everything works fine but when i upload my site to server it crashed... :/

**Comment by alemarengo** [comment]
yep.
Problem was due to a theme customization and a specific plugin conflict.
I simply deactivate every plugin and get rid of any custom. Then reupload everything, but what caused conflict.
Smtp problem are up to my server config.

**Comment by natsukiss** [comment]
So in your case plugin was an issue,.. you know which one exactly ? 
You just turn off the plugins or completely uninstall ?
I will try your way to resolve this problem...

but how explain this, that on localhost everything works fine ??

**Comment by alemarengo** [comment]
My issues:
Ajax Layered Navigation that caused a huge conflict
+
a little theme customization, due to a broken file
