### ISSUE TITLE
Multisite reset passwords error

### ISSUE THREAD

**Issue by rchq** [woothemes/woocommerce#9012]
I think I stumbled upon a bug.

I'm currently running a multisite with several different online stores and was having problems with my customers receiving and error whenever they attempt to reset their passwords, The error read as follows "Invalid username or e-mail.". Upon further inspection I tracked the issue down to [this section of code...]( https://github.com/woothemes/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-my-account.php#L241-L244) I realized that the culprit was [is_user_member_of_blog](https://github.com/WordPress/WordPress/blob/master/wp-includes/user-functions.php#L606-L608). Which is doing a check to see if the site is a multisite and since I am running a multisite it always returns false and triggers the error. 

as a temporary fix I edited [Line #241](https://github.com/woothemes/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-my-account.php#L241) as 
`if ( ! is_multisite() && ! is_user_member_of_blog( $user_data->ID, get_current_blog_id() ) ) {`
but I'm not sure if this is the best way of handling the issue.

**Comment by mikejolley** [comment]
If I understand the logic correct its not a bug; you can only reset your password on a site you are a member. If you try to reset your password on someone else's site, it should not let you.

`is_user_member_of_blog` sees if the user is part of the site they are viewing.

let me know if I'm missing something :)

**Comment by rchq** [comment]
I understand that users should only be able to reset a password for the site that they are members of which is my problem. I have customers on my stores that are registered users but they cannot reset their passwords for the store because `is_user_member_of_blog` will always return false and present that error.

**Comment by mikejolley** [comment]
@rchq if they don't have an account on the store, thats correct.

**Comment by danielhuesken** [comment]
@mikejolley i have a similar problem. The WooCommerce login pages and accout pages are not checking for `is_user_member_of_blog()`. That means i can login with a user that is not registerd for that seite, but the can't do a password reset. Only the password rest and the `WC_Admin_Menus::admin_bar_menus()` checks for that. I think that is inconsistent.
