### ISSUE TITLE
Shipping Class Costs not working at checkout

### ISSUE THREAD

**Issue by forwardmarketing** [woothemes/woocommerce#9013]
Shipping during checkout shows:	Flat Rate (Free)
when it should be set up according to the Shipping Class Costs that were set up. They were working until just a few days ago and we didn't change anything to make it not work. Everything is still selected as enabled so not sure why it's not working now.
Please help!!

http://designsbycozyquarters.com/

**Comment by WPprodigy** [comment]
Hi @forwardmarketing,

I just tested this out on the latest version of WooCommerce and it seems to be working correctly for me. Here is screenshot of my flat rate settings: http://cld.wthms.co/16W3Y/2V7lDER4. When I add a normal product to the cart, I get $0 flat rate returned. But when I add a product with the large shipping class (http://cld.wthms.co/16W3Y/2V7lDER4), then flat rate becomes $5 at checkout.

In this case, this is not a WooCommerce core issue and Github is not the best outlet for support with issues like these. If you can't seem to get it working, feel free to open up a support ticket: https://woothemes.com/my-account/create-a-ticket/

**Comment by mikejolley** [comment]
@forwardmarketing in flat rate settings ensure there are no stray * (). If there are, remove them. Ensure its a valid price in each field.

e.g. 10
or 10 * [qty]

That will solve your issue.

**Comment by forwardmarketing** [comment]
thank you!!

(920).470.7438
1835 E. Edgewood Dr. Appleton, WI

Online Marketing Simplified
Forward-Marketing.net
