### ISSUE TITLE
Ship to different address checkbox isn't working

### ISSUE THREAD

**Issue by amylove** [woothemes/woocommerce#9014]
I have had to comment out the following code in woocommerce/checkout/form-billing.php because it isn’t work properly.

**Comment by WPprodigy** [comment]
Hi @amylove, 

This is likely a theme/plugin conflict. Try disabling all other plugins and switch to a default theme. If this resolves the issue, then slowly enable features until you find the one causing the conflict. 

There isn't anything wrong with WooCommerce core in this case, and this isn't really the best channel for support. Open up a support ticket here for help w/ issues like this  in the future: https://woothemes.com/my-account/create-a-ticket/

**Comment by amylove** [comment]
Thanks. I was told by customer support to submit to this channel.
