### ISSUE TITLE
add new endpoints for account page

### ISSUE THREAD

**Issue by pjyong** [woothemes/woocommerce#9016]
Hi All
I developed my plugin to add some new endpoints into account page, those options could be saved perfectly. But there was no way to visit those new endpoints in frontend customer center, all of them went to 404.
In order to solve this problem, I have to add one new hook into this file.
```
//woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php
++++++from line 56
$end = apply_filters('woocommerce_my_account_continue', true );
if( !$end ){
    return ;
}
```
So in my own plugin, I can use above filter to check $wp->query_vars, if that's my own new endpoint, return false. everything works now.

Do someone know elegant solution for this?I really don't want to change core code. or try to think about adding one solution into release.
Thanks
June

**Comment by mikejolley** [comment]
https://trello.com/c/D3Vo1ccI/55-custom-my-account-page-endpoints?

We don't support theme right now. If you come up with a (more elegant than the above) solution feel free to submit a PR for feedback :)
