### ISSUE TITLE
Problems with `woocommerce_product_subcategories`

### ISSUE THREAD

**Issue by ibndawood** [woothemes/woocommerce#9018]
1. It is coded directly into the `archive-product.php` file and not hooked like all other functions.
2. The default arguments cannot be overwritten via filters and hence it is impossible to modify or control output from `woocommerce_product_subcategories` when called from `archive-product`.

The above 2 problems makes it difficult to code themes. I'd like to know your thoughts on this.

**Comment by mikejolley** [comment]
1. Needs to be within loop. Could be hooked, but would need a new hook. May cause theme compat issues.

2. Could introduce a filter just for the archive for passed in args. Again on compatibility though.

cc @jameskoster  If you have a proposal please submit a PR.
