### ISSUE TITLE
Bulk editing action of api keys doesn't work

### ISSUE THREAD

**Issue by krautnerds** [woothemes/woocommerce#9019]
The "revoke" bulk action for api keys on /wp-admin/admin.php?page=wc-settings&tab=api&section=keys doesn't seem to have any effect.

**Comment by mikejolley** [comment]
Just tested; revoke deletes the key as intended cc @claudiosmweb

**Comment by krautnerds** [comment]
I found the bug! You can reproduce it in a translated version (used translation "de" of transifex) in WC 2.4.6. I will fix it in a second with a pull request. Just a moment!
