### ISSUE TITLE
Ajax checkout can not choose payment - shop broken

### ISSUE THREAD

**Issue by Tobias-Conrad** [woothemes/woocommerce#9020]
HI,

i tried with WP theme fithteen same problem.
http://awesomescreenshot.com/0d457dcm60
![payment-not-clickable](https://cloud.githubusercontent.com/assets/7352673/9639132/cec4aaac-51aa-11e5-940a-0c49d331ab5d.png)

It does not make the payment clickable.
so nobody could buy.

no errors in firebug.

here is my page: http://www.santegra-international.com/checkout/

**Comment by Tobias-Conrad** [comment]
### WordPress Environment ###

Home URL: http://www.santegra-international.com
Site URL: http://www.santegra-international.com
WC Version: 2.4.6
Log Directory Writable: ✔ /usr/www/users/santeh/wordpress/wp-content/uploads/wc-logs/
WP Version: 4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.44
PHP Post Max Size: 15 MB
PHP Time Limit: 500
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.44
Max Upload Size: 15 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.6
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (42) ###

Admin Menu Editor Pro: von Janis Elsts – 1.99
BackupBuddy: von iThemes – 6.3.2.2
Kommentare deaktivieren: von Samir Shah – 1.3.2
Easy WP SMTP: von wpecommerce – 1.1.9
English WordPress Admin: von khromov – 1.5.1
EWWW Image Optimizer: von Shane Bishop – 2.5.0
Indeed My Testimonials (Visual Composer Version): von indeed – 2.9
WPBakery Visual Composer: von Michael M - WPBakery.com – 4.6.1
Layered Popups Add-On - Side Tabs: von Halfdata
Inc. – 1.29

Layered Popups: von Halfdata
Inc. – 4.85

Permalink Finder: von Keith P. Graham – 2.3
WooCommerce Product Filter: von Mihajlovic Nenad – 4.1.2
Code Insert Manager (Q2W3 Inc Manager): von Max Bond – 2.3.3
Recover Abandoned Cart: von Fantastic Plugins – 9.0
Redirection: von John Godley – 2.3.16
Regenerate Thumbnails: von Viper007Bond – 2.2.4
Responsive Mobile-Friendly Tooltip: von ItayXD – 1.5.2
Sidebar Login: von Mike Jolley – 2.7.2
NextScripts: Social Networks Auto-Poster: von Next Scripts – 3.4.22
SEO by SQUIRRLY: von cifi
calinvingan
florinmuresan – 5.2.2

Timed Content: von K. Tough – 2.6
TinyMCE Advanced: von Andrew Ozz – 4.2.3.1
Velvet Blues Update URLs: von VelvetBlues.com – 3.2.4
Widget Context: von Kaspars Dambis – 1.0.3
Widget Logic: von Alan Trewartha – 0.57
WooCommerce Admin Custom Order Fields: von WooThemes / SkyVerge – 1.4.1
WooCommerce Bulk Order Form: von Jeremiah Prummer – 2.2
WooCommerce Checkout Field Editor: von WooThemes / Mike Jolley / Patrick Garman – 1.4.5
WooCommerce DE Avia Themes Anpassung: von InoPlugs – 1.4
WooCommerce Dropshippers: von ArticNet LLC. – 2.0.1
WooCommerce German Market: von Inpsyde GmbH – 2.6.3
WooCommerce Recommendation Engine: von Lucas Stark – 3.0.0
WooCommerce Sequential Order Numbers Pro: von WooThemes / SkyVerge – 1.8.0
WooCommerce Table Rate Shipping: von Mike Jolley – 2.9.0
WooCommerce URL Coupons: von WooThemes / SkyVerge – 2.1.0
WooCommerce: von WooThemes – 2.4.6
WooThemes Helper: von WooThemes – 1.5.9
WP External Links: von Victor Villaverde Laan – 1.80
WP-Optimize: von Ruhani Rabin – 1.8.9.10
Wordpress Rankie: von Atef – 1.3.1
WP-SpamShield: von Scott Allen – 1.9.5.9
WordPress zu Klick-Tipp: von Tobias B. Conrad – 3.0.1 Premium (gültig bis 31-12-2015)

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop-Basis: #1013 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /checkout/
Mein Konto: #9 - /mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Enfold Child
Version: 1.0
Author URL: http://www.kriesi.at
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 3.3.2
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
There are errors on console. And there are no shipping methods showing (I don't have a german address to test).

Rule out all PLUGINS as well as the theme (switch properly, not in preview) to rule out conflicts before posting here. This is not a support area, and this is not a bug report.
