### ISSUE TITLE
Filter for wc_prices_include_tax() conditional function

### ISSUE THREAD

**Issue by dbarproductions** [woothemes/woocommerce#9021]
It would be extremely helpful to plugin extension developers if your function that checks to see if prices include tax had a filter hook on its return value.
wc_prices_include_tax()

Similarly for the tax_display_shop option, although you don't have a conditional function set up for that yet.

Description/Reasoning:

My wholesale ordering plugin is getting very popular, mainly because of the independent tax settings for wholesale vs retail customers.  There are several of my plugin customers that need to have it set so that prices are entered including tax for retail customers, and prices are entered excluding tax for wholesale customers.

Right now I have this working by using the WordPress pre get option hook to change the option value retrieved based on whether the customer is wholesale or retail. However, the caching/session system can sometimes screw this up, especially when the site owner switches their own user account between wholesale and resale while testing. Sometimes the value gets cached at the wholesale setting, and when they switch back to retail the display is wrong even though my plugin is no longer altering the option value. I have found that in those cases, it can only be reset by clearing the browser data, or logging out and then logging back in. So, it seems that these settings may be cached in session data (WC Session?) and need to be cleared first before things start operating correctly again.

With the newer tax laws for B2B vs B2C in many countries, independent tax settings for B2B vs B2C is becoming a big issue, and seems to be the main reason why my extension is getting so popular. It would be great to see some filters/functions to make this easier to alter in WooCommerce!

**Comment by mikejolley** [comment]
`wc_prices_include_tax` isn't like settings which vary based on user. It's based on the prices actually input into products so I'm struggling to see a use case 'why' this should be set by plugins. Regardless of wholesale or retail, prices are still and should still be input consistently.

**Comment by dbarproductions** [comment]
Hi Mike,

Thanks for the reply. I'm not sure I fully understand the "why" of it either, but it has become an issue for some countries, and I have had several customers request that feature, which was a bitch to get working correctly with the way things currently work.  I will have to go back to some of those emails to remember their specific reasons why, but it is really a "user" thing since we are talking about "wholesale" (B2B), versus retail (B2C) customers, which have separate price fields in my plugin.  So, yes, I have to change the settings based on the user that is logged in (my plugin sets up a Wholesale Customer role for B2B and uses the regular Customer role for B2C). I change which prices are shown, the tax rate/class, the way taxes are displayed in shop/cart, and (by demand) whether the prices (which are separate wholesale price fields my plugin creates for each product) have been entered inclusive or exclusive of tax.  They tell me that they are required to do things that way by their new tax laws that regulate online sales.

So, sure, if you are only using the built-in "Regular Price" in WooCommerce, you would never have a need to filter that setting since you would always enter the prices the same way. However, many plugins, not just mine, create additional price fields for different users or roles, so a filter to modify that setting would be extremely helpful.  Since you now have that wc_prices_include_tax() conditional function, the change to add an "apply_filter" around that return statement would be extremely minor and would not break anything that already exists.

**Comment by mikejolley** [comment]
Sounds like a nightmare to be honest. What if you don't have a wholesale price for a particular product, but change the 'wc_prices_include_tax' value? Prices will be wrong.

**Comment by dbarproductions** [comment]
A bit of additional info to hopefully make my case:

I don't know if it's WordPress or something in WooCommerce, but as described in my first post, recently these option values seemed to be getting cached more aggressively, thus causing the wrong value to be returned. After I released an update to my plugin last night, and explain some of the caching/session/transient issues to my customers, and how to clear/reset those, I had a customer in the UK email me this morning about an order that got calculated/processed incorrectly. She had one order in the morning that worked fine (her prices are entered incl tax), but then another order in the evening where taxes were added on top when they shouldn't be, and claims she made absolutely no changes to any settings.

My argument for a filter on that setting would be that I can then bypass any possible caching/session issues by always filtering that setting and returning the correct value. Whereas if I alter the value the way I'm doing via the WP pre_get_option filter, it seems that WP will sometimes cache my altered value. 

So, hopefully you can add that little extra code, and hopefully all other classes/functions are using that conditional instead of reading directly from the option, and then problem solved!

You replied while I was typing this... you said:
"Sounds like a nightmare to be honest. What if you don't have a wholesale price for a particular product, but change the 'wc_prices_include_tax' value? Prices will be wrong."

I have already considered that when first creating my plugin, even before adding the independent tax settings.  My plugin, right now, only changes that prices incl tax setting for wholesale customers (must be logged in to a wholesale custom role).  If there is no wholesale price for a product it does NOT revert to the regular price... there is an option to either show some kind of admin defined "no price" message (and makes the product not purchasable), or there is an option to hide all products that don't have a wholesale price... basically, I have settings that allow them to create "wholesale only" and "retail only" products, that are filtered from the query and made not purchasable for the other type of customer, or just simply shows no price and doesn't allow them to add to cart.

But, yes, you are correct that this whole independent tax settings have been a huge nightmare, and I'm almost sorry I went down that road.  A client in Germany paid me for my time to add those features to my plugin, and it's been a nightmare ever since to get and keep them working correctly with all the different setting combination! Several WC updates have also broken what I originally did, and I have to be creative to make it work!

Thanks so much for taking your time to consider this!!  It really would be EXTREMELY helpful to add the filter to the output of that function, and other conditionals as well!  I would be forever grateful to you!!!!

**Comment by mikejolley** [comment]
@dbarproductions Thinking about cache, I don't think this is going to help you.

pre_get_option is always ran https://core.trac.wordpress.org/browser/tags/4.3/src/wp-includes/option.php#L47 Even if we filtered wc_prices_include_tax, its based on the option so the extra filter will make no difference.

I think you may be instead encountering cache in WooCommerce. We cache prices of variations for example:

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variable.php#L257-L265

This is where you'll need to add something unique based on what you're doing to prevent caching.

**Comment by dbarproductions** [comment]
I have seen some issues with prices being cached and being returned wrong when switching between having admin treated as wholesale or retail. In those situations, I can clear the WC transients in the Woocommerce>System Status>Tools tab, and that fixes the problem. That is not an issue for regular public side customers, since they can't switch back and forth between different customer types (wholesale or retail).  But, thanks for the link to the variations cache, as that may certainly be helpful.

Regarding the prices_incl_tax option and the WordPress cache, I think the problem is that I ONLY change the value of the pre_get_option filter if the user is wholesale. If it's retail, I let it pass through unaltered in case other plugins may also need to modify it for something else. However, if you look at that code for retrieving the options, if I'm not returning false, then it goes ahead and gets the value from the cache (if it exists) instead of doing the database call.  What I can't seem to tell for sure is if I return a different value for wholesale users, is that then getting added to the cache somewhere, because that seems to be what has happened in testing.  Based on the options code, it shouldn't happen within that function, since if I don't return false, then the value I return is immediately returned by the options function.

Does WooCommerce store that value in session data or cache somewhere else?  It's not a price caching issue, but something to do with that prices_incl_tax value sometimes getting cached somewhere... because it's not the price that changes, but the backwards tax calculation that is wrong only sometimes... if I log out, and then log back in to the same account without changing anything in my settings, it works correctly again.

**Comment by dbarproductions** [comment]
I think I will have to do some testing and see what happens if I ALWAYS return something other than false for that pre_get_option, for both customer types, so that the WP options function is never returning a cached value... at least then I can figure out if it's the option cache that is causing a problem, or something that WC is saving in product transients or some kind of session data.  It's definitely separate from the prices issue, though.

**Comment by dbarproductions** [comment]
Expanding on my last comment, that is where the apply filter would still be helpful, so that I can always set the returned value of that option based on customer type and the admin's settings without getting into a potential loop situation by filtering the actual get_option call.  If I try to always return a value for the pre_get_option call, I still need to get the original WooCommerce option value, but that could be affected by either the cache or my own pre_get_option filter, unless I just set up a query to directly retrieve the database value myself.  Just seems easier for other developers in the future if there was a filter on that conditional function.

**Comment by mikejolley** [comment]
You don't have to get the original; you just return the value you want.

I think its likely cache such as whats being discussed here https://github.com/woothemes/woocommerce/pull/9034#issuecomment-137740934 I don't think this filter/option is your problem at all. Filters run everytime an option is called, cached or not.

**Comment by dbarproductions** [comment]
Actually, I do need to get the original when the user is a guest or a retail customer. My plugin has a similar setting, but only for the wholesale prices that wholesale customers see.  So, I still need to know what the regular WC option is.  So, when it's not a wholesale customer, my hook is not replace the filter value, and in those cases it can be returning the cached value for the prices include tax option instead of getting it from the database.  Somehow, those values are occasionally returned wrong (when my plugin in NOT filtering the WC option).

I still believe a filter on that function is the best way to go and easiest for other developers to work with, and would be an extremely minor change in the WC code since that conditional function is already in place and you already have filters on most of the other conditional functions.

But, I very much appreciate you taking the time to discuss this and consider it, and I will find a way to work around the issue by doing a direct database query for the WC option instead to make sure it's not getting cached incorrectly so I can always return some value for the pre-get-option filter. It's not ideal, and it's much more unnecessary code, but I will make it work.

I also appreciate the links to the variations cache thing, which is something I need to address also, but is a separate thing from the above, since the above happens with any type of products.
