### ISSUE TITLE
use filter for post_class in content-product.php

### ISSUE THREAD

**Issue by drrobotnik** [woothemes/woocommerce#9024]
Similar to issue #7923. Currently the top of content-product.php has a grip of $woocommerce_loop conditionals, and then manually adds the result to the post_class( $classes ); function. 

It would be more effective to move the conditionals into a function and apply it with the post_class filter.

This would make it easier for developers to remove if not needed without modifying the templates.

**Comment by mikejolley** [comment]
#9026
