### ISSUE TITLE
Payment label disappears when different payment is selected 

### ISSUE THREAD

**Issue by Rastalamm** [woothemes/woocommerce#9029]
I have two payment options on my checkout page: A & B

When I click on payment option A everything works normally. 

As soon as I click on payment option B, the label for option A disappears. It's like the css property is set to visibility: hidden on option A. 

I do not see any CSS changes, that relate to that element, automatically taking effect when an option is clicked. 

Attached is a screenshot of what I am seeing. 
Option A selected:
<img width="597" alt="option_a_selected" src="https://cloud.githubusercontent.com/assets/9030131/9650455/36e30862-51c0-11e5-9ce2-0cd3a5bc2b14.png">
Option B selected:
<img width="559" alt="option_b_selected" src="https://cloud.githubusercontent.com/assets/9030131/9650454/36e12e70-51c0-11e5-83f6-10f68439b8c7.png">

**Comment by mikejolley** [comment]
Not seeing this locally on any default theme. Need link but you should rule out gateway first.

**Comment by Rastalamm** [comment]
Hey Mike, 

Thanks for replying quickly.

Here is a link to the page but in order to get there you need to register as a user and add something to your cart, then go to the checkout page.

http://spanishvirtually.com/checkout

I tried adding multiple payment gateways and it was still happening, regardless of how many there were.

Please let me know how I can try to solve this. 

Thanks,
Judah

**Comment by mikejolley** [comment]
Due to display:inline label. Block/inline block mess up layout of input and paypal images/link. The label needs to be 100% width.

Enjoy.

**Comment by Rastalamm** [comment]
I removed the label css display:inline and set it to 100% and it worked! 

Now the button and the label are on two different lines :( (which is the reason why I originally set the label to be inline) 

<img width="1090" alt="screen shot 2015-09-04 at 11 24 32 am" src="https://cloud.githubusercontent.com/assets/9030131/9690090/8bbece92-52f7-11e5-94c9-22c7f14cbe25.png">

**Comment by Rastalamm** [comment]
Thank you for all the help!

I kept the display:inline for the label and cloned down the most up to date repo in order to get the changes from jameskoster on the clearfix in the sass and compiled css files. 

Its all working!

Thanks again!!

**Comment by jameskoster** [comment]
You're welcome
