### ISSUE TITLE
Remove Free Shipping when another Shipping Class is in Basket

### ISSUE THREAD

**Issue by LindsayHeydon** [woothemes/woocommerce#9031]
WC Version: 	2.4.6
WP Version: 	4.3

I've created a shipping class for Heavy\Bulky items and also have Free Shipping when a minimum order amount is over 10.00.

Issue is that when an order is both over £10.00 with a standard item in the basket AND also a Heavy\Bulky item then the customer is still offered Free Posting when of course because of the Heavy\Bulky item in the cart would like the Free Shipping to disappear in those circumstances. Have added the below to the functions.php (http://bolderelements.net/support/knowledgebase/hide-shipping-method-when-cart-contains-shipping-class/) but to no avail.

Any idea for a solution? Many thanks.

/**
 * Hide Free Shipping Method When Cart Contains Shipping Class
 **/

add_filter( 'woocommerce_package_rates', 'hide_shipping_when_class_is_in_cart', 10, 2 );
 
function hide_shipping_when_class_is_in_cart( $rates, $package ) {
    foreach( WC()->cart->cart_contents as $key => $values ) {
        // shipping class IDs that need the method removed
        $shipping_classes = array('29','31');
        $if_exists = false;
 
        if( in_array( $values[ 'data' ]->get_shipping_class_id(), $shipping_classes ) )
            $if_exists = true;
    }
 
    if( $if_exists ) unset( $rates['free_shipping'] );
 
    return $rates;
}

**Comment by mikejolley** [comment]
`
$shipping_classes = array( 29, 31 );
`
Class ID is an integer.

FYI github is for bug reports only; please don't post support requests like this here.

**Comment by ChromeOrange** [comment]
@LindsayHeydon try https://gist.github.com/ChromeOrange/9486596
