### ISSUE TITLE
Update Coupon Sale

### ISSUE THREAD

**Issue by caygri** [woothemes/woocommerce#9036]
1st Scenario

If a client make an order with a coupon of 10% of sale, if I need to edit order add/remove products,  coupon price don't update and I can make order pending and  client receive more emails.

2nd Scenario

My client forgot to add a coupon, I can't manually coupon in anyway or status order.

Can you fix it?

**Comment by WPprodigy** [comment]
http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/3867647-ability-to-apply-coupons-manually-when-manually-ad

**Comment by caygri** [comment]
Thank you so much!
