### ISSUE TITLE
Performance issue with WC Layer-Navigation Widget

### ISSUE THREAD

**Issue by Ninos** [woothemes/woocommerce#9041]
If you have lots of products (e.g. > 5000) and use some (4-10) "Layer-Navigation" widgets on product pages (need to be available for products / visible on products pages), the products pages will take a lot of more time to load. In my example ~ 10sec.
I think it's because of the mysql query.

System: Root Server (8 core)
OS: Debian Jessie
Webserver: Apache2.4
DB: MariaDB 10
PHP: php5-fpm v5.6
Wordpress: v4.3
Woocommerce: v2.4.6

PS: I've already done performance optimizations...

**Comment by mikejolley** [comment]
yes this will because it has to do extra queries to get the products 'in view'. Tis cached on first run however.

**Comment by Ninos** [comment]
Where is it cached? Without usage of any object / query / page caches, nothing will be cached. So on a default installation all products page loads are very slow.

**Comment by mikejolley** [comment]
#7806
