### ISSUE TITLE
WooCommerce V4.3 payment issues

### ISSUE THREAD

**Issue by whitemint** [woothemes/woocommerce#9043]
Hi
We have the latest version of woocommerce installed with a "Store" theme.

when proceeding to the payment gateway (Mijreh only, paypal works fine) we get the following error

"•We were unable to process your order, please try again."

Any ideas what would cause this and how to fix it? ( I have have already changed themes and checked for updates to check if nonces are missing and this has NOT fixed the issue)

Thanks

**Comment by WPprodigy** [comment]
Hi @whitemint,

What extension are you using for the Mijreh checkout? This is not the appropriate place for support with this. Github issues here are for WooCommerce related bugs. What you are experiencing is likely not a bug, but just a setup issue.

You should contact the plugin authors of your Mijreh checkout extensions. If WooThemes is the author of the plugin then you could submit a support ticket at https://woothemes.com/my-account/create-a-ticket/

**Comment by whitemint** [comment]
Hi Caleb,

It doesnt make it to the mijreh porthole, just at the point of checkout. It
has started since I updated woocommerce this morning so am sure it is a
woocommerce issue?

Many Thanks

Paul

On 4 September 2015 at 13:39, Caleb Burks <notifications@github.com> wrote:

> Closed #9043 <https://github.com/woothemes/woocommerce/issues/9043>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/issues/9043#event-401090709>.
>



-- 
Paul Cheshire
White Mint Contemporary Home Accessories & Gifts
www.whitemint.co.uk

**Comment by WPprodigy** [comment]
Nope, highly unlikely it's a WooCommerce issue. Check with the plugin authors, or open a ticket if it's a WooTheme's plugin.
