### ISSUE TITLE
Variations add to cart button hidden when variations are out of stock

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9044]
If you have a variable product where all variations are out of stock, you must select a variation to know that the product is out of stock, despite all variations being out of stock.

Should the product display this warning before having to commit to picking a variation?

Also, perhaps rather than hiding the add to cart button with variations, it remains there and gives an error message that variations are needed to be selected?

**Comment by mikejolley** [comment]
The variable product is (or should be) kept in sync with variations. If all are out of stock, so is the parent. This disables the form.
