### ISSUE TITLE
HTML to show the order total for a refunded order is wrong

### ISSUE THREAD

**Issue by khag7** [woothemes/woocommerce#9047]
The Edit Order page includes a meta box which shows the order items and the total. The lien for "Order Total" attempts to take into account any refund and marks that up using `<INS>` and `<DEL>` tags.

`includes/admin/meta-boxes/views/html-order-items.php` Lines 186-192 tries to apply `<INS>` and `<DEL>` tags if a refund exists for the order. However, those tags are already included by the function `get_formatted_order_total()`. 

The tags added by `get_formatted_order_total()` are being stripped and then re-added in the `html-order-items.php`. The result is that the HTML output to the end user has the original order total, the new order total (both struck out with a `<DEL>` tag), and then the new order total (wrapped in an `<INS>` tag).

The image below is a screencap taken from a new install with woocommerce as the only plugin, I did a test order for $10, refunded $7.

![glitch](https://cloud.githubusercontent.com/assets/1531746/9690854/e7fe0640-530c-11e5-95c3-969c8c7248a7.png)

The solution is to modify `includes/admin/meta-boxes/views/html-order-items.php` Lines 186-192 to simply be `<div class="view"><?php echo $order->get_formatted_order_total() ;?></div>`

The end result is shown in the image below
![glitch](https://cloud.githubusercontent.com/assets/1531746/9691071/1f76845c-530e-11e5-9e98-409d58ee5a34.png)

**Comment by zenichanin** [comment]
Same issue happens on the actual orders page that shows a list of all orders.  Which file needs to be changed to fix that?
