### ISSUE TITLE
Multiple customer IP addresses

### ISSUE THREAD

**Issue by tamarazuk** [woothemes/woocommerce#9048]
Regrading [this line](https://github.com/woothemes/woocommerce/blob/0361a10e2653899cf6e97c63b525e04fe5f8c912/includes/wc-core-functions.php#L107), apparently the `HTTP_X_FORWARDED_FOR` header could return two (possibly more) IP addresses as explained in this [post](http://www.jamescrowley.co.uk/2007/06/19/gotcha-http-x-forwarded-for-returns-multiple-ip-addresses/). In ticket [330025](https://woothemes.zendesk.com/agent/tickets/330025), this causes an issue with the Authorize.net AIM gateway. 

I propose that we re-work this to only store the last one as explained in the above mentioned post as well as [here](http://www.howgeek.com/2011/06/04/_serverhttp_x_forwarded_for-returns-multiple-ips-what-to-do/).

**Comment by mikejolley** [comment]
This is handled in our geolocation class. We can reuse that.
