### ISSUE TITLE
Don't rely on an order status to judge if an order needs payment

### ISSUE THREAD

**Issue by khag7** [woothemes/woocommerce#9049]
In 3 places an order's status is checked to see if it is in the list of `woocommerce_valid_order_statuses_for_payment`

But a function exists in the `WC_Order` class which checks this already. `$order->needs_payment()` should be used instead. It relies on `woocommerce_valid_order_statuses_for_payment` anyway.

The three locations I found using `woocommerce_valid_order_statuses_for_payment`:
`includes/class-wc-form-handler.php` line 269 - used for processing the pay form
`templates/myaccount/my-orders.php` line 65 - used to display a pay button to a customer
`includes/shortcodes/class-wc-shortcode-checkout.php` line 87 - used to show the pay page

Again, it doesn't make sense to use an order status to determine if an order has a balance due or not. I am using a plugin which handles partial payments for an order, and I have orders in different phases of production (therefore different statuses) and some still have balances due and some do not. The partial payment plugin I use hooks into needs_payment but your files aren't referencing needs_payment as they should, they're checking against order statuses.

**Comment by maxrice** [comment]
Yeah this is because the order status represents both the financial status of the order *and* and the fulfillment status. I think there needs to be some refactoring to either split the current order statuses into financial/fulfillment, or make them objects so you could have properties, e.g. `processing->paid` would be true, while `processing->fulfilled` would be false.

cc @thenbrent

**Comment by khag7** [comment]
While I agree with what you said I really didn't mean to make the issue
about that. At the end of the day what's important here is that there's a
function called needs payment which should be exclusively used to determine
if an order needs payment or not. I've chosen to hook into the needs
payment function and the expectation is that all places in WooCommerce
should use that function to determine if an order needs payment
