### ISSUE TITLE
Option to remove Wistia

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#9052]
This message

>[Error] Blocked a frame with origin "http://fast.wistia.net" from accessing a frame with origin "http://test.chrome-orange.co.uk". Protocols, domains, and ports must match.

Can cause some sites to not finish loading. It's easy to remove the whole help tab but they can be useful so it would be nice if there was an option to just remove the videos

**Comment by ChromeOrange** [comment]
https://woothemes.zendesk.com/agent/tickets/330476
https://woothemes.zendesk.com/agent/tickets/328912
https://woothemes.zendesk.com/agent/tickets/324580

Code to remove help tabs if anyone stumbles across this issue in the future, just add to your theme functions.php file 

```
add_filter( 'woocommerce_enable_admin_help_tab','remove_woocommerce_enable_admin_help_tab' );
function remove_woocommerce_enable_admin_help_tab() {
	return false;
}
```

**Comment by DavidAnderson684** [comment]
`add_filter( 'woocommerce_enable_admin_help_tab', '__return_false');`

**Comment by mikejolley** [comment]
@ChromeOrange how does one get that error to appear?

**Comment by ChromeOrange** [comment]
@mikejolley just open any WooCommerce settings page

**Comment by mikejolley** [comment]
@ChromeOrange I don't get it, so wondering if there is any specific config required.

**Comment by javorszky** [comment]
I have uBlock origin installed as replacement for AdBlock. This happens on every edit product page:

![](https://cldup.com/RlkDPUkelz.png)

I see that the original issue has been solved by https://github.com/woothemes/woocommerce/commit/a0411e7d8be7378f796455f29578bd39959cecb9, I'm not sure this shouldn't need a "disable videos" checkbox in WC core under settings / privacy.

**Comment by byronyasgur** [comment]
Can anyone tell me why woocommerce is loading these resources - it looks to me like they're for loading videos - i don't understand what they have to do with woocommerce
