### ISSUE TITLE
Missing data in the CSV products export report

### ISSUE THREAD

**Issue by PhilipSheir** [woothemes/woocommerce#9059]
I have over 2,000 products in my products page. However, when I try to export a CSV file for all of the simple products, I realize that the exported CSV file does includes all of the product. It can only export around 1,700 products. The newest and latest products that I have imported in this couple of months are not in there. No matter how many times do I export the data, it still cannot export all of the products. It is a very serious problem for me. Thus, please help me to figure it out.

Thanks,
Philip

**Comment by mikejolley** [comment]
CSV export is not part of core. If this is the WooThemes product csv suite, you can set an offset to export large catalogs. We're working on a different way of export.
