### ISSUE TITLE
woocommerce account pages redirected spam url?

### ISSUE THREAD

**Issue by woont** [woothemes/woocommerce#9060]
Hi,

I installed Woocommerce plugin free.

And I have wrong url's linking, when clicking on the account pages links:
This is the link target of the 'spam':  href="http://shop.giannimarra.com/?controller=404">

My site: <a href="http://woont.be/">
The link with spam: <a href="http://woont.be/mijn-account/">

I presume I am not the only one with such an issue..?

**Comment by mikejolley** [comment]
Replied on .org
