### ISSUE TITLE
Install Pages tool does not find page in trash

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#9061]
Steps to reproduce:
1. In settings, deselect the Shop page. 
2. Then move the Shop page to the trash. 
3. Tools> Reinstall pages. 

In [`wc_create_page()`](https://github.com/woothemes/woocommerce/blob/master/includes/admin/wc-admin-functions.php#L76) the trashed page is correctly identified. But a few lines [later](https://github.com/woothemes/woocommerce/blob/master/includes/admin/wc-admin-functions.php#L76) you only check for the ID and don't test the post status for the page found via SQL. The function then exits early and never gets to [`wp_update_page()`](https://github.com/woothemes/woocommerce/blob/master/includes/admin/wc-admin-functions.php#L85).

**Comment by mikejolley** [comment]
This needs a refactor I think. If a page is trashed, it may be for good reason. And its unreliable to compare content + status.

I think the best way to handle this function is:

1. Check if assigned page is valid
2. Check if page exists (content or name)
3. Create page if the above checks fail.

No updates.

**Comment by helgatheviking** [comment]
:+1: Nice job Mike.
