### ISSUE TITLE
No `Terms and Conditions` checkbox when the order is created from the backend.

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#9067]
**Description**

When an order is created from the backend for a customer by the store administrator and when the customer visits his ```My-Accounts``` page to complete the Pending payment he sees:

![](http://cld.wthms.co/1i99H/5dHNLQRg+)

Now upon clicking the Pay Button the customer sees the ```Pay for Order``` page but there is no indication of the ```I’ve read and accept the terms & conditions``` checkbox that appears on the checkout page during a regular checkout.

![](http://cld.wthms.co/1bztq/1b9iCgom+)

**Concerned Ticket**

https://woothemes.zendesk.com/agent/tickets/329675

**Cc**

@tommyshellberg @slash1andy @stevetested @seanreloaded @BFTrick @ChromeOrange

**Comment by BFTrick** [comment]
People love their ToS can definitely see store owners wanting this. Thoughts @mikejolley ?

**Comment by ChromeOrange** [comment]
https://github.com/woothemes/woocommerce/issues/7252

**Comment by mikejolley** [comment]
@BFTrick Not a high priority tbh. I think this is edge, also only affects people who do manual orders AND have terms at the same time.

**Comment by sjeden** [comment]
Doesnt Germany require there be a T&C box before payment?

**Comment by mikejolley** [comment]
@sjeden there is a german law plugin. Don't get started on German laws :p
