### ISSUE TITLE
The cart is empty

### ISSUE THREAD

**Issue by kevin25** [woothemes/woocommerce#9071]
I used varnish for my Wooecommerce. The cart is empty whenever i add anything. I tried to disable ajax request but no luck. Here are my exeptions:

    ### REMOVE IT IF YOU DO NOT USE WOOCOMMERCE ###
    if (req.url ~ "/(cart|my-account|checkout|addons|/?(add-to-cart=|added-to-cart=))") {
            return (pass);
    }
    if (req.url ~ "/product/*$") {
            return (pass);
    }

     if ( req.url ~ "/?add-to-cart=" ) {
             return (pass);
     }
    if (req.http.X-Requested-With == "XMLHttpRequest") {
            return(pass);
    }

**Comment by mikejolley** [comment]
I'm by no means a varnish expert but how about:

`
 if ( req.url ~ "wc-ajax=" ) {
         return (pass);
 }
`

**Comment by kevin25** [comment]
Thanks, Mike but it didnt work for me.

**Comment by claudiosmweb** [comment]
@kevin25 This depends on your varnish configuration and is not an issue in WooCommerce.
