### ISSUE TITLE
[API] Sending SKU with Variation breaks them

### ISSUE THREAD

**Issue by lileddie** [woothemes/woocommerce#9077]
I am importing products with Variations and each variation having its own SKU via the API. However if I include a 'sku' with a Variation, it does not add them, it adds one Variation as 'default value' and not the individual ones. If I exclude the 'sku' then it works as expected.

This is what I am sending: 
```
[0] => Array
        (
            [sku] => BH2057A
            [regular_price] => 2.99
            [stock_quantity] => 29
            [in_stock] => 1
            [managing_stock] => 1
            [attributes] => Array
                (
                    [0] => Array
                        (
                            [name] => Alphabet
                            [option] => A
                        )
                )
        )
```
This is the variant for 'A', it goes down to 'Z'. the attribute is added on the product fine, as I say this works when I do not include the sku line fine.

**Comment by lileddie** [comment]
It is telling me it is not unique, yet no other products have the sku, the parent is not the same, and there is no other variants on my site.

Why does it think its not unique?

**Comment by lileddie** [comment]
It 'used' to exist as a product, but Ive long deleted it

**Comment by mikejolley** [comment]
This is returning true for you https://github.com/woothemes/woocommerce/blob/9330176865244258a1fdb7c4e170489e4fbf6bb2/includes/wc-product-functions.php#L523-L541

Check your database for the SKU. Perhaps its a hidden variation due to changing the parent product type? Or an orphan. Can happen when importing data.
