### ISSUE TITLE
Option on WP Settings API

### ISSUE THREAD

**Issue by mahype** [woothemes/woocommerce#9087]
Hello,

if I want to have a multiple checkboxes at once on settings pages, I dont have the possibility to add more than one option. It would be very nice if there would be the possibility to give parameter "options" like on radio buttons, to add more than one options to checkboxes.

That would be nice, because it's nearly impossible to add a list of checkable options to a Payment or a Shipment Extension.

Thanks for your help! :)

Greetings,

Sven

**Comment by mikejolley** [comment]
Checkboxes are supposed to be individual options. 

> That would be nice, because it's nearly impossible to add a list of checkable options to a Payment or a Shipment Extension.

Multiselect, enhanced with select2 is how we do it in extensions.
