### ISSUE TITLE
When download limits are reached WooCommerce outputs 2 notices.

### ISSUE THREAD

**Issue by lordspace** [woothemes/woocommerce#9091]
![woocommerce_warning_on_dl_limit](https://cloud.githubusercontent.com/assets/137558/9758892/1241eb2c-56f2-11e5-895e-a0e825bf8ab4.png)

WooCommerce Version 2.4.6

**Comment by mikejolley** [comment]
Should have been resolved here for .7 https://github.com/woothemes/woocommerce/commit/1c68137cf9bf1ae241ee4bf165ffa297e576ce49
