### ISSUE TITLE
Automated Delisting of Products

### ISSUE THREAD

**Issue by deepankarpathak** [woothemes/woocommerce#9092]
We want to delist few products (Expired/discontinued) and want to show them after sometime (as per delivery / classes schedules). How can we hide any product from woo-commerce without showing 404 (or product not found error). 

Any class (is_available) can be molded for same?

**Comment by mikejolley** [comment]
Github is for reporting bugs, not asking for customisations or support https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

You need custom functionality to set the catalog visibility setting per product. If its set to 'none' it will only be accessible directly.
