### ISSUE TITLE
woocommerce - new coupon cannot be created

### ISSUE THREAD

**Issue by ccrg88** [woothemes/woocommerce#9093]
Am unable to create new coupons or edit existing ones. deleting coupons works ok. 
Behaviour: creating new coupon, click on 'publish', and wait - nothing happens for over several minutes. 
The coupon remains in draft mode and cannot be published.

**Comment by mikejolley** [comment]
I'm having no issues publishing coupons and there are no other reports of this. I'd suggest ruling out any other plugins you have installed by deactivating them, and changing theme. Then retesting the publish.

If all else fails, look at the server error logs for notices/errors.

Next time you stop by github, please report your issue only after reading https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md - in general, more information is needed for a valid bug report.

Thanks
