### ISSUE TITLE
Shipping Meta Data

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#9094]
Allow orders to have shipping meta data. This meta data could be used to store information like how many boxes were used and exactly which items go in which box for packing purposes.

> This is really useful for extensions like USPS, UPS, FedEx, etc that pack boxes for you and give you a quote but don't tell you how to pack the boxes. You just have to figure it out yourself.

**Comment by bolderelements** [comment]
+1

I've been asked this so many times by users with all kinds of shipping methods. I've had a client use shipping titles such as Small Box, Medium Box, 2 Boxes, etc... to a customer it's ghastly!

**Comment by corsonr** [comment]
+1 to this, it's a common feature request

**Comment by WPprodigy** [comment]
+1

**Comment by mikejolley** [comment]
Since there are already shipping API changes in https://github.com/woothemes/woocommerce/pull/9826, I'm making this part of the zones PR.
