### ISSUE TITLE
Product Category Widget - incorrect URL

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#9096]
To reproduce:

* both the WooCommerce product category widget and the WooCommerce cart widget are enabled
* the category widget is configured to "show as dropdown"
* AJAX add to cart is enabled
* Redirect to cart after adding item is not enabled
* pretty permalinks are enabled

1. from the shop page, add an item to the cart
2. remove the item from the cart via the red x in the cart widget
3. choose any product category from the product categories dropdown
4. experience the 404 :(

**Comment by mikejolley** [comment]
@WillBrubaker confirmed fix in master. applied to your test site.
