### ISSUE TITLE
Using coupons 

### ISSUE THREAD

**Issue by gregy1403** [woothemes/woocommerce#9099]
During purchase a customer can enter coupon code in shopping cart and recalculate the shopping cart. Then click Proceed to payment or shipping and there is a notice "Have a coupon? Click here to enter your code"

Yes, i have it, i already entered it on prevoius page. Wasn't accepted? I did something wrong? 

Confusing ...

On payment page instead of notice "Have a coupon? Click here to enter your code" we should say something like .. "You already entered "coupon2015" ad we gave you XY discount. Do you have any other coupon to use? Click here"

What do you think?

**Comment by jameskoster** [comment]
I like.

**Comment by kochhase** [comment]
Yes, thats right. my customer are confusing ether. So we need some toolbox after using the coupon code. some notice like "You entered the "couponXXX" we gave you XY discount."

**Comment by WPprodigy** [comment]
What if the text was just replaced to "Have another coupon?" ?

Maybe like:

```
if ( WC()->cart->applied_coupons ) {
	$info_message = apply_filters( 'woocommerce_checkout_coupon_message', __( 'Have another coupon?', 'woocommerce' ) . ' <a href="#" class="showcoupon">' . __( 'Click here to enter your code', 'woocommerce' ) . '</a>' );
} else {
	$info_message = apply_filters( 'woocommerce_checkout_coupon_message', __( 'Have a coupon?', 'woocommerce' ) . ' <a href="#" class="showcoupon">' . __( 'Click here to enter your code', 'woocommerce' ) . '</a>' );
}
```

**Comment by jameskoster** [comment]
Honestly I think it would be better to remove it. If someone has entered their coupon on the cart page it seems unlikely to me that they would then decide to use a different coupon on the checkout page.
