### ISSUE TITLE
Variations Sort Option is confusing

### ISSUE THREAD

**Issue by keninbassart** [woothemes/woocommerce#9104]
Had a customer report that Variation ordering was not functioning because they were changing the order on the menu here: 

![screenshot](http://cld.wthms.co/1d2C6/2dO5Gp2S+)

When I tested I had the same result as well as 2 other Ninjas. Only after some discussion did we realize that the menu ordering there was only for the Admin screen, not the drop down menu the customer sees. The tooltip should be a bit more clear as to what this will change and the solution may be as simple as adding the word "admin" so it reads: "... click to set admin menu order..."

Also, it's not clear that when using custom attributes the order of the variable products on the front end is determined by the order in which they are added on the Attributes screen. Not sure how to resolve this but it's not highly intuitive.

@claudiosmweb  @mikejolley tagging since this continues on from here: https://github.com/woothemes/woocommerce/issues/8690

**Comment by mikejolley** [comment]
> Also, it's not clear that when using custom attributes the order of the variable products on the front end is determined by the order in which they are added on the Attributes screen. Not sure how to resolve this but it's not highly intuitive.

How were you all expecting variable products with TWO attributes to work then?

**Comment by jameskoster** [comment]
> Also, it's not clear that when using custom attributes the order of the variable products on the front end is determined by the order in which they are added on the Attributes screen. Not sure how to resolve this but it's not highly intuitive.

I think this is a documentation thing. It's quite in-depth and would be overly-complex to explain in a tooltip imo.

I agree the tooltip on the variations screen could do with a rewrite to make it more concise/explicit.

**Comment by keninbassart** [comment]
>How were you all expecting variable products with TWO attributes to work then?

TBH not sure. It understand the logic behind setting the order in the Attributes screen however it's not necessarily intuitive. I imagine the majority of the time the individual setting up the site simply creates the attributes in the order intended so for those individuals it's a non-issue. The confusion arises when a user wants to change the order at a later time and doesn't know that the order of the attribute is the determining factor. 

>I think this is a documentation thing. 

Documentation is always helpful, however we know many users only defer to documentation as a last resort. 

>It's quite in-depth and would be overly-complex to explain in a tooltip imo.

Perhaps a simple tool-tip would help even if it's not thorough. Look at this tool tip as an example. It's pretty long and complex:

![upsells](http://cld.wthms.co/1d5Ya/2VtIsdtN+)

What if we added a short tool tip here:

![attributes](http://cld.wthms.co/16yqP/62EtkuOe+)

That said something as simple as: "Order of attributes determines display order in variations drop down"  It's short, concise, rather unobtrusive and should be enough to help users.

**Comment by jameskoster** [comment]
The problem is that only applies to custom attributes. I think it should be fairly obviously that the order they're input in will be the order they're displayed in.

I'm hesitant to add a tooltip that only applies to custom attributes. That might just lead to more confusion.

**Comment by mikeyarce** [comment]
Just to add as a note - I just spent like 30 minutes doing "WHY IS THE ORDER NOT WORKING????"
I think the tooltip will help, but I agree there should be some more explanation that ordering happens in the Attributes and not in the Variations tab.

**Comment by keninbassart** [comment]
Customers still find this confusing as well: https://woothemes.zendesk.com/agent/tickets/345361

**Comment by jameskoster** [comment]
@keninbassart this updated tooltip isn't live yet.

Suggestions are always welcome :-)

**Comment by garymseven** [comment]
I had this issue - would have been much easier to solve if someone posted this image. 
<img width="1348" alt="screen shot 2018-02-08 at 6 52 10 pm" src="https://user-images.githubusercontent.com/36287192/36009578-9873af92-0d01-11e8-9d82-4a08d5b6ff6b.png">
