### ISSUE TITLE
Layered navigation giving 404 error

### ISSUE THREAD

**Issue by tal1481** [woothemes/woocommerce#9105]
Hi this is a strange problem.

I'll do my best to be descriptive...

If you visit our store here http://your-new-site.co.uk/uct/shop/

Follow these steps to recreate the error we are getting:

Under "filter by grade" (in the widget in the sidebar to the right" select "grade A"

When the products have loaded, go back to the widget area in the sidebar and then select the drop down – "filter by colour " and select "Blue"

Once the product has loaded, go back to the sidebar and then select the "filter by grade" drop down menu and select "grade B"

Instead of loading the grade B section – we get a error 404 error?

I am using the latest version of wordpress and woocommerce. Can anyone shed any light onto this problem?

If no product is found matching the filters, then it redirects to themes 404.php; not "no product found" page. So I believe this is a bug.

**Comment by mikejolley** [comment]
This is fixed in master and will be part of 2.4.7.

**Comment by tal1481** [comment]
How do I go about getting the fix? Do I have to wait for it to be released?

**Comment by mikejolley** [comment]
Yes please.

**Comment by tal1481** [comment]
Downloaded and patched the master zip file.

Thanks for the quick support!

Great product!
