### ISSUE TITLE
Make product variation :backorders a readable attribute

### ISSUE THREAD

**Issue by carpe171** [woothemes/woocommerce#9106]
Product variation :backorders is a writable attribute via the POST call, but not a readable attribute included in the response or GET call.

**Comment by claudiosmweb** [comment]
`backorders` affect `backorders_allowed` and `backordered`:

![screenshot from 2015-09-14 13 35 37](https://cloud.githubusercontent.com/assets/1264099/9855590/a22c0b90-5ae5-11e5-81f7-e850fa5d8256.png)
