### ISSUE TITLE
PayPal Instant Payment Notification (IPN) certificate changes

### ISSUE THREAD

**Issue by ace-dent** [woothemes/woocommerce#9107]
No sure whether this is an issue yet... From PayPal:
" PayPal is upgrading the certificate for www.paypal.com to SHA-256. This endpoint is also used by merchants using the Instant Payment Notification (IPN) product. This upgrade is scheduled for 30/9/2015; however, we may need to change this date on short notice to you to align to the industry security standard. ... Full technical details can be found in our Merchant Security System Upgrade Guide . In addition, our 2015-2016 SSL Certificate Change microsite contains a schedule of our service upgrade plan."

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/re-paypal-service-upgrades?replies=1
