### ISSUE TITLE
'Proceed to checkout' in cart page is missing

### ISSUE THREAD

**Issue by Evelyn5899** [woothemes/woocommerce#9111]
Hi, 

Our customber can’t checkout because there is no "proceed to checkout" button on the Cart page. Please kindly advise how to make the button back. 

Thank you.

**Comment by roykho** [comment]
Hello,

Please read the support section of this page https://github.com/woothemes/woocommerce

**Comment by Evelyn5899** [comment]
Hi Roy, 

I didn't find out the solution in your link. Please kindly advise. Thanks.

**Comment by roykho** [comment]
Hello,

So it wasn't a solution but showing you that this is not a support place.  The link shows where you can get support for your question.
