### ISSUE TITLE
Inability to View an Agenda in Daily View in the WooCommerce Booking Calendar

### ISSUE THREAD

**Issue by lisarae1** [woothemes/woocommerce#9112]
We have been using WooCommerce Booking for almost a year now and can not get past the bug that you can not view an agenda in the Daily View in the WooCommerce Booking Calendar. All you see is a big, blue box with an order number in it... How does this help you with what you have booked for the day???????? Yes, you can see the information if you hover over the big, blue box but not everyone has there computer with them to do this. You should be able to see an agenda of who you have booked for the day so you can print it like a Day Timer agenda page. PLEASE FIX THIS ISSUE!!!!!

**Comment by WPprodigy** [comment]
Hi @lisarae1,

This channel is for WooCommerce core related bugs and issues. For problems with Bookings, could you submit a ticket into WooThemes using this link: https://woothemes.com/my-account/create-a-ticket/ ?

Thanks!
