### ISSUE TITLE
Cart gets currency from other blog in multisite install

### ISSUE THREAD

**Issue by raelmiu** [woothemes/woocommerce#9114]
In a multisite install, currency is transferred from the original blog visited to the users preferred blog until the cart is updated.

So this happens:
I have a multisite store, people come to the international store, navigate through to the national store but get a cart that says it's empty displaying the currency of the international site.

Is this set in a cookie perhaps?

**Comment by WPprodigy** [comment]
Hi @raelmiu,

WooCommerce does not currently work in a multisite capacity like that. On a multisite install, WooCommerce acts like any other plugin. Each site in the network, although sharing a database, stores it's information in separate tables. Thus each site/store is a separate and silo'd setup.

While you can network activate plugins, like WooCommerce and it's extensions, you wouldn't be able to share product databases, checkout, user accounts, etc... across the sites in the network at this time.
