### ISSUE TITLE
[API] How to use woocommerce API v3? 

### ISSUE THREAD

**Issue by rebelholic** [woothemes/woocommerce#9115]
Hello,

Could anyone give an example to use JSON API Parameter such as [show products list](http://woothemes.github.io/woocommerce-rest-api-docs/#view-list-of-products) on [this chrome plugin](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo/related)? 

Thanks b4

**Comment by WPprodigy** [comment]
Hi @rebelholic,

I'm not sure how that plugin works, but you would first need to authenticate: http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

After authenticating using your keys, you can get the JSON using the url like - http://test.dev/wc-api/v3/products. Of course, your secret/consumer keys will need to be in the request though - http://cld.wthms.co/1iYpc/5lSFCKhD

**Comment by rebelholic** [comment]
@WPprodigy Yeah its works with curl method but its still get a 404 error if I making integration with my ionic/angular js app. Please check out what's wrong from my services.js script below:

>angular.module('starter.services',[]).factory('Todo',['$http','PARSE_CREDENTIALS',function($http,PARSE_CREDENTIALS){
    return {
        getAll:function(){
            return $http.get('http://localhost:8100/api/products',{
                headers:{
                    'consumer_key': PARSE_CREDENTIALS.consumer_key,
                    'consumer_secret':PARSE_CREDENTIALS.consumer_secret,
                }
            });
        },
       
    }
   }]).value('PARSE_CREDENTIALS',{
    consumer_key: 'insert your key',
    consumer_secret:'insert your key'
   });

**Comment by claudiosmweb** [comment]
Please, read the docs: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by santoshshinde2012** [comment]
@rebelholic You got solution for this ,If got then please mention here.
