### ISSUE TITLE
woocommerce_get_sections_ not working for 'Checkout' tab

### ISSUE THREAD

**Issue by davetgreen** [woothemes/woocommerce#9120]
I'm working on a small plugin that needs to add settings to a sub-section under the 'Checkout' tab.

Creating the sub-section with the `woocommerce_get_sections_checkout` filter works absolutely fine, however when you try to add settings via `woocommerce_get_settings_checkout` it neither works nor makes the `$custom_section` variable available. It generates this error in the admin:

````
Warning: Missing argument 2 for add_plugin_settings() in /srv/www/wordpress-default/wp-content/themes/twentyfifteen/functions.php on line 378

Notice: Undefined variable: current_section in /srv/www/wordpress-default/wp-content/themes/twentyfifteen/functions.php on line 384
````

Quickest way to replicate is to use the Gists found in the official docs below and change the filter names accordingly.

http://docs.woothemes.com/document/adding-a-section-to-a-settings-tab/

**Comment by mikejolley** [comment]
This isn't supported yet. see https://github.com/woothemes/woocommerce/issues/6361

**Comment by davetgreen** [comment]
@mikejolley Is there a recommended 'workaround'?

**Comment by mikejolley** [comment]
I've not looked into it - I just know the same tabs/sections are not used in that screen.

**Comment by davetgreen** [comment]
Hey @mikejolley. Would you be open to a PR for this, or willing to re-visit in a future release?

I've come up against this issue several times, and the docs (https://docs.woocommerce.com/document/adding-a-section-to-a-settings-tab/) do imply that it's possible to use `woocommerce_get_settings_checkout` in the same way you can with `woocommerce_get_settings_products` etc.

As it stands, I can create the sub-section within the Checkout tab using `woocommerce_get_sections_checkout`, but I can't populate it with any settings which is frustrating inconsistent. :) Cheers!

**Comment by Bravehartk2** [comment]
Same here! Any updates on this issue? 
The filter ist used in WC_Settings_Payment_Gateways::get_settings for example:
`return apply_filters( 'woocommerce_get_settings_' . $this->id, $settings, $current_section );
`
where $this->id is 'checkout'. And obviously it works for PayPal and other stuff, why not for me?
