### ISSUE TITLE
sidebar appears twice (on the top) after activating woocomerce plug-in 

### ISSUE THREAD

**Issue by ranulheinzberg** [woothemes/woocommerce#9121]
have a look at:
http://www.ranulheinzberg.at/shop/

where you can see the issue.
pls. tell me what can I do?

best regards,
Ranul Heinzberg.

www.ranulheinzberg.at
kontakt@ranulheinzberg.at

![bildschirmfoto 2015-09-13 um 22 33 15](https://cloud.githubusercontent.com/assets/11291747/9838883/0f9f8652-5a69-11e5-9172-859e1e1976d7.png)

**Comment by mikejolley** [comment]
You need to integrate your theme - http://docs.woothemes.com/document/third-party-custom-theme-compatibility/

Then in your custom template file for WooCommerce pages you can remove or move the get_sidebar call.
