### ISSUE TITLE
Geolocate with page cache support negates caching

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#9122]
On a site with WP Super Cache, the cache filled up with URLs ending in ?v=xxxxxxxx, which basically meant that every page was unique and only shown from cache if the same use reloaded it. I'm pretty sure this wasn't the intention.

[Possibly unrelated:] When using a currency switcher, the unique URL parameter makes the currency switch ineffective, as it simply goes back to the cached version with the original currency.

Seems to me that using a combination of JavaScript and session cookies should allow the URL to be kept clean, which will enable caching as before, but I'm not sure how the code for this works.

**Comment by mikejolley** [comment]
@galbaras definitely was the intention. v= keeps the URL unique to avoid cache. You'll get a different 'v' based on your location/address - this is so you see the correct taxes and prices, since those vary based on your location. Two people from Alabama in the US will see the same cache and same prices.

If its not working for your use case, use the regular geolocation setting.

**Comment by galbaras** [comment]
Like I said, that negates caching and for a site that's mostly a shop, makes caching impossible and slows the store down to a screeching halt.

If the special option for caching doesn't work, you're suggesting the one that doesn't consider caching? How does that make sense?

Come on! The checkout page loads and reloads stuff with every change. Surely something similar can be done on shop pages, where they are mostly loaded from cache and then some little snippet changes the country and/or currency symbol after the page loads. You've done it before.

Since the site I mentioned is based in Australia and sells to Europe and Japan, the Alabama argument really doesn't apply. We're not all Americans.

**Comment by mikejolley** [comment]
@galbaras I don't think you fully understand what the option is doing.

This option prevents caching to prevent users from different locations seeing cached prices. Your Australia users won't be charged the same taxes as the Japanese. If a Japanese user hits pages first, **THEIR prices will be cached for your Australian uses.**

So this option prevents this.

If you don't care about the above, change the option to standard geolocation and cache everything.

**Comment by galbaras** [comment]
@mikejolley This still means that each visitor will end up getting an uncached page initially, which means that most of the page loads will require PHP processing.

For handling taxes on a country basis, country-based caching can be turned on with no need for the URL parameter (there's a WPSC addon that does this). That's a far faster and more efficient option, which mostly serves pages from static/pre-compressed cache.

I still think that WooCommerce's geolocation is used by cart extensions for other things. In a sense, WooCommerce is now a platform and would be best developed as one.

**Comment by mikejolley** [comment]
@galbaras if you're hitting a statically cached page, no PHP runs, so no geolocation can run. Does not matter how fancy your addon is. It cannot run.

Thats why we use ajax > get location > redirect with query string. Bust cache.

**Comment by galbaras** [comment]
@mikejolley I know how caching works. That's why your checkout page runs admin-ajax.php from JavaScript to repopulate shipping, taxes and totals after the visitor changes their country. admin-ajax.php is never cached, so there's no need to have a unique identifier in the URL.

Why not do the same with geolocation on other pages? When caching support is on, default to the store location in PHP (for the best cached version) and update in AJAX when the page loads.

**Comment by mikejolley** [comment]
@galbaras because its not feasible to detect ALL instances of prices on a page because prices can be output from anywhere, by anything.

**Comment by galbaras** [comment]
Would this not work:

1. In the cached page, generated by PHP, store the default country code and country settings, like tax
2. After the page loads, get the current visitor's country code and settings
3. Only replace the contents of elements that adhere to the standard WooCommerce HTML structure

**Comment by mikejolley** [comment]
Yes it would "work" but a) it won't work with prices displayed elsewhere and b) how do you get all prices for each product being displayed. You'd need product ids etc.

**Comment by galbaras** [comment]
Mike, WooCommerce is already quite advanced, well designed and well written. I'm sure that once you guys put your mind to it, nothing will stop you. The combination of shopping and caching just seems to be very common and useful and geolocation can reduce the friction on the way to successful sales.

**Comment by galbaras** [comment]
@mikejolley I've looked at the setting again and the pop-up states it's used to determine the customer's default address before they enter it. Does this have any effect on pages other than the cart and checkout? On all my sites, these pages are excluded from caching and are so small, it's a small price to pay for functionality.

If that's the case, instead of the unique identifier, pages can be blocked from being cached through hooks with known caching plugins and/or a message when WooCommerce is activate and/or a notice next to the geolocate option.

**Comment by wsiodelski** [comment]
Guys I have come across this thread now because this option is basically killing my website and it isnt the lack of caching as such but it is causing hosting Server CPU spike..

I have 2 x Core CPU VDS and both were at 100%... The response time of the website was  6 seconds and changing back to "Default Location" reduced the load time to 2 seconds.

Does this feature require so much CPU or can it be a bug?

**Comment by TiKaWe** [comment]
I like to add, turning on the WooCommerce geolocation with page caching support redirects the visitor 4 times. 

![image-20170916-1810-001](https://user-images.githubusercontent.com/28215673/30527072-ff74f816-9c56-11e7-9151-290da64a5f2e.jpg)

I have another suggestion. For stores which are using NGINX or Varnish, I understand there's a way for either one to retrieve the visitor's geo location, without hitting Woocommerce and causing PHP to run.

https://guides.wp-bullet.com/cache-edd-currency-from-geoip-with-cloudflare-varnish-4/

I assume most store owners will know where the majority of their revenue / customers are from, and will declare the necessary country / currency combinations via their multi-currency plugins in admin settings. If so, is the following possible?

(1) have woocommerce cache plugins (WP-rocket / W3TC / Breeze) "built out" via CRON at the end-of-day/least traffic hours and cache these country/currency combinations in advance?
(2) have Woocommerce these cache plugins link up with NGINX / Varnish and have the latter two serve the correct cached country/currency combinations from the geolocation retrieved from the visitor?

In theory this will still allow the correct currencies / taxes served from cache.

P.S. I dont understand woocommerce code structure well enough. I'm not an expert.

**Comment by mikejolley** [comment]
> If so, is the following possible?

Anything is possible, but I doubt we'll be building anything like that into core. If you're really concerned about performance, don't use this option. You'll still get correct prices + taxes during checkout.

**Comment by galbaras** [comment]
> Yes it would "work" but a) it won't work with prices displayed elsewhere and b) how do you get all prices for each product being displayed. You'd need product ids etc.

@mikejolley Can you please explain? Product IDs shouldn't be difficult to store in a cookie and the rest seems to flow from there, no?

@TiKaWe Please start a new thread for this, as it is a different topic.
