### ISSUE TITLE
Unable to filter or add stock statuses

### ISSUE THREAD

**Issue by andyexeter** [woothemes/woocommerce#9124]
One of our client's asked for a new stock status "Available to order" instead of just In Stock and Out of Stock - I said we would more than likely be able to add this in because WooCommerce gives you control over a lot and allows you to filter a lot of it's values.

I was quite surprised when I looked into it that the In Stock and Out of Stock values are just hard coded and not passed through any filters for developers to hook on to. Is there a reason for this?

I noticed the `woocommerce_product_options_stock_status` action being done below the stock status dropdown and thought I could use that to output an available to order checkbox underneath stock status. The problem with that approach is there doesn't appear to be any action done after the stock status dropdown for variations, only for simple products.

I think there should be a filter for all stock statuses on WooCommerce, and/or an interface in the backend for users to add/edit/delete to match their store's requirement.

**Comment by mikejolley** [comment]
https://trello.com/c/JuJugV5Y/12-custom-stock-statuses-3051
