### ISSUE TITLE
Reports export does not match the reports chart

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#9125]
This is my report at the moment:

![](http://cld.wthms.co/1cewN/3M3azplX+)

and this the exported CSV

```
Date,Number of items sold,Number of orders,Coupon amount,Shipping amount,Gross Sales amount,Net Sales amount,Refund amount
2015-9-14,2,1,0.00,7.00,37.00,30.00,15.00
```

I removed the previous 6 days because they were all 0.

As you can see, the Gross Sales amount in the CSV are 37.00, while in the cart they are 22.00.
The difference is that in the chart the Gross Sales exclude refunds, while in the CSV they don't.

**Comment by SiR-DanieL** [comment]
The same if for Net Sales.

**Comment by gedex** [comment]
@SiR-DanieL could you try branch `issues/9125-report-does-not-match-with-chart` and verify it works as expected?

**Comment by kaviarasukr** [comment]
Hi,

In my case,the chart displays the correct figures, but when i export ,the report is not showing the refund amounts.
