### ISSUE TITLE
Checkout is adding extra items to cart

### ISSUE THREAD

**Issue by keshrao** [woothemes/woocommerce#9126]
Hi,

I'm using WooCommerce version 2.3.8 and WooCommerce Checkout Manager 3.6.8. I have been having a problem where people try to purchase a ticket and it automatically signs them up for 2 tickets. They try to redo it by clicking just 1 ticket but in the checkout process, it makes it 2 tickets again. Any ideas what could be causing this and what we can do about it?

I was referred here from this location but I'm still not sure how to fix it: https://wordpress.org/support/topic/woocommerce-adds-1-extra-item-to-cart

Thanks!

**Comment by mikejolley** [comment]
This is the issue tracker for WooCommerce core, not "WooCommerce Checkout Manager". If its "WooCommerce Checkout Manager" causing your problem, post on their forums.. that ticket is unrelated.
