### ISSUE TITLE
'Proceed to checkout' in cart page is missing

### ISSUE THREAD

**Issue by Evelyn5899** [woothemes/woocommerce#9127]
Hi, 
Our customber can’t checkout because there is no "proceed to checkout" button on the Cart page. Please kindly advise how to make the button back. Thanks.

**Comment by roykho** [comment]
Again, this is not the place for support.  Please use the link I provided previously.

But to try and help, you should start by changing themes, to Twenty Twelve and see if it works then.  That way you know if this issue is caused by your theme or not.
