### ISSUE TITLE
Admin Order Page - Add note defaults to Private Note instead of Note to Customer

### ISSUE THREAD

**Issue by JoseRaffucci** [woothemes/woocommerce#9128]
The default behaviour before the update was for the Add Note section to default to Note to Customer.  We have part of our workflow expecting this and now there is an additional step changing the type of note.

Is there a way for us to change the default back to Note to Customer?

**Comment by bekarice** [comment]
You can default to the customer note instead -- add wherever you keep custom code (custom plugin / functions.php):
```
// Set customer notes as the default order note
function sv_default_customer_order_note() {
	if ( is_admin() ) {
		wc_enqueue_js('
			jQuery("select#order_note_type").val("customer");
		');
	}
}
add_action( 'admin_init', 'sv_default_customer_order_note' );
```

**Comment by JoseRaffucci** [comment]
Much appreciated, worked perfectly!

Thank you again.

**Comment by pdfrequest3** [comment]
I have a custom order note automatically added every time an order is made. Will the code above make my auto-generated custom note set as Customer note? How about setting my custom note as Private?
