### ISSUE TITLE
Brunei Country Name

### ISSUE THREAD

**Issue by slash1andy** [woothemes/woocommerce#9130]
I'm not really certain what should be done in this case, but it was raised in a support ticket that the correct name for Brunei is Brunei Darussalam.

Here is the ticket: 332447

It seems that this is backed up by these links: 

* http://thecommonwealth.org/our-member-countries/brunei-darussalam
* http://www.worldatlas.com/webimage/countrys/asia/bn.htm

**Comment by Kenshino** [comment]
Are we going for qualified names?

We commonly just refer to Brunei as...... Brunei.

If we wanted fully qualified names, Singapore would have to be called Republic of Singapore. That would be rather inconvenient.

**Comment by mikejolley** [comment]
I think its fine to list names however they are used - the translations can be used to tweak if needed. In this case, it makes little different because both start with 'Brunei' so it won't affect position, or the ease of finding the country. Lets leave it.
