### ISSUE TITLE
SKU instead of ID in order notes

### ISSUE THREAD

**Issue by novoopusIW** [woothemes/woocommerce#9133]
During a checkout some note are added. One of them is the note that says

"Item #1942 stock reduced from 254 to 252."

Is it possible to replace the id of the item with its SKU? The sku to be a link which sents to the product?

"Item SKU4436WP stock reduced from 254 to 252."

SKU4436WP to be clickable and to send to product using its ID.

For variations to send the user to the parent product.

**Comment by greguly** [comment]
Added a comment at https://github.com/woothemes/woocommerce/commit/d4fbe0e45cfc58c54845887de21b87c7692a8def
