### ISSUE TITLE
Searching for Products on the Coupon page returns blogs posts

### ISSUE THREAD

**Issue by cutesiness** [woothemes/woocommerce#9137]
On the latest version, when searching products under the "Usage Restriction" tab, it lists out blog posts instead.

![screen shot 2015 09 15 at 11 17 47 am](https://cloud.githubusercontent.com/assets/6559643/9880989/0d2226e4-5b9c-11e5-9727-49269f0b42b9.png)

**Comment by mikejolley** [comment]
Unable to replicate this one. You must have a plugin installed thats changing queries globally e.g. this https://github.com/woothemes/woocommerce/blob/a056e3e6492f55853ab97064df9f24add3277329/includes/class-wc-ajax.php#L1977
