### ISSUE TITLE
Adjust/set price on frontend via js/jquery

### ISSUE THREAD

**Issue by radykal** [woothemes/woocommerce#9140]
A lot of plugins for woocommerce adjusting/setting the price dynamically on frontend via jquery based on some extra modules in the product page, e.g. Product designers, extra product options etc. . All of these plugins using their own technique. 

I am doing that by searching for the price html element via jquery, strap currency, make it to js-friendly number so I can add an extra price, set decimal/ thousand operator, add currency again, update price html element.

The problem is since everyone is using his own technique, that the plugins are not compatible. 

You already have a adjust_price method in php. I would like to a have helper functions in js/jquery that we (developer) can use in the frontend to change price after the product page is loaded.

What do you think?

**Comment by jameskoster** [comment]
Yup, we can add something like this for the next major release. Feel free to send a PR :-)

**Comment by radykal** [comment]
Cool, thank you.

This is the code I am using currently:

```
$productWrapper = jQuery('.post-<?php echo $post->ID; ?>');
function _setTotalPrice() {

	var totalPrice = parseFloat(wcPrice) + parseFloat(customPrice),
		htmlPrice;

	totalPrice = totalPrice.toFixed(numberOfDecimals);
	htmlPrice = totalPrice.toString().replace('.', decimalSeparator);
	if(thousandSeparator.length > 0) {
		htmlPrice = _addThousandSep(htmlPrice);
	}

	if(currencyPos == 'right') {
		htmlPrice = htmlPrice + currencySymbol;
	}
	else if(currencyPos == 'right_space') {
		htmlPrice = htmlPrice + ' ' + currencySymbol;
	}
	else if(currencyPos == 'left_space') {
		htmlPrice = currencySymbol + ' ' + htmlPrice;
	}
	else {
		htmlPrice = currencySymbol + htmlPrice;
	}

	//check if variations are used
	if($productWrapper.find('.variations_form').size() > 0) {
		//check if amount contains 2 prices or sale prices. If yes different prices are used
		if($productWrapper.find('.price:first > .amount').size() == 2 || $productWrapper.find('.price:first ins > .amount').size() == 2) {
			//different prices
			$productWrapper.find('.single_variation .price .amount:last').html(htmlPrice);
		}
		else {
			//same price
			$productWrapper.find('.price:first .amount:last').html(htmlPrice);
		}

	}
	//no variations are used
	else {
		$productWrapper.find('.price:first .amount:last').html(htmlPrice);
	}
        //a hidden input to send the custom price to cart
	$cartForm.find('input[name="custom_price"]').val(customPrice);

};

function _addThousandSep(n){

    var rx=  /(\d+)(\d{3})/;
    return String(n).replace(/^\d+/, function(w){
        while(rx.test(w)){
            w= w.replace(rx, '$1'+thousandSeparator+'$2');
        }
        return w;
    });

};
```

**Comment by jameskoster** [comment]
That's roughly how we do it in our currency converter widget. We'll probably do something like that if we add it to core.

**Comment by BFTrick** [comment]
All of the price changes should be handled in PHP.

Passing a hidden input via JavaScript that changes the price would be _very_ bad as anyone could modify it and pay whatever price they want.

**Comment by johnhearfield** [comment]
When they mean price changes, they mean updating the UI view itself and not the actual price passed back. You shouldnt be passing the price back, but the variant values, such as sizes.

I agree that you should not handle any setting of the price on the UI, as you should never trust the client side, as anyone could input anything.
