### ISSUE TITLE
Global attributes remain attached to product when deleted until product is updated

### ISSUE THREAD

**Issue by anagio** [woothemes/woocommerce#9141]
When a global attribute is deleted it remains attached to the product which you can see outputting ```$product->get_attributes()``` on a product page. While it returns the array of the attribute it's not shown in the attribute table on the front end.

This causes ```has_attributes()``` to return true which is correct since the product does have an attribute still attached, however some may not be aware they need to update the product to remove it.

**Comment by roykho** [comment]
One approach to this is to add a check if the attribute taxonomy exists within here https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L597

And unset the attribute that the taxonomy does not exist and update the _product_attributes postmeta so it will no longer be linked to the deleted attributes.  That works for the backend.  Frontend will need to target a different function which I have not yet looked into.

Thoughts on better approach to this?  @mikejolley @claudiosmweb
