### ISSUE TITLE
Unable to Set Bulk Regular Prices for variations within a variable product to Zero

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#9143]
**Description**

We are unable to set Bulk Regular Prices for variations within a variable product to zero using the **Product Data >> Variations >> Pricing >> Set Regular prices** as below:

**Demo**

![](http://cld.wthms.co/13Nd6/4mMSXGoO+)

**CC**

@tommyshellberg @slash1andy @stevetested @seanreloaded @BFTrick  @ChromeOrange 

**Concerned Ticket**

https://woothemes.zendesk.com/agent/tickets/333065

**Comment by ChromeOrange** [comment]
As a work around you can use the "Decrease Regular Price" options and use 100%

![](https://dl.dropboxusercontent.com/s/x8v37v72z0t2xkn/2015-09-16%20at%2011.34.png?dl=0)
