### ISSUE TITLE
2.4 'average daily sales'

### ISSUE THREAD

**Issue by cdukes** [woothemes/woocommerce#9144]
Hi,

It looks like 2.4 changed the 'average daily sales' on the 'Sales by date' report to pull from net sales, instead of gross sales. 

Before 2.4:
average daily = total sales / days

After 2.4:
average daily = (total sales - refunds - shipping - taxes) / days

The commit that made this change was 6c8cc4287619eab7662a1637d62f305fa5fff33d, with #8028 as the related issue. The issue documents including refunds in the calculation, but _not_ taxes or shipping. 

I understand accounting for refunds in this figure, as that just updates the report to include new WC functionality, but including taxes and shipping changes what this number means, which I can't find a documented reason or discussion for. 

Was this intentional? If not, can we change it back? =) I have some confused clients.

```
// Calculate average based on net
$this->report_data->average_sales = wc_format_decimal( $this->report_data->net_sales / ( $this->chart_interval + 1 ), 2 );
```

to

```
// Calculate average based on gross
$this->report_data->average_sales = wc_format_decimal( $this->report_data->total_sales / ( $this->chart_interval + 1 ), 2 );
```

**Comment by mikejolley** [comment]
Intentional yes - shipping and taxes are not 'sales' technically.. I think either way *some* groups of users won't like the change?

**Comment by cdukes** [comment]
@mikejolley 

A couple thoughts:

1. As you said, shipping and taxes aren't sales. I think they're also less likely to accurately reflect real costs/provide useful data. For example, I can charge a flat rate of $50 on shipping, but pay $45 on some orders and $60 on others. I might setup state taxes in WC, but not bother with odd municipal taxes.
2. Was there any issue arguing for making the change? If it ain't broke and all =)
3. Maybe show two lines? 'average daily gross sales' and 'average daily net sales'?

**Comment by BFTrick** [comment]
Hey @jameskoster I think we should do this. We would be adding one extra line in the graph. Split `average monthly sales` into `average net sales` & `average gross sales`.

<img width="822" alt="reports_ _woocommerce_ _wordpress_and_inbox__11__-_bftrick_gmail_com_-_gmail" src="https://cloud.githubusercontent.com/assets/1065372/10222878/9d017730-6856-11e5-818b-7bf61ecf584a.png">

We should probably add this in 2.5.

**Comment by jameskoster** [comment]
Happy. Would be much quicker if someone else handled this though xD
