### ISSUE TITLE
UPDATE PRODUCT Method sets price and regular_price to 0.00 ( API v2 + API v3) #16

### ISSUE THREAD

**Issue by yatanasov** [woothemes/woocommerce#9147]
GET
{
"product": {
"title": "Дамски боти в черно с връзки и заден цип",
"id": 47655,
"price": "199.00", - THE PRICE IS CORRECT
"regular_price": "199.00", - THE PRICE IS CORRECT
etc .....
etc ...........
}
}

"PUT" :
https://website.com/wc-api/v3/products/47655/?consumer_key=ck&consumer_secret=cs

DATA:

{
"product": {
"regular_price" : "106"
}
}

RESPONSE:
{
"product": {
"title": "Дамски боти в черно с връзки и заден цип",
"id": 47655,
"price": "0.00", ???????????? why is it 0 ?
"regular_price": "0.00", ?????????????? why is it 0 ?
etc .....
etc ...........
}
}

Please advice or investigate as soon as possible.

Thanks for your efforts.

Best,
Yordan

**Comment by claudiosmweb** [comment]
=/

![screenshot from 2015-09-16 18 09 49](https://cloud.githubusercontent.com/assets/1264099/9918606/3303b514-5c9e-11e5-8ed4-4be5c6d7441c.png)


https://github.com/woothemes/woocommerce#support
