### ISSUE TITLE
Reviews: Jetpack Comments conflict with Reviews

### ISSUE THREAD

**Issue by Warpsmith** [woothemes/woocommerce#9152]
As reported here:
https://wordpress.org/support/topic/jetpack-conflict-with-review-tab

If Jetpack's comments module is active, the review tab in WooCommerce product pages stops functioning.

**Comment by mikejolley** [comment]
@BFTrick you were looking into this?

**Comment by kraftbj** [comment]
Jetpack needs to add a better way of disabling the comments module by CPT than is currently available. Being tracked (above) in the JP repo.

**Comment by BFTrick** [comment]
@mikejolley I don't see this taking the JetPack team too long (They're pretty cool people from what I hear). Let's leave this open now that it's properly tracked in GitHub and try to fit it into 2.5.

**Comment by kraftbj** [comment]
Jetpack PR in progress: https://github.com/Automattic/jetpack/pull/2936

**Comment by claudiosmweb** [comment]
@kraftbj thanks :)
