### ISSUE TITLE
Admin Variable Product UI: All Variations are hidden after changing/saving attributes

### ISSUE THREAD

**Issue by krautnerds** [woothemes/woocommerce#9154]
After saving the attributes on a variable product all variations are collapsing without a reason. Only a click on the pagination brings them back.

Steps to reproduce:
1) Open variable product with at least 1 variation
2) Go to the attributes and change some (variation) attributes
3) Go to variations tab and you will see no variations despite there are 12 in my case: 
<img width="951" alt="screenshot 2015-09-17 22 39 28" src="https://cloud.githubusercontent.com/assets/7906407/9945344/0bd607ea-5d8d-11e5-88cd-feca9b665597.png">

**Comment by mikejolley** [comment]
I fixed this in master.

**Comment by krautnerds** [comment]
Good to know ;) Thanks!
