### ISSUE TITLE
US/Canadian phone numbers with leading "1" corrupted by PayPal gateway

### ISSUE THREAD

**Issue by siliconforks** [woothemes/woocommerce#9156]
Steps to reproduce:

1. On the checkout page, enter a US or Canadian address and a phone number with a leading 1, e.g., `1-555-555-1234` or `+15555551234`
2. Select the PayPal payment gateway and submit.
3. On the PayPal page (you may have to click the option for people without a PayPal account), the phone number is displayed as `155-555-5123` or `+15-555-5512` (for the first and second example phone numbers above, respectively).

**Comment by claudiosmweb** [comment]
Weird, but make sense.
