### ISSUE TITLE
Underlying shipping method html code revealed in Orders list

### ISSUE THREAD

**Issue by jimu001** [woothemes/woocommerce#9159]
We have a technical issue relating to how our shipping methods are displayed. They are displayed properly in the Cart and Checkout views, however, in the wp-admin Orders and Order Details views they are displayed improperly, revealing the underlying html code. 

Here are some pictures so that you can see what I mean...
![woo_cart](https://cloud.githubusercontent.com/assets/414337/9952631/641279de-5dd8-11e5-875a-4c6093fc118c.jpg)
![woo_checkout](https://cloud.githubusercontent.com/assets/414337/9952661/9fe00968-5dd8-11e5-934a-4111022099d0.jpg)
![woo_admin_orders_list](https://cloud.githubusercontent.com/assets/414337/9952698/ffa308aa-5dd8-11e5-90fc-2806d0970dc4.jpg)
![woo_admin_order_details](https://cloud.githubusercontent.com/assets/414337/9952707/2246b67c-5dd9-11e5-96df-a699f6f945b3.jpg)

To me it seems that if the shipping method "label" is displayed correctly on Cart and Checkout then it should be handled the same way on other views. 

Please have a look at the code and see if this can be adjusted!

**Comment by mikejolley** [comment]
Labels shouldn't contain HTML - they are escaped in several places. Could add filters to list extra data, but using label is not ideal.

**Comment by jimu001** [comment]
The labels used to display the other order items (products) contain HTML, so why shouldn't a shipping method being displayed as another item not be able to contain HTML? Our shipping method labels containing HTML are being handled nicely by your Cart and Checkout code (not escaped in several places perhaps), so why can't the Order admin views be adjusted to do the same? 
Our customers who are WooCommerce customers want the functionality provided when the label contains HTML, like a link to a map showing where the shipment can be picked up.

**Comment by claudiosmweb** [comment]
We can stop use `wp_kses_post()` on frontend and start use `sanitize_text_field()` on frontend and admin. So no more HTML in anywhere.

**Comment by jimu001** [comment]
Hi Claudio and Mike,
I hope you are joking. Your last suggestion would destroy my intended solution instead of making it possible. Why do you want to do that? Showing some html in the shipping method label is good for woocommerce, not bad. So why don't you seem to agree? What's the problem with allowing a plugin to display html in the label text?
Best regards, 
Jim Mulshine
Fraktjakt AB

**Comment by jimu001** [comment]
We'll just try adding filters. Thanks for your help.
/Jim

**Comment by claudiosmweb** [comment]
@jimu001 as @mikejolley said:

> Labels shouldn't contain HTML

So the best is stop it for good.

**Comment by mikejolley** [comment]
The label itself could be used in many places @jimu001 - e.g. outputting in a PDF. Obviously html won't work there, so it just be test based.

Extra description should be added elsewhere, or via hooks.
