### ISSUE TITLE
orderby filter parameter doesn't work for /customers/<id>/orders

### ISSUE THREAD

**Issue by pschael** [woothemes/woocommerce#9162]
I like to sort orders by date. A query on:
`/orders?filter[order]=DESC&filter[orderby]=date`

will return a sorted result.
If I want to sort orders from a specific customer, the orders are **not be sorted**: 
`/customers/2/orders?filter[order]=DESC&filter[orderby]=date`

**Comment by claudiosmweb** [comment]
This come as a feature for WooCommerce 2.5.

**Comment by basanthalluri** [comment]
Hi @claudiosanches,

I am using woocommerce 2.6 api but still didn't work for me. I am using node js

app.get('/api/products',function(req,res){

  WooCommerce.get('products?orderby=slug&order=desc',function(err, data, res1) {
    var json=JSON.parse(res1)
    res.send(json)
  });
})
