### ISSUE TITLE
Deleting a wordpress user should affect shop orders belonging to that user

### ISSUE THREAD

**Issue by khag7** [woothemes/woocommerce#9166]
Default behavior in WordPress:
When you are deleting a user, you are prompted to choose who to attribute posts which belong to the user being deleted. WP will update the post_author to the chosen user.

In WooCommerce:
After a user is deleted, any orders which that user is the selected customer (i.e. '_customer_user' has their user_id) aren't affected. Those orders are still linked to the deleted user, but the customer drop down box on the edit order page has user 0 selected. Its a little confusing.

Proposal:
Orders should, at the very least, be updated so that _customer_user is changed to 0 when a user is deleted. This means the order is now a "Guest" order which is logical because there is no longer a user account to associate the order with.
`"UPDATE `wp_postmeta` SET meta_value=0 WHERE meta_key='_customer_user' and meta_value={$old_user_id}"`

Maybe even better:
If the option is selected to re-attribute posts from the deleted user to a different user (standard WP behavior), we could hook into the `deleted_user` action and use it to re-attribute the deleted user's orders to the different user.
`"UPDATE `wp_postmeta` SET meta_value={$new_user_id} WHERE meta_key='_customer_user' and meta_value={$old_user_id}"`

I'm not convinced that the solutions I propose are perfect behavior, but I don't think its good either to have _customer_user with a value that links to a user that no longer exists. Thoughts?

**Comment by maxrice** [comment]
:+1: this is particularly troublesome when fetching orders via the REST API, since it also retrieves the associated customer for the order. If a customer has been deleted it returns an error for the customer object, whereas it'd be nicer to return a valid object instead.

**Comment by khag7** [comment]
The other nice thing this allows is for a way to merge customer accounts. I have some customers who have used two different email addresses when checking out. I will be able to merge their accounts simply by deleting account 2 and re-attributing content to account 1.

**Comment by BFTrick** [comment]
Hi @khag7 we like the first proposal. Reassigning a user shouldn't be done on deletion in most cases. If you do have duplicate users we should build some new UI to merge user accounts (probably under the tool menu or in the System Status)

If you want to help could you please send a new pull request which does the following:

* When deleting a user change the `_customer_user` to `0` so they're marked as a guest.

Merging can be useful but would be tricky to implement so we don't want to add that to WooCommerce core right now.

**Comment by mikejolley** [comment]
@jeffstieler

**Comment by garrett-eclipse** [comment]
Not sure if this is helpful to you guys, I implemented this function in my installation as I had alot of duplicate customers and wanted to merge them so tied into the delete_user action to associate orders to the reassigned user and grant them downloadable permissions on those orders.

```php
<?php
    // Delete User Action to Attribute Order on Reassignment
    function attribute_user_content($user_id) {

        if ( empty( $user_id ) )
            return;

        if ( $_SERVER['REQUEST_METHOD'] != 'POST' || empty( $_POST ) )
            return;

        if ( ! isset( $_POST['action'] ) || $_POST['action'] != 'dodelete' )
            return;

        if ( ! isset( $_POST['delete_option'] ) || $_POST['delete_option'] != 'reassign' )
            return;

        if ( ! isset( $_POST['reassign_user'] ) || empty( $_POST['reassign_user'] ) )
            return;

        $reassign_user_id = $_POST['reassign_user'];

        // Get User Objects
        $user = get_userdata( $user_id );
        $reassign_user = get_userdata( $reassign_user_id );

        // Get User Meta
        $user_meta = get_user_meta( $user_id );
        $reassign_user_meta = get_user_meta( $reassign_user_id );

        // Re-Associate Orders
        $user_orders = get_posts(
            array(
                'post_type'     => wc_get_order_types(),
                'post_status'   => 'any',
                'numberposts'   => -1,
                'meta_key'      => '_customer_user',
                'meta_value'    => $user_id

            )
        );
        if ( ! empty( $user_orders ) ) {
            foreach( $user_orders as $order ) {
                // Get Order Meta
                $order_meta = get_post_meta( $order->ID );

                // Associate New User
                update_post_meta( $order->ID, '_customer_user', $reassign_user_id, $user_id );

                // Update WC Information
                update_post_meta( $order->ID, '_billing_first_name', $reassign_user->first_name, $user->first_name );
                update_post_meta( $order->ID, '_billing_last_name', $reassign_user->last_name, $user->last_name );
                update_post_meta( $order->ID, '_billing_email', $reassign_user->user_email, $user->user_email );
                update_post_meta( $order->ID, '_shipping_first_name', $reassign_user->first_name, $user->first_name );
                update_post_meta( $order->ID, '_shipping_last_name', $reassign_user->last_name, $user->last_name );

            }
        }

        // Re-Associate Product Downloadable Permissions
        $user_downloads = wc_get_customer_available_downloads( $user_id );
        if ( ! empty( $user_downloads ) ) {
            foreach ( $user_downloads as $download ) {
                $download_order = new WC_Order( $download['order_id'] );
                wc_downloadable_file_permission( $download['download_id'], $download['product_id'], $download_order );
            }
        }

    }
    add_action('delete_user', array($this, 'attribute_user_content'), 5);
?>
```

Sorry if it's not appropriate to comment here, feel free to can my comment.

I just realized if you're attributing _customer_user you'll also want to update the name/email information as well.

Cheers
