### ISSUE TITLE
Restrict coupons by custom taxonomies

### ISSUE THREAD

**Issue by lawkwok** [woothemes/woocommerce#9168]
You can only restrict coupon usage based on category and specific products, but not by taxonomy.

**Comment by claudiosmweb** [comment]
If is a **custom** taxonomy, you need to write **custom** code to do that.

**Comment by tommypicard** [comment]
@lawkwok did you ever figure out how to do this?

**Comment by lawkwok** [comment]
@tommypicard Unfortunate not. I ended up assigning products I wanted excluded from promotions to a category. I then excluded that category in the coupon settings.

**Comment by kmcaloon** [comment]
+1. This would be such a helpful feature.

**Comment by cedriccharles4** [comment]
Hello !

Does someone figure how to achieve that out ?
Thank you in advance !

**Comment by swatiag1101** [comment]
Hi everyone, I am also looking for the exact same feature. Any help would be appreciated.
Thanks!

**Comment by fearlex** [comment]
+1 here !

**Comment by drs-nyc** [comment]
Looks like someone wrote a plug-in for this request.
https://wordpress.org/plugins/taxonomy-discounts-woocommerce/#developers

Appears to be working. I'll be testing on a site and will add to code if necessary.

**Comment by unrealthemes** [comment]
I also ran into this problem
there is a suitable plugin
[https://wordpress.org/plugins/woo-custom-taxonomies-coupons/](url)
