### ISSUE TITLE
WordPress Core Term Metadata

### ISSUE THREAD

**Issue by dominic-p** [woothemes/woocommerce#9169]
I'm sure you guys are aware of this, but just in case you weren't, I wanted point out this [Trac ticket](https://core.trac.wordpress.org/ticket/10142) on bringing taxonomy term metadata support into WordPress core.

I know WooCommerce currently implements its own term meta system via a custom table. Are there plans to ditch the WC system in favor of the core implementation when it lands? If so, do you know if the API (`*_woocommerce_term_meta` functions) will change?

**Comment by claudiosmweb** [comment]
Yes, we are and will be easy support that.
However it's too early to think about it. Depends on being really implemented on WP core, we can think about it probably for WooCommerce 2.6

**Comment by dominic-p** [comment]
Glad to know the team is on top of things. Thanks.
