### ISSUE TITLE
CSS Select Options (variable button)

### ISSUE THREAD

**Issue by gabthemonster** [woothemes/woocommerce#9170]
Hi, 

I am using the CSS code below and it adds a nice hover to my add to cart button. However, the select options button for variable products does not take the hover. Is it supposed to work? any thoughts on how to get it work? 

Thank you, 

.woocommerce a.button:hover,
.woocommerce .products .product_type_variable:hover,
.woocommerce .product_type_variable:hover,
.woocommerce .products .product_type_variable,
.woocommerce button.button:hover,
.woocommerce input.button:hover,
.woocommerce #respond input#submit:hover,
.woocommerce #content input.button:hover,
.woocommerce-page a.button:hover,
.woocommerce-page button.button:hover,
.woocommerce-page input.button:hover,
.woocommerce-page #respond input#submit:hover,
.woocommerce-page #content input.button:hover {
	background-color: #FFFFFF;
	color: #000;
}

**Comment by claudiosmweb** [comment]
I don't see any selector for `select` elements.
This is not an issue with WooCommerce.
