### ISSUE TITLE
Can't view order in my account page. it redirect to edit-account page

### ISSUE THREAD

**Issue by sornanun** [woothemes/woocommerce#9171]
I can't view order in my account page. 
when I click on view button it redirect to edit-account page.

**Comment by claudiosmweb** [comment]
What "view button"?

**Comment by claudiosmweb** [comment]
Is your theme replacing the WooCommerce templates?

**Comment by sornanun** [comment]
Please visit this site. http://horpakpim.esy.es/%E0%B8%9A%E0%B8%B1%E0%B8%8D%E0%B8%8A%E0%B8%B5%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%89%E0%B8%B1%E0%B8%99/ 
The site is in Thailand But you can translate with google it. Then login with  username : test  and password : test , You will see look button. When you click view button it should be redirected to the page view order. But it redirects to edit account. I use MyStile theme. And I don't Know my theme is replacing the WooCommerce templates or not. Sorry about the language. My English is not good
Thanks for reply.

**Comment by khag7** [comment]
Sounds like you have the short codes woocommerce_view_order and woocommerce_edit_account mixed up on the wrong pages. Also that means you're on an old version of woocommerce, since those short codes aren't used anymore

**Comment by claudiosmweb** [comment]
This is a problem with the translation into your language.
I just fixed it, please go to WooCommerce > System Status > Tools and click in the **Force Translation Upgrade** button.
