### ISSUE TITLE
woocommerce Rest api Nodejs library issue with list of all Orders

### ISSUE THREAD

**Issue by rchowdary** [woothemes/woocommerce#9172]
woocommerce Rest api Nodejs library issue with list of all Orders brings back only the latest order but not all of them.

 WooCommerce.get('orders', function(err, data, res) {
        //JSON.stringify(res);
        console.log(res);    
       //  myData = JSON.parse(res, function (key, value) {
       //          var type;
       //          if (value && typeof value === 'object') {
       //              type = value.type;
       //              if (typeof type === 'string' && typeof window[type] === 'function') {
       //                  return new (window[type])(value);
       //              }
       //          }
       //          return value;
       //      });
       // console.log(myData);
    });

**Comment by claudiosmweb** [comment]
Wrong place for report it.
Use the library repo.

**Comment by claudiosmweb** [comment]
And please, read the docs.
There have answers about it and how to get all requests at once.
