### ISSUE TITLE
When saving variations object cache isn't being cleared.

### ISSUE THREAD

**Issue by SeenNotHurd** [woothemes/woocommerce#9173]
Have not been able to test this with all variation options but when changing the value of 'Enabled' with object caching enabled, the value is saved correctly in the database but WooCommerce still loads the old value.

**Comment by khag7** [comment]
I am having this issue as well. The only thing I noticed it for was for the "enabled" checkbox but didn't thoroughly test anything else.

I wasn't sure if the database was saving correctly or not, so I just manually set the options in the database where I needed, but that's obviously not ideal.

**Comment by SeenNotHurd** [comment]
At least in our case we were using Redis object caching, and it seemed that the values saved to the database (but then didn't refresh the cache) and WC pulled values from the cache, so they were getting stuck.

**Comment by lkraav** [comment]
Simple workaround for 2.4 is to just fire that `clean_post_cache( $variation_id );` call from `woocommerce_update_product_variation` action.
