### ISSUE TITLE
Variable product price error (same price for regular and stock price)

### ISSUE THREAD

**Issue by lumierestudios** [woothemes/woocommerce#9174]
Hi, I have a problem with the visualisation of the regular and stock prices.
I need to swap the regular and discount price on variable and simple products.

I have tried with this code but the price swap work for simple products and not for variable products:

```
add_filter('woocommerce_sale_price_html', 'wdm_change_price_text', 10, 2);
add_filter('woocommerce_variable_sale_price_html', 'wdm_change_price_text', 10, 2);
/*add_filter('woocommerce_variation_sale_price_html', 'wdm_change_price_text', 10, 2);*/
/*add_filter('woocommerce_free_sale_price_html', 'wdm_change_price_text', 10, 2);*/


function wdm_change_price_text( $price, $this_object ) {
    $display_price       = $this_object->get_display_price();
    $display_regular_price   = $this_object->get_display_price($this_object->get_regular_price());
    $price='<ins>' . wc_price($display_price) . '</ins>' . $this_object->get_price_suffix() . '<del>' . wc_price($display_regular_price) . '</del> ';
    return $price;
}
```

I'm able to see the correct regular and stock price only for the simple products but, for the variable products, I see the same price for regular and stock.

To check the page you can go here:

http://www.danistoreonline.com/shop/

As you can see, with the difference of the only two simple products (bag and shoes), all the other products that are variable products, show me only the stock price for both the regular and stock price.

Please, exist a fix for this problem?

Thank you
-Enrico

**Comment by claudiosmweb** [comment]
**stock price**? What's this?
I saw a few pages of your store and found nothing strange.
You also is not using the native WooCommerce variables but using a plugin to modify the way they are displayed (can be the problem).
