### ISSUE TITLE
create order with hebrew text using the api retuns an error

### ISSUE THREAD

**Issue by junkqwe2** [woothemes/woocommerce#9177]
I am using woocommerce Version Version 2.4.6. 
I am creating an order using the API successfully. 
The entire order text is in English. Once there is Hebrew in one of the fields (billing addres first name for example), I am getting an error when trying to create the order.

The error i am getting is: woocommerce_api_missing_callback_param Any ideas how to fix it? i tried to encode the text to unicode string but the string is not being decoded back to hebrew when the order is created. There is no problem to create an order with Hebrew in it using the regular website (not using the api)

**Comment by claudiosmweb** [comment]
Show me your json data.

**Comment by junkqwe2** [comment]
here is the json.
The hebrew is at  "billing_address" > "first_name"
If i put there "test" the order is created

{
    "order": {
        "status": "pending",
        "currency": "ILS",
        "total": "3980.00",
        "subtotal": "3980.00",
        "total_line_items_quantity": 2,
        "total_tax": "0.00",
        "total_shipping": "0.00",
        "cart_tax": "0.00",
        "shipping_tax": "0.00",
        "total_discount": "0.00",
        "shipping_methods": "",
        "tax_lines": "",
        "fee_lines": "",
        "coupon_lines": "",
        "payment_details": {
            "method_id": "bacs",
            "method_title": "test",
            "paid": "true"
        },
        "billing_address": {
            "first_name": "בדיקה",
            "last_name": "test",
            "address_1": "test",
            "address_2": "",
            "city": "test",
            "country": "",
            "postcode": "12",
            "email": "tomer1@tomer.com",
            "phone": "1234567"
        },
        "shipping_address": {
            "first_name": "test",
            "last_name": "test",
            "address_1": "test",
            "address_2": "",
            "city": "test",
            "country": "",
            "postcode": "12"
        },
        "customer_id": 88,
        "shipping_lines": [
            {
                "method_id": "flat_rate",
                "method_title": "FlatRate",
                "total": 10
            }
        ],
        "line_items": [
            {
                "product_id": 870,
                "quantity": 1
            },
            {
                "product_id": 870,
                "quantity": 1
            }
        ]
    }
}

**Comment by junkqwe2** [comment]
Problem solved
I am using the API with c#
I added encoding to the webclient and it solved the problem:

WebClient wc = new WebClient();
wc.Headers[HttpRequestHeader.ContentType] = "application/json";
wc.Encoding = Encoding.UTF8;

**Comment by claudiosmweb** [comment]
:)
