### ISSUE TITLE
Import of German transifex language files is wrong on translate.wordpress.org

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#9179]
At the moment the import from transifex to  translate.wordpress.org is totally wrong for german. Please fix the initial import for the German translation files as follows:

1. Please import the files from https://www.transifex.com/woothemes/woocommerce/language/de_DE/ to [German → German (Formal)](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/de/default)
2. Please import the files from https://www.transifex.com/woothemes/woocommerce/language/de/ to [German](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/de/formal)

This must be done for [stable](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable) and [dev](https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev) sub-projects.

**Some background information about why it is the way it is now:**

The situation at transifex for WooCommerce was always as follows:
> Project description:
>
> Here you can contribute localisations to WooCommerce. Please when requesting a translation, ensure you use the WordPress codes from http://wpcentral.io/internationalization/ e.g. es_ES (Spanish Spain) over just es.
> 
> Exceptions:
> 
>   de_DE (German (Germany)) is the formal "Sie" variant of German
>
 >   de (German) is the informal "du" variant of German

For various (historical) reasons this is different from how it has always been done for WordPress (it was always considered to have a formal wording as default for a WebShop like WooCommerce, whereas it was considered more appropriate to have informal wording as default for a blogging software like Wordpress). Hence the import needs to be done different.

**Comment by claudiosmweb** [comment]
We can't do that. Once imported, we can't import again.
You will be translate reviewer and will have a chance to correct it.

**Comment by jnachtigall** [comment]
@claudiosmweb Can I import a po file then? I do not want to manually copy and paste 3500 (already translated) strings one by one ;)

**Comment by claudiosmweb** [comment]
@jnachtigall I don't know. I just know that we as plugin authors, we are not able to import again any .po file for any language.

Please read:
https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/

> 1. Eventually, all active plugins will be imported into translate.wordpress.org and made available for translation. However, we will import them in phases.
> 2. Upon import, if you have any translations, **we will import them into translate.wordpress.org. This only happens during initial import**.
> 3. Before importing your plugin, we will email you when your plugin is in the next “batch” of imports. You should ensure that all translations are up-to-date.
> 4. If you do not wish to use language packs, you may continue to ship translations with your plugin.

**Comment by jnachtigall** [comment]
@claudiosmweb Can you please get in contact with the owners of translate.wordpress.org and make them aware of the problem. I am sure it is better if you do it (as plugin owner) as if I would do (as just any reviewer/user). I can noway manually import 3500 strings and days(!) of work would be lost...

**Comment by claudiosmweb** [comment]
@jnachtigall Nop! Under any circumstances!
But you can do it, you can contact the reviewers WordPress de_DE and ask for their help. They will be able to do this.

**Comment by claudiosmweb** [comment]
Understand that it is not because we are the authors of the plugin, we'll have any kind of privilege or tools... Because we don't!
You turning a reviewer, will have more freedom for the `de_DE` translations than the plugin authors.

**Comment by claudiosmweb** [comment]
Here, try this editors: https://make.wordpress.org/polyglots/teams/?locale=de_DE
Then CAN help you.

**Comment by jnachtigall** [comment]
ok.

@claudiosmweb  have you already assigned the role reviewer to me? Then I can see what I can do.

**Comment by claudiosmweb** [comment]
@jnachtigall To be honest, I think that when you become an editor/reviewer, you should be able to import and export. It happens to WP core editors.
I can't add you as a editor now, we need wait for all the others transifex reviewers.

Please read:
https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/#requesting-new-translation-editors

**Comment by ocean90** [comment]
@jnachtigall This has been corrected now.

**Comment by claudiosmweb** [comment]
@ocean90 :heart:

**Comment by jnachtigall** [comment]
@ocean90 Thanks :+1: just out of curiosity, how have you done it? Are you a reviewer of WC or WP core already?

**Comment by claudiosmweb** [comment]
@jnachtigall WP core editor: https://make.wordpress.org/polyglots/teams/?locale=de_DE

**Comment by ocean90** [comment]
@jnachtigall I'm the technical point of contact of all the i18n stuff around w.org which includes translate.wordpress.org. :)

**Comment by shivapoudel** [comment]
@claudiosanches Where should I request to be WooCommerce Translation Editors for Nepali (ne_NP) locale?
