### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by jontest2008** [woothemes/woocommerce#9180]
I just updated to 2.4.6 and I don't see the featured image on the right side. Can anyone tell me why this is? Thank you.

**Comment by Kenshino** [comment]
Look at the top right hand corner, click Screen Options and see if you have 'Featured Image' checked.

**Comment by claudiosmweb** [comment]
Thanks @Kenshino

**Comment by jontest2008** [comment]
![not](https://cloud.githubusercontent.com/assets/14502122/9998892/5f266792-6048-11e5-863b-58f9ef2e57b5.JPG)

**Comment by jontest2008** [comment]
there is no options there to pick.

**Comment by jontest2008** [comment]
This is all I have that is coming up.....
![not](https://cloud.githubusercontent.com/assets/14502122/9998948/a2468d72-6048-11e5-885c-4bd8fd26993c.JPG)

**Comment by askaryabbas** [comment]
Please add the code :
add_theme_support( 'post-thumbnails' ); 

in your function.php file
