### ISSUE TITLE
"Allowed Countries" setting is restricting billing address (not just shipping address) - followup

### ISSUE THREAD

**Issue by ralphmorris** [woothemes/woocommerce#9184]
I am experiencing the same issue as in the ticket below but can't seem to find a resolution. Was there ever a fix for this as I can't see anything new in the settings. My client only wants to ship to the United Kingdom but wants to accept billing information from anywhere in the world. Is this possible?

https://github.com/woothemes/woocommerce/issues/3215

Any help really appreciated.

Thanks

Ralph

**Comment by WPprodigy** [comment]
Hi @ralphmorris,

Yea, the above issue was resolved.

So the setting in general options applies to the billing country, as it says "This option lets you limit which countries you are willing to sell to". So for your case, you will want to leave this to all countries. - http://cld.wthms.co/1ihwi/13vV5Z3G

Then in the shipping method(s) you are using, you can add a rule to only ship to the UK: http://cld.wthms.co/F7kl/1ujyqS3Q

**Comment by ralphmorris** [comment]
Hi @WPprodigy 

Many thanks for your reply and screenshots. Much appreciated. It is working perfectly!

Thanks
Ralph
