### ISSUE TITLE
Update variable product (regular_price, sale_price, price_html and possibly others) not working

### ISSUE THREAD

**Issue by yatanasov** [woothemes/woocommerce#9188]
/products/ endpoint sets price and regular_price to 0.00 

This happens only with VARIABLE product. Simple product is OK.

Example:

GET
{
"product": {
"title": "Product title",
"id": 47655,
"regular_price": "19" - THE PRICE IS CORRECT
etc .....
etc ...........
}
}

"PUT" :
https://website.com/wc-api/v3/products/47655/?consumer_key=ck&consumer_secret=cs

DATA:
{
"product": {
"regular_price" : "10"
}
}

RESPONSE:
{
"product": {
"title": "Product Title",
"id": 47655,
"price": "0.00", ???????????? why is it 0 ?
"regular_price": "0.00", ?????????????? why is it 0 ?
etc .....
etc ...........
}
}

This is not a support issue. This is a major bug in the API. Please investigate.

**Comment by claudiosmweb** [comment]
@yakirgot this is not a major bug!
Works fine, see: https://cloudup.com/c3cJjxZxnZq

**Comment by claudiosmweb** [comment]
>This happens only with VARIABLE product. Simple product is OK.

Because you can't set any price for variable products!
You need to set prices INSIDE each variation!
