### ISSUE TITLE
Rest API v2 and v3 order payment method update not working

### ISSUE THREAD

**Issue by calvinlyc** [woothemes/woocommerce#9189]
Hi, I have created an order via rest api with Paypal payment details and paid as false. Then I got Paypal 
IPN data and I'd like to update the order

Here's the sample request via PUT method to 
https://localhost/wc-api/v3/orders/153?consumer_key=ck&consumer_secret=cs

 {
  "order": {
       "payment_details": {
             "method_id": "paypal"
             "method_title": "PayPal",
             "transaction_id": "12345678",
             "paid": true
        }
   }
}

However, the response with 200 OK still contains the paid as false and transaction id has not been updated correctly.

I try to google around and had no luck, hope I can get some helps here. Thanks

**Comment by claudiosmweb** [comment]
What is the order status?
Is order total greater than zero?
