### ISSUE TITLE
Request: Don't hide the add to cart button

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9190]
I've mentioned this a few times now, but I still feel strongly about it.
I don't think the add to cart button should be hidden, ever.

Relating to this issue still: #1984, i'm still not 100% sure why this hasn't been discussed more

I have the same issue with every site I build. Variations hide the add to cart button and any additional prices that occur from other woothemes plugins such as product add ons. 

When no variations are selected, there's no price, no add to cart etc. This is counter-intuitive with design and forces a jQuery Slidedown to reveal it when variations are selected. 

Is there any room for putting forward any of the suggestions from the previous issue?

**Comment by claudiosmweb** [comment]
You need just to select the "Default Form Values" in variations tab.

**Comment by yratof** [comment]
What's the default dress size?

Kind regards

Andrew

**Comment by claudiosmweb** [comment]
@yratof use your imagination ;)

**Comment by yratof** [comment]
In all seriousness though, I don’t have a default dress size, I certainly don’t want to force my customers to think “they think I should be a 10?” or “they think i should be 18?”

What other major websites pre-pick sizes for you and hide the add to cart button otherwise?

**Comment by claudiosmweb** [comment]
> I certainly don’t want to force my customers to think “they think I should be a 10?” or “they think i should be 18?”
See, you've got to use your imagination.

**Comment by yratof** [comment]
My imagination is telling me a combination of no default and #9200
