### ISSUE TITLE
Featured Image

### ISSUE THREAD

**Issue by jontest2008** [woothemes/woocommerce#9192]
I still have my issues! But it was closed. I was told "Look at the top right hand corner, click Screen Options and see if you have 'Featured Image' checked." 
I looked and I do not see this option! Please Help I do not what I am doing wrong.
![not](https://cloud.githubusercontent.com/assets/14502122/9999363/d777920a-604a-11e5-9eb6-3eecb394173d.JPG)
![not](https://cloud.githubusercontent.com/assets/14502122/9999376/eabb14ea-604a-11e5-8cf2-d80d67fa7fbd.JPG)

**Comment by claudiosmweb** [comment]
Theme releated, not an issue with WooCommerce. Maybe even some plugin disabling it.
Please test before open an issue.

**Comment by jontest2008** [comment]
I don't get why it gets closed before I can say anything! and its not working for me.

**Comment by claudiosmweb** [comment]
@jontest2008 It's not a WooCommerce issue.
