### ISSUE TITLE
Fee API - Multiple same-name fees

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#9193]
If you add multiple fees with the same name, only one will display. Would it be possible to add another parameter to <a href="https://github.com/woothemes/woocommerce/blob/3e55364e3a1ecf0dc93bd796c51cd85093de5127/includes/class-wc-cart.php#L1909">add_fee()</a> that can make the fees distinctive of each other w/o altering the visible fee name?

I believe WordPress does this with transients?

**Comment by claudiosmweb** [comment]
Why use the same name for all?
If all fees has the same name, why not make a sum of the total value?

**Comment by WPprodigy** [comment]
In some cases a store might have fees specific to a product, and the fees could be named the same on some occasions.

That could be a good option though. If there are multiple add_fee()'s with the same fee name, could they just be appended together rather than overruling each other?

**Comment by claudiosmweb** [comment]
I will see if it is possible to do this.

**Comment by mikejolley** [comment]
I think stacking fees could be problematic. User should merge fees in their own code and add once.
