### ISSUE TITLE
Samsung Country and State Selector Drop-Down Glitch

### ISSUE THREAD

**Issue by Stormlilly** [woothemes/woocommerce#9195]
When testing on Samsung Galaxy 4 phone the Country and State dropdown selector boxes auto-close before I have a chance to select my Country or State.  It appears to be a bug.

Tested on multiple themes with latest Wordpress and Woocommerce 2.4.6

**Comment by claudiosmweb** [comment]
@jameskoster can you check it?

**Comment by jameskoster** [comment]
Yup, will probably look at this tomorrow.

**Comment by jameskoster** [comment]
Played with this a bit but couldn't find anything obvious. Tried versions 3.5.4 and 4.0.0 and they don't fix.

Found this issue on the select2 repo which seems to describe the issue we're having; https://github.com/select2/select2/issues/2606 Claims that 4.0.0 fixes but didn't for me. 

Needs further digging.

**Comment by BFTrick** [comment]
This only affects a particular phone and an older one at that. Since it's not a show stopper (you can click it a second time and it works) we're going to close this issue. If other android users have this problem feel free to reopen.
