### ISSUE TITLE
Cannot add variation to cart without javascript enabled

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9200]
Accessibility issue with adding to cart:

To recreate, conditions are:

- No variation selected by default
- Javascript disabled

The add to cart button never shows when selections are made, this is because `display: none` is hard coded into this button, rather than it being added with javascript.

Another reason why #1984 and #9190 were brought up and should be revisited, not just shook off and claiming to use 'imagination' to fix these issues.

**Comment by claudiosmweb** [comment]
@yratof no worry, I'm choosing dresses sizes for you ;)

**Comment by yratof** [comment]
@claudiosmweb thanks...

**Comment by claudiosmweb** [comment]
@yratof see if this size is right for you: https://github.com/woothemes/woocommerce/tree/variations-hijax :)

**Comment by yratof** [comment]
@claudiosmweb the shoulders fit fantastic, especially without javascript – if only the waist was a little trimer and showed the add to cart button constantly ;)

**Comment by claudiosmweb** [comment]
Don't close just yet, I'm testing it to make sure it will function well without javascript ;)

**Comment by claudiosmweb** [comment]
Need some tweaks, but almost there.

**Comment by centurypixel** [comment]
Has this been implemented?  I just had my client and his customer not able to make a purchase because the 'Add to Cart' button as missing.

In Magento, the button is always visible, and warns the user if they click the button without making the selection.
