### ISSUE TITLE
jQuery event name typos

### ISSUE THREAD

**Issue by aaemnnosttv** [woothemes/woocommerce#9202]
jQuery events `contry-change.woocommerce` should be `country-change.woocommerce`.

[Search results](https://github.com/woothemes/woocommerce/search?utf8=%E2%9C%93&q=contry-change.woocommerce) as of woothemes/woocommerce@06d31d1f86c5029dc102830d7c6ede37986fe8b5

Specific references:
- [admin/users.js#L65](https://github.com/woothemes/woocommerce/blob/62d879e86cb5901864045a4774e93ddf9d378991/assets/js/admin/users.js#L65)
- [admin/meta-boxes-order.js#L74](https://github.com/woothemes/woocommerce/blob/7e63374aafe2b75cb3457b4d9601e1ceda6f5e95/assets/js/admin/meta-boxes-order.js#L74)

**Comment by claudiosmweb** [comment]
Wrong commit reference ^
