### ISSUE TITLE
coupons on cart (Click on the coupon to use it)

### ISSUE THREAD

**Issue by david2k** [woothemes/woocommerce#9204]
Available Coupons (Click on the coupon to use it) only works when a user is logged in, for guest this does not work

**Comment by WPprodigy** [comment]
Hi @david2k,

Are you referring to Smart Coupons: http://docs.woothemes.com/document/smart-coupons/ ?

If so, could you submit a ticket to WooThemes here: https://woothemes.com/my-account/create-a-ticket/? This channel is for WooCommerce core issues, not extension support. Thanks.

**Comment by claudiosmweb** [comment]
This is not a WooCommerce issue as @WPprodigy said.
