### ISSUE TITLE
Woocommerce Create Order Api

### ISSUE THREAD

**Issue by ZayleWy** [woothemes/woocommerce#9205]
Hi there, i have some query to clarify for woocommerce create order api.

The API function name = create_order($data)
i wants to know what kind of data structure is parse in to $data? and i also have woocommerce points& reward extension, not sure this api works with the point deduction or not? I am trying to call this api function from mobile app what kind of data structure is use for $data please give me an example or idea Thanks.

IMPORTANT NOTE*  let say i make payment in the mobile using paypal already and wants to create the order from here by calling this api.  im not sure how to do this or modify this function

**Comment by WPprodigy** [comment]
Hello,

This documentation should answer your questions: http://woothemes.github.io/woocommerce-rest-api-docs/#create-an-order

As for Points and Rewards, creating an order in the API skips that process entirely. You still need to collect money from the custom of course, so they will need to login to the site and pay (which could be with rewards), or you will need to build a custom way of doing this in your app. But yea, either way, this is aside from the API.

**Comment by ZayleWy** [comment]
Hello,
ihave read the api docs on create-an-order, not very sure how to pass data from mobile app. i am trying to parse data in xamarin c# codes etc. is that array of data from the api docs a raw data? not very sure with that.

i have purchase the woocommerce points & reward extensions so means i have 1 year of support helps form you guys? does the support comes with coding helps like help to create api?

for the points and rewards - assuming that payment checkout is all done through the mobile app and only pass back the required data for creating an order into wordpress how can i modify the create_order($data) so that when order is create it deducts the woopoints? im very confuse with woocommerce and PHP already quite new to this.

i just hope that next woocommerce update helps all users to create the api for points and coupons too.

Thanks :)

Date: Tue, 22 Sep 2015 21:50:15 -0700

**Comment by WPprodigy** [comment]
Hello,

I'm not sure about c#, but this is something quite outside the range of what Github issues are for. 

And then no, Woo Support does not include code help and customization like this: www.woothemes.com/support-policy

It seems you are just starting to dive into development, so perhaps it would be worth finding a techer or mentor to help your through this. Codeable could help you out there: https://codeable.io/

**Comment by claudiosmweb** [comment]
Our documentation shows all you need: http://woothemes.github.io/woocommerce-rest-api-docs
