### ISSUE TITLE
missing product images on front end of site after updating woocommerce plugin

### ISSUE THREAD

**Issue by uchedotphp** [woothemes/woocommerce#9206]
hi, i recently updated woocommerce plugin on my wordpress site and now the product images are no more displaying. ive also gone to update the out-of-date template files but that didnt fix the issue. ive also deleted the woocommerce plugin, deleted all the files and re-installed it but still the issue persists. HELP PLEASE!!! this is a clients job and is pending
![25](https://cloud.githubusercontent.com/assets/11481757/10038333/4f671e32-6179-11e5-81e6-80e3090e89aa.png)
![24](https://cloud.githubusercontent.com/assets/11481757/10038334/4f780cb0-6179-11e5-8801-4df3cab5db0c.png)

**Comment by claudiosmweb** [comment]
We have not made absolutely no change that could cause this problem.
This can only be an issue with your theme or maybe even with another plugin you must have upgraded together.
