### ISSUE TITLE
IE/Edge checkout AJAX/jQuery issues

### ISSUE THREAD

**Issue by Spreeuw** [woothemes/woocommerce#9207]
Running WP4.3.1 + WC2.4.7 in on a site with force secure checkout enabled seems to cause AJAX issues in the checkout when accessing the site via Edge 12 (Win10) or IE11 (Windows Phone 8.1).
I have turned off all plugins and switched to twenty fourteen (didn't have twenty fifteen on this site yet, although I don't think that matters), but the problem remains.
I am not sure what happens and I can't see any errors in the console, and no php errors in the php error log on the server.

Here's how I can consistently reproduce the error:
I fill in all billing address fields, and as soon as I get to either the postcode or the city, the order summary and payment gateway is blocked (+spinning infinitely). Strangely enough, when I switch to a different program in Windows (alt+tab) and go back to IE, the summary+payment gateways are unblocked and I can check out without any problems. Switching to another country (from NL to BE) and back also fixed the issue. Turning off Force SSL in the WC settings also fixes the issue.

I haven't been able to duplicate this issue in FF or Chrome.
I thought this may have been related to #8992 but after updating to 2.4.7 (+clearing cache), the problem persisted.

I understand that the above report may not contain all the necessary information. If there is any way in which I can gather more infromation on where this goes wrong, let me know and I'll do my best to collect it. Unfortunately this error is on a live site and because the problem is with SSL and I don't have a certificate for the staging site, I can't provide full testing access to this site. (site was put in maintenance mode to test with all plugins and theme turned off)

**Comment by Spreeuw** [comment]
Some light actually. I guess I wasn't used to the IE console enough to know that it only logs errors from the moment you open it (whereas also Chrome shows errors from pages already loaded).

Here's the error I received:
```
SCRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3.
```

Which makes me suspect that this is related to the server (some fixes suggested [here](http://stackoverflow.com/questions/23145688/ie10-11-ajax-xhr-error-script7002-xmlhttprequest-network-error-0x2ef3)). Why switching language, changing applications etc. makes this work is a mystery to me.

**Comment by Spreeuw** [comment]
@jameskoster @mikejolley I have a simple fix for this issue from the WC side and I'd like to have your thoughts on this. Basically, all you need to do is make a get call before doing the ajax post.

in checkout.js:
````js
update_checkout: function() {
	// Small timeout to prevent multiple requests when several fields update at the same time
	wc_checkout_form.reset_update_checkout_timer();
	// make get call to make sure client has SSL certificate
	$.get(wc_checkout_params.wc_ajax_url).then( function () {
		wc_checkout_form.updateTimer = setTimeout( wc_checkout_form.update_checkout_action, '5' );
	})		
},
```

This solution (based on (this)[http://jonnyreeves.co.uk/2013/making-xhr-request-to-https-domains-with-winjs/]) of using a GET call is applied/suggested in several places. Would you consider adding this to core?

Some sources say you only need to make this call once, but it didn't work when I added it to init.

**Comment by jameskoster** [comment]
Looks fine to me. Would you like to send a PR?

**Comment by Spreeuw** [comment]
Definitely can make a PR. I think this error may affect more than just this specific AJAX `update_checkout` call. it's the only place I encountered it but I don't use add to cart ajax for example. Any thoughts on how this can be applied more broadly, other than adding before every ajax call?
