### ISSUE TITLE
WooCommerce API Activated 404

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#9208]
Hi,

A customer of mine is using WooCommerce 2.4. He has activated the REST API. When we go to the endpoint, he gets a 404 error:

https://www.adaptive.ag/wc-api/v2

Is there another endpoint that I can try?

**Comment by claudiosmweb** [comment]
You need to enable the WordPress permalinks.

http://docs.woothemes.com/document/woocommerce-rest-api/
