### ISSUE TITLE
Consuming rest API by angular js based theme.

### ISSUE THREAD

**Issue by lapak10** [woothemes/woocommerce#9211]
Sorry that i am putting up this question at wrong place...but seriously i just wanna know how to use wc-api/v3 .... in the theme installed on the same wordpress installation which is based on angularjs. I mean I dont how to use OAuth when using angular js as frontend.

My simple question... do we still need to use OAuth when simply using angularjs(or any other JS framework) based theme on the same wordpress installation.

**Comment by claudiosmweb** [comment]
If you want to use the API and authenticate to use... you must use Basic Auth (over HTTPS) or OAuth 1.0a.

Remember If you can't leave exposed your API keys.
