### ISSUE TITLE
REST API - Creating a product with attributes

### ISSUE THREAD

**Issue by darkkean** [woothemes/woocommerce#9212]
Hi,

We're having problems when creating a variable product via REST API and binding it with pre-created attributes in Woocommerce dashboard.

http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product doesn't tell much about how the payload should be when creating a variable product with attributes.

However when using the sample payload that we have below, and do a POST using the products API endpoint, the product gets created however the attributes aren't bonded to the correct "pre-created" attributes.

![sample payload](https://cloud.githubusercontent.com/assets/5990055/10067159/804f363e-62cc-11e5-9cf3-c33304837801.JPG)

![woo-product-attributes](https://cloud.githubusercontent.com/assets/5990055/10067148/6a3f1328-62cc-11e5-8cab-5a2223708fa5.png)

Anyone who have been successful in creating a variable product and bind it to "pre-created" attributes in Woocommerce?

Looking forward to your help.

**Comment by claudiosmweb** [comment]
Use the `slug` for "pre-created" attributes.

**Comment by darkkean** [comment]
Thanks @claudiosmweb for the quick response!

I amended my payload to this:

"attributes": [
		{
			"slug":"pa_genus",
			"visible": true,
			"options": [
			  "Polianthes"
			]
		}
  	]

However after the product gets created, and checked in Woocommerce dashboard, the product no longer have any attribute assigned.

Here's some of our product attributes:

 "product_attributes":[
      {
         "id":2,
         "name":"Quantity",
         "slug":"pa_quantity",
         "type":"select",
         "order_by":"menu_order",
         "has_archives":false
      },
      {
         "id":5,
         "name":"Genus",
         "slug":"pa_genus",
         "type":"text",
         "order_by":"menu_order",
         "has_archives":false
      },

**Comment by claudiosmweb** [comment]
Need to send both, `name` and `slug`.

**Comment by jklepatch** [comment]
I confirm including both `name` and `slug` work to attach a global attribute to a product.
For the slug, it needs to be without the `pa_` part. So if full slug is `pa_color`, then it needs to be only `color` in the request.

**Comment by paipatisb** [comment]
I am trying to add attributes to a product like this and it still doesn't work.I've tried both using and excluding  the 'id' or 'name' or 'slug' but nothing happens.  Even though the product itself is created.
The attributes array is being sent as a empty array, judging by the json output on the screen:  [attributes] => Array ( )

`'attributes' => [
                        [
                        'id' => 8,
                        'name' => 'Παράδοση',
                        'slug' => 'paradosi',
                        'option' => [$a_product->availability],
                        'visible' => true
                        ],
                        [
                        'id' => 4,
                        'name' => 'Brand',
                        'slug' => 'brand',
                        'option' => ['Inart'],
                        'visible' => true
                        ],
                        [
                        'id' => 3,
                        'name' => 'Χρώμα',
                        'slug' => 'xroma',
                        'option' => [$a_product->xrwma001],
                        'visible' => true
                        ]
]`

**Comment by paipatisb** [comment]
I am trying to add attributes to a product like this and it still doesn't work.I've tried both using and excluding  the 'id' or 'name' or 'slug' but nothing happens.  Even though the product itself is created.
The attributes array is being sent as a empty array, judging by the json output on the screen:  [attributes] => Array ( )

`'attributes' => [
                        [
                        'id' => 8,
                        'name' => 'Παράδοση',
                        'slug' => 'paradosi',
                        'option' => [$a_product->availability],
                        'visible' => true
                        ],
                        [
                        'id' => 4,
                        'name' => 'Brand',
                        'slug' => 'brand',
                        'option' => ['Inart'],
                        'visible' => true
                        ],
                        [
                        'id' => 3,
                        'name' => 'Χρώμα',
                        'slug' => 'xroma',
                        'option' => [$a_product->xrwma001],
                        'visible' => true
                        ]
]`

**Comment by Artistan** [comment]
sorry, but when I request a attribute and then have to remove the "pa_" for creating a new one???

that is wrong on so many level, but apparently it is still the case.

**Comment by Artistan** [comment]
also, requiring the name AND the slug???

**Comment by claudiosanches** [comment]
@Artistan this has been updated, check the docs: https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by Artistan** [comment]
using the docs, still having issues...
docs show using id OR name, not name and slug....
tried many ways and it still does not work

DOCS>>>
```
    'attributes' => [
        [
            'id' => 6,   /* shows that id should work!! */
            'position' => 0,
            'visible' => false,
            'variation' => true,
            'options' => [
                'Black',
                'Green'
            ]
        ],
        [
            'name' => 'Size',   /* shows that just name should work!! */
            'position' => 0,
            'visible' => true,
            'variation' => true,
            'options' => [
                'S',
                'M'
            ]
        ]
    ],
```

**this is not working...**
with id, name, and slug does not work
```  
"attributes" => array:8 [
    2 => array:5 [
      "id" => 2
      "name" => "Brand"
      "slug" => "brand"
      "visible" => true
      "options" => array:1 [
        270 => array:3 [
          "id" => 270
          "name" => "Viking"
          "slug" => "viking"
        ]
      ]
    ]
```

**and this is not working...**
ids do not owrk
```  
"attributes" => array:8 [
    2 => array:5 [
      "id" => 2
      "visible" => true
      "options" => array:1 [
        270 => array:3 [
          "id" => 270
        ]
      ]
    ]
```

**and this added attributes, but "Array" as the options...**
note that there is NO id.
```  
"attributes" => array:8 [
    2 => array:5 [
      "name" => "Brand"
      "slug" => "brand"
      "visible" => true
      "options" => array:1 [
        270 => array:3 [
          "name" => "Viking"
          "slug" => "viking"
        ]
      ]
    ]
```


**and this added attributes, but not from the global, it used "custom" attribute...**
```  
"attributes" => array:8 [
    2 => array:5 [
      "name" => "Brand"
      "slug" => "brand"
      "visible" => true
      "options" => array:1 [
        270 => array:3 [
          "name" => "Viking"
          "slug" => "viking"
        ]
      ]
    ]
```
![image](https://user-images.githubusercontent.com/801349/30977442-2652e108-a43d-11e7-99df-d774a6804624.png)


this is what I want it to be...
![image](https://user-images.githubusercontent.com/801349/30977524-5d3542d8-a43d-11e7-9ada-0ad0dd468264.png)

**Comment by Artistan** [comment]
Looks like attribute IDs should work
https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L766

**Comment by claudiosanches** [comment]
@Artistan "ID" should be used for global variations and "Name" for product level variations.

**Comment by claudiosanches** [comment]
You always can create first one product on WooCommerce and after fetch by the REST API.
So you'll know what to do to create by REST API reading the results.

**Comment by Artistan** [comment]
So slug is not required...

```

    2 => array:6 [
      "id" => 24
      "name" => "Rings"
      "position" => 0
      "visible" => true
      "variation" => false
      "options" => array:1 [
        0 => "Brass"
      ]
    ]
```

**Comment by ajaykumarCubix** [comment]
how to find product by attributes in WooCommerce Rest API

[ {
        "id": 72,
        "name": "WordPress Pennant",
        "slug": "wordpress-pennant",
        "permalink": "http://192.168.10.31/wordpress/product/wordpress-pennant/",
        "date_created": "2019-01-15T08:50:16",
        "date_created_gmt": "2019-01-15T08:50:16",
        "date_modified": "2019-01-15T08:58:54",
        "date_modified_gmt": "2019-01-15T08:58:54",
        "type": "external",
        "status": "publish",
        "featured": false,
        "catalog_visibility": "visible",
        "description": "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
        "short_description": "<p>This is an external product.</p>\n",
        "sku": "wp-pennant",
        "price": "11.05",
        "regular_price": "11.05",
        "sale_price": "",
        "date_on_sale_from": null,
        "date_on_sale_from_gmt": null,
        "date_on_sale_to": null,
        "date_on_sale_to_gmt": null,
        "price_html": "<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>11.05</span>",
        "on_sale": false,
        "purchasable": false,
        "total_sales": 0,
        "virtual": false,
        "downloadable": false,
        "downloads": [],
        "download_limit": 0,
        "download_expiry": 0,
        "external_url": "https://mercantile.wordpress.org/product/wordpress-pennant/",
        "button_text": "Buy on the WordPress swag store!",
        "tax_status": "taxable",
        "tax_class": "",
        "manage_stock": false,
        "stock_quantity": null,
        "stock_status": "instock",
        "backorders": "no",
        "backorders_allowed": false,
        "backordered": false,
        "sold_individually": false,
        "weight": "",
        "dimensions": {
            "length": "",
            "width": "",
            "height": ""
        },
        "shipping_required": true,
        "shipping_taxable": true,
        "shipping_class": "",
        "shipping_class_id": 0,
        "reviews_allowed": true,
        "average_rating": "0.00",
        "rating_count": 0,
        "related_ids": [],
        "upsell_ids": [],
        "cross_sell_ids": [],
        "parent_id": 0,
        "purchase_note": "",
        "categories": [
            {
                "id": 25,
                "name": "Decor",
                "slug": "decor"
            }
        ],
        "tags": [],
        "images": [
            {
                "id": 95,
                "date_created": "2019-01-15T08:51:10",
                "date_created_gmt": "2019-01-15T08:51:10",
                "date_modified": "2019-01-15T08:51:10",
                "date_modified_gmt": "2019-01-15T08:51:10",
                "src": "http://192.168.10.31/wordpress/wp-content/uploads/2019/01/pennant-1.jpg",
                "name": "pennant-1.jpg",
                "alt": ""
            }
        ],
        "attributes": [
            {
                "id": 2,
                "name": "Size",
                "position": 0,
                "visible": true,
                "variation": false,
                "options": [
                    "Large",
                    "Medium",
                    "Small"
                ]
            }
        ],
        "default_attributes": [],
        "variations": [],
        "grouped_products": [],
        "menu_order": 0,
        "meta_data": [
            {
                "id": 1828,
                "key": "_wpcom_is_markdown",
                "value": "1"
            }
        ],
        "_links": {
            "self": [
                {
                    "href": "http://192.168.10.31/wordpress/wp-json/wc/v3/products/72"
                }
            ],
            "collection": [
                {
                    "href": "http://192.168.10.31/wordpress/wp-json/wc/v3/products"
                }
            ]
        }
    }]

**Comment by philipwoodrow** [comment]
Thank you so much for this - saved me hours!
