### ISSUE TITLE
REST API - Creating a product with tags

### ISSUE THREAD

**Issue by darkkean** [woothemes/woocommerce#9213]
I am trying to create a new variable product via REST API and have this test payload for tags:

```
"tags": [  
         "hello",
         "mark",
         "test"
]
```

Creation was a success however upon checking the created new product in Woocommerce admin, Product tags are still empty.

Has anyone tried doing this via REST API?

**Comment by claudiosmweb** [comment]
To create need to send the tag IDs.
On WooCommerce 2.5 will be easy to create tags or get tag IDs using the new `product/tags` endpoint.
