### ISSUE TITLE
applying vaild coupon code gives ERR_EMPTY_RESPONSE error

### ISSUE THREAD

**Issue by bassjobsen** [woothemes/woocommerce#9214]
Version: 2.4.7 ( WordPress 4.3.1 )

When i apply an invalid code, i got an error. Valid codes do not work.

**Comment by bassjobsen** [comment]
well i found that the above will caused by in `class-wc-coupon.php`:

			if ( ! apply_filters( 'woocommerce_coupon_is_valid', true, $this ) ) {
	                             throw new Exception( self::E_WC_COUPON_INVALID_FILTERED );
			}

**Comment by mikejolley** [comment]
In that case you have an extension filtering on woocommerce_coupon_is_valid and returning false. Not a core issue.
