### ISSUE TITLE
Woocommerce Reports

### ISSUE THREAD

**Issue by citatplakat** [woothemes/woocommerce#9215]
Hi

After updating Woocommerce, I can no longer see my sales in Woocommerce reports. I can only see the my sale back to the 21st of september, which must be the day I have updated. I have no problem in seeing how many orders have been processed, or the value of all the coupons that have been used. But the Gross Sales and the Net Sales, are totally gone! What do I do to get it back?

Notice that I have changed the periods on the pictures below:

<img width="1440" alt="skaermbillede 2015-09-24 kl 13 45 51" src="https://cloud.githubusercontent.com/assets/14820635/10072514/a947eef0-62c2-11e5-8e5b-1ed222ea175c.png">
<img width="1440" alt="skaermbillede 2015-09-24 kl 13 46 10" src="https://cloud.githubusercontent.com/assets/14820635/10072515/a9481664-62c2-11e5-863c-5f2794679fcc.png">
<img width="1440" alt="skaermbillede 2015-09-24 kl 13 46 21" src="https://cloud.githubusercontent.com/assets/14820635/10072513/a947d3de-62c2-11e5-8352-cf58358f1d2c.png">

**Comment by serveds** [comment]
I have the exact same issue.

The last 7 days I have all the sales totals.  Other then that I see nothing when I switch to a full month or any other dates.

Justin

**Comment by mikejolley** [comment]
Have you imported products, or played with currency options? Or used a plugin which messes with currency such as WPML?

**Comment by serveds** [comment]
I think it may have been a caching issue.  I did not change anything and the reports started working after I cleared the cache of my site. 

Justin

**Comment by claudiosmweb** [comment]
@serveds thanks for let we know :)
