### ISSUE TITLE
Flat rate cost issue

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#9217]
If I leave empty the Cost option and set a shipping class "Free" to 0, the checkout/cart shows "No shipping method available". If I set the Cost option to 0 then the Free shipping method (flat rate) shows correctly.

I think it should be the same if I leave it empty or to 0.

**Comment by mikejolley** [comment]
This is expected. If the cost is '' for the main cost, and any matching shipping classes, $has_costs is false. At least one cost must be 0 or greater to offer the rate.

**Comment by SiR-DanieL** [comment]
In my test the Free shipping class was 0 as I can read from the description on my first reply.

So the main cost is empty, but the matching shipping class was not empty, it was 0.
