### ISSUE TITLE
API featured_src return type

### ISSUE THREAD

**Issue by emrahu** [woothemes/woocommerce#9220]
When requesting /products, the v2 api returns type string if there is a featured_src, a boolean false when there is no value. Can we make it a consistent return type? Instead of returning a boolean false when there is no value, can we return an empty string?

**Comment by emrahu** [comment]
Thanks! Wouldn't an empty string be more appropriate instead of casting the boolean value as string?

**Comment by claudiosmweb** [comment]
Oo

```php
var_dump( (string) false );
```
