### ISSUE TITLE
Changing Delivery Time not Working in Products > Quick Edit

### ISSUE THREAD

**Issue by davidk82** [woothemes/woocommerce#9221]
Hello,

When Changing Delivery time by quick edit ... value changes to woo default.
When changing delivery time in product itself ... works fine.

### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 2.4.6
Log Directory Writable: ✔  / WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.26-nmm1
PHP Post Max Size: 200 MB
PHP Time Limit: 0
PHP Max Input Vars: 5000
SUHOSIN Installed: –
MySQL Version: 5.6.24
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.6
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (34) ###

Antispam Bee: von pluginkollektiv – 2.6.8
BackUpWordPress: von Human Made Limited – 3.2.7
iThemes Security: von iThemes.com – 4.9.0
Contact Form 7 Honeypot: von Dao By Design – 1.7
Contact Form DB: von Michael Simpson – 2.9.8
Contact Form 7: von Takayuki Miyoshi – 4.2.2
CW Google Analytics Datenschutz: von Christian Wenzl – 1.3
Artikel duplizieren: von Enrico Battocchi – 2.6
Envato WordPress Toolkit: von Envato – 1.7.3
ExtraWatch PRO (Live Stats, Heatmap, Click tracking, Download Monitor and more): von CodeGravity.com – 2.3.2587 PRO
Google Analytics Dashboard for WP: von Alin Marcu – 4.8.2
Google Analytics Opt-Out Pro: von WP-Buddy – 1.2.0
heatmap for WordPress: von HeatMap
Inc – 0.3.1

WPBakery Visual Composer (Artbees Modified Version): von Michael M - WPBakery.com – 4.7
Media Library Assistant: von David Lingren
Fair Trade Judaica – 2.14

MyMail - Email Newsletter Plugin for WordPress: von revaxarts.com – 2.0.28
Simple History: von Pär Thernström – 2.1.7
Simple Image Sizes: von Rahe – 3.0.9
Smart Manager for e-Commerce: von Store Apps – 3.9.8
Woocomerce Brands: von Proword – 2.8
WooCommerce Print Address Labels: von Ewout Fernhout – 1.3.1
WooCommerce Adminbar-Zusatz: von David Decker - DECKERWEB.de – 2.7.0
WooCommerce German Market: von Inpsyde GmbH – 2.6.3
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 1.5.22
WooCommerce PDF Invoices & Packing Slips Professional: von Ewout Fernhout – 1.0.0
WooCommerce PDF Invoices & Packing Slips Premium Templates: von Ewout Fernhout – 1.2.0
Woocommerce Poor Guys Swiss Knife: von Uli Hake – 2.2.4
WooCommerce Sequential Order Numbers: von SkyVerge – 1.4.0
WooCommerce: von WooThemes – 2.4.6
Shipping Details for WooCommerce: von PatSaTECH – 1.7.0
WooThemes Helper: von WooThemes – 1.5.3
Yoast SEO Premium: von Team Yoast – 2.3.4
WP-Memory-Usage: von Alex Rabe – 1.2.2
WP Rocket: von WP Rocket – 2.6.6

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: –
API Version: 3.0.0

### WC Pages ###

Shop-Basis: #6 - /
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /kasse/
Mein Konto: #9 - /mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Jupiter Child Theme
Version: 4.0.9
Author URL: 
Child Theme: ✔
Parent Theme Name: Jupiter
Parent Theme Version: 4.4
Parent Theme Author URL: http://themeforest.net/user/artbees
WooCommerce Support: ✔

### Templates ###

Overrides: jupiter/woocommerce/archive-product.php
jupiter/woocommerce/cart/cart-empty.php
jupiter/woocommerce/cart/cart.php
jupiter/woocommerce/cart/mini-cart.php
jupiter/woocommerce/cart/shipping-calculator.php
jupiter/woocommerce/checkout/cart-errors.php
jupiter/woocommerce/checkout/form-coupon.php
jupiter/woocommerce/checkout/review-order.php
jupiter/woocommerce/content-product.php
jupiter/woocommerce/content-product_cat.php
jupiter/woocommerce/content-single-product.php
jupiter/woocommerce/global/form-login.php
jupiter/woocommerce/loop/no-products-found.php
jupiter/woocommerce/loop/orderby.php
jupiter/woocommerce/loop/pagination.php
jupiter/woocommerce/loop/price.php
jupiter/woocommerce/loop/rating.php
jupiter/woocommerce/loop/result-count.php
jupiter/woocommerce/loop/sale-flash.php
jupiter/woocommerce/myaccount/form-edit-account.php
jupiter/woocommerce/myaccount/form-edit-address.php
jupiter/woocommerce/myaccount/form-login.php
jupiter/woocommerce/myaccount/form-lost-password.php
jupiter/woocommerce/myaccount/my-address.php
jupiter/woocommerce/notices/error.php
jupiter/woocommerce/notices/notice.php
jupiter/woocommerce/notices/success.php
jupiter/woocommerce/order/form-tracking.php
jupiter/woocommerce/single-product/add-to-cart/external.php
jupiter/woocommerce/single-product/add-to-cart/grouped.php
jupiter/woocommerce/single-product/add-to-cart/simple.php
jupiter/woocommerce/single-product/add-to-cart/variable.php
jupiter/woocommerce/single-product/meta.php
jupiter/woocommerce/single-product/price.php
jupiter/woocommerce/single-product/product-image.php
jupiter/woocommerce/single-product/product-thumbnails.php
jupiter/woocommerce/single-product/rating.php
jupiter/woocommerce/single-product/related.php
jupiter/woocommerce/single-product/review.php
jupiter/woocommerce/single-product/sale-flash.php
jupiter/woocommerce/single-product/share.php
jupiter/woocommerce/single-product/short-description.php
jupiter/woocommerce/single-product/tabs/additional-information.php
jupiter/woocommerce/single-product/tabs/description.php
jupiter/woocommerce/single-product/tabs/tabs.php
jupiter/woocommerce/single-product/title.php
jupiter/woocommerce/single-product/up-sells.php

**Comment by mikejolley** [comment]
Core does not have nor process a 'delivery time' field - this is coming from an extension.
