### ISSUE TITLE
get_price_html() didn't return the price with taxes on variable product 

### ISSUE THREAD

**Issue by Yokann** [woothemes/woocommerce#9224]
Hello, 

I am trying woocommerce 4.2.7 before update my website. 
The price return by the function WC_Product_Variable->get_html_prices() is only with excluded taxes.

I enter my prices in excluded tax.

Everything is ok with other product type. I don't use any filters on 'woocommerce_get_price_html' or 'woocommerce_variation_prices'. 

Did i missed something ?

**Comment by daigo75** [comment]
It's caused by a bug, I also spotted it. I'm preparing a pull request precisely for this.

**Comment by Yokann** [comment]
Great. Thank you for your return !

**Comment by daigo75** [comment]
Pull request created: https://github.com/woothemes/woocommerce/pull/9226.
