### ISSUE TITLE
Reporting - hovering a chart legend section hightlights the wrong data series in the graph

### ISSUE THREAD

**Issue by aprea** [woothemes/woocommerce#9228]
1. Hovering the "gross sales" legend highlights "net sales" in the graph.
1. Hovering the "net sales" legend highlights "refunded order" in the graph.
1. Hovering the "refunded order" legend highlights "charged for shipping" in the graph.
1. Hovering the "charged for shipping" legend highlights "gross sales" in the graph.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/pull/9178/files
