### ISSUE TITLE
Unwillingingly updated to 2.4.x - add to cart and checkout broken

### ISSUE THREAD

**Issue by optionb** [woothemes/woocommerce#9232]
Hello,
An over-zealous person decided it was a good idea to update the woocommerce plugin to 2.4.7, before doing any backups (without my approval) and has now broken the functionality of the shop...and I'm doubtful as to the WP backup process integrity?!

http://www.neko.org.au

From the shop, 'Add to Cart' reveals the shopping cart logo (theme) top right; hovering over that produces an empty 'quote' style box. The button doesn't change either. 

In the events area, Oct.31 there is an event which has tickets available. From here I can get to the checkout page, but this sits in an ajax payment infinite loop of nothing...

Any suggestions please as to how to resolve this? Possible to roll back the woocommerce version?

cheers
Luke

**Comment by claudiosmweb** [comment]
Problems like you are describing are related to your theme's template files that may be out of date or other plugins not updated.
So try update every thing, but this is not an issue with WooCommerce core.

**Comment by optionb** [comment]
Hi Claudio,

I appreciate you getting back to me! I tried updating the out-of-date
template files;

maneki-neko/woocommerce/content-product.php version *1.6.4* is out of date.
The core version is 2.4.0,
maneki-neko/woocommerce/single-product/tabs/tabs.php version *1.6.4* is out
of date. The core version is 2.4.0,

...this didn't fix the problem, and additionally broke the layout?! I'd be
fine if it was only the layout that broke (some simple css would clean it
up) but I'm having real issues with WooCommerce here.

Is it possible to roll back WC? Ideally this would be best for me, as I
can't see a way of fixing this problem?

Thanks again!

cheers
Luke

**Comment by claudiosmweb** [comment]
This repository is not suitable for support. Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:

- The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
- [Our forum on WordPress.org](https://wordpress.org/support/plugin/woocommerce).

Support requests in issues on this repository will be closed on sight.
