### ISSUE TITLE
Variable products not abiding by tax settings

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#9233]
To recreate:
- Taxes enabled, and prices entered "Excluding Tax"
- Display prices in shop/cart "Including Tax"

![](http://cld.wthms.co/1eskk/MgqpK6ml+)

When viewing a simple product, the price displays including tax, but when viewing a variable product, the price range shows the prices excluding tax. When the variation is selected, the product's price shows including tax. See screencast: http://recordit.co/K4irul7wJ5

**Comment by franticpsyx** [comment]
@mikejolley @claudiosmweb 

Probably due to this:

https://github.com/woothemes/woocommerce/commit/3a1bcd8e7d5411f9f796b887d433f00670c67a24#commitcomment-13410574

**Comment by stevetested** [comment]
As seen on:
https://woothemes.zendesk.com/agent/tickets/339251

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/pull/9226
