### ISSUE TITLE
Custom Product Type

### ISSUE THREAD

**Issue by circleb** [woothemes/woocommerce#9239]
I'm using the `product_type_selector ` (as well as my own class) to create two new product types in my plugin. Everything looks good in the admin, but when I use `$product->product_type` in any of the template files it returns 'simple', for both of the custom product types that I've setup. Any idea how I can fix this?

**Comment by mikejolley** [comment]
In your product type's class file, set the type. Just as the core type classes do: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-external.php#L27

**Comment by circleb** [comment]
That's exactly what I did, here's what I put in the `product_type_selector` `add_filter` function, and `$this->product_type = 'slonlinecourse'` in my class...

**Comment by circleb** [comment]
Here's my `add_filter` function:
```
function sl_add_custom_product_type( $types ){
    $types[ 'slonlinecourse' ] = __( 'Online Course' );
    return $types;
}
```
And my class:
```
    class WC_Product_Sloc extends WC_Product {
        public function __construct( $product ) {
            $this->product_type = 'slonlinecourse';
            parent::__construct( $product );
        }
    }
```

**Comment by iskandar** [comment]
I encounted this issue as well and solved it by making sure my PHP class names map to the custom `product_type` value.

In this case, you have:

```PHP
class WC_Product_Sloc extends WC_Product {
        public function __construct( $product ) {
            $this->product_type = 'slonlinecourse';
            parent::__construct( $product );
        }
}
```

The `product_type` value must map to the PHP class name. [Here is the relevant code that converts the `product_type` to a class name value](https://github.com/woothemes/woocommerce/blob/d42d7c13b6d472454084e19d7e3d7085453b6e8f/includes/class-wc-product-factory.php#L58):

```PHP
private function get_classname_from_product_type( $product_type ) {
	return $product_type ? 'WC_Product_' . implode( '_', array_map( 'ucfirst', explode( '-', $product_type ) ) ) : false;
}
``` 

So this might work for you:

```PHP
class WC_Product_Slonlinecourse extends WC_Product {
      public function __construct( $product ) {
            $this->product_type = 'slonlinecourse';
            parent::__construct( $product );
      }
}
```
