### ISSUE TITLE
Tooltips on Order Screen stopped working

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#9240]
As near as I can tell this was introduced here: https://github.com/woothemes/woocommerce/commit/fc78f85bc61ee7442fd5294c97bf596ca1c1a30c

![see screen shot](http://cld.wthms.co/1bxIt/3Fgsk73L+)

**Comment by WPprodigy** [comment]
I think tooltips were taken out in favor of showing all of the information at the start / after clicking the items purchased.

For instance, if there are products in the order, you can click on the "# items" and they will appear: http://cld.wthms.co/1drqI/3igwM639

And then shipping address info is shown by default now as well (check the screen options).

**Comment by mikejolley** [comment]
These were removed here to support mobile https://github.com/woothemes/woocommerce/commit/4aff861626c978842b0f7c28c6ad03fc015d25c8

I'll add a column (hidden by default).
