### ISSUE TITLE
PHP examples missing

### ISSUE THREAD

**Issue by greencopper** [woothemes/woocommerce#9241]
Why are there absolutely no PHP examples in the docs? 

http://woothemes.github.io/woocommerce-rest-api-docs

Only cURL, Node, Python and Ruby, but no PHP examples!

**Comment by greencopper** [comment]
This is really really extremely annoying!

**Comment by mikejolley** [comment]
You can do curl requests with PHP

**Comment by claudiosmweb** [comment]
Don't have examples, because the PHP library don't support WooCommerce Rest API v3 yet.
