### ISSUE TITLE
WOFF linegap

### ISSUE THREAD

**Issue by szepeviktor** [woothemes/woocommerce#9242]
> downloadable font: OS/2: bad linegap: -64 (font-family: "WooCommerce" style:normal weight:normal stretch:normal src index:1) source: `hxxp://wp.*.hu/static/plugins/woocommerce/assets/fonts/WooCommerce.woff`
*Firefox 42*

Please consider correcting the linegap.
Thank you!

**Comment by shivapoudel** [comment]
@jameskoster Icomoon has done several changes over woff and svg extension which I am known. Please update the fonts file :)

**Comment by szepeviktor** [comment]
Try the converting the original font file (ttf, otf whatever) with
http://www.fontsquirrel.com/tools/webfont-generator

**Comment by szepeviktor** [comment]
Thank you.
