### ISSUE TITLE
Order Listing Issue

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#9243]
I have created a plugin which has a separate page for order listing.. in that it looks like the same as WooCommerce's Order Listing page but. i am unable to get the comments of the order so i added my custom post type to ```wc_order_types``` after that there is no order listed..  its showing a empty table. ?

```php
add_filter( 'wc_order_types',array($this,'add_wc_order_types'),10,3);
public function add_wc_order_types($order_types,$type){
        $order_types[] = WC_QD_PT;
        return $order_types;
    }
```

**Comment by mikejolley** [comment]
The above doesn't affect comments. Your problem must be elsewhere in your code...
