### ISSUE TITLE
VAT calculation for variable products

### ISSUE THREAD

**Issue by MasterPCUK** [woothemes/woocommerce#9245]
Hi there,

I have an issue with VAT calculation and variations.

All prices on my store are entered exclusive of VAT and WooCommerce is set to calculate VAT for me. VAT calculation is fine when product is “Simple Product” 21% is added as per settings for VAT.

When product type is “Variable Product” then if I enter price for variation to be 347,00(without VAT) in backed, on front end it should show price 420,00(21%), but it displays 347.00, and only when added to cart it shows price with VAT..
It's very confusing for customers.

This issue wasn't there few months ago..

Issue persists with latest WP & WooCommerce and Storefront theme.

Thanks

**Comment by Damione1** [comment]
I am relieved to not be only one to have this problem. After several backups restored, I think I will temporarily remove the VAT calculation while waiting to solve the problem

**Comment by ChromeOrange** [comment]
@MasterPCUK Can you provide some screenshots please, we'll need screen shots of your tax options, your tax rates, the general options, the product variations and the cart with the shipping calculator open.

Also, were your products entered manually or were they imported? If imported, which importer did you use? If you imported does everything work if you create a variable product manually?

I've tried to replicate this and can't, my settings : 

## Screen shot of everything working : 

![](https://dl.dropboxusercontent.com/s/ucbdaqfg9tg2zc4/2015-10-01%20at%2006.45.png?dl=0)

## Tax Options : 

![](https://dl.dropboxusercontent.com/s/9yfs9nyh8kgctk5/2015-10-01%20at%2006.46.png?dl=0)

## Tax Rates : 

![](https://dl.dropboxusercontent.com/s/ike2acu69agugah/2015-10-01%20at%2006.46%20%281%29.png?dl=0)

## General Options : 

![](https://dl.dropboxusercontent.com/s/io1hdzxi7pkyx0e/2015-10-01%20at%2006.47.png?dl=0)

## Product Variations : 

![](https://dl.dropboxusercontent.com/s/oj5lfneoh9fk2ec/2015-10-01%20at%2006.49.png?dl=0)

**Comment by MasterPCUK** [comment]
Hi @ChromeOrange ,

Products are added manually.

I have created new variation test product with price of 200 Eur, and I still have the same problem as you will be able to see in screen shots.

## General Settings
![screen shot 2015-10-01 at 15 55 18](https://cloud.githubusercontent.com/assets/8301081/10221215/cc854d16-6855-11e5-91ec-f152ae4aec43.png)
## Tax Options
![screen shot 2015-10-01 at 15 54 22](https://cloud.githubusercontent.com/assets/8301081/10221217/cc88c96e-6855-11e5-9670-1b077a54518c.png)
## Tax rates
![screen shot 2015-10-01 at 15 54 55](https://cloud.githubusercontent.com/assets/8301081/10221216/cc887f4a-6855-11e5-9bad-8e45b19e9105.png)

## Variable product & newly created test product.
![screen shot 2015-10-01 at 15 56 05](https://cloud.githubusercontent.com/assets/8301081/10221285/2ba03cac-6856-11e5-9558-2912e73aaf28.png)
## Single product page, here it's displayed without tax, should be with.
![screen shot 2015-10-01 at 15 56 50]
(https://cloud.githubusercontent.com/assets/8301081/10221286/2ba393a2-6856-11e5-87e1-f438188a595f.png)
## Cart
![screen shot 2015-10-01 at 15 56 26](https://cloud.githubusercontent.com/assets/8301081/10221287/2ba6a114-6856-11e5-8305-b2212afad09f.png)

## Newly created product
![screen shot 2015-10-01 at 16 02 35](https://cloud.githubusercontent.com/assets/8301081/10221297/3d0aeb5e-6856-11e5-94ad-91908150ba32.png)
## Single product page, here it's displayed without tax, should be with.
![screen shot 2015-10-01 at 15 59 42](https://cloud.githubusercontent.com/assets/8301081/10221298/3d0d3c06-6856-11e5-9db8-42f382d67a84.png)
## Cart
![screen shot 2015-10-01 at 16 00 02](https://cloud.githubusercontent.com/assets/8301081/10221299/3d0fdec0-6856-11e5-8cc6-0d06e383902c.png)


Not sure what is causing this, as it happens to newly manually entered products..

**Comment by ChromeOrange** [comment]
@mikejolley 

I've modified my settings to match @MasterPCUK and I'm seeing the same issue

![](https://dl.dropboxusercontent.com/s/63h1331z6aovyzs/2015-10-01%20at%2016.54.png?dl=0)

I've applied the fix from here https://github.com/woothemes/woocommerce/commit/44f4a3b9be000a4d84fc682e1a34505607c6a3b8 which relates to https://github.com/woothemes/woocommerce/issues/9224 but it made no difference

**Comment by ChromeOrange** [comment]
@MasterPCUK can you apply the fix from https://github.com/woothemes/woocommerce/commit/44f4a3b9be000a4d84fc682e1a34505607c6a3b8 then clear the transients etc in the System Status -> Tools and let me know if you are still seeing the issue

![](https://dl.dropboxusercontent.com/s/3jv8cfth99j8fu0/2015-10-01%20at%2017.51.png?dl=0)

**Comment by MasterPCUK** [comment]
@ChromeOrange thanks for info, that was it, I applied fix from 44f4a3b and it works as expected now.

**Comment by Damione1** [comment]
Thanks @ChromeOrange ! The fix 44f4a3b works perfectly!

**Comment by LucSpan** [comment]
I have exactly the same problem as @MasterPCUK. Not sure how to fix this.  

[44f4a3b] (https://github.com/woocommerce/woocommerce/commit/44f4a3b9be000a4d84fc682e1a34505607c6a3b8) provides a solution fro 2015 for includes/class-wc-product-variable.php which since then has changed, it seems. 

Running WooCommerce 4.9.5.
