### ISSUE TITLE
Create nested categories via API

### ISSUE THREAD

**Issue by lysenko** [woothemes/woocommerce#9246]
Do you have plans to add Create Categories API endpoint?
I am working on integration with Woocommerce and I need an ability to push nested categories tree.
If there a change it would be merged if I create one, or is it better to create a plugin?

**Comment by claudiosmweb** [comment]
Will be possible on WooCommerce 2.5.
#9100

**Comment by lysenko** [comment]
Cool!

**Comment by Casy** [comment]
please, make it
