### ISSUE TITLE
Shipping priority funky

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#9247]
If a "rates" shipping extension is active then the cheapest "non-free" rate is selected instead of the first rate

![](https://dl.dropboxusercontent.com/s/78kw9tkm43vxj0i/2015-09-30%20at%2014.32%202x.png?dl=0)

Confirmed on my site

ref https://woothemes.zendesk.com/agent/tickets/339362

**Comment by WPprodigy** [comment]
I have also been able to replicate this.

**Comment by WPprodigy** [comment]
Even stranger - set them all to Priority 1, and Free Shipping will correctly be chosen. Set them all to Priority 2, and the cheapest USPS/UPS rate will be chosen.

**Comment by mikejolley** [comment]
As discussed with @ChromeOrange, once you've picked a method, priority is ignored. Clearing cache will select flat rate in this test (confirmed).

**Comment by ChromeOrange** [comment]
Actually this is not resolved.

This is the cart when I first visit 

![](https://dl.dropboxusercontent.com/s/shj992ckv9216or/2015-10-02%20at%2007.40.png?dl=0)

everything is correct 

Add a shipping address and it defaults to the cheapest shipping option that isn't Free Shipping

![](https://dl.dropboxusercontent.com/s/iljpzvuzenge2ph/2015-10-02%20at%2007.44.png?dl=0)

I did not choose any shipping method, Flat Rate was initially chosen for me, as I would expect, after adding the address the USPS rate was chosen for me - not as expected

**Comment by ChromeOrange** [comment]
Excuse the currency change - that's incidental
