### ISSUE TITLE
Since Update to 2.4.7 checkout is broken now

### ISSUE THREAD

**Issue by mrdavidsparks** [woothemes/woocommerce#9248]
Hello All. I have had a problem with my WooCommerce checkout since it was updated to 2.4.7. I get the following message when trying to checkout:

Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements.

I have made no changes to the settings in Woocommerce. If anyone can help, the site is at: https://www.davidpakman.com

Thanks.

**Comment by roykho** [comment]
Hello,

Please read the support criteria on this page https://github.com/woothemes/woocommerce

**Comment by mikejolley** [comment]
^ you should also double check your gateways show on checkout and are working - some themes will have outdated templates which break this process.

**Comment by mrdavidsparks** [comment]
Thanks,

I have double checked and Stripe is activated. But I am getting the
following:


   - Unable to add a new card. We have not charged your card. Please try
   again.

Thanks,

David

**Comment by mikejolley** [comment]
Try a different gateway - we don't debug stripe issues here.
