### ISSUE TITLE
API does not set order_number

### ISSUE THREAD

**Issue by danielhoey** [woothemes/woocommerce#9250]
The API docs list order_number as a property that can be set on an order. However it has no effect.

This code sets _order_number meta data to the value supplied to the API endpoint:

    includes/api/class-wc-api-orders.php

    // set order number
    if ( isset( $data['order_number'] ) ) {
    
        update_post_meta( $order->id, '_order_number', $data['order_number'] );
    }

But this value doesn't seem to be used anywhere else in the code base.

What is the intent with this? Should order_number be settable via the API?

**Comment by claudiosmweb** [comment]
Yep, you are right, we don't need this.
