### ISSUE TITLE
Email template consistency

### ISSUE THREAD

**Issue by Lewiscowles1986** [woothemes/woocommerce#9253]
Hi, 

WooCommerce is pretty awesome, so I'd like to start by saying thanks for all your hard-work!

I have just finished customizing a customers WooCommerce e-mails, they work great and I was able to achieve all that I wanted; but the process seemed to me to be a little clunky and disconnected from editing in one place, using consistent methodology...

Everything else in the emails is great; as it works with templates, which allows me to modify whatever I need presentationally; but some of the content is not in e-mail templates, but rather Core WooCommerce code, which felt like I had to switch gears to locate, there were not notes on filters used in the template so I had to read the code, locate the filter in the right file, then do this...

added following to *child-theme* ***functions.php***
```PHP
add_filter( 'woocommerce_email_customer_details_fields', 'theme_woo_edit_email_fields' );
function theme_woo_edit_email_fields( &$fields, &$sent_to_admin, &$order ) {
	$fields = array();
}
```

added this to ***/woocommerce/email/email-address.php***
```PHP
<table id="customer-details" cellspacing="0" cellpadding="0" style="width: 100%; vertical-align: top;" border="0">
	<tr>
		<td style="padding: 0;">
			<h2><?php echo ( isset($sent_to_admin) ? $sent_to_admin : false ) ? __( 'Customer details', 'woocommerce' ) : __( 'Your details', 'woocommerce' ); ?></h2>
		</td>
	</tr>
	<tr>
		<td class="td" style="text-align:left; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;" valign="top" width="100%">
			<p>
				<strong>Name:</strong>
				<span class="text" style="color: #505050; font-family: &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif;">
				<?php echo $order->billing_first_name . ' ' . $order->billing_last_name; ?></span><br>

				<strong>Email:</strong>
				<span class="text" style="color: #505050; font-family: &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif;">
				<?php echo $order->billing_email; ?></span><br>
				<strong>Tel:</strong>
				<span class="text" style="color: #505050; font-family: &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif;">
				<?php echo $order->billing_phone; ?></span>
			</p>
		</td>
	</tr>
</table>
```

It really was a pain for me that this was not in a separate file; I suspect the same might be true for other users, and specifically for customizing customer details, so anything you can do to ensure this follows the same process as addresses would be really appreciated, and I feel would represent an easier e-mail theming experience :smile:

**Comment by jameskoster** [comment]
Yup, this can probably be improved :-) Not a big priority atm though, please feel free to send a PR.

**Comment by Lewiscowles1986** [comment]
:+1: 

Cool, if it is something you are open to receiving a PR on, I'll do so soon. One question I do have is how would I unit test, as I can't find any specific tests for email templating functionality, are there any links to docs, or is this pure functional testing? or any links to where I might ask?

TIA :smile:

**Comment by jameskoster** [comment]
There aren't any unit tests for emails yet afaik.

**Comment by Lewiscowles1986** [comment]
This one takes care of customer details, if accepted I'll make another later tonight or tomorrow AM for order meta.

https://github.com/woothemes/woocommerce/pull/9326
