### ISSUE TITLE
User meta fields

### ISSUE THREAD

**Issue by Lewiscowles1986** [woothemes/woocommerce#9254]
This one is more of a gripe than a severe issue, but I was looking into the user-meta fields, and I really feel like if the woo-commerce specific additions could be wrapped in a DOM structure, rather than echoed out with `h3` followed by `table.form-table`. 

The end result would be super for allowing others to customize the look and feel of the user-meta fields, and would allow things like (what I would like to do), putting shipping and billing next to each other on larger screens to save scrolling. Mostly, by containing them in a div each with outer div, so any devs can traverse the DOM in a more specific way :wink:

**Comment by jameskoster** [comment]
If we feel that having the addresses side by side on large screens is a valid enhancement (probably is) then we should just roll that into core itself. Feel free to send a PR if you'd like to see this, and we can assess from there.

**Comment by mikejolley** [comment]
Not a fan of #9377 to be honest. We're following the WP markup currently. None of the profile sections there get wrapped - its just a list of headers and tables.

If anything we could wrap the section, but not each input. And the class name should be clearer e.g. woocommerce-user-section-billing woocommerce-user-section-shipping

**Comment by claudiosmweb** [comment]
+1 for WP default markup. It makes no sense to change the markup on this page.
To be honest, it would be better to create a view to show only what you want. So you can have more control if you want to change the default markup.

**Comment by Lewiscowles1986** [comment]
Okay, can you explain why it makes more sense to build out a whole new screen; and change the user-interaction of those that use their profile to multiple end-points, develop new documentation, dev & test code with logic, potentially creating new challenges vs three div tags which do not affect the 99%, who won't use anyway?

**Comment by Lewiscowles1986** [comment]
@mikejolley it's three div's, it doesn't touch individual input's, just sets of fields; all entirely necessary to give a dev control over each section individually without effects passing on to non WC elements. 

It's not deviating from the WP standard in any way, shape or form; it's just being intelligent about giving control, as the vertical on the form is already pretty long (excessively so), and may at some point be better to use up horizontal space.

**Comment by claudiosmweb** [comment]
@Lewiscowles1986 more sense than change this HTML.

**Comment by claudiosmweb** [comment]
To be honest, closing it, since we have plans to create a menu just do manage customers, in the future...

**Comment by Lewiscowles1986** [comment]
> @Lewiscowles1986 more sense than change this HTML.
No HTML has been changed, just three tags added, which by themselves do nothing, but add potential for others to change... have a nice weekend, look forward to seeing the "customers" menu

**Comment by jameskoster** [comment]
Sorry to waste your time with this one @Lewiscowles1986 but @mikejolley and @claudiosmweb are right, we shouldn't really be adjusting markup trivially like this.

**Comment by Lewiscowles1986** [comment]
it's not a huge problem TBH, the assumed tone from @claudiosmweb, which comes across as aggression and arrogance is probably worse than the tiny PR not getting through...

What I can't wrap my head around is why go to the trouble of creating a separate listing, and presentation screen (far more trivial from a WP perspective), than have markup which is innate in nature, represents zero risk, and opens up new possibilities? I tried to raise it with @mikejolley & @claudiosmweb, and the response seemed unhelpful to anyone reading...

> @Lewiscowles1986 more sense than change this HTML.

I'd love to help out with creating a better admin experience, so if it really does make sense to relocate a sub-section of users, create more documentation, and break BC with any plugins that display user data on the profile (I have such a project upcoming to add badges, like achievements for purchases), I'd love to know why is all.
