### ISSUE TITLE
Decimals stripped from prices

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#9255]
I'm not sure this is a bug since I was not able to reproduce it and also on the customer's site only some products had the issue.

So the decimals separator is a comma in the settings.

On a variable product, each variation has a different price like:

* 10,50
* 20,87
* etc.

The method `get_price` was returning a string with the decimals separator as a comma instead of the dot which you would instead expect (the price should be saved with a dot in the DB).

That comma was causing issues when calculating the price because `$price * qty` was returning an integer since it was a multiplication between a string and an integer, and since the decimals separator in that string is a comma, PHP does not convert that string to a float automatically.

While if the price returned by `get_price` has a dot as decimals separator, everything works like expected.

I fixed in the customer site by using 

```php
$price = wc_format_decimal( $price ) * $qty;
```

in `get_price_including_tax` in abstract-wc-product.php, but that's only a workaround for now.

Do you think this could be a bug in WooCommerce?

**Comment by mikejolley** [comment]
This will be an issue with how the user has imported prices. get_price() returns it however its stored in the database. This should be stored with a '.' dot. 

Commas will only be added when displaying the value on the frontend or in admin. It is never stored with comma. Look at the product and variation data for the error.
