### ISSUE TITLE
the payment gateways redirecting users to wrong URL

### ISSUE THREAD

**Issue by rebelholic** [woothemes/woocommerce#9265]
I'm using WC 2.0.16, with the latest version of WP. I am testing WC with many payment gateway such as cheque payment, cash on delivery, and etc. The only issue I'm having is when the user finishes a purchase and is being redirected back to my site, they are sent to a page with an incorrect address such as "http://galerigadget.com/payment/?key=order_560bb443d3fed&order=9004" (or "http://galerigadget.com/payment/") and just got blank screen.

I already tried everything to purchase a product with all payment gateways from my website still got same error like above.

Why is WooCommerce or the payment gateways adding the 'http://galerigadget.com/payment/' to the head of the URL? And how can it be removed? Any help would be greatly appreciated, as the authors don't seem to be very helpful with support.

I can't update WC to latest version because will break my current theme.

You can reproduce this bug with try to buy a product from my website: http://galerigadget.com/product/lenovo-s60/

**Comment by mikejolley** [comment]
This is a glitch with your gateway, not WooCommerce core. Your gateway handles the redirect.
