### ISSUE TITLE
Fatal error: Call to undefined method WC_Product_Simple::get_variation_attributes() 

### ISSUE THREAD

**Issue by mikakaltoft** [woothemes/woocommerce#9269]
Hi,

I have seen following issue on several websites, as I have been searching for a solution, so I thought it might be worth posting it here:

I am writing a simple plugin which starts with:

global $product;

$available_attributes = $product->get_variation_attributes();
$available_variations = $product->get_available_variations();

However, on the frontpage I get this:

Fatal error: Call to undefined method WC_Product_Simple::get_variation_attributes() 

How can I sole this problem?

Sincerely,
Mika

**Comment by mikakaltoft** [comment]
For anyone interested. I found the solution.

Change global $product to $product = new WC_Product_Variable( get_the_ID() );

**Comment by greguly** [comment]
Hi Mika, 

Sorry, but that is not the correct solution.....

See, you are force-changing a simple product to a variable product while you only should be checking if the product is variable or not.

This can help you: https://wordpress.org/support/topic/condition-to-check-if-product-is-simple-or-variable


Cheers,
Gabriel
