### ISSUE TITLE
Coupon's Description field showing HTML entities for special characters

### ISSUE THREAD

**Issue by niravmehta** [woothemes/woocommerce#9273]
Steps to reproduce:

1. Add a new coupon or edit an existing one from admin
2. Set code, set discount type, set amount
3. In coupon description field add special characters like `special characters " '!@#$%^&*`
4. Publish it & check coupon description field
5. Now keep clicking **Update** button & check for coupon description field. It keeps adding HTML entities  
![coupon-description](https://cloud.githubusercontent.com/assets/822681/10261911/9957dc0e-69ce-11e5-9b3a-79e3ac1d24c5.png)

Possible solution: 

Replace following line of code:

```php
<textarea id="woocommerce-coupon-description" name="excerpt" cols="5" rows="2" placeholder="<?php esc_attr_e( 'Description (optional)', 'woocommerce' ); ?>"><?php echo esc_textarea( $post->post_excerpt ); ?></textarea>
```

with this line of code:

```php
<textarea id="woocommerce-coupon-description" name="excerpt" cols="5" rows="2" placeholder="<?php esc_attr_e( 'Description (optional)', 'woocommerce' ); ?>"><?php esc_html_e( $post->post_excerpt ); ?></textarea>
```

Related ticket: Zendesk Ticket No. 340188

**Comment by WPprodigy** [comment]
Not sure if removing it is the best option though - for security reasons. Perhaps it would be better to use `htmlentities()` wrapped inside of `esc_textarea()`? http://php.net/manual/en/function.htmlentities.php

**Comment by niravmehta** [comment]
@WPprodigy Yeah, right. `esc_html_e()` is better. I updated the code above. Thanks.
