### ISSUE TITLE
"Uploaded to this post" as default

### ISSUE THREAD

**Issue by theleemon** [woothemes/woocommerce#9278]
Hi,

I'm the developer of the plugin [Default Media Uploader View](https://wordpress.org/plugins/default-media-uploader-view/), that sets "Uploaded to this post" instead of "All media items" as the default view in the WP media uploader. 

My question is, is possible to allow my plugin to change the default view in the "Product Gallery" window in WooCommerce, too? Is there a filter I can hook to or something?

Thanks in advance

**Comment by WPprodigy** [comment]
Not sure what you need to do, but the Product Gallery is just a custom meta box. You can see it here: https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-images.php
