### ISSUE TITLE
Reducing Line Items on Variable Products 

### ISSUE THREAD

**Issue by windsorraw** [woothemes/woocommerce#9280]
When I am in any order on the back end and trying to reduce line items on any variable product the loading circle begins to rotate however it gets stuck on this loading screen and the dialogue box to indicate the the item stock has been reduced does not appear. It simply continues to "load" indefinitely until I click save order. At this point it show that the line items have been reduced in the order notes but it only does it 1 product at a time. If I am reducing 10 items I have to do this process (select product -> select reduce line items (loading gets stuck) -> click save order) 10 times. If I try to select multiple products, as long as one of them is a variable product, I will have the same problem and will only reduce the line items on the very first product. 

If I select one or multiple non-variable products then there is no problem. Furthermore, If I select a single non-variable product and reduce line item then it works, the next variable product I select and reduce line items for will also work. Then I select another variable product and I am back to the same problem (loading gets stuck, no dialogue box and I have to click save order).

Please help this is very irritating and making my work very time consuming.

**Comment by mikejolley** [comment]
I'm not having this issue locally. Tested with 3 stock managed variations in an order, went to backend and reduced successfully. 

Suspect a plugin conflict in your install (error logs would confirm).
