### ISSUE TITLE
Enhancement: Add sort order field to product variation

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#9283]
With the new way of paginating variations, there is no way to sort variations completely. It's possible to drag and drop on the same page, but if a product has more than one page of variations, it's not an easy task.

As a possible enhancement, would it be possible to add a sort order field to each variation? That way, the store admin could edit that value to move variations. 

An alternate idea I've had is to allow the store admin to sort the variations based on the attribute terms. 

Thanks!

**Comment by MindyPostoff** [comment]
Although clicking on the drag & drop icon offers a pop-up to enter in a desired order number (http://cld.wthms.co/14xfi/39oA5Drm), it would be great if this order value could be included in the variation's meta data that is exportable using the Product CSV Import Suite.

**Comment by mikejolley** [comment]
Will be part of CSV export.
