### ISSUE TITLE
Fatal error: Call to a member function get_cart_url() on a non-object

### ISSUE THREAD

**Issue by HowdyMcGee** [woothemes/woocommerce#9284]
I have [All In One WP Security & Firewall](https://wordpress.org/plugins/all-in-one-wp-security-and-firewall/) installed. This allows me to set a limit on incorrect logins and lock users out for a certain amount of time. Once locked out, the user can "Request Unlock" which will send them an email and allow them to manually unlock themselves. It's found on the Login Page. 

Recently, when I click this Unlock button I get the following error by WooCommerce:

    Fatal error: Call to a member function get_cart_url() on a non-object in /httpdocs/wp-content/plugins/woocommerce/includes/class-wc-frontend-scripts.php on line 260

The unlock feature uses `wp-login.php` and is keeping my users from unlocking themselves.

**Comment by mikejolley** [comment]
@jeffstieler One to look at :) Suspect the login page will be messing with conditionals so some classes won't be loaded.
