### ISSUE TITLE
Custom Product Type Trouble

### ISSUE THREAD

**Issue by circleb** [woothemes/woocommerce#9289]
I'm having trouble with setting up a custom product type, please see this (erroniously) closed issue: #9239.

**Comment by WPprodigy** [comment]
Hi @circleb,

I'm sorry, but this is not the place to get help and support. I can ensure that it is possible to create a custom product type, as there are hundreds of plugins doing it. If there were an issue/error with this process, then you should report it here, but that is not the case.

There is a helpful answer in this thread that could help you get started: http://wordpress.stackexchange.com/questions/120215/how-to-add-a-new-product-type-on-woocommerce-product-types

**Comment by circleb** [comment]
@WPprodigy There actually IS an issue/error! The issue is that `$product->product_type` returns `simple` when it should be returning `slonlinecourse`.

**Comment by WPprodigy** [comment]
Sorry, I can't help you develop a plugin. 

This may help: https://wisdmlabs.com/blog/create-product-type-custom-settings-woocommerce/

**Comment by circleb** [comment]
@WPprodigy I already saw that example (I actually followed it to do what I've done). I'll dig a little deeper and post my findings...

**Comment by iskandar** [comment]
@circleb I commented on your original issue (#9239) with an answer that worked for me: https://github.com/woothemes/woocommerce/issues/9239#issuecomment-222349491
