### ISSUE TITLE
css syntactic error

### ISSUE THREAD

**Issue by ploki25233** [woothemes/woocommerce#9296]
on version 2.4.7, in file woocommerce/assets/css/woocommerce-smallscreen.css there is a css syntactic error: ( content: attr(data-title) ": "; ) the ": " invalidates the rest of the styles from that css

**Comment by jameskoster** [comment]
It's not the colon. It's `attr(data-title)`.

It's a validation error I'm willing to overlook. It's well supported and required for our responsive table styles.
