### ISSUE TITLE
Duplicate PayPal payments

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#9297]
Today a store I am involved in running received two PayPal payments from a customer for the same WooCommerce order.

The two payments were 45 minutes apart. Identical invoice ID (the WooCommerce order number), identical data in the Custom field (JSON with identical order_id and order_key).

I had thought this was impossible (I thought PayPal prevented it via some unique-to-the-order ID that WooCommerce passes it and recognises). I only became aware of it from the customer informing us. I've checked the WooCommerce PayPal logs. They do detect the duplicate ("Aborting, Order #130800 is already complete.").

However... would it be better if WooCommerce notified the store owner of an apparent duplicate payment? There's a different PayPal transaction ID, and at that point WooCommerce has verified that the payment is real, and can know that there are two transaction IDs (because it already recorded the earlier one).

**Comment by DavidAnderson684** [comment]
And then there's a follow-up problem... when I refund the duplicate PayPal payment (I was careful to duplicate the second payment - the one which WC detected as a duplicate, and whose transaction ID is *not* recorded in the database), WooCommerce then marks the order as refunded, and that in turn triggers all the actions on the store hooked into that (which, thankfully, was not much that could not be easily reversed in this case).

**Comment by mikejolley** [comment]
This coincided with some downtime of paypal IPN. So:

1. User paid
2. Order was not updated by IPN
3. User likely paid again after seeing the order was 'pending payment'

In this situation, not much WC can do. You can however setup PDT so when the user returns to the site, the order will update without relying on PayPal IPN.
