### ISSUE TITLE
Unable to create order with variations REST API

### ISSUE THREAD

**Issue by stevechan3310** [woothemes/woocommerce#9300]
I tried creating a new order with below JSON data:

POST
----------------------------------------------------------
order =     {
        "billing_address" =         {
            "address_1" = "Add1";
            "address_2" = "Add2";
            city = test;
            company = "Test company";
            country = MY;
            email = "test@gmail.com";
            "first_name" = abc;
            "last_name" = 123;
            phone =0123456789;
            postcode = 12345;
            state = PNG;
        };
        "customer_id" = 1;
        "line_items" =         (
                        {
                "product_id" = 12345;
                quantity = 1;
                variations =                 {
                    "pa_size" = XXXL;
                };
            }
        );
        "payment_details" =         {
            "method_id" = bacs;
            "method_title" = "Direct Bank Transfer";
            paid = 0;
        };
        "shipping_address" =         {
            "address_1" = "Add1";
            "address_2" = "";
            city = test;
            company = "";
            country = SG;
            "first_name" = abc;
            "last_name" = 123;
            postcode = 12345;
            state = "";
        };
        "shipping_lines" =         (
                        {
                "method_id" = "table_rate";
                "method_title" = "Table rates";
                total = "50.00";
            }
        );
        status = "on-hold";
    };

----------------------------------------------------------

Response
----------------------------------------------------------
order =     {
        "billing_address" =         {
            "address_1" = "Add1";
            "address_2" = "Add2";
            city = test;
            company = "Test company";
            country = MY;
            email = "test@gmail.com";
            "first_name" = abc;
            "last_name" = 123;
            phone = 0123456789;
            postcode = 12345;
            state = PNG;
        };
        "cart_tax" = "0.00";
        "completed_at" = "2015-10-07T05:22:14Z";
        "coupon_lines" =         (
        );
        "created_at" = "2015-10-07T05:22:14Z";
        currency = MYR;
        customer =         {
            "avatar_url" = "";
            "billing_address" =             {
                "address_1" = "Add1";
                "address_2" = "Add2";
                city = test;
                company = "Test company";
                country = MY;
                email = "test@gmail.com";
                "first_name" = abc;
                "last_name" = 123;
                phone = 0123456789;
                postcode = 12345;
                state = PNG;
            };
            "created_at" = "2015-01-30T08:19:51Z";
            email = "test@gmail.com";
            "first_name" = abc;
            id = 1;
            "last_name" = 123;
            "last_order_date" = "2015-10-07T05:22:14Z";
            "last_order_id" = 12168;
            "orders_count" = 7;
            role = customer;
            "shipping_address" =             {
                "address_1" = "Add1";
                "address_2" = "";
                city = test;
                company = "";
                country = SG;
                "first_name" = abc;
                "last_name" = 123;
                postcode = 12345;
                state = "";
            };
            "total_spent" = "438.00";
            username = abc;
        };
        "customer_id" = =1;
        "customer_ip" = "122.123.123.123";
        "customer_user_agent" = "(iPhone; iOS 8.4; Scale/2.00)";
        "fee_lines" =         (
        );
        id = 12121;
        "line_items" =         (
                        {
                id = 468;
                meta =                 (
                );
                name = "Some dress";
                price = "368.00";
                "product_id" = 12107;
                quantity = 1;
                sku = B1683;
                subtotal = "368.00";
                "subtotal_tax" = "0.00";
                "tax_class" = "<null>";
                total = "368.00";
                "total_tax" = "0.00";
            }
        );
        note = "";
        "order_number" = 12168;
        "payment_details" =         {
            "method_id" = bacs;
            "method_title" = "Direct Bank Transfer";
            paid = 0;
        };
        "shipping_address" =         {
            "address_1" = "Add1";
            "address_2" = "";
            city = test;
            company = "";
            country = SG;
            "first_name" = abc;
            "last_name" = 123;
            postcode = 12345;
            state = "";
        };
        "shipping_lines" =         (
                        {
                id = 469;
                "method_id" = "table_rate";
                "method_title" = "Table rates";
                total = "50.00";
            }
        );
        "shipping_methods" = "Table rates";
        "shipping_tax" = "0.00";
        status = "on-hold";
        subtotal = "368.00";
        "tax_lines" =         (
        );
        total = "418.00";
        "total_discount" = "0.00";
        "total_line_items_quantity" = 1;
        "total_shipping" = "50.00";
        "total_tax" = "0.00";
        "updated_at" = "2015-10-07T05:22:14Z";
        "view_order_url" = "";
    };

----------------------------------------------------------

As you can see, I POST line items with variations. According to the docs, it should return the variations in the meta of line items in response. May I know is this a bug or is it anything im doing wrong? Please advice.

**Comment by claudiosmweb** [comment]
Follow the documentation that everything will work: http://woothemes.github.io/woocommerce-rest-api-docs/#create-an-order

I do not know what language you are using for it, but I don't think this generates a valid JSON.

**Comment by tkchuah** [comment]
Hey guys, this issue is not fixed. PLease refer to #9338 to see how this bug is fixed
