### ISSUE TITLE
Issue with variations/attributes containing spaces or uppercase characters 

### ISSUE THREAD

**Issue by jchaps21** [woothemes/woocommerce#9301]
When an attribute value contains a space (eg. 'light blue' instead of just 'blue') and is used for a variable product, an error message appears when you load the product page on the front end: A popup appears that says "No products found which match your selection." and it doesn't allow you to select anything from the dropdown.

This means we're unable to add variations such as 'item with gift box'.

The problem also occurs when an attribute value contains any uppercase characters.

Any fixes or workarounds?

**Comment by mikejolley** [comment]
This is your template - I believe its bundling an outdated variations template file.

View your system status report to confirm and update the theme. FYI attributes used to be sanitised, but are no longer, hence the issue on your site only.
