### ISSUE TITLE
Tax does not work for variations on the product page

### ISSUE THREAD

**Issue by aureliendebord** [woothemes/woocommerce#9303]
Hello Guys,

Tax does not apply on the variations of my product :
http://www.nautiboutique.fr/produit/commande-joystick-maxpower-double-pour-propulseurs-avant-et-arriere-noire/

But if, the product is added to the cart, the tax is correctly applied.

FYI : I set the parent product "taxable" and this tax status is inherited.

I really don't get it.
Any help is welcomed.

Thanks

PS : this problem occurs with 2.4.7. No problem with an older version.

**Comment by daigo75** [comment]
It could be due to the same issue described in my PR #9226.

**Comment by aureliendebord** [comment]
https://github.com/woothemes/woocommerce/commit/44f4a3b9be000a4d84fc682e1a34505607c6a3b8

**Comment by daigo75** [comment]
:+1:
