### ISSUE TITLE
Can adding new shipping classes be like adding email classes?

### ISSUE THREAD

**Issue by asalkey** [woothemes/woocommerce#9307]
It seems like I have to create a new plugin for each shipping method I want to make looking at this guide https://docs.woothemes.com/document/shipping-method-api/. 

Is there anyway I can add new shipping classes like I can add emails?

something like...

    add_filter( 'woocommerce_shipping_classes', 'add_woocommerce_shipping' );
    function add_woocommerce_shipping( $shipping_classes ) {
     
        require_once(  SUBSCRIPTION_PLUGIN_PATH . '/classes/Subscriptions_Direct_Shipping.class.php' );

        $email_classes['Subscriptions_Direct_Shipping'] = new Subscriptions_Direct_Shipping();

        return $shipping_classes;
    }

**Comment by mikejolley** [comment]
What do you mean by shipping classes? What are you attempting? Why can't you use the API like other shipping extensions?

**Comment by asalkey** [comment]
I was trying to get all my shipping methods in one plugin without creating a new plugin for each like the example in the docs show. I was able to get everything working similar to how new email classes are loaded..


           class Delivery_Loader
           {
                public function __construct()
                {
                   add_action( 'woocommerce_shipping_init', array( &$this,'delivery_zones') );
                   add_filter( 'woocommerce_shipping_methods',array( &$this,'delivery_method' ));
                 }

                public function delivery_zones( $shipping ) {

                         require_once(  DELIVERY_PLUGIN_PATH . '/classes/shipping/delivery_zones.php' );

                         $shipping['delivery_zones'] = new Delivery_Zones();

                       return $shipping;
               } 

                  public function delivery_method( $methods ) {
                      $methods[] = 'Delivery_Zones';
                     return $methods;
                 }
             }
