### ISSUE TITLE
Administrator with Sub-role of Customer loses access to Posts Admin Menu

### ISSUE THREAD

**Issue by garrett-eclipse** [woothemes/woocommerce#9309]
Hello,

Don't ask me why my administrator got a sub-role of customer but when an administrator has a customer role on them they then lose access to the backend menu items for 'All Posts' and 'Add New' under posts. They can access pages just not posts or anything that has a posts capability setting such as a custom post type.

Would have figured the admininistrator role would add the capabilities rather than the customer role blocking capabilities.

Thoughts?
Thanks
P.S. I've removed the role just wanted to raise as I figured it was a bug that the customer role blocks the edit_posts capability even is they also have a higher level role applied to them.

**Comment by mikejolley** [comment]
Sub-role? A user has 1 role (https://codex.wordpress.org/Class_Reference/WP_User#set_role.28.24role.29) - but can have multiple capabilities. WC checks the capabilities for things like manage_woocommerce edit_products edit_shop_orders etc etc.

If the admin was made into a customer, then they rightly don't have access. If you're using a role managing plugin, be careful to assign the correct caps to the correct roles.

**Comment by garrett-eclipse** [comment]
Hi @mikejolley 

That's actually not correct, a user has a primary role and can have multiple sub-roles. See add_role to add additional roles, set_role replaces all roles with one primary role.
https://codex.wordpress.org/Class_Reference/WP_User#add_role.28_.24role_.29

So the administrator can have a primary role of Administrator with sub-roles of Customer, etc. As is my case.

From the default WP user edit page you can only set the primary role, however you can programatically add additional roles through WP_User::add_role function. Or if you opt to install a role manager such as [WPFront User Role Editor](https://wordpress.org/plugins/wpfront-user-role-editor/) a gui interface is introduced to the user edit page to manage sub-roles;
![screen shot 2015-10-08 at 9 36 12 am](https://cloud.githubusercontent.com/assets/8726005/10373090/11edda4a-6da0-11e5-8538-a60bc11948b9.png)

If this wasn't the case then plugins like Buddypress wouldn't be able to operate as they require a sub-role for their Forum Role (Keymaster, Moderator, Participant, etc.)

So the admin isn't actually added as a customer they've just had customer added as a sub-role through the WP_User::add_role function. And with primary and sub-roles standardly capabilities are simply added to the user but in this case they appear to be detracted when the customer is applied as a sub-role.

Looking into the Woocommerce plugin and the customer role it appears that rather than adding capabilities it actually removes the edit_posts and delete_posts capabilities by setting them to false;
```php
		// Customer role
		add_role( 'customer', __( 'Customer', 'woocommerce' ), array(
			'read' 						=> true,
			'edit_posts' 				=> false,
			'delete_posts' 				=> false
		) );
```
This is in woocommerce/includes/class-wc-install.php on line 483

So to me Woocommerce has their customer role set-up to remove capabilities rather than the standard approach of only adding needed capabilities. Is there a reason for this? I amended woo on my instance and re-installed to have the customer role only add the read capability and not remove any capabilities which corrects the issue allowing the admin to have a sub-role of customer which is useful as it indicate they've made purchases through the website.

Amended code:
```php
		// Customer role
		add_role( 'customer', __( 'Customer', 'woocommerce' ), array(
			'read' 						=> true
		) );
```

Let me know your thoughts as I don't foresee any conflicts or issues caused by this change as users with only the customer role won't have the edit_posts or delete_posts capabilities still it just means if this is a sub-role on a user that the capabilities aren't disabled/denied.

Thanks

**Comment by garrett-eclipse** [comment]
@mikejolley to reproduce/test this you can either enable a Role Editor or add a user programatically as follows (this creates an admin with sub-role of customer);
```php
add_action('init', 'add_my_user');
function add_my_user() {
    $username = 'username';
    $email = 'email@domain.com';
    $password = 'password';

    $user_id = username_exists( $username );
    if ( !$user_id && email_exists($email) == false ) {
        $user_id = wp_create_user( $username, $password, $email );
        if( !is_wp_error($user_id) ) {
            $user = new WP_User($user_id);
            $user->set_role( 'administrator' );
            $user->add_role( 'customer' );
        }
    }
}
```

You'll notice when you login as this admin user who has a sub-role of customer that he can't add new posts or even see the posts listing.

If you then update the woocommerce plugin removing the denied capabilities (edit_posts & delete_posts) from the customer role and reset roles through Woocommerce > System Status > Tools > Reset Capabilities logging in again you'll notice he then has proper admin privileges.

Cheers

**Comment by garrett-eclipse** [comment]
Thanks @mikejolley
