### ISSUE TITLE
REST API - Setting of order_number not working

### ISSUE THREAD

**Issue by darkkean** [woothemes/woocommerce#9310]
I am using the "Create An Order" REST API end-point and have set a value to order_number. However it seems not applying and when viewing the orders in Dashboard -> Woocommerce -> Orders, the order number is still showing the default.

In
> woocommerce/includes/api/class-wc-api-orders.php

This code seems to set order_number, but the _order_number field it isn't used anywhere so it has no effect.

```
// set order number
if ( isset( $data['order_number'] ) ) {
    
    update_post_meta( $order->id, '_order_number', $data['order_number'] );
}
```

**Comment by claudiosmweb** [comment]
We don't have `_order_number` on core.
This as been removed.

**Comment by darkkean** [comment]
Thanks @claudiosmweb for confirming.

To everyone else who want to use this feature, the
> update_post_meta( $order->id, '_order_number', $data['order_number'] );

is actually working and it adds new line in wp_postmeta table.

If you want your woocommerce to use this order number instead of the default ID, copy and paste the below code in your themes/theme-folder/functions.php file.

````
// Display custom order number in WP-Dashboard and Client-end

add_filter( 'woocommerce_order_number', 'custom_display_order_number', 10, 3 );

function custom_display_order_number( $order_number, $order ) {
  if ( $custom_order_number = get_post_meta( $order->id, '_order_number', true ) )
      $order_number = $custom_order_number;

  return $order_number;
}
````

**Comment by claudiosmweb** [comment]
Here a code to make the API save this field, if necessary for someone:

```php
function my_wc_api_save_order_number( $order_id, $data ) {
	if ( isset( $data['order_number'] ) ) {
		update_post_meta( $order_id, '_order_number', sanitize_text_field( $data['order_number'] ) );
	}
}

add_action( 'woocommerce_api_create_order', 'my_wc_api_save_order_number', 10, 2 );
add_action( 'woocommerce_api_edit_order', 'my_wc_api_save_order_number', 10, 2 );
```
