### ISSUE TITLE
How to Contribute Code to WooCommerce Repository?

### ISSUE THREAD

**Issue by nishitlangaliya** [woothemes/woocommerce#9311]
Hello,

I want to contribute my code to WooCommerce Repository. I am facing Issue regarding commit changes in minified js files. anybody would you please let me know steps for commit my changes.

For Example I have made changes in abc.min.js file. now I want to commit my changes to repository than should I commit abc.min.js file with minified version or I should just put my code to abc.min.js file and woocommerce will minify it ? Any thoughts and suggestions please....

**Comment by shivapoudel** [comment]
@nishitlangaliya Have a look to WooCommerce contributing guidelines:
https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

**Comment by nishitlangaliya** [comment]
@shivapoudel , Thanks for reply, my query is regarding pushing minified js file. suppose I need to write one function in abc.min.js file then should i commit that file just put that function in min file and commit or I should first make that file minify and then commit ?

**Comment by shivapoudel** [comment]
> suppose I need to write one function in abc.min.js file...

@nishitlangaliya you can't directly make changes in minified `*.min.js`. First you should make changes to unminified file `*.js` and should minify those files using grunt task. 

Also do not submit the minified file changes during Pull request as it may arouse merge conflicts. Only you have to submit the changes in unminified file.

**Comment by nishitlangaliya** [comment]
@shivapoudel, 
Thanks for your reply.

Here what I understood is , what ever the changes I need to do in 'abc.min.js' file, First I should put that code into simple 'abc.js' file and then commit those changes ? and Woocommerce will automatic merge that changes into .min.js file using grunt. am I on the same page. 

Because  I see that in my local server .min.js file is calling in view source. so on that bases I put my code into .min.js file and it worked for me here in my local server.

**Comment by shivapoudel** [comment]
> Woocommerce will automatic merge that changes into .min.js file using grunt. am I on the same page.

@nishitlangaliya Nope, Woocommerce will not automatic merge those changes by respective developers does this task ;)

> I see that in my local server .min.js file is calling in view source.

Try to add `define( 'SCRIPT_DEBUG', false );` in your `wp-config.php` so that WordPress and WooCommerce can load unminified `*.js` script files xD

**Comment by nishitlangaliya** [comment]
@shivapoudel , Thanks, I understood your concern and yes define( 'SCRIPT_DEBUG', true ); worked for me and I changed my code and made  pull request. ref #3f74539
