### ISSUE TITLE
Html Validator fixes

### ISSUE THREAD

**Issue by tomob7** [woothemes/woocommerce#9314]
Hi,

What's your stance on making woocommerce a bit more compatible with https://validator.w3.org/nu/

There only little things but Particularly the container ID (id="container") is used in a lot of themes and so duplicates, could this be renamed id="wc-container" or something, also the product search form has a for="s" but no ID on the input.

There may be a few other things and forgive me if they are only issues I am having but I think it would just help speed website checking up a little for people who use this service.

**Comment by jameskoster** [comment]
Validation is something that's nice to have, but not really a priority. Any small changes and enhancements would be appreciated, but we have to be extremely careful when changing things like class names and IDs so as to not break backwards compatibility. It's not worth it.

We have a similar issue open here: https://github.com/woothemes/woocommerce/issues/9055 so I'll close this one for now.

For 2.6 we'll probably look to add standardised class names with a view to removing them in 3.0.

**Comment by CNick** [comment]
Hi,

While validation may be considered by some as nice to have, the WordPress HTML Coding Standards state that "All HTML pages should be verified against the W3C validator to ensure that the markup is well formed."

Reference: https://make.wordpress.org/core/handbook/best-practices/coding-standards/html/

Currently, the templates/product-searchform.php file uses invalid HTML 4 form code. When the `for` attribute is used in a label tag, the ID of the input must match, and the ID of the input cannot be omitted.

Reference: http://www.w3.org/TR/WCAG-TECHS/H44.html

I propose changing this form to follow the HTML 5 example provided by WordPress – nest the input inside of its label. This does not require the `for` attribute and the ID on the input.

Reference: https://codex.wordpress.org/Function_Reference/get_search_form#Default_HTML5_Form

Earliest version that has issue:  2.30 (best I can tell)

**Comment by jameskoster** [comment]
@CNick This is a perfect example of something that would be nice to have. Please feel free to send a PR for things like this.
