### ISSUE TITLE
Inconsistent classes on products

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9317]
On a variable product, the pricing is wrapped in `single_variation_wrap` and `single_variation`.  

Single products do not follow this convention. So i'm thinking, can we have it so `single_product_wrap` and `single_product` are in the same place? 

This will allow for consistent styling throughout different types of products.

**Comment by mikejolley** [comment]
single_variation_wrap wraps a variation. A variation is not a product - its something within a product, so having same classes probably doesn't make sense in this case. Look at the body/product page wrappers for the classes which are consistent across product types.

**Comment by yratof** [comment]
But styling from a body class means we have to nest styles deeply and then overwrite other classes to make sure the desired style is applied.

What reasons are there for not adding classes to elements that are regularly styled?

There are no wrappers for the pricing, this includes stock quantity and price for single, yet those are wrapped on a variation.

If you are to follow the single product style, remove the price and quality from the variation wrapper, as they belong to all products and not just variations

**Comment by mikejolley** [comment]
Variable products need to be handled differently. There are classes on the product wrapper too; not just body.

**Comment by yratof** [comment]
but i don't think, for both performance and styling purposes, trying to change everything with a body or page class is the optimal way of doing these things.

Take the `cart` class for example. How is a variable product a cart? Variable products have `variations_form cart` as the class., which means you can't style `.cart` without affecting other pages that aren't even relevant.

Class refactoring needs to happen throughout woocommerce. Not removing the, but describing and being more specific. There are instances where the only difference between `.price` on the variation page is one is a `span` and one is a `p`. But since they are just `.price`, they're repeated on the categories page, the cart page, the checkout. Each with different layouts usually and styled differently.

**Comment by mikejolley** [comment]
I'm not talking about body classes. Have you viewed source? Look at the post_class

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/master/templates/content-single-product.php#L38

**Comment by yratof** [comment]
I understand your condescension, but it still means you have to write a
whole new set of styles for everything, overwrite other styles and nest 4-5
levels deep to be able to target something

Is there an underlining reason why anything class related is always
rejected as an issue? Anything remotely related to helping front end
styling seems to be closed instantly, often with a harsh tone.

I have been building woo commerce websites for some time now and i'm
familiar with many designers who hand over designs, knowing the abilities
of WC, yet every site there are always things that are missing from
woocommerce that could be implemented to help.

If there's another reason why being more specific with classes is an issue,
please flag that so I know i'm not missing something. My honest guess would
be that it messes up javascript somewhere & it's much easier to carry on
with the same classes woocommerce has had for several versions, avoiding
any conflicts.

**Comment by yratof** [comment]
Perhaps it would be better to allow classes to be added via filters

**Comment by mikejolley** [comment]
I really don't get your issue; it doesn't matter how high up the wrapping class is.

`
.product-type-variable
.product-type-simple
`

etc etc then target whatever element inside that area. Adding more classnames is overkill and just bloats up the markup even more than it already is. cc @jameskoster

**Comment by forsvunnet** [comment]
I'd prefer a good class to select over a long string of selectors. Chaining together long strings is also bad for CSS performance.

Mozilla has a great writeup on the subject: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Writing_efficient_CSS

**Comment by mikejolley** [comment]
It doesn't need to be more specific. Price for example:

`
.product-type-simple .price {}
`

Thats no more complex than:

`
.single_variation_wrap .price {}
`

**Comment by forsvunnet** [comment]
I think the issue here is that variations a double wrapper around quantity and add-to-cart (`.single_variation_wrap > .variations_button`) whereas single product does not.

Ideally this should be standarised so that all types of products has the same type of markup.
Something like:
`.actions_wrap.single_variation_wrap > .actions_button.variations_button`
and
`.actions_wrap.single_wrap > .actions_button.variations_button`
etc..

That would make it easier to style and script when you need to do general things that spans between different types of products.
