### ISSUE TITLE
(Perhaps feature request) Shipping prices are always treated as "exclusive of tax"

### ISSUE THREAD

**Issue by daigo75** [woothemes/woocommerce#9320]
One of my clients pointed out to me that, even though WooCommerce Tax settings is on "Yes, I will enter prices inclusive of tax", the shipping costs are always considered exclusive of tax. Initially I thought that the system was configured incorrectly, but no matter what we tried the tax was always added on top of shipping prices. I then looked at the code, and noticed the following.

Shipping tax calculation occurs in `WC_Shipping_Method::add_rate()`
~~~
[...]
// $total_cost is always the total shipping cost BEFORE tax
WC_Tax::calc_shipping_tax( $total_cost, $rates );
~~~

Then, in `WC_Tax::calc_shipping_tax()`:
~~~
public static function calc_shipping_tax( $price, $rates ) {
  return self::calc_exclusive_tax( $price, $rates );
}
~~~
There is no check to verify if prices are inclusive of tax, the calculation is always treating shipping prices **exclusive** of tax.

Is this logic by design (on purpose), or is it a limitation that will be removed in the future?

**Comment by mikejolley** [comment]
It's noted here https://trello.com/c/cjHijcxy/19-shipping-inc-tax-prices-4425 Limitation. Fixing will have BW compat issues.

**Comment by daigo75** [comment]
It should be possible to fix it while still keeping backward compatibility. Simply add a new option called "enter shipping costs inclusive of tax". Leave it disabled by default, and that will trigger the calculations ad they are at the moment. Existing sites won't be affected, unless the Administrator explicitly chooses to enable shipping costs inclusive of tax.


Of course, this applies as long as there isn't something else, of which I'm not aware, that should be considered.




On Fri, Oct 9, 2015 at 2:34 AM -0700, "Mike Jolley" <notifications@github.com> wrote:
It's noted here https://trello.com/c/cjHijcxy/19-shipping-inc-tax-prices-4425 Limitation. Fixing will have BW compat issues.

---

**Comment by mikejolley** [comment]
Yeah, it will need extra options to ensure BW compat. But one for the future.

**Comment by daigo75** [comment]
I'm not sure I understand what you mean with "but one for the future", but, as long as we can confirm that current behaviour is just how WC works (i.e. it's not that we misconfigured it), I can explain it to my clients. :)




On Fri, Oct 9, 2015 at 2:46 AM -0700, "Mike Jolley" <notifications@github.com> wrote:
Yeah, it will need extra options to ensure BW compat. But one for the future.

---

**Comment by mcombuechen** [comment]
+1 up for this one. Here in Germany we generally show the customer prices inclusive of tax, and the shipping is treated with the highest tax rate from the cart items. So if I have a cart full of 7% VAT items, the shipping costs only have 7% VAT. If a 19% VAT item is in the cart, the shipping needs to have 19% VAT. Still the final shipping costs should be the same in both scenarios. This makes this functionality legally essiential for the German market (not sure on other EU countries).

@mikejolley is there a snippet to fix this for the latest WC version you could provide, or some filter hooks you could point us to to recalculate the shipping taxes? So far I found the ´'woocommerce_get_shipping_tax'` filter but it doesn’t really change anything.

**Comment by mcombuechen** [comment]
sorry @mikejolley I just saw that we Germans have been nagging about this for quite some time. Just hope you guys can bump up the priority for this feature!

**Comment by daigo75** [comment]
I'm actually surprised of that rule for the German market. I never heard of a "dynamic VAT rate" in Europe, shipping has always been considered a service and taxed accordingly.


For example, food often has a 0 to 4% VAT, but the shipping for a box of food would be taxed at the highest rate. This is why WooCommerce allows to choose a separate tax class for the shipping.


Allowing to enter shipping prices inclusive of tax would not make them "inherit" the VAT rate from the goods. That would still require a customisation, if I'm not mistaken, and it might be possible to do it already, even though the shipping price would change depending on the VAT applied to the goods.




On Fri, Nov 6, 2015 at 12:49 AM -0800, "Maximilian Combüchen" <notifications@github.com> wrote:
+1 up for this one. Here in Germany we generally show the customer prices inclusive of tax, and the shipping is treated with the highest tax rate from the cart items. So if I have a cart full of 7% VAT items, the shipping costs only have 7% VAT. If a 19% VAT item is in the cart, the shipping needs to have 19% VAT. Still the final shipping costs should be the same in both scenarios. This makes this functionality legally essiential for the German market (not sure on other EU countries).

@mikejolley is there a snippet to fix this for the latest WC version you could provide, or some filter hooks you could point us to to recalculate the shipping taxes? So far I found the ´'woocommerce_get_shipping_tax'` filter but it doesn’t really change anything.

---

**Comment by mcombuechen** [comment]
I got this info off a law firms website (in German): http://www.it-recht-kanzlei.de/umsatzsteuer-versandkosten-mehrwertsteuer.html
It says that shipping is treated as a “service fee” and its tax rate depends on the order’s items. So if you send out a loaf of bread at 7%, shipping includes 7%. If you send out a bottle of rum at 19%, shipping should include 19%. Furthermore, it gets super confusing when an order includes both 7% and 19% items: the tax rate should take the ratio of the items’ values into consideration. Here I’d just become lazy and take the 19% :-)
I’m just working on a store with mainly food items at 7% VAT, but there is a couple of products (t-shirts, coffee mugs etc.) that are taxed at 19%.

**Comment by daigo75** [comment]
Correction to my last reply. It seems that WooCommerce already includes the logic to get the shipping tax from the items, as "the highest tax rate applicable". From `WC_Tax` class,  line 435:


// This will be per order shipping - loop through the order and find the highest tax class rate


I haven't tested it yet, but it seems that such logic is triggered by leaving the shipping tax class empty in WooCommerce settings.



On Fri, Nov 6, 2015 at 12:49 AM -0800, "Maximilian Combüchen" <notifications@github.com> wrote:
+1 up for this one. Here in Germany we generally show the customer prices inclusive of tax, and the shipping is treated with the highest tax rate from the cart items. So if I have a cart full of 7% VAT items, the shipping costs only have 7% VAT. If a 19% VAT item is in the cart, the shipping needs to have 19% VAT. Still the final shipping costs should be the same in both scenarios. This makes this functionality legally essiential for the German market (not sure on other EU countries).

@mikejolley is there a snippet to fix this for the latest WC version you could provide, or some filter hooks you could point us to to recalculate the shipping taxes? So far I found the ´'woocommerce_get_shipping_tax'` filter but it doesn’t really change anything.

---

**Comment by mcombuechen** [comment]
It sure does, the "highest tax rate" thing works well. But the problem is the input of the flat rate shipping costs. Let’s say I want to charge my customers € 5,00 for shipping. What do I enter? If I knew all my products were taxed at 7%, I could enter € 4,67 and be sure that the final costs will be € 5,00. But when a customer buys something at 19%, the final shipping costs will be € 5,56. Or am I missing a nifty way to configure WooCommerce?

**Comment by daigo75** [comment]
No, that's correct. The shipping cost is **always** excluding tax. WooCommerce will take whatever shipping applies to the order, and add the taxes on top of it. It's a hard-coded logic, as I pointed out at the beginning. There are no filters or settings to change it, the core itself must be modified.

**Comment by daigo75** [comment]
**Off-topic**
@mcombuechen I just read the article you linked, from the law firm. The bureaucracy of that country sometimes surprises me. I can't believe how efficient they can be, with all this red tape. My country has an equal amount of useless rules, and nothing works due to that. :smile:

**Comment by Szendy** [comment]
In Hungary the same situation. The shipping tax always equals the highest tax rate which in your chart. And the flat rate shipping gives the wrong amount.

**Comment by tex0gen** [comment]
I still cannot believe this has not been fixed. 3 years after the issue was raised and still no solution, despite a perfectly adequate fix being mentioned. "One of the future".. how far in the future are we talking here?!

**Comment by mrgrandmother** [comment]
I can confirm that the same rules apply in Norway (and in other countries too: https://wordpress.org/support/topic/shipping-tax-calculation-issue/ ) and that this is an important fix for all stores. 

VAT-rate on shipping is inherited from the highest VAT-rate of the products being shipped. This functionality works well and as intended. 

The problem is that there is no way to get a flat rate shipping including VAT regardless of what the excluding VAT cost for shipping is. I can only get a flat rate shipping excluding tax. 

Hence I have one product where shipping is 68 and another where shipping is 85 to the customer. But on the backend it is a flat fee for shipping at 68.

**Comment by BusinessBloomer** [comment]
This must be reopen, it's a big mess entering product prices inclusive of Tax while keeping shipping prices exclusive of Tax

@mikejolley @rrennick can you please give us an ETA?

**Comment by JamboMedia** [comment]
We have the problem also in the Netherlands. 2 different VAT rates, it is not possible to have the same shipping cost now.

It is also very strange to fill the price excluding VAT(at the flat rate shipping) almost al shops want to show the prices including VAT.

Please fix this asap!

**Comment by GustyZ** [comment]
Hy @mikejolley! Any news about exclusive tax of shipping prices?

**Comment by michaelbourne** [comment]
How many votes are needed for an ecommerce plugin to consider offering proper financial calculations? :/

Please fix this. Flat Rate Shipping needs a tax inclusive option.

**Comment by Masterjoa** [comment]
Same in Belgium...
Having an "enter shipping costs inclusive of tax" option would fix everything.
I can't believe this has not been addressed yet 🙄

**Comment by jonathannz** [comment]
This is also a hassle even in countries with just one tax rate. But at least when there is only one tax rate, there's a workaround (that gives you a fixed tax inclusive shipping rate, whilst avoiding potential rounding issues through the rate off). You can enter the rate as TAX-INCL-SHIPPING / 1.[the tax rate]. So, with 12% tax, and a $6 tax inclusive shipping price, you'd enter the shipping cost as:  `6 / 1.12`. Magically, that will give you the desired result (namely, exactly $6, including tax, for shipping).

**Comment by tomknaepkens** [comment]
Is there still no fix after 5 years or have I missed something? Or has anyone found a way around this? This is a real pain if you need to combine multiple products with each their own tax rates for shipping..

**Comment by BennyBolivar** [comment]
Maybe there is a solution by using the shipping cost formula? Something like price - (price/100*[tax])?

**Comment by betzebu** [comment]
Same in Germany... Also need a fix for that..

**Comment by daigo75** [comment]
I tried to prepare a "fix" using a filter. It's experimental, and I didn't have the time to test it on many shipping methods, but it should work. Code snippet here: https://pastebin.com/jifVtqFQ

**Comment by drenina** [comment]
@daigo75 This does not work for me. The shipping cost for the prduct with the lower tax rate is 1 Cent less than the shipping cost entered in backend. For products with the higher shipping rate it is working however.

**Comment by daigo75** [comment]
@drenina A difference of 1 cent could be causes by rounding. You can try altering the custom code to use a greater precision (more decimals) for the calculations, that might be sufficient to fix the discrepancy.

**Comment by drenina** [comment]
@daigo75 Yes, that seemed to work! One question though: In Germany you are reequired to have the shipping tax be based on the products, so if you have one product in the cart with tax rate 19 %, and one with 7%, the shipping tax needs to be half 19%-half 7% . Currently Woocommerce automatically applies the higher tax rate to the shipping cost. Do you know how to change this?

**Comment by daigo75** [comment]
I'm afraid that I wouldn't be able to give a ready made example of how you could handle the "mixed VAT" condition. Perhaps it could be a matter of splitting the base cost into parts, applying the correct VAT to each part, then use each amount to recalculate the ex-VAT value. 

I would recommend to consult your accountant, to find the best approach. If you are using a plugin like WooCommerce Germanized or WooCommerce German Market, its authors should also be able to tell you how to calculate the VAT inclusive amount for each portion of the shipping costs.

**Comment by webdesignpresse** [comment]
+1 here! Can't believe that after so many years such a feature has still not been integrated.

**Comment by Trischan** [comment]
@mikejolley can we please, pretty please get this issue some more priority? It's rediculous that WooCommerce doesn't allow it's users to follow their national laws and maintain professional image. This request has been pretty much ignored for over 5 years now.

**Comment by tfourk** [comment]
I'm having the same issue in 2020. Tax calculations on shipping has suddenly STOPPED. It worked fine. Then we noticed a discrepancy in our bills.  We need to charge tax on shipping for items shipping in the same state.. But it doesn't do it. I have no idea What to do...? 5 years? Honestly?

**Comment by BuroStaal** [comment]
+1 We really needs this functionality in the Netherlands to comply with Dutch tax laws. The only thing we need is an option to enter shipping costs including VAT. Is there a timeline for this issue? @mikejolley 

Thanks for your fix @daigo75 , going to test it asap!

**Comment by djvuchet** [comment]
Hello, I have the exact same issue in Chile. By law, all prices must be Tax Inclusive, including shipping, and chilean tax 19% is applied  to shipping cost, even when I specified "Yes, I will enter price inclusive of tax". I have seen many other posts asking for this feature, but it seems all are getting ignored.

**Comment by janv01** [comment]
Fix of @daigo75 works fine, or you could also buy the plugin to solve this issue:
https://aelia.co/shop/tax-display-by-country-for-woocommerce/
But nevertheless I agree with the others that Woocommerce should respect tax laws and give them more priority.

**Comment by daigo75** [comment]
@janv01 thanks for your feedback. The Tax Display by Country plugin you linked is one of mine, but it doesn't keep shipping costs fixed, due to the logic described in this thread. If WooCommerce were to apply the same tax calculation logic to shipping and product prices, then the "fixed prices" feature should work for shipping costs as well.

**Comment by janv01** [comment]
I totally agree to that, for now your fix works good enough for me. Thanks.

**Comment by melek** [comment]
A customer had this problem recently (4159446-zen). Their case is simple; they want the price + shipping to be constant throughout their shipping area, even across different tax rates - but they want correct tax lines, so want to absorb the costs. They are using the `woocommerce_adjust_non_base_location_prices` filter flag ([experimental feature](https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#prices-including-tax---experimental-behavior)) to absorb product cost differences across tax zones, but can't do the same with shipping costs.

@inspiredearth's "Cost / 1 + Tax Rate" solution is the best solution right now, setting up shipping zones for each country so they can have flat rate shipping appropriate for the corresponding tax zone. I found this also [documented by a user here](https://annaschneider.me/calculate-shipping-cost-including-tax-woocommerce/).

Unfortunately, the workaround solution is fragile regarding complex shipping setups, and as more Woo shops are opening up across borders with complex tax differences, this flat rate option can help shops that want to improve the customer experience without additional plugins. Maybe it could be implemented with a filter like the other snippet.

Hopefully this could also be applied when creating manual orders, which is a problem with the other snippet in #26067.

**Comment by PontusTideman** [comment]
Tried to remove the VAT today on a manually order, without pressing the recalculate button WooCommerce multiplied EACH item by 10 in the order...

Because we are shipping to other countries outside EU, we can't charge them VAT on the shipping. But when you remove the VAT from the shipping line and then save the order, WC is freaking out and multiplies the items price by 10!!

**Comment by alpha-pix** [comment]
+1 for this. I'm in the UK, and it works very similarly to Germany. I can live with using standard rate VAT if anything is taxable in the basket, instead of the averaging approach; but it's a mess for me if the basket is not taxed.

I was wondering if the reason this hasn't been implemented is to do with the need for a deeper overhaul of calculations on tax inclusive prices, as the rounding errors on refunds have been driving me nuts.

**Comment by stgoos** [comment]
> One question though: In Germany you are reequired to have the shipping tax be based on the products, so if you have one product in the cart with tax rate 19 %, and one with 7%, the shipping tax needs to be half 19%-half 7% . Currently Woocommerce automatically applies the higher tax rate to the shipping cost. Do you know how to change this?

Same for The Netherlands and I reckon this will apply to most, if not all, of the countries within the European Union as it's the agreed method to counter VAT evasion via non taxed shipping costs.

Just charging the highest percentage would not be correct BUT it at least ensures you're not paying to little taxes which potentially result in a fine by the tax office.

What I would love to be able to do is to insert the shipping price **included** VAT and that it then gets translated to an **excluded** VAT price depending on the applied tax category (for the shipping address / country).

So e.g. when the shipping price is € 6,75 then I would like to see the € 6,75 as the shipping price for all countries - regardless of the (highest) local VAT percentage:

- **NL** has **21%** VAT, so the **excluded** VAT shipping price would have to be 6,75 / 1,21 = 5,5785
- **DE** has **19%** VAT, so the **excluded** VAT shipping price would have to be 6,75 / 1,19 = 5,6723
- outside the **EU** is with **0%** VAT, so the **excluded** VAT shipping price would have to be 6,75 / 1,00 = 6,7500
- etc

*I think this can only be implemented correctly when there will be a setting introduced that let you allow to insert the shipping price **including** VAT so some new functions in the background can then do their magic to get hold of the right **excluding** VAT shipping price.*

or

*Just add a new hook (or how it's called), which can be used in the Shipping Costs field so you can do: 6,75 / [highest_applied_tax_rate]*

**Comment by alpha-pix** [comment]
Hi @stgoos,

> What I would love to be able to do is to insert the shipping price included VAT and that it then gets translated to an excluded VAT price depending on the applied tax category (for the shipping address / country).

Very much so. The practical reason is that that I'd like the shipping cost to customers to remain constant, irrespective of the tax status of the products. Flat shipping cost is simpler for customers to understand. I choose my flat shipping cost based more on what customers will pay than what it costs, so if I'm subsidising shipping a little less when selling untaxed products, then that is good. 

Conversely, I'm sure there are plenty of stores that charge shipping at cost, so they would want to add the specific tax to that, resulting in a variable final cost.

So the kind of options I'd like for shipping cost would be either:
a) Shipping cost stated Exclusive of tax with constant net proceeds
b) Shipping cost stated Inclusive of tax with variable net proceeds

and either
a) Tax percentage determined by average tax value in the basket
b) Tax percentage determined by whatever other method(s) people want

**Comment by daigo75** [comment]
@alpha-pix @stgoos The code snippet I published a while ago is an attempt to do exactly what you described: https://pastebin.com/jifVtqFQ. It uses a "trick" to adjust the shipping cost, exclusive of tax, so that the value inclusive of tax is the initial one.

I can't say if it can work with the "mixed tax" scenario, but you should be able to check that easily.

**Comment by alpha-pix** [comment]
@daigo75 Thank you! I tested it at the time of my earlier post, and it is really super. Before putting it live, I just need to adjust quite a complex load of shipping costs from ex-tax to inc.-tax. I had understood that it was either/or rather than allowing mixed tax averages, but I will check for that.

**Comment by daigo75** [comment]
@alpha-pix Thanks for the update. I understand that the snippet works. I really didn't think about the "mixed tax" scenario too much, for several reasons. It doesn't affect me directly, I'm not a "tax man" able to test it accurately and I also dislike complicated tax rules that, in my opinion as a guy ignorant on the matter, don't make sense. 😄

**Comment by stgoos** [comment]
@diago75 I already spotted that code as well. Will have something to play/work with between Christmas and Years End :)
Thanks.

**Comment by alpha-pix** [comment]
@daigo75 OK, I have put it live, and it works very well. Customer prices are consistent, which was the main thing for me. I _am_ a tax man (Financial analyst and forensic accountant), so my OCD goes off a bit when things aren't fully and correctly matched, and also when giving the tax authorities any more than they are entitled to. So I am happy to help test if you felt inclined to take it any further :)

But I do agree with the reasoning behind this, as @stgoos said, which is that there would be tax evasion opportunities if the tax liability of shipping did not follow that of the item(s) being shipped. And instinctively it seems fair that way, even if it is a pig to implement.

**Comment by gudsystems** [comment]
Why is this issue closed?

It's can be a real problem for a large part of the userbase.

**Comment by arnaudpfu** [comment]
I had the same problem on a client's site.
He was using a 10% VAT (with a shipping cost of 1€, we had 1,10€).

To solve this problem, I subtracted the VAT amount from the total.
This way, when the tax amount is added, we have a price including VAT.

Here is the snippet :


	// We check that we are currently using the TTC on the store.
	if ( 'yes' === get_option( 'woocommerce_prices_include_tax', 'no' ) ) {
		add_filter( 'woocommerce_shipping_method_add_rate', 'set_shipping_rate_for_inclusive_tax', 20, 3 );
	}

	/**
	 * Change the total by subtracting the amount of taxes to have a TTC price.
	 *
	 * @param WC_Shipping_Rate   $rate
	 * @param mixed              $args
	 * @param WC_Shipping_Method $context
	 * @return WC_Shipping_Rate
	 */
	function set_shipping_rate_for_inclusive_tax( $rate, $args, $context ) {

		$total_cost = $rate->get_cost();

		$taxes      = WC_Tax::get_shipping_tax_rates();
		$tax_rate   = null !== $taxes && null !== $taxes[1] && null !== $taxes[1]['rate'] ? $taxes[1]['rate'] : 0;
		$tax_amount = $total_cost * $tax_rate / 100;

		if ( $total_cost > 0 && $context->is_taxable() ) {
			$total_cost -= $tax_amount;

			if ( $total_cost >= 0 ) {
				$rate->set_cost( $total_cost );
			}
		}

		return $rate;
	}

I hope this helps someone.

**Comment by daigo75** [comment]
@arnaudpfu thanks for your contribution. If you need, you can also find a similar contribution that I posted a while ago: https://github.com/woocommerce/woocommerce/issues/9320#issuecomment-644262317. The logic is slightly different, but it should produce the same result.

**Comment by bakkbone** [comment]
Why is this closed and how is this still not core? Shipping is the **only** thing you can't enter inclusive of tax... In Australia, for example, it is extremely rare for merchants to show or calculate absolutely anything exclusive of tax at a retail level so having to customise via code or recalculate all shipping is onerous.

**Comment by apsjohn** [comment]
@daigo75 @arnaudpfu Can you please help me modify one of your functions to make this calculation instead?
For example if we have 24% vat on a shipping_price which is 4 euros
$rate->set_cost ( 4 / 1.24 );
and set the applicable tax to ( 4 - ( 4 / 1,24 ) )

Cause i am connecting my woocommerce to odoo erp which calculates the taxes on its own which means that with your method, for the 4 euro shipping example,  it gets 3.04 untaxed shipping cost and then it multiplies it by 1.24, resulting in a big inaccuracy!

I tried altering @arnaudpfu code which was a bit more easy for me but didnt get anywhere...

```
if ( 'yes' === get_option( 'woocommerce_prices_include_tax', 'no' ) ) {
	add_filter( 'woocommerce_shipping_method_add_rate', 'set_shipping_rate_for_inclusive_tax', 20, 3 );
}
function set_shipping_rate_for_inclusive_tax( $rate, $args, $context ) {

	$total_cost = $rate->get_cost();

	$taxes      = WC_Tax::get_shipping_tax_rates();
	$tax_rate   = null !== $taxes && null !== $taxes[1] && null !== $taxes[1]['rate'] ? $taxes[1]['rate'] : 0;
	//$tax_amount = $total_cost * $tax_rate / 100;
	$tax_number = 1 + ( $tax_rate / 100 );
	$tax_amount = $total_cost - ($total_cost / $tax_number);
	
	if ( $total_cost > 0 && $context->is_taxable() ) {
		//$total_cost -= $tax_amount;
		$total_cost /= $tax_number;
		$rate->set_taxes( $tax_amount );
		if ( $total_cost >= 0 ) {
			$rate->set_cost( $total_cost );
		}
	}
	return $rate;
}
```


Can you please help me out, because this will help a lot of people i believe with their erp's or even odoo which is widely used!?

**Comment by kaushikasomaiya** [comment]
6596005-zen, any ideas what exactly these limitations are? I could not access the Trello board.

**Comment by RVandenbussche** [comment]
Here we are in mid-2023, still not in core.

**Comment by anthonysbr** [comment]
What I did was disable the tax calculations, as I introduce the prices including taxes. Then calculate the taxes based on the total.

add_action('woocommerce_cart_totals_before_order_total', 'add_vat_row_to_cart_totals');
add_action('woocommerce_review_order_before_order_total', 'add_vat_row_to_checkout_totals');

function add_vat_row_to_cart_totals() {
    calculate_and_display_vat();
}

function add_vat_row_to_checkout_totals() {
    calculate_and_display_vat();
}

function calculate_and_display_vat() {
   
    $cart_subtotal_ex_tax = WC()->cart->subtotal_ex_tax; // Subtotal excluding taxes
    $shipping_total = WC()->cart->shipping_total; // Total shipping cost

    
    $total_amount_before_taxes = $cart_subtotal_ex_tax + $shipping_total; // Total amount before taxes

    
    $vat_rate = 0.19; // VAT amount 19%
    $vat_amount = $total_amount_before_taxes * $vat_rate;

    ?>
    <tr class="order-vat">
        <th><?php _e('MwSt. (19%)', 'entkreis.de'); ?></th>
        <td><?php echo wc_price($vat_amount); ?></td>
    </tr>
    <?php
}

**Comment by hagedigital** [comment]
Waited over 7 years for this to be fixed. Finally my client had enough and swapped to Shopify Plus (which sucks as I was hoping see the full potential of HPOS as they started to process >$1m a month. I guess that's an oops for WooPayments losing that 1.75% + 30c)

Even viewing orders in the backend and each line item has seperate amounts for the product and GST instead of a total amount is super frustrating. Imagine if it was the other way around for the US, forced to see all of their prices inclusive of tax, and they had no options to configure it correctly? 

A great example of platforms that handle Australian GST correctly 1) Shopify handle Australia product and shipping prices correctly on the backend/frontend (including shipping).  2) MedusaJS which is a new to the open source market has also successfully addressed this

**Comment by kloon** [comment]
@hagedigital, sorry to hear this. A somewhat workaround could be to define your shipping costs, not to include taxes. There are two ways to go about this:
1. In your tax settings, ensure you have the shipping option unchecked next to the tax rates
![0Jpbkq.png](https://github.com/woocommerce/woocommerce/assets/271630/58ff5c7a-d3a4-4535-90ec-7a29a25e791c)
2. If your shipping method supports it, e.g. Flat Rate, select the `None` under tax status.
![DPyGJN.png](https://github.com/woocommerce/woocommerce/assets/271630/67d13f83-2e31-448c-903a-1ae7f3570d1c)

The only downside to using these methods is that the inclusive tax amount displayed on the cart and checkout would exclude shipping from the taxes being backwards calculated and displayed.

**Comment by hagedigital** [comment]
GST in Australia is 10% of the total, including shipping. Using this method will show the incorrect amount.

**Comment by HonzaKopecky** [comment]
Let me add my vote here. In the Czech republic we are actually bound by law to display prices including VAT (so the customer is aware to see the complete price) and customers are used to the fact that the prices including VAT are rounded to have no decimal part. 

You can imagine that configuring the price excluding VAT can be quite challenging since our VAT is now 21% and thus in some cases the shipping cost excl. VAT must have 3 or more decimal digits to land as an integer (incl. VAT).

What I would like to stress the most is that this behaviour is **very confusing** in the first place! For people who are not WC experts it must be quite complicated to understand & remember that they can set literally all prices incl. VAT just with the sole exception for shipping!.

I indeed hope this gets reopened.

**Comment by dabesa** [comment]
+1 vote, it's annoying to show different shipping cost price depending on the customer country and VAT

**Comment by KPYahoo** [comment]
@mikejolley @vedanshujain Why is this issue status still closed?
