### ISSUE TITLE
Regression from 2.4.6 to 2.4.7 - prices being displayed exclusive of tax

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#9321]
On single product pages within a shop I'm currently working on (https://www.simbahosting.co.uk/s3/shop), the price immediately at the top is being displayed exclusive of taxes, even though the "Display prices in the shop:" setting is set to "Including tax".

Screenshot from WC 2.4.7: http://snag.gy/ChInb.jpg
I rolled back to WC 2.4.6, and it corrected itself; screenshot: http://snag.gy/BVvD0.jpg

This is a variable product. The price further down the page (above the "Add to Cart" button) is always behaving correctly (i.e. inclusive of tax). I have a multi-currency plugin, but de-activated this for testing purposes - no difference in the result (and it happens in every currency if it is activated).

I then rolled back and forth a few times, doing nothing except unzipping the 2.4.6 or 2.4.7 files and hitting "Reload" in the web browser. It's always doing the wrong thing in 2.4.7, and always right in 2.4.6.

**Comment by DavidAnderson684** [comment]
I forgot to mention: the theme I'm using has no WooCommerce templates. (To make doubly sure, I also added some PHP code in the variable product method get_price_html() to print a backtrace, to verify that it is using the default WC templates).

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/5da98ce7827378c8cd90290810de49b7760d3aec

**Comment by DavidAnderson684** [comment]
Thanks. The problem must be more subtle than Diego's comment says, as this was a case where it's getting a wrong price (varying on tax included/excluded), not just on $display. But, I can confirm that the fix fixes it in my case.
