### ISSUE TITLE
Unable to process refunds via Simplify Commerce on Subscription renewal orders

### ISSUE THREAD

**Issue by jeffro84** [woothemes/woocommerce#9325]
When a subscription order comes up for renewal, a renewal order is created and the credit card is charged.  However, the renewal order is charged against the ORIGINAL order ID, not the renewal order ID.  So when you try to process a refund on a renewal order, it fails and says "An invalid payment ID was specified" because it tried to use the renewal ID, which obviously doesn't match anything since the original ID was re-used for the actual payment.

I'm not sure which is the proper way to fix this, but it seems like charging against the renewal order ID would solve the problem.

**Comment by claudiosmweb** [comment]
You need to update to WooCommerce Subscriptions 2.0.
https://docs.woothemes.com/document/subscriptions/version-2/#section-7
