### ISSUE TITLE
Manual product price change not reflecting in emails or My Account

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#9328]
To replicate:

1. Create an order manually and add a free product to that order.
2. Calculate the totals, and then save the order.
3. Look at the sent email, and notice the price change is not reflected.
4. Look at the order in the My Account section and notice the same issue.

Order: http://cld.wthms.co/rekp/4GvK0q1v
Email: http://cld.wthms.co/NS8f/Yz6Fi2go
My Account: http://cld.wthms.co/fBCw/9P8WoloH

Those two locations are likely just pulling the products price, but is there something that could be done to reflect the manual price change?

**Comment by mikejolley** [comment]
Misusing the totals. One if before discount, one is after discount. Edit the other total on the line item (you shouldn't see 0 striped out after changing price).
