### ISSUE TITLE
Settings API: Notice when saving an Array

### ISSUE THREAD

**Issue by Biont** [woothemes/woocommerce#9329]
I have created a couple of settings fields using the WC Settings API. Some of these fields are submitting an Array instead of a plain string (using square brackets in input names like so: ```name="foo[bar]"```)

For all custom fields (with an unknown ```'type'```), ```WC_Admin_Settings::save_fields()``` [will run the ```$raw_value``` through ```wc_clean()```](https://github.com/woothemes/woocommerce/blob/090de0c6a7d8357410c9b228dec1db6f93e81b25/includes/admin/class-wc-admin-settings.php#L705), which in turn [assumes the input is a string](https://github.com/woothemes/woocommerce/blob/090de0c6a7d8357410c9b228dec1db6f93e81b25/includes/wc-formatting-functions.php#L252-L254).

This results in the following notice:

```
    Notice: Array to string conversion in (...)\wp-includes\formatting.php on line 957
```

My current workaround is not using the ```$option['id']``` as the input name and thus sidestep this part of the Settings API by using my own set of identifiers and returning the proper value in the sanitize callback. This is not ideal and could be easily avoided if the Settings API wasn't assuming that all input is a string.

I would propose not using ```wc_clean()``` if the ```$raw_value``` is an array.

**Comment by mikejolley** [comment]
wc_clean could support array. Ill submit a fix.
