### ISSUE TITLE
PayPal standard and refunding VAT only

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#9334]
Scenario (seen earlier today):

1) Customer in a VAT-exempt special region of an EU country purchases digital goods. He got charged VAT (because of his country - he didn't have a VAT number, so couldn't get exempted via a VAT number. In regions where there is no VAT, they don't need VAT numbers!).

2) He then got refunded the VAT, only, through the WooCommerce dashboard (i.e. go to WooCommerce -> Orders -> (specific order), press "Refunds", then enter something in the "VAT" tax column, whilst leaving the full product price at zero - then press 'Refund via PayPal').

This refunds him. However, in PayPal, it shows as a refund solely off the main product amount, and not off the VAT. And as such, when you download transaction info as a CSV from PayPal (History -> Download History), both the "VAT" column in the CSV and the product amount column have bogus data in them, and so the accounts don't reconcile.

Whilst this is a specific scenario (customer in VAT-exempt region), there could be other similar scenarios where the shop wants to refund VAT only, and to have its PayPal account/history still reconcile.

This page for the NVP API suggests that it supports specifying the refund amount across tax and shipping: https://developer.paypal.com/docs/classic/api/merchant/RefundTransaction_API_Operation_NVP/ . I haven't actually checked which API WC uses, but I felt hopeful that if one of them supports it, then perhaps the one in use does too...?

**Comment by mikejolley** [comment]
This API doc isn't clear. You must use the AMT field for a partial refund regardless. It's also not linked to a line item, so I'm failing to see how TAXAMT will help.

**Comment by DavidAnderson684** [comment]
I see what you mean. Looks awkward.

Not being able to refund via PayPal's API in a way that has PayPal CSV downloads not have false accounting information in them about net VAT collected really sucks. Do Woo have the clout / access to someone in PayPal who can bang heads together on this sort of thing? Basic tax accounting is sort of thing that it feels wrong to have to keep on Post-It notes when reconciliation time comes around.

**Comment by mikejolley** [comment]
@DavidAnderson684 what is the advantage of using PayPal reporting vs WC reporting?

**Comment by DavidAnderson684** [comment]
I use the PayPal CSV history download quite often (and similarly for other payment processors). A spreadsheet of all order information is hugely useful... off the top of my head, I use it to 1) gather figures for my accountant, 2) to reconcile accounts (especially useful when tracking down the inevitable various irritating discrepancies in end-of-quarter/year reports), and 3) gather figures for commission payments (which are paid on the pre-VAT total, after refunds - but I must have been doing these wrongly, because I only just realised the issue). I've done each of those in the last couple of months.

And, of course, reconciling what happened to the PayPal balance is awkward if PayPal's spreadsheets have things in the wrong columns.

I've purchased a CSV export extension for WooCommerce in the past (a SkyVerge one - not sure if that's the official one or not, OTTOMH); but it was really slow once if I asked it to do anything complex (I monitored the SQL queries - many things I asked it to do were O(n) in terms of the number of SQL queries they ran, where n is the number of orders involved - you could watch the queries roll by, one by one - not fun with thousands of orders...), buggy, prone to running out of time or memory and hence needed to be run in batches on large stores and the results stitched manually together. (There was a security issue too, but I alerted the order and he fixed it). Wrestling with it and reporting and following up issues was a big unproductive sink-hole for my time; I stopped using it after trying for a couple of months and discerning that the O(n) problems weren't likely to go away for a loong time.

Obviously, it's PayPal's fault if PayPal's APIs suck. But I'm supposing that if Woo don't have the clout to say "Oy! PayPal! This needs sorting!" then nobody does.

**Comment by maxrice** [comment]
>I've purchased a CSV export extension for WooCommerce in the past

Instantiating new `WC_Order` objects doesn't produce the nicest or most efficient SQL queries and tends to take up quite a bit of memory, especially for thousands or tens of thousands of orders :person_frowning: We're aware of the that limitation and there's the limit/offset feature that can be used as a workaround right now, and we're working on an update that'll batch process the export via Ajax to avoid both the timeout issues and memory exhaustion problems :smile_cat:

**Comment by DavidAnderson684** [comment]
My view was that even if I could whip up some script to help automatically batch it, then the O(n) SQL query numbers would still be there, and they were the really fatal defect. Regardless of whether batching needed manual help or not, it still involved locking up one CPU core on their webserver for the PHP, and a second CPU core on the database server, for hours, to produce a sales report. :-( In my view, for the concept to work on big stores, it needs lots of hand-made SQL, based on knowledge of the table structures, instead of using WC_Order... which feels ugly, of course, but ugly-and-works-without-melting-everything also has its plus side! ;-) That's all drifting off topic for this issue, of course - just my 2c based on the experience...

**Comment by mikejolley** [comment]
@DavidAnderson684 If you set TAXAMT to the same value as AMT here https://github.com/woothemes/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-refund.php#L40 and do the refund in your test case above, how does your report look? Do you refund both amounts, or does the TAX just get reported correctly?

**Comment by mikejolley** [comment]
@DavidAnderson684 interestingly you cannot even do what you're asking via PayPal's UI 
![2015-10-28 at 09 44](https://cloud.githubusercontent.com/assets/90977/10784921/9ea6bd90-7d58-11e5-9548-d8b8f65ea253.png)

**Comment by mikejolley** [comment]
And sending the tax amt in the refund request does nothing PayPal side - does not look like this one is possible.

**Comment by DavidAnderson684** [comment]
But don't Woo, with ~25% of the e-commerce market, have enough clout to speak to PayPal about what's wrong with their API?

**Comment by mikejolley** [comment]
It could be bought up (@BFTrick?), but its not something we're going to be able to fix until then. I also envision this to be technically complex - you'd have to resend the entire order for it to calculate correctly.

**Comment by BFTrick** [comment]
Reached out to PP to see if there's anything we missed or if there's an undocumented feature in the API. I'm going to assume if they don't have it in their UI it's not possible but we might as well be thorough and check.

This might be a `wontfix` item because resending orders to PP is a really big workaround. For tax purposes we may recommend telling users to use WC reporting.

**Comment by BFTrick** [comment]
We had a discussion with PayPal and the only way to refund a customer any amount is to use the interface above. WooCommerce has more granular tax / refund functionality (where you can refund tax separately from total price) so for the most accurate reports you should use WooCommerce.

**Comment by DavidAnderson684** [comment]
Thanks for trying! It's amazing that PayPal have got to 2015 with any interface for something so simple as refunding tax. But it seems we're stuck with it!
