### ISSUE TITLE
Variable Product Dropdown Issue in IE11

### ISSUE THREAD

**Issue by rspublishing** [woothemes/woocommerce#9335]
When selecting the dropdown on a variable product in IE (lets say the color), it opens fine with the initial click. However, when wanting the change the color and you select the dropdown again, you have to click twice before the dropdown appears. This doesn't happen in other browsers.

I used WordPress 4.3.1, WooCommerce 2.4.7 and could replicate the issue using several different themes (Mystile, Storefront, Twenty Fifteen, and Twenety Fourteen) on IE11.

The issue can be replicated by following these steps: 

1. Load IE11
2. Visit [http://demo2.woothemes.com/forthecause/product/ship-your-idea/](http://demo2.woothemes.com/forthecause/product/ship-your-idea/)
3. Select the color drop down option

What happens:

- First click = the dropdown is displayed as it should

Then click away for a second, then come back and try change the color:

- The drop down is highlighted on first click
- The second click displays the drop down

Ticket in question: #342506

**Comment by jameskoster** [comment]
Seems to be an issue with how we dynamically create the `option`s every time the user interacts with these `select`s. 

Chat about it this week @claudiosmweb? :-)

**Comment by claudiosmweb** [comment]
@jameskoster yes, of course :)

**Comment by mikejolley** [comment]
@jameskoster what did you decide?

**Comment by jameskoster** [comment]
@mikejolley The javascript needs looking at. The options are generated dynamically, but not quick enough for IE. On first click there are no options which is why the dropdown doesn't open. Let's debug next week?

**Comment by chetansatasiya** [comment]
@jameskoster I have applied the changes for issue and push code for review. Please check for the same because I think you no need to focus when selecting the variations for the product. I have tried with all the browser and all the devices it's working fine for me. Let me know your thoughts for the same.

**Comment by jameskoster** [comment]
@chetansatasiya doing this means some of the `options` aren't visible on page load though.

**Comment by chetansatasiya** [comment]
@jameskoster Can you please tell which options are not showing I have tried using 10 options in the select box but all the options coming properly.

**Comment by jameskoster** [comment]
Try setting a default variation. Video evidence; https://cloudup.com/cQQXh5YpWxS

**Comment by nishitlangaliya** [comment]
@jameskoster, Actually setting up a default variation didn't worked for me but the changes ref #25783e3 worked fine. please check for the same and let me know your thoughts.

**Comment by nishitlangaliya** [comment]
@jameskoster , I have done the PR for the same https://github.com/woothemes/woocommerce/pull/9431 please review it when you get a chance.

**Comment by nishitlangaliya** [comment]
@mikejolley, setting up default variation for first options worked. please review  67f3e0b commit for the same.

**Comment by jameskoster** [comment]
@nishitlangaliya this just sets the first option as selected... that might not be the one that was chosen as the default...

**Comment by nishitlangaliya** [comment]
@jameskoster Thanks for the reply, Do you mean that if the user has selected the default option then it  should show as chosen otherwise first one ?

**Comment by nishitlangaliya** [comment]
@jameskoster, I just tested with default option selected and if the default variations set then selected option comes selected and its working fine. :)

**Comment by nishitlangaliya** [comment]
@jameskoster,  any update ?

**Comment by jameskoster** [comment]
Did you want me to test @claudiosmweb ?

**Comment by mikejolley** [comment]
@jameskoster yes please do

**Comment by claudiosmweb** [comment]
@jameskoster please :)

**Comment by jameskoster** [comment]
@claudiosmweb it's not cool :(

Works fine if a default is set. But with no default it still requires a double click.

**Comment by claudiosmweb** [comment]
I'll check it again ;)

**Comment by jameskoster** [comment]
@claudiosmweb let me know when to test

**Comment by claudiosmweb** [comment]
@rspublishing seems to be working fine. Can you test for us?

**Comment by jameskoster** [comment]
Spoke about this on Slack. Closing, we can re-open during beta if it arises again.
