### ISSUE TITLE
How to properly display tax in the checkout page?

### ISSUE THREAD

**Issue by wsenjer** [woothemes/woocommerce#9337]
I'm building A Woocommerce plugin for Australia Post. Please take a look at this checkout screenshot.

![uk3uw](https://cloud.githubusercontent.com/assets/132250/10410277/84e8506a-6f45-11e5-9c4e-2f35213c69b9.png)

added standard tax rate of 10%. And as you see in the totals, There are $4.00 as a tax. and that correct for the items of the cart. But it should calculate the 10% of the shipping cost too. The shipping rate that I received from Australia Post API is already taxed with 10% too.

So the total tax should be $5.455 not $4.00

This is how I add the shipping rate

    <?php 
                $this->add_rate(array(
                            'id' => 'australia_post',
                            'label' => 'Australia Post',
                            'cost' => $cost_from_api,
                            ));  

How can I fix that?

**Comment by nishitlangaliya** [comment]
@wsenjer, Can you please confirm does your woocommerce shipping settings are set to taxable or not ? like below screenshot.

![issue-9337](https://cloud.githubusercontent.com/assets/11435772/10410449/b053bfae-6f5f-11e5-97c6-1823a203438d.png)

**Comment by wsenjer** [comment]
Yes, it's set to taxable. Anyway, I removed this field from the settings of the shipping method because the prices of Australia Post are ALWAYS taxable.

**Comment by wsenjer** [comment]
Any advice please?

**Comment by mikejolley** [comment]
To have the taxes shown in WC for this method you need to;

a) make sure aus post is taxable
b) make sure the 'shipping' checkbox is set when declaring your tax rates.

In your plugin, take the 10% off. Shipping rates need to be defined excl. tax.
