### ISSUE TITLE
woocommerce Order API bug

### ISSUE THREAD

**Issue by tkchuah** [woothemes/woocommerce#9338]
$item_args['variation']`  is set at class-wc-api-orders.php line 913 but then the array is cleared at line 934. This is causing variation product order not able to be captured correctly

Commenting out line 934 seems to solve the isseu

thanks

**Comment by WPprodigy** [comment]
Possibly related: https://github.com/woothemes/woocommerce/issues/9300 ?

**Comment by tkchuah** [comment]
Yes it is. Please fix it. The way how #9300 is handled is extremely unprofessional.
