### ISSUE TITLE
Remove brackets around post count in Layered Nav widget.

### ISSUE THREAD

**Issue by xrelaxerx** [woothemes/woocommerce#9339]
I want to remove brackets around posts count and move its parent span inside sibling link element. I can customise post count output of product categories widget by filtering `wp_list_categories`, but how do I customise post count output of layered nav widget?

Basically how to change this:
```
<li><a href="#">Preforms</a> <span class="count">(27)</span></li>
```
To this:
```
<li><a href="#">Preforms <span class="count">27</span></a></li>
```
without modifying core files.

**Comment by roykho** [comment]
This is not a place for support.  Please read support section here https://github.com/woothemes/woocommerce
