### ISSUE TITLE
Address field in Shipping Calculator

### ISSUE THREAD

**Issue by mahype** [woothemes/woocommerce#9340]
Hello together,

at the moment I am programming the shipcloud Shipment Gateway. Therefor I need not only Postcode, City and Country, I also need the Address to calculate the Shipping.

I have added at first a filter to 'woocommerce_shipping_calculator_enable_city' and set it true. But to add the address field, i had to do a bit dirty code. I hace also added the code for the form to the filter.

```php
public static function add_calculate_shipping_form_fields( $woocommerce_shipping_calculator_enable_city )
{
	$woocommerce_shipping_calculator_enable_city = TRUE;
	?>
	<p class="form-row form-row-wide" id="calc_shipping_city_field">
		<input type="text" class="input-text" value="<?php echo esc_attr( WC()->customer->get_shipping_address() ); ?>" placeholder="<?php esc_attr_e( 'Address', 'woocommerce' ); ?>" name="calc_shipping_address" id="calc_shipping_address" />
	</p>
	<?php
	return $woocommerce_shipping_calculator_enable_city;
}
```
I would ask you if you could add the address field also to the code like the city field. Annother solution would be to have an do_action before the fields.

If you would agree, I also can give you a pull Request with the complete code you need for this.

Greetings,

Sven

**Comment by mikejolley** [comment]
Hi Sven

If it requires a full address, I don't think this quote box is suitable. You may want to consider disabling it and having the checkout form calc shipping only. 

Could also add a before/after hook around here if you want to do a PR, https://github.com/woothemes/woocommerce/blob/master/templates/cart/shipping-calculator.php#L35
