### ISSUE TITLE
[REST] Custom Product Price on Create Order

### ISSUE THREAD

**Issue by dammionx** [woothemes/woocommerce#9341]
Hello..

I develop a stand-alone php web application that connect to woocommerce using the REST API, but i got a little trouble here, i read about the documentation but i cant find how to apply custom price for products.

I mean like this, lets say i develop a point of sale application, and then i search for item with name "A" , then i add it into the point of sale, what i looking for is, i change the "A" price only for this order without affecting the real item data..

Is that possible ? 

Thankyou

**Comment by mikejolley** [comment]
PUT requests in the API for products are permanent. You would have to modify the order line items to change on a per-order basis.

**Comment by yahyaoffroad** [comment]
can you send me an example of this i want to update  product price during create order
