### ISSUE TITLE
Variable Product Submissions constantly throw "Please choose product options"

### ISSUE THREAD

**Issue by kylehotchkiss** [woothemes/woocommerce#9344]
I've done my research - no JS errors, all JS loading as expected.
No customized template code. Not live (just doing this locally for now).

Added a simple 3-variant setup for a product.

Checked network inspector to see the data flowing out of the "add to cart" request, and got this:

```
------WebKitFormBoundaryzT4T6nTeNm96gcxd
Content-Disposition: form-data; name="attribute_size"

small
------WebKitFormBoundaryzT4T6nTeNm96gcxd
Content-Disposition: form-data; name="quantity"

1
------WebKitFormBoundaryzT4T6nTeNm96gcxd
Content-Disposition: form-data; name="add-to-cart"

1720
------WebKitFormBoundaryzT4T6nTeNm96gcxd
Content-Disposition: form-data; name="product_id"

1720
------WebKitFormBoundaryzT4T6nTeNm96gcxd
Content-Disposition: form-data; name="variation_id"


------WebKitFormBoundaryzT4T6nTeNm96gcxd--
```

Looks like `variation_id` isn't setting for me - any quick fix to set that? Seems to be the issue.

- - - - 

Debug info:

### WordPress Environment ###

Home URL: http://sitename.dev
Site URL: http://sitename.dev
WC Version: 2.4.7
Log Directory Writable: ✕ To allow logging
make /Sites/sitename.dev/wordpress/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Unix) PHP/5.5.27
PHP Version: 5.5.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.41
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.7
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (7) ###

Gravity Forms: by rocketgenius – 1.9.1.2
Advanced Custom Fields: Gravity Forms Field: by @adam_pope of @stormuk – 1.0.0
Advanced Custom Fields Pro: by elliot condon – 5.3.0
Amazon Web Services: by Delicious Brains – 0.3.2
Timber: by Jared Novack + Upstatement – 0.21.10
WooCommerce: by WooThemes – 2.4.7
Yoast SEO: by Team Yoast – 2.3.5

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #1716 - /shop
Cart: #1717 - /cart
Checkout: #1718 - /checkout
My Account: #1719 - /my-account

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Site Name
Version: 4.0
Author URL: http://www.kylehotchkiss.com/
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: sitename/woocommerce/single-product/add-to-cart/external.php
sitename/woocommerce/single-product/add-to-cart/grouped.php
sitename/woocommerce/single-product/add-to-cart/simple.php
sitename/woocommerce/single-product/add-to-cart/variable.php
sitename/woocommerce/single-product/meta.php
sitename/woocommerce/single-product/price.php
sitename/woocommerce/single-product/product-attributes.php
sitename/woocommerce/single-product/product-image.php
sitename/woocommerce/single-product/product-thumbnails.php
sitename/woocommerce/single-product/rating.php
sitename/woocommerce/single-product/related.php
sitename/woocommerce/single-product/review.php
sitename/woocommerce/single-product/sale-flash.php
sitename/woocommerce/single-product/share.php
sitename/woocommerce/single-product/short-description.php
sitename/woocommerce/single-product/tabs/additional-information.php
sitename/woocommerce/single-product/tabs/description.php
sitename/woocommerce/single-product/tabs/tabs.php
sitename/woocommerce/single-product/title.php
sitename/woocommerce/single-product/up-sells.php

**Comment by mikejolley** [comment]
> No customized template code. 

And yet the report has:

> sitename/woocommerce/single-product/add-to-cart/variable.php

So this is likely your issue.
