### ISSUE TITLE
STOP alerting theme users for little changes..

### ISSUE THREAD

**Issue by unsalkorkmaz** [woothemes/woocommerce#9347]
Hi,
I am trying my best to keep WooCommerce support for my theme but with little changes, you are alerting them like their site is broken now.

An example;
in 2.4.7 update, **templates/checkout/payment.php** file got only removed `<div class="clear"></div>` and it gives alert like their payment broken now.

Stop it. Please. Just alert for important changes.

**Comment by jameskoster** [comment]
The alert simply says the template file is out of date. It doesn't explicitly say it is broken. You should be checking your theme against WooCommerce updates anyway.

**Comment by unsalkorkmaz** [comment]
Well.. A large alert that shows in top of admin panel after every minor update is just unfriendly for developers. You shouldnt directly close this topic in my opinion.

**Comment by jameskoster** [comment]
If you update your theme the alert goes away.
