### ISSUE TITLE
Hebrew characters in all emails from woocommerce display as "????????"

### ISSUE THREAD

**Issue by batz-bar** [woothemes/woocommerce#9348]
Using latest version of woocommerce 2.4.7
Problem is with all emails from Woo (image "broken" attached).
If  line 459 in woocommerce/includes/emails/class-wc-email.php is commented
```
//$message = apply_filters( 'woocommerce_mail_content', $this->style_inline( $message ) );
```
So the Hebrew is fine (image "fixed" attached), but no design to emails.
Fault occurs even on a clean installation with no other plugins installed on basic WP theme (like twenty-fifteen).
This is a bug for above a year ,Don't know the the exact version number (Every update i comment the line again to fix it).

![broken](https://cloud.githubusercontent.com/assets/11011901/10434817/c876e508-70e9-11e5-95de-b02c9fb35ab3.png)
![fixed](https://cloud.githubusercontent.com/assets/11011901/10434852/061b3ab2-70ea-11e5-8ea3-df4ba52a7185.png)

Debug info:

### WordPress Environment ###

WC Version: 2.4.7

WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: he_IL

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.4.40
PHP Post Max Size: 20 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.45
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Your server does not have the SOAP Client class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.7
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (14) ###

מערכת רדוקס: על ידי Team Redux – 3.5.7
CMB2: על ידי WebDevStudios – 2.1.2
CodeStyling Localization: על ידי הייקו רבי – 1.99.30
Contact Form DB: על ידי Michael Simpson – 2.9.10
Contact Form 7: על ידי Takayuki Miyoshi – 4.3
Duplicator: על ידי LifeInTheGrid – 0.5.32
oEmbed API: על ידי פסקל בירצ'לר – 0.9.0-20151002
OW Bootstrap: על ידי Onistaweb.com – 1.0
Master Toolkit: על ידי Onista Web – 1.0
Prism Syntax Highlighter for WordPress: על ידי Nicolas Jonas – 1.0.1
WooCommerce - Name your own price: על ידי Sean Voss – 1.7
WooCommerce: על ידי WooThemes – 2.4.7
ייבוא מוורדפרס: על ידי wordpressdotorg – 0.6.1
WP Lightbox 2: על ידי Syed Balkhi – 3.0.5

### Settings ###

Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

מאגר החנות: #373 - /shop/
עגלה: #374 - /cart/
קופה: #375 - /%d7%a7%d7%95%d7%a4%d7%94/
החשבון שלי: #376 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Master Portfolio WordPress Child Theme
Version: 1.0
Author URL: http://www.qodepixel.com/
Child Theme: ✔
Parent Theme Name: Master
Parent Theme Version: 1.1
Parent Theme Author URL: http://qodepixel.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Please look at other installed plugins/the theme - I tested hebrew and did not experience the issue. Also check your mail client supports utf. Emails are sent in UTF8 so should be fine.

**Comment by mikejolley** [comment]
Closing due to lack of feedback.

**Comment by einavha** [comment]
I have the same issue - and the suggested fix it.

**Comment by eladfeinberg** [comment]
Seems that on class-emogrifier.php (file can be found in woocommerce/includes/libraries/class-emogrifier.php) you should remove in line #530 the utf8_decode, that will solve the issue...

**Comment by batz-bar** [comment]
Turned out he problem was because mbstring extension was not installed on server.  Once it was installed problem was solved.
Hope this will help others that has same issue.

**Comment by ytwebdesigns** [comment]
I had the same issue and removing the utf8_decode in class-emogrifier.php as mentioned above worked for me
Thanks Elad

**Comment by batz-bar** [comment]
@ytwebdesigns 
The problem with commenting a line, next update you will need to do again. 
Connect hosting and ask to install mbstring  php extension, hopefully Hebrew will be fine  in emails without comment the line.  
That how i solved after a few months of every update commenting that line.
