### ISSUE TITLE
Customer name enumeration for all users stored as authors

### ISSUE THREAD

**Issue by themetric** [woothemes/woocommerce#9349]
User enumeration (info leakage) is a known problem in Wordpress.  Appending `?author=1` (or any ID) reveals the name and nickname of the Wordpress author / user.  This info leak can be prevented in Wordpress with some changes, but it's even more of a concern with Woocommerce as those names are customer names and all of them can easily be enumerated.  

Protecting the names of customers should be a default in Woocommerce or at the minimum be added to a list of security enhancements or suggestions for Woocommerce users.

**Comment by Kenshino** [comment]
In short, usernames are not secret and should not be considered as part of your security procedure. Amazon and other e-commerce giants / service providers use your email as login, and your email is not a secret. 

See http://halfelf.org/2014/username-secret/ for long explanation

**Comment by mikejolley** [comment]
^ that. Usernames are not secret.
