### ISSUE TITLE
[FEATURE REQUEST] custom port numbers with web hook delivery urls

### ISSUE THREAD

**Issue by achadee** [woothemes/woocommerce#9350]
Hi all,

Ive noticed that Woo does not support web hook delivery URL's with port numbers. Can we fix this?
Ill fork it when i get the chance, but I'm a bit too busy atm

Thanks,

**Comment by claudiosmweb** [comment]
Because it's not a safe url. We use `wp_safe_remote_request()` and it uses https://developer.wordpress.org/reference/functions/wp_http_validate_url/ to test for safe urls.

You can filter it: https://developer.wordpress.org/reference/hooks/http_request_reject_unsafe_urls/

**Comment by achadee** [comment]
ah cool, thanks for the clarification
