### ISSUE TITLE
Media query instead of media type in link tag

### ISSUE THREAD

**Issue by szepeviktor** [woothemes/woocommerce#9352]
Although [it is valid HTML](http://www.w3.org/TR/html5/document-metadata.html#attr-link-media) WordPress expects [media type](https://codex.wordpress.org/Function_Reference/wp_enqueue_style) in wp_enqueue_style/wp_register_style.

```css
<link rel='stylesheet' id='woocommerce-smallscreen-css'  
href='//subtwo.wp/static/plugins/woocommerce/assets/css/woocommerce-smallscreen.css?ver=2.4.7' 
type='text/css' media='only screen and (max-width: 768px)' />
```
Please consider using only media type.

Use case: W3 Total Cache merges small screen and desktop CSS files.

*I know it is a caching consideration to use media query here.*

**Comment by jameskoster** [comment]
Not really sure what you're asking us to do here?

**Comment by szepeviktor** [comment]
Could you go `media="screen"` ?

**Comment by claudiosmweb** [comment]
Feel free to use our `woocommerce_enqueue_styles` filter.

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-frontend-scripts.php#L54

But this is valid HTML and displays to be read only by small screens.

Here for your reference: http://www.w3.org/TR/css3-mediaqueries/

**Comment by szepeviktor** [comment]
Thank you.
I do understand that the output is valid HTML but WordPress code lacks the feature of media queries. Only media type is allowed in `media`.

For googlers:

1. You exclude woocommerce-smallscreen.css from minification/combining

2. Replace it in the above filter with
```css
@import('woocommerce-smallscreen.css');
```

**Comment by claudiosmweb** [comment]
WordPress accept any media queries, however it seems that the docs needs some update.
See how the class responsible for this:

https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/class.wp-styles.php#L0

**Comment by szepeviktor** [comment]
Yes.
Please pay attention that all plugins are written based on the docs.
For example W3 Total Cache.

**Comment by claudiosmweb** [comment]
@szepeviktor this is a W3 Total Cache issue, not a WooCommerce or WordPress issue.

**Comment by claudiosmweb** [comment]
But, I'll update the docs for you @szepeviktor ;)
Since anyone can update the WordPress docs.

**Comment by szepeviktor** [comment]
I think W3TC is core conformant.

**Comment by claudiosmweb** [comment]
@szepeviktor good luck!
