### ISSUE TITLE
Variation creation attribute sorting issue

### ISSUE THREAD

**Issue by partounian** [woothemes/woocommerce#9354]
When creating variations for a variable products, the options are ordered alphanumerically rather than following the actual order of the terms per attribute.

**Comment by mikejolley** [comment]
Attributes are not ordered by the order of variations in the backend. Drag drop terms to sort via Products > Attributes

**Comment by partounian** [comment]
Here's an example.  
![screen shot 2015-10-15 at 5 02 03 pm](https://cloud.githubusercontent.com/assets/2541595/10530728/5d834412-735f-11e5-9889-5449d4051da8.png)
![screen shot 2015-10-15 at 5 02 44 pm](https://cloud.githubusercontent.com/assets/2541595/10530730/5d84ea42-735f-11e5-94d9-77e440e2af55.png)
![screen shot 2015-10-15 at 5 03 22 pm](https://cloud.githubusercontent.com/assets/2541595/10530727/5d828b4e-735f-11e5-81a4-e13cffe6b6e9.png)
![screen shot 2015-10-15 at 5 04 10 pm](https://cloud.githubusercontent.com/assets/2541595/10530729/5d842c1a-735f-11e5-8d5e-2446f697d401.png)
![screen shot 2015-10-15 at 5 04 18 pm](https://cloud.githubusercontent.com/assets/2541595/10530731/5d85d740-735f-11e5-92d8-955770fbbdec.png)
![screen shot 2015-10-15 at 5 04 24 pm](https://cloud.githubusercontent.com/assets/2541595/10530732/5d869176-735f-11e5-9ecc-d191eb4f38b2.png)
![screen shot 2015-10-15 at 5 04 30 pm](https://cloud.githubusercontent.com/assets/2541595/10530733/5d99a608-735f-11e5-91d0-b320adaac257.png)
![screen shot 2015-10-15 at 5 04 33 pm](https://cloud.githubusercontent.com/assets/2541595/10530734/5d9a26fa-735f-11e5-81fe-ab0b1301e8b9.png)
