### ISSUE TITLE
Issue While Registering New User Via WooCommerce My Account Page

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#9355]
While registering a new user via woocommerce i get the below error

![wc_issue](https://cloud.githubusercontent.com/assets/1884287/10475033/2734c59c-725c-11e5-86d9-a9c2fea6254f.png)

My WC System Report

`
### WordPress Environment ###

Home URL: http://10.0.1.9/iir/sites/sareepuram3.0/site
Site URL: http://10.0.1.9/iir/sites/sareepuram3.0/site
WC Version: 2.4.7
Log Directory Writable: ✔  /opt/lampp/htdocs/iir/sites/sareepuram3.0/site/wp-content/uploads/wc-logs/
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.21 (Unix) DAV/2 mod_ssl/2.2.21 OpenSSL/1.0.0c PHP/5.3.8 mod_apreq2-20090110/2.7.1 mod_perl/2.0.5 Perl/v5.10.1
PHP Version: 5.3.8 - We recommend a minimum PHP version of 5.4. See: How to update your PHP version
PHP Post Max Size: 25 TB
PHP Time Limit: 30
PHP Max Input Vars: 
SUHOSIN Installed: –
MySQL Version: 5.5.16
Max Upload Size: 25 TB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.7
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (14) ###

Nav Menu Roles: by Kathy Darling – 1.7.1
WC Vendors: by WC Vendors – 1.7.9
Woocommerce CSV Import: by Allaerd Mensonides – 3.0.5
Woocommerce Quick Buy: by Varun Sridharan – 0.16
WooCommerce: by WooThemes – 2.4.7
WooThemes Helper: by WooThemes – 1.5.9
WordPress Importer: by wordpressdotorg – 0.6.1
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.88
YITH WooCommerce Ajax Product Filter: by yithemes – 2.4.0
YITH WooCommerce PDF Invoice and Shipping List: by Yithemes – 1.1.5
YITH WooCommerce Quick View: by Yithemes – 1.0.8
YITH WooCommerce Social Login: by Yithemes – 1.0.6
YITH WooCommerce Wishlist: by Yithemes – 2.0.11
YITH WooCommerce Zoom Magnifier: by Yithemes – 1.2.10

### Settings ###

Force SSL: –
Currency: INR (Rs.)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: SareePuram  Child
Version: 1.0.0
Author URL: http://example.com
Child Theme: ✔
Parent Theme Name: Mystile
Parent Theme Version: 1.3.10
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
Tested and works great.
Probably it is being generated by another plugin.
