### ISSUE TITLE
Incorrect Translation function used

### ISSUE THREAD

**Issue by pratikshrestha** [woothemes/woocommerce#9356]
Line 57 in woocommerce/templates/cart/shipping-calculator.php has following code
<code>__( esc_html( $cvalue ), 'woocommerce' ) </code>

Here the value esc_html( $cvalue ) is being passed through translation function. Trying to translate a variable is not correct. It should be only as follows
<code>esc_html( $cvalue ) </code>

**Comment by claudiosmweb** [comment]
This is for WPML.
