### ISSUE TITLE
Authentication Endpoint Callback

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#9357]
Hi,

To create a consumer key and secret for the REST API, I am using this method:

https://woocommerce.wordpress.com/2015/08/07/api-settings-and-the-api-authentication-endpoint-in-2-4/

After authorizing the app, what data is sent back to the call back url? I cannot test on local host, since it's not HTTPS. I opened Fiddler and here is all I could find:

GET https://www.cloudcartconnector.com/?success=1&user_id=cloudcartconnector HTTP/1.1
Host: www.cloudcartconnector.com
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8

Is the data POST or GET? Here is my request URL:

http://1106-7916.el-alt.com/wc-auth/v1/authorize?app_name=Cloud Cart Connector&scope=read_write&user_id=cloudcartconnector&return_url=https://www.cloudcartconnector.com&callback_url=https://www.cloudcartconnector.com/myauthcallback

I am using ASP.NET MVC, so I need something like this:

    public ActionResult WooCommerceAuthCallBack(string consumerkey, string consumerSecret)
    {
            return RedirectToAction("MyConnections", "Home", new { Complete = "true" });
    }

**Comment by claudiosmweb** [comment]
Will receive a POST with the follow json data:

```
{
	"key_id": 12,
	"user_id": 1234,
	"consumer_key": "xxxxxxxxxxxxxxxx",
	"consumer_secret": "xxxxxxxxxxxxxxxx",
	"key_permissions": "read"
}
```
