### ISSUE TITLE
Should using get_shipping_methods() work?

### ISSUE THREAD

**Issue by pavelevap** [woothemes/woocommerce#9360]
Sorry, I did not know how to reopen #8949 and nobody answered.
Is this code snippet supposed to work?

```
add_action( 'woocommerce_review_order_after_shipping', 'woo_shipping_test' );
function woo_shipping_test() {
  $available_shipping = WC()->shipping->get_shipping_methods();
  var_dump($available_shipping);
}
```

Maybe I am missing something, but `get_shipping_methods()` returns `$this->shipping_methods` which will be always only empty `array()`?

Instead this it should return cached shipping methods? `$this->shipping_methods` is set during  `load_shipping_methods()` function, but this is running only inside `calculate_shipping_for_package()` when there is no cached value (not very often).

Or is there any other recommended approach to get cached shipping methods inside `woocommerce_review_order_after_shipping` hook?

**Comment by mikejolley** [comment]
It depends where it's called. Please don't ask questions like this on github - this is a bug reporting tool, not a support forum.

https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

**Comment by pavelevap** [comment]
Sorry, but it was not support question, I think that it is possible bug. And I still do not know if I am doing it wrong or it is bug, because it was closed once again :-(

Should this code above work? When you add it inside simple plugin .php file? I guess, it should, but it does not work.

And I am not alone: http://stackoverflow.com/questions/16460580/woocommerce-is-returning-empty-array-list-while-fetching-shipping-methods

Or should be another function `load_shipping_methods()` used in this case? But then we are missing cached values?

**Comment by mikejolley** [comment]
As I said, It depends when you call it. It's not a bug because core has no issue with the calls.

https://github.com/woothemes/woocommerce/blob/master/templates/cart/cart-shipping.php#L26

https://github.com/woothemes/woocommerce/blob/da8cae596bf00ea6e2786f6d677b3da9666f5e56/includes/wc-cart-functions.php#L170

**Comment by pavelevap** [comment]
Following code in core will not work, I guess: https://github.com/woothemes/woocommerce/blob/f7ea1d4c6a1f3751b80e807ef89b2968cb25c6e0/includes/class-wc-tracker.php#L313

It will return empty array() instead of shipping methods (without debug shipping enabled).

So, it should not be called inside custom plugin (as in my example)? Which function should be used to get cached shipping methods? I saw many different examples in different plugins, but what is the suggested approach? Using `load_shipping_methods()` instead of `get_shipping_methods()`?

**Comment by pavelevap** [comment]
It is also not very consistent, because `get_shipping_methods()` sometimes returns empty `array()` and sometimes shipping methods. Instead of empty `array()` it should return cached shipping methods (as expected). And so I think that it is some kind of bug.

**Comment by greguly** [comment]
As Mike said, this is not a support forum and code works, albeit not as you expect.

Then is not some kind of bug and you gotta look for support somewhere else.

Good luck!

**Comment by proArtex** [comment]
Absolutely agree with @pavelevap. Different methods behaviour on different pages in pretty strange. It's a bad practice. Now I need all the available shipping methods for Apple Pay js-API on single product and loop pages. Ok, I think, get_shipping_methods(): empty it says. Ok then, why do I see not empty list on checkout? Something went wrong with the logic...

**Comment by claudiosanches** [comment]
@proArtex feel free to submit a Pull Request.
