### ISSUE TITLE
Cannot Add a state in an existing Country that already has states

### ISSUE THREAD

**Issue by panbill** [woothemes/woocommerce#9361]
For example I am trying to add a new state in a country. This is what i am doing.
In i18n/states/GR.php

global $states;
$states['GR'] = array(
	'I' => __( 'Αττική', 'woocommerce' ),
	'A' => __( 'Ανατολική Μακεδονία και Θράκη', 'woocommerce' ),
	'B' => __( 'Κεντρική Μακεδονία', 'woocommerce' ),
	'C' => __( 'Δυτική Μακεδονία', 'woocommerce' ),
	'D' => __( 'Ήπειρος', 'woocommerce' ),
	'E' => __( 'Θεσσαλία', 'woocommerce' ),
	'F' => __( 'Ιόνιοι Νήσοι', 'woocommerce' ),
	'G' => __( 'Δυτική Ελλάδα', 'woocommerce' ),
	'H' => __( 'Στερεά Ελλάδα', 'woocommerce' ),
	'J' => __( 'Πελοπόννησος', 'woocommerce' ),
	'K' => __( 'Βόρειο Αιγαίο', 'woocommerce' ),
	'L' => __( 'Νότιο Αιγαίο', 'woocommerce' ),
	'M' => __( 'Κρήτη', 'woocommerce' )
);

I add another one so it becomes
global $states;
$states['GR'] = array(
	'I' => __( 'Αττική', 'woocommerce' ),
	'A' => __( 'Ανατολική Μακεδονία και Θράκη', 'woocommerce' ),
	'B' => __( 'Κεντρική Μακεδονία', 'woocommerce' ),
	'C' => __( 'Δυτική Μακεδονία', 'woocommerce' ),
	'D' => __( 'Ήπειρος', 'woocommerce' ),
	'E' => __( 'Θεσσαλία', 'woocommerce' ),
	'F' => __( 'Ιόνιοι Νήσοι', 'woocommerce' ),
	'G' => __( 'Δυτική Ελλάδα', 'woocommerce' ),
	'H' => __( 'Στερεά Ελλάδα', 'woocommerce' ),
	'J' => __( 'Πελοπόννησος', 'woocommerce' ),
	'K' => __( 'Βόρειο Αιγαίο', 'woocommerce' ),
	'L' => __( 'Νότιο Αιγαίο', 'woocommerce' ),
	'M' => __( 'Κρήτη', 'woocommerce' )
         'NST' => __( 'New State', 'woocommerce' )
);
But then i go to cart or to checkout page i just get a blank page.
Thanks

**Comment by claudiosmweb** [comment]
Well, in your example have a syntax error...

Should be:

```php
global $states;
$states['GR'] = array(
'I' => __( 'Αττική', 'woocommerce' ),
'A' => __( 'Ανατολική Μακεδονία και Θράκη', 'woocommerce' ),
'B' => __( 'Κεντρική Μακεδονία', 'woocommerce' ),
'C' => __( 'Δυτική Μακεδονία', 'woocommerce' ),
'D' => __( 'Ήπειρος', 'woocommerce' ),
'E' => __( 'Θεσσαλία', 'woocommerce' ),
'F' => __( 'Ιόνιοι Νήσοι', 'woocommerce' ),
'G' => __( 'Δυτική Ελλάδα', 'woocommerce' ),
'H' => __( 'Στερεά Ελλάδα', 'woocommerce' ),
'J' => __( 'Πελοπόννησος', 'woocommerce' ),
'K' => __( 'Βόρειο Αιγαίο', 'woocommerce' ),
'L' => __( 'Νότιο Αιγαίο', 'woocommerce' ),
'M' => __( 'Κρήτη', 'woocommerce' ),
'NST' => __( 'New State', 'woocommerce' )
);
```

**Comment by panbill** [comment]
You are right! I confused myself for no reson! Sorry
Issue solved!
