### ISSUE TITLE
Performance layered navigation

### ISSUE THREAD

**Issue by nickkuijpers** [woothemes/woocommerce#9366]
Hi,

The performance of my website is so bad, that i cant deliver this to my client. My client has 3k products, and 15 filters. When i insert 1 layered navigation in the widget, the website wont load anymore. My server is strong enough and i've got some other projects on it so its really the way WooCommerce handles filters.

Do you guys have any advice for me?

Thanks so much.

**Comment by mikejolley** [comment]
Current layered nav uses as many transients as it can, but due to the nature of the queries isn't perfect. See #7806

**Comment by nickkuijpers** [comment]
Hmm okay, thanks!
