### ISSUE TITLE
Api Authentication Endpoint Returns No Consumer Key or Secret

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#9367]
Hi,

I am trying to use the Api Endpoint:

https://woocommerce.wordpress.com/2015/08/07/api-settings-and-the-api-authentication-endpoint-in-2-4/

It appears that only a success and a user_id are sent back, but not JSON with a consumer key and secret. Here is my request and response. What am I doing wrong? The consumer key and secret are successfully created in WooCommerce.

Can this request take place over a non SSL site?

Request:
https://1106-7916.el-alt.com/wc-auth/v1/authorize?app_name=Connex%20for%20QuickBooks&scope=read_write&user_id=ConnexForQuickBooks&return_url=https://www.connexforquickbooks.com/integrations/woocommerceauthcallback&callback_url=https://www.connexforquickbooks.com/integrations/woocommerceauthcallback

Response

GET https://www.connexforquickbooks.com/integrations/woocommerceauthcallback?success=1&user_id=ConnexForQuickBooks HTTP/1.1
Host: www.connexforquickbooks.com
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
Referer: https://1106-7916.el-alt.com/wc-auth/v1/authorize?app_name=Connex%20for%20QuickBooks&scope=read_write&user_id=ConnexForQuickBooks&return_url=https://www.connexforquickbooks.com/integrations/woocommerceauthcallback&callback_url=https://www.connexforquickbooks.com/integrations/woocommerceauthcallback
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

**Comment by claudiosmweb** [comment]
You will receive in the `callback_url`. It sent a POST with the json data and works only with SSL.
