### ISSUE TITLE
Fatal error only when Logged IN when no taxes set on parent items

### ISSUE THREAD

**Issue by mathetos** [woothemes/woocommerce#9368]
You can see details here: https://wordpress.org/support/topic/variations-getting-fatal-error-about-tax-status?replies=3#post-7549952

This is the offending line: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variation.php#L386

** How to Duplicate:
* Be logged in as Admin
* Have Taxes disable, and "No, I will enter prices exclusive of tax"
* Have no child categories
* View the site/store while logged out (in a new browser perhaps) and there's no error
* View the site/store whille logged in and you'll receive this fatal error everywhere:
`Fatal error: Call to a member function get_tax_status() on a non-object in /home/*website*/public_html/wp-content/plugins/woocommerce/includes/class-wc-product-variation.php on line 386`

Commenting out the whole line resolves it, so does removing "parent"

**Comment by mikejolley** [comment]
Not able to replicate this one - sounds like the parent of a variation is invalid or does not exist. Checked your products themselves? System status report?

**Comment by claudiosmweb** [comment]
> Not able to replicate this one
[2]

And a variation must have some parent.

Possibly a problem by import products incorrectly. I recommend you delete the product and create it again.

**Comment by shekki25** [comment]
In my case it was a variation that didn't have a parent. You could add something to that file so you can find out what variation is causing this error. I added the following to `/wp-content/plugins/woocommerce/includes/class-wc-product-variation.php` so it would keep a log of the variations causing a problem:

Replace (lines 385-387):
```
public function get_tax_status() {
	return $this->parent->get_tax_status();
}
```

With: 
```
public function get_tax_status() {
	if( ! is_object( $this->parent ) ) {
		file_put_contents( 'class-wc-product-variation.log', 'THIS: ' . print_r( $this, true ), FILE_APPEND );
		file_put_contents( 'class-wc-product-variation.log', 'PARENT: ' . print_r( $this->parent, true ), FILE_APPEND );
	}
	return $this->parent->get_tax_status();
}
```
