### ISSUE TITLE
Issue in related.php file in single-product folder.

### ISSUE THREAD

**Issue by wpthemes786** [woothemes/woocommerce#9370]
Hello Woocommerce.

I just want to inform you that you have an issue in related.php file in single-product folder.

There is no global declaration of $posts_per_page in related.php, so

$related = $product->get_related( $posts_per_page ); did not know how many products to pull as a related products. Kindly update this in next woocommerce update.

I also attached the picture for your convenience

![2015-10-16_1739](https://cloud.githubusercontent.com/assets/12461946/10541883/bb66e006-742d-11e5-8464-3ee4d98d8908.png)

Thanks Regards :+1:

**Comment by bekarice** [comment]
Not needed, it's passed into the template from `woocommerce_related_products()` :)

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce/blob/f6526d72a72e3e2b110ed6c0f7b18329239c6667/includes/wc-template-functions.php#L1151-L1174
