### ISSUE TITLE
Woocommerce Reports not showing sales dollar values

### ISSUE THREAD

**Issue by windsorraw** [woothemes/woocommerce#9375]
This is a feature that has been working for over a year with no issues, I check the reports almost daily to see where I'm at for sales for the month.

When I click on my WP dashboard it does show me the monthly sale amount and all relevant information. When I click on the reports tab in woocommerce it shows $0 for all the sale amounts. It does show how many orders were placed and products sold but no dollar values. 

I did not change anything from the time this feature worked to when it didn't work.

I have shut down all plugin (except woocommerce) to see if that would help and it did not. I am not sure what to do at this point but this is an important feature for me.

Please help!

**Comment by mikejolley** [comment]
Try going to System Status > Tools and clearing transients, or changing the date range of the report.

**Comment by windsorraw** [comment]
I have done both of these and still no change and I  have also cleared the cache of the site. I can't figure this out and this is a very important feature especially for tax reporting.

**Comment by mikejolley** [comment]
You using a plugin to add custom order statuses?

**Comment by windsorraw** [comment]
No I am not. I am using only the standard order statuses.

**Comment by mikejolley** [comment]
Post your system status report.

**Comment by mikejolley** [comment]
WooCommerce > System Status - please send the report or this issue will be closed

**Comment by windsorraw** [comment]
I will post today


Sent from my Samsung device

-------- Original message --------

**Comment by windsorraw** [comment]
### WordPress Environment ###

Home URL: http://www.windsoressexcountyraw.ca
Site URL: http://www.windsoressexcountyraw.ca
WC Version: 2.4.7
Log Directory Writable: ✔  /hermes/bosnaweb06a/b1926/nf.pingpongcanadacom/public_html/wp-content/uploads/wc-logs/
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: –
Language: en_CA

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.6
PHP Post Max Size: 20 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.32
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✕ Your server does not have the SOAP Client class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.7
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (12) ###

Akismet: by Automattic – 3.1.5
Calculated Fields Form: by CodePeople.net – 1.0.67
Display Product for WooCommerce: by Sureshopress – 2.0.0
Elegant Themes Updater: by Elegant Themes – 1.1
MailChimp for WordPress Lite: by ibericode – 2.3.16
MailChimp User Sync: by ibericode – 1.3
MailChimp Top Bar: by ibericode – 1.2.2
WooCommerce Table Rate Shipping by Mangohour: by mangohour – 1.1.0
WooCommerce Breadcrumbs: by Anthony Hortin – 1.0.2
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce 'Email Money Transfer' Gateway: by Massoud Shakeri
BlazingSpider – 1.0.0

WooCommerce: by WooThemes – 2.4.7

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #760 - /shop/
Basket: #761 - /cart/
Checkout: #762 - /checkout-2/
My Account: #763 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Divi
Version: 2.5.4
Author URL: http://www.elegantthemes.com
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Has that been modified at all - why is there a gap after BlazingSpider?

**Comment by windsorraw** [comment]
no modifications at all, there seems to be a blank there on the report. i copy pasted as is

**Comment by windsorraw** [comment]
FYI, i have tried deactivating all of these plugins but have the same problem. I am not sure what blazing spider is BTW.

**Comment by mikejolley** [comment]
I think its an environment issue e.g. js error on your report page. Would need a login to check if you email, but it won't be a core bug.

**Comment by windsorraw** [comment]
Would you be able to look for me? I can give you my log-in privately

**Comment by windsorraw** [comment]
scratch that, the latest update fixed it :)

**Comment by windsorraw** [comment]
actually no it didn't, it is no showing me only the last 7 days and it goes to 0 for any other period

**Comment by mikejolley** [comment]
Email is on my profile.
