### ISSUE TITLE
Help with displaying Tax

### ISSUE THREAD

**Issue by ZanMarolt** [woothemes/woocommerce#9376]
Hello, 
I am having an issue modifying a code, I am not an expert and it would be really helpful if a developer would take a quick look at this.

I have opened a stackoverflow question.

Thanks!
http://stackoverflow.com/questions/33199266/woocommerce-wrapping-tax-into-a-div-and-a-span-php

**Comment by mikejolley** [comment]
Use strip tags? This is not a support area - use github for bug reports only.
