### ISSUE TITLE
is_shop doesn't return true when Shop page is set as Front Page

### ISSUE THREAD

**Issue by jkohlbach** [woothemes/woocommerce#9379]
If you set your Shop page as the Front Page under Settings->Reading, the function is_shop which is meant to return true if you are on the Shop page returns false.

I believe this is wrong/misleading as technically we are on the shop page, it just also happens to be the front page.

**Comment by mikejolley** [comment]
Debug: https://dl.dropboxusercontent.com/s/tvfe7pl9wxthhs5/2015-10-23%20at%2013.08.png?dl=0

Result: https://dl.dropboxusercontent.com/s/jxkvb00ct9owe43/2015-10-23%20at%2013.08%20%281%29.png?dl=0
