### ISSUE TITLE
Downloadable file tooltip icons

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#9381]
The downloadable product tooltips are not using the nice icon 

![](https://dl.dropboxusercontent.com/s/xk1jxztm7uonadb/2015-10-19%20at%2010.53.png?dl=0)

**Comment by claudiosmweb** [comment]
@jameskoster maybe time to remove this icon from all tooltips.

**Comment by jameskoster** [comment]
@claudiosmweb you mean replace instances of `[?]` with the icon?

**Comment by jameskoster** [comment]
Ohhh, I thought we'd already updated these to use the icon font. We should do that.

**Comment by claudiosmweb** [comment]
@jameskoster better use icon font for both.
