### ISSUE TITLE
reCaptcha Auth Endpoint

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#9384]
Hi,

I have a customer trying to use the OAuth endpoint, but they receive an error about captcha:

![image001](https://cloud.githubusercontent.com/assets/1679993/10592399/db592a46-7689-11e5-9b34-531029d7722c.png)

Site: https://centralvape.co.uk/

How do we turn the captcha off?

**Comment by mikejolley** [comment]
There is no captcha in WooCommerce. You have a plugin conflict.

**Comment by claudiosmweb** [comment]
What reCaptcha plugin you use?
