### ISSUE TITLE
How i create a custom structure like this site http://flatsome.uxthemes.com/ ?

### ISSUE THREAD

**Issue by hamdan-mahran** [woothemes/woocommerce#9388]
Hello,

Thanks for this awesome plugin :)
I want to use Woocommerce plugin to build custom pages layout like this site http://flatsome.uxthemes.com/ ?

I hope to tell me where i can find some advanced tutorials to do that ? 

Thanks very much!
All the best

**Comment by roykho** [comment]
Hello,

This is a place for logging bugs and not for support.  Please read the support section here https://github.com/woothemes/woocommerce
