### ISSUE TITLE
Exiting Setup Wizard results in re-installation attempt

### ISSUE THREAD

**Issue by andrewspittle** [woothemes/woocommerce#9392]
When first installing the WooCommerce plugin exiting out of the "Setup Wizard" using the "Not right now" button prompts WordPress to attempt to re-install the plugin. This was tested on a local installation of WooCommerce 2.4.7 on a single-site installation of WordPress 4.3.1.

To reproduce:
1. On a clean installation of WordPress (one where you have not installed WooCommerce before) navigate to Plugins > Add New.
2. Search for WooCommerce and click "Install Now"
3. After the plugin installs click "Activate Plugin"
4. This will launch the "Setup Wizard"
5. Click the "Not right now" button in the "Setup Wizard"
6. You'll be redirected to the plugin installation flow where WordPress attempts to re-install WooCommerce.

When step 6 completes you are redirected to a screen that displays this:

<img width="1349" alt="r5_claj0fi-3000x3000" src="https://cloud.githubusercontent.com/assets/86101/10621141/bbfdd3ae-7733-11e5-8b12-a269b51f17bf.png">

Despite saying that the plugin installation failed WooCommerce runs fine. I think this can be tracked down to the destination URL of [line 210 here](https://github.com/woothemes/woocommerce/blob/f6526d72a72e3e2b110ed6c0f7b18329239c6667/includes/admin/class-wc-admin-setup-wizard.php#L210).

If you try re-entering the "Setup Wizard" and then clicking "Not right now" again you will be properly redirected back to just `/wp-admin/plugins.php` That seems like the proper destination page for the button on the first initialization as well.

**Comment by mikeyarce** [comment]
Nice find @andrewspittle. I was able to reproduce following the same steps.
The same issue occurs if you click on the "Skip Setup" button in the screenshot above.

**Comment by WPprodigy** [comment]
Possibly an issue with wp_get_referer()? 

Looks like this was added in 2.4.7: https://github.com/woothemes/woocommerce/commit/991bd96fb66160205a5c6df66804dbdafdfebdcc

**Comment by claudiosmweb** [comment]
The button label just says: "Not right now"...
It makes no sense that is trying to "return to the previous page" or to the plugins page.
