### ISSUE TITLE
Variation prices not including tax on archive pages

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#9394]
To replicate, set it to "Display Prices in the Shop" including tax: http://cld.wthms.co/15C2d/4c9OTArl, and then just make a dummy tax rate: http://cld.wthms.co/13vUn/4EtsgWcn

The "Variation Test" product here is set to be $5, and the "Woo Single # 2" is set to be $10. You can see that the latter has the tax added on, but not the variation product: http://cld.wthms.co/1eQRj/1Vwyt9LH

Looks like none of this is ever getting called: https://github.com/woothemes/woocommerce/blob/2.4.7/includes/class-wc-product-variable.php#L310-L320

I think it has to do with the hashing, and maybe that the prices are being returned here regardless of $display: https://github.com/woothemes/woocommerce/blob/2.4.7/includes/class-wc-product-variable.php#L268

**Comment by WPprodigy** [comment]
Oh, this looks to fix the issue: https://github.com/woothemes/woocommerce/commit/6027b355ca7d5a471d1ccafd9e0b5149e872cc68 :)

**Comment by AlesMenzel** [comment]
I have encountered the same issue, will it be fixed soon?

Just to clarify. Variable products display prices EXcluding Tax on the Store Front even when they are set to be displayed INcluding Tax.

**Comment by mikejolley** [comment]
We're aiming to release the fixes monday. xx @claudiosmweb
