### ISSUE TITLE
CORS GET with Authorization header causing 401 preflight (OPTIONS)

### ISSUE THREAD

**Issue by limbera** [woothemes/woocommerce#9395]
I am serving a JavaScript web client from a different box to the Wordpress application and have configured CORS in the .htaccess file appropriately.

A GET request to /wc-api/v3/products/56 (with Authorization: Basic in the headers) is causing a preflight check. That OPTIONS request is returning 401 unauthorized. 

Here is the .htaccess config that I am using: 
````
    <ifModule mod_headers.c>
        Header always set Access-Control-Allow-Origin: "*"
        Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS"
        Header always set Access-Control-Allow-Headers "authorization"
    </ifModule>
````
Here is the JavaScript causing the issue:
````
    var consumerKey = "<redacted>";
    var consumerSecret = "<redacted>";
    var xhr = new XMLHttpRequest();
    xhr.open("get", "https://www.<redacted>.com/wc-api/v3/products/56", true);
    xhr.setRequestHeader("Authorization", "Basic " + btoa(consumerKey + ":" + consumerSecret));
    xhr.send();
````

I have tried adding this to the .htaccess file to force all OPTIONS to 200:
````
    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(.*)$ $1 [R=200,L]
````
Here is the Response Headers and Request Headers from chrome dev tools:
![cors_issue](https://cloud.githubusercontent.com/assets/2503457/10628430/f8855a9e-7810-11e5-8bc1-a48806f21f46.png)

**Comment by claudiosmweb** [comment]
Apparently this not coming to make the request on the API endpoint.
This is a problem with the configuration of your server and not with the WooCommerce Rest API.

In addition you should not use it:
```
    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(.*)$ $1 [R=200,L]
```

The API is already able to verify this...

We don't use `OPTIONS`... Just `GET`, `POST`, `DELETE` and `PUT`.

Maybe this can help you:

<ifModule mod_headers.c>
    Header always set Access-Control-Allow-Origin: "*"
    Header always set Access-Control-Allow-Methods "POST, GET, PUT, DELETE"
    Header always set Access-Control-Allow-Headers "Origin, Authorization, Content-Type"
</ifModule>

But is still an issue with your server and not with the WooCommerce.

**Comment by limbera** [comment]
I am not sure that you are correct. If you look at the screenshot I attached which has the response headers, you'll see that the WWW-Authenticate header is set to:
''''
Basic realm="WooCommerce API. Use a consumer key in the username field and a consumer secret in the password field"
''''

Which implies that the exit_with_unauthorized_headers() function [located in the /api/class-wc-api-authentication.php file] was called. This is because woo-commerce is trying to authenticate an OPTIONS request, which should not happen because an OPTIONS request should not be authenticated.

Reference:
The source code for the exit_with_unaithorized_headers() function is here: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L111

**Comment by claudiosmweb** [comment]
So your server is not setting the `PHP_AUTH_USER` and `PHP_AUTH_PW`.

Try it:

```
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

Or you can try pass as query strings:

```
/wc-api/v3/products/56?consumer_key=xxx&consumer_secret=xxx
```

**Comment by limbera** [comment]
Is the problem not that WooCommerce is trying to authenticate the OPTIONS request?

**Comment by claudiosmweb** [comment]
@limbera have you tried?

```
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

**Comment by limbera** [comment]
Yes I have. Fairly sure that WooCommerce is involved because this is still in the response headers:

Basic realm="WooCommerce API. Use a consumer key in the username field and a consumer secret in the password field"

**Comment by claudiosmweb** [comment]
@limbera Nop, the problem is that your server is not able to set `PHP_AUTH_USER` and `PHP_AUTH_PW`.
WooCommerce try check for this, since this vars are empty, you will get this error.

**Comment by limbera** [comment]
I see. I will try that tomorrow thanks for all your help claudio :)

**Comment by limbera** [comment]
@claudiosmweb I have set this in .htaccess:
```
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

But still no luck. Although I am not sure why not having those set would trigger this returned in the response headers: "Basic realm="WooCommerce API. Use a consumer key in the username field and a consumer secret in the password field"".

It sounds to me like the OPTIONS Request is being checked against WooComm credentials.

**Comment by claudiosmweb** [comment]
Nop, you need to fix your server to make able to set `PHP_AUTH_USER` and `PHP_AUTH_PW`.

**Comment by claudiosmweb** [comment]
http://php.net/manual/en/features.http-auth.php

https://www.google.com.br/search?client=ubuntu&channel=fs&q=php+set+PHP_AUTH_USER&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=178tVsGyKoSq8we8hIvoDQ#channel=fs&q=missing+PHP_AUTH_USER+and+PHP_AUTH_PW

**Comment by limbera** [comment]
Have managed to get the server correctly configured. Now the response is HTTP400 :-1: 

Thanks  for all your help. I'll let you know what I had done wrong when I work it out.

**Comment by psimondk** [comment]
Had a similar issue. 
Ended up bypassing the wooCommerce API completely by using the standard WP JSON API with post_type=product etc. Downside is that it only retrieves parameters with a value, but at least there are no CORS issue and oauth is optional.

**Comment by limbera** [comment]
@psimondk what version of nginx? i found that the apt-get ubuntu version was the cause of the issue.

**Comment by bradennapier** [comment]
I am also having this issue - can't make any requests due to cors... cors is setup in the htaccess

**Comment by raphaelkross** [comment]
I also had to deal with this kind of problem, I used this config in my .htaccess to solve it:

`Header  set Access-Control-Allow-Methods "POST, GET, PUT, OPTIONS, PATCH, DELETE" 
Header  set Access-Control-Allow-Origin "*"
Header  set Access-Control-Allow-Credentials "true"
Header  set Access-Control-Allow-Headers "X-Accept-Charset,X-Accept,Content-Type,Credentials"`

Attention to the Allow-Credentials and to Credentials in the Allow-Headers.

After that - all good.
