### ISSUE TITLE
Show all the skus's on admin panel for variable products. (back-end side)

### ISSUE THREAD

**Issue by mariosmaselli** [woothemes/woocommerce#9396]
If you have a simple product, you add the sku and the sku shows on the admin area on products.

But if you have a variable product which has an sku per variation they do not show on the admin panel.  The only way to show up is to add a parent sku (and you only see one sku anyway), which it doesnt make sense if there is not an actual product related to that sku. Plus it will be nice to see all the skus on the panel so you know how many variations and skus do you have on an specific product.

![screen shot 2015-10-13 at 18 23 43](https://cloud.githubusercontent.com/assets/1336977/10631832/22c7265c-77e9-11e5-8b0b-97f6a57d6fe8.png)

**Comment by mikejolley** [comment]
It might not be great to list all child SKUs there - there could literally be hundreds. How are you hoping its displayed? Why can you not set parent SKU to something that represents the child in this case? e.g. child 1001, 1002, parent 1001-1002

**Comment by mariosmaselli** [comment]
Well I understand that it can be a lot, but if you are giving the option to add specific sku for a variation and treat a variation like a "product", then I think that is a good idea to give the option to display somehow the list of skus.. or amount of variations or something... (my own personal opinion :D) anyway... I kind of came on a solution on my own... http://stackoverflow.com/questions/33106690/variations-sku-not-showing-up-wordpress-woocommerce/33259057#33259057

**Comment by mikejolley** [comment]
This table doesn't list variations though, it lists variable products :)

**Comment by mariosmaselli** [comment]
Yeah!!! that's what I meant, sorry maybe I didn't explain my self very well...

**Comment by mikejolley** [comment]
As a variation is a child, this isn't supposed to be listed. Adding those variation SKUs to the output would a) cause a performance drain as all child posts would need querying per variable product, and b) be a display issue if too many were present.

I think this is best left to customisation.

**Comment by mariosmaselli** [comment]
Thanks for your help!!!
