### ISSUE TITLE
Sorry, this product cannot be purchased => decimal points in attributes

### ISSUE THREAD

**Issue by 111-101** [woothemes/woocommerce#9397]
I have a client's site whose woocommerce plugin worked perfectly last xmas (he sells xmas turkeys through his site).

This year, I updated his prices, updated his plugins and WP only to get the error message 'Sorry, this product cannot be purchased.' when trying to add a product to his shopping cart.

Having spent 4 hours on this problem, I have found that attributes in the Woocommerce plugin no longer support decimal points or spaces. Or am I missing something?

You can see what I mean by going to a test page http://www.christmasturkeys.com.au/product/whole-turkeys-copy-2/

If you click on any options that do not have a decimal point or a space (eg 5 kg), then it all works. If you click on any that do (eg. 3.5kg) or the one with the space, then the ADD TO CART button disappears.

Has any one else found that problem?

I have spent 4 hours troubleshooting this problem and now will have to spend a couple more re-doing all his attributes and prices.

This means a total of 6 hours lost. I cannot charge him for that as it is not his fault.

Needless to say I am peeved!!!

Did I make a booboo somewhere along the way or am I right about the attributes not working with decimals and spaces?

**Comment by ChromeOrange** [comment]
Works here 

![](https://dl.dropboxusercontent.com/s/88230fofy6hvnaz/2015-10-21%20at%2012.30.png?dl=0)

How are you changing the standard drop down to radio buttons? Try going back to the standard dropdowns to see if that resolves the issue

**Comment by 111-101** [comment]
thank you chromeorange, it works if i disable the radio buttons plugin ... will contact my client to see if he is happy with using a drop down as opposed to radio buttons ... now i know where the problem resides ie the radio buttons plugin ... thanks again ;-)
