### ISSUE TITLE
Order received on confirmation page should have the class woocommerce-message or equivalent

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9398]
On the order-recieved page there is a `<p>` with the order success message. This p-tag does not have any classes and is difficult to target with javascript and css.

I would give it the same class as `woocommerce-message` or similar for it to be differentiated from regular text:

![image](https://s3.amazonaws.com/f.cl.ly/items/0Q381Q0P2S0s2C2E2R1h/Screen%20Shot%202015-10-22%20at%2009.40.30.png)

**Comment by WPprodigy** [comment]
I've thought about this as well, but it gets messy to generate a class based on the message. You could do so in this template though: https://github.com/woothemes/woocommerce/blob/master/templates/notices/success.php#L29

It may be worth looking into adding a third optional parameter to `wc_add_notice` that would act as an ID or Class for that paragraph. https://github.com/woothemes/woocommerce/blob/f7ea1d4c6a1f3751b80e807ef89b2968cb25c6e0/includes/wc-notice-functions.php#L75 - CC: @mikejolley 

In the meantime, you could maybe do some logic in that template file. Like:

```
<?php foreach ( $messages as $message ) :
	if ( $message == "Thank you. Order has been recieved.") {
		$class = "woocommerce-message order-thank-you";
	} else {
		$class = "woocommerce-message";
	}
?>
	<div class="<?php echo $class; ?>"><?php echo wp_kses_post( $message ); ?></div>
<?php endforeach; ?>
````

Or for a more global use, you could use str_replace and replace spaces with dashes, and make the message the class name. Which is the messy part I referenced early: http://php.net/manual/en/function.str-replace.php

**Comment by nishitlangaliya** [comment]
@mikejolley, I have done code for apply class for order received message and push code for review please check for the same.

![thankyou](https://cloud.githubusercontent.com/assets/11435772/10686894/58fe693a-7986-11e5-93fc-b6dac30dfb74.png)

**Comment by WPprodigy** [comment]
Hey @nishitlangaliya,

That only covers one use case though. If something is going to be implemented into core, then it should cover more than just that one message. Running a conditional for each message isn't ideal, and won't work with translations, etc.

**Comment by gedex** [comment]
@WPprodigy I think @yratof was referring to this template: https://github.com/woothemes/woocommerce/blob/master/templates/checkout/thankyou.php.

**Comment by gedex** [comment]
Adding class to the `p` or wrapper with `.woocommerce-message` in that template should clear the issue.

**Comment by WPprodigy** [comment]
Oh. Just add the class to the template then. No need for the JS.

Would it be better to replace those alerts with calls to `wc_add_notice()` though?

**Comment by nishitlangaliya** [comment]
@WPprodigy, Would it be better option direct add changes into template files?.

**Comment by gedex** [comment]
> Should that text be an alert though? And if so, would it be better to replace those alerts with calls to wc_add_notice()?

It might be too late, or `woocommerce_init` already passed, as the message in order received is rendered from shortcode. Not sure though. However, adding `.woocommerce-message` in that template won't be a big deal. @yratof in the mean time you can override it in your theme.

**Comment by WPprodigy** [comment]
I don't think there is anything wrong with giving it a class, but `.woocommerce-message` would give it the alert styling, which may not be the intended goal for just a simple line of thank-you text. 

Not sure though.

**Comment by yratof** [comment]
@gedex I'm developing something that is non-destructive, which means I'm not touching any theme files for woocommerce. Ideally, it needs to be done through a filter or through the core being changed

**Comment by yratof** [comment]
@WPprodigy true that it may not need the `woocommerce-message` class, but any class would work better than no class, as currently the only way to target it is by the body class followed by the `woocommerce` wrapper class.

- `message-thank-you`
- `message-order-notice`

It could technically follow the same principles as an alert, but for it's own purposes:

- `order-notice-success`
- `order-notice-failed`
- `order-notice-info`

Which you could then apply to failed orders, orders with warnings (backorder notifications) or failed because of X reason notification (Based on `<?php if ( $order->has_status( 'failed' ) ) : ?>`)
