### ISSUE TITLE
_wc_term_recount is super slow

### ISSUE THREAD

**Issue by KayLeung** [woothemes/woocommerce#9399]
_wc_term_recount taken 0.5s to perform one DB query. It's easily take 1s for adding one product into DB. It would be an issue when we do batch imports.

WP has wp_defer_term_counting() to disable recount temporarily. I hope woocommerce can implement a similar feature.

**Comment by mikejolley** [comment]
Term recount is a callback which WP will call when it's time to recount terms. wp_defer_term_counting will work here as well.

**Comment by ziodave** [comment]
There's a filter to disable it:

```
	/**
	 * Filter to allow/prevent recounting of terms as it could be expensive.
	 * A likely scenario for this is when bulk importing products. We could
	 * then prevent it from recounting per product but instead recount it once
	 * when import is done. Of course this means the import logic has to support this.
	 *
	 * @since 5.2
	 * @param bool
	 */
	if ( ! apply_filters( 'woocommerce_product_recount_terms', '__return_true' ) ) {
		return;
	}
```
