### ISSUE TITLE
Problem with price not showing in front simple product and quick edit price not updating in table row.

### ISSUE THREAD

**Issue by mundosam** [woothemes/woocommerce#9400]
Greetings

My host updated to the following specifications:

Apache Version	2.4.16
PHP Version	        5.6.14
MySQL Version	5.6.23

and since then I noticed that prices are not updating in the back end or on the table row during the quick edit action. In addition the price is also not showing in the front end, while instead a "SALE" badge is showing indicating 100% discount. This is a huge problem for me because I have more than 7 eshops up and running and none can add new products or update prices.

Can some help me please.

I also tried a fresh wordpress and woocommerce installation without any other plugin installed and enabled all debugging and error logging capabilities and permissions and still the problem remains.

Thanks a lot in advance I would appreciate your answer asap. 
![single product front](https://cloud.githubusercontent.com/assets/7571748/10642826/6beadee8-7828-11e5-8519-1ecc15fa6c5d.PNG)
![single product admin](https://cloud.githubusercontent.com/assets/7571748/10642827/6beba88c-7828-11e5-937f-dc159c79025e.PNG)
![quick view opened](https://cloud.githubusercontent.com/assets/7571748/10642825/6bea0b26-7828-11e5-8696-c43d5a39902f.PNG)
![quick view closed](https://cloud.githubusercontent.com/assets/7571748/10642828/6bee654a-7828-11e5-8798-e2aa851a397b.PNG)

**Comment by mundosam** [comment]
I thing the problem is with WooCommerce 2.4.7 because as soon as I downgraded to WooCommerce 2.4.6 and the problem is solved.

Can you please provide a new version with a fix?

Thanks in advance

**Comment by mikejolley** [comment]
@mundosam you're probably referring to the variation price issue patched in master.

As for this one, I cannot replicate. I tried a product without price, set price via quick edit and both instances refreshed the pricing. Sale is turned off.

Is this product supposed to be simple or variable? Does regular edit work in your case? You should rule out extensions and the theme too, and ensure no caching is affecting the frontend.

If you find a way to replicate it with core only, ping me and I'll reopen.

**Comment by mundosam** [comment]
mike I was able to replicate the problem in my own testing installation. Is there anyway I can give you FTP access and wordpress access to see the problem live?

**Comment by mundosam** [comment]
@mikejolley I have a clear picture of the problem now as I have just tested a new series of actions and events.

When I press "Add Product" I enter the title, sku, category and I press publish then the product price is saved and shown in the edit product screen as expected but in the products list and in the front end the prices are not shown. In quick edit whatsoever the price is shown on the newly created product. 

In order for the price to be shown in the front end I have to put a sale price. If I don't put a sale price the price in the front end is not shown. as soon as I put a sale price both in the edit product screen and in the quick edit then the price works fine. 

I tried every single thing out there from fresh installations to different plugin combinations to different themes nothing works. 

The only think that works is a function that I wrote my self that gets the job don which is the following.


	add_action( 'save_post', array( $this, 'woocommercesavepost' ), 10, 3 );

function woocommercesavepost( $post_id, $post, $update ) {
  $slug = 'product';
  if ( $slug != $post->post_type ) {
	return;
  }

if ( isset( $_REQUEST['_sale_price'] ) && isset( $_REQUEST['_regular_price'] ) ) 
{

 update_post_meta( $post_id, '_price', sanitize_text_field( $_REQUEST['_sale_price'] ) );
update_post_meta( $post_id, '_sale_price', sanitize_text_field( $_REQUEST['_sale_price'] ) );
update_post_meta( $post_id, '_regular_price', sanitize_text_field( $_REQUEST['_regular_price'] ) );

}else if( !isset( $_REQUEST['_sale_price'] ) && isset( $_REQUEST['_regular_price'] ) ){

update_post_meta( $post_id, '_price', sanitize_text_field( $_REQUEST['_regular_price'] ) );

}

}   

That actually saves the _regular_price to the _price meta_value where as under normal circuimstances and after I cheked the database of my site the price is only saved to the 
_regular_price meta and not in the _price meta.

Can you please help me resolve this problem because it is really important because I cannot enter prices with a sale on the product. In addition to that a selling price cannot be removed after it is entered nor a price you are only given the ability to change the price but not remove it.

Thanks in advance

**Comment by mundosam** [comment]
@mikejolley 

Mike sorry for spamming the posts but I wrote a function that actually works in every case except bulk edit of products. Because bulk edit works on its own just fine so no need to modify the behavior.

/**
	 * Save post metadata when a post is saved.
	 *
	 * @param int $post_id The post ID.
	 * @param post $post The post object.
	 * @param bool $update Whether this is an existing post being updated or not.
	 */
	public function savegiftpost( $post_id, $post, $update ) {

		/*
		 * In production code, $slug should be set only once in the plugin,
		 * preferably as a class property, rather than in each function that needs it.
		 */
		$slug = 'product';

		// If this isn't a 'book' post, don't update it.
		if ( $slug != $post->post_type ) {
			return;
		}
		
		if( $_REQUEST['action'] == 'edit' ){
			return;
		}
	
		if( $_REQUEST['action'] == 'inline-save' || $_REQUEST['action'] == 'editpost' ){
			
			if ( isset( $_REQUEST['_sale_price'] ) && isset( $_REQUEST['_regular_price'] ) ) {
				update_post_meta( $post_id, '_price', sanitize_text_field( $_REQUEST['_sale_price'] ) );
				update_post_meta( $post_id, '_sale_price', sanitize_text_field( $_REQUEST['_sale_price'] ) );
				update_post_meta( $post_id, '_regular_price', sanitize_text_field( $_REQUEST['_regular_price'] ) );
			}else if( !isset( $_REQUEST['_sale_price'] ) && isset( $_REQUEST['_regular_price'] ) ){
				update_post_meta( $post_id, '_price', sanitize_text_field( $_REQUEST['_regular_price'] ) );
				update_post_meta( $post_id, '_sale_price', '' );
			}else if( !isset( $_REQUEST['_sale_price'] ) && !isset( $_REQUEST['_regular_price'] ) ){
					update_post_meta( $post_id, '_sale_price', '' );
					update_post_meta( $post_id, '_regular_price', '' );
					update_post_meta( $post_id, '_price', '' );
			}else if( isset( $_REQUEST['_sale_price'] ) && !isset( $_REQUEST['_regular_price'] ) ){
					update_post_meta( $post_id, '_sale_price', '' );
					update_post_meta( $post_id, '_regular_price', '' );
					update_post_meta( $post_id, '_price', '' );
			}
		}
	}

Can you please revise the conditional statements and tell me if this will work until woocommerce is fixed with a future update?

Thanks in advance

**Comment by mikejolley** [comment]
I don't follow; show me the line in WC which sets the wrong price?

**Comment by geoffthibeau** [comment]
We were having similar issues—the post meta data `_regular_price` would update in MySQL when publishing or updating but not `_price`.

We resolved it by increasing the `max_upload_size` via `php.ini` in `wp-admin` folder. My guess is that the POST object was too large. I'm also guessing that if the code above works/worked for you, it's because it's generating a new SQL query after the original one truncates (or however it pseudo-saves).

I hope this helps anyone else who stumbles upon this thread.

**Comment by mundosam** [comment]
I will try that and see if it resolves the issue. Mainly because the problem persists on all my sites. 
I hope it helps.
Thanks for the insight, I will be providing my feedback soon.

**Comment by geoffthibeau** [comment]
In the event that `post_max_size` wasn't the variable that was key, I'm pasting the full `php.ini` file we used (which honestly is a bit too generous on the numbers, so adjust as needed).

```
upload_max_filesize = 1000M
post_max_size = 2000M
memory_limit = 3000M
file_uploads = On
max_execution_time = 180
```

**Comment by shameemreza** [comment]
Thanks @geoffthibeau  I was trying to solve this problem last few hours. Though I am not sure this is not the actual solution. Hope woocommerce team will take care on it.

**Comment by mundosam** [comment]
Greetings.

I would like to post another problem that a client of mine is facing, but i do not have the time to write another function to handle variations. The stock and quantity on variations are not updating when  I  first change the stock quantity at variation level or change the price at variation level and then pressing the Save Changes to save via Ajax and then update for the post to update. Everything returns to the amount that was previously displayed. I saw a lot of woocommerce updates but the problem remains and I am really concerned.

@mikejolley can you please provide a solution? I can register and account for you so that you can view the problem in real time.

Thanks in advance

**Comment by mundosam** [comment]
I have just tried another scenario on a different website/installation/theme the problem remains. In this case as soon as I create a new product  =>  add some custom attributes  => add some variations with price, SKU, stock, stock status then the price is not saving. I first press the Save Changes to save via ajax and then press update post. The prices are not saved and the system returns an empty value for the variation price.

This is a huge problem.

@mikejolley I tried the approach of @geoffthibeau and the problem remains.

I am just pointing out that I cannot create any shops until this problem is solved. I am really frustrated about this.

Please provide a feedback asap.

Thanks in advance.

**Comment by mikejolley** [comment]
@mundosam you showed custom code you had running earlier - how are you certain you're not breaking the save? Try a clean install. I'm trying what you said and its saving the data fine.

**Comment by mundosam** [comment]
@mikejolley I will try one now. And give you my feedback

**Comment by almazka** [comment]
Awesome!
I was faced with the same problem not for the first time! when I programmatically create a product, the field values for example, such as the price are not showing in the front.
The problem was solved when I changed the values in the file php.ini as written **geoffthibeau**.
In addition, these values were specified in the htaccess file, **but until I changed the file php.ini, the problem was not solved.**
**Great Thanks!**

**Comment by shubhamkhandel** [comment]
@mundosam hello there i am facing problem in Woocommerce  page. i have a product page where price is not updating when i use variation for example my product base price is 20$ and i use  variation which should add 50$in base price so total should be 70$ so the total is showing in cart but on page its not showing. i'm sending you link of that page **http://printbizkits.com/product/round-corner/** please provide feedback asap.
Thanks in advance.

**Comment by vietzon** [comment]
I almost have same issue. 

I have can see the updates (95) in admin. But frontend display old price (90). 

where is the code:
update_post_meta( $prod_id, '_regular_price', '350' );
update_post_meta( $prod_id, '_sale_price', '95' );
update_post_meta( $prod_id, '_price', '95' );

**Comment by dash33bba** [comment]
HELLO THERE PLEASE HELP. 
Me to? I have can see the updates (16~220 price) in admin. But frontend display price on variation
 (16.13-221.80). i think is around  "12.04 %" but this lagg is only with admin.

**Comment by thewhiterabbit** [comment]
I'm using the newest version... This is a HUGE problem! I've had to fix some things for modx in the past...must I fix this also, or is there some actual attention on this as opposed to blaming "custom code" and ignoring the issue?

About to switch to a more reliable platform after only testing woocommerce for the first time and finding that this is an ongoing unadressed issue. Please advise.

![6b411a1d-0fd0-49cc-8f3f-1c7769b109a4](https://user-images.githubusercontent.com/5334222/44884434-3fb5e500-ac70-11e8-83e6-99708d99e155.png)
![415dbd2c-7ba5-42b4-9c40-a27a6845db0f](https://user-images.githubusercontent.com/5334222/44884435-3fb5e500-ac70-11e8-8b2e-09ec2684516b.jpeg)
![c03d5853-517c-40ff-b56b-f6b3fa3a76aa](https://user-images.githubusercontent.com/5334222/44884436-3fb5e500-ac70-11e8-9202-d22cbb38952e.png)

**Comment by thewhiterabbit** [comment]
Further investigation reveals that the buffer error is NOT the issue.
Upon clicking update the following error is produced...
![1841768d-cfa4-4256-98e2-c3662c2556b9](https://user-images.githubusercontent.com/5334222/44885810-c1f5d780-ac77-11e8-80be-cbc1851ee8af.jpeg)
![1516041e-7f0e-40fc-96a5-5b20ebc999e6](https://user-images.githubusercontent.com/5334222/44885811-c28e6e00-ac77-11e8-90ed-aa9ebaa6e079.jpeg)
![37025992-0032-4996-b9cb-121325cd95a7](https://user-images.githubusercontent.com/5334222/44885812-c28e6e00-ac77-11e8-8026-f3ed6fa47ce6.jpeg)


My professional advice is to change the name of the variable in woocommerce that is conflicting.

**Comment by TheMangoTrain** [comment]
Hello, I've been dealing with a similar issue (prices not being displayed in the front-end or the price column in Admin/Products).

I've been generating fake products for testing WooCommerce. Titles, content, images... all work. However when it came to the price, I had the similar problems as above.

Initially I was populating the _regular_price field, and was seeing a successful result in the editor view of the fake product... so I thought everything was working. But when I looked at products in Admin/Products, nothing was shown in the price column for my fake products. Only my manually-created products had a price in the column. Similarly only the manually created products were visible in the store front-end.

In Admin/Products, if I selected all my fake products, and did an arbitrary batch edit... for example just change the category for them all... then all of sudden the problem got fixed. Like WooCommerce sanitized my fake product or something along those lines; perhaps it saw my price fields were corrupt.

Eventually the main trick was to populate _price when generating my fake products, and no problems were seen.

Hope this input is relevant. I'm glad I didn't have to dive into server config =).

**Comment by ajayshrivas** [comment]
Hello All ,
you can try this 
if(isset($_POST['products_upload'])){
    
    if(!isset($_POST['productname']) ) {
        return;
    }
    // Check that the nonce was set and valid
    if( !wp_verify_nonce($_POST['_wpnonce'], 'wps-frontend-post') ) {
        echo 'Did not save because your form seemed to be invalid. Sorry';
        return;
    }
   // Do some minor form validation to make sure there is content
    if (strlen($_POST['productname']) < 3) {
        echo 'Please enter a title. Titles must be at least three characters long.';
        return;
    }
    if (strlen($_POST['product_description']) < 50) {
        echo 'Please enter content more than 50 characters in length';
        return;
    }
    if($_POST['productregularprice'] < $_POST['productsaleprice']){
        
        echo 'Please check sale price';
        return; 
    }
    
    $user_id = get_current_user_id();
    // Add the content of the form to $post as an array
    $post = array(
        'post_author' => $user_id,
        'post_title'  => $_POST['productname'],
        'post_content' => $_POST['product_description'],
        'post_status' => 'publish',   // Could be: publish
        'post_type' => 'product', // Could be: `page` or your CPT
        'comment_status' =>'closed',
        );
    $insert_id = wp_insert_post($post); 
    if($insert_id):
        $product = wc_get_product($insert_id);
        if(!empty($_POST['productregularprice'])):
         //update_post_meta($insert_id,'_regular_price',sanitize_text_field($_POST['productregularprice']));
          $product->set_regular_price($_POST['productregularprice']);
          $product->save();
        endif;
        if(!empty($_POST['productsaleprice'])):
            
          //update_post_meta($insert_id,'_sale_price',sanitize_text_field( $_POST['productsaleprice']));
          $product->set_sale_price($_POST['productsaleprice']);
          $product->save();
        endif;
        require_once( ABSPATH . 'wp-admin/includes/image.php' );
        require_once( ABSPATH . 'wp-admin/includes/file.php' );
        require_once( ABSPATH . 'wp-admin/includes/media.php' ); 
        
        $attach_id = media_handle_upload('product_image_upload', $insert_id);
        set_post_thumbnail( $insert_id, $attach_id );
       
        
        $attach_product_sample_id = media_handle_upload('product_sample_upload', $insert_id); 
        
        $attachment_product_sample_url = wp_get_attachment_url($attach_product_sample_id);
        
        if(!empty($attachment_product_sample_url)):
          update_post_meta($insert_id, 'fw_option:mp3_full_songs', $attachment_product_sample_url);
        endif;
        
        $attach_zip_id = media_handle_upload('product_zip_upload', $insert_id); 
        $attachment_zip_url = wp_get_attachment_url($attach_zip_id);
        $download_id = md5( $attachment_zip_url );
        $file_name = $_POST['productname'];
        // Creating an empty instance of a WC_Product_Download object
        $pd_object = new WC_Product_Download();
        // Set the data in the WC_Product_Download object
        $pd_object->set_id( $download_id );
        $pd_object->set_name( $file_name );
        $pd_object->set_file( $attachment_zip_url );
    ?>  
    <script>
    jQuery(document).ready(function($){
       "use strict";
        toastr.success('upload success full');
        window.location.replace('<?php echo esc_url(home_url('/products/')); ?>'); 
    }); 
    </script>
    <?php
    endif;
}

**Comment by ajayshrivas** [comment]
https://docs.woocommerce.com/wc-apidocs/source-class-WC_Product.html#844-852

More detail you can check here all WooCommerce function

**Comment by nhui77777777** [comment]
As on date i tried all above.still problem exist.Trying to create new products using storefront child theme. After WooCommerce update, I am not able to update price at all.whatever regular price I feed once I update doesn’t show regular price and displays blank. What I tried was deactivated all plugins and child theme, cleared all cache still the price is not updating in back-end and in front end displays BLANK
![Screenshot_1](https://user-images.githubusercontent.com/31938601/66769652-45ea3d80-eed3-11e9-83c7-37c8362485cc.png)
.

**Comment by chanduking08** [comment]
I'm also having this issue, when switching from Simple to Variant product's select dropdown.
