### ISSUE TITLE
Multi-Currency support

### ISSUE THREAD

**Issue by Lewiscowles1986** [woothemes/woocommerce#9413]
WooCommerce is a hugely popular tool for selling online, but out of the box, it only seems to support single currency per-store. You can sort of get around this with plugins like WPML, or using a multi-site, but this feels like using a hammer to push a door shut.

Problems other platforms have
 * All currencies translate to main store currency on invoices etc
 * Difficult setup requiring plugins to poll currency rates (most stores use a normalized conversion rate that changes maybe twice a year...)
 * Not enough control over multi-currency & multi-lingual

**Comment by claudiosmweb** [comment]
Not a core issue. Exists plugins for it.
