### ISSUE TITLE
change price as dynamic

### ISSUE THREAD

**Issue by yassara** [woothemes/woocommerce#9414]
Hi,
I want to add to my product as dolar price and sell as turkish lira. 
in code must be change price with currrent currency automaticlly. 
What should I add code and where? 
For example;
price(usd) * (usd/tl) =new price(as turkish lira)

this code check the usd/tl: 
<?php

$xml = simplexml_load_file('http://www.tcmb.gov.tr/kurlar/today.xml');
foreach ($xml->Currency as $Currency) {
    // USD ALIŞ-SATIŞ
    if ($Currency['Kod'] == "USD") {
        $usd_DS = $Currency->BanknoteSelling;
        $usd_DA = $Currency->BanknoteBuying;
    }
    // EURO ALIŞ-SATIŞ
    if ($Currency['Kod'] == "EUR") {
        $eur_DS = $Currency->BanknoteSelling;
        $eur_DA = $Currency->BanknoteBuying;
    }
  }
?>
<table>
    <tr>
        <td style="width: 200px;"><strong>Para Birimi</strong></td>
        <td style="width: 50px;"><strong>KUR</strong></td> 
    </tr>
    <tr>
        <td>Dolar (USD)</td>
        <td><?php echo $usd_DS; ?>$</td>
    </tr>
    <tr>
        <td>Euro (EUR)</td>
        <td><?php echo $eur_DS; ?>€</td>
    </tr>

    </tr>
</table>

**Comment by claudiosmweb** [comment]
Good luck man! But here is not a support channel...
