### ISSUE TITLE
Hide other shipping methods when free shipping is made available via a coupon

### ISSUE THREAD

**Issue by corsonr** [woothemes/woocommerce#9419]
Shouldn't other shipping methods be hidden when a coupon allows free shipping?

![](http://cld.wthms.co/1c2Lu/5CEbts0o+)

![](http://cld.wthms.co/1hZfh/1AVMqctS+)

**Comment by shivapoudel** [comment]
+1

**Comment by WPprodigy** [comment]
Ideally. But what if you wanted to also offer a two-day or one-day shipping option? Free shipping usually implies standard 5-day or whatever, so some stores may also want to offer expedited methods, like Amazon does even when free shipping is available.

**Comment by mikejolley** [comment]
This should not be in core - it can be done with code. As Caleb said, some stores offer free shipping + expedited options. It's easier to remove options than add them.
