### ISSUE TITLE
Add Authorizations to Simplify Commerce

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#9420]
It looks like the Simplify Commerce library shipped with WooCommerce is out of date and does not yet support Authorizations(only payments). 

The updated library bundle includes Authorization.php while the WooCommerce core version doesn't:

http://cld.wthms.co/EVQX/5sc7QSMs

This would allow us to offer Authorization-only charges in the future.

https://www.simplify.com/commerce/docs/sdk/php

**Comment by claudiosmweb** [comment]
@mikejolley we can't do it.
Since this new lib works just for PHP 5.3 or later.

**Comment by claudiosmweb** [comment]
Forget, I just test and works with 5.2 :)
