### ISSUE TITLE
City field on checkout is missing

### ISSUE THREAD

**Issue by Faldano** [woothemes/woocommerce#9423]
I'm trying to test the checkout on wocommerce and this appeard

![screenshot 2015-10-25 18 16 27](https://cloud.githubusercontent.com/assets/14995072/10715318/049fdaa2-7b45-11e5-8139-8c226ee8027d.png)
![screenshot 2015-10-25 18 16 40](https://cloud.githubusercontent.com/assets/14995072/10715317/049181a0-7b45-11e5-9c76-cb187879b295.png)

Is this a bug or what?

**Comment by mikejolley** [comment]
No; you've hidden the field, possibly with CSS. Core doesn't hide the city field for any locale.

**Comment by Faldano** [comment]
I don't think I edited the checkout css because i didn't see the html city field on developer mode.

anyway, thanks a lot for replying :)
I've reinstall it anyway. We'll see if it comes again

**Comment by mikejolley** [comment]
Then look at plugins. I don't think city is ever hidden.
