### ISSUE TITLE
Customer Details Section on Order review/view screens

### ISSUE THREAD

**Issue by NWR91** [woothemes/woocommerce#9424]
Contact Details (Telephone and Email) on View Order and Order Confirmation pages are not tabular and should be a list.

**Comment by jameskoster** [comment]
Debatable :p

**Comment by NWR91** [comment]
How is it debatable?

Telephone and email are not tabular data and it's just being used to apply titles to the data and a box around them

**Comment by mikejolley** [comment]
@jameskoster vs table, these could alternatively be a definition list. But yes, its debatable like the cart argument before.

Basically, if you remove all styles and just view the page 'raw', the data should make sense. For cart, a table does make the most sense.

For email + tel, maybe not so much. However, this area can be extended by plugins.

**Comment by NWR91** [comment]
Even so, the contact details added to that section via plugins will never be required to be in a table format. It will only ever be a title and the data - which should be in a list and a span on the title to style it, and apply display: block; on it on mobile. This will also me semantically better as it is not tabular data.

I only say that the cart should be in divs with an outer list for each item is that it can be styled to look a HELL of a lot better than a boring row on a table - look at the Apple website for example. Looks better, and uses DIVS

It’s not viewing the ‘raw’ page that makes it ‘make sense’, it’s if it makes sense without headers.. which the cart does make sense without the headers in thead. Semantically, and responsively, the WHOLE of WooCommerce should be divs! even if using display: table; display: table-row; and display: table-cell; is the work around!

**Comment by mikejolley** [comment]
@NWR9 Again, a DIV and SPAN has no semantic meaning :) CSS styling !== semantics.

You're thinking too visual; as I said, without styling, the CONTENT should make sense to a user/screen reader. Table does for cart, but we're talking about a different area here and I agree a list would be better. But not divs and spans.

**Comment by jameskoster** [comment]
I still think you can argue both causes and wouldn't generally want to change something ambiguous like this just because one person opened an issue. But it's a small item and I doubt anyone would mind if we changed it :-) Feel free to send a PR to make it a `ul`. I don't think `dl` makes sense here since it's not really a description.

**Comment by claudiosmweb** [comment]
+1 for @jameskoster

**Comment by NWR91** [comment]
I use lists for the cart items, and divs within the list item to lay out the details. It's semantically better than a table as each cart item is a list item.. It allows for a more readable layout and is also responsive.

I'm thinking more practical, professional and semantically about the layout of the cart/checkout process.

As far as screen readers, it will see each cart item as an ITEM, instead of a table row. It will make more sense to the user as it is read out and look better on screen to regular users. 

That's why I make the point that the cart should be a list/divs.
