### ISSUE TITLE
Add to Cart button in variable.php

### ISSUE THREAD

**Issue by NWR91** [woothemes/woocommerce#9425]
Add to Cart button in variable.php comes from core function so adjusting the order of elements (price before quantity and vice-versa) is impossible

**Comment by mikejolley** [comment]
This area (variation data) contains more than just a cart button and is dynamic - what is your proposal here?

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/compare/revised-single-variation-cart-template

**Comment by mikejolley** [comment]
Closed in favour of #9458. Add your feedback there @NWR91
