### ISSUE TITLE
Proposal: Symlinks

### ISSUE THREAD

**Issue by NWR91** [woothemes/woocommerce#9426]
Symlinks like Magento has which can be turned on/off in Woo System Settings to show which template sections are being loaded from, to allow easier overriding of templates if needed.

**Comment by mikejolley** [comment]
https://wordpress.org/plugins/woocommerce-template-hints/

**Comment by NWR91** [comment]
Build into WooCommerce instead of separate plugin. 

It's standard in Magento so should be standard in WooCommerce

**Comment by claudiosmweb** [comment]
@NWR91 There is absolutely nothing on earth, not even God can say that it has something in Magento... for obligation must have in WooCommerce too.
WooCommerce is not a clone of Magento!
