### ISSUE TITLE
Variable Product not showing individual picture/Add to cart button also disappeared 

### ISSUE THREAD

**Issue by SouthernEdgeApparel** [woothemes/woocommerce#9427]
I am running klean theme and I just did update all and everything was working great and the when i went back to check everything something happened. I can no longer add my variable products into the basket nor will it show each products picture. The menu is still there and the drop down list still has all the options. My simple products are still able to be put in my shopping cart. 

I am new to websites and really need to get this worked out. Any help is appreciated!!
Please help me!!

Thanks so much

**Comment by mikejolley** [comment]
Theme issue, not core. https://wordpress.org/support/topic/24-common-issue-variations-missing-on-product-pages?replies=1

**Comment by SouthernEdgeApparel** [comment]
@mikejolley  Thanks for responding and I read that article prior to posting. I still don't know how or where to do any of that stuff. I have never done a single thing using codes. Sorry for the lack of knowledge. Any help would be great.

**Comment by mikejolley** [comment]
If you read it you'll see it tells you to check both system status and for theme updates. Please do that.
