### ISSUE TITLE
Export invoice doesnot view good in e-mail

### ISSUE THREAD

**Issue by JeroenALV** [woothemes/woocommerce#9429]
![schermafbeelding 2015-10-26 om 14 20 35](https://cloud.githubusercontent.com/assets/15324981/10729879/bff032f0-7bec-11e5-96d0-de7a4ce4a839.png)
![schermafbeelding 2015-10-26 om 14 20 23](https://cloud.githubusercontent.com/assets/15324981/10729880/bff23a32-7bec-11e5-96c8-1bb31bc1058d.png)

When a customers makes an order in WooCommerce there is informations missing in the exporttabel to e-mail and PDF. Like measurement of the item. What is the problem?

**Comment by claudiosmweb** [comment]
Export invoices in PDFs is not a native feature of WooCommerce... Contact the invoices plugin developer that you are using.
