### ISSUE TITLE
I need a way to search for an order by note

### ISSUE THREAD

**Issue by slloyd88** [woothemes/woocommerce#9430]
Can you add a way to search for orders based on a note?  This would be very, very helpful.

	$cnt=$wooClient->orders->get_count(null,array('note'=>'ABCDEFG'));
	$crecs=$wooClient->orders->get(null,array('note'=>'ABCDEFG'));

**Comment by claudiosmweb** [comment]
Using our API is not possible at this time.
But you can do this using WP_Query.

Need to be using API?

**Comment by slloyd88** [comment]
Yes

**Comment by mikejolley** [comment]
Core doesn't allow a search by note either; it would need adding to core first. However, I don't really see the value in note searching. Could you submit to ideas.woothemes.com with justification? Cheers!

**Comment by slloyd88** [comment]
Here is the use case:

I am pulling Amazon Orders and pushing them into wooCommerce so that all 
my orders are in one system.  I need a way to mark the newly created woo 
order with some identifying mark from the Amazon order info.  My hope 
was to add the Amazon order number as a note and then search woo for 
that order by note to insure I do not add the same order twice.

Is there another way or field that I can search on that would 
accommodate this?  What do you suggest?

Steven Lloyd
Water Guru - http://www.purestill.com
Dev Mavin - http://www.devmavin.com

**Comment by mikejolley** [comment]
@slloyd88 You cannot query by custom fields or notes right now.

**Comment by slloyd88** [comment]
Can you tell me what table the notes are stored in?
I see the orders are in wp_posts but I cannot seem to find the table 
where the notes are stored.

Steven Lloyd
Water Guru - http://www.purestill.com
Dev Mavin - http://www.devmavin.com

**Comment by gedex** [comment]
Notes in order are comments. You can use `WP_Comment_Query` or `get_comments`. Make sure to remove `array( 'WC_Comments', 'exclude_order_comments' )` filter. Here's an example (taken from API code with addition of `search` arg):

~~~php
$args = array(
	'post_id' => $order_id,
	'approve' => 'approve',
	'type'    => 'order_note',
	'search'  => 'Your search query',
);

remove_filter( 'comments_clauses', array( 'WC_Comments', 'exclude_order_comments' ), 10, 1 );

$notes = get_comments( $args );

add_filter( 'comments_clauses', array( 'WC_Comments', 'exclude_order_comments' ), 10, 1 );
~~~

Pass in your search query in `search` arg. Hope this helps.

**Comment by AnandaDivine** [comment]
I need to also search my orders by note. Is there a plugin?

**Comment by ospiotr** [comment]
Hey @AnandaDivine 

You can use this plugins to search orders by notes: 
https://wordpress.org/plugins/note-finder-for-woocommerce/

**Comment by AnandaDivine** [comment]
OMG, That is precisely what I have been looking for ospiotr! Thank you so much.
