### ISSUE TITLE
Hooks / filters for reviews

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9432]
I'm using Advanced Custom Fields to extend the reviews for woocommerce to include a few more fields, however, I'm unable to find a way of hooking onto any reviews:

				<li itemprop="review" itemscope itemtype="http://schema.org/Review" <?php comment_class(); ?> id="li-comment-<?php comment_ID() ?>">

					<div id="comment-<?php comment_ID(); ?>" class="comment_container">

						<?php echo get_avatar( $comment, apply_filters( 'woocommerce_review_gravatar_size', '60' ), '' ); ?>

						<div class="comment-text">

							<?php if ( $rating && get_option( 'woocommerce_enable_review_rating' ) == 'yes' ) : ?>

								<div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating" class="star-rating" title="<?php echo sprintf( __( 'Rated %d out of 5', 'woocommerce' ), $rating ) ?>">
									<span style="width:<?php echo ( $rating / 5 ) * 100; ?>%"><strong itemprop="ratingValue"><?php echo $rating; ?></strong> <?php _e( 'out of 5', 'woocommerce' ); ?></span>
								</div>

							<?php endif; ?>

							<?php if ( $comment->comment_approved == '0' ) : ?>

								<p class="meta"><em><?php _e( 'Your comment is awaiting approval', 'woocommerce' ); ?></em></p>

							<?php else : ?>

								<p class="meta">
									<strong itemprop="author"><?php comment_author(); ?></strong> <?php

										if ( get_option( 'woocommerce_review_rating_verification_label' ) === 'yes' )
											if ( wc_customer_bought_product( $comment->comment_author_email, $comment->user_id, $comment->comment_post_ID ) )
												echo '<em class="verified">(' . __( 'verified owner', 'woocommerce' ) . ')</em> ';

									?>&ndash; <time itemprop="datePublished" datetime="<?php echo get_comment_date( 'c' ); ?>"><?php echo get_comment_date( wc_date_format() ); ?></time>:
								</p>

							<?php endif; ?>

							<div itemprop="description" class="description"><?php comment_text(); ?></div>
						</div>
					</div>

Is there a better way of changing this template without altering the file in the current theme?

**Comment by yratof** [comment]
@claudiosmweb In the interest of using Advanced Custom Fields with woocommerce, would it be plausible to have `woocommerce_review_before_comment_text` also?

**Comment by claudiosmweb** [comment]
@yratof done ^
