### ISSUE TITLE
Cart coupon should only show as Discount Total in Edit Order screen

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#9433]
When a cart discount coupon is applied to an order, the discounted amount displays correctly under Discount Total. However, it also seems to change the line item unit price and line item total price to reflect the fully discounted amount. 

![](http://cld.wthms.co/1iT3p/3P7YT9bY+)

This is confusing. In my opinion, the order items should equal the total price of all regular priced items. Then discount total should be subtracted from that to give the total order price.

**Comment by mikejolley** [comment]
All discounts (cart and product) are applied to line items, before taxes. Doing the discount later would be incorrect.

The bottom value is the total discount across all line items.
