### ISSUE TITLE
"Hide out of stock items from the catalog" doesn't work if over 30 variations

### ISSUE THREAD

**Issue by mdmoore** [woothemes/woocommerce#9434]
This is related to the ajax variation threshold and can be fixed by increasing that value.  

https://gist.github.com/claudiosmweb/6f91ad228c2176b986b2#file-functions-php

Is this considered a bug, or is increasing the ajax variation threshold the preferred way to handle these issues?

**Comment by mdmoore** [comment]
Answered here. https://github.com/woothemes/woocommerce/issues/8825

**Comment by harkalygergo** [comment]
Claudio’s nickname changed to claudiosanches, so the required link: https://gist.github.com/claudiosanches/6f91ad228c2176b986b2
