### ISSUE TITLE
403 Error API

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#9435]
Hi,

I am receiving a 403 error, when I access this website's API. Is there a plugin issue or HTAAccess file error?
![screen shot 2015-10-26 at 1 43 55 pm](https://cloud.githubusercontent.com/assets/1679993/10742072/97092e40-7c01-11e5-847e-7274947f444f.png)

Request

GET https://thewhosoevers.com/wc-api/v2 HTTP/1.1
Accept: application/json
Authorization: Basic XX==
Host: thewhosoevers.com

Response

HTTP/1.1 403 Forbidden
Date: Mon, 26 Oct 2015 20:47:29 GMT
Server: Apache/2.2.15 (CentOS)
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Vary: Accept-Encoding
Content-Length: 295
Keep-Alive: timeout=3, max=500
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wc-api/v2
on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at thewhosoevers.com Port 443</address>
</body></html>

**Comment by WPprodigy** [comment]
Hi @jmawebtech,

I'm sorry but this is not the place to get support. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Try the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.

API documentation: http://woothemes.github.io/woocommerce-rest-api-docs/
