### ISSUE TITLE
how to upload image ??

### ISSUE THREAD

**Issue by shahshyam** [woothemes/woocommerce#9438]
Hello all,

I am planing to upload image in Woocommerce from  local machine. i did not get any method to upload image in woocommerce ? what about creating category in Woocommerce ??

**Comment by WPprodigy** [comment]
Hi @shahshyam,

WooCommerce uses WordPress' media library: http://cld.wthms.co/10cHE/2RPuY1d4. And you can add a product category here: http://cld.wthms.co/10A7b/16f91OXc

This is not the place to ask for support like this though. Github is for reporting issues and/or contributing. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, try asking in the support forums, https://wordpress.org/support/plugin/woocommerce. Or try a few google searches / searches here: https://support.woothemes.com
