### ISSUE TITLE
Products only showing title

### ISSUE THREAD

**Issue by mgeoth** [woothemes/woocommerce#9442]
Hi this morning i saw all my products are only showing the title on the category pages. Not sure what happened. I restored to a few days back when all was fine but tge problem still persists. Was there an update recently to 2.4.8? Could this have caused the fault?

**Comment by WPprodigy** [comment]
Hi @mgeoth,

This is likely a theme related issue, but could be a plugin as well. Try switching to a default theme / disabling other plugins till you find the cause.

This is not the place to ask for support though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.

**Comment by mikejolley** [comment]
I've seen this caused by the archive customiser plugin too. So its a plugin/theme issue.
