### ISSUE TITLE
If no star rating, allow filter to substitute html

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9445]
Is it possible that if there products with ratings and products without ratings, then rather than outputting nothing, there could be a filter allowing something to be placed there.

My example would be having a list of products with various reviews, new products with no reviews, everything is misaligned from a design point of view:
![image](https://s3.amazonaws.com/f.cl.ly/items/1O273P3y390H070i041F/misaligned.png)

	...
	<?php else : ?>
		<?php do_action( 'woocommerce_product_no_rating' ); ?>
	<?php endif; ?>

File: `woocommerce/templates/single-product/rating.php`

**Comment by claudiosmweb** [comment]
Just change the template.

**Comment by yratof** [comment]
I'm trying to not change template files, as they change and update
