### ISSUE TITLE
Variable Product Variations Issue

### ISSUE THREAD

**Issue by geeklore** [woothemes/woocommerce#9446]
When there are more than 30 variations added to a Variable Product, the front end drop downs stop limiting the options to the specific variation and show all options. Reported in 2.4.7, replicated in 2.4.7 and 2.4.8. Ticket #346487

**Comment by mdmoore** [comment]
You may be able to solve the issue by raising the variation threshold to accommodate the max number of variations being used.  Check this as well as the snippet Mike includes.  https://github.com/woothemes/woocommerce/issues/8825

**Comment by claudiosmweb** [comment]
This is not an issue and is the expected behavior...  https://woocommerce.wordpress.com/2015/07/13/improving-the-variations-interface-in-2-4/

**Comment by geeklore** [comment]
Thanks guys. Updated the customer. Sorry for the extra work.
