### ISSUE TITLE
Updating Product Issue (Error: Missing parameter data [woocommerce_api_missing_callback_param]) 

### ISSUE THREAD

**Issue by RazV3R** [woothemes/woocommerce#9447]
I can make a new product, delete but cannot update a product.

just make a simple request;
	
print_r( $client->products->update( '3858', array( 'title' => 'Yet another test product' ) ) );

and return this ;

Error: Missing parameter data [woocommerce_api_missing_callback_param]
400
stdClass Object
(
    [headers] => Array
        (
            [0] => Accept: application/json
            [1] => Content-Type: application/json
            [2] => User-Agent: WooCommerce API Client-PHP/2.0.1
        )

    [method] => PUT
    [url] =>xxxx
    [params] => Array
        (
            [oauth_consumer_key] => xxxx
            [oauth_timestamp] => xxxx
            [oauth_nonce] => xxxx
            [oauth_signature_method] =>xxxxx
            [oauth_signature] => xxxxx
        )

    [data] => Array
        (
            [product] => Array
                (
                    [title] => Yet another test product
                )

        )

    [body] => {"product":{"title":"Yet another test product"}}
    [duration] => 1.165
)
stdClass Object
(
    [body] => {"errors":[{"code":"woocommerce_api_missing_callback_param","message":"Missing parameter data"}]}
    [code] => 400
    [headers] => Array
        (
            [Date] =>  Tue, 27 Oct 2015 21:13:24 GMT
            [Content-Type] =>  application/json; charset=UTF-8
            [Content-Length] =>  97
            [Connection] =>  keep-alive
            [Keep-Alive] =>  timeout=30
            [Server] =>  Apache/2
            [X-Powered-By] =>  PHP/5.3.29
            [Vary] =>  User-Agent,Accept-Encoding
        )

)
Any idea why?

**Comment by claudiosmweb** [comment]
Use:

print_r( $client->products->update( '3858', array( 'product' => array( 'title' => 'Yet another test product' ) ) ) );

**Comment by RazV3R** [comment]
Thank you but Not working still show same error;

Error: Missing parameter data [woocommerce_api_missing_callback_param]
400

I also had tried print_r( $client->products->update( '3858', array( 'products' => array( 'title' => 'Yet another test product' ) ) ) ); but still no luck

**Comment by claudiosmweb** [comment]
Need to test, maybe the library is not sending any data.
But not seems to be an issue with WooCommerce.

**Comment by Naveenkant93** [comment]
Hi @claudiosmweb 

I am accessing the api in Android to update data.
http://woothemes.github.io/woocommerce-rest-api-docs/?shell#update-a-customer

but I am getting the same error. I have set all query parameters and json data too.

Please help me for the same

**Comment by chruldt** [comment]
I (try to) use curl, but the docs ain't right: http://woothemes.github.io/woocommerce-rest-api-docs/?shell#create-a-product
I use -d as per the docs, but the error says "missing parameter data"

**Comment by achadee** [comment]
+1 to this 

using the ruby client and sending:

```
{:product=>
  {:id=>1988,
   :title=>"Rock Pools Cape",
   :sku=>"MFAS010022",
   :description=>
    "<p>The intricate design and dark romantic colours of this stunning cape make it the perfect fashion accessory for those seeking to wrap themselves in sheer, luxurious silk.</p><p>The cape has been styled to be to worn as a lightweight and effortlessly elegant wrap suitable for daytime or evening.</p><h2>The Art</h2><p>Artist: <span style=\"color: #800080;\">Joy Nangala Brown</span><br> Artwork: Yumari<span style=\"color: #800080;\"> Jukurrpa</span></p><p>The original painting depicts the Dreamtime Story of a forbidden love between a man and a woman from different clans. The couple would meet in secret at a group of rocks in the desert called Yumari. The circles represent the pools of water in the rocks.</p><p>All items are beautifully presented in a handmade gift box with a card confirming the authenticity of the Aboriginal artwork</p>",
   :short_description=>
    "<p><span class=\"silk\">100% Pure Silk Chiffon</span><br>\nWrapped in Luxury 110cm x 180cm</p>\n",
   :regular_price=>#<BigDecimal:64d0638,'0.22E3',9(18)>,
   :weight=>#<BigDecimal:64d0520,'0.0',9(18)>,
   :stock_quantity=>100,
   :images=>
    [{:id=>2017,
      :src=>
       "https://logicsaas-company-images.s3.amazonaws.com/4f3256f6-6b5c-4e14-8f25-bcb84f7c9beb/21092/3c9b9d68-bbd6-4aa9-96e8-432de0f9e50f-Rock-Pools-Cape-5.jpg",
      :position=>0},
     {:id=>2018,
      :src=>
       "https://logicsaas-company-images.s3.amazonaws.com/4f3256f6-6b5c-4e14-8f25-bcb84f7c9beb/21092/cdfa7683-0c6b-4a4c-937c-4828f481c4e1-Rock-Pools-Cape-8.jpg",
      :position=>1},
     {:id=>2016,
      :src=>
       "https://logicsaas-company-images.s3.amazonaws.com/4f3256f6-6b5c-4e14-8f25-bcb84f7c9beb/21092/6340a637-6ef4-407f-8253-7e80010e6431-Rock-Pools-Cape-1.jpg",
      :position=>2},
     {:id=>2212,
      :src=>
       "https://logicsaas-company-images.s3.amazonaws.com/4f3256f6-6b5c-4e14-8f25-bcb84f7c9beb/21092/5648cc3f-451b-4e3d-9cc4-385e9082faca-Rock-Pools-Cape.jpg",
      :position=>3}
    ]
  }
}
```

Any help at all would be appreciated!

**Comment by chruldt** [comment]
"missing parameter data" seems to indicate that the data wasn't appreciated as such, any variable out of the perceived bounds can trigger it, so have you checked if WC can handle BigDecimal?

**Comment by achadee** [comment]
Solved!

There was a plugin on the customers wordpress instance called "ithemes security" blocking all put and post requests

**Comment by KennethRatzlaff** [comment]
achadee, How can you tell if something is blocking put or post requests?

**Comment by achadee** [comment]
I deactivated it and the API freed up, then reactivated it and it started throwing security errors again

hope that helps

**Comment by KennethRatzlaff** [comment]
Thanks, that does help. I'll take a look at what other plugins we have installed and go through them one by one.

**Comment by abegit** [comment]
[https://github.com/KennethRatzlaff](@KennethRatzlaff) I double checked and found that its listed in the iThemes plugin > System Tweaks > Filter Long URL Strings
