### ISSUE TITLE
Hosted Page Failure Since 2.3.13

### ISSUE THREAD

**Issue by kkevilus** [woothemes/woocommerce#9450]
It'd be nice to get to the bottom of the WC-Ajax failures at Checkout.  At checkout my gateway plugin echo's the form below and the javascript to submit the form.  This worked fine in all version prior to 2.4 and I've done all the posted steps and have made no progress.  Please help!

&lt;form name=&quot;checkout' id=&quot;checkout_form&quot; action=&quot;https://hostedpaymentpage.com/payment&quot; method=&quot;post&quot;&gt;&lt;input type=&quot;hidden&quot; name=&quot;x_login&quot; value='ABCDEFGHIJKLM' /&gt;&lt;input type=&quot;hidden&quot; name=&quot;x_amount' value='&quot;.99&quot;/&gt;&lt;input type='hidden' name=&quot;x_fp_sequence&quot; value=&quot;45947&quot; /&gt;&lt;input type ='hidden' name=&quot;x_fp_timestamp&quot; value='1446017986' /&gt;&lt;input type='hidden' name='x_fp_hash' value='hash-generated' /&gt;&lt;input type='hidden' name='x_currency_code' value=USD /&gt;&lt;input type='hidden' name='x_type' value=AUTH_ONLY /&gt;&lt;input type='hidden' name='x_receipt_link_url' value=https://xxxxx.xxxx/return.php /&gt;&lt;input type='hidden' name='x_show_form' value='PAYMENT_FORM' /&gt;&lt;input type='hidden' name='x_test_request' value='FALSE' /&gt;&lt;input type='hidden' name='x_invoice_num' value='3124' /&gt;&lt;input type='hidden' name='x_cust_id' value='2' /&gt;&lt;input type='hidden' name='x_customer_ip' value='64.134.26 .202' /&gt;&lt;input type='hidden' name='x_email' value='emaik@email.com' /&gt;&lt;input type='hidden' name ='x_first_name' value='first' /&gt;&lt;input type='hidden' name='x_last_name' value='Last' /&gt;&lt;input type ='hidden' name='x_address' value='1 Main' /&gt;&lt;input type='hidden' name='x_city' value='Blah' /&gt;&lt;input type='hidden' name='x_state' value='TX' /&gt;&lt;input type='hidden' name='x_zip' value =12345' /&gt;&lt;input type='hidden' name='x_country' value='US' /&gt;&lt;input type='hidden' name='x_phone' value ='5555555557' /&gt;&lt;input type='hidden' name='x_ship_to_first_name' value='First' /&gt;&lt;input type='hidden' name='x_ship_to_last_name' value=''Lastss' /&gt;&lt;input type='hidden' name='x_ship_to_address' value='1 Main St' /&gt;&lt;input type='hidden' name='x_ship_to_city' value='Blah' /&gt;&lt;input type='hidden' name='x_ship_to_state' value='TX' /&gt;&lt;input type='hidden' name='x_ship_to_zip' value='7xxx8' /&gt;&lt;input type='hidden' name='x_ship_to_country' value='US' /&gt;&lt;/form&gt; &lt;script type=&quot;text/javascript&quot;&gt; //&lt;![CDATA[ window.document.getElementById('checkout_form').submit(); //]]&gt; &lt;/script&gt;

**Comment by mikejolley** [comment]
Spitting out HTML is not supported - gateways need to return an ARRAY response which is then changed to JSON. Your plugin should instead redirect to the thanks page and output the form there.
