### ISSUE TITLE
Downloadable Product appears with shipping cost in the cart

### ISSUE THREAD

**Issue by FEDEUBER** [woothemes/woocommerce#9451]
Hi, great plugin!
I have an issue with the downloadable products. I set up the downloadable product as the woocommerce guide suggest. When I try to add it to the cart, it appears the shipping cost and taxes set for the other product. I tested if there was a conflict with the theme I use, Lobo. I changed the theme and I still have the same issue. Can you help me?
Thanks in advance,
Fede

**Comment by mikejolley** [comment]
Make it virtual as well.

**Comment by FEDEUBER** [comment]
Thank you, Mike!!! it works now.
