### ISSUE TITLE
Support custom meta for line items

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#9452]
When creating an order and adding line items, there's no way to add custom meta (IE subscriptions meta fields).

Can we add support for them?

**Comment by claudiosmweb** [comment]
@SiR-DanieL in API?

**Comment by SiR-DanieL** [comment]
Yes in the API

**Comment by claudiosmweb** [comment]
@SiR-DanieL Subscriptions have an API now.
The same should apply to other plugins that use custom data.
