### ISSUE TITLE
Add Currency Symbol for Pakistan 

### ISSUE THREAD

**Issue by mohsinr** [woothemes/woocommerce#9453]
Hi,

I see there are many currencies listed in the Wizard's step of choosing currency. However I see currency of our country, Pakistan is not listed. Can you please add that too? e.g.

Pakistani Rupee (Rs.)

Thank you
PS. I wanted to add that I can easily add this info using Filters, however I am trying to promote WordPress and Woocommerce as an Open Source solution in our country and It will be great if users can install WordPress & Woocommerce without with this custom tweak in their functions file, if they could easily select the currency just like they can select the country from the list in the field above the currency field. Thanks

**Comment by shivapoudel** [comment]
You can create a Pull Request for your currency symbol xD

**Comment by mohsinr** [comment]
Thank you @shivapoudel ! Can you please check if I got it right before I submit the pull request? Thank you!

**Comment by shivapoudel** [comment]
Cool!
