### ISSUE TITLE
Price Submitted through API comes out wrong or truncated on product page

### ISSUE THREAD

**Issue by christechno25** [woothemes/woocommerce#9459]
Hi Sir/Madam,

I've been working on a software that communicates with the API. Everything works well in terms of the submission and updating part, however, I've recently discovered something wrong. Let's say if I submit '$250.00' for the price and I check the information through the browser, it's the right price, but if I view it on the product page, only the first 2 numerical characters comes out as the price. If I do inspect element on it there's a meta tag that contains the real price but the price that is shown is wrong. I know this is how the php part of Woocommerce is coded but I'm wondering why this is happening. I never changed any default code on Woocommerce. If I enter the product through the browser it works fine. Is there something in the API that submits information to make Woocommerce display the product page like this? Then again, if I check price information through the browser, the price is right. Any help is greatly appreciated. Thank you so much!

Sample Product Page
http://www.gloriabazar.com/products/panasonic-nr-a8513ds-8-5-cu-ft-single-door/

**Comment by claudiosmweb** [comment]
We have two problems here...

First:

>  Website Under Construction 

Second:

> '$250.00'

You need to send as a float number, and not an string.
Need to be like `250` or `250.00`.
