### ISSUE TITLE
Full vs partial refund

### ISSUE THREAD

**Issue by Spreeuw** [woothemes/woocommerce#9460]
In `includes/class-wc-ajax.php` there is a condition that determines whether a refund was partial or complete:
```php
if ( $order->get_remaining_refund_amount() > 0 || $order->get_remaining_refund_items() > 0 ) {
	do_action( 'woocommerce_order_partially_refunded', $order_id, $refund->id, $refund->id );
} else {
	do_action( 'woocommerce_order_fully_refunded', $order_id, $refund->id );
}
```

However, this results in people receiving an email about a partial refund when only the total refunded amount has been entered, even if this results in a net of 0. Now this can be 'fixed' by setting all the product quantities accordingly, but I think it would be better to avoid this by only checking the total amount:
```php
if ( $order->get_remaining_refund_amount() > 0 ) {
	do_action( 'woocommerce_order_partially_refunded', $order_id, $refund->id, $refund->id );
} else { ...
```

or, if you need to check the items qty, reverse it:
```php
if ( $order->get_remaining_refund_amount() <= 0 || $order->get_remaining_refund_items() == 0 ) {
	do_action( 'woocommerce_order_fully_refunded', $order_id, $refund->id );
} else {
	do_action( 'woocommerce_order_partially_refunded', $order_id, $refund->id, $refund->id );
}
```

**Comment by mikejolley** [comment]
This was changed because orders can contain free items. If you refund the money portion of an order, but it still contains a free item, it will be fully refunded and access to said free item revoked.
