### ISSUE TITLE
Continue Shopping button pops up every time a purchase is made

### ISSUE THREAD

**Issue by nextstepsyep** [woothemes/woocommerce#9461]
Thanks for such a great plugin!!!  

QUESTION: Can you help me remove the code that adds the Continue Shopping button to the top of the screen every time a product is added to the cart? 

You guys did a great job explaining how to get the Continue Shopping button to appear on the page without any products in the cart, I was able to pop that puppy on there in one swoop.  Unfortunately, my newness to coding made me add the code prematurely as the Continue Shopping button actually showed up on the next screen during the checkout process so, of course, it wasn't necessary to add it. Secondly I have no idea how to find where I added the extra code to remove it without disrupting my store.  Outside of the extra Continue Shopping buttons, everything else is working perfectly so I'm scared!  Please help. 
![stem exchange screen capture](https://cloud.githubusercontent.com/assets/15329521/10817292/3b6c8360-7e0f-11e5-8599-14ff1b2d8eea.png)

http://nextstepsyep.org/outreach/stem-exchange-2/

**Comment by technofreaky** [comment]
@nextstepsyep 
if you have modified any woo commerce template. then there is some issue with the modification

**Comment by nextstepsyep** [comment]
Unfortunately, I realized I did too late.  Although I followed instructions and it worked perfectly, I don't remember what I did or where I did it.  I was hoping someone could tell me what I did to get it on there so I can go back and delete it.

**Comment by technofreaky** [comment]
@nextstepsyep 
Can you post your woocommerce cart template code via paste bin ?

**Comment by nextstepsyep** [comment]
@technofreaky Sure!  How do I do that? :)

**Comment by technofreaky** [comment]
@nextstepsyep 
Step 1. Open A File Copy The Full Code
Step 2. just go to http://pastebin.com/ 
Step 3. Paste In The TextArea Provided 
Step 4. Submit.

you will get a link. just share that here :)

**Comment by nextstepsyep** [comment]
Doing it now. Stay awesome @technofreaky

**Comment by technofreaky** [comment]
Going out will be back in 20min

On Thu, Oct 29, 2015 at 5:32 pm, nextstepsyep < notifications@github.com [notifications@github.com] > wrote:
Doing it now. Stay awesome @technofreaky [https://github.com/technofreaky]

—
Reply to this email directly or view it on GitHub
[https://github.com/woothemes/woocommerce/issues/9461#issuecomment-152157907] .[https://github.com/notifications/beacon/ABzAf8MQ_n5AynxOF_txXq51L2d5NrnWks5pAgJegaJpZM4GYH78.gif]

**Comment by nextstepsyep** [comment]
@technofreaky I remember following instructions to edit an add-to-cart.php, a loop.php and a single-product.php file.  I can't fnd the single-product one but did find the other two. 
http://pastebin.com/07HhyFpL

**Comment by technofreaky** [comment]
@nextstepsyep you have give the file for add to cart. but cart template is required to check

**Comment by nextstepsyep** [comment]
@technofreaky Oh okay

**Comment by nextstepsyep** [comment]
@technofreaky Hi! I just uploaded the woocommerce template file.  I couldn't remember how to get to it. :/ Hope I added the right one.

**Comment by technofreaky** [comment]
@nextstepsyep 

where its ?Link

**Comment by nextstepsyep** [comment]
@technofreaky Sorry about that. Forgot to hit the submit button. It's there now. :)

**Comment by technofreaky** [comment]
@nextstepsyep 
No its not there..

**Comment by nextstepsyep** [comment]
@technofreaky It's showing as Issue #3 on my end. I'll refresh my screen in case I'm looking at something weird.

**Comment by nextstepsyep** [comment]
@technofreaky http://pastebin.com/nRnH4WaK

**Comment by nextstepsyep** [comment]
@technofreaky Here's the other link http://pastebin.com/70qtq67L

**Comment by technofreaky** [comment]
@nextstepsyep 
are you joking . ?? you are give the woocommerce file source. i asked for cart page template source from
`your-theme/woocommerce/cart/` 

i am leaving

**Comment by nextstepsyep** [comment]
@technofreaky No, I am not  joking. I honestly don't know what I am doing!  I am a strategic planner not a coder.  I came to github and copied some code to add a Continue Shopping button into the thing it told me to when I thought my woocommerce system wasn't working.  I don't remember what I did or where it told me to add the extra code.  I am so sorry if I offended your intelligence, but I am at the level before someone is considered a novice coder. Well, actually, I'm closer to the "wasn't really interested in learning code for my site but had to because I work for myself" level.  

Please don't leave!!!! I'm supposed to launch my online store tomorrow morning and I don't know what to do. (tears forming)

**Comment by nextstepsyep** [comment]
@technofreaky Someone just helped me find the your-theme/woocommerce/cart file you mention via something called Filezilla.  I'll post it in the pastebin for you to review.

Please don't leave. I know I'm a pain but I'm being honest.

**Comment by nextstepsyep** [comment]
@technofreaky http://pastebin.com/teGWMi61

**Comment by technofreaky** [comment]
@nextstepsyep 
try changing the line
`<?php do_action( 'woocommerce_before_cart_table' ); ?>` to
`<?php //do_action( 'woocommerce_before_cart_table' ); ?>`

**Comment by nextstepsyep** [comment]
Thank you....and I'm so very, very sorry!  I truly appreciate you.

**Comment by technofreaky** [comment]
@nextstepsyep  np
