### ISSUE TITLE
Admin can't remove coupon code

### ISSUE THREAD

**Issue by jmfonseca** [woothemes/woocommerce#9465]
There is no way to remove a used coupon from an order, even on the admin side.

**Comment by mikejolley** [comment]
Those are a list of used coupons; removing them wouldn't change the totals. You need to modify the line item costs.

**Comment by jmfonseca** [comment]
I understand that, but check this example:

1) Admin creates coupon for 10% discount with a restriction of only one use per user.
2) User uses the coupon.
3) Admin sees something wrong with the order and wants to remove that coupon from the order so the user can use it again in a following order without creating a new coupon.

Right now there is no way of doing this.

**Comment by mikejolley** [comment]
The coupon stored in the order just keeps a record of what coupon was used; it's not used for tracking.

The tracking is done by post meta attached to the coupon itself; _used_by meta. As it's been applied by your user, regardless of whether its removed from the old order, or the old order is deleted, the coupon cannot be used again. Therefore a new coupon is required, or the usage count needs increasing.
