### ISSUE TITLE
New filter suggestion 

### ISSUE THREAD

**Issue by guzun** [woothemes/woocommerce#9466]
Hi there.

I'd like to propose to add a new filter for 'request_query' method in 'WC_Admin_Post_Types' class
woocommerce/includes/admin/class-wc-admin-post-types.php

That filter would be used to alter the returned value:

```
.....
$vars = apply_filters( 'woocommerce_update_request_query', $vars );
return $vars;
```

For example I needed this to hide some orders from the orders list based on some custom meta.

If this filter would be added in a future version it would be very nice.

Thank you,
Alex

**Comment by mikejolley** [comment]
Not required; you can filter on 'request' like we do.
