### ISSUE TITLE
Gist min purchase order snippet no longer working

### ISSUE THREAD

**Issue by adstrakt** [woothemes/woocommerce#9468]
This great snippet no longer works with the latest update of woocommerce, which is a real shame, as it was working perfectly. https://gist.github.com/woogist/0ad5bff8f0e87c8033e7

**Comment by claudiosmweb** [comment]
![screenshot from 2015-10-30 13-04-21](https://cloud.githubusercontent.com/assets/1264099/10849212/c30dc16a-7f06-11e5-9a4f-0ce72542ca8c.png)
