### ISSUE TITLE
Plugin Integration With WooCommerce Request

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#9470]
Hi,

i dont know this is a good place for this request. but i dont know where to post it.

i have already developed a plugin For WordPress + WooCommerce .
https://wordpress.org/plugins/woocommerce-quick-donation/

in the plugin i have used **WP_List_Table** To list only Donation order in that i am not able to delete order bulk. can any one please help me to get it fixed https://github.com/technofreaky/woocomerce-quick-donation/issues/21

**Comment by mikejolley** [comment]
I think you know by now this place is for bug reports only and not dev/code support. WP_List_Table usage is related to WP itself, not WooCommerce specifically.

**Comment by technofreaky** [comment]
@mikejolley thanks. but i am trying to get it for woocommerce orders. if possible kindly support me .

**Comment by mikejolley** [comment]
This is not a support forum.

**Comment by technofreaky** [comment]
@mikejolley thanks
