### ISSUE TITLE
System Status page confuses the child theme's version number with the parent theme's

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/woocommerce#9472]
The System Status page confuses the child theme's version number with the parent theme's version number, and that results in an invalid notification that a theme update is available.

Screenshot: http://cld.wthms.co/11Zzq/6yIeGhBv ( Latest version of ProShop is 1.0.2, the latest version of Storefront ( parent ) is 1.5.1 ).

_Link to the ticket: https://woothemes.zendesk.com/agent/tickets/350164_

**Comment by WPprodigy** [comment]
Ahh, we are using get_template() rather than get_stylesheet() here: https://github.com/woothemes/woocommerce/blob/5917ff15ba734b32aca7bc97bb873d81164afb15/includes/admin/views/html-admin-page-status-report.php#L556
