### ISSUE TITLE
Add To Cart shortcode only triggers "X has been added to your cart." message for variations

### ISSUE THREAD

**Issue by aand01** [woothemes/woocommerce#9474]
If the [add_to_cart id="X"] shortcode is being used to add a SIMPLE product, on a product page, no "“X” has been added to your cart." message is displayed - ie. the customer receives no notification that the product has been added to the cart. 

However, if the [add_to_cart id="X"] shortcode is being used to add a VARIABLE product, an "“X” has been added to your cart." is shown at the top of the page, notifying the customer that the given product has been added to the cart. The latter behavior is desired for SIMPLE products as well.

**Comment by WPprodigy** [comment]
Hey,

I just tested this out but was unable to replicate the issue you described. Both simple and variable products triggered that message for me.

Did you try turning off all other plugins and switching to a default theme?

**Comment by mikejolley** [comment]
Works here too, even with ajax which gives you a different notice https://dl.dropboxusercontent.com/s/s57jfwcaa4pr3fe/2015-11-02%20at%2009.38.png?dl=0

**Comment by aand01** [comment]
It must be theme or plugin related somehow - thanks!
