### ISSUE TITLE
add_to_cart()-method | Don't work for "guests"

### ISSUE THREAD

**Issue by inovek** [woothemes/woocommerce#9475]
I've written a external visual product editor which allows to customize the product and add the result to the cart of Woocommerce. Works like a charme: "**If you're logged in**"

As guest, nothing happens. I searched and searched for a reason, because I thought this problem could be my failure. But then I found topics of other users with the same problem in the forums. (unanswered)

So I think it could be a bug/issue of WooCommerce and want to report it.

    $orderItem = $woocommerce->cart->add_to_cart($ppcProduct, 1, '', '', array(
            'ppcSession' => $ppcSession,
            'ppcPriceOffeset' => $ppcPriceOffeset,
            'ppcMeta' => $ppcMeta,
            'ppcImage' => $ppcImagePath,
            )
        );

**Comment by claudiosmweb** [comment]
Using on `plugins_loaded`?

**Comment by inovek** [comment]
No, I'm using it in inside of a external file where I require wp-load.php first, processing the data and at the and I use the shown snippet (first post) to add the results into the cart. (then redirect into it)

If the customer or admin is logged in, it works. Logged out, not.

I checked what  $woocommerce->cart->add_to_cart() returns when I'm a guest (a692c7754699185e4da4ca5e6aedf0f8) but that seems correct, too.

I don't get an error message (Live/Log-Files) or a message (in the cart).
The WC-Option for "Allow checkout for guest" is checked.

**Comment by claudiosmweb** [comment]
LOL xD
Sorry, but impossible support this kind of "custom code".
