### ISSUE TITLE
Add to/update cart major issue. 

### ISSUE THREAD

**Issue by resachris** [woothemes/woocommerce#9484]
Hi there,

I created a website with a woocommerce store. But the store is not working correctly. Cart is acting crazy when not logged in! You can't either add to the cart or to change the quantity. Everything is going smoothly when logged in.

I recorded a vid to show what I am dealing with
https://youtu.be/dYaMoAWdh8w

Please help as my customers are either unable to put a products in the cart or are unable to update the cart (remove, add quantities)  :( It looks like in order to see the proper values/quanities one would have to press the update cart twice. 
That is a major issue for an online store.
I’ve tried disabling all plugins except for woocommerce but it did not help. Tried going back to version 2.47 - no difference. Issue is seen on all browsers (Safari, Chrome, Firefox)

The url: www.rebelsagenda.com

Please help.
Thanks,
Mike

**Comment by gedex** [comment]
Unable to reproduce. Please switch to different theme, default WP theme or Storefront, and report again if issue persists.

**Comment by resachris** [comment]
My issue is fixed. Turned out that my hosting had some kind of a caching option turned on on the server. They turned it off and everything is working smoothly now. 

ps. changing theme did not help and it was one of the first things I did.
