### ISSUE TITLE
Over 30 variations all mix

### ISSUE THREAD

**Issue by Hugo44** [woothemes/woocommerce#9486]
Hello every one, i'm french

On woo commerce about variation, i can just add 30 variations because after, the variations to mix on product page. For exemple, if i have a tee shirt with 3 differents forms and by tee shirt there is 15 colors so I would have 45 variations but me I 'm stuck at 30 after all mix they colors to mix with 3 forms of tee shirt. check this screenshot to better understand. http://hpics.li/7d9ca50

Sorry for my english

Thank you very much for your answers.

Best regards, 

Hugo

**Comment by WPprodigy** [comment]
Hi Hugo44,

It is paginated. So click on the arrows to see the next 30 variations: http://cld.wthms.co/XRao/1TFYeqlT

This is not the place to ask for support though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.

**Comment by Hugo44** [comment]
Thanks you for your express reply WPprodigy.

I may not speak well , I have 30 variations but when I exceed 30. There Is a new page that appears, this. this is not a problem of course. But when I record and I'm going on the product page from 30 there is no longer any sort of changes . to understand I invite you to go on this page http://serrurerie-service-cles.fr/produit/cylindre-ifam-f5s/ . It was in French but you can understand .
For the moment I have just 30 variation, so it's ok. when you go this page, tell me, I will add other variations and you will see the difference before 30 variations and after 30 variation save

Sorry for my english, THANK you very much for your help

**Comment by WPprodigy** [comment]
Hey Hugo44,

I understand that you are having an issue, but this is not the correct support outlet. Refer to the links above to find a way to get support.

**Comment by Hugo44** [comment]
Ok Wp Prodigy i understand " I understand that you are having an issue, but this is not the correct support outlet " but i don't understand " Refer to the links above to find a way to get support Refer to the links above to find a way to get support " ? 

thanks

**Comment by WPprodigy** [comment]
I meant, ask for help in the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page. 

You can also submit a support ticket to WooThemes if you have purchased a premium extension.

**Comment by Hugo44** [comment]
Ok WP P,

Thanks you for your help
