### ISSUE TITLE
Custom variation sorting not working

### ISSUE THREAD

**Issue by vinnyusestrict** [woothemes/woocommerce#9487]
Custom sorting for variable products doesn't work on the front-end, single product, drop-down list. It's forcing alphabetical order, even though the attribute is set to custom ordering. The reason seems to be in lines 1938 to 1947 in includes/wp-template-functions.php

    if ( $product && taxonomy_exists( $attribute ) ) {
        // Get terms if this is a taxonomy - ordered. We need the names too.
        $terms = wc_get_product_terms( $product->id, $attribute, array( 'fields' => 'all' ) );
        
        foreach ( $terms as $term ) {
	        if ( in_array( $term->slug, $options ) ) {
		    echo '<option value="' . esc_attr( $term->slug ) . '" ' . selected( sanitize_title( $args['selected'] ), $term->slug, false ) . '>' . apply_filters( 'woocommerce_variation_option_name', $term->name ) . '</option>';
            }
        }
    }

The `$options` array is sorted correctly by menu_order, but `wc_get_product_terms()` returns the terms in alphabetical order and that's the order the `foreach()` uses as it's looping over `$terms`.

**Comment by mikejolley** [comment]
Not in my tests: https://dl.dropboxusercontent.com/s/2cmlv7qvqg8qwk3/2015-11-02%20at%2009.26.png?dl=0

Thats the order I set; not alphabetical. wc_get_product_terms handles the sorting as well.
