### ISSUE TITLE
Cart subtotal does not indicate tax

### ISSUE THREAD

**Issue by startDaemons** [woothemes/woocommerce#9488]
We have a site with 10% tax, products are entered ex tax and woo is set to show cart prices inclusive of tax. Based on the settings and looking at WC_Cart->get_product_subtotal() the *Total* column should be inclusive of tax but instead it looks like this. The price column includes tax but the total doesn't.

![cart](https://cloud.githubusercontent.com/assets/2549415/10872763/c9953e3c-8154-11e5-8f10-90937d006fb1.jpg)

**Prices Entered With Tax:** no
**Calculate Tax Based On:** Shop base address
**Display Prices During Cart and Checkout:** Including tax

**Comment by mikejolley** [comment]
Likely a template override in your theme. Works fine with core templates: https://dl.dropboxusercontent.com/s/57vka9azn2s0bc3/2015-11-02%20at%2009.22.png?dl=0
