### ISSUE TITLE
Order Status Change Note is Array since 2.4.7

### ISSUE THREAD

**Issue by svenauhagen** [woothemes/woocommerce#9489]
Hi,

order status notes are Array since either 2.4.7 or a PHP update from the weekend.
The problem is in line 2220 in includes/abstracts/abstract-wc-order.php .
The dot after %s in the sprintf 

$this->add_order_note( trim( $note . ' ' . sprintf( __( 'Order status changed from %s to %s.', 'woocommerce' ), wc_get_order_status_name( $old_status ), wc_get_order_status_name( $new_status ) ) ), 0, $manual );

causes the error: 

PHP Notice:  Array to string conversion in wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 2220

Please merge the following fix:

$this->add_order_note( trim( $note . ' ' . sprintf( __( 'Order status changed from %1$s to %2$s.', 'woocommerce' ), wc_get_order_status_name( $old_status ), wc_get_order_status_name( $new_status ) ) ), 0, $manual );

Thanks
Sven

**Comment by mikejolley** [comment]
There is not issue in core with this string - look at your translation instead.
