### ISSUE TITLE
woocommerce order API not return error for out of stock produc

### ISSUE THREAD

**Issue by tkchuah** [woothemes/woocommerce#9490]
I try to add a couple of products into the cart, then go to backend and change one of the product (let say Product A) to be out of stock.

If i were to now try to proceed to checkout, woocommerce correctly flag an error telling me Product A is out of stock and ask me to remove it from cart.

However, if I were to use the WC Rest API (Create an Order), it allows me to go through.

This issue happen on variation product.

**Comment by mikejolley** [comment]
The API handles order creation, but not additional logic/rules and stock checking which the cart has. This is the responsibility of your code. [Check the product first if this is important.](https://woothemes.github.io/woocommerce-rest-api-docs/#products-properties)

@claudiosmweb
