### ISSUE TITLE
Checkout "Comment" section is not working 

### ISSUE THREAD

**Issue by LorianaK** [woothemes/woocommerce#9491]
Hello,

I am working on this site:
https://legendland.hu/wp/      (Shop: https://legendland.hu/wp/porcelanbaba/)

On the checkout page (https://legendland.hu/wp/checkout/) there is a comment section called "Megjegyzés - Csomagautomata nevét kérjük írd ide" this is the original WooCommerce comment section I just modified the language files to Hungarian. 

The problem: I tested the checkout page. In the case of **non PayPal payment**, everything is  **working**. I also wrote something to the comment section and we got it in the e-mail, but if I use **PayPal payment** and write to the **comment section** we get the buyer name, address etc. correctly except the comment information. So **no comment line in the e-mail**.

Thank you for any help,
Loriana

**Comment by mikejolley** [comment]
The buyer note/comment via the PayPal UI is not sent or sent back to WooCommerce. That can only be viewed in the notification you get from paypal. 

This comment field is viewable in the WC order emails or WordPress backend.

**Comment by LorianaK** [comment]
You really misunderstood or did not read properly what I have wrote. I talk about the **WooCommerce Comment section** not the PayPal comment section.
"Instructions to merchant:
The buyer hasn't entered any instructions." 
This is what I've got from PayPal and this is what I am not talk about, I talk about the WooCommerce comment line in the WooCommerce email.

**Comment by mikejolley** [comment]
> This comment field is viewable in the WC order emails or WordPress backend.

It's not sent to PayPal.

**Comment by mikejolley** [comment]
And before asked, PayPal does not let us send it either. Refer to https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/

**Comment by LorianaK** [comment]
![Example](https://legendland.hu/wp/wp-content/uploads/2015/11/example.jpg)

This is what I need. How can I get that line if the buyer uses PayPal? If "PayPal does not let us send it" then why there is a comment section?

**Comment by LorianaK** [comment]
I need that line in the email from WooCommerce not PayPal email. 
In the case of "Cash payment' for example I see that line.

**Comment by mikejolley** [comment]
That line is output in all WC emails - screenshot an example of it being missing for me?

**Comment by LorianaK** [comment]
![example2](https://cloud.githubusercontent.com/assets/15609844/10882556/0b3c7a3c-816c-11e5-9511-ea2f50f84fa5.jpg)

I do not see the comment line. I checked 4 times already. (4 PayPal payments).

**Comment by LorianaK** [comment]
Btw, this is a bug what I have found. I do not know why you closed the topic...

**Comment by mikejolley** [comment]
Which paypal gateway is that?

It's closed because I don't believe it to be a core issue; otherwise I'd be able to reproduce it.

**Comment by LorianaK** [comment]
This is the WooCommerce PayPal payment. There is only one, I enabled it in the WC Settings.

**Comment by LorianaK** [comment]
I solved the problem by myself, deleted the whole Comment section because it's not useful, I can not launch a site with a not working section.

**Comment by mikejolley** [comment]
@LorianaK I tested this with both cheque and paypal orders - in both instances the note was present.
