### ISSUE TITLE
New created Product don't appears in category page

### ISSUE THREAD

**Issue by raphaeldas** [woothemes/woocommerce#9492]
Hi there!

I have problems display new products on the <b>shop</b> page.
As usually I add a new product with picture, information and that stuff. This works fine and the product is visible in the back-end page <b>"products"</b> but not in the front-end site <b>"shop"</b>. I searched through the internet, found some sollution but no one worked for me.

The product should be visible in shop page and search result:

![image](https://cloud.githubusercontent.com/assets/15084829/10886888/832066d6-8184-11e5-9e65-985eb2ab1692.png)

I switched the theme from 3clicks to the default Twenty Fifteen, unfortunately without success.

<i>Funny thing</i>: In the page "shop" where the overview of the categories is, the <b>new product is counted</b>

![image](https://cloud.githubusercontent.com/assets/15084829/10887546/e68dddb8-8187-11e5-9063-048ef28800ae.png)

but not into this specific category (I add a second product, too! so there are missing two products):

![image](https://cloud.githubusercontent.com/assets/15084829/10887564/021f7834-8188-11e5-848b-d6781d6410d5.png)

I tried to refer the product to an other category or a new created category. The product don't appears nowhere. 

Had someone a simular problem, can somebody help me?
Thanks in advance! And sorry for bad english :-P

**Comment by claudiosmweb** [comment]
Tested and works fine.
Maybe is cache on your website.

**Comment by raphaeldas** [comment]
now it works! i temporary deactive the Plugin WPML Multilanguage CMS, <b>all</b> the products appeare, then reactive WPML Plugin, all product are still displayed. 
So, the problem is with WPML, hope they release a bugfix soon. 

thanks!
