### ISSUE TITLE
Translation "Hi there. Your order on %s has been partially refunded" not working

### ISSUE THREAD

**Issue by dagoebel** [woothemes/woocommerce#9493]
See 

templates/emails/customer-refunded-order.php

printf( __( "Hi there. Your order on %s has been partially refunded.", 'woocommerce' ), get_option( 'blogname' ) );

Should be single quotes instead of " " in order to make transtion working.

Just tried it by replacing the double quotes with single quotes -> works.

**Comment by claudiosmweb** [comment]
That does not make any sense, PHP has no problem with that.
But I honestly prefer single quotes.
