### ISSUE TITLE
Attributes Tab Not Loading Correctly

### ISSUE THREAD

**Issue by rockytin117** [woothemes/woocommerce#9495]
When trying to view the Attribute tab for a product, the content doesn't load correctly.  All of the content gets shifted to the left and cut off on the screen.  I thought it was a browser issue, but I tried in Safari, Firefox and Chrome with all the same results as show in the screenshots below.  Changing product types hasn't help either.

<img width="1280" alt="screen shot 2015-11-02 at 9 36 18 pm" src="https://cloud.githubusercontent.com/assets/15619918/10895757/c3829dc4-81ad-11e5-9385-03d75a972475.png">
<img width="1280" alt="screen shot 2015-11-02 at 9 59 53 pm" src="https://cloud.githubusercontent.com/assets/15619918/10895756/c3823960-81ad-11e5-98a9-d80c4d2ce4cf.png">
<img width="1280" alt="screen shot 2015-11-02 at 10 01 02 pm" src="https://cloud.githubusercontent.com/assets/15619918/10895755/c3804510-81ad-11e5-9179-d3e9bd4321dc.png">

**Comment by mikejolley** [comment]
This is a javascript error on your page, most likely from another plugin you have installed.

Right click the page and inspect. Fine the console tab.  This will list errors. Or just disable other plugins until the issue vanishes.
