### ISSUE TITLE
Coupons - Unable to select products 

### ISSUE THREAD

**Issue by Capitalplanning** [woothemes/woocommerce#9496]
WooCommerce coupons

When creating a coupon there is an option to select a product where we can create a coupon a particular product. However, the field is unable to show the list of products that we have in the shop.

Can you confirm if this is a bug, and if this bug would have been resolved in the latest WordPress update?

**Comment by claudiosmweb** [comment]
Chrome > View > Developer > Javascript console. go ahead and look at the errors. When it jumps to the top, or events fail to fire, it's usually a javascript error on your page.

**Comment by mikejolley** [comment]
Just to add, this is a search field. It won't show any results until something is typed. Check the console as suggested. This is working fine our side.
