### ISSUE TITLE
Woocommerce crashing site

### ISSUE THREAD

**Issue by goodgrub** [woothemes/woocommerce#9497]
When I activate the plugin I get the error 
Fatal error: GeoIP API: Error traversing database - perhaps it is corrupt? in /home/content/p3pnexwpnas02_data03/42/2669442/html/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1535

I cannot seem to find anything about how to fix this and I contacted my hosting/server provider and made sure everything was correct on their end.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/issues/9501
