### ISSUE TITLE
Bug with variations

### ISSUE THREAD

**Issue by 418Design** [woothemes/woocommerce#9498]
Trying to narrow this down more but this is the first time I have reported a bug and I am merely a front end developer.

Problem: I can create and add attributes and variations but once added the 'Remove' link doesnt do anything and the bulk edit tool, the dialog box to enter the info you want to edit fails to pop up at all. The meta box seems to reload twice in quick succession though when you do press Go.

I am running a fully up to date Wordpress website and the only plugin active is Woocommerce. Hello Dolly and Askimet are inactive but they are on there.

I have tried with both up to date Wordpress default themes and my own bare bone (css and a few divs) theme.

I have checked the Woocommerce Status page, nothing in red and nothing in the log tab.

Searched Google a bit and cant find anyone having the same issue.

Only thing I can think of and I am currently checking, I think these are Cpanel installed Wordpress sites. Manually uploading and installing a Wordpress now which I have just downloaded from wordpress.org.

**Comment by 418Design** [comment]
Now tried with a fresh manually installed copy of Wordpress and still no luck. Variations are just broken.

Normally use Chrome but using Firefox clicking the Remove link jumps me back to the top of the page.

**Comment by 418Design** [comment]
Just to check I am not being totally stupid this is how I setup a product.

Add title,
Select Product Category,
Add short description
Add image
Change to Variable Product
Add Attributes
Add Variables
Attempt to edit variables.

If I set prices manually that does seem to work. I think.

**Comment by mikejolley** [comment]
Chrome > View > Developer > Javascript console. go ahead and look at the errors. When it jumps to the top, or events fail to fire, it's usually a javascript error on your page.

**Comment by 418Design** [comment]
I ended up installing WAMP and it worked fine running locally.

Weird thing is I then went to report it to my hosting company and it was all working fine and still is.

Had 3 people look over it so I know I am not going mad. It didnt work for a good 4 or 5 hours and then it started working.

Is there some weird caching at play that I dont know about or something?

**Comment by claudiosmweb** [comment]
Have you checked the console of your browser?

**Comment by 418Design** [comment]
@claudiosmweb that was the first place I looked and suprisingly for a wordpress page there weren't any errors for once.

Its behaving ok now. Its like there was a cache at play that I wasnt aware of so hadnt cleared?

**Comment by mikejolley** [comment]
Possibly cache via something such as cloudflare.
