### ISSUE TITLE
Can Someone help me about this problem?

### ISSUE THREAD

**Issue by zensatsu** [woothemes/woocommerce#9499]
I want to make my website login menu like this before the user logged in.
![login menu](https://cloud.githubusercontent.com/assets/15625610/10903508/0a06ade6-823d-11e5-94ba-5afb2f06a681.png)

And i want to make the menu like this after the user logged in 
![logged in](https://cloud.githubusercontent.com/assets/15625610/10903514/1a377e20-823d-11e5-9b5c-16f2877ad8fa.png)

it looks like to make it auto change text for them. And i have the code too. but i don't know how to fix it and put it on my themes " Divi "

 <?php if ( is_user_logged_in() ) { ?>
<a href="<?php echo get_permalink( get_option('woocommerce_myaccount_page_id') ); ?>" title="<?php _e('My Account','woothemes'); ?>"><?php _e('My Account','woothemes'); ?></a>
<?php }
else { ?>
<a href="<?php echo get_permalink( get_option('woocommerce_myaccount_page_id') ); ?>" title="<?php _e('Login / Register','woothemes'); ?>"><?php _e('Login / Register','woothemes'); ?></a>
<?php } ?>

**Comment by technofreaky** [comment]
@zensatsu  Try this plugin. to change menu based on users / visitor

https://wordpress.org/plugins/nav-menu-roles/

**Comment by mikejolley** [comment]
^ And please don't post support questions on a bug tracker

**Comment by zensatsu** [comment]
Thank you so much Sir.
Btw, can you help me something?
I want to change text " My Account " on my menu when the user logged in and
the text will " Login / Register " when the user not logged in.
I am using code from Github too. but the themes doesn't support.

 <?php if ( is_user_logged_in() ) { ?>
  <a href="<?php echo get_permalink(
get_option('woocommerce_myaccount_page_id') ); ?>" title="<?php _e('My
Account','woothemes'); ?>"><?php _e('My Account','woothemes'); ?></a>
 <?php }
 else { ?>
  <a href="<?php echo get_permalink(
get_option('woocommerce_myaccount_page_id') ); ?>" title="<?php _e('Login /
Register','woothemes'); ?>"><?php _e('Login / Register','woothemes'); ?></a>
 <?php } ?>

Can you help me to resolve that, please?
