### ISSUE TITLE
An excessive number of transients being created

### ISSUE THREAD

**Issue by samheavyside** [woothemes/woocommerce#9500]
I have noticed that the wp_options table was at roughly 1M Rows and I thought that seemed a little odd! I took measures to delete all the transients in the table and brought it down to only 1200 or so rows! (almost 700MB down to 2.5MB). 

I then kept an eye on it over the next hour or so and noticed that slowly but surely - maybe 50 -100  new rows per minute i would estimate - the table was filling back up with transients, Majority of which are named something along the lines of "transient_wc_var_prices".

I only have 16 products in my store and while a few of them have upto 5 variations, It seems odd that there are literally thousands of transients being created every hour!

Is this normal behaviour (I hope not as it brought my server to a grinding holt having such a rediculously large options table) or is there something I can investigate further as to why so many are constantly being created?

Thanks

**Comment by claudiosmweb** [comment]
No worry, will be improved on WooCommerce 2.5.

**Comment by mikejolley** [comment]
FYI to add, right now you get a transient for each unique request, per product version.  So for example, if a user with XYZ taxes views a product, they get a different transient from a person with ABC taxes.

2.5 uses a single transient to avoid spamming the options table.

**Comment by samheavyside** [comment]
Ok, that makes sense. Our site gets roughly 3-5K unique visitors per day. Is it ok to periodically delete such transients to keep the table at a manageable size? Thanks :)

**Comment by mikejolley** [comment]
Yes, do so from WooCommerce > System status > tools
