### ISSUE TITLE
Change display text Login / Register and My Account

### ISSUE THREAD

**Issue by zensatsu** [woothemes/woocommerce#9502]
Someone can help me, please? How to change Login / Register into My Account text while users logged in? i've used code from GitHub too. but the themes doesn't support. Need your advice about plugin or else please.

**Comment by mikejolley** [comment]
As I said in your last issue, this is not a support area. Bug reports **only**. https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Use a plugin to offer conditional menu items.
