### ISSUE TITLE
Woocommerce terms & condition popup without content slider and closure buttom (X)

### ISSUE THREAD

**Issue by FEDEUBER** [woothemes/woocommerce#9503]
Hi,
I just installed the Woocommerce terms & condition popup plugin by DualCube. 
I have some issues: 
-the pop up page doesn't have a slider so i can't read all the text
-there is no buttom X to close the pop-up window
-the css style of the text is not right (as I set up in the page)
can you help me?
Thanks in advance.
Fede
![bug](https://cloud.githubusercontent.com/assets/15358541/10908912/728c599a-8235-11e5-8d51-e9264e6ff0f0.png)

**Comment by mikejolley** [comment]
This is a bug tracker for core - we have no affiliation with DualCube.

**Comment by FEDEUBER** [comment]
Oh thank you... Is there a woothemes plugin I can install?

**Comment by mikejolley** [comment]
Why not report the issue to DualCube?

**Comment by FEDEUBER** [comment]
Yep, already done. Thank you.
