### ISSUE TITLE
Fatal error: GeoIP API: Error traversing database - perhaps it is corrupt? in /home/content/p3pnexwpnas03_data03/48/2428948/html/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1535

### ISSUE THREAD

**Issue by bborden51** [woothemes/woocommerce#9504]
Just a heads up.  Got this error on my Ipad and Android phones this morning when trying to access any other page on my website except the home page.  Website was working fine on my Windows laptop.  Fixed error by changing "Default Customer Address" under Woocommerce Settings General to "No Address" from "Geolocate".

Fatal error: GeoIP API: Error traversing database - perhaps it is corrupt? in /home/content/p3pnexwpnas03_data03/48/2428948/html/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1535

**Comment by mikejolley** [comment]
Please read other issues before submitting https://github.com/woothemes/woocommerce/issues/9501
