### ISSUE TITLE
No differentiation between parent category and child / subcategory

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9505]
Body class for parent categories, `category-has-children`, would be something to latch on to.

The short point here is 'How can you target the subcategory pages?'

**Comment by mikejolley** [comment]
Add a body class via the WP filters by seeing if the currently displayed category has a parent.

**Comment by yratof** [comment]
Incase this comes up again, this is the function I'm using to add a custom class
```
add_filter( 'body_class', function ( $classes ) {
  $term = ( get_term_by( 'slug', get_query_var('term'), get_query_var('taxonomy') ) );
  if ( !$term )
    return $classes;
  if ( 'subcategories' == get_metadata( 'woocommerce_term', $term->term_id, 'display_type', 1 ) ) {
    $classes[] = 'display-subcategories';
  }
  return $classes;
} );
