### ISSUE TITLE
feature request: woocommerce_wp_select2() function

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#9510]
WC has a handful of prepackaged functions for creating admin inputs. One that I'd like to add would be one that uses WC's select2 script... for pages/posts/products/categories and the like. I will try to take a stab at it if I get some time.

**Comment by claudiosmweb** [comment]
Maybe this can be part of #6361

**Comment by helgatheviking** [comment]
Could be, but could also be possible much sooner than revamping the whole settings API. that issue looks like it has been around a while..  is it on the 2.5 roadmap?

**Comment by claudiosmweb** [comment]
Most likely 2.6

**Comment by mikejolley** [comment]
#6361 will be 2.6, and this is related. Although I think all you need to do now is use a select box and add a CSS class.

Add notes to #6361 if more discussion is needed please. Keeping github clean :)
