### ISSUE TITLE
Cannot get price including tax

### ISSUE THREAD

**Issue by tigerstrikemedia** [woothemes/woocommerce#9511]
I am working on an issue where the price is always displayed without tax when the user is logged in and is VAT exempt. ( store is based in Australia so VAT is irrelevant. )

in the function `get_price_including_tax` (`abstract-wc-product.php` line `804`) the following occurs..

``` php
if ( ! empty( WC()->customer ) && WC()->customer->is_vat_exempt() ) {
	$base_taxes         = WC_Tax::calc_tax( $price * $qty, $base_tax_rates, true );
	$base_tax_amount    = array_sum( $base_taxes );
	$price              = round( $price * $qty - $base_tax_amount, wc_get_price_decimals() );
}
```

why would the function to get prices including tax strip them out??  This is completely ignoring any settings in wp-admin regarding display inclusive or exclusive of tax.

**Comment by mikejolley** [comment]
This is the price including tax relative to the user. If the user has no tax to pay, it is correct to strip that out. The user doesn't need to see the tax amount. This is intended.
