### ISSUE TITLE
Uninstall routine deletes options that belong to other extensions and plugins

### ISSUE THREAD

**Issue by om4james** [woothemes/woocommerce#9512]
WooCommerce's uninstall routine automatically deletes **all** wp_options that begin with `woocommerce_`:

`$wpdb->query("DELETE FROM $wpdb->options WHERE option_name LIKE 'woocommerce\_%';");`

Ref: https://github.com/woothemes/woocommerce/blob/master/uninstall.php#L46

There are a **lot** of official WooCommerce extensions (and presumably other WooCommerce plugins) that prefix their options with `woocommerce_extensionname_`.

For example, WooCommerce Subscriptions uses `woocommerce_subscriptions`.

Table Rate Shipping uses `woocommerce_table_rate_`.

Should WooCommerce only be deleting option records that it creates, rather than blindly deleting all options that are prefixed with `woocommerce_`?

Presumably the query above was used so that uninstall.php doesn't need to have hard-coded list of options that need to be deleted.

I understand the convenience of that, however I don't think WooCommerce should be deleting options that are created by other plugins.

**Comment by mikejolley** [comment]
@om4james Since WooCommerce extensions require WooCommerce to actually function, what is the downside here if WC is removed?

**Comment by om4james** [comment]
Fair question @mikejolley!

It just feels odd/unexpected that one plugin's uninstall routine will delete data that is created/managed by other plugins.

Each plugin/extension should be responsible for uninstalling/deleting its own data.

Perhaps the `admin.php?page=wc-status&tab=tools` page could be updated to explain that this occurs?

For example:

`Remove All Data`
`This tool will remove all WooCommerce, Product and Order data when using the "Delete" link on the plugins screen.`

becomes

`Remove All Data`
`This tool will remove all WooCommerce, Product and Order data when using the "Delete" link on the plugins screen. It will also remove settings/options for most WooCommerce Extensions.`

And ideally https://docs.woothemes.com/document/installing-uninstalling-woocommerce/#section-2 should be updated too.

**Comment by Kenshino** [comment]
Or we could look at it as - WooCommerce helps to clean up other WooCommerce plugins. We have this issue with WordPress.org plugins, most of them don't clean up after themselves.

Not all plugins are created equal.

I support the idea of just making the text clearer :)

**Comment by mikejolley** [comment]
Ok we can do that. Listing all options we used would be some task.
