### ISSUE TITLE
API returns order containing line items where product id set to 0

### ISSUE THREAD

**Issue by zeeshan-m** [woothemes/woocommerce#9513]
I was using the V2 API to get a list of orders and parse through them when I noticed this:

                    [id] => xxxx
                    [subtotal] => 0.00
                    [subtotal_tax] => 0.00
                    [total] => 0.00
                    [total_tax] => 0.00
                    [price] => 0.00
                    [quantity] => 1
                    [tax_class] => 
                    [name] => xxxxxxxx
                    [product_id] => 
                    [sku] => 

Product ID was left as blank for this line item. This order contained multiple line items, and this is the only line item that had it's product_id set to nothing. Any ideas why? I did rename the item in question, if that makes a difference.

**Comment by claudiosmweb** [comment]
Because the product in question does not exist yet, it should have been deleted:

https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-orders.php#L215-L225

**Comment by zeeshan-m** [comment]
Sorry, not sure what you mean? What do you mean the product doesn't exist yet.

**Comment by claudiosmweb** [comment]
The Product doesn't exist anymore.

**Comment by zeeshan-m** [comment]
Ah, I see. Is it possible to see what the product ID was set to prior to the product deletion?

**Comment by claudiosmweb** [comment]
Nop

**Comment by zeeshan-m** [comment]
Great, thank you. :+1:
