### ISSUE TITLE
Fatal error: GeoIP API

### ISSUE THREAD

**Issue by nvvavolleyball** [woothemes/woocommerce#9514]
I was getting this error on my wordpress site www.virginiavolleyballcenter.com I deactivated WooCommerce through FTP and the site is back to work. Any updates needed on your site before I can reactive the plugin?

**Comment by WPprodigy** [comment]
Hey @nvvavolleyball,

This is likely a conflict issue with another theme/plugin. Try deactivating all plugins and switching to a default theme. Then enable WooCommerce. Your site should be working fine at this point, so slowly enable plugins until you find the conflict.

This is not the place to ask for support. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.

**Comment by claudiosmweb** [comment]
Closed in favor of #9501
