### ISSUE TITLE
Implement variation sorting during bulk variation creation

### ISSUE THREAD

**Issue by jkohlbach** [woothemes/woocommerce#9515]
Variations created using the bulk variation creation tool are created in randomised order.

Sure, you can drag and drop to sort them, but try doing that over a big catalog of products and anything but efficient (try headache inducing...)

Here's the original Idea Suggestion for this issue which has left users frustrated and no closer to solving this problem. You can see some people are quite passionate about this and not happy with the suggested workaround:

http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/2650776-be-able-to-sort-variations-of-variable-products-in

Happily, Elliot Condon (of ACF plugin) made a suggestion to override the array_cartesian function in /includes/class-wc-ajax.php, his fix basically sorts the variations by attribute key which seems to make sense.

Here's his GIST which contains the fixed function:
https://gist.github.com/elliotcondon/c94abec50dc26ac065c6

If this function isn't being used anywhere else and this sorting won't cause a problem elsewhere, I propose this gets integrated into core as is.

**Comment by mikejolley** [comment]
For the record, the order of the variations in the backend makes absolutely no difference whatsoever to the frontend/display of attributes on the frontend.

**Comment by jkohlbach** [comment]
@mikejolley Thanks.. your comments are true of course, but why is that so? Why make the variations tab sortable at all in that case?

All the clients I implement WC for are extremely confused as to why and how the front end sorting works. They expect it to be on the variations tab order... thats probably out of the scope of this Issue, but has this been investigated?

**Comment by claudiosmweb** [comment]
@jkohlbach "variations tab order" make sense just when you have one attribute. How should be ordered when used two or more attributes, since this will create selects for each one?

Variations are not ordered on the front-end, but attributes are ordered... And have settings for it on attributes page:

![screenshot from 2015-11-05 02-13-08](https://cloud.githubusercontent.com/assets/1264099/10959692/c615a048-8362-11e5-9433-e6b8a8e2839d.png)

**Comment by jkohlbach** [comment]
@claudiosmweb I think we got sidetracked a bit on this, lol. My original issue above has nothing to do with the front end sorting, Mike just raised it as an example of what people were complaining about in that idea suggestion post.

I do think it would be nice to provide a better interface for this front end sorting though, it confuses lots of users (speaking as a developer that trains clients how to use Woo).

But that is probably something to be raised in another Issue. I would raise it myself but I don't really have a good alternative suggestion!

The original problem is to do with the bulk creation not sorting the generated variations properly (they'd just end up in whatever order it deemed fit at the time) and it looks like @mikejolley may have already implemented it in 2.5.0 beta. 

Thanks Mike! Should this be marked on the 2.5.0 milestone?

**Comment by robert1112** [comment]
Is this integrated with Woo?

**Comment by jkohlbach** [comment]
The original request was implemented afaik. Bulk creation is now sorted in logical order on insertion.

**Comment by robert1112** [comment]
@jkohlbach  That is awesome. Thanks for your confirmation. Have a good day/ night 👍
