### ISSUE TITLE
No user tagged on order notes

### ISSUE THREAD

**Issue by BeeHealthLimited** [woothemes/woocommerce#9516]
When updating an order via wp-admin/post.php the order notes save who preformed the action, however when using the check(tick) on edit.php?post_type=shop_order to change order status to complete the order notes do not save who.

I've tried to look through the code to resolve this myself but have come up empty.

Any help is appreciated, thanks.

**Comment by mikejolley** [comment]
Looks fixed in master - just tested successfully.
