### ISSUE TITLE
Geolocate (with page caching support) causes theme customize preview to recursively embed itself.

### ISSUE THREAD

**Issue by CurtisL** [woothemes/woocommerce#9521]
Enable Geolocate (with page caching support) for the Default Customer Address setting.
Then go to Appearance > Customize to witness infinity.

Page loads with the customize controls and a customize preview iframe. The iframe will reload and contain the current page, which contains an iframe that does the same, and that iframe does the same... ad infinitum.

Wordpress: **v4.3.1**
WooCommerce: **v2.4.8**
Tested on a fresh WP and WC install with no plugins.

**Comment by claudiosmweb** [comment]
Fixed in https://github.com/woothemes/woocommerce/commit/fde904b27a366169117e3b2da7f764a1de29628a
