### ISSUE TITLE
Filter for display name on order_title in class-wc-admin-post-types.php

### ISSUE THREAD

**Issue by Einkoro** [woothemes/woocommerce#9522]
We need to identify users by the option set in "Display name publicly as" from the user profile when reviewing orders, and fall back to company in the billing address ideally, this would be easiest to accomplish if a filter was added:
https://github.com/woothemes/woocommerce/blob/5893875b0c03dda7b2d448d1a904ccfad3cdae3f/includes/admin/class-wc-admin-post-types.php#L741

Use case is each company, a vendor, has one account and the nickname contains the company name we'd like to see rather than displaying users by first/last name. Currently we have to open the order to see the display name rather than browsing the order list.

**Comment by mikejolley** [comment]
Since this will require custom handling anyway for your specific use case, rather than filtering on this column, add a new column, then choose to show via the screen options tab. 

Adding columns requires functions hooked into:

- manage_shop_order_posts_custom_column
- manage_shop_order_posts_columns

See https://codex.wordpress.org/Plugin_API/Filter_Reference/manage_posts_columns

**Comment by haroldkyle** [comment]
Simply adding a filter to the order title (specifically the username) would make sense. It's oddly inflexible the way the order title is hard coded to the user data (or, when the buyer is not logged in and the order completely lacks a first/last name, the order's business name).

Our installation services primarily other businesses, whose employees log in as users. Displaying the logged-in username makes no sense on our end--our staff bills, picks, and packs for the business. If the order from Acme Inc., why show purchasing agent John Doe who was logged in? 

It sounds like you're suggesting we add a new column, but a filter is a much less invasive solution. I'm still left with the existing 'order_title' and really only want to swap out the name. I see there are already filters on other columns, like 'order_items' and 'order_date'--and this seems similar to those situations.
