### ISSUE TITLE
Woocommerce get products from another Webservice API and show.

### ISSUE THREAD

**Issue by YNaVN** [woothemes/woocommerce#9524]
Hello,

I have 1 web server supply one API for get Products, Products Information, ….(A)
And my website using Woocommerce(B). Now, Can I use REST API for get Products from that webserver(A)
And how I show Products from that API in my website (B).
Really thanks, and waiting for your answers.

**Comment by claudiosmweb** [comment]
![screenshot from 2015-11-05 12-09-47](https://cloud.githubusercontent.com/assets/1264099/10970495/203a2bf4-83b6-11e5-8e10-406441fb6c4a.png)
