### ISSUE TITLE
(low priority) Missing UI setting for woocommerce_enable_order_comments 

### ISSUE THREAD

**Issue by neonics** [woothemes/woocommerce#9529]
When searching for a way to disable order notes (`woocommerce_enable_order_notes_field` filter), I found that the value is retrieved from the database using `get_option( 'woocommerce_enable_order_comments', 'yes' )` (and this seems to be the only use for that setting).

However, there is no code in WooCommerce that allows to change this setting. I would have expected to find it under WooCommerce > Settings > General (as there is no Orders tab).

It's easy enough to work around this using custom filters, but since an option is retrieved from the DB, it would be nice to be able to change it using the WP back end. 

(Also, the names (`...notes` and `..comments`) are a bit misleading, since only a single note will be stored in the order `post_excerpt` field.)

**Comment by WPprodigy** [comment]
There used to be a setting for disabling this field. It has since been removed. The database entry still exists for backwards compat I believe.

If you want, you could just use update_option() to change the value: https://codex.wordpress.org/Function_Reference/update_option

**Comment by claudiosmweb** [comment]
This is a deprecated option. It's still used to ensure that works for those who use this option in the past to deactivate.
For now you should use the `woocommerce_enable_order_notes_field` filter.

You can disable using:

```php
add_filter( 'woocommerce_enable_order_notes_field', '__return_false' );
```
