### ISSUE TITLE
Appearance is not showing up within Dashboard

### ISSUE THREAD

**Issue by Kekay69** [woothemes/woocommerce#9530]
Hi,
Someone set the Theme WooCommerce before. Client is asking me to add a menu bar at the top of her site. But, I don't have the option to select display menu within Appearance.  Any advice would be much appreciate it.

Thank you,
-QuiQue

**Comment by WPprodigy** [comment]
Hello,

This is not the place to ask for help with that. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce). This is something actually related to your theme though, so you should reach out in your theme's support forums.
