### ISSUE TITLE
Saving variation information does not change the product update date

### ISSUE THREAD

**Issue by tkchuah** [woothemes/woocommerce#9531]
Go to variation, update the price of one of the variation follow by save doesnt update the Post/Product "Last edited on.. " date ?

However, manually press on "Update" on the product will reflect that.

Is this an expected behaviour ? Shouldn't saving product data also consider as update too ?

**Comment by mikejolley** [comment]
Not necessarily as you're not saving the product, you're saving a variation inside.

**Comment by mikejolley** [comment]
And as this is a child post, not the parent, post_modified should not be updated.

Use the main update post button to save both variations and the parent.
