### ISSUE TITLE
fatal error message

### ISSUE THREAD

**Issue by escapeimagery** [woothemes/woocommerce#9533]
Assistance required Please
Theme Avada current update Version 3.8.8
woocommerce current update Version 2.4.8 
WordPress 4.3.1

Error message Fatal error: GeoIP API: Error traversing database - perhaps it is corrupt? in /home/content/p3pnexwpnas03_data01/17/2242817/html/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1535

this error persists despite all plugins being deactivated.
Only allows website to load if woocommerce current update Version 2.4.8 is deactivated.

Plugin reinstalled no change.

**Comment by escapeimagery** [comment]
Please be aware this also persists when another theme is used

**Comment by WPprodigy** [comment]
Related: https://github.com/woothemes/woocommerce/issues/9501
