### ISSUE TITLE
WC New Order Hook Not Working When  Simplify Commerce is active

### ISSUE THREAD

**Issue by technofreaky** [woothemes/woocommerce#9536]
I am unable to hook 
`woocommerce_checkout_update_order_meta` 
and
 `woocommerce_new_order`

 when **Simplify Commerce**  active.

**Comment by roykho** [comment]
If the order is able to create successfully, both those hooks will trigger.  I have tested this with Simplify active and it works correctly.  So I am assuming something on your site is preventing the order from being created.  Check for conflicting plugins..etc.

**Comment by technofreaky** [comment]
@roykho thanks for your fast reply. yes your are right it was my big mistake. sorry :( i feel very bad.
