### ISSUE TITLE
[WP 4.4] Product type filter stopped work

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#9537]
![screenshot from 2015-11-06 14-05-18](https://cloud.githubusercontent.com/assets/1264099/11001883/dea7d1a6-8490-11e5-9cc4-6047d24b0acd.png)

**Comment by BFTrick** [comment]
Could also be related to #9608

**Comment by claudiosmweb** [comment]
@BFTrick for sure :)
Have something wrong in your `actions`.

**Comment by mikejolley** [comment]
@claudiosmweb @BFTrick No longer occurring in 4.4 beta 4.
