### ISSUE TITLE
[WP 4.4] Shipping Classes admin page access issue

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#9538]
On `wp-admin/edit-tags.php?taxonomy=product_shipping_class&post_type=product`

![screenshot from 2015-11-06 14-17-04](https://cloud.githubusercontent.com/assets/1264099/11001918/17e23a38-8491-11e5-8ad0-3513c286bb54.png)

**Comment by roykho** [comment]
I think if we flag this to true https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-post-types.php#L149

And remove the add_submenu_page, it will work.  I am not sure why we did it this way in the first place?  Perhaps it was because of positioning the sub menu under products?
