### ISSUE TITLE
Product variations should be able to be displayed as a radio buttons

### ISSUE THREAD

**Issue by nathansh** [woothemes/woocommerce#9540]
It'd be really beneficial for theming if product variations could be displayed in `radio` buttons with labels. This is far easier to style than dropdown since you can use a common [custom radio element](https://css-tricks.com/snippets/css/custom-radio-buttons) technique. I noticed that `wc_dropdown_variation_attribute_options` is used to print the `select` element. Perhaps this template function could be named differently and have an argument for element type, with `select` and `radio` as options.

**Comment by roykho** [comment]
You can overload that function.  I believe the majority will still want dropdowns as default.  So for edge cases/customizations, just overload the function to do what you want.

**Comment by nathansh** [comment]
@roykho I agree dropdowns are a good default. It'd be a really valuable option to add those for those that want it. Are you aware of any examples of overloading?

**Comment by roykho** [comment]
It is not good practice to put every option imaginable just because some people might want it as that will bloat the code/plugin.  Only if there are significant use cases for something is when we can decide to add or not.

You can declare this function wc_dropdown_variation_attribute_options in your functions.php file of a child theme and add in your own radio style html.  Refer to the original function code for what you need to make it work.

**Comment by nathansh** [comment]
@roykho in the context of WordPress it'd make a lot of sense, and be consistent with what WordPress theme developers are used to from functions like [wp_get_archives](https://codex.wordpress.org/Function_Reference/wp_get_archives) where a format option is available.

**Comment by mikejolley** [comment]
Radio's don't work well with many or multiple options. Select boxes are the sensible option, regardless of styling.

Also bare in mind, if we added a new style *every* theme dev would need to accommodate for them which is more work.

**Comment by nathansh** [comment]
@mikejolley Radios are fantastic for multiple options, and let you do things like this with only CSS: 
![screenshot 2015-11-06 11 17 08](https://cloud.githubusercontent.com/assets/894613/11006317/060bee58-8478-11e5-8bf8-011bf316d3dc.png)

**Comment by nathansh** [comment]
I overwrote the `wc_dropdown_variation_attribute_options` function in `functions.php` and got the markup I wanted without much trouble, but the JS that checks for a variation match and displays the add to cart button accordingly only responds to `select`. So close!

**Comment by roykho** [comment]
Then you need to get creative such as copy the code from add-to-cart-variation.js and enqueue that in your theme but remember to add the dependency of 'wc-add-to-cart-variation' so that your copied code loads after that script.  Then change the select in the script to whatever you need it to be.

**Comment by mikejolley** [comment]
cc @jameskoster ^

**Comment by carmolim** [comment]
@nathansh could you share the overwrote function you created?

**Comment by gerdneuman** [comment]
@roykho Unless there are more than 5 options, radio buttons should always be the default. As https://uxplanet.org/mobile-ecommerce-product-details-28feba377a55#.47mme8jsg puts it:

> Product description should be easy to skim (get a general overview) and scan (find a specific info).

(see the image at "Incomplete product details may lead to user frustration" there and imagine this with a dropdown which initially just shows "Select an option").

Funny sidekick ;) Woocommerce itself does not use (rightly so) a dropdown for its variations, see https://woocommerce.com/products/woocommerce-subscriptions/

![2016-08-22 12_36_54-woocommerce subscriptions - woocommerce - firefox developer edition](https://cloud.githubusercontent.com/assets/12525563/17851995/29d3c3d4-6865-11e6-8851-0a6822f07328.png)

**Comment by lukecav** [comment]
Seems like there is a plugin solution for this, that is updated.
https://github.com/8manos/wc-variations-radio-buttons
