### ISSUE TITLE
Hook to change cart item URL

### ISSUE THREAD

**Issue by radykal** [woothemes/woocommerce#9541]
Hey devs,

there is a hook to change the thumbnail of a cart item:

```php
//cart.php
$thumbnail = apply_filters( 'woocommerce_cart_item_thumbnail', $_product->get_image(), $cart_item, $cart_item_key );
```

But I also would like to change the URL of some cart items in the cart dynamically. So I tried to hook into the 'post_type_link' filter to change the URL. Thats my approach, but the find_in_cart_product() method of cart class returns an empty string:

```php
add_filter('post_type_link', array(&$this, 'change_cart_item_url'), 100, 2);

public function change_cart_item_url( $post_link, $post ) {

    if( is_cart() ) {
        $key = WC()->cart->find_product_in_cart($post->ID);
        var_dump($post->ID, $key);
    }

    return $post_link;
}
```

So would it maybe possible to add also a hook to change the cart item URL in future. Something like this in the loop of the cart.php.

```php
$cart_item_url = apply_filters( 'woocommerce_cart_item_url', $_product->get_permalink( $cart_item ), $cart_item, $cart_item_key );
```

**Comment by claudiosmweb** [comment]
Use `post_link` from `get_permalink()`: https://developer.wordpress.org/reference/functions/get_permalink/

**Comment by radykal** [comment]
The filter `post_link` is only be used for posts. 
See: 	https://developer.wordpress.org/reference/hooks/post_link/

Actually I would like to know if you maybe add a custom hook for the item url in the cart in a future release of wc?
