### ISSUE TITLE
[REST API] Delete / generate all variations

### ISSUE THREAD

**Issue by dolfim** [woothemes/woocommerce#9542]
Hi,

In the GUI we have the action "Delete all variations" and "Create variations from all attributes".
Is there an equivalent via REST API?

What is something like this doing?
```python
data = {
    "product": {
        'attributes' : [{
            'name': 'Color',
            'variation': False,
        }]
    }
}
r = wcapi.put("products/12717", data)
```
Is it deleting all variations and generating them again without the ```Color``` attribute?

**Comment by claudiosmweb** [comment]
Nop, maybe in a future version.

Suggestions logged in our roadmap:

- https://trello.com/c/7l6JJ2Zi/81-api-delete-all-variations
- https://trello.com/c/G1AsaPtL/82-api-create-variations-for-all-attributes
