### ISSUE TITLE
login link and coupon link with no action

### ISSUE THREAD

**Issue by nanda13ap** [woothemes/woocommerce#9544]
login link and coupon link when clicked lead to nowhere, they do nothing on checkout page.

I tried to activate a diferrent default theme and it works on 2014 but not on 2015

**Comment by roykho** [comment]
It works fine on my test.  Check to make sure you're not having JS errors from a plugin.

**Comment by nanda13ap** [comment]
This is the first thing that I check.

**Comment by roykho** [comment]
Check your browser console for JS errors.

**Comment by nanda13ap** [comment]
Like I said before, this is the first thing that I check.
There are no errors.

Could u tell me the name of the js file responsible for opening the link ? then I could try to see if there is a reference on the page to this file.

Thank you for your help.

**Comment by roykho** [comment]
Post URL to your site.

**Comment by nanda13ap** [comment]
http://www.test.greenregimen.com/shop/
http://www.greenregimen.com/shop/

I have the test enviroment to try to fix his error then updating it to my production enviroment.

Also, the woocommerce has its last version updated on the test enviroment

**Comment by roykho** [comment]
Please switch to 2015 theme on test and turn all plugins off except WC.

**Comment by nanda13ap** [comment]
it still doesnt work.

but now there is this error on the console: 

Uncaught ReferenceError: templateUrl is not defined(anonymous function) @ back-to-top.js:11

**Comment by roykho** [comment]
Did you make sure you're using the latest version of 2015?  Check for updates...etc.

**Comment by nanda13ap** [comment]
I just checked.
It is the lases version.

If if it helps 2014 theme that works is not the latest version.

**Comment by roykho** [comment]
Your 2015 theme is not official WP theme.

**Comment by nanda13ap** [comment]
Can you give me more information about how you can see that ?

**Comment by roykho** [comment]
Your theme CSS.

**Comment by nanda13ap** [comment]
is there any tag that shows that ?

**Comment by roykho** [comment]
http://cld.wthms.co/1kdhN/5J0wlfOG

**Comment by nanda13ap** [comment]
I was checking the css it is been used when i switch to 2015.
ok, I use the css shown on ur screenshot.

But I believe that the mai one is this one : http://test.greenregimen.com/wp-content/themes/twentyfifteen/style.css?ver=4.3.1 

which I use and you can see the reference on my page .

One question : the effect of opening the login form or coupon form is done by css?

**Comment by roykho** [comment]
Nope!  Just view source on your site and you will see what you're really using.

**Comment by nanda13ap** [comment]
it says I am using a lot of css files including the file of your screenshot and the one I said :+1: 
<link rel='stylesheet' id='twentyfifteen-style-css'  href='http://test.greenregimen.com/wp-content/themes/twentyfifteen/style.css?ver=4.3.1' type='text/css' media='all' />

**Comment by nanda13ap** [comment]
sorry, the thumb showed up out of nowhere. I had written the link that also shows on viewsource : <link rel='stylesheet' id='twentyfifteen-style-css'  href='http://test.greenregimen.com/wp-content/themes/twentyfifteen/style.css?ver=4.3.1' type='text/css' media='all' />

**Comment by nanda13ap** [comment]
link rel='stylesheet' id='twentyfifteen-style-css'  href='http://test.greenregimen.com/wp-content/themes/twentyfifteen/style.css?ver=4.3.1' type='text/css' media='all' />

**Comment by roykho** [comment]
It means you're not using the official theme.

**Comment by roykho** [comment]
For future reference this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

**Comment by nanda13ap** [comment]
ok, thank you.
