### ISSUE TITLE
cant access dashboard after 2.4.9 update

### ISSUE THREAD

**Issue by mgeoth** [woothemes/woocommerce#9546]
Hi guys.

I just updated woocommerce to 2.4.9 and I now cant access my dashboard. Im receiving an error saying  " Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /home4/.......on line 840"

Any one have any idea?

Thanks

**Comment by technofreaky** [comment]
Just increase the memory limit

On Mon, Nov 09, 2015 at 7:55 pm, mgeoth < notifications@github.com [notifications@github.com] > wrote:
Hi guys.

I just updated woocommerce to 2.4.9 and I now cant access my dashboard. Im
receiving an error saying " Fatal error: Allowed memory size of 268435456 bytes
exhausted (tried to allocate 72 bytes) in /home4/.......on line 840"

Any one have any idea?

Thanks

**Comment by roykho** [comment]
^^

**Comment by technofreaky** [comment]
Search in Google for wp memory limit

On Mon, Nov 09, 2015 at 7:55 pm, mgeoth < notifications@github.com [notifications@github.com] > wrote:
Hi guys.

I just updated woocommerce to 2.4.9 and I now cant access my dashboard. Im
receiving an error saying " Fatal error: Allowed memory size of 268435456 bytes
exhausted (tried to allocate 72 bytes) in /home4/.......on line 840"

Any one have any idea?

Thanks

**Comment by mgeoth** [comment]
Thank you ill look at that now.

**Comment by mgeoth** [comment]
Stuck!

On the htaccess file below, where should I add this code " php_value memory_limit 64M " 

<IfModule mod_deflate.c>
    SetOutputFilter DEFLATE
    <IfModule mod_setenvif.c>
        # Netscape 4.x has some problems...
        BrowserMatch ^Mozilla/4 gzip-only-text/html
        
        # Netscape 4.06-4.08 have some more problems
        BrowserMatch ^Mozilla/4\.0[678] no-gzip
        
        # MSIE masquerades as Netscape, but it is fine
        # BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
        
        # NOTE: Due to a bug in mod_setenvif up to Apache 2.0.48
        # the above regex won't work. You can use the following
        # workaround to get the desired effect:
        BrowserMatch \bMSI[E] !no-gzip !gzip-only-text/html
        
        # Don't compress images
        SetEnvIfNoCase Request_URI .(?:gif|jpe?g|png)$ no-gzip dont-vary
    </IfModule>
    
    <IfModule mod_headers.c>
        # Make sure proxies don't deliver the wrong content
        Header append Vary User-Agent env=!dont-vary
    </IfModule>
</IfModule>

**Comment by roykho** [comment]
Unfortunately this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

**Comment by mgeoth** [comment]
thanks will do.

**Comment by mikejolley** [comment]
@mgeoth  https://docs.woothemes.com/document/increasing-the-wordpress-memory-limit/
