### ISSUE TITLE
Edited email fields not showing changes

### ISSUE THREAD

**Issue by jlpajares** [woothemes/woocommerce#9547]
When you edit the field "email subject" in any of the Email settings and press "Save changes", the changes are saved but don't show. You have to manually refresh the page to see the change displayed.

**Comment by mikejolley** [comment]
Which email specifically? And what version of WC? It's saving fine/showing fine my side.

**Comment by jlpajares** [comment]
For example in Completed order. Maybe a WPML plugin problem?
WC Version 2.4.8.

**Comment by mikejolley** [comment]
It's refreshing here so possibly. Can you test without WPML on?

**Comment by jlpajares** [comment]
Confirmed this is a WPML problem. Sorry and thanks for support!
