### ISSUE TITLE
Error when there are too many grouped products

### ISSUE THREAD

**Issue by sselao** [woothemes/woocommerce#9548]
When adding a new product or editing a product, the dropdown for Grouped Products is causing an issue when there are too many grouped products.

It will generate this error:
Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0

**Comment by mikejolley** [comment]
After search or before? How many grouped products?

**Comment by claudiosmweb** [comment]
What WooCommerce version?

**Comment by claudiosmweb** [comment]
Since WooCommerce 2.4 this field was changed to work with ajax and should prevent this type of error.

**Comment by mikejolley** [comment]
^ as above. Closing due to lack of response.
