### ISSUE TITLE
Automatic refund for full order amount not changing status to Refunded

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#9549]
To recreate, complete a full refund via a payment gateway that supports automatic refunds. Doing so should change the order status to Refunded, based on the docs:

> If a refund had been completed for the entire order, the order status will be automatically changed to refunded. If a partial refund was awarded, the status will not change.

If the problem is with our docs, what is the correct workflow for a full refund?

**Comment by mikejolley** [comment]
This is correct @MindyPostoff. The page will refresh. However, there was handling added for free items - so to be classes as a full refund you must refund the complete $$ and each line item qty.
