### ISSUE TITLE
Payment not received but order processed

### ISSUE THREAD

**Issue by michaelcalero** [woothemes/woocommerce#9550]
I use woocommerce for my webstore and recently several orders were made. In the payment field it says the user has paid via paypal but the payment was never put into my linked paypal account. Is this an error with the woocommerce application and if so how can I figure out if the money was actually paid without contacting the customer directly?

**Comment by mikejolley** [comment]
Sounds like you may be using sandbox?

**Comment by michaelcalero** [comment]
No, not using sandbox for my webstore. Previous payments have gone through fine and notified me of the purchase and money received.

**Comment by mikejolley** [comment]
Are the orders pending or processing?

**Comment by michaelcalero** [comment]
Both said Pending when I opened up the page. both also said $30 paid via paypal. once I clicked the processing button on the first order it changed to processing.

**Comment by mikejolley** [comment]
Pending = unpaid. It's a temp order which was abandoned by the user. Ignore those! If you're concerned about payments going through, run a test yourself.

**Comment by michaelcalero** [comment]
Ok that makes more sense. So what does clicking on the processing button do on my end then? Because now it looks like a normal order not an abandoned order. Is there a way to tell if a transaction is actually paid or not other then the "pending" icon ?

**Comment by mikejolley** [comment]
Processing button is marking it paid, manually.
