### ISSUE TITLE
Return Virtual & Downloadable fields in Order line_items

### ISSUE THREAD

**Issue by JaggedJax** [woothemes/woocommerce#9551]
Having the virtual and downloadable fields in the line_items array when hitting the Orders API would be very helpful.

This would make it very easy when downloading orders to know which items need fulfillment without having to also hit the Products API each time, or having to cache the value and re-check occasionally to see if it has changed.

**Comment by mikejolley** [comment]
@claudiosmweb I couldn't figure out how to pass it with the request as a filter, but it might be good to accept an 'expand' param like Stripe API, so you can expand the product if needed.

If expanded, you'd have:

`
if ( ! empty( $filter['expand'] ) && in_array( 'product', $filter['expand'] ) ) {
				$line_item['product'] = WC()->api->WC_API_Products->get_product( $product_id );
			}
`

This would return the full product with each line item.

**Comment by claudiosmweb** [comment]
@mikejolley great idea :)

**Comment by JaggedJax** [comment]
Is this feature gone again in the new WordPress API? I don't see it listed in the documentation anymore for the latest version.

**Comment by claudiosmweb** [comment]
@JaggedJax not included on the WordPress REST API.
