### ISSUE TITLE
Free shipping not immediately visible after entering free shipping coupon

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#9552]
I was tracking an issue with Free Gift Coupons killing a regular free shipping coupon. I've fixed that now, but even with FCG disabled there's a slight problem in the cart. 

1. create a free shipping coupon
2. apply the coupon to the cart
3. the available shipping methods in cart totals aren't refreshed to add the free shipping method. 

Screenshot immediately after free shipping coupon is applied. You can see the "coupon has been added" text and the coupon is listed under the cart totals, but the Free shipping isn't an option yet.

![coupon applied](https://cloud.githubusercontent.com/assets/507025/11045393/13843b24-86dc-11e5-9e81-0893cb9fc880.png)

Instead, you have to click on "calculate shipping" and then "update totals" for the packages/transients to refresh... or you can reload the page to make the free shipping option visible in the cart totals.

![page reloaded: free shipping now visible](https://cloud.githubusercontent.com/assets/507025/11045426/3a287740-86dc-11e5-9dc0-d7e03b443108.png)

**Comment by helgatheviking** [comment]
One more thing, it seems like a free shipping coupon ought to both add free shipping to the allowed methods *and* set the shipping method to free shipping. The customer shouldn't have to select that if it could be done automatically.

**Comment by mikejolley** [comment]
@helgatheviking I think there must be something up with your coupon. It's applying here right away.

The code: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L1722-L1731

**Comment by helgatheviking** [comment]
Thanks Mike. Now I feel half-crazy because I was sure this was happening the other day. :)

**Comment by mdmoore** [comment]
>One more thing, it seems like a free shipping coupon ought to both add free shipping to the allowed methods and **set the shipping method to free shipping. The customer shouldn't have to select that if it could be done automatically**.

On the cart page, a free shipping coupon sets the shipping method automatically.  On checkout however, it only enables the free shipping option and doesn't set it automatically.

This is immediately after adding a free shipping enabled coupon:

![](https://cldup.com/hFmwUTItCf.png)
