### ISSUE TITLE
spaces beween <p> in checkout fields

### ISSUE THREAD

**Issue by dirad** [woothemes/woocommerce#9554]
I came across a strange issue while making some pixel perfect design for someome.

![asfe clipboard01](https://cloud.githubusercontent.com/assets/12030851/11050532/87fe84a0-874f-11e5-9cb5-99d5b1d3735b.jpg)

I have selected all the text on screen before the screen shot so you can see the issue.
If you look at the checkout fields, between each two horizontal ones there is a white selected space.

in the source code there is only a `</p>` and immediately follows a `<p>` on the next line for the next input. There is no space i can spot in the code .
I have remove my checkout template folder to eliminate chances of it being from my modifications and the issue persists.

After a POSTCODE field, there is no space . SAME in the shipping column. .
Actually there shouldn't be any spaces, but if so, at least i would like them to be consistent...

**Comment by dirad** [comment]
i found that removing the select2 styles and scripts will "solve" the issue - putting a space also after the postcode.

**Comment by mikejolley** [comment]
If you float these elements, spaces won't affect the positioning. The issue does not occur with the default CSS and theme https://dl.dropboxusercontent.com/s/iyxvo5yvr3fe8dk/2015-11-11%20at%2013.27.png?dl=0

**Comment by dirad** [comment]
Floating is move of a workaround than a solve..

This is the generated HTML so CSS shouldn't factor into it anyway.

**Comment by claudiosmweb** [comment]
@dirad feel free to submit a Pull Request.

**Comment by dirad** [comment]
I'd be very happy to. It would be my first time submitting one.
@mikejolley  @claudiosmweb  Guys, I set up another clean wordpress install to test this out.
Running latest WP, twentyfifteen, latest WC, and I've spent some good hours trying to figure where it come from, and i finally have.

In template files `form-shipping.php` and `form-billing.php` the PHP tags that surround each line in the each loop cause the spaces to be inserted into the HTML.
![q woo inline](https://cloud.githubusercontent.com/assets/12030851/11243934/af4d21fe-8e13-11e5-9b71-5169d467236d.jpg)

Since the default theme uses floats [and TBH so do I], the issue is not visible.
But if i set ``.form-row { display: inline-block;}`` or ``inline`` - you can see the issue appear.

![q woo inline space](https://cloud.githubusercontent.com/assets/12030851/11244071/6f11361a-8e14-11e5-9be0-163bc4d2df9b.jpg)

Thank you
* Removed the floats on .form-row-first , .form-row-last
