### ISSUE TITLE
Checkout not possible [SyntaxError: Unexpected token <]

### ISSUE THREAD

**Issue by nipeco** [woothemes/woocommerce#9557]
Hey there,
i was updating WooCommerce from **2.3.13** to **2.4.8**. Then i got this error message `SyntaxError: Unexpected token <` while proceeding to checkout. Today i updated to version **2.4.10** and the issue is still existent.

I read about this issue but only found solutions like turning off error messages ..

**Comment by roykho** [comment]
Which payment gateway are you using?

**Comment by nipeco** [comment]
Well okay, it seems that this error is caused by the **Woocommerce PayoneCw** Plugin. I will contact their support team.
