### ISSUE TITLE
[API] woocommerce_api_invalid_remote_product_image

### ISSUE THREAD

**Issue by frutality** [woothemes/woocommerce#9559]
It seems very strange, I'm just trying to post 'products/categories' with WooCommerce 2.5 beta. And it worked few hours ago. It was downloaded images and successfully added categories to database.

But at this moment all I get is:
[{"errors":[{"code":"woocommerce_api_invalid_remote_product_image","message":"Ошибка получения изображения http://woothemes.github.io/woocommerce-rest-api-docs/images/logo.png"}]}]

I've tried many websites with images, and I'm sure my internet connection is fine. I'm using https://github.com/woothemes/wc-api-node

**Comment by claudiosmweb** [comment]
Have you tried other images?
Perhaps you have tried many times and GitHub blocked you :P

**Comment by frutality** [comment]
@claudiosmweb yes, as I said, I tried many websites = many images. In example above, it was first attempt to fetch image from github.

**Comment by claudiosmweb** [comment]
This is the WordPress failing to be able to access the image, it can only be error in your server then.

**Comment by frutality** [comment]
I suppose you are right. Reloaded my vagrant machine and it works at this moment.
