### ISSUE TITLE
Checkout page

### ISSUE THREAD

**Issue by monica33** [woothemes/woocommerce#9560]
the product page is loading and does not complete

### WordPress Environment ###

Home URL: http://33amd.com/blog
Site URL: http://33amd.com/blog
WC Version: 2.4.10
Log Directory Writable: ✔  /home/hg33a836/public_html/33amd.com/blog/wp-content/uploads/wc-logs/
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 40 MB - Recomendamos configurar a memória para
pelo menos 64MB. Veja: Aumente a memória alocada para o PHP

WP Debug Mode: –
Language: pt_BR

### Server Environment ###

Server Info: Apache
PHP Version: 5.2.17 - Nos recomendamos no mínimo a versão 5.4 do PHP. Veja: Como atualizar a sua versão do PHP
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.40
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Post Remoto: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.10
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (13) ###

CSS Above The Fold: por Pau Iglesias
Blogestudio – 1.0

Custom Banners: por GoldPlugins – 1.7.2
Duplicar Post: por Enrico Battocchi – 2.6
Google Analytics by Yoast: por Equipe Yoast – 5.4.6
Pirate Forms: por Themeisle – 1.0.3
Pop-Up CC: por Chop-Chop.org – 2.0.6
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.4.1
WooCommerce Pagar.me: por Pagar.me
claudiosanches – 1.2.2

WooCommerce: por WooThemes – 2.4.10
Yoast SEO: por Equipe da Yoast – 2.3.5
WP Google Fonts: por Noah Kagan – v3.1.4
WP Minify: por Thaya Kareeson – 1.2.0
WP Simple Anchors Links: por Kilukru Media – 1.0.0

### Settings ###

Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Base da loja: #4 - /assine/
Carrinho: #5 - /carrinho/
Finalizar compra: #6 - /finalizar-compra/
Minha conta: #7 - /minha-conta/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: MinimalZerif
Version: 1.2
Author URL: http://www.9pixels.co
Child Theme: ✔
Parent Theme Name: Zerif Lite
Parent Theme Version: 1.8.2.6
Parent Theme Author URL: http://themeisle.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by roykho** [comment]
Unfortunately this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

But things for you to try is switch to a WP default theme such as 2016 theme.
