### ISSUE TITLE
Customer meta _order_count and _money_spent not accurate

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#9562]
So currently when the order status changes to `completed`, the customer meta `_order_count` and `_money_spent` is updated with the number of orders placed and total amount spent as expected.

However if the status is then changed from `completed` to any other status and then back to `completed`, those values are again increased which skews the accuracy.

Proposed change is to watch for order status changes and conditionally check for the status and increment/decrement accordingly so it stays accurate.

In addition, I think the status `processing` should also add to the value as that status essential means customer has already paid.  Currently it is only looking for `completed`.

Reported here https://wordpress.org/support/topic/user-metas-_money_spent-and-_order_count-bug?replies=3

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/issues/7222

> Looking at total_sales, it should be left as-is (storing the total sales regardless of future order status). The reason being, even if decreased during refund, it would require lots of extra logic to increase this should a refund be deleted or reversed. This will lead to issues keeping the value synced.
>
> One possible solution would be to query and cache that value rather than keeping it stored in meta permanently, but I suspect this best left until we refactor reporting for performance. For now, won't fix.

**Comment by roykho** [comment]
What about simply store a list of order ids to the customer meta so we add/remove the id according to status.  This way we can easily calculate the values without too much extra logic.

**Comment by mikejolley** [comment]
Still involves logic + extra storage. Maybe best to have the totals calc and store, but reset when a user ID makes a new order (to keep in sync)?

**Comment by roykho** [comment]
Does this solve the issue of when the order status is changed around?

**Comment by mikejolley** [comment]
You'd have to clear it on save_post @roykho
