### ISSUE TITLE
language pack updater 404

### ISSUE THREAD

**Issue by derekakelly** [woothemes/woocommerce#9563]
Originally posted on wordpress.org support forum..
https://wordpress.org/support/topic/language-pack-updater-404

This is from Query Monitor
https://wordpress.org/plugins/query-monitor/

Screen Shot:
http://i.imgur.com/Hbzh8Pn.png

This just came up again when i updated to 2.4.10

**Comment by claudiosmweb** [comment]
I just fixed it.
Try download the language pack again.
