### ISSUE TITLE
Out of stock message stays visible

### ISSUE THREAD

**Issue by JRhyne** [woothemes/woocommerce#9565]
When viewing a product variation that is marked out of stock, the Out of Stock message appears and the add to cart button disappears.  When you select another variation and it is in stock, the add to cart button reappears, but the Out of Stock message stays visible.

**Comment by roykho** [comment]
I am not able to reproduce this.  Please switch your theme to a WP default theme such as the 2015 and re-test.  Let me know if that resolves your issue.

**Comment by JRhyne** [comment]
Interesting, on a fresh test site, I cannot reproduce it either.  However, switching the theme to 2015 did not solve the issue.

**Comment by roykho** [comment]
So it is probably due to your plugins.  Deactivate all of them except WooCommerce and re-test.

**Comment by JRhyne** [comment]
Found the culprit plugin.  Thanks for responding quickly and helpfully.
