### ISSUE TITLE
Formal and informal translations

### ISSUE THREAD

**Issue by Willem-Siebe** [woothemes/woocommerce#9566]
Hi, what is the current opinion about formal and informal translations? I did found something about this topic: https://github.com/woothemes/woocommerce/commit/1b9b1ea2ccb8c49cebc2bc8c8aede3dc9ba44138.

Reason why I'm asking is because the Dutch translation is actually using both informal (je) and formal (u) mixed.... which makes the translation not so good. Is there a rule how translators should translate (formal or informal) and/or is there a formal and informal translation available/supported?

Kind regards,

Willem

**Comment by claudiosmweb** [comment]
The translations should now be made in WordPress.org: https://translate.wordpress.org/projects/wp-plugins/woocommerce

If Dutch need formal or informal variations, you should request it  to be included in the WordPress.
