### ISSUE TITLE
WooCommerce Image Rotation Issue

### ISSUE THREAD

**Issue by psasser** [woothemes/woocommerce#9568]
Hello Hello,

This is sort of a complex issue and I was wondering if something could be put into place to fix this.  I'm using the WooCommerce rest API library here https://github.com/kloon/WooCommerce-REST-API-Client-Library to create products in WooCommerce.  Everything works beautifully with the exception of one thing.

It creates a product but the images that it uploads are sometimes rotated incorrectly.  What I've gathered is that WooCommerce doesn't use exif data for image rotation.  This is actually a problem that is known in Wordpress as well.  See these google results https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8&safe=active&ssui=on#safe=active&q=wordpress+exif+image+rotation.  There are several plugins created just towards fixing that image rotation issue.  

However even with plugins installed it doesn't fix the issue when interfacing with the Rest API.  I dug deep into the WooCommerce core and changed this file https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L2348-L2352. 

To add in this code http://pastebin.com/MrteLewt and it fixes the issue. 

Any thoughts about possibly implementing this.  Or can you offer a suggestion to fix the issue?

Thanks,
patrick

**Comment by claudiosmweb** [comment]
Since is a "WordPress common issue" I just added a new filter, so you can hook and apply your code.

**Comment by psasser** [comment]
Hey Claudio,

I implemented this code and it works great.  However because I had to modified WooCommerce Core files it was overwritten when WooCommerce was updated.  Do you have any idea when it will be added to a new release?

Thanks much,
patrick

**Comment by claudiosmweb** [comment]
@psasser In WooCommerce 2.5.0 (January 2016).

**Comment by Charissame** [comment]
Hello, I'm having the same issue with all portrait photos being rotated to landscape orientation in my WooCommerce shop. What is the fix for this?

**Comment by psasser** [comment]
I think that you can add this into your plugin or whatever.  It hooks into the filter that Claudio added in above.

`function fixExifRotationIssue($upload)
	{
		 if ( is_callable('exif_read_data') )
		 {
			$exif = @exif_read_data( $upload['file'] );
			if ( isset($exif) && isset($exif['Orientation']) && $exif['Orientation'] > 1 ) 
			{
				$rotateImage = 0;
				$exif_orient = $exif['Orientation'];
				if ( 6 == $exif_orient )
				{
					$rotateImage = 90;
				}
				elseif ( 3 == $exif_orient )
				{
					$rotateImage = 180;
				}
				elseif ( 8 == $exif_orient )
				{
					$rotateImage = 270;
				}

				if ( $rotateImage != 0 )
				{
					if ( class_exists( 'Imagick' ) )
					{
						$imagick = new Imagick();
						$ImagickPixel = new ImagickPixel();
						$imagick->readImage( $upload['file'] );
						$imagick->rotateImage( $ImagickPixel, $rotateImage );
						$imagick->setImageOrientation( 1 );
						$imagick->writeImage( $upload['file'] );
						$imagick->clear();
						$imagick->destroy();
					}
				}
			   
				echo $exif['Orientation'];
				//exit;	
			}
		 }
	}
	add_action( 'woocommerce_api_uploaded_image_from_url', 'fixExifRotationIssue' );`
