### ISSUE TITLE
fragment_refresh ajax uses wc_ajax_url

### ISSUE THREAD

**Issue by sh-guti** [woothemes/woocommerce#9571]
Hi,

Issue refers to `/woocommerce/assets/js/frontend/cart-fragments.js:21`
I want to ask what's the reason to use `wc_cart_fragments_params.wc_ajax_url` and not `wc_cart_fragments_params.ajax_url`
wc_ajax_url is simple frontend request to my site and it cause to execute wp() function which is very heavy function (at-least in my case).
Would ajax_url could do the job of fetching the cart fragments ?

**Comment by mikejolley** [comment]
In many cases, admin requests are just as heavy, if not more. Thats why we switched in the first place.

**Comment by sh-guti** [comment]
Maybe you can put a filter there.
