### ISSUE TITLE
wc_get_product() function allways returns WC_Product_Simple Object

### ISSUE THREAD

**Issue by T-A-G** [woothemes/woocommerce#9572]
wc_get_product() allways returns WC_Product_Simple Objects even when the products are defined as variable products. This causes  incorrect return values for functions like get_children(), has_children(), etc...

**Comment by mikejolley** [comment]
I don't think thats the csae - this only occurs if the type is not found here: 

https://github.com/woothemes/woocommerce/blob/df75d2f617dc37c5c2c172bdce3a2fd152017499/includes/class-wc-product-factory.php#L34

Variations have their own handling too https://github.com/woothemes/woocommerce/blob/df75d2f617dc37c5c2c172bdce3a2fd152017499/includes/class-wc-product-factory.php#L69-L70

Additional note, WC_Product_Variation does extend WC_Product_Simple

**Comment by claudiosmweb** [comment]
Works fine.

Variable:
![screenshot from 2015-11-11 11-32-18](https://cloud.githubusercontent.com/assets/1264099/11092131/fc21c4be-8867-11e5-9993-cd892ef0337a.png)

Variation:
![screenshot from 2015-11-11 11-33-49](https://cloud.githubusercontent.com/assets/1264099/11092139/1d5c2476-8868-11e5-92fd-37f4b6351bcd.png)

**Comment by mrdilloway** [comment]
I had this same issue when my code was running on the woocommerce_init hook where I assume wc_product_variable isn't available.

Changing the hook to wp_loaded fixed the problem for me
