### ISSUE TITLE
Apostrophe in Fee Name

### ISSUE THREAD

**Issue by khag7** [woothemes/woocommerce#9583]
Create a new order in admin area.
Add a line item for a fee.
Call the Fee: Kevin's Special Fee
Save
Watch as your fee name becomes Kevin\'s Special Fee

In `wc-admin-functions.php` the `wc_save_order_items` function cleans the text using `wc_clean` on [line 200](../blob/master/includes/admin/wc-admin-functions.php#L200) and I believe this is what escapes the apostrophe with a slash.

Doesn't `$wpdb->update` handle sanitizing the data? Why do we need to use `wc_clean` (which is just a wrapper for wordpress's built in `sanitize_text_field` function) if `$wpdb->update` handles the sanitization for us? Or am I missing something?

**Comment by khag7** [comment]
For anyone else curious about the specifics of this...

My assumption was that wc_clean was escaping the apostrophe. That was incorrect.

Wordpress escapes all $_GET and $_POST very early on using an unconditional call to the function wp_magic_quotes. So we need to do stripslashes to counter that.

I'm still a little unclear on the purpose of using wc_clean, as $wpdb->update will sanitize the data.

**Comment by roykho** [comment]
So yes sanitation is not needed in this case as $wpdb->update handles it.  wc_clean was added just as a pre-caution in the past.  But as you found, that is not the cause of the issue anyhow.  See my PR for the fix.

**Comment by khag7** [comment]
Thanks. I am just trying to learn/understand. As I stated, I understand that wc_clean is not the problem, its wp_magic_quotes adding the slash, and we can't avoid that so we just use stripslashes. I'm caught up on that front. I just was curious about why we use wc_clean. And you answered that, "as a precaution" so I guess I understand now. Thanks for helping me learn.
