### ISSUE TITLE
Invalid orderby price clause 

### ISSUE THREAD

**Issue by smazur** [woothemes/woocommerce#9584]
Hi

I found an issue with WC_Query::get_catalog_ordering_args in following expression:
```php
$args['orderby']  = "meta_value_num {$wpdb->posts}.ID";
```
Assuming this should lead to SQL with following ORDER BY clause:

```SQL
ORDER BY wp_postmeta.meta_value+0 ASC, wp_posts.ID ASC
```
but it doesn't.

So, probably this expression should be written as follows:

```php
$args['orderby']  = "meta_value_num ID";
```

This causes unstable ordering by price, i.e. product order can change from time to time.

**Comment by roykho** [comment]
>Assuming this should lead to SQL with following ORDER BY clause:
>
>`ORDER BY wp_postmeta.meta_value+0 ASC, wp_posts.ID ASC`
>but it doesn't.

What does it lead to?

**Comment by smazur** [comment]
> What does it lead to?

When customer selects order by price, product order can differ each time page is loading. Products will be in right price order, for example from low to high. But in case when prices are same across multiple products their order can vary from time to time. 

Without `wp_posts.ID ASC` sql server doesn't care about order of records with equal values. But adding this extra ordering criteria will guarantee that post order will be always the same, because if sql server finds to records with equal values then it compares them by ID field.

I found this issue when I have detected that one of my plugin malfunctioning in case when customer orders products by price.

**Comment by roykho** [comment]
Sorry I should have asked the question better.  Are you saying that bit of code does not generate `wp_posts.ID` or just that it is missing `ASC`?

**Comment by smazur** [comment]
Yes, this expression doesn't generate `wp_posts.ID` in final SQL

**Comment by roykho** [comment]
At which point?  Because I just test dumped the argument and I get this:

![](http://cld.wthms.co/1hk2P/1Z3Bq1Bi+)

**Comment by smazur** [comment]
Please, check the final SQL query. Also check https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters
WP doesn't recognize such complex expressions like wp_posts.ID. As the case it accepts ID. So there should be `'meta_value_num ID'`, not the `meta_value_num wp_posts.ID`.

**Comment by roykho** [comment]
Let me do some testing.
