### ISSUE TITLE
woocommerce rest api allow Basic Auth without SSL

### ISSUE THREAD

**Issue by zouaghimariem** [woothemes/woocommerce#9585]
Hi!
I'm trying to take advantage of the WooCommerce rest apis built in (I already use wp-json).
As far as I've seen I can use oAuth only if I manually enable consumer and secret key on per-user basis or I can use Basic Auth if my website is under SSL (without manually enabling each user I suppose).
Since I'm just developing the new app and don't care about SSL on dev environment (it causes more troubles than benefits, even because windows users have troubles with self signed certificates), can I enable basic auth under clear http? Any hint?

Thank you very much!

**Comment by claudiosmweb** [comment]
Basic Auth is not safe without SSL.
Here the specs: https://tools.ietf.org/html/rfc2617
