### ISSUE TITLE
Email Templates - Move product table from individual templates to its own template

### ISSUE THREAD

**Issue by pmgarman** [woothemes/woocommerce#9587]
Customizing the product table in WC emails means customizing multiple email templates, considering this is the same product table it seems like it could easily be moved to its own email template file allow for easier customization.

**Comment by roykho** [comment]
I think this makes sense.

**Comment by mikejolley** [comment]
Agreed, but for a future update.

**Comment by JamesSimpson** [comment]
Yes please, would make things a whole lot faster when modifying the email templates
