### ISSUE TITLE
Create/Update product variation images with REST API

### ISSUE THREAD

**Issue by enigmascape** [woothemes/woocommerce#9588]
I have been trying to use the rest api to post and/or update products and having an issue with adding images to the variations using an existing attachment_id from the wordpress media library. It seems to work fine for the main product images, but it will not work for variation images: What happens is, it returns the json which shows that it replaces all of the imageid's in the variation with the id of the main image. I have also tried this with adding both the ID and the src url and, or just the src url and it creates a copy of the image in the media library. I have many variations that use the same image (ex red shirt, red hoodie, red tanktop, and then size 2x costs more, so it needs a new variation, size 3x costs more also, so it needs new variation also). This effectively triples the number of images necessary, and on a site with about 1000 root sku's, 5 style, and 5 color variations which need unique images its already alot... (25k images) but needing to have to create triple that many, its just not rational, and there must be some way to do this via the api. it can be done with manual entry to select existing images, but the api is not working this way. Am I doing something wrong?

Using the example code from the documentation I have altered it for demonstration purposes below:

{
  "product": {
    "title": "Ship Your Idea",
    "type": "variable",
    "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "categories": [
      9,
      14
    ],
    "images": [
      {
        "id":11111,
        "position": 0
      },
    "attributes": [
      {
        "name": "Color",
        "slug": "color",
        "position": "0",
        "visible": false,
        "variation": true,
        "options": [
          "Black",
          "Green"
        ]
      }
    ],
    "default_attributes": [
      {
        "name": "Color",
        "slug": "color",
        "option": "Black"
      }
    ],
    "variations": [
      {
        "regular_price": "19.99",
        "image": [
          {
            "id": 22222,
            "position": 0
          }
        ],
        "attributes": [
          {
            "name": "Color",
            "slug": "color",
            "option": "black"
          }
        ]
      },
      {
        "regular_price": "19.99",
        "image": [
          {
            "id": "33333",
            "position": 0
          }
        ],
        "attributes": [
          {
            "name": "Color",
            "slug": "color",
            "option": "green"
          }
        ]
      }
    ]
  }
}

**Comment by mikejolley** [comment]
Related #9664

**Comment by tundak** [comment]
getting same issue with variation image and also not showing featured image

**Comment by seanlane** [comment]
I'm seeing this issue as well. @mikejolley, I'm not sure if this is actually related to #9664. That issue seems to be about the duplication of files. What we're seeing here (or at least I am seeing) is when trying to create a variable product with images for the variants, each of the variants has the image set to the image specified for the product itself, rather than the variant images.

**Comment by ninobo11** [comment]
have you fix this issue? perhaps you can let us know, how the fix works?

**Comment by strarsis** [comment]
Related issue: https://github.com/woocommerce/wc-api-php/issues/157
