### ISSUE TITLE
[WP 4.4] Nav Tab Bottom Margin Scrunches WooCommerce Settings

### ISSUE THREAD

**Issue by allendav** [woothemes/woocommerce#9590]
Looks like a margin style on .wrap h2.nav-tab-wrapper in 4.4 beta (4.4-beta4-35632) is overriding .woocommerce .woo-nav-tab-wrapper margin-bottom and causing the sub tabs on Checkout and other Settings tabs to get pushed up against the tab bar:

<img width="1235" alt="screen shot 2015-11-12 at 12 48 48 pm" src="https://cloud.githubusercontent.com/assets/1595739/11130899/7d6faa70-893c-11e5-8636-4a8dd16470b5.png">

**Comment by roykho** [comment]
I am not seeing this issue on my end in Chrome nor Firefox.  Can you please re-confirm?

**Comment by claudiosmweb** [comment]
Fixed on master.
