### ISSUE TITLE
woocommerce-simple-product-bug

### ISSUE THREAD

**Issue by jshand2015** [woothemes/woocommerce#9591]
in the simple product page shown below, i have only put in a price of $5 and nothing in the sale price as it should be unless it's on special.

![woocommerce-simple-product-issue1](https://cloud.githubusercontent.com/assets/10791292/11133297/e46ffde8-89f9-11e5-8cb3-78d48ab5111d.png)

for the product shown on the shop page, it shows no price at all, so not able to purchase product.

![woocommerce-simple-product-issue2](https://cloud.githubusercontent.com/assets/10791292/11133298/e4759f96-89f9-11e5-99d5-a90c94ac7a4c.png)

**Comment by WPprodigy** [comment]
Hi @jshand2015,

I was not able to replicate this issue on any demo sites. This seems to be more of a conflict issue than a WooCommerce bug.Have you tried disabling all other plugins and switching to a default theme?

This is not the place to ask for support though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.

**Comment by jshand2015** [comment]
I am currently using the latest release 2.4.10

**Comment by WPprodigy** [comment]
And no other plugins are activated and you are on a default theme?

**Comment by jshand2015** [comment]
that is correct.  i'm getting the same problem.  and i am using the storefront default theme

**Comment by jshand2015** [comment]
1.5.3 is the current version of storefront

**Comment by WPprodigy** [comment]
Since I can't replicate this, could you submit a ticket into WooThemes Support and provide your login credentials there? That way somebody can take a look at your site and track down this issue.

**Comment by jshand2015** [comment]
i'm afraid that my site isn't live on a webserver, only on my computer until i've built it.  perhaps i should try another theme

**Comment by jshand2015** [comment]
tried the default theme that comes installed with wordpress twenty fifteen and i still have the same issue.

**Comment by jshand2015** [comment]
i have mariadb installed.  10.1.x, however it uses mysql 5.5.5

**Comment by mikejolley** [comment]
Tools > Export. Send us your content.

**Comment by jshand2015** [comment]
i couldn't upload the file as it is an xml file, and apparently right now, the repo doesn't support the uploading of xml.  can you gove your email address mike??

**Comment by claudiosmweb** [comment]
@jshand2015 use dropbox or another service.

**Comment by jshand2015** [comment]
This is my export of my site

[shandcleaningsolutions.wordpress.2015-11-13.docx](https://github.com/woothemes/woocommerce/files/34742/shandcleaningsolutions.wordpress.2015-11-13.docx)

**Comment by mikejolley** [comment]
The data is fine. Post your system status report too.

**Comment by jshand2015** [comment]
my system status
[Report.txt](https://github.com/woothemes/woocommerce/files/36472/Report.txt)

**Comment by mikejolley** [comment]
@jshand2015 no luck. Used your plugins and theme - shows price fine. Maybe you're running some form of caching locally. Hard to tell without access.

**Comment by jshand2015** [comment]
could it be possible it might be mariadb as i use the 10.1.x version.  i wonder if i need to convert to the community version of mysql

**Comment by mikejolley** [comment]
Looking back, mariadb has caused issues for some users. Worth a try.

**Comment by jshand2015** [comment]
i have reverted back to the mysql community version 5.6.x, i am still having the same issues with the single product.  as far as i know variable product works.  i may just have to use that instead.

to try and fix the problem i deleted my website and then deleted the database from mysql and then started fresh.

**Comment by mikejolley** [comment]
Wish I could be more help, but it's not possible to replicate. If you do find out what it was, or you reproduce it on a live server, let me know directly and I'll debug.
