### ISSUE TITLE
Woocommerce will not use SVG as "variable product" images.

### ISSUE THREAD

**Issue by atstockland** [woothemes/woocommerce#9592]
I am using wordpress version 4.3.1 and woocommerce version 2.4.10.  I have added the "SVG Support" plugin, version 2.2.2.  This plugin effectively fixes wordpress to allow the use of SVG images.  I am using SVG images successfully everywhere on my site, including product images in woocommerce...except I can not use SVG as "variable product" images.  I have also notified the plugin creator and he experienced the same issue.  He too was looking for a solution...

Is this a bug?  Is there a fix to allow the use of SVG as variable product images?

**Comment by roykho** [comment]
Off the top of my head I can't recall anything different about variation images that would allow main product image to work but not variation images.  But I will investigate in the next couple of days.  Will follow up.

**Comment by atstockland** [comment]
Thanks, roykho!  Looking forward to it!!

**Comment by atstockland** [comment]
Wanted to include the "SVG Support" dev on this.  @benbodhi

**Comment by atstockland** [comment]
I just noticed SVG images don't work in the image carousel either.  Will the changes made in this issue fix that as well?

**Comment by roykho** [comment]
What is image carousel?

**Comment by atstockland** [comment]
Whoops.  That is actually functionality of Visual Composure.  Sorry about that...
