### ISSUE TITLE
[Coupons] Please allow wildcards like *@woothemes.com in email restrictions

### ISSUE THREAD

**Issue by gerdneuman** [woothemes/woocommerce#9596]
Currently the email restrictions for a coupon only allow a list of email addresses. It would be great if one could use `*` wildcards, because I need to add a whole organization there. The organization has about 300 (changing) members, these are easily identified by their mail address. Think of somethink like `*@woothemes.com` :wink:  

I guess that could be easily added. (In case you downvote this, I would be very happy for a pointer how else this could be done maybe by using a hook)

**Comment by mikejolley** [comment]
Can you put this on http://ideas.woothemes.com/forums/133476-woocommerce to judge demand? Sounds useful, but more edge case.

For now you can add your own validation logic similar to how we do in the cart: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L170

If its not valid, trigger an error. Code can be based on what we have in the cart class now.

**Comment by gerdneuman** [comment]
Added the idea: http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/10691724--coupons-allow-wildcards-like-woothemes-com-in

But I suspect this will lie there indefintely... As you said it is an edge case only useful for a few people (like the whole email restriction list itself). As for the wildcards in postal codes I think it would still be good in order to complete the email restriction feature. Feels strange to have wildcards in postal codes but not for the email list... (and yeah, we would really need it)

**Comment by greguly** [comment]
There is this plugin https://pluginterritory.com/shop/woocommerce-coupons-wildcard-email-restriction/
