### ISSUE TITLE
API issue mismatch data type

### ISSUE THREAD

**Issue by BennSandoval** [woothemes/woocommerce#9598]
If I disable "Manage stocks" for a product, the api response with a string empty instead null or remove that field.

Manage stocks: disable
/wc-api/v3/products
"stock_quantity": ""

Manage stocks: enable
 "stock_quantity": 2

**Comment by BennSandoval** [comment]
Same case for "featured_src" sometimes returns the string of the URL and sometimes Boolean

"featured_src": "https://www.site.com/wp-content/uploads/2014/12/image147.jpg"
"featured_src": false

**Comment by claudiosmweb** [comment]
> Same case for "featured_src" sometimes returns the string of the URL and sometimes Boolean
> "featured_src": "https://www.site.com/wp-content/uploads/2014/12/image147.jpg"
> "featured_src": false

Is fixed since September 25 in #9220
