### ISSUE TITLE
Suggestion - Quantities on the shop page.

### ISSUE THREAD

**Issue by benjaminthedev** [woothemes/woocommerce#9599]
Hi Woo folks!

I love creating custom themes for my clients but I often get asked for the quantities to be on the shop page which I do in functions but would it not be better to have this feature right out of the box. It would be an amazing feature!

I would love to hear your thoughts? 

Thanks,

Ben.

**Comment by roykho** [comment]
Hello,

So it is the same reason we don't have a dropdown for variable products.  It is meant to be a quick shop page where it shows minimal information.

**Comment by benjaminthedev** [comment]
Fair enough! Thanks for the quick reply!
