### ISSUE TITLE
how to add order item meta from ADMIN if it custom meta is empty

### ISSUE THREAD

**Issue by alizainprasla** [woothemes/woocommerce#9600]
how to add order item meta from ADMIN if it custom meta eg.(warrenty) is empty

see the attachments.
![order_custom_post_auto](https://cloud.githubusercontent.com/assets/820419/11163183/6d9524a2-8ae7-11e5-9c80-0213eeda669f.jpg)

add_action( 'woocommerce_add_order_item_meta', 'my_add_order_item_meta', 10, 3 );

function my_add_order_item_meta( $order_item_id, $cart_item, $cart_item_key ) {
	wc_add_order_item_meta( $order_item_id, 'warrenty', 'hide this stuff' );
}

**Comment by roykho** [comment]
Unfortunately this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com
