### ISSUE TITLE
Redeem coupon

### ISSUE THREAD

**Issue by Adrilorenzo12** [woothemes/woocommerce#9601]
Hi!

I've got a Problem when i try to redeem coupon with the woocommerce API.

When i create a new order, pass all the order data, coupon data, shipping data, billing data.

When i check on my backend this order got all details but! just one fail the coupon code its detected but the amount of this coupon is not here and the order don't got the discount.

I don't know if this fail is a API issue or a configuration fail of my woocommerce.

Someone can help me

Thanks!!

**Comment by claudiosmweb** [comment]
Nop,  in the API you have to send the coupon value. Does not exist "Redeem".
