### ISSUE TITLE
Fatal Error : Site Crashed Help!

### ISSUE THREAD

**Issue by Rick8rooke** [woothemes/woocommerce#9605]
I am panicking because I think I've lost all my site.

I've been using Woocommerce with no problem so far but made a change in this file:

class-wc-product-variable.php

I changed the line :

public function add_to_cart_text() {
return apply_filters( 'woocommerce_product_add_to_cart_text', __( 'Select options', 'woocommerce' ), $this );
}

Where it says 'Select options' I changed it to 'View Products'.

Then uploaded it to the plugins > woo commerce > includes folder via ftp and my site went down!

It just shows a white screen and the text :

Fatal error: Access level to WC_Product_Variable::check_stock_status() must be public (as in class WC_Product) in /home/selectionfox/public_html/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php on line 655

I am so upset have I lost the site completely?

Please can anyone help me restore my site back online???

**Comment by roykho** [comment]
Unfortunately this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

But to help you along, you can simply use FTP to access your site and copy a new version of that file to your site overwriting the bad one you edited.  The other thing you can do is contact your host and have them roll back to a date before you made that change.
