### ISSUE TITLE
[WP 4.4] Product sorting stopped working

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#9607]
https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-assets.php#L305-L308

**Comment by BFTrick** [comment]
Same issue as #9608 I take it? Mind if I merge close this one and we work on the other issue?

**Comment by shivapoudel** [comment]
@BFTrick IMO this one is seperate bug from #9608 and is related to product ordering. Have a look to below screenshot xD

![capture](https://cloud.githubusercontent.com/assets/3774827/11262464/aa8f3cbc-8ea7-11e5-8e92-072e7f055e83.PNG)

**Comment by mikejolley** [comment]
@shivapoudel @BFTrick This is also working with beta 4 of 4.4 :)
