### ISSUE TITLE
[WP 4.4] Product sortable column stopped working

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#9608]
Price, SKU and feature column are not sorting data :D

**Comment by BFTrick** [comment]
Got a screenshot? That always helps. :)

**Comment by shivapoudel** [comment]
@BFTrick here is the bug ;)
![capture](https://cloud.githubusercontent.com/assets/3774827/11262399/eb88a984-8ea6-11e5-855c-fd3e48c73455.PNG)

**Comment by mikejolley** [comment]
@shivapoudel @BFTrick so is this :p
