### ISSUE TITLE
unsetting checkout fields causes json error

### ISSUE THREAD

**Issue by dirad** [woothemes/woocommerce#9610]
In my template, i am unsetting a few labels from checkout fields, just as described in the docs.
```
     unset($fields['billing']['billing_company'], 
      $fields['billing']['billing_first_name']['label'],
      $fields['billing']['billing_last_name']['label'],
....
```

Then while testing i found that if i have any invalid or missing fields while click the payment button in checkout - the lack of a label will break the json response in `class-wc-checkout.php`
Here is the full response: 
``` <br /> <b>Notice</b>: Undefined index: label in <b>/srv/www/wordpress-default/wp-content/plugins/woocommerce/includes/class-wc-checkout.php</b> on line <b>438</b><br /> {"result":"failure","messages":"<ul class=\"woocommerce-error\">\n\t\t\t<li><strong><\/strong> is a required field.<\/li>\n\t\t\t<li><strong>Last Name<\/strong> is a required field.<\/li>\n\t\t\t<li><strong>Address<\/strong> is a required field.<\/li>\n\t\t\t<li><strong>Town \/ City<\/strong> is a required field.<\/li>\n\t\t\t<li><strong>Email Address<\/strong> is a required field.<\/li>\n\t<\/ul>\n","refresh":"false","reload":"false"}```

What i actually get is the php error displayed instead of the WC validation messages.

**Comment by claudiosmweb** [comment]
Labels are required, with you don't what `billing_first_name` and `billing_last_name` you can unset... But many plugins will try use this fields.

**Comment by dirad** [comment]
sorry, can you please explain? I didn't understand what you mean by that.

**Comment by dirad** [comment]
i cannot unset any label ?
