### ISSUE TITLE
BUG Private Coupons are non existent 2.5.0-beta-1

### ISSUE THREAD

**Issue by codingideas** [woothemes/woocommerce#9612]
I upgraded to 2.5.0-beta-1 and my private coupons are not working when I apply them on the cart page.

### WordPress Environment ###

Home URL: https://site.com
Site URL: https://site.com
WC Version: 2.5.0
Log Directory Writable: ✔ /home/site/public_html/wc-logs/
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.15
PHP Post Max Size: 350 MB
PHP Time Limit: 600
PHP Max Input Vars: 8000
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.0
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (21) ###

Gravity Forms: by rocketgenius – 1.9.14
Advanced Custom Fields: Options Page: by Elliot Condon – 1.2.0
Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: by Elliot Condon – 4.4.3
Akismet: by Automattic – 3.1.5
Disqus Comment System: by Disqus  – 2.84
Heartbeat Control: by Jeff Matson – 1.0.3
Insert Headers and Footers: by WPBeginner – 1.3.3
Monarch Plugin: by Elegant Themes – 1.2
What The File: by Never5 – 1.5.2
WooCommerce Ecommerce tracking for Google and Facebook: by Multidots – 1.0.0
WooCommerce Custom Field Product Search: by Alvaro Neto – 1.0.0
WooCommerce Amazon Payments Advanced Gateway: by WooThemes – 1.4.4
WooCommerce PayPal Express Gateway: by WooThemes / SkyVerge – 3.5.1
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.2 – 1.10.6 is available
WooCommerce Google Product Feed: by Lee Willis – 5.1
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.3.1
WooCommerce: by WooThemes – 2.5.0-beta-1
WooThemes Helper: by WooThemes – 1.5.9
WP-Lister Pro for eBay: by Matthias Krok – 2.0.9.14
WP-Mail-SMTP: by Callum Macdonald – 0.9.5

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #40325 - /shop/
Cart: #1160 - /cart/
Checkout: #1161 - /checkout/
My Account: #1163 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###
Child Theme: ✔
WooCommerce Support: ✔

### Templates ###

Overrides: master/cart/cart-totals.php
master/cart/cart.php
master/cart/shipping-calculator.php
masterwoo-child-101/content-product.php version 1.6.4 is out of date. The core version is 2.5.0
masterwoo-child-101/woocommerce/single-product/meta.php
masterwoo-child-101/woocommerce/single-product.php

**Comment by claudiosmweb** [comment]
Do you know that the beta version is for use only in test sites, right?

**Comment by mikejolley** [comment]
Coupons need to be published to be valid. 

https://github.com/woothemes/woocommerce/blob/df75d2f617dc37c5c2c172bdce3a2fd152017499/includes/class-wc-coupon.php#L153

Does not look like this is a recent change either: https://github.com/woothemes/woocommerce/commit/883170e26187da1991753c01cf68b3ba46d4b624

There is no special handling for 'private' coupons, so setting them private shouldn't happen.

**Comment by codingideas** [comment]
Say we had a coupons landing page with all of our coupons. How should we
handle private coupons we give to just customers or customs we promote just
to email campaigns to measure success?

**Comment by mikejolley** [comment]
Set an email restriction. Private or published; codes are not listed anywhere.
