### ISSUE TITLE
Woocommerce Checkout Fields "add field Not working 

### ISSUE THREAD

**Issue by QuentinWeber** [woothemes/woocommerce#9613]
When I try to add a new field nothing happens. 

All plugins are up to date

**Comment by QuentinWeber** [comment]
Javascript error - Uncaught TypeError: jQuery(...).chosen is not a function
jQuery('table#wc_checkout_fields tr:not(.new_row) .chosen_select').chosen();

**Comment by claudiosmweb** [comment]
![screenshot from 2015-11-16 09-58-16](https://cloud.githubusercontent.com/assets/1264099/11181355/92dcb95c-8c48-11e5-8c07-58cea8a0d9d0.png)
