### ISSUE TITLE
does not send email to not logged in visitor

### ISSUE THREAD

**Issue by yassara** [woothemes/woocommerce#9616]
Hi,
I have a web form (Ninja) and want to phone number from our customer. before it works but now does not work, if you are a logged user you can send email or any requests but if you are not a logged user (visitor, guest) the system does not send email anyway. 
I tried on a bulk site, it works but when I copied my database, same issue has on bulk site. 
I think the problem is woocommerce.

**Comment by claudiosmweb** [comment]
> I have a web form (Ninja)
...

Custom code and I can see how this is a problem in WooCommerce.
If you found some bug, please, submit a Pull Request.
Good Luck.
