### ISSUE TITLE
Thank you page redirect without query string

### ISSUE THREAD

**Issue by gchokeen** [woothemes/woocommerce#9623]
I created the custom payment gateway plugin  for fssnet hdfc payment gateway for woocommerce. Every thing working fine but, fssnet not accepting the query string in response url. I passed used the thankyou page url as this ```$this->get_return_url($order)``` it generates url something like this http://localhost/press/checkout/order-received/64/?key=wc_order_564a4268ac79/. As per fssnet document

>Response URL where Payment gateway will send response once transaction processing is completed 
>		Merchant MUST esure that below points in Response URL
>		1- Response URL must start with http://
>		2- the Response URL SHOULD NOT have any additional paramteres or query string

Can you help me on this?  how to handles this ? I think this issue something similar to this #973. 

Thanks
Gowri

**Comment by claudiosmweb** [comment]
Create your own endpoint and redirect to the correct page.
