### ISSUE TITLE
[WP 4.4] Product variation images do not change when a variation is selected

### ISSUE THREAD

**Issue by mindsize** [woothemes/woocommerce#9624]
The link to the zoom image updates, but the image itself does not. This appears to be due to srcset being used in supported browsers now that RICG is part of core. Behavior replicated in Chrome (Mac) 46.0.2490.86, Firefox 42 and Safari 9.0.1 (11601.2.7.2). Regressing to 4.3.1 resolves the issue. It doesn't appear that this has been fixed in the current dev branch, though the rewrite of add-to-cart-variation.js looks much cleaner!

**Comment by mikejolley** [comment]
Confirmed; images don't change on the frontend @jameskoster

**Comment by WPprodigy** [comment]
@jameskoster Related: https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/

**Comment by jameskoster** [comment]
What am I doing wrong, I can't replicate this on 4.4-beta4-35729. https://cloudup.com/cc3mNtruGYe

**Comment by chaduk** [comment]
I'm having this exact issue right now with my website, did you find a solution?

**Comment by mindsize** [comment]
It's working fine for me in the final release of WordPress 4.4 with the latest public release of WooCommerce.
