### ISSUE TITLE
session->_data[removed_cart_contents] contains NULL characters

### ISSUE THREAD

**Issue by majemedia** [woothemes/woocommerce#9625]
Version: 2.4.10

I was trying to output the session to my error_log for development purposes but it kept cutting off.

had to adjust my error_log function to str_replace `\0` with `[NULL]` so that I could see everything

snippet from removed_cart_contents:

    rent";i:957;s:4:"guid";s:61:"http://freshmedfoods.com/product/pump-dinner-roll-16dzcase-2/";s:10:"menu_order";i:1600;s:9:"post_type";s:7:"product";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}s:12:"product_type";s:6:"simple";s:17:"[NULL]*[NULL]shipping_class";s:0:"";s:20:"[NULL]*[NULL]shipping_class_id";i:0;s:5:"price";s:5:"52.25";}}}

**Comment by mikejolley** [comment]
Seems to be a normal function of PHP - http://php.net/manual/en/function.serialize.php

> Object's private members have the class name prepended to the member name; protected members have a '*' prepended to the member name. These prepended values have null bytes on either side.

shipping_class and shipping_class_id are protected variables.
