### ISSUE TITLE
Incorrect WP Memory Limit in system status report

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#9627]
I run several sites with WooCommerce, all of which run on LiteSpeed, all have at least 256MB of memory configured for PHP/WP and all of them report 40MB in the WooCommerce system status report, along with a recommendation to increase it.

**Comment by claudiosmweb** [comment]
Nop. It's get that number from `WP_MEMORY_LIMIT` that is native from WordPress, if it's saying that using only 40MB, is because this set only 40MB for WordPress.

https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP

**Comment by galbaras** [comment]
That's a really bad idea, considering that WordPress uses ini_get('memory_limit') to find the PHP setting and only uses WP_MEMORY_LIMIT is that's not set. WooCommerce should switch to checking in the same way to get the EFFECTIVE setting, not some constant.

**Comment by claudiosmweb** [comment]
@galbaras here: https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/default-constants.php#L19

By default is `define('WP_MEMORY_LIMIT', '40M');`  ;)

**Comment by claudiosmweb** [comment]
@galbaras 
>  considering that WordPress uses ini_get('memory_limit') to find the PHP setting
Where? Since `wp-includes/default-constants.php` will test if `WP_MEMORY_LIMIT` is not defined and define to `40M`?

**Comment by galbaras** [comment]
@claudiosmweb We can do this all day. See: https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/default-constants.php#L52 . That's where the action really takes place. Line 19 is just foreplay.

**Comment by mikejolley** [comment]
Gal, wp sets the php memory limit to the value of that constant. The constant is accurate, and always has been. If WP reports 40MB, that's all you'll have allocated.
