### ISSUE TITLE
Email attachment issues (Documentation Update)

### ISSUE THREAD

**Issue by Lewiscowles1986** [woothemes/woocommerce#9629]
Hello,

Had a problem this AM with adding an attachment to an e-mail from child-theme folder.

**Initial Code**

```php
function cd2_attach_pdf_to_email ( $attachments='', $status='' , $order='' ) {
	$allowed_statuses = [ /*'new_order', */ 'customer_processing_order', 'customer_completed_order', 'customer_invoice' ];

	if( isset( $status ) && in_array ( $status, $allowed_statuses ) ) {
		$pdf_path = get_stylesheet_directory() . '/returns-warranty-webshop.pdf';
		$attachments[] = $pdf_path;
	}

	return $attachments;
}
add_filter( 'woocommerce_email_attachments', 'cd2_attach_pdf_to_email', 99, 3);
```

**Resolution**

```php
function cd2_attach_pdf_to_email ( $attachments='', $status='' , $order='' ) {
	$allowed_statuses = [ /*'new_order', */ 'customer_processing_order', 'customer_completed_order', 'customer_invoice' ];

	$attachmentStr = ( !is_array( $attachments ) );
	$attachments = $attachmentStr ? explode( "\n", $attachments ) : $attachments;
	if( isset( $status ) && in_array ( $status, $allowed_statuses ) ) {
		$pdf_path = get_stylesheet_directory() . '/returns-warranty-webshop.pdf';
		$attachments[] = $pdf_path;
	}

	return $attachmentStr ? implode("\n",$attachments) : $attachments;
}
add_filter( 'woocommerce_email_attachments', 'cd2_attach_pdf_to_email', 99, 3);
```

it seems more guidance should be given on ensuring that $attachments remains in the format received in to play well with other plugins, and WooCommerce updates, as the prior example was taken from a previous set of works, that we have confirmed worked at the time of deploy, however would not work on an active client site using 4.3 and the latest WooCommerce (likely due to receiving or returning a string value for $attachments)...

Perhaps the string version should be deprecated altogether in a future release?

**Comment by mikejolley** [comment]
WP accepts string or array as documented in https://codex.wordpress.org/Function_Reference/wp_mail - so we're just passing that value across. How plugins adjust that variable is out of our control, so code needs to check for both.
