### ISSUE TITLE
Add a filter in myaccount/my-orders template when echoing order status name

### ISSUE THREAD

**Issue by unfulvio** [woothemes/woocommerce#9633]
I didn't find a way to add markup in the order status column in recent orders.

https://github.com/woothemes/woocommerce/blob/master/templates/myaccount/my-orders.php#L64
this just outputs: `wc_get_order_status_name( $order->get_status() )`

the procedural function is filterable but it's not very useful in that context since I don't have the `$order` object for example

a use case came from an extension user feedback  https://github.com/woothemes/woocommerce-order-status-manager/issues/2 

>  The status descriptions that display in the view order screen (when rolling over the status text) is great, but these should also display the same way in the recent orders screen (the main orders list) of the customer account.

to achieve that I would need to add some markup around the order status name

**Comment by mikejolley** [comment]
I don't understand why you need context for a custom order status? Why would it be different based on the order? Order status names are global.

**Comment by unfulvio** [comment]
Hey Mike, perhaps a misunderstading

I would llike to add some custom markup here, between the `<td>` tags
https://github.com/woothemes/woocommerce/blob/master/templates/myaccount/my-orders.php#L63-L65

and I'd need to do that according to $order status and other order properties as well
