### ISSUE TITLE
API Product Attributes 2.5.0-beta-1

### ISSUE THREAD

**Issue by codingideas** [woothemes/woocommerce#9635]
I am using 2.5.0-beta-1 I need some help on the API. https://woothemes.github.io/woocommerce-rest-api-docs/#products

Say I have an attribute called apples which has an id of 1. So when I do this /wc-api/v3/products/attributes/1

I get this:

Array ( [has_archives] => [name] => Apples [order_by] => menu_order [slug] => pa_apples [type] => select [id] => 1 )

Though I want to see the archive for Apples. So I get the list of name and ids for example Green, Red. How do I do that? I have woocommerce 2.5.0-beta-1

**Comment by claudiosmweb** [comment]
Here is not a support forum.

**Comment by codingideas** [comment]
Where do I ask?

**Comment by roykho** [comment]
You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

**Comment by codingideas** [comment]
Thanks roykho, you're awesome. Because this is so edge case I hoped the 'professor' claudiosmweb would help with that. :+1: Though I followed your instruction and replied to the woocommerce plugin support on wordpress.org

https://wordpress.org/support/topic/api-product-attributes-250-beta-1?replies=1

Thanks

**Comment by claudiosmweb** [comment]
@codingideas 
> Though I want to see the archive for Apples. So I get the list of name and ids for example Green, Red. How do I do that?

You do not, this is not supported.
