### ISSUE TITLE
Redeem coupon via API

### ISSUE THREAD

**Issue by Adrilorenzo12** [woothemes/woocommerce#9636]
I know. woocommerce API dont got any method to auto redeem a coupon and i try some ways but any of this ways works for example:

I try "play" with diferents combination of subtotals and totals but i never get the correct quantities of totals and discount.
In this example my total was, 47,8 and it will be 50 (21% tax).
<myapp.IRLineProductMantle: 0x numbers> {
    identifier = 4487;
    quantity = 2;
    subtotal = "39.5";
    subtotalTax = "10.5";
    title = "product";
    total = "39.5";
    totalTax = "10.5";
}

Some one know how i can redeem coupon in my app?
I need build a especial web service or is posible via API changing the values of the total and subtotal?

Thanks!!!

**Comment by claudiosmweb** [comment]
![screenshot from 2015-11-17 23-08-25](https://cloud.githubusercontent.com/assets/1264099/11229773/209657ca-8d80-11e5-9b1e-14205657b4bf.png)
