### ISSUE TITLE
API Product Attributes Modification

### ISSUE THREAD

**Issue by codingideas** [woothemes/woocommerce#9637]
Usecase: 

We are building a product lister which creates everything based on attrubutes for a product: https://beckertime.com/private-product-lister/public/products/3/edit

As you can see in the attrubute tabs we have Gender and it's values as buttons. We will use these the attrubute values to create product titles, urls, and custom meta fields in the API. https://beckertime.com/private-product-lister/public/profiles/3/edit

My feature request recommandation is to be able to fetch the archive tree for products/attrubutes/id/

**Comment by claudiosmweb** [comment]
Done: https://github.com/woothemes/woocommerce/compare/a7cfcddd95a484345f2b31afc5a152d28fe9c794...11ce0fb18c2aa6790c935f79bd1cd019d8a3f250

**Comment by claudiosmweb** [comment]
Wrong place...

**Comment by claudiosmweb** [comment]
@codingideas Soon I'll write some docs for it.
