### ISSUE TITLE
Webservice API : allow to list tax_class rules

### ISSUE THREAD

**Issue by Max84** [woothemes/woocommerce#9640]
Hi,

An useful feature is missing into webservice REST API: the list of tax_class with their rules and rates.

If you'll add it, it'll be perfect :)

Best regards

**Comment by WPprodigy** [comment]
I guess it's already perfect then ;)

https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-taxes.php#L513-L550

**Comment by gedex** [comment]
Endpoint `/taxes/classes` only returns list of tax classes containing slugs and names without its rules. However, you can get all taxes and its rules from `/taxes/` endpoint. You could also filter by `tax_rate_class` too, for example `taxes?filter[tax_rate_class]=zero-rate` will returns taxe rules with class `zero-rate`.
