### ISSUE TITLE
Error in WooCommerce Dashboard

### ISSUE THREAD

**Issue by lhp83d** [woothemes/woocommerce#9642]
When I enter my site, in the WooCommerce Dashboard 77 sold out products are reported. 

![77 sold out](https://cloud.githubusercontent.com/assets/15912875/11250158/5b5b82bc-8e2b-11e5-97f5-d810e4c3888e.png)

When you get into the "sold out" products, in most of them, you try to edit it in order to delete it, you receive an error that the product doesn't exist. 

![inexistentproduct](https://cloud.githubusercontent.com/assets/15912875/11250212/ab4c970c-8e2b-11e5-8560-8340d961fb22.png)

Any clue about what's happening?

Thanks a lot.

**Comment by mikejolley** [comment]
Before you click one, see what ID it is linking to. Then cross reference that ID with your wp_posts table. See what it is.

**Comment by lhp83d** [comment]
Hi, mikejolley.
The entry with this ID does NOT exist in wp_posts table. Obviously, the dashoboard info is not correct. How can this be resolved?
Thanks a lot.

**Comment by mikejolley** [comment]
Post your system status report.

**Comment by lhp83d** [comment]
### WordPress Environment ###

Home URL: http://sce-desarrollo.biz/bk_rocio
Site URL: http://sce-desarrollo.biz/bk_rocio
WC Version: 2.4.6
Log Directory Writable: ✔  /home1/lhp83d/public_html/bk_rocio/wp-content/uploads/wc-logs/
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: –
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.45
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Publicar remoto: ✔
Obtén remoto: ✔

### Database ###

WC Database Version: 2.4.6
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (19) ###

LayerSlider WP: por Kreatura Media – 5.5.1
Akismet: por Automattic – 3.1.5
Activity Log: por Yakir Sitbon
Maor Chasen
Ariel Klikstein – 2.2.6

Nextend Facebook Connect: por Roland Soos – 1.5.7
WPML Multilingual CMS: por OnTheGoSystems – 3.1.9.7
WooCommerce - APG Weight and Postcode/State/Country Shipping: por Art Project Group – 1.9.0.2
WooCommerce Google Analytics Integration: por WooThemes – 1.3.0
WooCommerce Multilingual: por OnTheGoSystems – 3.6.11
WooCommerce: por WooThemes – 2.4.6
WordPress Backup to Dropbox: por Michael De Wildt – 4.3
Importador de WordPress: por wordpresspuntoorg – 0.6.1
Yoast SEO: por Equipo Yoast – 2.3.5
WPML Media: por OnTheGoSystems – 2.1.9
WPML String Translation: por OnTheGoSystems – 2.1.4
WPML Translation Management: por OnTheGoSystems – 1.9.11
XCloner: por Liuta Ovidiu – 3.1.3
YITH Custom Login: por Your Inspiration Themes – 1.0.3
YITH Maintenance Mode: por Your Inspiration Themes – 1.2.0
YITH WooCommerce Ajax Product Filter: por yithemes – 2.3.1

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Base de la tienda: #10 - /tienda/
Carrito: #11 - /carro/
Finalizar compra: #12 - /finalizar-comprar/
Mi cuenta: #13 - /mi-cuenta/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Maya Shop
Version: 2.9.0
Author URL: http://yithemes.com/
Child Theme: ✕ – Si está modificando WooCommerce o un tema de los padres que no construye personalmente le recomendamos que utilice un tema menor. Ver: Cómo crear un tema infantil
WooCommerce Support: ✔

### Templates ###

Overrides: maya/woocommerce/archive-product.php
maya/woocommerce/cart/cart-empty.php
maya/woocommerce/cart/cart-shipping.php
maya/woocommerce/cart/cart.php
maya/woocommerce/content-product.php
maya/woocommerce/content-product_cat.php
maya/woocommerce/content-single-product.php
maya/woocommerce/global/breadcrumb.php
maya/woocommerce/global/form-login.php
maya/woocommerce/global/quantity-input.php
maya/woocommerce/global/sidebar.php
maya/woocommerce/global/wrapper-end.php
maya/woocommerce/global/wrapper-start.php
maya/woocommerce/loop/add-to-cart.php
maya/woocommerce/loop/loop-start.php
maya/woocommerce/loop/pagination.php
maya/woocommerce/loop/price.php
maya/woocommerce/loop/sale-flash.php
maya/woocommerce/myaccount/form-login.php
maya/woocommerce/single-product/add-to-cart/external.php
maya/woocommerce/single-product/add-to-cart/grouped.php
maya/woocommerce/single-product/add-to-cart/simple.php
maya/woocommerce/single-product/meta.php
maya/woocommerce/single-product/price.php
maya/woocommerce/single-product/product-image.php
maya/woocommerce/single-product/product-thumbnails.php
maya/woocommerce/single-product/related.php
maya/woocommerce/single-product/review.php
maya/woocommerce/single-product/sale-flash.php
maya/woocommerce/single-product/share.php
maya/woocommerce/single-product/short-description.php
maya/woocommerce/single-product/tabs/description.php
maya/woocommerce/single-product/tabs/tabs.php
maya/woocommerce/single-product/up-sells.php
maya/woocommerce/single-product-reviews.php
maya/woocommerce/single-product.php
maya/woocommerce/taxonomy-product_cat.php
maya/woocommerce/taxonomy-product_tag.php

**Comment by mikejolley** [comment]
99% sure you're going to find WPML causing this since they use multiple IDs for each language. Confirm by disabling it, then raise a ticket on their forum if its the latest release.

**Comment by lhp83d** [comment]
Nothing to do with WPML. 
WPML disabled, buy issue is still happening.
I attach screenshot.
![no_wpml](https://cloud.githubusercontent.com/assets/15912875/11345413/0e92b8de-9217-11e5-8685-68c732ed8e01.png)

**Comment by lhp83d** [comment]
Please reopen issue. Nothing to do with WPML as suggested. A screenshot 
is attached in the support case.

**Comment by mikejolley** [comment]
@lhp83d It's cached. With WPML disabled if you make a new order it will refresh.

**Comment by lhp83d** [comment]
Hi, Mike.

I made a new order with WPML disabled, but the problem still remains...
