### ISSUE TITLE
Product page not displaying any of the product that have been uploaded

### ISSUE THREAD

**Issue by sweetboxdelivery** [woothemes/woocommerce#9646]
The Product page just displays the following in place of the 9 products that we uploaded:

Fatal error: Call to undefined function wc_placeholder_img() in /home/obloco/public_html/bake/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php on line 1453

Help!

**Comment by roykho** [comment]
Unfortunately this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com
