### ISSUE TITLE
High cpu load (mysqld, httpd) - Many transient selects

### ISSUE THREAD

**Issue by larastarter** [woothemes/woocommerce#9647]
I'm running WooCommerce 2.4.10 on WP 4.3.1 with PHP 5.6.14 on an CentOS installation.

The problem is, that the CPI load is very high - especially the mysqld process (~ 170% CPU Load) and a lot of httpd process all running on abou 90-100% CPU load.
This causes a page load time by about 20-30 seconds.

I checked the load intensive httpd processes (strace -p XXXX) and noticed that this queries are executed a lot of times and without any break:

SELECT option_value FROM wp_options WHERE option_name = '__1449555989' LIMIT 1

The strace output:
sendto(15, "O\0\0\0\3SELECT option_value FROM wp_options WHERE option_name = '__1449556003' LIMIT 1", 83, 0, NULL, 0) = 83
recvfrom(15, "\1\0\0\1\1K\0\0\2\3def\twordpress\nwp_options\nwp_options\foption_value\foption_value\f-\0\377\377\377\377\374\21\20\0\0\0\5\0\0\3\376\0\0\2\0\5\0\0\4\376\0\0"..., 16384, 0, NULL, NULL) = 102

Used plugins in relation with WooCommerce:
WooCommerce German Market (woocommerce-german-market)
WooCommerce Google Analytics Integration (woocommerce-google-analytics)
WooCommerce Product Filter (http://www.mihajlovicnenad.com/product-filter)
WooCommerce Products Compare (http://www.woothemes.com/products/woocommerce-products-compare/)
WooCommerce Table Rate Shipping (http://bolderelements.net/docs/woocommerce-table-rate-shipping/)
WooCommerce Variable Product Description

Thanks for your help.

**Comment by claudiosmweb** [comment]
Don't worry, it will not be more such problems in WooCommerce 2.4. 
We have a new https://woocommerce.wordpress.com/2015/10/07/new-session-handler-in-2-5/ and a lot of things that don't use transients for cache anymore.
