### ISSUE TITLE
Admin : Out of Stock report lists products that are in stock.

### ISSUE THREAD

**Issue by addedlovely** [woothemes/woocommerce#9648]
The 'Out of Stock' report ( wp-admin/admin.php?page=wc-reports&tab=stock&report=out_of_stock ) is listing 'simple' products (that have stock management enabled, and stock entered) as 'Out of Stock'.

Attached is an example product and the inventory settings from the store.

Inventory Settings:
<img width="1109" alt="screen shot 2015-11-19 at 11 39 28" src="https://cloud.githubusercontent.com/assets/565669/11269948/b37bfbca-8eb2-11e5-82fe-e41ae5fcf735.png">

Product Settings:
<img width="803" alt="screen shot 2015-11-19 at 11 38 27" src="https://cloud.githubusercontent.com/assets/565669/11269951/bc326038-8eb2-11e5-9c17-9b1d0af36aff.png">

Product in report:
<img width="1099" alt="screen shot 2015-11-19 at 11 38 16" src="https://cloud.githubusercontent.com/assets/565669/11269959/c844a4e4-8eb2-11e5-84a2-79b2e0cab88f.png">

We also ran the 'Recount Terms' tool, but this had no effect.

WP Version: 4.3.1
WC Version: 2.4.10

**Comment by mikejolley** [comment]
Have you ever used an importer plugin?

**Comment by addedlovely** [comment]
@mikejolley haven't on this site, was a clean install and manual product entry. Want a copy of the DB?

**Comment by mikejolley** [comment]
Need System Status report, and tools > export XML file to look at the data.

**Comment by mikejolley** [comment]
Responding via email.
