### ISSUE TITLE
Can’t conditionally filter 'from' addresses on built-in WC_Email mails

### ISSUE THREAD

**Issue by ymazuz** [woothemes/woocommerce#9653]
I tried really hard to see if this issue was a dupe, but *from*, *email*, and *filter* aren’t the most helpful search terms.

I can’t use filters to *conditionally* change the **From:** settings on WooCommerce emails. WordPress allows changing this through either the **wp_mail_from** and **wp_mail_from_name** filters or by changing the headers via the **wp_mail** filter, but these built-in **wp_mail*** filters only allow hooked functions to take one argument, so if I want to change things conditionally, I have to be able to count on finding the information I need in a global variable or **$_POST** args.

WooCommerce has a **woocommerce_email_headers* filter that allows hooked functions to see the WC_Email $id and $object, but I can't use this to change a **From:** name address because 
 1. **wp_mail()** ignores **From:** set via headers if the **wp_mail_from*** filters return a valid value
 2. the **WC_Email** class’s **send()** method sets the return address using those filters

WooCommerce has copious filters/actions for customizing emails and their templates, with context passed in via the **WC_Email**’s **$id** or the **$object** it’s for. I can change the subject line, recipient, header, and various chunks of content. Because y’all have been so thorough in adding the **woocommerce_email_*** filters, I imagine the lack of From: filters are deliberate. I’d be interested in hearing your justification for leaving them out. I’ll also point out why I think they’re a good idea. In my case, my business is a heavy user of WooCommerce Bookings for various services, and we have a separate email address that we use to communicate with customers about bookings. If I start selling T-shirts online, I’d want anything related to bookings to continue coming from my booking email account. I can see other reasons someone might want to filter these. E.g. maybe cancelation or refund emails should come from an address checked by a real person, but confirmations could come from a sending-only account.

I realize I can work around this with Reply-To: headers, but I’d prefer the correct name/address to show up in from. I’ll submit a pull request to implement this shortly.

**Comment by mikejolley** [comment]
No objections to adding filters so make your PR. I'd change the args to perhaps just be $this however, so you have access to the entire class from your hooked function?

**Comment by ymazuz** [comment]
@mikejolley Cool! I made the PR, but I was about to updated it based on feedback from Claudio. 

So, the reason I was going to pass in **$this->object** instead of just **$this** was for consistency with existing **woocommerce_email_*** filters, since that’s what I’d seen in some of the ones I’ve used. It looks like the title and description filters use **$this**, and most of the others use **$this->object**. If you think **$this** will be the preferred style going forward, that works for me! While I have you here, is there a preference between naming the hook tag as `'woocommerce_email_wp_from_name_' . $id` vs. just `'woocommerce_email_wp_from_name'`? I like the latter convention because it lets me write fewer **add_filter()** lines and just throw conditionals in the hooked functions, but I wasn’t sure if there was a rule for when to use which style. Thx.
