### ISSUE TITLE
Prefix/Suffix Checkout JSON response to avoid the "SyntaxError: Unexpected token <" error

### ISSUE THREAD

**Issue by maxrice** [woothemes/woocommerce#9655]
As far back as I can look in GitHub (see [1.6.6](https://github.com/woothemes/woocommerce/commit/c1e3da8bcb722be48a9f3101a7c42ed96e62b68d)), the checkout JSON response has been prefixed with  `<!--WC_START--> ` and suffixed with `<!--WC_END-->` to avoid parsing errors due to other plugins/themes producing output. As of 2.4, this was [removed](https://github.com/woothemes/woocommerce/commit/c1e3da8bcb722be48a9f3101a7c42ed96e62b68d) and a pure JSON response is sent.

Was there a reason for that change? I can see that it makes the checkout JS a bit cleaner, but it's responsible for a significant amount of support tickets. While it's certainly something that either the hosting provider can resolve (by disabling the output of PHP errors) or plugin/theme authors can resolve (by fixing notices/warnings/errors), I think WC would benefit from being resilient to these sort of issues, like it previously was from versions 1.6 to 2.3.

I'm happy to work up a PR to fix this :smile_cat:

**Comment by tamarazuk** [comment]
To add to this, I just tracked down the issue with [this ticket](http://woothemes.zendesk.com/agent/tickets/355125) and it has to do with the box packer bundled with the [Canada Post shipping extension](http://www.woothemes.com/products/canada-post-shipping-method/).

The specific culprit in this case is the `pack()` method echoing an error [here](https://github.com/woothemes/woocommerce-shipping-canada-post/blob/master/classes/box-packer/class-wc-boxpack.php#L164-L166) coming from [here](https://github.com/woothemes/woocommerce-shipping-canada-post/blob/master/classes/box-packer/class-wc-boxpack.php#L92-L94)

![] (https://cloudup.com/cQvX8PhUuEq+)

![](https://cloudup.com/cg00bkMNHmS+)

This is an important example for this issue because it shows that even in cases where hosts fix the problem of displaying error messages, you can still run into this situation.

**Comment by mikejolley** [comment]
A few reasons; 

- to let jquery handle the response
- to take advantage of wp_send_json, with correct headers
- to standardise all responses
- to simplify handling by of the response

Yes things can break the above. But the comments were always a hack...would feel dirty reverting this tbh. 

How about working on a better error handler? Maybe to try to force valid json if malformed?

**Comment by DavidAnderson684** [comment]
Here's an example of a plugin that uses PHP error handling to capture PHP log messages, prevent them from going direct to the browser, and add them to the JSON response (which then gets console.log()ed if any were present), to prevent breaking AJAX conversations: https://plugins.trac.wordpress.org/browser/two-factor-authentication/trunk/two-factor-login.php

See the if (defined('DOING_AJAX')) check in the constructor, and then the processing of any logged errors in the tfaInitLogin() method.

**Comment by mikejolley** [comment]
We do something similar @DavidAnderson684 but that only stops errors. White space or outputting html for example will still break.

**Comment by DavidAnderson684** [comment]
Hi Mike,

That's taken care of in the example too - see https://plugins.trac.wordpress.org/browser/two-factor-authentication/trunk/includes/tfa.js, and search for jsonstarter. (It does have an implicit assumption that json_encode() will put the first PHP array element as the first element in the JSON array too, which seems fairly safe - safe enough for a small plugin, anyway. You might want to have something more clever if that doesn't seem a reliable assumption).

David

**Comment by maxrice** [comment]
@mikejolley makes sense, yeah I think an improved error handler would be a step in the right direction. I'll have a go this week and see what I can work up :)

**Comment by mikejolley** [comment]
@maxrice how'd it go :)?

**Comment by maxrice** [comment]
@mikejolley sorry, didn't get to it over the holidays, going to have a look today :)

**Comment by maxrice** [comment]
@mikejolley what do you think of using the [jQuery Ajax dataFilter](http://clearhead.me/jquery-ajax-datafilter/)? It would let us sanitize the raw response, so we could check if valid JSON is received and immediately return it, or if not, attempt to strip out the invalid text and return valid JSON.

**Comment by mikejolley** [comment]
@maxrice never seen that before. Looks perfect.
