### ISSUE TITLE
action "woocommerce_cart_item_removed" can't get accurate count of items in cart

### ISSUE THREAD

**Issue by majemedia** [woothemes/woocommerce#9656]
The position of the `woocommerce_cart_item_removed` action in `WC_Cart` should be moved to below the `calculate_totals()`.

Why?

The `WC()->cart->get_cart_contents_count()` call won't return a valid amount of count if run.

Example:

- Items in cart: 1
- Remove item from cart
- call `WC()->cart->get_cart_contents_count()` from `woocommerce_cart_item_removed` action callback

Returns: 1

if within the callback you manually run `WC()->cart->calculate_totals()` the return will be 0, but then calculate totals is run twice.

**Comment by mikejolley** [comment]
Equally if someone was removing items based on other items they would need to run calculate totals in there function, which would result it in being done twice as well. So there is no winning scenario here. All that could be changed if anything (to avoid breakage) would be to make get_cart_contents_count dynamic and do its own loop where called. Slower however.

**Comment by majemedia** [comment]
you could add another action below the `calculate_totals` call. something like `woocommerce_cart_item_removed_totals_updated` or something less verbose.

It just feels like the woocommerce_cart_item_removed is confusing because due to its name I'm expecting it to actually be gone but the cart state is still as it was previously.

**Comment by majemedia** [comment]
The same could be done to the `restore_cart_item` method as well. since the same problem could potentially exist there.

**Comment by franticpsyx** [comment]
@mikejolley I added the `woocommerce_cart_item_removed/restored` hooks in https://github.com/woothemes/woocommerce/commit/f8567680da7d8c49be106fa92d489a863d1ca5bf

The motivation there was to have them run before the `calculate_totals()` call, since the hook was primarily meant to be used by extensions that remove cart items "dependent" on the currently removed item. Calling `calculate_totals()` before removing additional items would obviously cause issues.

Then, the second set of hooks was added in https://github.com/woothemes/woocommerce/pull/8110/files

So far so good.

One possible solution would be to update the `cart_contents_count` property after unsetting/restoring, before the second set of hooks kicks in.

**Comment by franticpsyx** [comment]
>One possible solution would be to update the cart_contents_count property after unsetting/restoring, before the second set of hooks kicks in.

In this case, we could also consider using a separate `update_cart_contents_count` method, which can be called from `calculate_totals`, too.

**Comment by franticpsyx** [comment]
@mikejolley Depending on scope, `get_cart_contents_weight` may not always return the same weight as the total weight of all shipping packages, depending on whether shipping package contents are filtered/modified.

In general, the assumption that [products in cart] == [products in shipping packages] is not valid in all cases, so we might consider adding something to the method docblock (?). I'd avoid having any shipping-related methods operate on cart items when all shipping calculations rely on package contents.

Example 1: Some shops add extra items (0 value) in the shipping package that may not exist in the cart. I've recently seen a case of a shop selling fish, which had a rather complex way of determining how much ice needs to be added into a cart full of fish. Ice there was added by adding a new item (with some extra weight) in the shipping package.

Example 2: A product-bundle may override the dimensions / weight of its "contents" - in this case, the bundled product weights + dimensions (or virtual status, either works) in the shipping packages are filtered to ensure that shipping costs are calculated correctly. Additionally, the total value of all items is aggregated into the "container" item, to ensure that shipping insurance costs are again correct. To do this, the bundled products in shipping packages are cloned from the cart and then modified to avoid modifying the same class instance in the cart.

**Comment by mikejolley** [comment]
@franticpsyx this is straight replacement for the old variable - its the weight of the cart, not a package.
