### ISSUE TITLE
[4.4] Product data panel issues

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#9657]
- [ ] Missing icon
- [x] Position of product type selector

**Comment by mikejolley** [comment]
![2015-11-20 at 12 40](https://cloud.githubusercontent.com/assets/90977/11300145/86834b3c-8f84-11e5-92c6-49dfa4f69d7f.png)

**Comment by claudiosmweb** [comment]
Need to cherry-pick from master.

**Comment by mikejolley** [comment]
@claudiosmweb icon is missing in master too
