### ISSUE TITLE
[4.4] Cannot access product_shipping_class menu

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#9658]

**Comment by shivapoudel** [comment]
@mikejolley Seems like I have fix this in PR #9573 :P

**Comment by claudiosmweb** [comment]
Need to cherry-pick from master.

**Comment by mikejolley** [comment]
@claudiosmweb @shivapoudel hard to cherry pick when people bump file versions ;)

**Comment by shivapoudel** [comment]
:P
