### ISSUE TITLE
[REST API] Create A Product - unnecessary image files duplication

### ISSUE THREAD

**Issue by scudai** [woothemes/woocommerce#9664]
I will try to explain this problem, if its not clear please ask me for better explanation.

I have following case: variable product with 3 variations. I will build request with 3 variations where each of them contains one image. Images are already stored on the site where the product is going to be created. As a result of request I can see that on server are stored 6 images. 3 original and other 3 which have been created during request.

You can imagine which kind of problems arrives when you have 1000 product where each has 5-8 variations and each of your images take arround 250KB.

**Comment by claudiosmweb** [comment]
If you send the image link that will be downloaded again, you need to send the image ID instead.

**Comment by ninobo11** [comment]
do you have a sample how the "request" looks like? normally in the documentation it's like this

var data = {
  product: {
    title: 'Premium Quality',
    type: 'simple',
    regular_price: '21.99',
    description: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.',
    short_description: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    categories: [
      9,
      14
    ],
    images: [
      {
        src: 'http://example.com/wp-content/uploads/2015/01/premium-quality-front.jpg',
        position: 0
      },
      {
        src: 'http://example.com/wp-content/uploads/2015/01/premium-quality-back.jpg',
        position: 1
      }
    ]
  }
};

WooCommerce.post('products', data, function(err, data, res) {
  console.log(res);
});
