### ISSUE TITLE
how do I display product unit price in email woocommerce thankyou page?

### ISSUE THREAD

**Issue by waisie** [woothemes/woocommerce#9666]
For example, 2 x $12 =$ 24. I want to display the $12 in thankyou page after the user place the order.

The code is in the order-details-item.php. For default woocommerce thankyou page, they don't display the product unit price. Is there a way to display it? This the woocommerce default code from order-details-item.php. Can someone help me?

    if ( ! apply_filters( 'woocommerce_order_item_visible', true, $item ) ) {
          return;
           }
            ?>
           <tr class="<?php echo esc_attr( apply_filters( 'woocommerce_order_item_class', 'order_item', $item, $order ) ); ?>">
           <td class="product-name">
    <?php
        $is_visible = $product && $product->is_visible();

        echo apply_filters( 'woocommerce_order_item_name', $is_visible ? sprintf( '<a href="%s">%s</a>', get_permalink( $item['product_id'] ), $item['name'] ) : $item['name'], $item, $is_visible );
        echo apply_filters( 'woocommerce_order_item_quantity_html', ' <strong class="product-quantity">' . sprintf( '&times; %s', $item['qty'] ) . '</strong>', $item );

        do_action( 'woocommerce_order_item_meta_start', $item_id, $item, $order );

        $order->display_item_meta( $item );
        $order->display_item_downloads( $item );

        do_action( 'woocommerce_order_item_meta_end', $item_id, $item, $order );
    ?>
        </td>
        <td class="product-total">
           <?php echo $order->get_formatted_line_subtotal( $item ); ?>
        </td>
        </tr>
            <?php if ( $order->has_status( array( 'completed', 'processing' ) ) && (  $purchase_note = get_post_meta( $product->id, '_purchase_note', true ) ) ) : ?>
          <tr class="product-purchase-note">
           <td colspan="3"><?php echo wpautop( do_shortcode( wp_kses_post( $purchase_note ) ) );   ?></td>
        </tr>
        <?php endif; ?>

**Comment by roykho** [comment]
Unfortunately this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

**Comment by eCommerceHints** [comment]
I've written a snippet to show product unit prices on the checkout, thank you page, emails, and order view in my account here: https://www.ecommercehints.com/woocommerce-show-product-unit-price
It utilises hooks so no need to edit the core template files 🙌
