### ISSUE TITLE
Downloadable File URLs & 404 Pages

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#9668]
Hey all,

Came across a situation today - not sure if it's something we can easily fix, something we can restrict during upload, or just something we need to clarify in the docs, bit here's the scoop!

-----

A user has a music download site, where someone can buy an album using a downloadable product. When the user uploaded the file there was a space in the folder name, so the file URL for a single song from the Media Library is:

`http://example.com/wp-content/uploads/SKU123 Album/SongTitle.mp3`

The proper way to get to that file would be:

`http://example.com/wp-content/uploads/SKU123%20Album/SongTitle.mp3`

But in the emails sent out, it's instead removing the space entirely and giving a 404:

`http://example.com/wp-content/uploads/SKU123Album/SongTitle.mp3`

-----

The date upload sorting is turned off, so maybe if that's the case we can change it up so during upload it adds a `-` or `_`?

**Comment by roykho** [comment]
@DanielSantoro How do you upload file with folder?  I have tried to reproduce this but I am not able to upload files with folder structure.

**Comment by DanielSantoro** [comment]
I actually had to spend some time figuring that out too - ftp seems to be
the way I could figure out, but the images were showing up in the Media
Library so it must have been through an upload. I'll test variations, it
might be the sku

**Comment by mikejolley** [comment]
@DanielSantoro @roykho I'm aware of issues like this - it's actually being fixed in WordPress 4.4. See https://core.trac.wordpress.org/ticket/23605 for reference.
