### ISSUE TITLE
Email headings added regardless of woocommerce_email_header placement

### ISSUE THREAD

**Issue by majemedia** [woothemes/woocommerce#9670]
Duplicated on Version: 2.4.10

Steps:

1. Override `templates/emails/customer-processing-order.php` (or any email template) and comment out or remove the `do_action('woocommerce_email_header', $email_heading);` line
1. place order that you'll receive an email with
1. view email

Results

1. Email header is still in place on the processing email.

**Comment by mikejolley** [comment]
![2015-11-23 at 18 32](https://cloud.githubusercontent.com/assets/90977/11345706/ada12b92-9210-11e5-8904-ff0406ebe254.png)

^ Must be looking at the wrong template.
