### ISSUE TITLE
[Settings API] Allow a 'wysiwyg' or 'tinymce' settings field type

### ISSUE THREAD

**Issue by ymazuz** [woothemes/woocommerce#9673]
Extension developers who add anything to the Settings tab—whether via emails, integrations, payment gateways, or shipping methods—may want to allow users to use a styled text editor for some settings/options. For example, you may want your users to be able to edit an html email, or add some styled text content to a WooCommerce Page via your plugin/Extension.

To implement this in settings now, you have to either just use a `'textarea'` and make sure your description thoroughly explains how to add html tags, or write a lot of custom code. I think this should be available via the API so Extension developers can use `'type'  => 'wysiwyg'`(or maybe `'tinymce'`) to throw in WYSIWYG editors and count on WooCommerce to store and retrieve from the db in html.

I started trying to work on this but it was a little over my head, so I won't be submitting a PR any time soon, but I’d like to hear whether WooThemes is interested in implementing it!

**Comment by claudiosmweb** [comment]
You can add new fields too. Very easy to do.
But maybe we can include in #6361

**Comment by ituk** [comment]
was this suggestion included in any wc version? can't find anything about it on the docs.
