### ISSUE TITLE
Replace credit card icons with SVG

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#9675]
So currently our credit card icons are quite blurry and not scalable.  Perhaps we could replace them with SVGs?

Here is a set we could use:
http://muffinresear.ch/payment-icons/
https://github.com/muffinresearch/payment-icons

cc @jameskoster

**Comment by jameskoster** [comment]
No objection here.

**Comment by WPprodigy** [comment]
Ehh, this may need some testing first. I believe there are hosts out there that don't have SVG's in the mime type.

**Comment by maxrice** [comment]
We switched over to using SVGs for payment gateway icons a few months ago and aside from a few theme CSS weirdness, there's been no issues. For reference, the icons are [here](https://github.com/skyverge/wc-plugin-framework/tree/wc-plugin-framework-4.1.1/woocommerce/payment-gateway/assets/images) and we supported a fallback to PNGs [here](https://github.com/skyverge/wc-plugin-framework/blob/wc-plugin-framework-4.1.1/woocommerce/payment-gateway/class-sv-wc-payment-gateway.php#L1129-L1140) :smile_cat:

**Comment by jameskoster** [comment]
@WPprodigy really? Any more info you can share? We should be pretty safe I woulda thought.

**Comment by WPprodigy** [comment]
@jameskoster Last time I looked into, the support for svgs were low. That may have changed though since then, as it's been a while. You can see lots of svg issues popping up in the WP forums: 

- htaccess fix needed: https://wordpress.org/support/topic/could-not-display-svg
- Not working on GoDaddy as of 3 months ago: http://stackoverflow.com/questions/32210637/svg-not-showing-on-godaddy-wordpress-site

**Comment by claudiosmweb** [comment]
This is supported by all browsers: http://caniuse.com/#feat=svg-img

But some servers need to enable the mime-type, usually only very old server. However this is not really a big problem, we can do like @maxrice

**Comment by elipoultorak** [comment]
@WPprodigy what about inlining the SVG in the html? That's also widely supported (http://caniuse.com/#feat=svg) and doesn't require server support.

**Comment by WPprodigy** [comment]
I just think it'd be bad if there were an edge case where even 5% of sites had to enable the filter to support fallbacks. That'd be around 10,000 issues with websites popping up all over support channels.

SVG is definitely the best approach I think, but an automatic fall back would be nice. Here's a js test for it: https://css-tricks.com/test-support-svg-img/. And looks like it may be possible to test in the backend as well: http://www.w3.org/services/svg-server/.

SVG being supported by Apache by default is good though: 

> Note: As of November 2015, the SVG MIME Type was still in the process of being registered with the IANA media type registry for image/* media types, but it is already in wide use, and is included by default in the list of supported MIME Types in the Apache Web server.

**Comment by jameskoster** [comment]
I think if folks are running a server that doesn't support .svg they're likely gonna have bigger issues than missing credit card icons :p
