### ISSUE TITLE
How to add two option set in single product in big commerce also single product have two quantity box

### ISSUE THREAD

**Issue by askaryabbas** [woothemes/woocommerce#9679]
How to add two option set in single product in big commerce also single product have two quantity box and this is required if you click add to cart button. After that in cart page two product added with different quantity

**Comment by roykho** [comment]
Unfortunately this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com

**Comment by askaryabbas** [comment]
Thanks for your comment
