### ISSUE TITLE
Media remains attached to a product after being deleted

### ISSUE THREAD

**Issue by mihaigrigori** [woothemes/woocommerce#9681]
After you delete a media file that is linked to a product as a product gallery, the id of the deleted media post still exists as a custom field for the product. e.g. _product_image_gallery = 55

Expected: when you delete a media post, it should be unlinked from all products using it.

<img width="359" alt="deleting-media" src="https://cloud.githubusercontent.com/assets/4200206/11334804/303fd782-91e0-11e5-96c7-5767e12c387d.png">

**Comment by WPprodigy** [comment]
Tested #9689. Works good :+1:
