### ISSUE TITLE
Can't purchase last item in inventory

### ISSUE THREAD

**Issue by AKlossner** [woothemes/woocommerce#9683]
When the inventory gets down to 1, it won't let a customer purchase it.  It says this: 

SORRY, WE DO NOT HAVE ENOUGH "XXXXXXXXXXXXXXXXXXXX" IN STOCK TO FULFILL YOUR ORDER RIGHT NOW. PLEASE TRY AGAIN IN 60 MINUTES OR EDIT YOUR CART AND TRY AGAIN. WE APOLOGISE FOR ANY INCONVENIENCE CAUSED.

**Comment by mikejolley** [comment]
This means the stock is being held in an unpaid order from another user. The held stock will free up every 60 mins - WooCommerce > Settings > Products > Inventory.

**Comment by AKlossner** [comment]
No... this doesn't work.  It is stuck.  I switch it to a minute... nothing.
SORRY, WE DO NOT HAVE ENOUGH "XXXXXXXXXXX" IN STOCK TO FULFILL YOUR ORDER RIGHT NOW. PLEASE TRY AGAIN IN 1 MINUTES OR EDIT YOUR CART AND TRY AGAIN. WE APOLOGISE FOR ANY INCONVENIENCE CAUSED.
