### ISSUE TITLE
after order processed stock inventory reduced automatically by -ve

### ISSUE THREAD

**Issue by Yeadh** [woothemes/woocommerce#9687]
I have created a store using WooCommerce and using Malibu child theme. Everything is working fine except one thing..

1) When the order is processed completely, the stock inventory for the products gets reduced by equal to the items purchased.

After sometime the stocks for the product is updated by some -ve number and suddenly the stocks is reduced '(x=any number)'. I have screen shot of the -ve number updated in the products of woocommerce (installed with wordpress)

screen shot http://s23.postimg.org/r43im39wr/stock_error.png

when the count for the black klip was 1000, i had purchased one order, then it reduced to 999. after some time, the count is reduced to -11 'Out of Stock'

I have no idea why it is happening ? Any help in this regard shall be highly appreciable. my site is about to launch soon.

**Comment by Yeadh** [comment]
Nobody don't knows this?

**Comment by WPHero** [comment]
The problem is probably in the payment gateway. See this function. Reduce stock levels before making the payment if anyone break the payment and pay back then stock levels will reduce again.

```
function process_payment( $order_id ) {
	global $woocommerce;
	$order = new WC_Order( $order_id );

	// Mark as on-hold (we're awaiting the cheque)
	$order->update_status('Pending', __( 'Awaiting cheque payment', 'woocommerce' ));

	// Reduce stock levels
	$order->reduce_order_stock();

	// Remove cart
	$woocommerce->cart->empty_cart();

	// Return thankyou redirect
	return array(
		'result' => 'success',
		'redirect' => $this->get_return_url( $order )
	);
}

```

**Comment by mikejolley** [comment]
I concur that it's likely mishandling by the gateway. I don't see a problem in the reduce stock function:

https://github.com/woothemes/woocommerce/blob/753014da5a6df243928e4b7baebb035300ab70ff/includes/abstracts/abstract-wc-order.php#L2470

Check orders notes, and rule out plugins and gateways before re-opening.
