### ISSUE TITLE
variable product prices separator

### ISSUE THREAD

**Issue by matteomatthew** [woothemes/woocommerce#9688]
I would like to modify size of the separator between min and max price of a variable product.
Screenshot: http://s27.postimg.org/42nm3qnqb/IMG_0632.jpg

Thanks to everybody in advance

**Comment by roykho** [comment]
Unfortunately this is not a support channel.  This is for bug reports only.

You can post this kind of questions in our public support forum: http://wordpress.org/support/plugin/woocommerce or if you're a WooThemes customer, please go to our support portal: http://support.woothemes.com
