### ISSUE TITLE
Reports not working

### ISSUE THREAD

**Issue by calendarboy** [woothemes/woocommerce#9692]
When I click on WooCommerce/Reports, it defaults to a chart for the past 7 days. It shows the figures to the left (gross sales, net sales, average daily sales, etc.)

However, if I click on This Month, Last Month, or Year it shows $0.00 for all dollar amounts. 

If I use "Custom:" it works for a two week period, but shows only zeroes when the period stretches to 15 days. 
![reports-14days](https://cloud.githubusercontent.com/assets/5973789/11374330/60fed864-928a-11e5-8d5a-2ee3e3e650d3.png)
![reports-15days](https://cloud.githubusercontent.com/assets/5973789/11374331/61008164-928a-11e5-9869-5e44a15b15a0.png)

**Comment by mikejolley** [comment]
It's due to the size of the query. This in 2.5 will help: 

https://github.com/woothemes/woocommerce/commit/4f0cc137ccf86da81d137373c029410591b69bbf

**Comment by calendarboy** [comment]
I thought a 14 day limit on reports would be something that you would want to fix on future releases.

**Comment by mikejolley** [comment]
..yes, which is why I referenced the above commit.

**Comment by uwehog** [comment]
I have the same problem and the above mentioned code above 
did not solve it (WooCommerce Version Version 2.4.12)

![wc_reports_fehlende_umsatzzahlen](https://cloud.githubusercontent.com/assets/16352340/11899962/043ad3fe-a5a3-11e5-94bf-beb20b4803b7.jpg)
