### ISSUE TITLE
add_to_cart shortcode improvement

### ISSUE THREAD

**Issue by dziudek** [woothemes/woocommerce#9693]
Currently the add_to_cart shortcode has no possibility to totally remove the **style** attribute from the output code. If the **style** parameter is empty, the code will contain an empty **style** attribute.

In my pull request I've added a solution for this issue.

**Comment by claudiosmweb** [comment]
Use `[add_to_cart id="99" style=""]`.

**Comment by claudiosmweb** [comment]
> the code will contain an empty style attribute
No one will die because that.
