### ISSUE TITLE
Paypal add-on send shipping info NOT billing info to Paypal

### ISSUE THREAD

**Issue by atstockland** [woothemes/woocommerce#9695]
If you check the box "ship to different address" and click "place order"...Paypal loads the shipping information.  This is incorrect, it should load the billing information.  If I wanted to pay for something, but ship it to someone else...why does Paypal receive the 'ship to' info in their payment form?

**Comment by roykho** [comment]
I am not sure I understand you.   PayPal should always receive the shipping address unless billing is the shipping address.

**Comment by roykho** [comment]
Perhaps this setting here will help you ![](http://cld.wthms.co/1gDyp/2f1eTIZa+)

**Comment by atstockland** [comment]
Thats it!  However, I can not find this setting.  I found "invoice prefix" (just above it).  Where is this setting?

**Comment by atstockland** [comment]
Paypal express checkout is what I have enabled.

**Comment by roykho** [comment]
Ok that is a completely different issue then.  This is for WooCommerce core.  PayPal Standard comes with core so the setting is for that.  If you're referring to express, and assuming you purchased that from WooThemes, you need to open a ticket about that.

**Comment by atstockland** [comment]
OK.  thanks.  I did find the setting...and it wasn't checked.
