### ISSUE TITLE
Simple Product price not displaying in admin list or on front site

### ISSUE THREAD

**Issue by Albofish** [woothemes/woocommerce#9698]
Previously reported by another user and closed in #9400 

After upgrading our server to PHP 5.6.15 any new product no longer displays a price on the front of the site or in the admin products list. The Regular Price field is populated when editing the product. If we add a sale price the regular price is displayed, but we can not then remove the sale price.

Tested on 4 different sites with different themes / plugins and a fresh install with just WooCommerce and Twenty Fifteen.
Screenshots
-----------
![woo-admin](https://cloud.githubusercontent.com/assets/2026297/11394251/d6d9d738-935b-11e5-87c3-3d04cbaa66a0.jpg)
![woo-edit](https://cloud.githubusercontent.com/assets/2026297/11394253/d6e1fcb0-935b-11e5-82a8-c67ca94bf90a.jpg)
![woo-front](https://cloud.githubusercontent.com/assets/2026297/11394252/d6db9d5c-935b-11e5-94bb-b099103d2d22.jpg)
Support report
---------------

### WordPress Environment ###

Home URL: http://wptest.[edited].co.uk
Site URL: http://wptest.[edited].co.uk
WC Version: 2.4.10
Log Directory Writable: ✔  /home/[edited]/public_html/wptest/wp-content/uploads/wc-logs/
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.15
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
SUHOSIN Installed: ✔
MySQL Version: 5.5.46
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.10
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.4.10

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: Page not set
Basket: Page not set
Checkout: Page not set
My Account: Page not set

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Fifteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
-------------

**Comment by mikejolley** [comment]
Since this one is online if you want to give me access that would be helpful.

**Comment by Albofish** [comment]
Hi @mikejolley thanks, I've sent you an email with login details.

**Comment by mikejolley** [comment]
@claudiosmweb here is a new one for you. When the _sale_price is empty, it comes up NULL.

https://github.com/stefanesser/suhosin/issues/62

PHP 5.6 + suhosin. Im adding a workaround but take note for future issues.

**Comment by highacid** [comment]
How can I solve this issue? I see all threads closed...

**Comment by Albofish** [comment]
https://github.com/woothemes/woocommerce/commit/28dcb9ddbccff96698173d7c2eedac4f7b48e2ae is the fix @mikejolley put in place. It will be fixed when https://github.com/woothemes/woocommerce/releases/tag/2.5.0-beta-3 is out of beta.

**Comment by drazeni** [comment]
Just to mention, have same issue here on a server with PHP 5.6.16, I tested the copy of the same site on my development server which has 5.5.9-ubuntu and everything worked fine.

I had to resort to a workaround in the meantime until resolve, where I put in a fictitious sale price and schedule it in the past, then it would show the product regular price.

There were issues where the orders we're not reflecting either, this may be a seperate issue but I suspect it's also due to php version / woocommerce issue, since this issue also arose coincidentally the same time.

**Comment by drazeni** [comment]
Just another heads-up, I rolled back the PHP version on the server with the issue to 5.5.31 and the site/product prices seem to be operating normally again.

**Comment by drazeni** [comment]
Hi guys, any update on this please, has it been resolved? We need to update the hosting server's PHP version to the latest (which is when this issue first occurred).

Thanks.

**Comment by Albofish** [comment]
@drazeni It was fixed in the beta of 2.5, not sure if this bad it out of beta but I'd assume it did. So I'd advise upgrading if you haven't already.

**Comment by drazeni** [comment]
Thanks Albo, we'll try the PHP and woocommerce updates. Hopefully it's ok. I see the latest woocommerce version currently is 2.5.5 in WP admin panel.
