### ISSUE TITLE
[WC 2.5] Move email description

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#9701]
![](http://cld.wthms.co/12ATe/WhKGKXtW+)

Can we move the `?` icon before the email name? That way they will line up, like in the System Status.

**Comment by mikejolley** [comment]
@SiR-DanieL what about making the ? align to the right of the column?

**Comment by SiR-DanieL** [comment]
It'd look like this

![](http://cld.wthms.co/161Nn/3QWNTzU1+)

Honestly I don't like it either way. Tried it in different places in the table but it always looks misplaced.

**Comment by roykho** [comment]
I like it the way it was... :)

**Comment by mikejolley** [comment]
Let's leave it then :)
