### ISSUE TITLE
Checkout AJAX conflict when registering custom post types or taxonomies

### ISSUE THREAD

**Issue by zackphilipps** [woothemes/woocommerce#9703]
See here: https://wordpress.org/support/topic/urgent-conflict-with-woocommerce-2410?replies=15

Is there any way to prefix the checkout data that is passed with `wc_` ? So instead of `state`, `city`, `currency`, it would be `wc_state`, etc.?

**Comment by sc0ttkclark** [comment]
+1 on this, definitely can cause hours/days of trouble tracking the issue down. Maybe less now that it's posted about in a few places :)

**Comment by mikejolley** [comment]
Prefixing would likely cause issues with BW compat. Posting variables with the same name as post types should not break requests though. I think I can fix that without prefixes.

**Comment by zackphilipps** [comment]
Thanks @mikejolley !!
