### ISSUE TITLE
Coupons - Include / Exclude Product Child Categories From Parent

### ISSUE THREAD

**Issue by JamesSimpson** [woothemes/woocommerce#9704]
After just dealing with a clients Black Friday code, I have lost the will to live, and looking through the issues board, I'm surprised no one else has mentioned this before.

Basically the way the coupon works at the moment, you add in EVERY single category that is either included or excluded. This is all well when the category base is small, but what if the child category list is huge!

There should be a little checkbox under the Include / Exclude category box to automatically include/exclude the child categories.

I.E. Add in the parent category in the text box, and press a check button to set this across every single child category.

**Comment by mikejolley** [comment]
> There should be a little checkbox under the Include / Exclude category box to automatically include/exclude the child categories.

Would be better if hierarchy were respected.

**Comment by JamesSimpson** [comment]
Exactly Mike :+1:
