### ISSUE TITLE
Layered navigation widget disappears when changing attribute slug

### ISSUE THREAD

**Issue by panvagenas** [woothemes/woocommerce#9710]
Ok it seems attribute in layered navigation widget is stored by attribute slug. This is wrong if you ask me, because WordPress allows to change attribute slugs. Instead the attribute id should be stored.

Reproduce:

1. Create an attribute
2. Choose it in layered navigation widget attribute option
3. Change attribute slug
4. Option in layered navigation widget is no longer valid

**Comment by mikejolley** [comment]
Attributes are taxonomies and thus do not have IDs. Slug is the only way in which they can be tracked.

You'll also lose terms if you change slugs so be careful.

**Comment by panvagenas** [comment]
You kidding me, right?
Whatever man...
