### ISSUE TITLE
Attributes mixed up with a category from other attribute.

### ISSUE THREAD

**Issue by SephTFR** [woothemes/woocommerce#9711]
There are instances that in my attributes, its being mixed up with categories from other attributes. Pls check this screenshot..http://screencast.com/t/yHn6GYee2wTB "troy" should be in the Brand attributes.

**Comment by mikejolley** [comment]
Attributes, like categories, are just terms and are handled 100% by WordPress itself. At some point you must have either added or imported a product category called 'troy' as well.
