### ISSUE TITLE
Auto-drafting variable products with no variations is bad for e-commerce

### ISSUE THREAD

**Issue by lkraav** [woothemes/woocommerce#9713]
The problem is `WC_Product_Variable::sync()` doing too much assumption.

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-product-variable.php#L721

I have live stores where all variations temporarily go inactive. It doesn't mean that the product page should drop off the Internet, which causes confusing 404-s for visitors, possible SEO penalties, etc. More optimal action is to always keep the product page live, but provide an alternate call to action for products that have run out of active variations. Full solution may be out scope for WC itself, but at the very least the product page needs to always stay live.

There are currently no opportunities to filter this behavior. Can we at least get an `apply_filters()` call going here?

**Comment by lkraav** [comment]
Tyvm sir. How many 2.4-branch point releases are planned before 2.5? I might have to deploy a monkey-patch of this to at least one customer if 2.5 isn't right around the corner.

**Comment by mikejolley** [comment]
1 - it won't be in before 2.5.
