### ISSUE TITLE
Bug with WooCommerce Plugin on WordPress (Setting > Shipping > International Flat Rate)

### ISSUE THREAD

**Issue by jakeohlion** [woothemes/woocommerce#9715]
Hi,

I cannot enter any number into the shipping class cost under International Flat Rate, it does not register when I click on "Save changes". I was able to do it for Flat Rate though.

<img width="788" alt="shipping class cost" src="https://cloud.githubusercontent.com/assets/16048455/11445325/36d01290-9566-11e5-88aa-e2dc83a1dd79.png">

This is my system report:

### WordPress Environment ###

Home URL: http://georgeannadorai.com
Site URL: http://georgeannadorai.com
WC Version: 2.4.10
Log Directory Writable: ✔  /home/georgean/public_html/wp-content/uploads/wc-logs/
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.3.29 - We recommend a minimum PHP version of 5.4. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
SUHOSIN Installed: ✔
MySQL Version: 5.5.42
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.10
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (12) ###

Builder Button: by Themify – 1.0.8
Builder Contact: by Themify – 1.1.0
Builder Counter: by Themify – 1.0.8
Builder WooCommerce: by Themify – 1.1.1
Donation Button: by mbj-webdevelopment – 1.3.3
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
MailMunch - Increase your Email Subscribers by over 500%: by MailMunch – 2.0.2
Paid Memberships Pro: by Stranger Studios – 1.8.6.7
Paid Memberships Pro - WooCommerce Add On: by Stranger Studios – 1.2.10
The Events Calendar: by Modern Tribe
Inc. – 3.12.6

Themify Portfolio Post: by Themify – 1.0.1
WooCommerce: by WooThemes – 2.4.10

### Settings ###

Force SSL: –
Currency: SGD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #4660 - /shop/
Basket: #4663 - /shop/basket/
Checkout: #4667 - /shop/checkout/
My Account: #4867 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Split
Version: 1.0.6
Author URL: http://www.themify.me
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by WPprodigy** [comment]
Hi @jakeohlion,

I haven't been able to replicate this issue. Could you try disabling all others plugins and the theme and test again?

**Comment by mikejolley** [comment]
This will be due to the length of the name of the settings field - your server may have a limit. International uses more characters than flat rate.

To work around, rename the shipping class/shipping class slug. I'll see if we can use IDs in future versions.

**Comment by jakeohlion** [comment]
Thanks Mike!!

*Relations Team*
Light Marketing Pte. Ltd.
–––––––––––––––––––––––––––––––––
*People First, Planet Second, Profit Third.*
–––––––––––––––––––––––––––––––––
*w:* www.lightmarketing.com.sg
*e:* mail@lightmarketing.com.sg
*Follow us* on Facebook <http://www.facebook.com/lightmarketingsg>

Privileged/Confidential Information may be contained in this message. If
you are not the addressee indicated in this message (or responsible for
delivery of the message to such person), you may not copy or deliver this
message to anyone. In such case, you should destroy this message and kindly
notify the sender by reply email. Please advise immediately if you or your
employer does not consent to email for messages of this kind. Opinions,
conclusions and other information in this message that do not relate to the
official business of Light Marketing Pte. Ltd. shall be understood as
neither given nor endorsed by it.
