### ISSUE TITLE
Variable product with regular and sale prices identical for all variations won't display regular price

### ISSUE THREAD

**Issue by michelpozio** [woothemes/woocommerce#9716]
When having a variable product with all variations having the same regular price (example : €2.00) and the same sale price (example : €1.00),
the front office will not display the "old" regular price, only sale price.
Example :
variation 1 : regular price = 2.00 / sale price = 1.00
variation 2 : regular price = 2.00 / sale price = 1.00
variation 3 : regular price = 2.00 / sale price = 1.00
... front office will never display regular price.

When one variation has a differrent regular or sale price, 
the front office will correctly display the "old" regular price + the sale price.
Example :
variation 1 : regular price = 2.00 / sale price = 1.00
variation 2 : regular price = 2.50 / sale price = 1.50
variation 3 : regular price = 2.80 / sale price = 1.80
... front office will display regular price + sale price.

**Comment by mikejolley** [comment]
Does not appear to be the case: https://dl.dropboxusercontent.com/s/tiet0l2ee6rqoo8/2015-11-30%20at%2011.16.png?dl=0

When prices are the same, only the 'product level' price is shown, as pictured.

**Comment by michelpozio** [comment]
Woops sorry, in fact it was a theme issue.
