### ISSUE TITLE
Woocommerce Tab Manager 1.4.1 installation leads to 500 server error

### ISSUE THREAD

**Issue by rosaiani** [woothemes/woocommerce#9717]
I have updated the tab manager on our website: www.plau.co and it resulted in a 500 server error.
The site works fine when the plugin is deactivated.
Any thoughts on why this is happening?
I use WPML, Wordfence and Woocommerce.
Best
Rodrigo

**Comment by roykho** [comment]
So this is for bug report on WooCommerce only.  Please open a ticket with WooThemes support http://support.woothemes.com/hc/en-us
