### ISSUE TITLE
[REST API] coupon_lines in Orders endpoint should return coupon type 

### ISSUE THREAD

**Issue by limbera** [woothemes/woocommerce#9719]
At the moment it returns id, amount and code. Amount is not useful unless we know the type too (e.g. percent or fixed, cart or product). It would make sense to put more information in the response to avoid having to make a call to the coupon endpoint too.

**Comment by mikejolley** [comment]
Looking at this, thats the only data stored at order level.

>  Amount is not useful unless we know the type too (e.g. percent or fixed, cart or product).

This is also not true - the amount you're returned was the **actual** discount amount. So if it was originally a % based coupon, you'll get the amount of $ it equated to, not the value of the coupon originally.
