### ISSUE TITLE
Problems with backslash in SKU

### ISSUE THREAD

**Issue by elipoultorak** [woothemes/woocommerce#9721]
If you create a SKU with a backslash in it, for example "SKU\123", there are a few problems:

1. If you type `SKU\123` in the SKU text field, it'll insert it in the database without escaping the slash, so `SKU\012` becomes `SKU�12` (Hex dump: `53 4b 55 ef bf bd 31 32`), and `SKU\123` becomes `SKU123` (without the slash). The only way to insert it properly is by typing `SKU\\123`. I'm not sure if this is also a security issue, but definitely a problem.

2. If you insert it with double slashes, you can create multiple products with the same SKU. Steps to reproduce: Create a product with SKU `SKU\\123`, which will be converted to `SKU\123`. Now create another product with SKU `SKU\\123`, and you'll have 2 products with the same SKU.

**Comment by elipoultorak** [comment]
Another problem with backslashes is that the API sometimes expects the SKU to have double slashes (SKU\\123) and sometimes just one slash (SKU\123). For example, `/wc-api/v3/products/bulk` will only match the product id to the sku (using `wc_get_product_id_by_sku`) if you have 1 slash (otherwise it won't update the product), while `/wc-api/v3/products` with `filter[sku]` will only return the product if you have double slashes.
It would be nice to have consistent behavior or at least document when to use what.

**Comment by claudiosmweb** [comment]
> If you type SKU\123 in the SKU text field, it'll insert it in the database without escaping the slash, so SKU\012 becomes SKU�12 (Hex dump: 53 4b 55 ef bf bd 31 32), and SKU\123 becomes SKU123 (without the slash)

This is expected behavior... Fpr your server you are escaping the number `1`.

> The only way to insert it properly is by typing SKU\\123. I'm not sure if this is also a security issue, but definitely a problem.

In fact perhaps can be better if we start use `wp_unslash()` and remove any `\`

@mikejolley this is not an issue only in API, we must first change how we handle it.

**Comment by claudiosmweb** [comment]
@mikejolley We strip slashes here: https://github.com/woothemes/woocommerce/blob/28dcb9ddbccff96698173d7c2eedac4f7b48e2ae/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L845

But it don't really works... I just tested and still pass `SKU\\123` or `SKU\123`.
We need to do something, like strip all `$_POST` for this work.

**Comment by elipoultorak** [comment]
@mikejolley What do you want to do? Remove all slashes completely, or turn `\\` into `\`? It would make more sense if the input was accepted as a literal (if you type 1 slash, it inserts 1 slash into the database, if you type 2, it inserts 2).

**Comment by mikejolley** [comment]
WP core strips all slashes on POST (or should) so the answer is probably to do no strip, and fix the unique SKU check.

**Comment by mikejolley** [comment]
Related: https://core.trac.wordpress.org/ticket/27421

**Comment by claudiosmweb** [comment]
> while /wc-api/v3/products with filter[sku] will only return the product if you have double slashes.

You'll need to escape it, will be mandatory in some programming languages too.

**Comment by elipoultorak** [comment]
@claudiosmweb So what's the difference between /wc-api/v3/products and /wc-api/v3/products/bulk ?

**Comment by claudiosmweb** [comment]
@elipoultorak easy.
You use a filter by the URL:

```
http://yoursite.com/wc-api/v3/products?filter[sku]=SKU\\123
```

But for ´/wc-api/v3/products/bulk´ you send a json!

**Comment by elipoultorak** [comment]
@claudiosmweb ok, if that's the expected behavior, then fine. I just couldn't work out why my json didn't work until I realized this is the problem :-)
Maybe you should specify in the documentation when to escape, and when not to escape.

**Comment by claudiosmweb** [comment]
Escape when is a URL!

**Comment by elipoultorak** [comment]
Yes, now I know, thanks :-)
