### ISSUE TITLE
Shop base page problems when changing the shop base id page

### ISSUE THREAD

**Issue by zauan** [woothemes/woocommerce#9725]
After changing the shop base id page, the rewrite rules are not properly flushed and the user needs to manually save the permalinks

Steps to reproduce : 
1. Change the shop base id to a different page
2. Look at the new page. You will see that no products are displayed

I've looked at the code and i saw that the rules are flushed from WC_Admin_Settings::save() function, however, this doesn't seem to work properly.

**Comment by mikejolley** [comment]
This can be affected by other things, such as plugins adding their own rewrite rules, or flushes. That said, our own flush does usually work.

On my test install, with a 'shop base' permalink setup, I was able to change this page and have products display on the new page without issue.

This was on WC 2.5. Beta 2 and WP 4.4 RC.

Steps taken:

1. Set permalinks to shop base
2. View shop page
3. Settings > Catalog > Display, change page
4. View new shop page

Products visible.
