### ISSUE TITLE
French translation not complete

### ISSUE THREAD

**Issue by juliette-lev** [woothemes/woocommerce#9726]
Hello,

I got a WP theme with woocommerce 2.3.11 on it.
I changed the language to fr_FR but a lot of pages are not translated... You can see on My Account page, there is only "Mon Adresse" in french, all the rest is in english : 
![account french](https://cloud.githubusercontent.com/assets/16083848/11473861/49df1dde-9775-11e5-9e73-bb1283fc581b.jpg)
How can I do ?

Thanks !

**Comment by mikejolley** [comment]
You can contribute here https://translate.wordpress.org/projects/wp-plugins/woocommerce

Thanks

**Comment by juliette-lev** [comment]
Hi 

I don't want to contribute in the translation, I need help on a bug !
Did you at least read the message before closing it ?!

**Comment by mikejolley** [comment]
If the translation is incomplete, it needs to be contributed to by the community to add those missing strings. The only french phrase I know is "Omelette du fromage" so I'm afraid I won't be much help :)

**Comment by mikejolley** [comment]
Additionally, if the translation shows as complete (which @corsonr tells me it is) the theme may be overriding templates with its own text domains, so you'll need to translate the theme yourself as well.

**Comment by corsonr** [comment]
Effectivement, toutes les versions de WooCommerce sont traduites en Francais à 100%

**Comment by juliette-lev** [comment]
okay, so maybe you or @corsonr could tell me the file where the translation
should be in?
Because in the files
woocommerce-admin-fr_FR.mo
woocommerce-admin-fr_FR.po
woocommerce-fr_FR.mo
woocommerce-fr_FR.mo
I can't see the sentences in english neither....

It could help a lot :/

Thanks

2015-11-30 16:47 GMT+01:00 Mike Jolley <notifications@github.com>:

**Comment by mikejolley** [comment]
If its the theme, it won't be in any of those.

**Comment by greguly** [comment]
Hi  juliette-lev, 

Try with a default theme like twenty-twelve.

Cheers,
Gabriel

**Comment by corsonr** [comment]
Here is the same page (my account) with Twenty Fifteen, WooCommerce 2.3.11 in French:

![](http://cld.wthms.co/16ih8/3crxqBS7+)

All strings are translated.
