### ISSUE TITLE
Dashboard Access broken for User Roles with Basic ("read" only) Capabilities

### ISSUE THREAD

**Issue by d4mation-** [woothemes/woocommerce#9729]
WooCommerce Version: 2.4.10
WordPress Version: 4.3.1
Theme: Any (Tested with TwentyFifteen as well as a few other custom themes)

How to reproduce: 
* Create a User with a User Role that has only the `read` capability (such as the `customer` User Role)
* Log in under that User
* WP Admin Bar will be missing, and attempting to access `/wp-admin/profile.php` results in a White Screen. No obvious PHP errors and no issues in the Browser's Developer Console
* Logging out via `/wp-login.php?action=logout` still works

I've tested this on a blank WordPress install with only TwentyFifteen and WooCommerce active and was able to consistently reproduce this.

**Comment by roykho** [comment]
If you login with a `customer` role, it should redirect you back to the frontend `my account`.  Same goes with if you try accessing `wp-admin/profile.php`

**Comment by d4mation-** [comment]
In my case, it is redirecting me to `wp-admin/profile.php` which is why I mentioned it specifically. That's pretty strange.

**Comment by roykho** [comment]
Is this a custom customer role or is the default that was created by WooCommerce?

**Comment by d4mation-** [comment]
I've tried both as I was originally using a Custom one and figured that may have been the problem, but I had the same issue with the default `customer` role.

**Comment by roykho** [comment]
Have you tried testing with a fresh database that does not contain the custom role you created?

**Comment by d4mation-** [comment]
I figured it out. It was because I never ran the WooCommerce setup wizard.

It is attempting to redirect to the My Account page which doesn't exist, so it White Screens. Makes sense now that I realize that's what it is trying to do. Maybe it should fallback to the WP Dashboard for the My Account page if it hasn't been ran and show an `admin_notice`?

I'll go ahead and close this.
