### ISSUE TITLE
Documentation Not Complete: enable_html_*

### ISSUE THREAD

**Issue by codingideas** [woothemes/woocommerce#9730]
I'm reading the documentation trying to use these two:

enable_html_description
enable_html_short_description

which I see here: https://woothemes.github.io/woocommerce-rest-api-docs/#products-properties

but I don't see how to use those here: https://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product

if you tell me how I can update the docs myself. I see enable_html_description is a bool but where do I put it? What about short_description which is a string?

**Comment by WPprodigy** [comment]
The GH repo for the docs can be found here: https://github.com/woothemes/woocommerce-rest-api-docs

I think the names are pretty descriptive of what they do though. Both allow for html to be in the descriptions: https://github.com/woothemes/woocommerce/blob/eeafb202aaa2e43fcd63e8b6ae4ecb6e634b1ecf/includes/api/class-wc-api-products.php#L274-L285

You use them just like any other attribute. When creating a product like this: http://cld.wthms.co/13da0/5KWx8znH, you would just add in an attribute for `enable_html_description` as set it to true. Then in your description, you can have html that will be parsed.
