### ISSUE TITLE
Cart quantity input maximum can be a negative number

### ISSUE THREAD

**Issue by pmgarman** [woothemes/woocommerce#9733]
Sometimes due to raw order volume even though products do not have backorders enabled we can end up with products with negative inventory. When this happens the quantity input will be set to a maximum with a negative number, so if you try to update your cart it will say "value must be less than {negative number}" This should probably be no lower than 0.

![](http://c.pmgr.mn/1gEIN+)

**Comment by WPprodigy** [comment]
When the product has a negative inventory and backorders are not enabled, shouldn't it not have an input at all? Thats what I got when testing this:

Product Settings: http://cld.wthms.co/3Nhs/4swgwMr8
Front-end: http://cld.wthms.co/1hwV3/2IIT39Qh

**Comment by pmgarman** [comment]
Try adding the product to your cart then go set the product out of stock and negative inventory (as if someone bought product out from under you). Then go to the cart where the product still shows up.

**Comment by WPprodigy** [comment]
Ahh, yea I could get the pop-up to do that on the cart page. But I mean, the shiny red alert in there as well:

![](http://cld.wthms.co/pHuw/4dLiXpsm)

**Comment by WPprodigy** [comment]
So here is where the max number is given: https://github.com/woothemes/woocommerce/blob/master/templates/cart/cart.php#L109

If you wrap it with `max( $var, 0 )`, then the negative issue is fixed, and products that have stock work the same. However, product's w/o stock become a problem as the max value for them becomes "0"
