### ISSUE TITLE
Consider moving orders & order meta to custom tables

### ISSUE THREAD

**Issue by pmgarman** [woothemes/woocommerce#9735]
Note: this would majorly break backwards comaptability. Before getting into the benefits here are the immediate cons and break points that I'm already aware of and thinking about.

- All basically anyone who is doing any pulling, querying, reporting, etc of orders will break
- All direct queries and reporting using postmeta will also break
- The entire UI of orders will break because it is no longer a custom post type.
- > All metaboxes will no longer function and need rebuilt for whatever the new UI is which won't be a CPT
- > All taxonomies registered to this CPT will no longer function
- *_post_meta functions will no longer work properly for orders
- The migration script will be brutal
- *every extension that touches orders UI or meta, will likely need a major update* ... many extensions just using existing actions or filters in WooCommerce may be unaffected.

:boom: The for sure, and potential breakage is impressively large.

#### however

I'm looking through orders right now and on average in a our fairly typical WooCommerce site each order has about 40-50 postmeta. Probably 75-80% of this is inserted when the order is first created. For the specific order I am looking at right now. Of 39 rows in the order I am looking at right now, I believe 36 rows of postmeta were inserted by WooCommerce core without any other extensions.

**WooCommerce with high order volume in the current configuration**

For the sake of simplicity lets just look at the inserts to the posts and postmeta table of the database when an order is created only for orders (so not tracking coupon usage, order notes, etc) and for simple math lets just say for each 1 order 30 metas are inserted. So when you process 2 orders, 60 metas are inserted. 100 orders, 3000 metas are inserted. Not even considering how this doesn't work well when orders are created in rapid concurrency, this over time is going to create a gigantic postmeta table. Meaning the orders in WooCommerce are going to impact all other queries and inserts into this table (1).

Of the 36 core metas in my example order... probably 3/4 of those could easily be a column in an orders table. Using simple math again lets say 25 of 30 post metas are taken out of postmeta and put into the order table. For every 1 order only 5 metas are inserted, and into a separate table at that. Order inserts would be about as large as an insert to the posts table which has about as many columns. Inserts are far fewer. When handling 100 orders, only 500 metas are added.

Now go one step deeper, now you have a much flatter set of order data. Reporting can be greatly improved at this point because I would imagine querying the data would be faster. Far less joins required just to get some simple data.

My rough sketch of a proposal:
- Two new tables `wp_woocommerce_orders` and `wp_woocommerce_ordermeta`
- Orders would have approx 25-30 columns, order ID, date, status, billing/shipping details, totals, etc.
- Order meta would just be using the WordPress metadata just like order items do currently.
- Attempt to reproduce the posts UI for custom orders so that metaboxes / etc still work as expected to try to reduce breakage. Possibly in a way that just deprecates it in an effort to handle it differently in the future? Not sure the best course of action here but attempting saving as many extensions from the trash as possible seems like a good idea.
- A minor update after this major update could focus on reporting and greatly improve the WooCommerce reporting.

What about other post types of WooCommerce? 
- Coupons > possibly may benefit from the same changes but may be better managed separately and not at the same time as orders?
- Products > personally I think are perfect just as they are as posts. Scaling WordPress for a large number of posts is not a hard thing to figure out, products are basically static content and scaling WordPress for static content can be done pretty easily (look at all the blogs on WordPress getting millions upon millions of page views). Products the only thing that really changes on them is when an order is place the inventory may be adjusted.

**Comment by lukecav** [comment]
Why not something similar for products then wp_woocommerce_products and wp_woocommerce_productmeta?

https://gist.github.com/lukecav/7a0fb38cc25055a1b392

**Comment by claudiosmweb** [comment]
Not a bad idea, but maybe for WooCommerce 3.0... Since it will break a lot of people.

**Comment by mikejolley** [comment]
Orders perhaps, but definitely not products. Kill that idea now (saw it bought up on Facebook and above) - CPT are perfectly suited for products.

**Comment by lukecav** [comment]
So why the push back for having product use custom tables instead of being a CPT?

**Comment by lukecav** [comment]
One example WooCommerce Memberships uses two custom tables.

**Comment by bekarice** [comment]
> One example WooCommerce Memberships uses two custom tables.

Nope, no custom tables in Memberships thus far. Have considered this for membership rules, but nothing there yet.

I think @pmgarman hit it on the head as to why this is change would help orders but wouldn't really matter for products as much.

**Comment by lawkwok** [comment]
Separate order tables would also make migrating WooCommerce sites much simpler.

Let's say you are working on a staging site, but have a live site that is still accepting orders. It's not currently possible to cleanly import orders to the staging site since virtually any post/media creation will cause conflicts in post IDs.

**Comment by claudiosmweb** [comment]
@lukecav 
> So why the push back for having product use custom tables instead of being a CPT?

Because:

> CPT are perfectly suited for products.

Every day in your shop you create 5000 products?
I don't think so... But you can easily have 5000 orders every day or more.

**Comment by thenbrent** [comment]
@pmgarman you don't need to go to all that trouble, you can achieve the same outcome by adding the following one liner to `WooCommerce::__construct()`:

```
$non_existant_variable->destroy_all_stores();
```

\</trolling\>

Jokes aside, are custom tables really necessary for core? They are essential for the 1% of stores with over a few hundred thousand orders. They also introduce benefits for other stores, but do the benefits of the custom tables for those 99% of sites outweigh the damage of breaking every non-professionally managed WooCommerce site?

A less nuclear option would be to abstract the way order data is stored/retrieved into an interface so that it can be swapped out for custom tables when needed.

An example of doing this can be seen in Action Scheduler, which uses a [custom post type](https://github.com/Prospress/action-scheduler/blob/dc19579cf8b88653777c763a1f4780b06f31daa7/classes/ActionScheduler_wpPostStore.php) for storing/querying scheduled actions by default, but all data storage and retrieval is done via an [abstract class with interface methods](https://github.com/Prospress/action-scheduler/blob/b2daf869e7053dc3f3f27e954676ee7c30e6d4a0/classes/ActionScheduler_Store.php) so that the location of the data is totally abstracted and easily [changed](https://github.com/Prospress/action-scheduler/blob/b2daf869e7053dc3f3f27e954676ee7c30e6d4a0/classes/ActionScheduler_Store.php#L122) on high volume sites.

In order for 3rd party code to work on sites using a custom store, that code would still need to be updated to use the new APIs instead of current post APIs, like `get_posts()` or `update_post_meta()`, or querying the DB directly, but at least it would be a situation of opting-in to the breaking changes for the sites that need it rather imposing it on all sites. Ideally, the sites that need it or care about it are professionally managed so they can safely manage using custom tables without break things.

**Comment by pmgarman** [comment]
Abstracting the data would be a great first step in allowing this to happen. However I think that this is really going to make it **worse** for extensions more than make it better. Though it would still be better than nothing.

- By defaulting to CPT for orders you will not actually force anyone to use proper methods, very few people will update, making attempting to use the abstracted data harder to actually switch to because extensions won't use them.
- Moving to tables by default will allow for better reporting and searching of orders on even small sites. I think we can all agree reporting and searching for orders can use some improvement.

Besides breaking basically everything that hooks into order meta or queries the posts table directly for orders... are there any negatives to moving data to custom tables? I think the positives are obvious, finding every negative to why it shouldnt happen and then examing each of thsoe would probably be a good way to start determining if this is something that should happen in core. I can already attest to the fact that WooCommerce *cannot* sustain itself under high order concurrency without this due to the volume of postmeta. So one way or the other there needs to be some method of doing this in order to scale WooCommerce which I assume is a goal everyone would like to achieve :)

**Comment by DavidAnderson684** [comment]
I hope that before inviting the hatred of the entire human race (+/- a few people not using WooCommerce yet), there'll be some serious gathering of performance data to compare the gains and losses!

> I can already attest to the fact that WooCommerce cannot sustain itself under high order concurrency without this due to the volume of postmeta.

So, is it the use of CPT, or of postmeta, that's the real problem? Would it bring 90% of the potential improvement if WC migrated away from so many postmeta entries, rather than from CPT entirely? (Or as step 1?).

I'm surprised, because the columns in the posts and postmeta table that you might search on are indexed, so, in theory, if core and plugins are doing it right and reading the postmeta data in a single SELECT (instead of spread out over many), then the performance ought to be similar. (A single SELECT over several indexed rows should perform similarly to SELECTing a single row).

Similarly with INSERT - if the writing of the postmeta is written as a single INSERT statements, instead of 25+ separate INSERTs, then performance should be in the same order of magnitude as writing a single row. Is that the real problem, that they're being executed separately? I see this with backups all the time (I'm the lead developer of UpdraftPlus, 600,000+ installs) - a decent backup plugin (or the mysqldump binary) dumps out batched INSERT statements, whereas some put one INSERT per row, and as a result restoring their backups takes approx. 1000% more CPU + wallclock time.

**Comment by DavidAnderson684** [comment]
P.S. And just imagine the wall-clock time needed to run that migrate script, on the site that's had 5,000 orders a day...

**Comment by pmgarman** [comment]
For some of us the clock hit zero already :P

**Comment by lukecav** [comment]
Real world use one store has around $20k in monthly sales and around 190 orders a month, whilst another store has $370k in sales and around 770 orders per month.

**Comment by pmgarman** [comment]
For a few sites I am aware of 190 orders / minute is a realistic number. Those are the stores that already exist that the issues described above become a limitation.

**Comment by pmgarman** [comment]
I'm not saying lets change 30% of the INTERNETS ecommerce for just a handful of sites. I am looking forward to the day that this becomes more common in WooCommerce and being able to support it means more larger site no longer can say "we don't use WooCommerce because it can't scale" when we can provide undeniable proof "yes it can"

**Comment by lukecav** [comment]
I agree the point where WooCommerce is thought of and used more than Magento for store builds since WooCommerce can scale, is where it needs to be.

**Comment by DavidAnderson684** [comment]
Presumably someone using WooCommerce to process 275,000 orders every day, or over 8 million a month (190 orders / minute) will have enough spare cash to fund some serious work on demonstrating the likely benefits of the various ideas thrown around in this thread in cold, hard numbers?

Look at WC_API_Orders::set_order_addresses(). It calls update_user_meta() once for each of the 20 address fields, resulting in 20 INSERT queries, instead of 1. See https://dev.mysql.com/doc/refman/5.7/en/insert-speed.html - "If you are inserting many rows from the same client at the same time, use INSERT statements with multiple VALUES lists to insert several rows at a time. This is considerably faster (many times faster in some cases) than using separate single-row INSERT statements." There's a very easy gain.

From the MySQL manual page, above:

" The time required for inserting a row is determined by the following factors, where the numbers indicate approximate proportions:

    Connecting: (3)
    Sending query to server: (2)
    Parsing query: (2)
    Inserting row: (1 × size of row)
    Inserting indexes: (1 × number of indexes)
    Closing: (1) 

This does not take into consideration the initial overhead to open tables, which is done once for each concurrently running query. 

... 

The size of the table slows down the insertion of indexes by log N, assuming B-tree indexes. "

So, according to that:
1) the majority of the time spent on inserting into the table structure is due to the use of multiple INSERT statements
2) the inefficiency of sending multiple INSERTs is O(n), whereas the inefficiency of spreading the data over multiple rows is only O(log(n)).

**Comment by pmgarman** [comment]
Yes the way WooCommerce handles order meta currently is using the normal WordPress `*_post_meta` functions. Unfortunately WordPress as a whole does not have a method to insert meta in bulk. In order to circumvent this I already have been running WooCommerce patched in a way that uses a function I wrote called `add_post_metas()` and this has increased capacity signifigantly. This really gets into an area that is very hard to keep the existing WordPress actions/filters on adding post meta available though. Slightly touching on the "cold hard numbers" yes... that is my plan. I have a signifigant amount of data (real world and load tests) already, however before moving on such a large change I really wanted to make sure it was aligned with the future of the core of WC to make the most use of our next few rounds of load tests.

I see combining inserts as a temporary solution though, inserting being placed is the first half of the problem. After that being able to access the data through reports also needs to work and by consolidating all the meta into a single table with many columns reporting could be much improved.

**Comment by thenbrent** [comment]
> you will not actually force anyone to use proper methods, very few people will update

Even when "forcing" developers to use proper methods, plenty of code doesn't get updated.

If we were given an API in WC core to optimise how we work with Orders/Subscriptions, we'd definitely update our code to use it. I'm sure Memberships and plenty of others 

> Similarly with INSERT - if the writing of the postmeta is written as a single INSERT statement, instead of 25+ separate INSERTs, then performance should be in the same order of magnitude as writing a single row. Is that the real problem, that they're being executed separately?

There was lots of discussion about refactoring inserts a year or two ago. The idea was to create something like a `WC_Order::save_state()` method, which would write all the data changed in memory to the DB in a single query. @mikejolley might be able to link to the Google doc where discussion/ideas were sourced.

> I hope that before inviting the hatred of the entire human race (+/- a few people not using WooCommerce yet), there'll be some serious gathering of performance data to compare the gains and losses!

Agreed! Fortunately, we have @pmgarman and his monster DBs to get that haha.

> P.S. And just imagine the wall-clock time needed to run that migrate script, on the site that's had 5,000 orders a day...

For reference, with Subscriptions v2.0, we migrated data from order item tables into post tables. This could take hours for sites with 10,000s of subscriptions. For stores with 100,000s orders, you could be looking at _days_. We wrote the upgrader to be deliberately slow to ensure it works on _all_ hosting (having been burned in the past using faster queries that didn't work on some hosts) and then provided hooks to optimise it for high volume sites and you could definitely offer WP CLI methods for running the updater significantly faster, but this is still a serious concern. It's a big ask to have site's doing thousands of orders per minute to go down for even a few hours for maintenance.

Another issue not discussed yet but to keep in mind is custom order types, like Refunds or Subscriptions. These use the same underlying data schema as orders, but potentially in different ways.

**Comment by pmgarman** [comment]
Something I thought of on the plane to WCUS, order notes. They are currently comments and comments are attached to.... Posts! So if orders are no longer posts then the order notes may need major refactoring too.

**Comment by mikejolley** [comment]
There are lots of things we take for granted we would lose or need to recreate from scratch. 

Comments, post screens, lists, convenient queries, count functions, import/export via WP importer to name a few.

**Comment by DavidAnderson684** [comment]
How much of the performance problem is from orders being posts, and how much from order meta being post meta? Orders being posts doesn't have to require that order meta be post meta, does it?

**Comment by WPprodigy** [comment]
Some positive points supporting orders having a custom table: https://pippinsplugins.com/custom-database-api-reasons-for-custom-tables-and-an-api/

**Comment by maxrice** [comment]
As an extension developer, I can't say we'd be thrilled with the prospect of adding compatibility for this sort of change but I agree that it needs to happen at some point. As @pmgarman has pointed out, WC can scale pretty well out of the box but then becomes a problem once you hit a certain order volume. I think it'd be pretty silly to have to tell potential organizations that want to use WC "sure you can use it up to X orders per day/minute/whatever, then you have to go use Shopify, Magento, Bigcommerce, etc."

I think a relatively immediate win would be reducing the amount of `INSERT` calls that WC core makes during checkout. This change benefits every store by making checkout faster, and should buy us more time for larger stores to continue using WooCommerce while the transition to custom tables happens over a few versions.

As part of that you could add core methods that extensions/3rd party code can use to interact with order data, so things like `wc_add_order_meta()`, etc. After a few versions, _most_ code should be using the new methods and the data source behind them could be swapped out.

I've not investigated the WP core methods fully, but there might be a way to maintain backwards compatibility for `*_post_meta()` usages (e.g. filter `get_{$meta_type}_metadata` for core WC meta keys and maybe extensions) along with others, provided we're willing to get creative.

W/R/T the migration -- since old orders (and their associated data) are _probably_ not accessed too frequently, could you migrate newest to oldest? Using something like WP Cron (or maybe Action Scheduler) we could schedule migration jobs that would move the data into the new custom table. It might take a few days or weeks for really big sites, and you'd have to block accessing orders that haven't be migrated yet (maybe with a way to "migrate" the order immediately) but it would prevent sites from needing to go down for maintenance as part of this.

**Comment by silenceisgolden** [comment]
Not sure if you all have tried it yet, but if you are using WP Engine the staging environment is not usable with WooCommerce installed and active. Orders are created, altering the posts and postmeta tables, but only on the production database which is expected. The staging database is a clone of the production database at a point in time before the orders were created. To deploy from staging to production you can select specific tables to push, but if you make page/post content changes on staging this creates a new write log for the database that is splintered from the orders that have been happening on production. To push from staging to production you would need to have a very custom script that would safely insert the changes from the staging database into the production database.

**Comment by pmgarman** [comment]
@maxrice it may be possible to maintain backwards compatibility for meta but filtering *every* post meta call and then attempting to parse "is this meant to be an order" which could even be "if this post does not exist maybe its an order" and then trying to determine "was this actually meant for an order?" ... the two words coming to mind are "slow" and "messy" ... Maintaining the compatibility would be good, but unsure of the cost at which it may come. I also may be 100% wrong and that its super fast and easy to do.

A trac ticket of mine ([#34848](https://core.trac.wordpress.org/ticket/34848)) has gained traction and the ability to insert multiple metadatas at once may be coming to WordPress in the not so distant future which could buy some time but then either WC would need to bump it's minimum WP requirement **OR** conditionally insert meta in bulk or one by one depending on the WP verison. 4.1 is already the required version so 4.5 wouldn't be a huge jump.

While these new functions would greatly reduce the amount of postmeta inserts (potentially), it just buys us some time and I still think moving data to custom tables is the right move for long term scalability and reporting.

**Comment by DavidAnderson684** [comment]
> While these new functions would greatly reduce the amount of postmeta inserts (potentially), it just buys us some time and I still think moving data to custom tables is the right move for long term scalability and reporting.

I'm very interested in what % of the extra overhead in the current design comes from using a custom post type, and what % is from using the postmeta to store the post's meta-data. It seems to me possible that (warning: invented statistic alert) 95%+ of the work will be in migrating from a CPT to a separate table, whereas a lot of the performance bottleneck might be in the use of postmeta. i.e. That you could possibly carry on using a CPT, but store the meta differently, and get almost all the performance gain without most of the migration pain.

**Comment by mountainviper** [comment]
If separate tables for order is being created which I think is a great idea, it should not AFFECT the REST API access. will it be possible to do this seamlessly? The same API end points should pull up orders.

**Comment by pmgarman** [comment]
It won't affect the WC REST API, not sure about WP core rest API I'm not sure how closely those are related

**Comment by JeroenSormani** [comment]
I'd also love to see this happen. 

I agree with @maxrice about adding functions like `wc_add_order_meta()` a.s.a.p (2.5?) so devs can start using that. Then make the big jump in the 3.0 so the breakage isn't as unexpected.

Adding BC would be great, but as mentioned by @pmgarman it will most likely be quite messy. 
I haven't decided if I like it myself, but maybe create a plugin/snippet that can be used to say, 
> "oh your site broke after 3.0, its because a plugin doesn't use the proper functions added in 2.5, you can use *this* to temporary fix it till they resolve the issues"
Just in case and as a fallback.

I'd be happy to help out with this if needed.

**Comment by pmgarman** [comment]
IMO A backwards compat **plugin** would be a great way to handle backwards compatibility I think. Gives people the _option_ to add it to their site if they need it, but doesn't give everyone else the performance hit.

:doughnut: for @JeroenSormani

**Comment by maxrice** [comment]
I disagree that a plugin is the best way to provide backwards compatibility here -- it's a poor experience for the merchant and there's no reason that WC core can't provide the necessary compatibility methods internally. You could provide an option/filter for merchants that positive they aren't using any older code that requires compatibility.

**Comment by thenbrent** [comment]
> it's a poor experience for the merchant and there's no reason that WC core can't provide the necessary compatibility methods internally

Agreed. The sites most likely to have out-of-date code are also the least likely to find/install a separate plugin to make sure their broken code still works.

> You could provide an option/filter for merchants that positive they aren't using any older code that requires compatibility.

That's [what we do with Subscriptions](https://support.woothemes.com/hc/en-us/articles/205214466), it's as simple as a oneliner, like:

```
add_filter( 'woocommerce_load_deprecation_handlers', '__return_false' );
```

> I'm very interested in what % of the extra overhead in the current design comes from using a custom post type, and what % is from using the postmeta to store the post's meta-data. It seems to me possible that (warning: invented statistic alert) 95%+ of the work will be in migrating from a CPT to a separate table, whereas a lot of the performance bottleneck might be in the use of postmeta.

Yeah I think we need better data before seriously discussion implementation details.

@pmgarman can you provide anything?

We currently have a test site creating ~20,000 orders per day (for subscription renewals, not via checkout) with New Relic running to find performance bottlenecks. We're only looking at subscription related code atm, but some WooCommerce core bottlenecks will probably show up and we can use the same site next year to investigate/profile other WooCommerce core behaviour.

**Comment by rahul286** [comment]
@pmgarman have you ever considered using something like elasticsearch/kibana to handle reporting issues?

As reports are SELECT queries, I am planning to deal with them differently and one approach I am exploring is possibility to use some tool which will pull data from mysql from time to time and so some magic on it which will make reporting and searching easier.

We also faced INSERT issues and first thing that came to mind was custom table. But I think combined insert for post meta may be better, considering minimal impact it will have on all sites.

**Comment by pmgarman** [comment]
This is a largely bad example, but when colors were taken out of WooCommerce settings a plugin had to be installed in order to add back that feature.

> The basic paradigms of wp-admin are largely the same as they were five years ago. Working within them had become limiting. The time seemed ripe for something new, something big… but if you’re going to break back compat, it needs to be for a really good reason. A 20x improvement, not a 2x. Most open source projects fade away rather than make evolutionary jumps.
[Matt Mullenweg on breaking backwards compatibility re: Calypso](http://ma.tt/2015/11/dance-to-calypso/)

Considering the benefits to reporting, searching/managing of orders, likely benefits to site speed, and major increase in capacity for taking orders without making **any** changes to hardware, and likely for many sites my guess would be the abilty to use *LESS* hardware to run their site. I'm not sure we could even quantify the actual X improvement to WooCommerce here.

@thenbrent I do have lots of data though and I can get at it and show some data around various implementations BUT at the same time I'd really need to have something to compare against for that data to be worth anything. What I know right now is:

1) you can't hardly get to data in WC in orders because of the _structure_ of the data. If you want to search all orders searching in the address, thats what 5 joins? 10 if you want to search the billing AND shipping. I'm pretty sure even 6-8 months ago for us the search was nearly worthless because it simply took forever. I've got some core hacks I do need to turn into a PR that allows someone to filter the fields being searched to not make it such AS much but as a store admin you should be able to _search_ your orders.

2) Building on above, reporting. HOW can we improve reporting with the core of WooCommerce _without_ moving to custom tables? Yes there are some cool things you can do with technology like elasticsearch and others (as @rahul286 suggested) _however_ (and maybe I'm a minority thinking this) this shouldn't be neccesary. We've not been able to reliable use WooCommerce reporting for anything but a single day for roughly a year. Even then if we have a good day, that single day's reporting also fails.

--- So 1 & 2 are admin related. These *only* impact someone managing a site. It does not matter as much about the load on the site (unless the load on the site is high enough to make the entire site start suffering in which case... the entire site is suffering). These are a couple examples of fairly large issues IMO around WC with lots of orders that I do not think can be solved WITHOUT moving to custom tables. 3 can be resolved via other methods (like I show) but if orders ALREADY are hard to manage BEFORE the flood gates are opened even wider, those issues are just going to get exponentially worse.

3) The primary bottleneck in scaling a WooCommerce site in terms of mass order volume at the same time is the post meta inserts. This really doesn't REQUIRE custom tables to resolve and I've been working towards fixes here to bridge us to _WHATEVER_ solution is found in the future. [I've got a set of functions to add/update post meta in bulk](https://gist.github.com/pmgarman/0cdaa428366db4455ced). I've replaced postmeta inserts in two locations with this now, I do not have good data around the first location where I combined *8* post metas, but it made a huge improvement during our load tests at that time. Yesterday I pushed live code that combined nearly *22* post metas. You can see the change at 12/29 @ 12:00, immediately we went from 400-600 postmeta inserts per minute down to ~200 inserts per minute.

*New Relic*
![](http://c.pmgr.mn/19ZC7+)

*Google Analytics*
![](http://c.pmgr.mn/15HbT+)

Noon isn't exactly a high traffic time, granted its still a decent amount of traffic. Going later in the day you can see the traffic rising. 12/28 had a larger than average amount of traffic, so use 12/27 to compare to 12/29 and you can see for a roughly similair amount of traffic (and yes conversion was roughly the same too) the postmeta inserts were nearly 1/3. Inserts on _average_ were taking a fraction of a ms longer to complete (.5ms to .8ms) but we are running 1/3 the volume.

We've not yet done big load tests on this to get a side by side comparison, but I plan to.

**Comment by pmgarman** [comment]
I thought that comment was long enough and this is on a different train of thought so I thought I'd start a new one ha!

The largest pushback has been not going to custom tables. Which I can appreciate. The steps TOWARD that though are what lies immediately in front of us. In order for me to start attempting to do more tests we need the code to start testing...

The first step towards ANYTHING sounds like is abstracting out orders which should have zero impact on breaking anything for backwards compatibility and at the same time is good for WC. What is our next steps to work towards this first goal? How do we want to abstract things out? Do we want to start on this part _NOW_ or does it need to wait a little bit, and if so for what? 2.5 stable?

**Comment by rahul286** [comment]
@pmgarman may I know what are you using for load testing woocommerce?

We are also working on similar thing at https://github.com/rtCamp/woobench . We have just started, so it might take 2 week before we have some code and data in github repo.

**Comment by pmgarman** [comment]
Blazemeter with a test that simulates real world user behaviour on our site, coming to the home page browsing around the shop while adding products to cart, viewing the my account page (a pretty DB intensive page), going to cart and changing items around, going to checkout, checking out, viewing the order received page, going back to my account.

**Comment by leokoo** [comment]
thanks, a shift to custom tables would definitely help WooCommerce.

**Comment by sprclldr** [comment]
The conversation has been focused on performance, but I'd like to reiterate @lawkwok's point and the issue that we re fighting with WC. There is no way to stage a live site, make changes and then reintegrate without losing orders. Orders are chalking up new post ID's in production while the staging site is producing the same ID's as post content or anything else that happens in staged content changes. There's no way to reconcile the two without dumping orders.

**Comment by rahul286** [comment]
@sprclldr if mysql auto-increment ID's is issue - you may use `auto_increment_increment` and `auto_increment_offset` variables so staging and live site ID's will never collide.

**Comment by sprclldr** [comment]
@rahul286 Thank you so much for the suggestion!

**Comment by twoelevenjay** [comment]
Very exciting! At this point in the thread it has become pretty clear the shift to custom order tables is inevitable, however I will add my two cents in support of it.

Some pointed out that this was only a problem for larger shops, although it was already argued that those larger shops are reason enough, I feel the need to represent the smaller shops too. As long as a smaller shop stays small it will never face the challenge of many concurrent orders. However being small won't protect against the performance impact of 100,000s of orders in the DB. The concept of a website is only 24 years old, WooCommerce is only 6 years old. Unless we have a zombie apocalypse, there will be a day where a WooCommerce shop is 100 years old. At that point a shop that only gets 10 orders per day will have 365,000 orders. So I think tackling the inevitable now is a good idea.

**Comment by w00tw00t111** [comment]
@pmgarman as you noted for us the biggest bottleneck is retrieving the post_meta.

We recently moved from a BigCommerce shop and although we love WooCommerce - the performance on the backend is...atrocious.

The front end was terrible as well - but we've solved that with a combo of serious page/browser/db caching, cdn, cloudfront, Pound, and Varnish.

In profiling the fundamental is pulling data out of the meta table that relates to the orders. Secondly is the basic WP loop functionality. WC uses multiple duplicate queries all related to the_loop() which causes a slow down.

A secondary item to add to the benefit of a custom order table is the fact that adding a page/post totally screws up with the order #'s. For a shop this is a pretty frustrating problem. We use a plugin that allows us custom order# (again using post_meta data), but the original post id is what's transferred to our 3rd party integrations (ShipStation, Auth.Net, etc.).

I think ultimately as WC begins to takeover the world in being one of the most used e-commerce platforms if Automattic is serious about taking the platform to industry scale (even SMB industry) there needs to be some import code refactoring.

For sake of reference - We do about 9,000 orders a month. 32GB 12 core VPS. Our warehouse manager, order manager, and customer support team general have to wait 2-4 seconds for the WC Order screens to load...talk about a time drain and poor customer experience :-1:

**Comment by thenbrent** [comment]
FYI @w00tw00t111 (and anyone else digging up this old issue), there is no question about whether WC should move to custom order tables anymore. It's happening and work is already well under way. See https://github.com/woothemes/woocommerce/issues/10071 and the many associated Issues and Pull Requests, like https://github.com/woothemes/woocommerce/pull/11455.

**Comment by w00tw00t111** [comment]
@thenbrent thanks for the comment! This thread came up in Google and it was still open so I thought it was the most appropriate area for discussion. Thanks for the links to the pull requests :)
