### ISSUE TITLE
REST API price_html for parent variations products

### ISSUE THREAD

**Issue by AdAvAn** [woothemes/woocommerce#9736]
I use the "REST API V3". After updating the parent product by "PUT" request, the price of the parent product - zero. It is not visible on the website, as well as being after repeated "GET" request shows that the field "JSON" "price_html" - empty.

"product":{
"title":"test",
"id":770,
"created_at":"2015-12-01T12:47:36Z",
"updated_at":"2015-12-01T19:10:22Z",
"type":"variable",
"status":"publish",
"downloadable":false,
"virtual":true,
"permalink":"https://test.com/shop/test-2/",
"sku":"770-6456",
"price":"123.00",
"regular_price":"0.00",
"sale_price":null,
"price_html":"<span class="amount">123.00 Грн. </span>–<span class="amount">123.00 Грн. </span>",
"taxable":false,
"tax_status":"taxable",
"tax_class":"",
"managing_stock":true,
"stock_quantity":3,
"in_stock":true,
.......
}

My "PUT" query:
https://test.com/wc-api/v3/products/770?consumer_key=ck_123&consumer_secret=cs_123
{
"product":{
"title":"test",
"catalog_visibility":"hidden",
"featured":false
}
}

Repeated "GET" request

"product":{
"title":"test",
"id":770,
"created_at":"2015-12-01T12:47:36Z",
"updated_at":"2015-12-01T18:50:31Z",
"type":"variable",
"status":"publish",
"downloadable":false,
"virtual":true,
"permalink":"https://test.com/shop/test-2/",
"sku":"770-6456",
"price":"0.00",
"regular_price":"0.00",
"sale_price":null,
"price_html":"",
"taxable":false,
"tax_status":"taxable",
"tax_class":"",
"managing_stock":true,
"stock_quantity":3,
"in_stock":true,
.....}

**Comment by claudiosmweb** [comment]
Variable product don't have prices, need to enter prices on the variations.

**Comment by AdAvAn** [comment]
Yes, but I do not try to update the price of parent, I update the other parameters of the parent:

"title": "test",
"catalog_visibility": "hidden",
"featured": false

After that field "price_html" - to become empty and of course the disappear price on the web page .Even if I update a photo to the parent via the API, the parent - "price_html" - empty. If I go to the store administration panel, then in my product and click "Update" button, enter values "price_html" - to become true.

**Comment by claudiosmweb** [comment]
@AdAvAn what WooCommerce version?

**Comment by claudiosmweb** [comment]
Fixed here in bfe98a283cc928d840a10a3907fa16d8a10af6b4
Wait for 2.4.11.
