### ISSUE TITLE
Webhook List Endpoint has an undocumented default status filter of "Active"

### ISSUE THREAD

**Issue by sunahfloship** [woothemes/woocommerce#9738]
The API Docs specify that a status filter is available on the webhook list endpoint, but doesn't document that the endpoint will default to `status=active` if no filter is specified: http://woothemes.github.io/woocommerce-rest-api-docs/#view-list-of-webhooks

Currently, there's no way to query for all webhooks regardless of status, so a complete list of webhooks requires three calls.

Looks like the filter is applied by default here:
https://github.com/woothemes/woocommerce/blob/0b789ed216021db61c152309b21b9c9f3ace2ae0/includes/api/class-wc-api-webhooks.php#L370

**Comment by claudiosmweb** [comment]
@sunahfloship I just added a new param `all` to get all for all status, will be shipped within WooCommerce 2.5. And updated our docs too, but please use our [Rest API Docs repository](https://github.com/woothemes/woocommerce-rest-api-docs) next time for docs issues.
