### ISSUE TITLE
Variation weight on page “product”.

### ISSUE THREAD

**Issue by anarmus** [woothemes/woocommerce#9744]
Could you help me please, how can i ouput weight of item varitaion in template variable.php?

**Comment by WPprodigy** [comment]
http://stackoverflow.com/questions/21668690/get-product-weight-from-wordpress

The tabs do this automatically in the "Additional info tab". Here is the js that switches the weights out when a product is changed: https://github.com/woothemes/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L163-L168

This is not the place to ask for support like this though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.
