### ISSUE TITLE
PayPal Guest Checkout issues

### ISSUE THREAD

**Issue by sccr410** [woothemes/woocommerce#9756]
So if a user makes a purchase as a Guest using PayPal, WooCommerce only sends the billing address. As such, within PayPal, there is no address information. This results in us not being able to take advantage of PayPal's seller protection since no shipping address could be verified.

I understand PayPal can only accept one address, so why is WooCommerce sending a billing address on guest checkout instead of shipping address?

**Comment by roykho** [comment]
In your PayPal settings WooCommerce settings->Checkout->PayPal Turn on `Send shipping details to PayPal instead of billing.`

**Comment by mikejolley** [comment]
^ guests are also handled no different to those logged in. It's identical.

**Comment by sccr410** [comment]
I have that checked, it's still an issue

**Comment by mikejolley** [comment]
There is no difference between guest and logged in user checkout @sccr410. The process is the same - data comes from your order. 

https://github.com/woothemes/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L84-L90

**Comment by sccr410** [comment]
Thanks guys, I am now working with PayPal to try to understand that even though the shipping address is being sent they are showing no record of it.
