### ISSUE TITLE
WP Notice Activity box in the Dashboard

### ISSUE THREAD

**Issue by grappler** [woothemes/woocommerce#9757]
I am getting this WP notice after I deactivate WooCommerce in the Activity box in the Dashboard.

```
Notice: map_meta_cap was called incorrectly. The post type product is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see Debugging in WordPress for more information. (This message was added in version 4.4.0.) in /wp-includes/functions.php on line 3787
```

How to replicate.
- Activate WooCommerce
- Comment on a product
- Deactivate WooCommerce
- Check the Activity box in the Dashboard and you should see the error.

I know this is a strange issue as it only shows up when the plugin is deactivated :)

**Comment by mikejolley** [comment]
Same issue as this one; it's the comments. https://wordpress.org/support/topic/php-error-notices-on-main-dashboard-page Not really something that can be fixed unless you remove all data during uninstall.

**Comment by rtpHarry** [comment]
You can delete the rogue comments from the dashboard and then when you refresh the error will be gone.
