### ISSUE TITLE
Order notes don't show the admin username if the change is made on the order list page

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#9758]
If I edit an order and complete it then the order note shows the name of the admin, if I complete the order on the order list page then the order note does not show the admin user name

## Edit Order : 
![](https://dl.dropboxusercontent.com/s/uz6owxg2vx5r192/2015-12-04%20at%2008.15%202x%20%281%29.png?dl=0)

## Order List : 
![](https://dl.dropboxusercontent.com/s/gkgmgpxuiuib07l/2015-12-04%20at%2008.15%202x.png?dl=0)

Can the order notes include the admin username if the action was done on the edit order screen as well :)

**Comment by mikejolley** [comment]
Confirmed fixed in master already.
