### ISSUE TITLE
Greater value than max attribute is saved in widgets

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#9761]
If widget setting type number has max attribute setup and if the user try to set greater value than that of value set in max attribute, its saved.

**Comment by mikejolley** [comment]
'max' is client side validated only.

**Comment by shivapoudel** [comment]
@mikejolley take this as an example. If I set number type 'max' as 20 [here](https://github.com/woothemes/woocommerce/blob/master/includes/widgets/class-wc-widget-top-rated-products.php#L38) and try to save 200 then in frontend more than 20 top rated products are displayed.

**Comment by shivapoudel** [comment]
@mikejolley Thanks! can you please cherry pick this on 2.4 release branch :)

**Comment by mikejolley** [comment]
Nope :) It can wait for 2.5.

**Comment by shivapoudel** [comment]
Okies :)
