### ISSUE TITLE
Adding settings to admin that I don't want saved by WC

### ISSUE THREAD

**Issue by greatwitenorth** [woothemes/woocommerce#9763]
Is it possible to add a setting to the admin area (specifically I have a page under WC -> Products -> My Setting Page) that will not get saved into the options table?

My use case is that I'm outputting a list of roles and checkboxes for each. I want my plugin to look at the checked roles, and attach a capability to the role if checked. I don't need WooCommerce handling any of the functionality for these fields. Based on the roles checked will effect the way products are displayed on the front end.

Is there something I can put in the settings array to make WooCommerce 'bypass' these specific fields?

**Comment by pmgarman** [comment]
You could always short circuit the update_option calls, set the value to the old value and then the function will return before updating options.

https://github.com/WordPress/WordPress/blob/4.3.1/wp-includes/option.php#L283

**Comment by mikejolley** [comment]
You can also make custom fields which have no save handler. You'd have to output your checkboxes, but you'd avoid any logic from WC on said fields.

**Comment by greatwitenorth** [comment]
Great ideas! I ended up doing a combination of the both. Thanks!
