### ISSUE TITLE
REST API: PUT to /wc-api/v3/products/<id> not supported

### ISSUE THREAD

**Issue by robertslagter** [woothemes/woocommerce#9767]
Hi there,

I am trying to update a product price via the REST API, using the curl command
PUT /wc-api/v3/products/<id>
Unfortunately I receive a "not supported" error.
The PHP WooCommerce-REST-API-Client-Library did not work either.
My Woocommerce version is 2.4.10, so that should not be the problem.
Any ideas what could be the case? Getting product data is just fine, and my user has read and write permissions.

Any help is welcome.

**Comment by claudiosmweb** [comment]
![screenshot from 2015-12-04 21-57-50](https://cloud.githubusercontent.com/assets/1264099/11604306/1444a2a6-9ad2-11e5-9b89-2881dd73b14e.png)
