### ISSUE TITLE
Add appropriate widget sanitize and form field hooks

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#9768]
It would be best if the `WC_Widget` class supports appropriate action hook to add additional form field type and filter hook to sanitize (one or all) fields type. Just like admin settings options :P

**Comment by mikejolley** [comment]
You can extend the class and replace those methods if you need custom handling for custom fields. Core doesn't need this - you cannot extend the options of core widgets like you can settings screens.
