### ISSUE TITLE
PHP Fatal error when trying to set current gateway while none are available.

### ISSUE THREAD

**Issue by jeffstieler** [woothemes/woocommerce#9769]
If no gateways are currently available (which I'm not 100% sure is OK - but it's happening for me locally), the call to `WC_Payment_Gateways::set_current_gateway()` causes a PHP Fatal [here](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-payment-gateways.php#L168).

It looks like this was introduced in [this commit](https://github.com/woothemes/woocommerce/commit/d363e810d84c50788a2006feaf04dff3ed2045b5) to fix issue #9378.

**Comment by shivapoudel** [comment]
@jeffstieler good catch :+1:
