### ISSUE TITLE
Should tabs validate function exists before calling?

### ISSUE THREAD

**Issue by pmgarman** [woothemes/woocommerce#9772]
If a tab is registered with an invalid callback it will create a notice. Should some form of validation be done before attempting to call a function that may not exist? I could see it going a few ways, leave it: if someone sees the notice it means the site is in debug mode and in theory its meant to be seen and tells you at least where to start looking, don't show any error: only call if callable, or third possibly add some more verbose error message?

`Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in /wp-content/plugins/woocommerce/templates/single-product/tabs/tabs.php on line 34`

https://github.com/woothemes/woocommerce/blob/2.5.0-beta-2/templates/single-product/tabs/tabs.php#L42

**Comment by mikejolley** [comment]
@pmgarman I was going to swap this out for a doing_it_wrong, however, my wording would have been near identical so for the sake of this (being a dev error) the existing notice is adequate and saves a template change.
