### ISSUE TITLE
Checkout page shipping options do not work with latest Pay-with-Amazon plugin

### ISSUE THREAD

**Issue by tipsytopsy** [woothemes/woocommerce#9776]
Here is how to recreate this issue:
In woocommerce shipping options - select "Hide shipping costs until an address is entered" option (This step is neccesary).

Enable Pay-with-Amazon plugin and try to checkout using "Login with Amazon" button. After login when Amazon shipping/ payment options are loaded - the shipping options should be shown - but they do not since the new Amazon plugin does not trigger 'shipping selected' event.

**Comment by claudiosmweb** [comment]
Need to be reported for "Pay-with-Amazon plugin" and not for WooCommerce.
