### ISSUE TITLE
where do I find " I " in this question

### ISSUE THREAD

**Issue by galerieimbert** [woothemes/woocommerce#9783]
the thing looks like an L in small letters but I am sure there is a key for this.  It is to define multiple attributes in Woocommerce,
thank you
Kathleen

**Comment by ibes** [comment]
See: https://en.wikipedia.org/wiki/Vertical_bar

**Comment by galerieimbert** [comment]
@ibes thank you, I have been looking for this for months |||||....

**Comment by ibes** [comment]
:|

:D
