### ISSUE TITLE
Cart shows product price instead of variation price

### ISSUE THREAD

**Issue by ibes** [woothemes/woocommerce#9784]
Hi there,

I have a shop with a couple of variable products where variations have a price different form the main product. 

The Cart shows the product price - not the price of the variation. 

In detail:
In the row of the product in the Cart:
- the thumbnail is of the product
- the name is of the product
- the meta information (like color/size) is of the variation (https://github.com/woothemes/woocommerce/blob/master/templates/cart/cart-item-data.php#L22)
- the single item price is of the product
- the total price is of the product

Fortunately the math is right - so the total price of the Cart is correct. But it's highly confusing that the wrong price is shown in the product row. And I guess it's just wrong this way. 

It the Cart loop there should be something asking if there is a variation and if so, get the details of the variation. 
Like the price https://github.com/woothemes/woocommerce/blob/master/templates/cart/cart.php#L97

Seems like someone of the team forgot about variations. Or do I get some concept wrong?

As the meta date of the variation is shown correctly I imagine that the variation was successfully added to the cart - not just the product without reference to the cart. 

In the backend - in the orders section - everything is alright. 
https://github.com/woothemes/woocommerce/blob/f7ea1d4c6a1f3751b80e807ef89b2968cb25c6e0/includes/admin/meta-boxes/views/html-order-items.php
There it's `get_product_from_item `

(WooCommerce 2.4.11, disabled all plugins that are related to WooCommerce, used a theme that does not overwrite WooCommerce themes)

**Comment by ibes** [comment]
Sorry - Problem is from Hyyan WooCommerce and Polylang Integration

**Comment by maximus-lynn** [comment]
Wish you left how you fixed this buddy
