### ISSUE TITLE
Updated to Version 2.5.0-beta-2 Still shows Version 2.5.0-beta-1

### ISSUE THREAD

**Issue by codingideas** [woothemes/woocommerce#9785]
I have the the beta tester plugin and updated to Version 2.5.0-beta-2 but the admin still shows that I am still on Version 2.5.0-beta-1.

**Comment by pmgarman** [comment]
Yeah seems like the version tag in the plugin header never got version bumped.

https://github.com/woothemes/woocommerce/blob/2.5.0-beta-2/woocommerce.php#L6

**Comment by claudiosmweb** [comment]
I just updated it.
