### ISSUE TITLE
looking for a great tutorial on how to get variable products up and going

### ISSUE THREAD

**Issue by galerieimbert** [woothemes/woocommerce#9787]
I have 4 options for prints and would like to set up the attributes, I have been at it all day and can't figure it out!!!

anyone know of a great tuttorial that I can watch !

thanks
Kimbert

**Comment by claudiosmweb** [comment]
![screenshot from 2015-12-07 15-52-15](https://cloud.githubusercontent.com/assets/1264099/11634915/8204b964-9cfa-11e5-9338-4e32c5291c4f.png)

https://docs.woothemes.com/document/variable-product/

**Comment by galerieimbert** [comment]
thank you

a newbie and hope to find a solution

K Imbert
