### ISSUE TITLE
[2.5] No support for PHP 7

### ISSUE THREAD

**Issue by av3nger** [woothemes/woocommerce#9788]
On a test install with PHP 7 it's impossible to activate WooCommerce. This error message appears:

Plugin could not be activated because it triggered a fatal error.
Fatal error: Redefinition of parameter $deprecated in /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 1931

**Comment by galerieimbert** [comment]
@claudiosmweb 
thank you Claudio for the link...about product variable.  I can't find my original issue... a real newbie, but am hopeful :)

K Imbert

**Comment by BurlesonBrad** [comment]
Error message when I turn on php7 &, select "use default" http://prntscr.com/9dt3h2:

"Fatal error: Redefinition of parameter $deprecated in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 1931"

What?  Line 1931 is not at all even remotely exciting enough to cause an error is it? https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L1931

Ugh..... what's the deal? Is it with php7 and the setup or is it w/ Woo?

**Comment by av3nger** [comment]
@BurlesonBrad, get the latest code from branch 'release/2.4'. The problem has been fixed there.

**Comment by BurlesonBrad** [comment]
pfft.... sorry.... fail on my part to mention i'm running Woo beta 2.5 :-)

**Comment by BurlesonBrad** [comment]
@claudiosmweb : Not that my super rocket skill will ever have the time to surpass your awesomeness, But if I want to submit a patch for 2.5 beta, where / how can I do that in the github?

Here's the fix for beta 2.5+ running on php7: https://gist.github.com/BurlesonBrad/bb672af3056a6752f00a

**Comment by claudiosmweb** [comment]
Try or master, not fixed in a tag yet I think.
