### ISSUE TITLE
UTF-8 wrecked in emails

### ISSUE THREAD

**Issue by baznikin** [woothemes/woocommerce#9789]
All non-ISO-8859-1 characters in emails send by WC converted into '?' character if !function_exists( 'mb_convert_encoding' ) in following code block:

includes/libraries/class-emogrifier.php
````
if ( function_exists( 'mb_convert_encoding' ) ) {
    return mb_convert_encoding( $bodyWithoutUnprocessableTags, 'HTML-ENTITIES', self::ENCODING );
} else {
    return htmlspecialchars_decode( utf8_decode( htmlentities( $bodyWithoutUnprocessableTags, ENT_COMPAT, self::ENCODING, false ) ) );
}
````

I suppose call of utf8_decode() should be removed OR usage of mbstrings should be enforced.

**Comment by claudiosmweb** [comment]
Not all servers have `mb_convert_encoding()` "installed".

http://php.net/manual/en/mbstring.installation.php

> mbstring is a non-default extension. This means it is not enabled by default. You must explicitly enable the module with the configure option. 

So we use `utf8_decode()` as a fallback.

**Comment by baznikin** [comment]
It is not right fallback, utf8_decode() simply change all non-latin
characters into question marks and email is completly unreadable. I can't
see why you need this function here, without it emails looks great.

вторник, 8 декабря 2015 г. пользователь Claudio Sanches написал:

**Comment by claudiosmweb** [comment]
> without it emails looks great.

Not in all email clients.

**Comment by baznikin** [comment]
On Tue, 08 Dec 2015 19:04:15 -0800
Claudio Sanches <notifications@github.com> wrote:

With it is absolutely unreadable in any client :) What's worse?

> > without it emails looks great.
> 
> Not in all email clients.

-- 
Andrew I Baznikin

#      /\    ASCII ribbon
#      \/      campaign
#      /\      against
#     /  \    HTML email

**Comment by claudiosmweb** [comment]
If you really need to work if this kind of characters you'll need install `mbstring` in your server.

**Comment by baznikin** [comment]
On Tue, 08 Dec 2015 19:23:48 -0800
Claudio Sanches <notifications@github.com> wrote:

I did, but I inform you - WC send complete rubbish via email in any language with non-Latin1 characters. It's up to you what to do with it.

PS: There is example of such email. I didn't notice this before - currency name is OK ("руб.", Russian rouble) but all other words is not...
============
??? ?????? ????????, ?????? ?????? ??????? ????.
????? #61
????? ?????????? ????
???? (#TST)
1 0.50 руб.
???????: 0.50 руб.
?????? ??????: PayPal
?????: 0.50 руб.
============

> If you really need to work if this kind of characters you'll need install `mbstring` in your server.

-- 
Andrew I Baznikin

#      /\    ASCII ribbon
#      \/      campaign
#      /\      against
#     /  \    HTML email

**Comment by claudiosmweb** [comment]
If you really need to work if this kind of characters you'll need install `mbstring` in your server.
