### ISSUE TITLE
Oh Hold Email

### ISSUE THREAD

**Issue by JamesSimpson** [woothemes/woocommerce#9792]
There should be an option to have an email sent when an order is on hold.

I.E. a user selects BACS or Cheque payments, there should be an email sent out stating payment should be sent to Bank account details or cheques sent to X address.

Just cant seem to get around using the Processing Order email template to send this information across, especially when there is card payments that go through straight away, and can confuse customers if we were to edit this template. 

If I disable to processing order template, no email is sent out to the customers who select Cheque or BACS payments, but if I enable it and customise this template, card payment people will get this and completed emails.

**Comment by mountainviper** [comment]
This can be done using one of the Custom Order Status plugins. But yeah this should be a default feature too.

**Comment by JamesSimpson** [comment]
Yea I have seen the plugins, but why use a plugin when this feature should be part of the standard build. There are email templates for every other aspect apart from this.

**Comment by galerieimbert** [comment]
Yes but my fields are all over the place and I can't get them on the right side as I would like

thank you 
James

**Comment by webdados** [comment]
I see @mikejolley closed this 23 days ago. It will be available at 2.6, correct?
