### ISSUE TITLE
Download for variation not updating

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#9793]
This is on WC 2.4.11 - though, it's been happening on the releases before that too.

A variable product, with 3 variations. Updating works fine for 2 of them. But with the other, here's what I do...

1) Observe the state of the current download. It's for http://some/path/woocommerce-eu-vat-compliance-premium.1.10.7.zip . Screenshot: http://snag.gy/DhSeT.jpg

2) Press "Choose file", and choose an uploaded filed from the selector - in this case, woocommerce-eu-vat-compliance-premium.1.10.14.zip. Press "Insert File URL". Screenshot: http://snag.gy/S2Jof.jpg

3) Observe that that's now correctly showing in the input field; screenshot: http://snag.gy/thwDH.jpg

4) Scroll down to the "Save Changes" button - and observe that it's greyed out; can't be pressed. Screenshot: http://snag.gy/bmm3i.jpg 

I can make the "Save Changes" button press-able by editing something else. But even if I do, this change doesn't get saved. When I reload the page, it's back to the original value ( http://some/path/woocommerce-eu-vat-compliance-premium.1.10.7.zip ).

As I say, changes to the other two variations save without problem.

**Comment by mikejolley** [comment]
I suspect 2 issues here.

1) the file input doesn't trigger a chance event. I can fix this one.

2) the save might not work if the file is not found (should be a notice). I cannot replicate this one - I can save without issue.

**Comment by DavidAnderson684** [comment]
"the save might not work if the file is not found" - in this case, I'm adding the file via the media uploader, and it definitely exists. (Selecting the same file from the media uploader works for the other 2 variations within the same 3-variation product and same edit operation).

**Comment by DavidAnderson684** [comment]
"I cannot replicate this one" - this also doesn't happen for me across all variable products on the same shop. Only on some. I don't have any good ideas about why that is. But, the odd thing is that even when the "Save changes" button is unlocked (via changing something else), the information still doesn't get saved.
