### ISSUE TITLE
API Settings and the API Authentication Endpoint in 2.4 Response Issue

### ISSUE THREAD

**Issue by indrajit-rathod** [woothemes/woocommerce#9800]
I am using API Authentication Endpoint  to generate "API Keys" as mentioned here:
https://woocommerce.wordpress.com/2015/08/07/api-settings-and-the-api-authentication-endpoint-in-2-4/

The keys are getting generated when I look into the woocommerce settings in the wordpress admin panel but I am not receiving any valid resoponse on the "Call back url" which I have mentioned during authentication.

I have tried $_SERVER, $_POST, $_GET for the response but in vain, so can anyone help me with this? How can I get the response after authentication?

**Comment by claudiosmweb** [comment]
It's in the body of the request.
