### ISSUE TITLE
Can't add Price to Product

### ISSUE THREAD

**Issue by awr10e** [woothemes/woocommerce#9802]
Since update I seem to be unable to change/add a price to products, using a variable products.

The option is missing when editing the product and doesn't work when Bulk editing.

I'm using Version 2.4.11.

![image](https://cloud.githubusercontent.com/assets/16224306/11685701/e11618ac-9e72-11e5-8e63-01b2c6973e34.png)

Thanks

**Comment by mikejolley** [comment]
Prices are added to variations, not the variable product itself.

**Comment by awr10e** [comment]
Thanks Mike
How do i Bulk Edit, I don't want to have to edit the items individually?

**Comment by mikejolley** [comment]
You'll see all of that on the variations tab.

**Comment by galerieimbert** [comment]
Hi Mike, Where do I find variations?  I would like to add a price to a sub product and have created a single product.  I have declared it parent and cannot link the sub product with the parent product...
