### ISSUE TITLE
plug in search

### ISSUE THREAD

**Issue by galerieimbert** [woothemes/woocommerce#9804]
Hello I would like to know if I would need a plug in to show a product that is original and subcategories for prints?  

Or can I add in the personalized fields?

I would like it to show as a neat looking box?

thank for any suggestions

**Comment by claudiosmweb** [comment]
This repository is not suitable for support.
Please don't use our issue tracker for support requests, but for core WooCommerce issues only.

Support can take place in the appropriate channels:

* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
* [Our community forum on wp.org](https://wordpress.org/support/plugin/woocommerce) which is available for all WooCommerce users.

Or check our documentation:

* [Our official docs](https://docs.woothemes.com/documentation/plugins/woocommerce/)
* [Knowledge Base](https://support.woothemes.com/hc/en-us/categories/200146917-WooCommerce)
* [Rest API docs](http://woothemes.github.io/woocommerce-rest-api-docs/)
* [Our Code Reference](https://docs.woothemes.com/wc-apidocs/)

**Comment by galerieimbert** [comment]
Thank you Claudio for the link, this is a great help

Now how do I get out of here?

K

**Comment by claudiosmweb** [comment]
@galerieimbert you can't delete it here.
