### ISSUE TITLE
Preview Each Email Templates

### ISSUE THREAD

**Issue by JamesSimpson** [woothemes/woocommerce#9805]
This is another feature request, that seems to be missing from WooCommerce.

Yes there is the overall email preview, which is only good for testing the header / footer and plain text, but how about being able to preview a actual order email, even some dummy data would help, as I've spent the last day modifying the templates to get them to look right, but to test them working, I have to put a dummy order through for it to be sent to my inbox. 

Cheers

James

**Comment by roykho** [comment]
With this plugin http://www.woothemes.com/products/woocommerce-email-customizer/ you can do just that.  Hope it helps.
