### ISSUE TITLE
Blank cell appears for gateways with empty titles in the Gateway Display Order view

### ISSUE THREAD

**Issue by allendav** [woothemes/woocommerce#9806]
If a Gateway is purposely set with an empty title (e.g. the merchant only wants to display the icon for the gateway in checkout), then an empty cell is displayed in the Gateway Display Order view in WooCommerce > Settings > Checkout > Checkout Options

![screen shot 2015-12-09 at 8 47 01 am](https://cloud.githubusercontent.com/assets/1595739/11691948/1607cfd6-9e52-11e5-8ca4-0c396b9061cf.png)

Perhaps we could display the `method_title` when `title` is empty?  Or perhaps `(Untitled)` ?

**Comment by claudiosmweb** [comment]
I like `(Untitled)`.

**Comment by mattyza** [comment]
@claudiosmweb How about "(no title)", like in WordPress core? :)

![image](https://cloud.githubusercontent.com/assets/880803/11693539/18a3ad4e-9eae-11e5-9cf7-19ee12d9df23.png)

cc @allendav

**Comment by claudiosmweb** [comment]
@mattyza for sure, doing like core is much better :)

**Comment by greguly** [comment]
+1 for like core
