### ISSUE TITLE
input created with woocommerce_wp_checkbox() doesn't update from value="yes" to value="no"

### ISSUE THREAD

**Issue by vtrpldn** [woothemes/woocommerce#9807]
Hello there, 

I created a few custom inputs based on [this article](http://www.remicorson.com/mastering-woocommerce-products-custom-fields/) and seems like that woocommerce_wp_checkbox() is not working as intended.

When I check the field and update the post, the value updates from "unchecked" to "checked" but not the other way around. However, if I manually edit the value attribute from "yes" to "no" the meta value updates successfully.

Here is an example: 

![woo_checkbox]
(https://cloud.githubusercontent.com/assets/5367401/11692342/3a4977a8-9e86-11e5-82b1-0db396f272ac.gif)

**Comment by claudiosmweb** [comment]
Not an issue in WooCommerce.
You're not saving it properly.

**Comment by benhuson** [comment]
When a checkbox is deselected that field won't be passed through with POST parameters so if you are checking `isset( $_POST['checkbox_name'])` before saving the checkbox value, it won't exist.
