### ISSUE TITLE
Return order line item weight information in API

### ISSUE THREAD

**Issue by simonkreuz** [woothemes/woocommerce#9810]
It would be great to return the weight (and weight unit) of each line item in the Order endpoint response. 

For use cases that require the total Order weight, the only way to retrieve this info currently is to make additional Product API queries, which isn't an efficient solution.

**Comment by mikejolley** [comment]
@claudiosmweb recently added 'expand' support to expand products in the API response. This will be part of 2.5.

**Comment by simplypost** [comment]
+1: Should include this info in webhooks (order.created, order.updated ...)
