### ISSUE TITLE
changing the product type should be prohibited

### ISSUE THREAD

**Issue by toddlahman** [woothemes/woocommerce#9811]
It is a common mistake for store owners to believe they can change a product type to another product type without any issues. This is especially problematic when it comes to a subscription product being switched to a non-subscription product, or perhaps to an external/affiliate product. The data for each product is used by many different third party plugins. When the product type changes this is often a breaking change for those third party plugins. There should be a JavaScript, and a PHP, restriction that prevents a product type from being changed whether it is a draft or has already been published, to prevent known and unknown issues. I've worked with many store owners over the past few years that have really messed things up because they didn't see a warning, or any indication that changing a product type would could break things. It would be a big step forward if this could be remedied in version 2.5.

**Comment by toddlahman** [comment]
Also, duplicating a product should not duplicate the postmeta _wp_old_slug, or create rewrite rules using the original product's _wp_old_slug.

**Comment by mikejolley** [comment]
> It is a common mistake for store owners to believe they can change a product type to another product type without any issues.

TBH it sounds like product type is something extensions should check and consider when running logic. The user should be able to change product type if they want. If something breaks, thats a bug.
