### ISSUE TITLE
Homepage Title Tag issue after upgrade to WordPress 4.4 and WooCommerce 2.4.12

### ISSUE THREAD

**Issue by todorchrisov** [woothemes/woocommerce#9812]
I am using WooCommerce and Storefront theme together with a Blank child theme.

After upgrading to WordPress 4.4 and after upgrading to WooCommerce 2.4.12 my Site Title and Tagline do not appear as my Homepage Title tag.

In Settings > General I still have my Site Title and Tagline set as before.

In Appearance > Customize > Site Identity I still have the same Site Title and Tagline set as before.

The problem is that on my homepage the title tag is different after the upgrades. It is not "Site Title | Tagline" as normal, but "The Title of the Static Page set for Homepage - Site Title".

My site is http://www.umniknigi.com/

I will apreciate your help in order to fix this issue.

Regards,

Todor

**Comment by mikejolley** [comment]
This appears to be the behaviour of WP core. Because this is a custom post type archive, the following takes precedence in the wp_title() function.

`
// Post type archives with has_archive should override terms.
	if ( is_post_type_archive() && $post_type_object->has_archive ) {
		$title = post_type_archive_title( '', false );
	}
`

You can filter on 'post_type_archive_title' to change it yourself, or use an SEO plugin.

@claudiosmweb

**Comment by todorchrisov** [comment]
Thank you for your quick reply, Mike!

So it seems that this is something new with WordPress 4.4... I guess many WooCommerce store owners will be concerned with this change as far as one of their most important Title tags is hit - the Homepage title tag.

Just to make sure - should I put the code you mention in the functions.php on my child theme? 

How can I make it work if I would like my homepage title tag to be, let say "A New Homepage Title"?

I will apreciate your feedback. The issue is new to me and I am not sure how to proceed with your code and filters.

Thank you once again for your quick reply!

**Comment by mikejolley** [comment]
Try just adding this to functions.php:

`
add_filter( 'post_type_archive_title', '__return_empty_string', 5 );
`

**Comment by todorchrisov** [comment]
Thanks, Mike! I appreciate your express replies!

Regratfully this code is not fixing the homepage title tag. I placed it inside my functions.php but it has no effect to my homepage. I double and triple checked it.

In case you can figure out another solution, it would be great.

Thanks once again!

**Comment by mikejolley** [comment]
Did you add it in the correct place? I did the same in https://github.com/woothemes/woocommerce/commit/77714623cf515e5fe83161752159b74741ec1e59 and it worked for me. it removed the post type name from the page, but left the site title.

**Comment by todorchrisov** [comment]
Well, I believe I added it in the correct place.

What I did is that I have added this code:

add_filter( 'post_type_archive_title', '__return_empty_string', 5 ); 

to my functions.php file. This is the file where I put all other custom codes for my Blank Child Theme.
