### ISSUE TITLE
woocommerce - can't log in if cart isn't empty

### ISSUE THREAD

**Issue by wsiodelski** [woothemes/woocommerce#9813]
hi all

I have recently been testing my website and basically looks like I can't log in properly whenever something is on the cart. If it is guest checkout it works, returning customer checkout doesn't work.

summary:

1. nothing on the cart - can log in ok
2. add item to the cart - can't log in using my-account page
3. add item to the cart - can't use "returning user" at the checkout

When I attempt to login I get a message "your are logged in as ...." but in fact I am not logged in as I can't see my account details. - check picture attached

![logged](https://cloud.githubusercontent.com/assets/14012313/11709556/7b411c5e-9f10-11e5-9bef-9d6de04dd45b.JPG)

Also if I log in and then logout I need to clear browser history to login again (getting the same message as above otherwise - that I am logged in but see no account details)

any help much appreciated

Woocommerce 2.4.6
W3Total  Cache 0.9.4.1-  with various recommended settings - not sure which one is relevant to paste here

http://peakart.co.uk/my-account/

**Comment by mikejolley** [comment]
This will be related to your cache config. Viewing the source of the page, I can see its being minified and cached. Exclude cart, checkout and my account.

Minify also has a setting "Never minify the following pages" you can use.

And of course, disabling all caching/minify to test you won't (or shouldn't) see this issue. Other users and myself are not affected.

**Comment by wsiodelski** [comment]
I have contacted W3 Total Cache and offered to pay them to fix it but they said it wasn’t W3 Total Cache related.

 

They said it must be the Theme but Theme provider said it wasn’t. They asked me to deactivate all plugins and check them one by one but even with all of them de-activated the problem is still there

**Comment by mikejolley** [comment]
Even with caching plugins disabled, there is often caching files left over in wp-content which can still affect the frontend FYI. You'd be better off disabling the settings within the plugin, rather than deactivating.

**Comment by wsiodelski** [comment]
ok, so in the end with the help from W3 Total Cache team it is fixed. The problem was Varnish Server settings on my Bluehost Provider

server sitting between you as a website visitor and your webserver, it is able to cache or modify content too) and it handles https particularly.

Disabling that varnish server solved the problem.
