### ISSUE TITLE
Add variable products to cart using query string with specific attribute

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#9814]
@mikejolley If we take a look to below link:

`http://localhost/woocommerce/cart/?add-to-cart=3111&quantity[1803]=5&quantity[1903]=2`

Where 3111 is the id of a grouped product and 1803 and 1903 are variable products within the group, and 5 and 2 are the respective quantities of those products. My question is how to add the specific variation id and attribute just like how we use for variable product to add it via query string. 

Additionally, Is there anyway we can add two variable products with similar attributes together to the cart via query string :)

**Comment by mikejolley** [comment]
This isn't a supported endpoint - if you try to use variable products within a grouped product you'll see it just links through. Forms for variations are not shown on grouped product pages.
