### ISSUE TITLE
Updated to latest version of woocommerce and now unable to place orders

### ISSUE THREAD

**Issue by mellyonthenet** [woothemes/woocommerce#9815]
I would really appreciate some help with this. My client has an e-commerce store for harp sheet music on http://www.annemarieofarrell.com. A couple of months ago I updated woocommerce and my client had reported that she was getting duplicate orders (and irate complaints from customers). Today in an attempt to solve the problem I updated to the latest version of woocommerce and now it is impossible to place orders at all. The Paypal Place Order box is completely grayed out (Paypal is the only payment option she offers). In Chrome I am getting the error message: SyntaxError: Unexpected token <
 I have increased my PHP memory. I have tried deactivating all plugins and reactivating them one-by-one. To no avail. Please can you help. This is my client's busiest time of year and she is very unhappy about this.
 Regards,
 Mel

**Comment by mikejolley** [comment]
Mel, please don't abuse Github issues for support queries. We make it quite clear this is not a support portal. 

Regarding your problem, follow the instructions posted here http://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/ Once you see the error you can disable whatever plugin is causing it.

**Comment by mellyonthenet** [comment]
Thanks for your link, I was able to determine that it was WP Supercache that was causing the problem, even though I had deleted it, there was a line in my wp-config file. Once I changed that to false, the problem was solved. Thank you
