### ISSUE TITLE
add_coupon not deducting total from order

### ISSUE THREAD

**Issue by bittoo** [woothemes/woocommerce#9816]
I created order programmatically and used $order->add_coupon method. By checking in database, coupon value is saved properly in order item and order item meta table but coupon did not deduct total from order.
My Code for creating order is
        $order = wc_create_order();
        $order->add_product( get_product( '12' ), 1 );
        $order->set_address( $address, 'billing' );
        $order->set_address( $address, 'shipping' );
        $order->add_coupon('anytestcoupon','10','0');
        $order->calculate_totals();

![screenshot-etrainshop local 2015-12-10 17-00-54](https://cloud.githubusercontent.com/assets/7957309/11714941/b719f472-9f5f-11e5-9af7-490d11afa677.png)

**Comment by claudiosmweb** [comment]
Because the coupons are not calculated, they are only calculated in the cart.
