### ISSUE TITLE
simple product showing out of stock

### ISSUE THREAD

**Issue by lmcezar** [woothemes/woocommerce#9817]
Currently I am having trouble registering simple product in my store, for example I have 4 products in stock but when I go to cart it says I do not have in stock.

Some screenshots below show that my product:

![12322730_442973302558982_7686712695872313641_o](https://cloud.githubusercontent.com/assets/3679709/11717862/24ffcfbe-9f3a-11e5-8e82-b80c7da30d14.jpg)
![12357084_442973299225649_7870262090147648895_o](https://cloud.githubusercontent.com/assets/3679709/11717863/2500c338-9f3a-11e5-9324-2129fcccce25.jpg)
![12356942_442973305892315_373631365009728503_o](https://cloud.githubusercontent.com/assets/3679709/11717864/25047d02-9f3a-11e5-9423-7d17ef619430.jpg)

I appreciate the help

**Comment by mikejolley** [comment]
It's like on-hold in someone else's cart. See wp-admin/admin.php?page=wc-settings&tab=products&section=inventory
