### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by omargourari** [woothemes/woocommerce#9818]
Having the most annoying (and quite discussed) "SyntaxError: Unexpected token < " error.

Current configuration:
- - - - - -
stack: trellis+bedrock+sage [https://roots.io]
plugins: (just) Woocommerce 2.4.12
Wp: WordPress 4.4
Payment gateway: Paypal and Bank transfer

Things I've tried
- - - - - - - - - - - - 
Tried to reproduce the error by changing Woocommerce plugin versions to previous versions.
I've checked the persistence of the error with all the versions from 2.3.5 to 2.5.0 Beta 2 and isolated the problem between versions 2.3.13 and 2.4.0.

The error message I get - I'm checking from the Chrome developer tools > Network > Preview - is:

Fatal error: Call to a member function add_product() on boolean in /srv/www/website.com/current/web/app/plugins/woocommerce-2.4.0/includes/class-wc-checkout.php on line 217

The error happens both on Paypal and Bank transfer method.
Error logging configuration is set correctly - following WordPress guidelines - and the error_log is empty.
I need to solve this issue (not just make it invisible by disabling the relative wp-config development options).

Any suggestions?

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/blob/release/2.4/includes/class-wc-checkout.php#L222

Check your error logs - the order is not being created. (false)

**Comment by omargourari** [comment]
My fault
The error was generated by a useless custom post that I created for products.
