### ISSUE TITLE
"Related Products" broken on IE 9, 10, 11

### ISSUE THREAD

**Issue by azn785** [woothemes/woocommerce#9822]
The "Related Products" section renders weirdly on Internet Explorer. Tried looking in compatibility mode for all versions. Could easily be my theme, but was wondering if there was a fix? Perhaps it's a small CSS thing? Here's the website:  http://www.marketingtechnologyinsights.com/product/live-instructor-led-training-january-2016 

![image](https://cloud.githubusercontent.com/assets/16245856/11726764/2a2e6db0-9f4e-11e5-9b1a-5e3623bf306c.png)

Renders perfectly in Google Chrome, by the way.

**Comment by mikejolley** [comment]
Your theme is missing a 'clearfix'. Check with the author, as it looks like your theme has custom styles for WooCommerce.
