### ISSUE TITLE
Add order_key in API

### ISSUE THREAD

**Issue by BasicPro** [woothemes/woocommerce#9823]
Hi,

Just wondering why "order_key" is not returned when you create an order with the API (v3). Right now I create an order and pay it through PayPal SDK (Android) and I'm trying to find a way to create an order and setup the PayPal payment so PayPal's IPN system will trigger the server with the correct information so the order gets completed when the payment is processed.

Right now I have to complete it myself by updating it from the app when I receive the success payment.

Regards

**Comment by claudiosmweb** [comment]
@maxrice some reason?

**Comment by maxrice** [comment]
@claudiosmweb nope, no specific reason this isn't included in the orders response. Definitely seems reasonable to add :)

**Comment by claudiosmweb** [comment]
@maxrice thanks :)
