### ISSUE TITLE
Payment Gateways no Longer Function in WP 4.4 - WC 2.4.x

### ISSUE THREAD

**Issue by mraburn** [woothemes/woocommerce#9824]
This might be wrong place to post but I thought it urgent for an FYI.  Upgrading from Wordpress to 4.4 which came out Dec 8th,  and running WC 2.4.12, .11 and/or 10 our payment gateways stopped working, to include Paypal Pro and Paypal Express. I also saw a user post on the WP Forums that his Stripe gateway was no longer working.

The error was about SSL certificates.

"12-11-2015 @ 02:41:33 - Error SSL certificate problem: unable to get local issuer certificate"

WC 2.4.12 is also painfully slow in the wp-admin area of the site under WP 4.4, BUT WC version 2.4.12 is ok in this regard on WP 4.3.1.

For me to resolve, was to revert WP back to 4.3.1 and all is well again with the Gateways.

Might want to take a look at see what changed on the WP side because I imagine a lot of sites are about to be broken if the admin upgrades the WP version, as I did. :/

**Comment by WPprodigy** [comment]
Likely related: https://core.trac.wordpress.org/ticket/34935

**Comment by mikejolley** [comment]
^ yep that will be the one. Monitor that trac ticket.
