### ISSUE TITLE
[REST API] Order with more than one variation not working

### ISSUE THREAD

**Issue by stevechan3310** [woothemes/woocommerce#9825]
Currently using 2.4.8 WC version and connecting using V3. Followed the documentation to add variations when creating order as below.

This works (One variation)
---------------------
"line_items": [
            {
                "product_id": 546,
                "quantity": 2
            },
            {
                "product_id": 613,
                "quantity": 1,
                "variations": {
                    "pa_color": "Black"
                }
            }
        ],

Does not work (More than one variations)
----------------------
"line_items": [
            {
                "product_id": 546,
                "quantity": 2
            },
            {
                "product_id": 613,
                "quantity": 1,
                "variation": {
                      "pa_color": "Black",
                      "pa_size": "XGG"
                }
            }
        ],

The response on line items meta will be empty when more than one variations.
Possible a bug?

**Comment by roykho** [comment]
Missing an "S" in your "variation" ?

**Comment by stevechan3310** [comment]
<img width="681" alt="screen shot 2015-12-11 at 1 37 09 pm" src="https://cloud.githubusercontent.com/assets/15008522/11736703/583a2686-a00c-11e5-92f9-634525068805.png">

Documentation states more than one variation is without "S". And if i add the "S" for more than one variations, it returns error.

**Comment by roykho** [comment]
What error is it returning you?

**Comment by stevechan3310** [comment]
It returns error code 400. Invalid product variations. But i managed to solve it. I added back the "S" and changed from array of variations into variation dictionary. Btw, im integrating on ios. Please update the documentation to add the S even when more than one variations. Its confusing. Thank you for the help.
