### ISSUE TITLE
Refund orders and totals missing from Reports

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#9827]
When an order is only partially refunded, or fully refunded but the order status is not set to "Refunded", the order and its refunded amount are not included in the axis totals in Reports. However, the refunded amount displays correctly in the chart itself.

![](http://cld.wthms.co/H7Ak/5Rub7SvZ+)

It would make sense for the order and the refunded amount to be included in the totals sidebar.

**Comment by SiR-DanieL** [comment]
Maybe related to https://github.com/woothemes/woocommerce/issues/8899 ?

**Comment by mikejolley** [comment]
Was unable to replicate in master and 2.4.

Order: https://dl.dropboxusercontent.com/s/tpjtlwf9l1gob89/2015-12-14%20at%2011.33.png?dl=0

And the report afterwards: https://dl.dropboxusercontent.com/s/3fd7rncuk25uir1/2015-12-14%20at%2011.34.png?dl=0

**Comment by MindyPostoff** [comment]
@mikejolley In your screenshot, I still see an issue, though:
![](http://cld.wthms.co/18Lb5/1cHzoKBH+)

The total number of orders isn't displaying correctly. In my testing, I see this, too, on my test site: 
![](http://cld.wthms.co/1bsk3/3UjnnmFB+)

**Comment by mikejolley** [comment]
@MindyPostoff the order wasn't refunded in my screenshot - it was partially refunded. The ITEM was refunded. So 0 orders, 1 item is accurate. It would say 1 if I refunded the entire order.

p.s. I can see follow ups without reopening ;) Can reopen if this bug is confirmed or can be replicated.
