### ISSUE TITLE
Some order loses variations

### ISSUE THREAD

**Issue by marcot1t** [woothemes/woocommerce#9828]
Hi, I have published www.internoitaliano.com (with woocommerce and WPML) where I have a lot of product with variations.

I've solved the problem about losing variation in back-end setting max_input_vars to 10.000.
Now randomly I see some order without variation value:

es. Color:  Variation: Set

![schermata 2015-12-11 alle 17 05 38](https://cloud.githubusercontent.com/assets/9050759/11748655/89886f3c-a029-11e5-8e68-98418321b9df.png)

I don't know where is the issue because on 10 orders this problem occours 1-2 times.

**Comment by mikejolley** [comment]
I'd suggest narrowing down the cause i.e. user's language, and trying to replicate this with and without WPML active. We cannot debug WPML issues here - it duplicates terms and attributes etc which are outside core's scope. 

You can also 'edit' that line item to see if data is set, but hidden, due to translation.

**Comment by marcot1t** [comment]
I've tried to replicate this with and without WPML, but the problem appears in a random way in the main language and with the traduct version.
I'm investigating all the possibility, it's possible a problem with the "post" variable for the user?

**Comment by marcot1t** [comment]
Sometimes when I reload the Cart ... some variations disappears!
I've tried this also without my woocommerce variations folder in my theme

![schermata 2015-12-14 alle 15 57 01](https://cloud.githubusercontent.com/assets/9050759/11784233/855a4a58-a27b-11e5-8141-ca4cba06b7a3.png)

**Comment by mikejolley** [comment]
It could be cut off - some servers do limit the size of things like arrays. Not sure how you'd identify this without var dumping the cart items.
