### ISSUE TITLE
Fatal error on my-account/view-order/### for non-existing order numbers.

### ISSUE THREAD

**Issue by dustyf** [woothemes/woocommerce#9829]
If you were to visit the view order page under my-account for an order number that does not exist, fatal error is caused. Even though, this is page doesn't display any actual product data, it should error more gracefully or return a 404 result. 

The following error is returned: 
Fatal error: Call to a member function get_status() on a non-object in /srv/www/site/htdocs/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php on line 119

wc_get_order() is returning false with no order existing and it's trying to runt he get_status method on false.

I will submit a pull request to check that the order exists and if not display an error and return a 404 status code.

**Comment by claudiosmweb** [comment]
Seems like have something wrong in your installation our using a old version.

Since is displayed this message for non-existing orders:

![screenshot from 2015-12-12 01-03-52](https://cloud.githubusercontent.com/assets/1264099/11759869/4f547426-a06c-11e5-8dac-5f7fdaaa1ded.png)
