### ISSUE TITLE
woocommerce reports not right with shipping (tax issues)

### ISSUE THREAD

**Issue by KushClean** [woothemes/woocommerce#9831]
There's also another problem with wooCommerce,
When free shipping is granted the cost that the item is usually requires for shipping, should be deducted from the shipping charges as a negative value. Currently free shipping is not counted as any of the shipping and this is technically and for all tax purposes wrong because it is a loss to the company and a tax write off.

So let's suppose an item has a shipping charge normally of $5
Now let's pretend I grant them free shipping with the coupon or other method

Under the column of reports the shipping section it only shows charges for shipping that were actually charged to the customer. But not the free shipping that is a loss to the store.

So what I'm saying is if a person buys a 50$ item with $5 shipping fee normally on that item.
Now the customer uses a free shipping coupon
It still cost our company five dollars to mail it out, The way woocommerce is set up currently it does not keep track of all the free shipping granted

If items do you have a shipping price attached to the product but a coupon is used the shipping price should still be deducted and calculated as a loss to our company in the reports section

Please get back to me on this problem as well I would like to know how to solve this

Because on my website I basically get free shipping for every order over $50

But I still have to pay for shipping which is not profit to my company but a loss to my company and it should be tracked by the reports but it is not

This issue and the issue with the refunds that we already talked about are the only issues I have noticed

**Comment by mikejolley** [comment]
Reports should not track this. Reports track **sales**. The customer didn't pay the $5 so it is not recorded. Your expenses are not something WC should or does track. WC is not accounting software.
