### ISSUE TITLE
Using /wc-api/v3/orders to create order and new order email is not fired

### ISSUE THREAD

**Issue by tkchuah** [woothemes/woocommerce#9833]
HI guys

I have configured woocommerce backend to fire an email to a list of email when new order is created via Woocommerce -> Setting -> Email -> New Order.

It works correctly if I were to place order through website. Email is received. However, If i were to use the API instead to create order, no email will be sent ?

thanks
TK

**Comment by claudiosmweb** [comment]
Email are sent when change status to on-hold or processing. Or when the order is paid.

**Comment by tkchuah** [comment]
Wow.. how can you just close this issue just like that ? 

The fact is that new order email is not fired is a problem ! Having the need to go to the backend and constantly poll for the order and then only change status to have email sent has beaten the purpose completely

**Comment by mikejolley** [comment]
@Claudiosmweb does API trigger emails or is this for on-site orders only?

**Comment by claudiosmweb** [comment]
@tkchuah @mikejolley API don't trigger emails, WooCommerce does...

When change status:
https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-orders.php#L667-L670

When is paid:
https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-orders.php#L477-L492

> Wow.. how can you just close this issue just like that ? 

Yes I can, since it works fine.
Use my example on http://woothemes.github.io/woocommerce-rest-api-docs/#create-an-order and you'll see email be fired!

**Comment by tkchuah** [comment]
@claudiosmweb I am kinda confused with your final statement. So basically, if I understand you correctly, API will not trigger email even though I have configured in the backend to have the email event.

So basically, we have an incomplete support for API at this point of time.

**Comment by claudiosmweb** [comment]
@tkchuah This will be too complicated, since you have not tested anything!

API don't need trigger any email, since WooCommerce trigger it when you change order status or complete the payment, as I showed in the example that YOU COMPLETELY IGNORED.

**Comment by tkchuah** [comment]
@claudiosmweb I did read your comment, and I agree what you are suggesting is working.

However, I think you have completely missed the point. Imagine I build a mobile app using Woocommerce API. When an order is placed via mobile app (API), it has to exhibit the same behavior as if the order is being made via the app - meaning the new order email must be sent. 

Without email notification for new order, Merchant have to manually and constantly look at the backend and be always worried they might miss a new order !

Going along with that line, I therefore think that the API support today is incomplete.

thanks

**Comment by claudiosmweb** [comment]
> However, I think you have completely missed the point. Imagine I build a mobile app using Woocommerce API. When an order is placed via mobile app (API), it has to exhibit the same behavior as if the order is being made via the app - meaning the new order email must be sent. 

Using WooCommerce every order made is pending status by default, after it's changed and emails are sent.
So works in the same you, you just need to create an order using the API, after you can enter the payment or change the order status and all emails will be send!
