### ISSUE TITLE
[API] $order->get_total_discount returns (float) 1.7763568394003E-15 in rare cases

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#9834]
`get_total_discount` returns a float. In very rare cases I get a discount of `(float) 1.7763568394003E-15` which is `(int) 0`. I get this sometimes on manually added orders, say 1 in 100 cases.

If you google for 1.7763568394003E-15 then you'll find out that this is due to the shortcoming of floating point arithmetics (google shows 75k results, imho this is actually a php bug): 
* http://forums.devshed.com/php-development-5/1-1-equals-0-a-384040.html
* http://board.phpbuilder.com/showthread.php?10287705-Weird-math-results

Problem is that comparisons against 0 (to find out if there is any discount) do not work anymore. As in 
`if ( $order->get_total_discount() > 0 ) {`
as in [class-wc-gateway-paypal-request.php](https://github.com/woothemes/woocommerce/blob/f408dcdabc611bf19d415d20b5081f73fd753438/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L168) do not work because logically 1.7763568394003E-15 is 0, but technically/mathematically it is not and the above evals to true (though there actually is no discount).

I became aware of this problem as a user of a woocommerce plugin, where the bug was eventually closed by having an extra safety guard like using
`if ( round( $order->get_total_discount(), 3 ) != 0 ) {`
instead of
`if ($order->get_total_discount() != 0 ) {`

See https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/12 for reference.

But in the end I think that this safety measure should be added to woocommerce itself and not being delegated to all plugins that use the API.

**Comment by madeshswamy768-maker** [comment]
Amount
