### ISSUE TITLE
Woothemes Cloud Zoom product images not changing over since upgrade

### ISSUE THREAD

**Issue by chaduk** [woothemes/woocommerce#9835]
I have recently upgraded to Wordpress 4.4 and also have the latest version of Woocommerce (2.4.12). However since upgrading Wordpress the Cloud zoom plugin has stopped working properly. It displays the main default image, however when you click on each thumbnail the default image doesn't switch over. So you basically get the zoom of each thumbnail but the same default image that never changes. Interestingly enough it works properly on safari but not on Chrome and Firefox.. I've read up on other similar threads but their solutions have not worked for me. Please assist

**Comment by claudiosmweb** [comment]
This repository is not suitable for support.
Please don't use our issue tracker for support requests, **but for core WooCommerce issues only**.

Support can take place in the appropriate channels:

* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
* [Our community forum on wp.org](https://wordpress.org/support/plugin/woocommerce) which is available for all WooCommerce users.

Or check our documentation:

* [WooCommerce Documentation](http://docs.woothemes.com/documentation/plugins/woocommerce/)
* [WooCommerce Knowledge Base](https://support.woothemes.com/hc/en-us/categories/200146917-WooCommerce)
* [WooCommerce Code Reference](http://docs.woothemes.com/wc-apidocs/)
* [WooCommerce REST API Docs](http://woothemes.github.io/woocommerce-rest-api-docs/)

**Comment by claudiosmweb** [comment]
Since it is a WooThemes plugin, use the [WooThemes premium support portal](http://support.woothemes.com/).

**Comment by mikejolley** [comment]
Ah so payment details are needed to trigger the email, got it.

**Comment by claudiosmweb** [comment]
@mikejolley wrong place xD

**Comment by mikejolley** [comment]
Oops :p
