### ISSUE TITLE
[API] PUT and POST return "501 Method not implemented" on http connection

### ISSUE THREAD

**Issue by robertslagter** [woothemes/woocommerce#9838]
When trying to perform any PUT or POST command on the REST API (v3) over a http connection, the user receives a "501 Method Not Implemented" error. 
The error occurs for instance on updating products (one product or in bulk) using the Python official library, cURL or the PHP library.
GET commands work as intended. Please note that the issue occurs even though the user credentials refer to an admin account, which has read/write access in the WooCommerce API.

The exact error message is:
PUT to /wc-api/v3/products/156 not supported.
(while 156 refers to a valid product id)

**Comment by claudiosmweb** [comment]
I bet that have something in your server changing it, like something in your `.htaccess` or nginx config.
Many servers have PUT, POST and DELETE blocked for safety.
Please check it.

**Comment by robertslagter** [comment]
I hope you are right, but it does not seem to be the case.
My .htaccess does not include anything special I think:

\<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
\</IfModule>

I have asked my provider today, and they do not have any other rewrite or blocking rules running.
Thank you so much for helping, as this is driving me crazy ;-)

**Comment by claudiosmweb** [comment]
Still can be have it in your apache config.
Check it too.

**Comment by robertslagter** [comment]
You were right! Thank you so much - my hosting provider had a check in apache that prevented PUT requests, While they were digging into the issue they found out logging was not set up properly, and because of that the error dit not show up in my logs.
 
The PUT request was blocked by:
modsecurity_crs_30_http_policy.conf

**Comment by claudiosmweb** [comment]
Cool, tomorrow I add a note about it in our docs. Thanks.

**Comment by claudiosmweb** [comment]
Note added: http://woothemes.github.io/woocommerce-rest-api-docs/#troubleshooting

**Comment by hram908** [comment]
Note: 404

**Comment by willgorham** [comment]
http://woocommerce.github.io/woocommerce-rest-api-docs/

https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#common-connection-issues
