### ISSUE TITLE
Update a variable product by SKUs gives The SKU already exists on another product

### ISSUE THREAD

**Issue by TOuhrouche** [woothemes/woocommerce#9839]
Excellent work on this API guys! Hat's off :+1: 
I have the very same problem as the one [described here](https://github.com/woothemes/woocommerce/issues/8699) where I would like to update a set of product variants' quantities by their SKUs (not IDs). Here is an example of a json data payload I put to my store:
`{ products: [ {sku:142,variations: [ {sku:142-143,stock_quantity:100} , {sku:142-144,stock_quantity:100}, {sku:142-145,stock_quantity:95} , {sku:142-146,stock_quantity:100} ] } ] }`
I triple checked all my products and tables, all these variants have unique SKUs:
Parent product SKU = 142
Variation1 SKU = 142-143
Variation2 SKU = 142-144
Variation3 SKU = 142-145
Variation4 SKU = 142-146
 Is there a way around this without having to query the variant IDs given their SKUs (will take a huge performance hit otherwise :( )?

**Comment by claudiosmweb** [comment]
Use our bulk endpoint:
http://woothemes.github.io/woocommerce-rest-api-docs/#create-update-multiple-products
You can bulk update/create using `id` or `sku`.

**Comment by TOuhrouche** [comment]
Thanks for the quick follow up. I am actually using the bulk API endpoint you mentioned above. It works for simple products but returns the error I mentioned in the title for variable products

**Comment by claudiosmweb** [comment]
You can pass the variations as single products too.

Like:

```json
{
  "products": [
    {
      "sku": "142-143",
      "stock_quantity": 100
    },
    {
      "sku": "142-144",
      "stock_quantity": 100
    },
    {
      "sku": "142-145",
      "stock_quantity": 95
    },
    {
      "sku": "142-146",
      "stock_quantity": 100
    }
  ]
}
```

**Comment by TOuhrouche** [comment]
Ah that's a lot better. Issue fixed. Thank you very much for your support :)

**Comment by Filoz** [comment]
Hi.
I'm really sorry for opening this old issue...  but I can't find any information in http://woocommerce.github.io/woocommerce-rest-api-docs/ about updating product by sku.

Is it still possible or it was removed from API?
