### ISSUE TITLE
SKU with dash not accepted after previous success?

### ISSUE THREAD

**Issue by RecursiveS** [woothemes/woocommerce#9840]
I have started getting the following error:
"Fatal error:  Uncaught exception 'WC_API_Client_HTTP_Exception' with message 'Error: Invalid product SKU [woocommerce_api_invalid_product_sku]..."
when attempting to load a product through the API.
What puzzles me is that it loaded two products (all my products have a dash in them) before deciding that it was invalid.
I deleted the two successful products and attempted to re-load one of them - that too failed.
Why is the dash not allowed? Do I have to change my entire part numbering system because of this?

**Comment by claudiosmweb** [comment]
I need more details about it:

> "Fatal error: Uncaught exception 'WC_API_Client_HTTP_Exception' with message 'Error: Invalid product SKU [woocommerce_api_invalid_product_sku]..."

In what line?

> Why is the dash not allowed? 

Dash is allowed, but seems to have another error.

**Comment by RecursiveS** [comment]
Thank you for your response which meant that I could ignore comments I had seen elsewhere. I have now re-evaluated my code and found that the error is being generated by a call I make to see if the sku already exists in the store database - if it is not it returns the error as described. I had read the error literally when it was really saying that the "sku does not exist". Perhaps this error could be mad a little clearer in future releases?
Anyhoo, thanks again for your response, it helped a great deal.
