### ISSUE TITLE
2.5.0-beta-2 tag has version number 2.5.0-beta-1 ← can’t update via beta tester plugin

### ISSUE THREAD

**Issue by glueckpress** [woothemes/woocommerce#9841]
The plugin header in [2.5.0-beta-2](https://github.com/woothemes/woocommerce/blob/2.5.0-beta-2/woocommerce.php) still shows `2.5.0-beta-1` as version number. As a consequence, the WooCommerce Beta Tester plugin perpetually indicates there’s an update available even after 2.5.0-beta-2 has been installed correctly (diffed files, all ok, it’s just the version number).

For myself I manually edited the version number after updating. Would it be too much of a hassle, though, to re-tag 2.5.0-beta-2 with a correct version number? I’m thinking of user tests we’ve scheduled where we planned to recommend the beta tester plugin. We could obviously tell users to manually edit the version number as well, but if that could be avoided, we’d really appreciate it. :wink:

**Comment by mikejolley** [comment]
Ill be tagging beta 3 soon, so this won't be an issue for much longer.

**Comment by glueckpress** [comment]
Thanks!
