### ISSUE TITLE
Free Shipping deducted from shipping totals in Reports?

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#9842]
Issue raised from a support ticket:

When free shipping is granted the cost that the item is usually requires for shipping, should be deducted from the shipping charges as a negative value. Currently free shipping is not counted as any of the shipping and this is technically and for all tax purposes wrong because it is a loss to the company and a tax write off.

So let's suppose an item has a shipping charge normally of $5 
Now let's pretend I grant them free shipping with the coupon or other method

Under the column of reports the shipping section it only shows charges for shipping that were actually charged to the customer. But not the free shipping that is a loss to the store.

So what I'm saying is if a person buys a 50$ item with $5 shipping fee normally on that item. 
Now the customer uses a free shipping coupon 
It still cost our company five dollars to mail it out, The way woocommerce is set up currently it does not keep track of all the free shipping granted

If items do you have a shipping price attached to the product but a coupon is used the shipping price should still be deducted and calculated as a loss to our company in the reports section

**Comment by mikejolley** [comment]
I answered this one here https://github.com/woothemes/woocommerce/issues/9831

Also bare in mind, you'd have no way of knowing which shipping method should or would have been used, and shipping are quotes - not real business costs, so reporting would be inaccurate.
