### ISSUE TITLE
REST API listing product attributes

### ISSUE THREAD

**Issue by zmilan** [woothemes/woocommerce#9844]
Hi,

I have problem with listing product attributes by following documentation http://woothemes.github.io/woocommerce-rest-api-docs/?shell#view-list-of-product-attributes . I believe that there is some issue with documentation/implementation, since there is no way to send product id for which you requesting attributes.

I try this 2 cases:
- I try to use it exactly like it is in documentation `/wc-api/v3/products/attributes`, but in that case I'm getting empty list (but success response).
- I try to use it like ` /wc-api/v3/products/[productID]/attributes`, but in this case I'm getting "Code#404, Message: Error: No route was found matching the URL and request method [woocommerce_api_no_route]" error.

Is there something that I'm doing wrong, or this not working correct?

**Comment by claudiosmweb** [comment]
This repository is not suitable for support.
Please don't use our issue tracker for support requests, but for core WooCommerce issues only.

Support can take place in the appropriate channels:

* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
* [Our community forum on wp.org](https://wordpress.org/support/plugin/woocommerce) which is available for all WooCommerce users.

Or check our documentation:

* [WooCommerce Documentation](http://docs.woothemes.com/documentation/plugins/woocommerce/)
* [WooCommerce Knowledge Base](https://support.woothemes.com/hc/en-us/categories/200146917-WooCommerce)
* [WooCommerce Code Reference](http://docs.woothemes.com/wc-apidocs/)
* [WooCommerce REST API Docs](http://woothemes.github.io/woocommerce-rest-api-docs/)

**Comment by zmilan** [comment]
@claudiosmweb I'm not totally sure that this is not issue. Maybe I wasn't clear with my comment. Can you, please, even inform me is this bug/issue in API/documentation or I'm doing something wrong? If I'm doing something wrong I will figure how to solve it, but this looks like possible bug/issue and that is why I post it here. Thanks in advance.

**Comment by claudiosmweb** [comment]
@zmilan Not a bug/issue, you just need to read the docs.

**Comment by zmilan** [comment]
@claudiosmweb thanks, I will do it again.
