### ISSUE TITLE
WP Rocket Cache and tax calculations

### ISSUE THREAD

**Issue by tomob7** [woothemes/woocommerce#9845]
Hi,

I've seen a few things about geolocation caching issues around but thought I would raise a ticket just in case, the tax settings do not work/calculate correctly if you use wp rocket, I suspect this has something to do with the geolocation.

My problem was I had prices inclusive of tax and had a tax rate of 20% for GB however all my prices on the site showed as without tax, I have since made the 20% apply to everywhere and this has resolved the issue for now but it is not a viable solution in the long term so I suspect the problem was that the site did not know to apply the VAT(20%) because it didn't know you were in the GB.

**Comment by claudiosmweb** [comment]
> few things about geolocation caching issues 

Even with Geolocate with page chacing support?

![screenshot from 2015-12-14 15-50-11](https://cloud.githubusercontent.com/assets/1264099/11788894/700414d2-a27a-11e5-88ff-90641797a5cc.png)

**Comment by tomob7** [comment]
Ah I didn't see that option, I'll give it a try!

Thanks
