### ISSUE TITLE
Taxes REST api route not working?

### ISSUE THREAD

**Issue by BasicPro** [woothemes/woocommerce#9847]
Hi,

I'm using the API for many queries but I can't get this one to work. Taxes route is not docummented but I found it in the api files and I wanted to use it.

I'm using GET request to the route /wc-api/v3/taxes and I'm getting a woocommerce_api_no_route error. I'm using the same exact class to call the api as I do to retreive the orders and customers, and those work fine. I also tried to use POST and I get the same error (when I should get a different error: "no $data value").

All the other routes inside /taxes , like /taxes/count do not work either.

Maybe I'm doing something wrong but I runned out of ideas, everything else on the API works just fine.

Regards

**Comment by claudiosmweb** [comment]
What WooCommerce version?

**Comment by BasicPro** [comment]
I'm using the latest stable version but now that I check it is 2.4.12 and in the WC_API_Taxes class file I read "Since 2.5.0", so maybe it is not active yet, however the routes are created and the class file is registered so not sure why is not working.

**Comment by claudiosmweb** [comment]
> "Since 2.5.0"

Means that will be available on WooCommerce 2.5.0 and not before!

> however the routes are created and the class file is registered so not sure why is not working

Where?

We don't have any file for it in 2.4.12: http://plugins.svn.wordpress.org/woocommerce/tags/2.4.12/includes/api/

**Comment by BasicPro** [comment]
Sorry you are right, I downloaded the latest version from woothemes page and assumed it would be the same last stable version that I have in the server but it is actually 2.5.0-beta-2. I just realized, I will update the server and it will sure work.

My apologizes, however you helped me find the issue although it was my stupidity.

Regards
