### ISSUE TITLE
Odd category of an order

### ISSUE THREAD

**Issue by calendarboy** [woothemes/woocommerce#9848]
Thought you might want to know. 
At the top of the Orders page it offers several selections:  
All, Trash, Processing, Completed, Cancelled, Refunded, Failed.

Starting last week it has a new category called "Mine". It is listing one order. The order was by a "Guest", not a User. The order has a status of "Completed". The order is from April 2013. 

I've tried changing the status to processing, saving and updating, then changing back again to completed, saving/updating. Didn't help.

**Comment by claudiosmweb** [comment]
Not a category... It's a post status: https://codex.wordpress.org/Post_Status
Post status need to be registered with `register_post_status()` so if you have a "Mine" post status, this means that have in some place some code to do it too...

Don't seems to be an issue with WooCommerce, probably with another plugin...

**Comment by claudiosmweb** [comment]
Or maybe orders imported incorrectly.

**Comment by calendarboy** [comment]
I have/had not imported orders at all.
The day before noticing the "Mine" category, I had updated thwo things: to WP Version: 4.4 and updated Amazon Payments to the as-yet-unreleased 1.5.

**Comment by cokolooks** [comment]
> Hello, I have been facing the same problem very recently. I don't know how to fix that. It seems all latest order in my website are falling under that "Mine" status. Is there anyone who can tell me how to fix that?
> ![order_status_mine](https://user-images.githubusercontent.com/44866609/48196015-79475280-e37b-11e8-9106-612f823e4ceb.png)

Do you have wc vendors installed?

**Comment by alieninfluenza** [comment]
> > Hello, I have been facing the same problem very recently. I don't know how to fix that. It seems all latest order in my website are falling under that "Mine" status. Is there anyone who can tell me how to fix that?
> > ![order_status_mine](https://user-images.githubusercontent.com/44866609/48196015-79475280-e37b-11e8-9106-612f823e4ceb.png)
> 
> Do you have wc vendors installed?

No.

**Comment by willgorham** [comment]
@alieninfluenza This is a known bug: #21834
