### ISSUE TITLE
'Error invalid shipping method when using Chrome autocomplete

### ISSUE THREAD

**Issue by phily245** [woothemes/woocommerce#9850]
Following on from 'Error invalid shipping method when using chrome autocomplete form (#3022), Chrome has changed it's autocomplete. My checkout has the billing address set to be the delivery address and, when the postcode is autofilled in the checkout, it doesn't trigger the javascript to update the order review table with the shipping details.

**Comment by claudiosmweb** [comment]
Seems to be fixed here since #3503
Do you have any js errors in your browser console?

**Comment by phily245** [comment]
It appears not, these changes could have been overwritten? Compare lines 30-34 of the checkout.js on the release/2.4 branch with the checkout.js changes at commit 19674a3 which closed #3022. I have fixed my copy so that it works and am in the process of making a patch.

**Comment by claudiosmweb** [comment]
You're right, we lose the correction over time. Please feel free to submit a patch :)

**Comment by mikejolley** [comment]
'input' event was breaking IE I believe. Will need to trawl logs.

**Comment by phily245** [comment]
Can anyone spot why my pull request failed the Travis-CI check? I've only change one thing!
