### ISSUE TITLE
Add filter for coupon type in validate_cart_excluded_items()

### ISSUE THREAD

**Issue by jconroy** [woothemes/woocommerce#9854]
Currently when you apply a product discount coupon which excludes one of your cart items (by product, category etc.), the coupon discount still applies to the cart but only discounts the 1 product in the cart. 

This is because the `fixed_product` and `percent_product` coupon types are excluded here: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-coupon.php#L473 - so the coupon is not invalidated (and stays applied).

Would it be possible to add a filter here to allow extensions with custom coupon types to add their coupons to the list to similarly be excluded.

Example use case - in Subscriptions - when a product/category is excluded from a recurring product discount coupon, and that product/category is in the cart the entire coupon is invalided and not applied to the cart.. even if there are products that qualify for the discount.

There also other spots like https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-coupon.php#L448 where the `fixed_product` and `percent_product` coupon types are singled out that might also benefit from a filter of sorts.

**Comment by mikejolley** [comment]
@jconroy can you confirm thats all you need?

**Comment by jconroy** [comment]
:+1: yep that looks like it does the trick!
