### ISSUE TITLE
Order numbers incorrect in backend but correct in cart.

### ISSUE THREAD

**Issue by stagfoo** [woothemes/woocommerce#9855]
Hi,
I have a woo commerce shop just did an upgrade and now the orders in the backend of wordpress are showing strange numbers.

![test](https://www.evernote.com/l/AUZ3OKFZhsROAZeLwz2SQjjJ4nqPz4J2qhEB/image.png" alt="Edit%20Order%20%E2%80%B9%20Joan%20Butts%20Bridge%20%E2%80%94%20WordPress")

pretty much just showing random amounts on products that have been ordered. eg 4 instead of 1

Have you seen this issues before?

**Comment by mikejolley** [comment]
Not seen this before - could be a plugin interfering during order creation. The qty values do get filtered.

The code for storing cart items here here https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-checkout.php#L221-L243 Notice it just uses the values directly from the cart. 

Rule out custom code and plugins.
