### ISSUE TITLE
Woo Commerce API - GET Products returning “1”?

### ISSUE THREAD

**Issue by SeanoSL** [woothemes/woocommerce#9859]
Hi,

I am calling Woo commerce's API through a REST Client however the API is responding with 200 OK however the body is returning "1".

Please refer to: http://stackoverflow.com/questions/34303245/woo-commerc-api-get-products-returning-1

I have spent a few days trying to figure out what is going on - SSL is valid and installed, all plugins seem to not have anything to do with the API, any ideas?

**Comment by WPprodigy** [comment]
You aren't making the connection correctly. Refer to the docs here: http://woothemes.github.io/woocommerce-rest-api-docs/, or just use this wrapper: https://github.com/kloon/WooCommerce-REST-API-Client-Library

**Comment by SeanoSL** [comment]
Can you please elaborate? I am connecting to the API on another Woo Commerce site with no issue at all. I am testing through a REST console however it would be called from a VB.NET application.

As i said i haven't had an issue with the other woo commerce store when using the same library/protocol in VB.NET.

**Comment by mikejolley** [comment]
'1' could mean you are not hitting an endpoint for the API, so it's just dieing. Maybe check if the API is setup correctly on the site, and the permalink structures are setup correct in WordPress > Settings > Permalinks.

Please don't use our bug tracker for support questions btw. If it were a core bug, it wouldn't work on any of your sites.
