### ISSUE TITLE
484,583 _transient_wc_product_children_ids_%

### ISSUE THREAD

**Issue by galbaras** [woothemes/woocommerce#9860]
There are 484,583 _transient_wc_product_children_ids in wp_options, which are not cleared by Clear Transients or Clear All Expired Transients.

Can these be deleted? Can they be selectively deleted? Can they be regenerated?

Please advise.

There are also transients for ratings (_transient_wc_rating_count_%), although ratings are disabled in the cart settings. Can these be deleted?

Thank you,
Gal

**Comment by mikejolley** [comment]
They can be - no transient data is permanent. They are also being overhauled in 2.5 https://woocommerce.wordpress.com/2015/12/04/woocommerce-2-5-beta-2/
