### ISSUE TITLE
Total Sales on grouped products

### ISSUE THREAD

**Issue by daveredfern** [woothemes/woocommerce#9862]
Hello,

This is technically not a bug but think it might be something to consider.

There is post meta for each product to show the total sales for that product. This allows for ordering of products by sales.

When using grouped products it will always have zero sales. This is correct because grouped products cannot be purchased – they require children products. If the children products are not visible there is no way to order by total sales unless you do a bespoke sql query.

It would be nice if total sales post meta for grouped products would be the total sales of all children products.

Thanks,

Dave.

**Comment by WPprodigy** [comment]
I've seen similar requests for variations as well. With each variation having a total sales option on it. 

Though I think this request has been more focused towards using the total sales meta for displaying a number to customers on the product page, rather than actual sorting.

**Comment by daveredfern** [comment]
@WPprodigy I didn't think of that possibility of showing number of sales but that would be useful too. At the moment sorting and sales counts don't work if using grouped products. We've had to implement a lengthy custom query where we fetch children products and add the totals up so we can order by sales.

**Comment by mikejolley** [comment]
I've decided this should be punted to after working on the new order tables - it may be possible without storing and syncing extra data once those optimisations are made.

**Comment by heArt-coder** [comment]
Its been a year but this is still needed please consider implementing this enhancement... i display total sales under price and its really helpful for small stores that needs to do everything to look 
trustworthy. And manually editing total sales on grouped item is looking suspecious for revisiting users.

**Comment by Stapelchips** [comment]
@mikejolley Why did you close this? AFAIK this is still impossible yet still needed. Or is there a different solution to this problem?

**Comment by mikejolley** [comment]
Still waiting on https://github.com/woocommerce/woocommerce/issues/10071

**Comment by leandrotavaresrocha** [comment]
There is any update about this feature?

I am looking for a way to make grouped product get total sales from their child products, even a cronjob would be useful in this situation.

The reason is that without a total sales in a grouped product is impossible to sort these products based on sales. If the child products are hidden, we can have best sellers that will never will appear in widgets that use total sales to rank products.
