### ISSUE TITLE
Function get_woocommerce_currency_numeric

### ISSUE THREAD

**Issue by SubZero5** [woothemes/woocommerce#9863]
There is a function called <i>get_woocommerce_currency_symbol</i> to get the current currency symbol.
My payment gateway requests a currency numeric code number.

US Dollar:USD:<strong>840</strong>
Euro:EUR:<strong>978</strong>
Yen:JPY:<strong>392</strong>

Can you add a function called <i>get_woocommerce_currency_numeric</i>?

**Comment by claudiosmweb** [comment]
Note required for many gateways, so better you do it in your payment gateway, don't need to have some function for it on WooCommerce core.
