### ISSUE TITLE
Import WooCommerce localization strings for Cymraeg/Welsh (cy) into main GlotPress

### ISSUE THREAD

**Issue by carlmorris** [woothemes/woocommerce#9864]
Can somebody please import the content of these po files into the main GlotPress project for WooCommerce?

They were generated from my local install of GlotPress. I can't see an easy way of doing a GlotPress import as an ordinary user - and I don't think a Github pull request is appropriate either.

[WooCommerce po file for main plugin](http://nativehq.com/wordpressibawb/woocommerce/woocommerce-cy.po)

[WooCommerce po file for admin strings](http://nativehq.com/wordpressibawb/woocommerce/woocommerce-admin-cy.po)

They should be good up to 2.2.6. Once they're added we can switch to working on the GlotPress!

Diolch / Thanks

Carl

**Comment by claudiosmweb** [comment]
We don't have access for it.
Need to request in https://make.wordpress.org/polyglots/
