### ISSUE TITLE
Coupon discount calculation

### ISSUE THREAD

**Issue by vlapo** [woothemes/woocommerce#9870]
Hi, 

I have same problem as in https://github.com/woothemes/woocommerce/issues/8558. I have 2 coupons to product 100% discount. I have one product (quantity 2) in cart and apply coupons:

There is cart calculation:
```
CART SUBTOTAL	     28,00
--------------------------
COUPON1         	-14,00
COUPON2          	 -7,00
==========================
TOTAL                 7,00
```

Expected behavior:
Total would be 0.

WC version 2.4.10

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/kn1mrt6s3lfkrhe/2015-12-17%20at%2013.01.png?dl=0

**Comment by vlapo** [comment]
Great @mikejolley, thnx for fast investigation ;)

After more digging I find I have ```Calculate coupon discounts sequentially``` checked in settings. But I think it is still wrong behavior.

From description ```When applying multiple coupons, apply the first coupon to the full price and the second coupon to the discounted price and so on.``` So, I think wc has to apply second coupon to discounted price (in my example case 14,00) and create discount -14,00.

**Comment by vlapo** [comment]
@mikejolley, what do you think about it ??

**Comment by mikejolley** [comment]
Not sure what you mean - I just tried replicating your example and didn't get the same calc.

**Comment by vlapo** [comment]
Hi, 

I made fresh install of woocommerce. There are screenshots from my checkout settings, coupon setup and cart.
https://www.dropbox.com/sh/wdoqgce7eeydpt8/AAACP3T0BDG2WLokNZOBEEKUa?dl=0

Maybe I dont understand ```Calculate coupon discounts sequentially``` setting.

**Comment by reigelgallarde** [comment]
@vlapo  I've tried your settings and it works on my install.

http://i.imgur.com/Kg85WgG.png

**Comment by vlapo** [comment]
@reigelgallarde please increase quantity to 2.

**Comment by reigelgallarde** [comment]
@vlapo I'm not sure why you are having this problem..

I've tried 2,3, even 4. It works perfectly...

http://i.imgur.com/pGVGmJz.png

**Comment by vlapo** [comment]
@reigelgallarde. Did you see my dropbox link ?? You dont have exactly my settings. So again:

coupon setting:
![coupon_setup1](https://cloud.githubusercontent.com/assets/2484063/12032409/59ea4a46-ae18-11e5-8b60-f7ca66260967.png)
![coupon_setup2](https://cloud.githubusercontent.com/assets/2484063/12032410/5bec9ce0-ae18-11e5-8b5e-3850767ea095.png)
![coupon_setup3](https://cloud.githubusercontent.com/assets/2484063/12032403/4219e052-ae18-11e5-87b2-6445de2fcc59.png)

Checkout settings:
![setting_checkout](https://cloud.githubusercontent.com/assets/2484063/12032422/7da5e0b2-ae18-11e5-853e-15bc415886ab.png)

My cart:
![cart](https://cloud.githubusercontent.com/assets/2484063/12032424/828347fa-ae18-11e5-9d3f-b13f59f18e5c.png)

**Comment by reigelgallarde** [comment]
@vlapo ahh yes.. I got your problem now... sorry I make I mistake earlier, mine uses cart % discount.

using product % discount, it shows your screenshot as result.

@mikejolley I have replicated his problem. it seems there's an error in the calculation. I'm using version 2.4.12

I might dig into this later.

**Comment by vlapo** [comment]
@reigelgallarde Thnx a lot. I've already started to think I'm crazy. :)

**Comment by mikejolley** [comment]
"Calculate coupon discounts sequentially" (the legacy option) would do this. It's only there for backwards compatibility and is off by default. 

If you select "Calculate coupon discounts sequentially" think of WooCommerce applying coupons one at a time.

So coupon #1 is applied to the line item, but for 1 qty. Thats $14. $14 is left.

At this point, the line is still $14, but there are 2 items. So item price is now $7.

Next coupon is applied, same deal, 1 qty. This time it thinks its $7. $7 is left.

Turn the option off if you don't want this kind of logic.

**Comment by vlapo** [comment]
What do you mean 
> At this point, the line is still $14, but there are 2 items. So item price is now $7.

I think this is wrong behavior because item price of product is $14 ... not $7! 

I am really sorry but this "workaround" is unacceptable for me.

The reason why I have this setting turn on is this:

1) Create variable product with attribute color and values e.g. red, green, blue
2) Create two coupons to 100% of product with restriction to variable product (not variation but to product! - this is important)
3) Add to cart one red, one green product
4) Apply coupons and there is it.

```Calculate coupon discounts sequentially``` **disabled** - wrong behavior:
![image](https://cloud.githubusercontent.com/assets/2484063/12034433/3f011e4e-ae31-11e5-9568-69fb1a76fa99.png)

```Calculate coupon discounts sequentially``` **enabled** - good behavior:
![image](https://cloud.githubusercontent.com/assets/2484063/12034444/58daa51a-ae31-11e5-88dd-5f437f645ff6.png)

**Comment by mikejolley** [comment]
@vlapo the backstory is here https://github.com/woothemes/woocommerce/issues/5874 It's not really a case of it being acceptable to you or not - the fact is, the "sequentially" option cannot handle what you are asking which is why it was deprecated and replaced with the new coupon handling. Disable it.

> Create two coupons to 100% of product with restriction to variable product (not variation but to product! - this is important)

Then this is a separate bug which should be addressed.

**Comment by vlapo** [comment]
Okey. I understand now. Thanks for explanation. 
Should I create new issue about variable product coupon calculation?

**Comment by mikejolley** [comment]
I'm looking at it now.

**Comment by vlapo** [comment]
Looks greate :) @mikejolley You made my day.
