### ISSUE TITLE
Category filter in /products doesn't work (v3 REST API)

### ISSUE THREAD

**Issue by dimitrovskif** [woothemes/woocommerce#9871]
The WooCommerce REST API Documentation [specifies the `category` query param](https://woothemes.github.io/woocommerce-rest-api-docs/#view-list-of-products) when doing a `GET /wc-api/v3/products`. 

I am using latest WooCommerce & WordPress, and that parameter doesn't change the response at all. In fact, all products are returned - it doesn't matter if I pass the category query parameter.

The request that I am talking about is:

    GET https://mydomain.com/wc-api/v3/products?category=brus

I also tried: (where 5 is the id of the same category)

    GET https://mydomain.com/wc-api/v3/products?category=5

**Comment by claudiosmweb** [comment]
Missing read better the docs... https://woothemes.github.io/woocommerce-rest-api-docs/#parameters

**Comment by dhenniga** [comment]
That link seems to be gone now.  I can't find documentation for this anywhere.  Any help would be great.

**Comment by dipeshparashar** [comment]
Just resolved similar issue. Use slug instead of id / name . It will work.
Here
` https://yourwebsite.com/api/user/proxy/products/?filter[category]=<SLUG OF CATAGORY`

**Comment by heemu9** [comment]
It is not working for me.  

However http://demotwo.technitab.net/wp-json/wc/v2/products/category=20 is working for me but when I am trying to run the URL in Postman it is working fine, but if i am trying to integrate same url in Android code it is not working.

Please help I am, trying to solve this error from one week

**Comment by juliomiy** [comment]
woocommerce api is great but documentation is pitiful , incomplete and often wrong

**Comment by claudiosanches** [comment]
@juliomiy we have a complete documentation for all REST API versions, maybe you are looking for the documentation for different version of the REST API.

**Comment by smtech12** [comment]
@claudiosanches i am using v3 for getting products from woocommerce but the issue it's only showing 10 products which is default how to get all products ? because filter[limit] is not available in v3 then how to get all products on this wc-api/v3/products 
waiting for your kind help ..
Thanks

**Comment by claudiosanches** [comment]
@smtech12 there is how to do it on the documentation.
