### ISSUE TITLE
After update, login / register / cart return empty forms / empty page

### ISSUE THREAD

**Issue by chromafunk** [woothemes/woocommerce#9873]
This was working fine but now woocommerce is giving problems with the latest version of wordpress / woocommerce. When I register or login through /my-account/ or login at checkout, the my account page with user popuplated data doesn't come up. It just remains empty. The user is logged in, but nothing changes. It also happens with register : you can register a user, the backend registers it properly on database but it does not login the user and you can't see any user data.

You can check this here : https://elsitar.com at the login area. 

Thanks

**Comment by mikejolley** [comment]
Locally I'm not seeing this issue, this means you're looking at either:

- Host or plugin level caching
- A conflict with a theme or plugin
- Possibly something to do with your SSL/https config

Look into the above. I've tested this locally as I said without seeing the same issue so its not something reproducible my side.
