### ISSUE TITLE
[2.5] PHP Fatal error: Call to a member function get_tax_status() 

### ISSUE THREAD

**Issue by mikylucky** [woothemes/woocommerce#9874]
Hi,
I'm using WooCommerce 2.5 Beta3 and I found this error

>PHP Fatal error:  Call to a member function get_tax_status() on boolean in /var/www/mysite.com/wp-content/plugins/woocommerce/includes/class-wc-product-variation.php on line 397

The error occurs when I call the product API with the filter[sku] applied. Same procedure was working with the stable version of Woocommerce.

My script looks if there is a product with a specific sku, and in this case there is not.

The error is present in Beta1 too with this message

>PHP Fatal error:  Call to a member function get_tax_status() on boolean in /var/www/mysite.com/wp-content/plugins/woocommerce-2.5.0-beta-1/includes/class-wc-product-variation.php on line 386

**Comment by mikylucky** [comment]
SOLVED: I made a cleanup of the products before, but it not succeded. Is working in a fresh installation

**Comment by mikejolley** [comment]
Variation had no parent I suspect.

**Comment by mikylucky** [comment]
@mikejolley indeed!
