### ISSUE TITLE
V3 API via HTTPS will not connect on staging enviroment

### ISSUE THREAD

**Issue by Codecomp** [woothemes/woocommerce#9878]
I have a shop siting on a live server with SSL installed and the API is working fine. The development site that sits on another near identical server with the same API keys is having issues.

The development environment has a wildcard SSL installed and im able to access the API but my authentication fails every time. I get the flowing response with old and newly generated Keys. This happens when trying to connect via the browser or via cURL direct from the server.

{"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer Secret is invalid"}]}

**Comment by mikejolley** [comment]
SSL should make no difference in this case - the error message is "Consumer Secret is invalid" - that means the hash check is failing. 

https://github.com/woothemes/woocommerce/blob/89d177a48b25337883119cb3cbf44855af89cb54/includes/api/class-wc-api-authentication.php#L82

https://github.com/woothemes/woocommerce/blob/89d177a48b25337883119cb3cbf44855af89cb54/includes/api/class-wc-api-authentication.php#L213

https://woothemes.github.io/woocommerce-rest-api-docs/#errors

Make a new set of keys on the sandbox and try those. cc @claudiosmweb
