### ISSUE TITLE
Sort product attributes by name

### ISSUE THREAD

**Issue by jimpalompa** [woothemes/woocommerce#9879]
I have a shop with around 30 different attributes. The larger a shop gets, the more attributes we need. However, WooCommerce only sorts the attributes list by "added date".

`/wp-admin/edit.php?post_type=product&page=product_attributes`

It would be better if the list were ordered by name or if you make them dragable, just like categories.

This also goes for the product data tab:

`/wp-admin/post.php?post=1234&action=edit#product_attributes`

Where you REALLY want them sorted by name/or personal preference. I could only imagine a shop with twice the amount of attributes as I have, and trying to find the right one if they are in a random order, when adding product information.

If the list could be dragable, users could have their most common attributes first, followed by all the others in an alphabetic order. If you don't want to make it dragable, please just order them by name at least.

**Comment by mikejolley** [comment]
Edit the attribute - you can already set the sort order... There is a drop down setting.

**Comment by jimpalompa** [comment]
I don't mean the terms list, I mean the parent Attribute list

`/wp-admin/edit.php?post_type=product&page=product_attributes`

`/wp-admin/post.php?post=1234&action=edit#product_attributes`

**Comment by mikejolley** [comment]
Attributes can also be re-ordered at product level..

**Comment by jimpalompa** [comment]
This is the list I am referring to...

![Image of attributes](https://i1.wp.com/docs.woothemes.com/wp-content/uploads/2013/05/WooCommerce-Attributes.png)

The screenshot shows three different Attributes:
1. **Color**
2. **Level**
3. **Size**

Let's say I add another Attribute to the list: **Fabric**

It would look like this:
1. **Color**
2. **Level**
3. **Size**
4. **Fabric**

Are you saying there is a way to have **Fabric** appear right after **Color** (2.)?

This also goes for the dropdown as shown here:

![Image of attribute dropdown](https://docs.woothemes.com/wp-content/uploads/2013/05/Adding-Custom-Attributes-to-WooCommerce.png)

This example only shows 4 different attributes, but you can imagine what happens if you have 50-100 different attributes...

I'm just saying that it would make more sense retrieving the list "by name" instead of scrolling down to the last entry of the list, even though the attribute may begin with the letter A.

**Comment by mikejolley** [comment]
I'm saying once you add the attribute to your product, you can drag and drop to sort them. The display I guess could be alphabetical though - I shall patch that, but it won't be customisable.

**Comment by jimpalompa** [comment]
I understood what you meant, you just misunderstood what I was referring to ;)

Alphabetical is good enough, at least they are sorted by something that makes sense, instead of date.

Does your commit also change the order in the dropdown list on product data tab?

**Comment by mikejolley** [comment]
Should affect all listings of attributes.

**Comment by renrax** [comment]
This is also a big problem for Russian-speaking users. Sorting by name is different from sorting by slug. Read more here:
https://wordpress.org/support/topic/sort-list-of-attributes-by-alphabetical-order-of-the-default-site-language/
That's why sorting by name is needed.
