### ISSUE TITLE
Adding attributes via Quick/Bulk edit, doesn't affect attributes tab.

### ISSUE THREAD

**Issue by dimitrov-adrian** [woothemes/woocommerce#9882]
When adding attributes from quick or bulk edit, that are not yet added on a product, doesn't update attributes on product edit screen and product view page, but actually they are added so layer filter are works fine.

Seems that '_product_attributes' meta value is not updated.

It is a little bit tricky as it's not really clear what action should be taken in this case about attribute visibility. I think they should be visible by default, but someone could not want this. May be checkbox about the action will be good idea.

Also one button in wp-admin/admin.php?page=wc-status&tab=tools to do fix over the _product_attributes from the actual taxonomy terms could be useful in some cases.

WP 4.4
WC 2.4.12

**Comment by mikejolley** [comment]
I don't think these used to be available via quick-edit. They shouldn't be visible and will need hiding until correct logic is in place to set the meta. cc @claudiosmweb

**Comment by claudiosmweb** [comment]
@mikejolley Symptom of 78f3d8a6cbad332621546334714c454115a5ee5f
