### ISSUE TITLE
Incompatible with system running WP 4.4, mySQL 5.6, and PHP 5.6?

### ISSUE THREAD

**Issue by thinman** [woothemes/woocommerce#9883]
It appears that WC is incompatible with a system running WP 4.4, MySQL5.6.27, and PHP 5.6.16.

When entering a product, it adds _regular_price to the posts meta table, but *not* _price, and therefore triggers sale but, with no sale price defined, no price shows, and there's no add to cart button.

**Comment by claudiosmweb** [comment]
Nop, works great with WP 4.4 MySQL 5.6 and PHP 5.6.
