### ISSUE TITLE
Orders no view

### ISSUE THREAD

**Issue by BGWebDevelopment** [woothemes/woocommerce#9885]
Hi,
In my woocommerce seems that i haven´t got any order, nothing display in the orders page or reports page
![captura de pantalla 2015-12-21 00 42 39-recortada](https://cloud.githubusercontent.com/assets/5717454/11920931/fb2d4f46-a77b-11e5-9683-6c01c2592869.png)

**Comment by reigelgallarde** [comment]
we need more information about this. It's hard to tell what's the problem with just a screenshot.

**Comment by BGWebDevelopment** [comment]
If u want i can create a user for u

**Comment by claudiosmweb** [comment]
@BGWebDevelopment NO ONE WILL ACCESS OR YOUR SITE OR NEED AN USER ACCOUNT!

This seems to be a plugin conflict.
Check your plugins before reporting anything.

Tested and works great the order screen in WooCommerce 2.4.12 and WordPress 4.4.

**Comment by BGWebDevelopment** [comment]
Hi,
I´d try deactivating all plugins before create this issue. I dont know how could i make u help me.

All the best,

**Comment by mikejolley** [comment]
If this were a core bug, more users would be reporting it. Check the above (conflicts).
