### ISSUE TITLE
Rename variation admin custom fields action tags

### ISSUE THREAD

**Issue by tamarazuk** [woothemes/woocommerce#9886]
Ran into an issue while updating Measurement Price Calculator for WC2.5 compatibility. Some of the actions added in SHA 7c05671188df1c32f00b2a05eda0ab34a74136e6 share the same tag as actions used in other product data tabs. For example, `woocommerce_product_options_dimensions` is used [here](https://github.com/woothemes/woocommerce/blob/4b87b0fbdc2082c3fe889613c6fa6be166fee80d/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L383) for the Shipping tab and now [here](https://github.com/woothemes/woocommerce/blob/887d37583c000153012bace1e0b6d1266e37afd8/includes/admin/meta-boxes/views/html-variation-admin.php#L202) for the variation shipping section. 

To make it a bit easier to differentiate these, I would suggest renaming the variation action tag to something like `woocommerce_variation_options_dimensions`.

**Comment by claudiosmweb** [comment]
Sorry, my bad.
Seems like I failed in copy/paste xD

**Comment by tamarazuk** [comment]
@claudiosmweb thanks so much for the prompt fix! :beers:
