### ISSUE TITLE
Signature invalide - la méthode de signature est invalide Woocomerce Rest API

### ISSUE THREAD

**Issue by hatim-haffane** [woothemes/woocommerce#9887]
Hello ,

i'm trying to make a oauth authentication to my woocomerce using ionic platforme (angularjs) but i get this error : 

code: "woocommerce_api_authentication_error",
message: "Signature invalide - la méthode de signature est invalide"

here is my code : 

var oauthObject = {
    oauth_consumer_key: OAUTH_CONSUMER_KEY,
    oauth_timestamp: Math.round((new Date()).getTime() / 1000.0),
    oauth_nonce: $cordovaOauthUtility.createNonce(10),
    oauth_signature_method: "HMAC-SHA1",
    oauth_version: "1.0a"
  };
  
  var signatureObj = $cordovaOauthUtility.createSignature("GET", ApiEndpoint, oauthObject,  { oauth_callback: "http://localhost/callback" }, CLIENT_SECRET);
  console.log('##################### signatureObj ######################### //  '+signatureObj);
  this.getAllCategories = function(categoryId) {
    var deferred = $q.defer();
     $http({
        url: ApiEndpoint + 'products/categories' + '?id=' + categoryId,
        method: "GET",
        cache: true,
        params: {oauth_consumer_key: OAUTH_CONSUMER_KEY,oauth_timestamp: Math.round((new Date()).getTime() / 1000.0),oauth_nonce: $cordovaOauthUtility.createNonce(10),oauth_signature:signatureObj.signature,oauth_signature_method:'1.0'}
      //params: {oauth_consumer_key: OAUTH_CONSUMER_KEY,oauth_timestamp: Math.round((new Date()).getTime() / 1000.0),oauth_nonce: $cordovaOauthUtility.createNonce(10),oauth_signature:signatureObj.signature,oauth_signature_method:'1.0'}
     })
    .success(function(data) {
      deferred.resolve(data);
    })
    .error(function(data) {
      deferred.reject(data);
    });

    return deferred.promise;
  };

MErci

**Comment by claudiosmweb** [comment]
Because you are generating a wrong oAuth 1.0a signature.

http://woothemes.github.io/woocommerce-rest-api-docs/#authentication
