### ISSUE TITLE
"Set regular prices" on variations skips over some variations

### ISSUE THREAD

**Issue by technifreak** [woothemes/woocommerce#9888]
I have a product with 48 variations and I went to update the prices, using the dropdown menu to "Set regular prices" for the variations. It skipped the whole first page and only did 38 price updates. That meant I had to manually enter 15 prices on those variations. I'm going to have to do this on 42 products. Very time consuming.

**Comment by claudiosmweb** [comment]
Just tested with WooCommerce 2.4.12 and WordPress 4.4... Works fine.

**Comment by technifreak** [comment]
I increased the memory limit on my WP config file and that appears to have fixed it. Thanks for looking into it.

**Comment by claudiosmweb** [comment]
If you have errors like that you can use: https://codex.wordpress.org/Debugging_in_WordPress
Make easier to see what is happens wrong.
