### ISSUE TITLE
Adding product attributes programatically

### ISSUE THREAD

**Issue by raicabogdan** [woothemes/woocommerce#9889]
Hello,

Is there an example on how to add attributes from within code / programatically ?

I tried searching for this but I couldn't find and some examples found on the internet appear to not work as expected / not being linked to products.

example code I use:
````
$_product_attributes[color] = array(
		    'name' => "Color",
		    'value' => 'Red',
		    'position' => 0,
		    'is_visible' => 1,
		    'is_variation' => 0,
		    'is_taxonomy' => 1
		);
update_post_meta($post_id, '_product_attributes', $_product_attributes);
```
Thank you.

**Comment by claudiosmweb** [comment]
Check or API files for examples.

But please, not that this repository is not suitable for support.
Please don't use our issue tracker for support requests, but for core WooCommerce issues only.

Support can take place in the appropriate channels:

* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.
* [Our community forum on wp.org](https://wordpress.org/support/plugin/woocommerce) which is available for all WooCommerce users.

Or check our documentation:

* [WooCommerce Documentation](http://docs.woothemes.com/documentation/plugins/woocommerce/)
* [WooCommerce Knowledge Base](https://support.woothemes.com/hc/en-us/categories/200146917-WooCommerce)
* [WooCommerce Code Reference](http://docs.woothemes.com/wc-apidocs/)
* [WooCommerce REST API Docs](http://woothemes.github.io/woocommerce-rest-api-docs/)

**Comment by ZararAnsari** [comment]
foreach ($review['options'] as $options) {
        $product_options_name = $options['name'];
//attribute
        foreach ($options['product_option_value'] as $key2) {
            $options_values = $key2['name'];
            $product_attributes['type'] = array(
                //Make sure the 'name' is same as you have the attribute
                'name' => htmlspeialchars(stripslashes($product_options_name)),
                'value' =>  $options_values,
                'position' => 1,
                'is_visible' => 1,
                'is_variation' => 1,
                'is_taxonomy' => 0
            );        
        }
        //Add as post meta
        update_post_meta($new_post_id, '_product_attributes', $product_attributes);  
//variations
        }    
Result : Size : Small
