### ISSUE TITLE
Free shipping coupon at checkout not auto-selecting free shipping method

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#9895]
If Free Shipping has the lowest priority level, then upon entering a free shipping coupon in the cart, free shipping will be chosen: http://cld.wthms.co/1jcEI/3NyrekoY

But if you try the above again, except entering the coupon at checkout, free shipping will not be chosen by default: http://cld.wthms.co/178tK/2FBVjOge

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/issues/9552
