### ISSUE TITLE
write permissions for create order

### ISSUE THREAD

**Issue by uriel-frankel** [woothemes/woocommerce#9897]
Hi

I am developing an Android store app that its backend is woocommerce. I want the user to be able to create order and view products. The problem is that if someone will decompile the android APK, he can find the keys, and then he can, literally, wipe out all of store data. Can I limit a key to write only for orders? Is is something out of the box?
thank you
Uriel

**Comment by claudiosmweb** [comment]
Just with you install plugins to have more control on it.
