### ISSUE TITLE
Introduce log file size limitation and rotation

### ISSUE THREAD

**Issue by javorszky** [woothemes/woocommerce#9898]
On some sites the log files can grow quite substantial (I'm currently FTPing a paypal one that's 154 MB). That means a visit to System Status -> Logs will either not show the log file, or take ages to download the entire file. Additionally some processes that write to them can become slow due to PHP needing to open the entire file, write to the end, close it, often a lot of times in succession.

I propose a log file rotation. Once a file hits a filterable upper limit (5 MB for example), a new one can be started, and the previous archived (datetime added to file name) and moved to an archive folder.

**Comment by maxrice** [comment]
:+1: maybe an interim solution here might be simply reading in the first few MB when viewing the log under System Status, instead of loading the entire file.

**Comment by claudiosmweb** [comment]
Not really only "Introduce log file size limitation"... Need to have a log rotation.

**Comment by claudiosmweb** [comment]
Closed in favor of #10468
