### ISSUE TITLE
Incompitable with performance testing tool 

### ISSUE THREAD

**Issue by iam404** [woothemes/woocommerce#9899]
Hi,

While doing performance testing on my woocommerce store using jmeter scipt.  I am facing an issue that when ever my script goes to `/checkout` page, order value on cart goes to `null` . 

HTTP Cookie and session are handled on the jmeter script .

Is there a way to initiate a performance/load testing on a WooCommerce store ?

**Comment by mikejolley** [comment]
Have you confirmed that each simulated user of your testing tool has a unique session, and that cookies are really handled? Why not trying having them register or login (something non-woocommerce) so you can ensure each user is handled independently?

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-session-handler.php#L118-L126

**Comment by pmgarman** [comment]
While it's not something I can share, we do our load testing on WooCommerce using jmeter scripts and have done it a number of times succesfully. So I can confirm that it's not a WooCommerce issue here and likely in your jmeter script.

**Comment by mikejolley** [comment]
Thanks Patrick :+1:
