### ISSUE TITLE
[API] Manually added orders aren't marked as paid

### ISSUE THREAD

**Issue by Ramblurr** [woothemes/woocommerce#9900]
When you manually add an order via the Add order button on the orders CPT, and then mark it as completed, the `payment_details.paid property` is still `false`"

I'd expect it to be true.

**Comment by mikejolley** [comment]
Only if payment details are present, which if you're not setting via the API won't be. https://woothemes.github.io/woocommerce-rest-api-docs/#orders-properties

**Comment by Ramblurr** [comment]
@mikejolley Thanks for the info. A follow up question:

If a Shop Manager, manually creates an order for a user, via the "Add Order" button in the Order CPT. Then the user pays via Check or some other out-of-band method, what can the Manager do to make the `payment_details.paid` property be set to `true`?

I'm using the (amazingly awesome) API to create important reports, and this `paid` property is very important.

**Comment by mikejolley** [comment]
@claudiosmweb ^

**Comment by claudiosmweb** [comment]
Here an example of a paid order: https://woothemes.github.io/woocommerce-rest-api-docs/#create-an-order

**Comment by Ramblurr** [comment]
Thanks @claudiosmweb , but this doesn't answer my question..
Here is an illustrated example of what I mean.

1. Add an order manually via 
<img width="177" alt="orders_ _alliance_for_coffee_excellence_ _wordpress" src="https://cloud.githubusercontent.com/assets/14830/12252733/b5f4d902-b88e-11e5-8bb1-c92e8a7a4745.png">
2. Mark the order as completed 
<img width="109" alt="edit_order_ _alliance_for_coffee_excellence_ _wordpress" src="https://cloud.githubusercontent.com/assets/14830/12252745/cb07ae6e-b88e-11e5-9421-5d8260450424.png">
3. Edit billing details add choose a method 
<img width="125" alt="edit_order_ _alliance_for_coffee_excellence_ _wordpress" src="https://cloud.githubusercontent.com/assets/14830/12252772/064c8990-b88f-11e5-882f-fa7c1f4ee4db.png">
4. Add line items,
5. Save the order
6. Note the order is marked as paid in the admin section: 
<img width="315" alt="edit_order_ _alliance_for_coffee_excellence_ _wordpress" src="https://cloud.githubusercontent.com/assets/14830/12252784/1fc5e81c-b88f-11e5-99bc-70a41b9c0c7d.png">

Now fire up your favorite API client:

7. Request orders: `https://SITE.com/wc-api/v3/orders/ORDERID`
8. Note the `payment_details.paid` property is `false`

<img width="149" alt="reports_ _alliance_for_coffee_excellence_ _wordpress" src="https://cloud.githubusercontent.com/assets/14830/12252824/7858eec0-b88f-11e5-990e-0fe4ec9b9499.png">


Summary: The API always returns `payment_details.paid` as false for *manually added orders*. 

@mikejolley  indicated this might be intentional.

But my question remains: **How can I determine if a manually added order is paid with the API?**

**Comment by claudiosmweb** [comment]
@Ramblurr 

> Summary: The API always returns payment_details.paid as false for manually added orders. 

Not true, nothing wrong with the API, actually no manual order is saved as paid. This is expected behavior since need a payment gateway to mark as paid.

> How can I determine if a manually added order is paid with the API?

You can determine it reading the order status.

**Comment by Ramblurr** [comment]
Ok thanks! I didn't realize that the `paid` property was only set by the merchant gateways.
