### ISSUE TITLE
Product Webhooks not firing for bulk editing or quick editing

### ISSUE THREAD

**Issue by nevernotsean** [woothemes/woocommerce#9905]
When bulk updating products, product webhooks aren't triggered.

**Comment by claudiosmweb** [comment]
For now you can create custom triggers for `woocommerce_product_quick_edit_save` and `woocommerce_product_bulk_edit_save`.

**Comment by rfmeier** [comment]
@claudiosan I tried adding those filters in the past.  However, a WC_Product object is passed as a parameter for `woocommerce_product_quick_edit_save` and `woocommerce_product_bulk_edit_save` which causes an error within `WC_Webhook::build_payload()`.

There error from the webhook logs is `{"errors":{"woocommerce_api_invalid_product_id":["Invalid product ID"]},"error_data":{"woocommerce_api_invalid_product_id":{"status":404}}}`

The other callbacks within `WC_Webhook:: get_topic_hooks()` https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-webhook.php#L532 pass product IDs as their parameter.

Either an integer needs to somehow be passed from `woocommerce_product_quick_edit_save` and `woocommerce_product_bulk_edit_save` or `WC_Webhook::build_payload()` needs to be able to accept objects as a parameter and know what to do with it.

I am willing to help patch this if needed.

**Comment by claudiosmweb** [comment]
@rfmeier Nice! It's not for me. Good luck waiting for him to answer :)

**Comment by claudiosan** [comment]
@claudiosmweb and he is not the first one! 
at least they keep me informed ;)

**Comment by rfmeier** [comment]
Autocomplete for the win.  Sorry, @claudiosan ;)

**Comment by claudiosmweb** [comment]
@rfmeier and you have not understood what I said.

**Comment by rfmeier** [comment]
Then I will let it be.
