### ISSUE TITLE
Incorrect running form select shipping

### ISSUE THREAD

**Issue by sunshineart** [woothemes/woocommerce#9908]
When section, select the delivery cart and go to the checkout page, the price dropped and not stored. ie the buyer will have to do twice obscure operation which greatly rastroilas buyer and can cause problems!

to try and see there is a test product. http://sunshineart.ru/tovar/test/

Here's the address basket http://sunshineart.ru/korzina/
Note. when to go to the basket design orders shipping price is not stored!

 please help solve the problem! Thank you!

**Comment by mikejolley** [comment]
There are settings to hide shipping before addresses are entered which might be used here (wp-admin/admin.php?page=wc-settings&tab=shipping) however it does look like customisation in your theme removing those shipping costs from the cart page. Certainly not a core reproducible bug, and nothing that has been reported anywhere else.
