### ISSUE TITLE
Add transaction_url param for payment_complete method

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/woocommerce#9909]
Sometime transaction ID is not what I need to grab and index in `get_transaction_url()` method query args. So I have to save meta and grab the invoice url which is obviously time consuming. If there will be the param support for transaction URL in `payment_complete()` method it will be obviously useful for 3rd party gateways ;)
https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L2348-L2396

**Comment by mikejolley** [comment]
All gateways have an 'id' of sorts to reference a payment. Your gateway can take care of the link via it's own method. This shouldn't support a URL directly.
