### ISSUE TITLE
Woocommerce URL Permalink changed

### ISSUE THREAD

**Issue by deepankarpathak** [woothemes/woocommerce#9910]
Our Woocommerce website is working on url format (1) which is changed to (2) after woocommerce (2.3.5 to 2.4.12) and wordpress (4.1.1 to 4.4) update. 
1. abc.com/parent-category/child-category/product-name 
2. abc.com/cart-page/child-category/product-name
3. abc.com/parent-category/child-category/sub-child-category/product-name

Any changes in code or any permalink hack for changing it to (3)?

**Comment by claudiosmweb** [comment]
We have not changed the structure of any permalink.
