### ISSUE TITLE
"cart" was changed to "basket" site-wide

### ISSUE THREAD

**Issue by Mario-M** [woothemes/woocommerce#9914]
Not which when this happened but I just updated wooCommerce and now every button and text that previously read "cart" has been replaced with "basket" as if I'm living in the UK (which I'm not).

**Comment by mikejolley** [comment]
Check the translation file for whatever locale you're using (settings > General). You'll likely be using en-GB https://translate.wordpress.org/projects/wp-plugins/woocommerce
