### ISSUE TITLE
Woocommerce remove item from cart

### ISSUE THREAD

**Issue by JakWalker** [woothemes/woocommerce#9915]
There appears to be an issue removing items from carts when using woocomerce together with storefront. Sometimes it removes ok but then it doesnt remove at all, and sometimes after it looks like its been removed it will then show back up! 
When using other themes it works perfectly everytime.

**Comment by mikejolley** [comment]
Latest version? Sure its not cache? Not aware of any storefront issues with the cart page. Certainly not occurring for me.

**Comment by JakWalker** [comment]
Hi mike thank you for your reply, it doesn't appear to be cache as I've cleared that. I forgot to mention it only appears to not remove from mobile version for some reason?

**Comment by mikejolley** [comment]
> I forgot to mention it only appears to not remove from mobile version for some reason?

Then its likely cache rules ;) w3 total cache etc have special rules for mobile devices. Exclude your cart page.

**Comment by mikejolley** [comment]
https://docs.woothemes.com/document/configuring-caching-plugins/
