### ISSUE TITLE
View List Of Products only returns 6 out of 23 products 

### ISSUE THREAD

**Issue by Jhs458** [woothemes/woocommerce#9916]
When I GET call the list of all products from  my WooCommerce site it only returns 6 out of the 23 products that are listed. Below are my calls:

Using node with express and mongoDB

var WooCommerce = new WooCommerceAPI({
  url: 'http://coffeeworks.com',
  consumerKey: 'myKey',
  consumerSecret: 'mySecret'
});

router.get('/products', function(req, next) {
  WooCommerce.get('products', function(err, data, res) {
    var coffeeString = JSON.parse(data.body);
    console.log(coffeeString);
  });
});

This code returns the first 6 products to my terminal, but if I use the product count it shows 23 products, which is how many I have in my WooCommerce terminal.

router.get('/products', function(req, next) {
  WooCommerce.get('products/count', function(err, data, res) {
    console.log(data.body);
  });
});

returns:
{"count":23}

Been working on this issue for a few days, and haven't had any success getting more than the first 6 products. 

Thanks for the help!

**Comment by claudiosmweb** [comment]
Please read the docs before open issues: http://woothemes.github.io/woocommerce-rest-api-docs/

Especially this part: http://woothemes.github.io/woocommerce-rest-api-docs/#pagination

> Requests that return multiple items will be paginated to 10 items by default. This default can be changed by the site administrator by changing the `posts_per_page` option. Alternatively the items per page can be specifed with the `?filter[limit]` parameter:

I bet a horse with you that on your site is limited to 6 posts per page.
