### ISSUE TITLE
"cart" was changed to "basket" site-wide

### ISSUE THREAD

**Issue by Mario-M** [woothemes/woocommerce#9918]
Looks like my previous issue was closed pre-maturely.

After a WooCommerce update, every "add to cart" instance was changed to "add to basket".

As directed in the previous issue, I double checked my language settings in WordPress, and they are indeed correct (Canadian). So I went on a limb and changed it to English United States and low and behold, "add to basket" was changed back to "add to cart".

It looks like WooCommerce is associating the Canadian English language with the UK English language. In Canada, we certainly don't use the term "basket" in the context of shopping like they do in the UK.

In the interim I'll be using the United Stated language until this can be addressed. Any Canadian sites affected by this change should be made aware of this issue and how to temporarily fix it.

**Comment by tjuris** [comment]
This is a choice made by the person or team translating WooCommerce to Canadian English, done here (this is a search for "add to cart"): https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/en-ca/default?filters%5Bterm%5D=add+to+cart&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

Via the "details" toggle there you can either propose a better translation or try to contact the author who made this particular change.

**Comment by mikejolley** [comment]
^ this. Don't re-post the same thing multiple times - it was closed (not a bug) for a reason.

**Comment by Mario-M** [comment]
@mikejolley Your response was insufficient - and to point out, it does not have to be a "bug" to be considered an issue. FYI - This is why github does not label issues as "bugs".
But at any rate, I wasn't aware you could reply to a closed issue. So won't happen again.

@tjuris That's awesome information and is addresses this issue perfectly. Thanks so much, I'll take further action elsewhere.
