### ISSUE TITLE
Error in refund mail

### ISSUE THREAD

**Issue by yarivkohn** [woothemes/woocommerce#9920]
When a refund is being made, the shopper receive an email.
The email state that the order was partially refunded even when it is actually fully refunded.

**Comment by mikejolley** [comment]
You need to refund the item qty's too for a 'full' refund. 2.5 will resolve this.

**Comment by yarivkohn** [comment]
Tnx.
BTW, is it possible to join the woocomerce community and maybe help with
bug resolve?
