### ISSUE TITLE
Fatal error on order factory

### ISSUE THREAD

**Issue by moise** [woothemes/woocommerce#9923]
I had this error:
Fatal error: Call to a member function get_order() on null

The function used is wc_create_order() but the error is made by

function wc_get_order( $the_order = false ) {
	return WC()->order_factory->get_order( $the_order );
}

Edit:
the same error here:
function wc_get_product( $the_product = false, $args = array() ) {
	return WC()->product_factory->get_product( $the_product, $args );
}

any idea?

**Comment by mikejolley** [comment]
Related to your server perhaps? https://github.com/woothemes/woocommerce/issues/9279

**Comment by moise** [comment]
thank you @mikejolley I'll check soon :)

**Comment by mikejolley** [comment]
Nevermind, this will also happen if you call it before 'init'. I will add error handling, but its your code's fault :p
