### ISSUE TITLE
REST API does not return Product custom fields - Product Properties

### ISSUE THREAD

**Issue by drmDev** [woothemes/woocommerce#9925]
We have custom fields added to our products under WooCommerce > Custom Fields > Product Properties. When I do a get request on a product with those properties such as:

r = api.get("products/37")
or r = wcapi.get("products/37?filter[meta]=true")

The JSON returned does not include these custom fields or their values.

How can I retrieve these Product custom fields by the API?

**Comment by claudiosmweb** [comment]
Please, before you open issues, see the documentation: https://woothemes.github.io/woocommerce-rest-api-docs/

We don't intend to display custom fields, if you need it, use the actions and filters that we have in the API code to add new fields: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php

**Comment by drmDev** [comment]
I did read the documentation. I don't see where it states anything about retrieving custom fields values. If you don't support being able to retrieve these custom fields by the API, okay understood. I just want to clarify - are you saying this API can add the WooCommerce Product Properties custom fields but cannot retrieve them? If they can be retrieved, can you let me know what filter or action I should be using on the get request for the product to retrieve them? If it's in the documentation, I apologize, I do not see it.

**Comment by claudiosmweb** [comment]
I'm saying that custom fields are not included in the API... If you have custom fields, you'll need custom logic to add the fields and saved them within the API.

It have filters and actions that can be used for this.
Like for example you can use this filter https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L214 to include your custom fields.

For example:

```php
function my_custom_product_api_response( $product ) {
    $id = $product['product']['id'];

    // Adding your custom field:
    $product['product']['custom_field_name'] = get_post_meta( $id, 'custom_field_name', true );

    return $product;
}

add_filter( 'woocommerce_api_product_response', 'my_custom_product_api_response' );
```

**Comment by izhwei** [comment]
@claudiosanches   All the pages you provided are 404.  Where are the correct pages now?

**Comment by willgorham** [comment]
Docs: http://woocommerce.github.io/woocommerce-rest-api-docs/

The class linked to above is now legacy. Below are resources now in use that might help.
https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php

https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L175

**Comment by asafm7** [comment]
Hi,

I need to show a custom field of a line item (a product) in the result of "List all orders" of the Orders API.

Tried to use the documentation, but with now success.

Any direction?
