### ISSUE TITLE
Product Categories search under menus is broken

### ISSUE THREAD

**Issue by geeklore** [woothemes/woocommerce#9926]
Using WordPress 4.4 and WooCommerce 2.4.12
[Ticket #365830](https://woothemes.zendesk.com/agent/tickets/365830)

Navigate to **Appearance** > **Menus** and select **Product Categories**. Click on the **Search** tab and perform a search. This works. Then select the **View All** tab and then click back to the **Search** tab and perform a search. [It no longer works](http://cld.wthms.co/1eCiL/3s4SonWC).

**Comment by mikejolley** [comment]
Just tested on 4.4 with master and 2.4.12 and was unable to see the issue.

1. View all
2. Search "clothing"
3. View all
4. Clear field and search again for "clothing"

Results (clothing product cat) showed both times, no errors on console.

FYI this is powered by WordPress, not WooCommerce, so not sure if you simply have a plugin conflict here. I'd suggest repeating the test with regular categories to see if the same thing occurs and view the browser error console (in chrome, view > developer tools > javascript console).

**Comment by geeklore** [comment]
Hi @mikejolley I did not give you the proper testing parameter. Sorry about that. It seems to happen with lots of categories. Like enough to create pagination. Please see this video. http://recordit.co/cHBB4oqoiy

I am also going to be filing a second bug. When there are enough categories to create pagination, then nested categories (second and third levels) are show as first level. Maybe related?

**Comment by mikejolley** [comment]
@geeklore can you replicate this with regular posts? As I mentioned, WordPress powers this - not WooCommerce.

**Comment by geeklore** [comment]
@mikejolley Understood. Yes, totally reproducible under regular categories. WordPress bug. Thank you for the feedback!
