### ISSUE TITLE
WooCommerce Cart - Total does not calculate correctly

### ISSUE THREAD

**Issue by Onewinery** [woothemes/woocommerce#9927]
I recently installed WooCommerce on a WP multi vendor site I manage. The plugin works perfectly, but there is one issue. The blue cart does not display the total number of items and the total price. It simply displays the primary order and secondary orders are not added. I've searched around and cannot find a solution.

Reference image: http://tinypic.com/r/2mfzwav/9

In this instance, the blue cart icon should show 2 items for $73. Instead it only shows 1 item for $38.

Any help would be greatly appreciated  - Thanks!

**Comment by mikejolley** [comment]
This would be an issue with the vendor plugin, not WC core (wc core doesn't support multiple carts out of the box).
