### ISSUE TITLE
product management screen uses original image! not thumbnail!

### ISSUE THREAD

**Issue by vedia** [woothemes/woocommerce#9928]
wp-admin/edit.php?post_type=product
On product management screen my images shown too slow. I checked image and I see no thumbnail image is used. It shows original image !!! (I'm using woocommerce 2.4.12)

![ekran resmi 2016-01-02 11 03 06](https://cloud.githubusercontent.com/assets/60007/12073921/df2b0b34-b140-11e5-8384-b4f930b7e5e7.png)

**Comment by mikejolley** [comment]
The class is size-post-thumbnail is there, so its using post-thumbnail size. This is determined by https://codex.wordpress.org/Function_Reference/set_post_thumbnail_size I believe - if you edit the product, thats the same size used in the 'featured image' meta box.
