### ISSUE TITLE
 Add callback API hook to WC_Payment_Gateway class extension?

### ISSUE THREAD

**Issue by Grauen** [woothemes/woocommerce#9929]
I wrote a payment plugin, which should recieve callback to unlock paid items.

`class WC_FooBar_Payment extends WC_Payment_Gateway {
....
add_action('woocommerce_api_'.strtolower(get_class($this)), array($this, 'handle_callback'));
}`
`function handle_callback() {
 // unlock items...
 exit; 
     }`

When I call the api, woocommerce will return:
`https://mydomain.com/wordpress/wc-api/v3/wc_foobar_payment?consumer_key=mykey&consumer_secret=mysecret`

`{"errors":[{"code":"woocommerce_api_no_route","message":"No route was found matching the URL and request method"}]}`

Funny part is: when you are logged in to wordpress as admin you can trigger the callback-function by using the alternative url schema: `https://mydomain.com/wordpress/?wc-api=wc_foobar_payment`

Should I create a new class to process the callback or should this be working, even if the class extends WC_Payment_Gateway?

**Comment by mikejolley** [comment]
> When I call the api, woocommerce will return...

I think this is where you're going wrong. You should be getting the callback URL using:

https://github.com/woothemes/woocommerce/blob/master/woocommerce.php#L406

`
WC()-> api_request_url( 'wc_foobar_payment' );
`

This will be something like https://mydomain.com/wordpress/?wc-api=wc_foobar_payment

I think you may be confusing this payments endpoint with the WC Rest API. They are not the same thing.
