### ISSUE TITLE
Being able to choose more items than what's in stock

### ISSUE THREAD

**Issue by ChangePlaces** [woothemes/woocommerce#9934]
With just e.g. 2 items in stock, the customer can choose a greater number. Shouldn't the limit be set to that of the stock level?

**Comment by reigelgallarde** [comment]
not sure what's your problem, but stock management works as expected.


![image](http://i.imgur.com/4cWr4Sk.png)

**Comment by roykho** [comment]
Check your "Allow Backorders" Setting.  If it is checked, it means you can have more than what your stock allows.

**Comment by ChangePlaces** [comment]
Even when allow backorders is set to 'no', I can still have a quantity greater than what's in stock.

**Comment by roykho** [comment]
Turn all plugins off except WooCommerce and switch to 2015 default WP theme and re-test.

**Comment by ChangePlaces** [comment]
Same problem

**Comment by ChangePlaces** [comment]
Thanks for the suggestion. It turned out to be very troublesome to diagnose... It's the `Woocommerce Poor Guys Swiss Knife` plugin, except to actually find it, I had to wait 2 mins for the cron to kick in that's doing something that's causing the problem!
