### ISSUE TITLE
WC 2.4.12 - WC Report about partial refund problem.

### ISSUE THREAD

**Issue by telilbo** [woothemes/woocommerce#9935]
Hello. I'm Alan.

this is about partial refund with total sales price report problem. 
I just make a new order with bacs payment (product price value is 10,000 Korea Won) . 
and then change order status to complete.
and then you can see WC Report says sale total is 10,000 Korea won.
after then i try to partial refund some price value( ex : 1,000 Korea Won ).
and then go to WC Report Menu. 
but report was not changed, stil show original price value.  ( WC 2.4.12 )

so, i try to debug, and then found it. 

/woocommerce/includes/admin/reports/class-wc-report-sales-by-date.php : 293 Line.
======================================================================
		foreach ( $this->report_data->partial_refunds as $key => $value ) {
			switch ( $value->item_type ) {
				case 'shipping' :
					$this->report_data->total_shipping_tax_refunded += ( $value->total_shipping_tax * -1 );
					$this->report_data->total_shipping_refunded     += wc_format_decimal( $value->total_refund, 2 );
					$this->report_data->total_refunds               += $value->total_refund;
					break;
				case 'line_item' :
					$this->report_data->total_tax_refunded   += ( $value->total_tax * -1 );
					$this->report_data->refunded_order_items += absint( $value->order_item_count );
					$this->report_data->total_refunds        += $value->total_refund;
					break;
			}
		}
======================================================================

i try to check '$this->report_data->partial_refunds' structure, i found partial refund 'item_type' is null.
 'item_type' is null, woocommerce is just pass this code, and partial refunds price value is not apply.
my suggest is add default: code in switch syntax like this( i don't know it is right or wrong )

/woocommerce/includes/admin/reports/class-wc-report-sales-by-date.php : 293 Line.
======================================================================
		foreach ( $this->report_data->partial_refunds as $key => $value ) {
			switch ( $value->item_type ) {
				case 'shipping' :
					$this->report_data->total_shipping_tax_refunded += ( $value->total_shipping_tax * -1 );
					$this->report_data->total_shipping_refunded     += wc_format_decimal( $value->total_refund, 2 );
					$this->report_data->total_refunds               += $value->total_refund;
					break;
				case 'line_item' :
					$this->report_data->total_tax_refunded   += ( $value->total_tax * -1 );
					$this->report_data->refunded_order_items += absint( $value->order_item_count );
					$this->report_data->total_refunds        += $value->total_refund;
					break;
				default:
					$this->report_data->total_tax_refunded   += ( $value->total_tax * -1 );
					$this->report_data->refunded_order_items += absint( $value->order_item_count );
					$this->report_data->total_refunds        += $value->total_refund;
					break;

			}
		}
======================================================================

but, i don't know many thing woocommerce coding style and goals. 
please, someone check this code. 

Thanks.

**Comment by mikejolley** [comment]
No other case should be needed here - only line items and shipping refunds should be tallied up, not the refund lines themselves and line items without a type.

Please note on these reports, the order values will remain unchanged if the refund was done in a different period. I.e. if I have an order last month for 10000, refund 1000 this month, and view last months report, it will still report 10000. This month it would report -1000.

If you do the refund in the same period, it will be shown. Here is an example I just prepared to see if the above really was an issue:

https://dl.dropboxusercontent.com/s/hm03xbffti8lpl3/2016-01-04%20at%2010.28.png?dl=0

The report appears fine in 2.4.x and 2.5.x beta. This was the order in my test case:

https://dl.dropboxusercontent.com/s/2q5c3o9mmdrf0ci/2016-01-04%20at%2010.30.png?dl=0

**Comment by telilbo** [comment]
Hi i'm Alan.

https://youtu.be/QDc2tRVqMbQ

Could you please, check this movie? 
I try to install wp4.4 + wc2.4.12 and test again.
but not counted refund price. 

Thanks

**Comment by mikejolley** [comment]
@telilbo confirmed in 2.4, but fixed in 2.5. That release is out in ~2 weeks.

**Comment by telilbo** [comment]
okay.. thanks
