### ISSUE TITLE
Product Categories not appearing in menu admin

### ISSUE THREAD

**Issue by ChangePlaces** [woothemes/woocommerce#9936]
I didn't know it was possible to add product categories to a menu until I saw it in the customiser for the storefront theme.

In the admin for building a menu, it isn't possible to add product categories, products, and product tags unlike it is in the theme customiser for storefront. Should it be possible?

**Comment by mikejolley** [comment]
'Screen options' top right of your screen. You need to turn them on.

**Comment by ChangePlaces** [comment]
wow, thank you!
