### ISSUE TITLE
"empty cart" on anonymous safari

### ISSUE THREAD

**Issue by starfrosch** [woothemes/woocommerce#9944]
Woocommerce 2.4.12
Wordpress 4.4 Multisite
WP Super Cache
LEMP Stack
OS X El Capitan
Windows 10
Android 5 Browser / Firefox Mobile

When I add a product to the cart with an anonymous user using safari under OS X el capitan / Android 5 Browser / Firefox Mobile, there is no product in the cart "Your cart is currently empty." (Cache and Cookies clear did not help).

I deactivated all Wordpress Plugins incl. WP Super Cache without success.
With Chrome and Firefox under OS X and Windows 10 the cart works as expected. The cart also works for logged in users.

Can you reproduce it? https://starfrosch.com/shop/

**Comment by mikejolley** [comment]
Yes I can; it will likely be 1 of 2 things.

1. Even with super cache plugin disabled, it can still leave files in place and leave wp cache on. Enable the plugin, but disable caching within it's settings.
2. Check with the hosting provider to see if varnish cache or any other server level cache is enabled.

Cart should be excluded from cache rules. 

https://docs.woothemes.com/document/configuring-caching-plugins/

**Comment by starfrosch** [comment]
Thanks you for looking into it.

1. I now have disabled WP Super Cache Plugin from within it's settings and deleted the cache files on the server ( /wp-content/cache/ is empty)
2. I'm hosting on my own and there is no varnish or server level cache implemented on nginx for wordpress

I also excluded /cart/, /checkout/, /my-account/ from caching from within the nginx config and WP Super Cache config.

When it would be server side caching related, I expected to have the problem with all kind of browsers or am I wrong?

**Comment by mikejolley** [comment]
Most setups I've come across have (in the case of varnish) rules which exclude certain cookies, such as logged in user cookies. Thats why I expect it affects guests only.

**Comment by starfrosch** [comment]
Thanks again for your help. I can follow that, but I have totally disabled caching on the wordpress and nginx side. It also works for guests on Firefox and Chrome, that's why I'm not searching for a caching problem. If it would be a server caching problem, it affected all browser on all os.

**Comment by mikejolley** [comment]
I'm using Chrome as a guest and I encountered the issue on your store only.

**Comment by greguly** [comment]
I get guest empty cart with Firefox on Ubuntu.

**Comment by mikejolley** [comment]
Screams server caching to me - I just went back to the page and saw an 'added to cart' notice. Shouldn't be there unless its cached from previous.

**Comment by starfrosch** [comment]
I noticed this behaviour with the "added to cart" notice too, but I can't find any server caching activated (not wp super cache, no varnish).

I can reproduce the failure under Ubuntu with Chrome and Firefox.
I can reproduce the failure under OS X with Safari.
I can reproduce the failure with Windows 10 Firefox/Chrome.

I don't have the failure with OS X Firefox/Chrome.

Strange things happen.

**Comment by mikejolley** [comment]
What host is it anyway? Checked phpinfo?

**Comment by starfrosch** [comment]
It's a Digitalocean VPS. I don't find any strange things in https://starfrosch.com/phpinfo.php

**Comment by starfrosch** [comment]
I had the following in my wp-config.php

define('ADMIN_COOKIE_PATH', '/');
define('COOKIEPATH', '');
define('SITECOOKIEPATH', '');

Removing it solved all problems. Thank you so much for all the help and hints!
