### ISSUE TITLE
Products displayed only as on SALE

### ISSUE THREAD

**Issue by highacid** [woothemes/woocommerce#9953]
Hello,

I am running multiple woocommerce websites, one of them at http://sr-isoliertechnik.ch has issues while creating new products, the display of the products and the price will always appear as on SALE, no matter what type of product is added, I also tried to duplicate a working product with price and it did not helped. Here is the product detail: http://prntscr.com/9mb2pk here how is displayed http://prntscr.com/9mb329 if anyone can provide some feedback to this would be great.
<img width="669" alt="screen shot 2016-01-05 at 11 07 36" src="https://cloud.githubusercontent.com/assets/6324047/12112563/a4698930-b39d-11e5-833f-575b661fec12.png">
<img width="368" alt="screen shot 2016-01-05 at 11 07 48" src="https://cloud.githubusercontent.com/assets/6324047/12112566/a4abbc2e-b39d-11e5-8019-d4cc9886cc25.png">
<img width="862" alt="screen shot 2016-01-05 at 11 13 18" src="https://cloud.githubusercontent.com/assets/6324047/12112567/a4ad6dc6-b39d-11e5-9b1f-7ad2173f8d35.png">
<img width="1001" alt="screen shot 2016-01-04 at 10 34 54" src="https://cloud.githubusercontent.com/assets/6324047/12112569/a4b12d9e-b39d-11e5-9d26-2a03740a03cc.png">
<img width="570" alt="screen shot 2016-01-04 at 10 35 54" src="https://cloud.githubusercontent.com/assets/6324047/12112565/a4a9e5ac-b39d-11e5-8a11-e75581e142e8.png">
<img width="1211" alt="screen shot 2016-01-04 at 10 53 24" src="https://cloud.githubusercontent.com/assets/6324047/12112568/a4aead12-b39d-11e5-8201-1ebb429cf9b0.png">
<img width="1302" alt="screen shot 2016-01-04 at 10 53 33" src="https://cloud.githubusercontent.com/assets/6324047/12112564/a48588c4-b39d-11e5-9f2e-6d80b0bb88b3.png">

Here is the woocommerce log:

### WordPress Environment ###

Home URL: http://sr-isoliertechnik.ch
Site URL: http://sr-isoliertechnik.ch
WC Version: 2.4.12
Log Directory Writable: ✔ /home/srisoliertechnik/public_html/wp-content/uploads/wc-logs/
WP Version: 4.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.16
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: ✔
MySQL Version: 5.5.5
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.12
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (7) ###

Akismet: by Automattic – 3.1.7
Envato WordPress Toolkit: by Envato – 1.7.3
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Redirection: by John Godley – 2.4.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
WooCommerce PDF Invoice: by RightPress – 3.0
WooCommerce: by WooThemes – 2.4.12

### Settings ###

Force SSL: –
Currency: CHF (CHF)
Currency Position: right_space
Thousand Separator: `
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #741 - /shop/
Cart: #742 - /warenkorb/
Checkout: #743 - /kasse/
My Account: #744 - /mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Enfold
Version: 3.4.7
Author URL: http://www.kriesi.at
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/issues/9698
