### ISSUE TITLE
some variable is undifened

### ISSUE THREAD

**Issue by Nugrah** [woothemes/woocommerce#9983]
hi, i use check your 2.5.0 rc version, on our theme, when i go to the wishlist, i have found this error in the add to cart link `Undefined variable: quantity in .....plugins\woocommerce\templates\loop\add-to-cart.php on line 27` and `Undefined variable: class in .....plugins\woocommerce\templates\loop\add-to-cart.php on line 30`, may i know there is error from the yith wishlist plugin or not? because i have to try change to the other theme and still same, thankss

**Comment by mikejolley** [comment]
Yes; please make them aware. If they use the woocommerce_template_loop_add_to_cart function instead of calling the template file directly, those variables will be yet.

@dymissy ?

**Comment by dymissy** [comment]
@mikejolley I'm no longer working at YITH anymore so I can't help you.

@antoscarface could be the man you are looking for.

**Comment by antoscarface** [comment]
I'm looking for it, I'll let you know as soon as possible. Thank you for reporting!

**Comment by Nugrah** [comment]
yeahh thank you for all @mikejolley @antoscarface
