### ISSUE TITLE
backorders can't be set to true through the api

### ISSUE THREAD

**Issue by SeriousJester** [woothemes/woocommerce#9984]
While trying to add products using the api. We noticed that we couldn't add products with backorders set to true.
When we set it to true it would show up as 'notify'

After trying some different stuff we scanned through the api code and found that the if statement for backorders in "class-wc-api-products" wasn't checking for type.

<addr>if ('notify' == true)</addr>
will evaluate as true which it shouldn't, thus setting backorders to notify instead of true. using === instead of == would fix this problem.

![woocommerce_bug](https://cloud.githubusercontent.com/assets/16572698/12138022/d4d03bd8-b455-11e5-82b5-284d452e20eb.png)

This is also the case on line 1366 with variation backorders (and maybe some others i haven't checked them all)

**Comment by mikejolley** [comment]
This is fixed in master.
