### ISSUE TITLE
Submitting order on checkout page only blocks ui of form not whole page

### ISSUE THREAD

**Issue by gerdneuman** [woothemes/woocommerce#9987]
I do not know how the blockui is implemented (maybe http://jquery.malsup.com/block/#demos ?). But I noticed that if a customer submits an order, then the page gets a greyish overlay and seems to be blocked until the page is reloaded. 

This is good behaviour to prevent that the user does not click anymore accicentially somewhere until payment and order transaction s have been done and the user is forwarded to the `order-received` page.

But I noticed that the complete `<header>...</header>` area (all menus) is not being blocked so that links there are still clickable there, happens on all sites with a sticky header. Would be better if this could be blocked as well and not only the `<form name="checkout" class="checkout woocommerce-checkout" ...>` element. 

Reproducable also on http://demo2.woothemes.com/storefront/checkout/ (though there is no sticky header)

**Comment by mikejolley** [comment]
This is intended - we are only interested in preventing the place order button/order review area links etc from being clicked. Prevents things like placing orders twice. If the user wants to navigate away, thats up to them, but accidental clicking of place order can be a problem.
